### ISSUE TITLE
referentialIntegrity=prisma: Delete parent relation failing when using composite id

### ISSUE THREAD

**Issue by appsbytom** [prisma/prisma#10000]
### Bug description

I am trying to move to referential actions when deleting but get failures. If i don't add anything to `onDelete` the event gets deleted but not the sessions (whats the default action when using `referentialIntegrity = "prisma"`?), adding `onDelete: Cascade` I get an error `FailedPrecondition desc = Operand should contain 2 column(s) (errno 1241)`. 

Looking at the query logged (shown below) it looks like only the `id` is passed to delete the session when it needs the `id` and `event_id` because of the composite id

```DELETE FROM `sessions` WHERE (`sessions`.`id`,`sessions`.`event_id`) IN ((?),(?))```

### How to reproduce
```js
const prisma = new PrismaClient({
  log: ['query', 'info', 'warn', 'error'],
})

// step 2 create snippet
prisma.event.create({
  data: {
    id: 'prisma',
    name: 'prisma-bug',
    sessions: {
      createMany: {
        data: [
          { id: 'g', name: 'github' },
          { id: 'i', name: 'issue' },
        ]
      }
    }
  }
})

//step 3 delete snippet
prisma.event.delete({ where: { id: 'prisma' }})
```
1. Create the DB with Prisma Migrate using the provided Prisma schema
2. Create an event with sessions
3. Delete an event, see the error (recommend adding logging to client)

### Expected behavior

When using cascade on a model with a composite id the delete should use all parameters of the composite id

### Prisma information

```prisma
datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  shadowDatabaseUrl    = env("SHADOW_DATABASE_URL")
  referentialIntegrity = "prisma"
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

model Event {
  id          String    @id
  name        String
  sessions    Session[]

  @@map("events")
}

model Session {
  id          String
  name        String
  event       Event    @relation(fields: [eventId], references: [id], onDelete: Cascade)
  eventId     String   @map("event_id")

  @@id([id, eventId])
  @@map("sessions")
}
```

### Environment & setup

- OS: Windows
- Database: PlanetScale
- Node.js version: 15.3.0

### Prisma Version

```
prisma                  : 3.2.1
@prisma/client          : 3.2.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c
Studio                  : 0.435.0
Preview Features        : referentialIntegrity
```

**Comment by TheTomTom3901** [comment]
I have added reproduce steps (I had commented them by accident) and removed fields from the schema that didn't relate to the issue. Any other information needed @janpio ?

**Comment by janpio** [comment]
No, that looks good. Someone on our side will have to try this reproduction and see if we can confirm it. I would not be surprised if that was the case - thanks for all the information @TheTomTom3901!

**Comment by janpio** [comment]
I can reproduce and confirm this problem in 3.7.0:

```
C:\Users\Jan\Documents\throwaway\10000>node script.js
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\10000\.env +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\10000\.env +6ms
  prisma:client clientVersion: 3.7.0 +0ms
  prisma:client clientEngineType: library +1ms
  prisma:client:libraryEngine internalSetup +0ms
  prisma:client Prisma Client call: +14ms
  prisma:client prisma.event.create({
  prisma:client   data: {
  prisma:client     id: 'prisma',
  prisma:client     name: 'prisma-bug',
  prisma:client     sessions: {
  prisma:client       createMany: {
  prisma:client         data: [
  prisma:client           {
  prisma:client             id: 'g',
  prisma:client             name: 'github'
  prisma:client           },
  prisma:client           {
  prisma:client             id: 'i',
  prisma:client             name: 'issue'
  prisma:client           }
  prisma:client         ]
  prisma:client       }
  prisma:client     }
  prisma:client   }
  prisma:client }) +3ms
  prisma:client Generated request: +6ms
  prisma:client mutation {
  prisma:client   createOneEvent(data: {
  prisma:client     id: "prisma"
  prisma:client     name: "prisma-bug"
  prisma:client     sessions: {
  prisma:client       createMany: {
  prisma:client         data: [
  prisma:client           {
  prisma:client             id: "g"
  prisma:client             name: "github"
  prisma:client           },
  prisma:client           {
  prisma:client             id: "i"
  prisma:client             name: "issue"
  prisma:client           }
  prisma:client         ]
  prisma:client       }
  prisma:client     }
  prisma:client   }) {
  prisma:client     id
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: false +31ms
  prisma:client:libraryEngine Search for Query Engine Library in C:\Users\Jan\Documents\throwaway\10000\node_modules\.prisma\client +2ms
  prisma:client:libraryEngine loadEngine using C:\Users\Jan\Documents\throwaway\10000\node_modules\.prisma\client\query_engine-windows.dll.node +1ms
  prisma:client:libraryEngine library starting +10ms
prisma:info Starting a mysql pool with 9 connections.
  prisma:client:libraryEngine library started +973ms
prisma:query BEGIN
prisma:query INSERT INTO `10000`.`events` (`id`,`name`) VALUES (?,?)
prisma:query INSERT INTO `10000`.`sessions` (`id`,`event_id`,`name`) VALUES (?,?,?), (?,?,?)
prisma:query SELECT `10000`.`events`.`id`, `10000`.`events`.`name` FROM `10000`.`events` WHERE `10000`.`events`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
{ id: 'prisma', name: 'prisma-bug' }
  prisma:client Prisma Client call: +2s
  prisma:client prisma.event.delete({
  prisma:client   where: {
  prisma:client     id: 'prisma'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +1ms
  prisma:client mutation {
  prisma:client   deleteOneEvent(where: {
  prisma:client     id: "prisma"
  prisma:client   }) {
  prisma:client     id
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +1ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +960ms
prisma:query BEGIN
prisma:query SELECT `10000`.`events`.`id`, `10000`.`events`.`name` FROM `10000`.`events` WHERE `10000`.`events`.`id` = ? LIMIT ? OFFSET ?
prisma:query SELECT `10000`.`sessions`.`id`, `10000`.`sessions`.`event_id` FROM `10000`.`sessions` WHERE (1=1 AND `10000`.`sessions`.`event_id` IN (?))
prisma:query DELETE FROM `10000`.`sessions` WHERE (`10000`.`sessions`.`id`,`10000`.`sessions`.`event_id`) IN ((?),(?))
prisma:query ROLLBACK
  prisma:client:fetcher Error: Error occurred during query execution:
  prisma:client:fetcher ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1241, message: "vttablet: rpc error: code = FailedPrecondition desc = Operand should contain 2 column(s) (errno 1241) (sqlstate 21000) (CallerID: unsecure_grpc_client): Sql: \"delete from sessions where (sessions.id, sessions.event_id) in (:v1, :v2)\", BindVars: {#maxLimit: \"type:INT64 value:\\\"100001\\\"\"v1: \"type:VARBINARY value:\\\"g\\\"\"v2: \"type:VARBINARY value:\\\"i\\\"\"}", state: "21000" })) })
  prisma:client:fetcher     at prismaGraphQLToJSError (C:\Users\Jan\Documents\throwaway\10000\node_modules\@prisma\client\runtime\index.js:35963:10)
  prisma:client:fetcher     at Object.request (C:\Users\Jan\Documents\throwaway\10000\node_modules\@prisma\client\runtime\index.js:36324:17)
  prisma:client:fetcher     at async cb (C:\Users\Jan\Documents\throwaway\10000\node_modules\@prisma\client\runtime\index.js:38658:26)
  prisma:client:fetcher     at async main (C:\Users\Jan\Documents\throwaway\10000\script.js:28:17) +0ms
PrismaClientUnknownRequestError:
Invalid `prisma.event.delete()` invocation in
C:\Users\Jan\Documents\throwaway\10000\script.js:28:42

  25 console.log(event)
  26
  27 //step 3 delete snippet
→ 28 let deleted = await prisma.event.delete(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1241, message: "vttablet: rpc error: code = FailedPrecondition desc = Operand should contain 2 column(s) (errno 1241) (sqlstate 21000) (CallerID: unsecure_grpc_client): Sql: \"delete from sessions where (sessions.id, sessions.event_id) in (:v1, :v2)\", BindVars: {#maxLimit: \"type:INT64 value:\\\"100001\\\"\"v1: \"type:VARBINARY value:\\\"g\\\"\"v2: \"type:VARBINARY value:\\\"i\\\"\"}", state: "21000" })) })
    at cb (C:\Users\Jan\Documents\throwaway\10000\node_modules\@prisma\client\runtime\index.js:38692:17)
    at async main (C:\Users\Jan\Documents\throwaway\10000\script.js:28:17) {
  clientVersion: '3.7.0'
}
  prisma:client:libraryEngine hookProcess received: exit +840ms
  prisma:client:libraryEngine runBeforeExit +23ms
```

I used the schema you provided:
```prisma
datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

model Event {
  id       String    @id
  name     String
  sessions Session[]

  @@map("events")
}

model Session {
  id      String
  name    String
  event   Event  @relation(fields: [eventId], references: [id], onDelete: Cascade)
  eventId String @map("event_id")

  @@id([id, eventId])
  @@map("sessions")
}

```


And this reproduction script:

```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient({
  log: ['query', 'info', 'warn', 'error'],
})

// A `main` function so that we can use async/await
async function main() {
    
  // step 2 create snippet
  let event = await prisma.event.create({
    data: {
      id: 'prisma',
      name: 'prisma-bug',
      sessions: {
        createMany: {
          data: [
            { id: 'g', name: 'github' },
            { id: 'i', name: 'issue' },
          ]
        }
      }
    }
  })
  console.log(event)
  
  //step 3 delete snippet
  let deleted = await prisma.event.delete({ where: { id: 'prisma' }})
  console.log(deleted)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

**Comment by janpio** [comment]
Here are the failing queries with their parameters:
```
Query:  BEGIN
Params: []
Query:  SELECT `10000`.`events`.`id`, `10000`.`events`.`name` FROM `10000`.`events` WHERE `10000`.`events`.`id` = ? LIMIT ? OFFSET ?
Params: ["prisma",1,0]
Query:  SELECT `10000`.`sessions`.`id`, `10000`.`sessions`.`event_id` FROM `10000`.`sessions` WHERE (1=1 AND `10000`.`sessions`.`event_id` IN (?))
Params: ["prisma"]
Query:  DELETE FROM `10000`.`sessions` WHERE (`10000`.`sessions`.`id`,`10000`.`sessions`.`event_id`) IN ((?),(?))
Params: ["g","i"]
Query:  ROLLBACK
Params: []
```

which makes the failing query:
`DELETE FROM `10000`.`sessions` WHERE (`10000`.`sessions`.`id`,`10000`.`sessions`.`event_id`) IN (("g"),("i"));` and invalid indeed

**Comment by laybacktrade** [comment]
Hey there! I'm facing the same issue. Any updates on this?

**Comment by jkomyno** [comment]
Hi @appsbytom, while I was able to reproduce the issue with `prisma@3.2.1`, this bug should be gone by now (as tested locally with `prisma@4.1.1`).
I'm closing this issue now. Please let us know whether this is indeed fixed, and if it's still a problem we will reopen this issue!

**Comment by janpio** [comment]
@laybacktrade Can you please also take a look to confirm this is fixed? Thanks.
