### ISSUE TITLE
Crash on multiline defaults introspection on MSSQL

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#10123]
Error: [libs/sql-schema-describer/src/mssql.rs:315:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `\r\n/****** Object:  Default [dbo].[Default_0]    Script Date: 04/02/2009 17:47:36 ******/\r\ncreate default [dbo].[Default_P] as 'P'\r\n\r\n\r\n`" 

Command: `prisma db pull`
Version: `3.3.0`
Binary Version: `33838b0f78f1fe9052cf9a00e9761c9dc097a63c`
Report: https://prisma-errors.netlify.app/report/13560 
OS: `x64 linux 4.19.128-microsoft-standard`

JS Stacktrace:
```
Error: [libs/sql-schema-describer/src/mssql.rs:315:30] called `Result::unwrap()` on an `Err` value: "Couldn't parse default value: `\r\n/****** Object:  Default [dbo].[Default_0]    Script Date: 04/02/2009 17:47:36 ******/\r\ncreate default [dbo].[Default_P] as 'P'\r\n\r\n\r\n`"
    at ChildProcess.<anonymous> (/server/node_modules/prisma/build/index.js:45792:30)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
```

Rust Stacktrace:
```
   0: user_facing_errors::Error::new_in_panic_hook
   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:626:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
   6: core::panicking::panic_fmt
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
   7: core::result::unwrap_failed
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
   8: <sql_schema_describer::mssql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::{{closure}}::{{closure}}
   9: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  15: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  16: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  17: introspection_engine::main::{{closure}}
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: introspection_engine::main
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: std::rt::lang_start::{{closure}}
  22: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
      std::panicking::try
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
      std::panic::catch_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
      std::panicking::try::do_call
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
      std::panicking::try
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
      std::panic::catch_unwind
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
      std::rt::lang_start_internal
             at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
  23: std::rt::lang_start
  24: __libc_start_main
  25: <unknown>

```

**Comment by pimeys** [comment]
Cannot reproduce. Created a table with this same default value, it introspects just fine.

I suspect this might have something to do with an old SQL Server version and some weird collation...

**Comment by tomhoule** [comment]
Another instance: https://prisma-errors.netlify.app/report/13696

**Comment by janpio** [comment]
We still do not know how to make Introspection crash because of the existence of such an index. 
We need a SQL dump of a database that reproduces this behavior to replicate this behavior.

(For us the default is just ignored and not represented in the Prisma schema: https://github.com/prisma/prisma/issues/12150)

**Comment by janpio** [comment]
Reproduced: The line breaks cause this, see https://github.com/prisma/prisma/issues/24275

@tomhoule This issue here is the only one that got it right and identified "multiline" as the cause, unfortunately no one tried to use that to reproduce the problem before. You were soooo close all this time.

**Comment by tomhoule** [comment]
Oh wow, I wouldn't have come up with the comment in the default definition. Glad the mystery is solved :)
