### ISSUE TITLE
To elaborate error message for Prisma Migrate crashes for SQL Server

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#10138]
For example when the user does not have the right to create a new database that does not exist (as in our internal db-provision SQL Server connection strings):

```
C:\Users\Jan\Documents\throwaway\9933>npx prisma db push

Error: Error: Migration engine error:
Performing a TLS handshake
Trusting the server certificate without validation.
TLS handshake successful
Turning TLS off after a login. All traffic from here on is not encrypted.
Database change from 'master' to 'master'
Changed database context to 'master'.
SQL collation change from None to windows-1252/windows-1252
Microsoft SQL Server version 3910074383
Packet size change from '4096' to '4096'
Starting a mssql connection.
CREATE DATABASE permission denied in database 'master'.
CREATE DATABASE permission denied in database 'master'.

    at createDatabase (C:\Users\Jan\Documents\throwaway\9933\node_modules\prisma\build\index.js:46437:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ensureDatabaseExists (C:\Users\Jan\Documents\throwaway\9933\node_modules\prisma\build\index.js:101091:9)
    at async Object.parse (C:\Users\Jan\Documents\throwaway\9933\node_modules\prisma\build\index.js:102786:28)
    at async main (C:\Users\Jan\Documents\throwaway\9933\node_modules\prisma\build\index.js:105393:18)
```

**Comment by JoaoG23** [comment]
For me the error 
of Turning TLS off after a login. All traffic from here on is not encrypted ;
it error was resolved for me with disenable 'integratedSecurity=true;' for 'integratedSecurity=false;' in the DATABASE_URL
