### ISSUE TITLE
Prisma client throws error with no code or message

### ISSUE THREAD

**Issue by goleary** [prisma/prisma#10141]
### Bug description

We have a production service that uses prisma & catches an error thrown from prisma that looks like this:

```
{
  clientVersion: "3.4.1"
}
```

### How to reproduce

This is the query that triggers the error to be thrown:
```ts
try{
const startDate = new Date(Date.now() - 24 * 60 * 60 * 1000);
const limit = 100;

const query = Prisma.sql`
  select url, count(*) as count
  from (
    select distinct "Status"."userIdStr", "Status".url
    from "Status"
    where "Status"."createdAt" > (to_timestamp(${startDate.getTime()} / 1000.0))
        and "Status".url is not null
    ) as distinct_user_url_statuses
  group by url
  having distinct_user_url_statuses.count > 1
  order by count desc  
  limit ${limit}
`;
const data = await prisma.$queryRaw<{ url: string; count: number }[]>(query);
} catch (error){
  // log error
}
```

### Expected behavior

an error to be thrown with a message & code that can help me debug what's going on

### Prisma information

prisma & client 3.4.1

prisma.schema:
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  idStr String @id 
  name String?
  statuses Status[]
  follows Follow[] @relation("Follower")
  followers Follow[] @relation("Followee")
}

model Follow {
  id Int @id @default(autoincrement())
  userIdStr String
  user User @relation("Follower", fields: [userIdStr], references: [idStr])
  followeeIdStr String
  followee User @relation("Followee", fields: [followeeIdStr], references: [idStr])
  @@unique([userIdStr, followeeIdStr])
}

model Status {
  idStr String @id
  createdAt DateTime
  userIdStr String
  retweetCount Int @default(0)
  favoriteCount Int @default(0)
  user User? @relation(fields: [userIdStr], references: [idStr])
  url String?
  rawJson Json?
}
```

### Environment & setup

- GCP Cloud Function
- Database: PostgreSQL 13
- Node.js version: node v14

### Prisma Version

from my local dev environment which is not what's running in the cloud/prod:
```
Environment variables loaded from .env
prisma                  : 3.4.1
@prisma/client          : 3.4.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
```

**Comment by goleary** [comment]
switched to use `pg` & now this error is thrown:
```
{
address: "..."
code: "ECONNREFUSED"
errno: -111
port: 7516
syscall: "connect"
}
```

**Comment by jsw** [comment]
I was just noticing some odd behavior when updating prisma from 3.4.0 to 3.4.1. My nest app would exit on startup with no error message. Didn't look into it too deeply yet. Might be related. See if 3.4.0 works for you.

**Comment by goleary** [comment]
I originally had this problem with 3.3.0

Turns out I had a misconfigured GCP cloud function env variable that was being used instead of the correct connection string...doh!

Too bad I had to switch to using `pg` to get an actual error message that helped me track down the issue...

**Comment by samparmenter** [comment]
Having same issue here. No errors generated on 3.4.1,  it just hung at "starting nest application". Reverting to 3.4.0 fixed it.

**Comment by gheorghemolnar** [comment]
I'm experiencing also an issue concerning prisma client erorr message thrown when creating a record with missing a required field: the error is an object with constructor name = 'PrismaClientValidationError', it  has an error message, but no code.

Context:
MacOS BigSur 11.6
“Prisma”: “^3.4.0"

**Comment by koprivajakub** [comment]
I am experiencing the very same behavior.

The application quits silently while connecting to pgql database via

```ts
try {
    await prisma.$connect() // gets killed
} catch (e) {
    throw e; // does not happen
}
```

Context:
```
macOS Monterey
Prisma: 3.4.1, 3.4.0
```

fixed by downgrading to `3.3.0`

unfortunatelly `3.3.0` is not supported by the latest `typegraphql-prisma`

**Comment by janpio** [comment]
@koprivajakub Can you please open a new issue about this? Seems unrelated to me but we definitely want to debug and understand this. Thanks!

@gheorghemolnar That also sounds unrelated to me, and needs its own issue. Please make sure to fill the issue template so we have all the information to reproduce. Thanks!

@samparmenter @jsw Exit on startup with no error message or hanging _also_ seem unrelated to me - please open a new issue and fill all the information. 3.4.0 to 3.4.1 should definitely not cause any of this as almost nothing changed, so we _definitely_ want to look into this as soon as possible. Thanks!

**Comment by janpio** [comment]
And finally to @goleary:

> {
>   clientVersion: "3.4.1"
> }

Yep, that is a useless error message indeed.



> Turns out I had a misconfigured GCP cloud function env variable that was being used instead of the correct connection string...doh!

Can you share the misconfiguration you had? Otherwise it will be hard to reproduce the problem with the information from your first message here I guess. And as that error message is indeed super useless, and the `pg` one makes _much_ more sense, we definitely should understand, reproduce and fix that so others do not have to go through the same process you went through.

**Comment by goleary** [comment]
Thanks for looking into this @janpio 

Because of how environment variables are handled in Firebase Functions, this is how we initialize Prisma:
```ts
// src/clients/prisma.ts

import * as functions from 'firebase-functions';
import { PrismaClient } from '@prisma/client';

export type { ... } from '@prisma/client';

// .env file not present on the server so we explicitly pass in the database_url
// during initialization.
const prisma = process.env.DATABASE_URL
  ? new PrismaClient()
  : new PrismaClient({
      datasources: {
        db: {
          url: functions.config().prisma.database_url,
        },
      },
    });

export default prisma;
```
Locally I sometimes dev with a `.env` file with the connection string (although using the firebase functions emulator, `functions.config().prisma.database_url` will be present).

On the server `process.env.DATABASE_URL` should not be set. The source of my issue was that `process.env.DATABASE_URL` was set to an old (no longer provisioned) database for a specific cloud function which resulted in the connection being refused.

We don't own the IP of the old database, it was (de)provisioned using https://railway.app.

**Comment by janpio** [comment]
Can you maybe share that decommissioned connection string (maybe also in private to jan@prisma.io)? Then we should be able to directly reproduce the behavior with your init code and the query code you posted before.

**Comment by goleary** [comment]
I emailed you @janpio

**Comment by janpio** [comment]
I turned the script you shared into a minimal js file:
```js
const { PrismaClient, Prisma } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {

  try {
    const startDate = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const limit = 100;

    const query = Prisma.sql`
      select url, count(*) as count
      from (
        select distinct "Status"."userIdStr", "Status".url
        from "Status"
        where "Status"."createdAt" > (to_timestamp(${startDate.getTime()} / 1000.0))
            and "Status".url is not null
        ) as distinct_user_url_statuses
      group by url
      having distinct_user_url_statuses.count > 1
      order by count desc  
      limit ${limit}
    `;
    const data = await prisma.$queryRaw(query);
  } catch (error) {
    // log error
    console.log(error)
  }

}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

With the connection string you shared via email, I get a pretty ok error though:
```
C:\Users\Jan\Documents\throwaway\10141>node script.js
PrismaClientInitializationError:
Invalid `prisma.queryRaw()` invocation:


  Can't reach database server at `containers-us-west-9.railway.app`:`8056`

Please make sure your database server is running at `containers-us-west-9.railway.app`:`8056`.
    at cb (C:\Users\Jan\Documents\throwaway\10141\node_modules\@prisma\client\runtime\index.js:38508:17)
    at async main (C:\Users\Jan\Documents\throwaway\10141\script.js:25:18) {
  clientVersion: '3.4.2',
  errorCode: undefined
}
(node:1264) UnhandledPromiseRejectionWarning: Error: Can't reach database server at `containers-us-west-9.railway.app`:`8056`

Please make sure your database server is running at `containers-us-west-9.railway.app`:`8056`.
    at C:\Users\Jan\Documents\throwaway\10141\node_modules\@prisma\client\runtime\index.js:36260:21
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Am I missing something?

**Comment by gheorghemolnar** [comment]
@janpio thank  you for looking into this.
I've created the new issue with requested infos => https://github.com/prisma/prisma/issues/10221

**Comment by goleary** [comment]
@janpio Thanks for putting together that script.

When I run the same locally I see that error in the console, but because this is running on GCP cloud functions, it's the error object that we log and can actually see.


When I modify your script slightly (the catch block) to add this:
```
catch (error) {
  console.log('keys: ', Object.keys(error));
  console.log('error.errorCode: ', error.errorCode);
  console.error(JSON.stringify(error, null, 2));
}
```
I get this output:
```
keys:  [ 'clientVersion', 'errorCode' ]
error.errorCode:  undefined
{
  "clientVersion": "3.4.1"
}
```
I would expect this error object to contain information that is useful for me debugging the error.

**Comment by koprivajakub** [comment]
> @koprivajakub Can you please open a new issue about this? Seems unrelated to me but we definitely want to debug and understand this. Thanks!

I was trying to simulate it on a simple debuggable repository. It actually works there correctly, which made me think. I cleaned the yarn cache, deleted node_modules, reinstalled dependencies and now it seems to work without a single change in the code. Not sure what was causing this. I consider this to be resolved for now 🤷‍♂️ BTW: I am using `yarn 3.1.0` with `nodeLinker: node-modules` If I will encounter it again I will open another issue. Thanks for the answer anyway.

**Comment by janpio** [comment]
> I get this output:

Ok that is interesting behavior - the exception _message_ does not seem to be part of the object really? Probably some JS behavior? Will need to understand that.

> I would expect this error object to contain information that is useful to me while attempting to debug the error.

Ok, that we totally agree - and that for example the `errorCode` is empty here is bad - as this should really map to one of the known errors of Prisma.

So we have 2 issues here:
- Unexpectedly there is no key for any error _message_ in the `error` object
- The `errorCode` is undefined

**Comment by deltorosalazar** [comment]
@janpio Hi Jan, any updates on this one?

**Comment by gustavo-maurina** [comment]
Facing the same issue, it bothers me that it makes error handling functions to use more lines than it should and harder to read.

**Comment by raiseandfall** [comment]
Facing the same issue here, running Prisma with Serverless and Lambdas with an API Gateway on AWS.

**Comment by goleary** [comment]
Hey @janpio any update here?

I'd love to use Prisma on my projects, but if I have 0 visibility into errors that I encounter then it's a non-starter...

**Comment by janpio** [comment]
No, and update would manifest itself in a message in this comment thread. We are aware of the problem, and will try to reproduce and then potentially fix when we are done with other, higher priority work.

**Comment by rj-xy** [comment]
@goleary do you use a transpiling step?
if so, does using **then/catch** work for you?

---

I had the same issue, but my case may not be the same for everyone.
I am using Babel to transpile JS for node.

What I noticed was if I **then/catch** instead of **async/await** I got the full error (not just _clientVersion_)

I noticed when I debugged in the catch block, there was a `_context` object, and the `t0` actually had the error - this seems to be because I was missing a Babel plugin or some polyfill wasn't added to the output.

---

### Getting async/await working

So the fix that worked for me was to configure Babel to target my current version of Node (LTS 16.x), which seems to be able to handle whatever Babel is transpiling now.

`.babelrc` is now:
```
{
    "presets": [["@babel/env", { "targets": { "node": "current" } }]],
    "plugins": ["@babel/plugin-transform-modules-commonjs"]
}
```
The important part is the `{ "targets": { "node": "current" } }`

**Comment by pj-aditya** [comment]
I'm facing the same issue, the error object is different than what's expected. For now, I'm doing this to circumvent the issue:

```
modelRef.createMany({ data, skipDuplicates: true })
                .then((data) => resolve(data))
                .catch((e) => { 
                    handleError(e?.constructor?.name);
                    reject(e)
                })
```

This will give us the error types as given here: [https://www.prisma.io/docs/reference/api-reference/error-reference](url)

Although, I still would prefer having error codes as that would help me handle the error in a better manner.

**Comment by SevInf** [comment]
I could not reproduce it.
Tried with current prisma version, 3.10.0 and 3.4.0 reported here. @rj-xy information strongly points towards that babel being the culprit. I tried transpiling async/await with babel 7.18.0 and 7.0.0 using `@babel/plugin-tranform-regeneration` or `@babel/plugin-transform-async-to-generator` which are the only async/await plugins I am aware of and could not reproduce the issue as well. 

@rj-xy or anyone else experiencing this issue: could you share your babel config, as well as the versions of babel and its plugins used? Thank you.

**Comment by bablukpik** [comment]
When this would be fixed? I'm also getting the same thing instead of the proper error message. I'm using `"@prisma/client": "^4.2.0"`

**Comment by SevInf** [comment]
@bablukpik we would really love if we could fix it, but unfortunately, information posted in this ticket is not enough to pinpoint it. Are you using babel? If yes, could you share you config, babel & its plugin version? If not, could you provide a small repo where we could see the bug happening?

**Comment by janpio** [comment]
@deltorosalazar @goleary @pj-aditya @raiseandfall @gustavo-maurina Can one of you help us out here to get to a reproduction? We are really unclear what is going on here - but need some more information to reproduce and potentially fix. Thanks!

**Comment by gustavo-maurina** [comment]
@janpio on my end, the problem was not exactly coming necessarily from raw queries, I made the issue #11385 specifying my problem. I found a way around it and documented on the issue.

**Comment by bablukpik** [comment]
Hi @SevInf SevInf my issue no longer exists. Thanks

**Comment by janpio** [comment]
Once more @deltorosalazar @goleary @pj-aditya @raiseandfall - can you maybe help us out here to get more information so we have a chance to reproduce this? Thank you.

**Comment by LefanTan** [comment]
I was able to replicate this issue when
1. Run `npx prisma generate` with DATABASE_URL (Connection string A)
2. Change DATABASE_URL to a different connection string (Connection String B)
3. Start an express server that will use Connection string B and run a query

The mismatch of the generated client seems to have caused it for me. Hope it helps

**Comment by LefanTan** [comment]
Happened to me when I entered an invalid connection string, hope it helps

**Comment by whytrno** [comment]
I get same error here, i try to use simple findUniqueOrThrow function like this
`try{
        const user = await prisma.user.findUniqueOrThrow({
            where: {
                id: req.params.id
            }
        })
        res.status(200).json({
            data: user
        })
    }catch(error){
        res.status(400).json({
            data: error
        })
    }`
    
   i get res like this
   `{
  "data": {
    "clientVersion": "4.5.0"
  }
}`

but when i throw(error) or console.log(error), i got like this
`Invalid `prisma.user.findUniqueOrThrow()` invocation:

{
  where: {
    id: '5'
        ~~~
  }
}

Argument id: Got invalid value '5' on prisma.findUniqueUser. Provided String, expected Int.
`

I know that error happend because parameter is not Integer, but its helpfull when its return to client maybe like this, 
error: Got invalid value '5' on prisma.findUniqueUser. Provided String, expected Int.

**Comment by sniper365** [comment]
I am using prisma -v 4.5.0.

I was following the guide [https://planetscale.com/docs/tutorials/connect-nextjs-app](https://planetscale.com/docs/tutorials/connect-nextjs-app)

At first it worked on local and on vercel. But after refactoring I faced this error..
I am very struggling to fix this. But couldn't find the solution yet.

Is there any relation about previous comments? Could you anyone help me?

Thank you

**Comment by goleary** [comment]
Hey @janpio 

using an invalid `DATABASE_URL` I continue getting the error when running this script

index.js
```js
const { PrismaClient, Prisma } = require("@prisma/client");

const prisma = new PrismaClient();

async function main() {
  try {
    const startDate = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const limit = 100;

    const query = Prisma.sql`
      select url, count(*) as count
      from (
        select distinct "Status"."userIdStr", "Status".url
        from "Status"
        where "Status"."createdAt" > (to_timestamp(${startDate.getTime()} / 1000.0))
            and "Status".url is not null
        ) as distinct_user_url_statuses
      group by url
      having distinct_user_url_statuses.count > 1
      order by count desc  
      limit ${limit}
    `;
    const data = await prisma.$queryRaw(query);
  } catch (error) {
    console.log("keys: ", Object.keys(error));
    console.log("error.errorCode: ", error.errorCode);
    console.error(JSON.stringify(error, null, 2));

    console.log("------------------");
    console.log(error);
  }
}

```
here is the output:
```
keys:  [ 'clientVersion', 'errorCode' ]
error.errorCode:  undefined
{
  "clientVersion": "4.5.0"
}
------------------
PrismaClientInitializationError:
Invalid `prisma.$queryRaw()` invocation:


Can't reach database server at `localhost`:`5432`

Please make sure your database server is running at `localhost`:`5432`.
    at RequestHandler.handleRequestError (C:\Users\olear\github\prisma-repro\node_modules\@prisma\client
\runtime\index.js:30879:13)
    at RequestHandler.request (C:\Users\olear\github\prisma-repro\node_modules\@prisma\client\runtime\in
dex.js:30856:12)
    at async Proxy._request (C:\Users\olear\github\prisma-repro\node_modules\@prisma\client\runtime\inde
x.js:31836:16)
    at async main (C:\Users\olear\github\prisma-repro\index.js:23:18) {
  clientVersion: '4.5.0',
  errorCode: undefined
}
```

_If_ the user is able to inspect the console they can see an intelligent error message (below the separator), _but_ if instead the error is being sent to a client (as in @whytrno's example) or relayed using some other method (like the GCP logger) this message is lost as the caught error object does not contain this information. The error object contains only: `{"clientVersion": "4.5.0"}` in the example above which is not particularly useful while debugging.

If you run the same script on your computer does logging out the stringified error object product a different result?

Env info:
node v16.15.0
"prisma": "^4.5.0",
window 11
git bash


also @rj-xy apologies, I missed your question. No I am not using any transpile step in the above script.

**Comment by janpio** [comment]
Ah ok, from that it looks like using `JSON.stringigy` on the error object loses a lot of information vs. just using `console.log` on it. We should be able to reproduce _that_.

**Comment by goleary** [comment]
Yup, when I first created this issue I didn't realize that was what was happening, but the issue can be boiled down to: 

> using JSON.stringigy on the error object loses a lot of information vs. just using console.log on it.

Let me know if you'd like me to update the title of the issue to make it more representative.

**Comment by janpio** [comment]
Yes, that would be neat 👍

**Comment by millsp** [comment]
Reproduction https://github.com/prisma/prisma/pull/16231

**Comment by whytrno** [comment]
Its fixed?

**Comment by millsp** [comment]
Not fixed yet, this is in discussion stage for the moment, I will update this issue once we have made progress.
