### ISSUE TITLE
Prisma does not recover from DB being down on start up

### ISSUE THREAD

**Issue by ivanstanev** [prisma/prisma#10153]
### Bug description

Hey team,

We have an application which runs with Prisma to connect to our Postgres database.
Alongside the application there is a sidecar container running Google's Cloud SQL Proxy.

Prisma connects to the Cloud SQL Proxy, which in turn proxies the connection to our Postgres database hosted on Google Cloud.

Occasionally the Cloud SQL Proxy takes longer to start up, so our application launches first. It then does a database query and Prisma emits an error:
```text
Can't reach database server at `127.0.0.1`:`5432`\n\nPlease make sure your database server is running at `127.0.0.1`:`5432`."
```

The problem is that Prisma never recovers from this. Even if the Cloud SQL Proxy starts shortly after, Prisma keeps throwing the same error over and over, even though the address/port is now reachable and something is listening there.

### How to reproduce

Start your app, ensure the Db is unavailable in the beginning, run a query, make the DB available, run the query again - see it fail even though the DB is available

### Expected behavior

I would expect Prisma would actually retry connecting to the DB with a new connection rather than keep returning an old error.

### Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["debian-openssl-1.1.x", "native"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// ... a bunch of models
```
Env vars:
```bash
DATABASE_URL=postgres://user:pass@127.0.0.1:5432/kubernetes-upstream?connection_limit=50
```

### Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Node.js version: 14

### Prisma Version

```
prisma                  : 3.4.1
@prisma/client          : 3.4.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
```

**Comment by tobsenll** [comment]
We have the same issue. When we trigger a db request while the AWS Aurora Serverless DB is still coldstarting we get exactly the same message. Even when then DB is available then, prisma does not recover

**Comment by janpio** [comment]
This could be related: https://github.com/prisma/prisma/issues/9420

**Comment by matthewmueller** [comment]
For now, you can retry by hand. We need to decide if we want to do retries or expose retry callbacks.

**Comment by janpio** [comment]
This is not really about a retry though, but about being able to recover from a previous error on another query being executed. Per the description this currently needs a restart of Prisma Client (which usually means of the whole app) instead.

**Comment by stianl** [comment]
Can confirm this is still an issue (tested with 3.7.0). If the DB is unavailable on the first query, Prisma never recovers. If it is available initially, becomes unavailable and later available again, Prisma recovers. Tested with stopping and starting docker container running postgresql.

FWIW, I noticed the stack trace is slightly different:

Unrecoverable:
```
Please make sure your database server is running at `localhost`:`49155`.
    at cb (<redacted>/node_modules/@prisma/client/runtime/index.js:38694:17)
```

Recoverable:
```
Please make sure your database server is running at `localhost`:`49155`.
    at cb (<redacted>/node_modules/@prisma/client/runtime/index.js:38688:17)
```

**Comment by ivanstanev** [comment]
Hey @matthewmueller! Do you have any updates around this issue? Would it be prioritised soon and is there a decision around how you want Prisma to handle this?

**Comment by leppaott** [comment]
Still an issuea connect_timeouts don't have an affect on this: if DB is down before Prisma we get an error. Would be nice if this was retried/configurable on Prisma instead of having to do docker wait-for kind of scripts waiting for a DB.

**Comment by garrensmith** [comment]
https://github.com/prisma/prisma/pull/12066 fixes this. 
You can test it out with `prisma@dev` and will be out in the next release
