### ISSUE TITLE
"Could not open datamodel file" with weird path after upgrading from 3.0.2

### ISSUE THREAD

**Issue by MichalLytek** [prisma/prisma#10171]
### Bug description

After upgrading to 3.3.0 I've encountered this issue and rollbacked waiting for a fix.
Then I tried 3.4.1 and the issue still exist.

When I create in my code a `new PrismaClient()`, it throws such error:
```
 Invalid `prisma.user.create()` invocation:


      Query engine exited with code 101

    thread 'main' panicked at 'Could not open datamodel file "/home/majkel/work/BlueReceipt/dashboard/api/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/generated/schema.prisma"', query-engine/query-engine/src/opt.rs:196:53
    stack backtrace:
       0: rust_begin_unwind

      at ../../../../../../../rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
         1: std::panicking::begin_panic_fmt
      at ../../../../../../../rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:457:5
      2: query_engine::opt::load_datamodel_file::{{closure}}
         3: structopt::StructOpt::from_args
      4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
         5: std::thread::local::LocalKey<T>::with
      6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
         7: async_io::driver::block_on
         8: std::thread::local::LocalKey<T>::with
         9: std::thread::local::LocalKey<T>::with
        10: async_std::task::builder::Builder::blocking
        11: query_engine::main
      note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
      at Object.request (../prisma/generated/runtime/index.js:38872:15)
     (...)
```

The Prisma schema is stored in `prisma` folder while the source code is in `src`. All Prisma commands like `prisma generate` works correctly and can find the schema.

### How to reproduce

It might be hard, as it works when I setup a fresh repo with Prisma from scratch. However, it still works with 3.0.2, so it's not related to my code change or build setup.

### Expected behavior

It should work normally without an error, like it used to do in 3.0.2.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  output          = "./generated"
  previewFeatures = ["filterJson", "interactiveTransactions"]
  binaryTargets   = ["native", "rhel-openssl-1.0.x"]
  engineType      = "binary"
}

datasource db {
  provider = "mysql"
  url      = env("DB_URL")
}
```

### Environment & setup

- OS:  Ubuntu 20.04
- Database:  MySQL 5.7
- Node.js version:  14.17

### Prisma Version

```
prisma                  : 3.4.1
@prisma/client          : 3.4.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 57771c0558568c7d08bd34c7248af5244ae16bd9 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 57771c0558568c7d08bd34c7248af5244ae16bd9
Studio                  : 0.438.0
Preview Features        : filterJson, interactiveTransactions
```

**Comment by pantharshit00** [comment]
I am also unable to reproduce this with fresh setup. 

What is really weird here is prisma is trying to resolve the schema inside of `babel` dependency path `"/home/majkel/work/BlueReceipt/dashboard/api/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/generated/schema.prisma"'`.

I might be stating the obvious but did you try clean node_modules install after upgrading? If you can reliably reproduce in the local setup, would it be possible to share the contents of the folder in a zip file, that would help here.

**Comment by MichalLytek** [comment]
@pantharshit00 
I've just checked, pruned whole node_modules and lock files, installed from scratch and the error still occurs.

Can I somehow enable more detailed logs, try some `dev` version with debug mode or something that might help to narrow the faulty part?

While technically I could zip the project, NDA does not allow me to do this 😕

**Comment by jared-fraser** [comment]
> What is really weird here is prisma is trying to resolve the schema inside of `babel` dependency path `"/home/majkel/work/BlueReceipt/dashboard/api/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/generated/schema.prisma"'`.
> 

That seems related to this issue https://github.com/prisma/prisma/issues/9435

There was a change to `findSync` that is eagerly matching the wrong folder.

**Comment by MichalLytek** [comment]
@jared-fraser Thanks! I was searching for such issue but couldn't find 😞 
I think it's the same issue as at first it was searching for prisma schema at my `build` folder - I removed it and then it started to look at `node_modules`.
I'm also using yarn workspaces but with Yarn 1.2 and Lerna 👀

**Comment by MichalLytek** [comment]
I've managed to make it work with `v.3.6.0`.

I had to change `output = "./generated" to `output = "./generated/client", as described in mentioned above issue 😉

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
