### ISSUE TITLE
PANIC: called `Result::unwrap()` on an `Err` value: Any { .. } in query-engine/connectors/sql-query-connector/src/error.rs:58:51

### ISSUE THREAD

**Issue by fizx** [prisma/prisma#10224]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.13.0           | 
| OS              | linux-arm64-openssl-1.1.x|
| Prisma Client   | 3.4.2              |
| Query Engine    | 0.1.0              |
| Database        | postgresql         |

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:client clientVersion: 3.4.2
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine Search for Query Engine Library in /app/home/node_modules/.prisma/client
prisma:client:libraryEngine loadEngine using /app/home/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-1.1.x.so.node
prisma:client prisma.queryRaw( 
  SELECT "Package"."content", "InstallContext"."value"
  FROM 
    "Package" INNER JOIN "App" ON "Package"."appId" = "App"."id" 
    INNER JOIN "Installation" ON "Package"."id" = "Installation"."packageId"
    INNER JOIN "InstallContext" ON "InstallContext"."id" = "Installation"."installContextId"
    WHERE 
        "InstallContext"."key" = 'subreddit' 
        AND "App"."appTypeId" IN ('PostRender')
        AND "InstallContext"."value" = $1
  , [["popular","redditdev","devvittests","u_testabledevvit"]])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine graphQLToJSError
prisma:client:fetcher Error: called `Result::unwrap()` on an `Err` value: Any { .. }
    at Object.prismaGraphQLToJSError (/app/home/node_modules/@prisma/client/runtime/index.js:36310:12)
    at Object.request (/app/home/node_modules/@prisma/client/runtime/index.js:36325:22)
    at async cb (/app/home/node_modules/@prisma/client/runtime/index.js:38472:26)
    at async eval (webpack-internal:///./pages/listing.tsx:64:16)
prisma:client prisma.queryRaw( 
  SELECT "Package"."content", "InstallContext"."value"
  FROM 
    "Package" INNER JOIN "App" ON "Package"."appId" = "App"."id" 
    INNER JOIN "Installation" ON "Package"."id" = "Installation"."packageId"
    INNER JOIN "InstallContext" ON "InstallContext"."id" = "Installation"."installContextId"
    WHERE 
        "InstallContext"."key" = 'subreddit' 
        AND "App"."appTypeId" IN ('PostRender')
        AND "InstallContext"."value" IN ($1)
  , [["popular","redditdev","devvittests","u_testabledevvit"]])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by janpio** [comment]
Hey @fizx, can you share the SQL schema of `Package`, `Installation` and `InstallContext` so we can reproduce this query? Does the data you have in those tables possible play a role?
