### ISSUE TITLE
Raw queries exception error message do not include "code snippet"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#10230]
Compare these error messages for `prisma.$queryRaw` and `prisma.user.findMany()`:

```
C:\Users\Jan\Documents\throwaway\10141>node script.js
PrismaClientInitializationError: 
Invalid `prisma.user.findMany()` invocation in
C:\Users\Jan\Documents\throwaway\10141\script.js:8:36

   5 async function main() {
   6
   7   try {
→  8     const data = await prisma.user.findMany(
  Can't reach database server at `example.org`:`123`

Please make sure your database server is running at `example.org`:`123`.
    at cb (C:\Users\Jan\Documents\throwaway\10141\node_modules\@prisma\client\runtime\index.js:38508:17)
    at async main (C:\Users\Jan\Documents\throwaway\10141\script.js:8:18) {
  clientVersion: '3.4.2',
  errorCode: undefined
}
```

and

```
C:\Users\Jan\Documents\throwaway\10141>node script.js
PrismaClientInitializationError: 
Invalid `prisma.queryRaw()` invocation:


  Can't reach database server at `example.org`:`123`

Please make sure your database server is running at `example.org`:`123`.
    at cb (C:\Users\Jan\Documents\throwaway\10141\node_modules\@prisma\client\runtime\index.js:38508:17)
    at async main (C:\Users\Jan\Documents\throwaway\10141\script.js:8:18) {
  clientVersion: '3.4.2',
  errorCode: undefined
}
```

Note how the raw error does not include the "code snippet".

(The missing `errorCode` is reported in https://github.com/prisma/prisma/issues/10229)

**Comment by janpio** [comment]
(Might already have been fixed by a recent PR from @SevInf)

**Comment by millsp** [comment]
This is still the case, the stacktrace information for raw queries has no useful information because it is obstructed by the proxies we use for `prisma.<model>.<method>`.
