### ISSUE TITLE
Unable to build Prisma Client on Netlify

### ISSUE THREAD

**Issue by didier** [prisma/prisma#10318]
Hi, I'm unable to build the Prisma Client on Netlify, no matter what I try. 
I'm running it inside a SvelteKit project, but I'm building it seperately, so that probably doesn't matter.

# Build log
```yml
12:29:05 PM: /opt/build/repo/node_modules/@prisma/client/runtime/index.js:36456
12:29:05 PM:       throw new PrismaClientInitializationError(errorText, this.config.clientVersion);
12:29:05 PM:             ^
12:29:05 PM: PrismaClientInitializationError: Query engine library for current platform "debian-openssl-1.0.x" could not be found.
12:29:05 PM: You incorrectly pinned it to debian-openssl-1.0.x
12:29:05 PM: This probably happens, because you built Prisma Client on a different platform.
12:29:05 PM: (Prisma Client looked in "/opt/build/repo/node_modules/@prisma/client/runtime/libquery_engine-debian-openssl-1.0.x.so.node")
12:29:05 PM: Searched Locations:
12:29:05 PM:   /opt/build/repo/node_modules/.prisma/client
12:29:05 PM:   /opt/build/repo/node_modules/@prisma/client
12:29:05 PM:   /opt/build/repo/node_modules/@prisma/client
12:29:05 PM:   /opt/build/repo/node_modules/.prisma/client
12:29:05 PM:   /opt/build/repo/prisma
12:29:05 PM:   /tmp/prisma-engines
12:29:05 PM:   /opt/build/repo/node_modules/.prisma/client
12:29:05 PM: You already added the platforms "debian-openssl-1.0.x", "rhel-openssl-1.0.x" to the "generator" block
12:29:05 PM: in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
12:29:05 PM: but something went wrong. That's suboptimal.
12:29:05 PM: Please create an issue at https://github.com/prisma/prisma/issues/new
12:29:05 PM:     at Object.getLibQueryEnginePath (/opt/build/repo/node_modules/@prisma/client/runtime/index.js:36456:13)
12:29:05 PM:     at async Object.loadEngine (/opt/build/repo/node_modules/@prisma/client/runtime/index.js:36124:33)
12:29:05 PM:     at async Object.instantiateLibrary (/opt/build/repo/node_modules/@prisma/client/runtime/index.js:36090:5) {
12:29:05 PM:   clientVersion: '3.5.0',
12:29:05 PM:   errorCode: undefined
12:29:05 PM: }
12:29:05 PM: error Command failed with exit code 1.
```

**Comment by janpio** [comment]
How are you building it then? Could you please provide all the information the bug issue template asks for? Thanks.

**Comment by didier** [comment]
@janpio Strange, when creating the issue it didn't autofill or template anything.

Anyway, I'm just building the prisma client using `prisma generate`. Not at a computer at the moment, but will try to update according to the template once I am.

**Comment by janpio** [comment]
https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml

**Comment by pantharshit00** [comment]
@didier I am going to close this issue. Please link the new issue here and fill out the complete template there.

**Comment by collegewap** [comment]
For me the issue solved with the following steps:

- Added the following line to `schema.prisma`

```diff
generator client {
  provider        = "prisma-client-js"
+ binaryTargets   = ["native", "debian-openssl-1.1.x"]
}

```

- Triggered **Clear cache and deploy site** in Netlify.
