### ISSUE TITLE
PrismaClientUnknownRequestError in prisma.user.create(...);

### ISSUE THREAD

**Issue by Datzu712** [prisma/prisma#10497]
### Bug description

When I try to create a new user I got this error:
```sh-session
prisma:info Starting a mysql pool with 9 connections.
prisma:query BEGIN
prisma:query INSERT INTO `iosef_db`.`user` (`id`,`hash`,`salt`,`password`,`email`,`token`,`tokenExpiration`) VALUES (?,?,?,?,?,?,?)
prisma:query SELECT `iosef_db`.`user`.`id`, `iosef_db`.`user`.`hash`, `iosef_db`.`user`.`salt`, `iosef_db`.`user`.`password`, `iosef_db`.`user`.`email`, `iosef_db`.`user`.`token`, `iosef_db`.`user`.`tokenExpiration` FROM `iosef_db`.`user` WHERE `iosef_db`.`user`.`id` = ? LIMIT ? OFFSET ?
prisma:query ROLLBACK
PrismaClientUnknownRequestError: 
Invalid `prisma.user.create()` invocation in
/api/src/prisma/models/User.model.ts:150:44

  147 const salt = await bcrypt.genSalt(10);
  148 const hashedPassword = await bcrypt.hash(data.password, salt);
  149 
→ 150 const user = await prisma.user.create(
  Query createOneuser is required to return data, but found no record(s).
    at cb (/api/node_modules/@prisma/client/runtime/index.js:38679:17)
    at async Function.create (/api/src/prisma/models/User.model.ts:150:26)
    at async loginController.test (/api/src/controllers/login.controller.ts:31:25)
    at async /api/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /api/node_modules/@nestjs/core/router/router-proxy.js:9:17 {
  clientVersion: '3.5.0'
}
```

### How to reproduce

```ts
await prisma.user.create({
    data: {
        email: data.email,
        password: data.password,
        tokenExpiration: `${moment(Date.now()).add(15, 'minutes').valueOf()}`,
        token: token,
        salt: salt,
        hash: hashedPassword
    }
});
```

### Expected behavior

It should create the user without error

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("MYSQL_URL")
}

model user {
  id              String @id @default("") @db.VarChar(36)
  hash            String @db.VarChar(80)
  salt            String @db.VarChar(80)
  password        String @db.VarChar(22)
  email           String @db.VarChar(50)
  token           String @db.VarChar(280)
  tokenExpiration String @db.VarChar(50)
}

```

### Environment & setup

- OS: Linux
- Database: MySQL
- Node.js version: 16.13.0

### Prisma Version

```
3.5.0
```

**Comment by janpio** [comment]
Is this consistently reproducible for you? Super weird.

**Comment by csanso-limit** [comment]
I think @Datzu712 hasn't configured the model correctly and that's why it's failing.

`id              String @id @default("") @db.VarChar(36)`

Default is set to blank string, thus when you use create() Prisma thinks you are inserting an empty string "" as the id, thus when it tries to the select after inserting it tries to select the user with id = "" empty string and fails, and then rolls back.
Thus the failure is happening when running the SELECT query, it returns nothing, and so then prisma rolls back the insert, since the whole query sequence is in a trasaction.

What happens with createMany() is that it successfully inserts like with create(), but createMany() does not try and run a SELECT query afterwards with id = "" empty string.

Solution found, I think.

**Comment by csanso-limit** [comment]
However I am having a similar problem.
I amb IoT programmer, I save millions of timestamps in the database.

My problem is due to the fact that my primary key includes a timestamp, and Prisma thinks mysql and postgres save the exact timestamp (with milliseconds) that Prisma sent in the INSERT query, but mysql and postgres both round up or down the timestamp when it saves it. HOWEVER when running the SELECT query mysql and postgres do not round up or down the timestamps thus having an exact timestamp comparision, but it cannot find the inserted ROW because the timestamp was rounded up in the save process. And thus Prisma rolls back the INSERT query because it did not return any values.

I think this is a big problem.

**Comment by csanso-limit** [comment]
It doesn't matter in which ISO 8601 you send it as "2022-01-27T16:49:54.9+01:00" or "2022-01-27T15:49:54.9Z" both have the same problem.

`const stationTaxi = await prisma.stationTaxi.create({
   data: {
      taxiId: client.taxi.id,
      stationId: station.id,
      arrivedAt: new Date(),
  },
});`

You cannot use `new Date()` directly.

A simple workaround would be "const arrivedAt = new Date(parseVar)" and then call "arrivedAt.setMilliseconds(0)", and then send the date. Then the whole create() sequence works correctly.
But this is a flaw, most people won't know how to do this workaround.

This workaround also proves my point, that that milliseconds is causing prisma create() to fail when the **primary key** includes a datetime or timestamp.

**Comment by janpio** [comment]
Can you please split your problem into its own issue @csanso-limit? Right now I can not apply the correct labels or ask the correct questions as this is in another user's issue which you already kind of debugged and solved. Very happy to take a look at what you write - but in its own issue with the full issue information filled out. Thanks.

**Comment by Datzu712** [comment]
> I think @Datzu712 hasn't configured the model correctly and that's why it's failing.
> 
> `id String @id @default("") @db.VarChar(36)`
> 
> Default is set to blank string, thus when you use create() Prisma thinks you are inserting an empty string "" as the id, thus when it tries to the select after inserting it tries to select the user with id = "" empty string and fails, and then rolls back. Thus the failure is happening when running the SELECT query, it returns nothing, and so then prisma rolls back the insert, since the whole query sequence is in a trasaction.
> 
> What happens with createMany() is that it successfully inserts like with create(), but createMany() does not try and run a SELECT query afterwards with id = "" empty string.
> 
> Solution found, I think.

Hi @csanso-limit Thanks for answering me! 
I have the @default("") because after create a user in my database I have atrigger that before insert a user it is executed and it assing a UUID to the user id automatically, but but the id to have a primary key I cannot set i with allow null.
![image](https://user-images.githubusercontent.com/66436460/152372876-a8c052b2-a1cb-4346-bc00-370f0369e0d0.png)

I tried adding the ID manually but I got the same error :( 
`Query createOnetest is required to return data, but found no record(s).`

```prisma
model test {
  id              String @id @db.VarChar(50)
  salt            String @db.VarChar(50)
  email           String @db.VarChar(50)
  token           String @db.VarChar(50)
  tokenExpiration String @db.VarChar(50)
  hash            String @db.VarChar(80)
}
```

```js
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient()

prisma.test.create({
    data: {
        email: 'someone@gmail.com',
        tokenExpiration: `1643896265257`,
        token: 'eyJh9rxfUhIu_UUYZ-ZkRUCuqW-9tUk',
        salt: '$2b$10$q.y4.vrHKxDYMQkeWm9xW.',
        hash: '$2b$10$Qju63Il/erAV1epJyeEk6epdX5/zD.6kC4oTTjTtlHeUpCUDfpHay',
        id: '7bbf1f4a-7713-11ec-8968-0242ac120002'
    }
}).then(console.log).catch(console.error);
```

**Comment by codymihai** [comment]
Does anybody figure out to fix this problem? or a way to fix it?

**Comment by codymihai** [comment]
> Does anybody figure out to fix this problem? or a way to fix it?

Resolve it. I've migrated from prisma 1 to prisma 2 and the length of Id(@id) was increased to 30 characters into prisma 2 due to cuid() generator

**Comment by pantharshit00** [comment]
I can reproduce the problem. This can be associated with https://github.com/prisma/prisma/issues/4246. 

But the setup with trigger to assign IDs is not very common so this might not be as straightfoward.

**Comment by Jolg42** [comment]
Note:
The database has a trigger setting the UUID after the data was written by Prisma.
There is probably no way we can fix that in the current architecture because in a `create()` we always return the created row, and we need to fetch it. This doesn't work when the primary key changes.
(`createMany()` works because it doesn't return the data, only a count.)

Alternatively, Prisma could return the data that was created but the data would be incorrect.

We could make this work by disabling the fetch, see feature request https://github.com/prisma/prisma/issues/4246

**Comment by pimeys** [comment]
This looks like there are way too many problems in the same issue. 

For the first problem, I cannot reproduce that with 3.5.0 or with 4.3.1.

**Comment by pimeys** [comment]
Ok, now I can reproduce this with 4.3.1.

What happens here is that we generate that empty string default value in the core, and we expect to find this new record with that value. The database generates a UUID, and our `SELECT` does not find anything.

**Comment by janpio** [comment]
Probably related: https://github.com/prisma/prisma/issues/14918
