### ISSUE TITLE
Running db seed fails on v3.4.0+ (ARM)

### ISSUE THREAD

**Issue by lvnr** [prisma/prisma#10519]
### Bug description

Running `npx prisma db seed` on Prisma v3.3.0 works.
The same command on v3.4.0 and newer versions fails.

It happens on Node v16 arm-x64. But when changing to Node v14 x64 (non-ARM) and regenerating Prisma Client, seed command starts working on newer Prisma versions.

```
❯ DEBUG="*" npx prisma db seed
  prisma:loadEnv project root found at /Users/___REDACTED___/package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from /Users/___REDACTED___/.env +0ms
Environment variables loaded from .env
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:migrate:seed {
  prisma:migrate:seed   prismaConfig: {
  prisma:migrate:seed     data: { seed: 'ts-node prisma/seed.ts' },
  prisma:migrate:seed     packagePath: '/Users/___REDACTED___/package.json'
  prisma:migrate:seed   }
  prisma:migrate:seed } +0ms
Running seed command `ts-node prisma/seed.ts` ...
  prisma:tryLoadEnv Environment variables loaded from /Users/___REDACTED___/.env +0ms
  prisma:tryLoadEnv Environment variables loaded from /Users/___REDACTED___/.env +7ms
  prisma:client clientVersion: 3.6.0 +0ms
  prisma:client clientEngineType: library +0ms
  prisma:client:libraryEngine internalSetup +0ms
  prisma:client Prisma Client call: +13ms

___REDACTED___

  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: false +20ms
  prisma:client:libraryEngine Search for Query Engine Library in /Users/___REDACTED___/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine loadEngine using /Users/___REDACTED___/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:migrate:seed {
  prisma:migrate:seed   e: Error: Command was killed with SIGKILL (Forced termination): ts-node prisma/seed.ts
  prisma:migrate:seed       at makeError (/Users/___REDACTED___/node_modules/prisma/build/index.js:2977:17)
  prisma:migrate:seed       at handlePromise (/Users/___REDACTED___/node_modules/prisma/build/index.js:3704:33)
  prisma:migrate:seed       at runMicrotasks (<anonymous>)
  prisma:migrate:seed       at processTicksAndRejections (node:internal/process/task_queues:96:5)
  prisma:migrate:seed       at async executeSeedCommand (/Users/___REDACTED___/node_modules/prisma/build/index.js:102506:5)
  prisma:migrate:seed       at async Object.parse (/Users/___REDACTED___/node_modules/prisma/build/index.js:104010:31)
  prisma:migrate:seed       at async main (/Users/___REDACTED___/node_modules/prisma/build/index.js:106401:18) {
  prisma:migrate:seed     shortMessage: 'Command was killed with SIGKILL (Forced termination): ts-node prisma/seed.ts',
  prisma:migrate:seed     command: 'ts-node prisma/seed.ts',
  prisma:migrate:seed     escapedCommand: 'ts-node "prisma/seed.ts"',
  prisma:migrate:seed     exitCode: undefined,
  prisma:migrate:seed     signal: 'SIGKILL',
  prisma:migrate:seed     signalDescription: 'Forced termination',
  prisma:migrate:seed     stdout: undefined,
  prisma:migrate:seed     stderr: undefined,
  prisma:migrate:seed     failed: true,
  prisma:migrate:seed     timedOut: false,
  prisma:migrate:seed     isCanceled: false,
  prisma:migrate:seed     killed: false
  prisma:migrate:seed   }
  prisma:migrate:seed } +974ms

An error occured while running the seed command:
Error: Command was killed with SIGKILL (Forced termination): ts-node prisma/seed.ts
```

### How to reproduce

1. Run `prisma db push` on darwin-arm architecture
2. Run `prisma db seed`
3. Exits with `An error occured while running the seed command:
Error: Command was killed with SIGKILL (Forced termination): ts-node prisma/seed.ts`

### Expected behavior

The seed.ts script should execute.

### Prisma information

N/A

### Environment & setup

- OS: Mac OS (on MacBook Pro with M1 Max)
- Database: MySQL
- Node.js version: v16-ARM-x64 & v14-x64

### Prisma Version

```
3.6.0
```

**Comment by janpio** [comment]
Can you run `npx ts-node prisma/seed.ts` manually or does that also crash?

**Comment by lvnr** [comment]
@janpio I tried that too, and it was running into the same error. But today I tried `npx prisma db seed` again and this time it worked for some reason.

Even though I had tried installing 3.3.0 and then 3.6.0 a few times, it was only running on 3.3.0

I think I may have deleted `node_modules` at some point, and maybe after that it started working on 3.6.0.

**Comment by janpio** [comment]
If standalone `npx ts-node prisma/seed.ts` also failed, it would mean that this is not about Prisma and it's `db seed` command but really about either `ts-node` or the `prisma/seed.ts` and whatever you do in there.

As you report it now working, I will close this - feel free to come back and comment again if this ever happens again and we will reopen. Thanks.

**Comment by pimmee** [comment]
I ran into the samme issue having the M1 chip (don't know if it's related). Can confirm that deleting node_modules and reinstalling fixed the issue. Thanks!
