### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine\core\src\query_document\parser.rs:250:87

### ISSUE THREAD

**Issue by mamichels** [prisma/prisma#10586]
Hi Prisma Team! My Prisma Client crashes when using an ridiculous large number for an field of type Integer. In this case, fixing my business logic will be fairly simple, what does make me feel uncomfortabl is, that all further calls on the prisma client (singleton, as described [here](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/instantiate-prisma-client)) will give me a similar error as stated below. I now manually need to create a new instance of my PrismaClient or better, restart the whole application. I am pretty sure, that those invalid inputs weren't crashing my whole PrismaClient a few weeks ago. What happend?

**Update:** Change query data to indicate integer input is actually formated in scientific notation

This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | windows            |
| Prisma Client   | 3.6.0              |
| Query Engine    | 0.1.0              |
| Database        | postgresql         |

## Logs
```
:client:libraryEngine library started
prisma:client:libraryEngine library started
prisma:tryLoadEnv Environment variables loaded from C:\code\project\app\.env
prisma:client clientVersion: 3.6.0
prisma:client clientEngineType: library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine Search for Query Engine Library in C:\code\project\app\node_modules\.prisma\client
prisma:client:libraryEngine loadEngine using C:\code\project\app\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine library starting
prisma:tryLoadEnv Environment variables loaded from C:\code\project\app\.env
prisma:client clientVersion: 3.6.0
prisma:client clientEngineType: library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine Search for Query Engine Library in C:\code\project\app\node_modules\.prisma\client
prisma:client:libraryEngine loadEngine using C:\code\project\app\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:tryLoadEnv Environment variables loaded from C:\code\project\app\.env
prisma:client clientVersion: 3.6.0
prisma:client clientEngineType: library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine Search for Query Engine Library in C:\code\project\app\node_modules\.prisma\client
prisma:client:libraryEngine loadEngine using C:\code\project\app\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine library started
prisma:tryLoadEnv Environment variables loaded from C:\code\project\app\.env
prisma:client clientVersion: 3.6.0
prisma:client clientEngineType: library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine Search for Query Engine Library in C:\code\project\app\node_modules\.prisma\client
prisma:client:libraryEngine loadEngine using C:\code\project\app\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:tryLoadEnv Environment variables loaded from C:\code\project\app\.env
prisma:client clientVersion: 3.6.0
prisma:client clientEngineType: library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine Search for Query Engine Library in C:\code\project\app\node_modules\.prisma\client
prisma:client:libraryEngine loadEngine using C:\code\project\app\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:tryLoadEnv Environment variables loaded from C:\code\project\app\.env
prisma:client clientVersion: 3.6.0
prisma:client clientEngineType: library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine Search for Query Engine Library in C:\code\project\app\node_modules\.prisma\client
prisma:client:libraryEngine loadEngine using C:\code\project\app\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
  public async save(entity: Entity): Promise<Entity> {
    const insertQuery = {
      data: entity
    };

    try {
      return await this.db.client.entity.create(insertQuery); // this.db.client retrieves a singleton of the PrismaClient
    } catch (e) {
      console.error(e);
      throw new ApiError(`Error on Save`, e);
    }
  }
```

## Schema
```prisma
model entity {
  id             Int      @id @default(autoincrement())
  ....
  intField Int
  ...
  someRelation       Relation @relation(fields: [someRelationId], references: [id], onDelete: Cascade)
}
```

## Prisma Engine Query (Initial query that will crash the PrismaClient)
```
{"data": { ..., intField: 1.1111111111111111e+61,, ... }}
```

## Stderr on query that will crash the client
```bash
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', query-engine\core\src\query_document\parser.rs:250:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PrismaClientUnknownRequestError:
Invalid `this.db.client.entity.create()` invocation in
C:\code\project\app\domain\entity\entity.dao.js:93:77

   90     _a.label = 1;
   91 case 1:
   92     _a.trys.push([1, 3, , 4]);
ÔåÆ  93     return [4 /*yield*/, this.db.client.entity.create(insertQuery)];
  called `Option::unwrap()` on a `None` value
    at Object.request (C:\code\project\app\node_modules\@prisma\client\runtime\index.js:39049:15) {
  clientVersion: '3.6.0'
}
```

## Stderr on any subsequent query
```bash
PrismaClientRustPanicError:
Invalid `this.db.client.COMPLETLY_DIFFERENT_ENTITY.findUnique()` invocation in
C:\code\project\app\domain\projekt\projekt.dao.js:112:69

  109     _a.label = 1;
  110 case 1:
  111     _a.trys.push([1, 3, , 4]);
ÔåÆ 112     return [4 /*yield*/, this.db.client.projekt.findUnique(findByIdQuery)];
  PANIC: called `Option::unwrap()` on a `None` value in query-engine\core\src\query_document\parser.rs:250:87

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

... <link stuff>

If you want the Prisma team to look into it, please open the link above ­ƒÖÅ
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

    at Object.request (C:\code\project\app\node_modules\@prisma\client\runtime\index.js:39053:15) {
  clientVersion: '3.6.0'
}
Error: Error on Save ...

```

**Comment by terion-name** [comment]
also encountered such panics

**Comment by DmitryKazanok-LP** [comment]
faced the same issue on attempting to upsert 22 digit value into an int column

**Comment by janpio** [comment]
Feel free to share your reproduction code as well - anything helps when we got to reproducing this.

**Comment by dguenther** [comment]
I've also seen this issue. I created a simple reproduction case to help with debugging here: https://github.com/dguenther/prisma-panic-demo

**Comment by janpio** [comment]
Thanks for the awesome reproduction @dguenther - couldn't be easier than that one. While playing with that (trying to understand why this does not behave as expected besides the Engine side crash) I discovered a small regression in our error logic: https://github.com/prisma/prisma/issues/11362 Usually the message about the non recoverable error should definitely already be shown on the first query - not only on the second one.

**Comment by mehdyouras** [comment]
Any update on this?

**Comment by Arman-Hosseini** [comment]
Friendly ping @janpio .
Do you have an update for this issue?

**Comment by janpio** [comment]
No. Any update will be posted in the issue.

**Comment by kasir-barati** [comment]
I faced this issue in my prod app too. IDK why it does not happen in my local running app and in my app which is running on the same server but exposed on different domain name. :confused:

Great bug and hard to discover AFAIK :joy:

Do you - @mamichels @terion-name @DmitryKazanok-LP @dguenther @NullSoldier @mehdyouras  - figured it out? or did you have any suggestion?

Does it only works on `number`s  @NullSoldier ?

**Comment by DmitryKazanok-LP** [comment]
> I faced this issue in my prod app too. IDK why it does not happen in my local running app and in my app which is running on the same server but exposed on different domain name. 😕
> 
> Great bug and hard to discover AFAIK 😂
> 
> Do you - @mamichels @terion-name @DmitryKazanok-LP @dguenther @NullSoldier @mehdyouras - figured it out? or did you have any suggestion?
> 
> Does it only works on `number`s @NullSoldier ?

In my experience once you try to test with an overflowing integer it was pretty consistent across all environments. and to my knowledge floats are affected too.

**Comment by kasir-barati** [comment]
@DmitryKazanok-LP I did this: 

```ts
import { IsInt, Max } from 'class-validator';

export class ClassName {
    @IsInt()
    @Max(2_147_483_647)
    fieldNameWichIsInt: number;
}
```

I realized that [`@IsInt` decorator in class-validator](https://github.com/typestack/class-validator/blob/master/src/decorator/typechecker/IsInt.ts#L10) cannot validate integers as we all expect. BTW we have to make sure that our app validate integers narrowly and rigidly to prevent any but ATM and later on prisma dev team can resolve issue form its root if possible. TBH I think it is my fault that my app breaks due to I learned from The Pragmatic Programmer book, debugging sectionm :smile: 

Thank you prisma dev team for hard work.

**Comment by farshidbeheshti** [comment]
The issue is because of the long integers too, for example 999999999999999999999999999999(1e+30), that not fall within the range of an integer for Prisma.

**Comment by mamichels** [comment]
@[kasir-barati](https://github.com/kasir-barati), since this is a extremly serious issue we assessed that we add a manual strict validation on all affected fields.

**Comment by dpetrick** [comment]
3.15 will ship a change that returns a structured error instead of a panic.

**Comment by parkarsayali** [comment]
### called `Option::unwrap()` on a `None` value


//schema.prisma

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["relationJoins"]
}

model country {
  country_id      Int       @id @default(autoincrement())
  name            String    @db.VarChar(100)
  alpha_2         String    @default("") @db.Char(2)
  alpha_3         String    @default("") @db.Char(3)
  phone_code      Int       @default(0)
  currency        String    @db.VarChar(3)
  currency_symbol String    @db.VarChar(10)
  created_on      DateTime  @default(dbgenerated("(now())")) @db.Timestamp(0)
  modified_on     DateTime? @db.Timestamp(0)
  is_deleted      Boolean   @default(false)
  States          state[]   // Establishing the one-to-many relationship

}

model state {
  state_id    Int       @id @default(autoincrement())
  name        String    @db.VarChar(100)
  alpha_code  String    @db.VarChar(10)
  country_id  Int
  created_on  DateTime  @default(dbgenerated("(now())")) @db.DateTime(0)
  modified_on DateTime? @db.DateTime(0)
  is_deleted  Boolean   @default(false)
  Country     country   @relation(fields: [country_id], references: [country_id])

}

```

//state.repository

```
  async getStates(): Promise<any> {
    try {
      return this.prisma.state.findMany({
        include: {
          country: {
            select: {
              name: true,
            },
          },
        },
      });
    } catch (error) {
      console.error('Error fetching states:', error);
      throw error;
    }
  }
```

//error:

async getStates(): Promise<any> {
  27   try {
→ 28     return this.prisma.state.findMany(
called `Option::unwrap()` on a `None` value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
