### ISSUE TITLE
PANIC in C:\Users\runneradmin\.cargo\git\checkouts\rust-postgres-dc0fca9be721a90f\8a61d46\postgres-types\src\lib.rs:762:18expected array type

### ISSUE THREAD

**Issue by joaofurini** [prisma/prisma#10635]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.4.0            | 
| OS              | windows            |
| Prisma Client   | 2.30.3             |
| Query Engine    | query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20|
| Database        | undefined|

## Logs
```
  prisma:client clientVersion: 2.30.3  
  prisma:engine Search for Query Engine in C:\Users\jpfur\ytech\anticimex\node_modules\.prisma\client  
  prisma:engine { cwd: 'C:\\Users\\jpfur\\ytech\\anticimex\\prisma' }  
  prisma:engine Search for Query Engine in C:\Users\jpfur\ytech\anticimex\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '61488' ] }  
  prisma:engine stdout  Starting a postgresql pool with 13 connections in PgBouncer mode.  
  prisma:engine stdout  Started http server on http://127.0.0.1:61488  +1s
  prisma:engine Search for Query Engine in C:\Users\jpfur\ytech\anticimex\node_modules\.prisma\client  
  prisma:engine Client Version: 2.30.3  
  prisma:engine Engine Version: query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in C:\Users\runneradmin\.cargo\git\checkouts\rust-postgres-dc0fca9be721a90f\8a61d46\postgres-types\src\lib.rs:762:18
expected array type  +8s
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:61488
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 61488
  prisma:engine   }
  prisma:engine }  +2s
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd: 'C:\\Users\\jpfur\\ytech\\anticimex\\prisma' }  
  prisma:engine Search for Query Engine in C:\Users\jpfur\ytech\anticimex\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '61499' ] }  
  prisma:engine stdout  Starting a postgresql pool with 13 connections in PgBouncer mode.  
  prisma:engine stdout  Started http server on http://127.0.0.1:61499  +1s
  prisma:engine Search for Query Engine in C:\Users\jpfur\ytech\anticimex\node_modules\.prisma\client  
  prisma:engine Client Version: 2.30.3  
  prisma:engine Engine Version: query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in C:\Users\runneradmin\.cargo\git\checkouts\rust-postgres-dc0fca9be721a90f\8a61d46\postgres-types\src\lib.rs:762:18
expected array type  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
mutation {
  createManyUser(data: [
    {
      id: "X"
      email: "X"
      subsidiaryId: ["X"]
      firstName: "X"
      isActive: true
      lastName: "X"
      password: "X"
      gdprCheck: true
      gdprDate: null
      isBlocked: false
      isOnline: false
      lastLogonDate: null
      loginFailures: 5
      token: "X"
      roleId: "X"
    }
  ]) {
    count
  }
}
```

**Comment by pantharshit00** [comment]
Hello! Sorry for late reply here. Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?
