### ISSUE TITLE
Cannot insert data after migration

### ISSUE THREAD

**Issue by mingzhaocn** [prisma/prisma#10652]
### Bug description

After each migration, only one piece of data can be inserted. When the second piece is inserted, a Unique constraint failed on the fields error will be thrown.
If I run ```npx prisma generate``` again, ```Do you want to continue? All data will be lost. … yes``` will appear. Then I typed ```yes```. I can insert a piece of data again, but the same error will occur the second time I insert the data, and so on.
I try to run ```npx prisma db pull``` and ```npx prisma generate```. It doesn't work. ```npx prisma db push``` also doesn't work.
I try to add a ```map``` for ```@unique``` also doesn't work.

### How to reproduce

0.
```
model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  Post  Post[]
}
model Post {
  id        Int     @id
  title     String
  published Boolean @default(false)
  userId    Int
  User      User    @relation(fields: [userId], references: [id])
}
```

1. DDL
```sql
-- auto-generated definition
create table "User"
(
    id    integer not null
        constraint "User_pkey"
            primary key,
    email text    not null,
    name  text
);

alter table "User"
    owner to prisma;

create unique index "User_email_key"
    on "User" (email);

-- auto-generated definition
create table "Post"
(
    id        integer               not null
        constraint "Post_pkey"
            primary key,
    title     text                  not null,
    published boolean default false not null,
    "userId"  integer               not null
        constraint "Post_userId_fkey"
            references "User"
            on update cascade on delete restrict
);

alter table "Post"
    owner to prisma;
```

2.
```js
const { prisma } = require('../prisma');

(async () => {
  await prisma.user.create({
    data: {
      email: 'ttt@tt.com',
    },
  });
})();

``` 

3. run again
```js
const { prisma } = require('../prisma');

(async () => {
  await prisma.user.create({
    data: {
      email: 'ttt@tt.com',
    },
  });
})();

``` 

### Prisma information

```
prisma:tryLoadEnv Environment variables loaded from /base/.env +0ms
  prisma:tryLoadEnv Environment variables loaded from /base/.env +4ms
  prisma:client clientVersion: 3.6.0 +0ms
  prisma:client clientEngineType: library +0ms
  prisma:client:libraryEngine internalSetup +0ms
  prisma:client Prisma Client call: +9ms
  prisma:client prisma.user.create({
  prisma:client   data: {
  prisma:client     email: 'ttt@tt.com'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client mutation {
  prisma:client   createOneUser(data: {
  prisma:client     email: "ttt@tt.com"
  prisma:client   }) {
  prisma:client     id
  prisma:client     email
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: false +10ms
  prisma:client:libraryEngine Search for Query Engine Library in /base/node_modules/.prisma/client +1ms
  prisma:client:libraryEngine loadEngine using /base/node_modules/.prisma/client/libquery_engine-darwin.dylib.node +0ms
  prisma:client:libraryEngine library starting +42ms
  prisma:client:libraryEngine library started +444ms
  prisma:client:fetcher Error: Unique constraint failed on the fields: (`email`)
  prisma:client:fetcher     at prismaGraphQLToJSError (/base/node_modules/@prisma/client/runtime/index.js:35956:12)
  prisma:client:fetcher     at Object.request (/base/node_modules/@prisma/client/runtime/index.js:36319:17)
  prisma:client:fetcher     at async cb (/base/node_modules/@prisma/client/runtime/index.js:38653:26)
  prisma:client:fetcher     at async /base/bin/createUser.js:4:3 +0ms
  prisma:client:libraryEngine hookProcess received: exit +127ms
  prisma:client:libraryEngine runBeforeExit +0ms
/base/node_modules/@prisma/client/runtime/index.js:38683
          throw new PrismaClientKnownRequestError(message, e.code, this.prisma._clientVersion, e.meta);
                ^

PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation in
/base/bin/createUser.js:4:21

  1 const { prisma } = require('../prisma');
  2 
  3 (async () => {
→ 4   await prisma.user.create(
  Unique constraint failed on the fields: (`email`)
    at cb (/base/node_modules/@prisma/client/runtime/index.js:38683:17)
    at async /base/bin/createUser.js:4:3 {
  code: 'P2002',
  clientVersion: '3.6.0',
  meta: { target: [ 'email' ] }
}

Node.js v17.0.1
```

### Environment & setup

-OS: Mac OS 12.0.1 (21A559)
- Database: 13.4
- Node.js version: v17.0.1

### Prisma Version

```
3.6.0
```

**Comment by mingzhaocn** [comment]
The current problem is unclear.
