### ISSUE TITLE
Docker Compose: Query engine library for current platform "debian-openssl-1.1.x" could not be found.

### ISSUE THREAD

**Issue by madhavkhoslaa** [prisma/prisma#10689]
### Bug description

```
FROM node:14
WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .env ./
COPY src ./src
RUN npm install
RUN npx prisma generate
RUN npx tsc
CMD ["npm", "run", "compare"]
```
Dockerfile

```
version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=testUser
  mongo:
    image: mongo
  web:
    build: .
    volumes:
      - .:/./app
    depends_on: 
    - postgres
    - mongo
```

### How to reproduce

.

### Expected behavior

The dockerfile built image works fine but when I run the same image on the compose I get the following error.

```
(node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
web_1       | (node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
web_1       | (node:20) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
web_1       | (node:20) UnhandledPromiseRejectionWarning: Error: 
web_1       | Invalid `this.prisma.project.createMany()` invocation in
web_1       | /app/dist/Insert/Method1/SQL/InsertTest.js:77:70
web_1       | 
web_1       |    74 return __awaiter(this, void 0, void 0, function () {
web_1       |    75     return __generator(this, function (_a) {
web_1       |    76         switch (_a.label) {
web_1       | →  77             case 0: return [4 /*yield*/, this.prisma.project.createMany(
web_1       |   Query engine library for current platform "debian-openssl-1.1.x" could not be found.
web_1       | You incorrectly pinned it to debian-openssl-1.1.x
web_1       | 
web_1       | This probably happens, because you built Prisma Client on a different platform.
web_1       | (Prisma Client looked in "/app/node_modules/@prisma/client/runtime/libquery_engine-debian-openssl-1.1.x.so.node")
web_1       | 
web_1       | Searched Locations:
web_1       | 
web_1       |   /app/node_modules/.prisma/client
web_1       |   /Users/madhavkhosla/Documents/GitHub/db-comparison/node_modules/@prisma/client
web_1       |   /app/node_modules/@prisma/client
web_1       |   /app/node_modules/.prisma/client
web_1       |   /app/src/models/prisma
web_1       |   /tmp/prisma-engines
web_1       |   /app/node_modules/.prisma/client
web_1       | 
web_1       | 
web_1       | To solve this problem, add the platform "debian-openssl-1.1.x" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
web_1       | generator client {
web_1       |   provider      = "prisma-client-js"
web_1       |   binaryTargets = ["native"]
web_1       | }
web_1       | 
web_1       | Then run "prisma generate" for your changes to take effect.
web_1       | Read more about deploying Prisma Client: https://pris.ly/d/client-generator
web_1       |     at cb (/app/node_modules/@prisma/client/runtime/index.js:38681:17)
web_1       |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
web_1       | (node:20) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

```

### Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl", "debian-openssl-1.1.x", "darwin"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v14.15.1

### Prisma Version

```
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
```

**Comment by janpio** [comment]
Does the file `libquery_engine-debian-openssl-1.1.x.so.node` exist anywhere in that project after `npm install` and `npx prisma generate`?

**Comment by madhavkhoslaa** [comment]
No it does not. Surprisingly the dockerfile on it's own runs. But when I run it from a compose file. I get this issue.

**Comment by madhavkhoslaa** [comment]
@janpio Take a look at this.
![Screenshot 2021-12-15 at 11 52 19 AM](https://user-images.githubusercontent.com/28945483/146134451-1643f802-d0f6-4c0b-83b8-f0636a6fd0db.png)
Running from a Dockerfile build


![Screenshot 2021-12-15 at 11 52 48 AM](https://user-images.githubusercontent.com/28945483/146134399-a851a527-5cba-4f14-bd89-62a3503400eb.png)
Running the same from docker compose

**Comment by madhavkhoslaa** [comment]
Okay, I know why this happened. The reason was that I had the code repo and the docker code folder as volume maps. Even though the prisma was generated on the docker host but because of the docker volume map, prisma was not able to figure out what host it was on.

**Comment by Jaykob** [comment]
Thanks for the info!
I spent a couple of hours solving the exact same problem…
Out of interest: Do you know how prisma detects the host that it runs on?
