### ISSUE TITLE
PlanetScale Relationship connections

### ISSUE THREAD

**Issue by bardiaheshmati** [prisma/prisma#10758]
### Bug description

I'm testing my existing schema on PlanetScale and i'm getting an error when i'm trying to connect relations

```js
Message: 
Invalid `prisma.product.update()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol tino.Product.id not found", state: "HY000" })) })

Query: 
prisma.product.update(
{
  where: {
    id: "69d7ee03-6d9e-46ec-a2ae-0b40e58158e1",
  },
  data: {
    category: {
      connect: {
        id: "0226b8aa-4fc5-4b20-801b-6a62b0ca8711",
      },
    },
  },
  select: {
    id: true,
    category: true,
    categoryId: true,
  },
}
)
```

Schema
```js
  model Category {
    id          String       @id @default(uuid()) @db.Char(36)
    name        String       @db.VarChar(255)
    description String?
    createdAt   DateTime     @default(now())
    updatedAt   DateTime     @updatedAt
    active      Boolean      @default(true)
    products    Product[]
  
    @@unique([id, active])
  }
  
  model Product {
  id           String         @id @default(uuid()) @db.Char(36)
  sku          String?        @db.VarChar(255)
  name         String         @db.VarChar(255)
  categoryId   String?
  category     Category?      @relation(fields: [categoryId], references: [id], onDelete: SetNull)
}
```

I have no issues when testing locally so i assume it has to do something with planetScale.

### How to reproduce

Tested Using Prisma Studio and from the code itself.

### Expected behavior

to create connection between many to many relationships

### Prisma information

prisma:  3.6.0
@prisma/client: 3.6.0

### Environment & setup

- OS:MacOS
- Database: PlanetScale MySql
- Node.js version: 14

### Prisma Version

```
prisma:  3.6.0
@prisma/client: 3.6.0
```

**Comment by janpio** [comment]
This looks related: https://github.com/prisma/prisma/discussions/10755 from @sbkl
As does this: https://github.com/prisma/prisma/discussions/10720 from @dextermb

**Comment by bardiaheshmati** [comment]
Updated the report and found where the bug is coming from. `Prisma` is creating a query that doesn't even exist

- Added more detailed replication envrioment
- Potentially found the root cause

**Comment by bardiaheshmati** [comment]
find attached project file for local testing
[ps.zip](https://github.com/prisma/prisma/files/7740719/ps.zip)

**Comment by janpio** [comment]
I can reproduce the error message with the schema you added to your message:

```
C:\Users\Jan\Documents\throwaway\10758>node script.js
{ id: 'a78cbbe6-0fba-4fa3-ab5b-9de4afc92072', name: 'foo' }
PrismaClientUnknownRequestError: 
Invalid `prisma.user.update()` invocation in
C:\Users\Jan\Documents\throwaway\10758\script.js:15:34

  12 })
  13 console.log(user)
  14 
→ 15 let update = await prisma.user.update(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol `10569`.`User`.id not found", state: "HY000" })) })
    at cb (C:\Users\Jan\Documents\throwaway\10758\node_modules\@prisma\client\runtime\index.js:38692:17)
    at async main (C:\Users\Jan\Documents\throwaway\10758\script.js:15:16) {
  clientVersion: '3.7.0'
}
```

My full script:
```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient({
  log: ['query', 'info', 'warn', 'error'],
})

// A `main` function so that we can use async/await
async function main() {

  let user = await prisma.user.create({
    data: {
      name: "foo"
    }
  })
  console.log(user)

  let update = await prisma.user.update({
    where: {
      id: user.id,
    },
    data: {
      name: 'name',
    },
  })
  console.log(update)


}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

And the full logging output I am getting:

```
C:\Users\Jan\Documents\throwaway\10758>node script.js
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\10758\.env +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\10758\.env +6ms
  prisma:client clientVersion: 3.7.0 +0ms
  prisma:client clientEngineType: library +1ms
  prisma:client:libraryEngine internalSetup +0ms
  prisma:client Prisma Client call: +15ms
  prisma:client prisma.user.create({
  prisma:client   data: {
  prisma:client     name: 'foo'
  prisma:client   }
  prisma:client }) +2ms
  prisma:client Generated request: +1ms
  prisma:client mutation {
  prisma:client   createOneUser(data: {
  prisma:client     name: "foo"
  prisma:client   }) {
  prisma:client     id
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: false +20ms
  prisma:client:libraryEngine Search for Query Engine Library in C:\Users\Jan\Documents\throwaway\10758\node_modules\.prisma\client +1ms
  prisma:client:libraryEngine loadEngine using C:\Users\Jan\Documents\throwaway\10758\node_modules\.prisma\client\query_engine-windows.dll.node +1ms
  prisma:client:libraryEngine library starting +39ms
prisma:info Starting a mysql pool with 9 connections.
  prisma:client:libraryEngine library started +399ms
prisma:query BEGIN
prisma:query INSERT INTO `10569`.`User` (`id`,`name`) VALUES (?,?)
prisma:query SELECT `10569`.`User`.`id`, `10569`.`User`.`name` FROM `10569`.`User` WHERE `10569`.`User`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
{ id: 'de9a0f33-acd3-402d-8fdc-21e1ee236fed', name: 'foo' }
  prisma:client Prisma Client call: +816ms
  prisma:client prisma.user.update({
  prisma:client   where: {
  prisma:client     id: 'de9a0f33-acd3-402d-8fdc-21e1ee236fed'
  prisma:client   },
  prisma:client   data: {
  prisma:client     name: 'name'
  prisma:client   }
  prisma:client }) +6ms
  prisma:client Generated request: +5ms
  prisma:client mutation {
  prisma:client   updateOneUser(
  prisma:client     where: {
  prisma:client       id: "de9a0f33-acd3-402d-8fdc-21e1ee236fed"
  prisma:client     }
  prisma:client     data: {
  prisma:client       name: "name"
  prisma:client     }
  prisma:client   ) {
  prisma:client     id
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +3ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +392ms
prisma:query BEGIN
prisma:query SELECT `10569`.`User`.`id` FROM `10569`.`User` WHERE `10569`.`User`.`id` = ?
prisma:query SELECT `10569`.`Profile`.`userId` FROM `10569`.`Profile` WHERE (1=1 AND `10569`.`Profile`.`userId` IN (?))
prisma:query SELECT `10569`.`User`.`id`, `10569`.`Profile`.`userId` FROM `10569`.`Profile` WHERE 1=0
prisma:query ROLLBACK
  prisma:client:fetcher Error: Error occurred during query execution:
  prisma:client:fetcher ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol `10569`.`User`.id not found", state: "HY000" })) })
  prisma:client:fetcher     at prismaGraphQLToJSError (C:\Users\Jan\Documents\throwaway\10758\node_modules\@prisma\client\runtime\index.js:35963:10)
  prisma:client:fetcher     at Object.request (C:\Users\Jan\Documents\throwaway\10758\node_modules\@prisma\client\runtime\index.js:36324:17)
  prisma:client:fetcher     at async cb (C:\Users\Jan\Documents\throwaway\10758\node_modules\@prisma\client\runtime\index.js:38658:26)
  prisma:client:fetcher     at async main (C:\Users\Jan\Documents\throwaway\10758\script.js:17:16) +0ms
PrismaClientUnknownRequestError:
Invalid `prisma.user.update()` invocation in
C:\Users\Jan\Documents\throwaway\10758\script.js:17:34

  14 })
  15 console.log(user)
  16
→ 17 let update = await prisma.user.update(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol `10569`.`User`.id not found", state: "HY000" })) })
    at cb (C:\Users\Jan\Documents\throwaway\10758\node_modules\@prisma\client\runtime\index.js:38692:17)
    at async main (C:\Users\Jan\Documents\throwaway\10758\script.js:17:16) {
  clientVersion: '3.7.0'
}
  prisma:client:libraryEngine hookProcess received: exit +337ms
  prisma:client:libraryEngine runBeforeExit +1ms
```

**Comment by janpio** [comment]
Removing `referentialIntegrity = "prisma"` temporarily from the Prisma schema without running `db push` or similar (!) causes the same script to work fine on PlanetScale. 

Same with a normal MySQL database, running `db push` to get a schema with foreign keys, and then running the script.

From that we can conclude that this is a problem of the emulated referential actions of the preview feature `referentialIntegrity` and setting its value to `prisma` (as required for PlanetScale).

**Comment by janpio** [comment]
Ok, deeper look into the problematic queries:

```
prisma:query SELECT `10569`.`User`.`id` FROM `10569`.`User` WHERE `10569`.`User`.`id` = ?
prisma:query SELECT `10569`.`Profile`.`userId` FROM `10569`.`Profile` WHERE (1=1 AND `10569`.`Profile`.`userId` IN (?))
prisma:query SELECT `10569`.`User`.`id`, `10569`.`Profile`.`userId` FROM `10569`.`Profile` WHERE 1=0
```

First one returns an ID, the second one returns nothing, and the third one uses `User.id` in the selection although the only table it is talking to is `Profile` => error message.

When the first `create` also creates a Profile, so the second query also returns the userId, the same broken third query is generated.

**Comment by janpio** [comment]
Had a quick look at our current documentation, and `onUpdate` is not supposed to really work with `referentialIntegrity = prisma` yet: https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-integrity#handling-the-referential-integrity-in-prisma That said, the current broken state is of course also not expected and instead we should not validate a schema using it. We will probably fail forward though and soon support these referential actions on update as well.

**Comment by bardiaheshmati** [comment]
> Removing `referentialIntegrity = "prisma"` temporarily from the Prisma schema without running `db push` or similar (!) causes the same script to work fine on PlanetScale. The log output looks like this then:
> 
> ```
>   prisma:client Prisma Client call: +699ms
>   prisma:client prisma.user.update({
>   prisma:client   where: {
>   prisma:client     id: 'c93eed48-b917-43a0-ae39-1a1df639bfde'
>   prisma:client   },
>   prisma:client   data: {
>   prisma:client     name: 'name'
>   prisma:client   }
>   prisma:client }) +1ms
>   prisma:client Generated request: +3ms
>   prisma:client mutation {
>   prisma:client   updateOneUser(
>   prisma:client     where: {
>   prisma:client       id: "c93eed48-b917-43a0-ae39-1a1df639bfde"
>   prisma:client     }
>   prisma:client     data: {
>   prisma:client       name: "name"
>   prisma:client     }
>   prisma:client   ) {
>   prisma:client     id
>   prisma:client     name
>   prisma:client   }
>   prisma:client }
>   prisma:client  +0ms
>   prisma:client:libraryEngine sending request, this.libraryStarted: true +302ms
> prisma:query BEGIN
> prisma:query SELECT `10569`.`User`.`id` FROM `10569`.`User` WHERE `10569`.`User`.`id` = ?
> prisma:query UPDATE `10569`.`User` SET `name` = ? WHERE `10569`.`User`.`id` IN (?)
> prisma:query SELECT `10569`.`User`.`id`, `10569`.`User`.`name` FROM `10569`.`User` WHERE `10569`.`User`.`id` = ? LIMIT ? OFFSET ?
> prisma:query COMMIT
> ```
> 
> Same with a normal MySQL database, running `db push` to get a schema with foreign keys, and then running the script - all fine.
> 
> From that we can conclude that this is a problem of the emulated referential actions of the preview feature `referentialIntegrity` and setting its value to `prisma` (as required for PlanetScale).

I've tested this, and it worked on a few examples that i tested. this could be a short term workaround. i used ```prisma db push ``` with ```referentialIntegrity = "prisma"``` and removed it at ```prisma generate```.

**Comment by janpio** [comment]
Setting `onUpdate: NoAction` might have similar effects than this @bardiaheshmati - let me know if you have time to try it out and it works.

**Comment by bardiaheshmati** [comment]
@janpio as you have mentioned i've updated my schema and added ```onUpdate: NoAction``` and created the following code:
```js
const user = await prisma.user.upsert({
    where: {
      id: "d02f60ef-e9dd-4a4e-9169-eec2f50d4d1c",
    },
    create: {
      id: "d02f60ef-e9dd-4a4e-9169-eec2f50d4d1c",
      name: "Johnnny",
      profile: {
        connectOrCreate: {
          where: {
            userId: "d02f60ef-e9dd-4a4e-9169-eec2f50d4d1c",
          },
          create: {
            name: "create profile Johnny",
          },
        },
      },
    },
    update: {
      name: "update name Johnny",
      profile: {
        upsert: {
          create: {
            name: "new profile Johnny",
          },
          update: {
            name: "profile update Johnny",
          },
        },
      },
    },
  });
```

this works and i think this kinda of does everything that a request might want to do. there's no difference having any referential ```onUpdate```  at all.
with or without ```onUpdate``` if i try and do something mad like 

```js
await prisma.user.update({
    where: {
      id: "d02f60ef-e9dd-4a4e-9169-eec2f50d4d1c",
    },
    data: {
      id: uuid(),
    },
});
```
it updates the user and leaves profile unchanged which breaks Prisma Studio as well.
omitting  ```referentialIntegrity = "prisma"``` in the schema basically kills all the referential connections.

**Comment by janpio** [comment]
Yes, but isn't that what you tried to achieve by after the fact changing the Prisma Schema file? That is very error prone (as e.g. the next `db push` will try to create foreign keys again) - so until this bug about `onUpdate: Cascade` is fixed (which it will, `referentialintegrity` currently is a preview feature expected to not be fully working) using `NoAction` might be the safer option.

**Comment by jde** [comment]
Thanks for addressing this! I've been working around this in my project. I just switched to `onUpdate: noAction` and can confirm that all update queries are working as expected now (without the cascade logic of course.) This is a workaround I can live with for a while.

**Comment by bardiaheshmati** [comment]
@janpio @jde  yes you're right, i've moved all the ```onUpdate```s to ```NoAction``` and it seems like it has resolved the issue for now.

**Comment by edmbn** [comment]
I recently had a similar problem. I couldn't update and the error was:

`Expected record selection to contain required model ID fields conversionFailure("/"d23ca13a-92bb-4b55-bc28-a029c86a906f"/", "Int")`.

It couldn't be a type error. The schema is correctly set and working perfectly on postreSQL. Now on Planetscale is happening this problem.

Also by setting `onUpdate` to `NoAction` solved the problem.

**Comment by janpio** [comment]
Can you open a separate issue @edmbn? That sounds like a separate, very interesting problem we would want to look into. Optimally you could include your Prisma schema and the SQL of your database. Bonus points if it is a minimal reproduction that just shows this problem. Thanks!

**Comment by smasala** [comment]
`3.6.x -> 3.8.1` I'm getting this error with many-to-many and one-to-many explicit relationships. If I follow the instructions here regarding `onUpdate` and `NoAction` the query attempts to access the relational table without the preceding `_`.

**Comment by janpio** [comment]
If you do not get the same error messages as in the original issue, please also open a new issue @smasala so we can discuss and debug this in isolation. Thanks.

**Comment by smasala** [comment]
@janpio it's definitely the same issue and error as recorded in the initial comment of this issue. However, the initial error mentioned here only happens for me when using explicit many-to-many relations (not implicit as shown above). If I use implicit many-to-many as demonstrated in this issue, the query is almost 100% correct, however the join table name is missing the `_` in the query.

**Comment by edmbn** [comment]
Yeah @janpio, did it here https://github.com/prisma/prisma/issues/11191. Thank you very much for the attention. If you need any help ask me there.

**Comment by smasala** [comment]
Typical, you spend hours trying to fix it and when you finally post something it works. Although it was strangely updating the queries and creating a new schema in planetscale (I could debug the newly generated files when switching from explicit to implicit relations) it was still picking up files either from the vscode local history extension (xyz.local-history) or dist folder at times and building incorrect queries randomly 🤷‍♂️ 

I can confirm that the workarounds mentioned here work for both implicit and explicit.

**Comment by focux** [comment]
I'm also experiencing this same issue with an explicit many-to-many relation. I can also confirm that the work-around posted here of removing `referentialIntegrity = "prisma"` and then re-generating the client without running `db push` work as expected.

**Comment by jde** [comment]
> Typical, you spend hours trying to fix it and when you finally post something... it works. 

I've had this experience literally hundreds of times in the 2+ decades I've been doing this. For years I used the exact same language: "it works." I wrote it off to some problem or other with the code, or whatever.

Over the years I've changed my reaction to these situations. Now, I find that these are pathways to deepening your understandings of the systems you're using. Instead of "it didn't work and now it works", try "I don't understand what changed." It's an exercise in understanding yourself as much as the software. 

If you can find the difference between then and now, you're likely to build reflexes so that next time you'll intuit this and make it part of your workflow, avoiding the problem all together. You'll learn from the painful experience. You'll become a better engineer.

If you really can't find the problem you shouldn't trust your software, or at least it should lower your trust. I've been in situations where I needed to figure things out that seemed to come from nowhere but were preventing millions of customers from doing the thing they came to do. You can't look a ceo in the eye and say "it works and now it doesn't". Once you've made your way up to that level of responsibility you get allergic to uncertainty. You just don't use that tech or that pattern anymore when it's important... and everything is important.

Just my 2 cents.

**Comment by dmacdermott** [comment]
Any update on when this will be fixed? Currently on 3.11 and I'm having to do the "regenerate client without pushing" fix to get it working and OnUpdate: NoAction doesn't seem to work.

**Comment by jacksonblankenship** [comment]
I'm having a pretty tough time dealing with this as well. Here is my schema...

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Employment {
  id        Int    @id @default(autoincrement())
  title     String
  employer  String
  startDate String
  endDate   String
  summary   String @db.Text
  resume    Resume @relation(fields: [resumeId], references: [id], onDelete: Cascade, onUpdate: NoAction)
  resumeId  Int

  @@index([resumeId])
}

model Education {
  id          Int    @id @default(autoincrement())
  degree      String
  institution String
  startDate   String
  endDate     String
  resume      Resume @relation(fields: [resumeId], references: [id], onDelete: Cascade, onUpdate: NoAction)
  resumeId    Int

  @@index([resumeId])
}

model Resume {
  id         Int            @id @default(autoincrement())
  createdAt  DateTime       @default(now())
  updatedAt  DateTime       @updatedAt
  firstName  String
  lastName   String
  jobTitle   String
  summary    String         @db.Text
  employment Employment[]
  education  Education[]
  skills     ResumeSkills[]
}

model Skill {
  id        Int            @id @default(autoincrement())
  createdAt DateTime       @default(now())
  name      String         @unique
  resumes   ResumeSkills[]
}

model ResumeSkills {
  resume   Resume @relation(fields: [resumeId], references: [id], onDelete: Cascade, onUpdate: NoAction)
  resumeId Int
  skill    Skill  @relation(fields: [skillId], references: [id], onDelete: Cascade, onUpdate: NoAction)
  skillId  Int

  @@id([resumeId, skillId])
}
```

I'm having trouble with the `Resume` table. I'm able to update records without issue, but when I try to delete them I get the following error.

> Type: undefined
> Message: 
> Invalid `prisma.resume.delete()` invocation:
> 
> 
>   Error occurred during query execution:
> ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol comet.Resume.id not found", state: "HY000" })) })
> 
> Code: undefined
> 
> Query:
> [object Object]

When I change the `onDelete` flag to `SetNull` I can delete the record, but when I try to view the many-to-many table `ResumeSkill` it gets mad at me because some of the foreign keys are now null. When I remove `onDelete` altogether the operation fails because it breaks the contract for the many-to-many table.

I'm kind of between a rock and a hard place and I'm not sure what to do. Having trouble finding answers online for this, too. Aybody have any suggestions?

**Comment by janpio** [comment]
No update on fixes to the referentialIntegrity feature right now unfortunately. We'll get to it though, and seems you all have the same error here so at least this will be 1 fix for all of these.

**Comment by steven-tey** [comment]
Facing a similar error as well – I am trying to delete a record that is connected to another record via `onDelete: Cascade` but it won't let me delete – I'm getting the following error: 

```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol db.Model.attribute not found", state: "HY000" })) })
```

When I remove `referentialIntegrity = "prisma"` the delete of the first record goes through but the related records are not deleted.

**Comment by janpio** [comment]
This also affects non PlanetScale (MySQL 8) databases: https://github.com/prisma/prisma/issues/12810 
Note the full schema and script for reproduction there: https://github.com/prisma/prisma/issues/12810#issuecomment-1098427246
