### ISSUE TITLE
Better Schema validation for MongoDB

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#10809]
## Problem

I had the following schema

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
  id    String @id @default(dbgenerated()) @map("_id") @db.String
  name  String
  posts Post[]
}

model Post {
  id     String  @id @default(dbgenerated()) @map("_id") @db.String
  title  String
  User   User   @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId String
}
```

There's a subtle bug in this schema. Can you spot it? Validation doesn't catch it, db push says it works, but when I go to `create` or `upsert`, I get the following runtime error:

```
PrismaClientUnknownRequestError: 
Invalid `prisma.user.create()` invocation in
/Users/m/dev/src/github.com/prisma/ra/index.ts:37:21

  34 //     },
  35 //   ],
  36 // })
→ 37 await prisma.user.create(
  Query createOneUser is required to return data, but found no record(s).
    at cb (/Users/m/dev/src/github.com/prisma/ra/node_modules/@prisma/client/runtime/index.js:38692:17)
    at main (/Users/m/dev/src/github.com/prisma/ra/index.ts:37:3) {
  clientVersion: '3.7.0'
}
```

The correct schema is the following:

```diff
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
+ id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
-  id    String @id @default(dbgenerated()) @map("_id") @db.String
  name  String
  posts Post[]
}

model Post {
+ id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
-  id    String @id @default(dbgenerated()) @map("_id") @db.String
  title  String
  User   User   @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId String
}
```

Interestingly, `createMany` works as expected, I guess because it doesn't return the data.

## Suggested solution

Decide if this should work or not. If not, catch this at build-time. Either during validate, migrate or generate.

**Comment by janpio** [comment]
Do I understand correctly that the "incorrect" part is indeed only the `@db.string`, so we could potentially validate that `@id` on MongoDB always and only has `@db.ObjectId`?

**Comment by janpio** [comment]
Note: The `@id` line should only allow `dbgenerated()` (or soon `auto()`) when native type `@db.ObjectId` is present.

**Comment by pimeys** [comment]
Closed in https://github.com/prisma/prisma-engines/pull/2648

**Comment by pimeys** [comment]
![2022-02-03_19-02-1643912454](https://user-images.githubusercontent.com/34967/152404622-bae323dc-8440-42f8-84f6-2533ee3760ac.png)
