### ISSUE TITLE
Prisma requires relation field when adding related record with compound key

### ISSUE THREAD

**Issue by dariusj18** [prisma/prisma#10834]
### Bug description

If I have a compound key that is also a relation key, when attempting to create a related record it requires me to include the key field in the related record.

### How to reproduce

See code example index.ts file with error. (will attach after issue created)

### Expected behavior

Related records are created with the compound key fields autofilled

### Prisma information

datasource db {
  url      = env("DATABASE_URL")
  provider = "postgres"
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

model User {
  id         String   @id @default(uuid()) @db.Uuid
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
  username   String   @unique

  posts Post[]
  postMetas PostMeta[]
}

model Post {
  id         String   @id @default(uuid()) @db.Uuid
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
  title      String

  user   User @relation(fields: [userId], references: [id])
  userId String   @db.Uuid

  postMetas PostMeta[]
  @@unique([id, userId])
}

model PostMeta {
  id         String   @id @default(uuid()) @db.Uuid
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
  is_deleted Boolean  @default(false)

  user   User @relation(fields: [userId], references: [id])
  userId String   @db.Uuid

  post   Post @relation(fields: [postId, userId], references: [id, userId])
  postId String   @db.Uuid
}

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: 14.18.2

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0
Preview Features        : interactiveTransactions
```

**Comment by pantharshit00** [comment]
`user` is not required. I am able to run the query fine without it: 
![image](https://user-images.githubusercontent.com/22195362/147251027-950db780-ddf0-4eb1-a82d-cdb49ef46fe0.png)


Can you please confirm that I understood the problem correctly here or you are asking for something else?

**Comment by dariusj18** [comment]
Ok, I see the issue now and pushed a change to recreate it.  It's because the `PostMetaCreateWithoutPostInput` type has the `user` field required, whereas the `PostMetaUncheckedCreateWithoutPostInput` type does not.  So in effect even though the `userId` is supposed to be populated by the relation, the checked type still includes it as required.

Here's the error message if I add a ts-ignore and let it run

```
(node:34336) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.post.create()` invocation in
PROJECT_PATH\prisma_playground\index.ts:13:34

  10 })
  11
  12 async function main() {
→ 13   const post = await prisma.post.create({
         data: {
           title: 'test',
           user: {
             connect: {
               id: '62edd1de-868b-4698-b802-b7eb030ace4e'
             }
           },
           postMetas: {
             create: {
               type: {
                 connect: {
                   id: 'a38e3f17-cf6d-43f0-89ba-2673d0c77050'
                 }
               },
       +       user: {
       +         create?: UserCreateWithoutPostMetasInput | UserUncheckedCreateWithoutPostMetasInput,
       +         connectOrCreate?: UserCreateOrConnectWithoutPostMetasInput,
       +         connect?: UserWhereUniqueInput
       +       },
       ?       id?: String,
       ?       createdAt?: DateTime,
       ?       updatedAt?: DateTime,
       ?       is_deleted?: Boolean
             }
           }
         },
         include: {
           postMetas: {}
         }
       })

Argument user for data.postMetas.create.user is missing.

Note: Lines with + are required, lines with ? are optional.

    at Object.validate (PROJECT_PATH\prisma_playground\node_modules\@prisma\client\runtime\index.js:34755:20)
    at PrismaClient._executeRequest (PROJECT_PATH\prisma_playground\node_modules\@prisma\client\runtime\index.js:39749:17)  
    at consumer (PROJECT_PATH\prisma_playground\node_modules\@prisma\client\runtime\index.js:39690:23)
    at PROJECT_PATH\prisma_playground\node_modules\@prisma\client\runtime\index.js:39694:49
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at PrismaClient._request (PROJECT_PATH\prisma_playground\node_modules\@prisma\client\runtime\index.js:39694:27)
    at request (PROJECT_PATH\prisma_playground\node_modules\@prisma\client\runtime\index.js:39799:77)
    at _callback (PROJECT_PATH\prisma_playground\node_modules\@prisma\client\runtime\index.js:40007:14)
    at PrismaPromise.then (PROJECT_PATH\prisma_playground\node_modules\@prisma\client\runtime\index.js:40014:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:34336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dariusj18** [comment]
And using the Unchecked type doesn't really work if you need to also create a relation for the relation.

**Comment by dariusj18** [comment]
@pantharshit00 not sure if you saw my response above

**Comment by pantharshit00** [comment]
Hey! Thanks for the more details, I can confirm the bug here now. Behaviour should generally match across both input types.
