### ISSUE TITLE
Prisma Studio cannot be started with the packaged CLI

### ISSUE THREAD

**Issue by RobertCraigie** [prisma/prisma#10917]
### Bug description

Running `prisma studio` launches the studio in the browser and then crashes:

```
Environment variables loaded from .env
Prisma schema loaded from tests/data/schema.prisma
Prisma Studio is up on http://localhost:5555
Unable to get DMMF from Prisma Client:  AggregateError: 
    Error: Generator at /snapshot/node_modules/prisma/prisma-client/generator-build/index.js could not start:
    internal/modules/cjs/loader.js:967
      throw err;
      ^
    Error: Cannot find module '/prisma-client-py/--max-old-space-size=8096'
        at Function._resolveFilename (pkg/prelude/bootstrap.js:1459:46)
        at Function.runMain (pkg/prelude/bootstrap.js:1488:12)
        at internal/main/run_main_module.js:17:47 {
      code: 'MODULE_NOT_FOUND',
      requireStack: []
    }
        at Timeout._onTimeout (/snapshot/node_modules/prisma/build/index.js:37450:25)
    at next (/snapshot/node_modules/prisma/build/index.js:17854:25)
    at /snapshot/node_modules/prisma/build/index.js:17875:17
```

Should be noted that the standalone Prisma Studio app and running with `npx prisma studio` can both be successfully launched.

### How to reproduce

```sh
#!/bin/bash

set -eux

git clone https://github.com/RobertCraigie/prisma-client-py
cd prisma-client-py

python3 -m venv .venv

set +x
source .venv/bin/activate
set -x

pip install -U -e .

python -m prisma studio --schema=tests/data/schema.prisma
```

This will either hang or crash.

### Expected behavior

The studio should be launched successfully.

### Prisma information

```prisma
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

generator db {
  provider               = "prisma-client-py"
  interface              = "asyncio"
  recursive_type_depth   = 5
  partial_type_generator = "tests/scripts/partial_type_generator.py"
}

model Post {
  id         String     @id @default(cuid())
  created_at DateTime   @default(now())
  updated_at DateTime   @updatedAt
  title      String
  published  Boolean
  views      Int        @default(0)
  desc       String?
  author     User?      @relation(fields: [author_id], references: [id])
  author_id  String?
  categories Category[] @relation(references: [id])
}

model User {
  id      String   @id @default(cuid())
  name    String
  email   String?  @unique
  posts   Post[]
  profile Profile?
}

model Category {
  id    Int    @id @default(autoincrement())
  posts Post[] @relation(references: [id])
  name  String
}

model Profile {
  id      Int    @id @default(autoincrement())
  user    User   @relation(fields: [user_id], references: [id])
  user_id String @unique
  bio     String
}

// model that just exists for testing different schema types
model Types {
  id       Int      @id @default(autoincrement())
  bool_    Boolean  @default(false)
  string   String   @default("")
  bytes    Bytes    @default("")
  bigint   BigInt   @default(0)
  integer  Int      @default(0)
  float_   Float    @default(0)
  datetime DateTime @default(now())
}
```

### Environment & setup

- OS:  Mac OS
- Database:  SQLite
- Node.js version:  N/A

### Prisma Version

```
prisma                : 3.7.0
@prisma/client        : Not found
Current platform      : darwin
Query Engine (Binary) : query-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at ../../../../../../../var/folders/ql/0v8h20s972s6zz4t_3qc49bc0000gp/T/prisma/binaries/engines/8746e055198f517658c08a0c426c7eec87f5a85f/prisma-query-engine-darwin, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine      : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at ../../../../../../../var/folders/ql/0v8h20s972s6zz4t_3qc49bc0000gp/T/prisma/binaries/engines/8746e055198f517658c08a0c426c7eec87f5a85f/prisma-migration-engine-darwin, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine  : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at ../../../../../../../var/folders/ql/0v8h20s972s6zz4t_3qc49bc0000gp/T/prisma/binaries/engines/8746e055198f517658c08a0c426c7eec87f5a85f/prisma-introspection-engine-darwin, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary         : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at ../../../../../../../var/folders/ql/0v8h20s972s6zz4t_3qc49bc0000gp/T/prisma/binaries/engines/8746e055198f517658c08a0c426c7eec87f5a85f/prisma-prisma-fmt-darwin, resolved by PRISMA_FMT_BINARY)
Default Engines Hash  : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                : 0.445.0
```

**Comment by janpio** [comment]
Sounds related to https://github.com/prisma/prisma/issues/10564 - under the hood Studio also uses a generated Prisma Client, so if generating is not possible, using Prisma Studio is also not possible.

**Comment by Milo123459** [comment]
Hate to be that guy, but any updates?

PS: If there haven't been any, I'd like to work on this.

**Comment by janpio** [comment]
No updates and also no high priority, so if you want to take a look feel free.

**Comment by max-programming** [comment]
@RobertCraigie Is there a workaround as of now :thinking: ?

**Comment by RobertCraigie** [comment]
@max-programming Currently there are two other possible ways to use Prisma Studio:

1. Download the Prisma Studio app

   Prisma Studio can be downloaded from: https://github.com/prisma/studio/releases

2. Use the Node based Prisma CLI:

   If you have Node / NPX installed you can launch Prisma Studio by running the command: npx prisma studio

However I am actively working on removing the use of the packaged CLI to begin with, so this issue should be fixed in the next release.

**Comment by max-programming** [comment]
Thanks a lot @RobertCraigie :smile: !

Just FYI I was stuck while generating the client too and I realized I had to change `prisma-client.js` to `prisma-client.py` manually.
