### ISSUE TITLE
Support for `@>` and `<@` operators when working with full-text-search

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma#10933]
## Problem

[Prisma docs/full-text-search](https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search#query-format) state that Prisma Client supports operators that [Postgres](https://www.postgresql.org/docs/12/functions-textsearch.html) supports. 

![image](https://user-images.githubusercontent.com/33921841/147945043-09eea89f-05e1-4a52-b9fc-3d3dbc790029.png)

When I tried executing a query using the `@>` or `<@`, Prisma Client returned the following error:

```bash
{ query: 'tom <@ sawyer' } // not related to the Prisma client error
{
  error: PrismaClientUnknownRequestError: 
  Invalid `prisma.book.findMany()` invocation:
  
  
    Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "syntax error in tsquery: \"tom sawyer\"", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("tsquery.c"), line: Some(689), routine: Some("makepol") }) }) })
      at cb (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/@prisma/client/runtime/index.js:38692:17)
      at async handler (webpack-internal:///./pages/api/search.ts:40:29)
      at async Object.apiResolver (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/api-utils.js:102:9)
      at async DevServer.handleApiRequest (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/next-server.js:1064:9)
      at async Object.fn (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/next-server.js:951:37)
      at async Router.execute (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/router.js:222:32)
      at async DevServer.run (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/next-server.js:1135:29)
      at async DevServer.run (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/dev/next-dev-server.js:445:20)
      at async DevServer.handleRequest (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/next-server.js:325:20) {
    clientVersion: '3.7.0'
  }
}
```

## Suggested solution

It would be worth noting explicitly the operators Prisma client supports in the docs or provide more concrete examples of how it works/ use it.

**Comment by Weakky** [comment]
The operators you're mentioning are _Postgres_ operators, not _query_ operators. The link provided in the documentation is misleading.

Below are the query operators Postgres supports, with the addition of `<->` that I couldn't find documented anywhere:

![image](https://user-images.githubusercontent.com/25233379/148044568-00a20b5b-b77d-4045-b2e1-3fe8d76edf72.png)

This is more of a documentation issue. I, unfortunately, couldn't find any proper documentation on all the supported query operators.

I'll leave it open and hand it over to the docs team.

**Comment by janpio** [comment]
I think the link on https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search#querying-the-database has been fixed. Can you confirm @ruheni?

**Comment by ruheni** [comment]
Yes
