### ISSUE TITLE
[Introspection] Model validation fails on pivot table

### ISSUE THREAD

**Issue by jcloutz-radix** [prisma/prisma#1093]
I am unable to introspect a simple database schema when using a pivot table. There are 2 issues here:
1. The introspection fails on the pivot table because it doesn't have a primary key which should still be valid. This could be related to #1083.
2. I'm not sure that `GroupToUser` is being detected as a pivot table. Based on the error output it looks like its trying to create a `user_groupses user_groups[]` property on the User and Group model. Based on the way that Lift generates the client code it should it should add a `users User[]` and `groups Group[]` property to the respective models.
3. If i add an `_` to the pivot table name similar to lift i get exception.

Assuming the following sqlite schema:
```sql
create table "Group"
(
	id integer not null
		primary key autoincrement,
	name varchar(255)
);

create table User
(
	id integer not null
		primary key autoincrement,
	email varchar(255) not null,
	password varchar(255) not null,
	created_at datetime,
	updated_at datetime
);

create table GroupToUser
(
	user_id integer
		references User,
	group_id integer
		references "Group"
);

```

I receive the following error: 
```
Introspection failed: Introspected schema can't be parsed.
Introspected Schema:

model User {
  created_at   DateTime?
  email        String        @unique
  id           Int           @id
  password     String
  updated_at   DateTime?
  groupToUsers GroupToUser[]
}

model Group {
  id           Int           @id
  name         String?
  groupToUsers GroupToUser[] @relation(references: [group_id])
}

model GroupToUser {
  group_id Group?
  user_id  User?
}

Error: Schema parsing
error: Error validating model "GroupToUser": Each model must have exactly one id criteria. Either mark a single field with `@id` or add a multi field id criterion with `@@id([])` to the model..
  -->  schema.prisma:28
   |
27 |
28 | model GroupToUser {
29 |   group_id Group?
   |
    at Object.<anonymous> (C:\Users\jeremycloutier\develop\labs\prisma\test-project\node_modules\prisma2\build\index.js:73435:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\jeremycloutier\develop\labs\prisma\test-project\node_modules\prisma2\build\index.js:73330:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

When attempting to add a compound primary key to the GroupToUser table the rust library throws an exception:
```
Introspection failed: Introspected schema can't be parsed.
Introspected Schema:

model User {
  created_at   DateTime?
  email        String        @unique
  id           Int           @id
  password     String
  updated_at   DateTime?
  groupToUsers GroupToUser[]
}

model Group {
  id           Int           @id
  name         String?
  groupToUsers GroupToUser[] @relation(references: [group_id])
}

model GroupToUser {
  group_id Group?
  user_id  User?

  @@id([user_id, group_id])
}

Error: Schema parsing
thread 'main' panicked at 'No id field defined!', src\libcore\option.rs:1190:5
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:60
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src\libstd/panicking.rs:380
  12: rust_begin_unwind
             at src\libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src\libcore/panicking.rs:85
  14: core::option::expect_failed
             at src\libcore/option.rs:1190
  15: once_cell::imp::OnceCell<T>::initialize::{{closure}}
  16: once_cell::imp::initialize_inner
  17: once_cell::imp::OnceCell<T>::initialize
  18: prisma_models::fields::Fields::id
  19: query_core::schema_builder::object_type_builder::ObjectTypeBuilder::many_records_arguments
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  21: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  23: query_core::schema_builder::object_type_builder::ObjectTypeBuilder::new
  24: query_core::schema_builder::query_schema_builder::QuerySchemaBuilder::new
  25: prisma::cli::CliCommand::execute
  26: <std::future::GenFuture<T> as core::future::future::Future>::poll
  27: tokio::runtime::global::with_thread_pool
  28: tokio::runtime::global::with_state
  29: tokio::runtime::spawner::Spawner::enter
  30: tokio::runtime::time::variant::with_default
  31: std::thread::local::LocalKey<T>::with
  32: prisma::main
  33: std::rt::lang_start::{{closure}}
  34: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:49
  35: std::panicking::try::do_call
             at src\libstd/panicking.rs:292
  36: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:80
  37: std::panicking::try
             at src\libstd/panicking.rs:271
  38: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  39: std::rt::lang_start_internal
             at src\libstd/rt.rs:48
  40: main
  41: _tmainCRTStartup
  42: mainCRTStartup
  43: sqlite3GenerateConstraintChecks
  44: sqlite3GenerateConstraintChecks
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at Object.<anonymous> (C:\Users\jeremycloutier\develop\labs\prisma\test-project\node_modules\prisma2\build\index.js:73435:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\jeremycloutier\develop\labs\prisma\test-project\node_modules\prisma2\build\index.js:73330:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

When adding an underscore to the pivot table name i get the following error:
```
Introspection failed: Introspected schema can't be parsed.
Introspected Schema:

model User {
  created_at    DateTime?
  email         String         @unique
  id            Int            @id
  password      String
  updated_at    DateTime?
  _GroupToUsers _GroupToUser[] @relation(references: [user_id])
}

model Group {
  id            Int            @id
  name          String?
  _GroupToUsers _GroupToUser[] @relation(references: [group_id])
}

model _GroupToUser {
  group_id Group?
  user_id  User?

  @@id([user_id, group_id])
}

Error: Schema parsing
error: Unexpected token. Expected one of: End of block ("}"), field declaration.
  -->  schema.prisma:19
   |
18 |   updated_at    DateTime?
19 |   _GroupToUsers _GroupToUser[] @relation(references: [user_id])
   |   ^ Unexpected token.
20 | }
   |
    at Object.<anonymous> (C:\Users\jeremycloutier\develop\labs\prisma\test-project\node_modules\prisma2\build\index.js:73435:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\jeremycloutier\develop\labs\prisma\test-project\node_modules\prisma2\build\index.js:73330:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by janpio** [comment]
Thanks @jcloutz-radix, you just made a journey through 3 of the known problems with Introspection:

1. Introspection correctly infers a model without a primary key, the validator does not like that (and the Query Engine can currently not handle that)
2. Compound primary keys are correctly inferred, but are not recognized by the Query Engine
3. Table and column names starting with underscores are currently not supported

We of course know that all of these should work just fine, and working on fixing these bugs.

**Comment by janpio** [comment]
The underscore problem should now be solved in new alphas via #1139. Progress!

**Comment by janpio** [comment]
Can you please see what happens here with the current `alpha` @pantharshit00? Thanks.

**Comment by pantharshit00** [comment]
In `prisma2@2.0.0-preview022, binary version: f608db3b9e4f50f9a384356e532357b0a525969a`, I am getting the following panic after introspecting.
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/22195362/74757765-75072600-529c-11ea-8348-01453eff86c0.png">


Error goes away if I remove the pivot table.

**Comment by janpio** [comment]
Can you please submit the error and post the error ID here? This might be unrelated.

**Comment by pantharshit00** [comment]
It is not giving me an error report ID. 
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/22195362/74822000-78e18980-532a-11ea-9896-5dfb906492f7.png">


I also can't find it in the internal dashboard.

**Comment by janpio** [comment]
I can reproduce both problems as well @pantharshit00.

2 new issues:
- Introspection failure: https://github.com/prisma/prisma2/issues/1648
- Error reporting failure: https://github.com/prisma/prisma2/issues/1649

**Comment by janpio** [comment]
Let's wait until those are fixed, and try to reproduce here again.

**Comment by janpio** [comment]
Hey @jcloutz-radix, back to your initial issue:

Re 1) The modified schema with an added compound primary key should now be supported in a current `alpha` version:

```prisma
model User {
  created_at   DateTime?
  email        String        @unique
  id           Int           @id
  password     String
  updated_at   DateTime?
  groupToUsers GroupToUser[]
}

model Group {
  id           Int           @id
  name         String?
  groupToUsers GroupToUser[] @relation(references: [group_id])
}

model GroupToUser {
  group_id Group?
  user_id  User?

  @@id([user_id, group_id])
}
```

This is a pretty clean database design, so we are happy to suggest our users to use this for now. Do you agree?

The model `GroupToUser` without the `@@id` unfortunately is not supported and will also stay unsupported for some time - for now we always need a unique thing in a table (like a primary key or a unique index).

---

Re 2)

> I'm not sure that `GroupToUser` is being detected as a pivot table. Based on the error output it looks like its trying to create a `user_groupses user_groups[]` property on the User and Group model. Based on the way that Lift generates the client code it should it should add a `users User[]` and `groups Group[]` property to the respective models.

For that to happen the pivot table has to be in a very special format right now. You can look at it if you write the model out as you suggested, then use the experimental `prisma2 migrate` to create the tables for you:

```prisma
model User {
  created_at DateTime?
  email      String    @unique
  id         Int       @id
  password   String
  updated_at DateTime?
  groups     Group[]
}

model Group {
  id    Int     @id
  name  String?
  users User[]
}
```

this creates the following SQL:

```sql
CREATE TABLE IF NOT EXISTS "_GroupToUser" (
	"A"	INTEGER NOT NULL,
	"B"	INTEGER NOT NULL,
	FOREIGN KEY("A") REFERENCES "Group"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("B") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Group" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "User" (
	"created_at"	DATE,
	"email"	TEXT NOT NULL DEFAULT '',
	"id"	INTEGER NOT NULL,
	"password"	TEXT NOT NULL DEFAULT '',
	"updated_at"	DATE,
	PRIMARY KEY("id")
);

CREATE INDEX IF NOT EXISTS "_GroupToUser_B_index" ON "_GroupToUser" (
	"B"
);

CREATE UNIQUE INDEX IF NOT EXISTS "_GroupToUser_AB_unique" ON "_GroupToUser" (
	"A",
	"B"
);

CREATE UNIQUE INDEX IF NOT EXISTS "User.email" ON "User" (
	"email"
);
```

Introspection requires the `A` and `B` columns with their respective foreign keys, the index and unique index, and the underscore at the beginning of the table name for this to be picked up. The rest of the table name defines the relation name (and is dropped it it is a combination of the to table names, sorted alphabetically, connected with `To` [`User` + `Group` => `_GroupToUser`]).

**Comment by do4gr** [comment]
As @janpio mentioned this scenario should now work with either of the two approaches he posted. Here is the current documentation for scenario 2 https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/relations#conventions-for-relation-tables-in-implicit-m-n-relations

If you are still running into problems please let us know.
