### ISSUE TITLE
Full-text search doesn't work with filter operators/ conditions – `OR`

### ISSUE THREAD

**Issue by ruheni** [prisma/prisma#10930]
### Bug description

Executing the following query throws an error when using the `OR` operator with full-text search:

```typescript
const query = 'Prisma rocks'.split(' ').join('&')

const results = await prisma.book.findMany({
  where: {
    OR: {
      title: {
        search: query
      },
      content: {
        search: query
      }
    }
  },
})
```

The following error is thrown by Prisma Client:

```bash
{ query: 'Prisma & rocks' }
{
  error: PrismaClientUnknownRequestError: 
  Invalid `prisma.book.findMany()` invocation:
  
  
    Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "syntax error in tsquery: \"david copperfield\"", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("tsquery.c"), line: Some(689), routine: Some("makepol") }) }) })
      at cb (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/@prisma/client/runtime/index.js:38692:17)
      at async handler (webpack-internal:///./pages/api/search.ts:40:29)
      at async Object.apiResolver (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/api-utils.js:102:9)
      at async DevServer.handleApiRequest (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/next-server.js:1064:9)
      at async Object.fn (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/next-server.js:951:37)
      at async Router.execute (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/router.js:222:32)
      at async DevServer.run (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/next-server.js:1135:29)
      at async DevServer.run (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/dev/next-dev-server.js:445:20)
      at async DevServer.handleRequest (/Users/ruheni/Documents/repos/work/prisma/projects/prisma-fulltextsearch/node_modules/next/dist/server/next-server.js:325:20) {
    clientVersion: '3.7.0'
  }
```

If filter operators are not supposed to work when paired with full-text search, we should provide some level of type-safety around it.

### How to reproduce

Query
```typescript
const query = 'Prisma rocks'.split(' ').join(' & ')

const results = await prisma.book.findMany({
  where: {
    OR: {
      title: {
        search: query
      },
      content: {
        search: query
      }
    }
  },
})
```

### Expected behavior

No error if the query is executed, or provide type safety that filter operators can't be used when using FTS

### Prisma information

Schema:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Book {
  id      Int      @id @default(autoincrement())
  title   String
  content String
  url     String
  cover   String
  authors String[]
}
```

Migration

### Environment & setup

- OS:  Mac OS
- Database: PostgreSQL
- Node.js version: 16.13

### Prisma Version

```
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0
Preview Features        : fullTextSearch
```

**Comment by ruheni** [comment]
This was a mistake on my end. There's no bug here 🙂
