### ISSUE TITLE
Prisma queries not working for postgresql- "Can't reach database server", but everything else can reach the DB

### ISSUE THREAD

**Issue by ivan7707** [prisma/prisma#10945]
### Bug description

Hello, I am using prisma, docker (server, postgres, and react in different containers), apollo, postgres, express. 

I have hooked it all together.  

**What works:**

- Prisma migrations create and update the database beautifully
- Prisma studio can view and add records just fine
- Seeding the database (using prisma upserts)
- Graphiql/studio.apollographql
- postgres-node calls to the database from the host machine
- pgadmin4 from the host machine

`What doesn't work`
- prisma queries in my resolvers, either through the the model or raw sql queries. 

The thing that is stumping me is that the DB is reachable everywhere else (including Prisma studio).  

I am stumped.  

Error response in the apollo studio

```
{
  "errors": [
    {
      "message": "\nInvalid `context.prisma.user.findMany()` invocation in\n/api/resolvers.ts:12:40\n\n   9 Query: {\n  10     hello: () => { return ['Hello World!', 'Hello World #2', 'Hello World #3'] },\n  11     allUsers: async (_: any, __: any, context: Context) => {\n→ 12         return context.prisma.user.findMany(\n  Can't reach database server at `localhost`:`5432`\n\nPlease make sure your database server is running at `localhost`:`5432`.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allUsers"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "clientVersion": "3.7.0",
          "stacktrace": [
            "Error: ",
            "Invalid `context.prisma.user.findMany()` invocation in",
            "/api/resolvers.ts:12:40",
            "",
            "   9 Query: {",
            "  10     hello: () => { return ['Hello World!', 'Hello World #2', 'Hello World #3'] },",
            "  11     allUsers: async (_: any, __: any, context: Context) => {",
            "→ 12         return context.prisma.user.findMany(",
            "  Can't reach database server at `localhost`:`5432`",
            "",
            "Please make sure your database server is running at `localhost`:`5432`.",
            "    at cb (/api/node_modules/@prisma/client/runtime/index.js:38694:17)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

### Prisma information

PRISMA SETUP

context.ts
```
import { PrismaClient } from '@prisma/client'

export interface Context {
  prisma: PrismaClient
}

const prisma = new PrismaClient()

export const context: Context = {
  prisma: prisma,
}

```

schema.prisma

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id         Int    @id @default(autoincrement())
  email      String
  username   String
  idp        String
  oid        String
}

```

EVERYTHING ELSE
resolvers.ts 

```
import { prisma } from '@prisma/client';
import { Context } from './prisma/context';

const resolvers:any = {
    Query: {
        hello: () => { return ['Hello World!', 'Hello World #2', 'Hello World #3'] },
        allUsers: async (_: any, __: any, context: Context) => {
            return context.prisma.user.findMany()
        },
        allUsers2: async (_: any, __: any, context: Context) => {
            return context.prisma.$queryRaw`SELECT * from public."User"`
        },
        user: async () => {
            return {'username': 'Ivan',
                    'email': 'ivan@ivan.ca',
                    'idp': 'google.com',
                    'oid': 'asdfasdfasdf'}
                   } 
                   
    }
}

export default resolvers;
```

typeDefs.ts

```
import { gql } from 'apollo-server-express';

const typeDefs = gql`
    type Query {
        hello: [String]
        allUsers: [User!]!
        allUsers2: [User!]!
        user: User
        
    }

    type User {
        id: ID!
        username: String!
        email: String!
        idp: String!
        oid: String!
    }

`

export default typeDefs; 
```

server.ts

```
import express, {Request, Response} from 'express';
import morgan from 'morgan';
const cors = require('cors')

// graphql setup
import { ApolloServer } from 'apollo-server-express';
import { ApolloServerPluginDrainHttpServer } from 'apollo-server-core';
import typeDefs from "./typeDefs";
import resolvers from "./resolvers";
import http from 'http';
import { context } from './prisma/context';

const app = express();

async function startApolloServer(typeDefs: any, resolvers: any) {
  const httpServer = http.createServer(app);
  const server = new ApolloServer({
    context: context,
    typeDefs,
    resolvers,
    plugins: [ApolloServerPluginDrainHttpServer({ httpServer })],
 
  });
  await server.start();
  server.applyMiddleware({ app });
  
}

startApolloServer(typeDefs, resolvers); 



app.use(express.urlencoded({ extended: true }));
app.use(express.json());

app.use(morgan('dev'));

//enable CORS (for testing only -remove in production/deployment)
app.use(cors()) // enable `cors` to set HTTP response header: Access-Control-Allow-Origin: *
app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Headers', 'Authorization, Origin, X-Requested-With, Content-Type, Accept');
    next();
});

app.get('/', 
(req, res) => {
    res.send('test REST')
})

const port = process.env.PORT || 5000;

app.listen(port, () => {
    console.log('Listening on port ' + port);
});


module.exports = app;
```

### Environment & setup

- OS: Ubuntu 20.04
- Database: PostgreSQL
- Node.js version 16.11.1
- 

### Prisma Version

```
prisma                  : 3.7.0
@prisma/client          : 3.7.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8746e055198f517658c08a0c426c7eec87f5a85f (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8746e055198f517658c08a0c426c7eec87f5a85f (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 8746e055198f517658c08a0c426c7eec87f5a85f (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 8746e055198f517658c08a0c426c7eec87f5a85f (at ../../../../../../usr/local/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 8746e055198f517658c08a0c426c7eec87f5a85f
Studio                  : 0.445.0

```

**Comment by ivan7707** [comment]
Also, this query works when calling it with node directly- i.e running this returns results from the DB

`node pg.js`

pg.js
```
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();


async function main() {
    const allUsers = await prisma.user.findMany({})
    console.log(allUsers)
    return allUsers
  }

  main()
```

**Comment by ivan7707** [comment]
It ultimately was a docker network issue.  Everything above was working because I was calling from my host computer to **localhost**.  

When running `prisma migrate dev` and other prisma commands I have to update the DATABASE_URL to localhost.

DATABASE_URL="postgresql://username:password@localhost:5432/db_name"

Otherwise, the URL has to be updated to use the name of the docker container so that the api container can find the postgres container when calling the URL from the server. 

DATABASE_URL="postgresql://username:password@db:5432/db_name"

**Comment by adamsimonini** [comment]
> It ultimately was a docker network issue. Everything above was working because I was calling from my host computer to **localhost**.
> 
> When running `prisma migrate dev` and other prisma commands I have to update the DATABASE_URL to localhost.
> 
> DATABASE_URL="postgresql://username:password@localhost:5432/db_name"
> 
> Otherwise, the URL has to be updated to use the name of the docker container so that the api container can find the postgres container when calling the URL from the server.
> 
> DATABASE_URL="postgresql://username:password@db:5432/db_name"
> 
> It is important to note that I am using volumes so that when I change the files on the host drive it gets updated in the container for the API (and other) docker container on the fly. That is the source of the issue.

Thank you @ivan7707 . This really helped me. In my case I had a few issues. One was that I had postgres installed locally, so locahost was actually writing to a database, but not the containerized database. Second, is the issue you specified - I was targeting localhost instead of the database service specified in docker-compose.yml.

Actually, a third problem has become apparent for me. When I "npx prisma generate", because I am using a bind mounted volume. Therefore, I don't have permissions to change the file, as it's actively in use
