### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/interpreter/query_interpreters/nested_read.rs:221:50

### ISSUE THREAD

**Issue by malikkurosaki** [prisma/prisma#11114]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v17.3.0            | 
| OS              | darwin             |
| Prisma Client   | 3.7.0              |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Logs
```
FUsers%252Fprobus%252FDocuments%252Fprojects%252Fservers%252Ffb_bot%252Ffb_bot%252Fnode_modules%252F.prisma%252Fclient%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2BSearch%2Bfor%2BQuery%2BEngine%2BLibrary%2Bin%2B%252FUsers%252Fprobus%252FDocuments%252Fprojects%252Fservers%252Ffb_bot%252Ffb_bot%252Fnode_modules%252F.prisma%252Fclient%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2BSearch%2Bfor%2BQuery%2BEngine%2BLibrary%2Bin%2B%252FUsers%252Fprobus%252FDocuments%252Fprojects%252Fservers%252Ffb_bot%252Ffb_bot%252Fnode_modules%252F.prisma%252Fclient%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2BSearch%2Bfor%2BQuery%2BEngine%2BLibrary%2Bin%2B%252FUsers%252Fprobus%252FDocuments%252Fprojects%252Fservers%252Ffb_bot%252Ffb_bot%252Fnode_modules%252F.prisma%252Fclient%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2BloadEngine%2Busing%2B%252FUsers%252Fprobus%252FDocuments%252Fprojects%252Fservers%252Ffb_bot%252Ffb_bot%252Fnode_modules%252F.prisma%252Fclient%252Flibquery_engine-darwin.dylib.node%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2BloadEngine%2Busing%2B%252FUsers%252Fprobus%252FDocuments%252Fprojects%252Fservers%252Ffb_bot%252Ffb_bot%252Fnode_modules%252F.prisma%252Fclient%252Flibquery_engine-darwin.dylib.node%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2BloadEngine%2Busing%2B%252FUsers%252Fprobus%252FDocuments%252Fprojects%252Fservers%252Ffb_bot%252Ffb_bot%252Fnode_modules%252F.prisma%252Fclient%252Flibquery_engine-darwin.dylib.node%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2BloadEngine%2Busing%2B%252FUsers%252Fprobus%252FDocuments%252Fprojects%252Fservers%252Ffb_bot%252Ffb_bot%252Fnode_modules%252F.prisma%252Fclient%252Flibquery_engine-darwin.dylib.node%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2BloadEngine%2Busing%2B%252FUsers%252Fprobus%252FDocuments%252Fprojects%252Fservers%252Ffb_bot%252Ffb_bot%252Fnode_modules%252F.prisma%252Fclient%252Flibquery_engine-darwin.dylib.node%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2BloadEngine%2Busing%2B%252FUsers%252Fprobus%252FDocuments%252Fprojects%252Fservers%252Ffb_bot%252Ffb_bot%252Fnode_modules%252F.prisma%252Fclient%252Flibquery_engine-darwin.dylib.node%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2Bsending%2Brequest%252C%2Bthis.libraryStarted%253A%2Bfalse%2B%2B%252B3s%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2Blibrary%2Bstarting%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2Bsending%2Brequest%252C%2Bthis.libraryStarted%253A%2Bfalse%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2Blibrary%2Balready%2Bstarting%252C%2Bthis.libraryStarted%253A%2Bfalse%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2Bsending%2Brequest%252C%2Bthis.libraryStarted%253A%2Bfalse%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2Blibrary%2Balready%2Bstarting%252C%2Bthis.libraryStarted%253A%2Bfalse%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2Bsending%2Brequest%252C%2Bthis.libraryStarted%253A%2Bfalse%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2Blibrary%2Balready%2Bstarting%252C%2Bthis.libraryStarted%253A%2Bfalse%2B%2B%250A%2B%2Bprisma%253Aclient%253AlibraryEngine%2Blibrary%2Bstarted%2B%2B%250A%2560%2560%2560%250A%250A%2523%2523%2BClient%2BSnippet%250A%2560%2560%2560ts%250A%252F%252F%2BPLEASE%2BFILL%2BYOUR%2BCODE%2BSNIPPET%2BHERE%250A%2560%2560%2560%250A%250A%2523%2523%2BSchema%250A%2560%2560%2560prisma%250A%252F%252F%2BPLEASE%2BADD%2BYOUR%2BSCHEMA%2BHERE%2BIF%2BPOSSIBLE%250A%2560%2560%2560%250A%250A%2523%2523%2BPrisma%2BEngine%2BQuery%250A%2560%2560%2560%250A%257B%2522X%2522%253A%257B%257D%257D%250A%2560%2560%2560%250A%26title%3DPANIC%253A%2Bcalled%2B%2560Option%253A%253Aunwrap%2528%2529%2560%2Bon%2Ba%2B%2560None%2560%2Bvalue%2Bin%2Bquery-engine%252Fcore%252Fsrc%252Finterpreter%252Fquery_interpreters%252Fnested_read.rs%253A221%253A50%26template%3Dbug_report.md%0A++prisma%3Aclient%3Afetcher+%0A++prisma%3Aclient%3Afetcher+If+you+want+the+Prisma+team+to+look+into+it%2C+please+open+the+link+above+%F0%9F%99%8F%0A++prisma%3Aclient%3Afetcher+To+increase+the+chance+of+success%2C+please+post+your+schema+and+a+snippet+of%0A++prisma%3Aclient%3Afetcher+how+you+used+Prisma+Client+in+the+issue.+%0A++prisma%3Aclient%3Afetcher+%0A++prisma%3Aclient%3Afetcher+++++at+Object.logger+%28%2FUsers%2Fprobus%2FDocuments%2Fprojects%2Fservers%2Ffb_bot%2Ffb_bot%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A36195%3A30%29%0A++prisma%3Aclient%3Afetcher+++++at+%2FUsers%2Fprobus%2FDocuments%2Fprojects%2Fservers%2Ffb_bot%2Ffb_bot%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A36164%3A34++%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=PANIC%3A+called+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value+in+query-engine%2Fcore%2Fsrc%2Finterpreter%2Fquery_interpreters%2Fnested_read.rs%3A221%3A50&template=bug_report.md
  prisma:client:fetcher 
  prisma:client:fetcher If you want the Prisma team to look into it, please open the link above 🙏
  prisma:client:fetcher To increase the chance of success, please post your schema and a snippet of
  prisma:client:fetcher how you used Prisma Client in the issue. 
  prisma:client:fetcher 
  prisma:client:fetcher     at Object.logger (/Users/probus/Documents/projects/servers/fb_bot/fb_bot/node_modules/@prisma/client/runtime/index.js:36195:30)
  prisma:client:fetcher     at /Users/probus/Documents/projects/servers/fb_bot/fb_bot/node_modules/@prisma/client/runtime/index.js:36164:34  +1s
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Content {
  id         Int         @id @default(autoincrement())
  judul      String
  harga      Int
  keterangan String @db.Text
  Gambar     Gambar[]
  Postingan  Postingan[]
}

model Gambar {
  id          Int     @id @default(autoincrement())
  destination String
  filename    String
  path        String
  contentId   Int
  Content     Content? @relation(fields: [contentId], references: [id], onDelete: Cascade, onUpdate: Cascade)

  @@index([contentId], map: "Gambar_contentId_fkey")
}

model Postingan {
  id        Int       @id @default(autoincrement())
  tanggal   DateTime  @default(now())
  contentId Int
  groupId   String
  userId    Int
  postingId String
  Content   Content?   @relation(fields: [contentId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  UserGroup UserGroup @relation(fields: [groupId], references: [groupId], onDelete: Cascade, onUpdate: Cascade)
  User      User      @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)

  @@index([contentId], map: "Postingan_contentId_fkey")
  @@index([groupId], map: "Postingan_groupId_fkey")
  @@index([userId], map: "Postingan_userId_fkey")
}

model Session {
  id   Int    @id @default(autoincrement())
  data String @db.Text
  User User   @relation(fields: [id], references: [id], onDelete: Cascade, onUpdate: Cascade)
}

model SessionBrowser {
  id   Int  @id @default(autoincrement())
  User User @relation(fields: [id], references: [id], onDelete: Cascade, onUpdate: Cascade)
}

model ShareKeBanyak {
  id        Int      @id @default(autoincrement())
  groupName String
  tanggal   DateTime
  userId    Int
  User      User     @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)

  @@index([userId], map: "ShareKeBanyak_userId_fkey")
}

model User {
  id             Int             @id @default(autoincrement())
  name           String
  email          String          @unique
  password       String
  active         Boolean         @default(true)
  desc           String?
  Postingan      Postingan[]
  Session        Session?
  SessionBrowser SessionBrowser?
  ShareKeBanyak  ShareKeBanyak[]
  UserGroup      UserGroup[]
}

model UserGroup {
  groupId   String
  name      String
  url       String
  userId    Int
  jualBeli  Boolean?
  User      User        @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  Postingan Postingan[]

  @@id([groupId, userId])
  @@index([userId], map: "UserGroup_userId_fkey")
}

```

## Prisma Engine Query
```js
Api.get('/user', expresAsyncHandler(async (req, res) => {
    let usr = await prisma.user.findMany({
        include: {
            UserGroup: true,
            ShareKeBanyak: {
                where: {
                    tanggal: {
                        lt: new Date(new Date(new Date().toISOString().split("T")[0]).setDate(new Date().getDate() + 1)),
                        gt: new Date(new Date(new Date().toISOString().split("T")[0]).setDate(new Date().getDate() - 1))
                    }
                }
            },
            
            Postingan: {
                where: {
                    tanggal: {
                        lt: new Date(new Date(new Date().toISOString().split("T")[0]).setDate(new Date().getDate() + 1)),
                        gt: new Date(new Date(new Date().toISOString().split("T")[0]).setDate(new Date().getDate() - 1))
                    }
                }
            }

        }
    });
    res.json(usr);
}));
```

**Comment by pantharshit00** [comment]
Hello,

Are you still able to reproduce this with 3.9.1?

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
