### ISSUE TITLE
P4001 The introspected database was empty

### ISSUE THREAD

**Issue by manufaktor** [prisma/prisma#11175]
### Bug description

I tried `npx prisma db pull` with a minimal SQLite database with a single table `events`. However the prisma schema is not updated. 

I've validated that the database contains at least one table:

```
sqlite3 test.db

SQLite version 3.36.0 2021-06-18 18:58:49
Enter ".help" for usage hints.


sqlite> .tables
events


sqlite> .schema events
CREATE TABLE events(
id INTEGER PRIMARY KEY,
payload TEXT
created_at TEXT
);
```

The following error is produced (with DEBUG mode on):

```
npx prisma db pull            
  prisma:loadEnv project root found at /Users/immi/Code/guarda/package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from /Users/immi/Code/guarda/.env +0ms
Environment variables loaded from .env
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: /Users/immi/Code/guarda/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +0ms
Datasource "db": SQLite database "guarda.db" at "file:guarda.db"

Introspecting based on datasource defined in prisma/schema.prisma …
  prisma:introspectionEngine:rpc starting introspection engine with binary: /Users/immi/Code/guarda/node_modules/@prisma/engines/introspection-engine-darwin-arm64 +0ms
  prisma:introspectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider = \"sqlite\"\n  url      = env(\"DATABASE_URL\")\n}\n"}]} +4ms
  prisma:introspectionEngine:rpc {
  prisma:introspectionEngine:rpc   jsonrpc: '2.0',
  prisma:introspectionEngine:rpc   error: {
  prisma:introspectionEngine:rpc     code: 4466,
  prisma:introspectionEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:introspectionEngine:rpc     data: {
  prisma:introspectionEngine:rpc       is_panic: false,
  prisma:introspectionEngine:rpc       message: 'The introspected database was empty: file:guarda.db',
  prisma:introspectionEngine:rpc       meta: [Object],
  prisma:introspectionEngine:rpc       error_code: 'P4001'
  prisma:introspectionEngine:rpc     }
  prisma:introspectionEngine:rpc   },
  prisma:introspectionEngine:rpc   id: 1
  prisma:introspectionEngine:rpc } +6ms
Error: Error: 
P4001 The introspected database was empty: 

prisma db pull could not create any models in your schema.prisma file and you will not be able to generate Prisma Client with the prisma generate command.

To fix this, you have two options:

- manually create a table in your database.
- make sure the database connection URL inside the datasource block in schema.prisma points to a database that is not empty (it must contain at least one table).

Then you can run prisma db pull again. 

    at Object.parse (/Users/immi/Code/guarda/node_modules/prisma/build/index.js:103378:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/Users/immi/Code/guarda/node_modules/prisma/build/index.js:106144:18)
```

### How to reproduce

Run `npx prisma db pull` on [this](https://github.com/prisma/prisma/files/7872815/guarda.db.zip) sqlite db. The db file sits in the same directory where I invoke npx (and === pwd)

### Expected behavior

The prisma schema is updated with the model from the `events` table.

### Prisma information

my `.env` file:
```
DATABASE_URL="file:guarda.db"
```

my `schema.prisma` file:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: Mac OS 12.0
- Database: SQLite 3.36.0
- Node.js version: v17.0.1

### Prisma Version

```
prisma                  : 3.8.1
@prisma/client          : 3.8.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
```

**Comment by janpio** [comment]
I actually get the following error message:

```
C:\Users\Jan\Documents\throwaway\11175>npx prisma db pull
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "guarda.db" at "file:./guarda.db"

Introspecting based on datasource defined in prisma\schema.prisma …

✔ Introspected 1 model and wrote it into prisma\schema.prisma in 39ms

*** WARNING ***

These fields are not supported by the Prisma Client, because Prisma currently does not support their types.
- Model "events", field: "payload", original data type: "TEXT
created_at TEXT"

Run prisma generate to generate Prisma Client.
```

But at the same time this introspects as:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model events {
  id      Int                                  @id @default(autoincrement())
  payload Unsupported("TEXT
created_at TEXT")?
}
```

Note the invalid line break after `TEXT`. 

That is happening because your original SQL is missing a `,` after `payload TEXT`. Seems SQLite happily pulls in the line break and everything after until it finds another `,` and uses that multi line string as the "type".

**Comment by manufaktor** [comment]
Yikes! Thank you for catching this.
I've tried with a new db, with a minimal `events` table, but still the same error. 

Now if I use an absolute path in my `DATABASE_URL` it works. So it must be because of the relative path, but I don't really understand why.

**Comment by manufaktor** [comment]
OK I believe this is the same as #9649 as there sits an empty db with the same name in the `./prisma` directory.

**Comment by janpio** [comment]
Ok, let's close this then. Seems I uncovered an unrelated problem, and your issues is better described with that other issue.
