### ISSUE TITLE
Error: P1001 migrate + MariaDB

### ISSUE THREAD

**Issue by jdmoliner** [prisma/prisma#11213]
### Bug description

Hi,

I get next error when I want to migrate a basic schema to a MariaDB server with `npx prisma migrate dev --name init`: 

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "test" at "xxx.xxx.xxx.xxx:3306"

Error: P1001

Can't reach database server at "xxx.xxx.xxx.xxx":"3306"

Please make sure your database server is running at "xxx.xxx.xxx.xxx":"3306".
```
Database is created, but tables are not created.

If I want to pull a database with `npx prisma db pull` everything works fine. Only migrate process fail.

I tried in several databases with MariaDB with same error. SSL is not being used.

(I have a localhost MySQL server with Mamp and process works perfectly, it seems that the problem is related only to MariaDB)

### How to reproduce

`npx prisma migrate dev --name init`

### Prisma information

schema.prisma

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id              Int         @id @default(autoincrement())
  username        String      @unique  
}
```
.env

`DATABASE_URL="mysql://user:pass@xxx.xxx.xxx.xxx/test"
`

### Environment & setup

- OS: Mac OS
- Database: MariaDb
- Node.js version: v16.13.2
- Server connection: SSL is not being used
- Server version: 10.6.5-MariaDB - MariaDB Server

### Prisma Version

```
3.8.0
```

**Comment by janpio** [comment]
Can you enable debugging paste the output here? https://pris.ly/d/debugging Important you do so without the database already existing.

**Comment by jdmoliner** [comment]
```
prisma:loadEnv project root found at /Applications/MAMP/htdocs/app-winnerodds-futbol/server/package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from /Applications/MAMP/htdocs/app-winnerodds-futbol/server/.env +0ms
Environment variables loaded from .env
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: /Applications/MAMP/htdocs/app-winnerodds-futbol/server/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node +0ms
Datasource "db": MySQL database "test" at "185.129.xxx.xxx:3306"

  prisma:getDMMF Using CLI Query Engine (Node-API) at: /Applications/MAMP/htdocs/app-winnerodds-futbol/server/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node +0ms
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: /Applications/MAMP/htdocs/app-winnerodds-futbol/server/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node +164ms
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: /Applications/MAMP/htdocs/app-winnerodds-futbol/server/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node +20ms
  prisma:migrateEngine:rpc starting migration engine with binary: /Applications/MAMP/htdocs/app-winnerodds-futbol/server/node_modules/@prisma/engines/migration-engine-darwin +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"/Applications/MAMP/htdocs/app-winnerodds-futbol/server/prisma/migrations"}} +16ms
  prisma:migrateEngine:stderr {"timestamp":"2022-01-17T21:09:35.259957Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"34df67547cf5598f5a6cd3eb45f14ee70c3fb86f"},"target":"migration_engine"} +0ms
  prisma:migrateEngine:rpc {
  prisma:migrateEngine:rpc   jsonrpc: '2.0',
  prisma:migrateEngine:rpc   error: {
  prisma:migrateEngine:rpc     code: 4466,
  prisma:migrateEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:migrateEngine:rpc     data: {
  prisma:migrateEngine:rpc       is_panic: false,
  prisma:migrateEngine:rpc       message: "Can't reach database server at `185.129.xxx.xxx`:`3306`\n" +
  prisma:migrateEngine:rpc         '\n' +
  prisma:migrateEngine:rpc         'Please make sure your database server is running at `185.129.xxx.xxx`:`3306`.',
  prisma:migrateEngine:rpc       meta: [Object],
  prisma:migrateEngine:rpc       error_code: 'P1001'
  prisma:migrateEngine:rpc     }
  prisma:migrateEngine:rpc   },
  prisma:migrateEngine:rpc   id: 1
  prisma:migrateEngine:rpc } +5s
Error: Error: P1001

Can't reach database server at `185.129.xxx.xxx`:`3306`

Please make sure your database server is running at `185.129.xxx.xxx`:`3306`.

    at Object.<anonymous> (/Applications/MAMP/htdocs/app-winnerodds-futbol/server/node_modules/prisma/build/index.js:101420:25)
    at Object.handleResponse (/Applications/MAMP/htdocs/app-winnerodds-futbol/server/node_modules/prisma/build/index.js:101291:36)
    at LineStream3.<anonymous> (/Applications/MAMP/htdocs/app-winnerodds-futbol/server/node_modules/prisma/build/index.js:101380:16)
    at LineStream3.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at LineStream3.Readable.push (_stream_readable.js:213:10)
    at LineStream3.Transform.push (_stream_transform.js:152:32)
    at LineStream3._pushBuffer (/Applications/MAMP/htdocs/app-winnerodds-futbol/server/node_modules/prisma/build/index.js:101177:17)
    at LineStream3._transform (/Applications/MAMP/htdocs/app-winnerodds-futbol/server/node_modules/prisma/build/index.js:101171:8)
```

**Comment by pantharshit00** [comment]
@jdmoliner Can you please tell me where your MariaDB instance is hosted? Also, are you able to reach it via the command line cli or any other GUI from your computer?

**Comment by jdmoliner** [comment]
@pantharshit00 MariaDB is hosted in a Cubenode VPS using CentOS 7. Yes I am able to use command line.

**Comment by jdmoliner** [comment]
@pantharshit00 @janpio can you tell me if I can try to do something via command line?

**Comment by janpio** [comment]
We unfortunately have no good idea what could be going on here.

Can you `npx prisma db pull` on a MariaDB database that already exists and has tables?
Can you also use Prisma Client with that existing database?
(So basically: Is only `migrate dev` affected?)

**Comment by jdmoliner** [comment]
@janpio exactly that. I can `npx prisma db pull` and use Prisma Client perfectly. Only `migrate dev` is affected. I can create a user for you in my database and try it yourself.

**Comment by janpio** [comment]
Happy to try - I am jan@prisma.io.

**Comment by janpio** [comment]
There were no further similar reports, so we can consider this a one off problem.

If you still have this problem, please open a new issue. Thanks!
