### ISSUE TITLE
Defining `DATABASE_URL` in `.env` without opening `"` leads to weird error message

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11247]
This is what I did in `.env` by accident:

```
DATABASE_URL=mysql://dkffbuuix8dw:pscale_...@9fmdbmgdvtpo.us-east-2.psdb.cloud/collate5?sslaccept=strict"
```
Note how the first `"` is missing.

This leads to the following error message:

```
C:\Users\Jan\Documents\throwaway\planetscaleRepro>npx prisma migrate dev --name=second
  prisma:loadEnv project root found at C:\Users\Jan\Documents\throwaway\planetscaleRepro\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\planetscaleRepro\.env +0ms
Environment variables loaded from .env
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\Documents\throwaway\planetscaleRepro\node_modules\@prisma\engines\query_engine-windows.dll.node +0ms
Datasource "db": MySQL database "collate5" at "9fmdbmgdvtpo.us-east-2.psdb.cloud:3306"

  prisma:getDMMF Using CLI Query Engine (Node-API) at: C:\Users\Jan\Documents\throwaway\planetscaleRepro\node_modules\@prisma\engines\query_engine-windows.dll.node +0ms
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\Documents\throwaway\planetscaleRepro\node_modules\@prisma\engines\query_engine-windows.dll.node +19ms
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\Documents\throwaway\planetscaleRepro\node_modules\@prisma\engines\query_engine-windows.dll.node +3ms
Error: Error: P1012: error: Error validating: This line is not a valid definition within a datasource.
  -->  schema.prisma:4
   |
 3 |                 provider = "mysql"
 4 |                 url = "mysql://dkffbuuix8dw:pscale_...@9fmdbmgdvtpo.us-east-2.psdb.cloud/collate5?sslaccept=strict""
 5 |             }
   |

    at ensureDatabaseExists (C:\Users\Jan\Documents\throwaway\planetscaleRepro\node_modules\prisma\build\index.js:101886:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.parse (C:\Users\Jan\Documents\throwaway\planetscaleRepro\node_modules\prisma\build\index.js:102407:26)
    at async main (C:\Users\Jan\Documents\throwaway\planetscaleRepro\node_modules\prisma\build\index.js:106144:18)
```

Note how the error message puts the connectrion string into a schema that does not like that, and then chokes because of the double `""` at the end (I guess).

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
