### ISSUE TITLE
Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }

### ISSUE THREAD

**Issue by taruyar** [prisma/prisma#11298]
Hi Prisma Team! My Prisma Client just crashed.

I'm running web application on Azure Functions(App Service Plan), using Azure Database For PostgreSQL.

This error has just occured once, meanwhile DB server log  says below every 5 min .

```log
2022-01-15 01:21:44 UTC-61e22076.e7274-LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
```

I assume this is somewhat related on [#1330](https://github.com/prisma/prisma/issues/1330) 
This is the report:

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.18.1           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.26.0             |
| Query Engine    | query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d|
| Database        | undefined|

## Query
```
{"X":true}
```

## Logs
```
59:41.699Z prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Fetched a connection from the pool
prisma:engine stdout  Unknown error
prisma:client prisma.$executeRaw(DELETE FROM "Token" where user_id = $1, [8407881])
prisma:client Prisma Client call:
prisma:client prisma.$executeRaw(DELETE FROM "Billing" where user_id = $1, [8407881])
prisma:client Prisma Client call:
prisma:engine stdout  Fetched a connection from the pool
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine {
  error: Error: Error occurred during query execution:
  InterpretationError("Error for binding '9'", Some(QueryGraphBuilderError(RelationViolation(RelationViolation { relation_name: "InquiryToUser", model_a_name: "Inquiry", model_b_name: "User" }))))
      at /home/site/wwwroot/node_modules/@prisma/client/runtime/index.js:28009:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
}
prisma:engine stdout  Fetched a connection from the pool
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine {
  error: Error: Error occurred during query execution:
  InterpretationError("Error for binding '9'", Some(QueryGraphBuilderError(RelationViolation(RelationViolation { relation_name: "InquiryToUser", model_a_name: "Inquiry", model_b_name: "User" }))))
      at /home/site/wwwroot/node_modules/@prisma/client/runtime/index.js:28009:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
}
prisma:engine stdout  Fetched a connection from the pool
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine stdout  Unknown error
prisma:engine {
  error: Error: Error occurred during query execution:
  InterpretationError("Error for binding '9'", Some(QueryGraphBuilderError(RelationViolation(RelationViolation { relation_name: "InquiryToUser", model_a_name: "Inquiry", model_b_name: "User" }))))
      at /home/site/wwwroot/node_modules/@prisma/client/runtime/index.js:28009:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
}
```

## Client Snippet
```ts

type DeleteUserAccountParams = {
  userId: number;
  unsubscriptionParams: {
    address1: string | null;
    address2: string | null;
    dateOfBirth: string;
    gender: string;
    reason?: string | null;
  };
};

/*
 * @param userId
 * @returns
 */
export const unsubscribe = async ({
  userId,
  unsubscriptionParams,
}: DeleteUserAccountParams): Promise<void> => {
  console.log('SERVICE: deleteUser: ');

  const params = {
    where: {
      id: userId,
    },
  };

  const { address1, address2, dateOfBirth, gender, reason } =
    unsubscriptionParams;

  await prisma.$transaction([
    prisma.userActivity.delete(params),
    prisma.$executeRaw('DELETE FROM "Token" where user_id = $1', userId),
    prisma.$executeRaw('DELETE FROM "Billing" where user_id = $1', userId),
    prisma.user.delete(params),
    prisma.unsubscription.create({
      data: {
        userId,
        address1,
        address2,
        dateOfBirth,
        gender,
        reason,
      },
    }),
  ]);
};// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Unsubscription {
  userId      Int      @id
  address1    String?  @map("address_1") @db.VarChar(255)
  address2    String?  @map("address_2") @db.VarChar(255)
  dateOfBirth String?  @map("date_of_birth") @db.VarChar(255)
  gender      String?  @db.VarChar(255)
  // ... some fields ...
  createdAt   DateTime @default(now()) @db.Timestamptz
  updatedAt   DateTime @updatedAt @db.Timestamptz
  deleted     Boolean  @default(false)
}

model User {
  id                           Int            @id
  email                        String         @unique @db.VarChar(255)
  // ... some fields ...
  userActivity                 UserActivity[]
  createdAt                    DateTime       @default(now()) @map("created_at") @db.Timestamptz
  updatedAt                    DateTime       @updatedAt @map("updated_at") @db.Timestamptz
}

model UserActivity {
  id                 Int       @id
  // ... some fields ...
  createdAt          DateTime  @default(now()) @map("created_at") @db.Timestamptz
  updatedAt          DateTime  @updatedAt @map("updated_at") @db.Timestamptz
  user               User      @relation(fields: [id], references: [id])
}
```

**Comment by matthewmueller** [comment]
Hey @taruyar are you able to reproduce this or is it intermittent?

**Comment by dpetrick** [comment]
If you still encounter that error, please reopen.
