### ISSUE TITLE
Different error handling for `library` than for `binary` on engine panics

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11362]
While reproducing https://github.com/prisma/prisma/issues/10586 with the nice reproduction repository https://github.com/dguenther/prisma-panic-demo/blob/main/script.js provided in a PR supposed to fix the problem (https://github.com/prisma/prisma-engines/pull/2589) I discovered that our error handling is different for the Library Engine than it is for the Binary Engine:

Default `engineType` or `engineType = "library"`:

```
> prisma-panic-demo@1.0.0 dev C:\Users\Jan\Documents\throwaway\prisma-panic-demo
> node ./script.js

2022-01-24T14:54:30.774Z prisma:tryLoadEnv Environment variables not found at null
2022-01-24T14:54:30.780Z prisma:tryLoadEnv Environment variables not found at undefined
2022-01-24T14:54:30.781Z prisma:tryLoadEnv No Environment variables loaded
2022-01-24T14:54:30.785Z prisma:tryLoadEnv Environment variables not found at null
2022-01-24T14:54:30.786Z prisma:tryLoadEnv Environment variables not found at undefined
2022-01-24T14:54:30.786Z prisma:tryLoadEnv No Environment variables loaded
2022-01-24T14:54:30.792Z prisma:client clientVersion: 3.8.1
2022-01-24T14:54:30.792Z prisma:client clientEngineType: library
2022-01-24T14:54:30.794Z prisma:client:libraryEngine internalSetup

Query #1 (id = 1.1111111111111111e+21):

2022-01-24T14:54:30.811Z prisma:client Prisma Client call:
2022-01-24T14:54:30.819Z prisma:client prisma.user.findUnique({
  where: {
    id: 1.1111111111111111e+21
  }
})
2022-01-24T14:54:30.819Z prisma:client Generated request:
2022-01-24T14:54:30.819Z prisma:client query {
  findUniqueUser(where: {
    id: 1.1111111111111111e+21
  }) {
    id
  }
}

2022-01-24T14:54:30.823Z prisma:client:libraryEngine Searching for Query Engine Library in C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\.prisma\client
2022-01-24T14:54:30.824Z prisma:client:libraryEngine loadEngine using C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\.prisma\client\query_engine-windows.dll.node
2022-01-24T14:54:30.849Z prisma:client:libraryEngine sending request, this.libraryStarted: false
2022-01-24T14:54:30.850Z prisma:client:libraryEngine library starting
2022-01-24T14:54:30.866Z prisma:client:libraryEngine library started
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', query-engine\core\src\query_document\parser.rs:250:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-01-24T14:54:30.874Z prisma:client:fetcher Error: called `Option::unwrap()` on a `None` value
    at prismaGraphQLToJSError (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:35966:10)
    at Object.request (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:36327:17)
PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation in
C:\Users\Jan\Documents\throwaway\prisma-panic-demo\script.js:11:21

   8 async function query1() {
   9   console.log(`\nQuery #1 (id = ${longId}):\n`)
  10 
→ 11   await prisma.user.findUnique(
  called `Option::unwrap()` on a `None` value
    at cb (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:38695:17)
    at async query1 (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\script.js:11:3) {
  clientVersion: '3.8.1'
}

Query #2 (id = 1):

2022-01-24T14:54:30.888Z prisma:client Prisma Client call:
2022-01-24T14:54:30.888Z prisma:client prisma.user.findUnique({
  where: {
    id: 1
  }
})
2022-01-24T14:54:30.888Z prisma:client Generated request:
2022-01-24T14:54:30.889Z prisma:client query {
  findUniqueUser(where: {
    id: 1
  }) {
    id
  }
}

2022-01-24T14:54:30.889Z prisma:client:libraryEngine sending request, this.libraryStarted: true
2022-01-24T14:54:30.894Z prisma:client:fetcher Error: PANIC: called `Option::unwrap()` on a `None` value in query-engine\core\src\query_document\parser.rs:250:87

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%...A87&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at Object.logger (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:36198:30)
    at C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:36167:34
PrismaClientRustPanicError: 
Invalid `prisma.user.findUnique()` invocation in
C:\Users\Jan\Documents\throwaway\prisma-panic-demo\script.js:19:21

  16 async function query2(n) {
  17   console.log(`\nQuery #2 (id = ${shortId}):\n`)
  18 
→ 19   await prisma.user.findUnique(
  PANIC: called `Option::unwrap()` on a `None` value in query-engine\core\src\query_document\parser.rs:250:87

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+...3A87&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at cb (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:38699:17)
    at async query2 (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\script.js:19:3) {
  clientVersion: '3.8.1'
}
2022-01-24T14:54:30.909Z prisma:client:libraryEngine library stopping
2022-01-24T14:54:30.910Z prisma:client:libraryEngine library stopped
2022-01-24T14:54:30.910Z prisma:client:libraryEngine hookProcess received: beforeExit
2022-01-24T14:54:30.910Z prisma:client:libraryEngine runBeforeExit
2022-01-24T14:54:30.910Z prisma:client:libraryEngine hookProcess received: exit

```

Modified `engineType = "binary"`:
```

> prisma-panic-demo@1.0.0 dev C:\Users\Jan\Documents\throwaway\prisma-panic-demo
> node ./script.js

2022-01-24T14:54:55.109Z prisma:tryLoadEnv Environment variables not found at null
2022-01-24T14:54:55.111Z prisma:tryLoadEnv Environment variables not found at undefined
2022-01-24T14:54:55.112Z prisma:tryLoadEnv No Environment variables loaded
2022-01-24T14:54:55.113Z prisma:tryLoadEnv Environment variables not found at null
2022-01-24T14:54:55.113Z prisma:tryLoadEnv Environment variables not found at undefined
2022-01-24T14:54:55.113Z prisma:tryLoadEnv No Environment variables loaded
2022-01-24T14:54:55.115Z prisma:client clientVersion: 3.8.1
2022-01-24T14:54:55.115Z prisma:client clientEngineType: binary

Query #1 (id = 1.1111111111111111e+21):

2022-01-24T14:54:55.124Z prisma:client Prisma Client call:
2022-01-24T14:54:55.125Z prisma:client prisma.user.findUnique({
  where: {
    id: 1.1111111111111111e+21
  }
})
2022-01-24T14:54:55.125Z prisma:client Generated request:
2022-01-24T14:54:55.125Z prisma:client query {
  findUniqueUser(where: {
    id: 1.1111111111111111e+21
  }) {
    id
  }
}

2022-01-24T14:54:55.126Z prisma:engine Search for Query Engine in C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\.prisma\client
2022-01-24T14:54:55.129Z prisma:engine {
  cwd: 'C:\\Users\\Jan\\Documents\\throwaway\\prisma-panic-demo\\prisma'
}
2022-01-24T14:54:55.129Z prisma:engine Search for Query Engine in C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\.prisma\client
2022-01-24T14:54:55.153Z prisma:engine { flags: [ '--enable-raw-queries', '--port', '55719' ] }
2022-01-24T14:54:55.649Z prisma:engine stdout Starting a sqlite pool with 9 connections.
2022-01-24T14:54:55.656Z prisma:engine stdout Started http server on http://127.0.0.1:55719
2022-01-24T14:54:55.658Z prisma:engine Search for Query Engine in C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\.prisma\client
2022-01-24T14:54:55.677Z prisma:engine stdout PANIC in query-engine\core\src\query_document\parser.rs:250:87
called `Option::unwrap()` on a `None` value
2022-01-24T14:54:55.682Z prisma:engine {
  error: Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
2022-01-24T14:54:55.691Z prisma:engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:55719
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 55719
  }
}
2022-01-24T14:54:55.694Z prisma:engine There is a child that still runs and we want to start again
2022-01-24T14:54:55.694Z prisma:engine {
  cwd: 'C:\\Users\\Jan\\Documents\\throwaway\\prisma-panic-demo\\prisma'
}
2022-01-24T14:54:55.694Z prisma:engine Search for Query Engine in C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\.prisma\client
2022-01-24T14:54:55.699Z prisma:engine { flags: [ '--enable-raw-queries', '--port', '55722' ] }
2022-01-24T14:54:56.219Z prisma:engine Client Version: 3.8.1
2022-01-24T14:54:56.219Z prisma:engine Engine Version: query-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
2022-01-24T14:54:56.219Z prisma:engine Active provider: sqlite
2022-01-24T14:54:56.260Z prisma:engine stdout Starting a sqlite pool with 9 connections.
2022-01-24T14:54:56.269Z prisma:engine stdout Started http server on http://127.0.0.1:55722
2022-01-24T14:54:56.269Z prisma:engine Search for Query Engine in C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\.prisma\client
2022-01-24T14:54:56.289Z prisma:engine stdout PANIC in query-engine\core\src\query_document\parser.rs:250:87
called `Option::unwrap()` on a `None` value
2022-01-24T14:54:56.291Z prisma:engine {
  error: Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
2022-01-24T14:54:56.293Z prisma:client:fetcher Error: PANIC in query-engine\core\src\query_document\parser.rs:250:87
called `Option::unwrap()` on a `None` value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21...lue&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at Object.throwAsyncErrorIfExists (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:37565:19)
    at Object.handleRequestError (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:36862:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.request (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:37486:7)
PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation in
C:\Users\Jan\Documents\throwaway\prisma-panic-demo\script.js:11:21

   8 async function query1() {
   9   console.log(`\nQuery #1 (id = ${longId}):\n`)
  10 
→ 11   await prisma.user.findUnique(
  PANIC in query-engine\core\src\query_document\parser.rs:250:87
called `Option::unwrap()` on a `None` value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+...ue&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at cb (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:38695:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async query1 (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\script.js:11:3) {
  clientVersion: '3.8.1'
}

Query #2 (id = 1):

2022-01-24T14:54:56.299Z prisma:client Prisma Client call:
2022-01-24T14:54:56.299Z prisma:client prisma.user.findUnique({
  where: {
    id: 1
  }
})
2022-01-24T14:54:56.299Z prisma:client Generated request:
2022-01-24T14:54:56.299Z prisma:client query {
  findUniqueUser(where: {
    id: 1
  }) {
    id
  }
}

2022-01-24T14:54:56.301Z prisma:engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:55722
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 55722
  }
}
2022-01-24T14:54:56.307Z prisma:client:fetcher Error: PANIC in query-engine\core\src\query_document\parser.rs:250:87
called `Option::unwrap()` on a `None` value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21...lue&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at Object.throwAsyncErrorIfExists (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:37565:19)
    at Object.handleRequestError (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:36862:12)
    at Object.request (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:37486:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation in
C:\Users\Jan\Documents\throwaway\prisma-panic-demo\script.js:19:21

  16 async function query2(n) {
  17   console.log(`\nQuery #2 (id = ${shortId}):\n`)
  18 
→ 19   await prisma.user.findUnique(
  PANIC in query-engine\core\src\query_document\parser.rs:250:87
called `Option::unwrap()` on a `None` value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+...ue&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at cb (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\node_modules\@prisma\client\runtime\index.js:38695:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async query2 (C:\Users\Jan\Documents\throwaway\prisma-panic-demo\script.js:19:3) {
  clientVersion: '3.8.1'
}
2022-01-24T14:54:56.310Z prisma:engine Stopping Prisma engine4
2022-01-24T14:54:56.310Z prisma:engine Done waiting for start promise
2022-01-24T14:54:56.808Z prisma:engine Client Version: 3.8.1
2022-01-24T14:54:56.808Z prisma:engine Engine Version: query-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
2022-01-24T14:54:56.808Z prisma:engine Active provider: sqlite

```

See how besides the obvious and expected differences, the `binary` output already shows the "This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic." error message including the GH issue creation link on Query #1, while `library` only shows it on Query #2 (where `binary` additionally also shows it).

**Comment by janpio** [comment]
Relevant code snippets:
https://github.com/prisma/prisma/blob/5bc3c0543202fcc29d59dcc6c9ee2b89780a58fc/packages/engine-core/src/library/LibraryEngine.ts#L252-L260
https://github.com/prisma/prisma/blob/ea78e2cde1f14f3ce2b2fa96b10116c278fcc764/packages/engine-core/src/binary/BinaryEngine.ts#L685-L706

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
