### ISSUE TITLE
generate import problem

### ISSUE THREAD

**Issue by AMIT9027** [prisma/prisma#11394]
### Bug description

```
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (G:\Final\Final\node_modules\.prisma\client\index.js:3:11)
    at Object.<anonymous> (G:\Final\Final\index.js:14:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by matthewmueller** [comment]
Do you mind providing some more information @AMIT9027?

**Comment by nesimtunc** [comment]
Hi, 

I'm having same issue when I run it inside a docker container. It works fine on host machine. Whole project can be seen here: https://github.com/evrimagaci/periodum-api/pull/13

**Comment by nesimtunc** [comment]
Okay, I have managed to run this work by execute the `npx prisman generate` inside the docker container (will add to Dockerfile) however this time it says it can't reach the `db` container which is actually not a case.. Any idea?

```bash
periodum_api  | Invalid `prisma.elements.findMany()` invocation in
periodum_api  | /usr/app/src/app.ts:14:41
periodum_api  | 
periodum_api  |   11 });
periodum_api  |   12 
periodum_api  |   13 app.get('/elements', async (_, res: Response) => {
periodum_api  | → 14    const elements = await prisma.elements.findMany()
periodum_api  |   Can't reach database server at `db`:`3306`
periodum_api  | 
periodum_api  | Please make sure your database server is running at `db`:`3306`.
periodum_api  |     at cb (/usr/app/node_modules/@prisma/client/runtime/index.js:38709:17)
periodum_api  |     at PrismaClient._request (/usr/app/node_modules/@prisma/client/runtime/index.js:40859:18)
```
But actually that's not the case. When I connect to the container I can ping to the db. 

```bash
docker exec -it 222b41888aaa1d33c5d5c145f350bd53694ea4fec96238b8a769f550c53fb889 /bin/sh
$ ping db
PING db (172.19.0.2) 56(84) bytes of data.
64 bytes from periodum_db.periodum-api_default (172.19.0.2): icmp_seq=1 ttl=64 time=0.171 ms
64 bytes from periodum_db.periodum-api_default (172.19.0.2): icmp_seq=2 ttl=64 time=0.261 ms
64 bytes from periodum_db.periodum-api_default (172.19.0.2): icmp_seq=3 ttl=64 time=0.221 ms
```

**Comment by millsp** [comment]
Hey @AMIT9027 I'll be closing this issue since this does not look like a bug. Please make sure you always run `prisma generate` and feel free to ping us for any help. Thanks!
