### ISSUE TITLE
Prisma Adapter Not Working With Next Auth + Planetscale (MySQL)

### ISSUE THREAD

**Issue by terose73** [prisma/prisma#11487]
### Bug description

Error related to the Accounts field in the Prisma schema when trying to use Twitter OAuth2. Field is defined in a @@unique relationship, although referential integrity is enabled. Using a Planetscale MySQL Connection String.

```
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error
Invalid `p.account.findUnique()` invocation in
C:\Users\teros\Desktop\transcript-geek\node_modules\@next-auth\prisma-adapter\dist\index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
  Failed to validate the query: `Field does not exist on enclosing type.` at `Query.findUniqueAccount` Error:
Invalid `p.account.findUnique()` invocation in
C:\Users\teros\Desktop\transcript-geek\node_modules\@next-auth\prisma-adapter\dist\index.js:11:45

   8 getUserByEmail: (email) => p.user.findUnique({ where: { email } }),
   9 async getUserByAccount(provider_providerAccountId) {
  10     var _a;
→ 11     const account = await p.account.findUnique(
  Failed to validate the query: `Field does not exist on enclosing type.` at `Query.findUniqueAccount`
    at cb (C:\Users\teros\Desktop\transcript-geek\node_modules\@prisma\client\runtime\index.js:38691:17)
    at async getUserByAccount (C:\Users\teros\Desktop\transcript-geek\node_modules\@next-auth\prisma-adapter\dist\index.js:11:29) {
  name: 'GetUserByAccountError',
  code: 'P2009'
}
```

### How to reproduce

Using default v4 Prisma Models [next-auth docs](https://next-auth.js.org/adapters/prisma) with additional fields in the User model.

```
import { baseUrl } from "./../../../config/seo"
import TwitterProvider from "next-auth/providers/twitter"
import { PrismaAdapter } from "@next-auth/prisma-adapter"
import NextAuth, { User, UserPreview } from "next-auth"

export default NextAuth({
  secret: process.env.JWT_SIGNING_KEY as string,
  adapter: PrismaAdapter(prisma),
  theme: {
    colorScheme: "auto",
    brandColor: "",
    logo: `${baseUrl}/static/logo.png`,
  },
  callbacks: {
    async session({
      session,
      user: {
        username,
        name,
        twitter_image,
        role,
        email,
        twitter_verified,
        id,
      },
    }) {
      session.user = {
        id,
        name,
        username,
        twitter_image,
        role,
        email,
        twitter_verified,
      } as UserPreview

      return session
    },
  },
  providers: [
    TwitterProvider({
      clientId: process.env.TWITTER_CONSUMER_API_KEY as string,
      clientSecret: process.env.TWITTER_CONSUMER_API_SECRET as string,
      // docs: https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-me
      userinfo: {
        params: {
          "user.fields":
            "created_at,description,id,profile_image_url,public_metrics,username,verified",
        },
        url: "https://api.twitter.com/2/users/me",
      },
      version: "2.0",

      //assertion since we can't make the distinction between User and UserPreview (only one User in next-auth)
      profile({
        data: {
          id,
          name,
          username,
          description,
          created_at,
          public_metrics,
          verified,
          profile_image_url,
        },
      }) {
        return {
          id,
          name,
          username,
          description,
          twitter_created_at: created_at,
          twitter_public_metrics: public_metrics,
          twitter_verified: verified,
          twitter_image: profile_image_url,
        } as User
      },
    }),
  ],
})
```

```
import NextAuth from "next-auth"
import type { User as PrismaUser, UserCreateInput } from "@prisma/client"

declare module "next-auth" {
  type UserPreview = Pick<
    PrismaUser,
    | "name"
    | "username"
    | "twitter_image"
    | "role"
    | "email"
    | "twitter_verified"
    | "id"
  >

  interface Session {
    user: UserPreview
  }

  type User = PrismaUser
}
```

```
model User {
  id                     String    @id
  name                   String
  username               String    @unique
  description            String?   @db.Text
  twitter_created_at     DateTime
  twitter_public_metrics Json?
  twitter_verified       Boolean?
  twitter_image          String
  role                   Role      @default(FREE)
  email                  String?   @unique
  email_verified         Boolean   @default(false)
  created_at             DateTime  @default(now())
  accounts               Account[]
  sessions               Session[]
  Comment                Comment[]
  Post                   Post[]
}
```

```
import { PrismaClient } from '@prisma/client'

declare global {
  var prisma: PrismaClient | undefined
}

export const prisma =
  global.prisma ||
  new PrismaClient({
    log:
      process.env.NODE_ENV === 'development'
        ? ['query', 'error', 'warn']
        : ['error'],
  })

if (process.env.NODE_ENV !== 'production') global.prisma = prisma
```

### Prisma information

Referential Integrity is enabled, Database URL is MySQL connection string from planetscale

### Environment & setup

- OS: Windows
- Database: MySQL
- Node.js version: v16.13.0

### Prisma Version

```
prisma                  : 3.8.1
@prisma/client          : 3.8.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules\@prisma\engines\prisma-fmt-windows.exe)        
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
Preview Features        : referentialIntegrity
```

**Comment by janpio** [comment]
`referentialIntegrity=prisma` currently is buggy for referential actions. Can you try setting them all to `NoAction` manually?

**Comment by terose73** [comment]
I added NoAction to the User relation + @@index([userId]) and nothing changed

**Comment by janpio** [comment]
Ok, please share a full reproduction that we can as quickly as possible deploy and connect to a PlanetScale database. Optimally a GH repo we just need to check out. Thanks.

**Comment by terose73** [comment]
Deleting / re-cloning the Github repo solved the issue. I was surprised this worked given that I had this worked since I tried `rm -rf ./node_modules, yarn cache clean, prisma generate, prisma db push, etc.`

**Comment by janpio** [comment]
That is indeed weird, but happy it works now. Let us know if you encounter this again in the future.

**Comment by elmariachi111** [comment]
I can confirm that this issue still exists. I got some entities relating to my User object:

after completely dropping everything the email based signing process works, first. It broke after I added related entities. It works perfectly when I'm running the same stuff on a plain mysql database (switching off the experimental referential integrity flags)...

The error (`symbol `to-one`.`User`.id not found`) is thrown during the login phase when [using nextauth's email signin feature](https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-prisma/src/index.ts#L16), that's the trace:

```
2022-04-01T10:15:48.783Z	3f25e4da-b8fa-49ba-82cb-32a63320a01f	ERROR	[next-auth][error][adapter_error_updateUser]
 https://next-auth.js.org/errors#adapter_error_updateuser 
 
 Invalid `prisma.user.update()` invocation:  
 Error occurred during query execution:ConnectorError(ConnectorError {
  user_facing_error: None, 
  kind: QueryError(Server(ServerError { 
  code: 1105, message: "symbol `to-one`.`User`.id not found", state: "HY000" 
  })) }) 
  
  {  message: '\n' +    'Invalid `prisma.user.update()` invocation:\n' +    '\n' +    '\n' + 
     '  Error occurred during query execution:\n' +
         'ConnectorError(ConnectorError { user_facing_error: None, kind:
          QueryError(Server(ServerError { code: 1105, message: "symbol `to-one`.`User`.id not found",
           state: "HY000" })) })', 
           
  stack: 'Error: \n' +    'Invalid `prisma.user.update()` invocation:\n' +    '\n' +    '\n' +
      '  Error occurred during query execution:\n' +   
       'ConnectorError(ConnectorError { user_facing_error: None,
        kind: QueryError(Server(ServerError { 
        code: 1105, message: "symbol `to-one`.`User`.id not found", state: "HY000" })) })\n' + 
        
           '    at Object.request (/var/task/node_modules/@prisma/client/runtime/index.js:39822:15)\n' + 
          '    at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:40649:18)',
      name: 'Error'}
      
2022-04-01T10:15:48.784Z	3f25e4da-b8fa-49ba-82cb-32a63320a01f	ERROR	[next-auth][error][CALLBACK_EMAIL_ERROR] 
https://next-auth.js.org/errors#callback_email_error Invalid `prisma.user.update()` 
invocation:  Error occurred during query execution:ConnectorError(ConnectorError {
 user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, 
 message: "symbol `to-one`.`User`.id not found", state: "HY000" 
 })) }) 
 
 Error: Invalid `prisma.user.update()` invocation:  
 Error occurred during query execution:ConnectorError(ConnectorError { 
 user_facing_error: None, kind: QueryError(Server(ServerError { 
 code: 1105, message: "symbol `to-one`.`User`.id not found", state: "HY000" 
 })) })    
 at Object.request (/var/task/node_modules/@prisma/client/runtime/index.js:39822:15) 
    at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:40649:18) {
      name: 'UpdateUserError',  code: undefined}
```

prisma schema:
```
generator client {
    provider = "prisma-client-js"
    previewFeatures = ["referentialIntegrity"]
}

datasource db {
    provider = "mysql"
    url      = env("DATABASE_URL")
    referentialIntegrity = "prisma"
}
model User {
    id            String    @id @default(cuid())
    name          String?
    email         String?   @unique
    emailVerified DateTime?
    image         String?
    accounts      Account[]
    sessions      Session[]
    links         Link[]
    payments      Payment[]
    sellerAccount SellerAccount?
}
model SellerAccount {
    id                  String  @id @default(cuid())
    userId              String 
    merchantIdInPayPal  String
    permissionsGranted  Boolean
    accountStatus       String?
    consentStatus       Boolean
    productIntentId     String
    isEmailConfirmed    Boolean
    riskStatus          String?
    user                User @relation(fields: [userId], references: [id], onDelete: Cascade)
}
model Link {
    hash       String    @id
    origin_uri String
    price      Decimal
    creatorId  String
    creator    User      @relation(fields: [creatorId], references: [id])
    payments   Payment[]
    metadata   Metadata?

    @@index([hash, origin_uri])
}

```

the generated schema on pscale:
```
CREATE TABLE `User` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emailVerified` datetime(3) DEFAULT NULL,
  `image` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `User_email_key` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `Link` (
  `hash` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `origin_uri` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `price` decimal(65,30) NOT NULL,
  `creatorId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`hash`),
  KEY `Link_hash_origin_uri_idx` (`hash`,`origin_uri`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `SellerAccount` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `userId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `merchantIdInPayPal` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `permissionsGranted` tinyint(1) NOT NULL,
  `accountStatus` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `consentStatus` tinyint(1) NOT NULL,
  `productIntentId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `isEmailConfirmed` tinyint(1) NOT NULL,
  `riskStatus` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `SellerAccount_userId_key` (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by janpio** [comment]
The `symbol ... not found` error is known (but different what was describe in this issue) and is tracked here: https://github.com/prisma/prisma/issues/10758
