### ISSUE TITLE
DBML Generator "Path" Type Error

### ISSUE THREAD

**Issue by johnmasonwilliams** [prisma/prisma#11564]
### Bug description

I added the dbml generator to my prisma schema to view it on dbdiagram.io. Then I ran "npx prisma generate" and received the following type error.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
    at mkdir (node:internal/fs/promises:608:10)
    at Object.generate [as onGenerate] (C:\Users\mwill\Documents\Development\Bloxsmith\next-js\node_modules\prisma-dbml-generator\dist\cli\dbml-generator.js:14:15)
    at LineStream.<anonymous> (C:\Users\mwill\Documents\Development\Bloxsmith\next-js\node_modules\@prisma\generator-helper\dist\generatorHandler.js:33:38)
    at LineStream.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at LineStream.Readable.push (node:internal/streams/readable:228:10)
    at LineStream._pushBuffer (C:\Users\mwill\Documents\Development\Bloxsmith\next-js\node_modules\@prisma\generator-helper\dist\byline.js:78:17)
    at LineStream._transform (C:\Users\mwill\Documents\Development\Bloxsmith\next-js\node_modules\@prisma\generator-helper\dist\byline.js:72:8)
    at LineStream.Transform._write (node:internal/streams/transform:184:23)
```

I then removed the dbml generator from my prisma scheme file and did not receive the type error.

### Expected behavior

When you run `npx prisma generate` there should be no type errors.

### Prisma information

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

generator dbml {
  provider = "prisma-dbml-generator"
}

datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

### Environment & setup

- Node.js version: v16.13.2

### Prisma Version

```
3.9.0
```

**Comment by johnmasonwilliams** [comment]
Update:
I was on prisma-dbml-generator version 0.4.0 and the type error above was produced.

I updated prisma-dbml-generator to version 0.8.3 which solved the type error, however introduced another issue. Using prisma 3.9.0 and prisma-dbml-generation 0.8.3 introduces high level vulnerabilities which are listed below.

```
node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix --force`
Will install prisma-dbml-generator@0.4.0, which is a breaking change
node_modules/node-fetch
  @prisma/sdk  >=0.0.177
  Depends on vulnerable versions of checkpoint-client
  Depends on vulnerable versions of node-fetch
  node_modules/@prisma/sdk
    prisma-dbml-generator  >=0.5.0-dev.0
    Depends on vulnerable versions of @prisma/sdk
    node_modules/prisma-dbml-generator
  checkpoint-client  *
  Depends on vulnerable versions of node-fetch
  node_modules/checkpoint-client

4 high severity vulnerabilities
```

**Comment by Jolg42** [comment]
@johnmasonwilliams You might want to try the dev version `0.9.0-dev.0`, just found it when I looked over the release on npm.

About the security warning, I'm unsure if this is something that applies here but we'll check and see if we have the latest version of node-fetch in `checkpoint-client`

**Comment by johnmasonwilliams** [comment]
I will give the dev version a try and let you know.  Thanks for the quick response.

**Comment by pantharshit00** [comment]
Since the original error reported is solved, I am going to close this. Please open a new issue if you are having any further problems.
