### ISSUE TITLE
MongoDb Connector QueryExceededMemoryLimitNoDiskUseAllowed

### ISSUE THREAD

**Issue by x052** [prisma/prisma#11707]
## Environment

```
prisma                  : 3.9.1
@prisma/client          : Not found
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
Preview Features        : mongoDb
```

### Mongo Environment

- Using Mongo Serverless instance
- The database contains 2GB worth of GridFs files
- The database also contains objects which go quite deep (5 layers)

## The Issue

Following the getting started guide for mongodb, I ran the command `npx prisma db pull ` which produces the error 
```
Error: Error in connector: Error querying the database: Command failed (QueryExceededMemoryLimitNoDiskUseAllowed): PlanExecutor error during aggregation :: caused by :: Sort exceeded memory limit of 33554432 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.)
```

The full debug logs for this error are 
```
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
  prisma:loadEnv project root found at /package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from /.env +0ms
Environment variables loaded from .env
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: /node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node +0ms
Datasource "db"

Introspecting based on datasource defined in prisma/schema.prisma …
  prisma:introspectionEngine:rpc starting introspection engine with binary: /node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x +0ms
  prisma:introspectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ngenerator client {\n  provider        = \"prisma-client-js\"\n  previewFeatures = [\"mongoDb\"]\n}\n\ndatasource db {\n  provider = \"mongodb\"\n  url      = env(\"DATABASE_URL\")\n}\n"}]} +9ms
  prisma:introspectionEngine:rpc {
  prisma:introspectionEngine:rpc   jsonrpc: '2.0',
  prisma:introspectionEngine:rpc   error: {
  prisma:introspectionEngine:rpc     code: 4466,
  prisma:introspectionEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:introspectionEngine:rpc     data: {
  prisma:introspectionEngine:rpc       is_panic: false,
  prisma:introspectionEngine:rpc       message: 'Error in connector: Error querying the database: Command failed (QueryExceededMemoryLimitNoDiskUseAllowed): PlanExecutor error during aggregation :: caused by :: Sort exceeded memory limit of 33554432 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.)',
  prisma:introspectionEngine:rpc       backtrace: null
  prisma:introspectionEngine:rpc     }
  prisma:introspectionEngine:rpc   },
  prisma:introspectionEngine:rpc   id: 1
  prisma:introspectionEngine:rpc } +2s

Error: Error: Error in connector: Error querying the database: Command failed (QueryExceededMemoryLimitNoDiskUseAllowed): PlanExecutor error during aggregation :: caused by :: Sort exceeded memory limit of 33554432 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.)

    at Object.<anonymous> (/node_modules/prisma/build/index.js:46523:29)
    at Object.handleResponse (/node_modules/prisma/build/index.js:46401:38)
    at LineStream4.<anonymous> (/node_modules/prisma/build/index.js:46479:20)
    at LineStream4.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at LineStream4.Readable.push (node:internal/streams/readable:228:10)
    at LineStream4._pushBuffer (/node_modules/prisma/build/index.js:46244:21)
    at LineStream4._transform (/node_modules/prisma/build/index.js:46238:12)
    at LineStream4.Transform._write (node:internal/streams/transform:184:23)
```

**Comment by Jolg42** [comment]
What's the average size of one document? Since it's GridFS files, they are probably quite large? 

Because Introspection relies on sampling the documents it might be related to the logic we apply where we take a sample of [1000 documents by default.](https://github.com/prisma/prisma-engines/blob/main/introspection-engine/connectors/mongodb-introspection-connector/src/sampler/statistics.rs#L23)

1000 x a big document might be the issue here.

**Comment by SevInf** [comment]
To reproduce, we should try to create a collection on Atlas with at least 1000 of large (hundreds of MB) documents and try to introspect the DB.
