### ISSUE TITLE
Odd behaviour of Prisma in AWS Lambda

### ISSUE THREAD

**Issue by halvardssm** [prisma/prisma#11798]
### Bug description

I have a rather large lambda codebase running on AWS Lambda, and I am experiencing some odd behaviours to which I was hoping to get some solutions. Please let me know if I can provide more information.

I am bundling the lambdas using esbuild, and deploying them using cdk, so all of the lambdas should all have the same runtime (node-14). The only difference between the lambdas is the amount of memory given (some 256 and some 128).

However when calling the lambda, I get varied response depending on the function. Some functions wants to use `libquery_engine-rhel-openssl-1.1.x.so.node`, while others want to use `libquery_engine-rhel-openssl-1.0.x.so.node`.

I also sometimes get this error for those using `libquery_engine-rhel-openssl-1.1.x.so.node`

```
PrismaClientInitializationError: 
  Invalid `t._entries.delete()` invocation in
  /var/task/app.js:350:23096
  
    347 It should have this form: { url: "CONNECTION_STRING" }`);if(r&&typeof r=="object")for(let[s,i]of Object.entries(r)){if(s!=="url")throw new PrismaClientConstructorValidationError(`Invalid value ${JSON.stringify(e)} for datasource "${t}" provided to PrismaClient constructor.
    348 It should have this form: { url: "CONNECTION_STRING" }`);if(typeof i!="string")throw new PrismaClientConstructorValidationError(`Invalid value ${JSON.stringify(i)} for datasource "${t}" provided to PrismaClient constructor.
    349 It should have this form: { url: "CONNECTION_STRING" }`)}}}},errorFormat:e=>{if(!!e){if(typeof e!="string")throw new PrismaClientConstructorValidationError(`Invalid value ${JSON.stringify(e)} for "errorFormat" provided to PrismaClient constructor.`);if(!errorFormats.includes(e)){let n=getDidYouMean(e,errorFormats);throw new PrismaClientConstructorValidationError(`Invalid errorFormat ${e} provided to PrismaClient constructor.${n}`)}}},log:e=>{if(!e)return;if(!Array.isArray(e))throw new PrismaClientConstructorValidationError(`Invalid value ${JSON.stringify(e)} for "log" provided to PrismaClient constructor.`);function n(t){if(typeof t=="string"&&!logLevels.includes(t)){let r=getDidYouMean(t,logLevels);throw new PrismaClientConstructorValidationError(`Invalid log level "${t}" provided to PrismaClient constructor.${r}`)}}__name(n,"validateLogLevel"),__name2(n,"validateLogLevel");for(let t of e){n(t);let r={level:n,emit:s=>{let i=["stdout","event"];if(!i.includes(s)){let a=getDidYouMean(s,i);throw new PrismaClientConstructorValidationError(`Invalid value ${JSON.stringify(s)} for "emit" in logLevel provided to PrismaClient constructor.${a}`)}}};if(t&&typeof t=="object")for(let[s,i]of Object.entries(t))if(r[s])r[s](i);else throw new PrismaClientConstructorValidationError(`Invalid property ${s} for "log" provided to PrismaClient constructor`)}},__internal:e=>{if(!e)return;let n=["debug","hooks","engine","measurePerformance"];if(typeof e!="object")throw new PrismaClientConstructorValidationError(`Invalid value ${JSON.stringify(e)} for "__internal" to PrismaClient constructor`);for(let[t]of Object.entries(e))if(!n.includes(t)){let r=getDidYouMean(t,n);throw new PrismaClientConstructorValidationError(`Invalid property ${JSON.stringify(t)} for "__internal" provided to PrismaClient constructor.${r}`)}},rejectOnNotFound:e=>{if(!!e){if(isError(e)||typeof e=="boolean"||typeof e=="object"||typeof e=="function")return e;throw new PrismaClientConstructorValidationError(`Invalid rejectOnNotFound expected a boolean/Error/{[modelName: Error | boolean]} but received ${JSON.stringify(e)}`)}}};function validatePrismaClientOptions(e,n){for(let[t,r]of Object.entries(e)){if(!knownProperties.includes(t)){let s=getDidYouMean(t,knownProperties);throw new PrismaClientConstructorValidationError(`Unknown property ${t} provided to PrismaClient constructor.${s}`)}validators[t](r,n)}}__name(validatePrismaClientOptions,"validatePrismaClientOptions");__name2(validatePrismaClientOptions,"validatePrismaClientOptions");function getDidYouMean(e,n){if(n.length===0||typeof e!="string")return"";let t=getAlternative(e,n);return t?` Did you mean "${t}"?`:""}__name(getDidYouMean,"getDidYouMean");__name2(getDidYouMean,"getDidYouMean");function getAlternative(e,n){if(n.length===0)return null;let t=n.map(s=>({value:s,distance:(0,import_js_levenshtein2.default)(e,s)}));t.sort((s,i)=>s.distance<i.distance?-1:1);let r=t[0];return r.distance<3?r.value:null}__name(getAlternative,"getAlternative");__name2(getAlternative,"getAlternative");var import_debug8=__toModule22(require_dist7()),import_strip_ansi5=__toModule22(require_strip_ansi()),debug8=(0,import_debug8.default)("prisma:client:request_handler"),RequestHandler=__name(class{constructor(e,n){this.client=e,this.hooks=n,this.dataloader=new DataLoader({batchLoader:t=>{var r;let s=t.map(a=>String(a.document)),i={transactionId:t[0].transactionId,traceparent:(r=t[0].headers)==null?void 0:r.traceparent};return this.client._engine.requestBatch(s,i)},singleLoader:t=>{let r=String(t.document);return this.client._engine.request(r,d({transactionId:t.transactionId},t.headers))},batchBy:t=>t.transactionId?`transaction-${t.transactionId}`:batchFindUniqueBy(t)})}async request({document:e,dataPath:n=[],rootField:t,typeName:r,isList:s,callsite:i,rejectOnNotFound:a,clientMethod:u,runInTransaction:l,showColors:o,engineHook:c,args:m,headers:f,transactionId:g,unpacker:w}){if(this.hooks&&this.hooks.beforeRequest){let _=String(e);this.hooks.beforeRequest({query:_,path:n,rootField:t,typeName:r,document:e,isList:s,clientMethod:u,args:m})}try{let _,S;if(c){let E=await c({document:e,runInTransaction:l},I=>this.dataloader.request(I));_=E.data,S=E.elapsed}else{let E=await this.dataloader.request({document:e,runInTransaction:l,headers:f,transactionId:g});_=E==null?void 0:E.data,S=E==null?void 0:E.elapsed}let A=this.unpack(e,_,n,t,w);return throwIfNotFound(A,u,r,a),process.env.PRISMA_CLIENT_GET_TIME?{data:A,elapsed:S}:A}catch(_){debug8(_);let S=_.message;if(i){let{stack:A}=printStack({callsite:i,originalMethod:u,onUs:_.isPanic,showColors:o});S=`${A}
  → 350   $
    Unable to load Node-API Library from /var/task/libquery_engine-rhel-openssl-1.1.x.so.node, Library may be corrupt
      at cb (/var/task/app.js:346:361)
      at async n._request (/var/task/app.js:364:2383)
      at async Tnn (/var/task/app.js:619:76714)
      at async Vkn (/var/task/app.js:619:77816)
      at async before (/var/task/app.js:619:78082)
      at async _qe (/var/task/app.js:1:2679)
      at async nMr (/var/task/app.js:1:2071) {
    clientVersion: '3.9.2',
    errorCode: undefined
  }
```

### How to reproduce

Uncertain how to provide reproducible steps, as I can not disclose the entire codebase.

### Expected behavior

Lambdas should use the same libquery engine and it should work.

### Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.1.x", "rhel-openssl-1.0.x"]
  output        = "client"
}

datasource db {
  provider = "postgresql"
  url      = env("DB_CONNECTION")
}

model User {
  id              String   @id @default(cuid())
  email           String?  @unique
}
```

### Environment & setup

- OS: AWS Lambda Node 14
- Database: PostgreSQL
- Node.js version: 14
- Using Yarn V3 PNP

### Prisma Version

```
prisma                  : 3.9.2
@prisma/client          : 3.9.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at .yarn/unplugged/@prisma-engines-npm-3.9.0-58.bcc2ff906db47790ee902e7bbc76d7ffb1893009-c1aff4e71f/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at .yarn/unplugged/@prisma-engines-npm-3.9.0-58.bcc2ff906db47790ee902e7bbc76d7ffb1893009-c1aff4e71f/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at .yarn/unplugged/@prisma-engines-npm-3.9.0-58.bcc2ff906db47790ee902e7bbc76d7ffb1893009-c1aff4e71f/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at .yarn/unplugged/@prisma-engines-npm-3.9.0-58.bcc2ff906db47790ee902e7bbc76d7ffb1893009-c1aff4e71f/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

**Comment by janpio** [comment]
Is there a correlation between the platform (`openssl-1.0.x` and `openssl-1.1.x`) and the memory size of the Lambda?
Do the `libquery_engine-rhel-openssl-1.1.x.so.node` generally ever work?

**Comment by halvardssm** [comment]
Actually yes: 128=1.0, 256=1.1. So far, some of the 1.1 requests are working, but others are getting the error above.

The only way to reproduce this would be to deploy some lambdas with 128 and some with 256, and see how they behave differently/
