### ISSUE TITLE
Not able to set utf8mb4 character collation, running into encoding issues with emojis.

### ISSUE THREAD

**Issue by flobraeuer** [prisma/prisma#11842]
Dear community, after a database migration we face serious issues in the production system, and I hope you can help me quickly!

We face issues with storing emojis and other special characters in our MySQL database. We get the following error:

> Conversion from collation utf8_general_ci into utf8mb4_unicode_520_ci impossible for parameter

`prisma:query INSERT INTO `app`.`show` [...]
PrismaClientUnknownRequestError: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError {
   code: 3988,
   message: "Conversion from collation utf8_general_ci into utf8mb4_0900_ai_ci impossible for parameter",
   state: "HY000" })) })
at cb (/app/node_modules/@prisma/client/runtime/index.js:38695:17) { clientVersion: '3.8.1' }
prisma:query ROLLBACK`

Our MySQL cluster has utf8mb4_0900_ai_ci set as default on all levels (db, table, column) but Prisma still sends utf8 (utf8mb3) to the database. How can I configure the charset of the underlying mysql-client?

I tried `SQL_PRISMA_URL='mysql://user:pass@host:port/db?charset=UTF8MB4&sslmode=require&sslcert=ssl.crt&sslaccept=accept_invalid_certs'` but the charset argument gets ignored. It is also not listed as an argument which is passed, so I wonder how I can specify it. Here is the docs: https://www.prisma.io/docs/concepts/database-connectors/mysql#connection-details

Querying `await prisma.$queryRaw(SHOW VARIABLES LIKE 'character_set_%')` returns

- 'character_set_client': 'utf8mb3'
- 'character_set_connection': 'utf8mb3'
- 'character_set_database': 'utf8mb4'
- 'character_set_results': 'utf8mb3'
- 'character_set_server': 'utf8mb4'
- 'character_set_system': 'utf8mb3'

Which shows that it is a Prisma mysql-client/connection issue.

Thanks for help!
Florian

**Comment by janpio** [comment]
Can you share that data you are trying to insert to your database?
Can you also share an example `CREATE TABLE` for one of your tables in that database?

**Comment by flobraeuer** [comment]
Sure! Thanks for help! This `CREATE TABLE` is from a fresh mysqldump:

```
DROP TABLE IF EXISTS `show`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `show` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(40) NOT NULL DEFAULT (hex(uuid_to_bin(uuid()))),
  `startsAt` datetime NOT NULL,
  `title` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `show_uuid_key` (`uuid`),
) ENGINE=InnoDB AUTO_INCREMENT=3342 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
```

And this is the `schema.prisma` definition which is in sync with `npx prisma db push`:

```
model Show {
  id                Int       @id @default(autoincrement()) @db.UnsignedInt
  uuid              String    @unique @default(dbgenerated("(hex(uuid_to_bin(uuid())))")) @db.VarChar(40)
  startsAt          DateTime  @db.DateTime(0)
  title             String    @db.Text
  @@map("show")
}
```

And this is the function I have to do so (no matter if on create or on update):

```
static update = async (uuid:string, data:any) =>{
  console.dir(data);
  let record = await prisma.show.update({
    where: {
      uuid: uuid
    },
    data: {
      title: data.title,
      startsAt: data.starts_at
    }
  });
  return new this(record);
}
```

And this is the data I try to insert (output by above `console.dir`):

```
2022-02-16 17:55:36: show update #0D8F71D18F4911ECA20EEEAB9DAD05F
{
  title: 'This is a show title with a lot of love ❤️ and passion 🤩 and fun 🎉',
  starts_at: '2022-02-17T16:50:09.000Z',
}
prisma:query SELECT 1
prisma:query BEGIN
prisma:query SELECT `app`.`show`.`id` FROM `app`.`show` WHERE `app`.`show`.`uuid` = ?
prisma:query UPDATE `app`.`show` SET `title` = ?, `startsAt` = ? WHERE `app`.`show`.`id` IN (?)
prisma:query ROLLBACK
2022-02-16 17:55:37: ERROR store updateRoom #0D8F71D18F4911ECA20EEEAB9DAD05F5 (db error)
PrismaClientUnknownRequestError: 
Invalid `prisma.show.update()` invocation in
  223 switch (_a.label) {
  224     case 0:
  225         console.dir(data);
→ 226         return [4 /*yield*/, prisma.show.update(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 3988, message: "Conversion from collation utf8_general_ci into utf8mb4_0900_ai_ci impossible for parameter", state: "HY000" })) })
    at cb (.../node_modules/@prisma/client/runtime/index.js:38707:17)
    at async PrismaClient._request (.../node_modules/@prisma/client/runtime/index.js:40859:18) {
  clientVersion: '3.9.2'
}
```

When I send the request with a title without emojis, everything works smooth:

```
2022-02-16 17:57:10: show update #0D8F71D18F4911ECA20EEEAB9DAD05F
{
  title: 'This is a show title without emojis. Everything fine.',
  starts_at: '2022-02-17T16:50:09.000Z',
}
prisma:query SELECT 1
prisma:query BEGIN
prisma:query SELECT `app`.`show`.`id` FROM `app`.`show` WHERE `app`.`show`.`uuid` = ?
prisma:query UPDATE `app`.`show` SET `title` = ?, `startsAt` = ? WHERE `app`.`show`.`id` IN (?)
prisma:query SELECT `app`.`show`.`id`, `app`.`show`.`uuid`, `app`.`show`.`startsAt`, `app`.`show`.`title` FROM `app`.`show` WHERE `app`.`show`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
```

A general question for a better understanding: How is Prisma connecting to mysql? You are not using the npm package mysql[2] under the hood right? I did not find any information on a connect() function in the node_modules folder. Is it possible to pass arguments to this connection client on-top of the ssl arguments you list here: https://www.prisma.io/docs/concepts/database-connectors/mysql#connection-details

Thanks!

**Comment by flobraeuer** [comment]
@janpio can you please give me an update on this. We face this issue in our production system after migration and see no solution ahead. Do you need more details or can we have a quick phone call if you can not reproduce it? How long does it usually take to confirm a bug on your end?

**Comment by janpio** [comment]
No, we do not give ETAs about bug fixes or functionality. We get to it, when we get to it.

**Comment by flobraeuer** [comment]
Ok, I understand that. But can't you give any input without a developer reproducing it?

- Like a short explanation, how I pass arguments to the mysql-connection inside Prisma or set them as environment variables.
- Or just the explanation of how you behave with encodings/collations? Are they read from the server/env/db?
- Some hint how we can investigate further on our side – I mean utf8mb4 is nothing special, and people on [Stackoverflow]( https://stackoverflow.com/questions/71034035/encoding-issues-storing-emojis-in-mysql-how-can-i-define-a-character-collation/71054524#71054524) pointed out this argument to the mysql connection, but there is prisma in between :-/

**Comment by janpio** [comment]
No, to me this looks like a potential real bug which needs to be confirmed by anyone on our side doing a reproduction using the information your provided (which sounds elaborate enough - which is great).

There is no parameter to set the encoding/collation with Prisma right now (see https://www.prisma.io/docs/concepts/database-connectors/mysql#connection-details), as that never came up as a problem. If we can confirm this, and can not find anything else wrong, this might be the time to introduce that parameter.

**Comment by PanMan** [comment]
I'm having the same issue: Prisma is connecting using UTF8mb3, not mb4. I'm sure this is based on some setting deep in my new database, but in the meantime it is causing issues. 
The best article about it for RDS I found is: 

https://aws.amazon.com/blogs/database/best-practices-for-configuring-parameters-for-amazon-rds-for-mysql-part-3-parameters-related-to-security-operational-manageability-and-connectivity-timeout/

Running `SET NAMES utf8mb4` fixes it for that connection, but there is no way to run this for all prisma connections (in a pool). 
I'm currently testing the init_connect option in that article, which seems to work, but it feels like a workaround: Prisma should have settings what charset to use with a connection.

**Comment by PanMan** [comment]
@flobraeuer are you using a new AWS RDS database? I still can't find where the `UTF8mb3` comes from, after digging trough the database settings and it feels like a strange default, but I do have the same issue - on a new AWS RDS mysql db .

**Comment by PanMan** [comment]
@flobraeuer btw, using `SET NAMES utf8mb4` via `init_connect` (see article above) does seems to fix this, but it feels more like a workaround than a proper fix. One that does work, tho.

**Comment by PanMan** [comment]
For the prisma team: I had this issue in 3 different "brand new" AWS RDS MySQL(8.0.28) servers with default settings. If it helps in debugging I can set up a new server and give you admin access - eg share the credentials on slack or email.

**Comment by chrisAracenaMentorSpaces** [comment]
Running into this issue as well, have there been any updates?

**Comment by Jolg42** [comment]
I tried but could not reproduce this on Prisma version `3.8.1` (version from error message). (or latest)

script
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient();

  const title =
    "This is a show title with a lot of love ❤️ and passion 🤩 and fun 🎉";
  const starts_at = "2022-02-17T16:50:09.000Z";

  const record = await prisma.show.create({
    data: {
      title: title,
      startsAt: starts_at,
    },
  });
  console.log(record);

  const charset = await prisma.$queryRaw`SHOW VARIABLES LIKE 'character_set_%'`;
  console.log(charset);

  prisma.$disconnect();
}

main();
```

I tried with
- a local MySQL 8 instance
```
{
  id: 3344,
  uuid: '7FF474765C2311EDAF670242AC120004',
  startsAt: 2022-02-17T16:50:09.000Z,
  title: 'This is a show title with a lot of love ❤️ and passion 🤩 and fun 🎉'
}
[
  { Variable_name: 'character_set_client', Value: 'utf8mb4' },
  { Variable_name: 'character_set_connection', Value: 'utf8mb4' },
  { Variable_name: 'character_set_database', Value: 'utf8mb4' },
  { Variable_name: 'character_set_filesystem', Value: 'binary' },
  { Variable_name: 'character_set_results', Value: 'utf8mb4' },
  { Variable_name: 'character_set_server', Value: 'utf8mb4' },
  { Variable_name: 'character_set_system', Value: 'utf8mb3' },
  {
    Variable_name: 'character_sets_dir',
    Value: '/usr/share/mysql-8.0/charsets/'
  }
]
```
- a remote AWS RDS 8.0.29 instance
with a new database with defaults
```sql
SELECT @@character_set_database, @@collation_database;
-> utf8mb4	utf8mb4_0900_ai_ci
```
running the script results in
```
{
  id: 3342,
  uuid: '0E8A803E5C2B11EDBBFC063761A39624',
  startsAt: 2022-02-17T16:50:09.000Z,
  title: 'This is a show title with a lot of love ❤️ and passion 🤩 and fun 🎉'
}
[
  { Variable_name: 'character_set_client', Value: 'utf8mb4' },
  { Variable_name: 'character_set_connection', Value: 'utf8mb4' },
  { Variable_name: 'character_set_database', Value: 'utf8mb3' }, <-- on 
  { Variable_name: 'character_set_filesystem', Value: 'binary' },
  { Variable_name: 'character_set_results', Value: 'utf8mb4' },
  { Variable_name: 'character_set_server', Value: 'utf8mb4' },
  { Variable_name: 'character_set_system', Value: 'utf8mb3' },
  {
    Variable_name: 'character_sets_dir',
    Value: '/rdsdbbin/mysql-8.0.29.R7/share/charsets/'
  }
]
```

with a new database with utf8mb3 encoding and utf8_general_ci collation
```sql
SELECT @@character_set_database, @@collation_database;
-> utf8mb3	utf8_general_ci
```
running the script results in
```
{
  id: 3342,
  uuid: '0E8A803E5C2B11EDBBFC063761A39624',
  startsAt: 2022-02-17T16:50:09.000Z,
  title: 'This is a show title with a lot of love ❤️ and passion 🤩 and fun 🎉'
}
[
  { Variable_name: 'character_set_client', Value: 'utf8mb4' },
  { Variable_name: 'character_set_connection', Value: 'utf8mb4' },
  { Variable_name: 'character_set_database', Value: 'utf8mb3' }, <-- on 
  { Variable_name: 'character_set_filesystem', Value: 'binary' },
  { Variable_name: 'character_set_results', Value: 'utf8mb4' },
  { Variable_name: 'character_set_server', Value: 'utf8mb4' },
  { Variable_name: 'character_set_system', Value: 'utf8mb3' },
  {
    Variable_name: 'character_sets_dir',
    Value: '/rdsdbbin/mysql-8.0.29.R7/share/charsets/'
  }
]
```

Could someone help and provide reproduction steps?
@PanMan Could you share access to a server where this happens? (Best would be to email `schemas@prisma.io` and ping me here in this issue.)

**Comment by PanMan** [comment]
Thanks for looking into this!

I have since set up multiple prisma servers, and never had this issue again, but I also don't know what caused it in this instance.. I think there we still run with the workaround to do "SET NAMES utf8mb4" on the server-side... 
I think I can open a new RDS instance for you, but that would be the same as you starting an RDS instance I think... 
our live servers now have the "set names" thing applied, so this doesn't happen there.

**Comment by pranav-chefman** [comment]
Hey Everyone,

I was able to conditionally reproduce this.

- When the SSL is enforced, the charset changes to `utf8mb3` and I get the emoji issue
- When the SSL is not enforced, the charset remains `utf8mb4`; it works as expected.

**Comment by PanMan** [comment]
Ah, whow. That totally makes sense: We forced SSL on the connections on that server.. So what @pranav-chefman could be the cause (no idea Why SSL would change the charset tho..)

**Comment by janpio** [comment]
Wow. That sounds super weird, but if it reproduces...

Can you help us by describing the steps you took so we can do that ourselves?
A repository with a project setup with Docker containers would be even nicer.

**Comment by haydenbleasel** [comment]
Hey folks, I have a temporary workaround for anyone using the same stack as me. This is definitely a Prisma related issue as I checked the encoding and data on the MySQL database as well as the data before and after it was sent.

Specifically, I was having issues with strings inside JSON fields. An mdash (`—`) was being stored as `â` (or similar) which isn't valid encoding, so I couldn't simply decode the string after fetching it.

Prisma seems to send the content with the correct encoding, just not retrieve it.

I solved the problem in the meantime by circumventing Prisma for fetches entirely. I'm using PlanetScale, so this just meant using `@planetscale/database` Node.js package and performing a highly specific request:

```ts
import { connect } from '@planetscale/database';

// Destructure Database URL e.g. mysql://username:password@host
const [username, password] = process.env.DATABASE_URL
  .split('//')[1]
  .split('@')[0]
  .split(':');
const host = databaseUrl.split('@')[1].split('?')[0];

const conn = await connect({ host, username, password });

const response = await conn.execute(
  `SELECT ${column} FROM ${tableName} WHERE id = "${id}"`
);

return response.rows[0][column] as object;
```

Not a good solution, but it solves a customer support ticket 😂

**Comment by haydenbleasel** [comment]
Alternative: you can intercept the request and patch the response like so:

```ts
const database = prisma.$extends({
  query: {
    myTableName: {
      async findFirst({ args, query }) {
        if (!args.select?.content) {
          return query(args);
        }

        const result = await query({
          ...args,
          select: {
            ...args.select,
            id: true,
          },
        });

        if (result) {
          result.content = await getJsonColumnFromTable(
            'my_table_name',
            'content',
            result.id as string
          );
        }

        return result;
      },
      async findMany({ args, query }) {
        if (!args.select?.content) {
          return query(args);
        }

        let results = await query({
          ...args,
          select: {
            ...args.select,
            id: true,
          },
        });

        const promises = results.map(async (result) => ({
          ...result,
          content: await getJsonColumnFromTable(
            'my_table_name',
            'content',
            result.id as string
          ),
        }));

        results = await Promise.all(promises);

        return results;
      },
      async findUnique({ args, query }) {
        if (args.select?.content) {
          args.select.id = true;
        }

        const result = await query({
          ...args,
          select: {
            ...args.select,
            id: true,
          },
        });

        if (result) {
          result.content = await getJsonColumnFromTable(
            'my_table_name',
            'content',
            result.id as string
          );
        }

        return result;
      },
    },
  }
});
```

Unfortunately these rules don't apply to nested queries though e.g.

```
await prisma.otherFeature.findFirst({
  where: { id: 'abc' },
  select: {
    myTableName: {
      content: true,
    }
  }
})
```
