### ISSUE TITLE
MongoDB: Better error message for when document does not match the defined schema

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11853]
With this Prisma schema:
```prisma
model mandatory {
  id   String @id @default(auto()) @map("_id") @db.ObjectId
  name String
}
```

this small script:
```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  const all = await prisma.mandatory.findMany()
  console.log(`all: `, all)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

creates the following output for the following data situations:
```
# no data
C:\Users\Jan\Documents\mongodb-errors>node mandatory.js   
all:  []
```
```
# only 1 document that has a `name` value
/*
[{
  "_id": {
    "$oid": "620d2926d32bc973f7f01781"
  },
  "name": "foo"
}]
*/
C:\Users\Jan\Documents\mongodb-errors>node mandatory.js
all:  [ { id: '620d2926d32bc973f7f01781', name: 'foo' } ]
```
```
# another document added that is missing the required `name` value
/*
[{
  "_id": {
    "$oid": "620d2926d32bc973f7f01781"
  },
  "name": "foo"
},{
  "_id": {
    "$oid": "620d2984d32bc973f7f01782"
  }
}]
*/
C:\Users\Jan\Documents\mongodb-errors>node mandatory.js
PrismaClientUnknownRequestError: 
Invalid `prisma.mandatory.findMany()` invocation in
C:\Users\Jan\Documents\mongodb-errors\mandatory.js:6:38

  3 const prisma = new PrismaClient()
  4
  5 async function main() {
→ 6   const all = await prisma.mandatory.findMany(
  Attempted to serialize scalar 'null' with incompatible type 'String' for field name.
    at cb (C:\Users\Jan\Documents\mongodb-errors\node_modules\@prisma\client\runtime\index.js:39807:17)
    at async PrismaClient._request (C:\Users\Jan\Documents\mongodb-errors\node_modules\@prisma\client\runtime\index.js:40845:18)
    at async main (C:\Users\Jan\Documents\mongodb-errors\mandatory.js:6:15) {
  clientVersion: '3.10.0-dev.49'
}
```

The error message `Attempted to serialize scalar 'null' with incompatible type 'String' for field name` is not very clear. Much better would be a known Prisma Client error with an error code and defined error message that is listed on https://www.prisma.io/docs/reference/api-reference/error-reference#prisma-client-error-types (The unexpected value `null`, the expected type `String` and the field name `name` could make an appearance in that error message)

part of https://github.com/prisma/prisma/issues/11856

**Comment by janpio** [comment]
(The error message can then also be linked on the last ordered list item under this headline: https://www.prisma.io/docs/concepts/overview/what-is-prisma/data-modeling#mongodb)
