### ISSUE TITLE
`No such table: information_schema.sequence` Error on `npx prisma db pull` for fresh install on existing project

### ISSUE THREAD

**Issue by MJGTwo** [prisma/prisma#11910]
### Bug description

I am attempting to connect a Redshift database to Prisma using the postgresql drivers. I did the setup as outlined [here](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases-typescript-postgres) successfully. i followed the database url instructions found [here](https://www.prisma.io/docs/getting-started/setup-prisma/add-to-existing-project/relational-databases/connect-your-database-typescript-postgres) with my credentials matching the following pattern:

`postgresql://username:password@abc-12-345-67-890.eu-west-1.redshift.amazonaws.com:1234/databaseName?schema=foo&readOnlyMode=always`

i run `DEBUG="*" npx prisma db pull` and i get the following error:

```bash
 prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
  prisma:loadEnv project root found at ./package.json +0ms       
  prisma:tryLoadEnv Environment variables loaded from ./.env +0ms
Environment variables loaded from .env
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: ./node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node +0ms
Datasource "db": PostgreSQL database "databaseName", schema "foo" at "abc-12-345-67-890.eu-west-1.redshift.amazonaws.com:1234"

Introspecting based on datasource defined in prisma/schema.prisma …
  prisma:introspectionEngine:rpc starting introspection engine with binary: ./node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x +0ms
  prisma:introspectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n"}]} +21ms
  prisma:introspectionEngine:rpc {
  prisma:introspectionEngine:rpc   jsonrpc: '2.0',
  prisma:introspectionEngine:rpc   error: {
  prisma:introspectionEngine:rpc     code: 4466,
  prisma:introspectionEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:introspectionEngine:rpc     data: {
  prisma:introspectionEngine:rpc       is_panic: false,
  prisma:introspectionEngine:rpc       message: 'Error in connector: Error querying the database: Error querying the database: No such table: information_schema.sequences',
  prisma:introspectionEngine:rpc       backtrace: null
  prisma:introspectionEngine:rpc     }
  prisma:introspectionEngine:rpc   },
  prisma:introspectionEngine:rpc   id: 1
  prisma:introspectionEngine:rpc } +868ms

Error: Error: Error in connector: Error querying the database: Error querying the database: No such table: information_schema.sequences

    at Object.<anonymous> (./node_modules/prisma/build/index.js:46523:29)
    at Object.handleResponse ./node_modules/prisma/build/index.js:46401:38)
    at LineStream4.<anonymous> (./node_modules/prisma/build/index.js:46479:20)
    at LineStream4.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at LineStream4.Readable.push (node:internal/streams/readable:228:10)
    at LineStream4._pushBuffer (./node_modules/prisma/build/index.js:46244:21)
    at LineStream4._transform (./node_modules/prisma/build/index.js:46238:12)
    at LineStream4.Transform._write (node:internal/streams/transform:184:23)
```

i use the same database url for my current postgres drivers with KnexJS, and would like to migrate to Prisma for it's ability to sync data models with my database.

### How to reproduce

1. have a Redshift database that you can connect to with postgres drivers
2. initialize Prisma for an existing project
3. run `DEBUG="*" npx prisma db pull`
4. see error

### Expected behavior

I expect the initialization to happen without an error. 

### Prisma information

from `.env`: 
```bash
# Environment variables declared in this file are automatically made available to Prisma.

# See the documentation for more detail: https://pris.ly/d/prisma-schema#accessing-environment-variables-from-the-schema

# Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server, MongoDB (Preview) and CockroachDB (Preview).

# See the documentation for all the connection string options: https://pris.ly/d/connection-strings

DATABASE_URL="postgresql://username:password@abc-12-345-67-890.eu-west-1.redshift.amazonaws.com:1234/databaseName?schema=foo&readOnlyMode=always"
```

from `schema.prisma`: 

```prisma

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

```

### Environment & setup

- OS: Windows 10, 64-bit, WSL1 using Ubuntu 18.04
- Database: Redshift with Postgresql drivers
- Node version: v16.13.2

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 3.9.2
@prisma/client          : Not found
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

**Comment by janpio** [comment]
Introspection depends on some system databases and tables being present, and one of those seems to be missing for Redshift with PostgreSQL. https://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html mentions something in that direction:

> Because it addresses very different requirements, the specialized data storage schema and query execution engine that Amazon Redshift uses are completely different from the PostgreSQL implementation.

Can you generally use this PostgreSQL connection string in database UIs like DBeaver or similar?

**Comment by MJGTwo** [comment]
I can use DBeaver to connect to the Redshift database successfully using the PostgreSQL Binaries from Windows 10. I can also use `pg` and `knex` packages to connect to it as well. My stack uses NextJS, TypeScript, and React-Query and using Prisma would make this a lot smoother for keeping sync with the Redshift database.

**Comment by MJGTwo** [comment]
I'm not a PostgreSQL expert, but I'm asking to maybe solve this issue: 

- does the `?schema=public` always have to be equal to `public`? for my usage, i have the value `analytics` to make DBeaver work because that schema contains the tables I an querying against.
- do I need to have `readOnly=true` or `readOnlyMode=always` to make Prisma read only for Redshift?

**Comment by MJGTwo** [comment]
Understood. So it seems like Prisma would need to add a new strategy for `db pull` for Redshift to bypass this behavior difference, right?

**Comment by MJGTwo** [comment]
Awesome; looks like a good exercise. Do you need anything else from me on this issue to move forward?

**Comment by janpio** [comment]
No, our next steps now is to a) reproduce the behavior you are seeing and then b) prioritize and implement any necessary changes. No promises and ETA obviously, this is the first time we hear about someone trying to use Prisma with Redshift, so the demand is not super high. On the other hand this is interesting and might be simple to fix.

**Comment by janpio** [comment]
Although, where you could help: What are the fastest steps to make a new Redshift cluster available to the internet to connect to? Is https://aws.amazon.com/premiumsupport/knowledge-center/redshift-cluster-private-public/ enough? Does it need an Elastic IP connected (which the UI offers, but the steps linked above don't mention)?

**Comment by MJGTwo** [comment]
Unfortunately I do not know; my account doesn't have those permissions with my company.

**Comment by MJGTwo** [comment]
Any update on the priority of this feature?

**Comment by janpio** [comment]
Super low, you are the first and only person asking for support of Amazon RedShift. Many other requests have more people asking for it, and so these will be prioritized unfortunately - but hopefully understandably.

Right now this would mostly be a "side project" for one of our Engineers, fighting through the missing information in RedShift to see if we can get Introspection working. Then we might uncover follow up problems in Migrations or Query Engine.

The biggest practical blocker here is that there is no Docker or other local testing environment available for Redshit that I could find. There are a few Docker images, but those are really just PostgreSQL with tiny modifications that would not even trigger error scenarios like the one you are observing. That would make it pretty hard to run our tests regularly on a environment that really behaves like Redshift.

**Comment by fPrager** [comment]
@janpio I would be a plus one to this Redshift-support-request!
Since the release of Prisma 1 I'm a huge fan of this ORM for my private projects. Usually I use a PostgreSQL database in the background and everything works like a charm. 
Now I would like to introduce Prisma in the tech stack of my company too, but we use Redshift as database in our AWS environment. 
Did you come to any known workaround in the meantime to make Prisma compatible with Redshift?

**Comment by janpio** [comment]
You can try migrating the same schema on a PostgreSQL, then `db pull` on that and then use the resulting Prisma Schema with your Redshift instance. That would let you skip the problem above (the missing table is not used when just using Prisma Client) - but of course there might be other, unknown problems waiting for you there.

**Comment by Gulbrandr** [comment]
wanted to comment to follow up and see if this is any traction 

already use Prisma everywhere else and have a use case in q4 that could definitely benefit from this having `db pull` work with Redshift, happy to experiment if you need data as well. 

also wanted to see if any one has had any luck going the manual schema route, and just using the client?

**Comment by MJGTwo** [comment]
@wildky I ended up not using Prisma for this; I used Knex. I created a script to introspect the Redshift schema and translate all the table definitions that I needed into TypeScript interfaces, and then fed them into Knex on the server. It worked pretty well :)

**Comment by wildky** [comment]
> @wildky I ended up not using Prisma for this; I used Knex. I created a script to introspect the Redshift schema and translate all the table definitions that I needed into TypeScript interfaces, and then fed them into Knex on the server. It worked pretty well :)

I also ended up using knex! I was mainly doing big complicated data queries with redshift for this project so Prisma lost a lot of its value quickly anyway.

**Comment by shivamp-argus** [comment]
Is there any updates regarding this?

**Comment by janpio** [comment]
None we are aware of. Last time we checked, RedShift was not emulating this standard PostgreSQL database table that we require on `db pull`.

**Comment by dankelleher** [comment]
+1 for redshift integration from me!

**Comment by mjones-PL** [comment]
+1 for Redshift integration

**Comment by jjensenbloom** [comment]
+1 for Redshift integration
