### ISSUE TITLE
MongoDB: Missing `&ssl=true` leads to `Error: unexpected end of file` on sharded connection string

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#11968]
I have a sharded connection string like `mongodb://user:password@cluster0-shard-00-00.bsdflt.mongodb.net:27017,cluster0-shard-00-01.bsdflt.mongodb.net:27017,cluster0-shard-00-02.bsdflt.mongodb.net:27017/test?retryWrites=true&w=majority&authSource=admin`. Using it with Prisma Client leads to this error message:

```
$ ts-node ./script.ts
PrismaClientInitializationError: 
Invalid `client.user.deleteMany()` invocation in
/home/runner/work/e2e-tests/e2e-tests/databases/mongodb-atlas-sharded/script.ts:7:21

   4 
   5 // A `main` function so that we can use async/await
   6 async function main() {
→  7   await client.user.deleteMany(
  Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: cluster0-shard-00-02.bu2lt.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: cluster0-shard-00-01.bu2lt.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: cluster0-shard-00-00.bu2lt.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, ] }
    at cb (/home/runner/work/e2e-tests/e2e-tests/databases/mongodb-atlas-sharded/node_modules/@prisma/client/runtime/index.js:39812:17) {
  clientVersion: '3.10.0-dev.71',
  errorCode: undefined
}
error Command failed with exit code 1.
```

Adding `&ssl=true` to the connection string makes the script succeed.

**Comment by pantharshit00** [comment]
I can reproduce this. To anyone hitting this, I would recommend using `mongo+srv://` protocol connection string but we do need to improve the error here.
```
 yarn start                                                                                                                                                            ─╯
yarn run v1.22.17
$ ts-node main.ts

/Users/harshitpant/code/reproductions/issue-11968/node_modules/@prisma/client/runtime/index.js:39815
        throw new PrismaClientInitializationError(message, this.client._clientVersion);
              ^
Error: 
Invalid `prisma.post.findMany()` invocation in
/Users/harshitpant/code/reproductions/issue-11968/main.ts:6:34

  3 async function main() {
  4   const prisma = new PrismaClient()
  5 
→ 6   const data = await prisma.post.findMany(
  Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: ReplicaSetNoPrimary, Servers: [ { Address: cluster0-shard-00-01.qxwt8.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: cluster0-shard-00-02.qxwt8.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, { Address: cluster0-shard-00-00.qxwt8.mongodb.net:27017, Type: Unknown, Error: unexpected end of file }, ] }
    at Object.request (/Users/harshitpant/code/reproductions/issue-11968/node_modules/@prisma/client/runtime/index.js:39815:15)
    at PrismaClient._request (/Users/harshitpant/code/reproductions/issue-11968/node_modules/@prisma/client/runtime/index.js:40637:18)
    at main (/Users/harshitpant/code/reproductions/issue-11968/main.ts:6:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by pantharshit00** [comment]
@janpio You are using `mongo+srv://` which will query shards from a SRV record instead of `mongodb://` scheme with all the shards already listed in the URL in the Rust attempt.

**Comment by janpio** [comment]
Yes, I am aware of that. But why does `mongodb://` with a list of shards have a weird error state when not explicitly adding `ssl=true`?

**Comment by pantharshit00** [comment]
Yeah that is the bug here.

**Comment by moersoy** [comment]
```

Invalid `prisma.account.upsert()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "unexpected end of file" } })

```

I'm getting this error even though there is only one hostname connection. This error usually appeared when the number of instant connections was high. 

 "@prisma/client": "4.5.0", node:16-alpine

**Comment by janpio** [comment]
Open a new issue for this please @moersoy, this one is explicitly for multi hostname connection strings. Thanks.
