### ISSUE TITLE
error when count a field with many to many relations

### ISSUE THREAD

**Issue by PegasisForever** [prisma/prisma#11974]
### Bug description

For example with the following (simplified) schema:

```
model Comment {
  id String @id

  upVotedUsers   User[] @relation("upVotes")
  downVotedUsers User[] @relation("downVotes")
}

model User {
  uid String @id

  upVotedComments   Comment[] @relation("upVotes")
  downVotedComments Comment[] @relation("downVotes")
}
```

The following query will fail:

```typescript
await prisma.comment.findMany({
  include: {
    _count: {
      select: {
        upVotedUsers: true,
        downVotedUsers: true,
      },
    },
  },
})
```

### How to reproduce

1. Apply the schema
2. You don't need to insert any data, just run the query:
   ```typescript
   await prisma.comment.findMany({
     include: {
       _count: {
         select: {
           upVotedUsers: true,
           downVotedUsers: true,
         },
       },
     },
   })
   ```
3. Error!

Error message:

```
2022-02-22T07:26:25.330Z prisma:client Prisma Client call:
2022-02-22T07:26:25.331Z prisma:client prisma.comment.findMany({
  include: {
    _count: {
      select: {
        upVotedUsers: true,
        downVotedUsers: true
      }
    }
  }
})
2022-02-22T07:26:25.331Z prisma:client Generated request:
2022-02-22T07:26:25.331Z prisma:client query {
  findManyComment {
    id
    authorUID
    createdAt
    content
    renderedHTML
    parentID
    webpageID
    _count {
      upVotedUsers
      downVotedUsers
    }
  }
}

2022-02-22T07:26:25.331Z prisma:client:libraryEngine sending request, this.libraryStarted: true
2022-02-22T07:26:25.382Z prisma:client:request_handler Error: The column `(not available)` does not exist in the current database.
    at prismaGraphQLToJSError (/Users/pegasis/Projects/Websites/pscs/node_modules/@prisma/client/runtime/index.js:35992:12)
    at Object.request (/Users/pegasis/Projects/Websites/pscs/node_modules/@prisma/client/runtime/index.js:36358:17)
    at Object.request (/Users/pegasis/Projects/Websites/pscs/node_modules/@prisma/client/runtime/index.js:39038:24)
    at PrismaClient._request (/Users/pegasis/Projects/Websites/pscs/node_modules/@prisma/client/runtime/index.js:40859:18)
    at /Users/pegasis/Projects/Websites/pscs/apps/comment-server/src/api/get_comments.ts:33:22
    at Object.<anonymous> (/Users/pegasis/Projects/Websites/pscs/apps/comment-server/src/createRoute.ts:31:29)
PrismaClientKnownRequestError: 
Invalid `prisma.comment.findMany()` invocation in
/Users/pegasis/Projects/Websites/pscs/apps/comment-server/src/api/get_comments.ts:33:43

  30 const prisma = getPrisma()
  31 
  32 await redis.siteViews.incr(body.siteID)
→ 33 const comments = await prisma.comment.findMany(
  The column `(not available)` does not exist in the current database.
    at Object.request (/Users/pegasis/Projects/Websites/pscs/node_modules/@prisma/client/runtime/index.js:39068:15)
    at PrismaClient._request (/Users/pegasis/Projects/Websites/pscs/node_modules/@prisma/client/runtime/index.js:40859:18)
    at /Users/pegasis/Projects/Websites/pscs/apps/comment-server/src/api/get_comments.ts:33:22
    at Object.<anonymous> (/Users/pegasis/Projects/Websites/pscs/apps/comment-server/src/createRoute.ts:31:29) {
  code: 'P2022',
  clientVersion: '3.9.2',
  meta: { column: '(not available)' }
}
```

### Expected behavior

The query should not results an error.

### Prisma information

Full prisma schema:

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity", "interactiveTransactions"]
}

datasource db {
  provider             = "mysql"
  url                  = env("ADMIN_DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Site {
  id     String @id
  domain String

  managers User[]
  webpages Webpage[]
}

model Webpage {
  id String @id @default(uuid())

  siteID String
  site   Site   @relation(fields: [siteID], references: [id])

  url String

  comments Comment[]

  allowComment Boolean

  @@unique([siteID, url])
}

model Comment {
  id String @id @default(uuid())

  authorUID String?
  author    User?   @relation(fields: [authorUID], references: [uid])

  createdAt    DateTime @default(now())
  content      String   @db.Text
  renderedHTML String   @db.Text

  parentID String?
  parent   Comment? @relation("CommentParents", fields: [parentID], references: [id], onDelete: NoAction, onUpdate: NoAction)

  webpageID String
  webpage   Webpage @relation(fields: [webpageID], references: [id])

  upVotedUsers   User[] @relation("upVotes")
  downVotedUsers User[] @relation("downVotes")

  replies Comment[] @relation("CommentParents")
}

model User {
  uid String @id

  comments Comment[]

  upVotedComments   Comment[] @relation("upVotes")
  downVotedComments Comment[] @relation("downVotes")

  lastVotedTime DateTime?

  sites Site[]
}
```

### Environment & setup

- OS: Mac OS 12.1 on M1 Pro
- Database: MySQL
- Node.js version: v16.14.0

### Prisma Version

```
prisma                  : 3.9.2
@prisma/client          : 3.9.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
Preview Features        : referentialIntegrity, interactiveTransactions
```

**Comment by PegasisForever** [comment]
probably related to #9880

**Comment by jxe** [comment]
I'm seeing prisma generate the following query, which has an error, trying to count the number of Values attached m:n to each List.

```
SELECT "public"."List"."id", "public"."List"."uuid",
  "public"."List"."name",  "aggr_selection_0_Value"."_aggr_count_values" 
FROM "public"."List" 
LEFT JOIN (
  SELECT "public"."List"."id", 
  COUNT(("public"."_ListToValue"."A")) AS "_aggr_count_values" 
  FROM "public"."List" 
  LEFT JOIN "public"."_ListToValue" ON (
    "public"."List"."id" = ("public"."_ListToValue"."A")
  ) 
  GROUP BY "public"."List"."id"
) 
AS "aggr_selection_0_Value" 
ON (
  "public"."List"."id" = "aggr_selection_0_Value"."uuid"
) 
WHERE "public"."List"."ownerId" = 1
```

The problem here is that Lists are grouped by the "id" column, not by the "uuid" column, so there is nothing at `"aggr_selection_0_Value"."uuid"`.  If the last part of the select statement is fixed to

```
ON (
  "public"."List"."id" = "aggr_selection_0_Value"."id"
) 
```

then the query works.

`uuid` is the name of the primary key on Value, not List. Does your code just use the wrong table's pk in that place?

**Comment by aqrln** [comment]
Related: https://github.com/prisma/prisma/issues/9880

**Comment by danstarns** [comment]
Cannot reproduce this. **Internal** follow the reproduction steps here: https://github.com/prisma/reproductions/tree/main/gh-11974

@PegasisForever can you conforim you still experience this issue?

**Comment by danstarns** [comment]
Can confirm that this was an issue when using version 3.9.2. To test use the bump version script here: https://github.com/prisma/reproductions/tree/main/gh-11974#how-to-reproduce-on-another-version

Regression test added here: https://github.com/prisma/prisma/pull/15282
