### ISSUE TITLE
PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43 index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by PanMan** [prisma/prisma#11998]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
BTW, the generated url was too long for github to load, and seems to include the report twice?!

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v15.14.0           | 
| OS              | darwin             |
| Prisma Client   | 2.30.3             |
| Query Engine    | query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20|
| Database        | undefined|

## Logs
```
/node_modules/.prisma/client  
  prisma:engine { cwd: '/Users/panman/Dropbox/Backup/Code/bookmydesk-api/prisma' }  
  prisma:engine Search for Query Engine in /Users/panman/Dropbox/Backup/Code/bookmydesk-api/node_modules/.prisma/client  
  plusX Execution permissions of /Users/panman/Dropbox/Backup/Code/bookmydesk-api/node_modules/.prisma/client/query-engine-darwin are fine  
  plusX Execution permissions of /Users/panman/Dropbox/Backup/Code/bookmydesk-api/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '58722' ] }  
  prisma:engine stdout  Starting a mysql pool with 17 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:58722  
  prisma:engine Search for Query Engine in /Users/panman/Dropbox/Backup/Code/bookmydesk-api/node_modules/.prisma/client  
  plusX Execution permissions of /Users/panman/Dropbox/Backup/Code/bookmydesk-api/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.30.3  
  prisma:engine Engine Version: query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20  
  prisma:engine Active provider: mysql  
  prisma:client prisma.queryRaw(SHOW PROCESSLIST, [])   2s
  prisma:client Prisma Client call:  
  prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43
index out of bounds: the len is 0 but the index is 0  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/panman/Dropbox/Backup/Code/bookmydesk-api/node_modules/@prisma/client/runtime/index.js:27696:24)
  prisma:engine       at Socket.emit (node:events:381:22)
  prisma:engine       at Socket.emit (node:domain:470:12)
  prisma:engine       at endReadableNT (node:internal/streams/readable:1307:12)
  prisma:engine       at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:58722
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1138:16) {
  prisma:engine     errno: -61,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 58722
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/Users/panman/Dropbox/Backup/Code/bookmydesk-api/prisma' }  
  prisma:engine Search for Query Engine in /Users/panman/Dropbox/Backup/Code/bookmydesk-api/node_modules/.prisma/client  
  plusX Execution permissions of /Users/panman/Dropbox/Backup/Code/bookmydesk-api/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '58726' ] }  
  prisma:engine stdout  Starting a mysql pool with 17 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:58726  
  prisma:engine Search for Query Engine in /Users/panman/Dropbox/Backup/Code/bookmydesk-api/node_modules/.prisma/client  
  plusX Execution permissions of /Users/panman/Dropbox/Backup/Code/bookmydesk-api/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.30.3  
  prisma:engine Engine Version: query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43
index out of bounds: the len is 0 but the index is 0  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/panman/Dropbox/Backup/Code/bookmydesk-api/node_modules/@prisma/client/runtime/index.js:27696:24)
  prisma:engine       at Socket.emit (node:events:381:22)
  prisma:engine       at Socket.emit (node:domain:470:12)
  prisma:engine       at endReadableNT (node:internal/streams/readable:1307:12)
  prisma:engine       at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
const iets = await prisma.$queryRaw`SHOW PROCESSLIST`;
```

## Prisma Engine Query
```
mutation {
  queryRaw(
    query: "X"
    parameters: "X"
  )
}
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this with latest 3.10 version: 
![image](https://user-images.githubusercontent.com/22195362/155716385-ccf42d20-f74a-4a52-ab33-8d55bb9717f8.png)

Looks like you are using 2.30 which is quite old so please try again with the latest version.

Script used for reproducing:
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient();

  const data = await prisma.$queryRaw`SHOW PROCESSLIST`;
  console.log(data);
  prisma.$disconnect();
}

main();
```
