### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine\core\src\query_document\parser.rs:250:87

### ISSUE THREAD

**Issue by PeaceAntoHim** [prisma/prisma#12011]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.13.2           | 
| OS              | windows            |
| Prisma Client   | 3.8.1              |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Logs
```
sers\user01\Documents\next-prisma-film-app\node_modules\.prisma\client\query_engine-windows.dll.node  
  prisma:tryLoadEnv Environment variables loaded from C:\Users\user01\Documents\next-prisma-film-app\.env  +1m
  prisma:client clientVersion: 3.8.1  +1m
  prisma:client clientEngineType: library  
  prisma:client:libraryEngine internalSetup  +1m
  prisma:client:libraryEngine Searching for Query Engine Library in C:\Users\user01\Documents\next-prisma-film-app\node_modules\.prisma\client  
  prisma:client:libraryEngine loadEngine using C:\Users\user01\Documents\next-prisma-film-app\node_modules\.prisma\client\query_engine-windows.dll.node  
  prisma:client:libraryEngine sending request, this.libraryStarted: false  
  prisma:client:libraryEngine library starting  
  prisma:client:libraryEngine library started  
  prisma:tryLoadEnv Environment variables loaded from C:\Users\user01\Documents\next-prisma-film-app\.env  +4s
  prisma:client clientVersion: 3.8.1  +4s
  prisma:client clientEngineType: library  
  prisma:client:libraryEngine internalSetup  +4s
  prisma:client:libraryEngine Searching for Query Engine Library in C:\Users\user01\Documents\next-prisma-film-app\node_modules\.prisma\client  
  prisma:client:libraryEngine loadEngine using C:\Users\user01\Documents\next-prisma-film-app\node_modules\.prisma\client\query_engine-windows.dll.node  
  prisma:client:libraryEngine sending request, this.libraryStarted: false  
  prisma:client:libraryEngine library starting  
  prisma:client:libraryEngine library started  
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +2s
  prisma:tryLoadEnv Environment variables loaded from C:\Users\user01\Documents\next-prisma-film-app\.env  +4s
  prisma:client clientVersion: 3.8.1  +4s
  prisma:client clientEngineType: library  
  prisma:client:libraryEngine internalSetup  +2s
  prisma:client:libraryEngine Searching for Query Engine Library in C:\Users\user01\Documents\next-prisma-film-app\node_modules\.prisma\client  
  prisma:client:libraryEngine loadEngine using C:\Users\user01\Documents\next-prisma-film-app\node_modules\.prisma\client\query_engine-windows.dll.node  
  prisma:client:libraryEngine sending request, this.libraryStarted: false  
  prisma:client:libraryEngine library starting  
  prisma:client:libraryEngine library started  
  prisma:client:libraryEngine sending request, this.libraryStarted: true  +8s
  prisma:client:fetcher Error: called `Option::unwrap()` on a `None` value
  prisma:client:fetcher     at prismaGraphQLToJSError (C:\Users\user01\Documents\next-prisma-film-app\node_modules\@prisma\client\runtime\index.js:35966:10)
  prisma:client:fetcher     at Object.request (C:\Users\user01\Documents\next-prisma-film-app\node_modules\@prisma\client\runtime\index.js:36327:17)
  prisma:client:fetcher     at async cb (C:\Users\user01\Documents\next-prisma-film-app\node_modules\@prisma\client\runtime\index.js:38661:26)
  prisma:client:fetcher     at async __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(api)/./pages/api/[id].js:11:19)
  prisma:client:fetcher     at async Object.apiResolver (C:\Users\user01\Documents\next-prisma-film-app\node_modules\next\dist\server\api-utils.js:101:9)
  prisma:client:fetcher     at async DevServer.runApi (C:\Users\user01\Documents\next-prisma-film-app\node_modules\next\dist\server\next-server.js:319:9)
  prisma:client:fetcher     at async Object.fn (C:\Users\user01\Documents\next-prisma-film-app\node_modules\next\dist\server\base-server.js:486:37)
  prisma:client:fetcher     at async Router.execute (C:\Users\user01\Documents\next-prisma-film-app\node_modules\next\dist\server\router.js:228:32)
  prisma:client:fetcher     at async DevServer.run (C:\Users\user01\Documents\next-prisma-film-app\node_modules\next\dist\server\base-server.js:598:29)
  prisma:client:fetcher     at async DevServer.run (C:\Users\user01\Documents\next-prisma-film-app\node_modules\next\dist\server\dev\next-dev-server.js:444:20)  +5h
  prisma:tryLoadEnv Environment variables loaded from C:\Users\user01\Documents\next-prisma-film-app\.env  +18s
  prisma:client clientVersion: 3.8.1  +18s
  prisma:client clientEngineType: library  
  prisma:client:libraryEngine internalSetup  +10s
  prisma:client:libraryEngine Searching for Query Engine Library in C:\Users\user01\Documents\next-prisma-film-app\node_modules\.prisma\client  
  prisma:client:libraryEngine loadEngine using C:\Users\user01\Documents\next-prisma-film-app\node_modules\.prisma\client\query_engine-windows.dll.node  
  prisma:client:libraryEngine sending request, this.libraryStarted: false  
  prisma:client:libraryEngine library starting  
  prisma:client:libraryEngine library started  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by janpio** [comment]
Can you please add some information what kind of query you were trying to execute and with which schema @PeaceAntoHim? Thanks.

**Comment by PeaceAntoHim** [comment]
I'm hi I was solved my probleam
