### ISSUE TITLE
MongoDB: `Decimal128 extended JSON not implemented yet.`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12097]
I introspected https://docs.atlas.mongodb.com/sample-data/sample-airbnb/, then replaced the `Decimal` columns with `Json` field type (resulting schema see below). When I then execute a `prisma.listingsAndReviews.findMany()` I get the following error:

```
Message: Error in Prisma Client request: 


Invalid `prisma.listingsAndReviews.findMany()` invocation:


  Decimal128 extended JSON not implemented yet.
  
Query:
{
  "modelName": "listingsAndReviews",
  "operation": "findMany",
  "args": {
    "take": 100,
    "skip": 0,
    "select": {
      "address": true,
      "availability": true,
      "host": true,
      "images": true,
      "review_scores": true,
      "reviews": true,
      "id": true,
      "access": true,
      "accommodates": true,
      "amenities": true,
      "bathrooms": true,
      "bed_type": true,
      "bedrooms": true,
      "beds": true,
      "calendar_last_scraped": true,
      "cancellation_policy": true,
      "cleaning_fee": true,
      "description": true,
      "extra_people": true,
      "first_review": true,
      "guests_included": true,
      "house_rules": true,
      "interaction": true,
      "last_review": true,
      "last_scraped": true,
      "listing_url": true,
      "maximum_nights": true,
      "minimum_nights": true,
      "monthly_price": true,
      "name": true,
      "neighborhood_overview": true,
      "notes": true,
      "number_of_reviews": true,
      "price": true,
      "property_type": true,
      "reviews_per_month": true,
      "room_type": true,
      "security_deposit": true,
      "space": true,
      "summary": true,
      "transit": true,
      "weekly_price": true
    }
  }
}
```

and:

```
thread 'tokio-runtime-worker' panicked at 'Decimal128 extended JSON not implemented yet.', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\bson-2.1.0\src\bson.rs:435:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Schema:
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

type ListingsAndReviewsAddress {
  country         String
  country_code    String
  government_area String
  location        ListingsAndReviewsAddressLocation
  market          String
  street          String
  suburb          String
}

type ListingsAndReviewsAddressLocation {
  coordinates       Float[]
  is_location_exact Boolean
  type              String
}

type ListingsAndReviewsAvailability {
  availability_30  Int
  availability_365 Int
  availability_60  Int
  availability_90  Int
}

type ListingsAndReviewsHost {
  host_about                String
  host_has_profile_pic      Boolean
  host_id                   String
  host_identity_verified    Boolean
  host_is_superhost         Boolean
  host_listings_count       Int
  host_location             String
  host_name                 String
  host_neighbourhood        String
  host_picture_url          String
  host_response_rate        Int?
  host_response_time        String?
  host_thumbnail_url        String
  host_total_listings_count Int
  host_url                  String
  host_verifications        String[]
}

type ListingsAndReviewsImages {
  medium_url     String
  picture_url    String
  thumbnail_url  String
  xl_picture_url String
}

type ListingsAndReviewsReviewScores {
  review_scores_accuracy      Int?
  review_scores_checkin       Int?
  review_scores_cleanliness   Int?
  review_scores_communication Int?
  review_scores_location      Int?
  review_scores_rating        Int?
  review_scores_value         Int?
}

type ListingsAndReviewsReviews {
  id            String   @map("_id")
  comments      String?
  date          DateTime @db.Date
  listing_id    String
  reviewer_id   String
  reviewer_name String
}

model listingsAndReviews {
  id                    String                         @id @map("_id")
  access                String
  accommodates          Int
  address               ListingsAndReviewsAddress
  amenities             String[]
  availability          ListingsAndReviewsAvailability
  bathrooms             Json?
  bed_type              String
  bedrooms              Int?
  beds                  Int?
  calendar_last_scraped DateTime                       @db.Date
  cancellation_policy   String
  cleaning_fee          Json?
  description           String
  extra_people          Json
  first_review          DateTime?                      @db.Date
  guests_included       Json
  host                  ListingsAndReviewsHost
  house_rules           String
  images                ListingsAndReviewsImages
  interaction           String
  last_review           DateTime?                      @db.Date
  last_scraped          DateTime                       @db.Date
  listing_url           String
  maximum_nights        String
  minimum_nights        String
  monthly_price         Json?
  name                  String
  neighborhood_overview String
  notes                 String
  number_of_reviews     Int
  price                 Json
  property_type         String
  review_scores         ListingsAndReviewsReviewScores
  reviews               ListingsAndReviewsReviews[]
  reviews_per_month     Int?
  room_type             String
  security_deposit      Json?
  space                 String
  summary               String
  transit               String
  weekly_price          Json?

  @@index([property_type, room_type, beds], map: "property_type_1_room_type_1_beds_1")
  @@index([name], map: "name_1")
}
```

**Comment by matthewmueller** [comment]
While this would be nice, I wouldn't expect this one to work out of the box.

While I'd prefer we focus on getting Decimal128 support in the query engine: https://github.com/prisma/prisma-engines/issues/2600

In the short-term we could potentially coerce decimals to strings or bytes and offer a limited API.

**Comment by Jolg42** [comment]
Can reproduce in `4.4.0-dev.27`

Note: I imported the sample db with this script https://github.com/neelabalan/mongodb-sample-dataset/

```
DEBUG="*" ts-node main.ts
  prisma:tryLoadEnv  Environment variables not found at null +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/j42/Repros/12099/prisma/.env +1ms
  prisma:tryLoadEnv  Environment variables not found at null +1ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/j42/Repros/12099/prisma/.env +1ms
  prisma:client  dirname /Users/j42/Repros/12099/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /Users/j42/Repros/12099/prisma +1ms
  prisma:client  clientVersion 4.4.0-dev.27 +0ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /Users/j42/Repros/12099/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /Users/j42/Repros/12099/node_modules/.prisma/client/libquery_engine-darwin.dylib.node +0ms
  prisma:client  Prisma Client call: +43ms
  prisma:client  prisma.listingsAndReviews.findMany(undefined) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findManylistingsAndReviews {
    id
    access
    accommodates
    address {
      country
      country_code
      government_area
      location {
        coordinates
        is_location_exact
        type
      }
      market
      street
      suburb
    }
    amenities
    availability {
      availability_30
      availability_365
      availability_60
      availability_90
    }
    bathrooms
    bed_type
    bedrooms
    beds
    calendar_last_scraped
    cancellation_policy
    cleaning_fee
    description
    extra_people
    first_review
    guests_included
    host {
      host_about
      host_has_profile_pic
      host_id
      host_identity_verified
      host_is_superhost
      host_listings_count
      host_location
      host_name
      host_neighbourhood
      host_picture_url
      host_response_rate
      host_response_time
      host_thumbnail_url
      host_total_listings_count
      host_url
      host_verifications
    }
    house_rules
    images {
      medium_url
      picture_url
      thumbnail_url
      xl_picture_url
    }
    interaction
    last_review
    last_scraped
    listing_url
    maximum_nights
    minimum_nights
    monthly_price
    name
    neighborhood_overview
    notes
    number_of_reviews
    price
    property_type
    review_scores {
      review_scores_accuracy
      review_scores_checkin
      review_scores_cleanliness
      review_scores_communication
      review_scores_location
      review_scores_rating
      review_scores_value
    }
    reviews {
      id
      comments
      date
      listing_id
      reviewer_id
      reviewer_name
    }
    reviews_per_month
    room_type
    security_deposit
    space
    summary
    transit
    weekly_price
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +44ms
  prisma:client:libraryEngine  library starting +0ms
  prisma:client:libraryEngine  library started +54ms
thread 'tokio-runtime-worker' panicked at 'Decimal128 extended JSON not implemented yet.', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/bson-2.3.0/src/bson.rs:450:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  prisma:client:request_handler  PrismaClientRustPanicError: Decimal128 extended JSON not implemented yet.

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```

**Comment by janpio** [comment]
Parent issue: https://github.com/prisma/prisma/issues/12099

**Comment by janpio** [comment]
Closing as I created a proper feature request for this: https://github.com/prisma/prisma/issues/16341
