### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/interpreter/query_interpreters/nested_read.rs:232:50

### ISSUE THREAD

**Issue by jonitiso** [prisma/prisma#12155]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.14.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 3.9.1              |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Logs
```
raryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=PANIC%3A+called+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value+in+query-engine%2Fcore%2Fsrc%2Finterpreter%2Fquery_interpreters%2Fnested_read.rs%3A232%3A50&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at Object.logger (/node_modules/@prisma/client/runtime/index.js:36229:30)
    at /node_modules/@prisma/client/runtime/index.js:36198:34
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by janpio** [comment]
Can you please provide some more information what kind of query you were executing etc?

**Comment by jonitiso** [comment]
The problem started from the last compilation of a docker image, one of the containers in the fleet launched this error, when restarting the container it is solved but time later it happens again

**Comment by jonitiso** [comment]
The problem occurs with all queries to the database in this case MariaDB

**Comment by jonitiso** [comment]
The problem has been fixed, a schema relation had the wrong reference

**Comment by janpio** [comment]
Could you please share the schema in its broken state with us? You should never get a `PANIC` like this but a helpful, userful error message. As that is not the case, we would love to fix this.

**Comment by ChristopherTrimboli** [comment]
Can confirm I get this too... just doing a simple `.findMany()` over 6 rows in my DB... here is the schema:

```
model users {
  id                 Int                  @id @default(autoincrement())
  email              String?              @unique(map: "users_unique_email")
  registrationDate   DateTime?            @default(now()) @db.Timestamptz(6)
  lastLoginDate      DateTime?            @db.Date
  name               String?              @unique(map: "users_unique_name")
  birthDate          DateTime?            @db.Date
  emailVerified      Boolean?
  profileImageUrl    String?
  bio                String?
  bannerImageUrl     String?
  address            String               @unique(map: "users_unique_address")
  nonce              String
  link               String?
  nft_mumbai_likes   nft_mumbai_likes[]
  nft_mumbai_reports nft_mumbai_reports[]
  nft_mumbai_views   nft_mumbai_views[]
  post_likes         post_likes[]
  posts              posts[]
}
```

Here is my exact code, Node.js v16 LTS:

```
const usersSearchResult = await prisma.users.findMany();
res.status(200).json(usersSearchResult);
 ```
 
 Console error: 
 
 ```
 called `Option::unwrap()` on a `None` value
 ```
 
This is a critical bug on Prisma `3.10.0` for us... multiple queries crashing randomly, requires server reboots to fix.
Prisma is basically unusable now.
Was using Prisma with same schemas for like 8 months no issues then all of a sudden Rust panics.

PostgresSQL v14
 
Cheers :)

**Comment by ChristopherTrimboli** [comment]
Sidenote... not a jab at Prisma devs but a jab at Rust... HILARIOUS that you get PANICs when whole point of Rust was to avoid this???? ahhhh the irony

**Comment by ChristopherTrimboli** [comment]
Here is my "official report":

%23%23 Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.14.0           | 
| OS              | windows            |
| Prisma Client   | 3.10.0             |
| Query Engine    | 0.1.0              |
| Database        | postgresql         |



%23%23 Logs
```
  prisma:tryLoadEnv Environment variables loaded from C:\Users\chris\Documents\Github\own-me\backend\.env  
  prisma:tryLoadEnv Environment variables loaded from C:\Users\chris\Documents\Github\own-me\backend\.env  
  prisma:client clientVersion: 3.10.0  
  prisma:client clientEngineType: library  
  prisma:client:libraryEngine internalSetup  
  prisma:client:libraryEngine Searching for Query Engine Library in C:\Users\chris\Documents\Github\own-me\backend\node_modules\.prisma\client  
  prisma:client:libraryEngine loadEngine using C:\Users\chris\Documents\Github\own-me\backend\node_modules\.prisma\client\query_engine-windows.dll.node  
  prisma:client:libraryEngine sending request, this.libraryStarted: false   1m
  prisma:client:libraryEngine library starting  
  prisma:client:libraryEngine library started  
  prisma:client:libraryEngine sending request, this.libraryStarted: true   3s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   2s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  
  prisma:client:libraryEngine sending request, this.libraryStarted: true   19s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   3s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   57s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   12s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   8s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   7s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   3s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   6s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   4s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   2s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   3s
  prisma:client:libraryEngine sending request, this.libraryStarted: true   1s
  prisma:client:libraryEngine sending request, this.libraryStarted: true  
```

**Comment by janpio** [comment]
Can you please open a new issue and collect all your information in there @ChristopherTrimboli?
Can you share these 6 rows in your database? Is this reproducible?

**Comment by ChristopherTrimboli** [comment]
Update: behaving OK now just after a computer restart... Could be a deep issue in windows 11 or Rust implementation in OS... Seems completely random, will report back if see it again.

**Comment by jonitiso** [comment]
It is not windows because the error appeared on an aws server with linux and running under a node container

**Comment by janpio** [comment]
I hid the off topic comments that were here about another issue.

Do you @jonitiso by chance still have the broken schema that caused this problem? We would love to be able to reproduce this and return a better error message to our users.

**Comment by Weakky** [comment]
Hey,

This is a duplicate of https://github.com/prisma/prisma/issues/13340 and was fixed by https://github.com/prisma/prisma-engines/pull/2973. It'll be available in Prisma 4.x.

Thanks for reporting 🙏
