### ISSUE TITLE
connectOrCreate on 1-1 relation always triggers create on upsert

### ISSUE THREAD

**Issue by nino-vrijman** [prisma/prisma#12240]
### Bug description

Imagine a Prisma schema where you have a User model and an Author model which have a 1-1 relation. In an application I have created a User (id: A) with a related Author record (id: B).

When using `prisma.user.upsert` on User A with a related Author B record I use `author.connectOrCreate` in the update clause of the `prisma.user.upsert` operation. When User A already has a related Author B record (which it has), I expect nothing to change but it seems like the `create` part of the `connectOrCreate` operation is **always** executed, causing a new Author record (with imaginary id C ) to be created and the old related Author record (B) seems to unintentionally be disconnected from the User.

### How to reproduce

1. Go to https://github.com/nino-vrijman/prisma-upsert-connect-or-create-issue
2. Pull the repo, run npm install
3. Change the database url in `.env`
4. Run `npm run dev`
5. See how two Author records are created in the end where one Author record is expected after the `prisma.user.upsert` operation

### Expected behavior

When using `author.connectOrCreate` in the`update` part of `prisma.user.upsert` on User A with a related Author record B, Author record B should remain connected to User A.

Instead Author record C is created and connected to User A and Author B is disconnected from User A.

### Prisma information

For more info see reproduction repository https://github.com/nino-vrijman/prisma-upsert-connect-or-create-issue.

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id String @id @default(cuid())
  
  author   Author?
}

model Author {
  id String @id @default(cuid())

  user   User?   @relation(fields: [userId], references: [id])
  userId String? @unique

  email String? @unique
  name  String?
}

```

### Environment & setup

- OS: MacOS Monterrey 12.1
- Database: PostgreSQL 12
- Node.js version: 12.22.0

### Prisma Version

```
prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0
```

**Comment by minh-v** [comment]
I am having this exact problem as well, which causes me to get relation violation error.

**Comment by Jolg42** [comment]
Output from `3.10.0`
```
DEBUG="*" npm run dev

> script@ dev /Users/j42/Repros/prisma-upsert-connect-or-create-issue
> ts-node ./script.ts
...
  prisma:client Prisma Client call: +14ms
  prisma:client prisma.user.create({
  prisma:client   data: {
  prisma:client     author: {
  prisma:client       create: {
  prisma:client         email: 'foo@example.com',
  prisma:client         name: 'Foo'
  prisma:client       }
  prisma:client     }
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client mutation {
  prisma:client   createOneUser(data: {
  prisma:client     author: {
  prisma:client       create: {
  prisma:client         email: "foo@example.com"
  prisma:client         name: "Foo"
  prisma:client       }
  prisma:client     }
  prisma:client   }) {
  prisma:client     id
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +16ms
  prisma:client Prisma Client call: +19ms
  prisma:client prisma.author.findMany(undefined) +0ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findManyAuthor {
  prisma:client     id
  prisma:client     userId
  prisma:client     email
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +18ms
author with id cl7q9lm0w00137e4pccplzwb3 is connected to user cl7q9lm0w00127e4p1eu16ihs
  prisma:client Prisma Client call: +5ms
  prisma:client prisma.user.upsert({
  prisma:client   create: {
  prisma:client     author: {
  prisma:client       create: {
  prisma:client         email: 'foo@example.com',
  prisma:client         name: 'Foo'
  prisma:client       }
  prisma:client     }
  prisma:client   },
  prisma:client   update: {
  prisma:client     author: {
  prisma:client       connectOrCreate: {
  prisma:client         create: {
  prisma:client           email: 'should-not-be-created@example.com',
  prisma:client           name: 'should-not-be-created'
  prisma:client         },
  prisma:client         where: {
  prisma:client           userId: 'cl7q9lm0w00127e4p1eu16ihs'
  prisma:client         }
  prisma:client       }
  prisma:client     }
  prisma:client   },
  prisma:client   where: {
  prisma:client     id: 'cl7q9lm0w00127e4p1eu16ihs'
  prisma:client   }
  prisma:client }) +0ms
  prisma:client Generated request: +1ms
  prisma:client mutation {
  prisma:client   upsertOneUser(
  prisma:client     create: {
  prisma:client       author: {
  prisma:client         create: {
  prisma:client           email: "foo@example.com"
  prisma:client           name: "Foo"
  prisma:client         }
  prisma:client       }
  prisma:client     }
  prisma:client     update: {
  prisma:client       author: {
  prisma:client         connectOrCreate: {
  prisma:client           create: {
  prisma:client             email: "should-not-be-created@example.com"
  prisma:client             name: "should-not-be-created"
  prisma:client           }
  prisma:client           where: {
  prisma:client             userId: "cl7q9lm0w00127e4p1eu16ihs"
  prisma:client           }
  prisma:client         }
  prisma:client       }
  prisma:client     }
  prisma:client     where: {
  prisma:client       id: "cl7q9lm0w00127e4p1eu16ihs"
  prisma:client     }
  prisma:client   ) {
  prisma:client     id
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +6ms
author with id cl7q9lm0w00137e4pccplzwb3 should still be connected to user cl7q9lm0w00127e4p1eu16ihs as asserted on line 35
  prisma:client Prisma Client call: +24ms
  prisma:client prisma.author.findUnique({
  prisma:client   where: {
  prisma:client     id: 'cl7q9lm0w00137e4pccplzwb3'
  prisma:client   }
  prisma:client }) +0ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findUniqueAuthor(where: {
  prisma:client     id: "cl7q9lm0w00137e4pccplzwb3"
  prisma:client   }) {
  prisma:client     id
  prisma:client     userId
  prisma:client     email
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +25ms
  prisma:client Prisma Client call: +5ms
  prisma:client prisma.author.findMany(undefined) +0ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findManyAuthor {
  prisma:client     id
  prisma:client     userId
  prisma:client     email
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +4ms
now 2 authors exist in the database while it should be only 1
and the author that was created initially is now disconnected from the user we created {
  id: 'cl7q9lm0w00137e4pccplzwb3',
  userId: null,
  email: 'foo@example.com',
  name: 'Foo'
}
  prisma:client:libraryEngine library stopping +11ms
  prisma:client:libraryEngine library stopped +0ms
(node:49514) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: author is no longer connected to our only user
    at /Users/j42/Repros/prisma-upsert-connect-or-create-issue/script.ts:104:9
    at step (/Users/j42/Repros/prisma-upsert-connect-or-create-issue/script.ts:33:23)
    at Object.next (/Users/j42/Repros/prisma-upsert-connect-or-create-issue/script.ts:14:53)
    at fulfilled (/Users/j42/Repros/prisma-upsert-connect-or-create-issue/script.ts:5:58)
```

3.10.0 without debug
```
author with id cl7q9qgqz0009kh4p665l7tpx is connected to user cl7q9qgqz0008kh4plhru14e7
author with id cl7q9qgqz0009kh4p665l7tpx should still be connected to user cl7q9qgqz0008kh4plhru14e7 as asserted on line 35
now 2 authors exist in the database while it should be only 1
and the author that was created initially is now disconnected from the user we created {
  id: 'cl7q9qgqz0009kh4p665l7tpx',
  userId: null,
  email: 'foo@example.com',
  name: 'Foo'
}
```

4.3.1 doesn't show this issue anymore ✅ (Same in 3.15.0)
```
author with id cl7q9up1700133r4p9ama1gq8 is connected to user cl7q9up1700123r4p85lljfp4
author with id cl7q9up1700133r4p9ama1gq8 should still be connected to user cl7q9up1700123r4p85lljfp4 as asserted on line 35
prisma:warn `rejectOnNotFound` option is deprecated and will be removed in Prisma 5. Please use `prisma.author.findUniqueOrThrow` method instead
now 1 authors exist in the database while it should be only 1
and the author that was created initially is now disconnected from the user we created {
  id: 'cl7q9up1700133r4p9ama1gq8',
  userId: 'cl7q9up1700123r4p85lljfp4',
  email: 'foo@example.com',
  name: 'Foo'
}
```

Closing as already fixed. Let us know if you can still reproduce with a recent version.
