### ISSUE TITLE
Fulltext sorting on _relevance bug

### ISSUE THREAD

**Issue by joshribakoff-sm** [prisma/prisma#12247]
### Bug description

`_relevance` does not work correctly with nested queries:

```
   '  The table `(not available)` does not exist in the current database.',
    '    at Object.request (/Users/jribakoff/a/node_modules/@prisma/client/runtime/index.js:39809:15)',
    '    at PrismaClient._request (/Users/jribakoff/a/node_modules/@prisma/client/runtime/index.js:40637:18)'
```

### How to reproduce

I am doing something that effectively reduces down to this, a nested search on a "parent" and a "child" record. I want to rank the matching parents to the top. Within each parent, I also want it's children records ranked in the order they matched.

```ts
const res = await prisma.categories.findMany({
  orderBy: {
    _relevance: {
      fields: ["label"],
      search,
      sort: "desc",
    },
  },
  include: {
    category_products: {
      select: {
        product: true,
      },
      orderBy: {
        product: {
          _relevance: {
            fields: ["label"],
            search,
            sort: "desc",
          },
        },
      },
    },
  },
});

```

### Expected behavior

At minimum, I would suggest It should at least produce a Typescript error if it is not supported

### Prisma information

Please reach out if you need more info, I am limited in what I can share.

### Environment & setup

Mac, postgres, node 16

### Prisma Version

```
3.9.1
```

**Comment by pantharshit00** [comment]
Hello,

Can you please only share the models that are in the query? You can privately share this data via schemas@prisma.io

**Comment by joshribakoff-sm** [comment]
The schema looks something like this. I removed some field(s) not related to this query, and the names of the models are changed to preserve confidentiality.

```
model category {
  id               String                       @id
  label            String                       @unique
}

model product {
  id               String                       @id
  label            String                       @unique
}

model product_category_relationship {
  product_id        String
  category_id      String
  product   product    @relation(fields: [product_id], references: [id])
  category category @relation(fields: [category_id], references: [id])
  @@id([product_id, category_id])
  @@unique([product_id, category_id])
}
```

**Comment by yassersebai** [comment]
just want to get attention back to this issue, any updates ?

**Comment by janpio** [comment]
No updates, and no need to bring our attention to any issue - we are aware they exist, but are working on things in a prioritized order and this is unfortunately not at the top of any list. Sorry.

**Comment by yassersebai** [comment]
wow, didn't realize asking for updates on a github issue would be this irritating for repo maintainers. Isn't it like a normal thing on other repos?.
anyway, just knew this isn't seeing light any time soon, thanks for the update!.

**Comment by janpio** [comment]
Sorry that you are reading irritation into my message. I just tried to be very explicit in my response about that there are no updates - but that there is also no need to ask for updates. We get dozens of such requests per week, which sends notifications to both subscribed users and maintainers and then requires time for us to respond to. If you have a suggestion on how I should deal with such messages instead, let me know.
