### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/connectors/mongodb-query-connector/src/root_queries/write.rs:353:89

### ISSUE THREAD

**Issue by Artak-Mkrtchyan** [prisma/prisma#12251]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.19.0           | 
| OS              | darwin             |
| Prisma Client   | 3.8.1              |
| Query Engine    | 0.1.0              |
| Database        | mongodb            |

## Logs
```
  prisma:tryLoadEnv Environment variables not found at null  
  prisma:tryLoadEnv Environment variables loaded from /Users/admin/Documents/instagram-clone/server/.env  
  prisma:tryLoadEnv Environment variables not found at null  
  prisma:tryLoadEnv Environment variables loaded from /Users/admin/Documents/instagram-clone/server/.env  
  prisma:client clientVersion: 3.8.1  
  prisma:client clientEngineType: library  
  prisma:client:libraryEngine internalSetup  
  prisma:client:libraryEngine Searching for Query Engine Library in /Users/admin/Documents/instagram-clone/common/temp/node_modules/.pnpm/@prisma+client@3.8.1_prisma@3.8.1/node_modules/.prisma/client  
  prisma:client:libraryEngine loadEngine using /Users/admin/Documents/instagram-clone/common/temp/node_modules/.pnpm/@prisma+client@3.8.1_prisma@3.8.1/node_modules/.prisma/client/libquery_engine-darwin.dylib.node  
  prisma:client:libraryEngine sending request, this.libraryStarted: false  +16s
  prisma:client:libraryEngine library starting  
  prisma:client:libraryEngine library started  
  prisma:client:libraryEngine sending request, this.libraryStarted: true  
```

## Client Snippet
```ts
import { Context } from 'src/context';
import { isAuthenticated } from 'src/middlewares';

export const resolvers = {
  Mutation: {
    searchUser: async (
      _: Record<string, unknown>,
      args: { term: string },
      context: Context
    ) => {
      try {
        console.log(args.term);
        isAuthenticated(context);

        if (args.term.length > 0) {

            const users = await context.prisma.user.findMany({
              where: {
                OR: [
                  { username: { contains: args.term } },
                  { name: { contains: args.term } },
                  { email: { contains: args.term } },
                ],
              },
            });


          await context.prisma.user.update({
            where: {
              id: context.user.id,
            },
            data: {
              recentSearch: {
                connect: { id: context.user.id },
              },
            },
          });

          return users;
        }

        const recentUsers = await context.prisma.user
          .findUnique({
            where: {
              id: context.user.id,
            },
          })
          .recentSearch();
        console.log(recentUsers);
        return recentUsers || [];
      } catch (e: any) {
        console.log(e)
        throw new Error(`Error: ${e}`);
      }
    },
  },
};
```

## Schema
```prisma
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

model User {
  id              String    @id @default(dbgenerated()) @map("_id") @db.ObjectId
  avatar          String    @default(value: "https://cdn0.iconfinder.com/data/icons/set-ui-app-android/32/8-512.png")
  name            String
  username        String    @unique
  password        String
  email           String    @unique
  gender          String?
  phoneNumber     Int?
  bio             String
  following       User[]    @relation("UserFollows", fields: [followingIDs])
  followingIDs    String[]  @db.Array(ObjectId)
  followers       User[]    @relation("UserFollows", fields: [followedByIDs])
  followedByIDs   String[]  @db.Array(ObjectId)
  posts           Post[]
  likes           Like[]
  comments        Comment[]
  channels        Channel[]
  loginSecret     String?
  recentSearch    User[]    @relation("RecentSearch", fields: [recentSearchIDs])
  recentSearchIDs String[]  @db.Array(ObjectId)
  predecessor     User[]    @relation("RecentSearch")
  testingAccount  Boolean   @default(false)
  createdAt       DateTime  @default(now())
  updatedAt       DateTime  @updatedAt
  message         Message[]
}

model Post {
  id        String    @id @default(dbgenerated()) @map("_id") @db.ObjectId
  location  String
  caption   String
  user      User      @relation(fields: [authorId], references: [id])
  files     File[]
  likes     Like[]
  comments  Comment[]
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  authorId  String    @db.ObjectId
}

model Like {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  user      User     @relation(fields: [authorId], references: [id])
  post      Post     @relation(fields: [postId], references: [id])
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  authorId  String   @db.ObjectId
  postId    String   @db.ObjectId
}

model Comment {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  text      String
  user      User     @relation(fields: [userId], references: [id])
  post      Post     @relation(fields: [postId], references: [id])
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  postId    String   @db.ObjectId
  userId    String   @db.ObjectId
}

model File {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  url       String
  post      Post     @relation(fields: [postId], references: [id])
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  postId    String   @db.ObjectId
}

model Channel {
  id           String    @id @default(dbgenerated()) @map("_id") @db.ObjectId
  participants User[]
  messages     Message[]
  createdAt    DateTime  @default(now())
  updatedAt    DateTime  @updatedAt
}

model Message {
  id        String   @id @default(dbgenerated()) @map("_id") @db.ObjectId
  text      String
  user      User     @relation(fields: [userId], references: [id])
  userId    String   @db.ObjectId
  channel   Channel  @relation(fields: [channelId], references: [id])
  channelId String   @db.ObjectId
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by ChristopherTrimboli** [comment]
I have similar issue. It is `tokio-runtime-worker` I think.

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', query-engine\core\src\query_document\parser.rs:250:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PrismaClientUnknownRequestError:
Invalid `prisma.nfts_mumbai.findUnique()` invocation:


  called `Option::unwrap()` on a `None` value
    at Object.request (C:\Users\chris\Documents\Github\own-me\backend\node_modules\@prisma\client\runtime\index.js:39813:15)
    at async PrismaClient._request (C:\Users\chris\Documents\Github\own-me\backend\node_modules\@prisma\client\runtime\index.js:40637:18)
    at async file:///C:/Users/chris/Documents/Github/own-me/backend/dist/api/nft/admin/getNft.js:11:33
    at async getAdminNftRequest (file:///C:/Users/chris/Documents/Github/own-me/backend/dist/api/nft/admin/getNft.js:7:9) {
  clientVersion: '3.10.0'
}
PrismaClientRustPanicError: 
Invalid `prisma.nfts_mumbai.findUnique()` invocation:


 PANIC: called `Option::unwrap()` on a `None` value in query-engine\core\src\query_document\parser.rs:250:87

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```

**Comment by pantharshit00** [comment]
Hello @Artak-Mkrtchyan 

Can you please try this once again with the latest version? MongoDB is a preview feature so it gets frequent changes so this might be already addressed.

@ChristopherTrimboli The panic you have reported is different and singles towards a bug in query parser, can you please open a new issue with more details?
