### ISSUE TITLE
Cannot run queries with small "notIn" or "not: null" on large tables

### ISSUE THREAD

**Issue by drico** [prisma/prisma#12499]
### Bug description

When querying the following in large tables, with postgresql, an error is raised by prisma.
It says that the negative filter prevents the request from being split.

But the negative filter only contains 1 or 2 parameters (either a "notIn [1,2]" or a "not: null").

This short filter should not be a problem.

This code was working fine in prisma 3.5.0 and the error raises since 3.6.0

### How to reproduce

Run the provided request with large tables with a `notIn` filter with the provided schema.

The request will fail

### Expected behavior

The query should run properly.

### Prisma information

Prisma query :

```
const machines = await prisma.tblMachine.findMany({
    select: {
      MCH_MACHLINK: true,
      parts: {
        where: {
          PRT_BLOCKED: 'N',
          PRT_DELETED: { notIn: [1, 2] }, // the negative filter. also fails if I replace it with "PRT_DELETED: { not: null }",
        },
        select: {
          PRT_PARTLINK: true,
        },
      },
    },
    orderBy: [{ MCH_MACHLINK: 'asc' }],
    take: 500,
  });
```

Prisma schema :

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model TblMachine {
  MCH_MACHLINK Int       @id
  parts        TblPart[]
}

model TblPart {
  PRT_PARTLINK Int        @id
  PRT_MACHLINK Int
  PRT_DELETED  Int?       @db.SmallInt
  PRT_BLOCKED  String?    @db.VarChar(1)
  machine      TblMachine @relation(fields: [PRT_MACHLINK], references: [MCH_MACHLINK])
}
```

Prisma logs :

```
  prisma:tryLoadEnv Environment variables loaded from /Users/drico/github/anacApiV2/backend/server/.env +0ms
  prisma:tryLoadEnv Environment variables loaded from /Users/drico/github/anacApiV2/backend/server/.env +3ms
  prisma:client clientVersion: 3.10.0 +0ms
  prisma:client clientEngineType: library +0ms
  prisma:client:libraryEngine internalSetup +0ms
  prisma:client:libraryEngine Searching for Query Engine Library in /Users/drico/github/anacApiV2/backend/server/node_modules/.prisma/client +10ms
  prisma:client:libraryEngine loadEngine using /Users/drico/github/anacApiV2/backend/server/node_modules/.prisma/client/libquery_engine-darwin.dylib.node +0ms
  prisma:client Prisma Client call: +960ms
  prisma:client prisma.tblMachine.findMany({
  prisma:client   select: {
  prisma:client     MCH_MACHLINK: true,
  prisma:client     parts: {
  prisma:client       where: {
  prisma:client         PRT_BLOCKED: 'N',
  prisma:client         PRT_DELETED: {
  prisma:client           notIn: [
  prisma:client             1,
  prisma:client             2
  prisma:client           ]
  prisma:client         }
  prisma:client       },
  prisma:client       select: {
  prisma:client         PRT_PARTLINK: true
  prisma:client       }
  prisma:client     }
  prisma:client   },
  prisma:client   orderBy: [
  prisma:client     {
  prisma:client       MCH_MACHLINK: 'asc'
  prisma:client     }
  prisma:client   ],
  prisma:client   take: 500,
  prisma:client   where: {}
  prisma:client }) +1ms
  prisma:client Generated request: +1ms
  prisma:client query {
  prisma:client   findManyTblMachine(
  prisma:client     orderBy: [
  prisma:client       {
  prisma:client         MCH_MACHLINK: asc
  prisma:client       }
  prisma:client     ]
  prisma:client     take: 500
  prisma:client     where: {
  prisma:client 
  prisma:client     }
  prisma:client   ) {
  prisma:client     MCH_MACHLINK
  prisma:client     parts(where: {
  prisma:client       PRT_BLOCKED: "N"
  prisma:client       PRT_DELETED: {
  prisma:client         notIn: [1, 2]
  prisma:client       }
  prisma:client     }) {
  prisma:client       PRT_PARTLINK
  prisma:client     }
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: false +951ms
  prisma:client:libraryEngine library starting +0ms
prisma:info Starting a postgresql pool with 10 connections.
  prisma:client:libraryEngine library started +541ms
prisma:query SELECT "ANAC"."TBLMACHINE"."MCH_MACHLINK" FROM "ANAC"."TBLMACHINE" WHERE 1=1 ORDER BY "ANAC"."TBLMACHINE"."MCH_MACHLINK" ASC LIMIT $1 OFFSET $2
  prisma:client:request_handler Error: Query parameter limit exceeded error: Parameter limits for this database provider require this query to be split into multiple queries, but the negation filters used prevent the query from being split. Please reduce the used values in the query..
  prisma:client:request_handler     at prismaGraphQLToJSError (/Users/drico/github/anacApiV2/backend/server/node_modules/@prisma/client/runtime/index.js:33913:12)
  prisma:client:request_handler     at Object.request (/Users/drico/github/anacApiV2/backend/server/node_modules/@prisma/client/runtime/index.js:35739:17)
  prisma:client:request_handler     at Object.request (/Users/drico/github/anacApiV2/backend/server/node_modules/@prisma/client/runtime/index.js:39779:24)
  prisma:client:request_handler     at PrismaClient._request (/Users/drico/github/anacApiV2/backend/server/node_modules/@prisma/client/runtime/index.js:40637:18)
  prisma:client:request_handler     at fetchBatch (/Users/drico/github/anacApiV2/backend/server/src/tasks/elastic/syncMachines.ts:154:20)
  prisma:client:request_handler     at /Users/drico/github/anacApiV2/backend/server/src/tasks/elastic/helpers.ts:83:28 +0ms
Error !
PrismaClientKnownRequestError: 
Invalid `prisma.tblMachine.findMany()` invocation in
/Users/drico/github/anacApiV2/backend/server/src/tasks/elastic/syncMachines.ts:154:44

→ 154   const machines = await prisma.tblMachine.findMany(
  Query parameter limit exceeded error: Parameter limits for this database provider require this query to be split into multiple queries, but the negation filters used prevent the query from being split. Please reduce the used values in the query..
    at Object.request (/Users/drico/github/anacApiV2/backend/server/node_modules/@prisma/client/runtime/index.js:39809:15)
    at PrismaClient._request (/Users/drico/github/anacApiV2/backend/server/node_modules/@prisma/client/runtime/index.js:40637:18)
    at fetchBatch (/Users/drico/github/anacApiV2/backend/server/src/tasks/elastic/syncMachines.ts:154:20)
    at /Users/drico/github/anacApiV2/backend/server/src/tasks/elastic/helpers.ts:83:28 {
  code: 'P2029',
  clientVersion: '3.10.0',
  meta: {
    message: 'Parameter limits for this database provider require this query to be split into multiple queries, but the negation filters used prevent the query from being split. Please reduce the used values in the query.'
  }
}
  prisma:client:libraryEngine hookProcess received: exit +128ms
  prisma:client:libraryEngine runBeforeExit +0ms
error Command failed with exit code 1.
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14.17.6

### Prisma Version

```
prisma                  : 3.10.0
@prisma/client          : 3.10.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 73e60b76d394f8d37d8ebd1f8918c79029f0db86 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 73e60b76d394f8d37d8ebd1f8918c79029f0db86
Studio                  : 0.458.0

```

**Comment by janpio** [comment]
Is this reproducible with the minimal Prisma schema and query you mentioned above? If so, we will try and see if we can also trigger this error.

**Comment by Jolg42** [comment]
I tried to reproduce by creating thousands of records, but unfortunately I can't reproduce this.
@drico Could you give us a reproduction if this is still an issue? (did you try with a recent Prisma v4 version?)

**Comment by StErMi** [comment]
I got the same error, I'm using `"@prisma/client": "^4.5.0",` and `"prisma": "^4.5.0",` with a `sqlite` db for the moment.

The error is raised when I try to call the query like

```ts
const snapshots = await prisma.snapshots.findMany({
    where: {
        // ... other code
        AND: [
            {
                // other code
            },
            {
                assetId: {
                    notIn: notInAlreadySelected,
                },
            },
        ],
    },
    include: {
        // other code
    },
    orderBy: {
        timestamp: 'desc',
    },
    distinct: ['assetId'],
});
```  

`notInAlreadySelected` is an array of **1051** IDs at the moment

**Comment by janpio** [comment]
Thanks, that code snippet is already great. As you are using SQLite, can you maybe quickly recreate your project with a minimal schema, create some data and put a script in there that triggers the error and then put it on GitHub? That would be the most amazing way for us to reproduce this @StErMi.

**Comment by raiomarco** [comment]
Happened to me, i will try to analyze and send what i find here

for instance, my schema is:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Tactic {
  id   String @id
  name String

  techniques Technique[]
}

model Technique {
  id   String @id
  name String

  tactics Tactic[]

  detections Detection[]
}

model Detection {
  id    String  @id
  name  String
  score String?

  techniques Technique[]
}
```

and my query is:

```js
  const data = await prisma.tactic.findMany({
    include: {
      techniques: {
        include: {
          detections: {
            where: { score: { not: null } }
          }
        }
      }
    }
  });
```

i can send my sqlite file if wanted, but i have this to analyse data from database:

```js
async function analyser() {
  const tacticCount = await prisma.tactic.count();
  const techniqueCount = await prisma.technique.count();
  const detectionCount = await prisma.detection.count();

  console.log(`tacticCount: ${tacticCount}`);
  console.log(`techniqueCount: ${techniqueCount}`);
  console.log(`detectionCount: ${detectionCount}`);

  const techniqueMultiTactic = (await prisma.technique.findMany({ include: { tactics: true } })).filter((technique) => technique.tactics.length > 1);

  console.log(`techniqueMultiTactic: ${techniqueMultiTactic.length}`);

  const detectionMultiTechnique = (await prisma.technique.findMany({ include: { tactics: true } })).filter((technique) => technique.tactics.length > 1);

  console.log(`detectionMultiTechnique: ${detectionMultiTechnique.length}`);

  const detectionNoScoreCount = await prisma.detection.count({ where: { score: null } });

  console.log(`detectionNoScoreCount: ${detectionNoScoreCount}`);
}
```

which resulted in:

```
tacticCount: 14
techniqueCount: 188
detectionCount: 8951
techniqueMultiTactic: 24
detectionMultiTechnique: 2433
detectionNoScoreCount: 6840
```

i hope this can be usefull somehow :)

**Comment by janpio** [comment]
Please send that file to schemas@prisma.io - then we can reproduce ourselves. Thanks.

**Comment by millsp** [comment]
I have tried many things on `3.10.0` and on latest `4.6.0` but couldn't reproduce this issue.

**Comment by raiomarco** [comment]
Using 4.6.1 and tried to see what could happen, got this

```
C:\Users\redacted\Downloads\redacted\node_modules\@prisma\client\runtime\index.js:34310
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^

PrismaClientKnownRequestError:
Invalid `prisma.tactic.findMany()` invocation in
C:\Users\redacted\Downloads\redacted\experiment.cjs:335:36

  334 async function teste() {
→ 335   const data = await prisma.tactic.findMany(
Query parameter limit exceeded error: Parameter limits for this database provider require this query to be split into multiple queries, but the negation filters used prevent the query from being split. Please reduce the used values in the query..
    at RequestHandler.handleRequestError (C:\Users\redacted\Downloads\redacted\node_modules\@prisma\client\runtime\index.js:34310:13)
    at RequestHandler.request (C:\Users\redacted\Downloads\redacted\node_modules\@prisma\client\runtime\index.js:34293:12)
    at async PrismaClient._request (C:\Users\redacted\Downloads\redacted\node_modules\@prisma\client\runtime\index.js:35273:16)
    at async teste (C:\Users\redacted\Downloads\redacted\experiment.cjs:335:16) {
  code: 'P2029',
  clientVersion: '4.6.1',
  meta: {
    message: 'Parameter limits for this database provider require this query to be split into multiple queries, but the negation filters used prevent the query from being split. Please reduce the used values in the query.'
  }
}
```

**Comment by mhesham93** [comment]
I started getting this error too, I have a date range in my query and if I tried to get over a month worth of data, I'll get this error. otherwise it runs just fine.

**Comment by ryancwalsh** [comment]
I'm getting this error, too.

```
error Error [PrismaClientKnownRequestError]:
Invalid `prisma.image.findMany()` invocation:


Query parameter limit exceeded error: Parameter limits for this database provider require this query to be split into multiple queries, but the negation filters used prevent the query from being split. Please reduce the used values in the query..
    at vn.handleRequestError (E:\project\node_modules\@prisma\client\runtime\library.js:123:67
```


"prisma": "^5.2.0",
"@prisma/client": "^5.2.0",

My app is a tool that runs locally and greps a folder to find all files in all its nested subfolders, then add them to a Postgresql table.

On PC 1, it runs fine when inserting and reading 30,605 files.

On PC 2, it finds 36,582 files and inserts them into the DB but then throws this error when trying to read them via findMany.

**Comment by ryancwalsh** [comment]
Here is my workaround for now:

```ts
export async function getAllowImagesConsideringDatabase(imagePaths: string[]): Promise<Image[]> {
  // https://github.com/prisma/prisma/issues/12499#issuecomment-1720310932
  const baseWhere = {
    OR: [
      {
        flag: {
          not: {
            equals: Flag.BANNED,
          },
        },
      },
      {
        flag: {
          equals: null,
        },
      },
    ],
  };
  const allowedImagesArray = await prisma.image.findMany({
    orderBy: {
      path: 'asc',
    },
    where: baseWhere,
  });
  console.log(`Found ${allowedImagesArray.length.toLocaleString()} allowed images in DB.`);
  const imagesThatAreAllowedAndStillExist = allowedImagesArray.filter((image) => {
    return imagePaths.includes(image.path);
  });
  console.log(`${imagesThatAreAllowedAndStillExist.length.toLocaleString()} still exist and are allowed.`);

  return imagesThatAreAllowedAndStillExist;
}
```

**Comment by tncn1122** [comment]
I have the same issue, my database has 500k+ record and my query has 100k+ items in `not in` array, i use Prisma 4.16.2.

**Comment by pyh0414** [comment]
How is the issue progressing?

**Comment by millsp** [comment]
@pyh0414 we had spent some time trying to reproduce the issue without success. We'd appreciate if you could help us with a self-contained reproduction. Thanks :)

**Comment by dwojtyca** [comment]
@millsp it's easy to reproduce, just put more than `32767` items in `notIn`, that should trigger this error

**Comment by sneko** [comment]
@millsp to reproduce:
```ts
        await tx.xxxxx.deleteMany({
          where: {
            id: {
              notIn: new Array(35831).fill('13422339-278f-400d-9b25-5399e9fe6232'),
            },
          },
        });
```

But I guess the message is explicit enough, as for command-lines and so on, there is always a "string" limit.
