### ISSUE TITLE
“may contain” Composite with empty filter set has a runtime error

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#12518]
### Bug description

From our QA session,

```ts
const results = await prisma.product.findMany({
  where: {
    photo: {},
  },
})
```

is valid in Typescript, but produces the following runtime error:

```
→  76 const results = await prisma.product.findMany({
        where: {
          photo: {}
          ~~~~~
        }
      })

Argument photo: Got invalid value {} on prisma.findManyProduct. Provided Json, expected PhotoNullableCompositeFilter or PhotoObjectEqualityInput or Null.


    at Object.validate (/Users/m/dev/src/github.com/prisma/mongodb-qa-template/node_modules/@prisma/client/runtime/index.js:38614:20)
    at PrismaClient._executeRequest (/Users/m/dev/src/github.com/prisma/mongodb-qa-template/node_modules/@prisma/client/runtime/index.js:40699:17)
    at consumer (/Users/m/dev/src/github.com/prisma/mongodb-qa-template/node_modules/@prisma/client/runtime/index.js:40643:23)
    at /Users/m/dev/src/github.com/prisma/mongodb-qa-template/node_modules/@prisma/client/runtime/index.js:40647:76
    at runInChildSpan (/Users/m/dev/src/github.com/prisma/mongodb-qa-template/node_modules/@prisma/client/runtime/index.js:39891:12)
    at /Users/m/dev/src/github.com/prisma/mongodb-qa-template/node_modules/@prisma/client/runtime/index.js:40647:20
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at PrismaClient._request (/Users/m/dev/src/github.com/prisma/mongodb-qa-template/node_modules/@prisma/client/runtime/index.js:40646:86)
    at /Users/m/dev/src/github.com/prisma/mongodb-qa-template/node_modules/@prisma/client/runtime/index.js:37277:25
    at _callback (/Users/m/dev/src/github.com/prisma/mongodb-qa-template/node_modules/@prisma/client/runtime/index.js:37041:52) {
  clientVersion: '3.12.0-integration-chore-composite-filter-rewrite.1'
}
```

### How to reproduce

See above

### Expected behavior

Should probably show a compiler error.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Product {
  id     String  @id @default(auto()) @map("_id") @db.ObjectId
  name   String  @unique
  photos Photo[]
}

type Photo {
  height Int    @default(200)
  width  Int    @default(100)
  url    String
}
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma                  : 3.11.1-dev.2
@prisma/client          : 3.11.1-dev.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : b371888aaf8f51357c7457d836b86d12da91658b
Studio                  : 0.458.0
Preview Features        : mongoDb, referentialIntegrity
```

**Comment by millsp** [comment]
(Broader problem, not limited to mongo)

Next steps:
* Utilize "at least one" require fields hints in the DMMF
