### ISSUE TITLE
MongoDB: Find distinct on a Decimal/Float panics ConversionFailure("Float(BigDecimal(\"59.55\"))", "Decimal")'

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#12517]
### Bug description

When running distinct on a Decimal type in MongoDB, 

```
const results = await prisma.product.findMany({
  distinct: "price",
})
```

You get teh following Rust panic

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConversionFailure("Float(BigDecimal(\"59.55\"))", "Decimal")', query-engine/core/src/interpreter/query_interpreters/inmemory_record_processor.rs:120:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PrismaClientUnknownRequestError: 
Invalid `prisma.product.findMany()` invocation in
/Users/m/dev/src/github.com/prisma/mongodb-qa-template/mattm/index.ts:80:40

   77 // - [ ]  **[**`take`**]**
   78 // - [x]  **[**`where`**]**
   79 
→  80 const results = await prisma.product.findMany(
  called `Result::unwrap()` on an `Err` value: ConversionFailure("Float(BigDecimal(\"59.55\"))", "Decimal")
    at Object.request (/Users/m/dev/src/github.com/prisma/mongodb-qa-template/node_modules/@prisma/client/runtime/index.js:39822:15)
    at PrismaClient._request (/Users/m/dev/src/github.com/prisma/mongodb-qa-template/node_modules/@prisma/client/runtime/index.js:40646:18) {
  clientVersion: '3.12.0-dev.12'
}
```

### How to reproduce

_(Simplified from a larger example, let me know if you need more info)_

Given the following schema:

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb"]
}

datasource db {
  provider             = "mongodb"
  url                  = env("DATABASE_URL")
}

model Product {
  id    String  @id @default(auto()) @map("_id") @db.ObjectId
  price Decimal
}
```

And queries:

```
await prisma.product.createMany({
  data: [
    { price: 59.55 },
    { price: 59.55 }
  ]
})
```

Then try running distinct

```
const results = await prisma.product.findMany({
  distinct: "price",
})
```

### Expected behavior

It should show one product

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma                  : 3.11.1-dev.2
@prisma/client          : 3.11.1-dev.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : b371888aaf8f51357c7457d836b86d12da91658b
Studio                  : 0.458.0
Preview Features        : mongoDb, referentialIntegrity
```

**Comment by Weakky** [comment]
Update:
- Cannot reproduce with float, bigint, string, int...
- Since we're removing `Decimal` support, this doesn't seem to be an issue anymore
