### ISSUE TITLE
Error: Raw query failed. Code: `42P18`. Message: `db error: ERROR: could not determine data type of parameter $1`

### ISSUE THREAD

**Issue by kasir-barati** [prisma/prisma#12531]
### Bug description

I tried to run a simple raw query which I tested it in the PSQL before using it in the Prisma. By I got this error:
```cmd
  prisma:client:libraryEngine sending request, this.libraryStarted: true +9s
  prisma:client prisma.$executeRaw(
  prisma:client                 SELECT  *, POSITION(
  prisma:client                     LOWER('$1') 
  prisma:client                     IN 
  prisma:client                     LOWER($2)
  prisma:client                 ) AS indexOfTheSearchedName FROM cities
  prisma:client                 WHERE $3 
  prisma:client                     ILIKE '%$4%'
  prisma:client                 ORDER BY 
  prisma:client                     indexOfTheSearchedName ASC, 
  prisma:client                     $5 ASC;
  prisma:client             , ["لن","nameFa","nameFa","لن","domesticPriority"]) +26ms
  prisma:client Prisma Client call: +10ms
  prisma:client Prisma Client call: +2ms
  prisma:client prisma.executeRaw({
  prisma:client   query: '\n                SELECT  *, POSITION(\n                    LOWER(\'$1\') \n                    IN \n                    LOWER($2)\n                ) AS indexOfTheSearchedName FROM cities\n                WHERE $3 \n                    ILIKE \'%$4%\'\n                ORDER BY \n                    indexOfTheSearchedName ASC, \n                    $5 ASC;\n            ',
  prisma:client   parameters: {
  prisma:client     values: '["لن","nameFa","nameFa","لن","domesticPriority"]',
  prisma:client     __prismaRawParamaters__: true
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +7ms
  prisma:client mutation {
  prisma:client   executeRaw(
  prisma:client     query: "\n                SELECT  *, POSITION(\n                    LOWER('$1') \n                    IN \n                    LOWER($2)\n                ) AS indexOfTheSearchedName FROM cities\n                WHERE $3 \n                    ILIKE '%$4%'\n                ORDER BY \n                    indexOfTheSearchedName ASC, \n                    $5 ASC;\n            "
  prisma:client     parameters: "[\"لن\",\"nameFa\",\"nameFa\",\"لن\",\"domesticPriority\"]"
  prisma:client   )
  prisma:client }
  prisma:client  +2ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +56ms
  prisma:client:fetcher Error: Raw query failed. Code: `42P18`. Message: `db error: ERROR: could not determine data type of parameter $1`
  prisma:client:fetcher     at prismaGraphQLToJSError (/media/user/2DE701966937BBDE/Projects/spad.co/flyver_backend/node_modules/@prisma/client/runtime/index.js:35992:12)
  prisma:client:fetcher     at Object.request (/media/user/2DE701966937BBDE/Projects/spad.co/flyver_backend/node_modules/@prisma/client/runtime/index.js:36358:17)
  prisma:client:fetcher     at cb (/media/user/2DE701966937BBDE/Projects/spad.co/flyver_backend/node_modules/@prisma/client/runtime/index.js:38673:26)
  prisma:client:fetcher     at Proxy._request (/media/user/2DE701966937BBDE/Projects/spad.co/flyver_backend/node_modules/@prisma/client/runtime/index.js:40853:18)
  prisma:client:fetcher     at CityService.findAll (/media/user/2DE701966937BBDE/Projects/spad.co/flyver_backend/src/city/service/city.service.ts:58:22)
  prisma:client:fetcher     at CityController.findAll (/media/user/2DE701966937BBDE/Projects/spad.co/flyver_backend/src/city/city.controller.ts:36:16) +0ms
```
# Important Note: 
- The same query return result when I execute it in the `psql`.
- I tried `$queryRawUnsafe`, `$queryRaw`, `$executeRaw`, and `$queryRaw` but none off them work
- I read this issues: [753](https://github.com/prisma/prisma-client-js/issues/753), and [2847](https://github.com/prisma/prisma/issues/2847)
- I also read [doc](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access) too.

### How to reproduce

You can pull and run this dockerized Prisma project. In this way we have same environment, therefore it is almost guaranteed to get the same error: https://github.com/kasir-barati/my-prisma-bugs

All the necessary information is in `README.md`.

### Expected behavior

My raw Query executed and return `cities`.

### Prisma information

In the repo

### Environment & setup

- OS: Alpine linux 3.15
- Database: Postgres:13
- Node.js version: 16.14.0

### Prisma Version

```
prisma                  : 3.11.1
@prisma/client          : 3.11.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 1a2506facaf1a4727b7c26850735e88ec779dee9
Studio                  : 0.458.0
```

**Comment by Weakky** [comment]
Hey, `queryRawUnsafe` should solve your problem but your reproduction produces a broken SQL query. You're referring to column & tables with the prisma schema names instead of the database names.

- `nameEn` should be `official_english_name`
- `nameFa` should be `name_fa`
- `domesticPriority` should be `domestic_priority`

The reason you cannot use `queryRaw` the way you intend it to is because you're trying to dynamically refer to columns which is not possible with prepared statement. `lowerFieldName` and `orderByFieldName` _must_ be "hardcoded" in your query.

Here is a working version of your reproduction:

```ts
import { PrismaClient } from "@prisma/client";

// A `main` function so that you can use async/await
async function main() {
  const prisma = new PrismaClient();

  const filters = {
    query: "Ch",
    // country: ''
  };
  const isEnglish = /[a-zA-Z]/.test(filters.query[0]);
  const lowerFieldName = isEnglish ? "official_english_name" : "name_fa";
  const orderByFieldName = isEnglish
    ? "international_priority"
    : "domestic_priority";

  const unsafeQuery = `
  SELECT  *, POSITION(
      LOWER('${"Ch"}')
      IN
      LOWER(${lowerFieldName})
  ) AS indexOfTheSearchedName FROM cities
  WHERE ${lowerFieldName}
      ILIKE '${"%Ch%"}'
  ORDER BY
      indexOfTheSearchedName ASC,
      ${orderByFieldName} ASC;
`;


  const unsafeRes = await prisma.$queryRawUnsafe(unsafeQuery);

  console.log({ unsafeRes })

  await prisma.$disconnect();
}

main().catch(console.error);
```

**Comment by kasir-barati** [comment]
Thanks :white_flower: @Weakky I got it. I messed up. :sweat_smile:
