### ISSUE TITLE
Prisma doesn't work with Electron-Forge/Webpack

### ISSUE THREAD

**Issue by WalissonPires** [prisma/prisma#12627]
### Bug description

Prisma fails to run when used alongside webpack. Project created using electron-forge.

In this repository you can see the problem:  https://github.com/WalissonPires/electron-forge-prisma-error
And in this branch my temporary fix: https://github.com/WalissonPires/electron-forge-prisma-error/tree/fixed

The test with the prisma is executed at the end of the *src/index.ts* file.

When running the project with ```npm start``` the following error occurs:

```js
Error: ENOENT: no such file or directory, open 'C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\schema.prisma'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at Object.readFileSync (node:fs:453:35)
    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at new LibraryEngine (C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\index.js:35648:41)
    at PrismaClient.getEngine (C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\index.js:40447:16)
    at new PrismaClient (C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\index.js:40422:29)
    at C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\index.js:45610:14
    at C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\index.js:45615:3
    at Object.<anonymous> (C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\index.js:45618:12)
```

The **schema.prisma** is copied by webpack to *.webpack/main/native_modules/schema.prisma* but prism tries to use *.webpack/main/schema.prisma*.

Prisma uses *.webpack/main/schema.prisma* because of this line modifies by webpack when bundling:

original line:
```js
// @filename: node_modules/.prisma/client/index.js
const regularDirname = hasDirname && fs.existsSync(path.join(__dirname, 'schema.prisma')) && __dirname
```
Line generated by webpack:
```js
// @filename: .webpack/main/index.js
const regularDirname = hasDirname && fs.existsSync(__webpack_require__.ab + "schema.prisma") && __dirname
```

And when **__webpack_require__.ab** is the path to *.webpack/main/native_modules* folder, **__dirname** is the path to *.webpack/main*. Therefore, checking for schema existence is done in the correct location (returning true) but the path used is wrong.

Changing the lines below the source of prisma client, generated by prisma fixes the problem:

```js
// @filename: node_moduels/.prisma/client/index.js
const schemaFilename  = hasDirname && path.join(__dirname, 'schema.prisma');
const regularDirname = hasDirname && fs.existsSync(schemaFilename) && path.resolve(schemaFilename, '..');
```

Webpack generates:
```js
// @filename: .webpack/main/index.js
const schemaFilename  = hasDirname && __webpack_require__.ab + "schema.prisma";
const regularDirname = hasDirname && fs.existsSync(schemaFilename) && path.resolve(schemaFilename, '..');
```

However the prisma generates a new error:

```js
PrismaClientInitializationError:
Invalid `prisma.user.findFirst()` invocation:


  Query engine library for current platform "windows" could not be found.
You incorrectly pinned it to windows

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\query_engine-windows.dll.node")

Searched Locations:

  C:\Users\<user>\Desktop\.prisma\client
  C:\Users\<user>\Desktop\electron-forge-prisma\node_modules\@prisma\client
  C:\Users\<user>\Desktop\electron-forge-prisma\.webpack
  C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\native_modules
  C:\Users\<user>\Desktop\electron-forge-prisma\prisma
  /tmp/prisma-engines
  C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\native_modules


To solve this problem, add the platform "windows" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
    at Object.request (C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\index.js:40005:15)
    at async PrismaClient._request (C:\Users\<user>\Desktop\electron-forge-prisma\.webpack\main\index.js:40828:18) {
  clientVersion: '3.11.1',
  errorCode: undefined
}
```

This problem happens because webpack copies the "dll" to *.webpack/main/native_modules/client/query_engine-windows.dll.node*. The locations where the prism is looking are:

- 'C:\\Users\\<user>\\Desktop\\.prisma\\client'
- 'C:\\Users\\<user>\\Desktop\\electron-forge-prisma\\node_modules\\@prisma\\client'
- 'C:\\Users\\<user>\\Desktop\\electron-forge-prisma\\.webpack'
- 'C:\\Users\\<user>\\Desktop\\electron-forge-prisma\\.webpack\\main\\native_modules'
- 'C:\\Users\\<user>\\Desktop\\electron-forge-prisma\\prisma'
- '/tmp/prisma-engines'
- 'C:\\Users\\<user>\\Desktop\\electron-forge-prisma\\.webpack\\main\\native_modules

Fix this problem by setting the **PRSMA_QUERY_ENGINE_LIBRARY ** environment variable before instance prisma:

```js
// @filename: src/index.ts
process.env.PRISMA_QUERY_ENGINE_LIBRARY = path.join(__dirname, 'native_modules', 'client', 'query_engine-windows.dll.node');

const prisma = new Prisma();
//... rest code
```

With that I was able to use the prisma.

### How to reproduce

1. ```git clone https://github.com/WalissonPires/electron-forge-prisma-error```
2. ```cd electron-forge-prisma-error```
3. ```npm install```
4. ```npm start```
5. See error

### Expected behavior

Expected the query to run.

### Environment & setup

- OS: Windows 10
- Database: SQLite
- Node.js version: v16.9.1

### Prisma Version

```
prisma                  : 3.11.1
@prisma/client          : 3.11.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 1a2506facaf1a4727b7c26850735e88ec779dee9 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 1a2506facaf1a4727b7c26850735e88ec779dee9
Studio                  : 0.458.0
```

**Comment by WalissonPires** [comment]
I can fix the problem of not finding **query_engine-windows.dll.node** by changing the following code:

```diff
// @filename:  node_modules/@prisma/client/runtime/index.js
// @function: resolveEnginePath

 if (this.config.dirname) {
       searchLocations.push(this.config.dirname);
+      searchLocations.push(import_path3.default.join(this.config.dirname, 'client'));
  }
```
This works because **this.dirname** equals *.webpack/main/native_modules*. That way I don't need to use the PRISMA_QUERY_ENGINE_LIBRARY environment variable.

If I could inform the schema path as I do with the query engine it would be good.

**Comment by lemonpole** [comment]
@WalissonPires  As this is a few months after your initial post, I am unsure if you've solved it yet, but I would like to share my solution which works for me in both development and production.

- Electron Forge: `6.0.0-beta.66`
- Electron: `20.1.3`
- Prisma: `4.3.1`
- SQLite3: `5.0.2`

This is my Electron Forge `packagerConfig` in `package.json`:

```diff
"packagerConfig": {
  "appBundleId": "baz.foo",
  "appCopyright": "Copyright © 2022 Foo Bar",
+ "extraResource": [
+   "./node_modules/.prisma",
+   "./prisma/save_0.db"
+ ],
  "icon": "./assets/icon"
},
```

This is my `prisma/schema.prisma` file:

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:save_0.db"
}
```

Lastly, the bit that fixed everything for me was _excluding_ the `.prisma` directory in the `webpack/webpack.rules.js` configuration:

```diff
diff --git a/webpack/webpack.rules.js b/webpack/webpack.rules.js
index 174b320..96aa10a 100644
--- a/webpack/webpack.rules.js
+++ b/webpack/webpack.rules.js
@@ -8,6 +8,7 @@ module.exports = [
   },
   {
     test: /\.(m?js|node)$/,
+    exclude: /\.prisma/,
     parser: { amd: false },
     use: {
       loader: '@vercel/webpack-asset-relocator-loader',
```

After creating the production bundle, my resources folder looks like this:

```bash
$ ls -la out/alpha/app-win32-x64/resources/
total 28
drwxr-xr-x 1 Foo Bar 197121     0 Sep 15 10:59 .
drwxr-xr-x 1 Foo Bar 197121     0 Sep 15 10:59 ..
drwxr-xr-x 1 Foo Bar 197121     0 Sep 15 10:59 .prisma
drwxr-xr-x 1 Foo Bar 197121     0 Sep 15 10:59 app
-rw-r--r-- 1 Foo Bar 197121 24576 Sep 15 10:58 save_0.db

$ ls -la out/alpha/app-win32-x64/resources/.prisma/client
total 30019
drwxr-xr-x 1 Foo Bar 197121        0 Sep 15 10:59 .
drwxr-xr-x 1 Foo Bar 197121        0 Sep 15 10:59 ..
-rw-r--r-- 1 Foo Bar 197121     1149 Sep 14 17:05 edge.d.ts
-rw-r--r-- 1 Foo Bar 197121      335 Sep 14 17:05 edge.js
-rw-r--r-- 1 Foo Bar 197121    54712 Sep 15 10:58 index.d.ts
-rw-r--r-- 1 Foo Bar 197121     5488 Sep 15 10:58 index.js
-rw-r--r-- 1 Foo Bar 197121     3836 Sep 15 10:58 index-browser.js
-rw-r--r-- 1 Foo Bar 197121      110 Sep 15 10:58 package.json
-rwxr-xr-x 1 Foo Bar 197121 30658560 Sep 14 17:05 query_engine-windows.dll.node
-rw-r--r-- 1 Foo Bar 197121      319 Sep 15 10:58 schema.prisma
```

**Comment by WalissonPires** [comment]
@lemonpole Thanks for sharing a solution. It works perfectly. :3

**Comment by luigi-raynel-dev** [comment]
For those using webpack, a simpler solution is to add in your package.json on `build`:
```json
"extraResources": [
    {
      "from": "./node_modules/.prisma",
      "to": "../.prisma/"
    }
  ]
```

Remember to run `prisma generate` first.
