### ISSUE TITLE
P1011 error when trying to connect to RDS Postgres instance over TLS

### ISSUE THREAD

**Issue by jimpala** [prisma/prisma#12645]
### Bug description

I'm getting the following error for trying to connect to an AWS RDS PostgreSQL 14 instance over TLS. The RDS instance has its `rds.force_ssl` parameter set to 1.

```
Error: P1011: Error opening a TLS connection: One or more parameters passed to a function were not valid.
```

when trying to run `prisma db push` (or any command that touches the database).

When I try to connect to the database using an IDE / GUI client (DataGrip), it connects fine (though the TLS mode is set to 'Verify CA', not 'require'.

Also when I **don't** use the URL's available SSL parameters and just try to connect without them (with the RDS cert added to my Mac's Keychain / trust store), connection works fine.

### How to reproduce

1. Set up an RDS Postgres 14 instance with security group allowing all inbound traffic into port 5432. Set the RDS parameter `rds.force_ssl` to 1. Create an initial db.
2. Download RDS certificate bundle for all regions from https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem and move to `./prisma` directory.
3. Change `DATABASE_URL` env variable to `postgresql://user:password@endpoint:5432/db?schema=public&sslmode=require&sslcert=rds-global-bundle.pem`
4. Create a valid schema
5. Run `prisma db push`

Same error also occurs if a client identity is also created as per this page of the docs: https://www.prisma.io/docs/concepts/database-connectors/postgresql. However, RDS doesn't require (or allow) you to use a client certificate when connecting to RDS afaik.

### Expected behavior

```
🚀  Your database is now in sync with your schema. Done in 961ms
```

Successful connection and syncing with the DB instance.

### Prisma information

Database URL is:
```postgresql://user:password@endpoint:5432/prisma?schema=public&sslmode=require&sslcert=rds-global-bundle.pem```

None of the characters in the URL required escaping when encountering this error.

### Environment & setup

- OS: MacOS
- Database: PostgreSQL 14 (via RDS)
- Node.js version: 16.2

### Prisma Version

```
3.11.1
```

**Comment by jamie-unmind** [comment]
Getting the same issue. Any advice on how to fix this?

**Comment by hmbanan666** [comment]
The same problem.

OS: MacOS
Database: PostgreSQL 14
Node.js version: 16.16

**Comment by JefferyHus** [comment]
Same issue here, I don't want to regret using Prisma again 😮‍💨

**Comment by Gilaad-Elstein** [comment]
Seeing the same issue here:
OS: MacOS
Database: PostgreSQL 14
Node.js version: v18.17.1
prisma: 4.7.1

```
process.env.DATABASE_URL = `postgres://${backendUserName}:${encodedToken}@${process.env.DB_HOST}:${process.env.DB_PORT}/<DB NAME>?sslmode=require&sslcert=global-bundle.pem`
```

```
Error: Error opening a TLS connection: One or more parameters passed to a function were not valid.
    at startFn (/Users/gilaadelstein/VizoDev/vizolab/backend/node_modules/@prisma/client/runtime/index.js:27688:17)
    at Proxy.onModuleInit (/Users/gilaadelstein/VizoDev/vizolab/backend/src/prisma/prisma.service.ts:93:9)
    at async Promise.all (index 0)
    at callModuleInitHook (/Users/gilaadelstein/VizoDev/vizolab/backend/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
    at NestApplicationContext.callInitHook (/Users/gilaadelstein/VizoDev/vizolab/backend/node_modules/@nestjs/core/nest-application-context.js:210:13)
    at NestApplicationContext.init (/Users/gilaadelstein/VizoDev/vizolab/backend/node_modules/@nestjs/core/nest-application-context.js:94:9)
    at bootstrap (/Users/gilaadelstein/VizoDev/vizolab/backend/src/main.ts:20:15)
    at handler (/Users/gilaadelstein/VizoDev/vizolab/backend/src/main.ts:27:17)
```

**Comment by janpio** [comment]
@Gilaad-Elstein So you are only getting this problem when running locally on MacOS?

**Comment by Gilaad-Elstein** [comment]
@janpio

Correct. 

I have ran this code:
* Locally on my macbook - resulting in the above error.
* Deployed as lambda function running a docker image based on Amazon Linux 2 - Success.

**Comment by JefferyHus** [comment]
@janpio it happened to me un aws linux as well

**Comment by robblovell** [comment]
I had this problem and figured out what was going on in my situation: I am running code that would normally be deployed to a lambda locally for development purposes and using Prisma to connect to an AWS RDS database through a tunnel using a bastion server. The bastion server tunnel works fine in utilities like PG Admin or NOSQLBooster and I can connect without issue.

The code connects and runs on a lambda when deployed, but when running locally was giving the error `PrismaClientInitializationError: Error opening a TLS connection: One or more parameters passed to a function were not valid.`. 

What I found was that I did not need the flag `sslcert=bundle.pem` parameter (I think because the bastion server was already taking care of this part of the connection). Once I removed the `sslcert` parameter, the connection no longer gave this error and connected. The parameters I ended up using for Prisma in my case are: `schema=app&sslmode=prefer&connection_limit=1`. 

Keep in mind that this is for development purposes only.
