### ISSUE TITLE
Confusing error message re: SSL client cert password invalid when deployed to Vercel (i.e. AWS Lambda)

### ISSUE THREAD

**Issue by andyjy** [prisma/prisma#12661]
### Bug description

I finally figured out all the steps required[^1] to connect using client + server SSL certificates (to Postgres) when deployed to Vercel (i.e. AWS Lambda serverless functions).

I got held up for ages by a cryptic error when deploying to Vercel, that took me forever to figure out - eventually realising I wasn't passing in the client PKCS12 file password correctly to the Prisma `sslpassword` param in the connection string in the Vercel production environment.

## Observed behaviour (cryptic error)

When deployed to Vercel the error in case of incorrect PKCS12 cert password is:

```
PrismaClientInitializationError: Error opening a TLS connection: error:0200100D:system library:fopen:Permission denied:crypto/bio/bss_file.c:69:fopen('/root/build/target/release/build/openssl-sys-cacd48fffbb900ae/out/openssl-build/install/ssl/openssl.cnf','rb'), error:2006D002:BIO routines:BIO_new_file:system lib:crypto/bio/bss_file.c:78:, error:0E078002:configuration file routines:def_load:system lib:crypto/conf/conf_def.c:170:, error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure:crypto/pkcs12/p12_kiss.c:70:
    at Object.request (/var/task/node_modules/@prisma/client/runtime/index.js:39824:15)
```

.. which although in hindsight I now realise does reference the `PKCS12:mac verify failure` part buried within, led me astray with the confusing error re: Permission denied attempting fopen of opensl.cnf.

## Expected behaviour (observed locally)

Expected behaviour would be to receive in the Vercel production environment the much more straightforward and pleasing error message that Prisma outputs in the case of invalid cert password in local development (and NextJS build/start production environment run locally): 

```
PrismaClientInitializationError: Error opening a TLS connection: MAC verification failed during PKCS12 import (wrong password?)
    at Object.request (/Users/andy/repos/prisma-rest-nextjs-api-routes/node_modules/@prisma/client/runtime/index.js:39824:15)
```

[^1]: namely: 1) pass SSL certificates as files rather than env vars (due to Vercel/AWS Lambda's 4kb env limit + Prisma's requirement to receive as files); 2) determine how to pass correct paths to cert files given Prisma expects relative to prisma folder but NextJS compiles scripts (I ended up providing absolute paths hardcoded to current AWS Lambda filesystem structure);  3) figure how to get cert files into filesystem of serverless function - I used the approach of storing encrypted certs within my repo and decrypting them to /tmp on function load, an alternative approach would be loading from a 3rd party hosted secrets service; 3)b) storing certs in the repo requires a hack to `fs.access()` the cert files from javascript to force Vercel to include them within the trace of files bundled for the serverless function...  in short, got there but not without pain 😞 

### How to reproduce

Deploy to Vercel (i.e. AWS Lambda) using a client SSL cert PKCS12 file and incorrect password.

Reproduction repo: [https://github.com/andyjy/prisma-ssl-vercel-error](https://github.com/andyjy/prisma-ssl-vercel-error) (can be deployed directly to a free Vercel account).

### Prisma information

Reproduction repo: [https://github.com/andyjy/prisma-ssl-vercel-error](https://github.com/andyjy/prisma-ssl-vercel-error) 

### Environment & setup

- OS: Locally: MacOS. Deployed: Vercel/AWS Lambda.
- Database: Postgres
- Node.js version: 14 (i.e. most recent version supported by AWS Lambda)

### Prisma Version

```
3.11.1
```

**Comment by janpio** [comment]
(Unrelated, but do you want to do a writeup about your tiny footnote? Just create it as an issue here and we will see if we can add that to our docs somewhere, somehow [probably not instantly as we are missing the location for it, so it would live in the issue first for people to find via Google])

**Comment by andyjy** [comment]
> Unrelated, but do you want to do a writeup about your tiny footnote?

Gladly, I'll try find the time ASAP. Now I've Made-it-Work I need to [Make-It-Work-Better](https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast) (try remove hardcoded absolute paths for AWS Lambda file locations, etc).

For anyone looking sooner, the [reproduction repo](https://github.com/andyjy/prisma-ssl-vercel-error) example demonstrates ~most of it (in [lib/prisma.ts](https://github.com/andyjy/prisma-ssl-vercel-error/blob/main/lib/prisma.ts)) - with the exception this repo contains the (example!) raw unencrypted client certificate. 

For encrypting/decrypting the client certificate I created a script heavily inspired by [this prior comment](https://github.com/prisma/prisma/issues/1673#issuecomment-647107891) on #1673

Related: #2817 #12546
