### ISSUE TITLE
MongoDB: Coerce undefined composites to @default value when read

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#12665]
## Problem

In 3.11.1, we support coercing undefined fields to the `@default` value on model fields but not composite fields.

For example,

```prisma
model Product {
  id     String  @id @default(auto()) @map("_id") @db.ObjectId
  name   String  @unique
  photos Photo[]
}

type Photo {
  height Int    @default(200)
  width  Int    @default(100)
  url    String
}
```

And run the following to create a product:

```ts
const product = await prisma.product.create({
    data: {
      name: "Forest Runners",
      photos: [{ height: 100, url: "3.jpg" }],
    },
  })
```

Then adjust the schema and regenerate:

```diff
model Product {
  id     String  @id @default(auto()) @map("_id") @db.ObjectId
  name   String  @unique
+  color  String  @default("Blue")
  photos Photo[]
}
```

And run a find:

```ts
console.dir(await prisma.product.findMany({}), { depth: Infinity })
```

To get:

```
[
  {
    photos: [ { height: 100, width: 100, url: '3.jpg' } ],
    id: '624b57b3d1ab25f3fec39e72',
    name: 'Forest Runners',
    color: 'Blue'
  }
]
```

However, if you add a required field with a default to a composite:

```diff
type Photo {
  height Int    @default(200)
  width  Int    @default(100)
  url    String
+ filter String @default("none")
}
```

And regenerate, then try the find again:

```
console.dir(await prisma.product.findMany({}), { depth: Infinity })
```

You get an error:

```
Invalid `prisma.product.findMany()` invocation in
/Users/m/dev/src/github.com/prisma/mongodb-composites/index.ts:15:36

  12 // await prisma.product.deleteMany()
  13 
  14 // console.log(await prisma.order.findMany({}))
→ 15 console.dir(await prisma.product.findMany(
  Error converting field "filter" of expected non-nullable type "String", found incompatible value of "null".
    at Object.request (/Users/m/dev/src/github.com/prisma/mongodb-composites/node_modules/@prisma/client/runtime/index.js:39818:15)
    at PrismaClient._request (/Users/m/dev/src/github.com/prisma/mongodb-composites/node_modules/@prisma/client/runtime/index.js:40649:18) {
  code: 'P2032',
  clientVersion: '3.11.1',
  meta: { field: 'filter', expected_type: 'String', found: 'null' }
}
```

## Suggested solution

It'd be nice to align these two and allow coercing undefineds to the default for required defaults on composites. I don't think this would be a breaking change unless for some reason you were relying on this error (since the time we introduced composites)

**Comment by dpetrick** [comment]
Internal spec: https://www.notion.so/prismaio/Composite-read-default-on-undefined-1688123bac0e4d6db8da25241e0cf4d8
