### ISSUE TITLE
`Invalid value undefined for datasource "db" provided to PrismaClient constructor.` error message looks weird

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12683]
This code
```
const prismaLibrary = new PrismaClientLibrary({
  log: ['query', 'info', 'warn', 'error'],
  datasources: {
    db: {
      url: process.env.sdfsdfsd
    }
  }
})
```
 causes this error message:
```
C:\Users\Jan\Documents\throwaway\3.12.0_simple>npx ts-node scripts.ts
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\3.12.0_simple\.env +0ms
C:\Users\Jan\Documents\throwaway\3.12.0_simple\prisma\library\runtime\index.js:45749
            throw new PrismaClientConstructorValidationError(`Invalid value ${JSON.stringify(value1)} for datasource "${key}" provided to PrismaClient constructor.
                  ^
PrismaClientConstructorValidationError: Invalid value undefined for datasource "db" provided to PrismaClient constructor.
It should have this form: { url: "CONNECTION_STRING" }
Read more at https://pris.ly/d/client-constructor
    at Object.datasources (C:\Users\Jan\Documents\throwaway\3.12.0_simple\prisma\library\runtime\index.js:45749:19)
    at validatePrismaClientOptions (C:\Users\Jan\Documents\throwaway\3.12.0_simple\prisma\library\runtime\index.js:45839:20)
    at new PrismaClient (C:\Users\Jan\Documents\throwaway\3.12.0_simple\prisma\library\runtime\index.js:45928:9)
    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\3.12.0_simple\scripts.ts:4:23)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (C:\Users\Jan\Documents\throwaway\3.12.0_simple\node_modules\ts-node\src\index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Jan\Documents\throwaway\3.12.0_simple\node_modules\ts-node\src\index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

It first logging the code location `C:\Users\Jan\Documents\throwaway\3.12.0_simple\prisma\library\runtime\index.js:45749` and the code that throws is weird. 

The error message itself is of course correct - `sdfsdfsd` is not set as an env var.

(3.12.0)

**Comment by Moanrisy** [comment]
I have the same error today, DId you try deploy it to heroku?
My problem was heroku can't read .env file because I put .env in .gitignore.

after I add config_vars on heroku, it work fine now

**Comment by janpio** [comment]
Yeah, I know exactly why it threw that error - the issue is just about how the error message looks. We want to improve that to make it easier to understand and then fix.

**Comment by janpio** [comment]
It includes the filename and the code that is throwing _that_ specific error. It should probably be a known error with an error code and so on as all the other known, structured ones.

**Comment by bimusiek** [comment]
That is one hell of a weird error. I was investigating why the tests are freezing Jetbrains Idea and it happens that the errors take so much memory because of stacktrace:
<img width="724" alt="CleanShot 2023-05-18 at 11 10 52@2x" src="https://github.com/prisma/prisma/assets/1025588/a154ce7c-b9b4-45a9-b305-583b255b8c3e">
Trust me, the minified code is much much longer.

**Comment by terence1990** [comment]
Error will be further down right at the bottom of the crazy minified code, likely a foreign key constraint

**Comment by amaben2020** [comment]
Hey @janpio was this resolved? I have this same issue
<img width="1247" alt="Screenshot 2023-08-25 at 12 24 21 PM" src="https://github.com/prisma/prisma/assets/60056927/136844d6-8c14-4450-9866-f21faad20402">
<img width="679" alt="Screenshot 2023-08-25 at 12 24 33 PM" src="https://github.com/prisma/prisma/assets/60056927/490f64b4-5311-44a8-b542-7c781770b6df">

**Comment by janpio** [comment]
Your log indicates it indeed might be fixed, as the weird part of the error message is gone.
In your case it seems that `DATABASE_URL` is just not set @amaben2020. You need to configure that in the Vercel UI to the desired value.

**Comment by Marinos20** [comment]
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import {PrismaClient} from '@prisma/client'

@Injectable()
export class PrismaService extends PrismaClient{
    constructor( configService : ConfigService) {
        super({
            datasources : {
                db :{
                    url : configService.get('DATABASE_UR'),
                }
            }
        })
    }
}
