### ISSUE TITLE
DataProxy Client logging is different from normal logging

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12681]
DataProxy Client:
```
C:\Users\Jan\Documents\throwaway\3.12.0_simple>npx ts-node scripts.ts
prisma:query query {
  findManyFoo {
    id
    name
  }
}
prisma:info Schema (re)uploaded (hash: 11e52bd7ecad95f9f3809fd9d8fec1533840f048c3c245ce8b703d8ff19d2fb3)
prisma:info Calling https://aws-us-east-1.prisma-data.com/3.12.0/11e52bd7ecad95f9f3809fd9d8fec1533840f048c3c245ce8b703d8ff19d2fb3/graphql (n=0)
    id
    name
  }
}
prisma:info Calling https://aws-us-east-1.prisma-data.com/3.12.0/11e52bd7ecad95f9f3809fd9d8fec1533840f048c3c245ce8b703d8ff19d2fb3/graphql (n=0)
foo proxy [ { id: '624c5afcef6abe4179942612', name: 'foo' } ]
```

Normal `library` Client:
```
  prisma:client:libraryEngine Searching for Query Engine Library in C:\Users\Jan\Documents\throwaway\3.12.0_simple\.prisma\client +53ms
  prisma:client:libraryEngine Searching for Query Engine Library in C:\Users\Jan\Documents\throwaway\3.12.0_simple\prisma\library +0ms
  prisma:client:libraryEngine loadEngine using C:\Users\Jan\Documents\throwaway\3.12.0_simple\prisma\library\query_engine-windows.dll.node +1ms
  prisma:client Prisma Client call: +920ms
  prisma:client prisma.foo.findMany({}) +2ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findManyFoo {
  prisma:client     id
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +1ms
  prisma:client:libraryEngine sending request, this.libraryStarted: false +871ms
  prisma:client:libraryEngine library starting +1ms
  prisma:client:libraryEngine library started +43ms
prisma:query db.Foo.aggregate([ { $project: { _id: 1, name: 1, }, }, ])
foo library [ { id: '624c5afcef6abe4179942612', name: 'foo' } ]
  prisma:client:libraryEngine library stopping +675ms
  prisma:client:libraryEngine library stopped +2ms
  prisma:client:libraryEngine hookProcess received: beforeExit +1ms
  prisma:client:libraryEngine runBeforeExit +1ms
  prisma:client:libraryEngine hookProcess received: exit +1ms
```

While it is expected that the DataProxy client can not log the query that is executed right now, there is no reason why e.g. "Prisma Client call" should not also be logged the same way it is with the normal Client.

Related: https://github.com/prisma/prisma/issues/12677

**Comment by aqrln** [comment]
Note to self: Prisma invocations (e.g., `prisma.foo.findMany({})`) are missing in the first snippet

**Comment by aqrln** [comment]
Doesn't seem to be the case for me, at least with the latest Prisma:

```
❯ ts-node playground.ts
  prisma:tryLoadEnv  Environment variables loaded from /Users/aqrln/projects/prisma/pdp-mongo-playground/.env +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/aqrln/projects/prisma/pdp-mongo-playground/.env +2ms
  prisma:client  dirname /Users/aqrln/projects/prisma/pdp-mongo-playground/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /Users/aqrln/projects/prisma/pdp-mongo-playground/prisma +0ms
  prisma:client  clientVersion: 4.0.0 +1ms
  prisma:client  clientEngineType: library +0ms
  prisma:client  Prisma Client call: +18ms
  prisma:client  prisma.message.findMany(undefined) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findManyMessage {
    id
    name
    message
  }
}
 +0ms
  prisma:client:dataproxyEngine  version 4.0.0 +0ms
[ { id: '62bc618f78fff75091a0a9ec', name: 'kitty', message: 'meow' } ]
```

Looking at the code, "Prisma Client call" and "Generated request" logs are emitted in the `PrismaClient` class and not in specific `Engine` subclasses, so they shouldn't depend on the type of the engine.

**Comment by janpio** [comment]
Next steps:
- @aqrln reproduces with 3.12. again
- @aqrln reaches out to @pantharshit00 test with Prisma 4.x

**Comment by aqrln** [comment]
Re-checked this again.

With Prisma 3.12.0 no logs whatsoever with `DEBUG=*` on my system, not even those that @janpio posted.

With Prisma 4.0.0 and node runtime everything works fine, the same logs as I posted above.

With Prisma 4.0.0 and edge runtime (which I didn't think about last time), no logs again. If I pass `{ __internal: { debug: true } }` to the constructor instead of using the env var, the edge client crashes:

```
/Users/aqrln/projects/prisma/pdp-mongo-playground/node_modules/@prisma/client/runtime/edge.js:17
`+i),e.push(o+"m+"+kn.exports.humanize(this.diff)+"\x1B[0m")}else e[0]=jp()+t+" "+e[0]}u($p,"formatArgs");function jp(){return se.inspectOpts.hideDate?"":new Date().toISOString()+" "}u(jp,"getDate");function Bp(...e){return v.stderr.write(Dn.format(...e)+`
                                                                                                                                                                                                                                         ^
TypeError: v.stderr.write is not a function
    at Function.log (/Users/aqrln/projects/prisma/pdp-mongo-playground/node_modules/@prisma/client/runtime/edge.js:17:234)
    at debug (/Users/aqrln/projects/prisma/pdp-mongo-playground/node_modules/@prisma/client/runtime/edge.js:15:5651)
    at /Users/aqrln/projects/prisma/pdp-mongo-playground/node_modules/@prisma/client/runtime/edge.js:19:396
    at new PrismaClient (/Users/aqrln/projects/prisma/pdp-mongo-playground/node_modules/@prisma/client/runtime/edge.js:104:1210)
    at main (/Users/aqrln/projects/prisma/pdp-mongo-playground/playground.ts:4:18)
    at Object.<anonymous> (/Users/aqrln/projects/prisma/pdp-mongo-playground/playground.ts:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module.m._compile (/Users/aqrln/.nvm/versions/node/v18.4.0/lib/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/aqrln/.nvm/versions/node/v18.4.0/lib/node_modules/ts-node/src/index.ts:1600:12) {
  clientVersion: '4.0.0'
}
```
