### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'not yet implemented'

### ISSUE THREAD

**Issue by Gorniaky** [prisma/prisma#12704]
### Bug description

```sh
thread 'tokio-runtime-worker' panicked at 'not yet implemented', query-engine\connectors\mongodb-query-connector\src\logger.rs:160:31
stack backtrace:
   0:     0x7ffcdc31e4af - napi_register_module_v1
   1:     0x7ffcdc33fe7a - rust_eh_personality
   2:     0x7ffcdc315bd8 - napi_register_module_v1
   3:     0x7ffcdc3212db - napi_register_module_v1
   4:     0x7ffcdc320dd4 - napi_register_module_v1
   5:     0x7ffcdb1a0a30 - <unknown>
   6:     0x7ffcdc321896 - napi_register_module_v1
   7:     0x7ffcdc32166f - napi_register_module_v1
   8:     0x7ffcdc31edf7 - napi_register_module_v1
   9:     0x7ffcdc321399 - napi_register_module_v1
  10:     0x7ffcdc4cf3a0 - rust_eh_personality
  11:     0x7ffcdc4cf2ec - rust_eh_personality
  12:     0x7ffcdb675623 - napi_register_module_v1
  13:     0x7ffcdb674a40 - napi_register_module_v1
  14:     0x7ffcdb6757a4 - napi_register_module_v1
  15:     0x7ffcdb55eb40 - napi_register_module_v1
  16:     0x7ffcdb5c24f5 - napi_register_module_v1
  17:     0x7ffcdb2be665 - napi_register_module_v1
  18:     0x7ffcdb2e72f1 - napi_register_module_v1
  19:     0x7ffcdb2e2dd0 - napi_register_module_v1
  20:     0x7ffcdb2facb6 - napi_register_module_v1
  21:     0x7ffcdb13e9cb - <unknown>
  22:     0x7ffcdb125ce6 - <unknown>
  23:     0x7ffcdb15836a - <unknown>
  24:     0x7ffcdb135575 - <unknown>
  25:     0x7ffcdb12b7f1 - <unknown>
  26:     0x7ffcdb12485f - <unknown>
  27:     0x7ffcdb131af3 - <unknown>
  28:     0x7ffcdb158fe2 - <unknown>
  29:     0x7ffcdb14540b - <unknown>
  30:     0x7ffcdb1f6a76 - napi_register_module_v1
  31:     0x7ffcdb0dd746 - <unknown>
  32:     0x7ffcdb0d31ae - <unknown>
  33:     0x7ffcdc20c4cf - napi_register_module_v1
  34:     0x7ffcdc211e97 - napi_register_module_v1
  35:     0x7ffcdc210c7f - napi_register_module_v1
  36:     0x7ffcdc2183d8 - napi_register_module_v1
  37:     0x7ffcdc21066a - napi_register_module_v1
  38:     0x7ffcdc222d6f - napi_register_module_v1
  39:     0x7ffcdc216444 - napi_register_module_v1
  40:     0x7ffcdc20cae6 - napi_register_module_v1
  41:     0x7ffcdc21b440 - napi_register_module_v1
  42:     0x7ffcdc227816 - napi_register_module_v1
  43:     0x7ffcdc219745 - napi_register_module_v1
  44:     0x7ffcdc2172e3 - napi_register_module_v1
  45:     0x7ffcdc32b8dc - napi_register_module_v1
  46:     0x7ffd3c8f7034 - BaseThreadInitThunk
  47:     0x7ffd3cec2651 - RtlUserThreadStart
F:\_RaccoonsCode\Konan\node_modules\@prisma\client\runtime\index.js:45582
        throw new PrismaClientUnknownRequestError(message, this.client._clientVersion);
              ^
PrismaClientUnknownRequestError:
Invalid `prisma.user.create()` invocation in
F:\_RaccoonsCode\Konan\test.ts:6:33

  3
  4 (async () => {
  5   console.log(await prisma.$connect());
→ 6   console.log(await prisma.user.create(
  not yet implemented
    at Object.request (F:\_RaccoonsCode\Konan\node_modules\@prisma\client\runtime\index.js:45582:15)
    at async PrismaClient._request (F:\_RaccoonsCode\Konan\node_modules\@prisma\client\runtime\index.js:46405:18) {
  clientVersion: '3.12.0'
}
error Command failed with exit code 1.
```

### How to reproduce
```
import { PrismaClient } from '@prisma/client';
import 'dotenv/config';

const prisma = new PrismaClient();

(async () => {
  console.log(await prisma.$connect());
  console.log(await prisma.user.create({
    data: {
      id: '1',
    },
  }));
})();
```

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
  ObjectId    String    @id @default(auto()) @map("_id") @db.ObjectId
  createdAt   DateTime  @default(now()) @db.Timestamp
  id          String    @unique
  premium     DateTime? @db.Timestamp
  guilds      Guild[]
  backups     Backup[]
}

model Guild {
  ObjectId  String   @id @default(auto()) @map("_id") @db.ObjectId
  createdAt DateTime @default(now()) @db.Timestamp
  id        String   @unique
  User      User     @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  userId    String
  backups   Backup[]
}

model Backup {
  ObjectId  String   @id @default(auto()) @map("_id") @db.ObjectId
  createdAt DateTime @default(now()) @db.Timestamp
  id        String   @unique
  data      Json
  premium   Boolean?
  Guild     Guild    @relation(fields: [guildId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  guildId   String
  User      User     @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  userId    String
}
```

### Environment & setup

- OS: Windows 10
- Database: MongoDB
- Node.js version: 16.14.0

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : 3.12.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\query_engine-windows.dll.node)    
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\migration-engine-windows.exe)Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

**Comment by janpio** [comment]
I can reproduce this with this script:
```
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  let user = await prisma.user.create({
    data: {
      id: '1',
    },
  })
  console.log(user);
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

Result:
```
PS C:\Users\Jan\Documents\throwaway\12704> node .\script.js
thread 'tokio-runtime-worker' panicked at 'not yet implemented', query-engine\connectors\mongodb-query-connector\src\logger.rs:160:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PrismaClientUnknownRequestError: 
Invalid `prisma.user.create()` invocation in
C:\Users\Jan\Documents\throwaway\12704\script.js:6:32

  3 const prisma = new PrismaClient()
  4
  5 async function main() {
→ 6   let user = await prisma.user.create(
  not yet implemented
    at Object.request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:45582:15)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:46405:18)
    at async main (C:\Users\Jan\Documents\throwaway\12704\script.js:6:14) {
  clientVersion: '3.12.0'
}
```

Also with `engineType = binary`:
```
PS C:\Users\Jan\Documents\throwaway\12704> node .\script.js   
PrismaClientUnknownRequestError: 
Invalid `prisma.user.create()` invocation in
C:\Users\Jan\Documents\throwaway\12704\script.js:6:32

  3 const prisma = new PrismaClient()
  4
  5 async function main() {
→ 6   let user = await prisma.user.create(
  PANIC in query-engine\connectors\mongodb-query-connector\src\logger.rs:160:31
not yet implemented

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v16.14.2+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+windows++++++++++++%7C%0A%7C+Prisma+Client+++%7C+3.12.0+++++++++++++%7C%0A%7C+Query+Engine++++%7C+query-engine+22b822189f46ef0dc5c5b503368d1bee01213980%7C%0A%7C+Database++++++++%7C+undefined%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0A++prisma%3AtryLoadEnv+Environment+variables+loaded+from+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5C.env++%0A++prisma%3AtryLoadEnv+Environment+variables+loaded+from+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5C.env++%0A++prisma%3Aclient+dirname++C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aclient+relativePath++..%5C..%5C..%5Cprisma++%0A++prisma%3Aclient+cwd++C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cprisma++%0A++prisma%3Aclient+clientVersion%3A+3.12.0++%0A++prisma%3Aclient+clientEngineType%3A+binary++%0A++prisma%3Aengine+Search+for+Query+Engine+in+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aengine+%7B+cwd%3A+%27C%3A%5C%5CUsers%5C%5CJan%5C%5CDocuments%5C%5Cthrowaway%5C%5C12704%5C%5Cprisma%27+%7D++%0A++prisma%3Aengine+Search+for+Query+Engine+in+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aengine+%7B+flags%3A+%5B+%27--enable-raw-queries%27%2C+%27--port%27%2C+%2754515%27+%5D+%7D++%0A++prisma%3Aengine+stdout++Started+query+engine+http+server+on+http%3A%2F%2F127.0.0.1%3A54515++%0A++prisma%3Aengine+Search+for+Query+Engine+in+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aengine+stdout++PANIC+in+query-engine%5Cconnectors%5Cmongodb-query-connector%5Csrc%5Clogger.rs%3A160%3A31%0Anot+yet+implemented++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+Error%3A+read+ECONNRESET%0A++prisma%3Aengine+++++++at+TCP.onStreamRead+%28node%3Ainternal%2Fstream_base_commons%3A217%3A20%29+%7B%0A++prisma%3Aengine+++++errno%3A+-4077%2C%0A++prisma%3Aengine+++++code%3A+%27ECONNRESET%27%2C%0A++prisma%3Aengine+++++syscall%3A+%27read%27%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+Error%3A+connect+ECONNREFUSED+127.0.0.1%3A54515%0A++prisma%3Aengine+++++++at+TCPConnectWrap.afterConnect+%5Bas+oncomplete%5D+%28node%3Anet%3A1157%3A16%29+%7B%0A++prisma%3Aengine+++++errno%3A+-4078%2C%0A++prisma%3Aengine+++++code%3A+%27ECONNREFUSED%27%2C%0A++prisma%3Aengine+++++syscall%3A+%27connect%27%2C%0A++prisma%3Aengine+++++address%3A+%27127.0.0.1%27%2C%0A++prisma%3Aengine+++++port%3A+54515%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A++prisma%3Aengine+%7B+cwd%3A+%27C%3A%5C%5CUsers%5C%5CJan%5C%5CDocuments%5C%5Cthrowaway%5C%5C12704%5C%5Cprisma%27+%7D++%0A++prisma%3Aengine+Search+for+Query+Engine+in+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aengine+%7B+flags%3A+%5B+%27--enable-raw-queries%27%2C+%27--port%27%2C+%2754521%27+%5D+%7D++%0A++prisma%3Aengine+Client+Version%3A+3.12.0++%0A++prisma%3Aengine+Engine+Version%3A+query-engine+22b822189f46ef0dc5c5b503368d1bee01213980++%0A++prisma%3Aengine+Active+provider%3A+mongodb++%0A++prisma%3Aengine+stdout++Started+query+engine+http+server+on+http%3A%2F%2F127.0.0.1%3A54521++%0A++prisma%3Aengine+Search+for+Query+Engine+in+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aengine+stdout++PANIC+in+query-engine%5Cconnectors%5Cmongodb-query-connector%5Csrc%5Clogger.rs%3A160%3A31%0Anot+yet+implemented++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+Error%3A+read+ECONNRESET%0A++prisma%3Aengine+++++++at+TCP.onStreamRead+%28node%3Ainternal%2Fstream_base_commons%3A217%3A20%29+%7B%0A++prisma%3Aengine+++++errno%3A+-4077%2C%0A++prisma%3Aengine+++++code%3A+%27ECONNRESET%27%2C%0A++prisma%3Aengine+++++syscall%3A+%27read%27%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0Amutation+%7B%0A++createOneUser%28data%3A+%7B%0A++++id%3A+%22X%22%0A++%7D%29+%7B%0A++++ObjectId%0A++++createdAt%0A++++id%0A++%7D%0A%7D%0A%60%60%60%0A&title=PANIC+in+query-engine%5Cconnectors%5Cmongodb-query-connector%5Csrc%5Clogger.rs%3A160%3A31%0Anot+yet+implemented&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

    at Object.request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:45582:15)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:46405:18)
    at async main (C:\Users\Jan\Documents\throwaway\12704\script.js:6:14) {
  clientVersion: '3.12.0'
}
PS C:\Users\Jan\Documents\throwaway\12704>
```

**Comment by dpetrick** [comment]
Fix will ship with 3.13.

**Comment by janpio** [comment]
I can confirm this is fixed in `3.13.0-dev.15`:

```
C:\Users\Jan\Documents\throwaway\12704>node .\script.js
{
  ObjectId: '6258c5058d4eed9d57ec271a',
  createdAt: 2022-04-15T01:06:12.000Z,
  id: '1'
}
```

**Comment by diogofalken** [comment]
Any idea when 3.13 will be released? If not, development will halt indefinitely without the 'create' command until the new version is released.

Any workaround meanwhile?

**Comment by janpio** [comment]
In the next 24 hours.

If you need to continue in the meantime, you can use the `prisma@dev` and `@prisma/client@dev` packages temporarily.

**Comment by Gorniaky** [comment]
> Any idea when 3.13 will be released? If not, development will halt indefinitely without the 'create' command until the new version is released.
> 
> Any workaround meanwhile?

The solution I found is using version 3.10.0 of the prisma and @prisma/client packages

**Comment by Gorniaky** [comment]
> Any idea when 3.13 will be released? If not, development will halt indefinitely without the 'create' command until the new version is released.
> 
> Any workaround meanwhile?

The solution I found is using version 3.10.0 of the prisma and @prisma/client packages

**Comment by diogofalken** [comment]
Thanks for the fast responses! Keep up the great work! 🚀
