### ISSUE TITLE
RUST_BACKTRACE advice on Engine panic is weird

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12707]
Noticed while reproducing https://github.com/prisma/prisma/issues/12704

With no `RUST_BACKTRACE` defined:

```
PS C:\Users\Jan\Documents\throwaway\12704> node .\script.js    
thread 'tokio-runtime-worker' panicked at 'not yet implemented', query-engine\connectors\mongodb-query-connector\src\logger.rs:160:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PrismaClientUnknownRequestError: 
Invalid `prisma.user.create()` invocation in
C:\Users\Jan\Documents\throwaway\12704\script.js:6:32

  3 const prisma = new PrismaClient()
  4
  5 async function main() {
→ 6   let user = await prisma.user.create(
  not yet implemented
    at Object.request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:45582:15)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:46405:18)
    at async main (C:\Users\Jan\Documents\throwaway\12704\script.js:6:14) {
  clientVersion: '3.12.0'
}
```

Then with `RUST_BACKTRACE=1`:
```
PS C:\Users\Jan\Documents\throwaway\12704> $env:RUST_BACKTRACE=1
PS C:\Users\Jan\Documents\throwaway\12704> node .\script.js     
thread 'tokio-runtime-worker' panicked at 'not yet implemented', query-engine\connectors\mongodb-query-connector\src\logger.rs:160:31
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
PrismaClientUnknownRequestError: 
Invalid `prisma.user.create()` invocation in
C:\Users\Jan\Documents\throwaway\12704\script.js:6:32

  3 const prisma = new PrismaClient()
  4
  5 async function main() {
→ 6   let user = await prisma.user.create(
  not yet implemented
    at Object.request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:45582:15)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:46405:18)
    at async main (C:\Users\Jan\Documents\throwaway\12704\script.js:6:14) {
  clientVersion: '3.12.0'
}
```

Then with `RUST_BACKTRACE = "full"`:
```
PS C:\Users\Jan\Documents\throwaway\12704> $env:RUST_BACKTRACE = "full"
PS C:\Users\Jan\Documents\throwaway\12704> node .\script.js
thread 'tokio-runtime-worker' panicked at 'not yet implemented', query-engine\connectors\mongodb-query-connector\src\logger.rs:160:31
stack backtrace:
   0:     0x7fff2b4ee4af - napi_register_module_v1
   1:     0x7fff2b50fe7a - rust_eh_personality
   2:     0x7fff2b4e5bd8 - napi_register_module_v1
   3:     0x7fff2b4f12db - napi_register_module_v1
   4:     0x7fff2b4f0dd4 - napi_register_module_v1
   5:     0x7fff2a370a30 - <unknown>
   6:     0x7fff2b4f1896 - napi_register_module_v1
   7:     0x7fff2b4f166f - napi_register_module_v1
   8:     0x7fff2b4eedf7 - napi_register_module_v1
   9:     0x7fff2b4f1399 - napi_register_module_v1
  10:     0x7fff2b69f3a0 - rust_eh_personality
  11:     0x7fff2b69f2ec - rust_eh_personality
  12:     0x7fff2a845623 - napi_register_module_v1
  13:     0x7fff2a844a40 - napi_register_module_v1
  14:     0x7fff2a8457a4 - napi_register_module_v1
  15:     0x7fff2a72eb40 - napi_register_module_v1
  16:     0x7fff2a7924f5 - napi_register_module_v1
  17:     0x7fff2a48e665 - napi_register_module_v1
  38:     0x7fff2b3f2d6f - napi_register_module_v1
  39:     0x7fff2b3e6444 - napi_register_module_v1
  40:     0x7fff2b3dcae6 - napi_register_module_v1
  41:     0x7fff2b3eb440 - napi_register_module_v1
  42:     0x7fff2b3f7816 - napi_register_module_v1
  43:     0x7fff2b3e9745 - napi_register_module_v1
  44:     0x7fff2b3e72e3 - napi_register_module_v1
  45:     0x7fff2b4fb8dc - napi_register_module_v1
  46:     0x7fffaee454e0 - BaseThreadInitThunk
  47:     0x7fffafb2485b - RtlUserThreadStart
PrismaClientUnknownRequestError:
Invalid `prisma.user.create()` invocation in
C:\Users\Jan\Documents\throwaway\12704\script.js:6:32

  3 const prisma = new PrismaClient()
  4
  5 async function main() {
→ 6   let user = await prisma.user.create(
  not yet implemented
    at Object.request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:45582:15)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:46405:18)    at async main (C:\Users\Jan\Documents\throwaway\12704\script.js:6:14) {
  clientVersion: '3.12.0'
}
```

Note how `RUST_BACKTRACE=1` did not actually do anything useful 😞 

This might of course just be a Rust thing we can not influence.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
