### ISSUE TITLE
Using 'set' to update explicit m2m relation fails silently or throws an error

### ISSUE THREAD

**Issue by jrmyio** [prisma/prisma#12701]
### Bug description

When I try to update an explicit many-to-many relation, via a `set` the update does nothing. 
When I try to delete all related via an update `The change you are trying to make would violate the required relation 'PlayListToTrackPlayList' between the `PlayList` and `TrackPlayList` models.` is thrown.

### How to reproduce

Run script.ts with the following schema:

schema.prisma:
```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Track {
    id   Int    @id @default(autoincrement()) 
    name String 

    TrackPlayList TrackPlayList[] @relation()
    @@map("test_tracks")
}

model PlayList {
    id   Int    @id @default(autoincrement()) 
    name String 

    TrackPlayList TrackPlayList[]
    @@map("test_playlists")
}

model TrackPlayList {

    track      Track    @relation(fields: [trackId], references: [id], onUpdate: Cascade, onDelete: Cascade)
    trackId    Int      @map("track_id") 
    playlist   PlayList @relation(fields: [playlistId], references: [id], onUpdate: Cascade, onDelete: Cascade)
    playlistId Int      @map("playlist_id") 
    addedAt    DateTime

    @@id([trackId, playlistId])
    @@map("test_track_playlist")
}
```
script.ts:
```ts
import { PrismaClient } from '@prisma/client';

const prisma: PrismaClient = new PrismaClient({ log: ['query', 'info', 'warn'] });

async function main() {
    await prisma.track.deleteMany({});
    await prisma.playList.deleteMany({});

    console.log('Creating songs and a playlist');
    const track1 = await prisma.track.create({
        data: {
            name: 'Great song #1'
        }
    });
    const track2 = await prisma.track.create({
        data: {
            name: 'Great song #2'
        }
    });
    const playlist = await prisma.playList.create({
        data: {
            name: 'Great playlist'
        }
    });

    console.log('Updating the playlist with its first track');
    await prisma.playList.update({
        data: {
            TrackPlayList: {
                upsert: [
                    {
                        create: {
                            trackId: track1.id,
                            addedAt: new Date()
                        },
                        update: {
                            trackId: track1.id
                        },
                        where: {
                            trackId_playlistId: {
                                trackId: track1.id,
                                playlistId: playlist.id
                            }
                        }
                    }
                ]
            }
        },
        where: {
            id: playlist.id
        }
    });

    console.log('Updating the playlist with the previous and another track');
    /**
     * You would expect track 2 to be added but no update queries are processed...
     */
    await prisma.playList.update({
        data: {
            TrackPlayList: {
                set: [
                    {
                        trackId_playlistId: {
                            playlistId: playlist.id,
                            trackId: track1.id
                        }
                    },
                    {
                        trackId_playlistId: {
                            playlistId: playlist.id,
                            trackId: track2.id
                        }
                    }
                ]
            }
        },
        where: {
            id: playlist.id
        }
    });

    /**
     * Trying to remove all related tracks from playlist throws:
     * The change you are trying to make would violate the required
     * relation 'PlayListToTrackPlayList' between the `PlayList` and `TrackPlayList` models.
     */
    await prisma.playList.update({
        data: {
            TrackPlayList: {
                set: []
            }
        },
        where: {
            id: playlist.id
        }
    });
}

main()
    .catch((e) => {
        throw e;
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
```

### Expected behavior

I create the 3 objects and link the first track to a playlist via an upsert. So far so good.

But then I try to use the `set` inside `prisma.playList.update`

I expect to have 2 `TrackPlayList` after running, but I have still 1:
```ts
prisma.playList.update({
        data: {
            TrackPlayList: {
                set: [
                    {
                        trackId_playlistId: {
                            playlistId: playlist.id,
                            trackId: track1.id
                        }
                    },
                    {
                        trackId_playlistId: {
                            playlistId: playlist.id,
                            trackId: track2.id
                        }
                    }
                ]
            }
        },
        where: {
            id: playlist.id
        }
    });
```

I expect the following to not throw an error but remove the track relations for the given playlist.
```
    await prisma.playList.update({
        data: {
            TrackPlayList: {
                set: []
            }
        },
        where: {
            id: playlist.id
        }
    });
```

### Prisma information

When running the script I get the following output:

```
DEBUG="*" npm run dev

> dev
> ts-node ./script.ts

  prisma:tryLoadEnv Environment variables loaded from /example/.env +0ms
  prisma:tryLoadEnv Environment variables loaded from /example/.env +2ms
  prisma:client clientVersion: 3.11.0 +0ms
  prisma:client clientEngineType: library +0ms
  prisma:client:libraryEngine internalSetup +0ms
  prisma:client Prisma Client call: +49ms
  prisma:client prisma.track.deleteMany({}) +0ms
  prisma:client Generated request: +0ms
  prisma:client mutation {
  prisma:client   deleteManyTrack {
  prisma:client     count
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: false +50ms
  prisma:client:libraryEngine Searching for Query Engine Library in /example/node_modules/.prisma/client +24ms
  prisma:client:libraryEngine loadEngine using /example/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node +1ms
  prisma:client:libraryEngine library starting +3ms
prisma:info Starting a sqlite pool with 17 connections.
  prisma:client:libraryEngine library started +6ms
prisma:query BEGIN
prisma:query SELECT `main`.`test_tracks`.`id` FROM `main`.`test_tracks` WHERE 1=1 LIMIT ? OFFSET ?
prisma:query SELECT `main`.`test_tracks`.`id` FROM `main`.`test_tracks` WHERE 1=1
prisma:query DELETE FROM `main`.`test_tracks` WHERE `main`.`test_tracks`.`id` IN (?,?)
prisma:query COMMIT
  prisma:client Prisma Client call: +42ms
  prisma:client prisma.playList.deleteMany({}) +0ms
  prisma:client Generated request: +0ms
  prisma:client mutation {
  prisma:client   deleteManyPlayList {
  prisma:client     count
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +7ms
prisma:query BEGIN
prisma:query SELECT `main`.`test_playlists`.`id` FROM `main`.`test_playlists` WHERE 1=1 LIMIT ? OFFSET ?
prisma:query SELECT `main`.`test_playlists`.`id` FROM `main`.`test_playlists` WHERE 1=1
prisma:query DELETE FROM `main`.`test_playlists` WHERE `main`.`test_playlists`.`id` IN (?)
prisma:query COMMIT
Creating songs and a playlist
  prisma:client Prisma Client call: +7ms
  prisma:client prisma.track.create({
  prisma:client   data: {
  prisma:client     name: 'Great song #1'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client mutation {
  prisma:client   createOneTrack(data: {
  prisma:client     name: "Great song #1"
  prisma:client   }) {
  prisma:client     id
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +8ms
prisma:query BEGIN
prisma:query INSERT INTO `main`.`test_tracks` (`name`) VALUES (?) RETURNING id
prisma:query SELECT `main`.`test_tracks`.`id`, `main`.`test_tracks`.`name` FROM `main`.`test_tracks` WHERE `main`.`test_tracks`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
  prisma:client Prisma Client call: +6ms
  prisma:client prisma.track.create({
  prisma:client   data: {
  prisma:client     name: 'Great song #2'
  prisma:client   }
  prisma:client }) +0ms
  prisma:client Generated request: +0ms
  prisma:client mutation {
  prisma:client   createOneTrack(data: {
  prisma:client     name: "Great song #2"
  prisma:client   }) {
  prisma:client     id
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +7ms
prisma:query BEGIN
prisma:query INSERT INTO `main`.`test_tracks` (`name`) VALUES (?) RETURNING id
prisma:query SELECT `main`.`test_tracks`.`id`, `main`.`test_tracks`.`name` FROM `main`.`test_tracks` WHERE `main`.`test_tracks`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
  prisma:client Prisma Client call: +6ms
  prisma:client prisma.playList.create({
  prisma:client   data: {
  prisma:client     name: 'Great playlist'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client mutation {
  prisma:client   createOnePlayList(data: {
  prisma:client     name: "Great playlist"
  prisma:client   }) {
  prisma:client     id
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +6ms
prisma:query BEGIN
prisma:query INSERT INTO `main`.`test_playlists` (`name`) VALUES (?) RETURNING id
prisma:query SELECT `main`.`test_playlists`.`id`, `main`.`test_playlists`.`name` FROM `main`.`test_playlists` WHERE `main`.`test_playlists`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
Updating the playlist with its first track
  prisma:client Prisma Client call: +8ms
  prisma:client prisma.playList.update({
  prisma:client   data: {
  prisma:client     TrackPlayList: {
  prisma:client       upsert: [
  prisma:client         {
  prisma:client           create: {
  prisma:client             trackId: 40,
  prisma:client             addedAt: new Date('2022-04-06T19:15:55.977Z')
  prisma:client           },
  prisma:client           update: {
  prisma:client             trackId: 40
  prisma:client           },
  prisma:client           where: {
  prisma:client             trackId_playlistId: {
  prisma:client               trackId: 40,
  prisma:client               playlistId: 25
  prisma:client             }
  prisma:client           }
  prisma:client         }
  prisma:client       ]
  prisma:client     }
  prisma:client   },
  prisma:client   where: {
  prisma:client     id: 25
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client mutation {
  prisma:client   updateOnePlayList(
  prisma:client     data: {
  prisma:client       TrackPlayList: {
  prisma:client         upsert: [
  prisma:client           {
  prisma:client             create: {
  prisma:client               trackId: 40
  prisma:client               addedAt: "2022-04-06T19:15:55.977Z"
  prisma:client             }
  prisma:client             update: {
  prisma:client               trackId: 40
  prisma:client             }
  prisma:client             where: {
  prisma:client               trackId_playlistId: {
  prisma:client                 trackId: 40
  prisma:client                 playlistId: 25
  prisma:client               }
  prisma:client             }
  prisma:client           }
  prisma:client         ]
  prisma:client       }
  prisma:client     }
  prisma:client     where: {
  prisma:client       id: 25
  prisma:client     }
  prisma:client   ) {
  prisma:client     id
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +9ms
prisma:query BEGIN
prisma:query SELECT `main`.`test_playlists`.`id` FROM `main`.`test_playlists` WHERE `main`.`test_playlists`.`id` = ?
prisma:query SELECT `main`.`test_track_playlist`.`track_id`, `main`.`test_track_playlist`.`playlist_id` FROM `main`.`test_track_playlist` WHERE ((`main`.`test_track_playlist`.`track_id` = ? AND `main`.`test_track_playlist`.`playlist_id` = ?) AND `main`.`test_track_playlist`.`playlist_id` IN (?)) LIMIT ? OFFSET ?
prisma:query INSERT INTO `main`.`test_track_playlist` (`track_id`, `playlist_id`, `addedAt`) VALUES (?,?,?) RETURNING track_id, playlist_id
prisma:query SELECT `main`.`test_playlists`.`id`, `main`.`test_playlists`.`name` FROM `main`.`test_playlists` WHERE `main`.`test_playlists`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
Updating the playlist with the previous and another track
  prisma:client Prisma Client call: +6ms
  prisma:client prisma.playList.update({
  prisma:client   data: {
  prisma:client     TrackPlayList: {
  prisma:client       set: [
  prisma:client         {
  prisma:client           trackId_playlistId: {
  prisma:client             playlistId: 25,
  prisma:client             trackId: 40
  prisma:client           }
  prisma:client         },
  prisma:client         {
  prisma:client           trackId_playlistId: {
  prisma:client             playlistId: 25,
  prisma:client             trackId: 41
  prisma:client           }
  prisma:client         }
  prisma:client       ]
  prisma:client     }
  prisma:client   },
  prisma:client   where: {
  prisma:client     id: 25
  prisma:client   }
  prisma:client }) +0ms
  prisma:client Generated request: +0ms
  prisma:client mutation {
  prisma:client   updateOnePlayList(
  prisma:client     data: {
  prisma:client       TrackPlayList: {
  prisma:client         set: [
  prisma:client           {
  prisma:client             trackId_playlistId: {
  prisma:client               playlistId: 25
  prisma:client               trackId: 40
  prisma:client             }
  prisma:client           },
  prisma:client           {
  prisma:client             trackId_playlistId: {
  prisma:client               playlistId: 25
  prisma:client               trackId: 41
  prisma:client             }
  prisma:client           }
  prisma:client         ]
  prisma:client       }
  prisma:client     }
  prisma:client     where: {
  prisma:client       id: 25
  prisma:client     }
  prisma:client   ) {
  prisma:client     id
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +6ms
prisma:query BEGIN
prisma:query SELECT `main`.`test_playlists`.`id` FROM `main`.`test_playlists` WHERE `main`.`test_playlists`.`id` = ?
prisma:query SELECT `main`.`test_track_playlist`.`track_id`, `main`.`test_track_playlist`.`playlist_id` FROM `main`.`test_track_playlist` WHERE (1=1 AND `main`.`test_track_playlist`.`playlist_id` IN (?)) LIMIT ? OFFSET ?
prisma:query SELECT `main`.`test_track_playlist`.`track_id`, `main`.`test_track_playlist`.`playlist_id` FROM `main`.`test_track_playlist` WHERE ((`main`.`test_track_playlist`.`track_id` = ? AND `main`.`test_track_playlist`.`playlist_id` = ?) OR (`main`.`test_track_playlist`.`track_id` = ? AND `main`.`test_track_playlist`.`playlist_id` = ?)) LIMIT ? OFFSET ?
prisma:query SELECT `main`.`test_playlists`.`id`, `main`.`test_playlists`.`name` FROM `main`.`test_playlists` WHERE `main`.`test_playlists`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
  prisma:client Prisma Client call: +5ms
  prisma:client prisma.playList.update({
  prisma:client   data: {
  prisma:client     TrackPlayList: {
  prisma:client       set: []
  prisma:client     }
  prisma:client   },
  prisma:client   where: {
  prisma:client     id: 25
  prisma:client   }
  prisma:client }) +0ms
  prisma:client Generated request: +0ms
  prisma:client mutation {
  prisma:client   updateOnePlayList(
  prisma:client     data: {
  prisma:client       TrackPlayList: {
  prisma:client         set: []
  prisma:client       }
  prisma:client     }
  prisma:client     where: {
  prisma:client       id: 25
  prisma:client     }
  prisma:client   ) {
  prisma:client     id
  prisma:client     name
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +5ms
prisma:query BEGIN
prisma:query SELECT `main`.`test_playlists`.`id` FROM `main`.`test_playlists` WHERE `main`.`test_playlists`.`id` = ?
prisma:query SELECT `main`.`test_track_playlist`.`track_id`, `main`.`test_track_playlist`.`playlist_id` FROM `main`.`test_track_playlist` WHERE (1=1 AND `main`.`test_track_playlist`.`playlist_id` IN (?)) LIMIT ? OFFSET ?
prisma:query SELECT `main`.`test_track_playlist`.`track_id`, `main`.`test_track_playlist`.`playlist_id` FROM `main`.`test_track_playlist` WHERE 1=0 LIMIT ? OFFSET ?
prisma:query ROLLBACK
  prisma:client:request_handler Error: The change you are trying to make would violate the required relation 'PlayListToTrackPlayList' between the `PlayList` and `TrackPlayList` models.
  prisma:client:request_handler     at prismaGraphQLToJSError (/example/node_modules/@prisma/client/runtime/index.js:33922:12)
  prisma:client:request_handler     at Object.request (/example/node_modules/@prisma/client/runtime/index.js:35748:17)
  prisma:client:request_handler     at async Object.request (/example/node_modules/@prisma/client/runtime/index.js:39788:24)
  prisma:client:request_handler     at async PrismaClient._request (/example/node_modules/@prisma/client/runtime/index.js:40646:18) +0ms
  prisma:client:libraryEngine library stopping +13ms
  prisma:client:libraryEngine library stopped +1ms
  prisma:client:libraryEngine hookProcess received: exit +1ms
  prisma:client:libraryEngine runBeforeExit +0ms
/example/node_modules/@prisma/client/runtime/index.js:39818
        throw new PrismaClientKnownRequestError(message, e.code, this.client._clientVersion, e.meta);
              ^
PrismaClientKnownRequestError: 
Invalid `prisma.playList.update()` invocation in
/example/script.ts:87:27

   84  * The change you are trying to make would violate the required
   85  * relation 'PlayListToTrackPlayList' between the `PlayList` and `TrackPlayList` models.
   86  */
→  87 await prisma.playList.update(
  The change you are trying to make would violate the required relation 'PlayListToTrackPlayList' between the `PlayList` and `TrackPlayList` models.
    at Object.request (/example/node_modules/@prisma/client/runtime/index.js:39818:15)
    at async PrismaClient._request (/example/node_modules/@prisma/client/runtime/index.js:40646:18) {
  code: 'P2014',
  clientVersion: '3.11.0',
  meta: {
    relation_name: 'PlayListToTrackPlayList',
    model_a_name: 'PlayList',
    model_b_name: 'TrackPlayList'
  }
}
```

### Environment & setup

**OS:**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

**Node 16.13.1**

package.json
```json
{
  "name": "script",
  "license": "MIT",
  "devDependencies": {
    "prisma": "3.11.0",
    "ts-node": "10.7.0",
    "typescript": "4.6.2",
    "@types/node": "16.11.26"
  },
  "scripts": {
    "dev": "ts-node ./script.ts"
  },
  "dependencies": {
    "@prisma/client": "3.11.0"
  },
  "engines": {
    "node": ">=12.2.0"
  }
}
```

### Prisma Version

```
prisma                  : 3.11.0
@prisma/client          : 3.11.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt b371888aaf8f51357c7457d836b86d12da91658b (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : b371888aaf8f51357c7457d836b86d12da91658b
Studio                  : 0.458.0
```

**Comment by dpetrick** [comment]
Let's dissect your script, what it does and what happens with your data.

```ts
    const track1 = await prisma.track.create({
        data: {
            name: 'Great song #1'
        }
    });
    const track2 = await prisma.track.create({
        data: {
            name: 'Great song #2'
        }
    });
    const playlist = await prisma.playList.create({
        data: {
            name: 'Great playlist'
        }
    });
```

You now have the following data:
Tracks:
- `{ id: 1, name: "Great song #1" }`
- `{ id: 2, name: "Great song #2" }`

Playlists:
- `{ id: 1, name: "Great playlist" }`

TrackPlayList:
- None

Next:
```ts
    console.log('Updating the playlist with its first track');
    await prisma.playList.update({
        data: {
            TrackPlayList: {
                upsert: [
                    {
                        create: {
                            trackId: track1.id,
                            addedAt: new Date()
                        },
                        update: {
                            trackId: track1.id
                        },
                        where: {
                            trackId_playlistId: {
                                trackId: track1.id,
                                playlistId: playlist.id
                            }
                        }
                    }
                ]
            }
        },
        where: {
            id: playlist.id
        }
    });
```

Now you have (create path of upsert triggers):
Tracks:
- `{ id: 1, name: "Great song #1" }`
- `{ id: 2, name: "Great song #2" }`

Playlists:
- `{ id: 1, name: "Great playlist" }`

TrackPlayList:
- `{ trackId: 1, playlistId: 1, addedAt: "..." }`

You're now doing:
```ts
    console.log('Updating the playlist with the previous and another track');
    /**
     * You would expect track 2 to be added but no update queries are processed...
     */
    await prisma.playList.update({
        data: {
            TrackPlayList: {
                set: [
                    {
                        trackId_playlistId: {
                            playlistId: playlist.id,
                            trackId: track1.id
                        }
                    },
                    {
                        trackId_playlistId: {
                            playlistId: playlist.id,
                            trackId: track2.id
                        }
                    }
                ]
            }
        },
        where: {
            id: playlist.id
        }
    });
```

Your data is still the same as above. Your question is why didn't track 2 and playlist 1 get connected?
The answer is because `set` doesn't create any record, it _finds_ certain records to connect with, and replaces the current related records. The types / data that you have to give should hint that nothing is created, but things are searched for.
In your case, it find `TrackPlaylist` with the `trackId: 1` and `playlistId: 1` key combination because it exists, so it's set to replace. The second one doesn't exist, so it doesn't get added.

Now, the second part of your problem, the next snippet:
```ts
    /**
     * Trying to remove all related tracks from playlist throws:
     * The change you are trying to make would violate the required
     * relation 'PlayListToTrackPlayList' between the `PlayList` and `TrackPlayList` models.
     */
    await prisma.playList.update({
        data: {
            TrackPlayList: {
                set: []
            }
        },
        where: {
            id: playlist.id
        }
    });
}
```

Your problems stem from a misunderstanding of `set`: This doesn't delete anything, this _disconnects_ the currently connected relation (the `trackId: 1` and `playlistId: 1` record from above) and sets a new set (here, empty). If you disconnect a `TrackPlaylist` record, it will fail because you're violating referential integrity by doing so ().

What you want are the correct operations to achieve the right things: `create` for creating explicit m2m links, `delete` for deleting certain ones, not `set`, which doesn't do any of that.
