### ISSUE TITLE
Node-API Engine is missing crash handling to create GitHub issue link

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#12708]
While reproducing https://github.com/prisma/prisma/issues/12704 I noticed that the Engine panic was not handled via creation of a GitHub issue link to report it: https://github.com/prisma/prisma/issues/12704#issuecomment-1091338289

With `library` engine type:
```
PS C:\Users\Jan\Documents\throwaway\12704> node .\script.js
thread 'tokio-runtime-worker' panicked at 'not yet implemented', query-engine\connectors\mongodb-query-connector\src\logger.rs:160:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PrismaClientUnknownRequestError: 
Invalid `prisma.user.create()` invocation in
C:\Users\Jan\Documents\throwaway\12704\script.js:6:32

  3 const prisma = new PrismaClient()
  4
  5 async function main() {
→ 6   let user = await prisma.user.create(
  not yet implemented
    at Object.request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:45582:15)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:46405:18)
    at async main (C:\Users\Jan\Documents\throwaway\12704\script.js:6:14) {
  clientVersion: '3.12.0'
}
```

And as it should be with `engineType = binary`:
```
PS C:\Users\Jan\Documents\throwaway\12704> node .\script.js   
PrismaClientUnknownRequestError: 
Invalid `prisma.user.create()` invocation in
C:\Users\Jan\Documents\throwaway\12704\script.js:6:32

  3 const prisma = new PrismaClient()
  4
  5 async function main() {
→ 6   let user = await prisma.user.create(
  PANIC in query-engine\connectors\mongodb-query-connector\src\logger.rs:160:31
not yet implemented

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v16.14.2+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+windows++++++++++++%7C%0A%7C+Prisma+Client+++%7C+3.12.0+++++++++++++%7C%0A%7C+Query+Engine++++%7C+query-engine+22b822189f46ef0dc5c5b503368d1bee01213980%7C%0A%7C+Database++++++++%7C+undefined%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0A++prisma%3AtryLoadEnv+Environment+variables+loaded+from+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5C.env++%0A++prisma%3AtryLoadEnv+Environment+variables+loaded+from+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5C.env++%0A++prisma%3Aclient+dirname++C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aclient+relativePath++..%5C..%5C..%5Cprisma++%0A++prisma%3Aclient+cwd++C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cprisma++%0A++prisma%3Aclient+clientVersion%3A+3.12.0++%0A++prisma%3Aclient+clientEngineType%3A+binary++%0A++prisma%3Aengine+Search+for+Query+Engine+in+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aengine+%7B+cwd%3A+%27C%3A%5C%5CUsers%5C%5CJan%5C%5CDocuments%5C%5Cthrowaway%5C%5C12704%5C%5Cprisma%27+%7D++%0A++prisma%3Aengine+Search+for+Query+Engine+in+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aengine+%7B+flags%3A+%5B+%27--enable-raw-queries%27%2C+%27--port%27%2C+%2754515%27+%5D+%7D++%0A++prisma%3Aengine+stdout++Started+query+engine+http+server+on+http%3A%2F%2F127.0.0.1%3A54515++%0A++prisma%3Aengine+Search+for+Query+Engine+in+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aengine+stdout++PANIC+in+query-engine%5Cconnectors%5Cmongodb-query-connector%5Csrc%5Clogger.rs%3A160%3A31%0Anot+yet+implemented++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+Error%3A+read+ECONNRESET%0A++prisma%3Aengine+++++++at+TCP.onStreamRead+%28node%3Ainternal%2Fstream_base_commons%3A217%3A20%29+%7B%0A++prisma%3Aengine+++++errno%3A+-4077%2C%0A++prisma%3Aengine+++++code%3A+%27ECONNRESET%27%2C%0A++prisma%3Aengine+++++syscall%3A+%27read%27%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+Error%3A+connect+ECONNREFUSED+127.0.0.1%3A54515%0A++prisma%3Aengine+++++++at+TCPConnectWrap.afterConnect+%5Bas+oncomplete%5D+%28node%3Anet%3A1157%3A16%29+%7B%0A++prisma%3Aengine+++++errno%3A+-4078%2C%0A++prisma%3Aengine+++++code%3A+%27ECONNREFUSED%27%2C%0A++prisma%3Aengine+++++syscall%3A+%27connect%27%2C%0A++prisma%3Aengine+++++address%3A+%27127.0.0.1%27%2C%0A++prisma%3Aengine+++++port%3A+54515%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A++prisma%3Aengine+%7B+cwd%3A+%27C%3A%5C%5CUsers%5C%5CJan%5C%5CDocuments%5C%5Cthrowaway%5C%5C12704%5C%5Cprisma%27+%7D++%0A++prisma%3Aengine+Search+for+Query+Engine+in+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aengine+%7B+flags%3A+%5B+%27--enable-raw-queries%27%2C+%27--port%27%2C+%2754521%27+%5D+%7D++%0A++prisma%3Aengine+Client+Version%3A+3.12.0++%0A++prisma%3Aengine+Engine+Version%3A+query-engine+22b822189f46ef0dc5c5b503368d1bee01213980++%0A++prisma%3Aengine+Active+provider%3A+mongodb++%0A++prisma%3Aengine+stdout++Started+query+engine+http+server+on+http%3A%2F%2F127.0.0.1%3A54521++%0A++prisma%3Aengine+Search+for+Query+Engine+in+C%3A%5CUsers%5CJan%5CDocuments%5Cthrowaway%5C12704%5Cnode_modules%5C.prisma%5Cclient++%0A++prisma%3Aengine+stdout++PANIC+in+query-engine%5Cconnectors%5Cmongodb-query-connector%5Csrc%5Clogger.rs%3A160%3A31%0Anot+yet+implemented++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+Error%3A+read+ECONNRESET%0A++prisma%3Aengine+++++++at+TCP.onStreamRead+%28node%3Ainternal%2Fstream_base_commons%3A217%3A20%29+%7B%0A++prisma%3Aengine+++++errno%3A+-4077%2C%0A++prisma%3Aengine+++++code%3A+%27ECONNRESET%27%2C%0A++prisma%3Aengine+++++syscall%3A+%27read%27%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0Amutation+%7B%0A++createOneUser%28data%3A+%7B%0A++++id%3A+%22X%22%0A++%7D%29+%7B%0A++++ObjectId%0A++++createdAt%0A++++id%0A++%7D%0A%7D%0A%60%60%60%0A&title=PANIC+in+query-engine%5Cconnectors%5Cmongodb-query-connector%5Csrc%5Clogger.rs%3A160%3A31%0Anot+yet+implemented&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

    at Object.request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:45582:15)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\12704\node_modules\@prisma\client\runtime\index.js:46405:18)
    at async main (C:\Users\Jan\Documents\throwaway\12704\script.js:6:14) {
  clientVersion: '3.12.0'
}
PS C:\Users\Jan\Documents\throwaway\12704>
```

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
