### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

### ISSUE THREAD

**Issue by redocecin** [prisma/prisma#12737]
Hi Prisma Team! My Prisma Client just crashed. It looks like this is a critical bug because after it happens, no more query is executed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.19.1           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 3.12.0             |
| Query Engine    | 0.1.0              |
| Database        | sqlite             |

## Logs
```
npm run dev

> script@ dev /tmp/starter
> ts-node ./script.ts

thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', query-engine/core/src/query_document/parser.rs:250:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Unexpected PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation in
/tmp/starter/script.ts:8:36

   5 // A `main` function so that you can use async/await
   6 async function main() {
   7   try {
→  8     const user = await prisma.user.findUnique(
  called `Option::unwrap()` on a `None` value
    at Object.request (/tmp/starter/node_modules/@prisma/client/runtime/index.js:45582:15)
    at async PrismaClient._request (/tmp/starter/node_modules/@prisma/client/runtime/index.js:46405:18) {
  clientVersion: '3.12.0'
}
PrismaClientRustPanicError: 
Invalid `prisma.user.findUnique()` invocation in
/tmp/starter/script.ts:16:35

  13 } catch (e) {
  14   console.error("Unexpected", e);
  15 }
→ 16 const user1 = await prisma.user.findUnique(
  PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

ttps://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v14.19.1+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-1.1.x%7C%0A%7C+Prisma+Client+++%7C+3.12.0+++++++++++++%7C%0A%7C+Query+Engine++++%7C+0.1.0++++++++++++++%7C%0A%7C+Database++++++++%7C+sqlite+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0A++prisma%3AtryLoadEnv+Environment+variables+loaded+from+%2Ftmp%2Fstarter%2F.env++%0A++prisma%3AtryLoadEnv+Environment+variables+loaded+from+%2Ftmp%2Fstarter%2F.env++%0A++prisma%3Aclient+dirname++%2Ftmp%2Fstarter%2Fnode_modules%2F.prisma%2Fclient++%0A++prisma%3Aclient+relativePath++..%2F..%2F..%2Fprisma++%0A++prisma%3Aclient+cwd++%2Ftmp%2Fstarter%2Fprisma++%0A++prisma%3Aclient+clientVersion%3A+3.12.0++%0A++prisma%3Aclient+clientEngineType%3A+library++%0A++prisma%3Aclient%3AlibraryEngine+internalSetup++%0A++prisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+false++%0A++prisma%3Aclient%3AlibraryEngine+Searching+for+Query+Engine+Library+in+%2Ftmp%2Fstarter%2Fnode_modules%2F.prisma%2Fclient++%0A++prisma%3Aclient%3AlibraryEngine+loadEngine+using+%2Ftmp%2Fstarter%2Fnode_modules%2F.prisma%2Fclient%2Flibquery_engine-debian-openssl-1.1.x.so.node++%0A++prisma%3Aclient%3AlibraryEngine+library+starting++%0A++prisma%3Aclient%3AlibraryEngine+library+started++%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=PANIC%3A+called+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value+in+query-engine%2Fcore%2Fsrc%2Fquery_document%2Fparser.rs%3A250%3A87&template=bug_report.mdhttps://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v14.19.1+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-1.1.x%7C%0A%7C+Prisma+Client+++%7C+3.12.0+++++++++++++%7C%0A%7C+Query+Engine++++%7C+0.1.0++++++++++++++%7C%0A%7C+Database++++++++%7C+sqlite+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0A++prisma%3AtryLoadEnv+Environment+variables+loaded+from+%2Ftmp%2Fstarter%2F.env++%0A++prisma%3AtryLoadEnv+Environment+variables+loaded+from+%2Ftmp%2Fstarter%2F.env++%0A++prisma%3Aclient+dirname++%2Ftmp%2Fstarter%2Fnode_modules%2F.prisma%2Fclient++%0A++prisma%3Aclient+relativePath++..%2F..%2F..%2Fprisma++%0A++prisma%3Aclient+cwd++%2Ftmp%2Fstarter%2Fprisma++%0A++prisma%3Aclient+clientVersion%3A+3.12.0++%0A++prisma%3Aclient+clientEngineType%3A+library++%0A++prisma%3Aclient%3AlibraryEngine+internalSetup++%0A++prisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+false++%0A++prisma%3Aclient%3AlibraryEngine+Searching+for+Query+Engine+Library+in+%2Ftmp%2Fstarter%2Fnode_modules%2F.prisma%2Fclient++%0A++prisma%3Aclient%3AlibraryEngine+loadEngine+using+%2Ftmp%2Fstarter%2Fnode_modules%2F.prisma%2Fclient%2Flibquery_engine-debian-openssl-1.1.x.so.node++%0A++prisma%3Aclient%3AlibraryEngine+library+starting++%0A++prisma%3Aclient%3AlibraryEngine+library+started++%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=PANIC%3A+called+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value+in+query-engine%2Fcore%2Fsrc%2Fquery_document%2Fparser.rs%3A250%3A87&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at Object.request (/tmp/starter/node_modules/@prisma/client/runtime/index.js:45586:15)
    at async PrismaClient._request (/tmp/starter/node_modules/@prisma/client/runtime/index.js:46405:18) {
  clientVersion: '3.12.0'
}
```

## Client Snippet
```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// A `main` function so that you can use async/await
async function main() {
  try {
    const user = await prisma.user.findUnique({
      where: {
        id: 1111111111111111111111111111111111111111,
      },
    });
  } catch (e) {
    console.error("Unexpected", e);
  }
  const user1 = await prisma.user.findUnique({
    where: {
      id: 1,
    },
  });
  console.log("user", user1);
}

main()
  .catch((e) => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```

## Schema
```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by dpetrick** [comment]
3.15 will ship a change that returns a structured error instead of a panic.

**Comment by redocecin** [comment]
Thanks a lot!
