### ISSUE TITLE
Improve the error when running the tests on unsupported platform

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#12740]
When trying to run the client tests on unsupported binaryTarget (on @cprieto's machine it was `rhel-openssl-3.0.x` — notice OpenSSL 3), it's hard to notice what exactly went wrong because the error just says that it couldn't find the binary in one of the expected paths.

@cprieto could you please post the error message here?

**Comment by cprieto** [comment]
Error message:

```
Could not find libquery-engine binary. Searched in:
    - /home/cprieto/Code/prisma/node_modules/.pnpm/@prisma+engines@3.13.0-2.ba8e3c2c2615e6af9303b3930e7de9377999a0e7/node_modules/@prisma/engines/libquery_engine-rhel-openssl-3.0.x.so.node
    - /home/cprieto/Code/prisma/packages/sdk/libquery_engine-rhel-openssl-3.0.x.so.node
    - /home/cprieto/Code/prisma/packages/libquery_engine-rhel-openssl-3.0.x.so.node
    - /home/cprieto/Code/prisma/packages/sdk/runtime/libquery_engine-rhel-openssl-3.0.x.so.node

      89 |     return maybeCopyToTmp(prismaPath4);
      90 |   }
    > 91 |   throw new Error(`Could not find ${name} binary. Searched in:
         |         ^
      92 | - ${prismaPath}
      93 | - ${prismaPath2}
      94 | - ${prismaPath3}

      at resolveBinary (../sdk/dist/resolveBinary.js:91:9)
      at getConfigNodeAPI (../sdk/dist/engine-commands/getConfig.js:75:27)
      at getConfig (../sdk/dist/engine-commands/getConfig.js:57:12)
      at getTestClient (src/utils/getTestClient.ts:34:18)
      at src/__tests__/integration/happy/composites-mongo/findMany/required.ts:19:20

```

**Comment by janpio** [comment]
We should be able to fail earlier when we construct the "platform" string.

Note: Unsupport SSL version might be a special case here, I _think_ an actually unsupported platform _is_ caught properly.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
