### ISSUE TITLE
I am also receiving the same error, on Ubuntu 22.04 (dev)

### ISSUE THREAD

**Issue by fomenkoyegor** [prisma/prisma#12786]
I am also receiving the same error, on Ubuntu 22.04 (dev)

```
$ npx prisma generate
Error: Unknown binaryTarget debian-openssl-3.0.x and no custom binaries were provided
```

OpenSSL version is 3.0.1 14

```
$ openssl version
OpenSSL 3.0.1 14 Dec 2021 (Library: OpenSSL 3.0.1 14 Dec 2021)
```

Executing "yarn dev" produces 

```
Server is running on http://localhost:4000/
/home/vee/Dev/graphql/hackernews-react-apollo/server/node_modules/@prisma/client/runtime/index.js:36111
      throw new PrismaClientInitializationError(`Unknown ${import_chalk7.default.red("PRISMA_QUERY_ENGINE_LIBRARY")} ${import_chalk7.default.redBright.bold(this.platform)}. Possible binaryTargets: ${import_chalk7.default.greenBright(knownPlatforms.join(", "))} or a path to the query engine library.
            ^

PrismaClientInitializationError: Unknown PRISMA_QUERY_ENGINE_LIBRARY undefined. Possible binaryTargets: darwin, darwin-arm64, debian-openssl-1.0.x, debian-openssl-1.1.x, rhel-openssl-1.0.x, rhel-openssl-1.1.x, linux-arm64-openssl-1.1.x, linux-arm64-openssl-1.0.x, linux-arm-openssl-1.1.x, linux-arm-openssl-1.0.x, linux-musl, linux-nixos, windows, freebsd11, freebsd12, openbsd, netbsd, arm, native or a path to the query engine library.
You may have to run prisma generate for your changes to take effect.
    at Object.getPlatform (/home/vee/Dev/graphql/hackernews-react-apollo/server/node_modules/@prisma/client/runtime/index.js:36111:13)
    at async Object.instantiateLibrary (/home/vee/Dev/graphql/hackernews-react-apollo/server/node_modules/@prisma/client/runtime/index.js:36102:21) {
  clientVersion: '3.8.1',
  errorCode: undefined
}
[nodemon] app crashed - waiting for file changes before starting...
```

_Originally posted by @bopucky in https://github.com/prisma/prisma/issues/11356#issuecomment-1056781743_

**Comment by fomenkoyegor** [comment]
Error: Unknown binaryTarget debian-openssl-3.0.x and no custom binaries were provided

**Comment by vlod** [comment]
@fomenkoyegor were you able to solve this? I'm getting the same problem. Thanks.

**Comment by fomenkoyegor** [comment]
openssl 3 work!!!!!!!!!!!!!!!!!!!!! thank you

**Comment by psdkumar** [comment]
I am also getting the same error on Ubuntu 22.04. @fomenkoyegor Can you help me what did you do to resolve the issue?

`Error: Unknown binaryTarget debian-openssl-3.0.x and no custom binaries were provided`

My OpenSSL Version : OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

**Comment by psdkumar** [comment]
Upgrading the libraries `prisma` and `@prisma/client` to `3.13.0` version resolved the issue for me.

**Comment by stefanpernpaintner** [comment]
After upgrading Ubuntu to 22.04 LTS I ran into the same error as described above. Now I have updated `prisma` and `@prisma/client` to `3.13.0` and I run into another error: 
```
> Downloading Prisma engines for Node-API for debian-openssl-3.0.x [                    ] 0%Error: Not Found https://binaries.prisma.sh/all_commits/22b822189f46ef0dc5c5b503368d1bee01213980/debian-openssl-3.0.x/libquery_engine.so.node.gz
error Command failed with exit code 1.
```
