### ISSUE TITLE
Prisma is not joining tables when making a query with referentialIntegrity feature

### ISSUE THREAD

**Issue by matthewninja** [prisma/prisma#12810]
### Bug description

Our database does not have foreign keys. To maintain relations, we're using `referentialIntegrity`: 
```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}
```

When calling `prisma.foo.update`, where `foo` has a relation with bridge table `foo_bar`. The problem is that prisma is not performing a join between `foo` and `bar` while trying to select data from both tables in one `SELECT` statement.

When I invoke this script:
```ts
  const updated = await prisma.merchant.update({
    where: { id: merchant.id },
    data: { currency: 'USD' },
  });
```
This are the queries logged by prisma:

```sql
BEGIN

SELECT 
  `my-local`.`merchant`.`id` 
FROM 
  `my-local`.`merchant` 
WHERE 
  `my-local`.`merchant`.`id` = ?

SELECT 
  `my-local`.`server`.`id`, 
  `my-local`.`server`.`merchant_id` 
FROM 
  `my-local`.`server` 
WHERE 
  (1=1 AND `my-local`.`server`.`merchant_id` IN (?))

SELECT 
  `my-local`.`refund_event`.`id`, 
  `my-local`.`refund_event`.`merchant_id` 
FROM 
  `my-local`.`refund_event` 
WHERE 
  (1=1 AND `my-local`.`refund_event`.`merchant_id` IN (?))

SELECT 
  `my-local`.`foo`.`id`, 
  `my-local`.`foo`.`merchant_id` 
FROM 
  `my-local`.`foo` 
WHERE 
  (1=1 AND `my-local`.`foo`.`merchant_id` IN (?))

SELECT 
  `my-local`.`foo`.`id`, 
  `my-local`.`foo_bar`.`foo_id`, 
  `my-local`.`foo_bar`.`bar_id` 
FROM 
  `my-local`.`foo_bar` 
WHERE 
  1=0

ROLLBACK
```

The error that follows is:
```
Invalid `prisma.merchant.update()` invocation in 
api/src/merchant/resolvers/mutation/toggleAcceptingOrders.ts:53:45 50 }); 
51 */ 52 → 53 const updated = await prisma.merchant.update( The column `my-local.foo.id` 
does not exist in the current database.
```

Specifically, the error is caused by 
```
SELECT 
  `my-local`.`foo`.`id`, 
  `my-local`.`foo_bar`.`foo_id`, 
  `my-local`.`foo_bar`.`bar_id` 
FROM 
  `my-local`.`foo_bar`
```
A join is needed between foo and foo_bar.

The only thing I've found to work is to disable `referentialIntegrity`.

### How to reproduce

With no foreign keys in your database, enable `referentialIntegrity` in your prisma schema:
```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}
```

Use a table (`merchant`) such that it has a one-to-many relationship with table `foo` and table `foo` has a relation to a bridge table `foo_bar`.

Then, call a `prisma.merchant.update()` and watch the `Invalid `prisma.merchant.update()` invocation` error occur following the same pattern as described above.

### Prisma schema (roughly)

```
model Merchant {
  id               Int      @id @default(autoincrement()) @db.UnsignedInt

  bars             Bar[]
  foos          Foo[]

  @@map("merchant")
}
model Foo {
  id         Int     @id @default(autoincrement()) @db.UnsignedInt

  merchant     Merchant      @relation(fields: [merchantId], references: [id])
  merchantId   Int           @map("merchant_id") @db.UnsignedInt
  fooBars FooBar[]

  @@map("foo")
}
model FooBar {
  bar      Bar    @relation(fields: [barId], references: [id])
  barId    Int     @map("barId") @db.UnsignedInt
  foo   Foo @relation(fields: [fooId], references: [id])
  fooId Int     @map("foo_id") @db.UnsignedInt

  @@id([fooId, barId])
  @@index([barId], map: "bar_id")
  @@map("foo_bar")
}
model Bar {
  id          Int       @id @default(autoincrement()) @db.UnsignedInt

  merchant       Merchant       @relation(fields: [merchantId], references: [id])
  merchantId     Int            @map("merchant_id") @db.UnsignedInt
  fooBars   FooBar[]

  @@map("bar")
}
```

### Environment & setup

- OS: Mac OS 12.2.1 
- Database: MySQL 8.0.28 
- Node.js version: 16.14.2 

### Prisma Version

```
3.9.1
```

**Comment by matthewninja** [comment]
> Can you please provide an example Prisma schema (and potentially sample script) so we have an easier time reproducing this? Thanks.

I've posted a schema and script. Please let me know if more info is needed to re-produce!

**Comment by janpio** [comment]
The schema has a few errors, both `Baz` and `Bar` are not present. The index and id in `FooBar` is also expecting a field `barId` to be present, which is missing. Not sure if I can remove/fix those just like that and not influence your reproduction.

**Comment by matthewninja** [comment]
> The schema has a few errors, both `Baz` and `Bar` are not present. The index and id in `FooBar` is also expecting a field `barId` to be present, which is missing. Not sure if I can remove/fix those just like that and not influence your reproduction.

Apologies! I've been omitting some data in an attempt to simplify, and mistakes were made. I've updated it again, removing `Baz` and adding `Bar`.

**Comment by janpio** [comment]
I can confirm this problem.

This is the schema (where I added a `currency` field additionally to `Merchant`:
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Merchant {
  id       Int    @id @default(autoincrement()) @db.UnsignedInt
  currency String?
  bars     Bar[]
  foos     Foo[]

  @@map("merchant")
}

model Foo {
  id Int @id @default(autoincrement()) @db.UnsignedInt

  merchant   Merchant @relation(fields: [merchantId], references: [id])
  merchantId Int      @map("merchant_id") @db.UnsignedInt
  fooBars    FooBar[]

  @@map("foo")
}

model FooBar {
  bar   Bar @relation(fields: [barId], references: [id])
  barId Int @map("barId") @db.UnsignedInt
  foo   Foo @relation(fields: [fooId], references: [id])
  fooId Int @map("foo_id") @db.UnsignedInt

  @@id([fooId, barId])
  @@index([barId], map: "bar_id")
  @@map("foo_bar")
}

model Bar {
  id Int @id @default(autoincrement()) @db.UnsignedInt

  merchant   Merchant @relation(fields: [merchantId], references: [id])
  merchantId Int      @map("merchant_id") @db.UnsignedInt
  fooBars    FooBar[]

  @@map("bar")
}
```

And my minimal `script.js`:
```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  let merchantId = 5
  const updated = await prisma.merchant.update({
    where: { id: merchantId },
    data: { currency: 'USD' },
  });
}

main()
    .catch((e) => {
    console.error(e)
    process.exit(1)
    })
    .finally(async () => {
    await prisma.$disconnect()
    })
```

Output I get:
```
PS C:\Users\Jan\Documents\throwaway\12810> node .\script.js  
PrismaClientUnknownRequestError: 
Invalid `prisma.merchant.update()` invocation in
C:\Users\Jan\Documents\throwaway\12810\script.js:7:41

   4
   5 async function main() {
   6   let merchantId = 5
→  7   const updated = await prisma.merchant.update(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1105, message: "symbol `12810`.bar.id not found", state: "HY000" })) })
    at Object.request (C:\Users\Jan\Documents\throwaway\12810\node_modules\@prisma\client\runtime\index.js:45582:15)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\12810\node_modules\@prisma\client\runtime\index.js:46405:18)
    at async main (C:\Users\Jan\Documents\throwaway\12810\script.js:7:19) {
  clientVersion: '3.12.0'
}
```

Does this match what you are describing? I notice your error message is different though - I was testing this on PlanetScale which is a bit weird version of MySQL/Vitess that changes the error messages. (Trying to find a playground for plain MySQL 8 now)

If so, this would be another case of https://github.com/prisma/prisma/issues/10758

**Comment by janpio** [comment]
Found one and can confirm your error message:
```
PS C:\Users\Jan\Documents\throwaway\12810> node .\script.js
PrismaClientKnownRequestError: 
Invalid `prisma.merchant.update()` invocation in
C:\Users\Jan\Documents\throwaway\12810\script.js:7:41

   4
   5 async function main() {
   6   let merchantId = 5
→  7   const updated = await prisma.merchant.update(
  The column `12810.bar.id` does not exist in the current database.
    at Object.request (C:\Users\Jan\Documents\throwaway\12810\node_modules\@prisma\client\runtime\index.js:45578:15)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\12810\node_modules\@prisma\client\runtime\index.js:46405:18)
    at async main (C:\Users\Jan\Documents\throwaway\12810\script.js:7:19) {
  code: 'P2022',
  clientVersion: '3.12.0',
  meta: { column: '12810.bar.id' }
}
```

**Comment by janpio** [comment]
I expanded that other issue's title, and posted a comment: https://github.com/prisma/prisma/issues/10758#issuecomment-1098430578

**Comment by matthewninja** [comment]
> 

Thanks for the quick response! Yes, let's close this as a duplicate.
