### ISSUE TITLE
Unable to search using embedded fields in MongoDB

### ISSUE THREAD

**Issue by PinkaminaDianePie** [prisma/prisma#12830]
### Bug description

queries on embedded fields in mongo don't work both on type level and query engine level

### How to reproduce

such a query
```javascript
const res = await prisma.m.findFirst({
  where: {
    a: {
      b: {
        c: 'd'
      }
    }
  },
});
```
doesn't work with such a schema:
```javascript
enum C {
  a
  b
  c
  d
}

type B {
  c          C
  otherField String
}

type A {
  b          B
  otherField String
}

model M {
  id         String @id @default(auto()) @map("_id") @db.ObjectId
  a          A
  otherField String
}
```
I have to specify ALL the fields, not just the ones I want to search with.
So such a query would work:
```javascript
const res = await prisma.m.findFirst({
  where: {
    a: {
      b: {
        c: 'd',
        otherField: 'something'
      },
      otherField: 'something'
    }
  },
});
```
but it makes no sense because I don't know the values of `otherField` in the object I'm looking for

### Expected behavior

All fields in search on embedded fields should be optional, not just on `model` level but in every nested `type` as well.

### Prisma information

-

### Environment & setup

-

### Prisma Version

```
3.12.0
```

**Comment by janpio** [comment]
I can reproduce this:

My slightly simplified schema (no enum):
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

type B {
  c          String
  otherField String
}

type A {
  b          B
  otherField String
}

model M {
  id         String @id @default(auto()) @map("_id") @db.ObjectId
  a          A
  otherField String
}

```

And this data in there:
```
[{
  "_id": {
    "$oid": "62604e8826bbe63d81ffe15c"
  },
  "otherField": "something in M",
  "a": {
    "b": {
      "c": "d",
      "otherField": "something in B"
    },
    "otherField": "something in A"
  }
}]
```

This script fails:
```
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {

  const res = await prisma.m.findFirst({
    where: {
      a: {
        b: {
          c: 'd'
        }
      }
    },
  });

  console.log(res)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

with

```
PS C:\Users\Jan\Documents\throwaway\12830> node .\script.js
PrismaClientValidationError: 
Invalid `prisma.m.findFirst()` invocation:

{
  where: {
    a: {
      b: {
      ~
        c: 'd'
      }
    }
  }
}

Unknown arg `b` in where.a.b for type ACompositeFilter. Available args:

type ACompositeFilter {
  equals?: AObjectEqualityInput
  is?: AWhereInput
  isNot?: AWhereInput
}


    at Object.validate (C:\Users\Jan\Documents\throwaway\12830\node_modules\@prisma\client\runtime\index.js:44374:20)
    at PrismaClient._executeRequest (C:\Users\Jan\Documents\throwaway\12830\node_modules\@prisma\client\runtime\index.js:46458:17)
    at consumer (C:\Users\Jan\Documents\throwaway\12830\node_modules\@prisma\client\runtime\index.js:46402:23)
    at C:\Users\Jan\Documents\throwaway\12830\node_modules\@prisma\client\runtime\index.js:46406:76
    at runInChildSpan (C:\Users\Jan\Documents\throwaway\12830\node_modules\@prisma\client\runtime\index.js:45651:12)
    at C:\Users\Jan\Documents\throwaway\12830\node_modules\@prisma\client\runtime\index.js:46406:20
    at AsyncResource.runInAsyncScope (node:async_hooks:201:9)
    at PrismaClient._request (C:\Users\Jan\Documents\throwaway\12830\node_modules\@prisma\client\runtime\index.js:46405:86)
    at C:\Users\Jan\Documents\throwaway\12830\node_modules\@prisma\client\runtime\index.js:43037:25
    at _callback (C:\Users\Jan\Documents\throwaway\12830\node_modules\@prisma\client\runtime\index.js:42801:52) {
  clientVersion: '3.12.0'
}
```

But this one works:
```
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {

  const res = await prisma.m.findFirst({
    where: {
      a: {
        b: {
          c: 'd',
          otherField: 'something in B'
        },
        otherField: 'something in A'
      }
    },
  });

  console.log(res)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```
returns
```
PS C:\Users\Jan\Documents\throwaway\12830> node .\script.js
{
  a: {
    b: { c: 'd', otherField: 'something in B' },
    otherField: 'something in A'
  },
  id: '62604e8826bbe63d81ffe15c',
  otherField: 'something in M'
}
```

Is this equivalent to what you are seeing @PinkaminaDianePie?

**Comment by PinkaminaDianePie** [comment]
sorry, i simplified all of the fields but for some reason forgot to replace enum with something simpler :D 
yes, that's exactly my issue, thx for checking!

**Comment by dpetrick** [comment]
This is not a bug: The implicit filter you're using is `equals`. What you want is a partial match on the embeds, which is `is`: `where: { a: { is: { b: { is: { c: "d" } } }} }`. For equality, you need a full comparison. If you have a schema that states you have a required field, then the full equals comparison naturally also requires a field to be set, which is what you're seeing.

**Comment by mhabsaoui** [comment]
Hi,
I have the same situation concerning the filtering on composite type key !  

- I am using Prisma for MongoDB, having a model as following (generated with `npx prisma db pull` after some playground on VSCode) :

```javascript
type SubscriptionKeys {
  auth   String
  p256dh String
}

model subscription {
  id             String           @id @default(auto()) @map("_id") @db.ObjectId
  endpoint       String
  expirationTime Float
  keys           SubscriptionKeys
}

```

-  This is an example of data to be inserted into my "suscription" collection

```json
{
  "endpoint": "https://fcm.googleapis.com/fcm/send/d61c5u920dw:APA91bEmnw8utjDYCqSRplFMVCzQMg9e5XxpYajvh37mv2QIlISdasBFLbFca9ZZ4Uqcya0ck-SP84YJUEnWsVr3mwYfaDB7vGtsDQuEpfDdcIqOX_wrCRkBW2NDWRZ9qUz9hSgtI3sY",
  "expirationTime": 1519211809934,
  "keys": {
    "p256dh": "BL7ELU24fJTAlH5Kyl8N6BDCac8u8li_U5PIwG963MOvdYs9s7LSzj8x_7v7RFdLZ9Eap50PiiyF5K0TDAis7t0",
    "auth": "juarI8x__VnHvsOgfeAPHg"
  }
}
```
- I have this get route to delete a subscription, but when trying to filter with when

![image](https://github.com/prisma/prisma/assets/18755135/fd4649ef-fa14-4966-a29c-8f5565c6944a)

 

```bash
Type '{ keys: { is: { auth: string; }; }; }' is not assignable to type 'subscriptionWhereUniqueInput'.
  Type '{ keys: { is: { auth: string; }; }; }' is not assignable to type '{ id: string; } & { id?: string; AND?: subscriptionWhereInput | subscriptionWhereInput[]; OR?: subscriptionWhereInput[]; NOT?: subscriptionWhereInput | subscriptionWhereInput[]; endpoint?: string | StringFilter<...>; expirationTime?: number | FloatFilter<...>; keys?: (Without<...> & SubscriptionKeysObjectEqualityInp...'.
    Property 'id' is missing in type '{ keys: { is: { auth: string; }; }; }' but required in type '{ id: string; }'.
```

Thanks for your feedback :-)

**Comment by mhabsaoui** [comment]
I mean, just like the javascript web API `Array.prototype.filter()` wich filters among a list of objects given a rule, isn't it possible on Mongo database driver ?
