### ISSUE TITLE
PANIC: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" } in /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/blocking/pool.rs:248:14

### ISSUE THREAD

**Issue by Cyl3el2Cleal2** [prisma/prisma#12977]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.14.0           | 
| OS              | linux-musl         |
| Prisma Client   | 3.3.0              |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Logs
```
l:
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.queryRaw(SELECT 1, [])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.queryRaw(SELECT 1, [])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.queryRaw(SELECT 1, [])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.queryRaw(SELECT 1, [])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.queryRaw(SELECT 1, [])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.queryRaw(SELECT 1, [])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.queryRaw(SELECT 1, [])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.queryRaw(SELECT 1, [])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.queryRaw(SELECT 1, [])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.queryRaw(SELECT 1, [])
prisma:client Prisma Client call:
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine graphQLToJSError
prisma:client:request_handler Error: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
    at Object.prismaGraphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:36343:12)
    at Object.request (/app/node_modules/@prisma/client/runtime/index.js:36358:22)
    at async Object.request (/app/node_modules/@prisma/client/runtime/index.js:38869:24)
    at async LetterService.getChatBalanceByPrisonerId (/app/dist/services/letter.service.js:32:24)
    at async LetterController.getChatBalanceByPrisonerId (/app/dist/controllers/letter.controller.js:28:32)
prisma:client:libraryEngine graphQLToJSError
prisma:client:request_handler Error: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
    at Object.prismaGraphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:36343:12)
    at Object.request (/app/node_modules/@prisma/client/runtime/index.js:36358:22)
prisma:client:libraryEngine graphQLToJSError
prisma:client:request_handler Error: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
    at Object.prismaGraphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:36343:12)
    at Object.request (/app/node_modules/@prisma/client/runtime/index.js:36358:22)
prisma:client:libraryEngine graphQLToJSError
prisma:client:request_handler Error: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
    at Object.prismaGraphQLToJSError (/app/node_modules/@prisma/client/runtime/index.js:36343:12)
    at Object.request (/app/node_modules/@prisma/client/runtime/index.js:36358:22)
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by Jolg42** [comment]
Hi @Cyl3el2Cleal2, it's been a while...
Did this only happen once? Does it still happen in a more recent version?
Could you share the code using Prisma Client and your Prisma schema?
Without any additional information, there is probably not much we can investigate.

**Comment by janpio** [comment]
Ping @Cyl3el2Cleal2

**Comment by garrensmith** [comment]
Closing since we haven't heard back and we cannot debug further.
