### ISSUE TITLE
Misleading Error for non-unique relation names

### ISSUE THREAD

**Issue by Haschikeks** [prisma/prisma#12986]
### Bug description

If you have two relations, that use the same name `@relation("a")`, running `prisma format` returns an unspecific error message.

```
Prisma schema loaded from prisma/schema.prisma
thread '<unnamed>' panicked at 'Did not find a relation for model User and field comments', query-engine/prisma-models/src/builders/internal_dm_builder.rs:122:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Unexpected token D in JSON at position 0
error Command failed with exit code 1.
```

Running the command with `DEBUG="*"` give me the following error
```
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
  prisma:getDMMF Using CLI Query Engine (Node-API) at: /Users/***/projects/test/prisma-test/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node +0ms
thread '<unnamed>' panicked at 'Did not find a relation for model User and field comments', query-engine/prisma-models/src/builders/internal_dm_builder.rs:122:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: SyntaxError: Unexpected token D in JSON at position 0
    at JSON.parse (<anonymous>)
    at getDmmfNodeAPI (/Users/***/projects/test/prisma-test/node_modules/prisma/build/index.js:42643:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getDMMF (/Users/***/projects/test/prisma-test/node_modules/prisma/build/index.js:42622:17)
    at async Object.parse (/Users/***/projects/test/prisma-test/node_modules/prisma/build/index.js:113414:5)
    at async main (/Users/***/projects/test/prisma-test/node_modules/prisma/build/index.js:115059:18)
error Command failed with exit code 1.
```

As a note, the VS Code prisma extension, does not throw an Error for this. (Which is somewhat okay for me)

### How to reproduce

Example repository

[https://github.com/Haschikeks/prisma-relation-name-bug](https://github.com/Haschikeks/prisma-relation-name-bug)

If you change the relation to be equal, for example both to `a` and then run `prisma format` the above mentioned error appears.

### Expected behavior

It would be nice, if there was an error message that indicates, that there is a problem with the relation names. This would already help in tracking down the problem.

### Prisma information

Prisma schema:

```
model Post {
  id     String @unique
  userId String
  user   User   @relation("a", fields: [userId], references: [id])
}

model User {
  id       String    @unique
  posts    Post[]    @relation("a")
  comments Comment[] @relation("a")
}

model Comment {
  id     String @unique
  userId String
  user   User   @relation("a", fields: [userId], references: [id])
}

```

### Environment & setup

- OS: Mac OS
- Node.js version: v17.9.0

### Prisma Version

```
prisma                  : 3.12.0
@prisma/client          : Not found
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 22b822189f46ef0dc5c5b503368d1bee01213980 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 22b822189f46ef0dc5c5b503368d1bee01213980
Studio                  : 0.459.0
```

**Comment by Haschikeks** [comment]
@Weakky thank you for attending to this problem. Just a quick follow up question.
With Version 4 we would then be able to have multiple relations that have the same name in the prisma schema?
