### ISSUE TITLE
Upgrading to version 3.13.0 results in error: collection is not iterable

### ISSUE THREAD

**Issue by alucardu** [prisma/prisma#13040]
### Bug description

When upgrading prisma to latest:

"@prisma/client": "^3.13.0",
"prisma": "^3.13.0",

And I run my application I get the error:

```
TypeError: collection is not iterable
    at keyBy (C:\Users\alucardu\Documents\projects\movieseat-react\node_modules\@prisma\client\runtime\index.js:38960:21)
    at Object.getTypeMap (C:\Users\alucardu\Documents\projects\movieseat-react\node_modules\@prisma\client\runtime\index.js:39300:17) 
    at new DMMFHelper (C:\Users\alucardu\Documents\projects\movieseat-react\node_modules\@prisma\client\runtime\index.js:39197:25)    
    at new PrismaClient (C:\Users\alucardu\Documents\projects\movieseat-react\node_modules\@prisma\client\runtime\index.js:46025:22)  
    at Object.<anonymous> (C:\Users\alucardu\Documents\projects\movieseat-react\src\database.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  clientVersion: '3.1.1'
}
```

### How to reproduce

Check out this branch in my repo > https://github.com/alucardu/movieseat-react/tree/issue-252-Allow_user_to_reset_their_password

### Expected behavior

Prisma should not crash.

### Prisma information

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL|
- Node.js version: v14.17.6

### Prisma Version

```
prisma: 3.13.0
```

**Comment by janpio** [comment]
Can you point out the query in your repo that is failing please? Thanks.

**Comment by alucardu** [comment]
@janpio thank you for your reply. There isn't a specific query or mutation that is failing. When I run `node index.js` in my `src` folder the crash happens.

**Comment by janpio** [comment]
It should not. You should also have gotten the validation error when generating the Client with the new version. 
Can you maybe share the problematic model(s) and let us know which Prisma version you ran before?
That way we might be able to reproduce this.

**Comment by SevInf** [comment]
@alucardu Sorry,  I can't reproduce the issue in your repo.  Could you give use more details on your environment?

**Comment by alucardu** [comment]
@SevInf Thank you for checking in. I think the issue was jus that "something" was wrong. After reinstalling my node modules the error was resolved.

**Comment by Jhaamlal** [comment]
`"error": {
    "clientVersion": "3.13.0"
  }`
I  am getting this error even after deleting nofe module and restalling it.

This is repository - https://github.com/Jhaamlal/MemebershipBackend/ 

File in which error = src/authentications/customerAuth.ts
line  to 11-13

while sending post request  at Line 14 in INDEX.ts   `    /Customer`


dummy data you can use to replicate :
`{
    "email":"shank@gmail.com",
    "firstName":"ravi",
    "lastName":"singh",
    "user":{
        "email":"shank@gmail.com",
        "password":"12345678",
        "phone":"9166186442"
    },
    "address":{
        "address_line":"p-124/2 ghotic line",
        "city":"jaipur",
        "state":"Rajsthan",
        "PIN":8002204
    }
}`
