### ISSUE TITLE
prisma doesn't generate client on ./build/ after node ace build --production

### ISSUE THREAD

**Issue by patrickJramos** [prisma/prisma#13143]
### Bug description

I am developing an API using AdonisJS and prisma as the ORM.

everything works on development, while we're using ```node ace serve```, we're able to generate the prisma client and it works perfectly.

however, when we try to build and run the project using 
```
node ace build --production
cd build
npm ci --production
node server.js 
```
the following error shows up: 
```
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/var/www/html/api/build/node_modules/.prisma/client/index.js:3:11)
    at Object.<anonymous> (/var/www/html/api/app/prisma/index.ts:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at ImportAliases.resolve (/var/www/html/api/build/node_modules/@adonisjs/fold/build/src/Ioc/ImportAliases.js:95:23)
    at Ioc.require (/var/www/html/api/build/node_modules/@adonisjs/fold/build/src/Ioc/index.js:294:36)
```
if I try to run ```prisma generate``` inside the build folder, the following warning shows up: 
```
prisma:warn The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
If you have a Prisma schema file in a custom path, you will need to run
`prisma generate --schema=./path/to/your/schema.prisma` to generate Prisma Client.
If you do not have a Prisma schema file yet, you can ignore this message.
```
if i run ```prisma generate --schema=../prisma/schema.prisma``` inside the build folder, it generates the client in the node_modules folder outside of build:
```
Prisma schema loaded from ../prisma/schema.prisma

✔ Generated Prisma Client (3.13.0 | library) to ./../node_modules/@prisma/client in 1.43s
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

```

### How to reproduce

1. create AdonisJS API using prisma
2. everything works properly during development
3. build and run the built application (shows the errors above)

### Expected behavior

The Prisma Client should be generated inside the build folder too

### Prisma information

my schema is fine, the only problem is with building the application
if you still need it I can provide more information later

### Environment & setup

- OS: Ubuntu/Windows
- Database: PostgreSQL
- Node.js version: v14.18.1

### Prisma Version

```
prisma                  : 3.13.0
@prisma/client          : 3.13.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine efdf9b1183dddfd4258cd181a72125755215ab7b (at ../../../../../usr/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli efdf9b1183dddfd4258cd181a72125755215ab7b (at ../../../../../usr/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core efdf9b1183dddfd4258cd181a72125755215ab7b (at ../../../../../usr/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt efdf9b1183dddfd4258cd181a72125755215ab7b (at ../../../../../usr/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : efdf9b1183dddfd4258cd181a72125755215ab7b
Studio                  : 0.459.0
```

**Comment by millsp** [comment]
Hey @patrickJramos :wave: Building with Adonis for production will likely differ from dev mode, have you tried outputting with a custom output path?
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#specify-a-custom-output-location-for-prisma-client
With this, you could generate your PrismaClient somewhere else than the default `node_modules`.

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
