### ISSUE TITLE
`prisma generate` doesn't work on Windows. Errors with `Could not resolve @prisma/client in the current project.`

### ISSUE THREAD

**Issue by HitoriSensei** [prisma/prisma#13166]
### Bug description

While trying to use `prisma generate` on Windows platform I've stumbled upon the issue that I couldn't resolve:

```
❯ prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: Could not resolve @prisma/client in the current project. Please install it with yarn add @prisma/client, and rerun prisma generate 🙏.
```

`dependencies` in project's `package.json` include:
```
"@prisma/client": "^3.13.0",
"prisma": "^3.13.0",
```

The issue happened both when using `yarn` and `npm`.

The issue seems to be caused by incorrectly resolved path to `@prisma/client`

Resolved path: `C:\Users\Hitori\WebstormProjects\nest-playground\prisma\node_modules\@prisma\client`
Correct path: `C:\Users\Hitori\WebstormProjects\nest-playground\node_modules\@prisma\client`

I've traced the bug's root to `resolve` package in `resolvePkg` function:https://github.com/prisma/prisma/blob/7fe166c036d1bbc4d283bce07f6690533cb82543/packages/sdk/src/utils/resolve.ts#L16-L17

Changing the line #17 from 
```
const resolvedPath = await resolve(`${id}/package.json`, options)
```
to
```
const resolvedPath = require.resolve(`${id}/package.json`)
```
seems to fix the problem.

After the change I was able to run `prisma generate`.

Full debug log:
```
❯ DEBUG='*' prisma generate
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv project root found at C:\Users\Hitori\WebstormProjects\nest-playground\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Hitori\WebstormProjects\nest-playground\.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: C:\Users\Hitor
i\WebstormProjects\nest-playground\node_modules\prisma\query_engine-windows.dll.node +0ms
  prisma:getDMMF Using CLI Query Engine (Node-API) at: C:\Users\Hitori\WebstormProjects\nest-playground\node_modules\prisma\query_engine-windows.dll.node +0ms
  prisma:generator prismaCLIDir C:\Users\Hitori\WebstormProjects\nest-playground\node_modules\prisma +0ms
  prisma:generator prismaClientDir C:\Users\Hitori\WebstormProjects\nest-playground\prisma\node_modules\@prisma\client +0ms
  prisma:generator baseDir C:\Users\Hitori\WebstormProjects\nest-playground\prisma +0ms
  prisma:generator typescriptPath C:\Users\Hitori\WebstormProjects\nest-playground\node_modules\typescript +2ms
Error: Error: Could not resolve @prisma/client in the current project. Please install it with yarn add @prisma/client, and rerun prisma generate 🙏.
    at prisma-client-js (C:\Users\Hitori\WebstormProjects\nest-playground\node_modules\prisma\build\index.js:43906:19)
    at async generators.stopOnError (C:\Users\Hitori\WebstormProjects\nest-playground\node_modules\prisma\build\index.js:45591:22)
    at async C:\Users\Hitori\WebstormProjects\nest-playground\node_modules\prisma\build\index.js:17655:32
```

Full debug log after the change (note the correct `prismaClientDir`):
```
❯ DEBUG='*' prisma generate
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv project root found at C:\Users\Hitori\WebstormProjects\nest-playground\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Hitori\WebstormProjects\nest-playground\.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: C:\Users\Hitor
i\WebstormProjects\nest-playground\node_modules\prisma\query_engine-windows.dll.node +0ms
  prisma:getDMMF Using CLI Query Engine (Node-API) at: C:\Users\Hitori\WebstormProjects\nest-playground\node_modules\prisma\query_engine-windows.dll.node +0ms
  prisma:generator prismaCLIDir C:\Users\Hitori\WebstormProjects\nest-playground\node_modules\prisma +0ms
  prisma:generator prismaClientDir C:\Users\Hitori\WebstormProjects\nest-playground\node_modules\@prisma\client +0ms
  prisma:generator baseDir C:\Users\Hitori\WebstormProjects\nest-playground\prisma +1ms
  prisma:generator typescriptPath C:\Users\Hitori\WebstormProjects\nest-playground\node_modules\typescript +1ms
  prisma:GeneratorProcess 2022-05-04T19:31:34.756Z prisma:client:generator requiredEngine: libqueryEngine +0ms
  prisma:getGenerators neededVersions {
  "efdf9b1183dddfd4258cd181a72125755215ab7b": {
    "engines": [
      "libqueryEngine"
    ],
    "binaryTargets": []
  }
} +0ms
  prisma:getGenerators {
  prisma:getGenerators   generatorBinaryPaths: {
  prisma:getGenerators     libqueryEngine: {
  prisma:getGenerators       windows: 'C:\\Users\\Hitori\\WebstormProjects\\nest-playground\\node_modules\\prisma\\query_engine-windows.dll.node'
  prisma:getGenerators     }
  prisma:getGenerators   }
  prisma:getGenerators } +80ms
  prisma:GeneratorProcess 2022-05-04T19:31:34.873Z prisma:loadEnv project root found at C:\Users\Hitori\WebstormProjects\nest-playground\package.json +117ms  
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Hitori\WebstormProjects\nest-playground\.env +0ms

✔ Generated Prisma Client (3.13.0 | library) to .\node_modules\@prisma\client in 247ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

  prisma:getConfig Using CLI Query Engine (Node-API Library) at: C:\Users\Hitor
i\WebstormProjects\nest-playground\node_modules\@prisma\engines\query_engine-windows.dll.node +827ms

```

### How to reproduce

1. `yarn add prisma`
2. `yarn add @prisma/client`
3. `prisma init`
4. make some prisma schema
5. `prisma generate`

### Expected behavior

`prisma generate` executes without error

### Prisma information
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Role {
    id Int @default(autoincrement()) @id
    name String
    users User[]
}

model User {
    id Int @default(autoincrement()) @id
    name String @unique
    roles Role[]
}
```

### Environment & setup

- OS: Windows
- Database: SQLite
- Node.js version: v18.0.0

### Prisma Version

```
❯ prisma -v
Environment variables loaded from .env
prisma                  : 3.13.0
@prisma/client          : 3.13.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules\@prisma\engines\migration-engine-windows.exe)        
Introspection Engine    : introspection-core efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules\@prisma\engines\introspection-engine-windows.exe)      
Format Binary           : prisma-fmt efdf9b1183dddfd4258cd181a72125755215ab7b (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : efdf9b1183dddfd4258cd181a72125755215ab7b
Studio                  : 0.459.0

```

**Comment by HitoriSensei** [comment]
Looks like I didn't notice that I've accidentally called a `npm add @prisma/client` from a schema directory, which created another `package.json` and `node_modules` inside `nest-playground/prisma` directory.

After clearing the schema directory (by removing the `node_modules` and `package.json` from  `nest-playground/prisma`) , the `prisma generate` worked properly.
