### ISSUE TITLE
Interactive Transactions Broken as of 3.13

### ISSUE THREAD

**Issue by YaakovR** [prisma/prisma#13192]
### Bug description

Interactive transactions stopped working for me upon updating to 3.13. This worked in 2.12

I'm getting the following error:
```
Error: Failed to convert napi `string` into rust type `String`
    at Object.transaction (/usr/src/app/node_modules/@prisma/client/runtime/index.js:41312:64)
    at async Proxy._transactionWithCallback (/usr/src/app/node_modules/@prisma/client/runtime/index.js:46414:21)
```

### How to reproduce

Schema:
```
model Person {
  id   Int    @id @default(autoincrement())
  name String
}
```

Function:
```
router.post('/person', (req, res, next) => {

  prisma.$transaction(async (prisma) => {
    const person = await prisma.person.create({
      data: {
        name: 'A new role',
      },
    });

    // Do something else

    return person;
  }).then(person => res.status(201).json(person))
    .catch(next);
});
```

### Prisma information

See in "How to reproduce" section.

### Environment & setup

- OS: Ubuntu
- Database: SQL Server
- Node.js version: 17

### Prisma Version

```
3.13
```

**Comment by janpio** [comment]
I converted your snippet into this minimal `script.js`:
```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

async function main() {
  prisma.$transaction(async (prisma) => {
    const person = await prisma.person.create({
      data: {
        name: 'A new role',
      },
    });

    // Do something else

    return person;
  }).then(person => {
    console.log("person", person)
  })
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

with this Prisma Schema:
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

model Person {
  id   Int    @id @default(autoincrement())
  name String
}
```

Running this with `node script.js` I get pretty much the expected output:
```
PS C:\Users\Jan\Documents\throwaway\13192> node .\script.js   
person { id: 1, name: 'A new role' }
```

Am I missing something?

**Comment by YaakovR** [comment]
After testing, it seems that the reason for the error is because I'm extending the String prototype.
```
String.prototype.twice = function() {
  return this.repeat(2);
};
```
This was not an issue in Prisma 3.12. Am I doing something wrong?

**Comment by janpio** [comment]
Can confirm the crash and also that downgrading fixes it:
```
PS C:\Users\Jan\Documents\throwaway\13192> node .\script.js
C:\Users\Jan\Documents\throwaway\13192\node_modules\@prisma\client\runtime\index.js:41312
      result = await ((_c = this.engine) == null ? void 0 : _c.startTransaction(jsonOptions, "{}"));
                                                               ^

Error: Failed to convert napi `string` into rust type `String`
    at Object.transaction (C:\Users\Jan\Documents\throwaway\13192\node_modules\@prisma\client\runtime\index.js:41312:64)
    at async Proxy._transactionWithCallback (C:\Users\Jan\Documents\throwaway\13192\node_modules\@prisma\client\runtime\index.js:46414:21) {
  code: 'StringExpected'
}
PS C:\Users\Jan\Documents\throwaway\13192> npm install prisma@3.12.0 @prisma/client@3.12.0

removed 1 package, changed 4 packages, and audited 5 packages in 13s

found 0 vulnerabilities
PS C:\Users\Jan\Documents\throwaway\13192> node .\script.js
person { id: 2, name: 'A new role' }
PS C:\Users\Jan\Documents\throwaway\13192> 
```

This seems unintended and unexpected. Probably some side effect we did not consider.

**Comment by YaakovR** [comment]
After testing on Prisma 3.15, it seems like this issue is fixed.
Can you confirm this to be the case?

**Comment by YaakovR** [comment]
Either way, I won't complain! 😄

**Comment by cprieto** [comment]
I am closing this issue now, it was fixed as part of the work with tracing in this PR https://github.com/prisma/prisma-engines/pull/2924
