### ISSUE TITLE
MySQL: PANIC: Expected parent IDs to be set when ordering by parent ID. in query-engine/core/src/interpreter/query_interpreters/inmemory_record_processor.rs:71:18

### ISSUE THREAD

**Issue by grandff** [prisma/prisma#13279]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.22.10          | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 3.11.0             |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Logs
```
B%2C%5D%22%2C+%22%22%29+AS+accumulatedTradingVolume%2C++REGEXP_REPLACE%28marketValue%2C+%22%5B%2C%5D%22%2C+%22%22%29+AS+marketValue%2C+localTradedAt+from+UsaStockData+where+localTradedAt+%3D+%28select+max%28localTradedAt%29+from+UsaStockData%29%29+A+LEFT+JOIN+StockDictionary+B+ON+A.symbolCode+%3D+B.symbolCode++ORDER+BY+A.closePrice%2B0+desc+limit+%3F+offset+%3F+%2C+%5B10%2C0%5D%29%0Aprisma%3Aclient+Prisma+Client+call%3A%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+false%0Aprisma%3Aclient%3AlibraryEngine+library+starting%0Aprisma%3Aclient%3AlibraryEngine+library+started%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient+prisma.queryRaw%28SELECT+A.*%2C+B.stockName+as+stockNameKor%2C+B.stockNameEng+as+stockNameOrigin+FROM+%28SELECT+gubun%2C+reutersCode%2C+symbolCode%2C+stockName%2C+stockNameEng%2C+REGEXP_REPLACE%28closePrice%2C+%22%5B%2C%5D%22%2C+%22%22%29+AS+closePrice%2C+REGEXP_REPLACE%28compareToPreviousClosePrice%2C+%22%5B%2C%5D%22%2C+%22%22%29+AS+compareToPreviousClosePrice%2C++REGEXP_REPLACE%28fluctuationsRatio%2C+%22%5B%2C%5D%22%2C+%22%22%29+AS+fluctuationsRatio%2C++REGEXP_REPLACE%28accumulatedTradingVolume%2C+%22%5B%2C%5D%22%2C+%22%22%29+AS+accumulatedTradingVolume%2C++REGEXP_REPLACE%28marketValue%2C+%22%5B%2C%5D%22%2C+%22%22%29+AS+marketValue%2C+localTradedAt+from+UsaStockData+where+localTradedAt+%3D+%28select+max%28localTradedAt%29+from+UsaStockData%29%29+A+LEFT+JOIN+StockDictionary+B+ON+A.symbolCode+%3D+B.symbolCode++ORDER+BY+A.accumulatedTradingVolume%2B0+desc+limit+%3F+offset+%3F+%2C+%5B10%2C0%5D%29%0Aprisma%3Aclient+Prisma+Client+call%3A%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient+prisma.queryRaw%28SELECT+A.*%2C+B.stockName+as+stockNameKor%2C+B.stockNameEng+as+stockNameOrigin+FROM+%28SELECT+gubun%2C+reutersCode%2C+symbolCode%2C+stockName%2C+stockNameEng%2C+REGEXP_REPLACE%28closePrice%2C+%22%5B%2C%5D%22%2C+%22%22%29+AS+closePrice%2C+REGEXP_REPLACE%28compareToPreviousClosePrice%2C+%22%5B%2C%5D%22%2C+%22%22%29+AS+compareToPreviousClosePrice%2C++REGEXP_REPLACE%28fluctuationsRatio%2C+%22%5B%2C%5D%22%2C+%22%22%29+AS+fluctuationsRatio%2C++REGEXP_REPLACE%28accumulatedTradingVolume%2C+%22%5B%2C%5D%22%2C+%22%22%29+AS+accumulatedTradingVolume%2C++REGEXP_REPLACE%28marketValue%2C+%22%5B%2C%5D%22%2C+%22%22%29+AS+marketValue%2C+localTradedAt+from+UsaStockData+where+localTradedAt+%3D+%28select+max%28localTradedAt%29+from+UsaStockData%29%29+A+LEFT+JOIN+StockDictionary+B+ON+A.symbolCode+%3D+B.symbolCode++ORDER+BY+A.fluctuationsRatio%2B0+ASC+limit+%3F+offset+%3F+%2C+%5B10%2C0%5D%29%0Aprisma%3Aclient+Prisma+Client+call%3A%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3Arequest_handler+Error%3A+Expected+parent+IDs+to+be+set+when+ordering+by+parent+ID.%0A++++at+prismaGraphQLToJSError+%28%2Fhome%2Fubuntu%2Fcunning-stock%2Finsider-backend%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A33924%3A10%29%0A++++at+Object.request+%28%2Fhome%2Fubuntu%2Fcunning-stock%2Finsider-backend%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A35748%3A17%29%0A++++at+async+Object.request+%28%2Fhome%2Fubuntu%2Fcunning-stock%2Finsider-backend%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A39788%3A24%29%0A++++at+async+PrismaClient._request+%28%2Fhome%2Fubuntu%2Fcunning-stock%2Finsider-backend%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A40646%3A18%29%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=PANIC%3A+Expected+parent+IDs+to+be+set+when+ordering+by+parent+ID.+in+query-engine%2Fcore%2Fsrc%2Finterpreter%2Fquery_interpreters%2Finmemory_record_processor.rs%3A71%3A18&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at Object.logger (/home/ubuntu/cunning-stock/insider-backend/node_modules/@prisma/client/runtime/index.js:35615:30)
    at /home/ubuntu/cunning-stock/insider-backend/node_modules/@prisma/client/runtime/index.js:35584:34
prisma:client:request_handler Error: Expected parent IDs to be set when ordering by parent ID.
    at prismaGraphQLToJSError (/home/ubuntu/cunning-stock/insider-backend/node_modules/@prisma/client/runtime/index.js:33924:10)
    at Object.request (/home/ubuntu/cunning-stock/insider-backend/node_modules/@prisma/client/runtime/index.js:35748:17)
    at async Object.request (/home/ubuntu/cunning-stock/insider-backend/node_modules/@prisma/client/runtime/index.js:39788:24)
    at async PrismaClient._request (/home/ubuntu/cunning-stock/insider-backend/node_modules/@prisma/client/runtime/index.js:40646:18)
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by Weakky** [comment]
Hey @grandff,

Would you mind sharing a minimal Prisma Schema + client snippet so that we could reproduce your bug? 

Thank you 🙏

**Comment by businessengine** [comment]
We got the same issue.
```Bsending%2Brequest%252C%2Bthis.libraryStarted%253A%2Btrue%250Aprisma%253Aclient%253AlibraryEngine%2Bsending%2Brequest%252C%2Bthis.libraryStarted%253A%2Btrue%250Aprisma%253Aclient%253AlibraryEngine%2Bsending%2Brequest%252C%2Bthis.libraryStarted%253A%2Btrue%250Aprisma%253Aclient%253AlibraryEngine%2Bsending%2Brequest%252C%2Bthis.libraryStarted%253A%2Btrue%250Aprisma%253Aclient%253AlibraryEngine%2Bsending%2Brequest%252C%2Bthis.libraryStarted%253A%2Btrue%250Aprisma%253Aclient%253AlibraryEngine%2Bsending%2Brequest%252C%2Bthis.libraryStarted%253A%2Btrue%250A%2560%2560%2560%250A%250A%2523%2523%2BClient%2BSnippet%250A%2560%2560%2560ts%250A%252F%252F%2BPLEASE%2BFILL%2BYOUR%2BCODE%2BSNIPPET%2BHERE%250A%2560%2560%2560%250A%250A%2523%2523%2BSchema%250A%2560%2560%2560prisma%250A%252F%252F%2BPLEASE%2BADD%2BYOUR%2BSCHEMA%2BHERE%2BIF%2BPOSSIBLE%250A%2560%2560%2560%250A%250A%2523%2523%2BPrisma%2BEngine%2BQuery%250A%2560%2560%2560%250A%257B%2522X%2522%253A%257B%257D%257D%250A%2560%2560%2560%250A%26title%3DPANIC%253A%2BExpected%2Bparent%2BIDs%2Bto%2Bbe%2Bset%2Bwhen%2Bordering%2Bby%2Bparent%2BID.%2Bin%2Bquery-engine%252Fcore%252Fsrc%252Finterpreter%252Fquery_interpreters%252Finmemory_record_processor.rs%253A71%253A18%26template%3Dbug_report.md%0A%0AIf+you+want+the+Prisma+team+to+look+into+it%2C+please+open+the+link+above+%F0%9F%99%8F%0ATo+increase+the+chance+of+success%2C+please+post+your+schema+and+a+snippet+of%0Ahow+you+used+Prisma+Client+in+the+issue.+%0A%0A++++at+Object.logger+%28%2Fvar%2Ftask%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A41425%3A30%29%0A++++at+%2Fvar%2Ftask%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A41394%3A34%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=PANIC%3A+Expected+parent+IDs+to+be+set+when+ordering+by+parent+ID.+in+query-engine%2Fcore%2Fsrc%2Finterpreter%2Fquery_interpreters%2Finmemory_record_processor.rs%3A71%3A18&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at Object.request (/var/task/node_modules/@prisma/client/runtime/index.js:45637:15)
    at async /var/task/dist/apps/api/.next/server/chunks/22.js:265:18
    at async /var/task/dist/apps/api/.next/server/chunks/22.js:1322:18
    at async /var/task/dist/apps/api/.next/server/chunks/22.js:1277:18
    at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:46456:18)
    at async Promise.all (index 1)
    at async <removed due to sensitive data>) {
  clientVersion: '3.13.0'
}
END RequestId: c55cb16d-1f36-4cac-a4d3-b3f32ab46341
REPORT RequestId: c55cb16d-1f36-4cac-a4d3-b3f32ab46341	Duration: 511.10 ms	Billed Duration: 512 ms	Memory Size: 1024 MB	Max Memory Used: 226 MB```

**Comment by janpio** [comment]
Same question as what @Weakky posted above then for you @businessengine:
> Would you mind sharing a minimal Prisma Schema + client snippet so that we could reproduce your bug?

**Comment by businessengine** [comment]
> Same question as what @Weakky posted above then for you @businessengine:
> 
> > Would you mind sharing a minimal Prisma Schema + client snippet so that we could reproduce your bug?

Sure, can you please send me your email? Thanks.

**Comment by businessengine** [comment]
@janpio we have invited you to access the repo with our schema and client code to reproduce the issue. Unfortunately, it is not always happened, weird!

**Comment by businessengine** [comment]
@janpio are you going to check it?
<img width="791" alt="image" src="https://user-images.githubusercontent.com/578995/169733889-26041d41-a5c7-40c4-944e-6ddc4fe1b680.png">

**Comment by pantharshit00** [comment]
@businessengine Hey, Can you send the invite to me?

**Comment by janpio** [comment]
I was out last week. Would be helpful if you indeed you invite @pantharshit00 as well @businessengine - as I will be out in a few days again for a bit longer. Thanks.

**Comment by businessengine** [comment]
Hi @janpio thanks for the info. We did invite @pantharshit00 already. Thank guys.

**Comment by businessengine** [comment]
G'day @pantharshit00, is there any update on this issue? Thank you!

**Comment by pantharshit00** [comment]
Hello @businessengine 

Sorry, yesterday was a public holiday here so I was out. 

I did try to reproduce the problem but I could not do it: 
<img width="929" alt="image" src="https://user-images.githubusercontent.com/22195362/170676500-f316e452-df2a-4d34-90ab-764cb0082cc0.png">


Can you tell me the exact route which will trigger the panic? I think I might have missed it.

**Comment by Weakky** [comment]
@businessengine Any chance you could point us in the right direction? 🙏

**Comment by janpio** [comment]
Ping @businessengine - can you help us out here? We need more information to be able to reproduce this. Otherwise we will unfortunately have to close this issue and wait until someone else reports it again. Thanks.

**Comment by janpio** [comment]
One more tiem @businessengine and @grandff - can you please help us out? We would really love to be able to reproduce this, but are lacking the information to do so for now. Thanks.

**Comment by janpio** [comment]
Closing then until someone provides more information. Please comment or open a new issue. Thanks!
