### ISSUE TITLE
PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

### ISSUE THREAD

**Issue by rajesh-technoidentity** [prisma/prisma#13293]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.14.2           | 
| OS              | rhel-openssl-1.0.x |
| Prisma Client   | 3.13.0             |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Logs
```
s.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:libraryEngine requestBatch
prisma:client:request_handler Error: called `Option::unwrap()` on a `None` value
    at prismaGraphQLToJSError (/var/app/current/node_modules/@prisma/client/runtime/index.js:39695:10)
    at Object.requestBatch (/var/app/current/node_modules/@prisma/client/runtime/index.js:41592:15)
prisma:client:request_handler Error: called `Option::unwrap()` on a `None` value
    at prismaGraphQLToJSError (/var/app/current/node_modules/@prisma/client/runtime/index.js:39695:10)
    at Object.requestBatch (/var/app/current/node_modules/@prisma/client/runtime/index.js:41592:15)
prisma:client:libraryEngine requestBatch
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":true}
```

**Comment by rajesh-technoidentity** [comment]
> 

No, issue disappeared once server restarted, but cause for this issue is not found neither solution :(

**Comment by kasir-barati** [comment]
@rajesh-technoidentity maybe this helps you: https://github.com/prisma/prisma/issues/10586#issuecomment-1134788364

**Comment by dpetrick** [comment]
3.15 will ship a change that returns a structured error instead of a panic.
