### ISSUE TITLE
PrismaClientInitializationError: Server has closed the connection. SQLServer 2016

### ISSUE THREAD

**Issue by Flusinerd** [prisma/prisma#13305]
### Bug description

I am unable to connect to our SQLServer 2016 using prisma:
I am using prisma ``3.14.0``. We want to migrate from typeorm, which can connect to the DB just fine.

Our connection string looks like this:
```
DATABASE_URL="sqlserver://<host>:1433;user=<user>;password=<password>;database=<DB_NAME>;encrypt=false;integratedSecurity=false;trustServerCertificate=true"
```

When I try to run ``prisma db pull`` I get the following error:
```
yarn prisma db pull 
yarn run v1.22.18
$ /Users/jan/Dev/monorepo/node_modules/.bin/prisma db pull
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
  prisma:loadEnv project root found at /Users/jan/Dev/monorepo/package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from /Users/jan/Dev/monorepo/.env +0ms
Environment variables loaded from .env
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: /Users/jan/Dev/monorepo/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node +0ms
Datasource "db" - SQL Server
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: /Users/jan/Dev/monorepo/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node +12ms

⠋ Introspecting based on datasource defined in prisma/schema.prisma  prisma:introspectionEngine:rpc starting introspection engine with binary: /Users/jan/Dev/monorepo/node_modules/@prisma/engines/introspection-engine-darwin +0ms
  prisma:introspectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider = \"sqlserver\"\n  url      = env(\"DATABASE_URL\")\n}\n\nmodel User {\n  id        Int @id @default(autoincrement())\n  name      String\n  email     String\n  password  String\n}\n","compositeTypeDepth":-1}]} +12ms
⠴ Introspecting based on datasource defined in prisma/schema.prisma  prisma:introspectionEngine:rpc {
  prisma:introspectionEngine:rpc   jsonrpc: '2.0',
  prisma:introspectionEngine:rpc   error: {
  prisma:introspectionEngine:rpc     code: 4466,
  prisma:introspectionEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:introspectionEngine:rpc     data: {
  prisma:introspectionEngine:rpc       is_panic: false,
  prisma:introspectionEngine:rpc       message: 'Error in connector: Error querying the database: Error querying the database: The server terminated the connection.',
  prisma:introspectionEngine:rpc       backtrace: null
  prisma:introspectionEngine:rpc     }
  prisma:introspectionEngine:rpc   },
  prisma:introspectionEngine:rpc   id: 1
  prisma:introspectionEngine:rpc } +447ms
✖ Introspecting based on datasource defined in prisma/schema.prisma

Error: Error: Error in connector: Error querying the database: Error querying the database: The server terminated the connection.

    at Object.<anonymous> (/Users/jan/Dev/monorepo/node_modules/prisma/build/index.js:51989:29)
    at Object.handleResponse (/Users/jan/Dev/monorepo/node_modules/prisma/build/index.js:51867:38)
    at LineStream4.<anonymous> (/Users/jan/Dev/monorepo/node_modules/prisma/build/index.js:51945:20)
    at LineStream4.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at LineStream4.Readable.push (node:internal/streams/readable:228:10)
    at LineStream4._pushBuffer (/Users/jan/Dev/monorepo/node_modules/prisma/build/index.js:51710:21)
    at LineStream4._transform (/Users/jan/Dev/monorepo/node_modules/prisma/build/index.js:51704:12)
    at LineStream4.Transform._write (node:internal/streams/transform:184:23)
error Command failed with exit code 1.
```

### How to reproduce

- Setup like above with SQLServer 2016
- Try to connect to the DB

### Expected behavior

Connection should be established

### Prisma information

The datasource configuration looks like this:
```
datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: Mac OS
- Database: SQLServer 2016 (13.0.63)
- Node.js version: 16.15.0

### Prisma Version

```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

**Comment by janpio** [comment]
Do the SQL Server logs have any indication why the server might terminate that connection?

**Comment by pip8786** [comment]
I don't get nearly the amount of logs as @Flusinerd but I have a similar issue. I upgraded from 3.12 (everything works fine) to 3.14 and get this:
```
$ yarn prisma db push
yarn run v1.22.19
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db" - SQL Server

Error: P1017: Server has closed the connection.
error Command failed with exit code 1.
```
and
```
yarn prisma db pull
yarn run v1.22.19
Prisma schema loaded from prisma/schema.prisma
Environment variables loaded from prisma/.env
Datasource "db" - SQL Server

✖ Introspecting based on datasource defined in prisma/schema.prisma

Error: Error in connector: Error querying the database: Error querying the database: The server terminated the connection.

error Command failed with exit code 1.
```
If I revert back to 3.12 things work as expected again (I do have to revert my yarn.lock and I think delete my node_modules for it to work).

**Comment by pip8786** [comment]
I just tried 3.13 to see if I could pinpoint the release that it stopped working and it didn't work on there either. So something between 3.12 and 3.13 causes the SQL Server connection to close for the same DB, URL, command, schema.

**Comment by janpio** [comment]
So a simple `db push` or `db pull` for a SQL Server 2016 should work in 3.12, but fail in 3.13?

**Comment by pip8786** [comment]
Yep, just tested it this morning, all other conditions were the same.

**Comment by janpio** [comment]
Prisma unfortunately officially only support SQL Server 2017 upwards:
https://www.prisma.io/docs/reference/database-reference/supported-databases

We do not really want to invest more time in 2016 - sorry.

**Comment by pip8786** [comment]
@janpio could you point be to where the code is for connecting to SQL server is in particular? I'd just want to see what changed between 3.12 and 3.13.

**Comment by janpio** [comment]
The relevant part if in Migration or Introspection Engine, relevant diff is here: https://github.com/prisma/prisma-engines/compare/3.12.0...3.13.0 Connection logic is probably pulled in via a dependency, quaint and/or tiberius (our SQL Server driver).
