### ISSUE TITLE
CLI Throws Error  "Invalid name: './' ". When typing any of the commands after Prisma initialization

### ISSUE THREAD

**Issue by boringslav** [prisma/prisma#13386]
### Bug description

Bug when trying to run `npx prisma <any-command>` after initializing prisma using `npx prisma init` in a NX monorepo with NestJS. When any of the commands run, there is an error "Invalid name:'./' "
![image](https://user-images.githubusercontent.com/56162273/168578020-ea2a8bc4-3ecb-4f39-985c-9cd3fa64f92c.png)

### How to reproduce

1. Set Up an Nx repo with nestjs
3. Initialize prisma
4. Add your DB connection link
5. create a model
6. run npx migrate dev -> you will see Error: Invalid name: "./"

### Expected behavior

The CLI should run the command and create the migration

### Prisma information

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
model Product {
  id          String @id @default(cuid())
  name        String
  description String
  image       String
  price       Int
}

### Environment & setup

- OS: Windows 11
- Database: PostgreSQL running inside of a Docker container
- Node.js version: 16.10.0

### Prisma Version

```

```
![image](https://user-images.githubusercontent.com/56162273/168579130-9f33ecdd-85ab-4ebe-bc1a-0285f2487ac3.png)

**Comment by janpio** [comment]
Can you activate the env var `DEBUG=*` (`set DEBUG=*` in Cmd, `$env:DEBUG="*"` )?

**Comment by myas92** [comment]
Based on [npm Docs][1]

> The "name" field contains your package's name, and must be lowercase and one word, and may contain hyphens and underscores.

So change package.json's name in your project with a valid name like the below example
```
"name": "project-name"
```


  [1]: https://docs.npmjs.com/creating-a-package-json-file

**Comment by janpio** [comment]
Is your project called `./` right now @boringslav?

**Comment by juan-belmonte** [comment]
I'm facing the same issue in the same scenario (a NestJS application in a Nx-managed monorepo).
The root cause is, as mentioned above, the `package.json` file containing an organization-scoped name (`@project/shared/whatever`).

Here's the output when enabling debug:
```sh
$ DEBUG=* npx prisma generate
  prisma:engines  binaries to download libquery-engine, migration-engine +0ms
  prisma:loadEnv  project root found at /Users/juan/git/my-proj/libs/shared/data-access-persistence/package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/juan/git/my-proj/libs/shared/data-access-persistence/.env +0ms
Environment variables loaded from .env
Error: Error: Invalid name: "@project/shared/persistence"
    at ensureValidName (/Users/juan/git/my-proj/node_modules/prisma/build/index.js:11336:15)
    at Object.fixNameField (/Users/juan/git/my-proj/node_modules/prisma/build/index.js:11232:9)
    at /Users/juan/git/my-proj/node_modules/prisma/build/index.js:11541:42
    at Array.forEach (<anonymous>)
    at normalize (/Users/juan/git/my-proj/node_modules/prisma/build/index.js:11540:19)
    at module2.exports (/Users/juan/git/my-proj/node_modules/prisma/build/index.js:11571:28)
    at async module2.exports (/Users/juan/git/my-proj/node_modules/prisma/build/index.js:11604:22)
    at async getPrismaConfigFromPackageJson (/Users/juan/git/my-proj/node_modules/prisma/build/index.js:86733:19)
    at async getSchemaPathFromPackageJson (/Users/juan/git/my-proj/node_modules/prisma/build/index.js:86745:24)
    at async getSchemaPathInternal (/Users/juan/git/my-proj/node_modules/prisma/build/index.js:86725:23)
```

Replacing the name to something else like `persistence` makes Prisma CLI happy, but Nx will complain when building the entire app:
```sh
error TS6059: File '/Users/juan/git/my-proj/libs/shared/data-access-persistence/src/index.ts' is not under 'rootDir' 'libs/project/feature'. 'rootDir' is expected to contain all source files.
```
This https://github.com/nrwl/nx/issues/5952#issuecomment-950332388 made me realize that fixing this Prisma issue drove me to the build error.
