### ISSUE TITLE
getting error when deploy to google cloud functions

### ISSUE THREAD

**Issue by gaspan** [prisma/prisma#1339]
i got this error when i deploy to GCF 

```
!  functions[api(asia-northeast1)]: Deployment error.
Build failed: {"error": {"canonicalCode": "INVALID_ARGUMENT", "errorMessage": "`npm_install` had stderr output:\nError: In order to use \"@prisma/photon\", please install prisma2. You can install it with \"npm add -D prisma2\".\n    at main (/workspace/functions/node_modules/@prisma/photon/scripts/postinstall.js:18:9)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\nsh: 1: prisma2: not found\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! functions@ postinstall: `npm -s run generate`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the functions@ postinstall script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2020-01-15T17_26_14_574Z-debug.log\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @ preinstall: `./install-function-dependencies`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @ preinstall script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /builder/home/.npm/_logs/2020-01-15T17_26_18_675Z-debug.log\n\nerror: `npm_install` returned code: 1", "errorType": "InternalError", "errorId": "C6E953C0"}}

```

anyone can solve this problem ?

**Comment by pantharshit00** [comment]
You will need to add `prisma2` to your package.json file if you are running the generate command in the serverless environment.

```
npm install prisma2
```

Otherwise, if you are not building it in serverless, please make sure you have run `prisma2 generate` before deploying your app.

Please let me know if this helps you or otherwise please share a minimal reproduction that I can use to reproduce this issue.

**Comment by pantharshit00** [comment]
I am going to close this as its been more than a year and there is no activity here. 

Please reply if you want us to take another look.
