### ISSUE TITLE
Cannot use generate_series command on SQLite

### ISSUE THREAD

**Issue by neil-oliver** [prisma/prisma#13426]
### Bug description

Error thrown when using the SQLite command ```generate_series```. Error throw is ```no such table: generate_series```

### How to reproduce

- Include the ```improvedQueryRaw ``` flag in the schema. 
- Run sample query ```SELECT value FROM generate_series(5,100,5)``` using either ```queryRaw``` or ```queryRawUnsafe```.

### Expected behavior

Output list of numbers from 5-100 in increments of 5.

### Prisma information

Query should not be schema dependent.

### Environment & setup

- OS: Mac OS
- Database: SQLite
- Node.js version: v16.3.0

### Prisma Version

```
3.14.0
```

**Comment by pimeys** [comment]
Repro:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}
```

```typescript
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  const result = await prisma.$queryRaw`SELECT value FROM generate_series(5,100,5)`

  console.log(result)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```

```
  prisma:tryLoadEnv  Environment variables loaded from /prisma-13426/.env +0ms
  prisma:tryLoadEnv  Environment variables loaded from /prisma-13426/.env +1ms
  prisma:client  dirname /prisma-13426/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /prisma-13426/prisma +0ms
  prisma:client  clientVersion 4.3.1 +0ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client  prisma.queryRaw(SELECT value FROM generate_series(5,100,5), []) +12ms
  prisma:client  Prisma Client call: +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /prisma-13426/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /prisma-13426/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node +0ms
  prisma:client  Prisma Client call: +33ms
  prisma:client  prisma.$queryRaw({
  query: 'SELECT value FROM generate_series(5,100,5)',
  parameters: {
    values: '[]',
    __prismaRawParamaters__: true
  }
}) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  queryRaw(
    query: "SELECT value FROM generate_series(5,100,5)"
    parameters: "[]"
  )
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +46ms
  prisma:client:libraryEngine  library starting +1ms
prisma:info Starting a sqlite pool with 33 connections.
  prisma:client:libraryEngine  library started +1ms
prisma:query SELECT value FROM generate_series(5,100,5)
  prisma:client:request_handler  PrismaClientKnownRequestError: Raw query failed. Code: `1`. Message: `no such table: generate_series`
    at prismaGraphQLToJSError (/prisma-13426/node_modules/@prisma/client/runtime/index.js:20426:12)
    at LibraryEngine.buildQueryError (/prisma-13426/node_modules/@prisma/client/runtime/index.js:26363:12)
    at LibraryEngine.request (/prisma-13426/node_modules/@prisma/client/runtime/index.js:26297:22)
    at async RequestHandler.request (/prisma-13426/node_modules/@prisma/client/runtime/index.js:29873:24)
    at async Proxy._request (/prisma-13426/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async main (/prisma-13426/scripts.ts:8:18) {
  code: 'P2010',
  clientVersion: '4.3.1',
  meta: { code: '1', message: 'no such table: generate_series' }
} +0ms
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRaw()` invocation:


Raw query failed. Code: `1`. Message: `no such table: generate_series`
    at RequestHandler.handleRequestError (/prisma-13426/node_modules/@prisma/client/runtime/index.js:29909:13)
    at RequestHandler.request (/prisma-13426/node_modules/@prisma/client/runtime/index.js:29892:12)
    at async Proxy._request (/prisma-13426/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async main (/prisma-13426/scripts.ts:8:18) {
  code: 'P2010',
  clientVersion: '4.3.1',
  meta: { code: '1', message: 'no such table: generate_series' }
}
  prisma:client:libraryEngine  library stopping +15ms
  prisma:client:libraryEngine  library stopped +0ms
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms
```

**Comment by neil-oliver** [comment]
Apologies, I should have followed up with additional findings that would support this. `generate_series` does not work with sqlite as a default command and is actually a [loadable extension](https://www.sqlite.org/series.html). This would be the reason it does work with Prisma, however I have not confirmed that it works if this extension is installed.
