### ISSUE TITLE
Unable to connect to GCP Postgres with SSL enabled

### ISSUE THREAD

**Issue by gildebrand** [prisma/prisma#13514]
### Bug description

I'm unable to connect to Postgres 14 on GCP when I require SSL for connections. When trying to connect to Postgres using Prisma I get the error
```
Error: P1011
Error opening a TLS connection: One or more parameters passed to a function were not valid
```
If I disable the SSL requirement the connection works great.

With the `DEBUG` flag enabled I get the following output
```
⠋ Introspecting based on datasource defined in prisma/schema.prisma  prisma:introspectionEngine:rpc starting introspection engine with binary: /Users/antongildebrand/.nvm/versions/node/v14.18.1/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin-arm64 +0ms
  prisma:introspectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"datasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}","compositeTypeDepth":-1}]} +4ms
  prisma:introspectionEngine:rpc {
  prisma:introspectionEngine:rpc   jsonrpc: '2.0',
  prisma:introspectionEngine:rpc   error: {
  prisma:introspectionEngine:rpc     code: 4466,
  prisma:introspectionEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:introspectionEngine:rpc     data: {
  prisma:introspectionEngine:rpc       is_panic: false,
  prisma:introspectionEngine:rpc       message: 'Error opening a TLS connection: One or more parameters passed to a function were not valid.',
  prisma:introspectionEngine:rpc       meta: [Object],
  prisma:introspectionEngine:rpc       error_code: 'P1011'
  prisma:introspectionEngine:rpc     }
  prisma:introspectionEngine:rpc   },
  prisma:introspectionEngine:rpc   id: 1
  prisma:introspectionEngine:rpc } +28ms
```

### How to reproduce

1. Set up Postgres database on GCP
2. Enable SSL only connections
3. Whitelist your own IP
4. Create a new server certificate and rotate to the new (because of some old known GCP bug causing other issues otherwise)
5. Create a new client certificate and download the `client-cert.pem`, `client-key-pem` and `server-ca.pem` files.
6. Generate a PKCS12 certificate using `openssl pkcs12 -export -out client-identity.p12 -inkey client-key.pem -in client-cert.pem` and set a password
7. Copy the `client-identity.p12` and `server-ca.pem` files to the `prisma` folder
8. Set the connection string like `DATABASE_URL="postgresql://username:password@ip:5432/db?sslidentity=client-identity.p12&sslpassword=myPassword&sslcert=server-ca.pem"`
9. Launch application that tries to connect to DB (or just launch `prisma introspect`)
10. See error `Error opening a TLS connection: One or more parameters passed to a function were not valid`

### Expected behavior

I expect being able to connect to my Postgres instance.

### Prisma information

The `schema.prisma` file only contains the following

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

### Environment & setup

- OS: Mac OS 12.1
- Database: Postgres 14 on GCP
- Node.js version: 14.18.1

### Prisma Version

```
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at ../../../../../.nvm/versions/node/v14.18.1/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at ../../../../../.nvm/versions/node/v14.18.1/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at ../../../../../.nvm/versions/node/v14.18.1/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at ../../../../../.nvm/versions/node/v14.18.1/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

**Comment by antongildebrand** [comment]
Since I've been investigating this pretty much nonstop without any success I'd like to provide some more information on what I've just tried.

When I tried to import the PKCS12 (`.p12`) file to the Keychain in MacOS I consistently got errors on the password. Apparently there's some issue with OpenSSL compatibility on MacOS so I downgraded from OpenSSL 3.x to OpenSSL 1.1.1. After doing that and generating a new PKCS12 file I was able to import it into the Keychain app but still get the same error from Prisma :(

I figured out also that the `Error opening a TLS connection:` part of the message comes from the `prisma-engines` part of the project, and that the `One or more parameters passed to a function were not valid.` part of the error message _probably_ comes from MacOS somehow. What I also discovered is that Prisma doesn't complain at all if the file that I'm referring to using the `sslidentity` argument doesn't exist, but if the `sslcert` argument is invalid I get the error `cert file not found (No such file or directory (os error 2))` (as expected)

**Comment by pantharshit00** [comment]
Can you make sure you enabled the Google Cloud SQL Admin API?

**Comment by antongildebrand** [comment]
@pantharshit00 I checked and it is enabled!

**Comment by antongildebrand** [comment]
Just discovered that it does actually work from a Docker container on MacOS but not directly under MacOS

**Comment by pimeys** [comment]
First test done with NixOS Linux, built with OpenSSL 1.1.1m  14 Dec 2021. Went through the reproduction and couldn't reproduce.

Next step: testing with the office M1 machine if it fails there.

**Comment by pimeys** [comment]
On the mac, I get the error. Using the repo I created in my Linux machine, I do another `db pull` with the mac and I get an error:

```
Error opening a TLS connection: One or more parameters passed to a function were not valid.
```

This looks like an issue with tokio-postgres, which by default uses the system TLS implementation, which for Linux is OpenSSL and for macOS it's Security Framework. For some reason we cannot connect to GCP using Apple's TLS...

**Comment by pimeys** [comment]
For the dev who picks this up, take a look what we do with Tiberius on macos for quaint/SQL Server: if the system that compiles the crate is macos, we switch to an implementation with OpenSSL that we statically link (vendor) to the binary. It might be some of our parameters are given wrong and the Security Framework just don't like it, and if this is the case, it's easier to solve by fixing the implementation in Quaint.

Otherwise you have to modify quaint to use vendored OpenSSL on Apple devices, but it's extremely important to not do that in any other systems, so we allow the user to upgrade their system TLS implementation on Linux in case of security issues.

**Comment by sec0ndhand** [comment]
## Bug description

I'm unable to connect to Postgres 14 on AWS RDS when I require SSL for connections. When trying to connect to Postgres using Prisma I get the error

```
...
2023-03-15T06:38:43.988Z prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so
 libssl.so.1.1
...

 Please make sure your database server is running at `rds-db-instance-name.ds7asfdiafdsh.us-west-2.rds.amazonaws.com`:`5432`.
     at startFn (/usr/src/app/node_modules/@prisma/client/runtime/library.js:101:2598)
     at async Vt.getDmmf (/usr/src/app/node_modules/@prisma/client/runtime/library.js:101:3489)
     at async /usr/src/app/node_modules/@prisma/client/runtime/library.js:174:2864
     at async /usr/src/app/node_modules/@prisma/client/runtime/library.js:174:3268
     at async t._executeRequest (/usr/src/app/node_modules/@prisma/client/runtime/library.js:174:10726)
     at async t._request (/usr/src/app/node_modules/@prisma/client/runtime/library.js:174:10455) {
   clientVersion: '4.11.0',
   errorCode: 'P1001'
 }
 
 Invalid `prisma.accounts.findUnique()` invocation:
```

If I connect with pg, the nodejs Postgres plugin with the SSL enabled, the connection works great.

With the DEBUG flag enabled I get the output from above

## How to reproduce

1. Set up Postgres database on AWS
2. Enable SSL only connections
3. [download the certificate from AWS](https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem)
4. Set the connection string like DATABASE_URL="postgresql://username:password@rds-url:5432/db?sslmode=verify-full&sslaccept=strict&sslrootcert=rds-ca-2019-root.pem"
5. Launch application that tries to connect to DB (or just launch prisma introspect)
6. See the error above

I expect being able to connect to my Postgres instance in TLS mode.

```dockerfile
FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# Install for production
RUN npm ci --only=production

# Bundle app source
COPY . .

# Build Prisma Schema
RUN npx prisma generate --schema=./prisma/schema.prisma

# Build typescript
RUN npx tsc --project ./tsconfig.json

EXPOSE 3001
CMD [ "npm", "start" ]

```

## Prisma information

The schema.prisma file only contains the following

```javascript
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// plus many tables
```

## Environment & setup

OS: Alpine
Database: Postgres 14.5 on AWS RDS
Node.js version: 16
Prisma Version

prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : x86 (using a docker image)

**Comment by digitaldeus** [comment]
Just wanted to chime in and say that we are having this exact same issue with GCP and ssl.  

Note also that we were having a generic user does not have permission to access public schema error until we regenerated the server-ca as per:
> Create a new server certificate and rotate to the new (because of some old known GCP bug causing other issues otherwise)
