### ISSUE TITLE
Error: Error in migration engine. Reason: [libs/sql-schema-describer/src/postgres.rs:1039:28] no entry found for key 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#13520]
Command: `prisma db push`
Version: `3.14.0`
Binary Version: `2b0c12756921c891fec4f68d9444e18c7d5d4a6a`
Report: https://prisma-errors.netlify.app/report/13938 
OS: `arm64 darwin 20.6.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/postgres.rs:1039:28] no entry found for key

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

    at handlePanic (/node_modules/prisma/build/index.js:112999:25)
    at ChildProcess.<anonymous> (/node_modules/prisma/build/index.js:113008:15)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

Rust Stacktrace:
```
Starting migration engine RPC server
[libs/sql-schema-describer/src/postgres.rs:1039:28] no entry found for key
```

**Comment by tomhoule** [comment]
fixed by https://github.com/prisma/prisma-engines/pull/2939
