### ISSUE TITLE
Preview feature feedback: Prisma Metrics (`metrics`)

### ISSUE THREAD

**Issue by garrensmith** [prisma/prisma#13579]
Please share your feedback about the `metrics` functionality released in [v3.15.0](https://github.com/prisma/prisma/releases/tag/3.15) in this issue.

- If you encounter a bug, please [open a bug report](https://github.com/prisma/prisma/issues/new?assignees=&labels=&template=bug_report.md&title=) in this repo.
- If the feature is working well for you, please share this in a comment below or leave a 👍 on this issue.

If you have any questions, don't hesitate to ask them in the [`#prisma-client`](https://prisma.slack.com/archives/CCWDULGUW) channel in the [Prisma Slack](https://slack.prisma.io).

**Comment by Borales** [comment]
@garrensmith we have a service, that is not prisma-centric - we also have other metrics being reported and exposed under the corresponding endpoint. So the problem we have is how to make Prisma metrics a part of the app metrics (initially configured by [nestjs-otel](https://github.com/pragmaticivan/nestjs-otel) for API + `@opentelemetry/sdk-node` for the otel setup).

[The documented solution](https://www.prisma.io/docs/concepts/components/prisma-client/metrics#use-prisma-metrics-with-the-prometheus-metrics-system) below doesn't seem very elegant and looks more like a misuse of open-telemetry API:

```ts
app.get('/metrics', async (_req, res: Response) => {
  let prismaMetrics = await prisma.$metrics.prometheus();
  let appMetrics = await register.metrics();
  res.end(prismaMetrics + appMetrics);
});
```

Are there any plans on using `@opentelemetry/api-metrics` methods instead of https://github.com/prisma/prisma/blob/main/packages/client/src/runtime/core/metrics/MetricsClient.ts#L1?

**Comment by janpio** [comment]
Do you have an example how this _should_ (or could) look like @Borales? We might just not know about the "right way" yet.

**Comment by janpio** [comment]
Note: There are some bug reports under the `topic: metrics` label: https://github.com/prisma/prisma/issues?q=is%3Aopen+label%3A%22topic%3A+metrics%22+sort%3Aupdated-desc

**Comment by janpio** [comment]
2 internal observations: 
1. The 2 `prisma_client_queries_wait` metrics are actually filled with data from the connection pool, mobc. That could indicate that they are misnamed right now.
2. `prisma_client_queries_active` is described as `The number of active transactions`. The mix of "query" and "transaction" here might be confusing and a bug.

**Comment by janpio** [comment]
Another note: We don't have any counter "total sum of all x" that just count up each time an gauge is increased (but not down then the x is done).

**Comment by Jolg42** [comment]
Here is something that appeared in CI in an unrelated PR
2 tests failed in one run https://github.com/prisma/prisma/actions/runs/6751470751/job/18355613392?pr=21770#step:8:298 `Tests / Client func/legacy-notypes (4/5, library, 20)`
- 1st: because `prisma_client_queries_wait` value was `-1` and `0` was expected
```
FAIL metrics/enabled/tests.ts (6.53 s)
  ● metrics.enabled (provider=postgresql) › before a query › SQL Providers: should have the same keys, before and after a query

    expect(received).toMatchObject(expected)

    - Expected  - 1
    + Received  + 1

    @@ -7,11 +7,11 @@
        },
        Object {
          "description": "The number of datasource queries currently waiting for a free connection",
          "key": "prisma_client_queries_wait",
          "labels": Object {},
    -     "value": 0,
    +     "value": -1,
        },
        Object {
          "description": "The number of pool connections currently executing datasource queries",
          "key": "prisma_pool_connections_busy",
          "labels": Object {},

      255 |           },
      256 |         ])
    > 257 |         expect(gaugesBefore.sort((a, b) => a.key.localeCompare(b.key))).toMatchObject([
          |                                                                         ^
      258 |           {
      259 |             key: 'prisma_client_queries_active',
      260 |             labels: {},

      at Object.<anonymous> (metrics/enabled/tests.ts:257:73)
```
- 2nd because `prisma_client_queries_wait` value was `0` and we expected `1`
```
  ● metrics.enabled (provider=postgresql) › after a query › returns metrics in prometheus format

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0

      467 |         expect((metrics.match(/prisma_client_queries_total \d/g) || []).length).toBe(1)
      468 |         expect((metrics.match(/prisma_client_queries_active \d/g) || []).length).toBe(1)
    > 469 |         expect((metrics.match(/prisma_client_queries_wait \d/g) || []).length).toBe(1)
          |                                                                                ^
      470 |         expect((metrics.match(/prisma_client_queries_duration_histogram_ms_bucket/g) || []).length).toBe(11)
      471 |         expect((metrics.match(/prisma_client_queries_duration_histogram_ms_sum .*/g) || []).length).toBe(1)
      472 |         expect((metrics.match(/prisma_client_queries_duration_histogram_ms_count \d/g) || []).length).toBe(1)

      at Object.<anonymous> (metrics/enabled/tests.ts:469:80)
```

**Comment by wmadden** [comment]
**Update: Discontinuation planned for Jun - Aug 2025**

Due to low usage and compatibility issues with the Query Compiler feature, we’ve decided to retire metrics.

Read more here: https://github.com/prisma/prisma/discussions/26136

**Comment by rjinski** [comment]
Hi @wmadden , is there any plan to support metrics with OTEL or will it be entirely discontinued?

**Comment by anuraaga** [comment]
Just for reference, I'm currently migrating my services to `driverAdapter` to use the OTel instrumentation for `pg`.

Ideally the current metrics aren't removed until driver adapter is moved out of preview but I'm not sure what the roadmap is for that. DB metrics are essential, and the problem with the current approach was the UX, not the metrics themselves and hopefully the Prisma team takes it into account.

**Comment by jbeavers-stoke** [comment]
Moved from discussion post:

Thank you for the update and for setting expectations in advance. And thank you for all of your hard work on Prisma, in general!

> [Metrics](https://github.com/prisma/prisma/issues/13579)
> Discontinuation planned for Jun - Aug 2025
> Due to low usage and compatibility issues with the Query Compiler, we’ve decided to retire metrics.

While understandable if few people are using it, this discovery was a huge bummer for our team. We just recently started using this feature and while it's not perfect, it has already proven helpful for diagnosing several production issues.

As an example of its usefulness, we've had several issues with high query fanout and socket pool exhaustion. We have a theory that `query` (vs `relationJoins`) relational queries are a contributing factor, but having the per-host metrics from Prisma's metrics helped us nail this down as a source of growing query wait times. Without it, we only had DB level metrics which do not give the full picture and are only point-in-time. Without this metric, it would be harder to confirm the impact of upcoming experiments for remedying the situation.

In a world without these metrics being first class (the connection pool idle/active counts and wait times in particular), do you have any recommendations for how we might be able to obtain similar metrics using other tools?

My understanding is that the connection pooling behavior lives in rust-land, so it's not clear to me how we would be able to instrument this. Is the expectation to opt into `driverAdapter` and [use](https://www.prisma.io/docs/orm/overview/databases/postgresql#using-the-node-postgres-driver)/instrument the `node-postgres` driver calls with wrappers?

**Comment by jbeavers-stoke** [comment]
And a followup question related to performance and this post w.r.t `driverAdapter` -- https://www.prisma.io/blog/from-rust-to-typescript-a-new-chapter-for-prisma-orm

> This approach enables compatibility with JavaScript drivers but introduces a tradeoff: data must be serialized from JavaScript to Rust and then back to JavaScript, reducing efficiency and negating some of the benefits of this method.

The diagrams in that post makes it seem like we would be moving from:`node <-> rust <-> DB` to `node <-> rust <-> node <-> DB`. Conceptually, that doesn't sound right to me given the way that the adapter is configured and passed in as configuration... but I just wanted to sanity check.

Can you confirm that using `node-pg` and this adapter behavior effectively bypasses the rust layer entirely?

**Comment by daniellockyer** [comment]
I really hope that the `metrics` functionality is not removed. This world needs more instrumentation and visibility into what's going on, not less.

Despite it being in preview mode, I've used the metrics exported here to debug a few issues within client apps. I'd love to see it become first class and enable an even better debugging experience
