### ISSUE TITLE
Prisma update: Timed out fetching a new connection from the connection pool.

### ISSUE THREAD

**Issue by B4tzz** [prisma/prisma#13681]
### Bug description

I'm trying to do a massive update on a database with about 54.000 rows. Each line can be have a different value to be updated. So a tried frist using for of loop to wait each update finishing before execute the next, but that took a long time. So I made this request parallel with map an async await and this way is throwing an error:  Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 13).

### How to reproduce

      Promise.all(controlledDocs.docs.map(async doc => {
        return await db.tbl_general_approval.update({
          where: {
            itemKey: doc.itemKey
          },
          data: {
            statusId: doc.statusId
          }
        });
      }));

### Expected behavior

I just expect that all parallel promises from await execute succesfully.

### Prisma information

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

model sysdiagrams {
  name         String @db.NVarChar(128)
  principal_id Int
  diagram_id   Int    @id(map: "PK__sysdiagr__C2B05B6196C32836") @default(autoincrement())
  version      Int?
  definition   Bytes?

  @@unique([principal_id, name], map: "UK_principal_name")
}

model tbl_status {
  id                   Int                    @id(map: "PK__tbl_stat__3213E83FCA804D33") @default(autoincrement())
  status               String                 @db.VarChar(30)
  tbl_general_approval tbl_general_approval[]
}

model tbl_general_approval {
  id                       Int                        @default(autoincrement())
  itemKey                  String                     @id(map: "PK__tbl_gene__A3039D594C9DECD2") @db.VarChar(50)
  process                  String                     @db.VarChar(50)
  sistem                   String                     @db.VarChar(50)
  date                     DateTime                   @db.Date
  link                     String?                    @db.VarChar(200)
  statusId                 Int?
  tbl_status               tbl_status?                @relation(fields: [statusId], references: [id], onDelete: NoAction, onUpdate: NoAction, map: "FK__tbl_gener__statu__2EDAF651")
  tbl_notification_control tbl_notification_control[]
  tbl_user_approval        tbl_user_approval[]
}

### Environment & setup

- OS: Windows 11 Pro
- Database: Azure SQL 10.2 (Similar to SQL Server)
- Node.js version: v14.16.1

### Prisma Version

```
"dependencies": {
    "@prisma/client": "^3.14.0",
  },
  "devDependencies": {
    "prisma": "^3.15.0",
    "typescript": "^4.6.4"
  }
```

**Comment by B4tzz** [comment]
For now I found solution to finish my project is using knex querybuilder to handle this  one operation...

**Comment by jkomyno** [comment]
Hi, I have trying reproducing this issue, unfortunately without success. Would you please be able to share with us a self-contained repository that we can run to observe this potentially faulty behavior?

**Comment by millsp** [comment]
Hey @B4tzz , would you take a look at the question @jkomyno asked in the previous comment, and please let us know about the missing information? This will help us identifying the problem. Thanks!

**Comment by millsp** [comment]
Also @KevinBatdorf thanks for the report. We have not been able to reproduce this. Could you please provide us with a reproduction that we can easily run? That would help us a lot in getting this fixed. Thanks.

**Comment by millsp** [comment]
Hey @KevinBatdorf and @B4tzz,

Did you get a chance to have a look at my previous comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by KevinBatdorf** [comment]
10 months later I'm not even sure I'll be able to reproduce it, let alone update that build to the latest version of Prisma (it's working ok enough as it is with the workarounds, so I don't want to mess with it). 

I use Prisma often enough and if it comes up again I'll open a new issue.

**Comment by millsp** [comment]
Thanks @KevinBatdorf. Apologies that we got to this too late, this one is on us. I understand that you're not ready to upgrade, and thanks for getting back to us anyways. If you have some time, I'd love if you could ping me on slack, discord, or in a gh discussion to talk about these workarounds you have been using.

**Comment by KevinBatdorf** [comment]
For that particular case, the code is fairly simple and linked above ([here](https://github.com/KevinBatdorf/steam-api/blob/main/prisma/seed.ts#L53))

I'm describing this a bit from memory, but it has 70k items to upsert, and adding 70k at once would result in a connection timeout almost always. Then chunking them (looks like 3k was a sweet spot based on the code) in a for loop, it would work, but only if I removed the `await` from the outer loop. Not sure why, but it was fairly sporadic. 

It runs in a GH action, and after making that change, it runs daily without issue (so the past ~10 months): https://github.com/KevinBatdorf/steam-api/actions

Another oddity is that it sometimes finishes in under 10 minutes, and other times takes 2+ hours. Didn't bother investigating that though. Maybe the db server is slow at times.

**Comment by millsp** [comment]
Hey @KevinBatdorf I took some time to take a look at your reproduction. Right now, I agree with your conclusion that using `await` makes things slower. That is expected because this will wait for each batch to be inserted, while your solution without `await` makes better use of parallelization and the batches are sent almost together. Then I removed the batching to just send the queries all at once with the following code:

```ts
const games = gameData.applist.apps as Game[]

await Promise.all(games.map((game) => prisma.game.upsert({
    where: { appid: game.appid },
    update: { name: game.name },
    create: { appid: game.appid, name: game.name },
})))
```

That then triggered the error that was mentioned in the OP, so I could properly reproduce it on `4.2.1`:

```ts
Invalid `prisma.game.upsert()` invocation:


  Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 17)
    at RequestHandler.handleRequestError (/home/millsp/Throwaway/steam-api/node_modules/@prisma/client/runtime/index.js:28838:13)
    at RequestHandler.request (/home/millsp/Throwaway/steam-api/node_modules/@prisma/client/runtime/index.js:28820:12)
    at async PrismaClient._request (/home/millsp/Throwaway/steam-api/node_modules/@prisma/client/runtime/index.js:29753:16)
    at async Promise.all (index 16342) {
  code: 'P2024',
  clientVersion: '4.2.1',
  meta: { connection_limit: 17, timeout: 10 }
```

I then tried it on `5.2.0` and it errors faster but with the exact same error:

```ts
  18 
  19 const games = gameData.applist.apps as Game[]
  20 
→ 21 await Promise.all(games.map((game) => prisma.game.upsert(
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 17)
    at vn.handleRequestError (/home/millsp/Throwaway/steam-api/node_modules/@prisma/client/runtime/library.js:123:6730)
    at vn.handleAndLogRequestError (/home/millsp/Throwaway/steam-api/node_modules/@prisma/client/runtime/library.js:123:6119)
    at vn.request (/home/millsp/Throwaway/steam-api/node_modules/@prisma/client/runtime/library.js:123:5839)
    at async l (/home/millsp/Throwaway/steam-api/node_modules/@prisma/client/runtime/library.js:128:9763)
    at async Promise.all (index 69244) {
  code: 'P2024',
  clientVersion: '5.2.0',
  meta: { connection_limit: 17, timeout: 10 }
}
```

**Comment by millsp** [comment]
Shortened reproduction

```ts
const prisma = new PrismaClient()

const gameData = await (await fetch(
    'https://api.steampowered.com/ISteamApps/GetAppList/v2?json=1',
)).json()
if (!gameData.applist.apps) {
    throw new Error('No games returned')
}

const games = gameData.applist.apps as Game[]

await Promise.all(games.map((game) => prisma.game.upsert({
    where: { appid: game.appid },
    update: { name: game.name },
    create: { appid: game.appid, name: game.name },
})))
```

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
    provider        = "prisma-client-js"
}

datasource db {
    provider = "postgres"
    url      = "postgres://prisma:prisma@localhost:5432/tests"
}

model Game {
    appid Int    @id
    name  String
}
```

**Comment by millsp** [comment]
After taking a closer look, I suggest that you disable or increase your connection pool timeout. You can find how to do it [here](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool#disabling-the-connection-pool-timeout). By default, we will only keep a query for up to 10s, if we don't get a connection from the pool in that time frame then you will get this error. Perhaps, this was not immediately obvious to you when you clicked the link and should have pointed you to the right section?

**Comment by janpio** [comment]
So the original issue reported a `Timed out ...` error with `Promise.all`, which is expected if there are too many parallel queries that take too long for the connection pool timeout.
But it also reported that "5 parallel updates" ran into the same problem, even though `connection limit: 13`. That is not expected.
@B4tzz Can you please help us reproduce this behavior?

Then the comment from @KevinBatdorf repeated the problem of `Timed out ...` with `Promise.all` - which again is expected if it's too many queries for the configured pool size and connection limit.
The change in behavior of it being "more fickle" via `await` again is a bit unexpected. The `await` should make it _slower_ to run, but "fickle" seems to refer to getting an error message - and slower run should do the opposite.
Is my understanding correct @KevinBatdorf?

**Comment by KevinBatdorf** [comment]
> The change in behavior of it being "more fickle" via await again is a bit unexpected. The await should make it slower to run, but "fickle" seems to refer to getting an error message - and slower run should do the opposite.
Is my understanding correct @KevinBatdorf?

For my case I believe this is accurate. I only added the chunking and async/await to purposely slow things down, so it was surprising when removing the `await` made it more resilient. But I'm also speaking to something from a year ago, so details could be hazy. I'm happy to make changes on that repo if you want to see the output (assuming it still errors even...)

**Comment by avsdev-cw** [comment]
I was beginning to think I was doing something wrong until I found this ticket. I am also experiencing the OP's issue.

I am ingesting some log files (~50 log files with an average ~3k entries each file). Because of the structure of the database the log files are being entered into, I can't do an insertMany (I need to get the auto-increment id back for each inserted "event" for a stupid many-to-many map table - I have tested an insertMany without inserting into the map table and I don't get a timeout). If I Promise.all() the log files, I get the connection pool timeout issue, however if I `for(...) { await fn(file[i]) }` I only have an issue with some of the larger files (4 of them are about 10k entries instead and each causes a timeout).

I've tried setting the connection pool to 1 and to 100 and setting the timeout to 5 minutes, all to no avail.

To get around the issue, I'm going to have to chunk the file contents themselves (I think).

**Comment by janpio** [comment]
Please open a new issue and fully describe what you tried @avsdev-cw. I am pretty sure we can figure out why you run into which error message with which approach. Thanks.

**Comment by janpio** [comment]
Did you have time to look into this @KevinBatdorf? I'm unclear on how to proceed here without additional information.

**Comment by KevinBatdorf** [comment]
I just don't want to experiment on that simple app as it's old [and working as-is](https://github.com/KevinBatdorf/steam-api/actions/workflows/seed-database.yml). I haven't had the issue come up elsewhere so if other users are reporting it it's probably better to try to investigate there.

**Comment by mannerism** [comment]
Adding `&pool_timeout=0` at the end of database URL, in my case PlanetScale, works perfectly fine.
