### ISSUE TITLE
Migrate dev takes over 20s to apply a simple migration on an M1

### ISSUE THREAD

**Issue by floelhoeffel** [prisma/prisma#13692]
Repo: https://github.com/floelhoeffel/migration-slow

### Setup
- MBP M1 Max, 32 gig RAM
- MacOS 12.4
- node v16.15.1
- Prisma CLI
- PSQL DB on AWS and local docker (both show 20s+)
```
prisma                  : 3.15.0
@prisma/client          : 3.15.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt b9297dc3a59307060c1c39d7e4f5765066f38372 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : b9297dc3a59307060c1c39d7e4f5765066f38372
Studio                  : 0.462.0
```

### Start condition
- Start with a basic setup from our [getting started guide](https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases/using-prisma-migrate-typescript-postgres)
- bring schemas into sync

### Reproduction

Apply a simple Prisma schema change by adding a second `name2` field:
```
model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
  name2   String?
  posts   Post[]
  profile Profile?
}
````

and then run

```
time npx prisma migrate dev --skip-generate --skip-seed --name add-field
```
which outputs

```
0.92s user 0.26s system 4% cpu 24.028 total
```

I think 24s is unreasonable slow.

**Comment by pantharshit00** [comment]
I wasn't able to reproduce this: 
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/22195362/172621331-ec10045a-0b31-44e6-838e-55b5f170a7c3.png">


I almost have the same machine as you, M1 Max 64 GB RAM model. Can you maybe enable debug output using `DEBUG=*` and see on which step migrate is hanging for you.

**Comment by floelhoeffel** [comment]
Yes, the slow commands are the ones with `prisma:migrateEngine:stderr`, here is the output:
```
➜  migration-slow git:(main) ✗ time npx prisma migrate dev --skip-generate --skip-seed --name add-field
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at /Users/prisma/code/migration-slow/package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/prisma/code/migration-slow/.env +0ms
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /Users/prisma/code/migration-slow/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:getConfig  Loaded Node-API Library +3ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +0ms
  prisma:loadEnv  project root found at /Users/prisma/code/migration-slow/package.json +7ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/prisma/code/migration-slow/.env +6ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /Users/prisma/code/migration-slow/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +2ms
  prisma:getConfig  Loaded Node-API Library +0ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +0ms
Datasource "db": PostgreSQL database "black_tiger", schema "public" at "db-provision-postgres23452b4.c8yxynpcltwd.us-east-1.rds.amazonaws.com:5432"

  prisma:getDMMF  Using CLI Query Engine (Node-API Library) at: /Users/prisma/code/migration-slow/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:getDMMF  Loaded Node-API Library +0ms
  prisma:getDMMF  unserialized dmmf result ready +2ms
  prisma:getDMMF  dmmf retrieved without errors in getDmmfNodeAPI +0ms
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /Users/prisma/code/migration-slow/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +4ms
  prisma:getConfig  Loaded Node-API Library +0ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +0ms
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /Users/prisma/code/migration-slow/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:getConfig  Loaded Node-API Library +0ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +0ms
  prisma:migrateEngine:rpc  starting migration engine with binary: /Users/prisma/code/migration-slow/node_modules/@prisma/engines/migration-engine-darwin-arm64 +0ms
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"/Users/prisma/code/migration-slow/prisma/migrations"}} +8ms
  prisma:migrateEngine:stderr  {"timestamp":"2022-06-08T14:10:11.340325Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"b9297dc3a59307060c1c39d7e4f5765066f38372"},"target":"migration_engine"} +0ms
  prisma:migrate:dev  {
  devDiagnostic: '{\n  "action": {\n    "tag": "createMigration"\n  }\n}'
} +0ms
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":2,"jsonrpc":"2.0","method":"applyMigrations","params":{"migrationsDirectoryPath":"/Users/prisma/code/migration-slow/prisma/migrations"}} +10s
  prisma:migrateEngine:stderr  {"timestamp":"2022-06-08T14:10:23.7562Z","level":"INFO","fields":{"message":"Analysis run in 2028ms","analysis_duration_ms":2028},"target":"migration_core::commands::apply_migrations","span":{"name":"ApplyMigrations"},"spans":[{"name":"ApplyMigrations"}]} +12s
  prisma:migrateEngine:stderr  {"timestamp":"2022-06-08T14:10:23.756284Z","level":"INFO","fields":{"message":"All the migrations executed in 0ms","apply_migrations_duration_ms":0},"target":"migration_core::commands::apply_migrations","span":{"name":"ApplyMigrations"},"spans":[{"name":"ApplyMigrations"}]} +0ms
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":3,"jsonrpc":"2.0","method":"evaluateDataLoss","params":{"migrationsDirectoryPath":"/Users/prisma/code/migration-slow/prisma/migrations","prismaSchema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n\nmodel Post {\n  id        Int      @id @default(autoincrement())\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  title     String   @db.VarChar(255)\n  content   String?\n  published Boolean  @default(false)\n  author    User     @relation(fields: [authorId], references: [id])\n  authorId  Int\n}\n\nmodel Profile {\n  id     Int     @id @default(autoincrement())\n  bio    String?\n  user   User    @relation(fields: [userId], references: [id])\n  userId Int     @unique\n}\n\nmodel User {\n  id      Int      @id @default(autoincrement())\n  email   String   @unique\n  name    String?\n  name2   String?\n  name3   String?\n  posts   Post[]\n  profile Profile?\n}\n"}} +2s
  prisma:migrate:dev  {
  evaluateDataLossResult: { migrationSteps: 0, unexecutableSteps: [], warnings: [] }
} +6s
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":4,"jsonrpc":"2.0","method":"createMigration","params":{"migrationsDirectoryPath":"/Users/prisma/code/migration-slow/prisma/migrations","migrationName":"","draft":false,"prismaSchema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n\nmodel Post {\n  id        Int      @id @default(autoincrement())\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  title     String   @db.VarChar(255)\n  content   String?\n  published Boolean  @default(false)\n  author    User     @relation(fields: [authorId], references: [id])\n  authorId  Int\n}\n\nmodel Profile {\n  id     Int     @id @default(autoincrement())\n  bio    String?\n  user   User    @relation(fields: [userId], references: [id])\n  userId Int     @unique\n}\n\nmodel User {\n  id      Int      @id @default(autoincrement())\n  email   String   @unique\n  name    String?\n  name2   String?\n  name3   String?\n  posts   Post[]\n  profile Profile?\n}\n"}} +4s
  prisma:migrateEngine:stderr  {"timestamp":"2022-06-08T14:10:31.13104Z","level":"INFO","fields":{"message":"Database is up-to-date, returning without creating new migration."},"target":"migration_core::commands::create_migration","span":{"draft":false,"migration_name":"","name":"CreateMigration"},"spans":[{"draft":false,"migration_name":"","name":"CreateMigration"}]} +7s
  prisma:migrate:dev  { createMigrationResult: { generatedMigrationName: null } } +4s
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":5,"jsonrpc":"2.0","method":"applyMigrations","params":{"migrationsDirectoryPath":"/Users/prisma/code/migration-slow/prisma/migrations"}} +4s
  prisma:migrateEngine:stderr  {"timestamp":"2022-06-08T14:10:33.162692Z","level":"INFO","fields":{"message":"Analysis run in 2027ms","analysis_duration_ms":2027},"target":"migration_core::commands::apply_migrations","span":{"name":"ApplyMigrations"},"spans":[{"name":"ApplyMigrations"}]} +2s
  prisma:migrateEngine:stderr  {"timestamp":"2022-06-08T14:10:33.162822Z","level":"INFO","fields":{"message":"All the migrations executed in 0ms","apply_migrations_duration_ms":0},"target":"migration_core::commands::apply_migrations","span":{"name":"ApplyMigrations"},"spans":[{"name":"ApplyMigrations"}]} +1ms
Already in sync, no schema change or pending migration was found.

  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /Users/prisma/code/migration-slow/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +23s
  prisma:getConfig  Loaded Node-API Library +0ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +0ms
npx prisma migrate dev --skip-generate --skip-seed --name add-field  0.87s user 0.27s system 4% cpu 23.934 total
```

**Comment by P4sca1** [comment]
Recently, `yarn prisma migrate dev` takes around 5 minutes for me.

**Comment by kristian240** [comment]
Same here, stuck after RPC call is sent. 

```bash
npx prisma migrate dev --name rename-migration --create-only          
  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at /Users/kristian/personal/diplomski-rad/apps/backend/package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/kristian/personal/diplomski-rad/apps/backend/.env +0ms
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +2ms
  prisma:loadEnv  project root found at /Users/kristian/personal/diplomski-rad/apps/backend/package.json +4ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/kristian/personal/diplomski-rad/apps/backend/.env +4ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig  Using getConfig Wasm +2ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +1ms
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.mzgjnldnpuuyhabprspw.supabase.co:5432"

  prisma:getDMMF  Using CLI Query Engine (Node-API Library) at: /Users/kristian/personal/diplomski-rad/node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:getDMMF  Loaded Node-API Library +7ms
  prisma:getDMMF  unserialized dmmf result ready +8ms
  prisma:getDMMF  dmmf retrieved without errors in getDmmfNodeAPI +3ms
  prisma:getConfig  Using getConfig Wasm +20ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +0ms
  prisma:getConfig  Using getConfig Wasm +1ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +1ms
  prisma:migrateEngine:rpc  starting migration engine with binary: /Users/kristian/personal/diplomski-rad/node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/migration-engine-darwin-arm64 +0ms
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"/Users/kristian/personal/diplomski-rad/apps/backend/prisma/migrations"}} +6ms
  prisma:migrateEngine:stderr  {"timestamp":"2022-12-31T15:37:10.829255Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"d6e67a83f971b175a593ccc12e15c4a757f93ffe"},"target":"migration_engine"} +0ms
```

@P4sca1 Check [`Debugging` chapter](https://www.prisma.io/docs/concepts/components/prisma-client/debugging) in `primsa` docs to see the logs.

**Comment by floelhoeffel** [comment]
@kristian240 @brianbolnick are you by chance using a local docker container to host the DB?

**Comment by kristian240** [comment]
@floelhoeffel I still am facing the issue. Here is the entire log, once again. I'm not using Docker container; I'm using Supabase if that helps.

```bash
npx prisma migrate dev --name rename-migration --create-only  
  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at /Users/kristian/personal/diplomski-rad/apps/backend/package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/kristian/personal/diplomski-rad/apps/backend/.env +0ms
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +1ms
  prisma:loadEnv  project root found at /Users/kristian/personal/diplomski-rad/apps/backend/package.json +4ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/kristian/personal/diplomski-rad/apps/backend/.env +4ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig  Using getConfig Wasm +2ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +1ms
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.mzgjnldnpuuyhabprspw.supabase.co:5432"

  prisma:getDMMF  Using CLI Query Engine (Node-API Library) at: /Users/kristian/personal/diplomski-rad/node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:getDMMF  Loaded Node-API Library +3ms
  prisma:getDMMF  unserialized dmmf result ready +9ms
  prisma:getDMMF  dmmf retrieved without errors in getDmmfNodeAPI +4ms
  prisma:getConfig  Using getConfig Wasm +18ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +1ms
  prisma:getConfig  Using getConfig Wasm +1ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +1ms
  prisma:migrateEngine:rpc  starting migration engine with binary: /Users/kristian/personal/diplomski-rad/node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/migration-engine-darwin-arm64 +0ms
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"/Users/kristian/personal/diplomski-rad/apps/backend/prisma/migrations"}} +12ms
  prisma:migrateEngine:stderr  {"timestamp":"2023-01-12T20:01:10.711519Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"d6e67a83f971b175a593ccc12e15c4a757f93ffe"},"target":"migration_engine"} +0ms
  prisma:migrateEngine:rpc  {
  jsonrpc: '2.0',
  error: {
    code: 4466,
    message: 'An error happened. Check the data field for details.',
    data: {
      is_panic: false,
      message: 'db error: ERROR: canceling statement due to statement timeout\n' +
        '   0: migration_core::state::DevDiagnostic\n' +
        '             at migration-engine/core/src/state.rs:264',
      backtrace: null
    }
  },
  id: 1
} +2m
Error: Error: db error: ERROR: canceling statement due to statement timeout
   0: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:264

    at Object.<anonymous> (/Users/kristian/personal/diplomski-rad/node_modules/.pnpm/prisma@4.8.0/node_modules/prisma/build/index.js:93745:25)
    at MigrateEngine.handleResponse (/Users/kristian/personal/diplomski-rad/node_modules/.pnpm/prisma@4.8.0/node_modules/prisma/build/index.js:93596:36)
    at LineStream3.<anonymous> (/Users/kristian/personal/diplomski-rad/node_modules/.pnpm/prisma@4.8.0/node_modules/prisma/build/index.js:93695:16)
    at LineStream3.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at LineStream3.Readable.push (node:internal/streams/readable:228:10)
    at LineStream3._pushBuffer (/Users/kristian/personal/diplomski-rad/node_modules/.pnpm/prisma@4.8.0/node_modules/prisma/build/index.js:93473:17)
    at LineStream3._transform (/Users/kristian/personal/diplomski-rad/node_modules/.pnpm/prisma@4.8.0/node_modules/prisma/build/index.js:93467:8)
```

**Comment by janpio** [comment]
Your problem is unrelated to this one @kristian240, please follow and comment on https://github.com/prisma/prisma/issues/17160 - thanks.

**Comment by kristian240** [comment]
Thanks @janpio I'll follow the discussion on that one

**Comment by floelhoeffel** [comment]
Closing the issue as we can't reproduce. Feel free to re-open in case anyone has a reproduction.
