### ISSUE TITLE
Error: Error in migration engine. Reason: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:98:76] called `Result::unwrap()` on an `Err` value: ....

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#13741]
Timeouts are not something we can prevent, but we should error gracefully here.

Command: `prisma migrate up --experimental --schema database/prisma/schema.prisma`
Version: `2.11.0`
Binary Version: `58369335532e47bdcec77a2f1e7c1fb83a463918`
Report: https://prisma-errors.netlify.app/report/14037 
OS: `x64 darwin 21.5.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:98:76] called `Result::unwrap()` on an `Err` value: ConnectionError { quaint_error: Error { kind: Timeout("tokio timeout"), original_code: None, original_message: Some("Query timed out.") }, connection_info: Postgres(PostgresUrl { url: Url { scheme: "postgresql", host: Some(Domain("klog-co-dev.cgknstodcxhq.us-east-1.rds.amazonaws.com")), port: Some(5432), path: "/prisma", query: Some("schema=public&socket_timeout=30&connect_timeout=30&statement_cache_size=0"), fragment: None }, query_params: PostgresUrlQueryParams { ssl_params: SslParams { certificate_file: None, identity_file: None, identity_password: <HIDDEN>, ssl_accept_mode: AcceptInvalidCerts }, connection_limit: None, schema: "public", ssl_mode: Prefer, pg_bouncer: false, host: None, socket_timeout: Some(30s), connect_timeout: Some(30s), statement_cache_size: 0 } }) }

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (<......>/node_modules/@prisma/cli/build/index.js:60100:23)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
```

Rust Stacktrace:
```
[migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:98:76] called `Result::unwrap()` on an `Err` value: ConnectionError { quaint_error: Error { kind: Timeout("tokio timeout"), original_code: None, original_message: Some("Query timed out.") }, connection_info: Postgres(PostgresUrl { url: Url { scheme: "postgresql", host: Some(Domain("klog-co-dev.cgknstodcxhq.us-east-1.rds.amazonaws.com")), port: Some(5432), path: "/prisma", query: Some("schema=public&socket_timeout=30&connect_timeout=30&statement_cache_size=0"), fragment: None }, query_params: PostgresUrlQueryParams { ssl_params: SslParams { certificate_file: None, identity_file: None, identity_password: <HIDDEN>, ssl_accept_mode: AcceptInvalidCerts }, connection_limit: None, schema: "public", ssl_mode: Prefer, pg_bouncer: false, host: None, socket_timeout: Some(30s), connect_timeout: Some(30s), statement_cache_size: 0 } }) }
```

**Comment by janpio** [comment]
Oh, this is oooooold - 2.11.0 and `migrate up` :D

**Comment by tomhoule** [comment]
omg yes, I totally missed the version on that one. Good catch, we can just close then.
