### ISSUE TITLE
Update Restrict failed on prisma referentialIntegrity

### ISSUE THREAD

**Issue by ManolisPap** [prisma/prisma#13766]
### Bug description

If you enable the previewFeatures referentialIntegrity, and you have a relation i.e., 1-many and you try to update a column(a non primary key) from the parent table, prisma gives an error.

```
The change you are trying to make would violate the required relation 'OrderToOrderStatusHistory' between the `Order` and `OrderStatusHistory` models.
```

With the default referentialIntegrity from the database the update succeed. Or if you change the onUpdate: Cascade

### How to reproduce

I have create a public project that you can clone if you like:
https://github.com/ManolisPap/prisma-playground

- Create an empty database with mysql or PlaneScale
- create the .env file with an envirome variable DATABASE_URL='...'
- create the prisma.schema file (with the attached code)
- npx prisma db push
- create the index2.ts file (with the attached code)
- run the index2.ts file npx ts-node index2.ts
- The typescript code will run successfully and we will create a new Order and a new OrderStatusHistory but then it will fail to update the paid column of the order with id 1.
- Or just follows the step from prisma.io:
[https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases-typescript-postgres](Initial Setup)

### Expected behavior

Update the paid field to true(1).

### Prisma information

**prisma.schema**

```prisma
datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

enum OrderStatus {
  NEW
  PICKED
  STORED
  DELIVERED
}

model Order {
  orderId          Int                  @id @default(autoincrement())
  paid             Boolean?
  statusMilestones OrderStatusHistory[]

  @@index([orderId])
}

model OrderStatusHistory {
  orderStatusHistoryId Int         @id @default(autoincrement())
  orderId              Int
  status               OrderStatus
  createdAt            DateTime    @default(now())
  order                Order       @relation(fields: [orderId], references: [orderId], onUpdate: Restrict, onDelete: Cascade)

  @@index([orderId])
}

```

**Dummy Typescript usage**
```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({
  log: ["query", "info", "warn", "error"],
  errorFormat: "pretty",
});

async function main() {
  const ordersNum = await prisma.order.count();
  console.log("Orders into database: " + ordersNum);

  if (ordersNum == 0) {
    console.log("Create a new order");
    const order = await prisma.order.create({
      data: {
        orderId: 1,
        paid: false,
        statusMilestones: {
          create: {
            status: "NEW",
          },
        },
      },
    });
    console.log(order);
  }

  console.log("Update Order with id 1");
  const updatedOrder = await prisma.order.update({
    where: {
      orderId: 1,
    },
    data: {
      paid: true,
    },
  });
  console.log(updatedOrder);
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```

### Environment & setup

OS: Windows
Database: mySQL or Planetscale
Node.js version: v16.13.0

### Prisma Version

prisma: "^3.15.1"

**Comment by Jolg42** [comment]
I can indeed reproduce.

Using the provided repository, I just did the following on MySQL and on PlanetScale with the same result:
Note: `referentialIntegrity = "prisma"` & relation has `onUpdate: Restrict, onDelete: Cascade)` 

```
npm i
npx prisma generate
npx prisma db push
npx ts-node index2.ts
prisma:info Starting a mysql pool with 5 connections.
prisma:query SELECT COUNT(*) FROM (SELECT `violet_orangutan`.`Order`.`orderId` FROM `violet_orangutan`.`Order` WHERE 1=1) AS `sub`
Orders into database: 0
Create a new order
prisma:query BEGIN
prisma:query INSERT INTO `violet_orangutan`.`Order` (`orderId`,`paid`) VALUES (?,?)
prisma:query INSERT INTO `violet_orangutan`.`OrderStatusHistory` (`orderStatusHistoryId`,`orderId`,`status`,`createdAt`) VALUES (?,?,?,?)
prisma:query SELECT `violet_orangutan`.`Order`.`orderId`, `violet_orangutan`.`Order`.`paid` FROM `violet_orangutan`.`Order` WHERE `violet_orangutan`.`Order`.`orderId` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
{ orderId: 1, paid: false }
Update Order with id 1
prisma:query BEGIN
prisma:query SELECT `violet_orangutan`.`Order`.`orderId` FROM `violet_orangutan`.`Order` WHERE `violet_orangutan`.`Order`.`orderId` = ?
prisma:query SELECT `violet_orangutan`.`OrderStatusHistory`.`orderStatusHistoryId`, `violet_orangutan`.`OrderStatusHistory`.`orderId` FROM `violet_orangutan`.`OrderStatusHistory` WHERE (1=1 AND `violet_orangutan`.`OrderStatusHistory`.`orderId` IN (?))
prisma:query ROLLBACK
/workspaces/prisma-playground/node_modules/@prisma/client/runtime/index.js:49022
        throw new PrismaClientKnownRequestError(message, e.code, this.client._clientVersion, e.meta);
              ^
PrismaClientKnownRequestError: 
Invalid `prisma.order.update()` invocation in
/workspaces/prisma-playground/index2.ts:30:43

  27 }
  28 
  29 console.log("Update Order with id 1");
→ 30 const updatedOrder = await prisma.order.update(
  The change you are trying to make would violate the required relation 'OrderToOrderStatusHistory' between the `Order` and `OrderStatusHistory` models.
    at RequestHandler.request (/workspaces/prisma-playground/node_modules/@prisma/client/runtime/index.js:49022:15)
    at async PrismaClient._request (/workspaces/prisma-playground/node_modules/@prisma/client/runtime/index.js:49919:18)
    at async main (/workspaces/prisma-playground/index2.ts:30:24) {
  code: 'P2014',
  clientVersion: '3.15.1',
  meta: {
    relation_name: 'OrderToOrderStatusHistory',
    model_a_name: 'Order',
    model_b_name: 'OrderStatusHistory'
  }
}
```

**Comment by Jolg42** [comment]
Now trying on MySQL with changing `referentialIntegrity = "prisma"` to `referentialIntegrity = "foreignKeys"` results in no error and `paid` is now true

```
npx prisma generate
npx ts-node index2.ts
prisma:info Starting a mysql pool with 5 connections.
prisma:query SELECT COUNT(*) FROM (SELECT `violet_orangutan`.`Order`.`orderId` FROM `violet_orangutan`.`Order` WHERE 1=1) AS `sub`
Orders into database: 1
Update Order with id 1
prisma:query BEGIN
prisma:query SELECT `violet_orangutan`.`Order`.`orderId` FROM `violet_orangutan`.`Order` WHERE `violet_orangutan`.`Order`.`orderId` = ?
prisma:query UPDATE `violet_orangutan`.`Order` SET `paid` = ? WHERE `violet_orangutan`.`Order`.`orderId` IN (?)
prisma:query SELECT `violet_orangutan`.`Order`.`orderId`, `violet_orangutan`.`Order`.`paid` FROM `violet_orangutan`.`Order` WHERE `violet_orangutan`.`Order`.`orderId` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
{ orderId: 1, paid: true }
```

**Comment by Jolg42** [comment]
Note: here is a minimal reproduction using dev version and Vitess docker image (using `4.3.0-dev.22` now)
https://github.com/Jolg42/repro-prisma-13766

```
❯ git clone https://github.com/Jolg42/repro-prisma-13766.git
❯ cd repro-prisma-13766
❯ docker-compose up -d
❯ npm i
❯ npx prisma db push
❯ ts-node index.ts  
   
prisma:info Starting a mysql pool with 21 connections.
prisma:query SELECT COUNT(*) FROM (SELECT `repro_13766`.`Order`.`orderId` FROM `repro_13766`.`Order` WHERE 1=1) AS `sub`
Orders into database: 0
Create a new order
prisma:query BEGIN
prisma:query INSERT INTO `repro_13766`.`Order` (`orderId`,`paid`) VALUES (?,?)
prisma:query INSERT INTO `repro_13766`.`OrderStatusHistory` (`orderStatusHistoryId`,`orderId`,`status`,`createdAt`) VALUES (?,?,?,?)
prisma:query SELECT `repro_13766`.`Order`.`orderId`, `repro_13766`.`Order`.`paid` FROM `repro_13766`.`Order` WHERE `repro_13766`.`Order`.`orderId` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
{ orderId: 1, paid: false }
Update Order with id 1
prisma:query BEGIN
prisma:query SELECT `repro_13766`.`Order`.`orderId` FROM `repro_13766`.`Order` WHERE `repro_13766`.`Order`.`orderId` = ?
prisma:query SELECT `repro_13766`.`OrderStatusHistory`.`orderStatusHistoryId`, `repro_13766`.`OrderStatusHistory`.`orderId` FROM `repro_13766`.`OrderStatusHistory` WHERE (1=1 AND `repro_13766`.`OrderStatusHistory`.`orderId` IN (?))
prisma:query ROLLBACK
/Users/j42/Repros/prisma-playground/node_modules/@prisma/client/runtime/index.js:28912
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^

Error: 
Invalid `prisma.order.update()` invocation:


  The change you are trying to make would violate the required relation 'OrderToOrderStatusHistory' between the `Order` and `OrderStatusHistory` models.
    at RequestHandler.handleRequestError (/Users/j42/Repros/prisma-playground/node_modules/@prisma/client/runtime/index.js:28912:13)
    at RequestHandler.request (/Users/j42/Repros/prisma-playground/node_modules/@prisma/client/runtime/index.js:28894:12)
    at PrismaClient._request (/Users/j42/Repros/prisma-playground/node_modules/@prisma/client/runtime/index.js:29827:16)
    at null.main (/Users/j42/Repros/prisma-playground/index2.ts:30:24) {
  code: 'P2014',
  clientVersion: '4.3.0-dev.22',
  meta: {
    relation_name: 'OrderToOrderStatusHistory',
    model_a_name: 'Order',
    model_b_name: 'OrderStatusHistory'
  }
}
```

**Comment by Jolg42** [comment]
Can reproduce with `4.4.0-dev.25`
```
prisma:info Starting a mysql pool with 21 connections.
prisma:query SELECT COUNT(*) FROM (SELECT `repro_13766`.`Order`.`orderId` FROM `repro_13766`.`Order` WHERE 1=1 /* traceparent=00-00-00-00 */) AS `sub` /* traceparent=00-00-00-00 */
Orders into database: 0
Create a new order
prisma:query BEGIN
prisma:query INSERT INTO `repro_13766`.`Order` (`orderId`,`paid`) VALUES (?,?) /* traceparent=00-00-00-00 */
prisma:query INSERT INTO `repro_13766`.`OrderStatusHistory` (`orderStatusHistoryId`,`orderId`,`status`,`createdAt`) VALUES (?,?,?,?) /* traceparent=00-00-00-00 */
prisma:query SELECT `repro_13766`.`Order`.`orderId`, `repro_13766`.`Order`.`paid` FROM `repro_13766`.`Order` WHERE `repro_13766`.`Order`.`orderId` = ? LIMIT ? OFFSET ? /* traceparent=00-00-00-00 */
prisma:query COMMIT
{ orderId: 1, paid: false }
Update Order with id 1
prisma:query BEGIN
prisma:query SELECT `repro_13766`.`Order`.`orderId` FROM `repro_13766`.`Order` WHERE `repro_13766`.`Order`.`orderId` = ? /* traceparent=00-00-00-00 */
prisma:query SELECT `repro_13766`.`OrderStatusHistory`.`orderStatusHistoryId`, `repro_13766`.`OrderStatusHistory`.`orderId` FROM `repro_13766`.`OrderStatusHistory` WHERE (1=1 AND `repro_13766`.`OrderStatusHistory`.`orderId` IN (?)) /* traceparent=00-00-00-00 */
prisma:query ROLLBACK
/Users/j42/Repros/repro-prisma-13766/node_modules/@prisma/client/runtime/index.js:30850
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.order.update()` invocation in
/Users/j42/Repros/repro-prisma-13766/index.ts:30:43

  27 }
  28 
  29 console.log("Update Order with id 1");
→ 30 const updatedOrder = await prisma.order.update(
The change you are trying to make would violate the required relation 'OrderToOrderStatusHistory' between the `Order` and `OrderStatusHistory` models.
    at RequestHandler.handleRequestError (/Users/j42/Repros/repro-prisma-13766/node_modules/@prisma/client/runtime/index.js:30850:13)
    at RequestHandler.request (/Users/j42/Repros/repro-prisma-13766/node_modules/@prisma/client/runtime/index.js:30833:12)
    at async PrismaClient._request (/Users/j42/Repros/repro-prisma-13766/node_modules/@prisma/client/runtime/index.js:31805:16)
    at async main (/Users/j42/Repros/repro-prisma-13766/index.ts:30:24) {
  code: 'P2014',
  clientVersion: '4.4.0-dev.25',
  meta: {
    relation_name: 'OrderToOrderStatusHistory',
    model_a_name: 'Order',
    model_b_name: 'OrderStatusHistory'
  }
}
```
