### ISSUE TITLE
Issues deploying Serverless Framework (AWS Lambda)

### ISSUE THREAD

**Issue by jonatanalava** [prisma/prisma#1383]
Deploying to AWS Lambda using Serverless, we are running into an issue when we call the API

Deployment finishes correctly. Graphiql comes up and shows me the generated schema, but calling any other operation (query/mutation) returns

Is this an issue with the library or are we doing something wrong. (running the latest preview version 19)

```
{
  "errors": [
    {
      "message": "\nInvalid `photon.()` invocation in /var/task/node_modules/nexus-prisma/dist/builder.js:129:97\n\n\n\nundefined target=\"exit\" timestamp=\"2020-01-21T00:42:14.995Z\" fields={\"message\":\"127\"}",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "companies"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: ",
            "Invalid `photon.()` invocation in /var/task/node_modules/nexus-prisma/dist/builder.js:129:97",
            "",
            "",
            "",
            "undefined target=\"exit\" timestamp=\"2020-01-21T00:42:14.995Z\" fields={\"message\":\"127\"}",
            "    at PhotonFetcher.<anonymous> (/var/task/node_modules/@prisma/photon/index.js:65:27)",
            "    at Generator.throw (<anonymous>)",
            "    at rejected (/var/task/node_modules/@prisma/photon/index.js:6:65)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

Also, this comes up in the logs on Cloudwatch
```60bea421-7b5f-4923-9968-b5ba3e2fceae	ERROR	[Error: ENOENT: no such file or directory, mkdir] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir'
}```

**Comment by pantharshit00** [comment]
Hi, 

Can you please tell me which version of Prisma 2 are you using? Also, can you please share a minimal reproduction of this issue?

**Comment by jonatanalava** [comment]
Sorry for the delay. Version is 2.0.0-preview019

Will add repro in a bit

**Comment by ccmarroquina-hb** [comment]
I have reproduced this issue when deploy to lambda this repo https://github.com/hellobuild/Issues-deploying-Serverless-AWS-Lambda

**Comment by pantharshit00** [comment]
Ok, AWS lambda is not Debian based but Amazon Linux based(which is based on CentOS). 

So you will need to use `rhel-openssl-1.0.x` binary for it:`
```
generator photon {
  provider = "photonjs"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

**Comment by jonatanalava** [comment]
After trying this, we see the same error

**Comment by pantharshit00** [comment]
I can reproduce this even after changing the platform. Probably related to sls framework.

**Comment by janpio** [comment]
We have a working e2e test with serverless framework and Lambda at https://github.com/prisma/e2e-tests/tree/dev/platforms/serverless-lambda - could you take another look please @pantharshit00 and define what the difference here is? Thanks.

**Comment by pantharshit00** [comment]
I am going to close this as its been over a month now and there is no activity here. 

Please reply if you want us to take another look.
