### ISSUE TITLE
Error in domain logic: Conversion from `Json(...)` to `Json` failed

### ISSUE THREAD

**Issue by behrangsa** [prisma/prisma#13887]
### Bug description

_NB: I've attached the sample [code.zip](https://github.com/prisma/prisma/files/8932959/code.zip)._ 

---

Schema:

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model DocumentStore {
  id   Json @id
  body Json
}
```

The database table is generated as expected:

```sql
CREATE TABLE "DocumentStore"
(
    id   JSONB NOT NULL PRIMARY KEY,
    body JSONB NOT NULL
);
```

But both insertion and lookup operations fail.

Example:

```typescript
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  await prisma.documentStore.create({
    data: {
      id: {
        "system": "foo",
        "key": "123"
      },
      body: {
        "url": "https://foo.example.com/123",
        "description": "I am Foo 123!"
      }
    }
  })
}

main()
  .catch((e) => {
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```

Test:

```
❯ yarn ts-node index.ts              
yarn run v1.22.15
$ .../node_modules/.bin/ts-node index.ts
.../node_modules/@prisma/client/runtime/index.js:49026
        throw new PrismaClientUnknownRequestError(message, this.client._clientVersion);
              ^
PrismaClientUnknownRequestError: 
Invalid `prisma.documentStore.create()` invocation in
.../index.ts:6:30

  3 const prisma = new PrismaClient()
  4 
  5 async function main() {
→ 6   await prisma.documentStore.create(
  Error in domain logic: Conversion from `Json("{\"key\":\"123\",\"system\":\"foo\"}")` to `Json` failed.
    at RequestHandler.request (.../node_modules/@prisma/client/runtime/index.js:49026:15)
    at async PrismaClient._request (.../node_modules/@prisma/client/runtime/index.js:49919:18) {
  clientVersion: '3.15.2'
}
error Command failed with exit code 1.
```

--- 

[code.zip](https://github.com/yarnpkg/berry/files/8932953/code.zip)

### How to reproduce

Download the attached sample code, install packages, and run

```
$ yarn ts-node index.ts  
```

### Expected behavior

Models should be serialized and get queried.

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model DocumentStore {
  id   Json @id
  body Json
}
```

### Environment & setup

- OS: Linux
- Database: Postgres
- Node.js version: v16.15.0

### Prisma Version

```
yarn run v1.22.15
$ .../node_modules/.bin/prisma -v
Environment variables loaded from .env
prisma                  : 3.15.2
@prisma/client          : 3.15.2
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 461d6a05159055555eb7dfb337c9fb271cbd4d7e
Studio                  : 0.462.0
Done in 0.90s.
```

**Comment by pimeys** [comment]
And, I can reproduce this with 3.15.2.
