### ISSUE TITLE
Running `npm install` in empty `node_modules`, leads to funny errors

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1398]
```
c:\Users\Jan\Documents\throwaway\613\node_modules>npm install

> prisma2@2.0.0-preview020 install c:\Users\Jan\Documents\throwaway\613\node_modules\prisma2
> node download-build/index.js

> Downloading Prisma engines for windows [====================] 100%




> @prisma/client@2.0.0-preview020 postinstall c:\Users\Jan\Documents\throwaway\613\node_modules\@prisma\client        
> node scripts/postinstall.js

Error: Can't find schema.prisma
1
Error: In order to use "@prisma/client", please install prisma2. You can install it with "npm add -D prisma2".        
    at main (c:\Users\Jan\Documents\throwaway\613\node_modules\@prisma\client\scripts\postinstall.js:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN 613@1.0.0 No description
npm WARN 613@1.0.0 No repository field.

added 3 packages from 42 contributors and audited 3 packages in 9.631s
found 0 vulnerabilities
```

`package.json` looks like this in `c:\Users\Jan\Documents\throwaway\613`:

```
{
  "name": "613",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@prisma/client": "2.0.0-preview020",
    "@types/node": "^13.1.8",
    "prisma2": "^2.0.0-preview020"
  },
  "engines": {
    "node": ">=10.0.0"
  }
}

```

**Comment by janpio** [comment]
(Running `npm install` from the real folder worked just fine)

**Comment by pantharshit00** [comment]
I can confirm this error. This also error also pops up in other places(like this one #1134) so I think we should silently fail in postinstall script if we can't find the schema.

**Comment by pantharshit00** [comment]
This is no longer reproducible in `2.21.2`
