### ISSUE TITLE
sqlite: show better error when a permission denied error occurs

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#13991]
Command: `prisma migrate reset`
Version: `3.15.0`
Binary Version: `b9297dc3a59307060c1c39d7e4f5765066f38372`
Report: https://prisma-errors.netlify.app/report/14081 
OS: `x64 linux 5.4.0-1018-aws`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/flavour/sqlite.rs:194:46] failed to truncate sqlite file: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

    at handlePanic (/home/../app/node_modules/prisma/build/index.js:93373:25)
    at ChildProcess.<anonymous> (/home/../app/node_modules/prisma/build/index.js:93382:15)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

Rust Stacktrace:
```
Starting migration engine RPC server
[migration-engine/connectors/sql-migration-connector/src/flavour/sqlite.rs:194:46] failed to truncate sqlite file: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
```

**Comment by jkomyno** [comment]
We have another reproduction of the same issue [here](https://prisma-errors.netlify.app/report/14177), on WSL2.

**Comment by janpio** [comment]
Another duplicate here: https://github.com/prisma/prisma/issues/15352
