### ISSUE TITLE
invalid character in $let in $lookup pipeline when using cursor and order by query

### ISSUE THREAD

**Issue by adamwimmj** [prisma/prisma#14001]
### Bug description

Our database consists of pascal case field names, therefore when using the cursor query options, and order by on a particular field (that starts with a capital letter), prisma builds up an aggregate query and uses the pascal case field name for a $let veriable in the pipeline. According to [https://www.mongodb.com/docs/v4.4/reference/aggregation-variables/](https://www.mongodb.com/docs/v4.4/reference/aggregation-variables/) let variables cannot start with uppercase letters which I think is my problem.

I've created an [example project](https://bitbucket.org/awimmjsystems/prisma/src/master/) that seeds the database with pascal case field names to demonstrate the error.

Here is all the output without running the example project:

When using this schema:

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model order {
  id      String @id @default(auto()) @map("_id") @db.ObjectId
  OrderBy Int @unique()
}
```
And running this query:

```
await prisma.order.findMany({
    cursor: { OrderBy: 1 },
    orderBy: { OrderBy: "asc" }
   });
```

This error is thrown (debug output):

```
prisma:client  Generated request: +0ms
  prisma:client  query {
  findManyorder(
    cursor: {
      OrderBy: 1
    }
    orderBy: [
      {
        OrderBy: asc
      }
    ]
  ) {
    id
    OrderBy
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +13ms
  prisma:client:request_handler  PrismaClientUnknownRequestError: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "unknown", message: "Command failed (Location16867): 'OrderBy' starts with an invalid character for a user variable name)" } })
    at prismaGraphQLToJSError (/Users/a/dev/tests/prisma/node_modules/@prisma/client/runtime/index.js:43011:10)
    at LibraryEngine.request (/Users/a/dev/tests/prisma/node_modules/@prisma/client/runtime/index.js:44865:17)
    at async RequestHandler.request (/Users/a/dev/tests/prisma/node_modules/@prisma/client/runtime/index.js:48992:24)
    at async PrismaClient._request (/Users/a/dev/tests/prisma/node_modules/@prisma/client/runtime/index.js:49919:18)
    at async main (/Users/a/dev/tests/prisma/index.js:8:19) {
  clientVersion: '3.15.2'
} +0ms
  prisma:client:libraryEngine  library stopping +22ms
  prisma:client:libraryEngine  library stopped +1ms
  prisma:client:libraryEngine  hookProcess received: exit +1ms
  prisma:client:libraryEngine  runBeforeExit +0ms
```

With the aggregate looking like this:

```
[
    {"$match":{"$expr":{"$and":[{"$eq":["$OrderBy",1]}]}}},
    {
        "$lookup":{
            "from":"order","let":{"OrderBy":"$OrderBy"},
            "pipeline":[
                {"$match":{"$expr":{"$gte":["$OrderBy","$$OrderBy"]}}},
                {"$sort":{"OrderBy":1}},
                {"$project":{"_id":1,"OrderBy":1}}
            ],
            "as":"cursor_inner"
        }
    },
    {"$unwind":"$cursor_inner"},
    {"$replaceRoot":{"newRoot":"$cursor_inner"}}
]
```

Is there anyway I can force prisma to lowercase the let variable name?

### How to reproduce

```
git clone https://awimmjsystems@bitbucket.org/awimmjsystems/prisma.git

npm install
npx prisma db seed
node index.js
```

Or

When using this schema:

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model order {
  id      String @id @default(auto()) @map("_id") @db.ObjectId
  OrderBy Int @unique()
}
```

And running this query:

```
await prisma.order.findMany({
    cursor: { OrderBy: 1 },
    orderBy: { OrderBy: "asc" }
   });
```

### Expected behavior

I expect the query to return all orders after the cursor and sorted by `OrderId`.

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model order {
  id      String @id @default(auto()) @map("_id") @db.ObjectId
  OrderBy Int @unique()
}
```

```
await prisma.order.findMany({
    cursor: { OrderBy: 1 },
    orderBy: { OrderBy: "asc" }
   });
```

### Environment & setup

- Mongodb version: 4.4.5
- Node.js version: 16.0.0

### Prisma Version

```
prisma                  : 3.15.2
@prisma/client          : 3.15.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 461d6a05159055555eb7dfb337c9fb271cbd4d7e (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 461d6a05159055555eb7dfb337c9fb271cbd4d7e
Studio                  : 0.462.0
```

**Comment by adamwimmj** [comment]
Hi, thanks for having a look at this. In the mean time, would you have any suggestions on a possible work around to get this working with our data please?

**Comment by Jolg42** [comment]
Can reproduce in our internal dev version `4.4.0-dev.27` (I didn't try the git repo, schema + query was enough apparently).
