### ISSUE TITLE
Entered unreachable code: no provider, no shadow database url for migrations target 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#14089]
Command: `prisma migrate diff --from-migrations prisma/migrations --to-empty`
Version: `3.15.2`
Binary Version: `461d6a05159055555eb7dfb337c9fb271cbd4d7e`
Report: https://prisma-errors.netlify.app/report/14099 
OS: `x64 win32 10.0.19044`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine\core\src\commands\diff.rs:127:22] internal error: entered unreachable code: no provider, no shadow database url for migrations target

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

    at handlePanic (C:\Users\...\node_modules\prisma\build\index.js:93373:25)
    at ChildProcess.<anonymous> (C:\Users\...\node_modules\prisma\build\index.js:93382:15)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

Rust Stacktrace:
```
Starting migration engine RPC server
[migration-engine\core\src\commands\diff.rs:127:22] internal error: entered unreachable code: no provider, no shadow database url for migrations target
```

**Comment by jkomyno** [comment]
Closing as it's already fixed.
