### ISSUE TITLE
Formatter: thread 'main' panicked at 'not yet implemented'

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#14090]
Command: `prisma format`
Version: `3.15.2`
Binary Version: `461d6a05159055555eb7dfb337c9fb271cbd4d7e`
Report: https://prisma-errors.netlify.app/report/14104 
OS: `x64 linux 5.13.0-48-generic`

JS Stacktrace:
```
Error: Command failed with exit code 101: /var/www/.../node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x format -i /var/www/.../libs/prisma/schema.prisma
    at _Format.parse (/var/www/.../node_modules/prisma/build/index.js:96309:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Rust Stacktrace:
```
Error: Command failed with exit code 101: /var/www/.../node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x format -i /var/www/.../libs/prisma/schema.prisma
thread 'main' panicked at 'not yet implemented', libs/datamodel/parser-database/src/walkers/relation/inline.rs:146:46
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: parser_database::walkers::relation::inline::InlineRelationWalker::forward_relation_field_arity
   4: datamodel::reformat::Reformatter::new
   5: datamodel::reformat::reformat
   6: prisma_fmt::format::run
   7: prisma_fmt::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at makeError (/var/www/.../node_modules/prisma/build/index.js:3673:18)
    at handlePromise (/var/www/.../node_modules/prisma/build/index.js:4426:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async formatSchema (/var/www/.../node_modules/prisma/build/index.js:89016:14)
    at async _Format.parse (/var/www/.../node_modules/prisma/build/index.js:96304:16)
    at async main (/var/www/.../node_modules/prisma/build/index.js:98081:18)
```

**Comment by tomhoule** [comment]
I can confirm this was fixed by https://github.com/prisma/prisma-engines/pull/3030
