### ISSUE TITLE
prisma find RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Mingfunction** [prisma/prisma#14183]
### Bug description

use clint api findMany or findUnique 

ERROR [ExceptionsHandler] Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at /Users/min/project/galaxy-system/node_modules/@prisma/client/runtime/index.js:48499:30
    at Array.reduce (<anonymous>)
    at selectionToFields (/Users/min/project/galaxy-system/node_modules/@prisma/client/runtime/index.js:48467:36)
    at /Users/min/project/galaxy-system/node_modules/@prisma/client/runtime/index.js:48617:55
    at Array.reduce (<anonymous>)
    at selectionToFields (/Users/min/project/galaxy-system/node_modules/@prisma/client/runtime/index.js:48467:36)
    at /Users/min/project/galaxy-system/node_modules/@prisma/client/runtime/index.js:48617:55
    at Array.reduce (<anonymous>)
    at selectionToFields (/Users/min/project/galaxy-system/node_modules/@prisma/client/runtime/index.js:48467:36)
    at /Users/min/project/galaxy-system/node_modules/@prisma/client/runtime/index.js:48617:55

### Environment & setup

- OS: Mac OS
- Database: mongodb
- Node.js v16.15.0

### Prisma Version

```
prisma                  : 4.0.0
@prisma/client          : 4.0.0
Current platform        : darwin-arm64
```

**Comment by Mingfunction** [comment]
in schema
type UsersRouterAuth {
  auth     Boolean
  children UsersRouterAuth[]
  path     String
  type     String
}
