### ISSUE TITLE
Serverless framework typescript template integration issue

### ISSUE THREAD

**Issue by kaykhan** [prisma/prisma#14258]
### Bug description

I am building a serverless function using the serverless framework. However im having an issue with running it locally

prisma/schema.prisma

generator client {
    provider      = "prisma-client-js"
    binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

serverless.ts 

    package: {
        individually: true,
        patterns: [
            "!node_modules/.prisma/client/libquery_engine-*",
            "node_modules/.prisma/client/libquery_engine-rhel-*",
            "!node_modules/prisma/libquery_engine-*",
            "!node_modules/@prisma/engines/**",
        ],
    },

npx prisma generate && npm install 

sls invoke local -f main

:heavy_multiplication_x: Error: ENOENT: no such file or directory, open ''/.esbuild/.build/node_modules/.prisma/client/schema.prisma'

What am i doing wrong here?

attempting to follow this example: https://github.com/prisma/prisma-examples/tree/latest/deployment-platforms/aws-lambda

note: i am using the serverless aws-nodejs-typescirpt template which uses serverless-esbuild and not serverless-webpack

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma                  : 4.0.0
@prisma/client          : 4.0.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : da41d2bb3406da22087b849f0e911199ba4fbf11
Studio                  : 0.465.0

```

**Comment by kaykhan** [comment]
I updated package.patterns to include schema.prisma as i noticed in the build folder it did not exist 

```
/.esbuild/.build/node_modules/.prisma
```

```
   package: {
        individually: true,
        patterns: [
            "!node_modules/.prisma/client/libquery_engine-*",
            "node_modules/.prisma/client/libquery_engine-rhel-*",
            "node_modules/.prisma/client/schema.prisma", // added this.
            "!node_modules/prisma/libquery_engine-*",
            "!node_modules/@prisma/engines/**",
        ],
    },
```

It got me further and then errored again.

```
null PrismaClientInitializationError:
Invalid `prisma.contract.upsert()` invocation:


  Query engine library for current platform "debian-openssl-1.1.x" could not be found.
You incorrectly pinned it to debian-openssl-1.1.x

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/home/kay/checkpoint/nft-transpose/.esbuild/.build/libquery_engine-debian-openssl-1.1.x.so.node")

Searched Locations:

  /home/kay/checkpoint/.prisma/client
  /home/kay/checkpoint/nft-transpose/node_modules/@prisma/client
  /home/kay/checkpoint/nft-transpose/.esbuild
  /home/kay/checkpoint/nft-transpose/.esbuild/.build/node_modules/.prisma/client
  /home/kay/checkpoint/nft-transpose/.esbuild/.build/node_modules/.prisma/client
  /tmp/prisma-engines
  /home/kay/checkpoint/nft-transpose/.esbuild/.build/node_modules/.prisma/client

You already added the platforms "debian-openssl-1.1.x", "rhel-openssl-1.0.x" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma/issues/new
    at RequestHandler.handleRequestError (/home/kay/checkpoint/nft-transpose/node_modules/@prisma/client/runtime/index.js:49676:13)
    at PrismaClient2._getDmmf (/home/kay/checkpoint/nft-transpose/node_modules/@prisma/client/runtime/index.js:50669:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PrismaClient2._executeRequest (/home/kay/checkpoint/nft-transpose/node_modules/@prisma/client/runtime/index.js:50599:22)
    at async PrismaClient2._request (/home/kay/checkpoint/nft-transpose/node_modules/@prisma/client/runtime/index.js:50572:18)
    at async Promise.all (index 0)
    at async InsertContracts (/home/kay/checkpoint/nft-transpose/src/models/contracts/contract.repo.ts:18:26)
    at async FetchCollectionByAddress (/home/kay/checkpoint/nft-transpose/src/functions/main.ts:22:35)
    at async MainHandler (/home/kay/checkpoint/nft-transpose/handler.ts:14:28) {
  clientVersion: '4.0.0',
  errorCode: undefined
}
```

**Comment by Pasi-D** [comment]
Getting the same issue when deployed & tested via API gateway.
![image](https://user-images.githubusercontent.com/19520064/178749275-ebcdc5d4-ee2b-4e3b-a6ac-897d50b83cac.png)

But this works with `serverless-offline`. package pattern in `serverless.ts` is as follow.

```serverless.ts
package: {
        individually: true,
        // Added to decrease output size to prevent size related issues.
        // Ref https://www.prisma.io/docs/guides/deployment/deployment-guides/caveats-when-deploying-to-aws-platforms#aws-lambda-upload-limit
        patterns: [
            "node_modules/.prisma/client/*",
            "!node_modules/.prisma/client/libquery_engine-*",
            "node_modules/.prisma/client/libquery_engine-rhel-*",
            "!node_modules/prisma/libquery_engine-*",
            "!node_modules/@prisma/engines/**"
        ]
},
```

**Comment by ThaFishDance** [comment]
I have a similar issue, serverless-offline works but i get a no such file or dir

**Comment by kaykhan** [comment]
I tihnk the documentation is not as clear as it could be when it comes to this matter. I did find a workout and someone can correct me if im wrong but i think the intention to get this workng in a local and deployed version requires you to know the engine version at the time of build.

So you can add something like this to the serverless.ts file

The binary to get this running in a serverless environment (aws lambda) is ` rhel-openssl-1.0.x` i atleast know this from the docs. 
https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda#binary-targets-in-schemaprisma
Then locally from the error messages we receive when we attempt to `sls invoke local  -f` i need this engine `libquery_engine-debian-*` i guess because im using ubuntu. 


```
let prismaPatterns: any = [];
if (process.env.PRISMA_BINARY_TARGET === "rhel-openssl-1.0.x") {
    prismaPatterns = ["node_modules/.prisma/client/libquery_engine-rhel-*"];
} else {
    prismaPatterns = ["node_modules/.prisma/client/libquery_engine-debian-*"];
}

const serverlessConfiguration: AWS = {
    ...
    package: {
        individually: true,
        patterns: [
            "!node_modules/.prisma/client/libquery_engine-*",
            "node_modules/.prisma/client/schema.prisma",
            "!node_modules/prisma/libquery_engine-*",
            "!node_modules/@prisma/engines/**",
            ...prismaPatterns,
        ],
    },
...
}
```
