### ISSUE TITLE
Print useful error message when `canConnectToDatabase` is an unexpected error

### ISSUE THREAD

**Issue by hugorut** [prisma/prisma#14279]
### Bug description

I had recently upgraded my prisma version to `4` and when running a `npx prisma migrate dev` I was running into a `Error: Error: Migration engine exited.` error. This message gave me no context about how I could fix/resolve the error. Even when I ran with with `export DEBUG="prisma*"` I still could not find useful information:

```
  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at /my/path/dashboard/api/package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from /my/path/dashboard/api/.env +0ms
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /my/path/dashboard/api/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:getConfig  Loaded Node-API Library +7ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +1ms
  prisma:loadEnv  project root found at /my/path/dashboard/api/package.json +11ms
  prisma:tryLoadEnv  Environment variables loaded from /my/path/dashboard/api/.env +11ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /my/path/dashboard/api/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +1ms
  prisma:getConfig  Loaded Node-API Library +0ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +1ms
Datasource "db": PostgreSQL database "dashboard", schema "public" at "localhost:5432"

  prisma:getDMMF  Using CLI Query Engine (Node-API Library) at: /my/path/dashboard/api/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:getDMMF  Loaded Node-API Library +0ms
  prisma:getDMMF  unserialized dmmf result ready +8ms
  prisma:getDMMF  dmmf retrieved without errors in getDmmfNodeAPI +4ms
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /my/path/dashboard/api/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +13ms
  prisma:getConfig  Loaded Node-API Library +0ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +1ms
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /my/path/dashboard/api/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:getConfig  Loaded Node-API Library +0ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +1ms
Error: Error: Migration engine exited.
    at canConnectToDatabase (/my/path/dashboard/api/node_modules/prisma/build/index.js:92205:13)
    at async ensureDatabaseExists (/my/path/dashboard/api/node_modules/prisma/build/index.js:92902:22)
    at async _MigrateDev.parse (/my/path/dashboard/api/node_modules/prisma/build/index.js:
```

I had to manually edit the built `prisma/build/index.js` file to add an additional `console.log` to get an error message. i.e. the line above this entry: https://github.com/prisma/prisma/blob/27c038fa2b61161fb9164f826f0ef1b574dff445/packages/internals/src/migrateEngineCommands.ts#L108

Only after this did I get a useful error which showed me:

```
Error: Env var PRISMA_MIGRATION_ENGINE_BINARY is provided, but provided path /my/path/dashboard/api/node_modules/@prisma/engines/migration-engine-darwin can't be resolved.
    at resolveBinary (/my/path/dashboard/api/node_modules/prisma/build/index.js:88948:13)
    at execaCommand (/my/path/dashboard/api/node_modules/prisma/build/index.js:92248:54)
    at canConnectToDatabase (/my/path/dashboard/api/node_modules/prisma/build/index.js:92184:11)
    at ensureDatabaseExists (/my/path/dashboard/api/node_modules/prisma/build/index.js:92903:28)
    at async _MigrateDev.parse (/my/path/dashboard/api/node_modules/prisma/build/index.js:95109:26)
    at async main (/my/path/dashboard/api/node_modules/prisma/build/index.js:98240:18)
```

It should be a simple fix to log the error within the `else` statement here: https://github.com/prisma/prisma/blob/27c038fa2b61161fb9164f826f0ef1b574dff445/packages/internals/src/migrateEngineCommands.ts#L108. I would open a PR for this however, I'm not sure how best you want to handle the error e.t.c.

### Expected behavior

I would like to see additional error context from from the connection error.

### Prisma information

n/a - any schema will work to reproduce

### Environment & setup

- OS: Mac OS Monterey M1
- Database: Postgresql
- Node.js version: v16.13.1

### Prisma Version

```
4.0.0
```

**Comment by janpio** [comment]
Thanks for this issue, makes total sense.

Just do double check: The file did indeed not exist, so the error you found was indeed correct in the end at least?

**Comment by hugorut** [comment]
@janpio yes that is correct, the file did not exist and it was a valid error.
