### ISSUE TITLE
The error is incorrectly pointed out when using the $transaction method

### ISSUE THREAD

**Issue by aya-eiya** [prisma/prisma#14373]
### Bug description

When multiple update queries are set to the $transaction method and an error occurs in one of them, it is always indicated that the first query in the array of arguments has failed.

### How to reproduce

https://github.com/aya-eiya/prisma-tx-error

schema.prisma

```schema.prisma
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id        Int      @id @default(autoincrement())
  email     String   @unique
  memo      String?
  createdAt DateTime @default(now())
}

```

main.js

```javascript
const { PrismaClient } = require('@prisma/client')

async function main() {
  const prisma = new PrismaClient()
  await prisma.user.deleteMany({})
  await prisma.$transaction([
    prisma.user.updateMany({
      where: {
        email: {
          contains: '@corp.com',
        },
      },
      data: {
        memo: 'corp',
      },
    }),
    prisma.user.update({
      where: {
        id: 1,
      },
      data: {
        memo: 'id is 1',
      },
    }),
  ])
}

main()
```

This script will get

```
./src/main.js:7:17

   4 const prisma = new PrismaClient()
   5 await prisma.user.deleteMany({})
   6 await prisma.$transaction([
→  7   prisma.user.updateMany(
  An operation failed because it depends on one or more records that were required but not found. Record to update not found.
    at RequestHandler.handleRequestError (/Users/aya-eiya/Work/prisma/node_modules/@prisma/client/runtime/index.js:49670:13)
    at RequestHandler.request (/Users/aya-eiya/Work/prisma/node_modules/@prisma/client/runtime/index.js:49652:12)
    at async PrismaClient._request (/Users/aya-eiya/Work/prisma/node_modules/@prisma/client/runtime/index.js:50572:18)
    at async Promise.all (index 0)
    at async main (/Users/aya-eiya/Work/prisma/src/main.js:6:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:45257) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:45257) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

> `An operation failed because it depends on one or more records that were required but not found. Record to update not found.
`

is never happen on `prisma.user.updateMany`. the actual error line is `prisma.user.update`.

this makes investigating difficult and causes confusion. so I think this must be a bug of $trancation.

### Expected behavior

It must point out an actual error line.

### Environment & setup

node: v14.17.0
OS: macOS 12.4 (21F79)
Kernel: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101

### Prisma Version

```
"@prisma/client": "^4.0.0",
"prisma": "^4.0.0"
```

**Comment by puncleV** [comment]
Reproduced with `^3.15.2` version. All errors in array of queries for `$transaction` being printed as an error within the first query call.
