### ISSUE TITLE
Prisma2 Application Potentially Creating DB Connections per API Request

### ISSUE THREAD

**Issue by daaasbu** [prisma/prisma#1438]
I have had a prisma app running in GCP that connects to a postgres instance also running in GCP for about a day. 

All API calls started failing to the app with: 
```
2020-01-24 21:15:52.056 CSTError querying the database: db error: FATAL: remaining connection slots are reserved for non-replication superuser connections
2020-01-24 21:15:52.056 CST at PhotonFetcher.request (/app/node_modules/@prisma/photon/index.js:62:23)
2020-01-24 21:15:52.056 CST at runMicrotasks (<anonymous>)
2020-01-24 21:15:52.056 CST at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-01-24 21:15:52.058 CSTGET500395 B44 msChrome 79 https://flag-api-vykaoik56q-uc.a.run.app/switches
```

Looks like the app is holding open connections. I have basically the boiler plate from the prisma init: 

```
import { GraphQLServer } from 'graphql-yoga';
import { schema } from './schema';
import { createContext } from './context';
import getSwitchesWithAuthHeader from './controllers/switches';
import * as cors from 'cors';

const server = new GraphQLServer({ schema, context: createContext });
server.express.use(cors());
server.express.get('/switches', getSwitchesWithAuthHeader);

server.start(
  { port: 8080 },

  () =>
    console.log(
      `🚀 Server ready at: http://localhost:8080\n⭐️ See sample queries: http://pris.ly/e/ts/graphql#5-using-the-graphql-api`,
    ),
);
```

Versions:  
```
    "@prisma/photon": "2.0.0-alpha.538",
    "basic-auth": "^2.0.1",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "graphql": "14.5.8",
    "graphql-yoga": "1.18.3",
    "nexus": "0.12.0-rc.5",
```

Restarting my database or the application fixes the issue temporarily.

**Comment by pantharshit00** [comment]
Hi @daaasbu,

We generate a connection pool by default based on the number of physical CPU cores that your machine has(It is `num_physical_cpus * 2 + 1`). It is possible that the amount of connection is exceeding the connection limits that your database provides.

In order to fix this, you can manually specify the connection limit in the datasource, for example: 

```
postgresql://postgres:postgres@yourhost.com:5432/test_db?schema=myschema&connection_limit=20
```

Docs about connection_limit: https://github.com/prisma/prisma2/blob/754620fcf105788f09c31a3a2f461852ad432eea/docs/core/connectors/postgresql.md#configuration-options

Let me know if this addresses your concerns

**Comment by daaasbu** [comment]
Hmm, well I only have one instance of the application running in docker, so there is only 1 cpu and the database can have 100 concurrent connections. 

I'm guessing its holding onto connections when it shouldn't. It doesn't happen right away, it builds up over time, which makes me think its leaking connections.

**Comment by pimeys** [comment]
I'm trying to replicate this. Now just working with the rust core without the js layer. Having a local database with the following uri `postgresql://user:password@localhost:5432/postgres?schema=sql_load_test&connection_limit=5`.

Starting the Query Engine against the database and querying PostgreSQL about the number of open connections:

```sql
postgres=# SELECT sum(numbackends) FROM pg_stat_database;
-[ RECORD 1 ]
sum | 6
```

Which is my psql client and 5 connections for the pool. I try to keep this open, query every now and then and see if the async pool has a problem with leaked connections, which might be possible due to their nature, but might also be something else.

@timsuchanek suggested the JS client also might not close the QE cleanly keeping the connections open. We'll put some effort now to replicate the issue here.

**Comment by pimeys** [comment]
Oh, and when I close down the core, database reports correctly I only have one connection open:

``` sql
postgres=# SELECT sum(numbackends) FROM pg_stat_database;
-[ RECORD 1 ]
sum | 1
```

**Comment by RDMStreet** [comment]
I have a similar problem with prisma2 studio. One instance of the Studio created 61 instances of query-engine-debian-openssl and took all 300 available postgresql connections.
![Screenshot_114_2](https://user-images.githubusercontent.com/8494787/73538316-c8274f00-443b-11ea-9760-f0e6d9a5d90f.png)

**Comment by bamne123** [comment]
Facing Same Issue, In my Case, its Creating 6-7 connections per request and not releasing it. 
Eventually Its fails creating DB Connection.

```
show status like 'Conn%';
```
Using Above Statement get following result.
```
Connections	52666
```

package.json
```
"@prisma/client": "2.0.0-preview021",
"nexus": "0.12.0-rc.9",
"nexus-prisma": "0.9.1",
"prisma2": "2.0.0-preview021",
```

**Comment by timsuchanek** [comment]
Thanks for reporting everyone!
Can you please show me, how you instantiate the Prisma Client?
You should normally just instantiate one client and reuse it for all requests.

**Comment by janpio** [comment]
Ping @daaasbu @RDMStreet @bamne123 - can you please help us figure out what is going on here? Thanks.

**Comment by janpio** [comment]
Internal Note: Dropping until we have a reproduction or more information here.

**Comment by asciant** [comment]
I know this isn't of much assistance, although I experienced the same issue in `2.0.0-beta.1`, although I was not aware of the issue until I had already made some minor code changes (so I wasn't able to reproduce/provide a reproduction).

I ran @pimeys query when I noticed the error (and came across this issue).

```
asciant=# SELECT sum(numbackends) FROM pg_stat_database;
 sum
-----
  98
(1 row)
```

After re-booting the server (the environment is `now dev`).

```
asciant=# SELECT sum(numbackends) FROM pg_stat_database;
 sum
-----
   5
(1 row)
```

I'm running Prisma in NextJS using API Routes with Apollo Server Micro. The Prisma Client is instantiated when the Apollo Server is created.

```
import { ApolloServer } from 'apollo-server-micro'
import { PrismaClient } from '@prisma/client'
import schema from './schema'

const apolloServer = new ApolloServer({
  schema,
  context: ({ req, res }) => {
    return {
      req,
      res,
      prisma: new PrismaClient()
    }
  }
})

export default apolloServer
```

At the time the connections spiked, NextJS was throwing errors (both on server render and client render) but nothing major. Pre-beta I was using m-n (many to many relations) but after perusing the updated docs (because I had to change the data model anywas for my 1-1 relations) I updated a couple of them to 1-m relations. 

As I result, I had some code needing updating, as I was reducing off an array of results, but now it is a single object.

The error NextJS was throwing:

```
GraphQL error occurred [getDataFromTree] TypeError: user.reduce is not a function
    at Media (/Users/asciant/Projects/crimson/.next/server/static/development/pages/webpack:/components/Card/Media.jsx:17:1)
    at processChild (/Users/asciant/Projects/crimson/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
    at resolve (/Users/asciant/Projects/crimson/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/asciant/Projects/crimson/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/asciant/Projects/crimson/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToStaticMarkup (/Users/asciant/Projects/crimson/node_modules/react-dom/cjs/react-dom-server.node.development.js:4004:27)
    at process (/Users/asciant/Projects/crimson/node_modules/@apollo/react-ssr/lib/react-ssr.cjs.js:38:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Function.WithApollo.getInitialProps (/Users/asciant/Projects/crimson/node_modules/next-with-apollo/lib/withApollo.js:53:29)
    at Object.loadGetInitialProps (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/lib/utils.js:59:19)
    at Object.renderToHTML (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/render.js:252:17)
    at DevServer.renderToHTMLWithComponents (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:635:26)
    at DevServer.renderToHTML (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:775:28)
    at DevServer.renderToHTML (/Users/asciant/Projects/crimson/node_modules/next/dist/server/next-dev-server.js:15:539)
    at DevServer.render (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:514:22)
    at Object.fn (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:372:17)
    at Router.execute (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/router.js:137:32)
    at DevServer.run (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:487:29)
    at DevServer.handleRequest (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:139:20)
TypeError: user.reduce is not a function
    at Media (/Users/asciant/Projects/crimson/.next/server/static/development/pages/webpack:/components/Card/Media.jsx:17:1)
    at processChild (/Users/asciant/Projects/crimson/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
    at resolve (/Users/asciant/Projects/crimson/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/asciant/Projects/crimson/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/asciant/Projects/crimson/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/Users/asciant/Projects/crimson/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at render (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/render.js:83:16)
    at renderPage (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/render.js:406:16)
    at Object.ctx.renderPage (/Users/asciant/Projects/crimson/.next/server/static/development/pages/webpack:/pages/_document.jsx:72:1)
    at Function.getInitialProps (/Users/asciant/Projects/crimson/.next/server/static/development/pages/webpack:/node_modules/next/dist/pages/_document.js:7:1)
    at Function.module.exports../pages/_document.jsx.MyDocument.getInitialProps (/Users/asciant/Projects/crimson/.next/server/static/development/pages/webpack:/pages/_document.jsx:77:1)
    at Object.loadGetInitialProps (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/lib/utils.js:59:29)
    at Object.renderToHTML (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/render.js:410:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at DevServer.renderToHTMLWithComponents (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:635:26)
    at DevServer.renderToHTML (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:775:28)
    at DevServer.renderToHTML (/Users/asciant/Projects/crimson/node_modules/next/dist/server/next-dev-server.js:15:539)
    at DevServer.render (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:514:22)
    at Object.fn (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:372:17)
    at Router.execute (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/router.js:137:32)
    at DevServer.run (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:487:29)
    at DevServer.handleRequest (/Users/asciant/Projects/crimson/node_modules/next/dist/next-server/server/next-server.js:139:20)
```

I should note, there were so many of these that the scroll of my terminal window was completely used by these two errors repeating over and over.

I will report back if I am able to reproduce.

**Comment by asciant** [comment]
It seems this issue is reproducible in NextJS when a `TypeError` or `ReferenceError` occurs on the server render, after running a query within `getInitialProps`.

I will try create a functional reproduction outside of my application.

**Comment by asciant** [comment]
@janpio @pantharshit00 I was able to reproduce the issue. In a very stripped down version of my NextJS application. 

Each time the error (the type error that I created on line 17 of `pages/index.js`)  is thrown by NextJS, the sum of the `SELECT sum(numbackends) FROM pg_stat_database;` query in PSQL increases by 1.

I am running `postgres (PostgreSQL) 12.2` locally.

To reproduce (should be as simple as the below):

1. Clone the repository (https://github.com/asciant/prisma-next-db-slots);
2. Have your own local Postgres server running, and setup the `DATABASE_URL` connection string environment variable;
3. Install the dependencies (`npm install`), generate the prisma client (`npx prisma generate`) and run the migration (`npx prisma migrate up --experimental`);
4. Start the server (`npm run dev`) and visit the page in the browser (`http://localhost:3000`).

Each time the page loads/receives a request the connection count will increase by 1 until the connection limit is reached.

Hopefully this helps, let me know if you need anything else.

**Comment by pantharshit00** [comment]
@asciant This is happening because you are creating a Prisma Client instance on every request.

See my comment here: https://github.com/prisma/prisma/issues/2143#issuecomment-611481435

**Comment by gustawdaniel** [comment]
But it could be better documented, in exemplary applications how to manage connection to database in nexus-graphql

**Comment by pantharshit00** [comment]
Please open an issue about that here: https://github.com/graphql-nexus/nexus-schema-plugin-prisma

**Comment by timsuchanek** [comment]
Closing this due to inactivity.
