### ISSUE TITLE
MySQL: Expected parent IDs to be set when ordering by parent ID.

### ISSUE THREAD

**Issue by eric183** [prisma/prisma#14425]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.15.0           | 
| OS              | rhel-openssl-1.0.x |
| Prisma Client   | 4.0.0              |
| Query Engine    | da41d2bb3406da22087b849f0e911199ba4fbf11|
| Database        | mysql              |

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:client dirname /var/task/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /var/task/node_modules/.prisma/client
prisma:client clientVersion: 4.0.0
prisma:client clientEngineType: library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine:loader Searching for Query Engine Library in /var/task/node_modules/.prisma/client
prisma:client:libraryEngine:loader loadEngine using /var/task/node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x.so.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.0.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
prismaClient.user
  .findUnique({
    where: {
      email: input?.email,
    },
  })
  .words({
    select: {
      id: true,
      score: true,
      master: true,
      wordData: true,
    },
  });
```

## Schema
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["referentialIntegrity"]
}

datasource db {
  provider             = "mysql"
  url                  = env("DATABASE_URL")
  referentialIntegrity = "prisma"
}

model Account {
  id                String   @id @default(cuid())
  userId            String   @unique
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?  @db.LongText
  access_token      String?  @db.LongText
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?  @db.Text
  session_state     String?
  createdAt         DateTime @default(now())
  updatedAt         DateTime @updatedAt
  isAdmin           Boolean  @default(false)
  isActive          Boolean  @default(true)
  isDeleted         Boolean  @default(false)
  user              User     @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  password      String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
  words         Word[]
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @db.LongText
  userId       String   @unique
  expires      DateTime
  user         User?    @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

model Word {
  id        String    @id @default(cuid())
  score     Int       @default(0)
  master    Boolean   @default(false)
  wordData  WordData? @relation(fields: [word], references: [searchingWord])
  word      String    @unique
  user      User?     @relation(fields: [userId], references: [id])
  userId    String?
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
}

model WordData {
  id              String   @id @default(cuid())
  createdAt       DateTime @default(now())
  updatedAt       DateTime @updatedAt
  searchingWord   String   @unique
  searchingEngine String
  translations    Json?
  userWords       Word[]
}

```

## Prisma Engine Query
```
Query:
{
  "modelName": "WordData",
  "operation": "findMany",
  "args": {
    "take": 100,
    "skip": 0,
    "select": {
      "id": true,
      "createdAt": true,
      "updatedAt": true,
      "searchingWord": true,
      "searchingEngine": true,
      "translations": true,
      "userWords": true
    }
  }
}
```

**Comment by eric183** [comment]
It's so weird, I logged into the other account instead, and the error didn't show up.
Please help me, anything I set wrong?

**Comment by eric183** [comment]
btw, I am using next-auth for logging thing,  I guessed that must be something wrong there

**Comment by eric183** [comment]
It seems like prisma studio display error.
I used prisma studio, there displays no data in my User table.
but I found data in my User table when I connected to pscale shell, "Select * From User;" ,

**Comment by garrensmith** [comment]
@eric183 Could you detail how you generated this error?
A reproduction would be really helpful.

**Comment by gabrielbusarello** [comment]
Hi guys,
Maybe I can bring some new information to this case.
I'm facing this problem too, and I think I know de causes, and I want to know if it is the cause.
I have this model:
```
model BudgetApprover {
  id                 String              @id @default(cuid())
  type               Int
  userId             String
  user               User                @relation(fields: [userId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  accountingAccounts AccountingAccount[]
  costCenters        CostCenter[]
  accountingItems    AccountingItem[]
  classValues        ClassValue[]

  @@unique([ type, userId ])
}

// The model from those four fields are the same as this (Are four different models in my schema):

model AccountingAccount | costCenters | accountingItems | classValues {
  code            String           @id @db.VarChar(20)
  name            String           @db.VarChar(50)
  budgets         Budget[]
  budgetApprovers BudgetApprover[]
}
```
I have two endpoints that are requested in one page at the same moment, and runs this same query. I read in the docs, that Prisma caches the findUnique method when requested in a tick.
```
return this.prisma.budgetApprover.findUnique({
        where: { type_userId: { userId, type: BudgetApproverType.CORPORATIVE_LEVEL } }
});
```
In my codes, I use async/await, and when this executes, the first request ran and I get an OK and the second one returns:
```
Invalid `prisma.budgetApprover.findUnique()` invocation:
4|rodalog-staging  |   PANIC: Expected parent IDs to be set when ordering by parent ID. in query-engine/core/src/interpreter/query_interpreters/inmemory_record_processor.rs:71:18
```
I'm facing this problem too, and not just in prisma studio. I simulate this on studio, by querying `accountingAccount` the error is below:
```
Message: Error in Prisma Client request: 


Invalid `prisma.accountingAccount.findMany()` invocation:


  Expected parent IDs to be set when ordering by parent ID.
  
Query:
prisma.accountingAccount.findMany({
  where: {
    AND: [
    ]
  },
  take: 100,
  skip: 0,
  select: {
    code: true,
    name: true,
    budgets: true,
    budgetApprovers: true,
  }
})
```
Maybe do I have to use Promise.then to this cases?
I can put the codes that I developed, if you want.

**Comment by janpio** [comment]
@gabrielbusarello Can you help us understand better how to reproduce this, either via code or via Studio? Right now the connection to Studio sounds pretty wild to us, but I totally trust that this is real for you - we are just missing some detailed information on how to reproduce this. Thanks!

**Comment by eric183** [comment]
> @eric183 Could you detail how you generated this error? A reproduction would be really helpful.

Then I deleted data from Prisma Studio, it did not work (that Data is still in the document by shell checking), and the error showed up as above.

So after that, I switched to shell command, and the deleting worked ( error disappeared )

**Comment by jkomyno** [comment]
Hi, I have attempted reproducing this issue with both @eric183's and @gabrielbusarello's schemas, with no success, even when simulating several Prisma requests of the same type at the same time.
Would you please be able to share a SQL dump of your database and a snippet that allow us to reproduce this issue? If you were able to do so by sharing a self-contained repository, that'd be a huge help for us. Thanks

**Comment by hampuskraft** [comment]
Hi there, I managed to reproduce this issue with a MariaDB schema looking like this:

```sql
CREATE TABLE `player_data` (
  `xuid` varchar(16) NOT NULL,
  `player` varchar(16) NOT NULL,
  -- Truncated
  PRIMARY KEY (`xuid`),
  UNIQUE KEY `player` (`player`) USING BTREE,
  -- Truncated
  FULLTEXT KEY `player_2` (`player`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE `player_relations` (
  `player_one` varchar(16) NOT NULL,
  `player_two` varchar(16) NOT NULL,
  `status` int(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`player_one`,`player_two`),
  KEY `player_two` (`player_two`),
  CONSTRAINT `player_relations_ibfk_1` FOREIGN KEY (`player_one`) REFERENCES `player_data` (`player`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `player_relations_ibfk_2` FOREIGN KEY (`player_two`) REFERENCES `player_data` (`player`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

And the following Prisma models:

```prisma
model PlayerData {
  xuid   String @id
  player String @unique
  // Truncated
  originRelationships PlayerRelationship[] @relation("OriginRelationships")
  targetRelationships PlayerRelationship[] @relation("TargetRelationships")

  @@map("player_data")
}

model PlayerRelationship {
  originPlayerName String     @map("player_one")
  originPlayer     PlayerData @relation("OriginRelationships", fields: [originPlayerName], references: [player])
  targetPlayerName String     @map("player_two")
  targetPlayer     PlayerData @relation("TargetRelationships", fields: [targetPlayerName], references: [player])
  status           Boolean

  @@id([originPlayerName, targetPlayerName])
  @@map("player_relations")
}
```

I managed to track down the root cause:

- A `player_data` record exists with the `player` being `vetele` (lowercase "v").
- A `player_relations` record exists with the `player_one` being `Vetele` (capital "V") and player_two something else.
  The following query is executed:

```ts
const relationships = await prisma.players.playerRelationship.findMany({
  where: {OR: [{originPlayerName: ctx.user.player}, {targetPlayerName: ctx.user.player}]},
  include: {originPlayer: true, targetPlayer: true},
})
```

Which creates the following stacktrace until the `player_relations` record referencing `Vetele` is changed to `vetele`
(the same casing as in the referenced record):

```sh
Error:
Invalid `prisma.playerRelationship.findMany()` invocation:


Inconsistent query result: Field originPlayer is required to return data, got `null` instead.
  File "/usr/src/app/prisma/players/generated/runtime/index.js", line 30855, col 13, in RequestHandler.handleRequestError
    throw new PrismaClientUnknownRequestError(message, this.client._clientVersion);
  File "/usr/src/app/prisma/players/generated/runtime/index.js", line 30834, col 12, in RequestHandler.request
    this.handleRequestError({ error: error2, clientMethod, callsite });
  File "/usr/src/app/prisma/players/generated/runtime/index.js", line 31812, col 16, in PrismaClient._request
    return await runInChildSpan(spanOptions.operation, () => {
  File "/usr/src/app/src/accounts/relationships.ts", line 22, col 27, in Object.handler
  File "/usr/src/app/src/api.ts", line 383, col 26, in Object.handler
```

Thanks!

**Comment by jkomyno** [comment]
HI @hampuskraft, thanks for your comment!
So, it seems the issue lies in how MariaDB deals with string capitalization.

## Reproduction

For each of the following reproductions using `mariadb:10`, we assume the database has been truncated.
Moreover, while I managed to get some errors, I didn't get `Expected parent IDs to be set when ordering by parent ID.`.

**Schema**:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model PlayerData {
  xuid   String @id
  player String @unique
  // Truncated
  originRelationships PlayerRelationship[] @relation("OriginRelationships")
  targetRelationships PlayerRelationship[] @relation("TargetRelationships")

  @@map("player_data")
}

model PlayerRelationship {
  originPlayerName String     @map("player_one")
  originPlayer     PlayerData @relation("OriginRelationships", fields: [originPlayerName], references: [player])
  targetPlayerName String     @map("player_two")
  targetPlayer     PlayerData @relation("TargetRelationships", fields: [targetPlayerName], references: [player])
  status           Boolean

  @@id([originPlayerName, targetPlayerName])
  @@map("player_relations")
}
```

1. Create two players with different strings that would be equal in a case-insensitive system, e.g. 'vetele' and 'Vetele'

```typescript
await prisma.playerData.create({
  data: {
    xuid: '1',
    player: 'vetele',
  }
})

await prisma.playerData.create({
  data: {
    xuid: '2',
    player: 'Vetele',
  }
})
```

This fails with the following error:

```text
PrismaClientKnownRequestError: 
Invalid `prisma.playerData.create()` invocation in
/index.ts:27:27

  17   }
  18 })
  19 
→ 20 await prisma.playerData.create(
  Unique constraint failed on the constraint: `player_data_player_key`
    at RequestHandler.handleRequestError (/node_modules/.pnpm/@prisma+client@4.2.1_prisma@4.2.1/node_modules/@prisma/client/runtime/index.js:28838:13)
    at RequestHandler.request (/node_modules/.pnpm/@prisma+client@4.2.1_prisma@4.2.1/node_modules/@prisma/client/runtime/index.js:28820:12)
    at async PrismaClient._request (/node_modules/.pnpm/@prisma+client@4.2.1_prisma@4.2.1/node_modules/@prisma/client/runtime/index.js:29753:16)
    at async main (/index.ts:27:3) {
  code: 'P2002',
  clientVersion: '4.4.0',
  meta: { target: 'player_data_player_key' }
}
```

2. Create a player 'vetele', but reference the player name with a different casing in `PlayerRelationship`, e.g., 'Vitele'

```typescript
await prisma.playerData.create({
  data: {
    xuid: '1',
    player: 'vetele',
  }
})

await prisma.playerData.create({
  data: {
    xuid: '2',
    player: 'Player 2',
  }
})

await prisma.playerRelationship.create({
  data: {
    status: true,
    originPlayerName: 'Vetele',
    targetPlayerName: 'Player 2',
  },
})  

const player = 'Vetele'
const relationships = await prisma.playerRelationship.findMany({
  where: {OR: [{originPlayerName: player}, {targetPlayerName: player}]},
  include: {originPlayer: true, targetPlayer: true},
})
```

This fails with the following error:

```text
PrismaClientUnknownRequestError: 
Invalid `prisma.playerRelationship.findMany()` invocation in
/index.ts:36:57

  33 })  
  34 
  35 const player = 'Vetele'
→ 36 const relationships = await prisma.playerRelationship.findMany(
Inconsistent query result: Field originPlayer is required to return data, got `null` instead.
    at RequestHandler.handleRequestError (/node_modules/.pnpm/@prisma+client@4.4.0_prisma@4.4.0/node_modules/@prisma/client/runtime/index.js:30855:13)
    at RequestHandler.request (/node_modules/.pnpm/@prisma+client@4.4.0_prisma@4.4.0/node_modules/@prisma/client/runtime/index.js:30834:12)
    at async PrismaClient._request (/node_modules/.pnpm/@prisma+client@4.4.0_prisma@4.4.0/node_modules/@prisma/client/runtime/index.js:31812:16)
    at async main (/index.ts:36:25) {
  clientVersion: '4.4.0'
}
```

## Potential Solution

[I believe](https://mariadb.com/kb/en/supported-character-sets-and-collations/) the default collation for MariaDB is `latin1_swedish_ci`, which is accent insensitive and case insensitive.
Could you please try to update your collation to something like `latin1_bin` instead (which is accent sensitive and case sensitive)?

E.g., for changing collation to your whole database, you may run:

```sql
ALTER DATABASE your_database_name COLLATE = 'latin1_bin';
```

**Comment by hampuskraft** [comment]
@jkomyno Thanks, changing the database collation to be case sensitive is unfortunately not an opinion in production since everything relies on case insensitivity. I ran a query that fixed the inconsistent results across our database, which does the trick for now. But yes, I can confirm that a "bin" collation doesn't have this issue in development.

**Comment by aqrln** [comment]
Hi @eric183! We have added support for MySQL 8.0.14 and newer to the `relationJoins` preview feature in Prisma 5.10.0, which we expect to resolve this issue thanks to the database comparing the IDs itself when joining the data.

Does enabling the `relationJoins` preview feature fix this problem for you?

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["relationJoins"]
}
```

Thank you in advance for following up 🙏
