### ISSUE TITLE
Prisma Client doesn't support special database name

### ISSUE THREAD

**Issue by shtse8** [prisma/prisma#14421]
### Bug description

prisma cli can support special database name

but prisma client doesn't support.

the database name is generated from google sql automatically. so it's a common use case.

```
Message: Error in Prisma Client request: 


Invalid `prisma.fetcher.findMany()` invocation:


  Database `'project-355708:asia-east2:project'` does not exist on the database server at `35.21.123.250:3306`.

```

### How to reproduce

1. create a mysql database name with `project-355708:asia-east2:project`
2. push a simple schema
3. run prisma client or simply call prisma studio
4. error occur

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Fetcher {
  id           Int      @id @default(autoincrement())
  name         String   @unique
  foundCount   Int
}
```

### Environment & setup

- OS: Windwos 11
- Database: Mysql 8
- Node.js version: 17.8

### Prisma Version

> prisma                  : 4.1.0
@prisma/client          : 4.1.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 8d8414deb360336e4698a65aa45a1fbaf1ce13d8
Studio                  : 0.467.0

**Comment by garrensmith** [comment]
@shtse8 could you try to urlencode your database connection string. That could be the issue.

**Comment by pimeys** [comment]
I can reproduce this with 4.3.1. `prisma db push` works, a simple client application crashes with the given error.

`prisma/schema.prisma`:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model A {
  id Int @id @default(autoincrement())
}
```

`.env`:

```bash
DATABASE_URL="mysql://root:prisma@10.89.4.3:3306/project-355708:asia-east2:project?schema=public"
```

`script.ts`:

```typescript
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient({
  log: ['query', 'info', 'warn', 'error']
})

async function main() {
  await prisma.a.findMany();
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```

Output from `DEBUG="*" npx ts-node script.ts`:

```
  prisma:tryLoadEnv  Environment variables loaded from /prisma-14421/.env +0ms
  prisma:tryLoadEnv  Environment variables loaded from /prisma-14421/.env +2ms
  prisma:client  dirname /prisma-14421/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /prisma-14421/prisma +0ms
  prisma:client  clientVersion 4.3.1 +0ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /prisma-14421/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /prisma-14421/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node +0ms
  prisma:client  Prisma Client call: +43ms
  prisma:client  prisma.a.findMany(undefined) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findManyA {
    id
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +44ms
  prisma:client:libraryEngine  library starting +0ms
prisma:info Starting a mysql pool with 33 connections.
  prisma:client:libraryEngine  library started +2ms
prisma:query SELECT `project-355708:asia-east2:project`.`A`.`id` FROM `project-355708:asia-east2:project`.`A` WHERE 1=1 /* traceparent=00-00-00-00 */
  prisma:client:request_handler  PrismaClientKnownRequestError: Database `project-355708:asia-east2:project` does not exist on the database server at `10.89.4.3:3306`.
    at prismaGraphQLToJSError (/prisma-14421/node_modules/@prisma/client/runtime/index.js:20426:12)
    at LibraryEngine.buildQueryError (/prisma-14421/node_modules/@prisma/client/runtime/index.js:26363:12)
    at LibraryEngine.request (/prisma-14421/node_modules/@prisma/client/runtime/index.js:26297:22)
    at async RequestHandler.request (/prisma-14421/node_modules/@prisma/client/runtime/index.js:29873:24)
    at async PrismaClient._request (/prisma-14421/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async main (/prisma-14421/script.ts:8:3) {
  code: 'P1003',
  clientVersion: '4.3.1',
  meta: {
    database_name: 'project-355708:asia-east2:project',
    database_host: '10.89.4.3',
    database_port: 3306
  }
} +0ms
PrismaClientKnownRequestError: 
Invalid `prisma.a.findMany()` invocation in
/prisma-14421/script.ts:8:18

  5 })
  6 
  7 async function main() {
→ 8   await prisma.a.findMany(
Database `project-355708:asia-east2:project` does not exist on the database server at `10.89.4.3:3306`.
    at RequestHandler.handleRequestError (/prisma-14421/node_modules/@prisma/client/runtime/index.js:29909:13)
    at RequestHandler.request (/prisma-14421/node_modules/@prisma/client/runtime/index.js:29892:12)
    at async PrismaClient._request (/prisma-14421/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async main (/prisma-14421/script.ts:8:3) {
  code: 'P1003',
  clientVersion: '4.3.1',
  meta: {
    database_name: 'project-355708:asia-east2:project',
    database_host: '10.89.4.3',
    database_port: 3306
  }
}
  prisma:client:libraryEngine  library stopping +23ms
  prisma:client:libraryEngine  library stopped +0ms
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms
```
