### ISSUE TITLE
Prisma thinks "did:ethr:0xe378374c8A932Ba42f81C3c8AACB43D96F6c5824" is a JSON and refuses to use it as string

### ISSUE THREAD

**Issue by capaj** [prisma/prisma#14448]
### Bug description

```
Error: 
  of:gql Invalid `prismaClient.users.findUnique()` invocation in
  of:gql /home/capaj/work-repos/official/official-graphql/graphql/src/models/api/NotificationModel.ts:47:29
  of:gql 
  of:gql   44 }
  of:gql   45 
  of:gql   46 const getUserPicture = (userId: string) => {
  of:gql → 47   return prismaClient.users.findUnique({
  of:gql          where: {
  of:gql            aws_user_id: {
  of:gql              aws_user_id: 'did:ethr:0xe378374c8A932Ba42f81C3c8AACB43D96F6c5824'
  of:gql            }
  of:gql            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  of:gql          },
  of:gql          select: {
  of:gql            picture: true
  of:gql          }
  of:gql        })
  of:gql 
  of:gql Argument aws_user_id: Got invalid value 
  of:gql {
  of:gql   aws_user_id: 'did:ethr:0xe378374c8A932Ba42f81C3c8AACB43D96F6c5824'
  of:gql }
  of:gql on prisma.findUniqueusers. Provided Json, expected String.
  of:gql 
  of:gql 
  of:gql     at Document.validate (/home/capaj/work-repos/official/official-graphql/graphql/node_modules/@prisma/client/runtime/index.js:27181:20)
  of:gql     at PrismaClient._executeRequest (/home/capaj/work-repos/official/official-graphql/graphql/node_modules/@prisma/client/runtime/index.js:29694:17)
  of:gql     at middleware (/home/capaj/work-repos/official/official-graphql/graphql/node_modules/@prisma/client/runtime/index.js:29603:60)
  of:gql     at consumer (/home/capaj/work-repos/official/official-graphql/graphql/node_modules/@prisma/client/runtime/index.js:29618:24)
  of:gql     at /home/capaj/work-repos/official/official-graphql/graphql/node_modules/@sentry/tracing/cjs/integrations/node/prisma.js:65:16
  of:gql     at middleware (/home/capaj/work-repos/official/official-graphql/graphql/node_modules/@prisma/client/runtime/index.js:29600:55)
  of:gql     at consumer (/home/capaj/work-repos/official/official-graphql/graphql/node_modules/@prisma/client/runtime/index.js:29618:24)
  of:gql     at /home/capaj/work-repos/official/official-graphql/graphql/node_modules/@prisma/client/runtime/index.js:29622:135
  of:gql     at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
  of:gql     at callback (/home/capaj/work-repos/official/official-graphql/graphql/node_modules/@prisma/client/runtime/index.js:29622:113) +3ms
```

### How to reproduce

I have schema like this:
```
model users {
  aws_user_id                                               String                         @id @unique(map: "users_aws_user_id_unique") @db.VarChar(255)
    picture                                                   String?                        @db.VarChar(255)
}
```
and running:
```ts
prismaClient.users.findUnique({
      where: {
        aws_user_id: "did:ethr:0xe378374c8A932Ba42f81C3c8AACB43D96F6c5824"
      },
      select: {
        picture: true
      }
    })

```

Gives me the error I have in the bug description.

### Expected behavior

you can use json as string. JSON is a string. Why is prisma even checking whether a string is a json?

### Prisma information

```
model users {
  aws_user_id                                               String                         @id @unique(map: "users_aws_user_id_unique") @db.VarChar(255)
    picture                                                   String?                        @db.VarChar(255)
}
```

### Environment & setup

- OS: ubuntu
- Database: PG
- Node.js version: 18.6.0

### Prisma Version

```
prisma                  : 4.1.0
@prisma/client          : 4.1.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Default Engines Hash    : 8d8414deb360336e4698a65aa45a1fbaf1ce13d8
Studio                  : 0.467.0
```

**Comment by capaj** [comment]
actually I retested this and it seems to work fine, will try to find out more about the previous case and I may reopen if I find out why it is failing
