### ISSUE TITLE
Cannot find module 'fp-ts/*' when using @prisma/migrate and @prisma/internals

### ISSUE THREAD

**Issue by okry** [prisma/prisma#14453]
### Bug description

When running Migrate from `@prisma/migrate` I get an error from my installed peer dependency `@prisma/internals` stating "Error: Cannot find module 'fp-ts/TaskEither'". Sometimes it will state this same error, but for other `fp-ts` packages.

The full error below:

```
Error: Cannot find module 'fp-ts/TaskEither'
Require stack:
- /snapshot/repo/node_modules/@prisma/internals/dist/resolveBinary.js
- /snapshot/repo/node_modules/@prisma/internals/dist/engine-commands/formatSchema.js
- /snapshot/repo/node_modules/@prisma/internals/dist/engine-commands/index.js
- /snapshot/repo/node_modules/@prisma/internals/dist/index.js
- /snapshot/repo/node_modules/@prisma/migrate/dist/commands/DbCommand.js
- /snapshot/repo/node_modules/@prisma/migrate/dist/index.js
- /snapshot/repo/packages/prisma-migrator/dist/index.js
- /snapshot/repo/packages/on-prem/dist/js/src/main.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/snapshot/repo/node_modules/@prisma/internals/dist/resolveBinary.js:36:18)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/repo/node_modules/@prisma/internals/dist/resolveBinary.js',
    '/snapshot/repo/node_modules/@prisma/internals/dist/engine-commands/formatSchema.js',
    '/snapshot/repo/node_modules/@prisma/internals/dist/engine-commands/index.js',
    '/snapshot/repo/node_modules/@prisma/internals/dist/index.js',
    '/snapshot/repo/node_modules/@prisma/migrate/dist/commands/DbCommand.js',
    '/snapshot/repo/node_modules/@prisma/migrate/dist/index.js',
    '/snapshot/repo/packages/prisma-migrator/dist/index.js',
    '/snapshot/repo/packages/on-prem/dist/js/src/main.js'
  ],
  pkg: true
}
```

### How to reproduce

1. Create a script that runs Migrate from `@prisma/migrate` over npm.
2. pkg script into an executable. (might not be necessary)
3. Run executable.

### Expected behavior

 The Migrate executable should be able to migrate a prisma database through the executable. I am currently using this approach for creating the Migrate executable https://github.com/prisma/prisma/issues/4703#issuecomment-879857806.

### Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["rhel-openssl-1.0.x", "native"]
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Customer {
  id        Int              @id @default(autoincrement())
  name      String           @db.VarChar(255)
  clientId  String           @unique @map("client_id") @db.VarChar(255)
  createdAt DateTime         @default(now()) @map("created_at") @db.DateTime(6)
  updatedAt DateTime         @default(now()) @map("updated_at") @db.DateTime(6)
  projects  Project[]
  servers   ServerLocation[]

  @@map("customer")
}

...
```

### Environment & setup

- OS: CentOS 7
- Database: MySQL:8
- Node.js version: v14.17.1

### Prisma Version

```
4.1.0
```

**Comment by aqrln** [comment]
cc @jkomyno

**Comment by jkomyno** [comment]
Preconditions:
- install `@prisma/migrate` and its peerDependency `@prisma/internals` as dependencies. I'm targeting `v4.1.0`.

So far I'm spotting the following, regardless of whether I'm using a commonjs (*.js) or module (*.mjs) JavaScript file:

```text
Error: Cannot find module '@prisma/engines-version'
Require stack:
- /Users/jkomyno/work/prisma/reprod-14453/node_modules/@prisma/migrate/dist/Migrate.js
- /Users/jkomyno/work/prisma/reprod-14453/node_modules/@prisma/migrate/dist/commands/DbExecute.js
- /Users/jkomyno/work/prisma/reprod-14453/node_modules/@prisma/migrate/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/jkomyno/work/prisma/reprod-14453/node_modules/@prisma/migrate/dist/Migrate.js:29:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jkomyno/work/prisma/reprod-14453/node_modules/@prisma/migrate/dist/Migrate.js',
    '/Users/jkomyno/work/prisma/reprod-14453/node_modules/@prisma/migrate/dist/commands/DbExecute.js',
    '/Users/jkomyno/work/prisma/reprod-14453/node_modules/@prisma/migrate/dist/index.js'
  ]
}
```

After installing `@prisma/engines-version@4.1.0`, the script runs as expected:

```text
❯ npm run dev

> reprod-14453@1.0.0 dev
> node index.js


Database already exists
diagnoseResult {
  history: null,
  failedMigrationNames: [],
  editedMigrationNames: [],
  hasMigrationsTable: false
}
```

**Note**: I'm currently not able to reproduce any `fp-ts` related error. 
@okry, I might try to package the current script into an executable and see whether that triggers the issues you've been experiencing. Would you please share your `pkg` configuration with us? 

# Files

```jsonc
// package.json

{
  "name": "reprod-14453",
  "version": "1.0.0",
  "main": "index.js",
  "type": "commonjs",
  "scripts": {
    "dev": "node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@prisma/internals": "^4.1.0",
    "@prisma/migrate": "^4.1.0"
  }
}
```

```javascript
// index.js

const { Migrate } = require('@prisma/migrate')
const { ensureDatabaseExists } = require('@prisma/migrate/dist/utils/ensureDatabaseExists')

async function main() {
  const schemaPath = "./prisma/schema.prisma"
  const migrate = new Migrate(schemaPath)
  const wasDbCreated = await ensureDatabaseExists("apply", true, schemaPath)
  
  console.info() // empty line
  if (wasDbCreated) {
    console.info(wasDbCreated)
  } else {
    console.info("Database already exists")
  }

  const diagnoseResult = await migrate.diagnoseMigrationHistory({
    optInToShadowDatabase: false,
  })

  console.log('diagnoseResult', diagnoseResult)
  migrate.stop()
}

main()
  .catch(e => {
    console.log('error in main')
    console.error(e)
    process.exit(1)
  })
```

**Comment by okry** [comment]
My pkg settings are pretty basic, it's simply:
```
"pkg": {
    "assets": [
      "package.json"
    ]
  }
```
It may be worth noting though that we are using esbuild to build this dependency.

esbuild:
```
const esbuild = require("esbuild");
const { dependencies } = require("./package.json");

esbuild.build({
  entryPoints: ["./src/main.ts"],
  outdir: "pre-build/js/src",
  bundle: true,
  sourcemap: true,
  minify: true,
  splitting: true,
  format: "esm",
  target: ["ES2019"],
  platform: "node",
  external: Object.keys(dependencies),
});
```

tsconfig:
```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Default",
  "compilerOptions": {
    "target": "ES2019",
    "module": "CommonJS",
    "lib": ["dom", "dom.iterable", "ES2022"],
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": false,
    "composite": false,
    "declaration": true,
    "declarationMap": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "noImplicitReturns": false,
    "noImplicitThis": true,
    "pretty": true,
    "removeComments": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": false,
    "useUnknownInCatchVariables": false
  },
  "exclude": ["node_modules"]
}
```

**Comment by jkomyno** [comment]
Closing this for inactivity. These are internal packages, we unfortunately don't have the bandwidth to provide support in bundling them any differently than how we do currently.
