### ISSUE TITLE
Finding schema.prisma without __dirname

### ISSUE THREAD

**Issue by revmischa** [prisma/prisma#14484]
### Bug description

From slack: https://prisma.slack.com/archives/CCWDULGUW/p1657602998648169

I have an issue with creating lambda function bundles with prisma. I'm using ESM and `__dirname` is not defined, but used in the prisma client to find the `schema.prisma` file as best I can tell.

I can hack around this by creating an ESM shim for dealing with legacy CJS code like the prisma client. This defines __dirname using `import.meta`. See https://github.com/evanw/esbuild/pull/2067#issuecomment-1073039746 for details.

However I can't tell prisma where my bundle path is since it assumes my schema.prisma is in __dirname. I can work around this by hardcoding `__dirname` in my shim to `/var/task` and just always copying the schema.prisma file in there. It doesn't seem like the best solution.

### How to reproduce

1. Create lambda function that runs as ESM (output a .mjs bundle or set type:module in package.json of function bundle)
2. Import @prisma/client

Should get an error 
```
  errorType: 'ReferenceError',
  errorMessage: '__dirname is not defined in ES module scope\n' +
    `This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.`,
  stack: [
    'ReferenceError: __dirname is not defined in ES module scope',
    `This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.`,
    '    at node_modules/.prisma/client/index.js (file:///var/task/packages/infra/lib/lambdas/cognito/preTokenGeneration.js:91:53)',
    '    at __require2 (file:///var/task/packages/infra/lib/lambdas/cognito/preTokenGeneration.js:20:50)',
    '    at node_modules/@prisma/client/index.js (file:///var/task/packages/infra/lib/lambdas/cognito/preTokenGeneration.js:1472:10)',
    '    at __require2 (file:///var/task/packages/infra/lib/lambdas/cognito/preTokenGeneration.js:20:50)',
    '    at file:///var/task/packages/infra/lib/lambdas/cognito/preTokenGeneration.js:75914:29',
    '    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)',
    '    at async Promise.all (index 0)',
    '    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)',
    '    at async _tryAwaitImport (file:///var/runtime/index.mjs:660:16)',
    '    at async _tryRequire (file:///var/runtime/index.mjs:709:37)'
```

### Expected behavior

What would be nice (from best to least best):
* Not to have to include the schema.prisma file in my deployment
* For prisma to generate runtime code that compatible with ESM (i.e. not use __dirname)
* To have an env var to tell prisma where to find the schema.prisma file

### Prisma information

4.0.0

### Environment & setup

- OS: 
- Database: 
- Node.js version: 
Node 16 lambda

### Prisma Version

```
prisma                  : 4.0.0
@prisma/client          : 4.0.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : da41d2bb3406da22087b849f0e911199ba4fbf11
Studio                  : 0.465.0
```

**Comment by matthewmueller** [comment]
I believe this will be solved by https://github.com/prisma/prisma/issues/5030.

**Comment by maietta** [comment]
It broke again. Not sure why.

**Comment by hahagu** [comment]
@maietta Have you been able to work around this by any chance?

**Comment by maietta** [comment]
> @maietta Have you been able to work around this by any chance?

I moved to Drizzle ORM, so I have no idea.

**Comment by hahagu** [comment]
> > @maietta Have you been able to work around this by any chance?
> 
> I moved to Drizzle ORM, so I have no idea.

Oh, okay :/

Thank you for the prompt response!

**Comment by runlong-yao** [comment]
> Drizzle ORM

yes, another choice

**Comment by Mateleo** [comment]
Ok, I've found a solution for the "__dirname is not defined in ES module scope" error.

The issue arises when using ES modules (ESM) in the generated Prisma Client. The `__dirname` variable is not automatically available in ESM.

**Solution:**

Explicitly set `moduleFormat = "esm"` in the generator block of your `schema.prisma` file. This ensures that the Prisma Client is generated with the correct module format and uses `import.meta.url` instead of `__dirname` for resolving file paths.

```prisma
generator client {
  provider = "prisma-client"
  output   = "../src/generated/prisma"
  moduleFormat = "esm" // Explicitly set module format to ESM
}
```
ref : https://www.prisma.io/docs/orm/prisma-schema/overview/generators#field-reference-1
