### ISSUE TITLE
The data types time and datetimeoffset are incompatible in the less than operator.

### ISSUE THREAD

**Issue by mikhael-abdallah** [prisma/prisma#14483]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.19.3           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 3.15.0             |
| Query Engine    | query-engine b9297dc3a59307060c1c39d7e4f5765066f38372|
| Database        | undefined|

## Logs
```
prisma:tryLoadEnv Environment variables loaded from /var/src/.env
prisma:tryLoadEnv Environment variables loaded from /var/src/.env
prisma:client dirname /var/src/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /var/src/prisma
prisma:client clientVersion: 3.15.0
prisma:client clientEngineType: binary
prisma:engine {"cwd":"/var/src/prisma"}
prisma:engine Search for Query Engine in /var/src/node_modules/.prisma/client
prisma:engine Search for Query Engine in /var/src/node_modules/.prisma/client
plusX Execution permissions of /var/src/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
plusX Execution permissions of /var/src/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine {"flags":["--enable-raw-queries","--enable-metrics","--port","37081"]}
prisma:engine stdout Starting a mssql pool with 9 connections.
prisma:engine stdout TLS encryption is not enabled. All traffic including the login credentials are not encrypted.
prisma:engine stdout Database change from 'germinare_adm_course' to 'master'
prisma:engine stdout Changed database context to 'germinare_adm_course'.
prisma:engine stdout SQL collation change from None to windows-1252/windows-1252
prisma:engine stdout Microsoft SQL Server�� version 2131755023
prisma:engine stdout Packet size change from '4096' to '4096'
prisma:engine stdout Started query engine http server on http://127.0.0.1:37081
prisma:engine Search for Query Engine in /var/src/node_modules/.prisma/client
plusX Execution permissions of /var/src/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine Client Version: 3.15.0
prisma:engine Engine Version: query-engine b9297dc3a59307060c1c39d7e4f5765066f38372
prisma:engine Active provider: sqlserver
prisma:engine stdout The data types time and datetimeoffset are incompatible in the less than operator.
prisma:engine {"error":{"clientVersion":"3.15.0"}}
prisma:engine stdout The data types time and datetimeoffset are incompatible in the less than operator.
prisma:engine {"error":{"clientVersion":"3.15.0"}}
prisma:engine stdout The data types time and datetimeoffset are incompatible in the less than operator.
prisma:engine {"error":{"clientVersion":"3.15.0"}}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
query {
  findManycal_calendars(
    where: {
      deactivation_date: null
      end_time: {
        lt: "X"
      }
    }
    skip: 5
    take: 5
    orderBy: [
      {
        pk_id: asc
      }
    ]
  ) {
    pk_id
    end_time
  }
}
```

**Comment by garrensmith** [comment]
@mikhael-abdallah could you provide your schema and if possible a reproduction of this crash. That would really help us.

**Comment by matthewmueller** [comment]
Ping @mikhael-abdallah. We could really use the schema + client to diagnose.

**Comment by pimeys** [comment]
Actual reproduction steps:

- Add column with `@db.Time` native type
- Do an `lt` query with `Date` as input

Logs:

```
prisma:info Starting a mssql pool with 33 connections.
prisma:info Performing a TLS handshake
prisma:warn Trusting the server certificate without validation.
prisma:info TLS handshake successful
prisma:warn Turning TLS off after a login. All traffic from here on is not encrypted.
prisma:info Database change from 'master' to 'master'
prisma:info Changed database context to 'master'.
prisma:info SQL collation change from None to windows-1252/windows-1252
prisma:info Microsoft SQL Server version 2349858831
prisma:info Packet size change from '4096' to '4096'
prisma:info Begin transaction
prisma:query BEGIN TRAN
prisma:query DECLARE @generated_keys table([id] BIGINT) INSERT INTO [dbo].[A] ([date]) OUTPUT [Inserted].[id] INTO @generated_keys VALUES (@P1) SELECT [t].[id] FROM @generated_keys AS g INNER JOIN [dbo].[A] AS [t] ON [t].[id] = [g].[id] WHERE @@ROWCOUNT > 0 /* traceparent=00-00-00-00 */
prisma:query SELECT [dbo].[A].[id], [dbo].[A].[date] FROM [dbo].[A] WHERE [dbo].[A].[id] = @P1 ORDER BY 1 OFFSET @P2 ROWS FETCH NEXT @P3 ROWS ONLY /* traceparent=00-00-00-00 */
prisma:info Commit transaction
prisma:query COMMIT
prisma:error The data types time and datetimeoffset are incompatible in the less than operator.
prisma:query SELECT [dbo].[A].[id], [dbo].[A].[date] FROM [dbo].[A] WHERE [dbo].[A].[date] < @P1 /* traceparent=00-00-00-00 */
PrismaClientUnknownRequestError: 
Invalid `prisma.a.findMany()` invocation in
/prisma-14483/script.ts:13:31

  10   },
  11 })
  12 
→ 13 const data = await prisma.a.findMany(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 402, state: 1, class: 16, message: "The data types time and datetimeoffset are incompatible in the less than operator.", server: "a34d42a6c4b6", procedure: "", line: 1 }) })
    at RequestHandler.handleRequestError (/prisma-14483/node_modules/@prisma/client/runtime/index.js:29913:13)
    at RequestHandler.request (/prisma-14483/node_modules/@prisma/client/runtime/index.js:29892:12)
    at async PrismaClient._request (/prisma-14483/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async main (/prisma-14483/script.ts:13:16) {
  clientVersion: '4.3.1'
```
