### ISSUE TITLE
Prisma Client fails with `Response from the Engine was empty` for some tests on Azure SQL

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#14528]
- Checkout to the [`joel/referential-integrity`](https://github.com/prisma/prisma/tree/joel/referential-integrity) branch
- Change the [`defaultMatrix`](https://github.com/prisma/prisma/blob/joel/referential-integrity/packages/client/tests/functional/referential-integrity/_matrix.ts) definition to:

```typescript
// packages/client/tests/functional/referential-integrity/_matrix.ts

export default defineMatrix(() => [
  [
    {
      provider: Providers.SQLSERVER,
      id: 'String @id',
      referentialIntegrity,
      referentialActions: {
        onUpdate,
        onDelete,
      },
    },
  ],
  [{ previewFeatures: '"referentialIntegrity"' }],
])
```

- Run `docker-compose -f docker/docker-compose.yml up` (see the docker/docker-compose.yml file definition below)

```yaml
# docker/docker-compose.yml

version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pr1sm4_Pr1sm4
    ports:
      - '1433:1433'
```

- In another terminal, run:
  1. `cd packages/client`
  2. `RI=foreignKeys pnpm run test:functional:code referential-integrity`. The output should look like the following (showing only the test results of `[tests_1-to-1.ts](https://github.com/prisma/prisma/blob/joel/referential-integrity/packages/client/tests/functional/referential-integrity/tests_1-to-1.ts)` for brevity):
  
```text
 FAIL  tests/functional/referential-integrity/tests_1-to-1.ts
  referential-integrity.tests_1-to-1 (provider=sqlserver, id=String @id, referentialIntegrity=foreignKeys, referentialActions=[object Object], previewFeatures=referentialIntegrity)
    1:1 mandatory (explicit)
      [create]
        ✕ [create] child with non existing parent should throw (320 ms)
        ✓ [create] child with undefined parent should throw with type error (8 ms)
        ✓ [create] nested child [create] (29 ms)
      [update]
        ✓ [update] (user) optional boolean field should succeed (62 ms)
        ✓ [update] (profile) optional boolean field should succeed (55 ms)
        mutate id
          ✓ [upsert] child id with non-existing id should succeed (48 ms)
          ✓ [update] child id with non-existing id should succeed (47 ms)
          ✓ [update] nested child [connect] child should succeed if the relationship didn't exist (65 ms)
          ✓ [update] nested child [update] should succeed (62 ms)
          ✓ [update] nested child [connect] should succeed if the relationship already existed (38 ms)
          ○ skipped [update] nested child [updateMany] should succeed
          ○ skipped [update] nested child [upsert] child should succeed
          ○ skipped [upsert] parent id should succeed
          ○ skipped [upsert] parent id with existing id should throw
          onUpdate: DEFAULT, Cascade
            ✓ [update] parent id with non-existing id should succeed (46 ms)
            ✓ [updateMany] parent id should succeed (40 ms)
          onUpdate: Restrict, NoAction
            ○ skipped [update] parent id with non-existing id should throw
            ○ skipped [updateMany] parent id with non-existing id should throw
          onUpdate: NoAction
            ○ skipped [updateMany] parent id with existing id should throw
          onUpdate: DEFAULT, Restrict, SetNull
            ✕ [update] parent id with existing id should throw (41 ms)
            ✕ [update] child id with existing id should throw (41 ms)
            ✕ [updateMany] parent id with existing id should throw (40 ms)
            ✓ [update] nested child [disconnect] should throw (36 ms)
          onUpdate: Cascade
            ○ skipped [update] parent id with existing id should succeed
            ○ skipped [update] child id with existing id should succeed
            ○ skipped [updateMany] parent id with existing id should
            ○ skipped [update] nested child [disconnect] should succeed
      [delete]
        ✓ [delete] child should succeed (47 ms)
        ✓ [delete] child and then [delete] parent should succeed (44 ms)
        onDelete: DEFAULT
          ✕ [delete] parent should throw (36 ms)
          ✕ [deleteMany] parents should throw (38 ms)
          ○ skipped [delete] parent should throw
          ○ skipped [deleteMany] parents should throw
        onDelete: Cascade
          ○ skipped [delete] parent should succeed

  ● referential-integrity.tests_1-to-1 (provider=sqlserver, id=String @id, referentialIntegrity=foreignKeys, referentialActions=[object Object], previewFeatures=referentialIntegrity) › 1:1 mandatory (explicit) › [create] › [create] child with non existing parent should throw

    Response from the Engine was empty

      20781 |   parseEngineResponse(response) {
      20782 |     if (!response) {
    > 20783 |       throw new PrismaClientUnknownRequestError(`Response from the Engine was empty`, this.config.clientVersion);
            |             ^
      20784 |     }
      20785 |     try {
      20786 |       const config2 = JSON.parse(response);

      at LibraryEngine.parseEngineResponse (../../runtime/index.js:20783:13)
      at LibraryEngine.parseEngineResponse [as logger] (../../runtime/index.js:20829:24)
      at logger (../../runtime/index.js:20815:27)

  ● referential-integrity.tests_1-to-1 (provider=sqlserver, id=String @id, referentialIntegrity=foreignKeys, referentialActions=[object Object], previewFeatures=referentialIntegrity) › 1:1 mandatory (explicit) › [update] › mutate id › onUpdate: DEFAULT, Restrict, SetNull › [update] parent id with existing id should throw

    Response from the Engine was empty

      20781 |   parseEngineResponse(response) {
      20782 |     if (!response) {
    > 20783 |       throw new PrismaClientUnknownRequestError(`Response from the Engine was empty`, this.config.clientVersion);
            |             ^
      20784 |     }
      20785 |     try {
      20786 |       const config2 = JSON.parse(response);

      at LibraryEngine.parseEngineResponse (../../runtime/index.js:20783:13)
      at LibraryEngine.parseEngineResponse [as logger] (../../runtime/index.js:20829:24)
      at logger (../../runtime/index.js:20815:27)

  ● referential-integrity.tests_1-to-1 (provider=sqlserver, id=String @id, referentialIntegrity=foreignKeys, referentialActions=[object Object], previewFeatures=referentialIntegrity) › 1:1 mandatory (explicit) › [update] › mutate id › onUpdate: DEFAULT, Restrict, SetNull › [update] child id with existing id should throw

    Response from the Engine was empty

      20781 |   parseEngineResponse(response) {
      20782 |     if (!response) {
    > 20783 |       throw new PrismaClientUnknownRequestError(`Response from the Engine was empty`, this.config.clientVersion);
            |             ^
      20784 |     }
      20785 |     try {
      20786 |       const config2 = JSON.parse(response);

      at LibraryEngine.parseEngineResponse (../../runtime/index.js:20783:13)
      at LibraryEngine.parseEngineResponse [as logger] (../../runtime/index.js:20829:24)
      at logger (../../runtime/index.js:20815:27)

  ● referential-integrity.tests_1-to-1 (provider=sqlserver, id=String @id, referentialIntegrity=foreignKeys, referentialActions=[object Object], previewFeatures=referentialIntegrity) › 1:1 mandatory (explicit) › [update] › mutate id › onUpdate: DEFAULT, Restrict, SetNull › [updateMany] parent id with existing id should throw

    Response from the Engine was empty

      20781 |   parseEngineResponse(response) {
      20782 |     if (!response) {
    > 20783 |       throw new PrismaClientUnknownRequestError(`Response from the Engine was empty`, this.config.clientVersion);
            |             ^
      20784 |     }
      20785 |     try {
      20786 |       const config2 = JSON.parse(response);

      at LibraryEngine.parseEngineResponse (../../runtime/index.js:20783:13)
      at LibraryEngine.parseEngineResponse [as logger] (../../runtime/index.js:20829:24)
      at logger (../../runtime/index.js:20815:27)

  ● referential-integrity.tests_1-to-1 (provider=sqlserver, id=String @id, referentialIntegrity=foreignKeys, referentialActions=[object Object], previewFeatures=referentialIntegrity) › 1:1 mandatory (explicit) › [delete] › onDelete: DEFAULT › [delete] parent should throw

    Response from the Engine was empty

      20781 |   parseEngineResponse(response) {
      20782 |     if (!response) {
    > 20783 |       throw new PrismaClientUnknownRequestError(`Response from the Engine was empty`, this.config.clientVersion);
            |             ^
      20784 |     }
      20785 |     try {
      20786 |       const config2 = JSON.parse(response);

      at LibraryEngine.parseEngineResponse (../../runtime/index.js:20783:13)
      at LibraryEngine.parseEngineResponse [as logger] (../../runtime/index.js:20829:24)
      at logger (../../runtime/index.js:20815:27)

  ● referential-integrity.tests_1-to-1 (provider=sqlserver, id=String @id, referentialIntegrity=foreignKeys, referentialActions=[object Object], previewFeatures=referentialIntegrity) › 1:1 mandatory (explicit) › [delete] › onDelete: DEFAULT › [deleteMany] parents should throw

    Response from the Engine was empty

      20781 |   parseEngineResponse(response) {
      20782 |     if (!response) {
    > 20783 |       throw new PrismaClientUnknownRequestError(`Response from the Engine was empty`, this.config.clientVersion);
            |             ^
      20784 |     }
      20785 |     try {
      20786 |       const config2 = JSON.parse(response);

      at LibraryEngine.parseEngineResponse (../../runtime/index.js:20783:13)
      at LibraryEngine.parseEngineResponse [as logger] (../../runtime/index.js:20829:24)
      at logger (../../runtime/index.js:20815:27)

Test Suites: 1 failed, 1 total
Tests:       6 failed, 14 skipped, 14 passed, 34 total
Snapshots:   0 total
Time:        3.864 s, estimated 4 s
Ran all test suites matching /referential-integrity/i.
 ELIFECYCLE  Command failed with exit code 1.
```

## Expected Output

If we substitute the `docker/docker-compose.yml` file with

```yaml
# docker/docker-compose.yml

version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pr1sm4_Pr1sm4
    ports:
      - '1433:1433'
```

and reproduce the steps above, we should get the following output instead:

```text
RI=foreignKeys pnpm run test:functional:code referential-integrity/tests_1-to-1.ts

 PASS  tests/functional/referential-integrity/tests_1-to-1.ts
  referential-integrity.tests_1-to-1 (provider=sqlserver, id=String @id, referentialIntegrity=foreignKeys, referentialActions=[object Object], previewFeatures=referentialIntegrity)
    1:1 mandatory (explicit)
      [create]
        ✓ [create] child with non existing parent should throw (663 ms)
        ✓ [create] child with undefined parent should throw with type error (21 ms)
        ✓ [create] nested child [create] (47 ms)
      [update]
        ✓ [update] (user) optional boolean field should succeed (88 ms)
        ✓ [update] (profile) optional boolean field should succeed (72 ms)
        mutate id
          ✓ [upsert] child id with non-existing id should succeed (61 ms)
          ✓ [update] child id with non-existing id should succeed (77 ms)
          ✓ [update] nested child [connect] child should succeed if the relationship didn't exist (66 ms)
          ✓ [update] nested child [update] should succeed (52 ms)
          ✓ [update] nested child [connect] should succeed if the relationship already existed (46 ms)
          ○ skipped [update] nested child [updateMany] should succeed
          ○ skipped [update] nested child [upsert] child should succeed
          ○ skipped [upsert] parent id should succeed
          ○ skipped [upsert] parent id with existing id should throw
          onUpdate: DEFAULT, Cascade
            ✓ [update] parent id with non-existing id should succeed (54 ms)
            ✓ [updateMany] parent id should succeed (50 ms)
          onUpdate: Restrict, NoAction
            ○ skipped [update] parent id with non-existing id should throw
            ○ skipped [updateMany] parent id with non-existing id should throw
          onUpdate: NoAction
            ○ skipped [updateMany] parent id with existing id should throw
          onUpdate: DEFAULT, Restrict, SetNull
            ✓ [update] parent id with existing id should throw (42 ms)
            ✓ [update] child id with existing id should throw (44 ms)
            ✓ [updateMany] parent id with existing id should throw (341 ms)
            ✓ [update] nested child [disconnect] should throw (44 ms)
          onUpdate: Cascade
            ○ skipped [update] parent id with existing id should succeed
            ○ skipped [update] child id with existing id should succeed
            ○ skipped [updateMany] parent id with existing id should
            ○ skipped [update] nested child [disconnect] should succeed
      [delete]
        ✓ [delete] child should succeed (92 ms)
        ✓ [delete] child and then [delete] parent should succeed (63 ms)
        onDelete: DEFAULT
          ✓ [delete] parent should throw (61 ms)
          ✓ [deleteMany] parents should throw (57 ms)
          ○ skipped [delete] parent should throw
          ○ skipped [deleteMany] parents should throw
        onDelete: Cascade
          ○ skipped [delete] parent should succeed

Test Suites: 1 passed, 1 total
Tests:       14 skipped, 20 passed, 34 total
Snapshots:   0 total
Time:        4.872 s, estimated 19 s
Ran all test suites matching /referential-integrity\/tests_1-to-1.ts/i.
```

**Comment by janpio** [comment]
Can we get a self contained reproduction of the problem that does not require checking out a branch and running some test suite please? A simple .ts file should be enough here.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
