### ISSUE TITLE
mongodb cannot use $runCommand Raw in transaction

### ISSUE THREAD

**Issue by Lizhooh** [prisma/prisma#14543]
### Bug description

mongodb cannot use $runCommand Raw in transaction

```js
Invalid `prisma.$runCommandRaw()` invocation:


  The current database provider doesn't support a feature that the query used: Raw queries
2022-07-29 09:52:21 error: Error: 
Invalid `prisma.$runCommandRaw()` invocation:


  The current database provider doesn't support a feature that the query used: Raw queries

```

### How to reproduce

demo: 

```js 
await prisma.$transaction(async $prisma => {
   $prisma.$runCommandRaw({
        "update": "component",
        "updates": [
            {
              "q": { "_id": "EDMBuss0V4" },
              "u": { "$set": { "alias": "abc" } },
              "multi": false,
              "upsert": false
            }
        ]
    })
})
```

### Environment & setup

- OS: Windows 
- Database: MongoDB 
- Node.js version: v14.20.0 

### Prisma Version

```
prisma                  : 4.0.0
@prisma/client          : Not found
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt da41d2bb3406da22087b849f0e911199ba4fbf11 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : da41d2bb3406da22087b849f0e911199ba4fbf11
Studio                  : 0.465.0
```

**Comment by Jolg42** [comment]
Can reproduce in our internal dev version `4.4.0-dev.27`
```
/Users/j42/Repros/14543/node_modules/@prisma/client/runtime/index.js:30850
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.$runCommandRaw()` invocation:


The current database provider doesn't support a feature that the query used: Raw queries
    at RequestHandler.handleRequestError (/Users/j42/Repros/14543/node_modules/@prisma/client/runtime/index.js:30850:13)
    at RequestHandler.request (/Users/j42/Repros/14543/node_modules/@prisma/client/runtime/index.js:30833:12)
    at async Proxy._request (/Users/j42/Repros/14543/node_modules/@prisma/client/runtime/index.js:31805:16)
    at async Proxy._transactionWithCallback (/Users/j42/Repros/14543/node_modules/@prisma/client/runtime/index.js:31744:18)
    at async main (/Users/j42/Repros/14543/main.ts:9:3) {
  code: 'P2026',
  clientVersion: '4.4.0-dev.27',
  meta: { feature: 'Raw queries' }
}
```
