### ISSUE TITLE
Error with custom output in Turborepo using Blitz.js: Error: ENOENT: no such file or directory, open '<...>/schema.prisma'

### ISSUE THREAD

**Issue by paulm17** [prisma/prisma#14566]
### Bug description

Very similar to 

Nx monorepo: https://github.com/prisma/prisma/issues/14033
NPM monorepo: https://github.com/prisma/prisma/issues/13233

This time, this is with Turbo Repo.  😄 

```
error - unhandledRejection: Error: ENOENT: no such file or directory, open '/Users/paul/development/src/[project]/apps/saas/.next/server/pages/contentEditor/schema.prisma'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at new LibraryEngine (webpack-internal:///../../packages/prisma/node_modules/@prisma/client/runtime/index.js:25120:41)
    at PrismaClient.getEngine (webpack-internal:///../../packages/prisma/node_modules/@prisma/client/runtime/index.js:29185:16)
    at new PrismaClient (webpack-internal:///../../packages/prisma/node_modules/@prisma/client/runtime/index.js:29157:29)
    at Object.construct (/Users/paul/development/src/[project]/node_modules/blitz/dist/chunks/prisma-utils.cjs:20:25)
    at eval (webpack-internal:///../../packages/prisma/index.ts:18:66)
    at ../../packages/prisma/index.ts (/Users/paul/development/src/[project]/apps/saas/.next/server/pages/contentEditor/adDesign.js:1657:1)
    at __webpack_require__ (/Users/paul/development/src/[project]/apps/saas/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///./app/modules/contentEditor/adDesign/queries/getTemplates.ts:7:75) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/paul/development/src/[project]/apps/saas/.next/server/pages/contentEditor/schema.prisma',
  clientVersion: '4.1.1'
}
```

### Expected behavior

Should just work, like 4.0.0 works fine

### Environment & setup

- OS: Mac Monterey 
- Database: Postgres
- Node.js version: 18.4

### Prisma Version

Says 4.0.0 but it's 4.1.1 in packages.json

```
prisma                  : 4.0.0
@prisma/client          : 4.0.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine da41d2bb3406da22087b849f0e911199ba4fbf11 (at ../../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli da41d2bb3406da22087b849f0e911199ba4fbf11 (at ../../node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core da41d2bb3406da22087b849f0e911199ba4fbf11 (at ../../node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt da41d2bb3406da22087b849f0e911199ba4fbf11 (at ../../node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : da41d2bb3406da22087b849f0e911199ba4fbf11
Studio                  : 0.465.0
```

**Comment by janpio** [comment]
> Says 4.0.0 but it's 4.1.1 in packages.json

That is _very_ weird already. The paths of the engine files also looks funky. Can you share more about your project setup?

**Comment by paulm17** [comment]
This is my TR directory:

![alt text](https://i.imgur.com/EHBp2cI.png)

------

packages.json

```
{
    "name": "@[project]/prisma",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
      "migrate:dev": "prisma migrate dev --preview-feature",
      "migrate:dev:create": "prisma migrate dev --create-only --preview-feature",
      "migrate:reset": "prisma migrate reset --preview-feature",
      "migrate:deploy": "yarn prisma migrate deploy --preview-feature",
      "migrate:status": "yarn prisma migrate status --preview-feature",
      "migrate:resolve": "yarn prisma migrate resolve --preview-feature",
      "studio": "yarn prisma studio",
      "generate": "yarn prisma generate",
      "generate:watch": "yarn prisma generate --watch",
      "start:db": "run-s migrate:up generate seed",
      "seed": "yarn prisma db seed"
    },
    "dependencies": {
      "@prisma/client": "4.0.0"
    },
    "devDependencies": {
      "config": "*",
      "tsconfig": "*",
      "prisma": "4.0.0"
    },
    "prisma": {
      "schema": "./schema.prisma",
      "seed": "ts-node ./seed.ts"
    }
  }
  
```

**Comment by anthonyespirat** [comment]
same issue here
OS: WSL2
Yarn version : 3.2
Nextjs: 12.2.3

```
error - Error: ENOENT: no such file or directory, open '/home/nox/code/red/apps/front/.next/server/pages/api/schema.prisma'
@red/front:dev:     at Object.openSync (node:fs:585:3)
@red/front:dev:     at Object.readFileSync (node:fs:453:35)
@red/front:dev:     at new LibraryEngine (webpack-internal:///(api)/../../packages/prisma/lib/runtime/index.js:25308:41)
@red/front:dev:     at PrismaClient.getEngine (webpack-internal:///(api)/../../packages/prisma/lib/runtime/index.js:29336:16)
@red/front:dev:     at new PrismaClient (webpack-internal:///(api)/../../packages/prisma/lib/runtime/index.js:29308:29)
@red/front:dev:     at eval (webpack-internal:///(api)/./lib/prisma.ts:8:16)
@red/front:dev:     at Object.(api)/./lib/prisma.ts (/home/nox/code/red/apps/front/.next/server/pages/api/user.js:253:1)
@red/front:dev:     at __webpack_require__ (/home/nox/code/red/apps/front/.next/server/webpack-api-runtime.js:33:42)
@red/front:dev:     at eval (webpack-internal:///(api)/./pages/api/user/index.ts:5:69)
@red/front:dev:     at Object.(api)/./pages/api/user/index.ts (/home/nox/code/red/apps/front/.next/server/pages/api/user.js:264:1) {
@red/front:dev:   errno: -2,
@red/front:dev:   syscall: 'open',
@red/front:dev:   code: 'ENOENT',
@red/front:dev:   path: '/home/nox/code/red/apps/front/.next/server/pages/api/schema.prisma',
@red/front:dev:   clientVersion: '4.2.1'
@red/front:dev: }
```

**Comment by paulm17** [comment]
Alright I have managed to solve the issue (maybe for myself).

I have no issues when having something like BlitzJS in a workspace (alone) that uses Prisma (in the packages folder).

However, when I introduce NestJS and for whatever reason not able to find the same Prisma package.  I then install the prisma dependencies and this is where I think the issue of the schema not being found is introduced.  At this point I have Prisma in a packages folder and prisma within nestjs.  I think under the hood in the central node_modules dir, there are 2 versions???

Anyway, I found myself reworking the nest installation today and to get around this issue, I symlinked a folder db to the packages/prisma folder and then imported what nestjs needs for prisma.

> import { PrismaClient } from '../../db/nestjs';

Ugly, but I don't care.  It works.  😄 

I'm now running 4.2.1 from a central location.  I have 3 js frameworks using it now:  🥳 

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by janpio** [comment]
Thanks @paulm17 and @anthonyespirat for opening an issue specifically for Turborepo.
Can you maybe create a reproduction repository of a minimal project nad put it on GitHub? We would love to be able to reproduce this problem so we can fix it (and test our workaround that we are currently testing in all the reproductions we can find.)

**Comment by millsp** [comment]
Hey guys, thanks for the feedback. We have been working on a simpler way to make things work for you, as the workaround we proposed had clear limitations for TS projects. We worked on an experimental webpack plugin that ensures your Prisma files are copied correctly. I'd love if you could give it a try (https://www.npmjs.com/package/experimental-prisma-webpack-plugin). We have tested it in many different scenarios, so we hope this works for you.

```ts
const { PrismaPlugin } = require('experimental-prisma-webpack-plugin')

module.exports = {
  output: 'standalone',
  webpack: (config, { isServer }) => {
    if (isServer) {
      config.plugins = [...config.plugins, new PrismaPlugin()]
    }

    return config
  },
}
```

**Comment by millsp** [comment]
For those using multiple Prisma Clients, we are going to schedule follow-up work via https://github.com/prisma/prisma/issues/18069. Please upvote it if you need multi-client support, and don't hesitate to share more information there.
