### ISSUE TITLE
`connectTimeoutMS` seemingly has no effect on migrate

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma#14607]
### Bug description

When running `prisma db push` command agains non-existing server, connection seems to always timeout after 30s. [Docs](https://www.prisma.io/docs/concepts/database-connectors/mongodb) suggest `connectTimeoutMS` query parameter can be used for changing this timeout, but actually, it does not seem to be the case.

### How to reproduce

1. Copy provided schema
2. Ensure mongo is **NOT** running on provided host/port.
3. Run `time prisma db push` against the schema
4. Command will timeout after 30s:

```
Prisma schema loaded from prisma/schema.prisma
Datasource "db"
Error: MongoDB error
Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: nothere:12345, Type: Unknown, Error: failed to lookup address information: nodename nor servname provided, or not known }, ] }
   0: migration_core::state::SchemaPush
             at migration-engine/core/src/state.rs:349

pnpm prisma db push  0.69s user 0.18s system 2% cpu 30.557 total
```

### Expected behavior

Same timeout error, but after 1 second as specified by connection string.

### Prisma information

Prisma schema:

```prisma
generator client {
  provider        = "prisma-client-js"
  output          = "../node_modules/.prisma/client"
  previewFeatures = []
}

datasource db {
  provider = "mongodb"
  url      = "mongodb://nothere:12345/db?connectTimeoutMS=1000"
}

model User {
  id String @id @map("_id")
}
```

### Environment & setup

- OS: macOS
- Database: MongoDB
- Node.js version: 16.15.1

### Prisma Version

```
4.2.0-dev
```

**Comment by Jolg42** [comment]
I can reproduce: (see `Executed in   31.60 secs`)
```
time npx prisma db push
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db"
Error: MongoDB error
Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: nothere:12345, Type: Unknown, Error: failed to lookup address information: nodename nor servname provided, or not known }, ] }
   0: migration_core::state::SchemaPush
             at migration-engine/core/src/state.rs:349


________________________________________________________
Executed in   31.60 secs    fish           external
   usr time    1.57 secs  137.00 micros    1.57 secs
   sys time    0.35 secs  801.00 micros    0.34 secs
```

But... if instead I use the parameter we document for the other databases like MySQL, `connect_timeout`, it works like expected: (Executed in    1.78 secs)
https://www.prisma.io/docs/concepts/database-connectors/mysql
```
time npx prisma db push
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db"
Error: P1013

The provided database string is invalid. An invalid argument was provided: connect_timeout is an invalid option. An option with a similar name exists: connecttimeoutms in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.


________________________________________________________
Executed in    1.78 secs    fish           external
   usr time    1.37 secs  131.00 micros    1.37 secs
   sys time    0.39 secs  684.00 micros    0.39 secs
```

We document it in docs like this for a 5 sec timeout:
```
&connectTimeoutMS=5000
```
From https://www.prisma.io/docs/concepts/database-connectors/mongodb

**Comment by tomhoule** [comment]
Copying my reaction from slack: Hmm, first time I read about this param. When I grep for it in prisma-engines, I have 0 matches, so either it's implemented in the mongo driver or we documented something that doesn't exist.

**Comment by tomhoule** [comment]
They do seem to have tests about this in the driver: https://github.com/mongodb/mongo-rust-driver/search?q=connecttimeoutms

One way to try to constrain the problem would be to see if the query engine behaves the same.

**Comment by Jolg42** [comment]
@tomhoule I also get something close to 30s when doing `time ts-node main.ts` with a Prisma Client query.

**Comment by Jolg42** [comment]
Can reproduce in our internal dev version ``

For Client here is the script
```
import { PrismaClient } from '@prisma/client'

async function main() {
  const prisma = new PrismaClient()

  const data = await prisma.user.findMany()
  console.log(data)
  prisma.$disconnect()
}

main()
```
and output shows 30s timeout
```
time ts-node main.ts
/Users/j42/Repros/14607/node_modules/@prisma/client/runtime/index.js:30856
      throw new PrismaClientInitializationError(message, this.client._clientVersion);
            ^
PrismaClientInitializationError: 
Invalid `prisma.user.findMany()` invocation in
/Users/j42/Repros/14607/main.ts:6:34

  3 async function main() {
  4   const prisma = new PrismaClient()
  5 
→ 6   const data = await prisma.user.findMany(
Database error. error code: unknown, error message: Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: nothere:12345, Type: Unknown, Error: failed to lookup address information: nodename nor servname provided, or not known }, ] }
    at RequestHandler.handleRequestError (/Users/j42/Repros/14607/node_modules/@prisma/client/runtime/index.js:30856:13)
    at RequestHandler.request (/Users/j42/Repros/14607/node_modules/@prisma/client/runtime/index.js:30833:12)
    at async PrismaClient._request (/Users/j42/Repros/14607/node_modules/@prisma/client/runtime/index.js:31805:16)
    at async main (/Users/j42/Repros/14607/main.ts:6:16) {
  clientVersion: '4.4.0-dev.30',
  errorCode: undefined
}
ts-node main.ts  1.35s user 0.11s system 4% cpu 30.611 total
```

**Comment by patrickfreed** [comment]
The timeout being hit here is `serverSelectionTimeoutMS`, which has a default value of 30 seconds. This timeout governs how long the MongoDB driver will wait until a suitable server is discovered when attempting an operation, which seems closer to what you intended. `connectTimeoutMS`, on the other hand, governs only how long connection establishment takes (i.e. it specifies how long we can wait for establishment to take before we can confidently say the server is down).

What's going on here is likely that the monitor task is attempting and failing to establish a connection the non-existent server quickly and repeatedly while the operation waits for the server to be discovered, with `connectTimeoutMS` never actually coming into play. 

To make this speedier, you can specify a lower `serverSelectionTimeoutMS`.

**Comment by dejurin** [comment]
Same problem

```
------                                                                                                                                     
 > [nextjs build 2/4] RUN dotenv -e .env.dev -- pnpm exec prisma db pull --force:                                                   
1.566 Prisma schema loaded from prisma/schema.prisma                                                                                       
1.567 Environment variables loaded from .env                                                                                               
1.571 Datasource "db": MongoDB database "my_db" at "mongodb:27017"
1.574 
1.577 - Introspecting based on datasource defined in prisma/schema.prisma
31.59 ✖ Introspecting based on datasource defined in prisma/schema.prisma
31.59 
31.59 Error: MongoDB error
31.59 Kind: Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: mongodb:27017, Type: Unknown, Error: Kind: I/O error: failed to lookup address information: Name does not resolve, labels: {} } ] }, labels: {}
31.59 
31.59 
------
```

MacOSX, M1
Docker container: Node20, Alpine 3.17, Prisma 5.4.1

**Comment by janpio** [comment]
@dejurin The problem reported here is that a customization of the timeout is not observed, not the problem itself. You should open a new discussion and provide more information about what you are doing exactly. Thanks.

**Comment by dejurin** [comment]
> @dejurin The problem reported here is that a customization of the timeout is not observed, not the problem itself. You should open a new discussion and provide more information about what you are doing exactly. Thanks.

Thank you for the answer. I initially thought that was the problem.
