### ISSUE TITLE
`Invalid prisma.$executeRaw() invocation:  Unique constraint failed on the (not available)` with Postgresql

### ISSUE THREAD

**Issue by NanoCode012** [prisma/prisma#14654]
### Bug description

Hello, I am getting the error `Invalid prisma.$executeRaw() invocation:  Unique constraint failed on the (not available)` when trying to insert into a table with unique constraint columns. 

I can confirm that if the name is unique, the insert is successful. But if I used a prior name, it returns this error without telling which is the offending column. I had two columns with unique constraint. Both showed this behavior.

I found https://github.com/prisma/prisma/issues/10829 , but that was designated for Planetscale and Vitess, and not Postgresql.

### How to reproduce

1. Schema (minimized)

    ```prisma
    model Location {
        id                                                String      @id  @db.Uuid
        name                                              String      @unique
        abbr                                              String?     @unique
    }
    ```

2. Prisma code which I run within a transaction. I run two commands prior to set my user jwt and role.
    ```typescript
    prisma.location.create({
       data: parsedBody,
    }),
    ```

    with `parsedBody` passing the schema:

    ```ts
    {
        name: string().required(),
        abbr: string().nullable().defined(),
    }

3. Call the API with a non-unique `name` and any `abbr`.
4. Error
    ```bash
    Invalid `prisma.$executeRaw()` invocation:


    Unique constraint failed on the (not available)
     at RequestHandler.handleRequestError (<redacted>\node_modules\@prisma\client\runtime\index.js:28658:13)
    at RequestHandler.request (<redacted>\node_modules\@prisma\client\runtime\index.js:28640:12)
    at async consumer (<redacted>\node_modules\@prisma\client\runtime\index.js:29618:18)
    at async Proxy._request (<redacted>\node_modules\@prisma\client\runtime\index.js:29639:16)
    at async Promise.all (index 0)
    at async constructTransaction (webpack-internal:///(api)/./src/configs/prisma.ts:43:30)
    at async __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(api)/./src/pages/api/locations/index.ts:30:17)
    at async Object.apiResolver (<redacted>\node_modules\next\dist\server\api-utils\node.js:185:9)
      at async DevServer.runApi (<redacted>\node_modules\next\dist\server\next-server.js:395:9)
    at async Object.fn (<redacted>\node_modules\next\dist\server\base-server.js:496:37) {
    code: 'P2002',
    clientVersion: '4.1.0',
    meta: { target: null }
    }
    ````

### Expected behavior

It should error with correct column name.

For ex: `Invalid prisma.$executeRaw() invocation:  Unique constraint failed on the column 'name'`

### Environment & setup

- OS: Windows
- Database: PostgreSQL on local dev supabase
- Node.js version: v16.15.1
- Nextjs

### Prisma Version

```
prisma                  : 4.1.0
@prisma/client          : 4.1.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 8d8414deb360336e4698a65aa45a1fbaf1ce13d8 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 8d8414deb360336e4698a65aa45a1fbaf1ce13d8
Studio                  : 0.467.0
```

**Comment by garrensmith** [comment]
Just a note, we rely on the database to return the field that has caused the failure. Not all databases return the field name.

**Comment by NanoCode012** [comment]
> Just a note, we rely on the database to return the field that has caused the failure. Not all databases return the field name.

@garrensmith , May I ask if postgresql should return the field name or not? 

Is there any way I can help provide more info for this issue?

**Comment by NanoCode012** [comment]
Hello, I would like to provide extra information. I think I've tracked down the reason. Using `@@map` causes error to miss information.

In my schema, I didn't add that I used `@@map("locations")` to the Location schema. 
- After I randomly tried to remove the `@@map` and created a new migration, it suddenly worked for me.
- To confirm, I added `@@map` back and removed the previous migration, the same issue came back.

**Comment by janpio** [comment]
An observation: Your issue describes how you use `prisma.location.create`. But the error message mentions "Invalid `prisma.$executeRaw()` invocation". Are you maybe also doing an `$executeRaw` that writes some data somewhere?

**Comment by NanoCode012** [comment]
> An observation: Your issue describes how you use `prisma.location.create`. But the error message mentions "Invalid `prisma.$executeRaw()` invocation". Are you maybe also doing an `$executeRaw` that writes some data somewhere?

Thank you for reply @janpio .

Currently, my setup is to run 2 `executeRawUnsafe` (`SET LOCAL ..`) before running the actual query (for ex, `prisma.location.create`) to setup Row level security (RLS) in a **transaction**. I was interested in this statement "Invalid `prisma.$executeRaw()` invocation" not being the norm for queries. 

When I removed RLS and ran the query without being in a transaction, it worked (log below)!

Therefore, my current observation is that `prisma.location.create` is converted to `$executeRaw` inside a **transaction** which causes the error field to not be returned if the model has `@@map` applied.

<details>

<summary>Normal Query log without transaction for future ref</summary>

```
PrismaClientKnownRequestError: 
Invalid `prisma.location.create()` invocation:


  Unique constraint failed on the fields: (`name`)
    at RequestHandler.handleRequestError (<redacted>\node_modules\@prisma\client\runtime\index.js:28658:13)
    at RequestHandler.request (<redacted>\node_modules\@prisma\client\runtime\index.js:28640:12)
    at async consumer (<redacted>\node_modules\@prisma\client\runtime\index.js:29618:18)       
    at async PrismaClient._request (<redacted>\node_modules\@prisma\client\runtime\index.js:29639:16)
    at async __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(api)/./src/pages/api/locations/index.ts:38:17)
    at async Object.apiResolver (<redacted>\node_modules\next\dist\server\api-utils\node.js:185:9)
    at async DevServer.runApi (<redacted>\node_modules\next\dist\server\next-server.js:395:9)  
    at async Object.fn (<redacted>\node_modules\next\dist\server\base-server.js:496:37)        
    at async Router.execute (<redacted>\node_modules\next\dist\server\router.js:226:36)        
    at async DevServer.run (<redacted>\node_modules\next\dist\server\base-server.js:606:29) {  
  code: 'P2002',
  clientVersion: '4.1.1',
  meta: { target: [ 'name' ] }
}
```

</details>

**Comment by NanoCode012** [comment]
Hello, @janpio , sorry for the repeated messages. I have created a mini reproducible repo here: https://github.com/NanoCode012/prisma-set-role-transaction-error-message with instruction in the ReadMe. 



I have narrowed the problem down to using `SET LOCAL ROLE` in a `$transaction` and RLS. The `@@map` was not the reason, (the reason it worked previously was a byproduct of some other changes.)
```
prisma.$executeRawUnsafe("SET LOCAL ROLE TO prisma;")
```

When I tried to `SET LOCAL ROLE`, the field returns `null` in the error. 

<details>

<summary>Null returned in error </summary>

```
Invalid `prisma.$executeRaw()` invocation:


  Unique constraint failed on the (not available)
    at RequestHandler.handleRequestError (<redacted>\node_modules\@prisma\client\runtime\index.js:28838:13)
    at RequestHandler.request (<redacted>\node_modules\@prisma\client\runtime\index.js:28820:12)
    at async Proxy._request (<redacted>\node_modules\@prisma\client\runtime\index.js:29753:16)
    at async Promise.all (index 0)
    at async handler (webpack-internal:///(api)/./pages/api/failSetRoleToPrisma.ts:25:9)
    at async Object.apiResolver (<redacted>\node_modules\next\dist\server\api-utils\node.js:184:9)
    at async DevServer.runApi (<redacted>\node_modules\next\dist\server\next-server.js:403:9)
    at async Object.fn (<redacted>\node_modules\next\dist\server\base-server.js:493:37)    
    at async Router.execute (<redacted>\node_modules\next\dist\server\router.js:222:36)    
    at async DevServer.run (<redacted>\node_modules\next\dist\server\base-server.js:612:29) {
  code: 'P2002',
  clientVersion: '4.2.1',
  meta: { target: null }
}
```

</details>

On another note, I noticed that `prisma.location.create` becomes `prisma.$executeRaw` if there are other queries in the transaction. I provided the logs in the repo ReadMe as well.

Thank you for reading!

**Comment by janpio** [comment]
Okay wow, that is quite a combination then: `$transaction` + raw queries + RLS - correct?

**Comment by NanoCode012** [comment]
Hey @janpio , it sure is a mess! I updated the repo to reflect my latest findings.

The **main** reason is actually just turning on RLS, which for some reason stops postgresql from returning the `hint` as seen in log.

It is not due to transaction, nor raw queries. I added more sample cases to test each individually. They work fine.

The reason `SET ROLE` causes this issue initially was because we went from a role with higher permission (`bypassRLS` aka `postgres`) to a role with lower permission, which didn't bypass RLS but still had permission to query the table.

**Comment by SevInf** [comment]
@NanoCode012 I can not reproduce the with the provided example. Following instructions in the README, when I hit `failRlsUsingPrismaRole` route, `meta.target.name` is successfully logged in the console. Could you double check the example? Or do you have any hunch on what might be missing?

**Comment by SevInf** [comment]
On the second attempt I managed to reproduce the issue on both 4.1 and 5.2.0. 
Note to future self/collegues: issue does not reproduces with docker images from prisma/prisma, but running postgres in separate container helps:

```
docker run  -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:15 
```

Slightly shorter reproducion instruction which does not require Next.JS
- Run postgres docker image with a command above.
- Use following schema:
```prisma
datasource db {
  provider = "postgres"
  url      = "postgres://postgres:postgres@localhost:5432/foo1"
}

generator client {
  provider = "prisma-client-js"
}

model Location {
  id   String  @id @default(uuid()) @db.Uuid
  name String  @unique
  abbr String? @unique

}

   ```
- Important: copy migration files from [here](https://github.com/NanoCode012/prisma-set-role-transaction-error-message/tree/main/prisma/migrations). Issue won't reprouduce without second migration that enables RLS.
- Run following code:

```ts
async function main() {
  const prisma = new PrismaClient()
  await prisma.location.deleteMany()

  await prisma.$transaction([
    prisma.$executeRawUnsafe('SET LOCAL ROLE TO prisma;'),
    prisma.location.create({
      data: {
        name: 'A',
        abbr: 'a',
      },
    }),
  ])

  try {
    await prisma.$transaction([
      prisma.$executeRawUnsafe('SET LOCAL ROLE TO prisma;'),
      prisma.location.create({
        data: {
          name: 'A',
          abbr: 'b',
        },
      }),
    ])
  } catch (error) {
    console.log(error.meta.target)
  }
}
```

It will output `null` where expected thing would've been `name`.

**Comment by NanoCode012** [comment]
That's interesting the issue stayed in Postgres v15. In my previous test, the beta version did return the field, so I thought v5 stable would've fixed it.

**Comment by anuraaga** [comment]
I happened to run into this problem too and found this issue. I'm a bit unsure from reading, but is it correct that this needs to be fixed in postgres itself, not prisma? if that's the case, does it make sense to leave a comment to that effect and close this issue since it's not a bug in prisma? Then it'd be clearer that there is nothing waiting on the prisma team here.

**Comment by baoshan** [comment]
This is how Postgres is designed/implemented. I am quoting Laurenz Albe (from [this SO answer](https://stackoverflow.com/a/55374365)):

> [when RLS is enabled], if you know which key your entry conflicts with, you may get some information about rows in the database that you cannot see.

I am not sure if other RDBMS(s) exhibit the same behavior, but there is nothing that Prisma can fix for now.
