### ISSUE TITLE
Mongo $runCommandRaw() bulk update operation results in `new Date()` as string instead of ISODate

### ISSUE THREAD

**Issue by doronrk** [prisma/prisma#14815]
### Bug description

The following command results in the field `importDate` being stored in the DB as a string, not an ISODate:

```
import { PrismaClient } from '@prisma/client';
import uuid from 'uuid';

export const prisma = new PrismaClient();

prisma
  .$runCommandRaw({
    update: 'tags',
    updates: [
      {
        q: {
          name: 'tagName',
        },
        u: {
          $setOnInsert: {
            importDate: new Date(),
          },
        },
        upsert: true,
      },
    ],
  });
};
```

### How to reproduce

Run a code snippet like the above

### Expected behavior

Instead of:

```
"historicalImportDate" : "2022-08-15T15:39:40.375Z"
```

The field should be:

```
"historicalImportDate" : ISODate("2022-08-15T15:27:24.726Z"),
```

The former is what is produced by Prisma. The latter is what is produced by mongoose. 

### Prisma information

prisma schema
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("MONGO_URL")
}

model Tag {
  id                   String    @id @map("_id") @default(uuid())
  dateCreated          DateTime? @default(now())
  importDate           DateTime?
  name                 String

  @@map("tags")
  @@unique([id])
}

```

I'm on `prisma/client' 4.2.1

### Environment & setup

- OS: Mac OS
- Database: MongoDB
- Node.js version: v14.19.3

### Prisma Version

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by doronrk** [comment]
Anything else I can do here to further the investigation here?

**Comment by janpio** [comment]
Besides sending us a truckload of competent developers that want to work for Prisma on Prisma ORM (https://boards.greenhouse.io/prisma/jobs/6322225002), so we have more capacity to tackle this: Unfortunately not.

**Comment by Jolg42** [comment]
Can reproduce with 4.2.1 and our internal dev version `4.4.0-dev.27'`
```
DEBUG="*" ts-node main.ts
  prisma:tryLoadEnv  Environment variables not found at null +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/j42/Repros/14815/prisma/.env +1ms
  prisma:tryLoadEnv  Environment variables not found at null +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/j42/Repros/14815/prisma/.env +0ms
  prisma:client  dirname /Users/j42/Repros/14815/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /Users/j42/Repros/14815/prisma +0ms
  prisma:client  clientVersion 4.2.1 +0ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /Users/j42/Repros/14815/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /Users/j42/Repros/14815/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:client  Prisma Client call: +13ms
  prisma:client  prisma.$runCommandRaw({
  command: {
    update: 'tags',
    updates: [
      {
        q: {
          name: 'tagName'
        },
        u: {
          $setOnInsert: {
            importDate: new Date('2022-09-06T16:33:45.915Z')
          }
        },
        upsert: true
      }
    ]
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  runCommandRaw(command: "{\"update\":\"tags\",\"updates\":[{\"q\":{\"name\":\"tagName\"},\"u\":{\"$setOnInsert\":{\"importDate\":\"2022-09-06T16:33:45.915Z\"}},\"upsert\":true}]}")
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +14ms
  prisma:client:libraryEngine  library starting +0ms
  prisma:client:libraryEngine  library started +35ms
  prisma:client  Prisma Client call: +56ms
  prisma:client  prisma.tag.findMany(undefined) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findManyTag {
    id
    dateCreated
    importDate
    name
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +20ms
  prisma:client:request_handler  PrismaClientKnownRequestError: Inconsistent column data: Failed to convert '"2022-09-06T16:33:45.915Z"' to 'DateTime' for the field 'importDate'.
    at prismaGraphQLToJSError (/Users/j42/Repros/14815/node_modules/@prisma/client/runtime/index.js:20007:12)
    at LibraryEngine.buildQueryError (/Users/j42/Repros/14815/node_modules/@prisma/client/runtime/index.js:25668:12)
    at LibraryEngine.request (/Users/j42/Repros/14815/node_modules/@prisma/client/runtime/index.js:25605:22)
    at async RequestHandler.request (/Users/j42/Repros/14815/node_modules/@prisma/client/runtime/index.js:28802:24)
    at async PrismaClient._request (/Users/j42/Repros/14815/node_modules/@prisma/client/runtime/index.js:29753:16)
    at async main (/Users/j42/Repros/14815/main.ts:27:16) {
  code: 'P2023',
  clientVersion: '4.2.1',
  meta: {
    message: `Failed to convert '"2022-09-06T16:33:45.915Z"' to 'DateTime' for the field 'importDate'.`
  }
} +0ms
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms
/Users/j42/Repros/14815/node_modules/@prisma/client/runtime/index.js:28838
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.tag.findMany()` invocation in
/Users/j42/Repros/14815/main.ts:27:33

  24   ],
  25 });
  26 
→ 27 const tags = await prisma.tag.findMany()
  Inconsistent column data: Failed to convert '"2022-09-06T16:33:45.915Z"' to 'DateTime' for the field 'importDate'.
    at RequestHandler.handleRequestError (/Users/j42/Repros/14815/node_modules/@prisma/client/runtime/index.js:28838:13)
    at RequestHandler.request (/Users/j42/Repros/14815/node_modules/@prisma/client/runtime/index.js:28820:12)
    at async PrismaClient._request (/Users/j42/Repros/14815/node_modules/@prisma/client/runtime/index.js:29753:16)
    at async main (/Users/j42/Repros/14815/main.ts:27:16) {
  code: 'P2023',
  clientVersion: '4.2.1',
  meta: {
    message: `Failed to convert '"2022-09-06T16:33:45.915Z"' to 'DateTime' for the field 'importDate'.`
  }
}
```

Note that I had to put a `// @ts-ignore` because of the following TypeError
```
error TS2322: Type '{ q: { name: string; }; u: { $setOnInsert: { importDate: Date; }; }; upsert: true; }' is not assignable to type 'InputJsonValue | null | undefined'.
  Types of property 'u' are incompatible.
    Type '{ $setOnInsert: { importDate: Date; }; }' is not assignable to type 'InputJsonValue | null | undefined'.
      Types of property '$setOnInsert' are incompatible.
        Type '{ importDate: Date; }' is not assignable to type 'InputJsonValue | null | undefined'.
          Types of property 'importDate' are incompatible.
            Type 'Date' is not assignable to type 'InputJsonValue | null | undefined'.
              Type 'Date' is not assignable to type 'InputJsonObject'.
                Index signature for type 'string' is missing in type 'Date'.

  9       {
          ~
 10         q: {
    ~~~~~~~~~~~~
... 
 18         upsert: true,
    ~~~~~~~~~~~~~~~~~~~~~
 19       },
    ~~~~~~~

    at createTSError (/Users/j42/.nvm/versions/node/v16.16.0/lib/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/j42/.nvm/versions/node/v16.16.0/lib/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/j42/.nvm/versions/node/v16.16.0/lib/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/j42/.nvm/versions/node/v16.16.0/lib/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/j42/.nvm/versions/node/v16.16.0/lib/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/j42/.nvm/versions/node/v16.16.0/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  diagnosticCodes: [ 2322 ]
}
```

```
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient();

  await prisma.$runCommandRaw({
    update: "tags",
    updates: [
      // @ts-ignore
      {
        q: {
          name: "tagName",
        },
        u: {
          $setOnInsert: {
            importDate: new Date(),
          },
        },
        upsert: true,
      },
    ],
  });

  const tags = await prisma.tag.findMany();
  console.log(tags);
  await prisma.$disconnect();
}

main();

```

Also `findMany` errors with
```
Failed to convert '"2022-09-06T16:33:45.915Z"' to 'DateTime' for the field 'importDate'.
```

I don't think we have a way to make an ISODate at the moment with runCommandRaw?

**Comment by Jolg42** [comment]
Note: `Failed to convert '"2022-09-06T16:33:45.915Z"' to 'DateTime' for the field 'importDate'.` is an error from the engine: https://github.com/prisma/prisma-engines/blob/825b01c7f9881f5a4ae165ccdef06b55de278513/query-engine/connectors/mongodb-query-connector/src/error.rs#L24-L30

**Comment by randytarampi** [comment]
Piling on here. 

We had to bring in `mongoose` because the driver wouldn't turn a JS `Date` into an `ISODate` for Mongo in a [`$search` aggregation stage](https://www.mongodb.com/docs/manual/reference/operator/aggregation/search/), which doesn't accept the aggregation expression [workaround of `$dateFromString: { dateString: new Date().toISOString() }`](https://github.com/prisma/prisma/issues/17522#issuecomment-1438188073).

`prisma` and Atlas not playing nice together. Not fun! 😭

Is this anywhere close to being scheduled? 🙏

**Comment by Dsantosjaime** [comment]
I'm using Prisma and MongoDb our new enterprise project and this bug is highly blocking.
I can't perform a "simple" match with my date fields

**Comment by janpio** [comment]
> We can't updateMany and connect at the same time either, how should we create a bunch of new documents in a collection and get them connected to an other ?

You should open an issue about this problem instead of commenting in other unrelated issue, please. Thank you.

**Comment by Dsantosjaime** [comment]
This comment is just here to highlight the seriousness of this kind of bug.
Prisma recommends using it tool with mongoDb but lacks like this (put together) put us in very bad situation.
I hope you'll address it as soon as possible.

**Comment by ledniy** [comment]
The raw command can be fixed by adding `$date` to the query
```
$setOnInsert: {
  importDate: {
    $date: new Date()
  }
}
```
