### ISSUE TITLE
CLI: `studio` should not hang and return a non-successful exit code (1) an error occurs

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#14861]
### Bug description

From https://github.com/prisma/prisma/issues/12349

Studio, when an error occurs, does not exit.

### How to reproduce

```
# Create an empty `schema.prisma`
❯ npx prisma studio        
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Prisma Studio is up on http://localhost:5555
Unable to get DMMF from Prisma Client:  Error: 
You don't have any datasource defined in your schema.prisma.
You can define a datasource like this:

datasource db {
  provider = "postgresql"
  url      = env("DB_URL")
}

More information in our documentation:
https://pris.ly/d/prisma-schema

    at getGenerators (/Users/j42/Repros/exit-codes/node_modules/prisma/build/index.js:90249:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $fc77884679bbcc28$export$569332143708bf93 (/Users/j42/Repros/exit-codes/node_modules/prisma/build/index.js:96078:28)
    at async $527b23cbb13e8bc6$var$PCW.getDMMF (/Users/j42/Repros/exit-codes/node_modules/prisma/build/index.js:96138:39)
    at async $b22dca7664055e05$export$cf1ce5b2c3d7dc8c.respond (/Users/j42/Repros/exit-codes/node_modules/prisma/build/index.js:96343:37)
    at async /Users/j42/Repros/exit-codes/node_modules/prisma/build/index.js:96510:26
```
And here it hangs forever, until the process is killed.
Every reload of `http://localhost:5555` prints the same error over and over.

### Expected behavior

The CLI should exit with an exit code 1 for these unrecoverable errors. (reloading the page will not fix it, the schema would need to be fixed and the command restarted)

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
4.3.0-dev.27
```

**Comment by Jolg42** [comment]
For this error `Unable to get DMMF from Prisma Client:` it seems the origin is here:
- it logs the error
- and throws
https://github.com/prisma/studio-code/blob/v0.472.0/packages/pcw/src/pcw.ts#L243-L247

`this.pcw.getDMMF();` called in a try catch here, which seems like it only returns the error to the frontend
Maybe we could `process.exit(1)` here in the case of an unrecoverable error (= getDmmf error)
https://github.com/prisma/studio-code/blob/v0.472.0/packages/server/src/channels/prisma.ts#L52-L92

On the CLI side, `await studio.start()` is called and there is no error handling logic that could be done.
https://github.com/prisma/prisma/blob/4.2.1/packages/cli/src/Studio.ts
