### ISSUE TITLE
sqlite:cuid():called `Result::unwrap()` on an `Err` value: FingerprintError("Could not retrieve hostname")

### ISSUE THREAD

**Issue by zzlb0224** [prisma/prisma#14870]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.16.0           | 
| OS              | windows            |
| Prisma Client   | 4.2.1              |
| Query Engine    | 2920a97877e12e055c1333079b8d19cee7f33826|
| Database        | sqlite             |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from D:\workspace\lunwen4\test-remix1\.env
prisma:tryLoadEnv Environment variables loaded from D:\workspace\lunwen4\test-remix1\.env
prisma:client dirname D:\workspace\lunwen4\test-remix1\node_modules\.prisma\client
prisma:client relativePath ..\..\..\prisma
prisma:client cwd D:\workspace\lunwen4\test-remix1\prisma
prisma:client clientVersion 4.2.1
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine:loader Searching for Query Engine Library in D:\workspace\lunwen4\test-remix1\node_modules\.prisma\client
prisma:client:libraryEngine:loader loadEngine using D:\workspace\lunwen4\test-remix1\node_modules\.prisma\client\query_engine-windows.dll.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:request_handler {"code":"P2025","clientVersion":"4.2.1","meta":{"cause":"Record to delete does not exist."}}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
const { PrismaClient } = require("@prisma/client");

const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

async function seed() {
  const email = "rachel@remix.run";

  // cleanup the existing database
  await prisma.user.delete({ where: { email } }).catch(() => {
    // no worries if it doesn't exist yet
  });

  const hashedPassword = await bcrypt.hash("racheliscool", 10);
  const ds = await prisma.user.findMany();
  ds.forEach((f) => console.log(f));
  console.log({
    email,
    password: {
      create: {
        hash: hashedPassword,
      },
    },
  });
  const user = await prisma.user.create({
    data: {
      email,
      password: {
        create: {
          hash: hashedPassword,
        },
      },
    },
  });

  await prisma.note.create({
    data: {
      title: "My first note",
      body: "Hello, world!",
      userId: user.id,
    },
  });

  await prisma.note.create({
    data: {
      title: "My second note",
      body: "Hello, world!",
      userId: user.id,
    },
  });

  console.log(`Database has been seeded. 🌱`);
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

```

## Schema
```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id    Int @id @default(autoincrement())
  email String @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  password Password?
  notes    Note[]
}

model Password {
  hash String

  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  userId Int @unique
}

model Note {
  id    String @id @default(cuid())
  title String
  body  String

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  userId Int
}

```

## Prisma Engine Query
```
{"X":{}}
```

## full error
```

D:\workspace\lunwen4\test-remix1>npx prisma db seed
Environment variables loaded from .env
Running seed command `node --require tsconfig-paths/register prisma/seed.js` ...
{
  email: 'rachel@remix.run',
  password: {
    create: {
      hash: '$2a$10$1XzAqhH8x3XI0VL/Jr4voufpwdzvTwDZFFyOYtMnAGKvxLDfotbQe'
    }
  }
}
Database has been seeded. 🌱

The seed command has been executed.

D:\workspace\lunwen4\test-remix1>npx prisma db seed
Environment variables loaded from .env
Running seed command `node --require tsconfig-paths/register prisma/seed.js` ...
{
  email: 'rachel@remix.run',
  password: {
    create: {
      hash: '$2a$10$qiZ6BIuMPcaBzsZTJ7H3ieodAxaE2nVVrQHnE9c0LdBKCc60oGs.a'
    }
  }
}
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: FingerprintError("Could not retrieve hostname")', C:\Users\runneradmin\.cargo\git\checkouts\cuid-rust-05420f73eb18afd9\1637fd2\src\lib.rs:29:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PrismaClientRustPanicError: 
Invalid `prisma.note.create()` invocation in
D:\workspace\lunwen4\test-remix1\prisma\seed.js:37:21

  34   },
  35 });
  36
→ 37 await prisma.note.create(
  called `Result::unwrap()` on an `Err` value: FingerprintError("Could not retrieve hostname")

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v16.16.0+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+windows++++++++++++%7C%0A%7C+Prisma+Client+++%7C+4.2.1++++++++++++++%7C%0A%7C+Query+Engine++++%7C+2920a97877e12e055c1333079b8d19cee7f33826%7C%0A%7C+Database++++++++%7C+sqlite+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aprisma%3AtryLoadEnv+Environment+variables+loaded+from+D%3A%5Cworkspace%5Clunwen4%5Ctest-remix1%5C.env%0Aprisma%3AtryLoadEnv+Environment+variables+loaded+from+D%3A%5Cworkspace%5Clunwen4%5Ctest-remix1%5C.env%0Aprisma%3Aclient+dirname+D%3A%5Cworkspace%5Clunwen4%5Ctest-remix1%5Cnode_modules%5C.prisma%5Cclient%0Aprisma%3Aclient+relativePath+..%5C..%5C..%5Cprisma%0Aprisma%3Aclient+cwd+D%3A%5Cworkspace%5Clunwen4%5Ctest-remix1%5Cprisma%0Aprisma%3Aclient+clientVersion+4.2.1%0Aprisma%3Aclient+clientEngineType+library%0Aprisma%3Aclient%3AlibraryEngine+internalSetup%0Aprisma%3Aclient%3AlibraryEngine%3Aloader+Searching+for+Query+Engine+Library+in+D%3A%5Cworkspace%5Clunwen4%5Ctest-remix1%5Cnode_modules%5C.prisma%5Cclient%0Aprisma%3Aclient%3AlibraryEngine%3Aloader+loadEngine+using+D%3A%5Cworkspace%5Clunwen4%5Ctest-remix1%5Cnode_modules%5C.prisma%5Cclient%5Cquery_engine-windows.dll.node%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+false%0Aprisma%3Aclient%3AlibraryEngine+library+starting%0Aprisma%3Aclient%3AlibraryEngine+library+started%0Aprisma%3Aclient%3Arequest_handler+%7B%22code%22%3A%22P2025%22%2C%22clientVersion%22%3A%224.2.1%22%2C%22meta%22%3A%7B%22cause%22%3A%22Record+to+delete+does+not+exist.%22%7D%7D%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=called+%60Result%3A%3Aunwrap%28%29%60+on+an+%60Err%60+value%3A+FingerprintError%28%22Could+not+retrieve+hostname%22%29&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

    at RequestHandler.handleRequestError (D:\workspace\lunwen4\test-remix1\node_modules\@prisma\client\runtime\index.js:28846:13)
    at RequestHandler.request (D:\workspace\lunwen4\test-remix1\node_modules\@prisma\client\runtime\index.js:28820:12)
    at async PrismaClient._request (D:\workspace\lunwen4\test-remix1\node_modules\@prisma\client\runtime\index.js:29753:16)
    at async seed (D:\workspace\lunwen4\test-remix1\prisma\seed.js:37:3) {
  clientVersion: '4.2.1'
}

An error occured while running the seed command:
Error: Command failed with exit code 1: node --require tsconfig-paths/register prisma/seed.js
```

##  when i change the id from cuid() to autoincrement(), it run ok
``` 
model User {
  id    String @id @default(cuid())
 
}
```
``` 
model User {
  id    Int @id @default(autoincrement())
 
}
```
possiblely it cause by the id column define cuid type

**Comment by Jolg42** [comment]
Related old issue https://github.com/prisma/prisma/issues/8716

**Comment by Jolg42** [comment]
Note: @do4gr daid we are using a fork of the cuid crate but we could probably go back to the original one now.

**Comment by pimeys** [comment]
Internal discussion on how we might be able to get a reproduction:

https://prisma-company.slack.com/archives/C040N0UADF0/p1663002257434649

**Comment by pimeys** [comment]
I'll write some observations and some guesswork what is causing this issue. We have three open issues with similar problems:

- The one you're reading.
- https://github.com/prisma/prisma/issues/14864
- https://github.com/prisma/prisma/issues/14130

The error is coming from the `cuid` library, we forked 0.1 back in the days and never been merging back the upstream changes. The code tries to determine the hostname and stores it in `lazy_static`:

- fingerprinting here: https://github.com/mplanchard/cuid-rust/blob/703e2733a65670e4bd8beadbcf8b3246b1a959fe/src/lib.rs#L30-L32
- calls `get_hostname` from an old version of `hostname`: https://github.com/mplanchard/cuid-rust/blob/703e2733a65670e4bd8beadbcf8b3246b1a959fe/src/fingerprint.rs
- The old version of `get_hostname` calls `winutil::get_computer_name()`: https://github.com/svartalf/hostname/blob/1c6ff9ba7a5a3c5651351a88db7f606808d17bd7/src/lib.rs#L18-L22
- And that call uses the Windows API function `GetComputerNameA`, that returns the NetBIOS name if available (docs: https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getcomputernamea)
- Microsoft started deprecating the NetBIOS system in the latest dev builds: https://news.thewindowsclub.com/microsoft-starts-disabling-netbios-name-resolution-in-windows-106920/
- If disabled, we get `None` back from the winapi, causing the `unwrap` errors...

This is very hard to reproduce, but all signs show that updating our `cuid` and `hostname` crates to the latest version would fix the issue. The latest version of `hostname` calls the Windows API function `GetComputerNameExA` that returns the DNS name if NetBIOS name is not set, and can never return `None` as the hostname on Windows.

For the developer fixing the issue: update `hostname` and `cuid`. Close the issues and monitor are we still having these errors in the future. Microsoft is just rolling out the deprecation, so in the future we will see more of these errors if we are not fixing it now.

The new `hostname` does the correct API calls: https://github.com/svartalf/hostname/blob/master/src/windows.rs#L12-L44

## What about the poisoning errors?

If a function that sets a `Once` or `lazy_static` value panics, all further calls to this function return a poison error instead of the original one.
