### ISSUE TITLE
Expected parent IDs to be set when ordering by parent ID.

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [prisma/prisma#14899]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.17.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 4.1.0              |
| Query Engine    | 8d8414deb360336e4698a65aa45a1fbaf1ce13d8|
| Database        | mysql              |

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:client dirname /kontrol/node_modules/.prisma/client
prisma:client relativePath ../../..
prisma:client cwd /kontrol
prisma:client clientVersion: 4.1.0
prisma:client clientEngineType: library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine:loader Searching for Query Engine Library in /kontrol/node_modules/.prisma/client
prisma:client:libraryEngine:loader loadEngine using /kontrol/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.1.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"clientVersion":"4.1.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
  const projects = await db.project.findMany({
    select: {
      projectId: true,
      deployments: {
        take: 15,
        orderBy: { createdAt: 'desc' },
        include: {stages: {}},
      },
    },
  })
```

## Schema
```prisma
  const projects = await db.project.findMany({
    select: {
      projectId: true,
      deployments: {
        take: n,
        orderBy: { createdAt: 'desc' },
        include: {stages: {}},
      },
    },
  })
```

## Prisma Engine Query
```
model Project {
  projectId         String             @id @map("project_id") @db.VarChar(50)
  createdAt         DateTime           @default(now()) @map("created_at")
  deployments       Deployment[]
  stages            DeploymentStage[]

  @@map("project")
}

model Deployment {
  projectId        String            @map("project_id") @db.VarChar(40)
  project          Project           @relation(fields: [projectId], references: [projectId])
  deploymentId     String            @map("deployment_id") @db.VarChar(20)
  createdAt        DateTime          @default(now()) @map("created_at")
  stages           DeploymentStage[]

  @@id([projectId, deploymentId])
  @@index([deploymentId], map: "ix_deploymentid")
  @@index([createdAt], map: "ix_createdat")
  @@map("deployment")
}

model DeploymentStage {
  projectId        String               @map("project_id") @db.VarChar(40)
  deploymentId     String               @map("deployment_id") @db.VarChar(20)
  project          Project              @relation(fields: [projectId], references: [projectId])
  deployment       Deployment           @relation(fields: [projectId, deploymentId], references: [projectId, deploymentId])
  stage            StageType
  createdAt        DateTime             @default(now()) @map("created_at")

  @@id([projectId, deploymentId, stage])
  @@map("deployment_stage")
}
```

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Additional log:

```
thread 'tokio-runtime-worker' panicked at 'Expected parent IDs to be set when ordering by parent ID.', query-engine/core/src/interpreter/query_interpreters/inmemory_record_processor.rs:69:18
stack backtrace:
   0:     0x7fdca0f11bed - std::backtrace_rs::backtrace::libunwind::trace::hb729d9642bb971eb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fdca0f11bed - std::backtrace_rs::backtrace::trace_unsynchronized::h373bb774579df5c7
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fdca0f11bed - std::sys_common::backtrace::_print_fmt::hfbd4e92d240c89bb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fdca0f11bed - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f618991fbf64972
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fdca0f39a7c - core::fmt::write::hc69b5b640d88cce8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:     0x7fdca0f0b6f1 - std::io::Write::write_fmt::h3403cef06a24a303
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:     0x7fdca0f13405 - std::sys_common::backtrace::_print::h368f27cdedea0e52
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fdca0f13405 - std::sys_common::backtrace::print::ha105c9cf5a64cd17
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fdca0f13405 - std::panicking::default_hook::{{closure}}::h48ed2c3707d5e20e
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:     0x7fdca0f13079 - std::panicking::default_hook::h8744fc5cea5e3110
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
  10:     0x7fdca0f139d8 - std::panicking::rust_panic_with_hook::hc82286af2030e925
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
  11:     0x7fdca0f13887 - std::panicking::begin_panic_handler::{{closure}}::h1c15057c2f09081f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
  12:     0x7fdca0f120a4 - std::sys_common::backtrace::__rust_end_short_backtrace::h65de906a5330f8da
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7fdca0f135b9 - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  14:     0x7fdc9fc83b13 - core::panicking::panic_fmt::h741cfbfc95bc6112
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  15:     0x7fdca0f36781 - core::panicking::panic_display::h1094c8c253f473c8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:72:5
  16:     0x7fdca0f3672b - core::panicking::panic_str::hbdaf98ecbcb31da3
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:56:5
  17:     0x7fdc9fc83986 - core::option::expect_failed::hf79a0c6dca04c0cf
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:1854:5
  18:     0x7fdc9febb1a4 - alloc::slice::<impl [T]>::sort_by_key::{{closure}}::hcc19fe99acf1be2f
  19:     0x7fdc9feb7a75 - alloc::slice::merge_sort::h3489937be4807a6e
  20:     0x7fdc9ff91465 - query_core::interpreter::query_interpreters::inmemory_record_processor::InMemoryRecordProcessor::apply::ha3132007d3cf0dd1
  21:     0x7fdc9ff95174 - query_core::interpreter::query_interpreters::read::read_related::{{closure}}::h91baeab190c936b8
  22:     0x7fdc9ff80eb3 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h37feabd211270582
  23:     0x7fdc9ff84d14 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h744ec2e3d1f6d18e
  24:     0x7fdc9ff870b3 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h96687d73280f4761
  25:     0x7fdc9ff7f465 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h118d367dfd2c7af0
  26:     0x7fdc9ff84d84 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h744ec2e3d1f6d18e
  27:     0x7fdc9ff15ebe - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hb5ed60556fed7a1b
  28:     0x7fdc9ff8024a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1b1d9e48d440cac7
  29:     0x7fdc9ff814d0 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h56b5491bb0be970f
  30:     0x7fdc9fca9442 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hd7eec88cf3564b46
  31:     0x7fdc9fd1f2ab - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd7ab282503d4148f
  32:     0x7fdc9fcf3017 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h12d683a16356715f
  33:     0x7fdc9fd1e7c9 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hcfe2eaf3c35dd8a7
  34:     0x7fdc9fd03088 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h572a6bcf310a9e54
  35:     0x7fdc9fcee01d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h07498d16539fd1f6
  36:     0x7fdc9fd0037d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3f99912e8aa56aa1
  37:     0x7fdc9fca9139 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h6697c188e93ee04b
  38:     0x7fdc9fd1b376 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha5a318b8008ed4ad
  39:     0x7fdc9fd0b638 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h73b85976b60bb18d
  40:     0x7fdc9fd0ac0e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h723594efdd7d2c59
  41:     0x7fdc9fc8dedd - tokio::runtime::task::harness::poll_future::hfe639c97ba81bae6
  42:     0x7fdc9fc9160e - tokio::runtime::task::harness::Harness<T,S>::poll::h42fcca695d6eb4c4
  43:     0x7fdca0c4cf45 - std::thread::local::LocalKey<T>::with::h2d0e9ed58861ec70
  44:     0x7fdca0c3d5b3 - tokio::runtime::thread_pool::worker::Context::run_task::h5a52e3ea3fb43a4a
  45:     0x7fdca0c3cabe - tokio::runtime::thread_pool::worker::Context::run::h3cd3802a71cc8058
  46:     0x7fdca0c4ea07 - tokio::macros::scoped_tls::ScopedKey<T>::set::h7ade1805a47fb20f
  47:     0x7fdca0c3c4db - tokio::runtime::thread_pool::worker::run::hc1b2df6af724a650
  48:     0x7fdca0c53c41 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::he8c42e24997221d3
  49:     0x7fdca0c5e949 - tokio::runtime::task::harness::Harness<T,S>::poll::h664d6208268ba0c4
  50:     0x7fdca0c42d8a - tokio::runtime::blocking::pool::Inner::run::h946b4a5079d1c641
  51:     0x7fdca0c519e2 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfacce70eaa0395c5
  52:     0x7fdca0c5506f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd72c29fe0cbbd74b
  53:     0x7fdca0f183b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcbca3baf872b7fe4
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1872:9
  54:     0x7fdca0f183b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h18790338ce1743e2
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1872:9
  55:     0x7fdca0f183b3 - std::sys::unix::thread::Thread::new::thread_start::hb1067183bad48893
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys/unix/thread.rs:108:17
  56:     0x7fdcc36b8fa3 - start_thread
  57:     0x7fdcc35e9eff - clone
  58:                0x0 - <unknown>
  prisma:client:request_handler  PrismaClientRustPanicError: Expected parent IDs to be set when ordering by parent ID.

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v16.17.0+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-1.1.x%7C%0A%7C+Prisma+Client+++%7C+4.1.0++++++++++++++%7C%0A%7C+Query+Engine++++%7C+8d8414deb360336e4698a65aa45a1fbaf1ce13d8%7C%0A%7C+Database++++++++%7C+mysql++++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aprisma%3AtryLoadEnv+Environment+variables+not+found+at+null%0Aprisma%3AtryLoadEnv+Environment+variables+not+found+at+undefined%0Aprisma%3AtryLoadEnv+No+Environment+variables+loaded%0Aprisma%3AtryLoadEnv+Environment+variables+not+found+at+null%0Aprisma%3AtryLoadEnv+Environment+variables+not+found+at+undefined%0Aprisma%3AtryLoadEnv+No+Environment+variables+loaded%0Aprisma%3Aclient+dirname+%2Fkontrol%2Fnode_modules%2F.prisma%2Fclient%0Aprisma%3Aclient+relativePath+..%2F..%2F..%0Aprisma%3Aclient+cwd+%2Fkontrol%0Aprisma%3Aclient+clientVersion%3A+4.1.0%0Aprisma%3Aclient+clientEngineType%3A+library%0Aprisma%3Aclient%3AlibraryEngine+internalSetup%0Aprisma%3Aclient%3AlibraryEngine%3Aloader+Searching+for+Query+Engine+Library+in+%2Fkontrol%2Fnode_modules%2F.prisma%2Fclient%0Aprisma%3Aclient%3AlibraryEngine%3Aloader+loadEngine+using+%2Fkontrol%2Fnode_modules%2F.prisma%2Fclient%2Flibquery_engine-debian-openssl-1.1.x.so.node%0Aprisma%3Aclient+Prisma+Client+call%3A%0Aprisma%3Aclient+prisma.project.findMany%28%7B%0A++select%3A+%7B%0A++++projectId%3A+true%2C%0A++++deployments%3A+%7B%0A++++++take%3A+15%2C%0A++++++orderBy%3A+%7B%0A++++++++createdAt%3A+%27desc%27%0A++++++%7D%2C%0A++++++include%3A+%7B%0A++++++++stages%3A+%7B%7D%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D%29%0Aprisma%3Aclient+Generated+request%3A%0Aprisma%3Aclient+query+%7B%0A++findManyProject+%7B%0A++++projectId%0A++++deployments%28%0A++++++take%3A+15%0A++++++orderBy%3A+%5B%0A++++++++%7B%0A++++++++++createdAt%3A+desc%0A++++++++%7D%0A++++++%5D%0A++++%29+%7B%0A++++++projectId%0A++++++deploymentId%0A++++++triggerUserEmail%0A++++++gitSHA%0A++++++gitRef%0A++++++updatedAt%0A++++++createdAt%0A++++++stages+%7B%0A++++++++projectId%0A++++++++deploymentId%0A++++++++triggerUserEmail%0A++++++++stage%0A++++++++status%0A++++++++deploymentEnv%0A++++++++deploymentRegion%0A++++++++duration%0A++++++++startTime%0A++++++++endTime%0A++++++++updatedAt%0A++++++++createdAt%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D%0A%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+false%0Aprisma%3Aclient%3AlibraryEngine+library+starting%0Aprisma%3Aclient%3AlibraryEngine+library+started%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=Expected+parent+IDs+to+be+set+when+ordering+by+parent+ID.&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 
```

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
I found root cause of this error that Prisma does not support the `utf8mb4_0900_ai_ci` collation table well.
    
This problem occurred when there was a `project` with projectId: `ABC`, and there was a record with projectId: `abc` as FK in the `deployment` and `deployment_stage` tables.

I eventually solved it by modifying the DB data to `ABC` as projectId, I wonder if this problem can be solved by enhancing the `utf8mb4_0900_ai_ci` collation support in Prisma.

**Comment by janpio** [comment]
Can you maybe share an example SQL for such a table? That would make it super easy for us to reproduce the problem and then decide on what needs to happen here. Thanks!

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
The `schema.prisma` file I used to reproduce the error. It can be reproduced with just two tables.

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider          = "mysql"
  url               = env("DB_URL_WITH_CREDENTIALS")
  shadowDatabaseUrl = env("SHADOW_DB_URL_WITH_CREDENTIALS")
}

model Project {
  projectId         String             @id @map("project_id") @db.VarChar(40)
  createdAt         DateTime           @default(now()) @map("created_at")
  deployments       Deployment[]
  @@map("project")
}

model Deployment {
  projectId        String            @map("project_id") @db.VarChar(40)
  project          Project           @relation(fields: [projectId], references: [projectId])
  deploymentId     String            @map("deployment_id") @db.VarChar(20)
  createdAt        DateTime          @default(now()) @map("created_at")
  @@id([projectId, deploymentId])
  @@map("deployment")
}
```

This is the query created with the `prisma migrate dev --create-only` command. What I found out while writing this comment is that errors occur in both collations `utf8mb4_unicode_ci` and `utf8mb4_0900_ai_ci`. So, you can reproduce the error even if you use the following query generated by prisma as it is.

```sql
-- CreateTable
CREATE TABLE `project` (
    `project_id` VARCHAR(50) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`project_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `deployment` (
    `project_id` VARCHAR(40) NOT NULL,
    `deployment_id` VARCHAR(20) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`project_id`, `deployment_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `deployment` ADD CONSTRAINT `deployment_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `project`(`project_id`) ON DELETE RESTRICT ON UPDATE CASCADE;

```

insert sample contents to check non-error case:

```sql
INSERT INTO `project` (`project_id`, `created_at`) VALUES
('p1', '2022-08-26 16:31:28.673'),
('p2', '2022-08-26 16:31:28.683');

INSERT INTO `deployment` (`project_id`, `deployment_id`, `created_at`) VALUES
('p1', 'd1', '2022-08-26 16:31:47.098'),
('p1', 'd2', '2022-08-26 16:34:12.807'),
('p2', 'd1', '2022-08-26 16:34:12.818'),
('p2', 'd2', '2022-08-26 16:31:47.108');
```

test code:
```ts
// test.js
const { PrismaClient } = require('@prisma/client')

const db = new PrismaClient({
  log: [{ emit: 'event', level: 'query' }],
})

db.$on('query', e => {
  console.log(`Query: ${e.query}`)
  console.log(`Params: ${e.params}`)
  console.log(`Duration: ${e.duration}ms`)
})

const run = async () => {
  const projects = await db.project.findMany({
    select: {
      projectId: true,
      deployments: {
        take: 15,
        orderBy: { createdAt: 'desc' },
      },
    },
  })
  console.log(JSON.stringify(projects, null, 2))
}

if (require.main === module) {
  run().catch(console.error)
}
```

Run test code to check success results.
```js
$ node test.js

Query: SELECT `local_db`.`project`.`project_id` FROM `local_db`.`project` WHERE 1=1
Params: []
Duration: 8ms
Query: SELECT `local_db`.`deployment`.`project_id`, `local_db`.`deployment`.`deployment_id`, `local_db`.`deployment`.`created_at` FROM `local_db`.`deployment` WHERE `local_db`.`deployment`.`project_id` IN (?,?) ORDER BY `local_db`.`deployment`.`created_at` DESC
Params: ["p1","p2"]
Duration: 3ms
[
  {
    "projectId": "p1",
    "deployments": [
      {
        "projectId": "p1",
        "deploymentId": "d2",
        "createdAt": "2022-08-26T16:34:12.807Z"
      },
      {
        "projectId": "p1",
        "deploymentId": "d1",
        "createdAt": "2022-08-26T16:31:47.098Z"
      }
    ]
  },
  {
    "projectId": "p2",
    "deployments": [
      {
        "projectId": "p2",
        "deploymentId": "d1",
        "createdAt": "2022-08-26T16:34:12.818Z"
      },
      {
        "projectId": "p2",
        "deploymentId": "d2",
        "createdAt": "2022-08-26T16:31:47.108Z"
      }
    ]
  }
]
```

To reproduce this error, insert a Deployment record with a projectId `P1` using a capital `P`.

```sql
INSERT INTO `deployment` (`project_id`, `deployment_id`, `created_at`) VALUES
('P1', 'd3', '2022-08-26 17:12:06.000'),
('p1', 'd4', '2022-08-26 17:12:54.207');
```

> The following record (p1, d4) must also be inserted for this error to be reproduced.

Then, when you run test.js again, you can reproduce the error.

```shell
Query: SELECT `local_db`.`project`.`project_id` FROM `local_db`.`project` WHERE 1=1
Params: []
Duration: 9ms
thread 'tokio-runtime-worker' panicked at 'Expected parent IDs to be set when ordering by parent ID.', query-engine/core/src/interpreter/query_interpreters/inmemory_record_processor.rs:69:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Query: SELECT `local_db`.`deployment`.`project_id`, `local_db`.`deployment`.`deployment_id`, `local_db`.`deployment`.`created_at` FROM `local_db`.`deployment` WHERE `local_db`.`deployment`.`project_id` IN (?,?) ORDER BY `local_db`.`deployment`.`created_at` DESC
Params: ["p1","p2"]
Duration: 6ms
PrismaClientRustPanicError: 
Invalid `db.project.findMany()` invocation in
/Users/alfred/projects/issue14899/scripts/import-db-data-from-source-db-url.js:14:37

  11 })
  12 
  13 const run = async () => {
→ 14   const projects = await db.project.findMany(
  Expected parent IDs to be set when ordering by parent ID.

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++.......

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at RequestHandler.handleRequestError (/Users/alfred/projects/issue14899/node_modules/@prisma/client/runtime/index.js:28846:13)
    at RequestHandler.request (/Users/alfred/projects/issue14899/node_modules/@prisma/client/runtime/index.js:28820:12)
    at async PrismaClient._request (/Users/alfred/projects/issue14899/node_modules/@prisma/client/runtime/index.js:29753:16)
    at async run (/Users/alfred/projects/issue14899/scripts/test.js:14:20) {
  clientVersion: '4.2.1'
}
```

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@janpio To make replaying errors easy and accurate, I also created a repository https://github.com/b6pzeusbc54tvhw5jgpyw8pwz2x6gs/prisma-issue-14899

**Comment by Jolg42** [comment]
Error with same error message, potentially related
https://github.com/prisma/prisma/issues/9875

**Comment by Jolg42** [comment]
Note: We think this might be caused by the engine join which does things differently than the database join

**Comment by pimeys** [comment]
I can still reproduce this with Prisma 4.3.1. MySQL is case-insensitive by default with foreign keys, so `P1` can be joined with `p1`. We could of course allow this in the core by joining in a case-insensitive manner, but that would then break collations that is case-sensitive.

The right solution is to let the database to join instead of us doing so.

**Comment by pmosconi** [comment]
I just (painfully) confirmed this on 5.8 with SqlServer that is case insensitive. Is it correct to expect that native joins will solve this issue?
