### ISSUE TITLE
sslaccept=accept_invalid_certs not working with mysql server 8.0.30

### ISSUE THREAD

**Issue by P4sca1** [prisma/prisma#14903]
### Bug description

After upgrading my MySQL server to 8.0.30, prisma is no longer able to connect.
> Error querying the database: Server error: `ERROR 08S01 (1043): Bad handshake'`

### How to reproduce

1. Deploy a MySQL server with version 8.0.30
2. Add `?sslaccept=accept_invalid_certs` to your `DATABASE_URL`

### Environment & setup

- Database: MySQL 8.0.30
- Node.js version: 16.13.0

### Prisma Version

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by Jolg42** [comment]
Using Prisma version `4.2.1` and `MySQL 8.0.26` deployed on Google Cloud 

`npx prisma db pull` (or push) work like expected with the following conenction string:
```
DATABASE_URL="mysql://root:PASSWORD@34.141.92.205:3306/14903?sslaccept=accept_invalid_certs"
``` 

@P4sca1 Could you tell us if this happens with a particular
- database provider? Which one did you try with?
- is it specific to MySQL `8.0.30` maybe?
- Which command did you execute?

**Comment by Jolg42** [comment]
Note that it would be interesting to try the latest Prisma version to see if the problem is the same, currently [`4.5.0`](https://github.com/prisma/prisma/releases)

**Comment by P4sca1** [comment]
Just tried with prisma 4.5.0 and the issue persists. It happens right after calling `prisma.$connect()`.

```
[11:49:22.877] INFO (prisma): Starting a mysql pool with 13 connections.
    target: "quaint::pooled"
[11:49:23.113] FATAL: Startup failed
    err: {
      "type": "PrismaClientInitializationError",
      "message": "Error querying the database: Server error: `ERROR 08S01 (1043): Bad handshake'",
      "stack":
          Error: Error querying the database: Server error: `ERROR 08S01 (1043): Bad handshake'
              at startFn (/Users/pascal/code/ips-hosting/api/node_modules/@prisma/client/runtime/index.js:27188:17)
              at async main (/Users/pascal/code/ips-hosting/api/src/main.ts:16:3)
      "clientVersion": "4.5.0"
    }
```

It's a self hosted MySQL server running on Ubuntu 20.04.4 LTS, installed from the official package registry.

**Comment by P4sca1** [comment]
I just upgraded to MySQL 8.0.31 (latest version available via package manager), which did not resolve the issue.

**Comment by P4sca1** [comment]
Might be related: https://github.com/prisma/prisma/issues/15641
Same error and same MySQL version.

**Comment by Jolg42** [comment]
Note: An issue was open by someone else, and it looks like the same problem to me https://github.com/prisma/prisma/issues/16886

**Comment by Jolg42** [comment]
I tried to get a reproduction of this error, but so far could not.

One person reported the following workaround
- pin MySQL Server to v8.0.29

**Comment by Jolg42** [comment]
I could reproduce on Google Cloud SQL with MySQL v8.0.30+
and locally with
```
version: "3.7"
services:
  mysql803:
    image: mysql:8.0.30
	# This does not change anything
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tests
      - MYSQL_USER=prisma
    ports:
      - "3306:3306"
```

.env
```
DATABASE_URL="mysql://root:root@localhost:3306/16886?sslaccept=accept_invalid_certs"
```

With Prisma versions, 4.6.1, 4.7.1, 4.8.0.
Example with `prisma db push` (it also errors with Prisma Client)
```
npx prisma db push
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "16886" at "34.89.164.209:3306"

Error: Migration engine error:
Bad handshake
```

Removing `sslaccept=accept_invalid_certs` makes this error disappear. 

Release notes of MySQL 8.0.30
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-30.html

**Comment by Jolg42** [comment]
Someone who knows quaint / mysql in Prisma engines could have a look here

We use a fork of mysql_async with the vendored-openssl feature/branch in
https://github.com/prisma/quaint/blob/main/Cargo.toml

The fork
https://github.com/prisma/mysql_async/tree/vendored-openssl

**Comment by WY-S** [comment]
> I could reproduce on Google Cloud SQL with MySQL v8.0.30+ and locally with
> 
> ```
> version: "3.7"
> services:
>   mysql803:
>     image: mysql:8.0.30
> 	# This does not change anything
>     # command: --default-authentication-plugin=mysql_native_password
>     restart: always
>     environment:
>       - MYSQL_ROOT_PASSWORD=root
>       - MYSQL_DATABASE=tests
>       - MYSQL_USER=prisma
>     ports:
>       - "3306:3306"
> ```
> 
> .env
> 
> ```
> DATABASE_URL="mysql://root:root@localhost:3306/16886?sslaccept=accept_invalid_certs"
> ```
> 
> With Prisma versions, 4.6.1, 4.7.1, 4.8.0. Example with `prisma db push` (it also errors with Prisma Client)
> 
> ```
> npx prisma db push
> Environment variables loaded from prisma/.env
> Prisma schema loaded from prisma/schema.prisma
> Datasource "db": MySQL database "16886" at "34.89.164.209:3306"
> 
> Error: Migration engine error:
> Bad handshake
> ```
> 
> Removing `sslaccept=accept_invalid_certs` makes this error disappear.
> 
> Release notes of MySQL 8.0.30 https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-30.html
> 
> > Important Change: For platforms on which OpenSSL libraries are bundled, the linked OpenSSL library for MySQL Server has been updated to version 1.1.1o. Issues fixed in OpenSSL version 1.1.1o are described at https://www.openssl.org/news/cl111.txt and https://www.openssl.org/news/vulnerabilities.html. (Bug #34133985)
> 
> Release notes of MySQL 8.0.31 https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-31.html
> 
> > Important Change: For platforms on which OpenSSL libraries are bundled, the linked OpenSSL library for MySQL Server has been updated to version 1.1.1q. Issues fixed in OpenSSL version 1.1.1q are described at https://www.openssl.org/news/cl111.txt and https://www.openssl.org/news/vulnerabilities.html. (Bug #34414695)
> 
> MySQL 8.0 error reference https://downloads.mysql.com/docs/mysql-errors-8.0-en.pdf
> 
> > Error number: 1043; Symbol: ER_HANDSHAKE_ERROR; SQLSTATE: 08S01
> > Message: Bad handshake

Hi @Jolg42 May I ask if we have any plan to fix this bug?

**Comment by shangzhipan** [comment]
@Jolg42 We are seeing the same problem with Prisma.io trying to connect to MySQL 8.0.31 using SSL. Our theory is that MySQL version 8.0.30 removed a couple of legacy SSL cipher suits. Prisma.io does not seem to use the node.js native openssl implementation but rather a vendor lib. We need to update those libs or change to something that are not using legacy SSL cipher suits.

**Comment by Marcdj-02** [comment]
> We are seeing the same problem with Prisma.io trying to connect to MySQL 8.0.31 using SSL. Our theory is that MySQL version 8.0.30 removed a couple of legacy SSL cipher suits. Prisma.io does not seem to use the node.js native openssl implementation but rather a vendor lib. We need to update those libs or change to something that are not using legacy SSL cipher suits. ECDHE-ECDSA-AES256-GCM-SHA384 and ECDHE-ECDSA-AES128-GCM-SHA256 are not supported anymore.

Seem to be the case. 8.0.28 gives no problems, 8.0.31 does result in a bad handshake.

**Comment by mathijs-jojoschool** [comment]
+1

**Comment by GuillaumeSarfati** [comment]
+1

**Comment by Marcdj-02** [comment]
@Jolg42 Any intention on fixing this in an upcoming release?

**Comment by nalham** [comment]
@Jolg42 Is there a need for Prisma to keep the fork to mysql_async? Is it possible to use the non-forked version?

**Comment by janpio** [comment]
Nothing is impossible 😆 

We originally forked to be able to use a vendored OpenSSL (which is why our fork relies on a fork of https://github.com/tokio-rs/tls). That recently was merged upstream, so we can start cleaning up that chain and see where we are at with `mysql_async`. WE just recently added another change... but that might not keep us from getting all the other changes from upstream.

Do you have information about mysql_async that this problem would go away if we upgrade to the recent releases?

**Comment by shangzhipan** [comment]
@janpio Yes, our assumption is that the OpenSSL implementation in the vendored openssl feature/branch of that mysql_async fork is outdated and does not work with MySql 8.0.30+ anymore.

**Comment by janpio** [comment]
I can confirm that the prior reproduction from @Jolg42 does not fail any more with `prisma@4.11.0-dev.51` (but did with `prisma@4.10.1`).

**Comment by nalham** [comment]
@janpio thanks for following up, confirmed 4.11 fixes my issue
