### ISSUE TITLE
Triggers not working properly with Prisma: [ERROR] `Query '' is required to return data, but found no record(s).`

### ISSUE THREAD

**Issue by gmwill934** [prisma/prisma#14918]
### Bug description

Hello

I'm having trouble when trying to insert a new record to my `shipment` table, I have a trigger that is in charge of creating a custom unique ID. (you can see the sql script in the `How to reproduce` section.

NOTE: Whenever I drop the trigger from the table, I can create a record without an error.

Couple of **notes**
- **The trigger works when I use pgAdmin to execute raw sql scripts.**
- **Whenever I drop the trigger from the table, I can create a record without an error.**

This is the **error** that I get

```
/Users/gmwill934/Documents/gmwill934/prisma-trigger-error/node_modules/@prisma/client/runtime/index.js:28842
      throw new PrismaClientUnknownRequestError(message, this.client._clientVersion);
            ^
PrismaClientUnknownRequestError: 
Invalid `prisma.shipment.create()` invocation in
/Users/gmwill934/Documents/gmwill934/prisma-trigger-error/prisma.ts:15:34

  12 await prisma.$executeRawUnsafe(setClient("NPS"));
  13 await prisma.$executeRawUnsafe(setWarehouse("01"));
  14 
→ 15 return await prisma.shipment.create(
  Query createOneshipment is required to return data, but found no record(s).
    at RequestHandler.handleRequestError (/Users/gmwill934/Documents/gmwill934/prisma-trigger-error/node_modules/@prisma/client/runtime/index.js:28842:13)
    at RequestHandler.request (/Users/gmwill934/Documents/gmwill934/prisma-trigger-error/node_modules/@prisma/client/runtime/index.js:28820:12)
    at async PrismaClient._request (/Users/gmwill934/Documents/gmwill934/prisma-trigger-error/node_modules/@prisma/client/runtime/index.js:29753:16) {
  clientVersion: '4.2.1'
}
```

### How to reproduce

1. On pgAdmin (postgres), run the following `sql script` to create the table.
```
create table shipment (
	client varchar(16) not null default(current_setting('app.client')::varchar(16)),
	warehouse varchar(16) not null default(current_setting('app.warehouse')::varchar(16)),
	id varchar(64) default(''),
	notes text null,
	is_validated boolean not null default(false),
	constraint "PK_Shipment__id" primary key (id)
);
```
2.  Run the following `sql script` to create the trigger function
```
create or replace function shipment_custom_id_generator() returns trigger as $$
begin
	new.id = (select
		   		current_setting('app.client') || current_setting('app.warehouse') || 'LPN' || LPAD(cast(count(*) + 1 as varchar(64)),8,'0')::varchar(16)
			from 
				shipment
			where
				client = current_setting('app.client')
				and warehouse = current_setting('app.warehouse')
		   );
	return new;
end
$$ language plpgsql
```
3. Create the trigger
```
create trigger shipment_custom_generator_id_trigger
before insert on shipment
for each row
execute procedure shipment_custom_id_generator();
```
4. Clone the repo https://github.com/gmwill934/prisma-trigger-error
5. Install dependencies
6. Create a .env file with a `DATABASE_URL` attribute. Make sure it matches your local pg environment. (`DATABASE_URL="postgresql://user:password@localhost:port/database-name?schema=schema-name"`)
7. Run `npm run prisma:pull` to introspect the database
8. Generate prisma client running `npm run prisma:generate`
9. Run the app with `npm run dev`

### Expected behavior

Insert a new record on the `shipment` table without a `500` error code.

### Prisma information

This is the my prisma schema

```
model shipment {
  client       String  @default(dbgenerated("(current_setting('app.client'::text))::character varying(16)")) @db.VarChar(16)
  warehouse    String  @default(dbgenerated("(current_setting('app.warehouse'::text))::character varying(16)")) @db.VarChar(16)
  id           String  @id(map: "PK_Shipment__id") @default("") @db.VarChar(64)
  notes        String?
  is_validated Boolean @default(false)
}
```

### Environment & setup

- OS: Mac OS M1
- Database: Postgres 14
- Node.js version: v16.15.1

### Prisma Version

```
4.2.1
```

**Comment by janpio** [comment]
Prisma can currently probable not handle the way the trigger fills in the ID, or can not retrieve the data that was created as it was modified before the `INSERT` by the trigger. That is an interesting problem, that we will need to understand and fix somehow. That will definitely not be easy.

Can you maybe create a simplified schema and trigger etc to reproduce this that we can easily execute ourselves? Seeing this in action would be very helpful. Thanks.

**Comment by gmwill934** [comment]
For sure @janpio 

1. Clone the repo @ `https://github.com/gmwill934/prisma-simple` and `cd` to new created folder
2. Install dependencies with `npm i`
3. Create .env file and specify the `DATABASE_URL` property (https://www.prisma.io/docs/concepts/database-connectors/postgresql#connection-details)
4. Execute migrations and generate client `npx prisma migrate dev` and enter a nme for the migration
5. Run SQL script (script.sql) to create simple trigger function and trigger
6. Run app with `npm run dev`
7. See ERROR

**A few notes.**

- It appears PRISMA only errors out when no records exist on the table
- If you first insert manually a new record and run the app again, no error is shown (on the first example that I showed, it didn't work either way)


**FOR QUICK REFERENCE**

Prisma Schema

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model shipment {
  id   Int     @id
  data String? @db.VarChar(64)
}

```
SQL Script

```
create or replace function my_trigger() returns trigger as $$
	begin
		new.id = (select count(*) + 1 from shipment);
		return new;
	end
$$ language plpgsql;

create or replace trigger shipment_my_trigger
before insert on shipment
for each row
execute procedure my_trigger();




```

**Comment by wmgsh** [comment]
Hello, are there any updates on this matter?

How can I help?

**Comment by gmwill934** [comment]
Is there any update on this? How can I help?

**Comment by gmwill934** [comment]
Where you able to replicate this? @janpio

**Comment by Jolg42** [comment]
@gmwill934 As `createMany` doesn't do any `select` (it doesn't return data) it should work well as a workaround.
Let us know if this works for you:
```ts
 return await prisma.shipment.createMany({
      data: [{ notes: "My super awesome notes!" }],
    });
```

**Comment by gmwill934** [comment]
@Jolg42 

It’s working! I still need the id though, but I’ll manage with this for now! 

Any plans on fully supporting this?

**Comment by gmwill934** [comment]
@janpio 
For postgresql, instead of doing a select after an insert, what about the following?

`insert into table (column_one) values ('value') returning *;`

**Comment by gmwill934** [comment]
Anything else I can do to help with prisma team?

**Comment by janpio** [comment]
No, we need to find the time to reproduce this and then think about a possible solution. Triggeres intervening with primary key values is not a common use case our users report to us, so compared to other bugs or features it will most probably not have the highest priority unfortunately.

Does the suggested workaround work fully for you? If so, that would additionally count against us prioritizing this. Although we of course want to support many use cases, a working workaround sometimes has to be enough. I hope you understand.

**Comment by gmwill934** [comment]
Unfortunately it doesn't work, I need to be able to select the id for further business logic. 

I do understand you! Hopefully this can be fixed at some point.

Thanks @janpio

**Comment by janpio** [comment]
If the data you inserted is unique, you could use a query to retrieve the created row that way. Not nice and one technically not necessary query, but it would probably be an ok workaround for now hopefully unblocking you.

**Comment by gmwill934** [comment]
Tried workarounds but no luck, data is not unique. Hoping the team could address this at some point.

Thank you very much @janpio

**Comment by wmra92** [comment]
Hey

Would this be possible with client extensions?  @janpio

**Comment by gmwill934** [comment]
Would this be possible with client extensions?

**Comment by janpio** [comment]
Interesting idea. You could probably catch the error in the extension, and manually run a `find` query manually to retrieve the data and then return it. That would make it look like it just works in your application, at the cost of having to have the extension and the additional query. Depends very much on the complexity of your Client query if this is feasible and convenient.

**Comment by gmwill934** [comment]
With the release of Prima 5.1, do you think this will now work? @janpio

**Comment by janpio** [comment]
We have not done any specific work on this, or this would have been posted here and the issue closed. So if something changed, it would be accidental and we would not be aware of it yet. Sorry, this has not been prioritized yet.
