### ISSUE TITLE
Type error in `IN` clause in postgreSQL using `$queryRaw` when upgrading to v4

### ISSUE THREAD

**Issue by floriantz** [prisma/prisma#14978]
### Bug description

There seems to be a regression regarding `IN` clauses in postgreSQL in prisma v4.

The issue happened on postgresql and the behaviour changed somewhere between prisma `3.15.2` and `4.2.1`.

For a given table of this structure:
````sql
CREATE TABLE repro(
    `id` UUIN NOT NULL PRIMARY KEY,
)
````

When querying a list of rows using an IN query clause like so:
```typescript
   const rows = await this.prismaClient.$queryRaw<
    { id: string }[]
    >(Prisma.sql`
      SELECT id
      FROM repro
      WHERE id IN (${Prisma.join(ids)});
    `)
```

This worked fine in `3.15.2` but returns a type error in `4.2.1`:
```json
{
  "code": "P2010",
  "clientVersion": "4.2.1",
  "meta": {
    "code": "42883",
    "message": "db error: ERROR: operator does not exist: uuid = text\nHINT: No operator matches the given name and argument types. You might need to add explicit type casts."
  }
}
```

I've tried different castings but nothing seemed to work.

This query works on the other hand:
```typescript
   const rows = await this.prismaClient.$queryRaw<
    { id: string }[]
    >(Prisma.sql`
      SELECT id
      FROM repro
      WHERE id = ANY (ARRAY[${Prisma.join(ids)}]::uuid[]);
    `)
```

I haven't seen what would cause this in the upgrade guide and it does look like a regression to me.
I'm guessing there's a change in how the casting is done which broke this query.

### How to reproduce

A reproduction repository is available here: https://github.com/floriantz/repro-prisma 

### Expected behavior

The query should not cause an error

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgres"
  url      = "postgres://postgres:postgres@localhost:5432/postgres"
}

model repro {
  id String @id @db.Uuid
}
```

### Environment & setup

- OS: MacOS 12.2.1
- Database: PostgreSQL
- Node.js version: 16+

### Prisma Version

```
prisma                  : 4.2.1
@prisma/client          : 4.2.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2920a97877e12e055c1333079b8d19cee7f33826 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 2920a97877e12e055c1333079b8d19cee7f33826
Studio                  : 0.469.0
```

**Comment by emmanuelpineda** [comment]
I upgraded from version 3.15.2 to version 4.3.1 and I got the same error:
![image](https://user-images.githubusercontent.com/45979790/188714094-c08e1c62-968e-4660-a9e1-ce423b58bb5c.png)


![image](https://user-images.githubusercontent.com/45979790/188713958-3b83cae5-c3ce-4602-96c4-df60833856e2.png)

**Comment by janpio** [comment]
Seems in 3.x Prisma just sent the resulting string of `userIdsToIgnore` (for @emmanuelpineda) and `Prisma.join(ids)` (for @floriantz) in an let the database figure out how to match that with the `uuid` type column. In 4.x we changed some things around how raw queries type the data, and it is now probably explicitly sent as tpye `text` - which the database can not match to `uuid` itself. (Casting should somehow fix this, but I am not sure what exactly that should look like for a `IN` param)

**Comment by floriantz** [comment]
> Seems in 3.x Prisma just sent the resulting string of userIdsToIgnore (for @emmanuelpineda) and Prisma.join(ids) (for @floriantz) in an let the database figure out how to match that with the uuid type column. In 4.x we changed some things around how raw queries type the data, and it is now probably explicitly sent as tpye text - which the database can not match to uuid itself. (Casting should somehow fix this, but I am not sure what exactly that should look like for a IN param)

I've tried quite a few different things to try and cast to a uuid array, but nothing worked except this version which does not use an `IN` query:

```sql
WHERE id = ANY (ARRAY[${Prisma.join(ids)}]::uuid[])
```

Though I'd rather use IN queries. But I haven't found a way to cast that works, I always end up with an explicit `text` type.

Since these kind of queries are quite common, it might be good to have an example on how to cast those.

**Comment by Weakky** [comment]
Hey @floriantz,

Could you try doing the following?

```ts
const ids = [
 '422b72f9-2ec9-4482-8a2f-527251af5606',
 'ee5f92a7-1741-48d4-b8c3-517e9621453a',
].map(uuid => Prisma.sql`${uuid}::uuid`);

const rows = await client.$queryRaw`
  SELECT id
  FROM repro
  WHERE id IN (${Prisma.join(ids)});
`;
```

Let us know whether that fixes your issue.

**Comment by bryanjswift** [comment]
Using the `separator` and `suffix` arguments of `Prisma.join` also appears to work. Though now that I've seen the map casting individual values with `Prisma.sql` I find that more readable.

```ts
const rows = await client.$queryRaw`
  SELECT id
  FROM repro
  WHERE id IN (${Prisma.join(ids, '::uuid,', '', '::uuid')});
`;
```

**Comment by WesleyYue** [comment]
when trying to use any of the solutions in this thread, I get the following cryptic error:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at new Sql (/Users/wesley/Code/double/node_modules/@prisma/client/runtime/library.js:164:19658)
    at klona (/Users/wesley/Code/double/node_modules/@prisma/client/runtime/library.js:164:9172)
    at klona (/Users/wesley/Code/double/node_modules/@prisma/client/runtime/library.js:164:9458)
    at /Users/wesley/Code/double/node_modules/@prisma/client/runtime/library.js:164:10168
    at _callback (/Users/wesley/Code/double/node_modules/@prisma/client/runtime/library.js:164:2796)
    at PrismaPromise.then (/Users/wesley/Code/double/node_modules/@prisma/client/runtime/library.js:164:2887)
```

Any ideas?

**Comment by sneko** [comment]
Had hard time with a simpler case, just using a uuid (not in array). In case it can help you have to write:
```ts
await prisma.$queryRaw`SELECT ... WHERE id = ${user.id}::uuid`;
```

(it was not obvious to me, https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access never mentions any casting)

**Comment by SevInf** [comment]
@WesleyYue could you share your schema and prisma query you are executing, as well as Prisma verison? I am not able to reproduce the issue with the information you've provided.

I can meanwhile confirm that solutions mentioned [here](https://github.com/prisma/prisma/issues/14978#issuecomment-1246753681) and [here](https://github.com/prisma/prisma/issues/14978#issuecomment-1307766093) work and requiring type cast in 4.x was intentional on our side.
I agree that our docs could be improved (I've opened an [issue for that](https://github.com/prisma/docs/issues/5222)) and mention the solution for this specific case, but there is no bug on Prisma side here.

**Comment by janpio** [comment]
Did you see Serhii's message @WesleyYue?

**Comment by WesleyYue** [comment]
Can you share your emails? I'll send you the schema and a loom over email

**Comment by janpio** [comment]
my first name @prisma.io should work.

**Comment by Weakky** [comment]
Hey folks,

This reason behind this issue is a bit complex so I'll explain you how we arrived to this.

The need for more specific type casts was introduced in https://github.com/prisma/prisma/releases/tag/3.14.0. For context, it was introduced because we were suffering from lots of subtle and implicit type casts on PG's side which were confusing users or even worse, preventing basic queries from working.

By default, Postgres _infers_ the types of your query parameters based on where they are used. Here's an example:

``` sql
PREPARE SELECT LENGTH($1);
```

For this prepared statement, Postgres will answer back with a type for `$1` of `TEXT` (because LENGTH can only accept a TEXT input). Based on which type PG infers, the PG driver encodes query parameters values as the specified type.

Unfortunately, there were many cases where Postgres could not infer the types correctly. Here's a simple example:

```sql
await prisma.$queryRaw`SELECT ${1.5}::int`;
```

This query used to fail because PG always infers the type of the query param as the type it is being cast to. So in this case, `$1` was inferred as an `int`. Consequently, the value `1.5` was encoded as an integer and sent to the database like that. No need to explain you why a float encoded as an int was not working well 🙈.

To circumvent that issue, we have decided to no longer let PG infer the types of query parameters and instead _specify_ the type of every individual query parameters based on the incoming javascript values. In the example above, this means that `1.5` is inferred, by _Prisma_, as a `NUMERIC` type, encoded as a `NUMERIC` and sent to PG as a `NUMERIC`. Problem solved.

The downside of this approach is that, in some cases, we can't properly infer the types of your values. In fact, Prisma can only infer the following types (there might be small mistakes in this list):
- Number -> INT(4, 8)
- Number -> NUMERIC
- String -> TEXT
- Bytes -> BYTEA
- Boolean -> BOOL
- Char -> CHAR
- Date -> TIMESTAMPTZ
- (maybe more, but I can't think of more from the top of my head)

In OP's case, we've got a problem because Prisma _cannot_ know that the string value is actually a uuid. So the string is encoded as a string, PG fails to implicitly cast it to a uuid and so it errors. _This_ is the reason why it fails.

Now, we wouldn't want to go to the old behaviour, even knowing this bug. There are only two other alternatives that I can think of to improve the situation:

1. [Switch to the TEXT protocol](https://github.com/prisma/prisma/issues/3337) (instead of the binary protocol we currently use), which is less sensitive to these types shenanigans (and which is used by all JS drivers out there)
2. Introduce type-specific wrappers client side so that users can specify the types of their values when it is ambiguous
	```ts
	import { Prisma, PrismaClient } from "@prisma/client";
	
	async function main() {
	  const prisma = new PrismaClient();
	
	  const ids = [
	    Prisma.Uuid("178d1412-35a2-4a9d-9e6c-e85607f52733"),
	    Prisma.Uuid("2515c1d5-c17a-4988-ba2b-cf5dd9232b36"),
	    Prisma.Uuid("27a8fdde-1514-4338-ab08-32750bd8bb30"),
	  ];
	
	  const rows = await prisma.$queryRaw<{ id: string }[]>(Prisma.sql`
	    SELECT id
	    FROM repro
	    WHERE id IN (${Prisma.join(ids)});
	  `);
	
	  await prisma.$disconnect();
	}
	```

The TEXT protocol sounds like our best bet, but also the riskiest one.

All that to say what? There's technically something we can do about this, and you're right that the DX is not great. @SevInf has already created an issue to improve documentation and that's what we should focus on short-term.

Long-term, solutions presented above feel too costly for the attraction it currently has.

Based on that, here's what I'll do:
- Keep this issue open until we do something about it. I'll mark it as `confirmed`.
- Remove the `kind/regression` label. It's not a regression. It's a known limitation that we knew when introducing this fix. It was clearly noted as a breaking change in the release notes.

Finally, I know this comment doesn't bring much to the table in terms of solution. But I hope it'll give context to others coming to this issue.

Thanks

**Comment by WesleyYue** [comment]
@Weakky thanks, this is very clear. I'm not familiar with the inner workings of how the type inference occurs, but is it not possible to add a bit of extra logic to cast the strings as uuid automatically if it sees ::uuid after? And throw an error if you try to do something like cast a float as an int?

**Comment by floriantz** [comment]
@Weakky Option 2 would be enough imho, but it requires to be well documented and easy to discover since it is a very common use-case of Prisma when using Postresql.

**Comment by klotztech** [comment]
I also came across the same issue when selecting a range of UUIDs in a raw query.
As it seems Prisma is able to pass arrays of primitive values as a single query parameter. 
To anyone interested: I adapted my solution to use the following:

```typescript
const ids = [
    "178d1412-35a2-4a9d-9e6c-e85607f52733",
    "2515c1d5-c17a-4988-ba2b-cf5dd9232b36",
    "27a8fdde-1514-4338-ab08-32750bd8bb30",
];
// pass `ids` as text[] -> cast to uuid[]
await prisma.$queryRaw`SELECT ... WHERE "id" = ANY(${ids}::uuid[])`
```

**Comment by sikirumoshood** [comment]
This worked for me:
Where `','` is the separator, `''` prefix, `::"DeliveryMediumEnum"` suffix

```
da."deliveryMedium" IN (${Prisma.join(deliveryMediums, ',', '', '::"DeliveryMediumEnum"')})
```

**Comment by mib008** [comment]
WHERE "id"::text = ${id}

it works for me.

**Comment by am484evits** [comment]
> WHERE "id"::text = ${id}
> 
> it works for me.

@mib008 no its not working

**Comment by AviBueno** [comment]
Using `Prisma.join()` I got a final `WHERE "myField" IN ([object Object])` (maybe because I'm further joining the result as a string with other strings, but why should that matter?)

So I managed to pull this off with something like:
```
  joinTypedValues(values: string[], type: string): string {
    return values.map((value) => `'${value}'::"${type}"`).join(',');
  }
```

**Comment by l0gicgate** [comment]
@klotztech's solution worked for me. Thank you!

```ts
const ids = [
    "178d1412-35a2-4a9d-9e6c-e85607f52733",
    "2515c1d5-c17a-4988-ba2b-cf5dd9232b36",
    "27a8fdde-1514-4338-ab08-32750bd8bb30",
];
// pass `ids` as text[] -> cast to uuid[]
await prisma.$queryRaw`SELECT ... WHERE "id" = ANY(${ids}::uuid[])`
```
