### ISSUE TITLE
Error in migration engine (quaint result_row) index out of bounds: the len is 1 but the index is 10 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#15017]
Command: `prisma db push`
Version: `3.14.0`
Binary Version: `2b0c12756921c891fec4f68d9444e18c7d5d4a6a`
Report: https://prisma-errors.netlify.app/report/14254 
OS: `arm64 darwin 21.4.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [/Users/runner/.cargo/git/checkouts/quaint-9f01e008b9a89c14/0e60962/src/connector/result_set/result_row.rs:59:64] index out of bounds: the len is 1 but the index is 10

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

    at handlePanic (/node_modules/prisma/build/index.js:112999:25)
    at ChildProcess.<anonymous> (/node_modules/prisma/build/index.js:113008:15)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

Rust Stacktrace:
```
Starting migration engine RPC server
The migration was not applied because it triggered warnings and the force flag was not passed.
[/Users/runner/.cargo/git/checkouts/quaint-9f01e008b9a89c14/0e60962/src/connector/result_set/result_row.rs:59:64] index out of bounds: the len is 1 but the index is 10
```

**Comment by jkomyno** [comment]
Still happening in 4.5.0: https://prisma-errors.netlify.app/report/14526

**Comment by janpio** [comment]
Both reports are using `relationMode=prisma`, so most probably PlanetScale.

**Comment by Weakky** [comment]
Hey,

We have tried with both datamodels from both reports (14254 & 14256) and couldn't reproduce on latest Prisma version, prisma@3.14 or prisma@4.5.0.

Given that we can't ping any user here, I'm now closing this issue.
