### ISSUE TITLE
Error in migration engine. Reason: called `Result::unwrap()` on an `Err` value: Error("unknown variant `Text`, expected one of `Bit`, `Bool`, `Bytes`, `Char`, `Date`, `Decimal`, `Float4`, `Float8`, `Inet`, `Int2`, `Int4`, `Int8`, `JsonB`, `Oid`, `CatalogSingleChar`, `String`, `Time`, `Timestamp`, `Timestamptz`, `Timetz`, `Uuid`, `VarBit`", line: 0, column: 0) 

### ISSUE THREAD

**Issue by jkomyno** [prisma/prisma#15019]
This sounds like a misalignment between a local `schema.prisma` file and the actual DB schema that generates a confusing error message about native types.

Command: `prisma migrate dev`
Version: `4.2.1`
Binary Version: `2920a97877e12e055c1333079b8d19cee7f33826`
Report: https://prisma-errors.netlify.app/report/14264 
OS: `arm64 darwin 21.6.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [/Users/runner/work/prisma-engines/prisma-engines/libs/sql-schema-describer/src/walkers.rs:126:60] called `Result::unwrap()` on an `Err` value: Error("unknown variant `Text`, expected one of `Bit`, `Bool`, `Bytes`, `Char`, `Date`, `Decimal`, `Float4`, `Float8`, `Inet`, `Int2`, `Int4`, `Int8`, `JsonB`, `Oid`, `CatalogSingleChar`, `String`, `Time`, `Timestamp`, `Timestamptz`, `Timetz`, `Uuid`, `VarBit`", line: 0, column: 0)

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

    at handlePanic (/node_modules/prisma/build/index.js:92130:25)
    at ChildProcess.<anonymous> (/node_modules/prisma/build/index.js:92139:15)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

Rust Stacktrace:
```
Starting migration engine RPC server
Connecting to user-provided shadow database.
Attempting best_effort_reset
Connecting to user-provided shadow database.
Attempting best_effort_reset
Attempting best_effort_reset
Analysis run in 417ms
Applying `20220825152323_init`
Connecting to user-provided shadow database.
Attempting best_effort_reset
[/Users/runner/work/prisma-engines/prisma-engines/libs/sql-schema-describer/src/walkers.rs:126:60] called `Result::unwrap()` on an `Err` value: Error("unknown variant `Text`, expected one of `Bit`, `Bool`, `Bytes`, `Char`, `Date`, `Decimal`, `Float4`, `Float8`, `Inet`, `Int2`, `Int4`, `Int8`, `JsonB`, `Oid`, `CatalogSingleChar`, `String`, `Time`, `Timestamp`, `Timestamptz`, `Timetz`, `Uuid`, `VarBit`", line: 0, column: 0)
```

**Comment by tomhoule** [comment]
It's the issue about postgres and cockroachdb native types mixups in sql-schema-describer (there is another one we closed because we thought it was fixed).

**Comment by jkomyno** [comment]
I've tried reproducing this with `prisma@4.2.1` and the Prisma schema provided in https://prisma-errors.netlify.app/report/14264, with no success. Likely, we need some manual SQL migrations in order for this error to arise.

## Commands

Assuming the Prisma schema is in `./prisma/schema.prisma`:

- `rm -rf ./prisma/migrations`
- `pnpx prisma@4.2.1 db push`
- `echo "yes" | pnpx prisma@4.2.1 migrate dev --name init`

Repeat the commands above with the following combinations:
- `postgres` database instance, `postgres` as a `provider` in the schema
- `postgres` database instance, `cockroachdb` as a `provider` in the schema (this will fail with a `You are trying to connect to a PostgreSQL database, but the provider in your Prisma schema is cockroachdb. Please change it to postgresql.` error message)
- `cockroachdb` database instance, `postgres` as a `provider` in the schema
- `cockroachdb` database instance, `cockroachdb` as a `provider` in the schema

**Comment by pimeys** [comment]
I can reproduce this. What you have to do is to have a data model, using `cockroachdb` as the provider:

```prisma
datasource db {
  provider = "cockroachdb"
  url = "postgresql://postgres:prisma@localhost:5432/postgres"
}
```

Now, the url points to PostgreSQL 15 instead of CockroachDB. The easiest way to trigger this is to just `db pull` with the given data model. 4.2.0 fails with the given error, latest main with another one:

```
❯ cargo run --bin test-cli -- introspect --file-path test.prisma
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/test-cli introspect --file-path test.prisma`
reading the prisma schema from test.prisma
2022-12-14T11:35:51.985456Z  INFO quaint::single: Starting a postgresql connection.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', psl/builtin-connectors/src/cockroach_datamodel_connector.rs:151:55
```

Maybe we should detect the wrong provider, and error out earlier? Ping @tomhoule @janpio

**Comment by janpio** [comment]
So `provider=cockroach` but talking to a PostgreSQL 15 and then just `db pull` leads to this problem? Does it need a specific schema in the database? Or any existing local schema file?

**Comment by pimeys** [comment]
It needs types we do not support in the cockroach connector. For example, `TEXT`. It would be nice to give a good error here, but I have no idea how common it is that people do this.

**Comment by jkomyno** [comment]
This is still happening in Prisma `4.8.0`: https://prisma-errors.netlify.app/report/14515
