### ISSUE TITLE
Running generate fails for prisma migrate dev

### ISSUE THREAD

**Issue by fractionalJoe** [prisma/prisma#15047]
### Bug description

I'm new to prisma. When running `prisma migrate dev` it fails on the generate step. I created a repo to replicate the error. https://github.com/fractionalJoe/prisma-migrate-issue

<details>
  <summary>Log Tail</summary>

``` text
...
14099 timing idealTree:node_modules/.pnpm/node_modules/webpack/node_modules/string_decoder/node_modules/safe-buffer Completed in 0ms
14100 timing idealTree:node_modules/ava/node_modules/del/node_modules/globby/node_modules/pify Completed in 0ms
14101 timing idealTree Completed in 85892ms
14102 timing command:install Completed in 85897ms
14103 verbose stack TypeError: Cannot read properties of null (reading 'isDescendantOf')
14103 verbose stack     at Arborist.[resolveLinks] (/home/joe/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1466:37)
14103 verbose stack     at Arborist.[buildDepStep] (/home/joe/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:838:33)
14103 verbose stack     at Arborist.[buildDepStep] (/home/joe/.nvm/versions/node/v16.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1094:31)
14104 verbose cwd /home/joe/repos/test-proj/projects/db/prisma
14105 verbose Linux 5.10.102.1-microsoft-standard-WSL2
14106 verbose node v16.16.0
14107 verbose npm  v8.11.0
14108 error Cannot read properties of null (reading 'isDescendantOf')
14109 verbose exit 1
14110 timing npm Completed in 85945ms
14111 verbose unfinished npm timer reify 1661640664666
14112 verbose unfinished npm timer reify:loadTrees 1661640664669
14113 verbose unfinished npm timer idealTree:buildDeps 1661640664746
14114 verbose code 1
14115 error A complete log of this run can be found in:
14115 error     /home/joe/.npm/_logs/2022-08-27T22_51_04_618Z-debug-0.log
```
</details>

### Expected behavior

Complete without error and generate prisma client

### Prisma information

see https://github.com/fractionalJoe/prisma-migrate-issue

### Environment & setup

- OS: WSL running on Windows 11
- Database: PostgreSQL 14
- Node.js version: v16.16.0

### Prisma Version

```
4.2.1
```

**Comment by fractionalJoe** [comment]
Resolved. I was following this tutorial https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases-typescript-postgres. Turns out I needed to install the Prisma client first. I may have missed it, but I don't think the tutorial mentions this. It may be helpful to add a note to the docs. I'm enjoying the library so far btw, thanks!
