### ISSUE TITLE
Count method with two level join and two column join fails on SqlServer

### ISSUE THREAD

**Issue by michaelaltmann** [prisma/prisma#15178]
### Bug description

Given a three level schema 
Country --< Author --< Post
with two columns joining Author to Post.
If you try to count Posts restricted to a particular country, the generated SQL is invalid for SQL Server

### How to reproduce

See https://github.com/michaelaltmann/prisma_bug_2col_join

Create schema
Country --< Author --< Post
with two columns joining Author to Post.

Try to count Posts for a particular country.
Fails on SqlServer

Generated SQL is
`SELECT COUNT(*) FROM (SELECT [dbo].[Post].[id] FROM [dbo].[Post] WHERE ([dbo].[Post].[id]) IN (SELECT [t0].[id] FROM [dbo].[Post] AS [t0] INNER JOIN [dbo].[Person] AS [j0] ON (([j0].[id] = [t0].[author_id] AND [j0].[country_id] = [t0].[author_country])) WHERE (([j0].[id],[j0].[country_id]) IN (SELECT [t1].[id], [t1].[country_id] FROM [dbo].[Person] AS [t1] INNER JOIN [dbo].[Country] AS [j1] ON (([j1].[id] = [t1].[country_id])) WHERE ([j1].[id] = @P1 AND [t1].[id] IS NOT NULL AND [t1].[country_id] IS NOT NULL)) AND [t0].[id] IS NOT NULL)) /* traceparent=00-00-00-00 */) AS [sub]`

## Error

```
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 4145, state: 1, class: 15, message: "An expression of non-boolean type specified in a context where a condition is expected, near ','.", server: "4f84ff6ad587", procedure: "", line: 1 }) })
```

### Expected behavior

count should return the number of Posts in a given country

### Prisma information

// Schema

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlserver"
  url      = env("DB_URL")
}

model Country {
  id      String   @id
  persons Person[]
}

model Person {
  id         String
  country_id String
  posts      Post[]
  country    Country @relation(fields: [country_id], references: [id])

  @@unique([id, country_id])
}

model Post {
  id             Int    @id @default(autoincrement())
  author_id      String
  author_country String
  author         Person @relation(fields: [author_id, author_country], references: [id, country_id])
}

```

// main.js

```js
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient({ log: ["query", "warn", "error"] })
 await prisma.post.count({ where: { author: { is: { country: { id: "USA" } } } } })

```

### Environment & setup

- OS: macOS
- Database:  SQL Server running in a Docker VM or in Azure
- Node.js: 16.14.2

### Prisma Version

```
4.3.1
```

**Comment by janpio** [comment]
Can confirm:

```
PS C:\Users\Jan\Documents\throwaway\15178> node main.js
Sanity check 1: This works
prisma:query SELECT [dbo].[Post].[id], [dbo].[Post].[author_id], [dbo].[Post].[author_country] FROM [dbo].[Post] WHERE ([dbo].[Post].[author_id] = @P1 AND [dbo].[Post].[author_country] = @P2) /* traceparent=00-00-00-00 */
Sanity check 2: This works
prisma:query SELECT COUNT(*) FROM (SELECT [dbo].[Post].[id] FROM [dbo].[Post] WHERE ([dbo].[Post].[author_id] = @P1 AND [dbo].[Post].[author_country] = @P2) /* traceparent=00-00-00-00 */) AS [sub] /* traceparent=00-00-00-00 */
Sanity check 3: This works
prisma:query SELECT COUNT(*) FROM (SELECT [dbo].[Post].[id] FROM [dbo].[Post] WHERE ([dbo].[Post].[id]) IN (SELECT [t0].[id] FROM [dbo].[Post] AS [t0] INNER JOIN [dbo].[Person] AS [j0] ON (([j0].[id] = [t0].[author_id] AND [j0].[country_id] = [t0].[author_country])) WHERE ([j0].[id] = @P1 AND [j0].[country_id] = @P2 AND [t0].[id] IS NOT NULL)) /* traceparent=00-00-00-00 */) AS [sub] /* traceparent=00-00-00-00 */
Sanity check 4: This works
prisma:query WITH [cte_0] AS (SELECT [t1].[id], [t1].[country_id] FROM [dbo].[Person] AS [t1] INNER JOIN [dbo].[Country] AS [j1] ON (([j1].[id] = [t1].[country_id])) WHERE ([j1].[id] = @P1 AND [t1].[id] IS NOT NULL AND [t1].[country_id] IS NOT NULL)) SELECT [dbo].[Post].[id], [dbo].[Post].[author_id], [dbo].[Post].[author_country] FROM [dbo].[Post] WHERE ([dbo].[Post].[id]) IN (SELECT [t0].[id] FROM [dbo].[Post] AS [t0] INNER JOIN [dbo].[Person] AS [j0] ON (([j0].[id] = [t0].[author_id] AND [j0].[country_id] = [t0].[author_country])) WHERE ([j0].[id] IN (SELECT [id] FROM [cte_0] WHERE [country_id] = [j0].[country_id]) AND [t0].[id] IS NOT NULL)) /* traceparent=00-00-00-00 */
Bug: this fails with SqlServer, but not with SQLite
prisma:error An expression of non-boolean type specified in a context where a condition is expected, near ','.
prisma:query SELECT COUNT(*) FROM (SELECT [dbo].[Post].[id] FROM [dbo].[Post] WHERE ([dbo].[Post].[id]) IN (SELECT [t0].[id] FROM [dbo].[Post] AS [t0] INNER JOIN [dbo].[Person] AS [j0] ON (([j0].[id] = [t0].[author_id] AND [j0].[country_id] = [t0].[author_country])) WHERE (([j0].[id],[j0].[country_id]) IN (SELECT [t1].[id], [t1].[country_id] FROM [dbo].[Person] AS [t1] INNER JOIN [dbo].[Country] AS [j1] ON (([j1].[id] = [t1].[country_id])) WHERE ([j1].[id] = @P1 AND [t1].[id] IS NOT NULL AND [t1].[country_id] IS NOT NULL)) AND [t0].[id] IS NOT NULL)) /* traceparent=00-00-00-00 */) AS [sub] /* traceparent=00-00-00-00 */
C:\Users\Jan\Documents\throwaway\15178\node_modules\@prisma\client\runtime\index.js:29913
      throw new PrismaClientUnknownRequestError(message, this.client._clientVersion);
            ^

PrismaClientUnknownRequestError: 
Invalid `prisma.post.count()` invocation in
C:\Users\Jan\Documents\throwaway\15178\main.js:20:21

  17 await prisma.post.findMany({ where: { author: { is: { country: { id: "USA" } } } } })
  18 
  19 console.log('Bug: this fails with SqlServer, but not with SQLite')
→ 20 await prisma.post.count(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 4145, state: 1, class: 15, message: "An expression of non-boolean type specified in a context where a condition is expected, near ','.", server: "691e20505c5a", procedure: "", line: 1 }) })
    at RequestHandler.handleRequestError (C:\Users\Jan\Documents\throwaway\15178\node_modules\@prisma\client\runtime\index.js:29913:13)
    at RequestHandler.request (C:\Users\Jan\Documents\throwaway\15178\node_modules\@prisma\client\runtime\index.js:29892:12)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\15178\node_modules\@prisma\client\runtime\index.js:30864:16)
    at async main (C:\Users\Jan\Documents\throwaway\15178\main.js:20:3)
    at async C:\Users\Jan\Documents\throwaway\15178\main.js:26:3 {
  clientVersion: '4.3.1'
}
```

**Comment by pimeys** [comment]
Duplicate: https://github.com/prisma/prisma/issues/14037
