### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by michal-kapala** [prisma/prisma#15204]
Hello, I've started getting this Prisma Client error in my test environment without any changes to Prisma/query code.
This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.15.1           | 
| OS              | windows            |
| Prisma Client   | 4.1.0              |
| Query Engine    | 8d8414deb360336e4698a65aa45a1fbaf1ce13d8|
| Database        | sqlite             |

## Logs
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', query-engine\core\src\response_ir\internal.rs:543:81
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Error: 
Invalid `prisma.users.findMany()` invocation:


  called `Option::unwrap()` on a `None` value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

If you want the Prisma team to look into it, please open the link above
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at RequestHandler.handleRequestError (<project_path>\node_modules\@prisma\client\runtime\index.js:28666:13)
    at RequestHandler.request (<project_path>\node_modules\@prisma\client\runtime\index.js:28640:12)
    at async consumer (<project_path>\node_modules\@prisma\client\runtime\index.js:29618:18)
    at async PrismaClient._request (<project_path>\node_modules\@prisma\client\runtime\index.js:29639:16)
    at async GET (<project_path>\src\routes\api\players.js:6:19)
    at async render_endpoint (file:///<project_path>/.svelte-kit/runtime/server/index.js:260:19)
    at async resolve (file:///<project_path>/.svelte-kit/runtime/server/index.js:3452:11)
    at async respond (file:///<project_path>/.svelte-kit/runtime/server/index.js:3389:20)
    at async fetch (file:///<project_path>/.svelte-kit/runtime/server/index.js:2437:17)
    at async load (leaderboard.svelte:5:15)
Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///<project_path>/.svelte-kit/runtime/server/index.js:2556:21)
    at async load (leaderboard.svelte:6:21)
    at async load_node (file:///<project_path>/.svelte-kit/runtime/server/index.js:2582:22)
    at async respond$1 (file:///<project_path>/.svelte-kit/runtime/server/index.js:2983:15)
    at async resolve (file:///<project_path>/.svelte-kit/runtime/server/index.js:3453:11)
    at async respond (file:///<project_path>/.svelte-kit/runtime/server/index.js:3389:20)
    at async file:///<project_path>/node_modules/@sveltejs/kit/dist/vite.js:2382:22
```

## Client Snippet

The code below is of a SvelteKit endpoint.

```js
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

export async function GET() {
    var players = await prisma.users.findMany({
        orderBy: {
            stats: {ranking: 'desc'}
        },
        include: {
            stats: {
                select: {
                    ranking: true,
                    law_victories: true,
                    crim_victories: true,
                    law_defeats: true,
                    crim_defeats: true,
                    law_time: true,
                    crim_time: true,
                }
            },
            friends: false
        }
    });
    
    return {
        status: 200,
        body: players,
    }
}
```

## Schema
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

// 'users' SQLite model
model users {
  id            Int      @id @unique
  pid           Int      @unique
  username      String   @unique
  country       String?
  birthday_date Int?
  clan_tag      String?
  stats         stats?
  friends       friends[]
}

// 'friends' SQLite model
model friends {
  id         Int      @id @unique
  user       users    @relation(fields: [friend_of], references: [pid])
  friend_of  Int
  pid        Int
  name       String
  details    Int
  clan_abbr  String
  wanna_play Int
}

// 'message' SQLite model
model message {
  msg String @unique
}

// 'stats' SQLite model
model stats {
  id                   Int    @id @unique
  user                 users  @relation(fields: [pid], references: [pid])
  pid                  Int    @unique
  ranking              Int?
  law_victories        Int?
  law_defeats          Int?
  law_draws            Int?
  crim_victories       Int?
  crim_defeats         Int?
  crim_draws           Int?
  law_kills            Int?
  crim_kills           Int?
  law_deaths           Int?
  crim_deaths          Int?
  law_suicides         Int?
  crim_suicides        Int?
  law_headshots        Int?
  crim_headshots       Int?
  stat16               Int?
  stat17               Int?
  stat18               Int?
  stat19               Int?
  law_hostages_killed  Int?
  crim_hostages_killed Int?
  law_apprehensions    Int?
  crim_apprehended     Int?
  law_shots_fired      Int?
  crim_shots_fired     Int?
  law_shots_hit        Int?
  crim_shots_hit       Int?
  law_time             Int?
  crim_time            Int?
}
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by janpio** [comment]
Did the same query work with the same data before?
If the data changed: Can you maybe share the data that would be returned here with us?

**Comment by michal-kapala** [comment]
> Did the same query work with the same data before? If the data changed: Can you maybe share the data that would be returned here with us?

Yes, thanks for drawing my attention to that, I've just solved it.
I've got new `user` records `birthday_date` SQLite field values ( saved in scientific notation, e.g. `1.84467440724388e+19`, just a parsing bug), which was the root cause for this. After a correction everything is back to normal.
Thanks for help and sorry for trouble, i forgot to check the data.

**Comment by janpio** [comment]
No, thank you for actually letting us know. Although this is invalid data, we should probably try to fail in a better way with a more helpful error message I would say.

I assume because this is SQLite it let you write whatever into the `Int` field instead?

**Comment by michal-kapala** [comment]
The date format is special, it's not a regular timestamp but a number created using bitwise shifting, sometimes it's a random memory dump (old games have their charms). It's an [SQLite INTEGER](https://www.sqlite.org/datatype3.html) so I would guess that is how large 64-bit values are saved here, I don't have much experience working with those though.

**Comment by pimeys** [comment]
Super small reproduction (still has that ugly error in 4.3.1):

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model a {
  id           Int  @id
  birthdayDate Int?
}
```

```typescript
import { PrismaClient, Prisma } from '@prisma/client'

const prisma = new PrismaClient({
  log: ['query', 'info', 'warn', 'error']
})

async function main() {
  const data = await prisma.a.findMany();

  console.log(data);
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```

Before executing the script, insert a broken item to the table:

```sql
insert into "a" ("birthdayDate") values (1.84467440724388e+19);
```

Debug logs:

```
  prisma:tryLoadEnv  Environment variables loaded from /prisma-15204/.env +0ms
  prisma:tryLoadEnv  Environment variables loaded from /prisma-15204/.env +2ms
  prisma:client  dirname /prisma-15204/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /prisma-15204/prisma +0ms
  prisma:client  clientVersion 4.3.1 +0ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /prisma-15204/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /prisma-15204/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node +0ms
  prisma:client  Prisma Client call: +47ms
  prisma:client  prisma.a.findMany(undefined) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findManya {
    id
    birthdayDate
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +47ms
  prisma:client:libraryEngine  library starting +0ms
prisma:info Starting a sqlite pool with 33 connections.
  prisma:client:libraryEngine  library started +1ms
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', query-engine/core/src/response_ir/internal.rs:543:81
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
prisma:query SELECT `main`.`a`.`id`, `main`.`a`.`birthdayDate` FROM `main`.`a` WHERE 1=1 LIMIT ? OFFSET ? /* traceparent=00-00-00-00 */
  prisma:client:request_handler  PrismaClientRustPanicError: called `Option::unwrap()` on a `None` value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v18.8.0++++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-1.1.x%7C%0A%7C+Prisma+Client+++%7C+4.3.1++++++++++++++%7C%0A%7C+Query+Engine++++%7C+c875e43600dfe042452e0b868f7a48b817b9640b%7C%0A%7C+Database++++++++%7C+sqlite+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aprisma%3AtryLoadEnv+Environment+variables+loaded+from+%2Fprisma-15204%2F.env%0Aprisma%3AtryLoadEnv+Environment+variables+loaded+from+%2Fprisma-15204%2F.env%0Aprisma%3Aclient+dirname+%2Fprisma-15204%2Fnode_modules%2F.prisma%2Fclient%0Aprisma%3Aclient+relativePath+..%2F..%2F..%2Fprisma%0Aprisma%3Aclient+cwd+%2Fprisma-15204%2Fprisma%0Aprisma%3Aclient+clientVersion+4.3.1%0Aprisma%3Aclient+clientEngineType+library%0Aprisma%3Aclient%3AlibraryEngine+internalSetup%0Aprisma%3Aclient%3AlibraryEngine%3Aloader+Searching+for+Query+Engine+Library+in+%2Fprisma-15204%2Fnode_modules%2F.prisma%2Fclient%0Aprisma%3Aclient%3AlibraryEngine%3Aloader+loadEngine+using+%2Fprisma-15204%2Fnode_modules%2F.prisma%2Fclient%2Flibquery_engine-debian-openssl-1.1.x.so.node%0Aprisma%3Aclient+Prisma+Client+call%3A%0Aprisma%3Aclient+prisma.a.findMany%28undefined%29%0Aprisma%3Aclient+Generated+request%3A%0Aprisma%3Aclient+query+%7B%0A++findManya+%7B%0A++++id%0A++++birthdayDate%0A++%7D%0A%7D%0A%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+false%0Aprisma%3Aclient%3AlibraryEngine+library+starting%0Aprisma%3Aclient%3AlibraryEngine+library+started%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=called+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at LibraryEngine.buildQueryError (/prisma-15204/node_modules/@prisma/client/runtime/index.js:26358:14)
    at LibraryEngine.request (/prisma-15204/node_modules/@prisma/client/runtime/index.js:26297:22)
    at async RequestHandler.request (/prisma-15204/node_modules/@prisma/client/runtime/index.js:29873:24)
    at async PrismaClient._request (/prisma-15204/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async main (/prisma-15204/script.ts:8:16) {
  clientVersion: '4.3.1'
} +0ms
PrismaClientRustPanicError: 
Invalid `prisma.a.findMany()` invocation in
/prisma-15204/script.ts:8:31

  5 })
  6 
  7 async function main() {
→ 8   const data = await prisma.a.findMany(
called `Option::unwrap()` on a `None` value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v18.8.0++++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-1.1.x%7C%0A%7C+Prisma+Client+++%7C+4.3.1++++++++++++++%7C%0A%7C+Query+Engine++++%7C+c875e43600dfe042452e0b868f7a48b817b9640b%7C%0A%7C+Database++++++++%7C+sqlite+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aprisma%3AtryLoadEnv+Environment+variables+loaded+from+%2Fprisma-15204%2F.env%0Aprisma%3AtryLoadEnv+Environment+variables+loaded+from+%2Fprisma-15204%2F.env%0Aprisma%3Aclient+dirname+%2Fprisma-15204%2Fnode_modules%2F.prisma%2Fclient%0Aprisma%3Aclient+relativePath+..%2F..%2F..%2Fprisma%0Aprisma%3Aclient+cwd+%2Fprisma-15204%2Fprisma%0Aprisma%3Aclient+clientVersion+4.3.1%0Aprisma%3Aclient+clientEngineType+library%0Aprisma%3Aclient%3AlibraryEngine+internalSetup%0Aprisma%3Aclient%3AlibraryEngine%3Aloader+Searching+for+Query+Engine+Library+in+%2Fprisma-15204%2Fnode_modules%2F.prisma%2Fclient%0Aprisma%3Aclient%3AlibraryEngine%3Aloader+loadEngine+using+%2Fprisma-15204%2Fnode_modules%2F.prisma%2Fclient%2Flibquery_engine-debian-openssl-1.1.x.so.node%0Aprisma%3Aclient+Prisma+Client+call%3A%0Aprisma%3Aclient+prisma.a.findMany%28undefined%29%0Aprisma%3Aclient+Generated+request%3A%0Aprisma%3Aclient+query+%7B%0A++findManya+%7B%0A++++id%0A++++birthdayDate%0A++%7D%0A%7D%0A%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+false%0Aprisma%3Aclient%3AlibraryEngine+library+starting%0Aprisma%3Aclient%3AlibraryEngine+library+started%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=called+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at RequestHandler.handleRequestError (/prisma-15204/node_modules/@prisma/client/runtime/index.js:29917:13)
    at RequestHandler.request (/prisma-15204/node_modules/@prisma/client/runtime/index.js:29892:12)
    at async PrismaClient._request (/prisma-15204/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async main (/prisma-15204/script.ts:8:16) {
  clientVersion: '4.3.1'
}
  prisma:client:libraryEngine  library stopping +25ms
  prisma:client:libraryEngine  library stopped +1ms
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms
```
