### ISSUE TITLE
Raw bulk insert failing

### ISSUE THREAD

**Issue by sebpowell** [prisma/prisma#15205]
### Bug description

I'm attempting to do a bulk raw insert. This is to avoid having to loop through every record, as this has performance implications. I need the IDs from the initial bulk insert as I then need to update other tables, and as per what's discussed here, `createMany` does not return the inserted rows.

I have spoken to a Prisma Engineer about this, and have attempted to use the code he supplied me with (which, he says, was working for him). 

See: https://github.com/prisma/prisma/issues/8131#issuecomment-1237992626

### How to reproduce

I am running the following code, in Nest.js:

```
const rows = [{ status: 's' }, { status: 'x' }];

const values = rows.map((row) => Prisma.sql`(${row.status})`);

await this.prismaService
  .$queryRaw`INSERT INTO "test" (status) VALUES ${Prisma.join(
  values,
)} RETURNING *`;
```

When I run the above, I get the following error back:

```
prisma:query SELECT 1
prisma:query INSERT INTO "test" (status) VALUES $1 RETURNING *
[Nest] 43379  - 06/09/2022, 13:12:24   ERROR [ExceptionsHandler] 
Invalid `prisma.$queryRaw()` invocation:


  Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "$1"`
Error: 
Invalid `prisma.$queryRaw()` invocation:


  Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "$1"`
```

### Prisma information

```prisma
model test {
  id     Int     @id @default(autoincrement())
  status String? @db.VarChar
}
```

### Environment & setup

- OS: macOS
- Database: Postgres
- Node.js version: 16.13.1

### Prisma Version

4.3.1

**Comment by janpio** [comment]
Who did you talk to? Knowing that would allow us to skip the "reproduce with no knowledge" step.

**Comment by pantharshit00** [comment]
That was me. I wasn't able to locally reproduce the problem though. https://prisma.slack.com/archives/CA491RJH0/p1662461878343699

**Comment by janpio** [comment]
Internal:
The code above worked for Harshit.
It did not work for the user.
Next step: Reproduce if the code actually works locally.

**Comment by Noitidart** [comment]
I'm having the same issue. I had to move to `queryRawUnsafe`.

this is my code that fails

```
prisma.$queryRaw`INSERT INTO "l_intent" ("english") VALUES ${Prisma.join(
          missingResourceIntentEnglishes.map(english => `($E$${english}$E$)`)
        )} RETURNING *`
```

the error is:

```
error - PrismaClientKnownRequestError: 
Invalid `prisma.$queryRaw()` invocation:


  Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "$1"`
    at Object.request (/Users/noitidart/Documents/The-App/web/node_modules/@prisma/client/runtime/index.js:45405:15)
    at async Proxy._request (/Users/noitidart/Documents/The-App/web/node_modules/@prisma/client/runtime/index.js:46301:18) {
  code: 'P2010',
  clientVersion: '3.14.0',
  meta: {
    code: '42601',
    message: 'db error: ERROR: syntax error at or near "$1"'
  },
  page: '/api/v1/l/admin/projects/upload'
}
```


It's interesting because if I run this code it works just fine:

```
prisma.$queryRaw`INSERT INTO "l_intent" ("english") VALUES ($E$don't do it$E$),($E$build with spaces$E$) RETURNING *`
```

**Comment by SevInf** [comment]
I manage to reproduce some variant of this [here](https://github.com/prisma/reproductions/tree/main/gh-15205).

It looks to me like this is the same problem as reported [in this issue](https://github.com/prisma/prisma/issues/11454#issuecomment-1240997649). I suspect that you have multiple instances of Prisma client generated, `Prisma.join` comes from one of them and `prisma.$queryRaw` from the other, so `instanceof` check within sql-template-tag does not work.  @sebpowell @Noitidart could check if that's true?

**Comment by Noitidart** [comment]
Thanks @SevInf! Clicking on that link takes me to a broken page here - https://github.com/prisma/reproductions/tree/main/gh-15205

I am using Vercel/Next.js so it is serverless. And this issue I haven't yet tested in production. But I import `prisma` from a file that looks like this snippet below. We do see that it tries to set `global.prisma` if its not yet set. I got this from the Vercel/Next.js tutorial here - https://vercel.com/guides/nextjs-prisma-postgres#step-3.-install-and-generate-prisma-client

```
import { PrismaClient } from '@prisma/client';
import { Hub } from '@sentry/hub';
import * as Sentry from '@sentry/nextjs';
import { isThenable } from '@sentry/utils';

let prisma: PrismaClient;
let DID_SETUP_SENTRY = false;

if (process.env.NODE_ENV === 'production') {
  prisma = new PrismaClient();

  tracePrismaWithSentry(prisma, Sentry.getCurrentHub);
} else {
  // @ts-ignore: dev only
  if (!global.prisma) {
    // @ts-ignore: dev only
    global.prisma = new PrismaClient();

    tracePrismaWithSentry(
      // @ts-ignore: dev only
      global.prisma,
      Sentry.getCurrentHub
    );
  }
  // @ts-ignore: dev only
  prisma = global.prisma;
}

/**
 * This is stolen directly from here -
 * https://github.com/getsentry/sentry-javascript/pull/4931/files#diff-1299d6ad2dcb1bc219acbc53ed90550ab15c6240e54efd6bd007692864ddcd3fR78-R79
 * I only added in the `data` property which has the `runInTransaction` and
 * `args` properties. I also add a breadcrumb of this, in case the query fails,
 * the span won't be logged.
 */
function tracePrismaWithSentry(client: PrismaClient, getCurrentHub: () => Hub) {
  if (DID_SETUP_SENTRY) {
    return;
  } else {
    DID_SETUP_SENTRY = true;
  }

  client.$use((params, next) => {
    const scope = getCurrentHub().getScope();
    const parentSpan = scope?.getSpan();

    const action = params.action;
    const model = params.model;

    const description = model ? `${model} ${action}` : action;
    const data = {
      runInTransaction: params.runInTransaction,
      args: params.args
    };

    const span = parentSpan?.startChild({
      description,
      op: 'db.prisma',
      // Add data to the span so it's shown when span finishes.
      data
    });

    // Add a breadcrumb on query start, in case span doesn't finish (due to
    // permdission denied by database for instance), then the data is available
    // as a breadcrumb.
    scope?.addBreadcrumb({
      type: 'query',
      category: 'prisma.started',
      level: 'info',
      message: description,
      data
    });

    const rv = next(params);

    if (isThenable(rv)) {
      return rv.then((res: unknown) => {
        span?.finish();
        return res;
      });
    }

    span?.finish();
    return rv;
  });
}

export default prisma;
```

**Comment by SevInf** [comment]
@Noitidart thank you! Here is a snippet from my reproduction:

```
const { PrismaClient } = require('.prisma/client')

delete require.cache[require.resolve('.prisma/client')]
delete require.cache[require.resolve('.prisma/client/runtime')]

const { Prisma } = require('.prisma/client')

async function main() {
  const prisma = new PrismaClient()

  const rows = [{ status: 's' }, { status: 'x' }]
  const values = rows.map((row) => Prisma.sql`(${row.status})`)

  await prisma.$queryRaw`INSERT INTO "test" (status) VALUES ${Prisma.join(values)} RETURNING *`
}


```

Removing `cache` entry is there just to emulate client being loaded from different places.

Regarding your code, could you please do the following:

1. `console.log(require.resolve('@prisma/client'))` in the module you've just posted, the one that sets up Prisma instance
2. `console.log(require.resolve('@prisma/client'))` in the module that executes failing `$queryRaw`
3. See if they point to the same path

**Comment by Noitidart** [comment]
Thanks @SevInf! Sorry for late test, I had to set up the environment and stuff.

It's logging the same path but this was fresh `npm run dev` and first call, I'll keep testing cuz I think it makes sense, because I store it in `global.prisma` and eventually maybe much later, it changes.

Anyways first run values:

```
prisma.ts: @prisma/client
upload.ts: @prisma/client
```

**Comment by Noitidart** [comment]
Still same path so far :(

**Comment by Noitidart** [comment]
I uncommented by `queryRaw` and its giving me this error, I think I forgot how to use queryRaw lol:


```
prisma.$queryRaw`INSERT INTO "l_intent" ("english") VALUES ${Prisma.join(
          missingResourceIntentEnglishes.map(english => `($E$${english}$E$)`)
        )} RETURNING *`
```


This is the queryRawUnsafe that works:

```
prisma.$queryRawUnsafe<Array<Pick<TLIntent, 'id' | 'english'>>>(
          `INSERT INTO "LIntent" ("english") VALUES ${missingResourceIntentEnglishes
            .map(english => `($E$${english}$E$)`)
            .join(', ')} RETURNING *`
```

Does anything look wrong with that queryRaw?

Thanks again for your attention on this issue!

**Comment by SevInf** [comment]
@Noitidart i think there is a syntax error in your raw query, just noticed it: round brackets around values are missing. I think you've meant to do:

```ts
prisma.$queryRaw`INSERT INTO "l_intent" ("english") VALUES (${Prisma.join(
          missingResourceIntentEnglishes.map(english => `$E$${english}$E$`)
        }) RETURNING *`
```

`$queryRaw` does not construct a plain string, but prepared sql statement, automatically escaping the values. So in your original query, round brackets are part of the column value, not the query itself.

Looking further into your query, i think it will only work if `missingResourceIntentEnglishes` has exactly one item. If that's intended, you can probably do it without raw queries at all:

```ts
prisma.LIntent.create({
    data: {
       english: `$E$${missingResourceIntentEnglishes[0]}$E$`
    }
})
```

**Comment by Noitidart** [comment]
Oh thanks I'll give that a try on by Monday please!

The reason I was using `rawQuery` was to insert and return at once. The `RETURNING *` part. Postgres has this awesome support.

**Comment by Noitidart** [comment]
Hey hey, thanks again, sorry for the wait. So I added the parents: so my query now looks like this:

```
        prisma.$queryRaw<
          Array<Pick<TLIntent, 'id' | 'english'>>
        >`INSERT INTO "LIntent" ("english") VALUES (${Prisma.join(
          missingResourceIntentEnglishes.map(english => `($E$${english}$E$)`)
        )}) RETURNING *`,
```

Now the error I get is:

```
INSERT INTO "LIntent" ("english") VALUES ($1,$2,$3) RETURNING *
2022-10-24T18:54:28.040749500Z 2022-10-24 18:54:28.040 UTC [21949] ERROR:  INSERT has more expressions than target columns at character 46
```

The logs on path is same too:

```
prisma.ts: @prisma/client
upload.ts: @prisma/client
```

**Comment by Noitidart** [comment]
Just a gentle bump, if you notice anything silly/obvious in my last post.

**Comment by Jolg42** [comment]
Note: we could update our dependency and expose `bulk` https://github.com/prisma/prisma/pull/20977

It would look like this:

>Accepts an array of arrays, and returns the SQL with the values joined together in a format useful for bulk inserts.
```js
const query = `INSERT INTO users (name) VALUES ${bulk([
  ["Blake"],
  ["Bob"],
  ["Joe"],
])}`;

query.sql; //=> "INSERT INTO users (name) VALUES (?),(?),(?)"
query.values; //=> ["Blake", "Bob", "Joe"]
```
