### ISSUE TITLE
Ms

### ISSUE THREAD

**Issue by CapitaineToinon** [prisma/prisma#15305]
### Bug description

[discussions/15291](https://github.com/prisma/prisma/discussions/15291)

It seems like it isn't possible to use prisma's `$executeRaw`'s function to set SqlServer's `IDENTITY_INSERT` value in order to allows explicit values to be inserted into the identity column of a table.

cf: [SET IDENTITY_INSERT (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-identity-insert-transact-sql?view=sql-server-ver16)

Context: in order to do some e2e testing with cypress using a dotnet backend using SqlServer, I need to have my database populated with data. Because the backend is hosted on AWS and isn't aware of when the tests are happening (and because dotnet entity framework seeding options are frankly dog shit), I'm trying to use prisma instead to populate a database I have full control over with mock data before the cypress tests are fired.

However, in order to be able to insert data with hard coded ids for easiest testing, I need to set the `IDENTITY_INSERT` property to ON on each relevant table before inserting any data.

### How to reproduce

I'm trying to insert into the databse entities with hard coded ids for testing purposes. In SqlServer, in order to do that, you need first to set the IDENTITY_INSERT value for the specific table you want to insert data into to ON. 

I've tried: 
```js
await prisma.$executeRaw`SET IDENTITY_INSERT Customer ON`;
await prisma.customer.create({
  data: { id: 5 /* ... other data here */ },
});
await prisma.$executeRaw`SET IDENTITY_INSERT Customer OFF`;
```

and also
```js
await prisma.$transaction([
  prisma.$executeRaw`SET IDENTITY_INSERT Customer ON`,
  prisma.customer.create({
    data: { id: 5 /* ... other data here */ },
  }),
  prisma.$executeRaw`SET IDENTITY_INSERT Customer OFF`,
]);
```

### Expected behavior

The data should be inserted to the database. 

However prisma is throwing me the following error instead.

```
Error: 
Invalid `prisma.$executeRaw()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 544, state: 1, class: 16, message: "Cannot insert explicit value for identity column in table 'Customer' when IDENTITY_INSERT is set to OFF.", server: "a6d5592dc4ee", procedure: "", line: 1 }) })
    at RequestHandler.handleRequestError (/Users/antoine/Documents/www/karpeo/frontend/node_modules/@prisma/client/runtime/index.js:29913:13)
    at RequestHandler.request (/Users/antoine/Documents/www/karpeo/frontend/node_modules/@prisma/client/runtime/index.js:29892:12)
    at async Proxy._request (/Users/antoine/Documents/www/karpeo/frontend/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async Promise.all (index 0)
    at async Object.handler (/Users/antoine/Documents/www/karpeo/frontend/cypress.config.localhost.js:76:9)
```

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "sqlserver"
  url = env("DATABASE_URL")
}

// some other models not relevant

model Customer {
  id Int @id(map: "PK_Customer") @default(autoincrement())
  // some other fields not relevant
}
```

```ts

// tried this
await prisma.$executeRaw`SET IDENTITY_INSERT Customer ON`;
await prisma.customer.create({
  data: { id: 5 /* ... other data here */ },
});
await prisma.$executeRaw`SET IDENTITY_INSERT Customer OFF`;

// also tried this
await prisma.$transaction([
  prisma.$executeRaw`SET IDENTITY_INSERT Customer ON`,
  prisma.customer.create({
    data: { id: 5 /* ... other data here */ },
  }),
  prisma.$executeRaw`SET IDENTITY_INSERT Customer OFF`,
]);
```

### Environment & setup

- OS: macOS
- Database: SQL Server
- Node.js version: v16.13.2

### Prisma Version

```
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
```

**Comment by janpio** [comment]
If at all, this would only be expected inside an explicit transaction as you tried in your second code example. Without that, in theory each query could be executed on a different connection. 

Is there maybe a query you could run to _read_ the current status of this setting after the first query that should set it?

**Comment by CapitaineToinon** [comment]
I don't think there is a query to get the value directly. However, because `IDENTITY_INSERT` cannot be active on two tables at once, it will throw an error if you try to do so anyway have tell you which table it is active on and thus "reading" the value. 

So for example doing this:

```sql
SET IDENTITY_INSERT Customer ON
SET IDENTITY_INSERT Activity ON
```

gives this error:

```
IDENTITY_INSERT is already ON for table 'cypress.dbo.Customer'. Cannot perform SET operation for table 'Activity'.
```

But trying this with prisma

```js
await prisma.$transaction([
  prisma.$executeRaw`SET IDENTITY_INSERT Customer ON`,
  prisma.$executeRaw`SET IDENTITY_INSERT Activity ON`,
]);
```

shows me it generates the following sql (which seems correct)

```
prisma:query BEGIN TRAN
prisma:query SET IDENTITY_INSERT Customer ON
prisma:query SET IDENTITY_INSERT Activity ON
prisma:query COMMIT
```

But no error is thrown, which shows either the SET query are ignored or each SET is executed in a different session than the other.

**Comment by janpio** [comment]
Thanks for that context. Something for us to investigate then.

**Comment by millsp** [comment]
Reproduction https://github.com/prisma/prisma/pull/15933

**Comment by thecrazyrussian** [comment]
Not sure if this is helpful, I was able to recreate the error using:
```
await prisma.$transaction([
  prisma.$executeRaw`SET IDENTITY_INSERT ClientType ON`,
   prisma.$executeRaw`
   INSERT INTO ClientType (id, name) VALUES (1,'Name')`, 
])}
```
However, the following seems to work:
```
await prisma.$transaction([
  prisma.$executeRaw`SET IDENTITY_INSERT ClientType ON;
  INSERT INTO ClientType (id, name) VALUES (1,'Name')`, 
])}
```
Schema:
```
model ClientType {
  id     Int                @id @default(autoincrement())
  name   String             @db.VarChar(100)
}
```

Leading me to think that the issue is validation happening on a per-query basis, ignoring the fact it is in a transaction.

**Comment by peterhirn** [comment]
This behavior makes seeding mssql tables very annoying. I'm currently using this hacky workaround:

```js
const users = [
  [1, "Bob", "foo"],
  [2, "Alice", "bar"]
]

const seedUsers = async (prisma) => {
  const raw = `
    SET IDENTITY_INSERT [user] ON
    ${users
      .map(
        ([id, name, password]) => `
          IF NOT EXISTS (SELECT id FROM [user] WHERE id = ${id})
          BEGIN
            INSERT [user]
              ([id], [name], [password])
            VALUES (${id}, N'${name}', N'${password}')
          END`
      )
      .join("\n")}
    SET IDENTITY_INSERT [user] OFF
  `

  await prisma.$executeRawUnsafe(raw)
}
```

**Comment by janpio** [comment]
Potential hunch to investigate: Is `SET IDENTITY_INSERT` expected to work inside a transaction, before the transaction is committed? Otherwise use case might depend on https://github.com/prisma/prisma/issues/5128 being implemented first, which will guarantee execution of commands on the same connection but without the wrapping transaction.

**Comment by raix** [comment]
The `SET IDENTITY_INSERT` works inside / outside transactions _(likely not across connections)_

When testing this, Prisma seems to use the correct query _(accordingly to logs)_ - when executing the query manually it works, not sure what side effects causing this issue in the Prisma client.

For now, since I only depend on this feature for seeding data I've workaround using an extension only used when migrating.

If anyone finds it useful:

```TypeScript
export function forMigration() {
  return Prisma.defineExtension((prisma) =>
    prisma.$extends({
      query: {
        $allModels: {
          async $allOperations({ model, args, query, operation }) {
            if (
              operation !== "create" ||
              typeof args.data !== "object" ||
              getId(args.data) == null
            ) {
              return query(args);
            }

            const keys = Object.keys(args.data).join(", ");
            const values = Object.values(args.data)
              .map((value) =>
                typeof value === "string" ? `'${value}'` : value
              )
              .join(", ");

            return await prisma.$executeRawUnsafe(`
            SET IDENTITY_INSERT ${model} ON;
            DELETE FROM ${model} WHERE ID = ${getId(args.data)};
            INSERT INTO ${model} (${keys}) VALUES (${values});
            SET IDENTITY_INSERT ${model} OFF;
            `);
          }
        }
      }
    })
  );
}
```

**Comment by chriseaton** [comment]
Oh god this is over 3 years old and I just ran into it. I'm doomed ☠️
