### ISSUE TITLE
Prisma throws error on enabling logging

### ISSUE THREAD

**Issue by prithvihv** [prisma/prisma#15309]
### Bug description

Unable to start the application when logs are enabled. Crashes on start with the following error message:

```js
{"level":30,"time":1663116069562,"pid":2825049,"hostname":"nyx","context":"RouterExplorer","msg":"Mapped {/, GET} route"}
{"level":30,"time":1663116069564,"pid":2825049,"hostname":"nyx","context":"RouterExplorer","msg":"Mapped {/how, GET} route"}
{"level":30,"time":1663116069564,"pid":2825049,"hostname":"nyx","context":"RoutesResolver","msg":"PartnerController {/partner} (version: 1):"}
{"level":30,"time":1663116069565,"pid":2825049,"hostname":"nyx","context":"RoutesResolver","msg":"PropertyController {/property} (version: 1):"}
{"level":30,"time":1663116069565,"pid":2825049,"hostname":"nyx","context":"RouterExplorer","msg":"Mapped {/property, GET} (version: 1) route"}
  prisma:client:libraryEngine:loader  loadEngine using /nix/store/z6b2myc9bhgb94d3140hzww50d5y1csf-prisma-engines-4.2.1/lib/libquery_engine.node +0ms
  prisma:client:libraryEngine  library starting +82ms

/home/phv/code/src/github.com/gamezop/partner-service/prisma/generated/gamezop-read/runtime/index.js:25389
      throw new PrismaClientUnknownRequestError(`Response from the Engine was empty`, this.config.clientVersion);
            ^
Error: Response from the Engine was empty
    at LibraryEngine.parseEngineResponse (/home/phv/code/src/github.com/gamezop/partner-service/prisma/generated/gamezop-read/runtime/index.js:25389:13)
    at LibraryEngine.logger (/home/phv/code/src/github.com/gamezop/partner-service/prisma/generated/gamezop-read/runtime/index.js:25440:24)
    at /home/phv/code/src/github.com/gamezop/partner-service/prisma/generated/gamezop-read/runtime/index.js:25424:59
```

### How to reproduce

1. Install nestjs, prisma 
2. enable logs

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  output = "./generated/gamezop-read"
}

datasource gamezopRead {
  provider = "postgresql"
  url      = env("POSTGRESQL_GAMEZOP_READ_URL")
}

....
```

// not working version
```ts
import { Injectable, OnModuleInit, INestApplication } from '@nestjs/common';
import { PrismaClient, Prisma } from '../prisma/generated/gamezop-read';

@Injectable()
export class GzpReadPrismaService
  extends PrismaClient<Prisma.PrismaClientOptions, 'info' | 'query'>
  implements OnModuleInit
{
  constructor() {
    // super();
    super({
      log: ['info', 'query'],
    });
  }

  async onModuleInit() {
    await this.$connect();
  }

  async enableShutdownHooks(app: INestApplication) {
    this.$on('beforeExit', async () => {
      await app.close();
    });
  }
}
```

// working version 
```ts
import { Injectable, OnModuleInit, INestApplication } from '@nestjs/common';
import { PrismaClient, Prisma } from '../prisma/generated/gamezop-read';

@Injectable()
export class GzpReadPrismaService
  extends PrismaClient<Prisma.PrismaClientOptions, 'info' | 'query'>
  implements OnModuleInit
{
  constructor() {
    super();
  }

  async onModuleInit() {
    await this.$connect();
  }

  async enableShutdownHooks(app: INestApplication) {
    this.$on('beforeExit', async () => {
      await app.close();
    });
  }
}
```

### Environment & setup

- OS: NixOS
- Database:PostgreSQL
- Node.js version: v16.15.0
- prisma: 4.2.1: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/database/prisma-engines/default.nix

### Prisma Version

```
prisma                  : 4.3.1
@prisma/client          : 4.2.1
Current platform        : linux-nixos
Query Engine (Node-API) : libquery-engine  (at ../../../../../../../nix/store/z6b2myc9bhgb94d3140hzww50d5y1csf-prisma-engines-4.2.1/lib/libquery_engine.node, resolved by PRISMA_QUERY_ENGINE_LIBRARY)
Migration Engine        : migration-engine-cli  (at ../../../../../../../nix/store/z6b2myc9bhgb94d3140hzww50d5y1csf-prisma-engines-4.2.1/bin/migration-engine, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine    : introspection-core  (at ../../../../../../../nix/store/z6b2myc9bhgb94d3140hzww50d5y1csf-prisma-engines-4.2.1/bin/introspection-engine, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary           : prisma-fmt  (at ../../../../../../../nix/store/z6b2myc9bhgb94d3140hzww50d5y1csf-prisma-engines-4.2.1/bin/prisma-fmt, resolved by PRISMA_FMT_BINARY)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
```

**Comment by janpio** [comment]
@prithvihv Do you maybe have a non Nix-OS machine/VM handy where you can try to run the same project? I would be interested if you get the same problem/error there.

**Comment by diamondburned** [comment]
I can confirm that this also happens to me with Prisma v4.2.1 on NixOS.

Relevant code:

```ts
export const client = new prisma.PrismaClient({
  // crashes if the following line is uncommented:
  // log: ["query"],
});
```

<details>
<summary>Console output with <code>export DEBUG='*'</code>:</summary>

```
  prisma:tryLoadEnv  Environment variables not found at null +0ms
  prisma:tryLoadEnv  Environment variables not found at undefined +1ms
  prisma:tryLoadEnv  No Environment variables loaded +0ms
  prisma:tryLoadEnv  Environment variables not found at null +6ms
  prisma:tryLoadEnv  Environment variables not found at undefined +0ms
  prisma:tryLoadEnv  No Environment variables loaded +0ms
  prisma:client  dirname /home/diamond/Scripts/chatter/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../src/lib/db +0ms
  prisma:client  cwd /home/diamond/Scripts/chatter/src/lib/db +0ms
  prisma:client  clientVersion 4.2.1 +1ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  loadEngine using /nix/store/918kir4dsxfry3d0975pryna285mkkiy-prisma-engines-4.2.1/lib/libquery_engine.node +0ms
  prisma:client:libraryEngine  library starting +101ms
  prisma:client:libraryEngine  library started +266ms
  prisma:client  Prisma Client call: +418ms
  prisma:client  prisma.asset.findMany(undefined) +1ms
  prisma:client  Generated request: +1ms
  prisma:client  query {
  findManyAsset {
    hash
    name
    data
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +53ms
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms
/home/diamond/Scripts/chatter/node_modules/@prisma/client/runtime/index.js:25389
      throw new PrismaClientUnknownRequestError(`Response from the Engine was empty`, this.config.clientVersion);
            ^
PrismaClientUnknownRequestError: Response from the Engine was empty
    at LibraryEngine.parseEngineResponse (/home/diamond/Scripts/chatter/node_modules/@prisma/client/runtime/index.js:25389:13)
    at LibraryEngine.logger (/home/diamond/Scripts/chatter/node_modules/@prisma/client/runtime/index.js:25440:24)
    at /home/diamond/Scripts/chatter/node_modules/@prisma/client/runtime/index.js:25424:59 {
  clientVersion: '4.2.1'
}
```

</details>

I unfortunately do not have a non-NixOS machine to reproduce this error on. All of my development is done on this distro.
