### ISSUE TITLE
When prisma create record I get an error which depends prisma generate

### ISSUE THREAD

**Issue by victor-dm-black** [prisma/prisma#15367]
### Bug description

```
Unknown arg `userId` in data.userId for type BotUsersCreateInput. Did you mean `user`? Available args:
type BotUsersCreateInput {
  telegramId: BigInt
  telegramBotId: BigInt
  role?: RoleName
  bot?: BotsCreateNestedOneWithoutBotUsersInput
  user?: UsersCreateNestedOneWithoutBotUsersInput
  inviterId?: BigInt | Null
}


    at Document.validate (/Users/victordmitrishen/Desktop/code/cosmo-core/node_modules/@prisma/client/runtime/index.js:28329:20)
    at serializationFn (/Users/victordmitrishen/Desktop/code/cosmo-core/node_modules/@prisma/client/runtime/index.js:30929:19)
    at runInChildSpan (/Users/victordmitrishen/Desktop/code/cosmo-core/node_modules/@prisma/client/runtime/index.js:24157:12)
    at PrismaClient._executeRequest (/Users/victordmitrishen/Desktop/code/cosmo-core/node_modules/@prisma/client/runtime/index.js:30936:31)
    at async PrismaClient._request (/Users/victordmitrishen/Desktop/code/cosmo-core/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async /Users/victordmitrishen/Desktop/code/cosmo-core/test.js:4:2 {
  clientVersion: '4.3.1'
}
```
or 
```
Unique constraint failed on the fields: (`id`)
    at RequestHandler.handleRequestError (/Users/victordmitrishen/Desktop/code/cosmo-core/node_modules/@prisma/client/runtime/index.js:29909:13)
    at RequestHandler.request (/Users/victordmitrishen/Desktop/code/cosmo-core/node_modules/@prisma/client/runtime/index.js:29892:12)
    at async PrismaClient._request (/Users/victordmitrishen/Desktop/code/cosmo-core/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async /Users/victordmitrishen/Desktop/code/cosmo-core/test.js:4:2 {
  code: 'P2002',
  clientVersion: '4.3.1',
  meta: { target: [ 'id' ] }
}
```

### Expected behavior

The script, doesn't have any errors.

### Prisma information

```prisma
model BotUsers {
  id            Int      @id @default(autoincrement())
  userId        Int
  telegramId    BigInt
  telegramBotId BigInt
  role          RoleName @default(User)
  bot           Bots?    @relation(fields: [botId], references: [id])
  user          Users?   @relation(fields: [userId], references: [id])
  botId         Int
  inviterId     BigInt?
}
```

```ts
const prisma = require('./prisma');

(async () => {
	await prisma.botUsers.create({
		data: {
			telegramId: BigInt(1),
			telegramBotId: BigInt(3), userId: 1,
			role: 'Admin', botId: 9
		}
	});
})();
```

### Environment & setup

- OS: Mac OS M1
- Database: PostgreSQL
- Node.js version: v15.13.0

### Prisma Version

```
4.3.1
```

**Comment by janpio** [comment]
What do you mean with the second error message behind `or`? That looks like it is from a successful creation, where an item with `id` already existed. DI you overcome the `Unknown arg` problem for that?

Your actual problem could be because of a confusing area of our types right now: You can not combine updating foreign key fields (`telegramId`, `telegramBotId`, `userId`, `botId`) and relations (`role`) at the same time. It might be that this also applies to enums.

On the other hand, are you sure your Prisma Client is up to date via `prisma generate` when you get this error message?

**Comment by victor-dm-black** [comment]
Thank you, I solve the problem, error was in another place.
