### ISSUE TITLE
[Typescript] "RangeError: Maximum call stack size exceeded" because of triangle relations

### ISSUE THREAD

**Issue by alexandrevanhoutte** [prisma/prisma#15479]
### Bug description

Hi,

I currently have a bug during a typescript build.

My current schema have 3 models: "Picture" / "Request" / "RequestProposal"
**Request** and **RequestProposal** are connected and these both models are connected to **Picture Table**.

So it makes a triangle.

When I make **prisma migrate dev**, I don't get any problem.
But when I build (tsc), I get:

```
RangeError: Maximum call stack size exceeded
    at getUnionType (.../node_modules/typescript/lib/tsc.js:50708:21)
    at getTypeFromUnionTypeNode (.../node_modules/typescript/lib/tsc.js:50791:38)
    at getTypeFromTypeNodeWorker (.../node_modules/typescript/lib/tsc.js:52356:28)
    at getTypeFromTypeNode (.../node_modules/typescript/lib/tsc.js:52305:49)
    at tryGetTypeFromEffectiveTypeNode (.../node_modules/typescript/lib/tsc.js:46471:24)
    at getTypeForVariableLikeDeclaration (.../node_modules/typescript/lib/tsc.js:45988:32)
    at getWidenedTypeForVariableLikeDeclaration (.../node_modules/typescript/lib/tsc.js:46435:56)
    at getTypeOfVariableOrParameterOrPropertyWorker (.../node_modules/typescript/lib/tsc.js:46576:24)
    at getTypeOfVariableOrParameterOrProperty (.../node_modules/typescript/lib/tsc.js:46477:28)
    at getTypeOfSymbol (.../node_modules/typescript/lib/tsc.js:46814:24)

```

I removed 1 relation to verify, the build is working.

Thank you in advance for your answer. :)

### How to reproduce

1. Make a schema prisma. (See Prisma Information.)
2. prisma migrate dev
3. Build (tsc)

### Expected behavior

I expect that the build is running without any error.

### Prisma information

```prisma
model Picture {
  id                    Int              @id @default(autoincrement())
  Request               Request?         @relation(fields: [requestId], references: [id])
  requestId             Int?
  Proposal              RequestProposal?        @relation(fields: [proposalId], references: [id])
  proposalId            Int?
}

model Request {
  id               Int                @id @default(autoincrement())
  pictures         Picture[]
  proposals              RequestProposal[]
}

model RequestProposal {
  id               Int                @id @default(autoincrement())
  pictures         Picture[]
  requestId        Int
  request          Request            @relation(fields: [requestId], references: [id])
}

```

### Environment & setup

- OS:  macOS
- Database: MariaDB
- Node.js version: v16.14.0

### Prisma Version

```
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
Preview Features        : interactiveTransactions
```

**Comment by millsp** [comment]
Hey @alexandrevanhoutte, which version of TypeScript are you using?

**Comment by alexandrevanhoutte** [comment]
Currently `"typescript": "4.7.4"`.
I’m not sure it will change something 
, but i can try to upgrade.
Will test as soon as possible.

**Comment by alexandrevanhoutte** [comment]
Oh ok, the problem occurs only with "typescript": "4.7.4".

I updated to 4.8.3, the build was working.
I downgraded again to verify, it was crashing.
 
So I only needed to update typescript, oops... Sorry for the inconvenience.
