### ISSUE TITLE
db error: ERROR: invalid input syntax for type uuid: "$2"

### ISSUE THREAD

**Issue by ahmetkca** [prisma/prisma#15472]
### Bug description

I have the following query statement which I can run it with no problem on pgAdmin v4 
```sql
SELECT 	(gitTree.obj ->> 'path'),
		(gitTree.obj ->> 'content_url'),
		gitTree.pos as  pos,
		bgr."backgroundJobId" as bgj_id
FROM "BackgroundJobResult" bgr
LEFT JOIN LATERAL jsonb_array_elements(bgr."data")
					WITH ORDINALITY AS gitTree(obj, pos) ON true
WHERE (gitTree.obj ->> 'path') ='utils/generateAllMetricsDocumentation.py' AND "backgroundJobId" = '6d988338-5791-42ff-9c37-e1fcd6f9a6b5';
```

However when I try to run this query statement with `$queryRaw` I get the following error
```
 error PrismaClientKnownRequestError:
 Invalid `prisma.$queryRaw()` invocation:


 Raw query failed. Code: `22P02`. Message: `db error: ERROR: invalid input syntax for type uuid: "$2"`
     at RequestHandler.handleRequestError (/home/xxxxx/xxxxx/xxxxxxx/app1/node_modules/@prisma/client/runtime/index.js:29909:13)
     at RequestHandler.request (/home/xxxxx/xxxxx/xxxxxxx/app1/node_modules/@prisma/client/runtime/index.js:29892:12)
     at async Proxy._request (/home/xxxxx/xxxxx/xxxxxxx/app1/node_modules/@prisma/client/runtime/index.js:30864:16) {
   code: 'P2010',
   clientVersion: '4.3.1',
   meta: {
     code: '22P02',
     message: 'db error: ERROR: invalid input syntax for type uuid: "$2"'
   }
 
```

### Expected behavior

```
[
    {
        "path": "utils/generateAllMetricsDocumentation.py",
        "content_url": "https://api.github.com/repos/xxxxxxx/xxxxxxx/git/blobs/88d9ae91c71ca30feeba4339db942e91a04dbab5
    }
]
```

### Prisma information

```prisma
generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["filterJson"]
}

datasource db {
    provider = "postgresql"
    url      = env("DATABASE_URL")
}

model BackgroundJob {
    id           Int                    @id @default(autoincrement())
    jobName      String
    jobId        String                 @unique @db.Uuid
    jobPayload   BackgroundJobPayload?
    jobStatus    String
    jobProgress  BackgroundJobProgress?
    jobResult    BackgroundJobResult?
    jobError     String?
    jobCreatedAt DateTime               @default(now())
    jobUpdatedAt DateTime               @updatedAt
}

model BackgroundJobPayload {
    id              Int           @id @default(autoincrement())
    data            Json
    backgroundJob   BackgroundJob @relation(fields: [backgroundJobId], references: [id])
    backgroundJobId Int           @unique
    createdAt       DateTime      @default(now())
    updatedAt       DateTime      @updatedAt
}

model BackgroundJobResult {
    id              Int           @id @default(autoincrement())
    data            Json          @db.JsonB
    backgroundJob   BackgroundJob @relation(fields: [backgroundJobId], references: [jobId])
    backgroundJobId String        @unique @db.Uuid
    createdAt       DateTime      @default(now())
    updatedAt       DateTime      @updatedAt
}

model BackgroundJobProgress {
    id              Int           @id @default(autoincrement())
    status          String        @default("processing")
    currentStep     Int
    totalSteps      Int
    message         String
    backgroundJob   BackgroundJob @relation(fields: [backgroundJobId], references: [jobId])
    backgroundJobId String        @unique @db.Uuid
    createdAt       DateTime      @default(now())
    updatedAt       DateTime      @updatedAt
}
```

```ts
export async function openFileFromGithubRepo(filePath: string, backgroundJobId: string,  cb: (file: File) => void): Promise<void> {
    const queryStatement = Prisma.sql`SELECT (gitTree.obj ->> 'path') as path, (gitTree.obj ->> 'content_url') as content_url FROM "BackgroundJobResult" bgr LEFT JOIN LATERAL jsonb_array_elements(bgr."data") WITH ORDINALITY AS gitTree(obj, pos) ON true WHERE (gitTree.obj ->> 'path') = '${filePath}' AND "backgroundJobId" = '${backgroundJobId}';`;

    const queryResult = await prisma.$queryRaw<Array<{ path: string, content_url: string }>>(queryStatement);
}
```

### Environment & setup

- OS: WSL2 on Windows 10
- Database: PostgreSQL
- Node.js version: v16.16.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt c875e43600dfe042452e0b868f7a48b817b9640b (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.3.0-32.c875e43600dfe042452e0b868f7a48b817b9640b
Default Engines Hash    : c875e43600dfe042452e0b868f7a48b817b9640b
Studio                  : 0.473.0
Preview Features        : filterJson
```

**Comment by ahmetkca** [comment]
might be related to this #5083

**Comment by ahmetkca** [comment]
`$queryRawUnsafe` works as expected! Is there something I am missing about `$queryRaw`?

**Comment by SevInf** [comment]
@ahmetkca 
`Prisma.sql` as well as `$queryRaw` do not create a string but rather prepared statement - object, where `text` and `values` are separate. This a safe way to pass raw query to the driver while avoiding potential injections. So, for example, ``Prisma.sql`SELECT ${foo}` `` will produce `{ text: 'SELECT $1', values: ['foo']}` object. Note that it does not have quotes around substitution. And that's a mistake in your raw query — you have quotes around `fileName` and `backgroundJobId` substitutions. Correct code would be:

```ts
  const queryStatement = Prisma.sql`SELECT (gitTree.obj ->> 'path') as path, (gitTree.obj ->> 'content_url') as content_url FROM "BackgroundJobResult" bgr LEFT JOIN LATERAL jsonb_array_elements(bgr."data") WITH ORDINALITY AS gitTree(obj, pos) ON true WHERE (gitTree.obj ->> 'path') = ${filePath} AND "backgroundJobId" = ${backgroundJobId}::UUID;`
```

I've also added typcast around `backgroundJobId` — this is necessary since it is now a string variable and not a literal.

**Comment by juanse24262000** [comment]
just do prisma.$queryRaw´select * from table where id = ${uuid}::UUID´
