### ISSUE TITLE
Regression in the way we show validation errors

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#15471]
### Bug description

We have a regression in the way we display errors in case of an invalid input between 2.2.0 and 4.3.0. The errors used to be more helpful and more pretty. Basically, the TS validation of this query has stopped working and a less-friendly validation error from the engines has replaced it.

### How to reproduce

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Author {
  id        Int              @id @default(autoincrement()) // Primary key
  name      String // Author name
  Book      Book[]
}

model Book {
  id        Int              @id @default(autoincrement()) // Primary key
  title     String // Book title
  authorId  Int?
  author    Author?         @relation(fields: [authorId], references: [id]) // A foreign key to Author
  @@unique([title, authorId])
}

generator client {
  provider = "prisma-client-js"
}
```

```ts
async function main() {
  prisma.author.upsert({
    where: {
      id: 1,
    },
    update: {},
    create: {
      name: 'Hemingway'
    },
  });
}
```

```sh
  50 {
  51   const title = "For Whom the Bell Tolls";
  52   try {
→ 53     await prismaClient.book.upsert(
Missing a required value at `Mutation.upsertOneBook.where.BookWhereUniqueInput.title_authorId.BookTitleAuthorIdCompoundUniqueInput.authorId`
Error: 
Invalid `prismaClient.book.upsert()` invocation in
/Users/j42/Repros/prisma-null-foreignkey/src/index.ts:53:31

  50 {
  51   const title = "For Whom the Bell Tolls";
  52   try {
→ 53     await prismaClient.book.upsert(
Missing a required value at `Mutation.upsertOneBook.where.BookWhereUniqueInput.title_authorId.BookTitleAuthorIdCompoundUniqueInput.authorId`
    at RequestHandler.handleRequestError (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:30850:13)
    at RequestHandler.request (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:30833:12)
    at PrismaClient._request (/Users/j42/Repros/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:31805:16)
```

### Expected behavior

```sh
Error: 
Invalid `prisma.book.upsert()` invocation:

{
  where: {
    title_authorId: {
      title: 'For Whom the Bell Tolls',
      authorId: null
                ~~~~
    }
  },
  update: {},
  create: {
    title: 'For Whom the Bell Tolls',
    authorId: null
  }
}

Argument authorId: Got invalid value null on prisma.upsertOneBook. Provided null, expected Int.


    at Document.validate (/home/xqkuang/github/prisma-null-foreignkey/node_modules/@prisma/client/runtime/index.js:32548:19)
```

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Ubuntu 20.04
- Database: Sqlite
- Node.js version: 16

### Prisma Version

```
4.3.0
```

**Comment by SevInf** [comment]
As of 5.10.0 seems to be fixed, both for compile and runtime.

With the provided schema, following code:

```ts
async function main() {
  const prisma = new PrismaClient()
  await prisma.book.upsert({
    where: {
      title_authorId: {
        title: 'For Whom the Bell Tolls',
        // @ts-ignore
        authorId: null,
      },
    },
    update: {},
    create: {
      title: 'For Whom the Bell Tolls',
      authorId: null,
    },
  })
}
```

Produces TS Error:

```
index.ts:10:9 - error TS2322: Type 'null' is not assignable to type 'number'.

10         authorId: null
```

If we ignore compile-time error, we get a proper runtime error instead:

```
PrismaClientValidationError:
Invalid `prisma.book.upsert()` invocation in
/Users/serhii/projects/prisma/sandbox/workbench/index.ts:6:21

  3
  4 async function main() {
  5   const prisma = new PrismaClient()
→ 6   await prisma.book.upsert({
        where: {
          title_authorId: {
            title: "For Whom the Bell Tolls",
      +     authorId: Int
          }
        },
        update: {},
        create: {
          title: "For Whom the Bell Tolls",
          authorId: null
        }
      })

Argument `authorId` must not be null.
```

So, i think, this issue can be closed now.
