### ISSUE TITLE
PrismaClientUnknownRequestError on create statement default optional value

### ISSUE THREAD

**Issue by iiAku** [prisma/prisma#15581]
### Bug description

Hello,

Since version 4.4.0 I have a breaking change in our code. Their is some create statement that do not work if a default time based field is not set. It is now a mandatory to explicitly specify default value within create statement ? It was basically working in 4.3.1 version. However it does work if you explicitly set the time based field (created_at, in my case) with a date value for instance.

It very like or similar to this #14918  or #10497 

Base SQL schema is

```
CREATE TABLE public.values (
    value_id uuid NOT NULL,
    value numeric(13, 5) NOT NULL DEFAULT 0,
    created_at timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT values_pkey PRIMARY KEY (value_id, created_at)
);
```

In 4.4.0

```
  prisma:tryLoadEnv  Environment variables loaded from /Users/iiaku/dev-d/create_repro/.env +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/iiaku/dev-d/create_repro/.env +2ms
  prisma:client  dirname /Users/iiaku/dev-d/create_repro/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /Users/iiaku/dev-d/create_repro/prisma +0ms
  prisma:client  clientVersion 4.4.0 +0ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /Users/iiaku/dev-d/create_repro/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /Users/iiaku/dev-d/create_repro/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:client  Prisma Client call: +13ms
  prisma:client  prisma.values.create({
  data: {
    value_id: '37958000-3275-4f29-a4b4-1d26705de434',
    value: 1000
  }
}) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  createOnevalues(data: {
    value_id: "37958000-3275-4f29-a4b4-1d26705de434"
    value: 1000
  }) {
    value_id
    value
    created_at
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +14ms
  prisma:client:libraryEngine  library starting +1ms
prisma:info Starting a postgresql pool with 21 connections.
  prisma:client:libraryEngine  library started +25ms
prisma:query BEGIN
prisma:query INSERT INTO "public"."values" ("value_id","value","created_at") VALUES ($1,$2,$3) RETURNING "public"."values"."value_id", "public"."values"."created_at"
prisma:query SELECT "public"."values"."value_id", "public"."values"."created_at", "public"."values"."value" FROM "public"."values" WHERE ("public"."values"."value_id" = $1 AND "public"."values"."created_at" = $2) LIMIT $3 OFFSET $4
prisma:query ROLLBACK
  prisma:client:request_handler  PrismaClientUnknownRequestError: Query createOnevalues is required to return data, but found no record(s).
    at prismaGraphQLToJSError (/Users/iiaku/dev-d/create_repro/node_modules/@prisma/client/runtime/index.js:20428:10)
    at LibraryEngine.buildQueryError (/Users/iiaku/dev-d/create_repro/node_modules/@prisma/client/runtime/index.js:27330:12)
    at LibraryEngine.request (/Users/iiaku/dev-d/create_repro/node_modules/@prisma/client/runtime/index.js:27263:22)
    at async RequestHandler.request (/Users/iiaku/dev-d/create_repro/node_modules/@prisma/client/runtime/index.js:30816:24)
    at async PrismaClient._request (/Users/iiaku/dev-d/create_repro/node_modules/@prisma/client/runtime/index.js:31812:16) {
  clientVersion: '4.4.0'
} +0ms
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms
/Users/iiaku/dev-d/create_repro/node_modules/@prisma/client/runtime/index.js:30855
      throw new PrismaClientUnknownRequestError(message, this.client._clientVersion);
            ^
PrismaClientUnknownRequestError: 
Invalid `prisma.values.create()` invocation in
/Users/iiaku/dev-d/create_repro/index.ts:6:23

  3   log: ["error", "info", "query", "warn"],
  4 })
  5 const main = async () => {
→ 6   await prisma.values.create(
Query createOnevalues is required to return data, but found no record(s).
    at RequestHandler.handleRequestError (/Users/iiaku/dev-d/create_repro/node_modules/@prisma/client/runtime/index.js:30855:13)
    at RequestHandler.request (/Users/iiaku/dev-d/create_repro/node_modules/@prisma/client/runtime/index.js:30834:12)
    at async PrismaClient._request (/Users/iiaku/dev-d/create_repro/node_modules/@prisma/client/runtime/index.js:31812:16) {
  clientVersion: '4.4.0'
}

```

In 4.3.1
```
  prisma:tryLoadEnv  Environment variables loaded from /Users/iiaku/dev-d/create_repro/.env +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/iiaku/dev-d/create_repro/.env +2ms
  prisma:client  dirname /Users/iiaku/dev-d/create_repro/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /Users/iiaku/dev-d/create_repro/prisma +0ms
  prisma:client  clientVersion 4.3.1 +0ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /Users/iiaku/dev-d/create_repro/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /Users/iiaku/dev-d/create_repro/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:client  Prisma Client call: +242ms
  prisma:client  prisma.values.create({
  data: {
    value_id: '37958000-3275-4f29-a4b4-1d26705de434',
    value: 1000
  }
}) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  createOnevalues(data: {
    value_id: "37958000-3275-4f29-a4b4-1d26705de434"
    value: 1000
  }) {
    value_id
    value
    created_at
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +243ms
  prisma:client:libraryEngine  library starting +1ms
prisma:info Starting a postgresql pool with 21 connections.
  prisma:client:libraryEngine  library started +29ms
prisma:query BEGIN
prisma:query INSERT INTO "public"."values" ("value_id","value","created_at") VALUES ($1,$2,$3) RETURNING "public"."values"."value_id", "public"."values"."created_at" /* traceparent=00-00-00-00 */
prisma:query SELECT "public"."values"."value_id", "public"."values"."created_at", "public"."values"."value" FROM "public"."values" WHERE ("public"."values"."value_id" = $1 AND "public"."values"."created_at" = $2) LIMIT $3 OFFSET $4 /* traceparent=00-00-00-00 */
prisma:query COMMIT
  prisma:client:libraryEngine:exitHooks  exit event received: beforeExit +0ms
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms

```

### How to reproduce

1. Clone repro from here: https://github.com/iiAku/prisma-default-field-repro
2. Follow usage README.md section
3. Try with both version Prisma Client 4.3.1 and 4.4.0

### Expected behavior

We should either have the same behavior with both version OR to know that defaulted field from db should now be explicitly set within data statements.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model values {
  value_id   String   @db.Uuid
  value      Decimal  @default(0) @db.Decimal(13, 5)
  created_at DateTime @default(now())

  @@id([value_id, created_at])
}
```

```ts
import { Prisma, PrismaClient } from "@prisma/client"
const prisma = new PrismaClient({
  log: ["error", "info", "query", "warn"],
})
const main = async () => {
  await prisma.values.create({
    data: {
      value_id: "37958000-3275-4f29-a4b4-1d26705de434",
      value: 1000,
      //created_at: new Date(),
    },
  })
}

main()
```

### Environment & setup

- OS: macOS Monterey
- Database: PostgreSQL
- Node.js version: v16.17.0

### Prisma Version

```
4.4.0
```

**Comment by garrensmith** [comment]
thanks for the info @iiAku we will look into this.

**Comment by garrensmith** [comment]
I think the issue can be traced to this commit https://github.com/prisma/prisma-engines/commit/fcf3572335e1fd8e0cd0fff9322345dae114f071

In 4.3 we would run this query:

```

INSERT INTO
"public"."values" ("value_id", "value", "created_at")
VALUES
($1, $2, $3) RETURNING "public"."values"."value_id",
"public"."values"."created_at"
params=["37958000-3275-4f29-a4b4-1d26705de434",1000,"2022-09-28 13:25:31.713 UTC"] result="success" item_type="query" is_query=true duration_ms=41
query=SELECT
"public"."values"."value_id",
"public"."values"."created_at",
"public"."values"."value"
FROM
"public"."values"
WHERE
(
"public"."values"."value_id" = $1
AND "public"."values"."created_at" = $2
)
LIMIT
$3 OFFSET $4
params=["37958000-3275-4f29-a4b4-1d26705de434","2022-09-28 13:25:31.713 UTC",1,0] result="success" item_type="query" is_query=true duration_ms=26

```

And in 4.4 we run:

```
INSERT INTO
"public"."values" ("value_id", "value", "created_at")
VALUES
($1, $2, $3) RETURNING "public"."values"."value_id",
"public"."values"."created_at"
params=["37958000-3275-4f29-a4b4-1d26705de434",1000,"2022-09-28 13:16:50.552979 UTC"]

query=SELECT
"public"."values"."value_id",
"public"."values"."created_at",
"public"."values"."value"
FROM
"public"."values"
WHERE
(
"public"."values"."value_id" = $1
AND "public"."values"."created_at" = $2
)
LIMIT
$3 OFFSET $4
params=["37958000-3275-4f29-a4b4-1d26705de434","2022-09-28 13:16:50.552979 UTC",1,0] result="success" item_type="query" is_query=true duration_ms=2

```

We have a lot more precision in the time `.552979` versus the older precision of 3 decimal points. I'm not sure why that causes an issue but it does.

**Comment by iiAku** [comment]
This is exactly what @garrensmith mentioned that cause the bug. Basically my timestamp field has a p = 3 precision.

From https://www.postgresql.org/docs/current/datatype-datetime.html

it says: 
> time, timestamp, and interval accept an optional precision value p which specifies the number of fractional digits retained in the seconds field. By default, there is no explicit bound on precision. The allowed range of p is from 0 to 6.

So I increased the precision it does work, with:
```
ALTER TABLE public."values" ALTER COLUMN created_at TYPE timestamp(6) USING created_at::timestamp;
```

Nevertheless it does not answer why we are getting more precision between version but at least it a fix for the problem.

Thanks for looking into this.
