### ISSUE TITLE
`__dirname is not defined` when generating PrismaClient to custom location, w/ SvelteKit

### ISSUE THREAD

**Issue by McGaelen** [prisma/prisma#15614]
### Bug description

Prisma seems to have issues running with SvelteKit when generating the client to some other location other than the default.

When running a production build for the app, the following error will show:
```
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/<sveltekit-project-dir>/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///<sveltekit-project-dir>/build/server/chunks/2-6f7b7120.js:19960:27
    at file:///<sveltekit-project-dir>/build/server/chunks/2-6f7b7120.js:31969:3
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async Promise.all (index 1)
    at async render_page (file:///<sveltekit-project-dir>/build/server/index.js:2382:19)
    at async resolve (file:///<sveltekit-project-dir>/build/server/index.js:2872:22)
    at async respond (file:///<sveltekit-project-dir>/build/server/index.js:2910:22)
    at async Array.ssr (file:///<sveltekit-project-dir>/build/handler.js:19060:3)
```

### Notes: 
* This issue does not happen when running `vite dev` or `vite preview` for some reason. Prisma works as expected under those conditions. The error only happens when running the build output directly with node.
* If you remove the `output` option from the generator, then import the prisma client from '@prisma/client', Prisma will run as expected - but unfortunately that doesn't meet my needs.
* **Reason for this use case**: I need to connect to multiple schemas, and I want the benefit of prisma's generated types for both. As far as I know, the only way to connect to multiple schemas is to generate multiple prisma clients - which in turn means I can't use '@prisma/client' because that package will only point to one client at a time. (When generating multiple clients to the default location, they will just overwrite each other)

### How to reproduce

See my test repo where I've reproduced the error: [https://github.com/McGaelen/prisma-sveltekit](https://github.com/McGaelen/prisma-sveltekit)

### Expected behavior

No error and Prisma runs as expected.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  output = "../node_modules/custom-client-location"
}
...(the rest is an exact copy of https://www.prisma.io/docs/getting-started/quickstart)
```

```ts
import {PrismaClient} from 'custom-client-location' // <- importing from custom location specified in prisma.schema
const prisma = new PrismaClient()
```

### Environment & setup

- OS: macOS, CentOS
- Database: PostgreSQL, SQLite, but probably all of them
- Node.js version: v16.15.1

### Prisma Version

```
prisma                  : 4.4.0
@prisma/client          : 4.4.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.4.0-66.f352a33b70356f46311da8b00d83386dd9f145d6
Default Engines Hash    : f352a33b70356f46311da8b00d83386dd9f145d6
Studio                  : 0.474.0

```

**Comment by apollo79** [comment]
I'm getting this error too, but with [`solid-start`](https://start.solidjs.com). 

```
file:///<path_to_project>/dist/server.js:36641
        import_path2.default.join(__dirname, "../query-engine-darwin");
                                  ^

ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '<path_to_project>/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///<path_to_project>/dist/server.js:36641:28
    at file:///<path_to_project>/dist/server.js:52455:3
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
```

Would be awesome if this would be fixed!

**Comment by feynmanliang** [comment]
Can confirm this is an issue we are affected with (Sveltekit + Prisma fails on node-adapter). Probably related to https://github.com/prisma/prisma/issues/5030#issuecomment-1347116391?

**Comment by feynmanliang** [comment]
FWIW we have since migrated off of SvelteKit + Prisma as being locked in to Vercel for deployments did not meet our requirements.

**Comment by AlienHack** [comment]
> FWIW we have since migrated off of SvelteKit + Prisma as being locked in to Vercel for deployments did not meet our requirements.

@feynmanliang I got a hacky solution from other thread that works

![5CEEE39C-FA31-4017-A08B-E13BD401275C](https://user-images.githubusercontent.com/8213866/229022504-2e70b566-cde3-4132-936c-3b2b3c890ce1.jpeg)
![4A36CE88-8D8C-4D83-896D-AA448E80241B](https://user-images.githubusercontent.com/8213866/229022508-e1fd3de3-b906-41aa-b275-44f5b88b1001.jpeg)

**Comment by MilyMilo** [comment]
Linking the solution that @AlienHack mentioned: https://github.com/prisma/prisma/issues/5030#issuecomment-1398076317

It's ugly - but it works. Would love to see some movement on this issues!

**Comment by maietta** [comment]
> Can confirm this is an issue we are affected with (Sveltekit + Prisma fails on node-adapter). Probably related to [#5030 (comment)](https://github.com/prisma/prisma/issues/5030#issuecomment-1347116391)?

**_THANK YOU. Finally after days of researching to find the root cause of my problem, I finally find someone else who has the same problem!_**

It's specifically the use of Prisma Client with the node adapter. SvelteKit just happens to be what I'm using to make it work. I don't think it's septically tied to the SSR/Server Side Rendering. That's just the mode.

As you are likely aware, the root cause seems to be that we're using ES6 but the Prisma client is using an old __dirname() function that isn't support/available in ES6. The reason for the continued use of this __dirname() function for the detection of the environment specifically for Vercel hosted websites.

Are you by chance deploying to CapRover PaaS?

I'm still working to find a solution as of this writing.

**Comment by ryoppippi** [comment]
Hi! This problems came up on Azure Web Service, too
This hack works fine and is brilliant!! ↓
https://github.com/prisma/prisma/issues/5030#issuecomment-1398076317

**Comment by dievardump** [comment]
> As you are likely aware, the root cause seems to be that we're using ES2022 but the Prisma client is using an old __dirname() function that isn't support/available in ES2022, which I believe is the default used in SvelteKit. The reason for the continued use of this __dirname() function for the detection of the environment specifically for Vercel hosted websites.
> 

Is there no way to detect if __dirname exists and if not, shim/manage it with import.meta.url?

SvelteKit allows to build and ship the build folder "as is", without needing to install any dependencies after the build.

https://github.com/prisma/prisma/issues/5030#issuecomment-1398076317 solution is not very clean, but it also forces to reinstall @prisma/client where the build is shipped, which is really not convenient!

**Comment by Jolg42** [comment]
@gtim mentioned in https://github.com/prisma/prisma/discussions/19564 that our prototype version will ESM support worked.

@feynmanliang @ryoppippi @dievardump @wvhulle @AlienHack @maietta @McGaelen @MilyMilo @apollo79
It would really help if you could try that prototype version, see instruction at https://pris.ly/esm

The more feedback we get, the more confident we will be to bring this into the latest version of Prisma 🙌🏼

**Comment by maietta** [comment]
> 

I am no longer having any issues with Prisma and not sure what changed. I don't think I will have to run the prototype version-- but just out of curiosity I'll try to make that happen in the next few days and report back any issues I run into.

**Comment by AlienHack** [comment]
> @gtim mentioned in #19564 that our prototype version with ESM support worked.
> 
> @feynmanliang @ryoppippi @dievardump @wvhulle @AlienHack @maietta @McGaelen @MilyMilo @apollo79 It would really help if you could try that prototype version, see instructions at https://pris.ly/esm
> 
> The more feedback we get in #19564, the more confident we will be to bring this into the latest version of Prisma 🙌🏼

I also no longer have this issue. Using standard prisma setup, and viola no error appeared.

**Comment by Torbet** [comment]
I'm getting this error now specifically when importing prisma into `hooks.server.ts`, seems to be working everywhere else!

**Comment by maietta** [comment]
> I'm getting this error now specifically when importing prisma into `hooks.server.ts`, seems to be working everywhere else!

Is this only in deployments and if so, are you by chance using the Node adapter? This is where I was having this issue, but no longer am I having the issue.

**Comment by Torbet** [comment]
@maietta Yup! Only when running the Node build!

Working in `+page.server.ts` though, how did you fix?

**Comment by Torbet** [comment]
The same build works fine on all prisma versions <=4.16.0! Broke in 4.16.1

**Comment by maietta** [comment]
> @maietta Yup! Only when running the Node build!
> 
> Working in `+page.server.ts` though, how did you fix?

I honestly don't know. Just one day it started working. I was able to deploy to Vercel without issues, but not using Node adapter until one day it just started working.

Frustrating not knowing the exact reason.

But, you say have specific version nailed down from working to non-working, so that means we can review what changed between versions.

**Comment by lost22git** [comment]
simillar problem with running binary executable produced by  `bun build --compile`

start error info
```
prisma:error Can't find variable: __dirname
1 | __dirname
   ^
ReferenceError: Can't find variable: __dirname
      at compiled://root/test-elysia:4097:69
      at processTicksAndRejections (:1:2602)
```

**Comment by janpio** [comment]
Can you open a new issue for this @lost22git? WIth bun that is a different problem for us. Thank you.
(Please fill the full issue template so we can hopefully reproduce this.)

**Comment by tbdrz** [comment]
> I'm getting this error now specifically when importing prisma into `hooks.server.ts`, seems to be working everywhere else!

@Torbet Did you find a solution? Get the same, only in hooks.server.ts, with node build

**Comment by ridly** [comment]
I have created a shell script that updates the `build/handler.js` and adds the missing globals.

`fix_dirname_error.sh`:
`
#!/usr/bin/bash

sed -i '/await server.init/i \
globalThis.__filename = fileURLToPath(import.meta.url); \
globalThis.__dirname = path.dirname(__filename);' build/handler.js
`

then in the package.json update the build command:
`"build": "vite build && ./fix_dirname_error.sh",`

The above works with the current (2.5.10) version of sveltekit and on linux. I assume would work on Mac too.

**Comment by lpknv** [comment]
I am experiencing the same issue on vercel with nuxt 3.

`/api/login
 ReferenceError: __dirname is not defined in ES module scope
    at file:///var/task/chunks/_/db.mjs:825:16
    ... 4 lines matching cause stack trace ...
    at async Server.<anonymous> (/opt/rust/nodejs.js:16:5739) {
  cause: ReferenceError: __dirname is not defined in ES module scope
      at file:///var/task/chunks/_/db.mjs:825:16
      at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:578:26)
      at async Object.handler (file:///var/task/chunks/nitro/nitro.mjs:2633:19)
      at async toNodeHandle (file:///var/task/chunks/nitro/nitro.mjs:2904:7)
      at async Server.<anonymous> (/opt/rust/nodejs.js:16:5739),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: `

**Comment by Mateleo** [comment]
Ok, I've found a solution for the "__dirname is not defined in ES module scope" error.

The issue arises when using ES modules (ESM) in the generated Prisma Client. The `__dirname` variable is not automatically available in ESM.

**Solution:**

Explicitly set `moduleFormat = "esm"` in the generator block of your `schema.prisma` file. This ensures that the Prisma Client is generated with the correct module format and uses `import.meta.url` instead of `__dirname` for resolving file paths.

```prisma
generator client {
  provider = "prisma-client"
  output   = "../src/generated/prisma"
  moduleFormat = "esm" // Explicitly set module format to ESM
}
```
ref : https://www.prisma.io/docs/orm/prisma-schema/overview/generators#field-reference-1

**Comment by davidparys** [comment]
`ReferenceError: __dirname is not defined in ES module scope
    at file:///var/task/chunks/nitro/nitro.mjs:10417:16
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async d (/opt/rust/nodejs.js:16:18341)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
ReferenceError: __dirname is not defined in ES module scope
    at file:///var/task/chunks/nitro/nitro.mjs:10417:16
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async d (/opt/rust/nodejs.js:16:18341)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.`



Same with nuxt 3 / vercel

**Comment by lpknv** [comment]
I actually managed to solve that issue... simply by moving away from nodejs entirely (no hate & no rant).

**Comment by OliverRM** [comment]
Thank you @gozilla-paradise the wonderful [workaround](https://github.com/prisma/prisma/issues/15614#issuecomment-1491269798) you posted above. It works just great 😊 As a matter of convenience for others I am reposting it here as plain code:

``` typescript
import type { PrismaClient as ImportedPrismaClient } from "@prisma/client";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const { PrismaClient: RequiredPrismaClient } = require("@prisma/client");

const _PrismaClient: typeof ImportedPrismaClient = RequiredPrismaClient;

export class PrismaClient extends _PrismaClient {}
```

Now importing the just created `PrismaClient` instead of the one from `@prisma/client` fixed the issue for me.

**Comment by JoeskiG** [comment]
I managed to fix this issue with one of my projects by replacing all occurrences of `__dirname` with `import.meta.url` from all files in the build directory. I made a short script to automatically do this after each build too so it's faster. Maybe you could try doing that?

**Comment by kambanwait** [comment]
Getting this with Netlify, Nuxt3 and Prisma. It's frustrating.

I've tried all solutions and can't seem to find what the issue is. The site builds, but as soon as you start calling the endpoints, it fails.

Netlify logs show the following:

```
Apr 21, 08:33:55 AM: b7d5b9d4 ERROR  [request error] [unhandled] [POST] https://scriptednotes.netlify.app/api/user
 ReferenceError: __dirname is not defined in ES module scope
    at file:///var/task/chunks/_/db.mjs:825:16
    ... 7 lines matching cause stack trace ...
    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26) {
  cause: ReferenceError: __dirname is not defined in ES module scope
      at file:///var/task/chunks/_/db.mjs:825:16
      at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:578:26)
      at async Object.handler (file:///var/task/chunks/nitro/nitro.mjs:2433:19)
      at async toNodeHandle (file:///var/task/chunks/nitro/nitro.mjs:2704:7)
      at async b (file:///var/task/chunks/nitro/nitro.mjs:1176:6914)
      at async Module.handler (file:///var/task/chunks/nitro/nitro.mjs:6107:13)
      at async Runtime.handler (file:///var/task/___netlify-bootstrap.mjs:2:34361)
      at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}
```

I've the following in the in my `schema.prisma`: 

```
generator client {
  provider      = "prisma-client-js"
  output        = "../generated/prisma"
  moduleFormat  = "esm"
}
```

My db.ts has the following:

```
import { PrismaClient } from '@/generated/prisma'

const prismaClientSingleton = () => {
  return new PrismaClient()
}

type PrismaClientSingleton = ReturnType<typeof prismaClientSingleton>

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClientSingleton | undefined
}

export const prisma = globalForPrisma.prisma ?? prismaClientSingleton()

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma
```

I think I'm ready to just give up with all of this 🤦🏽‍♂️

**Comment by rukshn** [comment]
> I actually managed to solve that issue... simply by moving away from nodejs entirely (no hate & no rant).

I also tried different ways of solving this issue for a Nuxt application, but then I switched from NodeJs to Bun. Also the image size is considerably reduced when used Bun over Node containerizing

**Comment by OliverRM** [comment]
The issue should be solved by migrating from `prisma-client-js` to the new `prisma-client`-generator and if need be setting `moduleFormat = "esm"`, see [Generators](https://www.prisma.io/docs/orm/prisma-schema/overview/generators) in the Prisma docs. This is also what @Mateleo does in his [post](https://github.com/prisma/prisma/issues/15614#issuecomment-2794068148) even though he does not explicitly mention it.

**Comment by damisparks** [comment]
> Ok, I've found a solution for the "__dirname is not defined in ES module scope" error.
> 
> The issue arises when using ES modules (ESM) in the generated Prisma Client. The `__dirname` variable is not automatically available in ESM.
> 
> **Solution:**
> 
> Explicitly set `moduleFormat = "esm"` in the generator block of your `schema.prisma` file. This ensures that the Prisma Client is generated with the correct module format and uses `import.meta.url` instead of `__dirname` for resolving file paths.
> 
> generator client {
>   provider = "prisma-client"
>   output   = "../src/generated/prisma"
>   moduleFormat = "esm" // Explicitly set module format to ESM
> }
> ref : https://www.prisma.io/docs/orm/prisma-schema/overview/generators#field-reference-1

@Mateleo I appreciate the solution. However it does not work. Still the same issue.
I had to revert to the version I had before.

```ts
// lib/prisma.ts
import { PrismaClient } from '@prisma/client'

/**
 * TODO: Uncomment and the import when the issue is resolved upstream
 */
// import { PrismaClient } from '../prisma/generated/client'

const prismaClientSingleton = () => {
  return new PrismaClient()
}

declare const globalThis: {
  prismaGlobal: ReturnType<typeof prismaClientSingleton>
// eslint-disable-next-line no-restricted-globals
} & typeof global

const prisma = globalThis.prismaGlobal ?? prismaClientSingleton()

export default prisma

if (process.env.NODE_ENV !== 'production') {
  globalThis.prismaGlobal = prisma
}

```

**Comment by rvillanueva** [comment]
@damisparks 

`moduleFormat = 'esm'` is a red herring. The real fix is the change from using the `prisma-client-js` generator to `prisma-client`. (Example below.)

```
generator client {
  provider = "prisma-client"
  output   = "../src/generated/prisma"
  runtime  = "nodejs"
}
```

This will migrate you to the new generator that's ESM-friendly and will become the default in v7.

https://www.prisma.io/blog/orm-6-12-0-esm-compatible-generator-in-preview-and-new-options-for-prisma-config

**Comment by arshx86** [comment]
3 years post and still same. Every damn time, everything runs well in dev. BUT AS soon as i deploy the project to vercel, PRISMA creating errors. I am sick of it. I am switching to another ORM. It is litereally not possible to deploy nuxt with prisma to anywhere.

I am following EXACT docs from Prisma (both general and the one for nuxt) and it is failing every time. If anyone succeed to deploy with Nuxt 3, please let me know!

https://www.prisma.io/docs/guides/nuxt > ` ERROR  [uncaughtException] WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 63 6f 6e 73`

https://www.prisma.io/docs/getting-started/prisma-orm/quickstart/postgresql > `ESM errors` 

- The nuxt module is not maintained
- ESM errors everywhere
- WASM errors if you use `prisma-client` 

If you are on nuxt, honestly, just use another ORM for your own mental health. Every error takes days to get resolved, updated, noted in docs. I wonder how they have +40 stars.  Nothing is stable. I am sick of it.

I have tried prisma 7, 6, 5, 4. Nothing helps. Yes you don't get ESM errors in prisma 7, but if you are on Nitro you get wasm errors instead and at this point even the dev server don't run.

Some of the errors if i get (there were no workarounds, switching versions sometimes helped)
```
ReferenceError: __dirname is not defined in ES module scope
    at file:///var/task/chunks/nitro/nitro.mjs:7270:16
    at ModuleJob.run (node:internal/modules/esm/module_job:345:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:665:26)
    at async d (/opt/rust/nodejs.js:16:22205)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
```

> 
> ```
> generator client {
>   provider = "prisma-client"
>   output   = "../src/generated/prisma"
>   runtime  = "nodejs"
> }
> ```
> 
> This will migrate you to the new generator that's ESM-friendly and will become the default in v7.
> 
> https://www.prisma.io/blog/orm-6-12-0-esm-compatible-generator-in-preview-and-new-options-for-prisma-config

didn't work 


> Explicitly set `moduleFormat = "esm"` in the generator block of your `schema.prisma` file. This ensures that the Prisma Client is generated with the correct module format and uses `import.meta.url` instead of `__dirname` for resolving file paths.
> 
> generator client {
>   provider = "prisma-client"
>   output   = "../src/generated/prisma"
>   moduleFormat = "esm" // Explicitly set module format to ESM
> }
> ref : https://www.prisma.io/docs/orm/prisma-schema/overview/generators#field-reference-1

Didn't work unfortunately. WASM errors now.

**Comment by damisparks** [comment]
@rvillanueva I appreciate the feedback. I stopped using the Prisma client. I do not have the bandwidth to test your suggestion.
Hopefully, it helps the community.

**Comment by Mateleo** [comment]
@arshx86 Do you have a repo to share ?
