### ISSUE TITLE
Cant connect to remote mysql server: bad handshake.

### ISSUE THREAD

**Issue by codingholt** [prisma/prisma#15641]
### Bug description

When I try to connect with prisma to my database I get : `Error: Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: Server error: ERROR 08S01 (1043): Bad handshake'`

But when I try to connect via my comandline directly to the mysql server using: `mysql -usven -h<ip-address> -p`
It works as expected.

### How to reproduce

- My prisma database url is: `mysql://sven:<URL-ENCODEDPASSWORD>@<IP-ADDRESS>:3306/portfolio?sslidentity=client-identity.p12&sslpassword=<SSL-PASSWORD>&sslcert=ca.pem`

- I copied the ssl certificate and keys like this, and made sure I copied it right. :

  - ```sudo cat /var/lib/mysql/client-key.pem```

  - ```sudo cat /var/lib/mysql/client-cert.pem```

  - ```sudo cat /var/lib/mysql/ca.pem```

- following the [documention](https://www.prisma.io/docs/concepts/database-connectors/mysql#configuring-an-ssl-connection) I made the one sslindentiy of it.

### Prisma information

```prisma
schema.prisma

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

```

```
// command when getting error
npx prisma db pull
```

```
// Debug logs when running npx prisma db pull

 prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at /Users/svennijholt/Documents/Dev/portfolio-site/package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/svennijholt/Documents/Dev/portfolio-site/.env +0ms
  prisma:tryLoadEnv  Environment variables not found at undefined +0ms
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /Users/svennijholt/Documents/Dev/portfolio-site/node_modules/.pnpm/@prisma+engines@4.4.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:getConfig  Loaded Node-API Library +4ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +0ms
Prisma schema loaded from schema.prisma
  prisma:loadEnv  project root found at /Users/svennijholt/Documents/Dev/portfolio-site/package.json +13ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/svennijholt/Documents/Dev/portfolio-site/.env +12ms
  prisma:tryLoadEnv  Environment variables not found at undefined +0ms
Environment variables loaded from ../.env
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /Users/svennijholt/Documents/Dev/portfolio-site/node_modules/.pnpm/@prisma+engines@4.4.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +2ms
  prisma:getConfig  Loaded Node-API Library +0ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +1ms
Datasource "db": MySQL database "portfolio" at "145.89.192.195:3306"
  prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /Users/svennijholt/Documents/Dev/portfolio-site/node_modules/.pnpm/@prisma+engines@4.4.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node +1ms
  prisma:getConfig  Loaded Node-API Library +0ms
  prisma:getConfig  config data retrieved without errors in getConfigNodeAPI +0ms

⠋ Introspecting based on datasource defined in schema.prisma  prisma:introspectionEngine:rpc  starting introspection engine with binary: /Users/svennijholt/Documents/Dev/portfolio-site/node_modules/.pnpm/@prisma+engines@4.4.0/node_modules/@prisma/engines/introspection-engine-darwin-arm64 +0ms
  prisma:introspectionEngine:rpc  SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider = \"mysql\"\n  url      = env(\"DATABASE_URL\")\n}\n","compositeTypeDepth":-1}]} +7ms
⠹ Introspecting based on datasource defined in schema.prisma  prisma:introspectionEngine:rpc  {
  jsonrpc: '2.0',
  error: {
    code: 4466,
    message: 'An error happened. Check the data field for details.',
    data: {
      is_panic: false,
      message: "Error in connector: Error querying the database: Error querying the database: Error querying the database: Server error: `ERROR 08S01 (1043): Bad handshake'",
      backtrace: null
    }
  },
  id: 1
} +171ms
✖ Introspecting based on datasource defined in schema.prisma

Error: Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: Server error: `ERROR 08S01 (1043): Bad handshake'

    at Object.<anonymous> (/Users/svennijholt/Documents/Dev/portfolio-site/node_modules/.pnpm/prisma@4.4.0/node_modules/prisma/build/index.js:91845:25)
    at IntrospectionEngine.handleResponse (/Users/svennijholt/Documents/Dev/portfolio-site/node_modules/.pnpm/prisma@4.4.0/node_modules/prisma/build/index.js:91705:34)
    at LineStream2.<anonymous> (/Users/svennijholt/Documents/Dev/portfolio-site/node_modules/.pnpm/prisma@4.4.0/node_modules/prisma/build/index.js:91791:18)
    at LineStream2.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at LineStream2.Readable.push (node:internal/streams/readable:228:10)
    at LineStream2._pushBuffer (/Users/svennijholt/Documents/Dev/portfolio-site/node_modules/.pnpm/prisma@4.4.0/node_modules/prisma/build/index.js:91592:17)
    at LineStream2._transform (/Users/svennijholt/Documents/Dev/portfolio-site/node_modules/.pnpm/prisma@4.4.0/node_modules/prisma/build/index.js:91586:8)
    at LineStream2.Transform._write (node:internal/streams/transform:184:23)

```

### Environment & setup

- OS: MacOS
- Database:  MySQL
- Node.js version: v16.14.0
- NextJS version: 12.3.0
- MySQL version: 8.0.30

### Prisma Version

```
4.4.0
```

**Comment by Jolg42** [comment]
@codingholt Did you figure out how to resolve this? I'm curious to know what was the problem 👀

**Comment by codingholt** [comment]
I don't exactly know what was the problem, but I did a new clean install of mysql, and it just worked as expected. So it was probably a configuration issue

**Comment by janpio** [comment]
Probably: https://github.com/prisma/prisma/issues/16886
