### ISSUE TITLE
Updating a one to many not working...

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#15701]
### Discussed in https://github.com/prisma/prisma/discussions/14433

<div type='discussions-op-text'>

<sup>Originally posted by **MarcGodard** July 22, 2022</sup>
So here is my model:

```
model Commentaries {
  id          String     @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  active      Boolean    @default(false)
  locale      String     @default("en")
  title       String
  description String
  author      String
  link        String
  contents    Contents[]
  category    Categories @relation(fields: [categoryId], references: [id])
  categoryId  String     @db.Uuid
  tags        String[]
  published   DateTime?
  user        Users      @relation(fields: [userId], references: [id])
  userId      String     @db.Uuid
  createdAt   DateTime   @default(now())
  updatedAt   DateTime   @default(now())
}

model Contents {
  id           String        @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  title        String?
  description  String?
  link         String?       @unique
  contentType  String
  content      String
  commentaries Commentaries? @relation(fields: [commentaryId], references: [id])
  commentaryId String?       @db.Uuid
  streams      Streams?      @relation(fields: [streamId], references: [id])
  streamId     String?       @db.Uuid
  displayOrder Int           @default(0)
  createdAt    DateTime      @default(now())
  updatedAt    DateTime      @default(now())
}

model Streams {
  id          String     @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  active      Boolean    @default(false)
  locale      String     @default("en")
  name        String
  description String
  contents    Contents[]
  createdAt   DateTime   @default(now())
  updatedAt   DateTime   @default(now())
}

model Categories {
  id         String         @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  category   String         @unique
  Commentary Commentaries[]
  createdAt  DateTime       @default(now())
  updatedAt  DateTime       @default(now())
}
```

Here are the errors (includes queries):

```
PrismaClientValidationError: 
Invalid `prisma.commentaries.update()` invocation:

{
  where: {
    id: '6c30348b-0770-42ba-a0a8-9872ef887e91'
  },
  data: {
    active: false,
    locale: 'en',
    title: 'test',
    description: 'test',
    author: 'test',
    link: 'test-DnVS7',
    tags: [
      'test'
    ],
    published: null,
    createdAt: '2022-07-22T00:49:40.800Z',
    updatedAt: new Date('2022-07-22T01:03:51.341Z'),
    contents: {
      set: [],
      create: [],
      update: [
        {
          where: {
            id: 'cb4dca80-d006-4cf9-9f14-395c1ed9a77c'
          },
          data: {
            title: null,
            description: null,
            link: null,
            contentType: 'quill',
            content: '<p><strong><em><u>test</u></em></strong></p>',
            commentaryId: '6c30348b-0770-42ba-a0a8-9872ef887e91',
            ~~~~~~~~~~~~
            streamId: null,
            displayOrder: 1,
            createdAt: '2022-07-22T00:49:40.800Z',
            updatedAt: '2022-07-22T00:49:40.800Z'
          }
        },
        {
          where: {
            id: '552c6641-a1cd-41e3-aa58-5b1bc4691299'
          },
          data: {
            title: null,
            description: null,
            link: null,
            contentType: 'text',
            content: 'test',
            commentaryId: '6c30348b-0770-42ba-a0a8-9872ef887e91',
            ~~~~~~~~~~~~
            streamId: null,
            displayOrder: 2,
            createdAt: '2022-07-22T00:49:40.800Z',
            updatedAt: '2022-07-22T00:49:40.800Z'
          }
        }
      ]
    },
    category: {
      connect: {
        id: '0fd4a1c5-3434-456b-ac60-64a45bbbb0a7'
      }
    }
  }
}

Unknown arg `commentaryId` in data.contents.update.0.data.commentaryId for type ContentsUncheckedUpdateWithoutCommentariesInput. Available args:

type ContentsUncheckedUpdateWithoutCommentariesInput {
  id?: String | StringFieldUpdateOperationsInput
  title?: String | NullableStringFieldUpdateOperationsInput | Null
  description?: String | NullableStringFieldUpdateOperationsInput | Null
  link?: String | NullableStringFieldUpdateOperationsInput | Null
  contentType?: String | StringFieldUpdateOperationsInput
  content?: String | StringFieldUpdateOperationsInput
  streamId?: String | NullableStringFieldUpdateOperationsInput | Null
  displayOrder?: Int | IntFieldUpdateOperationsInput
  createdAt?: DateTime | DateTimeFieldUpdateOperationsInput
  updatedAt?: DateTime | DateTimeFieldUpdateOperationsInput
}
```

and if I delete the `commentaryId` it is complaining about:

```
PrismaClientKnownRequestError: 
Invalid `prisma.commentaries.update()` invocation:


  Query interpretation error. Error for binding '8': AssertionError("Expected a valid parent ID to be present for nested update to-one case.")
    at RequestHandler.handleRequestError (/home/marcgodard/Documents/Github/guber/node_modules/@prisma/client/runtime/index.js:28658:13)
    at RequestHandler.request (/home/marcgodard/Documents/Github/guber/node_modules/@prisma/client/runtime/index.js:28640:12)
    at async consumer (/home/marcgodard/Documents/Github/guber/node_modules/@prisma/client/runtime/index.js:29618:18)
    at async PrismaClient._request (/home/marcgodard/Documents/Github/guber/node_modules/@prisma/client/runtime/index.js:29639:16)
    at async POST (/home/marcgodard/Documents/Github/guber/src/routes/api/commentaries.js:131:14)
    at async render_endpoint (file:///home/marcgodard/Documents/Github/guber/.svelte-kit/runtime/server/index.js:282:19)
    at async resolve (file:///home/marcgodard/Documents/Github/guber/.svelte-kit/runtime/server/index.js:3439:11)
    at async Object.handle (/marcgodard/Documents/Github/guber/src/hooks.js:48:10)
    at async respond (file:///home/marcgodard/Documents/Github/guber/.svelte-kit/runtime/server/index.js:3384:20)
    at async file:///home/marcgodard/Documents/Github/guber/node_modules/@sveltejs/kit/dist/vite.js:2329:22 {
  code: 'P2016',
  clientVersion: '4.1.0',
  meta: {
    details: `Error for binding '8': AssertionError("Expected a valid parent ID to be present for nested update to-one case.")`
  }
}

```

I am at a lost of what i am doing wrong.</div>

**Comment by pantharshit00** [comment]
I can reproduce the above problem:
```
yarn start                                                                                                                                                       ─╯
yarn run v1.22.17
$ ts-node main.ts
/Users/harshitpant/code/reproductions/issue-14433/node_modules/@prisma/client/runtime/index.js:30852
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.commentaries.update()` invocation in
/Users/harshitpant/code/reproductions/issue-14433/main.ts:6:42

  3 async function main() {
  4   const prisma = new PrismaClient();
  5 
→ 6   const data = await prisma.commentaries.update(
Query interpretation error. Error for binding '1': AssertionError("Expected a valid parent ID to be present for nested update to-one case.")
    at RequestHandler.handleRequestError (/Users/harshitpant/code/reproductions/issue-14433/node_modules/@prisma/client/runtime/index.js:30852:13)
    at RequestHandler.request (/Users/harshitpant/code/reproductions/issue-14433/node_modules/@prisma/client/runtime/index.js:30835:12)
    at async PrismaClient._request (/Users/harshitpant/code/reproductions/issue-14433/node_modules/@prisma/client/runtime/index.js:31813:16)
    at async main (/Users/harshitpant/code/reproductions/issue-14433/main.ts:6:16) {
  code: 'P2016',
  clientVersion: '4.5.0-dev.16',
  meta: {
    details: `Error for binding '1': AssertionError("Expected a valid parent ID to be present for nested update to-one case.")`
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
