### ISSUE TITLE
Foreign Key Constraint - Create Record

### ISSUE THREAD

**Issue by TehIvan** [prisma/prisma#15722]
### Bug description

Trying to create a record of Model "Commission"

Code: 
`        this.client.db.commission.create({
            data: {
                channelId: "a",
                department: "a",
                details: ["Detail1"],
                roleId: "b",
                clientUserId: "a",
            }
        }).then(comm => {
            console.log(comm)
        })`

Error:
private async loadTickets() {
→ 12     this.client.db.commission.create(
Foreign key constraint failed on the field: `clientUserId`
    at RequestHandler.handleRequestError (C:\Users\josep\OneDrive\Desktop\Bots\Navi\node_modules\@prisma\client\runtime\index.js:29909:13)
    at RequestHandler.request (C:\Users\josep\OneDrive\Desktop\Bots\Navi\node_modules\@prisma\client\runtime\index.js:29892:12)
    at async PrismaClient._request (C:\Users\josep\OneDrive\Desktop\Bots\Navi\node_modules\@prisma\client\runtime\index.js:30864:16) {
  code: 'P2003',
  clientVersion: '4.3.1',
  meta: { field_name: 'clientUserId' }
}

### How to reproduce

Run the code linked above, attempting to create a record that has a relational field.

### Expected behavior

A record is created

### Prisma information

datasource db {
  provider = "mysql"
  url      = ""
}

model Commission {
  id           Int         @unique @default(autoincrement())
  clientUserId       String
  channelId    String
  department   String
  roleId       String
  details      Json
  freelancerId String?
  managerId    String?
  Freelancer   Freelancer? @relation(fields: [freelancerId], references: [userId])
  Manager      Manager?    @relation(fields: [managerId], references: [userId])
  Client       Client?      @relation(fields: [clientUserId], references: [userId])
}

model Profile {
  userId     String      @unique
  Freelancer Freelancer?
  Client     Client?
  Manager    Manager?
}

model Manager {
  userId      String       @unique
  Profile     Profile?     @relation(fields: [userId], references: [userId])
  Commissions Commission[]
}

model Freelancer {
  userId      String       @unique
  portfolio   String       @default("No portfolio!")
  timezone    String?
  paypal      String       @default("No paypal set!")
  Profile     Profile?     @relation(fields: [userId], references: [userId])
  Commissions Commission[]
}

model Client {
  userId      String       @unique
  Profile     Profile?     @relation(fields: [userId], references: [userId])
  Commissions Commission[]
}

### Environment & setup

Windows 11, Node 16

### Prisma Version

prisma                  : 4.3.1
@prisma/client          : 4.3.1
Current platform        : windows

**Comment by Jolg42** [comment]
Did you check that the `Client` exists? Maybe this errored because you tried to reference a non existing `Client` with `clientUserId`

**Comment by Jolg42** [comment]
No not with that query,
You can use the nested API with `connectOrCreate` to either connect if already existing or create it if not

```ts
    await prisma.customer.create({
      data: {
        channelId: "a",
        department: "a",
        details: ["Detail1"],
        roleId: "b",
        client: {
          connectOrCreate: {
            create: {
              userId: "a",
            },
            where: {
              userId: "a",
            },
          },
        },
      },
    });
```


See https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#connectorcreate

**Comment by TehIvan** [comment]
I believe I tried that already, but I’ll try it again when I am home.
Thank you, will let you know.
