### ISSUE TITLE
uuid_to_bin function with swap flag cause Null constraint error in MySQL in prisma v4

### ISSUE THREAD

**Issue by sidvenu** [prisma/prisma#15727]
### Bug description

If I use `uuid_to_bin` function along with the 2nd parameter swap flag in `dbgenerated`, when I create a new row, I get a null-constraint error.

### How to reproduce

Use Prisma v4.4:

✅ no error:

model A {
  id String @id @default(dbgenerated("(uuid())")) @db.VarChar(36)
}
❌ error:

model B {
  id Bytes @id @default(dbgenerated("(uuid_to_bin(uuid(), 1))")) @db.Binary(16)
}

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model A {
  id             Bytes @id @default(dbgenerated("(uuid_to_bin(uuid(), 1))")) @db.Binary(16)
}
```

```ts
export const test = async () => {
  await prisma.a.create({ data: {} });
}
```

### Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: v16.17.1

### Prisma Version

```
prisma                  : 4.4.0
@prisma/client          : 4.4.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt f352a33b70356f46311da8b00d83386dd9f145d6 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.4.0-66.f352a33b70356f46311da8b00d83386dd9f145d6
Default Engines Hash    : f352a33b70356f46311da8b00d83386dd9f145d6
Studio                  : 0.474.0
Preview Features        : interactiveTransactions
```

**Comment by janpio** [comment]
Did you fully migrate your database with `db push` or `migrate` commands before trying to use Prisma Client with a `create()`?

**Comment by Druue** [comment]
Hey @sidvenu, could you please clarify which version of `MySQL` you're using and also send any (SQL) error logs, cheers!

**Comment by aqrln** [comment]
I also wasn't able to reproduce this neither with latest Prisma nor with 4.4.0. The schema and the query from the report produce the following result without any errors:

```
{ id: <Buffer 11 ed 4b b0 cd f4 ef 23 a7 68 02 42 ac 12 00 02> }
```

In addition to what was requested in the comment above, could you please also check if the version of Prisma you use at runtime is what you expect it to be?

```ts
 // @ts-ignore
console.log(prisma._clientVersion)
```

**Comment by sidvenu** [comment]
Hey folks,

So I copy pasted the schema that is error-ing out wrongly. Here's the erroring out schema:

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["interactiveTransactions"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model A {
  id             Bytes @id @default(dbgenerated("(uuid_to_bin(uuid(), true))")) @db.Binary(16)
}
```

I realised substituting `true` for the value `1` makes it work perfectly in my local - but true and 1 from a MySQL perspective should be the same.

I can close this issue because `dbgenerated("(uuid_to_bin(uuid(), 1))")` works for me - but we potentially might want to keep this issue open to tackle `dbgenerated("(uuid_to_bin(uuid(), true))")` not functioning as expected.

**Comment by janpio** [comment]
If we can reproduce with `true`, that is certainly something worth fixing.

**Comment by sidvenu** [comment]
Fwiw, `bin_to_uuid(uuid_to_bin(uuid(), 1), 0)` does not work either. I use this expression to store UUIDs with time-high and time-low swapped, but as VarChar. In this case, the schema was:

```prisma
model A {
  id    String @id @default(dbgenerated("(bin_to_uuid(uuid_to_bin(uuid(), 1), 0))")) @db.VarChar(36)
}
```

**Comment by Druue** [comment]
Reproduced on Prisma 4.5.0 w/ MySQL 8, macos -- repo : https://github.com/Druue/prisma-debug/tree/repro/uuid_to_bin
```prisma
model B {
  id Bytes @id @default(dbgenerated("(uuid_to_bin(uuid(), 1))")) @db.Binary(16)
}
```

```js
prisma:query BEGIN
prisma:query SELECT uuid_to_bin(uuid(), 1) AS `id`
prisma:query SELECT `prisma`.`A`.`id` FROM `prisma`.`A` WHERE 1=1 LIMIT ? OFFSET ?
null // console.log(a);
prisma:query INSERT INTO `prisma`.`A` (`id`) VALUES (?)
prisma:query SELECT `prisma`.`A`.`id` FROM `prisma`.`A` WHERE `prisma`.`A`.`id` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
```
----
```prisma
model A {
  id Bytes @id @default(dbgenerated("(uuid_to_bin(uuid(), true))")) @db.Binary(16)
}
```

```js
prisma:query SELECT `prisma`.`A`.`id` FROM `prisma`.`A` WHERE 1=1 LIMIT ? OFFSET ?
{ id: <Buffer 11 ed 4f f8 0f f3 e7 b9 b9 2c 02 42 ac 14 00 02> }
prisma:query BEGIN
prisma:query INSERT INTO `prisma`.`A` (`id`) VALUES (?)
prisma:query ROLLBACK
.../node_modules/@prisma/client/runtime/index.js:30873
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.a.create()` invocation in
.../index.ts:16:18

  13 // prisma.$use
  14 
  15 export const populate = async () => {
→ 16   await prisma.a.create(
Null constraint violation on the fields: (`id`)
    at RequestHandler.handleRequestError (/node_modules/@prisma/client/runtime/index.js:30873:13)
    at RequestHandler.request (.../node_modules/@prisma/client/runtime/index.js:30856:12)
    at async PrismaClient._request (/node_modules/@prisma/client/runtime/index.js:31836:16) {
  code: 'P2011',
  clientVersion: '4.5.0',
  meta: { constraint: [ 'id' ] }
}
```
----
```prisma
model A {
  id String @id @default(dbgenerated("(bin_to_uuid(uuid_to_bin(uuid(), 1), 0))")) @db.VarChar(36)
}
```

```js
prisma:query BEGIN
prisma:query INSERT INTO `prisma`.`A` (`id`) VALUES (?)
prisma:query ROLLBACK
.../node_modules/@prisma/client/runtime/index.js:30873
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.a.create()` invocation in
.../index.ts:16:18

  13 // prisma.$use
  14 
  15 export const populate = async () => {
→ 16   await prisma.a.create(
Null constraint violation on the fields: (`id`)
    at RequestHandler.handleRequestError (.../node_modules/@prisma/client/runtime/index.js:30873:13)
    at RequestHandler.request (.../node_modules/@prisma/client/runtime/index.js:30856:12)
    at async PrismaClient._request (.../node_modules/@prisma/client/runtime/index.js:31836:16) {
  code: 'P2011',
  clientVersion: '4.5.0',
  meta: { constraint: [ 'id' ] }
}
```
