### ISSUE TITLE
Prisma Client: on MongoDB many-to-many relations: Unexpected results when using `@map` on the scalar list of referenced IDs

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#15776]
### Bug description

`@map` should not change the result of a query, as it only changes the name of the document field used in the database.

https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#map
> Maps a field name or enum value from the Prisma schema to a column or document field with a different name in the database. If you do not use @map, the Prisma field name matches the column name or document field name exactly.

But when `@map` on the scalar list of referenced IDs, here categoryIDs and postIDs, we can observe unexpected results.

```
yarn jest
 FAIL  ./spec.test.ts
  MongoDB
    ✕ [create] create post [nested] [create] categories [nested] [create] category should succeed (68 ms)
    ✕ [update] (post) optional boolean field should succeed (78 ms)
    ✕ [delete] post should succeed (72 ms)

  ● MongoDB › [create] create post [nested] [create] categories [nested] [create] category should succeed

    expect(received).toEqual(expected) // deep equality

    - Expected  - 3
    + Received  + 1

      Array [
        Object {
    -     "categoryIDs": Array [
    -       "1",
    -     ],
    +     "categoryIDs": Array [],
          "id": "1",
          "published": null,
        },
      ]

      71 |     expect(
      72 |       await prisma.postManyToMany.findMany({ orderBy: { id: "asc" } })
    > 73 |     ).toEqual([
         |       ^
      74 |       {
      75 |         id: "1",
      76 |         categoryIDs: ["1"],

      at Object.toEqual (spec.test.ts:73:7)

  ● MongoDB › [update] (post) optional boolean field should succeed

    expect(received).toEqual(expected) // deep equality

    - Expected  - 8
    + Received  + 2

      Array [
        Object {
    -     "categoryIDs": Array [
    -       "1-cat-a",
    -       "1-cat-b",
    -     ],
    +     "categoryIDs": Array [],
          "id": "1",
          "published": true,
        },
        Object {
    -     "categoryIDs": Array [
    -       "2-cat-a",
    -       "2-cat-b",
    -     ],
    +     "categoryIDs": Array [],
          "id": "2",
          "published": null,
        },
      ]

      103 |     expect(
      104 |       await prisma.postManyToMany.findMany({ orderBy: { id: "asc" } })
    > 105 |     ).toEqual([
          |       ^
      106 |       {
      107 |         id: "1",
      108 |         // The update

      at Object.toEqual (spec.test.ts:105:7)

  ● MongoDB › [delete] post should succeed

    expect(received).toEqual(expected) // deep equality

    - Expected  - 4
    + Received  + 1

      Array [
        Object {
    -     "categoryIDs": Array [
    -       "2-cat-a",
    -       "2-cat-b",
    -     ],
    +     "categoryIDs": Array [],
          "id": "2",
          "published": null,
        },
      ]

      155 |     expect(
      156 |       await prisma.postManyToMany.findMany({ orderBy: { id: "asc" } })
    > 157 |     ).toEqual([
          |       ^
      158 |       {
      159 |         id: "2",
      160 |         categoryIDs: ["2-cat-a", "2-cat-b"],

      at Object.toEqual (spec.test.ts:157:7)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 3 total
Snapshots:   0 total
Time:        0.418 s, estimated 1 s
Ran all test suites.
```

### How to reproduce

- git clone TODO
- yarn
- Set `DATABASE_URL` to a replica set instance
- yarn prisma generate
- yarn jest

### Expected behavior

Test should pass.

In `schema.prisma` removing the 2 `@map`, makes the tests pass.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

// Here is the many to many relation for MongoDB from our docs 
// https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#mongodb
// - relation fields on both sides, that each have a @relation attribute, with mandatory fields and references arguments
// - a scalar list of referenced IDs on each side, with a type that matches the ID field on the other side

// 
// Tests are passing without @map("categoryIDsAtMap") & @map("postIDsAtMap")
// Tests are failing with @map 
// When @map is on the scalar list of referenced IDs, here categoryIDs and postIDs
// 

model PostManyToMany {
  id          String               @id @map("_id")
  categoryIDs String[]             @map("categoryIDsAtMap")
  categories  CategoryManyToMany[] @relation(fields: [categoryIDs], references: [id])
  published   Boolean?
}

model CategoryManyToMany {
  id        String           @id @map("_id")
  postIDs   String[]         @map("postIDsAtMap")
  posts     PostManyToMany[] @relation(fields: [postIDs], references: [id])
  published Boolean?
}
```

```ts
// Add your code using Prisma Client
See reproduction repo
```

### Environment & setup

- OS: macoOS
- Database: MongoDB 
- Node.js version: v16.16.0

### Prisma Version

```
prisma                  : 4.5.0-dev.33
@prisma/client          : 4.5.0-dev.33
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 391c653df16840951b0b755c8c7a157da82eea16 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 391c653df16840951b0b755c8c7a157da82eea16 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 391c653df16840951b0b755c8c7a157da82eea16 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 391c653df16840951b0b755c8c7a157da82eea16 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.5.0-31.391c653df16840951b0b755c8c7a157da82eea16
Default Engines Hash    : 391c653df16840951b0b755c8c7a157da82eea16
Studio                  : 0.475.0
```

**Comment by Jquery-animate-low-incom** [comment]
https://express-graphql.github.io/2Gbpvi5/



I deduced it
