### ISSUE TITLE
Prisma client won't generate and reports mismatch after upgrade to v4.5.0

### ISSUE THREAD

**Issue by macklinhrw** [prisma/prisma#15924]
### Bug description

I was updating packages,
I updated Prisma from v4.4.0 -> v4.5.0
Then, I used `prisma generate` and the generated client stopped working, and it says there is a prisma version mismatch (prisma = 4.5.0 vs @prisma/client = 4.4.0, even though when I run prisma --version it shows both are at 4.5.0).

I tried clearing my node modules and reinstalling, but after that didn't work I tried clearing my pnpm store and reinstalling, but that didn't work either.

I tried downgrading to v4.4.0, which didn't work either.

I'm running a turbo repo and cleared the node_modules in all locations, and reinstalled using the above method.

### How to reproduce

1. use `pnpm prisma generate` after updating from 4.4.0
2. attempt to import types or make queries
3. see error image

### Expected behavior

Prisma client is generated correctly and able to be used.

### Prisma information

![image](https://user-images.githubusercontent.com/19892721/197130272-92a3ee15-020b-4f50-9b7b-f3864fe1461b.png)

![image](https://user-images.githubusercontent.com/19892721/197130390-d386a540-64fc-4756-98c3-8eb4e48a44f8.png)

### Environment & setup

- OS: Fedora
- Database: MySQL (postgres)
- Node.js version: v16.14.0

![image](https://user-images.githubusercontent.com/19892721/197129053-bdb52e3b-d18d-4d9f-b111-2916f9577ade.png)

### Prisma Version

![image](https://user-images.githubusercontent.com/19892721/197129053-bdb52e3b-d18d-4d9f-b111-2916f9577ade.png)

**Comment by macklinhrw** [comment]
![image](https://user-images.githubusercontent.com/19892721/197253679-583704b8-bca6-4271-bea6-f6911f61c060.png)

I reverted the changes using git, created a fresh branch, did a fresh install of both `prisma` and `@prisma/client` and here is the result. Thanks for the help!

![image](https://user-images.githubusercontent.com/19892721/197254013-950d705c-77df-4a27-83ba-4eba9a21ffc8.png)

**Update**:

Strange, I just stashed the changes, and I'm still getting the same error...

![image](https://user-images.githubusercontent.com/19892721/197254775-47c41d85-522e-4dd8-b22c-efa44371d887.png)

I removed node_modules and reinstalled then it went away,
strange :thinking: 

**Before updating and generating**:
![image](https://user-images.githubusercontent.com/19892721/197256201-7009e554-33df-48c6-a837-7efa0e84c9f7.png)

**After updating and generating** (with version mismatch error):
![image](https://user-images.githubusercontent.com/19892721/197255906-411b8c42-d31e-4ab1-abd9-d343f0098f23.png)

**Comment by macklinhrw** [comment]
**Another update**:
It worked fine after I tried installing and generating with yarn, so I suppose it's a pnpm problem

**Comment by wladiston** [comment]
Having the same issue with NPM on a turborepo. Had to clean cache, remove all node_modules folders and pin `4.4.0` version to make it work

**Comment by delight** [comment]
I can confirm that the issue remains in prisma version 4.6.1  with the following error message:

`npm ERR! Cannot read properties of null (reading 'matches')`

npm / npx works fine ... so it seems to be a problem only appearing in cobination with pnpm 

pnpm -v
7.17.0
node -v
v18.12.1

Stacktrace:
```
pnpx prisma generate 
.../Library/pnpm/store/v3/tmp/dlx-14877  |   +2 +
.../Library/pnpm/store/v3/tmp/dlx-14877  | Progress: resolved 2, reused 2, downloaded 0, added 2, done
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/koko/.npm/_logs/2022-11-25T18_03_13_916Z-debug-0.log
Error: Command failed with exit code 1: npm install @prisma/client@4.6.1
 ERROR  Command failed with exit code 1: /Users/koko/Library/pnpm/store/v3/tmp/dlx-14877/node_modules/.bin/prisma generate

pnpm: Command failed with exit code 1: /Users/koko/Library/pnpm/store/v3/tmp/dlx-14877/node_modules/.bin/prisma generate
    at makeError (/Users/koko/.config/yarn/global/node_modules/pnpm/dist/pnpm.cjs:22437:17)
    at handlePromise (/Users/koko/.config/yarn/global/node_modules/pnpm/dist/pnpm.cjs:23008:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/Users/koko/.config/yarn/global/node_modules/pnpm/dist/pnpm.cjs:200957:7)
    at async /Users/koko/.config/yarn/global/node_modules/pnpm/dist/pnpm.cjs:208255:21
    at async main (/Users/koko/.config/yarn/global/node_modules/pnpm/dist/pnpm.cjs:208226:34)
    at async runPnpm (/Users/koko/.config/yarn/global/node_modules/pnpm/dist/pnpm.cjs:208450:5)
    at async /Users/koko/.config/yarn/global/node_modules/pnpm/dist/pnpm.cjs:208442:7
```

**Comment by delight** [comment]
works fine in 4.6.1 as long as you do a pnpm i @prisma/client before running generate ( which is also run on every migrate )
