### ISSUE TITLE
Error when trying to implement a One to Many ( Unique constraint failed on the constraint )

### ISSUE THREAD

**Issue by Niwau** [prisma/prisma#15984]
### Bug description

I am trying to make a **one to many** relation, where a **user** can report many **bugs**. But when I try to make a user post bugs this error occurs: **Unique constraint failed on the constraint: Bug_authorId_key**

![image](https://user-images.githubusercontent.com/85759155/197805585-ccbae3a8-4fd3-4e69-a090-f59e8174182d.png)

### How to reproduce

1. Create two models (user, bug)
2. Create a one-to-many relation between user-bug
3. Try make a user create more than one bug

### Expected behavior

The user many posts.

### Prisma information

```ts
model User {
  id Int @id @default(autoincrement())
  name String 
  email String @unique
  password String
  role Role @default(User)
  bugs Bug[] 
}

model Bug {
  id Int @id @default(autoincrement())
  title String
  description String
  status Status
  author User @relation(fields: [authorId], references: [id])
  authorId Int 
}

enum Role {
  User
  Admin
}

enum Status {
  Solved
  High
  Medium
  Low
}
```

### Environment & setup

- OS: Windows
- Database: MySQL
- Node.js version: v16.16.0

### Prisma Version

```
prisma                  : 4.5.0
@prisma/client          : 4.5.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.5.0-43.0362da9eebca54d94c8ef5edd3b2e90af99ba452
Default Engines Hash    : 0362da9eebca54d94c8ef5edd3b2e90af99ba452
Studio                  : 0.476.0
```

**Comment by garrensmith** [comment]
@Niwau can you share the code you are running for this.

**Comment by Niwau** [comment]
```ts
const bug = await prisma.bug.create({
    data: {
      title: req.body.title,
      status: req.body.status,
      description: req.body.description,
      author: {
        connect: {
          id: req.body.authorId
        }
      }
    }
  })
```

**Comment by jkomyno** [comment]
## Reproduction

We cannot reproduce this problem with `mysql:8` with the information provided so far. Probably the database schema wasn't aligned to the Prisma schema which resulted in this weird error appearing.

Consider the following Prisma schema:

```prisma
# ./prisma/schema.prisma

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id       Int    @id @default(autoincrement())
  name     String
  email    String @unique
  password String
  role     Role   @default(User)
  bugs     Bug[]
}

model Bug {
  id          Int    @id @default(autoincrement())
  title       String
  description String
  status      Status
  author      User   @relation(fields: [authorId], references: [id])
  authorId    Int
}

enum Role {
  User
  Admin
}

enum Status {
  Solved
  High
  Medium
  Low
}
```

and the following `docker-compose.yml` file:

```yml
# ./docker/docker-compose.yml

version: '3.7'

services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=tests
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    ports:
      - '5432:5432'

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tests
      - MYSQL_USER=prisma
    ports:
      - '3306:3306'
```

We define the following environment variables:

```console
export TEST_POSTGRES_URI="postgres://prisma:prisma@localhost:5432/tests"
export TEST_MYSQL_URI="mysql://root:root@localhost:3306/tests"
export DATABASE_URL="$TEST_MYSQL_URI"
```

We run the following:
- Start the `mysql` database instance via `docker-compose -f docker/docker-compose.yml up mysql`
- Write the Prisma schema to the database via `npx prisma@4.5.0 db push`

We then run the following `@prisma/client` script:

```typescript
import { PrismaClient } from '@prisma/client'

export const prisma = new PrismaClient()

async function main() {
  await prisma.bug.create({
    data: {
      title: 'Issue #15984',
      status: 'Medium',
      description: 'Some bug description',
      author: {
        connect: {
          id: 1,
        }
      }
    }
  })
}

main()
```

which results in the following failure, as we're trying to connect a `Bug` to a not-yet existing `User`:

```console
Invalid `prisma.bug.create()` invocation in
/Users/jkomyno/work/prisma/reprod-15200/index.ts:13:31

  10    description: 'Some bug description',
  11 } as const
  12 
→ 13 const bug = await prisma.bug.create(
An operation failed because it depends on one or more records that were required but not found. No 'User' record(s) (needed to inline the relation on 'Bug' record(s)) was found for a nested connect on one-to-many relation 'BugToUser'.
    at RequestHandler.handleRequestError (/.../@prisma/client/runtime/index.js:30873:13)
    at RequestHandler.request (/.../@prisma/client/runtime/index.js:30856:12)
    at async PrismaClient._request (/.../@prisma/client/runtime/index.js:31836:16)
    at async main (/.../index.ts:13:14) {
  code: 'P2025',
  clientVersion: '4.5.0',
  meta: {
    cause: "No 'User' record(s) (needed to inline the relation on 'Bug' record(s)) was found for a nested connect on one-to-many relation 'BugToUser'."
  }
}
```

We then change the `@prisma/client` script to the following:

```typescript
import { PrismaClient } from '@prisma/client'

export const prisma = new PrismaClient()

async function main() {
  await prisma.user.create({
    data: {
      id: 1,
      email: 'name.surname@prisma.io',
      password: '<A_VERY_STRONG_PASSWORD>',
      name: 'Name Surname',
    },
  })
  await prisma.bug.create({
    data: {
      title: 'Issue #15984',
      status: 'Medium',
      description: 'Some bug description',
      author: {
        connect: {
          id: 1,
        }
      }
    }
  })
}

main()
```

This works as intended, and creates exactly 1 `User` entry and 1 `Bug` entry.
