### ISSUE TITLE
`Can't write to /.../node_modules/prisma2/ please make sure you install "prisma2" with the right permissions.`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1605]
Introspection CI sometimes gets this random error when invoking `prisma2 introspect`:

```
Error: Can't write to /Users/runner/runners/2.164.0/work/introspection-engine-output/introspection-engine-output/node_modules/prisma2/ please make sure you install "prisma2" with the right permissions.
```

2 Examples: https://github.com/prisma/introspection-engine-output/commit/5b8febbe009279614f9fd8d3e2d45b8803070f6e

**Comment by pantharshit00** [comment]
Is there a reproduction that I can use for this? I don't fully understand how introspection-engine-output works internally 😅

**Comment by janpio** [comment]
No, this happens totally random on `prisma2 introspect` calls that worked a thousand times before. We have no idea what is going on and what is causing it.

**Comment by timsuchanek** [comment]
Closing this for now, as apparently the fix we recently added worked 🙂

**Comment by janpio** [comment]
I could just reproduce this on Windows, when running `prisma-test-utils-automation` which runs `prisma2 introspect` under the hood:

```
coppermine Error: Command failed with exit code 1: yarn prisma2 introspect --url=mysql://root:root@localhost:3306/coppermine --print
Error: Can't write to C:\Users\Jan\Documents\prisma-test-utils-automation\node_modules\prisma2\ please make sure you install "prisma2" with the right permissions.
error Command failed with exit code 1.
$ C:\Users\Jan\Documents\prisma-test-utils-automation\node_modules\.bin\prisma2 introspect --url=mysql://root:root@localhost:3306/coppermine --print
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    at makeError (C:\Users\Jan\Documents\prisma-test-utils-automation\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\Jan\Documents\prisma-test-utils-automation\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  shortMessage: 'Command failed with exit code 1: yarn prisma2 introspect --url=mysql://root:root@localhost:3306/coppermine --print',
  command: 'yarn prisma2 introspect --url=mysql://root:root@localhost:3306/coppermine --print',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '$ C:\\Users\\Jan\\Documents\\prisma-test-utils-automation\\node_modules\\.bin\\prisma2 introspect --url=mysql://root:root@localhost:3306/coppermine --print\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.',
  stderr: `Error: Can't write to C:\\Users\\Jan\\Documents\\prisma-test-utils-automation\\node_modules\\prisma2\\ please make sure you install "prisma2" with the right permissions.\n` +
    'error Command failed with exit code 1.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```
