### ISSUE TITLE
RangeError: Invalid count value during prisma generate

### ISSUE THREAD

**Issue by niksrc** [prisma/prisma#16126]
### Bug description

I'm getting the following error every time I run `prisma generate` on GitHub Actions:
```
Error: RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at /home/runner/work/model/node_modules/prisma/build/index.js:92469:13
    at Array.map (<anonymous>)
    at drawBox (/home/runner/work/model/node_modules/prisma/build/index.js:92464:44)
    at printUpdateMessage (/home/runner/work/model/node_modules/prisma/build/index.js:98209:24)
    at main (/home/runner/work/model/node_modules/prisma/build/index.js:98407:5)
```

Here are the full debug logs:
```
2022-10-20T13:19:14.359Z prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt
2022-10-20T13:19:16.455Z prisma:loadEnv  project root found at /home/runner/work/model/package.json
2022-10-20T13:19:16.465Z prisma:tryLoadEnv  Environment variables not found at null
2022-10-20T13:19:16.466Z prisma:tryLoadEnv  Environment variables not found at undefined
2022-10-20T13:19:16.466Z prisma:tryLoadEnv  No Environment variables loaded
Prisma schema loaded from prisma/schema.prisma
2022-10-20T13:19:16.925Z prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /home/runner/work/model/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node
2022-10-20T13:19:16.930Z prisma:getConfig  Loaded Node-API Library
2022-10-20T13:19:16.932Z prisma:getConfig  config data retrieved without errors in getConfigNodeAPI
2022-10-20T13:19:16.949Z prisma:getDMMF  Using CLI Query Engine (Node-API Library) at: /home/runner/work/model/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node
2022-10-20T13:19:16.950Z prisma:getDMMF  Loaded Node-API Library
2022-10-20T13:19:16.974Z prisma:getDMMF  unserialized dmmf result ready
2022-10-20T13:19:16.987Z prisma:getDMMF  dmmf retrieved without errors in getDmmfNodeAPI
2022-10-20T13:19:17.018Z prisma:generator  prismaCLIDir /home/runner/work/model/node_modules/prisma
2022-10-20T13:19:17.018Z prisma:generator  prismaClientDir /home/runner/work/model/node_modules/@prisma/client
2022-10-20T13:19:17.018Z prisma:generator  baseDir /home/runner/work/model/prisma
2022-10-20T13:19:17.022Z prisma:generator  typescriptPath /home/runner/work/model/node_modules/typescript
2022-10-20T13:19:17.238Z prisma:GeneratorProcess  2022-10-20T13:19:17.236Z prisma:client:generator  requiredEngine: libqueryEngine
2022-10-20T13:19:17.238Z prisma:getGenerators  neededVersions {
  "5a48a95376daf2f71f434e8f77a3eeb9943d997b": {
    "engines": [
      "libqueryEngine"
    ],
    "binaryTargets": []
  }
}
2022-10-20T13:19:17.681Z prisma:getGenerators  {
  generatorBinaryPaths: {
    libqueryEngine: {
      'debian-openssl-1.1.x': '/home/runner/work/model/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node'
    }
  }
}
2022-10-20T13:19:17.788Z prisma:GeneratorProcess  2022-10-20T13:19:17.787Z prisma:loadEnv  project root found at /home/runner/work/model/package.json
2022-10-20T13:19:18.081Z prisma:tryLoadEnv  Environment variables not found at null
2022-10-20T13:19:18.081Z prisma:tryLoadEnv  Environment variables not found at undefined
2022-10-20T13:19:18.081Z prisma:tryLoadEnv  No Environment variables loaded

✔ Generated Prisma Client (4.5.0-integration-use-keep-alive-for-node-fetch.1 | library) to ./node_modules/@prisma/client in 326ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
	```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
	```
2022-10-20T13:19:18.140Z prisma:getConfig  Using CLI Query Engine (Node-API Library) at: /home/runner/work/model/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node
2022-10-20T13:19:18.142Z prisma:getConfig  Loaded Node-API Library
2022-10-20T13:19:18.145Z prisma:getConfig  config data retrieved without errors in getConfigNodeAPI
Error: RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at /home/runner/work/model/node_modules/prisma/build/index.js:92469:13
    at Array.map (<anonymous>)
    at drawBox (/home/runner/work/model/node_modules/prisma/build/index.js:92464:44)
    at printUpdateMessage (/home/runner/work/model/node_modules/prisma/build/index.js:98209:24)
    at main (/home/runner/work/model/node_modules/prisma/build/index.js:98407:5)
```

On GitHub Actions, for some strange reason, `paddingRight` is less than `horizontalPadding` resulting in `" ".repeat` getting a negative value:
https://github.com/prisma/prisma/blob/f641d9fb16bfc95605c74af8e4b55ee8814d3559/packages/internals/src/utils/drawBox.ts#L54

I've been using this patch as a workaround to solve the issue:
```
@@ -92463,7 +92463,7 @@ function drawBox({ title, width, height, str, horizontalPadding }) {
   }
   const mappedLines = lines.slice(-height).map((l2) => {
     const lineWidth = Math.min((0, import_string_width.default)(l2), width);
-    const paddingRight = Math.max(width - lineWidth - 2, 0);
+    const paddingRight = Math.max(width - lineWidth - 2, 0, horizontalPadding);
     return `${import_chalk23.default.grey(chars.vertical)}${" ".repeat(horizontalPadding)}${import_chalk23.default.reset(
       (0, import_cli_truncate.default)(l2, width - 2)
     )}${" ".repeat(paddingRight - horizontalPadding)}${import_chalk23.default.grey(chars.vertical)}`;
```

### Expected behavior

`prisma migrate` should not fail with the error

### Environment & setup

- OS: [Ubuntu 20.04 ](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md)
- Database: CockroachDB
- Node.js version: Node 16.10.0
- Package Manager: [yarn berry](https://yarnpkg.com/getting-started)

### Prisma Version

```
prisma                  : 4.5.0-integration-use-keep-alive-for-node-fetch.1
@prisma/client          : 4.5.0-integration-use-keep-alive-for-node-fetch.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 5a48a95376daf2f71f434e8f77a3eeb9943d997b (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 5a48a95376daf2f71f434e8f77a3eeb9943d997b (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 5a48a95376daf2f71f434e8f77a3eeb9943d997b (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 5a48a95376daf2f71f434e8f77a3eeb9943d997b (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.5.0-34.5a48a95376daf2f71f434e8f77a3eeb9943d997b
Default Engines Hash    : 5a48a95376daf2f71f434e8f77a3eeb9943d997b
Studio                  : 0.475.0
```

**Comment by janpio** [comment]
I remember we had an issue about something like this before...

Oh yeah, it was mine! https://github.com/prisma/prisma/issues/9429
