### ISSUE TITLE
Prisma Client regression bug after upgrading to 4.6.0: `findMany` errors with `PANIC: index out of bounds: the len is 0 but the index is 0`

### ISSUE THREAD

**Issue by DarioSiroki** [prisma/prisma#16195]
### Bug description

Panic when executing code provided below

```
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but the index is 0', query-engine/core/src/query_document/mod.rs:74:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/Users/dar0/projects/prisma-demo/node_modules/@prisma/client/runtime/index.js:34310
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.balance.findMany()` invocation in
/Users/dar0/projects/prisma-demo/index.ts:12:20

   9     id: 1,
  10   },
  11 }),
→ 12 prisma.balance.findMany(
PANIC: index out of bounds: the len is 0 but the index is 0
    at RequestHandler.handleRequestError (/Users/dar0/projects/prisma-demo/node_modules/@prisma/client/runtime/index.js:34310:13)
    at RequestHandler.request (/Users/dar0/projects/prisma-demo/node_modules/@prisma/client/runtime/index.js:34293:12)
    at async PrismaClient._request (/Users/dar0/projects/prisma-demo/node_modules/@prisma/client/runtime/index.js:35273:16)
    at async Promise.all (index 1)
    at async main (/Users/dar0/projects/prisma-demo/index.ts:6:30) {
  code: 'GenericFailure',
  clientVersion: '4.6.0',
  meta: undefined
}
```

### How to reproduce

Run the code below

### Prisma information

```prisma
generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["interactiveTransactions"]
}

datasource db {
    provider = "postgresql"
    url      = "postgres://postgres:root@localhost:5432/bug-demo"
}

model client {
    id       Int       @id @default(autoincrement())
    username String    @db.VarChar(100)
    balance  balance[]
}

model balance {
    id       Int    @id @default(autoincrement())
    amount   Int
    clientId Int
    client   client @relation(fields: [clientId], references: [id])
}
```

```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const [client, balances] = await prisma.$transaction([
    prisma.client.findUniqueOrThrow({
      where: {
        id: 1,
      },
    }),
    prisma.balance.findMany(),
  ]);
}

main();

```

### Environment & setup

- OS: macOS, EC2 linux AMI
- Database: Postgres
- Node.js version: 16.15

### Prisma Version

```
prisma                  : 4.6.0
@prisma/client          : 4.6.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2e719efb80b56a3f32d18a62489de95bb9c130e3 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 2e719efb80b56a3f32d18a62489de95bb9c130e3 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 2e719efb80b56a3f32d18a62489de95bb9c130e3 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 2e719efb80b56a3f32d18a62489de95bb9c130e3 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.6.0-53.2e719efb80b56a3f32d18a62489de95bb9c130e3
Default Engines Hash    : 2e719efb80b56a3f32d18a62489de95bb9c130e3
Studio                  : 0.476.0
Preview Features        : interactiveTransactions
```

**Comment by Weakky** [comment]
Hey @DarioSiroki,

We can reproduce this bug. Thanks for reporting 🙏

**Comment by Jolg42** [comment]
Hi @DarioSiroki !

We will prepare a patch release tomorrow.
We'll keep you updated as soon as it's available.

**Comment by DarioSiroki** [comment]
Tried it, works, thanks for the quick fix!

**Comment by Jolg42** [comment]
The official patch is out in [`4.6.1`](https://github.com/prisma/prisma/releases/tag/4.6.1)
