### ISSUE TITLE
Strange thread

### ISSUE THREAD

**Issue by shadoworion** [prisma/prisma#16251]
### Bug description

I don't understand when and where it throws this exception. How can I check it?
Cos if I run my app in debug mode and move row row it works...

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', query-engine/prisma-models/src/field/relation.rs:110:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

OR 

```
thread 'tokio-runtime-worker' panicked at 'Expected weak reference to be valid.', /Users/runner/work/prisma-engines/prisma-engines/query-engine/schema/src/lib.rs:44:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How to reproduce

...

### Environment & setup

- OS: macOS 13.0.1
- Database: PostgreSQL 14
- Node.js version: v18.3.0

### Prisma Version

```
prisma                  : 4.6.1
@prisma/client          : 4.6.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.6.1-3.694eea289a8462c80264df36757e4fdc129b1b32
Default Engines Hash    : 694eea289a8462c80264df36757e4fdc129b1b32
Studio                  : 0.476.0
```

**Comment by janpio** [comment]
Can you shared what triggered this problem, and how you solved it?
