### ISSUE TITLE
Raw parameterized will not search WHERE enum value equals some string

### ISSUE THREAD

**Issue by emanualjade** [prisma/prisma#16361]
### Bug description

There appears to be an issue fetching data with parameterized values using a raw query on a column that is an enum.
UPDATE in comments below. Is typecasting the column necessary?

### Error in Browser
<img width="984" alt="image" src="https://user-images.githubusercontent.com/612095/202867439-2c2cf9f2-cab3-4404-a3c8-6b241896ca22.png">

### Error in Terminal
```
prisma:client  prisma.queryRaw(SELECT * FROM "Post" WHERE "currentStatus" = $1, ["ACTIVELY_LOOKING"]) +2m
  prisma:client  Prisma Client call: +1ms
  prisma:client  Prisma Client call: +4ms
  prisma:client  prisma.$queryRaw({
  query: 'SELECT * FROM "Post" WHERE "currentStatus" = $1',
  parameters: {
    values: '["ACTIVELY_LOOKING"]',
    __prismaRawParameters__: true
  }
}) +2ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  queryRaw(
    query: "SELECT * FROM \"Post\" WHERE \"currentStatus\" = $1"
    parameters: "[\"ACTIVELY_LOOKING\"]"
  )
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +2m
prisma:query SELECT 1
prisma:query SELECT * FROM "Post" WHERE "currentStatus" = $1
  prisma:client:request_handler  PrismaClientKnownRequestError: Raw query failed. Code: `42883`. Message: `db error: ERROR: operator does not exist: "CurrentStatus" = text
HINT: No operator matches the given name and argument types. You might need to add explicit type casts.`
    at prismaGraphQLToJSError (/Users/alexander/Sites/myproject/node_modules/@prisma/client/runtime/index.js:20423:12)
    at LibraryEngine.buildQueryError (/Users/alexander/Sites/myproject/node_modules/@prisma/client/runtime/index.js:27332:12)
    at LibraryEngine.request (/Users/alexander/Sites/myproject/node_modules/@prisma/client/runtime/index.js:27265:22)
    at async RequestHandler.request (/Users/alexander/Sites/myproject/node_modules/@prisma/client/runtime/index.js:30838:24)
    at async Proxy._request (/Users/alexander/Sites/myproject/node_modules/@prisma/client/runtime/index.js:31836:16)
    at async handler (webpack-internal:///(api)/./pages/api/search/[[...params]].ts:24:20)
    at async Object.apiResolver (/Users/alexander/Sites/myproject/node_modules/next/dist/server/api-utils/node.js:367:9)
    at async DevServer.runApi (/Users/alexander/Sites/myproject/node_modules/next/dist/server/next-server.js:474:9)
    at async Object.fn (/Users/alexander/Sites/myproject/node_modules/next/dist/server/next-server.js:736:37)
    at async Router.execute (/Users/alexander/Sites/myproject/node_modules/next/dist/server/router.js:252:36) {
  code: 'P2010',
  clientVersion: '4.5.0',
  meta: {
    code: '42883',
    message: 'db error: ERROR: operator does not exist: "CurrentStatus" = text\n' +
      'HINT: No operator matches the given name and argument types. You might need to add explicit type casts.'
  }
} +2m
  compression gzip compression +2m
error - PrismaClientKnownRequestError:
Invalid `prisma.$queryRaw()` invocation:


Raw query failed. Code: `42883`. Message: `db error: ERROR: operator does not exist: "CurrentStatus" = text
HINT: No operator matches the given name and argument types. You might need to add explicit type casts.`
    at RequestHandler.handleRequestError (/Users/alexander/Sites/myproject/node_modules/@prisma/client/runtime/index.js:30873:13)
    at RequestHandler.request (/Users/alexander/Sites/myproject/node_modules/@prisma/client/runtime/index.js:30856:12)
    at async Proxy._request (/Users/alexander/Sites/myproject/node_modules/@prisma/client/runtime/index.js:31836:16)
    at async handler (webpack-internal:///(api)/./pages/api/search/[[...params]].ts:24:20)
    at async Object.apiResolver (/Users/alexander/Sites/myproject/node_modules/next/dist/server/api-utils/node.js:367:9)
    at async DevServer.runApi (/Users/alexander/Sites/myproject/node_modules/next/dist/server/next-server.js:474:9)
    at async Object.fn (/Users/alexander/Sites/myproject/node_modules/next/dist/server/next-server.js:736:37)
    at async Router.execute (/Users/alexander/Sites/myproject/node_modules/next/dist/server/router.js:252:36)
    at async DevServer.run (/Users/alexander/Sites/myproject/node_modules/next/dist/server/base-server.js:384:29)
    at async DevServer.run (/Users/alexander/Sites/myproject/node_modules/next/dist/server/dev/next-dev-server.js:732:20) {
  code: 'P2010',
  clientVersion: '4.5.0',
  meta: {
    code: '42883',
    message: 'db error: ERROR: operator does not exist: "CurrentStatus" = text\n' +
      'HINT: No operator matches the given name and argument types. You might need to add explicit type casts.'
  },
  page: '/api/search/[[...params]]'
}
```

### How to reproduce

1. Create the model.
2. Create some rows with the appropriate value for currentStatus enum.
3. Attempt to fetch those rows with a raw query using parameterized values like so
```ts
const current = 'ACTIVELY_LOOKING'
const result = await prisma.$queryRawUnsafe(
    `SELECT * FROM "Post" WHERE "currentStatus" = $1`,
    current
  )
```
4. See errors as described above.

### Expected behavior

Expectation is that the query with parameterized value will fetch the appropriate records.

### Prisma information

```prisma
model Post {
  id        String  @id @default(cuid())
  currentStatus       CurrentStatus         @default(ACTIVELY_LOOKING)
}

enum CurrentStatus {
  ACTIVELY_LOOKING
  CASUALLY_LOOKING
}
```

```ts
const current = 'ACTIVELY_LOOKING'
const result = await prisma.$queryRawUnsafe(
    `SELECT * FROM "Post" WHERE "currentStatus" = $1`,
    current
  )
```

### Environment & setup

- OS: macOS 13.0 
- Database: PostgreSQL 14
- Node.js version: v14.20.1
- Prisma version: ^4.5.0

### Prisma Version

```
^4.5.0
```

**Comment by emanualjade** [comment]
Update. I just read in postgres docs that I can do this and it starts working.

Casting to text seems required for parameterized query on enum field 

```
  const result = await prisma.$queryRawUnsafe(
    `SELECT * FROM "Post" WHERE "currentStatus"::text = $1`,
    current
  )
```

 But not required for non-parameterized query like so

```
const result = await prisma.$queryRawUnsafe(
    `SELECT * FROM "Post" WHERE "currentStatus" = '${current}'`
  )
```

Did I stumble on the correct way to do this with the mandatory typecast or should it technically work without the typecast and therefore still a bug?

**Comment by miguelff** [comment]
You did stumble on the correct way of doing this. You could also use the type safe enumeration, but that would also have required the query typecast:

```js
async function main() {
  const result = await prisma.$queryRawUnsafe(
    `SELECT * FROM "Post" WHERE "currentStatus"::text = $1`,
    CurrentStatus.ACTIVELY_LOOKING
  )
}
```

**Comment by ctsstc** [comment]
I wanted to also provide an example using `$queryRaw` with the type safe enumeration, which also required the typecasting.

```typescript
await prisma.$queryRaw`
  SELECT *
  FROM post
  WHERE post.status::text = ${PostStatus.FINISHED}
`
```

**Comment by LavransBjerkestrand** [comment]
If you need to update it seems you have to cast to the enum:

```typescript
await prisma.$queryRaw`
  UPDATE post
  SET post.status = ${PostStatus.PUBLISHED}::"PostStatus"
  WHERE post.status::text = ${PostStatus.FINISHED}
`
```

This doesn't work:
```typescript
await prisma.$queryRaw`
  UPDATE post
  SET post.status::text = ${PostStatus.PUBLISHED}
  WHERE post.status::text = ${PostStatus.FINISHED}
`
```
