### ISSUE TITLE
Incorrect syntax near ')'.

### ISSUE THREAD

**Issue by mikhael-abdallah** [prisma/prisma#16383]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.16.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 4.6.1              |
| Query Engine    | query-engine 694eea289a8462c80264df36757e4fdc129b1b32|
| Database        | undefined|

## Logs
```
prisma:tryLoadEnv Environment variables loaded from /var/src/.env
prisma:tryLoadEnv Environment variables loaded from /var/src/.env
prisma:client dirname /var/src/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /var/src/prisma
prisma:client clientVersion 4.6.1
prisma:client clientEngineType binary
prisma:engine {"cwd":"/var/src/prisma"}
prisma:engine Search for Query Engine in /var/src/node_modules/.prisma/client
prisma:engine Search for Query Engine in /var/src/node_modules/.prisma/client
plusX Execution permissions of /var/src/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
plusX Execution permissions of /var/src/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine {"flags":["--enable-raw-queries","--enable-metrics","--enable-open-telemetry","--port","43721"]}
prisma:engine stdout Starting a mssql pool with 9 connections.
prisma:engine stdout Performing a TLS handshake
prisma:engine stdout Trusting the server certificate without validation.
prisma:engine stdout TLS handshake successful
prisma:engine stdout Database change from 'adm-dbsql-dev' to 'master'
prisma:engine stdout Changed database context to 'adm-dbsql-dev'.
prisma:engine stdout SQL collation changed to windows-1252
prisma:engine stdout Microsoft SQL Server�� version 805502988
prisma:engine stdout Packet size change from '4096' to '4096'
prisma:engine stdout Started query engine http server on http://127.0.0.1:43721
prisma:engine Search for Query Engine in /var/src/node_modules/.prisma/client
plusX Execution permissions of /var/src/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine Client Version: 4.6.1
prisma:engine Engine Version: query-engine 694eea289a8462c80264df36757e4fdc129b1b32
prisma:engine Active provider: sqlserver
prisma:engine Search for Query Engine in /var/src/node_modules/.prisma/client
plusX Execution permissions of /var/src/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine stdout An expression of non-boolean type specified in a context where a condition is expected, near ','.
prisma:engine stdout Incorrect syntax near ')'.
prisma:engine {"error":{"clientVersion":"4.6.1"}}
prisma:engine stdout An expression of non-boolean type specified in a context where a condition is expected, near ','.
prisma:engine stdout Incorrect syntax near ')'.
prisma:engine {"error":{"clientVersion":"4.6.1"}}
prisma:engine stdout An expression of non-boolean type specified in a context where a condition is expected, near ','.
prisma:engine stdout Incorrect syntax near ')'.
prisma:engine {"error":{"clientVersion":"4.6.1"}}
prisma:client:request_handler {"clientVersion":"4.6.1"}
prisma:engine stdout An expression of non-boolean type specified in a context where a condition is expected, near ','.
prisma:engine stdout Incorrect syntax near ')'.
prisma:engine {"error":{"clientVersion":"4.6.1"}}
prisma:engine stdout An expression of non-boolean type specified in a context where a condition is expected, near ','.
prisma:engine stdout Incorrect syntax near ')'.
prisma:engine {"error":{"clientVersion":"4.6.1"}}
prisma:engine stdout An expression of non-boolean type specified in a context where a condition is expected, near ','.
prisma:engine stdout Incorrect syntax near ')'.
prisma:engine {"error":{"clientVersion":"4.6.1"}}
```

## Client Snippet
```ts
await this.prismaService.bok_user_type_accesses.count({
            where: {
              bok_user_types: {
                deactivation_date: null,
              },
            },
          })
```

## Schema
```prisma
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "darwin", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "sqlserver"
  url      = env("DB_URL")
}

model bok_user_types {
  pk_id                  Int                      @id(map: "idx_pk_bok_user_types_id") @default(autoincrement())
  name                   String                   @db.VarChar(100)
  max_days               Int
  max_books              Int
  creation_date          DateTime                 @default(now())
  change_date            DateTime?                @default(now()) @updatedAt
  deactivation_date      DateTime?                @db.DateTime
  bok_user_type_accesses bok_user_type_accesses[]
}

model bok_user_type_accesses {
  pk_id                 Int            @unique(map: "in_un_bok_user_type_accesses_pk_id") @default(autoincrement())
  pfk_bok_user_types_id Int
  bok_user_types        bok_user_types @relation(fields: [pfk_bok_user_types_id], references: [pk_id], onUpdate: NoAction, map: "idx_bok_user_type_accesses_pfk_bok_user_types_id")

  @@id([pfk_bok_user_types_id , pk_id], map: "idx_pk_bok_user_type_accesses")
  @@index([pfk_bok_user_types_id], map: "in_bok_user_type_accesses_pfk_bok_user_types_id")
}
}
```

## Prisma Engine Query
```
query {
  aggregatebok_user_type_accesses(where: {
    bok_user_types: {
      deactivation_date: null
    }
  }) {
    _count {
      _all
    }
  }
}
```

**Comment by tomhoule** [comment]
I just tried to reproduce this issue, and with the same query and schema, I do get a panic but it's a different one. Can you confirm that this is what you get too?

![2023-06-02_14-06-05](https://github.com/prisma/prisma/assets/13155277/79ac1298-0eba-4974-9268-3409b230872f)

**Comment by tomhoule** [comment]
We see the same error you reported above in a previous query in the logs, though.

**Comment by janpio** [comment]
I can confirm a problem with 4.6.1:
```
Invalid `prisma.bok_user_type_accesses.count()` invocation in
C:\Users\Jan\Documents\throwaway\19963\script.js:6:39

  3 const prisma = new PrismaClient({ log: ['query'] })
  4
  5 async function main() {
→ 6   await prisma.bok_user_type_accesses.count(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 4145, state: 1, class: 15, message: "An expression of non-boolean type specified in a context where a condition is expected, near ','.", server: "943cfde6df22", procedure: "", line: 1 }) })
    at RequestHandler.handleRequestError (C:\Users\Jan\Documents\throwaway\19963\node_modules\@prisma\client\runtime\index.js:34314:13)
    at RequestHandler.request (C:\Users\Jan\Documents\throwaway\19963\node_modules\@prisma\client\runtime\index.js:34293:12)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\19963\node_modules\@prisma\client\runtime\index.js:35273:16)
    at async main (C:\Users\Jan\Documents\throwaway\19963\script.js:6:3) {
  clientVersion: '4.6.1'
}
```

**Comment by janpio** [comment]
With the more recent 5.14.0 everything seems to work as expected though:
```
> node .\script.js 
prisma:tryLoadEnv Environment variables not found at null +20ms
prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\16383\.env +2ms
prisma:client checkPlatformCaching:postinstall false +2ms
prisma:client checkPlatformCaching:ciName undefined +1ms
prisma:tryLoadEnv Environment variables not found at null +1ms
prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\16383\.env +0ms
prisma:client dirname C:\Users\Jan\Documents\throwaway\19963\node_modules\.prisma\client +1ms
prisma:client relativePath ../../../prisma +0ms
prisma:client cwd C:\Users\Jan\Documents\throwaway\16383\prisma +1ms
prisma:client clientVersion 5.14.0 +0ms
prisma:client:libraryEngine internalSetup +1ms
prisma:client Prisma Client call: +5ms
prisma:client prisma.bok_user_type_accesses.count({
  select: {
    _count: {
      select: {
        _all: true
      }
    }
  },
  where: {
    bok_user_types: {
      deactivation_date: null
    }
  }
}) +2ms
prisma:client Generated request: +1ms
prisma:client {
  "modelName": "bok_user_type_accesses",
  "action": "aggregate",
  "query": {
    "arguments": {
      "where": {
        "bok_user_types": {
          "deactivation_date": null
        }
      }
    },
    "selection": {
      "_count": {
        "arguments": {},
        "selection": {
          "_all": true
        }
      }
    }
  }
}
 +0ms
prisma:client:libraryEngine sending request, this.libraryStarted: false +2ms
prisma:client:engines:resolveEnginePath enginePath C:\Users\Jan\Documents\throwaway\16383\node_modules\.prisma\client\query_engine-windows.dll.node +3ms
prisma:client:libraryEngine library starting +4ms
prisma:client:libraryEngine library started +39ms
prisma:query SELECT COUNT(*) FROM (SELECT [dbo].[bok_user_type_accesses].[pfk_bok_user_types_id], [dbo].[bok_user_type_accesses].[pk_id] FROM [dbo].[bok_user_type_accesses] LEFT JOIN [dbo].[bok_user_types] AS [j1] ON (([j1].[pk_id] = [dbo].[bok_user_type_accesses].[pfk_bok_user_types_id])) WHERE ([j1].[deactivation_date] IS NULL AND ([j1].[pk_id] IS NOT NULL))) AS [sub]
{ result: 1 }
prisma:client:libraryEngine library stopping +34ms
prisma:client:libraryEngine library stopped +1ms
```
(I created one entry to be returned via `prisma studio` before, so the result is `1`)
