### ISSUE TITLE
_count not existing on some models

### ISSUE THREAD

**Issue by ekwoka** [prisma/prisma#16516]
### Bug description

When trying to use `_count` in an `include` or `select`, sometimes it's not available on the type, and it's unclear why.

To me there isn't any reason why it complains in one and is fine in the other.

### How to reproduce

Not Working:
```js
const listings = await prismaClient.storeListing.findMany({
        include: {
          _count: true,
        },
      });
      
   // model
   model StoreListing {
  id          Int     @id @default(autoincrement())
  name        String?
  description String?
  price       Int
  quantity    Int?
  Image       Image?  @relation(fields: [imageId], references: [id])
  imageId     Int?
  Item        Item    @relation(fields: [itemId], references: [id], onDelete: Cascade)
  itemId      Int
}
```

Working:
```js
const items = await prismaClient.item.findMany({
        include: {
          Image: true,
          _count: true,
        },
      });
      
// model

model Item {
  id                 Int            @id @default(autoincrement())
  name               String
  description        String?
  Image              Image          @relation(fields: [imageId], references: [id])
  imageId            Int
  type               ItemType
  rarity             ItemRarity
  create_on_purchase Boolean        @default(true)
  is_unique          Boolean        @default(false)
  StoreListing       StoreListing[]
  Inventory          Inventory[]
}

```

### Expected behavior

That I can use `_count` in every `findMany`

### Prisma information

Not Working:
```js
const listings = await prismaClient.storeListing.findMany({
        include: {
          _count: true,
        },
      });
      
   // model
   model StoreListing {
  id          Int     @id @default(autoincrement())
  name        String?
  description String?
  price       Int
  quantity    Int?
  Image       Image?  @relation(fields: [imageId], references: [id])
  imageId     Int?
  Item        Item    @relation(fields: [itemId], references: [id], onDelete: Cascade)
  itemId      Int
}
```

Working:
```js
const items = await prismaClient.item.findMany({
        include: {
          Image: true,
          _count: true,
        },
      });
      
// model

model Item {
  id                 Int            @id @default(autoincrement())
  name               String
  description        String?
  Image              Image          @relation(fields: [imageId], references: [id])
  imageId            Int
  type               ItemType
  rarity             ItemRarity
  create_on_purchase Boolean        @default(true)
  is_unique          Boolean        @default(false)
  StoreListing       StoreListing[]
  Inventory          Inventory[]
}

```

### Environment & setup

MacOS, Postgresql

### Prisma Version

```
4.6.1
```

**Comment by OMikkel** [comment]
Same issue, it should work according to the docs but it does not. I believe this is related to the `selectRelationCount` feature.
I am running `Prisma Client 5.2.0`

Code:
```ts
const result = await prisma.order.findMany({
    where: {
        orderDate: {
            gte: new Date(
                new Date(
                    new Date().getFullYear(),
                    new Date().getMonth(),
                    1
                ).setHours(0, 0, 0)
            ),
        },
    },
    include: {
        _count: {
            select: {
                invoice: true,
            },
        },
    },
});
```
TS-Error: `Type '{ _count: { select: { invoice: true; }; }; }' is not assignable to type 'OrderInclude<DefaultArgs>'.
  Object literal may only specify known properties, and '_count' does not exist in type 'OrderInclude<DefaultArgs>'.ts(2322)`

Console Error:
```cmd
PrismaClientUnknownRequestError: 
Invalid `prisma.order.findMany()` invocation:


Unknown nested field '_count' for operation findManyOrder does not match any query.
    at vn.handleRequestError (C:\...\project\node_modules\@prisma\client\runtime\library.js:123:6902)
    at vn.handleAndLogRequestError (C:\...\project\node_modules\@prisma\client\runtime\library.js:123:6119)
    at vn.request (C:\...\project\node_modules\@prisma\client\runtime\library.js:123:5839)
    at async l (C:\...\project\node_modules\@prisma\client\runtime\library.js:128:9763)
    at async getStats (webpack-internal:///(rsc)/./src/app/(dashboard)/dashboard/overview/data/stats.tsx:72:24)
    at async Overview (webpack-internal:///(rsc)/./src/app/(dashboard)/dashboard/overview/page.tsx:22:19) {
  clientVersion: '5.2.0'
}
```

Schema:
```prisma
model Order {
  id Int @id @default(autoincrement())
  companyID Int
  company Company @relation(fields: [companyID], references: [id], onDelete: Cascade, onUpdate: Cascade)
  contactID Int
  contact Contact @relation(fields: [contactID], references: [id], onDelete: Cascade, onUpdate: Cascade)
  productID Int @default(1)
  product Product @relation(fields: [productID], references: [id], onDelete: Cascade, onUpdate: Cascade)
  orderDate DateTime @default(now())
  nextCall DateTime?
  invoice Invoice?
  userID Int
  user User @relation(fields: [userID], references: [id], onDelete: Cascade, onUpdate: Cascade)
  changes String? @db.Text
  comment2 String? @db.Text
}
```

[Image of IDE](https://i.imgur.com/ay6wS6B.png)

**Comment by glebourgeois** [comment]
I got the same issue, on a quite simple model.
Query:
```
const messagesCount = await prisma.SMS.findMany({
                select: {
                    _count: {
                        select: {
                            User: {
                                where: {clerk_organization_id: organizationId}
                            }
                        }
                    }
                }                
            });
```
```
Model
model SMS {
  id           String   @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  head         String?  @db.VarChar(255)
  footer       String?  @db.VarChar(255)
  body         String
  created_at   DateTime @default(now()) @db.Timestamp(6)
  recipient_id String   @db.Uuid
  sender_id    String   @db.Uuid
  success      Boolean
  Patient      Patient  @relation(fields: [recipient_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
  User         User     @relation(fields: [sender_id], references: [id], onDelete: NoAction, onUpdate: NoAction)
}

model User {
  id                    String @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  clerk_id              String  @unique @db.VarChar(255)
  clerk_organization_id String  @db.VarChar(255)
  name                  String? @db.VarChar(255)
  email                 String? @db.VarChar(255)
  SMS                   SMS[]
}
```
The use of this query triggers an error 

> Unknown nested field '_count' for operation findManySMS does not match any query.

clientVersion: 5.4.1

**Comment by oxillix** [comment]
Had the same issue, restarting my dev server fixed the problem.

**Comment by John6Connor** [comment]
same problem with
```
prisma                        : 6.5.0
@prisma/client          : 6.5.0
```

I tried adding "filteredRelationCount" to previewFeatures, but it says the feature is deprecated (and it didn’t work anyway).

**Comment by Serpentarius13** [comment]
I believe it only happens when model is on the "Many" side of One-To-Many relationship
