### ISSUE TITLE
CockroachDB: cannot atomically divide `BigInt` or `Int`

### ISSUE THREAD

**Issue by RobertCraigie** [prisma/prisma#16511]
### Bug description

You cannot atomically `divide` a `BigInt` or `Int` value on CockroachDB. Other atomic operations such as `multiply` can be used successfully.

### How to reproduce

Setup a CockroachDB instance and run the given script.

This error will be thrown:
```
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E22023), message: "unsupported binary operator: <int> / <anyelement> (desired <int>)", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("type_check.go"), line: Some(345), routine: Some("TypeCheck") }) }) })
```

<details>
<summary>Full logs</summary>

```
prisma:info Starting a postgresql pool with 17 connections.
prisma:query BEGIN
prisma:query INSERT INTO "public"."Post" ("id","value") VALUES ($1,$2) RETURNING "public"."Post"."id"
prisma:query SELECT "public"."Post"."id", "public"."Post"."value" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
prisma:query COMMIT
{ id: 'clb1f73s70000uxt1e1ui3sbd', value: 10n }
prisma:query BEGIN
prisma:query SELECT "public"."Post"."id" FROM "public"."Post" WHERE ("public"."Post"."id" = $1 AND 1=1)
prisma:query UPDATE "public"."Post" SET "value" = ("public"."Post"."value" / $1) WHERE ("public"."Post"."id" IN ($2) AND ("public"."Post"."id" = $3 AND 1=1))
prisma:query ROLLBACK
/Users/robert/tmp/prisma-testing/node_modules/@prisma/client/runtime/index.js:34317
      throw new PrismaClientUnknownRequestError(message, this.client._clientVersion);
            ^
PrismaClientUnknownRequestError: 
Invalid `prisma.post.update()` invocation in
/Users/robert/tmp/prisma-testing/index.ts:9:37

  6 const post = await prisma.post.create({ data: { value: 10 } });
  7 console.log(post);
  8 
→ 9 const updated = await prisma.post.update(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E22023), message: "unsupported binary operator: <int> / <anyelement> (desired <int>)", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("type_check.go"), line: Some(345), routine: Some("TypeCheck") }) }) })
    at RequestHandler.handleRequestError (/Users/robert/tmp/prisma-testing/node_modules/@prisma/client/runtime/index.js:34317:13)
    at RequestHandler.request (/Users/robert/tmp/prisma-testing/node_modules/@prisma/client/runtime/index.js:34296:12)
    at async PrismaClient._request (/Users/robert/tmp/prisma-testing/node_modules/@prisma/client/runtime/index.js:35276:16)
    at async main (/Users/robert/tmp/prisma-testing/index.ts:9:19) {
  clientVersion: '4.6.1'
}
```

</details>

### Expected behavior

This script should not result in the client crashing.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
}

datasource client {
  provider = "postgresql"
  url = env("COCKROACHDB_URL")
}

model Post {
  id    String @id @default(cuid())
  value BigInt
}
```

```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({ log: ["query", "info", "error", "warn"] });

async function main() {
  const post = await prisma.post.create({ data: { value: 10 } });
  console.log(post);

  const updated = await prisma.post.update({
    where: { id: post.id },
    data: { value: { divide: 2 } },
  });
  console.log(updated);
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```

### Environment & setup

- OS:  MacOS
- Database:  CockroachDB
- Database Version: `22`
- Node.js version:  `v16.14.2`

### Prisma Version

```
prisma                  : 4.6.1
@prisma/client          : 4.6.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.6.1-3.694eea289a8462c80264df36757e4fdc129b1b32
Default Engines Hash    : 694eea289a8462c80264df36757e4fdc129b1b32
Studio                  : 0.476.0
```

**Comment by RobertCraigie** [comment]
Also interesting that running the same exact query that Prisma runs internally doesn't throw any errors!

```ts
async function main() {
  const post = await prisma.post.create({ data: { value: 10 } });
  console.log(post);

  const count =
    await prisma.$executeRaw`UPDATE "public"."Post" SET "value" = ("public"."Post"."value" / ${2}) WHERE ("public"."Post"."id" IN (${
      post.id
    }) AND ("public"."Post"."id" = ${post.id} AND 1=1))`;
  console.log(count);

  const updated = await prisma.post.findUnique({ where: { id: post.id } });
  console.log(updated);
}
```

Sounds like CockroachDB is interpreting the query parameters in the wrong way...

**Comment by RobertCraigie** [comment]
This also seems to apply to to pushing an enum value to an `Enum[]`.

```
Error occurred during query execution:

ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("22023"), message: "unsupported binary operator: <Role[]> || <anyelement> (desired <Role[]>)", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("type_check.go"), line: Some(345), routine: Some("TypeCheck") }) }) })
```

In my case the enum definition is:

```prisma
enum Role {
  USER
  ADMIN
  EDITOR
}
```

With this Python script (which is practically equivalent to Node):

```py
model = await client.lists.update(
    where={
        'id': models[0].id,
    },
    data={
        'roles': {
            'push': [Role.ADMIN, Role.USER],
        },
    },
)
```

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
