### ISSUE TITLE
Regression bug: batched findUniqueOrThrow queries throw  'Field does not exist on enclosing type.'

### ISSUE THREAD

**Issue by DarioSiroki** [prisma/prisma#16548]
### Bug description

I assume there was a query batching update in 4.7.0. which doesn't seem to be working properly. The provided example works with 4.6.1. 

```
/Users/dar0/projects/prisma-demo/node_modules/@prisma/client/runtime/index.js:34843
      throw new PrismaClientKnownRequestError(message, {
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.user.findUniqueOrThrow()` invocation in
/Users/dar0/projects/prisma-demo/seed.ts:15:23

  12 // });
  13 
  14 names.forEach(async (id) => {
→ 15   await prisma.user.findUniqueOrThrow(
Failed to validate the query: `Field does not exist on enclosing type.` at `Query.findManyUserOrThrow`
    at RequestHandler.handleRequestError (/Users/dar0/projects/prisma-demo/node_modules/@prisma/client/runtime/index.js:34843:13)
    at RequestHandler.handleAndLogRequestError (/Users/dar0/projects/prisma-demo/node_modules/@prisma/client/runtime/index.js:34815:12)
    at RequestHandler.request (/Users/dar0/projects/prisma-demo/node_modules/@prisma/client/runtime/index.js:34810:12)
    at async PrismaClient._request (/Users/dar0/projects/prisma-demo/node_modules/@prisma/client/runtime/index.js:35900:16)
    at async /Users/dar0/projects/prisma-demo/node_modules/@prisma/client/runtime/index.js:34034:20
    at async /Users/dar0/projects/prisma-demo/seed.ts:15:5 {
  code: 'P2009',
  clientVersion: '4.7.0',
  meta: {
    query_validation_error: 'Field does not exist on enclosing type.',
    query_position: 'Query.findManyUserOrThrow'
  },
  batchRequestIdx: undefined
}
```

### How to reproduce

Run my code

### Prisma information

```prisma
generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "postgresql"
    url      = "postgres://postgres:root@localhost:5432/bug-demo"
}

model User {
    id   String @id @default(uuid())
    name String @unique
}

```

```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const names = Array(100)
    .fill(0)
    .map((_, i) => `Number ${i}`);

  // Run this on first run to seed the database
  // await prisma.user.createMany({
  //   data: names.map((i) => ({ name: i })),
  // });

  names.forEach(async (id) => {
    await prisma.user.findUniqueOrThrow({
      where: {
        name: id,
      },
    });
  });
}

main();

```

### Environment & setup

- OS: macOS, AWS linux AMI
- Database: psql
- Node.js version: v16.15.0

### Prisma Version

```
4.6.1 / 4.7.0
```

**Comment by miguelff** [comment]
There's indeed a bug in the way findUniqueOrThrow is being batched. We identified the root cause, and we are working towards resolution.
