### ISSUE TITLE
Error: Migration engine exited (Docker on M1 Max)

### ISSUE THREAD

**Issue by tomadimitrie** [prisma/prisma#16586]
### Bug description

I am getting this error while running Prisma inside a Docker container on M1 Max:

```
2022-12-01T21:12:33.935Z prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt
2022-12-01T21:12:34.240365632Z 2022-12-01T21:12:34.240Z prisma:loadEnv  project root found at /usr/local/app/package.json
2022-12-01T21:12:34.242856299Z 2022-12-01T21:12:34.242Z prisma:tryLoadEnv  Environment variables not found at null
2022-12-01T21:12:34.242979757Z 2022-12-01T21:12:34.242Z prisma:tryLoadEnv  Environment variables not found at undefined
2022-12-01T21:12:34.243005382Z 2022-12-01T21:12:34.242Z prisma:tryLoadEnv  No Environment variables loaded
2022-12-01T21:12:34.245266257Z 2022-12-01T21:12:34.245Z prisma:getConfig  Using getConfig Wasm
2022-12-01T21:12:34.249764841Z 2022-12-01T21:12:34.249Z prisma:getConfig  config data retrieved without errors in getConfig Wasm
2022-12-01T21:12:34.250321132Z 2022-12-01T21:12:34.250Z prisma:loadEnv  project root found at /usr/local/app/package.json
2022-12-01T21:12:34.252674591Z 2022-12-01T21:12:34.252Z prisma:tryLoadEnv  Environment variables not found at null
2022-12-01T21:12:34.252717674Z 2022-12-01T21:12:34.252Z prisma:tryLoadEnv  Environment variables not found at undefined
2022-12-01T21:12:34.253228924Z 2022-12-01T21:12:34.253Z prisma:tryLoadEnv  No Environment variables loaded
2022-12-01T21:12:34.253870091Z Prisma schema loaded from prisma/schema.prisma
2022-12-01T21:12:34.255586924Z 2022-12-01T21:12:34.255Z prisma:getConfig  Using getConfig Wasm
2022-12-01T21:12:34.256507382Z 2022-12-01T21:12:34.256Z prisma:getConfig  config data retrieved without errors in getConfig Wasm
2022-12-01T21:12:34.258214882Z Datasource "db": PostgreSQL database "antimony_events_dev", schema "public" at "db-events:5432"
2022-12-01T21:12:34.260412216Z 2022-12-01T21:12:34.260Z prisma:getConfig  Using getConfig Wasm
2022-12-01T21:12:34.262079966Z 2022-12-01T21:12:34.261Z prisma:getConfig  config data retrieved without errors in getConfig Wasm
2022-12-01T21:12:34.286840799Z 
2022-12-01T21:12:34.287205924Z Error: Error: Migration engine exited.
2022-12-01T21:12:34.287249132Z     at canConnectToDatabase (/usr/local/app/node_modules/prisma/build/index.js:92248:13)
2022-12-01T21:12:34.287253341Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-12-01T21:12:34.287256049Z     at async ensureDatabaseExists (/usr/local/app/node_modules/prisma/build/index.js:92965:22)
2022-12-01T21:12:34.287258424Z     at async _MigrateDeploy.parse (/usr/local/app/node_modules/prisma/build/index.js:95028:28)
2022-12-01T21:12:34.287266632Z     at async main (/usr/local/app/node_modules/prisma/build/index.js:98523:18)
```

My Dockerfile:
```dockerfile
FROM node:alpine AS build

RUN apk add openssl

WORKDIR /usr/local/app
COPY package.json tsconfig.json nodemon.json babel.config.js jest.config.js ./

RUN yarn install --pure-lockfile --non-interactive --production=false

ENV PATH="/usr/local/app/node_modules/.bin:${PATH}"
# ENV NODE_ENV="production"

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

ENV DEBUG="prisma*"

CMD /wait && prisma migrate deploy && prisma generate && yarn start
```

### Expected behavior

the migration should succeed (it works when using `platform: 'linux/amd64'` in docker-compose.yml OR when using the ARM version of node:slim -- only alpine is affected)

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- OS: macOS (M1 Max, Docker with Linux Alpine)
- Database: PostgreSQL
- Node.js version: v19.2.0

### Prisma Version

```
prisma                  : 4.7.0
2022-12-01T21:14:56.969825546Z @prisma/client          : 4.7.0
2022-12-01T21:14:56.969827462Z Current platform        : linux-arm64-openssl-1.1.x
2022-12-01T21:14:56.969829171Z Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-1.1.x.so.node)
2022-12-01T21:14:56.969831212Z Migration Engine        : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/migration-engine-linux-arm64-openssl-1.1.x)
2022-12-01T21:14:56.969833004Z Introspection Engine    : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/introspection-engine-linux-arm64-openssl-1.1.x)
2022-12-01T21:14:56.969841546Z Format Binary           : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/prisma-fmt-linux-arm64-openssl-1.1.x)
2022-12-01T21:14:56.969843421Z Format Wasm             : @prisma/prisma-fmt-wasm 4.7.0-74.39190b250ebc338586e25e6da45e5e783bc8a635
2022-12-01T21:14:56.969845129Z Default Engines Hash    : 39190b250ebc338586e25e6da45e5e783bc8a635
2022-12-01T21:14:56.969846879Z Studio                  : 0.477.0
```

**Comment by aqrln** [comment]
Alpine Linux on ARM64 is now supported as of Prisma 4.10.0 and newer. I'll go ahead and close this issue.
