### ISSUE TITLE
Slow postgres connections cause Prisma to throw error

### ISSUE THREAD

**Issue by hackermondev** [prisma/prisma#16619]
### Bug description

If the connection to a PostgreSQL server from Prisma is very slow and/or throttled, Prisma will throw a ``Can't reach database server`` error.

I'm connecting to my database server in a AWS datacenter from my home network (my network is kinda slow). Whenever I try to do a query with Prisma, I get an error saying my database server is not running.

```bash
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: 
Invalid `database_1.prisma.______.findMany()` invocation in
/home/hackermon/projects/______/______/______/______/______/______.js:11:60

   8 const log = (0, internals_1.logger)('______-______');
   9 async function default_1() {
  10     var _a;
→ 11     const ______= await database_1.prisma.______.findMany(
Can't reach database server at `______.______.______.______`:`5432`

Please make sure your database server is running at `______.______.______.______`:`5432`.
    at RequestHandler.handleRequestError (/home/hackermon/projects/______/node_modules/@prisma/client/runtime/index.js:30879:13)
    at RequestHandler.request (/home/hackermon/projects/______/node_modules/@prisma/client/runtime/index.js:30856:12)
    at async PrismaClient._request (/home/hackermon/projects/______/node_modules/@prisma/client/runtime/index.js:31836:16)
    at async default_1 (/home/hackermon/projects/______/apps/backend/dist/scripts/reattach.js:11:29)
    at async /home/hackermon/projects/______/apps/backend/dist/index.js:100:5
```

I know the server is running because I can connect to it my pgAdmin and when I run the same exact script on my EC2 instance (AWS VPS), everything works and I don't get any errors.

### How to reproduce

I'm connecting to my database server in a AWS datacenter from my home network (my network is kinda slow). Whenever I try to do a query with Prisma, I get an error saying my database server is not running.

```bash
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: 
Invalid `database_1.prisma.______.findMany()` invocation in
/home/hackermon/projects/______/______/______/______/______/______.js:11:60

   8 const log = (0, internals_1.logger)('______-______');
   9 async function default_1() {
  10     var _a;
→ 11     const ______= await database_1.prisma.______.findMany(
Can't reach database server at `______.______.______.______`:`5432`

Please make sure your database server is running at `______.______.______.______`:`5432`.
    at RequestHandler.handleRequestError (/home/hackermon/projects/______/node_modules/@prisma/client/runtime/index.js:30879:13)
    at RequestHandler.request (/home/hackermon/projects/______/node_modules/@prisma/client/runtime/index.js:30856:12)
    at async PrismaClient._request (/home/hackermon/projects/______/node_modules/@prisma/client/runtime/index.js:31836:16)
    at async default_1 (/home/hackermon/projects/______/apps/backend/dist/scripts/reattach.js:11:29)
    at async /home/hackermon/projects/______/apps/backend/dist/index.js:100:5
```

I know the server is running because I can connect to it my pgAdmin and when I run the same exact script on my EC2 instance (AWS VPS), everything works and I don't get any errors.

### Expected behavior

It should wait until the connection goes through or let me set a custom timeout for the connection.

### Prisma information

**None**

### Environment & setup

- OS:  Ubuntu
- Database: PostgreSQL
- Node.js version: v18.9.0

### Prisma Version

```
prisma                  : 4.5.0
@prisma/client          : 4.5.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt 0362da9eebca54d94c8ef5edd3b2e90af99ba452 (at ../../node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.5.0-43.0362da9eebca54d94c8ef5edd3b2e90af99ba452
Default Engines Hash    : 0362da9eebca54d94c8ef5edd3b2e90af99ba452
Studio                  : 0.476.0
```

**Comment by hackermondev** [comment]
Yeah, thanks
