### ISSUE TITLE
Nested create not working when using model.upsert()

### ISSUE THREAD

**Issue by ericsj** [prisma/prisma#16636]
### Bug description

I understand prisma automatically sets the id attribute of a relation, but I got the following error creating an upsert use case:

```
[1] prisma:query SELECT "public"."RepresentativeLogin"."id", "public"."RepresentativeLogin"."email", "public"."RepresentativeLogin"."password", "public"."RepresentativeLogin"."representativeId" FROM "public"."RepresentativeLogin" WHERE "public"."RepresentativeLogin"."id" = $1 LIMIT $2 OFFSET $3
[1] prisma:query SELECT "public"."RepresentativeLogin"."id", "public"."RepresentativeLogin"."email", "public"."RepresentativeLogin"."password", "public"."RepresentativeLogin"."representativeId" FROM "public"."RepresentativeLogin" WHERE "public"."RepresentativeLogin"."id" = $1 LIMIT $2 OFFSET $3
[1] prisma:query SELECT "public"."Representative"."id", "public"."Representative"."companyId" FROM "public"."Representative" WHERE "public"."Representative"."id" IN ($1) OFFSET $2
[1] prisma:query SELECT "public"."RepresentativeLogin"."id", "public"."RepresentativeLogin"."representativeId" FROM "public"."RepresentativeLogin" WHERE "public"."RepresentativeLogin"."id" = $1 LIMIT $2 OFFSET $3
[1] prisma:query SELECT "public"."Representative"."id", "public"."Representative"."companyId" FROM "public"."Representative" WHERE "public"."Representative"."id" IN ($1) OFFSET $2
[1] prisma:query SELECT "public"."Company"."id" FROM "public"."Company" WHERE "public"."Company"."id" IN ($1) OFFSET $2
[1] prisma:query SELECT "public"."ClientSource"."id", "public"."ClientSource"."name", "public"."ClientSource"."companyId" FROM "public"."ClientSource" WHERE "public"."ClientSource"."companyId" IN ($1) OFFSET $2
[1] prisma:query SELECT "public"."RepresentativeLogin"."id", "public"."RepresentativeLogin"."representativeId" FROM "public"."RepresentativeLogin" WHERE "public"."RepresentativeLogin"."id" = $1 LIMIT $2 OFFSET $3
[1] prisma:query SELECT "public"."Representative"."id", "public"."Representative"."companyId" FROM "public"."Representative" WHERE "public"."Representative"."id" IN ($1) OFFSET $2
[1] prisma:query SELECT "public"."Company"."id" FROM "public"."Company" WHERE "public"."Company"."id" IN ($1) OFFSET $2
[1] prisma:query SELECT "public"."ClientStatus"."id", "public"."ClientStatus"."name", "public"."ClientStatus"."companyId" FROM "public"."ClientStatus" WHERE "public"."ClientStatus"."companyId" IN ($1) OFFSET $2
[1] PrismaClientValidationError: 
[1] Invalid `db_1.prisma.clientLogin.upsert()` invocation in
[1] /home/user/Desktop/autoflow/server/dist/src/data/usecases/company/client/upsertClient.js:43:35
[1] 
[1]   40     throw new invalidParamError_1.InvalidParamError('clientStatus');
[1]   41 }
[1]   42 const password = crypto_1.default.randomBytes(15).toString('hex');
[1] → 43 yield db_1.prisma.clientLogin.upsert({
[1]        where: {
[1]          email: 'string@test.com'
[1]        },
[1]        update: {
[1]          email: 'string@test.com',
[1]          client: {
[1]          ~~~~~~
[1]            update: {
[1]              notes: 'string',
[1]              clientPersonalData: {
[1]                update: {
[1]                  cpf: 'string',
[1]                  cnh: 'string',
[1]                  phone: 'string',
[1]                  firstName: 'string',
[1]                  lastName: 'string',
[1]                  birthDay: '2022-11-25',
[1]                  cnhAquisitionDate: '2022-11-25'
[1]                }
[1]              },
[1]              clientStatus: {
[1]                connect: {
[1]                  id: '67adb182-662b-43f9-9c4a-d9a0ecd2f9a2'
[1]                }
[1]              },
[1]              clientSource: {
[1]                connect: {
[1]                  id: '13d758d9-9c36-497e-9b18-ab695e4b915c'
[1]                }
[1]              },
[1]              company: {
[1]                connect: {
[1]                  id: 'e9a4f239-341f-4d27-97b0-a15f2b3503a6'
[1]                }
[1]              }
[1]            }
[1]          }
[1]        },
[1]        create: {
[1]          email: 'string@test.com',
[1]          password: '00f3f20f05661b65dacc443821c270',
[1]          client: {
[1]          ~~~~~~
[1]            create: {
[1]              notes: 'string',
[1]              clientPersonalData: {
[1]                create: {
[1]                  cpf: 'string',
[1]                  cnh: 'string',
[1]                  phone: 'string',
[1]                  firstName: 'string',
[1]                  lastName: 'string',
[1]                  birthDay: '2022-11-25',
[1]                  cnhAquisitionDate: '2022-11-25'
[1]                }
[1]              },
[1]              clientStatus: {
[1]                connect: {
[1]                  id: '67adb182-662b-43f9-9c4a-d9a0ecd2f9a2'
[1]                }
[1]              },
[1]              clientSource: {
[1]                connect: {
[1]                  id: '13d758d9-9c36-497e-9b18-ab695e4b915c'
[1]                }
[1]              },
[1]              company: {
[1]                connect: {
[1]                  id: 'e9a4f239-341f-4d27-97b0-a15f2b3503a6'
[1]                }
[1]              }
[1]            }
[1]          },
[1]      +   clientId: String,
[1]      ?   id?: String
[1]        }
[1]      })
[1] 
[1] Unknown arg `client` in update.client for type ClientLoginUncheckedUpdateInput. Did you mean `clientId`?
[1] Unknown arg `client` in create.client for type ClientLoginUncheckedCreateInput. Did you mean `clientId`?
[1] Argument clientId for create.clientId is missing.
[1] 
[1] Note: Lines with + are required, lines with ? are optional.
[1] 
[1]     at Document.validate (/home/user/Desktop/autoflow/server/node_modules/@prisma/client/runtime/index.js:32256:20)
[1]     at serializationFn (/home/user/Desktop/autoflow/server/node_modules/@prisma/client/runtime/index.js:35337:19)
[1]     at runInChildSpan (/home/user/Desktop/autoflow/server/node_modules/@prisma/client/runtime/index.js:28209:12)
[1]     at PrismaClient._executeRequest (/home/user/Desktop/autoflow/server/node_modules/@prisma/client/runtime/index.js:35344:31)
[1]     at consumer (/home/user/Desktop/autoflow/server/node_modules/@prisma/client/runtime/index.js:35271:23)
[1]     at /home/user/Desktop/autoflow/server/node_modules/@prisma/client/runtime/index.js:35276:51
[1]     at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
[1]     at /home/user/Desktop/autoflow/server/node_modules/@prisma/client/runtime/index.js:35276:29
[1]     at runInChildSpan (/home/user/Desktop/autoflow/server/node_modules/@prisma/client/runtime/index.js:28209:12)
[1]     at PrismaClient._request (/home/user/Desktop/autoflow/server/node_modules/@prisma/client/runtime/index.js:35273:22) {
[1]   clientVersion: '4.6.1'
[1] }
```

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model RepresentativeLogin {
  id               String         @id @default(uuid())
  email            String         @unique
  password         String
  representative   Representative @relation(fields: [representativeId], references: [id])
  representativeId String         @unique
}

model ClientLogin {
  id       String @id @default(uuid())
  email    String @unique
  password String
  client   Client @relation(fields: [clientId], references: [id])
  clientId String @unique
}

enum UserType {
  CLIENT
  REPRESENTATIVE
}

model Client {
  id                   String             @id @default(uuid())
  updatedAt            DateTime           @default(now()) @updatedAt
  notes                String?
  welcomeEmailSent     Boolean            @default(false)
  clientPersonalData   ClientPersonalData @relation(fields: [clientPersonalDataId], references: [id])
  clientPersonalDataId String             @unique
  clientStatus         ClientStatus       @relation(fields: [clientStatusId], references: [id])
  clientStatusId       String
  clientSource         ClientSource       @relation(fields: [clientSourceId], references: [id])
  clientSourceId       String
  company              Company            @relation(fields: [companyId], references: [id])
  companyId            String
  ClientLogin          ClientLogin?
}

model ClientPersonalData {
  id                String    @id @default(uuid())
  updatedAt         DateTime  @default(now()) @updatedAt
  cpf               String?
  cnh               String?
  phone             String?
  firstName         String
  lastName          String?
  birthDay          DateTime?
  cnhAquisitionDate DateTime?
  client            Client?
}

model ClientStatus {
  id        String   @id @default(uuid())
  name      String
  clients   Client[]
  company   Company  @relation(fields: [companyId], references: [id])
  companyId String

  @@unique([companyId, name])
}

model ClientSource {
  id        String   @id @default(uuid())
  name      String
  clients   Client[]
  company   Company  @relation(fields: [companyId], references: [id])
  companyId String

  @@unique([companyId, name])
}

model Company {
  id             String          @id @default(uuid())
  name           String
  clientSources  ClientSource[]
  clientStatuses ClientStatus[]
  clients        Client[]
  representative Representative?
}

model Representative {
  id                  String               @id @default(uuid())
  firstName           String
  lastName            String
  company             Company              @relation(fields: [companyId], references: [id])
  companyId           String               @unique
  RepresentativeLogin RepresentativeLogin?
}
```

```ts
export const upsertClient = async (clientData: UpsertClientData): Promise<void> => {
  const foundRepresentativeLogin = await prisma.representativeLogin.findFirstOrThrow({
    where: {
      id: clientData.representativeLoginId
    },
    include: {
      representative: {
        select: {
          companyId: true
        }
      }
    }
  })
  const clientSourceExists = await checkIfClientSourceExists(clientData.representativeLoginId,
    clientData.clientSourceId)
  if (!clientSourceExists) {
    throw new InvalidParamError('clientSource')
  }
  const clientStatusExists = await checkIfClientStatusExists(clientData.representativeLoginId,
    clientData.clientStatusId)
  if (!clientStatusExists) {
    throw new InvalidParamError('clientStatus')
  }
  const password = crypto.randomBytes(15).toString('hex')
  await prisma.clientLogin.upsert({
    where: {
      email: clientData.email
    },
    update: {
      email: clientData.email,
      client: {
        update: {
          notes: clientData.notes,
          clientPersonalData: {
            update: {
              cpf: clientData.cpf,
              cnh: clientData.cnh,
              phone: clientData.phone,
              firstName: clientData.firstName,
              lastName: clientData.lastName,
              birthDay: clientData.birthDay,
              cnhAquisitionDate: clientData.cnhAquisitionDate,
            }
          },
          clientStatus: {
            connect: { id: clientData.clientStatusId }
          },
          clientSource: {
            connect: { id: clientData.clientSourceId }
          },
          company: {
            connect: { id: foundRepresentativeLogin.representative.companyId }
          }
        }
      },
    },
    create: {
      email: clientData.email,
      password,
      client: {
        create: {
          notes: clientData.notes,
          clientPersonalData: {
            create: {
              cpf: clientData.cpf,
              cnh: clientData.cnh,
              phone: clientData.phone,
              firstName: clientData.firstName,
              lastName: clientData.lastName,
              birthDay: clientData.birthDay,
              cnhAquisitionDate: clientData.cnhAquisitionDate,
            }
          },
          clientStatus: {
            connect: { id: clientData.clientStatusId }
          },
          clientSource: {
            connect: { id: clientData.clientSourceId }
          },
          company: {
            connect: { id: foundRepresentativeLogin.representative.companyId }
          }
        }
      },
    }
  })
}
```

### Environment & setup

- OS: Ubuntu 18
- Database: Postgresql
- Node.js version: 16

### Prisma Version

```
4.6.1
```

**Comment by ericsj** [comment]
After changing the schema, the error accidentally disappeared, so I closed the issue.
