### ISSUE TITLE
Query engine library for current platform "linux-musl" could not be found

### ISSUE THREAD

**Issue by nimbit-software** [prisma/prisma#16642]
/usr/src/app/main.js:27562
2022-12-06 01:29:15       throw new PrismaClientInitializationError(errorText, this.config.clientVersion);
2022-12-06 01:29:15             ^
2022-12-06 01:29:15 
2022-12-06 01:29:15 PrismaClientInitializationError: Query engine library for current platform "linux-musl" could not be found.
2022-12-06 01:29:15 You incorrectly pinned it to linux-musl
2022-12-06 01:29:15 
2022-12-06 01:29:15 This probably happens, because you built Prisma Client on a different platform.
2022-12-06 01:29:15 (Prisma Client looked in "/usr/src/app/libquery_engine-linux-musl.so.node")
2022-12-06 01:29:15 
2022-12-06 01:29:15 Searched Locations:
2022-12-06 01:29:15 
2022-12-06 01:29:15   /.prisma/client
2022-12-06 01:29:15   C:\Users\sooter\Documents\IOT\nimbit-service-mono\customer-apps\doppstadt\proemion-data-manager\node_modules\@prisma\doppstadt\proemion-data-manager
2022-12-06 01:29:15   /usr/src
2022-12-06 01:29:15   /usr/src/app
2022-12-06 01:29:15   /usr/src/app
2022-12-06 01:29:15   /tmp/prisma-engines
2022-12-06 01:29:15   /usr/src/app
2022-12-06 01:29:15 
2022-12-06 01:29:15 You already added the platforms "windows", "linux-musl" to the "generator" block
2022-12-06 01:29:15 in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
2022-12-06 01:29:15 but something went wrong. That's suboptimal.
2022-12-06 01:29:15 
2022-12-06 01:29:15 Please create an issue at https://github.com/prisma/prisma/issues/new
2022-12-06 01:29:15     at DefaultLibraryLoader.getLibQueryEnginePath (/usr/src/app/main.js:27562:13)
2022-12-06 01:29:15     at async DefaultLibraryLoader.loadLibrary (/usr/src/app/main.js:27480:33)
2022-12-06 01:29:15     at async LibraryEngine.loadEngine (/usr/src/app/main.js:27799:24)
2022-12-06 01:29:15     at async LibraryEngine.instantiateLibrary (/usr/src/app/main.js:27753:5) {
2022-12-06 01:29:15   clientVersion: '4.7.1',
2022-12-06 01:29:15   errorCode: undefined
2022-12-06 01:29:15 }

**Comment by claudiowilson** [comment]
happens to me to using node:16-alpine

```
~ $ npx prisma -v
Environment variables loaded from .env
prisma                  : 4.6.1
@prisma/client          : 4.6.1
Current platform        : linux-musl
Query Engine (Node-API) : libquery-engine 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/libquery_engine-linux-musl.so.node)
Migration Engine        : migration-engine-cli 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/migration-engine-linux-musl)
Introspection Engine    : introspection-core 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/introspection-engine-linux-musl)
Format Binary           : prisma-fmt 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/prisma-fmt-linux-musl)
Format Wasm             : @prisma/prisma-fmt-wasm 4.6.1-3.694eea289a8462c80264df36757e4fdc129b1b32
Default Engines Hash    : 694eea289a8462c80264df36757e4fdc129b1b32
Studio                  : 0.476.0
```

**Comment by jirayui** [comment]
> happens to me as well using node:16-alpine
> 
> ```
> ~ $ npx prisma -v
> Environment variables loaded from .env
> prisma                  : 4.6.1
> @prisma/client          : 4.6.1
> Current platform        : linux-musl
> Query Engine (Node-API) : libquery-engine 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/libquery_engine-linux-musl.so.node)
> Migration Engine        : migration-engine-cli 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/migration-engine-linux-musl)
> Introspection Engine    : introspection-core 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/introspection-engine-linux-musl)
> Format Binary           : prisma-fmt 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/prisma-fmt-linux-musl)
> Format Wasm             : @prisma/prisma-fmt-wasm 4.6.1-3.694eea289a8462c80264df36757e4fdc129b1b32
> Default Engines Hash    : 694eea289a8462c80264df36757e4fdc129b1b32
> Studio                  : 0.476.0
> ```

change from `node:16-alpine` to `node:16-alpine3.16` works to me

**Comment by jirayui** [comment]
relates to this issue

https://github.com/prisma/prisma/issues/16553

**Comment by claudiowilson** [comment]
> > happens to me as well using node:16-alpine
> > ```
> > ~ $ npx prisma -v
> > Environment variables loaded from .env
> > prisma                  : 4.6.1
> > @prisma/client          : 4.6.1
> > Current platform        : linux-musl
> > Query Engine (Node-API) : libquery-engine 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/libquery_engine-linux-musl.so.node)
> > Migration Engine        : migration-engine-cli 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/migration-engine-linux-musl)
> > Introspection Engine    : introspection-core 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/introspection-engine-linux-musl)
> > Format Binary           : prisma-fmt 694eea289a8462c80264df36757e4fdc129b1b32 (at node_modules/@prisma/engines/prisma-fmt-linux-musl)
> > Format Wasm             : @prisma/prisma-fmt-wasm 4.6.1-3.694eea289a8462c80264df36757e4fdc129b1b32
> > Default Engines Hash    : 694eea289a8462c80264df36757e4fdc129b1b32
> > Studio                  : 0.476.0
> > ```
> 
> try to change from `node:16-alpine` to `node:16-alpine3.16`, it works for me

@jirayui can you post your full dockerfile? mine still isn't working

**Comment by jkomyno** [comment]
Hey @nimbit-software, could you please tell us more about the problem you're experiencing?
It looks to us you're generating the client on Windows and using it on Linux Alpine, but we would need more info to be able to help.
E.g., could you paste your schema, describe which OS you're in, and the steps you were performing with Prisma? Thanks

**Comment by jkomyno** [comment]
Hey @claudiowilson, could you please elaborate what issue you're experiencing? Your `prisma -v` command reveals `libquery_engine-linux-musl.so.node` is correctly download, so `linux-musl` is found.
Can you please paste any error (and stacktrace) you're facing, describe which OS and architecture you're in, paste your schema, and tell us which step you were taking? Thanks

**Comment by claudiowilson** [comment]
@jkomyno figured it out -- the image i was using build the prism client was different than the image i was using to build. that output was from when I had run prisma generate again but had not yet restarted the application. everything works now!

**Comment by jclaessens97** [comment]
I have the same issue in #16901 but as far as I can see I install, build and generate on the same platform (being node18-alpine3.16). 

I tried both building from my m1 mac as from Github Actions.

**Comment by azaek** [comment]
add prisma generate command before your run in Dockerfile. It worked for me
```Dockerfile
...
RUN npx prisma generate
RUN npm run build

EXPOSE 4000
CMD [ "npm", "start" ]
```

**Comment by aqrln** [comment]
The original report looks like it might be https://github.com/prisma/prisma/issues/15325, given these lines:

```
2022-12-06 01:29:15 Searched Locations:
2022-12-06 01:29:15 
2022-12-06 01:29:15   /.prisma/client
2022-12-06 01:29:15   C:\Users\sooter\Documents\IOT\nimbit-service-mono\customer-apps\doppstadt\proemion-data-manager\node_modules\@prisma\doppstadt\proemion-data-manager
2022-12-06 01:29:15   /usr/src
2022-12-06 01:29:15   /usr/src/app
2022-12-06 01:29:15   /usr/src/app
2022-12-06 01:29:15   /tmp/prisma-engines
2022-12-06 01:29:15   /usr/src/app
```

**Comment by janpio** [comment]
This should be solved. Please open a new issue, if you still have a similar problem. Thanks.
