### ISSUE TITLE
Cryptic N/A errors with rawQuery

### ISSUE THREAD

**Issue by RodolpheGohard** [prisma/prisma#16669]
## Problem

with this rawQuery:
```ts
    const yup = prismaLegacy.$queryRaw`
SELECT customer_entity.entity_id          as entity_id,
   customer_entity.email              as email, 
   customer_address_entity.entity_id  as addressId,
   customer_entity.updated_at         as userUpdate,
   customer_address_entity.updated_at as lastAddressUpdate
FROM customer_entity
       LEFT JOIN customer_address_entity
                 ON (customer_entity.entity_id = customer_address_entity.parent_id)
WHERE
  customer_address_entity.updated_at > DATE('${dateLimit.toISOString()}') OR # Where address has been update
  customer_entity.updated_at > DATE('${dateLimit.toISOString()}') # Where user has no adress but has been updated
LIMIT 100
;
  `;
```
I had this error message:
```
path/prisma/legacy/client/runtime/index.js:29909
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
Error: 
Invalid `prisma.$queryRaw()` invocation:


Raw query failed. Code: `N/A`. Message: `N/A`
    at RequestHandler.handleRequestError (path/prisma/legacy/client/runtime/index.js:29909:13)
    at RequestHandler.request (path/prisma/legacy/client/runtime/index.js:29892:12)
    at Proxy._request (path/prisma/legacy/client/runtime/index.js:30864:16)
error Command failed with exit code 1.

```
Which doesn't say much.

The problem was my syntax is incorrect (quotes not required around templates variables),  but the error doesn't point in this direction.

I have seen other similar tickets with "N/A" errors but the provided resolutions seems very specific to each case. Couldn't we have the underlying exceptions shown in the generic case, instead of this useless N/A message ?

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
