### ISSUE TITLE
Preview feature "orderByNulls" not working with MongoDB

### ISSUE THREAD

**Issue by dfilipidisz** [prisma/prisma#16728]
### Bug description

I was trying to write a query that utilizes the `orderByNulls` preview feature for MongoDB, but I'm not sure if it's supported or not. The docs don't mention that it's not supported.

# Sample

Code sample from the docs:
```ts
const posts = await prisma.post.findMany({
  orderBy: {
    updatedAt: { sort: 'asc', nulls: 'last' },
  },
})
```

My code (full sample in later section):
```ts
const res = await prisma.test.findMany({
  orderBy: {
    name: { sort: 'asc', nulls: 'last' },
  },
});
```
# Prisma client with sqlite

```ts
export type TestOrderByWithRelationInput = {
  id?: SortOrder
  email?: SortOrder
  name?: SortOrderInput | SortOrder // <--- SortOrderInput is generated
}
```

# Prisma client with MongoDB
```ts
export type TestOrderByWithRelationInput = {
  id?: SortOrder
  email?: SortOrder
  name?: SortOrder // <--- SortOrderInput missing
}  
```

# Issues

1. I get the following TS error on the `orderBy` property of the `.findMany()` call.
```zsh
index.ts:8:5 - error TS2322: Type '{ name: { sort: string; nulls: string; }; }' is not assignable to type 'Enumerable<TestOrderByWithRelationInput> | undefined'.
  Types of property 'name' are incompatible.
    Type '{ sort: string; nulls: string; }' is not assignable to type 'SortOrder | undefined'.

8     orderBy: {
      ~~~~~~~
Found 1 error in index.ts:8
```

2. Executing the code sample, results in this error, when ignoring the TS problems:
```shell
PrismaClientValidationError: 
Invalid `prisma.test.findMany()` invocation in
/<..path>/prisma_issue/index.ts:7:33

  4 
  5 async function main() {
  6   await prisma.$connect();
→ 7   const res = await prisma.test.findMany({
        orderBy: {
          name: {
            sort: 'asc',
            nulls: 'last'
          }
          ~~~~~~~~~~~~~~~
        }
      })

Argument name: Provided value 
{
  sort: 'asc',
  nulls: 'last'
}
of type Json on prisma.findManyTest is not a SortOrder.
→ Possible values: SortOrder.asc, SortOrder.desc

    at Document.validate (/<..path>/prisma_issue/node_modules/@prisma/client/runtime/index.js:32409:20)
    at serializationFn (/<..path>/prisma_issue/node_modules/@prisma/client/runtime/index.js:35993:19)
    at runInChildSpan (/<..path>/prisma_issue/node_modules/@prisma/client/runtime/index.js:25431:12)
    at PrismaClient._executeRequest (/<..path>/prisma_issue/node_modules/@prisma/client/runtime/index.js:36000:31)
    at async PrismaClient._request (/<..path>/prisma_issue/node_modules/@prisma/client/runtime/index.js:35926:16) {
  clientVersion: '4.7.1'
}
```

### How to reproduce

Run the code provided below.

### Expected behavior

I'd expect either:
1. A note in the docs that `orderByNulls` is not supported with MongoDB.
2. That it works with MongoDB as it is with sqlite.

### Prisma information

schema.prisma
```prisma
datasource db {
  provider = "mongodb"
  url      = "mongodb+srv://...removed"
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["orderByNulls"]
}

model Test {
  id    String  @id @default(auto()) @map("_id") @db.ObjectId
  email String
  name  String?
}
```

Full sample code
```ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({ log: ['query', 'info', 'warn'] });

async function main() {
  await prisma.$connect();
  const res = await prisma.test.findMany({
    orderBy: {
      name: { sort: 'asc', nulls: 'last' }, // <---------
    },
  });
  console.log(JSON.stringify(res, null, 2));
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
```

### Environment & setup

- OS: macOS 12.6.1
- Database: MongoDB Atlas 6.0 and 5.0.14
- Node.js version: 18.12.0

### Prisma Version

```
prisma                  : 4.7.1
@prisma/client          : 4.7.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/@prisma/engines/prisma-fmt-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.7.1-1.272861e07ab64f234d3ffc4094e32bd61775599c
Default Engines Hash    : 272861e07ab64f234d3ffc4094e32bd61775599c
Studio                  : 0.477.0
Preview Features        : orderByNulls
```

**Comment by mcbethio** [comment]
Ok, I have a full reproduction on this and @dfilipidisz is absolutely correct that our documentation does not mention a lack of support for orderByNulls with MongoDb.

**Comment by Weakky** [comment]
Hey @dfilipidisz,

I've just slightly edited your issue so it counts as a feature request and not a bug. MongoDB was intentionally not supported when implementing the feature because it requires too many hacks to support it at the moment.

We might reconsider this in the future.
