### ISSUE TITLE
Unique constraint error when connecting an item in a 1-1 relation that is already connected

### ISSUE THREAD

**Issue by emmatown** [prisma/prisma#16743]
### Bug description

When connecting an item that is already connected in a 1-1 relation, the item is not disconnected from the previous item when connecting to a new item so a unique constraint error occurs. In versions prior to 4.7.0, the item was disconnected as expected.

### How to reproduce

1. Create a `schema.prisma` with the schema below.
2. Run `prisma db push`
3. Create an `index.js` with the code below.
4. Run `node index.js`
5. See the following output and error
```
prisma:query BEGIN
prisma:query INSERT INTO "public"."B" DEFAULT VALUES RETURNING "public"."B"."id"
prisma:query INSERT INTO "public"."A" ("bId") VALUES ($1) RETURNING "public"."A"."id"
prisma:query SELECT "public"."A"."id", "public"."A"."bId" FROM "public"."A" WHERE "public"."A"."id" = $1 LIMIT $2 OFFSET $3
prisma:query COMMIT
prisma:query BEGIN
prisma:query SELECT "public"."B"."id" FROM "public"."B" WHERE ("public"."B"."id" = $1 AND 1=1) OFFSET $2
prisma:query INSERT INTO "public"."A" ("bId") VALUES ($1) RETURNING "public"."A"."id"
prisma:query ROLLBACK
node_modules/.pnpm/@prisma+client@4.7.1_prisma@4.7.1/node_modules/@prisma/client/runtime/index.js:34869
      throw new PrismaClientKnownRequestError(message, {
            ^

PrismaClientKnownRequestError: 
Invalid `client.a.create()` invocation in
index.js:7:18

  4 
  5 (async () => {
  6   const item = await client.a.create({ data: { b: { create: {} } } });
→ 7   await client.a.create(
Unique constraint failed on the fields: (`bId`)
    at RequestHandler.handleRequestError (node_modules/.pnpm/@prisma+client@4.7.1_prisma@4.7.1/node_modules/@prisma/client/runtime/index.js:34869:13)
    at RequestHandler.handleAndLogRequestError (node_modules/.pnpm/@prisma+client@4.7.1_prisma@4.7.1/node_modules/@prisma/client/runtime/index.js:34841:12)
    at RequestHandler.request (node_modules/.pnpm/@prisma+client@4.7.1_prisma@4.7.1/node_modules/@prisma/client/runtime/index.js:34836:12)
    at async PrismaClient._request (node_modules/.pnpm/@prisma+client@4.7.1_prisma@4.7.1/node_modules/@prisma/client/runtime/index.js:35926:16)
    at async index.js:7:3 {
  code: 'P2002',
  clientVersion: '4.7.1',
  meta: { target: [ 'bId' ] },
  batchRequestIdx: undefined
}

Node.js v18.12.1
```

### Expected behavior

The first item is disconnected before connecting to the new item like on versions prior to 4.7.0.
The output of the same code on Prisma 4.6.1:
```
prisma:query BEGIN
prisma:query INSERT INTO "public"."B" DEFAULT VALUES RETURNING "public"."B"."id"
prisma:query INSERT INTO "public"."A" ("bId") VALUES ($1) RETURNING "public"."A"."id"
prisma:query SELECT "public"."A"."id", "public"."A"."bId" FROM "public"."A" WHERE "public"."A"."id" = $1 LIMIT $2 OFFSET $3
prisma:query COMMIT
prisma:query BEGIN
prisma:query SELECT "public"."B"."id" FROM "public"."B" WHERE ("public"."B"."id" = $1 AND 1=1) OFFSET $2
prisma:query SELECT "public"."A"."id", "public"."A"."bId" FROM "public"."A" WHERE (1=1 AND "public"."A"."bId" IN ($1)) OFFSET $2
prisma:query UPDATE "public"."A" SET "bId" = $1 WHERE ("public"."A"."id" IN ($2) AND 1=1)
prisma:query INSERT INTO "public"."A" ("bId") VALUES ($1) RETURNING "public"."A"."id"
prisma:query SELECT "public"."A"."id", "public"."A"."bId" FROM "public"."A" WHERE "public"."A"."id" = $1 LIMIT $2 OFFSET $3
prisma:query COMMIT
```

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model A {
  id  Int  @id @default(autoincrement())
  b   B?   @relation(fields: [bId], references: [id])
  bId Int? @unique
}

model B {
  id Int @id @default(autoincrement())
  a  A?
}
```

```ts
const { PrismaClient } = require("@prisma/client");

const client = new PrismaClient({ log: ["query"] });

(async () => {
  const item = await client.a.create({ data: { b: { create: {} } } });
  await client.a.create({ data: { b: { connect: { id: item.bId } } } });
})();
```

### Environment & setup

- OS: macOS 13.0.1
- Database: PostgreSQL 14.6
- Node.js version: 18.12.1

### Prisma Version

```
prisma                  : 4.7.1
@prisma/client          : 4.7.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/.pnpm/@prisma+engines@4.7.1/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/.pnpm/@prisma+engines@4.7.1/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/.pnpm/@prisma+engines@4.7.1/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 272861e07ab64f234d3ffc4094e32bd61775599c (at node_modules/.pnpm/@prisma+engines@4.7.1/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.7.1-1.272861e07ab64f234d3ffc4094e32bd61775599c
Default Engines Hash    : 272861e07ab64f234d3ffc4094e32bd61775599c
Studio                  : 0.477.0
```

**Comment by Weakky** [comment]
Regression confirmed. Thanks for letting us know 🙏🏻
