### ISSUE TITLE
End to end tests failing in github actions

### ISSUE THREAD

**Issue by vinu-ablabs** [prisma/prisma#16917]
### Bug description

We have a pipeline that runs our tests. Both for unit and e2e we get the following error from prisma. This does not happen on local machines. Only on github actions

```bash
> jest --config ./test/jest-e2e.json

PASS test/app.e2e-spec.ts
FAIL test/service-category.e2e-spec.ts
  ● Test suite failed to run

    readStream must be readable

      at createLineStream (../node_modules/@prisma/generator-helper/dist/byline.js:53:[11](https://github.com/ABrightLab/microservices/actions/runs/3738274899/jobs/6344210512#step:8:12))
      at createStream (../node_modules/@prisma/generator-helper/dist/byline.js:42:[12](https://github.com/ABrightLab/microservices/actions/runs/3738274899/jobs/6344210512#step:8:13))
      at byline (../node_modules/@prisma/generator-helper/dist/byline.js:37:10)
      at Object.generatorHandler (../node_modules/@prisma/generator-helper/dist/generatorHandler.js:33:29)
      at Object.generatorHandler (../node_modules/@Abrightlab/arkshare/src/generator.ts:[17](https://github.com/ABrightLab/microservices/actions/runs/3738274899/jobs/6344210512#step:8:18):1)
      at Object.<anonymous> (../node_modules/@Abrightlab/arkshare/dist/index.js:7:[20](https://github.com/ABrightLab/microservices/actions/runs/3738274899/jobs/6344210512#step:8:21))

Test Suites: 1 failed, 1 passed, 2 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        5.556 s
Ran all test suites.
Error: Process completed with exit code 1.
```

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: ubuntu
- Database: MySQL
- Node.js version: 16.8

### Prisma Version

```

```

**Comment by janpio** [comment]
What is this test suite running? Certain commands or queries?

**Comment by aqrln** [comment]
Would you be able to provide a reproduction? Looking at the stack trace, the issue seems to arise from third-party custom generator (`@Abrightlab/arkshare/src/generator.ts`), so it's hard to say if it's an issue in Prisma or not.

**Comment by vinu-ablabs** [comment]
I am sorry I left this here unattended. It was an issue with the middleware we added. Somehow it was acting up with Jest. 

We managed to resolve. Appreciate you following up and being super responsive. Will reach out in the future if need be.
