### ISSUE TITLE
The change you are trying to make would violate the required relation

### ISSUE THREAD

**Issue by Deliana90** [prisma/prisma#17048]
### Bug description

I want to replace many-to-many pivot table with a new set of values.

schema
```
model Role {
  id          Int    @id @default(autoincrement())
  name        String @unique
  description String

  users       User[]
  permissions PermissionsOnRoles[]
}

model Permission {
  id          Int    @id @default(autoincrement())
  name        String @unique
  description String

  roles PermissionsOnRoles[]
}

model PermissionsOnRoles {
  permission   Permission @relation(fields: [permissionId], references: [id])
  permissionId Int
  role         Role       @relation(fields: [roleId], references: [id])
  roleId       Int
  description1 String
  description2 String

  @@id([permissionId, roleId])
}
```
function for create
```
return await this.prisma.role.create({
      data: {
        description: 'manager',
        name: 'manager',
        permissions: {
          create: [
            {
              description1: 'permission 11',
              description2: 'permission 12',
              permissionId: 1,
            },
            {
              description1: 'permission 31',
              description2: 'permission 32',
              permissionId: 3,
            },
          ],
        },
      },
    });
```
function for update(let say I want to revoke all manager's permissions)
```
return await this.prisma.role.update({
      where: { id: 2 },
      data: {
        description: 'manager',
        name: 'manager',
        permissions: {
          set: [],
        },
      },
    });
```

when run function for update, I got error
> The change you are trying to make would violate the required relation 'PermissionsOnRolesToRole' between the `PermissionsOnRoles` and `Role` models.

### How to reproduce

^

### Prisma information

^

### Environment & setup

- OS:  linuxmint
- Database:  postgresql
- Node.js version:  16.16.0

### Prisma Version

```
4.8.0
```

**Comment by Deliana90** [comment]
still unconfirmed, is it hard to reproduce?

**Comment by janpio** [comment]
There are hundreds of other open unconfirmed bugs, and other work going on. We'll get to this as soon as we can.

**Comment by icecoconut** [comment]
I also got this error

**Comment by virus2016** [comment]
Any news on this one?

**Comment by rzzo** [comment]
Yeah I am getting this same thing... Just need to updated a simple M2M relation wondering if this is a massive bug or we are missing something very small?

**Comment by Deliana90** [comment]
RIP :-)

**Comment by icecoconut** [comment]
RIP graphcool v3

**Comment by cluk3** [comment]
I had the same problem on postgres with M:N relationship.
My workaround was to do the following instead of `set`:

```
        deleteMany: {},
        createMany: {
          data: hosts.map(({ type, id }) => ({
            [`${type}Id`]: id,
          })),
        },
```

Keep in mind that the order of the keys is important as it reflects the order of the operations performed.
I'm assuming equivalent to set in terms of desired outcome as in the API [docs](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#set) it says: `Update an existing User record by disconnecting any previous Post records and connecting two other existing ones` (in case of M:N relationships disconnecting is equivalent the deleting the join table row).

I'm not sure if it's equivalent in term in performance, so if you have performance issues it might be better running a raw optimized query.

**Comment by josesilveiraa07** [comment]
Bump.

**Comment by GuyMevorachLevy** [comment]
Still reproducible, trying to use `set` on m:n and getting this error

**Comment by jkomyno** [comment]
I can reproduce this with Prisma 5.19.1, with the schema and snippet provided by @Deliana90.
The query fails on `prisma.role.create()`.

## Reproduction

- `schema.prisma`
  ```prisma
  generator client {
    provider  = "prisma-client-js"
  }
  
  datasource db {
    provider = "postgresql"
    url      = env("TEST_POSTGRES_URI")
  }
  
  model Role {
    id          Int    @id @default(autoincrement())
    name        String @unique
    description String
  
    permissions PermissionsOnRoles[]
  }
  
  model Permission {
    id          Int    @id @default(autoincrement())
    name        String @unique
    description String
  
    roles PermissionsOnRoles[]
  }
  
  model PermissionsOnRoles {
    permission   Permission @relation(fields: [permissionId], references: [id])
    permissionId Int
    role         Role       @relation(fields: [roleId], references: [id])
    roleId       Int
    description1 String
    description2 String
  
    @@id([permissionId, roleId])
  }
  ```
- `index.ts` snippet
  ```typescript
  import { PrismaClient } from 'prisma/client'
  
  async function main() {
    const prisma = new PrismaClient({
      log: [
        {
          emit: 'event',
          level: 'query',
        },
      ],
    })
  
    prisma.$on('query', ({ query, params }) => {
      console.log('[query]')
      console.dir({ query, params }, { depth: null })
      console.log('')
    })
  
    await prisma.permissionsOnRoles.deleteMany()
    await prisma.permission.deleteMany()
    await prisma.role.deleteMany()
  
    await prisma.role.create({
      data: {
        description: 'manager',
        name: 'manager',
        permissions: {
          create: [
            {
              description1: 'permission 11',
              description2: 'permission 12',
              permissionId: 1,
            },
            {
              description1: 'permission 31',
              description2: 'permission 32',
              permissionId: 3,
            },
          ],
        },
      },
    })
  
    process.exit(0)
  }
  
  void main().catch((e) => {
    console.log(e)
    process.exit(1)
  })
  ```
- Output
  ```
  ❯ ts-node index.ts

  [query]
  {
    query: 'DELETE FROM "public"."PermissionsOnRoles" WHERE 1=1',
    params: '[]'
  }
  
  [query]
  { query: 'DELETE FROM "public"."Permission" WHERE 1=1', params: '[]' }
  
  [query]
  { query: 'DELETE FROM "public"."Role" WHERE 1=1', params: '[]' }
  
  [query]
  { query: 'BEGIN', params: '[]' }
  
  [query]
  {
    query: 'INSERT INTO "public"."Role" ("name","description") VALUES ($1,$2) RETURNING "public"."Role"."id"',
    params: '["manager","manager"]'
  }
  
  [query]
  {
    query: 'INSERT INTO "public"."PermissionsOnRoles" ("description2","permissionId","roleId","description1") VALUES ($1,$2,$3,$4), ($5,$6,$7,$8)',
    params: '["permission 12",1,2,"permission 11","permission 32",3,2,"permission 31"]'
  }
  
  [query]
  { query: 'ROLLBACK', params: '[]' }
  
  PrismaClientKnownRequestError: 
  Invalid `prisma.role.create()` invocation in
  /Users/jkomyno/work/prisma/prisma/sandbox/basic-postgres/index.ts:23:21
  
    20 await prisma.permission.deleteMany()
    21 await prisma.role.deleteMany()
    22 
  → 23 await prisma.role.create(
  Foreign key constraint failed on the field: `PermissionsOnRoles_permissionId_fkey (index)`
      at Ln.handleRequestError (/Users/jkomyno/work/prisma/prisma/sandbox/basic-postgres/node_modules/.prisma/client/runtime/library.js:121:7753)
      at Ln.handleAndLogRequestError (/Users/jkomyno/work/prisma/prisma/sandbox/basic-postgres/node_modules/.prisma/client/runtime/library.js:121:7061)
      at Ln.request (/Users/jkomyno/work/prisma/prisma/sandbox/basic-postgres/node_modules/.prisma/client/runtime/library.js:121:6745)
      at async l (/Users/jkomyno/work/prisma/prisma/sandbox/basic-postgres/node_modules/.prisma/client/runtime/library.js:130:9633)
      at async main (/Users/jkomyno/work/prisma/prisma/sandbox/basic-postgres/index.ts:23:3) {
    code: 'P2003',
    clientVersion: '5.19.1-dev.3',
    meta: {
      modelName: 'Role',
      field_name: 'PermissionsOnRoles_permissionId_fkey (index)'
    }
  }
  ```

**Comment by jkomyno** [comment]
I've also realised that, if we remove extra fields from the explicit m:n model `PermissionsOnRoles` (namely: `description1` and `description2`), we can reformulate the query to obtain the intended outcome: to create a role and its permissions in a single Prisma Query.

## Alternative

- `schema.prisma`
  ```prisma
  generator client {
    provider  = "prisma-client-js"
  }
  
  datasource db {
    provider = "postgresql"
    url      = env("TEST_POSTGRES_URI")
  }
  
  model Role {
    id          Int    @id @default(autoincrement())
    name        String @unique
    description String
  
    permissions PermissionsOnRoles[]
  }
  
  model Permission {
    id          Int    @id @default(autoincrement())
    name        String @unique
    description String
  
    roles PermissionsOnRoles[]
  }
  
  model PermissionsOnRoles {
    permission   Permission @relation(fields: [permissionId], references: [id])
    permissionId Int
    role         Role       @relation(fields: [roleId], references: [id])
    roleId       Int
    description1 String
    description2 String
  
    @@id([permissionId, roleId])
  }
  ```

- `index.ts` snippet
  ```typescript
  import { PrismaClient } from '@prisma/client'
  
  async function main() {
    const prisma = new PrismaClient({
      log: [
        {
          emit: 'event',
          level: 'query',
        },
      ],
    })
  
    prisma.$on('query', ({ query, params }) => {
      console.log('[query]')
      console.dir({ query, params }, { depth: null })
      console.log('')
    })
  
    await prisma.permissionsOnRoles.deleteMany()
    await prisma.permission.deleteMany()
    await prisma.role.deleteMany()
  
    const managerRole = await prisma.role.create({
      include: {
        permissions: true,
      },
      data: {
        id: 1,
        name: 'manager',
        description: 'Manager role',
        permissions: {
          create: [
            {
              permission: {
                create: {
                  name: 'permission1',
                  description: 'First permission',
                },
              },
            },
            {
              permission: {
                create: {
                  name: 'permission2',
                  description: 'Second permission',
                },
              },
            },
          ],
        },
      },
    })
  
    console.dir(managerRole, { depth: null })
  
    process.exit(0)
  }
  
  void main().catch((e) => {
    console.log(e)
    process.exit(1)
  })
  ```
- Output:
  ```sh
  ❯ pnpm test

  [query]
  {
    query: 'DELETE FROM "public"."PermissionsOnRoles" WHERE 1=1',
    params: '[]'
  }
  
  [query]
  { query: 'DELETE FROM "public"."Permission" WHERE 1=1', params: '[]' }
  
  [query]
  { query: 'DELETE FROM "public"."Role" WHERE 1=1', params: '[]' }
  
  [query]
  { query: 'BEGIN', params: '[]' }
  
  [query]
  {
    query: 'INSERT INTO "public"."Role" ("id","name","description") VALUES ($1,$2,$3) RETURNING "public"."Role"."id"',
    params: '[1,"manager","Manager role"]'
  }
  
  [query]
  {
    query: 'INSERT INTO "public"."Permission" ("name","description") VALUES ($1,$2) RETURNING "public"."Permission"."id"',
    params: '["permission2","Second permission"]'
  }
  
  [query]
  {
    query: 'INSERT INTO "public"."PermissionsOnRoles" ("permissionId","roleId") VALUES ($1,$2) RETURNING "public"."PermissionsOnRoles"."permissionId", "public"."PermissionsOnRoles"."roleId"',
    params: '[1,1]'
  }
  
  [query]
  {
    query: 'INSERT INTO "public"."Permission" ("name","description") VALUES ($1,$2) RETURNING "public"."Permission"."id"',
    params: '["permission1","First permission"]'
  }
  
  [query]
  {
    query: 'INSERT INTO "public"."PermissionsOnRoles" ("permissionId","roleId") VALUES ($1,$2) RETURNING "public"."PermissionsOnRoles"."permissionId", "public"."PermissionsOnRoles"."roleId"',
    params: '[2,1]'
  }
  
  [query]
  {
    query: 'SELECT "public"."Role"."id", "public"."Role"."name", "public"."Role"."description" FROM "public"."Role" WHERE "public"."Role"."id" = $1 LIMIT $2 OFFSET $3',
    params: '[1,1,0]'
  }
  
  [query]
  {
    query: 'SELECT "public"."PermissionsOnRoles"."permissionId", "public"."PermissionsOnRoles"."roleId" FROM "public"."PermissionsOnRoles" WHERE "public"."PermissionsOnRoles"."roleId" IN ($1) OFFSET $2',
    params: '[1,0]'
  }
  
  [query]
  { query: 'COMMIT', params: '[]' }
  
  {
    id: 1,
    name: 'manager',
    description: 'Manager role',
    permissions: [ { permissionId: 1, roleId: 1 }, { permissionId: 2, roleId: 1 } ]
  }
  ```

If I also updated the manager's role by removing its permissions via

```typescript
const updatedManagerRole = await prisma.role.update({
  where: { id: 1 },
  data: {
    description: 'manager',
    name: 'manager',
    permissions: {
      set: [],
    },
  },
});

console.log('[updatedManagerRole]')
console.dir(updatedManagerRole, { depth: null })
```

then I'd get the following error:

> The change you are trying to make would violate the required relation 'PermissionsOnRolesToRole' between the `PermissionsOnRoles` and `Role` models.

Adding `onDelete: Cascade` to

```prisma
model PermissionsOnRoles {
  permission   Permission @relation(fields: [permissionId], references: [id], onDelete: Cascade)
  permissionId Int
  role         Role       @relation(fields: [roleId], references: [id])
  roleId       Int

  @@id([permissionId, roleId])
}
```

doesn't help either, and neither would removing the compound id via

```prisma
model PermissionsOnRoles {
  permission   Permission @relation(fields: [permissionId], references: [id], onDelete: Cascade)
  permissionId Int
  role         Role       @relation(fields: [roleId], references: [id])
  roleId       Int

  id          Int    @id @default(autoincrement())
}
```

## Removing the permissions

Here's how I managed to remove the permissions on the role `manager`:

```typescript
// ... use the previous `index.ts` snippet as a seed

await prisma.permissionsOnRoles.deleteMany({
  where: {
    role: {
      name: 'manager',
    },
  },
})

const updatedManagerRole = await prisma.role.findFirst({
  include: {
    permissions: true,
  },
  where: {
    name: 'manager',
  },
})

console.log('[updatedManagerRole]')
console.dir(updatedManagerRole, { depth: null })
```

Output:

```sh
[query]
{
  query: 'SELECT "public"."Role"."id", "public"."Role"."name", "public"."Role"."description" FROM "public"."Role" WHERE "public"."Role"."name" = $1 LIMIT $2 OFFSET $3',
  params: '["manager",1,0]'
}

[query]
{
  query: 'SELECT "public"."PermissionsOnRoles"."permissionId", "public"."PermissionsOnRoles"."roleId" FROM "public"."PermissionsOnRoles" WHERE "public"."PermissionsOnRoles"."roleId" IN ($1) OFFSET $2',
  params: '[1,0]'
}

[updatedManagerRole]
{
  id: 1,
  name: 'manager',
  description: 'Manager role',
  permissions: []
}
```
