### ISSUE TITLE
`pnpx prisma db push` exits with code 1

### ISSUE THREAD

**Issue by techboy-coder** [prisma/prisma#17053]
### Bug description

I'm trying to integrate prisma into my sveltekit project. I'm trying to do the initial migration with a local sqlite db. I'm using pnpm so I tried running `pnpx prisma db push` to run my first migration. (I also tried to run it with npx).

Error:
```bash
❯ pnpx prisma db push
.../Library/pnpm/store/v3/tmp/dlx-36791  | Progress:.../Library/pnpm/store/v3/tmp/dlx-36791  |   +2 +
.../Library/pnpm/store/v3/tmp/dlx-36791  | Progress:Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/shivramsambhus/Library/pnpm/store/v3
  Virtual store is at:             ../../../../../../Library/pnpm/store/v3/tmp/dlx-36791/node_modules/.pnpm
.../Library/pnpm/store/v3/tmp/dlx-36791  | Progress:.../Library/pnpm/store/v3/tmp/dlx-36791  | Progress: resolved 2, reused 2, downloaded 0, added 2, done
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

SQLite database dev.db created at file:./dev.db

🚀  Your database is now in sync with your Prisma schema. Done in 11ms

Running generate... (Use --skip-generate to skip the
 generators)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @eslint/eslintrc@1.4.0
npm WARN Found: peer eslint-plugin-jsdoc@">=22.1.0" from eslint-config-eslint@7.0.0
npm WARN node_modules/.pnpm/@eslint+eslintrc@1.4.0/node_modules/@eslint/eslintrc/node_modules/eslint-config-eslint
npm WARN   dev eslint-config-eslint@"^7.0.0" from @eslint/eslintrc@1.4.0
npm WARN   node_modules/.pnpm/@eslint+eslintrc@1.4.0/node_modules/@eslint/eslintrc
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-jsdoc@">=22.1.0" from eslint-config-eslint@7.0.0
npm WARN node_modules/.pnpm/@eslint+eslintrc@1.4.0/node_modules/@eslint/eslintrc/node_modules/eslint-config-eslint
npm WARN   dev eslint-config-eslint@"^7.0.0" from @eslint/eslintrc@1.4.0
npm WARN   node_modules/.pnpm/@eslint+eslintrc@1.4.0/node_modules/@eslint/eslintrc
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: debug@2.6.9
npm ERR! Found: dev karma-chai@"^0.1.0" from debug@2.6.9
npm ERR! node_modules/.pnpm/debug@2.6.9/node_modules/debug
npm ERR!   debug@2.6.9
npm ERR!   node_modules/.pnpm/websocket@1.0.34/node_modules/debug
npm ERR!     debug@"^2.2.0" from websocket@1.0.34
npm ERR!     node_modules/.pnpm/websocket@1.0.34/node_modules/websocket
npm ERR!       websocket@1.0.34
npm ERR!       node_modules/.pnpm/@supabase+realtime-js@2.1.0/node_modules/websocket
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev karma-chai@"^0.1.0" from debug@2.6.9
npm ERR! node_modules/.pnpm/debug@2.6.9/node_modules/debug
npm ERR!   debug@2.6.9
npm ERR!   node_modules/.pnpm/websocket@1.0.34/node_modules/debug
npm ERR!     debug@"^2.2.0" from websocket@1.0.34
npm ERR!     node_modules/.pnpm/websocket@1.0.34/node_modules/websocket
npm ERR!       websocket@1.0.34
npm ERR!       node_modules/.pnpm/@supabase+realtime-js@2.1.0/node_modules/websocket
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/shivramsambhus/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shivramsambhus/.npm/_logs/2022-12-28T17_18_40_321Z-debug-0.log
Error: Command failed with exit code 1: npm install @prisma/client@4.8.0
 ERROR  Command failed with exit code 1: /Users/shivramsambhus/Library/pnpm/store/v3/tmp/dlx-36791/node_modules/.bin/prisma db push

pnpm: Command failed with exit code 1: /Users/shivramsambhus/Library/pnpm/store/v3/tmp/dlx-36791/node_modules/.bin/prisma db push
    at makeError (/opt/homebrew/Cellar/pnpm/7.12.2/libexec/dist/pnpm.cjs:22289:17)
    at handlePromise (/opt/homebrew/Cellar/pnpm/7.12.2/libexec/dist/pnpm.cjs:22860:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler [as dlx] (/opt/homebrew/Cellar/pnpm/7.12.2/libexec/dist/pnpm.cjs:199043:7)
    at async /opt/homebrew/Cellar/pnpm/7.12.2/libexec/dist/pnpm.cjs:206407:21
    at async run (/opt/homebrew/Cellar/pnpm/7.12.2/libexec/dist/pnpm.cjs:206378:34)
    at async runPnpm (/opt/homebrew/Cellar/pnpm/7.12.2/libexec/dist/pnpm.cjs:206599:5)
    at async /opt/homebrew/Cellar/pnpm/7.12.2/libexec/dist/pnpm.cjs:206591:7
```

Additionally, I can't import my prisma client.

```ts
// error: Cannot find module '@prisma/client' or its corresponding type declarations.ts(2307)
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

### Expected behavior

I expected the migration to work and a prisma client to be generated.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id        Int     @id @default(autoincrement())
  email     String  @unique
  firstName String
  lastName  String
  motto     String?
  image     String?
  lastImage String?
  buy       Boolean @default(false)
}
```

```ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 
OS: Mac, DB: sqlite

package.json:
```json
{
	"name": "saasv1",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir . --write ."
	},
	"devDependencies": {
		"@sveltejs/adapter-auto": "^1.0.0",
		"@sveltejs/kit": "^1.0.0",
		"@typescript-eslint/eslint-plugin": "^5.45.0",
		"@typescript-eslint/parser": "^5.45.0",
		"autoprefixer": "^10.4.7",
		"eslint": "^8.28.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.14",
		"postcss-load-config": "^4.0.1",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.8.1",
		"prisma": "^4.8.0",
		"svelte": "^3.54.0",
		"svelte-check": "^2.9.2",
		"svelte-preprocess": "^4.10.7",
		"tailwindcss": "^3.1.5",
		"tslib": "^2.4.1",
		"typescript": "^4.9.3",
		"vite": "^4.0.0"
	},
	"type": "module",
	"dependencies": {
		"@supabase/auth-helpers-sveltekit": "^0.8.6",
		"@supabase/supabase-js": "^2.2.1"
	}
}

```

### Prisma Version

`pnpx prisma -v`
```bash
❯ pnpx prisma -v
 .../Library/pnpm/store/v3/tmp/dlx-37179  | Progress.../Library/pnpm/store/v3/tmp/dlx-37179  |   +2 +
.../Library/pnpm/store/v3/tmp/dlx-37179  | Progress:Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/shivramsambhus/Library/pnpm/store/v3
  Virtual store is at:             ../../../../../../Library/pnpm/store/v3/tmp/dlx-37179/node_modules/.pnpm
.../Library/pnpm/store/v3/tmp/dlx-37179  | Progress:.../Library/pnpm/store/v3/tmp/dlx-37179  | Progress: resolved 2, reused 2, downloaded 0, added 2, done
Environment variables loaded from .env
prisma                  : 4.8.0
@prisma/client          : Not found
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../../../../../Library/pnpm/store/v3/tmp/dlx-37179/node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../../../../../Library/pnpm/store/v3/tmp/dlx-37179/node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../../../../../Library/pnpm/store/v3/tmp/dlx-37179/node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at ../../../../../../Library/pnpm/store/v3/tmp/dlx-37179/node_modules/.pnpm/@prisma+engines@4.8.0/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by techboy-coder** [comment]
I was able to solve this issue: My pnpm store was using an outdated version of prisma (probably).
Running `pnpm install -D prisma@4.8.0` and `pnpm install @prisma/client@4.8.0` solved my problem.
