### ISSUE TITLE
After upgrade to version newer than 4.7.0: `TypeError: this.engine.dmmf is not a function` (workaround inside)

### ISSUE THREAD

**Issue by NikStepMnstr** [prisma/prisma#17070]
### Bug description

`2022-12-30T13:49:57.334Z	f7b358d7-cebe-4cd0-9dfa-9963d44d58fd	ERROR	TypeError: this.engine.dmmf is not a function
    at LibraryEngine.getDmmf (/opt/nodejs/node_modules/@prisma/client/runtime/index.js:27892:41)
    at async /opt/nodejs/node_modules/@prisma/client/runtime/index.js:35539:24 {
  clientVersion: '4.6.1'
}`

when running prisma client operations in AWS Lambda

### How to reproduce

It began with schema adjustment which renamed 1 table (droped and craeted) and its index name changein relations..

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Brand {
  brand_id           Int                @id @default(autoincrement())
  brand_name         String             @db.VarChar(255)
  corporation        String?            @db.VarChar(255)
  sectors            Sector[]
  markets            Market[]
  search_stims       SearchStim[]
  trend_mentions     MarketTrend[]
  brand_market_share BrandMarketShare[]
}

model Market {
  market_id          Int                @id @default(autoincrement())
  market_name        String             @db.VarChar(255)
  market_code        String             @db.VarChar(255)
  brands             Brand[]
  trends             Trend[]
  market_trend       MarketTrend[]
  brand_market_share BrandMarketShare[]
  related_queries    RelatedQuery[]
  BrandSearchTerm    BrandSearchTerm[]
  generic_term       GenericTerm[]
}

model Trend {
  date           DateTime   @db.Date
  trend          Float
  search_stim    SearchStim @relation(fields: [search_stim_id], references: [search_stim_id])
  search_stim_id Int
  market         Market     @relation(fields: [market_id], references: [market_id])
  market_id      Int

  @@id([date, search_stim_id, market_id])
}

model Sector {
  sector_id          Int                @id @default(autoincrement())
  sector_name        String             @unique
  brands             Brand[]
  brand_market_share BrandMarketShare[]
  generic_term       GenericTerm[]
}

model SearchStim {
  search_stim_id    Int               @id @default(autoincrement())
  search_stim       String            @unique
  type              String
  brand             Brand             @relation(fields: [brand_id], references: [brand_id])
  brand_id          Int
  description       String?
  trend             Trend[]
  related_queries   RelatedQuery[]
  BrandSearchTerm   BrandSearchTerm[]
  averageTrendValue Float?
}

model MarketTrend {
  market_trend_id   Int       @id @default(autoincrement())
  market            Market    @relation(fields: [market_id], references: [market_id])
  market_id         Int
  title             String
  traffic           Int
  date              DateTime?
  content           String
  associated_brands Brand[]
  source            Source?   @relation(fields: [source_id], references: [source_id])
  source_id         Int?
  url               String?
}

model Source {
  source_id Int           @id @default(autoincrement())
  source    String
  trend     MarketTrend[]
}

model BrandMarketShare {
  BrandMarketShare Int       @id @default(autoincrement())
  date             DateTime?
  brand            Brand     @relation(fields: [brand_id], references: [brand_id])
  brand_id         Int
  market           Market    @relation(fields: [market_id], references: [market_id])
  market_id        Int
  sector           Sector    @relation(fields: [sector_id], references: [sector_id])
  sector_id        Int
  share            Float
  is_term          Boolean   @default(false)
}

model RelatedQuery {
  type            String
  query           String
  value           Int
  market          Market            @relation(fields: [market_id], references: [market_id])
  market_id       Int
  search_stim     SearchStim        @relation(fields: [search_stim_id], references: [search_stim_id])
  search_stim_id  Int
  BrandSearchTerm BrandSearchTerm[]

  @@id([type, query, market_id, search_stim_id])
}

model BrandSearchTerm {
  competitiveness    Int
  market_association Float
  brand_association  Int
  category           Category      @relation(fields: [category_id], references: [category_id])
  category_id        Int
  related_query      RelatedQuery? @relation(fields: [type, query, market_id, search_stim_id], references: [type, query, market_id, search_stim_id])
  type               String
  query              String
  market             Market        @relation(fields: [market_id], references: [market_id])
  market_id          Int
  search_stim        SearchStim    @relation(fields: [search_stim_id], references: [search_stim_id])
  search_stim_id     Int

  @@id([type, query, market_id, search_stim_id])
}

model Category {
  category_id       Int               @id @default(autoincrement())
  category_name     String
  brand_search_term BrandSearchTerm[]
}

model GenericTerm {
  generic_term_id Int    @id @default(autoincrement())
  sector          Sector @relation(fields: [sector_id], references: [sector_id])
  sector_id       Int
  market          Market @relation(fields: [market_id], references: [market_id])
  market_id       Int
  type            String
  generic_term    String
}

```

### Environment & setup

AWS Lambda
- Database: PostgreSQL
- Node.js version: 16

### Prisma Version

```
  clientVersion: '4.6.1'

```

**Comment by ernstoarllano** [comment]
Were you able to resolve the issue?

**Comment by chynamyerz** [comment]
I am facing the same issue after upgrading to prisma 4.8. Any idea how to resolve this?

**Comment by chynamyerz** [comment]
> I am facing the same issue after upgrading to prisma 4.8. Any idea how to resolve this?

In my case, I deleted node_modules and yarn.lock, reinstalled packages, then all started to work again. @ernstoarllano maybe this can be helpful to you as well.

**Comment by ernstoarllano** [comment]
Deleting `node_modules` and reinstalling did the trick. 🚀

**Comment by janpio** [comment]
Hm, that is pretty unexpected. Any idea how to reproduce?

**Comment by ernstoarllano** [comment]
> Hm, that is pretty unexpected. Any idea how to reproduce?

I originally encountered the issue by simply updating to 4.8.

**Comment by tnobody** [comment]
Rerunning `npx prisma generate` (directly after installing/upgrading the version to 4.8) solves this problem for me

**Comment by marcalj** [comment]
In our case, it was a missing binary target. Development needed a different binary than deployed hosts:

To fix it we needed to add the binary target that our deployment environment needs:

```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}
```

PD: prisma@4.9.0

**Comment by ralcorta** [comment]
🚀 I fixed it as said above: I deleted `node_modules` folder and updated `Prisma` package to version  "^4.9.0".

```json
{
  "devDependencies": {
   "prisma": "^4.9.0",
  },
    "dependencies": {
      "@prisma/client": "^4.9.0",
  },
}
```
 

```sh
rm -rf node_modules
npm i prisma -D
prisma generate
```

**Comment by superjose** [comment]
I've been facing this same issue using Remix 1.13.0. 

Have done everything that has been outlined above to no avail.  Currently using Windows 10.

**Comment by superjose** [comment]
It is a caching issue. I cloned the repo somewhere else and was able to proceed without problems 🤔

**Comment by miku86** [comment]
Currently having this issue with NixOS, a NestJS app and tested this with prisma `4.8.1` and `4.11.0`.

I successfully used [this minimal nix shell](https://github.com/prisma/prisma/issues/3026#issuecomment-1439131599) to make `prisma generate` work.

I can start my application, but then I can't do anything with the database, because any database commands, either from the application or from prisma studio fails with `Message: Error in Prisma Client request: this.engine.dmmf is not a function`.

Unfortunately it seems that not so many people use the combo of NixOS and Prisma and I'm just a beginner with Nix, so I can't come up with any ideas.

**Comment by miku86** [comment]
After investing some additional hours into solving this issue, I had the simple idea to downgrade prisma to `4.6.0` in `package.json`, because this is the same as in the [current version in the stable Nix channel](https://search.nixos.org/packages?channel=22.11&show=prisma-engines&from=0&size=50&sort=relevance&type=packages&query=prisma-engines).

Now I can run `prisma generate` from the minimal shell and everything works as expected.

**Comment by sfratini** [comment]
To anyone coming here in 2024 and using serverless-webpack-prisma, keep in mind that the plugin automatically installs the last version of Prisma (I have no idea why), so you need to force it with the version property in serverless.yml or you get this as well. If you want to double check, we had our graphql deployed in a Lambda so you can download the zip in AWS, check the final package.json and find that you are indeed installing "^5.14.0" at the time of me writing this. I only put this together once I saw our builds breaking suddenly and Prisma releasing a new version 3 days ago. 
For reference we are using 4.16.2. 

Our pipeline builds everything and does a zip but then we have a separate release pipeline for serverless. That step was updating Prisma so I guess that is how we got the mismatch.

**Comment by SevInf** [comment]
Hey, the issue looks like a mistmatch between `@prisma/client` and `prisma` packages or missing `prisma generate` after the update. Does it still happen to anybody on prisma 5+?

**Comment by FGoessler** [comment]
Closing this due to inactivity.
