### ISSUE TITLE
Binary problems for tools using Prisma2/SDK as a dependency

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1710]
On some OSs the initial download of the binaries fails. We fix this by also downloading the binaries when you run `generate` and similar comments (related bug report: https://github.com/prisma/prisma2/issues/1699 that this does not happen on `migrate` right now).

But there is another case: Other tools that use Prisma2 or its SDK as a dependency and then try to use it.

Prisma-Viewer for example: https://github.com/williamluke4/prisma-viewer
https://github.com/williamluke4/prisma-viewer/blob/7eceb8124bce4edba9d84461dcc0698a6194284b/package.json#L24
https://github.com/williamluke4/prisma-viewer/blob/7eceb8124bce4edba9d84461dcc0698a6194284b/package.json#L35

@sorenbs and @lassebramer tried to install `prisma-viewer` on his machine but got this error then:

```
Error: Error: Could not find query-engine binary. Searched in /usr/local/lib/node_modules/prisma-viewer/node_modules/@prisma/sdk/query-engine-darwin and /usr/local/lib/node_modules/prisma-viewer/node_modules/@prisma/query-engine-darwin
    at /usr/local/lib/node_modules/prisma-viewer/node_modules/@prisma/sdk/dist/engineCommands.js:56:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/prisma-viewer/node_modules/@prisma/sdk/dist/engineCommands.js:5:58)
```

And that although they could run `prisma2 generate` successfully - but that only downloaded the binary for the `prisma2` install, not for `@prisma/sdk` (See error message).

**Comment by janpio** [comment]
(Maybe this could be fixed already by upgrading the versions in `prisma-viewer` - we are investigating this now)
