### ISSUE TITLE
`validate` gave success message, although it clearly did not and crashed

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1712]
The issue in https://github.com/prisma/prisma2/issues/1692 led to a clear crash and no schema being written, but it still said `The schema at ... is valid`.

Full output it gave was this:
```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:437:19)
    at writeOrBuffer (_stream_writable.js:425:5)
    at Socket.Writable.write (_stream_writable.js:316:11)
    at /home/runner/work/introspection-engine-output/introspection-engine-output/node_modules/prisma2/build/index.js:2:903601
    at new Promise (<anonymous>)
    at IntrospectionEngine.<anonymous> (/home/runner/work/introspection-engine-output/introspection-engine-output/node_modules/prisma2/build/index.js:2:902308)
    at Generator.next (<anonymous>)	
    at fulfilled (/home/runner/work/introspection-engine-output/introspection-engine-output/node_modules/prisma2/build/index.js:2:896611)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {	
  code: 'ERR_STREAM_DESTROYED'	
}	
Error: [/rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40] called `Option::unwrap()` on a `None` value	
The schema at /home/runner/work/introspection-engine-output/introspection-engine-output/mysql_127/VisualGenome.log is valid 
```

That is concerning and should be fixed, so future errors clearly lead to failures.

**Comment by pantharshit00** [comment]
This might not be relevant anymore as I can't reproduce this. 

![image](https://user-images.githubusercontent.com/22195362/77260018-37d2f100-6cab-11ea-883e-a937033a459d.png)

**Comment by janpio** [comment]
The underlying crash was fixed - I am not sure if the logic to ensure it only tells you it is valid if it actually is was improved :/
