### ISSUE TITLE
Decimal128 extended JSON not implemented yet.

### ISSUE THREAD

**Issue by ChilG** [prisma/prisma#17149]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.12.1           | 
| OS              | darwin-arm64       |
| Prisma Client   | 4.7.1              |
| Query Engine    | 272861e07ab64f234d3ffc4094e32bd61775599c|
| Database        | mongodb            |

Hi Prisma Dev

i can't use mongodb aggregate $facet

## Logs
```
Invalid `this.prisma.meterValue.aggregateRaw()` invocation in
/Users/chilgoe/Documents/2022/atom/atom-api-service/src/meter-value/meter-value.service.ts:840:35

  837 
  838 // return [];
  839 
→ 840 return this.prisma.meterValue.aggregateRaw(
Decimal128 extended JSON not implemented yet.

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v18.12.1+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+darwin-arm64+++++++%7C%0A%7C+Prisma+Client+++%7C+4.7.1++++++++++++++%7C%0A%7C+Query+Engine++++%7C+272861e07ab64f234d3ffc4094e32bd61775599c%7C%0A%7C+Database++++++++%7C+mongodb++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0A%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=Decimal128+extended+JSON+not+implemented+yet.&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

Error: 
Invalid `this.prisma.meterValue.aggregateRaw()` invocation in
/Users/chilgoe/Documents/2022/atom/atom-api-service/src/meter-value/meter-value.service.ts:840:35

  837 
  838 // return [];
  839 
→ 840 return this.prisma.meterValue.aggregateRaw(
Decimal128 extended JSON not implemented yet.

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v18.12.1+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+darwin-arm64+++++++%7C%0A%7C+Prisma+Client+++%7C+4.7.1++++++++++++++%7C%0A%7C+Query+Engine++++%7C+272861e07ab64f234d3ffc4094e32bd61775599c%7C%0A%7C+Database++++++++%7C+mongodb++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0A%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=Decimal128+extended+JSON+not+implemented+yet.&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at RequestHandler.handleRequestError (/Users/chilgoe/Documents/2022/atom/atom-api-service/node_modules/@prisma/client/runtime/index.js:34885:13)
    at RequestHandler.handleAndLogRequestError (/Users/chilgoe/Documents/2022/atom/atom-api-service/node_modules/@prisma/client/runtime/index.js:34841:12)
    at RequestHandler.request (/Users/chilgoe/Documents/2022/atom/atom-api-service/node_modules/@prisma/client/runtime/index.js:34836:12)
    at PrismaService._request (/Users/chilgoe/Documents/2022/atom/atom-api-service/node_modules/@prisma/client/runtime/index.js:35926:16)
    at TransactionController.transactionMeterValue (/Users/chilgoe/Documents/2022/atom/atom-api-service/src/transaction/transaction.controller.ts:327:20)
```

## Client Snippet
```ts
  private readonly countDocument = async (
    $match: Prisma.InputJsonValue,
  ): Promise<number> => {
    const countAggregate: any = await this.prisma.meterValue.aggregateRaw({
      pipeline: [{ $match }, { $count: 'amount' }],
    });

    return countAggregate[0] ? countAggregate[0].amount : 0;
  };

  private readonly aggregateMatchPipeline = (
    filter: MeterValueAggregateFilter,
  ): Prisma.InputJsonValue => {
    const {
      vin,
      transactionId,
      timestampBegin,
      timestampEnd,
      context,
      measurand,
    } = filter;

    let matchAppend;
    if (timestampBegin || timestampEnd) {
      matchAppend = {
        timestamp: {
          $gte: timestampBegin ? new Date(timestampBegin) : undefined,
          $lte: timestampEnd ? new Date(timestampEnd) : undefined,
        },
      };
    }

    const $match = {
      vin: vin ? vin : undefined,
      transaction: transactionId ? transactionId : undefined,
      context: context ? context : undefined,
      measurand: measurand ? measurand : undefined,
      ...matchAppend,
    };

    // Clean undefined
    return JSON.parse(JSON.stringify($match));
  };

  private readonly aggregate = (
    $match: Prisma.InputJsonValue,
    sample: number,
    count: number,
  ): Prisma.MeterValueAggregateRawArgs => {
    const $sort = {
      timestamp: 1,
    };

    let $facet;

    const $group = {
      _id: 0,
      id: { $first: '$_id' },
      vin: { $first: '$vin' },
      transaction: { $first: '$transaction' },
      timestamp: { $first: '$timestamp' },
      value: { $avg: { $toDecimal: '$value' } },
      valueMax: { $max: { $toDecimal: '$value' } },
      valueMin: { $min: { $toDecimal: '$value' } },
      context: { $first: '$context' },
      measurand: { $first: '$measurand' },
      format: { $first: '$format' },
      unit: { $first: '$unit' },
      createdAt: { $first: '$createdAt' },
    };

    if (count < sample * 10 || !sample) {
      $facet = {};
      for (let i = 0; i < count; i++) {
        if (i === 0) {
          $facet = {
            ...$facet,
            [`decimate_${i}`]: [{ $limit: 1 }, { $group }],
          };
        } else {
          $facet = {
            ...$facet,
            [`decimate_${i}`]: [{ $skip: i }, { $limit: 1 }, { $group }],
          };
        }
      }
    } else {
      $facet = {};
      const limit = Math.round(count / sample);
      for (let i = 0; i < count; i += sample) {
        if (i === 0) {
          $facet = {
            ...$facet,
            [`decimate_${i}`]: [{ $limit: limit }, { $group }],
          };
        } else {
          $facet = {
            ...$facet,
            [`decimate_${i}`]: [{ $skip: i }, { $limit: limit }, { $group }],
          };
        }
      }
    }

    const formatValue = [
      {
        $project: {
          result: {
            $objectToArray: '$$ROOT',
          },
        },
      },
      {
        $unwind: {
          path: '$result',
          preserveNullAndEmptyArrays: true,
        },
      },
      {
        $unwind: {
          path: '$result.v',
          preserveNullAndEmptyArrays: true,
        },
      },
      {
        $project: {
          id: '$result.v.id',
          vin: '$result.v.vin',
          transaction: '$result.v.transaction',
          timestamp: '$result.v.timestamp',
          value: '$result.v.value',
          valueMax: '$result.v.valueMax',
          valueMin: '$result.v.valueMin',
          context: '$result.v.context',
          measurand: '$result.v.measurand',
          format: '$result.v.format',
          unit: '$result.v.unit',
          createdAt: '$result.v.createdAt',
        },
      },
    ];

    const pipeline = [{ $match }, { $sort }];

    return {
      pipeline,
    };
  };

  async findAggregate(filter: MeterValueAggregateFilter) {
    const { sample } = filter;

    const $match: Prisma.InputJsonValue = this.aggregateMatchPipeline(filter);

    const count: number = await this.countDocument($match);

    if (count === 0) return [];

    const args = this.aggregate($match, sample, count);

    console.log(args);

    // return [];

    return this.prisma.meterValue.aggregateRaw(args);
  }
```

## Schema
```prisma
model MeterValue {
  id          String       @id @default(auto()) @map("_id") @db.ObjectId
  vin         String
  transaction String?
  timestamp   DateTime
  createdAt   DateTime     @default(now())
  value       String?
  context     String?
  format      String?
  measurand   String?
  unit        String?
  Vehicle     Vehicle      @relation(fields: [vin], references: [vin], onDelete: Cascade, onUpdate: NoAction)
  Transaction Transaction? @relation(fields: [transaction], references: [transactionId], onDelete: Cascade, onUpdate: NoAction)

  @@index([vin])
  @@index([transaction])
  @@index([createdAt])
  @@index([timestamp])
  @@index([measurand])
  @@index([context])
}
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by janpio** [comment]
Unfortunately known, the MongoDB driver that we use does not support Decimal128 yet: https://github.com/prisma/prisma/issues/16341
