### ISSUE TITLE
vercel/pkg into binary failed and throw "prebuild-install WARN install No prebuilt binaries found"

### ISSUE THREAD

**Issue by tatsuketer** [prisma/prisma#17173]
### Bug description

When I compile with `pkg` I have some problems, I don't know if it's a problem with my code, or with `vercel/pkg`, or with `prisma`.

Errors are **prebuild-install WARN install No prebuilt binaries found** and **Unable to load Node-API Library from /snapshot/tmp/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node, Library may be corrupt: UNEXPECTED-15**.

Here's the `package.json`:

```json
{
  "name": "tmp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "nodemon ."
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@prisma/client": "^4.8.1",
    "prisma": "^4.8.1"
  }
}
```

### How to reproduce

1. Run `npx prisma generate`.

```sh
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.8.1 | library) to ./node_modules/@prisma/client in 147ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

2. Compile **.ts** files with `tsc`.
3. Run `pkg -t node16-linux-x64 index.js -d` and output a binary named `index`.

```sh
/usr/local/lib/node_modules/pkg/node_modules/prebuild-install/util.js:13
    major: opts.pkg.version.split('.')[0],
                            ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Object.getDownloadUrl (/usr/local/lib/node_modules/pkg/node_modules/prebuild-install/util.js:13:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/pkg/node_modules/prebuild-install/bin.js:77:22)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

4. Then push the `version` field into `node_modules/.prisma/client/package.json`.
5. Run `pkg -t node16-linux-x64 index.js -d` again.

```sh
> [debug] prebuild-install failed[/home/geter/data/3-Subject/04-Production/CloudStation/tmp/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node]:
  Command failed: /usr/local/lib/node_modules/pkg/node_modules/.bin/prebuild-install --target v16.16.0 --platform linux --arch x64
prebuild-install WARN install No prebuilt binaries found (target=v16.16.0 runtime=node arch=x64 libc= platform=linux)
```

6. Try to specify the `asset` option into `package.json` and it looks like:

```json
"pkg": {
    "assets": [
      "node_modules/.prisma/client/*.node"
    ],
    "targets": [
      "node16-linux-x64"
    ]
}
```

7. Run `pkg -c package.json index.js`, errors show again.
8. Run `./index`.

```sh
/snapshot/tmp/node_modules/@prisma/client/runtime/index.js:35038
      throw new PrismaClientInitializationError(message, this.client._clientVersion);
            ^

PrismaClientInitializationError: 
Invalid `prisma.visit.findMany()` invocation:


Unable to load Node-API Library from /snapshot/tmp/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node, Library may be corrupt: UNEXPECTED-15
    at RequestHandler.handleRequestError (/snapshot/tmp/node_modules/@prisma/client/runtime/index.js:35038:13)
    at RequestHandler.handleAndLogRequestError (/snapshot/tmp/node_modules/@prisma/client/runtime/index.js:34996:12)
    at /snapshot/tmp/node_modules/@prisma/client/runtime/index.js:35542:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PrismaClient._executeRequest (/snapshot/tmp/node_modules/@prisma/client/runtime/index.js:36111:22)
    at async PrismaClient._request (/snapshot/tmp/node_modules/@prisma/client/runtime/index.js:36082:16) {
  clientVersion: '4.8.1',
  errorCode: undefined
}
```

### Expected behavior

`vercel/pkg` should output nothing and the binary file runs correctly.

### Prisma information

```prisma
generator client {
    provider      = "prisma-client-js"
    binaryTargets = ["debian-openssl-3.0.x"]
}

datasource db {
    provider = "sqlite"
    url      = "file:main.db"
}

model temp {
    ID Int @id @default(autoincrement())
}
```

```ts
import { PrismaClient } from "@prisma/client";

!async function () {
	console.log(await new PrismaClient().temp.findMany());
}();
```

### Environment & setup

- OS: Ubuntu Server 22.04LTS
- Database: SQLite
- Node.js version: v16.17.1

### Prisma Version

```
prisma                  : 4.8.1
@prisma/client          : 4.8.1
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/introspection-engine-debian-openssl-3.0.x)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
```

**Comment by janpio** [comment]
We have a test with `pkg` here: https://github.com/prisma/ecosystem-tests/tree/dev/binaries/pkg Have a look at the hacks this uses.

What do you mean by:

> Then push the version field into node_modules/.prisma/client/package.json.


?

**Comment by tatsuketer** [comment]
@janpio I have tried this test you mentioned a few days ago, but it didn't seem very helpful to me.

For the error ` major: opts.pkg.version.split('.')[0]`, which means that a certain package lacks a version field. After checking, I found that the problem lies in `.prisma/client`, so I filled in the missing field.

**Comment by janpio** [comment]
The test for example does this to make sure the engines are present:
https://github.com/prisma/ecosystem-tests/blob/65da4ba28828b32b7bd7918c5b5a9e2fcaa23c38/binaries/pkg/run.sh#L8-L9

Which version of `pkg` are you trying to use?

**Comment by tatsuketer** [comment]
v5.8.0 with `node16-linux-x64`.

**Comment by amiralam0** [comment]
same

**Comment by ParseDark** [comment]
same issue. And has been configuration the assets field.
```
  "pkg": {
    "assets": [
      "dist/**/*",
      "node_modules/.prisma/client/*.node",
      "node_modules/prisma"
    ],
    "targets": ["node18-win-x64", "node18-macos-x64"]
  },
```

<img width="1025" alt="image" src="https://github.com/prisma/prisma/assets/26950370/c145ee32-eab3-4049-9dc4-7871989f96ef">

**Comment by ParseDark** [comment]
> The test for example does this to make sure the engines are present: https://github.com/prisma/ecosystem-tests/blob/65da4ba28828b32b7bd7918c5b5a9e2fcaa23c38/binaries/pkg/run.sh#L8-L9↳
> 
> Which version of `pkg` are you trying to use?

This use case looks like not a real use case.

**Comment by janpio** [comment]
Why not? For our case this workaround (these 2 lines) make the project go from being broken, to working.

**Comment by ParseDark** [comment]
> Why not? For our case this workaround (these 2 lines) make the project go from being broken, to working.↳

Hi. @janpio  Because your test case only validation in the pkg snapshot can call the prisma. But prisma project also have other things.  Not sure why. But I think yes. I can prepare a Prisma toy project to validate my error case. Thanks for your response.

**Comment by ParseDark** [comment]
> Why not? For our case this workaround (these 2 lines) make the project go from being broken, to working.↳

Hi. @janpio  Do you mind try to re-produce pkg build prisma issue in this repo?

node & npm version
```
node -v
v16.20.1

npm -v
8.19.4
```

how to re-produce
```
npm install

npx prisma migrate dev

npm run build

// validation the bundle if you want 
node ./dist/index.js

// build with pkg
npm run pkg

// then run the executable file.
./executable/hello-prisma

```

https://github.com/ParseDark/pkg-build-prisma-project
```
./executable/hello-prisma
user
PrismaClientInitializationError:
Invalid `prisma.user.create()` invocation in
/snapshot/hello-prisma/dist/index.js:18:41

  15 console.log("user");
  16 function main() {
  17     return __awaiter(this, void 0, void 0, function* () {
→ 18         const user1 = yield prisma.user.create(
Error querying the database: unable to open database file: /snapshot/hello-prisma/node_modules/.prisma/client/dev.db
    at Rn.handleRequestError (/snapshot/hello-prisma/node_modules/@prisma/client/runtime/library.js:174:7601)
    at Rn.handleAndLogRequestError (/snapshot/hello-prisma/node_modules/@prisma/client/runtime/library.js:174:6754)
    at /snapshot/hello-prisma/node_modules/@prisma/client/runtime/library.js:177:3010
    at async /snapshot/hello-prisma/node_modules/@prisma/client/runtime/library.js:177:3225
    at async t._executeRequest (/snapshot/hello-prisma/node_modules/@prisma/client/runtime/library.js:177:11403) {
  clientVersion: '4.16.2',
  errorCode: undefined
}
```

**Comment by janpio** [comment]
Please open a new issue @ParseDark, this clearly has nothing to do with the problem that was originally reported in this issue. Make sure you fill all the details of the bug report issue template, as that includes information that is required for us. Thanks.

**Comment by ParseDark** [comment]
> Please open a new issue @ParseDark, this clearly has nothing to do with the problem that was originally reported in this issue. Make sure you fill all the details of the bug report issue template, as that includes information that is required for us. Thanks.
> 
> (Your reproduction for example is missing `pkg`, or the information which information to install globally)

Got it. Will create a new issue. Thanks @janpio
