### ISSUE TITLE
Error "P2000" does not behave as expected

### ISSUE THREAD

**Issue by mseifid** [prisma/prisma#17228]
### Bug description

I am using Prisma in a Node.js (Typescript) project to connect to a PostgreSQL database, so I wrote an error-handling layer to satisfy my scenario. Based on Prisma official documentation on [error-handling](https://www.prisma.io/docs/reference/api-reference/error-reference#error-codes), when a `P2000` error (value size exceeded for column type) occurs, the error object should contain the column name in the `meta` object. But, I get the following for columns with `String` type:
```
15 public async createCustomer(newCustomer: customer): Promise<boolean> {
  16
  17     try {
→ 18         let createRes = await this.db.customer.create(
The provided value for the column is too long for the column's type. Column: (not available)
    at RequestHandler.handleRequestError (D:\{dir}\node_modules\@prisma\client\runtime\index.js:35024:13)
    at RequestHandler.handleAndLogRequestError (D:\{dir}\node_modules\@prisma\client\runtime\index.js:34996:12)
    at RequestHandler.request (D:\{dir}\node_modules\@prisma\client\runtime\index.js:34991:12)
    at async PrismaClient._request (D:\{dir}\node_modules\@prisma\client\runtime\index.js:36082:16) {
  code: 'P2000',
  clientVersion: '4.8.0',
  meta: { column_name: '(not available)' },
  batchRequestIdx: undefined
}
```
And this is for the columns with `Int` type with no error code, however the problem is the same (value type size limit):
```
13 public async createTransaction(trx: transaction): Promise<boolean> {
  14     try {
→ 15         let createRes = await this.db.transaction.create(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(8), cause: Some(Error { kind: ConversionError("Unable to fit integer value '327672548787' into an INT2 (16-bit signed integer)."), original_code: None, original_message: None }) }) })
    at RequestHandler.handleRequestError (D:\{dir}\node_modules\@prisma\client\runtime\index.js:35033:13)
    at RequestHandler.handleAndLogRequestError (D:\{dir}\node_modules\@prisma\client\runtime\index.js:34996:12)
    at RequestHandler.request (D:\{dir}\node_modules\@prisma\client\runtime\index.js:34991:12)
    at async PrismaClient._request (D:\{dir}\node_modules\@prisma\client\runtime\index.js:36082:16) {
  clientVersion: '4.8.0',
  batchRequestIdx: undefined
}
```
So the Prisma here does not behave as expected and makes the error-handling very difficult.

### How to reproduce

1. Go to `schema.prisma` file
2. Create a model as follows for a PostgreSQL database
```
model Customer {
  customerId String @id @db.VarChar(5)
  orderWeight Int @db.SmallInt
}
```
3. Migrate using `npx prisma migrate dev --name initial` command.
4. Try to create a customer with a `customerId` longer than five characters OR an `orderWeight` larger than 32767.
5. Log the error and see it.

### Expected behavior

Get an error object including column name in `meta` object (and not `'(not available)'`) when the error code `P2000` occurs when a value larger (longer) than what determined in `schema.prisma` file is inserted into the database:
```
meta: { column_name: {column_name} }
```

### Prisma information

```prisma
model Customer {
  customerId String @id @db.VarChar(5)
  orderWeight Int @db.SmallInt
}
```
```ts
let newCustomer = {
   customerId: "123456",
   orderWeight: 12
};

let createRes = await this.db.customer.create({
     data: newCustomer
});
```

### Environment & setup

- OS:  Windows
- Database:  PostgreSQL
- Node.js version:  v16.14.2

### Prisma Version

```
4.8.0
```

**Comment by synerp** [comment]
Not sure if its related but I too have been seeing Column: (not available) in a P2022 in 4.8.1

**Comment by shwao** [comment]
Also having this issue with version 4.12.0. Can't figure out how to find the string thats too long. I'd rather not log every object.

`The provided value for the column is too long for the column's type. Column: (not available)`

**Comment by nick-carma** [comment]
Also seeing this issue in prisma 5.22.0
