### ISSUE TITLE
Prisma Client: unexpected color codes `"lightblue": [173, 216, 230],` in error stack when query fails 

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#17221]
### Bug description

In our CI (and probably not only? someone needs to try that) we can see Prisma Client errors with some colors in the stack, which is unexpected.

Examples, both for `prisma.user.create()`
- https://buildkite.com/prisma/test-prisma-typescript/builds/19001#01859b53-153f-46b4-a046-9fd6870c0fbf/280-6414
- https://github.com/prisma/prisma/actions/runs/3848169546/jobs/6555590302#step:10:5581
```
FAIL methods/upsert/simple/tests.ts (22.134 s)
  ● methods.upsert.simple (provider=sqlserver) › should update a record using upsert


    Invalid `prisma.user.create()` invocation in
    /home/ubuntu/actions-runner/_work/prisma/prisma/packages/client/tests/functional/methods/upsert/simple/tests.ts:33:23

      30 test('should update a record using upsert', async () => {
      31   const name = faker.name.firstName()
      32 
    → 33   await prisma.user.create(
    Unique constraint failed on the constraint: `dbo.User`

      567 |       "lightblue": [173, 216, 230],
      568 |       "lightcoral": [240, 128, 128],
    > 569 |       "lightcyan": [224, 255, 255],
          |                                    ^
      570 |       "lightgoldenrodyellow": [250, 250, 210],
      571 |       "lightgray": [211, 211, 211],
      572 |       "lightgreen": [144, 238, 144],

      at RequestHandler.handleRequestError (../../runtime/index.js:569:3667)
      at RequestHandler.handleAndLogRequestError (../../runtime/index.js:569:3003)
      at RequestHandler.request (../../runtime/index.js:569:2842)
      at PrismaClient._request (../../runtime/index.js:604:2811)
      at Object.<anonymous> (methods/upsert/simple/tests.ts:33:5)
```

This is unexpected
```
      567 |       "lightblue": [173, 216, 230],
      568 |       "lightcoral": [240, 128, 128],
    > 569 |       "lightcyan": [224, 255, 255],
          |                                    ^
      570 |       "lightgoldenrodyellow": [250, 250, 210],
      571 |       "lightgray": [211, 211, 211],
      572 |       "lightgreen": [144, 238, 144],
```

On the local setup I found a match in `prisma/packages/cli/node_modules/@prisma/client/generator-build/index.js`
```

// ../../node_modules/.pnpm/color-name@1.1.4/node_modules/color-name/index.js
var require_color_name = __commonJS({
  "../../node_modules/.pnpm/color-name@1.1.4/node_modules/color-name/index.js"(exports, module2) {
    "use strict";
    module2.exports = {
      "aliceblue": [240, 248, 255],
      "antiquewhite": [250, 235, 215],
      "aqua": [0, 255, 255],
      "aquamarine": [127, 255, 212],
      "azure": [240, 255, 255],
      "beige": [245, 245, 220],
      "bisque": [255, 228, 196],
      "black": [0, 0, 0],
      "blanchedalmond": [255, 235, 205],
      "blue": [0, 0, 255],
      "blueviolet": [138, 43, 226],
      "brown": [165, 42, 42],
      "burlywood": [222, 184, 135],
      "cadetblue": [95, 158, 160],
      "chartreuse": [127, 255, 0],
      "chocolate": [210, 105, 30],
      "coral": [255, 127, 80],
      "cornflowerblue": [100, 149, 237],
      "cornsilk": [255, 248, 220],
      "crimson": [220, 20, 60],
      "cyan": [0, 255, 255],
      "darkblue": [0, 0, 139],
      "darkcyan": [0, 139, 139],
      "darkgoldenrod": [184, 134, 11],
      "darkgray": [169, 169, 169],
      "darkgreen": [0, 100, 0],
      "darkgrey": [169, 169, 169],
      "darkkhaki": [189, 183, 107],
      "darkmagenta": [139, 0, 139],
      "darkolivegreen": [85, 107, 47],
      "darkorange": [255, 140, 0],
      "darkorchid": [153, 50, 204],
      "darkred": [139, 0, 0],
      "darksalmon": [233, 150, 122],
      "darkseagreen": [143, 188, 143],
      "darkslateblue": [72, 61, 139],
      "darkslategray": [47, 79, 79],
      "darkslategrey": [47, 79, 79],
      "darkturquoise": [0, 206, 209],
      "darkviolet": [148, 0, 211],
      "deeppink": [255, 20, 147],
      "deepskyblue": [0, 191, 255],
      "dimgray": [105, 105, 105],
      "dimgrey": [105, 105, 105],
      "dodgerblue": [30, 144, 255],
      "firebrick": [178, 34, 34],
      "floralwhite": [255, 250, 240],
      "forestgreen": [34, 139, 34],
      "fuchsia": [255, 0, 255],
      "gainsboro": [220, 220, 220],
      "ghostwhite": [248, 248, 255],
      "gold": [255, 215, 0],
      "goldenrod": [218, 165, 32],
      "gray": [128, 128, 128],
      "green": [0, 128, 0],
      "greenyellow": [173, 255, 47],
      "grey": [128, 128, 128],
      "honeydew": [240, 255, 240],
      "hotpink": [255, 105, 180],
      "indianred": [205, 92, 92],
      "indigo": [75, 0, 130],
      "ivory": [255, 255, 240],
      "khaki": [240, 230, 140],
      "lavender": [230, 230, 250],
      "lavenderblush": [255, 240, 245],
      "lawngreen": [124, 252, 0],
      "lemonchiffon": [255, 250, 205],
      "lightblue": [173, 216, 230],
      "lightcoral": [240, 128, 128],
      "lightcyan": [224, 255, 255],
      "lightgoldenrodyellow": [250, 250, 210],
      "lightgray": [211, 211, 211],
      "lightgreen": [144, 238, 144],
      "lightgrey": [211, 211, 211],
      "lightpink": [255, 182, 193],
      "lightsalmon": [255, 160, 122],
      "lightseagreen": [32, 178, 170],
      "lightskyblue": [135, 206, 250],
      "lightslategray": [119, 136, 153],
      "lightslategrey": [119, 136, 153],
      "lightsteelblue": [176, 196, 222],
      "lightyellow": [255, 255, 224],
      "lime": [0, 255, 0],
      "limegreen": [50, 205, 50],
      "linen": [250, 240, 230],
      "magenta": [255, 0, 255],
      "maroon": [128, 0, 0],
      "mediumaquamarine": [102, 205, 170],
      "mediumblue": [0, 0, 205],
      "mediumorchid": [186, 85, 211],
      "mediumpurple": [147, 112, 219],
      "mediumseagreen": [60, 179, 113],
      "mediumslateblue": [123, 104, 238],
      "mediumspringgreen": [0, 250, 154],
      "mediumturquoise": [72, 209, 204],
      "mediumvioletred": [199, 21, 133],
      "midnightblue": [25, 25, 112],
      "mintcream": [245, 255, 250],
      "mistyrose": [255, 228, 225],
      "moccasin": [255, 228, 181],
      "navajowhite": [255, 222, 173],
      "navy": [0, 0, 128],
      "oldlace": [253, 245, 230],
      "olive": [128, 128, 0],
      "olivedrab": [107, 142, 35],
      "orange": [255, 165, 0],
      "orangered": [255, 69, 0],
      "orchid": [218, 112, 214],
      "palegoldenrod": [238, 232, 170],
      "palegreen": [152, 251, 152],
      "paleturquoise": [175, 238, 238],
      "palevioletred": [219, 112, 147],
      "papayawhip": [255, 239, 213],
      "peachpuff": [255, 218, 185],
      "peru": [205, 133, 63],
      "pink": [255, 192, 203],
      "plum": [221, 160, 221],
      "powderblue": [176, 224, 230],
      "purple": [128, 0, 128],
      "rebeccapurple": [102, 51, 153],
      "red": [255, 0, 0],
      "rosybrown": [188, 143, 143],
      "royalblue": [65, 105, 225],
      "saddlebrown": [139, 69, 19],
      "salmon": [250, 128, 114],
      "sandybrown": [244, 164, 96],
      "seagreen": [46, 139, 87],
      "seashell": [255, 245, 238],
      "sienna": [160, 82, 45],
      "silver": [192, 192, 192],
      "skyblue": [135, 206, 235],
      "slateblue": [106, 90, 205],
      "slategray": [112, 128, 144],
      "slategrey": [112, 128, 144],
      "snow": [255, 250, 250],
      "springgreen": [0, 255, 127],
      "steelblue": [70, 130, 180],
      "tan": [210, 180, 140],
      "teal": [0, 128, 128],
      "thistle": [216, 191, 216],
      "tomato": [255, 99, 71],
      "turquoise": [64, 224, 208],
      "violet": [238, 130, 238],
      "wheat": [245, 222, 179],
      "white": [255, 255, 255],
      "whitesmoke": [245, 245, 245],
      "yellow": [255, 255, 0],
      "yellowgreen": [154, 205, 50]
    };
  }
});
```

### Expected behavior

At least no color codes, they are not relevant.

### Environment & setup

Probably unrelated to setup, see CI failures.

### Prisma Version

main branch, latest commit

**Comment by Jolg42** [comment]
New occurrence but for `deleteMany()`
```
  ● relationMode.tests_m-to-n (relationMode=prisma,provider=mysql,providerFlavor=vitess_8,onUpdate=Restrict,onDelete=Restrict,id=String @id, isSchemaUsingMap=true) › m:n mandatory (explicit) - SQL Databases › [create] › [create] post alone should succeed


    Invalid `prisma[categoriesOnPostsModel].deleteMany()` invocation in
    /home/runner/work/prisma/prisma/packages/client/tests/functional/relationMode/tests_m-to-n.ts:129:42

      126 
      127 beforeEach(async () => {
      128   const prismaPromises = [
    → 129     prisma[categoriesOnPostsModel].deleteMany(
    Error in connector: Error querying the database: Server error: `ERROR HY000 (1105): tablet: cell:"test" uid:79 is either down or nonexistent'

      501 |       "antiquewhite": [250, 235, 215],
      502 |       "aqua": [0, 255, 255],
    > 503 |       "aquamarine": [127, 255, 212],
          |                                     ^
      504 |       "azure": [240, 255, 255],
      505 |       "beige": [245, 245, 220],
      506 |       "bisque": [255, 228, 196],

      at RequestHandler.handleRequestError (../../runtime/index.js:503:3990)
      at RequestHandler.handleAndLogRequestError (../../runtime/index.js:503:3003)
      at RequestHandler.request (../../runtime/index.js:503:2842)
      at PrismaClient._request (../../runtime/index.js:538:2810)
```
https://github.com/prisma/prisma/actions/runs/3884582169/jobs/6627349299#step:10:710

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
