### ISSUE TITLE
Rust Panic when querying a model with @@id

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#1729]
Using this schema:
```
datasource db {
  provider = "postgresql"
  url      = "postgresql://siddhant@localhost:5432/experiments?schema=public"
}

generator client {
  provider = "prisma-client-js"
}

model AtAtId {
  @@id([ id, name ])

  id Int
  name String
}
```

and this script:
```
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

(async () => {
  await prisma.atAtId.findMany({
    after: {
      id_name: {
        id: 1,
        name: ""
      }
    }
  });

  await prisma.disconnect();
})();
```

I see this error: 
```
PANIC: called `Option::unwrap()` on a `None` value
    at PrismaClientFetcher.request (/Users/siddhant/Code/Tests/photon/node_modules/@prisma/client/index.js:90:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error in Prisma Client:
PANIC: called `Option::unwrap()` on a `None` value in
/rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
Please create an issue in https://github.com/prisma/prisma-client-js describing the last Prisma Client query you called.
```

**Comment by janpio** [comment]
What version exactly were you using @madebysid?

**Comment by madebysid** [comment]
Sorry, that’d be 2.0.0-alpha.842

**Comment by pantharshit00** [comment]
I can confirm this. 

![image](https://user-images.githubusercontent.com/22195362/75879556-95f57c80-5e41-11ea-99eb-705aaa82cf1f.png)


Even though I have the entry the database for which I am querying the database:
![image](https://user-images.githubusercontent.com/22195362/75879609-a7d71f80-5e41-11ea-83fb-5f19bb03c848.png)

**Comment by pantharshit00** [comment]
This is not reproducible now with `2.5` after changing `after` to `cursor` as to accommodate pagination changes:
![image](https://user-images.githubusercontent.com/22195362/90623015-9046f400-e233-11ea-8a65-4b26b886a96b.png)

```js
 const data = await prisma.atAtId.findMany({
    cursor: {
      id_name: {
        id: 1,
        name: "",
      },
    },
  });
```

Closing....
