### ISSUE TITLE
Bug: Using @ignore on a field that is used @@unique causes panic

### ISSUE THREAD

**Issue by leppaott** [prisma/prisma#17332]
### Bug description

Using `@ignore` on a field that is used inside `@@unique` (@@id too?), seems to either crash the generator or simply not generate the model at all without an error.

Such models:
```
  uuid String           @ignore @db.Uuid
  yes  String           @db.Uuid

  @@unique([uuid, yes])
```

````
`thread '<unnamed>' panicked at 'Error finding primary identifier: The parser field uuid does not exist in the query engine datamodel.', query-engine/prisma-models/src/model.rs:55:97
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    76518 IOT instruction (core dumped) prisma generate`
````

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by janpio** [comment]
Internal: `@ignore` removes a field from Client. Client needs at least one unique identified to work with a model. Should this possibly be invalid then, and setting an `@ignore`d field in Client disallowed?

**Comment by Druue** [comment]
Hey @leppaott,

I can confirm the following error message on versions `4.8.0` and `4.9.0`
```
thread '<unnamed>' panicked at 'Error finding primary identifier: The parser field uuid does not exist in the query engine datamodel.', query-engine/prisma-models/src/model.rs:49:97
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
zsh: abort      npx prisma migrate dev
```

On updating to `4.10.0` this changes to the following interactive prompt, this is due to updates around `getDMMF`, you can read more [here](https://github.com/prisma/prisma/pull/17533)
```
Oops, an unexpected error occurred!
unreachable

Please help us improve Prisma by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry

? Submit error report › - Use arrow-keys. Return to submit.
❯   Yes - Send error report once
    No
```

From `4.11.0` and onwards, I can no longer reproduce this error. I can't immediately see what happened here however there was work done around dmmf and schema validation this release too. However, as the field `uuid` is marked with `@ignore`, errors will still show up on create

```ts
> ts-node index.ts

prisma:query BEGIN
prisma:query INSERT INTO "public"."A" ("yes") VALUES ($1) RETURNING "public"."A"."uuid", "public"."A"."yes"
prisma:query ROLLBACK
PrismaClientKnownRequestError: 
Invalid `prisma.a.create()` invocation in
/src/prisma_debug/index.ts:20:18

  17 }
  18 
  19 const populate = async () => {
→ 20   await prisma.a.create(
Null constraint violation on the fields: (`uuid`)
    at Zr.handleRequestError (/src/prisma_debug/node_modules/@prisma/client/runtime/library.js:171:6414)
    at Zr.handleAndLogRequestError (/src/prisma_debug/node_modules/@prisma/client/runtime/library.js:171:5948)
    at Zr.request (/src/prisma_debug/node_modules/@prisma/client/runtime/library.js:171:5786)
    at async t._request (/src/prisma_debug/node_modules/@prisma/client/runtime/library.js:174:10455) {
  code: 'P2011',
  clientVersion: '4.11.0',
  meta: { constraint: [ 'uuid' ] }
}
```

---

Schema:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model A {
  uuid String @ignore @db.Uuid
  yes  String @db.Uuid

  @@unique([uuid, yes])
}
```

TS Code Used:
```ts
const prisma = new PrismaClient({
  log: ["query"],
});

function uuidv4() {
  return "10000000-1000-4000-8000-100000000000";
}

const populate = async () => {
  await prisma.a.create({
    data: {
      yes: uuidv4(),
    },
  });
};

async function test() {
  const a = await prisma.a.findFirst();
  console.log(a);
}

async function main() {
  await populate();
  return test();
}
```

**Comment by Druue** [comment]
Note: we don't provide any validation errors on the following either

```prisma
model A {
  uuid String @unique @ignore
}
```

**Comment by Druue** [comment]
As the panic issue has been resolved, I'll be closing this now and opening up a new issue for validations and the run-time error :)
