### ISSUE TITLE
`_relevance` error when utilizing `orderBy` relations

### ISSUE THREAD

**Issue by malbaugh** [prisma/prisma#17428]
### Bug description

Using `_relevance` fails when used with fields within a relation table.

```prisma:query BEGIN
prisma:query SELECT "public"."Parent"."id", "public"."Parent"."childId" FROM "public"."Parent" WHERE 1=1 ORDER BY ts_rank(to_tsvector(concat_ws(' ', "public"."Child"."name","public"."Child"."description","public"."Child"."notes")), to_tsquery($1)) DESC OFFSET $2
prisma:query ROLLBACK
Error - ParentUtils.fetch():  PrismaClientKnownRequestError: 
Invalid `prisma.parent.findMany()` invocation:


The table `(not available)` does not exist in the current database.
    at RequestHandler.handleRequestError (/node_modules/@prisma/client/runtime/index.js:35024:13)
    at RequestHandler.handleAndLogRequestError (/node_modules/@prisma/client/runtime/index.js:34996:12)
    at RequestHandler.request (/node_modules/@prisma/client/runtime/index.js:34991:12)
    at PrismaClient._request (/node_modules/@prisma/client/runtime/index.js:36082:16) {
  code: 'P2021',
  clientVersion: '4.8.1',
  meta: { table: '(not available)' },
  batchRequestIdx: 0
}
ERROR: Resource not found.
```

If `orderBy: { ... }` is removed, the query works without the table '{not available}' error.

### How to reproduce

Setup a parent & child table relation. Preform the query.

### Expected behavior

I would expect this to order results according to their relevance to the search query and the fields specified in the relation table.

### Prisma information

```prisma
model child {
  id          String              @id @default(uuid())
  name        String
  description String?
  notes       String?
  parent     Parent
}

model parent {
  id          String              @id @default(uuid())
  child     Child               @relation(fields: [childId], references: [id])
  childId  String              @unique
}
```

```ts
await prisma.parent.findMany({
          orderBy: {
            child: {
              _relevance: {
                fields: ['name', 'description', 'notes'],
                search: formattedQuery,
                sort: 'desc',
              },
            },
          },
})
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v16.16.0

### Prisma Version

```
prisma                  : 4.8.1
@prisma/client          : 4.8.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt d6e67a83f971b175a593ccc12e15c4a757f93ffe (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93ffe
Default Engines Hash    : d6e67a83f971b175a593ccc12e15c4a757f93ffe
Studio                  : 0.479.0
Preview Features        : fullTextSearch
```

**Comment by SimonRosengren** [comment]
Any updates on this? Im having the same issue in the same scenario.

**Comment by janpio** [comment]
Can one of you please [enable query logging](https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/logging#event-based-logging) and share the SQL queries that are created for this under the hood? What happens when you run them manually against the database?

**Comment by reubenjh** [comment]
I can't see an issue with the SQL, Card and Guardian both exist in the database

**Comment by reubenjh** [comment]
Ran the SQL direct against the database and got the following err

```
target: sorcery.-.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'Guardian.typeText' in 'order clause' (errno 1054) (sqlstate 42S22) (CallerID: c8wo5ic6laxzc2b6yedl): Sql: "select Card.id, Card.slug, Card.`name`, Card.hotscore from Card left join Guardian as j1 on j1.cardId = Card.id left join Guardian as j2 on j2.cardId = Card.id where match(j1.typeText) against (:vtg1 /* VARCHAR */ in boolean mode) and j1.id is not null or match(j2.rulesText) against (:vtg1 /* VARCHAR */ in boolean mode) and j2.id is not null or match(Card.`name`) against (:vtg1 /* VARCHAR */ in boolean mode) order by match(Card.`name`) against (:vtg1 /* VARCHAR */ in boolean mode) desc, match(Guardian.typeText, Guardian.rulesText) against (:vtg1 /* VARCHAR */ in boolean mode) asc limit :vtg2 /* INT64 */, :vtg3 /* INT64 */", BindVars: {REDACTED}
```
