### ISSUE TITLE
`P2002` error doesn't include meaningful meta with SQL Server

### ISSUE THREAD

**Issue by pete-otaqui** [prisma/prisma#17433]
### Bug description

I have a unique constraint on a `name` field in a table.  When I try and update one record with the same name as another one, I correctly get a `PrismaKnownClientError`.

So, when I do this:

```js
prismaClient.thing.update({
  where: { id: 1 },
  data: { name: 'Thing 2' }
});
```

I get an error thrown like this:

```js
{
  code: 'P2002',
  clientVersion: '4.9.0',
  meta: { target: 'dbo.Thing' },
}
```

As you can see, the "target" is the name of the _table_ rather than the name of the _field_.

If I manually a similar query against the database using Azure Data Studio like this (which tries to set the name of one Thing to the same as that of another):

```sql
UPDATE [dbo].[Thing]
SET [name] = 'Thing 2'
WHERE [dbo].[Umbrella].[id] = 1
```

I can see that SQL Server itself gives back the following message:

```
Violation of UNIQUE KEY constraint 'Thing_name_key'.
Cannot insert duplicate key in object 'dbo.Thing'. The
duplicate key value is (Test Thing 2).
```

I understand that this does not include the column name directly, but I would assume that prisma ought to be able to get the relevant column name(s) from the constraint name that is provided.

### How to reproduce

Trigger a unique constraint error on update (or in fact, on create), and inspect the error object.

### Expected behavior

I expect the error object `meta` to include something like `fields`, `target`, or `constraint` so that I can provide meaningful error messages myself.

See https://github.com/prisma/prisma/issues/10829 for a similar request.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}
datasource db {
  provider          = "sqlserver"
  url               = env("SQL_SERVER_DB_URL")
  shadowDatabaseUrl = env("SQL_SERVER_SHADOW_DB_URL")
}
model Thing {
  id              Int          @id @default(autoincrement())
  name            String       @unique
}
```

```ts
// Add your code using Prisma Client
const prismaClient = new PrismaClient();
await prismaClient.thing.create({ name: 'Thing' });
await prismaClient.thing.create({ name: 'Thing 2'});

// this is where the error is thrown
```
await prismaClient.thing.update({
  where: { id: 1 },
  data: { name: 'Thing 2' },
});
```

### Environment & setup

- OS: macOS (M1 chip), Azure SQL Edge in Docker
- Database: SQL Server
- Node.js version: 16.6


### Prisma Version

```
4.9.0
```

**Comment by dev-xo** [comment]
Getting the same error code @pete-otaqui.
Error message is this: `Unique constraint failed on the fields: (`userId`)`

Hope we get some help.

**Comment by pete-otaqui** [comment]
Thanks for looking @dev-xo, let me know if there's any more information I can provide, or other testing you'd like me to do (in other environments / with a specific branch of prisma, etc)

**Comment by BryanDGuy** [comment]
I've made a similar feature request here https://github.com/prisma/prisma/issues/15046. Would love to see this come to fruition. Even just allowing us to access the raw error thrown by the DB would be great help.

**Comment by AlimovSV** [comment]
any updates?

**Comment by EricDotSmith** [comment]
Just ran into this issue too. If the error was more meaningful I would've saved lots of time debugging.

**Comment by andriiwp3** [comment]
I just ran into this issue as well. I'm trying to debug it, but I feel like some kind of error message could save me a lot of time

**Comment by daiho-nfq** [comment]
same here 

<img width="784" alt="image" src="https://github.com/prisma/prisma/assets/61769800/c1e85546-e10c-4332-9ea0-8b1803d8cd0e">

**Comment by janpio** [comment]
@daiho-nfq Isn't that the name of the constraint that is failing in your database? To me this looks as good as it can get on a database level.

**Comment by BryanDGuy** [comment]
@janpio DB's also relay what _value_ is violating the unique constraint, not just the column name. In this case, it'd be good to know that it's the user `Thing 2` that's violating the unique constraint.

**Comment by BryanDGuy** [comment]
Understood. I don’t intend to hijack the thread of the original poster, so I’ll let them make a case for a bug versus feature request.

I opened a feature request for this in the past https://github.com/prisma/prisma/issues/15046, so I’m more than happy to plug that as the “feature request” split off of this, if you think there is sufficient information outlined in that issue.

**Comment by janpio** [comment]
Nice flex to be able to point to a feature request from August last year 🤣  Thanks!

**Comment by janpio** [comment]
Back to the original report for SQL Server:

Running the script:
```ts
  await prisma.thing.create({ data: { name: 'Thing' }});
  await prisma.thing.create({ data: { name: 'Thing 2'}});

  // this is where the error is thrown
  await prisma.thing.update({
    where: { id: 1 },
    data: { name: 'Thing 2' },
  });
```

Indeed throws this error:
```
PrismaClientKnownRequestError: 
Invalid `prisma.thing.update()` invocation in
C:\Users\Jan\Documents\throwaway\19963\script.js:10:22

   7 await prisma.thing.create({ data: { name: 'Thing 2'}});
   8
   9 // this is where the error is thrown
→ 10 await prisma.thing.update(
Unique constraint failed on the constraint: `dbo.Thing`
    at In.handleRequestError (C:\Users\Jan\Documents\throwaway\19963\node_modules\@prisma\client\runtime\library.js:122:6877)
    at In.handleAndLogRequestError (C:\Users\Jan\Documents\throwaway\19963\node_modules\@prisma\client\runtime\library.js:122:6211)
    at In.request (C:\Users\Jan\Documents\throwaway\19963\node_modules\@prisma\client\runtime\library.js:122:5919)
    at async l (C:\Users\Jan\Documents\throwaway\19963\node_modules\@prisma\client\runtime\library.js:127:11167)
    at async main (C:\Users\Jan\Documents\throwaway\19963\script.js:10:3) {
  code: 'P2002',
  clientVersion: '5.14.0',
  meta: { modelName: 'Thing', target: 'dbo.Thing' }
}
```

And then the manual equivalent SQL via another database client directly:
```sql
UPDATE [dbo].[Thing] SET [name] = 'Thing 2' WHERE ([dbo].[Thing].[id] = 1
```
returns this error message:
```
SQL Error [2627] [23000]: Violation of UNIQUE KEY constraint 'Thing_name_key'. Cannot insert duplicate key in object 'dbo.Thing'. The duplicate key value is (Thing 2).
```

As @pete-otaqui identified, Prisma currently only parses the object name `dbo.Thing` for its error message and `target`, but the error message also includes the constraint name `Thing_name_key` and value `Thing 2`. It might be possible to go from the constraint name to the affected column in many cases.

**Comment by janpio** [comment]
Aside: @daiho-nfq's screenshot indicates that for some other Non SQL Server database Prisma might return the constraint name as the target, instead of the object name. This might indicate some inconsistency in how Prisma utilized the `target` property.

**Comment by shaununderwood** [comment]
Guys, this bug is > 18 months old, can we get some closure?

**Comment by janpio** [comment]
Happy to take a look at any pull request you opened @shaununderwood and see if it fixes the problem. If you didn't open one, then we will get to it when we have the capacity to figure this out ourselves. That can take some time, as you can see we have many open feature requests and also bug reports and are doing our best to work on them in a prioritized manner that will affect most of our users. Thanks for understanding.

**Comment by iagomissias** [comment]
tive esse retorno no terminal após realizar o teste  de descrição de dados via POST,

PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation:


Unique constraint failed on the constraint: `User_email_key`
    at qn.handleRequestError (/home/iago/Sistema-de-Login/node_modules/@prisma/client/runtime/library.js:121:7315)
    at qn.handleAndLogRequestError (/home/iago/Sistema-de-Login/node_modules/@prisma/client/runtime/library.js:121:6640)
    at qn.request (/home/iago/Sistema-de-Login/node_modules/@prisma/client/runtime/library.js:121:6347)
    at async l (/home/iago/Sistema-de-Login/node_modules/@prisma/client/runtime/library.js:130:9616)
    at async file:///home/iago/Sistema-de-Login/server.js:12:6 {
  code: 'P2002',
  clientVersion: '6.1.0',
  meta: { modelName: 'User', target: 'User_email_key' }
}

mesmo rodando 
$:npx prisma migrate dev --name add_age_field

ele não corrige o erro

porem ao realizar o inserimento manual no banco de dados o mesmo aceita como isso é possivel

**Comment by Shahor** [comment]
> Also I'm seeing that in Postgres the `meta.target` of a compound index comes as an array and not the name of the unique index.
> 
> For example if I have: `@@unique([name, code], map: "name_code_idx")`
> 
> The error P2002 `meta.target` in Postgres is an array: `["name", "code"]`
> 
> but in MongoDB `meta.target` is an string `"name_code_idx"`

Having the same exact issue right now and it seems there is no way to obtain the actual database error as Prisma seems to insist on providing its own rewrite of it.

I've tried running a raw query as well, but my understanding is that this rewrite might be happening on the intermediate rust part instead so I suppose there's no way for me to know about the actual real error that happened and that means I can't differentiate the types of error happening in my application. 

What is the rationale behind Prisma rewriting the error? We're losing actual information from the database, and it makes handling issues more difficult than it needs to be. 

At the very least, can we maybe have the original information somewhere in the `meta` array?

**Comment by jason-jos** [comment]
It's probably because the data you are creating, already exists in your db

**Comment by capaj** [comment]
I just updated to rust-free client and there is nothing on `error.meta.target`

I hackfixed it with  https://github.com/authier-pm/authier/commit/769195df362d20a91c3f9f9b6ec24e3f99187fcd

but this suxx.
bring `meta.target` back pls
