### ISSUE TITLE
Running prisma from CLI causes TypeError

### ISSUE THREAD

**Issue by flikkr** [prisma/prisma#17459]
### Bug description

When I try running `npx run prisma` from my terminal, the following error message appears after asking me to install the `run` package. I tried deleting my node_modules director, package-lock.json file and doing a fresh reinstall by running npm install but this error keeps showing up.

```
Watching /Users/username/Projects/myproject/app/server and all sub-directories not excluded by your .gitignore. Will not monitor dotfiles.
/Users/username/.npm/_npx/755986f37193a6d8/node_modules/run/run.js:127
        if (minimatch(file, pattern)) {
            ^

TypeError: minimatch is not a function
    at /Users/username/.npm/_npx/755986f37193a6d8/node_modules/run/run.js:127:13
    at Array.forEach (<anonymous>)
    at parseFolder (/Users/username/.npm/_npx/755986f37193a6d8/node_modules/run/run.js:113:9)
    at Object.<anonymous> (/Users/username/.npm/_npx/755986f37193a6d8/node_modules/run/run.js:63:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)

Node.js v19.3.0
```

### How to reproduce

1. Install prisma as a local npm dependency
2. Run `npx run prisma`

### Expected behavior

Prisma CLI should work

### Prisma information

-

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 19.3.0

### Prisma Version

```
4.9.0
```

**Comment by flikkr** [comment]
I'm dumb, the command I was looking for is `npx prisma`
