### ISSUE TITLE
Error(replit): Unable to establish a connection to query-engine-node-api library. It seems there is a problem with your OpenSSL installation!

### ISSUE THREAD

**Issue by AyanavaKarmakar** [prisma/prisma#17635]
I keep getting this error whenever I try to run `npx prisma generate` in Replit.

![image](https://user-images.githubusercontent.com/89210438/215489629-31387054-aa43-4821-9187-50db734dec92.png)

I was able to fix the error before by updating the `replit.nix` file with `pkgs.openssl` like this:

```nix
{ pkgs }: {
    deps = [
        pkgs.yarn
        pkgs.esbuild
        pkgs.nodejs-16_x

        pkgs.nodePackages.typescript
        pkgs.nodePackages.typescript-language-server
      
        pkgs.openssl
    ];
}
```

The error showed up again after [updating my schema](https://github.com/TypeSafe-Travellers/trippins/pull/85). Not sure what is the problem here. Maybe, I'm missing something. `npx prisma generate` works fine on branches before the schema is changed

_converted to a new issue as @janpio suggested_

_Originally posted by @AyanavaKarmakar in https://github.com/prisma/prisma/discussions/17621_

**Comment by janpio** [comment]
I can reproduce this:

1. https://replit.com/new/nodejs
2. `npm install prisma` in the right hand "Shell"
3. `npx prisma -v` there as well returns:
```
~/EuphoricEmbarrassedTrialsoftware$ npx prisma -v
Error: Unable to require(`/home/runner/EuphoricEmbarrassedTrialsoftware/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`)
 libssl.so.1.1: cannot open shared object file: No such file or directory
    at load (/home/runner/EuphoricEmbarrassedTrialsoftware/node_modules/prisma/build/index.js:91073:11)
    at getEngineVersion (/home/runner/EuphoricEmbarrassedTrialsoftware/node_modules/prisma/build/index.js:91870:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
prisma                  : 4.9.0
@prisma/client          : Not found
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.9.0-42.ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Default Engines Hash    : ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Studio                  : 0.479.0
~/EuphoricEmbarrassedTrialsoftware$
```

**Comment by janpio** [comment]
For the CLI I could also work around this by forcing the engine type to binary via setting an env variable `PRISMA_CLI_QUERY_ENGINE_TYPE=binary`:
```
~/EuphoricEmbarrassedTrialsoftware$ export PRISMA_CLI_QUERY_ENGINE_TYPE=binary
~/EuphoricEmbarrassedTrialsoftware$ npx prisma -v
prisma                : 4.9.0
@prisma/client        : Not found
Current platform      : debian-openssl-1.1.x
Query Engine (Binary) : query-engine ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine      : migration-engine-cli ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine  : introspection-core ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary         : prisma-fmt ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Format Wasm           : @prisma/prisma-fmt-wasm 4.9.0-42.ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Default Engines Hash  : ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Studio                : 0.479.
``` 

The equivalent for Prisma Client would be to set `engineType = "binary"` in the `generator` block of the Prisma Schema.

**Comment by janpio** [comment]
Just fixing the CLI is not enough though, you get the same error when using a generated Client as well:

```
~/EuphoricEmbarrassedTrialsoftware$ node script.js
PrismaClientInitializationError: 
Invalid `prisma.user.create()` invocation in
/home/runner/EuphoricEmbarrassedTrialsoftware/script.js:8:35

  5 // A `main` function so that we can use async/await
  6 async function main() {
  7   // Seed the database with users and posts
→ 8   const user1 = await prisma.user.create(
Unable to load Node-API Library from /home/runner/EuphoricEmbarrassedTrialsoftware/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node, Library may be corrupt: libssl.so.1.1: cannot open shared object file: No such file or directory
    at RequestHandler.handleRequestError (/home/runner/EuphoricEmbarrassedTrialsoftware/node_modules/@prisma/client/runtime/index.js:31955:13)
    at RequestHandler.handleAndLogRequestError (/home/runner/EuphoricEmbarrassedTrialsoftware/node_modules/@prisma/client/runtime/index.js:31913:12)
    at /home/runner/EuphoricEmbarrassedTrialsoftware/node_modules/@prisma/client/runtime/index.js:32458:25
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PrismaClient._executeRequest (/home/runner/EuphoricEmbarrassedTrialsoftware/node_modules/@prisma/client/runtime/index.js:33022:22)
    at async PrismaClient._request (/home/runner/EuphoricEmbarrassedTrialsoftware/node_modules/@prisma/client/runtime/index.js:32994:16)
    at async main (/home/runner/EuphoricEmbarrassedTrialsoftware/script.js:8:17) {
  clientVersion: '4.9.0',
  errorCode: undefined
}
```

The equivalent for Prisma Client to the env var for CLI is to set `engineType = "binary"` in the `generator` block of the Prisma Schema. Run `npx prisma generate` and the script works.

**Comment by AyanavaKarmakar** [comment]
> The equivalent for Prisma Client to the env var for CLI is to set `engineType = "binary"` in 
 the `generator` block of the Prisma Schema. Run `npx prisma generate` and the script works

Just tried this. Now, I can run `npx prisma generate` in the "shell" successfully.

![image](https://user-images.githubusercontent.com/89210438/215727295-bbc28fb8-e1b3-4330-a451-14e55c4f724c.png)

But, when I click on `Run` (`npm run dev`) button at the top. The error shows up again in the console. The site _works_ for a few seconds, then crashes.

![image](https://user-images.githubusercontent.com/89210438/215726342-0320dc62-5d0a-4734-95fd-6dc87e809843.png)

![image](https://user-images.githubusercontent.com/89210438/215730140-3a1e971d-81ce-4317-82f5-a0c4f27b6c30.png)

**Comment by janpio** [comment]
How did you set the environment variable?

I forked https://github.com/TypeSafe-Travellers/trippins and then imported it on replit: https://replit.com/@janpio/trippins For me it is currently failing because of missing env vars. What is the simplest way to get those or skip that requirement?

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
❌ Invalid environment variables:
 DATABASE_URL: Required
 NEXTAUTH_URL: Required
 GITHUB_CLIENT_ID: Required
 GITHUB_CLIENT_SECRET: Required
 GOOGLE_CLIENT_ID: Required
 GOOGLE_CLIENT_SECRET: Required
 EMAIL_SERVER_USER: Required
 EMAIL_SERVER_PASSWORD: Required
 EMAIL_SERVER_HOST: Required
 EMAIL_SERVER_PORT: Required
 EMAIL_FROM: Required

error - Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Invalid environment variables
    at file:///home/runner/trippins/src/env/server.mjs:16:9
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async file:///home/runner/trippins/next.config.mjs:9:4
exit status 1
```

**Comment by janpio** [comment]
I think I got it to work by setting all the required env variables in the "Secrets" tabs:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/183673/215877045-3f808cab-f5f9-4735-8145-ce5281df9d58.png">

I used nonsensical values, so nothing works of course. Here is the raw view:
```
{
  "DATABASE_URL": "mysql://root@127.0.0.1:3309/typesafetravellers",
  "NEXTAUTH_SECRET": "dsfasdfasdf",
  "GITHUB_CLIENT_ID": "123",
  "GITHUB_CLIENT_SECRET": "123",
  "GOOGLE_CLIENT_ID": "123",
  "GOOGLE_CLIENT_SECRET": "123",
  "EMAIL_FROM": "asdfsfd@kshdfsfd.de",
  "EMAIL_SERVER_PORT": "123",
  "EMAIL_SERVER_HOST": "asdfsdf",
  "EMAIL_SERVER_USER": "sdf",
  "EMAIL_SERVER_PASSWORD": "dfsd",
  "PRISMA_CLI_QUERY_ENGINE_TYPE": "binary",
  "NEXTAUTH_URL": "http://localhost:3000"
}
```
(I also added `engineType = "binary"` to the `generator block, as described above)

**Comment by AyanavaKarmakar** [comment]
I deleted my repl and created a new one. Added my secrets including `"PRISMA_CLI_QUERY_ENGINE_TYPE": "binary"` & updated the `generator` block with `engineType = "binary"`. The site loads up fine. However, it crashes when I try to log in. 

Sometimes, the console shows a prisma related error when the site crashes. Something like `p.unique... etc doesn't exist please regenerate again`. I wasn't able to take a screenshot of that error since the error only shows up rarely. I'm gonna take a screenshot when the error shows up again ASAP.

This error shows up every time when I click on `run` 

![image](https://user-images.githubusercontent.com/89210438/215890760-0f8484c4-f2ae-4cb3-9e8d-e27b8122c193.png)

Can you check if your repl also shows the same error when clicked on `Run`? Sometimes the error stays in the console but usually gets overwritten when replit tries to re-run `npm run dev`.

The code works fine when deployed on Netlify. Another strange thing is that this error only showed up when I updated the schema. The replit site was working fine before.

Replit Site: https://trippins.ayanavakarmakar.repl.co
Replit Repo: https://replit.com/@AyanavaKarmakar/trippins?v=1
Netlify Site: https://trippins.netlify.app/

**Comment by janpio** [comment]
As long as it is trying to load a file that ends in `.so.node` it is not actually using the binary.
I can unfortunately not really tell if this is sometimes happening in the Console, as when there is something red it just reloads and I end up with a working app as far as I can tell.

On the bottom left I can also see that Replit is majorly stretched on CPU and memory to run this app: 
<img width="272" alt="image" src="https://user-images.githubusercontent.com/183673/215905331-f653ccdf-ee2c-42d0-8553-38d51b9003c4.png">

I did quickly set up my own MySQL database and push to it with `prisma db push` - and I got some queries working:
```
 npm run dev

> trippins@0.1.3 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 7.5s (288 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 11.7s (891 modules)
wait  - compiling /api/auth/[...nextauth] (client and server)...
event - compiled successfully in 761 ms (160 modules)
prisma:query SELECT `black_urial`.`User`.`id`, `black_urial`.`User`.`name`, `black_urial`.`User`.`email`, `black_urial`.`User`.`emailVerified`, `black_urial`.`User`.`image` FROM `black_urial`.`User` WHERE (`black_urial`.`User`.`email` = ? AND 1=1) LIMIT ? OFFSET ?
[next-auth][error][SIGNIN_EMAIL_ERROR] 
https://next-auth.js.org/errors#signin_email_error getaddrinfo ENOTFOUND asdfsdf {
  error: {
    message: 'getaddrinfo ENOTFOUND asdfsdf',
    stack: 'Error: getaddrinfo ENOTFOUND asdfsdf\n' +
      '    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)',
    name: 'Error'
  },
  providerId: 'email',
  message: 'getaddrinfo ENOTFOUND asdfsdf'
}
prisma:query BEGIN
prisma:query INSERT INTO `black_urial`.`VerificationToken` (`identifier`,`token`,`expires`) VALUES (?,?,?)
prisma:query SELECT `black_urial`.`VerificationToken`.`token`, `black_urial`.`VerificationToken`.`identifier`, `black_urial`.`VerificationToken`.`expires` FROM `black_urial`.`VerificationToken` WHERE `black_urial`.`VerificationToken`.`token` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
```

So to me it looks like this is working with the binary engine:
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/183673/215905978-61297434-9b2d-4478-bb88-6c6a12bd0a0f.png">

**Comment by aqrln** [comment]
With latest Prisma there are no errors when generating the client (because the CLI is not using the query engine anymore) but queries, as expected, fail with:

```
PrismaClientKnownRequestError: 
Invalid `prisma.user.findMany()` invocation in
/home/runner/LightheartedWeeklyUtilities/index.js:5:33

  2 
  3 async function main() {
  4   const prisma = new PrismaClient();
→ 5   console.log(await prisma.user.findMany(
libssl.so.1.1: cannot open shared object file: No such file or directory
    at Zr.handleRequestError (/home/runner/LightheartedWeeklyUtilities/node_modules/@prisma/client/runtime/library.js:171:6414)
    at Zr.handleAndLogRequestError (/home/runner/LightheartedWeeklyUtilities/node_modules/@prisma/client/runtime/library.js:171:5948)
    at /home/runner/LightheartedWeeklyUtilities/node_modules/@prisma/client/runtime/library.js:174:3087
    at async /home/runner/LightheartedWeeklyUtilities/node_modules/@prisma/client/runtime/library.js:174:3268
    at async t._executeRequest (/home/runner/LightheartedWeeklyUtilities/node_modules/@prisma/client/runtime/library.js:174:10726)
    at async t._request (/home/runner/LightheartedWeeklyUtilities/node_modules/@prisma/client/runtime/library.js:174:10455)
    at async main (/home/runner/LightheartedWeeklyUtilities/index.js:5:15) {
  code: 'ERR_DLOPEN_FAILED',
  clientVersion: '4.11.0',
  meta: undefined
}
```

The reason why the binary engine works, and why none of our checks we have added show any warnings is because the operating system that replit uses in their VMs is regular Ubuntu 20.04 with OpenSSL 1.1 available in `/lib/x86_64-linux-gnu/libssl.so.1.1`. Nix is used on top as a package manager, it's not NixOS. So there's nothing wrong from the point of view of checks in `@prisma/get-platform`, and standalone binaries compiled for Debian/Ubuntu like `query-engine` and `migration-engine` work without any issues since they are being loaded by Ubuntu's system loader.

However, when using the library engine inside Nix-provided Node.js, it is being loaded with `dlopen` from Nix-provided `glibc` which knows nothing about Ubuntu's system libraries.

Adding `pkgs.openssl` to `deps` in `replit.nix` won't solve the problem because the full path to OpenSSL in Nix store needs to be embedded in the Query Engine library. The easiest way is to use Prisma engines from nixpkgs rather than relying on our builds.

Here's an example of how you can do this: https://replit.com/@aqrln/InsistentStunningPoints#shell.nix (notice that I switched from simplified `replit.nix` to standard `shell.nix` [which replit also supports](https://docs.replit.com/programming-ide/nix-on-replit#the-replitnix-file) to be able to add a `shellHook`.

This way Prisma's library engine works on replit, but you need to be careful to make sure your Prisma client and engines versions don't diverge.

**Comment by jesper-bylund** [comment]
Tried @aqrln 's solution above. But can't get my Replit to run the new nix file without errors.
Does this mean that prisma is currently not useable on replit at all?

**Comment by jesper-bylund** [comment]
@aqrln installing prisma@latest gives me the same as OP

![image](https://github.com/prisma/prisma/assets/186083/8c6f0f9f-935a-4fba-ac6a-bb78251a15ca)

Trying to use your nix variation (I'm a NIX noob so might be having issues) lands me in a crash loop.

**Comment by jesper-bylund** [comment]
Prisma client v 4.11 btw

**Comment by jesper-bylund** [comment]
For others finding this, my error was that I still had a file called `replit.nix` as soon as I renamed it `replit.nix.bak` @aqrln's replit example above started working for me!

Thanks @aqrln
