### ISSUE TITLE
`Error: ENOENT: no such file or directory, open '/.../workspaces/server/dist/schema.prisma'` in NestJS server app in Yarn monorepo

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#17630]
(Note: This issue is patched together from multiple comments that @Geebrox correctly left in some related comments. They were slightly misleading as they used a integration version of Prisma Client that led to another error message, and the repository also already included the workaround activated which led to false negatives when trying to reproduce the problem. This issue tries to fix that.)

When using Prisma Client in a Nestjs appliation in a monorepo, you can get a `Error: ENOENT: no such file or directory, open '/.../workspaces/server/dist/schema.prisma'` error.

This is the reproduction: https://github.com/janpio/next-nest-mono/tree/nestjs-enoent-schema

Steps to reproduce:

1. Clone the repo
2. Install dependencies (yarn install)
3. Populate `.env` vars (via `.env.example`)
4. Run dev command (`yarn dev`)
5. Open site running at localhost:3000
6. Observer error in terminal

## Workaround

A workaround is already included in `/workspaces/server/webpack.config.js` and just needs to be uncommented:

```
externals: [
    nodeExternals({
      // additionalModuleDirs: [path.resolve(__dirname, '../../node_modules')],
      allowlist: ['webpack/hot/poll?100'],
    }),
  ],
```

Removing the `//` for `additionalModuleDirs` (remove them, then start `yarn dev` new) make Prisma Client work in this project.

Thanks so much @Geebrox for the great reproduction and explanation what was going on.

**Comment by janpio** [comment]
This reproduction has also been used in our issue about testing an inlined schema, which only surfaces another error when retrieving the Query Engine: https://github.com/prisma/prisma/issues/13233#issuecomment-1120427039

It was also used in this standalone issue: https://github.com/prisma/prisma/issues/13460

**Comment by basememara** [comment]
The `node_modules` folder its pointing to `additionalModuleDirs` wasn't compatible for me in a commonjs vs esm scenario so it gives this error instead: `Error: Cannot find module '@prisma/client'`. I have a Next and Nest app in my monorepo that share a Prisma package so each `node_modules` is compiled differently.

I believe the [Next.js team pinpointed the issue](https://github.com/vercel/next.js/issues/46070#issuecomment-1457672050) about `new URL()` should be used instead of `__dirname` to derive the paths in the Prisma client. I know you're already on that thread, but digging the rabbit hole deeper for anyone else stumbling on this post.

Thanks for all the help, you all have been amazing trying to get to the bottom of this with all the samples, suggestions, workarounds, and replies. Seems promising and hopefully this resolves the root issue across all stacks and scenarios once and for all.

**Comment by basememara** [comment]
This was fixed in `v4.15`!! Thank you Prisma team!!!

Now I can keep my Prisma schema and logic in a single shared package in a monorepo and use it within my NestJS and Next.js apps. I still have to use the `@prisma/nextjs-monorepo-workaround-plugin` workaround package in my Next.js app but that's ok for now. At least now I don't have to duplicate the Prisma schema's across apps in a monorepo, and also no longer do I have to hoist them in a yarn workspace! Amazing work 👍🏽

**Comment by janpio** [comment]
I can confirm that for @Geebrox original reproduction as well.

Before:
```
gitpod /workspace/next-nest-mono (nestjs-enoent-schema) $ yarn dev
yarn run v1.22.19
$ cross-env NODE_ENV=development yarn pretify "yarn client dev" "yarn server dev"
$ concurrently --kill-others-on-fail -p " {name} " -n "CLIENT,SERVER" -c "bgBlue.bold,bgCyan.bold" 'yarn client dev' 'yarn server dev'
$ dotenv -e .env yarn workspace server dev
$ dotenv -e .env yarn workspace client dev
$ next dev
$ yarn prebuild && webpack --watch
 CLIENT  ready - started server on 0.0.0.0:3000, url: http://localhost:3000
$ rimraf dist && yarn prisma:build
 CLIENT  warn  - You have enabled experimental feature(s).
 CLIENT  warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
 CLIENT  
 CLIENT  warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
$ yarn prisma:generate 2>&1 > /dev/null
 CLIENT  Browserslist: caniuse-lite is outdated. Please run:
 CLIENT    npx browserslist@latest --update-db
 CLIENT    Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 CLIENT  wait  - compiling...
 SERVER  asset main.js 3.69 MiB [emitted] (name: main)
 SERVER  orphan modules 192 KiB [orphan] 86 modules
 SERVER  runtime modules 23.5 KiB 9 modules
 SERVER  modules by path ../../node_modules/ 3.07 MiB 260 modules
 SERVER  modules by path ./src/ 17 KiB
 SERVER    modules by path ./src/*.ts 5.73 KiB 5 modules
 SERVER    modules by path ./src/modules/todos/ 8.3 KiB 5 modules
 SERVER    ./src/utils/validation.utils.ts 2.97 KiB [built] [code generated]
 SERVER  modules by path external "@nestjs/ 252 bytes
 SERVER    external "@nestjs/common" 42 bytes [built] [code generated]
 SERVER    external "@nestjs/core" 42 bytes [built] [code generated]
 SERVER    + 4 modules
 SERVER  optional modules 84 bytes [optional]
 SERVER    external "worker_threads" 42 bytes [optional] [built] [code generated]
 SERVER    external "diagnostics_channel" 42 bytes [optional] [built] [code generated]
 SERVER  + 26 modules
 SERVER  webpack 5.72.1 compiled successfully in 2065 ms
 CLIENT  event - compiled client and server successfully in 5.5s (984 modules)
 CLIENT  Attention: Next.js now collects completely anonymous telemetry regarding usage.
 CLIENT  This information is used to shape Next.js' roadmap and prioritize features.
 CLIENT  You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
 CLIENT  https://nextjs.org/telemetry
 CLIENT  
 CLIENT  Browserslist: caniuse-lite is outdated. Please run:
 CLIENT    npx browserslist@latest --update-db
 CLIENT    Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 CLIENT  wait  - compiling / (client and server)...
 CLIENT  wait  - compiling...
 CLIENT  event - compiled client and server successfully in 310 ms (987 modules)
 SERVER  (node:2026) [FST_MODULE_DEP_FASTIFY-COOKIE] FastifyWarning.fastify-cookie: fastify-cookie has been deprecated. Use @fastify/cookie@6.0.0 instead.
 SERVER  (Use `node --trace-warnings ...` to show where the warning was created)
 SERVER  [Nest] 2026  - 06/01/2023, 3:55:38 PM     LOG [NestFactory] Starting Nest application...
 SERVER  [Nest] 2026  - 06/01/2023, 3:55:38 PM   ERROR [ExceptionHandler] ENOENT: no such file or directory, open '/workspace/next-nest-mono/workspaces/server/dist/schema.prisma'
 SERVER  Error: ENOENT: no such file or directory, open '/workspace/next-nest-mono/workspaces/server/dist/schema.prisma'
 SERVER      at Object.openSync (node:fs:601:3)
 SERVER      at Object.readFileSync (node:fs:469:35)
 SERVER      at new LibraryEngine (webpack://server/../../node_modules/@prisma/client/runtime/index.js?:44573:41)
 SERVER      at PrismaService.getEngine (webpack://server/../../node_modules/@prisma/client/runtime/index.js?:49531:16)
 SERVER      at new PrismaClient (webpack://server/../../node_modules/@prisma/client/runtime/index.js?:49503:29)
 SERVER      at new PrismaService (webpack://server/./src/prisma.service.ts?:14:21)
 SERVER      at Injector.instantiateClass (/workspace/next-nest-mono/workspaces/server/node_modules/@nestjs/core/injector/injector.js:330:19)
 SERVER      at callback (/workspace/next-nest-mono/workspaces/server/node_modules/@nestjs/core/injector/injector.js:48:41)
 SERVER      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 SERVER      at async Injector.resolveConstructorParams (/workspace/next-nest-mono/workspaces/server/node_modules/@nestjs/core/injector/injector.js:122:24)
 CLIENT  wait  - compiling /_error (client and server)...
 CLIENT  wait  - compiling...
 CLIENT  event - compiled client and server successfully in 157 ms (988 modules)
 ```
 
 After upgrade to 4.15.0:
 ```
 gitpod /workspace/next-nest-mono (nestjs-enoent-schema) $ yarn upgrade prisma@latest @prisma/client@latest
yarn upgrade v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "workspace-aggregator-3cec2875-e6e0-4d46-9f29-7ec9675f4b74 > client > react-feather@2.0.9" has incorrect peer dependency "react@^16.8.6 || ^17".
warning "workspace-aggregator-3cec2875-e6e0-4d46-9f29-7ec9675f4b74 > client > @chakra-ui/react > @chakra-ui/modal > react-remove-scroll@2.4.1" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning "workspace-aggregator-3cec2875-e6e0-4d46-9f29-7ec9675f4b74 > client > @chakra-ui/react > @chakra-ui/modal > @chakra-ui/focus-lock > react-focus-lock@2.5.2" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
[5/5] Rebuilding all packages...
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
├─ @prisma/client@4.15.0
└─ prisma@4.15.0
info All dependencies
├─ @prisma/client@4.15.0
├─ @prisma/engines-version@4.15.0-28.8fbc245156db7124f997f4cecdd8d1219e360944
└─ prisma@4.15.0
Done in 15.89s.
gitpod /workspace/next-nest-mono (nestjs-enoent-schema) $ yarn dev
yarn run v1.22.19
$ cross-env NODE_ENV=development yarn pretify "yarn client dev" "yarn server dev"
$ concurrently --kill-others-on-fail -p " {name} " -n "CLIENT,SERVER" -c "bgBlue.bold,bgCyan.bold" 'yarn client dev' 'yarn server dev'
$ dotenv -e .env yarn workspace server dev
$ dotenv -e .env yarn workspace client dev
$ next dev
$ yarn prebuild && webpack --watch
 CLIENT  ready - started server on 0.0.0.0:3000, url: http://localhost:3000
$ rimraf dist && yarn prisma:build
 CLIENT  warn  - You have enabled experimental feature(s).
 CLIENT  warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.
 CLIENT  
 CLIENT  warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
$ yarn prisma:generate 2>&1 > /dev/null
 CLIENT  wait  - compiling...
 CLIENT  event - compiled client and server successfully in 3.4s (984 modules)
 CLIENT  Browserslist: caniuse-lite is outdated. Please run:
 CLIENT    npx browserslist@latest --update-db
 CLIENT    Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 CLIENT  wait  - compiling / (client and server)...
 CLIENT  wait  - compiling...
 CLIENT  wait  - compiling /_error (client and server)...
 CLIENT  wait  - compiling...
 CLIENT  event - compiled client and server successfully in 1296 ms (988 modules)
 SERVER  asset main.js 1.17 MiB [emitted] (name: main)
 SERVER  orphan modules 192 KiB [orphan] 86 modules
 SERVER  runtime modules 23.5 KiB 9 modules
 SERVER  modules by path ../../node_modules/ 743 KiB 260 modules
 SERVER  modules by path ./src/ 17 KiB
 SERVER    modules by path ./src/*.ts 5.73 KiB 5 modules
 SERVER    modules by path ./src/modules/todos/ 8.3 KiB 5 modules
 SERVER    ./src/utils/validation.utils.ts 2.97 KiB [built] [code generated]
 SERVER  modules by path external "@nestjs/ 252 bytes
 SERVER    external "@nestjs/common" 42 bytes [built] [code generated]
 SERVER    external "@nestjs/core" 42 bytes [built] [code generated]
 SERVER    external "@nestjs/platform-fastify" 42 bytes [built] [code generated]
 SERVER    external "@nestjs/config" 42 bytes [built] [code generated]
 SERVER    + 2 modules
 SERVER  + 11 modules
 SERVER  webpack 5.72.1 compiled successfully in 3388 ms
 SERVER  (node:2977) [FST_MODULE_DEP_FASTIFY-COOKIE] FastifyWarning.fastify-cookie: fastify-cookie has been deprecated. Use @fastify/cookie@6.0.0 instead.
 SERVER  (Use `node --trace-warnings ...` to show where the warning was created)
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:15 PM     LOG [NestFactory] Starting Nest application...
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:15 PM     LOG [InstanceLoader] AppModule dependencies initialized +39ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:15 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:15 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:15 PM     LOG [InstanceLoader] TodosModule dependencies initialized +1ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:15 PM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:15 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:15 PM     LOG [RoutesResolver] TodosController {/api/todos}: +5ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:15 PM     LOG [RouterExplorer] Mapped {/api/todos, POST} route +3ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:16 PM     LOG [RouterExplorer] Mapped {/api/todos, GET} route +1ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:16 PM     LOG [RouterExplorer] Mapped {/api/todos/:id, GET} route +1ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:16 PM     LOG [RouterExplorer] Mapped {/api/todos/:id, PATCH} route +0ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:16 PM     LOG [RouterExplorer] Mapped {/api/todos/:id, DELETE} route +1ms
 SERVER  [Nest] 2977  - 06/01/2023, 3:57:16 PM   ERROR [Bootstrap] Error: The provided database string is invalid. MongoDB connection string error: invalid connection string scheme: mongo in database URL. Please refer to the documentation in https://www.prisma.io/docs/reference/database-reference/connection-urls for constructing a correct connection string. In some cases, certain characters must be escaped. Please check the string for any illegal characters.
```

That this error message complains about my fake `DATABASE_URL="mongo://foo.bar"` connection string indicates that the schema and engine file is now correctly found and executed.

**Comment by janpio** [comment]
Can you maybe confirm that in the real project @Geebrox? Thanks.

**Comment by millsp** [comment]
Internal discussion https://prisma-company.slack.com/archives/C04DG9JL6TV/p1685603621595009
