### ISSUE TITLE
Debugging Migration Engine: Add `--datamodel` information to debug log

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#17657]
Real world example:
```
C:\Users\Jan\Documents\throwaway\prisma_migrate_debug>npx prisma migrate resolve --applied 0_init
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"
Error: P3017

The migration 0_init could not be found. Please make sure that the migration exists, and that you included the whole name of the directory. (example: "20201207184859_initial_migration")
```

With `DEBUG=*`:
```
C:\Users\Jan\Documents\throwaway\prisma_migrate_debug>set DEBUG=*

C:\Users\Jan\Documents\throwaway\prisma_migrate_debug>npx prisma migrate resolve --applied 0_init
  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\.env +0ms
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +2ms
  prisma:loadEnv  project root found at C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\package.json +10ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\.env +7ms
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig  Using getConfig Wasm +5ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +2ms
Datasource "db": SQLite database "dev.db" at "file:./dev.db"
  prisma:getConfig  Using getConfig Wasm +2ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +5ms
  prisma:migrateEngine:rpc  starting migration engine with binary: C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\node_modules\@prisma\engines\migration-engine-windows.exe +0ms
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"markMigrationApplied","params":{"migrationsDirectoryPath":"C:\\Users\\Jan\\Documents\\throwaway\\prisma_migrate_debug\\prisma\\migrations","migrationName":"0_init"}} +4ms
  prisma:migrateEngine:stderr  {"timestamp":"2023-01-31T17:37:26.3325371Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5"},"target":"migration_engine"} +0ms
  prisma:migrateEngine:rpc  {
  jsonrpc: '2.0',
  error: {
    code: 4466,
    message: 'An error happened. Check the data field for details.',
    data: {
      is_panic: false,
      message: 'The migration 0_init could not be found. Please make sure that the migration exists, and that you included the whole name of the directory. (example: "20201207184859_initial_migration")',
      meta: [Object],
      error_code: 'P3017'
    }
  },
  id: 1
} +11ms
Error: Error: P3017

The migration 0_init could not be found. Please make sure that the migration exists, and that you included the whole name of the directory. (example: "20201207184859_initial_migration")

    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\node_modules\prisma\build\index.js:95044:25)
    at MigrateEngine.handleResponse (C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\node_modules\prisma\build\index.js:94897:36)
    at LineStream2.<anonymous> (C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\node_modules\prisma\build\index.js:94997:16)
    at LineStream2.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at LineStream2._pushBuffer (C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\node_modules\prisma\build\index.js:94752:17)
    at LineStream2._transform (C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\node_modules\prisma\build\index.js:94746:8)
    at Transform._write (node:internal/streams/transform:175:8)
```

Relevant bits for Migration Engine:
```
  prisma:migrateEngine:rpc  starting migration engine with binary: C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\node_modules\@prisma\engines\migration-engine-windows.exe +0ms
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"markMigrationApplied","params":{"migrationsDirectoryPath":"C:\\Users\\Jan\\Documents\\throwaway\\prisma_migrate_debug\\prisma\\migrations","migrationName":"0_init"}} +4ms
  prisma:migrateEngine:stderr  {"timestamp":"2023-01-31T17:37:26.3325371Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5"},"target":"migration_engine"} +0ms
  prisma:migrateEngine:rpc  {
  jsonrpc: '2.0',
  error: {
    code: 4466,
    message: 'An error happened. Check the data field for details.',
    data: {
      is_panic: false,
      message: 'The migration 0_init could not be found. Please make sure that the migration exists, and that you included the whole name of the directory. (example: "20201207184859_initial_migration")',
      meta: [Object],
      error_code: 'P3017'
    }
  },
  id: 1
} +11ms
```

Running the `.exe` manually and then inputting the JSON unfortunately leads to an error as `--datamodel` is not supplied:
```
C:\Users\Jan\Documents\throwaway\prisma_migrate_debug>C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\node_modules\@prisma\engines\migration-engine-windows.exe
{"id":1,"jsonrpc":"2.0","method":"markMigrationApplied","params":{"migrationsDirectoryPath":"C:\\Users\\Jan\\Documents\\throwaway\\prisma_migrate_debug\\prisma\\migrations","migrationName":"0_init"}}
{"jsonrpc":"2.0","error":{"code":4466,"message":"An error happened. Check the data field for details.","data":{"is_panic":false,"message":"Missing --datamodel\n","backtrace":null}},"id":1}
```

This on the other hand works:
```
C:\Users\Jan\Documents\throwaway\prisma_migrate_debug>C:\Users\Jan\Documents\throwaway\prisma_migrate_debug\node_modules\@prisma\engines\migration-engine-windows.exe --datamodel C:\\Users\\Jan\\Documents\\throwaway\\prisma_migrate_debug\\prisma\\schema.prisma
{"id":1,"jsonrpc":"2.0","method":"markMigrationApplied","params":{"migrationsDirectoryPath":"C:\\Users\\Jan\\Documents\\throwaway\\prisma_migrate_debug\\prisma\\migrations","migrationName":"0_init"}}
{"jsonrpc":"2.0","error":{"code":4466,"message":"An error happened. Check the data field for details.","data":{"is_panic":false,"message":"The migration 0_init could not be found. Please make sure that the migration exists, and that you included the whole name of the directory. (example: \"20201207184859_initial_migration\")","meta":{"migration_name":"0_init"},"error_code":"P3017"}},"id":1}
```

It would be convenient if one would not need to construct the datamodel path (that the CLI knows and uses) and maybe even the `--datamodel` would be mentioned.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
