### ISSUE TITLE
Issue when querying Many-To-Many tables with tables that self reference: `Recursive common table expression 'cte_0' does not contain a top-level UNION ALL operator.`

### ISSUE THREAD

**Issue by salcio** [prisma/prisma#17701]
### Bug description

When queuing explicit many to many table I get the exception 

```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 252, state: 1, class: 16, message: "Recursive common table expression 'cte_0' does not contain a top-level UNION ALL operator.", server: "e0a44d9012ef", procedure: "", line: 1 }), transient: false })
    at RequestHandler.handleRequestError (/Users/lukaszsalamon/Repos/spikes/prisma/node_modules/@prisma/client/runtime/index.js:31950:13)
    at RequestHandler.handleAndLogRequestError (/Users/lukaszsalamon/Repos/spikes/prisma/node_modules/@prisma/client/runtime/index.js:31913:12)
    at RequestHandler.request (/Users/lukaszsalamon/Repos/spikes/prisma/node_modules/@prisma/client/runtime/index.js:31908:12)
    at async PrismaClient._request (/Users/lukaszsalamon/Repos/spikes/prisma/node_modules/@prisma/client/runtime/index.js:32994:16) {
  clientVersion: '4.9.0',
  batchRequestIdx: undefined
}
```

The many-to-many table references and entity that has self references which are used in the  query. 

prisma query looks like : 

```
prisma.userGroups.findMany({
        where: {
            group: {
                application: {
                    owners: {
                        some: {
                            group: {
                                users: {
                                    some: {
                                        userId: '9771e3b4-2508-4531-9012-1932064acef2'
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
    })
```

Might be related to #16747 (https://github.com/prisma/prisma/issues/16747).

### How to reproduce

I have prepared example project that reproduce this and one more issue 
https://github.com/salcio/prismaIssue

### Expected behavior

Query should execute without errors. 

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = []
  binaryTargets   = ["native", "debian-openssl-3.0.x", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

model User {
  id                    String                 @id @default(dbgenerated("newid()")) @db.UniqueIdentifier
  name                  String                 @db.NVarChar(255)
  email                 String?
  username              String                 @unique @db.NVarChar(255)
  organisationId        String?                @db.UniqueIdentifier
  organisation          Organisation?          @relation(fields: [organisationId], references: [id])
  groups                UserGroups[]
}

model Organisation {
  id         String    @id @default(dbgenerated("newid()")) @db.UniqueIdentifier
  name       String    @unique @db.NVarChar(255)
  users      User[]
}

model Group {
  id                    String                 @id @default(dbgenerated("newid()")) @db.UniqueIdentifier
  name                  String                 @unique
  tcpPrefix             String?
  applicationId         String?                @db.UniqueIdentifier
  ownedApplications     ApplicationOwner[]
  application           Application?           @relation(fields: [applicationId], references: [id])
  managedGroups         GroupManager[]         @relation("managedGroups")
  managers              GroupManager[]         @relation("managers")
  users                 UserGroups[]
}

model Application {
  id               String               @id @default(dbgenerated("newid()")) @db.UniqueIdentifier
  name             String               @unique
  owners           ApplicationOwner[]
  groups           Group[]
}

model UserGroups {
  userId     String   @db.UniqueIdentifier
  groupId    String   @db.UniqueIdentifier
  assignedAt DateTime @default(now())
  assignedBy String
  group      Group    @relation(fields: [groupId], references: [id])
  user       User     @relation(fields: [userId], references: [id])

  @@id([groupId, userId])
}

model ApplicationOwner {
  applicationId String      @db.UniqueIdentifier
  groupId       String      @db.UniqueIdentifier
  assignedAt    DateTime    @default(now())
  assignedBy    String
  application   Application @relation(fields: [applicationId], references: [id], onUpdate: NoAction)
  group         Group       @relation(fields: [groupId], references: [id])

  @@id([groupId, applicationId])
}

model GroupManager {
  managerId  String   @db.UniqueIdentifier
  groupId    String   @db.UniqueIdentifier
  assignedAt DateTime @default(now())
  assignedBy String
  group      Group    @relation("managedGroups", fields: [groupId], references: [id], onUpdate: NoAction)
  manager    Group    @relation("managers", fields: [managerId], references: [id], onUpdate: NoAction)

  @@id([groupId, managerId])
}

```

```ts
import {PrismaClient} from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
    if (!(await prisma.user.findFirst({where: {name: 'Alice'}}))) {
        const user = await prisma.user.create({
            data: {
                name: 'Alice',
                email: 'alice@prisma.io',
                username: 'alice'
            },
        })
        console.log(user);
    }
    console.log('-----======== Get all user groups where user name is Alice =======-----');
    console.log(await prisma.userGroups.findMany({where: {user: {name: 'Alice'}}}));
    console.log('-----======== Count all user groups where user name is Alice - directly from usersGroups table =======-----');
    try {
        console.log(await prisma.userGroups.count({ where: {user: {name: 'Alice'}}}));
        console.log(await prisma.userGroups.aggregate({_count: {_all: true}, where: {user: {name: 'Alice'}}}));
    } catch (e) {
        console.log(e);
    }
    console.log('-----======== Count all user groups where user name is Alice - from user record =======-----');
    console.log(await prisma.user.findMany({where: {name: 'Alice'}, select: {_count: {select: {groups: true}}}}));
    console.log('-----======== Get all users groups that belong to an aplication in which user is the owner =======-----');
    try {
        console.log(await prisma.userGroups.findMany({
        where: {
            group: {
                application: {
                    owners: {
                        some: {
                            group: {
                                users: {
                                    some: {
                                        userId: '9771e3b4-2508-4531-9012-1932064acef2'
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
    }));
    } catch (e) {
        console.log(e);
    }
    console.log('-----======== Get all groups that belong to an application in which user is the owner =======-----');
    console.log(await prisma.group.findMany({
        where: {
                application: {
                    owners: {
                        some: {
                            group: {
                                users: {
                                    some: {
                                        userId: '9771e3b4-2508-4531-9012-1932064acef2'
                                    }
                                }
                            }
                        }
                    }
                }
        },
    }));
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })

```

### Environment & setup

- OS: macOS
- Database: SQL Server
- Node.js version: v16.14.2

### Prisma Version

```
prisma                  : 4.9.0
@prisma/client          : 4.9.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.9.0-42.ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Default Engines Hash    : ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Studio                  : 0.479.0

```

**Comment by FraGoTe** [comment]
any workaround for this?

**Comment by janpio** [comment]
I can confirm this with Prisma 4.9.0 @salcio, thanks for the excellent reproduction.

**Comment by janpio** [comment]
Upgrading to `latest` Prisma though, 5.14.0, the script successfully runs and does not crash any more:

```
> node .\script.js
prisma:query SELECT [dbo].[User].[id], [dbo].[User].[name], [dbo].[User].[email], [dbo].[User].[username], [dbo].[User].[organisationId] FROM [dbo].[User] WHERE [dbo].[User].[name] = @P1 ORDER BY 1 OFFSET @P2 ROWS FETCH NEXT @P3 ROWS ONLY
-----======== Get all user groups where user name is Alice =======-----
prisma:query SELECT [dbo].[UserGroups].[groupId], [dbo].[UserGroups].[userId], [dbo].[UserGroups].[assignedAt], [dbo].[UserGroups].[assignedBy] FROM [dbo].[UserGroups] LEFT JOIN [dbo].[User] AS [j1] ON (([j1].[id] = [dbo].[UserGroups].[userId])) WHERE ([j1].[name] = @P1 AND ([j1].[id] IS NOT NULL))
[]
-----======== Count all user groups where user name is Alice - directly from usersGroups table =======-----
prisma:query SELECT COUNT(*) FROM (SELECT [dbo].[UserGroups].[groupId], [dbo].[UserGroups].[userId] FROM [dbo].[UserGroups] LEFT JOIN [dbo].[User] AS [j1] ON (([j1].[id] = [dbo].[UserGroups].[userId])) WHERE ([j1].[name] = @P1 AND ([j1].[id] IS NOT NULL))) AS [sub]
0
prisma:query SELECT COUNT(*) FROM (SELECT [dbo].[UserGroups].[groupId], [dbo].[UserGroups].[userId] FROM [dbo].[UserGroups] LEFT JOIN [dbo].[User] AS [j1] ON (([j1].[id] = [dbo].[UserGroups].[userId])) WHERE ([j1].[name] = @P1 AND ([j1].[id] IS NOT NULL))) AS [sub]
{ _count: { _all: 0 } }
-----======== Count all user groups where user name is Alice - from user record =======-----
prisma:query SELECT [dbo].[User].[id], [aggr_selection_0_UserGroups].[_aggr_count_groups] FROM [dbo].[User] LEFT JOIN (SELECT [dbo].[UserGroups].[userId], COUNT(*) AS [_aggr_count_groups] FROM [dbo].[UserGroups] WHERE 1=1 GROUP BY [dbo].[UserGroups].[userId]) AS [aggr_selection_0_UserGroups] ON ([dbo].[User].[id] = [aggr_selection_0_UserGroups].[userId]) WHERE [dbo].[User].[name] = @P1
[ { _count: { groups: 0 } } ]
-----======== Get all users groups that belong to an aplication in which user is the owner =======-----
prisma:query SELECT [dbo].[UserGroups].[groupId], [dbo].[UserGroups].[userId], [dbo].[UserGroups].[assignedAt], [dbo].[UserGroups].[assignedBy] FROM [dbo].[UserGroups] LEFT JOIN [dbo].[Group] AS [j1] ON (([j1].[id] = [dbo].[UserGroups].[groupId])) LEFT JOIN [dbo].[Application] AS [j2] ON (([j2].[id] = [j1].[applicationId])) WHERE (([j2].[id]) IN (SELECT [t3].[applicationId] FROM [dbo].[ApplicationOwner] AS [t3] LEFT JOIN [dbo].[Group] AS [j4] ON (([j4].[id] = [t3].[groupId])) WHERE (([j4].[id]) IN (SELECT [t5].[groupId] FROM [dbo].[UserGroups] AS [t5] WHERE ([t5].[userId] = @P1 AND [t5].[groupId] IS NOT NULL)) AND ([j4].[id] IS NOT NULL) AND [t3].[applicationId] IS NOT NULL)) AND ([j2].[id] IS NOT NULL) AND ([j1].[id] IS NOT NULL))
[]
-----======== Get all groups that belong to an application in which user is the owner =======-----
prisma:query SELECT [dbo].[Group].[id], [dbo].[Group].[name], [dbo].[Group].[tcpPrefix], [dbo].[Group].[applicationId] FROM [dbo].[Group] LEFT JOIN [dbo].[Application] AS [j1] ON (([j1].[id] = [dbo].[Group].[applicationId])) WHERE (([j1].[id]) IN (SELECT [t2].[applicationId] FROM [dbo].[ApplicationOwner] AS [t2] LEFT JOIN [dbo].[Group] AS [j3] ON (([j3].[id] = [t2].[groupId])) WHERE (([j3].[id]) IN (SELECT [t4].[groupId] FROM [dbo].[UserGroups] AS [t4] WHERE ([t4].[userId] = @P1 AND [t4].[groupId] IS NOT NULL)) AND ([j3].[id] IS NOT NULL) AND [t2].[applicationId] IS NOT NULL)) AND ([j1].[id] IS NOT NULL))
[]
```

Hence I am closing this issue as resolved now. 

Can you confirm that this has been fixed @salcio and @FraGoTe?
