### ISSUE TITLE
Error when getting 'count' of explicit many-to-many tables: "An expression of non-boolean type specified in a context where a condition is expected, near ..."

### ISSUE THREAD

**Issue by salcio** [prisma/prisma#17702]
### Bug description

When queuing explicit many-to-many tables for count I get: 

```
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 4145, state: 1, class: 15, message: "An expression of non-boolean type specified in a context where a condition is expected, near ','.", server: "e0a44d9012ef", procedure: "", line: 1 }), transient: false })
    at RequestHandler.handleRequestError (/Users/lukaszsalamon/Repos/spikes/prisma/node_modules/@prisma/client/runtime/index.js:31950:13)
    at RequestHandler.handleAndLogRequestError (/Users/lukaszsalamon/Repos/spikes/prisma/node_modules/@prisma/client/runtime/index.js:31913:12)
    at RequestHandler.request (/Users/lukaszsalamon/Repos/spikes/prisma/node_modules/@prisma/client/runtime/index.js:31908:12)
    at async PrismaClient._request (/Users/lukaszsalamon/Repos/spikes/prisma/node_modules/@prisma/client/runtime/index.js:32994:16) {
  clientVersion: '4.9.0',
  batchRequestIdx: undefined

```

prisma queries

```ts
       console.log(await prisma.userGroups.count({ where: {user: {name: 'Alice'}}}));
       console.log(await prisma.userGroups.aggregate({_count: {_all: true}, where: {user: {name: 'Alice'}}}));
```

### How to reproduce

I have prepared example project that reproduce this and one more issue (#17701)
https://github.com/salcio/prismaIssue

### Expected behavior

Should return count without any errors.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = []
  binaryTargets   = ["native", "debian-openssl-3.0.x", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

model User {
  id                    String                 @id @default(dbgenerated("newid()")) @db.UniqueIdentifier
  name                  String                 @db.NVarChar(255)
  email                 String?
  username              String                 @unique @db.NVarChar(255)
  organisationId        String?                @db.UniqueIdentifier
  organisation          Organisation?          @relation(fields: [organisationId], references: [id])
  groups                UserGroups[]
}

model Organisation {
  id         String    @id @default(dbgenerated("newid()")) @db.UniqueIdentifier
  name       String    @unique @db.NVarChar(255)
  users      User[]
}

model Group {
  id                    String                 @id @default(dbgenerated("newid()")) @db.UniqueIdentifier
  name                  String                 @unique
  tcpPrefix             String?
  applicationId         String?                @db.UniqueIdentifier
  ownedApplications     ApplicationOwner[]
  application           Application?           @relation(fields: [applicationId], references: [id])
  managedGroups         GroupManager[]         @relation("managedGroups")
  managers              GroupManager[]         @relation("managers")
  users                 UserGroups[]
}

model Application {
  id               String               @id @default(dbgenerated("newid()")) @db.UniqueIdentifier
  name             String               @unique
  owners           ApplicationOwner[]
  groups           Group[]
}

model UserGroups {
  userId     String   @db.UniqueIdentifier
  groupId    String   @db.UniqueIdentifier
  assignedAt DateTime @default(now())
  assignedBy String
  group      Group    @relation(fields: [groupId], references: [id])
  user       User     @relation(fields: [userId], references: [id])

  @@id([groupId, userId])
}

model ApplicationOwner {
  applicationId String      @db.UniqueIdentifier
  groupId       String      @db.UniqueIdentifier
  assignedAt    DateTime    @default(now())
  assignedBy    String
  application   Application @relation(fields: [applicationId], references: [id], onUpdate: NoAction)
  group         Group       @relation(fields: [groupId], references: [id])

  @@id([groupId, applicationId])
}

model GroupManager {
  managerId  String   @db.UniqueIdentifier
  groupId    String   @db.UniqueIdentifier
  assignedAt DateTime @default(now())
  assignedBy String
  group      Group    @relation("managedGroups", fields: [groupId], references: [id], onUpdate: NoAction)
  manager    Group    @relation("managers", fields: [managerId], references: [id], onUpdate: NoAction)

  @@id([groupId, managerId])
}

```

```ts
import {PrismaClient} from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
    if (!(await prisma.user.findFirst({where: {name: 'Alice'}}))) {
        const user = await prisma.user.create({
            data: {
                name: 'Alice',
                email: 'alice@prisma.io',
                username: 'alice'
            },
        })
        console.log(user);
    }
    console.log('-----======== Get all user groups where user name is Alice =======-----');
    console.log(await prisma.userGroups.findMany({where: {user: {name: 'Alice'}}}));
    console.log('-----======== Count all user groups where user name is Alice - directly from usersGroups table =======-----');
    try {
        console.log(await prisma.userGroups.count({ where: {user: {name: 'Alice'}}}));
        console.log(await prisma.userGroups.aggregate({_count: {_all: true}, where: {user: {name: 'Alice'}}}));
    } catch (e) {
        console.log(e);
    }
    console.log('-----======== Count all user groups where user name is Alice - from user record =======-----');
    console.log(await prisma.user.findMany({where: {name: 'Alice'}, select: {_count: {select: {groups: true}}}}));
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })

```

### Environment & setup

- OS: macOS
- Database: SQL Server
- Node.js version: v16.14.2

### Prisma Version

```
prisma                  : 4.9.0
@prisma/client          : 4.9.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.9.0-42.ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Default Engines Hash    : ceb5c99003b99c9ee2c1d2e618e359c14aef2ea5
Studio                  : 0.479.0

```

**Comment by mcbethio** [comment]
Thanks for reproduce repository - That was a great help and I can confirm I've just reproduced the bug.

**Comment by ryoku4** [comment]
Is this the same issue as #14037?

**Comment by ludralph** [comment]
Closing this in favour of [14037](https://github.com/prisma/prisma/issues/14037)
