### ISSUE TITLE
Prisma CLI fails silenty when Migration Engine is not usable (`Error: Migration engine error:`)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#17892]
Similar to https://github.com/prisma/prisma/issues/13165, but different:

When running Prisma CLI on Stackblitz it is expected to crash. When using `prisma -v` it outputs the error message, but not when e.g. using `db push` or `migrate dev` (with `DEBUG=*` activated):

```
~/janpio/stackblitz-codeflow-prisma main
❯ npx prisma -v
  prisma:engines  binaries to download query-engine, migration-engine +0ms
...
Error: Command failed with exit code 2: /home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version
/home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: line 2: a command can only contain words and redirects
    at makeError (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:3640:18)
    at handlePromise (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:4408:33)
    at async getEngineVersion (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:93558:20) {
  shortMessage: 'Command failed with exit code 2: /home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version',
  command: '/home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version',
  escapedCommand: '"/home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x" --version',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: line 2: a command can only contain words and redirects',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +2ms
prisma                : 4.10.1
@prisma/client        : 4.10.1
Current platform      : debian-openssl-1.1.x
Query Engine (Binary) : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine      : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm           : @prisma/prisma-fmt-wasm 4.10.1-1.80b351cc7c06d352abe81be19b8a89e9c6b7c110
Default Engines Hash  : aead147aa326ccb985dcfed5b065b4fdabd44b19
Studio                : 0.481.0
  prisma:getConfig  Using getConfig Wasm +6ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +1ms
```

But with the other commands:

```
~/janpio/stackblitz-codeflow-prisma main
❯ npx prisma db push
  prisma:engines  binaries to download query-engine, migration-engine +0ms
...

Error: Error: Migration engine error:

    at canConnectToDatabase (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:95410:15)
    at async ensureDatabaseExists (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:96150:22)
    at async _DbPush.parse (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:97554:28)
    at async main (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:101724:18)

```

Adding a `console.log(_e)` in the first linked stacktraced file (before it throws the `Migration engine error:`) then outputs the actual error as well:

```
Error: Command failed with exit code 2: /home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x cli --datasource <REDACTED> can-connect-to-database
/home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: line 2: a command can only contain words and redirects
    at makeError (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:3640:18)
    at handlePromise (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:4408:33)
    at async execaCommand (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:95458:12)
    at async canConnectToDatabase (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:95392:5)
    at async ensureDatabaseExists (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:96150:22)
    at async _DbPush.parse (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:97554:28)
    at async main (file:///home/janpio/stackblitz-codeflow-prisma/node_modules/prisma/build/index.js:101724:18) {
  shortMessage: 'Command failed with exit code 2: /home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x cli --datasource postgresql://jade_nutritious_sissy:lYiWAtmhL9@db-provision-postgres23452b4.c8yxynpcltwd.us-east-1.rds.amazonaws.com:5432/aquamarine_mosquito can-connect-to-database',
  command: '/home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x cli --datasource postgresql://jade_nutritious_sissy:lYiWAtmhL9@db-provision-postgres23452b4.c8yxynpcltwd.us-east-1.rds.amazonaws.com:5432/aquamarine_mosquito can-connect-to-database',
  escapedCommand: '"/home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x" cli --datasource "postgresql://jade_nutritious_sissy:lYiWAtmhL9@db-provision-postgres23452b4.c8yxynpcltwd.us-east-1.rds.amazonaws.com:5432/aquamarine_mosquito" can-connect-to-database',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: line 2: a command can only contain words and redirects',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

The solution is to somehow either log or include the actual exception in the error that is thrown.

**Comment by jkomyno** [comment]
With `prisma@4.11.0-integration-fix-17892.1`, I can't reproduce.
I get "socket hang up" error when loading https://binaries.prisma.sh/all_commits/f096a21f3e47685586a81ad7198fbb9cb16d213f/debian-openssl-1.1.x/migration-engine.gz.sha25.

![Uploading Screenshot 2023-02-27 at 12.28.12.png…]()

**Comment by janpio** [comment]
I forgot to include in the issue that you have to overcome the download problem by installing this Chrome extension: https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino

**Comment by janpio** [comment]
Output I get with `prisma@4.11.0-integration-fix-17892.1`:

```
~/janpio/stackblitz-codeflow-prisma main 10s
❯ npx prisma db push
prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "..."
prisma:warn Prisma failed to detect the libssl/openssl version to use, and may not work as expected. Defaulting to "openssl-1.1.x".
Please manually install OpenSSL and try installing Prisma again.
prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.

Error: Migration engine error (canConnectToDatabase): Command failed with exit code 2: /home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x cli --datasource <REDACTED> can-connect-to-database
```

The actual output of the command is:
```
❯ /home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x cli --datasource postgresql://... can-connect-to-database
/home/janpio/stackblitz-codeflow-prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: line 2: a command can only contain words and redirects
```

**Comment by thecoolestcoderrushil** [comment]
A migration engine that fails with an empty error message is a painful silent failure, since there is no actual exception to diagnose the problem. Logging the underlying error would save a lot of debugging time. Rehearsing the migration on a production-shaped twin first would surface the engine problem before deploy day. antifailure.dev (https://antifailure.dev) spins up disposable database twins for migration rehearsal, and it is open source and free to try. Happy to set up a demo if that would help.
