### ISSUE TITLE
TypeScript tests often fail with OOM

### ISSUE THREAD

**Issue by millsp** [prisma/prisma#17914]
### Bug description

Our functional test suite often fails on type-level tests with the following error. On way to fix this could be to feed the test folders to be type-checked by batches instead of feeding an ever increasing amount of types and clients to TypeScript.

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
--
  | [2023-02-13T18:28:56Z]  1: 0xa3ac30 node::Abort() [node]
  | [2023-02-13T18:28:56Z]  2: 0x970199 node::FatalError(char const*, char const*) [node]
  | [2023-02-13T18:28:56Z]  3: 0xbba76e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
  | [2023-02-13T18:28:56Z]  4: 0xbbaae7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
  | [2023-02-13T18:28:56Z]  5: 0xd76d05  [node]
  | [2023-02-13T18:28:56Z]  6: 0xd7788f  [node]
  | [2023-02-13T18:28:56Z]  7: 0xd856cb v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
  | [2023-02-13T18:28:56Z]  8: 0xd8928c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
  | [2023-02-13T18:28:56Z]  9: 0xd5796b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
  | [2023-02-13T18:28:56Z] 10: 0x109ffbf v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
  | [2023-02-13T18:28:56Z] 11: 0x14491d9  [node]
  | [2023-02-13T18:29:02Z] (node:1108) UnhandledPromiseRejectionWarning: Error: Command was killed with SIGABRT (Aborted): node_modules/.bin/jest --verbose --config tests/functional/jest.config.js -- typescript
  | [2023-02-13T18:29:02Z]     at makeError (/app/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
  | [2023-02-13T18:29:02Z]     at Function.module.exports.sync (/app/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:194:17)
  | [2023-02-13T18:29:02Z]     at JestCli.run (/app/packages/client/helpers/functional-test/JestCli.ts:24:11)
  | [2023-02-13T18:29:02Z]     at main (/app/packages/client/helpers/functional-test/run-tests.ts:137:48)
  | [2023-02-13T18:29:02Z]     at Object.<anonymous> (/app/packages/client/helpers/functional-test/run-tests.ts:170:6)
  | [2023-02-13T18:29:02Z]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
  | [2023-02-13T18:29:02Z]     at Module._compile (/app/node_modules/.pnpm/esbuild-register@3.3.3_esbuild@0.15.13/node_modules/esbuild-register/dist/node.js:2258:26)
  | [2023-02-13T18:29:02Z]     at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
  | [2023-02-13T18:29:02Z]     at Object.newLoader [as .ts] (/app/node_modules/.pnpm/esbuild-register@3.3.3_esbuild@0.15.13/node_modules/esbuild-register/dist/node.js:2262:9)
  | [2023-02-13T18:29:02Z]     at Module.load (internal/modules/cjs/loader.js:950:32)


```

### How to reproduce

I happens often enough on BuildKite
https://buildkite.com/prisma/test-prisma-typescript/builds/19914#01864c02-be92-4af9-93ac-ab500fa2d6c2/253-7305

### Expected behavior

Tests should work and most importantly the test suite should not fail to report the failure, as it currently succeeds regardless.

### Prisma information

n/a

### Environment & setup

n/a

### Prisma Version

```
latest
```

**Comment by Jolg42** [comment]
With `NODE_OPTIONS: '--max-old-space-size=8096'` I did not encounter any OOM.
