### ISSUE TITLE
import of `reflect-metadata` breaks `$queryRawUnsafe`

### ISSUE THREAD

**Issue by pjpsoares** [prisma/prisma#17933]
### Bug description

I have a couple of `$queryRawUnsafe` on my code, but they all started breaking as soon as I started using "reflect-metadata".
`"TypeError: Cannot read properties of undefined (reading 'map')","    at deserializeRawResults (/<project>/node_modules/@prisma/client/runtime/index.js:30932:15)"]}`

### How to reproduce

Have a `$queryRawUnsafe`, and import `reflect-metadata` at the beginning of your project.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: [macOS, Windows, Linux]
- Database: [MySQL]
- Node.js version: v16.13.2

### Prisma Version

```
4.3.1
```

**Comment by brentpi** [comment]
I've confirmed this issue on my project as well.  After attempting to upgrade from 4.9.0 to 5.1.1 these issues present.

Environment:
- macOS
- Database: MySQL
- NodeJS: v18
- NestJS 9.x and 10.x (using ScheduleModule, which imports reflect-metadata via DiscoveryModule)

I added some additional logging to ScheduleExplorer.js > lookupSchedulers to grab the instance type that reflect-metadata is attempting to parse:

`console.log(`IN: ${instance}, KEY: ${methodRef}`)`

I receive the following:

`IN: [object Object], KEY: getVersioning() {
        return this.versioningOptions;
    }
Target: getVersioning() {
        return this.versioningOptions;
    }
IN: [object PrismaClient], KEY: function(r){let n,i=(o=e)=>{try{return o===void 0||o?.kind==="itx"?n??(n=ya(r(o))):ya(r(o))}catch(s){return Promise.reject(s)}};return{then(o,s){return i().then(o,s)},catch(o){return i().catch(o)},finally(o){return i().finally(o)},requestTransaction(o){let s=i(o);return s.requestTransaction?s.requestTransaction(o):s},[Symbol.toStringTag]:"PrismaPromise"}}
Target: function(r){let n,i=(o=e)=>{try{return o===void 0||o?.kind==="itx"?n??(n=ya(r(o))):ya(r(o))}catch(s){return Promise.reject(s)}};return{then(o,s){return i().then(o,s)},catch(o){return i().catch(o)},finally(o){return i().finally(o)},requestTransaction(o){let s=i(o);return s.requestTransaction?s.requestTransaction(o):s},[Symbol.toStringTag]:"PrismaPromise"}}
IN: [object PrismaClient], KEY: function ks(e){if(typeof e=="function")return e(this);let t=Lr(this),r=Object.create(t,{_extensions:{value:this._extensions.append(e)},_appliedParent:{value:this,configurable:!0},$use:{value:void 0},$on:{value:void 0}});return Bt(r)}
Target: function ks(e){if(typeof e=="function")return e(this);let t=Lr(this),r=Object.create(t,{_extensions:{value:this._extensions.append(e)},_appliedParent:{value:this,configurable:!0},$use:{value:void 0},$on:{value:void 0}});return Bt(r)}
IN: [object PrismaClient], KEY: getEngine(){if(this._dataProxy,this._clientEngineType==="library")return new Dt(this._engineConfig);throw this._clientEngineType,"binary",new te("Invalid client engine type, please use `library` or `binary`",{clientVersion:this._clientVersion})}
Target: getEngine(){if(this._dataProxy,this._clientEngineType==="library")return new Dt(this._engineConfig);throw this._clientEngineType,"binary",new te("Invalid client engine type, please use `library` or `binary`",{clientVersion:this._clientVersion})}
IN: [object PrismaClient], KEY: undefined
Target: undefined

/Users/brentp/Desktop/repos/server/src/server-node/node_modules/reflect-metadata/Reflect.js:355
                throw new TypeError();
                      ^
TypeError: 
    at Reflect.getMetadata (/Users/brentp/Desktop/repos/server/src/server-node/node_modules/reflect-metadata/Reflect.js:355:23)
    at Reflector.get (/Users/brentp/Desktop/repos/server/src/server-node/node_modules/@nestjs/core/services/reflector.service.js:24:24)
    at SchedulerMetadataAccessor.getSchedulerType (/Users/brentp/Desktop/repos/server/src/server-node/node_modules/@nestjs/schedule/dist/schedule-metadata.accessor.js:22:31)
    at ScheduleExplorer.lookupSchedulers (/Users/brentp/Desktop/repos/server/src/server-node/node_modules/@nestjs/schedule/dist/schedule.explorer.js:56:48)
    at /Users/brentp/Desktop/repos/server/src/server-node/node_modules/@nestjs/schedule/dist/schedule.explorer.js:49:24
    at MetadataScanner.scanFromPrototype (/Users/brentp/Desktop/repos/server/src/server-node/node_modules/@nestjs/core/metadata-scanner.js:34:31)
    at /Users/brentp/Desktop/repos/server/src/server-node/node_modules/@nestjs/schedule/dist/schedule.explorer.js:48:34
    at Array.forEach (<anonymous>)
    at ScheduleExplorer.explore (/Users/brentp/Desktop/repos/server/src/server-node/node_modules/@nestjs/schedule/dist/schedule.explorer.js:43:26)
    at ScheduleExplorer.onModuleInit (/Users/brentp/Desktop/repos/server/src/server-node/node_modules/@nestjs/schedule/dist/schedule.explorer.js:36:14)`

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
