### ISSUE TITLE
Prisma Error 

### ISSUE THREAD

**Issue by Fatmasiam** [prisma/prisma#17939]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v17.2.0            | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 3.12.0             |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Logs
```
ocket timeout (the database failed to respond to a query within the configured timeout — see https://pris.ly/d/mysql-connector for more details.).
    at prismaGraphQLToJSError (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:39674:12)
    at Object.request (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:41508:17)
    at Object.request (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:45548:24)
    at PrismaService._request (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:46405:18)
    at IntegrationLogsService.handelClosedOrder (/home/ubuntu/cronjobs/src/modules/integration-logs/integration-logs.service.ts:592:21)
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler Error: Operations timed out after `10s`. Context: Socket timeout (the database failed to respond to a query within the configured timeout — see https://pris.ly/d/mysql-connector for more details.).
    at prismaGraphQLToJSError (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:39674:12)
    at Object.request (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:41508:17)
    at Object.request (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:45548:24)
    at PrismaService._request (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:46405:18)
    at IntegrationLogsService.handelClosedOrder (/home/ubuntu/cronjobs/src/modules/integration-logs/integration-logs.service.ts:592:21)
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler Error: Server has closed the connection.
    at prismaGraphQLToJSError (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:39674:12)
    at Object.request (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:41508:17)
    at Object.request (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:45548:24)
    at PrismaService._request (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:46405:18)
    at IntegrationLogsService.handelClosedOrder (/home/ubuntu/cronjobs/src/modules/integration-logs/integration-logs.service.ts:746:7)
prisma:client:request_handler Error: An operation failed because it depends on one or more records that were required but not found. Record to update not found.
    at prismaGraphQLToJSError (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:39674:12)
    at Object.request (/home/ubuntu/cronjobs/node_modules/@prisma/client/runtime/index.js:41508:17)
    at Object.reques

**Comment by mvarchdev** [comment]
I have same issue. When using sqlite and batch `.update` calls, it will show exactly this message: `The database failed to respond to a query within the configured timeout — see https://pris.ly/d/sqlite-connector for more details.`
