### ISSUE TITLE
Better error messages from database (PostgreSQL)

### ISSUE THREAD

**Issue by renatocron** [prisma/prisma#18026]
## Problem

When attempting to insert data into a table where a trigger generates an error, only a portion of the exception is displayed

Actually, it isn't really the same message, but it MAY share some internal code that the Prisma client uses to generate its own errors.

## Additional context

This is the error I got from the node:
```
PrismaClientKnownRequestError: 
Invalid `this.prisma.tarefa.create()` invocation in
/home/renato/projetos/appcivico/smae/backend/src/pp/tarefa/tarefa.service.ts:30:53

  27 
  28 
  29 const numero = dto.numero;
→ 30 const tarefa = await this.prisma.tarefa.create(
The column `new` does not exist in the current database.
    at Kr.handleRequestError (/home/renato/projetos/appcivico/smae/backend/node_modules/@prisma/client/src/runtime/RequestHandler.ts:211:13)
    at Kr.handleAndLogRequestError (/home/renato/projetos/appcivico/smae/backend/node_modules/@prisma/client/src/runtime/RequestHandler.ts:173:12)
    at Kr.request (/home/renato/projetos/appcivico/smae/backend/node_modules/@prisma/client/src/runtime/RequestHandler.ts:163:12)
    at PrismaService._request (/home/renato/projetos/appcivico/smae/backend/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1036:14)
    at /home/renato/projetos/appcivico/smae/backend/src/pp/tarefa/tarefa.service.ts:30:28
    at Proxy._transactionWithCallback (/home/renato/projetos/appcivico/smae/backend/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:928:18)
    at TarefaService.create (/home/renato/projetos/appcivico/smae/backend/src/pp/tarefa/tarefa.service.ts:26:25)
    at TarefaController.create (/home/renato/projetos/appcivico/smae/backend/src/pp/tarefa/tarefa.controller.ts:32:16) {
  code: 'P2022',
  clientVersion: '4.10.1',
  meta: { column: 'new' },
  batchRequestIdx: undefined
}
```

And here is the error I got when running the statement via PSQL:

```
ERROR:  record "new" has no field "tarefa_pai"
CONTEXT:  SQL statement "SELECT NEW.tarefa_pai IS NULL"
PL/pgSQL function f_trg_pp_tarefa_esticar_datas_do_pai() line 12 at IF
```

Testes on 4.9.0 and 4.10.1

If any help is need to how reproduce this error, I'm available to help, but it's just a simple trigger with a invalid column name (no type checking the the functions :sweat_smile: )

**Comment by janpio** [comment]
Can you please help us reproduce this by giving the SQL for such a simple trigger? Anything that saves us some time is welcome. Thanks.

**Comment by renatocron** [comment]
sure:


based on the https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch/relational-databases-typescript-postgres I created this repo: 
https://github.com/renatocron/prisma-issue-18026

but the main files are:

```js
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Person {
    id                  Int                 @id @default(autoincrement())
    email               String              @unique

    parent_id Int?
}
```

migration:
```sql
-- CreateTable
CREATE TABLE "Person" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "parent_id" INTEGER,

    CONSTRAINT "Person_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Person_email_key" ON "Person"("email");

CREATE OR REPLACE FUNCTION f_trg_xpto() RETURNS trigger AS $emp_stamp$
DECLARE
BEGIN

    -- should be "parent_id", for example
    IF NEW.parent IS NULL THEN
        -- perform ...
    END IF;

    RETURN NEW;
END;
$emp_stamp$ LANGUAGE plpgsql;

CREATE TRIGGER trg_foo_insert AFTER INSERT ON "Person"
    FOR EACH ROW
    EXECUTE FUNCTION f_trg_xpto();
```

main.ts:

```ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {

    await prisma.person.create({
        data: {
            email: 'hey'
        }
    })
}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })
    
 ```

output:

```
PrismaClientKnownRequestError: 
Invalid `prisma.person.create()` invocation in
/tmp/hello-prisma/index.ts:7:25

  4 
  5 async function main() {
  6 
→ 7     await prisma.person.create(
The column `new` does not exist in the current database.
    at Kr.handleRequestError (/tmp/hello-prisma/node_modules/@prisma/client/src/runtime/RequestHandler.ts:211:13)
    at Kr.handleAndLogRequestError (/tmp/hello-prisma/node_modules/@prisma/client/src/runtime/RequestHandler.ts:173:12)
    at Kr.request (/tmp/hello-prisma/node_modules/@prisma/client/src/runtime/RequestHandler.ts:163:12)
    at async t._request (/tmp/hello-prisma/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1036:14) {
  code: 'P2022',
  clientVersion: '4.10.1',
  meta: { column: 'new' },
  batchRequestIdx: undefined
}
```

**Comment by andrewpurcell** [comment]
+1 and related, we have a custom exception message that comes from our trigger that we'd like access to. Here's an example of the response we get when triggering it:

```
Invalid `prisma.appointment.delete()` invocation: Error occurred during query execution: ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "P0001", message: "Cannot delete an appointment in the past", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })```

What I want is for the message `Cannot delete an appointment in the past` to be surfaced through the instance of `PrismaClientUnknownRequestError`.
