### ISSUE TITLE
Error creating a database connection.

### ISSUE THREAD

**Issue by lglie** [prisma/prisma#1807]
When the following error prompt appears, the database can no longer be accessed:

```
Error:
Error in connector: Error creating a database connection.

Invalid `prisma.categories.findMany()` invocation in
/usr/local/services/tsf-agent/exec/1257983906/application-evj45bzv/group-9ynx94zv/node_modules/nexus-prisma/src/builder.ts:315:20
at PrismaClientFetcher.request (/usr/local/services/tsf-agent/exec/1257983906/application-evj45bzv/group-9ynx94zv/node_modules/@prisma/client/index.js:90:17)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by pantharshit00** [comment]
@lglie Can you please provide a reproduction for this? The provided information is insufficient for us to triage this.

**Comment by awebi** [comment]
Having the same issue. Was working, all of a sudden, I now get this same error.

**Comment by pantharshit00** [comment]
@awebi Can you provide steps by which we can produce this?

**Comment by pantharshit00** [comment]
@awebi @lglie I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
