### ISSUE TITLE
Make it possible to use sourcemaps for the client runtime without shipping them in `@prisma/client` package.

### ISSUE THREAD

**Issue by SevInf** [prisma/prisma#18082]
In #17156 we started minifying our runtime. In the process, we've also started building source maps to be able to map stacktraces back to original sources. In #18081 we excluded source maps from default package because of the size increase. While source maps are still used for local development, we are left without an option to use them for published releases and bug reports. It would be helpful to regain that ability.

Basic idea: introduce separate package which would publish source map for prisma releases. Add a script which would allow us to turn minified stack trace into original:

```sh
echo "minified-stack-trace" |  npx @prisma/client-source-maps@version # will print non-minified stacktrace.
```

**Comment by drakedeatonuk** [comment]
Think I may be having an error related to this. I'm trying to upload source maps for my backend to the service, Sentry, so that I can read my stacktraces in my prod env.

I'm using a webpack plugin to upload my source maps to Sentry, and I'm getting an error related a prisma source map:

```
Failed to parse source map from '...node_modules/.prisma/{NAME}-client/runtime/library.js.map' file: Error: ENOENT: no such file or directory, open '.../node_modules/.prisma/{NAME]-client/runtime/library.js.map'
```

I can see in the nested .prisma directory that the `library.js.map` file is indeed missing:

![Screenshot 2023-03-11 at 17 42 26](https://user-images.githubusercontent.com/41165256/224503593-daa8126e-2090-4da2-827e-79583d117586.png)

I'm not sure how or when this source map was supposed to be generated... I've seen very little in the prisma docs, issues, & PRs around source maps... 

Is this related to this issue or should I create an separate one?

**Comment by SevInf** [comment]
@drakedeatonuk I don't think this is related. For now, it is expected that source map is not included in the generated folder and this issue won't change that. Does webpack plugin have an option for excluding a directory? If so, I'd advice to do just that for generated client.

**Comment by josh-** [comment]
I'm currently debugging a strange error in an app which Sentry reports as originating in [`RequestHandler.handleRequestError`](https://github.com/prisma/prisma/blob/4ec6c05c69c64735a215bf5041855018edc0667b/packages/client/src/runtime/RequestHandler.ts#LL189C3-L189C21).

It would be super helpful to be able to see an unminifed stack trace as part of this debugging - do you have any recommendations on a workaround to achieve this until the `@prisma/client-source-maps` script is available @SevInf?

Thanks in advance 🙂

**Comment by SevInf** [comment]
@josh- I would maybe suggest building prisma from source and linking resulting package to you repo. In that case, it will contain source maps.
Also not that `Request.handleRequestError` is where most client-side errors are constructed, so stacktrace you have might be a red herring. If you are encountering confusing error message, it might be worth opening a separate issue with all necessary details so we could take a look and improve it.

**Comment by josh-** [comment]
Great, thanks the prompt response and extra details @SevInf 🙌

**Comment by alvis** [comment]
Perhaps it's completely unexpected but missing the sourcemaps breaks coverage reporting from v8 with vitest in a monorepo setting. While smaller bundled size is always good, but Primsa is meant to be a server side library and so a few kilobyte smaller package size won't have any impact at all. Please add the source map back 🙏🏼 

Here is an example stack trace:
```
Error: An error occurred while trying to read the map file at edge-esm.js.map
Error: ENOENT: no such file or directory, open '/<path/to/client>/edge-esm.js.map'
    at readFileSync (node:fs:453:20)
    at V8ToIstanbul._readFileFromDir (/workspace/node_modules/.pnpm/v8-to-istanbul@9.2.0/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:94:12)
    at readFromFileMap (/workspace/node_modules/.pnpm/convert-source-map@2.0.0/node_modules/convert-source-map/index.js:54:14)
    at exports.fromMapFileComment (/workspace/node_modules/.pnpm/convert-source-map@2.0.0/node_modules/convert-source-map/index.js:196:12)
    at exports.fromMapFileSource (/workspace/node_modules/.pnpm/convert-source-map@2.0.0/node_modules/convert-source-map/index.js:219:22)
    at V8ToIstanbul.load (/workspace/node_modules/.pnpm/v8-to-istanbul@9.2.0/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:53:66)
    at file:///workspace/node_modules/.pnpm/@vitest+coverage-v8@1.1.0_vitest@1.1.0/node_modules/@vitest/coverage-v8/dist/provider.js:392:25
    at async Promise.all (index 4)
    at async V8CoverageProvider.convertCoverage (file:///workspace/node_modules/.pnpm/@vitest+coverage-v8@1.1.0_vitest@1.1.0/node_modules/@vitest/coverage-v8/dist/provider.js:388:7)
    at async V8CoverageProvider.reportCoverage (file:///workspace/node_modules/.pnpm/@vitest+coverage-v8@1.1.0_vitest@1.1.0/node_modules/@vitest/coverage-v8/dist/provider.js:273:25)
```
