### ISSUE TITLE
`error: Found argument '--enable-raw-queries' which wasn't expected, or isn't valid in this context`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1811]
I got into this strange state, where at the end I got the error message from the title which is strange. This is what I did:

1. Global `prisma2` install of version `preview023`.
2. Create folder `C:\Users\Jan\Documents\throwaway\albertoRepro`
3. `prisma2 init`
4. updated the connection string to a `discourse` schema
5. then opened VS Code on the project where I did:

```
Microsoft Windows [Version 10.0.18362.657]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Jan\Documents\throwaway\albertoRepro>prisma2 introspect
Introspecting based on datasource defined in prisma\schema.prisma …

✔ Wrote Prisma data model into prisma\schema.prisma in 1.68s

Run prisma2 generate to generate Prisma Client.


C:\Users\Jan\Documents\throwaway\albertoRepro>prisma2 generate
✔ Created ./package.json
yarn add v1.22.0
warning ..\..\package.json: No license field
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.22.4", while you're on "1.22.0".
success Saved 1 new dependency.
info Direct dependencies
└─ prisma2@2.0.0-preview023
info All dependencies
└─ prisma2@2.0.0-preview023
Done in 13.91s.
yarn add v1.22.0
warning ..\..\package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @prisma/client@2.0.0-preview023
info All dependencies
└─ @prisma/client@2.0.0-preview023
Done in 3.05s.

✔ Installed the @prisma/client and prisma2 packages in your project
✔ Generated Prisma Client to .\node_modules\@prisma\client in 1.28s

You can now start using Prisma Client in your code:

import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

Explore the full API: http://pris.ly/d/client


C:\Users\Jan\Documents\throwaway\albertoRepro>node test.js
C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\@prisma\client\index.js:39484
const dmmfString = '{"datamodel":{"enums":[],"models":[{"name":"api_keys","isEmbedded":false,"dbName":null,"fields":[{"name":"allowed_ips","kind":"scalar","dbNames":[],"isList":true,"isRequired":false,"isUnique":false,"isId":false,"type":"String","isGenerated":false,"isUpdatedAt":false},{"name":"created_at","kind":"scalar","dbNames":[],"isList":false,"isRequired":true,"isUnique":false,"isId":false,"type":"DateTime","isGenerated":false,"isUpdatedAt":false},{"name":"created_by_id","kind":"scalar","dbNames":[],"isList":false,"isRequired":false,"isUnique":false,"isId":false,"type":"Int","isGenerated":false,"isUpdatedAt":false},{"name":"hidden","kind":"scalar","dbNames":[],"isList":false,"isRequired":true,"isUnique":false,"isId":false,"type":"Boolean","default":false,"isGenerated":false,"isUpdatedAt":false},{"name":"id","kind":"scalar","dbNames":[],"isList":false,"isRequired":true,"isUnique":false,"isId":true,"type":"Int","d

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\albertoRepro\test.js:2:26)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)

C:\Users\Jan\Documents\throwaway\albertoRepro>npm install prisma2@alpha
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> sqlite3@4.1.1 install C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node" is installed via remote

> prisma2@2.0.0-alpha.883 install C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\prisma2
> node download-build/index.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN my-prisma-project@1.0.0 No description
npm WARN my-prisma-project@1.0.0 No repository field.

+ prisma2@2.0.0-alpha.883
added 113 packages from 101 contributors, updated 1 package and audited 164 packages in 27.418s
found 0 vulnerabilities


C:\Users\Jan\Documents\throwaway\albertoRepro>yarn prisma2 generate
yarn run v1.22.0
warning ..\..\package.json: No license field
$ C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\.bin\prisma2 generate
✔ Generated Prisma Client to .\node_modules\@prisma\client in 1.20s

You can now start using Prisma Client in your code:

import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

Explore the full API: http://pris.ly/d/client

Done in 2.70s.

C:\Users\Jan\Documents\throwaway\albertoRepro>npm install @prisma/client@alpha

> @prisma/client@2.0.0-alpha.883 postinstall C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\@prisma\client
> node scripts/postinstall.js

✔ Generated Prisma Client to .\node_modules\@prisma\client in 913ms

You can now start using Prisma Client in your code:

import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

Explore the full API: http://pris.ly/d/client

npm WARN my-prisma-project@1.0.0 No description
npm WARN my-prisma-project@1.0.0 No repository field.

+ @prisma/client@2.0.0-alpha.883
updated 1 package in 15.729s

C:\Users\Jan\Documents\throwaway\albertoRepro>yarn prisma2 generate
yarn run v1.22.0
warning ..\..\package.json: No license field
$ C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\.bin\prisma2 generate
✔ Generated Prisma Client to .\node_modules\@prisma\client in 886ms

You can now start using Prisma Client in your code:

import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

Explore the full API: http://pris.ly/d/client

Done in 2.31s.

C:\Users\Jan\Documents\throwaway\albertoRepro>node test.js
C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\@prisma\client\index.js:60
const dmmfString = '{"datamodel":{"enums":[],"models":[{"name":"api_keys","isEmbedded":false,"dbName":null,"fields":[{"name":"allowed_ips","kind":"scalar","dbNames":[],"isList":true,"isRequired":false,"isUnique":false,"isId":false,"type":"String","isGenerated":false,"isUpdatedAt":false},{"name":"created_at","kind":"scalar","dbNames":[],"isList":false,"isRequired":true,"isUnique":false,"isId":false,"type":"DateTime","isGenerated":false,"isUpdatedAt":false},{"name":"created_by_id","kind":"scalar","dbNames":[],"isList":false,"isRequired":false,"isUnique":false,"isId":false,"type":"Int","isGenerated":false,"isUpdatedAt":false},{"name":"hidden","kind":"scalar","dbNames":[],"isList":false,"isRequired":true,"isUnique":false,"isId":false,"type":"Boolean","default":false,"isGenerated":false,"isUpdatedAt":false},{"name":"id","kind":"scalar","dbNames":[],"isList":false,"isRequired":true,"isUnique":false,"isId":true,"type":"Int","defa

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\albertoRepro\test.js:2:26)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)

C:\Users\Jan\Documents\throwaway\albertoRepro>prisma2 introspect
Introspecting based on datasource defined in prisma\schema.prisma …

✔ Wrote Prisma data model into prisma\schema.prisma in 1.32s

Run prisma2 generate to generate Prisma Client.


C:\Users\Jan\Documents\throwaway\albertoRepro>npm install @prisma/client@latest prisma2@latest

> prisma2@2.0.0-preview023 install C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\prisma2
> node download-build/index.js


> @prisma/client@2.0.0-preview023 postinstall C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\@prisma\client
> node scripts/postinstall.js

✔ Generated Prisma Client to .\node_modules\@prisma\client in 1.33s

You can now start using Prisma Client in your code:

import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

Explore the full API: http://pris.ly/d/client

npm WARN my-prisma-project@1.0.0 No description
npm WARN my-prisma-project@1.0.0 No repository field.

+ prisma2@2.0.0-preview023
+ @prisma/client@2.0.0-preview023
removed 113 packages, updated 2 packages and audited 2 packages in 15.084s
found 0 vulnerabilities


C:\Users\Jan\Documents\throwaway\albertoRepro>prisma2 introspect
Introspecting based on datasource defined in prisma\schema.prisma …

✔ Wrote Prisma data model into prisma\schema.prisma in 1.12s

Run prisma2 generate to generate Prisma Client.


C:\Users\Jan\Documents\throwaway\albertoRepro>prisma2 introspect
Introspecting based on datasource defined in prisma\schema.prisma …

✔ Wrote Prisma data model into prisma\schema.prisma in 1.57s

Run prisma2 generate to generate Prisma Client.


C:\Users\Jan\Documents\throwaway\albertoRepro>npm install @prisma/client@alpha prisma2@alpha
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> sqlite3@4.1.1 install C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\sqlite3\lib\binding\node-v72-win32-x64\node_sqlite3.node" is installed via remote

> prisma2@2.0.0-alpha.883 install C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\prisma2
> node download-build/index.js


> @prisma/client@2.0.0-alpha.883 postinstall C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\@prisma\client
> node scripts/postinstall.js

✔ Generated Prisma Client to .\node_modules\@prisma\client in 994ms

You can now start using Prisma Client in your code:

import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

Explore the full API: http://pris.ly/d/client

npm WARN my-prisma-project@1.0.0 No description
npm WARN my-prisma-project@1.0.0 No repository field.

+ @prisma/client@2.0.0-alpha.883
+ prisma2@2.0.0-alpha.883
added 113 packages from 101 contributors, updated 2 packages and audited 164 packages in 22.517s
found 0 vulnerabilities


C:\Users\Jan\Documents\throwaway\albertoRepro>node test.js
C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\@prisma\client\index.js:60
const dmmfString = '{"datamodel":{"enums":[],"models":[{"name":"api_keys","isEmbedded":false,"dbName":null,"fields":[{"name":"allowed_ips","kind":"scalar","dbNames":[],"isList":true,"isRequired":false,"isUnique":false,"isId":false,"type":"String","isGenerated":false,"isUpdatedAt":false},{"name":"created_at","kind":"scalar","dbNames":[],"isList":false,"isRequired":true,"isUnique":false,"isId":false,"type":"DateTime","isGenerated":false,"isUpdatedAt":false},{"name":"created_by_id","kind":"scalar","dbNames":[],"isList":false,"isRequired":false,"isUnique":false,"isId":false,"type":"Int","isGenerated":false,"isUpdatedAt":false},{"name":"hidden","kind":"scalar","dbNames":[],"isList":false,"isRequired":true,"isUnique":false,"isId":false,"type":"Boolean","default":false,"isGenerated":false,"isUpdatedAt":false},{"name":"id","kind":"scalar","dbNames":[],"isList":false,"isRequired":true,"isUnique":false,"isId":true,"type":"Int","defa

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\albertoRepro\test.js:2:26)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)

C:\Users\Jan\Documents\throwaway\albertoRepro>prisma2 generate
✔ Generated Prisma Client to .\node_modules\@prisma\client in 852ms

You can now start using Prisma Client in your code:

import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

Explore the full API: http://pris.ly/d/client


C:\Users\Jan\Documents\throwaway\albertoRepro>node test.js
(node:24300) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.application_requests.findMany()` invocation in
C:\Users\Jan\Documents\throwaway\albertoRepro\test.js:6:29


error: Found argument '--enable-raw-queries' which wasn't expected, or isn't valid in this context
        Did you mean --enable_raw_queries?
USAGE:
    query-engine-windows.exe --enable_raw_queries
For more information try --help
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\throwaway\albertoRepro\node_modules\@prisma\client\runtime\index.js:1:47328)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:24300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I kind of assume this problem appeared because I ran `prisma2 generate` at the end instead of `yarn prisma2 generate` and so global install (preview023) and local install (alpha.883) got messed up?

**Comment by pantharshit00** [comment]
Can you please share the contents of the `test.js` file? Without that I wasn't able to reproduce this.

**Comment by janpio** [comment]
See https://github.com/prisma/prisma-client-js/issues/559#issue-578630713, but the content does not matter at all as long as it runs any query that triggers the QE.

**Comment by pantharshit00** [comment]
I am still unable to reproduce this. If you are still able to reproduce, I will add this to my list of things to test on windows.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
