### ISSUE TITLE
Enabling jsonProtocol preview feature breaks Prisma Data Platform

### ISSUE THREAD

**Issue by craigsc** [prisma/prisma#18166]
After enabling the jsonProtocol feature on the new 4.11 release, the data browser and query console both are broken since it fails to properly parse the prisma.schema. I also noticed the the data platform is reportedly still using client version 4.10.1, perhaps it just needs an upgrade to the new release?

Raw error message I am receiving when trying to access the data browser now:
```
Error starting Prisma Client: {
  "type": "PrismaClientKnownRequestError",
  "code": "P1012",
  "message": "Prisma schema validation - (get-dmmf wasm)\nError code: P1012\n\u001b[1;91merror\u001b[0m: \u001b[1mThe preview feature \"jsonProtocol\" is not known. Expected one of: fullTextSearch, fullTextIndex, tracing, metrics, orderByNulls, multiSchema, filteredRelationCount, fieldReference, postgresqlExtensions, clientExtensions, deno, extendedWhereUnique, views\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:6\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m 5 | \u001b[0m  provider = \"prisma-client-js\"\n\u001b[1;94m 6 | \u001b[0m  previewFeatures = \u001b[1;91m[\"jsonProtocol\"]\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1\n[Context: getDmmf]\n\nPrisma CLI Version : 4.10.1",
  "stack": "Error: Prisma schema validation - (get-dmmf wasm)\nError code: P1012\n\u001b[1;91merror\u001b[0m: \u001b[1mThe preview feature \"jsonProtocol\" is not known. Expected one of: fullTextSearch, fullTextIndex, tracing, metrics, orderByNulls, multiSchema, filteredRelationCount, fieldReference, postgresqlExtensions, clientExtensions, deno, extendedWhereUnique, views\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:6\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m 5 | \u001b[0m  provider = \"prisma-client-js\"\n\u001b[1;94m 6 | \u001b[0m  previewFeatures = \u001b[1;91m[\"jsonProtocol\"]\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1\n[Context: getDmmf]\n\nPrisma CLI Version : 4.10.1\n    at /var/task/node_modules/.pnpm/@prisma+internals@4.10.1/node_modules/@prisma/internals/dist/engine-commands/getDmmf.js:149:12\n    at n.e.run (/var/task/node_modules/.pnpm/ts-pattern@4.1.3/node_modules/ts-pattern/dist/index.cjs:1:4927)\n    at n.e.exhaustive (/var/task/node_modules/.pnpm/ts-pattern@4.1.3/node_modules/ts-pattern/dist/index.cjs:1:4613)\n    at getDMMF (/var/task/node_modules/.pnpm/@prisma+internals@4.10.1/node_modules/@prisma/internals/dist/engine-commands/getDmmf.js:153:6)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.getDmmf (/var/task/apps/fox/.next/server/chunks/9033.js:8250:25)\n    at async /var/task/apps/fox/.next/server/pages/api/databrowser.js:882:30\n    at async /var/task/apps/fox/.next/server/chunks/9033.js:10194:13\n    at async runMiddlewares (/var/task/apps/fox/.next/server/chunks/9033.js:10200:5)\n    at async /var/task/apps/fox/.next/server/chunks/9033.js:10202:23"
}
init@https://cloud.prisma.io/studio/assets/index.js:1:82961
```

**Comment by janpio** [comment]
Thanks, that is an aspect we did indeed not consider. The team is on it. Let's see if the update makes it work or if the old protocol is somehow hard coded there.

**Comment by janpio** [comment]
We can confirm this problem, both specifically in Data Browser and Query Console but also with Data Proxy in general.

**Comment by arnm** [comment]
I get a similar error but on  `npx prisma generate`

```
❯ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error:
✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in 227ms

Prisma schema validation - (get-dmmf wasm)
Error code: P1012
error: The preview feature "jsonProtocol" is not known. Expected one of: fullTextSearch, fullTextIndex, tracing, metrics, orderByNulls, multiSchema, filteredRelationCount, fieldReference, postgresqlExtensions, clientExtensions, deno, extendedWhereUnique, views
  -->  schema.prisma:6
   |
 5 |     provider        = "prisma-client-js"
 6 |     previewFeatures = ["jsonProtocol"]
   |

Validation Error Count: 1
[Context: getDmmf]

Prisma CLI Version : 4.10.1❯ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error:
✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in 227ms

Prisma schema validation - (get-dmmf wasm)
Error code: P1012
error: The preview feature "jsonProtocol" is not known. Expected one of: fullTextSearch, fullTextIndex, tracing, metrics, orderByNulls, multiSchema, filteredRelationCount, fieldReference, postgresqlExtensions, clientExtensions, deno, extendedWhereUnique, views
  -->  schema.prisma:6
   |
 5 |     provider        = "prisma-client-js"
 6 |     previewFeatures = ["jsonProtocol"]
   |

Validation Error Count: 1
[Context: getDmmf]

Prisma CLI Version : 4.10.1
```

Note sure why it says prisma CLI version is 4.10.1 even though I upgraded prisma with `npm i prisma@latest` and `package.json` shows 4.11.0

**Comment by janpio** [comment]
What you seen in the output is truth @arnm - so somehow your local `node_modules` folder still contains the previous version @arnm. I suggest you double check this, and make sure that `prisma -v` actually shows the correct version. (Often nuking the node_modules folder and re-running `npm install` fixes these problems.)

**Comment by janpio** [comment]
Could you figure out what was wrong in your project @arnm?

@craigsc We now understand the problem in Data Browser and Query Console better: Although you upload or use a Prisma schema with `previewFeatures = ["jsonProtocol"]` the Prisma Client of these two components uses an empty `previewFeatures` array. When it then talks to the Data Proxy under the hood, _that_ one parses the array correctly from the schema file though and expects to receive JSON - but then gets GraphQL and does not like that and crashes. For now you unfortunately can not use `jsonProtocol` with Data Browser or Query Console.

**Comment by janpio** [comment]
This should be fixed now @craigsc.

Thanks again for reporting it originally.
