### ISSUE TITLE
Error: Error in migration engine. Reason:  

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#18194]
Command: `prisma db pull`
Version: `4.11.0`
Binary Version: `8fde8fef4033376662cad983758335009d522acb`
Report: https://prisma-errors.netlify.app/report/14594 
OS: `x64 win32 10.0.22621`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: 

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

    at handlePanic (C:\xxx\node_modules\prisma\build\index.js:94475:15)
    at ChildProcess.<anonymous> (C:\xxx\node_modules\prisma\build\index.js:94495:15)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

Rust Stacktrace:
```

```

**Comment by jkomyno** [comment]
Closing as we have no way of reproducing Windows `db pull` panics with empty stacktraces.
