### ISSUE TITLE
Error: unreachable 

### ISSUE THREAD

**Issue by pimeys** [prisma/prisma#18195]
Command: `prisma migrate dev --name linked_in_integration_account`
Version: `4.10.1`
Binary Version: `aead147aa326ccb985dcfed5b065b4fdabd44b19`
Report: https://prisma-errors.netlify.app/report/14586 
OS: `arm64 darwin 21.6.0`

JS Stacktrace:
```
Error: unreachable
    at /Users/francisco/Documents/assembly/assembly/node_modules/prisma/build/index.js:93473:21
    at O.run (/Users/francisco/Documents/assembly/assembly/node_modules/prisma/build/index.js:89790:12)
    at O.exhaustive (/Users/francisco/Documents/assembly/assembly/node_modules/prisma/build/index.js:89770:17)
    at getDMMF (/Users/francisco/Documents/assembly/assembly/node_modules/prisma/build/index.js:93488:6)
    at async _MigrateDev.parse (/Users/francisco/Documents/assembly/assembly/node_modules/prisma/build/index.js:98399:5)
    at async main (/Users/francisco/Documents/assembly/assembly/node_modules/prisma/build/index.js:101724:18)
```

Rust Stacktrace:
```
RuntimeError: unreachable
    at rust_panic (wasm://wasm/00a0f2c2:wasm-function[2917]:0x19d798)
    at std::panicking::rust_panic_with_hook::hd000e9fb43b5781d (wasm://wasm/00a0f2c2:wasm-function[2056]:0x1934bb)
    at std::panicking::begin_panic_handler::{{closure}}::he16e52e9a7dddeb1 (wasm://wasm/00a0f2c2:wasm-function[2386]:0x19962b)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h227361e053771d9e (wasm://wasm/00a0f2c2:wasm-function[2533]:0x19b479)
    at rust_begin_unwind (wasm://wasm/00a0f2c2:wasm-function[2348]:0x198d13)
    at core::panicking::panic_fmt::h9d972fcdb087ce21 (wasm://wasm/00a0f2c2:wasm-function[2387]:0x19966b)
    at prisma_models::convert::convert::hf33eb387ec28608f (wasm://wasm/00a0f2c2:wasm-function[16]:0x51564)
    at dmmf::dmmf_json_from_schema::hd7734bce4b2a77ca (wasm://wasm/00a0f2c2:wasm-function[11]:0x3e4d1)
    at get_dmmf (wasm://wasm/00a0f2c2:wasm-function[165]:0xdb80d)
    at module2.exports.get_dmmf (/Users/francisco/Documents/assembly/assembly/node_modules/prisma/build/index.js:12094:14)
```

**Comment by jkomyno** [comment]
Closed as fixed in `prisma@4.11.0`.
