### ISSUE TITLE
Cannot use Prisma Client on CloudFlare Pages

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#18204]
### Bug description

- We created a hello-world style Cloud Flare Pages app
- We happen to be using Remix but that is not relevant AFAWCT
- When the Prisma Client is constructed an error is thrown as follows:

	```
	[dev:wrangler] [pages:err] ReferenceError: DATABASE_URL_PROXY is not defined.
	[dev:wrangler] Attempted to access binding using global in modules.
	[dev:wrangler] You must use the 2nd `env` parameter passed to exported handlers/Durable Object constructors, or `context.env` with Pages Functions.
	[dev:wrangler]     at EventTarget.get (/Users/jasonkuhrt/projects/prisma/pdp-cp-spike-control-plane-v2-jasonkuhrt/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/standards/event.ts:291:19)
	[dev:wrangler]     at node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/.prisma/client/edge.js (/private/Users/jasonkuhrt/projects/prisma/pdp-cp-spike-control-plane-v2-jasonkuhrt/functions/[[path]].js:23893:67)
	[dev:wrangler]     at /private/Users/jasonkuhrt/projects/prisma/pdp-cp-spike-control-plane-v2-jasonkuhrt/functions/[[path]].js:17:46
	[dev:wrangler]     at node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client/edge.js (/private/Users/jasonkuhrt/projects/prisma/pdp-cp-spike-control-plane-v2-jasonkuhrt/functions/[[path]].js:23908:10)
	[dev:wrangler]     at /private/Users/jasonkuhrt/projects/prisma/pdp-cp-spike-control-plane-v2-jasonkuhrt/functions/[[path]].js:17:46
	[dev:wrangler]     at /private/Users/jasonkuhrt/projects/prisma/pdp-cp-spike-control-plane-v2-jasonkuhrt/functions/[[path]].js:25413:27
	[dev:wrangler]     at SourceTextModule.evaluate (node:internal/vm/module:226:23)
	[dev:wrangler]     at VMScriptRunner.runAsModule (/Users/jasonkuhrt/projects/prisma/pdp-cp-spike-control-plane-v2-jasonkuhrt/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:40:18)
	[dev:wrangler]     at VMScriptRunner.run (/Users/jasonkuhrt/projects/prisma/pdp-cp-spike-control-plane-v2-jasonkuhrt/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:86:17)
	[dev:wrangler]     at EventTarget.#reload (/Users/jasonkuhrt/projects/prisma/pdp-cp-spike-control-plane-v2-jasonkuhrt/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/index.ts:790:13)
	```

- The above looks like a user error but once you look at the repro repo you will see that it is not.

### How to reproduce

Please check out this repro repo https://github.com/prisma/repro-prisma-client-cloud-flare-pages.

You should see an error like the following get produced:

<img width="1281" alt="CleanShot 2023-03-03 at 12 28 53@2x" src="https://user-images.githubusercontent.com/284476/222788140-40fc7d7d-ea3c-43d6-bd17-de75e6fc295a.png">

Notice the second error's stack including the generated edge prisma client.

Note that both errors go away when removing the Prisma Client constructor call.

### Expected behavior

When we `new PrismaClient(...)` in CF Pages we expect it to work without error.

### Prisma information

All of this is available in the repro repo. We're on the latest version of everything (Mar 2 2023).

### Environment & setup

All of this is available in the repro repo. We're on the latest version of everything (Mar 2 2023).

### Prisma Version

`4.11`

**Comment by janpio** [comment]
Can confirm something going wrong in the reproduction:
```
gitpod /workspace/repro-prisma-client-cloud-flare-pages (main) $ pnpm dev

> @ dev /workspace/repro-prisma-client-cloud-flare-pages
> npm-run-all build --print-label --parallel "dev:*"

[build] 
[build] > @ build /workspace/repro-prisma-client-cloud-flare-pages
[build] > remix build
[build] 
[build] Building Remix app in production mode...
[build] Built in 820ms
[dev:remix   ] 
[dev:remix   ] > @ dev:remix /workspace/repro-prisma-client-cloud-flare-pages
[dev:remix   ] > remix watch
[dev:remix   ] 
[dev:wrangler] 
[dev:wrangler] > @ dev:wrangler /workspace/repro-prisma-client-cloud-flare-pages
[dev:wrangler] > dotenv -c development -- wrangler --compatibility-date 2023-03-02 pages dev ./public
[dev:wrangler] 
[dev:wrangler] 🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
[dev:wrangler] Compiling worker to "/tmp/functionsWorker-0.3228208365374463.mjs"...
[dev:wrangler] ✨ Compiled Worker successfully
[dev:remix   ] Watching Remix app in development mode...
[dev:wrangler] ╭──────────────────────────────────────────────────────────────────────────────╮
[dev:wrangler] │ [b open a       [d open        [l turn off local   [c] clear       [x to     │
[dev:wrangler] │   browser,        Devtools,      mode,                console,       exit    │
[dev:wrangler] ╰──────────────────────────────────────────────────────────────────────────────╯
[dev:wrangler] Debugger listening on ws://127.0.0.1:36043/dc6a6931-f833-4f91-9bc9-9cc35fc3c600
[dev:wrangler] For help, see: https://nodejs.org/en/docs/inspector
╭──────────────────────────────────────────────────────────────────────────────╮
[dev:wrangler] │ [b open a       [d open        [l turn off local   [c] clear       [x to     │
[dev:wrangler] │   browser,        Devtools,      mode,                console,       exit    │
[dev:wrangler] ╰──────────────────────────────────────────────────────────────────────────────╯
[dev:wrangler] ✘ [ERROR] Expected identifier but found end of file
[dev:wrangler] 
[dev:wrangler]     ../../tmp/functionsWorker-0.3228208365374463.mjs:10750:2:
╭──────────────────────────────────────────────────────────────────────────────╮
[dev:wrangler] │ [b open a       [d open        [l turn off local   [c] clear       [x to     │
[dev:wrangler] │   browser,        Devtools,      mode,                console,       exit    │
[dev:wrangler] ╰──────────────────────────────────────────────────────────────────────────────╯
[dev:wrangler] ✘ [ERROR] Watch build failed: Build failed with 1 error:
[dev:wrangler] 
[dev:wrangler]   ../../tmp/functionsWorker-0.3228208365374463.mjs:10750:2: ERROR: Expected identifier but found end of file
[dev:wrangler] 
[dev:wrangler] 
[dev:wrangler] Debugger listening on ws://127.0.0.1:36043/75a7886f-a164-4388-b444-be07409790f7
[dev:wrangler] For help, see: https://nodejs.org/en/docs/inspector
[dev:wrangler] Debugger attached.
[dev:wrangler] [pages:wrn] Parsed 1 valid header rule.
[dev:wrangler] [pages:wrn] Service bindings are experimental. There may be breaking changes in the future.
[dev:wrangler] [pages:err] ReferenceError: DATABASE_URL_PROXY is not defined.
[dev:wrangler] Attempted to access binding using global in modules.
[dev:wrangler] You must use the 2nd `env` parameter passed to exported handlers/Durable Object constructors, or `context.env` with Pages Functions.
[dev:wrangler]     at EventTarget.get (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/standards/event.ts:291:19)
[dev:wrangler]     at node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/.prisma/client/edge.js (/workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:23896:67)
[dev:wrangler]     at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:17:46
[dev:wrangler]     at node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client/edge.js (/workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:23911:10)
[dev:wrangler]     at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:17:46
[dev:wrangler]     at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:25416:27
[dev:wrangler]     at SourceTextModule.evaluate (node:internal/vm/module:226:23)
[dev:wrangler]     at VMScriptRunner.runAsModule (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:40:18)
[dev:wrangler]     at VMScriptRunner.run (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:86:17)
[dev:wrangler]     at EventTarget.#reload (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/index.ts:790:13)
[dev:wrangler] ReferenceError: DATABASE_URL_PROXY is not defined.
[dev:wrangler] Attempted to access binding using global in modules.
[dev:wrangler] You must use the 2nd `env` parameter passed to exported handlers/Durable Object constructors, or `context.env` with Pages Functions.
[dev:wrangler]     at EventTarget.get (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/standards/event.ts:291:19)
[dev:wrangler]     at node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/.prisma/client/edge.js (/workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:23896:67)
[dev:wrangler]     at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:17:46
[dev:wrangler]     at node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client/edge.js (/workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:23911:10)
[dev:wrangler]     at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:17:46
[dev:wrangler]     at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:25416:27
[dev:wrangler]     at SourceTextModule.evaluate (node:internal/vm/module:226:23)
[dev:wrangler]     at VMScriptRunner.runAsModule (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:40:18)
[dev:wrangler]     at VMScriptRunner.run (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:86:17)
[dev:wrangler]     at EventTarget.#reload (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/index.ts:790:13)
[dev:wrangler] Waiting for the debugger to disconnect...
```

**Comment by janpio** [comment]
Also reproducible after an initial build this command:
```
gitpod /workspace/repro-prisma-client-cloud-flare-pages (main) $ pnpm dotenv -c development -- wrangler --compatibility-date 2023-03-02 pages dev ./public
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
Compiling worker to "/tmp/functionsWorker-0.26370337256135756.mjs"...
✨ Compiled Worker successfully
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ [b] open a browser, [d] open Devtools, [l] turn off local mode, [c] clear console, [x] to exit                                                                                                                                                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Debugger listening on ws://127.0.0.1:44815/5a95e8c2-f223-4309-8e5a-915686a46238
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[pages:wrn] Parsed 1 valid header rule.
[pages:wrn] Service bindings are experimental. There may be breaking changes in the future.
[pages:err] ReferenceError: DATABASE_URL_PROXY is not defined.
Attempted to access binding using global in modules.
You must use the 2nd `env` parameter passed to exported handlers/Durable Object constructors, or `context.env` with Pages Functions.
    at EventTarget.get (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/standards/event.ts:291:19)
    at node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/.prisma/client/edge.js (/workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:23896:67)
    at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:17:46
    at node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client/edge.js (/workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:23911:10)
    at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:17:46
    at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:25416:27
    at SourceTextModule.evaluate (node:internal/vm/module:226:23)
    at VMScriptRunner.runAsModule (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:40:18)
    at VMScriptRunner.run (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:86:17)
    at EventTarget.#reload (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/index.ts:790:13)
ReferenceError: DATABASE_URL_PROXY is not defined.
Attempted to access binding using global in modules.
You must use the 2nd `env` parameter passed to exported handlers/Durable Object constructors, or `context.env` with Pages Functions.
    at EventTarget.get (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/standards/event.ts:291:19)
    at node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/.prisma/client/edge.js (/workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:23896:67)
    at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:17:46
    at node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client/edge.js (/workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:23911:10)
    at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:17:46
    at /workspace/repro-prisma-client-cloud-flare-pages/functions/[[path]].js:25416:27
    at SourceTextModule.evaluate (node:internal/vm/module:226:23)
    at VMScriptRunner.runAsModule (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:40:18)
    at VMScriptRunner.run (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+runner-vm@2.12.1/node_modules/@miniflare/runner-vm/src/index.ts:86:17)
    at EventTarget.#reload (/workspace/repro-prisma-client-cloud-flare-pages/node_modules/.pnpm/@miniflare+core@2.12.1/node_modules/@miniflare/core/src/index.ts:790:13)
Waiting for the debugger to disconnect...
```

**Comment by janpio** [comment]
Closing this issue, as it is basically the same as https://github.com/prisma/prisma/issues/15958 - just with a different error message.

Workaround is currently: https://github.com/prisma/prisma/issues/15958#issuecomment-1453997671

We will update there if we find a better one.
