### ISSUE TITLE
Custom Prisma Client output location breaks Prisma Data Proxy in NextJS

### ISSUE THREAD

**Issue by borisno2** [prisma/prisma#18227]
### Bug description

When using a custom Prisma Client output location with Prisma Data proxy, the below error is received.
See https://github.com/borisno2/prisma-with-data-proxy-custom example of code not working when importing prisma client from custom location (this example works when using a direct DB connection)
While this example - importing from `@prisma/client` works - https://github.com/borisno2/prisma-with-data-proxy-standard

### How to reproduce

1. Create Next App with app directory install prisma
2. Change output location of Prisma Client
3. Import Prisma Client from custom location
4. Run `prisma generate --data-proxy`
5. Run `next dev` using a prisma data proxy url (`prisma://...` as DATABASE_URL )
6. See error
```
error - Error: 
Invalid `prisma.thing.findMany()` invocation:


Cannot fetch data from service:
Nf is not a function
    at Xr.handleRequestError (./prisma/__generated__/prisma-client/runtime/data-proxy.js:10175:52)
    at Xr.handleAndLogRequestError (./prisma/__generated__/prisma-client/runtime/data-proxy.js:10152:18)
    at Xr.request (./prisma/__generated__/prisma-client/runtime/data-proxy.js:10142:18)
    at async t._request (./prisma/__generated__/prisma-client/runtime/data-proxy.js:10701:20)
    at async Home (./app/page.tsx:28:20)
digest: "98910894"
```

### Expected behavior

Custom output location should work the same as importing from `@prisma/client` and no error should be received when using Prisma Data Proxy

### Prisma information

```prisma
datasource postgresql {
    url               = env("DATABASE_URL")
    shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
    provider          = "postgresql"
}

generator client {
    provider = "prisma-client-js"
    output   = "__generated__/prisma-client"
}

model Thing {
    id   String @id @default(cuid())
    name String @default("")
}

```

```ts
import { PrismaClient } from '../prisma/__generated__/prisma-client'

const inter = Inter({ subsets: ['latin'] })

export default async function Home() {
  const prisma = new PrismaClient({ log: ['query', 'info', 'warn', 'error'] })
  const things = await prisma.thing.findMany()
...
```

### Environment & setup

- OS: MacOS
- Database: Postgres and Prisma Data Proxy
- Node.js version:  18.13.0

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/migration-engine-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

**Comment by edmbn** [comment]
Is there any workaround for this? Prisma is broken on Next.js and multiple schemas inside a monorepo due to the plugin not working correctly. This was the last option and now It cannot work on Data Proxy with custom PrismaClient location.

**Comment by janpio** [comment]
What "plugin" do you refer to @edmbn?

**Comment by edmbn** [comment]
@janpio I'm sorry for not having detailed before. I was talking about this issue #18069 talking about @prisma/nextjs-monorepo-workaround-plugin. Everyone that have to deal with 2 schemas working with 2 databases is super blocked right now. The plugin isn't able to work with 2 clients and if we try to work with Prisma Data Proxy with find the error specified in this issue. Nothing to do apparently, that's why I asked for any workaround possible.

**Comment by janpio** [comment]
I can reproduce the problem that @borisno2 originally reported, when opening the page after `npx next dev`:

```
ient-request").runInAsyncScope(()=>u(o)))}async _executeRequest({args:n,clientMethod:o,dataPath:i,callsite:s,action:u,model:c,argsMapper:l,transaction:p,unpacker:f,otelParentCtx:d,customDataProxyFetch:m}){try{let y=await this._getProtocolEncoder({clientMethod:o,callsite:s});n=l?l(n):n;let g={name:"serialize",enabled:this._tracingConfig.enabled},b;c&&(b=Mi(u,c,n,this._rejectOnNotFound),Gm(b,c,u));let h=await Me(g,()=>y.createMessage({modelName:c,action:u,args:n,clientMethod:o,callsite:s,extensions:this._extensions}));return se.enabled("prisma:client")&&(_e("Prisma Client call:"),_e(`prisma.${o}(${Jn({ast:n,keyPaths:[],valuePaths:[],missingItems:[]})})`),_e("Generated request:"),_e(h.toDebugString()+`
error - prisma/__generated__/prisma-client/runtime/data-proxy.js (87:6414) @ Xr.handleRequestError
error - Error: 
Invalid `prisma.thing.findMany()` invocation:


Cannot fetch data from service:
Nf is not a function
    at Xr.handleRequestError (./prisma/__generated__/prisma-client/runtime/data-proxy.js:10175:52)
    at Xr.handleAndLogRequestError (./prisma/__generated__/prisma-client/runtime/data-proxy.js:10152:18)
    at Xr.request (./prisma/__generated__/prisma-client/runtime/data-proxy.js:10142:18)
    at async t._request (./prisma/__generated__/prisma-client/runtime/data-proxy.js:10701:20)
    at async Home (./app/page.tsx:28:20)
digest: "98910894"
  85 | 
  86 | More Information: https://pris.ly/d/execute-raw
> 87 | `)}a(Li,"checkAlter");function Im(e){return Array.isArray(e)}a(Im,"isReadonlyArray");var $i=a((e,t)=>([r,...n])=>{let o="",i;if(typeof r=="string")o=r,i={values:zt(n||[]),__prismaRawParameters__:!0},t.includes("executeRaw")&&Li(o,n,"prisma.$executeRawUnsafe(<SQL>, [...values])");else if(Im(r))switch(e._activeProvider){case"sqlite":case"mysql":{let s=new ce(r,n);o=s.sql,i={values:zt(s.values),__prismaRawParameters__:!0};break}case"cockroachdb":case"postgresql":{let s=new ce(r,n);o=s.text,t.includes("executeRaw")&&Li(o,s.values,"prisma.$executeRaw`<SQL>`"),i={values:zt(s.values),__prismaRawParameters__:!0};break}case"sqlserver":{o=ki(r),i={values:zt(n),__prismaRawParameters__:!0};bre
```

Or a bit cleaner and without less minified code being barfed at you with `npm run build`:

```
info  - Compiled successfully
info  - Linting and checking validity of types  
info  - Collecting page data  
[    ] info  - Generating static pages (0/4)prisma:info Calling https://aws-us-east-1.prisma-data.com/4.11.0/e398e8f3206d8e21cdc0e3af46dcb1ba2fdae7a1f75ab60fcc0d8871303c32f8/graphql (n=0)
prisma:warn Attempt 1/3 failed for querying: Cannot fetch data from service:
Nf is not a function
prisma:warn Retrying after 41ms
prisma:info Calling https://aws-us-east-1.prisma-data.com/4.11.0/e398e8f3206d8e21cdc0e3af46dcb1ba2fdae7a1f75ab60fcc0d8871303c32f8/graphql (n=1)
prisma:warn Attempt 2/3 failed for querying: Cannot fetch data from service:
Nf is not a function
[=   ] info  - Generating static pages (3/4)prisma:warn Retrying after 131ms
prisma:info Calling https://aws-us-east-1.prisma-data.com/4.11.0/e398e8f3206d8e21cdc0e3af46dcb1ba2fdae7a1f75ab60fcc0d8871303c32f8/graphql (n=2)
prisma:warn Attempt 3/3 failed for querying: Cannot fetch data from service:
Nf is not a function
prisma:warn Retrying after 287ms
prisma:info Calling https://aws-us-east-1.prisma-data.com/4.11.0/e398e8f3206d8e21cdc0e3af46dcb1ba2fdae7a1f75ab60fcc0d8871303c32f8/graphql (n=3)
prisma:error 
Invalid `prisma.thing.findMany()` invocation:


Cannot fetch data from service:
Nf is not a function
PrismaClientKnownRequestError: 
Invalid `prisma.thing.findMany()` invocation:


Cannot fetch data from service:
Nf is not a function
    at Xr.handleRequestError (/workspace/prisma-with-data-proxy-custom/.next/server/app/page.js:10865:52)
    at Xr.handleAndLogRequestError (/workspace/prisma-with-data-proxy-custom/.next/server/app/page.js:10842:18)
    at Xr.request (/workspace/prisma-with-data-proxy-custom/.next/server/app/page.js:10832:18)
    at async t._request (/workspace/prisma-with-data-proxy-custom/.next/server/app/page.js:11391:20)
    at async Home (/workspace/prisma-with-data-proxy-custom/.next/server/app/page.js:410:20) {
  code: 'P5010',
  clientVersion: '4.11.0',
  meta: undefined
}

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
```

**Comment by janpio** [comment]
From the minified `data-proxy.js` I get this for `Nf`:

```async function ni(e, t = {}) {
	let r = Nf("https"),
		n = If(t),
		o = [],
		{
			origin: i
		} = new URL(e);
	return new Promise((s, u) => {
		let c = r.request(e, n, l => {
			let {
				statusCode: p,
				headers: {
					location: f
				}
			} = l;
			p >= 301 && p <= 399 && f && (f.startsWith("http") === !1 ? s(ni(`${i}${f}`, t)) : s(ni(f, t))), l.on("data", d => o.push(d)), l.on("end", () => s(Df(o, l))), l.on("error", u)
		});
		c.on("error", u), c.end(t.body ?? "")
	})
}

a(ni, "nodeFetch");
var Nf = typeof require < "u" ? require : () => {};
var Ff = /^[1-9][0-9]*\.[0-9]+\.[0-9]+$/,
	Ba = se("prisma:client:dataproxyEngine");
async function kf(e) {
		let t = ja["@prisma/engines-version"],
			r = e.clientVersion ?? "unknown";
		if (process.env.PRISMA_CLIENT_DATA_PROXY_CLIENT_VERSION) return process.env.PRISMA_CLIENT_DATA_PROXY_CLIENT_VERSION;
		let [n, o] = r?.split("-") ?? [];
		if (o === void 0 && Ff.test(n)) return n;
		if (o !== void 0 || r === "0.0.0") {
			if (process.env.TEST_DATA_PROXY !== void 0) return "0.0.0";
			let [i] = t.split("-") ?? [], [s, u, c] = i.split("."), l = Lf(`<=${s}.${u}.${c}`), p = await lt(l, {
				clientVersion: r
			});
			if (!p.ok) throw new Error(`Failed to fetch stable Pri
```

**Comment by janpio** [comment]
I can also confirm that removing the custom `output` and updating the import from the custom one to just `@prisma/client` (or `@prisma/client/edge`) makes the project work just fine.
