### ISSUE TITLE
Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead (drupal)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1823]
https://github.com/prisma/introspection-engine-output/blob/17c81171e67e1e45312668a9b38b977dc061996b/test-utils/results/mysql_public_test_utils_drupal_stderr.log

```
2020-03-11T13:55:21.617Z prisma-client prisma.lAfOL_block_content_field_data.create({
  data: {
    changed: -1512,
    default_langcode: 440,
    id: 4,
    info: 'bawha',
    langcode: '57e13d34-ca08-5720-b994-69fb4d3a0f81',
    reusable: 990,
    revision_id: -915,
    revision_translation_affected: 159,
    status: 1315,
    type: 'uhred'
  }
})
2020-03-11T13:55:21.617Z prisma-client Generated request:
2020-03-11T13:55:21.617Z prisma-client mutation {
  createOnelAfOL_block_content_field_data(data: {
    changed: -1512
    default_langcode: 440
    id: 4
    info: "bawha"
    langcode: "57e13d34-ca08-5720-b994-69fb4d3a0f81"
    reusable: 990
    revision_id: -915
    revision_translation_affected: 159
    status: 1315
    type: "uhred"
  }) {
    changed
    default_langcode
    id
    info
    langcode
    reusable
    revision_id
    revision_translation_affected
    status
    type
  }
}

...

Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead.
    at PrismaClientFetcher.request (/home/runner/work/introspection-engine-output/introspection-engine-output/clients/mysql_public_test_utils/drupal/runtime/index.js:1:47203)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

```prisma
model lAfOL_block_content_field_data {
  changed                       Int?
  default_langcode              Int
  id                            Int
  info                          String?
  langcode                      String
  reusable                      Int?
  revision_id                   Int
  revision_translation_affected Int?
  status                        Int
  type                          String

  @@id([id, langcode])
  @@index([id, default_langcode, langcode], name: "block_content__id__default_langcode__langcode")
  @@index([revision_id], name: "block_content__revision_id")
  @@index([status, type, id], name: "block_content__status_type")
  @@index([type], name: "block_content_field__type__target_id")
}
```

```sql
CREATE TABLE `lAfOL_block_content_field_data` (
  `id` int(10) unsigned NOT NULL,
  `revision_id` int(10) unsigned NOT NULL,
  `type` varchar(32) CHARACTER SET ascii NOT NULL COMMENT 'The ID of the target entity.',
  `langcode` varchar(12) CHARACTER SET ascii NOT NULL,
  `status` tinyint(4) NOT NULL,
  `info` varchar(255) DEFAULT NULL,
  `changed` int(11) DEFAULT NULL,
  `reusable` tinyint(4) DEFAULT NULL,
  `default_langcode` tinyint(4) NOT NULL,
  `revision_translation_affected` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`,`langcode`),
  KEY `block_content__id__default_langcode__langcode` (`id`,`default_langcode`,`langcode`),
  KEY `block_content__revision_id` (`revision_id`),
  KEY `block_content_field__type__target_id` (`type`),
  KEY `block_content__status_type` (`status`,`type`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='The data table for block_content entities.';
```

**Comment by janpio** [comment]
On local reproduction the error message is different:

```
C:\Users\Jan\Documents\throwaway\1817>node index.js
(node:8944) UnhandledPromiseRejectionWarning: Error:
Invalid `const data = await prisma.lafol_block_content_field_data.create()` invocation in
C:\Users\Jan\Documents\throwaway\1817\index.js:6:60

  2 
  3 const prisma = new PrismaClient()
  4 
  5 async function main() {
→ 6   const data = await prisma.lafol_block_content_field_data.create(

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Server(ServerError { code: 1264, message: "Out of range value for column \'default_langcode\' at row 1", state: "22003" })) })
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\throwaway\1817\node_modules\@prisma\client\runtime\index.js:1:47359)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:8944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pantharshit00** [comment]
The current output for this test doesn't have this error: https://github.com/prisma/introspection-engine-output/blob/master/test-utils/results/mysql_public_test_utils_drupal_stderr.log

I think this can be closed @janpio

**Comment by janpio** [comment]
Please confirm manually with the SQL supplied in the issue - test-utils might have changed its behavior or the database is different to what was observed before.

**Comment by pantharshit00** [comment]
Ok, we have now a better error for this:
![image](https://user-images.githubusercontent.com/22195362/89651832-26992280-d8e2-11ea-951c-761a9baec250.png)

This completely makes sense as revision_id is unsigned but the query which test utils generated is signed with a negative value.

cc @divyenduz for a potential test utils fix. 

I think this can be closed. Reopen @janpio if you this there is something we can do additionally here.

**Comment by pantharshit00** [comment]
Support for unsigned in the schema is now tracked by https://github.com/prisma/prisma/issues/3239

**Comment by janpio** [comment]
Does this work for both MySQL and Postgres?

**Comment by pantharshit00** [comment]
@janpio Postgres doesn't have a concept of unsigned integer (ref https://stackoverflow.com/questions/2991405/what-is-the-difference-between-tinyint-smallint-mediumint-bigint-and-int-in-m)

**Comment by eemmiillyy** [comment]
Integration tests have been added for these with (https://github.com/prisma/prisma/pull/3683) in (https://github.com/prisma/prisma/commit/cd8361cf5a1e4c8786f40075db9888e188e701c1#diff-6e4bbddeca93b81ae24c82eaef9bbf5e)
