### ISSUE TITLE
Prisma can't generate Client and run Migrations for Openssl 3.1.x

### ISSUE THREAD

**Issue by SomeUserNameReally** [prisma/prisma#18342]
### Bug description

When running `prisma generate`  on Clear Linux OS.

I also get the error: `Unable to resolve path to query-engine binary`

The command `openssl version` returns

```bash
OpenSSL 3.1.0 14 Mar 2023 (Library: OpenSSL 3.1.0 14 Mar 2023)
```

The command `prisma migrate dev` also fails for the same reason.

The commands run fine where openssl version is less than 3.1

### Expected behavior

I am able to generate the client and run migrations.

### Prisma information

An excerpt from my `shema.prisma`.
```prisma
generator client {
  provider = "prisma-client-js"
}

generator typegraphql {
  provider = "typegraphql-prisma"
  output   = "./generated/type-graphql"
}
```

### Environment & setup

- OS: Clear Linux OS
- Database: PostgreSQL
- Node.js version: 16.19.1

### Prisma Version

```sh
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/migration-engine-debian-openssl-3.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

**Comment by janpio** [comment]
That would be this code: https://github.com/prisma/prisma/blob/ab328bd3602d44832428e5db37c77d0a7ae9cba2/packages/internals/src/engine-commands/queryEngineCommons.ts#L13-L22

Anything special in your project or are you confident if we setup a Clear Linux OS docker container and a trivial project using Prisma we would hit the same problem?

**Comment by SomeUserNameReally** [comment]
> That would be this code:
> 
> https://github.com/prisma/prisma/blob/ab328bd3602d44832428e5db37c77d0a7ae9cba2/packages/internals/src/engine-commands/queryEngineCommons.ts#L13-L22
> 
> Anything special in your project or are you confident if we setup a Clear Linux OS docker container and a trivial project using Prisma we would hit the same problem?

I'm pretty sure the issue is with the newer version of openssl. I'm on a fresh installation of Clear Linux; it wasn't working in the beginning, then it started working when I ran `npx prsima studio` (not sure why, maybe updates on the system ran or something), and it's not working again now.

In all this I hadn't changed `schema.prisma`.  I tried updating Prisma from `4.0.0` but that didn't help. Please note I'm using TypeGraphQL. I'm also using `bun` to run my scripts locally, but the project worked fine with this so I doubt that's causing the problem.

Thank you for looking into this.

**Comment by janpio** [comment]
Can you please share the full output you get when you enable `DEBUG=*` as an env var and then run `prisma generate`? Thanks.
Does it also happen when you remove the `generator typegraphql`?

**Comment by SomeUserNameReally** [comment]
@janpio 

The output for `npx prisma generate` with `DEBUG=*` in the env:

```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "clear-linux-os". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
prisma:warn Prisma doesn't know which engines to download for the Linux distro "clear-linux-os". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
  prisma:tryLoadEnv  Environment variables loaded from /home/ajay/Dev/Work/Stockment/backend/.env +0ms
Error:
✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in 194ms

Unable to resolve path to query-engine binary
Details: Could not find libquery-engine binary. Searched in:
- /home/ajay/Dev/Work/Stockment/backend/node_modules/@prisma/internals/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.1.x.so.node
- /home/ajay/Dev/Work/Stockment/backend/node_modules/@prisma/internals/libquery_engine-debian-openssl-3.1.x.so.node
- /home/ajay/Dev/Work/Stockment/backend/node_modules/@prisma/libquery_engine-debian-openssl-3.1.x.so.node
- /home/ajay/Dev/Work/Stockment/backend/node_modules/@prisma/internals/runtime/libquery_engine-debian-openssl-3.1.x.so.node
[Context: getDmmf]

Prisma CLI Version : 4.3.1
```

When I remove `generator typegraphql` the client generates but with warnings:

```
npx prisma generate
prisma:warn Prisma doesn't know which engines to download for the Linux distro "clear-linux-os". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
prisma:warn Prisma doesn't know which engines to download for the Linux distro "clear-linux-os". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
  prisma:tryLoadEnv  Environment variables loaded from /home/ajay/Dev/Work/Stockment/backend/.env +0ms

✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in 192ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

**Comment by janpio** [comment]
> When I remove `generator typegraphql` the client generates but with warnings:

Yes, those are perfectly fine.

So this is not a problem with Prisma Client itself, but with the prisma typegraphql generator. Interesting.

**Comment by SomeUserNameReally** [comment]
@janpio 

Yes, but I still think the main culprit here is the openssl version. I just pulled the docker image for Clear Linux where the openssl version is less than `3.1` and generated the client successfully.

**Comment by SomeUserNameReally** [comment]
@janpio 

I tried to generate the client again on my Clear Linux with `DEBUG=*`, and it gave me the following output. I think I must have configured the env incorrectly before, sorry about the confusion.

```
prisma:engines  binaries to download libquery-engine, migration-engine +0ms
  prisma:get-platform  Found distro info:
{
  "originalDistro": "clear-linux-os"
} +0ms
  prisma:get-platform  Command "uname -m" successfully returned "x86_64
" +14ms
  prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +0ms
  prisma:get-platform  Falling back to "ldconfig" and other generic paths +0ms
  prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
" +44ms
  prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
 +0ms
prisma:warn Prisma doesn't know which engines to download for the Linux distro "clear-linux-os". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
  prisma:get-platform  Found distro info:
{
  "originalDistro": "clear-linux-os"
} +2ms
  prisma:get-platform  Command "uname -m" successfully returned "x86_64
" +9ms
  prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +1ms
  prisma:get-platform  Falling back to "ldconfig" and other generic paths +0ms
  prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
" +45ms
  prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
 +0ms
  prisma:get-platform  Found distro info:
{
  "originalDistro": "clear-linux-os"
} +1ms
  prisma:get-platform  Command "uname -m" successfully returned "x86_64
" +8ms
  prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +0ms
  prisma:get-platform  Falling back to "ldconfig" and other generic paths +0ms
  prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
" +41ms
  prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
 +0ms
  prisma:loadEnv  project root found at /path/to/my/project/package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from /path/to/my/project/.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
  prisma:get-platform  Found distro info:
{
  "originalDistro": "clear-linux-os"
} +0ms
  prisma:get-platform  Command "uname -m" successfully returned "x86_64
" +14ms
  prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +1ms
  prisma:get-platform  Falling back to "ldconfig" and other generic paths +0ms
  prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
" +52ms
  prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
 +0ms
prisma:warn Prisma doesn't know which engines to download for the Linux distro "clear-linux-os". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
  prisma:get-platform  Found distro info:
{
  "originalDistro": "clear-linux-os"
} +9ms
  prisma:get-platform  Command "uname -m" successfully returned "x86_64
" +9ms
  prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +0ms
  prisma:get-platform  Falling back to "ldconfig" and other generic paths +1ms
  prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
" +29ms
  prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
 +0ms
  prisma:get-platform  Found distro info:
{
  "originalDistro": "clear-linux-os"
} +1ms
  prisma:get-platform  Command "uname -m" successfully returned "x86_64
" +7ms
  prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +0ms
  prisma:get-platform  Falling back to "ldconfig" and other generic paths +0ms
  prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
" +29ms
  prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
 +0ms
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +4ms
  prisma:getDMMF  Using getDmmf Wasm +0ms
  prisma:getDMMF  Using given datamodel +0ms
  prisma:getDMMF  dmmf data retrieved without errors in getDmmf Wasm +19ms
  prisma:generator  prismaCLIDir /path/to/my/project/node_modules/prisma +0ms
  prisma:generator  prismaClientDir /path/to/my/project/node_modules/@prisma/client +0ms
  prisma:generator  baseDir /path/to/my/project/prisma +0ms
  prisma:generator  typescriptPath /path/to/my/project/node_modules/typescript +1ms
  prisma:GeneratorProcess  2023-03-18T22:24:17.178Z prisma:client:generator  requiredEngine: libqueryEngine +0ms
  prisma:getGenerators  neededVersions {
  "8fde8fef4033376662cad983758335009d522acb": {
    "engines": [
      "libqueryEngine"
    ],
    "binaryTargets": []
  }
} +0ms
  prisma:get-platform  Found distro info:
{
  "originalDistro": "clear-linux-os"
} +1s
  prisma:get-platform  Command "uname -m" successfully returned "x86_64
" +9ms
  prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +0ms
  prisma:get-platform  Falling back to "ldconfig" and other generic paths +0ms
  prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
" +28ms
  prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
 +0ms
  prisma:get-platform  Found distro info:
{
  "originalDistro": "clear-linux-os"
} +1ms
  prisma:get-platform  Command "uname -m" successfully returned "x86_64
" +7ms
  prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +1ms
  prisma:get-platform  Falling back to "ldconfig" and other generic paths +0ms
  prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
" +30ms
  prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so
libssl.so
libssl.so
libssl.so
libssl.so.3
libssl.so.3
libssl.so.3
 +0ms
  prisma:getGenerators  {
  generatorBinaryPaths: {
    libqueryEngine: {
      'debian-openssl-3.0.x': '/path/to/my/project/node_modules/prisma/libquery_engine-debian-openssl-3.0.x.so.node'
    }
  }
} +121ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.181Z prisma:loadEnv  project root found at /path/to/my/project/package.json +1s
  prisma:GeneratorProcess  2023-03-18T22:24:18.257Z prisma:get-platform  Found distro info: +76ms
  prisma:GeneratorProcess  { +0ms
  prisma:GeneratorProcess    "originalDistro": "clear-linux-os" +0ms
  prisma:GeneratorProcess  } +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.261Z prisma:get-platform  Found distro info: +5ms
  prisma:GeneratorProcess  { +0ms
  prisma:GeneratorProcess    "originalDistro": "clear-linux-os" +0ms
  prisma:GeneratorProcess  } +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.265Z prisma:get-platform  Command "uname -m" successfully returned "x86_64 +3ms
  prisma:GeneratorProcess  " +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.266Z prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +1ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.266Z prisma:get-platform  Falling back to "ldconfig" and other generic paths +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.276Z prisma:get-platform  Command "uname -m" successfully returned "x86_64 +12ms
  prisma:GeneratorProcess  " +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.276Z prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.276Z prisma:get-platform  Falling back to "ldconfig" and other generic paths +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.298Z prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so +20ms
  prisma:GeneratorProcess  libssl.so +1ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  " +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.298Z prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  prisma:warn Prisma doesn't know which engines to download for the Linux distro "clear-linux-os". Falling back to Prisma engines built "debian". +0ms
  prisma:GeneratorProcess  Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros. +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.300Z prisma:get-platform  Found distro info: +1ms
  prisma:GeneratorProcess  { +0ms
  prisma:GeneratorProcess    "originalDistro": "clear-linux-os" +0ms
  prisma:GeneratorProcess  } +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.304Z prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so +4ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  " +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.304Z prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  prisma:warn Prisma doesn't know which engines to download for the Linux distro "clear-linux-os". Falling back to Prisma engines built "debian". +0ms
  prisma:GeneratorProcess  Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros. +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.305Z prisma:get-platform  Command "uname -m" successfully returned "x86_64 +1ms
  prisma:GeneratorProcess  " +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.305Z prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.305Z prisma:get-platform  Falling back to "ldconfig" and other generic paths +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.316Z prisma:get-platform  Found distro info: +11ms
  prisma:GeneratorProcess  { +0ms
  prisma:GeneratorProcess    "originalDistro": "clear-linux-os" +0ms
  prisma:GeneratorProcess  } +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.323Z prisma:get-platform  Command "uname -m" successfully returned "x86_64 +7ms
  prisma:GeneratorProcess  " +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.323Z prisma:get-platform  Don't know any platform-specific paths for "undefined" on x64 (x86_64) +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.323Z prisma:get-platform  Falling back to "ldconfig" and other generic paths +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.333Z prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so +12ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  " +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.333Z prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.345Z prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so +10ms
  prisma:GeneratorProcess  libssl.so +1ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  " +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.345Z prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  libssl.so.3 +0ms
  prisma:GeneratorProcess  2023-03-18T22:24:18.419Z prisma:getDMMF  error of type "query-engine-unresolved" in getDmmfNodeAPI: +75ms
  prisma:GeneratorProcess   { +0ms
  prisma:GeneratorProcess    reason: 'Unable to resolve path to query-engine binary', +1ms
  prisma:GeneratorProcess    error: Error: Could not find libquery-engine binary. Searched in: +0ms
  prisma:GeneratorProcess    - /path/to/my/project/node_modules/@prisma/internals/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.1.x.so.node +0ms
  prisma:GeneratorProcess    - /path/to/my/project/node_modules/@prisma/internals/libquery_engine-debian-openssl-3.1.x.so.node +0ms
  prisma:GeneratorProcess    - /path/to/my/project/node_modules/@prisma/libquery_engine-debian-openssl-3.1.x.so.node +0ms
  prisma:GeneratorProcess    - /path/to/my/project/node_modules/@prisma/internals/runtime/libquery_engine-debian-openssl-3.1.x.so.node +0ms
  prisma:GeneratorProcess        at resolveBinary (/path/to/my/project/node_modules/@prisma/internals/dist/resolveBinary.js:91:9) +0ms
  prisma:GeneratorProcess  } +0ms
  prisma:tryLoadEnv  Environment variables loaded from /path/to/my/project/.env +0ms
Error: Error:
✔ Generated Prisma Client (4.11.0 | library) to ./node_modules/@prisma/client in 205ms

Unable to resolve path to query-engine binary
Details: Could not find libquery-engine binary. Searched in:
- /path/to/my/project/node_modules/@prisma/internals/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.1.x.so.node
- /path/to/my/project/node_modules/@prisma/internals/libquery_engine-debian-openssl-3.1.x.so.node
- /path/to/my/project/node_modules/@prisma/libquery_engine-debian-openssl-3.1.x.so.node
- /path/to/my/project/node_modules/@prisma/internals/runtime/libquery_engine-debian-openssl-3.1.x.so.node
[Context: getDmmf]

Prisma CLI Version : 4.3.1


    at _Generate.parse (/path/to/my/project/node_modules/prisma/build/index.js:97917:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/path/to/my/project/node_modules/prisma/build/index.js:99555:18)
error: "prisma" exited with code 1 (SIGHUP)
```

**Comment by janpio** [comment]
> Prisma CLI Version : 4.3.1

I think this is your problem @SomeUserNameReally. It contradicts what you posted as your version ouptut:

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
```

How did you run the CLI to get the version output, vs. how did you run it to `generate`?
If that was in any way different, that could explain the difference.

**Comment by SomeUserNameReally** [comment]
@janpio 

It turns out the generator was old and prisma wasn't identifying this correctly.

I generated the client and ran migrations successfully when I updated both prisma and typegraphql. However, after this when I try to run the dev server, I get this error (also without using 'bun`):

```
TSError: ⨯ Unable to compile TypeScript:
prisma/generated/type-graphql/helpers.ts:27:22 - error TS2488: Type '[string, any] | undefined' must have a '[Symbol.iterator]()' method that returns an iterator.

27               const [[key, { value }]] = Object.entries(argument);
```

I'm not sure what's happening here.

**Comment by SomeUserNameReally** [comment]
@janpio 
 
Ah, I see! So the generator is failing, not prisma.

That was a bit of a wild goose chase, but thank you for looking into this with me!

I will open an issue there, I will mark this as closed.

Thank you again!
