### ISSUE TITLE
`ENOENT: ../../node_modules/.prisma/client/query-engine-darwin-arm64 --enable-raw-queries cli dmmf`

### ISSUE THREAD

**Issue by NoumanHumayun** [prisma/prisma#18354]
### Bug description

**@Prisma/Client v4.9.0**

Prisma fails with the following error when running any CRUD api methods while using `binary` type engine.

``` 
generator client {
  provider = "prisma-client-js"
  engineType = "binary"
  binaryTargets = ["native","debian-openssl-1.1.x"]
}
```

Tried manually pasting the generated engine file in all the possible locations for it to be accessed on this path `../../node_modules/.prisma/client/query-engine-darwin`, but correct path is not the issue.

Tried updating openssl@1. to openssl@3 

Tried upgrading prisma version to 4.11.0 & downgrading to 4.3.0

Tried using `@prisma/cli@alpha` instead of `prisma` as this is clearly a cli command that fails

```
Stack Trace: 
`"Error: ",
  "Invalid `prisma.xxxx.create()` invocation:",
  

  "Command failed with ENOENT: ../../node_modules/.prisma/client/query-engine-darwin--enable-raw-queries cli dmmf",
  "spawn ../../node_modules/.prisma/client/query-engine-darwin ENOENT",
  "    at RequestHandler.handleRequestError (webpack-internal:///../../node_modules/@prisma/client/runtime/index.js:31932:13)",
  "    at RequestHandler.handleAndLogRequestError (webpack-internal:///../../node_modules/@prisma/client/runtime/index.js:31904:12)",
  "    at eval (webpack-internal:///../../node_modules/@prisma/client/runtime/index.js:32449:25)",
  "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "    at async PrismaClient._executeRequest (webpack-internal:///../../node_modules/@prisma/client/runtime/index.js:33011:22)",
  "    at async PrismaClient._request (webpack-internal:///../../node_modules/@prisma/client/runtime/index.js:32983:16)"`
```

### How to reproduce

Just change engineType to `binary`

```
generator client {
  provider = "prisma-client-js"
  engineType = "binary"
  binaryTargets = ["native","debian-openssl-1.1.x"]
}
```

### Prisma information

```prisma
// Add your schema.prisma
```
NON schema related issue, works fine on local without `binary` engineType

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Ubuntu & MacOS & MacOS intel64 
- Database: Postgresql
- Node.js version: 18.12 & 18.14

### Prisma Version

```
4.9.0, 4.11.0, 4.3.0
```

**Comment by janpio** [comment]
> Tried using `@prisma/cli@alpha` instead of `prisma` as this is clearly a cli command that fails

That package is outdated and completely irrelevant. Prisma CLI, also `prisma` is in no way related to what you are reporting.

Why do you want to use `engineType=binary`?

Does `node_modules/.prisma/client/query-engine-darwin-arm64` or `node_modules/.prisma/client/query-engine-darwin` (your issue includes both...) exist in your project? If yes, what happen when you execute the command from the title manually in your terminal?

**Comment by NoumanHumayun** [comment]
if I don't use binary prisma crashes on Ubuntu and server restarts.

Yes the problem occurs on both arm and arm64 arch

When I run that command

`{"is_panic":false,"message":"Datamodel should be provided either as path or base64-encoded string.","backtrace":"   0: __mh_execute_header\n   1: __mh_execute_header\n   2: __mh_execute_header\n   3: __mh_execute_header\n   4: __mh_execute_header\n   5: __mh_execute_header\n   6: __mh_execute_header\n   7: <unknown>\n"}`

**Comment by NoumanHumayun** [comment]
Yes, that issue is already reported [here](https://github.com/prisma/prisma/issues/10649#issuecomment-1454138068) with the solution that worked for many. i.e. using engineType: 'binary'

App details:
Node v18
webpack 5.7
Graphql 15
inversify 6

Only difference is that we are using inversify to inject prisma. however even with simple no-hoist implementation (i.e. without inversify) we faced same issue.

This exact implementation works with engineType library ONLY on local and crashes as the thread attached above on docker (Ubuntu 18).

**Comment by janpio** [comment]
Ok, then the original error is indeed covered well enough in the other issue(s).

You should never have to copy/paste any files anywhere. It should just work.

Can you provide a reproduction of your project setup that could help us reproduce your problem? With yarn workspaces and inversify that is pretty specific.

**Comment by alexander-joinlane** [comment]
@NoumanHumayun, I have an implementation on a personal project which has had no problems post-build:

For context, this is running on windows (reason for atypical path construction), but I did need to specifically `COPY` the `.prisma` module (since I didn't want to `yarn prisma generate` or whatever) within the build process, I expect it to be done upfront.

Not sure if any of this pet stuff will help.

## Dockerfile
```Dockerfile
FROM node:18

WORKDIR /usr/awesome-bot

COPY package*.json ./

RUN yarn --production=true

COPY ./dist .
COPY .env .
COPY ./node_modules/.prisma ./node_modules/.prisma
VOLUME ["/usr/awesome-bot/prisma"]

CMD ["node", "index.js"]
```

## docker-compose.yml
```yml
version: '3.4'

services:
  awesomebot:
    image: awesomebot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/usr/awesome-bot/prisma/dev.db
      TZ: "America/Toronto"
    volumes:
      - "D:/Projects/awesome-bot/prisma:/usr/awesome-bot/prisma"
```

## schema.prisma
```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

// Rest of the file is the models.
```

**Comment by jkomyno** [comment]
Hi @NoumanHumayun, did @alexander-joinlane's [comment](https://github.com/prisma/prisma/issues/18354#issuecomment-1479576339) help you figuring out how to solve this issue? Can you please report back about it - also by trying with the latest available Prisma version? Thanks!

**Comment by jkomyno** [comment]
Hey @NoumanHumayun, I saw you noticed our latest comment 👀😄
Can you please confirm that this issue is indeed solved in Prisma 5? Thanks

**Comment by jkomyno** [comment]
Hey @NoumanHumayun, we're closing this issue due to inactivity, as we consider [this](https://github.com/prisma/prisma/issues/18354#issuecomment-1479576339) being the solution to the reported problem. Should that not suffice, please leave a comment asking to re-open this issue.
