### ISSUE TITLE
CloudLinux wrong detection and libc

### ISSUE THREAD

**Issue by jcubic** [prisma/prisma#18504]
### Bug description

I use CloudLinux on my hosting provider which is based on RHEL. According to system requirement supported version of Libc is 2.17 for RHEL, but when executing prisma it detects Debian and fail to find the proper libc shared library that is in version 2.17

```
$ npx prisma -v
prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Environment variables loaded from .env
prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Error: Unable to require(`/home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.0.x.so.node`).
Prisma has detected an incompatible version of the `glibc` C standard library installed in your system. This probably means your system may be too old to run Prisma. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.0.x.so.node)
    at loadLibrary (/home/jcubic/websites/koduj/quiz/node_modules/prisma/build/index.js:91305:11)
    at getEngineVersion (/home/jcubic/websites/koduj/quiz/node_modules/prisma/build/index.js:91319:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Command failed with exit code 1: /home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x --version
/home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)
    at makeError (/home/jcubic/websites/koduj/quiz/node_modules/prisma/build/index.js:3641:18)
    at handlePromise (/home/jcubic/websites/koduj/quiz/node_modules/prisma/build/index.js:4409:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getEngineVersion (/home/jcubic/websites/koduj/quiz/node_modules/prisma/build/index.js:91322:20) {
  shortMessage: 'Command failed with exit code 1: /home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x --version',
  command: '/home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x --version',
  escapedCommand: '"/home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x" --version',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "/home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : debian-openssl-1.0.x
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.0.x.so.node)
Migration Engine        : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```
This are the shared libraries:

```
$ ls /lib64/libc{-,.}*
/lib64/libc-2.17.so  /lib64/libc-client.so  /lib64/libc-client.so.2007  /lib64/libc.so  /lib64/libc.so.6
```

### How to reproduce

1. Install Prisma on CloudLinux

### Expected behavior

Prisma works on CloudLinux

### Prisma information

NA

### Environment & setup

- OS:  CloudLInux
- Database:  `mysql  Ver 15.1 Distrib 10.4.24-MariaDB, for Linux (x86_64) using readline 5.1`
- Node.js version:  `v16.17.0`

### Prisma Version

NA

**Comment by jcubic** [comment]
There may be a problem in detecting OS on my system because there is any file in /etc/ directory. So I suggest adding a way to force the system. Users that know what kind of system they use can force a proper OS.

**Comment by jcubic** [comment]
After modification this code in node_modules:

```javascript
async function resolveDistro() {
  const osReleaseFile = "/etc/os-release";
  try {
    const osReleaseInput = await readFile(osReleaseFile, { encoding: "utf-8" });
    return parseDistro(osReleaseInput);
  } catch (_) {
    return {
      targetDistro: "rhel",
      familyDistro: "rhel",
      originalDistro: "CloudLinux"
    };
  }
}
```


Not sure why the code needed to be replaced in 3 files:
```
$ find node_modules/ -type f | xargs grep -o 'resolveDistro'
```

```
$ npx prisma -v
Environment variables loaded from .env
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : rhel-openssl-1.0.x
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/libquery_engine-rhel-openssl-1.0.x.so.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/@prisma/engines/migration-engine-rhel-openssl-1.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

I propose to use .env file to force the content of `/etc/os-release` this will make it possible to run on noncompatible systems that have compatible shared libraries.

I'm not sure how hard it will be to use `.env` file so maybe there is a way to use a normal Environment variable:

```
PRISM_FORCE_OS="ID=Cloud Linux\nID_LIKE=rhel"
```

I'm not sure what is the content of real CloudLinux because I don't have access, but I could just use:

```
PRISM_FORCE_OS="ID=fedora"
```

and it would just work, even if Cloud Linux is not part of the supported systems.

**Comment by jcubic** [comment]
My shared hosting support added file `/etc/os-release`:

```
NAME="CloudLinux"
VERSION="7.9 (Boris Yegorov)"
ID="cloudlinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="7.9"
PRETTY_NAME="CloudLinux 7.9 (Boris Yegorov)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:cloudlinux:cloudlinux:7.9:GA:server"
HOME_URL="https://www.cloudlinux.com/"
BUG_REPORT_URL="https://www.cloudlinux.com/support"
```

and now everything works, but I think that by default this file is missing that's why people have problems with CloudLinux, I'm willing to create a PR but I will no longer be able to test if this works. It's still a good idea to add this fallback env variable, this will solve a lot of issues. And probably not every hosting provider will be able to add this file to their server if missing.

**Comment by jcubic** [comment]
@soulr344 I think that it was working only for `npx prisma --version` I was not able to run normally, but I'm almost sure that this is the code that need to be fixed it only in multiple output files.

**Comment by ahinouye** [comment]
Having the same issue

**Comment by guyromb** [comment]
Same issue. Related to https://github.com/prisma/prisma/issues/18504

**Comment by Skatox** [comment]
Same problem here

**Comment by TiagoAndreAlmeida** [comment]
This is happen to me too.

**Comment by zsz20olesnica** [comment]
Same issue

**Comment by Jolg42** [comment]
Hello here,

I'm curious to know if this is still an issue with a recent version of Prisma and CloudLinux.

Please let us know and make sure to provide the versions when commenting.

If you can guide us on how we could try to reproduce this, that would help a lot, I guess there is no easy Dockerfile for this case, and we would need to install the OS as a VM (https://docs.cloudlinux.com/solo/installation/)

Notes: there is another issue about CloudLinux here https://github.com/prisma/prisma/issues/13977
From this comment https://github.com/prisma/prisma/issues/13977#issuecomment-1515274387 it could be this is only affecting CloudLinux v7 and v8 works.
v7 is apparently End-of-Life now (CloudLinux has recently announced the end-of-life for CloudLinux OS 7 (June 30, 2024) from https://blog.cloudlinux.com/)
v8 seems "old" and the current version is v9 I think.

**Comment by jkomyno** [comment]
Hi @jcubic and others, would the comment posted [here](https://github.com/prisma/prisma/issues/13977#issuecomment-2162635038) help anybody? Since v7 is end-of-life, and we didn't receive any reproduction for this issue, we welcome your feedback, as otherwise we will be unable to proceed with this issue. Thanks!

**Comment by jcubic** [comment]
I'm not able to test this. I use CloudLinux provided by the hosting company and they fixed my issue by adding a missing file.
