### ISSUE TITLE
`thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: No unsupported field should reach that path', query-engine\connectors\sql-query-connector\src\model_extensions\scalar_field.rs:70:44`

### ISSUE THREAD

**Issue by benkroeger** [prisma/prisma#18517]
Hi Prisma Team! My Prisma Client just crashed. This is the report:

This issue seems to be related to the use of `unsupported` on my model's field `path` (which is of type `ltree`).
Issue does not happen with PrismaClient@4.10.1

internal error: entered unreachable code: No unsupported field should reach that path

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.14.2           | 
| OS              | darwin             |
| Prisma Client   | 4.11.0             |
| Query Engine    | 8fde8fef4033376662cad983758335009d522acb|
| Database        | postgresql         |

## Logs
```
prisma:tryLoadEnv Environment variables loaded from .env
prisma:tryLoadEnv Environment variables loaded from .env
prisma:client dirname node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd prisma
prisma:client protocol graphql
prisma:client clientVersion 4.11.0
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine:loader Searching for Query Engine Library in node_modules/.prisma/client
prisma:client:libraryEngine:loader loadEngine using node_modules/.prisma/client/libquery_engine-darwin.dylib.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
prisma.container.findFirstOrThrow({
    where: { label: 'root', parentId: null },
});
```

## Schema
```prisma
model Container {
  id                    String                 @id @default(dbgenerated("xid()")) @db.Char(20)
  createdAt             DateTime               @default(now())
  label                 String?
  parent                Container?             @relation("ContainerToContainer", fields: [parentId], references: [id], onDelete: Cascade)
  parentId              String?                @db.Char(20)
  path                  Unsupported("ltree")?  @unique
  childContainers       Container[]            @relation("ContainerToContainer")
}
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by jfemia** [comment]
Also seeing this error message when running `prisma generate` while trying to update to 4.13. Schema contains `Unsupported("tstzrange")`

```
Prisma schema loaded from prisma/schema.prisma
Oops, an unexpected error occurred!
RuntimeError: panicked at 'internal error: entered unreachable code: No unsupported field should reach that path', query-engine/schema-builder/src/input_types/mod.rs:28:40
```

Node v16.18
darwin-arm64
Postgresql

**Comment by janpio** [comment]
Can you shared your schema @jfemia? When I used the schema above and run `prisma generate` everything works fine.

**Comment by janpio** [comment]
But I can confirm this when running the code from above:

```
PS C:\Users\Jan\Documents\throwaway\18517> node .\script.js
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: No unsupported field should reach that path', query-engine\connectors\sql-query-connector\src\model_extensions\scalar_field.rs:70:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PrismaClientRustPanicError: 
Invalid `prisma.container.findFirstOrThrow()` invocation in
C:\Users\Jan\Documents\throwaway\18517\script.js:7:28

  4 
  5 // A `main` function so that we can use async/await
  6 async function main() {
→ 7     await prisma.container.findFirstOrThrow(
internal error: entered unreachable code: No unsupported field should reach that path

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issue...hat+path&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at pn.handleRequestError (C:\Users\Jan\Documents\throwaway\18517\node_modules\@prisma\client\runtime\library.js:176:6802)
    at pn.handleAndLogRequestError (C:\Users\Jan\Documents\throwaway\18517\node_modules\@prisma\client\runtime\library.js:176:5907)
    at pn.request (C:\Users\Jan\Documents\throwaway\18517\node_modules\@prisma\client\runtime\library.js:176:5786)
    at async t._request (C:\Users\Jan\Documents\throwaway\18517\node_modules\@prisma\client\runtime\library.js:179:10484)
    at async C:\Users\Jan\Documents\throwaway\18517\node_modules\@prisma\client\runtime\library.js:164:6641
    at async main (C:\Users\Jan\Documents\throwaway\18517\script.js:7:5) {
  clientVersion: '4.13.0'
}
```

**Comment by Medvedscak** [comment]
Seeing the same issue starting from 4.11.0 (checked on 4.11, 4.12, 4.13). I'm using the unsupported field for storing postgis points (postgres): Unsupported("geometry(Point, 4326)"). It looks like something has happened to the unsupported types in v4.11.0
