### ISSUE TITLE
Improve downloading of binaries in postinstall

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1855]
Right now there are two things of the download of the binaries during postinstall that could be improved:

1. a failing download in the postinstall gives quite ugly output:

```
C:\Users\Jan\Documents\throwaway\1509  (1509@1.0.0)
λ npm install prisma2@alpha

> prisma2@2.0.0-alpha.917 install C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2
> node download-build/index.js

> Downloading Prisma engines for windows [                    ] 0%Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/migration-engine.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 1,
  retriesLeft: 1
}
Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/introspection-engine.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 1,
  retriesLeft: 1
}
Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/prisma.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 1,
  retriesLeft: 1
}
Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/prisma.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 2,
  retriesLeft: 0
}
Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/migration-engine.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 2,
  retriesLeft: 0
}
Error: Bad Request https://binaries.prisma.sh/master/4ff8379527ec7797e7bb5b55d374f82f5812a6f9/windows/introspection-engine.exe.gz
    at o.default.retries (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:69059)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async RetryOperation._fn (C:\Users\Jan\Documents\throwaway\1509\node_modules\prisma2\download-build\index.js:1:226069) {
  attemptNumber: 2,
  retriesLeft: 0
}
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN 1509@1.0.0 No description
npm WARN 1509@1.0.0 No repository field.

+ prisma2@2.0.0-alpha.917
added 1 package from 1 contributor and audited 1 package in 3.416s
found 0 vulnerabilities
```

2. Each download is only tried twice. With a bad connection, that might not be enough - and 2 is also a strange number. 3 or 5 tries could make more sense.

**Comment by pantharshit00** [comment]
I think this is solved. We don't have the ugly error anymore and we retry again on startup.
