### ISSUE TITLE
jsonProtocol: The `select` statement for type XXX needs at least one truthy value.

### ISSUE THREAD

**Issue by dfilipidisz** [prisma/prisma#18598]
### Bug description

Getting the error in the title on a `_count` query with the `jsonProtocol` preview feature.

When I'm not using the `jsonProtocol` feature, the error is not present.

### How to reproduce

I've added the sample `schema.prisma` and code in later section. 

Running the following query:
```
const res = await prisma.bar.findMany({
    select: {
      bar_id: true,
      foo: {
        select: {
          _count: true,
        },
      },
    },
  });
```

Yields the following error:
```
PrismaClientValidationError: 
Invalid `prisma.bar.findMany()` invocation in
/...redacted_path/index.ts:7:32

  4 
  5 async function main() {
  6   await prisma.$connect();
→ 7   const res = await prisma.bar.findMany({
        select: {
          bar_id: true,
          foo: {
            select: {
              _count: true
            }
          }
        }
      })

The `select` statement for type FooCountOutputType needs at least one truthy value.
    at throwValidationException (...redacted_path/node_modules/@prisma/client/runtime/library.js:167:1432)
    at fn.handleRequestError (/...redacted_path/node_modules/@prisma/client/runtime/library.js:174:6217)
    at fn.handleAndLogRequestError (/...redacted_path/node_modules/@prisma/client/runtime/library.js:174:5907)
    at fn.request (/...redacted_path/node_modules/@prisma/client/runtime/library.js:174:5786)
    at async t._request (/...redacted_path/node_modules/@prisma/client/runtime/library.js:177:10477)
    at async main (/...redacted_path/index.ts:12:15)
```

### Expected behavior

The `select: {_count: true}` to return proper value.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["jsonProtocol"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Foo {
  foo_id Int @id @default(autoincrement())

  bar    Bar[] @relation("FooBars")
  bar_id Int[]
}

model Bar {
  bar_id Int @id @default(autoincrement())

  foo    Foo @relation("FooBars", fields: [bar_id], references: [foo_id])
  foo_id Int
}

```

```ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient({ log: ['query', 'info', 'warn'] });

async function main() {
  await prisma.$connect();
  const res = await prisma.bar.findMany({
    select: {
      bar_id: true,
      foo: {
        select: {
          _count: true,
        },
      },
    },
  });
  console.log(JSON.stringify(res, null, 2));
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });

```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v18.12.0

### Prisma Version

```
prisma                  : 4.12.0
@prisma/client          : 4.12.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at node_modules/@prisma/engines/migration-engine-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.12.0-67.659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Default Engines Hash    : 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Studio                  : 0.483.0
Preview Features        : jsonProtocol
```

**Comment by SevInf** [comment]
Thanks for the great report @dfilipidisz, can confirm the error on 4.12.0.
Internal note: protocol request issued is:

```json
{
  "modelName": "Bar",
  "action": "findMany",
  "query": {
    "arguments": {},
    "selection": {
      "bar_id": true,
      "foo": {
        "arguments": {},
        "selection": {
          "_count": true
        }
      }
    }
  }
}

```

where GraphQL query for the same request is:

```graphql
query {
  findManyBar {
    bar_id
    foo {
      _count {
        bar
      }
    }
  }
}
```

Not 100% sure GraphQL one is correct either - and if it is, not sure the transform could be done on the client side.

**Comment by SevInf** [comment]
Workaround until fix is released: explicit sub-selection on `_count`. For example from this post, that would be:

```ts
const res = await prisma.bar.findMany({
    select: {
      bar_id: true,
      foo: {
        select: {
          _count: { bar: true },
        },
      },
    },
  });
```

**Comment by SevInf** [comment]
@dfilipidisz  the fix will be released in `4.13.0` version next week.
If you want to try it out before that, you can install `4.13.0-dev.31` snapshot version. Let me know if it helps and thanks a lot for reproduction again.

**Comment by PeerRich** [comment]
excited for this!

**Comment by dfilipidisz** [comment]
@SevInf Thanks for letting me know! I've tried `jsonProtocol` with `4.13.0-dev.31` and indeed the issue is gone :) Thanks!
