### ISSUE TITLE
Other side closed/ECONNREFUSED 

### ISSUE THREAD

**Issue by roxxel** [prisma/prisma#18596]
### Bug description

I am using prisma with nextjs api, strange behavior - it only happens on the first request, then the error does not occur, but also if there is no activity with the database for a period of time, it happens again.

```
prisma:query SELECT COUNT(*) FROM (SELECT "public"."Item"."id" FROM "public"."Item" WHERE "public"."Item"."usedByHero" = $1 OFFSET $2) AS "sub"
error - PrismaClientKnownRequestError: 
Invalid `prisma.item.findMany()` invocation:


connect ECONNREFUSED 127.0.0.1:42801
    at sa.handleRequestError (/home/ubuntu/nebula/node_modules/@prisma/client/runtime/binary.js:232:6479)
    at sa.handleAndLogRequestError (/home/ubuntu/nebula/node_modules/@prisma/client/runtime/binary.js:232:5908)
    at sa.request (/home/ubuntu/nebula/node_modules/@prisma/client/runtime/binary.js:232:5787)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t._request (/home/ubuntu/nebula/node_modules/@prisma/client/runtime/binary.js:235:10493)
    at async handle (webpack-internal:///(api)/./src/pages/api/skins/index.ts:32:18) {
  code: 'ECONNREFUSED',
  clientVersion: '4.12.0',
  meta: undefined,
  page: '/api/skins'
}
error - PrismaClientKnownRequestError: 
Invalid `prisma.item.findMany()` invocation:


other side closed
    at sa.handleRequestError (/home/ubuntu/nebula/node_modules/@prisma/client/runtime/binary.js:232:6479)
    at sa.handleAndLogRequestError (/home/ubuntu/nebula/node_modules/@prisma/client/runtime/binary.js:232:5908)
    at sa.request (/home/ubuntu/nebula/node_modules/@prisma/client/runtime/binary.js:232:5787)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t._request (/home/ubuntu/nebula/node_modules/@prisma/client/runtime/binary.js:235:10493)
    at async handle (webpack-internal:///(api)/./src/pages/api/skins/slots.ts:15:18) {
  code: 'UND_ERR_SOCKET',
  clientVersion: '4.12.0',
  meta: undefined,
  page: '/api/skins/slots'
}
```

### How to reproduce

No idea

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  engineType = "binary"
}

datasource db {
  provider = "postgres"
  url = env("DATABASE_URL")
}

model Admin {
  id Int @id @default(autoincrement())
  user_id String
}

model Item {
  id Int @id @default(autoincrement())
  name String
  itemSlot String
  usedByHero String
  rarity String
  fileId String
  imageId String
  inventories Inventory[]
}

model Inventory {
  id Int @id @default(autoincrement())
  sub String
  hero String
  item Item @relation(fields: [itemId], references: [id])
  itemId Int
  slot String
}
```
```ts
// Add your code using Prisma Client
// Any prisma database method
```

### Environment & setup

- OS: Ubuntu
- Database: PostgreSQL
- Node.js version: v18.14.2

### Prisma Version

```
4.12.0
```

**Comment by roxxel** [comment]
I experience segmentation fault when I use library, although this only happens on Ubuntu, when I develop on Windows everything's normal

**Comment by roxxel** [comment]
Bump :)

**Comment by janpio** [comment]
Please don't do that. It jsut costs me half a minute to click the notification and now write this message, and will not lead to us being able to address this any sooner.

**Comment by SevInf** [comment]
Hey @roxxel  ,

Did you get a chance to have a look at my collegues comment? It'd be helpful for us to move your issue forward.

Without further information, we'll have to close this issue. Thank you 🙏

**Comment by roxxel** [comment]
> Hey @roxxel ,
> 
> Did you get a chance to have a look at my collegues comment? It'd be helpful for us to move your issue forward.
> 
> Without further information, we'll have to close this issue. Thank you 🙏

The server was running on ARM processor, my guess is that some underlying executable was failing to run on ARM (Ampere). Maybe this will help

**Comment by aqrln** [comment]
> > Hey @roxxel ,
> > Did you get a chance to have a look at my collegues comment? It'd be helpful for us to move your issue forward.
> > Without further information, we'll have to close this issue. Thank you 🙏
> 
> The server was running on ARM processor, my guess is that some underlying executable was failing to run on ARM (Ampere). Maybe this will help.
> 
> UPD: This was the behavior when using `library` engineType. Can't give any clues on `binary` though

From the sound of it, should've been fixed in 5.3.0. I'll go ahead and close this issue, please reopen if you still run into this problem.
