### ISSUE TITLE
Fail to build Prisma with nuxt3 for Cloudflare Workers (via Wrangler)

### ISSUE THREAD

**Issue by razbakov** [prisma/prisma#18593]
### Bug description

`process.stderr.fd` is not available in cloudflare workers context, which is used in debug-js/debug

Might be related:
- https://github.com/debug-js/debug/issues/511
- https://github.com/prisma/prisma/issues/1856
- https://github.com/prisma/prisma/issues/10605

### How to reproduce

1. Setup prisma with nuxt3, I used https://sidebase.io/sidebase/welcome/stacks#merino
2. Run `NITRO_PRESET=cloudflare yarn build` 
3. Run `npx wrangler dev .output/server/index.mjs --site .output/public --local` (see https://nitro.unjs.io/deploy/providers/cloudflare)

**Starting a local server log:**
```
[mf:err] return "colors" in i.inspectOpts ? Boolean(i.inspectOpts.colors) : l.isatty(process.stderr.fd);

TypeError: Cannot read properties of undefined (reading 'fd')
    at Function.useColors (node_modules/@prisma/client/runtime/index.js:2639:112)
    at default (node_modules/@prisma/client/runtime/index.js:2243:41)
    at src_default (node_modules/@prisma/client/runtime/index.js:19943:43)
    at decompressFromBase64 (node_modules/@prisma/client/runtime/index.js:20021:14)
    at node_modules/@prisma/client/runtime/index.js:33263:38
    at .nuxt/dist/server/_nuxt/error-500.b19bab8c.js:68:72
    ...
```

**Build log on Cloudflare:**

```
Error: Failed to publish your Function. Got error: Uncaught TypeError: Cannot read properties of undefined (reading 'fd')
  at ... in useColors
  at ... in createDebug
  at ... in debugCall
```

### Prisma information

```prisma
// unrelevant
```

```ts
export default eventHandler((event) => {
  if (!prisma) {
    prisma = new PrismaClient({ errorFormat: 'minimal' })
  }
  event.context.prisma = prisma
})
```

### Environment & setup

- Operating System:  Darwin, macOS 13.3, Apple M1 Pro
- Database: PostgreSQL
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `build`, `typescript`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.5`, `@huntersofbook/naive-ui-nuxt@0.5.1`
- Build Modules:    `-`

### Prisma Version

```
4.9.0
```

**Comment by razbakov** [comment]
I updated to prisma 4.12.0 and now I am getting this error:

```
[mf:err] var Ad = (0, go.promisify)(Ha.default.readFile), Sd = (0, go.promisify)(Ja.default.exec), we = U("prisma:get-platform"), Pd = ["1.0.x", "1.1.x", "3.0.x"];

TypeError: Cannot read properties of undefined (reading 'exec')
    at node_modules/@prisma/client/runtime/library.js:18:11211
    at .nuxt/dist/server/_nuxt/error-500.b19bab8c.js:68:72
```

**Comment by razbakov** [comment]
I switched to `@prisma/client/edge`

Now I have this error:

```
[mf:err] TypeError: Cannot convert object to primitive value
    at /functions/[[path]].js:1:779211
    at SourceTextModule.evaluate (node:internal/vm/module:224:23)
```

**Comment by janpio** [comment]
Not yet. Can someone provide a repository with a reproduction of this we can easily deploy to understand what is going on?

**Comment by kleinpetr** [comment]
same here. also do you use connection pooling with `directUrl` for the edge?

**Comment by kleinpetr** [comment]
is there any workaround?

**Comment by TMBL-DEV** [comment]
looks like you have to use prisma edge client. But That just gives me personally a bigger headache.
Because i can't use that on my local dev environment because its made for the edge. 

Hopefully there comes a better solution for this.

**Comment by aqrln** [comment]
> Because i can't use that on my local dev environment because its made for the edge.

To clarify, do you mean that you can't connect to a dev database on your local machine or is there something else that makes using the edge client in your local dev environment problematic for you? The edge client itself runs fine in Node.js FWIW.

**Comment by TMBL-DEV** [comment]
the edge client cannot connect to my local database because you need a prisma data proxy for the edge client. And also the edge client still dies for me in production.

https://www.prisma.io/docs/data-platform/data-proxy

**Comment by millsp** [comment]
Prisma can currently only be deployed to Cloudflare Workers via `@prisma/client/edge`, if you see any error with `library` it means that you are likely trying to deploy `@prisma/client`, which will prevent any deployment to a the Workers or Vercel Edge platforms.

**Comment by millsp** [comment]
@razbakov could you please give us more info about your second [error](https://github.com/prisma/prisma/issues/18593#issuecomment-1494097325)? How can we reproduce it?

**Comment by razbakov** [comment]
@millsp same as described in the issue, but with `@prisma/client/edge`

**Comment by razbakov** [comment]
@janpio what happens if you switch to `@prisma/client/edge`?

**Comment by janpio** [comment]
To test the Prisma Client for Data Proxy that should work on Cloudflare Workers:

- Edit `my-sidebase-project\server\middleware\0.prisma.ts` to import `@prisma/client/edge` instead.
- `yarn build && npx wrangler dev .output/server/index.mjs --site .output/public --local`
- The previous error goes away
- On opening the browser with the project, an error is thrown:
	```
	[nuxt] [request error] [unhandled] [500] @prisma/client/edge did not initialize yet. Please run "prisma generate --data-proxy" and try to import it again.
	```
	
So instead:
- `npx prisma generate --data-proxy`
- `yarn build && npx wrangler dev .output/server/index.mjs --site .output/public --local`
- Opening in browser gives this:
	```
	[nuxt] [request error] [unhandled] [500] Datasource "db" references an environment variable "DATABASE_URL" that is not set
	```
	
So instead:
- Replace `env("DATABASE_URL")` in `schema.prisma` with `prisma://foo?api_key=123`, also change `provider = "sqlite"` to `provider = "postgresql"` to actually be able to use DataProxy
- `npx prisma generate --data-proxy && yarn build && npx wrangler dev .output/server/index.mjs --site .output/public --local`
- And then everything works as expected:
	![Uploading image.png…]()
- On `See example` it opens `/prisma` that indeed tries to connect to `foo` and fails. It seems to me that Prisma Client for Data Proxy is now working correctly.

Am I missing something @razbakov?

**Comment by janpio** [comment]
Ping @razbakov - can you help me understand what I am observing?

**Comment by Jolg42** [comment]
Closing due to inactivity, please comment here if you are still facing this when using a recent version of Prisma.
Also, please check the previous question.

**Comment by jfdelarosa** [comment]
I encountered the same issue when deploying a Nuxt 3 app to NuxtHub. I resolved it by replacing all instances of `@prisma/client` with `@prisma/client/edge`, and also applied [this workaround](https://github.com/prisma/prisma/issues/12504#issuecomment-2403271916).
