### ISSUE TITLE
Make type declarations of Prisma client compatible with Deno

### ISSUE THREAD

**Issue by Frando** [prisma/prisma#18663]
### Bug description

I'm investigating using Prisma with Deno (without Data Proxy).
Based on [this example](https://github.com/prisma/prisma/issues/2452#issuecomment-1491748012) and others in that issue I am using the following code

`prisma.ts`
```typescript
// @deno-types="./generated/prisma-client/index.d.ts"
import * as _prisma from './generated/prisma-client/index.js'
import { createRequire } from 'node:module'

type PrismaTypes = typeof _prisma

const require = createRequire(import.meta.url)
const prisma: PrismaTypes = require('./generated/prisma-client')

export class PrismaClient extends prisma.PrismaClient {}
export type Prisma = PrismaTypes['Prisma']
```
and then, using `import { PrismaClient } from './prisma.ts'`. This works fine, yay!

However, type checking is broken. To fix it I had to make (hack) the following changes in the generated client:

* In `index.d.ts`, replace line 6
  `import * as runtime from './runtime/library';`
  with
  `import * as runtime from './runtime/library.d.ts';`
* In `index.d.ts` add this line at the top:
  `import type { Buffer } from 'node:buffer'`
* In `runtime/library.d.ts` replace
  `export * from "./index"`
  with
  `export * from "./index.d.ts"`

These changes do not seem to break anything in a regular Node.js+TypeScript setup. Therefore I am proposing to upstream these changes into the code generation.

### How to reproduce

* Use a Prisma schema like 
```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["deno"]
  output = "./generated/prisma-client"
}

model Block {
  id  Int    @id @default(autoincrement())
  name String
  bytes Bytes
}
```
* Save the `prisma.ts` from above
* Create a file `test.ts` with
```
import { PrismaClient } from './src/prisma.ts'
import { Buffer } from 'node:buffer'

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: 'file:data/test.sqlite',
    },
  },
})

const res = await prisma.block.create({
  data: {
    name: 'foo',
    bytes: Buffer.from(new Uint8Array([0, 1, 2])),
  },
})
```
* See how `deno run -A --check test.ts` fails with errors
* Make the changes as described above, and see how now it works without errors

### Prisma information

(see above)

### Environment & setup

- OS: Linux
- Database: Sqlite
- Deno `1.32.3`

### Prisma Version

```
4.12.0
```

**Comment by filipesmedeiros** [comment]
I'm also interested in this. Thank you for the help :)

**Comment by amm297** [comment]
Any progress with this?

I have replicated what you did, I try to create a supabase project that uses prisma but when I try to import it to the function s it breaks

```
import { createRequire } from 'node:module'

// @deno-types="prisma-client/index.d.ts"
import * as _prisma from 'prisma-client/index.js'

const require = createRequire(import.meta.url)
const { PrismaClient }: typeof _prisma = require('prisma-client/index.js')

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.NEXT_PUBLIC_DATABASE_URL,
    },
  },
})

export default prisma
```

this is my import_map.json

{
  "imports": {
    "fmt/": "https://deno.land/std@0.204.0/fmt/",
    "std/server": "https://deno.land/std@0.204.0/http/server.ts",
    "load": "https://deno.land/std@0.204.0/dotenv/mod.ts",
    "prisma-client/": "../../generated/client/prisma/",
    "shared/": "/_shared/"
  }
}

with that `node:module` I get this error:

thread 'sb-iso-65c9302a-08c0-4e9f-b357-ba7938b85a2f' panicked at 'required type alloc::sync::Arc<dyn sb_node::NpmResolver> is not present in GothamState container', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.199.0/gotham_state.rs:82:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted
error running container: exit 134

whith out it using a prvious version `import { createRequire } from 'https://deno.land/std@0.177.0/node/module.ts'`

It says `Cannot find the module`

Any Idea why?

**Comment by aarbi** [comment]
tried this with:
- deno 1.38.1
- prisma 5.5.2

```
import { type PrismaClient } from "./src/generated/client/index.d.ts";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const Prisma = require("./src/generated/client/index.js");

try {
  const prisma: PrismaClient = new Prisma.PrismaClient();
  await prisma.user.create({
    data: {
      email: "test3@test.com",
    },
  });

  console.log(await prisma.user.findMany());
} catch (e) {
  console.log(e);
}

```

Getting the types separately this way because of the use of require, since typing would be inferred automatically if we're using import in all the places.
Hope this helps

**Comment by xXACCEXx** [comment]
I'm also struggling to get a request made. 

I've followed the same setup you outlined above. Which really only helps with types. But made no difference to the runtime errors.

No one has called out what errors they are getting atm. So I figure I'll put mine here for a reference point. Just give the ol' 👎 if your errors don't match mine.

Also, would love some links to documentation on how to solve the error I'm getting, which looks as though the configuration is being ignored and forcing a prisma hosted db config.

env file defines the DB connection string
```bash
DATABASE_URL="postgresql://<usr>:<pas>@<hos>:<por>/<db>?etc"
```

the schema file uses that env var
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

So does the prisma client.
```ts
export const prisma = new PrismaClient({
	datasources: {
		db: {
			url: Deno.env.get('DATABASE_URL')
		}
	}
})
```

But the error says the connection string schema is wrong? Confused.
```
PrismaClientKnownRequestError: 
Invalid `prisma.user.findUniqueOrThrow()` invocation:

Error validating datasource `db`: the URL must start with the protocol `prisma://`
    at In.handleRequestError (file:///C:/Users/ME/projects/fresh/prisma/client/runtime/library.js:122:6854)
    at In.handleAndLogRequestError (file:///C:/Users/ME/projects/fresh/prisma/client/runtime/library.js:122:6188)
    at In.request (file:///C:/Users/ME/projects/fresh/prisma/client/runtime/library.js:122:5896)
    at Object.runMicrotasks (ext:core/01_core.js:642:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:39:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:48:3)
    at eventLoopTick (ext:core/01_core.js:175:21)
    at async l (file:///C:/Users/ME/projects/fresh/prisma/client/runtime/library.js:127:11167)
    at async file:///C:/Users/ME/projects/fresh/prisma/client/runtime/library.js:31:551
    at async POST (file:///C:/Users/ME/projects/fresh/routes/api/search-invite.ts:15:18) {
  name: "PrismaClientKnownRequestError",
  code: "P6001",
  clientVersion: "5.13.0",
  meta: { modelName: "User" }
  ```
  
  I've checked the details for the error code P6001, which really didn't add any context at all.
https://www.prisma.io/docs/orm/reference/error-reference#p6001-invaliddatasource

Additionally, running `deno run -A npm:prisma db push` works perfectly. so 🤷

**Comment by janpio** [comment]
@xXACCEXx I think you are probably importing Prisma Client not quite right - can you add that bit to your code snippet? See above what @aarbi did - that might work to jump into the correct code path.

**Comment by xXACCEXx** [comment]
Hey, sorry it took so long, I had a whole mess happen while moving from windows to WSL ubuntu.

I'm back to where I was having issues again. So, my goal is to have a single `prisma` client, for the whole app.
I generate the client into `./server/client` and I create a `./server/client.ts` where I want to export the `prisma` client instance.

Here's what that looked like, when I commented above.

```ts
// @deno-types="@/prisma/client/index.d.ts"
import * as _prisma from '@/prisma/client/index.js';
import { createRequire } from 'node:module';

type PrismaTypes = typeof _prisma;

const require = createRequire(import.meta.url);
const Prisma: PrismaTypes = require('./client/index');


export type Prisma = PrismaTypes;
export class PrismaClient extends Prisma.PrismaClient {}

export type { Group, Guest } from '@/prisma/client/index.d.ts'

export const prisma = new PrismaClient();
```

Here's the updated version based on @aarbi's version.

```ts
import { type PrismaClient } from "./client/index.d.ts";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const Prisma = require("./client/index.js");

export { type PrismaClient };
export const prisma: PrismaClient = new Prisma.PrismaClient();
```

This solves the type issues, but when using the `prisma.<type>.find` method, I still get this error:
```
PrismaClientKnownRequestError:
Invalid `prisma.guest.findUniqueOrThrow()` invocation:
Error validating datasource `db`: the URL must start with the protocol `prisma://`
```

This absolutely solves the issue here.
though I'm still not able to _use_ the client, as I get an error around the prisma protocal being wrong. But thats a different thing I supose.

**Comment by janpio** [comment]
Can you open a new issue and optimally provide a reproduction repository? We would love to investigate this further.

**Comment by xXACCEXx** [comment]
For now, I'm going to just make postgres queries directly. Crunch time and all.
When I have some space to breath I'll come back to this and help explore it, since DX will be pretty important for my project later.
