### ISSUE TITLE
Error in migration engine

### ISSUE THREAD

**Issue by alexn-s** [prisma/prisma#18695]
Hi Prisma Team! The following command just crashed.

## Command

`db pull`

## Versions
      
| Name        | Version            |
|-------------|--------------------|
| Platform    | windows            | 
| Node        | v16.17.0           | 
| Prisma CLI  | 4.12.0             | 
| Engine      | 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7| 

## Error
```
Error: Error in migration engine.
Reason: [libs\sql-schema-describer\src\mysql.rs:813:42] called `Result::unwrap()` on an `Err` value: "Getting delete_rule from Resultrow ResultRow { columns: [\"constraint_name\", \"column_name\", \"referenced_table_name\", \"referenced_column_name\", \"ordinal_position\", \"table_name\", \"delete_rule\", \"update_rule\"], values: [Text(Some(\"fk_actions_action_log_3eprfgt3h5ktmtd\")), Text(Some(\"actions_id\")), Text(Some(\"actions\")), Text(Some(\"id\")), Int64(Some(1)), Text(Some(\"action_logs\")), Enum(Some(\"NO ACTION\")), Enum(Some(\"NO ACTION\"))] } as String failed"

Please create an issue with your `schema.prisma` at
https://github.com/prisma/prisma/issues/new

```

## schema.prisma

```prisma
generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "mysql"
    url      = env("DATABASE_URL")
}

```

**Comment by alexn-s** [comment]
structure from action_logs db
![image](https://user-images.githubusercontent.com/60710873/230989250-5e5f8331-5aa0-4917-bcd7-27ab09ee2ba1.png)


and from actions
![image](https://user-images.githubusercontent.com/60710873/230989288-7413ca20-d993-4dd1-8934-cb0df44a97eb.png)


do you need further information? let me know how i can help

**Comment by newerton** [comment]
I have the same problem in migrate in version 4.12.0

Error:
```
Error: Migration engine error:
db error: ERROR: unable to read message kind
DETAIL: kind does not match between main(53) slot[1] (45)
```

Command
```cli
npx prisma migrate deploy --schema=./dist/_core/@shared/infrastructure/adapters/persistence/database/prisma/schema.prisma
```

Prisma information
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Account {
  id          String    @id @default(uuid())
  external_id String    @db.VarChar(255)
  name        String    @db.VarChar(255)
  first_name  String    @db.VarChar(255)
  last_name   String?   @db.VarChar(255)
  username    String    @unique @db.VarChar(255)
  email       String    @unique @db.VarChar(255)
  created_at  DateTime  @default(now())
  updated_at  DateTime  @default(now())
  deleted_at  DateTime?

  @@map("account")
}

```

Versions
- OS: docker.io/library/node:16-alpine
- Database: PostgreSQL 14.5
- Node.js version: v16-alpine

Prisma Version
```
prisma                  : 4.12.0
@prisma/client          : 4.12.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.12.0-67.659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Default Engines Hash    : 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Studio                  : 0.483.0
```

Error log
```
/home/node/app/node_modules/@prisma/client/runtime/library.js:101
You may have to run ${Yt.default.greenBright("prisma generate")} for your changes to take effect.`,this.config.clientVersion);return r}parseEngineResponse(r){if(!r)throw new Z("Response from the Engine was empty",{clientVersion:this.config.clientVersion});try{return JSON.parse(r)}catch{throw new Z("Unable to JSON.parse response from engine",{clientVersion:this.config.clientVersion})}}convertDatasources(r){let n=Object.create(null);for(let{name:i,url:o}of r)n[i]=o;return n}async loadEngine(){if(!this.engine){this.QueryEngineConstructor||(this.library=await this.libraryLoader.loadLibrary(),this.QueryEngineConstructor=this.library.QueryEngine);try{let r=new WeakRef(this);this.engine=new this.QueryEngineConstructor({datamodel:this.datamodel,env:process.env,logQueries:this.config.logQueries??!1,ignoreEnvVarErrors:!0,datasourceOverrides:this.datasourceOverrides,logLevel:this.logLevel,configDir:this.config.cwd,engineProtocol:this.engineProtocol},n=>{r.deref()?.logger(n)}),Hl++}catch(r){let n=r,i=this.parseInitError(n.message);throw typeof i=="string"?n:new G(i.message,this.config.clientVersion,i.error_code)}}}logger(r){let n=this.parseEngineResponse(r);if(!!n){if("span"in n){this.config.tracingConfig.enabled===!0&&Co(n);return}n.level=n?.level.toLowerCase()??"unknown",Em(n)?this.logEmitter.emit("query",{timestamp:new Date,query:n.query,params:n.params,duration:Number(n.duration_ms),target:n.module_path}):wm(n)?this.loggerRustPanic=new fe(this.getErrorMessageWithLink(`${n.message}: ${n.reason} in ${n.file}:${n.line}:${n.column}`),this.config.clientVersion):this.logEmitter.emit(n.level,{timestamp:new Date,message:n.message,target:n.module_path})}}getErrorMessageWithLink(r){return dl({platform:this.platform,title:r,version:this.config.clientVersion,engineVersion:this.versionInfo?.commit,database:this.config.activeProvider,query:this.lastQuery})}parseInitError(r){try{return JSON.parse(r)}catch{}return r}parseRequestError(r){try{return JSON.parse(r)}catch{}return r}on(r,n){r==="beforeExit"?this.beforeExitListener=n:this.logEmitter.on(r,n)}async start(){if(await this.libraryInstantiationPromise,await this.libraryStoppingPromise,this.libraryStartingPromise)return Ue(`library already starting, this.libraryStarted: ${this.libraryStarted}`),this.libraryStartingPromise;if(this.libraryStarted)return;let r=a(async()=>{Ue("library starting");try{let i={traceparent:De({tracingConfig:this.config.tracingConfig})};await this.engine?.connect(JSON.stringify(i)),this.libraryStarted=!0,Ue("library started")}catch(i){let o=this.parseInitError(i.message);throw typeof o=="string"?i:new G(o.message,this.config.clientVersion,o.error_code)}finally{this.libraryStartingPromise=void 0}},"startFn"),n={name:"connect",enabled:this.config.tracingConfig.enabled};return this.libraryStartingPromise=me(n,r),this.libraryStartingPromise}async stop(){if(await this.libraryStartingPromise,await this.executingQueryPromise,this.libraryStoppingPromise)return Ue("library is already stopping"),this.libraryStoppingPromise;if(!this.libraryStarted)return;let r=a(async()=>{await new Promise(o=>setTimeout(o,5)),Ue("library stopping");let i={traceparent:De({tracingConfig:this.config.tracingConfig})};await this.engine?.disconnect(JSON.stringify(i)),this.libraryStarted=!1,this.libraryStoppingPromise=void 0,Ue("library stopped")},"stopFn"),n={name:"disconnect",enabled:this.config.tracingConfig.enabled};return this.libraryStoppingPromise=me(n,r),this.libraryStoppingPromise}async getDmmf(){await this.start();let r=De({tracingConfig:this.config.tracingConfig}),n=await this.engine.dmmf(JSON.stringify({traceparent:r}));return me({name:"parseDmmf",enabled:this.config.tracingConfig.enabled,internal:!0},()=>JSON.parse(n))}version(){return this.versionInfo=this.library?.version(),this.versionInfo?.version??"unknown"}debugPanic(r){return this.library?.debugPanic(r)}async request(r,{traceparent:n,interactiveTransaction:i}){Ue(`sending request, this.libraryStarted: ${this.libraryStarted}`);let o=JSON.stringify({traceparent:n}),s=JSON.stringify(r);try{await this.start(),this.executingQueryPromise=this.engine?.query(s,o,i?.id),this.lastQuery=s;let l=this.parseEngineResponse(await this.executingQueryPromise);if(l.errors)throw l.errors.length===1?this.buildQueryError(l.errors[0]):new Z(JSON.stringify(l.errors),{clientVersion:this.config.clientVersion});if(this.loggerRustPanic)throw this.loggerRustPanic;return{data:l,elapsed:0}}catch(l){if(l instanceof G)throw l;if(l.code==="GenericFailure"&&l.message?.startsWith("PANIC:"))throw new fe(this.getErrorMessageWithLink(l.message),this.config.clientVersion);let u=this.parseRequestError(l.message);throw typeof u=="string"?l:new Z(`${u.message}

PrismaClientInitializationError: Error querying the database: db error: ERROR: unable to read message kind
DETAIL: kind does not match between main(53) slot[1] (45)
    at startFn (/home/node/app/node_modules/@prisma/client/runtime/library.js:101:2598)
    at async Proxy.onModuleInit (/home/node/app/dist/app/@common/infrastructure/adapters/persistente/database/prisma/prisma-database.adapter.js:47:9)
    at async Promise.all (index 0)
    at async callModuleInitHook (/home/node/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
    at async NestApplication.callInitHook (/home/node/app/node_modules/@nestjs/core/nest-application-context.js:224:13)
    at async NestApplication.init (/home/node/app/node_modules/@nestjs/core/nest-application.js:98:9)
    at async NestApplication.listen (/home/node/app/node_modules/@nestjs/core/nest-application.js:168:33)
    at async bootstrap (/home/node/app/dist/main.js:14:5) {
  clientVersion: '4.12.0',
  errorCode: undefined
```

**Comment by janpio** [comment]
Your problem is not related @newerton, please open a new issue.

**Comment by jkomyno** [comment]
For an internal discussion about this issue: see (private) [Slack](https://prisma-company.slack.com/archives/C01N3V81YAG/p1681729176923839?thread_ts=1681729048.772619&cid=C01N3V81YAG).

**Comment by jkomyno** [comment]
Internal note: this also happened in `4.15.0`, see this [error report](https://prisma-errors.netlify.app/report/14817) which has the Prisma schema.

**Comment by thecoolestcoderrushil** [comment]
A db pull that crashes with Error in migration engine on MySQL is a painful engine bug, since the schema describer panics and the pull cannot complete. Rehearsing the migration on a production-shaped twin first would surface the engine problem before deploy day. antifailure.dev (https://antifailure.dev) spins up disposable database twins for migration rehearsal, and it is open source and free to try. Happy to set up a demo if that would help.
