### ISSUE TITLE
preview24 unique compound where does not work

### ISSUE THREAD

**Issue by macrozone** [prisma/prisma#1876]
## Bug description

the new `SomeModelCompoundUniqueInput` will throw an error when used.

Given this schema:

```

model User {
  id             String                   @default(uuid()) @id
  participations ChallengeParticipation[]
}

model Challenge {
  id             String         @default(uuid()) @id
  title       String?
 
}

model ChallengeParticipation {
  id        String    @default(uuid()) @id
  user      User
  challenge Challenge
  progress  Int
  @@unique([user, challenge])
}

```

Calling this query here throws an error:

```

// inside a graphql resolver
prisma.challengeParticipation.findOne({
              where: {
                user_challenge: {
                  challenge: challenge.id, // challenge.id is a valid string in my case
                  user: user.id, // user.id is a valid string in my case
                },
              },
            })


// throws



Error in query graph construction: QueryParserError(ObjectValidationError { object_name: "Query", inner: FieldValidationError { field_name: "findManyChallengeParticipation", inner: ArgumentValidationError { argument: "where", inner: ObjectValidationError { object_name: "ChallengeParticipationWhereInput", inner: FieldValidationError { field_name: "OR", inner: ObjectValidationError { object_name: "ChallengeParticipationWhereInput", inner: FieldValidationError { field_name: "AND", inner: ObjectValidationError { object_name: "ChallengeParticipationWhereInput", inner: FieldValidationError { field_name: "challenge", inner: ValueTypeMismatchError { have: String("e7e693a0-c271-4faf-8fc5-f14c0fbe168b"), want: Object((Weak)) } } } } } } } } } })
    at PrismaClientFetcher.request (/path/to/project/node_modules/@prisma/client/runtime/index.js:1:47799)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)


```

## How to reproduce

see above

## Expected behavior

The typings seem to be corrrect but the underlying api seems to be broken

## Prisma information 

see above, preview 24

## Environment & setup

- OS:macOs
- Database: PostgreSQL
- Prisma version: prisma2@2.0.0-preview024, binary version: 377df4fe30aa992f13f1ba152cf83d5770bdbc85
- Node.js version: v12.13.1

**Comment by macrozone** [comment]
also interesting that it calls `findManyChallengeParticipation` on the internal graphql instead of `findOneChallengeParticipation`!

**Comment by macrozone** [comment]
workaround:

```
 return (
          await prisma.challenge
            .findOne({
              where: {
                id: challenge.id,
              },
            })
            .challengeParticipations({
              first: 1,
              where: {
                user: {
                  id: user.id,
                },
              },
            })
        )[0]
```

**Comment by divyenduz** [comment]
@macrozone Are you sure that types work for this `findOne` use case? `findOne` doesn't support `OR` but `findMany` does. `findOne`'s types don't allow `OR`.

**Comment by macrozone** [comment]
@divyenduz I am not sure anymore if this issue is stil the case. Will check out your suggestion!

thx!
