### ISSUE TITLE
Prisma not running on Namecheap Cpanel

### ISSUE THREAD

**Issue by ushashir** [prisma/prisma#18832]
### Bug description

I successfully installed Prisma on my Cpanel via ssh, but it isn't running migration, this is the error message that I am getting.
```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "test", schema "public" at "localhost:5432"

prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Error: Could not parse migration engine response: SyntaxError: Unexpected token / in JSON at position 0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: Debian (Linux Server)
- Database: PostgreSQL
- Node.js version: 14.21

### Prisma Version

```
prisma client4.13.0

```

**Comment by Sirjoseph94** [comment]
This seems to be more of your server issue than Prisma. Shared web hosting limits what you can install on their server.

**Comment by janpio** [comment]
What do you get when you run `prisma -v` instead of migrate?

**Comment by guyromb** [comment]
Any solution ? have the same when running `prisma generate`
`prisma -v` returns the same
```
> npx prisma -v
stderr:
npm WARN lifecycle The node binary used for scripts is /home/XXXX/nodevenv/api.voja.ai/14/bin/node but npm is using /opt/alt/alt-nodejs14/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
WebAssembly.Instance(): Out of memory: wasm memory
```

**Comment by insectula** [comment]
> Any solution ? have the same when running `prisma generate` `prisma -v` returns the same

I think this is cause cpanel andits console have limited memory.
I moved steo ahead as I logged in via ssh and ran `npx prisma generate`,
however `npx prisma db push` returns:
```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "my_db" at "localhost:3306"

Error: Could not parse migration engine response: SyntaxError: Unexpected token / in JSON at position 0
```
and `prisma -v`
```
Details: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.0.x.so.node)
    at loadLibrary (/home/username/nodevenv/site_name/14/lib/node_modules/prisma/build/index.js:92837:11)
    at getEngineVersion (/home/username/nodevenv/site_name/14/lib/node_modules/prisma/build/index.js:92850:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Command failed with exit code 1: /home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x --version
/home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)
/home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)
/home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)
    at makeError2 (/home/username/nodevenv/site_name/14/lib/node_modules/prisma/build/index.js:2172:18)
    at handlePromise2 (/home/username/nodevenv/site_name/14/lib/node_modules/prisma/build/index.js:2935:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getEngineVersion (/home/username/nodevenv/site_name/14/lib/node_modules/prisma/build/index.js:92853:24) {
  shortMessage: 'Command failed with exit code 1: /home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x --version',
  command: '/home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x --version',
  escapedCommand: '"/home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x" --version',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "/home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)\n" +
    "/home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)\n" +
    "/home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
prisma                  : 4.16.2
@prisma/client          : 4.16.2
Current platform        : debian-openssl-1.0.x
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at ../nodevenv/site_name/14/lib/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.0.x.so.node)
Migration Engine        : E_CANNOT_RESOLVE_VERSION (at ../nodevenv/site_name/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.0.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
```
The Namecheap hosting distro is LightSpeed, sort of debian deep cut.

**Comment by janpio** [comment]
> Details: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/username/nodevenv/site_name/14/lib/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.0.x.so.node)

This will be a blocker for using Prisma, as it is a requirement. Prisma will not work on a system without it.

**Comment by miguelff** [comment]
@ushashir We recently made changes to the way engines are compiled in different platforms. However, as noted by @janpio [above](https://github.com/prisma/prisma/issues/18832#issuecomment-1622601579),  you need a usable version of GLIBC (or musl) installed on your system. Is that the case? If so, please reopen the issue and comment.

**Comment by miguelff** [comment]
We have meanwhile opened an issue to address the error message when the platform is unsupported and guide better the user. See https://github.com/prisma/prisma/issues/18832
