### ISSUE TITLE
Cyclic type array causes Error [RangeError]: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by h0m3us3r** [prisma/prisma#18893]
### Bug description

A schema with a type similar to:
```
type TestType {
  name String
  refs    TestType[]
}
```
causes `Error [RangeError]: Maximum call stack size exceeded` on db reads.

```
error - Error [RangeError]: Maximum call stack size exceeded
    at .../node_modules/@prisma/client/runtime/library.js:163:1700
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>)
    at selectionToFields (.../node_modules/@prisma/client/runtime/library.js:163:1192)
    at .../node_modules/@prisma/client/runtime/library.js:163:3469
    at Array.reduce (<anonymous>) {
  digest: undefined
}
```

### How to reproduce

See schema

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
}

type TestType {
  name String
  refs    TestType[]
}

model TestModel {
  id       String    @id @default(auto()) @map("_id") @db.ObjectId
  test     TestType?
}
```

```ts
await prisma.TestModel.findFirst()
```

### Environment & setup

- OS: clear-linux-os
- Database: MongoDB
- Node.js version: v18.13.0

### Prisma Version

```
4.13.0
```

**Comment by h0m3us3r** [comment]
Just in case, the following works fine with standard `mongodb` driver:
```ts
import {MongoClient} from 'mongodb'

type TestType = {
    name: String
    refs?: TestType[]
}

type TestModel = {
    test?: TestType
}

const mongo = new MongoClient(...)
const database = mongo.db(...)
const collection = database.collection<TestModel>(...)

await collection.findOne()
```
