### ISSUE TITLE
Required 1-1-self-relations should be forbidden?

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#1895]
1-1 self relations that are required on both sides aren't usable in Prisma at the moment (or at least I couldn't figure out a way how to use them properly).

Assume you have this Prisma schema:

```prisma
model User {
  id          Int      @id @default(autoincrement())
  name        String?
  mentors     User     @relation("UserMentor")
  mentee      User     @relation("UserMentor")
}
```

The DB schema created by Migrate looks as follows:

```sql
CREATE TABLE "public"."User" (
    "id" SERIAL,
    "mentee" integer  NOT NULL ,
    "name" text   ,
    PRIMARY KEY ("id")
) 

CREATE UNIQUE INDEX "User_mentee" ON "public"."User"("mentee")

ALTER TABLE "public"."User" ADD FOREIGN KEY ("mentee")REFERENCES "public"."User"("id") ON DELETE CASCADE  ON UPDATE CASCADE
```

Now, using the generated Prisma Client API  it's not possible to create `User` records because the typings _require_ each `User` to have a `mentors` and a `mentee`. The only 
way I could find in the API to satisfy the typings is by connecting a `User` to itself in both relations, but this fails at runtime:

```ts
const user = await prisma.user.create({
  data: {
    name: 'Alice',
    mentee: {
      connect: {
          id:  1 
      }
    },
    mentors: {
      connect: {
        id: 1
      }
    }
  },
})
```

Aside from the fact that this seems operation seems nonsensical in the first place, the query engine throws this error when running the code:

```
(node:41582) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.user.create()` invocation in
/Users/nikolasburk/Desktop/exs/typescript/script/script.ts:47:58

Error in query graph construction: RelationViolation(RelationViolation { relation_name: "UserMentor", model_a_name: "User", model_b_name: "User" })
    at PrismaClientFetcher.request (/Users/nikolasburk/Desktop/exs/typescript/script/node_modules/@prisma/client/runtime/index.js:1:51323)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:41582) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:41582) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As far as I can tell, required self 1-1-relations should therefore be forbidden in the Prisma schema:

- VS Code should indicate an error with red squiggly lines
- Prisma Migrate should fail when a migration is being saved

**Comment by pantharshit00** [comment]
Schema with the new syntax change:
```prisma
model User {
  id          Int      @id @default(autoincrement())
  name        String?
  mentors     User     @relation("UserMentor")
  mentee      User     @relation("UserMentor", fields:[menteeId], references:[id])
  menteeId    Int
}
```

But I agree, we should not allow this as this pattern will not allow you to create a root node in the requried relations.
