### ISSUE TITLE
validator's type doesn't match typescript type

### ISSUE THREAD

**Issue by OrJDev** [prisma/prisma#18993]
### Bug description

Prisma's validator seems to throw an error even tho all required data was provided

```prisma
enum SearchVersion {
  versionOne
}

model Search {
  id         String   @id @default(cuid())
  searchedAt DateTime @default(now())
  asin      String @unique
  response String @db.Text
  chatResponse String @db.Text
  users       UserSearch[]    
  title String @db.VarChar(1000) @default("")
  stars Float @default(0)
  ratingCount Int
  reviewsCount Int
  img String?
  version SearchVersion @default(versionOne)
  summed String? @db.Text
}

model UserSearch {
  id        String   @id @default(cuid())
  userId    String
  searchId  String
  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  search    Search   @relation(fields: [searchId], references: [id], onDelete: Cascade)
  createdAt DateTime @default(now())
  count Int?
}
````

Having this prisma schema, and using it like:
```ts
  const { id: sId } = await ctx.prisma.search.upsert({
            where: {
              asin,
            },
            create: createData,
            update: createData,
          });

          console.log("got here");
          const tmp = await ctx.prisma.userSearch.upsert({
            where: {
              id: input.id,
            },
            create: {
              searchId: sId,
              userId: ctx.session.user.id,
              count: input.count ?? 1,
            },
            update: {
              count: input.count ?? 1,
            },
          });
```

I expect it to be working, instead i get:

```
PrismaClientValidationError: 
Invalid `prisma.userSearch.upsert()` invocation:

{
  where: {
?   id?: String
  },
  create: {
    searchId: 'clh0g09n10000d2ikmotm4hiu',
    userId: 'clgjil56k0000d26plt9mcizb',
    count: 5
  },
  update: {
    count: 5
  }
}

Argument where of type UserSearchWhereUniqueInput needs at least one argument. Available args are listed in green.

Note: Lines with ? are optional.

    at ti.validate (/Users/or/Desktop/deqa/geenie-rating/next/node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client/runtime/library.js:149:91)
    at Wr.createMessage (/Users/or/Desktop/deqa/geenie-rating/next/node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client/runtime/library.js:164:13655)
    at /Users/or/Desktop/deqa/geenie-rating/next/node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client/runtime/library.js:174:10933
    at runInChildSpan (/Users/or/Desktop/deqa/geenie-rating/next/node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client/runtime/library.js:70:25817)
    at t._executeRequest (/Users/or/Desktop/deqa/geenie-rating/next/node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client/runtime/library.js:174:10922) {
  clientVersion: '4.11.0'
}
```

### How to reproduce

The repo is currently private, lmk if you need access for it, but i provided code & prisma schema above that should throw this exact error.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  // NOTE: When using postgresql, mysql or sqlserver, uncomment the @db.Text annotations in model Account below
  // Further reading:
  // https://next-auth.js.org/adapters/prisma#create-the-prisma-schema
  // https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#string
  url      = env("DATABASE_URL")
  relationMode = "prisma"
}

enum UserRole {
  ADMIN
  USER
}

// Necessary for Next auth
model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String? @db.Text
  access_token      String?  @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?  @db.Text
  session_state     String?
  user              User    @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
  role          UserRole  @default(USER)
  createdAt     DateTime  @default(now())
  searches      UserSearch[]
  subscriptionId String? 
  sentEnterprise Boolean @default(false)
  sentEmail Boolean @default(false)
  sentWelcome Boolean @default(false)
  lastLogin DateTime? 
  subscription Subscription? @relation(fields: [subscriptionId], references: [id])
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}

model Question {
  id       String @id @default(cuid())
  question String @db.Text
  order Int @default(0)
  titles String? @db.Text 
}

enum SearchVersion {
  versionOne
}

model Search {
  id         String   @id @default(cuid())
  searchedAt DateTime @default(now())
  asin      String @unique
  response String @db.Text
  chatResponse String @db.Text
  users       UserSearch[]    
  title String @db.VarChar(1000) @default("")
  stars Float @default(0)
  ratingCount Int
  reviewsCount Int
  img String?
  version SearchVersion @default(versionOne)
  summed String? @db.Text
}

model UserSearch {
  id        String   @id @default(cuid())
  userId    String
  searchId  String
  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  search    Search   @relation(fields: [searchId], references: [id], onDelete: Cascade)
  createdAt DateTime @default(now())
  count Int?
}
model Subscription {
    id          String  @id @default(cuid())
    title String
    description String
    price Float?
    level Int @default(1)
    users User[]
    sPrice String? @default("")
    sPriceDev String? @default("")
    isPopular Boolean @default(false)
}
````

```ts
  const { id: sId } = await ctx.prisma.search.upsert({
            where: {
              asin,
            },
            create: createData,
            update: createData,
          });

          console.log("got here");
          const tmp = await ctx.prisma.userSearch.upsert({
            where: {
              id: input.id,
            },
            create: {
              searchId: sId,
              userId: ctx.session.user.id,
              count: input.count ?? 1,
            },
            update: {
              count: input.count ?? 1,
            },
          });
```

### Environment & setup

- OS: MacOS
- Database: PlanetScale
- Node.js version: 19.3.0

### Prisma Version

```
prisma                  : 4.11.0
@prisma/client          : 4.11.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 8fde8fef4033376662cad983758335009d522acb (at node_modules/.pnpm/@prisma+engines@4.11.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 8fde8fef4033376662cad983758335009d522acb (at node_modules/.pnpm/@prisma+engines@4.11.0/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.11.0-57.8fde8fef4033376662cad983758335009d522acb
Default Engines Hash    : 8fde8fef4033376662cad983758335009d522acb
Studio                  : 0.483.0
```

**Comment by OrJDev** [comment]
it seems to be working with:

```ts
  const tmp = await ctx.prisma.userSearch.upsert({
            where: {
              id: input.id ?? "",
            },
            create: {
              searchId: sId,
              userId: ctx.session.user.id,
              count: input.count ?? 1,
            },
            update: {
              count: input.count ?? 1,
            },
          });
```
          
          like setting the default id to an empty string, but the prisma type is: `string | undefined` so i expect it to create a record if i don't provide an id, or the type to be `string`

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
