### ISSUE TITLE
Bug: When using @ignore on @id field, Prisma tries to save @default value in non-@ignore field

### ISSUE THREAD

**Issue by Wondermarin** [prisma/prisma#19033]
### Bug description

The `Player` model has an @id field that should be substituted with the @default value of @db.ObjectId, but when using the `create` function, Prisma tries to substitute the @default value in the field that is under the @id field in the schema. If you change the sequence of fields in the schema, i.e. `accountId` and `account` are swapped, then the error will already occur when serializing the `account` field.

Error:
```
PrismaClientKnownRequestError: 
Invalid `this.prismaService.player.create()` invocation in
C:\Users\wonder\Desktop\s\parser\dist\modules\parser\parser.processor.js:281:45

  278     },
  279 };
  280 console.dir(data, { depth: Infinity });
→ 281 await this.prismaService.player.create(
Error converting field "accountId" of expected non-nullable type "Int", found incompatible value of "6450aa292cab82d7d1a1f04f".
    at pn.handleRequestError (C:\Users\wonder\Desktop\s\parser\node_modules\@prisma\client\runtime\library.js:176:6477)
    at pn.handleAndLogRequestError (C:\Users\wonder\Desktop\s\parser\node_modules\@prisma\client\runtime\library.js:176:5907)
    at pn.request (C:\Users\wonder\Desktop\s\parser\node_modules\@prisma\client\runtime\library.js:176:5786)
    at PrismaService._request (C:\Users\wonder\Desktop\s\parser\node_modules\@prisma\client\runtime\library.js:179:10484)
    at ParserProcessor.savePlayers (C:\Users\wonder\Desktop\s\parser\dist\modules\parser\parser.processor.js:281:13)
    at ParserProcessor.parse (C:\Users\wonder\Desktop\s\parser\dist\modules\parser\parser.processor.js:83:17) {
  code: 'P2032',
  clientVersion: '4.13.0',
  meta: {
    field: 'accountId',
    expected_type: 'Int',
    found: '6450aa292cab82d7d1a1f04f'
  }
}
```

If you change the sequence of fields in the schema:
```
PrismaClientUnknownRequestError: 
Invalid `this.prismaService.player.create()` invocation in
C:\Users\wonder\Desktop\s\parser\dist\modules\parser\parser.processor.js:281:45

  278     },
  279 };
  280 console.dir(data, { depth: Infinity });
→ 281 await this.prismaService.player.create(
Attempted to serialize '6450aaa12a6a2369637b4e0a' with non-composite compatible type '"PlayerAccount"' for field account.
    at pn.handleRequestError (C:\Users\wonder\Desktop\s\parser\node_modules\@prisma\client\runtime\library.js:176:6649)
    at pn.handleAndLogRequestError (C:\Users\wonder\Desktop\s\parser\node_modules\@prisma\client\runtime\library.js:176:5907)
    at pn.request (C:\Users\wonder\Desktop\s\parser\node_modules\@prisma\client\runtime\library.js:176:5786)
    at PrismaService._request (C:\Users\wonder\Desktop\s\parser\node_modules\@prisma\client\runtime\library.js:179:10484)
    at ParserProcessor.savePlayers (C:\Users\wonder\Desktop\s\parser\dist\modules\parser\parser.processor.js:281:13)
    at ParserProcessor.parse (C:\Users\wonder\Desktop\s\parser\dist\modules\parser\parser.processor.js:83:17) {
  clientVersion: '4.13.0'
}
```

### How to reproduce

1. Set @ignore to @id field with @default.
2. Use the `create` function.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Player {
  id        String        @id @default(auto()) @map("_id") @ignore @db.ObjectId
  accountId Int           @unique
  account   PlayerAccount
  matches   PlayerMatch[]

  @@map("player")
}
```

```ts
await this.prismaService.player.create({
  data: {
    accountId: 1,
    account: {
      isAnonymous: false,
      avatar: 'test',
      name: 'Test',
      rank: [ 75, 0 ],
      pro: null
    },
    matches: { set: [] }
  },
});
```

### Environment & setup

- OS: Windows 11
- Database: MongoDB
- Node.js version: 16.6.0

### Prisma Version

```
prisma                  : 4.13.0
@prisma/client          : 4.13.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.13.0-50.1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Default Engines Hash    : 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Studio                  : 0.484.0
```

**Comment by Weakky** [comment]
Hey @Wondermarin,

Would you mind sharing the missing bits of your Prisma Schema? Specifically, the `PlayerAccount` model for which the error is happening is missing. Thank you 🙏

**Comment by Wondermarin** [comment]
> Hey @Wondermarin,
> 
> Would you mind sharing the missing bits of your Prisma Schema? Specifically, the `PlayerAccount` model for which the error is happening is missing. Thank you 🙏

The error does not occur for `PlayerAccount`, it occurs for any field that comes after `id`.

Full scheme:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model Player {
  id        String        @id @default(auto()) @map("_id") @ignore @db.ObjectId
  account   PlayerAccount
  accountId Int           @unique
  matches   PlayerMatch[]

  @@map("player")
}

type PlayerAccount {
  isAnonymous Boolean
  avatar      String
  name        String
  rank        Int[]
  pro         PlayerAccountPro?
}

type PlayerAccountPro {
  name String
  team PlayerAccountProTeam?
}

type PlayerAccountProTeam {
  name String
}

type PlayerMatch {
  id        Int
  lobbyType Int
  bracket   Int
  duration  Int
  startTime Int
  endTime   Int
  personal  PlayerMatchPersonal
}

type PlayerMatchPersonal {
  hero      Int
  position  Int
  isVictory Boolean
  kills     Int
  deaths    Int
  assists   Int
  items     Int[]
}
```

**Comment by Wondermarin** [comment]
@Weakky

**Comment by Wondermarin** [comment]
@Weakky
 I have updated the issue description to show the problem more clearly.

**Comment by janpio** [comment]
Can you please [enable query logging in your project](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging) and share what is output for the query that then throws the error message? Thanks.

**Comment by miguelff** [comment]
Reproduced in [19033.tar.gz](https://github.com/prisma/prisma/files/12257331/19033.tar.gz). 

* Decompress in prisma/prisma/reproductions
* `docker compose up mongo` in `prisma/prisma`
* `cd prisma/prisma/reproductions/19033`
* pnpx prisma generate && pnpx prisma db push && pnpx test

**Comment by wxfred** [comment]
Any progress?

**Comment by zyf0330** [comment]
Any progress? I meet it too.
