### ISSUE TITLE
Add support for RISC-V platforms

### ISSUE THREAD

**Issue by aragubas** [prisma/prisma#19141]
### Bug description

prisma client doesn't seem to work on RISC-V platforms, I have a StarFive VisionFive 2 running dietpi. When I try to run prisma generate it results in this error:

```
prisma:warn Prisma only officially supports Linux on amd64 (x86_64) and arm64 (aarch64) system architectures. If you are using your own custom Prisma engines, you can ignore this warning, as long as you've compiled the engines for your system architecture "riscv64".
Prisma schema loaded from prisma/schema.prisma
prisma:warn Prisma only officially supports Linux on amd64 (x86_64) and arm64 (aarch64) system architectures. If you are using your own custom Prisma engines, you can ignore this warning, as long as you've compiled the engines for your system architecture "riscv64".
Oops, an unexpected error occurred!


Please help us improve Prisma by submitting an error report.
Error reports never contain personal or other sensitive information.
Learn more: https://pris.ly/d/telemetry

✔ Submit error report › Yes
Submitting...
Oops. We could not send the error report.
Error report submission failed due to:  FetchError: invalid json response body at https://error-reports.prisma.sh/ reason: Unexpected token H in JSON at position 0
    at /home/dietpi/TaiyouCloudServices/node_modules/prisma/build/index.js:95677:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async request (/home/dietpi/TaiyouCloudServices/node_modules/prisma/build/index.js:101154:10)
    at async createErrorReport (/home/dietpi/TaiyouCloudServices/node_modules/prisma/build/index.js:101129:18)
    at async sendPanic (/home/dietpi/TaiyouCloudServices/node_modules/prisma/build/index.js:101239:23)
    at async panicDialog (/home/dietpi/TaiyouCloudServices/node_modules/prisma/build/index.js:101568:24)
    at async handlePanic (/home/dietpi/TaiyouCloudServices/node_modules/prisma/build/index.js:101529:3) {
  type: 'invalid-json'
}
```

This same project works just fine on Windows running on Intel x86-64

## I tried compiling prisma engines project that also results in errors:

```
error: failed to run custom build command for `ring v0.16.20`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/dietpi/TaiyouCloudServices/prisma-engines/target/release/build/ring-7d55e492ab4bfad9/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/dietpi/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
  stack backtrace:
     0:       0x2abee4c524 - std::backtrace_rs::backtrace::libunwind::trace::he9a1b82943da7084
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:       0x2abee4c524 - std::backtrace_rs::backtrace::trace_unsynchronized::h4a3bd124aff34be0
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:       0x2abee4c524 - std::sys_common::backtrace::_print_fmt::h0f1485e042da3be9
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
     3:       0x2abee4c524 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b7682bd7338e995
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
     4:       0x2abee65346 - core::fmt::write::h83e1f2466e441f0a
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
     5:       0x2abee48a66 - std::io::Write::write_fmt::h05c98a7be44d458d
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
     6:       0x2abee4c38a - std::sys_common::backtrace::_print::h912840d42c4684d9
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
     7:       0x2abee4c38a - std::sys_common::backtrace::print::hf6f811a61f26b68d
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
     8:       0x2abee4d868 - std::panicking::default_hook::{{closure}}::hac1f6108756dcba3
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
     9:       0x2abee4d5e4 - std::panicking::default_hook::h8f2a83a823fc3b04
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
    10:       0x2abee4e340 - std::panicking::rust_panic_with_hook::hab688c9ea57f8cbc
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
    11:       0x2abee4e212 - std::panicking::begin_panic_handler::{{closure}}::hf30e9e6fd2c5fedd
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:581:13
    12:       0x2abee4c878 - std::sys_common::backtrace::__rust_end_short_backtrace::ha91c2f23a1507f10
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
    13:       0x2abee4e016 - rust_begin_unwind
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
    14:       0x2abedf593a - core::panicking::panic_fmt::h39e8d07101af232a
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
    15:       0x2abedf599c - core::panicking::panic::h0961496bd60c7899
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
    16:       0x2abedf93ce - core::option::Option<T>::unwrap::h382e974f66d801da
    17:       0x2abedfb13c - build_script_build::build_c_code::hed61f6a747174ae8
    18:       0x2abedfab3c - build_script_build::ring_build_rs_main::h54f40c304c771cbf
    19:       0x2abedfa640 - build_script_build::main::hf0c48e186683f24f
    20:       0x2abedf97ee - core::ops::function::FnOnce::call_once::h7897e5d06bb56f5b
    21:       0x2abedf8b12 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2afc4eb3fa9f95f4
    22:       0x2abedf9f64 - std::rt::lang_start::{{closure}}::h76a7078e8244da50
    23:       0x2abee4d9fe - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h07ac3b34412336b7
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
    24:       0x2abee4d9fe - std::panicking::try::do_call::h17a8984105da8161
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
    25:       0x2abee5a3de - __rust_try
    26:       0x2abee4defe - std::panicking::try::h5992d5c22f06e21b
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
    27:       0x2abee4defe - std::panic::catch_unwind::hd9998f9915772564
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
    28:       0x2abee4defe - std::rt::lang_start_internal::{{closure}}::h8da58d6cb5692ea1
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
    29:       0x2abee4defe - std::panicking::try::do_call::ha70bf54d98ba8d2a
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
    30:       0x2abee5a3de - __rust_try
    31:       0x2abee45d06 - std::panicking::try::hf476c78e6fac8e15
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
    32:       0x2abee45d06 - std::panic::catch_unwind::hce313120d2abeb83
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
    33:       0x2abee45d06 - std::rt::lang_start_internal::hae5e647b21932486
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
    34:       0x2abedf9f4c - std::rt::lang_start::h03cb22da1b7a5786
    35:       0x2abedfe0ea - main
    36:       0x3fa636cb04 - <unknown>
    37:       0x3fa636cbac - __libc_start_main
    38:       0x2abedf5c58 - _start
    39:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
```

### Expected behavior

prisma generate should just work 

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  id       String   @id @default(uuid())
  taiyouID String   @unique
  fullName String
  password String
  joinedAt DateTime @default(now())

  // Contacts
  Contact Contact[]

  // Friend and Friend Requests
  // OutgoingFriendRequests FriendRequest[]

  FriendsSender UserFriendship[] @relation("friendSender")
  FriendsReceiver UserFriendship[] @relation("friendReceiver")

  FriendRequestSender UserFriendRequest[] @relation("friendRequestSender")
  FriendRequestReceiver UserFriendRequest[] @relation("friendRequestReceiver")
}

model UserFriendRequest {
  friendRequestSender   User   @relation("friendRequestSender", fields: [friendRequestSenderId], references: [id], onDelete: Cascade)
  friendRequestSenderId String

  friendRequestReceiver   User   @relation("friendRequestReceiver", fields: [friendRequestReceiverId], references: [id], onDelete: Cascade)
  friendRequestReceiverId String

  @@id([friendRequestSenderId, friendRequestReceiverId])
}

model UserFriendship {
  friendSender   User   @relation("friendSender", fields: [friendSenderId], references: [id], onDelete: Cascade)
  friendSenderId String

  friendReceiver   User   @relation("friendReceiver", fields: [friendReceiverId], references: [id], onDelete: Cascade)
  friendReceiverId String

  @@id([friendSenderId, friendReceiverId])
}

model Contact {
  id           String  @id @default(uuid())
  fullName     String
  phoneNumber  String?
  emailAddress String  @default("")

  // Contact Owner
  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId String
}
```

```ts
// there's hundres of lines of code on various files that uses prisma, so I'll just drop the main file in here xP

import { PrismaClient } from "@prisma/client";
import express from "express";
import { createServer } from "http";
import infoRouter from "./GlobalRoutes/InfoRoute";
import Cors from "./Middleware/Express/Cors";
import contactsRouter from "./Routes/Contacts/ContactsRoute";
import usersRouter from "./Routes/User/UserRoute";
import { Server } from "socket.io";
import { nodeInfo } from "./constants";
import * as dotenv from "dotenv";
import { constants, accessSync } from "fs";
import path from "path";
import JsonExceptionHandler from "./Middleware/Express/JsonExceptionHandler";
import { verify } from "jsonwebtoken";
import JwtSession from "./Models/JwtSession";
import authenticateToken from "./Middleware/SocketIO/JwtAuthenticateToken";

// Try to access .env file located one path above as __dirname
try {
  const pathOne: string = path.join(__dirname, "../", ".env");
  accessSync(pathOne, constants.R_OK);

  // Configures dotenv
  dotenv.config({ path: pathOne });

  if (process.env.TOKEN_SECRET == undefined) {
    console.error(
      "[Main] Fatal Error! dotenv file is empty or corrupted. Could not find field TOKEN_SECRET, required for Authentication."
    );
    process.exit(-1);
  }
} catch (ex: any) {
  if (ex.code == "ENOENT") {
    console.error("[Main] Fatal Error! could not find .env");
    console.info(
      "If you are setting up a TaiyouCS Node make sure to create the .env file using the template provided in the .env.example file."
    );
  } else {
    console.error(ex);
  }

  process.exit(-1);
}

export const expressServer = express();
export const prisma = new PrismaClient();

// Modules
expressServer.use(Cors);
expressServer.use(express.json({ limit: "128kb" }));
expressServer.use(JsonExceptionHandler);

// Global Routes
expressServer.use("/info", infoRouter);
expressServer.get("/", (request, response) => {
  response.json(nodeInfo);
});

// TaiyouApps Routes
expressServer.use("/contacts", contactsRouter);
expressServer.use("/users", usersRouter);

// SocketIO
const server = createServer(expressServer);
export const socketServer = new Server(server, {
  cors: { origin: "*" },
});

// Middlewares
socketServer.use(authenticateToken);

socketServer.on("connection", (socket) => {
  // When client disconnects
  socket.on("disconnect", () => {
    console.log(`[SocketIO] Client id:${socket.id} disconnected`);
  });
});

async function init(port: number) {
  console.log(`[Main] ${nodeInfo.type} v${nodeInfo.version.Major}.${nodeInfo.version.Revision}`);
  // First, start the database
  await prisma.$connect();

  server.listen(port);

  console.log(`[Main] Listening on port ${port}`);
}

init(3369);
```

### Environment & setup

- OS: dietpi v8.17.9 (debian based Linux Distro, running the version compiled for the JH7110 RISC-V CPU)
- Database: MySQL
- Node.js version: v18.13.0

### prisma -v returns this
```
prisma:warn Prisma only officially supports Linux on amd64 (x86_64) and arm64 (aarch64) system architectures. If you are using your own custom Prisma engines, you can ignore this warning, as long as you've compiled the engines for your system architecture "riscv64".
prisma:warn Prisma only officially supports Linux on amd64 (x86_64) and arm64 (aarch64) system architectures. If you are using your own custom Prisma engines, you can ignore this warning, as long as you've compiled the engines for your system architecture "riscv64".
Error: Unable to require(`/home/dietpi/TaiyouCloudServices/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`).
The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: /home/dietpi/TaiyouCloudServices/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node: cannot open shared object file: No such file or directory
    at loadLibrary (/home/dietpi/TaiyouCloudServices/node_modules/prisma/build/index.js:97408:11)
    at getEngineVersion (/home/dietpi/TaiyouCloudServices/node_modules/prisma/build/index.js:97422:16)
Error: Command failed with exit code 2: /home/dietpi/TaiyouCloudServices/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version
/home/dietpi/TaiyouCloudServices/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: 1: ELF: not found
/home/dietpi/TaiyouCloudServices/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: 2: Syntax error: ")" unexpected
    at makeError (/home/dietpi/TaiyouCloudServices/node_modules/prisma/build/index.js:3672:18)
    at handlePromise (/home/dietpi/TaiyouCloudServices/node_modules/prisma/build/index.js:4440:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getEngineVersion (/home/dietpi/TaiyouCloudServices/node_modules/prisma/build/index.js:97425:24) {
  shortMessage: 'Command failed with exit code 2: /home/dietpi/TaiyouCloudServices/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version',
  command: '/home/dietpi/TaiyouCloudServices/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x --version',
  escapedCommand: '"/home/dietpi/TaiyouCloudServices/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x" --version',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/dietpi/TaiyouCloudServices/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: 1: \x7FELF\x02\x01\x01\x03: not found\n' +
    '/home/dietpi/TaiyouCloudServices/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x: 2: Syntax error: ")" unexpected',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
prisma                  : 4.13.0
@prisma/client          : 4.13.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.13.0-50.1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Default Engines Hash    : 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Studio                  : 0.484.0
```

**Comment by aqrln** [comment]
See https://github.com/briansmith/ring/issues/1182 for the feature request to support RISC-V in the dependency that doesn't compile.

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
