### ISSUE TITLE
Prisma, PNPM, Esbuild - Schema path issues with multiple schemas

### ISSUE THREAD

**Issue by mckernanin** [prisma/prisma#19183]
### Bug description

I don't have a shareable reproduction at the moment but I will work on making one.

I have a pnpm monorepo with the following structure:
![image](https://github.com/prisma/prisma/assets/6300047/d5ee0b46-341a-4501-b542-589138c37049)

packages/eve-sde and packages/planets-db both contain a prisma schema (eve-sde uses sqlite, planets-db uses PostgreSQL)

planets-discord and planets-reminder are node apps that use both schemas, currently being built with @vercel/ncc (but have tried esbuild as well)

I didn't have any issues until I added the second prisma instance. Both would try to hit the postgres database, because they were referencing "schema.prisma". eve-sde uses `eve-sde.prisma` (with the setting in package.json). I updated planets-db to use a named file as well.

I switched to esbuild, and now no schema is available at runtime:
```
Error: ENOENT: no such file or directory, open '/app/apps/planets-discord/dist/schema.prisma'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at new LibraryEngine (/app/apps/planets-discord/dist/index.js:239:2538)
    at t.getEngine (/app/apps/planets-discord/dist/index.js:319:6010)
    at new PrismaClient (/app/apps/planets-discord/dist/index.js:319:5594)
    at Object.<anonymous> (/app/apps/planets-discord/dist/index.js:594:195177)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/app/apps/planets-discord/dist/schema.prisma',
  clientVersion: '4.13.0'
}
```

Interestingly, apps/planetsinspace is a nextjs 13 app, and it compiles fine and manages to use both of the clients just fine.

### How to reproduce

Will include better once I have a reproduction to share, tldr:
Try to use 2 separate prisma clients in a pnpm monorepo

### Prisma information

schemas in gist:
https://gist.github.com/mckernanin/f6509c15a09c80d5d67ad77320adadde

code isn't really an issue, works in development just fine. I"m only encountering issues once it's compiled.

### Environment & setup

- OS: Ubuntu (WSL)
- Database: Postgres and SQLite
- Node.js version: 16.14.2

### Prisma Version

```
❯ pnpm prisma -v          
Environment variables loaded from .env
prisma                  : 4.14.0
@prisma/client          : 4.14.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine d9a4c5988f480fa576d43970d5a23641aa77bc9c (at ../../node_modules/.pnpm/@prisma+engines@4.14.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli d9a4c5988f480fa576d43970d5a23641aa77bc9c (at ../../node_modules/.pnpm/@prisma+engines@4.14.0/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.14.0-67.d9a4c5988f480fa576d43970d5a23641aa77bc9c
Default Engines Hash    : d9a4c5988f480fa576d43970d5a23641aa77bc9c
Studio                  : 0.484.0
```

**Comment by mckernanin** [comment]
@Jolg42 good ol' fashioned docker containers

**Comment by mckernanin** [comment]
As I was working on building a reproduction, I'm pretty sure I realized what the issue is. I'm using the monorepo-workaround plugin for nextjs, and I don't have anything like that in the build steps for my other apps.

**Comment by mckernanin** [comment]
I was able to resolve my build issues by following the steps detailed here: https://github.com/prisma/prisma/issues/18069#issuecomment-1536344211

I also had an import that was importing @prisma/client directly instead of through one of my defined database packages. My apps are now building, but when I invoke something that calls my sqlite prisma schema I get a `Could not find mapping for model ${model}` error. I did need to specify a path to the query engine, which looks like this in my docker file:
`ENV PRISMA_QUERY_ENGINE_LIBRARY "/app/planets-db/libquery_engine-linux-musl.so.node"`

The contents of the container look like this:
```
/app # ls -alh
total 488M   
drwxr-xr-x    1 root     root        4.0K May 16 17:26 .
drwxr-xr-x    1 root     root        4.0K May 16 17:53 ..
-rw-r--r--    1 root     root       75.2K May 16 17:25 797.index.js
drwxr-xr-x    2 root     root        4.0K May 16 17:25 eve-sde
-rw-r--r--    1 root     root        7.9M May 16 17:25 index.js
drwxr-xr-x    2 root     root        4.0K May 16 17:25 planets-db
-rw-r--r--    1 root     root        3.3K May 16 17:25 schema.prisma
-rw-r--r--    1 root     root       23.2K May 16 17:25 schema1.prisma
-rw-r--r--    1 root     root      480.2M May  8 23:31 sqlite-latest.sqlite
/app # ls -alh eve-sde/
total 14M    
drwxr-xr-x    2 root     root        4.0K May 16 17:25 .
drwxr-xr-x    1 root     root        4.0K May 16 17:26 ..
-rwxr-xr-x    1 root     root       13.7M May 16 17:25 libquery_engine-linux-musl.so.node
/app # ls -alh planets-db/
total 14M    
drwxr-xr-x    2 root     root        4.0K May 16 17:25 .
drwxr-xr-x    1 root     root        4.0K May 16 17:26 ..
-rwxr-xr-x    1 root     root       13.7M May 16 17:25 libquery_engine-linux-musl.so.node
```

What do I need to do to get the second client working properly?

**Comment by mckernanin** [comment]
Ok the issue is that the eve-sde prisma client is reading in schema.prisma, when it should be looking at schema1.prisma. From looking at the source here https://github.com/prisma/prisma/blob/ccf0ad5232f83ffb7c3210287acb918e017c2fb0/packages/client/src/runtime/getPrismaClient.ts#LL439C28-L439C28 I see that datamodelPath is defaulting to `schema.prisma` as nothing else is defined. Where can I define a datamodelPath?

**Comment by theonlydaleking** [comment]
FWIW I'm at the same point as you. My package is a pnpm monorepo with turbo pack, I had the issue with the "cannot find mapping for {model}" 
I resolved that by actually removing the next-workaround-plugin and setting the output of the prisma schemas to the root level node-modules. This fixed the problem in Nextjs. 

As soon as I did this, the second app using prisma broke - a simple express app that worked all along now gives me an error saying the imported prisma schema can't find the env variables. I've put the .env in every location you can think of, even tried running generate with dotenv-cli and none of that works. 

So I either go back to using the workaround plugin and trying to fix nextjs another way, Or I bust apart the monorepo and just run separate repos. 

Prisma seems to struggle a bit with PNPM, it also seems to struggle slightly with >1 schema, and it struggles with monorepos. 
When you add all 3 of these together it's like a 1+1+1 = 300 situation of complexity. I see Prisma team are currently collecting reports on it so I'm hopeful there's something in the near future. But for now I think I'll bust apart the monorepo. I've wasted days on this now unfortunately and it's slowing me down. 

@mckernanin let me know how you go

**Comment by mckernanin** [comment]
@theonlydaleking similar issue to you. I removed the plugin, and am exporting clients to root node_modules. Next app works, 2 apps don't (one is a discord bot, the other is a reminders cron job). The other apps are compiled with @vercel/ncc and get confused on what schema they should be using. I need to try some other build tools where it's not bundling

**Comment by mckernanin** [comment]
@theonlydaleking i got it working

- built the database packages with ncc
- in my containers, copy the built versions into `node_modules`
- run ncc on the app with my database packages marked as external
- copy the prisma binary into node modules

```dockerfile
COPY --from=builder /app/packages/eve-sde/dist /app/node_modules/eve-sde
COPY --from=builder /app/packages/planets-db/dist /app/node_modules/planets-db
COPY --from=builder /app/packages/planets-db/dist/planets-db/libquery_engine-linux-musl.so.node /app/node_modules
```
