### ISSUE TITLE
$transaction([...]): Misleading code snippet on error

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#19203]
With this Prisma schema:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Test {
  id  String @id @default(uuid())
  foo String
}
```

and then running `db push`, and then this script:

```
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient({ log: ["query"]});

async function main() {
  await prisma.test.deleteMany();

  try {
    await prisma.$transaction([
      prisma.test.create({ data: { foo: "hello" } }),
      prisma.test.create({ data: { foo: null } }),
    ]);
  } catch (e) {
    console.error("error", e)
    /* noop */
  }
  console.table(await prisma.test.findMany())
  console.log(await prisma.test.count())
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```

you get this log output with `DEBUG=*` active:
```
PS C:\Users\Jan\Documents\throwaway\gatherTransactions> node .\transaction-error.js
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\gatherTransactions\.env +0ms
  prisma:client  checkPlatformCaching:postinstall undefined +0ms
  prisma:client  checkPlatformCaching:ciName undefined +2ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jan\Documents\throwaway\gatherTransactions\.env +9ms
  prisma:client  dirname C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\.prisma\client +0ms
  prisma:client  relativePath ..\..\..\prisma +1ms
  prisma:client  cwd C:\Users\Jan\Documents\throwaway\gatherTransactions\prisma +0ms
  prisma:client  protocol graphql +0ms
  prisma:client  clientVersion 4.14.0 +1ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\.prisma\client +0ms
  prisma:client:libraryEngine:loader  loadEngine using C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\.prisma\client\query_engine-windows.dll.node +0ms
  prisma:client:libraryEngine  library starting +14ms
  prisma:client:libraryEngine  library started +3ms
  prisma:client  Prisma Client call: +26ms
  prisma:client  prisma.test.deleteMany(undefined) +1ms
  prisma:client  Generated request: +1ms
  prisma:client  mutation {
  deleteManyTest {
    count
  }
}
 +1ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +12ms
prisma:query BEGIN
prisma:query SELECT `main`.`Test`.`id` FROM `main`.`Test` WHERE 1=1 LIMIT ? OFFSET ?
prisma:query SELECT `main`.`Test`.`id` FROM `main`.`Test` WHERE 1=1
prisma:query COMMIT
  prisma:client  Prisma Client call: +8ms
  prisma:client  prisma.test.create({
  data: {
    foo: 'hello'
  }
}) +2ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  createOneTest(data: {
    foo: "hello"
  }) {
    id
    foo
  }
}
 +1ms
  prisma:client  Prisma Client call: +1ms
  prisma:client  prisma.test.create({
  data: {
    foo: null
  }
}) +0ms
  prisma:client  Generated request: +1ms
  prisma:client  mutation {
  createOneTest(data: {
    foo: null
  }) {
    id
    foo
  }
}
 +0ms
  prisma:client:libraryEngine  requestBatch +13ms
prisma:query BEGIN
prisma:query ROLLBACK
  prisma:client:request_handler  PrismaClientKnownRequestError: Unable to match input value to any allowed input type for the field. Parse errors: [`data.foo`: A value is required but not set, `data.foo`: A value is required but not set]
    at Ds (C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\@prisma\client\runtime\library.js:31:5919)        
    at Zt.buildQueryError (C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\@prisma\client\runtime\library.js:106:903)
    at Zt.requestBatch (C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\@prisma\client\runtime\library.js:106:409) {
  code: 'P2009',
  clientVersion: '4.14.0',
  meta: { kind: 'Union', errors: [ [Object], [Object] ] }
} +0ms
  prisma:client:request_handler  PrismaClientKnownRequestError: Unable to match input value to any allowed input type for the field. Parse errors: [`data.foo`: A value is required but not set, `data.foo`: A value is required but not set]
    at Ds (C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\@prisma\client\runtime\library.js:31:5919)        
    at Zt.buildQueryError (C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\@prisma\client\runtime\library.js:106:903)
    at Zt.requestBatch (C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\@prisma\client\runtime\library.js:106:409) {
  code: 'P2009',
  clientVersion: '4.14.0',
  meta: { kind: 'Union', errors: [ [Object], [Object] ] }
} +10ms
error PrismaClientValidationError:
Invalid `prisma.test.create()` invocation in
C:\Users\Jan\Documents\throwaway\gatherTransactions\transaction-error.js:10:19

   7
   8 try {
   9   await prisma.$transaction([
→ 10     prisma.test.create({
           data: {
         +   foo: String
           }
         })

Argument `foo` is missing.
    at bn (C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\@prisma\client\runtime\library.js:164:1259)       
    at Pn.handleRequestError (C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\@prisma\client\runtime\library.js:171:6669)
    at Pn.handleAndLogRequestError (C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\@prisma\client\runtime\library.js:171:6358)
    at Pn.request (C:\Users\Jan\Documents\throwaway\gatherTransactions\node_modules\@prisma\client\runtime\library.js:171:6237)
  prisma:client  Prisma Client call: +20ms
  prisma:client  prisma.test.findMany(undefined) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findManyTest {
    id
    foo
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +21ms
prisma:query SELECT `main`.`Test`.`id`, `main`.`Test`.`foo` FROM `main`.`Test` WHERE 1=1 LIMIT ? OFFSET ?
┌─────────┐
│ (index) │
├─────────┤
└─────────┘
  prisma:client  Prisma Client call: +5ms
  prisma:client  prisma.test.count({
  select: {
    _count: {
      select: {
        _all: true
      }
    }
  }
}) +0ms
  prisma:client  Generated request: +1ms
  prisma:client  query {
  aggregateTest {
    _count {
      _all
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +6ms
prisma:query SELECT COUNT(*) FROM (SELECT `main`.`Test`.`id` FROM `main`.`Test` WHERE 1=1 LIMIT ? OFFSET ?) AS `sub`
0
  prisma:client:libraryEngine  library stopping +11ms
  prisma:client:libraryEngine  library stopped +1ms
  prisma:client:libraryEngine:exitHooks  exit event received: 0 +0ms
  prisma:client:libraryEngine:exitHooks  exit event received: 0 +0ms
```

Note how the code snippet that is generated to be helpful clearly points to the first query in the array of queries for `$transactions([...])`, while the one that causes the problem is clearly the second one:

```
error PrismaClientValidationError:
Invalid `prisma.test.create()` invocation in
C:\Users\Jan\Documents\throwaway\gatherTransactions\transaction-error.js:10:19

   7
   8 try {
   9   await prisma.$transaction([
→ 10     prisma.test.create({
           data: {
         +   foo: String
           }
         })

Argument `foo` is missing.
```

(Version 4.14.0)

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
