### ISSUE TITLE
P1017 Server has closed the connection on linux_arm64

### ISSUE THREAD

**Issue by jonathanswenson** [prisma/prisma#19209]
### Bug description

Intermittently (but very often) a database connection to an aurora serverless postgres instance will fail with 
`Server has closed the connection`. 

I am running on both linux_arm64 and linux_x86_64 (debian) containers. 

I am ONLY seeing these disconnects when running on linux_arm64. 

The linux_arm64 containers are using libquery_engine-linux-arm64-openssl-1.1.x.so.node
The linux_x86_64 containers are using libquery_engine-debian-openssl-1.1.x.so.node

There does not seem to be any rhyme or reason the schema / variety of calls that are made that fail, but they appear to be connections that have been open for random amounts of time and often (but not always) not used for a small period of time. 

I've seen findSingle and findMany calls on a resource / table fail intermittently. 

```
Error: 
Invalid `db.table.findFirst()` invocation in
/app/build/index.js:34054:34
  34051     }
  34052   });
  34053 }, getValue = async (id) => {
→ 34054   let value = await db.table.findFirst(
Server has closed the connection.
    at pn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:6477)
    at pn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:5907)
    at pn.request (/app/node_modules/@prisma/client/runtime/library.js:176:5786)
    at /app/node_modules/@prisma/client/runtime/library.js:70:26059
    at t._request (/app/node_modules/@prisma/client/runtime/library.js:179:10484)
```

At the same time the postgres server is reporting that there are disconnected sessions / connection reset by peer from the client. 

```
2023-05-11 23:52:48 UTC:10.0.5.22(49478):XXX@XXX:[25972]:LOG: disconnection: session time: 1:04:11.544 user=XXX database=XXX host=10.0.5.22 port=49478
2023-05-11 23:52:48 UTC:10.0.5.22(56242):[unknown]@[unknown]:[1514]:LOG: could not receive data from client: Connection reset by peer
2023-05-11 23:52:48 UTC:10.0.5.22(57500):XXX@XXX:[17186]:LOG: disconnection: session time: 2:14:50.294 user=XXX database=XXX host=10.0.5.22 port=57500
2023-05-11 23:52:48 UTC:10.0.5.22(57528):XXX@XXX:[17189]:LOG: disconnection: session time: 2:14:50.190 user=XXX database=XXX host=10.0.5.22 port=57528
2023-05-11 23:52:51 UTC:10.0.5.22(57504):XXX@XXX:[17187]:LOG: disconnection: session time: 2:14:53.154 user=XXX database=XXX host=10.0.5.22 port=57504
2023-05-11 23:53:20 UTC:10.0.5.22(56230):XXX@XXX:[1512]:LOG: could not receive data from client: Connection reset by peer
2023-05-11 23:53:20 UTC:10.0.5.22(56230):XXX@XXX:[1512]:LOG: disconnection: session time: 0:00:32.129 user=XXX database=XXX host=10.0.5.22 port=56230
2023-05-11 23:53:36 UTC:10.0.5.22(43924):XXX@XXX:[1594]:LOG: could not receive data from client: Connection reset by peer
2023-05-11 23:53:36 UTC:10.0.5.22(43924):XXX@XXX:[1594]:LOG: disconnection: session time: 0:00:15.051 user=XXX database=XXX host=10.0.5.22 port=43924
2023-05-11 23:54:42 UTC:10.0.5.22(56256):XXX@XXX:[1547]:LOG: could not receive data from client: Connection reset by peer
2023-05-11 23:54:42 UTC:10.0.5.22(56256):XXX@XXX:[1547]:LOG: disconnection: session time: 0:01:45.950 user=XXX database=XXX host=10.0.5.22 port=56256
2023-05-11 23:54:45 UTC:10.0.5.22(51814):XXX@XXX:[1763]:LOG: could not receive data from client: Connection reset by peer
2023-05-11 23:54:45 UTC:10.0.5.22(51814):XXX@XXX:[1763]:LOG: disconnection: session time: 0:00:01.678 user=XXX database=XXX host=10.0.5.22 port=51814
```

It fails more often if I go away for a few seconds (rather than running / refreshing continually). 

But from the disconnections log it seems like occasionally the session time is < 2 seconds. 

### How to reproduce

Run random queries against prisma connection on a host running an linux_arm64 architecture. 

They will fail intermittently. 

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["tracing"]
  binaryTargets   = ["native"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// schema is not relevant as far as i can tell. 
```
An example of one failing call. 
```ts
const db = new PrismaClient({
  log: [{ emit: 'event', level: 'query', },],
})

const value = await db.table.findFirst({
    where: {
      created_at: {
        gte: new Date(),
      },
      id,
    },
  })
```

### Environment & setup

- OS: linux_arm64 container in ECS
- Database: RDS Postgres aurora serverless 
- Node.js version: v16.20.0

### Prisma Version

```
4.13.0 
```

Also observed on 4.10.1

**Comment by janpio** [comment]
Does this also happen when the `tracing` preview feature is not enabled?
Do you think this would reproduce when we run a random app with trivial queries on a linux_arm64 container in ECS?

**Comment by jonathanswenson** [comment]
I can give it a shot running without tracing. 

> Do you think this would reproduce when we run a random app with trivial queries on a linux_arm64 container in ECS?

I would not be surprised if it reproduced (then again I also wouldn't be surprised if it didn't). 

I also have on my TODO list to try building the container we're running on linux_arm64 hardware (rather than building on an M1 mac). 

I'm using the public ecr image node:16-bullseye-slim image as my base image. 
```
FROM public.ecr.aws/docker/library/node:16-bullseye-slim as base
```

I'm installing a few other things on it, but the only real relevant one for prisma is openssl: 
```
apt-get install -y openssl
```

**Comment by jonathanswenson** [comment]
> I can give it a shot running without tracing.

I'm not sure if there's anything else I need to do here, but I removed the `previewFeatures = ["tracing"]` from the prisma file, as well as the dependency on `@prisma/instrumentation`, and where we registered any instrumentation. Despite this, I'm still was running into the same kinds of errors.

**Comment by jonathanswenson** [comment]
It also reproduces with a trivial example: 

prisma/schema.prisma:
```
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model FooQuery {
  id        String   @id @db.Uuid
  createdAt DateTime @default(now()) @map("created_at")

  @@map("queries")
}
```

<details>
  <summary>src/index.ts</summary>

```
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient({
  log: [{
   emit: 'event',
   level: 'query',
 }],
})

const launchQuery = (prisma: PrismaClient) => {
  const promise = prisma.fooQuery.findMany({
    take: 10
  })

  promise.then((result: any) => {
    // do nothing.
  }).catch((e) => {
    console.log(e)
  })
}

setInterval(function(){ 
   console.log('calling it ', new Date())
   for (var i = 0; i < 15; i++) {
     launchQuery(prisma)
   }
}, 5000);
```

</details>

<details>
  <summary>package.json and tsconfig.json </summary>
package.json 
```
{
  "name": "test",
  "private": true,
  "license": "",
  "version": "0.0.1",
  "main": "./build/index.js",
  "types": "./build/index.d.ts",
  "scripts": {
    "build": "yarn build:prisma && yarn build:ts",
    "build:ts": "tsc",
    "build:prisma": "npx prisma generate",
    "clean": "rm -rf build"
  },
  "dependencies": {
    "@prisma/client": "4.13.0",
    "eslint": "8.38.0",
    "tslib": "2.5.0",
    "uuid": "9.0.0"
  },
  "devDependencies": {
    "prisma": "4.13.0",
    "typescript": "5.0.4"
  },
  "type": "module",
  "module": "2020",
  "exports": "./build/index.js"
}
```

tsconfig.json
```
{
  "include": ["src/index.ts"],
  "compilerOptions": {
    "declaration": true, 
    "esModuleInterop": true 
    "forceConsistentCasingInFileNames": true 
    "isolatedModules": true 
    "lib": ["ESNext.AsyncIterable"],
    "module": "ES2020" 
    "moduleResolution": "node" 
    "outDir": "build",
    "target": "ES2020" 
    "skipLibCheck": true,
    "strict": true 
    "strictPropertyInitialization": false,
  }
}
```
</details>

````
# yarn install
... omittted

# yarn build
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.13.0 | library) to ./node_modules/@prisma/client in 594ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

# node build/index.js
calling it  2023-05-18T22:10:44.064Z
calling it  2023-05-18T22:10:49.066Z
calling it  2023-05-18T22:10:54.066Z
calling it  2023-05-18T22:10:59.068Z
calling it  2023-05-18T22:11:04.068Z
calling it  2023-05-18T22:11:09.073Z
calling it  2023-05-18T22:11:14.074Z
PrismaClientKnownRequestError: 
Invalid `prisma.fooQuery.findMany()` invocation:


Server has closed the connection.
    at pn.handleRequestError (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:6477)
    at pn.handleAndLogRequestError (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:5907)
    at pn.request (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:5786)
    at async t._request (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:179:10484) {
  code: 'P1017',
  clientVersion: '4.13.0',
  meta: null
}
PrismaClientKnownRequestError: 
Invalid `prisma.fooQuery.findMany()` invocation:


Server has closed the connection.
    at pn.handleRequestError (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:6477)
    at pn.handleAndLogRequestError (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:5907)
    at pn.request (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:5786)
    at async t._request (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:179:10484) {
  code: 'P1017',
  clientVersion: '4.13.0',
  meta: null
}
^C
````

**Comment by jonathanswenson** [comment]
Managed to reproduce with a trivial database / schema newly generated from RDS with aurora postgres.

```
test=>CREATE TABLE QUERIES (id UUID, created_at timestamp);
CREATE TABLE
test=> \dt
          List of relations
 Schema |  Name   | Type  |  Owner   
--------+---------+-------+----------
 public | queries | table | postgres
(1 row)

test=> \d queries
                          Table "public.queries"
   Column   |            Type             | Collation | Nullable | Default 
------------+-----------------------------+-----------+----------+---------
 id         | uuid                        |           |          | 
 created_at | timestamp without time zone |           |          | 

test=>INSERT INTO QUERIES VALUES ('a791356e-72fe-4b90-9282-4cac4f30a2f4', '2023-05-19 18:28:19.238487'),
 ('9287b6a5-f9ee-434a-9df2-d72771c6e64d', '2023-05-19 18:28:20.387501'),
 ('e572db4c-db10-48ae-976d-06b7528c329f', '2023-05-19 18:28:20.931351'),
 ('e4b05ebd-bf33-4ac0-bc0c-01f029e6e031', '2023-05-19 18:28:21.398429'),
 ('907a8441-cee7-4b8e-a1bb-dc35cfb0dc4e', '2023-05-19 18:28:21.871213'),
 ('62628b8f-c88b-4bbe-a205-3e0d65bad60f', '2023-05-19 18:28:22.458357'),
 ('a7dc1d79-4e7a-4c31-b265-5afe79eb17df', '2023-05-19 18:28:23.405305'),
 ('52b89ad7-15cf-49d8-820a-c050fa62b78c', '2023-05-19 18:28:23.994473'),
 ('f73168be-aa80-48d2-bd48-8fa4970377c4', '2023-05-19 18:28:24.522251'),
 ('c3363a99-ca88-4310-9bb9-45337bc1e275', '2023-05-19 18:28:25.05747'),
 ('56050541-0b7b-4e89-a4ae-5c8fb3231b47', '2023-05-19 18:28:25.557365'),
 ('8e778a4a-fbd6-4b97-8aba-4ac0f2882ce6', '2023-05-19 18:28:26.096332'),
 ('777fafcd-2ddd-484a-b393-754c1c09e17c', '2023-05-19 18:28:26.62346'),
 ('6634bf9f-b0bc-4f62-9408-cf302616b58a', '2023-05-19 18:28:27.117248');
INSERT 0 14
```

Every time I ran the test scripts above it failed in a few rounds. 

Occasionally it failed in the first iteration and had a different error message: 
```
PrismaClientKnownRequestError: 
Invalid `prisma.fooQuery.findMany()` invocation:


Error opening a TLS connection: error:24067044:random number generator:rand_pool_add:internal error:crypto/rand/rand_lib.c:733:, error:24067044:random number generator:rand_pool_add:internal error:crypto/rand/rand_lib.c:733: (unable to get local issuer certificate)
    at pn.handleRequestError (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:6477)
    at pn.handleAndLogRequestError (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:5907)
    at pn.request (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:5786)
    at async t._request (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:179:10484) {
  code: 'P1011',
  clientVersion: '4.13.0',
  meta: {
    message: 'error:24067044:random number generator:rand_pool_add:internal error:crypto/rand/rand_lib.c:733:, error:24067044:random number generator:rand_pool_add:internal error:crypto/rand/rand_lib.c:733: (unable to get local issuer certificate)'
  }
}
```

and 

```
Can't reach database server at `<hostname>`:`5432`

Please make sure your database server is running at `<hostname>`:`5432`.
    at pn.handleRequestError (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:6477)
    at pn.handleAndLogRequestError (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:5907)
    at pn.request (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:176:5786)
    at async t._request (/app/test_prisma_two/node_modules/@prisma/client/runtime/library.js:179:10484) {
  code: 'P1001',
  clientVersion: '4.13.0',
  meta: {
    database_host: '<hostname>',
    database_port: 5432
  }
}
```
Notably in both of these cases it DID connect with the same credentials in later iterations of the same execution.

---------------------
Then to confirm it was only related to aurora postgres, I did the same schema / on a standard (non-aurora) RDS postgres and it did NOT reproduce after ~100 iterations (and I gave up and stopped it).

**Comment by jonathanswenson** [comment]
It does appear to be SSL related. When my database_url environment variable has `sslmode=verify-full` it fails relatively quickly. 

However, with `sslmode=disable` it does not fail.

**Comment by aqrln** [comment]
Hey everyone! We've just fixed another issue that is very likely to have had the same root cause as this one. Could you please check if using the dev build of Prisma and Prisma Client version `5.3.0-integration-arm-openssl-5-2-0.1` fixes this issue for you? (Make sure to install it as an exact dependency, i.e., without `^` before the package version in package.json, otherwise you might get a different integration build that doesn't include this fix).

**Comment by khalilsarwari** [comment]
@aqrln do you think this dev build will also fix the following, or is it unrelated?:

```
PrismaClientKnownRequestError:
Invalid `prisma.user.findMany()` invocation:

Error opening a TLS connection: OpenSSL error (self signed certificate in certificate chain)
    at cg.handleRequestError (node_modules/@prisma/client/runtime/binary.js:181:6732)
    at cg.handleAndLogRequestError (node_modules/@prisma/client/runtime/binary.js:181:6120)
    at cg.request (node_modules/@prisma/client/runtime/binary.js:181:5840)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async a (node_modules/@prisma/client/runtime/binary.js:186:9778)
  code: 'P1011',
  clientVersion: '5.2.0',
  meta: {
    message: 'OpenSSL error (self signed certificate in certificate chain)'
  }
}
```

**Comment by jonathanswenson** [comment]
@aqrln As far as I can tell, version `5.3.0-integration-arm-openssl-5-2-0.1` fixes what I was seeing. 

I have not tried the above isolated reproductions I provided before, but I was unable to get it to fail after deploying my full application with the above version and re-enabling SSL. 

And just to verify, I swapped back to the original version we were using along with re-enabling ssl and it failed in the same way that it used to.

So seems like this is 👍🏻

**Comment by aqrln** [comment]
@khalilsarwari 
> do you think this dev build will also fix the following issue which seems to happen randomly/inconsistently, or is it unrelated?

Since the error originates from the query engine, it's quite possible, but hard to tell for sure without testing. If the error is wrong (i.e. you're not actually using self-signed certificates) and only happens intermittently, then it's may likely be fixed as well. Generally, the problem we fixed could've triggered many kinds of subtle bugs, although for most affected people it just caused segfaults and aborts, incorrect behaviour without crashing is a bit more rare.

If you could test whether using Prisma and Prisma Client version `5.3.0-dev.42` or `5.3.0-integration-arm-openssl-5-2-0.1` (the second one is identical to 5.2.0 but includes this fix) fixes this problem for you, that would be great. Alternatively, you can wait until 5.3.0 is released and try it. If it doesn't fix this specific bug, please open a new issue so we could reproduce and investigate it!

**Comment by khalilsarwari** [comment]
I have tried `5.3.0-integration-arm-openssl-5-2-0.1` for the past day, and the intermittent self-signed issue has not appeared - so far so good; I'll follow up if it returns!
