### ISSUE TITLE
`update` doesn't signal that a record wasn't found when using `extendedWhereUnique`

### ISSUE THREAD

**Issue by 0xuhe** [prisma/prisma#19233]
### Bug description

I wanna got a status ready row from database by the following code, but it seems get status using row if I run this code by multi prisma clients. 

### How to reproduce

from hostA

```
node run.js
```

then run this script at same time

```
node run.js
```

### Expected behavior

It should return different status ready rows, but sometimes it return status using rows from different client.

### Prisma information

```prisma
// Add your schema.prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["multiSchema","extendedWhereUnique"]
}
```

```ts
// Add your code using Prisma Client

//  file: run.js
import prisma from "@/db/client";
async function getReadyProxy {
   while(true){
     const proxies = await prisma.proxy.findMany({
        where: {
          type: _type,
          port: params?.port,
          host: params?.host,
          id: params?.id,
          country: _country,
          status: _status,
        },
      });

      if (proxies.length === 0) {
        console.log("no proxy avaliable");
        await sleep(5e3);
        continue;
      }
      const proxy = proxies[Math.floor(Math.random() * proxies.length)];
      const result = await prisma.proxy.update({

        where: {
            id: proxy.id,
            version: proxy.version
        },

        data: {
          status: Status.USING,
          version: { increment: 1 }
        },
      });

      if (!result) {
        console.log("proxy is using");
        await sleep(5e3);
        continue;
      }
      return proxy;
   }
}

```

### Environment & setup

- OS: Windows
- Database: MariaDB
- Node.js version: 18.16

### Prisma Version

```
4.13
```

**Comment by aqrln** [comment]
@0xuhe could you please add the missing details to your reproduction so that it's possible to run it? Thank you!

**Comment by aqrln** [comment]
ping @0xuhe

**Comment by aqrln** [comment]
I tried taking OP's code snippet and turning it into something runnable, and this is what I got.

**prisma.schema**
```prisma
generator client {
  provider        = "prisma-client-js"
  output          = "./client"
  previewFeatures = ["extendedWhereUnique"]
}

datasource db {
  provider = "mysql"
  url      = env("TEST_MARIADB_URI")
}

enum Status {
  READY
  USING
}

model Proxy {
  id      Int    @id
  version Int
  status  Status
}
```

**seed.mjs**
```js
// @ts-check

import { PrismaClient, Status } from './prisma/client/index.js'

const prisma = new PrismaClient()

await prisma.proxy.deleteMany()

for (let i = 0; i < 10; i++) {
  await prisma.proxy.create({
    data: {
      id: i,
      version: 0,
      status: Status.READY,
    },
  })
}
```

**run.mjs**
```js
// @ts-check

import timers from 'node:timers/promises'
import { PrismaClient, Status } from './prisma/client/index.js'

const prisma = new PrismaClient()

while (true) {
  const proxies = await prisma.proxy.findMany({
    where: {
      status: Status.READY,
    },
  })

  if (proxies.length === 0) {
    console.error('no proxies available')
    break
  }

  const proxy = proxies[Math.floor(Math.random() * proxies.length)]
  const result = await prisma.proxy.update({
    where: {
      id: proxy.id,
      version: proxy.version,
    },
    data: {
      status: Status.USING,
      version: { increment: 1 },
    },
  })

  if (result === null) {
    console.error('proxy already unavailable, this client lost the race')
    continue
  }

  console.log(process.pid, result)
}
```

And run it with `node run.mjs &; node run.mjs`.

It does look like something weird is happening here.

```
63365 { id: 9, version: 1, status: 'USING' }
63366 { id: 9, version: 0, status: 'READY' }
63365 { id: 3, version: 1, status: 'USING' }
63366 { id: 6, version: 1, status: 'USING' }
PrismaClientKnownRequestError:
Invalid `prisma.proxy.update()` invocation:


An operation failed because it depends on one or more records that were required but not found. Record to update not found.
    at An.handleRequestError (/Users/aqrln/prisma/prisma/reproductions/gh-19233/prisma/client/runtime/library.js:174:6929)
    at An.handleAndLogRequestError (/Users/aqrln/prisma/prisma/reproductions/gh-19233/prisma/client/runtime/library.js:174:6358)
    at An.request (/Users/aqrln/prisma/prisma/reproductions/gh-19233/prisma/client/runtime/library.js:174:6237)
    at async file:///Users/aqrln/prisma/prisma/reproductions/gh-19233/run.mjs:23:18 {
  code: 'P2025',
  clientVersion: '0.0.0',
  meta: { cause: 'Record to update not found.' }
}

Node.js v20.2.0
63366 { id: 7, version: 1, status: 'USING' }
[1]  + exit 1     node run.mjs
63366 { id: 4, version: 1, status: 'USING' }
63366 { id: 1, version: 1, status: 'USING' }
63366 { id: 5, version: 1, status: 'USING' }
63366 { id: 2, version: 1, status: 'USING' }
63366 { id: 8, version: 1, status: 'USING' }
63366 { id: 0, version: 1, status: 'USING' }
```

**Comment by aqrln** [comment]
I only got the "Record to update not found" error once, but the old version of the record instead of `null` being returned to the second client in the `update` operation when they both try to grab the same row seems to be reproducing reliably. With that in mind, it should be possible to come up with a more minimal reproduction — I tried staying closer to the code snippet in the original post because I didn't know what to expect.

**Comment by aqrln** [comment]
Actually after the fresh look I can see a usage problem in the report and this repro: `update` operation never returns `null`, as you can see in the return type. As per the docs, it throws a "Record not found" error when the record to update wasn't found: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#return-type-4.

So the error I got once was actually correct, what's not correct is that I only got it once rather than every time one of the clients tried to update a record that didn't exist anymore. The same error reliably happens when the provided unique field does not match any record, and it would be the expected behaviour.

The workaround for you @0xuhe is to either check if the result is what you expect, or, better, use `updateMany` operation instead of `update` and check the number of returned records — if it's 0, then update failed.

**Comment by 0xuhe** [comment]
Thanks for your help @aqrln , I will check my code again

**Comment by 0xuhe** [comment]
I face the same issue again in latest version V5.3.1

```typescript
 async getProxyAvaliableFromDB(params?: AvaliableProxyParams) {
    while (true) {
      const _type = this.processParam(params?.type);
      const _country = this.processParam(params?.zone);
      const _status = params?.status ? params.status : Status.READY;
      // console.log(_type, _country, _status)
      const proxies = await prisma.proxy.findMany({
        where: {
          type: _type,
          port: params?.port,
          host: params?.host,
          id: params?.id,
          country: _country,
          status: _status,
        },
        select: {
          data: false,
          id: true,
          host: true,
          port: true,
          ip: true,
          type: true,
          country: true,
          username: true,
          password: true,
          version: true,
          note: true,
          proxy_url: true,
          protocol: true,
        },
      });

      if (proxies.length === 0) {
        console.log("no proxy avaliable");
        await sleep(5e3);
        continue;
      }
      const proxy = proxies[Math.floor(Math.random() * proxies.length)];
      const result = await prisma.proxy.update({
        where: {
          id_status: {
            id: proxy.id,
            // version: proxy.version,
            status: Status.READY,
          },
        },

        data: {
          status: Status.USING,
          // version: { increment: 1 },
        },
      });
      if (!result) {
        console.log("proxy is using");
        await sleep(5e3);
        continue;
      }
      return proxy;   
    }
  }
```
![Jietu20230930-003843@2x](https://github.com/prisma/prisma/assets/6814715/bf1e42e4-0f03-4b7e-b3b7-cc2f81ec617e)

As the image before, I run three runtime, the left one and middle one got the same row, but the right one throw error.

**Comment by 0xuhe** [comment]
This happens again on version field.
```typescript
  const result = await prisma.proxy.update({
        where: {
          id: proxy.id,
          AND: {
            version: proxy.version,
          },
          // version: proxy.version,
          // status: Status.READY,
        },

        data: {
          status: Status.USING,
          version: { increment: 1 },
        },

      });

```
![Jietu20230930-010004@2x](https://github.com/prisma/prisma/assets/6814715/d2485185-3cf5-470f-9ccc-a8ffcd31c6db)
