### ISSUE TITLE
Non-ASCII fields should not be commented out if they were enriched with `@map` information from the previous schema

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#19252]
### Bug description

`prisma db pull` comments out fields with non-ASCII characters even if they were enriched with `@map` information from the previous schema, and asks to provide a supported name even though it's already present.

Noticed this when responding to a user in https://github.com/prisma/prisma/issues/19236.

### How to reproduce

1. Use the following schema:
   ```prisma
   generator client {
     provider        = "prisma-client-js"
     output          = "../node_modules/.prisma/client"
   }
   
   datasource db {
     provider = "sqlite"
     url      = "file:./dev.db"
   }
   
   model Test {
     id Int @id @default(autoincrement())
     test String? @map("한글")
   }
   ```
2. Run `prisma db push`
3. Run `prisma db pull`
4. The following warnings are displayed:
   ```
   *** WARNING ***
   
   These fields were commented out because their names are currently not supported by Prisma. Please provide valid ones that match [a-zA-Z][a-zA-Z0-9_]* using the `@map` attribute:
     - Model: "Test", field(s): ["test"]
   
   These fields were enriched with `@map` information taken from the previous Prisma schema:
     - Model: "Test", field: "test"
   ```
   and the `Test` model is updated to this:
   ```prisma
   model Test {
     id Int @id @default(autoincrement())
     /// This field was commented out because of an invalid name. Please provide a valid one that matches [a-zA-Z][a-zA-Z0-9_]*
     // test String? @map("한글")
   }
   ```

### Expected behavior

Since the `@map` attribute was reused and the field already had a supported name, it should not have been commented out by `prisma db pull`, the comment above shouldn't have been added, and the warning in the terminal ("These fields were commented out because their names are currently not supported by Prisma") probably shouldn't have been printed (or should've had a different wording).

### Prisma information

see above

### Environment & setup

- OS: macOS
- Database: SQLite
- Node.js version: 20.1.0

### Prisma Version

main at 589e093a1749c13db5d0d5d9914a5e19ee36f417, 4.15.0-dev

**Comment by gmkseta** [comment]
Are there any updates regarding this issue? I want to use a table name in a language other than English, and I've encountered the following issue. When using the Prisma client, I get an error like this

The table `dbo.ììê¸°ê´` does not exist in the current database.
    at si.handleRequestError (/PATH/node_modules/@prisma/client/runtime/library.js:125:6817)
    at si.handleAndLogRequestError (/PATHnode_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/PATH/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/PATH/node_modules/@prisma/client/runtime/library.js:130:9805) {
  code: 'P2021',
  clientVersion: '5.8.1',
  meta: {
    modelName: 'Organization',
    table: 'dbo.ì\x9A\x94ì\x96\x91ê¸°ê´\x80'
  }
}

**Comment by janpio** [comment]
That is not related to this bug report, which is missing a reproduction. Please open a new bug issue and fill the issue template @gmkseta. Thank you.

**Comment by ludralph** [comment]
Closing this in favour of [#19307](https://github.com/prisma/prisma/issues/19307).
