### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'Could not retrieve alloc::string::String from Value'

### ISSUE THREAD

**Issue by godkillCK** [prisma/prisma#19342]
### Bug description

datasource db {
  provider = "mysql"
  url      = "mysql://xxxx:xxxxx@rm-xxxxxx.mysql.rds.aliyuncs.com:3306/xxxxx"
}

thread 'tokio-runtime-worker' panicked at 'Could not retrieve alloc::string::String from Value', 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: PANIC: Could not retrieve alloc::string::String from Value

What is wrong？

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
4.14.1
```

**Comment by aqrln** [comment]
Could you please provide more information so we could reproduce it? Does this error happen when using the Prisma Client in your application, or when running Prisma CLI commands such as `prisma migrate`? If it happens in the client, what query are you running?

Would you be able to provide a schema or a reproduction we could run?

**Comment by zxw8715** [comment]
error PrismaClientKnownRequestError:
Invalid `prisma.site.findMany()` invocation:

PANIC: Could not retrieve alloc::string::String from Value
    at Pn.handleRequestError (/server/node_modules/@prisma/client/runtime/library.js:171:6929)
    at Pn.handleAndLogRequestError (/server/node_modules/@prisma/client/runtime/library.js:171:6358)
    at /server/node_modules/@prisma/client/runtime/library.js:174:2908
    at async /server/node_modules/@prisma/client/runtime/library.js:174:3123
    at async t._executeRequest (/server/node_modules/@prisma/client/runtime/library.js:174:10621)
    at async siteService (file:///server/chunks/site.mjs:42:33)
    at async file:///server/chunks/site.mjs:81:18
    at async Object.handler (file:///server/node_modules/h3/dist/index.mjs:1247:19)
    at async toNodeHandle (file:///server/node_modules/h3/dist/index.mjs:1322:7)
    at async ufetch (file:///server/node_modules/unenv/runtime/fetch/index.mjs:9:17) {
  code: 'GenericFailure',
  clientVersion: '4.14.0',
  meta: undefined
{"code":"GenericFailure","clientVersion":"4.14.0"}

**Comment by kamto7** [comment]
save error

**Comment by jhd4tmr** [comment]
same error

**Comment by Weakky** [comment]
Hey folks @godkillCK, @kamto7, @jhd4tmr,

Could you please provide us with some more information so that we're able to reproduce your issue? For instance, your Prisma Schema and which command led to that error.

Thank you 🙏

**Comment by jhd4tmr** [comment]
@Weakky https://github.com/prisma/prisma/issues/19977

**Comment by jhd4tmr** [comment]
@Weakky For the same data, after I switch the mysql version, the error is still there, and other databases are fine. So I wonder if it might be a charset issue. I am using utf8mb4, utf8mb4_general_ci

**Comment by jharrell** [comment]
@jhd4tmr thanks for linking the other issues!

Do you have a reproduction (schema, commands, etc) that give this error? That will really help us move forward here.

**Comment by jhd4tmr** [comment]
@jharrell I tried it. I found a free 8.0 version of mysql, but found that after I copied the data in. No problem using prisma. It should still be related to the database version. the database I used is the production env of the company, which is old mysql 5.6.16-log and not easy to reproduction. All I can provide is a new issue with the above error message. https://github.com/prisma/prisma/issues/20596

**Comment by Jolg42** [comment]
Note: @jhd4tmr could reproduce this in Prisma 5.1.1, https://github.com/prisma/prisma/issues/20596
The mysql_common version matches what we have in the Cargo lock at https://github.com/prisma/prisma-engines/blob/e85ce3aca7f93a88980847499cf3e6bfee4b2b69/Cargo.lock#L2271

**Comment by Jolg42** [comment]
@jhd4tmr So you think this is related to your database version?
@godkillCK What's your MySQL version in your case?

It would be interesting/helpful if you could try a reproduction using a docker image, the oldest MySQL 5.6 still around in the official images is `5.6.17`, close enough for attempting reproduction I think.
https://hub.docker.com/layers/library/mysql/5.6.17/images/sha256-975493e932282469fac15ffb69aafca329387440baf9a516f46eb6eda49caf51?context=explore

Also, did you try using a more recent version of MySQL 5.6? (It looks like the most recent is `5.6.51`)
And finally, any idea what `-log` in `5.6.16-log` means?

**Comment by jhd4tmr** [comment]
@Jolg42 I think so, because I copied the data to the 8.0 version and it was no problem. But I remember that there was another version of mysql, and I copied it in, the same problem still occurred, so I thought it was a data type or a character type problem.
5.6.16-log is just an version of mysql. I think maybe cloud service providers in China like alibaba RDS used it more.

**Comment by jhd4tmr** [comment]
@Jolg42 "5.6.16-log" is a version of MySQL database. In this version number, "5.6.16" represents the major and minor version, while "-log" indicates that it's a version compiled with logging enabled. just chatgpted.

**Comment by zeahoo** [comment]
hello everyone, I got same error here

**Comment by Jolg42** [comment]
@zeahoo If you can help us to get a reproduction, that would help. For example by providing more infoarmation, like:
If you are using a Docker image, please share it with us.
Or maybe you are using alibabacloud? I have no idea how easy it is to create an account and start a database there.

**Comment by zeahoo** [comment]
> @zeahoo If you can help us to get a reproduction, that would help. For example by providing more infoarmation, like: If you are using a Docker image, please share it with us. Or maybe you are using alibabacloud? I have no idea how easy it is to create an account and start a database there.

yes!!!
first of all, I used my local mysql (macOS), It works EVERYTHING FINE!, and now I use alibabacloud version mysql, And got this error... That's too weird

**Comment by Moolan-d** [comment]
Same Error in mysql 5.6.16-log！  So  I downgraded the version of prisma It works

**Comment by Jolg42** [comment]
To all the people that get this error:
- which command are you running? 
- which version of Prisma is that happening?

**Comment by SeigeC** [comment]
same error

**Comment by janpio** [comment]
@SeigeC : 
- which command are you running?
- which version of Prisma is that happening?

**Comment by SeigeC** [comment]
> @SeigeC :
> 
> * which command are you running?
> * which version of Prisma is that happening?

Prisma version: 5.14.0
error message:
```
thread 'tokio-runtime-worker' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mysql_common-0.29.2/src/value/convert/mod.rs:175:23:
Could not retrieve alloc::string::String from Value
[nuxt] [request error] [unhandled] [500] 
Invalid `prisma.m_event.findFirst()` invocation:
PANIC: Could not retrieve alloc::string::String from Value

**Comment by SeigeC** [comment]
```
model m_event {
  id              Int     @id @default(autoincrement()) @main.UnsignedInt
  title           String  @main.VarChar(256)
  intro           String  @main.Text
  draw_start_time Int  @default(0)
  draw_end_time   Int  @default(0)
  start_time      Int  @default(0)
  end_time        Int  @default(0)
  extended_fields String? @main.Text
}

client.m_event.findFirst({
    where: {
      id: parseInt(id),
    },
    take: 100,
  })
}
```
There is no problem with MYSQL8, but the error will be reported in MYSQL5.6

**Comment by janpio** [comment]
Then this is very probably related to the data being returned from `m_event`. Can you maybe isolate it to one specific entry by playing with the pagination parameters of your query?

**Comment by SeigeC** [comment]
> Then this is very probably related to the data being returned from `m_event`. Can you maybe isolate it to one specific entry by playing with the pagination parameters of your query?

```
model m_event {
  id              Int     @id @default(autoincrement()) @main.UnsignedInt
  draw_start_time Int  @default(0)
  draw_end_time   Int  @default(0)
  start_time      Int  @default(0)
  end_time        Int  @default(0)
}
```
I tested it and it still doesn't work. It doesn't seem to have anything to do with m_event

**Comment by janpio** [comment]
How can it not be related to `m_event` if the error happens when you run a query against that model?

We need a reproduction, that includes Prisma Client query, Prisma Schema, and data that triggers this bug. Only then will we be able to confirm and hopefully fix it.

**Comment by jinker** [comment]
It has nothing to do with specific schema and invocation methods. The reason is that when the query engine initializes the database connection, it will query the socket variable. Turning off this option is sufficient by adding the parameter `prefer_socket=false`.

DATABASE_URL:
`mysql://{username}:{password}@{host}:{port}/{db}`
Change it to:
`mysql://{username}:{password}@{host}:{port}/{db}?prefer_socket=false`

Related Documentation: https://open.oceanbase.com/blog/15137753618

**Comment by leric** [comment]
@jinker It works, saved my day

P.S. This error happens when querying a Aliyun hosted mysql service, db host name end with "mysql.polardb.rds.aliyuncs.com", so it might accually be a PolarDB
