### ISSUE TITLE
+20,000 CSV insertions causing Error in connector

### ISSUE THREAD

**Issue by alexvilchis** [prisma/prisma#1936]
## Bug description
I am trying to insert records from a CSV file to my database using `prisma-client-js` and `csv-parser` but when I reach an insert quantity of around 20,000, console throws the following error for every subsequent `create`:
```
PrismaClientUnknownRequestError:
Invalid `prisma.patient.create()` invocation:

Error in connector: Error creating a database connection.
    at PrismaClientFetcher.request (/Users/alexrv99/Projects/positive-zero/ayzer-dental/ayzer-backend/node_modules/@prisma/client/runtime/index.js:1:47490)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## How to reproduce
I made a repository to reproduce this error which includes a dummy CSV file of 34,000 records. The file bug.ts is the script I'm using to load the rows to my database.

1. Clone repo (https://github.com/alexvilchis/prisma2-csv-bug)
2. `npm install`
3. `npm run generate`
4. Migrate `npx prisma2 migrate up --experimental`
5. `npm start`

## Expected behavior
Full insertion of all CSV records to my database. This means `# of csv rows` = `rows in database table` 

## Prisma information 
Repo should suffice.

## Environment & setup
- .env at `prisma/` file pointing to my database

- OS: MacOS Catalina
- Database: MySQL 8.0.18
- Prisma version: prisma2@2.0.0-preview024
- Node.js version: v12.16.1

### Update
Note that the inserted objects are not using any value derived from the CSV, which is strange.

**Comment by pantharshit00** [comment]
I was unable to reproduce this:

**Comment by pinedo98** [comment]
I have the same problem. At first I thought everything was working fine but if you wait there and don't kill the process you'll see the error, I think @pantharshit00 
![image](https://user-images.githubusercontent.com/29076160/77669728-d92ba280-6f4a-11ea-9ce8-cacb9647aa67.png)

And after a few seconds:
![image](https://user-images.githubusercontent.com/29076160/77669767-e779be80-6f4a-11ea-9bc8-85160bb24658.png)

**Comment by alexvilchis** [comment]
@pantharshit00 I'm also using my local MySQL database.

**Comment by pantharshit00** [comment]
@alexvilchis I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.

Also, try again with the latest version once.
