### ISSUE TITLE
Your schema.prisma1 could not be found, even when using webpack plugin

### ISSUE THREAD

**Issue by iduuck** [prisma/prisma#19522]
### Bug description

I am seeing the error for a Next.js monorepo in my code (yes, I have a monorepo), but I am also using the webpack plugin.

Next 13.4.3 here.

```
- error ../node_modules/.pnpm/@prisma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client/runtime/library.js (99:2633) @ new LibraryEngine
- error Error: Your schema.prisma1 could not be found, and we detected that you are using Next.js.
Find out why and learn how to fix this: https://pris.ly/d/schema-not-found-nextjs
    at new LibraryEngine (webpack-internal:///(sc_server)/../../node_modules/.pnpm/@prisma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client/runtime/library.js:7328:65)
    at t1.getEngine (webpack-internal:///(sc_server)/../../node_modules/.pnpm/@prisma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client/runtime/library.js:11842:79)
    at new PrismaClient (webpack-internal:///(sc_server)/../../node_modules/.pnpm/@prisma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client/runtime/library.js:11826:223)
    at eval (webpack-internal:///(sc_server)/../../packages/prisma/index.ts:13:33)
    at (sc_server)/../../packages/prisma/index.ts (/Users/nick/dev/bauhow-energy/apps/web/.next/server/app/(admin)/admin/[providerId]/system-settings/page.js:19876:1)
    at __webpack_require__ (/Users/nick/dev/bauhow-energy/apps/web/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/./src/server/auth.ts:9:78)
    at (sc_server)/./src/server/auth.ts (/Users/nick/dev/bauhow-energy/apps/web/.next/server/app/(admin)/admin/[providerId]/system-settings/page.js:7407:1)
    at __webpack_require__ (/Users/nick/dev/bauhow-energy/apps/web/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(sc_server)/./src/app/(admin)/admin/[providerId]/layout.tsx:11:70) {
  digest: undefined
}
```

### How to reproduce

Currently no reproduction, sorry. I am able to invite a contributor to our private repository.

### Expected behavior

I want prisma to just work. 

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["clientExtensions"]
}

generator kysely {
  provider = "prisma-kysely"
  output = "../../types"
  fileName = "types.ts"
  enumFileName = "enums.ts"
}

generator enum {
  provider = "prisma-enums"
  output = "."
  file = "enums.ts"
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}
```

### Environment & setup

- OS: macOS
- Database: PlanetScale
- Node.js version: v18.14.0

### Prisma Version

```
prisma                  : 4.12.0
@prisma/client          : 4.12.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at ../../node_modules/.pnpm/@prisma+engines@4.12.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7 (at ../../node_modules/.pnpm/@prisma+engines@4.12.0/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.12.0-67.659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Default Engines Hash    : 659ef412370fa3b41cd7bf6e94587c1dfb7f67e7
Studio                  : 0.483.0
Preview Features        : clientExtensions
```

**Comment by iduuck** [comment]
As a quick side note: I am not using the traditional `prisma/schema.prisma` path, but I have it directly beside my index.ts (which is exposing the prisma client for all other packages).

---

For now, I have fixed the issue by instantiating the prisma inside my packages one by one.

**Comment by felixSchl** [comment]
I have been battling with exactly the same problem and am hoping for a proper solution... but for now I just copied the schema file by hand into the .next folder:

```
grep -lR 'Prisma Client could not find' apps/web/.next | xargs dirname | xargs -I {} cp packages/core/prisma/schema.prisma {}/schema.prisma1
```

it's a pretty bad workflow but at least it unblocks me

**Comment by SSardorf** [comment]
I have exactly the same issue in my pnpm workspace

**Comment by divx-alisson-ninomiya** [comment]
Bumping this thread. It's almost October prisma dev team. Any updates?

**Comment by darkopetrovic** [comment]
I installed `@prisma/nextjs-monorepo-workaround-plugin`  since I saw the error below while building for production. 

```
Error: Your schema.prisma could not be found, and we detected that you are using Next.js.
Find out why and learn how to fix this: https://pris.ly/d/schema-not-found-nextjs
```

All good, but then I started to see the error below when I launch the development server:

```
PrismaClientInitializationError: Prisma Client could not find its `schema.prisma1`. This is likely caused by a bundling step, which leads to `schema.prisma1` not being copied near the resulting bundle.
```

A simple solution would be:

```js
if(process.NODE_ENV !== 'production') {
  config.plugins = [...config.plugins]
} else {
  config.plugins = [...config.plugins, new PrismaPlugin()]
}
```

**Comment by EKP529** [comment]
I'm also experiencing this issue. It's been a while, so I'm not sure if anyone has discovered any fixes as of late? I try to run a trpc API on my prod nextjs server and get this error every. single. time. It's a pretty big roadblock for me. I have a turbo monorepo with pnpm as the package manager and I also already have the workaround plugin in my next.config.js.
