### ISSUE TITLE
Jest throws timeout error when calling `prisma.$transaction()` + `jest.useFakeTimers()`

### ISSUE THREAD

**Issue by ranggarifqi** [prisma/prisma#19542]
### Bug description

Hi, i have this problem when i wanted to test my function.

jest throws `Exceeded timeout of 5000 ms for a hook.`

So, i tried a simpler approach to replicate this issue.

on the `beforeEach()` hook, i tried to call a simple `.$tranasction()`, like
```ts
beforeEach(async () => {
    jest.useFakeTimers().setSystemTime(new Date(2022, 10, 30)); 
    
    console.log('before exec $transaction');
    await prismaService.$transaction(async (tx) => {
      console.log('111');
      await tx.someTable.create({
        data: {
          name: 'zzzz test',
        },
      });
      console.log('222');
    });
})

```

and jest also throws the same error.

this is the full log. 
<details><summary>Full Log</summary>
<p>

```
> NODE_ENV=test dotenv -e .env.test -- jest --config=jest-e2e.config.json --runInBand --no-cache --verbose --detectOpenHandles $FILE

[21:33:8.307][emittery:subscribe][undefined] Event Name: test-file-start
	data: undefined
[21:33:8.308][emittery:emit][undefined] Event Name: Symbol(listenerAdded)
	data: {"eventName":"test-file-start"}
[21:33:8.309][emittery:subscribe][undefined] Event Name: test-file-success
	data: undefined
[21:33:8.309][emittery:emit][undefined] Event Name: Symbol(listenerAdded)
	data: {"eventName":"test-file-success"}
[21:33:8.309][emittery:subscribe][undefined] Event Name: test-file-failure
	data: undefined
[21:33:8.310][emittery:emit][undefined] Event Name: Symbol(listenerAdded)
	data: {"eventName":"test-file-failure"}
[21:33:8.310][emittery:subscribe][undefined] Event Name: test-case-result
	data: undefined
[21:33:8.310][emittery:emit][undefined] Event Name: Symbol(listenerAdded)
	data: {"eventName":"test-case-result"}
[21:33:8.312][emittery:emit][undefined] Event Name: test-file-start
	data: [{"context":{"config":{"automock":false,"cache":false,"cacheDirectory":"/private/var/folders/t_/0cqd5jsd45597731r_f4rkmh0000gn/T/jest_dx","clearMocks":false,"coveragePathIgnorePatterns":["/node_modules/"],"cwd":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be","detectLeaks":false,"detectOpenHandles":true,"errorOnDeprecated":false,"extensionsToTreatAsEsm":[],"fakeTimers":{"enableGlobally":false},"forceCoverageMatch":[],"globals":{},"haste":{"computeSha1":false,"enableSymlinks":false,"forceNodeFilesystemAPI":true,"throwOnModuleCollision":false},"id":"192ad5326b97091d869e11a9fa70935b","injectGlobals":true,"moduleDirectories":["node_modules"],"moduleFileExtensions":["js","json","ts"],"moduleNameMapper":[["src/(.*)","/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/$1"]],"modulePathIgnorePatterns":["/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/dist/"],"prettierPath":"prettier","resetMocks":false,"resetModules":false,"restoreMocks":false,"rootDir":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src","roots":["/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src"],"runner":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-runner/build/index.js","sandboxInjectedGlobals":[],"setupFiles":[],"setupFilesAfterEnv":[],"skipFilter":false,"slowTestThreshold":5,"snapshotSerializers":[],"testEnvironment":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-environment-node/build/index.js","testEnvironmentOptions":{},"testLocationInResults":false,"testMatch":[],"testPathIgnorePatterns":["/node_modules/"],"testRegex":["(/__tests__/.*|(\\.|/)(test))\\.[jt]sx?$"],"testRunner":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-circus/runner.js","transform":[["^.+\\.(t|j)s$","/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/ts-jest/dist/index.js",{}]],"transformIgnorePatterns":["/node_modules/","\\.pnp\\.[^\\/]+$"],"watchPathIgnorePatterns":[]},"hasteFS":{"_rootDir":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src","_files":{}},"moduleMap":{"duplicates":[],"map":[],"mocks":[],"rootDir":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src"},"resolver":{"_options":{"extensions":[".js",".json",".ts"],"hasCoreModules":true,"moduleDirectories":["node_modules"],"moduleNameMapper":[{"moduleName":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/$1","regex":{}}],"rootDir":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src"},"_moduleMap":{"duplicates":[],"map":[],"mocks":[],"rootDir":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src"},"_moduleIDCache":{},"_moduleNameCache":{},"_modulePathCache":{},"_supportsNativePlatform":false}},"path":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts"}]
  prisma:tryLoadEnv  Environment variables loaded from /Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/.env +0ms
  prisma:client  checkPlatformCaching:postinstall true +0ms
  prisma:client  checkPlatformCaching:ciName undefined +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/.env +-183d
  prisma:client  dirname /Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/prisma +0ms
  prisma:client  protocol graphql +0ms
  prisma:client  clientVersion 4.15.0 +0ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:engines:resolveEnginePath  enginePath /Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/.prisma/client/libquery_engine-darwin.dylib.node +0ms
  console.log
    before exec $transaction

      at Object.<anonymous> (common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts:49:13)

  prisma:client:libraryEngine  library starting +0ms
  console.log
    prisma:info Starting a postgresql pool with 17 connections.

      at Object.pc (../node_modules/@prisma/client/runtime/library.js:26:431)

  prisma:client:libraryEngine  library started +0ms
  console.log
    prisma:query BEGIN

      at Object.pc (../node_modules/@prisma/client/runtime/library.js:26:431)

  console.log
    111

      at common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts:51:15

  prisma:client  Prisma Client call: +0ms
  prisma:client  prisma.transactionType.create({
  data: {
    name: 'zzzz test'
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  createOneTransactionType(data: {
    name: "zzzz test"
  }) {
    name
    createdAt
    updatedAt
  }
}
 +0ms
[21:33:19.40][emittery:emit][undefined] Event Name: test-case-result
	data: ["/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts",{"ancestorTitles":["TransactionRepository -> create() - Integration Test"],"duration":5009,"failureDetails":[{"message":"thrown: \"Exceeded timeout of 5000 ms for a hook.\nUse jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.\""}],"failureMessages":["Error: thrown: \"Exceeded timeout of 5000 ms for a hook.\nUse jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.\"\n    at /Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts:24:3\n    at _dispatchDescribe (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-circus/build/index.js:105:26)\n    at describe (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-circus/build/index.js:60:5)\n    at Object.<anonymous> (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts:14:1)\n    at Runtime._execModule (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-runtime/build/index.js:1714:24)\n    at Runtime._loadModule (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-runtime/build/index.js:1223:12)\n    at Runtime.requireModule (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-runtime/build/index.js:1047:12)\n    at jestAdapter (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:89:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at runTestInternal (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-runner/build/runTest.js:411:16)"],"fullName":"TransactionRepository -> create() - Integration Test","invocations":1,"location":null,"numPassingAsserts":0,"retryReasons":[],"status":"failed","title":""}]

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "prisma:query ROLLBACK".

      at console.log (../node_modules/@jest/console/build/CustomConsole.js:172:10)
      at Object.pc (../node_modules/@prisma/client/runtime/library.js:26:431)
      at ../node_modules/@prisma/client/runtime/library.js:177:5763
      at EventEmitter.<anonymous> (../node_modules/@prisma/client/runtime/library.js:177:6303)
      at rr.logger (../node_modules/@prisma/client/runtime/library.js:108:1286)
      at ../node_modules/@prisma/client/runtime/library.js:108:950

[21:33:19.145][emittery:emit][undefined] Event Name: test-file-success
	data: [{"context":{"config":{"automock":false,"cache":false,"cacheDirectory":"/private/var/folders/t_/0cqd5jsd45597731r_f4rkmh0000gn/T/jest_dx","clearMocks":false,"coveragePathIgnorePatterns":["/node_modules/"],"cwd":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be","detectLeaks":false,"detectOpenHandles":true,"errorOnDeprecated":false,"extensionsToTreatAsEsm":[],"fakeTimers":{"enableGlobally":false},"forceCoverageMatch":[],"globals":{},"haste":{"computeSha1":false,"enableSymlinks":false,"forceNodeFilesystemAPI":true,"throwOnModuleCollision":false},"id":"192ad5326b97091d869e11a9fa70935b","injectGlobals":true,"moduleDirectories":["node_modules"],"moduleFileExtensions":["js","json","ts"],"moduleNameMapper":[["src/(.*)","/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/$1"]],"modulePathIgnorePatterns":["/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/dist/"],"prettierPath":"prettier","resetMocks":false,"resetModules":false,"restoreMocks":false,"rootDir":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src","roots":["/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src"],"runner":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-runner/build/index.js","sandboxInjectedGlobals":[],"setupFiles":[],"setupFilesAfterEnv":[],"skipFilter":false,"slowTestThreshold":5,"snapshotSerializers":[],"testEnvironment":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-environment-node/build/index.js","testEnvironmentOptions":{},"testLocationInResults":false,"testMatch":[],"testPathIgnorePatterns":["/node_modules/"],"testRegex":["(/__tests__/.*|(\\.|/)(test))\\.[jt]sx?$"],"testRunner":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-circus/runner.js","transform":[["^.+\\.(t|j)s$","/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/ts-jest/dist/index.js",{}]],"transformIgnorePatterns":["/node_modules/","\\.pnp\\.[^\\/]+$"],"watchPathIgnorePatterns":[]},"hasteFS":{"_rootDir":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src","_files":{}},"moduleMap":{"duplicates":[],"map":[],"mocks":[],"rootDir":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src"},"resolver":{"_options":{"extensions":[".js",".json",".ts"],"hasCoreModules":true,"moduleDirectories":["node_modules"],"moduleNameMapper":[{"moduleName":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/$1","regex":{}}],"rootDir":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src"},"_moduleMap":{"duplicates":[],"map":[],"mocks":[],"rootDir":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src"},"_moduleIDCache":{},"_moduleNameCache":{},"_modulePathCache":{},"_supportsNativePlatform":false}},"path":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts"},{"leaks":false,"numFailingTests":1,"numPassingTests":0,"numPendingTests":0,"numTodoTests":0,"openHandles":[],"perfStats":{"end":1685543599131,"runtime":10796,"slow":true,"start":1685543588335},"skipped":false,"snapshot":{"added":0,"fileDeleted":false,"matched":0,"unchecked":0,"uncheckedKeys":[],"unmatched":0,"updated":0},"testFilePath":"/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts","testResults":[{"ancestorTitles":["TransactionRepository -> create() - Integration Test"],"duration":5009,"failureDetails":[{"message":"thrown: \"Exceeded timeout of 5000 ms for a hook.\nUse jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.\""}],"failureMessages":["Error: thrown: \"Exceeded timeout of 5000 ms for a hook.\nUse jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.\"\n    at /Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts:24:3\n    at _dispatchDescribe (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-circus/build/index.js:105:26)\n    at describe (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-circus/build/index.js:60:5)\n    at Object.<anonymous> (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/src/common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts:14:1)\n    at Runtime._execModule (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-runtime/build/index.js:1714:24)\n    at Runtime._loadModule (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-runtime/build/index.js:1223:12)\n    at Runtime.requireModule (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-runtime/build/index.js:1047:12)\n    at jestAdapter (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:89:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at runTestInternal (/Users/ranggarifqipratama/Works/ranggarifqi/projects/money-manager/money-manager-be/node_modules/jest-runner/build/runTest.js:411:16)"],"fullName":"TransactionRepository -> create() - Integration Test","invocations":1,"location":null,"numPassingAsserts":0,"retryReasons":[],"status":"failed","title":""}],"failureMessage":"\u001b[1m\u001b[31m  \u001b[1m● \u001b[22m\u001b[1mTransactionRepository -> create() - Integration Test › \u001b[39m\u001b[22m\n\n    thrown: \"Exceeded timeout of 5000 ms for a hook.\n    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test.\"\n\u001b[2m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 22 |\u001b[39m   \u001b[36mconst\u001b[39m seeds\u001b[33m:\u001b[39m \u001b[33mDict\u001b[39m\u001b[33m<\u001b[39m\u001b[33many\u001b[39m\u001b[33m>\u001b[39m \u001b[33m=\u001b[39m {}\u001b[33m;\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 23 |\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[2m\u001b[39m\u001b[90m 24 |\u001b[39m   beforeEach(\u001b[36masync\u001b[39m () \u001b[33m=>\u001b[39m {\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m    |\u001b[39m   \u001b[31m\u001b[1m^\u001b[22m\u001b[2m\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 25 |\u001b[39m     jest\u001b[33m.\u001b[39museFakeTimers()\u001b[33m.\u001b[39msetSystemTime(\u001b[36mnew\u001b[39m \u001b[33mDate\u001b[39m(\u001b[35m2022\u001b[39m\u001b[33m,\u001b[39m \u001b[35m10\u001b[39m\u001b[33m,\u001b[39m \u001b[35m30\u001b[39m))\u001b[33m;\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 26 |\u001b[39m\u001b[0m\u001b[22m\n\u001b[2m    \u001b[0m \u001b[90m 27 |\u001b[39m     \u001b[36mconst\u001b[39m module\u001b[33m:\u001b[39m \u001b[33mTestingModule\u001b[39m \u001b[33m=\u001b[39m \u001b[36mawait\u001b[39m \u001b[33mTest\u001b[39m\u001b[33m.\u001b[39mcreateTestingModule({\u001b[0m\u001b[22m\n\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat \u001b[22m\u001b[2m\u001b[0m\u001b[36mcommon/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts\u001b[39m\u001b[0m\u001b[2m:24:3\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.<anonymous> (\u001b[22m\u001b[2m\u001b[0m\u001b[36mcommon/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts\u001b[39m\u001b[0m\u001b[2m:14:1)\u001b[22m\u001b[2m\u001b[22m\n"}]
 FAIL  src/common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts (10.796 s)
  TransactionRepository -> create() - Integration Test
    ✕  (5009 ms)

  ● TransactionRepository -> create() - Integration Test ›

    thrown: "Exceeded timeout of 5000 ms for a hook.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      22 |   const seeds: Dict<any> = {};
      23 |
    > 24 |   beforeEach(async () => {
         |   ^
      25 |     jest.useFakeTimers().setSystemTime(new Date(2022, 10, 30));
      26 |
      27 |     const module: TestingModule = await Test.createTestingModule({

      at common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts:24:3
      at Object.<anonymous> (common/repos/transaction/__tests__/transaction.prisma.repository.create.test.ts:14:1)

[21:33:19.152][emittery:unsubscribe][undefined] Event Name: test-file-start
	data: undefined
[21:33:19.153][emittery:emit][undefined] Event Name: Symbol(listenerRemoved)
	data: {"eventName":"test-file-start"}
[21:33:19.153][emittery:unsubscribe][undefined] Event Name: test-file-success
	data: undefined
[21:33:19.153][emittery:emit][undefined] Event Name: Symbol(listenerRemoved)
	data: {"eventName":"test-file-success"}
[21:33:19.153][emittery:unsubscribe][undefined] Event Name: test-file-failure
	data: undefined
[21:33:19.153][emittery:emit][undefined] Event Name: Symbol(listenerRemoved)
	data: {"eventName":"test-file-failure"}
[21:33:19.153][emittery:unsubscribe][undefined] Event Name: test-case-result
	data: undefined
[21:33:19.153][emittery:emit][undefined] Event Name: Symbol(listenerRemoved)
	data: {"eventName":"test-case-result"}
Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        10.872 s
```

</p>
</details> 

As you can see from the log, `console.log('222');` was never called.

But then, when i remove the `jest.useFakeTimers()`. The issue seems to goes away.

Is this a bug ? 

and how are we supposed to do when we want to mock the time ?

Thanks in advance 🙂 

### How to reproduce

1. Call `prisma.$transaction()` on your test file anywhere. And please use a real db connection. (so, not a unit test)
2. Call `jest.useFakeTimers()`
3. Run the test

### Expected behavior

idk, maybe jest shouldn't throws timeout error ?

### Prisma information

```prisma
// Add your schema.prisma
Can use any schema
```

```ts
beforeEach(async () => {
    jest.useFakeTimers().setSystemTime(new Date(2022, 10, 30)); 
    
    console.log('before exec $transaction');
    await prismaService.$transaction(async (tx) => {
      console.log('111');
      await tx.someTable.create({
        data: {
          name: 'zzzz test',
        },
      });
      console.log('222');
    });
})

```

or

```ts
beforeEach(async () => {
    jest.useFakeTimers().setSystemTime(new Date(2022, 10, 30)); 
    
    console.log('before exec $transaction');
    await prismaService.$transaction([
        ....
    ]);
})

```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v16.17.0

### Prisma Version

```
4.15.0
```

**Comment by nahidakbar** [comment]
I've observed this as well. Prisma client 4.13.0. It is working fine in other repos where I am not using fake timers for tests.

**Comment by SeraphinLCK** [comment]
I got the same error trying to mock system time with Jest. Pretty annoying for cases where time is an important side effect in tests. 

Working fine with empty transaction so I guess it is a concurrency issue between them, concurrency management mechanism might not be waterproof to system time mocking

**Comment by ekowalsk** [comment]
@ranggarifqi  For me it worked with
```typescript
jest.useFakeTimers({ doNotFake: ['nextTick', 'setImmediate'] })
```

**Comment by jkomyno** [comment]
Closed as a duplicate of https://github.com/prisma/prisma/issues/7424.
