### ISSUE TITLE
PrismaClientKnownRequestError PANIC: Could not retrieve alloc::string::String from Value

### ISSUE THREAD

**Issue by zxw8715** [prisma/prisma#19573]
### Bug description

error PrismaClientKnownRequestError:
Invalid `prisma.site.findMany()` invocation:

PANIC: Could not retrieve alloc::string::String from Value
    at Pn.handleRequestError (/server/node_modules/@prisma/client/runtime/library.js:171:6929)
    at Pn.handleAndLogRequestError (/server/node_modules/@prisma/client/runtime/library.js:171:6358)
    at /server/node_modules/@prisma/client/runtime/library.js:174:2908
    at async /server/node_modules/@prisma/client/runtime/library.js:174:3123
    at async t._executeRequest (/server/node_modules/@prisma/client/runtime/library.js:174:10621)
    at async siteService (file:///server/chunks/site.mjs:42:33)
    at async file:///server/chunks/site.mjs:81:18
    at async Object.handler (file:///server/node_modules/h3/dist/index.mjs:1247:19)
    at async toNodeHandle (file:///server/node_modules/h3/dist/index.mjs:1322:7)
    at async ufetch (file:///server/node_modules/unenv/runtime/fetch/index.mjs:9:17) {
  code: 'GenericFailure',
  clientVersion: '4.14.0',
  meta: undefined

{"code":"GenericFailure","clientVersion":"4.14.0"}

### Prisma information

```prisma
datasource db {
  provider = "mysql"
  url =  "mysql://xxx:xxx@xxxx:xxxx/xxxx"
}

model xl_pc_site{
  id Int @id @default(autoincrement())
  name String @db.VarChar(100)
  url String @db.VarChar(200)
  state Int? @default(0)
  type String @db.VarChar(20)
}
```

```ts
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native","darwin","debian-openssl-1.0.x","debian-openssl-1.1.x","debian-openssl-3.0.x"]
}
```

### Environment & setup

- OS: linux
- Database: mysql
- Node.js version: 18.16.0

### Prisma Version

```
 prisma                  : 4.14.0
@prisma/client          : 4.14.0
Current platform  :Ubuntu
```

**Comment by petradonka** [comment]
Hello @zxw8715, could you help us with the details outlined above? We'll need this info to reproduce and address the issue. Thank you!

**Comment by jharrell** [comment]
Hi @zxw8715 (et al), we don't have enough information to continue here so are going to close. If you have this issue (or something similar) drop a comment and we'll re-open.

Thank you for your time!

**Comment by Moolan-d** [comment]
Same Error in mysql ！  So  I downgraded the version of prisma
