### ISSUE TITLE
Unicode character in JSON value seems to break foreign key relationships

### ISSUE THREAD

**Issue by mattcasey** [prisma/prisma#19620]
### Bug description

When I try to insert the unicode character `\udf9f️` into a JSON column, Prisma throws an error about a foreign key relationship. It seems to get schizophrenic about how I am trying to connect the models. It seems really bizarre, but I haven't found a workaround and it's important we can capture all types of characters in the JSON, where we store user content. Let me know if I can help any further.

### How to reproduce

Create two models in the example below and include the unicode character `\udf9f️` somewhere in the value of the JSON column.

### Expected behavior

I expect the insert to work and connect the page diff correctly to the page model.

### Prisma information

```prisma

model Page {
  id                  String            @id @default(uuid()) @db.Uuid
}

model PageDiff {
  data      Json
  pageId    String   @db.Uuid
  page      Page?    @relation(fields: [pageId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  version   Int

  @@unique([pageId, version])
  @@index([pageId])
}

```
Either approach triggers an error:
```ts

const page = await prisma.page.create({ data: { version: 0 } });

// Throws error: Unknown argument `pageId`. Did you mean `page`? Available options are listed in green.
await prisma.pageDiff.create({
  data: {
    pageId: page.id,
    data: {
       text: '\udf9f️'
    }
  }
});

// Throws error: Argument `pageId` is missing.
await prisma.pageDiff.create({
  data: {
    page: {
       connect: {
          id: page.id
       }
    },
    data: {
       text: '\udf9f️'
    }
  }
});
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v20.1.0

### Prisma Version

```
prisma                  : 4.13.0
@prisma/client          : 4.13.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a (at node_modules/@prisma/engines/migration-engine-darwin)
Format Wasm             : @prisma/prisma-fmt-wasm 4.13.0-50.1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Default Engines Hash    : 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Studio                  : 0.484.0
```

**Comment by Jolg42** [comment]
I could reproduce without any relation in our latest dev version `5.3.0-dev.6`

```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient();

  await prisma.something.create({
    data: {
      jsonData: {
        something: "\udf9f️",
      },
    },
  });

  prisma.$disconnect();
}

main();
```

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Something {
  id       String @id @default(uuid()) @db.Uuid
  jsonData Json
}
```

Errors with
```
PrismaClientKnownRequestError: 
Invalid `prisma.something.create()` invocation in
/Users/j42/Repros/19620/main.ts:6:26

  3 async function main() {
  4   const prisma = new PrismaClient();
  5 
→ 6   await prisma.something.create(
lone leading surrogate in hex escape at line 1 column 107
    at vn.handleRequestError (/Users/j42/Repros/19620/node_modules/@prisma/client/runtime/library.js:123:6730)
    at vn.handleAndLogRequestError (/Users/j42/Repros/19620/node_modules/@prisma/client/runtime/library.js:123:6119)
    at vn.request (/Users/j42/Repros/19620/node_modules/@prisma/client/runtime/library.js:123:5839)
    at l (/Users/j42/Repros/19620/node_modules/@prisma/client/runtime/library.js:128:9763)
    at main (/Users/j42/Repros/19620/main.ts:6:3)
```

Debug logs
```
  prisma:tryLoadEnv  Environment variables not found at null +0ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/j42/Repros/19620/prisma/.env +1ms
  prisma:client  checkPlatformCaching:postinstall undefined +0ms
  prisma:client  checkPlatformCaching:ciName undefined +0ms
  prisma:tryLoadEnv  Environment variables not found at null +1ms
  prisma:tryLoadEnv  Environment variables loaded from /Users/j42/Repros/19620/prisma/.env +0ms
  prisma:client  dirname /Users/j42/Repros/19620/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /Users/j42/Repros/19620/prisma +0ms
  prisma:client  clientVersion 5.3.0-dev.6 +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client  Prisma Client call: +2ms
  prisma:client  prisma.something.create({
  data: {
    jsonData: {
      something: "\udf9f️"
    }
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  {
  "modelName": "Something",
  "action": "createOne",
  "query": {
    "arguments": {
      "data": {
        "jsonData": {
          "something": "\udf9f️"
        }
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +1ms
  prisma:client:engines:resolveEnginePath  enginePath /Users/j42/Repros/19620/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:client:libraryEngine  library starting +3ms
  prisma:client:libraryEngine  library started +24ms
  prisma:client:request_handler  [Error: lone leading surrogate in hex escape at line 1 column 107] {
  code: 'InvalidArg'
} +0ms
```

**Comment by maltesa** [comment]
We're seeing a similar issue when updating JSONB fields. This happens quite often in production.

```
PrismaClientUnknownRequestError

Invalid `prisma.iteration.update()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "22P05", message: "unsupported Unicode escape sequence", severity: "ERROR", detail: Some("\\u0000 cannot be converted to text."), column: None, hint: None }), transient: false })
```

**Comment by ihadabs** [comment]
Same here using Prisma 7.2.0
`DriverAdapterError: unsupported Unicode escape sequence`
