### ISSUE TITLE
Invalid `prisma.user.findUnique()` invocation when deploying on Vercel

### ISSUE THREAD

**Issue by mart1d4** [prisma/prisma#19723]
### Bug description

When deploying a Nextjs project on Vercel using prisma (with MongoDB), some requests will fail with the following error:

```txt
PrismaClientKnownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Raw query failed. Code: `unknown`. Message: `unexpected end of file`
    at An.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:174:6929)
    at An.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:174:6358)
    at An.request (/var/task/node_modules/@prisma/client/runtime/library.js:174:6237)
    at async POST (/var/task/.next/server/app/api/auth/login/route.js:150:22)
    at async /var/task/.next/server/chunks/95.js:3094:37 {
  code: 'P2010',
  clientVersion: '4.15.0',
  meta: { code: 'unknown', message: 'unexpected end of file' }
}
```

I've only tested it with `findUnique` and `findFirst`.
This only triggers in production, everything works fine in developement.

I could show you *where* this error comes from, although it appears to be happening from any request.

```jsx
const user = await prisma.user.findUnique({
    where: {
        // username is just a string
        username: username,
    },
});

// Querying a user using its refresh token leads to the same error
const user = await prisma.user.findUnique({
    where: {
        refreshToken: token,
    },
});
```

Here is some of the User schema:

```prisma
model User {
  id           String     @id @default(auto()) @map("_id") @db.ObjectId
  username     String     @unique
  email        String?
  avatar       String     @default("blue")
  banner       String?
  accentColor  String?
  description  String?
  password     String
  refreshToken String?    @unique

  guildIds String[] @db.ObjectId
  guilds   Guild[]  @relation("UserGuild", fields: [guildIds], references: [id])

  channelIds String[]  @db.ObjectId
  channels   Channel[] @relation("UserChannel", fields: [channelIds], references: [id])
}
```

### How to reproduce

-

### Expected behavior

Expecting the query to work.

### Prisma information

-

### Environment & setup

- OS: Windows
- Database: MongoDB
- Node.js version: v19.3.0

### Prisma Version

```
4.14.0
```

**Comment by janpio** [comment]
Interesting mismatch:

> I've only tested it with `findUnique` and `findFirst`.

vs.

> ```
> Raw query failed.
> ```

**Comment by Druue** [comment]
> Interesting mismatch:
> 
> > I've only tested it with `findUnique` and `findFirst`.
> 
> vs.
> 
> > `Raw query failed.`
> > (From the error msg)

weird 🤔 
<img width="339" alt="image" src="https://github.com/prisma/prisma/assets/29753584/48e7aeac-12ee-4e01-9d24-14fa42e29cee">

**Comment by Jolg42** [comment]
Probably related to https://github.com/prisma/prisma/issues/11968 or https://github.com/prisma/prisma/issues/16517 / https://github.com/prisma/prisma/issues/12728

@mart1d4 could you verify that you have allow-listed the IP of your server in the Network Access section on MongoDB Atlas? (Vercel instructions are suboptimal as you'll need to allow connections from all IP addresses, see https://vercel.com/guides/how-to-allowlist-deployment-ip-address)
Also, do you have `&ssl=true` in your connection string?

**Comment by mart1d4** [comment]
> Probably related to #11968 or #16517 / #12728
> 
> @mart1d4 could you verify that you have allow-listed the IP of your server in the Network Access section on MongoDB Atlas? (Vercel instructions are suboptimal as you'll need to allow connections from all IP addresses, see https://vercel.com/guides/how-to-allowlist-deployment-ip-address) Also, do you have `&ssl=true` in your connection string?

Adding `&ssl=true` indeed made the trick. I did stumble upon #11968, however the error being displayed as "Unknown" made me think it was related to something else.
Thanks for your help!

**Comment by camaerart** [comment]
sometimes, you get this bug because your web app uses services that need serverless functions, because Prisma does not (directly) support this kind of, you have to make a connection to your db using the extension Prisma Accelerate,. check out  more: https://www.prisma.io/data-platform/accelerate

**Comment by janpio** [comment]
If that was the case for the problem, you would get a different error message @camaerart that would give indications in that direction. The problem above really was releated to the connection string.

**Comment by Eonsinde** [comment]
the issue is with the connection string as stated by Janpio. I used this `blahblahblah.mongodb.net/main?retryWrites=true&w=majority` and the error went away. Simply added the retryWrites=true and on

**Comment by camaerart** [comment]
> ```
> Invalid `prisma.user.findUnique()` invocation:
> ```

From my understanding, bugs can happen in several files, so you can get an invocation error in a Prisma function that calls different files, so different error messages for devs with the invocation error as the bug related, I came here because I browse the web using my error message

**Comment by Elozino** [comment]
I was able to fix mine by adding my IP address to my MongoDB network access. I don't know how it got removed but ensure your cluster is running and the IP address you are using to interact is correct.

**Comment by Bharat-kasera** [comment]
for me when i changed my internet network it worked and doesnt show any error.

**Comment by camaerart** [comment]
I notice that building with --no-engine solves this bug, which I guess is related to the request speed (?)

**Comment by Nzanzu-Lwanzo** [comment]
> #11968

Thank you, bro ! This fixed the bug for me !
