### ISSUE TITLE
`disconnect` on `.update()` returns a `P2035` error code with 1 element

### ISSUE THREAD

**Issue by nullndr** [prisma/prisma#19736]
### Bug description

The `disconnect` operation field on `.update()` method results in:

```
PrismaClientKnownRequestError:
Invalid `db_helper_1.db.audience.update()` invocation in
.../jobs/out/models/audiences.js:19:36

  16 };
  17 exports.connectCustomersToAudience = connectCustomersToAudience;
  18 const disconnectCustomersFromAudience = async ({ audienceId, customersId, }) => {
→ 19     return db_helper_1.db.audience.update(
Assertion violation on the database: `too many bind variables in prepared statement, expected maximum of 32767, received 32768`
    at An.handleRequestError (.../node_modules/@prisma/client/runtime/library.js:174:6929)
    at An.handleAndLogRequestError (.../node_modules/@prisma/client/runtime/library.js:174:6358)
    at An.request (.../node_modules/@prisma/client/runtime/library.js:174:6237)
    at async bruh (.../jobs/out/index.js:84:5) {
  code: 'P2035',
  clientVersion: '4.15.0',
  meta: {
    database_error: 'too many bind variables in prepared statement, expected maximum of 32767, received 32768'
  }
}
```

### How to reproduce

Use `disconnect` in the `.update()` method to disconnect some records. 

With the `DEBUG="*"` variable, there is some output about the call:

```
  prisma:client  Prisma Client call: +706ms
  prisma:client  prisma.audience.update({
  where: {
    id: 'cliu3rn7z0001fwn5963n9s15'
  },
  data: {
    customers: {
      disconnect: [
        {
          id: 'clionpeff005efwc1qf8eofr3'
        }
      ]
    }
  }
}) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  updateOneAudience(
    where: {
      id: "cliu3rn7z0001fwn5963n9s15"
    }
    data: {
      customers: {
        disconnect: [
          {
            id: "clionpeff005efwc1qf8eofr3"
          }
        ]
      }
    }
  ) {
    id
    description
    status
    filters
    name
    createdAt
    updatedAt
    deletedAt
    shopifyDomain
  }
}
```

### Expected behavior

The `customers` should be disconnected from the `audience`.

### Prisma information

```prisma
model Customer {
  id                    String    @id @default(cuid())
  audience              Audience[]
}

model Audience {
  id          String         @id @default(cuid())
  customers   Customer[]
}
```

```ts
export type CustomersToAudience = {
  audienceId: string;
  customersId: string[];
};

export const disconnectCustomersFromAudience = async ({
  audienceId,
  customersId,
}: CustomersToAudience) => {
  return db.audience.update({
    where: {
      id: audienceId,
    },
    data: {
      customers: {
        disconnect: customersId.map((id) => ({ id })),
      },
    },
  });
};
```

### Environment & setup

- OS: Arch Linux
- Database: PostgreSQL (on Docker)
- Node.js version: v20.3.0

### Prisma Version

```
prisma                  : 4.15.0
@prisma/client          : 4.15.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 8fbc245156db7124f997f4cecdd8d1219e360944 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 8fbc245156db7124f997f4cecdd8d1219e360944 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Format Wasm             : @prisma/prisma-fmt-wasm 4.15.0-28.8fbc245156db7124f997f4cecdd8d1219e360944
Default Engines Hash    : 8fbc245156db7124f997f4cecdd8d1219e360944
Studio                  : 0.484.0
```

**Comment by janpio** [comment]
Can you please turn on query logging (https://pris.ly/d/logging) and see what query it is trying to execute before and when it crashes?

**Comment by nullndr** [comment]
I tried to log the queries but it logged just a bunch of `BEGIN`, `SELECT` and `COMMIT`. The problematic `UPDATE` was not being printed.

I just tried again and the query works with no change in the configuration 🤔. I'll do other tests.
