### ISSUE TITLE
Transaction based Prisma does not respect `findFirst` invariants

### ISSUE THREAD

**Issue by axejintao** [prisma/prisma#19834]
### Bug description

When utilizing the transaction API `findFirst` does not behave as expected. 

Some snippets - 

Top Level
```
  await this.prisma.$transaction(
        async (prisma) => {
          const vaultSyncInfo = {
            prisma,
            chain,
            vault,
          };
          // aggregate some data
          // call this next function
        });
```

```
const existingInteraction = await prisma.vaultInteraction.findFirst({
  where: {
    hash,
  },
});
```

The `prisma` referenced in the second block is the prisma being passed in. `this.prisma` is a pristine prisma client, no ties to any transaction. 

When calling `findFirst` on the pristine client - this works as expected. When utilizing the transaction client - the call fails. 

```
catalyst_worker         |   311 let persistedInteractions = 0;
catalyst_worker         |   312 for (const interactionEvent of interactionEvents) {
catalyst_worker         |   313     const { hash, who, assets, amount, interactionType } = interactionEvent;
catalyst_worker         | → 314     const existingInteraction = await prisma.vaultInteraction.findFirst(
catalyst_worker         | An operation failed because it depends on one or more records that were required but not found. Expected a record, found none.
catalyst_worker         |     at Kr.handleRequestError (/usr/catalyst-worker/node_modules/@prisma/client/runtime/library.js:163:19499)
catalyst_worker         |     at Kr.handleAndLogRequestError (/usr/catalyst-worker/node_modules/@prisma/client/runtime/library.js:163:19031)
catalyst_worker         |     at Kr.request (/usr/catalyst-worker/node_modules/@prisma/client/runtime/library.js:163:18869)
catalyst_worker         |     at async PrismaService._request (/usr/catalyst-worker/node_modules/@prisma/client/runtime/library.js:173:9714)
catalyst_worker         |     at async VaultsJobsService.handleVaultInteractions (/usr/catalyst-worker/build/vaults/vaults.jobs.service.js:314:41)
catalyst_worker         |     at async Promise.all (index 0)
catalyst_worker         |     at async prisma.$transaction.timeout (/usr/catalyst-worker/build/vaults/vaults.jobs.service.js:96:17)
catalyst_worker         |     at async Proxy._transactionWithCallback (/usr/catalyst-worker/node_modules/@prisma/client/runtime/library.js:173:8643)
catalyst_worker         |     at async VaultsJobsService.handleVaultQuery (/usr/catalyst-worker/build/vaults/vaults.jobs.service.js:90:13)
catalyst_worker         |     at async VaultsJobsController.indexPoolEvent (/usr/catalyst-worker/build/vaults/vaults.jobs.controller.js:44:13) {
catalyst_worker         |   code: 'P2025',
catalyst_worker         |   clientVersion: '4.10.1',
catalyst_worker         |   meta: { cause: 'Expected a record, found none.' },
catalyst_worker         |   batchRequestIdx: 2
catalyst_worker         | }
```

### How to reproduce

- Create a tx
- Look up some item that doesn't exist using the prisma tx client

### Expected behavior

Error should not be thrown

### Prisma information

```prisma
model VaultInteraction {
  id              Int                  @id @default(autoincrement())
  createdAt       DateTime             @default(now())
  updatedAt       DateTime             @updatedAt
  hash            String               @db.VarChar
  who             Account              @relation(fields: [whoId], references: [id])
  whoId           Int
  assets          TokenBalance[]
  amount          Decimal
  value           Decimal
  interactionType VaultInteractionType
  vault           Vault                @relation(fields: [vaultId], references: [id])
  vaultId         Int

  @@unique([vaultId, hash], name: "uq_pool_interactions_on_vault_id_and_hash")
  @@index([vaultId], name: "index_vault_interactions_on_vault_id")
  @@index([whoId], name: "index_vault_interactions_on_who_id")
  @@map("vault_interactions")
}```

```ts
const { hash, who, assets, amount, interactionType } = interactionEvent;

const existingInteraction = await prisma.vaultInteraction.findFirst({
  where: {
    hash,
  },
});
```

### Environment & setup

- OS: macOS
- Database: Postgres
- Node.js version: 18.15.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.10.1
@prisma/client          : 4.10.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli aead147aa326ccb985dcfed5b065b4fdabd44b19 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.10.1-1.80b351cc7c06d352abe81be19b8a89e9c6b7c110
Default Engines Hash    : aead147aa326ccb985dcfed5b065b4fdabd44b19
Studio                  : 0.481.0
```

**Comment by axejintao** [comment]
@SevInf 

I had many concurrent operations going during these calls - since serializing the db invocations and upgrading to the latest I can no longer reproduce this.
