### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libs/datamodel/core/src/validator/validate.rs:178:29

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1988]
```prisma
model Post {
  id       Int  @id
  // 1
  author   User @relation(fields: [authorId], references: [id])
  // 2 (relation scalar field)
  authorId Int
}

model User {
  id    Int    @id
  // 3
  posts Post[]
}




model Post {
  id         Int
  categories Category[]  // 1
}

model Category {
  id    Int    @id
  posts Post[]  // 1
}
```

leads to

```
C:\Users\Jan\Documents\prisma-examples\typescript\script>prisma2 validate --schema prisma/schema2.prisma
Error: Schema parsing
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libs/datamodel/core/src/validator/validate.rs:178:29
stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src\libstd\sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src\libstd\sys_common/backtrace.rs:59
   4: core::fmt::write
             at src\libcore\fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src\libstd\io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src\libstd\sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src\libstd\sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src\libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src\libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src\libstd/panicking.rs:472
  11: rust_begin_unwind
             at src\libstd/panicking.rs:380
  12: core::panicking::panic_fmt
             at src\libcore/panicking.rs:85
  13: core::panicking::panic
             at src\libcore/panicking.rs:52
  14: datamodel::validator::validate::Validator::validate
  15: datamodel::validator::validation_pipeline::ValidationPipeline::validate
  16: datamodel::parse_datamodel_internal
  17: datamodel::parse_datamodel_and_ignore_env_errors
  18: prisma::opt::PrismaOpt::datamodel
  19: <prisma::cli::CliCommand as core::convert::TryFrom<&prisma::opt::PrismaOpt>>::try_from
  20: prisma::main::{{closure}}
  21: <std::future::GenFuture<T> as core::future::future::Future>::poll
  22: tokio::runtime::enter::Enter::block_on
  23: tokio::runtime::context::enter
  24: tokio::runtime::handle::Handle::enter
  25: prisma::main
  26: std::rt::lang_start::{{closure}}
  27: std::rt::lang_start_internal::{{closure}}
             at src\libstd/rt.rs:52
  28: std::panicking::try::do_call
             at src\libstd/panicking.rs:305
  29: __rust_maybe_catch_panic
             at src\libpanic_unwind/lib.rs:86
  30: std::panicking::try
             at src\libstd/panicking.rs:281
  31: std::panic::catch_unwind
             at src\libstd/panic.rs:394
  32: std::rt::lang_start_internal
             at src\libstd/rt.rs:51
  33: main
  34: _tmainCRTStartup
  35: mainCRTStartup
  36: sqlite3GenerateConstraintChecks
  37: sqlite3GenerateConstraintChecks
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I know this schema is stupid of course, but it should still fail with an error (and underline in VSCode) instead of crashing the formatter.

**Comment by pantharshit00** [comment]
I can confirm this.

Version used:
```
@prisma/cli          : 2.0.0-alpha.1000
Current platform     : darwin
Query Engine         : prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/harshit/.nvm/versions/node/v12.15.0/lib/node_modules/@prisma/cli/introspection-engine-darwin)
```

**Comment by pantharshit00** [comment]
This still crashes the validator in the latest stable version `2.3.0`:
![image](https://user-images.githubusercontent.com/22195362/88386128-641f8b00-cdcd-11ea-8382-8a21433788f1.png)


I am going to candidate this..

**Comment by mavilein** [comment]
Internal Note: The issue is probably that there are two models with the name `Post`.

**Comment by mavilein** [comment]
This is indeed causes by the duplicated models. `validate.rs` relies on this not being possible. We have checks for this in `precheck.rs` which should catch this and run before `validate.rs`. Somehow they are not working right now.
