### ISSUE TITLE
Validation error message for schema with missing relation scalar field (old syntax)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#1989]
Take this SQLite:
```sql
CREATE TABLE "Post" ( 
    "author" INTEGER REFERENCES "User"(id) ON DELETE SET NULL, 
    "content" TEXT , 
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
    "published" BOOLEAN NOT NULL DEFAULT false , 
    "title" TEXT NOT NULL
)

CREATE TABLE "User" ( 
	"email" TEXT NOT NULL UNIQUE, 
	"id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	"name" TEXT
)
```

Since alpha 978 this would be introspected as:
```prisma
model Post {
  author    Int?
  content   String?
  id        Int     @default(autoincrement()) @id
  published Boolean @default(false)
  title     String
  User      User?   @relation(fields: [author], references: [id])
}

model User {
  email String  @unique
  id    Int     @default(autoincrement()) @id
  name  String?
  Post  Post[]
}
```

But before it was represented as this "old" schema:
```prisma
model Post {
  id        Int     @default(autoincrement()) @id
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(references: [id])
}

model User {
  id    Int     @default(autoincrement()) @id
  email String  @unique
  name  String?
  posts Post[]
}
```
Note the missing `User` relation field in `Post`, as `author` is not a relation scalar field. Schemas like this exist in many projects, including our examples.

`prisma2 validate` is happy with that old schema:
```
C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs>prisma2 validate
The schema at C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs\prisma\schema.prisma is valid �🚀
```

`generate` also works. But if I try to run this simple script:

```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()

prisma.post.findMany({
    include: { author: true },
}).then(res => {
    console.log(res)
})
```

I get this error:

```
C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs>node index.js
(node:14096) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.post.findMany()` invocation in
C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs\index.js:5:13

  1 const { PrismaClient } = require('@prisma/client')
  2
  3 const prisma = new PrismaClient()
  4
→ 5 prisma.post.findMany(

Expected at most 1 item for 'author', got 2
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs\node_modules\@prisma\client\runtime\index.js:1:51487)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:14096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

or with `DEBUG=*`:

```
C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs>node index.js
  prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: 'C:\\Users\\Jan\\Documents\\prisma-examples\\typescript\\rest-nextjs\\prisma',
  prisma-client     debug: false,
  prisma-client     datamodelPath: 'C:\\Users\\Jan\\Documents\\prisma-examples\\typescript\\rest-nextjs\\node_modules\\@prisma\\client\\schema.prisma',
  prisma-client     prismaPath: undefined,
  prisma-client     datasources: [ [Object] ],
  prisma-client     generator: {
  prisma-client       name: 'client',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: 'C:\\Users\\Jan\\Documents\\prisma-examples\\typescript\\rest-nextjs\\node_modules\\@prisma\\client',
  prisma-client       binaryTargets: [],
  prisma-client       config: {}
  prisma-client     },
  prisma-client     showColors: false,
  prisma-client     logLevel: undefined,
  prisma-client     logQueries: undefined,
  prisma-client     env: {},
  prisma-client     flags: []
  prisma-client   }
  prisma-client } +0ms
  prisma-client Prisma Client call: +106ms
  prisma-client prisma.post.findMany({
  prisma-client   include: {
  prisma-client     author: true
  prisma-client   }
  prisma-client }) +16ms
  prisma-client Generated request: +34ms
  prisma-client query {
  prisma-client   findManyPost {
  prisma-client     id
  prisma-client     title
  prisma-client     content
  prisma-client     published
  prisma-client     author {
  prisma-client       id
  prisma-client       email
  prisma-client       name
  prisma-client     }
  prisma-client   }
  prisma-client }
  prisma-client  +1ms
  getos { platform: 'win32', libssl: undefined } +0ms
  engine {
  engine   PRISMA_DML_PATH: 'C:\\Users\\Jan\\Documents\\prisma-examples\\typescript\\rest-nextjs\\node_modules\\@prisma\\client\\schema.prisma',
  engine   PORT: '50804',
  engine   RUST_BACKTRACE: '1',
  engine   RUST_LOG: 'info',
  engine   OVERWRITE_DATASOURCES: '[{"name":"db","url":"file:C:\\\\Users\\\\Jan\\\\Documents\\\\prisma-examples\\\\typescript\\\\rest-nextjs\\\\prisma\\\\dev.db"}]'
  engine } +0ms
  engine {
  engine   cwd: 'C:\\Users\\Jan\\Documents\\prisma-examples\\typescript\\rest-nextjs\\prisma'
  engine } +37ms
  engine { flags: [ '--enable-raw-queries' ] } +36ms
  engine stderr Printing to stderr for debugging +47ms
  engine stderr Listening on 127.0.0.1:50804 +2ms
  engine stdout {
  timestamp: 'Mar 29 00:24:04.804',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a sqlite pool with 9 connections.' }
} +14ms
  engine stdout {
  timestamp: 'Mar 29 00:24:04.813',
  level: 'INFO',
  target: 'prisma::server',
  fields: {
    message: 'Started http server on 127.0.0.1:50804',
    'log.target': 'prisma::server',
    'log.module_path': 'prisma::server',
    'log.file': 'query-engine/prisma/src/server.rs',
    'log.line': 109
  }
} +18ms
  engine {
  engine   error: PrismaClientUnknownRequestError: Expected at most 1 item for 'author', got 2
  engine       at NodeEngine.graphQLToJSError (C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs\node_modules\@prisma\client\runtime\index.js:1:18853)
  engine       at C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs\node_modules\@prisma\client\runtime\index.js:1:16340
  engine       at processTicksAndRejections (internal/process/task_queues.js:85:5)
  engine       at Dataloader.loader (C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs\node_modules\@prisma\client\runtime\index.js:1:50649)
  engine } +67ms
  printStack callsite Error
    at Object.s [as Post] (C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs\node_modules\@prisma\client\runtime\index.js:1:48553)
    at Object.n.<computed> [as findMany] (C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs\node_modules\@prisma\client\runtime\index.js:1:50179)
    at Object.<anonymous> (C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs\index.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11 +0ms
(node:1536) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.post.findMany()` invocation in
C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs\index.js:5:13

  1 const { PrismaClient } = require('@prisma/client')
  2
  3 const prisma = new PrismaClient()
  4
→ 5 prisma.post.findMany(

Expected at most 1 item for 'author', got 2
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma-examples\typescript\rest-nextjs\node_modules\@prisma\client\runtime\index.js:1:51487)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:1536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It would be awesome if Validation could already catch this and tell the user that `fields` pointing to a relation scalar field is missing.

---

Everything works fine if I run `introspect`, `generate`, and replace `author` with `User` in my code snippet 💕

**Comment by mavilein** [comment]
This is fixed in: https://github.com/prisma/prisma-engines/pull/624
