### ISSUE TITLE
Prisma generate with custom specify output

### ISSUE THREAD

**Issue by Ily-1606** [prisma/prisma#19980]
### Bug description

Can't run (import issue) from custom specify output folder

```
root_project\node_modules\ts-node\src\index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
prisma/generated/central/index.js:18:3 - error TS18042: 'Debug' is a type and cannot be imported in JavaScript files. Use 'import("...").Debug' in a JSDoc type annotation.

18   Debug,
     ~~~~~
prisma/generated/central/index.js:30:1 - error TS2740: Type 'typeof Prisma' is missing the following properties from type 'typeof Prisma': TransactionIsolationLevel, Table_adsScalarFieldEnum, Table_catScalarFieldEnum, Table_commentScalarFieldEnum, and 26 more.

30 exports.Prisma = Prisma
   ~~~~~~~~~~~~~~
prisma/generated/central/index.js:515:38 - error TS2345: Argument of type '{ generator: { name: string; provider: { fromEnvVar: null; value: string; }; output: { value: string; fromEnvVar: null; }; config: { engineType: string; }; binaryTargets: { fromEnvVar: null; value: string; native: boolean; }[]; previewFeatures: never[]; isCustomOutput: boolean; }; ... 7 more ...; postinstall: boolea...' is not assignable to parameter of type 'GetPrismaClientConfig'.
  Type '{ generator: { name: string; provider: { fromEnvVar: null; value: string; }; output: { value: string; fromEnvVar: null; }; config: { engineType: string; }; binaryTargets: { fromEnvVar: null; value: string; native: boolean; }[]; previewFeatures: never[]; isCustomOutput: boolean; }; ... 7 more ...; postinstall: boolea...' is not assignable to type '{ runtimeDataModel?: undefined; document: Document; } & { generator?: GeneratorConfig; sqliteDatasourceOverrides?: DatasourceOverwrite[]; ... 16 more ...; isBundled?: boolean; }'.
    Property 'document' is missing in type '{ generator: { name: string; provider: { fromEnvVar: null; value: string; }; output: { value: string; fromEnvVar: null; }; config: { engineType: string; }; binaryTargets: { fromEnvVar: null; value: string; native: boolean; }[]; previewFeatures: never[]; isCustomOutput: boolean; }; ... 7 more ...; postinstall: boolea...' but required in type '{ runtimeDataModel?: undefined; document: Document; }'.

515 const PrismaClient = getPrismaClient(config)
                                         ~~~~~~

  prisma/generated/central/runtime/index.d.ts:1514:5
    1514     document: DMMF.Document;
             ~~~~~~~~
    'document' is declared here.

    at createTSError (root_project\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (root_project\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (root_project\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (root_project\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (root_project\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Object.require.extensions.<computed> [as .js] (root_project\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Function.Module._load (node:internal/modules/cjs/loader:838:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29) {
  diagnosticCodes: [ 18042, 2740, 2345 ]
}
```

### How to reproduce

1. Create schema prisma with custom output
2. Run `npx prisma db push --schema=./prisma/schema.prisma`
3. Import output generated into application code
4. Run application code with ts-node
5. See errors

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "./generated/central"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_CENTRAL")
}
```

```ts
import { PrismaClient as PrismaClientCentral } from "../../prisma/generated/central"
const prismaCentral = new PrismaClientCentral()
```

### Environment & setup

- OS: Windows 11
- Database: MariaDB and Postgres same error
- Node.js version: v18.8.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.16.1
@prisma/client          : 4.16.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.0-66.b20ead4d3ab9e78ac112966e242ded703f4a052c
Default Engines Hash    : b20ead4d3ab9e78ac112966e242ded703f4a052c
Studio                  : 0.484.0
```

**Comment by Ily-1606** [comment]
- More information:
+ Application executed by command: `npx ts-node my_application.ts`
- ts-node version: `v10.9.1`

**Comment by Ily-1606** [comment]
I'm disabled checkJs in tsconfig.json, and it has working.
```
{
  "compilerOptions": {
    "checkJs": false
  }
}
```

**Comment by janpio** [comment]
Which Typescript version are you using that you get this error with?

**Comment by Ily-1606** [comment]
The tsc version is: `5.1.3`
But I think this error not relate to typescript version.

**Comment by Jolg42** [comment]
@Ily-1606 this version had some issues, probably unrelated to your issue, but I would recommend upgrading to `5.1.6` in general.

From what I understand, you have a JavaScript project and maybe JSDoc comments? So you are using ts-node to type check it?

I think you could use `include` in your tsconfig to define the location of your source files instead of disabling `checkJs`:
```
  "include": [
    "src/**/*.js",
  ]
```

**Comment by Jolg42** [comment]
I think it's interesting to reopen this, so we try it out for a reproduction when we can.

**Comment by achadee** [comment]
If you are trying to run seed via turbo repo, this config worked for me

```package.json
  "scripts": {
    ...
    "db:seed": "prisma db seed",
  },
  "prisma": {
    "seed": "ts-node --transpile-only prisma/seed/seed.ts"
  }
```

**Comment by joshuakcockrell** [comment]
Excluding `src/generated` (my custom location for my Prisma client) worked for me

```ts
// tsconfig.json
{
  "compilerOptions": {
    "exclude": ["src/generated", "node_modules"]
  }
}
```
