### ISSUE TITLE
[MSSQL] Microsoft SQL Server type `@db.VarChar(x)` throws `QueryError Encoding: unspported encoding` on select

### ISSUE THREAD

**Issue by joonatassouza** [prisma/prisma#19982]
### Bug description

I'm trying to connect prisma orm to an existent mssql database.

Everything works fine till I try to select a varchar(x) column.
It work with other types including nvarchar.

```
2023-06-27T14:09:56.753Z prisma:tryLoadEnv  Environment variables loaded from D:\repos\todos\ctn-voucher\.env
2023-06-27T14:09:56.755Z prisma:client  checkPlatformCaching:postinstall false
2023-06-27T14:09:56.755Z prisma:client  checkPlatformCaching:ciName undefined
2023-06-27T14:09:56.756Z prisma:tryLoadEnv  Environment variables loaded from D:\repos\todos\ctn-voucher\.env
2023-06-27T14:09:56.756Z prisma:client  dirname D:\repos\todos\ctn-voucher\node_modules\.prisma\client
2023-06-27T14:09:56.756Z prisma:client  relativePath ../../../prisma
2023-06-27T14:09:56.756Z prisma:client  cwd D:\repos\todos\ctn-voucher\prisma
2023-06-27T14:09:56.756Z prisma:client  protocol graphql
2023-06-27T14:09:56.756Z prisma:client  clientVersion 4.16.1
2023-06-27T14:09:56.757Z prisma:client  clientEngineType library
2023-06-27T14:09:56.757Z prisma:client:libraryEngine  internalSetup
2023-06-27T14:09:56.762Z prisma:client:engines:resolveEnginePath  enginePath D:\repos\todos\ctn-voucher\node_modules\.prisma\client\query_engine-windows.dll.node
2023-06-27T14:09:56.763Z prisma:client:libraryEngine  library starting
prisma:info Starting a mssql pool with 13 connections.
prisma:info Performing a TLS handshake
prisma:warn Trusting the server certificate without validation.
prisma:info TLS handshake successful
prisma:warn Turning TLS off after a login. All traffic from here on is not encrypted.
prisma:info Database change from 'DATABASE_NAME' to 'master'
2023-06-27T14:09:57.184Z prisma:client:libraryEngine  library started
prisma:info Changed database context to 'DATABASE_NAME'.
prisma:info SQL collation changed to None
prisma:info Microsoft SQL Server version 2735734797
prisma:info Packet size change from '4096' to '4096'
2023-06-27T14:09:57.212Z prisma:client  Prisma Client call:
2023-06-27T14:09:57.213Z prisma:client  prisma.voucher.findFirst({})
2023-06-27T14:09:57.213Z prisma:client  Generated request:
2023-06-27T14:09:57.213Z prisma:client  query {
  findFirstVoucher {
    id
    identificador
  }
}

2023-06-27T14:09:57.213Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
prisma:query SELECT [dbo].[VOUCHER].[ID_VOUCHER], [dbo].[VOUCHER].[IDENTIFICADOR] FROM [dbo].[VOUCHER] WHERE 1=1 ORDER BY 1 OFFSET @P1 ROWS FETCH NEXT @P2 ROWS ONLY
2023-06-27T14:09:57.336Z prisma:client:request_handler  PrismaClientUnknownRequestError: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Encoding("encoding: unspported encoding (LCID: 0x409, sort ID: 42)")), transient: false })
    at Gs (D:\repos\todos\ctn-voucher\node_modules\@prisma\client\runtime\library.js:31:9067)
    at ir.buildQueryError (D:\repos\todos\ctn-voucher\node_modules\@prisma\client\runtime\library.js:109:903)
    at ir.request (D:\repos\todos\ctn-voucher\node_modules\@prisma\client\runtime\library.js:108:4165)
    at async Object.singleLoader (D:\repos\todos\ctn-voucher\node_modules\@prisma\client\runtime\library.js:174:5661)
    at async Rn.request (D:\repos\todos\ctn-voucher\node_modules\@prisma\client\runtime\library.js:174:6182) {
  clientVersion: '4.16.1'
}
(λ: ctn-vouchers-get-by-country-and-identification) RequestId: 4effe746-13cc-4bbc-9f30-a9207f05dbea  Duration: 704.73 ms  Billed Duration: 705 ms
prisma:error
Invalid `prisma_1.prisma.voucher.findFirst()` invocation in
D:\repos\todos\ctn-voucher\.build\src\infra\repositories\prisma\VouchersRepository.js:52:60

  49 return __awaiter(this, void 0, void 0, function* () {
  50     if (country !== 'BR')
  51         throw new Error(`country ${country} Not implemented`);
→ 52     const vouchers = yield prisma_1.prisma.voucher.findFirst(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Encoding("encoding: unspported encoding (LCID: 0x409, sort ID: 42)")), transient: false })
```

### How to reproduce

Model a table with a column typed Varchar(x)
Try to select a column varchar

It occurs as well with rawquery throwing "Invalid query"

### Expected behavior

Returns data type VarChar(x)

### Prisma information

```prisma

model Voucher {
  id            Int       @id @map("ID_VOUCHER")
  identificador String    @map("IDENTIFICADOR") @db.VarChar(100)

 @@map("VOUCHER")
}
```

```ts
const voucher = await prisma.voucher.findFirst();
```

### Environment & setup

- OS: Windows | wsl2
- Database: SQL Server
- Node.js version: 16

### Prisma Version

```
4.16.1
```

**Comment by jkomyno** [comment]
Hi @joonatassouza, could you please share what's the collation used in your database and in your `Voucher` table?
Thanks.

**Comment by joonatassouza** [comment]
Collation: SQL_Latin1_General_CP850_CI_AS
Version: Microsoft SQL Server 2016 (SP1-GDR) (KB4505219) - 13.0.4259.0 (X64)   Jun 15 2019 19:20:12


![image](https://github.com/prisma/prisma/assets/14007034/62f006e9-b972-431b-8458-49c526a261d9)
![image](https://github.com/prisma/prisma/assets/14007034/a83225ce-d1c5-46a8-a60e-ea7fbccdf3ed)

**Comment by janpio** [comment]
Does this error only happen with the existing data in the table, or also if you create a new empty database and migrate the database schema and then add some data with Prisma (or manually, or Prisma Studio)?

**Comment by joonatassouza** [comment]
With the new database locally it works (i've just recreated one table cuz I dont have access to database's backups)

**Comment by janpio** [comment]
That means that the _data_ in the table is throwing Prisma off. Can you identify the first item it would find and see if anything is weird about that row?

**Comment by jkomyno** [comment]
Hey @joonatassouza, I've also noticed that you're on SQL Server 2016.
However, Prisma only provides support for SQL Server 2017 and beyond (see [docs](https://www.prisma.io/docs/reference/database-reference/supported-databases)).

We encourage you to upgrade your database if possible and try again. Until then, we'll close this issue. Please let us know if the issue still persists on that version! Thanks.

**Comment by ThomasMulcahy** [comment]
Hello,

I am also having the same issue as the OP. My SQL Server version is 2019.

![image](https://github.com/prisma/prisma/assets/38696974/99ed4475-eab0-4fae-9453-96c6d7ae0583)

It seems that Prisma does not like the SQL_Latin1_General_CP850_CI_AS collation type.

**Comment by janpio** [comment]
This has now been reproduced in the issue that @RobertCZ created: https://github.com/prisma/prisma/issues/22166#issuecomment-2129503522 Please make sure to subscribe over there if you are interested in updates. Thanks.
