### ISSUE TITLE
Cannot use ObjectId()s in `findRaw`

### ISSUE THREAD

**Issue by domharrington** [prisma/prisma#20008]
### Bug description

With a fresh install of Prisma, and a simple schema, I cannot use the mongodb ObjectId constructor in any of the [raw query methods](https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#raw-queries-with-mongodb). No data is returned when using them. 

If I turn on profiling in the mongodb shell (using `db.setProfilingLevel(2)`) then run the script below, it outputs with this (keys omitted for brevity):

```json
{
	"op" : "query",
	"ns" : "prisma-mongodb-run-command.User",
	"command" : {
		"find" : "User",
		"filter" : {
			"_id" : "649d848c1355833f9323a566"
		},
		"$db" : "prisma-mongodb-run-command"
	},
	"nreturned" : 0
}
```

If I run the `runCommand` in the mongo shell directly, like so:

```sh
db.runCommand({ find: 'User', filter: { _id: new ObjectId("649d848c1355833f9323a566") }})
```

And check the profiler again:

```json
{
	"op" : "query",
	"ns" : "prisma-mongodb-run-command.User",
	"command" : {
		"find" : "User",
		"filter" : {
			"_id" : ObjectId("649d848c1355833f9323a566")
		},
		"$db" : "prisma-mongodb-run-command"
	},
	"nreturned" : 1
}
```

Note that `command.filter._id` is correctly wrapped in an ObjectId constructor and is not just a String type. I hope I'm just doing something silly here... 

### How to reproduce

1. Upsert a User with a fixed email address to guarantee that user exists (schema included further down) 
2. Perform a regular `findMany()` query to return it and get the id value
3. Perform a `findRaw()`, passing in the previous id as an ObjectId so that mongodb can recognise it
4. Observer that no data is returned for the query

### Expected behavior

The data should be returned for that user. I've also observed similar behaviour for `$runCommandRaw` when trying to issue a delete by _id as well, so I suspect the same issue here is present there too.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
  id    String @id @default(auto()) @map("_id") @db.ObjectId
  email String @unique
}
```

```ts
import { PrismaClient } from '@prisma/client'
import { ObjectId } from 'mongodb'

const prisma = new PrismaClient()

async function main() {
  const user = { email: 'test@example.com' };
  await prisma.user.upsert({ where: user, create: user, update: user });
  const foundUser = await prisma.user.findMany();
  console.log(foundUser[0]);

  console.log(await prisma.user.findRaw({ filter: { _id: new ObjectId(foundUser[0].id) }}))
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```

Output when running this:

```
{ id: '649d848c1355833f9323a566', email: 'test@example.com' }
[]
```

### Environment & setup

- OS: macOS 13.3.1
- Database: MongoDB
- Node.js version: v16.20.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 4.16.1
@prisma/client          : 4.16.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli b20ead4d3ab9e78ac112966e242ded703f4a052c (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.0-66.b20ead4d3ab9e78ac112966e242ded703f4a052c
Default Engines Hash    : b20ead4d3ab9e78ac112966e242ded703f4a052c
Studio                  : 0.484.0
```

**Comment by Jolg42** [comment]
Could you share the logs when setting this env var `DEBUG=*` like `DEBUG=* command` in your terminal?

And also, try the following query:
```
    await prisma.user.findRaw({
        filter: {
            _id: { $eq: { $oid: foundUser[0].id } },
        },
    })
```

**Comment by domharrington** [comment]
Sure! This is the output from that command with `DEBUG=*` (i also removed my console.logs to not pollute the logs):

```sh
$ DEBUG=* node index.js
  prisma:tryLoadEnv  Environment variables loaded from /private/tmp/prisma-mongodb-run-command/.env +0ms
  prisma:client  checkPlatformCaching:postinstall false +0ms
  prisma:client  checkPlatformCaching:ciName undefined +0ms
  prisma:tryLoadEnv  Environment variables loaded from /private/tmp/prisma-mongodb-run-command/.env +49ms
  prisma:client  dirname /private/tmp/prisma-mongodb-run-command/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /private/tmp/prisma-mongodb-run-command/prisma +0ms
  prisma:client  protocol graphql +0ms
  prisma:client  clientVersion 4.16.1 +0ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:engines:resolveEnginePath  enginePath /private/tmp/prisma-mongodb-run-command/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node +0ms
  prisma:client:libraryEngine  library starting +3ms
  prisma:client:libraryEngine  library started +14ms
  prisma:client  Prisma Client call: +22ms
  prisma:client  prisma.user.upsert({
  where: {
    email: 'test@example.com'
  },
  create: {
    email: 'test@example.com'
  },
  update: {
    email: 'test@example.com'
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  upsertOneUser(
    where: {
      email: "test@example.com"
    }
    create: {
      email: "test@example.com"
    }
    update: {
      email: "test@example.com"
    }
  ) {
    id
    email
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +5ms
  prisma:client  Prisma Client call: +16ms
  prisma:client  prisma.user.findMany(undefined) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findManyUser {
    id
    email
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +15ms
  prisma:client  Prisma Client call: +1ms
TypeError: Cannot convert a Symbol value to a string
    at Array.join (<anonymous>)
    at Object.transformLine (/private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:119:368)
    at /private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:118:1318
    at Array.map (<anonymous>)
    at i (/private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:118:1022)
    at /private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:118:1179
    at Array.map (<anonymous>)
    at i (/private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:118:1022)
    at /private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:118:1179
    at Array.map (<anonymous>) {
  clientVersion: '4.16.1'
}
  prisma:client:libraryEngine  library stopping +8ms
  prisma:client:libraryEngine  library stopped +0ms
  prisma:client:libraryEngine:exitHooks  exit event received: 1 +0ms
```

Does seem like the ObjectId in the findRaw call is causing that error in the debug logs:

```js
TypeError: Cannot convert a Symbol value to a string
    at Array.join (<anonymous>)
    at Object.transformLine (/private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:119:368)
    at /private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:118:1318
    at Array.map (<anonymous>)
    at i (/private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:118:1022)
    at /private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:118:1179
    at Array.map (<anonymous>)
    at i (/private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:118:1022)
    at /private/tmp/prisma-mongodb-run-command/node_modules/@prisma/client/runtime/library.js:118:1179
    at Array.map (<anonymous>)
```

**Comment by domharrington** [comment]
Can also confirm switching it to:

```js
filter: {
    _id: { $eq: { $oid: foundUser[0].id } },
}
```

Does the trick and finds the user as expected:

```js
$ node index.js
{ id: '649d848c1355833f9323a566', email: 'test@example.com' }
[
  {
    _id: { '$oid': '649d848c1355833f9323a566' },
    email: 'test@example.com'
  }
]
```

I'm guessing this is a bug in the code that's parsing the findRaw filter, and it's trying to call `ObjectId().toString()` when it should instead be converting it to `{ $eq: { $oid: ObjectId().toString() } }`?

Happy to send a PR for this if the code is in a state that will allow me to do so, and if that sounds about right 👍

**Comment by Jolg42** [comment]
Thanks for the update 🙌🏼 

I'm not sure what needs to be fixed at the moment, I think someone needs to take a look at https://github.com/prisma/prisma/blob/eebd33fc6608ae9de96f1be7f7f0abb8a1911f8d/packages/client/src/runtime/core/jsonProtocol/serializeJsonQuery.ts#L237-L252 and most likely check what happens inside `serializeArgumentsValue()`

Some tests for `findRaw` can be found here https://github.com/prisma/prisma/blob/eebd33fc6608ae9de96f1be7f7f0abb8a1911f8d/packages/client/src/__tests__/integration/happy/blog-env-mongo/test.ts#L232

Feel free to take a look, though I'm not sure if I can provide more help than that at the moment

**Comment by domharrington** [comment]
Yeah or perhaps it's something to do with the `context.nestArgument(String(i))` part, which would presumably call ObjectId.toString()
