### ISSUE TITLE
If you stop Prisma, the Rust process will continue to work, and you will not be able to start more than a certain number of Rust processes.

### ISSUE THREAD

**Issue by KohnoseLami** [prisma/prisma#20006]
### Discussed in https://github.com/prisma/prisma/discussions/19389

<div type='discussions-op-text'>

<sup>Originally posted by **KohnoseLami** May 23, 2023</sup>
I initially developed on Windows and it worked fine on Windows, but when I deployed it to Linux, the following error occurred:

```ts
- event compiled client and server successfully in 531 ms (269 modules)
- wait compiling /api/ip (client and server)...
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
- event compiled successfully in 89 ms (73 modules)
thread '<unnamed>' panicked at 'OS can't spawn worker thread: Resource temporarily unavailable (os error 11)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:365:13
stack backtrace:
   0:     0x7f3f19bc654c - <unknown>
   1:     0x7f3f194bf3ae - <unknown>
   2:     0x7f3f19b9b694 - <unknown>
   3:     0x7f3f19bc7c4f - <unknown>
   4:     0x7f3f19bc784f - <unknown>
   5:     0x7f3f19bc88eb - <unknown>
   6:     0x7f3f19bc83a4 - <unknown>
   7:     0x7f3f19bc830c - <unknown>
   8:     0x7f3f19bc82e1 - <unknown>
   9:     0x7f3f193971f2 - <unknown>
  10:     0x7f3f19782d48 - <unknown>
  11:     0x7f3f1942812a - <unknown>
  12:     0x7f3f197978b0 - <unknown>
  13:     0x7f3f19393987 - <unknown>
  14:     0x7f3f194373dc - <unknown>
- error src/pages/api/ip.ts (9:22) @ prisma
- error Error [TypeError]: Cannot read properties of undefined (reading 'user')
    at handler (webpack-internal:///(api)/./src/pages/api/ip.ts:9:77)
    at /home/XXX/XXX/XXX/bot/node_modules/next/dist/server/api-utils/node.js:463:16
    at /home/XXX/XXX/XXX/bot/node_modules/next/dist/server/lib/trace/tracer.js:113:36
    at NoopContextManager.with (/home/XXX/XXX/XXX/bot/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/home/XXX/XXX/XXX/bot/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NoopTracer.startActiveSpan (/home/XXX/XXX/XXX/bot/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)
    at ProxyTracer.startActiveSpan (/home/XXX/XXX/XXX/bot/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)
    at /home/XXX/XXX/XXX/bot/node_modules/next/dist/server/lib/trace/tracer.js:102:107
    at NoopContextManager.with (/home/XXX/XXX/XXX/bot/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/home/XXX/XXX/XXX/bot/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
    at NextTracerImpl.trace (/home/XXX/XXX/XXX/bot/node_modules/next/dist/server/lib/trace/tracer.js:102:32)
    at apiResolver (/home/XXX/XXX/XXX/bot/node_modules/next/dist/server/api-utils/node.js:461:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.runApi (/home/XXX/XXX/XXX/bot/node_modules/next/dist/server/next-server.js:663:9)
    at async Object.fn (/home/XXX/XXX/XXX/bot/node_modules/next/dist/server/next-server.js:1129:35)
    at async Router.execute (/home/XXX/XXX/XXX/bot/node_modules/next/dist/server/router.js:315:32)
    at async DevServer.runImpl (/home/XXX/XXX/XXX/bot/node_modules/next/dist/server/base-server.js:602:29)
    at async DevServer.run (/home/XXX/XXX/XXX/bot/node_modules/next/dist/server/dev/next-dev-server.js:922:20)
    at async DevServer.handleRequestImpl (/home/XXX/XXX/XXX/bot/node_modules/next/dist/server/base-server.js:533:20) {
  digest: undefined
}
   7 | ) {
   8 |   res.setHeader('Test', 'Test')
>  9 |   const users = await prisma.user.findMany();
     |                      ^
  10 |   console.log(users);
  11 |   return res.status(200).json({ users: users });
  12 |   //res.status(200).json({ ip: requestIp.getClientIp(req) ?? '' });
  15:     0x7f471b394c43 - _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
  16:     0x7f471b81af2d - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb1EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  17:     0x7f471b81b1d3 - _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
  18:     0x7f471b631439 - Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
fatal runtime error: failed to initiate panic, error 5
- error Error: socket hang up
    at connResetException (node:internal/errors:718:14)
    at Socket.socketOnEnd (node:_http_client:520:23)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ECONNRESET'
}
- wait compiling /_error (client and server)...
- event compiled client and server successfully in 54 ms (281 modules)
```

We use "XXX" to hide it because the path name contains authentication information.
The path name consists only of alphanumeric characters and does not contain any Japanese characters.

Also, using only Prisma without Next.js causes no problems
Also, using Next.js alone without Prisma won't cause any problems

We tested with MySQL and SQLite, and both have similar issues.</div>

Postscript:
As we moved from discussion to issue, we looked for additional validation and causes

Whenever I get these errors, it happens when I start two or more Next.js applications
I thought it was a problem that only occurred in combination with Next.js, but as I went along with the additions, I realized that even if I terminated the main process, the Rust process would continue to fire up behind the scenes.

My system probably has a low thread or process limit and won't start
But there were times when even a single application didn't launch. When I ran the "ps x" command at that time, the following Prisma engines were always running, and I could avoid this error by stopping them all with "pkill -f ”prisma""and starting them again.

```
100928 ?        Sl     0:00 /home/xs905136/.cache/prisma-python/binaries/4.15.0/8fbc245156db7124f997f4cecdd8d1219e360944/node_modules/prisma/query-engine-rhel-openssl-1.0.x -p 56787 --enable-raw-queries
```

This problem occurs both in the ported Python version of Prisma and in the Node.js version of Prisma.
And I use the [forever](https://www.npmjs.com/package/forever) package for resident applications, whether Python or Node.js.

If the process is stopped by this Rust error, perhaps because it doesn't work well with the forever package, the forever package will try to restart and the server itself will get stuck.

**Comment by Jolg42** [comment]
@KohnoseLami Could you try setting your generator like:
```
generator client {
  provider   = "prisma-client-js"
  engineType = "binary"
}
```
To see if that issue only happens with the default "library engine".

See https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#configuring-the-query-engine

**Comment by janpio** [comment]
I think the project from @KohnoseLami is already using the binary as this seems to be a Prisma Client Python project - is that correct?

> `100928 ?        Sl     0:00 /home/xs905136/.cache/prisma-python/binaries/4.15.0/8fbc245156db7124f997f4cecdd8d1219e360944/node_modules/prisma/query-engine-rhel-openssl-1.0.x -p 56787 --enable-raw-queries`

**Comment by KohnoseLami** [comment]
I am sorry that I could not answer your question for a long time.
I was not able to answer about Rust in detail.

Probably yes
As far as the process is concerned, it works by binary.
And what we found additionally is that there is an upper limit to which you can start prisma.
Starting Next.js creates multiple instances, making it more error-prone.
A similar error occurs if you start more than one Prisma-only resident process.

Probably a continuation of this problem.
https://github.com/prisma/prisma/issues/20006

My Linux has a slightly lower per-user process limit because it is shared by multiple people.
```
$ ulimit -u
2000
```
```
$ ps aux | wc -l
340
```
But just because it's set low doesn't mean it's close to the upper limit.
The limit is not met, but an error occurs.

```
thread 'tokio-runtime-worker' panicked at 'timer has gone away', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-timer-3.0.2/src/native/delay.rs:112:21
stack backtrace:
   0:     0x5587d414015c - <unknown>
   1:     0x5587d39890fe - <unknown>
   2:     0x5587d4113554 - <unknown>
   3:     0x5587d41418bf - <unknown>
   4:     0x5587d41414bf - <unknown>
   5:     0x5587d414254d - <unknown>
   6:     0x5587d39b35fa - <unknown>
   7:     0x5587d39b35ce - <unknown>
   8:     0x5587d382a170 - <unknown>
   9:     0x5587d4094212 - <unknown>
  10:     0x5587d40c503b - <unknown>
  11:     0x5587d40fed03 - <unknown>
  12:     0x5587d40fcfdd - <unknown>
  13:     0x5587d4100e52 - <unknown>
  14:     0x5587d3885fb4 - <unknown>
  15:     0x5587d38be58d - <unknown>
  16:     0x5587d415a44c - <unknown>
  17:     0x5587d4164b8e - <unknown>
  18:     0x5587d41591b4 - <unknown>
  19:     0x5587d4158c32 - <unknown>
  20:     0x5587d415e1cc - <unknown>
  21:     0x5587d41436b5 - <unknown>
  22:     0x7f0819711ea5 - start_thread
  23:     0x7f0818f34b0d - clone
  24:                0x0 - <unknown>
  ```

Are there any engines that don't use Rust?

**Comment by Weakky** [comment]
Hey @KohnoseLami, given that you're using the Python client, have you opened an issue there https://github.com/RobertCraigie/prisma-client-py ?

**Comment by jkomyno** [comment]
Hey @KohnoseLami, as asked by Weakky, please open an issue in https://github.com/RobertCraigie/prisma-client-py, as they maintain the Python Prisma Client. Thanks!
