### ISSUE TITLE
`$queryRaw` on `Unsupported("polygon")` field fails with `invalid input syntax for type polygon: "POLYGON(...)"`

### ISSUE THREAD

**Issue by maksimdrosdov** [prisma/prisma#20017]
### Bug description
```
Query: SELECT 1
Query: 
        INSERT INTO "shop_delivery" (shop_id, name, price, time, location)
        VALUES ($1, $2, $3, $4, $5::polygon)
        RETURNING *;
      
prisma:error 
Invalid `prisma.$queryRaw()` invocation:
Raw query failed. Code: `22P02`. Message: `db error: ERROR: invalid input syntax for type polygon: "POLYGON((55.19503399600201, 30.188493325347896), (55.193241863325376, 30.185424878234862), (55.18936272346971, 30.189351632232654), (55.18877808336348, 30.19608186067614), (55.197579386122186, 30.198184712543814), (55.19772667164176, 30.18927977861437), (55.19503399600201, 30.188493325347896))"`
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRaw()` invocation:
Raw query failed. Code: `22P02`. Message: `db error: ERROR: invalid input syntax for type polygon: "POLYGON((55.19503399600201, 30.188493325347896), (55.193241863325376, 30.185424878234862), (55.18936272346971, 30.189351632232654), (55.18877808336348, 30.19608186067614), (55.197579386122186, 30.198184712543814), (55.19772667164176, 30.18927977861437), (55.19503399600201, 30.188493325347896))"`
    at Rn.handleRequestError (/usr/src/app/generated/client/runtime/library.js:174:7325)
    at Rn.handleAndLogRequestError (/usr/src/app/generated/client/runtime/library.js:174:6754)
    at Rn.request (/usr/src/app/generated/client/runtime/library.js:174:6344)
    at ShopDeliveryPrismaRepository.create (/usr/src/app/src/modules/delivery/v1/repositories/shop-delivery.repository.ts:45:7)
    at CreateShopDeliveryZoneHandler.execute (/usr/src/app/src/modules/delivery/v1/commands/handlers/shop-delivery.command.handler.ts:19:5)
    at PanelShopDeliveryService.create (/usr/src/app/src/modules/delivery/v1/services/panel-shop-delivery.service.ts:20:5) {
  code: 'P2010',
  clientVersion: '4.16.1',
  meta: {
    code: '22P02',
    message: 'db error: ERROR: invalid input syntax for type polygon: "POLYGON((55.19503399600201, 30.188493325347896), (55.193241863325376, 30.185424878234862), (55.18936272346971, 30.189351632232654), (55.18877808336348, 30.19608186067614), (55.197579386122186, 30.198184712543814), (55.19772667164176, 30.18927977861437), (55.19503399600201, 30.188493325347896))"'
  }
}
```

### CreateShopDeliveryZoneDto data

```
{
    "name": "Zone 1",
    "price": 0,
    "time": "20",
    "location": [
        [
            55.19503399600201,
            30.188493325347896
        ],
        [
            55.193241863325376,
            30.185424878234862
        ],
        [
            55.18936272346971,
            30.189351632232654
        ],
        [
            55.18877808336348,
            30.19608186067614
        ],
        [
            55.197579386122186,
            30.198184712543814
        ],
        [
            55.19772667164176,
            30.18927977861437
        ],
        [
            55.19503399600201,
            30.188493325347896
        ]
    ]
}
```

_No response_

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  output        = "../generated/client"
  binaryTargets = ["native", "darwin"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model ShopDelivery {
  id        Int                      @id(map: "PK_SHOP_DELIVERY") @default(autoincrement())
  shop      Shop                     @relation(fields: [shopId], references: [id], onDelete: Cascade, map: "FK_SHOP_DELIVERY__SHOP_ID")
  shopId    Int                      @map("shop_id")
  name      String                   @db.VarChar(150)
  price     Decimal                  @default(0) @db.Decimal(15, 4)
  time      String                   @db.VarChar(40)
  location  Unsupported("polygon")?
  polygon   Unsupported("GEOMETRY")?
  createdAt DateTime                 @default(now()) @map("created_at")
  updatedAt DateTime                 @default(now()) @updatedAt @map("updated_at")

  @@index([shopId], map: "IDX_SHOP_DELIVERY__SHOP_ID")
  @@index([location], type: Gist, map: "IDX_SHOP_DELIVERY__LOCATION_GIST")
  @@map("shop_delivery")
}


```

```ts
async create(
    shopId: number,
    data: CreateShopDeliveryZonetDto,
  ): Promise<void> {
    const polygonCoordinates = data.location
      .map(([lon, lat]: any) => `(${lon}, ${lat})`)
      .join(', ');
    const polygonString = `POLYGON(${polygonCoordinates})`;

    try {
      await this.prisma.$queryRaw`
        INSERT INTO "shop_delivery" (shop_id, name, price, time, location)
        VALUES (${shopId}, ${data.name}, ${data.price}, ${data.time}, ${polygonString}::polygon)
        RETURNING *;
      `;
    } catch (error) {
      console.log(error);
    }
  }
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v19.4.0

### Prisma Version
"^4.16.1"
```

```

**Comment by Jolg42** [comment]
Hi @maksimdrosdov, it looks like you didn't fully enter all the information we need to attempt a reproduction.
I edited the issue description, please fill it in, so we can help you.

**Comment by Jolg42** [comment]
Note that when using `Unsupported()` it means that only raw queries are available for that field
See
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#unsupported
https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access#unsupported-types

**Comment by maksimdrosdov** [comment]
> Привет@maksimdrosdov, похоже, вы не полностью ввели всю информацию, необходимую нам для попытки воспроизведения. Я отредактировал описание проблемы, пожалуйста, заполните его, чтобы мы могли вам помочь.

update question

**Comment by maksimdrosdov** [comment]
> Hi @maksimdrosdov, it looks like you didn't fully enter all the information we need to attempt a reproduction. I edited the issue description, please fill it in, so we can help you.

updated question

**Comment by Jolg42** [comment]
@maksimdrosdov This does not look related to Prisma to me.
You could try verifying by executing the SQL directly using a GUI, like TablePlus or PGAdmin, I think it here this SQL query would fail the same.

Maybe try to replace `::polygon` by `::geometry` here?

**Comment by maksimdrosdov** [comment]
> @maksimdrosdov This does not look related to Prisma to me. You could try verifying by executing the SQL directly using a GUI, like TablePlus or PGAdmin because in this case this SQL query would fail the same for me.
> 
> Maybe try to replace `::polygon` by `::geometry` here?

error

```
Database error:
ERROR: type "geometry" does not exist

Position:
  0
  1 -- AlterTable
  2 ALTER TABLE "shop_delivery_prices" ADD COLUMN     "loc" geometry;

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42704), message: "type \"geometry\" does not exist", detail: None, hint: None, position: Some(Original(71)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_type.c"), line: Some(270), routine: Some("typenameType") }

```

my schema.prisma

```
model ShopDeliveryPrice {
  id             Int                      @id(map: "PK_SHOP_DELIVERY_PRICES") @default(autoincrement())
  shopDelivery   ShopDelivery             @relation(fields: [shopDeliveryId], references: [id], onDelete: Cascade, map: "FK_SHOP_DELIVERY_PRICES__SHOP_DELIVERY_ID")
  shopDeliveryId Int                      @map("shop_delivery_id")
  name           String?                  @db.VarChar(150)
  price          Decimal                  @default(0) @db.Decimal(15, 4)
  time           String?                  @db.VarChar(40)
  location       Unsupported("polygon")?
  loc            Unsupported("geometry")?
  distance       Int                      @default(0) @db.SmallInt
  createdAt      DateTime                 @default(now()) @map("created_at")
  updatedAt      DateTime                 @default(now()) @updatedAt @map("updated_at")

  @@index([shopDeliveryId], map: "IDX_SHOP_DELIVERY_PRICES__SHOP_DELIVERY_ID")
  @@index([location], type: Gist, map: "IDX_SHOP_DELIVERY_PRICES__LOCATION_GIST")
  @@map("shop_delivery_prices")
}
```

**Comment by jkomyno** [comment]
Hey @maksimdrosdov, could you please confirm that the comment above fixes this issue? Thanks.

**Comment by jkomyno** [comment]
Closing this issue for inactivity. Feel free to leave a comment asking to re-open the issue in case [this solution](https://github.com/prisma/prisma/issues/20017#issuecomment-1618220856) doesn't work out for your case. Thanks!
