### ISSUE TITLE
Error creating a database connection.

### ISSUE THREAD

**Issue by Fantros** [prisma/prisma#20141]
### Bug description

I run `npx prisma db push` or `npx prisma db pull` and it throws an error
I would appreciate it if you help, I don't think I have the problem, I did it by looking at the documents

### How to reproduce

1. Run 'npx prisma db push'
2. Error:
```
  prisma:engines  binaries to download libquery-engine, migration-engine +0ms
  prisma:loadEnv  project root found at C:\Users\90533\Desktop\shop.partivo.net\package.json +0ms
  prisma:tryLoadEnv  Environment variables not found at null +0ms
  prisma:tryLoadEnv  Environment variables not found at undefined +5ms
  prisma:tryLoadEnv  No Environment variables loaded +3ms
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +63ms
Prisma schema loaded from prisma\schema.prisma
  prisma:loadEnv  project root found at C:\Users\90533\Desktop\shop.partivo.net\package.json +111ms
  prisma:tryLoadEnv  Environment variables not found at null +106ms
  prisma:tryLoadEnv  Environment variables not found at undefined +1ms
  prisma:tryLoadEnv  No Environment variables loaded +4ms
  prisma:getConfig  Using getConfig Wasm +48ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +10ms
Datasource "db": SQL Server database
  prisma:getConfig  Using getConfig Wasm +14ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +17ms
  prisma:getConfig  Using getConfig Wasm +2ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +54ms

⠋ Introspecting based on datasource defined in prisma\schema.prisma  prisma:migrateEngine:rpc  starting migration engine with binary: C:\Users\90533\Desktop\shop.partivo.net\node_modules\@prisma\engines\migration-engine-windows.exe +0ms        
  prisma:migrateEngine:rpc  SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":{"schema":"generator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider = \"sqlserver\"\n  url = \"sqlserver://localhost:1433;initialCatalog=shop;integratedSecurity=true;trustServerCertificate=true;\"\n}","force":false,"compositeTypeDepth":-1}} +89ms
⠙ Introspecting based on datasource defined in prisma\schema.prisma  prisma:migrateEngine:stderr  {"timestamp":"2023-07-09T23:57:46.1834688Z","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"4bc8b6e1b66cb932731fb1bdbbc550d1e010de81"},"target":"migration_engine"} +0ms
  prisma:migrateEngine:stderr  {"timestamp":"2023-07-09T23:57:46.2024485Z","level":"INFO","fields":{"message":"\"generator client {\\n  provider = \\\"prisma-client-js\\\"\\n}\\n\\ndatasource db {\\n  provider = \\\"sqlserver\\\"\\n  url = \\\"sqlserver://localhost:1433;initialCatalog=shop;integratedSecurity=true;trustServerCertificate=true;\\\"\\n}\""},"target":"schema_core::state"} +4ms
⠼ Introspecting based on datasource defined in prisma\schema.prisma  prisma:migrateEngine:rpc  {
  jsonrpc: '2.0',
  error: {
    code: 4466,
    message: 'An error happened. Check the data field for details.',
    data: {
      is_panic: false,
      message: 'Error creating a database connection.\n',
      backtrace: null
    }
  },
  id: 1
} +4s
✖ Introspecting based on datasource defined in prisma\schema.prisma

Error: Error: Error creating a database connection.


    at Object.<anonymous> (C:\Users\90533\Desktop\shop.partivo.net\node_modules\prisma\build\index.js:100918:25)
    at MigrateEngine.handleResponse (C:\Users\90533\Desktop\shop.partivo.net\node_modules\prisma\build\index.js:100764:36)
    at LineStream2.<anonymous> (C:\Users\90533\Desktop\shop.partivo.net\node_modules\prisma\build\index.js:100867:16)     
    at LineStream2.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at LineStream2._pushBuffer (C:\Users\90533\Desktop\shop.partivo.net\node_modules\prisma\build\index.js:100543:17)     
    at LineStream2._transform (C:\Users\90533\Desktop\shop.partivo.net\node_modules\prisma\build\index.js:100537:8)       
    at Transform._write (node:internal/streams/transform:175:8)
```

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlserver"
  url = "sqlserver://localhost:1433;initialCatalog=shop;integratedSecurity=true;trustServerCertificate=true;"
}
```

### Environment & setup

- OS: Windows 11
- Database: SQL Server 2022
- Node.js version: v18.15.0

### Prisma Version

```
prisma                  : 4.16.2
@prisma/client          : 4.16.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
```

**Comment by Jolg42** [comment]
@Fantros Did you try this connection URL with another tool, like TablePlus, and dies it connects successfully?

**Comment by sharunkumar** [comment]
I am getting the same issue. trying to connect to the default instance installed using `Microsoft.SQLServer.2022.Developer` from `winget`

**Comment by sharunkumar** [comment]
This worked for me:
- Go to SQL Server Configuration Manager
- Enable TCP/IP for your Server (its disabled by default)
- Restart SQL Server Service

This is the case even if I don't specify a port for the connection (just my machine name)

`sqlserver://MyMachineName;database=sample;integratedSecurity=true;trustServerCertificate=true;`

Relevant Screenshots:

![image](https://github.com/prisma/prisma/assets/715417/47fe7901-2dd0-4a13-8cd6-ae658d378444)

![image](https://github.com/prisma/prisma/assets/715417/0b30db20-2e72-49ce-a9b5-46115f40d807)

**Comment by tddat15** [comment]
Do you guys have any other solution?
this error still happens to me, I have tried to enable the TCP in the SQL  server configuration management and restart the SQL server in th but still cannot access the DB.

**Comment by pasindu-pr** [comment]
I had the same issue. I enabled the TCP/IP and restarted the SQLServer service.

**Comment by janpio** [comment]
Seems that is the solution to this problem then. Thanks for sharing @sharunkumar!
