### ISSUE TITLE
Running a built binary fails with weird error

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma#2017]
When building the Prisma 2 CLI to a binary with [node-packer](https://github.com/pmq20/node-packer), I get this weird error:

```
❯ ./prisma-cli-darwin-2.0.0-alpha.911 version
internal/util.js:206
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:206:11)
    at Object.4364 (/__enclose_io_memfs__/build/index.js:2:1368472)
    at __webpack_require__ (/__enclose_io_memfs__/build/index.js:2:154)
    at Object.2740 (/__enclose_io_memfs__/build/index.js:2:706082)
    at __webpack_require__ (/__enclose_io_memfs__/build/index.js:2:154)
    at Object.5575 (/__enclose_io_memfs__/build/index.js:2:1677696)
    at __webpack_require__ (/__enclose_io_memfs__/build/index.js:2:154)
    at Object.729 (/__enclose_io_memfs__/build/index.js:2:142604)
    at __webpack_require__ (/__enclose_io_memfs__/build/index.js:2:154)
    at Object.6292 (/__enclose_io_memfs__/build/index.js:2:1880810)
```

I'm not quite sure why this happens, but it may have something to do with either 1) Promises (due to the error message) or 2) the file system (due to the fact that these bundlers use a virtual file system); but I'm also not sure if it has to do anything with either of those.

It happens in the latest alpha (tested with 2.0.0-alpha.1000), and I could track it back to 2.0.0-alpha.911, it did not not happen before 2.0.0-alpha.911.

**Comment by pantharshit00** [comment]
@steebchen Can you paste the exact node-packer command here?

Also, try using pkg once: https://github.com/zeit/pkg

**Comment by steebchen** [comment]
The command I'm using is:

```
npm install @prisma/cli@alpha
./nodec node_modules/@prisma/cli/build/index.js --skip-npm-install -o ./prisma-cli-darwin-latest
```

**Comment by steebchen** [comment]
@pantharshit00 I have tried building binaries with several tools, including zeit/pkg, but I have been unsuccessful with any of them except node-packer. I'm not sure how they do it but node-packer is able to pick up everything, at least before this error happened.

I've tried again with zeit/pkg but ran into this and also have no idea how to solve it:

```
❯ ./index-macos version
internal/modules/cjs/loader.js:636
    throw err;
    ^

Error: Cannot find module '/snapshot/build/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:634:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1350:46)
    at Function.Module._load (internal/modules/cjs/loader.js:560:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:660:3)
```

**Comment by timsuchanek** [comment]
This can now be accomplished with `pkg` and the following steps:
```bash
mkdir build
cd build
yarn init -y
npm i -g pkg
yarn add @prisma/cli@alpha
cd node_modules/@prisma/cli
pkg .
./cli-macos --version
```

**Comment by adrianoresende** [comment]
@timsuchanek 

I have the same problem but in development.

![image](https://user-images.githubusercontent.com/798755/82134007-e2a5ee00-97c8-11ea-85bd-e54e9c3e1110.png)

1. Install Vue
2. Install Prisma
3. Ran command init > introspect > generate
4. Add `import { PrismaClient } from '@prisma/client'` in `main.js`
5. `yarn serve`
6. Page empty and an error in console (screenshot)

**Comment by pantharshit00** [comment]
@adrianoresende Prisma won't run on frontend. Please make sure you are running Prisma in node
