### ISSUE TITLE
Unique constraint failed on the constraint: `treeNodes_parentTreeId_key`

### ISSUE THREAD

**Issue by maxime4000** [prisma/prisma#20217]
### Bug description

So I'm doing self relation with a owner of that tree data. When using it without pushing the schema, everything is fine, but when you start pushing the schema, you can't create nor update a treeNode correctly... 

Anyway, I place some commented prisma code in the schema, because doing the same, but inverted is causing other error. (The tree own the first node instead of the first node owning the tree reference).

### Related question
I create an empty treeOwner first because I want each node to be owned by the treeOwner. So I need his Id in the first place, but is there some ways to reference the creator for each node created inside the TreeOwner ? 
- I could remove the reference to the owner, but I think querying those nodes after would probably being problematics, so every node in that tree is referencing to it's owner for easier querying. I would be interested to know if there is a cleaner ways to do that?

### Comment
Btw, I wish I could do Composite Type relationship, but because this isn't implemented yet, I'm doing NoSQL wrong instead.

### How to reproduce

1. prisma generate
2. prisma db push
   - Without the db push, the insertion is working. 
   - Should we use db push ? How painful it is when you start going into prod and make some change to the schema ? 
      - (For a mongodb database)
4. run script

```
Invalid `prisma.treeNode.create()` invocation:
2

Unique constraint failed on the constraint: `treeNodes_parentTreeId_key`

PrismaClientKnownRequestError: 
Invalid `prisma.treeNode.create()` invocation:
2

Unique constraint failed on the constraint: `treeNodes_parentTreeId_key`
    at zr.handleRequestError (/Users/maxime/Repo/project/node_modules/@prisma/client/runtime/library.js:122:8308)
    at zr.handleAndLogRequestError (/Users/maxime/Repo/project/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/Users/maxime/Repo/project/node_modules/@prisma/client/runtime/library.js:122:7307)
    at local code...
```

### Expected behavior

I think in my code I have what is needed to make this work but for some reason, Unique constraint failed and I think it's because I can have null value, but I'm not sure.

### Prisma information

```prisma
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "linux-musl-openssl-3.0.x"]
}

model TreeNode {
  id String @id @default(auto()) @map("_id") @db.ObjectId

  name String

  parentId      String?    @db.ObjectId
  parentNode    TreeNode?  @relation("NodeTrees", fields: [parentId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  childrenNodes TreeNode[] @relation("NodeTrees")

  parentTreeId String?    @unique @db.ObjectId
  parentTree   TreeOwner? @relation("parentTree", fields: [parentTreeId], references: [id])
  //parentTree        TreeOwner?      @relation("entryNode")

  treeOwnerId String    @db.ObjectId
  treeOwner   TreeOwner @relation("allNodes", fields: [treeOwnerId], references: [id], onDelete: NoAction, onUpdate: NoAction)

  @@map("treeNodes")
}

model TreeOwner {
  id String @id @default(auto()) @map("_id") @db.ObjectId

  node TreeNode? @relation("parentTree")
  //entryNodeId String?                   @unique @db.ObjectId
  //entryNode   TreeNode?  @relation("entryNode", fields: [entryNodeId], references: [id])
  //entryNode   TreeNode   @relation("entryNode", fields: [entryNodeId], references: [id], onDelete: Cascade, onUpdate: NoAction)

  allNodes TreeNode[] @relation("allNodes")

  @@map("treeOwners")
}

```

```ts
const { id: newtreeOwnerId } = await prisma.treeOwner.create({
	data: {},
});

const errorHere = await prisma.treeNode.create({
	data: {
		name: "Node1",
		childrenNodes: {
			create: [
				{ name: "Node2", treeOwner: { connect: { id: newtreeOwnerId } } },
				{ name: `Node3`, treeOwner: { connect: { id: newtreeOwnerId } } },
			],
		},
		parentTree: { connect: { id: newtreeOwnerId } },
		treeOwner: { connect: { id: newtreeOwnerId } },
	},
});
```

### Environment & setup

- OS: macOS
- Database: MongoDB
- Node.js version: 18.16.0

### Prisma Version

```
prisma: 5.0.0
```

**Comment by janpio** [comment]
Mongo can create your schema dynamically when you insert data. `db push` only creates indexes and constraints, like the `@unique` you use in your schema. Without running `db push` these unique constraints are not enforced - so MongoDB will allow you to insert the same value multiple times into your collection by default.

> ```prisma
> parentTreeId String?    @unique @db.ObjectId
> ```

Is it intentional that there can only be 1 `TreeNode` that has a certain other TreeNode as the parent (because of the `@unique`)? That means, in the other direction, that any TreeNode can also only have one child.

(That `@unique` is also the unique constraint that is giving you the error message,  `**treeNodes**_**parentTreeId**_key` => collection `treeNodes`, field `parentTreeId`.)

**Comment by maxime4000** [comment]
I change name for this example, but yes it is intentional. I want one TreeOwner to own the first node of the graph. After that, each other nodes of the graph will be own by the same TreeOwner and TreeNode will self references to create the graph. From that point, TreeNode will reference other model in the database, but I didn't include them for the example because they doesn't cause the issue I'm having. 

That unique constraint is an optional 1-1 relationship and that's what I want. What I don't understand is why the constraint error is showing up. What I'm looking for is that the first Node in the graph is always including a TreeOwner. I know that I could make one without a TreeOwner, but the logic of my systems will always start from a TreeOwner and include a Graph of TreeNodes that will references other model in my schema. 

![image](https://github.com/prisma/prisma/assets/4070713/d97ace4a-3e1d-422e-9261-511a8eca2a58)

To me, I'm using the schema correctly, but I can't insert a TreeNode because the constraint error is showing up. I don't understand why and I don't think it should be showing up. If I'm wrong and I poorly design the schema, please correct my schema.

**Comment by janpio** [comment]
Just making sure I understand what you want to happen.

I would now try logging the command executed (https://pris.ly/d/logging) to understand what it is trying to run on the database. As I am personally more used to PostgreSQL, I would maybe also convert to that temporarily and look at the SQL query (and actually confirm the same problem happens there first).

That might help understand what is going on.

**Comment by maxime4000** [comment]
For the logging : 
```
Query: db.treeOwners.insertOne({ })
Query: db.treeOwners.aggregate([ { $match: { $expr: { $and: [ { $and: [ { $eq: [ "$_id", { $literal: ObjectId("64b16314f4d8735a99528cc1"), }, ], }, { $ne: [ "$_id", "$$REMOVE", ], }, ], }, ], }, }, }, { $project: { _id: 1, }, }, ])
2
Query: db.treeOwners.aggregate([ { $match: { $expr: { $or: [ { $and: [ { $and: [ { $and: [ { $eq: [ "$_id", { $literal: ObjectId("64b16314f4d8735a99528cc1"), }, ], }, { $ne: [ "$_id", "$$REMOVE", ], }, ], }, ], }, { }, ], }, ], }, }, }, { $project: { _id: 1, }, }, ])
Query: db.treeNodes.aggregate([ { $match: { $expr: { $and: [ { }, { $and: [ { $in: [ "$parentTreeId", [ { $literal: ObjectId("64b16314f4d8735a99528cc1"), }, ], ], }, { $ne: [ "$parentTreeId", "$$REMOVE", ], }, ], }, ], }, }, }, { $project: { _id: 1, parentTreeId: 1, }, }, ])
Query: db.treeNodes.insertOne({ name: "Node1", parentTreeId: ObjectId("64b16314f4d8735a99528cc1"), treeOwnerId: ObjectId("64b16314f4d8735a99528cc1"), })
Query: db.treeOwners.aggregate([ { $match: { $expr: { $or: [ { $and: [ { $and: [ { $and: [ { $eq: [ "$_id", { $literal: ObjectId("64b16314f4d8735a99528cc1"), }, ], }, { $ne: [ "$_id", "$$REMOVE", ], }, ], }, ], }, { }, ], }, ], }, }, }, { $project: { _id: 1, }, }, ])
Query: db.treeNodes.insertOne({ name: "Node3", parentId: ObjectId("64b16314f4d8735a99528cc2"), treeOwnerId: ObjectId("64b16314f4d8735a99528cc1"), })
Query: db.treeOwners.aggregate([ { $match: { $expr: { $or: [ { $and: [ { $and: [ { $and: [ { $eq: [ "$_id", { $literal: ObjectId("64b16314f4d8735a99528cc1"), }, ], }, { $ne: [ "$_id", "$$REMOVE", ], }, ], }, ], }, { }, ], }, ], }, }, }, { $project: { _id: 1, }, }, ])
Query: db.treeNodes.insertOne({ name: "Node2", parentId: ObjectId("64b16314f4d8735a99528cc2"), treeOwnerId: ObjectId("64b16314f4d8735a99528cc1"), })
prisma:error 
Invalid `prisma.treeNode.create()` invocation:
2

Unique constraint failed on the constraint: `treeNodes_parentTreeId_key`
[Nest] 2769  - 07/14/2023, 11:00:37 AM   ERROR [ExceptionsHandler] 
Invalid `prisma.treeNode.create()` invocation:
```

For the part with PostgreSQL, I'm not sure it's useful? In my case, I only use MongoDB and while I wish I was using SQL instead of NoSQL, all our project use MongoDB, so I'm stuck with it. Maybe in SQL it's working and not in NoSQL, but should that be prisma fault due to being the middle man between my app and my database?

**Comment by janpio** [comment]
Ok, so the logged commands make it roughly possible to understand how Prisma tries to write this data.

We see that the query that fails, does not actually write anything into the `treeNode` field: `db.treeNodes.insertOne({ name: "Node2", parentId: ObjectId("64b16314f4d8735a99528cc2"), treeOwnerId: ObjectId("64b16314f4d8735a99528cc1"), })`. This means that MongoDB is unhappy with something that _is not actually written_. 

`parentTreeId` is optional, so can be `null` in your schema. Without the `@unique` index that does not matter, but the index changes that: https://www.mongodb.com/docs/manual/core/index-unique/#unique-index-and-missing-field

Could that be the problem here?

**Comment by maxime4000** [comment]
Using mongodb 5 btw if that matter. And if I don't use the @unique, TreeOwner will have an array of node, but I want a one to one optional relationship. What I don't understand, does it crash at Node3 insertion ? Should it crash at Node2 instead ? Just saying I was probably running an empty DB so maybe it's the second "null-unique" insertion that cause a crash?

**Comment by janpio** [comment]
Yes, you can have 1 entry with `null` but MongoDB `@unique` logic forbids the second one as it also considers `null` a value that needs to be unique.

I fear you will have to remove the `@unique` and enforce the uniqueness you want to have some other way (or maybe enforce that every item but one has a `parentTreeId`).

**Comment by maxime4000** [comment]
Just saying, I use vscode with the Prisma extension. To do a 1-1 relationship you must do an unique, else it's a 1-n relationship. If you try to remove the unique, the extension will force you to insert a array to TreeOwner. 

What I'm saying, if I do that, I'm forced to handle the uniqueness by hand. Need to inform my colleagues that this relationship must be unique, but cannot be unique because it's a limitation of Prisma or MongoDB. So it's an Array that must only include one entry.

You see where I goes? If I'm defining a schemas, the schemas should be exactly what it's says, not something to circumvent a weakness of the primary tool I use for simplified database usage.

## Solutions
So I see 2-3 solutions here:
1. Improvement done on the Prisma db part to change the validation push to the database when it's a optional 1-1 relationship.
   1. Maybe the validation is not push to MongoDB and handle internally by Prisma if there is no way to make MongoDB understand what a optional unique is.
2. Instead of fixing this, make composite type able to do relationship. The graph I need to do could be a composite type if I didn't need optional relationship in each node. I know, it's probably harder to handle that than I understand it, but the real strength of MongoDB is to have embedded data instead of having 1-1 relationship. It's a shame that Prisma doesn't handle that completely and force their to user to find ways to make the same the SQL ways when they could use the strength of the database provider they are using. Just saying, a prisma.schema file for MongoDB is different than a schema for PostgreSQL or other providers and the vscode extension is working different depending on the provider. If the relationship are working differently because they use composite type, that's fine, they aren't compatible with other providers anyway. 

While I'm negative in my bug report, I really like what Prisma is, I like the generator features. (I automatized full seeding and factory functions using faker (and handle relationship creation) which is awesome imo.) I just think composite type with relationship would be the best improvement done for the MongoDB users. Thanks and I appreciate your work! 😊

**Comment by janpio** [comment]
Yes, I agree with your analysis - just put a little bit less blame on Prisma 😆 (Surprise...)

The underlying problem here is that [MongoDB defines uniqueness differently than expected](https://www.mongodb.com/docs/manual/core/index-unique/#unique-index-and-missing-field) (and most other databases), so only one `null` is allowed for a field with `@unique`. Right now Prisma does not support any other mechanism than this one for configuring uniqueness, and we are honestly not very hot on having to build something ourselves - as that would involve reading _all_ the data, and that usually doesn't end well.

Relations over composite types (embedded documents) are tracked here: https://github.com/prisma/prisma/issues/10102 That unique indexes are not supported inside documents is part of why we have not implemented that yet (I made that explicit in the issue).

It seems that a "[Partial Index with Unique Constraint](https://www.mongodb.com/docs/manual/core/index-partial/#std-label-partial-index-with-unique-constraints)" might be the native MongoDB solution for your problem. If I understand correctly this could exclude `null` values from being indexed. Unfortunately, Prisma does not support that yet: https://github.com/prisma/prisma/issues/6974

Or we could use a "[sparse index](https://www.mongodb.com/docs/manual/core/index-sparse/)", which seems to be the same thing, just more specific and explicit: "The index skips over any document that is missing the indexed field.". That is actually being tracked here: https://github.com/prisma/prisma/issues/3419 and hence is also not supported yet.

So for now I can only suggest you subscribe to these issues and find a different solution in the meantime.

If you are not planning to use `db push` regularly, you could for example just replace the full unique index with a sparse unique index on that collection manually, and you should be able to input the data as desired. If you need to use `db push` regularly, I would suggest you create a script you can run automatically after doing so that changes the full unique index to a sparse unique index - and optimally set up a npm script or bash script that automates combining these two command executions.

**Comment by maxime4000** [comment]
Thanks for your research. I will subscribe to those issues.

From what I understand, optional 1-1 relation should be using sparse index instead of "regular" unique index so that multiple Null value wouldn't cause unique constraint to raise error. It's look like this would be the proper solution and the same behaviour as how SQL DB are working when it's optional 1-1 relationship.

It still check for uniqueness but only if the value is define which is what an optional relationship should be imo.
(I don't think having a unique constraint on a null value should be an expected behaviour, but I'm not a MongoDB Dev, so I don't know their reason for implementing it this way)

For `db push` for now I'm good not using it, but here's why I use it. The generator I made for seeding data, well if I do not use `db push` inserting about 10k of entries will take multiple minutes (about 5+ minutes). If I use `db push`, inserting the same data will take about ~30 seconds. It's game changing on how fast insertion is with `db push`

We want `db push` functional because the latest feature I implement was logging hundreds of megabits of event data. Without the constraint pushed (because of this issue), it took 20+ minutes to insert all the data into a local MongoDB. Running the "simulation" take about 1-2 minutes, but inserting the result of this simulation take 10-15x the time of running the simulation. So I would expect faster insertion with `db push`, but that doesn't work because of null unique constraint error. That doesn't mean `db push` would improve the performance of it, but because seeding is very similar as inserting event log of a simulation, I'm pretty sure the insertion would be faster with `db push`. 
*(At least, I don't have to run that often 😅)*

**Comment by Paul-Chisenga** [comment]
Hello There !
I ran into a similar problem when I was implementing a 1-1 relation. Though in my case I was implementing a linked list with Prev-Next concept (see the code below). I looked around and didn't find a solution so I thought hard and came up with a workaround that could probably help someone

`model WaypointNode {
  id                 String                    @id @default(auto()) @map("_id") @db.ObjectId
  waypoint      Waypoint             @relation(fields: [waypointId], references: [id], onDelete: Restrict)
  waypointId   String                   @db.ObjectId
  next              WaypointNode?  @relation("PrevNext")
  prev              WaypointNode?  @relation("PrevNext", fields: [prevId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  prevId           String?                 @unique @db.ObjectId
  waypointList                             WaypointList?

  createdAt     DateTime             @default(now())
  updatedAt    DateTime            @updatedAt
}`

As you can see in my WaypointNode prevId has a unique constraint
For my linked list there will always be one Node that has no prev Node and one Node that has no next Node, head and tail respectively.
I was facing the unique constraint validation error whenever I tried to insert a new node before the head node (eg. effectively making this node the head):
`const newNode = await tx.waypointNode.create(
Unique constraint failed on the constraint: `WaypointNode_prevId_key`
...
code: 'P2002',
  clientVersion: '5.21.0',
  meta: { modelName: 'WaypointNode', target: 'WaypointNode_prevId_key' }
`

Solution:
I realised when the new node is being created both the prevId of the new and head node will initialy be null hence the validation error.
- I checked if I the reference node is the head node
- Assign a placeholder prevId to the head node
- Create new node, make it the head node by assigning the previous head node as next node of the new node, Prisma will automatically replace the placeholder prevId I previously assigned with the new node

`
// get the primary ref node
        const primaryRefNode = await tx.waypointNode.findUniqueOrThrow({
          where: params,
          select: {
            id: true,
            next: {
              select: { id: true },
            },
            prev: {
              select: { id: true },
            },
            waypointList: { select: { id: true } },
          },
        });
        // the node that knows the linked list is the head node
        const isHead = !!primaryRefNode.waypointList;

        // if is head node then prevId will be null
        if (isHead) {
          await tx.waypointNode.update({
            where: { id: primaryRefNode.id },
            data: {
              prevId: ObjectID().toHexString(), // Assign a placeholder Id to avoid the unique constraint validation on the prevId
            },
          });
        }

        // create new node
        const newNode = await tx.waypointNode.create({
          data: {
            waypoint: {
              connectOrCreate: connectOrCreateWaypoint(insertWaypointNodeDto),
            },
            next: { connect: { id: primaryRefNode.id } },
          },
        });

        // connect new node to other reference nodes
       // ....
`
