### ISSUE TITLE
optional relation field causes runtime type errors

### ISSUE THREAD

**Issue by samualtnorman** [prisma/prisma#20400]
### Bug description

when the relation field is optional but the scalar field is required e.g.
```prisma
model User {
  name   String
  email  String  @unique
  author Author? @relation(fields: [email], references: [email])
}

model Author {
  name  String
  email String @unique
  User  User?
}
```
prisma generates incorrect type declarations that mean when you forget the required scalar field e.g.
```js
prisma.user.create({ data: { name: "John Smith" } })
```
typescript does not detect the error and you find out at runtime
```
PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation:


Null constraint violation on the fields: (`email`)
    at zr.handleRequestError (/tmp/tmp.HTwZTpQucj/node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client/runtime/library.js:122:8308)
    at zr.handleAndLogRequestError (/tmp/tmp.HTwZTpQucj/node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/tmp/tmp.HTwZTpQucj/node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client/runtime/library.js:122:7307)
    at async file:///tmp/tmp.HTwZTpQucj/index.js:6:1 {
  code: 'P2011',
  clientVersion: '5.0.0',
  meta: { constraint: [ 'email' ] }
}

Node.js v20.4.0
```

### How to reproduce

there's a repro repo at https://github.com/samualtnorman/prisma-issue-repro. it requires docker to setup the temp database.

first take a look at `scripts/repro.sh`, then run it.

### Expected behavior

prisma should either properly support this schema (see https://github.com/prisma/prisma/issues/18058 and https://github.com/prisma/prisma-engines/pull/4083) or reject this schema

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model User {
  name   String
  email  String  @unique
  author Author? @relation(fields: [email], references: [email])
}

model Author {
  name  String
  email String @unique
  User  User?
}
```

```ts
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient

// typescript doesn't detect type errors
await prisma.user.create({ data: { name: "John Smith" } })
```

### Environment & setup

- OS: ArchLinux
- Database: MariaDB
- Node.js version: v20.4.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.0.0
@prisma/client          : 5.0.0
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules/.pnpm/@prisma+engines@5.0.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules/.pnpm/@prisma+engines@5.0.0/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Default Engines Hash    : 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Studio                  : 0.487.0
```

**Comment by ludralph** [comment]
Closing this in favour of [#9784](https://github.com/prisma/prisma/issues/9784) since it's a duplicate.

**Comment by samualtnorman** [comment]
> Closing this in favour of [#9784](https://github.com/prisma/prisma/issues/9784) since it's a duplicate.

That looks like a separate issue to me
