### ISSUE TITLE
RLS extension fails if called a second time 

### ISSUE THREAD

**Issue by jasonmacdonald** [prisma/prisma#20407]
### Bug description

Using the example provided at , if you try to execute an RLS bypass call a second time after a normal RLS call has been made, it fails with.

```
Error in batch request 1: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E22P02), message: "invalid input syntax for type uuid: \"\"", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("uuid.c"), line: Some(133), routine: Some("string_to_uuid") }) }), transient: false })
    at Rn.handleRequestError (/Users/jasonmacdonald/Projects/github/prisma-client-extensions/row-level-security/node_modules/@prisma/client/runtime/library.js:174:7499)
    at Rn.handleAndLogRequestError (/Users/jasonmacdonald/Projects/github/prisma-client-extensions/row-level-security/node_modules/@prisma/client/runtime/library.js:174:6754)
    at Rn.request (/Users/jasonmacdonald/Projects/github/prisma-client-extensions/row-level-security/node_modules/@prisma/client/runtime/library.js:174:6344) {
  clientVersion: '4.16.1'
}
```
I was able to replicate this using the example RLS extension.

This is happening in our large codebase as well, where certain calls need to be made without a tenant ID. It seems to try and convert the string to UUID even if it's not set and within a different extended client.

### How to reproduce

1. Checkout the RLS example https://github.com/prisma/prisma-client-extensions/tree/main/row-level-security
2. Add a second query that tries to bypass RLS after an RLS call has been made. 
```Typescript
const projects = await companyPrisma.project.findMany({
    include: projectInclude,
  });
  
  const user2 = await  prisma.$extends(bypassRLS()).user.findFirstOrThrow();
  ```
  
  See error.

### Expected behavior

It shouldn't bypass RLS as expected.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

Default environment provided by example.

### Prisma Version

```
4.16.1
```

**Comment by jasonmacdonald** [comment]
The only way I have found to make this work is to open two separate connections with their own connection pools. Which is not very efficient. :(

**Comment by Druue** [comment]
Hey @jasonmacdonald, I've managed to reproduce this but can you confirm that this is also the same error that you see?

---

<img width="1075" alt="image" src="https://github.com/prisma/prisma/assets/29753584/42a064a5-8dd6-416f-b5cd-5de51273522d">

**Comment by jasonmacdonald** [comment]
@Druue Yes, the same error.

**Comment by holtc** [comment]
Is there any update here? Having the same issue. Lmk if there's any logs or other materials I could provide if helpful!

**Comment by jasonmacdonald** [comment]
> Is there any update here? Having the same issue. Lmk if there's any logs or other materials I could provide if helpful!
> 
> EDIT: Any chance is it [related to this](https://stackoverflow.com/questions/50923911/how-to-remove-configuration-parameter)?
> 
> EDIT2: As a hack, I've solved by updating `bypassRLS`:
> 
> ```
> function bypassRLS() {
>   return Prisma.defineExtension((prisma) =>
>     prisma.$extends({
>       query: {
>         $allModels: {
>           async $allOperations({ args, query }) {
>             const [, , result] = await prisma.$transaction([
>               prisma.$executeRaw`SELECT set_config('app.bypass_rls', 'on', TRUE)`,
>               // This is a hack to get the 'app.current_company_id' to be set to a dummy value since the empty string is not a valid UUID
>               prisma.$executeRaw`SELECT set_config('app.current_company_id', '00000000-0000-0000-0000-000000000000', TRUE)`,
>               query(args),
>             ]);
>             return result;
>           },
>         },
>       },
>     })
>   );
> }
> ```

This is basically what we also had to do: supply a non-valid UUID. However, it worries me as it could find its way into the DB if you use the config value as a DB default value on create (we learned the hard way).

**Comment by janpio** [comment]
I had a deeper look into this, and simplified the reproduction a bit: https://github.com/prisma/prisma-client-extensions/pull/53/files

I understand that the missing / not defined `app.current_company_id` on the second call is the problem. That led me to try another call without _any_ extension, and that also fails the same way - so this is not limited to `bypassRLS()` I think, but a higher level problem of queries without `current_company_id` not working anymore after some queries used it before.

Does that make sense?

> EDIT: Any chance is it [related to this](https://stackoverflow.com/questions/50923911/how-to-remove-configuration-parameter)?

And that is indeed a viable explanation. The connection that has used a `app.current_company_id` once now includes an empty value, which leads to a problem when the policy is executed:
```
CREATE POLICY tenant_isolation_policy ON "Project" USING ("companyId" = current_setting('app.current_company_id', TRUE)::uuid);
```
https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-SET say:
> If there is no such setting, current_setting throws an error unless missing_ok is supplied and is true (in which case NULL is returned).
So we get `NULL`, which is cast to `uuid` as an empty string, and then the query is unhappy of course.

Might the solution be to craft a better policy that can handle empty strings?

**Comment by jasonmacdonald** [comment]
I ended up abandoning RLS with Prisma. There are too many problems with nested transactions, extensions, typing, etc., and too many factors that break things. Sorry.
