### ISSUE TITLE
I am new to PRISMA /. i am not able to install via  NPM .. can some body help ?

### ISSUE THREAD

**Issue by panindra2017** [prisma/prisma#2041]
Hi , I am getting error in installing PRISMA ,can you help whats the issue ,

```
PS F:\prisma\demoOne> npm install @prisma/cli
@prisma/cli@2.0.0-beta.1 preinstall F:\prisma\demoOne\node_modules\@prisma\cli
node preinstall/index.js
internal/fs/utils.js:230
throw err;
^
Error: ENOENT: no such file or directory, lstat 'C:\Users\vinsmart\AppData\Roaming\npm\node_modules'
at Object.realpathSync (fs.js:1588:7)
at Object.794 (F:\prisma\demoOne\node_modules\@prisma\cli\preinstall\index.js:1:53017)
at __webpack_require__ (F:\prisma\demoOne\node_modules\@prisma\cli\preinstall\index.js:1:154)
at Object.500 (F:\prisma\demoOne\node_modules\@prisma\cli\preinstall\index.js:1:30472)
at __webpack_require__ (F:\prisma\demoOne\node_modules\@prisma\cli\preinstall\index.js:1:154)
at startup (F:\prisma\demoOne\node_modules\@prisma\cli\preinstall\index.js:1:291)
at module.exports.8 (F:\prisma\demoOne\node_modules\@prisma\cli\preinstall\index.js:1:346)
at Object.<anonymous> (F:\prisma\demoOne\node_modules\@prisma\cli\preinstall\index.js:1:356)
at Module._compile (internal/modules/cjs/loader.js:1147:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10) {
errno: -4058,
syscall: 'lstat',
code: 'ENOENT',
path: 'C:\\Users\\vinsmart\\AppData\\Roaming\\npm\\node_modules'
}
npm WARN demoOne@1.0.0 No description
npm WARN demoOne@1.0.0 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @prisma/cli@2.0.0-beta.1 preinstall: node preinstall/index.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @prisma/cli@2.0.0-beta.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\vinsmart\AppData\Roaming\npm-cache\_logs\2020-04-01T16_24_20_406Z-debug.log
PS F:\prisma\demoOne> npm install @prisma/cli
@prisma/cli@2.0.0-beta.1 preinstall F:\prisma\demoOne\node_modules\@prisma\cli
node preinstall/index.js

**Comment by janpio** [comment]
hey @panindra2017, that is a nasty bug - sorry! You might be able to work around it by creating the folder `C:\Users\vinsmart\AppData\Roaming\npm\node_modules` manually if it does not exist yet. Does that help?

**Comment by timsuchanek** [comment]
We just added a fix to make this code fail silently, so you should not hit this situation anymore.

Please try out `npm install @prisma/cli@alpha` and let us know if this works for you 🙏

**Comment by pantharshit00** [comment]
@panindra2017 Can you please try this again? 

Please `npm install @prisma/cli@alpha` and let us know if that still errors out for you.

**Comment by pantharshit00** [comment]
Closing due to inactivity. Please comment here or open a new issue if you are still seeing this.

**Comment by Wyndham007** [comment]
I'm getting this error on my AWS EC2 instance. This npm install @prisma/cli@alpha is not working. Any idea?

**Comment by janpio** [comment]
Please open a new issue and include all the information the issue template asks for @Wyndham007 - then we can debug and help you.

**Comment by zayabattogtokh** [comment]
It's solved after the following steps:
- npm i @prisma/client@2.7.1
- npm install -g yarn
   > yarn add --dev prisma@latest
   > yarn add @prisma/client@latest
