### ISSUE TITLE
SQL-Lite: BigInt for autoincrement id column causes runtime Null constraint violation".

### ISSUE THREAD

**Issue by rehaldinho64** [prisma/prisma#20449]
### Bug description

When using SQLite as the database, Prisma allows the use of the BigInt datatype for the id column with the autoincrement property. SQLite, however, doesn't have a dedicated BIGINT type. Despite this mismatch, Prisma migrates the schema successfully. Yet, when I try to insert a new record into the table, I encounter a Null constraint violation on the fields: (id) error.

### How to reproduce

  model CarEngine {
    id BigInt @id @default(autoincrement())
    createdAt DateTime @default(now())
    modifiedAt DateTime @updatedAt
    name String
    hp  Int
    cars Car[]
  }

### Expected behavior

Prisma should either:

Provide a warning or error during the migration process, indicating the incompatibility of BigInt with SQLite.
Handle the BigInt datatype gracefully during runtime without errors.

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by janpio** [comment]
So a simple `create` for your datamodel with no `id` value provided should trigger an error?

**Comment by rehaldinho64** [comment]
> So a simple `create` for your datamodel with no `id` value provided should trigger an error?

Exactly. When performing a simple create operation without manually providing an id (since it should be auto-generated), I encounter the "Null constraint violation on the fields: (id)" error.

**Comment by janpio** [comment]
I can confirm the error you are seeing:
```
prisma:error
Invalid `prisma.carEngine.create()` invocation in
C:\Users\Jan\Documents\throwaway\20449\script.js:31:41

  28 })
  29
  30 async function main() {
→ 31   const engine = await prisma.carEngine.create(
Null constraint violation on the fields: (`id`)
PrismaClientKnownRequestError:
Invalid `prisma.carEngine.create()` invocation in
C:\Users\Jan\Documents\throwaway\20449\script.js:31:41

  28 })
  29
  30 async function main() {
→ 31   const engine = await prisma.carEngine.create(
Null constraint violation on the fields: (`id`)
    at Hr.handleRequestError (C:\Users\Jan\Documents\throwaway\20449\node_modules\@prisma\client\runtime\library.js:122:6999)
    at Hr.handleAndLogRequestError (C:\Users\Jan\Documents\throwaway\20449\node_modules\@prisma\client\runtime\library.js:122:6388)
    at Hr.request (C:\Users\Jan\Documents\throwaway\20449\node_modules\@prisma\client\runtime\library.js:122:6108)
    at async l (C:\Users\Jan\Documents\throwaway\20449\node_modules\@prisma\client\runtime\library.js:126:10298)
    at async main (C:\Users\Jan\Documents\throwaway\20449\script.js:31:18) {
  code: 'P2011',
  clientVersion: '5.1.1',
  meta: { constraint: [ 'id' ] }
}
```

The underlying reason is different though:
```
Query: INSERT INTO `main`.`CarEngine` (`createdAt`, `modifiedAt`, `name`, `hp`) VALUES (?,?,?,?) RETURNING `id` AS `id`
Params: ["2023-08-03 12:47:15.709 UTC","2023-08-03 12:47:15.709 UTC","V8",500]
```

It seems Prisma does not actually supply a `id` value in the query it generates. 
When I provide a value myself, it stores the data just fine:
<img width="688" alt="image" src="https://github.com/prisma/prisma/assets/183673/2b453f0c-1df5-4dca-beb5-aaa3125d5d77">

**Comment by janpio** [comment]
https://www.sqlite.org/autoinc.html explicitly documents that `AUTOINCREMENT` is for `INTEGER PRIMARY KEY` only. But after reading this I am still unclear, or even more unclear, why `BIGINT NOT NULL PRIMARY KEY` itself is not enough. (Maybe again that weird type system...)

**Comment by janpio** [comment]
Related: https://github.com/prisma/prisma/issues/13178

**Comment by iorzt** [comment]
here is a discussion related to the question on sqite
https://sqlite.org/forum/info/2dfa968a702e1506e885cb06d92157d492108b22bf39459506ab9f7125bca7fd

**Comment by JonathanWilbur** [comment]
This is still happening as of Prisma 7 using the SQLite adapter.
