### ISSUE TITLE
Upsert: InterpretationError("Unable to convert expression result into a set of selection results", None)

### ISSUE THREAD

**Issue by teaguestockwell** [prisma/prisma#20448]
### Bug description

```
2023-07-29T03:01:27.583Z prisma:client  Prisma Client call:
2023-07-29T03:01:27.583Z prisma:client  prisma.user.upsert({
  where: {
    email: "foobarbaz@gmail.com"
  },
  create: {
    email: "foobarbaz@gmail.com",
    name: "Teague Stockwell",
    profileSrc: "https://lh3.googleusercontent.com/a/foobarbaz"
  },
  update: {
    email: "foobarbaz@gmail.com",
    name: "Teague Stockwell",
    profileSrc: "https://lh3.googleusercontent.com/a/foobarbaz"
  }
})
2023-07-29T03:01:27.585Z prisma:client  Generated request:
2023-07-29T03:01:27.585Z prisma:client  {
  "modelName": "User",
  "action": "upsertOne",
  "query": {
    "arguments": {
      "where": {
        "email": "foobarbaz@gmail.com"
      },
      "create": {
        "email": "foobarbaz@gmail.com",
        "name": "Teague Stockwell",
        "profileSrc": "https://lh3.googleusercontent.com/a/foobarbaz"
      },
      "update": {
        "email": "foobarbaz@gmail.com",
        "name": "Teague Stockwell",
        "profileSrc": "https://lh3.googleusercontent.com/a/foobarbaz"
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true
    }
  }
}

2023-07-29T03:01:27.585Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
2023-07-29T03:01:27.606Z prisma:client:request_handler  PrismaClientKnownRequestError: Query interpretation error. Error for binding '6': Error occurred during query execution:
InterpretationError("Unable to convert expression result into a set of selection results", None)
    at ko (/Users/teaguestockwell/src/buildable/node_modules/@prisma/client/runtime/library.js:26:6409)
    at _t.buildQueryError (/Users/teaguestockwell/src/buildable/node_modules/@prisma/client/runtime/library.js:104:902)
    at _t.request (/Users/teaguestockwell/src/buildable/node_modules/@prisma/client/runtime/library.js:103:4117)
    at async Object.singleLoader (/Users/teaguestockwell/src/buildable/node_modules/@prisma/client/runtime/library.js:122:6714)
    at async zr.request (/Users/teaguestockwell/src/buildable/node_modules/@prisma/client/runtime/library.js:122:7206)
    at async Object.jwt (webpack-internal:///(api)/./src/pages/api/auth/[...nextauth].ts:71:13)
    at async Object.callback (/Users/teaguestockwell/src/buildable/node_modules/next-auth/core/routes/callback.js:135:25)
    at async AuthHandler (/Users/teaguestockwell/src/buildable/node_modules/next-auth/core/index.js:201:28)
    at async NextAuthHandler (/Users/teaguestockwell/src/buildable/node_modules/next-auth/next/index.js:24:19)
    at async /Users/teaguestockwell/src/buildable/node_modules/next-auth/next/index.js:60:32
    at async Object.apiResolver (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async DevServer.runApi (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/router.js:253:36)
    at async DevServer.run (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/base-server.js:384:29)
    at async DevServer.run (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/dev/next-dev-server.js:743:20)
    at async DevServer.handleRequest (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/base-server.js:322:20) {
  code: 'P2016',
  clientVersion: '5.0.0',
  meta: {
    details: "Error for binding '6': Error occurred during query execution:\n" +
      'InterpretationError("Unable to convert expression result into a set of selection results", None)'
  }
}
prisma:error 
Invalid `prisma.user.upsert()` invocation:


Query interpretation error. Error for binding '6': Error occurred during query execution:
InterpretationError("Unable to convert expression result into a set of selection results", None)
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error 
Invalid `prisma.user.upsert()` invocation:


Query interpretation error. Error for binding '6': Error occurred during query execution:
InterpretationError("Unable to convert expression result into a set of selection results", None) {
  message: '\n' +
    'Invalid `prisma.user.upsert()` invocation:\n' +
    '\n' +
    '\n' +
    "Query interpretation error. Error for binding '6': Error occurred during query execution:\n" +
    'InterpretationError("Unable to convert expression result into a set of selection results", None)',
  stack: 'PrismaClientKnownRequestError: \n' +
    'Invalid `prisma.user.upsert()` invocation:\n' +
    '\n' +
    '\n' +
    "Query interpretation error. Error for binding '6': Error occurred during query execution:\n" +
    'InterpretationError("Unable to convert expression result into a set of selection results", None)\n' +
    '    at zr.handleRequestError (/Users/teaguestockwell/src/buildable/node_modules/@prisma/client/runtime/library.js:122:8308)\n' +
    '    at zr.handleAndLogRequestError (/Users/teaguestockwell/src/buildable/node_modules/@prisma/client/runtime/library.js:122:7697)\n' +
    '    at zr.request (/Users/teaguestockwell/src/buildable/node_modules/@prisma/client/runtime/library.js:122:7307)\n' +
    '    at async Object.jwt (webpack-internal:///(api)/./src/pages/api/auth/[...nextauth].ts:71:13)\n' +
    '    at async Object.callback (/Users/teaguestockwell/src/buildable/node_modules/next-auth/core/routes/callback.js:135:25)\n' +
    '    at async AuthHandler (/Users/teaguestockwell/src/buildable/node_modules/next-auth/core/index.js:201:28)\n' +
    '    at async NextAuthHandler (/Users/teaguestockwell/src/buildable/node_modules/next-auth/next/index.js:24:19)\n' +
    '    at async /Users/teaguestockwell/src/buildable/node_modules/next-auth/next/index.js:60:32\n' +
    '    at async Object.apiResolver (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
    '    at async DevServer.runApi (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/next-server.js:488:9)\n' +
    '    at async Object.fn (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/next-server.js:751:37)\n' +
    '    at async Router.execute (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/router.js:253:36)\n' +
    '    at async DevServer.run (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/base-server.js:384:29)\n' +
    '    at async DevServer.run (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/dev/next-dev-server.js:743:20)\n' +
    '    at async DevServer.handleRequest (/Users/teaguestockwell/src/buildable/node_modules/next/dist/server/base-server.js:322:20)',
  name: 'PrismaClientKnownRequestError'
}
```

### How to reproduce

when a users signs in, the jwt callback from the file "[...nextauth].ts" upserts a user
```ts
  callbacks: {
    async jwt({
      token: {email, name, picture}
    }) {
      if (
        !email ||
        !name ||
        typeof email !== 'string' ||
        typeof name !== 'string' ||
        (typeof picture !== 'string' || typeof picture !== 'undefined')
      ) {
        throw new Error('malformed token')
      }
      const next = {email, name, profileSrc: picture}
      await client.user.upsert({
        where: {email},
        create: next,
        update: next,
      })
      return token
    },
  },
```

### Expected behavior

- the usert works as expected using 4.3.0 of @prisma/client and prisma works as expected
- creating a user on the same connected database from prisma studio with the same data using 5.0.0 also works as expected

### Prisma information

schema.prisma
```
datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  email  String @id @db.VarChar(256)
  userId String @unique @default(cuid()) @db.VarChar(64)

  name            String   @db.VarChar(128)
  createdAt       DateTime @default(now()) @db.DateTime(0)
  updatedAt       DateTime @updatedAt @db.DateTime(0)
  profileSrc      String?  @db.VarChar(128)
  profilePicS3Key String?  @db.VarChar(128)
  about           String?  @db.VarChar(256)
  profileViews    Int      @default(0) @db.UnsignedInt
  postViews       Int      @default(0) @db.UnsignedInt
  numFollowers    Int      @default(0) @db.UnsignedInt

  posts           Post[]      @relation("posted")
  comments        Comment[]   @relation("commented")
  likedComments   Comment[]   @relation("likedComments")
  likedPosts      Post[]      @relation("likedPosts")
  savedComments   Comment[]   @relation("savedComments")
  savedPosts      Post[]      @relation("savedPosts")
  topics          Topic[]     @relation("topics")
  usersFollowing  User[]      @relation("followingUsers")
  usersFollowedBy User[]      @relation("followingUsers")
  moderatesTopics Topic[]     @relation("moderatedTopics")
  pics            Pic[]
  rateLimits      RateLimit[]

  @@unique([email, userId])
  @@index([name])
  @@index([userId])
}
```

### Environment & setup

- OS: macos 12.6.3
- Database: MySQL 8.0.27-1debian10
- Node.js version: 18.14.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.0.0
@prisma/client          : 5.0.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Schema Engine           : schema-engine-cli 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules/@prisma/engines/schema-engine-darwin)
Schema Wasm             : @prisma/prisma-schema-wasm 4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Default Engines Hash    : 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Studio                  : 0.487.0
Preview Features        : referentialIntegrity
```

**Comment by teaguestockwell** [comment]
@Weakky Thanks for looking into this. I made a [repo](https://github.com/teaguestockwell/prisma-upsert-repro) that is setup to repro the issue. I also upgrade to the latest versions of prisma and prisma client: 5.1.1.1

Here are the steps to repro. The first upsert works, but the second fails:
1. git clone https://github.com/teaguestockwell/prisma-upsert-repro.git
1. cd prisma-upsert-repro
1. yarn
1. yarn db:up
1. yarn upsert
1. yarn upsert

I noticed removing all the related models from user fixes the issue:
1. git reset --hard HEAD~
1. yarn db:up
1. yarn upsert
1. yarn upsert

I wonder if I am doing something I'm not supposed to in models related to user?

**Comment by trevorr** [comment]
We also hit this error when attempting to upgrade from Prisma 4.14 to 5.3 on Postgres:

> Invalid `prisma.loan.update()` invocation:
> Query interpretation error. Error for binding '603': Error occurred during query execution:
> InterpretationError("Unable to convert expression result into a set of selection results", None)

Unfortunately, it only occurs during a very complex, deeply nested upsert of nearly 5000 lines of formatted JSON. We're still trying to narrow it down.

**Comment by trevorr** [comment]
@Weakky Do you know how I could figure out what binding 603 refers to?

**Comment by yovanoc** [comment]
I have same issue with big queries so didn't narrow it down yet too but for now I noticed that replacing upsert with update give the same error and removing some fields to update remove the error too as if there was a limit or something

**Comment by trevorr** [comment]
This error appears to essentially be an assert in [`ExpressionResult.as_selection_results`](https://github.com/prisma/prisma-engines/blob/3ef05ffb36cba7bf2d6b2a395abfe466195b6fbb/query-engine/core/src/interpreter/interpreter_impl.rs#L51) that occurs when none of the patterns are matched. There's a trace message in there for one of the cases, but I wasn't able to get it to show up in the logging.

**Comment by nykolaslima** [comment]
@trevorr any update on how to solve it? I am seeing this error on version 5.1.1

**Comment by trevorr** [comment]
@nykolaslima No idea. We're stuck on 4.x until this bug is fixed. Hopefully someone on the Prisma team will give us some tips on how to narrow it down.

**Comment by trevorr** [comment]
@janpio This is happening for us on Postgres, so maybe the issue labels need updating?

**Comment by janpio** [comment]
I can reproduce with the reproduction repository provided:
```
gitpod /workspace/prisma-upsert-repro (main) $ yarn upsert
yarn run v1.22.19
$ DATABASE_URL=mysql://user:password@localhost:3306/db ts-node ./upsert.ts
┌─────────────────┬─────────────────────────────────────────────────┐
│     (index)     │                     Values                      │
├─────────────────┼─────────────────────────────────────────────────┤
│      email      │              'foobarbaz@gmail.com'              │
│     userId      │           'clms9kivo0000ox8knjpi0y3q'           │
│      name       │               'Teague Stockwell'                │
│    createdAt    │                                                 │
│    updatedAt    │                                                 │
│   profileSrc    │ 'https://lh3.googleusercontent.com/a/foobarbaz' │
│ profilePicS3Key │                      null                       │
│      about      │                      null                       │
│  profileViews   │                        0                        │
│    postViews    │                        0                        │
│  numFollowers   │                        0                        │
└─────────────────┴─────────────────────────────────────────────────┘
Done in 1.63s.
gitpod /workspace/prisma-upsert-repro (main) $ yarn upsert
yarn run v1.22.19
$ DATABASE_URL=mysql://user:password@localhost:3306/db ts-node ./upsert.ts
PrismaClientKnownRequestError: 
Invalid `client.user.upsert()` invocation in
/workspace/prisma-upsert-repro/upsert.ts:6:33

  3 async function main() {
  4   const client = new PrismaClient();
  5 
→ 6   const res = await client.user.upsert(
Query interpretation error. Error for binding '6': Error occurred during query execution:
InterpretationError("Unable to convert expression result into a set of selection results", None)
    at Hr.handleRequestError (/workspace/prisma-upsert-repro/node_modules/@prisma/client/runtime/library.js:122:6999)
    at Hr.handleAndLogRequestError (/workspace/prisma-upsert-repro/node_modules/@prisma/client/runtime/library.js:122:6388)
    at Hr.request (/workspace/prisma-upsert-repro/node_modules/@prisma/client/runtime/library.js:122:6108)
    at async l (/workspace/prisma-upsert-repro/node_modules/@prisma/client/runtime/library.js:126:10298) {
  code: 'P2016',
  clientVersion: '5.1.1',
  meta: {
    details: "Error for binding '6': Error occurred during query execution:\n" +
      'InterpretationError("Unable to convert expression result into a set of selection results", None)'
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by janpio** [comment]
@trevorr Are you also using `relationMode="prisma"`? 
Do you have a reproduction for PostgreSQL similar to the one @teaguestockwell had provided for MySQL?

**Comment by trevorr** [comment]
@janpio No, we're not using `relationMode`, so we have foreign keys in the database.

No, we don't have a reproduction we can share because the only failing test case is a huge, generated, deeply nested upsert of hundreds of records across dozens of models (used for bulk data import). It would take a long time to narrow it down manually, so my hope was to debug it through logging.

**Comment by janpio** [comment]
Ok, that made me confirm that @teaguestockwell's problem is triggered by `relationMode = "prisma"`. When that is removed from the schema, and `prisma generate` is run, you can run `yarn upsert` multiple times without it triggering the problem. The generated SQL queries then look like this:
```
prisma:query BEGIN
prisma:query SELECT `db`.`User`.`email` FROM `db`.`User` WHERE (`db`.`User`.`email` = ? AND 1=1)
prisma:query SELECT `db`.`User`.`email` FROM `db`.`User` WHERE (`db`.`User`.`email` = ? AND 1=1)
prisma:query UPDATE `db`.`User` SET `email` = ?, `name` = ?, `profileSrc` = ?, `updatedAt` = ? WHERE (`db`.`User`.`email` IN (?) AND (`db`.`User`.`email` = ? AND 1=1))
prisma:query SELECT `db`.`User`.`email`, `db`.`User`.`userId`, `db`.`User`.`name`, `db`.`User`.`createdAt`, `db`.`User`.`updatedAt`, `db`.`User`.`profileSrc`, `db`.`User`.`profilePicS3Key`, `db`.`User`.`about`, `db`.`User`.`profileViews`, `db`.`User`.`postViews`, `db`.`User`.`numFollowers` FROM `db`.`User` WHERE `db`.`User`.`email` = ? LIMIT ? OFFSET ?
prisma:query COMMIT
```

@trevorr That tells me that you have a different problem than Teague. Optimally open a new issue and mention explicity that you are _not_ using `relationMode=prisma`. But please provide some information on which database you are using, OS, and so no - all the things that could have an impact here.

@yovanoc @nykolaslima Are you using `relationMode=prisma` or not? Depending on your answer, you should comment on the new issue that Trevor will create.

**Comment by yovanoc** [comment]
I'm not using it so I will wait the other issue

**Comment by trevorr** [comment]
@janpio @yovanoc I created #21182 for _not_ using `relationMode=prisma`.

**Comment by def-ilya** [comment]
Experiencing this one as well. 
For our use case, we've got a an "update" clause, within which is a "create" or "upsert" clause that always fails. 

Here's a contrived example: 
```
        { id: userAcc.id },
        {
          AccountDetails: {
            update: {
              fieldToUpdate: { /*any form of create or upsert here fails*/ },
            },
          },
        }
```

**Comment by janpio** [comment]
So to pinpoint when this broke.

It still worked in 4.5.0:
```
PS C:\Users\Jan\Documents\throwaway\prisma-upsert-repro> yarn prisma generate
yarn run v1.22.18
$ C:\Users\Jan\Documents\throwaway\prisma-upsert-repro\node_modules\.bin\prisma generate
Prisma schema loaded from schema.prisma

✔ Generated Prisma Client (4.5.0 | library) to .\node_modules\@prisma\client in 358ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
┌─────────────────────────────────────────────────────────┐
│  Update available 4.5.0 -> 5.3.1                        │
│                                                         │
│  This is a major update - please follow the guide at    │
│  https://pris.ly/d/major-version-upgrade                │
│                                                         │
│  Run the following to update                            │
│    yarn add --dev prisma@latest                         │
│    yarn add @prisma/client@latest                       │
└─────────────────────────────────────────────────────────┘
Done in 3.89s.
PS C:\Users\Jan\Documents\throwaway\prisma-upsert-repro> yarn clean 
yarn run v1.22.18
$ cross-env DATABASE_URL=mysql://user:password@localhost:3306/db ts-node ./clean.ts
┌─────────┬────────┐
│ (index) │ Values │
├─────────┼────────┤
│  count  │   1    │
└─────────┴────────┘
Done in 2.29s.
PS C:\Users\Jan\Documents\throwaway\prisma-upsert-repro> yarn upsert
>>
yarn run v1.22.18
$ cross-env DATABASE_URL=mysql://user:password@localhost:3306/db ts-node ./upsert.ts
┌─────────────────┬─────────────────────────────────────────────────┐
│     (index)     │                     Values                      │
├─────────────────┼─────────────────────────────────────────────────┤
│      email      │              'foobarbaz@gmail.com'              │
│     userId      │           'clmur8wza000040y4txaf9lhj'           │
│      name       │               'Teague Stockwell'                │
│    createdAt    │                                                 │
│    updatedAt    │                                                 │
│   profileSrc    │ 'https://lh3.googleusercontent.com/a/foobarbaz' │
│ profilePicS3Key │                      null                       │
│      about      │                      null                       │
│  profileViews   │                        0                        │
│    postViews    │                        0                        │
│  numFollowers   │                        0                        │
└─────────────────┴─────────────────────────────────────────────────┘
Done in 2.35s.
PS C:\Users\Jan\Documents\throwaway\prisma-upsert-repro> yarn upsert
>>
yarn run v1.22.18
$ cross-env DATABASE_URL=mysql://user:password@localhost:3306/db ts-node ./upsert.ts
┌─────────────────┬─────────────────────────────────────────────────┐
│     (index)     │                     Values                      │
├─────────────────┼─────────────────────────────────────────────────┤
│      email      │              'foobarbaz@gmail.com'              │
│     userId      │           'clmur8wza000040y4txaf9lhj'           │
│      name       │               'Teague Stockwell'                │
│    createdAt    │                                                 │
│    updatedAt    │                                                 │
│   profileSrc    │ 'https://lh3.googleusercontent.com/a/foobarbaz' │
│ profilePicS3Key │                      null                       │
│      about      │                      null                       │
│  profileViews   │                        0                        │
│    postViews    │                        0                        │
│  numFollowers   │                        0                        │
└─────────────────┴─────────────────────────────────────────────────┘
Done in 2.27s.
```

And broke in 4.6.0:
```
PS C:\Users\Jan\Documents\throwaway\prisma-upsert-repro> yarn prisma generate
yarn run v1.22.18
$ C:\Users\Jan\Documents\throwaway\prisma-upsert-repro\node_modules\.bin\prisma generate
Prisma schema loaded from schema.prisma

✔ Generated Prisma Client (4.6.0 | library) to .\node_modules\@prisma\client in 714ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
Done in 5.00s.
PS C:\Users\Jan\Documents\throwaway\prisma-upsert-repro> yarn clean 
yarn run v1.22.18
$ cross-env DATABASE_URL=mysql://user:password@localhost:3306/db ts-node ./clean.ts
┌─────────┬────────┐
│ (index) │ Values │
├─────────┼────────┤
│  count  │   1    │
└─────────┴────────┘
Done in 2.44s.
PS C:\Users\Jan\Documents\throwaway\prisma-upsert-repro> yarn upsert
>>
yarn run v1.22.18
$ cross-env DATABASE_URL=mysql://user:password@localhost:3306/db ts-node ./upsert.ts
┌─────────────────┬─────────────────────────────────────────────────┐
│     (index)     │                     Values                      │
├─────────────────┼─────────────────────────────────────────────────┤
│      email      │              'foobarbaz@gmail.com'              │
│     userId      │           'clmur7ohm000040mgs1pgoaew'           │
│      name       │               'Teague Stockwell'                │
│    createdAt    │                                                 │
│    updatedAt    │                                                 │
│   profileSrc    │ 'https://lh3.googleusercontent.com/a/foobarbaz' │
│ profilePicS3Key │                      null                       │
│      about      │                      null                       │
│  profileViews   │                        0                        │
│    postViews    │                        0                        │
│  numFollowers   │                        0                        │
└─────────────────┴─────────────────────────────────────────────────┘
Done in 2.33s.
PS C:\Users\Jan\Documents\throwaway\prisma-upsert-repro> yarn upsert
>> 
yarn run v1.22.18
$ cross-env DATABASE_URL=mysql://user:password@localhost:3306/db ts-node ./upsert.ts
PrismaClientKnownRequestError: 
Invalid `client.user.upsert()` invocation in
C:\Users\Jan\Documents\throwaway\prisma-upsert-repro\upsert.ts:6:33

  3 async function main() {
  4   const client = new PrismaClient();
  5
→ 6   const res = await client.user.upsert(
Query interpretation error. Error for binding '6': Error occurred during query execution:
InterpretationError("Unable to convert expression result into a set of selection results", None)
    at RequestHandler.handleRequestError (C:\Users\Jan\Documents\throwaway\prisma-upsert-repro\node_modules\@prisma\client\runtime\index.js:34310:13)
    at RequestHandler.request (C:\Users\Jan\Documents\throwaway\prisma-upsert-repro\node_modules\@prisma\client\runtime\index.js:34293:12)   
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\prisma-upsert-repro\node_modules\@prisma\client\runtime\index.js:35273:16) {
  code: 'P2016',
  clientVersion: '4.6.0',
  meta: {
    details: "Error for binding '6': Error occurred during query execution:\n" +
      'InterpretationError("Unable to convert expression result into a set of selection results", None)'
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cesarve77** [comment]
+1

**Comment by cesarve77** [comment]
No sure if it solved, I had this problem before and I had to downgrade to prisma 4.5, I was working fine, today I give another try to prisma 5.8.1 and seems to be working for me.
