### ISSUE TITLE
Support Vercel Edge Runtime

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#20566]
## Problem

Prisma Client currently does not work in the [Vercel Edge Runtime](https://vercel.com/docs/concepts/functions/edge-functions/edge-runtime), which is used to run Edge Functions by Vercel. Vercel's Edge Runtime is automatically used to run the API endpoint of your Next.js app [when you define `export const runtime = "nodejs"` for your routes](https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes#segment-runtime-option).

When trying to build your app, you get an error like this:

```
... 
- info Collecting page data ../workspace/next13-prisma-edge/.next/server/app/api/data/route.js:25

Error: PrismaClient is unable to be run under the Vercel Edge Runtime.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new t.PrismaClient (/workspace/next13-prisma-edge/.next/server/app/api/data/route.js:25:811)
    at 126 (/workspace/next13-prisma-edge/.next/server/app/api/data/route.js:13:48830)
    
... 
```
## Suggested solution

Prisma needs to improve the support for the Edge Runtime and Edge Functions. Because of the platform limitations, that will always work slightly differently than using Prisma in a Node.js or serverless environment, but we will do our best to communicate that via documentation.

Additionally, Prisma should implement support for serverless database drivers from databases like [PlanetScale](https://github.com/prisma/prisma/issues/15265) and [Neon](https://github.com/prisma/prisma/issues/19409), which are tailor-made for such use cases and will make it much easier to use Prisma in such environments.

## Alternatives

There are two workarounds right now:
1. Use [Prisma DataProxy](https://www.prisma.io/data-platform/proxy) to talk to your database and generate your Client with `prisma generate --data-proxy`, then import `@prisma/client/edge` into your app. This will generate an edge-optimized Prisma Client that talks to Dataproxy via HTTP.
2. Do not use the edge runtime. `export const runtime = "nodejs";` will configure your project to deploy its API functions as a _serverless_ function, which Prisma supports already as it has the necessary functionality.

## Additional context

We are working on supporting the Vercel Edge Runtime, and Edge Functions in general, better in Prisma **right now**. Please follow this issue for updates.

**Comment by styxlab** [comment]
@janpio thanks for looking into that :-) I am currently creating a new node api endpoint for every call to prisma from the edge. Native support for edge functions would reduce my code and accelerate response times.

**Comment by juanwall** [comment]
> Additionally, Prisma should implement support for serverless database drivers from databases like https://github.com/prisma/prisma/issues/15265 and https://github.com/prisma/prisma/issues/19409, which are tailor-made for such use cases and will make it much easier to use Prisma in such environments.

This is a great idea. I use Planetscale, and I agree that it's tailor-made for these use cases.

**Comment by janpio** [comment]
Hey, we at Prisma have been working on the foundations for Edge Functions support for the past few weeks. Soon, we'll have something to share and test! If you are interested in helping us, please respond to this super short survey and leave your email address so we can get in touch with instructions: https://pris.ly/survey/driver-adapter-vercel-edge Thanks.

**Comment by dBianchii** [comment]
Does this have an ETA? 

I really want to use Prisma on edge. Will it eventually be available? Or is this something that the Prisma team is just looking into / analyzing the possibilities and that will not necessarily happen?

It's important for me to know, because I am considering wether or not if I should stick to prisma or if it's best to use some other ORM that supports edge natively.

If the support for edge will come eventually, I'm all in. Even if it takes a while

**Comment by janpio** [comment]
> Does this have an ETA?

No, we never publish ETAs.

> If the support for edge will come

Yes. We are planning to share an early access with participants of our survey in days or weeks, not months. Afterwards you can expect a public preview release as well depending on that feedback.

**Comment by the-me-0** [comment]
Hi prisma team ! How is this issue going ?
I just fell agains it while trying to access my self-hosted DB on my nextjs project startup (to check/generate an api-key). Accessing database from this edge environment isn't yet supported I see.
Any info on the public preview release ?

**Comment by janpio** [comment]
First users are currently trying the early access version and are giving feedback on how it is going.
Make sure you have answered the survey if you want to be considered as well: https://github.com/prisma/prisma/issues/20566#issuecomment-1718352808

**Comment by styxlab** [comment]
Any chance, supabase is supported too? As supabase-js client can be run from next.js edge functions, I think this should be possible. Would be happy to test it.

**Comment by janpio** [comment]
Prisma ORM unfortunately can not support the Supabase JS Client, as it does not offer the adequate database-like APIs that Prisma's query engine requires to talk to a database. If you want to use the Supabase JS Client, you will need to use it directly without Prisma as your ORM. 
Prisma does support talking to the PostgreSQL database that Supabase offer though directly on all platforms that allow connections to PostgreSQL databases (which in the case of edge functions is Cloudflare Workers).

**Comment by styxlab** [comment]
Thanks for the quick answer. Yes, I am aware of the current possibilities. I was mentioning supabase-js only because it works with edge runtimes. That's why I am hoping that prisma can provide an edge adapter for supabase too. Isn't that technically possible?

**Comment by janpio** [comment]
Not really in our current understanding, as the supabase-js API is not the same as the direct SQL interface to a relational database. Many advanced queries would need to be executed via multiple calls, get a lot more data than needed, and then the datasets to be combined manually in memory. That will lead to suboptimal performance, and some queries will not be possible at all. 

(Happy to be proven wrong of course, our driver adapters are all open source and can be found in the `prisma/prisma` repository - the API is pretty minimal. See https://github.com/tidbcloud/prisma-adapter for an early example for a third party driver adapter as an example)

**Comment by styxlab** [comment]
@kincaidoneil Very cool. That's what I have been looking for. Will give it a try!

**Comment by styxlab** [comment]
@kincaidoneil I tried your suggestion on Vercel, an am getting the following error during runtime execution (deploy went fine):
````
 PrismaClientValidationError: PrismaClient failed to initialize because it wasn't configured to run in this environment (edge-light).
In order to run Prisma Client in an edge runtime, you will need to configure Accelerate: https://pris.ly/d/accelerate.
    at (node_modules/@prisma/client/runtime/wasm.js:13:313)
    at (node_modules/@prisma/client/runtime/wasm.js:27:5412)
    at (build/build-edge-eyJydW50aW1lIjoiZWRnZSJ9.js:6418:0)
    at (build/server-build-edge-eyJydW50aW1lIjoiZWRnZSJ9.mjs:2:23)
    at (start-confirm/:token:middleware.js:1:17) {
  name: 'PrismaClientValidationError',
  clientVersion: '5.11.0-dev.5'
}
```
What am I doing wrong?

**Comment by janpio** [comment]
Are you part of the [Early Access](https://github.com/prisma/prisma/issues/20566#issuecomment-1718352808) already @styxlab? If not, the instructions on how to use Prisma ORM on Edge Function deployments are not public yet - which would lead to the error message you shared.

**Comment by styxlab** [comment]
@janpio Yes, I am part of Early Access, and I now managed to get prisma working on the edge with supabase (postresql). So, I have an example with nextjs (prisma-edge-supabase) and one for remix both deployed to vercel edge. There are a few gotchas in terms of configuration and setup and I am also not super impressed by the performance (would have expected faster response times on the edge). Though it's great to be able to get it running in an experimental way.

Are you interested in making my experiments public here, or is that something that should be kept privaze as part of the early access phase?

**Comment by janpio** [comment]
Please just send them over via email for now. We are still honing in on the DX of the feature, so hopefully a  lot of the gotchas are removed soon. (Performance is mostly dependent on the database drivers being used. Often talking to a database from an edge function is actually slower depending on your location and setup - it's all about tradeoffs.)

**Comment by janpio** [comment]
Hey everyone!

We just released [Prisma ORM version 5.11.0](https://github.com/prisma/prisma/releases/tag/5.11.0) which includes a preview feature for **Edge Functions support for [Vercel Edge Functions and Middleware](https://www.prisma.io/docs/orm/prisma-client/deployment/edge/deploy-to-vercel)** (and [Cloudflare Workers and Pages](https://www.prisma.io/docs/orm/prisma-client/deployment/edge/deploy-to-cloudflare)) in Prisma ORM 🥳 

- The release notes give a quick overview: https://github.com/prisma/prisma/releases/tag/5.11.0
- We also have extensive documentation: https://www.prisma.io/docs/orm/prisma-client/deployment/edge/overview
- Prisma ORM now supports drivers for Neon Database (and Vercel Postgres), PlanetScale and Turso via their serverless drivers on both Vercel.

Please give it a try, and let us know how it goes! If you encounter any problems, please create a [new bug report issue](https://github.com/prisma/prisma/issues/new/choose), or if the problem is driver adapter specific, use the feedback discussions for [`@prisma/adapter-neon`](https://github.com/prisma/prisma/discussions/21346), [`@prisma/adapter-planetscale`](https://github.com/prisma/prisma/discussions/21347), [`@prisma/adapter-libsql` / Turso] or (https://github.com/prisma/prisma/discussions/21345) 🙇

**Comment by styxlab** [comment]
Thanks a lot for this great work on edge function support!

Now that this is publicly released, I would like to give a quick summary on my recent findings. My use case is a bit different to what is documented here, as I want to use `postresql` on supabase with Vercel edge functions and not the Vercel built in database options.

However, the setup is almost the same, as this is also possible with the `@neon/serverless` driver. Nonethelss, my setup contains some key differences:

1. The Next.js config must enable WebAssembly (side note: not needed when using remix.run):
```
const nextConfig = {
    webpack(config, { isServer, dev }) {
        // Use the client static directory in the server bundle and prod mode
        // Fixes `Error occurred prerendering page "/"`
        config.output.webassemblyModuleFilename =
            isServer && !dev
                ? "../static/wasm/[modulehash].wasm"
                : "static/wasm/[modulehash].wasm";

        // Since Webpack 5 doesn't enable WebAssembly by default, we should do it manually
        config.experiments = { ...config.experiments, asyncWebAssembly: true };

        return config;
    },
};
```

2. Neon pool (and prisma!?) should diconnect within each handler (inspired from the @neon/serverless docs). If you don't do this, you risk exhaustsing your connection limits. For example:
```
export async function GET() {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const adapter = new PrismaNeon(pool);
  const prisma = new PrismaClient({ adapter });

  const oneUser = await prisma.user.findFirst();

  // end the `Pool` inside the same request handler
  // (unlike `await`, `waitUntil` won't hold up the response)
  // still getting prisma client warnings, why?
  waitUntil(async () => await prisma.$disconnect());
  waitUntil(async () => await pool.end());

  return Response.json({ oneUser });
}
```

3. Adapters increase the edge function size above 1MB even with the most simple handlers, which is outside the Vercel Hobby limits (mentioned also in the docs, thanks for that). On a typical function, I get an increase of more than 50% compared to before (without adapter option).

4. Performance: The biggest benefit is that cold start times of 1 - 2 seconds are absent on the edge. That's huge! But my excitement derailed quickly when I saw that mean response times are actually larger compared to the node handlers, and typical response times on the edge are around 500 ms, and almost never in the 50 ms range. I don't think this is related to regions (I have everything in `fra1`, but most probably due to the additional overhead of always needing to establish a new connection. This is just a first impression, more testing is needed here.

Finally, I want to say a big thank you to the Prisma team, you are always on the edge (pun intended!) :1st_place_medal:

**Comment by janpio** [comment]
> The Next.js config must enable WebAssembly (side note: not needed when using remix.run):

Is this still the case with the 5.11.0 release? We had hoped to get rid of that, if not please open a quick bug issue with a reproduction so we can dig into it. Thanks!

**Comment by styxlab** [comment]
> > The Next.js config must enable WebAssembly (side note: not needed when using remix.run):
> 
> Is this still the case with the 5.11.0 release? We had hoped to get rid of that, if not please open a quick bug issue with a reproduction so we can dig into it. Thanks!

I can confirm, WebAssembly in the next.js config is not needed anymore with 5.11.0 release.

**Comment by styxlab** [comment]
New observations. I get the following warning message, when triggering edge functions multiple times:
```
warn(prisma-client) This is the 10th instance of Prisma Client being started. Make sure this is intentional.
```
This is the case, even though I try to close the connection with every request as detailed in my previous post.

**Comment by datacrud8** [comment]
Hi @janpio 
Thank you for the  edge function support and its working with planetscale MySQL.
But in our case , we are running mysql in local , that means DATABASE_URL='mysql://ID:psswrd@localhost:3306/db?useSSL=false'

Then executed below commands and perfectly fine no issues.
npx prisma db push
npx prisma studio

But when I run the application, its throwing "fetch:failed" error.

Went through your document and seeing only cloud related configuration for edge solution . BUT not for local setup.  
    Cloudflare
        PostgreSQL (traditional)
        PlanetScale
        Neon
    Vercel
        Vercel Postgres
        Neon
        PlanetScale 

Do you have any example code/document for locally running mySQL setup to fix the edge function support?

Thank you.

**Comment by janpio** [comment]
Connecting to MySQL databases directly is currently not supported by Vercel or Cloudflare as there are no compatible database drivers. There _might_ be an edge compatible database driver for MySQL in the future, but until that is the case there is unfortunately nothing Prisma can do to help here talking to a MySQL database _directly_.

PlanetScale, which is MySQL under the hood, has its own Serverless Driver as a workaround that you can use - but it only works with PlanetScale MySQL servers as those provide the required "proxy" for that driver to connect to. PlanetScale does have a setup to use that database driver locally for testing as well, we use it ourselves at https://github.com/prisma/prisma/blob/b0b4fb3f76a0b93ed4ca77f33df0c0c87bc8bef4/docker/docker-compose.yml#L241-L256 - hopefully you can use that as inspiration. It is not really documented beyond that, you best ask PlanetScale what they recommend about this.

**Comment by andreimacavei** [comment]
Hi! Thanks for the support of Vercel Edge Runtime Functions.
Here is a problem that I get when I instatiate a prisma client as  documented and use it on a route with 'edge' runtime:

```code
 ⚠ ./node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/.prisma/client/wasm-edge-light-loader.js
The generated code contains 'async/await' because this module is using "topLevelAwait".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors
``` 

... and here is the code that throws this error:
```js
export async function GET(req: Request) {
  // Create a new Prisma client
  const neon = new Pool({ connectionString: process.env.POSTGRES_MICRO_AI_PRISMA_URL })
  const adapter = new PrismaNeon(neon)
  const prisma = new PrismaClient({ adapter })
  
 const user = await prisma.user.findUnique({
    where: {
      id: userId,
    },
  });

```
@janpio  I also want to know if this way of instantiating a Prisma Client on each function call is the best approach, as in other app components I'm using a global prisma client as from the docs https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices

**Comment by janpio** [comment]
Interesting and unexpected problem you are running in there. Can you open a new bug report issue and include the information it asks for? Optimally, maybe even for a small minimal project, we can just install and try to reproduce the problem - this might depend on all kinds of things in your app, so that would be the fastest way for us to reproduce - which we definitely want to be able to understand and fix this!

> I also want to know if this way of instantiating a Prisma Client on each function call is the best approach, as in other app components I'm using a global prisma client as from the docs

Yes, this is unfortunately a limitation of the edge runtimes. Connections can only be used in the request where they were created, if you try to reuse them this might initially even work - but as soon as one worker or environment is called to handle multiple requests at the same time (which can happen in these environments) your worker will crash with an exception.

(If you use a serverless driver that uses HTTP like for example the one for PlanetScale, there is no downside in starting a new Prisma Client instance with each request. For the others that is one of the reasons why one really has to look if talking to a database in an edge environment really makes sense and gives them the desired performance. [Cloudflare is working on a local connection pooler Hyperdrive to potentially minimize the impact of this, also works with Prisma already.])

**Comment by andreimacavei** [comment]
> Interesting and unexpected problem you are running in there. Can you open a new bug report issue and include the information it asks for? Optimally, maybe even for a small minimal project, we can just install and try to reproduce the problem - this might depend on all kinds of things in your app, so that would be the fastest way for us to reproduce - which we definitely want to be able to understand and fix this!
> 
> > I also want to know if this way of instantiating a Prisma Client on each function call is the best approach, as in other app components I'm using a global prisma client as from the docs
> 
> Yes, this is unfortunately a limitation of the edge runtimes. Connections can only be used in the request where they were created, if you try to reuse them this might initially even work - but as soon as one worker or environment is called to handle multiple requests at the same time (which can happen in these environments) your worker will crash with an exception.
> 
> (If you use a serverless driver that uses HTTP like for example the one for PlanetScale, there is no downside in starting a new Prisma Client instance with each request. For the others that is one of the reasons why one really has to look if talking to a database in an edge environment really makes sense and gives them the desired performance. [Cloudflare is working on a local connection pooler Hyperdrive to potentially minimize the impact of this, also works with Prisma already.])

thank for your quick reply. I understand now the edge runtime limitations. As far as the error I've shown above , I think that was related to the fact that I was running my dev on localhost and had the `export const runtime = 'edge';` config . I've deployed the app and it works with no errors in vercel prod.

**Comment by ymc9** [comment]
> Hi! Thanks for the support of Vercel Edge Runtime Functions. Here is a problem that I get when I instantiate a prisma client as documented and use it on a API route with 'edge' runtime:
> 
> ```
>  ⚠ ./node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/.prisma/client/wasm-edge-light-loader.js
> The generated code contains 'async/await' because this module is using "topLevelAwait".
> However, your target environment does not appear to support 'async/await'.
> As a result, the code may not run as expected or may cause runtime errors
> ```
> 
> ... and here is the code that throws this error:
> 
> ```js
> export async function GET(req: Request) {
>   // Create a new Prisma client
>   const neon = new Pool({ connectionString: process.env.POSTGRES_MICRO_AI_PRISMA_URL })
>   const adapter = new PrismaNeon(neon)
>   const prisma = new PrismaClient({ adapter })
>   
>  const user = await prisma.user.findUnique({
>     where: {
>       id: userId,
>     },
>   });
> ```
> 
> @janpio I also want to know if this way of instantiating a Prisma Client on each function call is the best approach, as in other app components I'm using a global prisma client as from the docs https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices

I've run into the same "toplevelAwait" error with a very simple Next.js 14 (app router) setup, using Prisma in a RSC page with edge runtime.

```
 ⚠ ./node_modules/.prisma/client/wasm-edge-light-loader.js
The generated code contains 'async/await' because this module is using "topLevelAwait".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors.

Import trace for requested module:
./node_modules/.prisma/client/wasm-edge-light-loader.js
./node_modules/.prisma/client/wasm.js
./node_modules/.prisma/client/default.js
./node_modules/@prisma/client/default.js
```

@janpio Here's a repro project if needed: https://github.com/ymc9/prisma-edge

**Comment by ymc9** [comment]
> Interesting and unexpected problem you are running in there. Can you open a new bug report issue and include the information it asks for? Optimally, maybe even for a small minimal project, we can just install and try to reproduce the problem - this might depend on all kinds of things in your app, so that would be the fastest way for us to reproduce - which we definitely want to be able to understand and fix this!
> 
> > I also want to know if this way of instantiating a Prisma Client on each function call is the best approach, as in other app components I'm using a global prisma client as from the docs
> 
> Yes, this is unfortunately a limitation of the edge runtimes. Connections can only be used in the request where they were created, if you try to reuse them this might initially even work - but as soon as one worker or environment is called to handle multiple requests at the same time (which can happen in these environments) your worker will crash with an exception.
> 
> (If you use a serverless driver that uses HTTP like for example the one for PlanetScale, there is no downside in starting a new Prisma Client instance with each request. For the others that is one of the reasons why one really has to look if talking to a database in an edge environment really makes sense and gives them the desired performance. [Cloudflare is working on a local connection pooler Hyperdrive to potentially minimize the impact of this, also works with Prisma already.])

Today I learned if you use a singleton prisma instance and use it in Vercel edge runtime, you'll randomly get HTTP 405/500 etc, seemingly caused by database timeout.

**Comment by kincaidoneil** [comment]
> Today I learned if you use a singleton prisma instance and use it in Vercel edge runtime, you'll randomly get HTTP 405/500 etc, seemingly caused by database timeout.

Also ran into that issue: attaching the instance to `globalThis` caused bizarre [`INTERNAL_EDGE_FUNCTION_INVOCATION_FAILED`](https://vercel.com/docs/errors/INTERNAL_EDGE_FUNCTION_INVOCATION_FAILED) 500 errors on Vercel edge.

**Comment by janpio** [comment]
@ymc9 Thanks for the reproduction. Do I understand correctly that you are getting a _warning_ with this, and not an error?
<img width="1642" alt="image" src="https://github.com/prisma/prisma/assets/183673/a265a34e-78f6-48b4-9df8-adba255cf8cd">

**Comment by ScreamZ** [comment]
Interested in this

runtime = "edge" seems giving "top level await" error

**Comment by ymc9** [comment]
> @ymc9 Thanks for the reproduction. Do I understand correctly that you are getting a _warning_ with this, and not an error? <img alt="image" width="1642" src="https://private-user-images.githubusercontent.com/183673/323956324-a265a34e-78f6-48b4-9df8-adba255cf8cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NTc0NzQsIm5iZiI6MTcxNDU1NzE3NCwicGF0aCI6Ii8xODM2NzMvMzIzOTU2MzI0LWEyNjVhMzRlLTc4ZjYtNDhiNC05ZGY4LWFkYmEyNTVjZjhjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMVQwOTUyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2I2ODRkMTZhNDlhOWFmOWNjYzU3NWQ4YmMzYzkxN2RiNWIzYmU4OTBlYWQ0MWVkZGYyOWE1MWI5YmVhZjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KRDnhsaCNNb2xS4MnwKeQs0KwEuCnTsM_0ZlagMamjo">

Sorry for the late reply @janpio . You're right they seem to be warnings and don't really cause runtime problems.

**Comment by the-me-0** [comment]
Hello there !
I'm having trouble trying to run prisma in the vercel edge environment... but it might be because I missed something. I'm coming back to this huge project of mine and my coding skills are a bit out of shape ;).
I'm trying to run a simple "findMany" to test if running prisma for there is possible, but I get a bizarre error. My real goal here is to have my NextJS app generate a new API key once launched. Thing is, I only found one way to write code that will run on startup with nextjs, which is the ["instrumentation hook"](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation). My code, in the instrumentation file, looks like this :

```ts
import {PrismaClient} from '@prisma/client';

export function register() {
  const db = new PrismaClient();

  db.sponsorship.findMany().then((sponsorships) => {
    console.log(sponsorships);
  });
}
```


Getting this error :
```
Module not found: Can't resolve 'path'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.prisma/client/default.js
./node_modules/@prisma/client/default.js
./lib/db.ts
./instrumentation.ts
PrismaClientInitializationError: 
Invalid `prisma.sponsorship.findMany()` invocation:


error: Error validating: This line is invalid. It does not start with any known Prisma schema keyword.
  -->  schema.prisma:1
```

If you believe I'm doing this whole thing for nothing as there's a better way to achieve my end goal, please tell me. Thanks for your time, prisma team !

**Comment by reeddunkle** [comment]
@janpio Can you help me sort through a few things when you have time?

I rarely, (seemingly) randomly get this error on the tRPC handler, using abitrary procedures:

> Error in connector: Error querying the database: ERROR: current transaction is aborted, commands ignored until end of transaction block

It feels like I've narrowed it down to the Prisma client losing the connection.

- Prisma (v6.2.1) connecting via Supavisor transaction connection pooler URL.
- Nextjs [tRPC API route handler](https://trpc.io/docs/server/adapters/nextjs#route-handlers)
- `export const runtime = "nodejs"`

[Problem statement](https://github.com/prisma/prisma/issues/20566#issue-1837640371) (from OP):

> Prisma Client currently does not work in the Vercel Edge Runtime, which is used to run Edge Functions by Vercel. Vercel's Edge Runtime is automatically used to run the API endpoint of your Next.js app when you define export const runtime = "nodejs" for your routes.

Is Vercel's Edge Runtime still used to run my Node.js serverless function?

[Choosing a Runtime docs](https://vercel.com/docs/functions/runtimes#choosing-a-runtime) suggest something similar.

> Runtimes transform your source code into Functions, which are served by our Edge Network.

One of the workaround from the original statement:

> Do not use the edge runtime. export const runtime = "nodejs"; will configure your project to deploy its API functions as a serverless function, which Prisma supports already as it has the necessary functionality.

I explicitly added `export const runtime = "nodejs"`, and the function is displayed as "Serverless" in the logs.

---

#### Error log

When the error happens to occur, I see it in the initial Prisma query in the tRPC `createContext` of the [route handler](https://trpc.io/docs/server/adapters/nextjs#route-handlers). I'm assuming I'm seeing the error here because it's the first query. Maybe the shared client singleton gets lost here sometimes?

#### Healthy connection otherwise

- `connection_limit=1`
- `pool_timeout=30`
- Removed `Promise.all`
- Extra Vercel function time

---

[This comment](https://github.com/prisma/prisma/issues/20566#issuecomment-2021594203) could describe the issue:

> Yes, this is unfortunately a limitation of the edge runtimes. Connections can only be used in the request where they were created, if you try to reuse them this might initially even work - but as soon as one worker or environment is called to handle multiple requests at the same time (which can happen in these environments) your worker will crash with an exception.

- Tried removing the singleton pattern, and creating a new client inside of each handler (outside of the `createContext`).
- Still reproduces error.

[Another comment](https://github.com/prisma/prisma/discussions/24500#discussioncomment-9750002) says:

> For Supabase there unfortunately is no serverless driver available, so we can not offer it. You can only talk to that database directly. (The Supabase JS Client SDK is not powerful to support the APIs of Prisma)

The `pooler.supabase.com:6543/postgres?pgbouncer=true` string should accommodate this limitation?

**Comment by djshubs** [comment]
> > Today I learned if you use a singleton prisma instance and use it in Vercel edge runtime, you'll randomly get HTTP 405/500 etc, seemingly caused by database timeout.
> 
> 
> 
> Also ran into that issue: attaching the instance to `globalThis` caused bizarre [`INTERNAL_EDGE_FUNCTION_INVOCATION_FAILED`](https://vercel.com/docs/errors/INTERNAL_EDGE_FUNCTION_INVOCATION_FAILED) 500 errors on Vercel edge.

Did you solve this by just instantiating a new client in the edge rather than using a singleton? 

I'm seeing this as well.

**Comment by kincaidoneil** [comment]
@djshubs Yes! Create a new client per request.

If you're using Next.js/React, you can also use React `cache` to memoize the client across a single request for use in RSCs, etc:

```ts
import { after } from 'next/server'
import { cache } from 'react'

import { createPrisma } from '@/prisma/client'

import logger from './logger'

export const createPrisma = () => {
  // Instantiate a new Prisma Client ...
}

export const getPrisma = cache(() => {
  const prisma = createPrisma()
  after(async () => {
    await prisma.$disconnect()
    logger.debug('Disconnected from Prisma')
  })

  return prisma
})
```

**Comment by djshubs** [comment]
> @djshubs Yes! Create a new client per request.
> 
> If you're using Next.js/React, you can also use React `cache` to memoize the client across a single request for use in RSCs, etc:
> 
> ```ts
> import { after } from 'next/server'
> import { cache } from 'react'
> 
> import { createPrisma } from '@/prisma/client'
> 
> import logger from './logger'
> 
> export const createPrisma = () => {
>   // Instantiate a new Prisma Client ...
> }
> 
> export const getPrisma = cache(() => {
>   const prisma = createPrisma()
>   after(async () => {
>     await prisma.$disconnect()
>     logger.debug('Disconnected from Prisma')
>   })
> 
>   return prisma
> })
> ```

You are the effin' best. 

I'm trying to use this with Supabase and getting it to work has been PITA. Any tips or suggestions will be appreciated.
