### ISSUE TITLE
MongoDB: The argument to $size must be an array, but was of type: null

### ISSUE THREAD

**Issue by nils-jansen** [prisma/prisma#20574]
### Bug description

I am trying to perform the following query:
```ts
this.prismaService.firefightersParticipatedInSessions.count({
  where: {
    AND: [
      {
        firefighter: {
          firestations: { some: { firestationId } },
        },
      },
      {
        firefighter: {
          sessions: {
            some: {
              session: { date: { gte: startOfThisYear } },
            },
          },
        },
      },
    ],
  },
});

```

Which results in this error:
```
prisma:error 
Invalid `this.prismaService.firefightersParticipatedInSessions.count()` invocation in
/[...]/file.ts:73:70

  70 numberOfCompletedSessionsThisYear(firestationId: string) {
  71     const startOfThisYear = startOfYear(new Date());
  72 
→ 73     return this.prismaService.firefightersParticipatedInSessions.count(
Raw query failed. Code: `unknown`. Message: `Command failed (Location17124): PlanExecutor error during aggregation :: caused by :: The argument to $size must be an array, but was of type: null)`
```

This is the failing query generated by prisma:
```ts
prisma:query db.FirefightersParticipatedInSessions.aggregate([ { $lookup: { from: "Firefighter", let: { left_0: "$firefighterId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "FirefightersMembersOfFirestations", let: { left_0: "$_id", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$firefighterId", "$$left_0", ], }, ], }, }, }, ], as: "FirefighterToFirefightersMembersOfFirestations", }, }, ], as: "FirefighterToFirefightersParticipatedInSessions", }, }, { $lookup: { from: "Firefighter", let: { left_0: "$firefighterId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "FirefightersParticipatedInSessions", let: { left_0: "$_id", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$firefighterId", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "Session", let: { left_0: "$sessionId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, ], as: "FirefightersParticipatedInSessionsToSession", }, }, ], as: "FirefighterToFirefightersParticipatedInSessions", }, }, ], as: "FirefighterToFirefightersParticipatedInSessions", }, }, { $match: { $expr: { $and: [ { $and: [ { $eq: [ { $size: { $filter: { input: "$FirefighterToFirefightersParticipatedInSessions", as: "elem", cond: { $gt: [ { $size: { $filter: { input: "$$elem.FirefighterToFirefightersMembersOfFirestations", as: "elem", cond: { $and: [ { $eq: [ "$$elem.firestationId", { $literal: ObjectId("64243c5d8c89ed1f1ae052b0"), }, ], }, { $ne: [ "$$elem.firestationId", "$$REMOVE", ], }, ], }, }, }, }, 0, ], }, }, }, }, { $size: "$FirefighterToFirefightersParticipatedInSessions", }, ], }, { $eq: [ { $size: "$FirefighterToFirefightersParticipatedInSessions", }, 1, ], }, ], }, { $and: [ { $eq: [ { $size: { $filter: { input: "$FirefighterToFirefightersParticipatedInSessions", as: "elem", cond: { $gt: [ { $size: { $filter: { input: "$$elem.FirefighterToFirefightersParticipatedInSessions", as: "elem", cond: { $and: [ { $eq: [ { $size: { $filter: { input: "$$elem.FirefightersParticipatedInSessionsToSession", as: "elem", cond: { $and: [ { $gte: [ "$$elem.date", { $literal: DateTime("2022-12-31 23:00:00.0 +00:00:00"), }, ], }, { $ne: [ "$$elem.date", "$$REMOVE", ], }, ], }, }, }, }, { $size: "$$elem.FirefightersParticipatedInSessionsToSession", }, ], }, { $eq: [ { $size: "$$elem.FirefightersParticipatedInSessionsToSession", }, 1, ], }, ], }, }, }, }, 0, ], }, }, }, }, { $size: "$FirefighterToFirefightersParticipatedInSessions", }, ], }, { $eq: [ { $size: "$FirefighterToFirefightersParticipatedInSessions", }, 1, ], }, ], }, ], }, }, }, { $unwind: { path: "$FirefighterToFirefightersParticipatedInSessions", preserveNullAndEmptyArrays: true, }, }, { $unwind: { path: "$FirefighterToFirefightersParticipatedInSessions", preserveNullAndEmptyArrays: true, }, }, { $group: { _id: null, count_all: { $sum: 1, }, }, }, ])
```

### How to reproduce

I'm unsure what exactly to provide here. I hope the problem becomes apparent when looking at the raw query. 

### Expected behavior

In the past, this query has worked and yielded the correct result. I would expect this continue working.

### Prisma information

```prisma
model Firestation {
  id String @id @default(auto()) @map("_id") @db.ObjectId
  name String
  firefighters FirefightersMembersOfFirestations[]
}

model Firefighter {
  id String @id @default(auto()) @map("_id") @db.ObjectId
  firestations FirefightersMembersOfFirestations[]
  sessions FirefightersParticipatedInSessions[]
}

model FirefightersMembersOfFirestations {
  id String @id @default(auto()) @map("_id") @db.ObjectId

  firefighterId String      @db.ObjectId
  firefighter   Firefighter @relation(fields: [firefighterId], references: [id])

  firestationId String      @db.ObjectId
  firestation   Firestation @relation(fields: [firestationId], references: [id])


  @@unique([firefighterId, firestationId])
  @@index([firefighterId])
  @@index([firestationId])
}

model Session {
  id String @id @default(auto()) @map("_id") @db.ObjectId
  firefighters FirefightersParticipatedInSessions[]
}

model FirefightersParticipatedInSessions {
  id String @id @default(auto()) @map("_id") @db.ObjectId

  firefighterId String      @db.ObjectId
  firefighter   Firefighter @relation(fields: [firefighterId], references: [id], onDelete: Cascade)

  sessionId String  @db.ObjectId
  session   Session @relation(fields: [sessionId], references: [id], onDelete: Cascade)

  @@unique([firefighterId, sessionId])
  @@index([firefighterId])
  @@index([sessionId])
}
```

```ts
this.prismaService.firefightersParticipatedInSessions.count({
  where: {
    AND: [
      {
        firefighter: {
          firestations: { some: { firestationId } },
        },
      },
      {
        firefighter: {
          sessions: {
            some: {
              session: { date: { gte: startOfThisYear } },
            },
          },
        },
      },
    ],
  },
});
```

### Environment & setup

- OS: macOS
- Database: MongoDB
- Node.js version: v18.16.1

### Prisma Version

```
prisma                  : 4.16.2
@prisma/client          : 5.1.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
```

**Comment by millsp** [comment]
Hey @nils-janse, thanks for the report. Unfortunately, I was not able to reproduce this with the information your provided. I noticed that there's a missing `date` field in the `Session` model, so my query currently fails with:

```
 4 async function main() {
  5     const prisma = new PrismaClient()
  6 
→ 7     await prisma.firefightersParticipatedInSessions.count({
....
Unknown argument `date`. Available options are listed in green.
```

I have also tried to but a `date` field in the schema, but then the query is successful. Could you please provide us with some more info so that we can take another attempt at reproducing this? Thanks :)

**Comment by janpio** [comment]
Did you see Pierre's message @nils-jansen?

**Comment by Aicirou** [comment]
### Hey there,
### I was getting the same kind of error as below...

> error: PrismaClientKnownRequestError: 
Invalid `prisma.payOutData.findMany()` invocation:
Raw query failed. Code: `unknown`. Message: `Kind: Command failed: Error code 17124 (Location17124): PlanExecutor error during aggregation :: caused by :: The argument to $size must be an array, but was of type: null, labels: {}`

```
//throw Error 

where = {
  AND: [
         {
           AND: payOutFilters,
         },
         {
           OR: payOutSearch_Query,
         },
       ],
 };
```

Inside the AND array, I have two objects as shown below:

- The first object contains an OR key, which means it combines multiple conditions with a logical OR. This allows you to search for data that matches any of the conditions specified in payOutSearch_Query.

- The second object contains an AND key, which combines multiple conditions with a logical AND. This allows you to apply multiple filters using payOutFilters.


Inside where object, if i put `{ AND: payOutFilters,},` before ` {OR: payOutSearch_Query,},` it throws this above Error.

### What works for me is this,


```
//correct 

where = {
  AND: [
         {
           OR: payOutSearch_Query,
         },
         {
           AND: payOutFilters,
         },
       ],
 };
```
It seems the same thing to me but apparently, it's working. 
hey @janpio, could you please care to explain me what's the difference between these two approaches?

**Comment by janpio** [comment]
What values to `payOutFilters` and `payOutSearch_Query` have? I am not sure what your query is actually doing.

Can you [enable query logging](https://www.prisma.io/docs/orm/prisma-client/observability-and-logging/logging#event-based-logging) in your Prisma Client instance and share the commands that are generated and executed for both of these cases? That would probably be the best way to debug this.

**Comment by Aicirou** [comment]
hey @janpio, thanks for the reply.

### please find the detailed logs for the same below

This is the where object, includes payOutFilters and payOutSearch_Query
```
//where object 

let where = {
    AND: [
      {
        AND: payOutFilters,
      },
      {
        OR: payOutSearch_Query,
      },
    ],
  },
  
let payOutFilters = [
          {
            deliveryData: {
              AND: [{ month: { equals: 10 } }, { year: { equals: "2023" } }],
            },
          },
          { cycle: { in: ["FIRST", "SECOND"] } },
          {
            deliveryData: {
              rider: { hub: { state: { state: { in: ["GUJARAT"] } } } },
            },
          },
        ];
        
let payOutSearch_Query = [
          {
            deliveryData: {
              fhrid: { contains: "100000951858", mode: "insensitive" },
            },
          },
        ]
          
```
i'm trying to perform this query,

`const payOutData = await prisma.payOutData.findMany({
            where: where,
            skip,
            take: limit,
            orderBy: {
              createdAt: "desc",
            },
            include: {
              payOut: true,
              payOutType: true,
              deliveryData: {
                include: {
                  rider: {
                    include: {
                      hub: {
                        select: {
                          state: {
                            select: {
                              state: true,
                              RMId: true,
                            },
                          },
                          city: {
                            select: {
                              city: true,
                            },
                          },
                          deliveryHub: true,
                          OEId: true,
                        },
                      },
                      fhrids: {
                        orderBy: {
                          createdAt: "desc",
                        },
                        select: {
                          fhrid: true,
                        },
                      },
                    },
                  },
                  days: true,
                },
              },
            },
          });`
          
failing error generated by prisma:

```
prisma:error 
Invalid `prisma.payOutData.findMany()` invocation:


Raw query failed. Code: `unknown`. Message: `Kind: Command failed: Error code 17124 (Location17124): PlanExecutor error during aggregation :: caused by :: The argument to $size must be an array, but was of type: null, labels: {}`
error: PrismaClientKnownRequestError: 
Invalid `prisma.payOutData.findMany()` invocation:


Raw query failed. Code: `unknown`. Message: `Kind: Command failed: Error code 17124 (Location17124): PlanExecutor error during aggregation :: caused by :: The argument to $size must be an array, but was of type: null, labels: {}`
    at ai.handleRequestError (/var/www/sf-dev/sendfast-be/node_modules/@prisma/client/runtime/library.js:126:6775)
    at ai.handleAndLogRequestError (/var/www/sf-dev/sendfast-be/node_modules/@prisma/client/runtime/library.js:126:6109)
    at ai.request (/var/www/sf-dev/sendfast-be/node_modules/@prisma/client/runtime/library.js:126:5817)
    at async l (/var/www/sf-dev/sendfast-be/node_modules/@prisma/client/runtime/library.js:131:9709)
    at async Object.getPayOutData (file:///var/www/sf-dev/sendfast-be/src/graphql/resolvers/payoutResolvers.js:389:30) {
  code: 'P2010',
  clientVersion: '5.9.1',
  meta: {
    modelName: 'PayOutData',
    code: 'unknown',
    message: 'Kind: Command failed: Error code 17124 (Location17124): PlanExecutor error during aggregation :: caused by :: The argument to $size must be an array, but was of type: null, labels: {}'
  }
}
``` 
failing query generated by prisma:

```
Query: db.PayOutData.aggregate([ { $lookup: { from: "DeliveryData", let: { left_0: "$deliveryDataId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, ], as: "payOutData", }, }, { $lookup: { from: "DeliveryData", let: { left_0: "$deliveryDataId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "Rider", let: { left_0: "$riderId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "Hub", let: { left_0: "$hubId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "State", let: { left_0: "$StateId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, ], as: "hub_state", }, }, ], as: "hub_rider", }, }, ], as: "deliveryData", }, }, ], as: "payOutData", }, }, { $lookup: { from: "DeliveryData", let: { left_0: "$deliveryDataId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, ], as: "payOutData", }, }, { $match: { $expr: { $and: [ { $and: [ { $eq: [ { $size: { $filter: { input: "$payOutData", as: "elem", cond: { $and: [ { $and: [ { $eq: [ "$$elem.month", { $literal: 10, }, ], }, { $ne: [ "$$elem.month", "$$REMOVE", ], }, ], }, { $and: [ { $eq: [ "$$elem.year", { $literal: "2023", }, ], }, { $ne: [ "$$elem.year", "$$REMOVE", ], }, ], }, ], }, }, }, }, { $size: "$payOutData", }, ], }, { $eq: [ { $size: "$payOutData", }, 1, ], }, ], }, { $and: [ { $in: [ "$cycle", { $literal: [ "FIRST", "SECOND", ], }, ], }, { $ne: [ "$cycle", "$$REMOVE", ], }, ], }, { $and: [ { $eq: [ { $size: { $filter: { input: "$payOutData", as: "elem", cond: { $and: [ { $eq: [ { $size: { $filter: { input: "$$elem.deliveryData", as: "elem", cond: { $and: [ { $eq: [ { $size: { $filter: { input: "$$elem.hub_rider", as: "elem", cond: { $and: [ { $eq: [ { $size: { $filter: { input: "$$elem.hub_state", as: "elem", cond: { $and: [ { $in: [ "$$elem.state", { $literal: [ "GUJARAT", ], }, ], }, { $ne: [ "$$elem.state", "$$REMOVE", ], }, ], }, }, }, }, { $size: "$$elem.hub_state", }, ], }, { $eq: [ { $size: "$$elem.hub_state", }, 1, ], }, ], }, }, }, }, { $size: "$$elem.hub_rider", }, ], }, { $eq: [ { $size: "$$elem.hub_rider", }, 1, ], }, ], }, }, }, }, { $size: "$$elem.deliveryData", }, ], }, { $eq: [ { $size: "$$elem.deliveryData", }, 1, ], }, ], }, }, }, }, { $size: "$payOutData", }, ], }, { $eq: [ { $size: "$payOutData", }, 1, ], }, ], }, { $and: [ { $eq: [ { $size: { $filter: { input: "$payOutData", as: "elem", cond: { $and: [ { $regexMatch: { input: "$$elem.fhrid", regex: ".*100000951858.*", options: "i", }, }, { $ne: [ "$$elem.fhrid", "$$REMOVE", ], }, ], }, }, }, }, { $size: "$payOutData", }, ], }, { $eq: [ { $size: "$payOutData", }, 1, ], }, ], }, ], }, }, }, { $unwind: { path: "$payOutData", preserveNullAndEmptyArrays: true, }, }, { $unwind: { path: "$payOutData", preserveNullAndEmptyArrays: true, }, }, { $unwind: { path: "$payOutData", preserveNullAndEmptyArrays: true, }, }, { $sort: { createdAt: -1, }, }, { $skip: 0, }, { $limit: 1000, }, { $project: { _id: 1, cycle: 1, sfid: 1, payCode: 1, conversionBracket: 1, rate: 1, amount: 1, TDS: 1, deduction: 1, insurance: 1, advance: 1, sfEscalation: 1, incentive: 1, totalEarnings: 1, totalDeduction: 1, netPayable: 1, status: 1, partialHoldAmount: 1, deliveryDataId: 1, createdAt: 1, updatedAt: 1, }, }, ])
``` 

Inside where object, im trying filter by month, year, cycle and state, along with search by fhrid.
if I remove any one filter condition from either the state filter: `{
            deliveryData: {
              fhrid: { contains: "100000951858", mode: "insensitive" },
            },
          },` or the fhrid search: `{
            deliveryData: {
              rider: { hub: { state: { state: { in: ["GUJARAT"] } } } },
            },
          },`, then above query will work as expected.
          I think these both conditions were conflicting with each other or something...
          
So, I tried to Interchange the logical OR n logical AND filter conditions instead of removing any condition, like this
```
//correct 

where = {
  AND: [
         {
           OR: payOutSearch_Query, //this is the change         
           },
         {
           AND: payOutFilters,
         },
       ],
 };
```
successful query generated by prisma:
```
Query: db.PayOutData.aggregate([ { $lookup: { from: "DeliveryData", let: { left_0: "$deliveryDataId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, ], as: "payOutData", }, }, { $lookup: { from: "DeliveryData", let: { left_0: "$deliveryDataId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, ], as: "payOutData", }, }, { $lookup: { from: "DeliveryData", let: { left_0: "$deliveryDataId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "Rider", let: { left_0: "$riderId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "Hub", let: { left_0: "$hubId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "State", let: { left_0: "$StateId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, ], as: "hub_state", }, }, ], as: "hub_rider", }, }, ], as: "deliveryData", }, }, ], as: "payOutData", }, }, { $match: { $expr: { $and: [ { $and: [ { $eq: [ { $size: { $filter: { input: "$payOutData", as: "elem", cond: { $and: [ { $regexMatch: { input: "$$elem.fhrid", regex: ".*100000951858.*", options: "i", }, }, { $ne: [ "$$elem.fhrid", "$$REMOVE", ], }, ], }, }, }, }, { $size: "$payOutData", }, ], }, { $eq: [ { $size: "$payOutData", }, 1, ], }, ], }, { $and: [ { $eq: [ { $size: { $filter: { input: "$payOutData", as: "elem", cond: { $and: [ { $and: [ { $eq: [ "$$elem.month", { $literal: 10, }, ], }, { $ne: [ "$$elem.month", "$$REMOVE", ], }, ], }, { $and: [ { $eq: [ "$$elem.year", { $literal: "2023", }, ], }, { $ne: [ "$$elem.year", "$$REMOVE", ], }, ], }, ], }, }, }, }, { $size: "$payOutData", }, ], }, { $eq: [ { $size: "$payOutData", }, 1, ], }, ], }, { $and: [ { $in: [ "$cycle", { $literal: [ "FIRST", "SECOND", ], }, ], }, { $ne: [ "$cycle", "$$REMOVE", ], }, ], }, { $and: [ { $eq: [ { $size: { $filter: { input: "$payOutData", as: "elem", cond: { $and: [ { $eq: [ { $size: { $filter: { input: "$$elem.deliveryData", as: "elem", cond: { $and: [ { $eq: [ { $size: { $filter: { input: "$$elem.hub_rider", as: "elem", cond: { $and: [ { $eq: [ { $size: { $filter: { input: "$$elem.hub_state", as: "elem", cond: { $and: [ { $in: [ "$$elem.state", { $literal: [ "GUJARAT", ], }, ], }, { $ne: [ "$$elem.state", "$$REMOVE", ], }, ], }, }, }, }, { $size: "$$elem.hub_state", }, ], }, { $eq: [ { $size: "$$elem.hub_state", }, 1, ], }, ], }, }, }, }, { $size: "$$elem.hub_rider", }, ], }, { $eq: [ { $size: "$$elem.hub_rider", }, 1, ], }, ], }, }, }, }, { $size: "$$elem.deliveryData", }, ], }, { $eq: [ { $size: "$$elem.deliveryData", }, 1, ], }, ], }, }, }, }, { $size: "$payOutData", }, ], }, { $eq: [ { $size: "$payOutData", }, 1, ], }, ], }, ], }, }, }, { $unwind: { path: "$payOutData", preserveNullAndEmptyArrays: true, }, }, { $unwind: { path: "$payOutData", preserveNullAndEmptyArrays: true, }, }, { $unwind: { path: "$payOutData", preserveNullAndEmptyArrays: true, }, }, { $sort: { createdAt: -1, }, }, { $skip: 0, }, { $limit: 1000, }, { $project: { _id: 1, cycle: 1, sfid: 1, payCode: 1, conversionBracket: 1, rate: 1, amount: 1, TDS: 1, deduction: 1, insurance: 1, advance: 1, sfEscalation: 1, incentive: 1, totalEarnings: 1, totalDeduction: 1, netPayable: 1, status: 1, partialHoldAmount: 1, deliveryDataId: 1, createdAt: 1, updatedAt: 1, }, }, ])
Query: db.PayOut.aggregate([ { $match: { $expr: { $and: [ { $in: [ "$payOutDataId", [ { $literal: ObjectId("65d31dfcb97df87448a15d4a"), }, ], ], }, { $ne: [ "$payOutDataId", "$$REMOVE", ], }, ], }, }, }, { $project: { _id: 1, amount: 1, currency: 1, description: 1, source: 1, status: 1, createdAt: 1, updatedAt: 1, payOutDataId: 1, riderId: 1, }, }, ])
Query: db.PayOutType.aggregate([ { $match: { $expr: { $and: [ { $in: [ "$payOutDataId", [ { $literal: ObjectId("65d31dfcb97df87448a15d4a"), }, ], ], }, { $ne: [ "$payOutDataId", "$$REMOVE", ], }, ], }, }, }, { $project: { _id: 1, type: 1, riderId: 1, payOutDataId: 1, createdAt: 1, }, }, ])
Query: db.DeliveryData.aggregate([ { $match: { $expr: { $and: [ { $in: [ "$_id", [ { $literal: ObjectId("65cf8ce8b901c027dc84b7a2"), }, ], ], }, { $ne: [ "$_id", "$$REMOVE", ], }, ], }, }, }, { $project: { _id: 1, riderId: 1, month: 1, year: 1, cycle: 1, agentName: 1, fhrid: 1, totalOfd: 1, totalDel: 1, manDays: 1, conversion: 1, avgOfd: 1, avgDel: 1, createdAt: 1, updatedAt: 1, }, }, ])
Query: db.Rider.aggregate([ { $match: { $expr: { $and: [ { $in: [ "$_id", [ { $literal: ObjectId("65966635070909bcd762b370"), }, ], ], }, { $ne: [ "$_id", "$$REMOVE", ], }, ], }, }, }, { $project: { _id: 1, date: 1, name: 1, mobileNumber: 1, altMobileNumber: 1, pan: 1, aadhaar: 1, dob: 1, fathersName: 1, permanentAddress: 1, presentAddress: 1, landmark: 1, pincode: 1, dlNo: 1, hubId: 1, cityId: 1, stateId: 1, zone: 1, gender: 1, model: 1, email: 1, bankAccountNo: 1, ifscCode: 1, employeeID: 1, role: 1, createdAt: 1, updatedAt: 1, userId: 1, }, }, ])
Query: db.Hub.aggregate([ { $match: { $expr: { $and: [ { $in: [ "$_id", [ { $literal: ObjectId("65965d634436e8476a32d860"), }, ], ], }, { $ne: [ "$_id", "$$REMOVE", ], }, ], }, }, }, { $project: { _id: 1, StateId: 1, CityId: 1, deliveryHub: 1, OEId: 1, }, }, ])
Query: db.State.aggregate([ { $match: { $expr: { $and: [ { $in: [ "$_id", [ { $literal: ObjectId("65965d5e4436e8476a32d528"), }, ], ], }, { $ne: [ "$_id", "$$REMOVE", ], }, ], }, }, }, { $project: { _id: 1, state: 1, RMId: 1, }, }, ])
Query: db.City.aggregate([ { $match: { $expr: { $and: [ { $in: [ "$_id", [ { $literal: ObjectId("65965d624436e8476a32d75a"), }, ], ], }, { $ne: [ "$_id", "$$REMOVE", ], }, ], }, }, }, { $project: { _id: 1, city: 1, }, }, ])
Query: db.Fhrid.aggregate([ { $match: { $expr: { $and: [ { $in: [ "$riderId", [ { $literal: ObjectId("65966635070909bcd762b370"), }, ], ], }, { $ne: [ "$riderId", "$$REMOVE", ], }, ], }, }, }, { $sort: { createdAt: -1, }, }, { $project: { _id: 1, fhrid: 1, riderId: 1, }, }, ])
Query: db.DeliveryDay.aggregate([ { $match: { $expr: { $and: [ { $in: [ "$deliveryDataId", [ { $literal: ObjectId("65cf8ce8b901c027dc84b7a2"), }, ], ], }, { $ne: [ "$deliveryDataId", "$$REMOVE", ], }, ], }, }, }, { $project: { _id: 1, date: 1, ofd: 1, del: 1, deliveryDataId: 1, }, }, ])
Query: db.PayOutData.aggregate([ { $lookup: { from: "DeliveryData", let: { left_0: "$deliveryDataId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, ], as: "payOutData", }, }, { $lookup: { from: "DeliveryData", let: { left_0: "$deliveryDataId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, ], as: "payOutData", }, }, { $lookup: { from: "DeliveryData", let: { left_0: "$deliveryDataId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "Rider", let: { left_0: "$riderId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "Hub", let: { left_0: "$hubId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, { $lookup: { from: "State", let: { left_0: "$StateId", }, pipeline: [ { $match: { $expr: { $and: [ { $eq: [ "$_id", "$$left_0", ], }, ], }, }, }, ], as: "hub_state", }, }, ], as: "hub_rider", }, }, ], as: "deliveryData", }, }, ], as: "payOutData", }, }, { $match: { $expr: { $and: [ { $and: [ { $eq: [ { $size: { $filter: { input: "$payOutData", as: "elem", cond: { $and: [ { $regexMatch: { input: "$$elem.fhrid", regex: ".*100000951858.*", options: "i", }, }, { $ne: [ "$$elem.fhrid", "$$REMOVE", ], }, ], }, }, }, }, { $size: "$payOutData", }, ], }, { $eq: [ { $size: "$payOutData", }, 1, ], }, ], }, { $and: [ { $eq: [ { $size: { $filter: { input: "$payOutData", as: "elem", cond: { $and: [ { $and: [ { $eq: [ "$$elem.month", { $literal: 10, }, ], }, { $ne: [ "$$elem.month", "$$REMOVE", ], }, ], }, { $and: [ { $eq: [ "$$elem.year", { $literal: "2023", }, ], }, { $ne: [ "$$elem.year", "$$REMOVE", ], }, ], }, ], }, }, }, }, { $size: "$payOutData", }, ], }, { $eq: [ { $size: "$payOutData", }, 1, ], }, ], }, { $and: [ { $in: [ "$cycle", { $literal: [ "FIRST", "SECOND", ], }, ], }, { $ne: [ "$cycle", "$$REMOVE", ], }, ], }, { $and: [ { $eq: [ { $size: { $filter: { input: "$payOutData", as: "elem", cond: { $and: [ { $eq: [ { $size: { $filter: { input: "$$elem.deliveryData", as: "elem", cond: { $and: [ { $eq: [ { $size: { $filter: { input: "$$elem.hub_rider", as: "elem", cond: { $and: [ { $eq: [ { $size: { $filter: { input: "$$elem.hub_state", as: "elem", cond: { $and: [ { $in: [ "$$elem.state", { $literal: [ "GUJARAT", ], }, ], }, { $ne: [ "$$elem.state", "$$REMOVE", ], }, ], }, }, }, }, { $size: "$$elem.hub_state", }, ], }, { $eq: [ { $size: "$$elem.hub_state", }, 1, ], }, ], }, }, }, }, { $size: "$$elem.hub_rider", }, ], }, { $eq: [ { $size: "$$elem.hub_rider", }, 1, ], }, ], }, }, }, }, { $size: "$$elem.deliveryData", }, ], }, { $eq: [ { $size: "$$elem.deliveryData", }, 1, ], }, ], }, }, }, }, { $size: "$payOutData", }, ], }, { $eq: [ { $size: "$payOutData", }, 1, ], }, ], }, ], }, }, }, { $unwind: { path: "$payOutData", preserveNullAndEmptyArrays: true, }, }, { $unwind: { path: "$payOutData", preserveNullAndEmptyArrays: true, }, }, { $unwind: { path: "$payOutData", preserveNullAndEmptyArrays: true, }, }, { $group: { _id: null, count_all: { $sum: 1, }, }, }, ])
``` 

### Prisma Version
```
prisma                  : 5.10.1
@prisma/client          : 5.10.1
Computed binaryTarget   : linux-arm64-openssl-3.0.x
Operating System        : linux
Architecture            : arm64
Node.js                 : v18.18.0
Query Engine (Node-API) : libquery-engine 5a9203d0590c951969e85a7d07215503f4672eb9 (at ../../../../usr/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-linux-arm64-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 5a9203d0590c951969e85a7d07215503f4672eb9 (at ../../../../usr/lib/node_modules/prisma/node_modules/@prisma/engines/schema-engine-linux-arm64-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.10.0-34.5a9203d0590c951969e85a7d07215503f4672eb9
Default Engines Hash    : 5a9203d0590c951969e85a7d07215503f4672eb9
Studio                  : 0.498.0
``` 
please let me know if you need anything else...

**Comment by Nik-Novak** [comment]
Also having this issue:
```
export async function getLookupHistory(uuid:string):Promise<LookupHistory[]|undefined>{
  const session = await auth();
  if(!session) return undefined;
  let settings = await getRemoteSettings(uuid);
  let query:Prisma.LookupWhereInput = {
    OR:[
      {
        scrape:{
          device:{
            user_id: session.user.id
          }
        }
      }
    ]
  };
  if(settings.selected_project_id){
    query.OR?.push(
      {
        scrape:{
          project_id: settings.selected_project_id
        }
      }
    );
  }
  let lookups = await database.lookup.findMany({
    where: query,
    orderBy:{
      created_at:'desc'
    },
    include:LookupHistoryInclude
  });
  return lookups;
}```

**Comment by Nik-Novak** [comment]
![image](https://github.com/user-attachments/assets/d65a1a9b-ad7f-48d6-b05d-d3cd7a5c3578)

**Comment by Nik-Novak** [comment]
@janpio is there any way we can revive this thread?

**Comment by vinterdo** [comment]
I just got the same error, it seems that filtering by relation of relation is broken when its nested inside "AND" clause, but somehow, reordering conditions inside "AND" fixes it
