### ISSUE TITLE
DateTimes used in composite ids with MySQL 8 cause errors on creation

### ISSUE THREAD

**Issue by Ustice** [prisma/prisma#20632]
### Bug description

We are in the process of upgrading a legacy system from MySQL 5.7 to MySQL 8. We have a table that has a datetime/timestamp field as the first of a composite primary key. In MySQL 5.7, that doesn't cause an issue, but for MySQL 8, we are getting the following error when trying to create a record in that table. It seems to be related to the miliseconds of the datetime field.

```
    PrismaClientUnknownRequestError: 
    Invalid `prisma.paypalTransaction.create()` invocation:


    Query createOnePaypalTransaction is required to return data, but found no record(s).
```

If we use a string version of the date to the `create` method of the Prisma client for that model, it all works as expected.

Causes error
```ts
await prisma.paypalTransaction.create({
  data: {
    bidxid: 'test-user',
    profileid: 'test-profile',
    transaction: '{"Comment1": "Account bidxid: Internet Bidding (1), Basic Service"}',
    transid: '1234567890',
    transtime: new Date(),
  },
})
```

No error
```ts
await prisma.paypalTransaction.create({
  data: {
    bidxid: 'test-user',
    profileid: 'test-profile',
    transaction: '{"Comment1": "Account bidxid: Internet Bidding (1), Basic Service"}',
    transid: '1234567890',
    transtime: new Date().toISOString().slice(0, -5) + 'Z', // Prisma and MySQL 8.0 trip over the
  },
})
```

We tried both `@db.DateTime(0)` and `@db.Timestamp(0)`

### How to reproduce

Given the following model
```prisma
generator client {
  provider        = "prisma-client-js"
  output          = "../../node_modules/@prisma/bidx"
}

datasource db {
  provider = "mysql"
  url      = "REDACTED"
}

model PaypalTransaction {
  transtime     DateTime @db.DateTime(0)
  transid       String   @db.VarChar(45)
  bidxid        String   @db.VarChar(45)
  profileid     String   @db.VarChar(45)
  transaction   String?  @db.Text
  paymentnumber Int?
  updated       DateTime @default(now()) @db.Timestamp(0)

  @@id([transtime, transid, bidxid, profileid])
}
```

### Prisma information

Debug logs
```
  prisma:tryLoadEnv  Environment variables loaded from /home/node/app/.env +0ms
  prisma:tryLoadEnv  Environment variables loaded from /home/node/app/.env +0ms
  prisma:client  checkPlatformCaching:postinstall false +0ms
  prisma:client  checkPlatformCaching:ciName undefined +0ms
  prisma:tryLoadEnv  Environment variables loaded from /home/node/app/.env +4s
  prisma:client  dirname /home/node/app/node_modules/@prisma/bidx +0ms
  prisma:client  relativePath ../../../prisma/bidx +0ms
  prisma:client  cwd /home/node/app/prisma/bidx +0ms
  prisma:client  clientVersion 5.1.1 +1ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:get-platform  Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "debian"
} +0ms
  prisma:get-platform  Trying platform-specific paths for "debian" (and "ubuntu") +1ms
  prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.1.1 +3ms
  prisma:get-platform  The parsed libssl version is: 1.1.x +1ms
  prisma:client:engines:resolveEnginePath  enginePath /home/node/app/node_modules/@prisma/bidx/libquery_engine-debian-openssl-1.1.x.so.node +0ms
  prisma:client:libraryEngine  library starting +70ms
  prisma:client:libraryEngine  library started +9ms
  prisma:client  Prisma Client call: +83ms
  prisma:client  prisma.paypalTransaction.create({
  data: {
    bidxid: "test-user",
    profileid: "test-profile",
    transaction: "{\"Comment1\": \"Account bidxid: Internet Bidding (1), Basic Service\"}",
    transid: "1234567890",
    transtime: new Date("2023-08-09T22:04:49.297Z")
  }
}) +1ms
  prisma:client  Generated request: +1ms
  prisma:client  {
  "modelName": "PaypalTransaction",
  "action": "createOne",
  "query": {
    "arguments": {
      "data": {
        "bidxid": "test-user",
        "profileid": "test-profile",
        "transaction": "{\"Comment1\": \"Account bidxid: Internet Bidding (1), Basic Service\"}",
        "transid": "1234567890",
        "transtime": {
          "$type": "DateTime",
          "value": "2023-08-09T22:04:49.297Z"
        }
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +8ms
  prisma:client:request_handler  PrismaClientUnknownRequestError: Query createOnePaypalTransaction is required to return data, but found no record(s).
    at Oo (/home/node/app/node_modules/@prisma/bidx/runtime/library.js:26:6510)
    at Dt.buildQueryError (/home/node/app/node_modules/@prisma/bidx/runtime/library.js:104:902)
    at Dt.request (/home/node/app/node_modules/@prisma/bidx/runtime/library.js:103:4117)
    at Object.singleLoader (/home/node/app/node_modules/@prisma/bidx/runtime/library.js:122:5515) {
  clientVersion: '5.1.1'
} +0ms

```

### Environment & setup

- OS: debian running inside of docker
- Database: MySQL 8
- Node.js version: v18.17.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.1.1
@prisma/client          : 5.1.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.1.1-1.6a3747c37ff169c90047725a05a6ef02e32ac97e
Default Engines Hash    : 6a3747c37ff169c90047725a05a6ef02e32ac97e
Studio                  : 0.492.0
```

**Comment by ludralph** [comment]
Closing [#20632](https://github.com/prisma/prisma/issues/20632) in favour of [#8982](https://github.com/prisma/prisma/issues/8982)
