### ISSUE TITLE
Expected parent IDs to be set when ordering by parent ID (with detailed debug info)

### ISSUE THREAD

**Issue by henrymcl** [prisma/prisma#20649]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.17.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 5.1.1              |
| Query Engine    | 6a3747c37ff169c90047725a05a6ef02e32ac97e|
| Database        | mysql              |

<details>
<summary>

## Logs

</summary>

```
prisma:tryLoadEnv Environment variables loaded from /PROJECT_ROOT_DIR/.env
prisma:client checkPlatformCaching:postinstall 
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables loaded from /PROJECT_ROOT_DIR/.env
prisma:client dirname /PROJECT_ROOT_DIR/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /PROJECT_ROOT_DIR/prisma
prisma:client clientVersion 5.1.1
prisma:client clientEngineType library
prisma:client:libraryEngine internalSetup
prisma:get-platform Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
}
prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu")
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.1.1
prisma:get-platform The parsed libssl version is: 1.1.x
prisma:client:engines:resolveEnginePath enginePath /PROJECT_ROOT_DIR/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.$queryRaw(SELECT Service.description, Service.key, SUM(reducedCost) as cost FROM Service JOIN Project ON serviceKey = Service.key JOIN Record ON Project.id = projectId WHERE organizationId = ? GROUP BY Service.key, ["N54PDIm"])
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client prisma.$queryRaw(SELECT Service.description, Service.key, SUM(reducedCost) as cost FROM Service JOIN Project ON serviceKey = Service.key JOIN Record ON Project.id = projectId WHERE organizationId = ? GROUP BY Service.key, ["N54PDIm"])
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.1.1"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
```
</details>

<details>
<summary>

## Client Snippet

</summary>

```ts
// koa 2.14.2
router.get("/own/record", async (ctx) => {
  const records = await prisma.record.findMany({
    where: {
      Project: {
        organizationId: ctx.state.user.id,
      },
    },
    select: {
      id: true,
      title: true,
      createdAt: true,
      reducedCost: true,
      Project: {
        select: {
          id: true,
          deactivatedAt: true,
          Service: {
            select: {
              description: true,
              deactivatedAt: true,
            },
          },
        },
      },
    },
    orderBy: [
      {
        createdAt: "asc",
      },
    ],
  });
  const transactions = await prisma.transaction.findMany({
    where: {
      targetId: ctx.state.user.id,
    },
    select: {
      id: true,
      amount: true,
      createdAt: true,
    },
  });
  ctx.status = 200;
  ctx.body = { status: true, data: { records, transactions } };
});
```
</details>

<details>
<summary>

## Schema

</summary>

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Organization {
  id                  String         @id
  name                String
  email               String         @unique
  password            String
  contactInfo         Json
  balance             Decimal        @db.Decimal(65, 10)
  createdAt           DateTime       @default(now())
  updatedAt           DateTime       @updatedAt
  deactivatedAt       DateTime?
  TransactionAsSource Transaction[]  @relation("SourceOrganization")
  TransactionAsTarget Transaction[]  @relation("TargetOrganization")
  Projects            Project[]
}

enum ServiceMode {
  REQUEST
  TOKEN
}
model Service {
  key           String      @id
  description   String
  mode          ServiceMode
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt
  deactivatedAt DateTime?
  unitCost      Decimal
  targetURL     String
  apiKey        String
  Project       Project[]
  amountPath    String?
}

model Transaction {
  id        String       @id
  source    Organization @relation("SourceOrganization", fields: [sourceId], references: [id], onDelete: Restrict, onUpdate: Cascade)
  sourceId  String
  target    Organization @relation("TargetOrganization", fields: [targetId], references: [id], onDelete: Restrict, onUpdate: Cascade)
  targetId  String
  amount    Decimal      @db.Decimal(65, 10)
  createdAt DateTime     @default(now())
}

model Project {
  id             String       @id
  name           String
  Organization   Organization @relation(fields: [organizationId], references: [id], onDelete: Restrict, onUpdate: Cascade)
  organizationId String
  Service        Service      @relation(fields: [serviceKey], references: [key], onDelete: Restrict, onUpdate: Cascade)
  serviceKey     String
  maxToken       Int?
  targetURL      String?
  apiKey         String?
  burstLimit     Int
  Record         Record[]
  createdAt      DateTime     @default(now())
  updatedAt      DateTime     @updatedAt
  deactivatedAt  DateTime?
}

model Record {
  id          String      @id
  Project     Project     @relation(fields: [projectId], references: [id], onDelete: Restrict, onUpdate: Cascade)
  projectId   String
  title       String
  mode        ServiceMode
  unitCost    Decimal     @db.Decimal(65, 10)
  reducedCost Decimal     @db.Decimal(65, 10)
  createdAt   DateTime    @default(now())
  ip          String
}
```
</details>

<details>
<summary>

## SQL Schema

</summary>

```sql
CREATE TABLE `Organization` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contactInfo` json NOT NULL,
  `balance` decimal(65,10) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  `deactivatedAt` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Organization_email_key` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `Service` (
  `key` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mode` enum('REQUEST','TOKEN') COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL,
  `unitCost` decimal(65,30) NOT NULL,
  `description` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `deactivatedAt` datetime(3) DEFAULT NULL,
  `amountPath` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `apiKey` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `targetURL` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `Project` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `organizationId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `serviceKey` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `maxToken` int DEFAULT NULL,
  `targetURL` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `apiKey` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `burstLimit` int NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `deactivatedAt` datetime(3) DEFAULT NULL,
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `Project_organizationId_fkey` (`organizationId`),
  KEY `Project_serviceKey_fkey` (`serviceKey`),
  CONSTRAINT `Project_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `Organization` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `Project_serviceKey_fkey` FOREIGN KEY (`serviceKey`) REFERENCES `Service` (`key`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `Record` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mode` enum('REQUEST','TOKEN') COLLATE utf8mb4_unicode_ci NOT NULL,
  `unitCost` decimal(65,10) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `reducedCost` decimal(65,10) NOT NULL,
  `projectId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ip` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `Record_projectId_fkey` (`projectId`),
  CONSTRAINT `Record_projectId_fkey` FOREIGN KEY (`projectId`) REFERENCES `Project` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `Transaction` (
  `id` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sourceId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `targetId` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `amount` decimal(65,10) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `Transaction_sourceId_fkey` (`sourceId`),
  KEY `Transaction_targetId_fkey` (`targetId`),
  CONSTRAINT `Transaction_sourceId_fkey` FOREIGN KEY (`sourceId`) REFERENCES `Organization` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `Transaction_targetId_fkey` FOREIGN KEY (`targetId`) REFERENCES `Organization` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
</details>

<details>
<summary>

## Original error (with logs stdout for all 4 levels)

</summary>

```
prisma:info Starting a mysql pool with 9 connections.
prisma:query SELECT PROJECT_DB.`Record`.`id`, PROJECT_DB.`Record`.`title`, PROJECT_DB.`Record`.`createdAt`, PROJECT_DB.`Record`.`reducedCost`, PROJECT_DB.`Record`.`projectId` FROM PROJECT_DB.`Record` WHERE (PROJECT_DB.`Record`.`id`) IN (SELECT `t0`.`id` FROM PROJECT_DB.`Record` AS `t0` INNER JOIN PROJECT_DB.`Project` AS `j0` ON (`j0`.`id`) = (`t0`.`projectId`) WHERE (`j0`.`organizationId` = ? AND `t0`.`id` IS NOT NULL)) ORDER BY PROJECT_DB.`Record`.`createdAt` ASC
thread 'tokio-runtime-worker' panicked at 'Expected parent IDs to be set when ordering by parent ID.', query-engine/core/src/interpreter/query_interpreters/inmemory_record_processor.rs:69:18
stack backtrace:
prisma:query SELECT PROJECT_DB.`Project`.`id`, PROJECT_DB.`Project`.`deactivatedAt`, PROJECT_DB.`Project`.`serviceKey` FROM PROJECT_DB.`Project` WHERE PROJECT_DB.`Project`.`id` IN (?,?,?,?)
   0:     0x7fc6f58d5a7c - <unknown>
   1:     0x7fc6f51b9adf - <unknown>
   2:     0x7fc6f58ac444 - <unknown>
   3:     0x7fc6f58d71cf - <unknown>
   4:     0x7fc6f58d6dce - <unknown>
   5:     0x7fc6f58d7e30 - <unknown>
   6:     0x7fc6f58d7914 - <unknown>
   7:     0x7fc6f58d7876 - <unknown>
   8:     0x7fc6f58d7861 - <unknown>
   9:     0x7fc6f5087e82 - <unknown>
  10:     0x7fc6f5088272 - <unknown>
  11:     0x7fc6f56cc982 - <unknown>
  12:     0x7fc6f56cc7ba - <unknown>
  13:     0x7fc6f56c8fd9 - <unknown>
  14:     0x7fc6f56c617b - <unknown>
  15:     0x7fc6f56c0e25 - <unknown>
  16:     0x7fc6f56cbdf7 - <unknown>
  17:     0x7fc6f56cd2ad - <unknown>
  18:     0x7fc6f56c0eb3 - <unknown>
  19:     0x7fc6f56fd250 - <unknown>
  20:     0x7fc6f56fda93 - <unknown>
  21:     0x7fc6f50bec27 - <unknown>
  22:     0x7fc6f50c106b - <unknown>
  23:     0x7fc6f50ddc71 - <unknown>
  24:     0x7fc6f50db61a - <unknown>
  25:     0x7fc6f50c782a - <unknown>
  26:     0x7fc6f5128a4a - <unknown>
  27:     0x7fc6f5102e0c - <unknown>
  28:     0x7fc6f510cbad - <unknown>
  29:     0x7fc6f58ed696 - <unknown>
  30:     0x7fc6f58f6aed - <unknown>
  31:     0x7fc6f58f0309 - <unknown>
  32:     0x7fc6f58efd51 - <unknown>
  33:     0x7fc6f58f0924 - <unknown>
  34:     0x7fc6f58d8d46 - <unknown>
  35:     0x7fc6ff66a609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  36:     0x7fc6ff58f133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  37:                0x0 - <unknown>
prisma:error 
Invalid `prisma.record.findMany()` invocation in
/PROJECT_ROOT_DIR/src/server/routes/Organization.ts:42:39

  39 });
  40 
  41 router.get("/own/record", async (ctx) => {
→ 42   const records = await prisma.record.findMany(
Expected parent IDs to be set when ordering by parent ID.

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

> Github issue link omitted for brevity

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

PrismaClientRustPanicError: 
Invalid `prisma.record.findMany()` invocation in
/PROJECT_ROOT_DIR/src/server/routes/Organization.ts:42:39

  39 });
  40 
  41 router.get("/own/record", async (ctx) => {
→ 42   const records = await prisma.record.findMany(
Expected parent IDs to be set when ordering by parent ID.

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

> Github issue link omitted for brevity

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at Hr.handleRequestError (/PROJECT_ROOT_DIR/node_modules/@prisma/client/runtime/library.js:122:7324)
    at Hr.handleAndLogRequestError (/PROJECT_ROOT_DIR/node_modules/@prisma/client/runtime/library.js:122:6388)
    at Hr.request (/PROJECT_ROOT_DIR/node_modules/@prisma/client/runtime/library.js:122:6108)
    at async l (/PROJECT_ROOT_DIR/node_modules/@prisma/client/runtime/library.js:126:10298) {
  clientVersion: '5.1.1'
}
```
</details>

## Prisma Engine Query
```
{"X":true}}}}}}}
```

**Comment by henry132109** [comment]
I was able to avert the crash by substituting it with a raw query:

```js
const records =
    await prisma.$queryRaw`SELECT r.id, r.title, r.createdAt, r.reducedCost, r.projectId, s.description, p.deactivatedAt OR s.deactivatedAt as deactivatedAt FROM Record r JOIN Project p ON p.id = projectId JOIN \`Service\` s ON s.key = serviceKey WHERE p.organizationId = ${ctx.state.user.id} ORDER BY r.createdAt ASC`;
```

It leaves something to be desired though.

**Comment by Jolg42** [comment]
Looks similar / duplicate of
- https://github.com/prisma/prisma/issues/15745
- https://github.com/prisma/prisma/issues/14899
- https://github.com/prisma/prisma/issues/14425
- https://github.com/prisma/prisma/issues/17992
- https://github.com/prisma/prisma/issues/20397

**Comment by aqrln** [comment]
Hi @henry132109! We have added support for MySQL 8.0.14 and newer to the `relationJoins` preview feature in Prisma 5.10.0, which we expect to resolve this issue thanks to the database comparing the IDs itself when joining the data.

Does enabling the `relationJoins` preview feature fix this problem for you?

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["relationJoins"]
}
```

Thank you in advance for following up 🙏

**Comment by ludralph** [comment]
Closing this in favor of [#17992](https://github.com/prisma/prisma/issues/17992)
