### ISSUE TITLE
Client extensions that require use of a client-level method silently ignore transactions

### ISSUE THREAD

**Issue by fnimick** [prisma/prisma#20678]
### Bug description

Any Prisma client extensions that require use of the `client` directly in order to call client-level methods will silently ignore transactions. This is *not documented* and should be (or be fixed), considering how many examples require or recommend the use of the client.

[Example 1](https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions/shared-extensions#call-a-client-level-method-from-your-packaged-extension)
[Example 2](https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions/query#wrap-a-query-into-a-batch-transaction)
[Example 3](https://github.com/prisma/prisma-client-extensions/blob/main/row-level-security/script.ts)

In all of these cases, if you trigger the extension from inside a transaction (interactive or batched), the extension code will issue the queries in a new connection and ignore the transaction that you *think* you are operating in.

### How to reproduce

- Issue a query which mutates the database using one of the examples in a transaction, followed by one which deliberately errors
- Confirm via the debug log that multiple connections and transactions are being used
- Confirm that the database mutation, which should have been in the transaction and rolled back, is persisted

### Expected behavior

There should be a way to write client extensions that can operate using the client or the current transaction context.

### Prisma information

An example test using the RLS prisma extension example linked above:
```ts
  await rlsPrismaClient.$transaction(async (tx) => {
    console.log(await tx.organization.findMany());
    console.log("---");
    await tx.organization.create({ data: { name: "testOrg" } });
    console.log(await tx.organization.findMany());
    throw new Error("boom");
  });
```

The `testOrg` organization is created and persisted, even though the creation call was made on a transaction client context.

An alternative example using batched transactions, which fails in the same way:
```ts
  console.log(await rlsPrismaClient.$transaction([
    rlsPrismaClient.organization.findMany(),
    rlsPrismaClient.organization.create({ data: { name: "testOrg" } }),
    rlsPrismaClient.organization.findMany(),
    rlsPrismaClient.organization.create({ data: { name: "testOrg", id: 'foobar' } }), // id is deliberately invalid
  ]));
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL 14
- Node.js version: 18.14.1

### Prisma Version

```
prisma                  : 5.1.1
@prisma/client          : 5.1.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.1.1-1.6a3747c37ff169c90047725a05a6ef02e32ac97e
Default Engines Hash    : 6a3747c37ff169c90047725a05a6ef02e32ac97e
Studio                  : 0.492.0
Preview Features        : multiSchema
```

**Comment by whygee-dev** [comment]
Any news on this ?
This creates a very scary bug when using extensions to do a generic history / audit log

**Comment by Jolg42** [comment]
@whygee-dev Did you reproduce this with the same code & setup? Or is your code / setup different? Please let us know.
We would need to reproduce this first and additional information is always useful.
It would be ideal to have a simple reproduction repository that anyone could try out to confirm this for example.

**Comment by whygee-dev** [comment]
@Jolg42 Not exactly the same setup but i believe the root problem is the same. Here is a simple reproduction: https://github.com/whygee-dev/client-extensions-tx-bug-reproduction

**Comment by ploca14** [comment]
Does this also affect nested writes?

**Comment by jasonmacdonald** [comment]
This is a significant issue. Two separate Prisma-based frameworks have recognized it. I hope this gets more attention soon.

- https://zenstack.dev/docs/reference/limitations#sequential-operations-transaction
- https://github.com/cerebruminc/yates?tab=readme-ov-file#nested-transactions

In both cases, the note that they cannot support sequential transactions (Array) is a direct result of this bug, as are the others linked to this ticket. 

To make matters worse, RLS cannot be done correctly without the sequential approach, which means you are forced to choose one way to perform transactions throughout your entire code base AND the plugins/extensions you may pull in. Which is sometimes hard to guarantee for large projects.

All of these things combine to make it very easy to introduce bugs that break things like RLS permissions. This could potentially expose your business to unwanted disclosure of customer data through failed permission checks, which could result in lawsuits. This seems super essential!

Please look into it more seriously. I beg you.

**Comment by jkomyno** [comment]
Hi all, I've looked into this issue, and I can reproduce this with the latest version of Prisma, 5.17.0.

## Reproduction

To reproduce this issue, imagine we have two tables, `user` and `log`.
We create a Prisma extension named `prismaLogExtension` that, every time a new user record is created via `user.create(...)`, creates a new log entry.

Then, within a transaction opened in the `prismaLogExtension`'s scope, we create a couple of users - which will trigger the Client extension's logic -, and then we raise an error to forcefully cause a rollback of such transaction.
After the transaction has executed (within a try/catch block), we look into the `user` and `log` tables.

### Expectation

- `prismaLogExtension.$transaction(async (tx) => ...)` rolls back ✅
- `tx.user.create` triggers the `prismaLogExtension`'s logic ✅
- No entry is persisted in the database after the transaction is rolled back ❌

The expected series of operation is

```sql
BEGIN

-- Create user 1
INSERT INTO "public"."User" ...
INSERT INTO "public"."Log" ...

-- Create user 2
INSERT INTO "public"."User" ...
INSERT INTO "public"."Log" ...

ROLLBACK
```

all executed within the same transactional connection.

### Reality

- 2 log records are persisted in the database after the transaction is rolled back
- According to the query logs, the expected series of operations is correct. However, there exist two separate, concurrent blocks

1. One that creates records in the `user` table, within a transactional context created via `prismaLogExtension.$transaction(async (tx) => ...)`:
  ```sql
  BEGIN
  
  -- Create user 1
  INSERT INTO "public"."User" ...
  
  -- Create user 2
  INSERT INTO "public"."User" ...
  
  ROLLBACK
  ```
2. One that creates records in the `log` table, without any transactional guarantee, but in which every write follows the corresponding write attempt in the `user` table:
  ```sql
  -- Create log for user 1
  INSERT INTO "public"."Log" ...
  
  -- Create log for user 2
  INSERT INTO "public"."Log" ...
  ```

Here's a sequence diagram to conceptually visualise this:

```mermaid
sequenceDiagram
    participant Client
    participant prismaLogExtension
    participant prisma
    
    Client->>prismaLogExtension: BEGIN
    note right of prismaLogExtension: Transaction Start
    
    Client->>prismaLogExtension: INSERT INTO "public"."User" ...<br>-- Create user 1
    prismaLogExtension-->>Client: OK
    Client->>prisma: INSERT INTO "public"."Log" ...<br>-- Create log 1
    prisma-->>Client: OK
    
    Client->>prismaLogExtension: INSERT INTO "public"."User" ...<br>-- Create user 2
    prismaLogExtension-->>Client: OK
    Client->>prisma: INSERT INTO "public"."Log" ...<br>-- Create log 2
    prisma-->>Client: OK
    
    Client->>prismaLogExtension: ROLLBACK
    note right of prismaLogExtension: Transaction Rollback
```

### Setup

Here's the setup I've used to reproduce this issue:

- `schema.prisma`
  ```prisma
  generator client {
    provider  = "prisma-client-js"
  }
  
  datasource db {
    provider = "postgres"
    url      = env("TEST_POSTGRES_URI")
  }
  
  model User {
    id     Int      @id @default(autoincrement())
    name   String
  }
  
  model Log {
    id     Int      @id @default(autoincrement())
    text   String?
  }
  ```

- `index.ts`, the snippet using `@prisma/client`
  ```typescript
  import { PrismaClient } from '.prisma/client'
  
  async function main() {
    const prisma = new PrismaClient({ log: ['query'] })
  
    const prismaLogExtension = prisma.$extends({
      query: {
        user: {
          create: async ({ query, args }) => {
            const result = await query(args)
            console.log('[user.create]')
            console.dir(result, { depth: null })
  
            if (!('id' in result) || typeof result.id !== 'number') {
              throw new Error('User not created')
            }
  
            await prisma.log.create({
              data: {
                text: 'User created',
              },
            })
  
            return result
          },
        },
      },
    })
  
    await prisma.user.deleteMany()
    await prisma.log.deleteMany()
  
    try {
      await prismaLogExtension.$transaction(async (tx) => {
        await tx.user.create({
          data: {
            name: 'user1',
          },
        })
        
        await tx.user.create({
          data: {
            name: 'user2',
          },
        })
        
        // Enforce a rollback of the whole transaction
        throw new Error('Rollback')
      })
    } catch (error) {
      const e = error as Error
      console.error(error)
      console.log('')
    }
  
    const users = await prisma.user.findMany()
    console.log('[users]')
    console.dir(users, { depth: null })
    
    const logs = await prisma.log.findMany()
    console.log('[logs]')
    console.dir(logs, { depth: null })
  
    process.exit(0)
  }
  
  void main().catch((e) => {
    console.log(e.message)
    process.exit(1)
  })
  ```

- CLI Output
  ```
  prisma:query DELETE FROM "public"."User" WHERE 1=1
  prisma:query DELETE FROM "public"."Log" WHERE 1=1
  prisma:query BEGIN
  prisma:query INSERT INTO "public"."User" ("name") VALUES ($1) RETURNING "public"."User"."id", "public"."User"."name"
  [user.create]
  { id: 1, name: 'user1' }
  prisma:query INSERT INTO "public"."Log" ("text") VALUES ($1) RETURNING "public"."Log"."id", "public"."Log"."text"
  prisma:query INSERT INTO "public"."User" ("name") VALUES ($1) RETURNING "public"."User"."id", "public"."User"."name"
  [user.create]
  { id: 2, name: 'user2' }
  prisma:query INSERT INTO "public"."Log" ("text") VALUES ($1) RETURNING "public"."Log"."id", "public"."Log"."text"
  prisma:query ROLLBACK
  Error: Rollback
      at /.../index.ts:48:13
      at async Proxy._transactionWithCallback (/.../node_modules/.prisma/client/runtime/library.js:130:7722)
      at async main (/.../index.ts:34:5)
  
  prisma:query SELECT "public"."User"."id", "public"."User"."name" FROM "public"."User" WHERE 1=1 OFFSET $1
  [users]
  []
  prisma:query SELECT "public"."Log"."id", "public"."Log"."text" FROM "public"."Log" WHERE 1=1 OFFSET $1
  [logs]
  [ { id: 1, text: 'User created' }, { id: 2, text: 'User created' } ]
  ```

### Notes

This can techincally be interpreted as a limitation of Prisma Client Extensions, rather than a bug itself, as `prismaLogExtension` refers to the `prisma` client available in the outer scope when creating log entries, which thus lies outside any transactional guarantees of the extension itself.

To improve this, Prisma should allow passing the transactional context `tx` to the Prisma Client Extension closure, so that the `prismaLogExtension` could be rewritten as:

```diff
const prisma = new PrismaClient({ log: ['query'] })

const prismaLogExtension = prisma.$extends({
  query: {
    user: {
-        create: async ({ query, args }) => {
+       create: async ({ query, args, prisma: tx }) => {
        const result = await query(args)
        console.log('[user.create]')
        console.dir(result, { depth: null })

        if (!('id' in result) || typeof result.id !== 'number') {
          throw new Error('User not created')
        }

-         await prisma.log.create({
+         await tx.log.create({
          data: {
            text: 'User created',
          },
        })

        return result
      },
    },
  },
})
```

**Comment by marklai1998** [comment]
Just come across the same issue, I uses the official example for my RLS implementation and its not rolling back any of my interactive transaction

```ts
rls.$transaction(tx=>{ // uses the rls client with a nested transaction inside
  tx.table.create({foo: "bar"}) // this will still be inserted
  throw new Error("OOPS")
})
```

**Comment by patrick-yendou** [comment]
We have exactly the same issue @marklai1998. We followed the official docs on how to implement RLS. This basically means the transactions in our entire codebase don't work, since we are using the RLS client everywhere. 

Is there any workaround we can do right now to fix this?

**Comment by fnimick** [comment]
@marklai1998  @patrick-yendou   I dug out the solution I used to use before we switched off prisma entirely. Hope this helps?

https://gist.github.com/fnimick/9fce65218a15b8b0ef3eb4592c20a0e4

I was tempted to try to make this a library, but I don't want to be responsible for people messing up their databases with transactions, given how hacky this is.

**Comment by marklai1998** [comment]
@fnimick Never thought of overriding the `$transaction`, clever

I've cleaned up your example and tested in my projects and working as expected

Here is my implementation:
- All in 1 extension
- Prevent double running rls query
- Fixed `$executeRaw` and `$executeRawUnsafe` in transaction

```ts
import { AsyncLocalStorage } from 'node:async_hooks';

const rlsStore = new AsyncLocalStorage<{ alreadyInRls: boolean }>();

export const rls = () => {
  return Prisma.defineExtension((client) => {
    return client.$extends({
      name: 'RLS',
      query: {
        $allModels: {
          async $allOperations({ args, query, model }) {
            const alreadyInRls = rlsStore.getStore()?.alreadyInRls;
            if (alreadyInRls) return query(args);

            const results = await client.$transaction([
              `YOUR RLS QUERY`,
              query(args),
            ]);

            return results[results.length - 1];
          },
        },
        async $executeRaw({ args, query }) {
          const alreadyInRls = rlsStore.getStore()?.alreadyInRls;
          if (alreadyInRls) return query(args);

          const results = await client.$transaction([
            client.$executeRawUnsafe(`YOUR RLS QUERY`),
            query(args),
          ]);

          return results[results.length - 1];
        },
        async $executeRawUnsafe({ args, query }) {
          const alreadyInRls = rlsStore.getStore()?.alreadyInRls;
          if (alreadyInRls) return query(args);

          const results = await client.$transaction([
            client.$executeRawUnsafe(`YOUR RLS QUERY`),
            query(args),
          ]);

          return results[results.length - 1];
        },
        async $queryRaw({ args, query }) {
          const results = await client.$transaction([
            client.$executeRawUnsafe(`YOUR RLS QUERY`),
            query(args),
          ]);

          return results[results.length - 1];
        },
        async $queryRawUnsafe({ args, query }) {
          const results = await client.$transaction([
            client.$executeRawUnsafe(`YOUR RLS QUERY`),
            query(args),
          ]);

          return results[results.length - 1];
        },
      },
      client: {
        // https://github.com/prisma/prisma/issues/20678
        $transaction(first: any, ...rest: any) {
          return rlsStore.run({ alreadyInRls: true }, () => {
            if (Array.isArray(first)) {
              return client.$transaction(
                [client.$executeRawUnsafe(`YOUR RLS QUERY`), ...first],
                ...rest
              );
            }

            return client.$transaction(
              async (tx) => {
                await client.$executeRawUnsafe(`YOUR RLS QUERY`);
                return first(tx);
              },
              ...rest
            );
          });
        },
      } as { $transaction: (typeof client)['$transaction'] },
    });
  });
};

```

**Comment by patrick-yendou** [comment]
> @fnimick Never thought of overriding the `$transaction`, clever
> 
> I've cleaned up your example and tested in my projects and working as expected
> 
> Here is my implementation:
> 
> * All in 1 extension
> * Prevent double running rls query
> * Fixed `$executeRaw` and `$executeRawUnsafe` in transaction
> 
> ```ts
> import { AsyncLocalStorage } from 'node:async_hooks';
> 
> const rlsStore = new AsyncLocalStorage<{ alreadyInRls: boolean }>();
> 
> export const rls = () => {
>   return Prisma.defineExtension((client) => {
>     return client.$extends({
>       name: 'RLS',
>       query: {
>         $allModels: {
>           async $allOperations({ args, query, model }) {
>             const alreadyInRls = rlsStore.getStore()?.alreadyInRls;
>             if (alreadyInRls) return query(args);
> 
>             const results = await client.$transaction([
>               `YOUR RLS QUERY`,
>               query(args),
>             ]);
> 
>             return results[results.length - 1];
>           },
>         },
>         async $executeRaw({ args, query }) {
>           const alreadyInRls = rlsStore.getStore()?.alreadyInRls;
>           if (alreadyInRls) return query(args);
> 
>           const results = await client.$transaction([
>             client.$executeRawUnsafe(`YOUR RLS QUERY`),
>             query(args),
>           ]);
> 
>           return results[results.length - 1];
>         },
>         async $executeRawUnsafe({ args, query }) {
>           const alreadyInRls = rlsStore.getStore()?.alreadyInRls;
>           if (alreadyInRls) return query(args);
> 
>           const results = await client.$transaction([
>             client.$executeRawUnsafe(`YOUR RLS QUERY`),
>             query(args),
>           ]);
> 
>           return results[results.length - 1];
>         },
>         async $queryRaw({ args, query }) {
>           const results = await client.$transaction([
>             client.$executeRawUnsafe(`YOUR RLS QUERY`),
>             query(args),
>           ]);
> 
>           return results[results.length - 1];
>         },
>         async $queryRawUnsafe({ args, query }) {
>           const results = await client.$transaction([
>             client.$executeRawUnsafe(`YOUR RLS QUERY`),
>             query(args),
>           ]);
> 
>           return results[results.length - 1];
>         },
>       },
>       client: {
>         // https://github.com/prisma/prisma/issues/20678
>         $transaction(first: any, ...rest: any) {
>           return rlsStore.run({ alreadyInRls: true }, () => {
>             if (Array.isArray(first)) {
>               return client.$transaction(
>                 [client.$executeRawUnsafe(`YOUR RLS QUERY`), ...first],
>                 ...rest
>               );
>             }
> 
>             return client.$transaction(
>               async (tx) => {
>                 await client.$executeRawUnsafe(`YOUR RLS QUERY`);
>                 return first(tx);
>               },
>               ...rest
>             );
>           });
>         },
>       } as { $transaction: (typeof client)['$transaction'] },
>     });
>   });
> };
> ```

@marklai1998 I think there might be an issue in your example. The second `await client.$executeRawUnsafe(`YOUR RLS QUERY`);` needs to be `await tx.$executeRawUnsafe(`YOUR RLS QUERY`);`

I wrote a helper that can be reused for different prisma extensions (we have multiple)
```
const getTransactionClientWithRlsClaim = (client: PrismaClient, claim: Prisma.Sql) => {
  return (first: any, ...rest: any) => {
    if (Array.isArray(first)) {
      return client.$transaction([client.$executeRaw`${claim}`, ...first], ...rest);
    }

    return client.$transaction(
      async (txn: PrismaClient) => {
        await txn.$executeRaw`${claim}`;
        return first(txn);
      },
      ...rest
    );
  };
};

export const myExtension = () => {
  return Prisma.defineExtension(prisma =>
    prisma.$extends({
      query: {
        $allModels: {
          async $allOperations({ args, query }) {
            const [, result] = await prisma.$transaction([
              prisma.$executeRaw`YOUR RLS QUERY`,
              query(args)
            ]);
            return result;
          }
        }
      },
      client: {
        $transaction: getTransactionClientWithRlsClaim(
          prisma,
          Prisma.sql`SELECT set_config('YOUR RLS QUERY`
        )
      }
    })
  );
};

```

**Comment by marklai1998** [comment]
@patrick-yendou updated, just a typo(try to hide my logic)

**Comment by fnimick** [comment]
I believe the two-client approach does run the transactions / RLS code twice. The parent client opens a transaction, sets RLS, and then defers to a second extended client (either explicitly or created on the fly with e.g. 
`getTransactionClientWithRlsClaim`) which then opens another transaction and sets RLS variables again.

@marklai1998 your solution is incredibly clever, would you consider adding tests and publishing this as a library?

**Comment by marklai1998** [comment]
@fnimick I don't see the need of an library yet
the rls implementation might vary that rather keep an example here than thinking about how to generalise it.

There is an "issue" with my example that you cannot use regular client inside a tx.
I see this issue is assigned, hope we get an fix asap

**Comment by fnimick** [comment]
@marklai1998 out of curiosity what do you mean by the rls implementation varying? I assume different RLS strategies simply set different transaction variables, which we could easily support by passing in a callback to the `rls` function (like my example which was actually how we did it)

**Comment by marklai1998** [comment]
@fnimick  you can use `set local` for things more than RLS, RLS(to prevent other ppl seeing not your stuff) is only one of the implication

I also use it to set current user identity to use it as default value of record `createdAt` with `@default(dbgenerated("(current_setting('app.current_caller_id'::text))::uuid"))`

to generalize it would be a way to add any query to the same transaction or fix transaction so it always run in single context instead of saying its for "RLS"

So I think posting the fix here would be plenty enough(assume this gonna be fixed soon), ppl can take it and adjust it to your need
the main sauce is to override `$transaction`

If we dont get this fixed in upcoming few releases we can think of making it a lib

**Comment by fnimick** [comment]
> If we dont get this fixed in upcoming few releases we can think of making it a lib

I'm not hopeful considering it took a full year for them to even acknowledge this is a problem!

**Comment by patrick-yendou** [comment]
The only problem with your solution @marklai1998 is that you lose typing on the transaction client. Any way to fix this?

I played around a bit, but couldn't find a way to make it work.

**Comment by chawes13** [comment]
This is a huge issue – I don't think we can safely use the extension feature anywhere in our application as a result. I'd love to see this acknowledged in the documentation as a warning on https://www.prisma.io/docs/orm/prisma-client/client-extensions, at least until it's resolved.

**Comment by marklai1998** [comment]
@chawes13 meanwhile you can try the tmp fix above

**Comment by baoshan** [comment]
Based on @marklai1998’s concept, this one fixes several edge cases and reduces roundtrips when possible.

```ts
import { Prisma, type PrismaPromise } from '@prisma/client'
import { AsyncLocalStorage } from 'async_hooks'

const storage = new AsyncLocalStorage<true>()
type Operation = { args: any; query: (args: any) => PrismaPromise<any> }

/**
 * Returns a Prisma extension prepending `sql` to any (explicit or implicit)
 * transaction.
 */
export const prepend = (sql: string) => {
  const exec = (client: any) => client.$executeRawUnsafe(sql)
  return Prisma.defineExtension((client) =>
    client.$extends({
      query: {
        $allOperations: async ({ args, query }: Operation) =>
          storage.getStore()
            ? query(args)
            : (await client.$transaction([exec(client), query(args)])).pop(),
      },
      client: {
        $transaction: (first: any, ...rest: any) =>
          storage.getStore()
            ? client.$transaction(first, ...rest)
            : storage.run(true, async () =>
                Array.isArray(first)
                  ? client
                      .$transaction([exec(client), ...first], ...rest)
                      .then((results) => results.slice(1))
                  : client.$transaction(
                      async (tx) => {
                        await exec(tx)
                        return first(tx)
                      },
                      ...rest,
                    ),
              ),
      },
    }),
  ) as <T>(t: T) => T
}

```

**Comment by JulienLemaitre** [comment]
I come to this issue because I need to implement an audit-log context in an API route handler that looks like this at the end :

```typescript
return await prismaClient
  .$transaction(
    async (tx) => {
      await tx.person.createMany({data: personCreateManyInput});
      await tx.organization.createMany({data: organizationCreateManyInput});
      await tx.collection.createMany({data: collectionCreateManyInput});
      const mMSource = await tx.mMSource.create({data: mMSourceInput});
      const mMSourceId = mMSource.id;
      const metronomeMarksInput = state.metronomeMarks
          .filter((metronomeMark) => !metronomeMark.noMM)
          .map((metronomeMark) => getMetronomeMarkDBInputFromState(metronomeMark, mMSourceId));
      const metronomeMarks = await tx.metronomeMark.createMany({data: metronomeMarksInput});

      return { mMSourceInput, mMSource, metronomeMarks };
    })
```

I'm about to extend my prismaClient to create a postgreSQL context with `set_audit_context(<userId>, <reviewId>)` and use this variable in triggers.

@marklai1998 When you write:

> There is an "issue" with my example that you cannot use regular client inside a tx.

Is that not what your fix propose to fix in the first place? That means it will not fit with my code I suppose.

And @baoshan , I have to work on your solution, I don't understand all what your code is doing. But can you provide a short example of how to use it please ?

**Comment by marklai1998** [comment]
> I come to this issue because I need to implement an audit-log context in an API route handler that looks like this at the end :
> 
> return await prismaClient
>   .$transaction(
>     async (tx) => {
>       await tx.person.createMany({data: personCreateManyInput});
>       await tx.organization.createMany({data: organizationCreateManyInput});
>       await tx.collection.createMany({data: collectionCreateManyInput});
>       const mMSource = await tx.mMSource.create({data: mMSourceInput});
>       const mMSourceId = mMSource.id;
>       const metronomeMarksInput = state.metronomeMarks
>           .filter((metronomeMark) => !metronomeMark.noMM)
>           .map((metronomeMark) => getMetronomeMarkDBInputFromState(metronomeMark, mMSourceId));
>       const metronomeMarks = await tx.metronomeMark.createMany({data: metronomeMarksInput});
> 
>       return { mMSourceInput, mMSource, metronomeMarks };
>     })
> I'm about to extend my prismaClient to create a postgreSQL context with `set_audit_context(<userId>, <reviewId>)` and use this variable in triggers.
> 
> [@marklai1998](https://github.com/marklai1998) When you write:
> 
> > There is an "issue" with my example that you cannot use regular client inside a tx.
> 
> Is that not what your fix propose to fix in the first place? That means it will not fit with my code I suppose.
> 
> And [@baoshan](https://github.com/baoshan) , I have to work on your solution, I don't understand all what your code is doing. But can you provide a short example of how to use it please ?

What I mean is
```ts
prisma.myModal.tx((tx)=>{
  tx.anotherModal.create() // normal way
  prisma.anotherModal.create() // this used to be possible, but with our fix, this would throw an error instead
})
```

**Comment by JulienLemaitre** [comment]
@marklai1998 thanks for the clarification!

**Comment by baoshan** [comment]
@JulienLemaitre This `wrap` extension I shared above can be used to inject any GUC context (for RLS, auditing, default values, etc.), e.g.:

```ts
/** Prisma extension wrapping `before` & `after` SQLs to all operations. */
export const wrap = (getSQLs: getSQLs) =>
  Prisma.defineExtension((client) => {
    return client.$extends({
      query: {
        $allOperations: async ({ args, model, query, operation, ...rest }) => {
          const { before = [], after = [] } = getSQLs(args, model, operation)
          if (!before.length) return await query(args)
          const { transaction } = (rest as any)['__internalParams']
          if (transaction) {
            // https://github.com/prisma/prisma/discussions/25034
            if (transaction.kind !== 'itx') return await query(args) // batch
            const itxClient = (client as any)._createItxClient(transaction)
            for (const sql of before) await itxClient.$executeRawUnsafe(sql)
            const result = await query(args)
            for (const sql of after) await itxClient.$executeRawUnsafe(sql)
            return result
          }
          const er = (sql: string) => client.$executeRawUnsafe(sql)
          return await client
            .$transaction([...before.map(er), query(args), ...after.map(er)])
            .then((results) => results[before.length])
        },
      },
    })
  }) as <T>(t: T) => T

const extendedPrisma = prisma.$extend(wrap(() => ({ 
  before: ["PERFORM set_config('app.user_id', 'alice', TRUE)"]
})))
```
