### ISSUE TITLE
Incorrect OpenSSL version detected in WSL 2 (Ubuntu)

### ISSUE THREAD

**Issue by jporsay** [prisma/prisma#20682]
### Bug description

When I execute `openssl version` I get `OpenSSL 3.0.9 30 May 2023 (Library: OpenSSL 3.0.9 30 May 2023)`.

However when I execute `npx prisma --version` I get:

```
Error: Unable to require(`/home/jeipiou/code/qbic/pulpos/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`).
Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.

Details: libssl.so.1.1: cannot open shared object file: No such file or directory
    at loadLibrary (/home/jeipiou/code/qbic/pulpos/node_modules/prisma/build/index.js:85527:11)
    at getEngineVersion (/home/jeipiou/code/qbic/pulpos/node_modules/prisma/build/index.js:85540:16)
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +8ms
prisma                  : 5.1.1
@prisma/client          : 5.1.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.1.1-1.6a3747c37ff169c90047725a05a6ef02e32ac97e
Default Engines Hash    : 6a3747c37ff169c90047725a05a6ef02e32ac97e
Studio                  : 0.492.0
Preview Features        : fullTextSearch, jsonProtocol, orderByNulls
  prisma:getConfig  Using getConfig Wasm +3ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +5ms
```

Which ends up generating problems when executing the application since Prisma cannot find the `.so` for OpenSSL 1.1.

### How to reproduce

1. Create a `wsl` instance of Ubuntu
2. Create a project that uses the latest Prisma version
3. Confirm that the reported OpenSSL version is the one expected (3).
4. Execute `npx prisma --version`

### Expected behavior

OpenSSL 3 engine is being used since it is the one available.

### Prisma information

N/A since this isn't a problem with queries or the schema.

### Environment & setup

- OS: Windows (WSL 2, Ubuntu)
- Database: PostgreSQL
- Node.js version: v18.16.1

### Prisma Version

```
Error: Unable to require(`/home/jeipiou/code/qbic/pulpos/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`).
Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.

Details: libssl.so.1.1: cannot open shared object file: No such file or directory
    at loadLibrary (/home/jeipiou/code/qbic/pulpos/node_modules/prisma/build/index.js:85527:11)
    at getEngineVersion (/home/jeipiou/code/qbic/pulpos/node_modules/prisma/build/index.js:85540:16)
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +8ms
prisma                  : 5.1.1
@prisma/client          : 5.1.1
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.1.1-1.6a3747c37ff169c90047725a05a6ef02e32ac97e
Default Engines Hash    : 6a3747c37ff169c90047725a05a6ef02e32ac97e
Studio                  : 0.492.0
Preview Features        : fullTextSearch, jsonProtocol, orderByNulls
  prisma:getConfig  Using getConfig Wasm +3ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +5ms
```

**Comment by jporsay** [comment]
I have not set anything neither in the Prisma schema nor in any environment variable

**Comment by jkomyno** [comment]
Hey @jporsay, could you please run `DEBUG="prisma:get-platform" npx prisma version`, and paste the output in here? Thanks.

**Comment by jporsay** [comment]
Sure! Here you go:

```
$ export DEBUG="prisma*"
$ npx prisma --version
  prisma:engines  binaries to download libquery-engine, migration-engine +0ms
  prisma:get-platform  Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
} +0ms
  prisma:get-platform  Trying platform-specific paths for "debian" (and "ubuntu") +0ms
  prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.1.1 +1ms
  prisma:get-platform  The parsed libssl version is: 1.1.x +0ms
  prisma:get-platform  Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
} +1ms
  prisma:get-platform  Trying platform-specific paths for "debian" (and "ubuntu") +0ms
  prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.1.1 +0ms
  prisma:get-platform  The parsed libssl version is: 1.1.x +0ms
Environment variables loaded from .env
  prisma:get-platform  Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
} +0ms
  prisma:get-platform  Trying platform-specific paths for "debian" (and "ubuntu") +0ms
  prisma:get-platform  Found libssl.so file using platform-specific paths: libssl.so.1.1 +1ms
  prisma:get-platform  The parsed libssl version is: 1.1.x +0ms
Error: Unable to require(`/home/[...]/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node`).
Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.

Details: libssl.so.1.1: cannot open shared object file: No such file or directory
    at loadLibrary (/home/[...]/node_modules/prisma/build/index.js:97408:11)
    at getEngineVersion (/home/[...]/node_modules/prisma/build/index.js:97422:16)
Error: Could not find migration-engine binary. Searched in:
- /home/[...]/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x
- /home/[...]/node_modules/prisma/migration-engine-debian-openssl-1.1.x
- /home/[...]/node_modules/migration-engine-debian-openssl-1.1.x
- /home/[...]/node_modules/prisma/runtime/migration-engine-debian-openssl-1.1.x
    at resolveBinary (/home/[...]/node_modules/prisma/build/index.js:97363:9)
Error: Could not find migration-engine binary. Searched in:
- /home/[...]/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x
- /home/[...]/node_modules/prisma/migration-engine-debian-openssl-1.1.x
- /home/[...]/node_modules/migration-engine-debian-openssl-1.1.x
- /home/[...]/node_modules/prisma/runtime/migration-engine-debian-openssl-1.1.x
    at resolveBinary (/home/[...]/node_modules/prisma/build/index.js:97363:9)
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +7ms
prisma                  : 4.13.0
@prisma/client          : 4.13.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : E_CANNOT_RESOLVE_VERSION (at E_CANNOT_RESOLVE_PATH)
Format Wasm             : @prisma/prisma-fmt-wasm 4.13.0-50.1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Default Engines Hash    : 1e7af066ee9cb95cf3a403c78d9aab3e6b04f37a
Studio                  : 0.484.0
Preview Features        : fullTextSearch, orderByNulls, jsonProtocol
  prisma:getConfig  Using getConfig Wasm +2ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +5ms
```

**Comment by Jolg42** [comment]
I'm a bit confused how this shows the Prisma version as`4.13.0` but in the issue description it was `5.1.1` 🤔 
Can you try the same command with `5.1.1`?

**Comment by jporsay** [comment]
My bad, I had tried to upgrade Prisma's version and reverted that change after I saw that it wasn't fixed, reason for why the log is displaying that version. However I did a clean installation of my development box (WSL: Ubuntu) and the problem does not seem to happen anymore. Closing this ticket since the version is correctly detected now:

```
$ npx prisma --version
prisma                  : 5.1.1
@prisma/client          : 5.1.1
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 6a3747c37ff169c90047725a05a6ef02e32ac97e (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.1.1-1.6a3747c37ff169c90047725a05a6ef02e32ac97e
Default Engines Hash    : 6a3747c37ff169c90047725a05a6ef02e32ac97e
Studio                  : 0.492.0
Preview Features        : fullTextSearch, jsonProtocol, orderByNulls
```

Seems I might have had some leftover libssl version somewhere.

Thanks for the help!

**Comment by jkomyno** [comment]
Glad that this was so quickly solved! Have a nice day, @jporsay 😄

**Comment by jporsay** [comment]
That is correct! I didn't have much to loose so that's what I did and it
fixed it.
