### ISSUE TITLE
`Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.`

### ISSUE THREAD

**Issue by LogicNovaX** [prisma/prisma#20686]
### Bug description
```
[ERROR] (PRISMA) $queryRaw 
Invalid `prisma.$queryRaw()` invocation:


Unable to require(`/home/runner/bot/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node`).
Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.

Details: libssl.so.1.1: cannot open shared object file: No such file or directory
 14/08/23 14:23:35  [NOTICE] Discord Tickets v4.0.8 on Node.js v18.12.1 (linux)
 14/08/23 14:23:35  [WARN] Unhandled promise rejection (PrismaClientInitializationError)
 14/08/23 14:23:35  [ERROR] PrismaClientInitializationError: 
Invalid `prisma.$queryRaw()` invocation:


Unable to require(`/home/runner/bot/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node`).
Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.

Details: libssl.so.1.1: cannot open shared object file: No such file or directory
    at Rn.handleRequestError (/home/runner/bot/node_modules/@prisma/client/runtime/library.js:174:7601)
    at Rn.handleAndLogRequestError (/home/runner/bot/node_modules/@prisma/client/runtime/library.js:174:6754)
    at /home/runner/bot/node_modules/@prisma/client/runtime/library.js:177:3010
    at async /home/runner/bot/node_modules/@prisma/client/runtime/library.js:177:3225
    at async Proxy._executeRequest (/home/runner/bot/node_modules/@prisma/client/runtime/library.js:177:11403)
    at async module.exports (/home/runner/bot/src/lib/middleware/prisma-sqlite.js:44:15)
    at async Client.login (/home/runner/bot/src/client.js:77:19) {
  clientVersion: '4.16.2',
  errorCode: undefined
}
```

### Expected behavior

it should of worked but it didn't can anyone help 

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by Jolg42** [comment]
@LogicNovaX It looks like you did not fill in the issue template, could you add the missing info?

**Comment by Jolg42** [comment]
@LogicNovaX Did you my previous message? Without any activity on this issue, we would later close it as part of our issue process.

**Comment by millsp** [comment]
Hey @, without your input we cannot move this issue forward, so I am closing it. Please provide us with the missing information so we understand how to treat this, and we will happily re-open it.

**Comment by NielsCodes** [comment]
I also ran into this issue when building my Dockerfile. Problem was that I was using `node:21-slim` as the base image, which does not contain libssl. 

I fixed it by using the `node:21` as my base image instead of `node:21-slim`

**Comment by deowansajal** [comment]
I'm using the following base image and encountered the same issue:
`FROM node:20.18.0-bookworm-slim`

The solution that worked for me was adding this line to install OpenSSL:
`RUN apt-get update -y && apt-get install -y openssl`

**Comment by matewka** [comment]
I have exactly the same issue.
I tried every solution proposed in this thread. None worked for me.

I also use prisma in another project with a similar setup but the version is different - `5.10.2` and everything works fine there. Surprisingly, it uses `debian-openssl-3.0.x` binary despite lower versions of prisma and node. I tried to downgrade prisma to 5.22.0 or node to 18 but it didn't help.

Here are some of my files. Maybe someone can take a look and be able to help.
_It's a monorepo, hence jumping between folders._

### Dockerfile
```
# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=20.18.0
FROM node:${NODE_VERSION}-slim AS base

LABEL fly_launch_runtime="Remix"

# Remix app lives here
WORKDIR /omega

# Set production environment
ENV NODE_ENV="production"
ARG YARN_VERSION=1.22.18
RUN npm install -g yarn@$YARN_VERSION --force


# Throw-away build stage to reduce size of final image
FROM base AS build

# Install libssl for prisma
RUN apt-get update -y && apt-get install -y openssl libssl3

# Install node modules
COPY package.json yarn.lock ./
# Copy application code
COPY apps/celpal ./apps/celpal
RUN yarn install --frozen-lockfile --production=false
RUN yarn workspace celpal db:generate

WORKDIR /omega/apps/celpal

# Build application
RUN yarn run build

# Remove development dependencies
RUN yarn install --production=true

# Final stage for app image
FROM base

# Copy built application
COPY --from=build /omega/apps/celpal /omega/apps/celpal
COPY --from=build /omega/node_modules /omega/node_modules

WORKDIR /omega/apps/celpal

# Save DB cert as file
RUN touch app/prisma/cert.pem
RUN echo "$DB_CERT" > app/prisma/cert.pem

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD [ "yarn", "start" ]
```

### Top part of schema.prisma (I believe the whole schema is not necessary in this case)
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### package.json
```
{
  "name": "celpal",
  "version": "1.0.0",
  "license": "UNLICENSED",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "cross-env NODE_ENV=production react-router build",
    "dev": "react-router dev",
    "start": "NODE_ENV=production react-router-serve ./build/server/index.js",
    "typecheck": "react-router typegen && tsc",
    "db:format": "prisma format",
    "db:generate": "prisma generate",
    "db:migrate": "prisma migrate dev --create-only",
    "db:start": "./prisma/scripts/startup.sh",
    "db:clean": "./prisma/scripts/cleanup.sh",
    "db:seed": "tsx prisma/seed.ts",
    "e2e:seed": "tsx e2e/scripts/seed.ts"
  },
  "prisma": {
    "seed": "yarn db:seed"
  },
  "dependencies": {
    "@prisma/client": "6.1.0",
    "@react-router/node": "^7.0.2",
    "@react-router/serve": "^7.0.2",
    "bcrypt": "^5.1.1",
    "isbot": "^5.1.17",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-router": "^7.0.2"
  },
  "devDependencies": {
    "@flydotio/dockerfile": "^0.7.0",
    "@react-router/dev": "^7.0.2",
    "@react-router/fs-routes": "^7.0.2",
    "@types/bcrypt": "^5.0.2",
    "@types/node": "^20",
    "@types/react": "^19.0.1",
    "@types/react-dom": "^19.0.1",
    "autoprefixer": "^10.4.20",
    "cross-env": "^7.0.3",
    "postcss": "^8.4.49",
    "prisma": "^6.1.0",
    "tailwindcss": "^3.4.16",
    "tsx": "^4.19.2",
    "typescript": "^5.7.2",
    "vite": "^5.4.11",
    "vite-tsconfig-paths": "^5.1.4"
  }
}
```

**Comment by matewka** [comment]
What worked for me, was to switch to `alpine` image:

```
FROM node:20.18.0-alpine
```

**No additional installs needed.**

**Comment by pedroinbezerra** [comment]
> What worked for me, was to switch to `alpine` image:
> 
> ```
> FROM node:20.18.0-alpine
> ```
> 
> **No additional installs needed.**

Works fine. Thanks.
