### ISSUE TITLE
__dirname is not defined in ES module scope Error Only In hooks.server.ts in SvelteKit

### ISSUE THREAD

**Issue by Torbet** [prisma/prisma#20702]
### Bug description

I'm getting a ReferenceError: __dirname is not defined in ES module scope when building a barebones Prisma + Sveltekit app to node, preventing deployment - narrowed it down to importing prisma in hooks.server.ts, builds and runs fine when I remove the import!

full error:
      `;console.warn(`${ye("warn(prisma)")} ${u}`);}}}}function so(e){return zl(e)?(bn(`Environment variables loaded from ${e}`),{dotenvResult:oo(wn.default.config({path:e,debug:process.env.DOTENV_CONFIG_DEBUG?!0:void 0})),message:Oe(`Environment variables loaded from ${it.default.relative(process.cwd(),e)}`),path:e}):(bn(`Environment variables not found at ${e}`),null)}function ao(e,t){return e&&t&&it.default.resolve(e)===it.default.resolve(t)}function zl(e){return Boolean(e&&pr.default.existsSync(e))}var lo="library";function Pn(e){let t=Yl();return t||(e?.config.engineType==="library"?"library":e?.config.engineType==="binary"?"binary":lo)}function Yl(){let e=process.env.PRISMA_CLIENT_ENGINE_TYPE;return e==="library"?"library":e==="binary"?"binary":void 0}A(En());var k=A(require$$4);A(En());N("prisma:engines");function go(){return k.default.join(__dirname,"../")}k.default.join(__dirname,"../query-engine-darwin");k.default.join(__dirname,"../query-engine-darwin-arm64");k.default.join(__dirname,"../query-engine-debian-openssl-1.0.x");k.default.join(__dirname,"../query-engine-debian-openssl-1.1.x");k.default.join(__dirname,"../query-engine-debian-openssl-3.0.x");k.default.join(__dirname,"../query-engine-linux-static-x64");k.default.join(__dirname,"../query-engine-linux-static-arm64");k.default.join(__dirname,"../query-engine-rhel-openssl-1.0.x");k.default.join(__dirname,"../query-engine-rhel-openssl-1.1.x");k.default.join(__dirname,"../query-engine-rhel-openssl-3.0.x");k.default.join(__dirname,"../libquery_engine-darwin.dylib.node");k.default.join(__dirname,"../libquery_engine-darwin-arm64.dylib.node");k.default.join(__dirname,"../libquery_engine-debian-openssl-1.0.x.so.node");k.default.join(__dirname,"../libquery_engine-debian-openssl-1.1.x.so.node");k.default.join(__dirname,"../libquery_engine-debian-openssl-3.0.x.so.node");k.default.join(__dirname,"../libquery_engine-linux-arm64-openssl-1.0.x.so.node");k.default.join(__dirname,"../libquery_engine-linux-arm64-openssl-1.1.x.so.node");k.default.join(__dirname,"../libquery_engine-linux-arm64-openssl-3.0.x.so.node");k.default.join(__dirname,"../libquery_engine-linux-musl.so.node");k.default.join(__dirname,"../libquery_engine-linux-musl-openssl-3.0.x.so.node");k.default.join(__dirname,"../libquery_engine-rhel-openssl-1.0.x.so.node");k.default.join(__dirname,"../libquery_engine-rhel-openssl-1.1.x.so.node");k.default.join(__dirname,"../libquery_engine-rhel-openssl-3.0.x.so.node");k.default.join(__dirname,"../query_engine-windows.dll.node");var Tn=A(require$$3),yo=N("chmodPlusX");function vn(e){if(process.platform==="win32")return;let t=Tn.default.statSync(e),r=t.mode|64|8|1;if(t.mode===r){yo(`Execution permissions of ${e} are fine`);return}let n=r.toString(8).slice(-3);yo(`Have to call chmodPlusX on ${e}`),Tn.default.chmodSync(e,n);}function Cn(e){let t=e.e,r=a=>`Prisma cannot find the required \`${a}\` system library in your system`,n=t.message.includes("cannot open shared object file"),i=`Please refer to the documentation about Prisma's system requirements: ${Tt("https://pris.ly/d/system-requirements")}`,o=`Unable to require(\`${Oe(e.id)}\`).`,s=et({message:t.message,code:t.code}).with({code:"ENOENT"},()=>"File does not exist.").when(({message:a})=>n&&a.includes("libz"),()=>`${r("libz")}. Please install it and try again.`).when(({message:a})=>n&&a.includes("libgcc_s"),()=>`${r("libgcc_s")}. Please install it and try again.`).when(({message:a})=>n&&a.includes("libssl"),()=>{let a=e.platformInfo.libssl?`openssl-${e.platformInfo.libssl}`:"openssl";return `${r("libssl")}. Please install ${a} and try again.`}).when(({message:a})=>a.includes("GLIBC"),()=>`Prisma has detected an incompatible version of the \`glibc\` C standard library installed in your system. This probably means your system may be too old to run Prisma. ${i}`).when(({message:a})=>e.platformInfo.platform==="linux"&&a.includes("symbol not found"),()=>`The Prisma engines are not compatible with your system ${e.platformInfo.originalDistro} on (${e.platformInfo.archFromUname}) which uses the \`${e.platformInfo.binaryTarget}\` binaryTarget by default. ${i}`).otherwise(()=>`The Prisma engines do not seem to be compatible with your system. ${i}`);return `${o}

### How to reproduce

I'm running a minimal example, fairly easy to repro

### Prisma information

model User {
  id           String    @id @unique

  auth_session Session[]
  key          Key[]
}

model Session {
  id             String @id @unique
  user_id        String
  active_expires BigInt
  idle_expires   BigInt
  user           User   @relation(references: [id], fields: [user_id], onDelete: Cascade)

  @@index([user_id])
}

model Key {
  id              String  @id @unique
  hashed_password String?
  user_id         String
  user            User    @relation(references: [id], fields: [user_id], onDelete: Cascade)

  @@index([user_id])
}

### Environment & setup

- OS:Macos
- Database: Neon
- Node.js version:18

### Prisma Version

```
5.0.0
```

**Comment by Torbet** [comment]
@SevInf After using [create-svelte-app](https://kit.svelte.dev/docs/creating-a-project):


/src/lib/server/db.ts:
```
import { PrismaClient } from '@prisma/client';
export default new PrismaClient();
```

/src/hooks.server.ts:
```
import type { Handle } from "@sveltejs/kit";
import db from '$lib/server/db'

export const handle: Handle = async ({ event, resolve }) => {
	return await resolve(event);
};
```

If I remove the import from `hooks.server.ts`, everything works, I can even add it to page server paths and it works - but this is a breaking issue for all sveltekit users! Confirming it works as expected on prisma versions <= 4.16.0.

**Comment by maietta** [comment]
Common, people. STOP USING __dirname in your code. It's time to a take a look at Drizzle ORM and dump Prisma Client. As a SvelteKit user, this issue has crept up now 3 times through Prisma changes. I have to reverse code to older version to get this to work.

**Comment by EssaAlshammri** [comment]
have you found a solution for this?

**Comment by EssaAlshammri** [comment]
to be precise my prisma.ts file looks like this:

```typescript
import { PrismaClient } from '@prisma/client';
import { env } from '$env/dynamic/private';

const prismaClient = global.__prisma || new PrismaClient();

if (env.NODE_ENV === 'development') {
	global.__prisma = prismaClient;
}

export default prismaClient;
```

and on app.d.ts
```typescript
import type { PrismaClient } from '@prisma/client';

// for information about these interfaces
declare global {
	namespace App {
		// interface Error {}
		// interface PageData {}
		// interface Platform {}
	}
	// eslint-disable-next-line no-var
	var __prisma: PrismaClient;
}
```

**Comment by devidw** [comment]
Issue is that prisma is a cjs pkg, not esm, but the app runs as esm, so it will fail

What you can do is externalize the dependency

1. Build prisma client as package in monorepo
2. Add prisma client cjs package as (runtime) dependency not devDependency to sveltekit project package.json
3. Mark as external in vite.config.ts: `ssr.external`

**Comment by Razorback360** [comment]
This is still very much an issue as of: 

prisma 5.11.0
sveltejs/kit 2.0.0

Any further updates?

**Comment by pitzzahh** [comment]
Just got the same error when running with node build.
```js 
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/peter/hrms/build/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at requireLibrary (file:///home/peter/hrms/build/server/chunks/prisma-BfL2Hg9l.js:43:908)
    at file:///home/peter/hrms/build/server/chunks/prisma-BfL2Hg9l.js:199:7
    at requireClient (file:///home/peter/hrms/build/server/chunks/prisma-BfL2Hg9l.js:591:4)
    at require_default$1 (file:///home/peter/hrms/build/server/chunks/prisma-BfL2Hg9l.js:601:20)
    at require_default (file:///home/peter/hrms/build/server/chunks/prisma-BfL2Hg9l.js:612:7)
    at file:///home/peter/hrms/build/server/chunks/prisma-BfL2Hg9l.js:617:23
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async get_hooks (file:///home/peter/hrms/build/server/index.js:246:8)
    at async Server.init (file:///home/peter/hrms/build/server/index.js:3826:24)
```

cmd: ``node -r dotenv/config build``
prisma version: ``5.13.0``

**Comment by mgloc** [comment]
Same error with node build, only when hooks.server.ts is there and using PrismaClient somewhere (in my case with Lucia Auth)

`ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/sample-user/code/my-app/apps/userapp/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at requireLibrary (file:///home/sample-user/code/my-app/apps/userapp/build/server/chunks/default-BtqcaNrT.js:38:908)
    at file:///home/sample-user/code/my-app/apps/userapp/build/server/chunks/default-BtqcaNrT.js:194:7
    at requireClient (file:///home/sample-user/code/my-app/apps/userapp/build/server/chunks/default-BtqcaNrT.js:435:4)
    at require_default$1 (file:///home/sample-user/code/my-app/apps/userapp/build/server/chunks/default-BtqcaNrT.js:445:20)
    at require_default (file:///home/sample-user/code/my-app/apps/userapp/build/server/chunks/default-BtqcaNrT.js:456:7)
    at file:///home/sample-user/code/my-app/apps/userapp/build/server/chunks/default-BtqcaNrT.js:461:23
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async get_hooks (file:///home/sample-user/code/my-app/apps/userapp/build/server/index.js:239:8)
    at async Server.init (file:///home/sample-user/code/my-app/apps/userapp/build/server/index.js:3894:24)

Node.js v20.12.2`

Using Prisma 5.13.0 with TS bundled in a Turborepo package called "database", imported as a dependency.

**Comment by YpsilonTM** [comment]
I also have this problem and it is a pain. I haven't found a fix. I am working with Lucia, so it is not a direct import into the hook. But now I am really stuck on my project. I might have to switch to Drizzle unless I find a fix.

**Comment by sc32024826** [comment]
遇到了一样的问题, 经过百般尝试, 发现 只要把output的目录 放在node_modules中 就没有问题
```
generator client {
  provider        = "prisma-client-js"
  output          = "../../node_modules/@prisma-server/client"
  previewFeatures = ["prismaSchemaFolder"]
  binaryTargets   = ["native", "linux-musl-openssl-3.0.x"]
}
```
import { PrismaClient as PrismaClient1 } from '@prisma-server/client'
import { PrismaClient as PrismaClient2 } from '@prisma-system/client'

// 业务库
const server = new PrismaClient1({
    log: [{
        emit: 'event',
        level: 'query',
    }],
})
// 系统库
const system = new PrismaClient2({
    log: [{
        emit: 'event',
        level: 'query',
    }],
})
export { server, system };
```
 我本来是直接生成到 prisma/generated目录下的  开发环境不会报错 但是生产环境 就报错

**Comment by martinejaw** [comment]
In case someone finds it useful, this is the trick I've been using for a while
Source: https://github.com/liloryan/iru_belongings/commit/3044d732133df397e324eaef19b8905b31a6f442

Just define a single prisma instance in the project and use it everywhere:
import type { PrismaClient as Prisma } from '@prisma/client';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { PrismaClient } = require('@prisma/client');
const prisma: Prisma = new PrismaClient();
export default prisma;

**Comment by malun22** [comment]
I run into the same problem importing prisma to catch the PrismaClientKnownRequestError. I couldnt figure out a way for a workaround for that.

**Comment by Mateleo** [comment]
Same issue for Nuxt

**Comment by manuel-84** [comment]
> ~Same issue for Nuxt~
> 
> Ok, I've found a solution for the "__dirname is not defined in ES module scope" error.
> 
> The issue arises when using ES modules (ESM) in the generated Prisma Client. The `__dirname` variable is not automatically available in ESM.
> 
> **Solution:**
> 
> Explicitly set `moduleFormat = "esm"` in the generator block of your `schema.prisma` file. This ensures that the Prisma Client is generated with the correct module format and uses `import.meta.url` instead of `__dirname` for resolving file paths.
> 
> generator client {
>   provider = "prisma-client"
>   output   = "../src/generated/prisma"
>   moduleFormat = "esm" // Explicitly set module format to ESM
> }
> ref : https://www.prisma.io/docs/orm/prisma-schema/overview/generators#field-reference-1

not working for me in nuxt

**Comment by JoeskiG** [comment]
I managed to fix this issue with one of my projects by replacing all occurrences of `__dirname` with `import.meta.url` from all files in the build directory. I made a short script to automatically do this after each build too so it's faster. Maybe you could try doing that?

**Comment by benpoulson** [comment]
@Mateleo  is correct with their solution. 

@manuel-84  @JoeskiG  - Make sure you've changed your provider from `prisma-client-js` to `prisma-client`, or the solution will not work.

This is my generator block. Note - I work exclusively in typescript, but you can swap out configs where you see fit.

```
generator client {
  provider               = "prisma-client"
  output                 = "../src/generated/prisma"
  runtime                = "nodejs"
  moduleFormat           = "esm"
  generatedFileExtension = "ts"
  importFileExtension    = "ts" 
}
```

**Comment by JoeskiG** [comment]
> @Mateleo  is correct with their solution. 
> 
> @manuel-84  @JoeskiG  - Make sure you've changed your provider from `prisma-client-js` to `prisma-client`, or the solution will not work.
> 
> This is my generator block. Note - I work exclusively in typescript, but you can swap out configs where you see fit.
> 
> ```
> generator client {
>   provider               = "prisma-client"
>   output                 = "../src/generated/prisma"
>   runtime                = "nodejs"
>   moduleFormat           = "esm"
>   generatedFileExtension = "ts"
>   importFileExtension    = "ts" 
> }
> ```
> 
> 

Thanks. I had tried this and it made no difference for me. I saw this in documentation too. Not sure why doing that didn't work.I am on 6.6.0

**Comment by viktorholk** [comment]
@benpoulson Thank you. this solved my issue

**Comment by manuel-84** [comment]
> [@Mateleo](https://github.com/Mateleo) is correct with their solution.
> 
> [@manuel-84](https://github.com/manuel-84) [@JoeskiG](https://github.com/JoeskiG) - Make sure you've changed your provider from `prisma-client-js` to `prisma-client`, or the solution will not work.
> 
> This is my generator block. Note - I work exclusively in typescript, but you can swap out configs where you see fit.
> 
> ```
> generator client {
>   provider               = "prisma-client"
>   output                 = "../src/generated/prisma"
>   runtime                = "nodejs"
>   moduleFormat           = "esm"
>   generatedFileExtension = "ts"
>   importFileExtension    = "ts" 
> }
> ```

tried adding runtime and fileextensions to my config, result is this build error:


```
[ nuxi  09:47:41]  ERROR  Nuxt Build Error: node_modules/@prisma/client/runtime/library.mjs (595:9): "promisify" is not exported by "__vite-browser-external", imported by "node_modules/@prisma/client/runtime/library.mjs".
file: C:/.............../node_modules/@prisma/client/runtime/library.mjs:595:9
```

and it haven't fixed the console warning for `__dirname is not defined` when importing from generated client

**Comment by wsw70** [comment]
@benpoulson solution pushed, I believe, the problem to another place, with now having

```
TypeError: __banner_node_url.fileURLToPath is not a function
```

When looking at the generated code where this happens, it is suspiciously close to `__dirname`:

```
var __filename = __banner_node_url.fileURLToPath(import.meta.url);
var __dirname = __banner_node_path.dirname(__filename);
```

Also see https://github.com/prisma/prisma/issues/26897

**Comment by arshx86** [comment]
> [@Mateleo](https://github.com/Mateleo) is correct with their solution.
> 
> [@manuel-84](https://github.com/manuel-84) [@JoeskiG](https://github.com/JoeskiG) - Make sure you've changed your provider from `prisma-client-js` to `prisma-client`, or the solution will not work.
> 
> This is my generator block. Note - I work exclusively in typescript, but you can swap out configs where you see fit.
> 
> ```
> generator client {
>   provider               = "prisma-client"
>   output                 = "../src/generated/prisma"
>   runtime                = "nodejs"
>   moduleFormat           = "esm"
>   generatedFileExtension = "ts"
>   importFileExtension    = "ts" 
> }
> ```

Thanks, worked for nuxt!
I had to change 'output' only.

```prisma
generator client {
  provider               = "prisma-client"
  output                 = "../generated/prisma"
  runtime                = "nodejs"
  moduleFormat           = "esm"
  generatedFileExtension = "ts"
  importFileExtension    = "ts"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

**Comment by youssef1129** [comment]
> import { createRequire } from 'module';
> const require = createRequire(import.meta.url);
> const { PrismaClient } = require('@prisma/client');
> const prisma: Prisma = new PrismaClient();
> export default prisma;

works
