### ISSUE TITLE
Failing to locate libssl.so.1.1 on Gentoo

### ISSUE THREAD

**Issue by Sommmmy** [prisma/prisma#20822]
### Bug description

The following output occurs upon invoking `prisma version -v`, it shows that it is finding `libssl.so.1.1` via ldconfig yet seemingly loses it right after:

> $ [project]/node_modules/.bin/prisma version -v
> prisma:warn Prisma doesn't know which engines to download for the Linux distro "gentoo". Falling back to Prisma engines built "debian".
> Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
> prisma:warn Prisma doesn't know which engines to download for the Linux distro "gentoo". Falling back to Prisma engines built "debian".
> Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
> Error: Unable to require(`[project]/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`).
> Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.
> 
> Details: libssl.so.1.1: cannot open shared object file: No such file or directory
>     at loadLibrary ([project]/node_modules/prisma/build/index.js:107672:11)
>     at getEngineVersion2 ([project]/node_modules/prisma/build/index.js:107685:16)
> prisma                  : 5.2.0
> @prisma/client          : Not found
> Current platform        : debian-openssl-1.1.x
> Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
> Schema Engine           : schema-engine-cli 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
> Schema Wasm             : @prisma/prisma-schema-wasm 5.2.0-25.2804dc98259d2ea960602aca6b8e7fdc03c1758f
> Default Engines Hash    : 2804dc98259d2ea960602aca6b8e7fdc03c1758f
> Studio                  : 0.494.0

the library indeed exists: 
![image](https://github.com/prisma/prisma/assets/59640424/df750334-e2f6-4f0a-bf1a-234a19e00858)

prisma version:
`latest, 5.2.0`

openssl version:
`dev-libs/openssl-1.1.1t-r1`

### How to reproduce

1. Install `dev-libs/openssl-1.1.1t-r1`
2. Make a project and add prisma (`yarn add prisma`)
3. Run `yarn prisma version -v` (or `yarn prisma generate`)
4. See error trying to use `/usr/lib64/libssl.so.1.1` library

### Expected behavior

For it to be able to use libssl.so.1.1

### Prisma information

problem doesn't seem to be related to a particular project

### Environment & setup

- OS: Gentoo
- Database: PostgreSQL
- Node.js version: 19.5.0
- Node package manager: Yarn 3.4.1

### Prisma Version

```
5.2.0
```

**Comment by bazuka5801** [comment]
Also having this issue

**Comment by Sommmmy** [comment]
Issue was resolved by emerging openssl 3.0, although I'm not sure if i should close it as the error message is quite deceiving (1.1.x doesn't work)

**Comment by jkomyno** [comment]
Hey @Sommmmy, could you please run `DEBUG="prisma:get-platform" npx prisma -v` and report back the whole output you get? Thanks.

**Comment by aqrln** [comment]
@Sommmmy thanks for the logs, could you please also post the output of `ldconfig -p | grep libssl` on your system? Thank you!

**Comment by Sommmmy** [comment]
@aqrln On openssl 3 system:
        libssl3.so (libc6,x86-64) => /usr/lib64/libssl3.so
	libssl.so.3 (libc6,x86-64) => /usr/lib64/libssl.so.3
	libssl.so (libc6,x86-64) => /usr/lib64/libssl.so
I don't have the old environment anymore, but it was libssl.so.1.1 instead of libssl.so.3, essentially something like this:
       libssl3.so => /usr/lib64/libssl3.so
       libssl.so => /usr/lib64/libssl.so
       libssl.so.1.1 => /usr/lib64/libssl.so.1.1
which is also proven by the logs sent previously.

Also for anyone who might face this problem in future, just installing openssl 3 was not enough, I also needed to make sure there is no more so.1.1 in my system and nothing depends on it (or it will get auto-preserved by gentoo), as it was detected as the openssl version even with v3 being the installed version.

**Comment by markbugatti** [comment]
@Sommmmy looks similar to issue #20686. But here is more advanced fixes that helped me

1. Add binary targets to schema.prisma file:
`generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-3.0.x"]
}`
2.  install openssl on image. I used debian (find how install this package to Gentoo), so the command was next:
`apt update && apt install openssl`
3. Regenerate prisma stuff:
`npx prisma generate`

I applied these changes my docker file and it helped:
`
...
RUN apt update
RUN apt install openssl -y
...
RUN npx prisma generate
...`

**Comment by henil0604** [comment]
I had similar issue when using `node:20-slim` as base image in Dockerfile. Previously i was using `node:20-alpine` and there was no issue. I think the slim version does not include `openssl` by default.

**Comment by navicstein** [comment]
also having this issue
