### ISSUE TITLE
Syntax error with delete

### ISSUE THREAD

**Issue by kokokenada** [prisma/prisma#2085]
## Bug description

Calling delete causes a syntax error

## How to reproduce
````
await ctx.prisma.user.delete({
        where: { email_brandId: { email: uniqueEmail, brandId: 'habitat' } },
      });

````

## Prisma information

````
model User {
  id       String  @default(cuid()) @id
  createdAt  DateTime    @default(now())
  updatedAt  DateTime @updatedAt
  email      String
  brandId    String
  firstname     String?
  lastname     String?
  phone   String?

...

  couponUse  CouponUse[]

  @@unique([email, brandId])
}

model Coupon {
  code        String @id
  createdAt   DateTime    @default(now())
  updatedAt   DateTime @updatedAt
  couponUse   CouponUse[]
}

model CouponUse {
  id          String  @default(cuid()) @id
  createdAt   DateTime    @default(now())
  updatedAt   DateTime @updatedAt
  couponCode  String
  coupon      Coupon @relation(fields: [couponCode], references: [code])
  userId      String
  user        User @relation(fields: [userId], references: [id])
}

Debug:

onsole.log src/services/UserService.db.spec.ts:244
    Deleting user user-service-email@test.com

  prisma-client Prisma Client call: +8ms
  prisma-client prisma.user.delete({
  prisma-client   where: {
  prisma-client     email_brandId: {
  prisma-client       email: 'user-service-email@test.com',
  prisma-client       brandId: 'habitat'
  prisma-client     }
  prisma-client   }
  prisma-client }) +0ms
  prisma-client Generated request: +0ms
  prisma-client mutation {
  prisma-client   deleteOneUser(where: {
  prisma-client     email_brandId: {
  prisma-client       email: "user-service-email@test.com"
  prisma-client       brandId: "habitat"
  prisma-client     }
  prisma-client   }) {
  prisma-client     id
  prisma-client     createdAt
  prisma-client     updatedAt
  prisma-client     email
  prisma-client     brandId
  prisma-client     firstname
  prisma-client     lastname
  prisma-client     phone

...

  prisma-client   }
  prisma-client }
  prisma-client  +0ms
  engine {
  engine   error: PrismaClientUnknownRequestError: Error occurred during query execution:
  engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "syntax error at or near \")\"", detail: None, hint: None, position: Some(Original(72)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("scan.l"), line: Some(1128), routine: Some("scanner_yyerror") }) }) })
  engine       at NodeEngine.graphQLToJSError (/Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/client/runtime/index.js:1:19002)
  engine       at /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/client/runtime/index.js:1:16489
  engine       at processTicksAndRejections (internal/process/task_queues.js:97:5)
  engine       at Dataloader.loader (/Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/client/runtime/index.js:1:50798)
  engine } +541ms
  printStack callsite Error
    at Object.s [as User] (/Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/client/runtime/index.js:1:48702)
    at Object.n.<computed> [as delete] (/Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/client/runtime/index.js:1:50328)
    at Object.<anonymous> (/Users/kenono/apps/habitat/packages/back-end/src/services/UserService.db.spec.ts:289:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) +0ms
  engine Stopping Prisma engine +15ms
  getos { platform: 'darwin', libssl: undefined } +3s
  engine Stopping Prisma engine +0ms
  getos { platform: 'darwin', libssl: undefined } +0ms
````
## Environment & setup

````
kens-mbp:back-end kenono$ npx prisma -v
@prisma/cli          : 2.0.0-beta.1
Current platform     : darwin
Query Engine         : prisma 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 2accb9c7eacdc984874eaeb63377fe705dfd3203 (at /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/introspection-engine-darwin)
````

**Comment by ranjan-purbey** [comment]
Can you share the generated SQL query please? You can enable query logging in terminal by passing the log option in `PrismaClient` constructor like `new PrismaClient({log: ["query"])` .

**Comment by janpio** [comment]
With the environment variable `DEBUG=*` you will hopefully get exact output what command you are running with Prisma Client. Very possible something is going wrong somewhere, that output should confirm it. (It might be quite long, but worth posting)

**Comment by ranjan-purbey** [comment]
The error is caused due to this statement in the generated query:
```
SELECT "ken-dev"."Answer"."id" FROM "ken-dev"."Answer" WHERE (1=1 AND () IN (($1))) OFFSET $2
```
I will be able to help you more if you could share the relation you have for the `Answer` model

**Comment by janpio** [comment]
I have a hunch this was today fixed in the current alpha - maybe try with that quickly to see if it will be gone with the next beta.

**Comment by kokokenada** [comment]
How do I install the current alpha?

**Comment by kokokenada** [comment]
Answer model is:
````
model Answer {
  id          String   @default(cuid()) @id
  content     String
  question    Question
  author      User
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}
````

**Comment by janpio** [comment]
> How do I install the current alpha?

`npm install --save-dev @prisma/cli@alpha`

(This will update your local dependency, then you need to regenerate the client and try again)

**Comment by kokokenada** [comment]
Same problem after installing the Alpha.  Here's the DEBUG output:
````
Ran all test suites.
  console.error node_modules/@prisma/client/runtime/index.js:1
    prisma:query BEGIN

  console.error node_modules/@prisma/client/runtime/index.js:1
    prisma:query SELECT "ken-dev"."CouponUse"."id" FROM "ken-dev"."CouponUse" WHERE "ken-dev"."CouponUse"."userId" = $1 OFFSET $2

  console.error node_modules/@prisma/client/runtime/index.js:1
    prisma:query SELECT "ken-dev"."CouponUse"."id" FROM "ken-dev"."CouponUse" WHERE "ken-dev"."CouponUse"."userId" = $1

  console.error node_modules/@prisma/client/runtime/index.js:1
    prisma:query COMMIT

  console.error node_modules/@prisma/client/runtime/index.js:1
    prisma:query BEGIN

  console.error node_modules/@prisma/client/runtime/index.js:1
    prisma:query SELECT "ken-dev"."User"."id", "ken-dev"."User"."createdAt", "ken-dev"."User"."updatedAt", "ken-dev"."User"."email", "ken-dev"."User"."brandId", "ken-dev"."User"."firstname", "ken-dev"."User"."lastname", "ken-dev"."User"."phone", "ken-dev"."User"."vhxId", "ken-dev"."User"."subscriptionChannel", "ken-dev"."User"."subscriptionExpiry", "ken-dev"."User"."shopifyId", "ken-dev"."User"."fusionAuthId", "ken-dev"."User"."stripeId" FROM "ken-dev"."User" WHERE ("ken-dev"."User"."email" = $1 AND "ken-dev"."User"."brandId" = $2) LIMIT $3 OFFSET $4

  console.error node_modules/@prisma/client/runtime/index.js:1
    prisma:query SELECT "ken-dev"."Answer"."id" FROM "ken-dev"."Answer" WHERE (1=1 AND () IN (($1))) OFFSET $2

  console.error node_modules/@prisma/client/runtime/index.js:1
    prisma:query ROLLBACK

  console.error src/services/UserService.db.spec.ts:262
    error deleting

  console.error src/services/UserService.db.spec.ts:263
    PrismaClientUnknownRequestError: 
    Invalid `prisma.user.delete()` invocation:
    
    Error occurred during query execution:
    ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "syntax error at or near \")\"", detail: None, hint: None, position: Some(Original(72)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("scan.l"), line: Some(1128), routine: Some("scanner_yyerror") }) }) })
        at PrismaClientFetcher.request (/Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/client/runtime/index.js:1:51636)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

kens-mbp:back-end kenono$ npx prisma -v
  prisma .env not loaded +0ms
  getos { platform: 'darwin', libssl: undefined } +0ms
  download {
  download   cachedFile: '/Users/kenono/.cache/prisma/master/15b42f2c499c65576f47fa77108e39d86645242b/darwin/query-engine'
  download } +0ms
  download {
  download   cachedFile: '/Users/kenono/.cache/prisma/master/15b42f2c499c65576f47fa77108e39d86645242b/darwin/migration-engine'
  download } +1ms
  download {
  download   cachedFile: '/Users/kenono/.cache/prisma/master/15b42f2c499c65576f47fa77108e39d86645242b/darwin/introspection-engine'
  download } +0ms
  download { cachedFileSize: 16631840, targetFileSize: 16631840 } +0ms
  download { cachedFileSize: 14820632, targetFileSize: 14820632 } +6ms
  download { cachedFileSize: 11217104, targetFileSize: 11217104 } +4ms
  download Getting version of /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/query-engine-darwin. Result:  {
  command: '/Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/query-engine-darwin --version',
  exitCode: 0,
  stdout: 'prisma 15b42f2c499c65576f47fa77108e39d86645242b',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
} +5ms
  download Getting version of /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/query-engine-darwin. Result:  prisma 15b42f2c499c65576f47fa77108e39d86645242b +0ms
  download { works: true } +1ms
  download { needsToBeDownloaded: false } +0ms
  download Getting version of /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/migration-engine-darwin. Result:  {
  command: '/Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/migration-engine-darwin --version',
  exitCode: 0,
  stdout: 'migration-engine-cli 15b42f2c499c65576f47fa77108e39d86645242b',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
} +5ms
  download Getting version of /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/migration-engine-darwin. Result:  migration-engine-cli 15b42f2c499c65576f47fa77108e39d86645242b +0ms
  download { works: true } +0ms
  download { needsToBeDownloaded: false } +0ms
  download Getting version of /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/introspection-engine-darwin. Result:  {
  command: '/Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/introspection-engine-darwin --version',
  exitCode: 0,
  stdout: 'introspection-core 15b42f2c499c65576f47fa77108e39d86645242b',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
} +1ms
  download Getting version of /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/introspection-engine-darwin. Result:  introspection-core 15b42f2c499c65576f47fa77108e39d86645242b +0ms
  download { works: true } +0ms
  download { needsToBeDownloaded: false } +0ms
  getos { platform: 'darwin', libssl: undefined } +26ms
  engineCommands Getting version of /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/introspection-engine-darwin +0ms
  engineCommands Getting version of /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/migration-engine-darwin +13ms
  engineCommands Getting version of /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/query-engine-darwin +15ms
@prisma/cli          : 2.0.0-alpha.1031
Current platform     : darwin
Query Engine         : prisma 15b42f2c499c65576f47fa77108e39d86645242b (at /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 15b42f2c499c65576f47fa77108e39d86645242b (at /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 15b42f2c499c65576f47fa77108e39d86645242b (at /Users/kenono/apps/habitat/packages/back-end/node_modules/@prisma/cli/introspection-engine-darwin)
kens-mbp:back-end kenono$ 
````

**Comment by ranjan-purbey** [comment]
It's the same syntax error. I have a feeling that there is something wrong with your Answer model. If possible share the entire schema

**Comment by kokokenada** [comment]
The problem was resolved by changing the Answer model to: (previous version listed above)
````
model Answer {
  id          String   @default(cuid()) @id
  content     String
  question    Question
  userId      String
  author      User @relation (fields: [userId], references: [id])
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}
````
I guess prisma could be improved by providing better diagnostic messages

**Comment by ranjan-purbey** [comment]
You also need to add a scalar field for Question relation

**Comment by pantharshit00** [comment]
We are working on better schema validation. It will get released in the next beta version

**Comment by pantharshit00** [comment]
We no longer accept models without explicit foreign keys so this is addressed.
