### ISSUE TITLE
prisma commands dont worth with new AWS RDS CAs 

### ISSUE THREAD

**Issue by TomDo1234** [prisma/prisma#20921]
### Bug description

AWS this year has released new CAs that are meant to last a century or something, essentially, if you are running an app with prisma, and that app points to an RDS instance with one of these new CAs, or at least rds-ca-ecc384-g1 from my testing, then you will get a P1011 error, switching back to gold old RDS CA 2019 fixes it.

The error does NOT occur normally with the prisma CLIENT, but appears if you do npx prisma migrate or db push.

### How to reproduce

1. Make an RDS instance, any DB is fine, but use postgres preferably since thats what I used
2. Use rds-ca-ecc384-g1 CA 
3. do npx prisma db push or npx prisma migrate deploy 
4. Observe the p1011 error

### Expected behavior

You should be able to connect

### Prisma information

5.20

### Environment & setup

ubuntu 22.04 Docker container with prisma 5.20

### Prisma Version

5.20

**Comment by shadoworion** [comment]
@TomDo1234 

If you want a quick fix, you may select a new "rds-ca-rsa2048-g1" with RSA 2048 private key algorithm and SHA256 signing algorithm that was before in the previous "rds-ca-2019" CA.

"rds-ca-rsa4096-g1" with RSA 4096 private key algorithm and SHA384 signing algorithm and "rds-ca-ecc384-g1" with ECC 384 private key algorithm and SHA384 signing algorithm - may be a problem.

**Comment by tmadej** [comment]
We experienced the same issue today upon CA rotation mandated by AWS. Expect more people to experience this issue ahead of the August 2024 expiry of the AWS "rds-ca-2019" CA. 

Workaround from @shadoworion confirmed to work.

**Comment by manueltarouca** [comment]
Prisma version 5.0 as well.

**Comment by danf22** [comment]
Confirmed updated to rds-ca-rsa2048-g1 to solve the issue.

**Comment by ananththangaraj** [comment]
@danf22  Its failing for rds-ca-rsa2048-g1

**Comment by pirtlj** [comment]
Having this issue as well after doing the recommended AWS Cert update

**Comment by harrylev1ck** [comment]
I am using Prisma `v5.10.2`, I have rotated the CA of my RDS postgres instance from `rds-ca-2019` to `rds-ca-rsa2048-g1` and the connection string I am using to connect to the DB uses the [new certificate bundle](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.CertificatesAllRegions) `eu-west-2-bundle.pem` file, which is intended to work both for `rds-ca-2019` and `rds-ca-rsa2048-g1` CAs.

I am observing an error thrown by Prisma:

```
PrismaClientKnownRequestError:
Invalid `prisma.driver.findMany()` invocation:

Error opening a TLS connection: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1916: (self signed certificate in certificate chain)
    at _n.handleRequestError (/usr/src/app/main.js:69667:17)
    at _n.handleAndLogRequestError (/usr/src/app/main.js:69652:16)
    at _n.request (/usr/src/app/main.js:69643:16)
    at async l (/usr/src/app/main.js:70035:21)
    at async Promise.all (index 0)
    at async findMany (/usr/src/app/main.js:363340:25)
    at async resolveMiddleware (/usr/src/app/main.js:357048:22)
    at async callRecursive (/usr/src/app/main.js:357075:25)
    at async callRecursive (/usr/src/app/main.js:357075:25)
```

Any ideas why this might be happening?
