### ISSUE TITLE
Treat missing `provider` as known error that does not trigger Error Reporting

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2093]
```
Error: [<::std::macros::panic macros>:5:6] not implemented: Supported url schemes: file or sqlite, mysql, postgres or postgresql.
    at ChildProcess.child.on (/Users/Evan/Documents/VSCode Projects/52hospital/api-server/node_modules/@prisma/cli/build/index.js:2:1245660)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

via schema:

```
datasource mysql {\n  provider = \"mysql\"\n  url      = \"localhost:3360\"\n}
```

Example: https://prisma-errors.netlify.com/report/2726

**Comment by tomhoule** [comment]
This should already be fixed. Candidating for us to confirm it.

**Comment by tomhoule** [comment]
Checked with 2.20.1. Migrate now fails with:

```
Error: Schema Parsing P1012

Get config 
error: Error validating: This line is not a valid definition within a datasource.
  -->  schema.prisma:9
   | 
 8 | datasource db {
 9 |     provider = "mysql" // other options are: "mysql" and "sqlite"
10 |     url = "localhost:3306"
   | 
```

I think we can close the issue.
