### ISSUE TITLE
cannot find module '.prisma/client/index On AWS Lambda

### ISSUE THREAD

**Issue by ifat420** [prisma/prisma#20962]
### Bug description

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '.prisma/client/index'\nRequire stack:\n- /var/task/node_modules/@prisma/client/index.js\n- /var/task/index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '.prisma/client/index'",
        "Require stack:",
        "- /var/task/node_modules/@prisma/client/index.js",
        "- /var/task/index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)",
        "    at async start (file:///var/runtime/index.mjs:1256:23)",
        "    at async file:///var/runtime/index.mjs:1262:1"
    ]
}
```

### How to reproduce

Run a simple CRUD operation in aws lambda 
with the below import

```
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

```

### Prisma information

`// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "linux-arm64-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model stores {
  shop     String   @id
  isActive Boolean? @default(false)
}

model session {
  id      String  @id
  content String? @db.Text
  shop    String?
}

model store_status {
  shop    String @id
  hasNextPage Boolean? @default(false)
  after String? 
}

model product {
  id           String   @id @default(uuid())
  title        String?
  handle       String
  status       String
  productId    String
  image        String?
  athletes     athlete[]
  colleges     college[]
  sports       sport[]
}

model athlete {
  id        String    @id @default(uuid())
  name      String
  product       product       @relation(fields: [productId], references: [id], onDelete: Cascade)
  productId   String
}

model college {
  id        String    @id @default(uuid())
  name      String
  product       product       @relation(fields: [productId], references: [id], onDelete: Cascade)
  productId   String
}

model sport {
  id        String    @id @default(uuid())
  name      String
  product       product       @relation(fields: [productId], references: [id], onDelete: Cascade)
  productId   String
}

model active_stores {
  shop     String   @id
  isActive Boolean? @default(false)
}

model discount {
  id                    Int  @id @default(autoincrement())
  title                 String
  discountId            String
  segmentId             String
  discountPercentage    Float
  tag                   String @unique
  shop                  String
  isActive              Boolean?  @default(true)
  appliesTo             String
  ids                   String[]
  createdAt DateTime? @default(now())
  updatedAt DateTime? @updatedAt

}

model metafield {
  shopId                      String @id
  activeDiscountMetaId   String
  value                       String
  createdAt DateTime? @default(now())
  updatedAt DateTime? @updatedAt
}
`

### Environment & setup

- OS: AWS LAMBDA (Architecture: arm64)
- Database: PostgreSQL
- Node.js version: 18.17.1

### Prisma Version

```
 "@prisma/client": "^5.2.0",
    "prisma": "^5.2.0"
```

**Comment by c3sare** [comment]
https://www.prisma.io/docs/guides/deployment/serverless/deploy-to-aws-lambda

**Comment by ifat420** [comment]
`const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

exports.handler = async (event) => {
  try {
    const count = await prisma.product.count();
    console.log(`Total rows in User table: ${count}`);

    return {
      statusCode: 200,
      body: JSON.stringify({
        message: `Total rows in User table: ${count}`
      })
    };
  } catch (error) {
    console.error(error);

    return {
      statusCode: 500,
      body: JSON.stringify({
        message: 'Something went wrong'
      })
    };
  } finally {
    await prisma.$disconnect();
  }
};
`

I just want to run this piece of code on lambda that's it. 
How can I do that ?
