### ISSUE TITLE
When save the bigint report Could not convert argument value Object to ArgumentValue

### ISSUE THREAD

**Issue by GHChrisSu** [prisma/prisma#21049]
### Bug description

await prisma.stakeRecord.create(
Could not convert argument value Object {"$type": String("BigInt"), "value": String("47359100000000000000")} to ArgumentValue.
    at zr.handleRequestError (/Users/suhao/github/project/node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client/runtime/library.js:122:8480)
    at zr.handleAndLogRequestError (/Users/suhao/github/project/node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/Users/suhao/github/project/node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client/runtime/library.js:122:7307)
    at async fetchEvents (/Users/suhao/github/project/daemon/listenBlock.ts:45:3)
    at async /Users/suhao/github/project/daemon/listenBlock.ts:58:5 {
  clientVersion: '5.0.0'
}

### Expected behavior

Save correctly

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
    provider = "prisma-client-js"
}

datasource db {
    provider = "postgresql"
    // NOTE: When using mysql or sqlserver, uncomment the @db.Text annotations in model Account below
    // Further reading:
    // https://next-auth.js.org/adapters/prisma#create-the-prisma-schema
    // https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#string
    url      = env("DATABASE_URL")
}

model StakeRecord {
    id          String @id @default(cuid())
    user        String
    amountU     BigInt @db.BigInt
    amountT     BigInt @db.BigInt
    blockHash   String
    blockNumber Int

    createdAt DateTime @default(now())
    updatedAt DateTime @default(now()) @updatedAt
}

```

```ts
  await prisma.stakeRecord.create({
    data: {
      user: '',
      amountT: BigInt(47359100000000000000),
      amountU: BigInt(1),
      blockHash: '',
      blockNumber: 1,
    }
  })
```

### Environment & setup

- OS: macos
- Database: PostgreSQL
- Node.js version: v18.13.0

### Prisma Version

```
5.0.0
```

**Comment by OfirYC** [comment]
also having this issue. Have you found a solution?

**Comment by vh** [comment]
Same issue.

**Comment by benjioh5** [comment]
Same Issue 😭

**Comment by rohit-serri** [comment]
Anyone got any solutions to this?

**Comment by benjioh5** [comment]
Error is caused by difference between javascript's BigInt Max size and Databases' bigint type's max size.

e.g. 1n~1000n, BigInt(1000) is ok to insert. But BigInt(47359100000000000000) is bigger than 2^64 -1 which is mysql bigint type and emits errors.

**Comment by rohit-serri** [comment]
Inserts work fine, queries data with a where condition doesn't :(

**Comment by rohit-serri** [comment]
query: "SELECT * FROM Community_Data WHERE id=$1",
  parameters: {
    values: "[{\"prisma__type\":\"bigint\",\"prisma__value\":\"11670944315192156157\"}]",
    __prismaRawParameters__: true
  }
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
}

Invalid value for argument `parameters`: Could not convert from `JSON bigint value` to `PrismaValue`. Expected Flat JSON array (no nesting).

using raw query instead of normal prisma functions returns this error.

while normal function use throws "Could not convert argument value Object {"$type": String("BigInt"), "value": String("11670944315192156157")} to ArgumentValue."

**Comment by Jolg42** [comment]
On PostgreSQL, the limitation is similar as MySQL indeed https://www.postgresql.org/docs/current/datatype-numeric.html
The docs say bigint goes from `-9223372036854775808 to +9223372036854775807`

If you want a value bigger than what a database bigint can contain, then you will need to switch the field to use the native decimal type like this in your Prisma schema. 

See https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#postgresql-5
```prisma
@db.Decimal(p, s)
```
p (precision), the maximum total number of decimal digits to be stored. s (scale), the number of decimal digits that are stored to the right of the decimal point.

Example for storing big integers, with a maximum of 30 digits:
```prisma
myBigNumber Decimal @db.Decimal(30, 0)
```

For more details about how to choose the right precision and scale, read https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL

**Comment by benjioh5** [comment]
@Jolg42 When I changed all BigInt to Decimal(65,0), it returns string type. Is there any way to change type or input/output's type?

**Comment by benjioh5** [comment]
https://www.prisma.io/docs/concepts/components/prisma-client/advanced-type-safety/operating-against-partial-structures-of-model-types

https://www.prisma.io/docs/concepts/components/prisma-client/middleware#running-order-and-the-middleware-stack

I found this but I have no idea about convert BigInt to Decimal(65,0) which is acceptable range of js bigint common usage

**Comment by benjioh5** [comment]
I think ut is already exists issue.

https://github.com/prisma/prisma/issues/19860

**Comment by Jolg42** [comment]
I posted in https://github.com/prisma/prisma/issues/19860 that I think you could use a Client Extension for that purpose.

**Comment by Jolg42** [comment]
@dsldsl if you want to store a bigger number than what the database can store, you will need to switch the database type.

For example, by switching from BigInt to Decimal, see for example PostgreSQL Numeric types here https://www.postgresql.org/docs/9.1/datatype-numeric.html

And my previous post:
https://github.com/prisma/prisma/issues/21049#issuecomment-1781842721

**Comment by dsldsl** [comment]
@Jolg42 thanks for the reply.  Yes, I am using Decimal in the DB.  I would like to use BigInt instead of String in my JS model and not have to create a custom model object each time, and as I was starting out with Prisma was looking for a best practice solution.  I ended up doing the conversion in Middleware, and for right now I have a hardcoded list of all fields per model that have to be converted each direction and I update that as needed.  Would be ideal if that was something that could be handled automatically with a prisma type imo.

**Comment by pluggedinlife** [comment]
Facing the same problem using prisma and Postgresql@17

**Comment by Wildanzr** [comment]
I don't see any solution/workaround for this. Is it a good approach to save Bigint as a String in the database and do the real calculation in the program app?
