### ISSUE TITLE
NestJS, issues importing Prisma Client when using custom output path

### ISSUE THREAD

**Issue by rockmanflcl** [prisma/prisma#21066]
### Bug description

In a NestJS applicating, when importing prisma client using a custom generated path.
note: application runs fine when importing prisma client using default path `import { PrismaClient } from '@prisma/client';`

application gets following error
`Error: Cannot find module './generated/client'
Require stack:
- prismatest\dist\prisma\prisma.service.js
- prismatest\dist\prisma\prisma.module.js
- prismatest\dist\app.module.js
- prismatest\dist\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (prismatest\src\prisma\prisma.service.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)`

### How to reproduce

In NestJS application, set `schema.prisma` with custom output path

```prisma
generator client {
  provider = "prisma-client-js"
  output = "./generated/client"
}
```

Create nestJS service and extend PrismaClient which imports from generated output PrismaClient

```ts
import { Injectable } from '@nestjs/common';
import { PrismaClient } from './generated/client';

@Injectable()
export class PrismaService extends PrismaClient {}
```

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  output = "../../node_modules/@gigauth/generated/client"
}
```

```ts
import { Injectable } from '@nestjs/common';
import { PrismaClient } from './generated/client';

@Injectable()
export class PrismaService extends PrismaClient {}
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v18.15.0
- NestJS version: 10.1.8

### Prisma Version

```
prisma                  : 5.2.0
@prisma/client          : 5.2.0
Current platform        : windows
Query Engine (Node-API) : libquery-engine 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at ..\..\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at ..\..\node_modules\@prisma\engines\schema-engine-windows.exe)  
Schema Wasm             : @prisma/prisma-schema-wasm 5.2.0-25.2804dc98259d2ea960602aca6b8e7fdc03c1758f
Default Engines Hash    : 2804dc98259d2ea960602aca6b8e7fdc03c1758f
Studio                  : 0.494.0
```

**Comment by rockmanflcl** [comment]
I also tried using a NestJS monorepo project using the generated custom path for prisma client and got the following error
`ERROR [ExceptionHandler] Prisma Client could not find its `schema.prisma`. This is likely caused by a bundling step, which leads to `schema.prisma` not being copied near the resulting bundle. We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/bundler-investigation-error`

**Comment by janpio** [comment]
> Please help us by answering a few questions: https://pris.ly/bundler-investigation-error

Can you please do that and then link to your answer here? These questions are designed to ask for the correct details to debug such a problem.

For your original message:

> application gets following error

Can you share the complete error message? This only seems to be part of it - the actual _error_ is missing for example. Thanks!

**Comment by rockmanflcl** [comment]
@janpio 
> Can you please do that and then link to your answer here? These questions are designed to ask for the correct details to debug such a problem.
> 
https://github.com/prisma/prisma/discussions/20257#discussioncomment-6992382

> Can you share the complete error message? This only seems to be part of it - the actual _error_ is missing for example. Thanks!

```ts
Error: Cannot find module './generated/client'
Require stack:
- prismatest\dist\prisma\prisma.service.js
- prismatest\dist\prisma\prisma.module.js
- prismatest\dist\app.module.js
- prismatest\dist\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (prismatest\src\prisma\prisma.service.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
```

**Comment by janpio** [comment]
Ok, back to your original problem: I can reproduce it:

```
[5:41:14 PM] Starting compilation in watch mode...

[5:41:17 PM] Found 0 errors. Watching for file changes.

Error: Cannot find module '../prisma/generated/foo'
Require stack:
- /workspace/prisma-examples/typescript/rest-nestjs/dist/src/prisma.service.js
- /workspace/prisma-examples/typescript/rest-nestjs/dist/src/app.controller.js
- /workspace/prisma-examples/typescript/rest-nestjs/dist/src/app.module.js
- /workspace/prisma-examples/typescript/rest-nestjs/dist/src/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/workspace/prisma-examples/typescript/rest-nestjs/src/prisma.service.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
```

We have a nice NestJS example project at https://github.com/prisma/prisma-examples/tree/latest/typescript/rest-nestjs
When I add a custom output, I indeed get the same error: https://github.com/prisma/prisma-examples/pull/5228/files + https://github.com/prisma/prisma-examples/actions/runs/6175968386/job/16763936139?pr=5228#step:5:65

And indeed, the generated Prisma Client is not included in the `dist` folder of the project at all:
```
$ tree dist
dist
├── prisma
│   ├── seed.d.ts
│   ├── seed.js
│   └── seed.js.map
├── src
│   ├── app.controller.d.ts
│   ├── app.controller.js
│   ├── app.controller.js.map
│   ├── app.module.d.ts
│   ├── app.module.js
│   ├── app.module.js.map
│   ├── main.d.ts
│   ├── main.js
│   ├── main.js.map
│   ├── prisma.service.d.ts
│   ├── prisma.service.js
│   └── prisma.service.js.map
└── tsconfig.build.tsbuildinfo
```

Some bundler configuration is missing here.

**Comment by janpio** [comment]
(I know this is not what you want, but a custom output path that is in `node_modules`, e.g. `../node_modules/@foo/bar`, seems to work: https://github.com/prisma/prisma-examples/pull/5229 I totally do not recommend doing that, but for some reason that is picked up.)

**Comment by rockmanflcl** [comment]
> (I know this is not what you want, but a custom output path that is in `node_modules`, e.g. `../node_modules/@foo/bar`, seems to work: [prisma/prisma-examples#5229](https://github.com/prisma/prisma-examples/pull/5229) I totally do not recommend doing that, but for some reason that is picked up.)

I was actually about to mention that but you can also set the output path to a root folder and it will also get picked up . 
The root path does not work for the monorepo setup though and will only work if you set the output path as you stated in `../node_modules/@foo/bar`,

**Comment by janpio** [comment]
Yes, monorepo is a different problem completely.
What is an example for "a root folder" that works?

**Comment by bparras** [comment]
> Yes, monorepo is a different problem completely. What is an example for "a root folder" that works?

Was referring to the root folder of the app so if the folder you generate the client into is at the root level of the app it also gets picked up. `import { PrismaClient } from 'prisma/generated/client';`
```
\---prismatest
    +---dist
    +---node_modules
    +---prisma
    |   |   schema.prisma
    |   |   
    |   \---generated
    |       \---client
    |           |   edge.d.ts
    |           |   edge.js
    |           |   index-browser.js
    |           |   index.d.ts
    |           |   index.js
    |           |   package.json
    |           |   query_engine-windows.dll.node
    |           |   schema.prisma
    |           |   
    |           \---runtime
    |                   edge-esm.js
    |                   edge.js
    |                   index-browser.d.ts
    |                   index-browser.js
    |                   library.d.ts
    |                   library.js
    |                   
    +---src
    |   .eslintrc.js
    |   .gitignore
    |   .prettierrc
    |   nest-cli.json
    |   package-lock.json
    |   package.json
    |   README.md
    |   tree.txt
    |   tsconfig.build.json
    |   tsconfig.json
```

**Comment by rockmanflcl** [comment]
> Yes, monorepo is a different problem completely. What is an example for "a root folder" that works?

Was referring to the root folder of the app so if the folder you generate the client into is at the root level of the app it also gets picked up. `import { PrismaClient } from 'prisma/generated/client';`
```
\---prismatest
    +---dist
    +---node_modules
    +---prisma
    |   |   schema.prisma
    |   |   
    |   \---generated
    |       \---client
    |           |   edge.d.ts
    |           |   edge.js
    |           |   index-browser.js
    |           |   index.d.ts
    |           |   index.js
    |           |   package.json
    |           |   query_engine-windows.dll.node
    |           |   schema.prisma
    |           |   
    |           \---runtime
    |                   edge-esm.js
    |                   edge.js
    |                   index-browser.d.ts
    |                   index-browser.js
    |                   library.d.ts
    |                   library.js
    |                   
    +---src
    |   .eslintrc.js
    |   .gitignore
    |   .prettierrc
    |   nest-cli.json
    |   package-lock.json
    |   package.json
    |   README.md
    |   tree.txt
    |   tsconfig.build.json
    |   tsconfig.json
```

**Comment by rockmanflcl** [comment]
Yea it is. Wasn't sure if you knew that worked in addition to generating client into `../node_modules/@foo/bar`

**Comment by janpio** [comment]
No, that's the problem: That does _not_ work in my case, see https://github.com/prisma/prisma-examples/actions/runs/6175968386/job/16763936139?pr=5228#step:5:65

```
$ tree
.
├── nest-cli.json
├── package.json
├── prisma
│   ├── generated
│   │   └── foo
│   │       ├── edge.d.ts
│   │       ├── edge.js
│   │       ├── index-browser.js
│   │       ├── index.d.ts
│   │       ├── index.js
│   │       ├── libquery_engine-debian-openssl-3.0.x.so.node
│   │       ├── package.json
│   │       ├── runtime
│   │       │   ├── edge-esm.js
│   │       │   ├── edge.js
│   │       │   ├── index-browser.d.ts
│   │       │   ├── index-browser.js
│   │       │   ├── library.d.ts
│   │       │   └── library.js
│   │       └── schema.prisma
│   ├── schema.prisma
│   └── seed.ts
├── README.md
├── src
│   ├── app.controller.ts
│   ├── app.module.ts
│   ├── main.ts
│   └── prisma.service.ts
├── test
│   ├── app.e2e-spec.ts
│   └── jest-e2e.json
├── tsconfig.build.json
└── tsconfig.json
```

**Comment by rockmanflcl** [comment]
> No, that's the problem: That does _not_ work in my case, see https://github.com/prisma/prisma-examples/actions/runs/6175968386/job/16763936139?pr=5228#step:5:65
> 
@janpio I tried pulling down your branch and confirmed that the problem is still happening.
Took a while but figured out what was making your build fail was the `seed.ts` file in the prisma folder.
If you delete the `seed.ts` file and also need to delete the `dist` folder, the app seems to generate the correct structure in the `dist` folder.

```
+---dist
|       app.controller.d.ts
|       app.controller.js
|       app.controller.js.map
|       app.module.d.ts
|       app.module.js
|       app.module.js.map
|       main.d.ts
|       main.js
|       main.js.map
|       prisma.service.d.ts
|       prisma.service.js
|       prisma.service.js.map
|       tsconfig.build.tsbuildinfo
```

this is the `dist` folder structure when the `seed.ts` file is still in the prisma folder where the app has errors.
```
+---dist
|   |   tsconfig.build.tsbuildinfo
|   |   
|   +---prisma
|   |       seed.d.ts
|   |       seed.js
|   |       seed.js.map
|   |       
|   \---src
|           app.controller.d.ts
|           app.controller.js
|           app.controller.js.map
|           app.module.d.ts
|           app.module.js
|           app.module.js.map
|           main.d.ts
|           main.js
|           main.js.map
|           prisma.service.d.ts
|           prisma.service.js
|           prisma.service.js.map
```

hopefully this works for you and gives some insight into what the issue is

**Comment by janpio** [comment]
Ugh yes, I can reproduce that removing the `seed` file makes the application with a custom `output` folder work:
https://github.com/prisma/prisma-examples/pull/5234

That is... unexpected. Seems the `seed.ts` in the `prisma` folder leads to the app being bundled differently, without the custom output folder. :wat:

**Comment by ruheni** [comment]
A possible workaround without deleting the `prisma/ seed.ts` file would be copying the files ([`cpx`](https://www.npmjs.com/package/cpx)) right before you run the `dev` script or right after your `build` script (depending on your setup)

Using the `rest-nestjs` Prisma example, you can get around it as follows.:

1. Install `cpx` as a dev dependency — `npm install cpx`
2. Add a script to copy the files in your `package.json` file (if the output remains to be `../prisma/generated`):

```json
"copy:prisma": "cpx 'prisma/generated/**' 'dist/prisma/generated'",
```

4. Update the `dev` script to run `copy:prisma` before starting the application

```json
"dev": "npm run copy:prisma && nest start --watch",
```

**Comment by jeffersonveloso** [comment]
> import { PrismaClient } from 'prisma/generated/client

I'm having this problem with the docker container: 
![Captura de Tela 2024-10-02 às 11 17 46](https://github.com/user-attachments/assets/c90a5d07-0bfa-4aba-841b-27fd00d2d04f)

My prisma client is version: 5.15.0 and I'm using the default directory.

**Comment by waqarilyas** [comment]
following.

**Comment by waqarilyas** [comment]
This worked for me.

Modify your nest-cli.json file to include the generated folder as assets.
`{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "assets": [
      {
        "include": "../prisma/generated",
        "outDir": "dist/prisma",
        "watchAssets": true
      }
    ],
    "watchAssets": true
  }
}
`

**Comment by scarecrow-11** [comment]
Just a modification in the `start:prod` script in the `package.json`  file worked for me. Didn't need any custom output path or any issues with the `seed.ts` file. Just importing from `@prisma/client` should be fine.

`package.json` file
```json
{
    "scripts": {
        "start:prod": "node dist/src/main"
    }
}
```

It seems like, the `seed.ts` file changes the `dist` directory structure. Wihout the `seed.ts` file, the `main.js` file bundles into the `dist` directory. But if you add the `seed.ts` file, the `main.js` file goes into the `dist/src` directory

**Comment by jginorio** [comment]
I added the following path suggested by the prisma cli when running  "npx prisma generate --sql --watch" and worked for me. At least in dev mode (npm run start:dev), haven't tested in prod

```
generator client {
  // ... other configs
  output   = "../node_modules/.prisma/generated/client" // <-- added this path
}
```

**Comment by Brxlx** [comment]
> This worked for me.
> 
> Modify your nest-cli.json file to include the generated folder as assets.
> 
> {
> "$schema": "https://json.schemastore.org/nest-cli",
> "collection": "@nestjs/schematics",
> "sourceRoot": "src",
> "compilerOptions": {
>  "deleteOutDir": true,
>  "assets": [
>    {
>      "include": "../prisma/generated",
>      "outDir": "dist/prisma",
>      "watchAssets": true
>    }
>  ],
>  "watchAssets": true
> }
> }

This works, thanks!

**Comment by Eve-Sama** [comment]
I am using nx+nestjs, in my project can not found `nest-cli.json`, these is only `project.json`, anyone know how to update `project.json`?

**Comment by mevlutkural** [comment]
If you're experiencing similar issues, specifying the full relative path to the generated Prisma client can resolve module resolution errors:
```ts
import { Prisma, PrismaClient } from '../../../generated/prisma';
```
This ensures that the module resolution mechanism accurately locates the generated client files, especially when using a custom output path in your Prisma configuration.

**Comment by kyeoungwoon** [comment]
In my case, I generated my Prisma Client in `src/generated/prisma` directory like the code below,

```
generator client {
  provider = "prisma-client-js"
  output   = "../src/generated/prisma"
}
```

So I had to change my `compilerOptions` in `nest-cli.json` to

```json
  "compilerOptions": {
    "deleteOutDir": true,
    "assets": [
      {
        "include": "generated/prisma",
        "outDir": "dist",
        "watchAssets": true
      }
    ],
    "watchAssets": true
  }
```

worked for me !


btw, if we don't mind those dirty relative paths in the code, using relative path such as `../../../../src/generated/prisma` is the most clear way to fix it.

It seems to be the problem while bundling those files with TypeScript.

ADD: Found that we CANNOT use `@prisma/client` as a TypeScript Path alias, don't know why ..

**Comment by muxinqi** [comment]
I ran into something similar and here is a simple fix that worked for me.

### The Problem

I had `prisma/seed.ts` in my project, and TypeScript was compiling it into the build folder. This messed up my directory structure:
- With seed.ts: `dist/src/main.js` and `dist/prisma/seed.js`
- Without seed.ts: `dist/main.js`

The changing structure broke my import paths and caused "Cannot find module" errors.

### The Fix

Just exclude the `prisma` folder from your build config:

**tsconfig.build.json:**
```diff
{
  "extends": "./tsconfig.json",
- "exclude": ["node_modules", "test", "dist", "**/*spec.ts"]
+ "exclude": ["node_modules", "test", "dist", "**/*spec.ts", "prisma"]
}
```

### Why this works

In my case, `seed.ts` is only for development. It doesn't need to be in the production build at all.
