### ISSUE TITLE
getting error during build for vercel  with qwikcity

### ISSUE THREAD

**Issue by harshmangalam** [prisma/prisma#21094]
### Bug description

".prisma/client/index-browser" is imported by ".prisma/client/index-browser?commonjs-external", but could not be resolved – treating it as an external dependency.

error during build:
TypeError [PLUGIN_ERROR]: Invalid module ".prisma/client/index-browser" is not a valid package name imported from /Users/harshmangalam/qwik-prisma/.vercel/output/functions/_qwik-city.func/assets/@qwik-city-plan-2c65295d.js
    at new NodeError (node:internal/errors:399:5)
    at parsePackageName (node:internal/modules/esm/resolve:817:11)
    at packageResolve (node:internal/modules/esm/resolve:840:5)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)

### How to reproduce

- pnpm qwik add vercel-edge
- pnpm run build

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}

```

```ts

import { PrismaClient } from "@prisma/client";

export const prisma = new PrismaClient();

```

### Environment & setup

- OS:  macOS
- Database: PostgreSQL
- Node.js version: v18.16.0

### Prisma Version

```
5.3.1
```

**Comment by janpio** [comment]
How exactly are you using Prisma @harshmangalam? There seem to be many options with Quickcity, so some more information - or optimally a new minimal project in a GitHub repository - would be optimal for us to reproduce this problem.

**Comment by janpio** [comment]
I can confirm this:
```
npm create qwik@latest
npm run qwik add prisma
npm run qwik add vercel-edge
```

Two problems:
- `@prisma/client` currently does not work on Edge Functions, including Vercel Edge Functions or Runtime. Reproduction see: https://github.com/janpio/prisma-qwik
- Even using the supposedly compatible `@prisma/client/edge` does not work out of the box:
	```
	".prisma/client/edge" is imported by ".prisma/client/edge?commonjs-external", but could not be resolved – treating it as an external dependency.
	error during build:
	TypeError [PLUGIN_ERROR]: Invalid module ".prisma/client/edge" is not a valid package name imported from C:\Users\Jan\Documents\throwaway\qwik\.vercel\output\functions\_qwik-city.func\assets\@qwik-city-plan-382afed5.js
	    at new NodeError (node:internal/errors:387:5)
	    at parsePackageName (node:internal/modules/esm/resolve:777:11)
	    at packageResolve (node:internal/modules/esm/resolve:800:5)
	    at moduleResolve (node:internal/modules/esm/resolve:901:20)
	    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
	    at nextResolve (node:internal/modules/esm/loader:163:28)
	    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
	    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
	    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
	    at link (node:internal/modules/esm/module_job:75:36)
	```
    Reproduction see https://github.com/janpio/prisma-qwik/tree/data-proxy
    
@harshmangalam You original problem is expected right now, as Prisma does not support Vercel Edge Functions out of the box which Qwik's `vercel-edge` uses. You can follow this issue here for updates on this: https://github.com/prisma/prisma/issues/20566

The second problem is unexpected and something we might want to investigate independently - I will keep this issue for that.

**Comment by eglove** [comment]
I ran into this issue 11/11/23 when working with CloudFlare pages.

`Invalid module ".prisma/client/edge" is not a valid package name`

`import { PrismaClient } from '@prisma/client/edge';`

This is used with Prisma Accelerate as a proxy to work with edge functions. Is there any way to get build to resolve this?

**Comment by janpio** [comment]
Our release 5.11.0 just added preview support for edge function deployments, please take a look if this helps resolving this issue: https://github.com/prisma/prisma/releases/tag/5.11.0

**Comment by janpio** [comment]
(Internal: Next step is to confirm again with recent versions of everything)

**Comment by Jolg42** [comment]
With `5.13.0`, only the name of the file changed, from `edge` to `default`

```
✓ built in 2.52s
error during build:
TypeError [PLUGIN_ERROR]: Invalid module ".prisma/client/default" is not a valid package name imported from /Users/j42/Repros/21094/qwik-app/.vercel/output/functions/_qwik-city.func/@qwik-city-plan.js
    at new NodeError (node:internal/errors:406:5)
    at parsePackageName (node:internal/modules/esm/resolve:718:11)
    at packageResolve (node:internal/modules/esm/resolve:740:5)
    at moduleResolve (node:internal/modules/esm/resolve:838:20)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)

undefined
```

**Comment by Jolg42** [comment]
Note: I found the related issues in qwik's repo:
- Same problem https://github.com/QwikDev/qwik/issues/4075
- Same problem but with Deno https://github.com/QwikDev/qwik/issues/4747

**Comment by Jolg42** [comment]
`vercel-edge` adapter seems to be here https://github.com/QwikDev/qwik/tree/main/packages/qwik-city/adapters/vercel-edge
Docs: https://qwik.dev/docs/deployments/vercel-edge/

**Comment by Jolg42** [comment]
I found out that this could be solved with 2 aliases imports, see my repro here: https://github.com/Jolg42/prisma-repro-21094

This is what worked for me:
https://github.com/Jolg42/prisma-repro-21094/blob/main/adapters/vercel-edge/vite.config.ts
```ts
import { vercelEdgeAdapter } from "@builder.io/qwik-city/adapters/vercel-edge/vite";
import { extendConfig } from "@builder.io/qwik-city/vite";
import baseConfig from "../../vite.config";

export default extendConfig(baseConfig, () => {
  return {
    build: {
      ssr: true,
      rollupOptions: {
        input: ["src/entry.vercel-edge.tsx", "@qwik-city-plan"],
      },
      outDir: ".vercel/output/functions/_qwik-city.func",
    },
    plugins: [vercelEdgeAdapter()],
    resolve: {
      alias: {
        ".prisma/client/default": "./node_modules/.prisma/client/default.js",
        "./query_engine_bg.wasm?module": "./node_modules/.prisma/client/query_engine_bg.wasm?init",
      },
    },
  };
});
```

I found out about this in Vite's docs here https://vitejs.dev/guide/features#webassembly
> Pre-compiled .wasm files can be imported with ?init.

@harshmangalam @blakeley @eglove Could you try that and let us know if that works for you too?

**Comment by harshmangalam** [comment]
@Jolg42 It works for me when using `npm` but got following errors with `pnpm`.
```
error during build:
Error: [commonjs--resolver] Could not load ./node_modules/.prisma/client/default.js: ENOENT: no such file or directory, open './node_modules/.prisma/client/default.js'
```

**Comment by janpio** [comment]
@harshmangalam Can you try this out and confirm this is working? (Same for @blakeley @eglove)

If it does, we will be able to close this issue and document the special work needed to make it work in Qwikcity in our docs.

**Comment by harshmangalam** [comment]
I am getting error for pnpm
```
error during build:
TypeError: Bl.PrismaClient is not a constructor
    at my-project/.vercel/output/functions/_qwik-city.func/@qwik-city-plan.js:344:50027
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by leifermendez** [comment]
> I am getting error for pnpm
> 
> ```
> error during build:
> TypeError: Bl.PrismaClient is not a constructor
>     at my-project/.vercel/output/functions/_qwik-city.func/@qwik-city-plan.js:344:50027
>     at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
>  ELIFECYCLE  Command failed with exit code 1.
> ```

```ts
import { defineConfig, type UserConfig } from "vite";
import { qwikVite } from "@builder.io/qwik/optimizer";
import { qwikCity } from "@builder.io/qwik-city/vite";
import tsconfigPaths from "vite-tsconfig-paths";
import pkg from "./package.json";
import { createRequire } from "module";

const { dependencies = {}, devDependencies = {} } = pkg as {
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
  [key: string]: unknown;
};

const require = createRequire(import.meta.url);

const prismaClientPaths = {
  edge: require.resolve('@prisma/client/edge').replace(/@prisma\\client\\edge\.js/, '.prisma\\client\\edge.js'),
  default: require.resolve('@prisma/client').replace(/@prisma\\client\\default\.js/, '.prisma\\client\\default.js'),
  indexBrowser: require.resolve('@prisma/client/index-browser').replace(/@prisma\\client\\index-browser\.js/, '.prisma\\client\\index-browser.js'),
};

/**
 * Note that Vite normally starts from `index.html` but the qwikCity plugin makes start at `src/entry.ssr.tsx` instead.
 */
export default defineConfig(({ command, mode }): UserConfig => {
  const isProductionBuild = command === "build" && mode === "production";

  return {
    plugins: [qwikCity(), qwikVite(), tsconfigPaths()],
    optimizeDeps: {
      exclude: [],
    },
    ssr: isProductionBuild ? {
      noExternal: Object.keys(devDependencies),
      external: Object.keys(dependencies),
    } : undefined,
    server: {
      headers: {
        "Cache-Control": "public, max-age=0",
      },
    },
    resolve: {
      alias: {
        '.prisma/client/default': prismaClientPaths.default,
        '.prisma/client/index-browser': prismaClientPaths.indexBrowser,
        '.prisma/client/edge': prismaClientPaths.edge,
      },
    },
    preview: {
      headers: {
        "Cache-Control": "public, max-age=600",
      },
    },
  };
});

```
