### ISSUE TITLE
PRISMA_CLI_BINARY_TARGETS is not downloading the specified engine

### ISSUE THREAD

**Issue by SiNONiMiTY** [prisma/prisma#21105]
### Bug description

Adding the PRISMA_CLI_BINARY_TARGETS environment variable does not make Prisma download the indicated engine, instead, it only downloads the native binaries.

USAGE
`PRISMA_CLI_BINARY_TARGETS="debian-openssl-3.0.x" pnpm i`

`PRISMA_CLI_BINARY_TARGETS="debian-openssl-3.0.x" pnpm exec prisma generate`

None of the commands above initiates the download of the indicated binary

### How to reproduce

`PRISMA_CLI_BINARY_TARGETS="debian-openssl-3.0.x" pnpm i`

`PRISMA_CLI_BINARY_TARGETS="debian-openssl-3.0.x" pnpm exec prisma generate`

### Expected behavior

Should download the indicated engine

### Prisma information

```
Environment variables loaded from .env
prisma                  : 5.3.1
@prisma/client          : 5.3.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules\.pnpm\@prisma+engines@5.3.1\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules\.pnpm\@prisma+engines@5.3.1\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.3.1-2.61e140623197a131c2a6189271ffee05a7aa9a59
Default Engines Hash    : 61e140623197a131c2a6189271ffee05a7aa9a59
Studio                  : 0.494.0
```

### Environment & setup

- OS: Windows, Linux
- Database: N/A
- Node.js version: v20.6.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.3.1
@prisma/client          : 5.3.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules\.pnpm\@prisma+engines@5.3.1\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules\.pnpm\@prisma+engines@5.3.1\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.3.1-2.61e140623197a131c2a6189271ffee05a7aa9a59
Default Engines Hash    : 61e140623197a131c2a6189271ffee05a7aa9a59
Studio                  : 0.494.0
```

**Comment by janpio** [comment]
Which engine file would you expect it to download?

For me it does exactly what I expect it to do:
```
> npm init -y && npm install prisma
> tree .\node_modules\@prisma\engines /f
Folder PATH listing for volume Local Disk
Volume serial number is 803D-0C49
C:\USERS\JAN\DOCUMENTS\THROWAWAY\21105\NODE_MODULES\@PRISMA\ENGINES
│   LICENSE
│   package.json
│   query_engine-windows.dll.node
│   README.md
│   schema-engine-windows.exe
...
> $env:PRISMA_CLI_BINARY_TARGETS="debian-openssl-3.0.x"
> (delete node_modules)
> tree .\node_modules\@prisma\engines /f
Folder PATH listing for volume Local Disk
Volume serial number is 803D-0C49
C:\USERS\JAN\DOCUMENTS\THROWAWAY\21105\NODE_MODULES\@PRISMA\ENGINES
│   libquery_engine-debian-openssl-3.0.x.so.node
│   LICENSE
│   package.json
│   README.md
│   schema-engine-debian-openssl-3.0.x
```

(This is on Windows, using PowerShell) Instead of downloading the Windows engine files, the CLI downloads the `debian-openssl-3.0.x` ones. 

Running `prisma -v` on Windows hence will complain:

```
> npx prisma -v
Environment variables loaded from .env
Error: Could not find libquery-engine binary. Searched in:
- C:\Users\Jan\Documents\throwaway\21105\node_modules\@prisma\engines\query_engine-windows.dll.node
- C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\query_engine-windows.dll.node
- C:\Users\Jan\Documents\throwaway\21105\node_modules\query_engine-windows.dll.node
- C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\runtime\query_engine-windows.dll.node
    at resolveBinary2 (C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\build\index.js:109379:9)
Error: Could not find libquery-engine binary. Searched in:
- C:\Users\Jan\Documents\throwaway\21105\node_modules\@prisma\engines\query_engine-windows.dll.node
- C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\query_engine-windows.dll.node
- C:\Users\Jan\Documents\throwaway\21105\node_modules\query_engine-windows.dll.node
- C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\runtime\query_engine-windows.dll.node
    at resolveBinary2 (C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\build\index.js:109379:9)
Error: Could not find schema-engine binary. Searched in:
- C:\Users\Jan\Documents\throwaway\21105\node_modules\@prisma\engines\schema-engine-windows.exe
- C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\schema-engine-windows.exe
- C:\Users\Jan\Documents\throwaway\21105\node_modules\schema-engine-windows.exe
- C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\runtime\schema-engine-windows.exe
    at resolveBinary2 (C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\build\index.js:109379:9)
Error: Could not find schema-engine binary. Searched in:
- C:\Users\Jan\Documents\throwaway\21105\node_modules\@prisma\engines\schema-engine-windows.exe
- C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\schema-engine-windows.exe
- C:\Users\Jan\Documents\throwaway\21105\node_modules\schema-engine-windows.exe
- C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\runtime\schema-engine-windows.exe
    at resolveBinary2 (C:\Users\Jan\Documents\throwaway\21105\node_modules\prisma\build\index.js:109379:9)
prisma                  : 5.3.1
@prisma/client          : Not found
Current platform        : windows
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at E_CANNOT_RESOLVE_PATH)
Schema Engine           : E_CANNOT_RESOLVE_VERSION (at E_CANNOT_RESOLVE_PATH)
Schema Wasm             : @prisma/prisma-schema-wasm 5.3.1-2.61e140623197a131c2a6189271ffee05a7aa9a59
Default Engines Hash    : 61e140623197a131c2a6189271ffee05a7aa9a59
Studio                  : 0.494.0
```

But if I bundle the project, including its `node_modules`, and upload it to a debian machine with OpenSSL 3, the CLI will be able to work. (I could fix the `prisma -v` problem locally by adding `windows` to the env var.)

**Comment by SiNONiMiTY** [comment]
I see, so the download won't end up on the `.prisma/client` folder but on the `@prisma/engines` folder?

**Comment by janpio** [comment]
This env var is for Prisma CLI, hence `PRISMA_CLI_...` and not Prisma Client (both use engines).
For Prisma Client, the `binaryTargets` attribute is used to configure the "binary targets" (= platforms).

**Comment by SiNONiMiTY** [comment]
Alright, seems this is what I needed to download the engines. Closing this issue. Thanks @janpio
