### ISSUE TITLE
 missing index-browser.js.map

### ISSUE THREAD

**Issue by samjancool** [prisma/prisma#21111]
### Bug description

Failed to parse source map from 'D:\test\test\node_modules\@prisma\client\runtime\index-browser.js.map' file: Error: ENOENT: no such file or directory, open 'D:\test\test\node_modules\@prisma\client\runtime\index-browser.js.map'

I don't see index-browser.js.map in the specified path

PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `unknown`).
If this is unexpected, please open an issue: https://github.com/prisma/prisma/issues
Error: PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `unknown`).
If this is unexpected, please open an issue: https://github.com/prisma/prisma/issues
    at Object.get (http://localhost:3000/static/js/bundle.js:1747:15)
    at http://localhost:3000/static/js/bundle.js:687:12
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:31009:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:32502:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:32474:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:32464:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:32454:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:34339:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:34291:18)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:34250:9)

![index-browser js map_file_missing](https://github.com/prisma/prisma/assets/145305530/957552dd-70f1-4399-a086-0aab28651de9)

### Expected behavior

MySQL module table content must be rendered as html elements

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model attendance {
  id        Int     @id @default(autoincrement())
  sessionId Int
  studentId Int
  score     Int
  session   session @relation(fields: [sessionId], references: [id], map: "Attendance_sessionId_fkey")
  student   student @relation(fields: [studentId], references: [id], map: "Attendance_studentId_fkey")

  @@index([sessionId], map: "Attendance_sessionId_fkey")
  @@index([studentId], map: "Attendance_studentId_fkey")
}

model module {
  id       Int       @id @default(autoincrement())
  title    String
  semester Int
  code     String
  session  session[]
  student  student[] @relation("moduletostudent")
}

model session {
  id         Int          @id @default(autoincrement())
  date       DateTime     @default(now())
  group      String
  moduleId   Int
  attendance attendance[]
  module     module       @relation(fields: [moduleId], references: [id], map: "Session_moduleId_fkey")

  @@index([moduleId], map: "Session_moduleId_fkey")
}

model student {
  id          Int          @id @default(autoincrement())
  email       String       @unique(map: "Student_email_key")
  phone       Int          @unique(map: "Student_phone_key")
  parentPhone Int
  parentEmail String
  name        String
  course      String
  university  String
  level       String
  group       String
  attendance  attendance[]
  module      module[]     @relation("moduletostudent")
}

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

Windows 11
mysql
node v18.17.1

### Prisma Version

```

```
prisma                        : 5.3.1
@prisma/client          : 5.3.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 61e140623197a131c2a6189271ffee05a7aa9a59 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.3.1-2.61e140623197a131c2a6189271ffee05a7aa9a59
Default Engines Hash    : 61e140623197a131c2a6189271ffee05a7aa9a59
Studio                  : 0.494.0

**Comment by janpio** [comment]
Can you please tell us a bit more about your app?
Both errors you are getting are probably related how your app is set up.
Optimally you could provide us a reproduction app as a GitHub repository. Thanks!

**Comment by Jolg42** [comment]
@samjancool Did you see the message from @janpio? Without any activity on this issue, we would later close it as part of our issue process.

**Comment by FominSergiy** [comment]
Hi there! We are also seeing this warning in the webpack (doesn't throw errors, but a warning).

```

WARNING in ../../../node_modules/@prisma/client/runtime/index-browser.js
Module Warning (from ../../../node_modules/@nx/webpack/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/SergiyFomin/work-space/QualityNow/node_modules/@prisma/client/runtime/index-browser.js.map' file: Error: ENOENT: no such file or directory, open '/Users/SergiyFomin/work-space/QualityNow/node_modules/@prisma/client/runtime/index-browser.js.map'

```

It seems to be related to `client/runtime/index-browser.js` file, specifically to this line `//# sourceMappingURL=index-browser.js.map`. 

Unfortunately I am not sure yet what's the cause, but if I remove the line (`//# sourceMappingURL=index-browser.js.map`) from the file and re-run, the warning goes away.

we are running ` "@prisma/client": "5.5.2"`. hope it helps!

![Screenshot 2023-11-01 at 10 41 27 AM](https://github.com/prisma/prisma/assets/65659492/73581127-87c2-4558-81c0-f0a93ee4afa7)

**Comment by janpio** [comment]
Thanks for the information @FominSergiy! Can you help us reproduce this? What is your app setup? Can you create a minimal reproduction and put it on GitHub maybe?

**Comment by FominSergiy** [comment]
Hoped it would be something straightforward to do a little demo, but having a fun time reproducing this from a basic app with our stack.

I might take longer to reproduce the issue. Don't want you guys to keep waiting. if the original owner of the issue does not respond, feel free to close the issue. Once I can reproduce it, I can open a new issue?

**Comment by janpio** [comment]
We can leave this open a few weeks.

**Comment by FominSergiy** [comment]
Sounds good! That should be enough time, thanks!

**Comment by FominSergiy** [comment]
Hello again. The problem was my negligence. We've fixed the warning in our project. This was because a prisma client library was imported into a ui component where it shouldn't have. I've fixed the import, the warning is gone.

Good on my side.

**Comment by janpio** [comment]
Can you still explain the problem a bit more? As we know you are not the first one, so potentially your description might help others in the future to avoid this problem and find a solution to it quicker. Thanks.

**Comment by theonlystylar** [comment]
Hi, I'm seeing the warning as well.  We just upgraded our project to "@prisma/client": "5.5.2" from "@prisma/client": "5.1.1".  The webpack warning is coming from our React application ("react": "18.2.0") when it is served locally.  Here's the error:

```
WARNING in ../../node_modules/@prisma/client/runtime/index-browser.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/<me>/Documents/Current_Projects/app/node_modules/@prisma/client/runtime/index-browser.js.map' file: Error: ENOENT: no such file or directory, open '/Users/<me>/Documents/Current_Projects/app/node_modules/@prisma/client/runtime/index-browser.js.map'
```

I reverted back to 5.1.1, ran migrate reset, and the warning went away.

I hope that helps!

**Comment by Zenoo** [comment]
Same here, we only need the file `index-browser.js.map` to be included in the runtime files, since they are part of one of our package

![image](https://github.com/prisma/prisma/assets/7151485/f8ee233b-3a37-4d29-b0b9-13bc96c81c18)

**Comment by FominSergiy** [comment]
@janpio for sure, let me try it out.

In our application we use nestJs with prisma for our backend. In our nestJs app we rely on types generated by our prisma file (something similar to this: https://www.prisma.io/docs/concepts/components/prisma-client/advanced-type-safety#what-are-generated-types).

such types can imported in the backend by the following line.
```
import { YourCustomType } from '@prisma/client';
```

For our frontend we use react, and we are not directly importing the prisma types (there is a workaround we do). But the point is, we **don't** use the import statement `import { YourCustomType } from '@prisma/client';` <- this would give us a warning mentioned in this issue.


The warning mentioned in this issue comes from a webpack, during bundling process. There are two types of map files:

- `index.js` -> code intended to be used inside a Node application.
- `index-browser.js` -> code intended to be used on the browser.

It seems to me that Prisma is intended to be used inside a Node application, and when it is imported inside a browser-app (such a react app) it tries to find a source map inside the `index-browser.js` file, and throws a warnings because there is none?

**Comment by millsp** [comment]
Thanks for the additional information @FominSergiy. I think this is enough for us to attempt a reproduction. I can clearly see that Webpack's [source-map-loader](https://webpack.js.org/loaders/source-map-loader/) is attempting to load a source map in your errors as well as in other reported errors. Additionally, I found that Nest.js is suggesting similar tools as part of their [templates](https://github.com/nestjs/typescript-starter/blob/master/package.json#L45). Your analysis has shown that the source map name is [read](https://github.com/prisma/prisma/issues/21111#issuecomment-1789145758) and then cannot be found.

For the reproduction, I'd base myself on our webpack [test](https://github.com/prisma/ecosystem-tests/tree/dev/bundlers/webpack-browser-custom-output) that we have in ecosystem-tests which bundles our `index-browser`, and setup [source-map-loader](https://webpack.js.org/loaders/source-map-loader/) as per their documentation.

To all of you, please do come forward with a reproduction if you can create one. Thanks.

**Comment by millsp** [comment]
I was able to reproduce this issue with the instructions I left above
![image](https://github.com/prisma/prisma/assets/18401805/3cd4c0db-19f1-423f-b119-c033a6ae7d7f)

**Comment by jyannessa-mtx** [comment]
We ran into the same warning in our Nx monorepo when trying to migrate the generated prisma clients out of `node_modules` and into a `{projectRoot}/src/~generated` folder.

Thanks to @millsp and others for pointing us to the `source-map-loader`, our solution was to configure the `source-map-loader` webpack rule to ignore the `~generated` folder.

The `config.module.rules` value contains the following rule for `source_map_loader` by default
```js
{
    test: /\.js$/,
    enforce: 'pre',
    loader: '/Users/me/code/my-repo/node_modules/@nx/webpack/node_modules/source-map-loader/dist/cjs.js'
},
```
and we need to add the `exclude` property
```js
{
    test: /\.js$/,
    enforce: 'pre',
    loader: '/Users/me/code/my-repo/node_modules/@nx/webpack/node_modules/source-map-loader/dist/cjs.js',
    exclude: /~generated/
},
```

So our apps' `webpack.config.js` to accomplish the above:
```js
const { composePlugins, withNx } = require('@nx/webpack');

module.exports = composePlugins(withNx(), (config) => {
    // Find the rule that uses source-map-loader
    const sourceMapLoaderRule = config.module.rules.find((rule) =>
        rule.loader?.includes('source-map-loader')
    );

    // update the source-map-loader rule to exclude the ~generated directory
    if (sourceMapLoaderRule) {
        sourceMapLoaderRule.exclude = /~generated/;
    }
    return config;
});
```

**Comment by AntoninD-Galadrim** [comment]
We have this warning on our monorepo where we use the generated types in our vite React frontend, but none of the fixes make sense to me, can anyone explain the solution ?

**Comment by vabatta** [comment]
You are likely generating prisma code within a `src` folder which you will later transpile with your tooling (`swc`, `esbuild`, ...).

```
prisma/
  schema.prisma
src/
  @generated/prisma-client/**
  myapp.ts
  libs/
    mylib.ts
```

In this case, given you are likely doing something like this in your `schema.prisma`
```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../src/@generated/prisma-client"
}
```

You need to setup up your tooling to ignore and copy "as-is" the folder without additional transpilation, because you can't have source maps for generated code (where is the original code to map to if it has been generated?).

Example from our setup in a monorepo with SWC `.swcrc`
```jsonc
{
  "$schema": "https://swc.rs/schema.json",
  "sourceMaps": true, // Because you want source maps for your code
  "exclude": ["@generated/prisma-client"], // But not for generated one
  "jsc": {
    "parser": {
      "syntax": "typescript",
    }
  }
}
```

Set this up in your transpiler and you get rid of warnings.
