### ISSUE TITLE
Strange alpha/beta mismatch

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2116]
Installing the beta but get an error message that mentions `alpha` later:

```
λ npm install @prisma/cli -g

> @prisma/cli@2.0.0-beta.1 preinstall C:\Program Files\nodejs\node_modules\@prisma\cli
> node preinstall/index.js

  preinstall { installedGlobally: null } +0ms
C:\Program Files\nodejs\prisma2 -> C:\Program Files\nodejs\node_modules\@prisma\cli\build\index.js
C:\Program Files\nodejs\prisma -> C:\Program Files\nodejs\node_modules\@prisma\cli\build\index.js

> @prisma/cli@2.0.0-beta.1 install C:\Program Files\nodejs\node_modules\@prisma\cli
> node download-build/index.js

  getos { platform: 'win32', libssl: undefined } +0ms
  download { needsToBeDownloaded: true } +0ms
  download { needsToBeDownloaded: true } +2ms
  download { needsToBeDownloaded: true } +1ms
  download Downloading https://binaries.prisma.sh/master/2accb9c7eacdc984874eaeb63377fe705dfd3203/windows/prisma.exe.gz to C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\query-engine-windows.exe +4ms
> Downloading Prisma engines for windows [                    ] 0%  download Downloading zip +3ms
  download Downloading https://binaries.prisma.sh/master/2accb9c7eacdc984874eaeb63377fe705dfd3203/windows/introspection-engine.exe.gz to C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\introspection-engine-windows.exe +28ms
  download Downloading zip +2ms
  download Downloading https://binaries.prisma.sh/master/2accb9c7eacdc984874eaeb63377fe705dfd3203/windows/migration-engine.exe.gz to C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\migration-engine-windows.exe +7ms
  download Downloading zip +2ms
  cleanupCache Error: ENOENT: no such file or directory, scandir 'C:\Program Files\nodejs\node_modules\@prisma\cli\node_modules\.cache\prisma\alpha' +0ms
> Downloading Prisma engines for windows [===============     ] 74%  downloadZip Error: EPERM: operation not permitted, unlink 'C:\Users\Jan\AppData\Local\Temp\3efee176dfb125c9850abef71dccfa14'
  downloadZip     at Object.unlinkSync (fs.js:976:3)
  downloadZip     at Object.downloadZip (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:81606)
  downloadZip     at processTicksAndRejections (internal/process/task_queues.js:85:5)
  downloadZip     at async downloadBinary (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:213781)
  downloadZip     at async Promise.all (index 1)
  downloadZip     at async download (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:210414)
  downloadZip     at async main (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:84787) +0ms
> Downloading Prisma engines for windows [=================== ] 95%  downloadZip Error: EPERM: operation not permitted, unlink 'C:\Users\Jan\AppData\Local\Temp\a7106ec6669017bef55d25ce12c3cd1d'
  downloadZip     at Object.unlinkSync (fs.js:976:3)
  downloadZip     at Object.downloadZip (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:81606)
  downloadZip     at processTicksAndRejections (internal/process/task_queues.js:85:5)
  downloadZip     at async downloadBinary (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:213781)
  downloadZip     at async Promise.all (index 2)
  downloadZip     at async download (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:210414)
  downloadZip     at async main (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:84787) +1s
  downloadZip Error: EPERM: operation not permitted, unlink 'C:\Users\Jan\AppData\Local\Temp\bbe0207d74fff603ea35f53927f562ee'
  downloadZip     at Object.unlinkSync (fs.js:976:3)
  downloadZip     at Object.downloadZip (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:81606)
  downloadZip     at processTicksAndRejections (internal/process/task_queues.js:85:5)
  downloadZip     at async downloadBinary (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:213781)
  downloadZip     at async Promise.all (index 0)
  downloadZip     at async download (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:210414)
  downloadZip     at async main (C:\ProgramData\nvm\v12.6.0\node_modules\@prisma\cli\download-build\index.js:1:84787) +460ms
+ @prisma/cli@2.0.0-beta.1
added 1 package from 1 contributor in 7.102s

**Comment by pantharshit00** [comment]
Can you reliably reproduce this? 

As you can guess it is hard to reproduce for me.

**Comment by timsuchanek** [comment]
This is old cleanup code that made sure, that the cache directory is cleaned up properly. It came from times, where we used a `.cache/alpha` directory instead of a `.cache/master` directory. As we have this cleanup in place for a couple of months already and don't write to `.cache/alpha` since, it can be removed.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
