### ISSUE TITLE
Update: `InterpretationError("Unable to convert expression result into a set of selection results", None)`

### ISSUE THREAD

**Issue by trevorr** [prisma/prisma#21182]
### Bug description

After upgrading from Prisma 4.16.2 to 5.3.0, performing a complex update with many nested `upsert` and `connectOrCreate` results in the following error:

```
PrismaClientKnownRequestError:
Invalid `prisma.loan.update()` invocation:

Query interpretation error. Error for binding '603': Error occurred during query execution:
InterpretationError("Unable to convert expression result into a set of selection results", None)
    at wn.handleRequestError (.../packages/prisma-client/src/__generated__/PrismaClient/runtime/library.js:123:6730)
    at wn.handleAndLogRequestError (.../packages/prisma-client/src/__generated__/PrismaClient/runtime/library.js:123:6119)
    at wn.request (.../packages/prisma-client/src/__generated__/PrismaClient/runtime/library.js:123:5839)
    at async l (.../packages/prisma-client/src/__generated__/PrismaClient/runtime/library.js:128:9763)
```

This issue seemed to be the same as #20448, but that issue involves `relationMode = "prisma"` and MySQL, whereas this issue occurs with foreign keys and PostgreSQL.

### How to reproduce

I don't have a reproduction to share, since our schema has 229 models, and this update uses many of them. The generated update JSON is almost 5000 lines. Here is an trimmed down version representative of the whole:

```json
{
  "where": { "id": "bce93061-b5fa-4b4c-9242-687fe7993f75" },
  "data": {
    "baseLoanAmount": 656175419,
    "tridTriggeredAt": "2013-04-09T20:40:08.362Z",
    "blendSubmittedToOpsAt": "2022-01-02T05:54:24.161Z",
    "loanDownPayments": {
      "upsert": [
        {
          "where": { "id": "7733e420-1396-4c4e-885e-9b7b8446119a" },
          "update": { "giftTransferDate": "2020-01-01T00:00:00.000Z" },
          "create": {
            "id": "7733e420-1396-4c4e-885e-9b7b8446119a",
            "amount": 492700,
            "giftTransferDate": "2020-01-01T00:00:00.000Z"
            /* ... */
          }
        },
        {
          "where": { "id": "fdffe05e-b8a6-496b-af5a-26bf03f214cb" },
          "update": { "giftTransferDate": "2023-12-24T00:00:00.000Z" },
          "create": {
            "id": "fdffe05e-b8a6-496b-af5a-26bf03f214cb",
            "amount": 738573900,
            "giftTransferDate": "2023-12-24T00:00:00.000Z"
            /* ... */
          }
        }
      ]
    },
    "loanProduct": { /* ... */ },
    "loanPurchaseCredits": { /* ... */ },
    "loanFees": { /* ... */ },
    "loanPrepaidFees": { /* ... */ },
    "loanEscrowFees": { /* ... */ },
    "loanParties": { /* ... */ },
    "subjectProperty": {
      "upsert": {
        "update": {
          "propertyGroundLeaseExpiredAt": "2012-01-01T00:00:00.000Z"
        },
        "create": {
          "attachmentType": "Attached",
          "propertyProject": {
            "connectOrCreate": {
              "where": { "id": "112e6a59-4117-488a-b4a1-3135f52ffd7e" },
              "create": {
                "name": "Community Name",
                "designType": "GardenProject",
                "id": "112e6a59-4117-488a-b4a1-3135f52ffd7e"
              }
            }
          },
          "propertyGroundLeaseExpiredAt": "2012-01-01T00:00:00.000Z",
          /* ... */
          "id": "bc216582-1591-4113-902e-d22efaa0ac3b"
        }
      }
    },
    "monthlyPAndI": null
  }
}
```

### Expected behavior

The update should succeed, as it did against numerous Prisma 4.x versions.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["tracing"]
  output = "./__generated__/PrismaClient"
  binaryTargets = ["native", "linux-musl", "linux-musl-openssl-3.0.x"]
}

generator jsonSchema {
  provider = "prisma-json-schema-generator"
  output = "./__generated__/PrismaClient"
  keepRelationScalarFields = "true"
}

datasource postgresql {
  provider = "postgresql"
  url = env("DATABASE_URL")
}
```

### Environment & setup

- OS: macOS 13.5.2
- Database: PostgreSQL 15.2
- Node.js version: 16.20.0

### Prisma Version

```
prisma                  : 5.3.0
@prisma/client          : 5.3.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine e90b936d84779543cbe0e494bc8b9d7337fad8e4 (at ../../node_modules/.pnpm/@prisma+engines@5.3.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli e90b936d84779543cbe0e494bc8b9d7337fad8e4 (at ../../node_modules/.pnpm/@prisma+engines@5.3.0/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.3.0-36.e90b936d84779543cbe0e494bc8b9d7337fad8e4
Default Engines Hash    : e90b936d84779543cbe0e494bc8b9d7337fad8e4
Studio                  : 0.494.0
```

**Comment by def-ilya** [comment]
Experiencing this one as well. 
For our use case, we've got a an "update" clause, within which is a "create" or "upsert" clause that always fails. 

Also PostGres, but on remote. 

Here's a contrived example: 
```
        { id: userAcc.id },
        {
          AccountDetails: {
            update: {
              fieldToUpdate: { /*any form of create or upsert here fails*/ },
            },
          },
        }
```

**Comment by janpio** [comment]
If one could provide a reproduction we can run, that would be optimal.

**Comment by def-ilya** [comment]
Downgraded to 5.2.0, issue still occurs.

@janpio unfortunately we've got wrappers/middleware around Prisma client, not sure how helpful reproduction from us would be.

Again, apologies for this example, have to mask a wee bit, but I can tell you that removing our equivalent of friendsData stops the throw happening.

```
const friendsData = {
  create: {
    personalEmail: friend.email,
    PersonDetails: {
      create: {
        username: friend.name,
        personType: PersonType.FRIEND,
      },
    },
  },
}

await prisma.account.update(
  { id: userAcc.id },
  {
    AccountDetails: {
      update: {
        friends: friendsData,
      },
    },
  }
)

```

and in Prisma: 
```
model AccountDetails {
  id      String          @id @default(cuid())
  friends FriendDetails[] @relation("Friends")

  @@map("account_details")
}
```

**Comment by janpio** [comment]
Could you try to create a new app with this code and schema snippet and see if you can reproduce it this way? If you can't, we would also not be able to and hence would spendour time trying to make something happen, that can not happen.

**Comment by def-ilya** [comment]
> Could you try to create a new app with this code and schema snippet and see if you can reproduce it this way? If you can't, we would also not be able to and hence would spendour time trying to make something happen, that can not happen.

Thanks Jan.

>created new node-ts project
>init'd Prisma
>created new remote DB instance
>migrated schema from our project to DB
>created example update function that is identical in function to what we're trying to do
>runs without issue, correct output

Strange. Going to have a play around with swapping dev DB.

**Comment by def-ilya** [comment]
@trevorr 
Are you using data proxy? We are.

As an  update, used the working fresh instance's URL on the broken app. No luck there. So likely issue is with client. 
Glaring difference in the working vs non-working setup:
1. Working setup does not use data proxy
2. Working proxy was not upgraded from V3

**Comment by def-ilya** [comment]
Think we had a missing "where" clause in an upsert, possibly? I'm not 100% on this, I thought I tested an isolated example and with "create" exclusively. Worth checking in your situation @trevorr - Maybe V5 doesn't have an upsert default when "where" is missing.

**Comment by trevorr** [comment]
We're not using data proxy, and I'm pretty sure we don't have any missing where clauses. I really want a way to figure out what bind 603 is. Short of a breakthrough by someone else, it seems like we'll have to figure it how to build the Rust binary with enough tracing to figure out which part is triggering this invariant error.

**Comment by def-ilya** [comment]
> We're not using data proxy, and I'm pretty sure we don't have any missing where clauses. I really want a way to figure out what bind 603 is. Short of a breakthrough by someone else, it seems like we'll have to figure it how to build the Rust binary with enough tracing to figure out which part is triggering this invariant error.

@trevorr I had a rather short query, and I had "bind 2" as my error. It would have matched up to the second nested clause inside a query too. 
Maybe worth consideration? Is it possible you have 603 nested clauses within a single query?

**Comment by trevorr** [comment]
Yes, the query parameters are 5000 lines of JSON. We have many hundreds of test cases. Only the one 10-100x larger than the rest fails. 😅

**Comment by def-ilya** [comment]
@trevorr 🫡 Godspeed. Try delete one nested query and see if your bind # drops? If it does, it looks like you might have to get counting lol

**Comment by yovanoc** [comment]
https://github.com/yovanoc/prisma-repro

managed to get a repro guys <3

**Comment by yovanoc** [comment]
The problem occurs ONLY when multiple wrappedData are updated simultaneously. If you comment wrappedData1 or wrappedData2 in the update there is no issue

**Comment by janpio** [comment]
As far as I could figure out, this broke between 5.1.0 and 5.2.0:

````
PS C:\Users\Jan\Documents\throwaway\prisma-repro> pnpm prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (5.1.0 | library) to .\node_modules\.pnpm\@prisma+client@5.1.0_prisma@5.1.0\node_modules\@prisma\client in 191ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
PS C:\Users\Jan\Documents\throwaway\prisma-repro> pnpm run update

> prisma-repro@1.0.0 update C:\Users\Jan\Documents\throwaway\prisma-repro
> node ./dist/update.js

{ id: 'clmuoy62o0000gza728h6c80u' }
PS C:\Users\Jan\Documents\throwaway\prisma-repro> pnpm run update

> prisma-repro@1.0.0 update C:\Users\Jan\Documents\throwaway\prisma-repro
> node ./dist/update.js

{ id: 'clmuoy62o0000gza728h6c80u' }
PS C:\Users\Jan\Documents\throwaway\prisma-repro> pnpm run update

> prisma-repro@1.0.0 update C:\Users\Jan\Documents\throwaway\prisma-repro
> node ./dist/update.js

{ id: 'clmuoy62o0000gza728h6c80u' }
PS C:\Users\Jan\Documents\throwaway\prisma-repro> pnpm run update     

> prisma-repro@1.0.0 update C:\Users\Jan\Documents\throwaway\prisma-repro
> node ./dist/update.js

{ id: 'clmuoy62o0000gza728h6c80u' }
````

but:

````
PS C:\Users\Jan\Documents\throwaway\prisma-repro> pnpm prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma

✔ Generated Prisma Client (v5.2.0) to .\node_modules\.pnpm\@prisma+client@5.2.0_prisma@5.2.0\node_modules\@prisma\client in 112ms
Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client

PS C:\Users\Jan\Documents\throwaway\prisma-repro> pnpm run update

> prisma-repro@1.0.0 update C:\Users\Jan\Documents\throwaway\prisma-repro
> node ./dist/update.js

...

PrismaClientKnownRequestError:
Invalid `prisma.firstTable.update()` invocation:


Query interpretation error. Error for binding '4': Error occurred during query execution:
InterpretationError("Unable to convert expression result into a set of selection results", None)
    at vn.handleRequestError (C:\Users\Jan\Documents\throwaway\prisma-repro\node_modules\.pnpm\@prisma+client@5.2.0_prisma@5.2.0\node_modules\@prisma\client\runtime\library.js:123:6730)
    at vn.handleAndLogRequestError (C:\Users\Jan\Documents\throwaway\prisma-repro\node_modules\.pnpm\@prisma+client@5.2.0_prisma@5.2.0\node_modules\@prisma\client\runtime\library.js:123:6119)
    at vn.request (C:\Users\Jan\Documents\throwaway\prisma-repro\node_modules\.pnpm\@prisma+client@5.2.0_prisma@5.2.0\node_modules\@prisma\client\runtime\library.js:123:5839)
    at async l (C:\Users\Jan\Documents\throwaway\prisma-repro\node_modules\.pnpm\@prisma+client@5.2.0_prisma@5.2.0\node_modules\@prisma\client\runtime\library.js:128:9763) 
    at async file:///C:/Users/Jan/Documents/throwaway/prisma-repro/dist/update.js:4:15 {
  code: 'P2016',
  clientVersion: '5.2.0',
  meta: {
    details: "Error for binding '4': Error occurred during query execution:\n" +
      'InterpretationError("Unable to convert expression result into a set of selection results", None)'
  }
}
 ELIFECYCLE  Command failed with exit code 1.
````
 
 Can you confirm that?

**Comment by yovanoc** [comment]
>    Can you confirm that?

Yes!

**Comment by trevorr** [comment]
I can confirm that 5.1.0 works as well!

**Comment by janpio** [comment]
> The problem occurs ONLY when multiple wrappedData are updated simultaneously. If you comment wrappedData1 or wrappedData2 in the update there is no issue

@trevorr @def-ilya Does your query maybe also update two of the same models at the same time?

**Comment by def-ilya** [comment]
> @trevorr @def-ilya Does your query maybe also update two of the same models at the same time?

Confirming that it does in fact update two of the same models at the same time :)

**Comment by yharaskrik** [comment]
We are also experiencing this, it also happened once upgrading to 5.2.0

**Comment by jineshshah36** [comment]
I can also confirm that it happens for us as well on 5.4.x and has been happening since 5.2.x; however, it seems to happen for us even if we attempt to upsert multiple items for the same model

**Comment by thecodeboss** [comment]
I also ran into this issue. Initially tried downgrading to 5.1.0 but got hit with the enum bug in #20530. Luckily I tried with 5.1.1, and both this bug and the enum one are fixed for that version.

**Comment by yharaskrik** [comment]
Anyone try 5.5.0 yet?

**Comment by nangelina** [comment]
Yeah, the issue is still there in 5.5.0

**Comment by jineshshah36** [comment]
@janpio Is this bug being worked on? We would like to upgrade to the latest version and this is the primary blocker. We can workaround it, but it would require us rewriting a bunch of complex queries. If this is being worked on, we would rather just wait.

**Comment by janpio** [comment]
Not actively, but as it is a regression, it has high priority. Can't give you an ETA though. Might be 3 weeks, 6 weeks or longer.

**Comment by DmACKGL** [comment]
Oh, that's sad. This is the only thing holding us back from enjoying the latest features 😕

Hopefully, it gets fixed soon. Congrats to the team!

**Comment by wanjas** [comment]
One of the main features and the main way to do transactions in Prisma is "Nested writes" and now it is effectively broken for non-trivial cases. Broken in runtime without any type's warning.  

Am I misjudging it or it is the biggest issue possible, a literal show-stopper? 

I'm worried that the more new versions without a fix are released the more people are going to bump into this problem the hard way.

**Comment by yharaskrik** [comment]
Looks like it is still broken on 5.6.0 just so no one else needs to try it out.

**Comment by trevorr** [comment]
If it broke serverless databases, I bet it would get a lot more attention. 🤔 😭

**Comment by DmACKGL** [comment]
I cry every time I see "Requires Prisma 5.2+" :(

**Comment by wanjas** [comment]
> Looks like it is still broken on 5.6.0 just so no one else needs to try it out.

Yeah, it's absolutely broken in 5.6.0. 
One more super simple bug reproduction https://github.com/wanjas/prisma-nested-updates-bug

**Comment by AnthonyZhang220** [comment]
Any update on this issue? Running to the same error when updating two related tables simultaneously using nested upsert in 5.6.0 with pothos, without any type warnings.
```
builder.mutationFields((t) => ({
	updateProfile: t.prismaField({
		type: "User",
		args: {
			id: t.arg.string({ required: true }),
			displayName: t.arg.string(),
			bio: t.arg.string(),
			image: t.arg.string(),
			banner: t.arg.string(),
			avatar: t.arg.string(),
			city: t.arg.string(),
		},
		resolve: (query, parent, args, info) => {
			return prisma.user.update({
				...query,
				where: {
					id: args.id,
				},
				data: {
					displayName: args.displayName,
					image: args.image,
					profile: {
						upsert: {
							create: {
								bio: args.bio,
								banner: args.banner,
								avatar: args.avatar,
							},
							update: {
								bio: args.bio,
								banner: args.banner,
								avatar: args.avatar,
								location: {
									upsert: {
										create: {
											city: args.city,
										},
										update: {
											city: args.city,
										},
									},
								},
							},
						},
					},
				},
			});
		},
	}),
}));
```
