### ISSUE TITLE
"@prisma/client did not initialize yet" when using PrismaClient in symlinked external package

### ISSUE THREAD

**Issue by baconcheese113** [prisma/prisma#21194]
### Bug description

I'm creating an external package `external-package` for my NestJS application `my-app`

Inside of `external-package` I export a NestJS module `PrismaModule` which exports the `PrismaService` as defined here:
```ts
import { Injectable, OnModuleInit } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
    async onModuleInit() {
        await this.$connect();
    }
}
```

In `my-app` I import the `PrismaModule` globally in my `AppModule` and then inject the `PrismaService` into controllers farther down the hierarchy.

Everything works if:
1) The `PrismaModule` is located in `my-app`
2) `external-package` is published to npm and imported into `my-app`

However if I try to symlink `external-package` to `my-app` then I get the following error:
```
[Nest] 95473  - 09/22/2023, 12:28:00 PM   ERROR [ExceptionHandler] @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/Users/me/code/external-package/node_modules/.prisma/client/index.js:43:11)
    at new PrismaService (/Users/me/code/external-package/libs/shared/nest-common/src/lib/prisma/prisma.service.ts:5:8)
    at Injector.instantiateClass (/Users/me/code/external-package/node_modules/@nestjs/core/injector/injector.js:365:19)
    at callback (/Users/me/code/external-package/node_modules/@nestjs/core/injector/injector.js:65:45)
    at Injector.resolveConstructorParams (/Users/me/code/external-package/node_modules/@nestjs/core/injector/injector.js:144:24)
    at Injector.loadInstance (/Users/me/code/external-package/node_modules/@nestjs/core/injector/injector.js:70:13)
    at Injector.loadProvider (/Users/me/code/external-package/node_modules/@nestjs/core/injector/injector.js:97:9)
    at /Users/me/code/external-package/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 3)
    at InstanceLoader.createInstancesOfProviders (/Users/me/code/external-package/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
```

Is there a way to disable this error when symlinking `external-package` because the prisma client is only generated in `my-app`

### How to reproduce

1. Create new Nest project `my-app` with prisma schema and generated types
2. Create new Nest project `external-package`
3. Create `PrismaModule` and `PrismaService` in `external-package` with class definition above
4. Build and `npm link` from `external-package`
5. Symlink into `my-app` with `npm link external-package`
6. Import `PrismaModule` into `my-app`
7. Try to use `PrismaService` from `my-app`

### Expected behavior

I would expect the symlinked PrismaClient to work the same way as a published PrismaClient

### Prisma information

N/A

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: 16.19.0

### Prisma Version

```
prisma                  : 5.2.0
@prisma/client          : 5.2.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 2804dc98259d2ea960602aca6b8e7fdc03c1758f (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.2.0-25.2804dc98259d2ea960602aca6b8e7fdc03c1758f
Default Engines Hash    : 2804dc98259d2ea960602aca6b8e7fdc03c1758f
Studio                  : 0.494.0
```

**Comment by awooff** [comment]
Can confirm the bug is still present when other users develop [on my codebase](https://gitlab.com/kaelta/kwn)
The issue only seems to be present on Windows platforms, as I've tested on both MacOS and Linux without encountering the same problem.

## Steps to reproduce:

```bash
git clone https://github.com/kaelta/kwn
cd src/worker
pnpm i
pnpx prisma generate
pnpx dev
```

Returns:

```powershell

C:\Users\User\REPOS\kwn\src\worker\node_modules.pnpm@prisma+client@5.7.0_prisma@5.7.0\node_modules.prisma\client\index.js:43
    throw new Error(
    ^

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (C:\Users\User\REPOS\kwn\src\worker\node_modules.pnpm@prisma+client@5.7.0_prisma@5.7.0\node_modules.prisma\client\index.js:43:11)
    at new App (C:\Users\User\REPOS\kwn\src\worker\dist\worker.js:27:23)
    at Object.<anonymous> (C:\Users\User\REPOS\kwn\src\worker\dist\index.js:22:15)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
```

## Environment

+ **Windows**
+ **Node.js v20.10.0**
+ **pnpm**
+ **Prisma v5.7.0**

**Comment by anandbagmar** [comment]
Is there any workaround/solution to this issue? Thanks in advance!

**Comment by Jolg42** [comment]
@awooff I could reproduce using your repo.

Could you try to add this file `.npmrc` at the root with
```
strict-peer-dependencies=false
public-hoist-pattern[]=*prisma*
```
then run 
```
pnpm i
pnpx prisma generate
pnpm dev
```

Note that `pnpm i` in your repo might fail because it triggers `pnpm build` and because the Prisma Client might not be around, then `tsc, fails. TLDR: ignore and run the next commands.

**Comment by Doreapp** [comment]
For further readers, I had a similar issue, that was in fact produced by **having prisma client as dependency for two different pnpm packages, one as `dev` dependency and the other one as *main* dependency**. Thus `pnpm` was messing with `.prisma` folder location and symlink (or such). The workaround: using `prisma client` as *main* dependency for both.
