### ISSUE TITLE
Can't Prisma Generate on Docker 

### ISSUE THREAD

**Issue by medeiroshudson** [prisma/prisma#21241]
### Bug description

Trying to running `prisma generate` inside Docker container build, but it does not happen.
See console output:

It started some Prisma engine downloading, but gives up in about 1~2 seconds after started.
Nothing happens, and i can't prisma generate on container.

Running at my Windows macinhe (through WSL/ Ubuntu) it works fine.
Example repository: https://github.com/medeiroshudson/MiniCommerce

```
# ls
apps  bun.lockb  config  node_modules  package.json  packages  tsconfig.json  turbo.json
# bunx prisma generate
> Downloading Prisma engines for Node-API for debian-openssl-1.1.x [=======             ] 35%#
```

It always "fails" at some random percentage.

### How to reproduce

1 - Run docker container (see github repo)
2 - Exec `bunx prisma generate` inside container
3 - See nothing happening

### Expected behavior

Generating prisma client

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

Windows WSL
Docker
Bun 1.0.3

### Prisma Version

```
^5.3.1
```

**Comment by medeiroshudson** [comment]
The same occours when i run `prisma -v`

```
# bunx prisma -v
> Downloading Prisma engines for Node-API for debian-openssl-1.1.x [====                ] 19%#
```

**Comment by medeiroshudson** [comment]
Update: Got it working after install `nodejs` on docker container.
Is there some way to not depending nodejs binaries?

Maybe a feature request?
Thanks.

**Comment by TimoA200** [comment]
Thanks man, I had the exact same issue, while using Bun in combination with Prisma.
Installing node into the docker container worked for me as well.

**Comment by medeiroshudson** [comment]
You're welcome @TimoA200.
Glad to help you :)

**Comment by vutran-tvg** [comment]
I faced a similar issue when using Prisma with Bun. The prisma generate runs ok when I use bun but it's unable to create a Prisma client when running with docker. Tried to search around but didn't find any solution yet.

My workaround is to generate it locally with bun (in a non-docker environment) and then ship it with a docker image. Note that I work to change the output of the generator to a different location rather than the default inside node_module. It's help simplify the Dockerfile setup.

Here's my setup
**prisma.schema**
```
  provider      = "prisma-client-js"
  output        = "../generated/prisma-client" //Change output to custom path
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}
```

**Setup in Dockerfile**

```
WORKDIR /usr/src/app

COPY package*.json bun.lockb ./
RUN bun install
COPY . .

# If your `generated/prisma-client` is not in the Docker build context (the directory containing your Dockerfile), 
# you'll need to place it within the build context or adjust your project structure accordingly. E.g

ENV NODE_ENV production

CMD [ "bun", "start" ]
```
This solution works for me but it violates the docker concept to keep all the environment consistent and bring an additional step in the build process to generate client. Anw, it's good enough to go with current situation until I found better alternative or receive update from Prisma

**Comment by ZinoM21** [comment]
@vutran-tvg Worked for me too, thanks! yes, indeed a not very automated build process..

**Comment by m1212e** [comment]
Using the `imbios/bun-node` image seems to solve this problem. It contains node AND bun. https://github.com/ImBIOS/bun-node

**Comment by MataAzi** [comment]
Please consider fixing this!

**Comment by Licodeao** [comment]
A similar issue when I using docker.

**Comment by cholasimmons** [comment]
> Using the `imbios/bun-node` image works for me. It contains node AND bun. https://github.com/ImBIOS/bun-node

damn it's like 4 times the size!!

**Comment by janpio** [comment]
Can someone explain what goes wrong in the plain bun image without Node? The process just seems to die, which sounds very much like a bun problem and not something that Prisma is causing. Is there a way to get more output from `bunx`? Or some other way to invoke the Prisma CLI so that we see what causes `prisma generate` to just return?

**Comment by Syntarex** [comment]
I got no reproduction repo but got the same problem using `oven/bun:latest`
My repo: https://github.com/Syntarex/synbase

My Dockerfile:
```
# Nutze das offizielle Bun-Image
FROM oven/bun:latest as base
ENV TURBO_TELEMETRY_DISABLED=1
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
WORKDIR /usr/src/app

# Builde Projekt
FROM base AS build
COPY . ./
RUN bun install --frozen-lockfile
RUN bun run build

# Kopiere fertiges Projekt
FROM base AS release
COPY --from=build /usr/src/app /usr/src/app

# Starte NextJS
EXPOSE 3000/tcp
ENTRYPOINT ["bun", "run", "start"]
```

Line `RUN bun run build` starts up a turbo task to build my database- and web-package. The database-package's build script is `prisma generate`. Because the web-package depends_on the database-package, it should wait for the database-package to build. But it doesn't because `prisma generate` is not working correctly.

**Comment by cholasimmons** [comment]
Hold on guys, might have a fix .
Let me verify my build one more time...

**Comment by lukaswiklund** [comment]
> Hold on guys, might have a fix. Let me verify my build one more time...
> 
> ---EDIT---
> 
> Bun might be having a path finding issue. This worked for me. Edit your schema.prisma file
> 
> ```prisma
> generator client {
>    provider = "prisma-client-js"
>    output = "../generated"
>    binaryTargets = ["native", "debian-openssl-1.1.x"]
> }
> ```
> 
> Generate new definitions `bunx prisma generate`
> 
> Now your **generated** folder is in the root of your project. Use your IDE to search for **all** mentions of `"@prisma/client"` in your source code files, rename `"@prisma/client"` to `"generated"`
> 
> Be sure to copy over the generated folder into your Dockerfile

This does not work for us. Can you verify that you have added the `generated` directory to your `.dockerignore` so it doesn't just use the client you generated outside of Docker?

**Comment by cholasimmons** [comment]
I didn't add anything to .dockerignore. I fail to see how it's an issue where the folder is taken from, for as long as it works. No?
Every mention of `@prisma/client` in my project was changed to `generated` so it's definitely getting the one generated outside of docker, or within docker - doesn't matter, as it's location is relatively the same on the host and in the image.

I should try

**Comment by lukaswiklund** [comment]
> I didn't add anything to .dockerignore. I fail to see how it's an issue where the folder is taken from, for as long as it works. No? Every mention of `@prisma/client` in my project was changed to `generated` so it's definitely getting the one generated outside of docker, or within docker - doesn't matter, as it's location is relatively the same on the host and in the image.
> 
> I should try the same thing but maintaining the generated folder as the initial "@prisma/client", but! using openssl 1.1.x as the binaryTarget instead. I have a feeling this would work too.
> 
> N.B did you upgrade bun and Prisma to the latest?

The problem in this issue is that `prisma generate` does not work in Docker. If you do a `prisma generate` on your local machine and then build a Docker image the `generated` folder will be copied from your local machine into the Docker image. This means that the issue with `prisma generate` is not resolved but you instead just copy the folder over from your local development environment.

**Comment by cholasimmons** [comment]
Oh my oh my I totally overlooked that.
I guess many are using Bun in a docker image for development purposes.
I thought the struggle was for production 
My bad

**Comment by marvinruder** [comment]
> Can someone explain what goes wrong in the plain bun image without Node? The process just seems to die, which sounds very much like a bun problem and not something that Prisma is causing. Is there a way to get more output from `bunx`? Or some other way to invoke the Prisma CLI so that we see what causes `prisma generate` to just return?

@janpio There appears to have been some progress at Bun to resolve this but some issues still remain. I added more information in https://github.com/oven-sh/bun/issues/5320 including an easy-to-reproduce example.

**Comment by marvinruder** [comment]
Appears to be fixed in Bun 1.0.30

**Comment by garlab** [comment]
Still getting this with Bun 1.0.30 and prisma 5.10.2

**Comment by kabir-asani** [comment]
Prisma and BunJS don't particularly go well on Docker so here is a Dockerfile that'll solve your problems once and for all.

```Dockerfile
# > 1. OS SET UP --
FROM ubuntu:22.04

# > 1.a -- Install various essential dependencies
RUN apt-get update && apt-get install -y curl gnupg zip unzip

# > 1.b Install NodeJS
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

# > 1.c Install BunJS
ENV BUN_INSTALL=$HOME/bun
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH=$PATH:$HOME/bun/bin

# > 2. PROJECT SET UP --
# > 2.a -- Set up working directory for the project 
WORKDIR /app

# > 2.b -- Copy essential dependency specification files
COPY package.json .
COPY bun.lockb .
COPY tsconfig.json .
COPY prisma prisma

# > 2.c -- Install dependencies
RUN bun install

# > 2.d -- Run prisma codegen
RUN bunx prisma generate

# > 2.e -- Copy essential files and folders
COPY src src

# > 2.f -- Set up various environment variables
ENV PORT 8080

# > 3. RUN PROJECT --
# > 3.a -- Expose various ports as necessary
EXPOSE 8080

# > 3.b -- Run
CMD ["bun", "start"]
```

--

[Dockerfile as GitHub Gist](https://gist.github.com/kabir-asani/60da540c883480b9be86866c876948f1)

**Comment by cholasimmons** [comment]
This issue has lasted longer than I expected, isn't Prisma + Docker a popular choice of development?
I really had to test my Bun app in production mode, and inside a Docker Container so I had to use a workaround.

### Temporal Workaround
From my local computer (Windows) I switched the binaryTargets of the `schema.prisma` file to debian-openssl-1.1.x then executed `bunx prisma generate`, I then had to copy the folders **.prisma** and **@prisma** from **node_modules**, to the root directory of my project (I'm sure copying only one of these would have sufficed)
Then in Dockerfile I add a line that COPY's these 2 folders into the generated node_modules inside the image.

Also the database migrations - I manually had to injected the migration.sql file as Docker denied me permission to run bunx prisma commands,

not a pretty process but this got the project running with 0 errors.

Check the project on my GitHub: [Just.Chola](https://github.com/cholasimmons/elysia_lucia_prisma_server)

**Comment by fzn0x** [comment]
```Dockerfile
FROM oven/bun:1 as base
```

For my issue, I already set debian-openssl-1.1.x to binaryTargets, but still get the same errors

```sh
Prisma Client could not locate the Query Engine for runtime "debian-openssl-1.1.x".

This happened because Prisma Client was generated for "windows", but the actual deployment required "debian-openssl-1.1.x".
Add "debian-openssl-1.1.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:

generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}

The following locations have been searched:
  /usr/src/app/node_modules/.prisma/client
  /usr/src/app/node_modules/@prisma/client
  D:\number-website\node_modules\@prisma\client
  /tmp/prisma-engines
  /usr/src/app/prisma
      at new e (/usr/src/app/node_modules/@prisma/client/runtime/library.js:22:1872)
      at handleRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:122:7154)
      at handleAndLogRequestError (/usr/src/app/node_modules/@prisma/client/runtime/library.js:122:6183)
      at /usr/src/app/node_modules/@prisma/client/runtime/library.js:122:5891
```

**Comment by yainakrub** [comment]
I can't build while prisma is not connected to the database [nextjs]

PrismaClientInitializationError: 
#17 55.06 Invalid prisma.log_sms.count() invocation:

**Comment by wrspada02** [comment]
> I faced a similar issue when using Prisma with Bun. The Prisma generate runs ok when I use bun but it's unable to create a Prisma client when running with docker. Tried to search around but didn't find any solution yet.
> 
> My workaround is to generate it locally with bun (in a non-docker environment) and then ship it with a docker image. Note that I work to change the output of the generator to a different location rather than the default inside node_module. It helps simplify the Dockerfile setup.
> 
> Here's my setup **prisma.schema**
> 
> ```
>   provider      = "prisma-client-js"
>   output        = "../generated/prisma-client" //Change output to custom path
>   binaryTargets = ["native", "debian-openssl-1.1.x"]
> }
> ```
> 
> **Setup in Dockerfile**
> 
> ```
> WORKDIR /usr/src/app
> 
> COPY package*.json bun.lockb ./
> RUN bun install
> COPY . .
> 
> # If your `generated/prisma-client` is not in the Docker build context (the directory containing your Dockerfile), 
> # you'll need to place it within the build context or adjust your project structure accordingly. E.g
> 
> ENV NODE_ENV production
> 
> CMD [ "bun", "start" ]
> ```
> 
> This solution works for me but it violates the docker concept to keep the environment consistent and bring an additional step in the build process to generate clients. In my case, it's good enough to go with the current situation until I find a better alternative or receive an update from Prisma.
> 
> Note that the Prisma client runs differently on different OS so the deployment needs to be tested carefully

Thank you! Looks good now.

**Comment by wrspada02** [comment]
Thanks @vutran-tvg . Looks good now. Damn, didn't know bun got this issue.

**Comment by kaiyan910** [comment]
I found that only some of the version will trigger the problem, the latest (v5.21.0) does not work but (v5.20.0) works, so I decided to keep using v5.20.0 ATM, I tried https://github.com/oven-sh/bun/issues/5320#issuecomment-2166824602 method too it works but the image will become very large (~x1.5)

for those have the same problem here is my setup

```prisma
generator client {
  provider      = "prisma-client-js"
  output        = "./client"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Task {
  id        Int      @id @default(autoincrement())
  title     String
  done      Boolean
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map("task")
}
```

```json
{
	"name": "hono-boilerplate",
	"version": "1.0.0",
	"scripts": {
		"build": "bun build --minify-whitespace --minify-syntax --target bun --outdir ./dist ./src/index.ts",
		"start": "bunx prisma@5.20.0 migrate deploy && bun ./dist/index.js",
		"dev": "bun run --hot src/index.ts",
		"db:generate": "prisma generate",
		"biome": "biome format && biome lint"
	},
	"dependencies": {
		"@hono/zod-openapi": "0.16.4",
		"@hono/zod-validator": "0.4.1",
		"@prisma/client": "5.20.0",
		"@scalar/hono-api-reference": "0.5.153",
		"chalk": "5.3.0",
		"croner": "8.1.2",
		"hono": "4.6.3",
		"ky": "1.7.2",
		"moment": "2.30.1",
		"zod": "3.23.8"
	},
	"devDependencies": {
		"@biomejs/biome": "1.9.4",
		"@types/bun": "latest",
		"prisma": "5.20.0"
	}
}
```
```dockerfile
FROM oven/bun:debian AS build

WORKDIR /app

COPY package.json package.json
COPY bun.lockb bun.lockb

RUN bun install

COPY ./src ./src
COPY ./prisma ./prisma
COPY ./tsconfig.json ./tsconfig.json

RUN bun run db:generate
RUN bun run build

FROM oven/bun:debian

WORKDIR /app

COPY --from=build /app/prisma ./prisma
COPY --from=build /app/dist/index.js ./dist/index.js
COPY --from=build /app/package.json ./package.json

CMD ["bun", "start"]
```

**Comment by ghafarizar** [comment]
I faced the exact same issue as this. My intention was to migrate old Nodejs Version of a codebase to Bun with upgrading all of the library and leave Node out of the dependencies. There is some issue regarding on Docker builds related to package of `prisma`, `@prisma/config` (NOTE: this shouldn't work for someone that uses `migrate` command as it needs the `@prisma/config` package to specify the DATABASE URL). If you are using the Prisma like me, only for DB connection and typing, then use the `@prisma/client` only will works out of the box.

workaround by @the-dream-machine is not really visible as it's adding a Node runtime in the Docker which is not the goal of using Bun really
