### ISSUE TITLE
[Beta1]nested entity create& connect Error

### ISSUE THREAD

**Issue by zzyyzz1992** [prisma/prisma#2130]
Version: Beta1
Env: Win10 WSL2 VSCode Mysql

> 
> (node:632) UnhandledPromiseRejectionWarning: Error: 
> Invalid `prisma.image.create()` invocation in
> /mnt/c/Users/zzyyz/Code/CheckinDesk/server/index.ts:249:59
> 
> Error occurred during query execution:
> InterpretationError("Error for binding \'1\': DomainError(ConversionFailure(\"record identifier\", \"assimilated record identifier\"))")
>     at PrismaClientFetcher.request (/mnt/c/Users/zzyyz/Code/CheckinDesk/server/node_modules/@prisma/client/runtime/index.js:1:51485)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> warning.js:27
> (node:632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> warning.js:27
> (node:632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zzyyzz1992** [comment]
Model Def:
```

model Meeting {
    id        Int   @id @default(autoincrement())
    name      String 
    attendee  User[] @relation("UserMeeting",references:[id])
    createdAt   DateTime @default(now())
}

model User {
    id        Int   @id @default(autoincrement())
    createdAt   DateTime @default(now())
    attendedMeetings Meeting[] @relation("UserMeeting",references:[id])

    name  String
    idCardNo String @unique
  sex String
  nation String?
  birth String?
  address String?
  authority String? 
  validDate String?
  headB64 String?

  phoneNo String?
  remark String?

  images Image[]
}
model UserMeeting {
  meeting Meeting @relation(fields: [meetingId], references: [id])
  meetingId Int
  user User @relation(fields: [userId], references: [id])
  userId Int
  
  checkinTime DateTime @default(now())
  roomNo String?

  remark String?
  @@id([meetingId, userId])
}
enum ImageType {
  ID1
  ID2
  PassCard
  OTHER
}
model Image {
  id        Int   @id @default(autoincrement())
  user User?
  type ImageType
  base64Data String // TEXT?? mediumtext
  createdAt   DateTime @default(now())
}
```

**Comment by zzyyzz1992** [comment]
Related Code:
```
const {ImageBase64, meetingId} = req.body;
    ocrRequest.from_json_string(JSON.stringify({ImageBase64, CardSide: "FRONT"})); 
    ocrClient.IDCardOCR(ocrRequest, async function(errMsg: any, response: any ) {
        if (errMsg) {
            console.log(errMsg);
            res.json({result: false, info: errMsg});
            return;
        }
        console.log(response.to_json_string());
        const {IdNum, Name, Sex, Nation, Birth, Address, RequestId} = response;
        console.log(IdNum);
        const user = await prisma.user.upsert({
          where: { idCardNo: IdNum },
          create: { 
            idCardNo:IdNum, 
            name: Name, 
            sex: Sex, 
            nation: Nation, 
            birth: Birth, 
            address: Address,
            authority: "",
            validDate: "",
            headB64: ""
          },
          update:{
            name: Name, 
            sex: Sex, 
            nation: Nation, 
            birth: Birth, 
            address: Address
          }
        });
        const userMeeting = await prisma.userMeeting.upsert({
          where:{
            meetingId_userId: {
              meetingId: meetingId,
              userId: user.id
            }
          },
          create: {
            meeting:{ connect: { id: meetingId}},
            user: { connect: {id: user.id}},
          },
          update: {
            meeting:{ connect: { id: meetingId}},
            user: { connect: {id: user.id}}
          }
        })
        await prisma.image.create({
          data: {
            type: ImageType.ID1,
            base64Data: ImageBase64,
            user: {
              connect: {id: user.id}
            }
          }
        })
        res.json({
          result: true,
          userId: user.id
        })
    });
```

**Comment by zzyyzz1992** [comment]
BTW, I manually changed the imgae.base64Data's type to mediumtext in mysql

**Comment by zzyyzz1992** [comment]
Problem solved!
Inspired by #2029 's @jayanth1991 's answer
For guys who have same issue,
Read the "New syntax for defining relations"
