### ISSUE TITLE
Error validating datasource `db`: the URL must start with the protocol `prisma://`

### ISSUE THREAD

**Issue by FireTonnor** [prisma/prisma#21353]
### Bug description

PrismaClientKnownRequestError:
Invalid `prisma.users.findUnique()` invocation:

Error validating datasource `db`: the URL must start with the protocol `prisma://`
    at Jn.handleRequestError (C:\Users\shawn\WebstormProjects\discord_listener\node_modules\@prisma\client\runtime\edge.js:36:7072)
    at Jn.handleAndLogRequestError (C:\Users\shawn\WebstormProjects\discord_listener\node_modules\@prisma\client\runtime\edge.js:36:6460)
    at Jn.request (C:\Users\shawn\WebstormProjects\discord_listener\node_modules\@prisma\client\runtime\edge.js:36:6158)
    at async u (C:\Users\shawn\WebstormProjects\discord_listener\node_modules\@prisma\client\runtime\edge.js:41:10106) {
  code: 'P5002',
  clientVersion: '5.3.1',
  meta: undefined
}

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
"prisma": "^5.4.0"
```

**Comment by FireTonnor** [comment]
@janpio No i just started using it today and for the database i am trying to connect to is mysql
