### ISSUE TITLE
Invalid `….findMany()` invocation: The column `j1.id` does not exist in the current database.

### ISSUE THREAD

**Issue by marvinruder** [prisma/prisma#21352]
### Bug description

After updating to 5.4.0, the following error is shown when running the command provided below with the schema provided below:

```
prisma:query SELECT "public"."Post"."id" FROM "public"."Post" LEFT JOIN "public"."User" AS "j1" ON ("j1"."email") = ("public"."Post"."email") WHERE ("j1"."email" = $1 AND ("j1"."id" IS NOT NULL)) OFFSET $2
prisma:error 
Invalid `prisma.post.findMany()` invocation in
…/prisma21352/src/index.ts:14:33
…
→ 14 console.log(await prisma.post.findMany(
The column `j1.id` does not exist in the current database.
```

### How to reproduce

**See also: https://github.com/marvinruder/prisma21352**

Run
```js
await prisma.post.findMany({
  select: {
    id: true,
  },
  where: {
    user: {
      email: 'alice@example.com',
    }
  }
})
```
with client generated from the provided schema. 

### Expected behavior

All `watchlist` rows related to the specified user (identified by their email) are returned.

### Prisma information

```prisma
// Add your schema.prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  email String      @id @db.VarChar(255)
  posts Post[]
}

model Post {
  id    Int     @id @default(autoincrement())
  user  User    @relation(fields: [email], references: [email], onUpdate: Cascade, onDelete: Cascade)
  email String  @db.VarChar(255)
}
```

```ts
// Add your code using Prisma Client
await prisma.post.findMany({
  select: {
    id: true,
  },
  where: {
    user: {
      email: 'alice@example.com',
    }
  }
})
```

### Environment & setup

- OS: occurring on macOS 14.0 (build 23A344) and in `node:20.8.0-alpine` Docker image
- Database: PostgreSQL
- Node.js version: 20.8.0

### Prisma Version

```
prisma                  : 5.4.0
@prisma/client          : 5.4.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine a5596b96668f0f4b397761ce0956db54e17e48c4 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli a5596b96668f0f4b397761ce0956db54e17e48c4 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.4.0-47.a5596b96668f0f4b397761ce0956db54e17e48c4
Default Engines Hash    : a5596b96668f0f4b397761ce0956db54e17e48c4
Studio                  : 0.494.0
```

**Comment by chrishoermann** [comment]
same here:

```The column `j1.id` does not exist in the current database```

for query:

```ts
  const data = await prisma.$transaction([
    prisma.company.count({
      where: {
        isInStates: {
          stateRefNumber,
        },
      },
    }),
    prisma.state.count({
      where: {
        stateRefNumber,
      },
    }),
    prisma.district.count({
      where: {
        stateRefNumber,
      },
    }),
    prisma.city.count({
      where: {
        district: {
          stateRefNumber,
        },
      },
    }),
  ]);
```

complete Log:

````
prisma:query SELECT 1
prisma:query BEGIN
prisma:query DEALLOCATE ALL
prisma:query SELECT COUNT(*) FROM (SELECT "public"."Company"."id" FROM "public"."Company" LEFT JOIN "public"."State" AS "j1" ON ("j1"."stateRefNumber") = ("public"."Company"."stateRefNumber") WHERE ("j1"."stateRefNumber" = $1 AND ("j1"."id" IS NOT NULL)) OFFSET $2) AS "sub"
prisma:query ROLLBACK
prisma:error
Invalid `prisma.company.count()` invocation:


The column `j1.id` does not exist in the current database.
prisma:error The column `j1.id` does not exist in the current database.    
prisma:error The column `j1.id` does not exist in the current database.    
prisma:error The column `j1.id` does not exist in the current database.    
- error Error [PrismaClientKnownRequestError]: 
Invalid `prisma.company.count()` invocation:
```

**Comment by Eldemarkki** [comment]
I get the same error:
```ts
  return await prisma.recipesOnCollections.findMany({
    where: {
      recipeId,
      recipeCollection: {
        userId,
      },
    },
    include: {
      recipeCollection: {
        select: {
          id: true,
          name: true,
        },
      },
    },
  });
```

Error:
```
The column `j1.recipeId` does not exist in the current database.
    at Cn.handleRequestError (/home/eetu/recipeamigo/node_modules/@prisma/client/runtime/library.js:123:6817)
    at Cn.handleAndLogRequestError (/home/eetu/recipeamigo/node_modules/@prisma/client/runtime/library.js:123:6206)
    at Cn.request (/home/eetu/recipeamigo/node_modules/@prisma/client/runtime/library.js:123:5926)
    at async l (/home/eetu/recipeamigo/node_modules/@prisma/client/runtime/library.js:128:9968)
    at async getUserRecipeCollectionRelationships (webpack-internal:///./src/database/collections.ts:255:12)
    at async Object.handler (webpack-internal:///./src/dataLoaders/recipes/recipePageDataLoader.ts:38:38)
    at async loadProps (webpack-internal:///./src/dataLoaders/loadProps.ts:37:29) {
  code: 'P2022',
  clientVersion: '5.4.0',
  meta: { column: 'j1.recipeId' },
  page: '/recipe/4d118be3-6f12-45d6-97e7-1f37c1fa9020'
}
```

Relevant parts of schema:
```prisma
model Recipe {
  id                         String                 @id @default(uuid())
  name                       String
  description                String
  createdAt                  DateTime               @default(now())
  updatedAt                  DateTime               @updatedAt
  userId                     String
  user                       UserProfile            @relation(fields: [userId], references: [clerkId])
  ingredientSections         IngredientSection[]
  instructions               Instruction[]
  quantity                   Int
  visibility                 RecipeVisibility
  viewCount                  Int                    @default(0)
  timeEstimateMinimumMinutes Int                    @default(0)
  timeEstimateMaximumMinutes Int?
  coverImageName             String?
  likes                      Like[]
  tags                       Tag[]
  RecipesOnCollections       RecipesOnCollections[]
}

model RecipeCollection {
  id                   String                     @id @default(uuid())
  name                 String
  description          String?
  userId               String
  user                 UserProfile                @relation(fields: [userId], references: [clerkId])
  createdAt            DateTime                   @default(now())
  updatedAt            DateTime                   @updatedAt
  RecipesOnCollections RecipesOnCollections[]
  visibility           RecipeCollectionVisibility
}

model RecipesOnCollections {
  recipeId           String
  recipe             Recipe           @relation(fields: [recipeId], references: [id], onDelete: Cascade)
  recipeCollectionId String
  recipeCollection   RecipeCollection @relation(fields: [recipeCollectionId], references: [id], onDelete: Cascade)
  createdAt          DateTime         @default(now())

  @@id([recipeId, recipeCollectionId])
}

```

**Comment by janpio** [comment]
Thanks for the issue and comments, that does not look good. Seems one of the recent performance improvements did have bad side effects.

@chrishoermann Can you share the relevant models from your schema that are involved in the problematic query, please?
@Eldemarkki Can you enable query logging and also share the query that is failing?

**Comment by Eldemarkki** [comment]
I think this is it
```log
prisma:query SELECT "public"."RecipesOnCollections"."recipeId", "public"."RecipesOnCollections"."recipeCollectionId", "public"."RecipesOnCollections"."createdAt" FROM "public"."RecipesOnCollections" LEFT JOIN "public"."RecipeCollection" AS "j1" ON ("j1"."id") = ("public"."RecipesOnCollections"."recipeCollectionId") WHERE ("public"."RecipesOnCollections"."recipeId" = $1 AND ("j1"."userId" = $2 AND ("j1"."recipeId" IS NOT NULL AND "j1"."recipeCollectionId" IS NOT NULL))) OFFSET $3
```

**Comment by janpio** [comment]
Yes, thank you. That confirms that Prisma is now using a field name as a field in a query where that field does not actually exist. We'll have to fix that as soon as possible.

**Comment by chrishoermann** [comment]
part of my schema

```prisma

generator client {
    provider        = "prisma-client-js"
}

generator zod {
    provider                         = "zod-prisma-types"
    useMultipleFiles                 = true
    createOptionalDefaultValuesTypes = true
    createRelationValuesTypes        = true
    writeNullishInModelTypes         = true
    addSelectType                    = false
    addIncludeType                   = false
}

datasource db {
    provider  = "postgresql"
    url       = env("POSTGRES_PRISMA_URL") // uses connection pooling
    directUrl = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
}


// CITY
//------------------------------------------------------

/// City => "Ort/Stadt"
model City {
    cityRefNumber      String    @id /// Gemeindekennziffer 
    city               String
    zipCode            String
    additionalZipCodes String[]
    districtRefNumber  String /// foreignKey
    villages           Village[] // villages connected to this city
    district           District  @relation(fields: [districtRefNumber], references: [districtRefNumber])

    companies          Company[] // companies that have a license for this city
    applicantAddresses ApplicantAddress[]

    @@unique([cityRefNumber, districtRefNumber])
}

// DISTRICT
//------------------------------------------------------

/// District => "Bezirk"
model District {
    districtRefNumber String @id /// "Bezirkskennzahl" 
    district          String @unique
    stateRefNumber    String /// foreignKey
    cities            City[]
    state             State  @relation(fields: [stateRefNumber], references: [stateRefNumber])

    companies Company[] // companies that have a license for this district

    @@unique([districtRefNumber, stateRefNumber])
}

// STATE
//------------------------------------------------------

/// State => "Bundesland"
model State {
    stateRefNumber String     @id /// "Bundeslandkennzahl"
    state          String     @unique
    countryCode    String /// foreignKey
    districts      District[]
    country        Country    @relation(fields: [countryCode], references: [countryCode])
    Company        Company[]

    @@unique([stateRefNumber, countryCode])
}

// COUNTRY
//------------------------------------------------------

/// Country => "Staat"
model Country {
    countryCode String  @id
    country     String  @unique
    states      State[]
}

/////////////////////////////////////////
// COMPANY DATA
/////////////////////////////////////////

// @zod.import(["import validator from "validator";"])
model Company {
    id String @id @default(cuid())

    companyName           String?
    registeredCompanyName String?
    lastName              String?
    firstName             String?
    postGraduateTitle     String?
    title                 String?
    email                 String? /// @zod.string.email()
    homepage              String?
    phoneNumber           String?
    mobilePhone           String?
    faxNumber             String?
    street                String
    houseNumber           String
    houseNumberAddition   String?
    zipCode               String
    city                  String
    cityRefNumber         String?
    villageRefNumber      String?
    stateRefNumber        String?
    latitude              Float?
    longitude             Float?
    vacantJobs            Int? /// @zod.custom.use(z.union([z.number(), z.nan()]).transform((v) => (Number.isNaN(v) ? null : v)).optional()) 

    userId        String?
    user          User?              @relation(fields: [userId], references: [id])
    isInCity      City?              @relation(fields: [cityRefNumber], references: [cityRefNumber])
    isInVillage   Village?           @relation(fields: [villageRefNumber], references: [villageRefNumber])
    isInDistricts District[]
    isInStates    State?             @relation(fields: [stateRefNumber], references: [stateRefNumber])
    applicants    CompetitionEntry[]
}
```

**Comment by janpio** [comment]
Thanks, that also confirms the same problem @chrishoermann 👍

**Comment by marvinruder** [comment]
A minimal reproduction repository is now provided at https://github.com/marvinruder/prisma21352.

**Comment by janpio** [comment]
Thanks, we have a confirmed reproduction internally as well.

**Comment by janpio** [comment]
We are working on a fix now and hope to release it as a patch soon.

**Comment by janpio** [comment]
(Reopening until the patch release is actually out)

**Comment by millsp** [comment]
Hey everyone :wave: and thanks for your reports. The fix is now available in our latest patch release. https://github.com/prisma/prisma/releases/tag/5.4.1

**Comment by janpio** [comment]
Hey @marvinruder @Eldemarkki @chrishoermann, although we are pretty confident we fixed the problem, we would love if you could try out 5.4.1 and report back if this indeed fixed the problem for you. Thank you.

**Comment by marvinruder** [comment]
> Hey @marvinruder @Eldemarkki @chrishoermann, although we are pretty confident we fixed the problem, we would love if you could try out 5.4.1 and report back if this indeed fixed the problem for you. Thank you.

Yes, everything works fine after upgrading to 5.4.1 in my project. Thanks for the quick patch!

**Comment by chrishoermann** [comment]
Works on my end too! Thanks!

**Comment by Eldemarkki** [comment]
Works for me also, thanks!
