### ISSUE TITLE
The column `j2.organizationId` does not exist in the current database after upgrading to 5.4.0

### ISSUE THREAD

**Issue by rcbevans** [prisma/prisma#21359]
### Bug description

I was running validation of our product after doing a package bump and code that's unchanged in months is now throwing prisma runtime errors.

```
  26 async (req, res) => {
  27   const { skip, limit } = req.query;
→ 28   const orgs = await prisma.organization.findMany(
The column `j2.organizationId` does not exist in the current database.
    at Cn.handleRequestError (/home/rich/source/meetingplan/packages/server/dist/node_modules/@prisma/client/runtime/library.js:123:6817)
    at Cn.handleAndLogRequestError (/home/rich/source/meetingplan/packages/server/dist/node_modules/@prisma/client/runtime/library.js:123:6206)
    at Cn.request (/home/rich/source/meetingplan/packages/server/dist/node_modules/@prisma/client/runtime/library.js:123:5926)
    at l (/home/rich/source/meetingplan/packages/server/dist/node_modules/@prisma/client/runtime/library.js:128:9968)
    at /home/rich/source/meetingplan/packages/server/src/services/PrismaService.ts:26:14
    at /home/rich/source/meetingplan/packages/server/src/routes/OrganizationsRoutes.ts:28:18
```

There have been no changes to the schema, or code other than a simple package bump.

The error is correct that there is no column `j2.organizationId` on any table in the database so there appears to be something broken in the query generation for the join between the `Organization` and `OrganizationUserMembership` in the query.

### How to reproduce

I have provided the relevant schema and code.  Trying to use this with 5.4.0 is broken.

### Prisma information

```prisma
model Organization {
  id                                       Int                                       @id @default(autoincrement())
  createdAt                                DateTime                                  @default(now())
  updatedAt                                DateTime?
  slug                                     String                                    @unique
  name                                     String
  defaultVisibility                        MeetingflowVisibility                     @default(ORGANIZATION)
  type                                     OrganizationType                          @default(TRIAL)
  memberships                              OrganizationMembership[]

  @@index([slug])
}

model OrganizationMembership {
  id             Int                  @default(autoincrement())
  createdAt      DateTime             @default(now())
  updatedAt      DateTime?
  role           OrganizationUserRole
  organizationId Int
  organization   Organization         @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  userId         Int
  user           User                 @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@id([id, organizationId])
  @@unique([organizationId, userId])
  @@index([userId])
  @@index([organizationId])
  @@index([organizationId, role])
  @@index([userId, organizationId])
}

```

```ts
  export const DefaultOrganizationSelection = {
    id: true,
    createdAt: true,
    updatedAt: true,
    slug: true,
    name: true,
    defaultVisibility: true,
  } satisfies Prisma.OrganizationSelect;

const prisma = new PrismaClient({
  log: ['warn', 'error'],
});

prisma.$use(async (params, next) => {
  const ctx: CorrelationContext | null =
    Telementry.appInsights.getCorrelationContext();
  const before = Date.now();

  let success = false;
  let exception: unknown;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let result: any = null;
  try {
    result = await next(params);
    success = true;
  } catch (err: unknown) {
    exception = err;
    serviceLogger.error(err);
  }

  const after = Date.now();

  if (!!params.model && !!params.action) {
    Telementry.client?.trackDependency({
      target: 'postgres',
      name: `${params.model}.${params.action}`,
      data: ctx ? ctx.operation.name : '',
      duration: after - before,
      dependencyTypeName: 'prisma',
      resultCode: '',
      success,
    });
  }

  if (exception) {
    throw exception;
  }

  return result;
});


    const orgs = await prisma.organization.findMany({
      where: {
        memberships: {
          some: {
            user: {
              id: req.userId,
            },
          },
        },
      },
      select: Selections.DefaultOrganizationSelection,
      orderBy: {
        createdAt: 'asc',
      },
      skip,
      take: limit,
    });
```

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: v18.17.1

### Prisma Version

```
prisma                  : 5.4.0
@prisma/client          : 5.4.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine a5596b96668f0f4b397761ce0956db54e17e48c4 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli a5596b96668f0f4b397761ce0956db54e17e48c4 (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.4.0-47.a5596b96668f0f4b397761ce0956db54e17e48c4
Default Engines Hash    : a5596b96668f0f4b397761ce0956db54e17e48c4
Studio                  : 0.494.0
Preview Features        : fullTextIndex, fullTextSearch
```

**Comment by Eldemarkki** [comment]
Sounds like a duplicate of #21352

**Comment by rcbevans** [comment]
@Eldemarkki you're right.  I didn't spot that one before filing.  I'll close this
