### ISSUE TITLE
prisma 5.4.1 - planetscale driver adapter - fetch failed

### ISSUE THREAD

**Issue by sbkl** [prisma/prisma#21364]
Please see the detailed setup below. Anything I am doing wrong? I cleared all node-modules in my monorepo and reinstalled everything but no luck:

Using prisma in a db package in a monorepo.

Updated the prisma schema and generated the new prisma client:
```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}
```

Creating the prisma instance as follow:
```
import { PrismaClient } from "@prisma/client";
import { connect } from "@planetscale/database";
import { PrismaPlanetScale } from "@prisma/adapter-planetscale";
import { fetch as undiciFetch } from "undici";

declare global {
  // allow global `var` declarations
  // eslint-disable-next-line no-var
  var prisma: PrismaClient | undefined;
}

// Initialize Prisma Client with the PlanetScale serverless database driver. I double checked the env variable was returning the right connectionString.

const connection = connect({
  url: process.env.DATABASE_URL,
  fetch: undiciFetch,
});

const adapter = new PrismaPlanetScale(connection);

export const prisma =
  global.prisma ||
  new PrismaClient({
    adapter,
  });

export * from "@prisma/client";

if (process.env.NODE_ENV !== "production") {
  global.prisma = prisma;
}
```

This is the error I get when trying to fetch with my nextjs app using trpc and react query:
```
⨯ TypeError: fetch failed
   at fetch (/Users/sbkl/app/beebook/node_modules/next/dist/compiled/undici/index.js:1:26672)
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   at async postJSON (file:///Users/sbkl/app/beebook/node_modules/@planetscale/database/dist/index.js:128:22)
   at async Connection.execute (file:///Users/sbkl/app/beebook/node_modules/@planetscale/database/dist/index.js:86:23)
   at async PrismaPlanetScale.performIO (/Users/sbkl/app/beebook/node_modules/@prisma/adapter-planetscale/dist/index.js:143:22)
   at async PrismaPlanetScale.queryRaw (/Users/sbkl/app/beebook/node_modules/@prisma/adapter-planetscale/dist/index.js:114:54)
   at async /Users/sbkl/app/beebook/node_modules/@prisma/client/runtime/library.js:26:4983 {
 cause: ConnectTimeoutError: Connect Timeout Error
     at onConnectTimeout (/Users/sbkl/app/beebook/node_modules/next/dist/compiled/undici/index.js:1:92227)
     at /Users/sbkl/app/beebook/node_modules/next/dist/compiled/undici/index.js:1:91719
     at Immediate._onImmediate (/Users/sbkl/app/beebook/node_modules/next/dist/compiled/undici/index.js:1:92109)
     at process.processImmediate (node:internal/timers:471:21) {
   code: 'UND_ERR_CONNECT_TIMEOUT'
 },
 clientVersion: '5.4.1',
 page: '/'
```

**Comment by sbkl** [comment]
Had to change the connection string host to aws.connect.psdb.cloud for serverless environment [explained here](https://planetscale.com/blog/using-planetscale-with-serverless-framework-node-apps-on-aws#connecting-to-planetscale)

**Comment by janpio** [comment]
Great you figured it out @sbkl, we'll look into this as well if we can document this in some way.

After you changed that, everything is working as expected?
