### ISSUE TITLE
Confusing error message when trying to use engine type the client was not generated with

### ISSUE THREAD

**Issue by aqrln** [prisma/prisma#21428]
When generating the client for the library engine, trying to use the binary engine like this:

```
PRISMA_CLIENT_ENGINE_TYPE=binary ts-node index.ts
```

produces the following error:

```
PrismaClientValidationError: Invalid client engine type, please use `library` or `binary`
```

It should only list the engine types this generated client supports.

**Comment by WTanardi** [comment]
any updates on this? I'm using prisma with lucia in nextjs and this error popped up

**Comment by janpio** [comment]
Can you clarify how that happens @WTanardi? We until now thought this was mostly an internal challenge when testing esoteric features on our side.

**Comment by firoz3130** [comment]
Yeah ,can anyone help on this? I am getting like this
`⎔ Starting local server...
X [ERROR] PrismaClientValidationError: Invalid client engine type, please use `library` or binary
`
`  {
    clientVersion: '5.10.2'
  }
`

**Comment by swapyshelke** [comment]
Getting same error 
<img width="481" alt="image" src="https://github.com/prisma/prisma/assets/158486080/ef6600be-f20c-485d-b65e-1935165d1d97">

**Comment by fwx5618177** [comment]
You could try this solution:

1. Set `schema.prisma`

```json
generator client {
  provider   = "prisma-client-js"
  engineType = "library"
}
```

2. change the import: `import { PrismaClient } from "@prisma/client";`

**Comment by janpio** [comment]
Same question for you @firoz3130 @swapyshelke @fwx5618177:
Can you clarify how you end up in a situation where you get this error?

**Comment by fwx5618177** [comment]
> Same question for you @firoz3130 @swapyshelke @fwx5618177: Can you clarify how you end up in a situation where you get this error?

I have solved it.

**Comment by firoz3130** [comment]
> Same question for you @firoz3130 @swapyshelke @fwx5618177: Can you clarify how you end up in a situation where you get this error?

I have a serverless backend project which was using cloudflare workers . I was testing some of the apis in my project using postman.  So when I hit one of the apis , it was showing this error. It had a query to check if the user already exists in the db or not.

**Comment by nckre** [comment]
@janpio I ran into this error when trying to switch from the regular prisma client to edge (to enable running client w/ Vercel AI).

This is how I set up the client:

```ts
// lib/utils/db.ts
import { PrismaClient } from '@prisma/client/edge'
import { withAccelerate } from '@prisma/extension-accelerate'

export const db = new PrismaClient().$extends(withAccelerate())
```

And this is my generator: 

```
generator client {
    provider = "prisma-client-js"
}
```

Error:

```
 ⨯ PrismaClientValidationError: Invalid client engine type, please use `library` or `binary`
...
 ⨯  [Error: Invalid client engine type, please use `library` or `binary`] {
  digest: '3407705892'
}
 ⨯ [TypeError: Cannot read properties of null (reading 'default')]
 ```

**Comment by janpio** [comment]
Can you elaborate a bit? Did you have a working project before? What steps did you take to modify it, which commands did you run along the way? Do you maybe have a way to create a reproduction that we can run ourselves?

**Comment by herenickname** [comment]
I got this error when trying to use the latest version of Prisma (5.10.2) with the latest version of Deno (1.41.1)

schema.prisma:
```
generator client {
  provider        = "prisma-client-js"
  output          = "generated/client"
  previewFeatures = ["deno"]
}

datasource db {
  provider = "postgresql"
  url      = env("POSTGRES_URL")
}
```

main.ts:
```ts
import { PrismaClient } from '../../prisma/generated/client/deno/edge.ts'
export const prisma = new PrismaClient()
```

Output:
```
$ deno task dev:main
error: Uncaught (in promise) PrismaClientValidationError: Invalid client engine type, please use `library` or `binary`
    at ps (prisma/generated/client/runtime/edge-esm.js:13:65)
    at new t (prisma/generated/client/runtime/edge-esm.js:26:5761)
```
    
I tried generating different variants, with `engineType = "binary"` and `engineType = "library"` but always got the same error.

**Comment by mattwoodco** [comment]
I am getting this error in a Turborepo setup.

**Comment by frixaco** [comment]
@janpio Here's a repro: https://github.com/frixaco/test-prisma-edge-nextjs

It's a simple Next.js setup with Prisma. Error happens when using Edge client for me.

**Comment by helloiambguedes** [comment]
Also facing this error trying to connect to a remote DB from my local environment

**Comment by EseCurtis** [comment]
> > Same question for you @firoz3130 @swapyshelke @fwx5618177: Can you clarify how you end up in a situation where you get this error?
> 
> I have solved it.

How?

**Comment by curiousmike** [comment]
> > > Same question for you @firoz3130 @swapyshelke @fwx5618177: Can you clarify how you end up in a situation where you get this error?
> > 
> > 
> > I have solved it.
> 
> How?

He showed above https://github.com/prisma/prisma/issues/21428#issuecomment-1973562337

**Comment by deeratra** [comment]
I used this

`npx prisma generate --no-engine`

**Comment by reggi** [comment]
I'm getting this error using deno 

```
➜  d-prisma deno run --allow-env ./lib/repl.ts
error: Uncaught (in promise) PrismaClientValidationError: Invalid client engine type, please use `library` or `binary`
    at ms (file:///Users/thomasreggi/Desktop/d-prisma/generated/client/runtime/edge-esm.js:13:65)
    at new t (file:///Users/thomasreggi/Desktop/d-prisma/generated/client/runtime/edge-esm.js:26:5761)
    at file:///Users/thomasreggi/Desktop/d-prisma/lib/Session.ts:4:16
```

**Comment by Parag2812** [comment]
`PrismaClientValidationError: Invalid client engine type, please use `library` or `binary``

**Comment by chriszlr** [comment]
I have the same error

**Comment by leo-paz** [comment]
> I used this
> 
> `npx prisma generate --no-engine`

I modified my dev script like so and it worked

```
"dev": "npx prisma generate --no-engine && next dev",
```

**Comment by adamchipperfield** [comment]
@leo-paz I think that only works if you have a remote Accelerate connection. It doesn't work with a local database as described in [the Prisma docs](https://www.prisma.io/docs/accelerate/local-development).

**Comment by harshdasila** [comment]
do we require a pool connection url of our db to use this? @leo-paz

**Comment by InderKumhar0** [comment]
hey you can use this command it might be resolve your error

npx prisma generate --no-engine

**Comment by leo-paz** [comment]
@harshdasila this is assuming you're using prisma accelerate like @adamchipperfield mentioned which requires a DATABASE_URL env (or whatever you named this) that points to your prisma accelerate instance and a DIRECT_DATABASE_URL which is a direct connection to your db

**Comment by rohan12345a** [comment]
> You could try this solution:
> 
> 1. Set `schema.prisma`
> 
> ```json
> generator client {
>   provider   = "prisma-client-js"
>   engineType = "library"
> }
> ```
> 
> 2. change the import: `import { PrismaClient } from "@prisma/client";`

Thanks, it worked. Kudos!

**Comment by Saurabh-001-S** [comment]
when i try this it showing this error
X [ERROR] Error: PrismaClient is not configured to run in Cloudflare Workers. In order to run Prisma Client on edge runtime, either:

**Comment by issam-seghir** [comment]
My problem is fixed by executing the command `npx prisma generate --no-engine`. Moreover, I realized that I had forgotten to replace the database URL with the new one provided by Prisma Accelerate.

**Comment by cyrus-za** [comment]
Also running into this. Changing the engineType explicitly does not fix it for me. 

This happens when I run in CI on nx cloud. I use `PRISMA_GENERATE_NO_ENGINE="true"` in my .env file locally and got the same configured on vercel environment, but in the CI if I do that, I'd need to run prisma accelerate, or have an accelerate url, despite the fact that I am mocking out my prisma for tests, so I can't do no-engine in CI as it needs the binary else prisma generate will error out with the url

**Comment by Nivu789** [comment]
npx prisma generate --no-engine

this worked for me

PS: I am not having any engine specified in the prisma.Schema file

**Comment by dennisdingo28** [comment]
I had the same problem while using Prisma Accelerator and i fixed it by adding engineType = "library" and also modifying the pacakge.json prisma postinstall to `"postinstall": "prisma generate --no-engine"`

`generator client {
  provider = "prisma-client-js"
  engineType = "library"
}
`

**Comment by saurabhshukla689** [comment]
this worked for me
npx prisma generate --no-engine

**Comment by minhdtb** [comment]
I'm using vercel edge and "npx prisma generate --no-engine" still not worked

**Comment by UdittLamba** [comment]
i am unable to make it work for vercel edge middleware. 
same issue as others

**Comment by RameshPolubothu** [comment]
> I'm getting this error using deno 
> 
> ```
> ➜  d-prisma deno run --allow-env ./lib/repl.ts
> error: Uncaught (in promise) PrismaClientValidationError: Invalid client engine type, please use `library` or `binary`
>     at ms (file:///Users/thomasreggi/Desktop/d-prisma/generated/client/runtime/edge-esm.js:13:65)
>     at new t (file:///Users/thomasreggi/Desktop/d-prisma/generated/client/runtime/edge-esm.js:26:5761)
>     at file:///Users/thomasreggi/Desktop/d-prisma/lib/Session.ts:4:16
> ```
> 
> _Update_: I regenerated and it went away. 

How to regenerate the command

**Comment by kekzploit** [comment]
> I'm using vercel edge and "npx prisma generate --no-engine" still not worked

Did you figure this out in the end?
