### ISSUE TITLE
Persistent issues with initialising client

### ISSUE THREAD

**Issue by alf-tchldr** [prisma/prisma#21674]
### Bug description

Machine: Mac, M1 chip
Prisma: 5.5.2
Node: 18.8.0
NPM: 10.2.0

No matter what I do I cannot get Prisma to play ball.

When I try to use the client through my Next.js app, I get:

```
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
```

My db seed script is also failing:

```
Running seed command `ts-node --compiler-options {"module":"CommonJS"} seedData/seedTopics.ts` ...
/Users/username/Code/app/backend/tchldr-backend/node_modules/.prisma/client/index.js:43
    throw new Error(
          ^
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/Users/username/Code/app/backend/myapp-backend/node_modules/.prisma/client/index.js:43:11)
    at Object.<anonymous> (/Users/username/Code/app/backend/myapp-backend/seedData/seedTopics.ts:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/Users/username/Code/app/backend/myapp-backend/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/username/Code/app/backend/myapp-backend/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at phase4 (/Users/username/Code/app/backend/myapp-backend/node_modules/ts-node/src/bin.ts:649:14)

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node --compiler-options {"module":"CommonJS"} seedData/seedTopics.ts
```

Even when 

```npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (v5.4.2) to ./prisma/node_modules/@prisma/client in 121ms

Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
```
import { PrismaClient } from '@prisma/client/edge'
const prisma = new PrismaClient()
```

See other ways of importing Prisma Client: http://pris.ly/d/importing-client


warn Versions of prisma@5.5.2 and @prisma/client@5.4.2 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.```

I cannot work out where the two versions are coming from? npx prisma -v gives me 5.5.2

I've restarted the machine, reinstalled everything from NPM, cleared the Prisma cache... not sure what else to try or how to debug further?

### How to reproduce

I have installed Prisma from latest.

I have managed to migrate the schema.

Now, when I try to use the client for anything, it fails (after warning me that there are two versions- but I don't know where they are coming from)

### Expected behavior

Can use client after fresh install

### Prisma information

<!-- Do not include your database credentials when sharing your Prisma schema! -->
```generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider  = "postgresql"
  url       = env("POSTGRES_PRISMA_URL")
  directUrl = env("POSTGRES_URL_NON_POOLING")
}

model JournalEntry {
  id         String     @id @default(uuid())
  message    String
  date       DateTime
  topicId    String?
  userId     String
  activities Activity[]
  topic      Topic?     @relation(fields: [topicId], references: [id])
  user       User       @relation(fields: [userId], references: [id])
}

model Activity {
  id             String        @id @default(uuid())
  type           String
  date           DateTime
  journalEntryId String?
  userId         String
  JournalEntry   JournalEntry? @relation(fields: [journalEntryId], references: [id])
  user           User          @relation(fields: [userId], references: [id])
}

model Article {
  id     String  @id @default(uuid())
  name   String  @unique
  type   String
  status String
  read   Boolean
  link   String  @unique
  desc   String
  icon   String
  Topic  Topic[]
}

model Video {
  id     String  @id @default(uuid())
  name   String  @unique
  status String
  link   String  @unique
  desc   String
  icon   String
  img    String
  Topic  Topic[]
}

model Game {
  id     String  @id @default(uuid())
  name   String  @unique
  status String
  link   String  @unique
  desc   String
  icon   String
  img    String
  Topic  Topic[]
}

model Simulation {
  id     String  @id @default(uuid())
  name   String  @unique
  status String
  link   String  @unique
  desc   String
  icon   String
  img    String
  Topic  Topic[]
}

model Tip {
  id   String @id @default(uuid())
  desc String
}

model Error {
  id       String   @id @default(uuid())
  type     String
  desc     String
  dateTime DateTime
  userId   String
  url      String
  user     User     @relation(fields: [userId], references: [id])
}

model Topic {
  id           String         @id @default(uuid())
  name         String         @unique
  status       String
  link         String         @unique
  desc         String
  img          String
  icon         String
  JournalEntry JournalEntry[]
  Article      Article[]
  Game         Game[]
  Simulation   Simulation[]
  Video        Video[]
}

model User {
  id             String         @id @default(uuid())
  screenName     String         @unique
  fullName       String
  pronouns       String
  gender         String
  email          String         @unique
  socialLinkedIn String
  socialX        String
  jobTitle       String
  company        String
  companyType    String
  experience     Int
  memberSince    DateTime
  hereTo         String
  Activity       Activity[]
  Error          Error[]
  JournalEntry   JournalEntry[]
}

```

```ts
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

  type Topic = {
    id: number;
    name: string;
    status?: string;
    progress: number;
    link: string;
    desc: string;
    img: string;
  };

const topic: Topic =     {
      id: 1,
      name: "Test",
      progress: 100,
      link: "/topics/test-issues",
      status: "Coming Soon",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      img: "/imgs/test-issues.png",
    },

 const newEntry = await prisma.topic.upsert({
      where: { name: topic.name },
      update: {},
      create: {
        name: topic.name,
        status: topic.name,
        link: topic.link,
        desc: topic.desc,
        img: topic.img,
        icon: "",
      },
    });
```

### Environment & setup

- OS: Mac
- Database: PostgreSQL via Vercel
- Node.js version: 18.8.0

### Prisma Version

```
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules/prisma/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0

```

**Comment by alf-tchldr** [comment]
Released it was because I was using a package https://github.com/bcanfield/nexquik that was confusing things. After removing this, everything worked.

**Comment by miguelff** [comment]
Thank you so much for reporting @alf-tchldr and thank you as well for reporting back with your finding about nexquik interacting with prisma. Feel free to open an issue on nexquick, as it seems to consume the prisma schema, and refer this one, so we are on the loop.
