### ISSUE TITLE
Prisma unnecessary caches and prioritize an outdated schema

### ISSUE THREAD

**Issue by Nasfame** [prisma/prisma#21699]
### Bug description
```ts
import {PrismaClient} from '@prisma/client'
import {IPFSProviders, LIGHTHOUSE} from '../enums/ipfsProviders'

const prisma = new PrismaClient()

async function create_user(dto) {
  const user = await prisma.user.create({
    data: {
      email: dto.email,
    },
  })
  console.log({ created: user })
  return user
}

async function main() {
  // await prisma.user.deleteMany()

  const hiro = {
    email: 'hiro@decenterai.com',
    password: 'hiro@1234',
  }
  const deleteHiro = await prisma.user.findFirst({
    where: {
      email: hiro.email,
    },
  })
  if (deleteHiro) {
    console.log({ msg: `deleting user ${deleteHiro.id}` })
    await prisma.user.delete({
      where: {
        email: hiro.email,
      },
    })
  }
  const user1 = await create_user(hiro)

  const modelInput = {
    cid: 'Qme1HnwLHVzRxra7mT5gRkG7WbyE4FhnGFn9inETSj33Hw',
    // @ts-ignore FIXME:
    provider: LIGHTHOUSE,
  }

  const tr1 = await prisma.trainingRequest.create({
    data: {
      userId: user1.id,
      // @ts-ignore FIXME:
      inputs: modelInput ,
      config: {
        trainScript:'linear-regression.ipynb',
        inputArchive: `/inputs/${modelInput.cid}`
      }
    },
  })
  console.log({ orderReq1: tr1 })

  const m1 = await prisma.model.create({
    data:{
      userId: user1.id,
      name: "Prisma Seed Model",
      description: "seeded by prisma",
      trainingRequestId: tr1.id,
      data: {
          cid: "QmTsdCTu3MNFQWWQS9oYrrH1gwYcVADFZXRUbzbcZjkSi7",
        // @ts-ignore
          provider: IPFSProviders.IPFS,
      },
    }
  })

  console.log({m1})

}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

```

```prisma
// cat ./node_modules/.pnpm/@prisma+client@5.4.2_prisma@5.4.2/node_modules/.prisma/client/schema.prisma

generator client {
  provider            = "prisma-client-js"
  previewFeatures     = ["tracing", "metrics", "fieldReference", "fullTextIndex", "postgresqlExtensions"]
  // output          = "./generated"
  formatGeneratedCode = false
}

datasource db {
  provider = "cockroachdb"
  url      = env("DATABASE_URL")
}

model User {
  id Int @id @default(sequence(minValue: 1))

  userName String? @unique
  email    String? @unique

  name         String?
  profileImage String?

  createdAt    DateTime          @default(now()) @db.Timestamptz()
  updatedAt    DateTime          @updatedAt @db.Timestamptz()
  OrderRequest TrainingRequest[]

  @@map("users")
}

enum Category {
  FeatureExtraction @map("Feature Extraction")
}

model Model {
  id          Int        @id @default(sequence(minValue: 1))
  name        String
  description String
  category    Category[] // can be String[] FIXME unsure

  trainingRequestId Int
  trainingRequest   TrainingRequest @relation(fields: [trainingRequestId], references: [id])

  cid       String
  DataStore DataStore @relation(fields: [cid], references: [cid])

  createdAt DateTime @default(now()) @db.Timestamptz()
  updatedAt DateTime @updatedAt @db.Timestamptz()

  @@map("models")
}

enum IPFSProvider {
  LIGHTHOUSE
  IPFS
  INFURA
  S3
}

model DataStore {
  id       Int          @id @default(sequence(minValue: 1))
  cid      String       @unique
  provider IPFSProvider @default(LIGHTHOUSE)

  createdAt DateTime @default(now()) @db.Timestamptz()
  updatedAt DateTime @updatedAt @db.Timestamptz()

  TrainingRequest TrainingRequest[]
  Model           Model[]

  @@map("datastores")
}

model TrainingRequest {
  id     Int  @id @default(sequence(minValue: 1))
  userId Int
  user   User @relation(fields: [userId], references: [id])

  cid String

  createdAt DateTime @default(now()) @db.Timestamptz()
  updatedAt DateTime @updatedAt @db.Timestamptz()

  DataStore DataStore @relation(fields: [cid], references: [cid])

  Model Model[]

  @@map("training_requests")
}

```

### How to reproduce

You need to checkout main 1st, and do pnpm install 1st , this will create the cache
```
git clone https://github.com/DeCenter-AI/app.decenterai.com
git checkout 46980808787d28330207042e7c06d0c7a27033b7
pnpm install
npm run prisma:generate
npm run prisma:seed
```
This creates cached coachroach db based schema in /node_modules/.pnpm/@prisma+client@5.4.2_prisma@5.4.2/node_modules/.prisma/client/schema.prisma

```
git clone https://github.com/DeCenter-AI/app.decenterai.com
git checkout a33d8f4
pnpm install
npm run prisma:generate
npm run prisma:seed
```
The prisma:generate fails to overwrite the cached schema at /node_modules/.pnpm/@prisma+client@5.4.2_prisma@5.4.2/node_modules/.prisma/client/schema.prisma

### Expected behavior

works as expected

### Prisma information

```prisma
generator client {
  provider            = "prisma-client-js"
  previewFeatures     = ["tracing", "metrics", "fieldReference", "fullTextIndex", "postgresqlExtensions"]
  output          = "./generated"
  formatGeneratedCode = false
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model User {
  id             String            @id @default(auto()) @map("_id") @db.ObjectId

  userName String? @unique
  email    String? @unique

  name         String?
  profileImage String?

  createdAt    DateTime          @default(now()) @db.Timestamp
  updatedAt    DateTime          @updatedAt @db.Timestamp
  OrderRequest TrainingRequest[]

  models Model[]

  @@map("users")
}

enum Category {
  FeatureExtraction @map("Feature Extraction")
}

model Model {
  id             String            @id @default(auto()) @map("_id") @db.ObjectId
  name        String
  description String? @default("Trained by DecenterAI") //FIXME:
  category    Category[]

  userId String @db.ObjectId
  user User @relation(fields: [userId], references: [id])

  trainingRequestId String? @db.ObjectId
  trainingRequest   TrainingRequest? @relation(fields: [trainingRequestId], references: [id])

  data DataStore

  createdAt DateTime @default(now()) @db.Timestamp
  updatedAt DateTime @updatedAt @db.Timestamp

  @@map("models")
}

enum IPFSProvider {
  LIGHTHOUSE
  IPFS
  INFURA
  S3
}

type DataStore {
  cid      String
  provider IPFSProvider @default(LIGHTHOUSE)
}

type ModelTrainConfig {
  trainScript String
  inputArchive String
}

model TrainingRequest {
  id             String            @id @default(auto()) @map("_id") @db.ObjectId
  userId String? @db.ObjectId
  user   User? @relation(fields: [userId], references: [id])

  inputs DataStore
  config ModelTrainConfig

  createdAt DateTime @default(now()) @db.Timestamp
  updatedAt DateTime @updatedAt @db.Timestamp

  Model Model[]

  @@map("training_requests")
}

```

```ts
import {PrismaClient} from '@prisma/client'
import {IPFSProviders, LIGHTHOUSE} from '../enums/ipfsProviders'

const prisma = new PrismaClient()

async function create_user(dto) {
  const user = await prisma.user.create({
    data: {
      email: dto.email,
    },
  })
  console.log({ created: user })
  return user
}

async function main() {
  // await prisma.user.deleteMany()

  const hiro = {
    email: 'hiro@decenterai.com',
    password: 'hiro@1234',
  }
  const deleteHiro = await prisma.user.findFirst({
    where: {
      email: hiro.email,
    },
  })
  if (deleteHiro) {
    console.log({ msg: `deleting user ${deleteHiro.id}` })
    await prisma.user.delete({
      where: {
        email: hiro.email,
      },
    })
  }
  const user1 = await create_user(hiro)

  const modelInput = {
    cid: 'Qme1HnwLHVzRxra7mT5gRkG7WbyE4FhnGFn9inETSj33Hw',
    // @ts-ignore FIXME:
    provider: LIGHTHOUSE,
  }

  const tr1 = await prisma.trainingRequest.create({
    data: {
      userId: user1.id,
      // @ts-ignore FIXME:
      inputs: modelInput ,
      config: {
        trainScript:'linear-regression.ipynb',
        inputArchive: `/inputs/${modelInput.cid}`
      }
    },
  })
  console.log({ orderReq1: tr1 })

  const m1 = await prisma.model.create({
    data:{
      userId: user1.id,
      name: "Prisma Seed Model",
      description: "seeded by prisma",
      trainingRequestId: tr1.id,
      data: {
          cid: "QmTsdCTu3MNFQWWQS9oYrrH1gwYcVADFZXRUbzbcZjkSi7",
        // @ts-ignore
          provider: IPFSProviders.IPFS,
      },
    }
  })

  console.log({m1})

}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

```

### Environment & setup

OS: macOS
Database: MongoDB
Node.js version: v20.9.0

### Prisma Version

```
Environment variables loaded from ../.env
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at ../node_modules/.pnpm/@prisma+engines@5.5.2/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at ../node_modules/.pnpm/@prisma+engines@5.5.2/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
Preview Features        : fieldReference, fullTextIndex, metrics, postgresqlExtensions, tracing
```

**Comment by Jolg42** [comment]
@Nasfame the git hash you provided doesn't work for me
```
git fetch --all
git checkout a33d8f4
error: pathspec 'a33d8f4' did not match any file(s) known to git
```

**Comment by Nasfame** [comment]
@Jolg42 

https://github.com/DeCenter-AI/app.decenterai.com/blob/a33d8f42824ed6cae33140994508ea948b18a503/prisma/seed.ts#L12

**Comment by Jolg42** [comment]
@Nasfame this is probably only available on your local computer, because it's a 404 page online for me?
<img width="542" alt="Screenshot 2023-10-31 at 11 30 04" src="https://github.com/prisma/prisma/assets/1328733/177f8070-f57b-4029-a71b-bb5103fb65fc">

**Comment by Nasfame** [comment]
@Jolg42 sorry got to push commits.......

**Comment by Nasfame** [comment]
@Jolg42 done, i have pushed the commits. there were push conflicts,....

**Comment by Jolg42** [comment]
@Nasfame Now the `npm run prisma:seed` command fails with
```
npm run prisma:seed

> app.decenterai.com@0.5.0 prisma:seed
> prisma db seed

Running seed command `ts-node --transpile-only prisma/seed.ts` ...
Error: Cannot find module '@enums/ipfsProviders'
Require stack:
- /workspaces/app.decenterai.com/prisma/seed.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/workspaces/app.decenterai.com/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/workspaces/app.decenterai.com/prisma/seed.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module.m._compile (/workspaces/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/workspaces/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/workspaces/app.decenterai.com/prisma/seed.ts' ]
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node --transpile-only prisma/seed.ts
```

**Comment by Nasfame** [comment]
@Jolg42 
```
git checkout main (0ae89e0ae99a6932bdb839ca8561b66bf170a5ca)
pnpm install #(does prisma generate) 
```

Originally was coachroach db, when i switched to mongodb on a different branch 'migrate/mongo' , i kept on getting the error that i have put up in bug description

**Comment by Nasfame** [comment]
> @Nasfame Now the `npm run prisma:seed` command fails with
> 
> ```
> npm run prisma:seed
> 
> > app.decenterai.com@0.5.0 prisma:seed
> > prisma db seed
> 
> Running seed command `ts-node --transpile-only prisma/seed.ts` ...
> Error: Cannot find module '@enums/ipfsProviders'
> Require stack:
> - /workspaces/app.decenterai.com/prisma/seed.ts
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
>     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/workspaces/app.decenterai.com/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
>     at Function.Module._load (node:internal/modules/cjs/loader:901:27)
>     at Module.require (node:internal/modules/cjs/loader:1115:19)
>     at require (node:internal/modules/helpers:130:18)
>     at Object.<anonymous> (/workspaces/app.decenterai.com/prisma/seed.ts:2:1)
>     at Module._compile (node:internal/modules/cjs/loader:1241:14)
>     at Module.m._compile (/workspaces/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1618:23)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
>     at Object.require.extensions.<computed> [as .ts] (/workspaces/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1621:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/workspaces/app.decenterai.com/prisma/seed.ts' ]
> }
> 
> An error occurred while running the seed command:
> Error: Command failed with exit code 1: ts-node --transpile-only prisma/seed.ts
> ``

@Jolg42 That error is fine for now, creating a new issue for that

**Comment by Nasfame** [comment]
@Jolg42 I have rewritten the reproducer steps.

**Comment by Jolg42** [comment]
In your seed file you can replace
```
import {PrismaClient} from '@prisma/client'
```
by
```
import {PrismaClient} from './generated'
```

Since you are using, in your Prisma schema file:
```
  output          = "./generated"
```

That would work here.

**Comment by Nasfame** [comment]
@Jolg42 so the output is the issue?

**Comment by Jolg42** [comment]
I mean, it's getting confusing because your issue and the reproduction differs then, the issue has `output` commented out by in git it's not commented out.

**Comment by Nasfame** [comment]
@Jolg42 but i ideally the one in the generated should be prioritized right?

**Comment by Nasfame** [comment]
Otherwise the `output` feature is kind of breaking feature. Should be in preview then!!

**Comment by janpio** [comment]
No, it takes what you have in your code. If your code says `@prisma/client`, then it will load that. If your code says `./generated`, then it uses that. This is normal behavior that is documented and expected.

Do you still have a problem about "unnecessary caches and prioritize an outdated schema" when you take that into account?

**Comment by Nasfame** [comment]
ok @janpio not worries. Closing the issue. Thanks
