### ISSUE TITLE
prisma generate: not working in the latest version

### ISSUE THREAD

**Issue by Nasfame** [prisma/prisma#21698]
### Bug description

```
/opt/homebrew/bin/pnpm run prisma:seed

> app.decenterai.com@0.5.0 prisma:seed /Users/hiro/Decenter/app.decenterai.com
> prisma db seed

Environment variables loaded from .env
Running seed command `ts-node --transpile-only prisma/seed.ts` ...
/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/.prisma/client/index.js:43
    throw new Error(
          ^
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/.prisma/client/index.js:43:11)
    at Object.<anonymous> (/Users/hiro/Decenter/app.decenterai.com/prisma/seed.ts:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module.m._compile (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at phase4 (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/bin.ts:649:14)

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node --transpile-only prisma/seed.ts
 ELIFECYCLE  Command failed with exit code 1.

Process finished with exit code 1
```

### How to reproduce

- clone - https://github.com/DeCenter-AI/app.decenterai.com/blob/59a3cde3210a46c99d0c451503f113bfcf862750/prisma/seed.ts#L13

```
git clone https://github.com/DeCenter-AI/app.decenterai.com
git checkout 563f1278dd77d4018b65478f68e8c2b511cb4fb2
pnpm install
npm run prisma:generate
npm run prisma:seed
```

### Expected behavior

Should work normally.

### Prisma information

```prisma
 prisma -v
Environment variables loaded from ../.env
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at ../node_modules/.pnpm/@prisma+engines@5.5.2/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at ../node_modules/.pnpm/@prisma+engines@5.5.2/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
Preview Features        : fieldReference, fullTextIndex, metrics, postgresqlExtensions, tracing

```

```ts
import {PrismaClient} from '@prisma/client'
import {IPFSProviders, LIGHTHOUSE} from '../enums/ipfsProviders'

const prisma = new PrismaClient()

async function create_user(dto) {
  const user = await prisma.user.create({
    data: {
      email: dto.email,
    },
  })
  console.log({ created: user })
  return user
}

async function main() {
  // await prisma.user.deleteMany()

  const hiro = {
    email: 'hiro@decenterai.com',
    password: 'hiro@1234',
  }
  const deleteHiro = await prisma.user.findFirst({
    where: {
      email: hiro.email,
    },
  })
  if (deleteHiro) {
    console.log({ msg: `deleting user ${deleteHiro.id}` })
    await prisma.user.delete({
      where: {
        email: hiro.email,
      },
    })
  }
  const user1 = await create_user(hiro)

  const modelInput = {
    cid: 'Qme1HnwLHVzRxra7mT5gRkG7WbyE4FhnGFn9inETSj33Hw',
    // @ts-ignore FIXME:
    provider: LIGHTHOUSE,
  }

  const tr1 = await prisma.trainingRequest.create({
    data: {
      userId: user1.id,
      // @ts-ignore FIXME:
      inputs: modelInput ,
      config: {
        trainScript:'linear-regression.ipynb',
        inputArchive: `/inputs/${modelInput.cid}`
      }
    },
  })
  console.log({ orderReq1: tr1 })

  const m1 = await prisma.model.create({
    data:{
      userId: user1.id,
      name: "Prisma Seed Model",
      description: "seeded by prisma",
      trainingRequestId: tr1.id,
      data: {
          cid: "QmTsdCTu3MNFQWWQS9oYrrH1gwYcVADFZXRUbzbcZjkSi7",
        // @ts-ignore
          provider: IPFSProviders.IPFS,
      },
    }
  })

  console.log({m1})

}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

```

### Environment & setup

- OS: macOS
- Database: MongoDB
- Node.js version: v20.9.0

### Prisma Version

```
 prisma -v
Environment variables loaded from ../.env
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at ../node_modules/.pnpm/@prisma+engines@5.5.2/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at ../node_modules/.pnpm/@prisma+engines@5.5.2/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
Preview Features        : fieldReference, fullTextIndex, metrics, postgresqlExtensions, tracing

```

**Comment by Jolg42** [comment]
@Nasfame the git hash you provided doesn't work for me
```
git checkout 563f1278dd77d4018b65478f68e8c2b511cb4fb2
fatal: reference is not a tree: 563f1278dd77d4018b65478f68e8c2b511cb4fb2
```

**Comment by Jolg42** [comment]
Probably related to https://github.com/prisma/prisma/issues/21699

**Comment by Nasfame** [comment]
> git fetch --all

I have pushed the commits, should work now

**Comment by Nasfame** [comment]
Thanks @Jolg42 the issues are fixed: 

https://github.com/DeCenter-AI/app.decenterai.com/blob/d27cc74b64f19cbaaa7f0da565cdab3d8258758f/prisma/schema.prisma#L21

**Comment by Nasfame** [comment]
Your help was a deal breaker. Really appreciate it.
