### ISSUE TITLE
`npm run prisma:seed` fails to find typescript files in the project

### ISSUE THREAD

**Issue by Nasfame** [prisma/prisma#21703]
@Nasfame Now the `npm run prisma:seed` command fails with
```
npm run prisma:seed

> app.decenterai.com@0.5.0 prisma:seed
> prisma db seed

Running seed command `ts-node --transpile-only prisma/seed.ts` ...
Error: Cannot find module '@enums/ipfsProviders'
Require stack:
- /workspaces/app.decenterai.com/prisma/seed.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/workspaces/app.decenterai.com/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/workspaces/app.decenterai.com/prisma/seed.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module.m._compile (/workspaces/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/workspaces/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/workspaces/app.decenterai.com/prisma/seed.ts' ]
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node --transpile-only prisma/seed.ts
```

_Originally posted by @Jolg42 in https://github.com/prisma/prisma/issues/21699#issuecomment-1786949767_

**Comment by Nasfame** [comment]
```
git clone https://github.com/DeCenter-AI/app.decenterai.com
git checkout a33d8f4
pnpm install
npm run prisma:generate
npm run prisma:seed
```

**Comment by Jolg42** [comment]
Thanks for the issue, I took a shortcut and went for just trying `tsx prisma/seed.ts` (instead of `ts-node --transpile-only prisma/seed.ts`), and that works.

See https://www.npmjs.com/package/tsx

**Comment by Nasfame** [comment]
@Jolg42 yah the issue dissapeared with the fix applied ("commented: output") in schema.prisma. As per your suggestion in #21698

**Comment by Nasfame** [comment]
Now its all good, and working
https://github.com/DeCenter-AI/app.decenterai.com/blob/d27cc74b64f19cbaaa7f0da565cdab3d8258758f/prisma/schema.prisma#L21

**Comment by Nasfame** [comment]
@Jolg42 can u explain why ts-node was failing? I would love to know

**Comment by Nasfame** [comment]
@Jolg42 in my latest commit: `baf543e`

```
/opt/homebrew/bin/pnpm run prisma:seed

> app.decenterai.com@0.6.0 prisma:seed /Users/hiro/Decenter/app.decenterai.com
> prisma db seed

Environment variables loaded from .env
Running seed command `ts-node --transpile-only prisma/seed.ts` ...
/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
prisma/seed.ts:3:65 - error TS1002: Unterminated string literal.

3 import { IPFSProviders, LIGHTHOUSE } from "@enums/ipfsProviders'
                                                                  

    at createTSError (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:863:19)
    at /Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1379:34
    at Object.compile (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1458:13)
    at Module.m._compile (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  diagnosticCodes: [ 1002 ]
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node --transpile-only prisma/seed.ts
 ELIFECYCLE  Command failed with exit code 1.

```

My tconfig.json: https://github.com/DeCenter-AI/app.decenterai.com/blob/fb840d1d3c832034f01c2439b622e08e58fdd176/tsconfig.json#L74

**Comment by janpio** [comment]
Is the problem solved? Can you please close the issue then @Nasfame? Thanks.

**Comment by Nasfame** [comment]
No @janpio still getting the error!

**Comment by janpio** [comment]
The error your posted and the repository your linked to do not match.

Can you please shared which code causes which error exactly?

This most probably is not a bug in Prisma, but something in your script or how you use it.

**Comment by Nasfame** [comment]
@janpio the code causing the issuE: https://github.com/DeCenter-AI/app.decenterai.com/blob/a33d8f42824ed6cae33140994508ea948b18a503/prisma/seed.ts#L15

Error:
```
px prisma db seed
Environment variables loaded from .env
Running seed command `ts-node --transpile-only prisma/seed.ts` ...
Debugger listening on ws://127.0.0.1:59722/25ea04f0-6c31-421d-b88a-2f6ea845bf1d
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Error: Cannot find module '@enums/ipfsProviders'
Require stack:
- /Users/hiro/Decenter/app.decenterai.com/prisma/seed.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/@cspotcode+source-map-support@0.8.1/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/hiro/Decenter/app.decenterai.com/prisma/seed.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module.m._compile (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/hiro/Decenter/app.decenterai.com/node_modules/.pnpm/ts-node@10.9.1_@types+node@20.6.2_typescript@5.2.2/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/hiro/Decenter/app.decenterai.com/prisma/seed.ts' ]
}
Waiting for the debugger to disconnect...

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node --transpile-only prisma/seed.ts

```
Reproducer code

```
git clone https://github.com/DeCenter-AI/app.decenterai.com
git checkout a33d8f4
pnpm install
npm run prisma:generate
npm run prisma:seed
```

**Comment by janpio** [comment]
That again is a different error than what you reported above.
It also in no way seems to be related to Prisma, as it just reports that the import `import {IPFSProviders, LIGHTHOUSE} from '@enums/ipfsProviders'` does not work.

**Comment by Nasfame** [comment]
@janpio understood, closing the issue thansk!!!
