### ISSUE TITLE
Incorrect error messaging

### ISSUE THREAD

**Issue by Tom-DK** [prisma/prisma#21750]
### Bug description

By accident I was inserting the **password** field through prisma.update() function. 

Error message says **broker_id** is the unkown argument, however this should say **password**.

```
PrismaClientValidationError:
          Invalid prisma.agent.update()` invocation in
          D:\Coding\kloze-back-end\src\modules\agent\agent.service.ts:17:25

            14 }
            15
            16 export async function updateAgent(input: AgentResponseSchema) {
          ÔåÆ 17     return prisma.agent.update({
                     where: {
                       id: "z42RtjBDxMMM8wylfmnp6wM6IDp2"
                     },
                     data: {
                       name: "Test Update",
                       email: "mrtom9060@gmail.com",
                       telephone: "+32493049326",
                       avatar: "shrek.jpg",
                       broker_id: "J2YN6SWSVRXWbrBxZJb2R0Fkg6X2",
                       ~~~~~~~~~
                       password: "testakkak",
                       id: "z42RtjBDxMMM8wylfmnp6wM6IDp2",
                   ?   broker?: BrokerUpdateOneRequiredWithoutAgentsNestedInput,
                   ?   properties?: PropertyUpdateManyWithoutAgentNestedInput
                     }
                   })

          Unknown argument `broker_id`. Did you mean `broker`? Available options are marked with ?.
              at En (D:\Coding\kloze-back-end\node_modules\@prisma\client\runtime\library.js:116:5888)
              at Cn.handleRequestError (D:\Coding\kloze-back-end\node_modules\@prisma\client\runtime\library.js:123:6516)
              at Cn.handleAndLogRequestError (D:\Coding\kloze-back-end\node_modules\@prisma\client\runtime\library.js:123:6206)
              at Cn.request (D:\Coding\kloze-back-end\node_modules\@prisma\client\runtime\library.js:123:5926)
              at l (D:\Coding\kloze-back-end\node_modules\@prisma\client\runtime\library.js:128:9968)
      "name": "PrismaClientValidationError",
      "clientVersion": "5.5.1"

```

### How to reproduce

Create a basic schema, try to update the entry and add an extra field in the 'data' object that's not in the prisma.schema. 

### Expected behavior

An error message saying **password** field is the unknown argument.

### Prisma information

model Agent {
  id         String     @id
  name       String
  avatar     String?
  email      String     @unique
  telephone  String     @unique
  broker     Broker     @relation(fields: [broker_id], references: [id])
  broker_id  String
  properties Property[]
}

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: 21.0.0

### Prisma Version

```
prisma                  : 5.5.1
@prisma/client          : 5.5.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine 475c616176945d72f4330c92801f0c5e6398dc0f (at C:\Users\TOMDEK~1\AppData\Roaming\nvm\v21.0.0\node_modules\prisma\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 475c616176945d72f4330c92801f0c5e6398dc0f (at C:\Users\TOMDEK~1\AppData\Roaming\nvm\v21.0.0\node_modules\prisma\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.0-19.475c616176945d72f4330c92801f0c5e6398dc0f
Default Engines Hash    : 475c616176945d72f4330c92801f0c5e6398dc0f
Studio                  : 0.494.0

```

**Comment by janpio** [comment]
When you remove `password`, the query works with `broker_id` in place?

**Comment by Tom-DK** [comment]
> When you remove `password`, the query works with `broker_id` in place?

Yes, forgot to say that. Sorry!

**Comment by spanwair** [comment]
same for me:
```
server_1      | {
server_1      |   data: {
server_1      |     title: "New item",
server_1      |     endingDate: "2024-02-13T01:21:35.655Z",
server_1      |     imgUrl: undefined,
server_1      |     description: "description",
server_1      |     user_id: undefined,
server_1      |     categoryId: 1,
server_1      |     ~~~~~~~~~~
server_1      |     locationId: 6,
server_1      |     city: "Olomouc",
server_1      |     country: "CZ",
server_1      |     street: "U parčíku",
server_1      |     zipCode: "77900",
server_1      |     unitCode: "24/47",
server_1      |     offeredPrice: 200,
server_1      | ?   createdAt?: DateTime | Null,
server_1      | ?   updatedAt?: DateTime | Null,
server_1      | ?   user?: UserCreateNestedOneWithoutInsertionsInput,
server_1      | ?   category?: CategoryCreateNestedOneWithoutInsertionsInput,
server_1      | ?   location?: LocationCreateNestedOneWithoutLocationInput
server_1      |   },
server_1      |   select: {
server_1      |     id: true
server_1      |   }
server_1      | }

```
but the problem was with user_id: undefined where user_id is required but present is undefined

**Comment by Shadow-Scripter** [comment]
Got This Issue Too

**Comment by Shadow-Scripter** [comment]
PrismaClientValidationError {
    name: 'PrismaClientValidationError',
    clientVersion: '5.17.0',
    stack: 'PrismaClientValidationError: \n' +
      'Invalid `prisma.task.create()` invocation:\n' +
      '\n' +
      '{\n' +
      '  data: {\n' +
      '    title: "Surah Nass",\n' +
      '    description: "aebesbb hdxdxdhxdbdbl;jruioagahivubhuizsbvsuibgsuiofzsifhawuibgsuin uisbvnzsivnzsvo[hzs",\n' +
      '    date: new Date("2024-07-29T00:00:00.000Z"),\n' +
      '    isCompleted: "",\n' +
      '    isImportant: true,\n' +
      '    userId: "user_2jK3WB72owk1cAHfuZ9VMuhrTWu",\n' +
      '+   user: String\n' +
      '  }\n' +
      '}\n' +
      '\n' +
      'Argument `user` is missing.\n' +``
