### ISSUE TITLE
Failed deployment to Vercel: with build unknow error, but working as expected in local server

### ISSUE THREAD

**Issue by kelmedev** [prisma/prisma#21874]
### Bug description

Can someone please help me to identify what error is going on with my deploy to Vercel? I tried everything, I guess this is a bug...

log below:
```
[11:47:31.201] Cloning completed: 1.286s
[11:47:31.595] Running "vercel build"
[11:47:32.077] Vercel CLI 32.5.3
[11:47:32.892] Installing dependencies...
[11:48:06.901] 
[11:48:06.902] > app@0.1.0 postinstall
[11:48:06.902] > prisma generate
[11:48:06.903] 
[11:48:07.559] Environment variables loaded from .env
[11:48:07.561] Prisma schema loaded from prisma/schema.prisma
[11:48:08.055] 
[11:48:08.056] ✔ Generated Prisma Client (v5.5.2) to ./prisma/generated/client in 71ms
[11:48:08.057] 
[11:48:08.057] Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
[11:48:08.057] ```
[11:48:08.057] import { PrismaClient } from './prisma/generated/client'
[11:48:08.057] const prisma = new PrismaClient()
[11:48:08.058] ```
[11:48:08.058] or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
[11:48:08.058] ```
[11:48:08.058] import { PrismaClient } from './prisma/generated/client/edge'
[11:48:08.058] const prisma = new PrismaClient()
[11:48:08.058] ```
[11:48:08.059] 
[11:48:08.059] See other ways of importing Prisma Client: http://pris.ly/d/importing-client
[11:48:08.059] 
[11:48:08.121] 
[11:48:08.122] added 828 packages in 35s
[11:48:08.122] 
[11:48:08.122] 167 packages are looking for funding
[11:48:08.122]   run `npm fund` for details
[11:48:08.169] Detected Next.js version: 14.0.1
[11:48:08.170] Running "prisma generate && next build"
[11:48:08.827] Environment variables loaded from .env
[11:48:08.832] Prisma schema loaded from prisma/schema.prisma
[11:48:09.263] 
[11:48:09.264] ✔ Generated Prisma Client (v5.5.2) to ./prisma/generated/client in 73ms
[11:48:09.264] 
[11:48:09.264] Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
[11:48:09.264] ```
[11:48:09.265] import { PrismaClient } from './prisma/generated/client'
[11:48:09.265] const prisma = new PrismaClient()
[11:48:09.265] ```
[11:48:09.265] or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
[11:48:09.265] ```
[11:48:09.266] import { PrismaClient } from './prisma/generated/client/edge'
[11:48:09.266] const prisma = new PrismaClient()
[11:48:09.266] ```
[11:48:09.266] 
[11:48:09.266] See other ways of importing Prisma Client: http://pris.ly/d/importing-client
[11:48:09.266] 
[11:48:09.974] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[11:48:09.974] This information is used to shape Next.js' roadmap and prioritize features.
[11:48:09.975] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[11:48:09.975] https://nextjs.org/telemetry
[11:48:09.975] 
[11:48:10.080]    ▲ Next.js 14.0.1
[11:48:10.080]    - Environments: .env
[11:48:10.081] 
[11:48:10.082]    Creating an optimized production build ...
[11:48:31.622]  ✓ Compiled successfully
[11:48:31.624]    Linting and checking validity of types ...
[11:48:39.938]    Collecting page data ...
[11:48:40.377] Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
[11:48:40.378] In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
[11:48:40.378]     at new PrismaClient (/vercel/path0/node_modules/.prisma/client/index.js:43:11)
[11:48:40.378]     at 23758 (/vercel/path0/.next/server/chunks/758.js:1:129)
[11:48:40.379]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:1:146)
[11:48:40.379]     at 29821 (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:1254)
[11:48:40.379]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:1:146)
[11:48:40.379]     at __webpack_exec__ (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:1838)
[11:48:40.380]     at /vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:1876
[11:48:40.380]     at __webpack_require__.X (/vercel/path0/.next/server/webpack-runtime.js:1:1638)
[11:48:40.380]     at /vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:1851
[11:48:40.380]     at Object.<anonymous> (/vercel/path0/.next/server/app/api/auth/[...nextauth]/route.js:1:1919)
[11:48:40.381] 
[11:48:40.381] > Build error occurred
[11:48:40.386] Error: Failed to collect page data for /api/auth/[...nextauth]
[11:48:40.387]     at /vercel/path0/node_modules/next/dist/build/utils.js:1211:15
[11:48:40.387]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[11:48:40.387]   type: 'Error'
[11:48:40.387] }
[11:48:40.442] Error: Command "prisma generate && next build" exited with 1
[11:48:40.975] 
```

### How to reproduce

```

{
	"name": "ensiene-webapp",
	"version": "0.1.0",
	"private": true,
	"scripts": {
		"dev": "next dev",
		"build": "prisma generate && next build",
		"start": "next start",
		"lint": "next lint"
	},
	"dependencies": {
		"@headlessui/react": "^1.7.15",
		"@heroicons/react": "^2.0.18",
		"@next-auth/prisma-adapter": "^1.0.7",
		"@nextui-org/react": "^1.0.0-beta.13",
		"@prisma/client": "^5.5.2",
		"@radix-ui/react-dropdown-menu": "^2.0.5",
		"@radix-ui/react-label": "^2.0.2",
		"@radix-ui/react-navigation-menu": "^1.1.3",
		"@radix-ui/react-popover": "1.0.6",
		"@radix-ui/react-slot": "^1.0.2",
		"@tremor/react": "^3.6.0",
		"@types/react": "18.2.15",
		"@types/react-dom": "18.2.7",
		"@vercel/postgres": "^0.5.0",
		"autoprefixer": "10.4.14",
		"bun": "^1.0.11",
		"class-variance-authority": "^0.7.0",
		"clsx": "^2.0.0",
		"eslint": "8.45.0",
		"eslint-config-next": "^14.0.1",
		"framer-motion": "^10.16.4",
		"iconoir-react": "^6.10.0",
		"lucide-react": "^0.263.1",
		"next": "^14.0.1",
		"next-auth": "^4.24.4",
		"next-themes": "^0.2.1",
		"nextjs-toploader": "^1.4.2",
		"postcss": "^8.4.31",
		"prisma": "5.3.1",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"shadcn-ui": "^0.3.0",
		"sharp": "^0.32.6",
		"tailwind-merge": "^1.14.0",
		"tailwindcss": "3.3.3",
		"tailwindcss-animate": "^1.0.6"
	},
	"prisma": {
		"seed": "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts"
	},
	"devDependencies": {
		"@types/node": "^20.4.4",
		"prisma": "^5.3.1",
		"ts-node": "^10.9.1",
		"typescript": "^5.2.2"
	}
}


```

### Expected behavior

I expected that it would be correctly deployed to vercel, sense it's "next build" on local server is working pretty well. I configured "prisma generate && next build" at vercel and configurated "postinstall" in "package.json".

### Prisma information

//npx prisma studio 
//npx prisma migrate dev --name init
//npx prisma db push

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "./generated/client"
}

datasource db {
  provider = "postgresql"
  url = env("POSTGRES_PRISMA_URL") // uses connection pooling
  directUrl = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
}


// NextAuth Schema

model Account {
  id                 String  @id @default(cuid())
  userId             String
  type               String
  provider           String
  providerAccountId  String
  refresh_token      String?  @db.Text
  access_token       String?  @db.Text
  expires_at         Int?
  refresh_token_expires_in Int?
  token_type         String?
  scope              String?
  id_token           String?  @db.Text
  session_state      String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  name          String?
  bio           String? @db.Text
  age           Int?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}
```

### Environment & setup

- OS: **Linux**
- Database: **Vercel Postgree**
- Node.js version: **v20.9.0**

### Prisma Version

` prisma 5.3.1`

**Comment by janpio** [comment]
See https://github.com/prisma/prisma/discussions/21870

**Comment by kelmedev** [comment]
> See https://github.com/prisma/prisma/discussions/21870

It's my own post, xD

**Comment by kelmedev** [comment]
The problem still not resolved :/

**Comment by janpio** [comment]
That does not make a discussion a bug. And it especially does not justify just creating the same thing again. This just causes additional work to us which leads to everyone getting responses later.
