### ISSUE TITLE
`queries::filters::field_reference::failure::failure::alphanumeric_json_filter_fails` fails with `JSON target types only accept strings or numbers, found: {\"_ref\":\"json\",\"_container\":\"TestModel\"}"` for MySQL 5.7, 8 and MariaDB (for Json protocol)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#21896]
In context of https://github.com/prisma/prisma-engines/pull/4428:

```
thread 'queries::filters::field_reference::failure::failure::alphanumeric_json_filter_fails' panicked at /home/ubuntu/actions-runner/_work/prisma-engines/prisma-engines/query-engine/connector-test-kit-rs/query-tests-setup/src/query_result.rs:106:17:
Expected error with code `P2009` and message `Invalid argument type`, got: `{"errors":[{"error":"JSON target types only accept strings or numbers, found: {\"_ref\":\"json\",\"_container\":\"TestModel\"}","user_facing_error":{"is_panic":true,"message":"JSON target types only accept strings or numbers, found: {\"_ref\":\"json\",\"_container\":\"TestModel\"}","backtrace":null}}]}`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: query_tests_setup::query_result::QueryResult::assert_failure
             at /home/ubuntu/actions-runner/_work/prisma-engines/prisma-engines/query-engine/connector-test-kit-rs/query-tests-setup/src/query_result.rs:106:17
   3: query_engine_tests::queries::filters::field_reference::failure::failure::run_alphanumeric_json_filter_fails::{{closure}}
             at ./tests/queries/filters/field_reference/failure.rs:256:9
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/future/future.rs:125:9
   5: query_tests_setup::run_connector_test_impl::{{closure}}
             at /home/ubuntu/actions-runner/_work/prisma-engines/prisma-engines/query-engine/connector-test-kit-rs/query-tests-setup/src/lib.rs:287:29
   6: <tracing_futures::WithDispatch<T> as core::future::future::Future>::poll::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-futures-0.2.5/src/lib.rs:455:47
   7: tracing_core::dispatcher::with_default
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.31/src/dispatcher.rs:265:5
   8: <tracing_futures::WithDispatch<T> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-futures-0.2.5/src/lib.rs:455:9
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/future/future.rs:125:9
  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/scheduler/current_thread/mod.rs:665:57
  11: tokio::runtime::coop::with_budget
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/coop.rs:107:5
  12: tokio::runtime::coop::budget
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/coop.rs:73:5
  13: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/scheduler/current_thread/mod.rs:665:25
  14: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/scheduler/current_thread/mod.rs:410:19
  15: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/scheduler/current_thread/mod.rs:664:36
  16: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/scheduler/current_thread/mod.rs:743:68
  17: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/context/scoped.rs:40:9
  18: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/context.rs:176:26
  19: std::thread::local::LocalKey<T>::try_with
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:270:16
  20: std::thread::local::LocalKey<T>::with
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:246:9
  21: tokio::runtime::context::set_scheduler
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/context.rs:176:9
  22: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/scheduler/current_thread/mod.rs:743:27
  23: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/scheduler/current_thread/mod.rs:652:19
  24: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/scheduler/current_thread/mod.rs:175:28
  25: tokio::runtime::context::runtime::enter_runtime
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/context/runtime.rs:65:16
  26: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/scheduler/current_thread/mod.rs:167:9
  27: tokio::runtime::runtime::Runtime::block_on
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.30.0/src/runtime/runtime.rs:347:47
  28: query_tests_setup::run_with_tokio
             at /home/ubuntu/actions-runner/_work/prisma-engines/prisma-engines/query-engine/connector-test-kit-rs/query-tests-setup/src/lib.rs:57:5
  29: query_tests_setup::run_connector_test_impl
             at /home/ubuntu/actions-runner/_work/prisma-engines/prisma-engines/query-engine/connector-test-kit-rs/query-tests-setup/src/lib.rs:272:5
  30: query_tests_setup::run_connector_test
             at /home/ubuntu/actions-runner/_work/prisma-engines/prisma-engines/query-engine/connector-test-kit-rs/query-tests-setup/src/lib.rs:227:5
  31: query_engine_tests::queries::filters::field_reference::failure::failure::alphanumeric_json_filter_fails
             at ./tests/queries/filters/field_reference/failure.rs:254:5
  32: query_engine_tests::queries::filters::field_reference::failure::failure::alphanumeric_json_filter_fails::{{closure}}
             at ./tests/queries/filters/field_reference/failure.rs:254:5
  33: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  34: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
```

Seems the tests are not run with Json protocol anywhere else.

**Comment by Jolg42** [comment]
```
queries::filters::field_reference::failure::failure::alphanumeric_json_filter_fails
```

Is the only test failing in CI using json protocol for MariaDB, MySQL 5.7 & 8.0
But the test is passing for MySQL 5.6

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. 

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
