### ISSUE TITLE
Prisma infers the wrong type for arrays of timestamps which are null

### ISSUE THREAD

**Issue by gorbak25** [prisma/prisma#21943]
### Bug description

When using an array of date objects which are null as an argument for a query prisma infers the wrong type for the argument. What's weird is that this works for any type other than `timestamp with time zone[]`
```
Invalid `prisma.$queryRawUnsafe()` invocation:

Raw query failed. Code: `42846`. Message: `ERROR: cannot cast type integer[] to timestamp with time zone[]`
    at waitForPromises (/home/node/workspace/src/utils.ts:53:11)
    at <anonymous> (/home/node/workspace/src/entrypoints/admin-commands/restore-db.ts:95:7)
    at Proxy._transactionWithCallback (/home/node/workspace/node_modules/@prisma/server-client/runtime/library.js:128:8631)
    at restoreDbCommand (/home/node/workspace/src/entrypoints/admin-commands/restore-db.ts:50:3)
    at main (/home/node/workspace/src/entrypoints/admin-cli.ts:29:5) {
  errors: [
    PrismaClientKnownRequestError: 
    Invalid `prisma.$queryRawUnsafe()` invocation:
    
    
    Raw query failed. Code: `42846`. Message: `ERROR: cannot cast type integer[] to timestamp with time zone[]`
        at Cn.handleRequestError (/home/node/workspace/node_modules/@prisma/server-client/runtime/library.js:123:6817)
        at Cn.handleAndLogRequestError (/home/node/workspace/node_modules/@prisma/server-client/runtime/library.js:123:6206)
        at Cn.request (/home/node/workspace/node_modules/@prisma/server-client/runtime/library.js:123:5926)
        at l (/home/node/workspace/node_modules/@prisma/server-client/runtime/library.js:128:9968)
        at <anonymous> (/home/node/workspace/src/entrypoints/admin-commands/restore-db.ts:125:13)
        at async Promise.allSettled (index 0)
        at waitForPromises (/home/node/workspace/src/utils.ts:42:19)
        at <anonymous> (/home/node/workspace/src/entrypoints/admin-commands/restore-db.ts:95:7)
        at Proxy._transactionWithCallback (/home/node/workspace/node_modules/@prisma/server-client/runtime/library.js:128:8631)
        at restoreDbCommand (/home/node/workspace/src/entrypoints/admin-commands/restore-db.ts:50:3) {
      code: 'P2010',
      clientVersion: '5.5.2',
      meta: {
        code: '42846',
        message: 'ERROR: cannot cast type integer[] to timestamp with time zone[]'
      }
    }
  ]
}
```

### How to reproduce

Run 
```ts
await db.$queryRawUnsafe(`
    SELECT * from unnest($1::timestamp with time zone[])
  `, [null])
```

### Expected behavior

The query works

### Prisma information

```prisma
```

```ts
await db.$queryRawUnsafe(`
    SELECT * from unnest($1::timestamp with time zone[])
  `, [null])
```

### Environment & setup

- OS: Debian GNU/Linux 12 mcr.microsoft.com/devcontainers/typescript-node:20
- Database: PostgreSQL
- Node.js version: v20.9.0

### Prisma Version

```
node ➜ ~/workspace (main) $ yarn prisma -v
yarn run v1.22.19
$ /home/node/workspace/node_modules/.bin/prisma -v
Environment variables loaded from .env
prisma                  : 5.5.2
@prisma/client          : 5.5.2
Current platform        : debian-openssl-3.0.x
Query Engine (Node-API) : libquery-engine aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.5.1-1.aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Default Engines Hash    : aebc046ce8b88ebbcb45efe31cbe7d06fd6abc0a
Studio                  : 0.494.0
Done in 1.95s.
```

**Comment by Nikita-Shaked-dev** [comment]
Same for me, any updates?

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
