### ISSUE TITLE
prisma error

### ISSUE THREAD

**Issue by waheed7866** [prisma/prisma#22006]
### Bug description

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/home/wisecjgb/nodevenv/backend.wise1ne.com/14/lib/node_modules/.prisma/client/index.js:5:11)
    at Object.<anonymous> (/home/wisecjgb/backend.wise1ne.com/utils/prisma.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/wisecjgb/backend.wise1ne.com/routes/hr/rolePermission/rolePermission.controllers.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by Weakky** [comment]
Hey @waheed7866,

Have you tried running `prisma generate`? If you have, do you perhaps have any more information that could help us reproduce your issue, such as your datamodel?

Thank you!
