### ISSUE TITLE
Generated `CompoundUniqueInput` type is incorrect if one of the compound types is Nullable

### ISSUE THREAD

**Issue by rcbevans** [prisma/prisma#22016]
### Bug description

The Prisma generated type for a model `CompoundUniqueInput` is incorrect if one of the properties in the compound uniqueness constraint are nullable.

The type of the nullable field is missing the `| null`.

### How to reproduce

Create a model in Prisma:

```prisma
model BrokenModel {
  field1: String
  field2: Int
  field3: Int?

  @@unique([field1, field2, field3])
}
```

This results in

```ts
  export type BrokenModelField1Field2Field3CompoundUniqueInput = {
    field1: string
    field2: number
    field3: number
  }
```

However it should be 

```ts
  export type BrokenModelField1Field2Field3CompoundUniqueInput = {
    field1: string
    field2: number
    field3: number | null
  }
```

This results in the inability to correctly use prisma methods such as `model.upsert` because is not possible to specify `field3` as `number | null` despite both being valid.

### Expected behavior

The `CompoundUniqueInput` should generate with the correct type, per the schema.

### Prisma information

```prisma
model ExternalServiceObjectFieldConfiguration {
  id                     Int                            @default(autoincrement())
  createdAt              DateTime                       @default(now())
  updatedAt              DateTime?
  objectType             ExternalServiceObjectType
  fieldName              String
  displayOrder           Int?
  organizationId         Int
  organization           Organization                   @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  serviceConfigurationId Int
  serviceConfiguration   ExternalServiceConfiguration   @relation(fields: [organizationId, serviceConfigurationId], references: [organizationId, id], onDelete: Cascade)
  customFieldSetId       Int?
  customFieldSet         ExternalServiceCustomFieldSet? @relation(fields: [organizationId, customFieldSetId], references: [organizationId, id], onDelete: Cascade)

  @@id([organizationId, id])
  @@unique([organizationId, serviceConfigurationId, customFieldSetId, fieldName, objectType])
  @@index([organizationId, serviceConfigurationId, customFieldSetId, objectType])
}
```

```ts
  export type ExternalServiceObjectFieldConfigurationOrganizationIdServiceConfigurationIdCustomFieldSetIdFieldNameObjectTypeCompoundUniqueInput = {
    organizationId: number
    serviceConfigurationId: number
    customFieldSetId: number
    fieldName: string
    objectType: $Enums.ExternalServiceObjectType
  }
```

```ts
        prisma.externalServiceObjectFieldConfiguration.upsert({
          where: {
            organizationId_serviceConfigurationId_customFieldSetId_fieldName_objectType: {
              organizationId,
              serviceConfigurationId: configurationId,
              customFieldSetId: fieldsetId || null, // <<-- BROKEN
              fieldName,
              objectType: HubSpotObjectToMeetingflowObject[hubspotObjectType],
            },
          },
          create: {
            organizationId,
            serviceConfigurationId: configurationId,
            objectType: HubSpotObjectToMeetingflowObject[hubspotObjectType],
            fieldName,
            displayOrder: idx,
          },
          update: {
            updatedAt: new Date(),
            displayOrder: idx,
          },
        })
      ),
```

### Environment & setup

- OS: Pop_OS! 22.04
- Database: PostgreSQL
- Node.js version: v18.17.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.6.0
@prisma/client          : 5.6.0
Computed binaryTarget   : debian-openssl-1.1.x
Operating System        : linux
Architecture            : x64
Node.js                 : v18.17.1
Query Engine (Node-API) : libquery-engine e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.6.0-32.e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Default Engines Hash    : e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Studio                  : 0.495.0
Preview Features        : fullTextIndex, fullTextSearch
```

**Comment by rcbevans** [comment]
Something else seems broken in this version of Prisma.  With the provided schema, the following code throws what looks like an engine error:

```ts
      prisma.externalServiceObjectFieldConfiguration.deleteMany({
        where: {
          organizationId,
          serviceConfigurationId: configurationId,
          customFieldSetId: { equals: fieldsetId || null },
          objectType: SalesforceObjectToMeetingflowObject[sObject],
          fieldName: {
            notIn: fields,
          },
        },
      }),
```

```
Argument `customFieldSetId` is missing.
    at Zn (/node_modules/@prisma/client/runtime/library.js:117:5888)
    at ni.handleRequestError (/node_modules/@prisma/client/runtime/library.js:124:6516)
    at ni.handleAndLogRequestError (/node_modules/@prisma/client/runtime/library.js:124:6206)
```

**Comment by rcbevans** [comment]
Also tried

```ts
      prisma.externalServiceObjectFieldConfiguration.deleteMany({
        where: {
          organizationId,
          serviceConfigurationId: configurationId,
          customFieldSetId: fieldsetId || null,
          objectType: SalesforceObjectToMeetingflowObject[sObject],
          fieldName: {
            notIn: fields,
          },
        },
      }),
```

and get the same runtime error.

**Comment by rcbevans** [comment]
Checking the generated types, they look correct, so this looks like a runtime engine issue

```ts
  export type ExternalServiceObjectFieldConfigurationWhereInput = {
    AND?: ExternalServiceObjectFieldConfigurationWhereInput | ExternalServiceObjectFieldConfigurationWhereInput[]
    OR?: ExternalServiceObjectFieldConfigurationWhereInput[]
    NOT?: ExternalServiceObjectFieldConfigurationWhereInput | ExternalServiceObjectFieldConfigurationWhereInput[]
    id?: IntFilter<"ExternalServiceObjectFieldConfiguration"> | number
    createdAt?: DateTimeFilter<"ExternalServiceObjectFieldConfiguration"> | Date | string
    updatedAt?: DateTimeNullableFilter<"ExternalServiceObjectFieldConfiguration"> | Date | string | null
    objectType?: EnumExternalServiceObjectTypeFilter<"ExternalServiceObjectFieldConfiguration"> | $Enums.ExternalServiceObjectType
    fieldName?: StringFilter<"ExternalServiceObjectFieldConfiguration"> | string
    displayOrder?: IntNullableFilter<"ExternalServiceObjectFieldConfiguration"> | number | null
    organizationId?: IntFilter<"ExternalServiceObjectFieldConfiguration"> | number
    serviceConfigurationId?: IntFilter<"ExternalServiceObjectFieldConfiguration"> | number
    customFieldSetId?: IntNullableFilter<"ExternalServiceObjectFieldConfiguration"> | number | null
    organization?: XOR<OrganizationRelationFilter, OrganizationWhereInput>
    serviceConfiguration?: XOR<ExternalServiceConfigurationRelationFilter, ExternalServiceConfigurationWhereInput>
    customFieldSet?: XOR<ExternalServiceCustomFieldSetNullableRelationFilter, ExternalServiceCustomFieldSetWhereInput> | null
  }
```

**Comment by SevInf** [comment]
Hi @rcbevans.
This works as intended. Reason for that is that `NULL` is not treated as unique value by default in SQL. See [this example](https://www.db-fiddle.com/f/afqj6mHGRZbb4CXEn4Wc9M/0) - there are two `(1, NULL)` rows in the table despite unique index. 

`findUnique` and `upsert` from Prisma's side guarantee that at most 1 row will be affected/returned. If we are to allow `null` as an input, that would break that guarantee. For `findUnique` replacement you can use `findFirst` or `findMany` depending on how you want to treat duplicate values. For `upsert`, I think it has to be a transaction with a combination of `findMany` + `create`/`updateMany` or `findFirst` + `create`/`update`, again, depending on how do you decide to treat multiple rows.
