### ISSUE TITLE
Runtime error: Argument "name" is missing in deleteMany for NullableInt field

### ISSUE THREAD

**Issue by rcbevans** [prisma/prisma#22020]
### Bug description

Doing deleteMany with a where clause filtering on a NullableInt field fails with a runtime error:

```
Argument `customFieldSetId` is missing.
    at Zn (/server/node_modules/@prisma/client/runtime/library.js:117:5888)
    at ni.handleRequestError (/server/node_modules/@prisma/client/runtime/library.js:124:6516)
    at ni.handleAndLogRequestError (/server/node_modules/@prisma/client/runtime/library.js:124:6206)
```

### How to reproduce

See provided schema.

### Expected behavior

The deleteMany should work.

### Prisma information

```prisma
model ExternalServiceObjectFieldConfiguration {
  id                     Int                            @default(autoincrement())
  createdAt              DateTime                       @default(now())
  updatedAt              DateTime?
  objectType             ExternalServiceObjectType
  fieldName              String
  displayOrder           Int?
  organizationId         Int
  organization           Organization                   @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  serviceConfigurationId Int
  serviceConfiguration   ExternalServiceConfiguration   @relation(fields: [organizationId, serviceConfigurationId], references: [organizationId, id], onDelete: Cascade)
  customFieldSetId       Int?
  customFieldSet         ExternalServiceCustomFieldSet? @relation(fields: [organizationId, customFieldSetId], references: [organizationId, id], onDelete: Cascade)

  @@id([organizationId, id])
  @@unique([organizationId, serviceConfigurationId, customFieldSetId, fieldName, objectType])
  @@index([organizationId, serviceConfigurationId, customFieldSetId, objectType])
}

model ExternalServiceCustomFieldSet {
  id                     Int                                       @default(autoincrement())
  createdAt              DateTime                                  @default(now())
  updatedAt              DateTime?
  organizationId         Int
  organization           Organization                              @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  name                   String
  description            String?
  serviceConfigurationId Int
  serviceConfiguration   ExternalServiceConfiguration              @relation(fields: [organizationId, serviceConfigurationId], references: [organizationId, id], onDelete: Cascade)
  fieldConfigurations    ExternalServiceObjectFieldConfiguration[]
  fieldSetUserTokens     ExternalServiceUserToken[]

  @@id([organizationId, id])
  @@index([organizationId])
  @@index([organizationId, serviceConfigurationId])
}
```

```ts
      // fieldsetId is number | null | undefined
      prisma.externalServiceObjectFieldConfiguration.deleteMany({
        where: {
          organizationId,
          serviceConfigurationId: configurationId,
          customFieldSetId: fieldsetId || null,
          objectType: SalesforceObjectToMeetingflowObject[sObject],
          fieldName: {
            notIn: fields,
          },
        },
      }),
```
The generated type for the deleteMany where clause looks correct, and there are no ts compiler errors with the code:

```ts
  export type ExternalServiceObjectFieldConfigurationWhereInput = {
    AND?: ExternalServiceObjectFieldConfigurationWhereInput | ExternalServiceObjectFieldConfigurationWhereInput[]
    OR?: ExternalServiceObjectFieldConfigurationWhereInput[]
    NOT?: ExternalServiceObjectFieldConfigurationWhereInput | ExternalServiceObjectFieldConfigurationWhereInput[]
    id?: IntFilter<"ExternalServiceObjectFieldConfiguration"> | number
    createdAt?: DateTimeFilter<"ExternalServiceObjectFieldConfiguration"> | Date | string
    updatedAt?: DateTimeNullableFilter<"ExternalServiceObjectFieldConfiguration"> | Date | string | null
    objectType?: EnumExternalServiceObjectTypeFilter<"ExternalServiceObjectFieldConfiguration"> | $Enums.ExternalServiceObjectType
    fieldName?: StringFilter<"ExternalServiceObjectFieldConfiguration"> | string
    displayOrder?: IntNullableFilter<"ExternalServiceObjectFieldConfiguration"> | number | null
    organizationId?: IntFilter<"ExternalServiceObjectFieldConfiguration"> | number
    serviceConfigurationId?: IntFilter<"ExternalServiceObjectFieldConfiguration"> | number
    customFieldSetId?: IntNullableFilter<"ExternalServiceObjectFieldConfiguration"> | number | null
    organization?: XOR<OrganizationRelationFilter, OrganizationWhereInput>
    serviceConfiguration?: XOR<ExternalServiceConfigurationRelationFilter, ExternalServiceConfigurationWhereInput>
    customFieldSet?: XOR<ExternalServiceCustomFieldSetNullableRelationFilter, ExternalServiceCustomFieldSetWhereInput> | null
  }

  export type IntNullableFilter<$PrismaModel = never> = {
    equals?: number | IntFieldRefInput<$PrismaModel> | null
    in?: number[] | ListIntFieldRefInput<$PrismaModel> | null
    notIn?: number[] | ListIntFieldRefInput<$PrismaModel> | null
    lt?: number | IntFieldRefInput<$PrismaModel>
    lte?: number | IntFieldRefInput<$PrismaModel>
    gt?: number | IntFieldRefInput<$PrismaModel>
    gte?: number | IntFieldRefInput<$PrismaModel>
    not?: NestedIntNullableFilter<$PrismaModel> | number | null
  }
```

### Environment & setup

- OS: Pop_OS! 22.04
- Database: PostgreSQL
- Node.js version: v18.17.1

### Prisma Version

```
prisma                  : 5.6.0
@prisma/client          : 5.6.0
Computed binaryTarget   : debian-openssl-1.1.x
Operating System        : linux
Architecture            : x64
Node.js                 : v18.17.1
Query Engine (Node-API) : libquery-engine e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.6.0-32.e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Default Engines Hash    : e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Studio                  : 0.495.0
Preview Features        : fullTextIndex, fullTextSearch
```

**Comment by rcbevans** [comment]
Here's more comprehensive subset of the schema

```prisma
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["native", "debian-openssl-1.1.x", "windows"]
  previewFeatures = ["fullTextSearch", "fullTextIndex"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id                                           Int                                          @id @default(autoincrement())
  createdAt                                    DateTime                                     @default(now())
  updatedAt                                    DateTime?
  email                                        String                                       @unique
  name                                         String?
  
  externalServiceTokens                        ExternalServiceUserToken[]
  organizationMemberships                      OrganizationMembership[]
  
  @@index([email])
}

model Organization {
  id                Int                   @id @default(autoincrement())
  name              String

  memberships                              OrganizationMembership[]
  externalServiceUserTokens                ExternalServiceUserToken[]
  externalServiceConfigs                   ExternalServiceConfiguration[]
  externalServiceObjectFieldConfigurations ExternalServiceObjectFieldConfiguration[]
}

model ExternalServiceConfiguration {
  id                                       Int                                       @default(autoincrement())
  organizationId                           Int
  organization                             Organization                              @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  app                                      Application
  instanceId                               String                                    @default("DEFAULT")
  externalServiceUserTokens                ExternalServiceUserToken[]
  externalServiceObjectFieldConfigurations ExternalServiceObjectFieldConfiguration[]

  @@id([organizationId, id])
  @@unique([organizationId, instanceId])
  @@index([organizationId])
}

model ExternalServiceUserToken {
  id                      Int                            @default(autoincrement())
  state                   TokenState                     @default(OK)
  externalUserId          String?
  organizationId          Int
  organization            Organization                   @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  ownerId                 Int
  owner                   User                           @relation(fields: [ownerId], references: [id], onDelete: Cascade)
  serviceConfigurationId  Int
  serviceConfiguration    ExternalServiceConfiguration   @relation(fields: [organizationId, serviceConfigurationId], references: [organizationId, id], onDelete: Cascade)
  defaultCustomFieldSetId Int?
  defaultCustomFieldSet   ExternalServiceCustomFieldSet? @relation(fields: [organizationId, defaultCustomFieldSetId], references: [organizationId, id], onDelete: Restrict)

  @@id([organizationId, id])
  @@unique([organizationId, ownerId, serviceConfigurationId])
  @@index([ownerId])
  @@index([organizationId, ownerId])
}

model ExternalServiceObjectFieldConfiguration {
  id                     Int                            @default(autoincrement())
  createdAt              DateTime                       @default(now())
  updatedAt              DateTime?
  objectType             ExternalServiceObjectType
  fieldName              String
  displayOrder           Int?
  organizationId         Int
  organization           Organization                   @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  serviceConfigurationId Int
  serviceConfiguration   ExternalServiceConfiguration   @relation(fields: [organizationId, serviceConfigurationId], references: [organizationId, id], onDelete: Cascade)
  customFieldSetId       Int?
  customFieldSet         ExternalServiceCustomFieldSet? @relation(fields: [organizationId, customFieldSetId], references: [organizationId, id], onDelete: Cascade)

  @@id([organizationId, id])
  @@unique([organizationId, serviceConfigurationId, customFieldSetId, fieldName, objectType])
  @@index([organizationId, serviceConfigurationId, customFieldSetId, objectType])
}

model ExternalServiceCustomFieldSet {
  id                     Int                                       @default(autoincrement())
  createdAt              DateTime                                  @default(now())
  updatedAt              DateTime?
  organizationId         Int
  organization           Organization                              @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  name                   String
  description            String?
  serviceConfigurationId Int
  serviceConfiguration   ExternalServiceConfiguration              @relation(fields: [organizationId, serviceConfigurationId], references: [organizationId, id], onDelete: Cascade)
  fieldConfigurations    ExternalServiceObjectFieldConfiguration[]
  fieldSetUserTokens     ExternalServiceUserToken[]

  @@id([organizationId, id])
  @@index([organizationId])
  @@index([organizationId, serviceConfigurationId])
}

model OrganizationMembership {
  id                Int                  @default(autoincrement())
  role              OrganizationUserRole
  organizationId    Int
  organization      Organization         @relation(fields: [organizationId], references: [id], onDelete: Cascade)
  userId            Int
  user              User                 @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@id([id, organizationId])
  @@unique([organizationId, userId])
  @@index([userId])
  @@index([organizationId])
  @@index([organizationId, role])
  @@index([userId, organizationId])
}

enum OrganizationUserRole {
  ADMIN
  CREATOR
  COLLABORATOR
  GUEST
}

enum Application {
  GOOGLE
  M365
  SALESFORCE
  HUBSPOT
  SLACK
  TEAMS
}

enum TokenState {
  OK
  ERROR
}
```

**Comment by rcbevans** [comment]
It's exactly the same error on the upsert, I suspect both are due to #22016 assuming similar logic is used to build the validators as generate the types.

```ts
    await prisma.$transaction([
      prisma.externalServiceObjectFieldConfiguration.deleteMany({
        where: {
          organizationId,
          serviceConfigurationId: configurationId,
          customFieldSetId: fieldsetId || null,
          objectType: SalesforceObjectToMeetingflowObject[sObject],
          fieldName: {
            notIn: fields,
          },
        },
      }),
      ...fields.map((fieldName, idx) =>
        prisma.externalServiceObjectFieldConfiguration.upsert({
          where: {
            organizationId_serviceConfigurationId_customFieldSetId_fieldName_objectType:
              {
                organizationId,
                serviceConfigurationId: configurationId,
                //@ts-ignore https://github.com/prisma/prisma/issues/22016
                customFieldSetId: fieldsetId || null,
                fieldName,
                objectType: SalesforceObjectToMeetingflowObject[sObject],
              },
          },
          create: {
            organizationId,
            serviceConfigurationId: configurationId,
            customFieldSetId: fieldsetId || null,
            objectType: SalesforceObjectToMeetingflowObject[sObject],
            fieldName,
            displayOrder: idx,
          },
          update: {
            updatedAt: new Date(),
            displayOrder: idx,
          },
        })
      ),
    ]);
```

```
error:   ┏ 
Invalid `prisma.externalServiceObjectFieldConfiguration.deleteMany()` invocation in
/.ts:670:54

  667 }
  668 
  669 await prisma.$transaction([
→ 670   prisma.externalServiceObjectFieldConfiguration.deleteMany({
          where: {
            organizationId: 2,
            serviceConfigurationId: 6,
            customFieldSetId: null,
            objectType: "DEAL",
            fieldName: {
              notIn: [
                "LastActivityDate",
                "Decision_Process__c",
                "Amount",
                "CloseDate",
                "NextStep",
                "StageName",
                "Champion__c"
              ]
            }
          }
        })

Argument `customFieldSetId` is missing.
error:   ┏ 
Invalid `prisma.externalServiceObjectFieldConfiguration.upsert()` invocation in
/.ts:682:56

  679   },
  680 }),
  681 ...fields.map((fieldName, idx) =>
→ 682   prisma.externalServiceObjectFieldConfiguration.upsert({
          where: {
            organizationId_serviceConfigurationId_customFieldSetId_fieldName_objectType: {
              organizationId: 2,
              serviceConfigurationId: 6,
              fieldName: "LastActivityDate",
              objectType: "DEAL",
        +     customFieldSetId: Int
            }
          },
          create: {
            organizationId: 2,
            serviceConfigurationId: 6,
            customFieldSetId: null,
            objectType: "DEAL",
            fieldName: "LastActivityDate",
            displayOrder: 0
          },
          update: {
            updatedAt: new Date("2023-11-20T19:28:51.359Z"),
            displayOrder: 0
          }
        })

Argument `customFieldSetId` must not be null.
```

**Comment by rcbevans** [comment]
The error with prisma debug set doesn't look particularly informative:

```
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +4ms
  prisma:client  Prisma Client call: +673ms
  prisma:client  prisma.externalServiceObjectFieldConfiguration.deleteMany({
  where: {
    organizationId: 2,
    serviceConfigurationId: 6,
    customFieldSetId: null,
    objectType: "DEAL",
    fieldName: {
      notIn: [
        "LastActivityDate",
        "Decision_Process__c",
        "Amount",
        "CloseDate",
        "NextStep",
        "StageName",
        "Champion__c"
      ]
    }
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  {
  "modelName": "ExternalServiceObjectFieldConfiguration",
  "action": "deleteMany",
  "query": {
    "arguments": {
      "where": {
        "organizationId": 2,
        "serviceConfigurationId": 6,
        "customFieldSetId": null,
        "objectType": "DEAL",
        "fieldName": {
          "notIn": [
            "LastActivityDate",
            "Decision_Process__c",
            "Amount",
            "CloseDate",
            "NextStep",
            "StageName",
            "Champion__c"
          ]
        }
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true
    }
  }
}
 +0ms
  prisma:client  Prisma Client call: +1ms
  prisma:client  prisma.externalServiceObjectFieldConfiguration.upsert({
  where: {
    organizationId_serviceConfigurationId_customFieldSetId_fieldName_objectType: {
      organizationId: 2,
      serviceConfigurationId: 6,
      customFieldSetId: null,
      fieldName: "LastActivityDate",
      objectType: "DEAL"
    }
  },
  create: {
    organizationId: 2,
    serviceConfigurationId: 6,
    customFieldSetId: null,
    objectType: "DEAL",
    fieldName: "LastActivityDate",
    displayOrder: 0
  },
  update: {
    updatedAt: new Date("2023-11-20T19:35:01.822Z"),
    displayOrder: 0
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  {
  "modelName": "ExternalServiceObjectFieldConfiguration",
  "action": "upsertOne",
  "query": {
    "arguments": {
      "where": {
        "organizationId_serviceConfigurationId_customFieldSetId_fieldName_objectType": {
          "organizationId": 2,
          "serviceConfigurationId": 6,
          "customFieldSetId": null,
          "fieldName": "LastActivityDate",
          "objectType": "DEAL"
        }
      },
      "create": {
        "organizationId": 2,
        "serviceConfigurationId": 6,
        "customFieldSetId": null,
        "objectType": "DEAL",
        "fieldName": "LastActivityDate",
        "displayOrder": 0
      },
      "update": {
        "updatedAt": {
          "$type": "DateTime",
          "value": "2023-11-20T19:35:01.822Z"
        },
        "displayOrder": 0
      }
    },
    "selection": {
      "$composites": true,
      "$scalars": true
    }
  }
}
 +0ms
  prisma:client:libraryEngine  requestBatch +679ms
  prisma:client:request_handler  PrismaClientKnownRequestError: `where.organizationId_serviceConfigurationId_customFieldSetId_fieldName_objectType.customFieldSetId`: A value is required but not set
    at Pr (/./node_modules/@prisma/client/runtime/library.js:36:253)
    at Wt.buildQueryError (/./node_modules/@prisma/client/runtime/library.js:116:978)
    at Wt.requestBatch (/./node_modules/@prisma/client/runtime/library.js:116:409)
    at /./node_modules/@prisma/client/runtime/library.js:124:5022 {
  code: 'P2012',
  clientVersion: '5.6.0',
  meta: {
    kind: 'RequiredArgumentMissing',
    inputTypes: [ [Object] ],
    argumentPath: [
      'where',
      'organizationId_serviceConfigurationId_customFieldSetId_fieldName_objectType',
      'customFieldSetId'
    ],
    selectionPath: [ 'upsertOneExternalServiceObjectFieldConfiguration' ]
  }
} +0ms
prisma:error 
Invalid `prisma.externalServiceObjectFieldConfiguration.deleteMany()` invocation in
/.ts:670:54

  667 }
  668 
  669 await prisma.$transaction([
→ 670   prisma.externalServiceObjectFieldConfiguration.deleteMany({
          where: {
            organizationId: 2,
            serviceConfigurationId: 6,
            customFieldSetId: null,
            objectType: "DEAL",
            fieldName: {
              notIn: [
                "LastActivityDate",
                "Decision_Process__c",
                "Amount",
                "CloseDate",
                "NextStep",
                "StageName",
                "Champion__c"
              ]
            }
          }
        })

Argument `customFieldSetId` is missing.
  prisma:client:request_handler  PrismaClientKnownRequestError: `where.organizationId_serviceConfigurationId_customFieldSetId_fieldName_objectType.customFieldSetId`: A value is required but not set
    at Pr (/./node_modules/@prisma/client/runtime/library.js:36:253)
    at Wt.buildQueryError (/./node_modules/@prisma/client/runtime/library.js:116:978)
    at Wt.requestBatch (/./node_modules/@prisma/client/runtime/library.js:116:409)
    at /./node_modules/@prisma/client/runtime/library.js:124:5022 {
  code: 'P2012',
  clientVersion: '5.6.0',
  meta: {
    kind: 'RequiredArgumentMissing',
    inputTypes: [ [Object] ],
    argumentPath: [
      'where',
      'organizationId_serviceConfigurationId_customFieldSetId_fieldName_objectType',
      'customFieldSetId'
    ],
    selectionPath: [ 'upsertOneExternalServiceObjectFieldConfiguration' ]
  }
} +35ms
prisma:error 
Invalid `prisma.externalServiceObjectFieldConfiguration.upsert()` invocation in
/.ts:682:56

  679   },
  680 }),
  681 ...fields.map((fieldName, idx) =>
→ 682   prisma.externalServiceObjectFieldConfiguration.upsert({
          where: {
            organizationId_serviceConfigurationId_customFieldSetId_fieldName_objectType: {
              organizationId: 2,
              serviceConfigurationId: 6,
              fieldName: "LastActivityDate",
              objectType: "DEAL",
        +     customFieldSetId: Int
            }
          },
          create: {
            organizationId: 2,
            serviceConfigurationId: 6,
            customFieldSetId: null,
            objectType: "DEAL",
            fieldName: "LastActivityDate",
            displayOrder: 0
          },
          update: {
            updatedAt: new Date("2023-11-20T19:35:01.822Z"),
            displayOrder: 0
          }
        })

Argument `customFieldSetId` must not be null.

```
