### ISSUE TITLE
Prisma Fails to Connect to MongoDB Atlas Cluster

### ISSUE THREAD

**Issue by XiroXD** [prisma/prisma#22051]
### Bug description

Prisma fails to connect to the MongoDB cluster with the error: 
```
Error in connector: Failed to create database connection. (Type: An error occurred during DNS resolution: io error: Error parsing resolv.conf: ProtoError { Type: Msg("Bad label: com$router") }, labels: {})
```
Prisma logs after running with `DEBUG="*"` env variable:
```
2023-11-21T15:09:29.659Z prisma:tryLoadEnv  Environment variables loaded from /home/xir/Projects/Personal/TypeScript/Prisma-test/.env
2023-11-21T15:09:29.666Z prisma:client  checkPlatformCaching:postinstall undefined
2023-11-21T15:09:29.667Z prisma:client  checkPlatformCaching:ciName undefined
2023-11-21T15:09:29.668Z prisma:tryLoadEnv  Environment variables loaded from /home/xir/Projects/Personal/TypeScript/Prisma-test/.env
2023-11-21T15:09:29.668Z prisma:client  dirname /home/xir/Projects/Personal/TypeScript/Prisma-test/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/.prisma/client
2023-11-21T15:09:29.668Z prisma:client  relativePath ../../../../../../prisma
2023-11-21T15:09:29.669Z prisma:client  cwd /home/xir/Projects/Personal/TypeScript/Prisma-test/prisma
2023-11-21T15:09:29.669Z prisma:client  clientVersion 5.6.0
2023-11-21T15:09:29.671Z prisma:client:libraryEngine  internalSetup
2023-11-21T15:09:29.675Z prisma:client  Prisma Client call:
2023-11-21T15:09:29.675Z prisma:client  prisma.user.findMany()
2023-11-21T15:09:29.675Z prisma:client  Generated request:
2023-11-21T15:09:29.675Z prisma:client  {
  "modelName": "User",
  "action": "findMany",
  "query": {
    "arguments": {},
    "selection": {
      "$composites": true,
      "$scalars": true
    }
  }
}

2023-11-21T15:09:29.676Z prisma:client:libraryEngine  sending request, this.libraryStarted: false
2023-11-21T15:09:29.680Z prisma:get-platform  Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "arch",
  "originalDistro": "arch"
}
2023-11-21T15:09:29.680Z prisma:get-platform  Don't know any platform-specific paths for "arch" on x64 (x86_64)
2023-11-21T15:09:29.680Z prisma:get-platform  Falling back to "ldconfig" and other generic paths
2023-11-21T15:09:29.703Z prisma:get-platform  Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl3.so
libssl.so
libssl.so.3
"
2023-11-21T15:09:29.703Z prisma:get-platform  Found libssl.so file using "ldconfig" or other generic paths: libssl3.so
libssl.so
libssl.so.3

2023-11-21T15:09:29.704Z prisma:get-platform  The parsed libssl version is: 3.0.x
2023-11-21T15:09:29.705Z prisma:client:engines:resolveEnginePath  enginePath /home/xir/Projects/Personal/TypeScript/Prisma-test/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
2023-11-21T15:09:29.713Z prisma:client:libraryEngine  library starting
2023-11-21T15:09:29.718Z prisma:client:request_handler  PrismaClientInitializationError: Error in connector: Error creating a database connection. (Kind: An error occurred during DNS resolution: io error: Error parsing resolv.conf: ProtoError { kind: Msg("Malformed label: com$router") }, labels: {})
    at r (/home/xir/Projects/Personal/TypeScript/Prisma-test/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:115:2752)
    at async Wt.request (/home/xir/Projects/Personal/TypeScript/Prisma-test/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:115:3902)
    at async Object.singleLoader (/home/xir/Projects/Personal/TypeScript/Prisma-test/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:124:5333)
    at async ni.request (/home/xir/Projects/Personal/TypeScript/Prisma-test/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:124:5825)
    at async l (/home/xir/Projects/Personal/TypeScript/Prisma-test/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:129:10023) {
  clientVersion: '5.6.0',
  errorCode: undefined
}
PrismaClientInitializationError: 
Invalid `prisma.user.findMany()` invocation in
/home/xir/Projects/Personal/TypeScript/Prisma-test/index.ts:6:38

  3 const prisma = new PrismaClient();
  4 
  5 async function main() {
→ 6   const allUsers = await prisma.user.findMany(
Error in connector: Error creating a database connection. (Kind: An error occurred during DNS resolution: io error: Error parsing resolv.conf: ProtoError { kind: Msg("Malformed label: com$router") }, labels: {})
    at ni.handleRequestError (/home/xir/Projects/Personal/TypeScript/Prisma-test/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:124:7090)
    at ni.handleAndLogRequestError (/home/xir/Projects/Personal/TypeScript/Prisma-test/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:124:6206)
    at ni.request (/home/xir/Projects/Personal/TypeScript/Prisma-test/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:124:5926)
    at async l (/home/xir/Projects/Personal/TypeScript/Prisma-test/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client/runtime/library.js:129:10023) {
  clientVersion: '5.6.0',
  errorCode: undefined
}

```

I am not sure if this is a problem that only occurs on the Atlas cluster, but I have seen a similar problem reported in issue #13370.

### How to reproduce

1. Create a free cluster on MongoDB Atlas
2. Use connection string for 3.0 or later NodeJS MongoDB driver version

### Prisma information

```prisma
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id       String    @id @default(auto()) @map("_id") @db.ObjectId
  slug     String    @unique
  title    String
  body     String
  author   User      @relation(fields: [authorId], references: [id])
  authorId String    @db.ObjectId
  comments Comment[]
}

model User {
  id      String   @id @default(auto()) @map("_id") @db.ObjectId
  email   String   @unique
  name    String?
  address Address?
  posts   Post[]
}

model Comment {
  id      String @id @default(auto()) @map("_id") @db.ObjectId
  comment String
  post    Post   @relation(fields: [postId], references: [id])
  postId  String @db.ObjectId
}

type Address {
  street String
  city   String
  state  String
  zip    String
}

```

```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const allUsers = await prisma.user.findMany();
  console.log(allUsers);

  await prisma.user.create({
    data: {
      name: "Rich",
      email: "hello@prisma.com",
      posts: {
        create: {
          title: "My first post",
          body: "Lots of really interesting stuff",
          slug: "my-first-post",
        },
      },
    },
  });

  const users = await prisma.user.findMany({
    include: {
      posts: true,
    },
  });
  console.dir(users, { depth: null });
}

main()
  .catch(async (e) => {
    console.error(e);
    process.exit(1);
  })

  .finally(async () => {
    await prisma.$disconnect();
  });

```

### Environment & setup

- OS: Arch Linux
- Database: MongoDB
- Node.js version: `v21.2.0`

### Prisma Version

```
prisma                  : 5.6.0
@prisma/client          : 5.6.0
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v21.2.0
Query Engine (Node-API) : libquery-engine e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/.pnpm/@prisma+engines@5.6.0/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/.pnpm/@prisma+engines@5.6.0/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.6.0-32.e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Default Engines Hash    : e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Studio                  : 0.495.0
```

**Comment by XiroXD** [comment]
I also found a workaround for this problem by using the connection string for the `v2.2.12` driver version provided by Atlas.

**Comment by janpio** [comment]
Can you share an anonymized version of the two connection string you were/are using?
