### ISSUE TITLE
PrismaClientInitializationError:  Invalid `prisma.tenant.findUnique()` invocation

### ISSUE THREAD

**Issue by kaustubhdevstack** [prisma/prisma#22122]
### Bug description

I am creating a user authentication system for my SaaS and while registering new user I am getting following error:

```
PrismaClientInitializationError: 
Invalid `prisma.tenant.findUnique()` invocation:

Authentication failed against database server at `db.hgitddkezniwnyeiqqup.supabase.co`, the provided database credentials for `postgres` are not valid.

Please make sure to provide valid database credentials for the database server at `db.hgitddkezniwnyeiqqup.supabase.co`.
    at ni.handleRequestError (E:\Xampp\htdocs\digiforge\node_modules\@prisma\client\runtime\library.js:124:7090)
    at ni.handleAndLogRequestError (E:\Xampp\htdocs\digiforge\node_modules\@prisma\client\runtime\library.js:124:6206)
    at ni.request (E:\Xampp\htdocs\digiforge\node_modules\@prisma\client\runtime\library.js:124:5926)
    at async l (E:\Xampp\htdocs\digiforge\node_modules\@prisma\client\runtime\library.js:129:10023)    at async POST (webpack-internal:///(rsc)/./app/api/user/route.ts:46:30)
    at async E:\Xampp\htdocs\digiforge\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:62609 {
  clientVersion: '5.6.0',
  errorCode: undefined
}
```
Also the authentication error weird considering I have entered the URI along with right password (Even tried resetting the old password) 

This is my API code for registering user

// pages/api/user/route.ts

```ts
import prisma from '@/lib/prisma';
import { hash } from 'bcrypt';
import { NextResponse } from 'next/server';
import * as z from 'zod';

// Validating API response
const userSchema = z.object({
  name: z.string().min(1, 'Full Name is required').max(100),
  email: z.string().min(1, 'Email is required').email('Invalid email'),
  passwd: z.string().min(8, 'Password must have 8-15 characters'),
  account: z.string(),
  usrtype: z.number(),
  plan: z.string(),
});

export async function POST(req: Request) {
    try {
     const body = await req.json();

      // Check for the presence of all required fields
      const requiredFields = ['name', 'email', 'passwd', 'account', 'usrtype', 'plan'];
      const missingFields = requiredFields.filter(field => !(field in body));

      if (missingFields.length > 0) {
        return NextResponse.json(
          { message: `Missing required fields: ${missingFields.join(', ')}` },
          { status: 400 }
        );
      }

      const { name, email, passwd, account, usrtype, plan } = userSchema.parse(body);

      // Check if the email already exists
      const existingUser = await prisma.tenant.findUnique({
        where: { email: email },
      });

      if (existingUser) {
        return NextResponse.json(
          { user: null, message: 'User already exists' },
          { status: 409 }
        );
      }

      // Password hashing
      const hashedPassword = await hash(passwd, 10);
      const newUser = await prisma.tenant.create({
        data: {
          name,
          email,
          passwd: hashedPassword,
          account,
          usrtype,
          plan,
        },
      });

      const { passwd: newUserPassword, ...rest } = newUser;

      return NextResponse.json(
        { userId: newUser.id, message: 'User created successfully' },
        { status: 201 }
      );
    } catch (error) {
      console.log(error);
      return NextResponse.json(
        { message: 'Something went wrong, please try again' },
        { status: 500 }
      );
    }
  }
```

### How to reproduce

1. Install Next js 14.0.3 with Typescript
2. In app folder create API folder 
3. Inside API folder create user folder
4. Create route.ts file and paste the code (Install all the required dependencies 
5. Run command - npm run dev
6. Open postman and use http://localhost:3000/api/user
7. Fill the required inputs in the request and click on send you will receive internal server 500 error however in the terminal and console you will get the above mentioned error.

### Expected behavior

It should return the status of 201 and get the user registered

### Prisma information

This is my prisma schema

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Tenant {
  id        Int @id @default(autoincrement())
  email     String @unique
  passwd    String?
  name      String?
  account   String?
  plan      String?
  acstatus  Boolean @default(false)
  usrtype   Int
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  profile   ProfileBio?
}

model ProfileBio {
  id     Int     @id @default(autoincrement())
  userId Int?    @unique
  bio    String?
  user   Tenant?  @relation(fields: [userId], references: [id])
}
```
**Update:** This is prisma.ts file invoking client:

```
import { PrismaClient } from '@prisma/client'

const prismaClientSingleton = () => {
  return new PrismaClient()
}

type PrismaClientSingleton = ReturnType<typeof prismaClientSingleton>

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClientSingleton | undefined
}

const prisma = globalForPrisma.prisma ?? prismaClientSingleton()

export default prisma

if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma
```

### Environment & setup

- OS: Windows 10
- Database - Postgres Prisma using Supabase
- Node Version - 20.0.9
- Next JS - 14.0.3

### Prisma Version

```
prisma": "^5.6.0"
```

**Comment by MezianeKhalil** [comment]
The error message you're encountering indicates that there is an authentication failure when trying to connect to the PostgreSQL database server at db.hgitddkezniwnyeiqqup.supabase.co using the provided database credentials for the user postgres. This typically means that the username or password you are using to authenticate with the PostgreSQL server is incorrect or not authorized.

**Comment by kaustubhdevstack** [comment]
Well, I tried with new credentials as well but doesn't seem to work

**Comment by kaustubhdevstack** [comment]
Problem solved: Went to Supabase, restarted the entire database
It seems problems was from Supabase side.
