### ISSUE TITLE
Can't find prisma binary on vercel serverless

### ISSUE THREAD

**Issue by nabi-chan** [prisma/prisma#22142]
### Bug description

When I deploy my project on vercel, It always throws this error.
It seems generating prisma client not work.
Tested on pnpm 8.6.8, yarn 1.22.18

```
Unhandled rejection: PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "rhel-openssl-1.0.x".

This is likely caused by a bundler that has not copied "libquery_engine-rhel-openssl-1.0.x.so.node" next to the resulting bundle.
Ensure that "libquery_engine-rhel-openssl-1.0.x.so.node" has been copied next to the bundle or in "node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/.prisma/client".

We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-bundler-investigation

The following locations have been searched:
  /var/task/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/.prisma/client
  /var
  /vercel/path0/node_modules/.pnpm/@prisma+client@5.6.0_prisma@5.6.0/node_modules/@prisma/client
  /.prisma/client
  /tmp/prisma-engines
    at il (/var/task/index.js:67:805)
    at async Object.loadLibrary (/var/task/index.js:114:9808)
    at async Wt.loadEngine (/var/task/index.js:115:448)
    at async Wt.instantiateLibrary (/var/task/index.js:114:19566) {
  clientVersion: '5.6.0',
  errorCode: undefined
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

### How to reproduce

1. Clone this repo [nabi-chan/vercel-test](https://github.com/nabi-chan/vercel-test)
2. deploy it to vercel
3. after build, enter the deployment
4. It reproduced!

### Expected behavior

Find prisma binary and correctly works

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int    @id @default(autoincrement())
  email String @unique

  name     String?
  password String

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

```ts
const prisma = new PrismaClient();
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v20.10.0
- Package Manager : pnpm

### Prisma Version

```
prisma                  : 5.6.0
@prisma/client          : 5.6.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v16.15.0
Query Engine (Node-API) : libquery-engine e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/.pnpm/@prisma+engines@5.6.0/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli e95e739751f42d8ca026f6b910f5a2dc5adeaeee (at node_modules/.pnpm/@prisma+engines@5.6.0/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.6.0-32.e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Default Engines Hash    : e95e739751f42d8ca026f6b910f5a2dc5adeaeee
Studio                  : 0.495.0
```

**Comment by janpio** [comment]
I actually get a different error message:
```
PrismaClientInitializationError: Prisma Client could not find its `schema.prisma`. This is likely caused by a bundling step, which leads to `schema.prisma` not being copied near the resulting bundle. We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/bundler-investigation-error
    at new ir (/var/task/index.js:107:118)
    at t.getEngine (/var/task/index.js:177:6126)
    at new t (/var/task/index.js:177:5710)
    at Object.<anonymous> (/var/task/index.js:187:2735)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at r.<computed>.e._load (/var/task/___vc/__launcher/__launcher.js:14:2516)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29) {
  clientVersion: '4.16.2',
  errorCode: undefined
}
```
Did you already do anything with your setup to overcome this, and then land on the error above?

**Comment by likerRr** [comment]
Faced the same issue. @janpio , can you provide any workaround or the info about fixing ability?

**Comment by janpio** [comment]
No, but you could help by looking at the reproduction above and shared what is similar to your situation. Is this related to [one of these dependencies](https://github.com/nabi-chan/vercel-test/blob/5d9ccfc7f034d05f1a2fd814f105d63c2534c538/package.json#L16-L58)?

Optimally provide your own reproduction for us so we can take a look at that one as well.

**Comment by willrally** [comment]
Are there any updates on this? I'm using tsup with turborepo and I cannot build my docker image because of the same reason

```
PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "darwin-arm64".

This is likely caused by a bundler that has not copied "libquery_engine-darwin-arm64.dylib.node" next to the resulting bundle.
Ensure that "libquery_engine-darwin-arm64.dylib.node" has been copied next to the bundle or in "packages/api/dist".

We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-bundler-investigation
```

**Comment by wmtrinu** [comment]
Are there any updates on this? I'm having the same error, I cannot run my container based on my image

```
PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "darwin-arm64".

This is likely caused by a bundler that has not copied "libquery_engine-darwin-arm64.dylib.node" next to the resulting bundle.
Ensure that "libquery_engine-darwin-arm64.dylib.node" has been copied next to the bundle or in "packages/api/dist".

We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-bundler-investigation
```

**Comment by matmill5** [comment]
Same issue - have tried a number of suggestions online, but nothing is working.

During the vercel build phase, the libquery_engine-rhel-openssl-3.0.x.so.node is present in the ./node_modules/@prisma/client/fast-pos directory, but not bundled into the vercel functions.

I tried the @prisma nextjs-monorepo-workaround, but that broke the local next build.

I am on pnpm monorepo, next@15.0.4, and prisma@6.1.0

prisma:error 
Invalid `prisma.application.findMany()` invocation:

Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x".

We detected that you are using Next.js, learn how to fix this: https://pris.ly/d/engine-not-found-nextjs.

This is likely caused by a bundler that has not copied "libquery_engine-rhel-openssl-3.0.x.so.node" next to the resulting bundle.
Ensure that "libquery_engine-rhel-openssl-3.0.x.so.node" has been copied next to the bundle or in "node_modules/@prisma/client/fast-pos".

We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-bundler-investigation

The following locations have been searched:
  /var/task/packages/frontend/products/fast-pos/node_modules/@prisma/client/fast-pos
  /var/task/packages/frontend/products/fast-pos/.next/server
  /vercel/path0/packages/frontend/products/fast-pos/node_modules/@prisma/client/fast-pos
  /var/task/packages/frontend/products/fast-pos/.prisma/client
  /tmp/prisma-engines
Error [PrismaClientInitializationError]:

**Comment by Souravgodara** [comment]
Facing the same issue, is there any workaround ? I'm using turborepo.

**Comment by bwegrzyn** [comment]
Also facing the same issue. I spent a day trying everything under the sun to get this working. The only workaround that I was able to get going was with this webpack plugin: https://www.npmjs.com/package/@prisma/nextjs-monorepo-workaround-plugin

Unfortunately, this causes Turborepo to use webpack instead of turbopack. It seems like prisma is incompatible with this sort of Vercel, Next.js, Turbopack monorepo setup.

**Comment by rnnyrk** [comment]
@bwegrzyn Do you be any change have an example? Fine with using Webpack (didn't upgrade to Turbopack yet), but this error is driving me crazy. Deploying on Vercel keeps giving me the error 
> Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x".

Followed Prisma monorepo setup from their docs. Running Turborepo Prisma in `packages/db/generated/client`.
Try all sort of fixes with `outputFileTracingIncludes` in NextJS config and a `vercel.json` with:

```
"functions": {
    "app/api/**/*": {
      "includeFiles": "../../../../packages/db/generated/client/**"
    }
}
```

And believe me if I say I tried all different kind of import paths possible 😓

**Comment by bwegrzyn** [comment]
@rnnyrk Here is what my next.config.mjs file looks like. This file is under `/apps/<app name>/next.config.mjs` in my project.

```typescript
import { PrismaPlugin } from '@prisma/nextjs-monorepo-workaround-plugin'

/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: ["@workspace/ui"],
  webpack: (config, { isServer }) => {
    // This is a workaround to avoid this Prisma issue on Vercel
    // https://github.com/prisma/prisma/discussions/19499
    if (isServer) {
      config.plugins = [...config.plugins, new PrismaPlugin()]
    }

    return config
  },
}

export default nextConfig
```

**Comment by ricardomarsanc** [comment]
Hello, running Prisma in a package of turborepo, and I'm having this issue only when I deploy to Vercel (homepage issue, navigating to a different page works fine 🤷🏽). Anyone figured out how to solve this?

```
Unhandled Rejection: Error [PrismaClientInitializationError]: Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x".

We detected that you are using Next.js, learn how to fix this: https://pris.ly/d/engine-not-found-nextjs.

This is likely caused by a bundler that has not copied "libquery_engine-rhel-openssl-3.0.x.so.node" next to the resulting bundle.
Ensure that "libquery_engine-rhel-openssl-3.0.x.so.node" has been copied next to the bundle or in "generated/client".

We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-bundler-investigation

The following locations have been searched:
  /var/task/apps/web/generated/client
  /var/task/apps/web/.next/server
  /vercel/path0/packages/database/generated/client
  /var/task/apps/web/.prisma/client
  /tmp/prisma-engines
    at ml (.next/server/chunks/899.js:64:756)
    at async Object.loadLibrary (.next/server/chunks/899.js:111:9365)
    at async Bt.loadEngine (.next/server/chunks/899.js:112:448)
    at async Bt.instantiateLibrary (.next/server/chunks/899.js:111:13348) {
  clientVersion: '6.5.0',
  errorCode: undefined,
  retryable: undefined
}
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```

Using Node 20 and Prisma 6.5 (prisma version installed only in the database package, not globally).

This is my turbo.json:

```
{
  "$schema": "https://turbo.build/schema.json",
  "tasks": {
    "build": {
      "dependsOn": ["^build", "^db:generate"],
      "outputs": [".next/**", "!.next/cache/**"],
      "env": [
        "MOVIE_API_BASE_URL",
        "TMDB_API_KEY",
        "BASE_URL",
        "POSTGRES_PRISMA_URL",
        "POSTGRES_URL_NON_POOLING",
        "AUTH_SECRET"
      ]
    },
    "check-types": {
      "dependsOn": ["build", "^check-types"]
    },
    "dev": {
      "dependsOn": ["^db:generate"],
      "persistent": true,
      "cache": false
    },
    "db:generate": {
      "cache": false
    },
    "db:migrate": {
      "env": ["POSTGRES_PRISMA_URL", "POSTGRES_URL_NON_POOLING"],
      "cache": false,
      "persistent": true
    },
    "db:deploy": {
      "cache": false
    }
  }
}
```

**Comment by ricardomarsanc** [comment]
Update: made it work using the solution from @bwegrzyn and the workaround plugin. I still have some questions because there were some other errors when I tried to use the "edge" for running the queries with Prisma, NextAuth.js and NextJS, but in the end that was unrelated to this I think... The only issue with this is that I then cannot use `--turbo` but it is still discouraged from the NextAuth team given the problems it still has.

**Comment by matiasdecarli** [comment]
Facing the very same issue with Turborepo and next.js +15 (and prisma 6.5). 

Any solution? I don't get why event using `PRISMA_QUERY_ENGINE_BINARY` doesnt' seems to work

**Comment by ricardomarsanc** [comment]
@matiasdecarli seems that we have the very same config in our projects... TBH most of this things usually happen with new versions of NextJS, especially when working with also new versions of other packages like Turborepo or Prisma...

Seems that for now it is not possible to run this setup in the Edge, so I'm fixing it adding optimistic UI patterns instead until we have a more clear answer about how to setup this combo (Next + Prisma + Turborepo) in the edge.

**Comment by dr-msr** [comment]
+1 on this issue

**Comment by rafaelvicio** [comment]
+1

**Comment by PaulSinghDev** [comment]
I've been facing this issue myself and have found that the issue with Vercel seems to stem from the following:

- Having two instances of prisma within the app -- for example, one for auth and one for application logic
- Using the generator output in the schema

If you have a basic app which is just using one instance of Prisma and do not change the generator output, everything works as expected. When you add a generator output it looks as though Vercel's deployment pipeline does not copy over the engine which is where the issue is stemming from.

**Comment by olivierlesnicki** [comment]
Same issue here

````
Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x".

We detected that you are using Next.js, learn how to fix this: https://pris.ly/d/engine-not-found-nextjs.

This is likely caused by a bundler that has not copied "libquery_engine-rhel-openssl-3.0.x.so.node" next to the resulting bundle.
Ensure that "libquery_engine-rhel-openssl-3.0.x.so.node" has been copied next to the bundle or in "generated/client".

We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-bundler-investigation

The following locations have been searched:
  /var/task/apps/auth/generated/client
  /var/task/apps/auth/.next/server/app/api/auth
  /vercel/path0/packages/db/generated/client
  /var/task/apps/auth/.next/server/app/.prisma/client
  /tmp/prisma-engines
    at oL.handleRequestError (.next/server/app/api/auth/[...auth]/route.js:114:8288)
    at oL.handleAndLogRequestError (.next/server/app/api/auth/[...auth]/route.js:114:7049)
    at oL.request (.next/server/app/api/auth/[...auth]/route.js:114:6756)
    at async s (.next/server/app/api/auth/[...auth]/route.js:126:6317)
    at async Object.create (.next/server/app/api/auth/[...auth]/route.js:241:60373)
    at async Object.create (.next/server/app/api/auth/[...auth]/route.js:239:53216)
    at async createWithHooks (.next/server/app/api/auth/[...auth]/route.js:241:6332)
    at async Object.createVerificationValue (.next/server/app/api/auth/[...auth]/route.js:241:12991)
    at async sT (.next/server/app/api/auth/[...auth]/route.js:156:134124) {
  clientVersion: '6.7.0',
  errorCode: undefined
}
````

Prisma set to "latest"

**Comment by tuliren** [comment]
@RajvirS99, I had the exact same problem within a Turbo monorepo, and temporarily resolved it by NOT setting a custom `output` in `schema.prisma` file. This is not the recommended approach by Prisma, but it works for my case.

Also this package may be helpful: [`@prisma/nextjs-monorepo-workaround-plugin`](https://www.npmjs.com/package/@prisma/nextjs-monorepo-workaround-plugin). I have not tried it yet though.

**Comment by DiogoS** [comment]
I fixed it by removing the output dir and just letting Vercel to build & deploy everything instead of doing it on github via actions.

**Comment by Illyism** [comment]
Hi, I fixed it.

First, remove the output folder as mentioned above from schema.prisma

![Image](https://github.com/user-attachments/assets/39d5c12c-7f56-4ffb-9825-10232a650850)

Then update the index.ts file to point to @prisma/client

![Image](https://github.com/user-attachments/assets/0619599f-62a3-4606-87e4-8db207e52135)

That's the only change from https://www.prisma.io/docs/orm/more/help-and-troubleshooting/nextjs-help

Good luck!

**Comment by juggernog20** [comment]
Is there no other fix here? @Illyism's solution is going to be deprecated in two-ish months with Prisma 7

**Comment by ksmit799** [comment]
Same issue here, I had to move back from a custom output folder to letting Prisma generate to its own output path. I tried many things including attempting to copy the query engine manually with a JS script as part of the build process, but nothing has worked thus far. 

What's odd is that the error logs say that `/vercel/path0/packages/database/generated/prisma` was searched for the engine, and I could confirm that it was 100% there (as that's where I was trying to copy it from), so it's odd that it wasn't being resolved.

**Comment by godavdev** [comment]
Same issue here, only happens when the new output path in the prisma schema is set.

I'm using next js, and I noticed that if you are using prisma with server actions, you can solve the problem by forcing the dynamic render in the page.

`export const dynamic="force-dynamic"`

**Comment by jkomyno** [comment]
Hi, this issue is fixed by using the `prisma-client` generator + `queryCompiler` + `driverAdapters`.
We've tested it on our end and with some other users. Here are some examples of reference for you:
- [Next.js + Webpack](https://github.com/prisma/prisma-examples/tree/feat/prisma-client-fixes/generator-prisma-client/nextjs-starter-webpack)
- [Next.js + Turbopack](https://github.com/prisma/prisma-examples/tree/feat/prisma-client-fixes/generator-prisma-client/nextjs-starter-turbopack)
- [Monorepo: Next.js + pnpm workspaces](https://github.com/prisma/prisma-examples/tree/feat/prisma-client-fixes/generator-prisma-client/nextjs-starter-webpack-monorepo)
- [Monorepo: Next.js + Turborepo](https://github.com/prisma/prisma-examples/tree/feat/prisma-client-fixes/generator-prisma-client/nextjs-starter-webpack-turborepo)
- [Next.js, Node.js + Vercel-Edge middleware](https://github.com/prisma/prisma-examples/tree/feat/prisma-client-fixes/generator-prisma-client/nextjs-starter-webpack-with-middleware)

Some info for the future:
- `prisma-client` will be the default Prisma generator available in Prisma 7
- `queryCompiler` + `driverAdapters` will be the only way to run Prisma Client queries in Prisma 7

Thanks, and sorry this took so long.

cc @Illyism @godavdev @juggernog20 @tuliren @PaulSinghDev @nabi-chan and others

**Comment by rafayexalter** [comment]
tried everything but still facing this

``````2025-10-25T17:46:46.353Z [error] Unhandled Rejection: PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x".

This is likely caused by tooling that has not copied "libquery_engine-rhel-openssl-3.0.x.so.node" to the deployment folder.
Ensure that you ran `prisma generate` and that "libquery_engine-rhel-openssl-3.0.x.so.node" has been copied to "node_modules/.prisma/client".

We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-tooling-investigation

The following locations have been searched:
  /var/task/node_modules/.prisma/client
  /var/task/node_modules/@prisma/client
  /vercel/path0/node_modules/@prisma/client
  /tmp/prisma-engines
    at ml (/var/task/node_modules/@prisma/client/runtime/library.js:64:805)
    at async Object.loadLibrary (/var/task/node_modules/@prisma/client/runtime/library.js:111:7998)
    at async Qr.loadEngine (/var/task/node_modules/@prisma/client/runtime/library.js:112:448)
    at async Qr.instantiateLibrary (/var/task/node_modules/@prisma/client/runtime/library.js:111:11901)
2025-10-25T17:46:46.358Z [error] Error [PrismaClientInitializationError]: Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x".

This is likely caused by tooling that has not copied "libquery_engine-rhel-openssl-3.0.x.so.node" to the deployment folder.
Ensure that you ran `prisma generate` and that "libquery_engine-rhel-openssl-3.0.x.so.node" has been copied to "node_modules/.prisma/client".

We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-tooling-investigation

The following locations have been searched:
  /var/task/node_modules/.prisma/client
  /var/task/node_modules/@prisma/client
  /vercel/path0/node_modules/@prisma/client
  /tmp/prisma-engines
    at ignore-listed frames {
  clientVersion: '6.18.0',
  errorCode: undefined,
  retryable: undefined
}
2025-10-25T17:46:46.414Z [error] 2025-10-25T17:46:46.403Z ERROR [Better Auth]: PrismaClientInitializationError Error [PrismaClientInitializationError]: 
Invalid `prisma.verification.create()` invocation:


Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x".

This is likely caused by tooling that has not copied "libquery_engine-rhel-openssl-3.0.x.so.node" to the deployment folder.
Ensure that you ran `prisma generate` and that "libquery_engine-rhel-openssl-3.0.x.so.node" has been copied to "node_modules/.prisma/client".

We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-tooling-investigation

The following locations have been searched:
  /var/task/node_modules/.prisma/client
  /var/task/node_modules/@prisma/client
  /vercel/path0/node_modules/@prisma/client
  /tmp/prisma-engines
    at async Object.create (.next/server/chunks/_bc8b00f4._.js:187:21943)
    at async Object.create (.next/server/chunks/_bc8b00f4._.js:168:26328)
    at async createWithHooks (.next/server/chunks/_bc8b00f4._.js:178:65878)
    at async Object.createVerificationValue (.next/server/chunks/_bc8b00f4._.js:178:74611)
    at async pg (.next/server/chunks/_bc8b00f4._.js:88:6626)
    at async (.next/server/chunks/_bc8b00f4._.js:88:15886) {
  clientVersion: '6.18.0',
  errorCode: undefined,
  retryable: undefined
}
2025-10-25T17:46:46.415Z [error] # SERVER_ERROR:  Error [PrismaClientInitializationError]: 
Invalid `prisma.verification.create()` invocation:


Prisma Client could not locate the Query Engine for runtime "rhel-openssl-3.0.x".

This is likely caused by tooling that has not copied "libquery_engine-rhel-openssl-3.0.x.so.node" to the deployment folder.
Ensure that you ran `prisma generate` and that "libquery_engine-rhel-openssl-3.0.x.so.node" has been copied to "node_modules/.prisma/client".

We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-tooling-investigation

The following locations have been searched:
  /var/task/node_modules/.prisma/client
  /var/task/node_modules/@prisma/client
  /vercel/path0/node_modules/@prisma/client
  /tmp/prisma-engines
    at async Object.create (.next/server/chunks/_bc8b00f4._.js:187:21943)
    at async Object.create (.next/server/chunks/_bc8b00f4._.js:168:26328)
    at async createWithHooks (.next/server/chunks/_bc8b00f4._.js:178:65878)
    at async Object.createVerificationValue (.next/server/chunks/_bc8b00f4._.js:178:74611)
    at async pg (.next/server/chunks/_bc8b00f4._.js:88:6626)
    at async (.next/server/chunks/_bc8b00f4._.js:88:15886) {
  clientVersion: '6.18.0',
  errorCode: undefined,
  retryable: undefined
}
2025-10-25T17:46:46.472Z [fatal] Node.js process exited with exit status: 128. The logs above can help with debugging the issue.`

**Comment by matiasdecarli** [comment]
> Hi, I fixed it.
> 
> First, remove the output folder as mentioned above from schema.prisma
> 
> ![Image](https://github.com/user-attachments/assets/39d5c12c-7f56-4ffb-9825-10232a650850)
> 
> Then update the index.ts file to point to @prisma/client
> 
> ![Image](https://github.com/user-attachments/assets/0619599f-62a3-4606-87e4-8db207e52135)
> 
> That's the only change from https://www.prisma.io/docs/orm/more/help-and-troubleshooting/nextjs-help
> 
> Good luck!

This got fixed for me by following this. Thanks a lot!
