### ISSUE TITLE
Vitest coverage fails with custom client generator output

### ISSUE THREAD

**Issue by SSmietana** [prisma/prisma#22292]
### Bug description

I'm trying to run vitest test coverage on a project with a custom output defined in my prisma client generator. This results in the following error:
```
Error: An error occurred while trying to read the map file at index-browser.js.map
Error: ENOENT: no such file or directory, open '/Users/steve/src/prisma-v8-coverage/generated/prisma-client-js/runtime/index-browser.js.map'
    at readFileSync (node:fs:453:20)
    at V8ToIstanbul._readFileFromDir (/Users/steve/src/prisma-v8-coverage/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:94:12)
    at readFromFileMap (/Users/steve/src/prisma-v8-coverage/node_modules/convert-source-map/index.js:54:14)
    at exports.fromMapFileComment (/Users/steve/src/prisma-v8-coverage/node_modules/convert-source-map/index.js:196:12)
    at exports.fromMapFileSource (/Users/steve/src/prisma-v8-coverage/node_modules/convert-source-map/index.js:219:22)
    at V8ToIstanbul.load (/Users/steve/src/prisma-v8-coverage/node_modules/v8-to-istanbul/lib/v8-to-istanbul.js:53:66)
    at file:///Users/steve/src/prisma-v8-coverage/node_modules/@vitest/coverage-v8/dist/provider.js:392:25
    at async Promise.all (index 5)
    at async V8CoverageProvider.convertCoverage (file:///Users/steve/src/prisma-v8-coverage/node_modules/@vitest/coverage-v8/dist/provider.js:388:7)
    at async V8CoverageProvider.reportCoverage (file:///Users/steve/src/prisma-v8-coverage/node_modules/@vitest/coverage-v8/dist/provider.js:273:25)
```

### How to reproduce

1. Create project with prisma and vitest
2. Set client generator have custom output
3. Run tests with coverage

Created this repo to reproduce
1. Go to https://github.com/SSmietana/prisma-v8-coverage
4. Change this line, commenting in/out to reproduce https://github.com/SSmietana/prisma-v8-coverage/blob/main/prisma/schema.prisma#L6
5. Run `npm run recreate`
6. See error only when custom output is enabled

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../generated/prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User    @relation(fields: [authorId], references: [id])
  authorId  Int
}
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: SQLite
- Node.js version: v21.3.0

### Prisma Version

```
5.6.0
```

**Comment by janpio** [comment]
This could be related: https://github.com/prisma/prisma/issues/21111

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community. I recommend excluding generated files (such as Prisma's custom client generator output) from Vitest's covered statistics.

---

If this is issue is still important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest. If you do reopen the issue, please ensure that there’s a clear method for us to reproduce it. 

For more insight into our priorities and how we’re thinking about the future of the Prisma ORM, please see our recent blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!
