### ISSUE TITLE
Batched `findUnique()`  error out when the field is of `Boolean` type

### ISSUE THREAD

**Issue by MiccWan** [prisma/prisma#22384]
### Bug description

In the [Query Optimization](https://www.prisma.io/docs/orm/prisma-client/queries/query-optimization-performance#solving-n1-in-graphql-with-findunique-and-prismas-dataloader) section, it says Prisma will batch the `findUnique` operations in the same tick.
However, the batching algorithm will transform the condition `isX: true` into `isX: { in: [true]}`, which is invalid for a Boolean field.

### How to reproduce

1. Create a model with a unique Boolean field
```prisma
model User {
  id String @id
  isManager Boolean? @unique
}
```
2. Make multiple `findUnique` queries on the Boolean field
```javascript
async function getManager() {
  return await prisma.user.findUnique({
    where: {
      isManager: true
    },
  });
}

await Promise.all([
  getManager(),
  getManager(),
]);
```
3. See error in console
```
PrismaClientValidationError: 
Invalid `prisma.user.findUnique()` invocation:

{
  where: {
    isManager: true
  }
}

Unknown argument `in`. Did you mean `not`? Available options are marked with ?.
    at ti (/home/user/playground/node_modules/@prisma/client/runtime/library.js:118:5888)
    at si.handleRequestError (/home/user/playground/node_modules/@prisma/client/runtime/library.js:125:6473)
    at si.handleAndLogRequestError (/home/user/playground/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/home/user/playground/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/home/user/playground/node_modules/@prisma/client/runtime/library.js:130:10025)
    at async getManager (file:///home/user/playground/index.js:6:10)
    at async Promise.all (index 0)
    at async file:///home/user/playground/index.js:13:1 {
  clientVersion: '5.7.1'
}
```

### Expected behavior

The queries should returns the correct unique record.

Maybe dedupe the queries with the same arguments, or make `in` operator works in boolean fields?

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id String @id
  isManager Boolean? @unique
}
```

```javascript
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function getManager() {
  return await prisma.user.findUnique({
    where: {
      isManager: true
    },
  });
}

await Promise.all([
  getManager(),
  getManager(),
]);
```

### Environment & setup

- OS: Ubuntu 22.04.3 LTS
- Database: PostgreSQL
- Node.js version: v18.18.2

### Prisma Version

```
prisma                  : 5.7.1
@prisma/client          : 5.7.1
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v18.18.2
Query Engine (Node-API) : libquery-engine 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5 (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.7.1-1.0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5
Default Engines Hash    : 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5
Studio                  : 0.495.0
```

**Comment by MiccWan** [comment]
Update: Tested with the latest Prisma version (5.7.1) and confirmed the problem still exists.
I've updated the issue to match latest version

**Comment by SevInf** [comment]
Can confirm on latest `main` (5.11.0-dev). [Internal link](https://github.com/prisma/reproductions/tree/ac1c19edc201787e42c96680019caa7b58995708/gh-22384)

**Comment by MiccWan** [comment]
Cool! Thank you for your help!
