### ISSUE TITLE
Prisma connecting to Postgresql on Google Cloud Functions with Node.js 18

### ISSUE THREAD

**Issue by pip8786** [prisma/prisma#22568]
### Discussed in https://github.com/prisma/prisma/discussions/22520

<div type='discussions-op-text'>

<sup>Originally posted by **pip8786** December 27, 2023</sup>
### Question

I've been running our Google Cloud Functions on Node.js 16 for a long time, but that is about to stop working at the end of January. I was hoping to just update to Node.js 18 which is what my machine runs and move on from there. When I updated, my cloud functions started reporting an error when trying to use prisma:

```
Error opening a TLS connection: error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties () 
at si.handleRequestError (/workspace/node_modules/@prisma/client/runtime/library.js:125:7117) 
at si.handleAndLogRequestError (/workspace/node_modules/@prisma/client/runtime/library.js:125:6151) 
at si.request (/workspace/node_modules/@prisma/client/runtime/library.js:125:5859) 
at async l (/workspace/node_modules/@prisma/client/runtime/library.js:130:10025) 
```

I've been researching this all over the place and recommendations to downgrade to Node.js 16 or enable `--openssl-legacy-provider` aren't possible. Something I noticed is that Node.js 18 on GCP Functions runs on Ubuntu 22.04 while previous versions were on 18.04 (https://cloud.google.com/functions/docs/concepts/execution-environment#runtimes). I've seen a few places in the github issues mentioning problems on that OS but they seem to be closed. 

Any tips on how I can get my cloud functions connecting while running on Node.js 18?

### Information about Prisma Schema, Client Queries and Environment (optional)

DB URL is similar to: 
`postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_BASE}?sslidentity=${DB_ID}&sslpassword=${DB_ID_PASS}&sslcert=${DB_CERT}`

The sslidentity is a .p12 file and the sslcert is a .pem file. These both worked on the previous deployment. They also work on Node18 locally and on Vercel. Just can't figure it out on Google. 

- OS: Ubuntu 22.04
- Database: PostgreSQL on GCP using SSL certificates
- Node.js version: 18.18.2

- Prisma 5.7.1
</div>

Node 16 is deprecating on Google Cloud Functions on January 30th, 2024. I could use help with this issue, not sure where else to reach out.

**Comment by Jolg42** [comment]
Hi @pip8786

This doesn't look good, so when I saw your problem I tried to reproduce this, and "good news" I could reproduce this.

So here is what I tried,

1. Upgraded our `gcp-functions` test from Node.js v16 to v18
	We have a minimal deployment of Google Cloud Functions running on Node.js v16 called `gcp-functions`, and I upgraded the runtime to v18 in this PR:
	https://github.com/prisma/ecosystem-tests/pull/4433
	Note that this connects to an AWS RDS database.
	I can see in the logs that the Prisma engine switched, liked expected, from `libquery_engine-debian-openssl-1.0.x.so.node` to `libquery_engine-debian-openssl-3.0.x.so.node` and that the Prisma Client queries were successful.
	This was successful and working as expected

2. Upgraded our `debian-bullseye-amd64-openssl-1.1.x-tls` test and modified it as `debian-latest-amd64-openssl-3.0.x-tls`
	I did that in the same PR (https://github.com/prisma/ecosystem-tests/pull/4433)
	This is testing Prisma Client using GCP Postgres with the SSL certificate.
	And I can reproduce what you mentioned, so we need to turn this into a bug issue.
	Logs
	```
	PrismaClientInitializationError: 
	Invalid `client.user.findMany()` invocation in
	/usr/src/app/server.js:12:34
	
	   9 const client = new PrismaClient()
	  10 
	  11 app.get('/', async (req, res) => {
	→ 12   const data = await client.user.findMany(
	Error opening a TLS connection: error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
	    at si.handleRequestError (/usr/src/app/node_modules/.pnpm/@prisma+client@5.8.0-dev.50_prisma@5.8.0-dev.50/node_modules/@prisma/client/runtime/library.js:125:7117)
	    at si.handleAndLogRequestError (/usr/src/app/node_modules/.pnpm/@prisma+client@5.8.0-dev.50_prisma@5.8.0-dev.50/node_modules/@prisma/client/runtime/library.js:125:6151)
	    at si.request (/usr/src/app/node_modules/.pnpm/@prisma+client@5.8.0-dev.50_prisma@5.8.0-dev.50/node_modules/@prisma/client/runtime/library.js:125:5859)
	    at async l (/usr/src/app/node_modules/.pnpm/@prisma+client@5.8.0-dev.50_prisma@5.8.0-dev.50/node_modules/@prisma/client/runtime/library.js:130:9805)
	    at async /usr/src/app/server.js:12:16 {
	  clientVersion: '5.8.0-dev.50',
	  errorCode: undefined
	}
	```

_Originally posted by @Jolg42 in https://github.com/prisma/prisma/discussions/22520#discussioncomment-8021302_

**Comment by Jolg42** [comment]
Random find: https://community.fly.io/t/error-connecting-to-google-cloud-sql/5604 someone reported a similar error message on Fly.io's community forum in June 2022, so this might be an old problem?

**Comment by Jolg42** [comment]
I’m thinking this is because our PostgreSQL driver has openssl vendored, and it’s outdated?
https://github.com/prisma/rust-postgres/blob/pgbouncer-mode/postgres-native-tls/Cargo.toml
https://github.com/prisma/rust-postgres/blob/pgbouncer-mode/postgres-openssl/Cargo.toml

I’m not familiar with all the complexity of these forks here, I think some of my colleagues could help better than me here.

**Comment by pip8786** [comment]
@Jolg42 Thanks for looking into it. 

I found that fly.io thread when I was looking for a solution as well but it didn't have much in terms of help. Since our GCFs are in production and need to run, I had to revert back to Node16 after trying out a few different potential solutions. 

If you need me to test anything, please let me know, I will get on it ASAP. As I said, if we hit the January 30th deadline, I'm not sure what I'll need to do in order to keep them running with Prisma, hopefully I don't have to drop it as that would be a massive lift right now.

**Comment by pip8786** [comment]
@Jolg42 or @millsp do you guys have an idea on how difficult this will be to fix? I'm just wondering if I should start figuring out a different solution for my cloud functions that are set to deprecate in a few weeks.

**Comment by pip8786** [comment]
@janpio I got a new cert from Google* and tried again.  I still got the error though. Redeploying with 16 though still gives me the error, as does trying the old cert again. I'm not sure what's going on there when I did this in the past and going back to Node 16 made it work right away. This is all in a test function so I'm not messing with any of my production functions, though it's set up the same way. I'm going to keep investigating if I can get it running again on Node 16 (maybe some sort of caching issue?).

* Note: in order to use the certs with Prisma, I end up encoding them into a pk12cs file and then adding them to code encoded using secret keys. This was a workaround I found since keys have limited length on vercel, and it's used there and on my cloud functions.

Here's the `npx prisma -v` for each environment:

Local:
```
prisma                  : 5.7.1
@prisma/client          : 5.7.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v18.18.2
Query Engine (Node-API) : libquery-engine 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.7.1-1.0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5
Default Engines Hash    : 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5
Studio                  : 0.495.0
```

To do GCP I added `"gcp-build": "npx prisma -v",` to my package.json. It seems to be installing a new version of prisma to do that. Something weird I noticed is I didn't have the `npx prisma generate` in my `gcp-build` script which is what you guys have in your examples. It's been working up until now though. Something else to mention is that I use local packages for everything, I'll post more details below.

Node16 on GCP:
```
prisma                  : 5.8.0
@prisma/client          : 5.8.0
Computed binaryTarget   : debian-openssl-1.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v16.20.2
Query Engine (Node-API) : libquery-engine 0a83d8541752d7582de2ebc1ece46519ce72a848 (at ../www-data-home/.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.0.x.so.node)
Schema Engine           : schema-engine-cli 0a83d8541752d7582de2ebc1ece46519ce72a848 (at ../www-data-home/.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/schema-engine-debian-openssl-1.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.8.0-37.0a83d8541752d7582de2ebc1ece46519ce72a848
Default Engines Hash    : 0a83d8541752d7582de2ebc1ece46519ce72a848
Studio                  : 0.497.0
```

Node18 on GCP:
```
prisma : 5.8.0
@prisma/client : 5.8.0
Computed binaryTarget : debian-openssl-3.0.x
Operating System : linux
Architecture : x64
Node.js : v18.19.0
Query Engine (Node-API) : libquery-engine 0a83d8541752d7582de2ebc1ece46519ce72a848 (at ../www-data-home/.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine : schema-engine-cli 0a83d8541752d7582de2ebc1ece46519ce72a848 (at ../www-data-home/.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm : @prisma/prisma-schema-wasm 5.8.0-37.0a83d8541752d7582de2ebc1ece46519ce72a848
Default Engines Hash : 0a83d8541752d7582de2ebc1ece46519ce72a848
Studio : 0.497.0
```

Node 18 on Vercel:
```
prisma                  : 5.7.1
@prisma/client          : 5.7.1
Computed binaryTarget   : rhel-openssl-1.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v18.18.2
Query Engine (Node-API) : libquery-engine 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5 (at node_modules/@prisma/engines/libquery_engine-rhel-openssl-1.0.x.so.node)
Schema Engine           : schema-engine-cli 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5 (at node_modules/@prisma/engines/schema-engine-rhel-openssl-1.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.7.1-1.0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5
Default Engines Hash    : 0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5
Studio                  : 0.495.0
```

Interesting that his one is openssl-1.0.x which is probably why it works. Note that Node 20 on Vercel did not work, probably cause it was going to openssl-3. I can verify this if you like. 

As for my project structure, it is a monorepo with `apps/`, `cloud-functions/`, and `packages/` all written in Typescript. Prisma and the schema for it are in one of the local packages. When building the cloud functions, I put them all into TGZ files that I upload when I deploy, the structure at that point looks like this:

![Screenshot 2024-01-14 at 11 15 47 AM](https://github.com/prisma/prisma/assets/1085106/7c2c4a04-9b5c-4ef1-9773-afeaf173b470)

It was difficult getting all this to work together since cloud functions require very different modules than NextJS, but eventually I was able to get it all working. I'd be hesitant to modify it, but maybe I could test out a simpler version of this to try and debug the issue. My focus for now is going to be figuring out why my Node 16 function won't work after trying Node 18 when that rollback was working fine before.

Please let me know if there's anything else I can try.

**Comment by pip8786** [comment]
A breakthrough I think:
In your [connection instructions](https://www.prisma.io/docs/orm/overview/databases/postgresql#configuring-an-ssl-connection), you mention using `openssl` to combine the client key and client certificate into a `pkcs12`. I had done that a long time ago, and again yesterday using the new certs you suggested, but it turns out my machine had `LibreSSL 3.3.6` which would default to using the old `RC2-40-CBC` algorithm no longer supported on `OpenSSL3`. I got a new version of `OpenSSL`, went through all the encoding again, and used `openssl pkcs12 -info -in test.p12` to verify that the algorithm/encoding was the newer one `AES-256-CBC`. 

Tested my cloud function on Node 18 with that and it worked! The issue is the same `pcks12` file does not work on my local machine, so I'll either have to figure out how to make that work locally or use separate files (legacy vs modern). I'll also need to ensure that it works on Vercel, though I think Vercel with Node 20 is OpenSSL 3 so might be easy to fix that. I will likely try Node 20 on Cloud functions as well and report back.

In the end, maybe it's not a bug in your software (or dependencies) but maybe something useful to mention in the instructions for creating the `pkcs12` file linked above.

**Comment by janpio** [comment]
Ohhhh, thanks for giving us this update.

To see if I fully understand, in my words:
On a system using OpenSSL 3 to connect to the database, the `pkcs12` needs to use the new `AES-256-CBC` algorithm. If you use `OpenSSL 3`, that is the case. But for `LibreSSL 3.3.6` it is not yet, and it uses the old (and now not supported any more) `RC2-40-CBC`. Correct?

Can you share the output of `openssl pkcs12 -info` that confirmed it worked?

**Comment by pip8786** [comment]
> On a system using OpenSSL 3 to connect to the database, the pkcs12 needs to use the new AES-256-CBC algorithm. If you use OpenSSL 3, that is the case. But for LibreSSL 3.3.6 it is not yet, and it uses the old (and now not supported any more) RC2-40-CBC. Correct?

Yeah, that's the case. What's funny is though I used Homebrew to update to the latest `LibreSSL` which is 3.8.2, using that didn't work. However, in the process of updating the `LibreSSL`, it also updated an underlying version of `OpenSSL` to 3.2.0 which is the one I was successful with. This became the default on my terminal. 

```
% which openssl
/opt/homebrew/bin/openssl
% /opt/homebrew/bin/openssl version
OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)
% /opt/homebrew/opt/libressl/bin/openssl version
LibreSSL 3.8.2
```

Something I'm still unsure about is which version of SSL prisma is using under the hood to have it fail on the newly encoded p12 file. I have to use the old one for it to continue to work (I put it in a separate .env variable for local work).

> Can you share the output of openssl pkcs12 -info that confirmed it worked?

Using this command: 
`openssl pkcs12 -in test.p12 -info -nokeys -nocerts`

The output for the newly encoded p12 file is:
```
MAC: sha256, Iteration 2048
MAC length: 32, salt length: 8
PKCS7 Encrypted data: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
Certificate bag
PKCS7 Data
Shrouded Keybag: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
```

When I use the same command with the new version of openssl on the old p12:
```
MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
Error outputting keys and certificates
0050CBE001000000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:342:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```
Note that error is the same as what I got on the TSL connection error to begin with.

If I add the `legacy` flag to the command: `openssl pkcs12 -in client-identity.p12 -info -nokeys -nocerts -legacy` then I get this:
```
MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
Certificate bag
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2048
```

Use the OLD version of OpenSSL, the old p12 file's info gives me the output just above, and the new p12 file's info seems to break (no error output, just doesn't output anything useful).

Hopefully this helps, let me know if there's anything else you want me to try out.
