### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by RobinDev03** [prisma/prisma#22578]
### Bug description

Whe I try to make a Request with Prisma, the Application crashes with an Error.
```
[06-01-24 0:53:20]: CMD robinwolff (435493804418531348) executed Button ticket_create on TestServer :) (849353483000872992)
node:events:497
      throw er; // Unhandled 'error' event
      ^

RangeError: Maximum call stack size exceeded
    at va (D:\Drive\JetBrains\WebstormProjects\dsc-modular-discord-bot\node_modules\@prisma\client\runtime\library.js:28:53)
    at _a (D:\Drive\JetBrains\WebstormProjects\dsc-modular-discord-bot\node_modules\@prisma\client\runtime\library.js:28:850)
    at va (D:\Drive\JetBrains\WebstormProjects\dsc-modular-discord-bot\node_modules\@prisma\client\runtime\library.js:28:118)
    at _a (D:\Drive\JetBrains\WebstormProjects\dsc-modular-discord-bot\node_modules\@prisma\client\runtime\library.js:28:850)
    at va (D:\Drive\JetBrains\WebstormProjects\dsc-modular-discord-bot\node_modules\@prisma\client\runtime\library.js:28:118)
    at _a (D:\Drive\JetBrains\WebstormProjects\dsc-modular-discord-bot\node_modules\@prisma\client\runtime\library.js:28:850)
    at va (D:\Drive\JetBrains\WebstormProjects\dsc-modular-discord-bot\node_modules\@prisma\client\runtime\library.js:28:118)
    at _a (D:\Drive\JetBrains\WebstormProjects\dsc-modular-discord-bot\node_modules\@prisma\client\runtime\library.js:28:850)
    at va (D:\Drive\JetBrains\WebstormProjects\dsc-modular-discord-bot\node_modules\@prisma\client\runtime\library.js:28:118)
    at _a (D:\Drive\JetBrains\WebstormProjects\dsc-modular-discord-bot\node_modules\@prisma\client\runtime\library.js:28:850)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:402:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)

Node.js v21.5.0

```

### How to reproduce

Make a Request (findMany or findFirst)

### Expected behavior

Response with the Query-Result

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model member {
  id       String   @id @default(auto()) @map("_id") @db.ObjectId
  guildId  String
  userId   String
  joinedAt DateTime

  @@map("members")
}

// ### Tickets ###

model ticketCategory {
  id         String              @id @default(auto()) @map("_id") @db.ObjectId
  guild      String
  name       String
  prefix     String
  teamRole   String
  logChannel String
  created_at DateTime            @default(now())
  tickets    ticket[]
  state      ticketCategoryState @default(ACTIVE)
}

model ticket {
  id            String          @id @default(auto()) @map("_id") @db.ObjectId
  guild         String
  channel       String
  owner         String
  ccuser        Json?
  category      ticketCategory  @relation(fields: [categoryId], references: [id])
  categoryId    String
  state         ticketState     @default(OPEN)
  loguuid       String?
  created_at    DateTime        @default(now())
  ticketMessage ticketMessage[]
}

model ticketMessage {
  id         String   @id @default(auto()) @map("_id") @db.ObjectId
  messageId  String
  message    Json
  ticket     ticket   @relation(fields: [ticketId], references: [id])
  ticketId   String
  sender     String
  deleted    Boolean  @default(false)
  edited     Json?
  created_at DateTime @default(now())
}

model ticketSettings {
  id              String  @id @default(auto()) @map("_id") @db.ObjectId
  guild           String
  category_open   String?
  category_closed String?
}

enum ticketCategoryState {
  ACTIVE
  DISABLED
}

enum ticketState {
  OPEN
  PENDING
  CLOSED
  DELETED
}

```

### Environment & setup

- OS: Windows 11
- Database: MongoDB
- Node.js version: 21.5.0 and 20.8.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.4.1
@prisma/client          : 5.7.1
Current platform        : windows
Query Engine (Node-API) : libquery-engine 2f302df92bd8945e20ad4595a73def5b96afa54f (at C:\Users\Admin\AppData\Roaming\nvm\v20.8.0\node_modules\prisma\node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 2f302df92bd8945e20ad4595a73def5b96afa54f (at C:\Users\Admin\AppData\Roaming\nvm\v20.8.0\node_modules\prisma\node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.3.1-2.61e140623197a131c2a6189271ffee05a7aa9a59
Default Engines Hash    : 2f302df92bd8945e20ad4595a73def5b96afa54f
Studio                  : 0.494.0
```

**Comment by Weakky** [comment]
Hey @RobinDev03,

Do you experience this error no matter the findMany or findFirst query? Or does it reproduce only with certain ones? If it only reproduces with specific queries, would you mind sharing the specific query you're trying to run?

Thank you

**Comment by RobinDev03** [comment]
Hey @Weakky,

both. 

```js
const { Redis } = require('ioredis');
const cache = new Redis({
    port: 6379,
    host: process.env.REDIS_HOST,
    username: process.env.REDIS_USER,
    password: process.env.REDIS_PASSWORD,
    db: 0
})

exports.cache = cache;
```

```js
const {cache, db} = require("../../../../index");

async function getCategory(guild, categoryId) {
    let cached = await cache.get(`ticketCategory:${guild}:${categoryId}`);
    if (cached) {
        return JSON.parse(cached);
    } else {
        cached = await db.ticketCategory.findFirst({
            where: {
                id: categoryId
            }
        });
        await cache.set(`ticketCategory:${guild}:${categoryId}`, JSON.stringify(cached), "EX", 3 * 60);
        return cached;
    }
}
async function getAllActiveCategories(guild) {
    let cached = await cache.get(`ticketCategory:${guild}`);
    if (cached) {
        return JSON.parse(cached);
    } else {
        cached = await db.ticketCategory.findMany({
            where: {
                guild: guild,
                state: "ACTIVE"
            }
        });
        await cache.set(`ticketCategory:${guild}`, JSON.stringify(cached), "EX", 3 * 60);
        return cached;
    }
}
```

**Comment by RobinDev03** [comment]
@Weakky just for Information: Error occurs still with the newest release (5.8.0)

**Comment by janpio** [comment]
Can you help us by creating a reproduction repository of the problem? Optimally without the redis cache in between and just using Prisma Client directly.

**Comment by Jolg42** [comment]
@RobinDev03 Did you have a chance to take a look at @janpio's comment above?

**Comment by SevInf** [comment]
Hey @RobinDev03 
 

With the lack of information and our inability to reproduce this issue, we're now closing it. Feel free to comment if you have any updates about it.
 
Thank you 🙏
