### ISSUE TITLE
Prisma+mongodb+cloudflare succeeds local but fails in production with UnknownTextError error code: 1016

### ISSUE THREAD

**Issue by benkaiser** [prisma/prisma#22658]
### Bug description

When running my cloudflare pages site (which has some functions as part of it) locally, all the routes function correctly and are able to use prisma accelerate to connect to my db.

I run into issues when I deploy the same application to cloudflare in production, every single invocation of prisma (.aggreateRaw, .findMany) that I have returns an error as follows:

```
 [ERROR]   Error: PrismaClientKnownRequestError:

  Invalid `prisma.recordings.findMany()` invocation:


  Unknown server error: {"type":"UnknownTextError","body":"error code: 1016"}
  ```
  
  I managed to get a stack trace, but it's not very helpful in the compiled code:
  ```
  Unknown server error: {"type":"UnknownTextError","body":"error code: 1016"}
    at So.handleRequestError (functionsWorker-0.08469215675045039.js:8623:17)
    at So.handleAndLogRequestError (functionsWorker-0.08469215675045039.js:8608:16)
    at So.request (functionsWorker-0.08469215675045039.js:8599:16)
    at async u (functionsWorker-0.08469215675045039.js:9012:21)
    at async next (functionsWorker-0.08469215675045039.js:10199:26)
    at async Object.fetch (functionsWorker-0.08469215675045039.js:10213:14)
    ```

### How to reproduce

Deploying this app to production:

https://github.com/benkaiser/the-read-bible/tree/vnext

Schema file here:

https://github.com/benkaiser/the-read-bible/blob/vnext/prisma/schema.prisma

### Expected behavior

Expected data to be returned from the API call, same as it is developing locally with `wrangler pages dev`.

### Prisma information

https://github.com/benkaiser/the-read-bible/blob/vnext/prisma/schema.prisma

### Environment & setup

- OS: linux (cloudflare worker)
- Database: mongodb
- Node.js version: whatever cloudflare workers run

### Prisma Version

```
5.8.0
```

**Comment by benkaiser** [comment]
Setting `DEBUG="*"` didn't give me any additional logs.

**Comment by nurul3101** [comment]
Hello @benkaiser 👋 

Thank you for trying out Accelerate and reporting this issue.

Can you please send an email to support@prisma.io? This would provide us with necessary information about your project, which would allow us to take a look at the logs of your project for investigation.

I'll close the GitHub Issue here, as this repository is for managing our open-source product: Prisma ORM and not our commercial products.

Thank you so much for taking the time to open this issue! 🙏
