### ISSUE TITLE
Adding `@default(sequence())` to a already existing field with `@id` doesn't generate a sequence after running `prisma db push`

### ISSUE THREAD

**Issue by mateussilva92** [prisma/prisma#22666]
### Bug description

I've noticed that for some reason Prisma is not creating or removing a sequence on the database after the schema is updated an `prisma db push` is run.

This only happens for already existing properties that have @id field. New fields will work correctly.

From what I've been able to see it deletes or create the index for that field but doesn't run the and `CREATE SEQUENCE`.
It seem that this is a issue with prisma engine itself not detecting a AddSequence for that field.

For the example I provided bellow I get the following error saying that I need to provided the id because there is not sequence that was created.

```
PrismaClientUnknownRequestError: 
Invalid `prisma.table.create()` invocation in
/Users/mateussilva/Projects/barista-draft-app/packages/db-layer/seed/index.ts:4:22

  1 import { prisma } from './prisma-factory';
  2 
  3 async function main(): Promise<void> {
→ 4   await prisma.table.create(
Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42830", message: "missing \"id\" primary key column", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at si.handleRequestError (/Users/mateussilva/Projects/barista-draft-app/packages/db-layer/dist/runtime/library.js:125:7007)
    at si.handleAndLogRequestError (/Users/mateussilva/Projects/barista-draft-app/packages/db-layer/dist/runtime/library.js:125:6151)
    at si.request (/Users/mateussilva/Projects/barista-draft-app/packages/db-layer/dist/runtime/library.js:125:5859)
    at l (/Users/mateussilva/Projects/barista-draft-app/packages/db-layer/dist/runtime/library.js:130:9805)
    at main (/Users/mateussilva/Projects/barista-draft-app/packages/db-layer/seed/index.ts:4:3) {
  clientVersion: '5.8.1'
}
```

### Expected behavior

The value should be `nextval('public."Table_id_seq"'::REGCLASS)`

The `ts` code provided should work

### Prisma information

Old:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "cockroachdb"
  url      = env("DATABASE_URL")
}

model Table {
  id   Int    @id
  name String
}

```

New:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "cockroachdb"
  url      = env("DATABASE_URL")
}

model Table {
  id   Int    @id @default(sequence())
  name String
}
```

```ts
await prisma.table.create({ data: { name: 'test' } });
```

### Environment & setup

- OS: macOS
- Database: CockroachDB v23.1.1
- Node.js version: v20.6.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.8.1
@prisma/client          : 5.8.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.6.0
Query Engine (Node-API) : libquery-engine 78caf6feeaed953168c64e15a249c3e9a033ebe2 (at ../../node_modules/.pnpm/@prisma+engines@5.8.1/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 78caf6feeaed953168c64e15a249c3e9a033ebe2 (at ../../node_modules/.pnpm/@prisma+engines@5.8.1/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.8.1-1.78caf6feeaed953168c64e15a249c3e9a033ebe2
Default Engines Hash    : 78caf6feeaed953168c64e15a249c3e9a033ebe2
Studio                  : 0.497.0
```

**Comment by jkomyno** [comment]
Closing as a duplicate of https://github.com/prisma/prisma/issues/20804.
