### ISSUE TITLE
Environment variables not loaded from `.env` in monorepo

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#2269]
We tried introspection in an existing Prisma 1 project (a mono-repo with a total of seven `prisma.yml` and respective `datamodel.prisma` files). After having added the `@prisma/cli` as a dev dependency, we tried to introspect one of the PostgreSQL schemas that mapped to one of the seven Prisma 1 services. This is the error we got:

```
yarn run v1.12.3
$ prisma introspect
  prisma { argv:
  prisma    [ '/Users/abhiaiyer/.nvm/versions/node/v10.19.0/bin/node',
  prisma      '/Users/abhiaiyer/gatsby/mansion/cloud/packages/lib-prisma/node_modules/.bin/prisma',
  prisma      'introspect' ] } +0ms
  prisma Environment variables not loaded +4ms
  getos { platform: 'darwin', libssl: undefined } +0ms
  download { fileExists: true,
  download   cachedFile:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/query-engine' } +0ms
  download { cachedFile:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/query-engine' } +0ms
  download { fileExists: true,
  download   cachedFile:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/migration-engine' } +0ms
  download { cachedFile:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/migration-engine' } +0ms
  download { fileExists: true,
  download   cachedFile:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/introspection-engine' } +0ms
  download { cachedFile:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/introspection-engine' } +0ms
  download { sha256File:
  download    '031aa3d28731224dd1601098480011699473befd0d53f91bf0a6e0b9921d9b78',
  download   sha256Cache:
  download    '031aa3d28731224dd1601098480011699473befd0d53f91bf0a6e0b9921d9b78',
  download   cachedFile:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/introspection-engine',
  download   sha256FilePath:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/introspection-engine.sha256' } +101ms
  download { sha256File:
  download    '71d67323cfb48eea636e39c73559cae35baeec0132101c79f3cf2dd02292d2b8',
  download   sha256Cache:
  download    '71d67323cfb48eea636e39c73559cae35baeec0132101c79f3cf2dd02292d2b8',
  download   cachedFile:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/migration-engine',
  download   sha256FilePath:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/migration-engine.sha256' } +39ms
  download { sha256File:
  download    '7dfa7c8a8814c7f18ca37f052b0fcd59af62518ab2a56e1c0b9a5f8118754477',
  download   sha256Cache:
  download    '7dfa7c8a8814c7f18ca37f052b0fcd59af62518ab2a56e1c0b9a5f8118754477',
  download   cachedFile:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/query-engine',
  download   sha256FilePath:
  download    '/Users/abhiaiyer/.cache/prisma/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/darwin/query-engine.sha256' } +16ms
  download { targetSha256:
  download    '031aa3d28731224dd1601098480011699473befd0d53f91bf0a6e0b9921d9b78' } +67ms
  download sha256 of target is correct, so there's nothing to do :) +1ms
  download { needsToBeDownloaded: false } +0ms
  download { targetSha256:
  download    '71d67323cfb48eea636e39c73559cae35baeec0132101c79f3cf2dd02292d2b8' } +48ms
  download sha256 of target is correct, so there's nothing to do :) +0ms
  download { needsToBeDownloaded: false } +0ms
  download { targetSha256:
  download    '7dfa7c8a8814c7f18ca37f052b0fcd59af62518ab2a56e1c0b9a5f8118754477' } +14ms
  download sha256 of target is correct, so there's nothing to do :+0ms
  download { needsToBeDownloaded: false } +0ms
Introspecting based on datasource defined in services/static-uploads/prisma/schema.prisma …
  getos { platform: 'darwin', libssl: undefined } +297ms
  IntrospectionEngine:rpc starting introspection engine with binary: /Users/abhiaiyer/gatsby/mansion/cloud/node_modules/@prisma/cli/introspection-engine-darwin +0ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n"}]} +9ms
  IntrospectionEngine:rpc { jsonrpc: '2.0',
  IntrospectionEngine:rpc   error:
  IntrospectionEngine:rpc    { code: 4466,
  IntrospectionEngine:rpc      message: 'An error happened. Check the data field for details.',
  IntrospectionEngine:rpc      data:
  IntrospectionEngine:rpc       { is_panic: false,
  IntrospectionEngine:rpc         message:
  IntrospectionEngine:rpc          'Error in datamodel: ErrorCollection { errors: [EnvironmentFunctionalEvaluationError { var_name: "DATABASE_URL", span: Span { start: 160, end: 179 } }] }',
  IntrospectionEngine:rpc         backtrace: null } },
  IntrospectionEngine:rpc   id: 1 } +16ms
Error: Error: Error in datamodel: ErrorCollection { errors: [EnvironmentFunctionalEvaluationError { var_name: "DATABASE_URL", span: Span { start: 160, end: 179 } }] }
    at IntrospectionEngine.<anonymous> (/Users/abhiaiyer/gatsby/mansion/cloud/node_modules/@prisma/cli/build/index.js:2:2542935)
    at Generator.next (<anonymous>)
    at /Users/abhiaiyer/gatsby/mansion/cloud/node_modules/@prisma/cli/build/index.js:2:2537655
    at new Promise (<anonymous>)
    at n (/Users/abhiaiyer/gatsby/mansion/cloud/node_modules/@prisma/cli/build/index.js:2:2537403)
    at Object.registerCallback (/Users/abhiaiyer/gatsby/mansion/cloud/node_modules/@prisma/cli/build/index.js:2:2542141)
    at IntrospectionEngine.handleResponse (/Users/abhiaiyer/gatsby/mansion/cloud/node_modules/@prisma/cli/build/index.js:2:2539961)
    at LineStream.l.default.on.e (/Users/abhiaiyer/gatsby/mansion/cloud/node_modules/@prisma/cli/build/index.js:2:2541779)
    at LineStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It says: `prisma Environment variables not loaded +4ms`.

When hardcoding the `url` directly in `schema.prisma`, introspection worked as expected.

**Comment by pantharshit00** [comment]
@nikolasburk Can you please share your folder structure? 

Also, this might be already fixed via https://github.com/prisma/prisma-client-js/issues/664 so please try this again once as well with the alpha version.

**Comment by pantharshit00** [comment]
@nikolasburk do you still have the information? It's been over 3 months now, if this is not actionable anymore, please close it.

**Comment by matthewmueller** [comment]
Closing. Please re-open if you're still running into this. Thanks!

**Comment by jamesguan** [comment]
Hope this helps, I have a `.env` file in a parent directory and tried to delete the .env file that was in the prisma folder. However, it seems that `npx prisma introspect` does not pick up the `.env` file from the parent directory so I had to explicitly define another `.env` file in the prisma folder. Is it the case that the `.env` file has to be in the prisma folder for prisma environment variables?

**Comment by zomars** [comment]
Having the same issue here. It's kinda annoying we cannot have one single unified ´.env´ file in a monorepo setup.

**Comment by janpio** [comment]
Can you please share the full information? What does your structure look like? Where do you have `.env` files? What commands can pick it up or not?

**Comment by zomars** [comment]
We have a monorepo using turbo repo with the following structure:


<img width="208" alt="image" src="https://user-images.githubusercontent.com/3504472/160032900-a5b577b6-0eca-45f8-987c-5a4d86abe2b4.png">

The prisma package is being used in multiple applications, currently we're trying to use a single `.env` to avoid confusion. Moving the `DATABASE_URL` url from `packages/prisma/.env` to the root `.env` errors when trying to run any `yarn prisma script`.

We also tried to use a solution like `cmd-env`:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/3504472/160033119-251e5da0-0bab-4a16-aed7-a5b1d032d36c.png">

But no luck so far.

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/3504472/160033166-d45e1250-d16a-48df-8e6f-06175ddf0451.png">

**Comment by janpio** [comment]
Ok. Can you please open a new issue with exactly that information (And whatever else the template asks for)? Then we can apply the correct labels etc and make sure this gets worked on properly. Also post the link to the issue here when done please.

**Comment by zomars** [comment]
@janpio opened #12535 🙏🏽
