### ISSUE TITLE
using Serverless framework with aws lambda, got error

### ISSUE THREAD

**Issue by Q00** [prisma/prisma#2270]
## Bug description

I got an error about @prisma/client.

```yml
service:
  name: hakhak
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
```

I did like this. 

```json
{
  "name": "hakhak",
  "version": "1.0.0",
  "main": "main.js",
  "author": "Q00 <jqyu.lee@gmail.com>",
  "devDependencies": {
    "@nestjs/testing": "^7.0.6",
    "@types/aws-lambda": "^8.10.46",
    "@types/aws-serverless-express": "^3.3.3",
    "@types/chance": "^1.0.10",
    "@types/cors": "^2.8.6",
    "@types/debug": "^4.1.5",
    "@types/dotenv": "^8.2.0",
    "@prisma/cli": "^2.0.0-beta.3",
    "@types/jest": "^25.1.3",
    "@types/morgan": "^1.9.0",
    "@types/node": "^13.9.5",
    "@types/passport": "^1.0.3",
    "@types/passport-jwt": "^3.0.3",
    "@types/supertest": "^2.0.8",
    "@typescript-eslint/eslint-plugin": "^2.22.0",
    "@typescript-eslint/parser": "^2.22.0",
    "babel-eslint": "^10.1.0",
    "chance": "^1.1.4",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-prettier": "^3.1.2",
    "fork-ts-checker-webpack-plugin": "^4.1.2",
    "gts": "^1.1.2",
    "jest": "^25.1.0",
    "nodemon": "^2.0.2",
    "serverless-offline": "^6.1.2",
    "serverless-webpack": "^5.3.1",
    "supertest": "^4.0.2",
    "ts-jest": "^25.2.1",
    "ts-loader": "^6.2.2",
    "typescript": "^3.8.3",
    "webpack": "^4.42.1",
    "webpack-node-externals": "^1.7.2"
  },
  "scripts": {
    "check": "gts check",
    "clean": "gts clean",
    "compile": "tsc -p tsconfig.build.json",
    "fix": "gts fix",
    "pretest": "npm run compile",
    "posttest": "npm run check",
    "dev": "ts-node src/main.ts",
    "postinstall": "npx prisma generate",
    "build": "tsc -p tsconfig.build.json && cp schema.graphql dist",
    "deploy_test": "yarn build && NODE_ENV=production sls offline start",
    "deploy": "yarn build && NODE_ENV=production sls deploy",
    "test": "jest",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@nestjs/common": "^7.0.6",
    "@nestjs/config": "^0.4.0",
    "@nestjs/core": "^7.0.6",
    "@nestjs/graphql": "^7.1.3",
    "@nestjs/jwt": "^7.0.0",
    "@nestjs/passport": "^7.0.0",
    "@nestjs/platform-express": "^7.0.7",
    "@prisma/client": "^2.0.0-beta.2",
    "@prisma/engine-core": "^2.0.0-beta.3",
    "@prisma/generator-helper": "^2.0.0-beta.3",
    "@types/bcryptjs": "^2.4.2",
    "@types/graphql": "^14.5.0",
    "apollo-server-express": "^2.11.0",
    "aws-lambda": "^1.0.5",
    "aws-sdk": "^2.659.0",
    "aws-serverless-express": "^3.3.8",
    "axios": "^0.19.2",
    "bcryptjs": "^2.4.3",
    "class-validator": "^0.11.1",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "graphql": "^14.6.0",
    "graphql-tools": "^4.0.7",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^6.5.5",
    "ts-node": "^8.6.2",
    "type-graphql": "^0.17.6"
  }
}

```

and my webpack.config.js 
```javascript
const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

module.exports = {
  context: __dirname,
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  devtool: slsw.lib.webpack.isLocal
    ? 'cheap-module-eval-source-map'
    : 'source-map',
  resolve: {
    extensions: ['.js', '.json', '.ts'],
    symlinks: false,
    cacheWithContext: false,
    modules: [path.resolve('./src')],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  externals: [nodeExternals()],
  module: {
    rules: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      {
        test: /\.(tsx?)$/,
        loader: 'ts-loader',
        exclude: [
          [
            // path.resolve(__dirname, 'node_modules'),
            path.resolve(__dirname, '.serverless'),
            path.resolve(__dirname, '.webpack'),
          ],
        ],
        options: {
          transpileOnly: true,
          experimentalWatchApi: true,
        },
      },
    ],
  },
  plugins: [
  ],
};


```

when I sls deploy, I got error in AWS Cloud watch
```
[31m[Nest] 8   - [39m04/22/2020, 9:38:13 AM   [38;5;3m[ExceptionHandler] [39m[31m@prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma-client-js/issues/390.[39m[38;5;3m +57ms[39m
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
at new PrismaClient (/var/task/node_modules/@prisma/client/index.js:3:11)
at new s (/var/task/dist/index.js:1:2644)
at Injector.instantiateClass (/var/task/node_modules/@nestjs/core/injector/injector.js:289:19)
at callback (/var/task/node_modules/@nestjs/core/injector/injector.js:76:41)
at async Injector.resolveConstructorParams (/var/task/node_modules/@nestjs/core/injector/injector.js:117:24)
at async Injector.loadInstance (/var/task/node_modules/@nestjs/core/injector/injector.js:80:9)
at async Injector.loadProvider (/var/task/node_modules/@nestjs/core/injector/injector.js:37:9)
at async Promise.all (index 6)
at async InstanceLoader.createInstancesOfProviders (/var/task/node_modules/@nestjs/core/injector/instance-loader.js:42:9)
at async /var/task/node_modules/@nestjs/core/injector/instance-loader.js:27:13

```

How can I do?
How can I run prisma generate in serverless framework?

## How to reproduce

npx prisma generate
tsc -p tsconfig.build.json && cp schema.graphql dist
NODE_ENV=production sls deploy

## Expected behavior

make a connection using prisma client and run api server

## Prisma information

 "@prisma/client": "^2.0.0-beta.2",
 "@prisma/cli": "^2.0.0-beta.3",

## Environment & setup

- OS: mac os catalina 10.15.4
- Database: PostgreSQL
- Prisma version: 
@prisma/cli          : 2.0.0-beta.3
Current platform     : darwin
Query Engine         : query-engine 2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6 (at /Users/kyu/Desktop/hakhak/hakhak/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6 (at /Users/kyu/Desktop/hakhak/hakhak/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6 (at /Users/kyu/Desktop/hakhak/hakhak/node_modules/@prisma/cli/introspection-engine-darwin)
- Node.js version: 12.16.2

**Comment by mateo2181** [comment]
I got same error.

**Comment by rainems** [comment]
Same error here as well deploying to Google Cloud App Engine.

**Comment by AlissonEnz** [comment]
Same here deploying to AWS Lambda

**Comment by AmoDinho** [comment]
Same here for deploying to Lambda, works great locally though.... looks like I gotta go back to writing raw SQL again 😢

**Comment by AmoDinho** [comment]
Guys the solution is here: https://github.com/prisma/prisma/issues/2303

Here is my repo: https://github.com/AmoDinho/prisma2-f1-demo

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma/issues/2303

**Comment by Q00** [comment]
thank you for helping me @AmoDinho !

**Comment by yazumoto** [comment]
from #2303
in serverless.yml
```
custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
    packagerOptions:
      scripts:
        - prisma generate # <- this is it
```

**Comment by afcode123** [comment]
Hi! I am having this same issue when deploying prisma on lambda. However when trying to deploy with setup mentioned above my zipped package size becomes too large (139.14 MB). Do you have any ideas on what I might be missing?

package.json
```
{
  "name": <name>,
  "version": "1.0.0",
  "description": "Serverless aws-nodejs-typescript template",
  "main": "serverless.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "engines": {
    "node": ">=14.15.0"
  },
  "dependencies": {
    "@middy/core": "^1.5.2",
    "@middy/http-json-body-parser": "^1.5.2",
    "@prisma/client": "^3.4.2",
    "@types/graphql-fields": "^1.3.4",
    "apollo-server": "^3.5.0",
    "apollo-server-lambda": "^3.3.0",
    "axios": "^0.21.4",
    "class-validator": "^0.13.1",
    "copy-webpack-plugin": "^9.1.0",
    "dayjs": "^1.10.7",
    "express-jwt": "^6.1.0",
    "graphql": "^15.5.3",
    "graphql-fields": "^2.0.3",
    "graphql-scalars": "^1.10.1",
    "jwks-rsa": "^2.0.5",
    "nodemon": "^2.0.14",
    "reflect-metadata": "^0.1.13",
    "serverless": "^2.57.0",
    "serverless-http": "^2.7.0",
    "serverless-webpack": "^5.5.0",
    "source-map-support": "^0.5.19",
    "ts-promisify": "^3.3.2",
    "type-graphql": "^1.1.1",
    "typescript-graphql": "0.0.9",
    "webpack": "^5.51.2"
  },
  "devDependencies": {
    "@types/aws-lambda": "8.10.1",
    "@types/express-jwt": "^6.0.2",
    "@types/graphql": "^14.5.0",
    "@types/graphql-depth-limit": "^1.1.2",
    "@types/graphql-fields": "^1.3.4",
    "@types/jsonwebtoken": "^8.3.5",
    "@types/node": "^8.10.66",
    "babel-loader": "^8.2.2",
    "prisma": "^3.4.0",
    "serverless-dotenv-plugin": "^3.9.0",
    "serverless-offline": "^8.1.0",
    "serverless-plugin-typescript": "^2.0.0",
    "ts-loader": "^9.2.5",
    "tslib": "^2.3.1",
    "typegraphql-prisma": "^0.16.0",
    "typescript": "^4.4.2",
    "webpack-node-externals": "^3.0.0"
  },
  "author": "The serverless webpack authors (https://github.com/elastic-coders/serverless-webpack)",
  "license": "MIT"
}
```
serverless.yml
```
service: <api>

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  webpack:
    includeModules: true
    packagerOptions:
      scripts:
        - prisma generate

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  lambdaHashingVersion: 20201221
useDotenv: true
functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

```
webpack.config.js
```
const nodeExternals = require("webpack-node-externals");
const serverlessWebpack = require("serverless-webpack");
const CopyWebpackPlugin = require("copy-webpack-plugin");

module.exports = {
  devtool: "inline-cheap-module-source-map",
  entry: serverlessWebpack.lib.entries,
  mode: serverlessWebpack.lib.webpack.isLocal ? "development" : "production",
  module: {
    rules: [
      {
        exclude: /node_modules/,
        test: /\.ts$/,
        use: "ts-loader",
      },
    ],
  },
  experiments: {
    topLevelAwait: true,
  },
  node: false,
  externals: [nodeExternals()],
  plugins: [new CopyWebpackPlugin({ patterns: ["./prisma/schema.prisma"] })],
  optimization: {
    minimize: false,
  },
  resolve: {
    extensions: [".ts", ".js"],
  },
  target: "node",
};
```
Output of serverless deploy
```

asset src/apollo-server.js 212 KiB [emitted] (name: src/apollo-server)
asset schema.prisma 3.87 KiB [emitted] [from: prisma/schema.prisma] [copied]
orphan modules 88.9 KiB [orphan] 49 modules
runtime modules 937 bytes 4 modules
built modules 89.4 KiB [built]
  ./src/apollo-server.ts + 49 modules 89.3 KiB [not cacheable] [built] [code generated]
  external "fs" 42 bytes [built] [code generated]
  external "util" 42 bytes [built] [code generated]
webpack compiled successfully in 7796 ms
Serverless: WARNING: Could not determine version of module jsonwebtoken
Serverless: WARNING: Could not determine version of module aws-sdk
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: reflect-metadata@^0.1.13, apollo-server-lambda@^3.3.0, graphql@^15.5.3, type-graphql@^1.1.1, class-validator@^0.13.1, jsonwebtoken, jwks-rsa@^2.0.5, @prisma/client@^2.30.0, graphql-fields@^2.0.3, aws-sdk, axios@^0.21.4, dayjs@^1.10.7
Serverless: WARNING: Could not determine version of module jsonwebtoken
Serverless: WARNING: Could not determine version of module aws-sdk
Serverless: Copying existing artifacts...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service api.zip file to S3 (139.14 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
....
Serverless: Operation failed!
 
 Serverless Error ----------------------------------------
 
  An error occurred: GraphqlLambdaFunction - Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes (Service: Lambda, Status Code: 400, Request ID: 54a51c24-ad71-4670-994e-f29e611e9ce7, Extended Request ID: null)" (RequestToken: 954418bf-6c4e-a4ca-1b79-5e593eb7b2ba, HandlerErrorCode: InvalidRequest).

```

**Comment by janpio** [comment]
Please open a separate issue and provide all the information it asks for instead of posting in an old, closed issue. Thanks.
