### ISSUE TITLE
Connect nested in create not working when relation field name is mapped.

### ISSUE THREAD

**Issue by TLadd** [prisma/prisma#2294]
## Bug description

I have a one to many relationship and am trying to create one of the many entities and have it be connected to the one, which already exists. When I call

```
await ctx.prisma.site.create({
  data: { account: { connect: { id: 1 } } },
});
```
I get a null constraint violation because account_id is not being set.

## How to reproduce
Relevant part of my prisma file:
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Account {
  createdAt        DateTime          @default(now()) @map("created_at")
  id               Int               @default(autoincrement()) @id
  updatedAt        DateTime          @default(now()) @map("updated_at")
  sites            Site[]

  @@map("account")
}

model Site {
  accountId Int      @map("account_id")
  createdAt DateTime @default(now()) @map("created_at")
  id        Int      @default(autoincrement()) @id
  updatedAt DateTime @default(now()) @map("updated_at")
  account   Account  @relation(fields: [accountId], references: [id])

  @@map("site")
}
```
Call

```typescript
await ctx.prisma.site.create({
  data: { account: { connect: { id: 1 } } },
});
```

I turned on logging and DEBUG=*, and this is the output:

```
graphql_1   2020-04-24T13:35:20.945Z prisma-client Prisma Client call:
graphql_1   2020-04-24T13:35:20.945Z prisma-client prisma.site.create({
graphql_1     data: {
graphql_1       account: {
graphql_1         connect: {
graphql_1           id: 1
graphql_1         }
graphql_1       }
graphql_1     }
graphql_1   })
graphql_1   2020-04-24T13:35:20.945Z prisma-client Generated request:
graphql_1   2020-04-24T13:35:20.945Z prisma-client mutation {
graphql_1     createOneSite(data: {
graphql_1       account: {
graphql_1         connect: {
graphql_1           id: 1
graphql_1         }
graphql_1       }
graphql_1     }) {
graphql_1       accountId
graphql_1       createdAt
graphql_1       id
graphql_1       updatedAt
graphql_1     }
graphql_1   }
graphql_1   2020-04-24T13:35:20.949Z engine stdout {
graphql_1     timestamp: 'Apr 24 13:35:20.948',
graphql_1     level: 'INFO',
graphql_1     target: 'quaint::connector::metrics',
graphql_1     fields: {
graphql_1       query: 'SELECT 1',
graphql_1       item_type: 'query',
graphql_1       params: '[]',
graphql_1       duration_ms: 0
graphql_1     }
graphql_1   }
graphql_1   prisma:query SELECT 1
postgres_1  | 2020-04-24 13:35:20.950 UTC [32] ERROR:  null value in column "account_id" violates not-null constraint
postgres_1  | 2020-04-24 13:35:20.950 UTC [32] DETAIL:  Failing row contains (2020-04-24 13:35:20.948+00, 2020-04-24 13:35:20.948+00, 5, null).
postgres_1  | 2020-04-24 13:35:20.950 UTC [32] STATEMENT:  INSERT INTO "public"."site" ("created_at","updated_at") VALUES ($1,$2) RETURNING "public"."site"."id"
graphql_1   2020-04-24T13:35:20.949Z engine stdout {
graphql_1     timestamp: 'Apr 24 13:35:20.949',
graphql_1     level: 'INFO',
graphql_1     target: 'quaint::connector::metrics',
graphql_1     fields: { query: 'BEGIN', item_type: 'query', params: '[]', duration_ms: 0 }
graphql_1   }
graphql_1   prisma:query BEGIN
graphql_1   2020-04-24T13:35:20.950Z engine stdout {
graphql_1     timestamp: 'Apr 24 13:35:20.950',
graphql_1     level: 'INFO',
graphql_1     target: 'quaint::connector::metrics',
graphql_1     fields: {
graphql_1       query: 'SELECT "public"."account"."id" FROM "public"."account" WHERE "public"."account"."id" = $1 OFFSET $2',
graphql_1       item_type: 'query',
graphql_1       params: '[1,0]',
graphql_1       duration_ms: 0
graphql_1     }
graphql_1   }
graphql_1   prisma:query SELECT "public"."account"."id" FROM "public"."account" WHERE "public"."account"."id" = $1 OFFSET $2
graphql_1   2020-04-24T13:35:20.951Z engine stdout {
graphql_1     timestamp: 'Apr 24 13:35:20.951',
graphql_1     level: 'INFO',
graphql_1     target: 'quaint::connector::metrics',
graphql_1     fields: {
graphql_1       query: 'INSERT INTO "public"."site" ("created_at","updated_at") VALUES ($1,$2) RETURNING "public"."site"."id"',
graphql_1       item_type: 'query',
graphql_1       params: '[2020-04-24 13:35:20.948 UTC,2020-04-24 13:35:20.948 UTC]',
graphql_1       duration_ms: 1
graphql_1     }
graphql_1   }
graphql_1   prisma:query INSERT INTO "public"."site" ("created_at","updated_at") VALUES ($1,$2) RETURNING "public"."site"."id"
graphql_1   2020-04-24T13:35:20.951Z engine stdout {
graphql_1     timestamp: 'Apr 24 13:35:20.951',
graphql_1     level: 'INFO',
graphql_1     target: 'quaint::connector::metrics',
graphql_1     fields: {
graphql_1       query: 'ROLLBACK',
graphql_1       item_type: 'query',
graphql_1       params: '[]',
graphql_1       duration_ms: 0
graphql_1     }
graphql_1   }
graphql_1   prisma:query ROLLBACK
graphql_1   2020-04-24T13:35:20.953Z engine {
graphql_1     error: PrismaClientKnownRequestError: Null constraint violation on the fields: (`account_id`)
graphql_1         at NodeEngine.graphQLToJSError (/usr/src/app/node_modules/@prisma/engine-core/dist/NodeEngine.js:560:1)
graphql_1         at /usr/src/app/node_modules/@prisma/engine-core/dist/NodeEngine.js:468:1
graphql_1         at process.result (internal/process/task_queues.js:97:5)
graphql_1         at PrismaClientFetcher.request (/usr/src/app/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:621:13)
graphql_1         at resolve (/usr/src/app/packages/faves-backend/src/schema/index.ts:221:9) {
graphql_1       code: 'P2011',
graphql_1       meta: { constraint: [Array] }
graphql_1     }
graphql_1   }
graphql_1   2020-04-24T13:35:20.953Z printStack callsite Error:
graphql_1       at Object.model [as Site] (/usr/src/app/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:377:28)
graphql_1       at Object.n.<computed> [as create] (/usr/src/app/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:512:33)
graphql_1       at resolve (/usr/src/app/packages/faves-backend/src/schema/index.ts:221:31)
graphql_1       at field.resolve (/usr/src/app/node_modules/graphql-extensions/src/index.ts:274:18)
graphql_1       at resolveFieldValueOrError (/usr/src/app/node_modules/graphql/execution/execute.js:486:18)
graphql_1       at resolveField (/usr/src/app/node_modules/graphql/execution/execute.js:444:16)
graphql_1       at /usr/src/app/node_modules/graphql/execution/execute.js:250:18
graphql_1       at /usr/src/app/node_modules/graphql/jsutils/promiseReduce.js:23:10
graphql_1       at Array.reduce (<anonymous>)
graphql_1       at promiseReduce (/usr/src/app/node_modules/graphql/jsutils/promiseReduce.js:20:17)
graphql_1   [GraphQLError [Object]:
graphql_1   Invalid `prisma.site.create()` invocation in
graphql_1   /usr/src/app/packages/faves-backend/src/schema/index.ts:221:31
graphql_1   Null constraint violation on the fields: (`account_id`)] {
graphql_1     message: '\n' +
graphql_1       'Invalid `prisma.site.create()` invocation in\n' +
graphql_1       '/usr/src/app/packages/faves-backend/src/schema/index.ts:221:31\n' +
graphql_1       '\n' +
graphql_1       'Null constraint violation on the fields: (`account_id`)',
graphql_1     locations: [ { line: 2, column: 3 } ],
graphql_1     path: [ 'test' ],
graphql_1     extensions: {
graphql_1       code: 'INTERNAL_SERVER_ERROR',
graphql_1       exception: { code: 'P2011', meta: [Object], stacktrace: [Array] }
graphql_1     }
graphql_1   }
```

I also tried removing the null constraint, thinking maybe the account_id column would get set afterwards or something, but it just resulted in the Site row having an account_id as null. 

If I had to guess, maybe it has something to do with the mapping of column names, since that's the only thing I can think of that isn't standard.

## Expected behavior

I would expect the account_id column to be set to 1 in this case.

## Prisma information

Shared above

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Prisma version: 2.0.0-beta.3
- Node.js version: v12.16.2

**Comment by TLadd** [comment]
Yep, so if I change my prisma schema to

```
model Account {
  createdAt        DateTime          @default(now()) @map("created_at")
  id               Int               @default(autoincrement()) @id
  updatedAt        DateTime          @default(now()) @map("updated_at")
  sites            Site[]

  @@map("account")
}

model Site {
  account_id Int
  createdAt  DateTime @default(now()) @map("created_at")
  id         Int      @default(autoincrement()) @id
  updatedAt  DateTime @default(now()) @map("updated_at")
  account    Account  @relation(fields: [account_id], references: [id])
  pages      Page[]

  @@map("site")
}
```

where all I did was changed `accountId Int      @map("account_id")` to `account_id Int`, the above create with connect call works. So it definitely looks like it has to do with mapping the relation id field name.

**Comment by pantharshit00** [comment]
@TLadd We recently fixed this problem in alpha. Please try this again with the alpha version.

Use `npm install @prisma/cli@alpha && npx prisma generate` and try this again.

**Comment by brandonweiss** [comment]
Hmm, I think it might still be broken? 🤔

I’m on `2.0.0-alpha.1142`. I ran `prisma generate`. My two fields look like this:

```
brand      Brand       @relation(fields: [brandId], references: [id])
brandId    String      @map("brand")
```

Then the relevant part of insert looks like this:

```
{
  brand: {
    create: {
      name: "Brand name"
    }
  }
}
```

And I go the error: `Null constraint violation on the fields: (`brand`)`.

**Comment by TLadd** [comment]
Yep, I am also still seeing hitting the null constraint violation on version 2.0.0-alpha.1142

**Comment by pantharshit00** [comment]
I am unable to reproduce this with `2.0.0-alpha.1158`:
![image](https://user-images.githubusercontent.com/22195362/80593907-a55b0580-8a3f-11ea-8129-f421dd79ad81.png)


Please make sure that you run `npx @prisma/cli@alpha generate` in your project so that generated client is upto date with the latest version changes.

**Comment by TLadd** [comment]
Yep, pulled down 2.0.0-alpha.1158 and it's working now. I think when I tried testing two days ago I only upgraded one of the client or cli and not both. Thank you for the assistance!
