### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by mmachatschek** [prisma/prisma#22971]
### Bug description

When loading a relation with the `relationJoins` preview feature enabled on `postgres`. the query fails with an `Called 'Option::unwrap()' on a 'None' value` error.

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /Users/markus/Sites/relation-join-panic/.env
prisma:client checkPlatformCaching:postinstall 
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /Users/markus/Sites/relation-join-panic/.env
prisma:client dirname /Users/markus/Sites/relation-join-panic/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /Users/markus/Sites/relation-join-panic/prisma
prisma:client clientVersion 5.9.1
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:engines:resolveEnginePath enginePath /Users/markus/Sites/relation-join-panic/node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

### How to reproduce

I created a reproduction repo here: https://github.com/mmachatschek/relation-join-panic

### Expected behavior

Loading of the relation with the preview feature enabled should work

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["relationJoins", "nativeDistinct"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String    @id @default(cuid())
  post      Post?     @relation("User_post", fields: [postId], references: [id])
  postId    String?   @map("post")
  updatedAt DateTime? @updatedAt
  createdAt DateTime? @default(now())

  @@index([postId])
  @@index([updatedAt])
  @@index([createdAt])
}

model Post {
  id             String    @id @default(cuid())
  title          String    @unique @default("")
  updatedAt      DateTime? @updatedAt
  createdAt      DateTime? @default(now())
  from_User_post User[]    @relation("User_post")

  @@index([updatedAt])
  @@index([createdAt])
}

```

```ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const post = await prisma.post.create({
    data: {
      title: 'Hello, World!',
    },
  });
  const user = await prisma.user.create({
    data: {
      postId: post.id,
    },
  });
  const users = await prisma.user.findMany({
    include: {
      post: true,
    },
  });
  console.log(users);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });

```

### Environment & setup

| Name            | Version            |
|-----------------|--------------------|
| Node            | v20.11.0           | 
| OS              | darwin-arm64       |
| Prisma Client   | 5.9.1              |
| Query Engine    | 23fdc5965b1e05fc54e5f26ed3de66776b93de64|
| Database        | postgresql         |

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.9.1
@prisma/client          : 5.9.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.11.0
Query Engine (Node-API) : libquery-engine 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 23fdc5965b1e05fc54e5f26ed3de66776b93de64 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.9.0-32.23fdc5965b1e05fc54e5f26ed3de66776b93de64
Default Engines Hash    : 23fdc5965b1e05fc54e5f26ed3de66776b93de64
Studio                  : 0.497.0
Preview Features        : nativeDistinct, relationJoins
```

**Comment by jeremy-simplyscreens** [comment]
If you remove or change the ```@map("post")``` on the ```User``` model - the error no longer occurs. 

I cloned your repo and was able to recreate the error, after changing the map to ```@map("_post")``` and running a migration, the error no longer occurred. I deleted the repo and docker container. I cloned the repo again, changed only the map name, ran a migration, and the test script - it executed without error.  

My assumption is that the map name conflicts with the column name or another Prisma generated name.

**Comment by hornta** [comment]
I'm getting this very same error now myself. I added some `@@index` to a few models in our Prisma schema and then ran our test integration suite and it gave me this.

```
PrismaClientRustPanicError: 
Invalid `prisma.financialAsset.create()` invocation:


called `Option::unwrap()` on a `None` value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v18.18.0+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+windows++++++++++++%7C%0A%7C+Prisma+Client+++%7C+5.9.1++++++++++++++%7C%0A%7C+Query+Engine++++%7C+23fdc5965b1e05fc54e5f26ed3de66776b93de64%7C%0A%7C+Database++++++++%7C+postgresql+++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aequest%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient+prisma.%24queryRawUnsafe%28%0A++++INSERT+INTO+version%28%22legalEntityMasterKey%22%2C+%22nexusLegalEntityId%22%2C+name%2C+%22periodFrom%22%2C+%22periodTo%22%2C+%22actualsFrom%22%2C+status%2C+%22company_id%22%2C+%22thousands%22%2C+description%29+%0A++++VALUES%28%241%2C+%242%2C+%243%2C+%244%2C+%245%2C+%246%2C+%247%3A%3A%22PlanStatus%22%2C+%248%2C+%249%2C+%2410%29+RETURNING+*%2C+%5B%22LE_MASTER_KEY_1%22%2C%221%22%2C%22My+plan+c0s_5EyvV4X1mRXCh2U2i%22%2C%7B%22prisma__type%22%3A%22date%22%2C%22prisma__value%22%3A%222021-01-01T00%3A00%3A00.000Z%22%7D%2C%7B%22prisma__type%22%3A%22date%22%2C%22prisma__value%22%3A%222021-12-31T00%3A00%3A00.000Z%22%7D%2C%7B%22prisma__type%22%3A%22date%22%2C%22prisma__value%22%3A%222021-01-01T00%3A00%3A00.000Z%22%7D%2C%22in_progress%22%2C%222%22%2Cfalse%2C%22My+plan+description%22%5D%29%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient+prisma.%24queryRawUnsafe%28%0A++++++INSERT+INTO+plan_dimension+%28%22planId%22%2C+dimension%29%0A++++++VALUES+%28%271%27%2C+%27Customer%27%29%2C+%28%271%27%2C+%27Product%27%29%2C+%28%271%27%2C+%27Project%27%29%2C+%28%271%27%2C+%27Supplier%27%29%0A++++%2C+%5B%5D%29%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient%3AlibraryEngine+requestBatch%0Aprisma%3Aclient+prisma.%24queryRawUnsafe%28%0A++++insert+into+%22allocationKey%22+%28name%2C+%22keyType%22%2C+%22generatedFor%22%2C+%22versionId%22%2C+%22accountId%22%2C+%22organizationalUnitId%22%29%0A++++select+name%2C+%22keyType%22%2C+%22generatedFor%22%2C+%242%2C+%22accountId%22%2C+%22organizationalUnitId%22%0A++++from+json_populate_recordset%28NULL%3A%3A%22allocationKey%22%2C+%241%3A%3Ajson%29%0A++++returning+*%0A++++%2C+%5B%22%5B%5D%22%2C%7B%22prisma__type%22%3A%22bigint%22%2C%22prisma__value%22%3A%221%22%7D%5D%29%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient+prisma.%24queryRawUnsafe%28%0A++++insert+into+allocation+%28period%2C+amount%2C+%22allocationKeyId%22%2C+%22generatedFor%22%29%0A++++select+period%2C+amount%2C+%22allocationKeyId%22%2C+%22generatedFor%22%0A++++from+json_populate_recordset%28NULL%3A%3A%22allocation%22%2C+%241%3A%3Ajson%29%0A++++%2C+%5B%22%5B%5D%22%5D%29%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3Atrue%7D%7D%7D%7D%7D%7D%7D%7D%7D%0A%60%60%60%0A&title=called+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value&template=bug_report.yml

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at ai.handleRequestError (C:\Users\Användaren\Documents\planning-api\node_modules\.pnpm\@prisma+client@5.9.1_prisma@5.9.1\node_modules\@prisma\client\runtime\library.js:126:7136)
    at ai.handleAndLogRequestError (C:\Users\Användaren\Documents\planning-api\node_modules\.pnpm\@prisma+client@5.9.1_prisma@5.9.1\node_modules\@prisma\client\runtime\library.js:126:6109)
    at ai.request (C:\Users\Användaren\Documents\planning-api\node_modules\.pnpm\@prisma+client@5.9.1_prisma@5.9.1\node_modules\@prisma\client\runtime\library.js:126:5817)
    at l (C:\Users\Användaren\Documents\planning-api\node_modules\.pnpm\@prisma+client@5.9.1_prisma@5.9.1\node_modules\@prisma\client\runtime\library.js:131:9709)
    at FinancialAssetsService.create (C:\Users\Användaren\Documents\planning-api\src\features\finance\financialAssetsService.ts:135:25)
    at Object.handler (C:\Users\Användaren\Documents\planning-api\src\features\finance\financialAssetsPlanModuleDefinition.ts:44:33)
    at handler (C:\Users\Användaren\Documents\planning-api\src\features\common\planModuleRepository\PlanModuleRepository.ts:106:11)
    at C:\Users\Användaren\Documents\planning-api\src\utils\createRoute.ts:20:5 {
  clientVersion: '5.9.1'
}
```
