### ISSUE TITLE
`Only reachable with String types.`

### ISSUE THREAD

**Issue by MuhammadBilalQamar** [prisma/prisma#23138]
### Bug description

```
    at si.handleRequestError (F:\VQode\siingio\node_modules\@prisma\client\runtime\library.js:125:7178)
    at si.handleAndLogRequestError (F:\VQode\siingio\node_modules\@prisma\client\runtime\library.js:125:6151)
    at si.request (F:\VQode\siingio\node_modules\@prisma\client\runtime\library.js:125:5859)
    at async l (F:\VQode\siingio\node_modules\@prisma\client\runtime\library.js:130:9805)
    at async messagesAPI.beforeGet (webpack-internal:///(api)/./pages/api/messages/[[...id]].ts:45:34)
    at async messagesAPI.handleGet (webpack-internal:///(api)/./libs/rest-handlers.ts:47:17)
    at async messagesAPI.handleRequest (webpack-internal:///(api)/./libs/rest-handlers.ts:187:17) {
  clientVersion: '5.8.0'
}
thread 'tokio-runtime-worker' panicked at query-engine\connectors\mongodb-query-connector\src\filter.rs:753:22:
Only reachable with String types.
error======> PrismaClientRustPanicError:
Invalid `prisma.messages.findMany()` invocation:


Only reachable with String types.

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```
facing this issue

Here is my query:

```typescript
const messages = await prisma.messages.findMany({
  where: {
    chatRoomId: { contains: roomId, mode: 'insensitive' },
  },
});
console.log('messages===>', messages);
```

and here is my `Messages` model:

```prisma
model Messages {
  id                   String      @id @default(auto()) @map("_id") @db.ObjectId
  sender               Users       @relation("sender", fields: [senderId], references: [id])
  senderId             String      @db.ObjectId
  edited               Boolean     @default(false)
  timestamp            DateTime    @default(now())
  content              String
  chatRoom             ChatRooms   @relation(fields: [chatRoomId], references: [id])
  chatRoomId           String      @db.ObjectId
  file                 File?
  seenBy               Users[]     @relation(fields: [seenByIds], references: [id])
  seenByIds            String[]    @db.ObjectId
  emojis               Json?
  replies              Messages[]  @relation("parentMessage")
  parentMessage        Messages?   @relation("parentMessage", fields: [parentMessageId], references: [id], onDelete: NoAction, onUpdate: NoAction)
  parentMessageId      String?     @db.ObjectId
  lastMessageChatRooms ChatRooms[] @relation("lastMessage")
  createdAt            DateTime    @default(now())
  updatedAt            DateTime    @default(now())
  deleted              Boolean     @default(false)
}
```

**Comment by jkomyno** [comment]
Hi @MuhammadBilalQamar, we kindly need additional information in order to investigate this issue:
1. Can you please share the value of `roomId` that triggered the error in your TypeScript snippet?
2. Can you please post a more complete Prisma schema? The `Messages` model references other models via `@relation` attributes, so we currently can't use that subset of a schema to attempt reproducing this issue.

Thanks!

**Comment by Jolg42** [comment]
@MuhammadBilalQamar please take a look at my colleague's comment above, without an answer we would close this issue later.
