### ISSUE TITLE
Schema field annotated with @updatedAt is not updated at data creation

### ISSUE THREAD

**Issue by XtofCH** [prisma/prisma#23174]
### Problem statement
Creation of new db entries fails, with the @updatedAt (see schema below) related exception below:
```
async function main() {
   await prisma.address.create(
Null constraint violation on the fields: (`updatedAt`)
    at ai.handleRequestError (C:\Dev\Web\deno\inventory\prisma\node_modules\@prisma\client\runtime\library.js:126:6775)
    at ai.handleAndLogRequestError (C:\Dev\Web\deno\inventory\prisma\node_modules\@prisma\client\runtime\library.js:126:6109)
    at ai.request (C:\Dev\Web\deno\inventory\prisma\node_modules\@prisma\client\runtime\library.js:126:5817)
    at async l (C:\Dev\Web\deno\inventory\prisma\node_modules\@prisma\client\runtime\library.js:131:9709)
    at async main (C:\Dev\Web\deno\inventory\prisma\prisma\seed.ts:9:3) {
  code: 'P2011',
  clientVersion: '5.9.1',
  meta: { modelName: 'address', constraint: [ 'updatedAt' ] }

```
I cannot specifiy the value for the field updatedAt, since the prisma generated client structures do not contain the @updatedAt-annotated field (correct). But the engine does not process it/set it either. How can I solve this issue?

### How to reproduce

1. Create the table below (s. SQL script)
2. Generate the prisma schema
3. Run the client code (e. g. `ts-node seed.ts`)

### Expected behavior

I expect the prisma client to set the current timestamp on the field "updatedAt" transparently, when calling `await prisma.address.create` or optionally allow me to set the field's value (not preferred).

### Prisma information

After pulling the db schema (see sql script below) and get the prisma generated schema below:

```
model address {
  id          String      @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  createdAt   DateTime    @default(now())
  updatedAt   DateTime    @updatedAt
  addresstype Int?        @db.SmallInt
  firstname   String?     @db.VarChar(100)
  lastname    String?     @db.VarChar(100)
  coremark    String?     @db.VarChar(150)
  street      String?     @db.VarChar(150)
  streetno    String?     @db.VarChar(20)
  pobox       String?     @db.VarChar(20)
  regioncode  String?     @db.VarChar(10)
  countrycode String?     @db.VarChar(10)
}

```
```ts
// Add your code using Prisma Client
import { PrismaClient } from '@prisma/client';
import { address } from './generated/client/index';

const prisma = new PrismaClient();
async function main() {
  await prisma.address.create({
    data: {
      "addresstype": 1,
      "firstname": "John",
      "lastname": "Doe",
      "coremark": "Apartment 101",
      "street": "Main Street",
      "streetno": "123",
      "pobox": "PO Box 456",
      "region": "Cityville",
      "regioncode": "CV",
      "countrycode": "US",
    }
  });
}
main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
  })
```

### Environment & setup

- OS: Windows 11
- Database: PostgreSQL
- Node.js version: v21.6.2
- npm: 10.4.0

### Prisma Version

- prisma@5.9.1
- @prisma/client@5.9.1

**Comment by XtofCH** [comment]
...here is the SQL script for the table creation:
```
CREATE TABLE IF NOT EXISTS public.address
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    "createdAt" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    addresstype smallint,
    firstname character varying(100) COLLATE pg_catalog."default",
    lastname character varying(100) COLLATE pg_catalog."default",
    coremark character varying(150) COLLATE pg_catalog."default",
    street character varying(150) COLLATE pg_catalog."default",
    streetno character varying(20) COLLATE pg_catalog."default",
    pobox character varying(20) COLLATE pg_catalog."default",
    region character varying(100) COLLATE pg_catalog."default",
    regioncode character varying(10) COLLATE pg_catalog."default",
    countrycode character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT address_pkey PRIMARY KEY (id)
)

```

**Comment by XtofCH** [comment]
I found the error (my mistake!): 
the problem was the import statement `import { PrismaClient } from '@prisma/client';`
Correct is `import { PrismaClient } from './prisma/generated/client'`;

Now it's working.
