### ISSUE TITLE
When using `previewFeatures` (metrics) with `$extends`, TS can't compile

### ISSUE THREAD

**Issue by yorch** [prisma/prisma#23180]
### Bug description

When using Prisma `metrics` preview feature and client extensions, TypeScript can't compile and throws an error like:

```
TSError: ⨯ Unable to compile TypeScript:
index.ts:25:38 - error TS2339: Property '$metrics' does not exist on type 'DynamicClientExtensionThis<TypeMap<InternalArgs & { result: {}; model: { user: { findById: () => (id: string) => Promise<{ id: string; name: string | null; email: string; } | null>; }; }; query: {}; client: {}; }>, TypeMapCb, { ...; }>'.
```

### How to reproduce

Running code: https://codesandbox.io/p/devbox/prisma-extends-with-preview-fd76zg

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  output          = "src/generated/prisma-client"
  previewFeatures = ["metrics"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id          String    @id @default(uuid())
  name        String?
  email       String
}
```

```ts
import { PrismaClient } from "./src/generated/prisma-client";

const prisma = new PrismaClient();

const prismaExtended = new PrismaClient().$extends({
  model: {
    user: {
      findById: async (id: string) => prisma.user.findUnique({ where: { id } }),
    },
  },
});

(async () => {
  try {
    console.log(await prisma.$metrics.prometheus());
    console.log(await prisma.user.findUnique({ where: { id: "123" } }));
  } catch (error) {
    console.log("PRISMA ERROR:", (error as Error).toString());
  }

  // When trying to use an extended Prisma client TS can't compile because:
  // Property '$metrics' does not exist on type 'DynamicClientExtensionThis<TypeMap<InternalArgs & ...'
  try {
    console.log(await prismaExtended.$metrics.prometheus());
    console.log(await prismaExtended.user.findById("123"));
  } catch (error) {
    console.log("EXTENDED PRISMA ERROR:", error);
  }
})();
```

### Environment & setup

- OS: macOS, Linux
- Database: PostgreSQL
- Node.js version: 18

### Prisma Version

```
5.9.1
```

**Comment by janpio** [comment]
Can confirm that Client Extensions seem to remove `$metrics` from the Client instance:

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["metrics"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Project {
  id    String @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  title String
}
```

```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const prismaExtended = new PrismaClient().$extends({
    model: {
      project: {
        findById: async (id: string) => prisma.project.findUnique({ where: { id } }),
      },
    },
  });

  console.log(await prisma.$metrics.prometheus());
  console.log(await prisma.project.findUnique({ where: { id: "123" } }));

  console.log(await prismaExtended.$metrics.prometheus());
  console.log(await prismaExtended.project.findById("123"));
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
```

leads to

```
ts-node script.ts

/workspace/prisma-client-extensions/row-level-security/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
script.ts:17:36 - error TS2339: Property '$metrics' does not exist on type 'DynamicClientExtensionThis<TypeMap<InternalArgs & { result: {}; model: { project: { findById: () => (id: string) => Promise<{ id: string; title: string; } | null>; }; }; query: {}; client: {}; }>, TypeMapCb, { ...; }>'.

17   console.log(await prismaExtended.$metrics.prometheus());
                                      ~~~~~~~~

    at createTSError (/workspace/prisma-client-extensions/row-level-security/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/workspace/prisma-client-extensions/row-level-security/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/workspace/prisma-client-extensions/row-level-security/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/workspace/prisma-client-extensions/row-level-security/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/workspace/prisma-client-extensions/row-level-security/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.require.extensions.<computed> [as .ts] (/workspace/prisma-client-extensions/row-level-security/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
  diagnosticCodes: [ 2339 ]
}
```

**Comment by Oliver-Bagin** [comment]
It looks to me like it still exists on the object and that its just a type issue. While I wait for a patch I am using the following:
```ts
const metrics = await (prisma as any as PrismaClient<any, any, any>).$metrics.json()
```

**Comment by andreasciamanna** [comment]
@Oliver-Bagin, how would you adapt this workaround in a NestJS context where `prisma` is an instance of ``?

```ts
@Injectable()
export class PrismaService
  extends PrismaClient<Prisma.PrismaClientOptions, Prisma.LogLevel>
  implements OnModuleInit
{

// ...

}
```


```ts
@Injectable()
export class PrismaMetricsService {
  constructor(private readonly prisma: PrismaService) {}

  async json() {
    return this.prisma.$metrics.json();
  }
}
```


`const metrics = await (this.prisma as any as PrismaClient<any, any, any>).$metrics.json()` inside of `async json()` won't work.
