### ISSUE TITLE
Prisma Client `ERR_INVALID_ARG_TYPE`: `Expected "port" to be a number between 0 and 65535`

### ISSUE THREAD

**Issue by nfichter** [prisma/prisma#23226]
### Bug description

When the Prisma client tries to connect to CockroachDB, it fails to parse the port as a number, and I get the following error:

```
PrismaClientKnownRequestError: 
Invalid `prisma.errorType.findMany()` invocation:


Expected "port" to be a number between 0 and 65535
 code: "ERR_INVALID_ARG_TYPE"

      at new Ue (/Users/noah-slash/teaching-assistant/node_modules/@prisma/client/runtime/binary.js:17015:3)
      at handleRequestError (/Users/noah-slash/teaching-assistant/node_modules/@prisma/client/runtime/binary.js:24306:11)
      at handleAndLogRequestError (/Users/noah-slash/teaching-assistant/node_modules/@prisma/client/runtime/binary.js:24259:5)
      at /Users/noah-slash/teaching-assistant/node_modules/@prisma/client/runtime/binary.js:24241:5
prisma:engine Client Version: 5.10.1 +5ms
prisma:engine Engine Version: query-engine 5a9203d0590c951969e85a7d07215503f4672eb9 +0ms
prisma:engine Active provider: cockroachdb +0ms
```

Connection string: `postgresql://root@localhost:26257/test_db`

I "solved" this by going into `node_modules/@prisma/client/runtime/binary.js` and finding the line where the request was being made after some debugging. Logging the request, I got:

```
URL {
  href: "http://127.0.0.1:57697/",
  origin: "http://127.0.0.1:57697",
  protocol: "http:",
  username: "",
  password: "",
  host: "127.0.0.1:57697",
  hostname: "127.0.0.1",
  port: "57697",
  pathname: "/",
  hash: "",
  search: "",
  searchParams: URLSearchParams {},
  toJSON: [Function: toJSON],
  toString: [Function: toString],
}
```

I noticed that the port was a string, and this error message indicated it should have been a number. So I updated the line where the port was being parsed to wrap it in `Number()`, and now it works, but obviously this means that I'd have to do this every time I generate the client.

### How to reproduce

I'm not exactly sure. It happened once, then I changed from the default engine to the binary engine and it stopped happening, then seemingly out of nowhere it started happening again. I suspect it might have something to do with the fact that I'm using Bun instead of Node, since I haven't seen anyone else report this issue anywhere.

### Expected behavior

Should successfully connect to the database and make the query.

### Prisma information

```
generator client {
  provider   = "prisma-client-js"
  engineType = "binary"
}

datasource db {
  provider = "cockroachdb"
  url      = env("DB_CONNECTION_STRING")
}
```

### Environment & setup

- OS: macOS
- Database: CockroachDB
- Node.js version: bun 1.0.26

### Prisma Version

```
prisma                  : 5.10.1
@prisma/client          : 5.10.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v18.6.0
Query Engine (Node-API) : libquery-engine 5a9203d0590c951969e85a7d07215503f4672eb9 (at ../../../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 5a9203d0590c951969e85a7d07215503f4672eb9 (at ../../../node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.10.0-34.5a9203d0590c951969e85a7d07215503f4672eb9
Default Engines Hash    : 5a9203d0590c951969e85a7d07215503f4672eb9
Studio                  : 0.498.0
```

**Comment by Jarred-Sumner** [comment]
This is a bug in Bun, which should be fixed by https://github.com/oven-sh/bun/pull/9047
