### ISSUE TITLE
Inconsistent column data: Unexpected conversion failure for field Keys.private_key from String(...) to Bytes. Reason: Could not convert from `base64 encoded bytes` to `PrismaValue::Bytes`

### ISSUE THREAD

**Issue by aacoimbra** [prisma/prisma#23262]
### Bug description

I've updated prisma to 5.10.2 and activated `previewFeatures = ["relationJoins"]`.

Then my server started raising the following error:

``` 
PrismaClientKnownRequestError: 
Invalid `prisma.wallet.findUnique()` invocation:


Inconsistent column data: Unexpected conversion failure for field Keys.private_key from String(VALUE HERE) to Bytes. Reason: Could not convert from `base64 encoded bytes` to `PrismaValue::Bytes`      
    at _n.handleRequestError (...\node_modules\@prisma\client\runtime\library.js:123:6854)
    at _n.handleAndLogRequestError (...\node_modules\@prisma\client\runtime\library.js:123:6188)
    at _n.request (...\node_modules\@prisma\client\runtime\library.js:123:5896)
    at async l (...\node_modules\@prisma\client\runtime\library.js:128:10871)
    at async main (file:///.../src/test.ts:11:24) {
  code: 'P2023',
  clientVersion: '5.10.2',
  meta: {
    modelName: 'Wallet',
    message: 'Unexpected conversion failure for field Keys.private_key from String(VALUE HERE) to Bytes. Reason: Could not convert from `base64 encoded bytes` to `PrismaValue::Bytes`'
  }
}
```

Removing `relationJoins` solves the issue.

### How to reproduce

1. Have a base64 encoded bytes object stored in a Bytes field
2. Try to retrieve this field

### Expected behavior

Return of the stored field.

### Prisma information

Here is are some relevant pieces of my prisma schema.

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
  // previewFeatures = ["relationJoins"]
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "foreignKeys"
}

model Keys {
  id          String @id @default(uuid())
  public_key  String
  private_key Bytes
  index       Int

  wallet    Wallet @relation( fields: [wallet_id], references: [id])
  wallet_id String

  @@index([wallet_id])
}

```

```ts
const wallet = await prisma.wallet.findUnique({
	where: { id: id },
	include: { 
		keys:  true
	},
});

```

### Environment & setup

- OS: Amazon Linux 2 (also managed to replicate in windows 11)
- Database: PlanetScale
- Node.js version: Node.js 18.x

### Prisma Version

```
prisma                  : 5.10.2
@prisma/client          : 5.10.2
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v18.17.0
Query Engine (Node-API) : libquery-engine 5a9203d0590c951969e85a7d07215503f4672eb9 (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 5a9203d0590c951969e85a7d07215503f4672eb9 (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.10.0-34.5a9203d0590c951969e85a7d07215503f4672eb9
Default Engines Hash    : 5a9203d0590c951969e85a7d07215503f4672eb9
Studio                  : 0.499.0
```

**Comment by jgnieuwhof** [comment]
I just ran into this issue as well, when using `@db.Oid` as a foreign key with `relationJoins` enabled:

```schema.prisma
datasource db {
  provider = "postgresql"
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["relationJoins"]
}

model File {
  oid    Int @id @db.Oid
  files  UserFile[]
}

model UserFile {
  id        String @id @default(cuid())
  fileOid   Int @db.Oid
  file      File @relation(fields: [fileOid], references: [oid], onDelete: Cascade)
}
```

```typescript
const results = await prisma.userFile.findMany({
  include: {
    file: true,
  },
});

```

```
PrismaClientKnownRequestError: 
Invalid `prisma.userFile.findMany()` invocation in
../script.ts:17:60

  14 import { prisma } from "@/lib/prisma";
  15 
  16 async function main(_args: string[]) {
→ 17   const results = await prisma.userFile.findMany(
Inconsistent column data: Unexpected conversion failure for field File.oid from String(65586) to Int.
    at In.handleRequestError (../node_modules/@prisma/client/runtime/library.js:122:6854)
    at In.handleAndLogRequestError (../node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (../node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (../node_modules/@prisma/client/runtime/library.js:127:10871)
    at async main (../script.ts:17:60) {
  code: 'P2023',
  clientVersion: '5.11.0',
  meta: {
    modelName: 'FhirResourceIngestFile',
    message: 'Unexpected conversion failure for field StudyFile.oid from String(65586) to Int.'
  }
}
```

**Comment by Weakky** [comment]
Hey @aacoimbra,

I'm afraid I'm unable to reproduce your issue. I've tried seeding a planetscale db with the following `Bytes` columns:

```prisma
model Test {
  id    Int    @id @default(autoincrement())
  bytes Bytes?

  childId Int?
  child   Child? @relation(fields: [childId], references: [id])
}

model Child {
  id    Int    @id @default(autoincrement())
  bytes Bytes

  Test  Test[]
}
```

`Child.bytes`  was seeded with `"Zmxhdmlhbg=="` (this is `"hello world!"` in base64).

I then queried it back with `relationJoins`:

```sql
SELECT
  `t1`.`id`,
  `t1`.`childId`,
  (
    SELECT
      JSON_OBJECT('bytes', to_base64(`t2`.`bytes`))
    FROM
      `repro-23262`.`Child` AS `t2`
    WHERE
      `t1`.`childId` = `t2`.`id`
    LIMIT
      ?
  ) AS `child`
FROM
  `repro-23262`.`Test` AS `t1`
```

Which returned the expected result (`aGVsbG8gd29ybGQh`).

Is there any way you could provide us with a reproducible client snippet (which includes some fake bytes data) ? Thank you 🙏

**Comment by Weakky** [comment]
@jgnieuwhof I have extracted your comment into a separate issue here https://github.com/prisma/prisma/issues/23816. A PR is already up for yours and should be available next release.

**Comment by Weakky** [comment]
Thanks for the additional information @aacoimbra, I have successfully reproduced your issue 🙏.

Internal note: Private repro can be found here https://github.com/prisma/team-orm/issues/1128
