### ISSUE TITLE
Uncaught (in promise) Error: PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `unknown`).

### ISSUE THREAD

**Issue by tigran1100** [prisma/prisma#23322]
### Bug description

In general prisma is working fine, even in other parts of my application, but idk why prisma don't want to work for "VerificationToken" model

This is the error code from console:
index-browser.js:186  Uncaught (in promise) Error: PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `unknown`).
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report
    at Object.get (index-browser.js:186:15)
    at generateVerificationToken (tokens.ts:53:41)
    at async sendVerificationCode (alertDialoge.tsx:33:29)

I checked my code a few times and it really seems to be a bug.
I'm using microsoft edge, but I have also tested on google chrome beta and the issue still remains

### How to reproduce

	const verificationToken = await prisma.verificationToken.create({
		data: {
			token: token,
			email: email,
			code: code,
			expires: expires,
		},
	});
	
	
	
This is the raw data object that I'm passing to prisma
{
    "token": "2d0aef21-5603-4a94-a14c-2f6affca9d9d",
    "email": "asd@asd.asd",
    "code": "771176",
    "expires": "2024-02-29T08:04:26.885Z"
}

### Expected behavior

Expected behavior is to work

### Prisma information

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?
// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model VerificationToken {
  id      String   @id @default(uuid())
  email   String?  @unique
  token   String?  @unique
  code    String?  @unique
  expires DateTime?

  @@unique([email, token])
}

### Environment & setup

- OS: Windows 11
- Database: MySQL
- Node.js version: 20.11.0

### Prisma Version

5.10.2

**Comment by tigran1100** [comment]
___UPDATE___

The error occured because I used prisma in client component.
In server component everything works fine.
