### ISSUE TITLE
Wrong `binaryTarget` in Alpine-based Bun docker image

### ISSUE THREAD

**Issue by marvinruder** [prisma/prisma#23340]
### Bug description

When running the commands below in an Alpine-based Bun Docker container (e.g. oven/bun:1.0.30-alpine), the output shows

```
/home/bun/app # bunx prisma -v
285 | - ${o}
286 | - ${u}
287 | - ${c}`)}function qJ(e,r){return xl(()=>eu(e,r),n=>n)}async function o6(file){let dir=eval("__dirname");if(dir.match(nd)){let e=Zo.default.join(MJ.default,"prisma-binaries");await(0,LJ.ensureDir)(e);let r=Zo.default.join(e,Zo.default.basename(file)),n=await Qo.default.promises.readFile(file);return await Qo.default.promises.writeFile(r,n),FJ(r),r}return file}var UJ=require("@prisma/engines");var GJ=$(rc());function BJ(e){let r=e.e,n=c=>`Prisma cannot find the required \`${c}\` system library in your system`,i=r.message.includes("cannot open shared object file"),a=`Please refer to the documentation about Prisma's system requirements: ${E1("https://pris.ly/d/system-requirements")}`,o=`Unable to require(\`${G(e.id)}\`).`,u=$e({message:r.message,code:r.code}).with({code:"ENOENT"},()=>"File does not exist.").when(({message:c})=>i&&c.includes("libz"),()=>`${n("libz")}. Please install it and try again.`).when(({message:c})=>i&&c.includes("libgcc_s"),()=>`${n("libgcc_s")}. Please install it and try again.`).when(({message:c})=>i&&c.includes("libssl"),()=>{let c=e.platformInfo.libssl?`openssl-${e.platformInfo.libssl}`:"openssl";return`${n("libssl")}. Please install ${c} and try again.`}).when(({message:c})=>c.includes("GLIBC"),()=>`Prisma has detected an incompatible version of the \`glibc\` C standard library installed in your system. This probably means your system may be too old to run Prisma. ${a}`).when(({message:c})=>e.platformInfo.platform==="linux"&&c.includes("symbol not found"),()=>`The Prisma engines are not compatible with your system ${e.platformInfo.originalDistro} on (${e.platformInfo.archFromUname}) which uses the \`${e.platformInfo.binaryTarget}\` binaryTarget by default. ${a}`).otherwise(()=>`The Prisma engines do not seem to be compatible with your system. ${a}`);return`${o}
288 | ${u}
289 | 
290 | Details: ${r.message}`}function jJ(e,r){try{return require(e)}catch(n){let i=BJ({e:n,platformInfo:r,id:e});throw new Error(i)}}async function qke(e,r){r||(r=(0,UJ.getCliQueryEngineBinaryType)()),e=await eu(r,e);let n=await D1();if(r==="libquery-engine"){Hp();let i=jJ(e,n);return`libquery-engine ${i.version().commit}`}else{let{stdout:i}=await(0,GJ.default)(e,["--version"]);return i}}function VJ(e,r){return xl(()=>qke(e,r),n=>n)}async function SE(){let r=[{name:"query-engine",type:(0,HJ.getCliQueryEngineBinaryType)()},{name:"schema-engine",type:"schema-engine"}],n=r.map(({name:c,type:p})=>jke(p).then(l=>[c,l])),i=await Promise.all(n).then(Object.fromEntries),a=r.map(({name:c})=>{let[p,l]=Bke(i[c]);return[{[c]:p},l]}),o=a.map(c=>c[0]),u=a.flatMap(c=>c[1]);return[o,u]}function Bke(e){let r=[],n=$e(e).with({fromEnvVar:sr.when(cj)},u=>`, resolved by ${u.fromEnvVar.value}`).otherwise(()=>""),i=$e(e).with({path:sr.when($s)},u=>u.path.right).with({path:sr.when(Un)},u=>(r.push(u.path.left),"E_CANNOT_RESOLVE_PATH")).exhaustive();return[`${$e(e).with({version:sr.when($s)},u=>u.version.right).with({version:sr.when(Un)},u=>(r.push(u.version.left),"E_CANNOT_RESOLVE_VERSION")).exhaustive()} (at ${WJ.default.relative(process.cwd(),i)}${n})`,r]}async function jke(e){let r=lj(Bc(e)),n=(0,u6.pipe)(r,fx(u=>u.fromEnvVar)),i=await(0,u6.pipe)(r,pj(()=>qJ(e),u=>Tj(u.path)))(),a=await(0,u6.pipe)(i,J1,Nj(u=>VJ(u,e)))();return{path:i,version:a,fromEnvVar:n}}var zJ=$(bt());var DE=ae("prisma:validate"),CE=class extends Error{constructor(r){let i=`${$e(r).with({_tag:"parsed"},({errorCode:a,message:o,reason:u})=>{let c=a?`Error code: ${a}`:"";return`${u}
                                                                                                                       ^
error: Unable to require(`/tmp/bunx-0-prisma@latest/node_modules/@prisma/engines/libquery_engine-linux-musl-arm64-openssl-3.0.x.so.node`).
The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: /usr/lib/libc.so: invalid ELF header
      at jJ (/tmp/bunx-0-prisma@latest/node_modules/prisma/build/index.js:290:114)
      at /tmp/bunx-0-prisma@latest/node_modules/prisma/build/index.js:290:266

prisma                  : 5.10.2
@prisma/client          : Not found
Computed binaryTarget   : linux-musl-arm64-openssl-3.0.x
Operating System        : linux
Architecture            : arm64
Node.js                 : v21.6.0
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at ../../../tmp/bunx-0-prisma@latest/node_modules/@prisma/engines/libquery_engine-linux-musl-arm64-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 5a9203d0590c951969e85a7d07215503f4672eb9 (at ../../../tmp/bunx-0-prisma@latest/node_modules/@prisma/engines/schema-engine-linux-musl-arm64-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.10.0-34.5a9203d0590c951969e85a7d07215503f4672eb9
Default Engines Hash    : 5a9203d0590c951969e85a7d07215503f4672eb9
Studio                  : 0.499.0
error: Script not found "/tmp/bunx-0-prisma@latest/node_modules/prisma/build/child"
```

(that last line is tracked in #23339 already)

It would appear that the binary target `linux-musl-arm64-openssl-3.0.x` is chosen because Alpine is detected as operating system. However, Bun requires glibc to run, so their Alpine-based container run with glibc instead of musl. It would be great if Prisma could somehow detect the installed libc more accurately (or at least check whether the runtime is Bun and then refrain from choosing any musl-related binary target).

### How to reproduce

```sh
bunx prisma -v
```

### Expected behavior

`debian-openssl-3.0.x ` or `linux-arm64-openssl-3.0.x` are chosen as binary targets.

### Prisma information

Not relevant at this point.

### Environment & setup

- OS: Alpine-based Docker container with glibc installed
- Database: N/A
- Node.js version: Bun revision 1.0.30+1424a196f

### Prisma Version

See above.

**Comment by Jolg42** [comment]
@marvinruder Did you try manually specifying the "binaryTarget" for the CLI?

See https://www.prisma.io/docs/orm/reference/environment-variables-reference#prisma_cli_binary_targets

You can for example set the env var, and then install, here with npm:
```sh
rm -rf ./node_modules
PRISMA_CLI_BINARY_TARGETS=linux-arm64-openssl-3.0.x npm install
```

Let us know if you try this and what happens, that would be helpful to know.

**Comment by marvinruder** [comment]
With `PRISMA_CLI_BINARY_TARGETS=linux-arm64-openssl-3.0.x` set, I get a different error message when running `bunx prisma -v`:

```
error: Could not find schema-engine binary. Searched in:
- /tmp/bunx-0-prisma@latest/node_modules/@prisma/engines/schema-engine-linux-musl-arm64-openssl-3.0.x
- /tmp/bunx-0-prisma@latest/node_modules/prisma/schema-engine-linux-musl-arm64-openssl-3.0.x
- /tmp/bunx-0-prisma@latest/node_modules/schema-engine-linux-musl-arm64-openssl-3.0.x
- /tmp/bunx-0-prisma@latest/node_modules/prisma/runtime/schema-engine-linux-musl-arm64-openssl-3.0.x
      at /tmp/bunx-0-prisma@latest/node_modules/prisma/build/index.js:283:9867

prisma                  : 5.10.2
@prisma/client          : Not found
Computed binaryTarget   : linux-musl-arm64-openssl-3.0.x
Operating System        : linux
Architecture            : arm64
Node.js                 : v21.6.0
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at E_CANNOT_RESOLVE_PATH)
Schema Engine           : E_CANNOT_RESOLVE_VERSION (at E_CANNOT_RESOLVE_PATH)
Schema Wasm             : @prisma/prisma-schema-wasm 5.10.0-34.5a9203d0590c951969e85a7d07215503f4672eb9
Default Engines Hash    : 5a9203d0590c951969e85a7d07215503f4672eb9
Studio                  : 0.499.0
error: Script not found "/tmp/bunx-0-prisma@latest/node_modules/prisma/build/child"
```

The correct binaries are downloaded though:

```
/home/bun/app # ls -la /tmp/bunx-0-prisma@latest/node_modules/@prisma/engines/
total 33196
drwxr-xr-x    4 root     root          4096 Mar  4 14:05 .
drwxr-xr-x    7 root     root          4096 Mar  4 14:05 ..
-rw-r--r--    2 root     root         11357 Mar  4 14:05 LICENSE
-rw-r--r--    2 root     root           740 Mar  4 14:05 README.md
drwxr-xr-x    3 root     root          4096 Mar  4 14:05 dist
-rwxrwxrwx    1 root     root      14265184 Mar  4 14:05 libquery_engine-linux-arm64-openssl-3.0.x.so.node
-rw-r--r--    2 root     root          1087 Mar  4 14:05 package.json
-rwxrwxrwx    1 root     root      19688552 Mar  4 14:05 schema-engine-linux-arm64-openssl-3.0.x
drwxr-xr-x    2 root     root          4096 Mar  4 14:05 scripts
```

However, when generating the Prisma Client:

```sh
mkdir hello-prisma
cd hello-prisma
bun init -y
bun install prisma
bun prisma init
# add a model to the schema, e.g.
# model User {
#   id    Int     @id @default(autoincrement())
#   email String  @unique
#   name  String?
# }
bun prisma generate
```

the binary in the client folder is wrong again: 

```
/home/bun/app/hello-prisma # ls -la ./node_modules/.prisma/client/
total 14128
…
-rwxr-xr-x    1 root     bun       14330376 Mar  4 14:16 libquery_engine-linux-musl-arm64-openssl-3.0.x.so.node
…
```

**Comment by Jolg42** [comment]
Thanks for trying this @marvinruder 🙌🏼 

It looks like you should actually use `linux-musl-arm64-openssl-3.0.x` for `musl` (Alpine)
So,
```sh
rm -rf ./node_modules
PRISMA_CLI_BINARY_TARGETS=linux-musl-arm64-openssl-3.0.x npm install
```

For the client this is expected, you will need to add a property in your generator block of your Prisma schema for setting the "binaryTarget" for it.

See https://www.prisma.io/docs/orm/prisma-schema/overview/generators#binary-targets
Like
```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["linux-musl-arm64-openssl-3.0.x"]
}
```


I think this should work in your case.

**Comment by marvinruder** [comment]
> It looks like you should actually use `linux-musl-arm64-openssl-3.0.x` for `musl` (Alpine)

`linux-musl-arm64-openssl-3.0.x` is used by default, as Alpine usually ships with `musl`. However, I am working in an environment (Bun) where I need my C library to be `glibc`, so I have that installed inside my container instead of `musl`. Right now I am unable to tell Prisma in all cases that a non-`musl` library is to be used. `PRISMA_CLI_BINARY_TARGETS` looks like the right way to go (thanks for pointing that option out), but apparently it is not respected in some cases (i.e. copying the correct binary to `./node_modules/.prisma/client/`, running `prisma -v`).

**Comment by janpio** [comment]
(The `PRISMA_CLI_BINARY_TARGETS` environment variable really only influences the Prisma CLI, not Prisma Client. For Prisma Client you indeed need to set `binaryTargets` in your Prisma schema - that explains the behavior you have been seeing.)

**Comment by ludralph** [comment]
Hi @marvinruder 

It looks like this was fixed on Bun's side. See this [issue](https://github.com/oven-sh/bun/issues/918). I could successfully use this Bun Alpine [image](https://hub.docker.com/layers/oven/bun/alpine/images/sha256-c7eb7bbc10efd87449decba4ac4527b167b7be0fc881135a7b3675add7ecd945).

**Comment by jkomyno** [comment]
Closing this as solved by Bun.
