### ISSUE TITLE
db.obj.create() Works in Development But Not When Deployed

### ISSUE THREAD

**Issue by lynixiox** [prisma/prisma#23368]
### Discussed in https://github.com/prisma/prisma/discussions/23361

<div type='discussions-op-text'>

<sup>Originally posted by **lynixiox** March  5, 2024</sup>
### Question

I am trying to create a voting object in the database. The object creates just fine in development but not when deployed. I have some logs . In development it logs before and after the completion. In deployment it logs only before.It does catch and logs the following in deployment 
```
PrismaClientInitializationError: Invalid prisma.vote.create() invocation:
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 5)
    at _n.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:7154)
    at _n.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6188)
    at _n.request (/var/task/node_modules/@prisma/client/runtime/library.js:123:5896)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:128:10871)
    at async a (/var/task/.next/server/app/competition/contestant/[id]/page.js:1:12755) {
  clientVersion: '5.10.2',
  errorCode: undefined
}
```

There are no hoops or any different configs from my development to my deployment and I am able to successfully create other objects in the deployment. Am I missing a config somewhere?

### Information about Prisma Schema, Client Queries and Environment 

Prisma schema
```prisma
model Bundle {
  id String @id @default(cuid())
  bundleId String
  totalValue String
  pricePerVote String
  competition Competition @relation(fields: [bundleId], references: [id], onDelete: Cascade)
  vote Vote[] 
  @@index([bundleId])
  @@unique([id])
}

model Contestant{
  id String @id @default(cuid())
  contestantId String 
  name String
  age String
  votes Vote[]
  competition Competition @relation(fields: [contestantId], references: [id], onDelete: Cascade)
  @@index([contestantId])
  @@unique([id])
}

model Vote{
  id String @id @default(cuid())
  voteId String
  contestantId String
  voterName String
  amountOFVotes Int
  bundle Bundle @relation(fields: [voteId], references: [id], onDelete: Cascade) 
  contestant Contestant @relation(fields: [contestantId], references: [id], onDelete: Cascade)
  @@index([contestantId])
  @@index([voteId])
  @@unique([id])
}

```

Action vote.ts
```ts
import { ContestantDef } from "@/lib/definitions"
import { Bundle } from "@prisma/client"

export const createVote = async({
    amountOFVotes, 
    voterName, 
    bundle, 
    contestant }:{
        amountOFVotes: number
        voterName: string
        bundle: Bundle,
        contestant: ContestantDef
    }) => {
    try{
        console.log("creating vote, ", amountOFVotes)

        await db.vote.create({
            data: {
                amountOFVotes,
                voterName,
                bundle: {
                    connect: {id: bundle.id}
                },
                contestant:{
                    connect: {id: contestant!.id}
                }
            }
        })

        console.log("Finished Creating Vote")

    }catch(error){
        console.log(error)
    }

}
```
ContestantDef
```ts
export type ContestantDef = Prisma.PromiseReturnType<typeof getContestantByid>  
```

package.json
```js
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "postinstall": "prisma generate"
  },
```

Payload
```ts
"use server"

import { ContestantDef } from "@/lib/definitions"
import { createVote } from "./vote"
import { Bundle } from "@prisma/client"

export const verify = async({amountOFVotes, voterName, bundle, contestant}:
  {
    amountOFVotes: number,
    voterName : string,
    bundle: Bundle,
    contestant:ContestantDef
  }) => {
  createVote({amountOFVotes: amountOFVotes,
    voterName: voterName,
    bundle: bundle!,
    contestant: contestant
  })
}
```
- OS: Manjaro
- Database: PlaneScale
- Node.js version: v-20.10.0
- Prisma version: 5.10.2
</div>

**Comment by janpio** [comment]
There is an ongoing discussion here: https://github.com/prisma/prisma/discussions/23361
Please stop creating an issue for this.
