### ISSUE TITLE
Cloudflare Wrangler failing to bundle engine .wasm for driverAdapters early access

### ISSUE THREAD

**Issue by vladinator1000** [prisma/prisma#23457]
### Bug description

This error appears when trying to bundle a Cloudflare Worker.
```
ENOENT: no such file or directory, open '/home/vlady/code/prisma-hyperdrive/node_modules/.prisma/client/query_engine_bg.wasm?module' [plugin wrangler-module-collector]

    node_modules/esbuild/lib/main.js:1360:21:
      1360 │         let result = await callback({
           ╵                      ^

    at async open (node:internal/fs/promises:633:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async /home/vlady/code/prisma-hyperdrive/node_modules/wrangler/wrangler-dist/cli.js:125081:37
    at async requestCallbacks.on-resolve (/home/vlady/code/prisma-hyperdrive/node_modules/esbuild/lib/main.js:1360:22)
    at async handleRequest (/home/vlady/code/prisma-hyperdrive/node_modules/esbuild/lib/main.js:723:13)

  This error came from the "onResolve" callback registered here:

    node_modules/wrangler/wrangler-dist/cli.js:125030:19:
      125030 │             build5.onResolve(
             ╵                    ~~~~~~~~~

    at /home/vlady/code/prisma-hyperdrive/node_modules/wrangler/wrangler-dist/cli.js:125030:20
    at Array.forEach (<anonymous>)
    at /home/vlady/code/prisma-hyperdrive/node_modules/wrangler/wrangler-dist/cli.js:125029:22
    at Array.forEach (<anonymous>)
    at setup (/home/vlady/code/prisma-hyperdrive/node_modules/wrangler/wrangler-dist/cli.js:125025:28)
    at handlePlugins (/home/vlady/code/prisma-hyperdrive/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/home/vlady/code/prisma-hyperdrive/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/home/vlady/code/prisma-hyperdrive/node_modules/esbuild/lib/main.js:776:5)
    at /home/vlady/code/prisma-hyperdrive/node_modules/esbuild/lib/main.js:2163:15

  The plugin "wrangler-module-collector" was triggered by this import

    node_modules/.prisma/client/wasm.js:168:31:
      168 │           return (await import(`./query_engine_bg.wasm${'?module'...
```

I don't understand why Wrangler freaks out because the file is definitely there
![image](https://github.com/prisma/prisma/assets/1226564/b0c6198b-2a6f-4bc5-9dee-d2ea098a96f0)

### How to reproduce

1. Clone this reproduction repo https://github.com/vladinator1000/prisma-hyperdrive/tree/no-such-file-engine-error
2. `npm install`
3. `npm run gen`
4. `npm run build`

Github action run where the error happens: https://github.com/vladinator1000/prisma-hyperdrive/actions/runs/8252989060/job/22573802592#step:6:58

### Expected behavior

Wrangler builds Prisma successfully.

### Environment & setup

- OS: Ubuntu
- Database: N/A
- Node.js version: v21

### Prisma Version

```
	"dependencies": {
		"@prisma/adapter-pg": "5.11.0-dev.5",
		"@prisma/client": "5.11.0-dev.5"
	},
	"devDependencies": {
		"@cloudflare/workers-types": "^4.20240312.0",
		"@types/pg": "^8.11.2",
		"prisma": "5.11.0-dev.5",
		"typescript": "^5.0.4",
		"wrangler": "^3.0.0"
	}
```

**Comment by vladinator1000** [comment]
@Jolg42 It looks like this might be a Wrangler issue. The error went away after removing the `--minify` flag on the build command https://github.com/vladinator1000/prisma-hyperdrive/pull/1

I'll try the same flag with `5.11.0` now ❤️

**Comment by vladinator1000** [comment]
@Jolg42 Updating to `5.11.0` worked with `wrangler deploy --dry-run --outdir dist --minify` 🎉 Thank you!
https://github.com/vladinator1000/prisma-hyperdrive/pull/1
