### ISSUE TITLE
PANIC: internal error: entered unreachable code

### ISSUE THREAD

**Issue by Dark-Developer93** [prisma/prisma#23473]
### Bug description

When I'm trying to fetch all the users from the Azure SQL DB it gives me the above error. I have check the `npx prisma studio` and it's working and I can see and interact with my database records

### How to reproduce

1. `npx prisma generate` for your Azure SQL DB
2.  `yarn dev` to run the Nextjs server and navigate to your page that do the fetching
3. The error will be shown

### Expected behavior

The expected behavior is that I can see all my user's entries in the database.

### Prisma information

```prisma
// Add your schema.prisma

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema
// https://www.prisma.io/docs/orm/prisma-migrate/workflows/troubleshooting

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}

model User {
  id        String @id @default(cuid()) //@db.UniqueIdentifier
  firstName String @db.VarChar(255)
  lastName  String @db.VarChar(255)
  email     String @unique
  username  String @unique
  createdAt DateTime @default(now())
  points    Int      @default(0)
  image     String?
  color     String?

  // Relations
  leaderboardEntries LeaderboardEntry[]
}

model LeaderboardEntry {
  id          String @id @default(cuid()) //@db.UniqueIdentifier
  userId      String
  username    String
  totalPoints Int

  // Relations
  user User @relation(fields: [userId], references: [id])
}
```

```ts
// Add your code using Prisma Client

import prisma from "@/lib/prisma";

export async function getAllUsers() {
  try {
    const users = await prisma.user.findMany({
      orderBy: {
        points: "desc",
      },
    });
    return [...users];
  } catch (error) {
    console.error(`Error fetching users: ${error}`);
    throw new Error(`Internal Server Error fetching users: ${error}`);
  }
}

```

### Environment & setup

- OS:  Windows 11
- Database:  Azure SQL
- Node.js version:  v18.18.0

### Prisma Version

```
5.10.2
```

**Comment by janpio** [comment]
@Dark-Developer93 What can we do to reproduce this? Does this depend on the data returned with that query? Can you reproduce this in a new project with a newly setup database?

@dimaboychev Same questions for you - what exactly is happening for you? Also Azure SQL and Prisma Studio works, but a specific query does not?

**Comment by dimaboychev** [comment]
@janpio I'm still trying to understand what exactly is happening. I have a nextjs server action that reads a csv file and creates and/or updates records in a table. It works fine until it doesn't. Once this "PANIC: internal error" happens, it will keep happening all the time when it reaches "await prisma.user.fineUnique" (or any prisma.[table].find* command) line in my code (before attempting to write anything to the database).

The app, however, works fine... which is strange because there are other places in code where await prisma.user.fineUnique is called.

Not sure if this has to do with open connections not being handled properly

**Comment by janpio** [comment]
Thanks for digging in. Can you check if this is reproducible with this code outside of your normal app? If you can get it to crash reliably, that would be amazing for us.

**Comment by ibarkett** [comment]
Was able to replicate the issue with the same azure managed sql database (sql server version seems to be 12.0.2000.8).

I dropped all the tables like so:
```
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[user]') AND type in (N'U'))
DROP TABLE [dbo].[user]
GO
```

Then ran npx prisma db push -- all good. Accessed an API endpoint (Next 14.1.0) that calls prisma.user.<anything> and I'm getting the 
```
thread 'tokio-runtime-worker' panicked at libs/user-facing-errors/src/quaint.rs:136:18:
internal error: entered unreachable code
Error creating user: PrismaClientRustPanicError:
Invalid `prisma.user.create()` invocation:


PANIC: internal error: entered unreachable code

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```

Created a test.js file and pasted the same code (prisma.user.<anything>). Ran the file with node "node test.js" and it worked (no panic).

Tried to reproduce the issue on another azure sql server but was not able to, albeit this time the sql database was not set up with geo replication.

**Comment by dimaboychev** [comment]
Was able to replicate the issue with the same azure managed sql database (sql server version seems to be 12.0.2000.8).

I dropped all the tables like so:

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[user]') AND type in (N'U'))
DROP TABLE [dbo].[user]
GO
Then ran npx prisma db push -- all good. Accessed an API endpoint (Next 14.1.0) that calls prisma.user.[anything] and I'm getting the

thread 'tokio-runtime-worker' panicked at libs/user-facing-errors/src/quaint.rs:136:18:
internal error: entered unreachable code
Error creating user: PrismaClientRustPanicError:
Invalid `prisma.user.create()` invocation:


PANIC: internal error: entered unreachable code

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
Created a test.js file and pasted the same code (prisma.user.[anything]). Ran the file with node "node test.js" and it worked (no panic).

Tried to reproduce the issue on another azure sql server but was not able to, albeit this time the sql database was not set up with geo replication.

**Comment by ibarkett** [comment]
```
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v20.13.1           | 
| OS              | debian-openssl-3.0.x|
| Prisma Client   | 5.14.0             |
| Query Engine    | e9771e62de70f79a5e1c604a2d7c8e2a0a874b48|
| Database        | sqlserver          |



## Logs
```
/.env
prisma:client dirname /home/dima/dev/cfp/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /home/dima/dev/cfp/prisma
prisma:client clientVersion 5.14.0
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:get-platform Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
}
prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu")
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3
prisma:get-platform The parsed libssl version is: 3.0.x
prisma:client:engines:resolveEnginePath enginePath /home/dima/dev/cfp/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
prisma:client:libraryEngine library starting
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.14.0"}
prisma:client checkPlatformCaching:postinstall 
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/dima/dev/cfp/.env
prisma:client dirname /home/dima/dev/cfp/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /home/dima/dev/cfp/prisma
prisma:client clientVersion 5.14.0
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:engines:resolveEnginePath enginePath /home/dima/dev/cfp/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
prisma:client:libraryEngine library starting
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.14.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.14.0"}
prisma:client checkPlatformCaching:postinstall 
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/dima/dev/cfp/.env
prisma:client dirname /home/dima/dev/cfp/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /home/dima/dev/cfp/prisma
prisma:client clientVersion 5.14.0
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:engines:resolveEnginePath enginePath /home/dima/dev/cfp/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
prisma:client:libraryEngine library starting
prisma:client:request_handler {"name":"PrismaClientInitializationError","clientVersion":"5.14.0","errorCode":"P1013"}
prisma:client checkPlatformCaching:postinstall 
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/dima/dev/cfp/.env
prisma:client dirname /home/dima/dev/cfp/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /home/dima/dev/cfp/prisma
prisma:client clientVersion 5.14.0
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request,
```

**Comment by dimaboychev** [comment]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v20.13.1           | 
| OS              | debian-openssl-3.0.x|
| Prisma Client   | 5.14.0             |
| Query Engine    | e9771e62de70f79a5e1c604a2d7c8e2a0a874b48|
| Database        | sqlserver          |



## Logs
```
/.env
prisma:client dirname /home/dima/dev/cfp/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /home/dima/dev/cfp/prisma
prisma:client clientVersion 5.14.0
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:get-platform Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "ubuntu"
}
prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu")
prisma:get-platform Found libssl.so file using platform-specific paths: libssl.so.3
prisma:get-platform The parsed libssl version is: 3.0.x
prisma:client:engines:resolveEnginePath enginePath /home/dima/dev/cfp/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
prisma:client:libraryEngine library starting
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.14.0"}
prisma:client checkPlatformCaching:postinstall 
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/dima/dev/cfp/.env
prisma:client dirname /home/dima/dev/cfp/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /home/dima/dev/cfp/prisma
prisma:client clientVersion 5.14.0
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:engines:resolveEnginePath enginePath /home/dima/dev/cfp/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
prisma:client:libraryEngine library starting
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.14.0"}
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.14.0"}
prisma:client checkPlatformCaching:postinstall 
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/dima/dev/cfp/.env
prisma:client dirname /home/dima/dev/cfp/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /home/dima/dev/cfp/prisma
prisma:client clientVersion 5.14.0
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:engines:resolveEnginePath enginePath /home/dima/dev/cfp/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
prisma:client:libraryEngine library starting
prisma:client:request_handler {"name":"PrismaClientInitializationError","clientVersion":"5.14.0","errorCode":"P1013"}
prisma:client checkPlatformCaching:postinstall 
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/dima/dev/cfp/.env
prisma:client dirname /home/dima/dev/cfp/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /home/dima/dev/cfp/prisma
prisma:client clientVersion 5.14.0
prisma:client:libraryEngine internalSetup
prisma:client:libraryEngine sending request,

**Comment by janpio** [comment]
Wait, so the same database once works, and once does not, with no real changes or differences? Do you have any explanation for that? Did you restart that server running the Next.js app - maybe it got into a bad state somehow while the database tables were all deleted?
