### ISSUE TITLE
PostgreSQL data type datetimetz inserts and updates fail via Prisma.

### ISSUE THREAD

**Issue by Darin-O** [prisma/prisma#23508]
### Bug description

Inserts, updates and upserts to a postgreSQL table fail with a Inconsistent Column error.

const upsertedContract = await prisma.contracts.upsert(
Inconsistent column data: Conversion failed: expected a datetime string in column 'contract_start_date', found 2024-03-15 00:00:00-06
    at In.handleRequestError (D:\YouturnHealth\youturn-web-api\node_modules\@prisma\client\runtime\library.js:122:6854)
    at In.handleAndLogRequestError (D:\YouturnHealth\youturn-web-api\node_modules\@prisma\client\runtime\library.js:122:6188)
    at In.request (D:\YouturnHealth\youturn-web-api\node_modules\@prisma\client\runtime\library.js:122:5896)
    at async l (D:\YouturnHealth\youturn-web-api\node_modules\@prisma\client\runtime\library.js:127:10871)
    at async main (D:\YouturnHealth\youturn-web-api\prisma\seeds\dev\seed.ts:220:30) {
  code: 'P2023',
  clientVersion: '5.11.0',
  meta: {
    modelName: 'contracts',
    message: "Conversion failed: expected a datetime string in column 'contract_start_date', found 2024-03-15 00:00:00-06"
  }
}

### How to reproduce

1. Create a table via a prisma schema that includes a column with at DateTime data type and @db.Timestamptz(0) [note the number argument does not matter] like this:
    contract_start_date DateTime? @db.Timestamptz(0)
2. Generate and deploy the schema to the database
3. Create an insert, upsert, or update function to write a datetime value to the table.  You can also use the @updatedAt flag in the schema to have a prisma generated time stamp that will also fail.
4. Run the function.
5 Error: Inconsistent column data.

const upsertedContract = await prisma.contracts.upsert(
Inconsistent column data: Conversion failed: expected a datetime string in column 'contract_start_date', found 2024-03-15 00:00:00-06
    at In.handleRequestError (D:\YouturnHealth\youturn-web-api\node_modules\@prisma\client\runtime\library.js:122:6854)
    at In.handleAndLogRequestError (D:\YouturnHealth\youturn-web-api\node_modules\@prisma\client\runtime\library.js:122:6188)
    at In.request (D:\YouturnHealth\youturn-web-api\node_modules\@prisma\client\runtime\library.js:122:5896)
    at async l (D:\YouturnHealth\youturn-web-api\node_modules\@prisma\client\runtime\library.js:127:10871)
    at async main (D:\YouturnHealth\youturn-web-api\prisma\seeds\dev\seed.ts:220:30) {
  code: 'P2023',
  clientVersion: '5.11.0',
  meta: {
    modelName: 'contracts',
    message: "Conversion failed: expected a datetime string in column 'contract_start_date', found 2024-03-15 00:00:00-06"
  }
}

### Expected behavior

DateTime stamp inserted or updated in the database.

### Prisma information

```prisma model contracts {
  contract_id String @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid
  client_id String? @db.Uuid
  contract_type_name_id String? @db.Uuid
  billing_cycle String? @db.VarChar(255)
  contracts_active Boolean?
  contract_start_date DateTime? @db.Timestamp(0)
  contract_end_date DateTime? @db.Timestamp(0)
  contract_billed_to_id String? @db.Uuid
  parent_billed_percentage Decimal? @db.Decimal
  program_fee Decimal? @db.Decimal
  coaching_rate Decimal? @db.Decimal
  coaching_billed_to_client_id String? @db.Uuid
  coaching_billed_percentage Int?
  calculation_rules String?
  billing_cadence String? @db.VarChar(255)
  setup_fee_billed_to_id String? @db.Uuid
  note String?
  last_modified_by String?
  updated_timestamp DateTime? @db.Timestamptz(6) // @updatedAt()
  daily_flat_fee Decimal? @db.Decimal
  monthly_coaching_fee Decimal? @db.Decimal
  monthly_content_fee Decimal? @db.Decimal
  monthly_flat_fee Decimal? @db.Decimal
  monthly_service_fee Decimal? @db.Decimal
  setup_fee Decimal? @db.Decimal

  fk_assessments_contract assessments_contract[]
  //Billings associated with a contract
  billings billing[]    // fk_billing
  coachingBilledToClient clients? @relation("coachingBilledToClient", fields: [coaching_billed_to_client_id], references: [client_id], onDelete: NoAction, onUpdate: NoAction)  // fk_clients_coaching_billed_to_client_idToclients
  fk_clients_contract_billed_to_idToclients clients? @relation("fk_contracts_contract_billed_to_idToclients", fields: [contract_billed_to_id], references: [client_id], onDelete: NoAction, onUpdate: NoAction)
  fk_clients_contracts_setup_fee_billed_to_idToclients clients? @relation("fk_contracts_setup_fee_billed_to_idToclients", fields: [setup_fee_billed_to_id], references: [client_id], onDelete: NoAction, onUpdate: NoAction)
  //Client 
  client clients? @relation("client", fields: [client_id], references: [client_id], onDelete: NoAction, onUpdate: NoAction)  // fk_contracts_client_idToclients
  fk_contracts_types contracts_types? @relation(fields: [contract_type_name_id], references: [contract_type_name_id], onDelete: NoAction, onUpdate: NoAction)

  participants participants[]

  creator_timezone_offset Int @default(0) @allow("update", false)

  //Everything allowed (no auth policies yet)
  @@allow('all', true)
}

```

```ts
export const contractsSeed: Prisma.contractsCreateInput[] = [
  {
    billing_cycle: 'Client 1',
    contracts_active: true,
    contract_start_date: new Date('2023-09-01'),
    contract_end_date: new Date('2023-09-30T00:00:00.000Z'),
    parent_billed_percentage: '1',
    program_fee: '1',
    coaching_rate: '1',
    coaching_billed_percentage: 1,
    calculation_rules: 'Client 1',
    billing_cadence: 'Client 1',
    note: 'Client 1',
    last_modified_by: 'seed',
    updated_timestamp: '2023-09-30T14:30:00Z',
    daily_flat_fee: '1',
    monthly_coaching_fee: '1',
    monthly_content_fee: '1',
    monthly_flat_fee: '1',
    monthly_service_fee: '1',
    setup_fee: '1',
  },
]

  let uniqueContractsIds: string[] = [];
  i = 0;
  for (const contract of contractsSeed) {
    const foundContract = await prisma.contracts.findFirst({
      where: {
        client_id: uniqueClientIds[i],
        contract_type_name_id: uniqueContractTypeIds[i],
      },
    });
    const contract_id = foundContract?.contract_id ?? blankUUID;

    const upsertedContract = await prisma.contracts.upsert({
      where: {
        contract_id: contract_id,
      },
      update: {
        client_id: uniqueClientIds[i],
        contract_type_name_id: uniqueContractTypeIds[i],
        billing_cycle: contract.billing_cycle,
        contracts_active: contract.contracts_active,
        contract_start_date: contract.contract_start_date,
        contract_end_date: contract.contract_end_date,
        contract_billed_to_id: uniqueClientIds[i],
        parent_billed_percentage: contract.parent_billed_percentage,
        program_fee: contract.program_fee,
        coaching_rate: contract.coaching_rate,
        coaching_billed_to_client_id: uniqueClientIds[i],
        coaching_billed_percentage: contract.coaching_billed_percentage,
        calculation_rules: contract.calculation_rules,
        billing_cadence: contract.billing_cadence,
        setup_fee_billed_to_id: uniqueClientIds[i],
        note: contract.note,
        last_modified_by: contract.last_modified_by,
        updated_timestamp: contract.updated_timestamp,
        daily_flat_fee: contract.daily_flat_fee,
        monthly_coaching_fee: contract.monthly_coaching_fee,
        monthly_content_fee: contract.monthly_content_fee,
        monthly_flat_fee: contract.monthly_flat_fee,
        monthly_service_fee: contract.monthly_service_fee,
        setup_fee: contract.setup_fee,
      },
      create: {
        client_id: uniqueClientIds[i],
        contract_type_name_id: uniqueContractTypeIds[i],
        billing_cycle: contract.billing_cycle,
        contracts_active: contract.contracts_active,
        contract_start_date: contract.contract_start_date,
        contract_end_date: contract.contract_end_date,
        contract_billed_to_id: uniqueClientIds[i],
        parent_billed_percentage: contract.parent_billed_percentage,
        program_fee: contract.program_fee,
        coaching_rate: contract.coaching_rate,
        coaching_billed_to_client_id: uniqueClientIds[i],
        coaching_billed_percentage: contract.coaching_billed_percentage,
        calculation_rules: contract.calculation_rules,
        billing_cadence: contract.billing_cadence,
        setup_fee_billed_to_id: uniqueClientIds[i],
        note: contract.note,
        last_modified_by: contract.last_modified_by,
        updated_timestamp: contract.updated_timestamp,
        daily_flat_fee: contract.daily_flat_fee,
        monthly_coaching_fee: contract.monthly_coaching_fee,
        monthly_content_fee: contract.monthly_content_fee,
        monthly_flat_fee: contract.monthly_flat_fee,
        monthly_service_fee: contract.monthly_service_fee,
        setup_fee: contract.setup_fee,
      },
    });
    if (upsertedContract?.contract_id) {
      uniqueContractsIds.push(upsertedContract.contract_id);
    }

```

### Environment & setup

- OS: Windows
- Database: PostgreSQL 16
- Node.js version: v20.8.1

### Prisma Version

```
 "@prisma/client": "^5.11.0",
"prisma": "^5.11.0",
```

**Comment by SevInf** [comment]
Hi @Darin-O.
Prisma dates are supposed to be valid ISO8601 dates, even when native DB accepts other formats. Try `2024-03-15T00:00:00-06:00` for your case.
