### ISSUE TITLE
Custom path does not work with vite

### ISSUE THREAD

**Issue by fredericrous** [prisma/prisma#23507]
### Bug description

here is the error message I'm getting

```console
✘ [ERROR] Could not resolve ".prisma/client/index-browser"

    ../../node_modules/.pnpm/@prisma+client@5.10.2_prisma@5.10.2/node_modules/@prisma/client/index-browser.js:1:23:
      1 │ const prisma = require('.prisma/client/index-browser')
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path ".prisma/client/index-browser" as external to exclude it from the bundle,
  which will remove this error and leave the unresolved path in the bundle. You can also surround
  this "require" call with a try/catch block to handle this failure at run-time instead of
  bundle-time.

9:32:51 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
../../node_modules/.pnpm/@prisma+client@5.10.2_prisma@5.10.2/node_modules/@prisma/client/index-browser.js:1:23: ERROR: Could not resolve ".prisma/client/index-browser"
    at failureErrorWithLog (/myproject/node_modules/.pnpm/esbuild@0.19.11/node_modules/esbuild/lib/main.js:1651:15)
    at /myproject/node_modules/.pnpm/esbuild@0.19.11/node_modules/esbuild/lib/main.js:1059:25
    at /myproject/node_modules/.pnpm/esbuild@0.19.11/node_modules/esbuild/lib/main.js:1527:9
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### How to reproduce

use any schema with a custom path in your generator client as shown in section `Prisma information`
import the PrismaClient, use it as normal

example of import

```ts
import { PrismaClient } from '@prisma-app/client'
```

### Expected behavior

I'm expecting no error in vite or official guidance in the prisma documentation

as a workaround to the error, we can configure vite with the following and the error goes away

```
  // vite.config.ts
  optimizeDeps: {
    exclude: ['.prisma/client']
  },
```

### Prisma information

```prisma
// schema.prisma
generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/@prisma-app/client"
}
```

### Environment & setup

```
macos 12.5
node v21.2.0
```

### Prisma Version

```
5.11.0
```

**Comment by fredericrous** [comment]
I have seen another workaround I haven't tested yet on [the recording of a conference](https://portal.gitnation.org/contents/how-to-solve-real-world-problems-with-remix).
instead of exporting to 

```
"../node_modules/@prisma-app/client"
```

export to

```
"../node_modules/.prisma/client/app"
```

and in your code, import `@prisma/client/app`

maybe that is the way to go and this doesn't have to be fixed but only documented on https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/generating-prisma-client

**Comment by gregpalaci** [comment]
Need to run "prisma generate"

**Comment by fredericrous** [comment]
yes, this is the second step of the “How to reproduce”

**Comment by gregpalaci** [comment]
Sorry!

**Comment by andvalsol** [comment]
I'm having this same error, has there been any progress?

**Comment by fredericrous** [comment]
Prisma has 2.8k issues, this bug I guess is very low priority because as much as it is annoying, there is a workaround. All we can do is add a thumbs up to show it matters to us
