### ISSUE TITLE
After Prisma Engine panic all future requests fail

### ISSUE THREAD

**Issue by squirly** [prisma/prisma#2366]
## Bug description

After Prisma Engine panic all future requests fail.

## How to reproduce

- Run a query that triggers a panic in `prisma-engine`.
- Issue a second query
- The second query fails because the js client cannot connect to `prisma-engine`

If multiple queries are running simultaneously and one panics, all the running queries show an error with the panic from the one query that caused the panic.

## Expected behavior

Ideally the `prisma-engine` would isolate the panic and continue running without effect other requests.
The `prisma-engine` instance should be restarted by the js client when it shuts down.

### Server Log
```
PANIC: called `Option::unwrap()` on a `None` value

... REMOVED EXTRA LOGGING ...

2020-05-01T20:40:46.501Z prisma-client Prisma Client call:
2020-05-01T20:40:46.501Z prisma-client prisma.partner.findMany({
  where: {
    pwsBaseUrl,
  }
})
2020-05-01T20:40:46.501Z prisma-client Generated request:
2020-05-01T20:40:46.501Z prisma-client query {
  findManyPartner(where: {
    pwsBaseUrl: "<URL>"
  }) {
    id
  }
}

2020-05-01T20:40:46.505Z engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:46591
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 46591
  }
}
2020-05-01T20:40:46.506Z printStack callsite Error
    at Object.s [as Partner] (/app/src/dbClient/runtime/index.js:1:82529)
    at Object.n.<computed> [as findMany] (/app/src/dbClient/runtime/index.js:1:84025)
    at Object.grantsFromToken (/app/src/auth/token.js:50:39)
    at Object.fromRequest (/app/src/graphql/context.js:35:45)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Environment & setup

- OS: Debian on Docker
- Database: PostgreSQL
- Prisma version: `2.0.0-beta.4`
- Node.js version: 12.16.1

**Comment by squirly** [comment]
Duplicate of #2100
