### ISSUE TITLE
Using `@ignore` on a field that is `(@)@unique` shouldn't be allowed but leads to runtime errors

### ISSUE THREAD

**Issue by Druue** [prisma/prisma#23726]
We should have some kind of validation error to prevent this

---

From `4.11.0` and onwards [...]. I can't immediately see what happened here however there was work done around dmmf and schema validation [that] release too. However, as the field `uuid` is marked with `@ignore`, errors will still show up on create

```ts
> ts-node index.ts

prisma:query BEGIN
prisma:query INSERT INTO "public"."A" ("yes") VALUES ($1) RETURNING "public"."A"."uuid", "public"."A"."yes"
prisma:query ROLLBACK
PrismaClientKnownRequestError: 
Invalid `prisma.a.create()` invocation in
/src/prisma_debug/index.ts:20:18

  17 }
  18 
  19 const populate = async () => {
→ 20   await prisma.a.create(
Null constraint violation on the fields: (`uuid`)
    at Zr.handleRequestError (/src/prisma_debug/node_modules/@prisma/client/runtime/library.js:171:6414)
    at Zr.handleAndLogRequestError (/src/prisma_debug/node_modules/@prisma/client/runtime/library.js:171:5948)
    at Zr.request (/src/prisma_debug/node_modules/@prisma/client/runtime/library.js:171:5786)
    at async t._request (/src/prisma_debug/node_modules/@prisma/client/runtime/library.js:174:10455) {
  code: 'P2011',
  clientVersion: '4.11.0',
  meta: { constraint: [ 'uuid' ] }
}
```

---

Schema:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model A {
  uuid String @ignore @db.Uuid
  yes  String @db.Uuid

  @@unique([uuid, yes])
}
```

TS Code Used:
```ts
const prisma = new PrismaClient({
  log: ["query"],
});

function uuidv4() {
  return "10000000-1000-4000-8000-100000000000";
}

const populate = async () => {
  await prisma.a.create({
    data: {
      yes: uuidv4(),
    },
  });
};

async function test() {
  const a = await prisma.a.findFirst();
  console.log(a);
}

async function main() {
  await populate();
  return test();
}
```

_Originally posted by @Druue in https://github.com/prisma/prisma/issues/17332#issuecomment-2031859146_

**Comment by jkomyno** [comment]
Closing in favor of https://github.com/prisma/prisma/issues/25290.
