### ISSUE TITLE
Postgres `Oid` fails with `relationJoins`

### ISSUE THREAD

**Issue by Weakky** [prisma/prisma#23816]
I just ran into this issue as well, when using `@db.Oid` as a foreign key with `relationJoins` enabled.

It works as expected with `relationJoins` disabled.

```schema.prisma
datasource db {
  provider = "postgresql"
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["relationJoins"]
}

model File {
  oid    Int @id @db.Oid
  files  UserFile[]
}

model UserFile {
  id        String @id @default(cuid())
  fileOid   Int @db.Oid
  file      File @relation(fields: [fileOid], references: [oid], onDelete: Cascade)
}
```

```typescript
const results = await prisma.userFile.findMany({
  include: {
    file: true,
  },
});

```

```
PrismaClientKnownRequestError: 
Invalid `prisma.userFile.findMany()` invocation in
../script.ts:17:60

  14 import { prisma } from "@/lib/prisma";
  15 
  16 async function main(_args: string[]) {
→ 17   const results = await prisma.userFile.findMany(
Inconsistent column data: Unexpected conversion failure for field File.oid from String(65586) to Int.
    at In.handleRequestError (../node_modules/@prisma/client/runtime/library.js:122:6854)
    at In.handleAndLogRequestError (../node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (../node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (../node_modules/@prisma/client/runtime/library.js:127:10871)
    at async main (../script.ts:17:60) {
  code: 'P2023',
  clientVersion: '5.11.0',
  meta: {
    modelName: 'FhirResourceIngestFile',
    message: 'Unexpected conversion failure for field StudyFile.oid from String(65586) to Int.'
  }
}
```

_Originally posted by @jgnieuwhof in https://github.com/prisma/prisma/issues/23262#issuecomment-1998045146_

**Comment by jgnieuwhof** [comment]
Just cleaning my inbox, this slipped past me.

Thank you for the fix!
