### ISSUE TITLE
internal error: entered unreachable code in end-to-end playwright tests run over sqlite database

### ISSUE THREAD

**Issue by voieducode** [prisma/prisma#23819]
### Bug description

A set of end-to-end tests written with playwright and using prisma over a sqlite database fail with this kind of error message:
```sh
[WebServer] GET /users/h3_lue_ruecker/notes/cluu8oa3p000j94gq6jhzofyw/edit?_data=root 200 - - 8.095 ms
thread 'tokio-runtime-worker' panicked at libs/user-facing-errors/src/quaint.rs:167:18:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
prisma:query - [31m5208ms[39m - DELETE FROM `main`.`User` WHERE `main`.`User`.`id` = ?
[31mprisma:error[39m 
Invalid `prisma.user.deleteMany()` invocation:


internal error: entered unreachable code

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v21.6.1++++++++++++%7C+%0A%7C+OS++++++++++++++%7C+darwin-arm64+++++++%7C%0A%7C+Prisma+Client+++%7C+5.12.0+++++++++++++%7C%0A%7C+Query+Engine++++%7C+473ed3124229e22d881cb7addf559799debae1ab%7C%0A%7C+Database++++++++%7C+sqlite+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aprisma%3AtryLoadEnv+Environment+variables+not+found+at+null%0Aprisma%3AtryLoadEnv+Environment+variables+loaded+from+%2FUsers%2Ffoobar%2FWork%2Fepic-stack%2F.env%0Aprisma%3Aclient+checkPlatformCaching%3Apostinstall+false%0Aprisma%3Aclient+checkPlatformCaching%3AciName+%0Aprisma%3AtryLoadEnv+Environment+variables+not+found+at+null%0Aprisma%3AtryLoadEnv+Environment+variables+loaded+from+%2FUsers%2Ffoobar%2FWork%2Fepic-stack%2F.env%0Aprisma%3Aclient+dirname+%2FUsers%2Ffoobar%2FWork%2Fepic-stack%2Fnode_modules%2F.prisma%2Fclient%0Aprisma%3Aclient+relativePath+..%2F..%2F..%2Fprisma%0Aprisma%3Aclient+cwd+%2FUsers%2Ffoobar%2FWork%2Fepic-stack%2Fprisma%0Aprisma%3Aclient+clientVersion+5.12.0%0Aprisma%3Aclient%3AlibraryEngine+internalSetup%0Aprisma%3Aclient%3Aengines%3AresolveEnginePath+enginePath+%2FUsers%2Ffoobar%2FWork%2Fepic-stack%2Fnode_modules%2F.prisma%2Fclient%2Flibquery_engine-darwin-arm64.dylib.node%0Aprisma%3Aclient%3AlibraryEngine+library+starting%0Aprisma%3Aclient%3AlibraryEngine+library+started%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3Atrue%7D%7D%7D%0A%60%60%60%0A&title=internal+error%3A+entered+unreachable+code&template=bug_report.yml

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 
```

Attaching full log of the failing `npm run validate` run
[prisma-bug.log](https://github.com/prisma/prisma/files/14937266/prisma-bug.log)

### How to reproduce

1. Clone the code in this repository: https://github.com/epicweb-dev/epic-stack.git
2.  Copy `.env.example` into `.env`
3.  Run `npm install && npm run setup -s` to install dependencies and run
    validation
4. Run `npm run validate` 2-3 time until it fails (it could fail a little bit earlier or later than that)

### Expected behavior

There should be no prisma internal error.

### Prisma information

```prisma
// Add your schema.prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id       String  @id @default(cuid())
  email    String  @unique
  username String  @unique
  name     String?

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  image       UserImage?
  password    Password?
  notes       Note[]
  roles       Role[]
  sessions    Session[]
  connections Connection[]
}

model Note {
  id      String @id @default(cuid())
  title   String
  content String

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  owner   User   @relation(fields: [ownerId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  ownerId String

  images NoteImage[]

  // non-unique foreign key
  @@index([ownerId])
  // This helps our order by in the user search a LOT
  @@index([ownerId, updatedAt])
}

model NoteImage {
  id          String  @id @default(cuid())
  altText     String?
  contentType String
  blob        Bytes

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  note   Note   @relation(fields: [noteId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  noteId String

  // non-unique foreign key
  @@index([noteId])
}

model UserImage {
  id          String  @id @default(cuid())
  altText     String?
  contentType String
  blob        Bytes

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  userId String @unique
}

model Password {
  hash String

  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  userId String @unique
}

model Session {
  id             String   @id @default(cuid())
  expirationDate DateTime

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  userId String

  // non-unique foreign key
  @@index([userId])
}

model Permission {
  id          String @id @default(cuid())
  action      String // e.g. create, read, update, delete
  entity      String // e.g. note, user, etc.
  access      String // e.g. own or any
  description String @default("")

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  roles Role[]

  @@unique([action, entity, access])
}

model Role {
  id          String @id @default(cuid())
  name        String @unique
  description String @default("")

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  users       User[]
  permissions Permission[]
}

model Verification {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())

  /// The type of verification, e.g. "email" or "phone"
  type String

  /// The thing we're trying to verify, e.g. a user's email or phone number
  target String

  /// The secret key used to generate the otp
  secret String

  /// The algorithm used to generate the otp
  algorithm String

  /// The number of digits in the otp
  digits Int

  /// The number of seconds the otp is valid for
  period Int

  /// The valid characters for the otp
  charSet String

  /// When it's safe to delete this verification
  expiresAt DateTime?

  @@unique([target, type])
}

model Connection {
  id           String @id @default(cuid())
  providerName String
  providerId   String

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade, onUpdate: Cascade)
  userId String

  @@unique([providerName, providerId])
}

```

Check the code in this repository: https://github.com/epicweb-dev/epic-stack.git, but here is an example of code that fails (https://github.com/epicweb-dev/epic-stack/blob/d663177944e97f2705ec69482d3cc3c56865b2c8/app/routes/users%2B/%24username_%2B/__note-editor.server.tsx#L97):
```ts
	const {
		id: noteId,
		title,
		content,
		imageUpdates = [],
		newImages = [],
	} = submission.value

	const updatedNote = await prisma.note.upsert({
		select: { id: true, owner: { select: { username: true } } },
		where: { id: noteId ?? '__new_note__' },
		create: {
			ownerId: userId,
			title,
			content,
			images: { create: newImages },
		},
		update: {
			title,
			content,
			images: {
				deleteMany: { id: { notIn: imageUpdates.map(i => i.id) } },
				updateMany: imageUpdates.map(updates => ({
					where: { id: updates.id },
					data: { ...updates, id: updates.blob ? cuid() : updates.id },
				})),
				create: newImages,
			},
		},
	})
```

### Environment & setup

- OS: macOS & Windows
- Database: SQLite
- Node.js version: v21.6.1

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.12.0
@prisma/client          : 5.12.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v21.6.1
Query Engine (Node-API) : libquery-engine 473ed3124229e22d881cb7addf559799debae1ab (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 473ed3124229e22d881cb7addf559799debae1ab (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.12.0-21.473ed3124229e22d881cb7addf559799debae1ab
Default Engines Hash    : 473ed3124229e22d881cb7addf559799debae1ab
Studio                  : 0.499.0
```

**Comment by mhuttner** [comment]
I ran into a similar problem, enabling WAL mode as described in 
https://github.com/prisma/prisma/issues/10403#issuecomment-1500770484
solved my issue:

**Comment by voieducode** [comment]
> I ran into a similar problem, enabling WAL mode as described in [#10403 (comment)](https://github.com/prisma/prisma/issues/10403#issuecomment-1500770484) solved my issue:

Tried to set WAL mode as described but I still get the problem.

**Comment by georgernstgraf** [comment]
As a workaround you can try to limit the connections from the prisma client to the sqlite file to 1:
```
datasource db {
  provider = "sqlite"
  url      = "file:./sqlite3.db?connection_limit=1"
}
```
This works for me (and does not negatively affect performance) since the code for handling parallelism in sqlite does not get used with this config.

Also make sure there is only one node process accessing the sqlite file, otherwise the same or similar error(s) like this could reappear:

```
thread 'tokio-runtime-worker' panicked at libs/user-facing-errors/src/quaint.rs:178:18:
internal error: entered unreachable code
stack backtrace:
   0:     0x77203dfe5a41 - <unknown>
   1:     0x77203d7febac - <unknown>
... and so forth
```

BTW I was running parallel inserts using Promise.any() and immediately after one got finished adding an new Promise to the array. This works with a seemingly infinite number (I tried up to 2000), but just raising the connection limit to anything above 1 throws this error again.

See my code here in the prisma folder: <https://github.com/georgernstgraf/js-playground>

Thanks to the prisma team for this otherwise really awesome piece of software!

**Comment by arpitdalal** [comment]
I already have `?connection_limit=1` in the `.env` as the database URL comes from there.
```
DATABASE_URL="file:./data.db?connection_limit=1"
```

**Comment by voieducode** [comment]
This has stopped happening for me on prisma 5.17.0+
