### ISSUE TITLE
i hosted three bots for VK on vds with help cron tab, two bots failed, just one work now easy project hehe, i see this stacktrace first in my life lol

### ISSUE THREAD

**Issue by ckieverentineas** [prisma/prisma#23832]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v18.17.0           | 
| OS              | debian-openssl-3.0.x|
| Prisma Client   | 3.13.0             |
| Query Engine    | 0.1.0              |
| Database        | sqlite             |

## Logs
```
equest, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:librar

Logs:
[Magomir Central Bank] --> In a private chat, succes get keyboard is viewed by user 598832292 <-- (11.04.2024, 22:18:00)
[Magomir Central Bank] --> In private chat, invite enter in system is viewed by user 598832292 <-- (11.04.2024, 22:18:05)
[Magomir Central Bank] --> In a private chat, the card is viewed by user 806193350 <-- (11.04.2024, 22:18:48)
[Magomir Central Bank] --> In a private chat, the card is viewed by user 507431478 <-- (11.04.2024, 22:18:56)
[Magomir Central Bank] --> In a private chat, left in shopping is viewed by user 756434895 <-- (11.04.2024, 22:19:12)
[Magomir Central Bank] --> In a private chat, enter in shopping is viewed by user 756434895 <-- (11.04.2024, 22:19:16)
[Magomir Central Bank] --> In a private chat, the card is viewed by user 756434895 <-- (11.04.2024, 22:19:32)
[Magomir Central Bank] --> In database, created new person GUID 20 UID 54 by user 507431478 <-- (11.04.2024, 22:19:48)
[Magomir Central Bank] --> In a private chat, succes get keyboard is viewed by user 507431478 <-- (11.04.2024, 22:19:50)
[Magomir Central Bank] --> In database, created new person GUID 16 UID 55 by user 756434895 <-- (11.04.2024, 22:20:23)
[Magomir Central Bank] --> In a private chat, succes get keyboard is viewed by user 507431478 <-- (11.04.2024, 22:20:24)
[Magomir Central Bank] --> In a private chat, succes get keyboard is viewed by user 756434895 <-- (11.04.2024, 22:20:30)
[Magomir Central Bank] --> In private chat, invite enter in system is viewed by user 507431478 <-- (11.04.2024, 22:20:33)
[Magomir Central Bank] --> In a private chat, succes get keyboard is viewed by user 756434895 <-- (11.04.2024, 22:20:51)
[Magomir Central Bank] --> In private chat, invite enter in system is viewed by user 756434895 <-- (11.04.2024, 22:20:59)
[Magomir Central Bank] --> In a private chat, enter in shopping is viewed by user 756434895 <-- (11.04.2024, 22:21:40)
[Magomir Central Bank] --> In a private chat, the card is viewed by user 507431478 <-- (11.04.2024, 22:22:21)
[Magomir Central Bank] --> In a private chat, open shop Артефакты и реликвии is viewed by user 756434895 <-- (11.04.2024, 22:23:00)
[Magomir Central Bank] --> In a private chat, opened 733772863 card UID 26 is viewed by admin 733772863 <-- (11.04.2024, 22:23:04)
[Magomir Central Bank] --> In database, created new person GUID 20 UID 56 by user 507431478 <-- (11.04.2024, 22:23:16)
[Magomir Central Bank] --> In a private chat, succes get keyboard is viewed by user 507431478 <-- (11.04.2024, 22:23:20)
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', query-engine/core/src/query_document/parser.rs:250:87
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PrismaClientUnknownRequestError:
Invalid `prisma.user.update()` invocation in
PrismaClientUnknownRequestError:
Invalid `prisma.user.update()` invocation in
/home/min-magic-vk-bank/src/engine/player.ts:1336:49

  1333 const count: number = await Ipnut_Gold()
  1334 const messa: string = await Ipnut_Message()
  1335 const user_get: any = await prisma.user.findFirst({ where: { id } })
→ 1336 const money_put = await prisma.user.update(
  called `Option::unwrap()` on a `None` value
    at Object.request (/home/min-magic-vk-bank/node_modules/@prisma/client/runtime/index.js:45633:15)
    at async PrismaClient._request (/home/min-magic-vk-bank/node_modules/@prisma/client/runtime/index.js:46456:18)
    at async Object.Medal_Up (/home/min-magic-vk-bank/src/engine/player.ts:1336:31)
    at async /home/min-magic-vk-bank/src/engine/player.ts:688:31
    at async /home/min-magic-vk-bank/node_modules/vk-io-question/lib/index.js:92:13
    at async /home/min-magic-vk-bank/node_modules/middleware-io/lib/index.js:280:9 {
  clientVersion: '3.13.0'
}
PrismaClientRustPanicError:
Invalid `prisma.account.findFirst()` invocation:


  PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node+++++++
https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v18.17.0+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-3.0.x%7C%0A%7C+Prisma+Client+++%7C+3.13.0+++++++++++++%7C%0A%7C+Query+Engine++++%7C+0.1.0++++++++++++++%7C%0A%7C+Database++++++++%7C+sqlite+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aequest%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3Alibrar
If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

    at Object.request (/home/min-magic-vk-bank/node_modules/@prisma/client/runtime/index.js:45637:15)
    at async PrismaClient._request (/home/min-magic-vk-bank/node_modules/@prisma/client/runtime/index.js:46456:18)
    at async Person_Detector (/home/min-magic-vk-bank/src/engine/core/person.ts:234:21)
    at async /home/min-magic-vk-bank/src/index.ts:118:2
    at async /home/min-magic-vk-bank/node_modules/vk-io-question/lib/index.js:40:17
    at async /home/min-magic-vk-bank/node_modules/middleware-io/lib/index.js:280:9 {
  clientVersion: '3.13.0'
}
PrismaClientRustPanicError:
Invalid `prisma.account.findFirst()` invocation:


  PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v18.17.0+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-3.0.x%7C%0A%7C+Prisma+Client+++%7C+3.13.0+++++++++++++%7C%0A%7C+Query+Engine++++%7C+0.1.0++++++++++++++%7C%0A%7C+Database++++++++%7C+sqlite+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aequest%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+req
https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v18.17.0+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-3.0.x%7C%0A%7C+Prisma+Client+++%7C+3.13.0+++++++++++++%7C%0A%7C+Query+Engine++++%7C+0.1.0++++++++++++++%7C%0A%7C+Database++++++++%7C+sqlite+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aequest%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3Alibrar
If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

    at Object.request (/home/min-magic-vk-bank/node_modules/@prisma/client/runtime/index.js:45637:15)
    at async PrismaClient._request (/home/min-magic-vk-bank/node_modules/@prisma/client/runtime/index.js:46456:18)
    at async Person_Detector (/home/min-magic-vk-bank/src/engine/core/person.ts:234:21)
    at async /home/min-magic-vk-bank/src/index.ts:118:2
    at async /home/min-magic-vk-bank/node_modules/vk-io-question/lib/index.js:40:17
    at async /home/min-magic-vk-bank/node_modules/middleware-io/lib/index.js:280:9 {
  clientVersion: '3.13.0'
}
PrismaClientRustPanicError:
Invalid `prisma.account.findFirst()` invocation:


  PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v18.17.0+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+debian-openssl-3.0.x%7C%0A%7C+Prisma+Client+++%7C+3.13.0+++++++++++++%7C%0A%7C+Query+Engine++++%7C+0.1.0++++++++++++++%7C%0A%7C+Database++++++++%7C+sqlite+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aequest%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0Aprisma%3Aclient%3AlibraryEngine+sending+req
ETC
If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

    at Object.request (/home/min-magic-vk-bank/node_modules/@prisma/client/runtime/index.js:45637:15)
    at async PrismaClient._request (/home/min-magic-vk-bank/node_modules/@prisma/client/runtime/index.js:46456:18)
    at async Person_Detector (/home/min-magic-vk-bank/src/engine/core/person.ts:234:21)
    at async /home/min-magic-vk-bank/src/index.ts:118:2
    at async /home/min-magic-vk-bank/node_modules/vk-io-question/lib/index.js:40:17
    at async /home/min-magic-vk-bank/node_modules/middleware-io/lib/index.js:280:9 {
  clientVersion: '3.13.0'
}
User 93440650 succes get keyboard
User 93440650 succes get keyboard
Init question for user 93440650
User 93440650 got quest
Analyzer module detected quest for user UID 636
User 349013707 ready for new quest
User 349013707 got quest
Analyzer module detected quest for user UID 615
PrismaClientRustPanicError:
Invalid `prisma.user.count()` invocation:


  PANIC: called `Option::unwrap()` on a `None` value in query-engine/core/src/query_document/parser.rs:250:87

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
ETC

**Comment by ckieverentineas** [comment]
soft runnig, but not ask me and other users

**Comment by ckieverentineas** [comment]
scheme prisma:
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Account {
  id          Int           @id @default(autoincrement())
  idvk        Int
  crdate      DateTime      @default(now())
  select_user Int           @default(0)
  User      User[]
}

model User {
  id          Int           @id @default(autoincrement())
  name        String
  class       String
  idvk        Int
  spec        String
  id_alliance Int?
  lvl         Int           @default(0)
  medal      Int           @default(5)
  gold        Int           @default(0)
  xp          Int           @default(0)
  private     Boolean       @default(false)
  crdate      DateTime      @default(now())
  id_role     Int           @default(1)
  role        Role          @relation(fields: [id_role], references: [id], onDelete: Cascade)
  id_account     Int           @default(1)
  account        Account          @relation(fields: [id_account], references: [id], onDelete: Cascade)
  Artefact    Artefact[]
  Inventory   Inventory[]
  Trigger     Trigger[]
  Achievement Achievement[]
  Analyzer    Analyzer[]
}

model BlackBox {
  id   Int @id @default(autoincrement())
  idvk Int @unique
}

model Role {
  id   Int    @id @default(autoincrement())
  name String
  User User[]
}

model Artefact {
  id          Int    @id @default(autoincrement())
  id_user     Int
  name        String
  label       String
  description String
  type        String
  user        User   @relation(fields: [id_user], references: [id], onDelete: Cascade)
}

model Inventory {
  id      Int  @id @default(autoincrement())
  id_user Int
  id_item Int
  item    Item @relation(fields: [id_item], references: [id], onDelete: Cascade)
  user    User @relation(fields: [id_user], references: [id], onDelete: Cascade)
}

model Item {
  id          Int         @id @default(autoincrement())
  name        String
  description String?
  price       Int
  id_category Int
  type        String
  category    Category    @relation(fields: [id_category], references: [id], onDelete: Cascade)
  Inventory   Inventory[]
}

model Category {
  id   Int    @id @default(autoincrement())
  name String
  Item Item[]
}

model Trigger {
  id      Int      @id @default(autoincrement())
  name    String
  value   Boolean
  user    User     @relation(fields: [id_user], references: [id], onDelete: Cascade, onUpdate: Cascade)
  id_user Int
  crdate  DateTime @default(now())
}

model Achievement {
  id      Int      @id @default(autoincrement())
  name    String
  uid     Int
  user    User     @relation(fields: [id_user], references: [id], onDelete: Cascade, onUpdate: Cascade)
  id_user Int
  crdate  DateTime @default(now())
}

model Analyzer {
  id           Int      @id @default(autoincrement())
  buying       Int      @default(0)
  quest        Int      @default(0)
  underwear    Int      @default(0)
  convert_mo   Int      @default(0)
  beer         Int      @default(0)
  beer_premiun Int      @default(0)
  birthday     Int      @default(0)
  gold_lost    Int      @default(0)
  gold_got     Int      @default(65)
  xp_got       Int      @default(0)
  xp_lost      Int      @default(0)
  user         User     @relation(fields: [id_user], references: [id], onDelete: Cascade, onUpdate: Cascade)
  id_user      Int
  crdate       DateTime @default(now())
}

model Alliance {
  id      Int      @id @default(autoincrement())
  name    String
  idvk  Int
}

**Comment by ckieverentineas** [comment]
index.ts:

import { VK, Keyboard } from 'vk-io';
import { HearManager } from '@vk-io/hear';
import {
    QuestionManager,
    IQuestionMessageContext
} from 'vk-io-question';
import { registerUserRoutes } from './engine/player'
import { InitGameRoutes } from './engine/init';
import { Keyboard_Index, Logger, Worker_Checker } from './engine/core/helper';
import * as dotenv from 'dotenv' // see https://github.com/motdotla/dotenv#how-do-i-use-dotenv-with-import
import prisma from './engine/events/module/prisma_client';
import { Exit, Main_Menu_Init } from './engine/events/contoller';
import { Admin_Enter, Artefact_Enter, Birthday_Enter, Card_Enter, Inventory_Enter, Rank_Enter, Statistics_Enter} from './engine/events/module/info';
import { Operation_Enter, Right_Enter, User_Info } from './engine/events/module/tool';
import { Service_Beer_Open, Service_Beer_Premium_Open, Service_Cancel, Service_Convert_Galleon, Service_Convert_Galleon_Change, Service_Convert_Magic_Experience, Service_Convert_Magic_Experience_Change, Service_Enter, Service_Level_Up, Service_Level_Up_Change, Service_Quest_Open, Service_Underwear_Open } from './engine/events/module/service';
import { Shop_Bought, Shop_Buy, Shop_Cancel, Shop_Category_Enter, Shop_Enter } from './engine/events/module/shop';
import { Person_Detector } from './engine/core/person';
import { Alliance_Control, Alliance_Control_Multi, Alliance_Controller } from './engine/events/module/alliance';
dotenv.config()

export const token: string = String(process.env.token)
export const root: number = Number(process.env.root) //root user
export const chat_id: number = Number(process.env.chat_id) //chat for logs
export const group_id: number = Number(process.env.group_id)//clear chat group
export const timer_text = { answerTimeLimit: 300_000 } // ожидать пять минут
export const timer_text_oper = { answerTimeLimit: 60_000 } // ожидать пять минут
export const answerTimeLimit = 300_000 // ожидать пять минут
export const starting_date = new Date(); // время работы бота
//авторизация
async function Group_Id_Get() {
	const vk = new VK({ token: token, apiLimit: 1 });
	const [group] = await vk.api.groups.getById(vk);
	const groupId = group.id;
	return groupId
}
export const vk = new VK({ token: token, pollingGroupId: Number(Group_Id_Get()), apiLimit: 1 });
//инициализация
const questionManager = new QuestionManager();
const hearManager = new HearManager<IQuestionMessageContext>();

/*prisma.$use(async (params, next) => {
	console.log('This is middleware!')
	// Modify or interrogate params here
	console.log(params)
	return next(params)
})*/

//настройка
vk.updates.use(questionManager.middleware);
vk.updates.on('message_new', hearManager.middleware);

//регистрация роутов из других классов
InitGameRoutes(hearManager)
registerUserRoutes(hearManager)

//миддлевар для предварительной обработки сообщений
vk.updates.on('message_new', async (context: any, next: any) => {
	
	if (context.peerType == 'chat') { 
		try { 
			await vk.api.messages.delete({'peer_id': context.peerId, 'delete_for_all': 1, 'cmids': context.conversationMessageId, 'group_id': group_id})
			await Logger(`In chat received a message from the user ${context.senderId} and was deleted`)
			//await vk.api.messages.send({ peer_id: chat_id, random_id: 0, message: `✅🚫 @id${context.senderId} ${context.text}`})  
		} catch (error) { 
			await Logger(`In chat received a message from the user ${context.senderId} and wasn't deleted`)
			//await vk.api.messages.send({ peer_id: chat_id, random_id: 0, message: `⛔🚫 @id${context.senderId} ${context.text}`}) 
		}  
		return
	}
	//проверяем есть ли пользователь в базах данных
	const user_check = await prisma.account.findFirst({ where: { idvk: context.senderId } })
	//если пользователя нет, то начинаем регистрацию
	if (!user_check) {
		//согласие на обработку
		const answer = await context.question(`⌛ Вы входите в Центробанк Министерства Магии 🏦, из ниоткуда перед вами предстали два орка и произнесли: \n — Министр Магии говорил нам о вас. Но прежде чем продолжить, распишитесь здесь о своем согласии на обработку персональных данных. \n В тот же миг в их руках магическим образом появился пергамент. \n 💡 У вас есть 5 минут на принятие решения!`,
			{	
				keyboard: Keyboard.builder()
				.textButton({ label: '✏', payload: { command: 'Согласиться' }, color: 'positive' }).row()
				.textButton({ label: '👣', payload: { command: 'Отказаться' }, color: 'negative' }).oneTime(),
				answerTimeLimit
			}
		);
		if (answer.isTimeout) { return await context.send(`⏰ Время ожидания подтверждения согласия истекло!`) }
		if (!/да|yes|Согласиться|конечно|✏/i.test(answer.text|| '{}')) {
			await context.send('⌛ Вы отказались дать свое согласие, а живым отсюда никто не уходил, вас упаковали!');
			return;
		}
		//приветствие игрока
		const visit = await context.question(`⌛ Поставив свою подпись, вы, стараясь не смотреть косо на орков, вошли в личный кабинет Центробанка, и увидели домашнего эльфа, наводящего порядок, ужас и страх.`,
			{ 	
				keyboard: Keyboard.builder()
				.textButton({ label: 'Подойти и поздороваться', payload: { command: 'Согласиться' }, color: 'positive' }).row()
				.textButton({ label: 'Ждать, пока эльф закончит', payload: { command: 'Отказаться' }, color: 'negative' }).oneTime().inline(),
				answerTimeLimit
			}
		);
		if (visit.isTimeout) { return await context.send(`⏰ Время ожидания активности истекло!`) }
		const save = await prisma.account.create({	data: {	idvk: context.senderId } })
		const info = await User_Info(context)
		await context.send(`⌛ Эльф отвлекся от дел, заприметив вас, подошел и сказал.\n - Добро пожаловать в мир меча и магии! \n И протянул вам вашу карточку.\n ⚖Вы получили картотеку, ${info.first_name}\n 🕯 GUID: ${save.id}. \n 🎥 idvk: ${save.idvk}\n ⚰ Дата Регистрации: ${save.crdate}\n`)
		await Logger(`In database created new user with uid [${save.id}] and idvk [${context.senderId}]`)
		const check_bbox = await prisma.blackBox.findFirst({ where: { idvk: context.senderId } })
		const ans_selector = `⁉ @id${save.idvk}(${info.first_name}) ${!check_bbox ? "легально" : "НЕЛЕГАЛЬНО"} получает банковскую карту GUID: ${save.id}!`
		await vk.api.messages.send({
			peer_id: chat_id,
			random_id: 0,
			message: ans_selector
		})
		await Person_Detector(context)
		await Keyboard_Index(context, `💡 Подсказка: Когда все операции вы успешно завершили, напишите [!банк] без квадратных скобочек, а затем нажмите кнопку: ✅Подтвердить авторизацию!`)
	} else {
		await Person_Detector(context)
		await Keyboard_Index(context, `⌛ Загрузка, пожалуйста подождите...`)
	}
	return next();
})
vk.updates.on('message_event', async (context: any, next: any) => { 
	await Person_Detector(context)
	const config: any = {
		"system_call": Main_Menu_Init,
		"card_enter": Card_Enter,
		"birthday_enter": Birthday_Enter,
		"exit": Exit,
		"artefact_enter": Artefact_Enter,
		"inventory_enter": Inventory_Enter,
		"admin_enter": Admin_Enter,
		"service_enter": Service_Enter,
		"service_cancel": Service_Cancel,
		"service_convert_galleon": Service_Convert_Galleon,
		"service_convert_galleon_change": Service_Convert_Galleon_Change,
		"service_convert_magic_experience": Service_Convert_Magic_Experience,
		"service_convert_magic_experience_change": Service_Convert_Magic_Experience_Change,
		"service_level_up": Service_Level_Up,
		"service_level_up_change": Service_Level_Up_Change,
		"shop_category_enter": Shop_Category_Enter,
		"shop_enter": Shop_Enter,
		"shop_cancel": Shop_Cancel,
		"shop_bought": Shop_Bought,
		"shop_buy": Shop_Buy,
		"operation_enter": Operation_Enter, // заглушки
		"right_enter": Right_Enter, // заглушки
		"service_beer_open": Service_Beer_Open,
		"service_beer_premium_open": Service_Beer_Premium_Open,
		"service_quest_open": Service_Quest_Open,
		"service_underwear_open": Service_Underwear_Open,
		"statistics_enter": Statistics_Enter,
		"rank_enter": Rank_Enter,
		"alliance_control_multi": Alliance_Control_Multi,
		"alliance_control": Alliance_Control,
		"alliance_controller": Alliance_Controller
	}
	try {
		await config[context.eventPayload.command](context)
	} catch (e) {
		await Logger(`Error event detected for callback buttons: ${e}`)
	}
	return await next();
})

vk.updates.start().then(() => {
	Logger('running succes')
}).catch(console.error);
setInterval(Worker_Checker, 86400000);
process.on('warning', e => console.warn(e.stack))

**Comment by ckieverentineas** [comment]
reloaded server and while all work in normal mode
