### ISSUE TITLE
gitlab ci failed on docker image node:20

### ISSUE THREAD

**Issue by edyrkaj** [prisma/prisma#23885]
### Bug description

ReferenceError: performance is not defined
    at /builds/bitwave/services/data-svc-group/data-svc/node_modules/prisma/build/index.js:1426:423
    at V1.runGenerate (/builds/bitwave/services/data-svc-group/data-svc/node_modules/prisma/build/index.js:1426:130)
    at V1.parse (/builds/bitwave/services/data-svc-group/data-svc/node_modules/prisma/build/index.js:1431:140)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async m5t (/builds/bitwave/services/data-svc-group/data-svc/node_modules/prisma/build/index.js:1981:280)
Start using Prisma Client in Node.js (See: https://pris.ly/d/client)

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by edyrkaj** [comment]
I think you must need to add the import at the top:
const {performance} = require('perf_hooks');

**Comment by Jolg42** [comment]
I find this a bit weird, because I think it should work without an import, since it's a global.
See https://nodejs.org/api/globals.html#performance

You mention this runs in `node:20`? Do you know which version exactly?

**Comment by edyrkaj** [comment]
It's a node service running inside of a docker.

versions used on the docker are: 
node: 20.12.2 
npm: 10.5.2

thnx
