### ISSUE TITLE
Could not figure out an ID in create

### ISSUE THREAD

**Issue by Sonichigo** [prisma/prisma#23907]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v21.6.0            | 
| OS              | linux-arm64-openssl-3.0.x|
| Prisma Client   | 5.12.1             |
| Query Engine    | 473ed3124229e22d881cb7addf559799debae1ab|
| Database        | postgresql         |

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/sonichigi.linux/bun-sql/.env
prisma:client checkPlatformCaching:postinstall false
prisma:client checkPlatformCaching:ciName 
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables loaded from /home/sonichigi.linux/bun-sql/.env
prisma:client dirname /home/sonichigi.linux/bun-sql/node_modules/.prisma/client
prisma:client relativePath ../../../prisma
prisma:client cwd /home/sonichigi.linux/bun-sql/prisma
prisma:client clientVersion 5.12.1
prisma:client:libraryEngine internalSetup
prisma:get-platform Found distro info:
{
  "targetDistro": "debian",
  "familyDistro": "debian",
  "originalDistro": "debian"
}
prisma:get-platform Trying platform-specific paths for "debian" (and "ubuntu")
prisma:get-platform Falling back to "ldconfig" and other generic paths
prisma:get-platform Command "ldconfig -p | sed "s/.*=>s*//" | sed "s|.*/||" | grep libssl | sort | grep -v "libssl.so.0"" successfully returned "libssl.so
libssl.so.3
libssl3.so
"
prisma:get-platform Found libssl.so file using "ldconfig" or other generic paths: libssl.so
libssl.so.3
libssl3.so

prisma:get-platform The parsed libssl version is: 3.0.x
prisma:client:engines:resolveEnginePath enginePath /home/sonichigi.linux/bun-sql/node_modules/.prisma/client/libquery_engine-linux-arm64-openssl-3.0.x.so.node
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:request_handler {"name":"PrismaClientRustPanicError","clientVersion":"5.12.1"}
prisma:client:libraryEngine sending request, this.libraryStarted: true
prisma:client:libraryEngine sending request, this.libraryStarted: true
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":true}}}
```

**Comment by Weakky** [comment]
Hey @Sonichigo ,

Would you mind sharing any additional information so that we can reproduce your issue? Your datamodel and some Prisma Client query that reproduces this bug is capital for us to work on the issue.

Thank you! 🙏

**Comment by Sonichigo** [comment]
hey @Weakky ,

Here's my repo:- https://github.com/darkin424/Blog-Website . 

To reproduce please follow the steps below:-
```bash
1. start the database docker instance
2. install `keploy` with :- https://keploy.io/docs/server/installation/
3. keploy record -c "bun --watch index.ts"
4. make few post api call for creation like `signup`, `create-post`
5. stop the docker instance
6. keploy test -c "bun --watch index.ts"
```

With this you can replicate the  issue

**Comment by Sonichigo** [comment]
@Weakky were you able to replicate the issue ?

**Comment by Weakky** [comment]
Hey @Sonichigo,

Would you mind trying with a newer version of Prisma and confirm whether the bug is still present?

Thank you 🙏

**Comment by Sonichigo** [comment]
The bug is still there but this time i'm able to see the issue as well while running the tests i got :- 

```
🐰 Keploy: 2024-06-06T16:29:18+05:30    INFO    running {"test-set": "test-set-1"}
Server is running on port 4040
🐰 Keploy: 2024-06-06T16:29:23+05:30    INFO    starting test for of    {"test case": "test-1", "test set": "test-set-1"}
thread 'tokio-runtime-worker' panicked at query-engine/connectors/sql-query-connector/src/database/operations/write.rs:194:22:
Could not figure out an ID in create
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Testrun failed for testcase with id: "test-1"
```

So i tried with export RUST_BACKTRACE=full and got the below log:- 

```
thread 'tokio-runtime-worker' panicked at query-engine/connectors/sql-query-connector/src/database/operations/write.rs:194:22:
Could not figure out an ID in create
stack backtrace:
   0:     0xffff62e79450 - <unknown>
   1:     0xffff627db750 - <unknown>
   2:     0xffff62e5afb4 - <unknown>
   3:     0xffff62e7cfc4 - <unknown>
   4:     0xffff62e7c968 - <unknown>
   5:     0xffff62e7d784 - <unknown>
   6:     0xffff62e7d288 - <unknown>
   7:     0xffff62e7d224 - <unknown>
   8:     0xffff62e7d21c - <unknown>
   9:     0xffff626c53f0 - <unknown>
  10:     0xffff62e43914 - <unknown>
  11:     0xffff62e5032c - <unknown>
  12:     0xffff62c80928 - <unknown>
  13:     0xffff62ca35c0 - <unknown>
  14:     0xffff62ca5620 - <unknown>
  15:     0xffff626fd20c - <unknown>
  16:     0xffff626fe734 - <unknown>
  17:     0xffff62717460 - <unknown>
  18:     0xffff62713b04 - <unknown>
  19:     0xffff62704f18 - <unknown>
  20:     0xffff62761b74 - <unknown>
  21:     0xffff6273845c - <unknown>
  22:     0xffff62742ad0 - <unknown>
  23:     0xffff62e92190 - <unknown>
  24:     0xffff62e9bf78 - <unknown>
  25:     0xffff62e902b8 - <unknown>
  26:     0xffff62e8fd1c - <unknown>
  27:     0xffff62e95aac - <unknown>
  28:     0xffff62e7e2e8 - <unknown>
  29:     0xffffaa21ee58 - <unknown>
  30:     0xffffaa287f9c - <unknown>
  31:                0x0 - <unknown>
Testrun failed for testcase with id: "test-1"
```

**Comment by Sonichigo** [comment]
> @Sonichigo A few questions:
> 
> 1. Can you maybe check if the same problem happens when running your code with Node instead of Bun?
> 2. Does this also happen outside the usage of keploy?
> 3. Can you add more logging around your Prisma Client queries so that on crash we know _which_ one triggered the crash?  Right now it seems we only know that _somehow_ and _somewhere_ when using your app a `create` query fails with this crash.

Sure, would need sometime, to change to Node and experiment with others.

**Comment by janpio** [comment]
Context by the way: I could not easily run `keploy` on Gitpod.io, which I usually use for reproductions.

**Comment by Sonichigo** [comment]
> Context by the way: I could not easily run `keploy` on Gitpod.io, which I usually use for reproductions.

Keploy needs root access to be precise the kernel access to listen to system call, which the gitpod doesn't allow, so even if you are using `sudo` you might not get full root access. You can try it with Devcontainers, Codespaces, they have full root access.

**Comment by janpio** [comment]
Codespaces seems to work.

> 4. make few post api call for creation like `signup`, `create-post`

What am I supposed to do in this step of the reproduction though? Can you share some of the calls somehow? curl, Postman, ...

**Comment by Sonichigo** [comment]
> Codespaces seems to work.
> 
> > 4. make few post api call for creation like `signup`, `create-post`
> 
> What am I supposed to do in this step of the reproduction though? Can you share some of the calls somehow? curl, Postman, ...
> 
> > 5. stop the docker instance
> 
> I assume you mean `keploy` here - Docker is running the database that is needed for the tests I assume?

Here are few curl commands :- 

```sh
## Create a User
curl --location 'http://localhost:4040/signup' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name":"Yash",
    "email":"isssalcupnamde@abc.com",
    "password":"1234"
}'

## Login 

curl --location 'http://localhost:4040/login' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email":"isssalcupnamde@abc.com",
    "password":"1234"
}'

## Create a Post
## You can get <TOKEN> from above curl response

curl --location 'http://localhost:4040/create-post' \
--header 'Authorization: Bearer <TOKEN>' \
--header 'Content-Type: application/json' \
--data '{
    "title":"Anime",
    "body":"AOT from quantum"
}'
```

2. I mean the database, since I'm using docker to run the postgresdb. After keploy record command and making curl requests, database instance is not required since the mocks are created.

**Comment by janpio** [comment]
Ok, I can reproduce what you report:

```
🐰 Keploy: 2024-06-06T18:08:12Z         INFO    starting test for of    {"test case": "test-1", "test set": "test-set-6"}
thread 'tokio-runtime-worker' panicked at query-engine/connectors/sql-query-connector/src/database/operations/write.rs:194:22:
Could not figure out an ID in create
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Testrun failed for testcase with id: "test-1"

--------------------------------------------------------------------

+-------------------------------------------------------------------------------------------------------------+
|                                                DIFFS TEST-1                                                 |
+-------------------------------------------------------------------------------------------------------------+
|                     EXPECT HEADER                    |                   ACTUAL HEADER                      |
| -----------------------------------------------------+----------------------------------------------------- |
|                 Content-Length: [216]                |               Content-Length: [2935]                 |
|                                                      |                                                      |
|                                                                                                             |
|                      EXPECT BODY                     |                    ACTUAL BODY                       |
| -----------------------------------------------------+----------------------------------------------------- |
|    {                                                 |  {                                                   |
|   -  "user": {                                       | +  "error": "                                        |
|   -    "createdAt": "2024-06-06T18:06:49.995Z",      | Invalid `prisma.user.create()` invocation in         |
|   -    "email": "isssalcupnamde@abc.com",            | /workspaces/Blog-Website/services/user.service.ts:   |
|   -    "id": 1,                                      | 19:12                                                |
|   -    "name": "Yash",                               |   16 });                                             |
|   -    "password": "$2b$10$sORFubjTUt8Mt2k7vNqt4O3VV |                                                17    |
|   hEWd71mbrad/h.Bm75.lm6CjOj6S",                     |   18 //Create the user                               |
|   -    "updatedAt": "2024-06-06T18:06:49.995Z"       | → 19 const user = await prisma.user.create(          |
|   -  }                                               | Could not figure out an ID in create                 |
|   Invalid `prisma.user.create()` invocation in       | This is a non-recoverable error which probably hap   |
|   /workspaces/Blog-Website/services/user.service.ts: | pens when the Prisma Query Engine has a panic.       |
|   19:12                                              | https://github.com/prisma/prisma/issues/new?body=H   |
|     16 });                                           | i+Prisma+Team%21+My+Prisma+Client+just+crashed.+Th   |
|                                                  17  | is+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Nam   |
```

But using the application itself worked fine, it is only when using these mocks. That is also true for you, correct?

Are you sure this is not a problem in what the Keploy mocks return to Prisma? If that would be incorrect a bit, Prisma would probably not be able to find the ID and throw this error.

**Comment by Sonichigo** [comment]
> Ok, I can reproduce what you report:
> 
> ```
> 🐰 Keploy: 2024-06-06T18:08:12Z         INFO    starting test for of    {"test case": "test-1", "test set": "test-set-6"}
> thread 'tokio-runtime-worker' panicked at query-engine/connectors/sql-query-connector/src/database/operations/write.rs:194:22:
> Could not figure out an ID in create
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Testrun failed for testcase with id: "test-1"
> 
> --------------------------------------------------------------------
> 
> +-------------------------------------------------------------------------------------------------------------+
> |                                                DIFFS TEST-1                                                 |
> +-------------------------------------------------------------------------------------------------------------+
> |                     EXPECT HEADER                    |                   ACTUAL HEADER                      |
> | -----------------------------------------------------+----------------------------------------------------- |
> |                 Content-Length: [216]                |               Content-Length: [2935]                 |
> |                                                      |                                                      |
> |                                                                                                             |
> |                      EXPECT BODY                     |                    ACTUAL BODY                       |
> | -----------------------------------------------------+----------------------------------------------------- |
> |    {                                                 |  {                                                   |
> |   -  "user": {                                       | +  "error": "                                        |
> |   -    "createdAt": "2024-06-06T18:06:49.995Z",      | Invalid `prisma.user.create()` invocation in         |
> |   -    "email": "isssalcupnamde@abc.com",            | /workspaces/Blog-Website/services/user.service.ts:   |
> |   -    "id": 1,                                      | 19:12                                                |
> |   -    "name": "Yash",                               |   16 });                                             |
> |   -    "password": "$2b$10$sORFubjTUt8Mt2k7vNqt4O3VV |                                                17    |
> |   hEWd71mbrad/h.Bm75.lm6CjOj6S",                     |   18 //Create the user                               |
> |   -    "updatedAt": "2024-06-06T18:06:49.995Z"       | → 19 const user = await prisma.user.create(          |
> |   -  }                                               | Could not figure out an ID in create                 |
> |   Invalid `prisma.user.create()` invocation in       | This is a non-recoverable error which probably hap   |
> |   /workspaces/Blog-Website/services/user.service.ts: | pens when the Prisma Query Engine has a panic.       |
> |   19:12                                              | https://github.com/prisma/prisma/issues/new?body=H   |
> |     16 });                                           | i+Prisma+Team%21+My+Prisma+Client+just+crashed.+Th   |
> |                                                  17  | is+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Nam   |
> ```
> 
> (The same is happening for the second `create()` later)
> 
> But using the application itself worked fine, it is only when using these mocks. That is also true for you, correct?
> 
> Are you sure this is not a problem in what the Keploy mocks return to Prisma? If that would be incorrect a bit, Prisma would probably not be able to find the ID and throw this error.

I debugged more into mocks which keploy return to Prisma and that seemed to be the problem. Seems like keploy is test and mocks are not in sequenece therefore there is the difference while record and keploy test. This issue can be closed ig https://github.com/prisma/prisma/issues/23923#issuecomment-2153152400

**Comment by janpio** [comment]
Can you explain a bit more what exactly is broken in Keploy? Can this be fixed somehow? This looked like an awesome tool, if we could get it to work properly.

**Comment by Sonichigo** [comment]
Hey @janpio, so what i observed was that the test case and mock for that specific test are not matched, this is happening due to the fact that the mock and test are based on binary matching while mostly resulted in random mocks for the test cases. Due to this the tests were failing, so when I tried to run `keploy test -c "bun --watch index.ts" --removeUnusedMocks` , i was able to get actual test result randomly out of 10 times.

**Comment by Sonichigo** [comment]
@janpio with the latest keploy release the issue is resolved!
```sh
🐰 Keploy: 2024-07-01T13:28:42+05:30    INFO    result  {"testcase id": "test-1", "testset id": "test-set-0", "passed": "true"}
🐰 Keploy: 2024-07-01T13:28:42+05:30    INFO    starting test for of    {"test case": "test-2", "test set": "test-set-0"}
Testrun failed for testcase with id: "test-2"

--------------------------------------------------------------------

+-------------------------------------------------------------------------------------------------------------+
|                                                DIFFS TEST-2                                                 |
+-------------------------------------------------------------------------------------------------------------+
|                     EXPECT HEADER                    |                   ACTUAL HEADER                      |
| -----------------------------------------------------+----------------------------------------------------- |
|                                                      |                                                      |
|                                                                                                             |
|                      EXPECT BODY                     |                    ACTUAL BODY                       |
| -----------------------------------------------------+----------------------------------------------------- |
|    {                                                 |  {                                                   |
|      "message": "User logged in successfully",       |    "message": "User logged in successfully",         |
|   -  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9. | +  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.   |
|   eyJpZCI6MSwiZW1haWwiOiJpc3NzYWxjdXBuYW1kZUBhYmMuY2 | eyJpZCI6MSwiZW1haWwiOiJpc3NzYWxjdXBuYW1kZUBhYmMuY2   |
|   9tIiwiaWF0IjoxNzE5ODIwNDE2LCJleHAiOjE3MTk5MDY4MTZ9 | 9tIiwiaWF0IjoxNzE5ODIwNzIyLCJleHAiOjE3MTk5MDcxMjJ9   |
|   .vPfugYdsBOlI-0LCdmLKADEEjRXz6FViBRWTJCKQTq8"      | ._q0QLMJ-6_Y588JLq3fzc3qtBwYEKzdnAQe9z-4PeeQ"        |
|    }                                                 |  }                                                   |
|                                                      |                                                      |
|                                                                                                             |
+-------------------------------------------------------------------------------------------------------------+
🐰 Keploy: 2024-07-01T13:28:42+05:30    INFO    result  {"testcase id": "test-2", "testset id": "test-set-0", "passed": "false"}
🐰 Keploy: 2024-07-01T13:28:42+05:30    INFO    starting test for of    {"test case": "test-3", "test set": "test-set-0"}
Testrun passed for testcase with id: "test-3"

--------------------------------------------------------------------

🐰 Keploy: 2024-07-01T13:28:42+05:30    INFO    result  {"testcase id": "test-3", "testset id": "test-set-0", "passed": "true"}
🐰 Keploy: 2024-07-01T13:28:42+05:30    INFO    starting test for of    {"test case": "test-4", "test set": "test-set-0"}
Testrun passed for testcase with id: "test-4"

--------------------------------------------------------------------

🐰 Keploy: 2024-07-01T13:28:42+05:30    INFO    result  {"testcase id": "test-4", "testset id": "test-set-0", "passed": "true"}

 <=========================================> 
  TESTRUN SUMMARY. For test-set: "test-set-0"
        Total tests: 4
        Total test passed: 3
        Total test failed: 1
 <=========================================> 

```

The issue was regarding how Prisma prepared the statement query, which is a bit different than the rest. I tried with couple of last releases as well from 16-19 and it worked prefectly fine.

**Comment by Sonichigo** [comment]
Hey @janpio, were you able to try out with new version ?
