### ISSUE TITLE
Studio startup doesn't work (ENOENT)

### ISSUE THREAD

**Issue by Cretezy** [prisma/prisma#2400]
When starting the studio with `prisma studio --experimental`, it can't find `@prisma/cli/index.js`:

```
➜  rm -rf /home/charles/.cache/prisma
➜  yarn prisma --experimental studio 
yarn run v1.22.4
$ prisma --experimental studio
Generating Prisma Client ... Failed to generate Prisma Client: GeneratorError: Error: ENOENT: no such file or directory, copyfile '/home/charles/code/socialux/api/node_modules/@prisma/cli/index.js' -> '/home/charles/.cache/prisma/studio/home-charles-code-socialux-api/index.js'
    at GeneratorProcess.handleResponse (/home/charles/code/socialux/api/node_modules/@prisma/cli/build/index.js:2:2807165)
    at LineStream.<anonymous> (/home/charles/code/socialux/api/node_modules/@prisma/cli/build/index.js:2:2806803)
    at LineStream.emit (events.js:310:20)
    at LineStream.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at LineStream.Readable.push (_stream_readable.js:209:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._pushBuffer (/home/charles/code/socialux/api/node_modules/@prisma/cli/build/index.js:2:2979140)
    at LineStream._transform (/home/charles/code/socialux/api/node_modules/@prisma/cli/build/index.js:2:2978959) {
  code: -32000,
  data: null
}
```

Using `2.0.0-beta.4`

**Comment by guilhermedeandrade** [comment]
Facing the exact same issue here. I can run `prisma generate` just fine, but running `prisma studio --experimental` will give me the same error

```sh
yarn run v1.22.4
$ /Users/guilherme/workspace/personal/valorant-plays/server/node_modules/.bin/prisma studio --experimental
Environment variables loaded from ./prisma/.env
Generating Prisma Client ... Failed to generate Prisma Client: GeneratorError: Error: ENOENT: no such file or directory, copyfile '/Users/guilherme/workspace/personal/valorant-plays/server/node_modules/@prisma/cli/index.js' -> '/Users/guilherme/.cache/prisma/studio/Users-guilherme-workspace-personal-valorant-plays-server/index.js'
    at GeneratorProcess.handleResponse (/Users/guilherme/workspace/personal/valorant-plays/server/node_modules/@prisma/cli/build/index.js:2:2807165)
    at LineStream.<anonymous> (/Users/guilherme/workspace/personal/valorant-plays/server/node_modules/@prisma/cli/build/index.js:2:2806803)
    at LineStream.emit (events.js:321:20)
    at LineStream.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:305:12)
    at readableAddChunk (_stream_readable.js:280:11)
    at LineStream.Readable.push (_stream_readable.js:214:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._pushBuffer (/Users/guilherme/workspace/personal/valorant-plays/server/node_modules/@prisma/cli/build/index.js:2:2979140)
    at LineStream._transform (/Users/guilherme/workspace/personal/valorant-plays/server/node_modules/@prisma/cli/build/index.js:2:2978959) {
  code: -32000,
  data: null
}
```

Using `"@prisma/cli": "^2.0.0-beta.4"` and `"@prisma/client": "^2.0.0-beta.4"`

**Comment by e2goon** [comment]
```
$ prisma studio --browser "Google Chrome" --experimental
Environment variables loaded from ./prisma/.env
Generating Prisma Client ... Failed to generate Prisma Client: GeneratorError: Error: ENOENT: no such file or directory, copyfile 'C:\Users\onemon\Documents\workspace\gamecamp-server\node_modules\@prisma\cli\index.js' -> 'C:\Users\onemon\AppData\Roaming\Prisma\Studio\-Users-onemon-Documents-workspace-gamecamp-server\index.js'
    at GeneratorProcess.handleResponse (C:\Users\onemon\Documents\workspace\gamecamp-server\node_modules\@prisma\cli\build\index.js:2:2807165)
    at LineStream.<anonymous> (C:\Users\onemon\Documents\workspace\gamecamp-server\node_modules\@prisma\cli\build\index.js:2:2806803)
    at LineStream.emit (events.js:311:20)
    at LineStream.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at LineStream.Readable.push (_stream_readable.js:209:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._pushBuffer (C:\Users\onemon\Documents\workspace\gamecamp-server\node_modules\@prisma\cli\build\index.js:2:2979140)
    at LineStream._transform (C:\Users\onemon\Documents\workspace\gamecamp-server\node_modules\@prisma\cli\build\index.js:2:2978959) {
  code: -32000,
  data: null
}
```

So do i

**Comment by madebysid** [comment]
Hey everyone, I've tried to reproduce this unsuccessfully, so I'm guessing something about my setup is different from yours. It also looks like this is happening on all platforms so can't be a macOS specific thing.

I'd really appreciate it if you could do some investigation for me:

1. Do you have @prisma/cli installed locally in your project's package.json or globally? I tried both ways, but haven't been able to see this.
2. Is this happening in one specific project? What happens if you move to a brand new directory and then do `npm init && npm i @prisma/cli @prisma/client && npx @prisma/cli@alpha init && npx @prisma/cli@alpha studio --experimental`? I just want to make sure this isn't a case of busted `node_modules` since we did make a change on that front recently. You might need to tweak the command a little, but the point is to init a new project.
3. Have you tried this on the latest alpha yet? (2.0.0-alpha.1200). I know @Cretezy did, but in their case, it looks like Studio failed to shut down correctly the first time around, so if you could kill all processes listening on port 5555 and try again, you should get the same error (or not!)

If there's anything else about your setup that you think might be relevant, please let me know too. Thanks so much!
