### ISSUE TITLE
JSONB support doesn't serialize objects on insert or select

### ISSUE THREAD

**Issue by airhorns** [prisma/prisma#2404]
## Bug description

According to the description in https://github.com/prisma/prisma/issues/186#issuecomment-623413319 , the new JSON type support in `2.0.0-beta.4` should accept unserialized objects for the values of `Json` fields, and return deserialized objects on query. I don't observe either of those behaviours:

## How to reproduce

See https://github.com/airhorns/prisma-json-test for an easy to clone example, but with a schema like this:

```
model Post {
  id         Int     @default(autoincrement()) @id
  title      String
  content    String?
  metafields Json?
}
```

### Inserting records

This code should not throw:

```typescript
  await prisma.post.create({
    data: {
      title: "A post with json",
      content: "stuff",
      metafields: { foo: "bar" },
    },
  });
```
but I get a query parse error:

```
prisma-client Prisma Client call: +83ms
  prisma-client prisma.post.create({
  prisma-client   data: {
  prisma-client     title: 'A post with json',
  prisma-client     content: 'stuff',
  prisma-client     metafields: {
  prisma-client       foo: 'bar'
  prisma-client     }
  prisma-client   }
  prisma-client }) +0ms
  prisma-client Generated request: +0ms
  prisma-client mutation {
  prisma-client   createOnePost(data: {
  prisma-client     title: "A post with json"
  prisma-client     content: "stuff"
  prisma-client     metafields: {
  prisma-client       "foo": "bar"
  prisma-client     }
  prisma-client   }) {
  prisma-client     id
  prisma-client     title
  prisma-client     content
  prisma-client     metafields
  prisma-client   }
  prisma-client }
  prisma-client  +0ms
  engine {
  engine   error: PrismaClientUnknownRequestError: Error parsing GraphQL query: query parse error: Parse error at 6:7
  engine   Unexpected `"foo"[StringValue]`
  engine   Expected `Name`, `:` or `}`
  engine
  engine       at NodeEngine.graphQLToJSError (/Users/airhorns/Code/prisma-json-test/node_modules/@prisma/engine-core/dist/NodeEngine.js:589:1)
  engine       at /Users/airhorns/Code/prisma-json-test/node_modules/@prisma/engine-core/dist/NodeEngine.js:495:1
  engine       at process.result (internal/process/task_queues.js:97:5)
  engine       at PrismaClientFetcher.request (/Users/airhorns/Code/prisma-json-test/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:620:13)
  engine       at main (/Users/airhorns/Code/prisma-json-test/test-create.ts:23:3)
  engine } +53ms
```

### Fetching records

With the same schema, this code should log objects with deserialized json objects

```typescript
  await prisma.post.create({
    data: {
      title: "A post",
      content: "stuff",
      metafields: '{"foo": "bar"}' as any,
    },
  });

  console.log(await prisma.post.findMany());
```

I would expect the logged records to have an object at the `metafields` key, but instead it has a string:

```javascript
[
  {
    id: 8,
    title: 'A post',
    content: 'stuff',
    metafields: '{"foo":"bar"}'
  }
]
```

To verify that the JSON is actually saved as JSON and not a string JSON literal in the database, we can connect with a sql client and test:

```
example=# select * from public."Post";
 content | id |   metafields   | title
---------+----+----------------+--------
 stuff   |  8 | {"foo": "bar"} | A post
(1 row)

example=# select metafields->>'foo' from public."Post";
 ?column?
----------
 bar
(1 row)

```

Also noteworthy is that the Typescript types for the `metafields` key of the input object on the `create` call expects an object for the field value, but to avoid the first issue I have to pass a string to get JSON inserted, hence the ` '{"foo": "bar"}' as any `.

## Expected behavior

To insert records I should be able to pass a plain old JavaScript object that gets serialized to the JSON column in the database.

When fetching records I should get JSON saved in the database deserialized to plain old JavaScript objects, not strings, for `Json` fields.

## Environment & setup

- OS: OS X
- Database: PostgreSQL
- Prisma version: 

```
@prisma/cli          : 2.0.0-beta.4
Current platform     : darwin
Query Engine         : query-engine afd294205618b1c825b013ba6f5a6ebe4aa4a514 (at /Users/airhorns/Code/prisma-json-test/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli afd294205618b1c825b013ba6f5a6ebe4aa4a514 (at /Users/airhorns/Code/prisma-json-test/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core afd294205618b1c825b013ba6f5a6ebe4aa4a514 (at /Users/airhorns/Code/prisma-json-test/node_modules/@prisma/cli/introspection-engine-darwin)
```

- Node.js version: `v13.7.0`

**Comment by andreyk-code** [comment]
experiencing the same problem and error when trying to create JSON object with prisma, running 2.0.0-beta.4

```
→  7   const instructor1 = await prisma.user.create(Error parsing GraphQL query: query parse error: Parse error at 13:11
Unexpected `"link"[StringValue]`
Expected `Name`, `:` or `}`
```

**Comment by pantharshit00** [comment]
Hi,

Can you please try again with the latest alpha? I did a bug fix for a similar issue there.

Use `npm install @prisma/client@alpha @prisma/cli@alpha && npx @prisma/cli@alpha generate`

**Comment by emckay** [comment]
Hi @pantharshit00 , I'm having the same issues, which were mostly resolved by switching to the latest alpha (1201)

However, my schema has an optional `Json` field and when upserting a record for that field with the value `null`, I get this error:

```
Error persisting view TypeError: Cannot read property 'values' of null
    at stringify (/node_modules/@prisma/client/src/runtime/query.ts:684:13)
    at Arg._toString (/node_modules/@prisma/client/src/runtime/query.ts:772:23)
    at Arg.toString (/node_modules/@prisma/client/src/runtime/query.ts:781:17)
    at map (/node_modules/@prisma/client/src/runtime/query.ts:657:25)
    at Array.map (<anonymous>)
    ...
```

Let me know if you need more info to track this down. Thanks!

**Comment by janpio** [comment]
@emckay New issue with all the details of this would be awesome.

**Comment by radicand** [comment]
@emckay @janpio I opened an issue with this a few days ago: https://github.com/prisma/prisma/issues/2399

**Comment by airhorns** [comment]
I think the alpha has fixed these issues, thanks!

**Comment by emroot** [comment]
I'm getting the same error. I'm using `@prisma/cli@^2.0.0-alpha.1207`

```
2020-05-12T23:57:13.516Z printStack callsite Error:
backend     |     at Object.model [as UserSubscription] (/srv/backend/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:376:28)
backend     |     at Object.n.<computed> [as upsert] (/srv/backend/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:511:33)
backend     |     at Object.<anonymous> (/srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:31:53)
backend     |     at step (/srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:33:23)
backend     |     at Object.next (/srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:14:53)
backend     |     at /srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:8:71
backend     |     at new Promise (<anonymous>)
backend     |     at __awaiter (/srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:4:12)
backend     |     at /srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:27:47
backend     |     at new Promise (<anonymous>)
backend     |     at Object.<anonymous> (/srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:27:22)
backend     |     at step (/srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:33:23)
backend     |     at Object.next (/srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:14:53)
backend     |     at /srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:8:71
backend     |     at new Promise (<anonymous>)
backend     |     at __awaiter (/srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:4:12)
backend     | (node:117) UnhandledPromiseRejectionWarning: Error:
backend     | Invalid `prisma.userSubscription.upsert()` invocation in
backend     | /srv/backend/packages/backend/src/schema/admin/UserSubscription.ts:31:53
backend     |
backend     | Error parsing GraphQL query: query parse error: Parse error at 14:9
backend     | Unexpected `"listCount"[StringValue]`
backend     | Expected `Name`, `:` or `}
```

**Comment by ujuc** [comment]
@emroot https://github.com/prisma/prisma-client-js/issues/680

**Comment by ragnorc** [comment]
Still experiencing this issue with 2.0.0-alpha.1219

**Comment by pantharshit00** [comment]
@ragnorc Please make sure you run `npx @prisma/cli@alpha generate` after updating. 

Also, if you are still experiencing this after running that, please open a new issue with a reproduction

**Comment by ragnorc** [comment]
@pantharshit00 Thanks! The error still occurs with JSON arrays and the issue is actually already being tracked in #2432.
