### ISSUE TITLE
Prisma does not work with bun alpine docker image.

### ISSUE THREAD

**Issue by hiroaki2020** [prisma/prisma#24095]
### Bug description

When I try to run prisma on oven/bun docker image(bun runtime official image), I got the following error.
```
PrismaClientInitializationError: Unable to require(`/home/bun/app/node_modules/.prisma/client/libquery_engine-linux-musl-arm64-openssl-3.0.x.so.node`).
2024-05-07 18:57:17 The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements
2024-05-07 18:57:17 
2024-05-07 18:57:17 Details: /usr/lib/libc.so: invalid ELF header
2024-05-07 18:57:17       at new e (/home/bun/app/node_modules/@prisma/client/runtime/library.js:22:1872)
2024-05-07 18:57:17       at /home/bun/app/node_modules/@prisma/client/runtime/library.js:111:10219
2024-05-07 18:57:17 
2024-05-07 18:57:17 Bun v1.1.7 (Linux arm64)
```

### How to reproduce

1. run docker image oven/bun:1.1.7-alpine and enter it 
2. setup Nest.js + GraphQL + apollo
3. run prisma migrate + generate. Those are successful.
4. When I start container, I got the error above.
5. Actualy when I ran prisma -v to get version I got the same error.

### Expected behavior

work properly without the error

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  // email String  @unique
  name  String?
}
```

### Environment & setup

- host PC OS: macOS
- host PC chip: apple sillicon(M2)
- docker OS: alpine. It's on docker for Mac.
- Database: PostgreSQL
- Node.js version: I use bun instead.

### Prisma Version

```
prisma + prisma client version is 5.13.0
```

**Comment by hiroaki2020** [comment]
I tried debian oven/bun image and clarified prisma is working.

**Comment by hiroaki2020** [comment]
Closing this issue because it seems this issue is caused by bun, not prisma.
[source](https://github.com/oven-sh/bun/issues/10892#issuecomment-2101666541)
