### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by fjdvchain** [prisma/prisma#24184]
### Bug description

got a PrismaClientRustPanicError 

```
at In.request (/usr/src/app/node_modules/.prisma/sqlite/runtime/library.js:122:5896)\n    at async l (/usr/src/app/node_modules/.prisma/sqlite/runtime/library.js:127:11167)\n    at async main (/usr/src/app/build/cmd/debit.js:66:13)","name":"PrismaClientRustPanicError","clientVersion":"5.13.0"}
```

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by jkomyno** [comment]
Hi @fjdvchain, unfortunately this issue doesn't tell us any information that can be useful to reproduce this panic.
I'm thus closing it, but I recommend you to open a new one by filling out [this template](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&projects=&template=bug_report.yml). Thanks!
