### ISSUE TITLE
Runtime error that occurs in `findunique()` when unique constraint is composed of one field

### ISSUE THREAD

**Issue by mmmmicha** [prisma/prisma#24241]
### Bug description

After configuring the schema as shown below(Prisma information), the `userId` set as a `unique constraint` was mapped to whereArgs of `findUnique()`. There is no type error or compile error, but the following error occurs at runtime.

```
PrismaClientValidationError: 
Invalid `this.readOnlyPrisma.test.findUnique()` invocation in
/Users/test/Workspace/test_monorepo/dist/apps/api/src/test/test.v3.service.js:1302:73

  1299 getTest(userId) {
  1300     var _a;
  1301     return __awaiter(this, void 0, void 0, function* () {
→ 1302         const test = yield this.readOnlyPrisma.test.findUnique({
                 where: {
                   userId: 1219,
               ?   id?: Int,
               ?   AND?: TestWhereInput | TestWhereInput[],
               ?   OR?: TestWhereInput[],
               ?   NOT?: TestWhereInput | TestWhereInput[],
               ?   createdAt?: DateTimeFilter | DateTime,
               ?   updatedAt?: DateTimeFilter | DateTime,
               ?   score?: IntFilter | Int,
               ?   user?: UserRelationFilter | UserWhereInput,
               ?   history?: TestHistoryListRelationFilter
                 },
                 select: {
                   score: true
                 }
               })

Argument `where` of type TestWhereUniqueInput needs at least one of `id` or `Test_userId_unique_constraint` arguments. Available options are marked with ?.
    at Tn (/Users/test/Workspace/test_monorepo/node_modules/@prisma/client/runtime/library.js:115:6855)
    at In.handleRequestError (/Users/test/Workspace/test_monorepo/node_modules/@prisma/client/runtime/library.js:122:6510)
    at In.handleAndLogRequestError (/Users/test/Workspace/test_monorepo/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/Users/test/Workspace/test_monorepo/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/Users/test/Workspace/test_monorepo/node_modules/@prisma/client/runtime/library.js:127:11167)
```

The `Test_userId_unique_constraint` mentioned here does not currently exist in `TestWhereUniqueInput`. (Please refer to the prisma information below). As a result, a type error occurs when trying to apply `Test_userId_unique_constraint` to the where condition only. (As a result of my testing, `id` and `Test_userId_unique_constraint` are not set to Where condition. If you pass it together, the type error seems to be avoided. However, I don't want to use the unique condition while passing the id like this). In fact, if you use `userId`(defined as unique), the type error does not occur. However, as mentioned earlier, a more serious runtime error occurs.

### How to reproduce

Please check prisma information part

### Prisma information

```prisma
// Add your schema.prisma
model Test {
  id        Int                   @id @default(autoincrement())
  createdAt DateTime              @default(now()) @db.Timestamptz(3)
  updatedAt DateTime              @updatedAt @db.Timestamptz(3)
  userId    Int
  user      User                  @relation(fields: [userId], references: [id])
  score     Int                   @default(0)
  history   TestHistory[]

  @@unique([userId], name: "Test_userId_unique_constraint")
  @@index([createdAt])
}
```

```ts
// Add your code using Prisma Client
const test = await this.readOnlyPrisma.test.findUnique({
      where: {
        userId, // <--- occured here
      },
      select: {
        score: true,
      },
    });
```
```ts
// index.d.ts
export type TestWhereUniqueInput = Prisma.AtLeast<
  {
    id?: number;
    userId?: number;
    AND?: TestWhereInput | TestWhereInput[];
    OR?: TestWhereInput[];
    NOT?: TestWhereInput | TestWhereInput[];
    createdAt?: DateTimeFilter<'Test'> | Date | string;
    updatedAt?: DateTimeFilter<'Test'> | Date | string;
    score?: IntFilter<'Test'> | number;
    user?: XOR<UserRelationFilter, UserWhereInput>;
    history?: TestHistoryListRelationFilter;
  },
  'id' | 'Test_userId_unique_constraint'
>;
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v20.10.0

### Prisma Version

```
prisma                  : 5.14.0
@prisma/client          : 5.13.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine e9771e62de70f79a5e1c604a2d7c8e2a0a874b48 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli e9771e62de70f79a5e1c604a2d7c8e2a0a874b48 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.14.0-25.e9771e62de70f79a5e1c604a2d7c8e2a0a874b48
Default Engines Hash    : e9771e62de70f79a5e1c604a2d7c8e2a0a874b48
Studio                  : 0.500.0
```

**Comment by jkomyno** [comment]
Hi, I've reproduced this issue with Prisma 5.14.0.

- `schema.prisma`
  ```prisma
  generator client {
    provider        = "prisma-client-js"
  }
  
  datasource db {
    provider = "postgres"
    url      = env("TEST_POSTGRES_URI")
  }
  
  model User {
    id   Int    @id @default(autoincrement())
    name String
    Test Test?
  }
  
  model Test {
    id        Int      @id @default(autoincrement())
    createdAt DateTime @default(now()) @db.Timestamptz(3)
    updatedAt DateTime @updatedAt @db.Timestamptz(3)
    userId    Int
    user      User     @relation(fields: [userId], references: [id])
    score     Int      @default(0)
  
    @@unique([userId], name: "Test_userId_unique_constraint")
    @@index([createdAt])
  }

  ```

- TypeScript snippet
  ```typescript
  import { PrismaClient } from '.prisma/client'
  
  async function main() {
    const prisma = new PrismaClient()
    const user = await prisma.user.create({
      data: {
        id: 1,
        name: 'jkomyno'
      }
    })
  
    console.log(user)
    
    // Add your code using Prisma Client
    const test = await prisma.test.findUnique({
      where: {
        userId: 1, // <--- occured here
      },
      select: {
        score: true,
      },
    });
  
    console.log(test)
  }
  
  void main().catch((e) => {
    console.log(e.message)
    process.exit(1)
  })
  ```

- Output:
  ```
  { id: 1, name: 'Alberto' }
  
  Invalid `prisma.test.findUnique()` invocation in
  /Users/jkomyno/work/prisma/prisma/sandbox/basic-sqlite/index.ts:15:34
  
    12 console.log(user)
    13 
    14 // Add your code using Prisma Client
  → 15 const test = await prisma.test.findUnique({
         where: {
           userId: 1,
       ?   id?: Int,
       ?   AND?: TestWhereInput | TestWhereInput[],
       ?   OR?: TestWhereInput[],
       ?   NOT?: TestWhereInput | TestWhereInput[],
       ?   createdAt?: DateTimeFilter | DateTime,
       ?   updatedAt?: DateTimeFilter | DateTime,
       ?   score?: IntFilter | Int,
       ?   user?: UserRelationFilter | UserWhereInput
         },
         select: {
           score: true
         }
       })
  
  Argument `where` of type TestWhereUniqueInput needs at least one of `id` or `Test_userId_unique_constraint` arguments. Available options are marked with ?.
  ```

**Comment by subashcs** [comment]
Is this issue only seen with postgres connector ?

**Comment by subashcs** [comment]
I have also replicated this issue with postgres and sqlite connector. 
The following error is returned by the LibraryEngine.
Here's the error:
```
Error in query graph construction: QueryParserError(ValidationError { kind: SomeFieldsMissing, message: "Some fields are missing: Expected a minimum of 1 fields of (id, Test_userId_unique_constraint) to be present, got 0.", meta: Some(Object {"inputType": Object {"kind": String("object"), "name": String("TestWhereUniqueInput"), "fields": Array [Object {"name": String("id"), "typeNames": Array [String("Int")], "required": Bool(false)}, Object {"name": String("userId"), "typeNames": Array [String("String")], "required": Bool(false)}, Object {"name": String("AND"), "typeNames": Array [String("TestWhereInput"), String("TestWhereInput[]")], "required": Bool(false)}, Object {"name": String("OR"), "typeNames": Array [String("TestWhereInput[]")], "required": Bool(false)}, Object {"name": String("NOT"), "typeNames": Array [String("TestWhereInput"), String("TestWhereInput[]")], "required": Bool(false)}, Object {"name": String("createdAt"), "typeNames": Array [String("DateTimeFilter"), String("DateTime")], "required": Bool(false)}, Object {"name": String("updatedAt"), "typeNames": Array [String("DateTimeFilter"), String("DateTime")], "required": Bool(false)}, Object {"name": String("score"), "typeNames": Array [String("IntFilter"), String("Int")], "required": Bool(false)}, Object {"name": String("user"), "typeNames": Array [String("UserRelationFilter"), String("UserWhereInput")], "required": Bool(false)}]}, "argumentPath": Array [String("where")], "selectionPath": Array [String("findUniqueTest")], "constraints": Object {"minFieldCount": Number(1), "maxFieldCount": Null, "requiredFields": Array [String("id"), String("Test_userId_unique_constraint")]}}) })
```

**Comment by TimBeyer** [comment]
We just ran into the same issue when upgrading from `4.16.2` to `5.19.1`.
It's a bug that prevents us from upgrading since we need the explicitly named uniqueness constraints for integration with another system.

**Comment by mmmmicha** [comment]
I really didn't want to do that, but because of this bug, I mostly changed `findUnique` to `findFirst`.. :(

**Comment by Lp-Francois** [comment]
Same issue as @TimBeyer :(
