### ISSUE TITLE
Can't use Prisma Client in Next.js middleware, even locally

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#24430]
> Also, @CodeZak, did you re-run `prisma generate` after installing the new Prisma Client version?

yeah, i did that, 
I have pushed a new repo that you can take a look at to investigate the issue: https://github.com/CodeZak/NextAuth5
The code runs Prisma on the middleware through the authConfig file.

_Originally posted by @CodeZak in https://github.com/prisma/prisma/issues/21310#issuecomment-2147682588_

**Comment by janpio** [comment]
@CodeZak I gave your reproduction a shot. Just running the obvious commands and flows (I had to log the verification link instead of using Resend, that was much easier), I indeed get this error message:

```
[auth][cause]: Error: PrismaClient is not configured to run in Vercel Edge Functions or Edge Middleware. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters

If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report
    at Object.get (webpack-internal:///(middleware)/./node_modules/.prisma/client/index-browser.js:223:15)
    at Object.jwt (webpack-internal:///(middleware)/./auth.config.ts:108:80)
    at Module.session (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/lib/actions/session.js:27:43)
    at async AuthInternal (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/lib/index.js:47:24)
    at async Auth (webpack-internal:///(middleware)/./node_modules/next-auth/node_modules/@auth/core/index.js:126:34)
    at async handleAuth (webpack-internal:///(middleware)/./node_modules/next-auth/lib/index.js:134:29)
    at async adapter (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:179:16)
    at async /workspace/NextAuth5/node_modules/next/dist/server/web/sandbox/sandbox.js:110:22
    at async runWithTaggedErrors (/workspace/NextAuth5/node_modules/next/dist/server/web/sandbox/sandbox.js:107:9)
    at async DevServer.runMiddleware (/workspace/NextAuth5/node_modules/next/dist/server/next-server.js:1062:24)
```

---

But that is expected as the project is using a Next.js middleware, which runs in the edge runtime, even locally:

> Middleware currently only supports the [Edge runtime](https://nextjs.org/docs/app/building-your-application/rendering/edge-and-nodejs-runtimes). The Node.js runtime can not be used.

via https://nextjs.org/docs/app/building-your-application/routing/middleware#runtime

That is why the error message tells you theoption `Use Driver Adapters: https://pris.ly/d/driver-adapters`.

Explanation: As in edge runtime of Next.js Prisma can not talk to databases by default, we built [driver adapters](https://www.prisma.io/docs/orm/overview/databases/database-drivers#driver-adapters) (currently behind preview feature flag `driverAdapters`). That allows you to use a database driver that _does_ work in the edge runtime that the Next.js middleware uses. 

---

Ok, let's follow this: 

The obvious driver adapter when using PostgreSQL is https://www.prisma.io/docs/orm/overview/databases/postgresql#using-the-node-postgres-driver, so apply the steps from there and adapt your code a bit. Run the app again and... 💥 

![image](https://github.com/prisma/prisma/assets/183673/c49c5d84-d0ad-458e-97f3-f30ba72ddc72)

Unfortunately it seems that the `pg` database driver is not compatible with the Next.js middlewares as well. 
Here is an issue for that in the `pg` repository: https://github.com/brianc/node-postgres/issues/3206

There supposedly is a workaround that `pg` could apply: https://github.com/brianc/node-postgres/issues/3206#issuecomment-2135313773

**Comment by janpio** [comment]
And to follow up to show that Prisma works fine in this context, here is the setup required to use a Neon PostgreSQL database:
https://github.com/CodeZak/NextAuth5/pull/2

![image](https://github.com/prisma/prisma/assets/183673/6fe46c34-5679-4e0e-a9b8-dee56a9612f7)

**Comment by liuhuapiaoyuan** [comment]
难道就没办法使用本地的开发的`sqlite`吗？

**Comment by janpio** [comment]
@liuhuapiaoyuan Can you please open a new issue and describe more what you are referring to? This issue here is specifically about the usage of `pg` via `@prisma/adapter-pg` in a Next.js middleware. No need to be connected to the internet if it works, but `pg` will need to remove their limitation of not working in Vercel/Next.js's edge runtime first. That happens in the issue I linked.

**Comment by liuhuapiaoyuan** [comment]
Sorry, I think I understand. I will try it first.

**Comment by liuhuapiaoyuan** [comment]
But in this case, it seems that only by looking at the documentation it is possible to solve the connection of `postgres`
Could we utilize the idea like `PrismaNeonHTTP` to implement the serialization of `sql` into json and then receive the possibility of this request in `next`?

Can we use prisma again for the request in the next?

**Comment by janpio** [comment]
I don't understand, and think this question is off topic for this issue that is about usage of `pg` via `@prisma/adapter-pg` in a Next.js middleware. If you are looking for workarounds, there are none for talking to a PostgreSQL database right now that I am aware of.

If you are looking other alternatives, please open a discussion and explain what you are looking for. Feel free to @ mention me in there to instantly get my attention. Thank you.

**Comment by liuhuapiaoyuan** [comment]
Okay, you are right。

**Comment by janpio** [comment]
The understanding in https://github.com/brianc/node-postgres/issues/3206 has evolved in that it is not possible to enable usage of `pg` in the Edge Runtime (which is used by Next.js Middleware and others edge runtime functionality) because of the missing TCP socket support. This is a limitation of the Edge Runtime by Vercel that is used in Next.js and when deployed to Vercel.

Instead of `@prisma/adapter-pg` one will have to use one of the [other driver adapters](https://www.prisma.io/docs/orm/overview/databases/database-drivers#driver-adapters), for example the one for Neon, PlanetScale or Turso. Unfortunately nothing Prisma or `pg` can do to workaround this limitation.

**Comment by Charismara** [comment]
Has someone managed to get prisma working with postgres in the nextjs edge runtime?

**Comment by dbradmit** [comment]
I'm looking for some clarity or confirmation on using Prisma Client with Next.js middleware. Prior to [5.11.0](https://github.com/prisma/prisma/releases/tag/5.11.0) there wasn't Edge function support. With 5.11.0 you can now use driver adapters to get around the Next.js middleware issue but not with the `pg` driver adapter due to the issues noted above.

So even if I'm not using Vercel Edge, the only options are to use Prisma Accelerate or a driver adapter for Neon, PlanetScale, or Turso? And that isn't likely to change anytime in the near future?

**Comment by jahabeebs** [comment]
> I'm looking for some clarity or confirmation on using Prisma Client with Next.js middleware. Prior to [5.11.0](https://github.com/prisma/prisma/releases/tag/5.11.0) there wasn't Edge function support. With 5.11.0 you can now use driver adapters to get around the Next.js middleware issue but not with the `pg` driver adapter due to the issues noted above.
> 
> So even if I'm not using Vercel Edge, the only options are to use Prisma Accelerate or a driver adapter for Neon, PlanetScale, or Turso? And that isn't likely to change anytime in the near future?

That's correct, and even with the driver adapters it seems there are issues running against a local db (at least with the neon adapter and neon db)

**Comment by zMattew** [comment]
I let prisma client orm connect to neondb in the vercel edge runtime with the http driver adapter.
```
import { PrismaClient } from '@prisma/client'
import { neon } from '@neondatabase/serverless'
import { PrismaNeonHTTP } from '@prisma/adapter-neon'

const connection = neon(`${process.env.DATABASE_URL}`,{
    arrayMode:false,
    fullResults:true
})
const adapter = new PrismaNeonHTTP(connection)
const db = new PrismaClient({adapter})

export default db
```

**Comment by iFlyinq** [comment]
> I'm looking for some clarity or confirmation on using Prisma Client with Next.js middleware. Prior to [5.11.0](https://github.com/prisma/prisma/releases/tag/5.11.0) there wasn't Edge function support. With 5.11.0 you can now use driver adapters to get around the Next.js middleware issue but not with the `pg` driver adapter due to the issues noted above.
> 
> So even if I'm not using Vercel Edge, the only options are to use Prisma Accelerate or a driver adapter for Neon, PlanetScale, or Turso? And that isn't likely to change anytime in the near future?

It is a huge drawback though...

**Comment by the-me-0** [comment]
Running into the same issue here. I made a repo to reproduce : https://github.com/the-me-0/node-pg-minimal-repro

Sadly I have not found a solution yet, and it seems unlikely pg will find a way around.

**Comment by the-me-0** [comment]
I might have found a way around for my use case (which was more precise than just the edge environment). I have the feeling it does not solve the `@prisma/adapter-pg` and `pg` issue, but I still have to test a few things to make sure it works. In any case, I will edit my comment with some documentation on my problem and the way I fixed it (I hope I did).

**Comment by ErickGiffoni** [comment]
I'm running the "same" issue. I need to access my db in the middleware, so I followed this guide:
- https://www.prisma.io/docs/orm/overview/databases/postgresql#using-the-node-postgres-driver

But then Edge complains about pg using the crypto module:

```
Error: The edge runtime does not support Node.js 'crypto' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
    at Object.get (.next/server/edge/chunks/_608f43._.js:62:19)
    at [project]/node_modules/pg/lib/crypto/utils-webcrypto.js [middleware] (ecmascript) (.next/server/edge/chunks/node_modules_5b1a03._.js:5725:36)
    at <unknown> (.next/server/edge/chunks/edge-wrapper_f533d1.js:693:27)
    at runModuleExecutionHooks (.next/server/edge/chunks/edge-wrapper_f533d1.js:738:9)
    at instantiateModule (.next/server/edge/chunks/edge-wrapper_f533d1.js:691:9)
    at getOrInstantiateModuleFromParent (.next/server/edge/chunks/edge-wrapper_f533d1.js:624:12)
    at commonJsRequire (.next/server/edge/chunks/edge-wrapper_f533d1.js:157:20)
    at [project]/node_modules/pg/lib/crypto/utils.js [middleware] (ecmascript) (.next/server/edge/chunks/node_modules_5b1a03._.js:5843:22)
    at <unknown> (.next/server/edge/chunks/edge-wrapper_f533d1.js:693:27)
    at runModuleExecutionHooks (.next/server/edge/chunks/edge-wrapper_f533d1.js:738:9)
```

**Comment by kamigi** [comment]
i run into the same issue  on  nextjs 15 project :
[Error: The edge runtime does not support Node.js 'crypto' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime]

**Comment by Rodrigo001-dev** [comment]
In my case, I was trying to implement authentication with Auth.js and was using Prisma, so I had to revert the version of

@auth/prisma-adapter to 2.7.4

And enable the feature to enable "nodeMiddleware: true"

In next.config.ts
`experimental: {
    nodeMiddleware: true,
  },
`

And in middleware file

`
export const config = {
  runtime: 'nodejs',
}
`

This worked for me

Some links that helped me
[NextJS, Auth.js and Postgres. Any way to make this combo work?](https://www.reddit.com/r/nextjs/comments/1hi6yne/nextjs_authjs_and_postgres_any_way_to_make_this)
[Next.js runtime config](https://nextjs.org/docs/app/building-your-application/routing/middleware#runtime)

**Comment by paambaati** [comment]
This is also a problem in Nuxt 3 apps running on Node v20.x.

```
Error:  [nuxi] Nuxt Build Error: node_modules/@prisma/client/runtime/client.mjs (78:11954): "webcrypto" is not exported by "__vite-browser-external", imported by "node_modules/@prisma/client/runtime/client.mjs".
file: /home/runner/work/devex-blueprint/devex-blueprint/node_modules/@prisma/client/runtime/client.mjs:78:11954
```

**Comment by popiazaza** [comment]
NodeJS for Next.js middleware is now stable in version 15.5+, just set it in middleware.ts, no need to set it in next.config.ts anymore.

https://nextjs.org/docs/app/api-reference/file-conventions/middleware#runtime

This solved a lot of trouble in Prisma, crypto, and other libs.

**Comment by thesolomon-tech** [comment]
Thanks @popiazaza 
Anyone know if there is a downside to using Node for Middleware?

**Comment by popiazaza** [comment]
> Thanks @popiazaza 
> Anyone know if there is a downside to using Node for Middleware?

I did see chunked file upload using form data to be unreadable.

I did not investigate further as I figured out that I shouldn't be using Prisma in NextJS middleware at all.

NextJS middleware is an edge server because it suppose to be fast and only do minimal work to route users like a gateway.

I got mislead by AuthJS to do a middleware in NextJS. It is not a requirement, you can just check session within your API. For middleware, you should just check for JWT data at most. Don't put any long process within it, unless you must have it.

**Comment by MoSattler** [comment]
I have this problem in latest react-router. Anyone has an idea how to fix that?

**Comment by mseebach** [comment]
@MoSattler The issue is that the Prisma library has some parts that handles the database connection with all sorts of dependencies that can't run in the browser. The 'problem' with frameworks like react-router and next.js is that it intermingles the server-side and the browser-side code, and makes it easy to accidentally cross the boundary.

This issue occurs when the build attempts to include the server-side parts of Prisma in the browser libraries.

The solution is to keep Prisma out of the browser-side. For me, I had to stop importing the Prisma _client_ in routes:

app/routes/customer.tsx:
`import { type Customer } from "prisma/generated/client";`

Change this to:
`import { type Customer } from "prisma/generated/browser";`

`browser` has all the types, but doesn't pull in any of the server-only dependencies.
