### ISSUE TITLE
Failed to deploy nuxtjs+prisma+cloudflareD1 to Cloudflare page

### ISSUE THREAD

**Issue by zou-yu** [prisma/prisma#24713]
### Bug description

Building failed with prisma+cloudflareD1 in nuxtjs framework, both local and cloudflare pipeline.

### How to reproduce

Running `prisma generate && nuxt build`
And got this:
```
Running
[plugin inject] node_modules/.pnpm/@prisma+client@5.16.1_prisma@5.16.1/node_modules/.prisma/client/query_engine_bg.wasm: rollup-plugin-inject: failed to parse /opt/buildhome/repo/node_modules/.pnpm/@prisma+client@5.16.1_prisma@5.16.1/node_modules/.prisma/client/query_engine_bg.wasm. Consider restricting the plugin to particular files via options.include
--
00:17:43.355 | [error] [nitro] RollupError: node_modules/.pnpm/@prisma+client@5.16.1_prisma@5.16.1/node_modules/.prisma/client/query_engine_bg.wasm (1:5): Unexpected eof (Note that you need plugins to import files that are not JavaScript)
00:17:43.356 |  
00:17:43.356 |  
00:17:43.356 | 1: asm�V```````````~```~`~`...
00:17:43.357 | ^
00:17:43.357 | 2: `}`\|`~`}`~`}`\|`~`~~`~~`\|`~~`\|`\|`...
00:17:43.357 | 3:  						!...
00:17:43.357 | [error] node_modules/.pnpm/@prisma+client@5.16.1_prisma@5.16.1/node_modules/.prisma/client/query_engine_bg.wasm (1:5): Unexpected eof (Note that you need plugins to import files that are not JavaScript)
00:17:43.357 | at getRollupError (node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
00:17:43.358 | at ParseError.initialise (node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:11332:28)
00:17:43.358 | at convertNode (node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:13082:10)
00:17:43.358 | at convertProgram (node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:12399:12)
00:17:43.359 | at Module.setSource (node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:14246:24)
00:17:43.359 | at async ModuleLoader.addModuleSource (node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:18892:13)
00:17:43.359 |  
00:17:43.359 | [error] node_modules/.pnpm/@prisma+client@5.16.1_prisma@5.16.1/node_modules/.prisma/client/query_engine_bg.wasm (1:5): Unexpected eof (Note that you need plugins to import files that are not JavaScript)

```

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator zod {
  provider         = "zod-prisma-types"
  output           = "./types"
  createInputTypes = false
  addIncludeType   = false
  addSelectType    = false
}
```

```ts
import type { EventHandlerRequest, H3Event } from 'h3'
import { PrismaD1 } from '@prisma/adapter-d1'
import { PrismaClient } from '@prisma/client'

export function useDB(event: H3Event<EventHandlerRequest>): D1Database {
  return event.context.cloudflare.env.db as D1Database
}

let prismaClient: PrismaClient
export function usePrisma(event: H3Event<EventHandlerRequest>) {
  if (!prismaClient) {
    const adapter = new PrismaD1(useDB(event))
    prismaClient = new PrismaClient({ adapter })
  }
  return prismaClient
}

```

### Environment & setup

- OS: macOs
- Database: CloudflareD1
- Node.js version: 20

### Prisma Version

```
prisma                  : 5.16.1
@prisma/client          : 5.16.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.13.1
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/.pnpm/@prisma+engines@5.16.1/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/.pnpm/@prisma+engines@5.16.1/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0
Preview Features        : driverAdapters
```

**Comment by zou-yu** [comment]
By the way: dev server is working well

**Comment by zou-yu** [comment]
Solved this issue by add following code to nuxt.config.ts
```
nitro: {
   experimental: {
      wasm: true,
    }
  }
```
