### ISSUE TITLE
Prisma fails to reconnect after being unfrozen in a Lambda instance

### ISSUE THREAD

**Issue by zmillman** [prisma/prisma#24718]
### Bug description

I've been getting intermittent (~3% of requests) `P1001` errors in my Lambda functions that look like this:

```
Invalid `prisma.session.findUnique()` invocation:

Can't reach database server at `<db-name>.cluster-czu26m4ieacl.us-west-2.rds.amazonaws.com:5432`

Please make sure your database server is running at `<db-name>.us-west-2.rds.amazonaws.com:5432`.
    at In.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:122:7177)
    at In.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:122:6211)
    at In.request (/var/task/node_modules/@prisma/client/runtime/library.js:122:5919)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async readData (file:///var/task/index.js:237966:23)
    at async Object.getSession (file:///var/task/index.js:126398:29)
    at async Authenticator2.isAuthenticated (file:///var/task/index.js:136666:76)
    at async authenticatedUserOrNull (file:///var/task/index.js:238281:23)
    at async authenticatedUser (file:///var/task/index.js:238267:16)
    at async Promise.all (index 0) {
  clientVersion: '5.14.0',
  errorCode: undefined
}
````

The strangest aspect is that the errors are occurring a full 7 seconds after the Lambda invocation finished:
```
2024-07-03T21:44:56.037Z	REPORT RequestId: 82ec3b58-1618-488d-91a4-a29491e7dc40	Duration: 989.84 ms	Billed Duration: 990 ms	Memory Size: 256 MB	Max Memory Used: 182 MB	...
....
2024-07-03T21:45:03.337Z	82ec3b58-1618-488d-91a4-a29491e7dc40	ERROR	Unhandled Promise Rejection
```

There are also a number of `Connection reset by peer` in the RDS error logs which seem correlated.
```
2024-07-03 21:45:03 UTC:10.0.165.245(34030):[unknown]@[unknown]:[19428]:LOG: could not accept SSL connection: Connection reset by peer
...
2024-07-03 21:50:52 UTC:10.0.165.245(7593):postgres@postgres:[19431]:LOG: could not receive data from client: Connection reset by peer
```

My suspicion is that something like this is happening:

* `t = 44:55` - Invocation 1 begins, creating a persistent DB connection to postgres over TCP
* `t = 44:56` - Invocation 1 finished, reported to console
* `t = 44:57` - Amazon freezes the execution environment preventing TCP keep-alive from being delivered ([reddit discussion](https://www.reddit.com/r/aws/comments/n8xlux/frozen_aws_lambda_how_does_keepalive_mechanisms/))
* `t = 45:00`(ish) - TCP connection is reset due to failed keep-alive requests
* `t = 45:02` - Invocation 2 begins, Amazon unfreezes the execution environemnt (which is unaware that the postgres TCP connection has been reset)
* `t = 45:03` - Prisma issues query, which fails with `P1001` "Can't reach database server" error

Has anyone else encountered this issue? I'm at a total loss for what to do 😅

### How to reproduce

Deploy an AWS Lambda (I'm using the Node 20.x runtime) with the `server-lambda.js` code below.

Make requests until you encounter the error in the logs.

This requires some non-deterministic combination of triggering concurrent executions & pausing between requests that I can't reliably reproduce. (AWS doesn't document the exact triggers that cause them to freeze a Lambda or what happens with keep-alive packets when frozen)

### Expected behavior

I wouldn't expect any connection errors, or for Prisma to gracefully recover when connections are reset.

### Prisma information

```prisma
generator client {
  provider      = "prisma-client-js"
  // "rhel-openssl-3.0.x" is for AWS runtime Node 20.X
  // https://www.prisma.io/docs/orm/reference/environment-variables-reference#prisma_cli_binary_targets
  binaryTargets = ["native", "rhel-openssl-3.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

/// Data stored for a browser session
model Session {
  /// Unique session id (the only thing that should be stored in cookies)
  id        String    @id @default(uuid()) @db.Uuid
  /// The serialized session data (including flash data)
  data      Json
}
```

```ts
// server-lambda.js
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient({
  // Use connection_limit=1 per Prisma docs
  datasourceUrl: process.env.DATABASE_URL
});

// set up connection before invoking handlers
await prisma.$connect();

export const handler = async function (event) {
  const session = await prisma.session.findUnique({
    where: {id: event.id}
  });
  return session;
}
```

### Environment & setup

- OS: [Amazon Linux 2023](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)
- Database: Postgres (Aurora Serverless v2)
- Node.js version: [20.X runtime](https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/)

### Prisma Version

```
5.14.0
```

**Comment by zmillman** [comment]
I'm currently trying this as a hack to see if the connection errors go away. Last 24 hours have been error-free, but since I don't have a clear repro I can't validate that this is an effective workaround.

```ts
export const handler = async function (event) {
  // HACK: ensure Prisma recovered from any reset TCP connections (https://github.com/prisma/prisma/issues/24718)
  await prisma.$connect();

  const session = await prisma.session.findUnique({
    where: {id: event.id}
  });
  return session;
}
```

**Comment by nurul3101** [comment]
Hello @zmillman 👋 

Thank you for taking the time to report the issue.

Have you observed any errors now, after the workaround you added?

Also, I am curious, did you tried out using [Prisma Accelerate](https://www.prisma.io/data-platform/accelerate) as a connection pooler, this may prevent the database connection errors you were observing.

**Comment by zmillman** [comment]
> Have you observed any errors now, after the workaround you added?

Still no new errors and I've had a few thousand requests. Perhaps `$connect` has extra retry handling that deals with reset TCP sockets?

> Also, I am curious, did you tried out using [Prisma Accelerate](https://www.prisma.io/data-platform/accelerate) as a connection pooler, this may prevent the database connection errors you were observing

Nope, but I wouldn't expect that to help. The DB cluster never went above ~10 active connections and the documented limit for my provisioned size is ~200.
