### ISSUE TITLE
TypeError thrown when calling Pulse `stream()` API with AND filter

### ISSUE THREAD

**Issue by ymc9** [prisma/prisma#24720]
### Bug description

When calling Pulse's `stream()` API with a filter containing a logical combination (e.g., AND), a TypeError is thrown:

```
node_modules/@prisma/extension-pulse/dist/cjs/serializer.js:105
            serialized[field] = this.#serializeField(field, fields[field]);
                                     ^
TypeError: Cannot read properties of undefined (reading 'PulseSubscriptionFilterSerializer')
    at #serializeFields (/private/tmp/xata-pulse/node_modules/@prisma/extension-pulse/dist/cjs/serializer.js:105:38)
    at Array.map (<anonymous>)
    at PulseSubscriptionFilterSerializer.#serializeFields (/private/tmp/xata-pulse/node_modules/@prisma/extension-pulse/dist/cjs/serializer.js:102:51)
    at PulseSubscriptionFilterSerializer.serialize (/private/tmp/xata-pulse/node_modules/@prisma/extension-pulse/dist/cjs/serializer.js:79:54)
    at establishSubscription (/private/tmp/xata-pulse/node_modules/@prisma/extension-pulse/dist/cjs/entry.node.js:70:27)
    at Proxy.stream (/private/tmp/xata-pulse/node_modules/@prisma/extension-pulse/dist/cjs/entry.node.js:56:32)
    at /private/tmp/xata-pulse/index.ts:13:38
    at Generator.next (<anonymous>)
    at /private/tmp/xata-pulse/index.ts:8:71
    at new Promise (<anonymous>)
```

It happens to `scribe()` too.

### How to reproduce

1. Create a Pulse starter project using `npx try-prisma@latest`
2. Set up database URL and Pulse key
3. Change the TS code to the following

```ts
import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { withPulse } from '@prisma/extension-pulse';

process.on('SIGINT', () => {
    process.exit(0);
});

const apiKey: string = process.env.PULSE_API_KEY ?? '';
const prisma = new PrismaClient().$extends(withPulse({ apiKey: apiKey }));

async function main() {
    const stream = await prisma.user.stream({
        create: { AND: [{ name: { contains: 'abc' } }] },
    });

    process.on('exit', (code) => {
        stream.stop();
    });

    for await (const event of stream) {
        console.log('just received an event:', event);
    }
}

main();
```

### Expected behavior

No error is thrown and the filter works.

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
}
```

```ts
import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { withPulse } from '@prisma/extension-pulse';

process.on('SIGINT', () => {
    process.exit(0);
});

const apiKey: string = process.env.PULSE_API_KEY ?? '';
const prisma = new PrismaClient().$extends(withPulse({ apiKey: apiKey }));

async function main() {
    const stream = await prisma.user.stream({
        create: { AND: [{ name: { contains: 'abc' } }] },
    });

    process.on('exit', (code) => {
        stream.stop();
    });

    for await (const event of stream) {
        console.log('just received an event:', event);
    }
}

main();
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL (Supabase)
- Node.js version: v20.10.0

### Prisma Version

```
prisma                  : 5.16.1
@prisma/client          : 5.16.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v20.10.0
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0
```

**Comment by nurul3101** [comment]
Hello @ymc9 👋 

Thank you for taking the time to report this issue.

I am able to reproduce the issue. I have added the reproduction here: https://github.com/nurul3101/prisma-pulse-filter-bug

We have informed our engineering team and they will look into this as soon as possible. Are you blocked due to this bug?

**Comment by nurul3101** [comment]
@ymc9 Can you try out the latest "@prisma/extension-pulse" version `1.2.0`?

This should fix the issue you were observing.

https://www.npmjs.com/package/@prisma/extension-pulse

**Comment by ymc9** [comment]
Thanks @nurul3101, and sorry for the late response. I can confirm v1.2.0 is working now.

Btw, is the old `subscribe` API still supported? I frequently run into the following error when using it (what Neon):

```
P6101 The connection to the database was momentarily interrupted. Prisma Pulse will attempt to reconnect to the database.
```

**Comment by ymc9** [comment]
Correction: the P6101 error happens to `stream` too, just seems to be less often with it. Is it possible to be an issue on Neon side?

**Comment by ymc9** [comment]
I can see an error on the console too

<img width="1288" alt="image" src="https://github.com/user-attachments/assets/8392dc47-4624-4f0c-b174-e407f1804663">

**Comment by nurul3101** [comment]
@ymc9 Does the error go away or are you still getting the same error on console?

**Comment by Amirnajafi** [comment]
I have the same issue with the Prisma pulse when I call stream function and I try i with latest client and pulse version

**Comment by ymc9** [comment]
> @ymc9 Does the error go away or are you still getting the same error on console?
> 
> 

Yes, I still run into it sporadically in my test cases.

**Comment by abshirahmed** [comment]
yep, I'm getting the same `P6101 The connection to the database was momentarily interrupted. Prisma Pulse will attempt to reconnect to the database.` error
