### ISSUE TITLE
ConnectorError: 42P05 occurs occurs frequently

### ISSUE THREAD

**Issue by localer** [prisma/prisma#24798]
### Bug description

`ConnectorError: 42P05` occurs frequently
(I'm using superbase as my database, and restarting it from the dashboard fixes it temporarily. Then the error starts occurring again right away.)

### How to reproduce

1. run: `bunx prisma generate --no-engine`
2. Run the following code:
```ts
const threads = await prisma.thread.findMany({
  include: {
    user: {
      select: {
        avatar: true,
        nickname: true,
        username: true
      }
    },
  },
  orderBy: {
    id: "desc"
  },
  where: {
    status: {
      not: "hidden"
    }
  },
  cacheStrategy: {
    ttl: 60,
  }
})
```

### Expected behavior

`ConnectorError: 42P05` does not occur and information is obtained correctly

### Prisma information

```prisma
// Add your schema.prisma

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["omitApi"]
}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}

// ユーザーデータ
model User {
  // 固有ID
  id       Int    @id @default(autoincrement())
  // 認証情報
  email    String @unique
  password String

  // 表示
  username  String   @unique
  nickname  String
  avatar    String?
  // アカウント作成日時
  createdAt DateTime @default(now())
  // ステータス
  status    Status   @default(EMAIL_VERIFICATION_PENDING)

  // リレーション
  threads  Thread[]
  messages ThreadMessage[]
  roles    Role[]          @relation("RoleToUser")
}

enum Status {
  // メールアドレス認証確認中(未認証)
  EMAIL_VERIFICATION_PENDING
  // 一般(認証済み)
  VERIFIED
  // 学生(学生認証済み)
  STUDENT_VERIFIED
  // アカウント停止
  BANNED
}

// ロール役職
model Role {
  // 固有ID
  id                Int              @id @default(autoincrement())
  // 表示
  name              String
  description       String?
  // 権限
  availableCategory ThreadCategory[] @relation("RoleToThreadCategory")

  // meta
  users User[] @relation("RoleToUser")
}

model Thread {
  id            Int             @id @default(autoincrement())
  userId        Int
  title         String
  content       String
  createdAt     DateTime        @default(now())
  categoryId    Int
  status        thread_status   @default(normal)
  contentCached String
  user          User            @relation(fields: [userId], references: [id])
  category      ThreadCategory  @relation(fields: [categoryId], references: [id])
  message       ThreadMessage[]
}
```

```ts
// Add your code using Prisma Client

/**
 * - prepared statement \"s0\" already exists #11643
 * > (Prisma ConnectorError / Code: 42P05)
 * @link {@see https://github.com/prisma/prisma/issues/11643}
 * 
 * - セキュリティ対策
 * @link {@see https://www.prisma.io/docs/orm/prisma-client/queries/excluding-fields#excluding-the-password-field-without-using-omit}
 */

import { PrismaClient } from '@prisma/client';
import { withAccelerate } from '@prisma/extension-accelerate';

export const prisma = new PrismaClient({
  omit: {
    user: {
      password: true
    }
  }
}).$extends(withAccelerate());

```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma                  : 5.16.2
@prisma/client          : 5.16.2
Computed binaryTarget   : debian-openssl-1.1.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.11.1
Query Engine (Node-API) : libquery-engine 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli 34ace0eb2704183d2c05b60b52fba5c43c13f303 (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.16.0-24.34ace0eb2704183d2c05b60b52fba5c43c13f303
Default Engines Hash    : 34ace0eb2704183d2c05b60b52fba5c43c13f303
Studio                  : 0.502.0
Preview Features        : omitApi
```

**Comment by Malekzie** [comment]
I'm getting the same error as well, with accelerate added as well as omitApi, thought it was accelerate bugging me

**Comment by localer** [comment]
What is neon?

**Comment by Malekzie** [comment]
A postgresql database. I just used it so I can't say much to compare it to supabase as supabase was my go to before this error. Im going to migrate back once this is fixed, for now Ill go for neon.

**Comment by localer** [comment]
I see, I will give it a try.

**Comment by SevInf** [comment]
Hey @localer, just to confirm once more: running the provided query once is enough to reproduce the issue? Or it needs to be run continuously? Does it reproduce without Accelerate, with the direct connection to the database?

**Comment by localer** [comment]
Use Accelerate. After running the query several times, the error will start occurring until restarted from the supabase dashboard.

**Comment by localer** [comment]
So far (since migrating from superbase to neon) I haven't seen any recurrence of the error. Thank you for letting me know, @Malekzie .

**Comment by SevInf** [comment]
@localer do I understand it correctly, that without Accelerate it all works as expected?

**Comment by Malekzie** [comment]
I believe that the problem lies with supabase. Ever since I used neon, I havent been getting any ConnectorError: 42P05.

**Comment by kevinreber** [comment]
Also have a similar `ConnectorError` issue during development – only happens local, deployed works fine
My tech stack is:
- Built with Remix
- Prisma for DB management
- DB hosted on Supabase

I'm getting an error for every query being made - errors below
```sh
 💿  remix dev

 info  building...
 info  built (2.1s)
[remix-serve] http://localhost:3000 (http://192.168.86.112:3000)
prisma:info Starting a postgresql pool with 25 connections.

prisma:query - 90ms - SELECT COUNT(*) FROM (SELECT "public"."Collection"."id" FROM "public"."Collection" WHERE "public"."Collection"."userId" = $1 OFFSET $2) AS "sub"
prisma:error 
Invalid `prisma.collection.count()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s0\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
prisma:query - 88ms - SELECT "public"."User"."id", "public"."User"."name", "public"."User"."username", "public"."User"."email", "public"."User"."image", "public"."User"."createdAt", "public"."User"."credits" FROM "public"."User" WHERE ("public"."User"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s1\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s1\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at _n.handleRequestError (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:7939)
    at _n.handleAndLogRequestError (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:7057)
    at _n.request (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:6741)
    at l (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:130:9355)
    at getLoggedInUserSSOData (file:///Users/kreber/Documents/code/personal/ai-icon-generator/build/index.js?t=1723450348975.0032:648:18)
    at loader (file:///Users/kreber/Documents/code/personal/ai-icon-generator/build/index.js?t=1723450348975.0032:4711:25)
    at Object.callRouteLoaderRR (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
    at callLoaderOrAction (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/router/router.ts:3842:16)
    at async Promise.all (index 0)
    at loadRouteData (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/router/router.ts:3153:19) {
  clientVersion: '5.18.0'
}
PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s1\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at _n.handleRequestError (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:7939)
    at _n.handleAndLogRequestError (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:7057)
    at _n.request (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:121:6741)
    at l (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@prisma/client/runtime/library.js:130:9355)
    at getLoggedInUserSSOData (file:///Users/kreber/Documents/code/personal/ai-icon-generator/build/index.js?t=1723450348975.0032:648:18)
    at loader (file:///Users/kreber/Documents/code/personal/ai-icon-generator/build/index.js?t=1723450348975.0032:4711:25)
    at Object.callRouteLoaderRR (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/server-runtime/dist/data.js:52:16)
    at callLoaderOrAction (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/router/router.ts:3842:16)
    at async Promise.all (index 0)
    at loadRouteData (/Users/kreber/Documents/code/personal/ai-icon-generator/node_modules/@remix-run/router/router.ts:3153:19) {
  clientVersion: '5.18.0'
}
```

Confirmed that there isn't any whitelisting setup in Supabase
```
~ npx supabase network-restrictions --project-ref XXXXXXXXX get --experimental 
DB Allowed IPv4 CIDRs: <nil>
DB Allowed IPv6 CIDRs: <nil>
```

`prisma/schema.prisma`
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id           String        @id @default(cuid())
  name         String?
  username     String       @unique
  email        String       @unique
  password     Password?
  image        String?
  credits      Int           @default(5)
  accounts     Account[]
  sessions     Session[]
  images       Image[]
  createdAt    DateTime      @default(now())
  updatedAt    DateTime?     @updatedAt
  comments     Comment[]
  imageLikes   ImageLike[]
  commentLikes CommentLike[]
  collections  Collection[]
  roles        Role[]
}

model Collection {
  id          String               @id @default(cuid())
  createdAt   DateTime             @default(now())
  updatedAt   DateTime             @updatedAt
  title       String
  description String?
  user        User                 @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId      String
  images      CollectionHasImage[]

  @@index([userId])
}

.....
```

Example of queries that are failing
```ts
export const getLoggedInUserSSOData = async (
  userGoogleData: UserGoogleData,
  request: Request,
) => {
  const userId = userGoogleData.id;
  let userData = await prisma.user.findUnique({
    where: { id: userId },
    select: {
      id: true,
      name: true,
      username: true,
      email: true,
      image: true,
      createdAt: true,
      credits: true,
      collections: {
        select: {
          id: true,
          title: true,
          description: true,
          images: {
            select: {
              imageId: true,
            },
          },
        },
      },
      roles: {
        select: {
          name: true,
          permissions: {
            select: {
              action: true,
              entity: true,
              access: true,
            },
          },
        },
      },
    },
  });

  if (!userData?.id) {
    const { name, email, picture } = userGoogleData._json;

    // If new user is created, no collections will exist
    // @ts-ignore
    userData = await prisma.user.create({
      data: {
        id: userId,
        name,
        username: userGoogleData.displayName,
        email,
        image: picture,
        roles: { connect: { name: "user" } },
      },
    });
  }

  return userData;
};


export const getUserCollections = async (
  userId: string,
  page = DEFAULT_CURRENT_PAGE,
  pageSize = DEFAULT_PAGE_SIZE,
) => {
  const count = await prisma.collection.count({
    where: {
      userId,
    },
  });
  const collections = await prisma.collection.findMany({
    take: pageSize,
    skip: (page - 1) * pageSize,
    where: {
      userId,
    },
    orderBy: {
      createdAt: "desc",
    },
    select: {
      id: true,
      title: true,
      description: true,
      user: {
        select: {
          id: true,
          username: true,
        },
      },
      createdAt: true,
      updatedAt: true,
      images: {
        select: {
          id: true,
        },
      },
    },
  });

  return { collections, count };
};

```


Will also create a thread in Supabase to see if anyone else is having similar issues

**Comment by Weakky** [comment]
Hey @kevinreber, it would be super helpful if you could provide us with a contained repository that reproduces your issue. Thank you 🙏

**Comment by kevinreber** [comment]
@Weakky 
here's my repo: https://github.com/kevinreber/ai-icon-generator

**Comment by programmeranish** [comment]
Is this issue fixed guys?

**Comment by nurul3101** [comment]
The repo mentioned in the above [comment](https://github.com/prisma/prisma/issues/24798#issuecomment-2287798089) seems to be not available anymore.

I tried reproducing the error by creating a minimal repository: https://github.com/nurul3101/prisma-issue-24798

I created 10,000 records via Accelerate on a Supabase database, but did not encounter this error. I made sure to use `omitApi` feature as reported by @localer. 

<img width="1136" alt="Image" src="https://github.com/user-attachments/assets/e359eded-f9ad-4b94-b88c-39c7eb6e37fc" />

Please let us know in case there is any other way to try to reproduce this.

**Comment by awais144506** [comment]
Go to Project Settings and restart Project. But its repetive process, evrytime you add functionality.
