### ISSUE TITLE
Add support to android? Everything works fine in termux except prisma

### ISSUE THREAD

**Issue by FerielNot1** [prisma/prisma#24848]
## Problem

I always use android with termux to raise my skills in places where I can't open a pc like school. The problem is that everything works fine except prisma
I setup postgresql and svelte kit template project and everything is OK until I did
```
template $ npx prisma migrate dev --name init
prisma:warn Prisma detected unknown OS "android" and may not work as expected. Defaulting to "linux".
prisma:warn Prisma detected unknown OS "android" and may not work as expected. Defaulting to "linux".
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "dev", schema "public" at "0.0.0.0:5432"

Error: Schema engine error:

template $ npx prisma -v
prisma:warn Prisma detected unknown OS "android" and may not work as expected. Defaulting to "linux".
Environment variables loaded from .env
prisma:warn Prisma detected unknown OS "android" and may not work as expected. Defaulting to "linux".
Error: Unable to require(`/data/data/com.termux/files/home/work/prv/template/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`).
The Prisma engines do not seem to be compatible with your system. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: dlopen failed: "/data/data/com.termux/files/home/work/prv/template/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node" is for EM_X86_64 (62) instead of EM_AARCH64 (183)
    at Jte (/data/data/com.termux/files/home/work/prv/template/node_modules/prisma/build/index.js:284:116)
    at i7e (/data/data/com.termux/files/home/work/prv/template/node_modules/prisma/build/index.js:284:269)
Error: Command failed with exit code 1: /data/data/com.termux/files/home/work/prv/template/node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x --version
/data/data/com.termux/files/home/work/prv/template/node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x[2]: syntax error: unexpected ';'
    at KAe (/data/data/com.termux/files/home/work/prv/template/node_modules/prisma/build/index.js:5:57)
    at /data/data/com.termux/files/home/work/prv/template/node_modules/prisma/build/index.js:5:10625
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async i7e (/data/data/com.termux/files/home/work/prv/template/node_modules/prisma/build/index.js:284:343) {
  shortMessage: 'Command failed with exit code 1: /data/data/com.termux/files/home/work/prv/template/node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x --version',
  command: '/data/data/com.termux/files/home/work/prv/template/node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x --version',
  escapedCommand: '"/data/data/com.termux/files/home/work/prv/template/node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x" --version',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "/data/data/com.termux/files/home/work/prv/template/node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x[2]: syntax error: unexpected ';'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
prisma                  : 5.17.0
@prisma/client          : 5.17.0
Computed binaryTarget   : debian-openssl-1.1.x
Operating System        : android
Architecture            : arm64
Node.js                 : v22.4.1
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.17.0-31.393aa359c9ad4a4bb28630fb5613f9c281cde053
Default Engines Hash    : 393aa359c9ad4a4bb28630fb5613f9c281cde053
Studio                  : 0.502.0
~/.../prv/template $ node -v
v22.4.1
```

## Suggested solution

I have no idea to be honest.
I am in a vacance and I was going to report this as bug but I know that android is not supported so I am asking for it as a feature. 
Based on this line
`"/data/data/com.termux/files/home/work/prv/template/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node" is for EM_X86_64 (62) instead of EM_AARCH64 (183)` it's a release architecture problem and I don't know what to do with it what should I rebuild or idk

**Comment by fatinghenji** [comment]
Encountered the same problem, looking forward to a solution

**Comment by thisjt** [comment]
Sadly I don't think they'll be compiling a binary that will be compatible with termux. Installing Linux on top of termux would be your best bet.

What worked for me is I installed alpine on termux using https://github.com/Hax4us/TermuxAlpine, prisma will instead download a compatible Linux binary that will work for this platform.
