### ISSUE TITLE
[5.18] `libquery_engine-linux-musl-openssl-3.0.x.so.node` exists but its version is `libquery-engine`  and we expect `4c784e32044a8a016d99474bd02a3b6123742169`

### ISSUE THREAD

**Issue by darthmaim** [prisma/prisma#24971]
### Bug description

When trying to update to 5.18 I got this error in one of my docker containers:

```raw
Error: Can't write to /app/node_modules/@prisma/engines please make sure you install "prisma" with the right permissions.
```

Enabling `DEBUG=*` produces this log:

```raw
prisma:engines binaries to download libquery-engine, schema-engine +346ms
prisma:get-platform Found distro info:
{
  "targetDistro": "musl",
  "familyDistro": "alpine",
  "originalDistro": "alpine"
} +10ms
prisma:get-platform Don't know any platform-specific paths for "alpine" on x64 (x86_64) +1ms
prisma:get-platform Falling back to "ldconfig" and other generic paths +0ms
prisma:get-platform Found libssl.so file using "ldconfig" or other generic paths: libssl.so.3 +12ms
prisma:get-platform The parsed libssl version is: 3.0.x +1ms
prisma:fetch-engine:download file /app/node_modules/@prisma/engines/libquery_engine-linux-musl-openssl-3.0.x.so.node exists but its version is libquery-engine  and we expect 4c784e32044a8a016d99474bd02a3b6123742169 +11ms
prisma:fetch-engine:download file /app/node_modules/@prisma/engines/schema-engine-linux-musl-openssl-3.0.x exists but its version is schema-engine-cli  and we expect 4c784e32044a8a016d99474bd02a3b6123742169 +13ms
prisma:fetch-engine:download https://binaries.prisma.sh/all_commits/4c784e32044a8a016d99474bd02a3b6123742169/linux-musl-openssl-3.0.x/libquery_engine.so.node.gz will be downloaded to /app/node_modules/@prisma/engines/libquery_engine-linux-musl-openssl-3.0.x.so.node +1ms
prisma:fetch-engine:download https://binaries.prisma.sh/all_commits/4c784e32044a8a016d99474bd02a3b6123742169/linux-musl-openssl-3.0.x/schema-engine.gz will be downloaded to /app/node_modules/@prisma/engines/schema-engine-linux-musl-openssl-3.0.x +1ms
Error: Error: Can't write to /app/node_modules/@prisma/engines please make sure you install "prisma" with the right permissions.
    at downloadBinary (/app/node_modules/@prisma/fetch-engine/dist/chunk-IDYGZR4L.js:2330:13)
    at /app/node_modules/@prisma/fetch-engine/dist/chunk-IDYGZR4L.js:2159:14
    at Array.map (<anonymous>)
    at download (/app/node_modules/@prisma/fetch-engine/dist/chunk-IDYGZR4L.js:2151:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ensureBinariesExist (/app/node_modules/@prisma/engines/dist/index.js:74:3)
    at async Ra.parse (/app/node_modules/prisma/build/index.js:1276:835)
    at async lPt (/app/node_modules/prisma/build/index.js:1999:1678)
```

The same on 5.17 instead finds the correct engine file and just continues:

```raw
prisma:engines binaries to download libquery-engine, schema-engine +391ms
prisma:get-platform Found distro info:
{
  "targetDistro": "musl",
  "familyDistro": "alpine",
  "originalDistro": "alpine"
} +10ms
prisma:get-platform Don't know any platform-specific paths for "alpine" on x64 (x86_64) +1ms
prisma:get-platform Falling back to "ldconfig" and other generic paths +1ms
prisma:get-platform Found libssl.so file using "ldconfig" or other generic paths: libssl.so.3 +12ms
prisma:get-platform The parsed libssl version is: 3.0.x +1ms
...
```

I can of course update the permissions so prisma is able to download the engine file, but I'm wondering why this did not happen before.

### How to reproduce

1. Save this as `Dockerfile`:  
    ```Dockerfile
	# syntax=docker/dockerfile:1.9
	
	ARG node_version=20.16.0-alpine
	ARG prisma_version=5.18.0
	
	FROM node:${node_version} AS source
	WORKDIR /app
	
	ENV NODE_ENV=production
	
	RUN addgroup --system --gid 1001 nodejs
	RUN adduser --system --uid 1001 worker
	
	ARG prisma_version
	RUN npm i prisma@${prisma_version}
	
	USER worker
	
	ENV DEBUG="*"
	CMD [ "./node_modules/.bin/prisma", "-v" ]
    ```
2. Build the image using `docker build -t prisma-issue-24971 .`
3. Run the container using `docker run --rm prisma-issue-24971`

### Expected behavior

The correct engine files should be included when installing prisma.

### Prisma information

\-

### Environment & setup

See Dockerfile

### Prisma Version

Can't even run `prisma -v` in the container because it wants to download the engine file.

```raw
prisma: 5.18.0
```

But this is the output for 5.17.0 (which does work)

```raw
prisma                  : 5.17.0
@prisma/client          : Not found
Computed binaryTarget   : linux-musl-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.16.0
Query Engine (Node-API) : libquery-engine 393aa359c9ad4a4bb28630fb5613f9c281cde053 (at node_modules/@prisma/engines/libquery_engine-linux-musl-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 393aa359c9ad4a4bb28630fb5613f9c281cde053 (at node_modules/@prisma/engines/schema-engine-linux-musl-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.17.0-31.393aa359c9ad4a4bb28630fb5613f9c281cde053
Default Engines Hash    : 393aa359c9ad4a4bb28630fb5613f9c281cde053
Studio                  : 0.502.0
```

**Comment by eatsleepcoderepeat** [comment]
Can confirm, same versions as you use.
As workaround, you could set permissions to the node_modules in your Dockerfile, which works.
(RUN chown -R worker:nodejs /app/node_modules)

**Comment by thgala** [comment]
I can confirm this. Same issue with `5.18`; downgrading to `5.17` solves the error.

**Comment by rchoffar** [comment]
Same here #25020 , sorry for dup
