### ISSUE TITLE
Breaking change after updating from 5.17 to 5.18

### ISSUE THREAD

**Issue by rchoffar** [prisma/prisma#25020]
### Bug description

After updating from 5.17 to 5.18 i notice i can no more run `npx prisma migrate deploy` inside my docker image

I have an error: `Error: Can't write to /home/node/node_modules/@prisma/engines please make sure you install "prisma" with the right permissions.`

Look like the command is now doing changes inside node_modules, but for security purpose we can't allow our runtime user to write inside node_modules

I feed like this is an unexpected behavior and should not append

DEBUG=*
```
prisma:engines binaries to download libquery-engine, schema-engine +113ms
prisma:get-platform Found distro info:
{
  "targetDistro": "musl",
  "familyDistro": "alpine",
  "originalDistro": "alpine"
} +3ms
prisma:get-platform Don't know any platform-specific paths for "alpine" on arm64 (aarch64) +0ms
prisma:get-platform Falling back to "ldconfig" and other generic paths +0ms
prisma:get-platform Found libssl.so file using "ldconfig" or other generic paths: libssl.so.3 +4ms
prisma:get-platform The parsed libssl version is: 3.0.x +0ms
prisma:fetch-engine:cache-dir The following error is being caught and just there for debugging: +1ms
prisma:fetch-engine:cache-dir {
  "errno": -2,
  "code": "ENOENT",
  "syscall": "mkdir",
  "path": "/home/node/.cache"
} +0ms
prisma:fetch-engine:download file /home/node/node_modules/@prisma/engines/libquery_engine-linux-musl-arm64-openssl-3.0.x.so.node exists but its version is libquery-engine  and we expect 4c784e32044a8a016d99474bd02a3b6123742169 +6ms
prisma:fetch-engine:cache-dir The following error is being caught and just there for debugging: +1ms
prisma:fetch-engine:cache-dir {
  "errno": -2,
  "code": "ENOENT",
  "syscall": "mkdir",
  "path": "/home/node/.cache"
} +0ms
prisma:fetch-engine:download file /home/node/node_modules/@prisma/engines/schema-engine-linux-musl-arm64-openssl-3.0.x exists but its version is schema-engine-cli  and we expect 4c784e32044a8a016d99474bd02a3b6123742169 +6ms
prisma:fetch-engine:download https://binaries.prisma.sh/all_commits/4c784e32044a8a016d99474bd02a3b6123742169/linux-musl-arm64-openssl-3.0.x/libquery_engine.so.node.gz will be downloaded to /home/node/node_modules/@prisma/engines/libquery_engine-linux-musl-arm64-openssl-3.0.x.so.node +0ms
prisma:fetch-engine:download https://binaries.prisma.sh/all_commits/4c784e32044a8a016d99474bd02a3b6123742169/linux-musl-arm64-openssl-3.0.x/schema-engine.gz will be downloaded to /home/node/node_modules/@prisma/engines/schema-engine-linux-musl-arm64-openssl-3.0.x +0ms
Error: Error: Can't write to /home/node/node_modules/@prisma/engines please make sure you install "prisma" with the right permissions.
    at downloadBinary (/home/node/node_modules/@prisma/fetch-engine/dist/chunk-IDYGZR4L.js:2330:13)
    at /home/node/node_modules/@prisma/fetch-engine/dist/chunk-IDYGZR4L.js:2159:14
    at Array.map (<anonymous>)
    at download (/home/node/node_modules/@prisma/fetch-engine/dist/chunk-IDYGZR4L.js:2151:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ensureBinariesExist (/home/node/node_modules/@prisma/engines/dist/index.js:74:3)
    at async Ra.parse (/home/node/node_modules/prisma/build/index.js:1276:835)
    at async lPt (/home/node/node_modules/prisma/build/index.js:1999:1678)
```

### How to reproduce

Here is a simple repo to reproduce:

https://github.com/rchoffar/prisma-breaking-repro

```
docker build . -t prisma-repro
docker run prisma-repro
```

Change version to 5.17 to see there is no issue

### Expected behavior

I expect the command `npx prisma migrate deploy` to not try to write inside node_modules and expect `npx prisma generate` or `npm installl` to install all deps

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Environment & setup

- Alpine 3.20
- PostgreSQL
- 22.3

### Prisma Version

```
5.18
```

**Comment by Kiborgik** [comment]
Have the same, when trying this command from github actions to custom next.js image
```
Run docker compose exec -T nextjs npx prisma migrate deploy
  docker compose exec -T nextjs npx prisma migrate deploy
  shell: /usr/bin/bash -e {0}
Error: Can't write to /app/node_modules/@prisma/engines please make sure you install "prisma" with the right permissions.
Error: Process completed with exit code 1.
```
