### ISSUE TITLE
Add information for PRISMA_CONFIG to the documentation

### ISSUE THREAD

**Issue by marktani** [prisma/prisma#2508]
https://www.prisma.io/forum/t/in-docker-compose-why-is-the-value-of-prisma-config-prefixed-by-a-pipe/3568?u=nilan

**Comment by valentinbe** [comment]
Hi, 
Can't figure out how to configure properly
So far I tried to create a YAML file with the following content:
```yaml
PRISMA_CONFIG: |
    port: 4466
        databases:
            default:
                connector: mysql
                host: mysql
                port: 3306
                user: root
                password: prisma
                migrations: true
```
Then pointing PRISMA_CONFIG_PATH to this file on docker compose gives the following error:

``` sh
Exception in thread "main" java.lang.RuntimeException: Unable to load Prisma config: com.prisma.config.InvalidConfiguration: Expected hash under 'databases' to be non-empty
 	at scala.sys.package$.error(package.scala:27)
 	at com.prisma.config.ConfigLoader$.load(ConfigLoader.scala:40)
 	at com.prisma.local.PrismaLocalDependencies.<init>(PrismaLocalDependencies.scala:40)
 	at com.prisma.local.PrismaLocalMain$.delayedEndpoint$com$prisma$local$PrismaLocalMain$1(PrismaLocalMain.scala:15)
 	at com.prisma.local.PrismaLocalMain$delayedInit$body.apply(PrismaLocalMain.scala:12)
 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
 	at scala.collection.immutable.List.foreach(List.scala:389)
 	at scala.App.main(App.scala:76)
 	at scala.App.main$(App.scala:74)
 	at com.prisma.local.PrismaLocalMain$.main(PrismaLocalMain.scala:12)
 	at com.prisma.local.PrismaLocalMain.main(PrismaLocalMain.scala)
```
Any idea how yaml file should be formatted?

**Comment by valentinbe** [comment]
[Self update]
Looks like the following format works:
```yaml
managementApiSecret: PRISMA_MANAGEMENT_API_SECRET
port: 4466
databases:
    default:
        connector: mysql
        host: mysql
        port: 3306
        user: root
        password: prisma
        migrations: true
```
