### ISSUE TITLE
Query Engine uses `schema.prisma` connection string for initial connection, even when `datasources.db` is set in Prisma Client constructor

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#2509]
Schema:

```
datasource postgresql {
  provider = "postgresql"
  url      = "postgresql://foo"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id      Int     @default(autoincrement()) @id
  email   String  @unique
  name    String?
  role    String?
  storeId Int?
}

model Product {
  id          Int     @default(autoincrement()) @id
  handle      String  @unique
  name        String?
  description String?
  price       Int?
}
```

Code:
```
const express = require('express')
const app = express() 
const port = process.env.PORT || 3000;

// const path = require('path')

const { PrismaClient } = require('@prisma/client')

const prismaPgPlain = new PrismaClient({
  log: ['query', 'info', 'warn'],
  datasources: {
    db: "postgresql://###connectiona###",
  },
  //forceTransactions: true,
})

app.get('/api/pg-plain', async (req, res) => {
  const products = await prismaPgPlain.product.findMany({ first: 4 })
  res.send(JSON.stringify(products))
})

app.listen(port, () =>
  console.log(`Example app listening at http://localhost:${port}`),
)
```

This means that `PrismaClient` should use the supplied connection string only, not what is visible in the schema. 

---

But if I run this server and try to call `/api/pg-plain`, I get the following error message:

```
PS C:\Users\Jan\Documents\throwaway\divyPgBouncer> yarn start
yarn run v1.22.0
warning package.json: No license field
$ node index.js
Example app listening at http://localhost:3000
prisma:info  Starting a postgresql pool with 9 connections.
prisma:info  Started http server on 127.0.0.1:50797
(node:23612) UnhandledPromiseRejectionWarning: Error:
Invalid `prismaPgBouncerPlain.product.findMany()` invocation in
C:\Users\Jan\Documents\throwaway\divyPgBouncer\index.js:31:55

  27   //forceTransactions: true,
  28 })
  29
  30 app.get('/api/pgbouncer-plain', async (req,[object Object], res) => {
→ 31   const products = await prismaPgBouncerPlain.product.findMany(Can't reach database server at `foo`:`5432`

Please make sure your database server is running at `foo`:`5432`.
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\throwaway\divyPgBouncer\node_modules\@prisma\client\runtime\index.js:1:85866)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:23612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This indicates to me that the initial server connection of the QE is probably made to the wrong server, which is very concerning and might lead to a lot of confusion.

**Comment by janpio** [comment]
This issue might be fully invalid, maybe `datasources.db` just does nothing. Investigating.
