### ISSUE TITLE
Query Fails with Invalid API Key Error Despite Correct .env Setup

### ISSUE THREAD

**Issue by HarjjotSinghh** [prisma/prisma#25122]
### Bug description

Despite having `DATABASE_URL` and `DIRECT_DATABASE_URL` correctly set up in the `.env` file, all queries via Prisma ORM fail with an invalid API key error.

### Error Message
```
This request could not be understood by the server: {"type":"UnknownJsonError","body":{"code":"P6002","message":"The provided API Key is invalid. Reason: Validation of API Key failed."}}
```

### Full Error Stack
```
[0] PrismaClientKnownRequestError: 
[0] Invalid `prisma.user.findFirst()` invocation:
[0]
[0]
[0] This request could not be understood by the server: {"type":"UnknownJsonError","body":{"code":"P6002","message":"The provided API Key is invalid. Reason: Validation of API Key failed."}} (The request id was: 8bb0216a4fe05a24)
[0]     at Hr.handleRequestError (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\@prisma\client\runtime\edge.js:20:7987)        
[0]     at Hr.handleAndLogRequestError (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\@prisma\client\runtime\edge.js:20:7295)  
[0]     at Hr.request (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\@prisma\client\runtime\edge.js:20:6985)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[0]     at async l (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\@prisma\client\runtime\edge.js:29:9558)
[0]     at async login (webpack-internal:///(action-browser)/./src/app/(auth)/login/actions.ts:30:30)
[0]     at async D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:418   
[0]     at async rS (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:7978)
[0]     at async r4 (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:41:1256)
[0]     at async doRender (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\base-server.js:1418:30)
[0]     at async cacheEntry.responseCache.get.routeKind (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\base-server.js:1579:28)
[0]     at async DevServer.renderToResponseWithComponentsImpl (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\base-server.js:1487:28)
[0]     at async DevServer.renderPageComponent (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\base-server.js:1911:24)
[0]     at async DevServer.renderToResponseImpl (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\base-server.js:1949:32)
[0]     at async DevServer.pipeImpl (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\base-server.js:916:25)     
[0]     at async NextNodeServer.handleCatchallRenderRequest (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\next-server.js:272:17)
[0]     at async DevServer.handleRequestImpl (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\base-server.js:812:17)
[0]     at async D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\dev\next-dev-server.js:339:20
[0]     at async Span.traceAsyncFn (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\trace\trace.js:154:20)
[0]     at async DevServer.handleRequest (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
[0]     at async invokeRender (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\lib\router-server.js:173:21)     
[0]     at async handleRequest (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\lib\router-server.js:350:24)    
[0]     at async requestHandlerImpl (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\lib\router-server.js:374:13)
[0]     at async Server.requestListener (D:\Projects\Avocodos\avocodos-web\frontend\node_modules\next\dist\server\lib\start-server.js:141:13) {
[0]   code: 'P5000',
[0]   clientVersion: '5.20.0-dev.2',
[0]   meta: { modelName: 'User' }
[0] }
```

### Steps Taken

1. Verified correct setup of `DATABASE_URL` and `DIRECT_DATABASE_URL` in `.env` file.
2. Recreated the project.
3. Followed the tutorial for setting up Accelerate and verified multiple times.

### Question

Does anyone know what might be causing this issue? Any help or suggestions would be greatly appreciated.

### How to reproduce

N/A

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["fullTextSearch"]
}

datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_DATABASE_URL")
}
```

```ts
import { PrismaClient } from "@prisma/client/edge";
import { withAccelerate } from '@prisma/extension-accelerate'

const prismaClientSingleton = () => {
  return new PrismaClient().$extends(withAccelerate())
};

declare global {
  var prisma: ReturnType<typeof prismaClientSingleton> | undefined;
}

const prisma =
  global.prisma ??
  (typeof window === 'undefined' ? prismaClientSingleton() : undefined);

if (process.env.NODE_ENV !== "production") global.prisma = prisma;

export default prisma;

```

### Environment & setup

- OS: Windows 11
- Database: Tembo
- Node.js version: v22.7.0

### Prisma Version

```
prisma                  : 5.20.0-dev.2
@prisma/client          : 5.20.0-dev.2
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v22.7.0
Query Engine (Node-API) : libquery-engine 5fe21811a6ba0b952a3bc71400666511fe3b902f (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 5fe21811a6ba0b952a3bc71400666511fe3b902f (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.19.0-31.5fe21811a6ba0b952a3bc71400666511fe3b902f
Default Engines Hash    : 5fe21811a6ba0b952a3bc71400666511fe3b902f
Studio                  : 0.502.0
Preview Features        : fullTextSearch
```

**Comment by nurul3101** [comment]
@HarjjotSinghh Can you please send us an email on support@prisma.io from the email id with which you have created an account on Prisma Data Platform. This would allow us to fetch your project/environment details easily and help in investigating.

**Comment by nurul3101** [comment]
Based on the error message, it is likely that the value of DATABASE_URL is in an incorrect format. The value of DATABASE_URL should be `"prisma://accelerate.prisma-data.net/?api_key=__API_KEY__"`, where `__API_KEY__` would be the API key you get from the Prisma console. The API Key would typically look like "eyJhbGci...".

I would recommend checking the DATABASE_URL again and verifying if it is in correct format.

**Comment by HarjjotSinghh** [comment]
Hey @nurul3101, the error seems to have resolved automatically without me doing anything specific at all. When I first created my accelerate instance, it worked fine for 5 minutes and then I randomly got the `Invalid API Key` error, which I tried my best to debug for about 2 hours. After almost giving up on it, it randomly started working. I have no idea what it could be but I am more than happy to share any details you might need from my end, even though the error is now resolved.

I will send an email to `support@prisma.com` from the account that I used to create the accelerate instance.

**Comment by zhyd1997** [comment]
I encountered the same issue, resolved by generating a new secret in console.prisma.io

<img width="1112" height="278" alt="Image" src="https://github.com/user-attachments/assets/2cdc2262-6d49-4a89-9ad8-0ac794da4a41" />
