### ISSUE TITLE
`typedSQL` causes deployment errors on Cloudflare Workers due to unresolved node modules

### ISSUE THREAD

**Issue by aiji42** [prisma/prisma#25123]
### Bug description

When deploying an application using Prisma's typedSQL on Cloudflare Workers, an error occurs due to unresolved Node.js built-in modules. The application uses the `@prisma/pg-worker` and `@prisma/adapter-pg-worker` with the `driverAdapters` feature enabled. The deployment fails with the following errors when attempting to use the module generated by `@prisma/client/sql`:

```vbnet
✘ [ERROR] Could not resolve "fs/promises"

    node_modules/@prisma/client/runtime/library.js:4:1407:
      4 │ ...d_process")),Jn=k(require("fs/promises")),Vr=k(require("os"));va...
        ╵                              ~~~~~~~~~~~~~

  The package "fs/promises" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "async_hooks"

    node_modules/@prisma/client/runtime/library.js:21:5329:
      21 │ ...l=k(ti());var Ml=require("async_hooks"),$l=require("events"),ql...
         ╵                             ~~~~~~~~~~~~~

  The package "async_hooks" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

These errors do not occur when not using the @prisma/client/sql module.

### How to reproduce

1. Follow the official documentation "[Deploy to Cloudflare Workers & Pages](https://www.prisma.io/docs/orm/prisma-client/deployment/edge/deploy-to-cloudflare#postgresql-traditional)"  to set up the application. (At this point, the application deploys successfully, and data retrieval using `.findFirst()` and `.findMany()` works as expected.)
2. Follow the [typedSQL documentation](https://www.prisma.io/docs/orm/prisma-client/using-raw-sql/typedsql) to add `typedSql` to the `previewFeatures`, create raw SQL files, and run `prisma generate --sql` to generate `@prisma/client/sql`.
3. Import the `@prisma/client/sql` module and write a query using `.$queryRawTyped()`.
4. Run `wrangler dev` or `wrangler deploy` to deploy the application. The deployment fails with errors.

### Expected behavior

The application should deploy successfully on Cloudflare Workers without errors related to unresolved Node.js modules. The `typedSQL` feature should work correctly in this environment.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters", "typedSql"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model ...
```

```ts
import { Pool } from "@prisma/pg-worker";
import { PrismaPg } from "@prisma/adapter-pg-worker";
import { PrismaClient } from "@prisma/client";
import { myRawSql } from "@prisma/client/sql";

const pool = new Pool({ connectionString: env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });
prisma.$queryRawTyped(myRawSql());
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v20.11.1
- Runtime: Cloudflare Workers

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.19.0
@prisma/client          : 5.19.0
Computed binaryTarget   : darwin
Operating System        : darwin
Architecture            : x64
Node.js                 : v20.11.1
Query Engine (Node-API) : libquery-engine 5fe21811a6ba0b952a3bc71400666511fe3b902f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Schema Engine           : schema-engine-cli 5fe21811a6ba0b952a3bc71400666511fe3b902f (at node_modules/@prisma/engines/schema-engine-darwin)
Schema Wasm             : @prisma/prisma-schema-wasm 5.19.0-31.5fe21811a6ba0b952a3bc71400666511fe3b902f
Default Engines Hash    : 5fe21811a6ba0b952a3bc71400666511fe3b902f
Studio                  : 0.502.0
Preview Features        : driverAdapters, typedSql
```

**Comment by Benjamin-Dobell** [comment]
I'm using Prisma 6.10 and run into similar issue:

```
Uncaught ReferenceError: __dirname is not defined

    at null.<anonymous> (index.js:18939:5) in
  ../node_modules/.pnpm/@prisma+client@6.1.0_prisma@6.1.0/node_modules/@prisma/client/runtime/library.js
    at null.<anonymous> (index.js:32:50) in __require2
    at null.<anonymous> (index.js:62813:30)
```

The generated typed SQL files all contain:

```
import * as $runtime from "@prisma/client/runtime/library"
```

Which is no good since the library engine runtime uses `__dirname` as a side-effect during import:
https://github.com/prisma/prisma/blob/06e67e56774fb333516e02d4edecef095677f2b9/packages/engines/src/index.ts#L60

**Comment by gustavozirbes** [comment]
Same issue as @Benjamin-Dobell after "resolving" the bug reported by @aiji42.
