### ISSUE TITLE
PrismaClient thinks it's a browser environment when running test via jest

### ISSUE THREAD

**Issue by thizzle** [prisma/prisma#25193]
### Bug description

When I try to write a Jest test that uses a real (not mocked) `PrismaClient`, I get this error:

```
  ● one

    PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `Node.js`).
    If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report

       5 |
       6 | beforeEach(async () => {
    >  7 |   await prisma.$executeRaw`DELETE FROM my_table`;
         |                ^
       8 | });
       9 |
      10 | test('one', async () => {

      at Object.get (node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/.prisma/client/index-browser.js:4005:15)
      at Object.$executeRaw (__tests__/integration/purchases/index.ts:7:16)
```

The code instantiates `PrismaClient` directly from the `@prisma/client` module, but it's unclear why Prisma thinks I'm running in a browser environment when I'm running this via Jest:

```
$ jest __tests__/integration/one.ts
```

### How to reproduce

Run this code:

```ts
import {PrismaClient} from '@prisma/client';

const prisma = new PrismaClient();

beforeEach(async () => {
  await prisma.$executeRaw`DELETE FROM my_table`;
});

test('one', async () => {
  expect(1).toEqual(1);
});
```

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: macOS
- Database: MySQL
- Node.js version: v18.18.2

### Prisma Version

```
prisma                  : 5.11.0
@prisma/client          : 5.11.0
Computed binaryTarget   : linux-musl-arm64-openssl-3.0.x
Operating System        : linux
Architecture            : arm64
Node.js                 : v18.18.2
Query Engine (Node-API) : libquery-engine efd2449663b3d73d637ea1fd226bafbcf45b3102 (at node_modules/.pnpm/@prisma+engines@5.11.0/node_modules/@prisma/engines/libquery_engine-linux-musl-arm64-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli efd2449663b3d73d637ea1fd226bafbcf45b3102 (at node_modules/.pnpm/@prisma+engines@5.11.0/node_modules/@prisma/engines/schema-engine-linux-musl-arm64-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.11.0-15.efd2449663b3d73d637ea1fd226bafbcf45b3102
Default Engines Hash    : efd2449663b3d73d637ea1fd226bafbcf45b3102
Studio                  : 0.499.0
Preview Features        : fullTextIndex, fullTextSearch
```

**Comment by jkomyno** [comment]
Hi @thizzle, what is your Jest test environment? If it's set to `jsdom`, for instance, it is expected for Prisma Client to detect that you are in a browser environment. Please share your Jest config, or even better, a minimal repository that reproduces this problem. Thanks!

**Comment by thizzle** [comment]
Thank you very much for your response. That was indeed the problem: I had set `testEnvironment` to `jest-environment-jsdom` in my jest config. Using the default of `node` fixes this issue.
