### ISSUE TITLE
Expected parent IDs to be set when ordering by parent ID.

### ISSUE THREAD

**Issue by muhammadfikri4** [prisma/prisma#25397]
### Bug description

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at _n.handleRequestError (/Users/muhfikri/Documents/HSD/bmt-api-new-revamp/src/prisma/client/runtime/library.js:6783:40)
    at _n.handleAndLogRequestError (/Users/muhfikri/Documents/HSD/bmt-api-new-revamp/src/prisma/client/runtime/library.js:6734:18)
    at _n.request (/Users/muhfikri/Documents/HSD/bmt-api-new-revamp/src/prisma/client/runtime/library.js:6714:18)
    at l (/Users/muhfikri/Documents/HSD/bmt-api-new-revamp/src/prisma/client/runtime/library.js:7336:25)
    at Object.getPPOB (/Users/muhfikri/Documents/HSD/bmt-api-new-revamp/src/app/ppob/ppob.repository.ts:106:12)
    at async Promise.all (index 0)
    at Object.getPPOB (/Users/muhfikri/Documents/HSD/bmt-api-new-revamp/src/app/ppob/ppob.service.ts:138:36)
    at getPPOB (/Users/muhfikri/Documents/HSD/bmt-api-new-revamp/src/app/ppob/ppob.controller.ts:87:20) {
  clientVersion: '5.18.0'
}

### Expected behavior

normal when running query

### Prisma information

```prisma
// Add your schema.prisma
```

```ts
// Add your code using Prisma Client
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
5.17.0
```

**Comment by SevInf** [comment]
Hi @muhammadfikri4 
It looks like you did not fill out our issue template. Without this information we have no way to reproduce the issue and help you with the problem. Please, open a new issue and provide all the required information.

Thank you!
