### ISSUE TITLE
View in schema ignores @@map

### ISSUE THREAD

**Issue by edwinhaver** [prisma/prisma#25416]
### Bug description

Hello,

I have created a view with the use of introspection but when I query that view, I get the error message below. It seems to ignore the @@map attribute of the view but it could be I am doing something wrong? Appreciate your input.

The table `public.EmployeeView` does not exist in the current database.
    at Ln.handleRequestError (/Users/edwinhaver/Documents/devprojects/ims/node_modules/@prisma/client/runtime/library.js:121:7753)
    at Ln.handleAndLogRequestError (/Users/edwinhaver/Documents/devprojects/ims/node_modules/@prisma/client/runtime/library.js:121:7061)
    at Ln.request (/Users/edwinhaver/Documents/devprojects/ims/node_modules/@prisma/client/runtime/library.js:121:6745)
    at async l (/Users/edwinhaver/Documents/devprojects/ims/node_modules/@prisma/client/runtime/library.js:130:9633) {
  code: 'P2021',
  clientVersion: '5.19.1',
  meta: { modelName: 'EmployeeView', table: 'public.EmployeeView' }

Prisma schema:
```
view EmployeeView {
  id              Int    @unique
  first_name      String @db.VarChar(50)
  last_name       String @db.VarChar(50)
  email           String @db.VarChar(255)
  mobile          String @db.VarChar(15)
  designation     String @db.VarChar(100)
  department_id   Int
  department_name String @db.VarChar(100)

  @@map("employee_view")
}
```

Query code:
```
prisma.employeeView.findMany()
```

Note I am using NextJs.

### How to reproduce

1) Create view in database
2) Use npx prisma db pull for introspection of the view
3) Create API in Node or NextJs
4) Run API

### Expected behavior

It should use the @@map attribute to construct the SQL query.

### Prisma information

```
view EmployeeView {
  id              Int    @unique
  first_name      String @db.VarChar(50)
  last_name       String @db.VarChar(50)
  email           String @db.VarChar(255)
  mobile          String @db.VarChar(15)
  designation     String @db.VarChar(100)
  department_id   Int
  department_name String @db.VarChar(100)

  @@map("employee_view")
}
```

```
prisma.employeeView.findMany()
```

### Environment & setup

- OS: macOs
- Database: PostgreSQL
- Node.js version: v20.17.0

### Prisma Version

5.19.1

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
