### ISSUE TITLE
The table `(not available)` does not exist in the current database

### ISSUE THREAD

**Issue by zfeed** [prisma/prisma#25468]
### Bug description

I get error `The table `(not available)` does not exist in the current database` when there is a row in `Setting` table with `accountId` `NULL`.

If change `accountId` to `1` the error doesn't happen.

I created a repository with a minimal reproducible example. Check it in **How to reproduce** section

```txt
prisma:query BEGIN
prisma:query SELECT "public"."User"."id", "public"."User"."userSettingId" FROM "public"."User" WHERE ("public"."User"."id" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."Setting"."id" FROM "public"."Setting" WHERE ("public"."Setting"."accountId" = $1 AND "public"."Setting"."id" IN ($2)) OFFSET $3
prisma:query INSERT INTO "public"."Setting" DEFAULT VALUES RETURNING "public"."Setting"."id"
prisma:query UPDATE "public"."User" SET "userSettingId" = $1 WHERE ("public"."User"."id" IN ($2) AND "public"."Setting"."accountId" = $3)
prisma:query ROLLBACK

PrismaClientKnownRequestError: 
Invalid `prisma.user.update()` invocation in
/Users/user/Documents/Projects/test-project/src/main.ts:7:23

  4 async function bootstrap() {
  5     const prisma = new PrismaClient();
  6 
→ 7     await prisma.user.update(
The table `(not available)` does not exist in the current database.
    at Mn.handleRequestError (/Users/user/Documents/Projects/test-project/node_modules/@prisma/client/runtime/library.js:121:7753)
    at Mn.handleAndLogRequestError (/Users/user/Documents/Projects/test-project/node_modules/@prisma/client/runtime/library.js:121:7061)
    at Mn.request (/Users/user/Documents/Projects/test-project/node_modules/@prisma/client/runtime/library.js:121:6745)
    at async l (/Users/user/Documents/Projects/test-project/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async bootstrap (/Users/user/Documents/Projects/test-project/src/main.ts:7:5) {
  code: 'P2021',
  clientVersion: '5.21.1',
  meta: { modelName: 'User', table: '(not available)' }
}
```

### How to reproduce

Check the repo. It contains a minimal reproducible example.

https://github.com/zfeed/prisma-bug-2024-10-19

### Expected behavior

The update should be succesful

### Prisma information

```prisma
// Add your schema.prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Account {
  id          Int          @id @default(autoincrement())
  subSettings SubSetting[]
  settings    Setting[]
}

model Setting {
  id        Int  @id @default(autoincrement())
  // foreign keys
  accountId Int?

  account     Account?     @relation(fields: [accountId], references: [id])
  subSettings SubSetting[]
  user        User[]       @relation("userSetting")
}

model SubSetting {
  id        Int      @id @default(autoincrement())
  // foreign keys
  accountId Int?
  account   Account? @relation(fields: [accountId], references: [id])
  settingId Int
  setting   Setting  @relation(fields: [settingId], references: [id])
}

model User {
  id            Int      @id @default(autoincrement())
  userSettingId Int?
  userSetting   Setting? @relation("userSetting", fields: [userSettingId], references: [id])
}

```

```ts
// Add your code using Prisma Client
import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

async function bootstrap() {
    const prisma = new PrismaClient();

    await prisma.user.update({
        where: { id: 1 },
        data: {
            userSetting: {
                upsert: {
                    where: { accountId: 1 },
                    create: {},
                    update: {}
                }
            }
        }
    });
}

bootstrap();

```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v18.20.2

### Prisma Version

```
prisma                  : 5.21.1
@prisma/client          : 5.21.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v18.20.2
Query Engine (Node-API) : libquery-engine bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.21.1-1.bf0e5e8a04cada8225617067eaa03d041e2bba36
Default Engines Hash    : bf0e5e8a04cada8225617067eaa03d041e2bba36
Studio                  : 0.503.0
```

**Comment by yovanoc** [comment]
Big blockers for me, if we can help don't hesitate to ask

**Comment by mkuhlmann** [comment]
Still reproduceable on latest 6.14.0, almost caused big issues in production for us :(

**Comment by ashlite** [comment]
Okay I encounter this problem after playing with trigger and function to my postgress
Even though it still in development env, but it is a blocker for me

stack
bun v1.3.10
prisma v6.19.0
prisma/client v6.14.0
postgres 18

**Comment by ashlite** [comment]
found the problem in mine
The problem is in the trigger function SQL resulting in invalid query.
So it seems that the error got pickup and get forwarded to the top prisma query.
