### ISSUE TITLE
typedSql and $allOperations extension errors

### ISSUE THREAD

**Issue by exAspArk** [prisma/prisma#25481]
### Bug description

It seems like the `typedSql` preview feature is not compatible with `$allOperations` client extensions. Here is the error stack trace:

```
TypeError: undefined is not an object (evaluating 'e.map')
      at hl (../node_modules/@prisma/client/runtime/library.js:114:15432)
  at $t (../node_modules/@prisma/client/runtime/library.js:114:15379)
      at ../node_modules/@prisma/client/runtime/library.js:121:408
      at ../node_modules/@prisma/client/runtime/library.js:130:10110
      at _executeRequest (../node_modules/@prisma/client/runtime/library.js:130:9962)
      at ../node_modules/@prisma/client/runtime/library.js:30:5137
      at i (../node_modules/@prisma/client/runtime/library.js:121:1025)
      at then (../node_modules/@prisma/client/runtime/library.js:121:1100)
      at then (../node_modules/@prisma/client/runtime/library.js:121:1100)
      at processTicksAndRejections (:61:76)
```

### How to reproduce

1. Enabled the `typedSql` preview feature.
2. Extend the Prisma client like this:

```ts
const prisma = new PrismaClient().$extends({
  query: {
    $allOperations({ args, query, operation, model }: any) {
      console.log({ args, query, operation, model });
      return query(args);
    }
  }
})
```

3. Attempt to run `$queryRawTyped`

```sql
-- prisma/sql/getTodoCount.sql
SELECT COUNT(*) as count FROM "todos"
```

```ts
import { getTodoCount } from "@prisma/client/sql";
const todoCount = await prisma.$queryRawTyped(getTodoCount())
```

The extension outputs the following

```
{
  args: {},
  query: [Function: query],
  operation: "$queryRawTyped",
  model: undefined
}
```

It crashes only with the `$extends`, without it the client works fine.

### Prisma information

```prisma
// Add your schema.prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["typedSql", "driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      =  env("SOURCE_DB_URI")
}

model Todo {
  @@map("todos")

  id          Int      @id @default(autoincrement())
  task        String   @db.VarChar(255)
  isCompleted Boolean  @default(false)
  authorId    Int?
}
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
5.20.0
```

**Comment by jimmyfortinx** [comment]
We faced the same issue on our side and for us we ended up using `$allModels` as a workaround, but it would be better to have `$allOperations` supported directly.

```ts
const prisma = new PrismaClient().$extends({
  query: {
    $allModels: {
      $allOperations({ args, query, operation, model }: any) {
        console.log({ args, query, operation, model });
        return query(args);
      },
    },
  },
});
```

**Comment by exAspArk** [comment]
Thanks for sharing this workaround, @jimmyfortinx!

In our case, we need an extension that also supports raw SQL queries (`$allOperations` directly without `$allModels`). Hopefully, this will can be resolved soon.

**Comment by martin-trummer** [comment]
related note: to get the typed raw info, we can currently do this:
```typescript
const sqlText = params.__internalParams.args.sql;
const args = params.__internalParams.args.values;
```
but it feels wrong to access some `__internalParams` variable.
Maybe when this issue is fixed, the related info should be in the `query`/`args` parameters?

**Comment by smilecc** [comment]
I use this method to bypass it in my project.I hope there will be an official plan soon.

```js
if (rootParams?.operation === '$queryRawTyped') {
    return rootParams.query(rootParams.__internalParams?.args);
}
```

**Comment by john-privy** [comment]
Great, thanks @smilecc !

Agreed this feels wrong and would love to see fixed!

**Comment by ludralph** [comment]
Hi @exAspArk 

I can reproduce this issue and have added it to the queue.
