### ISSUE TITLE
TypeError: 'ownKeys' on proxy: trap result did not include '$use' when using $transaction on extended client.

### ISSUE THREAD

**Issue by adrdra** [prisma/prisma#25501]
### Bug description

Hi there,

When attempting to use Prisma's `$transaction` method on an extended client, I'm encountering an error related to the proxy trap not including '$use'. This occurs when trying to log the transaction object inside the transaction callback.

Here is the error that I get:

```bash
Error in $transaction: TypeError: 'ownKeys' on proxy: trap result did not include '$use'
    at Reflect.ownKeys (<anonymous>)
    at Object.ownKeys (/Users/-/Workspace/prisma-test/node_modules/@prisma/client/runtime/library.js:21:8250)
    at i.<computed> (/Users/-/Workspace/prisma-test/node_modules/@prisma/client/runtime/library.js:21:8734)
    at formatValue (node:internal/util/inspect:806:19)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2304:40)
    at formatWithOptions (node:internal/util/inspect:2166:10)
    at console.value (node:internal/console/constructor:349:14)
    at console.log (node:internal/console/constructor:386:61)
    at file:///Users/-/Workspace/prisma-test/index.js:10:15
```

### How to reproduce

1. Create a new Node.js project
2. Install @prisma/client
3. Create an `index.js` file with the following content:

```js
import { PrismaClient } from '@prisma/client';

async function testTransaction() {
  console.log('Before $transaction');
  const client = new PrismaClient();

  try {
    await client.$extends({}).$transaction(async (tx) => {
      console.log('Inside transaction');
      console.log(tx)
    });
    console.log('After $transaction');
  } catch (error) {
    console.error('Error in $transaction:', error);
  } finally {
    await client.$disconnect();
  }
}

testTransaction()
  .then(() => console.log('Test completed'))
  .catch((error) => console.error('Unhandled error:', error));
```

4. Run the script with `node index.js`

### Expected behavior

The transaction should execute successfully, and the `tx` object should be logged without errors.

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
}
```

```ts
const client = new PrismaClient();
 await client.$extends({}).$transaction(async (tx) => {
      console.log('Inside transaction');
      console.log(tx)
    });
```

### Environment & setup

- OS: MacOs, Sonoma 14.5
- Database: PostgreSQL16
- Node.js version: v22.2.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.21.1
@prisma/client          : 5.21.1
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v22.2.0
Query Engine (Node-API) : libquery-engine bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.21.1-1.bf0e5e8a04cada8225617067eaa03d041e2bba36
Default Engines Hash    : bf0e5e8a04cada8225617067eaa03d041e2bba36
Studio                  : 0.503.0
```

**Comment by aqrln** [comment]
Thanks @adrdra, I can reproduce it. The next step is to check if it's a regression. What's weird is IIRC we have explicit tests for this.

cc @jkomyno

**Comment by JustinProbyn** [comment]
Hi @aqrln, any news on this issue?

**Comment by dennemark** [comment]
@aqrln am experiencing the same issue.

**Comment by dennemark** [comment]
for me this happens if i console.log the tx within client.$transaction in an extension.

**Comment by Kianoosh76** [comment]
+1 on this. being stuck trying to use a middleware on transaction

**Comment by whygee-dev** [comment]
No news ? Blocking me as well

**Comment by JustinProbyn** [comment]
Again, checking if there is any progress on this

**Comment by JustinProbyn** [comment]
Hi again, any news on this?

@jkomyno @aqrln
