### ISSUE TITLE
Cannot find libssl error when querying database locally

### ISSUE THREAD

**Issue by iampeternguyen** [prisma/prisma#25521]
### Bug description

I get the following error when going through the getting started guide. i have openssl 3.4 in zorin os. (based on ubuntu) I don't have openssl 1.1.x 

i've tried adding the environment variable here as well https://www.prisma.io/docs/orm/reference/environment-variables-reference#cli-binary-targets but no luck.

```
╰─➤  npx tsx prisma/index.ts
PrismaClientInitializationError: 
Invalid `prisma.user.findMany()` invocation in
/home/peter/Code/lingo-tools-api/prisma/index.ts:8:40

  5 export async function main() {
  6   try {
  7     // ... you will write your Prisma Client queries here
→ 8     const allUsers = await prisma.user.findMany(
Unable to require(`/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node`).
Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.

Details: libssl.so.1.1: cannot open shared object file: No such file or directory
    at Mn.handleRequestError (/node_modules/@prisma/client/runtime/library.js:121:8053)
    clientVersion: '5.21.1',
  errorCode: undefined
}
```

when i run npx prisma --version i get the followign

```
Environment variables loaded from .env
Error: Unable to require(`/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node`).
Prisma cannot find the required `libssl` system library in your system. Please install openssl-1.1.x and try again.

Details: libssl.so.1.1: cannot open shared object file: No such file or directory
    at pne (/node_modules/prisma/build/index.js:284:116)
    at uWe (//node_modules/prisma/build/index.js:284:269)
prisma                  : 5.21.1
@prisma/client          : 5.21.1
Computed binaryTarget   : debian-openssl-1.1.x
Operating System        : linux
Architecture            : x64
Node.js                 : v22.9.0
Query Engine (Node-API) : E_CANNOT_RESOLVE_VERSION (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli bf0e5e8a04cada8225617067eaa03d041e2bba36 (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.21.1-1.bf0e5e8a04cada8225617067eaa03d041e2bba36
Default Engines Hash    : bf0e5e8a04cada8225617067eaa03d041e2bba36
Studio                  : 0.503.0
```

### How to reproduce

1. getting started guide on zorinOS

### Prisma information

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?
// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init

generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-3.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String   @db.VarChar(255)
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}

model Profile {
  id     Int     @id @default(autoincrement())
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model User {
  id      Int      @id @default(autoincrement())
  email   String   @unique
  name    String?
  posts   Post[]
  profile Profile?
}
```

```ts
// Add your code using Prisma Client
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function main() {
  try {
    // ... you will write your Prisma Client queries here
    const allUsers = await prisma.user.findMany();
    console.log("finding users");
    console.log(allUsers);

    await prisma.$disconnect();
  } catch (error) {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  }
}
main();

```

### Environment & setup

- OS: ZorinOs (debian)
- Database: PostgreSQL
- Node.js version: 22.9.0

### Prisma Version

```
5.21.1
```

**Comment by kazza-dev** [comment]
any fix?
