### ISSUE TITLE
Usage of adapter-pg causes ENOENT error

### ISSUE THREAD

**Issue by adamjuhasz** [prisma/prisma#25597]
### Bug description

When switching to using `@prisma/adapter-pg` we are getting a ENOENT error. Reverting to not using the adapter does not experience this error.

If we have multiple schemas (we have the following previews enabled `["multiSchema", "tracing", "omitApi", "prismaSchemaFolder", "views", "metrics", "nativeDistinct", "driverAdapters"]` could the Postgres adapter not work?

Error:
```
PrismaClientKnownRequestError: 
Invalid `prisma.event.findUnique()` invocation in
/Users/adamjuhasz/Repos/frontend-monorepo/Vanadium/src/api/@middleware.ts:58:41

  55   };
  56 }
  57 
→ 58 const existing = await prisma.event.findUnique(
No such file or directory
 code: "ENOENT"

      at new PrismaClientKnownRequestError (/Users/adamjuhasz/Repos/frontend-monorepo/Vanadium/node_modules/@prisma/client/runtime/library.js:21:1414)
      at handleRequestError (/Users/adamjuhasz/Repos/frontend-monorepo/Vanadium/node_modules/@prisma/client/runtime/library.js:121:7315)
      at handleAndLogRequestError (/Users/adamjuhasz/Repos/frontend-monorepo/Vanadium/node_modules/@prisma/client/runtime/library.js:121:6623)
      at /Users/adamjuhasz/Repos/frontend-monorepo/Vanadium/node_modules/@prisma/client/runtime/library.js:121:6307
```

Setup:
```
const databaseUrl = process.env.DATABASE_URL;

const pool = new Pool({
  connectionString: databaseUrl,
  min: 10,
  max: 100,
  idleTimeoutMillis: milliseconds({ seconds: 10 }),
  allowExitOnIdle: true,
});

const adapter = new PrismaPg(pool);

export const prismaWithoutPagination = 
      new PrismaClient({
        adapter: adapter,
        log: ["info"],
      });
```

### How to reproduce

1. Enable multi schema
2. Enable database adapters
3. switch from Prisma's pool to native pool

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["multiSchema", "tracing", "omitApi", "prismaSchemaFolder", "views", "metrics", "nativeDistinct", "driverAdapters"]
  binaryTargets   = ["native", "debian-openssl-3.0.x"]
}

datasource db {
  // provider gets swapped for `"cockroachdb"` in the dockerfile
  provider = "postgresql"
  url      = env("DATABASE_URL")
  // If you add a schema here also add it to `../../scripts/drop-schemas.sql`
  schemas  = ["equivalent_securities_list", "idempotency", "service_team", "advisor_group", "entity", "person", "sharing", "identity", "investment", "constant", "account", "person_group", "security_master", "portfolio_manager", "vanadium", "farther_security_registrar", "financial_planning", "portfolio_storage", "proposal_manager", "proposal", "reporting_account"]
}

model Event {
  eventId        String   @id @default(uuid()) @map("event_id")
  idempotencyKey String   @unique @map("idempotency_key")
  action         String
  userId         String?  @map("user_id")
  createdAt      DateTime @default(now()) @map("created_at")

  @@unique([eventId])
  @@map("event")
  @@schema("idempotency")
}
```

### Environment & setup

- OS: macOS
- Database: CockroachDB
- Node.js version: 21

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 5.22.0
@prisma/client          : 5.22.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v21.6.0
Query Engine (Node-API) : libquery-engine 605197351a3c8bdd595af2d2a9bc3025bca48ea2 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 605197351a3c8bdd595af2d2a9bc3025bca48ea2 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 5.22.0-44.605197351a3c8bdd595af2d2a9bc3025bca48ea2
Default Engines Hash    : 605197351a3c8bdd595af2d2a9bc3025bca48ea2
Studio                  : 0.503.0
Preview Features        : driverAdapters, metrics, multiSchema, nativeDistinct, tracing, views, prismaSchemaFolder, omitApi
```

**Comment by adamjuhasz** [comment]
We figured it out that our connection string has a ca certificate in it (we use cockroach db) and the pool could not find this
