### ISSUE TITLE
RelationJoins feature causing normal queries to fail

### ISSUE THREAD

**Issue by ldobrovic** [prisma/prisma#25645]
### Bug description

We use Prisma as part of our Nest.js backend, which is containerized with Docker and deployed to AWS. 

We've recently been running into issues where Prisma fails to autochunk queries properly (as outlined in issues like #21648). In that discussion, it was recommended to give the relationJoins preview feature a go, and it seemed that for some users, this was successful. However, enabling this feature has actually broken nearly every Prisma query in our backend. For example, 

this code

```
		const subscriptionIds = await this.getSubscriptionIdsToHub({
			hubId,
			segmentId,
		});
		
		const subscribers = await this.prisma.hubSubscriber.findMany({
			where: {
				id: { in: subscriptionIds.map(({ id }) => id) },
			},
		});
```

where subscriptionIds is gathered from 

```
		return await this.prisma.hubSubscriber.findMany({
			take,
			skip: page !== undefined && take ? take * page : undefined,
			orderBy: sortOptions,
			where: whereConditions,
			select: {
				id: true,
			},
		});
```

throws the following error when relationJoins is enabled

```
PrismaClientKnownRequestError: 
Invalid `prisma.hubSubscriber.findMany()` invocation:

Query parameter limit exceeded error: Joined queries cannot be split into multiple queries..
    at Ln.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7753)
    at Ln.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7061)
    at Ln.request (/app/node_modules/@prisma/client/runtime/library.js:121:6745)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async SubscriptionService.getTotalHubSubscribers (/app/src/subscription/subscription.service.ts:275:23)
    at async <anonymous> (/app/node_modules/@opentelemetry/instrumentation-nestjs-core/src/instrumentation.ts:221:16)
```
    
 

### How to reproduce

Create a table called HubSubscriber with a foreign key to a another table, Hub

Create a record in the Hub table, assume it has id A

Create 1,000 records in the HubSubscriber table with a foreign key to that Hub table

Run a findMany on that HubSubscriber table where { hubId: A } 

### Expected behavior

We expect the query to return successfully, as it does when this preview feature is not enabled

### Prisma information

```ts
generator client {
  provider = "prisma-client-js"
}

generator json {
  provider  = "prisma-json-types-generator"
  namespace = "PrismaJson"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model HubSubscriber {
  id                    String                 @id @default(uuid()) @db.Uuid
  hubId                 String                 @db.Uuid
  userId                String                 @db.Uuid
  importBatchId         Int?                   @db.Integer()
  createdAt             DateTime               @default(now()) @db.Timestamptz(6)
  updatedAt             DateTime               @updatedAt @db.Timestamptz(6)
  lastMessageDate       DateTime?              @db.Timestamptz(6)
  isUnsubscribed        Boolean                @default(false)
  hub                   Hub                    @relation(fields: [hubId], references: [id], onDelete: Cascade)
  user                  User                   @relation(fields: [userId], references: [id], onDelete: Cascade)
  smsMarketingCampaigns SmsMarketingCampaign[]
  importBatch           ImportBatch?           @relation(fields: [importBatchId], references: [id], onDelete: Cascade)
}
```

### Environment & setup

- OS: Amazon Linux
- Database: PostgreSQL
- Node.js version: node:22-alpine

### Prisma Version

```
"prisma": "^5.18.0",
```

**Comment by controversial** [comment]
Happening to me too when passing a large `in`, even when the query that fails is not performing any joins.

**Comment by ludralph** [comment]
Hi @ldobrovic 

I couldn't reproduce this using the example you specified with "relationJoins", Do you have a reproduction you can share?

**Comment by ludralph** [comment]
> Happening to me too when passing a large array to `in`, even when the query that fails is not performing any joins.

Hi @controversial 

Do you have a reproduction you can share or steps to reproduce so i can take a look at it?

**Comment by controversial** [comment]
@ludralph I have a schema like this:

```prisma
model Event {
  id String @id @default(uuid())
  submissions Submission[]
}

model Submission {
  submission_id String @id
  event_id String
  event Event @relation(fields: [event_id], references: [id])

  // ... more fields ...
}
```

The following query fails when `relationJoins` is enabled: 
```ts
const submissionIds = [/* tens of thousands of items */];

const submissions = await prisma.submission.findMany({
  where: { submission_id: { in: submissionIds } },
  select: { submission_id: true, event_id: true },
});
```

The error looks like:
```
PrismaClientKnownRequestError:
Invalid 'prisma.submission.findMany() invocation in /path/to/my/script.ts

Query parameter limit exceeded error: Joined queries cannot be split into multiple queries..
Query parameter limit exceeded error: Joined queries cannot be split into multiple queries..
 clientVersion: "6.3.0",
       meta: {
  modelName: "Submission"
  message: "Joined queries cannot be split into multiple queries.",
},
       code: "P2029"
```

It’s fixed if I break the query into chunks myself:
```ts
import { chunk } from 'lodash';

const submissionIds = [/* tens of thousands of items */];

const submissions = (await Promise.all(
  chunk(submissionIds, 1000).map((sids) => (
    db.submission.findMany({
      where: { submission_id: { in: sids } },
      select: { submission_id: true, event_id: true },
    })
  )),
)).flat();
```

<details><summary>prisma version:</summary>

```
prisma                  : 6.3.0
@prisma/client          : 6.3.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v22.12.0
TypeScript              : 5.7.3
Query Engine (Node-API) : libquery-engine acc0b9dd43eb689cbd20c9470515d719db10d0b0 (at ../../node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli acc0b9dd43eb689cbd20c9470515d719db10d0b0 (at ../../node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 6.3.0-17.acc0b9dd43eb689cbd20c9470515d719db10d0b0
Default Engines Hash    : acc0b9dd43eb689cbd20c9470515d719db10d0b0
Studio                  : 0.508.0
```

</details>

**Comment by ldobrovic** [comment]
Following up here to say that manually breaking large queries into batches/chunks and then feeding those smaller segments into prisma works well — ideally Prisma would be handle this under-the-hood but this is a reasonable workaround
