### ISSUE TITLE
typedSql and Prisma Optimize extension errors

### ISSUE THREAD

**Issue by Aegirs** [prisma/prisma#25659]
### Bug description

It seems like the typedSql preview feature is not compatible with Prisma Optimize client extensions. Here is the error stack trace:

```
│ TypeError: Cannot read properties of undefined (reading 'map')
│     at El (/projects/prisma_optimize_tutorial/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:114:431)
│     at jt (projects/prisma_optimize_tutorial/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:114:376)
│     at /projects/prisma_optimize_tutorial/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:399
│     at Proxy._executeRequest (/projects/prisma_optimize_tutorial/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:10
│ 111)
│     at /projects/prisma_optimize_tutorial/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:31:9618
│     at i (/projects/prisma_optimize_tutorial/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:1016)
│     at PrismaPromise.then (/projects/prisma_optimize_tutorial/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:1091)
│     at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
│   clientVersion: '5.22.0'
│ }
```

Probably related to: https://github.com/prisma/prisma/issues/25481

### How to reproduce

1. Enabled the tracing preview feature.
2. Enabled the typedSql preview feature.
3. Attempt to run $queryRawTyped

```sql
-- prisma/sql/getTodoCount.sql
SELECT COUNT(*) as count FROM "Todo";
```

```node
import { getTodoCount } from "@prisma/client/sql";
const todoCount = await prisma.$queryRawTyped(getTodoCount())
```

It crashes only with the $extends, without it the client works fine.

### Expected behavior

Be able to see queryRawTyped in Prisma Optimize  dashbaord

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["typedSql", "tracing"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Todo {
  id          String   @id @default(cuid())
  title       String
  isCompleted Boolean  @default(false)
  isDeleted   Boolean  @default(false)
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}

```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v22.11.0 (lts)

### Prisma Version

```
5.22.0
```

**Comment by ludralph** [comment]
Hi @Aegirs 

This is related to[ #25481](https://github.com/prisma/prisma/issues/25481). I'm going to close this in favour of that other issue.
