### ISSUE TITLE
Cannot Create - Error about "m" being present in uuid when it is not

### ISSUE THREAD

**Issue by OriGummy** [prisma/prisma#25677]
### Discussed in https://github.com/prisma/prisma/discussions/25668

<div type='discussions-op-text'>

<sup>Originally posted by **OriGummy** November 19, 2024</sup>
### Question

I create a row with some valid uuid, and get error:
```'Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `m` at 2```
I added no "m" character and printing seems valid.

Full Logs:
```
{
  venueId: 'da0e9a82-f222-4029-9a6f-d15ea210b7d3',
  userId: 'd542b2cb-dc28-4fa9-b104-362b0e4e3ba4'
}
PrismaClientKnownRequestError: 
Invalid `prisma.attendee.create()` invocation in
/home/origummy/src/chremp-back/src/app/routes/menu/getVenueMenu.controller.ts:24:46

  21 let menu: MenuModel | null = null;
  22 if (!attendee) { // Not even attending
  23   console.log({venueId, userId})
→ 24   let attendee = await prisma.attendee.create(
Inconsistent column data: Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `m` at 2
    at $n.handleRequestError (/home/origummy/src/chremp-back/node_modules/@prisma/client/runtime/library.js:121:7315)
    at $n.handleAndLogRequestError (/home/origummy/src/chremp-back/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/home/origummy/src/chremp-back/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/home/origummy/src/chremp-back/node_modules/@prisma/client/runtime/library.js:130:9633)
    at <anonymous> (/home/origummy/src/chremp-back/src/app/routes/menu/getVenueMenu.controller.ts:24:24) {
  code: 'P2023',
  clientVersion: '5.22.0',
  meta: {
    modelName: 'Attendee',
    message: 'Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `m` at 2'
  }
}
```

I tried deleting the "migrations" folder, tried reinstalling prisma, tried regenerating client. Nope. What could be the problem?

Thanks for reading this.

### Information about Prisma Schema, Client Queries and Environment (optional)

```prisma
model Venue {
  id       String   @id @db.Uuid @default(cuid())
  title    String
  bio      String?
  location String
  time     BigInt

  attendees    Attendee[]
}

model Attendee {
  id                    String   @id @db.Uuid @default(cuid())
  venue                 Venue    @relation(fields: [venueId], references: [id], onDelete: Cascade)
  venueId               String   @db.Uuid
  user                  Profile  @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId                String   @db.Uuid
}

model Profile {
  id         String   @id @db.Uuid @default(cuid())
  first_name String   @default("unknown")
  last_name  String?
  phone      String

  attendees  Attendee[]
}
```

```ts
console.log({venueId, userId}) // Notice output is correct in the attached before logs
let attendee = await prisma.attendee.create({
  data: {
    venueId,
    userId,
  },
});
```

- OS: Ubuntu
- Database: PostgreSQL (SupaBase
- Node.js version: v20.11.0

```
prisma                  : 5.22.0
@prisma/client          : 5.22.0
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.11.0
Query Engine (Node-API) : libquery-engine 605197351a3c8bdd595af2d2a9bc3025bca48ea2 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 605197351a3c8bdd595af2d2a9bc3025bca48ea2 (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.22.0-44.605197351a3c8bdd595af2d2a9bc3025bca48ea2
Default Engines Hash    : 605197351a3c8bdd595af2d2a9bc3025bca48ea2
Studio                  : 0.503.0
Preview Features        : views
```</div>

**Comment by OriGummy** [comment]
almost - `@default(dbgenerated("gen_random_uuid()"))` did the trick.
thanks bro!
