### ISSUE TITLE
Unexpected error on fresh init

### ISSUE THREAD

**Issue by TeNNoX** [prisma/prisma#2574]
**report id 6303**
when I run `prisma introspect` on `DATABASE_URL="postgresql://bla:bluub@10.0.0.2/10020?schema=public"`

I'm a bit annoyed that you don't event print the error so I can get an idea what it is about.

**Comment by janpio** [comment]
That is indeed not what should happen, the error should be printed. I will create a new issue for this.

Here is the gist of the error that was reported:
```
Error: [libs/sql-schema-describer/src/postgres.rs:532:20] querying for sequences: Error { kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: None, code: SqlState("42P01"), message: "relation \"information_schema.sequences\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("namespace.c"), line: Some(188), routine: Some("RangeVarGetRelid") }) }), original_code: Some("42P01"), original_message: Some("db error: ERROR: relation \"information_schema.sequences\" does not exist") }
    at IntrospectionEngine.<anonymous> (/home/manu/.config/yarn/global/node_modules/@prisma/cli/build/index.js:2:2295124)
    at Generator.throw (<anonymous>)
    at rejected (/home/manu/.config/yarn/global/node_modules/@prisma/cli/build/index.js:2:2292154)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by pantharshit00** [comment]
You can access the stacktrace by setting `DEBUG` environment variable to `*`
```
export DEBUG=*
```

Error reported to us:

```
Error: [libs/sql-schema-describer/src/postgres.rs:532:20] querying for sequences: Error { kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: None, code: SqlState("42P01"), message: "relation \"information_schema.sequences\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("namespace.c"), line: Some(188), routine: Some("RangeVarGetRelid") }) }), original_code: Some("42P01"), original_message: Some("db error: ERROR: relation \"information_schema.sequences\" does not exist") }
    at IntrospectionEngine.<anonymous> (/home/manu/.config/yarn/global/node_modules/@prisma/cli/build/index.js:2:2295124)
    at Generator.throw (<anonymous>)
    at rejected (/home/manu/.config/yarn/global/node_modules/@prisma/cli/build/index.js:2:2292154)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Looks like information schema is missing some details. Can you please share a SQL dump of the database so that we can try to reproduce this?

**Comment by TeNNoX** [comment]
It is a wicked database. Not even Jetbrains' DataGrip is able to list the tables, as I just found out.

I don't think this is an issue concerning Prisma.
