### ISSUE TITLE
Unique constraint failed on the fields: (`userId`)

### ISSUE THREAD

**Issue by dxkyy** [prisma/prisma#25764]
### Bug description

My code worked fine before i switched to prisma 6 and I though I migrated fine, but now my code produces this error:
```
16 | `;throw new Error(u)}else if(r==="warn"){let u=`Conflict for env var${s.length>1?"s":""} ${s.map(c=>J(c)).join(", ")} in ${Y(a)} and ${Y(l)}
17 | Env vars from ${Y(l)} overwrite the ones from ${Y(a)}
18 |       `;console.warn(`${ke("warn(prisma)")} ${u}`)}}}}function es(e){if(nc(e)){ci(`Environment variables loaded from ${e}`);let t=pi.default.config({path:e,debug:process.env.DOTENV_CONFIG_DEBUG?!0:void 0});return{dotenvResult:Xo(t),message:Oe(`Environment variables loaded from ${mt.default.relative(process.cwd(),e)}`),path:e}}else ci(`Environment variables not found at ${e}`);return null}function ts(e,t){return e&&t&&mt.default.resolve(e)===mt.default.resolve(t)}function nc(e){return!!(e&&Hr.default.existsSync(e))}var rs="library";function Ht(e){let t=ic();return t||(e?.config.engineType==="library"?"library":e?.config.engineType==="binary"?"binary":rs)}function ic(){let e=process.env.PRISMA_CLIENT_ENGINE_TYPE;return e==="library"?"library":e==="binary"?"binary":void 0}var Kt;(t=>{let e;(E=>(E.findUnique="findUnique",E.findUniqueOrThrow="findUniqueOrThrow",E.findFirst="findFirst",E.findFirstOrThrow="findFirstOrThrow",E.findMany="findMany",E.create="create",E.createMany="createMany",E.createManyAndReturn="crea | ... truncated
19 | ${(0,ls.default)(ac(n),2)}
20 | }`}};function sc(e){let t;if(e.length>0){let r=e.find(n=>n.fromEnvVar!==null);r?t=`env("${r.fromEnvVar}")`:t=e.map(n=>n.native?"native":n.value)}else t=void 0;return t}function ac(e){let t=Object.keys(e).reduce((r,n)=>Math.max(r,n.length),0);return Object.entries(e).map(([r,n])=>`${r.padEnd(t)} = ${lc(n)}`).join(`
21 | `)}function lc(e){return JSON.parse(JSON.stringify(e,(t,r)=>Array.isArray(r)?`[${r.map(n=>JSON.stringify(n)).join(", ")}]`:JSON.stringify(r)))}var Zt={};jt(Zt,{error:()=>pc,info:()=>cc,log:()=>uc,query:()=>dc,should:()=>us,tags:()=>Yt,warn:()=>hi});var Yt={error:ce("prisma:error"),warn:ke("prisma:warn"),info:De("prisma:info"),query:et("prisma:query")},us={warn:()=>!process.env.PRISMA_DISABLE_WARNINGS};function uc(...e){console.log(...e)}function hi(e,...t){us.warn()&&console.warn(`${Yt.warn} ${e}`,...t)}function cc(e,...t){console.info(`${Yt.info} ${e}`,...t)}function pc(e,...t){console.error(`${Yt.error} ${e}`,...t)}function dc(e,...t){console.log(`${Yt.query} ${e}`,...t)}function Kr(e,t){if(!e)throw new Error(`${t}. This should never happen. If you see this error, please, open an issue at https://pris.ly/prisma-prisma-bug-report`)}function Le(e,t){throw new Error(t)}function bi(e,t){return Object.prototype.hasOwnProperty.call(e,t)}var Ei=(e,t)=>e.reduce((r,n)=>(r[t(n)]=n,r),{});function ft(e,t){let r={};for | ... truncated

PrismaClientKnownRequestError:
Invalid `prisma.lotteryParticipation.create()` invocation in
C:\Users\adria\Desktop\dev\typescript\discord\misterman-bun\src\subcommands\lottery\enter.ts:69:43

  66            ephemeral: true,
  67    };
  68 } else {
→ 69    lP = await prisma.lotteryParticipation.create(
Unique constraint failed on the fields: (`userId`)
 code: "P2002"

      at new PrismaClientKnownRequestError (C:\Users\adria\Desktop\dev\typescript\discord\misterman-bun\node_modules\@prisma\client\runtime\library.js:21:1686)
      at handleRequestError (C:\Users\adria\Desktop\dev\typescript\discord\misterman-bun\node_modules\@prisma\client\runtime\library.js:121:7338)
      at handleAndLogRequestError (C:\Users\adria\Desktop\dev\typescript\discord\misterman-bun\node_modules\@prisma\client\runtime\library.js:121:6663)
      at C:\Users\adria\Desktop\dev\typescript\discord\misterman-bun\node_modules\@prisma\client\runtime\library.js:121:6370
      
 ```

### How to reproduce

1. Setup a typescript project with bun using prisma for postgresql
2. Create two models with a one to one relation
3. Try to create an entry for one of these models.

### Expected behavior

The code should have created an entry in the database

### Prisma information

```prisma
model LotteryParticipation {
  id        String   @id @default(cuid())
  userId    String   @unique
  lottery   Lottery  @relation(fields: [lotteryId], references: [id])
  amount    Int
  lotteryId String
  createdAt DateTime @default(now())
}

model User {
  id          String     @id
  wallet      Int        @default(0)
  bank        Int        @default(0)
  maxBankSize Int        @default(10000)
  lastDaily   DateTime
  lastWeekly  DateTime
  lastMonthly DateTime
  job         String?
  allTime     Int        @default(0)
  cooldowns   Cooldown[]
}
```

```ts
lP = await prisma.lotteryParticipation.create({
	data: {
		userId: interaction!.user.id,
		lotteryId: lottery.id,
		amount,
	},
});
```

### Environment & setup

- OS: Windows 11
- Database: PostgreSQL
- Node.js version: 22.11.0

### Prisma Version

```
prisma                  : 6.0.0
@prisma/client          : 6.0.0
Computed binaryTarget   : windows
Operating System        : win32
Architecture            : x64
Node.js                 : v22.11.0
Query Engine (Node-API) : libquery-engine 5dbef10bdbfb579e07d35cc85fb1518d357cb99e (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Schema Engine           : schema-engine-cli 5dbef10bdbfb579e07d35cc85fb1518d357cb99e (at node_modules\@prisma\engines\schema-engine-windows.exe)
Schema Wasm             : @prisma/prisma-schema-wasm 5.23.0-27.5dbef10bdbfb579e07d35cc85fb1518d357cb99e
Default Engines Hash    : 5dbef10bdbfb579e07d35cc85fb1518d357cb99e
Studio                  : 0.503.0
```

**Comment by dxkyy** [comment]
Oh, I just had to remove the `@unique`. My bad
