### ISSUE TITLE
console.log(prisma) trigger : RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zhangfisher** [prisma/prisma#25798]
### Bug description

```ts
 const { PrismaClient } = await import("@prisma/client")
 const db = new PrismaClient()
console.log(db)

// trigger error:

node:internal/util/inspect:1640
          RegExpPrototypeSymbolSplit(/(?<=\n)/, value),
          ^

RangeError: Maximum call stack size exceeded
    at formatPrimitive (node:internal/util/inspect:1640:11)
    at formatValue (node:internal/util/inspect:774:12)
    at formatProperty (node:internal/util/inspect:1949:11)
    at formatRaw (node:internal/util/inspect:1058:9)
    at formatValue (node:internal/util/inspect:844:10)
    at formatProperty (node:internal/util/inspect:1949:11)
    at formatRaw (node:internal/util/inspect:1058:9)
    at formatValue (node:internal/util/inspect:844:10)
    at inspect (node:internal/util/inspect:368:10)
    at Ee.i.<computed> (.pnpm\@prisma+client@5.4.1_prisma@5.4.1\node_modules\@prisma\client\runtime\library.js:26:8097)
    at formatValue (node:internal/util/inspect:809:19)
    at formatProperty (node:internal/util/inspect:1949:11)
    at formatRaw (node:internal/util/inspect:1058:9)
    at formatValue (node:internal/util/inspect:844:10)
    at formatProperty (node:internal/util/inspect:1949:11)
    at formatRaw (node:internal/util/inspect:1058:9)
    at formatValue (node:internal/util/inspect:844:10)
    at inspect (node:internal/util/inspect:368:10)
    at Ee.i.<computed> (.pnpm\@prisma+client@5.4.1_prisma@5.4.1\node_modules\@prisma\client\runtime\library.js:26:8097)
    at formatValue (node:internal/util/inspect:809:19)
    at formatProperty (node:internal/util/inspect:1949:11)
    at formatRaw (node:internal/util/inspect:1058:9)
    at formatValue (node:internal/util/inspect:844:10)
    at inspect (node:internal/util/inspect:368:10)
    at Ee.i.<computed> (E:\Work\Code\sources\voerka-fullstack\node_modules\.pnpm\@prisma+client@5.4.1_prisma@5.4.1\node_modules\@prisma\client\runtime\library.js:26:8097)
    at formatValue (node:internal/util/inspect:809:19)
    at formatProperty (node:internal/util/inspect:1949:11)
    at formatRaw (node:internal/util/inspect:1058:9)
    at formatValue (node:internal/util/inspect:844:10)
    at formatProperty (node:internal/util/inspect:1949:11)
    at formatRaw (node:internal/util/inspect:1058:9)
    at formatValue (node:internal/util/inspect:844:10)
    at inspect (node:internal/util/inspect:368:10)
    at Ee.i.<computed> (.pnpm\@prisma+client@5.4.1_prisma@5.4.1\node_modules\@prisma\client\runtime\library.js:26:8097)
    at formatValue (node:internal/util/inspect:809:19)
    at formatProperty (node:internal/util/inspect:1949:11)
    at formatRaw (node:internal/util/inspect:1058:9)
    at formatValue (node:internal/util/inspect:844:10)
    at inspect (node:internal/util/inspect:368:10)
    at Ee.i.<computed> (.pnpm\@prisma+client@5.4.1_prisma@5.4.1\node_modules\@prisma\client\runtime\library.js:26:8097)
    at formatValue (node:internal/util/inspect:809:19)
    at formatProperty (node:internal/util/inspect:1949:11)
    at formatRaw (node:internal/util/inspect:1058:9)
    at formatValue (node:internal/util/inspect:844:10)
    at inspect (node:internal/util/inspect:368:10)
    at Ee.i.<computed> (.pnpm\@prisma+client@5.4.1_prisma@5.4.1\node_modules\@prisma\client\runtime\library.js:26:8097)
    at formatValue (node:internal/util/inspect:809:19)
    at formatProperty (node:internal/util/inspect:1949:11)
    at formatRaw (node:internal/util/inspect:1058:9)
    at formatValue (node:internal/util/inspect:844:10)

```

### How to reproduce

```ts
 const { PrismaClient } = await import("@prisma/client")
 const db = new PrismaClient()
console.log(db)
```

### Prisma information

@prisma/client :  5.4.1

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./voerka.db"
}

model Meta{
    @@map("voerka_meta")
    id  Int @id @default(autoincrement())
    seed Boolean? @default(false)      
}
 
model Dept{
    @@map("voerka_depts")
    id            String @id               
    name          String?       
    title         String?    
    level         Int? @default(0)  
    description   String? 
    code          String?           
    createdAt     DateTime @default(now())
    updatedAt     DateTime @updatedAt     
    manager       User?  @relation("dept-manager",fields: [managerId], references: [id])
    managerId     String? @unique
    users         User[] @relation("dept") 
    lv            Int?                  
    lft           Int?
    rgt           Int?
}

model UserGroup{
    @@map("voerka_user_group")
    id            String @id                 
    name          String?           
    title         String?                   
    description   String?             
    code          String?                 
    super         Boolean @default(false) 
    users         User[] @relation("group") 
    manager       User?  @relation("group-manager",fields: [managerId], references: [id])
    managerId     String? @unique
}
 
model User{
    @@map("voerka_users")
    id        String @id               
    name      String?                  
    title     String?                    
    email     String? @unique               
    emailVerified Boolean @default(false)    
    phone     String? @unique            
    phoneVerified Boolean @default(false)   
    super     Boolean                        
    avatar    String?                       
    enabled   Boolean                       @default(true)                    
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
    deletedAt DateTime?
    settings  String?                     
    managedDept Dept? @relation("dept-manager")
    deptId    String?                       
    dept      Dept? @relation("dept",fields: [deptId], references: [id])  
    managedGroup UserGroup? @relation("group-manager")
    groupId   String?
    group     UserGroup? @relation("group",fields: [groupId], references: [id]) 
}
  
model LocalAuthAccount{
    @@map("voerka_local_auth_accounts")
    userId String  @id @unique                
    password String                            
    createdAt DateTime @default(now())
    expireAt DateTime?                         
    enabled Boolean                       
}
 
model SmsAuthAccount{
    @@map("voerka_sms_auth_accounts")
    userId String  @id @unique                
    verifyCode String                 
    createdAt DateTime @default(now())
    expireAt DateTime?          
}

model JwtAuthAccount{
    @@map("voerka_jwt_auth_accounts")
    userId String  @id @unique 
    token String                         
    createdAt DateTime @default(now())
    expireAt DateTime?       
    enabled Boolean       
} 
 
model Resource{
    @@map("voerka_resources")
    name        String @id @default(cuid())    
    title       String?                         
    type        String?                        
    description String?                         
    lv            Int?                   
    lft           Int?
    rgt           Int? 
}
 

// 权限
model Permission{
    @@map("voerka_permissions")
    id          String @id @default(cuid())
    name        String                          
    description String?                     
    lv            Int?                   
    lft           Int?
    rgt           Int?
}

model PermissionAssign{
    @@map("voerka_assign_perms")
    id          String @id @default(cuid()) 
    user        String? 
    dept        String?
    group       String?
    // 对象：资源
    resource    String 
    permission  String    
    enabled     Boolean @default(true)
    createdAt   DateTime @default(now())
    updatedAt   DateTime @updatedAt
    expireAt    DateTime?                     
}
 
model UserLogs{
    @@map("voerka_user_logs")
    id        Int @id @default(autoincrement())
    user      String           
    type      String?          
    action    String            
    ip        String?
    createdAt DateTime   @default(now())    
} 

```

### Environment & setup

- OS:  Windows
- Database:  SQLite
- Node.js version:  v22.11.0
- @prisma/client :  5.4.1

### Prisma Version

```
@prisma/client :  5.4.1
"prisma": "^5.4.1",
```

**Comment by ludralph** [comment]
Hi @zhangfisher 

Do you experience this error. when you use the latest version 6.1.0 of Prisma?

**Comment by zhangfisher** [comment]
Upgraded to a new version resolved
