### ISSUE TITLE
Unknown argument. Availabe options are marked with ?

### ISSUE THREAD

**Issue by alisufiyan12** [prisma/prisma#25796]
### Bug description

Invalid `prisma.uploadedProduct.create()` invocation:

{
  data: {
    id: "cm49xnvyh0000cr84tgxl09x1",
    userName: "masonmiles",
    status: "delivered",
    ~~~~~~
    requestId: "6d52e65a-bbc2-4b92-ae2e-429c944167b3",
    title: "kasnka",
    description: "kdbaksdb",
    tiktokAds: [
      "kajbsdk",
      "kajsbd"
    ],
    fbAds: [
      "a,msnd",
      "da,msnd"
    ],
    winningCreative: "a,smnd",
    imageUrls: [
      "https://res.cloudinary.com/dmcgxohj3/image/upload/v1733334200/p4_hv7anp.jpg",
      "https://res.cloudinary.com/dmcgxohj3/image/upload/v1733334203/p3_ryt3ef.jpg",
      "https://res.cloudinary.com/dmcgxohj3/image/upload/v1733334201/p2_ckw5dy.jpg",
      "https://res.cloudinary.com/dmcgxohj3/image/upload/v1733334205/p1_xqmogg.jpg"
    ],
?   createdAt?: DateTime,
?   updatedAt?: DateTime
  }
}

Unknown argument `status`. Available options are marked with ?.
    at wn (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/@prisma/client/runtime/library.js:29:1363)
    at $n.handleRequestError (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/@prisma/client/runtime/library.js:121:6958)
    at $n.handleAndLogRequestError (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async POST (webpack-internal:///(rsc)/./app/api/products/singlesubrequests/statusupdater/route.ts:35:25)
    at async /home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63809
    at async eU.execute (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53964)
    at async eU.handle (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:65062)
    at async doRender (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/base-server.js:1315:42)
    at async cacheEntry.responseCache.get.routeKind (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/base-server.js:1537:28)
    at async DevServer.renderToResponseWithComponentsImpl (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/base-server.js:1445:28)
    at async DevServer.renderPageComponent (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/base-server.js:1842:24)
    at async DevServer.renderToResponseImpl (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/base-server.js:1880:32)
    at async DevServer.pipeImpl (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/base-server.js:893:25)
    at async NextNodeServer.handleCatchallRenderRequest (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/next-server.js:269:17)
    at async DevServer.handleRequestImpl (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/base-server.js:789:17)
    at async /home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/dev/next-dev-server.js:331:20
    at async Span.traceAsyncFn (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/trace/trace.js:151:20)
    at async DevServer.handleRequest (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/dev/next-dev-server.js:328:24)
    at async invokeRender (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/home/ligrey/Desktop/bolt-drill-blogger-aienhancer/node_modules/next/dist/server/lib/start-server.js:140:13) {
  clientVersion: '5.22.0'
}

### How to reproduce

<!--
1. Go to '...'
2. Change '....'
3. Run '....'
4. See error
-->


### Expected behavior

When i try to submit the form or push the required data to neondb using the pirsma schema it generated this error: Unknown argument `status`. Available options are marked with ?.
even though clearly I am passing the status from my code: 

this is my main code file: 
"use client";
import { useEffect, useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Upload } from "lucide-react";

interface UploadDialogProps {
  request: {
    id: string;
    username: string;
    requestid: string;
    status: string;
  } | null;
  onClose: () => void;
  onComplete: (requestId: string) => void;
}

interface FormData {
  images: File[];
  title: string;
  description: string;
  tiktokAds: string[];
  fbAds: string[];
  winningCreative: string;
  status: string;
}

const initialFormData: FormData = {
  images: [],
  title: "",
  description: "",
  tiktokAds: ["", ""],
  fbAds: ["", ""],
  winningCreative: "",
  status: "", // Default to pending
};

export function UploadDialog({ request, onClose, onComplete }: UploadDialogProps) {
  const [formData, setFormData] = useState<FormData>(initialFormData);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>, index: number) => {
    const files = e.target.files;
    if (files && files[0]) {
      const newImages = [...formData.images];
      newImages[index] = files[0];
      setFormData({ ...formData, images: newImages });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!request || formData.status !== "delivered") return;

    try {
      const uploadedImages = await Promise.all(
        formData.images.map(async (image) => {
          const imageData = new FormData();
          imageData.append("file", image);
          imageData.append("upload_preset", "ml_default"); // Replace with your preset
          const response = await fetch("https://api.cloudinary.com/v1_1/dmcgxohj3/image/upload", {
            method: "POST",
            body: imageData,
          });
          const data = await response.json();
          return data.secure_url;
        })
      );

      const dbResponse = await fetch("/api/products/singlesubrequests/statusupdater", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: request.id,
          userName: request.username,
          requestId: request.requestid,
          status: formData.status,
          title: formData.title,
          description: formData.description,
          tiktokAds: formData.tiktokAds,
          fbAds: formData.fbAds,
          winningCreative: formData.winningCreative,
          imageUrls: uploadedImages,
        }),
      });

      if (!dbResponse.ok) {
        throw new Error("Failed to upload product details to the database.");
      }

      onComplete(request.id);
    } catch (error) {
      console.error("Error uploading product details:", error);
      alert("Failed to upload product details. Please try again.");
    }
  };

  if (!request) {
    return null;
  }

  return (
    <Dialog open={!!request} onOpenChange={() => onClose()}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>Upload Product Details</DialogTitle>
        </DialogHeader>

        <div className="overflow-y-auto max-h-[80vh] space-y-6">
          <p className="text-gray-500 mb-4">
            User Name: <span className="font-semibold">{request.username}</span>
            <br />
            User ID: <span className="font-semibold">{request.id}</span>
            <br />
            Request ID: <span className="font-semibold">{request.requestid}</span>
            <br />
            Current Status: <span className="font-semibold">{formData.status}</span>
          </p>

          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Image Uploads */}
            <div className="grid grid-cols-2 gap-4">
              {[0, 1, 2, 3].map((index) => (
                <div key={index} className="space-y-2">
                  <label className="text-sm font-medium">
                    Product Image {index + 1}
                  </label>
                  <Input
                    type="file"
                    accept="image/*"
                    onChange={(e) => handleImageChange(e, index)}
                    className="bg-secondary"
                    required
                  />
                </div>
              ))}
            </div>

            {/* Status Toggle */}
            <div className="space-y-2">
              <label className="text-sm font-medium">Status</label>
              <Select
                value={formData.status}
                onValueChange={(value) => setFormData({ ...formData, status: value })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="pending">Pending</SelectItem>
                  <SelectItem value="delivered">Delivered</SelectItem>
                </SelectContent>
              </Select>
              {formData.status !== "delivered" && (
                <p className="text-red-500 text-sm">
                  Before submission, mark as "Delivered."
                </p>
              )}
            </div>

            {/* Product Details */}
            <div className="space-y-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">Product Title</label>
                <Input
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  placeholder="Enter product title"
                  required
                />
              </div>

              <div className="space-y-2">
                <label className="text-sm font-medium">Product Description</label>
                <Textarea
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  placeholder="Enter product description"
                  required
                />
              </div>
            </div>

            {/* TikTok Ads */}
            <div className="space-y-4">
              <label className="text-sm font-medium">TikTok Ad Links</label>
              <div className="grid grid-cols-2 gap-4">
                {formData.tiktokAds.map((link, index) => (
                  <Input
                    key={index}
                    value={formData.tiktokAds[index]}
                    onChange={(e) => {
                      const newAds = [...formData.tiktokAds];
                      newAds[index] = e.target.value;
                      setFormData({ ...formData, tiktokAds: newAds });
                    }}
                    placeholder={`TikTok Ad Link ${index + 1}`}
                    required
                  />
                ))}
              </div>
            </div>

            {/* Facebook Ads */}
            <div className="space-y-4">
              <label className="text-sm font-medium">Facebook Ad Links</label>
              <div className="grid grid-cols-2 gap-4">
                {formData.fbAds.map((link, index) => (
                  <Input
                    key={index}
                    value={formData.fbAds[index]}
                    onChange={(e) => {
                      const newAds = [...formData.fbAds];
                      newAds[index] = e.target.value;
                      setFormData({ ...formData, fbAds: newAds });
                    }}
                    placeholder={`Facebook Ad Link ${index + 1}`}
                    required
                  />
                ))}
              </div>
            </div>

            {/* Winning Creative */}
            <div className="space-y-2">
              <label className="text-sm font-medium">Winning Creative Link</label>
              <Input
                value={formData.winningCreative}
                onChange={(e) => setFormData({ ...formData, winningCreative: e.target.value })}
                placeholder="Enter winning creative link"
                required
              />
            </div>

            <Button
              type="submit"
              className="w-full"
              disabled={formData.status !== "delivered"}
            >
              <Upload className="mr-2 h-4 w-4" />
              Upload Product Details
            </Button>
          </form>
        </div>
      </DialogContent>
    </Dialog>
  );
}


and this is my route: import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    const {
      id,
      userName,
      requestId,
      title,
      description,
      tiktokAds,
      fbAds,
      winningCreative,
      imageUrls,
      status, // Include status from the form
    } = body;

    // Validate required fields
    const requiredFields = ["id", "userName", "requestId", "title", "description", "tiktokAds", "fbAds", "imageUrls", "status"];

    for (const field of requiredFields) {
      if (!body[field] || (Array.isArray(body[field]) && !body[field].length)) {
        return NextResponse.json(
          { error: `${field} is required.` },
          { status: 400 }
        );
      }
    }

    // Create the uploaded product in the database with the submitted status
    const product = await prisma.uploadedProduct.create({
      data: {
        id,
        userName,
        status, // Use the submitted status
        requestId,
        title,
        description,
        tiktokAds,
        fbAds,
        winningCreative,
        imageUrls,
      },
    });

    // Update the status of all matching SingleSubRequests
    await prisma.singleSubRequest.updateMany({
      where: { requestId },
      data: { status }, // Use the submitted status for consistency
    });

    return NextResponse.json({ success: true, data: product }, { status: 201 });
  } catch (error) {
    console.error("Error saving product to database:", error);

    if (error instanceof Error) {
      return NextResponse.json(
        { error: error.message },
        { status: 500 }
      );
    }

    return NextResponse.json(
      { error: "An unexpected error occurred." },
      { status: 500 }
    );
  }
}




### Prisma information

This is my shchema:

model UploadedProduct {
  id              String    @id @default(cuid())
  requestId       String?
  status          String    // Status will be taken from the submitted form
  userName        String
  title           String
  description     String
  tiktokAds       String[]
  fbAds           String[]
  winningCreative String
  imageUrls       String[]
  createdAt       DateTime  @default(now())
  updatedAt       DateTime  @updatedAt
}

model SingleSubRequest {
  id               String    @id @default(cuid())
  requestId        String?   @unique
  status           String    @default("Pending") // Status field for updates
  userName         String
  fullName         String
  email            String
  shopify          String?
  phone            String
  productCost      Float
  marketingBudget  Float
  storeType        String
  productType      String
  additionalDetails String?
  termsAccepted    Boolean
  createdAt        DateTime  @default(now())
  updatedAt        DateTime  @updatedAt
}


### Environment & setup

- OS: Linux -> Ubuntu
- Database: PostgreSQL using Prisma with Neondb
- Node.js version: latest node version


### Prisma Version

```

```

**Comment by ludralph** [comment]
Hi @alisufiyan12 

The `status` field is not recognized in the `UploadedProduct` schema. Did you run `prisma generate` command to sync the client and the schema?
