### ISSUE TITLE
Conversion failed: expected a string in column 'createdAt', found {} on `adapter-neon`

### ISSUE THREAD

**Issue by chenqianhe** [prisma/prisma#25799]
### Bug description

After using neon adapter and http, it appears:

```
PrismaClientKnownRequestError: 
Invalid `prisma.assignment.findMany()` invocation:


Inconsistent column data: Conversion failed: expected a string in column 'createdAt', found {}
    at Mn.handleRequestError (/Users/chenqianhe/WebstormProjects/learnieai-sveltekit-main-dev/node_modules/@prisma/client/runtime/library.js:121:7338)
    at Mn.handleAndLogRequestError (/Users/chenqianhe/WebstormProjects/learnieai-sveltekit-main-dev/node_modules/@prisma/client/runtime/library.js:121:6663)
    at Mn.request (/Users/chenqianhe/WebstormProjects/learnieai-sveltekit-main-dev/node_modules/@prisma/client/runtime/library.js:121:6370)
    at async l (/Users/chenqianhe/WebstormProjects/learnieai-sveltekit-main-dev/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async Promise.all (index 0)
    at async Module.listAssignmentAndProblemset (/Users/chenqianhe/WebstormProjects/learnieai-sveltekit-main-dev/src/routes/api/v1/assignment/listWithProblemSet/index.ts:4:47)
    at async Promise.all (index 0)
    at async load (/Users/chenqianhe/WebstormProjects/learnieai-sveltekit-main-dev/src/routes/(app)/teacher/(aitutor)/+layout.server.ts?sentry-auto-wrap:20:41)
    at async Module.load_server_data (/Users/chenqianhe/WebstormProjects/learnieai-sveltekit-main-dev/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:61:17)
    at async eval (/Users/chenqianhe/WebstormProjects/learnieai-sveltekit-main-dev/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:140:13)
```

### How to reproduce

1. Use PrismaNeonHTTP
2. Query data
3. error

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["views", "driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Assignment {
  id                   String                 @id @default(dbgenerated("gen_random_uuid()"))
  name                 String
  createdAt            DateTime               @default(now())
  updatedAt            DateTime               @updatedAt
}
```

```ts
import { neon } from "@neondatabase/serverless";
import { PrismaNeonHTTP } from "@prisma/adapter-neon";
import { PrismaClient } from "@prisma/client";
import { requireEnvironmentVariable } from "./load-dotenv";

const connection = neon(
    `${requireEnvironmentVariable("DATABASE_URL")}?pgbouncer=true&connect_timeout=30&connection_limit=10000&pool_timeout=0`
);
const adapter = new PrismaNeonHTTP(connection);
const prisma = new PrismaClient({
    adapter,
});

export default prisma;
```

### Environment & setup

- OS: macOS
- Database: PostgreSQL (Neon)
- Node.js version: 18.20.5

### Prisma Version

```
prisma                : 5.4.2
@prisma/client        : 6.0.0
Current platform      : darwin-arm64
Query Engine (Binary) : query-engine ac9d7041ed77bcc8a8dbd2ab6616b39013829574 (at ../../.cache/prisma-python/binaries/5.4.2/ac9d7041ed77bcc8a8dbd2ab6616b39013829574/node_modules/@prisma/engines/query-engine-darwin-arm64)
Schema Engine         : schema-engine-cli ac9d7041ed77bcc8a8dbd2ab6616b39013829574 (at ../../.cache/prisma-python/binaries/5.4.2/ac9d7041ed77bcc8a8dbd2ab6616b39013829574/node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm           : @prisma/prisma-schema-wasm 5.4.1-2.ac9d7041ed77bcc8a8dbd2ab6616b39013829574
Default Engines Hash  : ac9d7041ed77bcc8a8dbd2ab6616b39013829574
Studio                : 0.494.0
Preview Features      : driverAdapters, views
```

**Comment by andyjy** [comment]
I suspect this is likely fixed by https://github.com/prisma/prisma/pull/25515 which is now merged to be released in the next version 6.1, you could try manually patching your local Prisma install in the interim to verify (which is what I have been doing)

**Comment by ludralph** [comment]
Hi @chenqianhe 

I can reproduce this issue. The issue also exist on the latest Pisma version 6.1.0. This has mostly to do with date parsing because the query below executes correctly and returns a response
```js
const users = await db.user.findMany({
    select: {
        email: true,
        firstName: true,
    },
});
```
while this other query throws the error. So I'll be adding this to the queue.
```js
const users = await db.user.findMany({
    select: {
        email: true,
        firstName: true,
        createdAt:true
    },
});

```

**Comment by pvcnt** [comment]
I am hitting the exact same issue with Neon and Prisma 6.7.0. I can confirm that the issue is with the adapter-neon, it works fine if using adapter-pg.
