### ISSUE TITLE
Null constraint violation on the (not available)

### ISSUE THREAD

**Issue by JacobwBruce** [prisma/prisma#25805]
### Bug description

I'm using prisma with a PlanetScale database. Everything has looked good for about 2 years now but we recently made pushed changes and now we get the following error

```
error - PrismaClientKnownRequestError:
Invalid `prisma.driver.create()` invocation:


Null constraint violation on the (not available)
    at zr.handleRequestError (/Users/jacob/Documents/American_Expediting/code/vic/node_modules/@prisma/client/runtime/library.js:122:8308)
    at zr.handleAndLogRequestError (/Users/jacob/Documents/American_Expediting/code/vic/node_modules/@prisma/client/runtime/library.js:122:7697)
    at zr.request (/Users/jacob/Documents/American_Expediting/code/vic/node_modules/@prisma/client/runtime/library.js:122:7307)
    at async handleDriverContracted (webpack-internal:///(api)/./src/utils/integrations/openforce/create.ts:67:23)
    at async Object.apiResolver (/Users/jacob/Documents/American_Expediting/code/vic/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async DevServer.runApi (/Users/jacob/Documents/American_Expediting/code/vic/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/Users/jacob/Documents/American_Expediting/code/vic/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/Users/jacob/Documents/American_Expediting/code/vic/node_modules/next/dist/server/router.js:243:32)
    at async DevServer.runImpl (/Users/jacob/Documents/American_Expediting/code/vic/node_modules/next/dist/server/base-server.js:432:29)
    at async DevServer.run (/Users/jacob/Documents/American_Expediting/code/vic/node_modules/next/dist/server/dev/next-dev-server.js:831:20)
    at async DevServer.handleRequestImpl (/Users/jacob/Documents/American_Expediting/code/vic/node_modules/next/dist/server/base-server.js:375:20)
    at async /Users/jacob/Documents/American_Expediting/code/vic/node_modules/next/dist/server/base-server.js:157:99 {
  code: 'P2011',
  clientVersion: '5.0.0',
  meta: { constraint: null },
  page: '/api/webhooks/openforce'
}
```

The issue occurred after after creating a migration for the Capacity table that looks like this
```SQL
-- AlterTable
ALTER TABLE `Driver` ADD COLUMN `capacityId` INTEGER NULL;

-- CreateTable
CREATE TABLE `Capacity` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `status` ENUM('PENDING', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
    `serviceType` ENUM('ROUTE', 'ON_DEMAND') NOT NULL,
    `startTime` DATETIME(3) NOT NULL,
    `completionTime` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `lastModifiedTime` DATETIME(3) NOT NULL,
    `numberOfDriversNeeded` INTEGER NOT NULL,
    `vehicleTypeNeeded` VARCHAR(191) NOT NULL,
    `cityId` INTEGER NOT NULL,
    `notes` TEXT NULL,
    `createdById` INTEGER NOT NULL,
    `tsaRequired` BOOLEAN NOT NULL DEFAULT false,
    `markenRequired` BOOLEAN NOT NULL DEFAULT false,
    `parcelShieldRequired` BOOLEAN NOT NULL DEFAULT false,
    `dgRequired` BOOLEAN NOT NULL DEFAULT false,
    `dg7Required` BOOLEAN NOT NULL DEFAULT false,
    `monday` VARCHAR(191) NULL,
    `tuesday` VARCHAR(191) NULL,
    `wednesday` VARCHAR(191) NULL,
    `thursday` VARCHAR(191) NULL,
    `friday` VARCHAR(191) NULL,
    `saturday` VARCHAR(191) NULL,
    `sunday` VARCHAR(191) NULL,

    INDEX `Capacity_cityId_idx`(`cityId`),
    INDEX `Capacity_createdById_idx`(`createdById`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `Driver_capacityId_idx` ON `Driver`(`capacityId`);
```

And updating the prisma version, this was in my package.json before:
```
"@prisma/client": "5",
"prisma": "5",
```
And this was after
```
"@prisma/client": "5",
"prisma": "^5.22.0",
```

I've tried reversing the prisma version to what it was before, ugrading to the newest version, all while generating a new prisma schema with each one, nothing seems to work. I've also tried reversing the migration but that didn't solve it either

It's important to note that everything works great when connected to a local MySQL docker image, the error only occurs when connected to the PlanetScale DB.

I also happens everytime I call prisma.driver.create() it doesn't matter what the arguments are for it. However, raw SQL works, it just seems to be an issue with the prisma client

### How to reproduce

1. Use this schema on a PlanetScale DB with the same prisma version number
2. Call prisma.driver.create() with any arguments
3. See error

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  // previewFeatures = ["fullTextSearch", "fullTextIndex"]
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}


model Driver {
  id                                    Int                   @id @default(autoincrement())
  firstName                             String
  lastName                              String
  icNumber                              String                @unique
  email                                 String                @unique
  phone                                 String
  startDate                             DateTime?
  entryDate                             DateTime              @default(now())
  welcomeCallDate                       DateTime?
  howFoundAmex                          String?
  DGTC                                  DateTime?
  DG7                                   DateTime?
  DTP                                   Boolean               @default(false)
  dtpExpiry                             DateTime?
  kiteCatalent                          Boolean               @default(false)
  kiteCatalentExpiry                    DateTime?
  type                                  DriverType            @default(VENDOR)
  updatedAt                             DateTime              @updatedAt
  updatedById                           Int?
  updatedBy                             User?                 @relation(fields: [updatedById], references: [id], name: "UpdatedBy")
  cityId                                Int
  badgeOrdered                          DateTime?
  firstContact                          DateTime?
  notes                                 String?               @db.Text
  status                                Status                @default(ACTIVE)
  deactivatedDate                       DateTime?
  deactivatedReason                     String?
  // outOfServiceDate                      DateTime?
  // outOfServiceReason                    String?
  picture                               String?               @db.VarChar(255)
  businessName                          String?
  cbcCertified                          Boolean               @default(false)
  cbcDate                               DateTime?
  mvrCertified                          Boolean               @default(false)
  mvrDate                               DateTime?
  tsaCertified                          Boolean               @default(false)
  markenCatalent                        Boolean               @default(false)
  markenCatalentExpiryDate              DateTime?
  patheonAvillion                       Boolean               @default(false)
  patheonDTP                            Boolean               @default(false)
  quickStatBMS                          Boolean               @default(false)
  markenBMS                             Boolean               @default(false)
  markenBMSExpiryDate                   DateTime?
  markenCollectionProcess               Boolean               @default(false)
  markenCollectionProccessExpiryDate    DateTime?
  markenDispatchToCarrier               Boolean               @default(false)
  markenDispatchToCarrierExpiryDate     DateTime?
  markenRecoveryFromCarrier             Boolean               @default(false)
  markenRecoveryFromCarrierExpiryDate   DateTime?
  markenFinalDelivery                   Boolean               @default(false)
  markenFinalDeliveryExpiryDate         DateTime?
  markenDryIce                          Boolean               @default(false)
  markenDryIceExpiryDate                DateTime?
  markenSensitech                       Boolean               @default(false)
  markenSensitechExpiryDate             DateTime?
  markenVehicleBreakdown                Boolean               @default(false)
  markenVehicleBreakdownExpiryDate      DateTime?
  markenDTPDriverInstructions           Boolean               @default(false)
  markenDTPDriverInstructionsExpiryDate DateTime?
  markenGoodDocumentation               Boolean               @default(false)
  markenGoodDocumentationExpiryDate     DateTime?
  address                               String?
  deactivatedById                       Int?
  backgroundCheck                       CertApplication?
  backgroundDate                        DateTime?
  ein                                   String?
  staNumber                             String?
  vehicleTypeString                     String?
  pictureFileName                       String?               @unique @default(uuid()) @db.VarChar(255)
  lastJobDate                           DateTime?
  lastSettlementDate                    DateTime?
  logs                                  Log[]
  vehicles                              Vehicle[]
  incidents                             Incident[]
  comments                              Comment[]
  driverAvailability                    DriverAvailability[]
  city                                  City                  @relation(fields: [cityId], references: [id])
  deactivatedBy                         User?                 @relation(fields: [deactivatedById], references: [id], name: "DeactivatedBy")
  certifications                        DriverCertification[]
  Capacity                              Capacity?             @relation(fields: [capacityId], references: [id])
  capacityId                            Int?

  @@index([cityId])
  @@index([deactivatedById])
  @@index([updatedById])
  @@index([capacityId])
}


model Capacity {
  id                    Int            @id @default(autoincrement())
  status                CapacityStatus @default(PENDING)
  serviceType           ServiceType
  startTime             DateTime
  completionTime        DateTime?
  createdAt             DateTime       @default(now())
  lastModifiedTime      DateTime       @updatedAt
  numberOfDriversNeeded Int
  vehicleTypeNeeded     String
  cityId                Int
  city                  City           @relation(fields: [cityId], references: [id])
  notes                 String?        @db.Text
  createdById           Int
  createdBy             User           @relation(fields: [createdById], references: [id], onDelete: Cascade, name: "CreatedBy")
  tsaRequired           Boolean        @default(false)
  markenRequired        Boolean        @default(false)
  parcelShieldRequired  Boolean        @default(false)
  dgRequired            Boolean        @default(false)
  dg7Required           Boolean        @default(false)
  monday                String?
  tuesday               String?
  wednesday             String?
  thursday              String?
  friday                String?
  saturday              String?
  sunday                String?
  drivers               Driver[]

  @@index([cityId])
  @@index([createdById])
}

enum CapacityStatus {
  PENDING
  COMPLETED
}

enum ServiceType {
  ROUTE
  ON_DEMAND
}

enum Status {
  ACTIVE
  INACTIVE
  IDLE
  // OUT_OF_SERVICE
}

enum CertApplication {
  APPROVED
  DENIED
}

enum DriverType {
  APPLICANT
  VENDOR
  AGENT
}

```

```ts
import { PrismaClient } from "@prisma/client";

const createPrismaClient = () =>
  new PrismaClient({
    log: ["error", "info", "warn", "query"],
  });

const globalForPrisma = globalThis as unknown as {
  prisma: ReturnType<typeof createPrismaClient> | undefined;
};

const db = globalForPrisma.prisma ?? createPrismaClient();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = db;

export default db;
```

### Environment & setup

- OS: macOS
- Database:PlanetScale
- Node.js version: v22.9.0

### Prisma Version

```
prisma                  : 5.0.0
@prisma/client          : 5.0.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584 (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Default Engines Hash    : 6b0aef69b7cdfc787f822ecd7cdc76d5f1991584
Studio                  : 0.487.0
```

**Comment by JacobwBruce** [comment]
update: it appears to be with this column on the driver table:
```
  deactivatedDate                       DateTime?
```

But I have now idea why, its marked as optional and I have other DateTime fields in there that are also marked as optional that don't throw this error

**Comment by ludralph** [comment]
Hi @JacobwBruce 

Can you please enable [debugging](https://www.prisma.io/docs/orm/prisma-client/debugging-and-troubleshooting/debugging) and share the complete logs here?

**Comment by guyrandalf** [comment]
I faced this issue when I worked with Prisma and my table in Supabase. Since I did not have any important records in there, I deleted the table and recreated it. Ran `npx prisma migrate` and all is fine now.

**Comment by Ariastarcos** [comment]
This happened in one of our projects after removing a column, but not creating a new migration for this.

We resolved it by running running `prisma migrate dev && prisma generate`, which printed the following information:

```
⚠️  Warnings for the current datasource:                                                                                                                                       
  • You are about to drop the column `x` on the `y` table, which still contains z non-null values.
```

After applying this migration, and re-generating the client (as we did in the command) the issue is resolved. Hope this helps someone!

Using:

```
"prisma": "^6.19.0"
"@prisma/client": "^6.19.0"
"@prisma/adapter-pg": "^6.19.0"
```

**Comment by AliSeleem** [comment]
Long live for devs discussions and F*ck AI
