### ISSUE TITLE
strictUndefinedChecks does not work with query extensions

### ISSUE THREAD

**Issue by georgewitteman** [prisma/prisma#25845]
### Bug description

When using the `$allModels.$allOperations` query extension, any usages of `Prisma.skip` cause an error to be thrown.

### How to reproduce

1. Set `Prisma.skip` in a create query for a prisma client with query extensions
2. Running the file will trigger an error like this:
```
PrismaClientValidationError: 
Invalid `prisma.employee.create()` invocation in
/tmp/tmp.MOsQACwvAB/2024-12-12T233959/index.js:20:17

  17         }
  18     }
  19 });
→ 20 prisma.employee.create({
       data: {
         email: "0.19827359060498662@example.com",
         name: {}
               ~~
       }
     })

Argument `name`: Invalid value provided. Expected String or Null, provided Object.
    at En (/tmp/tmp.MOsQACwvAB/2024-12-12T233959/node_modules/@prisma/client/runtime/library.js:29:1363)
    at Mn.handleRequestError (/tmp/tmp.MOsQACwvAB/2024-12-12T233959/node_modules/@prisma/client/runtime/library.js:121:6981)
    at Mn.handleAndLogRequestError (/tmp/tmp.MOsQACwvAB/2024-12-12T233959/node_modules/@prisma/client/runtime/library.js:121:6663)
    at Mn.request (/tmp/tmp.MOsQACwvAB/2024-12-12T233959/node_modules/@prisma/client/runtime/library.js:121:6370)
    at async l (/tmp/tmp.MOsQACwvAB/2024-12-12T233959/node_modules/@prisma/client/runtime/library.js:130:9633) {
  clientVersion: '6.0.1'
}
```

### Expected behavior

An error is not thrown

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["strictUndefinedChecks"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Employee {
  id    String @id @default(cuid())
  name  String?
  email String @unique
}
```

```ts
const prisma = new PrismaClient().$extends({
    query: {
        $allModels: {
          // Example query extension that does nothing
          $allOperations: async (params) => params.query(params.args),
        }
    }
});

prisma.employee.create({ data: { email: `${Math.random()}@example.com`, name: Prisma.skip } }).then((result) => {
    console.log(result)
}).catch((error) => {
    console.error(error)
})
```

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: v20.18.0

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 6.0.1
@prisma/client          : 6.0.1
Computed binaryTarget   : debian-openssl-1.1.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.18.0
Query Engine (Node-API) : libquery-engine 5dbef10bdbfb579e07d35cc85fb1518d357cb99e (at node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Schema Engine           : schema-engine-cli 5dbef10bdbfb579e07d35cc85fb1518d357cb99e (at node_modules/@prisma/engines/schema-engine-debian-openssl-1.1.x)
Schema Wasm             : @prisma/prisma-schema-wasm 5.23.0-27.5dbef10bdbfb579e07d35cc85fb1518d357cb99e
Default Engines Hash    : 5dbef10bdbfb579e07d35cc85fb1518d357cb99e
Studio                  : 0.503.0
Preview Features        : strictUndefinedChecks
```

**Comment by georgewitteman** [comment]
Noticed a different failure in a `create()` call:

```
[server]:       'Invalid `prisma.checkout.count()` invocation in\n' +
[server]:       '/.../index.ts:1070:19\n' +
[server]:       '\n' +
[server]:       '  1067 };\n' +
[server]:       '  1068 \n' +
[server]:       '  1069 export const getTransactionCount = async (makerId: string, filters?: TransactionFilter) =>\n' +
[server]:       '→ 1070   prisma.checkout.count({\n' +
[server]:       '           select: {\n' +
[server]:       '             _count: {\n' +
[server]:       '               select: {\n' +
[server]:       '                 _all: true\n' +
[server]:       '               }\n' +
[server]:       '             }\n' +
[server]:       '           },\n' +
[server]:       '           where: {\n' +
[server]:       '             field1: "test",\n' +
[server]:       '             field2: "test",\n' +
[server]:       '             createdAt: {\n' +
[server]:       '               gte: {\n' +
[server]:       '         +       _ref: String\n' +
[server]:       '               },\n' +
[server]:       '               lt: {}\n' +
[server]:       '             }\n' +
[server]:       '           }\n' +
[server]:       '         })\n' +
[server]:       '\n' +
[server]:       'Argument `_ref` is missing.',
```

**Comment by p-j** [comment]
having the same issue, I've setup a recursive `removeUndefined` function and wrapped all my create/update objects in it to "fix" this.

**Comment by ludralph** [comment]
Hi @georgewitteman 

Thank you for raising this issue.

I can confirm it and will add it to the bug queue.

**Comment by g3yuri** [comment]
Is there any solution? Today in my project, when using `$extends`, I encountered the error mentioned in the first post. I tried different combinations like `model.$allModels`, `query.$allOperations`, and the value of `Prisma.skip` appears as `{}`, resulting in an error. I temporarily solved it by using `$use`.
