### ISSUE TITLE
PrismaClient throw error on missing is env even when overwriting database connection

### ISSUE THREAD

**Issue by husseinraoouf** [prisma/prisma#2609]
## Bug description
when creating a new PrismaClient it throws an error with the following message `error: Environment variable not found: DATABASE_URL.` even when I am providing a different database url to the Prisma client constructor

but if the url in `schema.prisma` is not `env()` it connects normally to the provided url from the constructor

I think the problem is that Prisma client evaluate  `env()` even though it is not needed

schema.prisma
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

index.js
```js
const { PrismaClient } = require('@prisma/client')
const config = require('../config');

const prisma = new PrismaClient({
  datasources: {
      db: config.databaseUrl
  },  
})
prisma.connect()
```

## How to reproduce

1. set the db url to env("ANY_THING") in `schema.prisma` file
2. Prisma generate
3. create index.js with the following code
```js
const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient({
  datasources: {
      db: "Valid Database Url"
  },  
})
prisma.connect()
```
4. run index.js

## Expected behavior
Prisma client connects normally to the provided url from the constructor even when the environment variable is not found

## Environment & setup

- OS: NixOS
- Database: PostgreSQL
- Prisma version: 2.0.0-alpha.1272
- Node.js version: 13.8.0

**Comment by husseinraoouf** [comment]
a temp workaround is to set the environment variable to dummy connection string like this
```
process.env.DATABASE_URL = "postgresql://dumy";
```

or assigning the connection string to the environment variable instead of providing it in the Prisma client constructor

**Comment by aakashkag** [comment]
Also not sure how to handle this environment variable in production.

**Comment by defrex** [comment]
This doesn't seem to be resolved. I was having the same issue, so I upgraded to `2.2.0` which should include the merged PR. However, I still received the following error.

```
error: Error validating datasource `db`: You must provide a nonempty URL for the datasource `db`. The environment variable `DATABASE_URL` resolved to an empty string.
-->  schema.prisma:7
| 
6 |   provider = \"postgresql\"
7 |   url      = env(\"DATABASE_URL\")
```

However, I was able to resolve the error by manually setting `DATABASE_URL` to the `datasource.db.url` value. 

```typescript
const url = `postgresql://${config.dbUsername}:${config.dbPassword}@${config.dbHost}:${config.dbPort}/${config.dbName}`

process.env.DATABASE_URL = url

prisma = new PrismaClient({
  datasources: { db: { url } },
})
```

It seems to me that `process.env.DATABASE_URL = url` shouldn't be needed, but currently it is.

**Comment by janpio** [comment]
Can you please share the full output you are getting @defrex? We currently have a tiny bug in the env loading that could affect you.

**Comment by defrex** [comment]
This is what I get if `DATABASE_URL` is unset

```
Error: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   | 
 6 |   provider = "postgresql"
 7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at LineStream.debug (/Users/defrex/Code/treasure/api/node_modules/@prisma/engine-core/dist/NodeEngine.js:451:1)
    at LineStream.emit (events.js:315:20)
    at LineStream.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at LineStream.Readable.push (_stream_readable.js:212:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._lineBuffer (/Users/defrex/Code/treasure/api/node_modules/@prisma/engine-core/dist/byline.js:103:1)
    at LineStream.length [as _transform] (/Users/defrex/Code/treasure/api/node_modules/@prisma/engine-core/dist/byline.js:96:1)
    at LineStream.Transform._read (_stream_transform.js:191:10)
```

If I set via `DATABASE_URL=`, so it's preset but blank, I get

```
Error: error: Error validating datasource `db`: You must provide a nonempty URL for the datasource `db`. The environment variable `DATABASE_URL` resolved to an empty string.
  -->  schema.prisma:7
   | 
 6 |   provider = "postgresql"
 7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at LineStream.debug (/Users/defrex/Code/treasure/api/node_modules/@prisma/engine-core/dist/NodeEngine.js:451:1)
    at LineStream.emit (events.js:315:20)
    at LineStream.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at LineStream.Readable.push (_stream_readable.js:212:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._lineBuffer (/Users/defrex/Code/treasure/api/node_modules/@prisma/engine-core/dist/byline.js:103:1)
    at LineStream.length [as _transform] (/Users/defrex/Code/treasure/api/node_modules/@prisma/engine-core/dist/byline.js:96:1)
    at LineStream.Transform._read (_stream_transform.js:191:10)
```

Finally, if I set a valid-looking but incorrect value, such as `DATABASE_URL=postgres://localhost`, then it works fine.

**Comment by janpio** [comment]
Wait what!? That last part looks super fishy.

Could you please open a new issue and just copy/paste the things you wrote in here to the new issue? Someone should definitely look at this.

**Comment by mavilein** [comment]
Just had a look at the code again and the part in the schema parser is covered by a test. That probably means that either the URL overrides are not provided correctly or they are not parsed correctly by the query engine.

**Comment by defrex** [comment]
I added a cleaner reproduction to the new Issue. Hopefully, that helps.
