### ISSUE TITLE
Prisma studio don't work by version 2.0.0-beta.7

### ISSUE THREAD

**Issue by primaryperson** [prisma/prisma#2611]
When did update scheme pagination (first, last to take)
Prisma studio didn't get update select default
![image](https://user-images.githubusercontent.com/32566617/83339137-743a5300-a2d3-11ea-8cc0-fb3acdd6414b.png)

**Comment by nahtnam** [comment]
I am also experiencing this. Downgrading to beta 6 works

**Comment by sol-idsnake** [comment]
Also experiencing this after fresh DB migrate save/up/generate.

Error in request:  {
  telemetry: true,
  message: 'Unknown arg `first` in first for type Challenge. Did you mean `cursor`?,
  stack: 'Error: Unknown arg `first` in first for type Challenge. Did you mean `cursor`?

    '    at Document.validate (...\\Prisma\\Studio\\-Coding-prisma-2-graphql\\runtime\\index.js:1:100210)\n' +
    '    at Object.s [as Challenge] (...\\Prisma\\Studio\\-Coding-prisma-2-graphql\\runtime\\index.js:1:70857)\n' +
    '    at Object.n.<computed> [as findMany] (...\\Prisma\\Studio\\-Coding-prisma-2-graphql\\runtime\\index.js:1:72200)\n' +  
    '    at eval (eval at Photon.request (...\\AppData\\Roaming\\npm-cache\\_npx\\10660\\node_modules\\@prisma\\cli\\build\\index.js:2:2320106), <anonymous>:5:55)\n' +
    '    at Photon.request (...\\AppData\\Roaming\\npm-cache\\_npx\\10660\\node_modules\\@prisma\\cli\\build\\index.js:2:2320295)\n' +     
    '    at PhotonService.respond (...\\AppData\\Roaming\\npm-cache\\_npx\\10660\\node_modules\\@prisma\\cli\\build\\index.js:2:1312846)\n' +
    '    at WebSocket.StudioServer.onWSMessage (...\\AppData\\Roaming\\npm-cache\\_npx\\10660\\node_modules\\@prisma\\cli\\build\\index.js:2:2528084)\n' +
    '    at WebSocket.emit (events.js:315:20)\n' +
    '    at WebSocket.EventEmitter.emit (domain.js:485:12)\n' +
    '    at Receiver.receiverOnMessage (...\\AppData\\Roaming\\npm-cache\\_npx\\10660\\node_modules\\@prisma\\cli\\build\\index.js:2:2700686)',
  isPanic: undefined,
  code: undefined
} {
  query: 'prisma.challenge.findMany({\n' +
    '  first: 100,
    '  select: {' 
    '   ...'
    '  }
    '})'
}

**Comment by macrozone** [comment]
altough its in beta, prisma team should start to deprecate stuff, before altering it. The stability improvement in beta.7 are much desired, the new pagination api on the other hand is more or less just cosmetics. It's a hard breaking change for something that is not even a new feature...
