### ISSUE TITLE
Error: spawn node --max-old-space-size=8096 .\node_modules\@prisma\client\generator-build\index.js ENOENT

### ISSUE THREAD

**Issue by felinto-dev** [prisma/prisma#2632]
The following error occurs when executing the "prisma generate" command.

```
yarn run v1.22.4
$ prisma generate
Environment variables loaded from ./prisma/.env
Error: spawn node --max-old-space-size=8096 C:\Users\emers\Documents\Projetos\1 - Work\2020\April - Juny\felinto-network-digital\graphql\node_modules\@prisma\client\generator-build\index.js ENOENT
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

NPM log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'generate:prisma'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'pregenerate:prisma', 'generate:prisma', 'postgenerate:prisma' ]
5 info lifecycle graphql-auth@~pregenerate:prisma: graphql-auth@
6 info lifecycle graphql-auth@~generate:prisma: graphql-auth@
7 verbose lifecycle graphql-auth@~generate:prisma: unsafe-perm in lifecycle true
8 verbose lifecycle graphql-auth@~generate:prisma: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\emers\Documents\Projetos\1 - Work\2020\April - Juny\felinto-network-digital\graphql\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\emers\AppData\Local\Microsoft\WindowsApps;;C:\Users\emers\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\emers\AppData\Roaming\npm;C:\Program Files\Oracle\VirtualBox;C:\Program Files\heroku\bin;C:\tools\Cmder
9 verbose lifecycle graphql-auth@~generate:prisma: CWD: C:\Users\emers\Documents\Projetos\1 - Work\2020\April - Juny\felinto-network-digital\graphql
10 silly lifecycle graphql-auth@~generate:prisma: Args: [ '/d /s /c', 'prisma generate' ]
11 silly lifecycle graphql-auth@~generate:prisma: Returned: code: 1  signal: null
12 info lifecycle graphql-auth@~generate:prisma: Failed to exec generate:prisma script
13 verbose stack Error: graphql-auth@ generate:prisma: `prisma generate`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid graphql-auth@
15 verbose cwd C:\Users\emers\Documents\Projetos\1 - Work\2020\April - Juny\felinto-network-digital\graphql
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "generate:prisma"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error graphql-auth@ generate:prisma: `prisma generate`
22 error Exit status 1
23 error Failed at the graphql-auth@ generate:prisma script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

This is my schema

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model Product {
  id              Int                @default(autoincrement()) @id
  name            String             @unique
  desc            String?
  developer       ProductDeveloper   @relation(fields: [developerId], references: [id])
  developerId     Int
  forum           Forum?             @relation(fields: [forumId], references: [id])
  forumId         Int?
  type            ProductType
  tags            ProductTag[]
  salesPages      ProductSalesPage[]
  productVersions ProductVersions[]
  productPictures ProductPictures[]
  Customer        Customer?          @relation(fields: [customerId], references: [id])
  customerId      Int?
  Invoice         Invoice?           @relation(fields: [invoiceId], references: [id])
  invoiceId       Int?
}

enum ProductType {
  Plugins_WordPress
  Temas_WordPress
}

model ProductDeveloper {
  id       Int       @default(autoincrement()) @id
  name     String    @unique
  products Product[]
}

model ProductTag {
  id          Int       @default(autoincrement()) @id
  name        String    @unique
  translation String
  products    Product[] @relation(references: [id])
}

model ProductSalesPage {
  id        Int     @default(autoincrement()) @id
  url       String  @unique
  productId Int
  product   Product @relation(fields: [productId], references: [id])
}

model ProductVersions {
  id                  Int          @default(autoincrement()) @id
  provider            Provider
  isCompacted         Boolean      @default(false)
  version             String
  lastUpdated         String?
  isUnlocked          Boolean      @default(false)
  warning             String?
  createdAt           DateTime     @default(now())
  downloadHost        downloadHost
  downloadHostAccount Int
  downloadPath        String
  productId           Int
  product             Product      @relation(fields: [productId], references: [id])
}

enum Provider {
  GPLZONE
  ULTRAPACKV2
}

enum downloadHost {
  DROPBOX
}

model ProductPictures {
  id         Int     @default(autoincrement()) @id
  pictureUrl String  @unique
  productId  Int
  product    Product @relation(fields: [productId], references: [id])
}

model Forum {
  id        Int      @default(autoincrement()) @id
  name      String
  permalink String   @unique
  parentId  Int?
  parent    Forum?   @relation(fields: [parentId], references: [id])
  Forum     Forum[]  @relation("ForumToForum")
  product   Product?
}

model Host {
  id        Int          @default(autoincrement()) @id
  host      downloadHost
  accountId String
}

model Customer {
  id          Int               @default(autoincrement()) @id
  name        String
  birthday    DateTime?
  cpf         String?           @unique
  gender      Gender?
  email       String            @unique
  loginName   String            @unique
  balance     Float             @default(0.00)
  isSuspended Boolean           @default(false)
  createdAt   DateTime          @default(now())
  tags        CustomerTag[]     @relation(references: [id])
  invoices    Invoice[]
  product     Product[]
  accounts    CustomerAccount[]
  // Criar um resolver na API GraphQL para pegar os produtos de acordo com as
  // invoices que estão pagas.
}

enum Gender {
  M
  F
}

model CustomerTag {
  id        Int        @default(autoincrement()) @id
  value     String     @unique
  customers Customer[] @relation(references: [id])
}

model CustomerAccount {
  id         Int                     @default(autoincrement()) @id
  nickname   String?
  platform   CustomerAccountPlatform
  details    Json
  customerId Int
  customer   Customer                @relation(fields: [customerId], references: [id])
}

enum CustomerAccountPlatform {
  FORUM
  MERCADOLIBRE
}

model Invoice {
  id                Int                  @default(autoincrement()) @id
  status            InvoiceStatus
  transactions      PaymentTransaction[]
  purchaseDate      DateTime
  details           Json
  products          Product[]
  supportExpiration DateTime
  customerId        Int
  customer          Customer             @relation(fields: [customerId], references: [id])
}

enum InvoiceStatus {
  PAID
  CANCELED
}

model PaymentTransaction {
  id            Int                        @default(autoincrement()) @id
  platform      PaymentTransactionPlatform
  date          DateTime
  transactionID Int                        @unique
  value         Float
  invoiceId     Int
  invoice       Invoice                    @relation(fields: [invoiceId], references: [id])
}

enum PaymentTransactionPlatform {
  MERCADOPAGO
}
```

## Environment & setup

- OS: Windows
- Database: MariaDB 10.4.12
- Prisma version: [Run `prisma -v` to see your Prisma version]
```
C:\Users\emers\Documents\Projetos\1 - Work\2020\April - Juny\felinto-network-digital\graphql>npx prisma -v
Environment variables loaded from ./prisma/.env
@prisma/cli          : 2.0.0-beta.7
Current platform     : windows
Query Engine         : query-engine 5d39801acf2e3475bd9dab029a63634358b07bf1 (at C:\Users\emers\Documents\Projetos\1 - Work\2020\April - Juny\felinto-network-digital\graphql\node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 5d39801acf2e3475bd9dab029a63634358b07bf1 (at C:\Users\emers\Documents\Projetos\1 - Work\2020\April - Juny\felinto-network-digital\graphql\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 5d39801acf2e3475bd9dab029a63634358b07bf1 (at C:\Users\emers\Documents\Projetos\1 - Work\2020\April - Juny\felinto-network-digital\graphql\node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 5d39801acf2e3475bd9dab029a63634358b07bf1 (at C:\Users\emers\Documents\Projetos\1 - Work\2020\April - Juny\felinto-network-digital\graphql\node_modules\@prisma\cli\prisma-fmt-windows.exe)
```
- Node.js version: 12.16.1

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by jarthursantos** [comment]
> s

This solution don't work from me.

**Comment by pantharshit00** [comment]
@jarthursantos Can you please open a new issue with a minimal reproduction? Thanks!

**Comment by davemccrea** [comment]
I can report the same error message.

```
./node_modules/.bin/prisma generate --schema "./src/lib/db/schema.prisma"
Error: Generator at node --max-old-space-size=8096 "/home/david/bin/javascript/edenflowers-server/node_modules/@prisma/client/generator-build/index.js" could not start:
```

Works fine on MacOS but problems arise on Linux (Elementary OS).

@prisma/cli v2.6.2
Node v12.18.4
NPM v6.14.6

**Comment by bastianhilton** [comment]
for anyone new to this issue, I got around this error by running npx prisma generate instead of just prisma generate on windows.
