### ISSUE TITLE
Internal server error caused by bad datamodel

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#2649]
User error causes internal server error:

```
❯ DEBUG=* prisma deploy
  config CWD /Users/jasonkuhrt/projects/personal/gql-experiments/prisma-stitch/prisma +0ms
  config HOME /Users/jasonkuhrt +1ms
  config definitionDir /Users/jasonkuhrt/projects/personal/gql-experiments/prisma-stitch/prisma +1ms
  config definitionPath /Users/jasonkuhrt/projects/personal/gql-experiments/prisma-stitch/prisma/prisma.yml +0ms
  cli { isGlobal: true } +0ms
  StatusChecker setting status checker +0ms
  cli command id deploy +5ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/jasonkuhrt/Library/Caches/prisma/plugins.json +1ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/jasonkuhrt/Library/Caches/prisma/plugins.json +0ms
  plugins findCommand prisma-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /Users/jasonkuhrt/.config/yarn/global/node_modules/prisma-cli-core +0ms
  portfinder:defaultHosts exports._defaultHosts is: [ '0.0.0.0', '127.0.0.1', '::1', 'fe80::1', 'fe80::1471:9054:af6:6cc8', '10.0.1.3', 'fe80::90d0:3fff:fe4b:6181', 'fe80::4e2f:549:9ad3:d620', 'fe80::2e80:9d30:d1a:5038', 'fe80::aede:48ff:fe00:1122' ] +0ms
  cli-engine:plugins:manager required +881ms
  plugin required command +884ms
  Environment saving global rc +0ms
  StatusChecker setting status checker +1s
  prisma definition making cluster here +0ms
  client Initializing cluster client +0ms
  deploy checking verions +0ms
  deploy checking if project exists +34ms
  client Sending query to cluster local +37ms
  client http://localhost:4466/management +0ms
  client
  client       query($name: String! $stage: String!) {
  client         project(name: $name stage: $stage) {
  client           name
  client           stage
  client         }
  client       }
  client      +0ms
  client { name: 'core', stage: 'dev' } +0ms
  client { project: { name: 'core', stage: 'dev' } } +57ms

Deploying service `core` to stage `dev` to server `local`...  client Sending query to cluster local +3ms
  client http://localhost:4466/management +0ms
  client       mutation($name: String!, $stage: String! $types: String! $dryRun: Boolean $secrets: [String!], $subscriptions: [FunctionInput!], $force: Boolean) {
  client         deploy(input: {
  client           name: $name
  client           stage: $stage
  client           types: $types
  client           dryRun: $dryRun
  client           secrets: $secrets
  client           subscriptions: $subscriptions
  client           force: $force
  client         }) {
  client           errors {
  client             type
  client             field
  client             description
  client           }
  client           warnings {
  client             type
  client             field
  client             description
  client           }
  client           migration {
  client             ...MigrationFragment
  client           }
  client         }
  client       }
  client
  client fragment MigrationFragment on Migration {
  client   revision
  client   steps {
  client     type
  client     __typename
  client     ... on CreateEnum {
  client       name
  client       ce_values: values
  client     }
  client     ... on CreateField {
  client       model
  client       name
  client       cf_typeName: typeName
  client       cf_isRequired: isRequired
  client       cf_isList: isList
  client       cf_isUnique: unique
  client       cf_relation: relation
  client       cf_defaultValue: default
  client       cf_enum: enum
  client     }
  client     ... on CreateModel {
  client       name
  client     }
  client     ... on CreateRelation {
  client       name
  client       leftModel
  client       rightModel
  client     }
  client     ... on DeleteEnum {
  client       name
  client     }
  client     ... on DeleteField {
  client       model
  client       name
  client     }
  client     ... on DeleteModel {
  client       name
  client     }
  client     ... on DeleteRelation {
  client       name
  client     }
  client     ... on UpdateEnum {
  client       name
  client       newName
  client       values
  client     }
  client     ... on UpdateField {
  client       model
  client       name
  client       newName
  client       typeName
  client       isRequired
  client       isList
  client       isUnique: unique
  client       relation
  client       default
  client       enum
  client     }
  client     ... on UpdateModel {
  client       name
  client       um_newName: newName
  client     }
  client   }
  client }
  client
  client      +0ms
  client { name: 'core',
  client   stage: 'dev',
  client   types: 'type User {\n  id: ID! @unique\n  email: String! @unique\n  channels: [MedicalEpisode!]! @relation(name: "MedicalEpisodes")\n  messages: [ChatMessage!]!\n}\n\ntype Channel {\n  id: ID! @unique\n  created_at: DateTime!\n  users: [User!]!\n  messages: [Message!]!\n}\n\ntype Message {\n  id: ID! @unique\n  sent_at: DateTime!\n  channel: Channel!\n  content: String!\n  author: User!\n}\n\n',
  client   dryRun: undefined,
  client   secrets: null,
  client   subscriptions: [],
  client   force: undefined } +7ms
 !
Error: Whoops. Looks like an internal server error. Search your server logs for request ID: local:management:cjil3v0e200080788wsdy1ot4: {"response":{"data":{"deploy":null},"errors":[{"message":"Whoops. Looks like an internal server error. Search your server logs for request ID: local:management:cjil3v0e200080788wsdy1ot4","path":["deploy"],"locations":[{"line":2,"column":9}],"requestId":"local:management:cjil3v0e200080788wsdy1ot4"}],"status":200},"request":{"query":"      mutation($name: String!, $stage: String! $types: String! $dryRun: Boolean $secrets: [String!], $subscriptions: [FunctionInput!], $force: Boolean) {\n        deploy(input: {\n          name: $name\n          stage: $stage\n          types: $types\n          dryRun: $dryRun\n          secrets: $secrets\n          subscriptions: $subscriptions\n          force: $force\n        }) {\n          errors {\n            type\n            field\n            description\n          }\n          warnings {\n            type\n            field\n            description\n          }\n          migration {\n            ...MigrationFragment\n          }\n        }\n      }\n      \nfragment MigrationFragment on Migration {\n  revision\n  steps {\n    type\n    __typename\n    ... on CreateEnum {\n      name\n      ce_values: values\n    }\n    ... on CreateField {\n      model\n      name\n      cf_typeName: typeName\n      cf_isRequired: isRequired\n      cf_isList: isList\n      cf_isUnique: unique\n      cf_relation: relation\n      cf_defaultValue: default\n      cf_enum: enum\n    }\n    ... on CreateModel {\n      name\n    }\n    ... on CreateRelation {\n      name\n      leftModel\n      rightModel\n    }\n    ... on DeleteEnum {\n      name\n    }\n    ... on DeleteField {\n      model\n      name\n    }\n    ... on DeleteModel {\n      name\n    }\n    ... on DeleteRelation {\n      name\n    }\n    ... on UpdateEnum {\n      name\n      newName\n      values\n    }\n    ... on UpdateField {\n      model\n      name\n      newName\n      typeName\n      isRequired\n      isList\n      isUnique: unique\n      relation\n      default\n      enum\n    }\n    ... on UpdateModel {\n      name\n      um_newName: newName\n    }\n  }\n}\n\n    ","variables":{"name":"core","stage":"dev","types":"type User {\n  id: ID! @unique\n  email: String! @unique\n  channels: [MedicalEpisode!]! @relation(name: \"MedicalEpisodes\")\n  messages: [ChatMessage!]!\n}\n\ntype Channel {\n  id: ID! @unique\n  created_at: DateTime!\n  users: [User!]!\n  messages: [Message!]!\n}\n\ntype Message {\n  id: ID! @unique\n  sent_at: DateTime!\n  channel: Channel!\n  content: String!\n  author: User!\n}\n\n","secrets":null,"subscriptions":[]}}}
    at GraphQLClient.<anonymous> (/Users/jasonkuhrt/.config/yarn/global/node_modules/graphql-request/src/index.ts:72:13)
    at step (/Users/jasonkuhrt/.config/yarn/global/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/Users/jasonkuhrt/.config/yarn/global/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/Users/jasonkuhrt/.config/yarn/global/node_modules/graphql-request/dist/src/index.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Exiting with code: 1
```

Not that the `@relation(name: \"MedicalEpisodes\")` is the offending issue. Removing it leads to a proper error message:

```
❯ DEBUG=* prisma deploy
  config CWD /Users/jasonkuhrt/projects/personal/gql-experiments/prisma-stitch/prisma +0ms
  config HOME /Users/jasonkuhrt +2ms
  config definitionDir /Users/jasonkuhrt/projects/personal/gql-experiments/prisma-stitch/prisma +0ms
  config definitionPath /Users/jasonkuhrt/projects/personal/gql-experiments/prisma-stitch/prisma/prisma.yml +0ms
  cli { isGlobal: true } +0ms
  StatusChecker setting status checker +0ms
  cli command id deploy +5ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/jasonkuhrt/Library/Caches/prisma/plugins.json +0ms
  cli:plugincache Got plugin from cache +1ms
  cli:plugincache /Users/jasonkuhrt/Library/Caches/prisma/plugins.json +0ms
  plugins findCommand prisma-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /Users/jasonkuhrt/.config/yarn/global/node_modules/prisma-cli-core +0ms
  portfinder:defaultHosts exports._defaultHosts is: [ '0.0.0.0', '127.0.0.1', '::1', 'fe80::1', 'fe80::1471:9054:af6:6cc8', '10.0.1.3', 'fe80::90d0:3fff:fe4b:6181', 'fe80::4e2f:549:9ad3:d620', 'fe80::2e80:9d30:d1a:5038', 'fe80::aede:48ff:fe00:1122' ] +0ms
  cli-engine:plugins:manager required +474ms
  plugin required command +477ms
  Environment saving global rc +0ms
  StatusChecker setting status checker +863ms
  prisma definition making cluster here +0ms
  client Initializing cluster client +0ms
  deploy checking verions +0ms
  deploy checking if project exists +38ms
  client Sending query to cluster local +41ms
  client http://localhost:4466/management +0ms
  client
  client       query($name: String! $stage: String!) {
  client         project(name: $name stage: $stage) {
  client           name
  client           stage
  client         }
  client       }
  client      +0ms
  client { name: 'core', stage: 'dev' } +0ms
  client { project: { name: 'core', stage: 'dev' } } +62ms

Deploying service `core` to stage `dev` to server `local`...  client Sending query to cluster local +2ms
  client http://localhost:4466/management +0ms
  client       mutation($name: String!, $stage: String! $types: String! $dryRun: Boolean $secrets: [String!], $subscriptions: [FunctionInput!], $force: Boolean) {
  client         deploy(input: {
  client           name: $name
  client           stage: $stage
  client           types: $types
  client           dryRun: $dryRun
  client           secrets: $secrets
  client           subscriptions: $subscriptions
  client           force: $force
  client         }) {
  client           errors {
  client             type
  client             field
  client             description
  client           }
  client           warnings {
  client             type
  client             field
  client             description
  client           }
  client           migration {
  client             ...MigrationFragment
  client           }
  client         }
  client       }
  client
  client fragment MigrationFragment on Migration {
  client   revision
  client   steps {
  client     type
  client     __typename
  client     ... on CreateEnum {
  client       name
  client       ce_values: values
  client     }
  client     ... on CreateField {
  client       model
  client       name
  client       cf_typeName: typeName
  client       cf_isRequired: isRequired
  client       cf_isList: isList
  client       cf_isUnique: unique
  client       cf_relation: relation
  client       cf_defaultValue: default
  client       cf_enum: enum
  client     }
  client     ... on CreateModel {
  client       name
  client     }
  client     ... on CreateRelation {
  client       name
  client       leftModel
  client       rightModel
  client     }
  client     ... on DeleteEnum {
  client       name
  client     }
  client     ... on DeleteField {
  client       model
  client       name
  client     }
  client     ... on DeleteModel {
  client       name
  client     }
  client     ... on DeleteRelation {
  client       name
  client     }
  client     ... on UpdateEnum {
  client       name
  client       newName
  client       values
  client     }
  client     ... on UpdateField {
  client       model
  client       name
  client       newName
  client       typeName
  client       isRequired
  client       isList
  client       isUnique: unique
  client       relation
  client       default
  client       enum
  client     }
  client     ... on UpdateModel {
  client       name
  client       um_newName: newName
  client     }
  client   }
  client }
  client
  client      +0ms
  client { name: 'core',
  client   stage: 'dev',
  client   types: 'type User {\n  id: ID! @unique\n  email: String! @unique\n  channels: [MedicalEpisode!]!\n  messages: [ChatMessage!]!\n}\n\ntype Channel {\n  id: ID! @unique\n  created_at: DateTime!\n  users: [User!]!\n  messages: [Message!]!\n}\n\ntype Message {\n  id: ID! @unique\n  sent_at: DateTime!\n  channel: Channel!\n  content: String!\n  author: User!\n}\n\n',
  client   dryRun: undefined,
  client   secrets: null,
  client   subscriptions: [],
  client   force: undefined } +15ms
  client { deploy: { errors: [ [Object], [Object] ], warnings: [], migration: null } } +102ms
 118ms

Errors:

  User
    ✖ The field `channels` has the type `[MedicalEpisode!]!` but there's no type or enum declaration with that name.
    ✖ The field `messages` has the type `[ChatMessage!]!` but there's no type or enum declaration with that name.

Deployment canceled. Please fix the above errors to continue deploying.
Read more about deployment errors here: https://bit.ly/prisma-force-flag
Exiting with code: 1
```

**Comment by marktani** [comment]
Thanks for the report. Can you share the exact datamodel you're setting up in your file system? You mention `@relation(name: \"MedicalEpisodes\")` but I can only see `@relation(name: "MedicalEpisodes")` in the deploy mutation.

Also, can you share the internal server error logs for id `local:management:cjil3v0e200080788wsdy1ot4`? 🙂

**Comment by jasonkuhrt** [comment]
@marktani Sorry somehow missed your reply. Will follow up next time I get back into this.
