### ISSUE TITLE
@prisma/sdk cannot find module `p-queue`

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma#2692]
When trying to installed `@prisma/sdk` beta 9 an erorr occurs:

```
❯ yarn add @prisma/sdk                
yarn add v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "nexus > @zeit/node-file-trace > acorn-export-ns-from@0.1.0" has incorrect peer dependency "acorn@^6.0.1".
warning " > ts-jest@26.0.0" has unmet peer dependency "typescript@>=3.8 <4.0".
[4/4] 🔨  Building fresh packages...
[1/2] ⠐ nexus
error /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/@prisma/sdk: Command failed.
Exit code: 1
Command: node scripts/download.js
Arguments: 
Directory: /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/@prisma/sdk
Output:
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'p-queue'
Require stack:
- /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/@prisma/fetch-engine/dist/getLatestAlphaTag.js
- /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/@prisma/fetch-engine/dist/download.js
- /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/@prisma/fetch-engine/dist/index.js
- /Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/@prisma/sdk/scripts/download.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/@prisma/fetch-engine/dist/getLatestAlphaTag.js:11:35)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/@prisma/fetch-engine/dist/getLatestAlphaTag.js',
    '/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/@prisma/fetch-engine/dist/download.js',
    '/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/@prisma/fetch-engine/dist/index.js',
    '/Users/jasonkuhrt/projects/graphql-nexus/examples/hello-world/node_modules/@prisma/sdk/scripts/download.js'
  ]
}
```

**Comment by Jolg42** [comment]
Fixed in latest alpha! Thanks :)
