### ISSUE TITLE
@id on all fileds

### ISSUE THREAD

**Issue by TomasMoskala** [prisma/prisma#2705]
## Bug description

Table that has 2 fields and both in primary key throws an error on schema generation. Adding some other field fixes that.

## How to reproduce
```
CREATE TABLE `test` ( `id_1` INT NOT NULL, `id_2` INT NOT NULL, PRIMARY KEY (`id_1`, `id_2`)) ENGINE = InnoDB 
```

`npx prisma introspect` produces

```
model test {
  id_1 Int
  id_2 Int

  @@id([id_1, id_2])
}
```

`npm run generate`

````
> typescript-graphql@ generate C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server
> npm -s run generate:prisma && npm -s run generate:nexus

Environment variables loaded from ./prisma/.env
✔ Generated Prisma Client to .\node_modules\@prisma\client in 148ms

You can now start using Prisma Client in your code:

```
import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
```

Explore the full API: http://pris.ly/d/client


C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus-prisma\src\builder.ts:465
          throw new Error(
                ^
Error: Your Prisma Model activity_type_group does not have an @id field. It's required for nexus-prisma to work.
    at Proxy.fieldPublisher (C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\nexus-prisma\src\builder.ts:465:17)
    at Object.definition (C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\src\defs.ts:38:17)
    at SchemaBuilder.walkOutputType (C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\@nexus\schema\src\builder.ts:1461:9)
    at SchemaBuilder.walkTypes (C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\@nexus\schema\src\builder.ts:688:16)
    at SchemaBuilder.getFinalTypeMap (C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\@nexus\schema\src\builder.ts:787:10)
    at makeSchemaInternal (C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\@nexus\schema\src\builder.ts:1585:15)
    at Object.makeSchema (C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\@nexus\schema\src\builder.ts:1630:49)
    at Object.<anonymous> (C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\src\schema.ts:145:27)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module.m._compile (C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\ts-node\src\index.ts:858:23)   
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-graphql@ generate: `npm -s run generate:prisma && npm -s run generate:nexus`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typescript-graphql@ generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\aa\npm-cache\_logs\2020-06-09T16_25_10_321Z-debug.log
````

## Expected behavior

generate schema
If you add a field
```
ALTER TABLE `test` ADD `save_the_schema` INT NOT NULL AFTER `id_2`; 
```
```
model test {
  id_1            Int
  id_2            Int
  save_the_schema Int

  @@id([id_1, id_2])
}
```
Now it works and this helps as well
```
model test {
  id_1 Int @default(1)
  id_2 Int

  @@id([id_1, id_2])
}
```
but then it fails anyway at definitions, at least I don't know how to write one. 
After adding
```
export const Test = objectType({
  name: 'test',
  definition(t) {
    t.model.id_1()
    t.model.id_2()
    t.model.save_the_schema()
}})
```
and 
```
makeSchema({types: [Query, Mutation, Test], ..........
```
I get the same error and cannot generate schema.graphql

## Prisma information

Environment variables loaded from ./prisma/.env
@prisma/cli          : 2.0.0-beta.8
Current platform     : windows
Query Engine         : query-engine 12105ee25e61860c17a381ffdfcf2b2513b0ba92 (at C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 12105ee25e61860c17a381ffdfcf2b2513b0ba92 (at C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 12105ee25e61860c17a381ffdfcf2b2513b0ba92 (at C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 12105ee25e61860c17a381ffdfcf2b2513b0ba92 (at C:\aa\TESTS\prisma-examples\typescript\graphql-apollo-server\node_modules\@prisma\cli\prisma-fmt-windows.exe)

## Environment & setup

Win10
MySQL
node v12.16.2

**Comment by pantharshit00** [comment]
Moved to https://github.com/graphql-nexus/nexus-schema-plugin-prisma/issues/724
