### ISSUE TITLE
Cannot return null for non-nullable field

### ISSUE THREAD

**Issue by jechazelle** [prisma/prisma#2752]
Hello, I tried to use the Prisma 2, but I have an error when I execute this request :

```
query {
  post(id:"1"){
    id
    title
        author {
        id
        }
    }
}
```

In my mutation, I have this : 

```
post(parent, args, { prisma }, info) {
    const post = prisma.post.findOne({
        where: {
            id: parseInt(args.id)
        }
    }, info)

    if(!post) {
        throw new Error('Post not found.')
    }

    return post
}
```

In my schema.graphql : 

```
type User {
    id: ID!
    name: String!
    email: String
    password: String!
}

type Post {
    id: ID!
    title: String!
    content: String!
    published: Boolean!
    author: User!
}

type Query {
    post(id: ID!): Post!
}
```

## Bug description

When I execute my request, I have this error : 

```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Post.author.",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "post",
        "author"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Post.author.",
            "    at completeValue (/Users/user/Sites/prisma2/node_modules/graphql/execution/execute.js:578:13)",
            "    at completeValueCatchingError (/Users/user/Sites/prisma2/node_modules/graphql/execution/execute.js:513:19)",
            "    at resolveField (/Users/user/Sites/prisma2/node_modules/graphql/execution/execute.js:444:10)",
            "    at executeFields (/Users/user/Sites/prisma2/node_modules/graphql/execution/execute.js:280:18)",
            "    at collectAndExecuteSubfields (/Users/user/Sites/prisma2/node_modules/graphql/execution/execute.js:731:10)",
            "    at completeObjectValue (/Users/user/Sites/prisma2/node_modules/graphql/execution/execute.js:721:10)",
            "    at completeValue (/Users/user/Sites/prisma2/node_modules/graphql/execution/execute.js:609:12)",
            "    at completeValue (/Users/user/Sites/prisma2/node_modules/graphql/execution/execute.js:575:21)",
            "    at /Users/user/Sites/prisma2/node_modules/graphql/execution/execute.js:510:16",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

But If I execute only : 

```
query {
  post(id:"1"){
    id
    title
    }
}
```

without author, I have no error (but I have no author)...

## Environment & setup

- OS: Mac OS
- Database: MariaDB
- Prisma version: 2.0.0
- Node.js version: 13.10.1
- apollo-server: 2.14.4
- SQL: 
```
CREATE TABLE User (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE TABLE Post (
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT now(),
  content TEXT,
  published BOOLEAN NOT NULL DEFAULT false,
  fk_user_id INTEGER NOT NULL,
  FOREIGN KEY (fk_user_id) REFERENCES User(id)
);
```
- schema.prisma: 
```
model Post {
  content    String?
  createdAt  DateTime @default(now())
  fk_user_id Int
  id         Int      @default(autoincrement()) @id
  published  Boolean  @default(false)
  title      String
  author     User     @relation(fields: [fk_user_id], references: [id])

  @@index([fk_user_id], name: "fk_user_id")
}

model User {
  email    String   @unique
  id       Int      @default(autoincrement()) @id
  name     String?
  password String   @default("")
  Post     Post[]
  Profile  Profile?
}
```

Do you have an idea how can I have the author ?

**Comment by dodas** [comment]
You need to add resolver for `Post.author` to your graphql server.
Check out [Write your GraphQL type resolvers](https://www.prisma.io/docs/guides/upgrade-from-prisma-1/upgrading-prisma-binding-to-sdl-first#2-write-your-graphql-type-resolvers) in prisma docs.

**Comment by jechazelle** [comment]
I added include: {author: true} to bind :

post(parent, args, { prisma }) {
    const post = prisma.post.findOne({
        where: {
            id: parseInt(args.id, 10),
        },
        include: {
            author: true,
        },
    })

    if (!post) {
        throw new Error("Post not found.")
    }

    return post
}

**Comment by dodas** [comment]
That is actually not correct solution. You will run into problems and you will need more and more code to fix it.
Please read something about graphql resolvers, for example [here](https://khalilstemmler.com/blogs/graphql/nested-graphql-resolvers/).

**Comment by jechazelle** [comment]
Hi @dodas it's better to have a specific resolver ?

```
const Post = {
    author(parent, args, { prisma }, info) {
        return prisma.user.findOne({
            where: {
                id: parseInt(parent.fk_user_id)
            }
        }, info)
    },
}

export { Post as default }
```

and import it :

```
import Query from "./Query"
import Mutation from "./Mutation"
import Post from "./Post"

const resolvers = {
    Query,
    Mutation,
    Post,
}

export { resolvers as default }
```

**Comment by dodas** [comment]
Yes, I think you would need exactly this:
```ts
Query: {
  Post: {
    author:(parent, args, { prisma }) {
      return prisma.post.findOne({
        where: { id: parent.id }
      }).author()
    }
  }
}
```

**Comment by codal-umistri** [comment]
facing same problem @dodas  can you help me ?
