### ISSUE TITLE
"Error occurred during query validation & transformation"

### ISSUE THREAD

**Issue by Rechdan** [prisma/prisma#2799]
The exception:
```
prisma:info  Starting a mysql pool with up to 17 connections.
prisma:info  Started http server on 127.0.0.1:60050
ex PrismaClientKnownRequestError:
Invalid `db.user.findOne()` invocation in
D:\....\src\admin\login.ts:12:30

   8 export const login = Router().post('/', async (req,[object Object], res) => {
   9    try {
  10            const { username, password } = req.body;
  11
→ 12            const user = await db.user.findOne(
  Failed to validate the query `Error occurred during query validation & transformation:
Assertion error: Expected object to have exactly 1 key-value pairs, got: 2 (category, email).` at ``
    at PrismaClientFetcher.request (D:\....\node_modules\@prisma\client\src\runtime\getPrismaClient.ts:762:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2009',
  meta: {
    query_validation_error: 'Error occurred during query validation & transformation:\n' +
      'Assertion error: Expected object to have exactly 1 key-value pairs, got: 2 (category, email).',
    query_position: ''
  }
}
```

The schema:
```prisma
model user {
   id       Int          @id @default(autoincrement())
   category UserCategory @default(NORMAL)
   email    String
   created  DateTime     @default(now())
}
```

The query that errors:
```ts
const user = await db.user.findOne({ where: { category: 'ADMIN', email: username } });
```

The query works when:
```ts
const user = await db.user.findOne({ where: { category: 'ADMIN' } });
```
or when:
```ts
const user = await db.user.findOne({ where: { email: username } });
```

Am I doing something wrong here? 😥

**Comment by pantharshit00** [comment]
`category` is not unique so it is not avaiable in `findOne`. You will need to either make it unique or use `findMany` here. 

Actually none of the queries that you have posted will work as `id` is the only unique field in that model.

Your editor will show you an error like so in addition to the runtime error:
![image](https://user-images.githubusercontent.com/22195362/85192090-e56f9380-b2de-11ea-8b83-ac9a2419d04d.png)


Also `findOne` only need one unique key as that is sufficient to guarantee that only one record will be retrieved. If you want to have combination of two fields unique, you should use an composite unique index. Find docs about that here: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/data-model#multi-field-unique-attributes
