### ISSUE TITLE
Prisma VSCode extension not starting

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/prisma#2845]
After installing 2.1.1 Prisma Language Server fails to start. I am getting the following error: 

```
Error: Cannot find module '/Users/macbookpro/.vscode/packages/language-server/bin/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by valentinpalkovic** [comment]
Wrong project :) https://github.com/prisma/vscode/issues/279

**Comment by malekjaroslav** [comment]
Closing in favor of #279
