### ISSUE TITLE
executeRaw could support multiple queries from a single string

### ISSUE THREAD

**Issue by AssisrMatheus** [prisma/prisma#2868]
## Problem
Since `prisma migrate` is experimental and our team is waiting for #446, I was trying to create a simple migration tool. Our needs aren't big for now so a simple script would help.

I made a node script that would read `.sql` files from a `scripts` folder and run them sequentially:
```typescript
import { PrismaClient } from '@prisma/client';
import path from 'path';
import fs from 'fs';

const main = async () => {
  const db = new PrismaClient();
  try {
    // Create the migrations table
    await db.executeRaw(
      'CREATE TABLE IF NOT EXISTS `Migrations` (`id` int NOT NULL AUTO_INCREMENT, `executedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `migrationName` varchar(255) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `Migrations.migrationName` (`migrationName`));'
    );

    // Read all the sql scrips
    const basePath = path.join(__dirname, './scripts');
    const scripts = fs.readdirSync(basePath, { encoding: 'utf8' });
    // For each file
    for (const fileName of scripts) {
      // We have to wrap empty results with try catch. Waiting for https://github.com/prisma/prisma/issues/2867
      try {
        // Check if the migration ran already
        await db.queryRaw`SELECT 1 FROM Migrations WHERE migrationName = '${fileName}' LIMIT 1`;
      } catch {
        // If didn't

        // Get the sql content
        const sql = fs.readFileSync(path.join(basePath, fileName), {
          encoding: 'utf8'
        });

        // Run the sql
        await db.executeRaw(sql);

        // Update the migration table
        await db.executeRaw`INSERT INTO Migrations(migrationName) VALUES ('${fileName}')`;
      }
    }
  } catch (error) {
    console.error(error);
  } finally {
    await db.disconnect();
  }
};

main().catch((e) => console.error(e));
```

But every time when executing the script, which has multiple queries like `CREATE TABLE` or `ALTER TABLE`, `executeRaw` throws an error:
```
PrismaClientKnownRequestError: Raw query failed. Code: `1064`. Message: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS `MyTable` (
  `id` int NOT NULL AUTO_INCREMEN' at line 31`
    at PrismaClientFetcher.request (D:\dev\perimetre\export-connect-backend\node_modules\@prisma\client\src\runtime\getPrismaClient.ts:902:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2010',
  meta: {
    code: '1064',
    message: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS `IndustrySector` (\r\n" +
      "  `id` int NOT NULL AUTO_INCREMEN' at line 31"
  }
}
```

The script is not incorrect as it runs fine with Mysql Workbench. And if I take only one query from the script and make a file with only that. It also runs fine.

## Suggested solution
`db.executeRaw` could support running multiple queries instead of only one

**Comment by BjoernRave** [comment]
@AssisrMatheus in the meantime you can maybe try my script I use to reset my db with data from an `.sql` file
```
  const sqls = fs
    .readFileSync(__dirname + '/test.sql')
    .toString()
    .split('\n')
    .filter((line) => line.indexOf('--') !== 0)
    .join('\n')
    .replace(/(\r\n|\n|\r)/gm, ' ') // remove newlines
    .replace(/\s+/g, ' ') // excess white space
    .split(';')

  for (const sql of sqls) {
    await prisma.executeRaw(sql)
  }

  await prisma.disconnect()
```

**Comment by AssisrMatheus** [comment]
> @AssisrMatheus in the meantime you can maybe try my script I use to reset my db with data from an `.sql` file
> 
> ```
>   const sqls = fs
>     .readFileSync(__dirname + '/test.sql')
>     .toString()
>     .split('\n')
>     .filter((line) => line.indexOf('--') !== 0)
>     .join('\n')
>     .replace(/(\r\n|\n|\r)/gm, ' ') // remove newlines
>     .replace(/\s+/g, ' ') // excess white space
>     .split(';')
> 
>   for (const sql of sqls) {
>     await prisma.executeRaw(sql)
>   }
> 
>   await prisma.disconnect()
> ```

Thanks @BjoernRave. It really worked. But I don't know/feel if that is reliable enough for us, but maybe it might be enough.

**Comment by BjoernRave** [comment]
glad I could help :)

**Comment by pantharshit00** [comment]
I can confirm this bug. Here is a simpler reproduction which uses MySQL:

```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const client = new PrismaClient({
    log: ["query"],
  });

  const data = await client.executeRaw(
    "CREATE TABLE IF NOT EXISTS `MyTable` ( `id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,PRIMARY KEY (`id`), UNIQUE KEY `MyTable.slug` (`slug`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; CREATE TABLE IF NOT EXISTS `MyOtherTable` ( `id` int NOT NULL AUTO_INCREMENT, `test` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `something` int NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `MyTable.something` (`something`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;"
  );

  console.log(data);
  client.disconnect();
}

main();
```

**Comment by janpio** [comment]
After an [internal discussion](https://prisma-company.slack.com/archives/C4GCG53BP/p1593513246334300) I can say that the current behaviour of `executeRaw` only being able to execute 1 query instead of a list of queries is actually expected. Using @BjoernRave 's script is a nice way around that limitation: https://github.com/prisma/prisma/issues/2868#issuecomment-650283841

We will add a more explicit callout to that behavior in our documentation so it is discoverable.

I will turn this issue into a `kind/improvement` and we might pick this up in the future - currently it is not a priority.

**Comment by ipy** [comment]
Transaction is not well supported for our cases. Hope full transaction will be supported with arbitrary multiline statements.

**Comment by internalfx** [comment]
This means I need a second connection to my database from a different library in order to run more complicated queries.

As prisma is still under heavy development, I think a built-in escape hatch is very important.

**Comment by matthewmueller** [comment]
Hi @ipy 

Do you mind describing your transaction use case a bit better?

**Comment by nerkn** [comment]
I tried transaction,
```

  prisma.$transaction(
      photos.map((p,i)=>
        prisma.$queryRawUnsafe(`update Photos set orderby=${i} 
            where id=${p} and projectId=${project}`) ))
    .then(res.json({msg:'Updated :'+ photos.length + ' photos'}))
```


It seems it dont send data as a batch instead sends one by one then ends batch
```
prisma:query BEGIN
prisma:query update Photos set orderby=0 
            where id=139 and projectId=1
prisma:query update Photos set orderby=1 
            where id=141 and projectId=1
prisma:query update Photos set orderby=2 
            where id=136 and projectId=1
prisma:query update Photos set orderby=3 
            where id=140 and projectId=1
prisma:query update Photos set orderby=4 
            where id=137 and projectId=1
prisma:query update Photos set orderby=5 
            where id=135 and projectId=1
prisma:query update Photos set orderby=6 
            where id=13 and projectId=1
prisma:query update Photos set orderby=7 
            where id=14 and projectId=1
prisma:query update Photos set orderby=8 
            where id=16 and projectId=1
prisma:query update Photos set orderby=9 
            where id=134 and projectId=1
prisma:query update Photos set orderby=10 
            where id=138 and projectId=1
prisma:query update Photos set orderby=11 
            where id=142 and projectId=1
prisma:query update Photos set orderby=12 
            where id=143 and projectId=1
prisma:query update Photos set orderby=13 
            where id=144 and projectId=1
prisma:query update Photos set orderby=14 
            where id=145 and projectId=1
prisma:query update Photos set orderby=15 
            where id=146 and projectId=1
prisma:query update Photos set orderby=16 
            where id=147 and projectId=1
prisma:query update Photos set orderby=17 
            where id=148 and projectId=1
prisma:query update Photos set orderby=18 
            where id=149 and projectId=1
prisma:query update Photos set orderby=19 
            where id=150 and projectId=1
prisma:query update Photos set orderby=20 
            where id=151 and projectId=1
prisma:query update Photos set orderby=21 
            where id=152 and projectId=1
prisma:query update Photos set orderby=22 
            where id=154 and projectId=1
prisma:query update Photos set orderby=23 
            where id=155 and projectId=1
prisma:query update Photos set orderby=24 
            where id=156 and projectId=1
prisma:query update Photos set orderby=25 
            where id=157 and projectId=1
prisma:query update Photos set orderby=26 
            where id=158 and projectId=1
prisma:query update Photos set orderby=27 
            where id=160 and projectId=1
prisma:query update Photos set orderby=28 
            where id=161 and projectId=1
prisma:query update Photos set orderby=29 
            where id=162 and projectId=1
prisma:query update Photos set orderby=30 
            where id=163 and projectId=1
prisma:query update Photos set orderby=31 
            where id=164 and projectId=1
prisma:query update Photos set orderby=32 
            where id=165 and projectId=1
prisma:query update Photos set orderby=33 
            where id=166 and projectId=1
prisma:query update Photos set orderby=34 
            where id=167 and projectId=1
prisma:query update Photos set orderby=35 
            where id=168 and projectId=1
prisma:query update Photos set orderby=36 
            where id=169 and projectId=1
prisma:query update Photos set orderby=37 
            where id=170 and projectId=1
prisma:query update Photos set orderby=38 
            where id=171 and projectId=1
prisma:query update Photos set orderby=39 
            where id=172 and projectId=1
prisma:query update Photos set orderby=40 
            where id=173 and projectId=1
prisma:query update Photos set orderby=41 
            where id=174 and projectId=1
prisma:query update Photos set orderby=42 
            where id=175 and projectId=1
prisma:query update Photos set orderby=43 
            where id=176 and projectId=1
prisma:query update Photos set orderby=44 
            where id=177 and projectId=1
prisma:query update Photos set orderby=45 
            where id=178 and projectId=1
prisma:query update Photos set orderby=46 
            where id=179 and projectId=1
prisma:query update Photos set orderby=47 
            where id=180 and projectId=1
prisma:query update Photos set orderby=48 
            where id=181 and projectId=1
prisma:query update Photos set orderby=49 
            where id=182 and projectId=1
prisma:query COMMIT
```
and unfortunately transaction returns immediately while those updates flowing on the console.

**Comment by b05902062** [comment]
> Two years later and no progress on something so rudimentary?
> 
> In my case the need arises due to another missing API. updateMany doesn't support multiple updates with different where cases. An example would be:
> 
> ```
> UPDATE categories SET products = 10 WHERE id = 1;
> UPDATE categories SET products = 20 WHERE id = 2;
> UPDATE categories SET products = 30 WHERE id = 3;
> ```
> 
> I cannot do:
> 
> ```
> db.$queryRawUnsafe(`
>   UPDATE categories SET products = 10 WHERE id = 1;
>   UPDATE categories SET products = 20 WHERE id = 2;
>   UPDATE categories SET products = 30 WHERE id = 3;
> `);
> ```
> 
> neither can I do:
> 
> ```
> updateMany([
>   {data: {products: 10}, where: {id: 1}},
>   {data: {products: 20}, where: {id: 2}},
>   {data: {products: 30}, where: {id: 3}},  
> ]);
> ```
> 
> The working alternative with Promise.all and single update exhausts the connection pool, while sequential run is extremely slow for large number of rows.

Another alternative to acheive that would be to define a database stored procedure that would maybe take a JSON array of arguments. Loop through the array in the procedure and issue an update query in each iteration. While on the client side,  you can use a raw query to call the procedure like ```prisma.executeRaw`call procedure(${<you_object_string>})` ```. Since there is only one statement, prisma would accept it and we can save all the round trips for multiple seperate update queries.

You may have to watch out for sql injection attack depending on how you will write your queries in the procedure.

**Comment by jeevanpillay** [comment]
Really liked @jeffrafter's solution. 

Here's a little more dynamic version

```
const updateManyByField = async <T>(
  prisma: PrismaClient<Prisma.PrismaClientOptions, never, Prisma.RejectOnNotFound | Prisma.RejectPerOperation | undefined>,
  model: string,
  field: string,
  array: T[],
  predicate: (value: T, index: number, array: T[]) => [string, any]
) => {
  for (const chunk of Array.from({ length: Math.ceil(array.length / 100) }, (_, index) =>
    array.slice(index * 100, (index + 1) * 100)
  )) {
    const values: any = chunk.flatMap((record, index) => predicate(record, index, array))
    await prisma.$executeRawUnsafe(
      `UPDATE ${model} SET ${field} = CASE ${chunk.map(() => `WHEN id = ? THEN ?`).join('\n')} ELSE ${field} END;`,
      ...values
    )
  }
```

And usage:
```
await updateManyByField(ctx.prisma, 'TableName', 'fieldName', list, (x) => [x.id, x.fieldName])

// E.g
await updateManyByField(ctx.prisma, 'User', 'email', userEmail, (x) => [x.user_id, x.email])
```

**Comment by RaczoOBY** [comment]
Based on @jeffrafter solution.
I was trying another version without the "ELSE"

Maybe we can try something like this:

```SQL
UPDATE tableName SET fieldName = (CASE WHEN id = 1 THEN 'value1'
WHEN id = 2 THEN 'value2'
WHEN id = 3 THEN 'value3'
WHEN id = 4 THEN 'value4'
END),
anotherFieldName = 'optional-value-to-be-update'
WHERE id IN (1,2,3,4);
```

**Comment by aravindanve** [comment]
If you are using postgres you can also do the following.

Representing each value as two columns `0` and `0_undefined` allows you to update only the defined keys and leave the undefined keys as they are.

For example, with the data:
```ts
const data = [
  { id: 1, name: "person 1" },
  { id: 2, age: 42 },
  { id: 3, age: null },
];
```

You can do:
```ts
const COLUMNS = ["name", "age"];

const count = await prisma.$executeRaw`
  update "person" set
    ${Prisma.join([
      Prisma.sql`"updated_at" = now()`,
      ...COLUMNS.map((field, i) =>
        Prisma.raw(`"${field}" = case when "${i}_undefined" is false then t."${i}" else "${field}" end`),
      ),
    ])}
  from (
    values ${Prisma.join(
      data.map(
        ({ id, ...values }) =>
          Prisma.sql`(${Prisma.join([
            Prisma.sql`${id}`,

            // each value is represented as two columns: `0` is value, `0_undefined` is value is undefined
            ...COLUMNS.map((field) => Prisma.sql`${values[field] ?? null},${values[field] === undefined}`),
          ])})`,
      ),
    )}
  ) as t(${Prisma.join([
    Prisma.sql`"id"`,

    // each value is represented as two columns: `0` is value, `0_undefined` is value is undefined
    ...COLUMNS.map((_, i) => Prisma.raw(`"${i}","${i}_undefined"`)),
  ])})
  where
    "person"."id" = t."id"
`;

console.log(count);
```

(`Prisma.raw` is only used with known constants or array index)
