### ISSUE TITLE
cannot be cast to org.joda.time.DateTime on Subscription for previousValues DateTime

### ISSUE THREAD

**Issue by Fi1osof** [prisma/prisma#2912]
**Describe the bug**
Subscription schema: 
```
subscription orderItem{
  orderItem{
    mutation
    node{
      id
      updatedAt
      status
    }
    updatedFields
    previousValues{
      id
      updatedAt
      status
    }
  }
}
```

**To Reproduce**
Create subscription with DateTime previousValues definition.

**Expected behavior**
Returns DateTime value.
 

**Versions (please complete the following information):**
 - OS: Ubuntu 18
 - `prisma` CLI: prisma/1.6.3 (linux-x64) node-v9.11.1
 - Prisma Server: 1.6? (Docker local_prisma-database_1)
 - `graphql-cli` 2.16.1

**Additional context**
Docker error:
```
[Bugsnag - local / testing] Error report: com.bugsnag.Report@37ac3c1a
java.lang.ClassCastException: java.lang.String cannot be cast to org.joda.time.DateTime
	at sangria.execution.Resolver.resolveValue(Resolver.scala:858)
	at sangria.execution.Resolver.$anonfun$resolveActionsPar$4(Resolver.scala:518)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sangria.execution.Resolver.resolveActionsPar(Resolver.scala:512)
	at sangria.execution.Resolver.resolveValue(Resolver.scala:901)
	at sangria.execution.Resolver.resolveValue(Resolver.scala:807)
	at sangria.execution.Resolver.$anonfun$resolveActionsPar$4(Resolver.scala:518)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sangria.execution.Resolver.resolveActionsPar(Resolver.scala:512)
	at sangria.execution.Resolver.resolveValue(Resolver.scala:901)
	at sangria.execution.Resolver.resolveValue(Resolver.scala:807)
	at sangria.execution.Resolver.$anonfun$resolveActionsPar$15(Resolver.scala:620)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
............
```

**Comment by marktani** [comment]
Can you reproduce this in the latest version, `1.13.7`?
