### ISSUE TITLE
run "prisma login" with proxy failed 

### ISSUE THREAD

**Issue by xiechao06** [prisma/prisma#2932]
**Describe the bug**

Since I am in mainland China, I could not access prisma's servcie unless I use a proxy. but when I run command `prisma login`, it reports an error

**To Reproduce**

running `https_proxy=http://localhost:<port> prisma login`

**Screenshots**

```
**  client Sending query to cloud api +564ms
  client https://api.cloud.prisma.sh +0ms
  client mutation {
  client       requestCloudToken {
  client         secret
  client       }
  client     } +0ms
  client undefined +0ms
  client { headers: {},
  client   agent:
  client    HttpProxyAgent {
  client      domain:
  client       Domain {
  client         domain: null,
  client         _events: [Object],
  client         _eventsCount: 1,
  client         _maxListeners: undefined,
  client         members: [],
  client         sentryContext: [Object] },
  client      _events: {},
  client      _eventsCount: 0,
  client      _maxListeners: undefined,
  client      _promisifiedCallback: false,
  client      timeout: null,
  client      options:
  client       Url {
  client         protocol: 'http:',
  client         slashes: true,
  client         auth: null,
  client         host: '127.0.0.1:1087',
  client         port: '1087',
  client         hostname: '127.0.0.1',
  client         hash: null,
  client         search: null,
  client         query: null,
  client         pathname: '/',
  client         path: '/',
  client         href: 'http://127.0.0.1:1087/' },
  client      secureProxy: false,
  client      proxy:
  client       { protocol: 'http:',
  client         slashes: true,
  client         auth: null,
  client         host: '127.0.0.1',
  client         port: 1087,
  client         hostname: '127.0.0.1',
  client         hash: null,
  client         search: null,
  client         query: null,
  client         href: 'http://127.0.0.1:1087/' } } } +0ms
 !
Error: GraphQL Error (Code: 400): {"response":{"error":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>400 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size=\"1px\">\nBad request.\n\n<BR clear=\"all\">\n<HR noshade size=\"1px\">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: 7tJlNKGdL94XYWafGd_r9JsoSRGAWw5rjaD3XVXJFJMrHXQNUPgPgA==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>","status":400},"request":{"query":"mutation {\n      requestCloudToken {\n        secret\n      }\n    }"}}
    at GraphQLClient.<anonymous> (/Users/xiechao/n/lib/node_modules/prisma/node_modules/graphql-request/src/index.ts:72:13)
    at step (/Users/xiechao/n/lib/node_modules/prisma/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/Users/xiechao/n/lib/node_modules/prisma/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/Users/xiechao/n/lib/node_modules/prisma/node_modules/graphql-request/dist/src/index.js:12:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  util timed out +0ms
Exiting with code: 0

```

**Versions (please complete the following information):**
 - OS: `OS X High Sierra` 
 - `prisma` CLI:  `prisma/1.9.0 (darwin-x64) node-v8.11.3`

**Comment by divyenduz** [comment]
@xiechao06 : Hi 👋 

Thanks for reaching out. Did you install the `proxy` module? 

These are the relevant [docs](https://docs-beta.prisma.io/1.13/develop-prisma-service/prisma-cli/prisma-cli-alx4/#using-a-http-proxy-for-the-cli). 

You also might want to use `http_proxy` / `https_proxy` accordingly. 

Please let me know how that goes. Thanks!
