### ISSUE TITLE
Error: unhandled - wrong column specified for PostgreSQL cursor id

### ISSUE THREAD

**Issue by raxosiris** [prisma/prisma#2959]
Paginating through a query in PostgreSQL based on cursor (ID) results in an unhandled request. The following message in playground is shown:  "Whoops. Looks like an internal server error. Search your server logs for request ID: local:api:cjl6nbp2t00030937ty1tytz7".

**To Reproduce**
1. Make a query with postgreSQL database using the before/after parameters 

**Expected behavior**
The query should resolve.

**Versions (please complete the following information):**
 - OS: [`Ubuntu 16.04`] 
 - `prisma` CLI: [`prisma/1.9.0`]
 - Prisma Server: [`1.9.0`]

**Additional context**
The problem results from a wrong connection being established to PostgreSQL. Instead of querying for  Image.id (Image being my node), prisma is querying for Image.i . Here is additional log output from the docker container: 

{"key":"error/unhandled","requestId":"local:api:cjl6n190001000837clrod0hc","clientId":"digitalocean$digitalocean","payload":{"exception":"org.postgresql.util.PSQLException: ERROR: column Image.i does not exist\n  Position: 62","query":"{\n  imagesConnection(first: 4, before: \"cjl5fh8lw00x30837kg6mwb9t\") {\n    pageInfo {\n      startCursor\n      endCursor\n    }\n    edges {\n      node {\n        id\n      }\n    }\n    aggregate {\n      count\n    }\n  }\n}\n","variables":"{}","code":"0","stack_trace":"org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)\\n org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)\\n org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)\\n org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)\\n org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)\\n org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)\\n org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)\\n com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)\\n com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)\\n slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)\\n slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)\\n slick.jdbc.Invoker.foreach(Invoker.scala:48)\\n slick.jdbc.Invoker.foreach$(Invoker.scala:47)\\n slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)\\n slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)\\n slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)\\n slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)\\n slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)\\n java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n java.lang.Thread.run(Thread.java:748)","message":"ERROR: column Image.i does not exist\n  Position: 62"}}
[Bugsnag - local / testing] Error report: com.bugsnag.Report@563ac9c6
Obtaining exclusive agent lock...
Obtaining exclusive agent lock... Successful.
Deployment worker initialization complete.
Initializing workers...
Successfully started 1 workers.
Server running on :4466
Version is up to date.
[Metrics] Warning: no metrics will be recorded.
[Metrics] Warning: no metrics will be recorded.
org.postgresql.util.PSQLException: ERROR: column Image.i does not exist
  Position: 62
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.Invoker.foreach(Invoker.scala:48)
	at slick.jdbc.Invoker.foreach$(Invoker.scala:47)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)
	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by raxosiris** [comment]
It seems I was using an outdated deployment of Postgres. I tried removing the container and recreating with the latest prisma cli. The issue is resolved now
