### ISSUE TITLE
PostgreSQL Time (without timezone) data type not working as expected

### ISSUE THREAD

**Issue by pachiraDIG** [prisma/prisma#2975]
## Bug description

When using TIME data type, user should be able to format data as seen in [Postgres docs](https://www.postgresqltutorial.com/postgresql-time/):

```
CREATE TABLE shifts (
    id serial PRIMARY KEY,
    shift_name VARCHAR NOT NULL,
    start_at TIME NOT NULL,
    end_at TIME NOT NULL
);

INSERT INTO shifts(shift_name, start_at, end_at)
VALUES('Morning', '08:00:00', '12:00:00'),
      ('Afternoon', '13:00:00', '17:00:00'),
      ('Night', '18:00:00', '22:00:00');
```

But when attempting this, I get an error message:
`Got invalid value '12:15:00' on prisma.updateOnewedding. Provided String, expected DateTime.`

## Expected behavior

Insert data like expected for the Postgres type:
![image](https://user-images.githubusercontent.com/46540659/86981526-ad1fe000-c13b-11ea-8978-bd1885459d0a.png)

## Prisma information

Schema
```
model wedding {
  ceremony_duration     Int?
  ceremony_start        DateTime?
  reception_end         DateTime?
  reception_hard_cutoff Boolean           @default(false)
  reception_start       DateTime?
  weddingid             String            @default(dbgenerated()) @id
  wedding_type_id       String?
  wedding_type          wedding_type?     @relation(fields: [wedding_type_id], references: [wedding_typeid])
}
```

Query
```
await prisma.wedding.update({
      where: {
        weddingid: body.weddingId
      },
      data: {
        ceremony_start: input.ceremony.start,
        ceremony_duration: input.ceremony.duration,
        reception_start: input.reception.start,
        reception_end: input.reception.end,
        reception_hard_cutoff: input.hardCutoff
      },
      include: {
        wedding_type: {
          select: {
            wedding_type: true
          }
        }
      }
    })
```

Debug
```
express:router dispatching PUT /wedding +21s
  express:router query  : /wedding +0ms
  express:router expressInit  : /wedding +0ms
  express:router corsMiddleware  : /wedding +1ms
  express:router jsonParser  : /wedding +0ms
  body-parser:json content-type "application/json;charset=utf-8" +0ms
  body-parser:json content-encoding "identity" +3ms
  body-parser:json read body +0ms
  body-parser:json parse body +2ms
  body-parser:json parse json +0ms
  express:router urlencodedParser  : /wedding +0ms
  body-parser:urlencoded body already parsed +0ms
  express:router logger  : /wedding +0ms
  express:router getCreds  : /wedding +0ms
process.env.GMAPS_KEY: ...
  express:router trim prefix (/wedding) from url /wedding +1ms
  express:router router /wedding : /wedding +0ms
  express:router dispatching PUT / +0ms
PrismaClientValidationError:
Invalid `prisma.wedding.update()` invocation in
/home/brendan/wdt/wdt-express/src/resources/wedding/wedding.controllers.js:147:41

  143
  144 async function updateBigPicture() {
  145   const input = body.input
  146
→ 147   const update = await prisma.wedding.update({
          where: {
            weddingid: '5af4605b-eea1-4006-a51f-efb400089ca5'
          },
          data: {
            ceremony_start: '12:20:00',
                            ~~~~~~~~~~
            ceremony_duration: 5,
            reception_start: '12:20:00',
                             ~~~~~~~~~~
            reception_end: '12:20:00',
                           ~~~~~~~~~~
            reception_hard_cutoff: false
          },
          include: {
            wedding_type: {
              select: {
                wedding_type: true
              }
            }
          }
        })

Argument ceremony_start: Got invalid value '12:20:00' on prisma.updateOnewedding. Provided String, expected DateTime.
Argument reception_start: Got invalid value '12:20:00' on prisma.updateOnewedding. Provided String, expected DateTime.
Argument reception_end: Got invalid value '12:20:00' on prisma.updateOnewedding. Provided String, expected DateTime.


    at Document.validate (/home/brendan/wdt/wdt-express/node_modules/@prisma/client/src/runtime/query.ts:271:19)
    at Object.model [as wedding] (/home/brendan/wdt/wdt-express/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:629:20)
    at Object.update (/home/brendan/wdt/wdt-express/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:787:33)
    at updateBigPicture (/home/brendan/wdt/wdt-express/src/resources/wedding/wedding.controllers.js:147:41)
    at updateWedding (/home/brendan/wdt/wdt-express/src/resources/wedding/wedding.controllers.js:191:25)
    at Layer.handle [as handle_request] (/home/brendan/wdt/wdt-express/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/brendan/wdt/wdt-express/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/brendan/wdt/wdt-express/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/brendan/wdt/wdt-express/node_modules/express/lib/router/layer.js:95:5)
    at /home/brendan/wdt/wdt-express/node_modules/express/lib/router/index.js:281:22
  morgan log request +3ms
```

## Environment & setup

- OS: Windows 10
- Database: PostgreSQL
- Prisma version: 2.2.0
- Node.js version: 12.18.2

**Comment by pantharshit00** [comment]
@pachiraDIG We support Date formats supported in https://en.wikipedia.org/wiki/ISO_8601 standard.

Other formats will not be automatically converted in the client. You will need to use the JS date object here. 


```js
const update = await prisma.wedding.update({
          where: {
            weddingid: '5af4605b-eea1-4006-a51f-efb400089ca5'
          },
          data: {
            ceremony_start: '12:20:00',
            ceremony_duration: 5,
            reception_start: new Date('12:20:00'),
            reception_end: new Date('12:20:00'),
            reception_hard_cutoff: false
          },
          include: {
            wedding_type: {
              select: {
                wedding_type: true
              }
            }
          }
        })
```
