### ISSUE TITLE
DATABASE_URL required when setting `datasources.db.url`

### ISSUE THREAD

**Issue by defrex** [prisma/prisma#2987]
## Bug description

I originally identified this as a regression of https://github.com/prisma/prisma/issues/2609.

`DATABASE_URL` is required, even when explicitly setting `datasources.db.url` in the `PrismaClient` constructor.

## How to reproduce

Given the following,

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  // ...etc
}
```

```typescript

import { PrismaClient } from '@prisma/client'

const url = `postgresql://user:pass@localhost/mydb`

const prisma = new PrismaClient({
  datasources: { db: { url } },
})

prisma.user.count()
```

Without setting `DATABASE_URL`, I get this error.

```
(node:35938) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.user.count()` invocation in
/Users/defrex/Code/treasure/api/src/prisma-repro.ts:19:47

  15 const prisma = new PrismaClient({
  16   datasources: { db: { url } },
  17 })
  18 
→ 19 console.log('user count', await prisma.user.count()


  error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   | 
 6 |   provider = "postgresql"
 7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at PrismaClientFetcher.message [as _request] (/Users/defrex/Code/treasure/api/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:999:51)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:35938) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35938) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected behavior

I expect it to connect without needing to set the `DATABASE_URL` environment variable.

This error can be solved by setting `DATABASE_URL` to a "dummy" value that appears valid. Eg. `DATABASE_URL=postgres://notarealhostname`.

## Environment & setup

- OS: Mac OS
- Database: Postgres
- Prisma version: 2.2.0
- Node.js version: 12.18.1

**Comment by janpio** [comment]
Do you get this output just when executing the count()?

**Comment by defrex** [comment]
Any DB query from that `prisma` object will do.

**Comment by janpio** [comment]
Do you have a `.env` file in your project root as well? We currently have a bug that this file is loaded by the CLI instead of just the `prisma/.env` as documented. This will be fixed on Monday if that is the reason.

**Comment by defrex** [comment]
I do have a `.env` in my project root, but it doesn't contain `DATABASE_URL`.

**Comment by defrex** [comment]
And to clarify, I _do not_ have a `prisma/.env` file.

**Comment by janpio** [comment]
Exactly, the CLI currently does read the `.env` in the root although it should not. Can you try if putting the value in there fixes your issue?

**Comment by defrex** [comment]
Putting an incorrect but well-formed value for `DATABASE_URL` in `.env` does indeed remove the error, implying that the root `.env` is being read.

I'm not sure what this has to do with the issue though. The problem is that `DATABASE_URL` shouldn't be required at all, rather than where it should be specified.

**Comment by janpio** [comment]
That is just not supported, as we require a valid schema. You can replace the `env("DATABASE_URL")` with a nonsense value in the `schema.prisma` if you want, then no error message should appear and the explicitly defined wvalue will overwrite the nonsense value.

**Comment by defrex** [comment]
I still need it for introspection, and eventually migrations, locally. I guess I'll just live with setting a nonsense value in production. 🤷‍♀️
