### ISSUE TITLE
Fatal Error (missing key) caused when selecting different fields for a child type in fragments

### ISSUE THREAD

**Issue by kelfish** [prisma/prisma#2995]
**Describe the bug**
When using fragments to retrieve a array of a child type you must select all the fields you want for all fragments in the first reference of the child type.

Trying to select additional fields for later fragments in the query causes a Fatal Error in Prisma.

This happens in 1.15.x only, queries work without issue in 1.14.x.

**Error Received**

```
{"key":"error/unhandled","requestId":"local:api:cjllug8c500290824m814tm30","clientId":"api@dev","payload":{"exception":"java.util.NoSuchElementException: key not found: name","query":"query ($_where: EntrepreneurWhereInput, $_orderBy: EntrepreneurOrderByInput, $_skip: Int, $_after: String, $_before: String, $_last: Int) {\n  entrepreneurs(first: 2, where: $_where, orderBy: $_orderBy, skip: $_skip, after: $_after, before: $_before, last: $_last) {\n    id\n    name\n    sectors {\n      id\n    }\n    ...SectorCard\n  }\n}\n\nfragment SectorCard on Entrepreneur {\n  sectors {\n    name\n  }\n}\n","variables":"{\"_where\":{\"archived\":false}}","code":"0","stack_trace":"scala.collection.immutable.Map$Map1.apply(Map.scala:108)\\n com.prisma.api.schema.ObjectTypeBuilder.mapToOutputResolve(ObjectTypeBuilder.scala:289)\\n com.prisma.api.schema.ObjectTypeBuilder.$anonfun$mapClientField$1(ObjectTypeBuilder.scala:111)\\n sangria.execution.Resolver.resolveField(Resolver.scala:1024)\\n sangria.execution.Resolver.$anonfun$collectActionsPar$1(Resolver.scala:445)\\n scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)\\n scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)\\n scala.collection.Iterator.foreach(Iterator.scala:929)\\n scala.collection.Iterator.foreach$(Iterator.scala:929)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1417)\\n scala.collection.IterableLike.foreach(IterableLike.scala:71)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:70)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)\\n scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)\\n scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)\\n sangria.execution.Resolver.collectActionsPar(Resolver.scala:439)\\n sangria.execution.Resolver.resolveValue(Resolver.sc	at com.prisma.api.schema.ObjectTypeBuilder.mapToOutputResolve(ObjectTypeBuilder.scala:289)
ala:899)\\n sangria.execution.Resolver.$anonfun$resolveValue$1(Resolver.scala:820)\\n scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)\\n scala.collection.Iterator.foreach(Iterator.scala:929)\\n scala.collection.Iterator.foreach$(Iterator.scala:929)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1417)\\n scala.collection.IterableLike.foreach(IterableLike.scala:71)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:70)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n scala.collection.TraversableLike.map(TraversableLike.scala:234)\\n scala.collection.TraversableLike.map$(TraversableLike.scala:227)\\n scala.collection.AbstractTraversable.map(Traversable.scala:104)\\n sangria.execution.Resolver.resolveValue(Resolver.scala:819)\\n sangria.execution.Resolver.resolveValue(Resolver.scala:807)\\n sangria.execution.Resolver.$anonfun$resolveActionsPar$13(Resolver.scala:609)\\n scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)\\n scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n akk	at com.prisma.api.schema.ObjectTypeBuilder.$anonfun$mapClientField$1(ObjectTypeBuilder.scala:111)
	at sangria.execution.Resolver.resolveField(Resolver.scala:1024)
	at sangria.execution.Resolver.$anonfun$collectActionsPar$1(Resolver.scala:445)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.sca.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)","message":"key not found: name"}}
ala:104)
	at sangria.execution.Resolver.collectActionsPar(Resolver.scala:439)
	at sangria.execution.Resolver.resolveValue(Resolver.scala:899)
	at sangria.execution.Resolver.$anonfun$resolveValue$1(Resolver.scala:820)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at sangria.execution.Resolver.resolveValue(Resolver.scala:819)
	at sangria.execution.Resolver.resolveValue(Resolver.scala:807)
	at sangria.execution.Resolver.$anonfun$resolveActionsPar$13(Resolver.scala:609)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**To Reproduce**

Run a query on the Playground using fragments with two different shapes of a child type:

Assuming the types:

```
type Sector {
		id
		name
		code
	}

	type Entrepreneur {
		id: ID
		name: String
		sectors: [Sector!]!
	}
```

Run a query with fragments:
	
```	
query {
  entrepreneurs(first:1) {
    id
    name
    sectors {
      id
      code
    }
    ...SectorCard
  }
}
fragment SectorCard on Entrepreneur {
	sectors{
  		name
	} 
}
```

**Expected behavior**
- Error informing that all fragments/child queried types must have the same fields; OR
- Return all selected fields for each fragment

**Versions (please complete the following information):**
 - Prisma Server: `1.15.2`

**Additional context**
I suspect this is caused by the performance improvement of selecting only the requested fields:
https://github.com/prisma/prisma/commit/13d67d8e6a52b4c79d29d74aafc37a6bcfb2dccc

**Comment by mavilein** [comment]
Thanks for reporting and providing such a well written description! 🙏 
We fixed this and this is part of release `1.16.1`, which will be available in a few minutes.
