### ISSUE TITLE
java.sql.SQLSyntaxErrorException: (conn=44) Unknown column 'Lease_Alias.id' in 'IN/ALL/ANY subquery'

### ISSUE THREAD

**Issue by crholliday** [prisma/prisma#3018]
I am trying to run a fairly deeply nested sub-select and it is bonking out. The schema is below:

`Schema`

```graphql
type Property {
  id: ID! @unique
  name: String! @unique
  numberOfUnits: Int!
  squareFootage: Int!
  zipcode: String!
  city: String!
  stateCode: String!
  isActive: Boolean! @default(value: "true")
  units: [Unit!]! @relation(name: "UnitProperty")
}

type Unit {
  id: ID! @unique
  property: Property! @relation(name: "UnitProperty")
  tenant: Tenant @relation(name: "TenantUnit")
  lease: Lease 
  streetAddress: String! @unique
  squareFootage: Int!
  numberOfBedrooms: Int!
  numberOfBathrooms: Float!
  petsAllowed: Boolean!
  dedicatedParkingSpaces: Int! # 0, 1, 2 etc
  notes: String
  isActive: Boolean! @default(value: "true")
}

type Lease {
  id: ID! @unique
  tenant: Tenant
  unit: Unit
  leaseDate: DateTime!
  startDate: DateTime!
  endDate: DateTime!
  term: String!
  rent: Float!
  securityDeposit: Float!
  petDeposit: Float!
  rentDeposit: Float!
  isDeleted: Boolean! @default(value: "false")
}

```

`Query`
```graphql
query {
  payments (
    where: {
      lease: {
        unit:{
          property: {id: "cjl7ya68f00280892e16yv0l3" }
        }
      }
    }
  	) {
    amount
  }
}
```
I then receive the following error:

```sh
java.sql.SQLSyntaxErrorException: (conn=44) Unknown column 'Lease_Alias.id' in 'IN/ALL/ANY subquery'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:173)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at com.prisma.api.connector.jdbc.database.BuilderBase.$anonfun$queryToDBIO$1(BuilderBase.scala:51)
        at com.prisma.api.connector.jdbc.database.BuilderBase.$anonfun$jooqToDBIO$1(BuilderBase.scala:81)
        at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
        at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Unknown column 'Lease_Alias.id' in 'IN/ALL/ANY subquery'
Query is: select *
from `rental-commander-backend@dev`.`Payment` as `Alias`
where `Alias`.`id` in (
  select `rental-commander-backend@dev`.`_LeaseToPayment`.`B`
  from `rental-commander-backend@dev`.`_LeaseToPayment`
  where `Lease_Alias`.`id` in (
    select `rental-commander-backend@dev`.`_LeaseToUnit`.`A`
    from `rental-commander-backend@dev`.`_LeaseToUnit`
    where `rental-commander-backend@dev`.`_LeaseToUnit`.`B` in (
      select `rental-commander-backend@dev`.`_UnitProperty`.`B`
      from `rental-commander-backend@dev`.`Property` as `Property_Unit_Lease_Alias`
        join `rental-commander-backend@dev`.`_UnitProperty`
        on (
          `Property_Unit_Lease_Alias`.`id` = `rental-commander-backend@dev`.`_UnitProperty`.`A`
          and `Property_Unit_Lease_Alias`.`id` = ?
        )
    )
  )
)
order by `Alias`.`id` asc, parameters ['cjl7ya68f00280892e16yv0l3']
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
        ... 13 more
java.sql.SQLSyntaxErrorException: (conn=44) Unknown column 'Lease_Alias.id' in 'IN/ALL/ANY subquery'
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:173)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at com.prisma.api.connector.jdbc.database.BuilderBase.$anonfun$queryToDBIO$1(BuilderBase.scala:51)
        at com.prisma.api.connector.jdbc.database.BuilderBase.$anonfun$jooqToDBIO$1(BuilderBase.scala:81)
        at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
        at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Unknown column 'Lease_Alias.id' in 'IN/ALL/ANY subquery'
Query is: select *
from `rental-commander-backend@dev`.`Payment` as `Alias`
where `Alias`.`id` in (
  select `rental-commander-backend@dev`.`_LeaseToPayment`.`B`
  from `rental-commander-backend@dev`.`_LeaseToPayment`
  where `Lease_Alias`.`id` in (
    select `rental-commander-backend@dev`.`_LeaseToUnit`.`A`
    from `rental-commander-backend@dev`.`_LeaseToUnit`
    where `rental-commander-backend@dev`.`_LeaseToUnit`.`B` in (
      select `rental-commander-backend@dev`.`_UnitProperty`.`B`
      from `rental-commander-backend@dev`.`Property` as `Property_Unit_Lease_Alias`
        join `rental-commander-backend@dev`.`_UnitProperty`
        on (
          `Property_Unit_Lease_Alias`.`id` = `rental-commander-backend@dev`.`_UnitProperty`.`A`
          and `Property_Unit_Lease_Alias`.`id` = ?
        )
    )
  )
)
order by `Alias`.`id` asc, parameters ['cjl7ya68f00280892e16yv0l3']
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
        ... 13 more
{"key":"error/unhandled","requestId":"local:api:cjlofdnne00260992mvxnc57k","clientId":"rental-commander-backend@dev","payload":{"exception":"java.sql.SQLSyntaxErrorException: (conn=44) Unknown column 'Lease_Alias.id' in 'IN/ALL/ANY subquery'","query":"{\n  payments(where: {lease: {unit: {property: {id: \"cjl7ya68f00280892e16yv0l3\"}}}}) {\n    amount\n  }\n}\n","variables":"{}","code":"0","stack_trace":"org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)\\n org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)\\n org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)\\n org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)\\n org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)\\n org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:173)\\n com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)\\n com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)\\n com.prisma.api.connector.jdbc.database.BuilderBase.$anonfun$queryToDBIO$1(BuilderBase.scala:51)\\n com.prisma.api.connector.jdbc.database.BuilderBase.$anonfun$jooqToDBIO$1(BuilderBase.scala:81)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)\\n java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n java.lang.Thread.run(Thread.java:748)","message":"(conn=44) Unknown column 'Lease_Alias.id' in 'IN/ALL/ANY subquery'"}}
[Bugsnag - local / testing] Error report: com.bugsnag.Report@50ef8ba7
```

**Versions (please complete the following information):**
 - OS: Docker on Windows 10
 - Prisma Server: 1.14

**Comment by crholliday** [comment]
This looks like it may be the same as #2899 and solved by 1.15.2?

**Comment by marktani** [comment]
Yes, I agree @crholliday. Could you upgrade and confirm that it is also fixed for you?

**Comment by crholliday** [comment]
I can confirm it is fixed. Thanks!
