### ISSUE TITLE
Self-referential one-to-many relationship query fails: "subquery has too many columns"

### ISSUE THREAD

**Issue by timleslie** [prisma/prisma#3078]
## Bug description

I have a `User` model with a one-to-many self-referential relationship, as follows:

```
model User {
  id         Int     @id @default(autoincrement())
  name       String?
  friends    User[]  @relation("UserfriendOf")
  friendOf   User?   @relation("UserfriendOf", fields: [friendOfId], references: [id])
  friendOfId Int?
}
```

A user can be the `friendOf` one person, but can be `friends` with many (forgive the contrived example).

I want to filter the users based on properties of the `friendOf` field, for example:

```
  await prisma.user.findMany({where: { friendOf: { name: { contains: "B" } } } });
```

Running this query causes the prisma engine to throw the following error:

```
Invalid `prisma.user.findMany()` invocation in
/Users/timleslie/src/prisma-issue/index.ts:6:21

  2 const prisma = new PrismaClient()
  3 
  4 async function main() {
  5   // Filter based on the name of the friend
→ 6   await prisma.user.findMany(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "subquery has too many columns", detail: None, hint: None, position: Some(Original(163)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_expr.c"), line: Some(2070), routine: Some("transformSubLink") }) }) })
    at PrismaClientFetcher._request (/Users/timleslie/src/prisma-issue/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:999:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:75365) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:75365) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

A full debug run gives:

```
  prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: '/Users/timleslie/src/prisma-issue/prisma',
  prisma-client     debug: false,
  prisma-client     datamodelPath: '/Users/timleslie/src/prisma-issue/node_modules/.prisma/client/schema.prisma',
  prisma-client     prismaPath: undefined,
  prisma-client     engineEndpoint: undefined,
  prisma-client     generator: {
  prisma-client       name: 'client',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: '/Users/timleslie/src/prisma-issue/node_modules/@prisma/client',
  prisma-client       binaryTargets: [],
  prisma-client       experimentalFeatures: [Array],
  prisma-client       config: {}
  prisma-client     },
  prisma-client     showColors: false,
  prisma-client     logLevel: undefined,
  prisma-client     logQueries: undefined,
  prisma-client     flags: [],
  prisma-client     clientVersion: '2.2.2',
  prisma-client     enableExperimental: [ 'aggregations' ]
  prisma-client   }
  prisma-client } +0ms
  prisma-client Prisma Client call: +108ms
  prisma-client prisma.user.findMany({
  prisma-client   where: {
  prisma-client     friendOf: {
  prisma-client       name: {
  prisma-client         contains: 'B'
  prisma-client       }
  prisma-client     }
  prisma-client   }
  prisma-client }) +1ms
  prisma-client Generated request: +0ms
  prisma-client query {
  prisma-client   findManyUser(where: {
  prisma-client     friendOf: {
  prisma-client       name_contains: "B"
  prisma-client     }
  prisma-client   }) {
  prisma-client     id
  prisma-client     name
  prisma-client     friendOfId
  prisma-client   }
  prisma-client }
  prisma-client  +0ms
  engine { cwd: '/Users/timleslie/src/prisma-issue/prisma' } +0ms
  engine {
  engine   dotPrismaPath: '/Users/timleslie/src/prisma-issue/node_modules/.prisma/client/query-engine-darwin'
  engine } +0ms
  plusX Execution permissions of /Users/timleslie/src/prisma-issue/node_modules/.prisma/client/query-engine-darwin are fine +0ms
  engine {
  engine   flags: [ '--enable-experimental=aggregations', '--enable-raw-queries' ]
  engine } +1ms
  engine port: 65291 +3ms
  engine stdout {
  timestamp: 'Jul 20 09:03:17.028',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a postgresql pool with up to 9 connections.' }
} +22ms
  engine stdout {
  timestamp: 'Jul 20 09:03:17.035',
  level: 'INFO',
  target: 'query_engine::server',
  fields: { message: 'Started http server on 127.0.0.1:65291' }
} +6ms
  prisma-client Client Version 2.2.2 +37ms
  prisma-client Engine Version a9e8c3d97ef2a0cf59256e6b26097f2a80f0a6a4 +0ms
  engine {
  engine   error: PrismaClientUnknownRequestError: Error occurred during query execution:
  engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "subquery has too many columns", detail: None, hint: None, position: Some(Original(163)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_expr.c"), line: Some(2070), routine: Some("transformSubLink") }) }) })
  engine       at NodeEngine.graphQLToJSError (/Users/timleslie/src/prisma-issue/node_modules/@prisma/engine-core/dist/NodeEngine.js:761:1)
  engine       at /Users/timleslie/src/prisma-issue/node_modules/@prisma/engine-core/dist/NodeEngine.js:709:1
  engine       at process.result (internal/process/task_queues.js:93:5)
  engine       at PrismaClientFetcher._request (/Users/timleslie/src/prisma-issue/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:957:15)
  engine } +37ms
  prisma-client Error: Error occurred during query execution:
  prisma-client ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "subquery has too many columns", detail: None, hint: None, position: Some(Original(163)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_expr.c"), line: Some(2070), routine: Some("transformSubLink") }) }) })
  prisma-client     at NodeEngine.graphQLToJSError (/Users/timleslie/src/prisma-issue/node_modules/@prisma/engine-core/dist/NodeEngine.js:761:1)
  prisma-client     at /Users/timleslie/src/prisma-issue/node_modules/@prisma/engine-core/dist/NodeEngine.js:709:1
  prisma-client     at process.result (internal/process/task_queues.js:93:5)
  prisma-client     at PrismaClientFetcher._request (/Users/timleslie/src/prisma-issue/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:957:15) +35ms
  engine Stopping Prisma engine +4ms
(node:75376) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.user.findMany()` invocation in
/Users/timleslie/src/prisma-issue/index.ts:6:21

  2 const prisma = new PrismaClient()
  3 
  4 async function main() {
  5   // Filter based on the name of the friend
→ 6   await prisma.user.findMany(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42601"), message: "subquery has too many columns", detail: None, hint: None, position: Some(Original(163)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_expr.c"), line: Some(2070), routine: Some("transformSubLink") }) }) })
    at PrismaClientFetcher._request (/Users/timleslie/src/prisma-issue/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:999:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:75376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:75376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## How to reproduce

1. Create a new project as per https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-prisma-migrate-typescript-postgres
2. Edit the `schema.prisma` file with the schema given below.
3. Run the migrations and generate the client as per the docs
4. Create an `index.ts` file with the contents given below
5. Run `DEBUG="*" npx ts-node index.ts`

## Expected behavior

The `findMany` query should not throw an exception.

### `schema.prisma`

```
datasource postgresql {
  url      = env("DATABASE_URL")
  provider = "postgresql"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id         Int     @id @default(autoincrement())
  name       String?
  friends    User[]  @relation("UserfriendOf")
  friendOf   User?   @relation("UserfriendOf", fields: [friendOfId], references: [id])
  friendOfId Int?
}
```

### `index.ts`
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {
  // Filter based on the name of the friend
  await prisma.user.findMany({where: { friendOf: { name: {contains: "B" } } } });
}

main()
  .catch((e) => {
    throw e
  })
  .finally(async () => {
    await prisma.disconnect()
  })

```

## Environment & setup

- OS: Mac OS 10.15.5
- Database: PostgreSQL 12
- Prisma version: 2.2.2
- Node.js version: 12.11.0

**Comment by divyenduz** [comment]
I am able to reproduce this with `2.4.0-dev.15`

![image](https://user-images.githubusercontent.com/746482/88555158-0dbc8180-d045-11ea-8212-14969ef51ff5.png)

**Comment by timleslie** [comment]
Confirming that this is still an issue in `2.4.0` 👍

**Comment by janpio** [comment]
This is most probably also still an issue with 2.5.0 - but we are starting work on investigating and potentially fixing this soon.

**Comment by timleslie** [comment]
Thanks for the feedback @janpio, much appreciated 🙏

**Comment by timleslie** [comment]
Can confirm that the issue I was seeing has been fixed 👍
