### ISSUE TITLE
Prisma should support SQLite's default date format

### ISSUE THREAD

**Issue by internalfx** [prisma/prisma#3084]
Prisma should support the default date format for CURRENT_TIMESTAMP.

For example...
```
sqlite> .mode column
sqlite> .headers on

sqlite> CREATE TABLE date_test ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "name" TEXT, "created_at" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP);

sqlite> INSERT INTO date_test (name) VALUES ("bob");

sqlite> SELECT * from date_test;

id          name        created_at         
----------  ----------  -------------------
1           bob         2020-07-17 21:56:16
```

From the SQLite Docs...

```
 SQLite has no DATETIME datatype. Instead, dates and times can be stored in any of these ways:

    As a TEXT string in the ISO-8601 format. Example: '2018-04-02 12:13:46'.
    As an INTEGER number of seconds since 1970 (also known as "unix time").
    As a REAL value that is the fractional Julian day number. 
```

But, SQLite _seems_ to default to **ISO-8601** So I would propose that prisma support this format.

As it stands now reading ISO-8601 in prisma causes a crash.

**Comment by hriziya** [comment]
I just tried prisma today and stucked at the same error `Could not parse DateTime` as I have migrated the database from mysql to sqlite so all my dates are in ISO-8601 format only. `2020-07-23 22:17:23`.

Please add support for this datetime parsing. 
Thanks.

**Comment by divyenduz** [comment]
I am able to reproduce this, running findMany on such a table produces the following error: 

```
(node:77267) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.date_test.findMany()` invocation in
/Users/divyendusingh/Documents/prisma/triage/prisma-3084/index.js:6:39

  2
  3 const prisma = new PrismaClient()
  4
  5 async function main() {
→ 6   const data = await prisma.date_test.findMany(
  PANIC: called `Result::unwrap()` on an `Err` value: Could not parse stored DateTime string: 2020-07-29 12:35:17 (input contains invalid characters)

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```

For simplicity, adding the exported SQL too but note that this date was generated by SQLite

```
CREATE TABLE date_test ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "name" TEXT, "created_at" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP);

INSERT INTO "date_test" ("id", "name", "created_at") VALUES
('1', 'bob', '2020-07-29 12:35:17');
```

**Comment by Jolg42** [comment]
I could also reproduce this in my project with the latest dev `2.5.0-dev.19`
```
  prisma-client Prisma Client call: +11s
  prisma-client prisma.user.findMany({
  prisma-client   where: {
  prisma-client     id: {
  prisma-client       lt: 100
  prisma-client     }
  prisma-client   },
  prisma-client   orderBy: {
  prisma-client     id: 'desc'
  prisma-client   }
  prisma-client }) +0ms
  prisma-client Generated request: +0ms
  prisma-client query {
  prisma-client   findManyUser(
  prisma-client     where: {
  prisma-client       id_lt: 100
  prisma-client     }
  prisma-client     orderBy: [
  prisma-client       {
  prisma-client         id: desc
  prisma-client       }
  prisma-client     ]
  prisma-client   ) {
  prisma-client     age
  prisma-client     createdAt
  prisma-client     email
  prisma-client     firstName
  prisma-client     id
  prisma-client     lastName
  prisma-client     password
  prisma-client     updatedAt
  prisma-client   }
  prisma-client }
  prisma-client  +0ms
  engine stdout {
  timestamp: 'Aug 11 11:59:00.764',
  level: 'ERROR',
  target: 'query_engine',
  fields: {
    message: 'PANIC',
    reason: 'called `Result::unwrap()` on an `Err` value: Could not parse stored DateTime string: 2020-08-10 14:37:48 (input contains invalid characters)',
    file: 'query-engine/connectors/sql-query-connector/src/row.rs',
    line: 154,
    column: 26
  }
```

<img width="541" alt="Screen Shot 2020-08-11 at 12 04 16" src="https://user-images.githubusercontent.com/1328733/89885129-de704d80-dbca-11ea-9155-77566ea8df50.png">

**Comment by mavilein** [comment]
That might be hard to do. Whether a space is allowed instead of a `T` seems to be complicated topic: https://stackoverflow.com/questions/9531524/in-an-iso-8601-date-is-the-t-character-mandatory

**Comment by internalfx** [comment]
@mavilein If I were to make a suggestion to the SQLite team when it was built (with the convenience of today's knowledge). I would suggest they have the "T". But I doubt they would be willing to (nor would I suggest they) break years of backwards compatibility to add a "T" now.

The ship has sailed and the decision is already made. For there to be real Date compatibility between prisma and SQLite the format that has a space needs to be supported.

**Comment by pantharshit00** [comment]
Another report of this: https://github.com/prisma/prisma-client-js/issues/875

**Comment by internalfx** [comment]
I'd like to bring more attention to this issue because after working with prisma for a few months it has been quite a burden for 2 reasons....

1. It makes using multiple database adapters very difficult because I must manually generate Unix Epoch Timestamps in my SQL queries myself, this would normally be unnecessary.
2. When viewing my database, the data itself is less useful. A long integer doesn't covey nearly the meaning that `2020-10-18 12:16:04` does.

**Comment by jasonkuhrt** [comment]
I just hit this case while working on Prisma Client benchmarks. I'm documenting the workaround in that project for now as follows:

> - Sequelize expects sqlite DATETIME columns to contain ISO formatted time stamps. Prisma Client however inserts unix timestamps. Since we use Prisma Client to seed the database, the result is that when sequelize benchmarks try to run against Sqlite they hit this runtime error:
>
>   ```
>    TypeError: date.includes is not a function
>      at parse (/Users/jasonkuhrt/projects/prisma/prisma-client-js-benchmarks/node_modules/sequelize/lib/dialects/sqlite/data-types.js:56:17)
>      at Query.applyParsers (/Users/jasonkuhrt/projects/prisma/prisma-client-js-benchmarks/node_modules/sequelize/lib/dialects/sqlite/query.js:357:14)
>      at /Users/jasonkuhrt/projects/prisma/prisma-client-js-benchmarks/node_modules/sequelize/lib/dialects/sqlite/query.js:144:20
>      at /Users/jasonkuhrt/projects/prisma/prisma-client-js-benchmarks/node_modules/lodash/lodash.js:13427:38
>      at /Users/jasonkuhrt/projects/prisma/prisma-client-js-benchmarks/node_modules/lodash/lodash.js:4925:15
>      at baseForOwn (/Users/jasonkuhrt/projects/prisma/prisma-client-js-benchmarks/node_modules/lodash/lodash.js:2990:24)
>      at Function.mapValues (/Users/jasonkuhrt/projects/prisma/prisma-client-js-benchmarks/node_modules/lodash/lodash.js:13426:7)
>      at /Users/jasonkuhrt/projects/prisma/prisma-client-js-benchmarks/node_modules/sequelize/lib/dialects/sqlite/query.js:117:18
>      at Array.map (<anonymous>)
>      at Query._handleQueryResponse (/Users/jasonkuhrt/projects/prisma/prisma-client-js-benchmarks/node_modules/sequelize/lib/dialects/sqlite/query.js:116:25)
>    ```
