### ISSUE TITLE
Introspection: "could not get columns"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3125]
Error reports for 2.2.0 and 2.3.0:
https://prisma-errors.netlify.app/report/9312
https://prisma-errors.netlify.app/report/8980

Rust Stacktrace:
```
0: user_facing_errors::Error::new_in_panic_hook
   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:515
   3: rust_begin_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:419
   4: core::panicking::panic_fmt
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/panicking.rs:111
   5: core::option::expect_failed
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/option.rs:1260
   6: sql_schema_describer::postgres::SqlSchemaDescriber::get_table
   7: <sql_schema_describer::postgres::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  13: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  14: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  15: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  16: futures::future::chain::Chain<A,B,C>::poll
  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  18: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  19: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  20: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  21: futures::task_impl::std::set
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: tokio::runtime::enter::Enter::block_on
  24: tokio::runtime::context::enter
  25: tokio::runtime::handle::Handle::enter
  26: introspection_engine::main
  27: std::rt::lang_start::{{closure}}
  28: std::rt::lang_start_internal::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
      std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:51
  29: main
  30: __libc_start_main
  31: <unknown>

```

JS error:
```
Error: [libs/sql-schema-describer/src/postgres.rs:125:23] could not get columns
    at IntrospectionEngine.<anonymous> (/usr/src/app/node_modules/@prisma/cli/build/index.js:2:1994783)
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/node_modules/@prisma/cli/build/index.js:2:1991796)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by janpio** [comment]
Same JS error with different Rust Stacktrace:

```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::option::expect_failed
   8: sql_schema_describer::postgres::SqlSchemaDescriber::get_table
   9: <sql_schema_describer::postgres::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  15: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  16: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  17: futures::future::chain::Chain<A,B,C>::poll
  18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  19: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  20: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  21: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  22: futures::task_impl::std::set
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: tokio::runtime::enter::Enter::block_on
  25: tokio::runtime::context::enter
  26: tokio::runtime::handle::Handle::enter
  27: introspection_engine::main
  28: std::rt::lang_start::{{closure}}
  29: std::rt::lang_start_internal
  30: _main

```

https://prisma-errors.netlify.app/report/8669

**Comment by divyenduz** [comment]
A related issue in migrate: https://github.com/prisma/migrate/issues/517

**Comment by janpio** [comment]
Also 2.6.2:



Command: `prisma introspect`
Version: `2.6.2`
Binary Version: `6a8054bb549e4cc23f157b0010cb2e95cb2637fb`
Report: https://prisma-errors.netlify.app/report/11195 
OS: `x64 linux 5.4.0-45-generic`

JS Stacktrace:
```
Error: [libs/sql-schema-describer/src/postgres.rs:125:44] could not get columns
    at IntrospectionEngine.<anonymous> (/home/fmif/work/udemy/graphql/graphql-clean/hello-prisma/node_modules/@prisma/cli/build/index.js:2:1828886)
    at Generator.throw (<anonymous>)
    at rejected (/home/fmif/work/udemy/graphql/graphql-clean/hello-prisma/node_modules/@prisma/cli/build/index.js:2:1825889)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Rust Stacktrace:
```
   0: user_facing_errors::Error::new_in_panic_hook
   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
   3: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437
   4: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85
   5: core::option::expect_failed
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/option.rs:1261
   6: sql_schema_describer::postgres::SqlSchemaDescriber::get_table
   7: <sql_schema_describer::postgres::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  13: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  14: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  15: futures::future::chain::Chain<A,B,C>::poll
  16: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  17: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  18: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  19: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  20: futures::task_impl::std::set
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  22: tokio::runtime::enter::Enter::block_on
  23: tokio::runtime::context::enter
  24: tokio::runtime::handle::Handle::enter
  25: introspection_engine::main
  26: std::rt::lang_start::{{closure}}
  27: std::rt::lang_start_internal::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
      std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
      std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:51
  28: main
  29: __libc_start_main
  30: <unknown>

```
