### ISSUE TITLE
AWS RDS: Adding the .pem file to sslcert doesn't work

### ISSUE THREAD

**Issue by ryands17** [prisma/prisma#3146]
## Bug description

I have a basic Prisma setup with the database URL as follows in my `.env` file:

```
DB_URL="mysql://admin:password@something.rds.amazonaws.com:3306/prisma?sslmode=require&sslcert=rds.pem"
```

The `rds.pem` file is obtained from [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html) and the file is kept in the *prisma* folder.

After deploying and hitting the endpoint, the following error is logged:

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Error occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Tls(Normal(ErrorStack([Error { code: 218529960, library: \"asn1 encoding routines\", function: \"ASN1_CHECK_TLEN\", reason: \"wrong tag\", file: \"tasn_dec.c\", line: 1220 }, Error { code: 218595386, library: \"asn1 encoding routines\", function: \"ASN1_ITEM_EX_D2I\", reason: \"nested asn1 error\", file: \"tasn_dec.c\", line: 386, data: \"Type=X509\" }])))) })",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Error occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Tls(Normal(ErrorStack([Error { code: 218529960, library: \"asn1 encoding routines\", function: \"ASN1_CHECK_TLEN\", reason: \"wrong tag\", file: \"tasn_dec.c\", line: 1220 }, Error { code: 218595386, library: \"asn1 encoding routines\", function: \"ASN1_ITEM_EX_D2I\", reason: \"nested asn1 error\", file: \"tasn_dec.c\", line: 386, data: \"Type=X509\" }])))) })",
        "stack": [
            "Error: Error occurred during query execution:",
            "ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Tls(Normal(ErrorStack([Error { code: 218529960, library: \"asn1 encoding routines\", function: \"ASN1_CHECK_TLEN\", reason: \"wrong tag\", file: \"tasn_dec.c\", line: 1220 }, Error { code: 218595386, library: \"asn1 encoding routines\", function: \"ASN1_ITEM_EX_D2I\", reason: \"nested asn1 error\", file: \"tasn_dec.c\", line: 386, data: \"Type=X509\" }])))) })",
            "    at PrismaClientFetcher._request (/var/task/node_modules/@prisma/client/runtime/index.js:1:207154)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Error occurred during query execution:",
        "ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Tls(Normal(ErrorStack([Error { code: 218529960, library: \"asn1 encoding routines\", function: \"ASN1_CHECK_TLEN\", reason: \"wrong tag\", file: \"tasn_dec.c\", line: 1220 }, Error { code: 218595386, library: \"asn1 encoding routines\", function: \"ASN1_ITEM_EX_D2I\", reason: \"nested asn1 error\", file: \"tasn_dec.c\", line: 386, data: \"Type=X509\" }])))) })",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:310:20)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```

## How to reproduce

1. Create a sample Prisma project and AWS RDS DB

2. Download the certificate bundle `.pem` from the above AWS Docs website

3. Add the file to the `sslcert` param in the connection string

4. Run the app and hit any endpoints to get the above error 

## Expected behavior

The setup should run successfully and if incrorect, shuold be documented on how to handle AWS RDS certs for an SSL connection.

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 12.18.2
- Prisma version: 2.2.2

**Comment by pantharshit00** [comment]
I wasn't able to reproduce this in latest version and the version used in this original issue is quite old as well. 

I think it is safe to close this.
