### ISSUE TITLE
Prisma & Yarn2

### ISSUE THREAD

**Issue by adarnon** [prisma/prisma#3168]
#  Bug description

I can't import `@prisma/client` using yarn2. I'm getting an ambiguous dependency error.
My app is a Next.js backend server, but I don't think that's relevant.
Looks like the problem is that the main `@prisma/client` file imports `.prisma/client` (which is my generated client), but it is not declared as a dependency. Tried some `packageExtension` hacks in `.yarnrc.yml` but couldn't get it to work.

Error message:
```
Error: @prisma/client tried to access .prisma, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: .prisma (via ".prisma/client")
Required by: @prisma/client@virtual:a83299fcd4deff07af72855eb207a7bfe60d62cd7bb2fc25e687e90d98445922cc96eb8ad550ce887958d6785d66a29c22e8989a690cc567c0750803784c6d26#npm:2.3.0 (via /Users/***/.yarn/unplugged/@prisma-client-virtual-9903ad0e60/node_modules/@prisma/client/)

Require stack:
- /Users/***/.yarn/unplugged/@prisma-client-virtual-9903ad0e60/node_modules/@prisma/client/index.js
- /Users/***/.next/server/pages/index.js
- /Users/***/.yarn/$$virtual/next-virtual-23fe31bb4b/0/cache/next-npm-9.5.0-11167af723-e011c861ac.zip/node_modules/next/dist/next-server/server/require.js
- /Users/***/.yarn/$$virtual/next-virtual-23fe31bb4b/0/cache/next-npm-9.5.0-11167af723-e011c861ac.zip/node_modules/next/dist/next-server/server/load-components.js
- /Users/***/.yarn/$$virtual/next-virtual-23fe31bb4b/0/cache/next-npm-9.5.0-11167af723-e011c861ac.zip/node_modules/next/dist/next-server/server/api-utils.js
- /Users/***/.yarn/$$virtual/next-virtual-23fe31bb4b/0/cache/next-npm-9.5.0-11167af723-e011c861ac.zip/node_modules/next/dist/next-server/server/next-server.js
- /Users/***/.yarn/$$virtual/next-virtual-23fe31bb4b/0/cache/next-npm-9.5.0-11167af723-e011c861ac.zip/node_modules/next/dist/server/next.js
- /Users/***/.yarn/$$virtual/next-virtual-23fe31bb4b/0/cache/next-npm-9.5.0-11167af723-e011c861ac.zip/node_modules/next/dist/server/lib/start-server.js
- /Users/***/.yarn/$$virtual/next-virtual-23fe31bb4b/0/cache/next-npm-9.5.0-11167af723-e011c861ac.zip/node_modules/next/dist/cli/next-dev.js
- /Users/***/.yarn/$$virtual/next-virtual-23fe31bb4b/0/cache/next-npm-9.5.0-11167af723-e011c861ac.zip/node_modules/next/dist/bin/next
    at internalTools_makeError (/Users/***/.pnp.js:21069:34)
    at resolveToUnqualified (/Users/***/.pnp.js:22002:21)
    at resolveRequest (/Users/***/.pnp.js:22088:29)
    at Object.resolveRequest (/Users/***/.pnp.js:22154:26)
    at Function.external_module_.Module._resolveFilename (/Users/***/.pnp.js:21301:34)
    at Function.external_module_.Module._load (/Users/***/.pnp.js:21165:48)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/***/.yarn/unplugged/@prisma-client-virtual-9903ad0e60/node_modules/@prisma/client/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
```

## How to reproduce

Import `@prisma/client` using yarn version 2.1.

## Expected behavior

Import should work.

## Prisma information

Prisma version 2.3.0.

## Environment & setup

- OS: MacOS
- Database: Postgres
- Node.js version: v14.6
- Prisma version:

**Comment by divyenduz** [comment]
Related: https://github.com/prisma/prisma/issues/1439
