### ISSUE TITLE
Duplicate "graphql"  error

### ISSUE THREAD

**Issue by psycura** [prisma/prisma#3235]
**Describe the bug**
receive an error on server start:
```
Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/Users/eugenealitz/training/wesbos_react/backend/node_modules/apollo-server-core/node_modules/graphql/jsutils/instanceOf.js:15:13)
    at isSchema (/Users/eugenealitz/training/wesbos_react/backend/node_modules/apollo-server-core/node_modules/graphql/type/schema.js:52:35)
    at validateSchema (/Users/eugenealitz/training/wesbos_react/backend/node_modules/apollo-server-core/node_modules/graphql/type/validate.js:55:25)
    at assertValidSchema (/Users/eugenealitz/training/wesbos_react/backend/node_modules/apollo-server-core/node_modules/graphql/type/validate.js:80:16)
    at Object.validate (/Users/eugenealitz/training/wesbos_react/backend/node_modules/apollo-server-core/node_modules/graphql/validation/validate.js:58:35)
    at doRunQuery (/Users/eugenealitz/training/wesbos_react/backend/node_modules/apollo-server-core/dist/runQuery.js:111:42)
    at /Users/eugenealitz/training/wesbos_react/backend/node_modules/apollo-server-core/dist/runQuery.js:21:56
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
`index.js`
```
require ( 'dotenv' ).config ( { path: '.env' } );
const createServer = require ( './createServer' );
const { GraphQLServer } = require ( 'graphql-yoga' );
const Mutation          = require ( './resolvers/Mutation' );
const Query             = require ( './resolvers/Query' );
const db                = require ( './db' );

const server = new GraphQLServer ( {
        typeDefs:                  'src/schema.graphql',
        resolvers:                 { Mutation, Query },
        resolverValidationOptions: {
            requireResolversForResolveType: false
        },
        context:                   req => ({ ...req, db })
    } );

server.start ( , deets => {
    console.log ( `Server is running on : http://localhost:${deets.port}` );
} )
```
`package.json`

```
{
    "name": "test-app",
    "description": "test prisma app",
    "scripts": {
        "start": "nodemon -e js,graphql -x node src/index.js",
        "debug": "nodemon -e js,graphql -x node --inspect src/index.js",
        "test": "jest",
        "playground": "graphql playground --dotenv variables.env",
        "deploy": "prisma deploy --env-file variables.env",
        "dev": "npm-run-all --parallel debug playground"
    },
    "dependencies": {
        "babel-preset-env": "^1.7.0",
        "bcryptjs": "2.4.3",
        "cookie-parser": "^1.4.3",
        "dotenv": "6.0.0",
        "global": "^4.3.2",
        "graphql": "^14.0.2",
        "graphql-yoga": "1.16.2",
        "jsonwebtoken": "8.3.0",
        "nodemailer": "^4.6.6",
        "nodemon": "1.18.4",
        "npm-run-all": "^4.1.3",
        "prisma": "^1.17.1",
        "prisma-binding": "2.1.6",
        "stripe": "^6.12.1"
    },
    "devDependencies": {
        "eslint": "^5.6.1",
        "graphql-cli": "^2.16.2",
        "jest-cli": "^23.1.0",
        "prisma-client-lib": "^1.17.1"
    },
    "license": "MIT",
    "babel": {
        "presets": [
            "env"
        ]
    }
}
```

**Versions (please complete the following information):**
 - OS: [`OS X High Sierra`] 
 - `prisma` CLI: [e.g. `prisma/1.7.1  node-v10.5.0`]

**Additional context**

**Comment by marktani** [comment]
Why do you have `"graphql": "^14.0.2"` installed manually?

**Comment by psycura** [comment]
Yes, but it also didn`t work with 0.13.2

**Comment by marktani** [comment]
I was simply curious about that explicit dependency. Why did you install it?

Can you share the output of `npm ls graphql -g` and `npm ls graphql` (the latter being run in the folder where the `node_modules` folder of your project sits).

**Comment by psycura** [comment]
I removed 'graphql` from the `package.json` ,did `rm -rf node_modules` and `yarn install` again, and everything work just fine.
Thank you, i close the issue
