### ISSUE TITLE
Can't deploy to Heroku

### ISSUE THREAD

**Issue by dodas** [prisma/prisma#3240]
**Describe the bug**
When using heroku integration, after few deploys, I suddenly can't deploy anymore:
```
ERROR: Whoops. Looks like an internal server error. Search your server logs for request ID: local:management:cjmrx6eah00be0948xy89vv25

{
  "data": {
    "deploy": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:management:cjmrx6eah00be0948xy89vv25",
      "path": [
        "deploy"
      ],
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "requestId": "local:management:cjmrx6eah00be0948xy89vv25"
    }
  ],
  "status": 200
}
```

When I run `heroku run bash -a appName`, I see following error in console:
```
SEVERE: Connection error:
org.postgresql.util.PSQLException: FATAL: permission denied for database "postgres"
  Detail: User does not have CONNECT privilege.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
        at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I am not sure if this error is related to why I can't deploy, as it doesn't appear in heroku bash while I run `prisma deploy`...
Also, queries/mutations on Prisma server work OK, I just can't deploy.

**Versions:**
 - OS: `MacOS 10.14`
 - prisma CLI: `prisma/1.17.1 (darwin-x64) node-v8.9.4`

**Comment by marktani** [comment]
Is there another Prisma server connected to the same database?
In the very beginning of the logs of your Prisma server, what does it say about the agent lock?

**Comment by dodas** [comment]
No, there shoudln't be any other servers connected. As long as Prisma integration didn't connect any.. :)
I can't currently post log about agent lock, as I already deleted and re-created my prisma service/server/db on heroku..this is only thing I could do to continue developing..

The agent lock status should be in prisma cli output, or in heroku bash? 
I guess it will happen again soon, so I will report.

**Comment by marktani** [comment]
Sounds good! Please open an issue at https://github.com/prisma/prisma-cloud-feedback if you encounter this again.
