### ISSUE TITLE
When transaction API used for update => Error: In order to use the .transaction() api, please enable 'experimentalFeatures = "transactionApi" in your schema.

### ISSUE THREAD

**Issue by tkinte** [prisma/prisma#3244]
TransactionAPI currently does not support update action.
## Bug description

The transaction API works well for create. But throws an error when tried with update action
`Error: In order to use the .transaction() api, please enable 'experimentalFeatures = "transactionApi" in your schema.
    at NewPrismaClient.transaction (C:\Program Files\EA_HOME\GraphQL\essential-node\node_modules\@prisma\client\runtime\index.js:1:202012)
    at C:\Program Files\EA_HOME\GraphQL\essential-node\src\script.js:673:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

## How to reproduce

1. schema.prisma 
` previewFeatures = ["connectOrCreate", "transactionApi", "distinct"]
  experimentalFeatures = ["transactionApi"]`
2. Create  an array of update tasks to use with transaction API
3. Run the transactional update
4. Error

`In order to use the .transaction() api, please enable 'experimentalFeatures = "transactionApi" in your schema.
    at NewPrismaClient.transaction (C:\Program Files\EA_HOME\GraphQL\essential-node\node_modules\@prisma\client\runtime\index.js:1:202012)
    at C:\Program Files\EA_HOME\GraphQL\essential-node\src\script.js:673:28
    at runMicrotasks (<anonymous>)`

## Environment & setup
- OS: windows
- Database: SQLite
- Node.js version: v14.5.0
- Prisma version:
@prisma/cli          : 2.4.1
`Current platform     : windows
Query Engine         : query-engine 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules\@prisma\cli\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules\@prisma\cli\migration-engine-windows.exe)
Introspection Engine : introspection-core 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules\@prisma\cli\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 195d4bdc2d16132977f4ba7a8ca312f7906cb086 (at node_modules\@prisma\cli\prisma-fmt-windows.exe)
Preview Features     : connectOrCreate, transactionApi, distinct`

**Comment by pantharshit00** [comment]
I am unable to reproduce this with following code and schema:
```ts
import { PrismaClient, User, UserCreateInput } from "@prisma/client";

async function main() {
  const client = new PrismaClient();
  const users: UserCreateInput[] = [
    {
      email: "pantharshit",
      name: "Harshit",
    },
    {
      email: "someone",
      name: "Bob",
    },
    {
      email: "anotherone",
      name: "ma name",
    },
  ];

  console.log("creating users");
  // create the users
  const createPromises = users.map((u) => client.user.create({ data: u }));
  const createUsers = await client.$transaction(createPromises);
  console.log("createUsers", createUsers);

  console.log("updating users");
  const updates = createUsers.map((u) =>
    client.user.update({
      where: { id: u.id },
      data: {
        name: "new name",
      },
    })
  );

  const updatedUsers = await client.$transaction(updates);
  console.log("updatedUsers", updatedUsers);

  client.disconnect();
}

main();

```
```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["connectOrCreate", "transactionApi", "distinct"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int      @default(autoincrement()) @id
  createdAt DateTime @default(now())
  title     String
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}

model Profile {
  id     Int     @default(autoincrement()) @id
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model User {
  id      Int      @default(autoincrement()) @id
  email   String   @unique
  name    String?
  posts   Post[]
  profile Profile?
}

```

It updates correctly:
![image](https://user-images.githubusercontent.com/22195362/89793808-e933cf80-db43-11ea-9cb7-3051005c683a.png)


Can you please make sure you have pasted the `previewFeatures` flag under the generator section of `generator` instead of `datasource`? I sometimes make the mistake of pasting it in the wrong place so please make sure it exist under the correct block.

**Comment by tkinte** [comment]
Hi.

Thank you for the attention.

My model is much more complex (... a lot of self referencing relations) with a large data set to update (1300000 records).

As already mentioned, the transaction api works fine for create action  with the same model and data set, 

But fails when trying to use the update action.

I will create a github project with the model and the a public data set to help reproduce the issue.

For now, here is the **schema.prisma**
`// 1
datasource db {
  provider = "sqlite"
  url      = "file:./essential-dev.db"
}

// 2
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["connectOrCreate", "transactionApi", "distinct"]
  //experimentalFeatures = ["transactionApi"]
}

// knowledge_base > simple_instance
model SimpleInstance {
  //knowledge_base > simple_instance > name
  name                String         @id
  // knowledge_base > simple_instance > own_slot_value
  own_slot_value      OwnSlotValue[]
  // knowledge_base > simple_instance > type
  type                Class?         @relation(fields: [typeName], references: [name])
  // knowledge_base > simple_instance > type
  typeName            String?
  // knowledge_base > simple_instance > supertype
  supertype           Class[]        @relation("SimpleInstanceToSupertype", references: [name])
  //knowledge_base >
  knowledgeBase       KnowledgeBase? @relation(fields: [knowledgeBaseTstamp], references: [timestamp])
  // knowledge_base > timestamp
  knowledgeBaseTstamp String?
  // knowledge_base > class|slot|simple_instance > own_slot_value > value
  // value pointing to this simple_instance
  value               Value[]
}

// knowledge_base > slot
model Slot {
  // knowledge_base > slot > name
  name                   String               @id
  // knowledge_base > slot > type
  type                   Class?               @relation(fields: [typeName], references: [name])
  // knowledge_base > slot > type
  typeName               String?
  // knowledge_base > slot > supertype
  supertype              Class[]              @relation("SlotToSupertype", references: [name])
  // knowledge_base > slot > own_slot_value
  ownSlotValue           OwnSlotValue[]
  // knowledge_base > slot > own_slot_value > slot_reference
  ownSlotValueTargetSlot OwnSlotValue[]       @relation("OwnSlotValueToTargetSlot")
  // knowledge_base > class > template_slot
  templateSlotForClass   Class[]              @relation("TemplateSlotToSlot")
  // knowledge_base > class > template_facet_value
  templateFacetValue     TemplateFacetValue[]
  // knowledge_base
  knowledgeBase          KnowledgeBase?       @relation(fields: [knowledgeBaseTstamp], references: [timestamp])
  // knowledge_base > timestamp
  knowledgeBaseTstamp    String?
  // knowledge_base > class|slot|simple_instance > own_slot_value > value
  // value pointing to this slot
  value                  Value[]
}

// knowledge_base > facet
model Facet {
  // knowledge_base > facet > name
  name                String               @id
  // knowledge_base > facet > type
  type                Class?               @relation(fields: [typeClassName], references: [name])
  typeClassName       String?
  // knowledge_base > facet > supertype
  supertype           Class[]              @relation("FacetToSupertype", references: [name])
  // knowledge_base
  knowledgeBase       KnowledgeBase?       @relation(fields: [knowledgeBaseTstamp], references: [timestamp])
  // knowledge_base > timestamp
  knowledgeBaseTstamp String? // knowledge_base > timestamp
  // knowledge_base > class > template_facet_value
  templateFacetValue  TemplateFacetValue[]
}

// knowledge_base > class > template_facet_value
model TemplateFacetValue {
  clsName_slotRef_facRef String  @id
  // knowledge_base > class > template_facet_value > slot_reference
  slot                   Slot    @relation(fields: [slotReference], references: [name])
  slotReference          String
  // knowledge_base > class > template_facet_value > facet_reference
  facet                  Facet   @relation(fields: [facetReference], references: [name])
  facetReference         String
  // knowledge_base > class > template_facet_value > value
  value                  Value[]
  // knowledge_base > class
  class                  Class   @relation(fields: [className], references: [name])
  className              String
}

// knowledge_base > class > own_slot_value
// knowledge_base > slot > own_slot_value
// knowledge_base > simple_instance > own_slot_value
model OwnSlotValue {
  ownerName_slotRef  String          @id
  // ... > own_slot_value > value
  value              Value[] //@relation(references: [type_value])
  // ... > own_slot_value > slot_reference
  targetSlot         Slot            @relation("OwnSlotValueToTargetSlot", fields: [targetSlotName], references: [name])
  targetSlotName     String
  // knowledge_base > class > own_slot_value
  class              Class?          @relation(fields: [className], references: [name])
  className          String?
  // knowledge_base > slot > own_slot_value
  slot               Slot?           @relation(fields: [slotName], references: [name])
  slotName           String?
  // knowledge_base > simple_instance > own_slot_value
  simpleInstance     SimpleInstance? @relation(fields: [simpleInstanceName], references: [name])
  simpleInstanceName String?
}

// knowledge_base > class > own_slot_value > value
// knowledge_base > class > template_facet_value > value
// knowledge_base > slot > own_slot_value > value
// knowledge_base > simple_instance > own_slot_value > value
model Value {
  type_value String @id
  @@unique([type, value])
  // ... > own_slot_value > value > CDATA
  value              String
  // ... > own_slot_value > value @value_type
  type               String
  // knowledge_base > class > template_facet_value
  templateFacetValue TemplateFacetValue[]
  // knowledge_base > class > own_slot_value > value
  // knowledge_base > slot > own_slot_value > value
  // knowledge_base > simple_instance > own_slot_value > value
  ownSlotValue       OwnSlotValue[] //@relation(references: [ownerName_slotRef])
  //@@map("ValueType")
  class              Class?               @relation(fields: [className], references: [name])
  className          String?
  slot               Slot?                @relation(fields: [slotName], references: [name])
  slotName           String?
  simpleInstance     SimpleInstance?      @relation(fields: [simpleInstanceName], references: [name])
  simpleInstanceName String?
}

// knowledge_base > class
model Class {
  // knowledge_base > class > name
  name                     String               @id // name of this class
  // knowledge_base > class > type (type of the current class)
  type                     Class?               @relation(fields: [typeName], references: [name]) // class which is the type of this class
  typeName                 String? // the name of the class which is the type this class 
  // knowledge_base > class > type ()
  //classWithThisAsType      Class[]              @relation("ClassToType") // which class has this class as the type
  // knowledge_base > class > type (inverse of : all declaring this class as class)
  //classUsedAsType          Class[]              @relation("ClassToType") // which class has this class as the type
  // knowledge_base > class > supertype
  supertype                Class[]              @relation("ClassToSupertype", references: [name]) // supertype of this class
  // knowledge_base > class > supertype (inverse of : all declaring this class as supertype)
  subtype                  Class[]              @relation("ClassToSupertype", references: [name]) // other class declaring this class as supertype
  // knowledge_base > class
  ownSlotValue             OwnSlotValue[]
  // knowledge_base > class > superclass
  superclass               Class[]              @relation("ClassToSuperclass", references: [name]) // superclass of this class
  // knowledge_base > class > superclass (inverse of : all declaring this class as superclass)
  subclass                 Class[]              @relation("ClassToSuperclass", references: [name]) // which class has this class as superclass
  // knowledge_base > class > template_slot
  templateSlot             Slot[]               @relation("TemplateSlotToSlot") // template_slot
  // knowledge_base > class > template_facet_value
  templateFacetValue       TemplateFacetValue[] // template_facet_value
  // knowledge_base > facet > type
  facetType                Facet[] // all facets with type = this class
  // knowledge_base > facet > supertype
  facetSupertypes          Facet[]              @relation("FacetToSupertype", references: [name]) // facet declaring this class as supertype  
  // knowledge_base > slot > type
  slot                     Slot[]
  // knowledge_base > slot > supertype
  slotSupertypes           Slot[]               @relation("SlotToSupertype", references: [name])
  // knowledge_base > simple_instance > type
  simpleInstance           SimpleInstance[] // all simple instances with type = this class
  // knowledge_base > simple_instance > supertype
  simpleInstanceSupertypes SimpleInstance[]     @relation("SimpleInstanceToSupertype", references: [name]) // simple_instance declaring this class as supertype
  // knowledge_base
  knowledgeBase            KnowledgeBase?       @relation(fields: [knowledgeBaseTstamp], references: [timestamp]) // Knowledge base related to
  // knowledge_base > timestamp
  knowledgeBaseTstamp      String? // knowledge_base > timestamp
  class                    Class[]              @relation("ClassToClass")
  // knowledge_base > class|slot|simple_instance > own_slot_value > value
  // value pointing to this class
  value                    Value[]
}

// knowledge_base attr:xmlns, xmlns:xsi, xsi:schemaLocation
model Schema {
  // knowledge_base attr:xmlns
  xmlns          String
  // knowledge_base attr:xmlns:xsi
  xsi            String          @id
  schemaLocation String // knowledge_base attr:xsi:schemaLocation
  // knowledge_base
  knowledgeBase  KnowledgeBase[] // knowledge_base
}

// knowledge_base
model KnowledgeBase {
  // knowledge_base attr:xmlns:xsi
  schema         Schema?          @relation(fields: [xsiReference], references: [xsi])
  // knowledge_base attr:xmlns:xsi
  xsiReference   String? // Reference to the schema identifier
  // Optional name of the knowledge base. Not defined in the ReportXML
  name           String?
  // knowledge_base > class
  class          Class[] // All class in the knowlege base
  // knowledge_base > slot
  slot           Slot[] // All slot in the knowledge base
  // knowledge_base > facet
  facet          Facet[] // All facet in the knowledge base
  // knowledge_base > simple_instance
  simpleInstance SimpleInstance[] // All simple_instance in the knowledge base
  // knowledge_base > timestamp
  timestamp      String           @id // knowledge_base > timestamp
}
`

**Comment by pantharshit00** [comment]
Thanks for the model @tkinte 

I will love to have a minimal reproduction in form of a git repo as I don't need to guess anything with that.

**Comment by tkinte** [comment]
Hi.
repo created
https://github.com/tkinte/prisma-transactional-update-debug/tree/master

**Comment by tkinte** [comment]
> Thanks for the model @tkinte
> 
> I will love to have a minimal reproduction in form of a git repo as I don't need to guess anything with that.

Hi,
 repo created
Regards
