### ISSUE TITLE
Connection URL error message shows wrong snippet when using `url` in PrismaClient constructor

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3318]
This is the error message I got:

```
yarn run v1.22.4
$ NODE_ENV=production node --max_old_space_size=8192 -r ts-node/register bench.ts
warn prisma.connect() is deprecated, please use prisma.$connect() instead
PrismaClientInitializationError: error: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `mysql://`.
  -->  schema.prisma:8
   | 
 7 |   provider = "mysql"
 8 |   url      = "mysql://root:root@localhost:3306/benchmark"
   | 

Validation Error Count: 1
    at LineStream.<anonymous> (/home/runner/work/prisma-client-js-benchmarks/prisma-client-js-benchmarks/node_modules/@prisma/engine-core/dist/NodeEngine.js:488:1)
    at LineStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at LineStream.Readable.push (_stream_readable.js:212:10)
    at LineStream.push (_stream_transform.js:152:32)
    at LineStream._pushBuffer (/home/runner/work/prisma-client-js-benchmarks/prisma-client-js-benchmarks/node_modules/@prisma/engine-core/dist/byline.js:106:1)
    at LineStream._transform (/home/runner/work/prisma-client-js-benchmarks/prisma-client-js-benchmarks/node_modules/@prisma/engine-core/dist/byline.js:98:1)
    at LineStream.Transform._read (_stream_transform.js:191:10)
    at LineStream.Transform._write (_stream_transform.js:179:12)
```

Clearly that does not make sense, as the `url` definitely does start with `mysql://`.

Turns out I was overloading that manually:

```
const DATABASE_STRING_WITHOUT_SCHEMA = `postgres://${ USER }:${ PASSWORD }@${ HOST }:${ PORT }/${ DATABASE }`
const DATABASE_STRING = `${ DATABASE_STRING_WITHOUT_SCHEMA }?schema=${ SCHEMA }`

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: DATABASE_STRING
    },
  },
  errorFormat: 'minimal'
})
```

**Comment by pantharshit00** [comment]
I can confirm this in `2.5.0-dev.62`.

Marking it as a candidate as the error message is very misleading and can cause frustration.

**Comment by pantharshit00** [comment]
This is still reproducible in 2.22

**Comment by do4gr** [comment]
This happens in the query engine. The client constructor gets a database url but the created error message references the url in the schema. (Should not show contents of schema file but reference the constructor params.)
