### ISSUE TITLE
Can't prisma deploy : User.inviteaccepted does not exist

### ISSUE THREAD

**Issue by TheYojimbo** [prisma/prisma#3336]
Hello everyone,

I'm having a huge issue right now and have absolutely no idea where to start to fix this.

So we've been trying a few things lately, including graphql-authentication, and file upload.

Authentication seems to work fine, and we moved on to file upload. We had an error saying that the size wasn't provided because it was required, so since we don't need it that much, we tried removing the "!" on the field in the datamodel. But, when we tried to deploy, we got an internal servor error :

`ERROR: Whoops. Looks like an internal server error. Search your server logs for request ID: local:management:cjneddw4d000409770pnph3r0`

So we looked up our logs on heroku, and we saw this :

`"org.postgresql.util.PSQLException: ERROR: column User.inviteaccepted does not exist\n  Hint: Perhaps you meant to reference the column \"User.inviteAccepted\"`

inviteAccepted is required for graphql-authentication, but it deployed fine the first time and works as expected. I searched our prisma api and couldn't find any mention of 'inviteaccepted ' anywhere.

I have no idea where to begin, where this might come from, and what to do. Anyone has an idea ?

I don't know how to give you an example so you can reproduce this bug, but I will answer any question or request you could have to help resolve this. I need to be able to deploy my database !

Here is the full log on heroku :

```
app[web.1]: org.postgresql.util.PSQLException: ERROR: column User.inviteaccepted does not exist
app[web.1]:   Hint: Perhaps you meant to reference the column "User.inviteAccepted".
app[web.1]:   Position: 69
app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
app[web.1]: 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
app[web.1]: 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
app[web.1]: 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
app[web.1]: 	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
app[web.1]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
app[web.1]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
app[web.1]: 	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
app[web.1]: 	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
app[web.1]: 	at slick.jdbc.Invoker.foreach(Invoker.scala:48)
app[web.1]: 	at slick.jdbc.Invoker.foreach$(Invoker.scala:47)
app[web.1]: 	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
app[web.1]: 	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
app[web.1]: 	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
app[web.1]: 	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)
app[web.1]: 	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)
app[web.1]: 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
app[web.1]: 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
app[web.1]: 	at java.lang.Thread.run(Thread.java:748)
app[web.1]: {"key":"error/unhandled","requestId":"local:management:cjnee2e7w007o09773qcyfie1","payload":{"exception":"org.postgresql.util.PSQLException: ERROR: column User.inviteaccepted does not exist
  Hint: Perhaps you meant to reference the column \"User.inviteAccepted\".
  Position: 69","query":"      mutation($name: String!, $stage: String! $types: String! $dryRun: Boolean $secrets: [String!], $subscriptions: [FunctionInput!], $force: Boolean) {
        deploy(input: {
          name: $name
          stage: $stage
          types: $types
          dryRun: $dryRun
          secrets: $secrets
          subscriptions: $subscriptions
          force: $force
        }) {
          errors {
            type
            field
            description
          }
          warnings {
            type
            field
            description
          }
          migration {
            ...MigrationFragment
          }
        }
      }
      
fragment MigrationFragment on Migration {
  revision
  steps {
    type
    __typename
    ... on CreateEnum {
      name
      ce_values: values
    }
    ... on CreateField {
      model
      name
      cf_typeName: typeName
      cf_isRequired: isRequired
      cf_isList: isList
      cf_isUnique: unique
      cf_relation: relation
      cf_defaultValue: default
      cf_enum: enum
    }
    ... on CreateModel {
      name
    }
    ... on CreateRelation {
      name
      leftModel
      rightModel
    }
    ... on DeleteEnum {
      name
    }
    ... on DeleteField {
      model
      name
    }
    ... on DeleteModel {
      name
    }
    ... on DeleteRelation {
      name
    }
    ... on UpdateEnum {
      name
      newName
      values
    }
    ... on UpdateField {
      model
      name
      newName
      typeName
      isRequired
      isList
      isUnique: unique
      relation
      default
      enum
    }
    ... on UpdateModel {
      name
      um_newName: newName
    }
  }
}

    ","variables":"{\"name\":\"citadel\",\"stage\":\"dev\",\"types\":\"type Post {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  isPublished: Boolean! @default(value: \"false\")
  title: String!
  text: String!
  author: User!
}

type User {
  id: ID! @unique
  email: String! @unique
  password: String!
  name: String!
  inviteToken: String
  inviteAccepted: Boolean! @default(value: \"true\")
  emailConfirmed: Boolean! @default(value: \"true\")
  emailConfirmToken: String
  resetToken: String
  resetExpires: DateTime
  deletedAt: DateTime
  lastLogin: DateTime
  joinedAt: DateTime! @default(value: \"2018-10-16T01:13:00.000Z\")
  isSuper: Boolean! @default(value: \"false\")
  isSparte: Boolean @default(value: \"false\")
  profileImageUrl: String
  company: String
  position: String
  avatar: File
  userGroups: [UserGroup!]! @relation(name: \"UsersGroups\", onDelete: SET_NULL)
}

type File {
  id: ID! @unique
  name: String!
  size: Int
  secret: String! @unique
  contentType: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  url: String! @unique
}

type Project {
  id: ID! @unique
  name: String!
  levelName: String
  fileName: String
  adresse: String
  archived: Boolean @default(value: \"false\")
  isAvailable: Boolean @default(value: \"false\")
  label: String
  livraison: String
  lng: String
  lat: String
  caption: String
  images: [File!]! @relation(name: \"FileOnProject\")
  userGroups: [UserGroup!]! @relation(name: \"ProjectGroups\")
  sectionDescription: [SectionDescription!]!
    @relation(name: \"DescriptionOnProject\")
}

type SectionDescription {
  id: ID! @unique
  image: File @relation(name: \"FileOnPojectDescription\")
  title: String
  content: String
  template: String
  order: Int
}

type Facade {
  id: ID! @unique
  idUnreal: String @unique
  name: String
}

type UserGroup {
  id: ID! @unique
  ref: String! @unique
  name: String @unique
  isAdmin: Boolean @default(value: \"false\")
  groupUsers: [User!]! @relation(name: \"UsersGroups\", onDelete: SET_NULL)
  entitiesCreate: [Entity!]! @relation(name: \"EntitiesCreate\")
  entitiesRead: [Entity!]! @relation(name: \"EntitiesRead\")
  entitiesUpdate: [Entity!]! @relation(name: \"EntitiesUpdate\")
  entitiesDelete: [Entity!]! @relation(name: \"EntitiesDelete\")
  childGroups: [UserGroup!]! @relation(name: \"ChildInGroup\")
  parentGroup: UserGroup @relation(name: \"ChildInGroup\")
}

type Entity {
  id: ID! @unique
  name: String @unique
  parentEntity: Entity @relation(name: \"ParentToChildrenEntity\")
  childrenEntities: [Entity!]! @relation(name: \"ParentToChildrenEntity\")
}
\
\",\"secrets\":null,\"subscriptions\":[]}","code":"0","stack_trace":"org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)\
 org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)\
 org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)\
 org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)\
 org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)\
 org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)\
 org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)\
 com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)\
 com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)\
 slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)\
 slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)\
 slick.jdbc.Invoker.foreach(Invoker.scala:48)\
 slick.jdbc.Invoker.foreach$(Invoker.scala:47)\
 slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)\
 slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)\
 slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)\
 slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)\
 slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)\
 slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)\
 slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)\
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\
 java.lang.Thread.run(Thread.java:748)","message":"ERROR: column User.inviteaccepted does not exist
  Hint: Perhaps you meant to reference the column \"User.inviteAccepted\".
  Position: 69"}}
app[web.1]: [Bugsnag - local / testing] Error report: com.bugsnag.Report@41384136
app[web.1]: org.postgresql.util.PSQLException: ERROR: column User.inviteaccepted does not exist
app[web.1]:   Hint: Perhaps you meant to reference the column "User.inviteAccepted".
app[web.1]:   Position: 69
app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
app[web.1]: 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
app[web.1]: 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
app[web.1]: 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
app[web.1]: 	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
app[web.1]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
app[web.1]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
app[web.1]: 	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
app[web.1]: 	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
app[web.1]: 	at slick.jdbc.Invoker.foreach(Invoker.scala:48)
app[web.1]: 	at slick.jdbc.Invoker.foreach$(Invoker.scala:47)
app[web.1]: 	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
app[web.1]: 	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
app[web.1]: 	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
app[web.1]: 	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)
app[web.1]: 	at slick.jdbc.SQLActionBuilder$$anon$1.run(StaticQuery.scala:98)
app[web.1]: 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
app[web.1]: 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
app[web.1]: 	at java.lang.Thread.run(Thread.java:748)
```

**Versions:**
 - OS: Windows 10
 - `prisma` CLI: prisma/1.18.1 (windows-x64) node-v8.11.3
- `prisma server` : 1.11-beta
    "graphql-authentication": "^0.5.5",
    "graphql-authentication-prisma": "^0.1.5",
    "graphql-yoga": "1.14.6",
    "prisma": "^1.18.1",
    "prisma-binding": "^2.1.0"

Please ask for anything that might help resolving this, I'll gladly provide any info !

Thanks for your time !

**Comment by marktani** [comment]
Hey @TheYojimbo, just for your understanding, this issue is solely about the Prisma server/CLI layer. Anything else is not further relevant, so we can leave that out of the picture for efficiency.

You are running into https://github.com/prisma/prisma/issues/2927, which has been fixed in `1.18.1`.
You can manually go into your management database + the actual database that contains the data to bring them back into sync.

Afterwards, I suggest to upgrade to a more recent version.

**Comment by TheYojimbo** [comment]
Hey @marktani, thanks for answering so fast as always ! We just upgraded our server to 1.18.1 and the issue disappeared ! Everything works as expected.

Thank you very much !

**Comment by marktani** [comment]
Amazement 🎉 💚
