### ISSUE TITLE
insensitiveFilters: Error occurred during query validation & transformation

### ISSUE THREAD

**Issue by bre7** [prisma/prisma#3341]
## Bug description

When running "same" query as before, with the new preview feature `insensitiveFilters` , the following error message appears:

```
Error: Failed to validate the query `Error occurred during query validation & transformation:
Query (object)
   ↳ findManySale (field)
     ↳ where (argument)
       ↳ SaleWhereInput (object)
         ↳ buyers (field)
           ↳ BuyerListRelationFilter (object)
             ↳ is (field)
               ↳ Field does not exist on enclosing type.\` at \`.Query.findManySale.where.SaleWhereInput.buyers.BuyerrListRelationFilter.is`
     at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:1:226003)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## How to reproduce

Run
```js
const result = await prisma.sale.findMany({
    where: {
      buyers: {
        some: {
          name: {
            contains: 'smith',
            mode: 'insensitive' ,
          },
        },
      },
    },
})
```

## Expected behavior

`result` should return at least one result (as it did before enabling `insensitiveFilters`)

## Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
  /// FIXME remove when stable
  previewFeatures = ["transactionApi", "insensitiveFilters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Buyer {
  id      String   @id @default(cuid())
  name    String
  sales   Sale[]  @relation("BuyersOnSale", references: [id])
}

model Sale {
  id       String              @id @default(cuid())
  date     DateTime
  buyers   Buyer[]            @relation("BuyersOnSale", references: [id])
}
```

## Environment & setup

- OS: [heroku-18](https://devcenter.heroku.com/articles/heroku-18-stack)
- Database: postgresql 12.3
- Node.js version: 14.8.0
- Prisma version: 2.5.0

**Comment by bre7** [comment]
See #3342, `insensitiveFilters` might not be the cause.

**Comment by janpio** [comment]
Closing this now under the assumption `insensitiveFilters` is not related.
