### ISSUE TITLE
JSON fields filtering stopped working in 2.5.0

### ISSUE THREAD

**Issue by MichalLytek** [prisma/prisma#3364]
## Bug description

Filtering on JSON field (equals, not) stopped working in 2.5.0.

## How to reproduce

Running this code:

```ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient({});

async function main() {
  await prisma.$connect();
  await prisma.post.deleteMany({});

  await prisma.post.create({
    data: {
      title: "Post title 1",
      metadata: {
        published: true,
      },
    },
  });
  await prisma.post.create({
    data: {
      title: "Post title 2",
      metadata: {
        published: false,
      },
    },
  });
  await prisma.post.create({
    data: {
      title: "Post title 3",
      metadata: {
        otherKey: "otherValue",
      },
    },
  });

  const allPosts = await prisma.post.findMany();
  const publishedPosts = await prisma.post.findMany({
    where: {
      metadata: {
        equals: {
          published: true,
        },
      },
    },
  });
  const notPublishedPosts = await prisma.post.findMany({
    where: {
      metadata: {
        equals: {
          published: false,
        },
      },
    },
  });
  const notEqualsPublishedPosts = await prisma.post.findMany({
    where: {
      metadata: {
        not: {
          equals: {
            published: true,
          },
        },
      },
    },
  });
  
  console.log(
    util.inspect(
      {
        allPosts,
        publishedPosts,
        notPublishedPosts,
        notEqualsPublishedPosts,
      },
      false,
      null
    )
  );
}

main()
  .catch((e) => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
```

Results in this:
```
{
  allPosts: [
    { id: 9, title: 'Post title 1', metadata: { published: true } },
    { id: 10, title: 'Post title 2', metadata: { published: false } },
    {
      id: 11,
      title: 'Post title 3',
      metadata: { otherKey: 'otherValue' }
    }
  ],
  publishedPosts: [],
  notPublishedPosts: [],
  notEqualsPublishedPosts: []
}
```

## Expected behavior

It should return properly filtered data.

## Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id       Int    @id @default(autoincrement())
  title    String
  metadata Json
}
```

## Environment & setup

- OS:  Windows 10 (WSL2 Ubuntu 20.04)
- Database:  Postgres
- Node.js version:  14
- Prisma version:
 
```
@prisma/cli          : 2.5.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 9a670138b1db276001d785a2adcba1584c869d24 (at node_modules/@prisma/cli/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.259.0
```

**Comment by pantharshit00** [comment]
I can confirm this. Initial investigation tell us that we fixed this `2.1.2` and forgot to backmerge the change to master so the fix was missing from `2.2` to `2.5` 🙈

**Comment by Jolg42** [comment]
@timsuchanek just fixed that in our latest dev build `2.6.0-dev.27`, it will be part of the official 2.6.0 release that should happen on September 1st 😃

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest dev version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@dev`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by MichalLytek** [comment]
@timsuchanek With `dev.32` it works but still there's an issue with JSON filter:

```json
{
  "name": "JsonFilter",
  "isOneOf": false,
  "fields": [
    {
      "name": "equals",
      "inputType": [
        {
          "type": "Json",
          "kind": "scalar",
          "isRequired": false,
          "isList": false,
          "isNullable": false
        }
      ]
    },
    {
      "name": "not",
      "inputType": [
        {
          "type": "Json",
          "kind": "scalar",
          "isRequired": false,
          "isList": false,
          "isNullable": false
        },
        {
          "type": "NestedJsonFilter",
          "kind": "object",
          "isRequired": false,
          "isList": false,
          "isNullable": true
        }
      ]
    }
  ]
}
```

The NestedJsonFilter is not supported:

```ts
const notEqualsPublishedPosts = await prisma.post.findMany({
  where: {
    metadata: {
      not: {
        equals: {
          published: true,
        },
      },
    },
  },
});
```

```
PrismaClientKnownRequestError: 
Invalid `prisma.post.findMany()` invocation in
/home/majkel/development/prisma-bug-2/src/index.ts:54:53

   50       },
   51     },
   52   },
   53 });
→  54 const notEqualsPublishedPosts = await prisma.post.findMany(
  Failed to validate the query `Error occurred during query validation & transformation:
Query (object)
  ↳ findManyPost (field)
    ↳ where (argument)
      ↳ PostWhereInput (object)
        ↳ metadata (field)
          ↳ JsonFilter (object)
            ↳ not (field)
              ↳ Value types mismatch. Have: String("{\"equals\":{\"published\":true}}"), want: Object((Weak))` at `.Query.findManyPost.where.PostWhereInput.metadata.JsonFilter.not`
    at PrismaClientFetcher.request (/home/majkel/development/prisma-bug-2/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1212:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at main (/home/majkel/development/prisma-bug-2/src/index.ts:54:35) {
  code: 'P2009',
  meta: {
    query_validation_error: 'Error occurred during query validation & transformation:\n' +
      'Query (object)\n' +
      '  ↳ findManyPost (field)\n' +
      '    ↳ where (argument)\n' +
      '      ↳ PostWhereInput (object)\n' +
      '        ↳ metadata (field)\n' +
      '          ↳ JsonFilter (object)\n' +
      '            ↳ not (field)\n' +
      '              ↳ Value types mismatch. Have: String("{\\"equals\\":{\\"published\\":true}}"), want: Object((Weak))',
    query_position: '.Query.findManyPost.where.PostWhereInput.metadata.JsonFilter.not'
  }
}
```

**Comment by Jolg42** [comment]
@timsuchanek ⬆️

**Comment by Jolg42** [comment]
@timsuchanek just shipped a new fix in our latest dev build `2.6.0-dev.35`, it will be part of the official 2.6.0 release that should happen on September 1st 😃 

Thanks again!

**Comment by MichalLytek** [comment]
@Jolg42 @timsuchanek Now it works correctly 🎉 

One thing left to do is to remove incorrect nested json filter:
```ts
export type JsonFilter = {
  equals?: InputJsonValue
  not?: InputJsonValue | NestedJsonFilter
}
```
It should be like that:
```ts
export type JsonFilter = {
  equals?: InputJsonValue
  not?: InputJsonValue
}
```
Because when I write such query:
```ts
 const notEqualsPublishedPosts = await prisma.post.findMany({
    where: {
      metadata: {
        not: {
          equals: {
            published: true,
          },
        },
      },
    },
  });
```
It treats the payload as the json value, not a query, so the intellisense is wrong:

![image](https://user-images.githubusercontent.com/10618781/91314713-268c9400-e7b7-11ea-92bb-840fcaca18ca.png)

**Comment by timsuchanek** [comment]
Good point @MichalLytek ! I just created a separate issue for that: https://github.com/prisma/prisma/issues/3441
