### ISSUE TITLE
Schema parser errors shouldn't be reported to error reporting

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3377]
## Problem

A lot of error reports like this https://prisma-errors.netlify.app/report/10480 are actually schema validation errors. 

## Suggested solution

They convey the error message correctly and shouldn't be reported.

**Comment by Jolg42** [comment]
Schema parsing error don't trigger the handlingPanic and looks like this now
```
Error: Error: P1012

error: Type "Intsfdf" is neither a built-in type, nor refers to another model, custom type, or enum.
  -->  schema.prisma:13
   | 
12 |   id          Int @id
13 |   viewCount20 Intsfdf
   | 


    at Object.<anonymous> (/Users/j42/Dev/prisma/src/packages/migrate/src/MigrateEngine.ts:285:24)
    at MigrateEngine.handleResponse (/Users/j42/Dev/prisma/src/packages/migrate/src/MigrateEngine.ts:145:34)
    at LineStream.<anonymous> (/Users/j42/Dev/prisma/src/packages/migrate/src/MigrateEngine.ts:233:16)
    at LineStream.emit (events.js:223:5)
    at LineStream.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at LineStream.Readable.push (_stream_readable.js:224:10)
    at LineStream.Transform.push (_stream_transform.js:150:32)
    at LineStream._pushBuffer (/Users/j42/Dev/prisma/src/packages/migrate/src/utils/byline.ts:118:17)
```
