### ISSUE TITLE
batch update is not working

### ISSUE THREAD

**Issue by agrakhov** [prisma/prisma#3432]
**Describe the bug**
Trying to perform batch update operation from examples but seeing error. Seems like passed param is incorrect?

**To Reproduce**
Using following model:
```
type User {
  id: ID! @unique
  name: String!
  address: String
}
```
create multiple instances of users and try to execute following code: 
```javascript
const res = prisma.updateManyUsers({
    where: {
      id_not_in: [
        'cjli6tknz005s0a23uf0lmlve',
        'cjli6tnkj005x0a2325ynfpb9',
        'cjli6tq3200620a23s4lp8npd'
      ]
    },
    data: {
      address: 'random address'
    }
  });
  console.log(await res.count()); // error (see below) 
  console.log(await res.count); // this prints 'function () { [native code] }'
```
 Error reported: 
```
(node:27944) UnhandledPromiseRejectionWarning: Error: Variable '$data' of type 'UserUpdateInput!' used in position expecting type 'UserUpdateManyMutationInput!'. (line 1, column 35):
mutation ($where: UserWhereInput, $data: UserUpdateInput!) {
                                  ^
 (line 2, column 40):
  updateManyUsers(where: $where, data: $data) {
                                       ^
    at BatchedGraphQLClient.<anonymous> (/xxx/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:77:35)
    at step (/xxx/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/xxx/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/xxx/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

```

**Versions (please complete the following information):**
 - OS: Ubuntu 16.04 
 - versions
		"babel-cli": "^6.26.0",
		"babel-preset-env": "^1.7.0",
		"body-parser": "^1.18.3",
		"express": "^4.16.4",
		"graphql": "^0.13.2",
		"prisma-client-lib": "^1.19.3"

**Comment by do4gr** [comment]
Thanks for reporting this. In this case the client schema is out of sync with the schema of the prisma server. We'll release a fix for the client soon. The mutation you provided should work once the client generates the correct types.

**Comment by qirex** [comment]
Having the same issue after updating from 0.19.x to 1.20.1.
Is there any workaround or a fix in a beta release?

**Comment by qirex** [comment]
Version: 1.20.7
  "graphql": "^0.13.2",
  "graphql-yoga": "^1.16.7",
  "prisma-client-lib": "^1.20.7",
  "prisma": "^1.20.7",

The Error is gone but update many still returns 0 updated nodes for me using prisma client.
Update many on service directly works fine.

**Comment by timsuchanek** [comment]
Thanks for reporting! @qirex: Can you please post your datamodel and client call that you're using? You can also send it to me in a pm in slack @tim2.
Thanks a lot!

**Comment by qirex** [comment]
Nevermind was my mistake. Initially connected some ids wrong which of course led to 0 updates.
Works all fine now.
Thanks for responding!

**Comment by Elfayer** [comment]
### Error
I'm opening this issue back again, I'm having the same issue:
```
(node:19968) UnhandledPromiseRejectionWarning: Error: Variable '$data' expected value of type 'LoanUpdateManyMutationInput!' but got: {"isCanceled":true,"items":{"update":{"data":{"isReturned":true}}}}. Reason: 'items' Field 'items' is not defined in the input type 'LoanUpdateManyMutationInput'. (line 1, column 35):
mutation ($where: LoanWhereInput, $data: LoanUpdateManyMutationInput!) {
                                  ^
    at BatchedGraphQLClient.<anonymous> (C:\Users\rvanrent080817\Documents\Projects\LOAN-BackEnd\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:77:35)
    at step (C:\Users\rvanrent080817\Documents\Projects\LOAN-BackEnd\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:40:23)
    at Object.next (C:\Users\rvanrent080817\Documents\Projects\LOAN-BackEnd\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:21:53)
    at fulfilled (C:\Users\rvanrent080817\Documents\Projects\LOAN-BackEnd\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
### Mutation
```graphql
await prisma.updateManyLoans({
  where: { id_in: ids },
  data: {
    isCanceled: true,
    items: {
      update: {
        data: {
          isReturned: true
        }
      }
    }
  }
})
```

### Schema
```graphql
type Loan {
  id: ID! @unique
  items: [LoanItem!]! @relation(name: "LoanItems", onDelete: CASCADE)
  isCanceled: Boolean! @default(value: "false")
  // [...]
}

type LoanItem {
  id: ID! @unique
  isReturned: Boolean! @default(value: "false")
  // [...]
}
```

### Generated `index.d.ts`
Note I do not get the relation `items` from `Loan` to `LoanItem`, I only get scalar types. Is that new? I had the correct typings under version 1.19, although batching didn't work.
```ts
updateManyLoans: (
  args: { data: LoanUpdateManyMutationInput; where?: LoanWhereInput }
) => BatchPayloadPromise;

export interface LoanUpdateManyMutationInput {
  isCanceled?: Boolean;
  // [...]
}
```

### Versions
- OS: Windows 10
- Prisma CLI: `prisma/1.24.0 (windows-x64) node-v8.11.2`
- `docker ps`: `prismagraphql/prisma:1.24`
```
"prisma": "^1.24.0",
"prisma-client-lib": "^1.24.0",
"graphql": "^0.13.2",
"graphql-cli": "^2.16.5",
```
