### ISSUE TITLE
Cannot read type of undefined on `prisma generate`

### ISSUE THREAD

**Issue by cdebotton** [prisma/prisma#3466]
I'm running into an interesting issue where when I add a new type with an `id` field to my `datamodel.graphql`, I will get an error `▸    Cannot read property 'type' of undefined`. when running `prisma generate` with any target. I have other types defined with IDs, I can remove any of them and add them back and run the command as expected, but if I define any new types, no matter the name, generate will fail if an ID is present.

Schema
```graphql
enum Role {
  ADMIN
  EDITOR
  USER
  VIEWER
  UNAUTHORIZED
}

type User {
  id: ID! @unique
  email: String! @unique
  password: String!
  lastLogin: DateTime
  createdAt: DateTime!
  updatedAt: DateTime!
  role: Role! @default(value: USER)
  profile: Profile! @relation(name: "UserProfile", onDelete: CASCADE)
  documents: [Document!]! @relation(name: "UserDocuments", onDelete: SET_NULL)
}

type Profile {
  id: ID! @unique
  firstName: String
  lastName: String
  dateOfBirth: DateTime
  createdAt: DateTime!
  updatedAt: DateTime!
  user: User! @relation(name: "UserProfile")
  avatar: File @relation(name: "Avatar")
}

type Document {
  id: ID! @unique
  publishDate: DateTime!
  title: String!
  author: User! @relation(name: "UserDocuments")
  createdAt: DateTime!
  updatedAt: DateTime!
}

type File {
  id: ID! @unique
  mimetype: String!
  encoding: String!
  key: String!
  etag: String!
  bucket: String!
  size: Int!
  url: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Block {
  id: ID! @unique
}
````

Error output
```bash
➜  cmyk git:(master) ✗ npx prisma --version
prisma/1.20.1 (darwin-x64) node-v10.13.0
➜  cmyk git:(master) ✗ DEBUG="*" prisma generate
zsh: command not found: prisma
➜  cmyk git:(master) ✗ DEBUG="*" npx prisma generate
  config CWD /Users/cdebotton/Projects/cmyk +0ms
  config HOME /Users/cdebotton +2ms
  config definitionDir /Users/cdebotton/Projects/cmyk/db +2ms
  config definitionPath /Users/cdebotton/Projects/cmyk/db/prisma.yml +0ms
  cli { isGlobal: false } +0ms
  StatusChecker setting status checker +0ms
  cli command id generate +4ms
  cli:plugincache Got plugin from cache +0ms
  cli:plugincache /Users/cdebotton/Library/Caches/prisma/plugins.json +0ms
  cli:plugincache Got plugin from cache +1ms
  cli:plugincache /Users/cdebotton/Library/Caches/prisma/plugins.json +0ms
  plugins findCommand prisma-cli-core +0ms
  plugin requiring command +0ms
  cli-engine:plugins:manager requiring /Users/cdebotton/Projects/cmyk/node_modules/prisma-cli-core +0ms
  cli-engine:plugins:manager required +1s
  plugin required command +1s
  StatusChecker setting status checker +1s

Generating schema... 38ms
TypeError: Cannot read property 'type' of undefined
    at TypescriptGenerator.renderFieldType (/Users/cdebotton/Projects/cmyk/node_modules/prisma-client-lib/src/codegen/typescript-client.ts:561:13)
    at TypescriptGenerator.renderInputFieldTypeHelper (/Users/cdebotton/Projects/cmyk/node_modules/prisma-client-lib/src/codegen/typescript-client.ts:413:17)
    at TypescriptGenerator.renderArgs (/Users/cdebotton/Projects/cmyk/node_modules/prisma-client-lib/src/codegen/typescript-client.ts:385:53)
    at /Users/cdebotton/Projects/cmyk/node_modules/prisma-client-lib/src/codegen/typescript-client.ts:436:44
    at Array.map (<anonymous>)
    at TypescriptGenerator.renderMainMethodFields (/Users/cdebotton/Projects/cmyk/node_modules/prisma-client-lib/src/codegen/typescript-client.ts:434:8)
    at TypescriptGenerator.renderMutations (/Users/cdebotton/Projects/cmyk/node_modules/prisma-client-lib/src/codegen/typescript-client.ts:292:17)
    at TypescriptGenerator.render (/Users/cdebotton/Projects/cmyk/node_modules/prisma-client-lib/src/codegen/typescript-client.ts:200:8)
    at GenereateCommand.<anonymous> (/Users/cdebotton/Projects/cmyk/node_modules/prisma-cli-core/src/commands/generate/generate.ts:150:28)
    at step (/Users/cdebotton/Projects/cmyk/node_modules/prisma-cli-core/dist/commands/generate/generate.js:42:23)
    at Object.next (/Users/cdebotton/Projects/cmyk/node_modules/prisma-cli-core/dist/commands/generate/generate.js:23:53)
    at /Users/cdebotton/Projects/cmyk/node_modules/prisma-cli-core/dist/commands/generate/generate.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/cdebotton/Projects/cmyk/node_modules/prisma-cli-core/dist/commands/generate/generate.js:13:12)
    at GenereateCommand.generateTypescript (/Users/cdebotton/Projects/cmyk/node_modules/prisma-cli-core/dist/commands/generate/generate.js:183:16)
    at GenereateCommand.<anonymous> (/Users/cdebotton/Projects/cmyk/node_modules/prisma-cli-core/src/commands/generate/generate.ts:100:22)
    at step (/Users/cdebotton/Projects/cmyk/node_modules/prisma-cli-core/dist/commands/generate/generate.js:42:23)
    at Object.next (/Users/cdebotton/Projects/cmyk/node_modules/prisma-cli-core/dist/commands/generate/generate.js:23:53)
    at fulfilled (/Users/cdebotton/Projects/cmyk/node_modules/prisma-cli-core/dist/commands/generate/generate.js:14:58)
raven@2.6.4 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting
Exiting with code: 1
```

**Versions (please complete the following information):**
 - OS: MacOS Mojave
 - `prisma` CLI: `prisma/1.20.1 (darwin-x64) node-v10.13.0`]

**Comment by lastmjs** [comment]
Hey @cdebotton I think I'm running into this same issue. Did you find a solution?

**Comment by bmgalego** [comment]
Got the same issue seems to happen when having a type with only the fields managed by prisma: id, updatedAt, createdAt. Adding another field removed the issue.

@cdebotton I think the problem in your schema is the type Block

@lastmjs maybe this helps

**Comment by Mbotes** [comment]
I'm running into a similar issue specifically around "zsh: command not found: prisma", I have installed prisma globally through yarn as well as npm and when I just try run prisma, I get the error above.
