### ISSUE TITLE
Better error message: Query interpretation error. Error for binding '0': AssertionError(\"Required exactly one parent ID to be present for connect query, found 0.\"

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3489]
_Originally posted by @Albert-Gao in https://github.com/prisma/prisma/issues/3488#issuecomment-684826417_

my current use case is:

When use nexus framework + prisma combo, when I have an error from the backend api

```json
{
  "errors": [
    {
      "message": "\nInvalid `ctx.db.user.update()` invocation in\n/Users/AlbertGao/codes/teamingCloud/monorepo/packages/nexus/api/graphql/entities/test.ts:9:28\n\n   5 definition(t) {\n   6   t.field('testPrisma', {\n   7     type: 'User',\n   8     resolve: (_, __, ctx) => {\n→  9       return ctx.db.user.update(\n  Query interpretation error. Error for binding '0': AssertionError(\"Required exactly one parent ID to be present for connect query, found 0.\")",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "testPrisma"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "P2016",
          "meta": {
            "details": "Error for binding '0': AssertionError(\"Required exactly one parent ID to be present for connect query, found 0.\")"
          },
          "stacktrace": [
            "Error: ",
            "\u001b[31mInvalid \u001b[1m`ctx.db.user.update()`\u001b[22m invocation in\u001b[39m",
            "\u001b[31m\u001b[4m/Users/AlbertGao/codes/teamingCloud/monorepo/packages/nexus/api/graphql/entities/test.ts:9:28\u001b[24m\u001b[39m",
            "",
            "\u001b[2m  \u001b[90m 5 \u001b[39mdefinition(t) {\u001b[22m",
            "\u001b[2m  \u001b[90m 6 \u001b[39m  t.field('testPrisma', {\u001b[22m",
            "\u001b[2m  \u001b[90m 7 \u001b[39m    type: 'User',\u001b[22m",
            "\u001b[2m  \u001b[90m 8 \u001b[39m    resolve: (_, __, ctx) => {\u001b[22m",
            "\u001b[31m\u001b[1m→\u001b[22m\u001b[39m \u001b[2m\u001b[90m 9 \u001b[39m      return ctx.db.user.update(\u001b[22m",
            "  Query interpretation error. Error for binding '0': AssertionError(\"Required exactly one parent ID to be present for connect query, found 0.\")",
            "    at PrismaClientFetcher.request (/Users/AlbertGao/codes/teamingCloud/monorepo/packages/nexus/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1212:15)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "testPrisma": null
  }
}
```

Is there any way I can do to identify what kind of error is this without matching hardcode string from the error message?

Isn't something like ErrorCode enum or a const object make it easier? Or I am miss something here.

Thanks :)

**Comment by Albert-Gao** [comment]
Thanks for moving, I thought it's duplicated 😂

information that needed:

- error code : PascalCase words but not number plz
- error message
- call to action
- callstack
- source code 
- doc url

The current one already includes a lot but not all.

Furthermore, might be better if we just separate each of them into a separate property in an error object.

**Comment by janpio** [comment]
This is most probably greatly improved by not. If not, please open a new issue and provide a full reproduction on how to get the problematic error message. Thank you for opening an issue back in the day AlbertGao!
