### ISSUE TITLE
Support `NaN`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3492]
## Problem

Some databases support a `NaN` value for floating point types like `numeric`, `real` and double precision` in PostgreSQL for example:

> In addition to ordinary numeric values, the numeric type allows the special value NaN, meaning "not-a-number". Any operation on NaN yields another NaN. When writing this value as a constant in an SQL command, you must put quotes around it, for example UPDATE table SET x = 'NaN'. On input, the string NaN is recognized in a case-insensitive manner.
>
> > Note: In most implementations of the "not-a-number" concept, NaN is not considered equal to any other numeric value (including NaN). In order to allow numeric values to be sorted and used in tree-based indexes, PostgreSQL treats NaN values as equal, and greater than all non-NaN values.

> In addition to ordinary numeric values, the floating-point types have several special values:
> 
> - Infinity
> - -Infinity
> - NaN
>
> These represent the IEEE 754 special values "infinity", "negative infinity", and "not-a-number", respectively. (On a machine whose floating-point arithmetic does not follow IEEE 754, these values will probably not work as expected.) When writing these values as constants in an SQL command, you must put quotes around them, for example UPDATE table SET x = 'Infinity'. On input, these strings are recognized in a case-insensitive manner.
Note: IEEE754 specifies that NaN should not compare equal to any other floating-point value (including NaN). In order to allow floating-point values to be sorted and used in tree-based indexes, PostgreSQL treats NaN values as equal, and greater than all non-NaN values.

https://www.postgresql.org/docs/9.1/datatype-numeric.html

Currently Prisma does not support that type at all, which leads to errors like https://github.com/prisma/prisma-client-js/issues/797

## Suggested solution

We could investigate the details of `NaN` and possibly implement support for it in Prisma.

## Alternatives

None really, as the missing support also causes raw queries to fail (see https://github.com/prisma/prisma-client-js/issues/797)

**Comment by pimeys** [comment]
We could do an enum variant, replacing `Value::Real` in the system, that's either `Decimal | NaN`, them implementing `PartialEq` to sort `NaN` higher than any other value, and so that `NaN == NaN`.

**Comment by pimeys** [comment]
This reflects the hacks PostgreSQL does to allow indexing and sorting with them.

**Comment by pimeys** [comment]
Microsoft SQL Server seemed to stop supporting `NaN` values in version 2005.

**Comment by janpio** [comment]
@DekzVt and @hayes, who originally reported this bug: What is your use case behind using this value? Would you have other workarounds if Prisma does not support this functionality?

**Comment by hayes** [comment]
For my use case, we have ~30 existing tables with many columns the occasionally contain NaNs.  The NaNs are not particularly meaningful.  We are no longer writing NaNs, but we still need to be able to query those rows.  Our current work around is to use a separate (non prosma) client when query columns that might have NaNs, which obviously is not sustainable.  An alternative on our end might be to use a raw query that returns NaNs as nulls (haven't thought through the details, but seems like it should be doable).  

I think of Prisma had an option to convert NaNs to nulls that would be sufficient for our use case, since we do not sort/filter on those columns (currently).  For us we just need to be able to return the rows that have NaNs, even if we just get them back as nulls instead.  Having a way to query for NaNs might be nice so we could use prosma to update those rows values might be nice, but not important for our current use cases.

**Comment by janpio** [comment]
> An alternative on our end might be to use a raw query that returns NaNs as nulls (haven't thought through the details, but seems like it should be doable).

We will confirm this and report back, and update the issues above if this is a doable workaround for reading tables with `NaN` values. Thanks for this idea!

**Comment by janpio** [comment]
This indeed works @hayes: Check the updated "Alternatives" section in https://github.com/prisma/prisma/issues/3492 Thanks again for the idea!

**Comment by DekzVt** [comment]
> For my use case, we have ~30 existing tables with many columns the occasionally contain NaNs. The NaNs are not particularly meaningful. We are no longer writing NaNs, but we still need to be able to query those rows. Our current work around is to use a separate (non prisma) client when query columns that might have NaNs, which obviously is not sustainable. An alternative on our end might be to use a raw query that returns NaNs as nulls (haven't thought through the details, but seems like it should be doable).
> 
> I think of Prisma had an option to convert NaNs to nulls that would be sufficient for our use case, since we do not sort/filter on those columns (currently). For us we just need to be able to return the rows that have NaNs, even if we just get them back as nulls instead. Having a way to query for NaNs might be nice so we could use prisma to update those rows/values, but not important for our current use cases.

same here. converting NaNs to null would be sufficient for our case as well. Thanks for all the hard work on this!

**Comment by DekzVt** [comment]
@janpio The workaround for reading: 

```
const nanData = await prisma.$queryRaw(
   `SELECT id, NULLIF(num, 'NaN') From "WithNan"`,
)
console.log({ nanData })
```
This is only viable for querying tables directly. Unfortunately our NaNful tables are used heavily as related tables. I assume there is no workaround at this time if the NaNs occur in related tables.

How difficult would it be to get NaNs converted to Null throughout the prisma client?

**Comment by janpio** [comment]
> This is only viable for querying tables directly. Unfortunately our NaNful tables are used heavily as related tables. I assume there is no workaround at this time if the NaNs occur in related tables.

Can you explain a bit more what exactly you mean with "related tables"? What would a query for those look like?

> How difficult would it be to get NaNs converted to Null throughout the prisma client?

It would probably be the simpler solution of many possible. Still we need to make sure this is explicit in some way - unexpectedly returning adapted data from a database could lead to nasty errors and misunderstandings so we need to really understand the problem here.

**Comment by DekzVt** [comment]
> Can you explain a bit more what exactly you mean with "related tables"? What would a query for those look like?

So we're using `prisma.user.findOne({ where: { id: ctx.userId } })` and that is failing because of a table called `Stats`.

The relation between these is declared in schema.prisma: 
``` stats                          Stats[]          @relation(name: "userTostats")```

The `findOne` to user is failing because of the NaN col in the Stats table, no? I may be misunderstanding how it is working (someone else in my org has been working with prisma mostly, I may pull them into this convo)

**Comment by janpio** [comment]
Uh, usually that table should only be included in the query if you explicitly ask for data from that table.
Best would be if you could open a bug issue with some information about the error, your schema, your query and so on so we can reproduce it and understand what really is going on. Definitely worth to look into.

**Comment by DekzVt** [comment]
> Uh, usually that table should only be included in the query if you explicitly ask for data from that table.

Talking to the other dev. I think we have eager loading of `stats` when querying for `user`. I'll have to get some more color on exactly how the failing query is setup and get back to you, but I'd assume that eager loading wouldn't be possible with the rawQuery workaround.

**Comment by DekzVt** [comment]
@janpio I now get where the magic was happening. We are using prisma with nexus and in our objectType definition for user, it was calling `t.model.stats()` (essentially `user.stats()`) to query for the related stats models.

I replaced this function call with a list field where the resolver uses `queryRaw`. This solved our issue for the query in question.

For those looking to replace 'NaN' and 'Infinity': 
```
const nanData = await prisma.$queryRaw(
   `SELECT id,
          CASE
              WHEN "WithNan"."num" = 'NaN' THEN NULL
              WHEN "WithNan"."num" = 'Infinity' THEN NULL
              ELSE "WithNan"."mining_income"
          END AS "num" FROM "WithNan"`,
)
console.log({ nanData })
```

We have a large legacy database with a lot of tables with floats, and we really need to avoid these unrecoverable panics. The workaround is _OK_ but I'm afraid it's not leaving us with many of the benefits of Prisma, given that we are going to have to write all our pagination SQL from scratch.

We would really appreciate some option passed to `FindMany`, `FindOne` and the related table functions (`.stats()` in our case) that would add this `CASE ... END AS` SQL for all float columns.

**Comment by DekzVt** [comment]
Also, not sure if I should make a separate issue for this, but large floats that psql stores in scientific notation seem to cause the same error as 'NaN' and 'Infinity'.

However when I switched to `queryRaw` these values were returned from the query successfully.

You should be able to recreate this issue with psql by setting a float8 column to a value like `12300000000000000000000` and then trying to query for that row with prisma's `FindMany`.

Using a typed `queryRaw` call to get the same data we are able to successfully return this value in our nexus graphql query. Without `queryRaw` we get the same "f64 is not a Decimal" error as with 'NaN' and 'Infinity'.

**Comment by janpio** [comment]
> Also, not sure if I should make a separate issue for this, [...]

Definitely. Thanks!

**Comment by tgeorgiadis** [comment]
Just ran into this problem with a PostgresSQL field that has the **timestamp with time zone** type. Any record with Infinity or -Infinity for the timestamp returns the following error 

```
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: FromSql(25), cause: Some("value too large to decode") }) })
    at PrismaClientFetcher.request (/home/tom/IdeaProjects/nextjs-neutron-app/node_modules/@prisma/client/runtime/index.js:78467:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async __webpack_exports__.default (webpack-internal:///./pages/api/securities/index.ts:25:18)
    at async apiResolver (/home/tom/IdeaProjects/nextjs-neutron-app/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async DevServer.handleApiRequest (/home/tom/IdeaProjects/nextjs-neutron-app/node_modules/next/dist/next-server/server/next-server.js:64:462)
    at async Object.fn (/home/tom/IdeaProjects/nextjs-neutron-app/node_modules/next/dist/next-server/server/next-server.js:56:492)
    at async Router.execute (/home/tom/IdeaProjects/nextjs-neutron-app/node_modules/next/dist/next-server/server/router.js:23:67)
    at async DevServer.run (/home/tom/IdeaProjects/nextjs-neutron-app/node_modules/next/dist/next-server/server/next-server.js:66:1042)
    at async DevServer.handleRequest (/home/tom/IdeaProjects/nextjs-neutron-app/node_modules/next/dist/next-server/server/next-server.js:34:1081) {
  clientVersion: '2.16.0'
```

**Comment by janpio** [comment]
That sounds like a new problem, although slightly related, so you might want to create a new issue for this.

**Comment by iamtheworstdev** [comment]
I just hit this issue when trying to do a database seed for a table that uses [postgresql periods](https://github.com/xocolatl/periods), which is basically the same timestamp issue @tgeorgiadis is hitting I believe.

**Comment by danielimmke** [comment]
Can confirm this is still an issue - If you have a timestamp that defaults to `-Infinity` as an arbitrary non null value, Prisma has issues creating new records with it.

**Comment by Schoonology** [comment]
Also running into this, and disappointed to find that Prisma is making this harder than expected. Both Postgres and JavaScript are using IEEE 754 double precision in this case, so this is Prisma artificially getting in the way of storing the number from JavaScript.

Any chance we can get a first-party solution for telling Prisma Client to _not_ do this, and to pass `number`s through unadulterated?

If you want a use case, we're ingesting data from a Python-based data science team, and would like to take their data without changing it. Infinity, -Infinity, and NaN are _meaningful_ values in this case, independent of any other canary value (e.g. 0, -1). And because the column itself is an array, it needs a data type like `Float[]`. As far as I can tell, there is no first-party solution to this problem. Am I understanding correctly?

**Comment by matisiekpl** [comment]
Any updates here?
