### ISSUE TITLE
Getting TypeError: Cannot read property 'selectionSet' of undefined

### ISSUE THREAD

**Issue by chanlito** [prisma/prisma#3509]
All my resolver started throwing this error after upgrading to prisma@1.20.3

Works fine on prisma@1.20.1

**Expected behavior**
This error shouldn't happen.

**Screenshots**
<img width="706" alt="screen shot 2018-11-14 at 11 44 19 am" src="https://user-images.githubusercontent.com/15667259/48460699-d53e2b00-e802-11e8-84f1-98056eac2e00.png">

According to the error there's something wrong with prisma-client-lib for this version 1.20.3

**Versions (please complete the following information):**
 - OS:  MacOS latest
 - `prisma` CLI: `prisma/1.20.3 (darwin-x64) node 8 lts`]
 - `graphql-cli`, `prisma-client`, `graphql-yoga`

**Comment by divyenduz** [comment]
@chanlito : If possible, can you also please share a minimal reproduction github project?

**Comment by tadejstanic** [comment]
I can confirm the same problem with the:

- `prisma CLI 1.20.5`
- `prisma-client-lib@1.20.5`
- `prisma server 1.20.5`

The repo for reproducing the bug can be found here - https://github.com/tadejstanic/prisma-nestjs 

It's a [NestJS](https://github.com/nestjs/nest) project which uses prisma client. So NestJS is just a wrapper around the prisma client therefore I'm sure NestJS has nothing to do with the bug. 

The error bubbles up when you execute a query with a related model (**courses**). For instance:

```
query getAllUsers {
  getAllUsers{
    id name courses {
    	title
    }
  }
}
```
On the other hand, this query works just fine:
```
query getAllUsers {
  getAllUsers{
    id name 
  }
}
```
With prisma@1.20.1 this bug was not presented.

**Comment by qirex** [comment]
Also having this issue after updating to 1.20.5.

Error stack:
`TypeError: Cannot read property 'selectionSet' of undefined
at C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\src\Client.ts:316:14
at Array.reduceRight (<anonymous>)
at Client.generateSelections (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\src\Client.ts:231:30)
at Client.<anonymous> (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\src\Client.ts:138:32)
at step (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\dist\Client.js:47:23)
at Object.next (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\dist\Client.js:28:53)
at C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\dist\Client.js:22:71
at new Promise (<anonymous>)
at __awaiter (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\dist\Client.js:18:12)
at Client.processInstructions (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\src\Client.ts:134:42)`

**Comment by chanlito** [comment]
So i updated my application, everything to **1.20.5** (prisma-cli, prisma-client, prisma-server) and here are the result:

1. 
<img width="967" alt="screen shot 2018-11-14 at 9 28 05 pm" src="https://user-images.githubusercontent.com/15667259/48488793-3510f200-e854-11e8-909e-b466825f8567.png">
I get **Cannot read property 'selectionSet' of undefined**

2.
<img width="831" alt="screen shot 2018-11-14 at 9 30 04 pm" src="https://user-images.githubusercontent.com/15667259/48488945-7b665100-e854-11e8-8f86-305419702749.png">
I get **Invalid AST Node: {}**

3.
<img width="830" alt="screen shot 2018-11-14 at 9 31 36 pm" src="https://user-images.githubusercontent.com/15667259/48489043-b10b3a00-e854-11e8-9996-4e43325e9456.png">
Seems to run fine.

And I ran those queries again on version **1.20.1** again, they all ran fine without errors.

**Comment by qirex** [comment]
Stack for invalid AST Node:

`Query:
Error: Invalid AST Node: {}
    at visit (C:\dev\cba-prisma-yoga\node_modules\graphql\language\visitor.js:245:15)
    at Object.print (C:\dev\cba-prisma-yoga\node_modules\graphql\language\printer.js:22:29)
    at Client.<anonymous> (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\src\Client.ts:145:21)
    at step (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\dist\Client.js:47:23)
    at Object.next (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\dist\Client.js:28:53)
    at C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\dist\Client.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\dist\Client.js:18:12)
    at Client.processInstructions (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\src\Client.ts:134:42)
    at Client.processInstructionsOnce (C:\dev\cba-prisma-yoga\node_modules\prisma-client-lib\src\Client.ts:128:33)`

**Comment by thsnyzkn** [comment]
Hello,
Unfortunately I am having the same problem, even I am just trying to learn Prisma by using the tutorial of the official documentation.
I got the error while I am trying the Step 6 (Query relational data)
https://www.prisma.io/docs/1.20/get-started/02-change-data-model-JAVASCRIPT-c001/

**Comment by iamandyk** [comment]
Getting this issue too

**Comment by i8ramin** [comment]
Also seeing this error with relations

**Comment by cdebotton** [comment]
Also seeing this problem unfortunately on 1.20.6

**Comment by ammezie** [comment]
Getting same error with **v1.20.6**, which wasn't present in **v1.20.0**.

**Comment by iamandyk** [comment]
Thanks @timsuchanek ! Working now for me.

**Comment by alexedev** [comment]
@timsuchanek Thank you for the quick fix! Works for me too.

**Comment by ducdev** [comment]
I'm on `1.20.7` and it's not fixed.
```prisma/1.20.7 (darwin-x64) node-v8.12.0```
I was trying to run ```console.log(await prisma.user({ email }).$fragment(`fragment UserId on User { id }`));```
![image](https://user-images.githubusercontent.com/3524016/48563200-5cd08a80-e926-11e8-8484-f977cf4d098b.png)

**Comment by lterfloth** [comment]
@timsuchanek how shall I go about updating? I have this issue #3508 which made me downgrade to 1.20.5. I tested the 1.21.0 and the issue wasn't resolved there. Now I'm not sure whether updating fixes both issues for me
