### ISSUE TITLE
Warn about syntax error in datasource url (with env var) earlier

### ISSUE THREAD

**Issue by madebysid** [prisma/prisma#3509]
## Bug description

This is an invalid `datasource` declaration:

```
datasource pg {
  provider = "postgresql"
  url          = env(DB_URL)
}
```

since `DB_URL` needs to be inside double quotes (`url          = env("DB_URL")`).

When I run `prisma generate`, no errors are thrown, but when I run a query, this is what I see:
```
PrismaClientInitializationError:
Invalid `prisma.with_all_field_types.update()` invocation in
/Users/siddhant/Code/Tests/cypress/index.ts:48:37

  44 //     },
  45 //   });
  46 // }
  47
→ 48 await prisma.with_all_field_types.update(
  error: Expected a String value, but received literal value "DB_URL".
  -->  schema.prisma:8
   |
 7 |   // url      = "postgresql://siddhant@localhost:5432/cypress?schema=public"
 8 |   url      = env(DB_URL)
   |

Validation Error Count: 1
    at PrismaClientFetcher.message (/Users/siddhant/Code/Tests/cypress/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1184:51)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Moreover, I see the same error when I run `prisma migrate save --experimental`.

## Expected behavior

1. Red squiggly lines in the VSCode extension
2. Error during `prisma generate`

## Prisma information

```
@prisma/cli          : 2.6.0
Current platform     : darwin
Query Engine         : query-engine 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 650b5d0348ec38ae61e1e7db69bb54808418ede4 (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.272.0
```

+

VSCode Extension: Prisma Insider v7.0.2

**Comment by pantharshit00** [comment]
Opened https://github.com/prisma/language-tools/issues/448 so that wee can track this for vscode

**Comment by mavilein** [comment]
This might be tricky to do as we intentionally ignore errors in the url argument within `generate`.
