### ISSUE TITLE
Error: [libs/datamodel/core/src/dml/model.rs:166:14] We assume an internally valid datamodel before mutating. 

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3516]
Command: `prisma introspect`
Version: `2.6.0`
Binary Version: `650b5d0348ec38ae61e1e7db69bb54808418ede4`
Report: https://prisma-errors.netlify.app/report/11025 
OS: `x64 darwin 19.5.0`

JS Stacktrace:
```
Error: [libs/datamodel/core/src/dml/model.rs:166:14] We assume an internally valid datamodel before mutating.
    at IntrospectionEngine.<anonymous> (/Users/.../projects/.../.../node_modules/@prisma/cli/build/index.js:2:1828886)
    at Generator.throw (<anonymous>)
    at rejected (/Users/.../projects/.../.../node_modules/@prisma/cli/build/index.js:2:1825889)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::option::expect_failed
   8: datamodel::dml::datamodel::Datamodel::find_relation_field_mut
   9: sql_introspection_connector::re_introspection::enrich
  10: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  16: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  17: futures::future::chain::Chain<A,B,C>::poll
  18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  19: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  20: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  21: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  22: futures::task_impl::std::set
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: tokio::runtime::enter::Enter::block_on
  25: tokio::runtime::context::enter
  26: tokio::runtime::handle::Handle::enter
  27: introspection_engine::main
  28: std::rt::lang_start::{{closure}}
  29: std::rt::lang_start_internal
  30: _main

```

**Comment by janpio** [comment]
Command: `prisma introspect`
Version: `2.6.1`
Binary Version: `6a8054bb549e4cc23f157b0010cb2e95cb2637fb`
Report: https://prisma-errors.netlify.app/report/11051 
OS: `x64 linux 4.15.0-115-generic`

JS Stacktrace:
```
Error: [libs/datamodel/core/src/dml/model.rs:166:14] We assume an internally valid datamodel before mutating.
    at IntrospectionEngine.<anonymous> (/home/.../Documents/.../...-api/node_modules/@prisma/cli/build/index.js:2:1828886)
    at Generator.throw (<anonymous>)
    at rejected (/home/.../Documents/../...-api/node_modules/@prisma/cli/build/index.js:2:1825889)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Rust Stacktrace:
```
   0: user_facing_errors::Error::new_in_panic_hook
   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
   3: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437
   4: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85
   5: core::option::expect_failed
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/option.rs:1261
   6: datamodel::dml::datamodel::Datamodel::find_relation_field_mut
   7: sql_introspection_connector::re_introspection::enrich
   8: sql_introspection_connector::calculate_datamodel::calculate_datamodel
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  12: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  13: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  14: futures::future::chain::Chain<A,B,C>::poll
  15: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  16: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  17: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  18: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  19: futures::task_impl::std::set
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: tokio::runtime::enter::Enter::block_on
  22: tokio::runtime::context::enter
  23: tokio::runtime::handle::Handle::enter
  24: introspection_engine::main
  25: std::rt::lang_start::{{closure}}
  26: std::rt::lang_start_internal::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
      std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
      std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:51
  27: main
  28: __libc_start_main
  29: <unknown>

```

**Comment by do4gr** [comment]
This is the same issue including a reproduction
https://github.com/prisma/prisma/issues/3507
