### ISSUE TITLE
Using $disconnect causes error: TypeError: Cannot read property 'signalCode' of undefined

### ISSUE THREAD

**Issue by mikecao** [prisma/prisma#3522]
## Bug description
When using `prisma.$disconnect` the following error occurs:

```
TypeError: Cannot read property 'signalCode' of undefined
    at NodeEngine.handleRequestError (/home/mike/test/nextjs-prisma/node_modules/@prisma/client/runtime/index.js:1:111338)
    at /home/mike/test/nextjs-prisma/node_modules/@prisma/client/runtime/index.js:1:126916
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PrismaClientFetcher.request (/home/mike/test/nextjs-prisma/node_modules/@prisma/client/runtime/index.js:1:227796)
    at async Promise.all (index 4)
    at async module.exports../pages/api/hello.js.__webpack_exports__.default (/home/mike/test/nextjs-prisma/.next/server/pages/api/hello.js:138:18)
    at async apiResolver (/home/mike/test/nextjs-prisma/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async DevServer.handleApiRequest (/home/mike/test/nextjs-prisma/node_modules/next/dist/next-server/server/next-server.js:47:397)
    at async Object.fn (/home/mike/test/nextjs-prisma/node_modules/next/dist/next-server/server/next-server.js:39:218)
```

This generally happens when multiple queries are run at once. I created a demo below that runs 10 queries at once.

## How to reproduce

I created an example repo here https://github.com/mikecao/nextjs-prisma
It's a barebones Next.js application with Prisma.io.

1. Run the project
```
npm install
npm run generate
npm run dev
```
2. On the home page, click the `Run test` button. This will make a call to the API at `/api/hello` defined by `/pages/api/hello.js`.
3. Running the test will cause the error.
4. If you comment out the disconnect method, there will be no error.

## Expected behavior

No error should be thrown when using disconnect.

## Prisma information

I used an example prisma schema just so I could generate the client. None of the models are actually used. The test query is simply `SELECT NOW()` run 10 times.

## Environment & setup

- OS: Ubuntu, Windows 
- Database: PostgreSQL 
- Node.js version: 14.8 
- Prisma version: 2.6.1

```

```

**Comment by alf5** [comment]
I am getting similar error.
Reverting to version 2.6.1 fixed it for me

**Comment by pantharshit00** [comment]
Thanks @mikecao for the report, I can reproduce this. 

Initially I wasn't able to reproduce this but then I was able to reproduce this by introducing some load.

I can reproduced by going to `/api/hello` and holding Cmd + R.
![image](https://user-images.githubusercontent.com/22195362/92499624-b8fe5000-f219-11ea-9d5d-676d9aa13b7d.png)


This is also reproduce in `2.7.0-dev.33` version as well so there is a bug in cleanup logic.

**Comment by SharadKumar** [comment]
Okay, I wasn't getting this until I did the following

Previous (without error)
- In my nextjs API (Vercel hosted), I had `import { PrismaClient } from '@prisma/client'`
- `const prisma = new PrismaClient()`
- In try/finally, I do `prisma.$disconnect`.

Now (with error)
- In API, `import prisma from '../prisma'` (from my `./prisma/index.ts`)
- Index.ts has the following:

```ts
import { PrismaClient } from "@prisma/client"
export * from "@prisma/client"

let prisma: PrismaClient

if (process.env.NODE_ENV === "production") {
  prisma = new PrismaClient()
} else {
  // Ensure the prisma instance is re-used during hot-reloading
  // Otherwise, a new client will be created on every reload
  global["prisma"] = global["prisma"] || new PrismaClient()
  prisma = global["prisma"]
}

export default prisma
```
After this, I started getting the error frequently now.

**Comment by williamluke4** [comment]
This seems to be the underlying issue
# Description
```
signalCode: undefined | exitCode: undefined | killed: undefined
SocketError: other side closed
    at Socket.Xu (/home/will/Prisma/Repoductions/nextjs-prisma/node_modules/@prisma/client/runtime/index.js:58:6693)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Exit code: undefined
Started http server
```

## Logs
```
  prisma-client  +0ms
  prisma-client Prisma Client call: +0ms
  prisma-client prisma.queryRaw(select now()) +0ms
  prisma-client Prisma Client call: +0ms
  prisma-client prisma.queryRaw({
  prisma-client   query: 'select now()',
  prisma-client   parameters: undefined
  prisma-client }) +0ms
  prisma-client Generated request: +0ms
  prisma-client mutation {
  prisma-client   queryRaw(query: "select now()")
  prisma-client }
  prisma-client  +0ms
  engine { cwd: '/home/will/Prisma/Repoductions/nextjs-prisma/prisma' } +25ms
  engine {
  engine   dotPrismaPath: '/home/will/Prisma/Repoductions/nextjs-prisma/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x'
  engine } +0ms
  plusX Execution permissions of /home/will/Prisma/Repoductions/nextjs-prisma/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine +27ms
  engine { flags: [ '--enable-raw-queries' ] } +1ms
  engine port: 38965 +0ms
  engine stdout {
  timestamp: 'Sep 22 11:15:17.070',
  level: 'INFO',
  target: 'quaint::pooled',
  fields: { message: 'Starting a postgresql pool with 9 connections.' }
} +14ms
  engine stdout {
  timestamp: 'Sep 22 11:15:17.073',
  level: 'INFO',
  target: 'query_engine::server',
  fields: { message: 'Started http server' }
} +3ms
  engine {
  engine   dotPrismaPath: '/home/will/Prisma/Repoductions/nextjs-prisma/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x'
  engine } +3ms
  plusX Execution permissions of /home/will/Prisma/Repoductions/nextjs-prisma/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine +20ms
  engine Client Version local +11ms
  engine Engine Version query-engine b2ba0251835a0fb068871fe65272136853245dd3 +0ms
  engine Stopping Prisma engine4 +41ms
  engine Waiting for start promise +0ms
  engine Done waiting for start promise +0ms
  engine {
  engine   error: pu [SocketError]: other side closed
  engine       at Socket.Xu (/home/will/Prisma/Repoductions/nextjs-prisma/node_modules/@prisma/client/runtime/index.js:58:6693)
  engine       at Socket.emit (events.js:327:22)
  engine       at endReadableNT (_stream_readable.js:1220:12)
  engine       at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  engine     code: 'UND_ERR_SOCKET'
  engine   }
  engine } +5ms
  engine Started http server
  engine 
  engine This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
```
