### ISSUE TITLE
java.lang.ClassCastException: com.prisma.api.mutations.NoReturnValue cannot be cast to com.prisma.api.mutations.ReturnValue

### ISSUE THREAD

**Issue by tomitrescak** [prisma/prisma#3559]
**Describe the bug**

When using in high load scenario and during unit tests with live database Prisma is throwing cryptic error when inserting a new field into database:

```
java.lang.ClassCastException: com.prisma.api.mutations.NoReturnValue cannot be cast to com.prisma.api.mutations.ReturnValue
	at com.prisma.api.mutations.Create.$anonfun$getReturnValue$3(Create.scala:53)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
{"key":"error/unhandled","requestId":"local:api:cjophypj70f580a77vjzk267y","clientId":"test@default","payload":{"exception":"java.lang.ClassCastException: com.prisma.api.mutations.NoReturnValue cannot be cast to com.prisma.api.mutations.ReturnValue","query":"mutation ($_v0_data: BpmnTaskInstanceCreateInput!) {\n  createBpmnTaskInstance(data: $_v0_data) {\n    id\n    dateFinished\n    dateStarted\n    duration\n    performerId\n    processInstanceId\n    data\n    status\n    taskId\n  }\n}\n","variables":"{\"_v0_data\":{\"dateStarted\":\"2018-11-20T08:48:41.126Z\",\"processInstanceId\":\"cjophyph60f540a77dwyigb19\",\"data\":\"{}\",\"status\":\"Started\",\"taskId\":\"Task_17t05yl\"}}","code":"0","stack_trace":"com.prisma.api.mutations.Create.$anonfun$getReturnValue$3(Create.scala:53)\\n scala.util.Success.$anonfun$map$1(Try.scala:251)\\n scala.util.Success.map(Try.scala:209)\\n scala.concurrent.Future.$anonfun$map$1(Future.scala:287)\\n scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)\\n scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)\\n java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\\n java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)\\n java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)\\n java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)\\n java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\\n java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)","message":"com.prisma.api.mutations.NoReturnValue cannot be cast to com.prisma.api.mutations.ReturnValue"}}
```

Would you have any idea when this error originates?

**To Reproduce**

I'm unable to reproduce, as this error happens on every 2-3rd run, just randomly.

**Expected behavior**
A clear and concise description of what you expected to happen. It happens when I am inserting data to database ;(

**Versions (please complete the following information):**
 - OS: OS X Mojave
 - `prisma` CLI: prisma/1.20.7 (darwin-x64) node-v10.9.0

**Comment by do4gr** [comment]
Hey @tomitrescak, 

could you test this with the latest Prisma version again? If this is still present I could take a look what might be causing this.

**Comment by pantharshit00** [comment]
@tomitrescak 

I am going to close this now. Feel free to open a new issue if you still facing this 🙂
