### ISSUE TITLE
prisma -v causes prisma Error: Could not find schema.prisma

### ISSUE THREAD

**Issue by FinnFrotscher** [prisma/prisma#3596]
on request of: https://github.com/prisma/migrate/issues/586#issuecomment-691066465

```
yarn prisma:version                                                                ...kages/backend-api
yarn run v1.22.4
$ prisma --version
  prisma Environment variables not loaded +0ms
@prisma/cli          : 2.6.2
Current platform     : darwin
Query Engine         : query-engine 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 6a8054bb549e4cc23f157b0010cb2e95cb2637fb (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.272.0
  prisma Error: Could not find schema.prisma
  prisma     at Object.<anonymous> (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:2830614)
  prisma     at Generator.next (<anonymous>)
  prisma     at fulfilled (/Users/finnfrotscher/code/cofenster/monorepo/packages/backend-api/node_modules/@prisma/cli/build/index.js:2:2827918)
  prisma     at processTicksAndRejections (internal/process/task_queues.js:97:5) +1s
✨  Done in 1
```

**Comment by janpio** [comment]
Can you reproduce this in a new project?

These are the required steps:
```
mkdir foo
cd foo
npm init -y
npm install @prisma/cli
npx prisma --version
```

If this does not give the same error message, it might be something with your project.

**Comment by FinnFrotscher** [comment]
they dont lead to the same issue

**Comment by janpio** [comment]
`prisma:version` is just `prisma --version`?
Any other idea what could be going on here?

**Comment by FinnFrotscher** [comment]
Yes it it

**Comment by pantharshit00** [comment]
@FinnFrotscher I am also unable to reproduce this and looks like you have closed https://github.com/prisma/migrate/issues/586. 

Do you have new information here which can provide a concrete reproduction?

**Comment by FinnFrotscher** [comment]
cant reproduce anymore. seems resolved
