### ISSUE TITLE
[Introspection] Error: [libs\sql-schema-describer\src\mysql.rs:351:34] non_unique 

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3609]
Command: `prisma introspect`
Version: `2.6.2`
Binary Version: `6a8054bb549e4cc23f157b0010cb2e95cb2637fb`
Report: https://prisma-errors.netlify.app/report/11189 
OS: `x64 win32 10.0.19042`

JS Stacktrace:
```
Error: [libs\sql-schema-describer\src\mysql.rs:351:34] non_unique
    at IntrospectionEngine.<anonymous> (C:\temp\...\...\node_modules\@prisma\cli\build\index.js:2:1828886)
    at Generator.throw (<anonymous>)
    at rejected (C:\temp\...\...\node_modules\@prisma\cli\build\index.js:2:1825889)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Rust Stacktrace:
```
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: BaseThreadInitThunk
  33: RtlUserThreadStart

```

**Comment by tomhoule** [comment]
I think this is fixed.
