### ISSUE TITLE
[Introspection] Error: [/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/0849b56/src/connector/postgres/error.rs:104:31] index out of bounds: the len is 1 but the index is 1 

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#3610]
Command: `prisma introspect`
Version: `2.6.0`
Binary Version: `650b5d0348ec38ae61e1e7db69bb54808418ede4`
Report: https://prisma-errors.netlify.app/report/11190 
OS: `x64 linux 5.4.0-47-generic`

JS Stacktrace:
```
Error: [/root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/0849b56/src/connector/postgres/error.rs:104:31] index out of bounds: the len is 1 but the index is 1
    at IntrospectionEngine.<anonymous> (/home/janusz/.../.../node_modules/@prisma/cli/build/index.js:2:1828886)
    at Generator.throw (<anonymous>)
    at rejected (/home/janusz/.../.../node_modules/@prisma/cli/build/index.js:2:1825889)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Rust Stacktrace:
```
   0: user_facing_errors::Error::new_in_panic_hook
   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:530
   3: rust_begin_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:437
   4: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:85
   5: core::panicking::panic_bounds_check
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/panicking.rs:62
   6: quaint::connector::postgres::error::<impl core::convert::From<tokio_postgres::error::Error> for quaint::error::Error>::from
   7: quaint::single::Quaint::new::{{closure}}
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  13: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  14: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  15: futures::future::chain::Chain<A,B,C>::poll
  16: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  17: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  18: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  19: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  20: futures::task_impl::std::set
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  22: tokio::runtime::enter::Enter::block_on
  23: tokio::runtime::context::enter
  24: tokio::runtime::handle::Handle::enter
  25: introspection_engine::main
  26: std::rt::lang_start::{{closure}}
  27: std::rt::lang_start_internal::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:52
      std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
      std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
      std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:51
  28: main
  29: __libc_start_main
  30: <unknown>

```

**Comment by janpio** [comment]
Last reported in 2.13.x
