### ISSUE TITLE
Variable expressions in .env not expanding in generated client

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#3657]
## Bug description

Given the following .env file:

```
DATABASE_NAME="prisma_env"
SCHEMA="public"
DATABASE_URL="postgresql://m@localhost:5432/${DATABASE_NAME}?schema=${SCHEMA}"
```

When I try generating and running the client with `ts-node src/index.js`, I get:

```
PrismaClientKnownRequestError: 
Invalid `client.user.create()` invocation in
/Users/m/Go/src/github.com/prisma/env/src/index.ts:6:21

  2 const client = new PrismaClient()
  3 
  4 async function run() {
  5   await client.$connect()
→ 6   await client.user.create(
  Database `$%7BDATABASE_NAME%7D.${SCHEMA}` does not exist on the database server at `localhost:5432`.
    at PrismaClientFetcher.request (/Users/m/Go/src/github.com/prisma/env/node_modules/@prisma/client/src/runtime/getPrismaClient.ts:1212:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P1003',
  meta: {
    database_name: '$%7BDATABASE_NAME%7D',
    database_schema_name: '${SCHEMA}',
    database_host: 'localhost',
    database_port: 5432
```

It works if I change it to the following, then re-generate, then run:

```
DATABASE_URL="postgresql://m@localhost:5432/prisma_env?schema=public"
```

Interestingly, migrate and generate seem to work properly. It's just when you try to run the generated client, you get this error.

## Prisma information

**schema.prisma**

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id Int @id
}
```

**src/index.ts**

```ts
import { PrismaClient } from '@prisma/client'
const client = new PrismaClient()

async function run() {
  await client.$connect()
  await client.user.create({
    data: {
      id: 10,
    },
  })
}

async function main() {
  try {
    await run()
  } catch (err) {
    console.error(err)
  } finally {
    await client.$disconnect()
  }
}

main()
```

## Environment & setup

```
Environment variables loaded from current directory
@prisma/cli          : 2.7.0-dev.79
Current platform     : darwin
Query Engine         : query-engine eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.287.0
```

**Comment by matthewmueller** [comment]
This was due to the client being out of date.
