### ISSUE TITLE
Custom Generator Output Breaks Client

### ISSUE THREAD

**Issue by williamluke4** [prisma/prisma#3671]
## Bug description
Adding a custom output breaks the prisma client
```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../generated/client"
}
```
## How to reproduce

1. `git clone git@github.com:prisma/prisma-examples.git --depth=1`
2. Switch branch to `Custom-Client-Generator-Output-Error`
3. `cd typescript/script`
4. `yarn`
4. `yarn dev`
5. Expect an Error
```
❯ yarn dev                                                                                                                                                                                 (base) 
yarn run v1.22.5
$ ts-node ./script.ts
Ap [Error]: 
Invalid `prisma.user.create()` invocation in
/home/will/Prisma/prisma-examples/typescript/script/script.ts:8:35


  Unique constraint failed on the fields: (`email`)
    at iy.request (/home/will/Prisma/prisma-examples/typescript/script/generated/client/runtime/src/runtime/getPrismaClient.ts:1181:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2002',
  meta: { target: [ 'email' ] }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Jolg42** [comment]
Unique constraint failed mean you already have an email with the same value in the database.

**Comment by williamluke4** [comment]
Haha thanks @Jolg42 . Was trying to reproduce an error when the output is manually set, which only seems to occur when using NextJS. Thought I had reproduced it in a repo without NextJS but  :see_no_evil:
