### ISSUE TITLE
List types with union input types are not supported

### ISSUE THREAD

**Issue by darioielardi** [prisma/prisma#3691]
## Bug description

I'm submitting this as a bug report since I can't find anything in the docs about this limitation, I apologize in case I'm missing something. 

I got this in my `schema.prisma`:

```
enum UserRole {
  ADMIN
  // ...
}

model User {
  roles UserRole[]
  // ...
}
```

Since this syntax is allowed and prisma client is correctly generated I expected I could query my `User` table on the `roles` column with the following syntax:

```prisma
import { UserRole } from '@prisma/client';

const users = await prisma.user.findMany({
  where: {
    roles: [UserRole.ADMIN],
  },
});
```

But if try to do so I get the following error:

```typescript
List types with union input types are not supported
```

## Expected behavior

Since the Prisma schema parser allows the enum list syntax and the client is correctly generated I would expect this to work, or at least a note in the docs.

## Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v12.13.1
- Prisma version:
```
@prisma/cli          : 2.7.0
Current platform     : darwin
Query Engine         : query-engine eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt eaade828a21d8ee3f4940f0af7da3ae0922db4df (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.287.0
Preview Features     : insensitiveFilters
```

Anyway, congratulations and thank you for the amazing work with this project.

**Comment by calummoore** [comment]
I'm running into the same error (List types with union input types are not supported) with the following model and query:

```
model Account {
  id         String          @default(dbgenerated()) @id
  scopes     String[]
}
```

```js
await prisma.account.findMany({
  where: { scopes: ['abc'] },
}),
```

I tried upgrading to 2.8-dev.55 (and 2.8-dev.36), but I get the following error when generating types (`prisma generate`).

```
Error:
TypeError: Cannot read property '0' of undefined
    at DMMFClass.resolveInputTypes (/Users/calummoore/snapboard/code/packages/api/node_modules/@prisma/client/generator-build/index.js:9943:39)
    at new DMMFClass (/Users/calummoore/snapboard/code/packages/api/node_modules/@prisma/client/generator-build/index.js:9922:10)
    at new TSClient (/Users/calummoore/snapboard/code/packages/api/node_modules/@prisma/client/generator-build/index.js:10321:17)
    at buildClient (/Users/calummoore/snapboard/code/packages/api/node_modules/@prisma/client/generator-build/index.js:11411:18)
    at generateClient (/Users/calummoore/snapboard/code/packages/api/node_modules/@prisma/client/generator-build/index.js:11466:45)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

And the following runtime error (although given I wasn't able to run `prisma generate` because of the above error, it's probably related to that.

```
/Users/calummoore/snapboard/code/packages/api/node_modules/@prisma/client/runtime/src/runtime/dmmf.ts:74
        const first = field.inputTypes[0].type
                            ^
TypeError: Cannot read property '0' of undefined
    at mr.resolveInputTypes (/Users/calummoore/snapboard/code/packages/api/node_modules/@prisma/client/runtime/src/runtime/dmmf.ts:74:29)
    at new mr (/Users/calummoore/snapboard/code/packages/api/node_modules/@prisma/client/runtime/src/runtime/dmmf.ts:35:10)
    at new t (/Users/calummoore/snapboard/code/packages/api/node_modules/@prisma/client/runtime/src/runtime/getPrismaClient.ts:310:20)
    at Object.<anonymous> (/Users/calummoore/snapboard/code/packages/api/src/db/prisma.ts:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at babelWatchLoader (/Users/calummoore/snapboard/code/node_modules/babel-watch/runner.js:51:13)
    at Object.require.extensions.<computed> [as .ts] (/Users/calummoore/snapboard/code/node_modules/babel-watch/runner.js:62:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
```

**Comment by pantharshit00** [comment]
@calummoore I am still unable to reproduce this. I used `2.8.0-dev.57`. I also tried the versions that you mentioned and they also work fine.

Can you please make sure you running the cli with the correct version? We are going to release `2.8` today so you can also wait for that release as well.

**Comment by calummoore** [comment]
Sorry, yes - I hadn't upgraded the client. That's now working - thanks!

Just need to wait for #3475 now, as exact equals on an array of strings is not very useful.

**Comment by calummoore** [comment]
Hey @pantharshit00 why the downvote?

**Comment by pantharshit00** [comment]
It was a misclick, oops. Fixed it ;)

**Comment by darioielardi** [comment]
This now works as expected, looking forward to array filtering now!
