### ISSUE TITLE
Error for foreign key violation is very undescriptive

### ISSUE THREAD

**Issue by Akxe** [prisma/prisma#3701]
## Descriotion
I have an old database. There are foreign key violations. Since basically all tables are interconnected, I cannot load any table from the studio. I would like to use a studio or some other tool to fix the database.

## Problem
```
Error in Prisma Client request: 

Error: Failed to validate the query `Error occurred during query validation & transformation:
Query (object)
  ↳ findManyadresy (field)
    ↳ take (argument)
      ↳ Argument does not exist on enclosing type.` at `.Query.findManyadresy.take`
    at PrismaClientFetcher.request (C:\Users\akxe\AppData\Roaming\Prisma\Studio\-Users-akxe-Documents-Programming-rita\runtime\index.js:1:228283)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\akxe\Documents\Programming\rita\node_modules\@prisma\cli\build\index.js:2:1616391
    at async Photon.request (C:\Users\akxe\Documents\Programming\rita\node_modules\@prisma\cli\build\index.js:2:1616874)
    at async PhotonService.respond (C:\Users\akxe\Documents\Programming\rita\node_modules\@prisma\cli\build\index.js:2:868721)
    at async WebSocket.StudioServer.onWSMessage (C:\Users\akxe\Documents\Programming\rita\node_modules\@prisma\cli\build\index.js:2:774591)
```
This error is not very much helpful. It does not provide anything to go reason about.

## Suggested solution
How about an error:
```
Error in Prisma Client request:

Error: Failed to validate the query `Row for column "fieldName" of table "tableName" was not present for value(s): 1,2,3,4,5,6... and X more.`
```

## Alternatives
You pick one, there will be many

## Additional context
Prisma 2.6.0, applies to 2.7.0, the same (waiting for `nexus-plugin-prisma` to upgrade)

**Comment by janpio** [comment]
We need a minimal reproduction here @pantharshit00 of the error message that you get when you have 2 models with a relation, and the data has an invalid foreign key value. If it matches the one given above, this becomes an issue to improve that error message. If not, we will need to figure out what really is going on.

**Comment by Akxe** [comment]
> Thanks! And your theory for an explanation is that `Adresy` contains an invalid foreign key in `idFirmy` that is backing the relation in that table, correct?

Well... I know for sure, that none of "Adresy" is invalid in "Firmy", but I am almost 100% confident, the others do have invalid foreign keys

**Comment by janpio** [comment]
That (un)fortunately invalidates the initial theory.

Can you try to execute the query Studio is sending manually in your script/app?

```
prisma.adresy.findMany({
  take: 100,
  skip: 0,
  select: {
    idAdr: true,
    idFirmy: true,
    aOdd: true,
    aUlice: true,
    aMesto: true,
    aPSC: true,
    aStat: true,
    aPozn: true,
    firmy_adresy_idFirmyTofirmy: true,
    dokumenty: true,
    firmy_adresyTofirmy_idFirAdr: true,
    firmy_adresyTofirmy_idKorespAdr: true,
    firmy_adresyTofirmy_idLepicAdr: true,
  }
})
```

For reference, this is the relevant model from the schema:

```
model adresy {
  idAdr                           Int         @default(autoincrement()) @id
  idFirmy                         Int
  aOdd                            String?
  aUlice                          String?
  aMesto                          String?
  aPSC                            String?
  aStat                           String?
  aPozn                           String?
  firmy_adresy_idFirmyTofirmy     firmy       @relation("adresy_idFirmyTofirmy", fields: [idFirmy], references: [idFirmy])
  dokumenty                       dokumenty[]
  firmy_adresyTofirmy_idFirAdr    firmy[]     @relation("adresyTofirmy_idFirAdr")
  firmy_adresyTofirmy_idKorespAdr firmy[]     @relation("adresyTofirmy_idKorespAdr")
  firmy_adresyTofirmy_idLepicAdr  firmy[]     @relation("adresyTofirmy_idLepicAdr")

  @@index([idFirmy], name: "key_idx")
}

model firmy {
  idFirmy                             Int         @id
  FFirma                              String
  FNazev                              String?
  ICO                                 String?
  DIC                                 String?
  Splatnost                           Int?        @default(14)
  Frekvence                           Int?        @default(dbgenerated())
  fTel                                String?
  fFax                                String?
  fPozn                               String?
  fSoud                               String?
  idPrimKontakt                       Int?
  idZastoupena                        Int?
  idLepic                             Int?
  idFirAdr                            Int?
  idKorespAdr                         Int?
  idLepicAdr                          Int?
  idkDir                              Int?
  fKlient                             Int         @default(0)
  fDodav                              Int         @default(0)
  fRSdod                              Int         @default(0)
  fAktivni                            Int         @default(1)
  Cinnost                             String?
  Region                              String?
  fKat                                firmy_fKat?
  adresy_adresyTofirmy_idFirAdr       adresy?     @relation("adresyTofirmy_idFirAdr", fields: [idFirAdr], references: [idAdr])
  adresy_adresyTofirmy_idKorespAdr    adresy?     @relation("adresyTofirmy_idKorespAdr", fields: [idKorespAdr], references: [idAdr])
  adresy_adresyTofirmy_idLepicAdr     adresy?     @relation("adresyTofirmy_idLepicAdr", fields: [idLepicAdr], references: [idAdr])
  dir                                 dir?        @relation(fields: [idkDir], references: [idDir])
  adresy_adresy_idFirmyTofirmy        adresy[]    @relation("adresy_idFirmyTofirmy")
  auditnos                            auditnos[]
  dokumenty_dokumenty_dokFirmaTofirmy dokumenty[] @relation("dokumenty_dokFirmaTofirmy")
  dokumenty_dokumenty_idFirmyTofirmy  dokumenty[] @relation("dokumenty_idFirmyTofirmy")
  dokumenty_dokumenty_idKlientTofirmy dokumenty[] @relation("dokumenty_idKlientTofirmy")
  jmena                               jmena[]
  korporace                           korporace[]
  korposoby                           korposoby[]
  loga                                loga[]
  nadobdobi                           nadobdobi[]
  carrier                             Carrier[]
  prodejny                            prodejny[]
  rsnosice                            rsnosice[]
  svoobdobi_firmyTosvoobdobi_idAgent  svoobdobi[] @relation("firmyTosvoobdobi_idAgent")
  svoobdobi_firmyTosvoobdobi_idKlient svoobdobi[] @relation("firmyTosvoobdobi_idKlient")
  undozakp                            undozakp[]
  zakazky                             zakazky[]
  zakazkyp                            zakazkyp[]
  zakpkorp                            zakpkorp[]

  @@index([idKorespAdr], name: "firma_adr_idx")
  @@index([idFirAdr], name: "firma_adr_idx1")
  @@index([idkDir], name: "firma_dir_idx")
  @@index([idLepicAdr], name: "firma_lepard_idx")
}
```

**Comment by Akxe** [comment]
This is an interesting way of debugging...

Here it is:
```
prisma:query SELECT `rex3`.`adresy`.`idAdr`, `rex3`.`adresy`.`idFirmy`, `rex3`.`adresy`.`aOdd`, `rex3`.`adresy`.`aUlice`, `rex3`.`adresy`.`aMesto`, `rex3`.`adresy`.`aPSC`, `rex3`.`adresy`.`aStat`, `rex3`.`adresy`.`aPozn` FROM `rex3`.`adresy` WHERE 1=1 ORDER BY `rex3`.`adresy`.`idAdr` ASC LIMIT ? OFFSET ?
prisma:query SELECT `rex3`.`firmy`.`idFirmy`, `rex3`.`firmy`.`FFirma`, `rex3`.`firmy`.`FNazev`, `rex3`.`firmy`.`ICO`, `rex3`.`firmy`.`DIC`, `rex3`.`firmy`.`Splatnost`, `rex3`.`firmy`.`Frekvence`, `rex3`.`firmy`.`fTel`, `rex3`.`firmy`.`fFax`, `rex3`.`firmy`.`fPozn`, `rex3`.`firmy`.`fSoud`, `rex3`.`firmy`.`idPrimKontakt`, `rex3`.`firmy`.`idZastoupena`, `rex3`.`firmy`.`idLepic`, `rex3`.`firmy`.`idFirAdr`, `rex3`.`firmy`.`idKorespAdr`, `rex3`.`firmy`.`idLepicAdr`, `rex3`.`firmy`.`idkDir`, `rex3`.`firmy`.`fKlient`, `rex3`.`firmy`.`fDodav`, `rex3`.`firmy`.`fRSdod`, `rex3`.`firmy`.`fAktivni`, `rex3`.`firmy`.`Cinnost`, `rex3`.`firmy`.`Region`, `rex3`.`firmy`.`fKat` FROM `rex3`.`firmy` WHERE `rex3`.`firmy`.`idFirmy` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
prisma:query SELECT `rex3`.`dokumenty`.`idDok`, `rex3`.`dokumenty`.`dokTyp`, `rex3`.`dokumenty`.`dokDruh`, `rex3`.`dokumenty`.`dokFirma`, `rex3`.`dokumenty`.`dokFakt`, `rex3`.`dokumenty`.`dokCislo`, `rex3`.`dokumenty`.`dokKCislo`, `rex3`.`dokumenty`.`dokNazev`, `rex3`.`dokumenty`.`idDir`, `rex3`.`dokumenty`.`idFirmy`, `rex3`.`dokumenty`.`idKlient`, `rex3`.`dokumenty`.`idZak`, `rex3`.`dokumenty`.`idOsoby`, `rex3`.`dokumenty`.`idAdrKP`, `rex3`.`dokumenty`.`dokOd`, `rex3`.`dokumenty`.`dokDo`, `rex3`.`dokumenty`.`dokDPodpis`, `rex3`.`dokumenty`.`dokNeurcita`, `rex3`.`dokumenty`.`dokVypMes`, `rex3`.`dokumenty`.`dokSeznam`, `rex3`.`dokumenty`.`idDokNad`, `rex3`.`dokumenty`.`dokPDF`, `rex3`.`dokumenty`.`dokPrac`, `rex3`.`dokumenty`.`dokExt`, `rex3`.`dokumenty`.`dokCCena`, 
`rex3`.`dokumenty`.`dokMena` FROM `rex3`.`dokumenty` WHERE `rex3`.`dokumenty`.`idAdrKP` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
prisma:query SELECT `rex3`.`firmy`.`idFirmy`, `rex3`.`firmy`.`FFirma`, `rex3`.`firmy`.`FNazev`, `rex3`.`firmy`.`ICO`, `rex3`.`firmy`.`DIC`, `rex3`.`firmy`.`Splatnost`, `rex3`.`firmy`.`Frekvence`, `rex3`.`firmy`.`fTel`, `rex3`.`firmy`.`fFax`, `rex3`.`firmy`.`fPozn`, `rex3`.`firmy`.`fSoud`, `rex3`.`firmy`.`idPrimKontakt`, `rex3`.`firmy`.`idZastoupena`, `rex3`.`firmy`.`idLepic`, `rex3`.`firmy`.`idFirAdr`, `rex3`.`firmy`.`idKorespAdr`, `rex3`.`firmy`.`idLepicAdr`, `rex3`.`firmy`.`idkDir`, `rex3`.`firmy`.`fKlient`, `rex3`.`firmy`.`fDodav`, `rex3`.`firmy`.`fRSdod`, `rex3`.`firmy`.`fAktivni`, `rex3`.`firmy`.`Cinnost`, `rex3`.`firmy`.`Region`, `rex3`.`firmy`.`fKat` FROM `rex3`.`firmy` WHERE `rex3`.`firmy`.`idFirAdr` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
prisma:query SELECT `rex3`.`firmy`.`idFirmy`, `rex3`.`firmy`.`FFirma`, `rex3`.`firmy`.`FNazev`, `rex3`.`firmy`.`ICO`, `rex3`.`firmy`.`DIC`, `rex3`.`firmy`.`Splatnost`, `rex3`.`firmy`.`Frekvence`, `rex3`.`firmy`.`fTel`, `rex3`.`firmy`.`fFax`, `rex3`.`firmy`.`fPozn`, `rex3`.`firmy`.`fSoud`, `rex3`.`firmy`.`idPrimKontakt`, `rex3`.`firmy`.`idZastoupena`, `rex3`.`firmy`.`idLepic`, `rex3`.`firmy`.`idFirAdr`, `rex3`.`firmy`.`idKorespAdr`, `rex3`.`firmy`.`idLepicAdr`, `rex3`.`firmy`.`idkDir`, `rex3`.`firmy`.`fKlient`, `rex3`.`firmy`.`fDodav`, `rex3`.`firmy`.`fRSdod`, `rex3`.`firmy`.`fAktivni`, `rex3`.`firmy`.`Cinnost`, `rex3`.`firmy`.`Region`, `rex3`.`firmy`.`fKat` FROM `rex3`.`firmy` WHERE `rex3`.`firmy`.`idKorespAdr` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
(node:8836) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.adresy.findMany()` invocation in
C:\Users\akxe\Documents\Programming\rita\dist\apps\server\webpack:\apps\server\src\main.ts:49:34


  Value '' not found in enum 'InternalEnum { name: "firmy_fKat", values: [InternalEnumValue { name: "Politika", database_name: None }, InternalEnumValue { name: "Alkohol", database_name: None }, InternalEnumValue { name: "Potraviny", database_name: None }, InternalEnumValue { name: "N_bytek", database_name: Some("Nábytek") }, InternalEnumValue { name: "Sex", database_name: None }, InternalEnumValue { name: "Kasino", database_name: None }, InternalEnumValue { name: "ostatn_", database_name: Some("ostatní") }] }'
    at PrismaClientFetcher.request (C:\Users\akxe\Documents\Programming\rita\node_modules\@prisma\client\src\runtime\getPrismaClient.ts:1184:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:8836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
prisma:query SELECT `rex3`.`firmy`.`idFirmy`, `rex3`.`firmy`.`FFirma`, `rex3`.`firmy`.`FNazev`, `rex3`.`firmy`.`ICO`, `rex3`.`firmy`.`DIC`, `rex3`.`firmy`.`Splatnost`, `rex3`.`firmy`.`Frekvence`, `rex3`.`firmy`.`fTel`, `rex3`.`firmy`.`fFax`, `rex3`.`firmy`.`fPozn`, `rex3`.`firmy`.`fSoud`, `rex3`.`firmy`.`idPrimKontakt`, `rex3`.`firmy`.`idZastoupena`, `rex3`.`firmy`.`idLepic`, `rex3`.`firmy`.`idFirAdr`, `rex3`.`firmy`.`idKorespAdr`, `rex3`.`firmy`.`idLepicAdr`, `rex3`.`firmy`.`idkDir`, `rex3`.`firmy`.`fKlient`, `rex3`.`firmy`.`fDodav`, `rex3`.`firmy`.`fRSdod`, `rex3`.`firmy`.`fAktivni`, `rex3`.`firmy`.`Cinnost`, `rex3`.`firmy`.`Region`, `rex3`.`firmy`.`fKat` FROM `rex3`.`firmy` WHERE `rex3`.`firmy`.`idLepicAdr` IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
```

---

Also, could we do something about the `IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)` part? It crashes if you select more numbers, or when your IDs are too long... It did happen to me already once

**Comment by janpio** [comment]
Hm, that is a very different error message than the one you were getting in Prisma Studio - correct?

Can you possibly put this into a new app and upload it to Github so we can reproduce it?

**Comment by janpio** [comment]
> Also, could we do something about the `IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)` part? It crashes if you select more numbers, or when your IDs are too long... It did happen to me already once

What do you mean by that? If this is a separate problem, please open a new issue about this so we can look into it in isolation.

**Comment by Akxe** [comment]
> Hm, that is a very different error message than the one you were getting in Prisma Studio - correct?

Indeed, the  error from studio is very generic...

> Can you possibly put this into a new app and upload it to Github so we can reproduce it?

I can, but I am now at vacation and will return on a week. You should have all necessary in here. I'll do it in a week if it is still needed.

**Comment by pantharshit00** [comment]
I tried all this locally and wasn't able to reproduce.

It would be quite hard to reproduce without some actual data. If you can upload some database rows here which has the conflict, that would help here.

The origin error message is most likely not even hitting the database as it seem to originate in the query engine validator with the take argument. 

Maybe possible you ran it with a older query engine which doesn't had the pagination change? Maybe clear your node_modules and install packages.

**Comment by Akxe** [comment]
> I tried all this locally and wasn't able to reproduce.
> 
> It would be quite hard to reproduce without some actual data. If you can upload some database rows here which has the conflict, that would help here.
> 
> The origin error message is most likely not even hitting the database as it seem to originate in the query engine validator with the take argument. 
> 
> Maybe possible you ran it with a older query engine which doesn't had the pagination change? Maybe clear your node_modules and install packages.

The engine is new. I don't have the `experimental-introspection` flag anymore as it is now default.

I will try to publish part of DB, but they are proprietary...

**Comment by Akxe** [comment]
@janpio @pantharshit00 Is NDA still possible?

**Comment by janpio** [comment]
Of course, just email schema@prisma.io - @divyenduz will take care of it.

**Comment by Sytten** [comment]
Yeah I also found that it is very annoying, I am also checking for relation violations (P2014) when I know a foreign key violation can occur since if you explicit set a one-to-one relation in the schema it's not the same error a one-to-many with a wrong foreign key.

**Comment by pantharshit00** [comment]
I think we have improved this message in the recent patches. I am going to close this due to inactivity.
