### ISSUE TITLE
Null pointer exception when using UUID - postgres

### ISSUE THREAD

**Issue by dsinai14** [prisma/prisma#3715]
**Describe the bug**
When there is a reference column to type UUID is set to null (on purpose), a NULL pointer exception is throws from prisma

**To Reproduce**
***SQL***
```
CREATE TABLE table_a (
  id uuid NOT NULL PRIMARY KEY,
  name text
);

CREATE TABLE table_b (
  id uuid NOT NULL PRIMARY KEY,
  a_id uuid references table_a(id)
);

insert into table_a (id, name) values ('ab6981ee-02e8-4d3c-87a1-08d45ebd8b03', 'test');
insert into table_b (id, a_id) values ('5ac8367d-702e-4eff-b3fe-edfd9490c967', null);
```

***Prisma data model***
```
type TableA @pgTable(name: "table_a") {
    id:             UUID! @unique
    name:           String!
}

type TableB @pgTable(name: "table_b") {
    id:             UUID! @unique
    a:              TableA @pgRelation(column: "a_id")
}
```

***graphql query***
```
query {
  tableBs {
    id
    a {
      id
    }
  }
}
```

***Exception***
```
java.lang.NullPointerException
       at java.util.UUID.fromString(UUID.java:192)
       at com.prisma.gc_values.UuidGCValue$.$anonfun$parse$1(GcValues.scala:89)
       at scala.util.Try$.apply(Try.scala:209)
       at com.prisma.gc_values.UuidGCValue$.parse(GcValues.scala:89)
       at com.prisma.gc_values.UuidGCValue$.parse_$bang(GcValues.scala:88)
       at com.prisma.api.connector.jdbc.extensions.JdbcExtensionsValueClasses$ResultSetExtensions$.getGcValue$extension(JdbcExtensions.scala:68)
       at com.prisma.api.connector.jdbc.database.ResultSetReaders.$anonfun$readPrismaNode$1(ResultSetReaders.scala:29)
       at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
       at scala.collection.Iterator.foreach(Iterator.scala:929)
       at scala.collection.Iterator.foreach$(Iterator.scala:929)
       at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
       at scala.collection.IterableLike.foreach(IterableLike.scala:71)
       at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
       at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
       at scala.collection.TraversableLike.map(TraversableLike.scala:234)
       at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
       at scala.collection.AbstractTraversable.map(Traversable.scala:104)
       at com.prisma.api.connector.jdbc.database.ResultSetReaders.readPrismaNode(ResultSetReaders.scala:29)
       at com.prisma.api.connector.jdbc.database.ResultSetReaders.$anonfun$readsPrismaNode$1(ResultSetReaders.scala:25)
       at com.prisma.slick.ReadsResultSet$$anon$1.read(ResultSetExtensions.scala:16)
       at com.prisma.slick.ResultSetExtensionsValueClasses$ResultSetExtensions2$.readWith$extension(ResultSetExtensions.scala:31)
       at com.prisma.api.connector.jdbc.database.NodeManyQueries.$anonfun$getNodes$2(NodeManyQueries.scala:20)
       at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$queryToDBIO$1(SharedSlickExtensions.scala:15)
       at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$jooqToDBIO$1(SharedSlickExtensions.scala:62)
       at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
       at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
       at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
       at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
Should return the records without the reference, not crash

**Versions (please complete the following information):**
 - OS: OS X High Sierra
 - Prisma Server: 1.22

**Comment by pantharshit00** [comment]
I am able to reproduce the bug in the latest beta too. Here is the reproduction repo: https://github.com/pantharshit00/prisma-issue-3175
