### ISSUE TITLE
When CLI and Client are not in sync, generate errors with TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3729]
## Bug description

When CLI and Client are not in sync, generate errors with 

`TypeError: Cannot read property 'type' of undefined`

## How to reproduce

1. package.json
```
{
  "name": "p2-dev",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@prisma/cli": "2.8.0-dev.27",
    "@prisma/client": "2.8.0-dev.9"
  }
}
```
2. schema.prisma
```
datasource db {
  provider = "postgresql"
  url      = "postgresql://this-will-not-be-used-but-overwritten-in-the-prisma-client-constructor"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  email String @default("")
  id    String @id
  name  String @default("")
}
```
3. Run `yarn; yarn prisma generate`
4. Observe the error

```
divyendusingh [p2-dev]$ yarn; yarn prisma generate
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.07s.
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/.bin/prisma generate
Prisma Schema loaded from schema.prisma
Error:
TypeError: Cannot read property 'type' of undefined
    at /Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:9439:45
    at Array.map (<anonymous>)
    at /Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:9436:43
    at Array.map (<anonymous>)
    at transformInputTypes (/Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:9424:61)
    at transformDmmf (/Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:9383:15)
    at getPrismaClientDMMF (/Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:9521:10)
    at buildClient (/Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:11092:21)
    at generateClient (/Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:11148:45)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## Expected behavior

It should not crash

## Prisma information

```
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/.bin/prisma --version
@prisma/cli          : 2.8.0-dev.27
Current platform     : darwin
Query Engine         : query-engine 7aef029819840cd88e6333b5037105264c82e2f4 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 7aef029819840cd88e6333b5037105264c82e2f4 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 7aef029819840cd88e6333b5037105264c82e2f4 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 7aef029819840cd88e6333b5037105264c82e2f4 (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.291.0
Done in 2.05s.
```

**Comment by williamluke4** [comment]
Closing https://github.com/prisma/prisma/issues/2419 help with this. Though I would like to add a check to see if the `@primsa/client` and `@prisma/cli` are in sync

**Comment by janpio** [comment]
> Closing #2419 help with this

This would merely try to avoid and minimize situations like this. The fundamental problem that you get an error when using different versions - which is not discouraged yet and used to work just fine - would not be fixed at all.

**Comment by Jolg42** [comment]
Note: this happened after @timsuchanek union types merge https://github.com/prisma/prisma/commit/de22f0dbc8220c37649ceec9cc89b14855dfe3e6
https://buildkite.com/prisma/prisma2-publish/builds/2762

**Comment by timsuchanek** [comment]
Fixed by https://github.com/prisma/prisma/pull/3782
