### ISSUE TITLE
When CLI and Client are not in sync, generate errors with TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3739]
## Bug description

Note: This is related to https://github.com/prisma/prisma/issues/3729, the only difference is that the versions of CLI and Client are switched in `package.json` and the returned error is different. 
When CLI and Client are not in sync, generate errors with 

`TypeError: Cannot read property 'type' of undefined`

## How to reproduce

1. package.json
```
{
  "name": "p2-dev",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@prisma/client": "2.8.0-dev.27",
    "@prisma/cli": "2.8.0-dev.9"
  }
}
```
2. schema.prisma
```
datasource db {
  provider = "postgresql"
  url      = "postgresql://this-will-not-be-used-but-overwritten-in-the-prisma-client-constructor"
}

generator client {
  provider = "prisma-client-js"
}

model User {
  email String @default("")
  id    String @id
  name  String @default("")
}
```
3. Run `yarn; yarn prisma generate`
4. Observe the error

```
divyendusingh [p2-dev]$ yarn; yarn prisma generate                                                                                          130 ↵
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 6.08s.
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/.bin/prisma generate
Prisma Schema loaded from schema.prisma
Error:
TypeError: Cannot read property '0' of undefined
    at DMMFClass.resolveInputTypes (/Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:9940:39)
    at new DMMFClass (/Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:9919:10)
    at new TSClient (/Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:10316:17)
    at buildClient (/Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:11391:18)
    at generateClient (/Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/@prisma/client/generator-build/index.js:11446:45)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Expected behavior

It should not crash

## Prisma information

```
yarn run v1.22.4
$ /Users/divyendusingh/Documents/prisma/triage/p2-dev/node_modules/.bin/prisma --version
@prisma/cli          : 2.8.0-dev.27
Current platform     : darwin
Query Engine         : query-engine 7aef029819840cd88e6333b5037105264c82e2f4 (at node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 7aef029819840cd88e6333b5037105264c82e2f4 (at node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 7aef029819840cd88e6333b5037105264c82e2f4 (at node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 7aef029819840cd88e6333b5037105264c82e2f4 (at node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.291.0
Done in 2.05s.
```

**Comment by timsuchanek** [comment]
Fixed by https://github.com/prisma/prisma/pull/3782
