### ISSUE TITLE
Support native bigint instance of nodejs?

### ISSUE THREAD

**Issue by Yama-Tomo** [prisma/prisma#3743]
## Bug description

I get a SQL error when I try to use the native bigInt of nodejs.

If you look at the stack trace, it's probably because bigint has been cast into the string.
Is there a workaround?

## Details

I'm making a graphql server that handles bigint columns with `nexus` and `graphql-scalars`.
Using the `graphql-scalars`, if your nodejs supports native bigInt, it will be resolved as a bigInt.
I suspect that prisma does not support it.

### tech stack
- prisma (more info see `Environment & setup` section)
- nexus@0.26.1
- nexus-plugin-prisma@0.19.0
- graphql-scalars@1.2.7

### code(some excerpts)

`schema.prisma`
```
model Product {
  id Int  @id   @default(autoincrement())  
  name String
  publisherId Int // NOTE: In mysql it's a BigInt
  ....
}
```

object type definitions
```typescript
const name = 'Product';
type PrismaScalarOpts = Parameters<NexusPrismaFields<typeof name>['id']>[0];

export const Product = objectType({
  name,
  definition(t) {
    Object.values(t.model).forEach((field: (args?: PrismaScalarOpts) => void) => field());

    // overwrite field type to BigInt
    t.field('publisherId', { type: 'BigInt' });
  },
});
```

### stack trace
```
"stacktrace": [
  "Error: ",
  "Invalid `prisma.product.findOne()` invocation in",
  "/path/to/project/node_modules/nexus-plugin-prisma/src/schema/builder.ts:346:91",
  "",
  "  342 }",
  "  343 ",
  "  344 args = this.paginationStrategy.resolve(args)",
  "  345 ",
  "→ 346 return prismaClient[mappedField.prismaClientAccessor][mappedField.operation](args{",
  "      where: {",
  "        publisherId: '20600013118079'",
  "                   ~~~~~~~~~~~~~~",
  "      }",
  "    })",
  "",
  "Argument publisherId: Got invalid value '20600013118079' on prisma.findOneProduct. Provided undefined, expected Int.",
  "",
  "",
  "    at Hi.validate (/path/to/project/node_modules/@prisma/client/runtime/src/runtime/query.ts:272:19)",
  "    at t._executeRequest (/path/to/project/node_modules/@prisma/client/runtime/src/runtime/getPrismaClient.ts:806:16)",
  "    at /path/to/project/node_modules/@prisma/client/runtime/src/runtime/getPrismaClient.ts:714:14",
  "    at AsyncResource.runInAsyncScope (async_hooks.js:186:9)",
  "    at t._request (/path/to/project/node_modules/@prisma/client/runtime/src/runtime/getPrismaClient.ts:713:23)",
  "    at Object.then (/path/to/project/node_modules/@prisma/client/runtime/src/runtime/getPrismaClient.ts:871:39)",
  "    at whenResultIsFinished (/path/to/project/node_modules/graphql-extensions/src/index.ts:304:12)",
  "    at field.resolve (/path/to/project/node_modules/graphql-extensions/src/index.ts:280:7)",
  "    at field.resolve (/path/to/project/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103:18)",
  "    at resolveFieldValueOrError (/path/to/project/node_modules/graphql/execution/execute.js:467:18)"
]
```

## Environment & setup

- OS: Mac OS
- Database: MySQL 5.6.41
- Node.js version: v12.18.3
- Prisma version:
```
@prisma/cli          : 2.7.0
Current platform     : darwin
Query Engine         : query-engine eaade828a21d8ee3f4940f0af7da3ae0922db4df (at ../../node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli eaade828a21d8ee3f4940f0af7da3ae0922db4df (at ../../node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core eaade828a21d8ee3f4940f0af7da3ae0922db4df (at ../../node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt eaade828a21d8ee3f4940f0af7da3ae0922db4df (at ../../node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.287.0
```

**Comment by BryceLarkin** [comment]
Adding to this, JavaScript's [max safe integer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) is `2^53 - 1` while Postgres' bigint *generally* has a max value of `2^63 - 1`, so any number received from the database that's between `2^53` and `2^63 - 1` can throw an error.

The [Node Postgres](https://github.com/brianc/node-pg-types/issues/78) library handles BigInts as string, but it looks like they might transition to JavaScript's `BigInt` in a couple of years.

**Comment by pantharshit00** [comment]
BigInts are supported now: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-advanced-types#working-with-bigint
