### ISSUE TITLE
two create commands incorrectly trigger unique constraint error

### ISSUE THREAD

**Issue by tianhuil** [prisma/prisma#3767]
**Describe the bug**
Creating two users via [this mutation](https://github.com/tianhuil/prisma-tutorial/blob/seeding-two-users/server/src/seed.graphql) (that uses [this schema](https://github.com/tianhuil/prisma-tutorial/blob/seeding-two-users/server/src/schema.graphql)):

```
mutation {
  user1: createUser (
    data: {
      firstName: "Alice",
      lastName: "Jones",
      email: "alice@example.com",
      hash: "xxxx",
      posts: {
        create: [
          {headline: "A" topic: DISCUSSION},
          {headline: "B" topic: HELP},
          {headline: "C" topic: DISCUSSION},
          {headline: "D" topic: HELP}
        ]
      },
    }
  ) {
    id
  }

  user2: createUser (
    data: {
      firstName: "Bob",
      lastName: "Smith",
      email: "bob@example.com",
      hash: "yyyy",
      posts: {
        create: [
          {headline: "X" topic: DISCUSSION},
          {headline: "Y" topic: HELP},
          {headline: "Z" topic: DISCUSSION},
        ]
      },
    }
  ) {
    id
  }
}
```

Note that in the schema, the `email` field of `User` is unique but in the mutation query, the email fields for the two users are unique.  Also, this error does not occur if we delete the second `createUser`.

**To Reproduce**
Check out [this repo](https://github.com/tianhuil/prisma-tutorial/tree/seeding-two-users) and run
```bash
make build-dev
make run-dev
```
After some biolerplate, you'll see a complaint `A unique constraint would be violated on User. Details: Field name = email, Location: [object Object], Path: user1`.  The full error message (showing the failure in both postgres and prisma levels) are shown here:
```
[36mpostgres_1   |[0m 2018-12-23 22:37:31.469 UTC [70] ERROR:  duplicate key value violates unique constraint "default$default.User.email._UNIQUE"
[36mpostgres_1   |[0m 2018-12-23 22:37:31.469 UTC [70] DETAIL:  Key (email)=(alice@example.com) already exists.
[36mpostgres_1   |[0m 2018-12-23 22:37:31.469 UTC [70] STATEMENT:  insert into "default$default"."User" (
[36mpostgres_1   |[0m 	  "id", 
[36mpostgres_1   |[0m 	  "firstName", 
[36mpostgres_1   |[0m 	  "lastName", 
[36mpostgres_1   |[0m 	  "about", 
[36mpostgres_1   |[0m 	  "email", 
[36mpostgres_1   |[0m 	  "hash", 
[36mpostgres_1   |[0m 	  "createdAt", 
[36mpostgres_1   |[0m 	  "updatedAt"
[36mpostgres_1   |[0m 	)
[36mpostgres_1   |[0m 	values (
[36mpostgres_1   |[0m 	  $1, 
[36mpostgres_1   |[0m 	  $2, 
[36mpostgres_1   |[0m 	  $3, 
[36mpostgres_1   |[0m 	  $4, 
[36mpostgres_1   |[0m 	  $5, 
[36mpostgres_1   |[0m 	  $6, 
[36mpostgres_1   |[0m 	  $7, 
[36mpostgres_1   |[0m 	  $8
[36mpostgres_1   |[0m 	)
[36mpostgres_1   |[0m 	RETURNING *
[35mprisma_1     |[0m {"key":"error/handled","requestId":"local:api:cjq1h3poc00120a32zi19ezon","clientId":"default$default","payload":{"exception":"com.prisma.api.schema.APIErrors$UniqueConstraintViolation: A unique constraint would be violated on User. Details: Field name = email","query":"mutation {\n  user1: createUser(data: {firstName: \"Alice\", lastName: \"Jones\", email: \"alice@example.com\", hash: \"xxxx\", posts: {create: [{headline: \"A\", topic: DISCUSSION}, {headline: \"B\", topic: HELP}, {headline: \"C\", topic: DISCUSSION}, {headline: \"D\", topic: HELP}]}}) {\n    id\n  }\n  user2: createUser(data: {firstName: \"Bob\", lastName: \"Smith\", email: \"bob@example.com\", hash: \"xxxx\", posts: {create: [{headline: \"X\", topic: DISCUSSION}, {headline: \"Y\", topic: HELP}, {headline: \"Z\", topic: DISCUSSION}]}}) {\n    id\n  }\n}\n","variables":"{}","code":"3010","stack_trace":"com.prisma.api.connector.jdbc.impl.CreateNodeInterpreter$$anonfun$1.applyOrElse(CreateNodeInterpreters.scala:33)\\n com.prisma.api.connector.jdbc.impl.CreateNodeInterpreter$$anonfun$1.applyOrElse(CreateNodeInterpreters.scala:31)\\n scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)\\n scala.PartialFunction$Lifted.apply(PartialFunction.scala:220)\\n com.prisma.api.connector.jdbc.DatabaseMutactionInterpreter.$anonfun$applyErrorMapper$1(NestedDatabaseMutactionInterpreter.scala:21)\\n slick.basic.BasicBackend$DatabaseDef.$anonfun$runInContextInline$1(BasicBackend.scala:171)\\n scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)\\n scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)","message":"A unique constraint would be violated on User. Details: Field name = email"}}
[31mbuild-dev_1  |[0m $ /home/workdir/node_modules/.bin/ts-node src/seed.ts src/seed.graphql
[31mbuild-dev_1  |[0m Connecting to prisma on http://prisma:4466
[31mbuild-dev_1  |[0m Opening File
[31mbuild-dev_1  |[0m Opened File
[31mbuild-dev_1  |[0m Request to http://prisma:4466:
[31mbuild-dev_1  |[0m query:
[31mbuild-dev_1  |[0m mutation {
[31mbuild-dev_1  |[0m   user1: createUser(data: {firstName: "Alice", lastName: "Jones", email: "alice@example.com", hash: "xxxx", posts: {create: [{headline: "A", topic: DISCUSSION}, {headline: "B", topic: HELP}, {headline: "C", topic: DISCUSSION}, {headline: "D", topic: HELP}]}}) {
[31mbuild-dev_1  |[0m     id
[31mbuild-dev_1  |[0m   }
[31mbuild-dev_1  |[0m   user2: createUser(data: {firstName: "Bob", lastName: "Smith", email: "bob@example.com", hash: "xxxx", posts: {create: [{headline: "X", topic: DISCUSSION}, {headline: "Y", topic: HELP}, {headline: "Z", topic: DISCUSSION}]}}) {
[31mbuild-dev_1  |[0m     id
[31mbuild-dev_1  |[0m   }
[31mbuild-dev_1  |[0m }
[31mbuild-dev_1  |[0m operationName: null
[31mbuild-dev_1  |[0m variables:
[31mbuild-dev_1  |[0m {}
[31mbuild-dev_1  |[0m [GraphQL error]: Message: A unique constraint would be violated on User. Details: Field name = email, Location: [object Object], Path: user1
[31mbuild-dev_1  |[0m [Network error]: Error: A unique constraint would be violated on User. Details: Field name = email
[31mbuild-dev_1  |[0m Error in Seeding
[31mbuild-dev_1  |[0m [ { Error: A unique constraint would be violated on User. Details: Field name = email
[31mbuild-dev_1  |[0m     at BatchedGraphQLClient.<anonymous> (/home/workdir/node_modules/http-link-dataloader/src/BatchedGraphQLClient.ts:74:13)
[31mbuild-dev_1  |[0m     at step (/home/workdir/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
[31mbuild-dev_1  |[0m     at Object.next (/home/workdir/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
[31mbuild-dev_1  |[0m     at fulfilled (/home/workdir/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
[31mbuild-dev_1  |[0m     at <anonymous>
[31mbuild-dev_1  |[0m     at process._tickDomainCallback (internal/process/next_tick.js:229:7)
[31mbuild-dev_1  |[0m     message: 'A unique constraint would be violated on User. Details: Field name = email',
[31mbuild-dev_1  |[0m     locations: [ [Object] ],
[31mbuild-dev_1  |[0m     path: [ 'user1' ] } ]
[31mbuild-dev_1  |[0m info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[31mbuild-dev_1  |[0m 
[31mbuild-dev_1  |[0m error Command failed with exit code 1.
[31mbuild-dev_1  |[0m 
[31mbuild-dev_1  |[0m [22:37:31] 'seed' errored after 1.79 s
[31mbuild-dev_1  |[0m [22:37:31] Error: Command failed: yarn ts-node src/seed.ts src/seed.graphql
[31mbuild-dev_1  |[0m error Command failed with exit code 1.
[31mbuild-dev_1  |[0m 
[31mbuild-dev_1  |[0m     at ChildProcess.exithandler (child_process.js:276:12)
[31mbuild-dev_1  |[0m     at emitTwo (events.js:126:13)
[31mbuild-dev_1  |[0m     at ChildProcess.emit (events.js:214:7)
[31mbuild-dev_1  |[0m     at maybeClose (internal/child_process.js:915:16)
[31mbuild-dev_1  |[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[31mbuild-dev_1  |[0m [22:37:31] 'build-dev' errored after 8.01 s
[31mbuild-dev_1  |[0m error Command failed with exit code 1.
[31mbuild-dev_1  |[0m info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[31mbuild-dev_1  |[0m 2018/12/23 22:37:31 Command exited with error: exit status 1
[32mdev_build-dev_1 exited with code 1
```

**Expected behavior**
The above mutation should succeed without a failure.

**Versions (please complete the following information):**
 - OS: This is in docker so should work on any OS.

**Additional context**
Does not appear to be any of the following issues:
- https://github.com/prisma/prisma/issues/407
- https://github.com/prisma/prisma/issues/153
- https://github.com/LawJolla/prisma-auth0-example/issues/11
- https://github.com/graphql-binding/graphql-binding/issues/45
- https://github.com/prisma/graphcool-framework/issues/165

But might have something to do with https://www.prisma.io/forum/t/handling-prismas-error-when-using-prisma-binding/4387

**Comment by pantharshit00** [comment]
Hi @tianhuil,

Thanks for the detailed explanation and reproduction that you have provided 👍. Really appreciate it. I was able to reproduce this. We will fix this in a future release.

**Comment by pantharshit00** [comment]
PS: The build scripts of your reproduction is not working as yarn is failing to download event-stream which has been taken down due to the recent npm issues: https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

**Comment by tianhuil** [comment]
Thanks for your that @pantharshit00!
