### ISSUE TITLE
Error: [libs/datamodel/core/src/transform/directives/unique_and_index.rs:148:46] called `Result::unwrap()` on an `Err` value: TypeMismatchError { expected_type: "constant literal", received_type: "array", raw: "(array)", span: Span { start: 1645, end: 1652 } } 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#3837]
Command: `prisma introspect`
Version: `2.8.0`
Binary Version: `e6c9b4b2b7fa162d0d459d1863321f547498fcfe`
Report: https://prisma-errors.netlify.app/report/11538 
OS: `x64 darwin 19.6.0`

JS Stacktrace:
```
Error: [libs/datamodel/core/src/transform/directives/unique_and_index.rs:148:46] called `Result::unwrap()` on an `Err` value: TypeMismatchError { expected_type: "constant literal", received_type: "array", raw: "(array)", span: Span { start: 1645, end: 1652 } }
    at IntrospectionEngine.<anonymous> (/Users/kaveh/git/99b/prisma-db/node_modules/@prisma/cli/build/index.js:2:1819280)
    at Generator.throw (<anonymous>)
    at rejected (/Users/kaveh/git/99b/prisma-db/node_modules/@prisma/cli/build/index.js:2:1816300)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   9: <datamodel::transform::directives::unique_and_index::ModelLevelIndexDirectiveValidator as datamodel::transform::directives::directive_validator::DirectiveValidator<datamodel::dml::model::Model>>::validate_and_apply
  10: datamodel::transform::directives::directive_list_validator::DirectiveListValidator<T>::validate_and_apply
  11: datamodel::transform::ast_to_dml::lift::LiftAstToDml::lift
  12: datamodel::transform::ast_to_dml::validation_pipeline::ValidationPipeline::validate
  13: datamodel::parse_datamodel_internal
  14: datamodel::parse_datamodel
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  17: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  18: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  19: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  20: futures::future::chain::Chain<A,B,C>::poll
  21: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  22: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  23: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  24: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  25: futures::task_impl::std::set
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: tokio::runtime::enter::Enter::block_on
  28: tokio::runtime::context::enter
  29: tokio::runtime::handle::Handle::enter
  30: introspection_engine::main
  31: std::rt::lang_start::{{closure}}
  32: std::rt::lang_start_internal
  33: _main

```

**Comment by pantharshit00** [comment]
https://github.com/prisma/prisma/issues/3838#issuecomment-704885809
