### ISSUE TITLE
Embedded document fails on 1:N relation

### ISSUE THREAD

**Issue by mhabegger** [prisma/prisma#3896]
**Describe the bug**
A second-degree relation onto embedded documents only works if the relation is stored as an array on the object also retaining the embedded document. 
Querying the related document fails with an exception on the graphql `Whoops. Looks like an internal server error. Search your server logs for request ID: local:cjr4nehzg000x073222hup9u0` the prisma stacktrace tells: `java.util.NoSuchElementException: key not found: street`

See the two schemas below.

**To Reproduce**
1. The following schema does not work:

```
type User {
  id: ID! @id
  email: String!
  password: String!
  account: Account
    @relation(name: "UsersByAccount", link: INLINE, onDelete: SET_NULL)
}

type Account {
  id: ID! @id
  name: String!
  users: [User!]! @relation(name: "UsersByAccount")
  address: Address
}

type Address @embedded {
  street: String
  city: String
  country: String
}
```

while the following schema works:

```
type User {
  id: ID! @id
  email: String!
  password: String!
  account: Account
    @relation(name: "UsersByAccount")
}

type Account {
  id: ID! @id
  name: String!
  users: [User!]! @relation(name: "UsersByAccount", link: INLINE, onDelete: SET_NULL)
  address: Address
}

type Address @embedded {
  street: String
  city: String
  country: String
}
```

2. in Prisma GraphQL, run the following mutation

```
mutation {
  createUser(
    data: {
      email: "me@domain.com"
      password: "hashedvalue"
      account: {
        create: {
          name: "Company A"
          address: {
            create: {
              street: "1 Fake Street"
              city: "Lausanne"
              country: "Switzerland"
            }
          }
        }
      }
    }
  ) {
    id
    email
    password
  }
}
```
3. Query the following data to confirm the error with the 1st schema, while the second one works properly:

```
query{
  users{
    email
    account{
      name
      address{
        street
      }
    }
  }
}
```

**Expected behavior**
This shall work with both schemas, indifferently where the relation is stored.

**Screenshots**

**Versions (please complete the following information):**
 - Connector: Prisma GraphQL, but occures as well when used with a TypeScript Client
 - Prisma Server: 
 - `prisma` replicated on 1.24.0, 1.25-beta, 1.26-alpha
 - OS: OSX Mojave 10.14.2, prisma as docker on docker 2.0.0.2
 - other dependencies: none

Stacktrace:
```
prisma_1  | java.util.NoSuchElementException: key not found: street
prisma_1  | 	at scala.collection.immutable.Map$Map1.apply(Map.scala:108)
prisma_1  | 	at com.prisma.api.schema.ObjectTypeBuilder.mapToOutputResolve(ObjectTypeBuilder.scala:214)
prisma_1  | 	at com.prisma.api.schema.ObjectTypeBuilder.$anonfun$mapClientField$1(ObjectTypeBuilder.scala:109)
prisma_1  | 	at sangria.execution.Resolver.resolveField(Resolver.scala:1024)
prisma_1  | 	at sangria.execution.Resolver.$anonfun$collectActionsPar$1(Resolver.scala:445)
prisma_1  | 	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
prisma_1  | 	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
prisma_1  | 	at scala.collection.Iterator.foreach(Iterator.scala:929)
prisma_1  | 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
prisma_1  | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
prisma_1  | 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
prisma_1  | 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
prisma_1  | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
prisma_1  | 	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
prisma_1  | 	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
prisma_1  | 	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
prisma_1  | 	at sangria.execution.Resolver.collectActionsPar(Resolver.scala:439)
prisma_1  | 	at sangria.execution.Resolver.resolveValue(Resolver.scala:899)
prisma_1  | 	at sangria.execution.Resolver.resolveValue(Resolver.scala:807)
prisma_1  | 	at sangria.execution.Resolver.$anonfun$resolveActionsPar$4(Resolver.scala:518)
prisma_1  | 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
prisma_1  | 	at scala.collection.Iterator.foreach(Iterator.scala:929)
prisma_1  | 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
prisma_1  | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
prisma_1  | 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
prisma_1  | 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
prisma_1  | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
prisma_1  | 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
prisma_1  | 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
prisma_1  | 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
prisma_1  | 	at sangria.execution.Resolver.resolveActionsPar(Resolver.scala:512)
prisma_1  | 	at sangria.execution.Resolver.resolveValue(Resolver.scala:901)
prisma_1  | 	at sangria.execution.Resolver.resolveValue(Resolver.scala:807)
prisma_1  | 	at sangria.execution.Resolver.$anonfun$resolveActionsPar$13(Resolver.scala:609)
prisma_1  | 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
prisma_1  | 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
prisma_1  | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
prisma_1  | 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
prisma_1  | 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
prisma_1  | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
prisma_1  | 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
prisma_1  | 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
prisma_1  | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
prisma_1  | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
prisma_1  | 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
prisma_1  | 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
prisma_1  | 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
prisma_1  | 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
prisma_1  | {"key":"error/unhandled","requestId":"local:cjr4nehzg000x073222hup9u0","clientId":"contacts_test","payload":{"exception":"java.util.NoSuchElementException: key not found: street","query":"{\n  users {\n    email\n    account {\n      name\n      address {\n        street\n      }\n    }\n  }\n}\n","variables":"{}","code":"0","stack_trace":"scala.collection.immutable.Map$Map1.apply(Map.scala:108)\\n com.prisma.api.schema.ObjectTypeBuilder.mapToOutputResolve(ObjectTypeBuilder.scala:214)\\n com.prisma.api.schema.ObjectTypeBuilder.$anonfun$mapClientField$1(ObjectTypeBuilder.scala:109)\\n sangria.execution.Resolver.resolveField(Resolver.scala:1024)\\n sangria.execution.Resolver.$anonfun$collectActionsPar$1(Resolver.scala:445)\\n scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)\\n scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)\\n scala.collection.Iterator.foreach(Iterator.scala:929)\\n scala.collection.Iterator.foreach$(Iterator.scala:929)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1417)\\n scala.collection.IterableLike.foreach(IterableLike.scala:71)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:70)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)\\n scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)\\n scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)\\n sangria.execution.Resolver.collectActionsPar(Resolver.scala:439)\\n sangria.execution.Resolver.resolveValue(Resolver.scala:899)\\n sangria.execution.Resolver.resolveValue(Resolver.scala:807)\\n sangria.execution.Resolver.$anonfun$resolveActionsPar$4(Resolver.scala:518)\\n scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)\\n scala.collection.Iterator.foreach(Iterator.scala:929)\\n scala.collection.Iterator.foreach$(Iterator.scala:929)\\n scala.collection.AbstractIterator.foreach(Iterator.scala:1417)\\n scala.collection.IterableLike.foreach(IterableLike.scala:71)\\n scala.collection.IterableLike.foreach$(IterableLike.scala:70)\\n scala.collection.AbstractIterable.foreach(Iterable.scala:54)\\n scala.collection.TraversableLike.map(TraversableLike.scala:234)\\n scala.collection.TraversableLike.map$(TraversableLike.scala:227)\\n scala.collection.AbstractTraversable.map(Traversable.scala:104)\\n sangria.execution.Resolver.resolveActionsPar(Resolver.scala:512)\\n sangria.execution.Resolver.resolveValue(Resolver.scala:901)\\n sangria.execution.Resolver.resolveValue(Resolver.scala:807)\\n sangria.execution.Resolver.$anonfun$resolveActionsPar$13(Resolver.scala:609)\\n scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)\\n scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)","message":"key not found: street"}}
```

**Comment by do4gr** [comment]
Thanks for the detailed reproduction. But I cannot reproduce this error when starting with a fresh project on 1.24. 

Can you check if this occurs for you when you start fresh as well? What other steps did you take before the error occurred?

<img width="1056" alt="bildschirmfoto 2019-01-22 um 16 51 31" src="https://user-images.githubusercontent.com/16278407/51547263-3539f900-1e66-11e9-94d9-b44d4bae5a77.png">

**Comment by Shion093** [comment]
Having the same error with the same scenario, second level nested embedded type.

**Comment by do4gr** [comment]
Hey, @Shion093 

can you provide a reproduction repo perhaps? As you can see above I could not replicate the issue and without more information there's not much I can do.

**Comment by Shion093** [comment]
Hello, @do4gr 

I got it working by deploying a new fargate cluster, I think the previous one was messed up.

Thanks for your response.
