### ISSUE TITLE
Failed to install prisma client 2.9 with Node 8

### ISSUE THREAD

**Issue by AlexSenchenko** [prisma/prisma#3930]
Install client give following output.

```
npm install @prisma/cli --save-dev

> @prisma/cli@2.9.0 preinstall /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli
> node preinstall/index.js


> @prisma/cli@2.9.0 install /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli
> node download-build/index.js

internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at m (/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/download-build/index.js:44:2440)
    at /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/download-build/index.js:1:164
    at Nr (/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/download-build/index.js:44:5501)
    at /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/download-build/index.js:1:164
    at ce (/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/download-build/index.js:47:2804)
    at /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/download-build/index.js:1:164
    at Ye (/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/download-build/index.js:47:9005)
    at /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/download-build/index.js:1:164
    at Object.<anonymous> (/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/download-build/index.js:47:11054)
npm WARN weighing-machine-1@1.0.0 No description
npm WARN weighing-machine-1@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @prisma/cli@2.9.0 install: `node download-build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @prisma/cli@2.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by AlexSenchenko** [comment]
Full log is here 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@prisma/cli',
1 verbose cli   '--save-dev' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 50ca1d81bbe36124
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/@prisma%2fcli 28ms (from cache)
8 silly pacote tag manifest for @prisma/cli@latest fetched in 113ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule @prisma/cli@2.9.0 checking installable status
14 silly currentTree weighing-machine-1@1.0.0
14 silly currentTree ├── @types/node@14.11.8
14 silly currentTree ├── arg@4.1.3
14 silly currentTree ├── buffer-from@1.1.1
14 silly currentTree ├── diff@4.0.2
14 silly currentTree ├── make-error@1.3.6
14 silly currentTree ├── source-map-support@0.5.19
14 silly currentTree ├── source-map@0.6.1
14 silly currentTree ├── ts-node@9.0.0
14 silly currentTree ├── typescript@4.0.3
14 silly currentTree └── yn@3.1.1
15 silly idealTree weighing-machine-1@1.0.0
15 silly idealTree └── @prisma/cli@2.9.0
16 silly install generateActionsToTake
17 silly diffTrees action count 11
18 silly diffTrees remove arg@4.1.3
19 silly diffTrees remove buffer-from@1.1.1
20 silly diffTrees remove diff@4.0.2
21 silly diffTrees remove make-error@1.3.6
22 silly diffTrees remove source-map@0.6.1
23 silly diffTrees remove source-map-support@0.5.19
24 silly diffTrees remove yn@3.1.1
25 silly diffTrees add @prisma/cli@2.9.0
26 silly diffTrees remove @types/node@14.11.8
27 silly diffTrees remove ts-node@9.0.0
28 silly diffTrees remove typescript@4.0.3
29 silly decomposeActions action count 28
30 silly decomposeActions unbuild arg@4.1.3
31 silly decomposeActions remove arg@4.1.3
32 silly decomposeActions unbuild buffer-from@1.1.1
33 silly decomposeActions remove buffer-from@1.1.1
34 silly decomposeActions unbuild diff@4.0.2
35 silly decomposeActions remove diff@4.0.2
36 silly decomposeActions unbuild make-error@1.3.6
37 silly decomposeActions remove make-error@1.3.6
38 silly decomposeActions unbuild source-map@0.6.1
39 silly decomposeActions remove source-map@0.6.1
40 silly decomposeActions unbuild source-map-support@0.5.19
41 silly decomposeActions remove source-map-support@0.5.19
42 silly decomposeActions unbuild yn@3.1.1
43 silly decomposeActions remove yn@3.1.1
44 silly decomposeActions fetch @prisma/cli@2.9.0
45 silly decomposeActions extract @prisma/cli@2.9.0
46 silly decomposeActions preinstall @prisma/cli@2.9.0
47 silly decomposeActions build @prisma/cli@2.9.0
48 silly decomposeActions install @prisma/cli@2.9.0
49 silly decomposeActions postinstall @prisma/cli@2.9.0
50 silly decomposeActions finalize @prisma/cli@2.9.0
51 silly decomposeActions refresh-package-json @prisma/cli@2.9.0
52 silly decomposeActions unbuild @types/node@14.11.8
53 silly decomposeActions remove @types/node@14.11.8
54 silly decomposeActions unbuild ts-node@9.0.0
55 silly decomposeActions remove ts-node@9.0.0
56 silly decomposeActions unbuild typescript@4.0.3
57 silly decomposeActions remove typescript@4.0.3
58 silly install executeActions
59 silly doSerial global-install 28
60 verbose correctMkdir /Users/alexander/.npm/_locks correctMkdir not in flight; initializing
61 verbose lock using /Users/alexander/.npm/_locks/staging-89234ed43674be08.lock for /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.staging
62 silly doParallel extract 28
63 silly extract @prisma/cli@2.9.0
64 silly doReverseSerial unbuild 28
65 silly unbuild typescript@4.0.3
66 info lifecycle typescript@4.0.3~preuninstall: typescript@4.0.3
67 info lifecycle typescript@4.0.3~uninstall: typescript@4.0.3
68 verbose unbuild rmStuff typescript@4.0.3 from /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules
69 silly isEverInside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/tsserver is not inside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/typescript
70 silly gentlyRm parent.path = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/typescript
71 silly gentlyRm parent.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/typescript is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
72 silly gentlyRm target.path =  /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/tsserver
73 silly gentlyRm target.symlink = ../typescript/bin/tsserver
74 silly gentlyRm target.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/tsserver is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
75 silly gentlyRm target.inParent =  { target: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/typescript/bin/tsserver',
75 silly gentlyRm   path: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/typescript' }
76 silly isEverInside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/tsc is not inside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/typescript
77 silly gentlyRm parent.path = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/typescript
78 silly gentlyRm parent.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/typescript is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
79 silly gentlyRm target.path =  /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/tsc
80 silly gentlyRm target.symlink = ../typescript/bin/tsc
81 silly gentlyRm target.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/tsc is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
82 silly gentlyRm target.inParent =  { target: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/typescript/bin/tsc',
82 silly gentlyRm   path: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/typescript' }
83 info lifecycle typescript@4.0.3~postuninstall: typescript@4.0.3
84 silly unbuild ts-node@9.0.0
85 info lifecycle ts-node@9.0.0~preuninstall: ts-node@9.0.0
86 info lifecycle ts-node@9.0.0~uninstall: ts-node@9.0.0
87 verbose unbuild rmStuff ts-node@9.0.0 from /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules
88 silly isEverInside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-script is not inside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node
89 silly gentlyRm parent.path = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node
90 silly gentlyRm parent.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
91 silly gentlyRm target.path =  /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-script
92 silly gentlyRm target.symlink = ../ts-node/dist/bin-script-deprecated.js
93 silly gentlyRm target.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-script is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
94 silly gentlyRm target.inParent =  { target: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node/dist/bin-script-deprecated.js',
94 silly gentlyRm   path: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node' }
95 silly isEverInside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-node-script is not inside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node
96 silly gentlyRm parent.path = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node
97 silly gentlyRm parent.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
98 silly gentlyRm target.path =  /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-node-script
99 silly gentlyRm target.symlink = ../ts-node/dist/bin-script.js
100 silly gentlyRm target.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-node-script is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
101 silly gentlyRm target.inParent =  { target: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node/dist/bin-script.js',
101 silly gentlyRm   path: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node' }
102 silly isEverInside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-node is not inside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node
103 silly gentlyRm parent.path = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node
104 silly gentlyRm parent.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
105 silly gentlyRm target.path =  /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-node
106 silly gentlyRm target.symlink = ../ts-node/dist/bin.js
107 silly gentlyRm target.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-node is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
108 silly gentlyRm target.inParent =  { target: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node/dist/bin.js',
108 silly gentlyRm   path: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node' }
109 silly isEverInside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-node-transpile-only is not inside /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node
110 silly gentlyRm parent.path = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node
111 silly gentlyRm parent.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
112 silly gentlyRm target.path =  /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-node-transpile-only
113 silly gentlyRm target.symlink = ../ts-node/dist/bin-transpile.js
114 silly gentlyRm target.managed = /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin/ts-node-transpile-only is in /Users/alexander/src/github/weighing.machine/weighing-machine-1
115 silly gentlyRm target.inParent =  { target: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node/dist/bin-transpile.js',
115 silly gentlyRm   path: '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node' }
116 info lifecycle ts-node@9.0.0~postuninstall: ts-node@9.0.0
117 silly unbuild @types/node@14.11.8
118 info lifecycle @types/node@14.11.8~preuninstall: @types/node@14.11.8
119 info lifecycle @types/node@14.11.8~uninstall: @types/node@14.11.8
120 verbose unbuild rmStuff @types/node@14.11.8 from /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules
121 info lifecycle @types/node@14.11.8~postuninstall: @types/node@14.11.8
122 silly unbuild yn@3.1.1
123 info lifecycle yn@3.1.1~preuninstall: yn@3.1.1
124 info lifecycle yn@3.1.1~uninstall: yn@3.1.1
125 verbose unbuild rmStuff yn@3.1.1 from /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules
126 info lifecycle yn@3.1.1~postuninstall: yn@3.1.1
127 silly unbuild source-map-support@0.5.19
128 info lifecycle source-map-support@0.5.19~preuninstall: source-map-support@0.5.19
129 info lifecycle source-map-support@0.5.19~uninstall: source-map-support@0.5.19
130 verbose unbuild rmStuff source-map-support@0.5.19 from /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules
131 info lifecycle source-map-support@0.5.19~postuninstall: source-map-support@0.5.19
132 silly unbuild source-map@0.6.1
133 info lifecycle source-map@0.6.1~preuninstall: source-map@0.6.1
134 info lifecycle source-map@0.6.1~uninstall: source-map@0.6.1
135 verbose unbuild rmStuff source-map@0.6.1 from /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules
136 info lifecycle source-map@0.6.1~postuninstall: source-map@0.6.1
137 silly unbuild make-error@1.3.6
138 info lifecycle make-error@1.3.6~preuninstall: make-error@1.3.6
139 info lifecycle make-error@1.3.6~uninstall: make-error@1.3.6
140 verbose unbuild rmStuff make-error@1.3.6 from /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules
141 info lifecycle make-error@1.3.6~postuninstall: make-error@1.3.6
142 silly unbuild diff@4.0.2
143 info lifecycle diff@4.0.2~preuninstall: diff@4.0.2
144 info lifecycle diff@4.0.2~uninstall: diff@4.0.2
145 verbose unbuild rmStuff diff@4.0.2 from /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules
146 info lifecycle diff@4.0.2~postuninstall: diff@4.0.2
147 silly unbuild buffer-from@1.1.1
148 info lifecycle buffer-from@1.1.1~preuninstall: buffer-from@1.1.1
149 info lifecycle buffer-from@1.1.1~uninstall: buffer-from@1.1.1
150 verbose unbuild rmStuff buffer-from@1.1.1 from /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules
151 info lifecycle buffer-from@1.1.1~postuninstall: buffer-from@1.1.1
152 silly unbuild arg@4.1.3
153 info lifecycle arg@4.1.3~preuninstall: arg@4.1.3
154 info lifecycle arg@4.1.3~uninstall: arg@4.1.3
155 verbose unbuild rmStuff arg@4.1.3 from /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules
156 info lifecycle arg@4.1.3~postuninstall: arg@4.1.3
157 silly doSerial remove 28
158 silly remove /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/arg
159 silly remove /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/buffer-from
160 silly remove /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/diff
161 silly remove /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/make-error
162 silly remove /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/source-map
163 silly remove /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/source-map-support
164 silly remove /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/yn
165 silly remove /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@types/node
166 silly remove /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/ts-node
167 silly remove /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/typescript
168 silly doSerial move 28
169 silly doSerial finalize 28
170 silly finalize /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli
171 silly doParallel refresh-package-json 28
172 silly refresh-package-json /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli
173 silly doParallel preinstall 28
174 silly preinstall @prisma/cli@2.9.0
175 info lifecycle @prisma/cli@2.9.0~preinstall: @prisma/cli@2.9.0
176 verbose lifecycle @prisma/cli@2.9.0~preinstall: unsafe-perm in lifecycle true
177 verbose lifecycle @prisma/cli@2.9.0~preinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/node_modules/.bin:/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
178 verbose lifecycle @prisma/cli@2.9.0~preinstall: CWD: /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli
179 silly lifecycle @prisma/cli@2.9.0~preinstall: Args: [ '-c', 'node preinstall/index.js' ]
180 silly lifecycle @prisma/cli@2.9.0~preinstall: Returned: code: 0  signal: null
181 silly doSerial build 28
182 silly build @prisma/cli@2.9.0
183 info linkStuff @prisma/cli@2.9.0
184 silly linkStuff @prisma/cli@2.9.0 has /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules as its parent node_modules
185 verbose linkBins @prisma/cli@2.9.0
186 verbose linkBins [ { prisma: 'build/index.js', prisma2: 'build/index.js' },
186 verbose linkBins   '/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin',
186 verbose linkBins   false ]
187 verbose linkMans @prisma/cli@2.9.0
188 silly linkBins Converting line endings of hashbang file: /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/build/index.js
189 silly linkBins Converting line endings of hashbang file: /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/build/index.js
190 silly doSerial global-link 28
191 silly doParallel update-linked 28
192 silly doSerial install 28
193 silly install @prisma/cli@2.9.0
194 info lifecycle @prisma/cli@2.9.0~install: @prisma/cli@2.9.0
195 verbose lifecycle @prisma/cli@2.9.0~install: unsafe-perm in lifecycle true
196 verbose lifecycle @prisma/cli@2.9.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli/node_modules/.bin:/Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
197 verbose lifecycle @prisma/cli@2.9.0~install: CWD: /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/@prisma/cli
198 silly lifecycle @prisma/cli@2.9.0~install: Args: [ '-c', 'node download-build/index.js' ]
199 silly lifecycle @prisma/cli@2.9.0~install: Returned: code: 1  signal: null
200 info lifecycle @prisma/cli@2.9.0~install: Failed to exec install script
201 verbose unlock done using /Users/alexander/.npm/_locks/staging-89234ed43674be08.lock for /Users/alexander/src/github/weighing.machine/weighing-machine-1/node_modules/.staging
202 silly saveTree weighing-machine-1@1.0.0
202 silly saveTree └── @prisma/cli@2.9.0
203 warn weighing-machine-1@1.0.0 No description
204 warn weighing-machine-1@1.0.0 No repository field.
205 verbose stack Error: @prisma/cli@2.9.0 install: `node download-build/index.js`
205 verbose stack Exit status 1
205 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
205 verbose stack     at emitTwo (events.js:126:13)
205 verbose stack     at EventEmitter.emit (events.js:214:7)
205 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
205 verbose stack     at emitTwo (events.js:126:13)
205 verbose stack     at ChildProcess.emit (events.js:214:7)
205 verbose stack     at maybeClose (internal/child_process.js:925:16)
205 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
206 verbose pkgid @prisma/cli@2.9.0
207 verbose cwd /Users/alexander/src/github/weighing.machine/weighing-machine-1
208 verbose Darwin 19.6.0
209 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@prisma/cli" "--save-dev"
210 verbose node v8.9.4
211 verbose npm  v5.6.0
212 error code ELIFECYCLE
213 error errno 1
214 error @prisma/cli@2.9.0 install: `node download-build/index.js`
214 error Exit status 1
215 error Failed at the @prisma/cli@2.9.0 install script.
215 error This is probably not a problem with npm. There is likely additional logging output above.
216 verbose exit [ 1, true ]

```

**Comment by pantharshit00** [comment]
Hey @AlexSenchenko 

Can you please try again with a newer node js version? 

Looks like you are using node js version 8 which has reached it end of life earlier this year: https://blog.risingstack.com/update-nodejs-8-end-of-life-no-support/

**Comment by Jolg42** [comment]
Indeed Prisma dropped support for Node 8 and requires Node 10 (or newer) see https://github.com/prisma/prisma/blob/master/src/packages/client/package.json#L25

Unfortunately npm only outputs a warning during install, while yarn does a proper error.

We will check how we can improve that but in any case you will need to switch to a newer version od Node, I would recommended the latest LTS which is Node 12.

**Comment by janpio** [comment]
I don't see a warning from Npm in the output that @AlexSenchenko posted above @Jolg42.

**Comment by AlexSenchenko** [comment]
@janpio @Jolg42 @pantharshit00 npm output was not really descriptive.
As you can see above not output the above node version.
Yarn is better, display a direct message about node version incompatibility.

**Comment by janpio** [comment]
So what is wrong here @Jolg42 - our expectation what Npm does or something in Prisma maybe?

**Comment by Jolg42** [comment]
My guess is that `"install": "node download-build/index.js",` happens and breaks the flow before npm outputs the Node version warning.
