### ISSUE TITLE
Error in connector: Error querying the database: connection closed

### ISSUE THREAD

**Issue by vonphlpp** [prisma/prisma#3934]
**Bug description**
I'm using a PostgreSQL and from time to time I get the error:

```
Invalid prisma.user.findMany() invocation in
/Users/.../Desktop/prisma/server/src/graphql/User/queries/trendyNewUser.ts:10:26
  Error in connector: Error querying the database: connection closed
    at $w.request (/Users/.../Desktop/prisma/server/node_modules/@prisma/client/runtime/src/runtime/getPrismaClient.ts:1270:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

If I'm waiting 2s and make the same request it is working fine.

**How to reproduce**

The error occurs from time to time for no apparent reason. 

**Prisma information**

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["atomicNumberOperations"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

**Environment & setup**
- Node.js version: v12.18.3
- Prisma version: 2.9.0 (same with 2.8.0)
- @nexus/schema: 0.16.0

**Comment by pantharshit00** [comment]
@vonphlpp 

Can you please make sure you are not calling `prisma.disconnect` after some requests. Also, please sure you are not initializing Prisma every request.

If you can share a part of your codebase, that would be very helpful in reproducing this problem.

**Comment by vonphlpp** [comment]
Thanks for the answer. Again this error happens really random on any query from time to time.

_context.ts_
```
import { PrismaClient, PrismaClientOptions } from '@prisma/client'
import { PubSub } from 'graphql-yoga'
import { PrismaDelete, onDeleteArgs } from '@paljs/plugins'

class Prisma extends PrismaClient {
  constructor(options?: PrismaClientOptions) {
    super(options)
  }

  async onDelete(args: onDeleteArgs) {
    const prismaDelete = new PrismaDelete(this)
    await prismaDelete.onDelete(args)
  }
}

export const prisma = new PrismaClient({
  datasources: {
    db: {
      url: process.env.DATABASE_URL,
    },
  },
})

export const pubsub = new PubSub()

export interface Context {
  prisma: PrismaClient
  request: any
  pubsub: PubSub
  select: any
}

export function createContext(request: any): Context {
  return { prisma, request, pubsub, select: {} }
}

```
I tried it without prisma.connect and prisma.disconnect. 
_server.ts_
```
import { GraphQLServer } from 'graphql-yoga'
import { schema } from './nexusSchema'

import { returnRefreshToken } from './utils/returnRefreshToken'
import { createContext, prisma } from './context'

const compression = require('compression')
const cookieParser = require('cookie-parser')
const cors = require('cors')

async function main() {
  await prisma.$connect()

  const server = new GraphQLServer({
    schema,
    context: (request) => createContext(request),
  })

server.express.use(
    cors({
      origin: process.env.ORIGIN,
      credentials: true,
    }),
  )

  server.express.post('/refresh_token', cookieParser(), async (req, res) => {
    returnRefreshToken(req, res, prisma)
  })

  server.express.use(compression())

  server.start(
    {
      port: process.env.PORT || 4000,
      cors: false,
      subscriptions: {
        onConnect: (_: any, ws: any) => {
          return ws.upgradeReq.headers
        },
      },
    },
    () => {
      console.log('🚀 Server ready at: http://localhost:4000 ⭐️')
    },
  )
}

main()
  .catch((e) => {
    console.log(e)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
```
on example Query:
```
import { queryField } from '@nexus/schema'
import { getOrderByTime } from '../../../utils/orderByTime'

export const trendyNewUsers = queryField('trendyNewUsers', {
  type: 'User',
  list: true,
  resolve: async (_parent, args: any, { prisma, select }) => {
    const lastMonth = getOrderByTime(90)
    return prisma.user.findMany({
      take: 10,
      orderBy: {
        totalLike: 'desc',
      },
      where: {
        createdAt: {
          gt: lastMonth,
        },
      },
      ...select,
    })
  },
})
```
_nexusSchema.ts_
```
export const schema = makeSchema({
  types: [types],
  plugins: [paljs()],
  outputs: {
    schema: __dirname + '/generated/schema.graphql',
    typegen: __dirname + '/generated/nexus.ts',
  },
  typegenAutoConfig: {
    sources: [
      {
        source: require.resolve('./context'),
        alias: 'Context',
      },
    ],
    contextType: 'Context.Context',
  },
})
```

**Comment by pantharshit00** [comment]
@vonphlpp That looks pretty alright. Can I know where your database is hosted and what is your connection limit? 

By default prisma will spawn a pool that will have `num_of_physical_cps * 2 + 1` max connections. You should make sure that is not above your database limit.

**Comment by vonphlpp** [comment]
I'm using the free hobby dev from Heroku (in development)

**Comment by pantharshit00** [comment]
Try limiting the connections to 5 using `?connection_limit=5` at the end of your connection string.

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
