### ISSUE TITLE
can not reach a database server when use three times nested query 

### ISSUE THREAD

**Issue by Q00** [prisma/prisma#3959]
## Bug description

```typescript
   await prisma.user.findMany({
      select: {
        userColumn: {
          select: {
            column: {
              select: {
                stamp: true,
              },
            },
          },
        },
      },
    }),
```

it causes database un reachable error.

```shell
Gf [Error]: 
Invalid `prisma.user.findMany()` invocation in
/Users/kyu/Desktop/hakhak/hakhak/prisma/getUserBoard.ts:47:23


  Can't reach database server at `hakhak-production.cjtxpo0ndrpb.ap-northeast-2.rds.amazonaws.com`:`7645`

Please make sure your database server is running at `my database url: port`.
    at $w.request (/Users/kyu/Desktop/hakhak/hakhak/node_modules/@prisma/client/runtime/src/runtime/getPrismaClient.ts:1258:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P1001',
  clientVersion: '2.9.0',
  meta: {
    database_host: 'my database url',
    database_port: port
  }
}
```

But when I delete one of nested queries, it works

![image](https://user-images.githubusercontent.com/31264094/96362189-8c1d5100-1166-11eb-9c7a-8a211d5922f8.png)

like this.

```typescript
await prisma.user.findMany({
      select: {
        userColumn: {
          select: {
            column: true,
          },
        },
      },
    }),
```
And it works.

I think my database server can afford to query three times nested query.

What can I do?

my database structure is like below

user : userColumn = 1: n
userColumn : Column = n : 1
Column. : stamp = 1: n

## How to reproduce

use ts-node to exceute test.ts file

## Prisma information

    "@prisma/client": "2.9.0",
    "@prisma/engine-core": "^2.0.0-beta.3",
    "@prisma/generator-helper": "^2.0.0-beta.3",

## Environment & setup

- OS: Mac os
- Database: PostgreSQL
- Node.js version: v12.16.2
- Prisma version: 2.9.0

```

```

**Comment by pantharshit00** [comment]
Hello,

Sorry for the late reply here? Can you please try this again with `2.10` release. If you can still reproduce this, please share your schema with us so that we can try a reproduction. Thanks!

**Comment by pantharshit00** [comment]
Closing due to inactivity.
