### ISSUE TITLE
Native Types Postgres: prisma.types.create() with Decimal[] results in runtime error

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4052]
## Bug description

`prisma.types.create()` with `Decimal[]` in Postgres results in runtime error

## How to reproduce

```prisma
model types {
  dl Decimal[] @db.Numeric(65, 30)
}
```

```ts
import { PrismaClient, Decimal } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {
  await prisma.$connect()
  await prisma.types.create({
    dl: new Decimal(0) // in Schema, dl Decimal[] @db.Numeric(65, 30)
  })
})
```

```
TypeError: arg.inputTypes is not iterable
    at valueToArg (/Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:14572:31)
    at /Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:14753:17
    at Array.reduce (<anonymous>)
    at objectToArgs (/Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:14730:28)
    at tryInferArgs (/Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:14641:40)
    at valueToArg (/Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:14573:16)
    at /Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:14753:17
    at Array.reduce (<anonymous>)
    at objectToArgs (/Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:14730:28)
    at tryInferArgs (/Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:14641:40) {
  clientVersion: '2.10.0-dev.58'
}
```

## Expected behavior

Creating lists of decimals should work.

## Environment & setup

```
Environment variables loaded from ./prisma/.env
@prisma/cli          : 2.10.0-dev.74
@prisma/client       : 2.10.0-dev.58
Current platform     : darwin
Query Engine         : query-engine 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.304.0
Preview Features     : nativeTypes
```

**Comment by timsuchanek** [comment]
This was fixed in `2.10.0`
