### ISSUE TITLE
Native Types Postgres: Creating a record with empty arrays for field types json[], jsonb[]  not working

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4053]
## Bug description

Right now you can't create a field with `json[]`, and `jsonb[]` in postgres.

## How to reproduce

```sql
create table types (
  jsonList json[],
  jsonbList jsonb[]
);
```

```sh
npx @prisma/cli@dev introspect
```

```prisma
model types {
  jsonlist                Json[]     @db.Json
  jsonblist               Json[]     @db.JsonB
}
```

```
npx @prisma/cli@dev generate
```

```ts
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {
  await prisma.$connect()
  await prisma.types.create({
    data: {
      jsonlist: [],
      jsonblist: []
    }
  })
}


main()
  .catch((err) => {
    console.error(err)
  })
  .finally(() => {
    prisma.$disconnect()
  })
```

```
PrismaClientKnownRequestError2: 
Invalid `prisma.types.create()` invocation in
/Users/m/Go/src/github.com/prisma/qa-native-types/index.ts:6:22

  2 const prisma = new PrismaClient()
  3 
  4 async function main() {
  5   await prisma.$connect()
→ 6   await prisma.types.create(
  Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOnetypes.data.typesCreateInput.jsonlist`: Value types mismatch. Have: String("[]"), want: Object(typesCreatejsonlistInput), Query parsing/validation error at `Mutation.createOnetypes.data.typesCreateInput.jsonlist`: Value types mismatch. Have: String("[]"), want: Json]` at `Mutation.createOnetypes.data.typesCreateInput.jsonlist`
    at PrismaClientFetcher.request (/Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:15871:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2009',
  clientVersion: '2.10.0-dev.58',
  meta: {
    query_validation_error: 'Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOnetypes.data.typesCreateInput.jsonlist`: Value types mismatch. Have: String("[]"), want: Object(typesCreatejsonlistInput), Query parsing/validation error at `Mutation.createOnetypes.data.typesCreateInput.jsonlist`: Value types mismatch. Have: String("[]"), want: Json]',
    query_position: 'Mutation.createOnetypes.data.typesCreateInput.jsonlist'
  }
}
```

## Expected behavior

Should work.

## Environment & setup

```
Environment variables loaded from ./prisma/.env
@prisma/cli          : 2.10.0-dev.74
@prisma/client       : 2.10.0-dev.58
Current platform     : darwin
Query Engine         : query-engine 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.304.0
Preview Features     : nativeTypes
```

**Comment by dpetrick** [comment]
Findings: This is entirely the clients issue. The encoding is most likely wrong: If the client doesn't send it in this format on the GQL layer (https://github.com/prisma/prisma-engines/pull/1354/files#diff-75b6d96ece3b54882a54bb29dbe12f1c0c3230024573d1b619ac83fae3c62247R1) then it fails with the above error. The reason is that the GQL parser we use craps out if the escaping isn't on point, causing list values to be parsed extremely weirdly.
