### ISSUE TITLE
Native Types Postgres: `bit` is mapped to `String` in the generated client, but expects a 1 or 0 in query engine

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4055]
## Bug description

In Prisma+Postgres `prisma.users.create({ data: { bitField: "foo" }})` is not a compile time / type error, but a runtime error (bit type 0 or 1). It doesn't need to be a runtime error if we narrow the type in Typescript.

## How to reproduce

```sql
create table types (
  optionalBit bit,
  requiredBit bit not null,
);
```

```sh
npx @prisma/cli@dev introspect
```

```prisma
model types {
  optionalbit             String?    @db.Bit(1)
  requiredbit             String     @db.Bit(1)
}
```

```ts
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {
  await prisma.$connect()
  await prisma.types.create({
    data: {
      optionalbit: "foo",
      requiredbit: "bar" 
    },
  })
}

main()
  .catch((err) => {
    console.error(err)
  })
  .finally(() => {
    prisma.$disconnect()
  })
```

```
PrismaClientUnknownRequestError2: 
Invalid `prisma.types.create()` invocation in
/Users/m/Go/src/github.com/prisma/qa-native-types/index.ts:6:22

  2 const prisma = new PrismaClient()
  3 
  4 async function main() {
  5   await prisma.$connect()
→ 6   await prisma.types.create(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(17), cause: Some(Error { kind: ConversionError("Unexpected character for bits input. Expected only 1 and 0."), original_code: None, original_message: None }) }) })
    at PrismaClientFetcher.request (/Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:15875:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.10.0-dev.58'
}
```

## Expected behavior

I personally think this should be a compile-time error since we can narrow the Typescript type to `Array<1|0>`.

## Environment & setup

```
Environment variables loaded from ./prisma/.env
@prisma/cli          : 2.10.0-dev.74
@prisma/client       : 2.10.0-dev.58
Current platform     : darwin
Query Engine         : query-engine 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.304.0
Preview Features     : nativeTypes
```

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
