### ISSUE TITLE
Native Types Postgres: Consider narrowing the bit type to only allow 0 or 1

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4059]
## Bug description

The `bit` type only allows 1's and 0's, but the bit type in Typescript allows any string.

## How to reproduce

```sql
create table types (
  optionalBit bit,
  requiredBit bit not null,
  bitList bit[]
);
```

```sh
npx @prisma/cli@dev introspect
```

```prisma
model types {
  optionalbit             String?    @db.Bit(1)
  requiredbit             String     @db.Bit(1)
  bitlist                 String[]   @db.Bit(1)
}
```

```
npx @prisma/cli@dev generate
```

```js
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {
  await prisma.$connect()
  await prisma.types.create({
    data: {
      optionalbit: "foo",
      requiredbit: "foo",
      bitlist: ["foo"]
    }
  })
}

main()
  .catch((err) => {
    console.error(err)
  })
  .finally(() => {
    prisma.$disconnect()
  })
```

Results in a Runtime error:

```jsx
./node_modules/.bin/ts-node index.ts
PrismaClientUnknownRequestError2: 
Invalid `prisma.types.create()` invocation in
/Users/m/Go/src/github.com/prisma/qa-native-types/index.ts:6:22

  2 const prisma = new PrismaClient()
  3 
  4 async function main() {
  5   await prisma.$connect()
→ 6   await prisma.types.create(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(18), cause: Some(Error(Parser(InvalidLength { expected: Any([36, 32]), found: 4 }))) }) })
    at PrismaClientFetcher.request (/Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:15875:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.10.0-dev.58'
}
```

## Expected behavior

Compile time error would be nice. One possible solution is if we narrow the type to `1|0` or `Array<1|0>` for bit(n) where n > 1.

## Environment & setup

```
Environment variables loaded from ./prisma/.env
@prisma/cli          : 2.10.0-dev.74
@prisma/client       : 2.10.0-dev.58
Current platform     : darwin
Query Engine         : query-engine 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.304.0
Preview Features     : nativeTypes
```

**Comment by matthewmueller** [comment]
Duplicate of: https://github.com/prisma/prisma/issues/4055
