### ISSUE TITLE
Postgres Native Types: Improve error when `uuid` is invalid

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4060]
## Bug description

`uuid` accepts a string, but returns this cryptic error if your length is not 32 or 36 characters long.

## How to reproduce

```sql
create table types (
  optionalUuid uuid,
  requiredUuid uuid not null,
  uuidList uuid[]
);
```

```sh
npx @prisma/cli@dev introspect
```

```prisma
model types {
  optionaluuid            String?    @db.Uuid
  requireduuid            String     @db.Uuid
  uuidlist                String[]   @db.Uuid
}
```

```
npx @prisma/cli@dev generate
```

```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

async function main() {
  await prisma.$connect()
  await prisma.types.create({
    data: {
      optionaluuid: null || 'foo',
      requireduuid: 'bar',
      uuidlist: ['baz'],
    },
  })
}

main()
  .catch((err) => {
    console.error(err)
  })
  .finally(() => {
    prisma.$disconnect()
  })
```

```
./node_modules/.bin/ts-node index.ts
PrismaClientUnknownRequestError2: 
Invalid `prisma.types.create()` invocation in
/Users/m/Go/src/github.com/prisma/qa-native-types/index.ts:6:22

  2 const prisma = new PrismaClient()
  3 
  4 async function main() {
  5   await prisma.$connect()
→ 6   await prisma.types.create(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(18), cause: Some(Error(Parser(InvalidLength { expected: Any([36, 32]), found: 3 }))) }) })
    at PrismaClientFetcher.request (/Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:15875:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.10.0-dev.58'
}
```

## Expected behavior

I think a better error would be nice, I assumed that [36, 32] was an array of two bytes at first, rather than two optional lengths.

## Environment & setup

```
Environment variables loaded from ./prisma/.env
@prisma/cli          : 2.10.0-dev.74
@prisma/client       : 2.10.0-dev.58
Current platform     : darwin
Query Engine         : query-engine 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt 77abecc4840127ebdcc02b83ee1e2c9cc27009f2 (at ../../../../../.npm/_npx/6106/lib/node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.304.0
Preview Features     : nativeTypes
```

**Comment by Jolg42** [comment]
Note: I have seen this a few times in the last weeks in user logs.

**Comment by cagmz** [comment]
Got here via Google. Agreed, this error is cryptic. Thanks for raising this!

**Comment by mbrookson** [comment]
Is it correct that Prisma throws this error? [ULID](https://github.com/ulid/spec) is designed to be the same 128-bits as UUID so should work with the underlying database type, but using this means Prisma throws the error because it is validating the string length which is only 26 characters for ULID.
