### ISSUE TITLE
Postgres: Deleting a record that doesn't exist gives a bad error

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4072]
## Problem

The error we get back from `bigserial` ids it not very nice.

```ts
await prisma.types.delete({
  where: {
    bigserial: "non-existent id",
  },
})
```

```
PrismaClientKnownRequestError2: 
Invalid `prisma.types.delete()` invocation in
/Users/m/Go/src/github.com/prisma/qa-native-types/index.ts:72:30

   68 //   },
   69 // })
   70 
   71 console.log(
→  72   await prisma.types.delete(
  Query interpretation error. Error for binding '0': RecordNotFound("Record to delete does not exist.")
    at PrismaClientFetcher.request (/Users/m/Go/src/github.com/prisma/qa-native-types/node_modules/@prisma/client/runtime/index.js:15871:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2016',
  clientVersion: '2.10.0-dev.58',
  meta: {
    details: `Error for binding '0': RecordNotFound("Record to delete does not exist.")`
  }
}
```

## Suggested Solution

Remove

```
Query interpretation error. Error for binding '0': 
```

**Comment by stemis** [comment]
We have the same happening to us on MariaDB with ints:
Prisma version: `2.22.1`
```
const nonExistingId = 1234;
this._prisma.someModel.delete({
  where: {
    someId: nonExistingId,
  },
})
```

```
driver_1  | InterpretationError("Error for binding \'0\'", Some(QueryGraphBuilderError(RecordNotFound("Record to delete does not exist.")))) +41845ms
driver_1  | Error: Error occurred during query execution:
driver_1  | InterpretationError("Error for binding \'0\'", Some(QueryGraphBuilderError(RecordNotFound("Record to delete does not exist."))))
driver_1  |     at /usr/src/app/node_modules/@prisma/client/runtime/index.js:27757:19
driver_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by janpio** [comment]
Is this the full error message here @stemis? No `PrismaClientKnownRequestError` from Prisma Client? That would make this a pretty bad bug vs. just an inconvenient error message. Or should the deletion actually work but does not?

**Comment by stemis** [comment]
@janpio Yes this is the full error message. I do have to note that we are running the promise returned from delete via `prisma.$transaction()`. The delete should function as delete if exists for our use-case, but instead, it's throwing the above error if the record is not in the database.

Be happy to provide you with more information, please let me know what you need!

**Comment by janpio** [comment]
Ok, the `$transaction` makes this definitely a separate problem - can you open a new bug issue and fill the complete issue template? Maybe you can try to see if this happens in a new, minimal reproduction project you could put on Github and link to? That would be awesome.

**Comment by jake-chambers** [comment]
`deleteIfExists`?

**Comment by conspireagency** [comment]
Same issue here as well.  Feel like it shouldn't require a different method, just handle more gracefully?

**Comment by CDDelta** [comment]
Would be great to have something akin to the following for `delete()`:
```ts
await this.prisma.product.delete({
    where: {
      id: product.id,
    },
    rejectOnNotFound: false,
});
```
The current behavior makes things hard to deal with when trying to write idempotent functions for handling Stripe webhooks etc.

**Comment by jbdemonte** [comment]
is there any plan for this problem?

I'm also facing the case where I need to update an object, with nested object nullable, and to delete it, I will have to first read the db to known if the nested is set or not, to put `{ delete : true }` or `undefined` in the update nested property.


```typescript
this.prisma.client.update({
      where: { id: client.id },
      data: {
        name: client.name,
        // ...


        billingAddress:
           billingAddressData
               ? { upsert: { create: billingAddressData, update: billingAddressData } }
               : hasPreviousBillingAddress ? { delete: true } : undefined,


        shippingAddress:
           shippingAddressData
               ? { upsert: { create: shippingAddressData, update: shippingAddressData } }
               : hasPreviousShippingAddress ? { delete: true } : undefined,
      },
```

**Comment by steven-tey** [comment]
Facing a similar issue as well:
```
An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
```

Right now I'm catching it in a `try-catch` but would love to be able to have a similar function as `upsert` but for deletes :)

**Comment by saulpalv** [comment]
you can catch it until the `delete if not exists` is implemented is changed

```ts
await prisma.entity.delete({
  where: { id: product.id }
}).catch()
```

**Comment by joshribakoff-sm** [comment]
This also surfaces an error via https://www.npmjs.com/package/@quixo3/prisma-session-store when it tries to invalidate sessions that were already cleaned up. As others mentioned, it should really be idempotent like the underlying SQL operation IMO

**Comment by MaltesBytes** [comment]
# +1

**Comment by bahatron** [comment]
My work around for this was to change `delete` for `deleteMany`. Hope it helps

**Comment by ansh** [comment]
It is quite absurd this doesn't exist yet even though the issue was opened 3 years ago...

**Comment by MaltesBytes** [comment]
@ansh fr

**Comment by joshribakoff-sm** [comment]
@nogy21 I think that if you re-throw the error in `catch` it's for all intents and purposes the same as just not catching in the first place. My understanding is that whether your "catch" function throw an error / returns a rejected promise is what determines the outcome of the original promise. The way I think about it is anything returned or thrown from then/catch will "become" the original promise. If you don't want any rejected promise you should probably not throw any error in the catch handler

**Comment by notflip** [comment]
I'm using deleteMany for now, since the email field is unique, I know it's a safe operation

```
prisma.user.deleteMany({
    where: { email }
}),
```

**Comment by robmonday** [comment]
+1

**Comment by mustapha-mayo** [comment]
I am encountering the same annoying issue, when updating a record and passing `delete: { true },` for one of the relations.

**Comment by atumas-bananamilk** [comment]
Any update?
`deleteMany` is NOT a workaround because it doesn't work for `1 <-> 1` relations (works for `1 <-> N`)
`catch` is NOT a workaround because it doesn't work for nested / inline `delete`

**Comment by elie222** [comment]
> I am encountering the same annoying issue, when updating a record and passing `delete: { true },` for one of the relations.

Did you find a fix?

**Comment by Austin-Love** [comment]
Are there any workarounds available for one-to-one relationships?

**Comment by brunodmn** [comment]
> Are there any workarounds available for one-to-one relationships?

It ain't pretty but works for me:
```javascript
    this.prisma.user.delete({ where: { id: id } }).catch((e) => {
      if (e instanceof Prisma.PrismaClientKnownRequestError) {
        if (e.code === 'P2025') {
          throw new NotFoundException(`Can't find user with id ${id}`);
        }
      }
      throw e;
    });
```
On my relation, I use `onDelete: Cascade ` to also remove all relational registers.

references:
https://www.prisma.io/docs/reference/api-reference/error-reference
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions

**Comment by vendkura** [comment]
> @mindlid Based on the above comment, I'm using it as follows.
> 
> ```ts
> await prisma.entity.delete({ where: { id } }).catch(() => {
>   throw new NotFoundException(`Can't find item with id ${id}`);
> });
> ```

Thank you so much!  It works for me with prisma version 5.5.2

**Comment by LinusU** [comment]
> > @mindlid Based on the above comment, I'm using it as follows.
> > ```ts
> > await prisma.entity.delete({ where: { id } }).catch(() => {
> >   throw new NotFoundException(`Can't find item with id ${id}`);
> > });
> > ```
> 
> Thank you so much! It works for me with prisma version 5.5.2

I would recommend against using this approach, as now any error, even a temporary network issue, will be treated the same as "the database answered that there is no record with id $id"...

Checking for `P2025` or `P2016` seems like a better interim solution...

**Comment by atumas-bananamilk** [comment]
#9460 doesn't fully cover everything because `deleteMany` doesn't work for `1 <-> 1` relations.
If we could cover these cases (https://github.com/prisma/prisma/issues/4072#issuecomment-1557486529) without throwing an error it would be perfect.

It also doesn't matter if we know the error code, this `try <-> catch` doesn't work if we do a nested `delete`.
Ideally, when the record to delete doesn't exist it should just ignore that and proceed further.

**Comment by janpio** [comment]
Isn't that what #9460 suggests though @atumas-bananamilk?
If it is missing there, could you please leave a comment on it to add that aspect?
Afterwards I think we _could_ close this issue here and focus our effort on the `deleteIfExists` issues instead on this misnamed one.

**Comment by vuhieutopicus** [comment]
Hi. I come from the future, and this issue is still open for the next 2 years.

**Comment by LutherTS** [comment]
> Hi. I come from the future, and this issue is still open for the next 2 years.

true

**Comment by LutherTS** [comment]
That used to work smoothly when I was making my queries by hand in Postgres. Guess I'm gonna have to implement a workaround by searching at where I want to delete, then if there's a return I delete, and if there's none, I don't.

**Comment by LutherTS** [comment]
Here's the workaround I've just implemented in my project. Luckily for me, the checks were only necessary across two tables. 

`// This is all the BS I have to do because Prisma currently does not support "delete if exists"
  if (!userQuestion) {
    // First, I find if there is an incorrect userQuestion regarding only its userQuestion fields.
    let deletableUserQuestion =
      await findDeletablePreExistingUserQuestionAtUserIdAndQuestionId(
        verifiedUser.id,
        question.id
      );

    if (!deletableUserQuestion) {
      // Second, if that test is passed, I find if there is an incorrect userQuestion regarding only its answer fields.
      deletableUserQuestion =
        await findDeletablePreExistingUserQuestionAnswerAtUserIdAndQuestionId(
          verifiedUser.id,
          question.id
        );
    }

    if (deletableUserQuestion) {
      // Then, if either tests return such an incorrect userQuestion, then I delete it.
      await deleteUserQuestionAtUserIdAndQuestionId(
        verifiedUser.id,
        question.id
      );
    }
  }
  // And now that I know for sure any incorrect userQuestion at userId and questionId is deleted if it existed, that's when I can create or update the new userQuestion and answer I initially intended to simply create.`

**Comment by MaltesBytes** [comment]
@vuhieutopicus 
![image](https://github.com/prisma/prisma/assets/76700741/b9e5a14d-a293-4ab0-965a-53959c89405b)

**Comment by JeanPSF** [comment]
Any updates on this? 
I have a table who can be referenced in many other tables as fk/ids at the same time, and those tables also contains other relations, i can't update those nested relations, can't upsert them, can't delete them, not to talk about the amount of logic to determine if a object should be deleted or just updated because no operation on prisma works as described on the documentation. 

A(id: 1, b: B(id: refA(1),attrs: [C(id: refAFromB(1)),C(id: refAFromB(1))]), f: F(id: refA(1), g:G(id: refA(1), h:H(id: refAFromG(1)))),);

Until now, my work arounds were based on creating transactions to slowly fix some relations until it is okay to finally update my main entity, but i guess that's not only me based on the amount of comments here.
