### ISSUE TITLE
Cannot deploy on heroku from local server

### ISSUE THREAD

**Issue by georgemickael-b** [prisma/prisma#4076]
Prisma version :prisma/1.26.6 (linux-x64) node-v8.15.0
OS : linux mint 19 (ubuntu 18.04)

NOTE : database is printed to be as "Schema"  in logs. database name is d6idulpflfr3k9

Issue while deploying to heroku from local prisma server

Deployment worker initialization complete.
Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
[Debug] Initializing deployment worker for default$default
[Debug] Scheduling deployment for project default$default
Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
Encountered exception while applying migration. Rolling back. org.postgresql.util.PSQLException: ERROR: schema "d6idulpflfr3k9" does not exist
  Position: 24
org.postgresql.util.PSQLException: ERROR: schema "d6idulpflfr3k9" does not exist
  Position: 24
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
        at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
        at slick.jdbc.Invoker.first(Invoker.scala:30)
        at slick.jdbc.Invoker.first$(Invoker.scala:29)
        at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:15)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
        at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
Warning: Management API authentication is disabled. To protect your management server you should provide one (not both) of the environment variables 'CLUSTER_PUBLIC_KEY' (asymmetric, deprecated soon) or 'PRISMA_MANAGEMENT_API_JWT_SECRET' (symmetric JWT).
[Debug] Applied migration for project default$default

**Comment by pantharshit00** [comment]
@georgemickael-b 

Did you use our heroku integration?

If yes please paste the `PRISMA_CONFIG` variable from the config vars here?

Also, share your workspace slug as well(it is under prisma cloud settings)

**Comment by georgemickael-b** [comment]
> @georgemickael-b
> 
> Did you use our heroku integration?
> 
> If yes please paste the `PRISMA_CONFIG` variable from the config vars here?
> 
> Also, share your workspace slug as well(it is under prisma cloud settings)


I did not use prisma cloud. I was developing locally and tried to use heroku.

docker-compose.yml

`version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.26
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-23-21-128-35.compute-1.amazonaws.com
            database: d6idulpflfr3k9
            user: *******
            password: *******
            port: '5432'
            migrations: true
            ssl: true`

prisma.yml

`endpoint: http://localhost:4466
datamodel: datamodel.prisma

generate:
  - generator: javascript-client
    output: ./generated/prisma-client/`

datamodel.prisma
`type User {
  id: ID! @unique
  name: String!
}
`

**Comment by pantharshit00** [comment]
@georgemickael-b 

Here are some instructions for deploying prisma to heroku. Please try to deploy using them: https://github.com/dpetrick/prisma-heroku

**Comment by georgemickael-b** [comment]
> @georgemickael-b
> 
> Here are some instructions for deploying prisma to heroku. Please try to deploy using them: https://github.com/dpetrick/prisma-heroku

I did not use heroku for  prisma server. I used local dev server. 
I used only postgres db from heroku (external database)

**Comment by StefTriv71** [comment]
@georgemickael-b Are you still having this issue? I just ran into today, while yesterday was working just fine and I did not touch nor update anything.
