### ISSUE TITLE
All Queries Break on 1.27 and 1.27.1

### ISSUE THREAD

**Issue by LawJolla** [prisma/prisma#4094]
**Describe the bug**
```
query {
  [any Query node] {
     id
     ...
  }
}
```

Returns  (Where "Vehicle" is the node)
```
2019-02-24T18:50:26.183701+00:00 app[web.1]: org.postgresql.util.PSQLException: ERROR: relation "d5jb4orrv4h617.Vehicle" does not exist
2019-02-24T18:50:26.183728+00:00 app[web.1]:   Position: 26
2019-02-24T18:50:26.183824+00:00 app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
2019-02-24T18:50:26.183895+00:00 app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
2019-02-24T18:50:26.183966+00:00 app[web.1]: 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
2019-02-24T18:50:26.184050+00:00 app[web.1]: 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
2019-02-24T18:50:26.184113+00:00 app[web.1]: 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
2019-02-24T18:50:26.184178+00:00 app[web.1]: 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
2019-02-24T18:50:26.184258+00:00 app[web.1]: 	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
2019-02-24T18:50:26.184323+00:00 app[web.1]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
2019-02-24T18:50:26.184392+00:00 app[web.1]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
2019-02-24T18:50:26.184463+00:00 app[web.1]: 	at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$queryToDBIO$1(SharedSlickExtensions.scala:17)
2019-02-24T18:50:26.184528+00:00 app[web.1]: 	at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$jooqToDBIO$1(SharedSlickExtensions.scala:56)
2019-02-24T18:50:26.184599+00:00 app[web.1]: 	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
2019-02-24T18:50:26.184662+00:00 app[web.1]: 	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
2019-02-24T18:50:26.184724+00:00 app[web.1]: 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
2019-02-24T18:50:26.184790+00:00 app[web.1]: 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
2019-02-24T18:50:26.184850+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-02-24T18:50:26.184911+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-02-24T18:50:26.184974+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:748)
2019-02-24T18:50:26.195753+00:00 app[web.1]: {"key":"error/unhandled","requestId":"local:cjsj9qb3900060841gyzn55im","clientId":"wk_v2_server$dev","payload":{"exception":"org.postgresql.util.PSQLException: ERROR: relation \"d5jb4orrv4h617.Vehicle\" does not exist\n  Position: 26","query":"{\n  vehicles {\n    id\n  }\n}\n","variables":"{}","code":"0","stack_trace":"org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)\\n org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)\\n org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)\\n org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)\\n org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)\\n org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)\\n org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)\\n com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)\\n com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)\\n com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$queryToDBIO$1(SharedSlickExtensions.scala:17)\\n com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$jooqToDBIO$1(SharedSlickExtensions.scala:56)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)\\n slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)\\n slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)\\n java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n java.lang.Thread.run(Thread.java:748)","message":"ERROR: relation \"d5jb4orrv4h617.Vehicle\" does not exist\n  Position: 26"}}
```
**To Reproduce**
Used Prisma's Heroku deployment.  Upgraded the container from 1.26.4 to 1.27.0 and 1.27.1.  Ran any query and get the above error.

Rolling back to 1.26.4 fixes all errors.

**Expected behavior**
Queries to return without errors.

**Screenshots**
<img width="1050" alt="image 2019-02-24 at 12 00 38 pm" src="https://user-images.githubusercontent.com/17485128/53303789-d46a5b80-382b-11e9-8740-6e47cac7ad59.png">

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.27.1
 - `prisma` CLI: prisma/1.27.0 (darwin-x64) node-v11.10.0`]
 - OS: MacOS Mojave 

Could be related to #4093 or #4086

Thanks for the help!

**Comment by pantharshit00** [comment]
Hi @LawJolla 

Can you please share your datamodel with us? I am unable to reproduce this issue right now. I also tried to upgrade one of my current projects but all of them are working fine right now.

**Comment by do4gr** [comment]
We released a fix for a Postgres issue that looks similar to this one earlier today. Could re-check whether the latest release 1.27.2 fixes your problem?

**Comment by LawJolla** [comment]
Hi @do4gr ,

I tried 1.27.3 and can confirm the fix.  Thanks so much!!
