### ISSUE TITLE
Error: [/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\str\mod.rs:1942:47] begin <= end (1 <= 0) when slicing `N` 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4102]
Command: `prisma introspect`
Version: `2.10.0`
Binary Version: `af1ae11a423edfb5d24092a85be11fa77c5e499c`
Report: https://prisma-errors.netlify.app/report/11861 
OS: `x64 win32 10.0.18363`

JS Stacktrace:
```
Error: [/rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\src\libcore\str\mod.rs:1942:47] begin <= end (1 <= 0) when slicing `N`
    at ChildProcess.<anonymous> (G:\apps\next\sufacturaweb\node_modules\@prisma\cli\build\index.js:33:4762)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Rust Stacktrace:
```
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: BaseThreadInitThunk
  34: RtlUserThreadStart

```

**Comment by pantharshit00** [comment]
The underlying report doesn't have much information so I am unable to reproduce this.

**Comment by janpio** [comment]
No further reports of this.
