### ISSUE TITLE
Error: [introspection-engine/connectors/sql-introspection-connector/src/misc_helpers.rs:396:72] called `Option::unwrap()` on a `None` value 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4103]
Command: `prisma introspect`
Version: `2.10.0`
Binary Version: `af1ae11a423edfb5d24092a85be11fa77c5e499c`
Report: https://prisma-errors.netlify.app/report/11875 
OS: `x64 darwin 19.6.0`

JS Stacktrace:
```
Error: [introspection-engine/connectors/sql-introspection-connector/src/misc_helpers.rs:396:72] called `Option::unwrap()` on a `None` value
    at ChildProcess.<anonymous> (/Users/paulbottein/workspaces/sencrop/sencrop-api-nestjs/node_modules/@prisma/cli/build/index.js:33:4762)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic
   8: sql_introspection_connector::misc_helpers::calculate_scalar_field
   9: sql_introspection_connector::introspection::introspect
  10: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  14: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  16: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  17: futures::future::chain::Chain<A,B,C>::poll
  18: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  19: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  20: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  21: futures::task_impl::std::set
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  23: tokio::runtime::thread_pool::ThreadPool::block_on
  24: tokio::runtime::context::enter
  25: tokio::runtime::handle::Handle::enter
  26: introspection_engine::main
  27: std::rt::lang_start::{{closure}}
  28: std::rt::lang_start_internal
  29: _main

```

**Comment by pantharshit00** [comment]
Same as #4102 

> The underlying report doesn't have much information so I am unable to reproduce this.

**Comment by janpio** [comment]
Recent reports for 2.17

**Comment by pantharshit00** [comment]
I am unable to find new reports of the crash:
![image](https://user-images.githubusercontent.com/22195362/119278723-b8d99f80-bc44-11eb-9326-e44f9caa0971.png)


I am just going to close this.
