### ISSUE TITLE
error: Error: connect ECONNREFUSED 127.0.0.1:32274

### ISSUE THREAD

**Issue by mmiszy** [prisma/prisma#4106]
## Bug description

Automattic port negotiation fails.

```
DEBUG='*' node app.js
  loadEnv Error: Cannot find module '/usr/home/…/myproject/apps/api/prisma/package.json'
  loadEnv Require stack:
  loadEnv - /usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js
  loadEnv - /usr/home/…/myproject/node_modules/.prisma/client/index.js
  loadEnv - /usr/home/…/myproject/node_modules/@prisma/client/index.js
  loadEnv - /usr/home/…/myproject/apps/api/src/db.ts
  loadEnv - /usr/home/…/myproject/apps/api/src/index.ts
  loadEnv - /usr/home/…/myproject/apps/api/app.js
  loadEnv     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
  loadEnv     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
  loadEnv     at Module.require (internal/modules/cjs/loader.js:1044:19)
  loadEnv     at require (internal/modules/cjs/helpers.js:77:18)
  loadEnv     at /usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:72657:21
  loadEnv     at runMatcher (/usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:72501:25)
  loadEnv     at AsyncFunction.module2.exports.sync (/usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:72508:25)
  loadEnv     at findRootPkg (/usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:72653:39)
  loadEnv     at loadEnvFromProjectRoot (/usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:72669:25)
  loadEnv     at Object.tryLoadEnv2 (/usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:72585:25) +0ms
  loadEnv Environment variables loaded from /usr/home/…/myproject/apps/api/.env +30ms
  loadEnv Searching in /usr/home/…/myproject/apps/api/prisma/.env +13ms
  loadEnv Searching in null +1ms
  loadEnv Searching in ./prisma/.env +0ms
  prisma-client {
  prisma-client   engineConfig: {
  prisma-client     cwd: '/usr/home/…/myproject/apps/api/prisma',
  prisma-client     enableDebugLogs: false,
  prisma-client     enableEngineDebugMode: undefined,
  prisma-client     datamodelPath: '/usr/home/…/myproject/node_modules/.prisma/client/schema.prisma',
  prisma-client     prismaPath: undefined,
  prisma-client     engineEndpoint: undefined,
  prisma-client     generator: {
  prisma-client       name: 'client',
  prisma-client       provider: 'prisma-client-js',
  prisma-client       output: '/usr/home/…/myproject/node_modules/@prisma/client',
  prisma-client       binaryTargets: [],
  prisma-client       previewFeatures: [],
  prisma-client       config: {}
  prisma-client     },
  prisma-client     showColors: false,
  prisma-client     logLevel: 'info',
  prisma-client     logQueries: true,
  prisma-client     flags: [],
  prisma-client     clientVersion: '2.10.1',
  prisma-client     enableExperimental: [],
  prisma-client     useUds: undefined
  prisma-client   }
  prisma-client } +0ms
  plusX Execution permissions of /home/…/prisma-engines/target/debug/query-engine are fine +0ms
  engine port: undefined +0ms
  prisma-client prisma.queryRaw(SELECT 1=1 AS "database ready";, []) +1s
  prisma-client Prisma Client call: +0ms
  prisma-client Prisma Client call: +9ms
  prisma-client prisma.queryRaw({
  prisma-client   query: 'SELECT 1=1 AS "database ready";',
  prisma-client   parameters: {
  prisma-client     values: '[]',
  prisma-client     __prismaRawParamaters__: true
  prisma-client   }
  prisma-client }) +2ms
  prisma-client Generated request: +0ms
  prisma-client mutation {
  prisma-client   queryRaw(
  prisma-client     query: "SELECT 1=1 AS \"database ready\";"
  prisma-client     parameters: "[]"
  prisma-client   )
  prisma-client }
  prisma-client  +0ms
  engine {
  engine   cwd: '/usr/home/…/myproject/apps/api/prisma'
  engine } +148ms
  plusX Execution permissions of /home/…/prisma-engines/target/debug/query-engine are fine +149ms
  engine { flags: [ '--enable-raw-queries' ] } +1ms
getFreePort
true
  engine port: 32274 +2ms
  engine stdout {
  timestamp: 'Oct 30 17:41:49.442',
  level: 'INFO',
  fields: { message: 'Starting a postgresql pool with 25 connections.' },
  target: 'quaint::pooled'
} +145ms
prisma:info  Starting a postgresql pool with 25 connections.
  engine stdout {
  timestamp: 'Oct 30 17:41:49.536',
  level: 'INFO',
  fields: { message: 'Started http server' },
  target: 'query_engine::server'
} +93ms
prisma:info  Started http server
  engine stdout {
  timestamp: 'Oct 30 17:41:49.537',
  level: 'INFO',
  fields: { message: 'Encountered error during initialization:' },
  target: 'query_engine'
} +14ms
prisma:info  Encountered error during initialization:
  engine stderr {"is_panic":false,"message":"Operation not permitted (os error 1)","backtrace":"   0: <unknown>\n   1: <unknown>\n   2: <unknown>\n   3: <unknown>\n   4: <unknown>\n   5: <unknown>\n   6: <unknown>\n   7: <unknown>\n   8: <unknown>\n   9: <unknown>\n  10: <unknown>\n  11: <unknown>\n  12: <unknown>\n  13: <unknown>\n  14: <unknown>\n  15: <unknown>\n  16: <unknown>\n  17: <unknown>\n  18: <unknown>\n  19: <unknown>\n  20: <unknown>\n  21: <unknown>\n  22: <unknown>\n  23: <unknown>\n  24: <unknown>\n  25: <unknown>\n  26: <unknown>\n  27: <unknown>\n  28: <unknown>\n  29: <unknown>\n  30: <unknown>\n  31: <unknown>\n  32: <unknown>\n  33: <unknown>\n  34: <unknown>\n  35: <unknown>\n  36: <unknown>\n  37: <unknown>\n  38: <unknown>\n  39: <unknown>\n  40: <unknown>\n  41: <unknown>\n  42: <unknown>\n  43: <unknown>\n  44: <unknown>\n  45: <unknown>\n  46: <unknown>\n  47: <unknown>\n"} +1ms
  engine {
  engine   is_panic: false,
  engine   message: 'Operation not permitted (os error 1)',
  engine   backtrace: '   0: <unknown>\n' +
  engine     '   1: <unknown>\n' +
  engine     '   2: <unknown>\n' +
  engine     '   3: <unknown>\n' +
  engine     '   4: <unknown>\n' +
  engine     '   5: <unknown>\n' +
  engine     '   6: <unknown>\n' +
  engine     '   7: <unknown>\n' +
  engine     '   8: <unknown>\n' +
  engine     '   9: <unknown>\n' +
  engine     '  10: <unknown>\n' +
  engine     '  11: <unknown>\n' +
  engine     '  12: <unknown>\n' +
  engine     '  13: <unknown>\n' +
  engine     '  14: <unknown>\n' +
  engine     '  15: <unknown>\n' +
  engine     '  16: <unknown>\n' +
  engine     '  17: <unknown>\n' +
  engine     '  18: <unknown>\n' +
  engine     '  19: <unknown>\n' +
  engine     '  20: <unknown>\n' +
  engine     '  21: <unknown>\n' +
  engine     '  22: <unknown>\n' +
  engine     '  23: <unknown>\n' +
  engine     '  24: <unknown>\n' +
  engine     '  25: <unknown>\n' +
  engine     '  26: <unknown>\n' +
  engine     '  27: <unknown>\n' +
  engine     '  28: <unknown>\n' +
  engine     '  29: <unknown>\n' +
  engine     '  30: <unknown>\n' +
  engine     '  31: <unknown>\n' +
  engine     '  32: <unknown>\n' +
  engine     '  33: <unknown>\n' +
  engine     '  34: <unknown>\n' +
  engine     '  35: <unknown>\n' +
  engine     '  36: <unknown>\n' +
  engine     '  37: <unknown>\n' +
  engine     '  38: <unknown>\n' +
  engine     '  39: <unknown>\n' +
  engine     '  40: <unknown>\n' +
  engine     '  41: <unknown>\n' +
  engine     '  42: <unknown>\n' +
  engine     '  43: <unknown>\n' +
  engine     '  44: <unknown>\n' +
  engine     '  45: <unknown>\n' +
  engine     '  46: <unknown>\n' +
  engine     '  47: <unknown>\n'
  engine } +0ms
  plusX Execution permissions of /home/…/prisma-engines/target/debug/query-engine are fine +257ms
  engine Restart attempt 1. Waiting for backoff +19ms
  engine Restart attempt 1. Backoff done +0ms
  engine There is a child that still runs and we want to start again +1ms
  engine {
  engine   cwd: '/usr/home/…/myproject/apps/api/prisma'
  engine } +0ms
  plusX Execution permissions of /home/…/prisma-engines/target/debug/query-engine are fine +19ms
  engine { flags: [ '--enable-raw-queries' ] } +0ms
  engine port: 32310 +1ms
  engine {
  engine   error: Error: connect ECONNREFUSED 127.0.0.1:32274
  engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  engine     errno: 'ECONNREFUSED',
  engine     code: 'ECONNREFUSED',
  engine     syscall: 'connect',
  engine     address: '127.0.0.1',
  engine     port: 32274
  engine   }
  engine } +17ms
  prisma-client TypeError: Cannot read property 'padEnd' of undefined
  prisma-client     at Object.getErrorMessageWithLink (/usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:4255:32)
  prisma-client     at NodeEngine3.handleRequestError (/usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:27108:73)
  prisma-client     at /usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:27738:36
  prisma-client     at processTicksAndRejections (internal/process/task_queues.js:97:5)
  prisma-client     at PrismaClientFetcher.request (/usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:78514:24)
  prisma-client     at start (/usr/home/…/myproject/apps/api/src/index.ts:21:15) +297ms
TypeError: Cannot read property 'padEnd' of undefined
    at Object.getErrorMessageWithLink (/usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:4255:32)
    at NodeEngine3.handleRequestError (/usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:27108:73)
    at /usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:27738:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at PrismaClientFetcher.request (/usr/home/…/myproject/node_modules/@prisma/client/runtime/index.js:78514:24)
    at start (/usr/home/…/myproject/apps/api/src/index.ts:21:15) {
  clientVersion: '2.10.1'
}
```

## Environment & setup

- OS: FreeBSD 11
- Database: PostgreSQL
- Node.js version: 12.16.1
- Prisma version:

```
@prisma/cli          : 2.10.1
@prisma/client       : 2.10.1
Current platform     : freebsd11
Query Engine         : query-engine 7c763cfd26b25a7fbce04acba78750b90aa79c96 (at ../../../prisma-engines/target/debug/query-engine, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine     : migration-engine-cli 6fafbb461b7e0c140280a7794ed19a4f7035f577 (at ../../../prisma-engines/target/debug/migration-engine, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine : introspection-core 6fafbb461b7e0c140280a7794ed19a4f7035f577 (at ../../../prisma-engines/target/debug/introspection-engine, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary        : prisma-fmt 6fafbb461b7e0c140280a7794ed19a4f7035f577 (at ../../../prisma-engines/target/debug/prisma-fmt, resolved by PRISMA_FMT_BINARY)
Studio               : 0.304.0
```

**Comment by pantharshit00** [comment]
Hey @mmiszy 

Looks like you also opened https://github.com/prisma/prisma-client-js/issues/923 regarding this. 

As I said there, try using the Unix domain socket mode: https://github.com/prisma/prisma-client-js/issues/923#issuecomment-719875538

**Comment by pantharshit00** [comment]
Closing for now as we are not technically fully supporting FreeBSD at the moment(limited engineering bandwidth for that) and this problem is solved via UDS.
