### ISSUE TITLE
DateTime  @id breaks relations - feature or bug?

### ISSUE THREAD

**Issue by TomasMoskala** [prisma/prisma#4111]
## Bug description

DateTime  @id field on detail table breaks relation to master table

## How to reproduce
```
CREATE TABLE `aa_master` (
  `aa_master_id` INT NOT NULL AUTO_INCREMENT,
  `somedata` INT NULL,
PRIMARY KEY (`aa_master_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `aa_master` (`aa_master_id`, `somedata`) VALUES
(1, 1),
(2, 2);

CREATE TABLE `aa_detail` (
  `aa_detail_id` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_aa_master` INT NOT NULL,
  `detaildata` VARCHAR(10) NULL,
PRIMARY KEY (`aa_detail_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `aa_detail` ADD CONSTRAINT `fk_aa_detail_aa_master`
FOREIGN KEY (`id_aa_master`) REFERENCES `aa_master`(`aa_master_id`);

INSERT INTO `aa_detail` (`aa_detail_id`, `id_aa_master`, `detaildata`) VALUES
('2020-11-01 14:11:36', 2, 'bbbb'),
('2020-11-01 14:11:37', 2, 'cccc');


```

## Expected behavior

graphql nested results

## Prisma information

```
model aa_detail {
  aa_detail_id DateTime  @id @default(now())
  id_aa_master Int
  detaildata   String?
  aa_master    aa_master @relation(fields: [id_aa_master], references: [aa_master_id])

  @@index([id_aa_master], name: "fk_aa_detail_aa_master")
}

model aa_master {
  aa_master_id Int         @id @default(autoincrement())
  somedata     Int?
  aa_detail    aa_detail[]
}


```

## Environment & setup

- OS:  Windows10
- Database: MariaDB
- Node.js version: v14.13.0
- Prisma version:     "nexus-plugin-prisma": "^0.23.1",
Prisma CLI version: 2.10.0 (see below)

---

Works for 1 record only, then breaks
![image](https://user-images.githubusercontent.com/35471478/97808720-bf80d500-1c68-11eb-84d3-f119d666fd9c.png)
2 records without querying relation
![image](https://user-images.githubusercontent.com/35471478/97808527-c0653700-1c67-11eb-8d7c-d6cf2b391c61.png)
2 records with relation
![image](https://user-images.githubusercontent.com/35471478/97808556-edb1e500-1c67-11eb-941d-3074fd75580d.png)

ERRORS
``` 
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field aa_detail.aa_master.",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "aa",
        0,
        "aa_master"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field aa_detail.aa_master.",
            "    at completeValue (C:\\aa\\graphql-apollo-server\\node_modules\\graphql\\execution\\execute.js:561:13)",
            "    at C:\\aa\\graphql-apollo-server\\node_modules\\graphql\\execution\\execute.js:471:16",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
            "    at async Promise.all (index 2)",
            "    at async Promise.all (index 0)",
            "    at async Promise.all (index 0)"
          ]
        }
      }
    },
    {
      "message": "Cannot return null for non-nullable field aa_detail.aa_master.",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "aa",
        1,
        "aa_master"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field aa_detail.aa_master.",
            "    at completeValue (C:\\aa\\graphql-apollo-server\\node_modules\\graphql\\execution\\execute.js:561:13)",
            "    at C:\\aa\\graphql-apollo-server\\node_modules\\graphql\\execution\\execute.js:471:16",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
            "    at async Promise.all (index 2)",
            "    at async Promise.all (index 1)",
            "    at async Promise.all (index 0)"
          ]
        }
      }
    }
  ],
  "data": {
    "aa": [
      null,
      null
    ]
  }
}
```

```
export const Aa_master = objectType({
  name: 'aa_master',
  definition(t) {
    t.model.aa_master_id()
    t.model.somedata()
}})
export const Aa_detail = objectType({
  name: 'aa_detail',
  definition(t) {
    t.model.aa_detail_id()
    t.model.detaildata()
    t.model.aa_master()
}})

t.list.field('aa', {
  type: 'aa_detail',
  nullable: true,
  resolve: (_, __, ctx) => {
    return ctx.prisma.aa_detail.findMany({
      where: {detaildata: {not: null}},
      include: {aa_master: true}
    });
  }
})
```
package.json
```
  "devDependencies": {
    "@types/node": "12.12.42",
    "ts-node": "8.10.1",
    "ts-node-dev": "1.0.0-pre.44"
  },
  "dependencies": {
    "@apollo/client": "^3.2.5",
    "@nexus/schema": "^0.17.0",
    "@prisma/cli": "^2.10.0",
    "@prisma/client": "^2.10.0",
    "@types/bcrypt": "^3.0.0",
    "@types/jsonwebtoken": "^8.5.0",
    "@types/react": "^16.9.55",
    "apollo-client": "^2.6.10",
    "apollo-server": "^2.19.0",
    "bcrypt": "^5.0.0",
    "cross-fetch": "^3.0.6",
    "dotenv": "^8.2.0",
    "graphql": "^15.4.0",
    "jsonwebtoken": "^8.5.1",
    "nexus-plugin-prisma": "^0.23.1",
    "nodemailer": "^6.4.14",
    "react": "^17.0.1",
    "typescript": "^4.0.5"
  }

```
This setup does not produce the bug
```
  "dependencies": {
    "@apollo/client": "^3.1.3",
    "@nexus/schema": "0.13.1",
    "@types/bcrypt": "^3.0.0",
    "@types/jsonwebtoken": "^8.5.0",
    "@types/node-fetch": "2.5.7",
    "@types/react": "^16.9.46",
    "apollo-client": "^2.6.10",
    "apollo-server": "^2.15.1",
    "bcrypt": "^5.0.0",
    "cross-fetch": "^3.0.5",
    "dotenv": "^8.2.0",
    "graphql": "14.6.0",
    "jsonwebtoken": "^8.5.1",
    "nexus-plugin-prisma": "^0.17.0",
    "nodemailer": "^6.4.11",
    "react": "^16.13.1",
    "rxjs": "^6.6.3",
    "typescript": "^3.9.7"
  },
  "devDependencies": {
    "@types/node": "12.12.42",
    "ts-node": "8.10.1",
    "ts-node-dev": "1.0.0-pre.44"
  },

```

**Comment by pantharshit00** [comment]
Hey @TomasMoskala 

Sorry for the late reply here. Can you please try this again with 2.11 release? I remember we fixed a similar bug in that so this might be already addressed.

**Comment by TomasMoskala** [comment]
Not really. I tried 2.11 but I broke the whole project because I am using Nexus which is not supported from 2.0 higher

**Comment by jasonkuhrt** [comment]
> because I am using Nexus which is not supported from 2.0 higher

What version of Nexus are you using?

**Comment by TomasMoskala** [comment]
> > because I am using Nexus which is not supported from 2.0 higher
> 
> What version of Nexus are you using?

 "@nexus/schema": "^0.17.0", (see package.json) or should I find out somewhere else?

**Comment by jasonkuhrt** [comment]
> I tried 2.11 but I broke the whole project because I am using Nexus which is not supported from 2.0 higher

I am not sure what this means. Anyways you can Upgrade to `nexus@1.0` if you want, maybe that will help this too.

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
