### ISSUE TITLE
Prisma CLI generates the wrong endpoint and doesn't allow users to deploy!

### ISSUE THREAD

**Issue by hobz-** [prisma/prisma#4142]
**Describe the bug**
When using the Prisma CLI to init a project and generate the yml file, the endpoint is missing information. When the user then runs prisma deploy, an error is thrown: 

TypeError: Cannot read property 'split' of undefined
    at getWorkspaceFromPrivateOrigin (/Users/ferdinandismael/.nvm/versions/node/v10.15.0/lib/node_modules/prisma/node_modules/prisma-yml/src/utils/parseEndpoint.ts:20:79)
    at Object.parseEndpoint (/Users/ferdinandismael/.nvm/versions/node/v10.15.0/lib/node_modules/prisma/node_modules/prisma-yml/src/utils/parseEndpoint.ts:46:21)
    at PrismaDefinitionClass.get [as cluster] (/Users/ferdinandismael/.nvm/versions/node/v10.15.0/lib/node_modules/prisma/node_modules/prisma-yml/src/PrismaDefinition.ts:121:13)
    at PrismaDefinitionClass.getClusterName (/Users/ferdinandismael/.nvm/versions/node/v10.15.0/lib/node_modules/prisma/node_modules/prisma-yml/src/PrismaDefinition.ts:256:17)
    at PrismaDefinitionClass.validate (/Users/ferdinandismael/.nvm/versions/node/v10.15.0/lib/node_modules/prisma/node_modules/prisma-yml/src/PrismaDefinition.ts:127:30)
    at PrismaDefinitionClass.<anonymous> (/Users/ferdinandismael/.nvm/versions/node/v10.15.0/lib/node_modules/prisma/node_modules/prisma-yml/src/PrismaDefinition.ts:63:12)
    at step (/Users/ferdinandismael/.nvm/versions/node/v10.15.0/lib/node_modules/prisma/node_modules/prisma-yml/dist/PrismaDefinition.js:32:23)
    at Object.next (/Users/ferdinandismael/.nvm/versions/node/v10.15.0/lib/node_modules/prisma/node_modules/prisma-yml/dist/PrismaDefinition.js:13:53)
    at fulfilled (/Users/ferdinandismael/.nvm/versions/node/v10.15.0/lib/node_modules/prisma/node_modules/prisma-yml/dist/PrismaDefinition.js:4:58)
Exiting with code: 1

**To Reproduce**
1. npm install -g prisma
2. prisma init 
  - Important that no project name is specified. Use the CLI wizard to generate the files.
  - Select Demo Server
  - Choose a region (This could be the first place for an error? Us1 appears to be the endpoint, but the description includes us2. In the file the blows up, parseEndpoint.ts it looks for a public end point with either eu1 or us2 in it. The generated end point from here is us1. Not sure what is intended)
  - Don't create client
3. prisma deploy
4. Error is thrown. 😿 

**Expected behavior**
Expected that I could deploy & create my service.

**Resolution steps**
I was able to fix the problem by manually adding a workplace slug to my endpoint -> 

prisma init generates an end point such as: "https://us1.prisma.sh/josh-tes/dev"

It looks like the code is expecting a workplace slug. So I added it... ""https://us1.prisma.sh/josh-a1b2c3/josh-sick-fits/dev". I can then deploy no problem. This solves the problem. However, I'm not sure what the intended behaviour is, and whether I should need the slug... 

**Versions (please complete the following information):**
 - `prisma` CLI: [e.g. `prisma/1.28.0 node-v11.5`]
 - OS:  OS X High Sierra 10.13.6

**Comment by aisflat439** [comment]
Had the same issues today. Josh's solve worked for me as well. Just update the URL and all is well. 

prisma -v outputs
```
prisma/1.28.0 (linux-x64) node-v8.2.1
```

**Comment by timsuchanek** [comment]
Thanks for reporting! We released a patch and just fixed it. Let me know if you're still facing the issue.
