### ISSUE TITLE
Improve error message for foreign key constraints with uncheckedScalarInputs

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#4196]
## Bug description

Right now we get back an unknown request error, when you try to create a relationship with a record that doesn't exist.

I'm using `uncheckedScalarInputs`. Since we have less checks in place here, we should have better error messages when things go wrong.

## How to reproduce

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["nativeTypes", "uncheckedScalarInputs"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int    @id @default(autoincrement()) @db.Integer
  first String @db.Text
  last  String @db.Text
  posts Post[]
}

model Post {
  id       Int     @id @default(autoincrement()) @db.Integer
  title    String  @db.Text
  body     String  @db.Text
  userId   Int     @db.Integer
  user     User    @relation(fields: [userId], references: [id])
}
```

```ts
  const result = await prisma.post.create({
    data: {
      body: '',
      title: '',
      userId: 99999,
    },
  })
}
```

```
PrismaClientUnknownRequestError2: 
Invalid `prisma.post.create()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ForeignKeyConstraintViolation { constraint: Index("Post_userId_fkey") } })
    at PrismaClientFetcher.request (/Users/m/Go/src/github.com/prisma/qa/node_modules/@prisma/client/runtime/index.js:78627:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.11.0-dev.43'
}
```

## Expected behavior

I think we could do a better job here, something like:

```
ForeignKeyConstraintViolation on "userId" in the "post" model.

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ForeignKeyConstraintViolation { constraint: Index("Post_userId_fkey") } })
    at PrismaClientFetcher.request (/Users/m/Go/src/github.com/prisma/qa/node_modules/@prisma/client/runtime/index.js:78627:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.11.0-dev.43'
}
```

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version:

```
Environment variables loaded from /Users/m/Go/src/github.com/prisma/qa/.env
@prisma/cli          : 2.11.0-dev.43
@prisma/client       : 2.11.0-dev.43
Current platform     : darwin
Query Engine         : query-engine a624a6628b9e5e453bb8f8cb0460e233a3a97e62 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli a624a6628b9e5e453bb8f8cb0460e233a3a97e62 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core a624a6628b9e5e453bb8f8cb0460e233a3a97e62 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt a624a6628b9e5e453bb8f8cb0460e233a3a97e62 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.308.0
Preview Features     : nativeTypes, uncheckedScalarInputs
```

**Comment by pantharshit00** [comment]
Error is bit better in 2.21 but not perfect:
```
node:30900) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.post.create()` invocation:


  Foreign key constraint failed on the field: `Post_userId_fkey (index)`
    at cb (C:\Users\harshit\code\reproductions\issue-4196\node_modules\@prisma\client\runtime\index.js:34780:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at main (C:\Users\harshit\code\reproductions\issue-4196\main.ts:5:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:30900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins
ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodej
s.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:30900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Terminate batch job (Y/N)?
^C
```

**Comment by guicsou-lw** [comment]
Would be very great to have a specific error thrown here, today it appears that every FK error falls into the same error (ForeignKeyError) and we have to work with the error code inside this error (P2003, for Restrict delete/update)
