### ISSUE TITLE
Error following getting started tutorial (Field configuration to merge has duplicate field names)

### ISSUE THREAD

**Issue by Glitched** [prisma/prisma#4208]
**Describe the bug**
I'm getting an error when I try to follow the [getting started](https://www.prisma.io/docs/1.28/get-started/01-setting-up-prisma-existing-database-TYPESCRIPT-t003/) tutorial with my existing Postgres database. 

**To Reproduce**
1. `prisma init hello-world`
2. Here's what I input:

```
? Set up a new Prisma server or deploy to an existing server? Use existing database
? What kind of database do you want to deploy to? PostgreSQL
? Does your database contain existing data? Yes
? Enter database host: localhost
? Enter database port: 5432
? Enter database user: ryan
? Enter database password: hunter2
? Enter database name (the database includes the schema)
? Use SSL? No
? Please select the schema you want to introspect: public
```

**Expected behavior**
Prisma init to generate schema.
Here's a dump of the database I'm using:
[schema.sql.txt](https://github.com/prisma/prisma/files/2978645/schema.sql.txt)

**Screenshots**
N/A

**Versions (please complete the following information):**
 - Connector: Postgres 10.2
 - Prisma Server: N/A

 - `prisma` CLI: prisma/1.28.5 (darwin-x64) node-v11.9.0
 - OS: macOS Mojave
 - other dependencies: N/A

**Additional context**
Error trace:
```
Error: Field configuration to merge has duplicate field names.
    at /usr/local/lib/node_modules/prisma/node_modules/prisma-generate-schema/src/generator/generator.ts:571:17
    at Array.forEach (<anonymous>)
    at _loop_1 (/usr/local/lib/node_modules/prisma/node_modules/prisma-generate-schema/src/generator/generator.ts:567:29)
    at Function.FieldConfigUtils.merge (/usr/local/lib/node_modules/prisma/node_modules/prisma-generate-schema/dist/src/generator/generator.js:428:13)
    at ModelWhereInputGenerator.generateFields (/usr/local/lib/node_modules/prisma/node_modules/prisma-generate-schema/src/generator/default/query/modelWhereInputGenerator.ts:202:35)
    at fieldFunction (/usr/local/lib/node_modules/prisma/node_modules/prisma-generate-schema/src/generator/generator.ts:213:38)
    at resolveThunk (/usr/local/lib/node_modules/prisma/node_modules/graphql/type/definition.js:374:40)
    at defineInputFieldMap (/usr/local/lib/node_modules/prisma/node_modules/graphql/type/definition.js:857:18)
    at GraphQLInputObjectType.getFields (/usr/local/lib/node_modules/prisma/node_modules/graphql/type/definition.js:838:27)
    at typeMapReducer (/usr/local/lib/node_modules/prisma/node_modules/graphql/type/schema.js:302:61)
    at typeMapReducer (/usr/local/lib/node_modules/prisma/node_modules/graphql/type/schema.js:304:22)
    at typeMapReducer (/usr/local/lib/node_modules/prisma/node_modules/graphql/type/schema.js:304:22)
    at typeMapReducer (/usr/local/lib/node_modules/prisma/node_modules/graphql/type/schema.js:304:22)
    at typeMapReducer (/usr/local/lib/node_modules/prisma/node_modules/graphql/type/schema.js:304:22)
    at Array.reduce (<anonymous>)
    at typeMapReducer (/usr/local/lib/node_modules/prisma/node_modules/graphql/type/schema.js:275:38)
    at typeMapReducer (/usr/local/lib/node_modules/prisma/node_modules/graphql/type/schema.js:278:22)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/usr/local/lib/node_modules/prisma/node_modules/graphql/type/schema.js:108:28)
    at SchemaGenerator.generate (/usr/local/lib/node_modules/prisma/node_modules/prisma-generate-schema/src/generator/default/schemaGenerator.ts:10:12)
    at generateCRUDSchema (/usr/local/lib/node_modules/prisma/node_modules/prisma-generate-schema/src/index.ts:35:48)
    at Object.generateCRUDSchemaString [as default] (/usr/local/lib/node_modules/prisma/node_modules/prisma-generate-schema/src/index.ts:64:22)
    at GenereateCommand.<anonymous> (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/src/commands/generate/generate.ts:83:48)
    at step (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/generate/generate.js:45:23)
    at Object.next (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/generate/generate.js:26:53)
    at fulfilled (/usr/local/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/generate/generate.js:17:58)
Exiting with code: 1
```

**Comment by ejoebstl** [comment]
Adressed in #4304, thanks for the bug report!
