### ISSUE TITLE
Error: [introspection-engine/connectors/sql-introspection-connector/src/misc_helpers.rs:417:72] called `Option::unwrap()` on a `None` value 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4249]
Command: `prisma introspect`
Version: `2.11.0`
Binary Version: `58369335532e47bdcec77a2f1e7c1fb83a463918`
Report: https://prisma-errors.netlify.app/report/12035 
OS: `x64 darwin 19.6.0`

JS Stacktrace:
```
Error: [introspection-engine/connectors/sql-introspection-connector/src/misc_helpers.rs:417:72] called `Option::unwrap()` on a `None` value
    at ChildProcess.<anonymous> (/Users/paulbottein/workspaces/sencrop/sencrop-api-nestjs/node_modules/@prisma/cli/build/index.js:4947:28)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_handler::{{closure}}
   6: std::sys_common::backtrace::__rust_end_short_backtrace
   7: _rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic
  10: sql_introspection_connector::misc_helpers::calculate_scalar_field
  11: sql_introspection_connector::introspection::introspect
  12: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  16: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  17: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  18: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  19: futures::future::chain::Chain<A,B,C>::poll
  20: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  21: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  22: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  23: futures::task_impl::std::set
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  25: tokio::runtime::thread_pool::ThreadPool::block_on
  26: tokio::runtime::context::enter
  27: tokio::runtime::handle::Handle::enter
  28: introspection_engine::main
  29: std::sys_common::backtrace::__rust_begin_short_backtrace
  30: std::rt::lang_start::{{closure}}
  31: std::rt::lang_start_internal
  32: _main

```

**Comment by do4gr** [comment]
I just checked and this was erroring because at that time introspection did not handle the case where the sql-schema-describer did not return a native type for a column. This is now handled and the error cannot occur anymore.
