### ISSUE TITLE
Query result was required, but an empty Object((Weak)) was returned instead

### ISSUE THREAD

**Issue by Stevenje** [prisma/prisma#4252]
## Bug description

I'm getting this error a lot when upsert-ing to Postgresql. Happens on different models. Certain bits of data seem to cause it to have this error although I can't figure out why. Majority of items upsert fine, but 7 out of 100 say will fail with this error. 

```
PrismaClientUnknownRequestError2: 
Invalid `prisma.keyword.upsert()` invocation:

  Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead.
    at PrismaClientFetcher.request (/Users/xx/Documents/boilerplate/node_modules/@prisma/client/runtime/index.js:78786:15)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at /Users/xx/Documents/boilerplate/packages/xx/lib/xxx.ts:424:25 {
  clientVersion: '2.11.0'
}
```

## How to reproduce

``` ts
              await prisma.keyword.upsert({
                create: {
                  id: item.keywordId,
                  bid: keywordStatus.bid,
                  state: keywordStatus.state,
                  keywordText: item.keywordText,
                  matchType: item.matchType,
                  updated: new Date(),
                  Campaign: { connect: { id: item.campaignId } },
                },
                update: {
                  bid: keywordStatus.bid,
                  state: keywordStatus.state,
                },
                where: { id: item.keywordId },
              });
```

Data Example 1: 
```
{
  keywordId: 35141915569505,
  cost: 0,
  attributedSales1d: 0,
  campaignId: 63045556084050,
  matchType: "EXACT",
  clicks: 0,
  impressions: 2,
  campaignName: "wood paint pens",
  keywordText: "wood paint pens",
  attributedUnitsOrdered1d: 0,
}
```

Data Example 2: 
```
{
  keywordId: 7598911878291,
  cost: 0,
  attributedSales1d: 0,
  campaignId: 149925639732250,
  matchType: "EXACT",
  clicks: 0,
  impressions: 43,
  campaignName: "glass paint",
  keywordText: "glass paint",
  attributedUnitsOrdered1d: 0,
}
```

## Expected behavior

Upsert object to DB

## Prisma information

```
model Keyword {
  id          Float           @id
  keywordText String
  matchType   MatchType
  bid         Float?
  state       State?
  rangeStart  Float?
  rangeEnd    Float?
  suggested   Float?
  updated     DateTime        @updatedAt
  reports     KeywordReport[]
  Campaign    Campaign        @relation(fields: [campaignId], references: [id])
  campaignId  Float
}
```

## Environment & setup

- OS: Mac OS,
- Database: PostgreSQL
- Node.js version:-v15.2.0
- Prisma version:2.11.0

```

```

**Comment by Stevenje** [comment]
Reverted to Prisma 2.10.0 and everything works again.

**Comment by pantharshit00** [comment]
Hey @Stevenje 

Sorry for the delay here, I was kinda on holiday. Can you please share `KeywordReport`, `MatchType` and `Campaign` models/enums. I wasn't able to reproduce this so please share these models.

**Comment by Stevenje** [comment]
Sure, here you go. Hope you had a nice break. 

```
enum MatchType {
  BROAD
  PHRASE
  EXACT
}

model Campaign {
  id                   Float      @id
  name                 String
  campaignType         String?
  targetingType        String?
  dailyBudget          Float?
  placementTop         Float?
  placementProductPage Float?
  strategy             String?
  state                State?
  adGroups             AdGroup[]
  Portfolio            Portfolio? @relation(fields: [portfolioId], references: [id])
  portfolioId          Float?
}

model KeywordReport {
  date                     DateTime
  clicks                   Int
  cost                     Float
  attributedSales1d        Float
  attributedUnitsOrdered1d Float
  impressions              Int
  Keyword                  Keyword  @relation(fields: [keywordId], references: [id])
  keywordId                Float

  @@id([keywordId, date])
}
```

**Comment by Stevenje** [comment]
Still present in 2.12.1

```
PrismaClientUnknownRequestError2: 
Invalid `prisma.keyword.upsert()` invocation:


  Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead.
    at PrismaClientFetcher.request (/Users/steven/Documents/boilerplate/versiontwo/node_modules/@prisma/client/runtime/index.js:79359:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at /Users/steven/Documents/boilerplate/versiontwo/packages/amazon/lib/amazon.ts:636:15 {
  clientVersion: '2.12.1'
}
```

**Comment by Stevenje** [comment]
@pantharshit00 Any idea what could be causing this? 

I tried with a clean DB today, using AWS RDS Postgres and spent a couple of hours playing around with the code to see if anything might happen to fix it and came up short.

**Comment by Stevenje** [comment]
It also seems to be unable to connect items sometimes. 

```
Create adgroup: PrismaClientUnknownRequestError2: 
Invalid `prisma.adGroup.create()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ForeignKeyConstraintViolation { constraint: Index("AdGroup_campaignId_fkey") } })
    at PrismaClientFetcher.request (/Users/steven/Documents/boilerplate/versiontwo/node_modules/@prisma/client/runtime/index.js:79359:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at /Users/steven/Documents/boilerplate/versiontwo/packages/amazon/lib/amazon.ts:497:45 {
  clientVersion: '2.12.1'
} {
  keywordId: 63241154731333,
  cost: 0,
  attributedSales1d: 0,
  adGroupName: 'CAM0009 Manual - Low Search Volume 0-1k',
  campaignId: 111291507866800,
  matchType: 'EXACT',
  clicks: 0,
  impressions: 45,
  campaignName: 'CAM0009 Manual - Low Search Volume 0-1k',
  adGroupId: 135753951356720,
  keywordText: 'paint marker',
  attributedUnitsOrdered1d: 0
}
```

Although the item 100% is in the DB 

<img width="891" alt="image" src="https://user-images.githubusercontent.com/4363358/100615354-7c586700-32e5-11eb-8811-a9e3b1754a1b.png">

**Comment by Stevenje** [comment]
Fixed by switching all ID values from FLOAT -> STRING although this was not idea.

**Comment by pantharshit00** [comment]
@Stevenje There is an open issue which covers this floats ids issue which is confirmed: https://github.com/prisma/prisma/issues/3665

So I am going to close this issue in favor of that.
