### ISSUE TITLE
P2000 error while upserting model and connect to other model

### ISSUE THREAD

**Issue by claassenarjan** [prisma/prisma#4305]
## Bug description

When upserting one model (TestReport) with a 1-to-1 relation to another model (Build) the whole transaction is rollbacked, due to a P2000 error.

Reported error:
```
PrismaClientKnownRequestError2: 
Invalid `prisma.testReport.upsert()` invocation:

  The provided value for the column is too long for the column's type. Column: \<unknown\>
    at PrismaClientFetcher.request (/usr/src/dasboard/modules/etl-manager/node_modules/@prisma/client/runtime/index.js:78782:15)
    at runMicrotasks (\<anonymous\>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Store.upsertTestReport (/usr/src/dasboard/modules/etl-manager/src/lib/store/store.js:90:12) {
  code: 'P2000',
  clientVersion: '2.11.0',
  meta: { column_name: '\<unknown\>' }
}
```

## How to reproduce

No small size example, but I have detailed logging. I will also add comment inline:

### Methods definitions :

1. create a build ConnectBlobRepo_NIGHTLY_625 via build.upsert

```ts
async upsertBuild(job, buildNumber, serviceAbbr, epoch, duration, result) {
    const variables = {
      job,
      number: buildNumber,
      job_number: job + "_" + buildNumber,
      service: serviceAbbr,
      epoch: epoch,
      duration: duration,
      result: resultToBoolean(result)
    };

    console.info("##! upsert build: ", variables.job_number);

    return await prisma.build.upsert({
      create: {
        job: variables.job,
        number: variables.number,
        job_number: variables.job_number,
        service: variables.service,
        epoch: variables.epoch,
        duration: variables.duration,
        result: variables.result
      },
      update: {
        duration: variables.duration,
        result: variables.result
      },
      where: {
        job_number: variables.job_number
      }
    });
  }
```

2.  testreport.upsert connecting to the just created build (ConnectBlobRepo_NIGHTLY_625)

```ts
async upsertTestReport(job, buildNumber, reportData) {
    const variables = {
      job_number: `${job}_${buildNumber}`,
      createDataSet: {
        job_number: `${job}_${buildNumber}`,
        build: { connect: { job_number: `${job}_${buildNumber}` } },
        RegressionTestCases: reportData.RegressionTestCases,
        NonRegressionTestCases: reportData.NonRegressionTestCases,
        PerformanceAutomatedTestCases: reportData.PerformanceAutomatedTestCases,
        TotalRegressionPassed: reportData.TotalRegressionPassed,
        TotalTestCases: reportData.TotalTestCases,
        TotalNonRegressionFailed: reportData.TotalNonRegressionFailed,
        SecurityAutomatedTestCases: reportData.SecurityAutomatedTestCases,
        RegressionAutomatedTestCases: reportData.RegressionAutomatedTestCases,
        AutomatedTestCases: reportData.AutomatedTestCases,
        NonRegressionAutomatedTestCases:
          reportData.NonRegressionAutomatedTestCases,
        TotalNonRegressionPassed: reportData.TotalNonRegressionPassed,
        TotalRegressionFailed: reportData.TotalRegressionFailed
      },
      updateDataSet: {
        RegressionTestCases: reportData.RegressionTestCases,
        NonRegressionTestCases: reportData.NonRegressionTestCases,
        PerformanceAutomatedTestCases: reportData.PerformanceAutomatedTestCases,
        TotalRegressionPassed: reportData.TotalRegressionPassed,
        TotalTestCases: reportData.TotalTestCases,
        TotalNonRegressionFailed: reportData.TotalNonRegressionFailed,
        SecurityAutomatedTestCases: reportData.SecurityAutomatedTestCases,
        RegressionAutomatedTestCases: reportData.RegressionAutomatedTestCases,
        AutomatedTestCases: reportData.AutomatedTestCases,
        NonRegressionAutomatedTestCases:
          reportData.NonRegressionAutomatedTestCases,
        TotalNonRegressionPassed: reportData.TotalNonRegressionPassed,
        TotalRegressionFailed: reportData.TotalRegressionFailed
      }
    };

    console.info(
      "##! Createset",
      variables.createDataSet,
      variables.updateDataSet
    );

    return await prisma.testReport.upsert({
      create: variables.createDataSet,
      update: variables.updateDataSet,
      where: {
        job_number: variables.job_number
      }
    });
  }
```
### Logging with annotations

> gather the information for creating a build and call above mentioned upsertBuild method

```
upsert build:  ConnectBlobRepo_NIGHTLY_625
prisma:query SELECT 1
prisma:query BEGIN
prisma:query SELECT "dashboard$develop"."Build"."id" FROM "dashboard$develop"."Build" WHERE "dashboard$develop"."Build"."job_number" = $1 OFFSET $2
prisma:query SELECT "dashboard$develop"."Build"."id" FROM "dashboard$develop"."Build" WHERE "dashboard$develop"."Build"."job_number" = $1
prisma:query UPDATE "dashboard$develop"."Build" SET "result" = $1, "duration" = $2 WHERE "dashboard$develop"."Build"."id" IN ($3)
prisma:query SELECT "dashboard$develop"."Build"."id", "dashboard$develop"."Build"."duration", "dashboard$develop"."Build"."epoch", "dashboard$develop"."Build"."job", "dashboard$develop"."Build"."job_number", "dashboard$develop"."Build"."number", "dashboard$develop"."Build"."result", "dashboard$develop"."Build"."service", "dashboard$develop"."Build"."testReportId" FROM "dashboard$develop"."Build" WHERE "dashboard$develop"."Build"."id" = $1 LIMIT $2 OFFSET $3
prisma:query COMMIT
....
```

> gather the information for creating a test report and call above mentioned upsertTestReport method

```
...
##! Createset {
  job_number: 'ConnectBlobRepo_NIGHTLY_625',
  build: { connect: { job_number: 'ConnectBlobRepo_NIGHTLY_625' } },
  RegressionTestCases: 231,
  NonRegressionTestCases: 48,
  PerformanceAutomatedTestCases: 0,
  TotalRegressionPassed: 229,
  TotalTestCases: 279,
  TotalNonRegressionFailed: 1,
  SecurityAutomatedTestCases: 14,
  RegressionAutomatedTestCases: 231,
  AutomatedTestCases: 258,
  NonRegressionAutomatedTestCases: 27,
  TotalNonRegressionPassed: 25,
  TotalRegressionFailed: 2
} {
  RegressionTestCases: 231,
  NonRegressionTestCases: 48,
  PerformanceAutomatedTestCases: 0,
  TotalRegressionPassed: 229,
  TotalTestCases: 279,
  TotalNonRegressionFailed: 1,
  SecurityAutomatedTestCases: 14,
  RegressionAutomatedTestCases: 231,
  AutomatedTestCases: 258,
  NonRegressionAutomatedTestCases: 27,
  TotalNonRegressionPassed: 25,
  TotalRegressionFailed: 2
}
...
prisma:query BEGIN
prisma:query SELECT "dashboard$develop"."TestReport"."id" FROM "dashboard$develop"."TestReport" WHERE "dashboard$develop"."TestReport"."job_number" = $1 OFFSET $2
prisma:query SELECT "dashboard$develop"."Build"."id", "dashboard$develop"."Build"."testReportId" FROM "dashboard$develop"."Build" WHERE "dashboard$develop"."Build"."job_number" = $1 OFFSET $2
prisma:query INSERT INTO "dashboard$develop"."TestReport" ("id","job_number","RegressionTestCases","NonRegressionTestCases","PerformanceAutomatedTestCases","TotalRegressionPassed","TotalTestCases","TotalNonRegressionFailed","SecurityAutomatedTestCases","RegressionAutomatedTestCases","AutomatedTestCases","NonRegressionAutomatedTestCases","TotalNonRegressionPassed","TotalRegressionFailed") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING "dashboard$develop"."TestReport"."id"
prisma:query SELECT "dashboard$develop"."Build"."id" FROM "dashboard$develop"."Build" WHERE "dashboard$develop"."Build"."id" = $1
**prisma:query UPDATE "dashboard$develop"."Build" SET "testReportId" = $1 WHERE "dashboard$develop"."Build"."id" IN ($2)
prisma:query ROLLBACK**
##! Error upserting test Report PrismaClientKnownRequestError2: 
Invalid `prisma.testReport.upsert()` invocation:


  The provided value for the column is too long for the column's type. Column: <unknown>
    at PrismaClientFetcher.request (/usr/src/dasboard/modules/etl-manager/node_modules/@prisma/client/runtime/index.js:78782:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Store.upsertTestReport (/usr/src/dasboard/modules/etl-manager/src/lib/store/store.js:90:12) {
  code: 'P2000',
  clientVersion: '2.11.0',
  meta: { column_name: '<unknown>' }
}
```

>  Error reporting information (similar as above)

```
##! Service:  ConnectBlobRepo_NIGHTLY
##! Buildnumber:  625
##! TestReport:  {
  RegressionTestCases: 231,
  NonRegressionTestCases: 48,
  PerformanceAutomatedTestCases: 0,
  TotalRegressionPassed: 229,
  TotalTestCases: 279,
  TotalNonRegressionFailed: 1,
  SecurityAutomatedTestCases: 14,
  RegressionAutomatedTestCases: 231,
  AutomatedTestCases: 258,
  NonRegressionAutomatedTestCases: 27,
  TotalNonRegressionPassed: 25,
  TotalRegressionFailed: 2
}
```

## Expected behavior

Expected behavior is to be able to upsert a TestReport and connect to the already existing Build.

## Prisma information

! removed other models
Model build with one optional testReport.

```prisma
model Build {
  id           String      @id @default(cuid())
  duration     Float       @default(0)
  epoch        Float?
  job          String
  job_number   String      @unique
  number       Int
  result       Boolean?
  service      String
  testReportId String?     @unique
  testReport   TestReport? @relation(fields: [testReportId], references: [id])
  testRuns     TestRun[]
}
// .....

model TestReport {
  id                              String @id @default(cuid())
  job_number                      String @unique
  RegressionTestCases             Int?
  NonRegressionTestCases          Int?
  PerformanceAutomatedTestCases   Int?
  TotalRegressionPassed           Int?
  TotalTestCases                  Int?
  TotalNonRegressionFailed        Int?
  SecurityAutomatedTestCases      Int?
  RegressionAutomatedTestCases    Int?
  AutomatedTestCases              Int?
  NonRegressionAutomatedTestCases Int?
  TotalNonRegressionPassed        Int?
  TotalRegressionFailed           Int?
  build                           Build?
}
```

## Environment & setup

- OS:  MacOSX Cataline 10.15.7 and Linux (docker image FROM node:latest = Ubuntu)
- Database:  PostgresQL 10.3 in docker
- Node.js version:  On MacOS: v12.18.0, On Linux docker: node:latest = 15.2.1
- Prisma version:  "@prisma/client": "^2.11.0", "@prisma/cli": "^2.11.0"

```

```

**Comment by pantharshit00** [comment]
Hey @claassenarjan 

Can you please try this again in the latest version? 

From the error message it seems to appear that one of your integer field is exceeding the database size limit so try changing that to a bigint in the database and then use introspection to use it via native types: https://www.prisma.io/docs/concepts/components/preview-features/native-types

Regarding the error message here not mentioning the exact field, there was a discussion here in the past where we concluded it can't be improved as the database doesn't return this information in the first place: https://github.com/prisma/prisma/issues/2730

**Comment by claassenarjan** [comment]
Thanks, In the mean time I have restructured the database model, removing this specific query.

**Comment by Allislove** [comment]
For anyone who is getting this error at this date. 2022! just remove the length limit for the field, in my case i was waiting only for a 50 limit characters, but i need more, so i just change my db varchar to no def

**Comment by JannikZed** [comment]
@Allislove how to remove the length limit? I have this issue for a string field in Postgres... it is ridiculous, that Prisma does not include any kind of documentation on such limits etc.. it just fails, and goodbye.

**Comment by Allislove** [comment]
> @Allislove how to remove the length limit? I have this issue for a string field in Postgres... it is ridiculous, that Prisma does not include any kind of documentation on such limits etc.. it just fails, and goodbye.


Hey! Salute, can you please show the error and you code.

**Comment by Allislove** [comment]
@JannikZed Cuz first of all "The length limit" is the database field, please share the error and the db schema, so I can help you.

**Comment by haseebkhan9081** [comment]
in 2024 you can use :
 topic String  @db.LongText()
