### ISSUE TITLE
Database conflict on multiple fields only specifies one field in error message

### ISSUE THREAD

**Issue by supermacro** [prisma/prisma#4350]
## Bug description

I tried to write to the database by calling `prisma.myModel.create` with two values that already existed in my database and which had a unique constraint.

When I looked at the logs, prisma had the following:

```
server_1  | { Error: 
server_1  | Invalid `prisma.admin.create()` invocation:
server_1  | 
server_1  | 
server_1  |   Unique constraint failed on the fields: (`email`)
server_1  |     at PrismaClientFetcher.request (/usr/app/node_modules/.prisma/client/runtime/index.js:78782:15)
server_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
server_1  |   code: 'P2002',
server_1  |   clientVersion: '2.11.0',
server_1  |   meta: { target: [ 'email' ] } }
```

However, I know that I also had a conflict on the `username` field, which I confirmed by repeating the query again but with a new (unique) email, and not changing the username, which got me this error:

```
server_1  | { Error: 
server_1  | Invalid `prisma.admin.create()` invocation:
server_1  | 
server_1  | 
server_1  |   Unique constraint failed on the fields: (`username`)
server_1  |     at PrismaClientFetcher.request (/usr/app/node_modules/.prisma/client/runtime/index.js:78782:15)
server_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
server_1  |   code: 'P2002',
server_1  |   clientVersion: '2.11.0',
server_1  |   meta: { target: [ 'username' ] } }
```

## How to reproduce

Do a call to `prisma.myModel.create` with at least 2 fields whose columns have a unique index / constraint and whose values you're inserting already exist in that table.

## Expected behavior

**I expected prisma to specify all unique constraint violations**.

## Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  output   = "./node_modules/.prisma/client"
}

model Admin {
  id         String   @id @default(cuid())
  email      String   @unique
  username   String   @unique
  password   String
  sites      Site[]
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt

  @@map("admins")
}

model Site {
  id         String   @id @default(cuid())
  hostname   String   @unique
  verified   Boolean  @default(false)
  dns_tag    String   @unique @default(uuid())
  admin      Admin    @relation(fields: [admin_id], references: [id])
  admin_id   String
  posts      Post[]
  created_at DateTime @default(now())
  updated_at DateTime @updatedAt

  @@map("sites")
}

model User {
  id         String    @id @default(cuid())
  email      String    @unique
  username   String    @unique
  password   String
  comments   Comment[]
  created_at DateTime  @default(now())
  updated_at DateTime  @updatedAt

  @@map("users")
}

model Comment {
  @@map("comments")

  id                String   @id @default(cuid())
  parent            Comment? @relation(fields: [parent_comment_id], references: [id])
  author            User?    @relation(fields: [author_id], references: [id])
  anon_author_name  String?
  body              String   @default("")
  votes             Int      @default(0)
  post              Post     @relation(fields: [post_id], references: [id])
  post_id           String
  created_at        DateTime @default(now())
  updated_at        DateTime @updatedAt
  replies           Comment[] @relation("CommentToComment")
  parent_comment_id String?
  author_id         String?
}


// Tracks the state of the leaf nodes on a per-post basis
model CommentTreeState {
  @@map("comment_tree_state")
  post               Post @relation(fields: [post_id], references: [id])
  post_id            String @id
  comment_tree_leafs Json // ["123", "345", "545"]
}


model Post {
  id         String    @id @default(cuid())
  url_slug   String    @unique
  site       Site      @relation(fields: [site_id], references: [id])
  site_id    String
  comments   Comment[]
  created_at DateTime  @default(now())
  updated_at DateTime  @updatedAt

  @@map("posts")
}


```

## Environment & setup
- OS: Mac OS Catalina (10.15.7)
- Database: PostgreSQL
- Node.js version: 10.16.0
- Prisma version: 

```
Environment variables loaded from /Users/giorgiodelgado/code/avila/parlez-vous/server/.env
@prisma/cli          : 2.11.0
@prisma/client       : 2.11.0
Current platform     : darwin
Query Engine         : query-engine 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 58369335532e47bdcec77a2f1e7c1fb83a463918 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.311.0
```

**Comment by iquabius** [comment]
Another thing I noticed is that the error only mentions the field name, which makes it difficult to identify which record is triggering the problem. Imagine a seed script inserting hundreds of records across several models.

<details><summary>Error output example</summary><p>

```sh
➜ npx prisma migrate reset --preview-feature --schema=./src/prisma/schema.prisma
Environment variables loaded from src/prisma/.env                                                       
Prisma schema loaded from src/prisma/schema.prisma                                                      
Datasource "db": PostgreSQL database "dev", schema "public" at "localhost:5433"                         
                                                                                                        
                                                                                                        
✔ Are you sure you want to reset your database? All data will be lost. … yes                            
Database reset successful                                                                               
                                                                                                        
The following migration(s) have been applied:

migrations/
  └─ 20210209185304_init/
    └─ migration.sql
  └─ 20210215220013_add_user/
    └─ migration.sql

✔ Generated Prisma Client (2.16.1) to ./../../node_modules/@prisma/client in 152ms
Running ts-node "/.../monorepo/apps/api/src/prisma/seed.ts" ...
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: Unique constraint failed on the fields:
(`id`)
    at PrismaClientFetcher.request (/.../monorepo/node_modules/@prisma/client/runtime/index
.js:78463:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2002',
  clientVersion: '2.16.1',
  meta: { target: [ 'id' ] }
}
Error: Command failed with exit code 1: ts-node "/.../monorepo/apps/api/src/prisma/seed.ts"
```
</p></details>

It would be helpful to include the **model name** and the **field value** that is causing the problem.

Let me know if I should open another issue for this.

**Comment by pantharshit00** [comment]
@iquabius That is hard to do as we don't get that information from the database driver.

**Comment by iquabius** [comment]
@pantharshit00 Oh, I see! It makes sense.

Then all we can do is hope for improved driver APIs in the future.

**Comment by bravo-kernel** [comment]
Confirmed same here, using both Sqlite and Postgres:

> When passing multiple "failing" unique constraints, only one/the first failing constraint is reported back as an error.

Is this how the current version of Prisma works? This makes it really hard to set multiple failing form fields.

**Comment by bravo-kernel** [comment]
After [reading more](https://stackoverflow.com/questions/57024741/i-need-advice-with-error-handling-for-multiple-unique-columns#comment100587893_57024741) on how constraints work I think this ticket can be closed:

> You cannot validate multiple columns as unique in a single insert - unless all are if unique. . **SQL uses AND conditions and short circuit evaluation: once any predicate evaluates FALSE others are not evaluated;** regardless of their true/false condition it cannot change the true/false condition of the statement as a whole. SQL only cares about the statement as a whole not individual predicates

**Comment by supermacro** [comment]
The aforementioned link is from an SO comment from 2019 which is also specific to postgresql.

- Is this still valid today / has postgresql released any changes that would allow to know ahead of time all unique constraint violations?
- does this apply to all other databases, or just postgresql?

**Comment by bravo-kernel** [comment]
The comment describes the situation better than I could hence the reference.

What I did to confirm is basically apply common sense and executed the following INSERT against **multiple** databases using their native GUI tools. They all show the same behavior.

```
insert into user (id, username, email, updatedAt, createdAt) values ("fake-guid", "existing-username", "existing@email-address.com", "1627934457079", "1627934457079")
```

I believe this ticket should be closed.

**Comment by pantharshit00** [comment]
Yeah, I agree with @bravo-kernel, we can close. We are not very aggressive in closing issues and we review issues like these time to time and close them in one go.
