### ISSUE TITLE
CLI should show rollback message

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4351]
**Describe the bug**
CLI treats rollback as a success without showing any messages specifically about the rollback. 

**To Reproduce**
Try this reproduction: 
https://github.com/prisma/prisma/issues/4344

It rolls back on the deployment but CLI doesn't show anything about the rollback and treats it like any deployment. 

**Expected behavior**
CLI should show rollback properly

**Screenshots**
![image](https://user-images.githubusercontent.com/746482/55883909-6f827f00-5ba7-11e9-9413-fea9552f15c1.png)

It infinitely shows the same message will applying changes going from 0-N-0 and never shows "service is up to date". 

**Versions (please complete the following information):**
 - Prisma Server: `1.30.0`
 - `prisma` CLI: `1.30.0`

**Additional context:**
https://github.com/prisma/prisma-cloud-feedback/issues/262

**Comment by johnthepink** [comment]
We experienced this yesterday as well. Hopefully this can help.

**Versions**

- Prisma Server: `1.29.2`
- `prisma` CLI: `1.29.2`
- Connector: `mysql`

**Reproduction**

We were trying to deploy this change:

```diff
- someId: ID! @unique
+ someId: String! @unique
```

The CLI recognized this change:

```
~ Updated field `someId`
```

But it causes this error on the Prisma Server:

```
Encountered exception while applying migration. Rolling back. java.sql.SQLSyntaxErrorException: (conn=52662) BLOB/TEXT column 'someId' used in key specification without a key length
java.sql.SQLSyntaxErrorException: (conn=52662) BLOB/TEXT column 'someId' used in key specification without a key length
       at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:163)
       at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:106)
       at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
       at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:224)
       at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)
       at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
       at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
       at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
       at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
       at slick.jdbc.Invoker.first(Invoker.scala:30)
       at slick.jdbc.Invoker.first$(Invoker.scala:29)
       at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:15)
       at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
       at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
       at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
       at scala.collection.Iterator.foreach(Iterator.scala:937)
       at scala.collection.Iterator.foreach$(Iterator.scala:937)
       at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
       at scala.collection.IterableLike.foreach(IterableLike.scala:70)
       at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
       at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
       at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
       at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
       at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
       at scala.collection.Iterator.foreach(Iterator.scala:937)
       at scala.collection.Iterator.foreach$(Iterator.scala:937)
       at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
       at scala.collection.IterableLike.foreach(IterableLike.scala:70)
       at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
       at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
       at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
       at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
       at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
       at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: BLOB/TEXT column 'someId' used in key specification without a key length
Query is: ALTER TABLE `default@production`.`Organization` CHANGE COLUMN `someId` `someId` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
       at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146)
       at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217)
       at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218)
       ... 33 more
[Debug] Applied migration for project default@production
```

So MySQL rolled back, and then the CLI moved on as if everything went smoothly. 

**Expected Behavior**

I would have expected the deploy to error out.

**Comment by yiniynyin** [comment]
It's silently breaking CI/CD... should have at the very least exit with error.

**Comment by nelsonpecora** [comment]
I just spent a few hours running into this issue, with Prisma server and CLI `v1.34.1`. I'm ok with treating rollbacks as a success but there really needs to be some kind of indication in the CLI tool that it didn't go through.

**Comment by omar-dulaimi** [comment]
I just spent the last couple of hours trying to find out why prisma is not deploying my changes. It kept deploying the same changes successfully!
Now that's embarrassing, the console should show errors when it can't deploy.
