### ISSUE TITLE
P2016 since 2.11.0 when nested create and reference to same are within same query graph

### ISSUE THREAD

**Issue by pbelbin** [prisma/prisma#4367]
## Bug description

Prior to Prisma 2.10.0, it was possible to, within a single query graph, both create a nested record, and, make reference to the newly created record.  Since Prisma 2.11.0, this is broken.

## How to reproduce

I created a sample on github that's based on the TypeScript 'scripts' example within the prisma-samples project.

https://github.com/pbelbin/2020-11-25-Prisma-P2016-Bug

Check out the project, at the command line, use:

npm install
npm run dev

and you will see the error being reported.

If you like, go into the package.json and change the version of Prisma back to 2.10.0, then use:

rm -rf node_modules
npm install
npm run dev

and you will see that there is no error.

## Expected behavior

There should not be an error thrown, and, the records in the database should all get created.

## Prisma information

schema.prisma:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model Group {
  id Int @id
  name String
  
  posts Post[]
}

model Post {
  id        Int     @default(autoincrement()) @id
  title     String
  content   String?
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
  
  group Group? @relation(fields: [groupId], references: [id])
  groupId Int?
}

model User {
  id    Int     @id
  email String  @unique
  name  String?
  posts Post[]
}
```

sample code:

```
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// A `main` function so that we can use async/await
async function main() {
  // Delete existing data
  await prisma.user.deleteMany({});
  await prisma.post.deleteMany({});
  await prisma.group.deleteMany({});
  
  
  // Determine high# for authorID
  const newAuthorID = 1;
  
  
  // Create 2 posts by new user
  await prisma.group.create({
    data: {
      id: 20,
      name: 'Grp1',
      posts: {
        create: [
          {
            title: 'post x-1',
            content: 'Yabba dabba do!',
            author: {
              create: {
                id: newAuthorID,
                email: 'author1@testing.com',
                name: 'Fred Flintstone',
              }
            }
          },
          {
            title: 'post x-1',
            content: 'Yabba dabba do!',
            author: {
              connect: {
                id: newAuthorID,
              }
            }
          }
        ]
      }
    }
  });
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

```

## Environment & setup

- OS: Mac OS 11.0.1
- Database: SQLLite, MySQL
- Node.js version: 14.15.1
- Prisma version: 
```
@prisma/cli          : 2.12.0
@prisma/client       : 2.12.0
Current platform     : darwin
Query Engine         : query-engine cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt cf0680a1bfe8d5e743dc659cc7f08009f9587d58 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.322.0
```

**Comment by nikolasburk** [comment]
Hey @pbelbin, thanks for raising this. It actually seems like this is not really a bug since the order of statements executed against the DB is not guaranteed by Prisma. So in this case, you unfortunately can't rely on the `create` call being executed _before_ the `connect` call.

In this case, the issue would better be solved using `connectOrCreate` to ensure the new `author` can be created – or if it has been created already – can be connected to the new `Post` record:

```ts
await prisma.group.create({
  data: {
    id: 20,
    name: "Grp1",
    posts: {
      create: [
        {
          title: "post x-1",
          content: "Yabba dabba do!",
          author: {
            connectOrCreate: {
              where: {
                id: newAuthorID,
              },
              create: {
                id: newAuthorID,
                email: "author1@testing.com",
                name: "Fred Flintstone",
              },
            },
          },
        },
        {
          title: "post x-1",
          content: "Yabba dabba do!",
          author: {
            connectOrCreate: {
              where: {
                id: newAuthorID,
              },
              create: {
                id: newAuthorID,
                email: "author1@testing.com",
                name: "Fred Flintstone",
              },
            },
          },
        },
      ],
    },
  },
});
```

Does that help?

**Comment by pbelbin** [comment]
Hmmmm.  I see.

I have to say, I'm not a big fan of repeating the data within the graph.  In the sample, it has to be repeated only twice.  In other cases, it could amount to many more times, and the amount of data could be quite large.

Perhaps I am mistaken, but, it was my understanding that the Prisma Engine had the responsibility of performing some analysis of the ask, and would re-sequence as needed to achieve the intended result.

Is that not correct?

**Comment by nikolasburk** [comment]
> It was my understanding that the Prisma Engine had the responsibility of performing some analysis of the ask, and would re-sequence as needed to achieve the intended result.
> Is that not correct?

As far as I understand, this is not correct unfortunately. Prima doesn't provide any guarantees about the sequencing of SQL statements that are generated by the Prisma engine for a nested write. 

I'd encourage you to open a feature request where you describe the behaviour you'd like to see, but the way how things are implemented right now there are no guarantees about this behaviour unfortunately.

**Comment by mavilein** [comment]
Yes the Engine has a responsibility to put the operations into the right order. But only within our defined semantics. There's no concept of ordering `create`s before `connect`s or so. That would significantly complicate our semantics imo.

The way to deal with the repetition is to extract it into a variable e.g.:
```
const theAuthor = {
    where: {
        id: newAuthorID,
    },
    create: {
        id: newAuthorID,
        email: "author1@testing.com",
        name: "Fred Flintstone",
    },
}

await prisma.group.create({
  data: {
    id: 20,
    name: "Grp1",
    posts: {
      create: [
        {
          title: "post x-1",
          content: "Yabba dabba do!",
          author: {
            connectOrCreate: theAuthor
          },
        },
        {
          title: "post x-2",
          content: "Yabba dabba do!",
          author: {
            connectOrCreate: theAuthor
          },
        },
      ],
    },
  },
});
```

**Comment by pantharshit00** [comment]
I can reproduce the behavior but looks like this is expected from the above conversation so I am marking this as a question. If you kind this should be further addressed, please comment here :)

**Comment by pbelbin** [comment]
Since the example I have provided already has the nested creates being contained within an array, is there no way to just ensure that the requests are processed in the order provided?  This would simplify things considerably.

**Comment by pbelbin** [comment]
It also seems, at least, for me, lack of clarity as to exactly what the Prisma Engine is or is not responsible for in terms of ordering of requests.  Is this documented anywhere?

**Comment by pantharshit00** [comment]
Prisma Engine is the internal component written in Rust used by Prisma Clients(Javascript and Go clients right now). You can find its code here: https://github.com/prisma/prisma-engines


So essentially the Prisma Client is just a wrapper around this engine. Clients send a wire protocol call to the engine over UDS right now and the engine decides how to execute the query, generate the relevant sql and return the executed result. The engine generates a query graph of your call and decides then it walks that graph generating sql and executing them over the database pool it has initialize during the startup. Right now in the graph, order of execution of `connect` and `create` is not guaranteed.

**Comment by janpio** [comment]
To reproduce this with the provided 2.12.0 I had to switch to a system not running OpenSSL 3 (in my case then Windows) and downgrade node to 12.18.4 (because of https://github.com/nodejs/node/issues/35582).

With that I indeed can reproduce the original report:
```
C:\Users\Jan\Documents\throwaway\2020-11-25-Prisma-P2016-Bug>npx ts-node ./script.ts
PrismaClientKnownRequestError2: 
Invalid `prisma.group.create()` invocation:


  Query interpretation error. Error for binding '4': AssertionError("[Query Graph] Expected a valid parent ID to be present for a nested connect on a one-to-many relation.")
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\throwaway\2020-11-25-Prisma-P2016-Bug\node_modules\@prisma\client\runtime\index.js:79353:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2016',
  clientVersion: '2.12.0',
  meta: {
    details: `Error for binding '4': AssertionError("[Query Graph] Expected a valid parent ID to be present for a nested connect on a one-to-many relation.")`
  }
}
```

After upgrading to 4.16.1, Prisma returns a much better error message:
```
C:\Users\Jan\Documents\throwaway\2020-11-25-Prisma-P2016-Bug>npx ts-node ./script.ts    
PrismaClientKnownRequestError: 
Invalid `prisma.group.create()` invocation in
C:\Users\Jan\Documents\throwaway\2020-11-25-Prisma-P2016-Bug\script.ts:18:22

  15
  16
  17 // Create 2 posts by new user
→ 18 await prisma.group.create(
An operation failed because it depends on one or more records that were required but not found. No 'User' record(s) (needed to inline the relation on 'Post' record(s)) was found for a nested connect on one-to-many relation 'PostToUser'.
    at Rn.handleRequestError (C:\Users\Jan\Documents\throwaway\2020-11-25-Prisma-P2016-Bug\node_modules\@prisma\client\runtime\library.js:174:7325)
    at Rn.handleAndLogRequestError (C:\Users\Jan\Documents\throwaway\2020-11-25-Prisma-P2016-Bug\node_modules\@prisma\client\runtime\library.js:174:6754)
    at Rn.request (C:\Users\Jan\Documents\throwaway\2020-11-25-Prisma-P2016-Bug\node_modules\@prisma\client\runtime\library.js:174:6344) {
  code: 'P2025',
  clientVersion: '4.16.1',
  meta: {
    cause: "No 'User' record(s) (needed to inline the relation on 'Post' record(s)) was found for a nested connect on one-to-many relation 'PostToUser'."
  }
}
```

Note that above colleagues already discussed that this might indeed not be intended to work any different, so this `bug/2-confirmed` only confirms that the behavior describe is happening - we might still close this issue with "works as expected".
