### ISSUE TITLE
BigInt not supported on initial introspection in psql 11 database

### ISSUE THREAD

**Issue by redaikidoka** [prisma/prisma#4442]
**Describe the bug**
A I have a table that has a BigInt datatype, and when I run the initial prisma deploy, it errors out

**To Reproduce**
1.  Create a psql table with a BigInt
```
create table nces_school
(
	school_year char(9) not null,
	school_year_ending integer,
	school_name varchar(150),
	district_name varchar(150),
	id_school_state varchar(40),
	id_school_nces bigint not null,
	id_district_state varchar(40),
	id_district_nces integer,
	id_district_state_num integer,
	gslo char(2),
	gshi char(2),
	grade_starting integer,
	grade_ending integer,
	school_type varchar(50),
	s_create timestamp(6) not null,
	s_update timestamp(6) not null,
	state_abbr char(2),
	id_school_state_num integer,
	id serial 
			primary key
);

```
2. ```prisma init``` for the database including that table
3. ```prisma deploy```
> Applying changes 7.2s
>  ▸    The Migration failed and has not been performed. This is very likely not a transient issue.
>  ▸    org.postgresql.util.PSQLException: ERROR: integer out of range
>  ▸    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
>  ▸    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
>  ▸    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
>  ▸    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
>  ▸    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
>  ▸    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
>  ▸    at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
>  ▸    at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
>  ▸    at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
>  ▸    at slick.jdbc.Invoker.first(Invoker.scala:30)
>  ▸    at slick.jdbc.Invoker.first$(Invoker.scala:29)
>  ▸    at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:15)
>  ▸    at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
>  ▸    at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
>  ▸    at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
>  ▸    at scala.collection.Iterator.foreach(Iterator.scala:937)
>  ▸    at scala.collection.Iterator.foreach$(Iterator.scala:937)
>  ▸    at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
>  ▸    at scala.collection.IterableLike.foreach(IterableLike.scala:70)
>  ▸    at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
>  ▸    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
>  ▸    at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
>  ▸    at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
>  ▸    at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
>  ▸    at scala.collection.Iterator.foreach(Iterator.scala:937)
>  ▸    at scala.collection.Iterator.foreach$(Iterator.scala:937)
>  ▸    at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
>  ▸    at scala.collection.IterableLike.foreach(IterableLike.scala:70)
>  ▸    at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
>  ▸    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
>  ▸    at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
>  ▸    at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
>  ▸    at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
>  ▸    at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
>  ▸    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>  ▸    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>  ▸    at java.lang.Thread.run(Thread.java:748)
> 

**Expected behavior**
It'd be great if Prisma recognized the bigInt as a bigInt and didn't error out on introspection

**Versions (please complete the following information):**
 - Connector:  Postgres 
 - Prisma CLI version: prisma/1.31.1 (darwin-x64) node-v10.15.3
 - Prisma server version: 1.31.0
 - OS:  OS X High Sierra

**Comment by redaikidoka** [comment]
This is a duplicate of issue 4190 https://github.com/prisma/prisma/issues/4190
