### ISSUE TITLE
FATAL: database "prisma" does not exist

### ISSUE THREAD

**Issue by stevenvachon** [prisma/prisma#4596]
**Describe the bug**
The first time I run `docker-compose up`, I get the above error. By `ctrl+c`'ing that and running `up` again, it works as expected.

**To Reproduce**
Dockerfile:
```
FROM node:12
COPY . /app
WORKDIR /app
RUN npm install --unsafe-perm
CMD ["node", "server/index.js"]
```

docker-compose.yml:
```yml
version: '3.7'
services:
  app:
    build: .
    depends_on:
      - prisma
    image: code-challenge # build name
    ports:
      - "8080:80"
    volumes:
      - .:/app
  postgres:
    environment:
      POSTGRES_DB: resumes
      POSTGRES_PASS: dbpass # unsafe
      POSTGRES_USER: dbuser # unsafe
    image: postgres:11
    ports:
      - "5432:5432"
    #restart: always
  prisma:
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        databases:
          default:
            host: postgres
            connector: postgres
            #migrations: true
            password: dbpass
            port: 5432
            user: dbuser
        port: 4466
    image: prismagraphql/prisma:1.33
    ports:
      - "4466:4466"
    #restart: always
```

**Expected behavior**
It should create the database the first time.

**Screenshots**
```shell
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | 2019-05-28 16:21:30.264 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2019-05-28 16:21:30.264 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2019-05-28 16:21:30.268 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2019-05-28 16:21:30.286 UTC [60] LOG:  database system was shut down at 2019-05-28 16:21:30 UTC
postgres_1  | 2019-05-28 16:21:30.296 UTC [1] LOG:  database system is ready to accept connections
app_app_1 exited with code 0
prisma_1    | No log level set, defaulting to INFO.
prisma_1    | [INFO] {} - Started.
postgres_1  | 2019-05-28 16:21:32.224 UTC [68] FATAL:  database "prisma" does not exist
prisma_1    | May 28, 2019 4:21:32 PM org.postgresql.core.v3.ConnectionFactoryImpl log
prisma_1    | WARNING: SQLException occurred while connecting to postgres:5432
prisma_1    | org.postgresql.util.PSQLException: FATAL: database "prisma" does not exist
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
prisma_1    | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
prisma_1    | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1    | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1    | 	at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1    | 	at org.postgresql.Driver.connect(Driver.java:254)
prisma_1    | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1    | 	at java.lang.Thread.run(Thread.java:748)
prisma_1    | 
prisma_1    | May 28, 2019 4:21:32 PM org.postgresql.Driver connect
prisma_1    | SEVERE: Connection error: 
prisma_1    | org.postgresql.util.PSQLException: FATAL: database "prisma" does not exist
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
prisma_1    | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
prisma_1    | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1    | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1    | 	at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1    | 	at org.postgresql.Driver.connect(Driver.java:254)
prisma_1    | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1    | 	at java.lang.Thread.run(Thread.java:748)
prisma_1    | 
postgres_1  | 2019-05-28 16:21:32.612 UTC [70] FATAL:  database "prisma" does not exist
prisma_1    | May 28, 2019 4:21:32 PM org.postgresql.core.v3.ConnectionFactoryImpl log
prisma_1    | WARNING: SQLException occurred while connecting to postgres:5432
prisma_1    | org.postgresql.util.PSQLException: FATAL: database "prisma" does not exist
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
prisma_1    | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
prisma_1    | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1    | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1    | 	at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1    | 	at org.postgresql.Driver.connect(Driver.java:254)
prisma_1    | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1    | 	at java.lang.Thread.run(Thread.java:748)
prisma_1    | 
prisma_1    | May 28, 2019 4:21:32 PM org.postgresql.Driver connect
prisma_1    | SEVERE: Connection error: 
prisma_1    | org.postgresql.util.PSQLException: FATAL: database "prisma" does not exist
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
prisma_1    | 	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
prisma_1    | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
prisma_1    | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
prisma_1    | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
prisma_1    | 	at org.postgresql.Driver.makeConnection(Driver.java:452)
prisma_1    | 	at org.postgresql.Driver.connect(Driver.java:254)
prisma_1    | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
prisma_1    | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:193)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:430)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:64)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:570)
prisma_1    | 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:563)
prisma_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1    | 	at java.lang.Thread.run(Thread.java:748)
prisma_1    | 
prisma_1    | [INFO] Initializing workers...
prisma_1    | [INFO] Obtaining exclusive agent lock...
prisma_1    | [INFO] Obtaining exclusive agent lock... Successful.
prisma_1    | [INFO] Deployment worker initialization complete.
prisma_1    | [INFO] Successfully started 1 workers.
prisma_1    | Server running on :4466
^CGracefully stopping... (press Ctrl+C again to force)
Stopping app_prisma_1   ... done
Stopping app_postgres_1 ... done
app$ docker-compose up
Recreating app_postgres_1 ... done
Recreating app_prisma_1   ... done
Recreating app_app_1      ... done
Attaching to app_postgres_1, app_prisma_1, app_app_1
postgres_1  | 2019-05-28 16:28:47.563 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2019-05-28 16:28:47.563 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2019-05-28 16:28:47.570 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2019-05-28 16:28:47.596 UTC [25] LOG:  database system was shut down at 2019-05-28 16:28:38 UTC
postgres_1  | 2019-05-28 16:28:47.602 UTC [1] LOG:  database system is ready to accept connections
app_1       | okay
app_app_1 exited with code 0
prisma_1    | No log level set, defaulting to INFO.
prisma_1    | [INFO] {} - Started.
postgres_1  | 2019-05-28 16:28:51.825 UTC [34] ERROR:  database "prisma" already exists
postgres_1  | 2019-05-28 16:28:51.825 UTC [34] STATEMENT:  CREATE DATABASE "prisma"
prisma_1    | [INFO] Obtaining exclusive agent lock...
prisma_1    | [INFO] Initializing workers...
prisma_1    | [INFO] Obtaining exclusive agent lock... Successful.
prisma_1    | [INFO] Successfully started 1 workers.
prisma_1    | [INFO] Deployment worker initialization complete.
prisma_1    | Server running on :4466
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  | 
postgres_1  | 2019-05-28 16:21:30.264 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2019-05-28 16:21:30.264 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2019-05-28 16:21:30.268 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2019-05-28 16:21:30.286 UTC [60] LOG:  database system was shut down at 2019-05-28 16:21:30 UTC
postgres_1  | 2019-05-28 16:21:30.296 UTC [1] LOG:  database system is ready to accept connections
app_app_1 exited with code 0
prisma_1    | No log level set, defaulting to INFO.
prisma_1    | [INFO] {} - Started.
postgres_1  | 2019-05-28 16:21:32.224 UTC [68] FATAL:  database "prisma" does not exist
prisma_1    | May 28, 2019 4:21:32 PM org.postgresql.core.v3.ConnectionFactoryImpl log
prisma_1    | WARNING: SQLException occurred while connecting to postgres:5432
```

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.33.0
 - `prisma` CLI:  prisma/1.33.0 (darwin-x64) node-v12.3.1
 - OS: macOS 10.14.5

**Comment by stevenvachon** [comment]
From https://hub.docker.com/_/postgres:
> `POSTGRES_DB`: This optional environment variable can be used to define a different name for the default database that is created when the image is first started. If it is not specified, then the value of `POSTGRES_USER` will be used.

Changing the value of `POSTGRES_DB` from "resumes" to "prisma" made it work.
