### ISSUE TITLE
Error: Error in migration engine. Reason: [/root/build/migration-engine/core/src/commands/diagnose_migration_history.rs:103:26]

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4607]
Failed to read migration script: ReadMigrationScriptError(Os { code: 2, kind: NotFound, message: "No such file or directory" }, SpanTrace [{ target: "migration_connector::migrations_directory", name: "read_migration_script", fields: "self=MigrationDirectory { path: \"/Users/pedrocavadas/Developer/people/service/prisma/migrations/20201209135949_test_migration\" }", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 185 }, { target: "migration_connector::migrations_directory", name: "matches_checksum", fields: "self=MigrationDirectory { path: \"/Users/pedrocavadas/Developer/people/service/prisma/migrations/20201209135949_test_migration\" } checksum_str=\"2eda809ffdb8dab1574fa6efab9897813219bbf4d975875925d79ebbe30c6\"", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 159 }, { target: "migration_core::api", name: "DiagnoseMigrationHistory", file: "migration-engine/core/src/api.rs", line: 148 }]) 

Command: `prisma migrate dev --preview-feature`
Version: `2.13.0`
Binary Version: `833ab05d2a20e822f6736a39a27de4fc8f6b3e49`
Report: https://prisma-errors.netlify.app/report/12287 
OS: `x64 darwin 19.6.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [/root/build/migration-engine/core/src/commands/diagnose_migration_history.rs:103:26] Failed to read migration script: ReadMigrationScriptError(Os { code: 2, kind: NotFound, message: "No such file or directory" }, SpanTrace [{ target: "migration_connector::migrations_directory", name: "read_migration_script", fields: "self=MigrationDirectory { path: \"/Users/pedrocavadas/Developer/people/service/prisma/migrations/20201209135949_test_migration\" }", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 185 }, { target: "migration_connector::migrations_directory", name: "matches_checksum", fields: "self=MigrationDirectory { path: \"/Users/pedrocavadas/Developer/people/service/prisma/migrations/20201209135949_test_migration\" } checksum_str=\"2eda809ffdb8dab1574fa6efab9897813219bbf4d975875925d79ebbe30c6\"", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 159 }, { target: "migration_core::api", name: "DiagnoseMigrationHistory", file: "migration-engine/core/src/api.rs", line: 148 }])

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (/Users/pedrocavadas/Developer/people/node_modules/@prisma/cli/build/index.js:59340:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
[/root/build/migration-engine/core/src/commands/diagnose_migration_history.rs:103:26] Failed to read migration script: ReadMigrationScriptError(Os { code: 2, kind: NotFound, message: "No such file or directory" }, SpanTrace [{ target: "migration_connector::migrations_directory", name: "read_migration_script", fields: "self=MigrationDirectory { path: \"/Users/pedrocavadas/Developer/people/service/prisma/migrations/20201209135949_test_migration\" }", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 185 }, { target: "migration_connector::migrations_directory", name: "matches_checksum", fields: "self=MigrationDirectory { path: \"/Users/pedrocavadas/Developer/people/service/prisma/migrations/20201209135949_test_migration\" } checksum_str=\"2eda809ffdb8dab1574fa6efab9897813219bbf4d975875925d79ebbe30c6\"", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 159 }, { target: "migration_core::api", name: "DiagnoseMigrationHistory", file: "migration-engine/core/src/api.rs", line: 148 }])
```

**Comment by albertoperdomo** [comment]
Closing in favor of https://github.com/prisma/prisma/issues/5170 (duplicate)
