### ISSUE TITLE
Error: [libs/datamodel/connectors/dml/src/datamodel.rs:175:14] Every RelationInfo should have a complementary RelationInfo on the opposite relation field. 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4609]
Command: `prisma introspect`
Version: `2.13.0`
Binary Version: `833ab05d2a20e822f6736a39a27de4fc8f6b3e49`
Report: https://prisma-errors.netlify.app/report/12276 
OS: `x64 darwin 20.1.0`

JS Stacktrace:
```
Error: [libs/datamodel/connectors/dml/src/datamodel.rs:175:14] Every RelationInfo should have a complementary RelationInfo on the opposite relation field.
    at ChildProcess.<anonymous> (/Users/konantian/Projects/Waste-Management-System/waste-front/node_modules/@prisma/cli/build/index.js:4956:28)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_handler::{{closure}}
   6: std::sys_common::backtrace::__rust_end_short_backtrace
   7: _rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: dml::datamodel::Datamodel::find_model_by_relation_field_ref
  11: <datamodel::transform::attributes::relation::RelationAttributeValidator as datamodel::transform::attributes::attribute_validator::AttributeValidator<dml::field::Field>>::serialize
  12: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  13: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
  14: datamodel::transform::dml_to_ast::lower::LowerDmlToAst::lower_field
  15: datamodel::transform::dml_to_ast::lower::LowerDmlToAst::lower_model
  16: datamodel::transform::dml_to_ast::lower::LowerDmlToAst::lower
  17: datamodel::render_datamodel_and_config_to_string
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  20: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  21: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  22: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  23: futures::task_impl::Spawn<T>::enter::{{closure}}
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  25: introspection_engine::main
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: std::rt::lang_start::{{closure}}
  28: std::rt::lang_start_internal
  29: std::rt::lang_start

```

**Comment by albertoperdomo** [comment]
Let's validate if this is gone now.

**Comment by do4gr** [comment]
This should be solved by us splitting the parsing and formatting step here https://github.com/prisma/prisma-engines/pull/1662
