### ISSUE TITLE
Error: [libs/datamodel/connectors/dml/src/model.rs:164:14] We assume an internally valid datamodel before mutating. 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4610]
Command: `prisma introspect`
Version: `2.13.0`
Binary Version: `833ab05d2a20e822f6736a39a27de4fc8f6b3e49`
Report: https://prisma-errors.netlify.app/report/12289 
OS: `x64 darwin 20.1.0`

JS Stacktrace:
```
Error: [libs/datamodel/connectors/dml/src/model.rs:164:14] We assume an internally valid datamodel before mutating.
    at ChildProcess.<anonymous> (/Users/victoriris/Lab/jnj/api-graphql-isaac/node_modules/@prisma/cli/build/index.js:4956:28)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_handler::{{closure}}
   6: std::sys_common::backtrace::__rust_end_short_backtrace
   7: _rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: dml::datamodel::Datamodel::find_relation_field_mut
  11: sql_introspection_connector::re_introspection::enrich
  12: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  16: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  18: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  19: futures::task_impl::Spawn<T>::enter::{{closure}}
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: introspection_engine::main
  22: std::sys_common::backtrace::__rust_begin_short_backtrace
  23: std::rt::lang_start::{{closure}}
  24: std::rt::lang_start_internal
  25: std::rt::lang_start

```

**Comment by tomhoule** [comment]
Should be addressed. Closing.
