### ISSUE TITLE
TypeError: Cannot read property 'custom' of undefined

### ISSUE THREAD

**Issue by akashgiricse** [prisma/prisma#4636]
**Describe the bug**
When running `prisma deploy` I get the following error

```
  command Failed to get the definition file +0ms
  command TypeError: Cannot read property 'custom' of undefined +2ms
TypeError: Cannot read property 'custom' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/prisma/node_modules/prisma-yml/src/yaml.ts:38:21)
    at step (/usr/local/lib/node_modules/prisma/node_modules/prisma-yml/dist/yaml.js:43:23)
    at Object.next (/usr/local/lib/node_modules/prisma/node_modules/prisma-yml/dist/yaml.js:24:53)
    at fulfilled (/usr/local/lib/node_modules/prisma/node_modules/prisma-yml/dist/yaml.js:15:58)
  util timed out +0ms
  output Exiting with code: 0 +0ms

```
**To Reproduce**
1. Install prisma globally by `$ sudo npm install -g prisma`
2. Run `prisma deploy` from the project root directory
3. See error

**Expected behavior**
It should start the interactive process

**Screenshots**
![image](https://user-images.githubusercontent.com/30580217/59024415-7d831200-886f-11e9-8331-0ca7cb58186d.png)

**Versions (please complete the following information):**
 - Prisma CLI version: prisma/1.34.0 (linux-x64) node-v10.16.0
 - OS:  `Ubuntu 18.04`
 - other dependencies:  "graphql-yoga": "^1.17.4"

**Additional context**
This error occurred while I was following *howtographql* tutorial. The stage was [this](https://www.howtographql.com/graphql-js/4-adding-a-database/)

**Comment by akashgiricse** [comment]
The issue was that I had not restarted the server. Sorry.
