### ISSUE TITLE
Error: Error in migration engine. Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\7f02e62\src\connector\postgres\error.rs:67:35] column on null constraint violation error 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4672]
Command: `prisma migrate up --experimental`
Version: `2.3.0`
Binary Version: `e11114fa1ea826f9e7b4fa1ced34e78892fe8e0e`
Report: https://prisma-errors.netlify.app/report/9757 
OS: `x64 win32 10.0.18363`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\7f02e62\src\connector\postgres\error.rs:67:35] column on null constraint violation error

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (C:\Users\Lenovo\train\untitled-allbet\node_modules\@prisma\cli\build\index.js:2:2134122)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Rust Stacktrace:
```
[C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\7f02e62\src\connector\postgres\error.rs:67:35] column on null constraint violation error
```

**Comment by tomhoule** [comment]
This is super old — we'll open a new issue if we see this popping up in error reporting again.
