### ISSUE TITLE
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: 오류: "PaymentStatus" 자료형이 이미 있습니다 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4673]
Command: `prisma migrate up --experimental`
Version: `2.5.0`
Binary Version: `9a670138b1db276001d785a2adcba1584c869d24`
Report: https://prisma-errors.netlify.app/report/10415 
OS: `x64 win32 10.0.18362`

JS Stacktrace:
```
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: 오류: "PaymentStatus" 자료형이 이미 있습니다
   0: migration_core::api::ApplyMigration
           with migration_id="20200819161857"
             at migration-engine\core\src\api.rs:79)
    at Object.<anonymous> (C:\Users\leftpole\Documents\flight-server\node_modules\@prisma\cli\build\index.js:2:2145445)
    at MigrateEngine.handleResponse (C:\Users\leftpole\Documents\flight-server\node_modules\@prisma\cli\build\index.js:2:2143653)
    at LineStream.<anonymous> (C:\Users\leftpole\Documents\flight-server\node_modules\@prisma\cli\build\index.js:2:2145110)
    at LineStream.emit (events.js:210:5)
    at LineStream.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at LineStream.Readable.push (_stream_readable.js:224:10)
    at LineStream.Transform.push (_stream_transform.js:150:32)
    at LineStream._pushBuffer (C:\Users\leftpole\Documents\flight-server\node_modules\@prisma\cli\build\index.js:2:1813582)
```

Rust Stacktrace:
```
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: 오류: "PaymentStatus" 자료형이 이미 있습니다
   0: migration_core::api::ApplyMigration
           with migration_id="20200819161857"
             at migration-engine\core\src\api.rs:79)
```

**Comment by tomhoule** [comment]
Not really actionable at the moment. Can someone reproduce this?
