### ISSUE TITLE
Error: Error in migration engine. Reason: [libs/datamodel/core/src/validator/validate.rs:196:29] called `Option::unwrap()` on a `None` value 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4678]
Command: `prisma migrate save --schema=/home/tamim/Programming/blitz-demo/db/schema.prisma --create-db --experimental`
Version: `2.2.0`
Binary Version: `45c4da4dd3ccd6a322796b228bdf937c7ce884e8`
Report: https://prisma-errors.netlify.app/report/8747 
OS: `x64 linux 5.6.16-1-MANJARO`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [libs/datamodel/core/src/validator/validate.rs:196:29] called `Option::unwrap()` on a `None` value

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (/home/tamim/Programming/blitz-demo/node_modules/@prisma/cli/build/index.js:2:2370192)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Rust Stacktrace:
```
[libs/datamodel/core/src/validator/validate.rs:196:29] called `Option::unwrap()` on a `None` value
```

**Comment by tomhoule** [comment]
Closing as duplicate. We changed a lot around that code too.
