### ISSUE TITLE
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR 22007 (1292): Incorrect datetime value: '0000-00-00 00:00:00' for column 'lastUpdated' at row 1' 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4679]
Command: `prisma migrate up --experimental`
Version: `2.2.0`
Binary Version: `45c4da4dd3ccd6a322796b228bdf937c7ce884e8`
Report: https://prisma-errors.netlify.app/report/8732 
OS: `x64 darwin 19.5.0`

JS Stacktrace:
```
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR 22007 (1292): Incorrect datetime value: '0000-00-00 00:00:00' for column 'lastUpdated' at row 1'
   0: migration_core::api::ApplyMigration
           with migration_id="20200709200412-init"
             at migration-engine/core/src/api.rs:77)
    at Object.registerCallback (/Users/matar/workplace/recruit/advanture-capitalist/backend/node_modules/@prisma/cli/build/index.js:2:2371074)
    at MigrateEngine.handleResponse (/Users/matar/workplace/recruit/advanture-capitalist/backend/node_modules/@prisma/cli/build/index.js:2:2369282)
    at LineStream.a.default.on.e (/Users/matar/workplace/recruit/advanture-capitalist/backend/node_modules/@prisma/cli/build/index.js:2:2370739)
    at LineStream.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at LineStream.Readable.push (_stream_readable.js:220:10)
    at LineStream.Transform.push (_stream_transform.js:151:32)
    at LineStream._pushBuffer (/Users/matar/workplace/recruit/advanture-capitalist/backend/node_modules/@prisma/cli/build/index.js:2:2062886)
    at LineStream._transform (/Users/matar/workplace/recruit/advanture-capitalist/backend/node_modules/@prisma/cli/build/index.js:2:2062707)
```

Rust Stacktrace:
```
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR 22007 (1292): Incorrect datetime value: '0000-00-00 00:00:00' for column 'lastUpdated' at row 1'
   0: migration_core::api::ApplyMigration
           with migration_id="20200709200412-init"
             at migration-engine/core/src/api.rs:77)
```

**Comment by tomhoule** [comment]
This is a WONTFIX.
