### ISSUE TITLE
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR HY000 (1822): Failed to add the foreign key constraint. Missing index for constraint 'Price_ibfk_1' in the referenced table 'Currency'' 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4680]
Command: `prisma migrate up --experimental`
Version: `2.2.0`
Binary Version: `45c4da4dd3ccd6a322796b228bdf937c7ce884e8`
Report: https://prisma-errors.netlify.app/report/8741 
OS: `x64 darwin 19.5.0`

JS Stacktrace:
```
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR HY000 (1822): Failed to add the foreign key constraint. Missing index for constraint 'Price_ibfk_1' in the referenced table 'Currency''
   0: migration_core::api::ApplyMigration
           with migration_id="20200709142035-init"
             at migration-engine/core/src/api.rs:77)
    at Object.<anonymous> (/Users/rickard/Dev/proguitar/proguitar.com/payment-service/node_modules/@prisma/cli/build/index.js:2:2371074)
    at MigrateEngine.handleResponse (/Users/rickard/Dev/proguitar/proguitar.com/payment-service/node_modules/@prisma/cli/build/index.js:2:2369282)
    at LineStream.<anonymous> (/Users/rickard/Dev/proguitar/proguitar.com/payment-service/node_modules/@prisma/cli/build/index.js:2:2370739)
    at LineStream.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at LineStream.Readable.push (_stream_readable.js:209:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._pushBuffer (/Users/rickard/Dev/proguitar/proguitar.com/payment-service/node_modules/@prisma/cli/build/index.js:2:2062886)
    at LineStream._transform (/Users/rickard/Dev/proguitar/proguitar.com/payment-service/node_modules/@prisma/cli/build/index.js:2:2062707)
```

Rust Stacktrace:
```
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: Server error: `ERROR HY000 (1822): Failed to add the foreign key constraint. Missing index for constraint 'Price_ibfk_1' in the referenced table 'Currency''
   0: migration_core::api::ApplyMigration
           with migration_id="20200709142035-init"
             at migration-engine/core/src/api.rs:77)
```

**Comment by tomhoule** [comment]
If this is still happening, it will come up again. Closing this issue for now.
