### ISSUE TITLE
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: foreign key constraint "Influencer_follower_ids_fkey" cannot be implemented 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4685]
Command: `prisma migrate up --experimental`
Version: `2.2.0`
Binary Version: `45c4da4dd3ccd6a322796b228bdf937c7ce884e8`
Report: https://prisma-errors.netlify.app/report/8650 
OS: `x64 darwin 19.4.0`

JS Stacktrace:
```
Error: Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: foreign key constraint "Influencer_follower_ids_fkey" cannot be implemented
   0: migration_core::api::ApplyMigration
           with migration_id="20200707171525-add-user-and-influencer"
             at migration-engine/core/src/api.rs:77)
    at Object.<anonymous> (/Users/jseo/Desktop/javascript_projects/Fitwind-BE/node_modules/@prisma/cli/build/index.js:2:2371074)
    at MigrateEngine.handleResponse (/Users/jseo/Desktop/javascript_projects/Fitwind-BE/node_modules/@prisma/cli/build/index.js:2:2369282)
    at LineStream.<anonymous> (/Users/jseo/Desktop/javascript_projects/Fitwind-BE/node_modules/@prisma/cli/build/index.js:2:2370739)
    at LineStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at LineStream.Readable.push (_stream_readable.js:217:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._pushBuffer (/Users/jseo/Desktop/javascript_projects/Fitwind-BE/node_modules/@prisma/cli/build/index.js:2:2062886)
    at LineStream._transform (/Users/jseo/Desktop/javascript_projects/Fitwind-BE/node_modules/@prisma/cli/build/index.js:2:2062707)
```

Rust Stacktrace:
```
Failure during a migration command: Connector error. (error: Error querying the database: Error querying the database: db error: ERROR: foreign key constraint "Influencer_follower_ids_fkey" cannot be implemented
   0: migration_core::api::ApplyMigration
           with migration_id="20200707171525-add-user-and-influencer"
             at migration-engine/core/src/api.rs:77)
```

**Comment by tomhoule** [comment]
This is from a very old version of migrate, we'll fix it if it comes up again.
