### ISSUE TITLE
Error: Error in migration engine. Reason: [libs/sql-schema-describer/src/walkers.rs:302:18] foreign key references unknown table 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#4695]
Context: This should be a known error

Command: `prisma db push --preview-feature`
Version: `2.11.0`
Binary Version: `58369335532e47bdcec77a2f1e7c1fb83a463918`
Report: https://prisma-errors.netlify.app/report/12051 
OS: `x64 darwin 19.6.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/walkers.rs:302:18] foreign key references unknown table

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/migrate/issues/new

    at ChildProcess.<anonymous> (/Users/Joel/Documents/Projects/2020-FPS/IBBA/ibba-listing-engine/frontend/node_modules/@prisma/cli/build/index.js:60100:23)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Rust Stacktrace:
```
[libs/sql-schema-describer/src/walkers.rs:302:18] foreign key references unknown table
```

**Comment by janpio** [comment]
This has recent reports with 2.17
