### ISSUE TITLE
Internal server error in making any request

### ISSUE THREAD

**Issue by neer17** [prisma/prisma#4711]
**Describe the bug**
Sometimes the following error is produced in playground as well as while running my Nodejs app which interacts with a Postgres database present on Heroku under hobby plan. 

**To Reproduce**
1.Set up a Prisma project with a self hosted database on Heroku using Heroku Postgres Hobby Plan
2.Lift your Docker image locally and try to deploy locally by doing `prisma deploy`
3.Make any request using `prisma-binding` or using `playground`

```
[GraphQL error]: Message: Whoops. Looks like an internal server error. Search your server logs for request ID: local:cjxkrhm3001090692c8z0r5kl, Location: [object Object], Path: users
[Network error]: Error: Whoops. Looks like an internal server error. Search your server logs for request ID: local:cjxkrhm3001090692c8z0r5kl
Whoops. Looks like an internal server error. Search your server logs for request ID: local:cjxkrhm3001090692c8z0r5kl
```         

5. Latest error in docker logs
```
org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:257)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
        at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:71)
        at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
        at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: ec2-54-228-246-214.eu-west-1.compute.amazonaws.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.postgresql.core.PGStream.<init>(PGStream.java:69)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
        ... 16 more
```

**Expected behavior**
Should have returned the results without any errors

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.34.0
 - `prisma` CLI: prisma/1.34.0 (windows-x64) node-v10.16.0
 - OS: `Windows 10 pro`
 - other dependencies: `prisma-binding v2.3.15`

**Additional context**
A similar issue was raised with id 2855 but the error in the docker logs was different.
Moreover, most of the times it works fine. Is error thrown because of the cold boot happens in the Heroku hobby pan?

**Comment by pantharshit00** [comment]
From the logs, it seems the Prisma instance is unable to communicate with your Postgres instance.

Can you please try connecting to your Postgres instance from a GUI and also double check whether a firewall is blocking the connections or not.

**Comment by neer17** [comment]
I have tried connecting to the database and I got successfully connected through pgAdmin4 while `prisma deploy` stuck and subsequently return the **Internal server error**. I don't think the Firewall is blocking the connections as I am able to access the internet while  `prisma deploy` gets stuck.

**Comment by pantharshit00** [comment]
Can you please provide a reproduction for this issue?

**Comment by neer17** [comment]
Change the datamodel and do `prisma deploy`. It randomly stuck there and after few minutes _Internal server error_ is thrown.
