### ISSUE TITLE
A unique constraint would be violated upon upsert

### ISSUE THREAD

**Issue by joshhopkins** [prisma/prisma#4760]
**Describe the bug**

Often seeing a unique constraint violation error when batching data using `prisma.upsert()`. After much testing it appears to be an issue with Prisma client.

Schema

```
type User {
    id: ID! @id(strategy: NONE)
   ...
}
```

Output of client with debug: true
```
{ Error: A unique constraint would be violated on User. Details: Field name = id
    at BatchedGraphQLClient.<anonymous> (/Users/joshhopkins/Projects/test/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:77:35)
    at step (/Users/joshhopkins/Projects/test/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:40:23)
    at Object.next (/Users/joshhopkins/Projects/test/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:21:53)
    at fulfilled (/Users/joshhopkins/Projects/test/node_modules/http-link-dataloader/dist/src/BatchedGraphQLClient.js:12:58)
    at processTicksAndRejections (internal/process/next_tick.js:81:5) result: { data: null, errors: [ [Object] ], status: 200 } }
```

**Versions (please complete the following information):**
 - Connector: `Postgres`
 - Prisma Server: 1.34.1
 - `prisma` CLI: `prisma/1.34.1 (darwin-x64) node-v11.7.0`]
 - OS: `MacOS 10.14.5`

**Comment by pantharshit00** [comment]
Hey, can you please provide me with a full reproduction? 

Unable to reproduce with a minimal example.
