### ISSUE TITLE
ERROR: relation "CloudSecret" does not exist

### ISSUE THREAD

**Issue by neer17** [prisma/prisma#4763]
**Describe the bug**
Getting "CloudSecret" does not exist error on resetting the Postgres database on Heroku

**To Reproduce**
Reset the Postgres database on Heroku then check the docker logs

**Expected behavior**
Should have connected to the database

**Error**
```
org.postgresql.util.PSQLException: ERROR: relation "CloudSecret" does not exist
prisma_1  |   Position: 36
prisma_1  |     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
prisma_1  |     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
prisma_1  |     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
prisma_1  |     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
prisma_1  |     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
prisma_1  |     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
prisma_1  |     at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
prisma_1  |     at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$queryToDBIO$1(SharedSlickExtensions.scala:17)   
prisma_1  |     at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$jooqToDBIO$1(SharedSlickExtensions.scala:56)    
prisma_1  |     at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
prisma_1  |     at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
prisma_1  |     at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
prisma_1  |     at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
prisma_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
prisma_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
prisma_1  |     at java.lang.Thread.run(Thread.java:748)
```

**Versions (please complete the following information):**
 - Connector:  `Postgres`
 - Prisma Server: `1.34.0`
 - `prisma` CLI: `prisma/1.34.3 (windows-x64) node-v10.16.0`
 - OS: `Windows 10 pro`
 - other dependencies: `prisma-binding: 2.3.15`

**Additional context**
The same issue was opened last year but was closed by the bot due to inactivity and without any viable solution https://github.com/prisma/prisma/issues/2921

**Comment by pantharshit00** [comment]
If you reset the database, it also resets the Management API tables. So you will need to restart your Prisma dyno in order to create those again. Prisma can't automatically recreate them. Just restart all dynos from the "more" menu and the error will be fixed
