### ISSUE TITLE
add the platform "debian-openssl-1.1.x"

### ISSUE THREAD

**Issue by alan345** [prisma/prisma#4769]
I am using prisma `"@prisma/client": "2.13.0",` and `"@prisma/cli": "2.13.0",`

After building the typescript express server, no error was founded. When later `prisma.companie.findMany()`  was invoked, it drops the error below. Unfortunately it was in production and we were not aware of this for a long time.

After rebuilding the typescript express server, it works fine. I cannot reproduce this error. I am now very concern this error might popup again in production.

Any recommendation? 

*Error:*

```
1|taskCron | 2020-12-22 07:30 -08:00: { Error: 
1|taskCron | 2020-12-22 07:30 -08:00: Invalid `prisma.companie.findMany()` invocation:
1|taskCron | 2020-12-22 07:30 -08:00: 
1|taskCron | 2020-12-22 07:30 -08:00: 
1|taskCron | 2020-12-22 07:30 -08:00:   Query engine binary for current platform "debian-openssl-1.1.x" could not be found.
1|taskCron | 2020-12-22 07:30 -08:00: This probably happens, because you built Prisma Client on a different platform.
1|taskCron | 2020-12-22 07:30 -08:00: (Prisma Client looked in "/home/ubuntu/nacho/server/node_modules/@prisma/client/runtime/query-engine-debian-openssl-1.1.x")
1|taskCron | 2020-12-22 07:30 -08:00: 
1|taskCron | 2020-12-22 07:30 -08:00: Searched Locations:
1|taskCron | 2020-12-22 07:30 -08:00: 
1|taskCron | 2020-12-22 07:30 -08:00:   /home/ubuntu/nacho/server/node_modules/.prisma/client
1|taskCron | 2020-12-22 07:30 -08:00:   /home/ubuntu/nacho/server/node_modules/@prisma/client
1|taskCron | 2020-12-22 07:30 -08:00:   /home/ubuntu/nacho/server/node_modules/@prisma/client
1|taskCron | 2020-12-22 07:30 -08:00:   /home/ubuntu/nacho/server/node_modules/.prisma/client
1|taskCron | 2020-12-22 07:30 -08:00:   /home/ubuntu/nacho/server/prisma/prisma
1|taskCron | 2020-12-22 07:30 -08:00:   /home/ubuntu/nacho/server/node_modules/.prisma/client
1|taskCron | 2020-12-22 07:30 -08:00: 
1|taskCron | 2020-12-22 07:30 -08:00: 
1|taskCron | 2020-12-22 07:30 -08:00: To solve this problem, add the platform "debian-openssl-1.1.x" to the "generator" block in the "schema.prisma" file:
1|taskCron | 2020-12-22 07:30 -08:00: generator client {
1|taskCron | 2020-12-22 07:30 -08:00:   provider      = "prisma-client-js"
1|taskCron | 2020-12-22 07:30 -08:00:   binaryTargets = ["native"]
1|taskCron | 2020-12-22 07:30 -08:00: }
1|taskCron | 2020-12-22 07:30 -08:00: 
1|taskCron | 2020-12-22 07:30 -08:00: Then run "prisma generate" for your changes to take effect.
1|taskCron | 2020-12-22 07:30 -08:00: Read more about deploying Prisma Client: https://pris.ly/d/client-generator
1|taskCron | 2020-12-22 07:30 -08:00:     at PrismaClientFetcher.request (/home/ubuntu/nacho/server/node_modules/@prisma/client/runtime/index.js:79361:15)
1|taskCron | 2020-12-22 07:30 -08:00:     at process._tickCallback (internal/process/next_tick.js:68:7) clientVersion: '2.12.1' }
```

**Comment by pantharshit00** [comment]
Hey @alan345 

Looks like you developed your code in a different environment and then deployed it in a different environment. Prisma uses a compiled Rust binary under the hood and it is platform specific so for example you can't use Mac binary when working in windows.


If you want to make sure binaries for additional platform is available all the time, you can add that to targets like so:

```prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "debian-openssl-1.1.x"]
}
```

Read more here: https://www.prisma.io/docs/concepts/components/prisma-schema/generators#binary-targets-prisma-client-js

**Comment by pantharshit00** [comment]
Closing due to inactivity
