### ISSUE TITLE
Subscription fails with graphql alias

### ISSUE THREAD

**Issue by a2er** [prisma/prisma#4772]
**Describe the bug**
Using graphql alias in subscriptions causes an exception `java.util.NoSuchElementException: JsError.get.`

**To Reproduce**
1. Subscribe data with graphql alias:
```
subscription {
  example: user {
    mutation
    node {
      id
      name
      state
    }
    previousValues {
      id
      name
      state
    }
  }
}
```
2. Trigger mutation:
```
mutation {
  createUser(
    data: {
      name: "John Doe"
      state: BUSY
    }
  ) {
    id
  }
}
```
3. Exception `java.util.NoSuchElementException: JsError.get` thrown at prisma server. No subscription update.

**Expected behavior**
Same behaviour as without alias except result structure is `data.example.*` instead of `data.user.*`.

**Versions:**
 - Connector: `Postgres`
 - Prisma Server: `prismagraphql/prisma:1.34 (Docker Image)`
 - OS: `Windows 10`
 - [Datamodel](https://github.com/a2er/tm-data-service/tree/e2df76100c13e9f0749d52cf51b31d319480fa1e)

**Full exception**
(Docker container log)
```
java.util.NoSuchElementException: JsError.get
	at play.api.libs.json.JsError.get(JsResult.scala:43)
	at play.api.libs.json.JsError.get(JsResult.scala:42)
	at com.prisma.subscriptions.SubscriptionExecutor$.$anonfun$execute$4(SubscriptionExecutor.scala:116)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by pantharshit00** [comment]
I can confirm this

**Comment by a2er** [comment]
The reason seems to be [here](https://github.com/prisma/prisma/blob/e5b2b56e55cfa99496c7163d53bbd6fa356976da/server/servers/api/src/main/scala/com/prisma/subscriptions/SubscriptionExecutor.scala#L115). There should be a determination if an alias is set or not. Unfortunately i don't speek scala, so i can't help more.
