### ISSUE TITLE
Prisma Deploy results in FetchError: request to http://localhost:4466/management failed, reason: socket hang up

### ISSUE THREAD

**Issue by Andrew1325** [prisma/prisma#4816]
I have looked at other issues around this error but they seem unrelated.

Key points:

Mac OS 10.14.6
Docker (desktop) version 2.1.0.1
Prisma version 1.34.5

I have a prisma project I am developing. Initially I was using a local postgres database and could deploy using "prisma deploy -e ../config/dev.env" and it would promptly update everything and it would work fine. As I am nearing production readiness I changed to a Heroku Postgres database that will be used for the final project. I was able to run "docker-compose up -d" successfully and then ran "prisma deploy -e ../config/dev.env".

This did run without error and successfully deployed however it took about 2 hours to do so.

I have now made another change to my datamodel.prisma by adding one new type (with no relations) and run prisma deploy again to update and I get the title error.

Here is the terminal output during deploy: 

```
Andrews-iMac:prisma redqueen$ prisma deploy -e ../config/dev.env
  environment { needsAuth: false } +0ms
  client is local cluster: true +0ms
  client Sending query to cloud api +1ms
  client https://api2.cloud.prisma.sh +0ms
  client {
  client       me {
    //... many more lines
 client { name: 'default', stage: 'default' } +0ms
  client { project: { name: 'default', stage: 'default' } } +28s

Deploying service `default` to stage `default` to server `local`...  client Sending query to cluster local +2ms
  client http://localhost:4466/management +0ms
    //... many more lines
client   types:
  client    'type User //... many more lines
 client   dryRun: undefined,
  client   secrets: [ '*************' ],
  client   subscriptions: [],
  client   force: undefined } +2ms
 !
FetchError: request to http://localhost:4466/management failed, reason: socket hang up
    at ... 
```

As I say the initial deploy was fine even though slow.

docker ps
```
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                    NAMES
d0e350516373        prismagraphql/prisma:1.34   "/bin/sh -c /app/sta…"   7 days ago          Up 45 minutes       0.0.0.0:4466->4466/tcp   prisma_prisma_1
```
I can run prisma token -e ../config/dev.env and receive a token

I can access localhost:4466 and run queries etc. I can access localhost:4466/management and run a query like this:

```
query {
	listProjects {
    name
    datamodel
  }
}
```
and I get a result so I know it is all running. I've tried increasing the memory and swap available to docker and have tried removing my new 'type' from datamodel.prisma to see if I get an 'up to date' message but get the same error.

I just need to know how I can deploy this successfully.

**Comment by pantharshit00** [comment]
Can you please check the container logs using `docker-compose logs`?

**Comment by Andrew1325** [comment]
This is what docker-compose logs showed:

```
Andrews-iMac:prisma redqueen$ docker logs 81d6ebf1df45
No log level set, defaulting to INFO.
[INFO] {} - Starting...
[INFO] {} - Start completed.
Aug 19, 2019 7:38:45 AM org.postgresql.core.v3.ConnectionFactoryImpl log
WARNING: SQLException occurred while connecting to ec2-54-227-251-33.compute-1.amazonaws.com:5432
org.postgresql.util.PSQLException: FATAL: permission denied for database "postgres"
  Detail: User does not have CONNECT privilege.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
        at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:68)
        at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
        at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
 
Aug 19, 2019 7:38:45 AM org.postgresql.Driver connect
SEVERE: Connection error: 
org.postgresql.util.PSQLException: FATAL: permission denied for database "postgres"
  Detail: User does not have CONNECT privilege.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
        at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:68)
        at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
        at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
        at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
        at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
 
[INFO] Initializing workers...
[INFO] Obtaining exclusive agent lock...
[INFO] Successfully started 1 workers.
Server running on :4466
[INFO] Obtaining exclusive agent lock... Successful.
[INFO] Deployment worker initialization complete.
[Warning] Management authentication is disabled. Enable it in your Prisma config to secure your server.
Trying (via loadLibrary) jnidispatch
Looking in classpath from sun.misc.Launcher$AppClassLoader@7852e922 for /com/sun/jna/linux-x86-64/libjnidispatch.so
Found library resource at jar:file:/app/lib/net.java.dev.jna.jna-4.5.2.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
Trying /tmp/jna-3506402/jna217119892927431931.tmp
Found jnidispatch at /tmp/jna-3506402/jna217119892927431931.tmp
Looking for library 'jwt_native'
Adding paths from jna.library.path: null
Trying libjwt_native.so
Adding system paths: [/lib64, /usr/lib, /lib]
Trying /lib/libjwt_native.so
Found library 'jwt_native' at /lib/libjwt_native.so
```

I wasn't able to resolve this in development but I did move onto production deployment and was able to deploy my container to heroku using Prisma Cloud and the deployment went perfectly and finished in about 20 seconds. 

I therefore am not sure this issue needs to remain open unless you see something in the logs.

**Comment by pantharshit00** [comment]
It looks fine, feel free to open a new issue if something like this happens again.
