### ISSUE TITLE
Problem when using alias for field names

### ISSUE THREAD

**Issue by KushalKatta** [prisma/prisma#4820]
**Describe the bug**
I want to be able to alias a field name, but when I do so in graphql-yoga server connected to prisma server, i get an error saying `Cannot return null for non-nullable field`.
I checked the requests made to prisma server, and came to know the request and response were successful to database, which means prisma server is responding with given alias but graphql server throws an unexpected error.

**To Reproduce**
1. Datamodel.prisma file:
```
type Model {
  id: ID! @id
  name: String!
}
```

2. graphql server index js:
```
const { GraphQLServer } = require('graphql-yoga');
const { Prisma } = require('prisma-binding');
  
const server = new GraphQLServer({
	typeDefs: './schema.graphql',
	resolvers,
	context: {
		db: new Prisma({
			typeDefs: './generated/prisma.graphql', // the auto-generated GraphQL schema of the Prisma API
			endpoint: 'http://localhost:4466', // the endpoint of the Prisma API
			debug: true, // log all GraphQL queries & mutations sent to the Prisma API
		}),
	},
});

server.start(() => console.log('Server is running on http://localhost:4000'));

```

3. In graphql server, resolvers:
```
  Query: {
    model(root, args, context) {
      return context.db.query.model(args);
    }
  }
```

4. Now after creating a few record in Graphql Playground(in graphql server, not prisma server) on port 4000 :
```
{
  model({where: {id: "5d41f66be03dd800076c79df"}) {
    id
    value: name
  }
}
```

5. **I am getting error saying `Cannot return null for non-nullable field Model.name`**

Console Log:
```
Request to http://localhost:4466:
query:
query ($_v0_where: ModelWhereUniqueInput!) {
  model(where: $_v0_where) {
    id
    value: name
  }
}
operationName: null
variables:
{
  "_v0_where": {
    "id": "5d41f66be03dd800076c79df"
  }
}
Response from http://localhost:4466:
{
  "model": {
    "id": "5d41f66be03dd800076c79df",
    "value": "Some name"
  }
}
Error: Cannot return null for non-nullable field Model.name.
    at completeValue (/Users/kushalkatta/workspace/Graphql/accounting/node_modules/graphql/execution/execute.js:596:13)
    at completeValueCatchingError (/Users/kushalkatta/workspace/Graphql/accounting/node_modules/graphql/execution/execute.js:531:19)
    at resolveField (/Users/kushalkatta/workspace/Graphql/accounting/node_modules/graphql/execution/execute.js:471:10)
    at executeFields (/Users/kushalkatta/workspace/Graphql/accounting/node_modules/graphql/execution/execute.js:311:18)
    at collectAndExecuteSubfields (/Users/kushalkatta/workspace/Graphql/accounting/node_modules/graphql/execution/execute.js:747:10)
    at completeObjectValue (/Users/kushalkatta/workspace/Graphql/accounting/node_modules/graphql/execution/execute.js:737:10)
    at completeValue (/Users/kushalkatta/workspace/Graphql/accounting/node_modules/graphql/execution/execute.js:626:12)
    at /Users/kushalkatta/workspace/Graphql/accounting/node_modules/graphql/execution/execute.js:528:16
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

```

**Expected behavior**
I should get response something like this
```
 "data": {
    "model": {
        id: "5d41f66be03dd800076c79df",
        value: "Some name"
    }
  },
```

**Versions:**
 - Connector: `MongoDB`
 - Prisma CLI version: prisma/1.34.5 (darwin-x64) node-v11.14.0
 - Prisma server version: 1.36-alpha-131
 - OS: `OS X High Sierra`
 - other dependencies: `graphql-yoga`, `prisma-binding`, `graphql-tools`

**Comment by pantharshit00** [comment]
This is a drawback of prisma-binding. That's why we introduced Prisma Client.

Use that to solve this limitation.
