### ISSUE TITLE
Introspection with SQLite says DB is empty but there are tables

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma#4821]
## Bug description

You can find a reproduction of the issue in this [repo](https://github.com/nikolasburk/apollo-server-tutorial):

```
git clone git@github.com:nikolasburk/apollo-server-tutorial.git
cd apollo-server-tutorial
npm install
npx prisma introspect
```

This should introspect the SQLite file at `./store.db` which has two tables: `trips` and `users`:

```sql
CREATE TABLE `trips` (`id` INTEGER PRIMARY KEY, `createdAt` DATETIME, `updatedAt` DATETIME, `launchId` INTEGER, `userId` INTEGER);
CREATE TABLE `users` (`id` INTEGER PRIMARY KEY, `createdAt` DATETIME, `updatedAt` DATETIME, `email` VARCHAR(255), `token` VARCHAR(255));
```

However, when running the `npx prisma introspect` command, I'm seeing this output (with `DEBUG` set to `*`):

```
$ npx prisma introspect
  tryLoadEnv Environment variables loaded from /Users/nikolasburk/Desktop/fullstack-tutorial/start/server/.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

Introspecting based on datasource defined in prisma/schema.prisma …
  IntrospectionEngine:rpc starting introspection engine with binary: /Users/nikolasburk/Desktop/fullstack-tutorial/start/server/node_modules/@prisma/engines/introspection-engine-darwin +0ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"sqlite\"\n  url      = \"file:./store.db\"\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n"}]} +10ms
  IntrospectionEngine:rpc {
  IntrospectionEngine:rpc   jsonrpc: '2.0',
  IntrospectionEngine:rpc   error: {
  IntrospectionEngine:rpc     code: 4466,
  IntrospectionEngine:rpc     message: 'An error happened. Check the data field for details.',
  IntrospectionEngine:rpc     data: {
  IntrospectionEngine:rpc       is_panic: false,
  IntrospectionEngine:rpc       message: 'The introspected database was empty: file:./store.db',
  IntrospectionEngine:rpc       meta: [Object],
  IntrospectionEngine:rpc       error_code: 'P4001'
  IntrospectionEngine:rpc     }
  IntrospectionEngine:rpc   },
  IntrospectionEngine:rpc   id: 1
  IntrospectionEngine:rpc } +9ms
Error: Error: 
P4001 The introspected database was empty: 

prisma introspect could not create any models in your schema.prisma file and you will not be able to generate Prisma Client with the prisma generate command.

To fix this, you have two options:

- manually create a table in your database (using SQL).
- make sure the database connection URL inside the datasource block in schema.prisma points to a database that is not empty (it must contain at least one table).

Then you can run prisma introspect again. 

    at Introspect2.parse (/Users/nikolasburk/Desktop/fullstack-tutorial/start/server/node_modules/@prisma/cli/build/index.js:105567:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/Users/nikolasburk/Desktop/fullstack-tutorial/start/server/node_modules/@prisma/cli/build/index.js:106192:18)
```

## Prisma information

```
$ npx prisma -v
  tryLoadEnv Environment variables loaded from /Users/nikolasburk/Desktop/fullstack-tutorial/start/server/.env +0ms
Environment variables loaded from .env
@prisma/cli          : 2.13.1
@prisma/client       : Not found
Current platform     : darwin
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.329.0
```

**Comment by nikolasburk** [comment]
Ok, this was my bad, I was pointing it to the wrong directory! We might want to improve the error message for this but I'm closing this issue as the problem is resolved 👍
