### ISSUE TITLE
No service with name 'default' and stage 'default' found

### ISSUE THREAD

**Issue by ethan605** [prisma/prisma#4855]
**Describe the bug**
I'm getting errors related to `name 'default' and stage 'default'` when initializing new prisma project

**To Reproduce**
1. Follow all the steps from [official guide](https://www.prisma.io/docs/get-started/01-setting-up-prisma-new-database-TYPESCRIPT-t002/) strictly
2. Get `com.prisma.deploy.schema.InvalidProjectId: No service with name 'default' and stage 'default' found` error when run `prisma deploy`
3. Get this error when performing a simple query from `http://localhost:4466/graphql`:

  - Query:

```graphql
query {
  user {
    id
    name
  }
}
```

  - Response:

```json
{
  "errors": [
    {
      "message": "Project not found: 'graphql_default'",
      "code": 3016,
      "requestId": "local:cjzs556h5000f0754vc6k36qd"
    }
  ]
}
```

**Expected behavior**
Working without errors

P/s: It actually was running flawlessly some days before, but today I can't manage to make it work again

**Versions**
 - Connector: `MongoDB`
 - Prisma Server: `1.34.6`
 - `prisma` CLI: `prisma/1.34.6 (darwin-x64) node-v10.16.3`
 - OS: `OS X Mojave - 10.14.6`

**Additional context**
Logs from Docker:

```
$ docker logs hello-world_prisma_1
No log level set, defaulting to INFO.
[INFO] Cluster created with settings {hosts=[mongo:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
[INFO] Exception in monitor thread while connecting to server mongo:27017
Exception opening socket
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$OpenCompletionHandler.failed(AsynchronousSocketChannelStream.java:272)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
	at sun.nio.ch.Invoker$2.run(Invoker.java:218)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
	... 1 more
[INFO] Initializing workers...
[INFO] Obtaining exclusive agent lock...
[INFO] Obtaining exclusive agent lock... Successful.
[INFO] Successfully started 1 workers.
[INFO] No server chosen by com.mongodb.async.client.ClientSessionHelper$1@70a6c292 from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=mongo:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]}. Waiting for 30000 ms before timing out
[INFO] Opened connection [connectionId{localValue:2, serverValue:1}] to mongo:27017
[INFO] Monitor thread successfully connected to server with description ServerDescription{address=mongo:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 6, 13]}, minWireVersion=0, maxWireVersion=6, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=16638401}
Server running on :4466
[INFO] Opened connection [connectionId{localValue:3, serverValue:2}] to mongo:27017
[INFO] Deployment worker initialization complete.
[Warning] Management authentication is disabled. Enable it in your Prisma config to secure your server.
{"key":"error/handled","requestId":"local:cjzs54qg500020754mbbzqni9","payload":{"exception":"com.prisma.deploy.schema.InvalidProjectId: No service with name 'default' and stage 'default' found","query":"\n      query($name: String! $stage: String!) {\n        project(name: $name stage: $stage) {\n          name\n          stage\n        }\n      }\n    ","variables":"{\"name\":\"default\",\"stage\":\"default\"}","code":"4000","stack_trace":"com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$3(SchemaBuilder.scala:144)\\n scala.Option.getOrElse(Option.scala:121)\\n com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$2(SchemaBuilder.scala:144)\\n scala.util.Success.$anonfun$map$1(Try.scala:251)\\n scala.util.Success.map(Try.scala:209)\\n scala.concurrent.Future.$anonfun$map$1(Future.scala:288)\\n scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)\\n scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)","message":"No service with name 'default' and stage 'default' found"}}
[Debug] Initializing deployment worker for default_default
[Debug] Scheduling deployment for project default_default
[INFO] Opened connection [connectionId{localValue:4, serverValue:3}] to mongo:27017
[Debug] Applied migration for project default_default
```

Formatted `[Warning]`:
```json
{
  "key": "error/handled",
  "requestId": "local:cjzs54qg500020754mbbzqni9",
  "payload": {
    "exception": "com.prisma.deploy.schema.InvalidProjectId: No service with name 'default' and stage 'default' found",
    "query": "\n      query($name: String! $stage: String!) {\n        project(name: $name stage: $stage) {\n          name\n          stage\n        }\n      }\n    ",
    "variables": "{\"name\":\"default\",\"stage\":\"default\"}",
    "code": "4000",
    "stack_trace": "com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$3(SchemaBuilder.scala:144)\\n scala.Option.getOrElse(Option.scala:121)\\n com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$2(SchemaBuilder.scala:144)\\n scala.util.Success.$anonfun$map$1(Try.scala:251)\\n scala.util.Success.map(Try.scala:209)\\n scala.concurrent.Future.$anonfun$map$1(Future.scala:288)\\n scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)\\n scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)\\n scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)\\n akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)\\n akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)\\n scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)\\n scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)\\n akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)\\n akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)\\n akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)\\n akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\\n akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\\n akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\\n akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)",
    "message": "No service with name 'default' and stage 'default' found"
  }
}
```

Formatted `"query"`:
```graphql
query($name: String! $stage: String!) {
  project(name: $name stage: $stage) {
    name
    stage
  }
}
```

Formatted `"variables"`:
```json
{ "name":"default", "stage":"default" }
```

Formatted stack trace:
```
com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$3(SchemaBuilder.scala:144)
 scala.Option.getOrElse(Option.scala:121)
 com.prisma.deploy.schema.SchemaBuilderImpl.$anonfun$projectField$2(SchemaBuilder.scala:144)
 scala.util.Success.$anonfun$map$1(Try.scala:251)
 scala.util.Success.map(Try.scala:209)
 scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
 scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
 scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
 scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
 akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
 akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
 scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
 akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
 akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
 akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
 akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by nealoke** [comment]
I have had this issue sometimes as well, for me this worked:

- Run `docker-compose down` (if you are using `docker-compose`, otherwise stop the docker container)
- Prune your docker (warning, will remove everything from docker, eg. containers, networks, images, ...) `docker system prune --all`
- Build and start the docker image

**Comment by ethan605** [comment]
Thanks @nealoke, but unfortunately it didn't work for me. Still getting the same error.

P/s: I use `docker-compose` as in the official guide

**Comment by nealoke** [comment]
You did deploy it right? :)

**Comment by ethan605** [comment]
@nealoke yes, I've deployed everything successfully:
- Deploy the docker containers with `docker-compose up --detach`
- Deploy the Prisma schemas with `prisma deploy`

But the errors are still there

**Comment by EhsanSarshar** [comment]
I have the same problem

**Comment by debianmaster** [comment]
getting same error.  `No service with name 'default' and stage 'default' found"`

**Comment by mataardit** [comment]
Getting the same error
```
{
  "data" : {
    "deploy" : null
  },
  "errors" : [ {
    "locations" : [ {
      "line" : 2,
      "column" : 2
    } ],
    "path" : [ "deploy" ],
    "code" : 4000,
    "message" : "No service with name 'default' and stage 'default' found",
    "requestId" : "local:ck345uay3000007988j5rlfpq"
  } ]
}
```
