### ISSUE TITLE
 [WARNING] {} - Failed to validate connection {} ({}). Possibly consider using a shorter maxLifetime value.

### ISSUE THREAD

**Issue by Melv** [prisma/prisma#4864]
We've upgraded our prisma-server (containers) from `1.18.1` to `1.34.3`

Checking the `docker logs`, if we start a session from the frontend we see in all instance this warning:

```
2019-09-01T06:00:12.729724084Z [WARNING] {} - Failed to validate connection {} ({}). Possibly consider using a shorter maxLifetime value.
```
Sometimes this warning is accompanied with some more warnings/errors (on our online instances)
```
2019-08-28T16:19:51.216560169Z [WARNING] {} - Failed to validate connection {} ({}). Possibly consider using a shorter maxLifetime value.
2019-08-28T16:19:51.217342974Z java.sql.SQLTransientConnectionException: database - Connection is not available, request timed out after 5006ms.
2019-08-28T16:19:51.217485076Z 	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
2019-08-28T16:19:51.217504776Z 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
2019-08-28T16:19:51.217513176Z 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
2019-08-28T16:19:51.217528176Z 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
2019-08-28T16:19:51.217534376Z 	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
2019-08-28T16:19:51.217568676Z 	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
2019-08-28T16:19:51.217575676Z 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
2019-08-28T16:19:51.217588476Z 	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
2019-08-28T16:19:51.217592976Z 	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
2019-08-28T16:19:51.217609576Z 	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
2019-08-28T16:19:51.217613476Z 	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
2019-08-28T16:19:51.217616776Z 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:275)
2019-08-28T16:19:51.217620076Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-08-28T16:19:51.217623377Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-08-28T16:19:51.217629377Z 	at java.lang.Thread.run(Thread.java:748)
2019-08-28T16:19:51.217879278Z Caused by: java.sql.SQLException: Connection.setNetworkTimeout cannot be called on a closed connection
2019-08-28T16:19:51.217900579Z 	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getSqlException(ExceptionMapper.java:197)
2019-08-28T16:19:51.217904979Z 	at org.mariadb.jdbc.MariaDbConnection.setNetworkTimeout(MariaDbConnection.java:1593)
2019-08-28T16:19:51.217908579Z 	at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:550)
2019-08-28T16:19:51.217911979Z 	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:165)
2019-08-28T16:19:51.217915179Z 	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:179)
2019-08-28T16:19:51.217918579Z 	... 13 more
```
**To Reproduce**
- upgrade to `1.34.3`

**Expected behavior**
Not show those warning/errors.

**Versions:**
 - Connector: `MySQL`
 - Prisma Server: `1.34.3.`
 - `prisma` CLI: `Prisma CLI version: prisma/1.34.3 (linux-x64) node-v10.16.0`
 - OS: 
   - `Linux 4.18.0-1024-azure #25~18.04.1-Ubuntu SMP Fri Jun 28 23:27:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
   - `Linux 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` 

**Additional context**
- the instances connect to databases hosted on Azure, AWS (RDS), and local mysql container
- on our frontend we notice some problems with realtime subscriptions/websocket (could this be related?)

**Comment by dhulme** [comment]
I'm having the same error connecting to an Azure DB. I'm not getting any data back from queries, but I don't know if this is the cause or if problem is elsewhere. Are your queries returning data ok?

**Comment by Melv** [comment]
The queries are returning data in our case.

It is a *warning*  that it can *not validate* a connection, maybe we have one and you don't hence no queries.

It would be nice if someone know which lib/.service throws this warning

**Comment by theRocket** [comment]
I just experienced this also on 1.34.7. It appears the prisma docker container lost its remote connection overnight. I had a terminal session going with MySQL simultaneously, and the subsequent (more direct) query reestablished the connection:

`mysql> select * from OwnershipType;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    1266
Current database: proteus@dev`

Then Prisma gets a response. I wonder what is required to make it tell MySQL to wake up?

**Comment by inlightmedia** [comment]
Getting this as well. It adds a lot of noise to the prisma logs.
