### ISSUE TITLE
Explicit many-to-many relation doesn't work

### ISSUE THREAD

**Issue by jferrettiboke** [prisma/prisma#4909]
## Bug description

Explicit many-to-many relation doesn't work. I get an error when executing the mutations.

## How to reproduce

`prisma.schema`

```prisma
model User {
  id        Int             @id @default(autoincrement())
  createdAt DateTime        @default(now())
  updatedAt DateTime        @updatedAt
  deletedAt DateTime?
  firstName String
  lastName  String
  email     String          @unique
  accounts  AccountMember[]
}

model Account {
  id        Int             @id @default(autoincrement())
  createdAt DateTime        @default(now())
  updatedAt DateTime        @updatedAt
  deletedAt DateTime?
  name      String
  members   AccountMember[]
}

model AccountMember {
  account   Account           @relation(fields: [accountId], references: [id])
  accountId Int // relation scalar field (used in the `@relation` attribute above)
  user      User              @relation(fields: [userId], references: [id])
  userId    Int // relation scalar field (used in the `@relation` attribute above)
  createdAt DateTime          @default(now())
  role      AccountMemberRole

  @@id([accountId, userId])
}

enum AccountMemberRole {
  ADMIN
}
```

**CRUD**

```ts
try {
  const user = await ctx.prisma.user.create({
    data: {
      email: `alice@domain.com`,
      firstName: "Alice",
      lastName: "Doe",
    },
  });
  const account = await ctx.prisma.account.create({
    data: {
      name: "My first account",
    },
  });
  await ctx.prisma.accountMember.create({
    data: {
      account: { connect: { id: account.id } },
      user: { connect: { id: user.id } },
      role: "ADMIN",
    },
  });
} catch (error) {
  console.log(error);
}
```

**Error**

```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.account.create()` invocation:


  Failed to validate the query: `Field does not exist on enclosing type.` at `Mutation.createOneAccount.Account.userId`
    at PrismaClientFetcher.request ([...]/api/node_modules/@prisma/client/runtime/index.js:78130:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async resolve (webpack-internal:///./graphql/types.ts:54:27) {
  code: 'P2009',
  clientVersion: '2.14.0',
  meta: {
    query_validation_error: 'Field does not exist on enclosing type.',
    query_position: 'Mutation.createOneAccount.Account.userId'
  }
}
```

## Environment & setup

- OS: macOS
- Database: PostgreSQL v10.3
- Node.js version: v14.7.0
- Prisma version: v2.14.0

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/104727599-99dd7500-575b-11eb-9e40-c096a4c8200f.png)


I am unable to reproduce this with latest dev version as well as `2.14`. Please make sure you generated the client after editing the schema using `prisma generate` and your database is upto date the the schema changes.

**Comment by jferrettiboke** [comment]
Closing this for now since I don't see the error anymore after updating Prisma.

Thanks @pantharshit00.

**Comment by forrestwilkins** [comment]
Running `prisma generate` resolved the issue for me as well.
