### ISSUE TITLE
Namespace '"/vercel/workpath0/node_modules/@prisma/client/index"' has no exported member when deploying on vercel

### ISSUE THREAD

**Issue by creativiii** [prisma/prisma#4973]
## Bug description

I've been trying to convert a Prisma project to serverless by using the [example provided in the repository](https://github.com/prisma/prisma-examples/tree/latest/deployment-platforms/vercel-graphql).

This works perfectly locally and I'm able to run it in development and successfully connect to my database and return records. The project installs and builds just fine.

Once I push it to Vercel unfortunately it doesn't seem to work. 

1) One of the generated files inside `node_modules/.prisma` doesn't seem to have an exported member I need. This returns the following error:
```
  | NowBuildError: api/_lib/generated/prisma-nexus.ts(17,18): error TS2694: Namespace '"/vercel/workpath0/node_modules/@prisma/client/index"' has no exported member 'Server'.
-- | --
21:56:16.872 | at createTSError (/vercel/746c5768655bc069/.build-utils/.builder/node_modules/@vercel/node/dist/index.js:99041:16)
21:56:16.872 | at reportTSError (/vercel/746c5768655bc069/.build-utils/.builder/node_modules/@vercel/node/dist/index.js:99047:23)
21:56:16.872 | at getOutputTypeCheck (/vercel/746c5768655bc069/.build-utils/.builder/node_modules/@vercel/node/dist/index.js:99134:17)
21:56:16.873 | at compile (/vercel/746c5768655bc069/.build-utils/.builder/node_modules/@vercel/node/dist/index.js:99212:40)
21:56:16.873 | at compileTypeScript (/vercel/746c5768655bc069/.build-utils/.builder/node_modules/@vercel/node/dist/index.js:98491:31)
21:56:16.873 | at Job.readFile (/vercel/746c5768655bc069/.build-utils/.builder/node_modules/@vercel/node/dist/index.js:98517:30)
21:56:16.873 | at Job.emitDependency (/vercel/746c5768655bc069/.build-utils/.builder/node_modules/@vercel/node/dist/index.js:48043:33)
21:56:16.873 | at /vercel/746c5768655bc069/.build-utils/.builder/node_modules/@vercel/node/dist/index.js:48057:32
21:56:16.873 | at Array.map (<anonymous>)
21:56:16.873 | at Job.emitDependency (/vercel/746c5768655bc069/.build-utils/.builder/node_modules/@vercel/node/dist/index.js:48053:28) {
```
Full build output can be found [here](https://gist.github.com/creativiii/10bd525f5b476e13ac87a05577edf865)

As far as I understand this is generated on `npm install`, in `/node_modules/.prisma/index.js` and should look something like this https://gist.github.com/creativiii/ffdf732049d777f8439d78829bc03918.

I have no idea why this isn't getting generated the same way on Vercel as it is on my machine, but that's definitely the problem.

2) Despite the error, the build succeeds and deploys. Unfortunately trying to hit the endpoint results in:
```
An error occurred with this application.

NO_RESPONSE_FROM_FUNCTION
```

And on Vercel's side I get the following log:
```
[POST] /api
22:15:39:82
2021-01-12T22:15:40.664Z	undefined	ERROR	Error: You most likely forgot to initialize the Prisma Client. Please run `prisma generate` and try to run it again.If that does not solve your problem, please open an issue.
```

## How to reproduce

I've made a reproduction repository which can be found [here](https://github.com/creativiii/mci-backend-serverless)

1. Clone the repository
2. `cd` into it
3. Use the Vercel cli to deploy it
4. Check the build logs

## Expected behavior

Ideally no errors should happen and the api should work.

**Comment by creativiii** [comment]
So after looking into it this looks like a red herring, even the example project has it but works. The actual problem is caused by the incorrect generation of types.

I'm going to close this and make a new issue.
