### ISSUE TITLE
Migration failed because relationship already exists

### ISSUE THREAD

**Issue by jimmy-e** [prisma/prisma#4973]
**Describe the bug**
Migration failed because relationship already exists

**To Reproduce**
datamodel.prisma:
```
type Comment {
  id: ID! @id
  text: String!
  post: Post!
}

type Post {
  id: ID! @id
  body: String!
  published: Boolean!
  title: String!
}

type User {
  id: ID! @id
  email: String!
  name: String!
  posts: [Post]!
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
}
```

When I run `prisma delete` and then `prisma deploy` I get the following error:
```
Deploying service `default` to stage `default` to server `local` 4.4s

Changes:

  Comment (Type)
  + Created type `Comment`
  + Created field `id` of type `ID!`
  + Created field `text` of type `String!`
  + Created field `post` of type `Post!`

  User (Type)
  + Created type `User`
  + Created field `id` of type `ID!`
  + Created field `email` of type `String!`
  + Created field `name` of type `String!`
  + Created field `posts` of type `[Post!]!`
  + Created field `createdAt` of type `DateTime!`
  + Created field `updatedAt` of type `DateTime!`

  Post (Type)
  + Created type `Post`
  + Created field `id` of type `ID!`
  + Created field `body` of type `String!`
  + Created field `published` of type `Boolean!`
  + Created field `title` of type `String!`

  PostToUser (Relation)
  + Link Table `_PostToUser` between `Post` and `User` has been created

  CommentToPost (Relation)
  + Created an inline relation between `Comment` and `Post` in the column `post` of table `Comment`

Applying changes 19.8s
 ▸    The Migration failed and has not been performed. This is very likely not a transient issue.
 ▸    org.postgresql.util.PSQLException: ERROR: column "post" of relation "Comment" already exists
 ▸    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
 ▸    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
 ▸    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
 ▸    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
 ▸    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
 ▸    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
 ▸    at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
 ▸    at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
 ▸    at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
 ▸    at slick.jdbc.Invoker.first(Invoker.scala:30)
 ▸    at slick.jdbc.Invoker.first$(Invoker.scala:29)
 ▸    at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)
 ▸    at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
 ▸    at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
 ▸    at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
 ▸    at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
 ▸    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 ▸    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 ▸    at java.lang.Thread.run(Thread.java:748)
 ▸    

Get in touch if you need help: https://slack.prisma.io
To get more detailed output, run $ export DEBUG="*"
(node:8357) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

**Comment by yiruka114514** [comment]
Did this problem solve? How do you solve it?

**Comment by jimmy-e** [comment]
> Did this problem solve? How do you solve it?

No, sorry, I just reset my docker instance. Don't know how to fix this.

**Comment by AlfredOdling** [comment]
I have this problem too. Still no solution?

**Comment by rahadkc** [comment]
Is there any solution? I have this same problem now.
