### ISSUE TITLE
Errors at nested writes

### ISSUE THREAD

**Issue by vadim-shilov** [prisma/prisma#5012]
Hello!

Don't you think that throwing an error in the following cases is not worth it?

1) nested update of a non-existing record
```
Error: 
Invalid `photon.()` invocation in /home/vadim/Projects/Temp/index.js:11:36



Reason: AssertionError("Expected a valid parent ID to be present for nested update to-one case.")

    at PhotonFetcher.<anonymous> (/home/vadim/Projects/Temp/node_modules/@generated/photon/index.js:54:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/vadim/Projects/Temp/node_modules/@generated/photon/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

2) disconnection/nested deletion of a non-existing record
```
Error: 
Invalid `photon.()` invocation in /home/vadim/Projects/Temp/index.js:11:36



Reason: RecordsNotConnected { relation_name: "PostToUser", parent_name: "User", child_name: "Post" }

    at PhotonFetcher.<anonymous> (/home/vadim/Projects/Temp/node_modules/@generated/photon/index.js:54:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/vadim/Projects/Temp/node_modules/@generated/photon/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by timsuchanek** [comment]
Related to https://github.com/prisma/prisma/issues/5015

**Comment by matthewmueller** [comment]
For "nested update of a non-existing record", we're tracking that in #5015 

For **disconnection/nested deletion of a non-existing record**, I think the error is better now:

```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.user.update()` invocation:


  The records for relation `PostToUser` between the `User` and `Post` models are not connected.
    at cb (/Users/m/dev/src/github.com/prisma/qa-errors/node_modules/@prisma/client/runtime/index.js:78689:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'P2017',
  clientVersion: '2.17.0',
  meta: {
    relation_name: 'PostToUser',
    parent_name: 'User',
    child_name: 'Post'
  }
}
```
