### ISSUE TITLE
`EROFS: read-only file system, chmod '/var/task/generated/prisma-client/runtime/query-engine-rhel-openssl-1.0.x'`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#5023]
I followed the setup in https://github.com/prisma/prisma2-e2e-tests/tree/master/platforms/netlify (clone, remove `.netlify/state.json`, `yarn install`, `yarn prisma2 generate`, execute commands from `build.sh` manually (`zip` does not exist and has to be done manually), get deployed site and function!).

When then calling the function, I get:

```
{"errorType":"Error","errorMessage":"\nInvalid `prisma.()` invocation in\n/var/task/generated/prisma-client/index.js:323:37\n\n\n\nEROFS: read-only file system, chmod '/var/task/generated/prisma-client/runtime/query-engine-rhel-openssl-1.0.x'","trace":["Error: ","Invalid `prisma.()` invocation in","/var/task/generated/prisma-client/index.js:323:37","","","","EROFS: read-only file system, chmod '/var/task/generated/prisma-client/runtime/query-engine-rhel-openssl-1.0.x'","    at PrismaClientFetcher.request (/var/task/generated/prisma-client/index.js:60:27)"]}
```
https://goofy-tereshkova-4bf91a.netlify.com/.netlify/functions/index

Theory: Because the the generated client was created on Windows, it is missing the necessary file permission flags.

(`index.zip` that was uploaded: [index.zip](https://github.com/prisma/prisma-client-js/files/4175784/index.zip))

**Comment by larrybek** [comment]
@divyenduz @samrith-s. Thanks for the suggestion it worked great, if you had got deeper with layer usage will be happy if you can share something on it. Will be glad.

**Comment by samrith-s** [comment]
@larrybek sure! Message me on Slack and I can share my Serverless file :)

**Comment by orochizu** [comment]
> @larrybek sure! Message me on Slack and I can share my Serverless file :)

Hi! Could you share your serverless?

**Comment by orochizu** [comment]
> @larrybek sure! Message me on Slack and I can share my Serverless file :)

Hi @samrith-s ! Could you share your serverless file please?

**Comment by janpio** [comment]
I confirmed the original problem, build on Windows, deploy to Lambda, does still exist:

```
START RequestId: 0827675d-b212-4165-89cd-17dbb67e1626 Version: $LATEST
2021-03-24T22:55:41.640Z	0827675d-b212-4165-89cd-17dbb67e1626	ERROR	Invoke Error 	***"errorType":"Error","errorMessage":"\nInvalid `prisma.user.deleteMany()` invocation:\n\n\n  EROFS: read-only file system, chmod '/var/task/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x'","code":"EROFS","clientVersion":"2.20.0-dev.20","stack":["Error: ","Invalid `prisma.user.deleteMany()` invocation:","","","  EROFS: read-only file system, chmod '/var/task/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x'","    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:34788:17)"]***
END RequestId: 0827675d-b212-4165-89cd-17dbb67e1626
REPORT RequestId: 0827675d-b212-4165-89cd-17dbb67e1626	Duration: 360.04 ms	Billed Duration: 361 ms	Memory Size: 128 MB	Max Memory Used: 84 MB	Init Duration: 354.88 ms	
```

(All comments regarding Serverless and related really belong into https://github.com/prisma/prisma/issues/5053 which is not about the Windows problem)

**Comment by janpio** [comment]
Interesting that https://github.com/prisma/e2e-tests/pull/1539 shows that Serverless Framework, deployed to Lambda from Windows does not show the same failure - so they are doing something to fix that problem.

**Comment by Jolg42** [comment]
@janpio indeed, they seem to chmod to 755 for windows here when zipping https://github.com/serverless/serverless/blob/6e3e21cafaa053a0f30239513eac5c7a725b7694/lib/plugins/package/lib/zipService.js#L92-L99

**Comment by janpio** [comment]
TIL you can set the permission of a file when putting it into a zip file 👍

**Comment by pantharshit00** [comment]
@janpio Is this still actionable?

**Comment by janpio** [comment]
Yes, this problem still exists when built on Windows as the file does not got the executable flag when uploaded to the platform where this matters.
