### ISSUE TITLE
MySQL, SQLite: Better `ForeignKeyConstraintViolation` error message

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#5036]
If you e.g. can not delete an entry because of a constraint, you get this error:

MySQL:
```
PrismaClientUnknownRequestError:
Invalid `const deletedUser = await prisma.user.delete()` invocation in
/Users/janedoe/cascasing-deletes-demo/index.js:16:49

  12   },
  13 });
  14
  15 try {
→ 16   const deletedUser = await prisma.user.delete(

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ForeignKeyConstraintViolation { constraint: Fields(["author"]) } })
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\mysql\node_modules\@prisma\client\runtime\index.js:1:51487)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

SQLite:
```
Invalid `const deletedUser = await prisma.user.delete()` invocation in
C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\sqlite\index.js:16:49

  12   },
  13 });
  14
  15 try {
→ 16   const deletedUser = await prisma.user.delete(

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: ConstraintViolation, extended_code: 1811 }, Some("FOREIGN KEY constraint failed"))) })
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma2-docs-demos\cascading-deletes\sqlite\node_modules\@prisma\client\runtime\index.js:1:51487)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

This could be nicer.

---

```sql
CREATE TABLE `CascadingDeletesDemo`.`User` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(256)
);

CREATE TABLE `CascadingDeletesDemo`.`Post` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(256),
  `author` INT,
  CONSTRAINT `author` FOREIGN KEY (`author`) REFERENCES `CascadingDeletesDemo`.`User`(`id`) ON DELETE RESTRICT
);
```

```prisma
model Post {
  author Int?
  id     Int     @default(autoincrement()) @id
  title  String?
  User   User?   @relation(fields: [author], references: [id])

  @@index([author], name: "author2")
}

model User {
  id   Int     @default(autoincrement()) @id
  name String?
  Post Post[]
}
```

```js
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  const userWithPost = await prisma.user.create({
    data: {
      name: 'Alice',
      Post: {
        create: { title: 'Hello World' },
      },
    },
  });

  try {
    const deletedUser = await prisma.user.delete({
      where: { id: userWithPost.id },
    });
  } catch (e) {
    console.log(e);
  }
}

main();
```

**Comment by janpio** [comment]
We haven't had any additional requests for this in the last 3+ years, so it is safe to say that this is not the most pressing need. As we have hundreds of issues where we do get constant feedback and upvotes, it is not realistic for us to prioritize this one any time soon, sorry. 

I am closing this issue for now. If someone has a dire need for this, please comment below or open a new feature request. Thank you.
