### ISSUE TITLE
Handle out of RAM better

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#5045]
# PANIC: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" } + Error: read ENOTCONN

Setup:

- App that creates new Prisma Client for each requests and does not close it
    - (to simulate the worst serverless function behavior)
- Deployed to Heroku Standard-1X dyno (512MB RAM)
- "Load test" via [https://loader.io/](https://loader.io/):
    - 50 clients over 15 sec

Seems around request 32 the RAM of the dyno is used up and a new QE can not be started any more and it crashes the Node Process:

```
2020-05-18T21:19:30.681220+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Error:
2020-05-18T21:19:30.681223+00:00 app[web.1]: Invalid `prisma.product.findMany()` invocation:
2020-05-18T21:19:30.681229+00:00 app[web.1]:
2020-05-18T21:19:30.681233+00:00 app[web.1]: PANIC: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
2020-05-18T21:19:30.681234+00:00 app[web.1]: at PrismaClientFetcher.request (/app/node_modules/@prisma/client/runtime/index.js:1:86042)
2020-05-18T21:19:30.681235+00:00 app[web.1]: at runMicrotasks (<anonymous>)
2020-05-18T21:19:30.681235+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-05-18T21:19:30.681254+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2020-05-18T21:19:30.681305+00:00 app[web.1]: (node:23) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-05-18T21:19:30.682110+00:00 app[web.1]: prisma:info  Starting a postgresql pool with 9 connections.
2020-05-18T21:19:30.682636+00:00 app[web.1]: Error in Prisma Client:
2020-05-18T21:19:30.682637+00:00 app[web.1]: PANIC: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" } in
2020-05-18T21:19:30.682637+00:00 app[web.1]: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/blocking/pool.rs:205:9
2020-05-18T21:19:30.682638+00:00 app[web.1]:
2020-05-18T21:19:30.682638+00:00 app[web.1]: This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.
2020-05-18T21:19:30.682639+00:00 app[web.1]: Please create an issue in https://github.com/prisma/prisma-client-js describing the last Prisma Client query you called.
...
2020-05-18T21:29:21.558185+00:00 app[web.1]: events.js:287
2020-05-18T21:29:21.558199+00:00 app[web.1]: throw er; // Unhandled 'error' event
2020-05-18T21:29:21.558199+00:00 app[web.1]: ^
2020-05-18T21:29:21.558199+00:00 app[web.1]:
2020-05-18T21:29:21.558200+00:00 app[web.1]: Error: read ENOTCONN
2020-05-18T21:29:21.558200+00:00 app[web.1]: at tryReadStart (net.js:571:20)
2020-05-18T21:29:21.558200+00:00 app[web.1]: at Socket._read (net.js:582:5)
2020-05-18T21:29:21.558201+00:00 app[web.1]: at Socket.Readable.read (_stream_readable.js:459:10)
2020-05-18T21:29:21.558201+00:00 app[web.1]: at Socket.read (net.js:622:39)
2020-05-18T21:29:21.558201+00:00 app[web.1]: at new Socket (net.js:373:12)
2020-05-18T21:29:21.558202+00:00 app[web.1]: at Object.Socket (net.js:263:41)
2020-05-18T21:29:21.558202+00:00 app[web.1]: at createSocket (internal/child_process.js:314:14)
2020-05-18T21:29:21.558202+00:00 app[web.1]: at ChildProcess.spawn (internal/child_process.js:437:23)
2020-05-18T21:29:21.558202+00:00 app[web.1]: at spawn (child_process.js:548:9)
2020-05-18T21:29:21.558203+00:00 app[web.1]: at Object.execFile (child_process.js:232:17)
2020-05-18T21:29:21.558203+00:00 app[web.1]: Emitted 'error' event on Socket instance at:
2020-05-18T21:29:21.558203+00:00 app[web.1]: at emitErrorNT (internal/streams/destroy.js:92:8)
2020-05-18T21:29:21.558203+00:00 app[web.1]: at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
2020-05-18T21:29:21.558204+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2020-05-18T21:29:21.558204+00:00 app[web.1]: errno: 'ENOTCONN',
2020-05-18T21:29:21.558204+00:00 app[web.1]: code: 'ENOTCONN',
2020-05-18T21:29:21.558205+00:00 app[web.1]: syscall: 'read'
2020-05-18T21:29:21.558205+00:00 app[web.1]: }
2020-05-18T21:29:21.567741+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-05-18T21:29:21.567914+00:00 app[web.1]: npm ERR! errno 1
2020-05-18T21:29:21.568816+00:00 app[web.1]: npm ERR! @ start: `node index.js`
2020-05-18T21:29:21.568909+00:00 app[web.1]: npm ERR! Exit status 1
2020-05-18T21:29:21.569025+00:00 app[web.1]: npm ERR!
2020-05-18T21:29:21.569107+00:00 app[web.1]: npm ERR! Failed at the @ start script.
2020-05-18T21:29:21.569181+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-05-18T21:29:21.576387+00:00 app[web.1]:
2020-05-18T21:29:21.576521+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-05-18T21:29:21.576612+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-05-18T21_29_21_569Z-debug.log
```

This is all the QE is doing for each request:
```
2020-05-18T21:24:47.295934+00:00 app[web.1]: prisma:info  Starting a postgresql pool with 9 connections.
2020-05-18T21:24:47.311381+00:00 app[web.1]: prisma:info  Started http server on 127.0.0.1:40537
2020-05-18T21:24:47.579091+00:00 app[web.1]: prisma:query BEGIN
2020-05-18T21:24:47.617087+00:00 app[web.1]: prisma:query BEGIN
2020-05-18T21:24:47.646082+00:00 app[web.1]: prisma:query SELECT "public"."Product"."id", "public"."Product"."handle", "public"."Product"."name", "public"."Product"."description", "public"."Product"."price" FROM "public"."Product" WHERE 1=1 ORDER BY "public"."Product"."id" ASC LIMIT $1 OFFSET $2
2020-05-18T21:24:47.678059+00:00 app[web.1]: prisma:query COMMIT
```

(Beta 5)

---
Internal Writeup: https://www.notion.so/prismaio/How-Prisma-behaves-when-no-more-RAM-is-available-54d676a763ba465cb351a3afdf882471

**Comment by maximerat** [comment]
@janpio Hey Janpio, do you have a workaround ?

**Comment by janpio** [comment]
No, this issue is me requesting improvements on how this is handled - but without a recent use case. Do you have this problem right now? If so, could you please describe it with as much information as possible? This would greatly help us to possibly work on this.

**Comment by maximerat** [comment]
> No, this issue is me requesting improvements on how this is handled - but without a recent use case. Do you have this problem right now? If so, could you please describe it with as much information as possible? This would greatly help us to possibly work on this.

It crashed with one dyno (512ram). I added 1 dyno (1gram) and it fixed the error.

**Comment by pantharshit00** [comment]
@maximerat Can you please tell us how much large is your schema in terms of line of code. Also, tell use how much traffic that dyno was receiving.

**Comment by maximerat** [comment]
My schema is 360 lines for a total of 7ko. It crashed just after the install, so no traffic, only me.

**Comment by pantharshit00** [comment]
@maximerat Can you please tell me what error message it threw when it failed from the logs?

**Comment by maximerat** [comment]
`
2021-01-31T13:02:54.255236+00:00 app[web.1]: 2021-01-31T13:02:54.255Z engine stdout PANIC in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/pool.rs:234:14
2021-01-31T13:02:54.255237+00:00 app[web.1]: called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }
2021-01-31T13:02:54.264098+00:00 app[web.1]: /app/node_modules/@prisma/client/runtime/index.js:3691
2021-01-31T13:02:54.264100+00:00 app[web.1]: const gotLogs = debug_12.getLogs(6e3 - query.length);
2021-01-31T13:02:54.264100+00:00 app[web.1]: ^
2021-01-31T13:02:54.264101+00:00 app[web.1]:
2021-01-31T13:02:54.264102+00:00 app[web.1]: TypeError: Cannot read property 'length' of undefined
2021-01-31T13:02:54.264103+00:00 app[web.1]: at Object.getErrorMessageWithLink (/app/node_modules/@prisma/client/runtime/index.js:3691:50)
2021-01-31T13:02:54.264103+00:00 app[web.1]: at NodeEngine.getErrorMessageWithLink (/app/node_modules/@prisma/client/runtime/index.js:27066:23)
2021-01-31T13:02:54.264107+00:00 app[web.1]: at ChildProcess.<anonymous> (/app/node_modules/@prisma/client/runtime/index.js:26833:74)
2021-01-31T13:02:54.264108+00:00 app[web.1]: at ChildProcess.emit (events.js:315:20)
2021-01-31T13:02:54.264108+00:00 app[web.1]: at maybeClose (internal/child_process.js:1051:16)
2021-01-31T13:02:54.264109+00:00 app[web.1]: at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
2021-01-31T13:02:54.274909+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-01-31T13:02:54.275269+00:00 app[web.1]: npm ERR! errno 1
2021-01-31T13:02:54.276235+00:00 app[web.1]: npm ERR! heeet@0.0.1 start:prod: `npm run migrate:deploy && node dist/main`
2021-01-31T13:02:54.276372+00:00 app[web.1]: npm ERR! Exit status 1
2021-01-31T13:02:54.276532+00:00 app[web.1]: npm ERR!
2021-01-31T13:02:54.276656+00:00 app[web.1]: npm ERR! Failed at the heeet@0.0.1 start:prod script.
2021-01-31T13:02:54.276774+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-01-31T13:02:54.352111+00:00 app[web.1]:
2021-01-31T13:02:54.352280+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-01-31T13:02:54.352435+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-01-31T13_02_54_277Z-debug.log
`

**Comment by pantharshit00** [comment]
Error thrown in 2.23 when reproducing using heroku:
```
2021-05-28T15:57:53.815959+00:00 app[web.1]: warn(prisma-client) Already 10 Prisma Clients are actively running.
2021-05-28T15:57:54.557810+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/api/feed" host=issue-5045.herokuapp.com request_id=ce5228bc-1c79-4116-823a-cac64643eac1 fwd="3.230.143.8" dyno=web.1 connect=0ms service=160ms status=503 bytes=0 protocol=https
2021-05-28T15:57:54.533730+00:00 app[web.1]: node:events:342
2021-05-28T15:57:54.533739+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2021-05-28T15:57:54.533739+00:00 app[web.1]:       ^
2021-05-28T15:57:54.533739+00:00 app[web.1]: 
2021-05-28T15:57:54.533740+00:00 app[web.1]: Error: spawn /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x EAGAIN
2021-05-28T15:57:54.533741+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
2021-05-28T15:57:54.533741+00:00 app[web.1]:     at onErrorNT (node:internal/child_process:480:16)
2021-05-28T15:57:54.533742+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2021-05-28T15:57:54.533742+00:00 app[web.1]: Emitted 'error' event on ChildProcess instance at:
2021-05-28T15:57:54.533743+00:00 app[web.1]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
2021-05-28T15:57:54.533743+00:00 app[web.1]:     at onErrorNT (node:internal/child_process:480:16)
2021-05-28T15:57:54.533744+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
2021-05-28T15:57:54.533744+00:00 app[web.1]:   errno: -11,
2021-05-28T15:57:54.533745+00:00 app[web.1]:   code: 'EAGAIN',
2021-05-28T15:57:54.533745+00:00 app[web.1]:   syscall: 'spawn /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x',
2021-05-28T15:57:54.533745+00:00 app[web.1]:   path: '/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x',
2021-05-28T15:57:54.533746+00:00 app[web.1]:   spawnargs: [ '--enable-raw-queries', '--port', '38224' ]
2021-05-28T15:57:54.533746+00:00 app[web.1]: }
```
