### ISSUE TITLE
PANIC:Invalid `prisma.user.findOne()` invocation 

### ISSUE THREAD

**Issue by lmichratsimbazafy** [prisma/prisma#5071]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name     | Version            |
|----------|--------------------|
| Node     | v12.18.3           | 
| OS       | debian-openssl-1.1.x|
| Prisma   | 2.5.1              |

## Logs
```
prisma-client {
  engineConfig: {
    cwd: '/server/prisma',
    enableDebugLogs: false,
    enableEngineDebugMode: undefined,
    datamodelPath: '/server/node_modules/.prisma/client/schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    generator: {
      name: 'client',
      provider: 'prisma-client-js',
      output: '/server/node_modules/@prisma/client',
      binaryTargets: [],
      previewFeatures: [],
      config: {}
    },
    showColors: false,
    logLevel: undefined,
    logQueries: undefined,
    flags: [],
    clientVersion: '2.5.1',
    enableExperimental: [],
    useUds: undefined
  }
}
plusX Execution permissions of /server/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma-client Client Version 2.5.1
prisma-client Engine Version 6a8054bb549e4cc23f157b0010cb2e95cb2637fb
```

**Comment by surajmandalcell** [comment]
is this the same issue? 
happens after idling instance for some time.

```
(node:342438) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.users.findUnique()` invocation:


  Socket Timeout Error
    at PrismaClientFetcher.request (/home/ubuntu/server/node_modules/@prisma/client/runtime/index.js:77564:15)   
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processTimers (internal/timers.js:494:9)
(node:342438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
/home/ubuntu/server/node_modules/@prisma/client/runtime/index.js:24996
        const {aborted} = client[kQueue][client[kRunningIdx]];
               ^

TypeError: Cannot destructure property 'aborted' of 'client[kQueue][client[kRunningIdx]]' as it is undefined.
    at _resume (/home/ubuntu/server/node_modules/@prisma/client/runtime/index.js:24996:16)
    at resume (/home/ubuntu/server/node_modules/@prisma/client/runtime/index.js:24971:5)
    at Parser.3 (/home/ubuntu/server/node_modules/@prisma/client/runtime/index.js:24836:9)
```

**Comment by pantharshit00** [comment]
@surajmandalcell Please open a new issue with a reproduction.

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
