### ISSUE TITLE
Prisma server crashes while saving array(text) in Postgres.

### ISSUE THREAD

**Issue by rootandleaves** [prisma/prisma#5081]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v13.8.0            | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.8.0              |

# Description
```
signalCode: null | exitCode: 255 | killed: true
SocketError: closed
    at Socket.mc (/home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/@prisma/node_modules/.pnpm/undici@2.0.5/node_modules/undici/lib/core/client.js:687:31)
    at Socket.emit (events.js:321:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at TCP.<anonymous> (net.js:668:12)
Exit code: 255
Started http server
```

## Logs
```
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +14s
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +1s
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +2s
  plusX Execution permissions of /home/dotsinspace/Documents/dev/truck.pe__server/node_modules/.pnpm/@prisma/client@2.8.0_@prisma+cli@2.8.0/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +1s
```

**Comment by pantharshit00** [comment]
Closing due to inactivity
