### ISSUE TITLE
String template not working in $queryRaw with postgres

### ISSUE THREAD

**Issue by gizmoGremlin** [prisma/prisma#5083]
## Bug description

String template variable triggers an error in my raw postgres query. When the I dont use a variable, but instead hardcode the value the query is completed sucessfully
## How to reproduce
This is my query
```ts
const tableName = openaddressesma;
const radiusSearch = await prisma.$queryRaw`SELECT postcode FROM ${tableName} where ST_Distance(geolocation::geography, ST_SetSRID(ST_MakePoint(${parseFloat(
          long
        )},${parseFloat(lat)}),4326)::geography) < ${
          parseFloat(miles) * 1609.34
        };`; 
```
  The above query fails and gives the error:

Invalid `prisma.queryRaw()` invocation:
  Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "$1"`

But It succeeds when I remove ${tableName} from the query and replace it with a hard code value. eg
```ts
const radiusSearch = await prisma.$queryRaw`SELECT postcode FROM openaddressesma where ST_Distance(geolocation::geography, ST_SetSRID(ST_MakePoint(${parseFloat(
          long
        )},${parseFloat(lat)}),4326)::geography) < ${
          parseFloat(miles) * 1609.34
        };`;
```

## Expected behavior

I expect The query to complete and return results from the database.

## Environment & setup

- OS: ubuntu 18.0.1
- Database: PostgreSQL
- Node.js version: v14.5.0
- Prisma version:
Prisma CLI version: prisma/1.34.10 (linux-x64) node-v14.5.0
```

```

**Comment by alexpmay** [comment]
I am having this issue as well. Here is a simple example:

```
async function testResolver() {
      // This will crash
      const name = "Tenant 1";
      const dbResult = await prisma.$queryRaw`select name from tenant where name='${name}'`;
      
      // This runs just fine
      //const dbResult = await prisma.$queryRaw`select name from tenant where name='Tenant 1'`;

      // As does this
      const name = "Tenant 1";
      const dbResult = await prisma.$queryRaw(`select name from tenant where name='${name}'`);

      console.log(dbResult[0]);
      return dbResult;
}
```

The error is: 
> Invalid `prisma.queryRaw()` invocation:\n\n\n  Your raw query had an incorrect number of parameters. Expected: `0`, actual: `1`

If you turn on prisma logging, for the non string template you get
> prisma:query select name from tenant where name='Tenant 1'

and for the string template you get:
> prisma:query select name from tenant where name='$1'

and with the parens around the string template
> prisma:query select name from tenant where name='Tenant 1'
> { name: 'Tenant 1' }

Please fix. It is a very serious issue since it makes it very hard write safe SQL. Thank you.

**Comment by pantharshit00** [comment]
@alexpmay you need to do the following:
```
const dbResult = await prisma.$queryRaw`select name from tenant where name=${name}`;
```

Since this will use a prepared statement it will translate the query to `select name from tenant where name=$1` and send along $1 as a parameter so you don't need wrap it around quotations.

**Comment by FaBeyyy** [comment]
good thing this still hasn't been fixed :)

**Comment by pantharshit00** [comment]
Closing due to inactivity from original author.

**Comment by chenliu9** [comment]
I got the same issues as @gizmoGremlin reported, see https://github.com/prisma/prisma/discussions/12817.

**Comment by jasonkuhrt** [comment]
When I try to run `DROP DATABASE url_shortener WITH (FORCE);` I get:

```
Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "$1"`

      39 |     const dropDatabaseSql = `DROP DATABASE ${databaseName} WITH (FORCE);`
      40 |     console.log(dropDatabaseSql)
    > 41 |     await prisma.$executeRaw`${dropDatabaseSql}`
         |     ^
      42 |     return null
      43 |
      44 |     const initResult = await ctx.run(`npm run init`, { reject: true })

      at Object.request (../../../../../tmp/6d9e6b22c77de75c1a6d613455886d9e/node_modules/@prisma/client/runtime/index.js:45578:15)
      at Proxy._request (../../../../../tmp/6d9e6b22c77de75c1a6d613455886d9e/node_modules/@prisma/client/runtime/index.js:46405:18)
      at Object.<anonymous> (tests/e2e/__testers__.ts:41:5)
```

Prisma Client version 3.12

**Comment by jasonkuhrt** [comment]
This worked:

```ts
await prisma.$executeRawUnsafe`DROP DATABASE ${databaseName} WITH (FORCE);`
```

**Comment by jasonkuhrt** [comment]
Nevermind, this is not working actually, I must have misinterpreted my terminal output at the time.

```ts
await prisma.$executeRawUnsafe`DROP DATABASE ${databaseName} WITH (FORCE);`
```
```
    Invalid `prisma.executeRaw()` invocation:


      Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "$1"`

      32 |         })
      33 |         try {
    > 34 |           await prisma.$executeRawUnsafe`DROP DATABASE ${databaseName} WITH (FORCE);`
         |           ^
      35 |         } catch (error) {
      36 |           const isDatabaseNotFoundErorr = error instanceof Error && error.message.match(/does not exist/)
      37 |           if (!isDatabaseNotFoundErorr) throw error

      at node_modules/konn/src/runners.ts:66:16
      Invalid `prisma.executeRaw()` invocation:
        Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "$1"`
      at Object.request (../../../../../tmp/3f70588290d8a06de713dcbd0c2e4e93/node_modules/@prisma/client/runtime/index.js:45578:15)
      at Proxy._request (../../../../../tmp/3f70588290d8a06de713dcbd0c2e4e93/node_modules/@prisma/client/runtime/index.js:46405:18)
      at Object.dropTestDatabase (tests/e2e/__testers__.ts:34:11)
      at Object.setdown (tests/e2e/__testers__.ts:48:7)
      at node_modules/konn/src/runners.ts:60:7

```

**Comment by jasonkuhrt** [comment]
IIUC also another mistake I made is that:

```
await prisma.$executeRawUnsafe`DROP DATABASE ${databaseName} WITH (FORCE);`
```

Should be:

```
await prisma.$executeRawUnsafe(`DROP DATABASE ${databaseName} WITH (FORCE);`)
```

**Comment by sanyAlam** [comment]
<img width="709" alt="Screen Shot 2022-08-18 at 11 43 38 AM" src="https://user-images.githubusercontent.com/100110840/185303031-bfa59f60-2860-4060-9067-30598b06b0e4.png">

**Comment by lucasjribeiro** [comment]
For some reason, Prisma does not accept the use of variables for table names and field names.
One way I found to solve this problem was to use an auxiliary variable to assemble the query and then use this variable with queryRaw.

See an example below:

```
const query = `
  SELECT * FROM "${options.table}"
  WHERE "${options.column}" = '${value}'
  LIMIT 1
`;

const row: any[] = await prisma.$queryRaw`${Prisma.raw(query)}`;
```

Important:
- If the name of the table or field contains double quotes, they must be placed in the query.
- It is necessary to use Prisma.raw() for the query to work.
