### ISSUE TITLE
Better error message for create with 2 connects where the IDs for the connected objects do not exist

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#5087]
I have put together a simple reproduction here: https://github.com/Pat-Ayres/prisma-error-message-reproduction

```
Error:                                                                                                                Invalid `prisma.comment.create()` invocation in
/home/payres/tmpsrc/prisma-error-message-reproduction/prisma/seed.ts:9:26

   5
   6 const prisma = new PrismaClient(prismaConfig);
   7
   8 async function main(): Promise<void> {
→  9     await prisma.comment.create(
  Query interpretation error. Error for binding '2': AssertionError("[Query Graph] Expected a valid parent ID to be present for a nested connect on a one-to-many relation.")
    at iy.request (/home/payres/tmpsrc/prisma-error-message-reproduction/node_modules/@prisma/client/runtime/src/runtime/getPrismaClient.ts:1181:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

This example has a create with 2 connects where the IDs for the connected objects do not exist. It would be helpful if we were given more information, e.g. which connect(s) it failed on, and potentially the ID that does not exist.

something like "Expected a valid parent ID to be present for a nested connect on a one-to-many relation [Connect: user, ID: 9000], [Connect: Post, ID: 9000]"

Hopefully this is helpful!

_Originally posted by @Pat-Ayres in https://github.com/prisma/prisma-client-js/issue_comments/710223928_

**Comment by omar-dulaimi** [comment]
Just faced this issue right now.
