### ISSUE TITLE
PANIC: called `Result::unwrap()` on an `Err` value: Could not parse stored DateTime string: 2020-11-27 01:17:30 (input contains invalid characters)

### ISSUE THREAD

**Issue by debdude** [prisma/prisma#5096]
Hi Prisma Team! My Prisma Client just crashed. This is the report:

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.18.2           | 
| OS              | darwin             |
| Prisma Client   | 2.12.1             |

## Logs
```
  prisma-client { clientVersion: '2.12.1' }  
  plusX Execution permissions of /Users/d/w/lam/gtway/node_modules/.prisma/client/query-engine-darwin are fine  
  plusX Execution permissions of /Users/d/w/lam/gtway/node_modules/.prisma/client/query-engine-darwin are fine  
  plusX Execution permissions of /Users/d/w/lam/gtway/node_modules/.prisma/client/query-engine-darwin are fine  
  plusX Execution permissions of /Users/d/w/lam/gtway/node_modules/.prisma/client/query-engine-darwin are fine  
```
This maybe of interest:
```
at PrismaClientFetcher.request (/Users/d/w/lam/gtway/node_modules/@prisma/client/runtime/index.js:79363:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Also, this was the table definition in sqlite:

```
create table users (
    id integer primary key autoincrement,
    ntlogin text,
    name text,
    is_active int default 1,
    is_admin int default 0,
    created_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);

insert into users(name, ntlogin, is_admin) values ("Kenobi, Obi Wan", "owkenobi", 1);
```

Also, happy Thanksgiving!

**Comment by pimeys** [comment]
Should be fixed in https://github.com/prisma/quaint/pull/243
