### ISSUE TITLE
PANIC

### ISSUE THREAD

**Issue by hamishirving** [prisma/prisma#5101]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.20.0           | 
| OS              | rhel-openssl-1.0.x |
| Prisma Client   | 2.11.0             |

## Logs
```
prisma-client {
  engineConfig: {
    cwd: '/var/task/src/node_modules/.prisma/client',
    enableDebugLogs: false,
    enableEngineDebugMode: undefined,
    datamodelPath: '/var/task/src/node_modules/.prisma/client/schema.prisma',
    prismaPath: undefined,
    engineEndpoint: undefined,
    generator: {
      name: 'client',
      provider: 'prisma-client-js',
      output: '/opt/build/repo/node_modules/@prisma/client',
      binaryTargets: [Array],
      previewFeatures: [],
      config: {}
    },
    showColors: false,
    logLevel: undefined,
    logQueries: undefined,
    flags: [],
    clientVersion: '2.11.0',
    enableExperimental: [],
    useUds: undefined
  }
}
plusX Execution permissions of /var/task/src/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
plusX Execution permissions of /var/task/src/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma-client Error: Error in PostgreSQL connection: Error { kind: Db, cause: Some(DbError { severity: "FATAL", parsed_severity: Some(Fatal), code: SqlState("57P01"), message: "terminating connection due to administrator command", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("postgres.c"), line: Some(3011), routine: Some("ProcessInterrupts") }) }

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma-client-js/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v12.20.0+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+rhel-openssl-1.0.x+%7C%0A%7C+Prisma+Client+++%7C+2.11.0+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0Aprisma-client+%7B%0A++engineConfig%3A+%7B%0A++++cwd%3A+%27%2Fvar%2Ftask%2Fsrc%2Fnode_modules%2F.prisma%2Fclient%27%2C%0A++++enableDebugLogs%3A+false%2C%0A++++enableEngineDebugMode%3A+undefined%2C%0A++++datamodelPath%3A+%27%2Fvar%2Ftask%2Fsrc%2Fnode_modules%2F.prisma%2Fclient%2Fschema.prisma%27%2C%0A++++prismaPath%3A+undefined%2C%0A++++engineEndpoint%3A+undefined%2C%0A++++generator%3A+%7B%0A++++++name%3A+%27client%27%2C%0A++++++provider%3A+%27prisma-client-js%27%2C%0A++++++output%3A+%27%2Fopt%2Fbuild%2Frepo%2Fnode_modules%2F%40prisma%2Fclient%27%2C%0A++++++binaryTargets%3A+%5BArray%5D%2C%0A++++++previewFeatures%3A+%5B%5D%2C%0A++++++config%3A+%7B%7D%0A++++%7D%2C%0A++++showColors%3A+false%2C%0A++++logLevel%3A+undefined%2C%0A++++logQueries%3A+undefined%2C%0A++++flags%3A+%5B%5D%2C%0A++++clientVersion%3A+%272.11.0%27%2C%0A++++enableExperimental%3A+%5B%5D%2C%0A++++useUds%3A+undefined%0A++%7D%0A%7D%0AplusX+Execution+permissions+of+%2Fvar%2Ftask%2Fsrc%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-rhel-openssl-1.0.x+are+fine%0AplusX+Execution+permissions+of+%2Fvar%2Ftask%2Fsrc%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-rhel-openssl-1.0.x+are+fine%0A%60%60%60&title=Error+in+PostgreSQL+connection%3A+Error+%7B+kind%3A+Db%2C+cause%3A+Some%28DbError+%7B+severity%3A+%22FATAL%22%2C+parsed_severity%3A+Some%28Fatal%29%2C+code%3A+SqlState%28%2257P01%22%29%2C+message%3A+%22terminating+connection+due+to+administrator+command%22%2C+detail%3A+None%2C+hint%3A+None%2C+position%3A+None%2C+where_%3A+None%2C+schema%3A+None%2C+table%3A+None%2C+column%3A+None%2C+datatype%3A+None%2C+constraint%3A+None%2C+file%3A+Some%28%22postgres.c%22%29%2C+line%3A+Some%283011%29%2C+routine%3A+Some%28%22ProcessInterrupts%22%29+%7D%29+%7D&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏

    at NodeEngine.handleRequestError (/var/task/src/node_modules/@prisma/client/runtime/index.js:27094:21)
    at /var/task/src/node_modules/@prisma/client/runtime/index.js:27730:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PrismaClientFetcher.request (/var/task/src/node_modules/@prisma/client/runtime/index.js:78755:24)
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
