### ISSUE TITLE
Prisma Enums generated from Introspect cause errors. 

### ISSUE THREAD

**Issue by blazestudios23** [prisma/prisma#5104]
## Bug description

I did prisma introspect, with:

```
datasource deliverables {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

I got the following Schema:

```
model ftp_profile {
  ftp_profile_id  Int                          @id @default(autoincrement())
  description     String
  server_protocol ftp_profile_server_protocol
  ...
}

enum ftp_profile_server_protocol {
  FTP
  SFTP
  FTPS
}
```

Then run Prisma generate with the below set:

```
generator client_deliverables {
  provider = "prisma-client-js"
  output   = "../../src/generated/prisma/ftp/client"
}

```

When I try to execute :

```
client.ftp_profile.findMany().then(data => console.log(data)).catch(e => console.log(e))

```
I get the following error:

```
Value '' not found in enum 'DatabaseEnumType { name: "server_protocol", internal_enum: InternalEnum { name: "server_protocol", values: [InternalEnumValue { name: "FTP", database_name: None }, InternalEnumValue { name: "SFTP", database_name: None }, InternalEnumValue { name: "FTPS", database_name: None }] } }'      
    at PrismaClientFetcher.request (C:\Git\VSTS\StateNetApps\Icefall\src\generated\prisma\deliverables\client\runtime\index.js:78134:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  clientVersion: '2.14.0'
}
```

There seems to be an issue with the generated enum types and how they are resolved in Prisma 2.

**Comment by albertoperdomo** [comment]
This seems to be related to the client, not introspection.

**Comment by matthewmueller** [comment]
@blazestudios23 that's interesting. Does the `server_protocol` column in your MySQL database contain empty values?

**Comment by blazestudios23** [comment]
Here's what the relevant columns look like: 
```
Table: ftb_provile
ftp_profile_id int(11) AI PK
description varchar(128)
server_protocol enum('FTP','SFTP','FTPS')
...
```

**Comment by janpio** [comment]
Could you check the actual data @blazestudios23? MySQL has this funny behavior where if you try to add an invalid value for an enum, it is (depending on config) silently converted into an empty string, see https://dev.mysql.com/doc/refman/5.7/en/enum.html#enum-nulls

**Comment by blazestudios23** [comment]
Well looks there are nulls.

**Comment by janpio** [comment]
nulls or empty strings? 
For a `NULL` introspect should have picked that up. 
An empty string though, might indeed be currently causing an error message. If that is the case, we could investigate and reproduce further.

**Comment by pantharshit00** [comment]
Hey @blazestudios23 

Can you please share the complete sql schema of that table? I am unable to reproduce with my attempt and without a complete schema it is hard to get a accurate reproduction.

**Comment by blazestudios23** [comment]
It was nulls that caused the issue. 

It was simply enums that had null values. However the error messaging was a bit obtuse so I was stumped for about a day until you said to check for nulls.

**Comment by janpio** [comment]
So the problem was that it was `server_protocol` and not `server_protocol?` (optional, which allows NULL), right @pantharshit00? Still should give a much better error message probably - might just not be handled at all right now.

**Comment by blazestudios23** [comment]
Yes, I believe that was the issue. 

Now that I know what the issues was the error messaging makes sense, but when I didn't I was lost as I wasn't thinking with null enums converting to empty string, or that we even had null enums.

**Comment by janpio** [comment]
After @pantharshit00 reproduces the error message, we will probably want to improve that error message to make that much clearer in the future. As this is happening in our code, not the database, this should be possible.

**Comment by pantharshit00** [comment]
I am unable to reproduce this with 2.16

Nullable enums are correctly introspected:
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

model ftp_profile {
  ftp_profile_id  Int                          @id @default(autoincrement())
  description     String
  server_protocol ftp_profile_server_protocol?
}

enum ftp_profile_server_protocol {
  FTP
  SFTP
  FTPS
}
```

Please try again with latest version.

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
