### ISSUE TITLE
Missing h in http panic error

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#5125]
## Bug description

Link is missing an h

```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]:
Invalid `prisma.executeRaw()` invocation:


  PANIC in /root/.cargo/git/checkouts/quaint-9f01e008b9a89c14/bc3aa8a/src/connector/postgres/error.rs:138:29
index out of bounds: the len is 1 but the index is 1

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

ttps://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v12.16.1+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+darwin+++++++++++++%7C%0A%7C+Prisma+Client+++%7C+2.14.0+++++++++++++%7C%0A%7C+Query+Engine++++%7C+query-engine+5d491261d382a2a5ffdc71de17072b0e409f1cc1%7C%0A%7C+Database++++++++%7C+undefined%7C%0A%0A%0A%0A%23%23+Query%0A%60%60%60%0Amutation+%7B%0A++executeRaw%28%0A++++query%3A+%22X%22%0A++++parameters%3A+%22X%22%0A++%29%0A%7D%0A%60%60%60%0A%0A%23%23+Logs%0A%60%60%60%0A++tryLoadEnv+Environment+variables+loaded+from+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2F.env++%0A++tryLoadEnv+Environment+variables+loaded+from+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2F.env++%0A++prisma-client+%7B+clientVersion%3A+%272.14.0%27+%7D++%0A++engine+%7B+cwd%3A+%27%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fprisma%27+%7D++%0A++engine+Search+for+Query+Engine+in+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient++%0A++engine+Search+for+Query+Engine+in+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient++%0A++plusX+Execution+permissions+of+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine++%0A++plusX+Execution+permissions+of+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine++%0A++engine+%7B%0A++engine+++flags%3A+%5B%0A++engine+++++%27--enable-raw-queries%27%2C%0A++engine+++++%27--unix-path%27%2C%0A++engine+++++%27%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock%27%0A++engine+++%5D%0A++engine+%7D++%0A++engine+stdout++Starting+a+postgresql+pool+with+13+connections.++%0A++engine+stdout++Started+http+server+on+http%2Bunix%3A%2F%2F%2Fprivate%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock++%0A++engine+Search+for+Query+Engine+in+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient++%0A++prisma-client+prisma.%24executeRaw%28SET+jwt.claims.user_id+%3D+10%2C+%5B%5D%29++%0A++prisma-client+Prisma+Client+call%3A++%0A++plusX+Execution+permissions+of+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine++%0A++prisma-client+prisma.%24executeRaw%28select+jwt.claims.user_id%2C+%5B%5D%29++%0A++prisma-client+Prisma+Client+call%3A++%0A++engine+stdout++PANIC+in+%2Froot%2F.cargo%2Fgit%2Fcheckouts%2Fquaint-9f01e008b9a89c14%2Fbc3aa8a%2Fsrc%2Fconnector%2Fpostgres%2Ferror.rs%3A138%3A29%0Aindex+out+of+bounds%3A+the+len+is+1+but+the+index+is+1++%0A++engine+TypeError%3A+this.currentRequestPromise.cancel+is+not+a+function%0A++engine+++++at+NodeEngine.handlePanic+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A26344%3A36%29%0A++engine+++++at+NodeEngine.setError+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A26290%3A16%29%0A++engine+++++at+LineStream.%3Canonymous%3E+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A26585%3A24%29%0A++engine+++++at+LineStream.emit+%28events.js%3A311%3A20%29%0A++engine+++++at+addChunk+%28_stream_readable.js%3A294%3A12%29%0A++engine+++++at+readableAddChunk+%28_stream_readable.js%3A275%3A11%29%0A++engine+++++at+LineStream.Readable.push+%28_stream_readable.js%3A209%3A10%29%0A++engine+++++at+LineStream.Transform.push+%28_stream_transform.js%3A152%3A32%29%0A++engine+++++at+LineStream._pushBuffer+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A23721%3A19%29%0A++engine+++++at+LineStream._transform+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A23715%3A10%29++%7B%22timestamp%22%3A%22Jan+15+17%3A04%3A51.789%22%2C%22level%22%3A%22ERROR%22%2C%22fields%22%3A%7B%22message%22%3A%22PANIC%22%2C%22reason%22%3A%22index+out+of+bounds%3A+the+len+is+1+but+the+index+is+1%22%2C%22file%22%3A%22%2Froot%2F.cargo%2Fgit%2Fcheckouts%2Fquaint-9f01e008b9a89c14%2Fbc3aa8a%2Fsrc%2Fconnector%2Fpostgres%2Ferror.rs%22%2C%22line%22%3A138%2C%22column%22%3A29%7D%2C%22target%22%3A%22query_engine%22%7D++%0A++engine+%7B%0A++engine+++error%3A+SocketError%3A+closed%0A++engine+++++++at+Socket.onSocketClose+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A24792%3A33%29%0A++engine+++++++at+Socket.emit+%28events.js%3A311%3A20%29%0A++engine+++++++at+Pipe.%3Canonymous%3E+%28net.js%3A668%3A12%29+%7B%0A++engine+++++name%3A+%27SocketError%27%2C%0A++engine+++++code%3A+%27UND_ERR_SOCKET%27%0A++engine+++%7D%0A++engine+%7D++%0A++engine+%7B%0A++engine+++error%3A+Error%3A+connect+ECONNREFUSED+%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock%0A++engine+++++++at+PipeConnectWrap.afterConnect+%5Bas+oncomplete%5D+%28net.js%3A1137%3A16%29+%7B%0A++engine+++++errno%3A+%27ECONNREFUSED%27%2C%0A++engine+++++code%3A+%27ECONNREFUSED%27%2C%0A++engine+++++syscall%3A+%27connect%27%2C%0A++engine+++++address%3A+%27%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock%27%0A++engine+++%7D%0A++engine+%7D++%0A++engine+Client+Version%3A+2.14.0++%0A++engine+Engine+Version%3A+query-engine+5d491261d382a2a5ffdc71de17072b0e409f1cc1++%0A++engine+Active+provider%3A+postgresql++%0A++engine+%7B%0A++engine+++error%3A+Error%3A+connect+ECONNREFUSED+%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock%0A++engine+++++++at+PipeConnectWrap.afterConnect+%5Bas+oncomplete%5D+%28net.js%3A1137%3A16%29+%7B%0A++engine+++++errno%3A+%27ECONNREFUSED%27%2C%0A++engine+++++code%3A+%27ECONNREFUSED%27%2C%0A++engine+++++syscall%3A+%27connect%27%2C%0A++engine+++++address%3A+%27%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock%27%0A++engine+++%7D%0A++engine+%7D++%2B1s%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A&title=PANIC+in+%2Froot%2F.cargo%2Fgit%2Fcheckouts%2Fquaint-9f01e008b9a89c14%2Fbc3aa8a%2Fsrc%2Fconnector%2Fpostgres%2Ferror.rs%3A138%3A29%0Aindex+out+of+bounds%3A+the+len+is+1+but+the+index+is+1&template=bug_report.mdhttps://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v12.16.1+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+darwin+++++++++++++%7C%0A%7C+Prisma+Client+++%7C+2.14.0+++++++++++++%7C%0A%7C+Query+Engine++++%7C+query-engine+5d491261d382a2a5ffdc71de17072b0e409f1cc1%7C%0A%7C+Database++++++++%7C+undefined%7C%0A%0A%0A%0A%23%23+Query%0A%60%60%60%0Amutation+%7B%0A++executeRaw%28%0A++++query%3A+%22X%22%0A++++parameters%3A+%22X%22%0A++%29%0A%7D%0A%60%60%60%0A%0A%23%23+Logs%0A%60%60%60%0A++tryLoadEnv+Environment+variables+loaded+from+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2F.env++%0A++tryLoadEnv+Environment+variables+loaded+from+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2F.env++%0A++prisma-client+%7B+clientVersion%3A+%272.14.0%27+%7D++%0A++engine+%7B+cwd%3A+%27%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fprisma%27+%7D++%0A++engine+Search+for+Query+Engine+in+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient++%0A++engine+Search+for+Query+Engine+in+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient++%0A++plusX+Execution+permissions+of+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine++%0A++plusX+Execution+permissions+of+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine++%0A++engine+%7B%0A++engine+++flags%3A+%5B%0A++engine+++++%27--enable-raw-queries%27%2C%0A++engine+++++%27--unix-path%27%2C%0A++engine+++++%27%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock%27%0A++engine+++%5D%0A++engine+%7D++%0A++engine+stdout++Starting+a+postgresql+pool+with+13+connections.++%0A++engine+stdout++Started+http+server+on+http%2Bunix%3A%2F%2F%2Fprivate%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock++%0A++engine+Search+for+Query+Engine+in+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient++%0A++prisma-client+prisma.%24executeRaw%28SET+jwt.claims.user_id+%3D+10%2C+%5B%5D%29++%0A++prisma-client+Prisma+Client+call%3A++%0A++plusX+Execution+permissions+of+%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine++%0A++prisma-client+prisma.%24executeRaw%28select+jwt.claims.user_id%2C+%5B%5D%29++%0A++prisma-client+Prisma+Client+call%3A++%0A++engine+stdout++PANIC+in+%2Froot%2F.cargo%2Fgit%2Fcheckouts%2Fquaint-9f01e008b9a89c14%2Fbc3aa8a%2Fsrc%2Fconnector%2Fpostgres%2Ferror.rs%3A138%3A29%0Aindex+out+of+bounds%3A+the+len+is+1+but+the+index+is+1++%0A++engine+TypeError%3A+this.currentRequestPromise.cancel+is+not+a+function%0A++engine+++++at+NodeEngine.handlePanic+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A26344%3A36%29%0A++engine+++++at+NodeEngine.setError+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A26290%3A16%29%0A++engine+++++at+LineStream.%3Canonymous%3E+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A26585%3A24%29%0A++engine+++++at+LineStream.emit+%28events.js%3A311%3A20%29%0A++engine+++++at+addChunk+%28_stream_readable.js%3A294%3A12%29%0A++engine+++++at+readableAddChunk+%28_stream_readable.js%3A275%3A11%29%0A++engine+++++at+LineStream.Readable.push+%28_stream_readable.js%3A209%3A10%29%0A++engine+++++at+LineStream.Transform.push+%28_stream_transform.js%3A152%3A32%29%0A++engine+++++at+LineStream._pushBuffer+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A23721%3A19%29%0A++engine+++++at+LineStream._transform+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A23715%3A10%29++%7B%22timestamp%22%3A%22Jan+15+17%3A04%3A51.789%22%2C%22level%22%3A%22ERROR%22%2C%22fields%22%3A%7B%22message%22%3A%22PANIC%22%2C%22reason%22%3A%22index+out+of+bounds%3A+the+len+is+1+but+the+index+is+1%22%2C%22file%22%3A%22%2Froot%2F.cargo%2Fgit%2Fcheckouts%2Fquaint-9f01e008b9a89c14%2Fbc3aa8a%2Fsrc%2Fconnector%2Fpostgres%2Ferror.rs%22%2C%22line%22%3A138%2C%22column%22%3A29%7D%2C%22target%22%3A%22query_engine%22%7D++%0A++engine+%7B%0A++engine+++error%3A+SocketError%3A+closed%0A++engine+++++++at+Socket.onSocketClose+%28%2FUsers%2Fm%2FGo%2Fsrc%2Fgithub.com%2Fprisma%2Fissue-4303%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A24792%3A33%29%0A++engine+++++++at+Socket.emit+%28events.js%3A311%3A20%29%0A++engine+++++++at+Pipe.%3Canonymous%3E+%28net.js%3A668%3A12%29+%7B%0A++engine+++++name%3A+%27SocketError%27%2C%0A++engine+++++code%3A+%27UND_ERR_SOCKET%27%0A++engine+++%7D%0A++engine+%7D++%0A++engine+%7B%0A++engine+++error%3A+Error%3A+connect+ECONNREFUSED+%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock%0A++engine+++++++at+PipeConnectWrap.afterConnect+%5Bas+oncomplete%5D+%28net.js%3A1137%3A16%29+%7B%0A++engine+++++errno%3A+%27ECONNREFUSED%27%2C%0A++engine+++++code%3A+%27ECONNREFUSED%27%2C%0A++engine+++++syscall%3A+%27connect%27%2C%0A++engine+++++address%3A+%27%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock%27%0A++engine+++%7D%0A++engine+%7D++%0A++engine+Client+Version%3A+2.14.0++%0A++engine+Engine+Version%3A+query-engine+5d491261d382a2a5ffdc71de17072b0e409f1cc1++%0A++engine+Active+provider%3A+postgresql++%0A++engine+%7B%0A++engine+++error%3A+Error%3A+connect+ECONNREFUSED+%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock%0A++engine+++++++at+PipeConnectWrap.afterConnect+%5Bas+oncomplete%5D+%28net.js%3A1137%3A16%29+%7B%0A++engine+++++errno%3A+%27ECONNREFUSED%27%2C%0A++engine+++++code%3A+%27ECONNREFUSED%27%2C%0A++engine+++++syscall%3A+%27connect%27%2C%0A++engine+++++address%3A+%27%2Ftmp%2Fprisma-309d86ec139dc8c202ae8134.sock%27%0A++engine+++%7D%0A++engine+%7D++%2B1s%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A&title=PANIC+in+%2Froot%2F.cargo%2Fgit%2Fcheckouts%2Fquaint-9f01e008b9a89c14%2Fbc3aa8a%2Fsrc%2Fconnector%2Fpostgres%2Ferror.rs%3A138%3A29%0Aindex+out+of+bounds%3A+the+len+is+1+but+the+index+is+1&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.

    at PrismaClientFetcher.request (/Users/m/Go/src/github.com/prisma/issue-4303/node_modules/@prisma/client/runtime/index.js:78134:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.14.0'
}
```

## How to reproduce

```js
const { PrismaClient} = require('@prisma/client')

const client= new PrismaClient()

async function main() {
  await client.$connect()
  const id = 10
  await client.$executeRaw(`SET jwt.claims.user_id = ${id}`)
  const result = await client.$executeRaw(`select jwt.claims.user_id`)
  console.log(result)
}

main().catch(console.error).finally(() => client.$disconnect())
```

## Expected behavior

Should be able to click on the issue to create an issue

## Environment & setup

- OS: 
- Database: 
- Node.js version: 
- Prisma version:

```
Environment variables loaded from .env
@prisma/cli          : 2.14.0
@prisma/client       : 2.14.0
Current platform     : darwin
Query Engine         : query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 5d491261d382a2a5ffdc71de17072b0e409f1cc1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.332.0
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this. Might be specific to your shell/terminal.

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/104757188-bf31a980-5782-11eb-8ee0-427baad61378.png)


Can you try using another terminal emulator?

**Comment by matthewmueller** [comment]
Yep, I think you're right. False alarm. Sorry about that!
