### ISSUE TITLE
PANIC in query-engine/connectors/sql-query-connector/src/query_builder/write.rs:22:56called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by alan345** [prisma/prisma#5168]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.18.3           | 
| OS              | darwin             |
| Prisma Client   | 2.14.0             |
| Query Engine    | query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1|
| Database        | undefined|

## Query
```
mutation {
  createOneCharge(data: {
    stripeChargeId: "X"
    source: {
      connect: {
        id: "X"
      }
    }
    invoice: {
      connect: {
        id: "X"
      }
    }
  }) {
    id
    createdAt
    stripeChargeId
    updatedAt
    invoiceId
    sourceId
  }
}
```

## Logs
```
engine {
  engine   flags: [
  engine     '--enable-raw-queries',
  engine     '--unix-path',
  engine     '/tmp/prisma-7bf593125da51df0a0eaa69a.sock'
  engine   ]
  engine }  
  engine stdout  Starting a mysql pool with 13 connections.  
  engine stdout  Started http server on http+unix:///private/tmp/prisma-7bf593125da51df0a0eaa69a.sock  
  engine Search for Query Engine in /Users/alan/Documents/app/nacho/server/node_modules/.prisma/client  
  plusX Execution permissions of /Users/alan/Documents/app/nacho/server/node_modules/.prisma/client/query-engine-darwin are fine  
  engine Client Version: 2.14.0  
  engine Engine Version: query-engine 5d491261d382a2a5ffdc71de17072b0e409f1cc1  
  engine Active provider: mysql  
  engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/query_builder/write.rs:22:56
called `Option::unwrap()` on a `None` value  +9s
  engine TypeError: this.currentRequestPromise.cancel is not a function
  engine     at NodeEngine.handlePanic (/Users/alan/Documents/app/nacho/server/node_modules/@prisma/client/runtime/index.js:26344:36)
  engine     at NodeEngine.setError (/Users/alan/Documents/app/nacho/server/node_modules/@prisma/client/runtime/index.js:26290:16)
  engine     at LineStream.<anonymous> (/Users/alan/Documents/app/nacho/server/node_modules/@prisma/client/runtime/index.js:26585:24)
  engine     at LineStream.emit (events.js:315:20)
  engine     at LineStream.EventEmitter.emit (domain.js:483:12)
  engine     at addChunk (_stream_readable.js:295:12)
  engine     at readableAddChunk (_stream_readable.js:271:9)
  engine     at LineStream.Readable.push (_stream_readable.js:212:10)
  engine     at LineStream.Transform.push (_stream_transform.js:152:32)
  engine     at LineStream._pushBuffer (/Users/alan/Documents/app/nacho/server/node_modules/@prisma/client/runtime/index.js:23721:19)
  engine     at LineStream._transform (/Users/alan/Documents/app/nacho/server/node_modules/@prisma/client/runtime/index.js:23715:10)
  engine     at LineStream.Transform._read (_stream_transform.js:191:10)
  engine     at LineStream.Transform._write (_stream_transform.js:179:12)
  engine     at doWrite (_stream_writable.js:403:12)
  engine     at writeOrBuffer (_stream_writable.js:387:5)
  engine     at LineStream.Writable.write (_stream_writable.js:318:11)
  engine     at Socket.ondata (_stream_readable.js:716:22)
  engine     at Socket.emit (events.js:315:20)
  engine     at Socket.EventEmitter.emit (domain.js:483:12)
  engine     at addChunk (_stream_readable.js:295:12)
  engine     at readableAddChunk (_stream_readable.js:271:9)
  engine     at Socket.Readable.push (_stream_readable.js:212:10)  {"timestamp":"Jan 18 22:27:21.949","level":"ERROR","fields":{"message":"PANIC","reason":"called `Option::unwrap()` on a `None` value","file":"query-engine/connectors/sql-query-connector/src/query_builder/write.rs","line":22,"column":56},"target":"query_engine"}  
  engine {
  engine   error: SocketError: other side closed
  engine       at Socket.onSocketEnd (/Users/alan/Documents/app/nacho/server/node_modules/@prisma/client/runtime/index.js:24788:25)
  engine       at Socket.emit (events.js:327:22)
  engine       at Socket.EventEmitter.emit (domain.js:483:12)
  engine       at endReadableNT (_stream_readable.js:1220:12)
  engine       at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  engine     code: 'UND_ERR_SOCKET'
  engine   }
  engine }  
  engine {
  engine   error: Error: connect ECONNREFUSED /tmp/prisma-7bf593125da51df0a0eaa69a.sock
  engine       at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  engine     errno: 'ECONNREFUSED',
  engine     code: 'ECONNREFUSED',
  engine     syscall: 'connect',
  engine     address: '/tmp/prisma-7bf593125da51df0a0eaa69a.sock'
  engine   }
  engine }  
  engine {
  engine   error: Error: connect ECONNREFUSED /tmp/prisma-7bf593125da51df0a0eaa69a.sock
  engine       at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  engine     errno: 'ECONNREFUSED',
  engine     code: 'ECONNREFUSED',
  engine     syscall: 'connect',
  engine     address: '/tmp/prisma-7bf593125da51df0a0eaa69a.sock'
  engine   }
  engine }  +1s
```

## Client Snippet
```ts
This works: 
    const charge = await ctx.prisma.charge.create({
      data: {
        stripeChargeId: '',
        invoice: {
          connect: {
            id: invoice.id,
          },
        },
      },
    })

Doesnt work: 
    const charge = await ctx.prisma.charge.create({
      data: {
        stripeChargeId: '',
        source: {
          connect: {
            id: source.id,
          },
        },
        invoice: {
          connect: {
            id: invoice.id,
          },
        },
      },
    })
```

## Schema
```prisma

model Charge {
  id             String   @id @default(cuid())
  createdAt      DateTime @default(now())
  stripeChargeId String
  updatedAt      DateTime @updatedAt
  invoiceId      String
  invoice        Invoice  @relation(fields: [invoiceId], references: [id])

  sourceId  String?
  source  Source?

  @@index([invoiceId], name: "invoiceId")
  @@index([sourceId], name: "sourceId")

}
```

**Comment by alan345** [comment]
it is because `@relation(fields: [sourceId], references: [id])` was missing in the schema. 
A nicer error would have been appreciated!

**Comment by pantharshit00** [comment]
Hey @alan345 

Can you please share your whole schema? I wasn't about to reproduce with a simple example.

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
