### ISSUE TITLE
Error: Error in migration engine. Reason: [migration-engine/connectors/sql-migration-connector/src/sql_renderer/sqlite_renderer.rs:229:45] not implemented: text 

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#5169]
Command: `prisma migrate dev --preview-feature`
Version: `2.14.0`
Binary Version: `5d491261d382a2a5ffdc71de17072b0e409f1cc1`
Report: https://prisma-errors.netlify.app/report/12630 
OS: `x64 linux 5.4.0-62-generic`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_renderer/sqlite_renderer.rs:229:45] not implemented: text
    "country" text not handled yet

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/prisma/issues/new

    at ChildProcess.<anonymous> (/home/felipe/www/cep/node_modules/@prisma/cli/build/index.js:54401:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
[migration-engine/connectors/sql-migration-connector/src/sql_renderer/sqlite_renderer.rs:229:45] not implemented: text
    "country" text not handled yet
```

**Comment by tomhoule** [comment]
I had a close look at this, and the code that crashed is now gone, so I think the issue can be closed.

**Comment by tomhoule** [comment]
(that changed with native types — we should be fine now)
