### ISSUE TITLE
Error when migration directory exists but migration script is missing

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#5170]
Command: `prisma migrate dev --preview-feature`
Version: `2.14.0`
Binary Version: `5d491261d382a2a5ffdc71de17072b0e409f1cc1`
Report: https://prisma-errors.netlify.app/report/12625 
OS: `x64 linux 5.4.0-62-generic`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [/root/build/migration-engine/core/src/commands/diagnose_migration_history.rs:98:26] Failed to read migration script: ReadMigrationScriptError(Os { code: 2, kind: NotFound, message: "No such file or directory" }, SpanTrace [{ target: "migration_connector::migrations_directory", name: "read_migration_script", fields: "self=MigrationDirectory { path: \"/home/arnaud-zg/Workspace/contraband-server/prisma/migrations/20210115195523_update_room_model\" }", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 185 }, { target: "migration_connector::migrations_directory", name: "matches_checksum", fields: "self=MigrationDirectory { path: \"/home/arnaud-zg/Workspace/contraband-server/prisma/migrations/20210115195523_update_room_model\" } checksum_str=\"5ce8cf98785c6e469fd3453179dd346b84b37125bfc44601c05aa65969e7\"", file: "migration-engine/connectors/migration-connector/src/migrations_directory.rs", line: 159 }, { target: "migration_core::api", name: "DiagnoseMigrationHistory", file: "migration-engine/core/src/api.rs", line: 109 }])

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/prisma/issues/new

    at ChildProcess.<anonymous> (/home/arnaud-zg/Workspace/contraband-server/node_modules/@prisma/cli/build/index.js:54401:23)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (do

**Comment by pantharshit00** [comment]
I think we might look into how we handle this file read in code.

**Comment by pantharshit00** [comment]
Another report: https://github.com/prisma/prisma/issues/5170
