### ISSUE TITLE
Error: Error in migration engine. Reason: [libs/datamodel/core/src/transform/ast_to_dml/validate.rs:226:34] called `Option::unwrap()` on a `None` value 

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma#5171]
Command: `prisma migrate dev --preview-feature`
Version: `2.14.0`
Binary Version: `5d491261d382a2a5ffdc71de17072b0e409f1cc1`
Report: https://prisma-errors.netlify.app/report/12587 
OS: `x64 linux 5.8.0-36-generic`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [libs/datamodel/core/src/transform/ast_to_dml/validate.rs:226:34] called `Option::unwrap()` on a `None` value

Please create an issue in the migrate repo with
your `schema.prisma` and the prisma command you tried to use 🙏:
https://github.com/prisma/prisma/issues/new

    at ChildProcess.<anonymous> (/home/pedro/javascript/interas/glpi/node_modules/@prisma/cli/build/index.js:54401:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
[libs/datamodel/core/src/transform/ast_to_dml/validate.rs:226:34] called `Option::unwrap()` on a `None` value
```

**Comment by pantharshit00** [comment]
Refer to the error report for the data model .

**Comment by albertoperdomo** [comment]
Probably related to https://github.com/prisma/prisma-engines/issues/1537

**Comment by albertoperdomo** [comment]
We should check if this is still happening.
