### ISSUE TITLE
Fix yarn workspace

### ISSUE THREAD

**Issue by timsuchanek** [prisma/prisma#5299]
Tracking issue for https://github.com/prisma/prisma/issues/5266#issuecomment-767656190

Clone blitz-js/blitz
```
yarn
yarn build
cd examples/auth
blitz start
# Open page in browser
# See Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
```

**Comment by williamluke4** [comment]
Hey @flybayer, I have tried to reproduce this by following your instructions but I receive the following error when running `yarn start` in `/examples/auth`.
```
blitz/examples/auth on  canary  via ⬢ v14.15.3 on ☁️  (eu-central-1) on ☁️ williamluke4@gmail.com 
❯ yarn start                                                                                                                                                                                                        (base) 
yarn run v1.22.10
$ blitz start
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

Error: Could not find a production build in the '/home/will/Prisma/blitz/examples/auth/.blitz/caches/build/.next' directory. Try building your app with 'next build' before starting the production server. https://err.sh/vercel/next.js/production-start-no-build-id
    at Server.readBuildId (/home/will/Prisma/blitz/node_modules/next/dist/next-server/server/next-server.js:146:355)
    at new Server (/home/will/Prisma/blitz/node_modules/next/dist/next-server/server/next-server.js:3:120)
    at createServer (/home/will/Prisma/blitz/node_modules/next/dist/server/next.js:2:638)
    at start (/home/will/Prisma/blitz/node_modules/next/dist/server/lib/start-server.js:1:323)
    at nextStart (/home/will/Prisma/blitz/node_modules/next/dist/cli/next-start.js:19:233)
    at /home/will/Prisma/blitz/node_modules/next/dist/bin/next:27:115
'next start' failed with status code: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I have also tested the yarn workspace behaviour with our [e2e test](https://github.com/prisma/e2e-tests/tree/dev/packagers/yarn-workspaces) and upon running `yarn` in the workspace root prisma does get generated. If this is still an issue for you, could you please try provide a minimal reproduction.

**Comment by flybayer** [comment]
@williamluke4 the command to start the server is now `yarn dev` or `blitz dev`. This just changed last week on canary, sorry about that!

**Comment by williamluke4** [comment]
Ok, so I've done some digging and added a log to our `postintall` hook (`Postinstall Trigger:`). It seems that our `postinstall` hook is correctly being trigger once when running `yarn`, but it seems that something else is also calling `prisma generate`. 
The only thing I can assume is that Blitz is also trying to generate the client on install (@flybayer can you confirm this). 
```
[sqlite3] Success: "/home/will/Prisma/blitz/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote
node-pre-gyp info ok
verbose 384.194443364 Prisma schema loaded from examples/auth/db/schema.prisma

✔ Generated Prisma Client (2.17.0-integration-postinstall-test.1) to ./examples/auth/node_modules/@prisma/client in 129ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()


warn Versions of prisma@2.16.0 and @prisma/client@2.17.0-integration-postinstall-test.1 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
verbose 384.206928304 Prisma schema loaded from examples/auth/db/schema.prisma

✔ Generated Prisma Client (2.17.0-integration-postinstall-test.1) to ./examples/auth/node_modules/@prisma/client in 131ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()


warn Versions of prisma@2.16.0 and @prisma/client@2.17.0-integration-postinstall-test.1 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
verbose 384.227069854 Prisma schema loaded from examples/auth/db/schema.prisma

✔ Generated Prisma Client (2.17.0-integration-postinstall-test.1) to ./examples/auth/node_modules/@prisma/client in 151ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()


warn Versions of prisma@2.16.0 and @prisma/client@2.17.0-integration-postinstall-test.1 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
verbose 384.996597941 Prisma schema loaded from examples/auth/db/schema.prisma

✔ Generated Prisma Client (2.17.0-integration-postinstall-test.1) to ./examples/auth/node_modules/@prisma/client in 142ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

Postinstall Trigger:yarn --verbose
success Saved lockfile.
$ npm rebuild husky && patch-package
rebuilt dependencies successfully
patch-package 6.2.2
Applying patches...
release@6.3.0 ✔
Done in 387.60s.
```
[full log; relevant output is right at the end](https://gist.github.com/williamluke4/e084b78382c1a107c657bd122bbf48e9)

**Comment by flybayer** [comment]
@williamluke4 interesting. Blitz definitely isn't generating the client. Maybe a bug in yarn where it's calling postinstall twice?

**Comment by williamluke4** [comment]
> Maybe a bug in yarn where it's calling postinstall twice?

Don't think so because the [postinstall trigger](https://github.com/prisma/prisma/pull/5550/files#diff-e7efd4fab55d10b7be51bdaa58dc339618a879aec3b564637a05c4af07735110R121) is only logged :point_up: once

**Comment by williamluke4** [comment]
https://github.com/williamluke4/blitz/tree/fix/prisma-postinstall

**Comment by timsuchanek** [comment]
I just tried out @williamluke4's fix with the following steps:
```
yarn install
yarn build
cd exmaples/auth
yarn
yarn build
yarn dev
```
and it works.

Without the `yarn build` in the `examples/auth` folder, it errored that the manifest could not be found.

**Comment by flybayer** [comment]
yes, I confirmed his fix works for me too
