### ISSUE TITLE
Prisma throwing the P1001 error when running the `npx prisma introspect` command against an existing MySQL database.

### ISSUE THREAD

**Issue by keithbeller** [prisma/prisma#5341]
## Bug description

Prisma throwing the P1001 error when running the `npx prisma introspect` command against an existing MySQL database.

````
Error: Error: P1001 
Can't reach database server at `software_name_app`:`3306`
Please make sure your database server is running at `software_name_app`:`3306`.
````

Prisma interprets the database `user` as the `host`.  Compare error with a sanitized connection string. 

````
DATABASE_URL="mysql://software_name_app:#XX&XX1XX&&XXXxx@localhost:3306/software_name"
````

Here is the DEBUG

```
username@Computer software_name-api % npx prisma introspect
  tryLoadEnv Environment variables loaded from /Users/username/Code/software_name-api/.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

Introspecting based on datasource defined in prisma/schema.prisma …
  IntrospectionEngine:rpc starting introspection engine with binary: /Users/username/Code/software_name-api/node_modules/@prisma/engines/introspection-engine-darwin +0ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"mysql\"\n  url      = \"mysql://software_name_app:#XX&XX1XXXXXXXxx@localhost:3306/software_name\"\n  //env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n"}]} +11ms
  IntrospectionEngine:rpc {
  IntrospectionEngine:rpc   jsonrpc: '2.0',
  IntrospectionEngine:rpc   error: {
  IntrospectionEngine:rpc     code: 4466,
  IntrospectionEngine:rpc     message: 'An error happened. Check the data field for details.',
  IntrospectionEngine:rpc     data: {
  IntrospectionEngine:rpc       is_panic: false,
  IntrospectionEngine:rpc       message: "Can't reach database server at `software_name_app`:`3306`\n" +
  IntrospectionEngine:rpc         '\n' +
  IntrospectionEngine:rpc         'Please make sure your database server is running at `software_name_app`:`3306`.',
  IntrospectionEngine:rpc       meta: [Object],
  IntrospectionEngine:rpc       error_code: 'P1001'
  IntrospectionEngine:rpc     }
  IntrospectionEngine:rpc   },
  IntrospectionEngine:rpc   id: 1
  IntrospectionEngine:rpc } +21ms
Error: Error: P1001

Can't reach database server at `software_name_app`:`3306`

Please make sure your database server is running at `software_name_app`:`3306`.

    at Object.<anonymous> (/Users/username/Code/software_name-api/node_modules/@prisma/cli/build/index.js:4862:26)
    at IntrospectionEngine3.handleResponse (/Users/username/Code/software_name-api/node_modules/@prisma/cli/build/index.js:4742:36)
    at LineStream.<anonymous> (/Users/username/Code/software_name-api/node_modules/@prisma/cli/build/index.js:4820:18)
    at LineStream.emit (events.js:315:20)
    at LineStream.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at LineStream.Readable.push (internal/streams/readable.js:223:10)
    at LineStream.Transform.push (internal/streams/transform.js:166:32)
    at LineStream._pushBuffer (/Users/username/Code/software_name-api/node_modules/@prisma/cli/build/index.js:4555:19)
```

### Swapping the `user` and `host` values
When the database `user` and `host` names are swapped in the query string the following error is thrown. 

````
Error in connector: Error querying the database: Error querying the database: Error querying the database: Unknown authentication plugin `sha256_password'.
````

Here is the DEBUG

````
username@Computer software_name-api % npx prisma introspect
  tryLoadEnv Environment variables loaded from /Users/username/code/software_name-api/.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

Introspecting based on datasource defined in prisma/schema.prisma …
  IntrospectionEngine:rpc starting introspection engine with binary: /Users/username/code/software_name-api/node_modules/@prisma/engines/introspection-engine-darwin +0ms
  IntrospectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ndatasource db {\n  provider = \"mysql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n"}]} +13ms
  IntrospectionEngine:rpc {
  IntrospectionEngine:rpc   jsonrpc: '2.0',
  IntrospectionEngine:rpc   error: {
  IntrospectionEngine:rpc     code: 4466,
  IntrospectionEngine:rpc     message: 'An error happened. Check the data field for details.',
  IntrospectionEngine:rpc     data: {
  IntrospectionEngine:rpc       is_panic: false,
  IntrospectionEngine:rpc       message: "Error in connector: Error querying the database: Error querying the database: Error querying the database: Unknown authentication plugin `sha256_password'.",
  IntrospectionEngine:rpc       backtrace: null
  IntrospectionEngine:rpc     }
  IntrospectionEngine:rpc   },
  IntrospectionEngine:rpc   id: 1
  IntrospectionEngine:rpc } +29ms
Error: Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: Unknown authentication plugin `sha256_password'.

    at Object.<anonymous> (/Users/username/code/software_name-api/node_modules/@prisma/cli/build/index.js:4864:26)
    at IntrospectionEngine3.handleResponse (/Users/username/code/software_name-api/node_modules/@prisma/cli/build/index.js:4742:36)
    at LineStream.<anonymous> (/Users/username/code/software_name-api/node_modules/@prisma/cli/build/index.js:4820:18)
    at LineStream.emit (events.js:315:20)
    at LineStream.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at LineStream.Readable.push (internal/streams/readable.js:223:10)
    at LineStream.Transform.push (internal/streams/transform.js:166:32)
    at LineStream._pushBuffer (/Users/username/code/software_name-api/node_modules/@prisma/cli/build/index.js:4555:19)
````

## Expected behavior

`npx prisma introspect` should run without error.

## Prisma information
Here is a sanitized example of my database connection URL with mappings below.
DATABASE_URL="mysql://software_name_app:#XX&XX1XX&&XXXxx@localhost:3306/software_name"

HOST=localhost
DB_USER=software_name_app
DB_PASS=#XX&XX1XX&&XXXxx
DB_DATABASE=software_name

## Environment & setup
- OS: macOS Big Sur 11.1
- Hardware: MacBook Pro M1
- Database: Mysql Ver 8.0.22 for macos10.15 on x86_64 (MySQL Community Server - GPL)
- Node.js version: v14.15.4
- Prisma version: 6.14.10

**Comment by janpio** [comment]
Probably same as https://github.com/prisma/prisma/issues/2177#issuecomment-621955760

**Comment by pantharshit00** [comment]
Indeed, please make sure special characters like `#` or `@` are percent encoded.

**Comment by nyxongod** [comment]
I do have the same problem but my password does not contain any special characters only letters and numbers, I can't use any prisma command , always the same error P1001,

Do you know why is that ?

**Comment by janpio** [comment]
No, please open a new issue and provide a lot more information if you want help.
