### ISSUE TITLE
Prisma query engine panic in making relation query

### ISSUE THREAD

**Issue by arifali123** [prisma/prisma#5407]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.15.1           | 
| OS              | windows            |
| Prisma Client   | 2.15.0             |
| Query Engine    | query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54|
| Database        | undefined|

## Query
```
query {
  findManyIssue(where: {
    resolved: false
    message: null
    request: {
      evidence: {
        isNot: null
      }
    }
  }) {
    id
    resolved
    approved
    reason
    request {
      id
      timecreated
      email
      issue
      orderid
      cashcode
      translink
      repreq
      otherissue
      evidence {
        id
        timeupload
        origname
        ETag
        key
        Location
        originid
      }
    }
  }
}
```

## Logs
```
ransform.js:193:12)
  engine     at writeOrBuffer (_stream_writable.js:352:12)
  engine     at LineStream.Writable.write (_stream_writable.js:303:10)
  engine     at Socket.ondata (_stream_readable.js:719:22)
  engine     at Socket.emit (events.js:315:20)  {"timestamp":"Feb 01 12:15:54.500","level":"ERROR","fields":{"message":"PANIC","reason":"index out of bounds: the len is 1 but the index is 1","file":"C:\\Users\\runneradmin\\.cargo\\git\\checkouts\\quaint-9f01e008b9a89c14\\2d8c9c7\\src\\connector\\postgres\\error.rs","line":138,"column":29},"target":"query_engine"}  
  engine {
  engine   error: Error: read ECONNRESET
  engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  engine     errno: -4077,
  engine     code: 'ECONNRESET',
  engine     syscall: 'read'
  engine   }
  engine }  
  engine {
  engine   error: Error: connect ECONNREFUSED 127.0.0.1:59118
  engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  engine     errno: -4078,
  engine     code: 'ECONNREFUSED',
  engine     syscall: 'connect',
  engine     address: '127.0.0.1',
  engine     port: 59118
  engine   }
  engine }  
  engine There is a child that still runs and we want to start again  
  engine { cwd: 'C:\\Users\\arifa\\Desktop\\Projects\\supplied-form\\prisma' }  
  engine Search for Query Engine in C:\Users\arifa\Desktop\Projects\supplied-form\node_modules\.prisma\client  
  engine { flags: [ '--enable-raw-queries' ] }  
  engine port: 59122  
  engine stdout  Starting a postgresql pool with 17 connections.  
  engine stdout  Started http server on http://127.0.0.1:59122  
  engine Search for Query Engine in C:\Users\arifa\Desktop\Projects\supplied-form\node_modules\.prisma\client  
  engine Client Version: 2.15.0  
  engine Engine Version: query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54  
  engine Active provider: postgresql  
  engine stdout  PANIC in C:\Users\runneradmin\.cargo\git\checkouts\quaint-9f01e008b9a89c14\2d8c9c7\src\connector\postgres\error.rs:138:29
index out of bounds: the len is 1 but the index is 1  
  engine TypeError: this.currentRequestPromise.cancel is not a function
  engine     at NodeEngine.handlePanic (C:\Users\arifa\Desktop\Projects\supplied-form\node_modules\@prisma\client\runtime\index.js:26519:36)
  engine     at NodeEngine.setError (C:\Users\arifa\Desktop\Projects\supplied-form\node_modules\@prisma\client\runtime\index.js:26465:16)
  engine     at LineStream.<anonymous> (C:\Users\arifa\Desktop\Projects\supplied-form\node_modules\@prisma\client\runtime\index.js:26760:24)
  engine     at LineStream.emit (events.js:315:20)
  engine     at addChunk (_stream_readable.js:309:12)
  engine     at readableAddChunk (_stream_readable.js:284:9)
  engine     at LineStream.Readable.push (_stream_readable.js:223:10)
  engine     at LineStream.Transform.push (_stream_transform.js:166:32)
  engine     at LineStream._pushBuffer (C:\Users\arifa\Desktop\Projects\supplied-form\node_modules\@prisma\client\runtime\index.js:23721:19)
  engine     at LineStream._transform (C:\Users\arifa\Desktop\Projects\supplied-form\node_modules\@prisma\client\runtime\index.js:23715:10)
  engine     at LineStream.Transform._read (_stream_transform.js:205:10)
  engine     at LineStream.Transform._write (_stream_transform.js:193:12)
  engine     at writeOrBuffer (_stream_writable.js:352:12)
  engine     at LineStream.Writable.write (_stream_writable.js:303:10)
  engine     at Socket.ondata (_stream_readable.js:719:22)
  engine     at Socket.emit (events.js:315:20)  {"timestamp":"Feb 01 12:15:55.278","level":"ERROR","fields":{"message":"PANIC","reason":"index out of bounds: the len is 1 but the index is 1","file":"C:\\Users\\runneradmin\\.cargo\\git\\checkouts\\quaint-9f01e008b9a89c14\\2d8c9c7\\src\\connector\\postgres\\error.rs","line":138,"column":29},"target":"query_engine"}  
  engine {
  engine   error: Error: read ECONNRESET
  engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  engine     errno: -4077,
  engine     code: 'ECONNRESET',
  engine     syscall: 'read'
  engine   }
  engine }  
```

## Client Snippet
```ts
const issues = await prisma.issue.findMany({
    where: {
      resolved: false,
      message: null,
      request: { evidence: { isNot: null } },
    },
    include: { request: { include: { evidence: true } } },
  });
```

## Schema
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Request {
  id          String   @id @default(uuid())
  timecreated DateTime @default(now())
  email       String
  issue       String
  orderid     String
  cashcode    String?
  translink   String?
  repreq      Int?
  otherissue  String?
  evidence    File?
  Issue       Issue?

  @@map(name: "REQUESTS")
}

model File {
  id         String   @id
  timeupload DateTime @default(now())
  origname   String
  ETag       String
  key        String
  Location   String
  origin     Request  @relation(fields: [originid], references: [id])
  originid   String

  @@map(name: "FILES")
}

model Issue {
  id       String   @id
  resolved Boolean
  approved Boolean?
  reason   String?
  message  Message?
  request  Request  @relation(fields: [id], references: [id])

  @@map(name: "ISSUES")
}

model Message {
  id       String   @id
  timesent DateTime
  issueid  String
  issue    Issue    @relation(fields: [issueid], references: [id])

  @@map(name: "MESSAGES")
}
```

**Comment by pantharshit00** [comment]
Hey @arifali123 

Can you please try this with the 2.16 release and tell us if this is already fixed? We did some recent fixes on that area so this might be already addressed.

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
