### ISSUE TITLE
Basic create query for model with implicit many to many relationship not working as described in official support article

### ISSUE THREAD

**Issue by saltenasl** [prisma/prisma#5472]
Hi Prisma team!

## Bug description

I'm following the documentation on how to create a new post with its tags (https://www.prisma.io/docs/support/help-articles/working-with-many-to-many-relations#implicit-relations) and it is not working. One small difference between my scenario and the example in the aforementioned support article is the model naming differences - in my case `Post` is a `Note` and `Tag` is a `Hashtag`

## How to reproduce

I've created a github repository with an example: https://github.com/saltenasl/prisma-many-to-many-example/tree/master

To reproduce (taken from README.md of the aforementioned example repo):
1. run `npm i`
2. make sure that the credentials in the `.env` file are valid and are pointing to an empty database
3. execute migrations `npx prisma migrate dev --preview-feature`
4. run `npm start` and observe the error

The error:
```
> prisma-many-to-many-example@1.0.0 start /Users/lukassaltenas/p/prisma-many-to-many-example
> DEBUG="*" node index.js

  tryLoadEnv Environment variables loaded from /Users/lukassaltenas/p/prisma-many-to-many-example/.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # Environment variables declared in this file are automatically made available to Prisma.
[dotenv][DEBUG] did not match key and value when parsing line 2: # See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables
[dotenv][DEBUG] did not match key and value when parsing line 3:
[dotenv][DEBUG] did not match key and value when parsing line 4: # Prisma supports the native connection string format for PostgreSQL, MySQL and SQLite.
[dotenv][DEBUG] did not match key and value when parsing line 5: # See the documentation for all the connection string options: https://pris.ly/d/connection-strings
[dotenv][DEBUG] did not match key and value when parsing line 6:
[dotenv][DEBUG] did not match key and value when parsing line 8:
  tryLoadEnv Environment variables loaded from /Users/lukassaltenas/p/prisma-many-to-many-example/.env +2ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # Environment variables declared in this file are automatically made available to Prisma.
[dotenv][DEBUG] did not match key and value when parsing line 2: # See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables
[dotenv][DEBUG] did not match key and value when parsing line 3:
[dotenv][DEBUG] did not match key and value when parsing line 4: # Prisma supports the native connection string format for PostgreSQL, MySQL and SQLite.
[dotenv][DEBUG] did not match key and value when parsing line 5: # See the documentation for all the connection string options: https://pris.ly/d/connection-strings
[dotenv][DEBUG] did not match key and value when parsing line 6:
[dotenv][DEBUG] did not match key and value when parsing line 8:
[dotenv][DEBUG] "DATABASE_URL" is already defined in `process.env` and will not be overwritten
  prisma-client { clientVersion: '2.16.0' } +0ms
  engine Search for Query Engine in /Users/lukassaltenas/p/prisma-many-to-many-example/node_modules/.prisma/client +0ms
PrismaClientValidationError:
Invalid `prisma.note.create()` invocation:

{
  data: {
    title: 'Types of relations',
    tags: {
    ~~~~
      create: [
        {
          name: 'dev'
        },
        {
          name: 'prisma'
        }
      ]
    }
  }
}

Unknown arg `tags` in data.tags for type NoteUncheckedCreateInput. Did you mean `id`? Available args:
type NoteUncheckedCreateInput {
  id?: Int
  title: String
}


    at Document.validate (/Users/lukassaltenas/p/prisma-many-to-many-example/node_modules/@prisma/client/runtime/index.js:76246:19)
    at NewPrismaClient._executeRequest (/Users/lukassaltenas/p/prisma-many-to-many-example/node_modules/@prisma/client/runtime/index.js:78075:17)
    at /Users/lukassaltenas/p/prisma-many-to-many-example/node_modules/@prisma/client/runtime/index.js:78010:52
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (/Users/lukassaltenas/p/prisma-many-to-many-example/node_modules/@prisma/client/runtime/index.js:78010:25)
    at Object.then (/Users/lukassaltenas/p/prisma-many-to-many-example/node_modules/@prisma/client/runtime/index.js:78130:39) {
  clientVersion: '2.16.0'
}
  plusX Execution permissions of /Users/lukassaltenas/p/prisma-many-to-many-example/node_modules/.prisma/client/query-engine-darwin are fine +0ms
```

## Expected behavior

A Note should be created.

## Prisma information

Prisma schema - https://github.com/saltenasl/prisma-many-to-many-example/blob/master/prisma/schema.prisma
Prisma client query - https://github.com/saltenasl/prisma-many-to-many-example/blob/master/index.js#L7

## Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: 14.15.4
- Prisma version:
```
prisma               : 2.16.0
@prisma/client       : 2.16.0
Current platform     : darwin
Query Engine         : query-engine 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.346.0
```

**Comment by saltenasl** [comment]
Sorry, there was an error in the examples code.
