### ISSUE TITLE
Error: Error in migration engine. Reason: [libs/datamodel/core/src/transform/helpers/value_validator.rs:202:26] Should only be empty or single String. 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#5481]
Command: `prisma migrate dev --name init --preview-feature`
Version: `2.16.0`
Binary Version: `a973e24a4e5194f8fe3301bfa7ff982b24f97c05`
Report: https://prisma-errors.netlify.app/report/12892 
OS: `x64 darwin 20.2.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [libs/datamodel/core/src/transform/helpers/value_validator.rs:202:26] Should only be empty or single String.

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

    at ChildProcess.<anonymous> (/Users/alimurad/Desktop/Prisma2/node_modules/@prisma/cli/build/index.js:54621:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
[libs/datamodel/core/src/transform/helpers/value_validator.rs:202:26] Should only be empty or single String.
```

**Comment by janpio** [comment]
Probably related: https://github.com/prisma/prisma/issues/5424 https://github.com/prisma/prisma/issues/5476
