### ISSUE TITLE
Error in PostgreSQL connection: Error { kind: Closed, cause: None }

### ISSUE THREAD

**Issue by AHBruns** [prisma/prisma#5515]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v15.5.0            | 
| OS              | darwin             |
| Prisma Client   | 2.15.0             |
| Query Engine    | query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54|
| Database        | undefined|

## Query
```
The query was programmatically generated. See the code below.
```

## Logs
```
m
  engine Search for Query Engine in /Users/alexbruns/code/autodidactv3/node_modules/.prisma/client  
  plusX Execution permissions of /Users/alexbruns/code/autodidactv3/node_modules/.prisma/client/query-engine-darwin are fine  
  engine { flags: [ '--enable-raw-queries' ] }  
  engine port: 54820  
  engine stdout  Starting a postgresql pool with 9 connections.  
  engine stdout  Started http server on http://127.0.0.1:54820  
  engine Search for Query Engine in /Users/alexbruns/code/autodidactv3/node_modules/.prisma/client  
  plusX Execution permissions of /Users/alexbruns/code/autodidactv3/node_modules/.prisma/client/query-engine-darwin are fine  
  engine Client Version: 2.15.0  
  engine Engine Version: query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54  
  engine Active provider: postgresql  
  engine {
  engine   error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
  engine       at NodeEngine.graphQLToJSError (/Users/alexbruns/code/autodidactv3/node_modules/@prisma/client/runtime/index.js:27079:14)
  engine       at NodeEngine.request (/Users/alexbruns/code/autodidactv3/node_modules/@prisma/client/runtime/index.js:26975:24)
  engine       at runMicrotasks (<anonymous>)
  engine       at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  engine     clientVersion: '2.15.0'
  engine   }
  engine }  +2d
  engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }  
  engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }  
  engine {
  engine   error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
  engine       at NodeEngine.graphQLToJSError (/Users/alexbruns/code/autodidactv3/node_modules/@prisma/client/runtime/index.js:27079:14)
  engine       at NodeEngine.request (/Users/alexbruns/code/autodidactv3/node_modules/@prisma/client/runtime/index.js:26975:24)
  engine       at runMicrotasks (<anonymous>)
  engine       at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  engine     clientVersion: '2.15.0'
  engine   }
  engine }  
  engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }  +2d
  engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }  
  engine {
  engine   error: Error: Error occurred during query execution:
  engine   InterpretationError("Error for binding \'3\'", Some(QueryGraphBuilderError(RelationViolation(RelationViolation { relation_name: "LicenseToRightArea", model_a_name: "License", model_b_name: "RightArea" }))))
  engine       at /Users/alexbruns/code/autodidactv3/node_modules/@prisma/client/runtime/index.js:27026:19
  engine       at runMicrotasks (<anonymous>)
  engine       at processTicksAndRejections (node:internal/process/task_queues:93:5)
  engine }  +21h
  engine {
  engine   error: Error: Error occurred during query execution:
  engine   InterpretationError("Error for binding \'3\'", Some(QueryGraphBuilderError(RelationViolation(RelationViolation { relation_name: "LicenseToRightArea", model_a_name: "License", model_b_name: "RightArea" }))))
  engine       at /Users/alexbruns/code/autodidactv3/node_modules/@prisma/client/runtime/index.js:27026:19
  engine       at runMicrotasks (<anonymous>)
  engine       at processTicksAndRejections (node:internal/process/task_queues:93:5)
  engine }  
  engine {
  engine   error: Error: Error occurred during query execution:
  engine   InterpretationError("Error for binding \'3\'", Some(QueryGraphBuilderError(RelationViolation(RelationViolation { relation_name: "LicenseToRightArea", model_a_name: "License", model_b_name: "RightArea" }))))
  engine       at /Users/alexbruns/code/autodidactv3/node_modules/@prisma/client/runtime/index.js:27026:19
  engine       at runMicrotasks (<anonymous>)
  engine       at processTicksAndRejections (node:internal/process/task_queues:93:5)
  engine }  
```

## Client Snippet
```ts
import { assert } from "console";
import { NextApiHandler } from "next";
import prisma, { deepRightArea } from "../../../lib/prisma";
import { Prisma } from "@prisma/client";
import { getSession } from "next-auth/client";
import { ppCreateContract } from "../../../lib/preprossessor";
import { deleteContract } from "../../../lib/deleteTransactionBuilder";

const includer = {
  include: {
    licenses: {
      include: {
        ipArticle: true,
        rightArea: deepRightArea,
      },
    },
  },
} as const;

export type DeepContract = Prisma.ContractGetPayload<typeof includer>;

const handler: NextApiHandler<DeepContract | DeepContract[]> = async (
  req,
  res
) => {
  try {
    const session = await getSession({ req });
    assert(session);
    switch (req.method) {
      case "POST": {
        return res.json(
          await prisma.contract.create({
            data: ppCreateContract(req.body, { userId: session?.userId }),
            ...includer,
          })
        );
      }
      case "GET": {
        return res.json(
          await prisma.contract.findMany({
            where: { ownerId: session?.userId },
            ...includer,
          })
        );
      }
      case "DELETE": {
        await prisma.$transaction(deleteContract(req.body));
        return res.end();
      }
      default:
        throw new Error("Unsupported HTTP method");
    }
  } catch (e) {
    console.error(e);
    res.status(400).end();
  }
};

export default handler;

// in ../../../lib/deleteTransactionBuilder

import { DeepContract } from "../pages/api/contract";
import { DeepIpArticle } from "../pages/api/ip-article";
import { DeepLicense } from "../pages/api/license";
import prisma from "./prisma";

export const deleteContract = (v: DeepContract) => {
  let queries: unknown[] = [];
  queries = [
    ...queries,
    ...v.licenses.reduce<unknown[]>(
      (acc, license) => [...acc, ...deleteLicense(license)],
      []
    ),
  ];
  queries = [...queries, prisma.contract.delete({ where: { id: v.id } })];
  return queries;
};

export const deleteIpArticle = (v: DeepIpArticle) => {
  let queries: unknown[] = [];
  queries = [
    ...queries,
    ...v.licenses.reduce<unknown[]>(
      (acc, license) => [...acc, ...deleteLicense(license)],
      []
    ),
  ];
  queries = [...queries, prisma.iPArticle.delete({ where: { id: v.id } })];
  return queries;
};

export const deleteLicense = (
  v: Omit<DeepLicense, "contract" | "ipArticle">
) => {
  let queries: unknown[] = [];
  queries = [...queries, ...deleteRightArea(v.rightArea)];
  queries = [...queries, prisma.license.delete({ where: { id: v.id } })];
  return queries;
};

export const deleteRightArea = (v: DeepLicense["rightArea"]) => {
  let queries: unknown[] = [];
  queries = [
    ...queries,
    ...v.children.reduce<unknown[]>(
      (acc, child) => [...acc, ...deleteRightArea(child)],
      []
    ),
  ];
  queries = [...queries, prisma.rightArea.delete({ where: { id: v.id } })];
  return queries;
};

```

## Schema
```prisma
datasource db {
  provider = "postgresql"
  url = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model PrimitiveRight {
  id String @default(cuid()) @id
  name String @unique
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

model Qualifier {
  id String @default(cuid()) @id
  name String @unique
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

enum RightAreaType {
  SUBTRACTIVE
  ADDITIVE
}

model RightArea {
  id String @default(cuid()) @id
  type RightAreaType
  primitiveRights PrimitiveRight[]
  qualifiers Qualifier[]
  children RightArea[]
  license License?
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

model License {
  id String @default(cuid()) @id
  startDate DateTime?
  contract Contract @relation(fields: [contractId], references: [id])
  contractId String
  ipArticle IPArticle @relation(fields: [ipArticleId], references: [id])
  ipArticleId String
  rightArea RightArea @relation(fields: [rightAreaId], references: [id])
  rightAreaId String
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

model Contract {
  id String @default(cuid()) @id
  name String
  signingDate DateTime
  licenses License[]
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

model IPArticle {
  id String @default(cuid()) @id
  name String
  description String?
  licenses License[]
  owner User @relation(fields: [ownerId], references: [id])
  ownerId Int
}

model User {
  id Int @default(autoincrement()) @id
  name String?
  email String? @unique
  emailVerified DateTime? @map(name: "email_verified")
  image String?
  createdAt DateTime @default(now()) @map(name: "created_at")
  updatedAt DateTime @updatedAt @map(name: "updated_at")

  IpArticles IPArticle[]
  Contracts Contract[]
  Licenses License[]
  RightArea RightArea[]
  Qualifier Qualifier[]
  PrimitiveRight PrimitiveRight[]

  @@map(name: "users")
}

model Account {
  id                 Int       @default(autoincrement()) @id
  compoundId         String    @unique @map(name: "compound_id")
  userId             Int       @map(name: "user_id")
  providerType       String    @map(name: "provider_type")
  providerId         String    @map(name: "provider_id")
  providerAccountId  String    @map(name: "provider_account_id")
  refreshToken       String?   @map(name: "refresh_token")
  accessToken        String?   @map(name: "access_token")
  accessTokenExpires DateTime? @map(name: "access_token_expires")
  createdAt          DateTime  @default(now()) @map(name: "created_at")
  updatedAt          DateTime  @default(now()) @map(name: "updated_at")

  @@index([providerAccountId], name: "providerAccountId")
  @@index([providerId], name: "providerId")
  @@index([userId], name: "userId")

  @@map(name: "accounts")
}

model Session {
  id           Int      @default(autoincrement()) @id
  userId       Int      @map(name: "user_id")
  expires      DateTime
  sessionToken String   @unique @map(name: "session_token")
  accessToken  String   @unique @map(name: "access_token")
  createdAt    DateTime @default(now()) @map(name: "created_at")
  updatedAt    DateTime @default(now()) @map(name: "updated_at")

  @@map(name: "sessions")
}
```

**Comment by Sytten** [comment]
Same as https://github.com/prisma/prisma/issues/5976

**Comment by janpio** [comment]
Information about the PR that closed this:
https://github.com/prisma/prisma/issues/6329#issuecomment-815012006

Feel free to reply here again if the problem is not solved/better for you and we can reopen the issue of course.
