### ISSUE TITLE
Fix distro detection for raspberry pi

### ISSUE THREAD

**Issue by sfoxdev** [prisma/prisma#5552]
## Bug description

I found that starting from version 2.14.0 Prisma support ARM64. 
Source: https://github.com/prisma/prisma/releases/tag/2.14.0 and https://github.com/prisma/prisma/issues/861#issuecomment-764867224

I need to run project on Raspberry Pi4 8Gb with Ubuntu 20.04.2 Server LTS.
Project runs in docker image based on `arm64v8/node:14.15.4-buster`.
Command `prisma generate` running okay.
Project can't start with the same error as `prisma --version` shows error:
```
prisma --version
Error: Could not find introspection-engine binary. Searched in /root/node_modules/prisma/introspection-engine-linux-arm-openssl-1.1.x and /root/node_modules/introspection-engine-linux-arm-openssl-1.1.x
```

## How to reproduce
```
docker run --rm -it arm64v8/node:14.15.4-buster /bin/bash
root@2682f203a74a:/# npm i -s prisma@2.16.0
+ prisma@2.16.0
added 2 packages from 1 contributor and audited 2 packages in 11.691s
found 0 vulnerabilities

root@2682f203a74a:/# npm i -s @prisma/client@2.16.0
warning The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
If you have a Prisma schema file in a custom path, you will need to run
`prisma generate --schema=./path/to/your/schema.prisma` to generate Prisma Client.
If you do not have a Prisma schema file yet, you can ignore this message.

+ @prisma/client@2.16.0
added 2 packages from 1 contributor and audited 4 packages in 7.799s
found 0 vulnerabilities

root@2682f203a74a:/# export PATH="/node_modules/.bin:./node_modules/.bin:${PATH}"
root@2682f203a74a:/# prisma --version
Error: Could not find introspection-engine binary. Searched in /node_modules/prisma/introspection-engine-linux-arm-openssl-1.1.x and /node_modules/introspection-engine-linux-arm-openssl-1.1.x
root@2682f203a74a:/#

```

## Expected behavior

`prisma version`

## Prisma information

Project runs in docker image based on `arm64v8/node:14.15.4-buster`
Prisma installed as
```
npm i -s prisma@2.16.0
npm i -s @prisma/client@2.16.0
```

Prisma schema is using `native` 
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
  output        = "./src/generated/db-client"
}
```

## Environment & setup

```
uname -a
Linux ubuntu 5.4.0-1028-raspi #31-Ubuntu SMP PREEMPT Wed Jan 20 11:30:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

docker version
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:47 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:32:03 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

Docker image `arm64v8/node:14.15.4-buster` uses
```
docker run --rm -it arm64v8/node:14.15.4-buster /bin/bash
root@2682f203a74a:/# node -v
v14.15.4
root@2682f203a74a:/# npm -v
6.14.10

```

**Comment by pantharshit00** [comment]
Hey @sfoxdev 

Can you please share output of `npx prisma -v`?

**Comment by sfoxdev** [comment]
Hey @pantharshit00 

```
docker run --rm -it arm64v8/node:14.15.4-buster /bin/bash
root@a8aa75927295:/# npx prisma -v
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/8/lib/node_modules/prisma/scripts/preinstall-entry.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prisma@2.16.1 preinstall: `node scripts/preinstall-entry.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prisma@2.16.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-09T13_53_08_406Z-debug.log
Install for [ 'prisma@latest' ] failed with code 1
root@a8aa75927295:/#

root@a8aa75927295:/# cat /root/.npm/_logs/2021-02-09T13_53_08_406Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'prisma@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/root/.npm/_npx/8',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose npm-session 604362b294ce88f0
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/prisma 533ms
8 http fetch GET 200 https://registry.npmjs.org/prisma/-/prisma-2.16.1.tgz 470ms
9 silly pacote tag manifest for prisma@latest fetched in 1086ms
10 timing stage:loadCurrentTree Completed in 1113ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 3ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule prisma@2.16.1 checking installable status
18 http fetch GET 200 https://registry.npmjs.org/@prisma%2fengines 225ms
19 http fetch GET 200 https://registry.npmjs.org/@prisma/engines/-/engines-2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03.tgz 206ms
20 silly pacote version manifest for @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 fetched in 455ms
21 silly resolveWithNewModule @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 checking installable status
22 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 471ms
23 timing stage:loadIdealTree Completed in 479ms
24 silly currentTree lib
25 silly idealTree lib
25 silly idealTree `-- prisma@2.16.1
25 silly idealTree   `-- @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
26 silly install generateActionsToTake
27 timing stage:generateActionsToTake Completed in 32ms
28 silly diffTrees action count 2
29 silly diffTrees add @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
30 silly diffTrees add prisma@2.16.1
31 silly decomposeActions action count 16
32 silly decomposeActions fetch @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
33 silly decomposeActions extract @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
34 silly decomposeActions preinstall @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
35 silly decomposeActions build @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
36 silly decomposeActions install @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
37 silly decomposeActions postinstall @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
38 silly decomposeActions finalize @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
39 silly decomposeActions refresh-package-json @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
40 silly decomposeActions fetch prisma@2.16.1
41 silly decomposeActions extract prisma@2.16.1
42 silly decomposeActions preinstall prisma@2.16.1
43 silly decomposeActions build prisma@2.16.1
44 silly decomposeActions install prisma@2.16.1
45 silly decomposeActions postinstall prisma@2.16.1
46 silly decomposeActions finalize prisma@2.16.1
47 silly decomposeActions refresh-package-json prisma@2.16.1
48 silly install executeActions
49 silly doSerial global-install 16
50 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
51 verbose lock using /root/.npm/_locks/staging-aa1ad98389d426fc.lock for /root/.npm/_npx/8/lib/node_modules/.staging
52 silly doParallel extract 2
53 silly extract @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
54 silly extract prisma@2.16.1
55 silly tarball trying prisma@latest by hash: sha512-TniTihl4xwWY7Hy+1UUpZ6jxHyriRDUW4i7TChZNBZM88IG8kvR5cSX+/JY/lzWGMUR4ZDBzoIuNcdPx/7eWag==
56 silly tarball trying @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 by hash: sha512-GZ1huP5KC6TPf9u8pYGFklUkGVTKFel6k4wL4iMr8AQ6MeSV4GDJX3lEtEJLb0ayj6je/hDEyQG9iMp/BysFYg==
57 silly extract @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03 extracted to /root/.npm/_npx/8/lib/node_modules/.staging/@prisma/engines-6787b1af (142ms)
58 silly extract prisma@latest extracted to /root/.npm/_npx/8/lib/node_modules/.staging/prisma-c36d3d85 (386ms)
59 timing action:extract Completed in 391ms
60 silly doReverseSerial unbuild 16
61 silly doSerial remove 16
62 silly doSerial move 16
63 silly doSerial finalize 16
64 silly finalize /root/.npm/_npx/8/lib/node_modules/prisma/node_modules/@prisma/engines
65 silly finalize /root/.npm/_npx/8/lib/node_modules/prisma
66 timing action:finalize Completed in 19ms
67 silly doParallel refresh-package-json 2
68 silly refresh-package-json /root/.npm/_npx/8/lib/node_modules/prisma/node_modules/@prisma/engines
69 silly refresh-package-json /root/.npm/_npx/8/lib/node_modules/prisma
70 timing action:refresh-package-json Completed in 34ms
71 silly doParallel preinstall 2
72 silly preinstall @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
73 info lifecycle @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03~preinstall: @prisma/engines@2.16.1-1.8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03
74 silly preinstall prisma@2.16.1
75 info lifecycle prisma@2.16.1~preinstall: prisma@2.16.1
76 verbose lifecycle prisma@2.16.1~preinstall: unsafe-perm in lifecycle false
77 verbose lifecycle prisma@2.16.1~preinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/.npm/_npx/8/lib/node_modules/prisma/node_modules/.bin:/root/.npm/_npx/8/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
78 verbose lifecycle prisma@2.16.1~preinstall: CWD: /root/.npm/_npx/8/lib/node_modules/prisma
79 silly lifecycle prisma@2.16.1~preinstall: Args: [ '-c', 'node scripts/preinstall-entry.js' ]
80 silly lifecycle prisma@2.16.1~preinstall: Returned: code: 1  signal: null
81 info lifecycle prisma@2.16.1~preinstall: Failed to exec preinstall script
82 timing action:preinstall Completed in 237ms
83 verbose unlock done using /root/.npm/_locks/staging-aa1ad98389d426fc.lock for /root/.npm/_npx/8/lib/node_modules/.staging
84 timing stage:rollbackFailedOptional Completed in 50ms
85 timing stage:runTopLevelLifecycles Completed in 2374ms
86 verbose stack Error: prisma@2.16.1 preinstall: `node scripts/preinstall-entry.js`
86 verbose stack Exit status 1
86 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
86 verbose stack     at EventEmitter.emit (events.js:315:20)
86 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
86 verbose stack     at ChildProcess.emit (events.js:315:20)
86 verbose stack     at maybeClose (internal/child_process.js:1048:16)
86 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
87 verbose pkgid prisma@2.16.1
88 verbose cwd /
89 verbose Linux 5.4.0-1028-raspi
90 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "install" "prisma@latest" "--global" "--prefix" "/root/.npm/_npx/8" "--loglevel" "error" "--json"
91 verbose node v14.15.4
92 verbose npm  v6.14.10
93 error code ELIFECYCLE
94 error errno 1
95 error prisma@2.16.1 preinstall: `node scripts/preinstall-entry.js`
95 error Exit status 1
96 error Failed at the prisma@2.16.1 preinstall script.
96 error This is probably not a problem with npm. There is likely additional logging output above.
97 verbose exit [ 1, true ]
root@a8aa75927295:/#

```

**Comment by ACAVJW4H** [comment]
I am having the same problem on jetson board. Gonna try building them with https://github.com/jcmcneal/prisma-arm64

**Comment by sfoxdev** [comment]
Hey @pantharshit00 any info/update when Prisma will have native support for ARMv8 (Raspberry Pi4)? 
@ACAVJW4H thank you for advice to use https://github.com/jcmcneal/prisma-arm64 but I want to use native binaries.

**Comment by tomhoule** [comment]
Possibly related: https://github.com/prisma/prisma/issues/5497

**Comment by pantharshit00** [comment]
@tomhoule Unrelated to #5497 since @sfoxdev is using 64bit OS.

We do shit arm64 binaries now. Problem here is inside docker in pi we are downloading our x86 based debian binaries for ubuntu which doesn't work. Can you please try this generator block:
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native","linux-arm-openssl-1.1.x"]
  output        = "./src/generated/db-client"
}
```

This will ensure we download the arm64 bins regardless of detection problem because of docker interop.

**Comment by sfoxdev** [comment]
@pantharshit00 Made test with configuration
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native","linux-arm-openssl-1.1.x"]
  output        = "./src/generated/db-client"
}
```
got the same error
```
root@93dc0ffaa336:~# prisma version
Error: Could not find introspection-engine binary. Searched in /root/node_modules/prisma/introspection-engine-linux-arm-openssl-1.1.x and /root/node_modules/introspection-engine-linux-arm-openssl-1.1.x
root@93dc0ffaa336:~# find / -name linux-arm-openssl-1.1.x
/root/.cache/prisma/master/854c8ba7f0dce66f115af36af24e66989a8c02a1/linux-arm-openssl-1.1.x
root@93dc0ffaa336:~#
```

**Comment by Tomyail** [comment]
> @tomhoule Unrelated to #5497 since @sfoxdev is using 64bit OS.
> 
> We do ship arm64 binaries now. Problem here is inside docker in pi we are downloading our x86 based debian binaries for ubuntu which doesn't work. Can you please try this generator block:
> 
> ```
> generator client {
>   provider      = "prisma-client-js"
>   binaryTargets = ["native","linux-arm-openssl-1.1.x"]
>   output        = "./src/generated/db-client"
> }
> ```
> 
> This will ensure we download the arm64 bins regardless of detection problem because of docker interop.

I found `node_modules/@prisma/engines/download/index.js` download debian binaries on raspberry because [here](https://github.com/prisma/prisma/blob/9aed14fd21dfa46f4dcf3803f8b01a85419e3f10/src/packages/get-platform/src/getPlatform.ts#L81) `parseDistro` parsed os as debian not arm。 and  here is the /etc/os-release output
 ```
➜  engines git:(master) ✗ pwd
/home/pi/vault-1/node_modules/@prisma/engines
➜  engines git:(master) ✗ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
➜  engines git:(master) ✗ uname -a    
Linux raspberrypi 5.10.11-v8+ #1399 SMP PREEMPT Thu Jan 28 12:14:03 GMT 2021 aarch64 GNU/Linux
```

**Comment by pantharshit00** [comment]
That makes sense, I am marking this as confirmed and we should improve that script.

**Comment by simnalamburt** [comment]
Is there any workaround for this issue? Like, can I fetch the ARM build of prisma engine in somewhere?

**Comment by sfoxdev** [comment]
Hey @pantharshit00 any update?

**Comment by pantharshit00** [comment]
@sfoxdev Unfortunately, no updates here. I will candidate this now.

**Comment by pantharshit00** [comment]
I made a repository which build the engines for Pi in the meantime while it is not officially supported. You can check it out here: https://github.com/pantharshit00/prisma-rpi-builds

**Comment by matthewmueller** [comment]
Thanks Harshit!

Harshit provided the binaries in: https://github.com/pantharshit00/prisma-rpi-builds
There's some instructions on how to use it in the link's Readme.

You can learn more about bringing your own binary here: https://www.prisma.io/docs/concepts/components/prisma-engines#using-custom-engine-binaries

Closing since I don't see us officially supporting this binary for the foreseeable future, but we do encourage community-driven binaries!

**Comment by pantharshit00** [comment]
@matthewmueller This issue ain't about support but correct detection of OS inside of docker in raspberry pi. 

I think we need to still look into this one.

**Comment by jelitter** [comment]
Hello! Is there any update on this ? Or any reliable workaround I can follow ? 
Thanks.

**Comment by Jolg42** [comment]
Potentially related: https://github.com/prisma/prisma/issues/17284

**Comment by aqrln** [comment]
I can reproduce this with the reported Prisma version 2.16.0. However, this is not reproducible starting with Prisma 2.18.0 and in modern Prisma 4.x, so I'm going to go ahead and close this issue.

Generally Prisma on ARM64 is widely used nowadays (including during development of Prisma itself) at least because of Apple Silicon (but we also have users running on ARM in production on Ampere A1 and AWS Graviton) so we would definitely know if there still were any issues with platform detection there.
