### ISSUE TITLE
Error: [libs/datamodel/connectors/dml/src/model.rs:166:14] We assume an internally valid datamodel before mutating. 

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma#5613]
Command: `prisma introspect`
Version: `2.16.1`
Binary Version: `8b74ad57aaf2cc6c155f382a18a8e3ba95aceb03`
Report: https://prisma-errors.netlify.app/report/12968 
OS: `x64 darwin 20.2.0`

JS Stacktrace:
```
Error: [libs/datamodel/connectors/dml/src/model.rs:166:14] We assume an internally valid datamodel before mutating.
    at ChildProcess.<anonymous> (/Users/terokujala/projects/cuuma/rest/packages/rest-server/node_modules/prisma/build/index.js:4780:28)
    at ChildProcess.emit (events.js:310:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_handler::{{closure}}
   6: std::sys_common::backtrace::__rust_end_short_backtrace
   7: _rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: dml::datamodel::Datamodel::find_relation_field_mut
  11: sql_introspection_connector::re_introspection::enrich
  12: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  16: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  17: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  18: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  19: futures::task_impl::Spawn<T>::enter::{{closure}}
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: introspection_engine::main
  22: std::sys_common::backtrace::__rust_begin_short_backtrace
  23: std::rt::lang_start::{{closure}}
  24: std::rt::lang_start_internal
  25: std::rt::lang_start

```

**Comment by Jolg42** [comment]
Also reported in https://prisma-errors.netlify.app/report/12980

**Comment by tomhoule** [comment]
Same as https://github.com/prisma/prisma/issues/4610 — closing.
