### ISSUE TITLE
Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead.

### ISSUE THREAD

**Issue by pizzafox** [prisma/prisma#5762]
## Bug description

```js
/home/jonah/programming/prisma-bug-repro/node_modules/@prisma/client/runtime/index.js:78693
          throw new import_engine_core.PrismaClientUnknownRequestError(message, this.prisma._clientVersion);
                ^

PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]:
Invalid `prisma.beta.create()` invocation:


  Invalid response data: the query result was required, but an empty Object((Weak)) was returned instead.
    at cb (/home/jonah/programming/prisma-bug-repro/node_modules/@prisma/client/runtime/index.js:78693:17)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async main (/home/jonah/programming/prisma-bug-repro/index.js:7:3) {
  clientVersion: '2.17.0'
}
```

## How to reproduce

https://github.com/pizzafox/prisma-bug-5762
This repository will be around until the issue is closed.
Once I delete it you should use the zip file I've attached.
[prisma-bug-5762-main.zip](https://github.com/prisma/prisma/files/6017493/prisma-bug-5762-main.zip)

The bug is caused when the `DateTime` field is left blank.
Try passing `new Date()` as the value and seeing if anything notable happens.

## Expected behavior

No error should be thrown.

## Prisma information

See reproduction.

## Environment & setup

- OS: Ubuntu 20.04.2 LTS on Windows 10 x86_64
- Database: PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
- Prisma version:

```
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.353.0
```
- Node.js versions:

```js
{
  node: '15.8.0',
  v8: '8.6.395.17-node.23',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '88',
  nghttp2: '1.42.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1i',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}
```

**Comment by pantharshit00** [comment]
Thanks for the detailed reproduction @pizzafox 

Looks like we are not applying the default in this case. We should fix this. 

Tested with `2.18.0-dev.36`

**Comment by matthewmueller** [comment]
Next steps:

- Reproduce issue @dpetrick 
- Start improving errors (Pierre)
