### ISSUE TITLE
PANIC in query-engine\connectors\sql-query-connector\src\query_builder\write.rs:22:56called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by dimoff66** [prisma/prisma#5765]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v10.15.3           | 
| OS              | windows            |
| Prisma Client   | 2.17.0             |
| Query Engine    | query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223|
| Database        | undefined|

## Query
```
mutation {
  createOneVenue(data: {
    sailingId: "X"
    name: "X"
    timeslotsStep: 5
    sittingDurations: {
      create: [
        {
          guestsNumber: 5
          duration: 5
        },
        {
          guestsNumber: 5
          duration: 5
        },
        {
          guestsNumber: 5
          duration: 5
        }
      ]
    }
    sessions: {
      create: [
        {
          name: "X"
          timeStart: "X"
          timeEnd: "X"
        },
        {
          name: "X"
          timeStart: "X"
          timeEnd: "X"
        },
        {
          name: "X"
          timeStart: "X"
          timeEnd: "X"
        }
      ]
    }
  }) {
    id
    name
    timeslotsStep
    sailingId
  }
}
```

## Logs
```
nk (_stream_readable.js:284:12)
  prisma:engine     at readableAddChunk (_stream_readable.js:265:11)
  prisma:engine     at LineStream.Readable.push (_stream_readable.js:220:10)
  prisma:engine     at LineStream.Transform.push (_stream_transform.js:151:32)
  prisma:engine     at LineStream._pushBuffer (C:\OSPanel\domains\localhost\node server\nodejs-typescript-2021\reservations-ts-prisma-app\node_modules\@prisma\client\runtime\index.js:23722:19)  {"timestamp":"Feb 21 14:17:32.741","level":"ERROR","fields":{"message":"PANIC","reason":"called `Option::unwrap()` on a `None` value","file":"query-engine\\connectors\\sql-query-connector\\src\\query_builder\\write.rs","line":22,"column":56},"target":"query_engine","span":{"name":"execute_single_operation"},"spans":[{"name":"execute_single_operation"}]}  
  prisma:engine { error:
  prisma:engine    { Error: read ECONNRESET
  prisma:engine        at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } }  
  prisma:engine { error:
  prisma:engine    { Error: connect ECONNREFUSED 127.0.0.1:5166
  prisma:engine        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  prisma:engine      errno: 'ECONNREFUSED',
  prisma:engine      code: 'ECONNREFUSED',
  prisma:engine      syscall: 'connect',
  prisma:engine      address: '127.0.0.1',
  prisma:engine      port: 5166 } }  +2s
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd:
  prisma:engine    'C:\\OSPanel\\domains\\localhost\\node server\\nodejs-typescript-2021\\reservations-ts-prisma-app\\prisma' }  
  prisma:engine Search for Query Engine in C:\OSPanel\domains\localhost\node server\nodejs-typescript-2021\reservations-ts-prisma-app\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '5326' ] }  
  prisma:engine stdout  Starting a mysql pool with 5 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:5326  
  prisma:engine Search for Query Engine in C:\OSPanel\domains\localhost\node server\nodejs-typescript-2021\reservations-ts-prisma-app\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\connectors\sql-query-connector\src\query_builder\write.rs:22:56
called `Option::unwrap()` on a `None` value  
  prisma:engine TypeError: this.currentRequestPromise.cancel is not a function
  prisma:engine     at NodeEngine.handlePanic (C:\OSPanel\domains\localhost\node server\nodejs-typescript-2021\reservations-ts-prisma-app\node_modules\@prisma\client\runtime\index.js:26601:36)
  prisma:engine     at NodeEngine.setError (C:\OSPanel\domains\localhost\node server\nodejs-typescript-2021\reservations-ts-prisma-app\node_modules\@prisma\client\runtime\index.js:26547:16)
  prisma:engine     at LineStream.byline_1.default.on (C:\OSPanel\domains\localhost\node server\nodejs-typescript-2021\reservations-ts-prisma-app\node_modules\@prisma\client\runtime\index.js:26837:24)
  prisma:engine     at LineStream.emit (events.js:189:13)
  prisma:engine     at LineStream.EventEmitter.emit (domain.js:441:20)
  prisma:engine     at addChunk (_stream_readable.js:284:12)
  prisma:engine     at readableAddChunk (_stream_readable.js:265:11)
  prisma:engine     at LineStream.Readable.push (_stream_readable.js:220:10)
  prisma:engine     at LineStream.Transform.push (_stream_transform.js:151:32)
  prisma:engine     at LineStream._pushBuffer (C:\OSPanel\domains\localhost\node server\nodejs-typescript-2021\reservations-ts-prisma-app\node_modules\@prisma\client\runtime\index.js:23722:19)  {"timestamp":"Feb 21 14:17:35.405","level":"ERROR","fields":{"message":"PANIC","reason":"called `Option::unwrap()` on a `None` value","file":"query-engine\\connectors\\sql-query-connector\\src\\query_builder\\write.rs","line":22,"column":56},"target":"query_engine","span":{"name":"execute_single_operation"},"spans":[{"name":"execute_single_operation"}]}  
  prisma:engine { error:
  prisma:engine    { Error: read ECONNRESET
  prisma:engine        at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } }  
```

## Client Snippet
```ts
const prisma = new PrismaClient()

  const data =  
  {
    "sailingId": "36f3ca6e-e695-46c1-be3f-f2d17adb615d",
    "name": "Italian restaurant", 
    "timeslotsStep": 20,
    "sittingDurations": {
      "create": [
        { "guestsNumber": 2, "duration": 40 }, 
        { "guestsNumber": 4, "duration": 60 },
        { "guestsNumber": 6, "duration": 80 }
      ]
    },
    
    // ATTENTION PRISMA TEAM!!! If remove sessions from data everything works, only after "sessions" block adding it crashes
     // adding @relation("venue_sessions", fields: [venueId], references: [id]) to field venue in Session model solves issue
     // but anyway check it should not crash the app
    "sessions": {
      "create": [
        { "name": "breakfast", "timeStart": "07:00", "timeEnd": "11:00" }, 
        { "name": "lunch", "timeStart": "13:00", "timeEnd": "16:00" }, 
        { "name": "dinner", "timeStart": "19:00", "timeEnd": "23:00" }  
      ]
    }
  }
  
  const insertedData = await prisma.venue.create({ data })
}
```

## Schema
```prisma
model Sailing {
  id          String     @id @default(uuid())
  name        String
  timezone    String 
  dateStart   DateTime
  dateEnd     DateTime

  venues      Venue[]

  @@map("sailings")
}

model Venue {
  id            String     @id @default(uuid())
  name          String 
  timeslotsStep Int
  sailing       Sailing

  sittingDurations  SittingDuration[]
  sessions          Session[]
  layouts           Layout[]

  @@map("venues")
}

model SittingDuration {
  venue         Venue @relation("venue", fields: [venueId], references: [id])
  venueId       String
  guestsNumber  Int 
  duration      Int

  @@id([venueId, guestsNumber])
  @@map("sitting_durations")
}

model Session {
  id            Int @id @default(autoincrement())
  venue         Venue 
  venueId       String
  name          String 
  timeStart     String 
  timeEnd       String 

  @@unique([venueId, name])
  @@unique([venueId, timeStart])

  @@map("sessions")
}

model Layout {
  id            String @id @default(uuid())
  venue         Venue
  venueId       String
  name          String 

  @@unique([venueId, name])
  
  @@map("layouts")
}
```

**Comment by pantharshit00** [comment]
Related: https://github.com/prisma/prisma/issues/5168

The model you have shared is incomplete. Prisma generate throws the following errors:
```
Error: Schema parsing
error: Error parsing attribute "@relation": The relation field `sailing` on Model `Venue` must specify the `fields` argument in the @relation attribute. You can run `prisma format` to fix this automatically.
  -->  schema.prisma:26
   |
25 |   timeslotsStep Int
26 |   sailing       Sailing
27 |
   |
error: Error parsing attribute "@relation": The relation field `sailing` on Model `Venue` must specify the `references` argument in the @relation attribute.
  -->  schema.prisma:26
   |
25 |   timeslotsStep Int
26 |   sailing       Sailing
27 |
   |
error: Error validating field `sittingDurations` in model `Venue`: The relation field `sittingDurations` on Model `Venue` is missing an opposite relation field on the model `SittingDuration`. Either run `prisma format` or add it manually.
  -->  schema.prisma:28
   |
27 |
28 |   sittingDurations  SittingDuration[]
29 |   sessions          Session[]
   |
error: Error validating field `venue` in model `SittingDuration`: The relation field `venue` on Model `SittingDuration` is missing an opposite relation field on the model `Venue`. Either run `prisma format` or add it manually.
  -->  schema.prisma:36
   |
35 | model SittingDuration {
36 |   venue         Venue @relation("venue", fields: [venueId], references: [id])
37 |   venueId       String
   |
error: Error parsing attribute "@relation": The relation field `venue` on Model `Session` must specify the `fields` argument in the @relation attribute. You can run `prisma format` to fix this automatically.
  -->  schema.prisma:47
   |
46 |   id            Int @id @default(autoincrement())
47 |   venue         Venue
48 |   venueId       String
   |
error: Error parsing attribute "@relation": The relation field `venue` on Model `Session` must specify the `references` argument in the @relation attribute.
  -->  schema.prisma:47
   |
46 |   id            Int @id @default(autoincrement())
47 |   venue         Venue
48 |   venueId       String
   |
error: Error parsing attribute "@relation": The relation field `venue` on Model `Layout` must specify the `fields` argument in the @relation attribute. You can run `prisma format` to fix this automatically.
  -->  schema.prisma:61
   |
60 |   id            String @id @default(uuid())
61 |   venue         Venue
62 |   venueId       String
   |
error: Error parsing attribute "@relation": The relation field `venue` on Model `Layout` must specify the `references` argument in the @relation attribute.
  -->  schema.prisma:61
   |
60 |   id            String @id @default(uuid())
61 |   venue         Venue
62 |   venueId       String
   |

Validation Error Count: 8
```

Please fix this warnings.

**Comment by dimoff66** [comment]
> Related: #5168
> 
> Please fix this warnings.

I'm sorry, i don't know why you get these warnings... In my app it works perfectly well

**Comment by pantharshit00** [comment]
Can you make sure you pasted it right?

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
