### ISSUE TITLE
MySQL migration creation bug

### ISSUE THREAD

**Issue by ericluwj** [prisma/prisma#5802]
## Bug description

Error occurred while doing initial MySQL database migration creation:

```
  prisma:tryLoadEnv Environment variables loaded from /Users/user/Projects/project-v3/.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "project" at "localhost:3306"

  prisma:migrateEngine:rpc starting migration engine with binary: /Users/user/Projects/project-v3/node_modules/@prisma/engines/migration-engine-darwin +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"/Users/user/Projects/project-v3/prisma/migrations"}} +4ms
  prisma:migrateEngine:stderr Feb 23 21:49:07.108  INFO migration_engine: Starting migration engine RPC server git_hash="3c463ebd78b1d21d8fdacdd27899e280cf686223" +0ms
  prisma:migrateEngine:stderr Feb 23 21:49:07.121  INFO quaint::single: Starting a mysql connection. +13ms
  prisma:migrateEngine:stderr Feb 23 21:49:07.126  INFO DevDiagnostic:calculate_drift:sql_schema_from_migration_history: quaint::single: Starting a mysql connection. +5ms
  prisma:migrateEngine:stderr Feb 23 21:49:07.227  INFO DevDiagnostic:validate_migrations:sql_schema_from_migration_history: quaint::single: Starting a mysql connection. +101ms
  prisma:migrateEngine:rpc {
  prisma:migrateEngine:rpc   jsonrpc: '2.0',
  prisma:migrateEngine:rpc   error: {
  prisma:migrateEngine:rpc     code: 4466,
  prisma:migrateEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:migrateEngine:rpc     data: {
  prisma:migrateEngine:rpc       is_panic: false,
  prisma:migrateEngine:rpc       message: 'Migration `20210223133504_` failed to apply cleanly to a temporary database. \n' +
  prisma:migrateEngine:rpc         'Error:\n' +
  prisma:migrateEngine:rpc         "Database error: Error querying the database: Server error: `ERROR 42000 (1067): Invalid default value for 'created_at''\n" +
  prisma:migrateEngine:rpc         '   0: sql_migration_connector::flavour::mysql::sql_schema_from_migration_history\n' +
  prisma:migrateEngine:rpc         '             at migration-engine/connectors/sql-migration-connector/src/flavour/mysql.rs:275\n' +
  prisma:migrateEngine:rpc         '   1: sql_migration_connector::sql_database_migration_inferrer::validate_migrations\n' +
  prisma:migrateEngine:rpc         '             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:70\n' +
  prisma:migrateEngine:rpc         '   2: migration_core::api::DevDiagnostic\n' +
  prisma:migrateEngine:rpc         '             at migration-engine/core/src/api.rs:79',
  prisma:migrateEngine:rpc       meta: [Object],
  prisma:migrateEngine:rpc       error_code: 'P3006'
  prisma:migrateEngine:rpc     }
  prisma:migrateEngine:rpc   },
  prisma:migrateEngine:rpc   id: 1
  prisma:migrateEngine:rpc } +128ms
Error: Error: P3006

Migration `20210223133504_` failed to apply cleanly to a temporary database.
Error:
Database error: Error querying the database: Server error: `ERROR 42000 (1067): Invalid default value for 'created_at''
   0: sql_migration_connector::flavour::mysql::sql_schema_from_migration_history
             at migration-engine/connectors/sql-migration-connector/src/flavour/mysql.rs:275
   1: sql_migration_connector::sql_database_migration_inferrer::validate_migrations
             at migration-engine/connectors/sql-migration-connector/src/sql_database_migration_inferrer.rs:70
   2: migration_core::api::DevDiagnostic
             at migration-engine/core/src/api.rs:79

    at Object.<anonymous> (/Users/user/Projects/project-v3/node_modules/prisma/build/index.js:54905:26)
    at MigrateEngine.handleResponse (/Users/user/Projects/project-v3/node_modules/prisma/build/index.js:54780:38)
    at LineStream.<anonymous> (/Users/user/Projects/project-v3/node_modules/prisma/build/index.js:54865:18)
    at LineStream.emit (events.js:314:20)
    at LineStream.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at LineStream.Readable.push (_stream_readable.js:213:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._pushBuffer (/Users/user/Projects/project-v3/node_modules/prisma/build/index.js:54617:19)
```

## How to reproduce

Run `DEBUG="*" ./node_modules/.bin/prisma migrate dev --preview-feature`.

## Expected behavior

Initial MySQL database migration creation should be successful.

## Prisma information

schema.prisma:

```
model Address {
  id              Int       @id @default(autoincrement())
  created_at      DateTime  @default(now()) @db.Timestamp(0)
  created_by      Int?
  updated_at      DateTime? @default(now()) @db.Timestamp(0)
  updated_by      Int?
}
```

Sample of generated migration SQL:

```
-- CreateTable
CREATE TABLE `address` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_by` INTEGER,
    `updated_at` TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(3),
    `updated_by` INTEGER,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

Generated SQL syntax for `created_at` and `updated_at` fields is invalid.

More information about correct MySQL syntax can be found here: https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html.

`DEFAULT CURRENT_TIMESTAMP(3)` should be `DEFAULT CURRENT_TIMESTAMP` or `DEFAULT CURRENT_TIMESTAMP(0)`.

## Environment & setup

- OS: Mac OS 10.15.7
- Database: MySQL 5.7.32
- Node.js version: 12.20.2
- Prisma version: 2.17.0

**Comment by tomhoule** [comment]
Hi! It does look like a bug indeed, scheduled some time to fix this.

**Comment by tomhoule** [comment]
PR is open here: https://github.com/prisma/prisma-engines/pull/1681 — should be merged in the next few days, and the fix will land in `prisma@dev`.

**Comment by ipamer** [comment]
Hi, 

I've run into the same problem, I have the schema like this:

```
model xx {
  id          Int       @id @default(autoincrement()) @db.UnsignedInt
  xx String    @db.VarChar(255)
  xx DateTime  @db.Timestamp(0)
  xx String    @db.VarChar(1000)
  xx String    @unique @db.VarChar(250)
  xx DateTime  @db.Timestamp(0) @default(now())

  @@map(name: "xx")
  @@index([xx, xx])
}

model yy {
  id          Int       @id @default(autoincrement()) @db.UnsignedInt
  yy          String    @db.VarChar(255)
  yy          DateTime  @db.Timestamp(0)
  problem     DateTime  @db.Timestamp(0)
  yy          Int

  @@map(name: "yy")
}
```

Both models have 2x DateTime, but in the 1. one there is a default value.
When I run the migration (dev) the 1. model creates the table, but the 2. does not - throws an error:
```
Database error code: 1067

Database error:
Invalid default value for 'problem'
```

So, after adding `@default(now())` to the `problem` field, it has passed.
But as you can see there is no default value for the other fields, and they pass.

Environment:
- prisma: 2.26.0
- mysql: 5.7
- node: v14.17.0

**Comment by pantharshit00** [comment]
@ipamer Open a new issue for this, we will have a look into this separately.

**Comment by janpio** [comment]
Happy to look at the issue you will create for this, with full information so we can reproduce, debug and hopefully fix what you are experiencing. Thanks.

**Comment by AhmerAftabPatel** [comment]
Did anyone know work around for this? I am still facing this issue.

**Comment by janpio** [comment]
Open a new issue please and fill the full issue template so we have the necessary data. Thanks.
