### ISSUE TITLE
Prisma Query Engine crash using findMany with many-to-many relations

### ISSUE THREAD

**Issue by JunquerGJ** [prisma/prisma#5825]
@@Hi Prisma Team! My Prisma Client just crashed. 

It's weird because I am doing the same request with assets and characteristics and it is working fine
This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v15.5.1            | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.15.0             |
| Query Engine    | query-engine e51dc3b5a9ee790a07104bec1c9477d51740fe54|
| Database        | undefined|

[schema.txt](https://github.com/prisma/prisma/files/6039045/schema.txt)

## Query
```
query {
  findManyServer {
    id
    hostname
    assets {
      id
      areaId
      name
      alias
      confidentiality
      authorization
      integrity
      availability
      trazability
      accessLogs
      activityLogs
      status
      statusDate
      repository
      risk
      documentation
      description
      assetType
    }
    ip {
      id
      networkId
      ip
    }
    idss {
      id
      name
      description
      denyList
    }
    characteristics {
      name
    }
  }
}
```

## Logs
```
,
  after: undefined,
  offset: undefined
})
prisma-client Generated request:
prisma-client query {
  findManyContact {
    id
    name
    tlf
    email
  }
}

engine stdout  Unknown error
engine stdout  Fetched a connection from the pool
engine stdout  Unknown error
engine stdout  Unknown error
engine stdout  Unknown error
engine stdout  PANIC in query-engine/core/src/interpreter/query_interpreters/nested_read.rs:78:56
1
engine TypeError: Cannot read property 'message' of undefined
    at EventEmitter.<anonymous> (/Backend_Prisma/node_modules/@prisma/client/runtime/index.js:77688:31)
    at EventEmitter.emit (node:events:388:22)
    at EventEmitter.emit (node:domain:470:12)
    at NodeEngine.setError (/Backend_Prisma/node_modules/@prisma/client/runtime/index.js:26460:25)
    at LineStream.<anonymous> (/Backend_Prisma/node_modules/@prisma/client/runtime/index.js:26760:24)
    at LineStream.emit (node:events:376:20)
    at LineStream.EventEmitter.emit (node:domain:470:12)
    at addChunk (node:internal/streams/readable:311:12)
    at readableAddChunk (node:internal/streams/readable:286:9)
    at LineStream.Readable.push (node:internal/streams/readable:225:10)  {"timestamp":"Feb 24 21:42:14.197","level":"ERROR","fields":{"message":"PANIC","reason":"1","file":"query-engine/core/src/interpreter/query_interpreters/nested_read.rs","line":78,"column":56},"target":"query_engine"}
engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/Backend_Prisma/node_modules/@prisma/client/runtime/index.js:24857:25)
      at Socket.emit (node:events:388:22)
      at Socket.EventEmitter.emit (node:domain:470:12)
      at endReadableNT (node:internal/streams/readable:1305:12)
      at processTicksAndRejections (node:internal/process/task_queues:80:21) {
    code: 'UND_ERR_SOCKET'
  }
}
engine There is a child that still runs and we want to start again
engine { cwd: '/Backend_Prisma/prisma' }
engine Search for Query Engine in /Backend_Prisma/node_modules/.prisma/client
plusX Execution permissions of /Backend_Prisma/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
engine { flags: [ '--enable-raw-queries' ] }
engine port: 33557
engine stdout  Starting a postgresql pool with 5 connections.
engine stdout  Fetched a connection fr

**Comment by pantharshit00** [comment]
@JunquerGJ 

I think this is fixed in the latest version. Please try again with the latest version.

**Comment by JunquerGJ** [comment]
Indeed it seems to be solved! Let me do some more tests to confirm it.

Thanks!
