### ISSUE TITLE
TypeError when using `npx prisma generate` with custom engine binaries

### ISSUE THREAD

**Issue by kylegentle** [prisma/prisma#5827]
## Bug description

`npx prisma generate` fails with `TypeError: Cannot read property 'filter' of undefined`

## How to reproduce
Repro on CentOS 8:
1. Download starter project from  [Quickstart with Typescript](https://www.prisma.io/docs/getting-started/quickstart-typescript).
```
curl -L https://pris.ly/quickstart | tar -xz --strip=2 quickstart-master/typescript/starter
```
2. Download and extract binaries:
```
mkdir vendor-bins && cd vendor-bins \
  && wget https://binaries.prisma.sh/2.1.x/latest/debian-openssl-1.1.x/introspection-engine.gz \
    https://binaries.prisma.sh/2.1.x/latest/rhel-openssl-1.1.x/migration-engine.gz \
    https://binaries.prisma.sh/2.1.x/latest/rhel-openssl-1.1.x/prisma-fmt.gz \
    https://binaries.prisma.sh/2.1.x/latest/rhel-openssl-1.1.x/query-engine.gz \
  && gunzip *.gz \
  && chmod +x ./* \
  && cd ..
```
3. Set environment variables 
```
export PRISMA_MIGRATION_ENGINE_BINARY="$PWD/vendor-bins/migration-engine" \
  && export PRISMA_QUERY_ENGINE_BINARY="$PWD/vendor-bins/query-engine" \
  && export PRISMA_INTROSPECTION_ENGINE_BINARY="$PWD/vendor-bins/introspection-engine" \
  && export PRISMA_FMT_BINARY="$PWD/vendor-bins/prisma-fmt"
```
4. Install project
```
npm install
```
5. Attempt to generate the client
```
$ DEBUG="*" npx prisma generate
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables loaded from ./prisma/.env +2ms
Environment variables loaded from prisma/.env
  download Using env var PRISMA_QUERY_ENGINE_BINARY for binary query-engine, which points to /home/kyle/starter/vendor-bins/query-engine +0ms
  download Using env var PRISMA_MIGRATION_ENGINE_BINARY for binary migration-engine, which points to /home/kyle/starter/vendor-bins/migration-engine +1ms
  download Using env var PRISMA_INTROSPECTION_ENGINE_BINARY for binary introspection-engine, which points to /home/kyle/starter/vendor-bins/introspection-engine +0ms
  download Using env var PRISMA_FMT_BINARY for binary prisma-fmt, which points to /home/kyle/starter/vendor-bins/prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
  prisma:download Using env var PRISMA_QUERY_ENGINE_BINARY for binary query-engine, which points to /home/kyle/starter/vendor-bins/query-engine +0ms
{ prismaClientDir: '/home/kyle/starter/node_modules/@prisma/client' }
  prisma:download Using env var PRISMA_QUERY_ENGINE_BINARY for binary query-engine, which points to /home/kyle/starter/vendor-bins/query-engine +582ms
__dirname /home/kyle/starter/node_modules/@prisma/client/generator-build
/home/kyle/starter/node_modules/@prisma/client/generator-build
Error: Error: 
TypeError: Cannot read property 'filter' of undefined
    at getMappings (/home/kyle/starter/node_modules/@prisma/client/generator-build/index.js:75843:52)
    at externalToInternalDmmf (/home/kyle/starter/node_modules/@prisma/client/generator-build/index.js:75839:15)
    at getPrismaClientDMMF (/home/kyle/starter/node_modules/@prisma/client/generator-build/index.js:75873:10)
    at buildClient (/home/kyle/starter/node_modules/@prisma/client/generator-build/index.js:73035:23)
    at Object.generateClient (/home/kyle/starter/node_modules/@prisma/client/generator-build/index.js:73097:47)
    at async LineStream.<anonymous> (/home/kyle/starter/node_modules/@prisma/client/generator-build/index.js:2802:26)


    at Generate2.parse (/home/kyle/starter/node_modules/prisma/build/index.js:63971:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/home/kyle/starter/node_modules/prisma/build/index.js:100809:18)
```
  
## Expected behavior
Client generation completes without error.

## Prisma information

Default setup from [Quickstart with Typescript](https://www.prisma.io/docs/getting-started/quickstart-typescript)

## Environment & setup

- OS: Linux x86_64 (Centos 8)
- Database: Likely db-independent, but verified with SQLite
- Node.js version: v14.15.4
- Prisma version:
```
$ DEBUG="*" npx prisma -v
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables loaded from ./prisma/.env +2ms
Environment variables loaded from prisma/.env
  download Using env var PRISMA_QUERY_ENGINE_BINARY for binary query-engine, which points to /home/kyle/starter/vendor-bins/query-engine +0ms
  download Using env var PRISMA_MIGRATION_ENGINE_BINARY for binary migration-engine, which points to /home/kyle/starter/vendor-bins/migration-engine +1ms
  download Using env var PRISMA_INTROSPECTION_ENGINE_BINARY for binary introspection-engine, which points to /home/kyle/starter/vendor-bins/introspection-engine +0ms
  download Using env var PRISMA_FMT_BINARY for binary prisma-fmt, which points to /home/kyle/starter/vendor-bins/prisma-fmt +0ms
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : rhel-openssl-1.1.x
Query Engine         : query-engine 363f5a521d6b06543e53d134652a0037a3096d41 (at vendor-bins/query-engine, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine     : migration-engine-cli 363f5a521d6b06543e53d134652a0037a3096d41 (at vendor-bins/migration-engine, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine : introspection-core 363f5a521d6b06543e53d134652a0037a3096d41 (at vendor-bins/introspection-engine, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary        : prisma-fmt 363f5a521d6b06543e53d134652a0037a3096d41 (at vendor-bins/prisma-fmt, resolved by PRISMA_FMT_BINARY)
Studio               : 0.353.0
  prisma:cli TypeError: Cannot read property 'length' of undefined
  prisma:cli     at /home/kyle/starter/node_modules/prisma/build/index.js:100832:77
  prisma:cli     at Array.find (<anonymous>)
  prisma:cli     at main (/home/kyle/starter/node_modules/prisma/build/index.js:100832:43) +0ms
```

**Comment by Jolg42** [comment]
Looks like a duplicate of https://github.com/prisma/prisma/issues/5813

**Comment by kylegentle** [comment]
Thanks @Jolg42, I agree it seems to be the same issue. I actually first ran into this on NixOS, but given that NixOS is not a high priority for Prisma I wanted to provide a simple repro on CentOS. Feel free to merge this and #5813 however works best for you

**Comment by williamluke4** [comment]
Hey @kylegentle , Could try [this repo](https://github.com/williamluke4/prisma-issues-5827) out and post the output here

**Comment by dustinlacewell** [comment]
Just for good measure ;)

```
nix-shell -p nodejs-14_x yarn                                           ~/src/sima/prisma-issues-5827

[nix-shell:~/src/sima/prisma-issues-5827]$ yarn install
yarn install v1.22.10
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
$ bash ./scripts/download.sh && bash ./scripts/setup-env.sh && npx prisma version
========================= Downloading Custom Binaries =========================
--2021-03-04 15:38:16--  https://binaries.prisma.sh/master/854c8ba7f0dce66f115af36af24e66989a8c02a1/debian-openssl-1.1.x/introspection-engine.gz
Resolving binaries.prisma.sh (binaries.prisma.sh)... 54.239.174.68, 54.239.174.107, 54.239.174.54, ...
Connecting to binaries.prisma.sh (binaries.prisma.sh)|54.239.174.68|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6403320 (6.1M) [binary/octet-stream]
Saving to: ‘introspection-engine.gz’

introspection-engine.gz             100%[===================================================================>]   6.11M  8.12MB/s    in 0.8s    

2021-03-04 15:38:18 (8.12 MB/s) - ‘introspection-engine.gz’ saved [6403320/6403320]

--2021-03-04 15:38:18--  https://binaries.prisma.sh/master/854c8ba7f0dce66f115af36af24e66989a8c02a1/debian-openssl-1.1.x/migration-engine.gz
Reusing existing connection to binaries.prisma.sh:443.
HTTP request sent, awaiting response... 200 OK
Length: 7748855 (7.4M) [binary/octet-stream]
Saving to: ‘migration-engine.gz’

migration-engine.gz                 100%[===================================================================>]   7.39M  9.13MB/s    in 0.8s    

2021-03-04 15:38:19 (9.13 MB/s) - ‘migration-engine.gz’ saved [7748855/7748855]

--2021-03-04 15:38:19--  https://binaries.prisma.sh/master/854c8ba7f0dce66f115af36af24e66989a8c02a1/debian-openssl-1.1.x/prisma-fmt.gz
Reusing existing connection to binaries.prisma.sh:443.
HTTP request sent, awaiting response... 200 OK
Length: 2219811 (2.1M) [binary/octet-stream]
Saving to: ‘prisma-fmt.gz’

prisma-fmt.gz                       100%[===================================================================>]   2.12M  3.69MB/s    in 0.6s    

2021-03-04 15:38:20 (3.69 MB/s) - ‘prisma-fmt.gz’ saved [2219811/2219811]

--2021-03-04 15:38:20--  https://binaries.prisma.sh/master/854c8ba7f0dce66f115af36af24e66989a8c02a1/debian-openssl-1.1.x/query-engine.gz
Reusing existing connection to binaries.prisma.sh:443.
HTTP request sent, awaiting response... 200 OK
Length: 8987970 (8.6M) [binary/octet-stream]
Saving to: ‘query-engine.gz’

query-engine.gz                     100%[===================================================================>]   8.57M  9.62MB/s    in 0.9s    

2021-03-04 15:38:22 (9.62 MB/s) - ‘query-engine.gz’ saved [8987970/8987970]

FINISHED --2021-03-04 15:38:22--
Total wall clock time: 5.5s
Downloaded: 4 files, 24M in 3.0s (7.99 MB/s)
===============================================================================
============================= Env =============================
PRISMA_MIGRATION_ENGINE_BINARY: /home/ldlework/src/sima/prisma-issues-5827/vendor-bins/migration-engine
PRISMA_QUERY_ENGINE_BINARY: /home/ldlework/src/sima/prisma-issues-5827/vendor-bins/query-engine
PRISMA_INTROSPECTION_ENGINE_BINARY: /home/ldlework/src/sima/prisma-issues-5827/vendor-bins/introspection-engine
PRISMA_FMT_BINARY: /home/ldlework/src/sima/prisma-issues-5827/vendor-bins/prisma-fmt
===============================================================
Environment variables loaded from prisma/.env
Warning Precompiled binaries are not available for nixos.
> Downloading Prisma engines for linux-nixos [                    ] 0%Error: Not Found https://binaries.prisma.sh/all_commits/da6fafb57b24e0b61ca20960c64e2d41f9e8cff1/linux-nixos/query-engine.gz
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by kylegentle** [comment]
@dustinlacewell precompiled binaries aren't provided for NixOS, so that error is expected. Nix users have been working around this by using the Debian binaries, with Nix's `autoPatchelf` hook (see #3026), but that's not relevant to the issue at hand.

@williamluke4 thanks for the quick work on this, I'll test the repo after I'm finished working today.

**Comment by kylegentle** [comment]
Here's the output. Although the `.env` file is loaded at one point, it seems to still be using the engines in `node_modules`:

```
[kyle@cent prisma-issues-5827]$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> prisma@2.18.0 preinstall /home/kyle/prisma-issues-5827/node_modules/prisma
> node scripts/preinstall-entry.js


> prisma@2.18.0 install /home/kyle/prisma-issues-5827/node_modules/prisma
> node scripts/install-entry.js


> @prisma/engines@2.18.0-34.da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 postinstall /home/kyle/prisma-issues-5827/node_modules/@prisma/engines
> node download/index.js


> @prisma/client@2.18.0 postinstall /home/kyle/prisma-issues-5827/node_modules/@prisma/client
> node scripts/postinstall.js

Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (2.18.0) to ./node_modules/@prisma/client in 71ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

> script@ postinstall /home/kyle/prisma-issues-5827
> bash ./scripts/download.sh && bash ./scripts/setup-env.sh && npx prisma version

========================= Downloading Custom Binaries =========================
--2021-03-04 21:05:46--  https://binaries.prisma.sh/master/854c8ba7f0dce66f115af36af24e66989a8c02a1/rhel-openssl-1.1.x/introspection-engine.gz
Resolving binaries.prisma.sh (binaries.prisma.sh)... 13.33.81.128, 13.33.81.118, 13.33.81.13, ...
Connecting to binaries.prisma.sh (binaries.prisma.sh)|13.33.81.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6397720 (6.1M) [binary/octet-stream]
Saving to: ‘introspection-engine.gz’

introspection-engine.gz 100%[============================>]   6.10M  7.57MB/s    in 0.8s    

2021-03-04 21:05:47 (7.57 MB/s) - ‘introspection-engine.gz’ saved [6397720/6397720]

--2021-03-04 21:05:47--  https://binaries.prisma.sh/master/854c8ba7f0dce66f115af36af24e66989a8c02a1/rhel-openssl-1.1.x/migration-engine.gz
Reusing existing connection to binaries.prisma.sh:443.
HTTP request sent, awaiting response... 200 OK
Length: 7740629 (7.4M) [binary/octet-stream]
Saving to: ‘migration-engine.gz’

migration-engine.gz     100%[============================>]   7.38M  7.29MB/s    in 1.0s    

2021-03-04 21:05:49 (7.29 MB/s) - ‘migration-engine.gz’ saved [7740629/7740629]

--2021-03-04 21:05:49--  https://binaries.prisma.sh/master/854c8ba7f0dce66f115af36af24e66989a8c02a1/rhel-openssl-1.1.x/prisma-fmt.gz
Reusing existing connection to binaries.prisma.sh:443.
HTTP request sent, awaiting response... 200 OK
Length: 2219545 (2.1M) [binary/octet-stream]
Saving to: ‘prisma-fmt.gz’

prisma-fmt.gz           100%[============================>]   2.12M  4.12MB/s    in 0.5s    

2021-03-04 21:05:50 (4.12 MB/s) - ‘prisma-fmt.gz’ saved [2219545/2219545]

--2021-03-04 21:05:50--  https://binaries.prisma.sh/master/854c8ba7f0dce66f115af36af24e66989a8c02a1/rhel-openssl-1.1.x/query-engine.gz
Reusing existing connection to binaries.prisma.sh:443.
HTTP request sent, awaiting response... 200 OK
Length: 8984538 (8.6M) [binary/octet-stream]
Saving to: ‘query-engine.gz’

query-engine.gz         100%[============================>]   8.57M  7.88MB/s    in 1.1s    

2021-03-04 21:05:51 (7.88 MB/s) - ‘query-engine.gz’ saved [8984538/8984538]

FINISHED --2021-03-04 21:05:51--
Total wall clock time: 5.2s
Downloaded: 4 files, 24M in 3.4s (7.07 MB/s)
===============================================================================
============================= Env =============================
PRISMA_MIGRATION_ENGINE_BINARY: /home/kyle/prisma-issues-5827/vendor-bins/migration-engine
PRISMA_QUERY_ENGINE_BINARY: /home/kyle/prisma-issues-5827/vendor-bins/query-engine
PRISMA_INTROSPECTION_ENGINE_BINARY: /home/kyle/prisma-issues-5827/vendor-bins/introspection-engine
PRISMA_FMT_BINARY: /home/kyle/prisma-issues-5827/vendor-bins/prisma-fmt
===============================================================
Environment variables loaded from prisma/.env
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : rhel-openssl-1.1.x
Query Engine         : query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/query-engine-rhel-openssl-1.1.x)
Migration Engine     : migration-engine-cli da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/migration-engine-rhel-openssl-1.1.x)
Introspection Engine : introspection-core da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/introspection-engine-rhel-openssl-1.1.x)
Format Binary        : prisma-fmt da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/prisma-fmt-rhel-openssl-1.1.x)
Studio               : 0.356.0
npm WARN script@ No repository field.

added 14 packages from 45 contributors and audited 14 packages in 19.165s
found 0 vulnerabilities

[kyle@cent prisma-issues-5827]$ npm run dev

> script@ dev /home/kyle/prisma-issues-5827
> ts-node ./script.ts

{
  posts: {
    id: 3,
    title: 'Hello',
    content: null,
    published: false,
    authorId: null
  }
}
{ deleted: { count: 3 } }


   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │      New major version of npm available! 6.14.10 → 7.6.1      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v7.6.1   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯

```

**Comment by pantharshit00** [comment]
Ultimately to support nix automatically, we can do something like this: https://github.com/fannheyward/coc-rust-analyzer/blob/3cca16908eebfb3e04003efe72c0274b9402ac14/src/downloader.ts#L16

**Comment by williamluke4** [comment]
Awesome thanks @kylegentle, One last thing could you try adding the following :point_down: into `prisma/.env` and see if `npx prisma version` is still displaying the location of the engines as `node_modules/@prisma/engines`   
```
PRISMA_MIGRATION_ENGINE_BINARY="/home/kyle/prisma-issues-5827/vendor-bins/migration-engine"
PRISMA_QUERY_ENGINE_BINARY="/home/kyle/prisma-issues-5827/vendor-bins/query-engine"
PRISMA_INTROSPECTION_ENGINE_BINARY="/home/kyle/prisma-issues-5827/vendor-bins/introspection-engine"
PRISMA_FMT_BINARY="/home/kyle/prisma-issues-5827/vendor-bins/prisma-fmt"
```

**Comment by kylegentle** [comment]
@williamluke4 glad to help! Looks like the env file is read correctly: 
```
[kyle@cent prisma-issues-5827]$ npx prisma version
Environment variables loaded from prisma/.env
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : rhel-openssl-1.1.x
Query Engine         : query-engine 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at vendor-bins/query-engine, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine     : migration-engine-cli 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at vendor-bins/migration-engine, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine : introspection-core 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at vendor-bins/introspection-engine, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary        : prisma-fmt 854c8ba7f0dce66f115af36af24e66989a8c02a1 (at vendor-bins/prisma-fmt, resolved by PRISMA_FMT_BINARY)
Studio               : 0.356.0
```

```
[kyle@cent prisma-issues-5827]$ npm run dev

> script@ dev /home/kyle/prisma-issues-5827
> ts-node ./script.ts

{
  posts: {
    id: 6,
    title: 'Hello',
    content: null,
    published: false,
    authorId: null
  }
}
{ deleted: { count: 1 } }
```

**Comment by williamluke4** [comment]
@kylegentle Can you confirm that you are no longer receiving a `TypeError` when running `npx prisma generate`. If so please feel free to close this issue!

**Comment by williamluke4** [comment]
Hey @kylegentle, There was no fix needed. I think your issue was that you were downloading the incorrect binaries
