### ISSUE TITLE
Error: [libs/sql-schema-describer/src/getters.rs:21:14] called `Result::unwrap()` on an `Err` value: "Getting index_name from Resultrow ResultRow { columns: [\"index_name\", \"is_unique\", \"is_primary_key\", \"column_name\", \"seq_in_index\", \"table_name\"], values: [Text(None), Boolean(Some(false)), Boolean(Some(false)), Text(Some(\"ArchivePartition\")), Integer(Some(0)), Text(Some(\"ClientBetBackFactor\"))] } as String failed" 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#5858]
Command: `prisma introspect`
Version: `2.17.0`
Binary Version: `3c463ebd78b1d21d8fdacdd27899e280cf686223`
Report: https://prisma-errors.netlify.app/report/13026 
OS: `x64 linux 5.4.72-microsoft-standard-WSL2`

JS Stacktrace:
```
Error: [libs/sql-schema-describer/src/getters.rs:21:14] called `Result::unwrap()` on an `Err` value: "Getting index_name from Resultrow ResultRow { columns: [\"index_name\", \"is_unique\", \"is_primary_key\", \"column_name\", \"seq_in_index\", \"table_name\"], values: [Text(None), Boolean(Some(false)), Boolean(Some(false)), Text(Some(\"ArchivePartition\")), Integer(Some(0)), Text(Some(\"ClientBetBackFactor\"))] } as String failed"
    at ChildProcess.child.on (/home/kean/workspace/opstech-api/node_modules/prisma/build/index.js:39181:28)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

Rust Stacktrace:
```
   0: user_facing_errors::Error::new_in_panic_hook
   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   6: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   7: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   8: <quaint::connector::result_set::result_row::ResultRow as sql_schema_describer::getters::Getter>::get_expect_string
   9: <sql_schema_describer::mssql::SqlSchemaDescriber as sql_schema_describer::SqlSchemaDescriberBackend>::describe::__describe::{{closure}}::{{closure}}
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll
  15: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  16: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  17: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  18: futures::task_impl::Spawn<T>::enter::{{closure}}
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: introspection_engine::main
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: std::rt::lang_start::{{closure}}
  23: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panic.rs:396:14
      std::rt::lang_start_internal
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/rt.rs:51:25
  24: std::rt::lang_start
  25: __libc_start_main
  26: <unknown>

```

**Comment by tomhoule** [comment]
Not scheduled for this sprint because it's SQL server.

**Comment by tomhoule** [comment]
@pimeys assigning to you but low priority. What is happening is that sql_schema_describer is crashing on indexes that don't have a name (index_name is NULL). Not clear what we need to do with indexes that have no name.
