### ISSUE TITLE
Conversion failed when converting from a character string to uniqueidentifier.

### ISSUE THREAD

**Issue by Frozen666** [prisma/prisma#5869]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.15.1           | 
| OS              | windows            |
| Prisma Client   | 2.17.0             |
| Query Engine    | undefined|
| Database        | undefined|

## Query
```
query {
  findManytable(where: {
    Id: "X"
  }) {
    Id
    Value
  }
}
```

## Logs
```
nvironment variables not found at undefined  
  prisma:tryLoadEnv No Environment variables loaded  
  prisma:client { clientVersion: '2.17.0' }  
  prisma:engine { cwd: 'C:\\temp\\prisma-issue' }  
  prisma:engine Search for Query Engine in C:\temp\prisma-issue\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\temp\prisma-issue\node_modules\.prisma\client  
  prisma:engine {
  prisma:engine   flags: [
  prisma:engine     '--enable-experimental=microsoftSqlServer',
  prisma:engine     '--enable-raw-queries',
  prisma:engine     '--port',
  prisma:engine     '54855'
  prisma:engine   ]
  prisma:engine }  
  prisma:engine stdout  Starting a mssql pool with 33 connections.  
  prisma:engine stdout  TLS encryption is not enabled. All traffic including the login credentials are not encrypted.  
  prisma:engine stdout  Database change from 'd2i_demoscorecard_3' to 'master'  
  prisma:engine stdout  Changed database context to 'd2i_demoscorecard_3'.  
  prisma:engine stdout  SQL collation change from None to None  
  prisma:engine stdout  Microsoft SQL Server�� version 537395215  
  prisma:engine stdout  Packet size change from '4096' to '4096'  
  prisma:engine stdout  Started http server on http://127.0.0.1:54855  
  prisma:engine Search for Query Engine in C:\temp\prisma-issue\node_modules\.prisma\client  
  prisma:engine stdout  Conversion failed when converting from a character string to uniqueidentifier.  
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 8169, state: 2, class: 16, message: "Conversion failed when converting from a character string to uniqueidentifier.", server: "MINIBEAST", procedure: "", line: 1 }) })
  prisma:engine       at NodeEngine.graphQLToJSError (C:\temp\prisma-issue\node_modules\@prisma\client\runtime\index.js:27156:14)
  prisma:engine       at NodeEngine.request (C:\temp\prisma-issue\node_modules\@prisma\client\runtime\index.js:27052:24)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:93:5)
  prisma:engine       at async cb (C:\temp\prisma-issue\node_modules\@prisma\client\runtime\index.js:78659:26)
  prisma:engine       at async main (C:\temp\prisma-issue\index.js:5:16) {
  prisma:engine     clientVersion: '2.17.0'
  prisma:engine   }
  prisma:engine }  
  prisma:engine stdout  Conversion failed when converting from a character string to uniqueidentifier.  
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 8169, state: 2, class: 16, message: "Conversion failed when converting from a character string to uniqueidentifier.", server: "MINIBEAST", procedure: "", line: 1 }) })
  prisma:engine       at NodeEngine.graphQLToJSError (C:\temp\prisma-issue\node_modules\@prisma\client\runtime\index.js:27156:14)
  prisma:engine       at NodeEngine.request (C:\temp\prisma-issue\node_modules\@prisma\client\runtime\index.js:27052:24)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:93:5)
  prisma:engine       at async cb (C:\temp\prisma-issue\node_modules\@prisma\client\runtime\index.js:78659:26)
  prisma:engine       at async main (C:\temp\prisma-issue\index.js:5:16) {
  prisma:engine     clientVersion: '2.17.0'
  prisma:engine   }
  prisma:engine }  
  prisma:engine stdout  Conversion failed when converting from a character string to uniqueidentifier.  
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 8169, state: 2, class: 16, message: "Conversion failed when converting from a character string to uniqueidentifier.", server: "MINIBEAST", procedure: "", line: 1 }) })
  prisma:engine       at NodeEngine.graphQLToJSError (C:\temp\prisma-issue\node_modules\@prisma\client\runtime\index.js:27156:14)
  prisma:engine       at NodeEngine.request (C:\temp\prisma-issue\node_modules\@prisma\client\runtime\index.js:27052:24)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:93:5)
  prisma:engine       at async cb (C:\temp\prisma-issue\node_modules\@prisma\client\runtime\index.js:78659:26)
  prisma:engine       at async main (C:\temp\prisma-issue\index.js:5:16) {
  prisma:engine     clientVersion: '2.17.0'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
const { PrismaClient } = require("@prisma/client");
async function main() {
  const client = new PrismaClient();
  await client.$connect();
  const data = await client.table.findMany({
    where: { Id: "test" },
  });
  console.log(data);
  client.$disconnect();
}
main();
```

## Schema
```prisma
model table {
  Id     String  @id @default(dbgenerated("newid()")) @db.UniqueIdentifier
  Value  Int
}
```

Prisma cannot handle the SQL error when trying to match a string to UniqueIdentifier

**Comment by peteralbert** [comment]
Bit of background: This error comes when SQL Server is trying to convert a string to a UNIQUEIDENTIFIER - but the string does not represent a GUID, i.e. does match the pattern for UNIQUEIDENTIFIER. E.g. `SELECT CONVERT(UNIQUEIDENTIFIER, 'test')` will throw such an error (`Msg 8169, Conversion failed when converting from a character string to uniqueidentifier.`) - while `SELECT CONVERT(UNIQUEIDENTIFIER, '10CC2B57-CA5F-4B67-8CB2-429CA6E432AE')` works.

So when Prisma converts `where: { Id: "test" },` to SQL `WHERE [Id]=@P1`, the value is passed in as a string - which SQL Server cannot convert to a GUID and hence throws...

**Comment by pimeys** [comment]
Hey @peteralbert what would be the expected outcome here? The database correctly doesn't allow you to query with a faulty UUID, and we give a pretty straight-forward error message back.

We could maybe make it a known error with a proper code?

**Comment by pimeys** [comment]
Ok, I got it. Better error, no panic.

Here's what I have now for the test reproduction:
```
(node:19839) UnhandledPromiseRejectionWarning: Error:
Invalid `prisma.table.findMany()` invocation:


  Inconsistent column data: Conversion failed: Conversion failed when converting from a character string to uniqueidentifier.
    at cb (/home/pimeys/code/bug-reproductions/client-5869/node_modules/@prisma/client/runtime/index.js:34657:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at main (/home/pimeys/code/bug-reproductions/client-5869/main.ts:6:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19839) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19839) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by peteralbert** [comment]
@pimeys Thanks - the error message instead of the panic certainly helps already!

In our situation, this was part of a `where` clause. Instead of an error, returning an empty list and only show a warning in the logs would be even more convenient - but not sure that this is always the ideal solution...

**Comment by pimeys** [comment]
Even better would be to have a proper uuid type so already you'd get an error in the client if your value is not a real guid.

**Comment by peteralbert** [comment]
> Even better would be to have a proper uuid type so already you'd get an error in the client if your value is not a real guid.

That is what we ended up doing! We used https://github.com/NicolasDeveloper/guid-typescript to make sure, only valid GUIDs can be used.
