### ISSUE TITLE
next.js API routes failing on Netlify

### ISSUE THREAD

**Issue by NicolasBonet** [prisma/prisma#5870]
## Bug description

Hello guys, awesome work with the library! I have enjoyed working with Prisma a lot!

Regarding the error that I have, it's basically that Prisma is not getting along with Netlify, I'm creating a next.js app and I get this error whenever I try to use the next.js API routes: 

```
errorMessage: "Error: Query engine binary for current platform "rhel-openssl-1.0.x" could not be found.↵This probably happens, because you built Prisma Client on a different platform.↵(Prisma Client looked in "/query-engine-rhel-openssl-1.0.x")↵↵Searched Locations:↵↵  /.prisma/client↵  /opt/build/repo/node_modules/@prisma/client↵  /↵  /var/task/node_modules/.prisma/client↵  /var/task↵  /var/task/node_modules/.prisma/client↵↵You already added the platform "native" to the "generator" block↵in the "schema.prisma" file as described in https://pris.ly/d/client-generator,↵but something went wrong. That's suboptimal.↵↵Please create an issue at https://github.com/prisma/prisma-client-js/issues/new"
errorType: "Runtime.UnhandledPromiseRejection"
```

I already look for solutions in Google, but I wasn't able to find much besides adding: `target: "experimental-serverless-trace"` to my next.config which didn't help. I found an already closed bug: https://github.com/prisma/prisma/issues/4011 which mentions that 2.11 fixed this issue, but I'm working with `"@prisma/client": "^2.17.0",` and it's still happening, I don't know if it's related or if the error is different.

## How to reproduce

Create a next.js app, using yarn and installing prisma 2.17 and the following generator:

`generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["createMany"]
  binaryTargets   = ["native"]
}`

Implement any kind of API route and try to deploy to Netlify, deployment is going to be "successful", but when you try to use the actual API it's going to throw that error.

## Expected behavior

prisma to work fine on Netlify, it's working good in local.

## Prisma information

I'm using postgres with the generator mentioned above.

## Environment & setup

Only with Netlify, I'm using yarn and next.js 10.0.6 in case that matters! Additionaly, I added `npx prisma generate` to the deployment process to see if anything changed, but it's not working either, I do was able to see some errors by setting DEBUG to *:

```
8:55:09 AM: 2021-02-26T13:55:09.989Z prisma:tryLoadEnv Environment variables not found at null
8:55:09 AM: 2021-02-26T13:55:09.991Z prisma:tryLoadEnv Environment variables not found at undefined
8:55:09 AM: 2021-02-26T13:55:09.991Z prisma:tryLoadEnv No Environment variables loaded
8:55:10 AM: Prisma schema loaded from prisma/schema.prisma
8:55:10 AM: { prismaClientDir: '/opt/build/repo/node_modules/@prisma/client' }
8:55:10 AM: __dirname /opt/build/repo/node_modules/@prisma/client/generator-build
8:55:10 AM: /opt/build/repo/node_modules/@prisma/client/generator-build
8:55:10 AM: 2021-02-26T13:55:10.866Z prisma:GeneratorProcess 2021-02-26T13:55:10.866Z prisma:loadEnv Error: Cannot find module '/opt/build/repo/node_modules/.prisma/package.json'
8:55:10 AM: 2021-02-26T13:55:10.866Z prisma:GeneratorProcess Require stack:
8:55:10 AM: 2021-02-26T13:55:10.866Z prisma:GeneratorProcess - /opt/build/repo/node_modules/@prisma/client/generator-build/index.js
8:55:10 AM: 2021-02-26T13:55:10.867Z prisma:GeneratorProcess     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
8:55:10 AM: 2021-02-26T13:55:10.867Z prisma:GeneratorProcess     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
8:55:10 AM: 2021-02-26T13:55:10.867Z prisma:GeneratorProcess     at Module.require (internal/modules/cjs/loader.js:1026:19)
8:55:10 AM: 2021-02-26T13:55:10.867Z prisma:GeneratorProcess     at require (internal/modules/cjs/helpers.js:72:18)
8:55:10 AM: 2021-02-26T13:55:10.867Z prisma:GeneratorProcess     at /opt/build/repo/node_modules/@prisma/client/generator-build/index.js:72570:24
8:55:10 AM: 2021-02-26T13:55:10.867Z prisma:GeneratorProcess     at runMatcher (/opt/build/repo/node_modules/@prisma/client/generator-build/index.js:72287:25)
8:55:10 AM: 2021-02-26T13:55:10.867Z prisma:GeneratorProcess     at AsyncFunction.module2.exports.sync (/opt/build/repo/node_modules/@prisma/client/generator-build/index.js:72294:25)
8:55:10 AM: 2021-02-26T13:55:10.867Z prisma:GeneratorProcess     at getProjectRootEnvPath (/opt/build/repo/node_modules/@prisma/client/generator-build/index.js:72566:43)
8:55:10 AM: 2021-02-26T13:55:10.867Z prisma:GeneratorProcess     at Object.getEnvPaths2 (/opt/build/repo/node_modules/@prisma/client/generator-build/index.js:72545:31)
8:55:10 AM: 2021-02-26T13:55:10.867Z prisma:GeneratorProcess     at TSClient.toJS (/opt/build/repo/node_modules/@prisma/client/generator-build/index.js:78157:34)
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess 2021-02-26T13:55:10.866Z prisma:loadEnv Error: Cannot find module '/opt/build/repo/node_modules/package.json'
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess Require stack:
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess - /opt/build/repo/node_modules/@prisma/client/generator-build/index.js
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess     at Module.require (internal/modules/cjs/loader.js:1026:19)
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess     at require (internal/modules/cjs/helpers.js:72:18)
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess     at /opt/build/repo/node_modules/@prisma/client/generator-build/index.js:72570:24
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess     at runMatcher (/opt/build/repo/node_modules/@prisma/client/generator-build/index.js:72287:25)
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess     at AsyncFunction.module2.exports.sync (/opt/build/repo/node_modules/@prisma/client/generator-build/index.js:72294:25)
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess     at getProjectRootEnvPath (/opt/build/repo/node_modules/@prisma/client/generator-build/index.js:72566:43)
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess     at Object.getEnvPaths2 (/opt/build/repo/node_modules/@prisma/client/generator-build/index.js:72545:31)
8:55:10 AM: 2021-02-26T13:55:10.868Z prisma:GeneratorProcess     at TSClient.toJS (/opt/build/repo/node_modules/@prisma/client/generator-build/index.js:78157:34)
8:55:11 AM: 2021-02-26T13:55:11.391Z prisma:tryLoadEnv Environment variables not found at null
8:55:11 AM: 2021-02-26T13:55:11.392Z prisma:tryLoadEnv Environment variables not found at undefined
8:55:11 AM: 2021-02-26T13:55:11.392Z prisma:tryLoadEnv No Environment variables loaded
8:55:11 AM: ✔ Generated Prisma Client (2.17.0) to ./node_modules/@prisma/client in 294ms
8:55:11 AM: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
8:55:11 AM: ```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

I wasn't able to find anything related to that error with the build/index.js

I would appreciate any help that could be provided with this error! :)

**Comment by pantharshit00** [comment]
Hey @NicolasBonet 

Try this:
```prisma
generator client { 
provider = "prisma-client-js"
 previewFeatures = ["createMany"]
binaryTargets = ["native","rhel-openssl-1.0.x"] 
}
```

**Comment by pantharshit00** [comment]
You can also checkout this e2e test: https://github.com/prisma/e2e-tests/tree/dev/platforms/netlify-cli

**Comment by NicolasBonet** [comment]
Hello @pantharshit00,

Thank you very much, at the end, I just deployed to Vercel and everything worked without further configuration, so at least for me it's no longer a problem.

**Comment by pantharshit00** [comment]
Okay, closing this for now.
