### ISSUE TITLE
Update() a many to many connection using wrong input type causing Unknown arg error

### ISSUE THREAD

**Issue by dan003400** [prisma/prisma#5884]
```
model User {
  id String @id
  shops Shop[]
}

model Shop {
  id String @id
  users User[]
}
```

```
await context.prisma.user.update({
  where: {
    id,
  },
  data: {
    shops: {
      connect: {
        id: shopId,
      },
    },
  },
});
```

Getting Unknown arg shops in data.shops for type UserUncheckedUpdateManyInput

**Comment by nikolasburk** [comment]
Related issue: https://github.com/prisma/prisma/issues/5852

For some reason, the `update` method that's being called has generated input and return types for an `updateMany` which is causing the errors.

**Comment by dan003400** [comment]
Yes, this would make sense, is there somewhere I can look in the generated client to confirm this theory for us?

**Comment by nikolasburk** [comment]
Typically, when you hit the <kbd>COMMAND</kbd> key on macOS (or I alternatively I _believe_ the <kbd>CTRL</kbd> key on Windows) and then click on the method, it should jump to its definition in Prisma Client's generated `index.d.ts` file where you can inspect all the generated types.

Which editor are you using?

**Comment by dan003400** [comment]
This is assuming I am using VSCode I am guess.

Im currently use vim. I can take a look at the index.d.ts, what definition would I be looking for, the name of this model is `Funnel` for instance.

**Comment by nikolasburk** [comment]
I am using a `User` model and this is what the definitions of `update` and `updateMany` look like respectively:

```ts
update<T extends UserUpdateArgs>(
  args: SelectSubset<T, UserUpdateArgs>
): CheckSelect<T, Prisma__UserClient<User>, Prisma__UserClient<UserGetPayload<T>>>

updateMany<T extends UserUpdateManyArgs>(
  args: SelectSubset<T, UserUpdateManyArgs>
): PrismaPromise<BatchPayload>
```

**Comment by nikolasburk** [comment]
For context, this is the `DEBUG` output from this query:

```
express:router dispatching OPTIONS / +5s
  express:router query  : / +1ms
  express:router expressInit  : / +0ms
  express:router router  : / +0ms
  express:router dispatching OPTIONS / +0ms
  express:router <anonymous>  : / +0ms
  express:router corsMiddleware  : / +1ms
  express:router dispatching POST / +3ms
  express:router query  : / +0ms
  express:router expressInit  : / +0ms
  express:router router  : / +0ms
  express:router dispatching POST / +0ms
  express:router <anonymous>  : / +0ms
  express:router corsMiddleware  : / +1ms
  express:router jsonParser  : / +0ms
  body-parser:json content-type "application/json" +0ms
  body-parser:json content-encoding "identity" +1ms
  body-parser:json read body +0ms
  body-parser:json parse body +7ms
  body-parser:json parse json +0ms
  express:router <anonymous>  : / +0ms
  express:router <anonymous>  : / +0ms
  prisma:client Prisma Client call: +6s
  prisma:client prisma.user.findUnique({
  prisma:client   where: {
  prisma:client     id: 'asdflhasdfjkhasdlfkjhasdf'
  prisma:client   },
  prisma:client   include: {
  prisma:client     shops: {
  prisma:client       include: {
  prisma:client         shop: true
  prisma:client       }
  prisma:client     }
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findUniqueUser(where: {
  prisma:client     id: "asdflhasdfjkhasdlfkjhasdf"
  prisma:client   }) {
  prisma:client     id
  prisma:client     email
  prisma:client     phone
  prisma:client     firstName
  prisma:client     lastName
  prisma:client     password
  prisma:client     resetToken
  prisma:client     status
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client     shops {
  prisma:client       id
  prisma:client       shopId
  prisma:client       userId
  prisma:client       shopInviteId
  prisma:client       role
  prisma:client       status
  prisma:client       createdAt
  prisma:client       shop {
  prisma:client         id
  prisma:client         contactEmail
  prisma:client         supportEmail
  prisma:client         title
  prisma:client         url
  prisma:client         timezone
  prisma:client         currency
  prisma:client         logo
  prisma:client         plan
  prisma:client         status
  prisma:client         orderNumberPrefix
  prisma:client         orderNumberSuffix
  prisma:client         betterPaymentsMerchantId
  prisma:client         betterPaymentsUserId
  prisma:client         betterPaymentsApiKey
  prisma:client         betterPaymentsUnderwritingStatus
  prisma:client         betterPaymentsAccountStatus
  prisma:client         createdAt
  prisma:client         updatedAt
  prisma:client       }
  prisma:client     }
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:engine {
  prisma:engine   cwd: '/Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/prisma'
  prisma:engine } +5s
  prisma:engine Search for Query Engine in /Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/.prisma/client +1ms
  plusX Execution permissions of /Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/.prisma/client/query-engine-darwin are fine +5s
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '51278' ] } +0ms
  prisma:engine stdout Starting a postgresql pool with 17 connections. +34ms
prisma:info  Starting a postgresql pool with 17 connections.
  prisma:engine stdout Fetched a connection from the pool +56ms
prisma:info  Fetched a connection from the pool
  prisma:engine stdout Started http server on http://127.0.0.1:51278 +1ms
prisma:info  Started http server on http://127.0.0.1:51278
  prisma:engine Search for Query Engine in /Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/.prisma/client +3ms
  plusX Execution permissions of /Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/.prisma/client/query-engine-darwin are fine +94ms
  prisma:engine stdout Fetched a connection from the pool +6ms
prisma:info  Fetched a connection from the pool
  prisma:engine Client Version: 2.17.0 +5ms
  prisma:engine Engine Version: query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 +0ms
  prisma:engine Active provider: postgresql +0ms
  prisma:engine stdout Unknown error +8ms
prisma:query SELECT "public"."User"."id", "public"."User"."email", "public"."User"."phone", "public"."User"."firstName", "public"."User"."lastName", "public"."User"."password", "public"."User"."resetToken", "public"."User"."status", "public"."User"."createdAt", "public"."User"."updatedAt" FROM "public"."User" WHERE "public"."User"."id" = $1 LIMIT $2 OFFSET $3
  prisma:engine stdout Unknown error +7ms
prisma:query SELECT "public"."UsersOnShops"."id", "public"."UsersOnShops"."shopId", "public"."UsersOnShops"."userId", "public"."UsersOnShops"."shopInviteId", "public"."UsersOnShops"."role", "public"."UsersOnShops"."status", "public"."UsersOnShops"."createdAt" FROM "public"."UsersOnShops" WHERE "public"."UsersOnShops"."userId" IN ($1) OFFSET $2
  prisma:engine stdout Unknown error +15ms
prisma:query SELECT "public"."Shop"."id", "public"."Shop"."contactEmail", "public"."Shop"."supportEmail", "public"."Shop"."title", "public"."Shop"."url", "public"."Shop"."timezone", "public"."Shop"."currency", "public"."Shop"."logo", "public"."Shop"."plan", "public"."Shop"."status", "public"."Shop"."orderNumberPrefix", "public"."Shop"."orderNumberSuffix", "public"."Shop"."betterPaymentsMerchantId", "public"."Shop"."betterPaymentsUserId", "public"."Shop"."betterPaymentsApiKey", "public"."Shop"."betterPaymentsUnderwritingStatus", "public"."Shop"."betterPaymentsAccountStatus", "public"."Shop"."createdAt", "public"."Shop"."updatedAt" FROM "public"."Shop" WHERE "public"."Shop"."id" IN ($1,$2) OFFSET $3
PrismaClientValidationError: Unknown arg `digitalWallets` in data.digitalWallets for type FunnelUncheckedUpdateManyInput.
    at Document.validate (/Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/@prisma/client/runtime/index.js:76461:19)
    at NewPrismaClient._executeRequest (/Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/@prisma/client/runtime/index.js:78299:17)
    at NewPrismaClient._requestWithMiddlewares (/Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/@prisma/client/runtime/index.js:78250:19)
    at /Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/@prisma/client/runtime/index.js:78243:53
    at /Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/dist/utils/prisma.js:44:16
    at NewPrismaClient._requestWithMiddlewares (/Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/@prisma/client/runtime/index.js:78243:16)
    at /Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/@prisma/client/runtime/index.js:78243:53
    at /Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/dist/utils/prisma.js:27:16
    at NewPrismaClient._requestWithMiddlewares (/Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/@prisma/client/runtime/index.js:78243:16)
    at /Users/danwetherald/Developer/BetterCart/refactor/bettercart/monster-bash/node_modules/@prisma/client/runtime/index.js:78243:53
```

**Comment by dan003400** [comment]
We have confirmed this only happens when running within a graphql resolver where prisma is accessed via context.

We have also confirmed this still happens if prisma is manually imported into the resolver rather than using `context.prisma` with the same issue.

We ahve also confirmed this does work just fine with a node script that runs the exact same code with the same imported prisma module tried in the last test.

**Comment by pantharshit00** [comment]
Hey @dan003400 

Can you please share a minimal reproduction for this in a github repository? 

I wasn't able to reproduce with my attempt.

**Comment by dan003400** [comment]
@pantharshit00 - This seems to only happen when run within a graphql resolver - VERY strange, also, this only happens for this one specific model in this case. I have other resolvers that can perform a single update() just fine.

**Comment by dan003400** [comment]
I would share more of a code example in a repo, but I actually have a number of other resolvers that are identical that work just fine, its only treating update() as updateMany() for this one model.

Anything else I can share that would help?

**Comment by dan003400** [comment]
Just stumbled upon the issue!

![image](https://user-images.githubusercontent.com/1211542/109700573-8c3b4d80-7b57-11eb-8584-29621b463545.png)

This is why we were only seeing the issue in this one model and not the others.

We added the suggest middleware for soft deleting records here: 

https://www.prisma.io/docs/concepts/components/prisma-client/middleware/soft-delete-middleware#option-2-use-middleware-to-determine-the-behavior-of-readupdate-queries-for-deleted-records

**Comment by nikolasburk** [comment]
Seems like this has been resolved then 🎉
