### ISSUE TITLE
PANIC in query-engine/connectors/sql-query-connector/src/query_builder/write.rs:22:56called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by Drunkenpilot** [prisma/prisma#5966]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.14.1           | 
| OS              | darwin             |
| Prisma Client   | 2.18.0             |
| Query Engine    | query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1|
| Database        | undefined|

## Query
```
mutation {
  createOneBusiness(data: {
    Balance: {
      create: {
        Count: 5
        WarningLine: 5
        CountTest: 5
      }
    }
  }) {
    businessId
  }
}
```

## Logs
```
ex.js:24049:10)  {"timestamp":"Mar 03 20:20:27.927","level":"ERROR","fields":{"message":"PANIC","reason":"called `Option::unwrap()` on a `None` value","file":"query-engine/connectors/sql-query-connector/src/query_builder/write.rs","line":22,"column":56},"target":"query_engine","span":{"name":"execute_single_operation"},"spans":[{"name":"execute_single_operation"}]}  
  prisma:engine {
  prisma:engine   error: SocketError: closed
  prisma:engine       at Socket.onSocketClose (/Users/user/workspace/project/project-b2b/node_modules/@prisma/client/runtime/index.js:25204:33)
  prisma:engine       at Socket.emit (events.js:223:5)
  prisma:engine       at TCP.<anonymous> (net.js:664:12) {
  prisma:engine     name: 'SocketError',
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:55023
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  prisma:engine     errno: 'ECONNREFUSED',
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 55023
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/Users/user/workspace/project/project-b2b/prisma' }  
  prisma:engine Search for Query Engine in /Users/user/workspace/project/project-b2b/node_modules/.prisma/client  
  plusX Execution permissions of /Users/user/workspace/project/project-b2b/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '55027' ] }  
  prisma:engine stdout  Starting a mysql pool with 13 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:55027  
  prisma:engine Search for Query Engine in /Users/user/workspace/project/project-b2b/node_modules/.prisma/client  
  plusX Execution permissions of /Users/user/workspace/project/project-b2b/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.18.0  
  prisma:engine Engine Version: query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/query_builder/write.rs:22:56
called `Option::unwrap()` on a `None` value  
  prisma:engine TypeError: this.currentRequestPromise.cancel is not a function
  prisma:engine     at NodeEngine.handlePanic (/Users/user/workspace/project/project-b2b/node_modules/@prisma/client/runtime/index.js:26934:36)
  prisma:engine     at NodeEngine.setError (/Users/user/workspace/project/project-b2b/node_modules/@prisma/client/runtime/index.js:26880:16)
  prisma:engine     at LineStream.<anonymous> (/Users/user/workspace/project/project-b2b/node_modules/@prisma/client/runtime/index.js:27170:24)
  prisma:engine     at LineStream.emit (events.js:223:5)
  prisma:engine     at addChunk (_stream_readable.js:309:12)
  prisma:engine     at readableAddChunk (_stream_readable.js:290:11)
  prisma:engine     at LineStream.Readable.push (_stream_readable.js:224:10)
  prisma:engine     at LineStream.Transform.push (_stream_transform.js:150:32)
  prisma:engine     at LineStream._pushBuffer (/Users/user/workspace/project/project-b2b/node_modules/@prisma/client/runtime/index.js:24055:19)
  prisma:engine     at LineStream._transform (/Users/user/workspace/project/project-b2b/node_modules/@prisma/client/runtime/index.js:24049:10)  {"timestamp":"Mar 03 20:20:28.149","level":"ERROR","fields":{"message":"PANIC","reason":"called `Option::unwrap()` on a `None` value","file":"query-engine/connectors/sql-query-connector/src/query_builder/write.rs","line":22,"column":56},"target":"query_engine","span":{"name":"execute_single_operation"},"spans":[{"name":"execute_single_operation"}]}  
  prisma:engine {
  prisma:engine   error: SocketError: closed
  prisma:engine       at Socket.onSocketClose (/Users/user/workspace/project/project-b2b/node_modules/@prisma/client/runtime/index.js:25204:33)
  prisma:engine       at Socket.emit (events.js:223:5)
  prisma:engine       at TCP.<anonymous> (net.js:664:12) {
  prisma:engine     name: 'SocketError',
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
  await this.client.business.create({
                data: {
                    Balance: {
                        create: {
                            Count: 0,
                            WarningLine: 0,
                            CountTest: 0
                        }
                    }
                }
            })
```

## Schema
```prisma
model Business {
  businessId           String          @id @default(cuid()) @db.VarChar(128)
  Balance              Balance?
  balanceRecords       BalanceRecord[]

  @@index([businessId], name: "businessId")
}

model Balance {
  balanceId      String          @id @default(cuid()) @db.VarChar(128)
  Count          Decimal         @map("count") @db.Decimal(10, 3)
  CountTest      Decimal         @map("count") @db.Decimal(10, 3)
  WarningLine    Decimal         @map("warningLine") @db.Decimal(10, 3)
  version        Int             @default(0) @db.Int
  createdAt      DateTime?       @default(now()) @db.Timestamp(0)
  updatedAt      DateTime?       @updatedAt @db.Timestamp(0)
  business       String          @unique @db.VarChar(128)
  Business       Business        @relation(fields: [business], references: [businessId])

  @@index([balanceId], name: "balanceId")
}

```

**Comment by Drunkenpilot** [comment]
Sorry, Error found
Duplicated @map("count")

**Comment by pantharshit00** [comment]
This schema should be rejected by the validator and should not hit the panic. We will keep this open and fix the validator here.

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/109929754-d73a9980-7cec-11eb-8762-c58564498770.png)

**Comment by daniellaera** [comment]
![Screenshot 2021-05-06 at 14 26 25](https://user-images.githubusercontent.com/8995710/117297947-15804080-ae77-11eb-82b6-0bbe7d68fb94.png)

**Comment by janpio** [comment]
That looks unrelated - please open a new issue and fill the issue template then we can take a look.
