### ISSUE TITLE
Engine dies on bad postgres connection

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#5976]
## Error
```
Error in PostgreSQL connection: Error { kind: Closed, cause: None }
```

This seems to be related to the elevated number of connection pool timeout I started seeing in my projects after updating to more recent versions of prisma (2.14 was working fine).

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.15.4           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.17.0             |
| Query Engine    | query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223|
| Database        | undefined|

## Query
```
query {
  findFirstEvent(where: {
    OR: [
      {
        slug: "X"
        launchDate: {
          lte: "X"
        }
      }
    ]
  }) {
    id
    visibility
    slug
    name
    description
    venueName
    timezone
    highlighted
    promoterId
    addressId
    accessibility
    startsAt
    endsAt
    ageLimit
    image
    delivery
    attendeesNote
    launchDate
    type
    createdAt
    updatedAt
  }
}
```

## Logs
```
ebian-openssl-1.1.x are fine
prisma:engine {
  flags: [
    '--enable-experimental=groupBy',
    '--enable-raw-queries',
    '--port',
    '36358'
  ]
}
prisma:engine stdout  Starting a postgresql pool with 10 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:36358
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine Client Version: 2.17.0
prisma:engine Engine Version: query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223
prisma:engine Active provider: postgresql
prisma:client Error: Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `connection_limit` parameter (https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#connection-pool). Current limit: 10.
    at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27154:16)
    at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27052:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async cb (/app/node_modules/.prisma/client/runtime/index.js:78659:26)
    at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24)
prisma:client Error: Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `connection_limit` parameter (https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#connection-pool). Current limit: 10.
    at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27154:16)
    at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27052:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async cb (/app/node_modules/.prisma/client/runtime/index.js:78659:26)
    at async DataLoader._batchLoadFn (/app/src/modules/TicketTier/loaders/categoryTiers.js:9:20)
prisma:client Error: Timed out fetching a new connection from the pool. Please consider reducing the number of requests or increasing the `connection_limit` parameter (https://www.prisma.io/docs/concepts/components/prisma-client/connection-management#connection-pool). Current limit: 10.
    at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27154:16)
    at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27052:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async cb (/app/node_modules/.prisma/client/runtime/index.js:78659:26)
    at async DataLoader._batchLoadFn (/app/src/modules/Promoter/loaders/promoter.js:9:20)
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27156:14)
      at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27052:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/app/node_modules/.prisma/client/runtime/index.js:78659:26)
      at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24) {
    clientVersion: '2.17.0'
  }
}
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27156:14)
      at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27052:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/app/node_modules/.prisma/client/runtime/index.js:78659:26)
      at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24) {
    clientVersion: '2.17.0'
  }
}
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27156:14)
      at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27052:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/app/node_modules/.prisma/client/runtime/index.js:78659:26)
      at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24) {
    clientVersion: '2.17.0'
  }
}
```

**Comment by Sytten** [comment]
This is running on Cloud Run with a minimum instance of 2 and max of 5.
This means some containers might live for a long time but be on pause.
This is problematic in other stacks, see this for golang https://issuetracker.google.com/issues/181655427
I resolved most of my issues by setting a maximum lifetime of every connection to 1h and a maximum idle of 15m.
I think we should be allowed to set those via query parameters.

**Comment by janpio** [comment]
Is there a way to possibly set up a minimal reproduction of this that we can look at ourselves?

**Comment by Sytten** [comment]
I don't think it is specific to a schema, it is more a cloud run with minimum instances + cloud sql combo I think. I have seen bad connection when the instance stays idle a long time and then some tries to use it.

**Comment by Sytten** [comment]
I believe the issue might be due to the `test_on_checkout` flag of the mobc pool: https://github.com/prisma/prisma-engines/blob/28e77d62415dc0475af4c133d8b87d49caaa8f88/query-engine/connectors/sql-query-connector/src/database/postgresql.rs#L35

**Comment by Sytten** [comment]
Well this code does look suspicious too: https://github.com/prisma/quaint/blob/d72b591a31ab2af4ff8d7ed0fe91fc48bbc97deb/src/pooled.rs#L442-L444

**Comment by Sytten** [comment]
I did more testing:
- Good news: the latest engine doesn't crash on connection closed
- Bad news: the connection doesn't seem to be discarded from the pool

**Comment by Sytten** [comment]
I thought that the  engine didn't die anymore but it seems like it still does:
```
:01:01.763Z"},{"prisma__type":"date","prisma__value":"2021-04-01T16:29:50.674Z"},"1 day",2155,29,"1 day"])
prisma:client Prisma Client call:
prisma:client prisma.queryRaw(
    SELECT
      start_ts AS timestamp,
      COUNT(ticket.id) AS value
    FROM
      generate_series($1::TIMESTAMP, $2::TIMESTAMP, $3::TEXT::INTERVAL) AS start_ts
      LEFT JOIN (
        SELECT
          ticket.id,
          ticket.created_at
        FROM
          ticket
          LEFT JOIN event ON event.id = ticket.event_id
        WHERE
          1 = 1
          AND ticket.event_id = $4 
          AND event.promoter_id = $5
       ) AS ticket ON ticket.created_at >= start_ts AND ticket.created_at < start_ts + $6::TEXT::INTERVAL
    GROUP by start_ts
    ORDER BY start_ts
  , [{"prisma__type":"date","prisma__value":"2021-03-01T17:29:50.674Z"},{"prisma__type":"date","prisma__value":"2021-04-01T16:29:50.674Z"},"1 day",2162,29,"1 day"])
prisma:client Prisma Client call:
prisma:client prisma.queryRaw(
    SELECT
      start_ts AS timestamp,
      COUNT(ticket.id) AS value
    FROM
      generate_series($1::TIMESTAMP, $2::TIMESTAMP, $3::TEXT::INTERVAL) AS start_ts
      LEFT JOIN (
        SELECT
          ticket.id,
          ticket.created_at
        FROM
          ticket
          LEFT JOIN event ON event.id = ticket.event_id
        WHERE
          1 = 1
          AND ticket.event_id = $4 
          AND event.promoter_id = $5
       ) AS ticket ON ticket.created_at >= start_ts AND ticket.created_at < start_ts + $6::TEXT::INTERVAL
    GROUP by start_ts
    ORDER BY start_ts
  , [{"prisma__type":"date","prisma__value":"2021-03-26T03:41:25.154Z"},{"prisma__type":"date","prisma__value":"2021-04-01T16:29:50.674Z"},"1 day",2162,29,"1 day"])
prisma:client Prisma Client call:
prisma:client prisma.queryRaw(
    SELECT
      start_ts AS timestamp,
      COUNT(ticket.id) AS value
    FROM
      generate_series($1::TIMESTAMP, $2::TIMESTAMP, $3::TEXT::INTERVAL) AS start_ts
      LEFT JOIN (
        SELECT
          ticket.id,
          ticket.created_at
        FROM
          ticket
          LEFT JOIN event ON event.id = ticket.event_id
        WHERE
          1 = 1
           
          AND event.promoter_id = $4
       ) AS ticket ON ticket.created_at >= start_ts AND ticket.created_at < start_ts + $5::TEXT::INTERVAL
    GROUP by start_ts
    ORDER BY start_ts
  , [{"prisma__type":"date","prisma__value":"2021-03-01T18:16:36.383Z"},{"prisma__type":"date","prisma__value":"2021-04-01T17:16:36.383Z"},"1 day",265,"1 day"])
prisma:client Prisma Client call:
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27578:14)
      at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27474:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/app/node_modules/.prisma/client/runtime/index.js:34832:26)
      at async Object.exports.default [as accessPromoLink] (/app/src/modules/PromoLink/actions/accessPromoLink.js:7:27)
      at async accessPromoLink (/app/src/modules/PromoLink/resolvers.js:49:24)
      at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24) {
    clientVersion: '2.20.1'
  }
}
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27578:14)
      at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27474:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/app/node_modules/.prisma/client/runtime/index.js:34832:26)
      at async Object.exports.default [as accessPromoLink] (/app/src/modules/PromoLink/actions/accessPromoLink.js:7:27)
      at async accessPromoLink (/app/src/modules/PromoLink/resolvers.js:49:24)
      at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24) {
    clientVersion: '2.20.1'
  }
}
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27578:14)
      at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27474:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/app/node_modules/.prisma/client/runtime/index.js:34832:26)
      at async Object.exports.default [as accessPromoLink] (/app/src/modules/PromoLink/actions/accessPromoLink.js:7:27)
      at async accessPromoLink (/app/src/modules/PromoLink/resolvers.js:49:24)
      at async middleware (/app/node_modules/graphql-shield/dist/generator.js:30:24) {
    clientVersion: '2.20.1'
  }
}
```

**Comment by Sytten** [comment]
Ok so my test bench reports that this is just a lie that the engine tells the client, the process doesnt actually crash.

**Comment by janpio** [comment]
Information about the PR that closed this:
https://github.com/prisma/prisma/issues/6329#issuecomment-815012006

Feel free to reply here again if the problem is not solved/better for you and we can reopen the issue of course.
