### ISSUE TITLE
Error: Error in migration engine. Reason: [libs\datamodel\core\src\transform\attributes\unique_and_index.rs:149:46] called `Result::unwrap()` on an `Err` value: TypeMismatchError { expected_type: "constant literal", received_type: "string", raw: "tenantId", span: Span { start: 6221, end: 6231 } } 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#5985]
Command: `prisma db push --preview-feature --accept-data-loss`
Version: `2.18.0`
Binary Version: `da6fafb57b24e0b61ca20960c64e2d41f9e8cff1`
Report: https://prisma-errors.netlify.app/report/13069 
OS: `x64 win32 10.0.19042`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [libs\datamodel\core\src\transform\attributes\unique_and_index.rs:149:46] called `Result::unwrap()` on an `Err` value: TypeMismatchError { expected_type: "constant literal", received_type: "string", raw: "tenantId", span: Span { start: 6221, end: 6231 } }

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

    at ChildProcess.<anonymous> (C:\Users\Ramin\Documents\GitHub\nest-multitenant\node_modules\prisma\build\index.js:54939:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
[libs\datamodel\core\src\transform\attributes\unique_and_index.rs:149:46] called `Result::unwrap()` on an `Err` value: TypeMismatchError { expected_type: "constant literal", received_type: "string", raw: "tenantId", span: Span { start: 6221, end: 6231 } }
```

**Comment by tomhoule** [comment]
New report: https://prisma-errors.netlify.app/report/13066

**Comment by tomhoule** [comment]
It's happening when putting string literals in `@@unique`. Actionable: better error.
