### ISSUE TITLE
Drift detected when nothing has changed

### ISSUE THREAD

**Issue by gavrichards** [prisma/prisma#5987]
## Bug description

I have a repeated issue where when running Prisma Migrate, it says "Drift detected: Your database schema is not in sync with your migration history." and wants to wipe the whole database, even though nothing has changed.

I've reluctantly opted to accept resetting the database several times otherwise I wouldn't be able to get anything done, but this is really becoming a chore and making me have second thoughts about Prisma which I otherwise love to use.

## How to reproduce

1. Make no changes to schema or the database itself
2. Run `prisma migrate dev --preview-feature`
3. Result:

```Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "(redacted)" at "(redacted)"

? Drift detected: Your database schema is not in sync with your migration history.

We need to reset the MySQL database "(redacted)" at "(redacted)".
Do you want to continue? All data will be lost. › (y/N)

## Expected behavior

<!-- A clear and concise description of what you expected to happen. -->

Nothing in the schema or the database has changed since the last use of the command, so there should be no need to reset the database.

## Prisma information

<!-- Your Prisma schema, Prisma Client queries, ...
Do not include your database credentials when sharing your Prisma schema! -->

My schema is sensitive to the project I'm working on, but if there is anything specific that would help diagnose the issue I'll do my best to share.

## Environment & setup

<!-- In which environment does the problem occur -->

- OS: Mac OS Big Sur
- Database: MySQL
- Node.js version: 12.20.0
- Prisma version: 
<!--[Run `prisma -v` to see your Prisma version and paste it between the ´´´]-->

```
Environment variables loaded from prisma/.env
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : darwin
Query Engine         : query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.356.0

```

**Comment by tomhoule** [comment]
Hi @gavrichards, thanks for reporting your problem. It's very hard to debug without knowing anything about the schema, especially since we have a pretty extensive test suite. One known problem that exhibits the same symptoms, and we are planning to work on soon is with datetime literal defaults (`myField DateTime @default("2020-01-18T00:00:00)` for example). Can you identify a specific model/field that triggers this behaviour?

If you run  `prisma migrate dev` with the `DEBUG=*` env var, you should have a lot of extra information that could help us figure this out.

**Comment by Jolg42** [comment]
You can share your schema privately to schemas@prisma.io with a link to this issue, that would help.

**Comment by gavrichards** [comment]
@Jolg42 done, thanks!

**Comment by gavrichards** [comment]
@tomhoule I've added the `DEBUG=*` env var but it isn't giving me any extra information.

Looking through my schema, DateTime is used in the following ways:
```
DateTime       @default(now())
DateTime       @updatedAt
DateTime
DateTime?
```

Would any of those cause this issue?

**Comment by tomhoule** [comment]
These should work, so it's probably not what is causing the problem — thanks for sending the schema, we'll give you an updated as soon as we've had a chance to look at it.

**Comment by gavrichards** [comment]
@tomhoule thanks, I really appreciate this.

**Comment by gavrichards** [comment]
I got the debug option to work by setting it using `export` before running the migrate command.
I'm not sure the result is very useful, but I thought I'd share just in case:
```
> project@1.0.0 prisma-migrate /Users/(redacted)
> prisma migrate dev --preview-feature

  prisma:loadEnv project root found at /Users/(redacted)/package.json +0ms
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables loaded from ./prisma/.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 3: 
[dotenv][DEBUG] "DEBUG" is already defined in `process.env` and will not be overwritten
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "(redacted)" at "(redacted)"

  prisma:migrateEngine:rpc starting migration engine with binary: /Users/(redacted)/node_modules/@prisma/engines/migration-engine-darwin +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"/Users/(redacted)/prisma/migrations"}} +4ms
  prisma:migrateEngine:stderr Mar 07 23:11:37.174  INFO migration_engine: Starting migration engine RPC server git_hash="da6fafb57b24e0b61ca20960c64e2d41f9e8cff1" +0ms
  prisma:migrateEngine:stderr Mar 07 23:11:37.329  INFO quaint::single: Starting a mysql connection. +153ms
  prisma:migrateEngine:stderr Mar 07 23:11:37.660  INFO DevDiagnostic:calculate_drift:sql_schema_from_migration_history: quaint::single: Starting a mysql connection. +331ms
  prisma:migrateEngine:stderr Mar 07 23:11:48.261  INFO DevDiagnostic:validate_migrations:sql_schema_from_migration_history: quaint::single: Starting a mysql connection. +11s
  prisma:migrate:dev {
  prisma:migrate:dev   devDiagnostic: '{\n' +
  prisma:migrate:dev     '  "action": {\n' +
  prisma:migrate:dev     '    "tag": "reset",\n' +
  prisma:migrate:dev     '    "reason": "Drift detected: Your database schema is not in sync with your migration history."\n' +
  prisma:migrate:dev     '  }\n' +
  prisma:migrate:dev     '}'
  prisma:migrate:dev } +0ms
? Drift detected: Your database schema is not in sync with your migration history.

We need to reset the MySQL database "(redacted)" at "(redacted)".
Do you want to continue? All data will be lost. › (y/N)
```

One other thing I wondered, would it be any help if I shared how the schema is changed by running the `prisma introspect` command?

**Comment by tomhoule** [comment]
Yes it would definitely help! I am planning to work on this tomorrow (today is a holiday here in Berlin :)) Thanks for all the info

**Comment by gavrichards** [comment]
Thanks @tomhoule - I have just sent you the updated schema. Please let me know if there is anything else you need.

**Comment by tomhoule** [comment]
I've spent some time to reproduce the issue with your schema, on both mysql 5.7 and mysql 8 (linux), and couldn't make the drift problem happen on my setup. There could be other factors influencing your setup:

- Do you get a migration after the message about drift and the reset? If so, what is in that migration? (no need to share the whole migration if you'd rather not too, just knowing the type of SQL statements in the migration would help a lot)
- Have you tried different mysql databases (like docker, remote, etc.)? Did it happen there? (Not implying you should switch, just trying to get more context to debug)
- What does `SELECT @@lower_case_table_names;` return on your MySQL instance? Example on mine:

```

mysql> SELECT @@lower_case_table_names;
+--------------------------+
| @@lower_case_table_names |
+--------------------------+
|                        0 |
+--------------------------+
1 row in set (0.00 sec)
```

I'll tweak the log output so we at least get a better idea of _what_ drifted. Sorry it's taking some time, thanks for your patience.

**Comment by gavrichards** [comment]
Hi @tomhoule 

- I don't get a migration but I haven't accepted the reset on this occasion, while this is being diagnosed. When this has happened previously and I have reset, it has generated an empty migration.
- No, I've only used this with the one database - MySQL on Amazon Aurora.
- It gives the same result as your example.

Knowing what drifted would be incredibly useful - thanks for your speedy work on this.

**Comment by tomhoule** [comment]
Ok that narrows things down. Aurora is based on MySQL 5.6, so I tried with a MySQL 5.6 container locally, and couldn't reproduce the problem either. Next steps for me:

- More useful verbose logging
- Get an actual Aurora instance to test on

**Comment by gavrichards** [comment]
I've just checked my Aurora config and it appears to be MySQL 5.7.
Engine version: `5.7.mysql_aurora.2.09.1`

**Comment by tomhoule** [comment]
@gavrichards the logger changes made it into `prisma@dev`. I double checked with `2.19.0-dev.23`, and with the verbose logging enabled, you can now see exactly what drifted. It would be super helpful if you could check and send us the drift (either here or at `schemas@prisma.io` if it contains sensitive info)

**Comment by gavrichards** [comment]
@tomhoule thanks - how do I enable verbose logging?

**Comment by tomhoule** [comment]
Ah, it's the same `export DEBUG=*` as previously.

**Comment by gavrichards** [comment]
Ok it's logged:

> prisma:migrateEngine:stderr Mar 10 16:12:46.519  INFO DevDiagnostic: migration_core::commands::dev_diagnostic: DriftDetected diagnostic rollback="/*\n  Warnings:\n\n  - The migration will add a unique constraint covering the columns `[parentSlotId]` on the table `Slot`. If there are existing duplicate values, the migration will fail.\n\n*/\n-- CreateIndex\nCREATE UNIQUE INDEX `Slot_parentSlotId_unique` ON `Slot`(`parentSlotId`);\n" +10s

This is interesting. 

I previously had a problem where a unique index was being created where I didn't want one, on the "parentSlotId" column of the Slot table. If that index were unique, then you couldn't have multiple slots with the same parentSlotId, which is a requirement of my app. I think I read about this problem in another issue.
It was suggested that you should manually remove the unique constraint and it should be fine.
I also read that the best way to do this is to create a blank migration and enter the SQL (or copy it from Workbench) so that your migration history is intact.

So in my last successful migration, I created a blank migration and entered this:
```
ALTER TABLE `svt`.`Slot`
DROP INDEX `Slot_parentSlotId_unique` ,
ADD INDEX `Slot_parentSlotId_unique` (`parentSlotId` ASC);
;
```

I realise the naming of the index is confusing there, suggesting it is unique when it isn't, but that's because I just altered the existing index that had been created by Prisma and thought it best not to rename it.

This migration worked and the problem in my app was fixed.

But now it seems like (thanks to this new verbose logging) that Prisma is trying to add the unique constraint back again.

**Comment by tomhoule** [comment]
Great! Ok, we have a much better idea now — I'll try to reproduce this behaviour in a test, and keep you up to date. Thanks a lot for your help debugging this, btw!

It's not clear to me yet where that unique constraint that migrate thinks is missing comes from — it could be a bug related to relations. We add an implicit index to enforce the 1:1 on one-to-one relations, this could be where the index comes from (and it would be bug, since the relation on this field is not 1:1 but 1:m).

**Comment by gavrichards** [comment]
No problem, very happy to help get this resolved with you.
As you say, yes this is a 1:m relationship and should not have a unique constraint, even though it is a self-relation.

**Comment by danyel117** [comment]
Hello guys, I'm experiencing the same issues in two projects I'm developing. What I have done so far is  that before applying a migration, I make a copy of my database and then restore the data from it after the migration is applied. I'm using Mysql on AWS RDS.

I'm available if you need more information or other examples for debugging.

My issue only happens when I use "dev" migrations. When I use the "deploy" command, it doesn't prompt me to restore the database.

**Comment by tomhoule** [comment]
Hi @danyel117, can you give us more detail on what is happening in dev? Do you get a new migration after accepting a reset (without change in your prisma schema)? What does it contain?

I'll try to find time to set up an Aurora database today to try to reproduce the issue.

**Comment by danyel117** [comment]
For me, what happens is the following: I define my schema, and after some days I make a change in the schema and use the command npx prisma migrate dev --name NameForMyMigration --preview-feature.

The command shows me a message saying that some random migration was modified after it was applied, and it asks me to reset the database, even though I have not made any manual changes to that specific migration.

What I have done so far, is that before applying the migration, I save a copy of the database, run the migration that ereases data, and after the migration is applied, I copy back all the info.

```
_Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "test_gentedemente" at "prevalentware.c3rkad1ay1ao.us-east-1.rds.amazonaws.com:3306"

The migration `20210224170328_modelos_otros` was modified after it was applied.     

We need to reset the MySQL database "test_gentedemente" at "prevalentware.c3rkad1ay1ao.us-east-1.rds.amazonaws.com:3306".
Do you want to continue? All data will be lost. » (y/N)_
```

**Comment by gavrichards** [comment]
@tomhoule I understand you're working on this - is it possible to have an indication of if it's something you're likely to fix in the near future in an upcoming release?
My project is currently on hold due to this, as otherwise I'd have to repeatedly clear my database every time I wanted to make a change to the schema (after first correcting the index constraint) and it's just way too much hassle.
Thanks!

**Comment by gavrichards** [comment]
@tomhoule is there a workaround for having a 1:m self relation that doesn't create a unique index? 

I think a concise summary of the issue I'm seeing is:

- Table has 1:m self relation.
- Prisma creates a 'unique' index on the table on the 'parent id' column. I don't want a unique index as multiple rows should be able to have the same parent.
- I create a blank migration, and add SQL which removes the 'unique' aspect of the index (it actually deletes the index and creates a new one).
- I continue adding data, and all is fine.
- I make a change to my schema (can be anything at all) and run the migrate command.
- Prisma says the database must be reset, and we now know it's because it wants to add the unique constraint back, which it can't do because there's now data in the table.

**Comment by tomhoule** [comment]
@gavrichards I got my hands on an aurora mysql instance, and I can't reproduce the issue — even with your schema, I never get the drift detected messages. I tried both with the default behaviour for shadow databases (no custom url) and with a custom `shadowDatabaseUrl` pointing to an existing database on the same host. 

```
mysql> SELECT @@version;
+-----------+
| @@version |
+-----------+
| 5.7.12    |
+-----------+
1 row in set (0.05 sec)
```

Does your instance have a different version? Are you using aurora serverless or provisioned?

**Comment by gavrichards** [comment]
@tomhoule thanks Tom, it's the same version as that.
Did you enter some data in the Slot table? I think that's the key to this you need to have multiple rows with the same parent, so that the parent column can't be unique.

**Comment by gavrichards** [comment]
@tomhoule thanks Tom, it's the same version as that.
@tomhoule Did you enter some data in the Slot table? I think that's the key to this you need to have multiple rows with the same parent, so that the parent column can't be unique.

It's provisioned.

**Comment by tomhoule** [comment]
Thanks for the quick reply, I'll try that :+1.

**Comment by tomhoule** [comment]
@gavrichards After another session of manual testing on the aurora instance, including data in the tables, I still can't reproduce the issue. I have a few more ideas of what might cause this that I can try to test for locally though, not giving up on the investigation.

**Comment by tomhoule** [comment]
@gavrichards  looking at the migration snippet you pasted again:

```sql
ALTER TABLE `svt`.`Slot`
DROP INDEX `Slot_parentSlotId_unique` ,
ADD INDEX `Slot_parentSlotId_unique` (`parentSlotId` ASC);
```

I think there is a bad interaction with the shadow database here in the "ALTER TABLE `svt`.`Slot`" part: the database name is not the same on the shadow database. Can you try to remove the table prefix in the migrations you edited manually and see if that solves the problem? It's definitely something that can happen and cause problems, we should build in some mitigation for that in migrate itself.

**Comment by gavrichards** [comment]
Thanks @tomhoule. I've altered the migration to remove the prefix. Then I ran migrate, it asked me to reset my DB so I accepted. I'm now trying to get things running again to see if the issue is still present once I've added some data, but I'm hitting a brick wall. This might be unrelated so feel free to tell me to create a new issue, but every call to my API (and by extension Prisma) is giving me this:
```
event - build page: /api/auth/login
wait  - compiling...
warn  - ./prisma/client/runtime/index.js
Critical dependency: the request of a dependency is an expression

./prisma/client/runtime/index.js
Module not found: Can't resolve 'encoding' in '/Users/[redacted]/prisma/client/runtime'
TypeError: debugLib is not a function
    at Object.eval (webpack-internal:///./prisma/client/index.js:1:471)
    at eval (webpack-internal:///./prisma/client/index.js:27:30)
    at Object../prisma/client/index.js (/Users/[redacted]/.next/server/pages/api/auth/login.js:103:1)
    at __webpack_require__ (/Users/[redacted]/.next/server/pages/api/auth/login.js:23:31)
    at eval (webpack-internal:///./src/libs/prisma.js:2:72)
    at Module../src/libs/prisma.js (/Users/[redacted]/.next/server/pages/api/auth/login.js:161:1)
    at __webpack_require__ (/Users/[redacted]/.next/server/pages/api/auth/login.js:23:31)
    at eval (webpack-internal:///./src/pages/api/auth/login.js:4:69)
    at Module../src/pages/api/auth/login.js (/Users/[redacted]/.next/server/pages/api/auth/login.js:173:1)
    at __webpack_require__ (/Users/[redacted]/.next/server/pages/api/auth/login.js:23:31)
    at /Users/[redacted]/.next/server/pages/api/auth/login.js:91:18
    at Object.<anonymous> (/Users/[redacted]/.next/server/pages/api/auth/login.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```
Any ideas?
I'm on 2.19.0 of `prisma` and `@prisma/client`.

**Comment by tomhoule** [comment]
Hmm looks like a typescript issue, I'm not an expert on that, relaying that to people who know — it's 9pm here in Berlin so I wouldn't expect an answer before tomorrow :) Thanks for your patience!

**Comment by gavrichards** [comment]
It's specific to `2.19.0`. I've rolled back to `2.18.0` and I don't get the "TypeError: debugLib is not a function" error.

**Comment by gavrichards** [comment]
Ok some good news. Now I'm back on `2.18.0` I've been able to:

- Run `prisma migrate dev` and no migration is generated as nothing has changed
- Run my app and add some data, particularly to the Slot table, creating a situation where multiple slots have the same parent ID (requiring that index to not have the unique constraint)
- Made a change to the schema
- Run `prisma migrate dev` again, the change is made and I am **not** asked to reset the database 🎉

So, learnings from this are:
1. The root issue is that the unique constraint is added when it shouldn't be, but I know you're aware of this as I saw it mentioned more recently in #6239.
2. Working around that, the issue of resetting the DB was caused by the inclusion of the database name in the manual migration. This came about from me copying the SQL from Workbench. I wasn't aware that the database name needed to be omitted.
3. `2.19.0` has a bug, so I'll remain on `2.18.0` for now until this can be addressed. Happy to open a new issue if necessary and you feel it is useful.

Thanks for all for your help and time so far @tomhoule. I can at least resume work on my project now :)

**Comment by tomhoule** [comment]
I'm super glad to read this! Sorry it took so long to get you back on track, and thanks for your patience. Let's keep this issue open, at least until we have more specialized issues or solutions for the `debugLib` crash and the implicit unique constraints.

**Comment by Jolg42** [comment]
@gavrichards 
> TypeError: debugLib is not a function
>     at Object.eval (webpack-internal:///./prisma/client/index.js:1:471)
>     at eval (webpack-internal:///./prisma/client/index.js:27:30)
>     at Object../prisma/client/index.js (/Users/[redacted]/.next/server/pages/api/auth/login.js:103:1)
> Any ideas?
> I'm on 2.19.0 of `prisma` and `@prisma/client`.

About this it seems we have a reproduction by a user here https://github.com/prisma/prisma/issues/6051#issuecomment-801901829, maybe follow that issue to get the updates.

**Comment by gavrichards** [comment]
Thanks @Jolg42 I've commented there.

**Comment by janpio** [comment]
FYI: `debugLib` crash has been fixed via https://github.com/prisma/prisma/pull/6260
