### ISSUE TITLE
(Nestjs + Prisma) Query engine error on Heroku

### ISSUE THREAD

**Issue by kraglalbert** [prisma/prisma#6091]
## Bug description

Following the discussion #6070 it seems there may be an issue with Nestjs + Prisma when deployed to Heroku. 

I've been trying to deploy the backend of a Yarn workspaces-based monorepo to Heroku and I've run into an issue that I can't seem to find many discussions about. The logs from my Heroku application are:

```
2021-03-11T17:31:02.034211+00:00 app[web.1]: events.js:292
2021-03-11T17:31:02.034244+00:00 app[web.1]: throw er; // Unhandled 'error' event
2021-03-11T17:31:02.034245+00:00 app[web.1]: ^
2021-03-11T17:31:02.034245+00:00 app[web.1]:
2021-03-11T17:31:02.034245+00:00 app[web.1]: Error: spawn /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x EAGAIN
2021-03-11T17:31:02.034246+00:00 app[web.1]: at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
2021-03-11T17:31:02.034249+00:00 app[web.1]: at onErrorNT (internal/child_process.js:465:16)
2021-03-11T17:31:02.034250+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-03-11T17:31:02.034250+00:00 app[web.1]: Emitted 'error' event on ChildProcess instance at:
2021-03-11T17:31:02.034251+00:00 app[web.1]: at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2021-03-11T17:31:02.034251+00:00 app[web.1]: at onErrorNT (internal/child_process.js:465:16)
2021-03-11T17:31:02.034252+00:00 app[web.1]: at processTicksAndRejections (internal/process/task_queues.js:80:21) {
2021-03-11T17:31:02.034252+00:00 app[web.1]: errno: -11,
2021-03-11T17:31:02.034253+00:00 app[web.1]: code: 'EAGAIN',
2021-03-11T17:31:02.034253+00:00 app[web.1]: syscall: 'spawn /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x',
2021-03-11T17:31:02.034254+00:00 app[web.1]: path: '/app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x',
2021-03-11T17:31:02.034254+00:00 app[web.1]: spawnargs: [ '--enable-raw-queries', '--port', '46000' ]
2021-03-11T17:31:02.034254+00:00 app[web.1]: }
2021-03-11T17:31:02.091427+00:00 app[web.1]: error Command failed with exit code 1.
2021-03-11T17:31:02.092738+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-03-11T17:31:02.199626+00:00 app[web.1]: error Command failed.
2021-03-11T17:31:02.199627+00:00 app[web.1]: Exit code: 1
2021-03-11T17:31:02.199628+00:00 app[web.1]: Command: /app/.heroku/node/bin/node
2021-03-11T17:31:02.199628+00:00 app[web.1]: Arguments: /app/.heroku/yarn/lib/cli.js run start:prod
2021-03-11T17:31:02.199629+00:00 app[web.1]: Directory: /app/backend
2021-03-11T17:31:02.199629+00:00 app[web.1]: Output:
2021-03-11T17:31:02.199629+00:00 app[web.1]:
2021-03-11T17:31:02.199977+00:00 app[web.1]: info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
2021-03-11T17:31:02.288259+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-03-11T17:31:02.289709+00:00 app[web.1]: npm ERR! errno 1
2021-03-11T17:31:02.334145+00:00 app[web.1]: npm ERR! root@1.0.0 start: `yarn workspace backend run start:prod`
2021-03-11T17:31:02.334372+00:00 app[web.1]: npm ERR! Exit status 1
2021-03-11T17:31:02.334633+00:00 app[web.1]: npm ERR!
2021-03-11T17:31:02.338627+00:00 app[web.1]: npm ERR! Failed at the root@1.0.0 start script.
2021-03-11T17:31:02.338784+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-03-11T17:31:02.371876+00:00 app[web.1]:
2021-03-11T17:31:02.373456+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-03-11T17:31:02.373650+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-03-11T17_31_02_340Z-debug.log
2021-03-11T17:31:02.601466+00:00 heroku[web.1]: Process exited with status 1
2021-03-11T17:31:02.694790+00:00 heroku[web.1]: State changed from starting to crashed
```

This occurs after the Heroku build has succeeded, the Nestjs modules have initialized and the Nestjs controller routes have been mapped. The Nestjs application does not finish starting up since the `[NestApplication] Nest application successfully started` is never logged.

When running the built app from Heroku bash directly I get the following:
```
(node:100) UnhandledPromiseRejectionWarning: Error: Query engine exited with code 101

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/blocking/pool.rs:261:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: tokio::runtime::blocking::pool::Spawner::spawn
   4: tokio::runtime::blocking::pool::spawn_blocking
   5: tokio::runtime::thread_pool::worker::Launch::launch
   6: tokio::runtime::builder::Builder::build
   7: tokio::runtime::Runtime::new
   8: core::ops::function::FnOnce::call_once
   9: once_cell::imp::OnceCell<T>::initialize::{{closure}}
  10: once_cell::imp::initialize_inner
  11: once_cell::imp::OnceCell<T>::initialize
  12: async_global_executor::reactor::block_on
  13: async_global_executor::init::init_with_config
  14: core::ops::function::FnOnce::call_once
  15: once_cell::imp::OnceCell<T>::initialize::{{closure}}
  16: once_cell::imp::initialize_inner
  17: once_cell::imp::OnceCell<T>::initialize
  18: async_std::task::builder::Builder::blocking
  19: query_engine::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at ChildProcess.<anonymous> (/app/node_modules/@prisma/client/runtime/index.js:27199:23)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I tried the workaround mentioned in [#5533](https://github.com/prisma/prisma/issues/5533#issuecomment-788016345) but this gave the same error when deployed.

Our `package.json` file in the root of our project has the following scripts:
```
"scripts": {
    "build": "yarn workspace backend run build",
    "heroku-postbuild": "yarn install --production=false && npx prisma generate --schema=backend/prisma/schema.prisma && yarn workspace backend run build",
    "start": "yarn workspace backend run start:prod"
  }
```

## How to reproduce

I haven't been able to produce this error other than in the repo I'm working on. I deployed a clone of https://github.com/notiz-dev/deploy-nestjs-prisma-heroku to Heroku after updating Prisma to 2.18.0, but that deployed without any issues. Looking at that repo and my own, I'm not sure if there are any Prisma-specific differences between them that would cause mine to fail. I can provide more info if needed.

## Expected behavior

The Nestjs app runs on Heroku successfully.

## Prisma information

```
prisma               : 2.18.0
@prisma/client       : 2.18.0
Current platform     : darwin
Query Engine         : query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt da6fafb57b24e0b61ca20960c64e2d41f9e8cff1 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.356.0
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14.16.0 (on Heroku)
- Prisma version: 2.18.0

**Comment by pantharshit00** [comment]
Hey @kraglalbert 

Can you please try this again with the latest version of Prisma once? We haven't received any new reports regarding deploys failing on heroku so please try this with the latest version once.

**Comment by kraglalbert** [comment]
@pantharshit00 it seemed the issue was due to the specific yarn workspaces setup we were using and not Prisma, so I'll go ahead and close this issue.
