### ISSUE TITLE
Caught error missing code and meta properties (they are undefined)

### ISSUE THREAD

**Issue by dilizarov** [prisma/prisma#6166]
## Bug description

I write a query like:

```typescript
try {
  await [deleted, created] =  this.prisma.$transaction([
  this.prisma.users.deleteMany({ where: { username: "someUsername" } }),
  this.prisma.users.create({ where: { username: "notUniqueUsername" } })
])
} catch (error) {
  if (error.code === "P2002") throw new BadRequestException("Username isn't unique. Derp")
}
```

My expectation is for this to work and I know the error is a P2002 error because when I `console.log(error)` I see information akin to:

```
Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: Some(KnownError { message: "Unique constraint failed on the fields: (`socialId`,`platform`)", meta: Object({"target": Array([String("socialId"), String("platform")])}), error_code: "P2002" }), kind: UniqueConstraintViolation { constraint: Fields(["socialId", "platform"]) } })
    at /Users/david/Code/project/packages/server2/node_modules/@prisma/client/runtime/index.js:27103:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  clientVersion: '2.17.0'
}
``` 

Ignore minor differences (socialId/platform versus username) as I was just giving an example earlier...

https://www.prisma.io/docs/reference/api-reference/error-reference

The documentation tells me to expect a `error.meta` and `error.code` and both are undefined when I console.log them.

## 

How to reproduce

View above

## Expected behavior

`error.code` and `error.meta` should behave as documented

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v12.10.0
- Prisma version:

```
prisma               : 2.17.0
@prisma/client       : 2.17.0
Current platform     : darwin
Query Engine         : query-engine 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 3c463ebd78b1d21d8fdacdd27899e280cf686223 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.353.0
```

**Comment by dilizarov** [comment]
I updated the above to show that my issue actually happens when doing things with transactions.

**Comment by dilizarov** [comment]
For what it is worth, error.message exists and is 

```
"ConnectorError(ConnectorError { user_facing_error: Some(KnownError { message: "Unique constraint failed on the fields: (`socialId`,`platform`)", meta: Object({"target": Array([String("socialId"), String("platform")])}), error_code: "P2002" }), kind: UniqueConstraintViolation { constraint: Fields(["socialId", "platform"]) } })"... but this is still broken and hella janky because I don't think it is realistic for me to have to do REGEX on this message to find the P2002 error.
```

Ryan on Slack confirmed it.

**Comment by janpio** [comment]
I think this is similar to https://github.com/prisma/prisma/issues/6156

**Comment by dilizarov** [comment]
@janpio I can confirm the 3 retry attempts on my end.

**Comment by pantharshit00** [comment]
I can reproduce this, looks like only `{"clientVersion":"2.20.0-dev.18"}` is available in the error. 

Ready to use reproduction:
```ts
import { PrismaClient } from "@prisma/client";

async function main() {
  const prisma = new PrismaClient();
  await prisma.user.create({
    data: {
      email: "nonunique",
    },
  });
  try {
    const [deleted, created] = await prisma.$transaction([
      prisma.user.deleteMany({
        where: {
          email: "test",
        },
      }),
      prisma.user.create({
        data: {
          email: "nonunique",
        },
      }),
    ]);
    console.log(deleted, created);
  } catch (error) {
    console.log(JSON.stringify(error));
    console.log(error.code);
    console.log(error.meta);
  }
  prisma.$disconnect();
}

main();
```

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int      @default(autoincrement()) @id
  createdAt DateTime @default(now())
  title     String
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}

model Profile {
  id     Int     @default(autoincrement()) @id
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model User {
  id      Int      @default(autoincrement()) @id
  email   String   @unique
  name    String?
  posts   Post[]
  profile Profile?
}
```
