### ISSUE TITLE
Cannot resolve the collation conflict between "Chinese_PRC_CI_AS" and "Chinese_PRC_CS_AS_KS" in the equal to operation.

### ISSUE THREAD

**Issue by TianYa-Q** [prisma/prisma#6167]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.14.0           | 
| OS              | darwin             |
| Prisma Client   | 2.19.0             |
| Query Engine    | query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d|
| Database        | undefined|

## Logs

```
a/本地文稿/0程序/starter/node_modules/.prisma/client/query-engine-darwin are fine
prisma:engine {
  flags: [
    '--enable-experimental=microsoftSqlServer',
    '--enable-raw-queries',
    '--port',
    '56974'
  ]
}
prisma:engine stdout  Starting a mssql pool with 9 connections.
prisma:engine stdout  Performing a TLS handshake
prisma:engine stdout  Trusting the server certificate without validation.
prisma:engine stdout  TLS handshake successful
prisma:engine stdout  Turning TLS off after a login. All traffic from here on is not encrypted.
prisma:engine stdout  Database change from '' to 'master'
prisma:engine stdout  Changed database context to ''.
prisma:engine stdout  SQL collation change from None to None
prisma:engine stdout  Microsoft SQL Server�� version 4077846543
prisma:engine stdout  Packet size change from '4096' to '4096'
prisma:engine stdout  Started http server on http://127.0.0.1:56974
prisma:engine Search for Query Engine in /Users/tianya/本地文稿/0程序/starter/node_modules/.prisma/client
plusX Execution permissions of /Users/tianya/本地文稿/0程序/starter/node_modules/.prisma/client/query-engine-darwin are fine
prisma:engine Client Version: 2.19.0
prisma:engine Engine Version: query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d
prisma:engine Active provider: sqlserver
prisma:engine stdout  Begin transaction
prisma:engine stdout  Cannot resolve the collation conflict between "Chinese_PRC_CI_AS" and "Chinese_PRC_CS_AS_KS" in the equal to operation.
prisma:engine stdout  Rollback transaction
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 468, state: 9, class: 16, message: "Cannot resolve the collation conflict between \"Chinese_PRC_CI_AS\" and \"Chinese_PRC_CS_AS_KS\" in the equal to operation.", server: "sql1", procedure: "", line: 1 }) })
      at NodeEngine.graphQLToJSError (/Users/tianya/本地文稿/0程序/starter/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/Users/tianya/本地文稿/0程序/starter/node_modules/@prisma/client/runtime/index.js:29695:24)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/Users/tianya/本地文稿/0程序/starter/node_modules/@prisma/client/runtime/index.js:34744:26)
      at async main (/Users/tianya/本地文稿/0程序/starter/index.js:5:22) {
    clientVersion: '2.19.0'
  }
}
prisma:engine stdout  Begin transaction
prisma:engine stdout  Cannot resolve the collation conflict between "Chinese_PRC_CI_AS" and "Chinese_PRC_CS_AS_KS" in the equal to operation.
prisma:engine stdout  Rollback transaction
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 468, state: 9, class: 16, message: "Cannot resolve the collation conflict between \"Chinese_PRC_CI_AS\" and \"Chinese_PRC_CS_AS_KS\" in the equal to operation.", server: "sql1", procedure: "", line: 1 }) })
      at NodeEngine.graphQLToJSError (/Users/tianya/本地文稿/0程序/starter/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/Users/tianya/本地文稿/0程序/starter/node_modules/@prisma/client/runtime/index.js:29695:24)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/Users/tianya/本地文稿/0程序/starter/node_modules/@prisma/client/runtime/index.js:34744:26)
      at async main (/Users/tianya/本地文稿/0程序/starter/index.js:5:22) {
    clientVersion: '2.19.0'
  }
}
prisma:engine stdout  Begin transaction
prisma:engine stdout  Cannot resolve the collation conflict between "Chinese_PRC_CI_AS" and "Chinese_PRC_CS_AS_KS" in the equal to operation.
prisma:engine stdout  Rollback transaction
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(TokenError { code: 468, state: 9, class: 16, message: "Cannot resolve the collation conflict between \"Chinese_PRC_CI_AS\" and \"Chinese_PRC_CS_AS_KS\" in the equal to operation.", server: "sql1", procedure: "", line: 1 }) })
      at NodeEngine.graphQLToJSError (/Users/tianya/本地文稿/0程序/starter/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/Users/tianya/本地文稿/0程序/starter/node_modules/@prisma/client/runtime/index.js:29695:24)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/Users/tianya/本地文稿/0程序/starter/node_modules/@prisma/client/runtime/index.js:34744:26)
      at async main (/Users/tianya/本地文稿/0程序/starter/index.js:5:22) {
    clientVersion: '2.19.0'
  }
}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
  const createUser = await prisma.boatUsers.create({
    data: {
      userName: '66',
      userPassward: '6666',
      gonghao: '66',
    },
  });
```

**Comment by pantharshit00** [comment]
Can you share some details about your database? Which version you are using and which collation you are using. 

First glance indicates this is related to specific collation which we don't handle properly.

**Comment by Gilbert-Qian** [comment]
@pantharshit00 
### version:
Microsoft SQL Server 2019 (RTM-CU8-GDR) (KB4583459) - 15.0.4083.2 (X64)   Nov  2 2020 18:35:09   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 18.04.5 LTS) <X64>
### collation:
Chinese_PRC_CI_AS

**Comment by pantharshit00** [comment]
I am still unable to reproduce, can you share your schema and possibly check whether collation of `boatUsers` table is not different from the database.

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
