### ISSUE TITLE
Optional `connect` with an `undefined` value causes prisma to fail

### ISSUE THREAD

**Issue by GCastilho** [prisma/prisma#6186]
## Bug description

I have a clients an users table. The user has an optional relation with the clients. When I try to create an user passing undefined to the client connect the query fails with ```Unknown arg `client` in data.client for type UserUncheckedCreateInput. Did you mean `clientId`? Available args```

This is the complete stack trace:
```
InternalServerError: PrismaClientValidationError: 
Invalid `prisma.user.create()` invocation in
/tmp/api/src/routes/v1/users.ts:20:21

  17 	client,
  18 	role,
  19 } = await validate(UserInput, req.body)
→ 20 await prisma.user.create({
       data: {
         email: 'register@email.com',
         password: '$2a$08$xylQ2RcEG4/IaOOK9xzBBOQYEKiFzZCl0usy.v7U4RAZ.DV9xyjg.',
         role: undefined,
         client: {
         ~~~~~~
           connect: {
             name: undefined
           }
         }
       }
     })

Unknown arg `client` in data.client for type UserUncheckedCreateInput. Did you mean `clientId`? Available args:
type UserUncheckedCreateInput {
  id?: String
  clientId?: String | Null
  email: String
  password: String
  role?: UserRole
  createdAt?: DateTime
  updatedAt?: DateTime
}


    at Document.validate (/tmp/api/node_modules/@prisma/client/runtime/index.js:32448:19)
    at NewPrismaClient._executeRequest (/tmp/api/node_modules/@prisma/client/runtime/index.js:34385:17)
    at /tmp/api/node_modules/@prisma/client/runtime/index.js:34320:52
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (/tmp/api/node_modules/@prisma/client/runtime/index.js:34320:25)
    at Object.catch (/tmp/api/node_modules/@prisma/client/runtime/index.js:34471:39)
    at /tmp/api/src/routes/v1/users.ts:29:11 {
  clientVersion: '2.19.0'
}
```

## Expected behavior

Since the type definitions allow the client name to be undefined on the connect object, the query just run without problems and create a user that is not linked to the client

## Prisma information

This is the prisma schema:
```prisma
enum UserRole {
  USER
  BOT
  ADMIN
}

model Client {
  @@map("clients")
  id              String    @id @default(uuid())  @db.VarChar(36)
  name            String    @unique               @db.VarChar(30)
  createdAt       DateTime  @default(now())
  updatedAt       DateTime  @updatedAt
  users           User[]
}

model User {
  @@map("users")
  id              String    @id @default(uuid())  @db.VarChar(36)
  clientId        String?                         @db.VarChar(36)
  client          Client?   @relation(fields: [clientId], references: [id])
  email           String    @unique               @db.VarChar(80)
  password        String                          @db.VarChar(60)
  role            UserRole  @default(USER)
  createdAt       DateTime  @default(now())
  updatedAt       DateTime  @updatedAt
}
```

And this is the prisma query:
```typescript
await prisma.user.create({
	data: {
		email,
		password,
		role,
		client: {
			connect: { name: client }
		}
	}
})
```
email and password are strings while the "client" is undefined
## Environment & setup

- OS: Debian 10 buster x64
- Database: PostgreSQL 12 (localhost)
- Node.js version: v14.16.0
- Prisma version: 2.19.0

**Comment by pantharshit00** [comment]
Sorry for the late reply here. 

This is expected. Please read this docs section about this: https://www.prisma.io/docs/concepts/components/prisma-client/null-and-undefined


Client will treat `undefined` as no value passed at all.

**Comment by GCastilho** [comment]
> Client will treat `undefined` as no value passed at all.

Yes, that is what I want. If I pass an undefined name it should (according to the docs) threat as I have passed no value. So it should NOT try to connect a client (since I passed "no value to the name"), but it does try to connect and it fails

**Comment by pantharshit00** [comment]
Sorry, I phrased this a bit incorrectly. Client will treat undefined as nothing and it will omit that field from the query. If you don't want to connect when name is undefined, do the following:
```ts
await prisma.user.create({
	data: {
		email,
		password,
		role,
		client: name ? {
			connect: { name: client }
		} : undefined,
	}
})
```

**Comment by GCastilho** [comment]
Right, I think I can use that as a workaround

But is that the expected behavior or a bug?

**Comment by pantharshit00** [comment]
I am pretty sure this is the expected behaviour here. 

Pinging @matthewmueller for confirmation.

**Comment by GCastilho** [comment]
I don't think it make sense to be the expected behavior 

The client name, in this example, is required, so it would _never_ be undefined yet the type system _allows_ an undefined name to be specified. On runtime it will try to connect with an undefined name which _will_ case an exception despite the type system allowing that value in the compilation

I think it should threat undefined as no value is passed at all, since that's what's written in the docs

**Comment by matthewmueller** [comment]
This seems to be about defining the behavior of:

```ts
await prisma.user.create({
	data: {
		email,
		password,
		role,
		client: {
			connect: {}
		}
	}
})
```

And right now it throws a runtime error, but @GCastilho proposes that it should do nothing.

I'm not sure we've clearly defined this yet. Labeling as an enhancement.
