### ISSUE TITLE
"number too large to fit in target type" using BigInt & PostgreSQL

### ISSUE THREAD

**Issue by embiem** [prisma/prisma#6212]
## Bug description

When using a number as large as `18375000000000000000n` to save into a "BigInt", then Prisma throws the following error:

```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]:
Invalid `prisma.<redacted>.update()` invocation:


  Error parsing GraphQL query: query parse error: Parse error at 7:13
number too large to fit in target type

    at cb (<redacted>\node_modules\@prisma\client\runtime\index.js:34778:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  clientVersion: '2.19.0'
}
```

## How to reproduce

1. Create a schema and add a field using BigInt as type.
2. Connect to a local PostgreSQL database
3. Try creating/updating with the field value of e.g. "18375000000000000000n".
4. Should throw the above mentioned error.

## Expected behavior

I'd expect a valid BigInt value in JS to work when using it with Prisma.

## Additional Context

I know that Prisma maps BigInt to integer for PostgreSQL databases & thusly BigInt cannot handle numbers larger than 9223372036854775807.

As I didn't find any results when googling "number too large to fit in target type", I thought I'd post this finding here anyways. Even if it's just for tracking that this won't be changed and you have to e.g. use a BigInt encoded as string or use the Decimal type to track big numbers like that.

**Comment by pantharshit00** [comment]
@embiem Hey, can you share your schema here? You can map to BigInt as well on db level via native types like so.

```prisma
model Test {
  id String @id @default(cuid())
  myfield BigInt
}
```

See details here: https://www.prisma.io/docs/concepts/database-connectors/postgresql#type-mapping-between-postgresql-to-prisma-schema

**Comment by pantharshit00** [comment]
I am going to close this as its been over a months now and there is no activity here. 

Please reply if you want us to take another look.

**Comment by artur-makeev** [comment]
Iv got the same error.

model ChatRoom {
  id BigInt @default(autoincrement()) @id
  eventId BigInt
 }

when I run this.prisma.chatRoom.create({ data }) with eventId as "2" it works but when I pass "9223372036854775808" it throws an error.
