### ISSUE TITLE
orderByRelation bug

### ISSUE THREAD

**Issue by stabl-finance** [prisma/prisma#6228]
## Bug description

The `orderByRelation`  works on 1/n relations but not n/n

Here is the simplified schema : 

```
model User {
  id                        Int                       @id @default(autoincrement())
  gender                    Gender?                   @relation("user_gender", fields: [gender_id], references: [id])
  user_to_message_dst       User_message[]            @relation("user_to_message_dst__user")
}

model Gender {
  id             Int        @id @default(autoincrement())
  user           User[]     @relation("user_gender")
}

model User_message {
  id             Int        @id @default(autoincrement())
  user_dst       User       @relation("user_to_message_dst__user", fields: [user_dst_id], references: [id])
}
```

## How to reproduce

The ordering by `gender` relation works fine.
But with `user_to_message_dst` it isn't, it asks me for `count`... : 

```js
  res.locals.prisma.user.findMany({
    orderBy : {
      user_to_message_dst : {
        id: 'desc'
      },
    },
    select: {
      id: true,
      user_to_message_dst : { 
        select : {
          id: true,
        },
      },
      gender : { select : {
        id: true,
      }},
    },
  })
```
 I got : 

```
Error:
Invalid `prisma.user.findMany()` invocation:

{
  where: {},
  orderBy: {
    user_to_message_dst: {
      id: 'desc',
      ~~
+     count: asc | desc
    }
  },
  select: {
    id: true,
    user_to_message_dst: {
      select: {
        id: true
      }
    },
    gender: {
      select: {
        id: true
      }
    }
  }
}

Unknown arg `id` in orderBy.user_to_message_dst.id for type User_messageOrderByAggregateInput.
Argument count for orderBy.user_to_message_dst.count is missing.

Note: Lines with + are required

    at Document.validate (C:\idm2_prisma\node_modules\@prisma\client\runtime\index.js:32448:19)
    at NewPrismaClient._executeRequest (C:\idm2_prisma\node_modules\@prisma\client\runtime\index.js:34385:17)
    at C:\idm2_prisma\node_modules\@prisma\client\runtime\index.js:34320:52
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (C:\idm2_prisma\node_modules\@prisma\client\runtime\index.js:34320:25)
    at Object.then (C:\idm2_prisma\node_modules\@prisma\client\runtime\index.js:34440:39)
    at _20c‍.r.exports.list_message (C:\idm2_prisma\src\queries\adm_user.js:129:6)
    at Layer.handle [as handle_request] (C:\idm2_prisma\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\idm2_prisma\node_modules\express\lib\router\route.js:137:13)
    at verifyToken (C:\idm2_prisma\src\middleware\authJwt.js:30:3)

```

## Expected behavior

Should order by related field

## Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v14.15.4
- Prisma version: 2.19

**Comment by stabl-finance** [comment]
Hi there, 
is there someone that uses this orderByRelation feature 😅 ?

**Comment by pantharshit00** [comment]
Hello 👋 

Sorry for late reply here. This is expected, you can only order by count of number of relations right now.

Can you please tell me how you want to order the fields here? Like this is an n:m relation as you expected so you can't really pick the a single record in the relation and order by its value.

**Comment by stabl-finance** [comment]
Hi, thanks for your response.
Yes it's a n:n relation
In fact I want to order by message date, to have the newest messages in top, to simplify the example I did the order using id.
(The gender is useless, it's just to show that the order by gender works as expected)

It would be great yes... or I don't know how to do it properly.

Thanks

**Comment by stabl-finance** [comment]
This is the query I'm trying to do in my case : 

`SELECT "User".id, "User".nickname 
FROM "User" 
JOIN "User_message" ON "User_message".user_dst_id = "User".id
ORDER BY "User_message"."createdAt" ASC `

Thanks for help

**Comment by pantharshit00** [comment]
Ah, this is not supported yet. I will mark this as a feature request I will update the title.

**Comment by pantharshit00** [comment]
Ok wait, I can get the same result as that join via the following query:
```js
  const test = await prisma.user_message.findMany({
    orderBy: {
      id: "asc",
    },
    select: {
      user_dst_id: true,
    },
  });
```

**Comment by stabl-finance** [comment]
It will order by user id, but not by last message, in the query I wan't to order by createdAt (or message id at least), but not user id..

> Ok wait, I can get the same result as that join via the following query:
> 
> ```js
>   const test = await prisma.user_message.findMany({
>     orderBy: {
>       id: "asc",
>     },
>     select: {
>       user_dst_id: true,
>     },
>   });
> ```

**Comment by johncantrell97** [comment]
I need this same functionality for a slightly different use case (but essentially the same query).  Example:

Project has many Tasks.

You want to list projects ordered by the most recently updated Task in each Project.

**Comment by matthewmueller** [comment]
Right now it's not possible to order the top-level results by a nested relation, you can just order the results in the nested relation.

```ts
await prisma.user.findMany({ 
  orderBy: { 
    messages: { 
      created_at: "desc"
    }
  }
})
```

Orders messages by creation time, not users that have most recently created a user. It's definitely an interesting idea.

For now, you'll need to do sorting this in your application.

**Comment by rohanrajpal** [comment]
Hey, would appreciate having this too. I'm implementing an Instagram-like chat that sorts contacts by the most recent message.

One more thing to think about is we'll need pagination too, which will break the sorting on an application-level logic and the only way now seems to be raw SQL. Let me figure out the raw SQL query as a workaround until this feature is figured out.

**Comment by rohanrajpal** [comment]
> Hey, would appreciate having this too. I'm implementing an Instagram-like chat that sorts contacts by the most recent message.
> 
> One more thing to think about is we'll need pagination too, which will break the sorting on an application-level logic and the only way now seems to be raw SQL. Let me figure out the raw SQL query as a workaround until this feature is figured out.

Wrote a quick and dirty solution, it's not the best, but progress anyway.

```ts
    async findAllConversations(userProfileId: number, cursor?: string) {
        const limit = 15;
        const where = cursor
            ? Prisma.sql`AND last."sentDateTime" <= ${new Date(cursor)}`
            : Prisma.empty;

        const conversationList = await this.prisma.$queryRaw<Conversation[]>`
                SELECT c.id,
                      c."scopedId",
                      c.name,
                      c."profilePicUrl",
                      c.username,
                      c.channel,
                      last.content,
                      last."sentDateTime"
                FROM "Contact" c
                        INNER JOIN (SELECT "contactId", max("id") messageId FROM "Message" group by "contactId") all_lasts
                                    on all_lasts."contactId" = c.id
                        INNER JOIN "Message" last on last.id = all_lasts.messageId
                WHERE c."userProfileId" = ${userProfileId}
                ${where}
                ORDER BY last."sentDateTime" DESC
                LIMIT ${limit + 1};
        `;
        let nextCursor: Date | undefined;

        if (conversationList.length > limit)
            ({ sentDateTime: nextCursor } = conversationList.pop());

        return {
            conversations: conversationList,
            cursor: nextCursor ? nextCursor.toISOString() : undefined,
        };
}
```

**Comment by dotMortis** [comment]
Need this
