### ISSUE TITLE
PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/7d3753e/postgres-types/src/lib.rs:760:18expected array type

### ISSUE THREAD

**Issue by llldar** [prisma/prisma#6237]
Hi Prisma Team! My Prisma Client just crashed. This is the report:

PS: it works well on my local machine and crashed on the server.

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.15.3           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.19.0             |
| Query Engine    | query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d|
| Database        | undefined|

## Query
```
mutation {
  createOneOAuthClient(data: {
    id: "X"
    secret: "X"
    owner: {
      connect: {
        id: "X"
      }
    }
    scopes: {
      connect: [
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        },
        {
          value: "X"
        }
      ]
    }
    grants: [authorization_code, client_credentials, refresh_token, password]
  }) {
    id
    secret
    grants
    redirectUris
    accessTokenLifetime
    refreshTokenLifetime
    onwerId
    createdAt
    updatedAt
  }
}
```

## Logs
```
m{
  prisma:engine   flags: [
  prisma:engine     '--enable-experimental=createMany',
  prisma:engine     '--enable-raw-queries',
  prisma:engine     '--port',
  prisma:engine     '43487'
  prisma:engine   ]
  prisma:engine }  
  prisma:engine stdout  Starting a postgresql pool with 5 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:43487  
  prisma:engine Search for Query Engine in /root/vlepo/node_modules/.prisma/client  
  plusX Execution permissions of /root/vlepo/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine Client Version: 2.19.0  
  prisma:engine Engine Version: query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/7d3753e/postgres-types/src/lib.rs:760:18
expected array type  
  prisma:engine TypeError: this.currentRequestPromise.cancel is not a function
  prisma:engine     at NodeEngine.handlePanic (/root/vlepo/node_modules/@prisma/client/runtime/index.js:29249:36)
  prisma:engine     at NodeEngine.setError (/root/vlepo/node_modules/@prisma/client/runtime/index.js:29195:16)
  prisma:engine     at LineStream.<anonymous> (/root/vlepo/node_modules/@prisma/client/runtime/index.js:29480:24)
  prisma:engine     at LineStream.emit (events.js:315:20)
  prisma:engine     at LineStream.EventEmitter.emit (domain.js:467:12)
  prisma:engine     at addChunk (internal/streams/readable.js:309:12)
  prisma:engine     at readableAddChunk (internal/streams/readable.js:284:9)
  prisma:engine     at LineStream.Readable.push (internal/streams/readable.js:223:10)
  prisma:engine     at LineStream.Transform.push (internal/streams/transform.js:166:32)
  prisma:engine     at LineStream._pushBuffer (/root/vlepo/node_modules/@prisma/client/runtime/index.js:26388:19)  {"timestamp":"Mar 25 16:09:46.053","level":"ERROR","fields":{"message":"PANIC","reason":"expected array type","file":"/root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/7d3753e/postgres-types/src/lib.rs","line":760,"column":18},"target":"query_engine","span":{"sql":"\"INSERT INTO \\\"public\\\".\\\"OAuthClient\\\" (\\\"id\\\",\\\"secret\\\",\\\"grants\\\",\\\"onwerId\\\",\\\"createdAt\\\",\\\"updatedAt\\\") VALUES ($1,$2,$3,$4,$5,$6) RETURNING \\\"public\\\".\\\"OAuthClient\\\".\\\"id\\\"\"","name":"query_raw"},"spans":[{"name":"execute_single_operation"},{"sql":"\"INSERT INTO \\\"public\\\".\\\"OAuthClient\\\" (\\\"id\\\",\\\"secret\\\",\\\"grants\\\",\\\"onwerId\\\",\\\"createdAt\\\",\\\"updatedAt\\\") VALUES ($1,$2,$3,$4,$5,$6) RETURNING \\\"public\\\".\\\"OAuthClient\\\".\\\"id\\\"\"","name":"query_raw"}]}  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/root/vlepo/node_modules/@prisma/client/runtime/index.js:27523:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:467:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:43487
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -111,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 43487
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
await prisma.oAuthClient.create({
      data: {
        id: OAuthConsts.DEFAULT_CLIENT_ID,
        secret: cryptoRandomString({ length: 20, type: 'alphanumeric' }),
        owner: {
          connect: {
            id: admin.id,
          },
        },
        scopes: {
          connect: [...OAuthConsts.entities, 'self'].map((entity) => ({
            value: entity,
          })),
        },
        grants: Object.values(OAuthGrants),
      },
    });
```

## Schema
```prisma
model OAuthScope {
  value       String  @id
  name        String
  description String?

  //self
  parentValue String?
  parent      OAuthScope?  @relation("OAuthScopeToOAuthScope", fields: [parentValue], references: [value])
  childScopes OAuthScope[] @relation("OAuthScopeToOAuthScope")

  //token
  accessTokens  OAuthAccessToken[]
  refreshTokens OAuthRefreshToken[]

  //code
  authorizationCodes OAuthAuthorizationCode[]

  //client
  clients OAuthClient[]

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@index([value])
}

model OAuthAccessToken {
  accessToken          String   @id
  accessTokenExpiresAt DateTime

  //client
  clientId String
  client   OAuthClient @relation(fields: [clientId], references: [id])

  //scope
  scopes OAuthScope[]

  //user
  user   User   @relation(fields: [userId], references: [id])
  userId String

  createdAt DateTime @default(now())
}

model OAuthRefreshToken {
  refreshToken          String   @id
  refreshTokenExpiresAt DateTime

  //client
  clientId String
  client   OAuthClient @relation(fields: [clientId], references: [id])

  //scope
  scopes OAuthScope[]

  //user
  user   User   @relation(fields: [userId], references: [id])
  userId String

  createdAt DateTime @default(now())

}

enum OAuthGrants {
  authorization_code
  client_credentials
  refresh_token
  password
}

model OAuthClient {
  id                   String        @id
  secret               String        @unique
  grants               OAuthGrants[]
  redirectUris         String[]
  accessTokenLifetime  Int?
  refreshTokenLifetime Int?

  //token
  accessTokens  OAuthAccessToken[]
  refreshTokens OAuthRefreshToken[]

  //user
  owner User @relation(fields: [onwerId], references: [id])

  //code
  authorizationCodes OAuthAuthorizationCode[]

  //scope
  scopes OAuthScope[]

  onwerId String

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@index([secret])
}

model OAuthAuthorizationCode {
  authorizationCode String   @id
  expiresAt         DateTime
  redirectUri       String?

  //client
  clientId String
  client   OAuthClient @relation(fields: [clientId], references: [id])

  //scope
  scopes OAuthScope[]

  user   User   @relation(fields: [userId], references: [id])
  userId String

  createdAt DateTime @default(now())
}

```

**Comment by llldar** [comment]
I'll email/dm you guys the full schema and full code snippet if needed, not going to post them here.

**Comment by janpio** [comment]
Could you fix this problem? If not, sending us the schema to schemas@prisma.io would indeed be useful 🙏

**Comment by llldar** [comment]
Thank you, I was able to fix the problem by renaming the enum name to
singular form. i.e: from OAuthGrants to OAuthGrant. And no more problems.
Although it's a bit wierd that the code is relying on naming conventions to
work.
