### ISSUE TITLE
Prisma query raw with tagged template not working

### ISSUE THREAD

**Issue by euberdeveloper** [prisma/prisma#6246]
When I used tagged template in this query:

```typescript
const result = await prisma.$queryRaw`
            SELECT
                F.id AS "fabbricatoId",
                F.codice AS "fabbricatoCodice",
                F.nome AS "fabbricatoNome",
                F.comune AS "fabbricatoComune",
                F.indirizzo AS "fabbricatoIndirizzo",
                F.n_civico AS "fabbricatoNCivico",
                S.unita_immobiliare AS "stanzaUnitaImmobiliare",
                S.piano AS "stanzaPiano",
                S.numero_stanza AS "stanzaNumeroStanza",
                PL.posto_letto AS "postoLettoPostoLetto",
                S.gestione_diretta AS "stanzaGestioneDiretta",
                S.note AS "stanzaNote",
                M._data_creazione AS "manutenzioneDataCreazione",
                P.id AS "personaId",
                P.nome AS "personaNome",
                P.cognome AS "personaCognome",
                P.codice_fiscale AS "personaCodiceFiscale",
                P.sesso AS "personaSesso",
                O.cittadinanza AS "ospiteCittadinanza",
                O.email AS "ospiteEmail",
                O.telefono_principale AS "ospiteTelefonoPrincipale",
                O.telefono_secondario AS "ospiteTelefonoSecondario",
                C.id AS "contrattoId",
                C.data_inizio AS "contrattoDataInizio",
                C.data_fine AS "contrattoDataFine",
                TC.sigla AS "tipoContrattoSigla",
                C.note AS "contrattoNote"
            FROM test.posto_letto PL
            JOIN test.stanza S
            ON PL.id_stanza = S.id
            JOIN test.fabbricato F
            ON S.id_fabbricato = F.id
            LEFT JOIN test.manutenzione M
            ON (
                S.id = M.id_stanza
                AND M._eliminato = NULL
                AND NOT (M._data_creazione > '${endString}'::date)
            )
            LEFT JOIN test.contratto_su_ospite_su_posto_letto COP
            ON COP.id_posto_letto = PL.id
            LEFT JOIN test.contratto C
            ON (
                COP.id_contratto = C.id
                AND NOT (
                    C.data_fine < '${startString}'::date
                    OR C.data_inizio > '${endString}'::date
                )
            )
            LEFT JOIN test.contratto_su_ospite CO
            ON (
                CO.id_contratto = C.id
                AND CO.id_ospite = COP.id_ospite
            )
            LEFT JOIN test.tipo_contratto TC
            ON C.id_tipo_contratto = TC.id
            LEFT JOIN test.persona P
            ON CO.id_ospite = P.id
            LEFT JOIN test.ospite O
            ON P.id = O.id;
        `;
```

I get this in the query log:

```
prisma:query 
            SELECT
                F.id AS "fabbricatoId",
                F.codice AS "fabbricatoCodice",
                F.nome AS "fabbricatoNome",
                F.comune AS "fabbricatoComune",
                F.indirizzo AS "fabbricatoIndirizzo",
                F.n_civico AS "fabbricatoNCivico",
                S.unita_immobiliare AS "stanzaUnitaImmobiliare",
                S.piano AS "stanzaPiano",
                S.numero_stanza AS "stanzaNumeroStanza",
                PL.posto_letto AS "postoLettoPostoLetto",
                S.gestione_diretta AS "stanzaGestioneDiretta",
                S.note AS "stanzaNote",
                M._data_creazione AS "manutenzioneDataCreazione",
                P.id AS "personaId",
                P.nome AS "personaNome",
                P.cognome AS "personaCognome",
                P.codice_fiscale AS "personaCodiceFiscale",
                P.sesso AS "personaSesso",
                O.cittadinanza AS "ospiteCittadinanza",
                O.email AS "ospiteEmail",
                O.telefono_principale AS "ospiteTelefonoPrincipale",
                O.telefono_secondario AS "ospiteTelefonoSecondario",
                C.id AS "contrattoId",
                C.data_inizio AS "contrattoDataInizio",
                C.data_fine AS "contrattoDataFine",
                TC.sigla AS "tipoContrattoSigla",
                C.note AS "contrattoNote"
            FROM test.posto_letto PL
            JOIN test.stanza S
            ON PL.id_stanza = S.id
            JOIN test.fabbricato F
            ON S.id_fabbricato = F.id
            LEFT JOIN test.manutenzione M
            ON (
                S.id = M.id_stanza
                AND M._eliminato = NULL
                AND NOT (M._data_creazione > '$1'::date)
            )
            LEFT JOIN test.contratto_su_ospite_su_posto_letto COP
            ON COP.id_posto_letto = PL.id
            LEFT JOIN test.contratto C
            ON (
                COP.id_contratto = C.id
                AND NOT (
                    C.data_fine < '$2'::date
                    OR C.data_inizio > '$3'::date
                )
            )
            LEFT JOIN test.contratto_su_ospite CO
            ON (
                CO.id_contratto = C.id
                AND CO.id_ospite = COP.id_ospite
            )
            LEFT JOIN test.tipo_contratto TC
            ON C.id_tipo_contratto = TC.id
            LEFT JOIN test.persona P
            ON CO.id_ospite = P.id
            LEFT JOIN test.ospite O
            ON P.id = O.id;
```

If I add the parentesis (no tagged template), it works.

## Environment & setup

- OS: Ubuntu 20.14
- Database: Postgres
- Node.js version: 15
- Prisma version: 2.18

```

```

**Comment by pantharshit00** [comment]
Hey @euberdeveloper 


Can you please paste the error here? It is hard to reproduce this without sql schema of your database as well so please also provide that if possible.

**Comment by euberdeveloper** [comment]
I thought that the error was the fact that in the query '$1' appeared instead of the date value. Soon I will add the log

**Comment by euberdeveloper** [comment]
@pantharshit00, this is the error logged

```
[WARNING] Prisma tabellone error PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.queryRaw()` invocation:


  Raw query failed. Code: `22007`. Message: `db error: ERROR: invalid input syntax for type date: "$1"`
    at cb (/home/euber/Github/150/operatn-backend/node_modules/@prisma/client/runtime/index.js:79160:17)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 'P2010',
  clientVersion: '2.18.0',
  meta: {
    code: '22007',
    message: 'db error: ERROR: invalid input syntax for type date: "$1"'
  }
}
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.queryRaw()` invocation:


  Raw query failed. Code: `22007`. Message: `db error: ERROR: invalid input syntax for type date: "$1"`
    at cb (/home/euber/Github/150/operatn-backend/node_modules/@prisma/client/runtime/index.js:79160:17)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 'P2010',
  clientVersion: '2.18.0',
  meta: {
    code: '22007',
    message: 'db error: ERROR: invalid input syntax for type date: "$1"'
  }
}
```

**Comment by euberdeveloper** [comment]
I just removed the `'${dateString}'::date` and substituted it directly by injecting the date between the ${}, so `${date}` and it seems to work, do you confirm that if I enclose directly the `Date` object instance it works?

**Comment by pantharshit00** [comment]
@euberdeveloper $1 is totally expected. It is prepared variable which prevents sql injection and it is part of postgres prepared statements that we use.


Yes, you can pass direct date instances to it.

**Comment by euberdeveloper** [comment]
Thank you!

I think that the fact that you can put Date directly inside it could be added to the documentation
