### ISSUE TITLE
Getting Error Message: Inconsistent column data: Conversion failed: premature end of input

### ISSUE THREAD

**Issue by Capsicum42** [prisma/prisma#6251]
## Bug description
I have a simple schema:
```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model Action {
  ActionWithMultiplier ActionWithMultiplier[]
  lnr String @id
  createdAt         DateTime            @default(now())
  updatedAt         DateTime            @updatedAt 
  name    String
}

model Schedule {
  id String @id @default(uuid())
  createdAt         DateTime            @default(now())
  updatedAt         DateTime            @updatedAt 
}

model Mission {
  id String @id @default(uuid())
  actionWMs ActionWithMultiplier[]
  createdAt         DateTime            @default(now())
  updatedAt         DateTime            @updatedAt 
}

model ActionWithMultiplier {
  id       String @id @default(uuid())
  quantity Int
  Action   Action @relation(fields: [actionLnr], references: [lnr])
  actionLnr String
  missionId String?
  mission  Mission? @relation(fields:[missionId], references: [id])
  createdAt         DateTime            @default(now())
  updatedAt         DateTime            @updatedAt 
}
```

## How to reproduce
```
import { PrismaClient } from "@prisma/client";
import { connect } from "node:http2";

const prisma = new PrismaClient();

async function main() {
  console.log("Los");
  const newMission = await prisma.mission.create({
    data: {},
  });

  console.log(newMission);

  let ret;

  ret = await prisma.actionWithMultiplier.create({
    data: {
      quantity: 1,
      Action: {
        connect: { lnr: "1" },
      },
      mission: { connect: { id: newMission.id } },
    },
  });

  console.log(ret);

  ret = await prisma.actionWithMultiplier.create({
    data: {
      quantity: 2,
      Action: {
        connect: { lnr: "2" },
      },
      mission: { connect: { id: newMission.id } },
    },
  });

  console.log(ret);

  ret = await prisma.mission.findMany({
    orderBy: { createdAt: "desc" },
    include: { actionWMs: true },
  });

  console.log("Mission with Actioms");

  console.log(ret);

  const action1 = ret[0].actionWMs[0];

  console.log("first action");

  console.log(action1);

  const newAction = { ...action1, quantity: 99 };

  console.log("new action");
  console.log(newAction);

  ret = await prisma.actionWithMultiplier.update({
    where: {
      id: newAction.id,
    },
    data: { quantity: newAction.quantity },
  });

  console.log("after Update");
  console.log(ret);


  console.log('Find all action')

  ret = await prisma.action.findMany({})

  console.log(ret);


}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```
The script run until the last step `prisma.action.findMany({})`

The following Error is thrown:
``` 
(node:92152) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.action.findMany()` invocation:


  Inconsistent column data: Conversion failed: premature end of input
    at cb (/home/holger/Documents/prisma-data-model-test/node_modules/@prisma/client/runtime/index.js:34774:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:92152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:92152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected behavior
Everything was compiled without error:
´yarn prisma generate´
´yarn prisma migrate dev´

I would expect a list of data or an Error in advance, If my schema is wrong.
Content of Action in database:
´

3 | 2021-03-23 21:42:24 |   | Trinken
-- | -- | -- | --
2 | 2021-03-23 21:42:18 |   | Essen
1 | 2021-03-23 21:42:06 |   | Singen

´

## Environment & setup

- OS: `Linux holger-bugie-dev 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Database: Sqlite
- Node.js version: `node v14.5.0`
- Prisma version:

```
prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.358.0

```

**Comment by Capsicum42** [comment]
I found the solution:

I have created the entries in Action manually. The field ´updatedAt ´ was empty. This causes the error.
