### ISSUE TITLE
Unable to deploy migration. Database error: Error querying the database: db error: ERROR: permission denied for table _prisma_migrations

### ISSUE THREAD

**Issue by DTX-92** [prisma/prisma#6282]
## Bug description

I can't deploy new migration to production database on heroku. 25 migrations already applied and everything was working fine until today. Meanwhile, deploying migrations to dev database on heroku runs without errors.
![image](https://user-images.githubusercontent.com/20479161/112724290-b8ae7380-8f23-11eb-8206-ff2f8960c0d8.png)

## How to reproduce

I can't reproduce it on dev database. I change only POSTGRES variable, so I have no idea, why it fails on production database. Also tried downgrading to 2.16.1. Same error.
I've already checked owner of _prisma_migrations table. Looks good - current user

## Expected behavior

Migration applies

## Environment & setup

- OS: Mac OS-->
- Database: PostgreSQL
- Node.js version: v14.15.4
- Prisma version: 
```
prisma               : 2.19.0
@prisma/client       : 2.19.0
Current platform     : darwin
Query Engine         : query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.358.0
Preview Features     : groupBy, createMany
```

Full log with debug info:
```
Environment variables loaded from .env
Environment variables loaded from prisma/.env
  prisma:engines using NAPI: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +1ms
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "d3cl...", schema "public" at "....compute.amazonaws.com:5432"
  prisma:migrateEngine:rpc starting migration engine with binary: /Users/dtx/Dev/projects/EasyDesk/easydesk-back/node_modules/@prisma/engines/migration-engine-darwin +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"diagnoseMigrationHistory","params":{"migrationsDirectoryPath":"/Users/dtx/Dev/projects/EasyDesk/easydesk-back/prisma/migrations","optInToShadowDatabase":false}} +5ms
  prisma:migrateEngine:stderr Mar 27 17:34:57.239  INFO migration_engine: Starting migration engine RPC server git_hash="c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d" +0ms
  prisma:migrateEngine:stderr Mar 27 17:34:57.700  INFO quaint::single: Starting a postgresql connection. +459ms
  prisma:migrate:deploy {
  prisma:migrate:deploy   diagnoseResult: '{\n' +
  prisma:migrate:deploy     '  "drift": null,\n' +
  prisma:migrate:deploy     '  "history": {\n' +
  prisma:migrate:deploy     '    "diagnostic": "databaseIsBehind",\n' +
  prisma:migrate:deploy     '    "unappliedMigrationNames": [\n' +
  prisma:migrate:deploy     '      "20210326203331_added_times_to_ticket",\n' +
  prisma:migrate:deploy     '      "20210327142602_test_mig"\n' +
  prisma:migrate:deploy     '    ]\n' +
  prisma:migrate:deploy     '  },\n' +
  prisma:migrate:deploy     '  "failedMigrationNames": [],\n' +
  prisma:migrate:deploy     '  "editedMigrationNames": [],\n' +
  prisma:migrate:deploy     '  "errorInUnappliedMigration": null,\n' +
  prisma:migrate:deploy     '  "hasMigrationsTable": true\n' +
  prisma:migrate:deploy     '}'
  prisma:migrate:deploy } +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":2,"jsonrpc":"2.0","method":"listMigrationDirectories","params":{"migrationsDirectoryPath":"/Users/dtx/Dev/projects/EasyDesk/easydesk-back/prisma/migrations"}} +741ms
  prisma:migrate:deploy {
  prisma:migrate:deploy   listMigrationDirectoriesResult: {
  prisma:migrate:deploy     migrations: [
  prisma:migrate:deploy       '20210203175740_initial',
  prisma:migrate:deploy       '20210203184703_added_user_created_tickets',
  prisma:migrate:deploy       '20210204094813_added_fields_to_user',
  prisma:migrate:deploy       '20210204144653_users_groups_m2m',
  prisma:migrate:deploy       '20210205164443_subscribers',
  prisma:migrate:deploy       '20210209133056_time_spent',
  prisma:migrate:deploy       '20210209133434_added_user_to_time_spent',
  prisma:migrate:deploy       '20210209143439_roadmap',
  prisma:migrate:deploy       '20210211090906_attachments',
  prisma:migrate:deploy       '20210225204748_ticket_last_answered_by',
  prisma:migrate:deploy       '20210225205632_last_answered_by_enum',
  prisma:migrate:deploy       '20210225205941_remove_last_answered',
  prisma:migrate:deploy       '20210227200710_projects_and_departments',
  prisma:migrate:deploy       '20210304205532_added_states',
  prisma:migrate:deploy       '20210311161459_updated_users_answeredby',
  prisma:migrate:deploy       '20210312093309_asnwer_user_id',
  prisma:migrate:deploy       '20210313145627_sendmail_ticked_id',
  prisma:migrate:deploy       '20210313190556_ticket_comment_column',
  prisma:migrate:deploy       '20210313202649_deadline',
  prisma:migrate:deploy       '20210318122407_notifications',
  prisma:migrate:deploy       '20210318161623_tickets_to_cc',
  prisma:migrate:deploy       '20210318175408_notifications_index',
  prisma:migrate:deploy       '20210318175549_notifications_last_read',
  prisma:migrate:deploy       '20210318211809_notifications_author',
  prisma:migrate:deploy       '20210321123359_department_to_ticket',
  prisma:migrate:deploy       '20210326203331_added_times_to_ticket',
  prisma:migrate:deploy       '20210327142602_test_mig'
  prisma:migrate:deploy     ]
  prisma:migrate:deploy   }
  prisma:migrate:deploy } +3ms

27 migrations found in prisma/migrations
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":3,"jsonrpc":"2.0","method":"applyMigrations","params":{"migrationsDirectoryPath":"/Users/dtx/Dev/projects/EasyDesk/easydesk-back/prisma/migrations"}} +3ms
  prisma:migrateEngine:stderr Mar 27 17:34:59.302  INFO ApplyMigrations:Applying migration{migration_name="20210326203331_added_times_to_ticket"}: migration_core::commands::apply_migrations: Applying `20210326203331_added_times_to_ticket` script="-- AlterTable\nALTER TABLE \"ticket\" ADD COLUMN     \"lastAssignedAt\" TIMESTAMP(3),\nADD COLUMN     \"lastClosedAt\" TIMESTAMP(3),\nADD COLUMN     \"deadlineChangedCount\" INTEGER DEFAULT 0;\n\n\nUPDATE \"ticket\" SET \"deadlineChangedCount\" = 0;" +2s
  prisma:migrateEngine:rpc {
  prisma:migrateEngine:rpc   jsonrpc: '2.0',
  prisma:migrateEngine:rpc   error: {
  prisma:migrateEngine:rpc     code: 4466,
  prisma:migrateEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:migrateEngine:rpc     data: {
  prisma:migrateEngine:rpc       is_panic: false,
  prisma:migrateEngine:rpc       message: 'Database error: Error querying the database: db error: ERROR: permission denied for table _prisma_migrations\n' +
  prisma:migrateEngine:rpc         '   0: migration_core::api::ApplyMigrations\n' +
  prisma:migrateEngine:rpc         '             at migration-engine/core/src/api.rs:75',
  prisma:migrateEngine:rpc       backtrace: null
  prisma:migrateEngine:rpc     }
  prisma:migrateEngine:rpc   },
  prisma:migrateEngine:rpc   id: 3
  prisma:migrateEngine:rpc } +1s
Error: Error: Database error: Error querying the database: db error: ERROR: permission denied for table _prisma_migrations
   0: migration_core::api::ApplyMigrations
             at migration-engine/core/src/api.rs:75

    at Object.<anonymous> (/Users/dtx/Dev/projects/EasyDesk/easydesk-back/node_modules/prisma/build/index.js:55412:26)
    at MigrateEngine.handleResponse (/Users/dtx/Dev/projects/EasyDesk/easydesk-back/node_modules/prisma/build/index.js:55286:38)
    at LineStream.<anonymous> (/Users/dtx/Dev/projects/EasyDesk/easydesk-back/node_modules/prisma/build/index.js:55370:18)
    at LineStream.emit (events.js:315:20)
    at LineStream.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at LineStream.Readable.push (internal/streams/readable.js:223:10)
    at LineStream.Transform.push (internal/streams/transform.js:166:32)
    at LineStream._pushBuffer (/Users/dtx/Dev/projects/EasyDesk/easydesk-back/node_modules/prisma/build/index.js:55126:19)
```

![image](https://user-images.githubusercontent.com/20479161/112736923-83c41000-8f67-11eb-947b-1a63b72d8387.png)

**Comment by DTX-92** [comment]
Okay. I've exceeded 10000 heroku row limit.
