### ISSUE TITLE
PANIC in query-engine\core\src\query_document\parser.rs:250:87called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by ChrisF999** [prisma/prisma#6487]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | windows            |
| Prisma Client   | 2.20.1             |
| Query Engine    | query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e|
| Database        | undefined|

## Query
```
mutation {
  createOneverified_emails(data: {
    u_id: 5e+23
    email: "X"
  }) {
    u_id
    email
  }
}
```

## Logs
```
treams/transform.js:166:32)
  prisma:engine     at LineStream._pushBuffer (C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules\@prisma\client\runtime\index.js:24158:19)
  prisma:engine     at LineStream._transform (C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules\@prisma\client\runtime\index.js:24152:10)  {"timestamp":"Apr 09 16:58:42.568","level":"ERROR","fields":{"message":"PANIC","reason":"called `Option::unwrap()` on a `None` value","file":"query-engine\\core\\src\\query_document\\parser.rs","line":250,"column":87},"target":"query_engine","span":{"scalar_type":"Int","name":"parse_scalar"},"spans":[{"name":"execute_single_operation"},{"name":"build"},{"name":"build_internal"},{"name":"parse_object"},{"name":"parse_arguments"},{"name":"parse_input_value"},{"name":"parse_input_object"},{"name":"parse_input_value"},{"scalar_type":"Int","name":"parse_scalar"}]}  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:18576
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 18576
  prisma:engine   }
  prisma:engine }  
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd: 'C:\\Users\\Khris\\Documents\\git\\KoalaBotFrontend\\prisma' }  
  prisma:engine Search for Query Engine in C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '18582' ] }  
  prisma:engine Client Version: 2.20.1  
  prisma:engine Engine Version: query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e  
  prisma:engine Active provider: sqlite  
  prisma:engine stdout  Starting a sqlite pool with 13 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:18582  
  prisma:engine Search for Query Engine in C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\core\src\query_document\parser.rs:250:87
called `Option::unwrap()` on a `None` value  
  prisma:engine TypeError: this.currentRequestPromise.cancel is not a function
  prisma:engine     at NodeEngine.handlePanic (C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules\@prisma\client\runtime\index.js:27023:36)
  prisma:engine     at NodeEngine.setError (C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules\@prisma\client\runtime\index.js:26969:16)
  prisma:engine     at LineStream.<anonymous> (C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules\@prisma\client\runtime\index.js:27259:24)
  prisma:engine     at LineStream.emit (events.js:315:20)
  prisma:engine     at addChunk (internal/streams/readable.js:309:12)
  prisma:engine     at readableAddChunk (internal/streams/readable.js:284:9)
  prisma:engine     at LineStream.Readable.push (internal/streams/readable.js:223:10)
  prisma:engine     at LineStream.Transform.push (internal/streams/transform.js:166:32)
  prisma:engine     at LineStream._pushBuffer (C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules\@prisma\client\runtime\index.js:24158:19)
  prisma:engine     at LineStream._transform (C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules\@prisma\client\runtime\index.js:24152:10)  {"timestamp":"Apr 09 16:58:42.918","level":"ERROR","fields":{"message":"PANIC","reason":"called `Option::unwrap()` on a `None` value","file":"query-engine\\core\\src\\query_document\\parser.rs","line":250,"column":87},"target":"query_engine","span":{"scalar_type":"Int","name":"parse_scalar"},"spans":[{"name":"execute_single_operation"},{"name":"build"},{"name":"build_internal"},{"name":"parse_object"},{"name":"parse_arguments"},{"name":"parse_input_value"},{"name":"parse_input_object"},{"name":"parse_input_value"},{"scalar_type":"Int","name":"parse_scalar"}]}  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
 const newEmail = await prisma.verified_emails.create({
    data: { u_id: req.body.u_id, email: req.body.email},
  });
```

## Schema
```prisma
datasource db {
  provider = "sqlite"
  url      = "file:C:/Users/Khris/Documents/git/Frontend/****/db.db"
}

generator client {
  provider = "prisma-client-js"
}

model verified_emails{
  u_id Int @id
  email String
}

```

**Comment by matthewmueller** [comment]
Just a guess: if you made u_id smaller (e.g. 100) can you reproduce this?

**Comment by ChrisF999** [comment]
If I reacall I did make it smaller but haven't been able to reproduce it since.

**Comment by pantharshit00** [comment]
I can reproduce the crash and changing the field to `BigInt` out of size error(note this looks like coming from protocol not from database):
![image](https://user-images.githubusercontent.com/22195362/114856897-4683cd00-9e05-11eb-97cd-5fcce2035f8a.png)

**Comment by matthewmueller** [comment]
Just did a couple tests based on [this answer](https://stackoverflow.com/questions/1685680/how-to-avoid-scientific-notation-for-large-numbers-in-javascript).

I'm assuming `5e+20` works, but not >= 21.

```
> JSON.stringify(5e+20)
'500000000000000000000'

> JSON.stringify(5e+21)
'5e+21'
```

---

Hey @ChrisF999, can you share why you need this? It's definitely a bug we'd like to fix eventually, but it'd be great to understand why one would need to set IDs this high.

**Comment by dguenther** [comment]
Possibly related to #10586.

**Comment by ChrisF999** [comment]
> Just did a couple tests based on [this answer](https://stackoverflow.com/questions/1685680/how-to-avoid-scientific-notation-for-large-numbers-in-javascript).
> 
> 
> 
> It looks like < 21 works, but not >= 21.
> 
> 
> 
> ```
> 
> > JSON.stringify(5e+20)
> 
> '500000000000000000000'
> 
> 
> 
> > JSON.stringify(5e+21)
> 
> '5e+21'
> 
> ```
> 
> 
> 
> And sending exponential notation causes the panic.
> 
> 
> 
> A possible workaround is to try sending it as a BigInt.
> 
> 
> 
> ---
> 
> 
> 
> Hey @ChrisF999, can you share how you ran into this? It's definitely a bug we'd like to fix eventually, but it'd be great to understand your context a bit better.

Not sure how I missed this the ID numbers are discord ID numbers either user, message or guild I can't quite recall.

**Comment by dpetrick** [comment]
Duplicate of https://github.com/prisma/prisma/issues/10586
