### ISSUE TITLE
Using current CLI and older Client `generate` gives `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object` or `TypeError: outputDir.endsWith is not a function` error and no helpful output

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6535]
## Bug description

When using a current CLI but an older Client, `generate` outputs the following for me:

@prisma/client@2.16.0:
```
λ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at Object.join (node:path:397:7)
    at getDotPrismaDir (C:\Users\Jan\Documents\throwaway\endsWithRepro\node_modules\@prisma\client\generator-build\index.js:72856:33)
    at Object.generateClient (C:\Users\Jan\Documents\throwaway\endsWithRepro\node_modules\@prisma\client\generator-build\index.js:72878:49)
    at Object.onGenerate (C:\Users\Jan\Documents\throwaway\endsWithRepro\node_modules\@prisma\client\generator-build\index.js:78167:34)
    at LineStream.<anonymous> (C:\Users\Jan\Documents\throwaway\endsWithRepro\node_modules\@prisma\client\generator-build\index.js:2802:40)
    at LineStream.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
```

@prisma/client@2.19.0:

```
Error:
TypeError: outputDir.endsWith is not a function
    at getDotPrismaDir (C:\Users\Jan\Documents\throwaway\endsWithRepro\node_modules\@prisma\client\generator-build\index.js:36836:19)
    at generateClient (C:\Users\Jan\Documents\throwaway\endsWithRepro\node_modules\@prisma\client\generator-build\index.js:36872:49)
    at Object.onGenerate (C:\Users\Jan\Documents\throwaway\endsWithRepro\node_modules\@prisma\client\generator-build\index.js:39932:53)
    at LineStream.<anonymous> (C:\Users\Jan\Documents\throwaway\endsWithRepro\node_modules\@prisma\client\generator-build\index.js:2846:40)
    at LineStream.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at LineStream.Readable.push (node:internal/streams/readable:227:10)
    at LineStream._pushBuffer (C:\Users\Jan\Documents\throwaway\endsWithRepro\node_modules\@prisma\client\generator-build\index.js:1115:19)
    at LineStream._transform (C:\Users\Jan\Documents\throwaway\endsWithRepro\node_modules\@prisma\client\generator-build\index.js:1109:10)
```

## How to reproduce

1. Create folder
2. `npm init -y`
3. `npm install prisma @prisma/client@2.16.0` or `npm install prisma @prisma/client@2.19.0`
4. `npx prisma init`
5. Add minimal model to schema file:
   ```
   model User {
    id    Int     @id @default(autoincrement())
    email String  @unique
    name  String?
   }
   ```
6. Run `npx prisma generate`
7. See error.

## Expected behavior

Get some helpful warning of not using different versions for CLI and Client.

## Environment & setup

```
λ npx prisma -v
Environment variables loaded from .env
prisma               : 2.20.1
@prisma/client       : 2.16.0
Current platform     : windows
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```
or

```
λ npx prisma -v
Environment variables loaded from .env
prisma               : 2.20.1
@prisma/client       : 2.19.0
Current platform     : windows
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by pantharshit00** [comment]
I can confirm this. 

![image](https://user-images.githubusercontent.com/22195362/114527455-a2175480-9c65-11eb-99b4-64acd5ccb083.png)

**Comment by matthewmueller** [comment]
Next Steps:

- For this case: throw an error with a minimum version requirement for the runtime
- Consider: turning the warning into an error
