### ISSUE TITLE
My Prisma Client just crashed.

### ISSUE THREAD

**Issue by nshusr** [prisma/prisma#6593]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | darwin             |
| Prisma Client   | 2.19.0             |
| Query Engine    | query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d|
| Database        | postgresql |

## Query
```
mutation {
  createOneSyncPlan(data: {
    name: "X"
    type: DAY
    status: ENABLE
    fieldsType: DEFAULT_BASE
    syncCron: "X"
    groupBy: {
      set: [STAT_GROUP_BY_ADVERTISER_ID]
    }
    advertisers: {
      connect: [
        {
          id: 5
        }
      ]
    }
    integrateWorkbook: {
      connect: {
        id: 5
      }
    }
    user: {
      connect: {
        id: 5
      }
    }
  }) {
    id
    name
    type
    status
    fieldsType
    fields
    startDate
    endDate
    groupBy
    timeGranularity
    syncPlanFilteringId
    orderField
    orderType
    sendCron
    syncCron
    sendEmails
    integrateWorkbookId
    userId
  }
}
```

## Logs
```
[0mExecution permissions of /Users/mac/code/oe-tr-be-prisma/node_modules/.pnpm/@prisma+client@2.19.0_prisma@2.19.0/node_modules/.prisma/client/query-engine-darwin are fine  +1m
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '58936' ] }  
  prisma:engine stdout  Starting a postgresql pool with 13 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:58936  
  prisma:engine Search for Query Engine in /Users/mac/code/oe-tr-be-prisma/node_modules/.pnpm/@prisma+client@2.19.0_prisma@2.19.0/node_modules/.prisma/client  
  plusX Execution permissions of /Users/mac/code/oe-tr-be-prisma/node_modules/.pnpm/@prisma+client@2.19.0_prisma@2.19.0/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.19.0  
  prisma:engine Engine Version: query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/7d3753e/postgres-types/src/lib.rs:760:18
expected array type  
  prisma:engine TypeError: this.currentRequestPromise.cancel is not a function
  prisma:engine     at NodeEngine.handlePanic (/Users/mac/code/oe-tr-be-prisma/node_modules/.pnpm/@prisma+client@2.19.0_prisma@2.19.0/node_modules/@prisma/client/runtime/index.js:29249:36)
  prisma:engine     at NodeEngine.setError (/Users/mac/code/oe-tr-be-prisma/node_modules/.pnpm/@prisma+client@2.19.0_prisma@2.19.0/node_modules/@prisma/client/runtime/index.js:29195:16)
  prisma:engine     at LineStream.<anonymous> (/Users/mac/code/oe-tr-be-prisma/node_modules/.pnpm/@prisma+client@2.19.0_prisma@2.19.0/node_modules/@prisma/client/runtime/index.js:29480:24)
  prisma:engine     at LineStream.emit (events.js:315:20)
  prisma:engine     at addChunk (internal/streams/readable.js:309:12)
  prisma:engine     at readableAddChunk (internal/streams/readable.js:284:9)
  prisma:engine     at LineStream.Readable.push (internal/streams/readable.js:223:10)
  prisma:engine     at LineStream.Transform.push (internal/streams/transform.js:166:32)
  prisma:engine     at LineStream._pushBuffer (/Users/mac/code/oe-tr-be-prisma/node_modules/.pnpm/@prisma+client@2.19.0_prisma@2.19.0/node_modules/@prisma/client/runtime/index.js:26388:19)
  prisma:engine     at LineStream._transform (/Users/mac/code/oe-tr-be-prisma/node_modules/.pnpm/@prisma+client@2.19.0_prisma@2.19.0/node_modules/@prisma/client/runtime/index.js:26382:10)
  prisma:engine     at LineStream.Transform._read (internal/streams/transform.js:205:10)
  prisma:engine     at LineStream.Transform._write (internal/streams/transform.js:193:12)
  prisma:engine     at writeOrBuffer (internal/str

**Comment by nshusr** [comment]
This error appeared in
1. I started to specify an enum type data to synchronize the schema in schema.prisma
2. Delete some attributes in the enum type again, and db push will fail again
3. The synchronization can be successful by executing the migration, but the operation will report an error `/root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/7d3753e/postgres-types/src/lib.rs:760:18\nexpected array type \n\nThis is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.`
4. When I try to use db push to synchronize the schema again, the following error is output
```
database: db error: ERROR: column "groupBy" cannot be cast automatically to type "IntegrateSyncPlanGroupBy"[]
HINT: You might need to specify "USING "groupBy"::"IntegrateSyncPlanGroupBy"[]".
   0: sql_migration_connector::sql_database_step_applier::apply_migration
             at migration-engine/connectors/sql-migration-connector/src/sql_database_step_applier.rs:14
   1: migration_core::api::SchemaPush
             at migration-engine/core/src/api.rs:165
```

It seems that the enum type is broken

**Comment by nshusr** [comment]
I first comment out the enumeration type and re db push
Then open the enumeration type and successfully solve the db push problem

**Comment by pantharshit00** [comment]
Hey @nshusr 

Can you please share your schema or the enum part of the schema which you changed which caused this issue? That will help us reproducing this.

**Comment by nshusr** [comment]
@pantharshit00 

Type in this sample

schema.prisma
```
enum IntegrateSyncPlanGroupBy {
  STAT_GROUP_BY_A_ID
  STAT_GROUP_BY_B_ID
  STAT_GROUP_BY_C_ID
  STAT_GROUP_BY_E_NAME
}
model SyncPlan {
  id                  Int                              @id @default(autoincrement())
  name                String                           @unique
  groupBy             IntegrateSyncPlanGroupBy[]
}
```

**Comment by pantharshit00** [comment]
Hey @nshusr 

Can you please try this again with the latest version? I wasn't able to reproduce this with `2.23.0-dev.27`

**Comment by nshusr** [comment]
I just tested the postgresql database
Adjust enum type field
The following error message appeared

schema.prisma
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

enum IntegrateSyncPlanGroupBy {
  STAT_GROUP_BY_A_ID
  STAT_GROUP_BY_B_ID
  STAT_GROUP_BY_C_ID
  // STAT_GROUP_BY_E_NAME
  // STAT_GROUP_BY_F_AG
}

model SyncPlan {
  id      Int                        @id @default(autoincrement())
  name    String                     @unique
  groupBy IntegrateSyncPlanGroupBy[]
}
```
step
1.  `pnpx prisma db push`
2.  enable `
  // STAT_GROUP_BY_E_NAME
  // STAT_GROUP_BY_F_AG` field
3. `pnpx prisma db push`

error response
```
Environment variables loaded from prisma/.env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "enumTest", schema "public" at "localhost:5432"
Error: Database error
Error querying the database: db error: ERROR: column "groupBy" cannot be cast automatically to type "IntegrateSyncPlanGroupBy"[]
HINT: You might need to specify "USING "groupBy"::"IntegrateSyncPlanGroupBy"[]".
   0: sql_migration_connector::sql_database_step_applier::apply_migration
             at migration-engine/connectors/sql-migration-connector/src/sql_database_step_applier.rs:15
   1: migration_core::api::SchemaPush
             at migration-engine/core/src/api.rs:163
```

**Comment by nshusr** [comment]
use 2.23.0-dev.27
![image](https://user-images.githubusercontent.com/45023042/118424293-8df9c380-b6f9-11eb-8915-9316a1ba377e.png)

**Comment by pantharshit00** [comment]
I am still unable to reproduce this. Can you please share which postgres version you are using? 

I used `2.24.0-dev.23` for the reproduction

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
