### ISSUE TITLE
Error after upgrade to v2.21.2

### ISSUE THREAD

**Issue by AndrewAllison** [prisma/prisma#6649]
On upgrading my current project from version 2.19.0 to 2.21.2, when I try to run `npx prisma db push --preview-feature`

I get the following error if I revert to 2.19.0 everything works fine. 

```bash
Prisma schema loaded from prisma\schema.prisma
Error: 
✔ Generated Prisma Client (2.21.2) to .\node_modules\@prisma\client in 702ms

AssertionError [ERR_ASSERTION]: prismaClientOutput
    at generate (\node_modules\prisma-nestjs-graphql\index.js:798:20)
    at Object.onGenerate (\node_modules\prisma-nestjs-graphql\index.js:1001:27)
    at LineStream.<anonymous> (\node_modules\@prisma\generator-helper\dist\generatorHandler.js:13:46)
    at LineStream.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at LineStream.Readable.push (_stream_readable.js:214:10)
    at LineStream.Transform.push (_stream_transform.js:152:32)
    at LineStream._pushBuffer (\node_modules\@prisma\generator-helper\dist\byline.js:108:23)
    at LineStream._transform (node_modules\@prisma\generator-helper\dist\byline.js:100:10)


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aquinas-api@1.0.10 prisma:generate: `prisma generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aquinas-api@1.0.10 prisma:generate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     \AppData\Roaming\npm-cache\_logs\2021-04-20T05_36_30_522Z-debug.log

Process finished with exit code 1
```

Logs Show
```bash
10 silly lifecycle aquinas-api@1.0.10~prisma:generate: Args: [ '/d /s /c', 'prisma generate' ]
11 silly lifecycle aquinas-api@1.0.10~prisma:generate: Returned: code: 1  signal: null
12 info lifecycle aquinas-api@1.0.10~prisma:generate: Failed to exec prisma:generate script
13 verbose stack Error: aquinas-api@1.0.10 prisma:generate: `prisma generate`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (\AppData\Roaming\nvm\v12.19.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (\AppData\Roaming\nvm\v12.19.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

It appears to be related to hapi/jpi from what I can gather based on https://stackoverflow.com/a/56433901/316657 

OS: Windows 10
NPM: 6.14.8
NODE: v12.19.0

Any help would be appreciated.

**Comment by pantharshit00** [comment]
Hey @AndrewAllison 

Can you provide a reproduction for this? Also, try upgrading your node version once.

**Comment by janpio** [comment]
Did you upgrade both Prisma CLI and Prisma Client @AndrewAllison? It would be helpful if you could post your `prisma -v` output when you have the project in the state that it is failing.

**Comment by AndrewAllison** [comment]
Hey thanks for the quick replies, I'm so sorry it's taken me till now to follow up with you after such quick responses.

I was trying to deliver a reproduction as per @pantharshit00 when I remembered we use a library called `prisma-nestjs-graphql` I've updated this to version 11.2.0 as well as the prisma client and cli to 2.21.0 and everythign now seems to be playing nicely.

Thanks again

**Comment by janpio** [comment]
It took you just a few hours, that is totally fine. Great this is fixed!
