### ISSUE TITLE
Inserting nan value via parameterized queries for negative float values

### ISSUE THREAD

**Issue by nimish-gupta** [prisma/prisma#6663]
## Bug description

So after inserting negative numbers under the float type column using raw queries, Prisma is storing them in DB as `nan` type. It should store them as float only. 

## How to reproduce

- Run the following script via node.
```
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const VALUE = -2000;

async function main() {
	await prisma.$connect();

	await prisma.$queryRaw(
		`INSERT INTO test(id, float_value) VALUES(
                        md5(random()::text || clock_timestamp()::text)::uuid,$1
                 )`,
		VALUE
	);

       console.log("raw-output", await prisma.$queryRaw('SELECT * FROM test'));
       console.log("error");
       const test = await prisma.test.findMany();  
}

main();
```

## Current behavior
It is throwing error
```
raw-output, [ { id: '8ed82704-f26d-0bea-b09f-b219432d8e5c', float_value: null } ] 

error - 
Invalid `prisma.test.findMany()` invocation:

  Inconsistent column data: Could not convert value NaN of the field `float_value` to type `Float`.
    at cb (/prisma-bug/node_modules/@prisma/client/runtime/index.js:34780:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/prisma-bug/src/index.js:17:15)
```

## Expected behavior
It should insert float value as provided(-2000) instead of `nan` in the database.

## Prisma information
- Prisma schema

```
generator client {
  provider = "prisma-client-js"
}

datasource postgresql {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Test {
  id         String @id @default(uuid())
  floatValue Float  @map("float_value")

  @@map("test")
}
```
- Prisma Debug info
```
prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables loaded from /prisma-bug/src/.env +1ms
[dotenv][DEBUG] did not match key and value when parsing line 2: 
  prisma:tryLoadEnv Environment variables not found at null +2ms
  prisma:tryLoadEnv Environment variables loaded from /prisma-bug/src/.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 2: 
[dotenv][DEBUG] "DATABASE_URL" is already defined in `process.env` and will not be overwritten
  prisma:client clientVersion: 2.21.2 +0ms
  prisma:engine { cwd: '/prisma-bug/src' } +0ms
  prisma:engine Search for Query Engine in /prisma-bug/node_modules/.prisma/client +2ms
  prisma:engine Search for Query Engine in /prisma-bug/node_modules/.prisma/client +0ms
  plusX Execution permissions of /prisma-bug/node_modules/.prisma/client/query-engine-darwin are fine +0ms
  plusX Execution permissions of /prisma-bug/node_modules/.prisma/client/query-engine-darwin are fine +10ms
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '64569' ] } +46ms
  prisma:engine stdout Starting a postgresql pool with 17 connections. +14ms
  prisma:engine stdout Started http server on http://127.0.0.1:64569 +13ms
  prisma:engine Search for Query Engine in /prisma-bug/node_modules/.prisma/client +1ms
  prisma:client prisma.queryRaw(INSERT INTO test(id, float_value) VALUES(
  prisma:client         md5(random()::text || clock_timestamp()::text)::uuid,$1
  prisma:client       ), [-2000]) +79ms
  prisma:client Prisma Client call: +0ms
  prisma:client Prisma Client call: +4ms
  prisma:client prisma.queryRaw({
  prisma:client   query: 'INSERT INTO test(id, float_value) VALUES(\n        md5(random()::text || clock_timestamp()::text)::uuid,$1\n      )',
  prisma:client   parameters: {
  prisma:client     values: '[-2000]',
  prisma:client     __prismaRawParamaters__: true
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +29ms
  prisma:client mutation {
  prisma:client   queryRaw(
  prisma:client     query: "INSERT INTO test(id, float_value) VALUES(\n        md5(random()::text || clock_timestamp()::text)::uuid,$1\n      )"
  prisma:client     parameters: "[-2000]"
  prisma:client   )
  prisma:client }
  prisma:client  +0ms
  plusX Execution permissions of /prisma-bug/node_modules/.prisma/client/query-engine-darwin are fine +104ms
  prisma:engine Client Version: 2.21.2 +50ms
  prisma:engine Engine Version: query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d +0ms
  prisma:engine Active provider: postgresql +0ms
```

## Environment & setup

- OS: Mac OS Big Sur v11.2.3
- Database: PostgreSQL 13.1
- Node.js version: v14.15.0
- Prisma version:
```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by pantharshit00** [comment]
Related to https://github.com/prisma/prisma/issues/3492

**Comment by nimish-gupta** [comment]
An update on this we are only getting errors when we are storing negative values in a float type column via raw query. Updated the description too.

**Comment by pantharshit00** [comment]
This is not easy to fix as that will require us to introduce a `Nan` type in the engine.

**Comment by SevInf** [comment]
Can confirm that prisma 3.0.5 inserted NaN numbers instead of negatives into the table.
As of 3.4.1 this is no longer reproduces and appears to be fixed.
