### ISSUE TITLE
Error in PostgreSQL connection: Error { kind: Closed, cause: None }

### ISSUE THREAD

**Issue by eduhenke** [prisma/prisma#6664]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.18.4           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.19.0             |
| Query Engine    | query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d|
| Database        | undefined|

## Query
```
query {
  findUniqueStation(where: {
    id: "X"
  }) {
    id
    companyId
    name
    qrCode
    compressedId
    canControl
    energyPrice
    status
    statusWhenOnline
    tag
    description
    unlockMethods
    errorCode
    errorCodeWhenOnline
    addressCity
    addressState
    lastHeartbeatTime
    openingHours
    reservable
    ocppVersion
    ocppUrl
    ocppPublicAccessAllowed
    chargePointId
    configPortal_url
    configPortal_user
    configPortal_password
    routerPortal_url
    routerPortal_user
    routerPortal_password
    images
    createdAt
    firstConnectedAt
    connectedAt
    lastVersion
    newestEventTimestamp
    normalizedPartnerCompanies
    normalizedName
    normalizedAddressCity
    normalizedAddressState
    normalizedSearchString
    connectors(orderBy: [
      {
        id: asc
      }
    ]) {
      id
      status
      statusWhenOnline
      power
      stationId
      companyId
      type
      errorCode
      errorCodeWhenOnline
      newestEventTimestamp
    }
    address {
      id
      stationId
      city
      country
      neighborhood
      postalCode
      state
      street
      streetNumber
    }
    coordinates {
      id
      stationId
      latitude
      longitude
    }
  }
}
```

## Logs
```
asks+%28%3Canonymous%3E%29%0A++++++at+processTicksAndRejections+%28internal%2Fprocess%2Ftask_queues.js%3A97%3A5%29+%7B%0A++++clientVersion%3A+%272.19.0%27%0A++%7D%0A%7D%0Aprisma%3Aengine+stdout++Unknown+error%0Aprisma%3Aengine+stdout++Fetched+a+connection+from+the+pool%0Aprisma%3Aengine+stdout++Unknown+error%0Aprisma%3Aengine+stdout++Fetched+a+connection+from+the+pool%0Aprisma%3Aengine+%7B%0A++error%3A+PrismaClientUnknownRequestError2+%5BPrismaClientUnknownRequestError%5D%3A+Error+in+connector%3A+Error+querying+the+database%3A+connection+closed%0A++++++at+NodeEngine.graphQLToJSError+%28%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A29799%3A14%29%0A++++++at+NodeEngine.request+%28%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A29695%3A24%29%0A++++++at+runMicrotasks+%28%3Canonymous%3E%29%0A++++++at+processTicksAndRejections+%28internal%2Fprocess%2Ftask_queues.js%3A97%3A5%29+%7B%0A++++clientVersion%3A+%272.19.0%27%0A++%7D%0A%7D%0Aprisma%3Aengine+stdout++Unknown+error%0Aprisma%3Aengine+stdout++Fetched+a+connection+from+the+pool%0Aprisma%3Aengine+%7B%0A++error%3A+PrismaClientUnknownRequestError2+%5BPrismaClientUnknownRequestError%5D%3A+Error+in+connector%3A+Error+querying+the+database%3A+connection+closed%0A++++++at+NodeEngine.graphQLToJSError+%28%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A29799%3A14%29%0A++++++at+NodeEngine.request+%28%2Fusr%2Fsrc%2Fapp%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A29695%3A24%29%0A++++++at+runMicrotasks+%28%3Canonymous%3E%29%0A++++++at+processTicksAndRejections+%28internal%2Fprocess%2Ftask_queues.js%3A97%3A5%29+%7B%0A++++clientVersion%3A+%272.19.0%27%0A++%7D%0A%7D%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A&title=Error+in+PostgreSQL+connection%3A+Error+%7B+kind%3A+Closed%2C+cause%3A+None+%7D&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at NodeEngine.throwAsyncErrorIfExists (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29776:21)
    at NodeEngine.handleRequestError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29115:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NodeEngine.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29710:9)
prisma:engine stdout  Unknown error
prisma:engine stdout  Fetched a connection from the pool
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    clientVersion: '2.19.0'
  }
}
prisma:engine stdout  Unknown error
prisma:engine stdout  Fetched a connection from the pool
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    clientVersion: '2.19.0'
  }
}
prisma:engine stdout  Unknown error
prisma:engine stdout  Fetched a connection from the pool
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29799:14)
      at NodeEngine.request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:29695:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    clientVersion: '2.19.0'
  }
}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
    const station = await this.prisma.station.findUnique({
      where: {
        compressedId: where.compressedStationId,
        id: where.stationId,
        qrCode: where.qrCode,
      },
      include,
    });
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Connector {
  id                   Int
  status               ConnectorStatus   @default(UNKNOWN)
  statusWhenOnline     ConnectorStatus   @default(AVAILABLE)
  power                Int
  stationId            String
  companyId            String
  type                 ConnectorType
  errorCode            StationErrorCode? @default(NoSignal)
  errorCodeWhenOnline  StationErrorCode?
  station              Station           @relation(fields: [stationId], references: [id])
  newestEventTimestamp DateTime          @default(now())

  @@id([stationId, id])
}

model StreamEvent {
  streamId      String
  streamVersion Int
  type          String
  timestamp     DateTime
  data          Json

  Session   Session? @relation(fields: [sessionId], references: [id])
  sessionId String?
  Station   Station? @relation(fields: [stationId], references: [id])
  stationId String?
  @@id([streamId, streamVersion])
}

model Session {
  id                  String              @id
  userId              Int
  stationId           String
  companyId           String
  connectorId         Int?
  chargingCardId      String?
  status              SessionStatus       @default(WAITING_PLUG)
  station             Station             @relation(fields: [stationId], references: [id])
  stationName         String              @default("") // Just for sorting 
  stationAddressCity  String? // Just for sorting
  stationAddressState String? // Just for sorting 
  checked             Boolean             @default(false)
  meterStart          Int?
  createdAt           DateTime            @default(now())
  startedChargingAt   DateTime?
  stoppedChargingAt   DateTime?
  finishedAt          DateTime?
  chargePrice         Float               @default(0)
  // in Wh
  energyConsumed      Int                 @default(0)
  // in seconds
  timeCharging        Int                 @default(0)
  energyMeasurements  EnergyMeasurement[]
  remote              Boolean
  updatedAt           DateTime            @updatedAt
  events              StreamEvent[]
  lastVersion         Int                 @default(0)

  //workaround for filter
  normalizedStationName         String  @default("")
  normalizedStationAddressCity  String?
  normalizedStationAddressState String?
}

model EnergyMeasurement {
  id        String   @id @default(uuid())
  sessionId String
  timestamp DateTime
  value     Float
  session   Session  @relation(fields: [sessionId], references: [id])
}

model Address {
  id           String  @id @default(uuid())
  stationId    String
  city         String
  country      String
  neighborhood String
  postalCode   String
  state        String
  street       String
  streetNumber String
  station      Station @relation(fields: [stationId], references: [id])
}

model Coordinates {
  id        String  @id @default(uuid())
  stationId String
  latitude  Float
  longitude Float
  station   Station @relation(fields: [stationId], references: [id])
}

model Station {
  id                  String            @id
  companyId           String
  name                String            @default("")
  qrCode              String            @unique
  compressedId        String            @unique
  canControl          Boolean           @default(false)
  energyPrice         Float             @default(0)
  status              StationStatus     @default(UNKNOWN)
  statusWhenOnline    StationStatus     @default(AVAILABLE)
  tag                 String?
  description         String            @default("")
  unlockMethods       UnlockMethod[]
  errorCode           StationErrorCode? @default(NoSignal)
  errorCodeWhenOnline StationErrorCode?
  coordinates         Coordinates?
  address             Address?
  addressCity         String? // Just for sorting
  addressState        String? // Just for sorting
  lastHeartbeatTime   DateTime?
  openingHours        String?

  //station reservation properties
  reservable Boolean @default(false)

  ocppVersion             OCPPVersion?
  ocppUrl                 String?
  ocppPublicAccessAllowed Boolean      @default(false)
  chargePointId           String


  // prisma dislikes two references to the same type :'(
  configPortal_url      String?
  configPortal_user     String?
  configPortal_password String?
  routerPortal_url      String?
  routerPortal_user     String?
  routerPortal_password String?

  images           String[]
  connectors       Connector[]
  sessions         Session[]
  events           StreamEvent[]
  createdAt        DateTime
  firstConnectedAt DateTime?
  connectedAt      DateTime?

  lastVersion          Int      @default(0)
  newestEventTimestamp DateTime @default(now())

  //workaroud for filtering
  normalizedPartnerCompanies String  @default("[]")
  //workaround for sorting
  normalizedName             String  @default("")
  normalizedAddressCity      String?
  normalizedAddressState     String?
  normalizedSearchString     String?
}

enum OCPPVersion {
  V15
  V16
}

enum ConnectorStatus {
  AVAILABLE // The connector is able to start a new charging session.
  PREPARING // When a Connector becomes no longer available for a new user but no charging session is active.
  CHARGING // The connector is in use.
  FINISHING // When a charging session has stopped at a Connector, but the Connector is not yet available, e.g. the cable has not been unplugged
  INOPERATIVE // The connector is not functioning
  UNKNOWN // No status information available (also used when offline).
  RESERVED // The connector is reserved for a particular EV driver and is unavailable for other drivers. Still not supported
}

enum ConnectorType {
  CHADEMO
  J1772
  TESLA
  TYPE1CCS
  TYPE2
  TYPE2CCS
  TYPE3
  WALL
}

enum SessionStatus {
  WAITING_PLUG
  TIMED_OUT
  CHARGING
  WAITING_UNPLUG
  FINISHED
  ERROR
}

enum StationStatus {
  AVAILABLE // The station is able to start a new charging session.
  CHARGING // The station is in use.
  INOPERATIVE // The station is not functioning
  UNKNOWN // No status information available (also used when offline).
  PLANNED // The station is planned, will be operating soon. Still not supported
  RESERVED // The station is reserved for a particular EV driver and is unavailable for other drivers. Still not supported
}

enum StationErrorCode {
  // Coming directly from OCPP
  ConnectorLockFailure // Failure to lock or unlock connector.
  EVCommunicationError // Communication failure with the vehicle, might be Mode 3 or other communication protocol problem. This is not a real error in the sense that the Charge Point doesn’t need to go to the faulted state. Instead, it should go to the SuspendedEVSE state.
  GroundFailure // Ground fault circuit interrupter has been activated.
  HighTemperature // Temperature inside Charge Point is too high.
  InternalError // Error in internal hard- or software component.
  LocalListConflict // The authorization information received from the Central System is in conflict with the LocalAuthorizationList.
  NoError // No error to report.
  OtherError // Other type of error. More information in vendorErrorCode.
  OverCurrentFailure // Over current protection device has tripped.
  OverVoltage // Voltage has risen above an acceptable level.
  PowerMeterFailure // Failure to read electrical/energy/power meter.
  PowerSwitchFailure // Failure to control power switch.
  ReaderFailure // Failure with idTag reader.
  ResetFailure // Unable to perform a reset.
  UnderVoltage // Voltage has dropped below an acceptable level.
  WeakSignal // Wireless communication device reports a weak signal.

  NoSignal // This error appears when the station could not be communicated(it is inferred)
  EmergencyButtonPressed
}

enum UnlockMethod {
  ChargingCard
  Remote
}

```

**Comment by janpio** [comment]
Hi @eduhenke. We improved the handling of these kinds of errors a lot in the more recent versions of Prisma CLI and Prisma Client. Can you please try upgrading your dependencies and see if the error still occurs? Thanks.

**Comment by eduhenke** [comment]
Sure, will update and them will report back with the problem

**Comment by pantharshit00** [comment]
@eduhenke Any updates?
