### ISSUE TITLE
PANIC in query-engine/core/src/response_ir/internal.rs:395:26Application logic invariant error: received null value for field photos which may not be null

### ISSUE THREAD

**Issue by jorgeleal12** [prisma/prisma#6673]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.21.2             |
| Query Engine    | query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d|
| Database        | undefined|

## Query
```
query {
  findManyphotos_service {
    idphotos_service
    type_inspection
    photos {
      idphotos
      name_photo
      quantity
      min
    }
  }
}
```

## Logs
```
rmissions of /home/aleal/Documents/proyectos/BackendJs/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +9s
  prisma:engine {
  prisma:engine   flags: [
  prisma:engine     '--enable-experimental=selectRelationCount',
  prisma:engine     '--enable-raw-queries',
  prisma:engine     '--port',
  prisma:engine     '35007'
  prisma:engine   ]
  prisma:engine }  
  prisma:engine stdout  Starting a mysql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:35007  
  prisma:engine Search for Query Engine in /home/aleal/Documents/proyectos/BackendJs/node_modules/.prisma/client  
  plusX Execution permissions of /home/aleal/Documents/proyectos/BackendJs/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine Client Version: 2.21.2  
  prisma:engine Engine Version: query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in query-engine/core/src/response_ir/internal.rs:395:26
Application logic invariant error: received null value for field photos which may not be null  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/home/aleal/Documents/proyectos/BackendJs/node_modules/@prisma/client/runtime/index.js:25205:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:467:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:35007
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -111,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 35007
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/home/aleal/Documents/proyectos/BackendJs/prisma' }  
  prisma:engine Search for Query Engine in /home/aleal/Documents/proyectos/BackendJs/node_modules/.prisma/client  
  plusX Execution permissions of /home/aleal/Documents/proyectos/BackendJs/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine {
  prisma:engine   flags: [
  prisma:engine     '--enable-experimental=selectRelationCount',
  prisma:engine     '--enable-raw-queries',
  prisma:engine     '--port',
  prisma:engine     '38321'
  prisma:engine   ]
  prisma:engine }  
  prisma:engine stdout  Starting a mysql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:38321  
  prisma:engine Search for Query Engine in /home/aleal/Documents/proyectos/BackendJs/node_modules/.prisma/client  
  plusX Execution permissions of /home/aleal/Documents/proyectos/BackendJs/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine Client Version: 2.21.2  
  prisma:engine Engine Version: query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in query-engine/core/src/response_ir/internal.rs:395:26
Application logic invariant error: received null value for field photos which may not be null  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/home/aleal/Documents/proyectos/BackendJs/node_modules/@prisma/client/runtime/index.js:25205:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:467:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE

model photos {
  idphotos       Int              @id @default(autoincrement())
  name_photo     String
  quantity       Int
  min            Int
  photos_service photos_service[]
}

model photos_service {
  idphotos_service Int             @id @default(autoincrement())
  photos           photos          @relation(fields: [photos_idphotos], references: [idphotos])
  photos_idphotos  Int
  type_inspections type_inspection @relation(fields: [type_inspection], references: [idtype_inspection])
  type_inspection  Int
}****

**Comment by jorgeleal12** [comment]
model photos {
  idphotos       Int              @id @default(autoincrement())
  name_photo     String
  quantity       Int
  min            Int
  photos_service photos_service[]
}

model photos_service {
  idphotos_service Int             @id @default(autoincrement())
  photos           photos          @relation(fields: [photos_idphotos], references: [idphotos])
  photos_idphotos  Int
  type_inspections type_inspection @relation(fields: [type_inspection], references: [idtype_inspection])
  type_inspection  Int
}

**Comment by jorgeleal12** [comment]
Solución 
const result = await this.prisma.$queryRaw`SELECT * FROM photos_service LEFT JOIN photos ON photos_service.photos_idphotos = photos.idphotos`;

**Comment by janpio** [comment]
Can you share the Prisma Client query that you tried to send before you found the workaround of using a raw query @jorgeleal12? Prisma should never crash in such a situation with such a messge.

**Comment by janpio** [comment]
5 months later no further information, so I think we can consider this solved.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
