### ISSUE TITLE
Error: [libs/datamodel/connectors/dml/src/model.rs:161:64] Could not find relation field clubs_clubsTousers on model User. 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#6737]
Command: `prisma introspect`
Version: `2.21.2`
Binary Version: `e421996c87d5f3c8f7eeadd502d4ad402c89464d`
Report: https://prisma-errors.netlify.app/report/13240 
OS: `x64 linux 5.8.0-50-generic`

JS Stacktrace:
```
Error: [libs/datamodel/connectors/dml/src/model.rs:161:64] Could not find relation field clubs_clubsTousers on model User.
    at ChildProcess.<anonymous> (/home/yanpro/_SparkRead/deploy/node_modules/prisma/build/index.js:39953:28)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
   0: user_facing_errors::Error::new_in_panic_hook
   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   6: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   7: core::option::expect_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1292:5
   8: dml::model::Model::find_relation_field_mut
   9: sql_introspection_connector::re_introspection::enrich
  10: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  14: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  15: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  16: introspection_engine::main::{{closure}}
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: introspection_engine::main
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
  20: std::rt::lang_start::{{closure}}
  21: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
      std::rt::lang_start_internal
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51:25
  22: std::rt::lang_start
  23: __libc_start_main
  24: <unknown>

```

**Comment by tomhoule** [comment]
Related: 13240

**Comment by tomhoule** [comment]
Other occurrence: https://prisma-errors.netlify.app/report/13285

**Comment by tomhoule** [comment]
New occurrence: https://prisma-errors.netlify.app/report/13436

Worth noting that this one is on cockroachdb.
