### ISSUE TITLE
Error: [libs/sql-schema-describer/src/lib.rs:150:32] Column user_id not found in Table am_user 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#6739]
Command: `prisma introspect`
Version: `2.20.1`
Binary Version: `60ba6551f29b17d7d6ce479e5733c70d9c00860e`
Report: https://prisma-errors.netlify.app/report/13197 
OS: `x64 linux 4.19.62-mod-std-ipv6-64-rescue`

JS Stacktrace:
```
Error: [libs/sql-schema-describer/src/lib.rs:150:32] Column user_id not found in Table am_user
    at ChildProcess.child.on (/<...>/node_modules/prisma/build/index.js:39909:28)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

Rust Stacktrace:
```
   0: user_facing_errors::Error::new_in_panic_hook
   1: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   5: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   6: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   7: sql_schema_describer::Table::column_bang::{{closure}}
   8: sql_schema_describer::Table::column_bang
   9: sql_introspection_connector::introspection::introspect
  10: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  14: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  15: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  16: introspection_engine::main::{{closure}}
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: introspection_engine::main
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
  20: std::rt::lang_start::{{closure}}
  21: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
      std::rt::lang_start_internal
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51:25
  22: std::rt::lang_start
  23: __libc_start_main
             at /root/glibc-2.18/csu/libc-start.c:269
  24: <unknown>

```

**Comment by tomhoule** [comment]
Related: 13211

**Comment by pimeys** [comment]
The error report is missing details to fix the bug:

- Only one table in the data model
- The schema JSON misses certain columns, such as the `user_id` from the `am_user` table

It's quite hard to reproduce this without having more info. An SQL dump would be great.

**Comment by janpio** [comment]
The error report presents what was present for the using when running `prisma introspect`. The Prisma schema had 1 model, and the database included the schema represented by what we have as "Schema Dump". 

Is it possible the user's database actually defined a PK on `user_id` although that column does not even exist?

(Similar situation seems to be present in https://prisma-errors.netlify.app/report/13211 which @tomhoule mentioned above (which comes from the same user))

**Comment by pimeys** [comment]
If following the `am_user` schema from the JSON, we can do:

```sql
MariaDB [prisma]> create table am_user(login varchar(64) not null);
Query OK, 0 rows affected (0.007 sec)

MariaDB [prisma]> alter table am_user add primary key (user_id);
ERROR 1072 (42000): Key column 'user_id' doesn't exist in table
MariaDB [prisma]>
```

I'm suspecting we might have a bug in the code that generates the JSON, that we miss some data. Can you @pantharshit00 point me to the code that generates the schema dump? Maybe it misses some columns in here...

**Comment by tomhoule** [comment]
This is not actionable enough to keep around. @pimeys went as far as we should go trying to fix this. Let's see if a more reproducible instance of the problem pops up in the future.
