### ISSUE TITLE
Error: Error in migration engine. Reason: [libs/sql-schema-describer/src/walkers.rs:402:18] called `Result::unwrap()` on an `Err` value: "Foreign key references unknown table. ForeignKeyWalker { foreign_key_index: 1, table_index: 2, __table_name: \"medals\", __referenced_table: \"videos\", __constrained_columns: [\"eMedalVideo\"], __referenced_columns: [\"id\"] }" 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#6741]
Command: `prisma db push --accept-data-loss --preview-feature`
Version: `2.20.1`
Binary Version: `60ba6551f29b17d7d6ce479e5733c70d9c00860e`
Report: https://prisma-errors.netlify.app/report/13229 
OS: `x64 darwin 20.3.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [libs/sql-schema-describer/src/walkers.rs:402:18] called `Result::unwrap()` on an `Err` value: "Foreign key references unknown table. ForeignKeyWalker { foreign_key_index: 1, table_index: 2, __table_name: \"medals\", __referenced_table: \"videos\", __constrained_columns: [\"eMedalVideo\"], __referenced_columns: [\"id\"] }"

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

    at ChildProcess.<anonymous> (/<...>/node_modules/prisma/build/index.js:55608:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
[libs/sql-schema-describer/src/walkers.rs:402:18] called `Result::unwrap()` on an `Err` value: "Foreign key references unknown table. ForeignKeyWalker { foreign_key_index: 1, table_index: 2, __table_name: \"medals\", __referenced_table: \"videos\", __constrained_columns: [\"eMedalVideo\"], __referenced_columns: [\"id\"] }"
```

**Comment by tomhoule** [comment]
We have logic to get rid of dangling foreign keys, we should look into this.

**Comment by janpio** [comment]
> ```shell
> The database is already in sync with the Prisma schema.
> ```

@pimeys Possible that you migrated the database before? Seems the run with the wrong binary you posted above did not actually try to migrate anything.

**Comment by pimeys** [comment]
I should try once more yeah... But this error is coming from the describer, so I'd expect the database to return something for the db push when the error happens.

**Comment by pimeys** [comment]
Did a new test with an empty database:

```bash
❯ npx prisma --version
Environment variables loaded from .env
Warning Precompiled binaries are not available for nixos.
prisma               : 2.20.1
@prisma/client       : 2.20.1
Current platform     : linux-nixos
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at ../../prisma-engines/target/debug/query-engine, resolved by PRISMA_QUERY_ENGINE_BINARY)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at ../../prisma-engines/target/debug/migration-engine, resolved by PRISMA_MIGRATION_ENGINE_BINARY)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at ../../prisma-engines/target/debug/introspection-engine, resolved by PRISMA_INTROSPECTION_ENGINE_BINARY)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at ../../prisma-engines/target/debug/prisma-fmt, resolved by PRISMA_FMT_BINARY)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
Preview Features     : selectRelationCount
```

```bash
❯ npx prisma db push --accept-data-loss --preview-feature
Environment variables loaded from .env
Warning Precompiled binaries are not available for nixos.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "localhost:5435"

🚀  Your database is now in sync with your schema. Done in 554ms

Running generate... (Use --skip-generate to skip the generators)
Warning Precompiled binaries are not available for nixos.
✔ Generated Prisma Client (2.20.1) to ./node_modules/@prisma/client in 778ms
```

So, still not able to reproduce :(

**Comment by tomhoule** [comment]
If we can't reproduce it, let's close and open something again when it pops up again in error reporting.
