### ISSUE TITLE
Prisma generate : The "path" argument must be of type string

### ISSUE THREAD

**Issue by shafikhaan** [prisma/prisma#6770]
## Bug description

I am running same versions of prisma and prisma/client which is `~2.20.1`, when executing `yarn prisma:generate` it thows the following exception

```
Error:
✔ Generated Prisma Client (2.20.1) to ./node_modules/@prisma/client in 125ms

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
    at mkdir (internal/fs/promises.js:467:10)
    at Object.generate [as onGenerate] (/home/programmer/projects/wemaku-api/node_modules/prisma-dbml-generator/dist/cli/dbml-generator.js:14:15)
    at LineStream.<anonymous> (/home/programmer/projects/wemaku-api/node_modules/@prisma/generator-helper/dist/generatorHandler.js:13:46)
    at LineStream.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at LineStream.Readable.push (internal/streams/readable.js:223:10)
    at LineStream.Transform.push (internal/streams/transform.js:166:32)
    at LineStream._pushBuffer (/home/programmer/projects/wemaku-api/node_modules/@prisma/generator-helper/dist/byline.js:108:23)
    at LineStream._transform (/home/programmer/projects/wemaku-api/node_modules/@prisma/generator-helper/dist/byline.js:100:10)
```

## Expected behavior

Prisma generate should run without any errors.

## Environment & setup

- OS: Ubuntu 18.03
- Database: PostgreSQL
- Node.js version: v8.10.0
- Prisma version: 2.20.1
- @prisma/client version: 2.20.1

```
Environment variables loaded from .env
prisma               : 2.20.1
@prisma/client       : 2.20.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by janpio** [comment]
Hey @safinsingh, seems you have a second generator in your `schema.prisma` file, `prisma-dbml-generator` is that possible? If so, can you double check that you are using the newest version of that? Might be outdated.

**Comment by safinsingh** [comment]
Oops, I believe you may have pinged the wrong person 😄

**Comment by janpio** [comment]
Yes, bad GH auto completion - sorry Safin from California. Updated the message above.

**Comment by shafikhaan** [comment]
@janpio sorry for being late here, `prisma-dbml-generator` wasn't the newest, that solved my issue, Ty

**Comment by Bariyard** [comment]
confirmed that it was caused by `prisma-dbml-generator`

> @janpio sorry for being late here, `prisma-dbml-generator` wasn't the newest, that solved my issue, Ty
