### ISSUE TITLE
PANIC in query-engine/connectors/mongodb-query-connector/src/value.rs:185:24not yet implemented: (Json, Json("[]"))

### ISSUE THREAD

**Issue by willin** [prisma/prisma#6773]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | darwin             |
| Prisma Client   | 2.22.0-dev.32      |
| Query Engine    | query-engine 546c8292ac34d3f483d080361ef0e9aa3813a268|
| Database        | undefined|

## Query
```
mutation {
  createOneDeployment(data: {
    status: "X"
    progress: "X"
    params: "X"
    type: "X"
    create_user: "X"
    request: "X"
  }) {
    id
  }
}
```

## Logs
```
 
  prisma:tryLoadEnv No Environment variables loaded  
  prisma:client clientVersion: 2.22.0-dev.32  
  prisma:engine Search for Query Engine in /Users/willin/Documents/WhiteMatrix/baas-dao/.prisma/client  
  prisma:engine Search for Query Engine in /Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist  
  prisma:engine { cwd: '/Users/willin/Documents/WhiteMatrix/baas-dao/prisma' }  
  prisma:engine Search for Query Engine in /Users/willin/Documents/WhiteMatrix/baas-dao/.prisma/client  
  prisma:engine Search for Query Engine in /Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist  
  plusX Execution permissions of /Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist/query-engine-darwin are fine  
  plusX Execution permissions of /Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '59411' ] }  
  prisma:engine stdout  Started http server on http://127.0.0.1:59411  
  prisma:engine Search for Query Engine in /Users/willin/Documents/WhiteMatrix/baas-dao/.prisma/client  
  prisma:engine Search for Query Engine in /Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist  
  plusX Execution permissions of /Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist/query-engine-darwin are fine  
  prisma:engine Client Version: 2.22.0-dev.32  
  prisma:engine Engine Version: query-engine 546c8292ac34d3f483d080361ef0e9aa3813a268  
  prisma:engine Active provider: mongodb  
  prisma:engine stdout  PANIC in query-engine/connectors/mongodb-query-connector/src/value.rs:185:24
not yet implemented: (Json, Json("[]"))  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist/runtime/index.js:25208:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:59411
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -61,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 59411
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/Users/willin/Documents/WhiteMatrix/baas-dao/prisma' }  
  prisma:engine Search for Query Engine in /Users/willin/Documents/WhiteMatrix/baas-dao/.prisma/client  
  prisma:engine Search for Query Engine in /Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist  
  plusX Execution permissions of /Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '59416' ] }  
  prisma:engine stdout  Started http server on http://127.0.0.1:59416  
  prisma:engine Search for Query Engine in /Users/willin/Documents/WhiteMatrix/baas-dao/.prisma/client  
  prisma:engine Search for Query Engine in /Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist  
  plusX Execution permissions of /Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist/query-engine-darwin are fine  
  prisma:engine stdout  PANIC in query-engine/connectors/mongodb-query-connector/src/value.rs:185:24
not yet implemented: (Json, Json("[]"))  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/willin/Documents/WhiteMatrix/baas-dao/prisma/dist/runtime/index.js:25208:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
import { client, BaseDto, Transform, ValidationErr } from '@dao/base';
import { IsArray, IsEnum, IsObject, IsString } from 'class-validator';
import { CreateDeploymentDto } from '../dto';
import { DeployStatus } from '../entity';
// import { DeploymentDaoErr } from '../error';

const db = client.deployment;

class Model extends BaseDto implements CreateDeploymentDto {
  // 用户 id
  @IsString()
  create_user: string;

  // 类型
  @IsString()
  @Transform.ToLowerCase()
  type: string;

  // 原始请求 Object
  @IsObject({ message: ValidationErr.InvalidJson })
  request: any;

  @IsEnum(DeployStatus)
  status = DeployStatus.Pending;

  @IsArray()
  progress: any = [];

  @IsObject()
  params = {};
}

/**
 * 添加部署
 * @param data CreateDeploymentDto
 * @returns string 创建的部署流程 id
 */
export async function createDeployment(data: CreateDeploymentDto): Promise<string> {
  const item = new Model(data);
  return db
    .create({
      data: item,
      select: {
        id: true
      }
    })
    .then(({ id }) => id);
}

```

## Schema
```prisma
model Deployment {
  id          String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  // 类型
  type        String
  // 状态
  // TODO: enum 暂不支持
  // - Pending
  // - Processing（doing）
  // - Success
  // - Fail
  status      String  // @default("pending")
  progress    Json
  request     Json
  params      Json
  // 创建者
  create_user String @db.ObjectId

  created_at DateTime @default(now())
  updated_at DateTime @updatedAt

  // 索引
  @@index(created_at)
  @@index(updated_at)
  @@map("t_deployment")
}
```

**Comment by matthewmueller** [comment]
`Json` support should work as of [2.24.0](https://github.com/prisma/prisma/releases/tag/2.24.0). Can you try again?

**Comment by willin** [comment]
sure, i'll try again.

**Comment by janpio** [comment]
Ping @willin

**Comment by matthewmueller** [comment]
Just tested this and it should be working as expected now in 3.11.0:

Prisma Schema

```prisma
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

model Deployment {
  id          String @id @default(auto()) @map("_id") @db.ObjectId
  type        String
  status      String // @default("pending")
  progress    Json
  request     Json
  params      Json
  create_user String @db.ObjectId

  created_at DateTime @default(now())
  updated_at DateTime @updatedAt
}
```

Script:

```ts
import { PrismaClient, Prisma } from "@prisma/client"
import { ObjectId } from "mongodb"
const prisma = new PrismaClient()

async function main() {
  await prisma.$connect()
  await prisma.deployment.deleteMany()

  const item = {
    type: "a",
    status: "b",
    progress: { just: "started" },
    request: { a: 1 },
    params: [1, 2, { a: "ok" }],
    create_user: new ObjectId().toString(),
  }

  const deployment = await prisma.deployment.create({
    data: item,
    select: {
      id: true,
    },
  })
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())

```

Resulting in:

```sh
$ ts-node index.ts   
{ id: '621ffa1de3fde1b3fc899778' }
```
