### ISSUE TITLE
Negative (prehistoric) DateTime values are not allowed

### ISSUE THREAD

**Issue by nhuesmann** [prisma/prisma#6784]
## Bug description

Prisma does not allow negative DateTime values to be saved. For example, the string `-003000-01-01T00:00:00.000Z` is able to be converted to a JavaScript DateTime object via `new Date(<the string above>)` and is a valid date, however if that date is passed to Prisma when creating a new database entry, an error occurs.

## How to reproduce

1. Follow the Prisma quickstart to create a fresh project
2. Add a `DateTime` field to any model and run the migrations
3. Try saving a record of the model type that has the `DateTime` field. The code in your main function in `script.ts` should look something like this:
```ts
async function main() {
  const dateString = '-003000-01-01T00:00:00.000Z';
  const dateObject = new Date(dateString);
  const createdPost = await prisma.post.create({
    data: {
      title: "test",
      releaseDate: dateObject,
    }
  });
  console.log({createdPost});
}
```
4. The mutation will fail with the following error:
```
Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOnePost.data.PostCreateInput.releaseDate`: Error parsing value: Invalid DateTime: '-003000-01-01T00:00:00.000Z' (must be ISO 8601 compatible). Underlying error: input contains invalid characters.
```

## Expected behavior

I expect that valid JavaScript `DateTime` objects that are ISO 8601 compatible should be accepted as input when creating a new database record.

## Prisma information

Default Prisma quickstart setup with one additional field.

## Environment & setup

- OS: Mac OS
- Database: Tested in PostgreSQL and SQLite
- Node.js version: v12.14.1
- Prisma version:
```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : darwin
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
```

**Comment by janpio** [comment]
(Adding "bug" labels although this might very well be intended behavior right now and have to become a feature request)

**Comment by pantharshit00** [comment]
This is reproducible and we need to discuss if we should allow this.

**Comment by SevInf** [comment]
I don't think postgres timestamp type supports this. [Link](https://www.db-fiddle.com/f/6e8mNjFeG6ydZZPQ1Afp4Q/0). Ultimately, we can be only as flexible as underlying database allows us. 

What's your usecase? Could it be covered by storing date as a string?

**Comment by janpio** [comment]
Ping @nhuesmann, can you help us out here please? We would love to be able to reproduce, but need additional information before attempting this again. Without that we will have to close this issue as unreproducible unforunately. Thanks!

**Comment by Jolg42** [comment]
Reproducible in our monorepo with latest code and engines, I changed the date here https://github.com/prisma/prisma/blob/5efb34ca7ff38792872e08dfc7fd19f617d69fc4/packages/client/src/__tests__/integration/happy/native-types-postgres/test.ts#L217
and ran `pnpm run test packages/client/src/__tests__/integration/happy/native-types-postgres/test.ts`

```
  ● native-types-postgres E: Date, Time, Timestamp


    Invalid `prisma.e.create()` invocation in
    /Users/j42/Dev/prisma/packages/client/src/__tests__/integration/happy/native-types-postgres/test.ts:222:28

      219   ts: '2020-05-05T16:28:33.983+03:00',
      220 }
      221 
    → 222 const e = await prisma.e.create(
    Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneE.data.ECreateInput.date`: Error parsing value: Invalid DateTime: '-003000-01-01T00:00:00.000Z' (must be ISO 8601 compatible). Underlying error: input contains invalid characters., Query parsing/validation error at `Mutation.createOneE.data.EUncheckedCreateInput.date`: Error parsing value: Invalid DateTime: '-003000-01-01T00:00:00.000Z' (must be ISO 8601 compatible). Underlying error: input contains invalid characters.]` at `Mutation.createOneE.data`
```

DEBUG
```
 prisma:client:libraryEngine  library started +7ms
  prisma:client  Prisma Client call: +14ms
  prisma:client  prisma.e.create({
  data: {
    date: new Date('-003000-01-01T00:00:00.000Z'),
    time: new Date('2020-05-02T16:28:33.983Z'),
    ts: '2020-05-05T16:28:33.983+03:00'
  },
  select: {
    date: true,
    time: true,
    ts: true
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  createOneE(data: {
    date: "-003000-01-01T00:00:00.000Z"
    time: "2020-05-02T16:28:33.983Z"
    ts: "2020-05-05T16:28:33.983+03:00"
  }) {
    date
    time
    ts
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +7ms
  prisma:client:request_handler  PrismaClientKnownRequestError: Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneE.data.ECreateInput.date`: Error parsing value: Invalid DateTime: '-003000-01-01T00:00:00.000Z' (must be ISO 8601 compatible). Underlying error: input contains invalid characters., Query parsing/validation error at `Mutation.createOneE.data.EUncheckedCreateInput.date`: Error parsing value: Invalid DateTime: '-003000-01-01T00:00:00.000Z' (must be ISO 8601 compatible). Underlying error: input contains invalid characters.]` at `Mutation.createOneE.data`
    at prismaGraphQLToJSError (/Users/j42/Dev/prisma/packages/engine-core/dist/common/errors/utils/prismaGraphQLToJSError.js:29:12)
    at LibraryEngine.buildQueryError (/Users/j42/Dev/prisma/packages/engine-core/dist/library/LibraryEngine.js:436:68)
    at LibraryEngine.buildQueryError [as request] (/Users/j42/Dev/prisma/packages/engine-core/dist/library/LibraryEngine.js:370:22)
    at RequestHandler.request (/Users/j42/Dev/prisma/packages/client/src/runtime/RequestHandler.ts:161:24)
    at PrismaClient._request (/Users/j42/Dev/prisma/packages/client/src/runtime/getPrismaClient.ts:1108:16)
    at Object.<anonymous> (/Users/j42/Dev/prisma/packages/client/src/__tests__/integration/happy/native-types-postgres/test.ts:222:13) {
  code: 'P2009',
  clientVersion: 'client-test-version',
  meta: {
    query_validation_error: "Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneE.data.ECreateInput.date`: Error parsing value: Invalid DateTime: '-003000-01-01T00:00:00.000Z' (must be ISO 8601 compatible). Underlying error: input contains invalid characters., Query parsing/validation error at `Mutation.createOneE.data.EUncheckedCreateInput.date`: Error parsing value: Invalid DateTime: '-003000-01-01T00:00:00.000Z' (must be ISO 8601 compatible). Underlying error: input contains invalid characters.]",
    query_position: 'Mutation.createOneE.data'
  }
} +0ms
```

**Comment by Jolg42** [comment]
I could find that this date notation `-003000-01-01T00:00:00.000Z`, and more specifically `-003000` is an `expanded year` notation from the ECMAScript Language Specification 
https://tc39.es/ecma262/#sec-expanded-years

>YYYY 	is the year in the proleptic Gregorian calendar as four decimal digits from 0000 to 9999, or as an [expanded year](https://tc39.es/ecma262/#sec-expanded-years) of "+" or "-" followed by six decimal digits.

<h1><span class="secnum">21.4.1.15.1</span> Expanded Years</h1>
          <p>Covering the full <emu-xref href="https://tc39.es/ecma262/#sec-time-values-and-time-range" id="_ref_9695"><a href="https://tc39.es/ecma262/#sec-time-values-and-time-range">time value</a></emu-xref> range of approximately 273,790 years forward or backward from 1 January 1970 (<emu-xref href="https://tc39.es/ecma262/#sec-time-values-and-time-range" id="_ref_631"><a href="https://tc39.es/ecma262/#sec-time-values-and-time-range">21.4.1.1</a></emu-xref>)
 requires representing years before 0 or after 9999. ISO 8601 permits 
expansion of the year representation, but only by mutual agreement of 
the partners in information interchange. In the simplified ECMAScript 
format, such an expanded year representation shall have 6 digits and is 
always prefixed with a + or - sign. The year 0 is considered positive 
and must be prefixed with a + sign. The representation of the year 0 as 
-000000 is invalid. Strings matching the <emu-xref href="https://tc39.es/ecma262/#sec-date-time-string-format" id="_ref_632"><a href="https://tc39.es/ecma262/#sec-date-time-string-format">Date Time String Format</a></emu-xref> with expanded years representing instants in time outside the range of a <emu-xref href="https://tc39.es/ecma262/#sec-time-values-and-time-range" id="_ref_9696"><a href="https://tc39.es/ecma262/#sec-time-values-and-time-range">time value</a></emu-xref> are treated as unrecognizable by <emu-xref href="https://tc39.es/ecma262/#sec-date.parse" id="_ref_633"><a href="https://tc39.es/ecma262/#sec-date.parse"><code>Date.parse</code></a></emu-xref> and cause that function to return <emu-val>NaN</emu-val> without falling back to implementation-specific behaviour or heuristics.</p>
          <emu-note><span class="note">Note</span><div class="note-contents">
            <p>Examples of date-<emu-xref href="https://tc39.es/ecma262/#sec-time-values-and-time-range" id="_ref_9697"><a href="https://tc39.es/ecma262/#sec-time-values-and-time-range">time values</a></emu-xref> with expanded years:</p>
            <figure>
              

-271821-04-20T00:00:00Z | 271822 B.C.
-- | --
-000001-01-01T00:00:00Z | 2 B.C.
+000000-01-01T00:00:00Z | 1 B.C.
+000001-01-01T00:00:00Z | 1 A.D.
+001970-01-01T00:00:00Z | 1970 A.D.
+002009-12-15T00:00:00Z | 2009 A.D.
+275760-09-13T00:00:00Z | 275760 A.D.

</figure></div></emu-note>

**Comment by Jolg42** [comment]
About PostgreSQL here is what I found
https://www.db-fiddle.com/f/6e8mNjFeG6ydZZPQ1Afp4Q/1
```
CREATE TABLE test (
  id INT,
  dateField0 DATE,
  dateField1 TIMESTAMP,
  dateField2 TIMESTAMPTZ
);

-- PostgreSQL does not understand "expanded years" notation, 
-- so this fails, but with a confusing message "time zone displacement out of range"
-- INSERT INTO test (id,dateField0) VALUES (1, '-001000-01-01');
-- INSERT INTO test (id,dateField1) VALUES (2, '-001000-01-01');
-- INSERT INTO test (id,dateField2) VALUES (3, '-001000-01-01');

-- PostgreSQL understands the BC notation though
INSERT INTO test (id,dateField0) VALUES (1, '3000-01-01 BC');
INSERT INTO test (id,dateField1) VALUES (2, '3000-01-01 BC');
INSERT INTO test (id,dateField2) VALUES (3, '3000-01-01 BC');
```

PostgreSQL docs for allowed values
https://www.postgresql.org/docs/current/datatype-datetime.html


Name | Storage Size | Description | Low Value | High Value | Resolution
-- | -- | -- | -- | -- | --
timestamp [ (p) ] [ without time zone ] | 8 bytes | both date and time (no time zone) | 4713 BC | 294276 AD | 1 microsecond
timestamp [ (p) ] with time zone | 8 bytes | both date and time, with time zone | 4713 BC | 294276 AD | 1 microsecond
date | 4 bytes | date (no time of day) | 4713 BC | 5874897 AD | 1 day

Random find, node-postgres checks the date value, reformats it and adds ` BC` (Before Christ) at the end for this case.
https://github.com/brianc/node-postgres/blob/9a95ee719b181341d381702a4404827ca906b036/packages/pg/lib/utils.js#L92-L124

**Comment by Jolg42** [comment]
Note: It seems to be a valid use case to me, we would need to check how other database do this.
A user should be able to insert a Before Christ year date if the database allows it.

```
await prisma.model.create({
    data: {
		...
		date: '3000-01-01 BC',
	}
)}

fails with
    Argument date: Got invalid value '3000-01-01 BC' on prisma.createOneE. Provided String, expected DateTime.
```

Workaround: use raw database access https://www.prisma.io/docs/concepts/components/prisma-client/raw-database-access
Like
```
await prisma.$queryRaw`INSERT INTO hello (id, date) VALUES ('12343244', '3000-01-01 BC');
```

Note that querying will successfully return the entry, but the date object would show `Invalid Date` (with findMany for example.)
