### ISSUE TITLE
Error in PostgreSQL connection: Error { kind: Closed, cause: None }

### ISSUE THREAD

**Issue by rhlsthrm** [prisma/prisma#6837]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | linux-musl         |
| Prisma Client   | 2.18.0             |
| Query Engine    | query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1|
| Database        | undefined|

## Query
```
mutation {
  upsertOneEventSubscription(
    where: {
      publicIdentifier_event: {
        event: "X"
        publicIdentifier: "X"
      }
    }
    create: {
      publicIdentifier: "X"
      event: "X"
      url: "X"
    }
    update: {
      url: "X"
    }
  ) {
    id
    event
    publicIdentifier
    url
  }
}
```

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:client { clientVersion: '2.18.0' }
prisma:engine { cwd: '/app/dist' }
prisma:engine Search for Query Engine in /.prisma/client
prisma:engine Search for Query Engine in /.prisma/client
plusX Execution permissions of /.prisma/client/query-engine-linux-musl are fine
plusX Execution permissions of /.prisma/client/query-engine-linux-musl are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '42465' ] }
prisma:engine stdout  Starting a postgresql pool with 5 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:42465
prisma:engine Search for Query Engine in /.prisma/client
plusX Execution permissions of /.prisma/client/query-engine-linux-musl are fine
prisma:engine Client Version: 2.18.0
prisma:engine Engine Version: query-engine da6fafb57b24e0b61ca20960c64e2d41f9e8cff1
prisma:engine Active provider: sqlite
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (webpack:///./src/generated/db-client/runtime/index.js?:132:37880)
      at NodeEngine._callee104$ (webpack:///./src/generated/db-client/runtime/index.js?:132:32936)
      at tryCatch (webpack:////app/node_modules/regenerator-runtime/runtime.js?:63:40)
      at Generator.invoke [as _invoke] (webpack:////app/node_modules/regenerator-runtime/runtime.js?:293:22)
      at Generator.eval [as next] (webpack:////app/node_modules/regenerator-runtime/runtime.js?:118:21)
      at asyncGeneratorStep (webpack:///./src/generated/db-client/runtime/index.js?:1:1585)
      at _next (webpack:///./src/generated/db-client/runtime/index.js?:1:1900)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    clientVersion: '2.18.0'
  }
}
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (webpack:///./src/generated/db-client/runtime/index.js?:132:37880)
      at NodeEngine._callee104$ (webpack:///./src/generated/db-client/runtime/index.js?:132:32936)
      at tryCatch (webpack:////app/node_modules/regenerator-runtime/runtime.js?:63:40)
      at Generator.invoke [as _invoke] (webpack:////app/node_modules/regenerator-runtime/runtime.js?:293:22)
      at Generator.eval [as next] (webpack:////app/node_modules/regenerator-runtime/runtime.js?:118:21)
      at asyncGeneratorStep (webpack:///./src/generated/db-client/runtime/index.js?:1:1585)
      at _next (webpack:///./src/generated/db-client/runtime/index.js?:1:1900)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    clientVersion: '2.18.0'
  }
}
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: connection closed
      at NodeEngine.graphQLToJSError (webpack:///./src/generated/db-client/runtime/index.js?:132:37880)
      at NodeEngine._callee104$ (webpack:///./src/generated/db-client/runtime/index.js?:132:32936)
      at tryCatch (webpack:////app/node_modules/regenerator-runtime/runtime.js?:63:40)
      at Generator.invoke [as _invoke] (webpack:////app/node_modules/regenerator-runtime/runtime.js?:293:22)
      at Generator.eval [as next] (webpack:////app/node_modules/regenerator-runtime/runtime.js?:118:21)
      at asyncGeneratorStep (webpack:///./src/generated/db-client/runtime/index.js?:1:1585)
      at _next (webpack:///./src/generated/db-client/runtime/index.js?:1:1900)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    clientVersion: '2.18.0'
  }
}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by iblfilip** [comment]
Hi, I have the same problem. Prisma randomly raises such errors.

**Comment by PranavSathy** [comment]
Please see #6791 and see if this is the same issue.

**Comment by rhlsthrm** [comment]
Mine came up when my app got restarted. I took everything down and restarted and it came up properly.

**Comment by janpio** [comment]
Just for the record: This is an error thrown by your actual database. You can handle these in your application and possibly retry the query or similar. Unfortunately Prisma can not help much here. If you are on Google Cloud SQL, def see https://github.com/prisma/prisma/issues/6791 for a possible reason.
