### ISSUE TITLE
Unable to run test suite from fresh clone

### ISSUE THREAD

**Issue by crrobinson14** [prisma/prisma#6841]
## Bug description

I was hoping to make my first contribution to Prisma. To get started, I did a fresh clone of the repo from `master@50d6b963` and followed the instructions in `CONTRIBUTING.md`. I have a recent Node LTS (v14.16.0) installed as well as the documented versions of things like PNPM from that document. Installing the base packages / `pnpm run setup` all work fine, but when I run the test suite (with no changes of my own yet) it fails.

## How to reproduce

1. Clone the repo at the tag described above.
2. `cd prisma/src`
3. `pnpm i`
4. `pnpm run setup`

These steps should succeed so far. The documentation calls for next running `yarn jest` in one of many variants but this does not work. One can however run `yarn test` to run the full test suite. This fails with the following output:

```
$ ts-node scripts/ci/publish.ts --test
Skipping @prisma/engines as it's not in this workspace
Skipping @prisma/engines-version as it's not in this workspace
Skipping @prisma/engines as it's not in this workspace
Skipping @prisma/engines as it's not in this workspace
Skipping @prisma/engines-version as it's not in this workspace
Skipping @prisma/engines-version as it's not in this workspace
Skipping @prisma/engines as it's not in this workspace
Changed files:
  src/packages/cli/package.json
  src/packages/client/package.json
  src/packages/engine-core/package.json
  src/packages/fetch-engine/package.json
  src/packages/migrate/package.json
  src/packages/sdk/package.json

Calculating new dev version...
getNewDevVersion: Next minor stable: 2.22.0
Got 2.22.0-dev.42 in 19144ms
{
  patchBranch: null,
  tag: 'dev',
  tagForE2ECheck: undefined,
  prisma2Version: '2.22.0-dev.42'
}

Testing packages

Run tests. Testing order:
[
  '@prisma/debug',
  '@prisma/generator-helper',
  '@prisma/get-platform',
  '@prisma/engine-core',
  '@prisma/fetch-engine',
  '@prisma/sdk',
  '@prisma/migrate',
  '@prisma/client',
  'prisma',
  'react-prisma',
  '@prisma/tests'
]

Testing @prisma/debug
./packages/debug pnpm run test

> @prisma/debug@0.0.0 test /Users/chad/projects/crrobinson14/prisma/src/packages/debug
> jest

 PASS  src/__tests__/env-disabled.test.ts
 PASS  src/__tests__/basic.test.ts
 PASS  src/__tests__/env-enabled.test.ts

Test Suites: 3 passed, 3 total
Tests:       4 passed, 4 total
Snapshots:   8 passed, 8 total
Time:        2.867 s
Ran all test suites.

Testing @prisma/generator-helper
./packages/generator-helper pnpm run test

> @prisma/generator-helper@0.0.0 test /Users/chad/projects/crrobinson14/prisma/src/packages/generator-helper
> jest


 FAIL  src/__tests__/generatorHandler.test.ts (9.544 s)
  generatorHandler
    ✓ exiting (2260 ms)
    ✕ parsing error (227 ms)
    ✓ minimal-executable (2212 ms)
    ✓ failing-executable (2280 ms)
    ✓ non existent executable (236 ms)

  ● generatorHandler › parsing error

    expect(received).rejects.toThrow()

    Received promise resolved instead of rejected
    Resolved to value: undefined

      64 |       path.join(__dirname, 'invalid-executable'),
      65 |     )
    > 66 |     await expect(() => generator.init()).rejects.toThrow(
         |           ^
      67 |       `Cannot find module 'ms-node/register'`,
      68 |     )
      69 |   })

      at expect (../../node_modules/.pnpm/expect@26.6.2/node_modules/expect/build/index.js:134:15)
      at Object.<anonymous> (src/__tests__/generatorHandler.test.ts:66:11)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 4 passed, 5 total
Snapshots:   1 passed, 1 total
Time:        9.584 s
Ran all test suites.
 ERROR  Test failed. See above for more details.
Error: Error: Error running pnpm run test in packages/generator-helper:Error: Command failed with exit code 1: pnpm run test
    at makeError (/Users/chad/projects/crrobinson14/prisma/src/node_modules/.pnpm/execa@5.0.0/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/chad/projects/crrobinson14/prisma/src/node_modules/.pnpm/execa@5.0.0/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at run (/Users/chad/projects/crrobinson14/prisma/src/scripts/ci/publish.ts:147:5)
    at testPackages (/Users/chad/projects/crrobinson14/prisma/src/scripts/ci/publish.ts:876:7)
    at publish (/Users/chad/projects/crrobinson14/prisma/src/scripts/ci/publish.ts:693:7)
    at run (/Users/chad/projects/crrobinson14/prisma/src/scripts/ci/publish.ts:157:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at testPackages (/Users/chad/projects/crrobinson14/prisma/src/scripts/ci/publish.ts:876:7)
    at publish (/Users/chad/projects/crrobinson14/prisma/src/scripts/ci/publish.ts:693:7)
error Command failed with exit code 1.
```

## Expected behavior

A fresh clone and basic instructions should allow a developer to successfully run a full test suite against a clean copy of the code to ensure his/her environment has no compatibility issues, and get familiar with the app.

## Prisma information

N/A

## Environment & setup

OS: Mac OS Big Sur 11.0.1 (M1 Silicon but that does not appear to be the issue)
Database: N/A (but will be MySQL for testing)
NodeJS: v14.16.0
Prisma: origin/master @50d6b963

**Comment by janpio** [comment]
That sucks, sorry about that @crrobinson14. Someone will look into that.

**Comment by Jolg42** [comment]
Hi @crrobinson14 👋 Thanks for opening this issue.

Could you run this to get pnpm and ts-node versions?
```
pnpm -v
ts-node -v
```

Also the root project `yarn test` is mainly used by our CI to run all tests.
Locally I can recommend changing to a specific package directory like `cd src/packages/cli` and running `pnpm run test` there.

**Comment by pantharshit00** [comment]
ping @Jolg42

**Comment by crrobinson14** [comment]
@Jolg42 Happy to. I don't have ts-node installed globally so I presume it's using the 9.1.1 called for in the repo...

```
[chad@chads-mac-mini prisma (master *)]$ pnpm -v
5.15.1
[chad@chads-mac-mini prisma (master *)]$ ts-node -v
bash: ts-node: command not found
```

**Comment by crrobinson14** [comment]
FYI I tried running an individual test suite e.g. `src/client` and it mostly went well except some tests that failed due to my not specifying `DATABASE_URL`, which I hadn't done for the experiment. So I appreciate you all looking into the general process but I may not be blocked here... I was exploring the LOE on adding a PR for NanoID support, mimicking what's already there for CUID.  It looks like the only packages involved are `client` and `sdk`...

**Comment by Jolg42** [comment]
I'm closing this since it's old and things changed.
We can look into this if there are still some issues on the current git head of the main branch.

Note that we now have this https://github.com/prisma/prisma/blob/main/TESTING.md
