### ISSUE TITLE
[Bug] Prisma-fmt sqlserver NVarChar(m) causes thread 'main' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by josh-hemphill** [prisma/prisma#6842]
## Bug description

This is especially annoying when using the vscode extension, since apparently whatever part is causing this is also being run for highlighting, since it throws the panic while trying to type `NVarChar(max)` while you only have `(m)` and `(ma)` typed in the parentheses.

## How to reproduce

1. Create a model with a column database type of `NVarChar()`
2. Enter any partial string of the keyword `max`
3. Run `prisma format`

## Expected behavior

Produce non-panic errors (hopefully resulting in the syntax marking as invalid through things like the vscode extension)

## Prisma information

```prisma
model Config {
    key   String  @id
    value String? @db.NVarChar(m)
}
```

## Environment & setup

- OS: Ubuntu (WSL)
- Database: SQL Server
- Node.js version: v14.16.1
- Prisma version:

```
prisma               : 2.21.2
@prisma/client       : 2.21.2
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d (at ../../.config/nvm/versions/node/v14.16.1/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli e421996c87d5f3c8f7eeadd502d4ad402c89464d (at ../../.config/nvm/versions/node/v14.16.1/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core e421996c87d5f3c8f7eeadd502d4ad402c89464d (at ../../.config/nvm/versions/node/v14.16.1/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt e421996c87d5f3c8f7eeadd502d4ad402c89464d (at ../../.config/nvm/versions/node/v14.16.1/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : e421996c87d5f3c8f7eeadd502d4ad402c89464d
Studio               : 0.371.0
Preview Features     : microsoftSqlServer
```

<details>
      <summary>Backtrace</summary>

      ```
	Error: Error: Command failed with exit code 101: /home/jhemphill/data-model/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x format -i /home/jhemphill/data-model/prisma/schema.prisma
	thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', libs/datamodel/connectors/sql-datamodel-connector/src/mssql_datamodel_connector.rs:391:57
	stack backtrace:
	0: rust_begin_unwind
				at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
	1: core::panicking::panic_fmt
				at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
	2: core::option::expect_none_failed
				at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
	3: sql_datamodel_connector::mssql_datamodel_connector::parse_mssql_type_parameter
	4: <sql_datamodel_connector::mssql_datamodel_connector::MsSqlDatamodelConnector as datamodel_connector::Connector>::parse_native_type
	5: datamodel::transform::ast_to_dml::lift::LiftAstToDml::lift_field_type
	6: datamodel::transform::ast_to_dml::validation_pipeline::ValidationPipeline::validate
	7: datamodel::parse_datamodel_internal
	8: datamodel::ast::reformat::reformatter::Reformatter::new
	9: prisma_fmt::format::run
	10: prisma_fmt::main
	note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
		at makeError (/home/jhemphill/data-model/node_modules/prisma/build/index.js:2564:15)
		at handlePromise (/home/jhemphill/data-model/node_modules/prisma/build/index.js:3232:31)
		at runMicrotasks (<anonymous>)
		at processTicksAndRejections (internal/process/task_queues.js:93:5)
		at async Object.formatSchema2 (/home/jhemphill/data-model/node_modules/prisma/build/index.js:14792:16)
		at async _Format.parse (/home/jhemphill/data-model/node_modules/prisma/build/index.js:140770:18)
		at async main (/home/jhemphill/data-model/node_modules/prisma/build/index.js:141299:18)
      ```
    </details>

**Comment by janpio** [comment]
I can confirm the issue:
![image](https://user-images.githubusercontent.com/183673/116445026-b0fd2a00-a855-11eb-873a-1a3b33847b73.png)

```
[Error - 19:12:17] prisma-fmt error'd during linting.

[Error - 19:12:17] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', libs\datamodel\connectors\sql-datamodel-connector\src\mssql_datamodel_connector.rs:391:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I did not get `prisma format` to crash though, only via VSCode for some reason.

**Comment by josh-hemphill** [comment]
> I did not get `prisma format` to crash though, only via VSCode for some reason.

I tried running `prisma format` quite a few times before I realized I didn't actually save the schema with the partial keyword, after that it crashed as expected.

**Comment by janpio** [comment]
Ah indeed, I probably only ran it with `max` in there. I indeed need to run it with a _partial_ version of that to get this:

```
C:\Users\Jan\Documents\throwaway\prismaTypeTest>npx prisma format
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: Command failed with exit code 101: C:\Users\Jan\Documents\throwaway\prismaTypeTest\node_modules\@prisma\engines\prisma-fmt-windows.exe format -i C:\Users\Jan\Documents\throwaway\prismaTypeTest\prisma\schema.prisma
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', libs\datamodel\connectors\sql-datamodel-connector\src\mssql_datamodel_connector.rs:391:57
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pimeys** [comment]
It should return a proper error now and not interfere with VSCode.

Release: 2.22.0 next Tuesday or the upcoming dev versions.
