### ISSUE TITLE
Prisma Engine Hangs on end of test

### ISSUE THREAD

**Issue by ChrisF999** [prisma/prisma#6855]
## Bug description

Prisma Engine hangs on test with Jest.

Used (https://www.npmjs.com/package/leaked-handles) to detect the open handles 

``` 
child process handle leaked at one of:
    at Object.fakeSpawn [as spawn] (C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules\leaked-handles\stacks.js:46:21)
    at C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules@prisma\client\runtime\index.js:27213:40
child process handle {
  pid: 29860,
  cmd: 'C:\Users\Khris\Documents\git\KoalaBotFrontend\node_modules.prisma\client\query-engine-windows.exe',
  args: [ '--enable-raw-queries', '--port', '24765' ]
}
```

## How to reproduce
https://github.com/ChrisF999/prisma-testing-hang

run the tests in the minimal app above: npm run test, after installing decencies. 

## Expected behavior

Prisma engine to close down gracefully and not hang. 

## Prisma information
Can be seen in the repo above

## Environment & setup

- OS: Windows
- Database: SQLight
- Node.js version: v14.16.1
- Prisma version: 2.21.2

```

```

**Comment by janpio** [comment]
I can confirm this observation.

To use `leaked-handles` I needed to:

1. `npm install leaked-handles`
2. Add to `express\__tests__\verify.test.js`: `require("leaked-handles");`

Then I get the following output:

```
C:\Users\Jan\Documents\throwaway\prisma-testing-hang>npm run test                        

> temp@1.0.0 test
> jest

 PASS  express/__tests__/verify.test.js
  Verify tests
    √ responds with json (396 ms)
    √ responds with 201 (136 ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        4.13 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.


no of handles 6

tcp stream {
  fd: 1,
  readable: false,
  writable: true,
  address: {},
  serverAddr: null
}

tcp stream {
  fd: 2,
  readable: false,
  writable: true,
  address: {},
  serverAddr: null
}

tcp stream {
  fd: 0,
  readable: true,
  writable: false,
  address: {},
  serverAddr: null
}

child process stdout stream handle leaked at one of:
    at C:\Users\Jan\Documents\throwaway\prisma-testing-hang\node_modules\@prisma\client\runtime\index.js:27126:40
child process stdout stream handle { fd: -1, readable: true, writable: false }

child process stderr stream handle leaked at one of:
    at C:\Users\Jan\Documents\throwaway\prisma-testing-hang\node_modules\@prisma\client\runtime\index.js:27126:40
child process stderr stream handle { fd: -1, readable: true, writable: false }

child process handle leaked at one of:
    at C:\Users\Jan\Documents\throwaway\prisma-testing-hang\node_modules\@prisma\client\runtime\index.js:27126:40
child process handle {
  pid: 20680,
  cmd: 'C:\\Users\\Jan\\Documents\\throwaway\\prisma-testing-hang\\node_modules\\.prisma\\client\\query-engine-windows.exe',
  args: [ '--enable-raw-queries', '--port', '58030' ]
}
```

**Comment by janpio** [comment]
The reproduction starts another `PrismaClient` instance when it starts, additionally to the one that is created in the server. Replacing that with `const prisma = require('../util/prisma.js');` makes the main leak go away.
