### ISSUE TITLE
Error: [libs/datamodel/connectors/dml/src/model.rs:161:64] Could not find relation field nodes on model nodes. 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#6861]
Command: `prisma db pull`
Version: `2.21.2`
Binary Version: `e421996c87d5f3c8f7eeadd502d4ad402c89464d`
Report: https://prisma-errors.netlify.app/report/13251 
OS: `x64 darwin 20.3.0`

JS Stacktrace:
```
Error: [libs/datamodel/connectors/dml/src/model.rs:161:64] Could not find relation field nodes on model nodes.
    at ChildProcess.<anonymous> (/<...>/src/github.com/storytable/api/node_modules/prisma/build/index.js:39953:28)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_handler::{{closure}}
   6: std::sys_common::backtrace::__rust_end_short_backtrace
   7: _rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: dml::model::Model::find_relation_field_mut
  11: sql_introspection_connector::introspection_helpers::deduplicate_relation_field_names
  12: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  16: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  17: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  18: introspection_engine::main::{{closure}}
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: introspection_engine::main
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal
  24: std::rt::lang_start

```

**Comment by pimeys** [comment]
SQL Schema that triggers this bug when introspecting:

```sql
CREATE TABLE profiles(
    id UUID PRIMARY KEY DEFAULT(uuid_generate_v4()),
    email_address VARCHAR
);

CREATE TABLE collections(
    id uuid PRIMARY KEY DEFAULT(uuid_generate_v4()),
    profile_id UUID,
    "name" VARCHAR,
    created_at TIMESTAMP(6) default(now()),
    updated_at TIMESTAMP(6) DEFAULT(now()),
    CONSTRAINT collections_profile_id_fkey FOREIGN KEY(id) REFERENCES profiles(id) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE nodes(
    id UUID PRIMARY KEY DEFAULT(uuid_generate_v4()),
    collection_id UUID,
    "name" VARCHAR,
    "type" VARCHAR,
    x INT4,
    y INT4,
    created_at TIMESTAMP(6) DEFAULT(now()),
    updated_at TIMESTAMP(6) DEFAULT(now()),
    CONSTRAINT nodes_collections_id_fkey FOREIGN KEY(id) REFERENCES collections(id) ON DELETE NO ACTION ON UPDATE CASCADE
);

CREATE TABLE _nodes(
    node_a UUID NOT NULL,
    node_b UUID NOT NULL,
    CONSTRAINT _nodes_node_a_fkey FOREIGN KEY(node_a) REFERENCES nodes(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT _nodes_node_b_fkey FOREIGN KEY(node_b) REFERENCES nodes(id) ON DELETE CASCADE ON UPDATE CASCADE
);
```

**Comment by pimeys** [comment]
The bug in question over here is the naming, but first we can simplify all cruft out from the previous post:

```sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE nodes(
    id uuid primary key default(uuid_generate_v4())
);

CREATE TABLE nodes_nodes(
    node_a uuid not null,
    node_b uuid not null,
    constraint _nodes_node_a_fkey foreign key(node_a) references nodes(id) on delete cascade on update cascade,
    constraint _nodes_node_b_fkey foreign key(node_b) references nodes(id) on delete cascade on update cascade
);
```
Of course we have not so kosher m2m table, but our crash happens before we can validate and add the `@ignore` attribute to the `_nodes` model.

We have logic to take the leading `_` out from model names, so in our `datamodel` representation we have two models with a name `nodes`. This leads to problems when we try to look for fields we expect to be there, but is actually in the other model also named `nodes`.
