### ISSUE TITLE
Error in PostgreSQL connection: Error { kind: Closed, cause: None }

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#6883]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.21.2             |
| Query Engine    | query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d|
| Database        | undefined|

## Query
```
mutation {
  updateOneOrder(
    where: {
      id: 5
    }
    data: {
      status: REFUNDED
      refunds: {
        create: {
          transaction: {
            create: {
              order: {
                connect: {
                  id: 5
                }
              }
              amount: 5
              paymentProcessor: STRIPE
              transactionId: "X"
              details: "X"
            }
          }
        }
      }
      tickets: {
        updateMany: {
          where: {

          }
          data: {
            status: REFUNDED
          }
        }
      }
    }
  ) {
    id
    shortId
    userId
    inviteeId
    purchaserId
    addressId
    paymentMethodId
    price
    discountAmount
    serviceFee
    promoterFee
    processorFee
    processorFeeCharged
    taxAmount
    status
    type
    delivery
    eventId
    promoLinkId
    createdAt
    updatedAt
    purchaser {
      id
      firstName
      lastName
      phoneNumber
      email
      createdAt
      updatedAt
    }
    event {
      name
      timezone
      venueName
    }
  }
}
```

## Logs
```
odules/Order/actions/refundOrder/index.js:12:27)
    at async refundOrder (/app/src/modules/Order/resolvers.js:86:27)
    at async resolver (/app/src/common/errors/resolver.js:7:16)
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:client Error: Server has closed the connection.
    at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27489:16)
    at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27387:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async cb (/app/node_modules/.prisma/client/runtime/index.js:34750:26)
    at async /app/src/common/prisma/retry.js:35:32
    at async Object.exports.default (/app/src/modules/Order/actions/refundOrder/refundCustomer.js:17:19)
    at async Object.exports.default [as refundOrder] (/app/src/modules/Order/actions/refundOrder/index.js:12:27)
    at async refundOrder (/app/src/modules/Order/resolvers.js:86:27)
    at async resolver (/app/src/common/errors/resolver.js:7:16)
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Closed, cause: None }
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: db error: FATAL: the database system is in recovery mode
      at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27491:14)
      at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27387:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/app/node_modules/.prisma/client/runtime/index.js:34750:26)
      at async /app/src/common/prisma/retry.js:35:32
      at async Object.exports.default (/app/src/modules/Order/actions/refundOrder/refundCustomer.js:17:19)
      at async Object.exports.default [as refundOrder] (/app/src/modules/Order/actions/refundOrder/index.js:12:27)
      at async refundOrder (/app/src/modules/Order/resolvers.js:86:27)
      at async resolver (/app/src/common/errors/resolver.js:7:16) {
    clientVersion: '2.21.2'
  }
}
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: db error: FATAL: the database system is in recovery mode
      at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27491:14)
      at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27387:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/app/node_modules/.prisma/client/runtime/index.js:34750:26)
      at async /app/src/common/prisma/retry.js:35:32
      at async Object.exports.default (/app/src/modules/Order/actions/refundOrder/refundCustomer.js:17:19)
      at async Object.exports.default [as refundOrder] (/app/src/modules/Order/actions/refundOrder/index.js:12:27)
      at async refundOrder (/app/src/modules/Order/resolvers.js:86:27)
      at async resolver (/app/src/common/errors/resolver.js:7:16) {
    clientVersion: '2.21.2'
  }
}
prisma:engine {
  error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error in connector: Error querying the database: db error: FATAL: the database system is in recovery mode
      at NodeEngine.graphQLToJSError (/app/node_modules/.prisma/client/runtime/index.js:27491:14)
      at NodeEngine.request (/app/node_modules/.prisma/client/runtime/index.js:27387:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cb (/app/node_modules/.prisma/client/runtime/index.js:34750:26)
      at async /app/src/common/prisma/retry.js:35:32
      at async Object.exports.default (/app/src/modules/Order/actions/refundOrder/refundCustomer.js:17:19)
      at async Object.exports.default [as refundOrder] (/app/src/modules/Order/actions/refundOrder/index.js:12:27)
      at async refundOrder (/app/src/modules/Order/resolvers.js:86:27)
      at async resolver (/app/src/common/errors/resolver.js:7:16) {
    clientVersion: '2.21.2'
  }
}
```

**Comment by Sytten** [comment]
It happened during a segfault on my postgres database:
```
2021-05-01 13:38:00.284 UTC [1]: [46-1] db=,user= LOG:  server process (PID 1091621) was terminated by signal 11: Segmentation fault 
2021-05-01 13:38:00.284 UTC [1]: [47-1] db=,user= DETAIL: Failed process was running: UPDATE "public"."order" SET "status" = $1, "updated_at" = $2 WHERE "public"."order"."id" IN ($3)
2021-05-01 13:38:00.285 UTC [1]: [48-1] db=,user= LOG: terminating any other active server processes
2021-05-01 13:38:00.287 UTC [1092074]: [1-1] db=cloudsqladmin,user=cloudsqladmin WARNING: terminating connection because of crash of another server process
2021-05-01 13:38:00.287 UTC [1092074]: [2-1] db=cloudsqladmin,user=cloudsqladmin DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-05-01 13:38:00.287 UTC [1092074]: [3-1] db=cloudsqladmin,user=cloudsqladmin HINT: In a moment you should be able to reconnect to the database and repeat your command.
```

**Comment by Ezard** [comment]
@Sytten based off your logs, I assume you're using Google Cloud SQL, and that you have Query Insights enabled?

If yes, then this issue is actually caused by the segfault that you discovered (and is nothing to do with Prisma AFAIK), which is the fault of Google Cloud's Query Insights functionality. There are some links to this issue in Google's bugtracker [in this comment](https://github.com/prisma/prisma/issues/6791#issuecomment-826870668)

**Comment by Sytten** [comment]
Good to know, but this is for internal prisma report. We worked on this to map the unknown errors like that to mapped error so people can catch and retry.

**Comment by janpio** [comment]
I updated the issue title @Sytten. Is this the correct error that is currently considered as unknown, but probably should not be?

**Comment by Sytten** [comment]
Yeah exactly

**Comment by PinkPigPinkPig** [comment]
Hi @Sytten is this issue solved, I got same proplem.
