### ISSUE TITLE
PANIC in query-engine\core\src\response_ir\internal.rs:395:26Application logic invariant error: received null value for field actions which may not be null

### ISSUE THREAD

**Issue by addiMohammed** [prisma/prisma#6889]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.15.5           | 
| OS              | windows            |
| Prisma Client   | 2.21.2             |
| Query Engine    | query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d|
| Database        | undefined|

## Query
```
query {
  findManyuserAction(where: {
    userId: 5
  }) {
    id
    userId
    actionId
    actions {
      id
      name
      desc
      created_at
      updated_at
      field
      endpoint
      label
      activeStatus
      method
    }
  }
}
```

## Logs
```
5;78;1mprisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine { cwd: 'C:\\Users\\HB\\Documents\\GitHub\\api\\prisma' }  +3s
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '59106' ] }  
  prisma:engine stdout  Starting a mysql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:59106  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine Client Version: 2.21.2  
  prisma:engine Engine Version: query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in query-engine\core\src\response_ir\internal.rs:395:26
Application logic invariant error: received null value for field actions which may not be null  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:59106
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 59106
  prisma:engine   }
  prisma:engine }  
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd: 'C:\\Users\\HB\\Documents\\GitHub\\api\\prisma' }  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '59111' ] }  
  prisma:engine stdout  Starting a mysql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:59111  
  prisma:engine Search for Query Engine in C:\Users\HB\Documents\GitHub\api\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\core\src\response_ir\internal.rs:395:26
Application logic invariant error: received null value for field actions which may not be null  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by janpio** [comment]
7 months later no further information, so I think we can consider this solved.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
