### ISSUE TITLE
Node-API library does not work on 32bit Node (Windows)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#6905]
Via Azure Functions Windows e2e tests @williamluke4 discovered that our Napi build does not work on 32 bit Node.

![image](https://user-images.githubusercontent.com/183673/116889652-1a51b400-ac2d-11eb-8c86-5083489377d7.png)

I can confirm this on Windows directly as well:

```
[2021-05-03T14:28:26.840Z] Worker process started and initialized.
[2021-05-03T14:28:26.857Z] Worker was unable to load function azure-function-win-e2e-test-2021-05-03-133402: 'Error: \\?\C:\Users\Jan\Documents\prisma2-e2e-tests\platforms-serverless\azure-functions-windows\node_modules\.prisma\client\query_engine_napi-windows.dll.node is not a valid Win32 application.
[2021-05-03T14:28:26.859Z] \\?\C:\Users\Jan\Documents\prisma2-e2e-tests\platforms-serverless\azure-functions-windows\node_modules\.prisma\client\query_engine_napi-windows.dll.node'
[2021-05-03T14:28:26.863Z] Worker failed to function id e5d13d4c-5182-407f-9838-920b085eef0e.
[2021-05-03T14:28:26.865Z] Result: Failure
Exception: Worker was unable to load function azure-function-win-e2e-test-2021-05-03-133402: 'Error: \\?\C:\Users\Jan\Documents\prisma2-e2e-tests\platforms-serverless\azure-functions-windows\node_modules\.prisma\client\query_engine_napi-windows.dll.node is not a valid Win32 application.
[2021-05-03T14:28:26.866Z] \\?\C:\Users\Jan\Documents\prisma2-e2e-tests\platforms-serverless\azure-functions-windows\node_modules\.prisma\client\query_engine_napi-windows.dll.node'
Stack: Error: \\?\C:\Users\Jan\Documents\prisma2-e2e-tests\platforms-serverless\azure-functions-windows\node_modules\.prisma\client\query_engine_napi-windows.dll.node is not a valid Win32 application.
[2021-05-03T14:28:26.868Z] \\?\C:\Users\Jan\Documents\prisma2-e2e-tests\platforms-serverless\azure-functions-windows\node_modules\.prisma\client\query_engine_napi-windows.dll.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Jan\Documents\prisma2-e2e-tests\platforms-serverless\azure-functions-windows\azure-function-win-e2e-test-2021-05-03-133402\index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14).
```

To get to this:
1. Clone https://github.com/prisma/e2e-tests/tree/enable-napi-tests
2. Set `PRISMA_FORCE_NAPI=true`
3. Run `yarn` in `platforms-servereless/azure-functions-windows`
4. Also run `yarn prisma generate` and `yarn tsc`
5. Make sure you have a 32 bit Node installed, e.g. `nvm install 14.16.1 32` and `nvm use 14.16.1 32` (uses https://github.com/coreybutler/nvm-windows)
5. Then run `yarn func start` and observe error above

**Comment by janpio** [comment]
Turns out you can test 32bit/x86 Node on Windows on GH Actions: https://github.com/prisma/e2e-tests/runs/2886971312?check_suite_focus=true

```
+ yarn prisma generate
yarn run v1.22.10
warning ..\..\package.json: No license field
$ D:\a\e2e-tests\e2e-tests\generic\basic\node_modules\.bin\prisma generate
2021-06-22T16:29:16.480Z prisma:loadEnv project root found at D:\a\e2e-tests\e2e-tests\generic\basic\package.json
2021-06-22T16:29:16.496Z prisma:tryLoadEnv Environment variables not found at null
2021-06-22T16:29:16.496Z prisma:tryLoadEnv Environment variables not found at undefined
2021-06-22T16:29:16.496Z prisma:tryLoadEnv No Environment variables loaded
2021-06-22T16:29:16.499Z prisma:engines using NAPI: true
2021-06-22T16:29:16.499Z prisma:engines binaries to download libquery-engine-napi, migration-engine, introspection-engine, prisma-fmt
Prisma schema loaded from prisma\schema.prisma
2021-06-22T16:29:17.160Z prisma:getConfig Using N-API Query Engine at: D:\a\e2e-tests\e2e-tests\generic\basic\node_modules\prisma\query_engine_napi-windows.dll.node
Error: Error: \\?\D:\a\e2e-tests\e2e-tests\generic\basic\node_modules\prisma\query_engine_napi-windows.dll.node is not a valid Win32 application.
\\?\D:\a\e2e-tests\e2e-tests\generic\basic\node_modules\prisma\query_engine_napi-windows.dll.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at getConfigNAPI (D:\a\e2e-tests\e2e-tests\generic\basic\node_modules\prisma\build\index.js:26951:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.getConfig5 (D:\a\e2e-tests\e2e-tests\generic\basic\node_modules\prisma\build\index.js:26930:14)
    at async Object.getGenerators (D:\a\e2e-tests\e2e-tests\generic\basic\node_modules\prisma\build\index.js:34025:20)
error Command failed with exit code 1.
```

**Comment by weavdale** [comment]
Any update on running 32bit Node on Windows. I get the error `The default query engine type (Node-API, "library") is currently not supported for 32bit Node. Please set `engineType = "binary"` in the "generator" block of your "schema.prisma" file`. I did this and tried `npx prisma generate` again and still get the same error.

**Comment by janpio** [comment]
If you did this and it did not work, please open a new issue and provide the full reproduction for it. Thanks.

**Comment by adamaslan** [comment]
I seem to be getting the same issue, but I am a bit confused.

**Comment by janpio** [comment]
Same answer as before, the error message includes the workaround. If that workaround does not work for you, open a new issue please.
