### ISSUE TITLE
PANIC in query-engine\core\src\response_ir\internal.rs:395:26Application logic invariant error: received null value for field clientInfo which may not be null

### ISSUE THREAD

**Issue by tudobemjz** [prisma/prisma#6933]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.17.0           | 
| OS              | windows            |
| Prisma Client   | 2.22.0             |
| Query Engine    | query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c|
| Database        | undefined|

## Query
```
query {
  findManyexplan(where: {
    Id: 5
  }) {
    Id
    ClientNo
    ClientName
    Parcel
    ParcelNo
    IsPay
    Deliver
    Status
    Plandate
    clientInfo {
      ClientNo
      InvoiceName
      ManegerName
      TaxNo
      Street
      PostCode
      City
      Province
      Country
      CountryID
      PhoneNo
      PhoneNo2
      Email
      AutoSendEmail
      ClientClass
      Transport
      LoginEnable
      Remarks
      Remarks2
    }
  }
}
```

## Logs
```
  prisma:tryLoadEnv Environment variables not found at null  
  prisma:tryLoadEnv Environment variables not found at undefined  
  prisma:tryLoadEnv No Environment variables loaded  
  prisma:tryLoadEnv Environment variables not found at null  
  prisma:tryLoadEnv Environment variables not found at undefined  
  prisma:tryLoadEnv No Environment variables loaded  
  prisma:client clientVersion: 2.22.0  
  prisma:engine Search for Query Engine in C:\Users\jiang\Documents\GitHub\bizfaction\node_modules\.prisma\client  
  prisma:engine { cwd: 'C:\\Users\\jiang\\Documents\\GitHub\\bizfaction\\prisma' }  +4s
  prisma:engine Search for Query Engine in C:\Users\jiang\Documents\GitHub\bizfaction\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '57786' ] }  
  prisma:engine stdout  Starting a sqlite pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:57786  
  prisma:engine Search for Query Engine in C:\Users\jiang\Documents\GitHub\bizfaction\node_modules\.prisma\client  
  prisma:engine Client Version: 2.22.0  
  prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c  
  prisma:engine Active provider: sqlite  
  prisma:engine stdout  PANIC in query-engine\core\src\response_ir\internal.rs:395:26
Application logic invariant error: received null value for field clientInfo which may not be null  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  prisma:engine     errno: 'ECONNRESET',
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:57786
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  prisma:engine     errno: 'ECONNREFUSED',
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 57786
  prisma:engine   }
  prisma:engine }  +2s
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd: 'C:\\Users\\jiang\\Documents\\GitHub\\bizfaction\\prisma' }  
  prisma:engine Search for Query Engine in C:\Users\jiang\Documents\GitHub\bizfaction\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '57789' ] }  
  prisma:engine stdout  Starting a sqlite pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:57789  
  prisma:engine Search for Query Engine in C:\Users\jiang\Documents\GitHub\bizfaction\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\core\src\response_ir\internal.rs:395:26
Application logic invariant error: received null value for field clientInfo which may not be null  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:205:27) {
  prisma:engine     errno: 'ECONNRESET',
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts

    return await ctx.prisma.explan.findMany({
        where:{ Id: 7 },
        include:{ clientInfo:true }
    })

```

## Schema
```prisma

model explan{
Id Int @id @default(autoincrement())
ClientNo Int @default(0)
...
clientInfo client? @relation(fields: [ClientNo],references:[ClientNo])
}

model explan{
 ClientNo      Int     @unique
...
 explan explan[]
}

```

##What i want: 

```ts
    return await ctx.prisma.explan.findMany({
        where:{ Id: 7 },
        include:{ clientInfo: clientInfo ===null ? false:true}
    })
```
well  I can also use queryRaw like this: 
```sql
SELECT b.* FROM explan a LEFT JOIN client b ON b.ClientNo = a.ClientNo WHERE Id = 7 
```
But the reason I use PRISMA is to reduce the use of sql statements. . .

**Comment by pantharshit00** [comment]
Hey @tudobemjz 

`clientInfo` can't be null as `ClientNo`. Are you sure you have some null values in the database?

**Comment by janpio** [comment]
5 months later no further information, so I think we can consider this solved.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
