### ISSUE TITLE
Query engine exited with code 101 - thread 'main' panicked at 'Could not open datamodel 

### ISSUE THREAD

**Issue by daniellaera** [prisma/prisma#6966]
## Bug description

Just updated to the latest version of Prisma and after restarting and migrating / generating everything I get this

`Query engine exited with code 101 - thread 'main' panicked at 'Could not open datamodel file '/...../.next/server/pages/post/schema.prisma'`

## How to reproduce
nexj js project
`yarn dev`

## Environment & setup
my prisma schema

```
model User {
  id        Int       @id @default(autoincrement())
  createdAt DateTime  @default(now())
  username  String    @unique
  password  String
  imageUrl  String?
  tweets    Tweet[]
  comments  Comment[]
}

model Tweet {
  id        Int       @id @default(autoincrement())
  createdAt DateTime  @default(now())
  text      String
  authorId  Int
  author    User      @relation(fields: [authorId], references: [id])
  comments  Comment[]
}

model Comment {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  text      String
  tweetId   Int?
  tweet     Tweet?   @relation(fields: [tweetId], references: [id])
  authorId  Int
  author    User     @relation(fields: [authorId], references: [id])
}
```
 what am I missing, some annotation or fixes on schema? since latest version?
![Screenshot 2021-05-06 at 14 26 25](https://user-images.githubusercontent.com/8995710/117299278-a3a8f680-ae78-11eb-86b7-be0edff5d0d7.png)

```
 stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: query_engine::opt::load_datamodel_file::{{closure}}
   3: structopt::StructOpt::from_args
   4: query_engine::main::main::{{closure}}::main::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: std::thread::local::LocalKey<T>::with
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: async_io::driver::block_on
   9: async_global_executor::reactor::block_on
  10: std::thread::local::LocalKey<T>::with
  11: async_std::task::builder::Builder::blocking
  12: query_engine::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    at cb (/Users/daniellaera/Desktop/fullstack-twitter/node_modules/@prisma/client/runtime/index.js:35104:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async getServerSideProps (webpack-internal:///./pages/post/[id].tsx:48:23)
    at async renderToHTML (/Users/daniellaera/Desktop/fullstack-twitter/node_modules/next/dist/next-server/server/render.js:40:215)
    at async /Users/daniellaera/Desktop/fullstack-twitter/node_modules/next/dist/next-server/server/next-server.js:111:97
    at async /Users/daniellaera/Desktop/fullstack-twitter/node_modules/next/dist/next-server/server/next-server.js:104:142
    at async DevServer.renderToHTMLWithComponents (/Users/daniellaera/Desktop/fullstack-twitter/node_modules/next/dist/next-server/server/next-server.js:136:387)
    at async DevServer.renderToHTML (/Users/daniellaera/Desktop/fullstack-twitter/node_modules/next/dist/next-server/server/next-server.js:137:1088)
    at async DevServer.renderToHTML (/Users/daniellaera/Desktop/fullstack-twitter/node_modules/next/dist/server/next-dev-server.js:36:578) {
  clientVersion: '2.22.0',
  errorCode: undefined
```

**Comment by janpio** [comment]
What version of Prisma are you running?
We recently had this issue with a similar error message: https://github.com/prisma/prisma/issues/6328

**Comment by daniellaera** [comment]
"@prisma/client": "^2.22.0", 
"prisma": "^2.22.0",

**Comment by pantharshit00** [comment]
Can you please share your directly structure? I think you are using next js so this is definitely related to the webpack 5 change.

**Comment by daniellaera** [comment]
what exactly want to see? my package.json?

**Comment by pantharshit00** [comment]
Yep, and output of `tree` command inside of that folder so that I can exactly figure out where the schema is located in the project. Feel free to remove any sensitive details from the output.

**Comment by daniellaera** [comment]
Ok I actually fixed my problem: so I had the configuration in my `next.config.js`
module.exports = {
    ```
future: {
        webpack5: false
    },
    devIndicators: {
        autoPrerender: true,
    },
    experimental: {
        turboMode: true
    }
}
```

and the fact of having the experimental mode, (don't exactly remember why I decided to activate this, might trying some Nextjs features I suppose...), for some reason did't load my `.babelrc` and other config files in dev so that caused all possible crashes. and so after downgrading the prisma version and fixed this I upgraded to the latest and now everything works fine even with webpack 5 version.

my next.config.js
```
module.exports = {
    future: {
        webpack5: false
    },
    devIndicators: {
        autoPrerender: true,
    }

my babelrc
```
{
    "presets": ["next/babel"],
    "plugins": [
      "superjson-next" // 👈
    ]
}
```
}
```
