### ISSUE TITLE
When connecting to a non existing database server (or using invalid credentials), the Client error message does not include an Error Code

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7027]
### Bug description

```
C:\Users\Jan\Documents\throwaway\timeoutTest>node script.js
PrismaClientInitializationError2 [PrismaClientInitializationError]: 
Invalid `prisma.user.create()` invocation:


  Can't reach database server at `lkjasdhfasdf.com`:`34234`

Please make sure your database server is running at `lkjasdhfasdf.com`:`34234`.
    at cb (C:\Users\Jan\Documents\throwaway\timeoutTest\node_modules\@prisma\client\runtime\index.js:35104:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (C:\Users\Jan\Documents\throwaway\timeoutTest\script.js:8:17) {
  clientVersion: '2.22.1',
  errorCode: undefined
}
```

### How to reproduce

1. New folder, `npm init -y`, `npm install -D prisma`, `npx prisma init`
2. Add model to schema file
3. `npx prisma generate`
4. Copy over script from https://github.com/prisma/prisma-examples/blob/latest/javascript/script/script.js
5. Set `DATABASE_URL` to non existant one like `postgresql://johndoe:randompassword@lkjasdhfasdf.com:34234/mydb?schema=public`
5. Run `node script.js`
6. Observe the error message above

### Expected behavior

The error message should also include a documented (https://www.prisma.io/docs/reference/api-reference/error-reference) error code.

### Prisma information

see above

### Environment & setup

- OS: Windows
- Database: PostgreSQL, MySQL
- Node.js version: v14.16.1
- Prisma version:

```
C:\Users\Jan\Documents\throwaway\timeoutTest>npx prisma -v
Environment variables loaded from .env
prisma               : 2.22.1
@prisma/client       : 2.22.1
Current platform     : windows
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\migration-engine-windows.exe)Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```

**Comment by janpio** [comment]
Similar behavior for invalid credentials:

```
C:\Users\Jan\Documents\throwaway\timeoutTest>node script.js
PrismaClientInitializationError2 [PrismaClientInitializationError]: 
Invalid `prisma.user.create()` invocation:


  Authentication failed against database server at `localhost`, the provided database credentials for `johndoe` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
    at cb (C:\Users\Jan\Documents\throwaway\timeoutTest\node_modules\@prisma\client\runtime\index.js:35104:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (C:\Users\Jan\Documents\throwaway\timeoutTest\script.js:8:17) {
  clientVersion: '2.22.1',
  errorCode: undefined
}
```

**Comment by pantharshit00** [comment]
I can also reproduce this.

**Comment by garrensmith** [comment]
This seems to be an error in the typescript client. If I run the master branch of the query-engine I get:
```
Nov 18 10:37:22.896  INFO query_engine:Encountered error during initialization:
{"is_panic":false,"message":"Authentication failed against database server at `localhost`, the provided database credentials for `postgres` are not valid.\n\nPlease make sure to provide valid database credentials for the database server at `localhost`.","meta":{"database_user":"postgres","database_host":"localhost"},"error_code":"P1000"}
make: *** [qe] Error 1
```
Notice the error code is defined there. But I can reproduce the above error with prisma 3.5.0 in nodejs. 
```
Please make sure your database server is running at `lkjasdhfasdf.com`:`34234`.
    at cb (/Users/garren/dev/prisma/reports/test1/node_modules/@prisma/client/runtime/index.js:38681:17)
    at async main (/Users/garren/dev/prisma/reports/test1/index.js:8:17) {
  clientVersion: '3.5.0',
  errorCode: undefined
  ```

**Comment by ludralph** [comment]
Closing this in favour of [18813](https://github.com/prisma/prisma/issues/18813)
