### ISSUE TITLE
PANIC in query-engine/core/src/query_graph_builder/read/aggregations/mod.rs:24:18Expected at least one selection for aggregate

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma#7052]
Hi Prisma Team! My Prisma Client just crashed. This is the report:

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | darwin             |
| Prisma Client   | 2.23.0-integration-query-engine-unify-aggregation-api-surface.1|
| Query Engine    | query-engine 2a9102cdc665fdd456107acac63cdf3d4de2e27c|
| Database        | postgres|

## Query
```
query {
  groupByExample(by: [count]) {
    count
    _count {
      _all
    }
  }
}
```

## Logs
```
  prisma:tryLoadEnv Environment variables loaded from /Users/m/dev/src/github.com/prisma/qa-aggregate3/.env  
  prisma:tryLoadEnv Environment variables loaded from /Users/m/dev/src/github.com/prisma/qa-aggregate3/.env  
  prisma:client clientVersion: 2.23.0-integration-query-engine-unify-aggregation-api-surface.1  
  prisma:engine Search for Query Engine in /Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/.prisma/client  
  prisma:engine { cwd: '/Users/m/dev/src/github.com/prisma/qa-aggregate3/prisma' }  
  prisma:engine Search for Query Engine in /Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/.prisma/client  
  plusX Execution permissions of /Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/.prisma/client/query-engine-darwin are fine  
  plusX Execution permissions of /Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '57882' ] }  
  prisma:engine stdout  Starting a postgresql pool with 13 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:57882  
  prisma:engine Search for Query Engine in /Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/.prisma/client  
  plusX Execution permissions of /Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine stdout  PANIC in query-engine/core/src/query_graph_builder/read/aggregations/mod.rs:24:18
Expected at least one selection for aggregate  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/@prisma/client/runtime/index.js:25530:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:467:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine Client Version: 2.23.0-integration-query-engine-unify-aggregation-api-surface.1  
  prisma:engine Engine Version: query-engine 2a9102cdc665fdd456107acac63cdf3d4de2e27c  
  prisma:engine Active provider: postgresql  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:57882
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -61,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 57882
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/Users/m/dev/src/github.com/prisma/qa-aggregate3/prisma' }  
  prisma:engine Search for Query Engine in /Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/.prisma/client  
  plusX Execution permissions of /Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '57886' ] }  
  prisma:engine stdout  Starting a postgresql pool with 13 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:57886  
  prisma:engine Search for Query Engine in /Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/.prisma/client  
  plusX Execution permissions of /Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine stdout  PANIC in query-engine/core/src/query_graph_builder/read/aggregations/mod.rs:24:18
Expected at least one selection for aggregate  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/m/dev/src/github.com/prisma/qa-aggregate3/node_modules/@prisma/client/runtime/index.js:25530:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:467:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
await prisma.example.groupBy({
  by: ["count"],
  _count: true,
})
```

## Schema
```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Example {
  id    String @id @default(cuid())
  count Int
}

```

**Comment by dpetrick** [comment]
A fix is merged for the engine integration branch. Please also test all other aggregations vs field names (sum, avg, ...).
