### ISSUE TITLE
PANIC in libs/prisma-models/src/record.rs:161:30Invalid coercion encountered: ConversionFailure("Float(BigDecimal(\"519.05\"))", "Decimal")

### ISSUE THREAD

**Issue by jonnyleeharris** [prisma/prisma#7061]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.3.0            | 
| OS              | darwin             |
| Prisma Client   | 2.22.1             |
| Query Engine    | query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c|
| Database        | undefined|

## Query
```
{"X":false}
```

## Logs
```
:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:58287
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  prisma:engine     errno: -61,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 58287
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   cwd: '/prisma'
  prisma:engine }  
  prisma:engine Search for Query Engine in /node_modules/.prisma/client  
  plusX Execution permissions of /node_modules/.prisma/client/query-engine-darwin are fine  +2s
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '58295' ] }  
  prisma:engine stdout  Starting a postgresql pool with 17 connections.  
  prisma:engine stdout  Fetched a connection from the pool  +1s
  prisma:engine stdout  Started http server on http://127.0.0.1:58295  
  prisma:engine Search for Query Engine in /node_modules/.prisma/client  
  plusX Execution permissions of /node_modules/.prisma/client/query-engine-darwin are fine  +1s
  prisma:engine Client Version: 2.22.1  
  prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  Fetched a connection from the pool  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  PANIC in libs/prisma-models/src/record.rs:161:30
Invalid coercion encountered: ConversionFailure("Float(BigDecimal(\"519.05\"))", "Decimal")  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (
/node_modules/@prisma/client/runtime/index.js:25530:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:485:12)
  prisma:engine       at endReadableNT (_stream_readable.js:1224:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
let spec = await prisma.line_item_specification_revisions.findUnique({
				where: {
					line_item_revision_id: parseFloat(parent.id)
				},
				include: {
					line_item_specification: {
						select: {
							line_item_edge_rails: true,							
							line_item_mid_rails: true							
						}
					}
				}
			})
```

## Schema
```prisma

model line_item_specification_revisions {
  line_item_revision_id      BigInt                    @unique
  line_item_specification_id BigInt
  order_line_item_revisions  order_line_item_revisions @relation(fields: [line_item_revision_id], references: [order_line_item_revision_id])
  line_item_specification    line_item_specification   @relation(fields: [line_item_specification_id], references: [line_item_specification_id])

  @@id([line_item_revision_id, line_item_specification_id])
}

model line_item_specification {
  line_item_edge_rails              line_item_edge_rails[]
  line_item_mid_rails               line_item_mid_rails[]
  line_item_specification_revisions line_item_specification_revisions[]
}

model line_item_edge_rails {
  line_item_specification_id BigInt
  tier_index                 Int                     @default(0)
  edge                       String
  height                     Decimal                 @db.Decimal
  is_critical                Boolean?
  line_item_specification    line_item_specification @relation(fields: [line_item_specification_id], references: [line_item_specification_id])

  @@unique([line_item_specification_id, tier_index, edge], name: "line_item_edge_rails_line_item_specification_id_tier_index__key")
}

model line_item_mid_rails {
  line_item_specification_id BigInt
  height                     Decimal                 @db.Decimal
  position                   Decimal                 @db.Decimal
  is_critical                Boolean?
  line_item_specification    line_item_specification @relation(fields: [line_item_specification_id], references: [line_item_specification_id])

  @@unique([line_item_specification_id, position], name: "line_item_mid_rails_line_item_specification_id_position_key")
}



```

**Comment by jonnyleeharris** [comment]
If I remove the position from unique constraint and add a primary key to `line_item_mid_rails` table the panic no longer occurs:

```prisma
model line_item_mid_rails {
  line_item_specification_id BigInt
  height                     Decimal                 @db.Decimal
  position                   Decimal                 @db.Decimal
  is_critical                Boolean?
  line_item_mid_rails_id     BigInt                  @id @default(autoincrement())
  line_item_specification    line_item_specification @relation(fields: [line_item_specification_id], references: [line_item_specification_id])
}
```

**Comment by pantharshit00** [comment]
Hey @jonnyleeharris 

Can you please try the dev version once? `npm install prisma@dev @prisma/client@dev`? I remember we changed this conversion very recently.

**Comment by zackify** [comment]
I'm seeing this same issue when using an id and decimal field together

```
  county_key       Decimal                  @id(map: "mp_census_county_0") @db.Decimal(28, 6)
```
thread 'tokio-runtime-worker' panicked at 'Invalid coercion encountered: ConversionFailure("Float(BigDecimal(\"122\"))", "Decimal")', query-engine/prisma-models/src/record.rs:161:30

**Comment by janpio** [comment]
Thanks @zackify for the additional information. Is it enough to have a table with such a field, some data in it and then read the data or how can we trigger the error? If we can reproduce this, we can most probably fix it as well.

**Comment by haydenbriese** [comment]
### Example
Schema excerpt
```
model Example {
  number   Decimal   @id
}
```

Example call
```
await prisma.example.create({
  data: { number: '1000000000' },
});
```

I didn't record this at the time, but I also encountered errors when trying to use very large decimals (think 1e20) even in non-id fields

### Workaround
Use string for the id.
If you need to perform number-specific operations on the data then create a duplicate field 
```
model Example {
  number    String   @id
  number2  Decimal
}
```

**Comment by Weakky** [comment]
Hey,

This was fixed by https://github.com/prisma/prisma-engines/pull/2988 and should be available in the next release.

Closing now, thanks for reporting 🙏
