### ISSUE TITLE
Problems with bigint

### ISSUE THREAD

**Issue by nicolasdanelon** [prisma/prisma#7064]
### Bug description

I can't print the result of my query when inserting data:

```typescript
import { Prisma, PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

export const snakeToCamel = (str: string) =>

function saveIt() {
	const data = {
		order_id: 12938
	};

	prisma.customer_referrals.create({ data })
		.then(a => {
			console.log(a);
		})
		.catch (e => console.log(e))
}

saveIt();
```

### How to reproduce

I'm just runnring the following command:

```bash
$ npx ts-node index.ts
```

### Expected behavior

expecting:

```javascript
{
  id: 8,
  order_id: 12938n,
}
```

but I got

```bash
npx ts-node index.ts
npx: installed 9 in 2.056s
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at /mnt/c/Users/Nicolas/work/prisma-ts/index.ts:19:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

### Prisma information

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = "postgresql://postgres:password@localhost:5432/postgres?schema=public"
}

model customer_referrals {
  id          Int       @id @default(autoincrement())
  order_id    BigInt?   @db.BigInt
}
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v14.15.0
- Prisma version:
```
prisma               : 2.22.1
@prisma/client       : 2.22.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```
```

```

**Comment by JoJk0** [comment]
I've had similar problem before, adding this function as a second argument of JSON.stringify() solved the problem. 

```
export const stringifyBigInt = (_: any, value: any) =>
    typeof value === 'bigint' ? value.toString() : value; // return everything else unchanged
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this with your example, it seems incomplete, looks like you missed something while pasting.

But the problem you are referring is true, JS `JSON.stringify` doesn't know how to serialize `BigInts` and it is according to the spec and that is not going to change: https://tc39.es/proposal-bigint/#sec-serializejsonproperty

What I will suggest is to use the `superjson` library here, it support other types as well which the native implementation doesn't: https://github.com/blitz-js/superjson

The workaround suggested by @JoJk0 also works here.

**Comment by aryanpayomatix** [comment]
facing issue in migration     id           BigInt  @id @default(autoincrement()) @db.BigInt
in prisma postgres
