### ISSUE TITLE
Upsert of big JSON throws the error "P1017 Server has closed the connection"

### ISSUE THREAD

**Issue by vadim-shilov** [prisma/prisma#7074]
### Bug description

Upsert of big JSON throws the error "P1017 Server has closed the connection"

### How to reproduce

Run the code snippet described below

### Expected behavior

Upsert should be finished successfully

### Prisma information

index.js
```
const {PrismaClient} = require('@prisma/client');

function generateData() {
    const result = {};
    for (let i = 0; i < 10; i++) {
        const l1 = {};
        for (let j = 0; j < 100; j++) {
            const l2 = {};
            for (let k = 0; k < 1000; k++) {
                l2[`key${k}`] = { value: k };
            }
            l1[`key${j}`] = l2;
        }
        result[`key${i}`] = l1;
    }
    return result;
}

// This method throws the error described below
//
// PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]:
// Invalid `prisma.dictionary.upsert()` invocation:
//
//
//   Server has closed the connection.
//     at cb (/save_json_err/node_modules/@prisma/client/runtime/index.js:35098:17)
//     at processTicksAndRejections (internal/process/task_queues.js:93:5)
//     at async main (/save_json_err/index.js:26:9) {
//   code: 'P1017',
//   clientVersion: '2.22.1',
//   meta: null
// }
async function main() {
    const name = 'data';
    const data = generateData();
    const updated = new Date();
    const client = new PrismaClient();
    await client.$connect();
    try {
        await client.dictionary.upsert({
            where: {name},
            create: {
                name,
                data,
                updated,
            },
            update: {
                data,
                updated,
            },
        });
        console.log('Success!');
    } catch (err) {
        console.error(err);
    } finally {
        client.$disconnect();
    }
}

main();
```

prisma.schema
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Dictionary {
  name    String   @id
  data    Json
  updated DateTime

  @@map("dictionaries")
}
```

### Environment & setup

- OS: macOS Big Sur v11.3.1, Ubuntu 20
- Database: PostgreSQL
- Node.js version: 14.16.0
- Prisma version:
```
prisma               : 2.22.1
@prisma/client       : 2.22.1
Current platform     : darwin
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this, can you please try again with the latest version: 
```
code/reproductions/issue-7074 is 📦 v1.0.0 via  v14.17.0
❯ yarn start
yarn run v1.22.5
$ ts-node main.ts
Success!
Done in 11.58s.

code/reproductions/issue-7074 is 📦 v1.0.0 via  v14.17.0
❯ npx prisma -v
Environment variables loaded from prisma\.env
prisma               : 2.24.0-dev.23
@prisma/client       : 2.24.0-dev.23
Current platform     : windows
Query Engine         : query-engine 5e7f7c52a0792622c1f7f0698634b86ce6aa7fe8 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 5e7f7c52a0792622c1f7f0698634b86ce6aa7fe8 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 5e7f7c52a0792622c1f7f0698634b86ce6aa7fe8 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 5e7f7c52a0792622c1f7f0698634b86ce6aa7fe8 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 5e7f7c52a0792622c1f7f0698634b86ce6aa7fe8
Studio               : 0.397.0

code/reproductions/issue-7074 is 📦 v1.0.0 via  v14.17.0
❯
```

![image](https://user-images.githubusercontent.com/22195362/119867310-5f6eba80-bf3b-11eb-9132-3243647e0c70.png)

**Comment by vadim-shilov** [comment]
Increasing of memory in k8s specs solved this problem.
```
resources:
    limits:
        memory: 512Mi -> 1024Mi
```

**Comment by janpio** [comment]
Meaning the PostgreSQL instances crashed because they were out of memory?

**Comment by vadim-shilov** [comment]
Yes! The instance is running on the local k8s cluster (minikube) and it's resources limited. I've found some pg logs described cause + I couldn't reproduce the error using docker compose.
