### ISSUE TITLE
value.map is not function

### ISSUE THREAD

**Issue by jason5149** [prisma/prisma#7085]
## Bug description

When I use update with relation updateMany as below picture

![image](https://user-images.githubusercontent.com/10546404/118243685-498bdf00-b4d1-11eb-970a-1871f981083d.png)

I got an exception about "value.map is not function"

Follow this exception I found issue as below picture

![image](https://user-images.githubusercontent.com/10546404/118243935-97084c00-b4d1-11eb-90b6-b58875976321.png)

Actually this "value" contains both "where" and "data" but not an array data

![image](https://user-images.githubusercontent.com/10546404/118244447-1c8bfc00-b4d2-11eb-8f1e-c9ea1f4624ac.png)

Environment & setup
OS: Mac OS
Database: MySQL
Node.js version: v14.16.0
Prisma version: 2.22.1
@prisma/client: 2.22.1

**Comment by janpio** [comment]
Can you please provide us the code as actual text, not as a screenshot? We also need the actual error message if possible.

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.

**Comment by janpio** [comment]
Are you having the same problem @eeve?

**Comment by rained23** [comment]
I am having the same error, happening to me when I nested the updateMany

```
TypeError: value.map is not a function at tryInferArgs (/app/node_modules/@prisma/client/runtime/index.js:48563:18) at valueToArg (/app/node_modules/@prisma/client/runtime/index.js:48380:16)
```

```
this.prismaService.tableName.update({
          where: { id },
          data: {
            something:  true,
            Relation: {
              disconnect: true,
              update: {
                items: {
                  updateMany: {
                    where: { id: { not: null } },
                    data: { name: null },
                  },
                },
              },
            },
          }});
```

**Comment by guilhermeseckert** [comment]
I'm also having the same problem.

`  const results = await prismaClient.alert.update({
    where: {
      id: "cl70ql6d50023emmaic1l73yy",
    },
    data: {
      description: "test",
      AlertAction: {
        updateMany: {
          data: [
            {
              action: "always",
            },
            {
              action: "always",
            },
          ],
          where: { alertId: "cl70ql6d50023emmaic1l73yy" },
        },
      },
    },
  });`

**Comment by guilhermeseckert** [comment]
Im also having the same issue with update many
`const results = await prismaClient.alert.update({
    where: {
      id: "cl70ql6d50023emmaic1l73yy",
    },
    data: {
      description: "test",
      AlertAction: {
        updateMany: {
          data: [
            {
              action: "always",
            },
            {
              action: "always",
            },
          ],
          where: { alertId: "cl70ql6d50023emmaic1l73yy" },
        },
      },
    },
  });
`

**Comment by Saarmann** [comment]
Also receiving this error in update block: 

prisma/client v4.4.0


C:\Users\kaspa\dev\austin-app\db-manager\node_modules\@prisma\client\runtime\index.js:30051
    value: value.map((v) => {
                 ^
TypeError: value.map is not a function 
at tryInferArgs (C:\Users\kaspa\dev\austin-app\dbmanager\node_modules\@prisma\client\runtime\index.js:30051:18)
    at valueToArg (C:\Users\kaspa\dev\austin-app\dbmanager\node_modules\@prisma\client\runtime\index.js:29868:16)
    at C:\Users\kaspa\dev\austin-app\dbmanager\node_modules\@prisma\client\runtime\index.js:30122:18
    at Array.reduce (<anonymous>)
    at objectToArgs (C:\Users\kaspa\dev\austin-app\dbmanager\node_modules\@prisma\client\runtime\index.js:30100:28)
    at tryInferArgs (C:\Users\kaspa\dev\austin-app\dbmanager\node_modules\@prisma\client\runtime\index.js:29998:40)
    at valueToArg (C:\Users\kaspa\dev\austin-app\dbmanager\node_modules\@prisma\client\runtime\index.js:29868:16)
    at C:\Users\kaspa\dev\austin-app\dbmanager\node_modules\@prisma\client\runtime\index.js:30122:18
    at Array.reduce (<anonymous>)
    at objectToArgs (C:\Users\kaspa\dev\austin-app\dbmanager\node_modules\@prisma\client\runtime\index.js:30100:28)


`
 async createGeneralLedgerTrans(dto: CreateGeneralLedgerTransDto): 
  Promise<GeneralLedgerTrans> {
    
    const {
      GLBId,
      BatchCode,
      No,
      Document,
      BatchDate,
      CurrencyCode,
      CurrencyRate,
      TotalAmount,
      PriceInclVat,
      Entries,
    } = dto;

    const glTrans = await this.prismaService.generalLedgerTrans.findUnique({
      where: { GLBId: dto.GLBId },
    });

    if (glTrans) {
      return this.prismaService.generalLedgerTrans.update({
        where: {
          GLBId: GLBId,
        },
        data: {
          GLBId: GLBId,
          BatchCode: BatchCode,
          No: No,
          Document: Document,
          BatchDate: BatchDate,
          CurrencyCode: CurrencyCode,
          CurrencyRate: CurrencyRate,
          TotalAmount: TotalAmount,
          PriceInclVat: PriceInclVat,
          Entries: {
            updateMany: {
              where: { BatchId: GLBId },
              data: Entries,
            },
          },
        },
      });
    }

    return await this.prismaService.generalLedgerTrans.create({
      data: {
        GLBId: GLBId,
        BatchCode: BatchCode,
        No: No,
        Document: Document,
        BatchDate: BatchDate,
        CurrencyCode: CurrencyCode,
        CurrencyRate: CurrencyRate,
        TotalAmount: TotalAmount,
        PriceInclVat: PriceInclVat,
        Entries: {
          createMany: {
            data: Entries,
          },
        },
      },
    });
  }

```

**Comment by prattcmp** [comment]
+1

**Comment by sn0wst0rm** [comment]
@janpio I just stumbled upon this bug in my last nested query.
I'm trying to updateMany a relation field and, when giving it an array, it will fail as described in this issue.

This is very frustrating because I do not know how to fix this issue, and the minified code is not helping...

From what I've seen the runtime tries to .map() a value object that contains `{ where: {....}, data: [....]}`, which obviously fails.

Can you please help me? Thank you!

**Comment by Jayaharshak** [comment]
@janpio Any update on this, in "@prisma/client": "4.9.0" also facing same issue.

**Comment by janpio** [comment]
I can reproduce this with the repository that @eeve provided - thanks! I forked to https://github.com/prisma/reproduction-7085-eeve and updated. Reproduction is as easy as creating a `.env` file with `DATABASE_URL=...`, then running `npx prisma db push` and then `node index.mjs`.

**Comment by janpio** [comment]
A bit weird, but potentially worth trying out for all of you: 
Our [preview feature `jsonProtocol`](https://github.com/prisma/prisma/issues/18095) seems to fix the problem and, at least in @eeve's reproduction, let's the first `create` query succeed. (Then the second query fails, but I am not sure if that is generally a bug, or a problem of the preview feature - anything is possible)

**Comment by janpio** [comment]
An analysis based on the example:
Currently the second query, the `update`, has this `where` inside a nested `updateMany`:
```
where: {
  cloud_app_id: app.id,
  user_id: userId
},
```
That does not match the data model of the to be updated model:
```
model AuthorizesOnCloudApps {
  app    CloudApp @relation(fields: [app_id], references: [id])
  app_id String   @db.VarChar(36)

  authorize    CloudAppAuthorize @relation(fields: [authorize_id], references: [id])
  authorize_id String            @db.VarChar(36)

  created_at DateTime  @db.Timestamptz(6)
  created_by String    @db.VarChar(36)
  updated_at DateTime? @db.Timestamptz(6)
  updated_by String?   @db.VarChar(36)

  @@id([app_id, authorize_id])
  @@map("t_authorize_on_app")
}
```
There is no `cloud_app_id` but only an `app_id`, and there is no `user_id` at all.
When replacing that with the following, the query can successfully be executed:
```
where: {
  app_id: app.id,
},
```

---

When using our `jsonProtocol` preview feature, the original code at least fails with a better error message:

```
  prisma:client:request_handler  PrismaClientKnownRequestError: Unable to match input value to any allowed input type for the field. Parse errors: [Unable to match input value to any allowed input type for the field. Parse errors: [`updateOneCloudApp`: Field does not exist in enclosing type., Invalid argument type. `updateMany` should be of any of the following types: `AuthorizesOnCloudAppsUpdateManyWithWhereWithoutAppInput[]`], Unable to match input value to any allowed input type for the field. Parse errors: [`updateOneCloudApp`: Field does not exist in enclosing type., Invalid argument type. `updateMany` should be of any of the following types: `AuthorizesOnCloudAppsUpdateManyWithWhereWithoutAppInput[]`]]
    at prismaGraphQLToJSError (/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:67:100)
    at zt.buildQueryError (/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:102:902)
    at zt.request (/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:101:4252)
    at async fn.request (/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:174:5395)
    at async t._request (/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:177:10477)
    at async main (file:///workspace/reproduction-7085-eeve/index.mjs:37:21) {
  code: 'P2009',
  clientVersion: '4.12.0',
  meta: { kind: 'Union', errors: [ [Object], [Object] ] }
} +0ms
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms
/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:167
`)}};a(Ni,"ArgumentsRenderingTree");function bc...function Cc(e){return typeof e=="bigint"?e.toString():Oc(e)}a(Cc,"preprocessValueInObject");var Ih=/^(\s*alter\s)/i,Mc=U("prisma:client");function cs(e,t,r){if(t.length>0&&Ih.exec(e))throw new Error(`Running ALTER using ${r} is not supported
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

PrismaClientValidationError: 
Invalid `prisma.cloudApp.update()` invocation:

{
  where: {
    id: "1pqTcsnO5675ZHM7-qu31_aUakQdkHalj-h5"
  },
  data: {
    authorizes: {
      updateMany: {
        where: {
          cloud_app_id: "1pqTcsnO5675ZHM7-qu31_aUakQdkHalj-h5",
          ~~~~~~~~~~~~
          user_id: "test",
?         AND?: AuthorizesOnCloudAppsScalarWhereInput | AuthorizesOnCloudAppsScalarWhereInput[],
?         OR?: AuthorizesOnCloudAppsScalarWhereInput[],
?         NOT?: AuthorizesOnCloudAppsScalarWhereInput | AuthorizesOnCloudAppsScalarWhereInput[],
?         app_id?: StringFilter | String,
?         authorize_id?: StringFilter | String,
?         created_at?: DateTimeFilter | DateTime,
?         created_by?: StringFilter | String,
?         updated_at?: DateTimeNullableFilter | DateTime | Null,
?         updated_by?: StringNullableFilter | String | Null
        },
        data: {
          updated_at: new Date("2023-04-06T22:14:32.583Z"),
          updated_by: "test"
        }
      }
    }
  }
}

Unknown argument `cloud_app_id`.
```

**Comment by janpio** [comment]
When using our `jsonProtocol` preview feature, the original code at least fails with a better error message:

```
  prisma:client:request_handler  PrismaClientKnownRequestError: Unable to match input value to any allowed input type for the field. Parse errors: [Unable to match input value to any allowed input type for the field. Parse errors: [`updateOneCloudApp`: Field does not exist in enclosing type., Invalid argument type. `updateMany` should be of any of the following types: `AuthorizesOnCloudAppsUpdateManyWithWhereWithoutAppInput[]`], Unable to match input value to any allowed input type for the field. Parse errors: [`updateOneCloudApp`: Field does not exist in enclosing type., Invalid argument type. `updateMany` should be of any of the following types: `AuthorizesOnCloudAppsUpdateManyWithWhereWithoutAppInput[]`]]
    at prismaGraphQLToJSError (/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:67:100)
    at zt.buildQueryError (/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:102:902)
    at zt.request (/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:101:4252)
    at async fn.request (/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:174:5395)
    at async t._request (/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:177:10477)
    at async main (file:///workspace/reproduction-7085-eeve/index.mjs:37:21) {
  code: 'P2009',
  clientVersion: '4.12.0',
  meta: { kind: 'Union', errors: [ [Object], [Object] ] }
} +0ms
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms
/workspace/reproduction-7085-eeve/node_modules/@prisma/client/runtime/library.js:167
`)}};a(Ni,"ArgumentsRenderingTree");function bc...function Cc(e){return typeof e=="bigint"?e.toString():Oc(e)}a(Cc,"preprocessValueInObject");var Ih=/^(\s*alter\s)/i,Mc=U("prisma:client");function cs(e,t,r){if(t.length>0&&Ih.exec(e))throw new Error(`Running ALTER using ${r} is not supported
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

PrismaClientValidationError: 
Invalid `prisma.cloudApp.update()` invocation:

{
  where: {
    id: "1pqTcsnO5675ZHM7-qu31_aUakQdkHalj-h5"
  },
  data: {
    authorizes: {
      updateMany: {
        where: {
          cloud_app_id: "1pqTcsnO5675ZHM7-qu31_aUakQdkHalj-h5",
          ~~~~~~~~~~~~
          user_id: "test",
?         AND?: AuthorizesOnCloudAppsScalarWhereInput | AuthorizesOnCloudAppsScalarWhereInput[],
?         OR?: AuthorizesOnCloudAppsScalarWhereInput[],
?         NOT?: AuthorizesOnCloudAppsScalarWhereInput | AuthorizesOnCloudAppsScalarWhereInput[],
?         app_id?: StringFilter | String,
?         authorize_id?: StringFilter | String,
?         created_at?: DateTimeFilter | DateTime,
?         created_by?: StringFilter | String,
?         updated_at?: DateTimeNullableFilter | DateTime | Null,
?         updated_by?: StringNullableFilter | String | Null
        },
        data: {
          updated_at: new Date("2023-04-06T22:14:32.583Z"),
          updated_by: "test"
        }
      }
    }
  }
}

Unknown argument `cloud_app_id`.
```

**Comment by janpio** [comment]
Can someone else provide a similarly reproducible example as @eeve?
