### ISSUE TITLE
PANIC in query-engine/core/src/interpreter/query_interpreters/nested_read.rs:79:561

### ISSUE THREAD

**Issue by gustawdaniel** [prisma/prisma#7099]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.17.0           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.22.1             |
| Query Engine    | query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c|
| Database        | undefined|

## Query
```
query {
  findManygroup_chats(where: {
    participants: {
      some: {
        id: 5
      }
    }
    deleted_at: null
  }) {
    id
    deleted_at
    participants {
      email
      full_name
      avatar
    }
    messages {
      created_at
    }
  }
}
```

## Logs
```
pp%2Fnode_modules%2F.prisma%2Fclient%0AplusX+Execution+permissions+of+%2Fapp%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-debian-openssl-1.1.x+are+fine%0Aprisma%3Aengine+%7B+flags%3A+%5B+%27--enable-raw-queries%27%2C+%27--port%27%2C+%2744511%27+%5D+%7D%0Aprisma%3Aengine+stdout++Starting+a+mysql+pool+with+3+connections.%0Aprisma%3Aengine+stdout++Started+http+server+on+http%3A%2F%2F127.0.0.1%3A44511%0Aprisma%3Aengine+Search+for+Query+Engine+in+%2Fapp%2Fnode_modules%2F.prisma%2Fclient%0AplusX+Execution+permissions+of+%2Fapp%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-debian-openssl-1.1.x+are+fine%0Aprisma%3Aengine+Client+Version%3A+2.22.1%0Aprisma%3Aengine+Engine+Version%3A+query-engine+60cc71d884972ab4e897f0277c4b84383dddaf6c%0Aprisma%3Aengine+Active+provider%3A+mysql%0Aprisma%3Aengine+stdout++PANIC+in+query-engine%2Fcore%2Fsrc%2Finterpreter%2Fquery_interpreters%2Fnested_read.rs%3A79%3A56%0A1%0Aprisma%3Aengine+%7B%0A++error%3A+SocketError%3A+other+side+closed%0A++++++at+Socket.onSocketEnd+%28%2Fapp%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A25530%3A24%29%0A++++++at+Socket.emit+%28events.js%3A388%3A22%29%0A++++++at+endReadableNT+%28internal%2Fstreams%2Freadable.js%3A1336%3A12%29%0A++++++at+processTicksAndRejections+%28internal%2Fprocess%2Ftask_queues.js%3A82%3A21%29+%7B%0A++++code%3A+%27UND_ERR_SOCKET%27%0A++%7D%0A%7D%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A&title=PANIC+in+query-engine%2Fcore%2Fsrc%2Finterpreter%2Fquery_interpreters%2Fnested_read.rs%3A79%3A56%0A1&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue. 

    at NodeEngine.throwAsyncErrorIfExists (/app/node_modules/@prisma/client/runtime/index.js:27787:21)
    at NodeEngine.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:27101:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async NodeEngine.request (/app/node_modules/@prisma/client/runtime/index.js:27721:9)
    at async cb (/app/node_modules/@prisma/client/runtime/index.js:35068:26)
prisma:engine { cwd: '/app' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '41675' ] }
prisma:engine stdout  Starting a mysql pool with 3 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:41675
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine Client Version: 2.22.1
prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c
prisma:engine Active provider: mysql
prisma:engine stdout  PANIC in query-engine/core/src/interpreter/query_interpreters/nested_read.rs:79:56
1
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:25530:24)
      at Socket.emit (events.js:388:22)
      at endReadableNT (internal/streams/readable.js:1336:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:41675
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 41675
  }
}
prisma:engine { cwd: '/app' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '40375' ] }
prisma:engine stdout  Starting a mysql pool with 3 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:40375
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine Client Version: 2.22.1
prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c
prisma:engine Active provider: mysql
prisma:engine stdout  PANIC in query-engine/core/src/interpreter/query_interpreters/nested_read.rs:79:56
1
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:25530:24)
      at Socket.emit (events.js:388:22)
      at endReadableNT (internal/streams/readable.js:1336:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'UND_ERR_SOCKET'
  }
}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by gustawdaniel** [comment]
Error was connected with String and Json types.
In database there was `String` in schema `Json`.
Problem was connected with other orm that works on the same database.
