### ISSUE TITLE
API calls failing with Error querying the database: db error: FATAL: remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by shwethashyam1** [prisma/prisma#7120]
### Bug description

I have been running my app on GCP that connects to a postgres instance also running in GCP, for the past few months. However, since yesterday, my REST API calls stopped working. 

I have been getting this error: 
Error querying the database: db error: FATAL: remaining connection slots are reserved for non-replication superuser connections

I have been initializing one prisma instance per endpoint (total 8 endpoints) and till date have had zero issues using connection_limit=80&pool_timeout=50 on the DB string.

I am not sure if it is from have idle open connections that aren't closing or if it is from my prisma queries or some other issue. Can you kindly advise me on how to fix this issue? Any help would be much appreciated.
Thank you

```
Default
2021-05-17 17:10:00.614 GMTInvalid `prisma instance.findMany()` invocation:
Default
2021-05-17 17:10:00.614 GMT
Default
2021-05-17 17:10:00.614 GMT
Default
2021-05-17 17:10:00.614 GMT Error querying the database: db error: FATAL: remaining connection slots are reserved for non-replication superuser connections
Default
2021-05-17 17:10:00.614 GMT at cb (/server/models/prisma-client/runtime/index.js:79166:17)
Default
2021-05-17 17:10:00.614 GMT at processTicksAndRejections (internal/process/task_queues.js:97:5)
Default
2021-05-17 17:10:00.614 GMT(node:14) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
Default
2021-05-17 17:12:00.721 GMT(node:14) UnhandledPromiseRejectionWarning: Error:
Default
2021-05-17 17:12:00.721 GMTInvalid `prisma.events.findMany()` invocation:
Default
2021-05-17 17:12:00.721 GMT

```

### Environment & setup

- OS:  MacOS
- Database: PSQL
- Node.js version:  14
- Prisma version: 2.18.0

```

```

### Prisma Version

```
2.18.0

```

**Comment by janpio** [comment]
Hi @shwethashyam1, the error message you mention in the title indeed means that all connections are in use and no new ones can be opened. Do you maybe have monitoring on that database that can show you the open and idle or active connections, optimally in relation to your database connection limit?

The `connection_limit=80` you mentioned, times 8 instances/endpoints would mean that in theory your applications can in parallel open 640 connections. Is that lower than the number of maximum supported connections of your database instance?

Your 8 instances are all running constantly I assume?

**Comment by shwethashyam1** [comment]
Hi janpio, apologies for the late reply! I completely missed this comment. You are right in (the implication) that the # connections may be higher than the number of maximum supported connections of your database instance.

That is exactly the case. My cloudSQL database supports up to 250 connections.

As for the 8 instances, about 5 of them are cron jobs. The remaining three are REST APIs.

Does this mean I will need to reduce the connection limit?

**Comment by janpio** [comment]
Probably yes, or add some retry middleware that catches the error message, waits a bit and just tries again (this assumes that e.g. the cronjobs make sure to free the connections again after they have been used and do not just keep them open for an hour until the next run). The math should work out in a way that you will not go over the number available.

(Often the cheaper and easier solution is to just increase the limit by paying a bit more though.)

**Comment by shwethashyam1** [comment]
So I figured out what the issue was. Sometimes (maybe 1 in 10 times or less often), when the prisma query is incorrect (for e.g. if I have incorrectly specified a field or a field doesn't exist), prisma is not throwing the error itself.

Instead it opened a lot of prisma connections and doesn't seem to close it -- so subsequent prisma queries ended up throwing the "fatal db.." error. I haven't enforced typescript so that could a way I can prevent incorrect queries to begin with. But perhaps could there be an issue also with prisma's error handling messages?

**Comment by janpio** [comment]
Absolutely, if you have a reproduction for this it would be amazing. We should really try to fix this of course.

**Comment by shwethashyam1** [comment]
Hi @janpio 
struggling to repro this error even though it still happens sometimes (especially now when running my jest tests). Should I close this for now, or keep it open?

**Comment by janpio** [comment]
Let's keep it open a bit and you just come back to it if you find a reproduction or get more information - otherwise we will close it in a few weeks or months.

**Comment by shwethashyam1** [comment]
Hi @janpio an update: this also seems to happen more when I am running my app on localhost and then deploying it to google cloud after. There is a lot of query-engine-darwin processes that I then manually have to kill to prevent this error from happening in google cloud. Should I try adding ?pgbouncer=true in my connection string?

**Comment by janpio** [comment]
If you are not using PgBouncer for Postgres, no.

Are you talking to the same database locally as on your deployment on Google Cloud? If you have many local query engine processes running, this would make sense that it blocks a lot of connections. The question then becomes: Why do you have these many local connections open?

If I understand your code snippet above correctly, it should make sure you only have 1 PrismaClient instance running usually that gets reused across the app, not instantiate new ones all over the place. Can you observer how the number of open Query Engine Processes increases?

We currently have a preview feature `nApi` which uses a different architecture to run the Engine, which should not be in danger of having the same behavior. Maybe you can try that out: https://github.com/prisma/prisma/issues/6301

**Comment by shwethashyam1** [comment]
Yes, the database url is exactly the same and you are right, technically, with the above prisma client in the code snippet, it shouldn't spawn new instances so rapidly. 

Running app on localhost w/o pgAdmin 4:  It usually goes up to ~50 query-engine-darwin processes on my activity monitor when the error happens.

Deploying as a container on google cloud: Sometimes I have about 6-8 query-engine-darwin processes open (even after killing/quitting pgAdmin 4), when this error pops up. 

I will look into nApi, thank you!

**Comment by janpio** [comment]
> Running app on localhost w/o pgAdmin 4: It usually goes up to ~50 query-engine-darwin processes on my activity monitor when the error happens.

Does it go up first, and then the error or the other way around? I would expect it going up over time to cause the error sooner or later.

**Comment by shwethashyam1** [comment]
I usually check the processes after encountering the error and it is around 50+. Then I terminate all of them locally and wait for the error to happen again - by then the # processes would have increased to the same.

**Comment by janpio** [comment]
Ok then this is the reason for your problem.

Maybe observe the process list to see how it goes from 1 to 2 (or whatever starts that increase) and see if you can identify the action that does that. Something you are doing - or your code is - has that effect and should be fixed.

**Comment by shwethashyam1** [comment]
Ok I will look into it :)

**Comment by Sytten** [comment]
Connection pool not killing idle connections is expected, I am working on it on https://github.com/importcjj/mobc/pull/60

In localhost make sure that if you are running ts-node or npx or other that it properly kills children. i had instances where the engine was not properly killed if the parent didnt call sigterm or if the application catched the signal and didnt call close on the prisma client.

**Comment by joshsny** [comment]
I have experienced this twice in a production app. The situation resolves itself after 5-10 minutes usually, but all Prisma queries return this error during that time.

**Comment by sonipranjal** [comment]
Hi, I am facing the same issue, I am using `cloud SQL` and running a containerized `nestjs` app on cloud run.
 
<img width="1677" alt="Screenshot 2022-03-08 at 11 33 50 PM" src="https://user-images.githubusercontent.com/43893639/157298493-b2a92c5c-1027-463b-af43-0f4091962d03.png">

**Comment by Sytten** [comment]
@garrensmith This is due to the reaper not doing its job after a load spike (and being bad in general). My PR on original mobc should help/point in the right direction. https://github.com/importcjj/mobc/pull/60

**Comment by garrensmith** [comment]
@callumlocke can you confirm what version of Prisma you are using?

@Sytten thanks. Once I have a moment I'll take a look.

**Comment by irunner-toptal** [comment]
I'm having this issue with `"@prisma/client": "^4.10.1"` :(

**Comment by Venkat03003** [comment]
To fix this issue ,Actually  ‎
💁

1. I added  **prisma.$disconnect();** after each query.

```
    const degreeData = await prisma.degree.findUnique({
      where: where,
    }).finally(() => {
      prisma.$disconnect();
    });
```
2. Then we added **connection_limit=20&pool_timeout=50**
Based on the maximum pool connection we have
**To see the maximum connection in postgres**
`SHOW max_connections;`
OR
`SELECT name, setting FROM pg_settings WHERE name = 'max_connections' OR name = 'max_worker_processes';`

**And also to terminate all the  connected connection**

`SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = 'db_name'  AND pid <> pg_backend_pid();`

3. Then , I removed `await Promise.all([query1, query2]) `and make that as seperate query.

Now it was fixed.

Prisma Team , kindly confirm this changes , I have made are correct and about each points.

**Thank you **  😃😍

**Comment by jkomyno** [comment]
Hi @shwethashyam1, @Sytten, and @Venkat03003, we are investigating how to reproduce this issue.
From my understanding, this issue presents itself when a long-running server has a Prisma Client connected to a Postgres database, as some connections from the pool are leaking. What's not clear is whether this only happens with the GCP Postgres instances, or with any Postgres instance. Would you consider [this](https://github.com/garrensmith/mobc-error-example) a faithful reproduction of this issue? If so, it looks like the problem is solved as of mobc 0.8.1 (https://github.com/importcjj/mobc/issues/63), which we have pulled in as of `prisma@4.14.0` (https://github.com/prisma/prisma-engines/pull/3905). Just in case, I encourage you all to try again with the most recent Prisma version (`5.0.0`) to assess whether this issue is still present. Thanks!

> i had instances where the engine was not properly killed if the parent didn't call sigterm or if the application catched the signal and didnt call close on the prisma client.

As far as I know, we've fixed a bug related to the Prisma Query Engine not terminating properly several months ago, but that doesn't exclude some other bug still exists. 

> Prisma Team, kindly confirm these changes

@Venkat03003, which Prisma version did you use in [this comment above](https://github.com/prisma/prisma/issues/7120#issuecomment-1601883121)?

**Comment by lanfersieckj** [comment]
Hello!

Unfortunetely, we are also experiencing this issue. Same scenarioas everyone else has discussed: Everything seems to be working fine then suddenly our connection spikes and the app becomes inactive for ~5 min until it eventually fixs itself.

We have a web app that uses Prisma to interact with a PostgreSQL DB.

Originally we were using Prisma version 3.14, but after reading this we updated our packages to version 5.0. Sadly, the issue still comes up. 

<img width="1896" alt="Screenshot 2023-07-19 at 10 34 40 AM" src="https://github.com/prisma/prisma/assets/71734504/c9128736-ba48-47ba-ad52-05cea220efc6">

Here is a graph from AWS showing the connection spikes where we are encountering the issues.

I have not been able to reproduce the issue. The spikes seem to be completely random.

Reading through this tread. I saw that @[Venkat03003](https://github.com/Venkat03003) manually disconnected his connection. This is something I have not tried yet. However, my assumption is that this is not necessary with Prism’s connection pooling. Also, reading this connection guide from Prisma (https://www.prisma.io/docs/guides/performance-and-optimization/connection-management) it explicitly says: “You do not need to explicitly $disconnect().”

I am not sure if this is an issue with Prisma or if this is some kind of issue on our end. We are continuing to investigate the situation. Just thought I would contribute to the matter to keep the discussion alive.

Thanks

**Comment by jackypan1989** [comment]
I got this, too!

We are building things on Vercel with Prisma + Supabase DB.

**Comment by lanfersieckj** [comment]
Hi Jacky!

Sorry, it has been a few weeks since you commented. I figured I would share some updates we had though.

Originally, I do not think we had the pooling set up properly. We were just connecting directly to our db: "postgresql//...." Then I was made aware of Prisma's Data Proxy service. THIS was the connection pooling service we were looking for. Now we would connect to the pooling service: "prisma//..." So, we had set that up. Unfortunately, we were still having problems. However this time it was different. Instead of it being the connection limit, we were getting 504 errors because our requests were timing out. After reaching out to Prisma, in turned out it was a bug on their end. Nurul worked with me on this and his service was fantastic. 

Eventually I was informed it was fixed, and we were invited to use Prisma Accelerate which contains their Data Proxy service and things seem to working great. We even noticed significant improvements in our load times. Here is what our connection chart looks like now for the past 4 weeks:

<img width="1699" alt="Screenshot 2023-08-25 at 10 03 58 AM" src="https://github.com/prisma/prisma/assets/71734504/b40ae67d-dc55-4f4a-a43e-92bcc8221eb2">

Hope this helps!

-Joey

**Comment by janpio** [comment]
Does anyone have an idea on how to reproduce this behavior of the in-use connection exploding?
Does this go _beyond_ your configured Pool `connection_limit` when it happens or does it just use all of them?

**Comment by Sytten** [comment]
@janpio its been a while since I touched that code, but here is a typical usecase:
- Smaller postgres DB with connection limit of 100
- Service with connection pool of max 20 x 3 instances (60 connections total max)
- You do a blue/green type update of services, that spawns 3 new instances
- If you are under load the new services will try to grab new connections as soon as they receive traffic
- GCP Cloud Run doesnt have guarantees and I have seen some containers take up to 10m to get killed
- Usually to counter that you set an aggressive idle timeout, but for a long time the connection pool of prisma didnt enforce those (in the background at least). I think this is fixed?
- That results in connection limit errors that was originally posted 2y ago

So my take away before closing would be:
- Write documentation around this issue and the connection limit of postgres
- Suggest users use some kind of pooler or prisma proxy to fix it
- if not possible, suggest they increase the connection limit of postgres if they can (usually I set the limit to 2x the expected usage to have my rolling update buffer)
- Also suggest and explain how to set the connection idle timeout and how this will impact (pros and cons) the application

Also double check that the idle timeout is actually respected before all that 😅

I think it can be a strong argument to use prisma proxy for many potential customers since technical and non technical will be able to appreciate the non negligible effort that needs to be done to avoid hitting a DB connection limit when running many instances of an application.

**Comment by venkateshb-icanio** [comment]
@Sytten @aliedp @garrensmith @janpio @callumlocke @jackypan1989 @Jolg42  could you guys give detailed view about pool management in NodeJS with Prisma  and Postgres db.


Why we need to append in this postgres db url with connection_limit=20&pool_timeout=50
what is connection_limit and pool_timeout

About Ram Size , and buffer Size (For Every Query , for operations it will use some memory) in Postgres reated to Postgres.

while managing pool , we have to consider Ram , buffer size , pool timeout , and connection_limit for each instance.
 Anyone kindly explain this about above points in detailed view and share your points and thoughts regarding that.

**Comment by janpio** [comment]
@venkateshb-icanio It is not appropriate to mention a list of users in a comment that is not about the original issue. Please don't do this (I will edit teh @ mentioned out of your message) and open a new discussion instead (without at-mentioning anyone). Thank you.

**Comment by janpio** [comment]
> * Service with connection pool of max 20 x 3 instances (60 connections total max)
> * You do a blue/green type update of services, that spawns 3 new instances
> * If you are under load the new services will try to grab new connections as soon as they receive traffic
> * GCP Cloud Run doesnt have guarantees to kill old containers and I have seen some containers take up to 10m to get killed

So, the situation you describe it is more or less expected to run into this error, correct?

> * Usually to avoid that problem that you set an aggressive idle timeout (10-60s), but for a long time the connection pool of prisma didnt enforce those (in the background at least). I think this is fixed?

Isn't an idle timeout enforced on the database side (considering that Prisma does not offer an option to set one for the connection pool, it has to be) so the connections should be closed from the server side and hence not take up connections any more? (Only Prisma will still potentially think the connection is still open, but as that is on the old deployment it will not try to run a query any more).

Am I missing something?

Your other points are of course correct.

**Comment by Sytten** [comment]
> So, the situation you describe it is more or less expected to run into this error, because the deployment can indeed end up using more connections than the database can provide, correct?

Correct but the pool and the engine can help mitigate this. It can retry when it sees this error and it can kill idle connections.

> Isn't an idle timeout enforced on the database side (considering that Prisma does not offer an option to set one for the connection pool, it has to be) so the connections should be closed from the server side and hence not take up connections any more? (Only Prisma will still potentially think the connection is still open, but as that is on the old deployment it will not try to run a query any more).

Usually the idle timeout is handled by the client pool. I know the setting postgres `idle_in_transaction_session_timeout` exists but usually its locked by the cloud provider and AFAIK prisma doesn't have a way to run code on connection open so you cant easily set it on each connection.

I believe I added the support for idle timeout in quaint more than a year ago, but it never was documented? But also it didnt work in the past because you need a reaper background thread or tokio task to kill the connections. I think that was fixed in mobc by someone at Prisma a couple months ago.

So like I said it kinda "works as intended" but prisma could help devs handle the error better and reduce the occurrence of it (and its a good selling point for your managed service).

**Comment by frogeth** [comment]
any update on this? I'm currently having this issue using Prisma, Postgres and Digital Ocean.

**Comment by f4i2u1** [comment]
This problem also exists on supabase and github actions images. Any updates on this please?

**Comment by yasseralsaidi** [comment]
any update here, every time i need to restart the db server.

**Comment by siddjellali** [comment]
any update on that ?

**Comment by ananay** [comment]
There's a similar problem where hot reloading causes too many connections to be open. If you're one of those, please use the following to resolve this:

https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections#prevent-hot-reloading-from-creating-new-instances-of-prismaclient


More specifically, just create a client.ts file to ensure a single instance of `PrismaClient` stays. Hope this helps!

**Comment by nikolaschou** [comment]
I solved it with this code. I hope it can be helpful to someone. 

`import { INestApplication, Injectable, OnModuleInit, Inject } from '@nestjs/common';
import { PrismaClient, Prisma } from '@prisma/client';
import { REQUEST } from '@nestjs/core';
import { ApmHelper } from '...';
import apm from 'elastic-apm-node';
import { transformSqlShort, transformSqlDetailed } from './instrumentationUtil';

type Event = { timestamp: Date; query: string; params: any; duration: number };
const MAX_LABEL_LENGTH = 1000;
@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  constructor(@Inject(REQUEST) private request: Request) {
    super({
      log: [
        {
          level: 'query',
          emit: 'event',
        },
        {
          level: 'info',
          emit: 'event',
        },
        {
          level: 'warn',
          emit: 'event',
        },
        {
          level: 'error',
          emit: 'event',
        },
      ],
    });
    
    this.$use(async (params, next) => {
      const span = ApmHelper.Instance.getApmAgent().startSpan(
        `${params.model}.${params.action}`,
        `prisma`,
        params.dataPath.join('.'),
      ) as apm.Span;
      ApmHelper.Instance.getApmAgent().currentSpan?.setLabel('prisma:model', params.model);
      try {
        return await next(params);
      } catch (error) {
        throw error;
      } finally {
        if (span) span.end();
      }
    });
    // This will in fact log the queries but they will not be correctly shown in the span tree.
    this.$on('query' as never, async (e) => {
      const e2 = e as Event;
      const agent = ApmHelper.Instance.getApmAgent();
      const isTransactionSampled = (agent.currentTransaction as any)?.sampled || false;
      if (agent.currentTransaction && isTransactionSampled) {
        const span = agent.currentSpan;
        if (span) {
          assignLabels(span, e2);
        } else {
          const endTime = e2.timestamp.getTime();
          const startTime = new Date(endTime - e2.duration);
          const options: apm.SpanOptions = { startTime: startTime.getTime() };
          const span2 = agent.currentTransaction?.startSpan(transformSqlShort(e2.query), 'db', options);
          if (span2) {
            assignLabels(span2, e2);
            span2?.end(endTime);
          }
        }
      }

      function assignLabels(span: apm.Span | null, _e: Event) {
        span?.setLabel('db_statement', transformSqlDetailed(_e.query));
        span?.setLabel('db_statement_raw', getStr(_e.query));
        span?.setLabel('db_params', getStr(_e.params));
      }
    });
  }

  async onModuleInit() {
    await this.$connect();
  }

  async enableShutdownHooks(app: INestApplication) {
    process.on('beforeExit', async () => {
      await app.close();
    });
  }

function getStr(params: any): apm.LabelValue {
  try {
    return JSON.stringify(params).substring(0, MAX_LABEL_LENGTH);
  } catch (error: any) {
    return 'Error parsing params: ' + typeof params + ' ' + error?.message;
  }
}
`

**Comment by eduardolundgren** [comment]
Any updates on this?
