### ISSUE TITLE
serverless-plugin-optimize can't parsing @prisma/client.

### ISSUE THREAD

**Issue by ltnscp9028** [prisma/prisma#7180]
### Bug description

serverless-plugin-optimize can't parsing @prisma/client.
 I disabled serverless-plugin-optimize, It's work well.
But I add serverless-plugin-optimize, It's crash.

https://github.com/ltnscp9028/prisma-optimize-error

### Expected behavior

It work's packaged.

### Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int      @default(autoincrement()) @id
  createdAt DateTime @default(now())
  title     String
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id]) // renamed from `User` -> `author`
  authorId  Int     // relation scalar field
}

model Profile {
  id     Int     @default(autoincrement()) @id
  bio    String?
  userId Int     @unique  // relation scalar field
  user   User    @relation(fields: [userId], references: [id]) // renamed from `User` -> `user`
}

model User {
  id      Int      @default(autoincrement()) @id
  email   String   @unique
  name    String?
  posts   Post[]   // renamed from `Post` -> `posts`
  profile Profile? // renamed from `Profile` -> `profile`
}
```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
prisma               : 2.23.0
@prisma/client       : 2.23.0
Current platform     : darwin
Query Engine         : query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt adf5e8cba3daf12d456d911d72b6e9418681b28b (at ../node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : adf5e8cba3daf12d456d911d72b6e9418681b28b
Studio               : 0.393.0
```

**Comment by ltnscp9028** [comment]
@janpio Hello, I asked in slack ! I make issue and I hope you can review this issue.
Thank's for your help :)

**Comment by janpio** [comment]
Can you share the message for the crash you are getting?

We will try your reproduction now to see what is going on.

**Comment by ltnscp9028** [comment]
@janpio 
```
 Syntax Error -------------------------------------------
 
  SyntaxError: Unexpected token (19382:12) while parsing /Users/hansangjin/Desktop/prisma-lambda/node_modules/@prisma/client/runtime/index.js while parsing file: /Users/hansangjin/Desktop/prisma-lambda/node_modules/@prisma/client/runtime/index.js
      at DestroyableTransform.end [as _flush] (/Users/hansangjin/Desktop/prisma-lambda/node_modules/insert-module-globals/index.js:114:21)
      at DestroyableTransform.prefinish (/Users/hansangjin/Desktop/prisma-lambda/node_modules/readable-stream/lib/_stream_transform.js:138:10)
      at DestroyableTransform.emit (events.js:315:20)
      at DestroyableTransform.EventEmitter.emit (domain.js:482:12)
      at prefinish (/Users/hansangjin/Desktop/prisma-lambda/node_modules/readable-stream/lib/_stream_writable.js:619:14)
      at finishMaybe (/Users/hansangjin/Desktop/prisma-lambda/node_modules/readable-stream/lib/_stream_writable.js:627:5)
      at endWritable (/Users/hansangjin/Desktop/prisma-lambda/node_modules/readable-stream/lib/_stream_writable.js:638:3)
      at DestroyableTransform.Writable.end (/Users/hansangjin/Desktop/prisma-lambda/node_modules/readable-stream/lib/_stream_writable.js:594:41)
      at DestroyableTransform.onend (/Users/hansangjin/Desktop/prisma-lambda/node_modules/readable-stream/lib/_stream_readable.js:577:10)
      at Object.onceWrapper (events.js:421:28)
      at DestroyableTransform.emit (events.js:327:22)
      at DestroyableTransform.EventEmitter.emit (domain.js:482:12)
      at endReadableNT (/Users/hansangjin/Desktop/prisma-lambda/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.1
     Framework Version:         1.74.1 (standalone)
     Plugin Version:            3.6.14
     SDK Version:               2.3.1
     Components Version:        2.31.6
```

**Comment by janpio** [comment]
I can confirm this is failing as described:

```
C:\Users\Jan\Documents\throwaway\prisma-optimize-error>yarn package        
yarn run v1.22.0
$ serverless package
Serverless: DOTENV: Could not find .env file.
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Optimize: starting engines
Serverless: Optimize: prisma-aws-lambda-example-dev-status
Serverless: Optimize: prisma-aws-lambda-example-dev-seed
Serverless: Optimize: prisma-aws-lambda-example-dev-getUsers
Serverless: Optimize: prisma-aws-lambda-example-dev-createUser
Serverless: Optimize: prisma-aws-lambda-example-dev-getPosts
 
 Syntax Error --------------------------------------------

  SyntaxError: Unexpected token (19382:12) while parsing C:\Users\Jan\Documents\throwaway\prisma-optimize-error\node_modules\@prisma\client\runtime\index.js while parsing file: C:\Users\Jan\Documents\throwaway\prisma-optimize-error\node_modules\@prisma\client\runtime\index.js
      at DestroyableTransform.end [as _flush] (C:\Users\Jan\Documents\throwaway\prisma-optimize-error\node_modules\insert-module-globals\index.js:114:21)
      at DestroyableTransform.prefinish (C:\Users\Jan\Documents\throwaway\prisma-optimize-error\node_modules\readable-stream\lib\_stream_transform.js:138:10)
      at DestroyableTransform.emit (events.js:315:20)
      at DestroyableTransform.EventEmitter.emit (domain.js:467:12)
      at prefinish (C:\Users\Jan\Documents\throwaway\prisma-optimize-error\node_modules\readable-stream\lib\_stream_writable.js:619:14)
      at finishMaybe (C:\Users\Jan\Documents\throwaway\prisma-optimize-error\node_modules\readable-stream\lib\_stream_writable.js:627:5)
      at endWritable (C:\Users\Jan\Documents\throwaway\prisma-optimize-error\node_modules\readable-stream\lib\_stream_writable.js:638:3)
      at DestroyableTransform.Writable.end (C:\Users\Jan\Documents\throwaway\prisma-optimize-error\node_modules\readable-stream\lib\_stream_writable.js:594:41)
      at DestroyableTransform.onend (C:\Users\Jan\Documents\throwaway\prisma-optimize-error\node_modules\readable-stream\lib\_stream_readable.js:577:10)
      at Object.onceWrapper (events.js:421:28)
      at DestroyableTransform.emit (events.js:327:22)
      at DestroyableTransform.EventEmitter.emit (domain.js:467:12)
      at endReadableNT (C:\Users\Jan\Documents\throwaway\prisma-optimize-error\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.16.1
     Framework Version:         2.42.0 (local)
     Plugin Version:            5.1.2
     SDK Version:               4.2.2
     Components Version:        3.10.0

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I opened a PR for the changes I make during the investigation.

**Comment by janpio** [comment]
I can also confirm that disabling `serverless-plugin-optimize` in the configuration makes `yarn package` work.

**Comment by janpio** [comment]
Via https://github.com/prisma/prisma/issues/5392 I found this: https://github.com/FidelLimited/serverless-plugin-optimize/issues/113 It also includes instructions for a workaround: https://github.com/FidelLimited/serverless-plugin-optimize/issues/113#issuecomment-824401619

In general it does not seem that https://github.com/FidelLimited/serverless-plugin-optimize is very well maintained and active any more. Is there maybe an alternative that you can use?

**Comment by ltnscp9028** [comment]
@janpio Thanks +1: . I try server-webpack and share the result.

**Comment by jkomyno** [comment]
Hey @ltnscp9028, could you please provide an update on this, as per the comment above? Thanks :)

**Comment by jkomyno** [comment]
Hi @ltnscp9028, as we were not able to get a response, we're closing this issue. Feel free to leave a comment asking to re-open it, should you have more info to share with us as per the comments above. Thanks!
