### ISSUE TITLE
Migrations commands crash when run on empty schema.prisma

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7186]
- `npm init -y`
- `npm install prisma@dev`
- Then:

```
C:\Users\Jan\Documents\throwaway\envRepro  (envRepro@1.0.0)
λ npx prisma db push
Prisma schema loaded from schema.prisma
Error: Get config thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', query-engine\query-engine\src\opt.rs:148:21
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

C:\Users\Jan\Documents\throwaway\envRepro  (envRepro@1.0.0)
λ npx prisma migrate dev
Prisma schema loaded from schema.prisma
Error: Get config thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', query-engine\query-engine\src\opt.rs:148:21
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

vs. handled error in Introspection:

```
C:\Users\Jan\Documents\throwaway\envRepro  (envRepro@1.0.0)
λ npx prisma introspect
Prisma schema loaded from schema.prisma

Introspecting based on datasource defined in schema.prisma …
Error: There is no datasource in the schema.
```

**Comment by tomhoule** [comment]
Pushing this to team/client because the crash is in the query engine (most likely getConfig).

**Comment by tomhoule** [comment]
We took this anyway since it's introspection-relevant and we know how to fix it.

**Comment by matthewmueller** [comment]
Thanks! I've moved this along.

**Comment by tomhoule** [comment]
We currently don't have bandwidth for that, assigning the client team in addition to us, since it's a crash in the QE, so the issue doesn't get lost.

**Comment by janpio** [comment]
Error message is now different in 3.6.0:

```
C:\Users\Jan\Documents\throwaway\7186  (7186@1.0.0)
λ npx prisma db push
Prisma schema loaded from schema.prisma
Error: Cannot read property 'url' of undefined

C:\Users\Jan\Documents\throwaway\7186  (7186@1.0.0)
λ npx prisma migrate dev
Prisma schema loaded from schema.prisma
Error: Cannot read property 'url' of undefined
```

**Comment by jkomyno** [comment]
# Current behavior

## prisma validate

![image](https://user-images.githubusercontent.com/12381818/170315507-07662bc0-4ede-4ae6-8aad-6ab7d7a568aa.png)

## prisma db push

![image](https://user-images.githubusercontent.com/12381818/170315570-c29e9744-193c-420e-bcd2-f83be28a41e2.png)

## prisma db pull

![image](https://user-images.githubusercontent.com/12381818/170315614-d82d91e4-5625-4fd7-b608-b37d4940e5c2.png)

## prisma format

![image](https://user-images.githubusercontent.com/12381818/170315706-9532e6ad-34cc-429c-825b-2cf2939039c8.png)

**Comment by janpio** [comment]
We should:
1. change "datamodel path" to "schema path" or something that users could understand,
2. add a snapshot test for all these commands in its current state, 
3. then decide if there is a better way to handle that (in the CLI for example where we can shot a unified and nicer error message instead of letting `getdmmf` and others handle this problem.

Side question: Why are `db push` and `db pull` different than the others?

**Comment by jkomyno** [comment]
- The `Couldn't find a datasource in the prisma.schema file` message appearing in `prisma db push` comes from the [`ensureDatabaseExists` function of `ensureDatabaseExists.ts`](https://github.com/prisma/prisma/blob/8e90f8a1ca12f9b596f92bae811d9d92266aab7a/packages/migrate/src/utils/ensureDatabaseExists.ts#L111-L173)
- The `There is no datasource in the schema.` message appearing in `prisma db pull` comes from the query engines, e.g.,  from [here](https://github.com/prisma/prisma-engines/blob/7f94cfc784ca8a6f19192a17b30727f90eb3878b/migration-engine/qe-setup/src/lib.rs#L39-L43).

**Comment by tomhoule** [comment]
> What is the connection between db pull and Query Engine?

probably `getConfig` or `getDmmf` for `generate`?

**Comment by jkomyno** [comment]
After adding snapshots for commands referencing empty schemas in [this PR](https://github.com/prisma/prisma/pull/14852), no other actionable task seems available for this issue.

Future steps might be:
- [ ] Agree on a single, shared error message to display in case of "missing required blocks from the schema" (which is a generalization of having an empty schema)
- [ ] This "missing required blocks" validation will most likely require access to the AST of the schema, so it should probably be performed by the Rust Prisma Engines and forwarded to the TS side

**Note**: We should consider that this issue doesn't seem to fall in the "broken promises" bucket, so we could postpone additional work on this until after our joint effort with the client team is completed.

**Comment by Jolg42** [comment]
So current state from the PR snapshots

PRISMA_CLI_QUERY_ENGINE_TYPE === 'library'
- validate
- format
- migrate dev
      Get DMMF: Error while trying to read datamodel path
      Details: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
      Prisma CLI Version : 0.0.0

- db push
- migrate reset
      Couldn't find a datasource in the schema.prisma file`,

- db pull
- db execute
      There is no datasource in the schema.

For PRISMA_CLI_QUERY_ENGINE_TYPE === 'binary' there are some differences to note:

The following are valid for the binary
- validate
     The schema at (.*) is valid 🚀
- format
     Formatted (.*) in \d+ms 🚀

And a different error:
- migrate dev
   Couldn't find a datasource in the schema.prisma file

**Comment by jkomyno** [comment]
The current situation (as per [main](https://github.com/prisma/prisma/blob/main/packages/cli/src/__tests__/empty-schema.test.ts)) is:

## PRISMA_CLI_QUERY_ENGINE_TYPE === 'library'
- validate
- migrate dev
```
      Get DMMF: Error while trying to read datamodel path
      Details: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
      Prisma CLI Version : 0.0.0
```
- db push
- migrate reset
```
      Couldn't find a datasource in the schema.prisma file`,
```
- db pull
- db execute
```
      There is no datasource in the schema.
```
- format
```
     Formatted (.*) in \d+ms 🚀
```

## For PRISMA_CLI_QUERY_ENGINE_TYPE === 'binary' there are some differences to note:

Different error:
- migrate dev
- migrate reset
```
   Couldn't find a datasource in the schema.prisma file
```

The following are valid for the binary but not for the library
- validate
```
     The schema at (.*) is valid 🚀
```

**Comment by jkomyno** [comment]
Next step:
- [ ] Figure out why `validate` and `migrate dev` fail with such an error when using the library. Can we change figure out that `undefined` parameter?
- [ ] We need to identify the differences between `getDmmf` in the Rust CLI and the Node API
- [ ] Refactor `empty-schema` tests to `incomplete-schema` tests:
  - You have a datasource URL, but the env variable is not set
  - You don't have a datasource block
  - You have a datasource block, but no URL

**Comment by jkomyno** [comment]
Note: this task requires the Wasm-ification of `getConfig` to be handled first (as `getConfig` can heavily influence the `incomplete-schema` tests linked to this issue).
