### ISSUE TITLE
StackBlitz Webcontainer: Prisma fails in multiple ways

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7187]
Prisma can be installed in the new StackBlitz Webcontainers with a small workaround of installing a Chrome extension that disables CORS: https://github.com/prisma/prisma/issues/7185#issuecomment-845477829

Then you can:
- Go to https://stackblitz.com/edit/node-psqsqe
- In the terminal run `npm install -D prisma@dev`
- Run `npx prisma init`
- Or run `npx prisma`

But other commands fail in different ways:

### `npx prisma studio`

In terminal: `Unimplemented `channel`, ignoring request: {}`
In browser console: 
```
vendor.js:59 Unable to communicate with backend:  SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at browser.js:1
    at browser.js:1
```
Internal discussion: https://prisma-company.slack.com/archives/CC8F34ALF/p1621545670013400

### `npx prisma format`

```
/projects/node-psqsqe
❯ npx prisma format
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Command failed with exit code 1: /projects/node-psqsqe/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x format -i /projects/node-psqsqe/prisma/schema.prisma
SyntaxError: Invalid or unexpected token
    at __global_eval__ (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:8:15954)
    at _0x18a892 (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:21075)
    at _0x372288.runInThisContext (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:20268)
    at _0x2e8059 (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19362)
    at wrapSafe (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:186554)
    at Module._compile (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187186)
    at Object.Module._extensions..js (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187908)
    at Module.load (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:185988)
    at Function.Module._load (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:183564)
    at Function.executeUserEntryPoint [as runMain] (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:794701)

error Command failed with exit code 1
```

### `npx prisma generate` / `npx prisma migrate dev` / `npx prisma db push`

```
/projects/node-psqsqe
❯ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Get config SyntaxError: Invalid or unexpected token
    at __global_eval__ (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:8:15954)
    at _0x18a892 (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:21075)
    at _0x372288.runInThisContext (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:20268)
    at _0x2e8059 (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19362)
    at wrapSafe (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:186554)
    at Module._compile (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187186)
    at Object.Module._extensions..js (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187908)
    at Module.load (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:185988)
    at Function.Module._load (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:183564)
    at Function.executeUserEntryPoint [as runMain] (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:794701)

error Command failed with exit code 1
```

### `npx prisma introspect`

```
/projects/node-psqsqe
❯ npx prisma introspect
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

Introspecting based on datasource defined in prisma/schema.prisma …
Error: Error in introspection engine: SyntaxError: Invalid or unexpected token
    at __global_eval__ (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:8:15954)
    at _0x18a892 (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:21075)
    at _0x372288.runInThisContext (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:20268)
    at _0x2e8059 (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19362)
    at wrapSafe (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:186554)
    at Module._compile (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187186)
    at Object.Module._extensions..js (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187908)
    at Module.load (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:185988)
    at Function.Module._load (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:183564)
    at Function.executeUserEntryPoint [as runMain] (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:794701)

error Command failed with exit code 1
```

### `npx prisma -v`

```
/projects/node-psqsqe 8s
❯ npx prisma -v
Environment variables loaded from .env
Error: Command failed with exit code 1: /projects/node-psqsqe/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version
SyntaxError: Invalid or unexpected token
    at __global_eval__ (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:8:15954)
    at _0x18a892 (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:21075)
    at _0x372288.runInThisContext (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:20268)
    at _0x2e8059 (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:11:19362)
    at wrapSafe (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:186554)
    at Module._compile (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187186)
    at Object.Module._extensions..js (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:187908)
    at Module.load (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:185988)
    at Function.Module._load (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:183564)
    at Function.executeUserEntryPoint [as runMain] (https://node-psqsqe.jw.staticblitz.com/blitz.7286dbe8d47d3473cde7be488b7d048fb59b05f2.js:6:794701
```

**Comment by janpio** [comment]
Probably a problem on the StackBlitz side, reported at https://github.com/stackblitz/webcontainer-core/issues/16

**Comment by janpio** [comment]
Confirmed: New StackBlitz can not run _any_ binaries, only WASM stuff :(

**Comment by janpio** [comment]
With https://github.com/prisma/prisma/issues/8626#issuecomment-1426853638 we are now fully Wasm in the Prisma CLI, so some of the commands actually work (as long as you have a CORS-enabling extension installed, I used this one this time: https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino). You can `prisma init` and then successfully `prisma generate` a Prisma Client. You can still not use any command that uses the Migration Engine, and Prisam Client itself can also not be used.

Will continue watching the topic via https://github.com/prisma/prisma/issues/8626. Slow and strady.
