### ISSUE TITLE
PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18expected array type

### ISSUE THREAD

**Issue by sbahaddi** [prisma/prisma#7207]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.22.1             |
| Query Engine    | query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c|
| Database        | undefined|

## Query
```
mutation {
  queryRaw(
    query: "X"
    parameters: "X"
  )
}
```

## Logs
```
prisma:tryLoadEnv Environment variables loaded from /app/.env
prisma:tryLoadEnv Environment variables loaded from /app/.env
prisma:client clientVersion: 2.22.1
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:client prisma.queryRaw(SELECT grg.id FROM public.garage as grg where grg.id in ($1), [[1,2,3]])
prisma:client Prisma Client call:
prisma:engine { cwd: '/app/prisma' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '39187' ] }
prisma:engine stdout  Starting a postgresql pool with 3 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:39187
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine Client Version: 2.22.1
prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c
prisma:engine Active provider: postgresql
prisma:engine stdout  PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18
expected array type
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:25530:24)
      at Socket.emit (events.js:327:22)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:39187
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 39187
  }
}
prisma:engine { cwd: '/app/prisma' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '32945' ] }
prisma:engine stdout  Starting a postgresql pool with 3 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:32945
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine
prisma:engine Client Version: 2.22.1
prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c
prisma:engine Active provider: postgresql
prisma:engine stdout  PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18
expected array type
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:25530:24)
      at Socket.emit (events.js:327:22)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    code: 'UND_ERR_SOCKET'
  }
}
```

## Client Snippet
```js
const findGarages = async () => {
  const ids = [1, 2, 3];
  const garages = await prisma.$queryRaw(
    `SELECT grg.id FROM public.garage as grg where grg.id in ($1)`,
    ids,
  );
  return garages;
};
```

## Schema
```prisma
model Garage {
  id      Int     @id @default(autoincrement())
  name    String  @unique @db.VarChar(250)
  address String  @db.VarChar(250)
  lat     Decimal
  lng     Decimal
  phone   String? @db.VarChar(20)

  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @updatedAt @map("updated_at")

  User       User     @relation(fields: [userId], references: [id])
  userId     Int      @map("user_id")
  district   District @relation(fields: [districtId], references: [id])
  districtId Int      @map("district_id")

  businessHours BusinessHour[]
  reviews       Review[]
  images        GarageImage[]
  experiences   Experience[]
  prestations   GaragePrestation[]

  @@map(name: "garage")
}
```

**Comment by sbahaddi** [comment]
it works fine if i don't use parameterized queries or tagged templates.
if i use it like this it works fine

const findGarages = async () => {
  const ids = [1, 2, 3];
  const garages = await prisma.$queryRaw(
    `SELECT grg.id FROM public.garage as grg where grg.id in (${ids})`,
  );
  return garages;
};

**Comment by pantharshit00** [comment]
You will need to use the `join()` helper here:
```js
import { PrismaClient, Prisma } from "@prisma/client";
const ids = [1, 2, 3];
const garages =
await prisma.$queryRaw`SELECT grg.id FROM public.garage as grg where grg.id in (${Prisma.join(
  ids
)})`;
```

It will generate the following sql:
```sql
prisma:query SELECT grg.id FROM public.garage as grg where grg.id in ($1,$2,$3)
```

(Notice all ids are now a prepared variable) 


A word of caution is that the version you shared above is prone to injection like so as it doesn't use the tagged template literals or prepared variables: 
```js
  const ids = [1, "2);SELECT 1;SELECT (1", 3];
  const garages = await prisma.$queryRaw(
    `SELECT grg.id FROM public.garage as grg where grg.id in (${ids})`
  );

```

It won't execute because you can't execute multiple statements in one prepared statement, but you get the idea. Basically `ids` is not escaped here.
