### ISSUE TITLE
`db push` does only semi handle Engine error in CLI

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7213]
When you try to `db push` to the `main` branch of a Planetscale database, an error is thrown. The CLI outputs that, but it also outputs more, indication it is not fully handling that case:

```
C:\Users\Jan\Documents\throwaway\planetscale>npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "fk-test" at "127.0.0.1:3306"
Error: Database error
Error querying the database: Server error: `ERROR HY000 (1105): direct DDL is disabled'
   0: sql_migration_connector::sql_database_step_applier::apply_migration
             at migration-engine\connectors\sql-migration-connector\src\sql_database_step_applier.rs:15
   1: migration_core::api::SchemaPush
             at migration-engine\core\src\api.rs:163

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: EPERM: operation not permitted, unlink 'C:\Users\Jan\AppData\Roaming\npm-cache\_npx\28260\node_modules\prisma\node_modules\@prisma\engines\migration-engine-windows.exe'
    at Object.unlinkSync (fs.js:1210:3)
    at fixWinEPERMSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:219:13)
    at rimrafSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:350:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:342:7)
    at fixWinEPERMSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:217:5)
    at rimrafSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:350:5
```

Everything from `This error originated ...` should not be output. The CLI also does not exit, and needs to be killed via Ctrl+C.

**Comment by janpio** [comment]
The same is true for `migrate dev` when the shadow database can not be created:

```
C:\Users\Jan\Documents\throwaway\planetscale>npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "fk-test" at "127.0.0.1:3306"

Error: P3014

Prisma Migrate could not create the shadow database. Please make sure the database user has permission to create databases. More info: https://pris.ly/d/migrate-shadow. Original error: 
Database error
Error querying the database: Server error: `ERROR 42000 (1235): create database is not supported'
   0: sql_migration_connector::flavour::mysql::sql_schema_from_migration_history
             at migration-engine\connectors\sql-migration-connector\src\flavour\mysql.rs:320
   1: sql_migration_connector::sql_database_migration_inferrer::calculate_drift
             at migration-engine\connectors\sql-migration-connector\src\sql_database_migration_inferrer.rs:57
   2: migration_core::api::DevDiagnostic
             at migration-engine\core\src\api.rs:95

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: EPERM: operation not permitted, unlink 'C:\Users\Jan\AppData\Roaming\npm-cache\_npx\23392\node_modules\prisma\node_modules\@prisma\engines\migration-engine-windows.exe'
    at Object.unlinkSync (fs.js:1210:3)
    at fixWinEPERMSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:219:13)
    at rimrafSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:350:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:349:26)
    at rmdirSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:342:7)
    at fixWinEPERMSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:217:5)
    at rimrafSync (C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:319:28)
    at C:\ProgramData\nvm\v14.16.1\node_modules\npm\node_modules\rimraf\rimraf.js:350:5

```

**Comment by janpio** [comment]
This was a side effect of `prisma` being downloaded instantly by `npx` instead of using a local version.
