### ISSUE TITLE
Database enum types with separator (dash/hypen) in its value causes the `prisma init` to fail

### ISSUE THREAD

**Issue by mohib0306** [prisma/prisma#728]
In can an enum's value has separator - in this case dash - the `prisma init` fails. The log of the command is attached below. The same issue is produced when `prisma generate` is executed.

```
Syntax Error: Invalid number, expected digit but got: "s".

GraphQL request:708:11
707 | enum AssignmentScopeEnum {
708 |   chapter-specific
    |           ^
709 |   course-wide
    at syntaxError (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/error/syntaxError.js:15:10)
    at readDigits (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/lexer.js:426:38)
    at readNumber (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/lexer.js:373:16)
    at readToken (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/lexer.js:259:14)
    at Object.lookahead (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/lexer.js:54:43)
    at Object.advanceLexer [as advance] (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/lexer.js:44:33)
    at Parser.expectToken (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/parser.js:1399:19)
    at Parser.parseName (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/parser.js:94:22)
    at Parser.parseEnumValueDefinition (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/parser.js:1014:21)
    at Parser.optionalMany (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/parser.js:1497:28)
    at Parser.parseEnumValuesDefinition (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/parser.js:1002:17)
    at Parser.parseEnumTypeDefinition (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/parser.js:986:23)
    at Parser.parseTypeSystemDefinition (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/parser.js:705:23)
    at Parser.parseDefinition (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/parser.js:146:23)
    at Parser.many (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/parser.js:111:25)
    at Object.parse (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/graphql/language/parser.js:36:17)
    at RelationalParser.DefaultParser.parseFromSchemaString (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/prisma-datamodel/src/datamodel/parser/parser.ts:31:20)
    at parseInternalTypes (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/prisma-generate-schema/src/index.ts:21:45)
    at generateCRUDSchema (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/prisma-generate-schema/src/index.ts:34:11)
    at Object.generateCRUDSchemaString [as default] (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/prisma-generate-schema/src/index.ts:64:22)
    at GenerateCommand.<anonymous> (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/prisma-cli-core/src/commands/generate/generate.ts:89:48)
    at step (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/generate/generate.js:45:23)
    at Object.next (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/generate/generate.js:26:53)
    at fulfilled (/Users/mohib/.nvm/versions/node/v10.15.3/lib/node_modules/prisma/node_modules/prisma-cli-core/dist/commands/generate/generate.js:17:58)
2019-10-11T23:35:08.316Z output Exiting with code: 1


Generating schema... !
```

**Comment by pantharshit00** [comment]
I think this is expected behaviour as we only don't allow hyphens or dashes there. Here is the pest declaration for an identifier that we allow: https://github.com/prisma/prisma-engine/blob/188a379c9b8c6650e5812f9bdb7407d7b197692f/libs/datamodel/src/ast/parser/datamodel.pest#L37

You can use `_` though(ie snake case)

Also, we would also allow you to map an enum to a different value very soon. Here is the spec for it: https://github.com/prisma/specs/tree/master/schema#enum-block

**Comment by mohib0306** [comment]
May I ask why the values are not just treated as strings literals without having any restrictions from PhotonJS? I mean if the databases are allowing these kind values - to have some special character - I think it could have been supported by PhotonJS as well.

**Comment by pantharshit00** [comment]
We don't allow hyphens in the schema because, after code generation, Javascript or Typescript won't execute this code as it would treat `-` as the minus operator.

Example:
```js
photon.some_thing.find() // this is valid
photon.some-thing.find() // invalid
```

Same goes for field and enums. Even though Enums are just a set of values, still we can't generate TS types if we allow '-'.

**Comment by divyenduz** [comment]
@mohib0306 Did you introspect an existing SQL schema? If yes, would you be up to share it with us? We are collecting SQL schemas https://github.com/prisma/prisma2/issues/757

Please send it to `schemas@prisma.io`.

**Comment by janpio** [comment]
This code was fully replaced. If this still happens, please open a new issue and we are happy to take a look. Thanks.

**Comment by ppoddar-affordably** [comment]
This restriction is preventing me from using crdb_region in CockroachDB. They define an internal crdb_internal_region enum that is required to be the type of any crdb_region column [0]. The enum values are cloud regions with dashes (gcp-us-east1, etc.). On their hosted offering, I can't change these values. Thus, I can't specify a corresponding enum that matches my database in my Prisma schema, so I'm rather stuck...

[0] https://www.cockroachlabs.com/blog/under-the-hood-multi-region/
