### ISSUE TITLE
PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18expected array type

### ISSUE THREAD

**Issue by ameerulislam** [prisma/prisma#7298]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.22.1           | 
| OS              | rhel-openssl-1.0.x |
| Prisma Client   | 2.22.1             |
| Query Engine    | query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c|
| Database        | undefined|

## Query
```
mutation {
  queryRaw(
    query: "X"
    parameters: "X"
  )
}
```

## Logs
```
process/task_queues.js:84:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine { cwd: '/var/task/prisma' }
prisma:engine Search for Query Engine in /var/task/node_modules/.prisma/client
plusX Execution permissions of /var/task/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '45875' ] }
prisma:engine stdout  Starting a postgresql pool with 5 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:45875
prisma:engine Search for Query Engine in /var/task/node_modules/.prisma/client
plusX Execution permissions of /var/task/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine Client Version: 2.22.1
prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c
prisma:engine Active provider: postgresql
prisma:engine stdout  PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18
expected array type
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/var/task/node_modules/@prisma/client/runtime/index.js:25530:24)
      at Socket.emit (events.js:326:22)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    code: 'UND_ERR_SOCKET'
  }
}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by pantharshit00** [comment]
Hey @ameerulislam 

Can you please provide a reproduction here? This might be a duplicate of https://github.com/prisma/prisma/issues/7207#issuecomment-849831952

**Comment by ameerulislam** [comment]
sorry, what is a reproduction?

**Comment by pantharshit00** [comment]
A reproduction is sequence of steps which can replicate the crash. For example, provide the schema and the query which is causing this so that I can replicate the crash and debug the problem.

**Comment by pantharshit00** [comment]
Please also check https://github.com/prisma/prisma/issues/7207#issuecomment-849831952 once and see if the query you are running is similar to that. If that is the case, we will close and continue the discussion over there.

**Comment by ameerulislam** [comment]
what I figured this one because my postgres db rejecting my json object (that was not valid json object) when my jsonobject field validator from postgres was rejecting it. For that this was crashing.

**Comment by pantharshit00** [comment]
Can you please paste the Prisma query that you are running here?

**Comment by ameerulislam** [comment]
module.exports.insertAmeer = async (event , contex , callback) => {

  try {
    
    const result = await prisma.$queryRaw`INSERT INTO ct_datatempstation(jsondata) VALUES(${event} );`

    return {
      statusCode: 200,
      headers:  { 'Content-Type': 'application/json' },
      body: JSON.stringify(event)
    }

  } catch(error){
    console.error(error)
    return{

      statusCode: 500,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(error)


    }

  }
};

**Comment by jacktan165** [comment]
I'm having the same issue too.

```
    const data: Prisma.RecipeCreateInput = {
      ...recipes,
      ingredients: {
        connectOrCreate: recipes.ingredients.map((ingredient) => ({
          create: {
            quantity: ingredient.quantity,
            ingredient: {
              connect: {
                name: ingredient.name,
              },
            },
          },
          where: {
            recipeLink_ingredientName: {
              recipeLink: recipes.link,
              ingredientName: recipes.name,
            },
          },
        })),
      },
    };

    const recipePayload = await this.prisma.recipe.create({
      data,
      include: {
        ingredients: {
          include: {
            ingredient: true,
          },
        },
      },
    });
```

Where recipes is just a bunch of objects. It used to work, but not recently. I'm going to downgrade Prisma or something to see if the version is the issue.

**Comment by pantharshit00** [comment]
@jacktan165 Please open a new issue, this seems unrelated. 

@ameerulislam Sorry I forgot to reply here. 

Please share a complete reproduction. I don't know value of `event` variable and structure of ` ct_datatempstation` table so I can't attempt to replicate this.

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
