### ISSUE TITLE
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by vjpr** [prisma/prisma#7335]
Occurs when there is an error in `queryRaw` and we are running multiple queries concurrently.

```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]:
Invalid `prisma.queryRaw()` invocation:


  Raw query failed. Code: `42P01`. Message: `relation "customer" does not exist`
    at cb (/xxx/.pnpm/@prisma+client@2.23.0/node_modules/@prisma/client/runtime/index.js:35101:17)
    at Object.queryRaw (/xxx/xxx/packages/orm/prisma/src/index.ts:27:15)
    at fun (/xxx/xxx/packages/cli/src/benchmark.ts:38:19)
    at /xxx/.pnpm/p-map@4.0.0/node_modules/p-map/index.js:57:22 {
  code: 'P2010',
  clientVersion: '2.23.0',
  meta: { code: '42P01', message: 'relation "customer" does not exist' }
}

Query: select * from customer
Duration: 0 ms
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `0`', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/napi-1.3.4/src/threadsafe_function.rs:409:5
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: napi::threadsafe_function::call_js_cb
   3: __ZN6v8impl12_GLOBAL__N_118ThreadSafeFunction6IdleCbEP9uv_idle_s
   4: _uv__run_idle
   5: _uv_run
   6: __ZN4node11Environment14CleanupHandlesEv
   7: __ZN4node11Environment10RunCleanupEv
   8: __ZN4node15FreeEnvironmentEPNS_11EnvironmentE
   9: __ZN4node16NodeMainInstance3RunEv
  10: __ZN4node5StartEiPPc
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
[1]    55256 abort      RUST_BACKTRACE=1 npm run dev
```

# Repro

Something like:

```js
import pTimes 'from p-times'

// Doesn't happen if I only try to run it once.
await pTimes(2, fun, {concurrency: 100})

async function fun() {
  await prisma.$queryRaw('select * from customer')
}
```

If that doesn't reproduce it for someone then I am happy to do a full git repro.

# Settings

Using psql and napi.

**Comment by pantharshit00** [comment]
Hey @vjpr 

Can you please tell me which version of Prisma are you using? This was probably already fixed via https://github.com/napi-rs/napi-rs/issues/518

**Comment by vjpr** [comment]
2.23.0

**Comment by pantharshit00** [comment]
Hey @vjpr 

We fixed the `dev` version bug which was blocking `napi` generation. Can you please try this again on the dev version?

**Comment by janpio** [comment]
This should now be release in 2.24.0. Can you please test that version @vjpr and confirm this is fixed for you? Thanks, that would be very helpful.

**Comment by janpio** [comment]
@vjpr Do you maybe have time to look at this again? Would be nice if we could close this.

**Comment by vjpr** [comment]
Fixed.
