### ISSUE TITLE
`--create-only` wants to delete my database content when drift detected

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7338]
### Bug description

`migrate dev --create-only` wants to delete data from my database when it detects drift. I only want it to create a migration file.

```
C:\Users\Jan\Documents\throwaway\planetscale>npx prisma migrate dev --create-only
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "fk-test" at "127.0.0.1:3306"

√ Drift detected: Your database schema is not in sync with your migration history.

We need to reset the MySQL database "fk-test" at "127.0.0.1:3306".
Do you want to continue? All data will be lost. ... yes

Error: P3016

The fallback method for database resets failed, meaning Migrate could not clean up the database entirely. Original error: 
Database error
Error querying the database: Server error: `ERROR HY000 (1105): direct DDL is disabled'
   0: sql_migration_connector::best_effort_reset
           with connection=Connection(Mysql(MysqlUrl { url: Url { scheme: "mysql", username: "root", password: None, host: Some(Domain("127.0.0.1")), port: Some(3306), path: "/fk-test", query: None, fragment: None }, query_params: MysqlUrlQueryParams { ssl_opts: SslOpts { pkcs12_path: None, password: None, root_cert_path: None, skip_domain_validation: false, accept_invalid_certs: true }, connection_limit: None, use_ssl: false, socket: None, socket_timeout: None, connect_timeout: Some(5s), pool_timeout: Some(10s), max_connection_lifetime: None, max_idle_connection_lifetime: Some(300s) } }))
             at migration-engine\connectors\sql-migration-connector\src\lib.rs:99
   1: migration_core::api::Reset
             at migration-engine\core\src\api.rs:157
```

Fortunately my database does not allow that. I have no idea which DDL commands this would execute.

Update:

```
C:\Users\Jan\Documents\throwaway\planetscale>set DEBUG=*

C:\Users\Jan\Documents\throwaway\planetscale>npx prisma migrate dev --create-only
  prisma:loadEnv project root found at C:\Users\Jan\Documents\throwaway\planetscale\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\planetscale\.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # Environment variables declared in this file are automatically made available to Prisma.
[dotenv][DEBUG] did not match key and value when parsing line 2: # See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables
[dotenv][DEBUG] did not match key and value when parsing line 3:
[dotenv][DEBUG] did not match key and value when parsing line 4: # Prisma supports the native connection string format for PostgreSQL, MySQL and SQLite.
[dotenv][DEBUG] did not match key and value when parsing line 5: # See the documentation for all the connection string options: https://pris.ly/d/connection-strings
[dotenv][DEBUG] did not match key and value when parsing line 6:
Environment variables loaded from .env
  prisma:engines using NAPI: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +1ms
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\planetscale\node_modules\@prisma\engines\query-engine-windows.exe +0ms
Datasource "db": MySQL database "fk-test" at "127.0.0.1:3306"

  prisma:getConfig Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\planetscale\node_modules\@prisma\engines\query-engine-windows.exe +141ms
  prisma:getConfig Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\planetscale\node_modules\@prisma\engines\query-engine-windows.exe +70ms
  prisma:migrateEngine:rpc starting migration engine with binary: C:\Users\Jan\Documents\throwaway\planetscale\node_modules\@prisma\engines\migration-engine-windows.exe +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"C:\\Users\\Jan\\Documents\\throwaway\\planetscale\\prisma\\migrations"}} +5ms
  prisma:migrateEngine:stderr May 29 04:26:47.175  INFO migration_engine: Starting migration engine RPC server git_hash="5ab68a73e954e003cc528d6e1e42d924ce99c676" +0ms
  prisma:migrateEngine:stderr May 29 04:26:48.067  INFO quaint::single: Starting a mysql connection. +891ms
  prisma:migrateEngine:stderr May 29 04:26:49.882  INFO DevDiagnostic:calculate_drift:sql_schema_from_migration_history: quaint::single: Starting a mysql connection. +2s
  prisma:migrateEngine:stderr May 29 04:26:49.883  INFO DevDiagnostic:calculate_drift:sql_schema_from_migration_history: sql_migration_connector::flavour::mysql: Connecting to user-provided shadow database at localhost.Some("fk-test") +1ms
  prisma:migrateEngine:stderr May 29 04:26:49.996  INFO DevDiagnostic:calculate_drift:sql_schema_from_migration_history:best_effort_reset{connection=Connection(Mysql(MysqlUrl { url: Url { scheme: "mysql", username: "root", password: None, host: Some(Domain("localhost")), port: Some(3333), path: "/fk-test", query: None, fragment: None }, query_params: MysqlUrlQueryParams { ssl_opts: SslOpts { pkcs12_path: None, password: None, root_cert_path: None, skip_domain_validation: false, accept_invalid_certs: true }, connection_limit: None, use_ssl: false, socket: None, socket_timeout: None, connect_timeout: Some(5s), pool_timeout: Some(10s), max_connection_lifetime: None, max_idle_connection_lifetime: Some(300s) } }))}: sql_migration_connector: Attempting best_effort_reset +112ms
  prisma:migrateEngine:stderr May 29 04:26:55.123  INFO DevDiagnostic:validate_migrations:sql_schema_from_migration_history: quaint::single: Starting a mysql connection. +5s
  prisma:migrateEngine:stderr May 29 04:26:55.123  INFO DevDiagnostic:validate_migrations:sql_schema_from_migration_history: sql_migration_connector::flavour::mysql: Connecting to user-provided shadow database at localhost.Some("fk-test") +1ms
  prisma:migrateEngine:stderr May 29 04:26:55.237  INFO DevDiagnostic:validate_migrations:sql_schema_from_migration_history:best_effort_reset{connection=Connection(Mysql(MysqlUrl { url: Url { scheme: "mysql", username: "root", password: None, host: Some(Domain("localhost")), port: Some(3333), path: "/fk-test", query: None, fragment: None }, query_params: MysqlUrlQueryParams { ssl_opts: SslOpts { pkcs12_path: None, password: None, root_cert_path: None, skip_domain_validation: false, accept_invalid_certs: true }, connection_limit: None, use_ssl: false, socket: None, socket_timeout: None, connect_timeout: Some(5s), pool_timeout: Some(10s), max_connection_lifetime: None, max_idle_connection_lifetime: Some(300s) } }))}: sql_migration_connector: Attempting best_effort_reset +113ms
  prisma:migrateEngine:stderr May 29 04:26:57.866  INFO DevDiagnostic: migration_core::commands::dev_diagnostic: DriftDetected diagnostic rollback="/*\n  Warnings:\n\n  - You are about to drop the `bar` table. If the table is not empty, all the data it contains will be lost.\n  - You are about to drop the `foo` table. If the table is not empty, all the data it contains will be lost.\n\n*/\n-- DropTable\nDROP TABLE `bar`;\n\n-- DropTable\nDROP TABLE `foo`;\n" +3s
  prisma:migrate:dev {
  prisma:migrate:dev   devDiagnostic: '{\n' +
  prisma:migrate:dev     '  "action": {\n' +
  prisma:migrate:dev     '    "tag": "reset",\n' +
  prisma:migrate:dev     '    "reason": "Drift detected: Your database schema is not in sync with your migration history."\n' +
  prisma:migrate:dev     '  }\n' +
  prisma:migrate:dev     '}'
  prisma:migrate:dev } +0ms
  prisma:getConfig Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\planetscale\node_modules\@prisma\engines\query-engine-windows.exe +12s
√ Drift detected: Your database schema is not in sync with your migration history.

We need to reset the MySQL database "fk-test" at "127.0.0.1:3306".
Do you want to continue? All data will be lost. ... yes

  prisma:migrateEngine:rpc SENDING RPC CALL {"id":2,"jsonrpc":"2.0","method":"reset","params":{}} +17s
  prisma:migrateEngine:stderr May 29 04:27:03.819  INFO Reset:best_effort_reset{connection=Connection(Mysql(MysqlUrl { url: Url { scheme: "mysql", username: "root", password: None, host: Some(Domain("127.0.0.1")), port: Some(3306), path: "/fk-test", query: None, fragment: None }, query_params: MysqlUrlQueryParams { ssl_opts: SslOpts { pkcs12_path: None, password: None, root_cert_path: None, skip_domain_validation: false, accept_invalid_certs: true }, connection_limit: None, use_ssl: false, socket: None, socket_timeout: None, connect_timeout: Some(5s), pool_timeout: Some(10s), max_connection_lifetime: None, max_idle_connection_lifetime: Some(300s) } }))}: sql_migration_connector: Attempting best_effort_reset +6s
  prisma:migrateEngine:rpc {
  prisma:migrateEngine:rpc   jsonrpc: '2.0',
  prisma:migrateEngine:rpc   error: {
  prisma:migrateEngine:rpc     code: 4466,
  prisma:migrateEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:migrateEngine:rpc     data: {
  prisma:migrateEngine:rpc       is_panic: false,
  prisma:migrateEngine:rpc       message: 'The fallback method for database resets failed, meaning Migrate could not clean up the database entirely. Original error: \n' +
  prisma:migrateEngine:rpc         'Database error\n' +
  prisma:migrateEngine:rpc         "Error querying the database: Server error: `ERROR HY000 (1105): direct DDL is disabled'\n" +
  prisma:migrateEngine:rpc         '   0: sql_migration_connector::best_effort_reset\n' +
  prisma:migrateEngine:rpc         '           with connection=Connection(Mysql(MysqlUrl { url: Url { scheme: "mysql", username: "root", password: None, host: Some(Domain("127.0.0.1")), port: Some(3306), path: "/fk-test", query: None, fragment: None }, query_params: MysqlUrlQueryParams { ssl_opts: SslOpts { pkcs12_path: None, password: None, root_cert_path: None, skip_domain_validation: false, accept_invalid_certs: true }, connection_limit: None, use_ssl: false, socket: None, socket_timeout: None, connect_timeout: Some(5s), pool_timeout: Some(10s), max_connection_lifetime: None, max_idle_connection_lifetime: Some(300s) } }))\n' +
  prisma:migrateEngine:rpc         '             at migration-engine\\connectors\\sql-migration-connector\\src\\lib.rs:99\n' +
  prisma:migrateEngine:rpc         '   1: migration_core::api::Reset\n' +
  prisma:migrateEngine:rpc         '             at migration-engine\\core\\src\\api.rs:157',
  prisma:migrateEngine:rpc       meta: [Object],
  prisma:migrateEngine:rpc       error_code: 'P3016'
  prisma:migrateEngine:rpc     }
  prisma:migrateEngine:rpc   },
  prisma:migrateEngine:rpc   id: 2
  prisma:migrateEngine:rpc } +1s
Error: Error: P3016

The fallback method for database resets failed, meaning Migrate could not clean up the database entirely. Original error: 
Database error
Error querying the database: Server error: `ERROR HY000 (1105): direct DDL is disabled'
   0: sql_migration_connector::best_effort_reset
           with connection=Connection(Mysql(MysqlUrl { url: Url { scheme: "mysql", username: "root", password: None, host: Some(Domain("127.0.0.1")), port: Some(3306), path: "/fk-test", query: None, fragment: None }, query_params: MysqlUrlQueryParams { ssl_opts: SslOpts { pkcs12_path: None, password: None, root_cert_path: None, skip_domain_validation: false, accept_invalid_certs: true }, connection_limit: None, use_ssl: false, socket: None, socket_timeout: None, connect_timeout: Some(5s), pool_timeout: Some(10s), max_connection_lifetime: None, max_idle_connection_lifetime: Some(300s) } }))
             at migration-engine\connectors\sql-migration-connector\src\lib.rs:99
   1: migration_core::api::Reset
             at migration-engine\core\src\api.rs:157

    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\planetscale\node_modules\prisma\build\index.js:57315:26)
    at MigrateEngine.handleResponse (C:\Users\Jan\Documents\throwaway\planetscale\node_modules\prisma\build\index.js:57190:38)
    at LineStream.<anonymous> (C:\Users\Jan\Documents\throwaway\planetscale\node_modules\prisma\build\index.js:57275:18)
    at LineStream.emit (events.js:315:20)
    at LineStream.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at LineStream.Readable.push (internal/streams/readable.js:223:10)
    at LineStream.Transform.push (internal/streams/transform.js:166:32)
    at LineStream._pushBuffer (C:\Users\Jan\Documents\throwaway\planetscale\node_modules\prisma\build\index.js:57065:19)
```

### How to reproduce

1. Create project with schema
2. Migrate Schema with `db push` (so no migration history is created)
4. Run `prisma migrate dev --create-only`
5. Observe the above

### Expected behavior

Tell me it would reset when I actually run this, but do not reset but just create the migration file for me.

### Environment & setup

- OS: Windows
- Database: MySQL

### Prisma Version

```
C:\Users\Jan\Documents\throwaway\planetscale>npx prisma -v
Environment variables loaded from .env
prisma               : 2.24.0-dev.27
@prisma/client       : 2.24.0-dev.27
Current platform     : windows
Query Engine         : query-engine 5ab68a73e954e003cc528d6e1e42d924ce99c676 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli 5ab68a73e954e003cc528d6e1e42d924ce99c676 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core 5ab68a73e954e003cc528d6e1e42d924ce99c676 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt 5ab68a73e954e003cc528d6e1e42d924ce99c676 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : 5ab68a73e954e003cc528d6e1e42d924ce99c676
Studio               : 0.397.0
Preview Features     : planetScaleMode
```

**Comment by janpio** [comment]
Reading the `DEBUG=*` log, it seems to connect to the shadow database at localhost:3333 but then want to (at least according to the prompt) reset the database at `127.0.0.1:3306`. I am not fully sure what is going on and what I can trust here.

**Comment by FGoessler** [comment]
Hi,

We’ve noticed there hasn’t been activity on this issue for quite some time, and we suspect it might no longer be relevant. As part of our ongoing effort to streamline open issues in this repository, we’re closing this one to focus on what’s most important to our community.

If you believe this issue is still relevant and requires attention, feel free to reopen it. Reopening the issue is a valuable signal to us about what matters most to you.

You can learn more about our approach and motivations in the [Prisma ORM Manifesto](https://www.prisma.io/blog/prisma-orm-manifesto#1-defining-first-class-databases).

With love,
Your Prisma ORM Team ❤️
