### ISSUE TITLE
Help With Cloud Function Deploy

### ISSUE THREAD

**Issue by xdougx** [prisma/prisma#7340]
Hello, im trying to deploy a cloud function but  im getting this error:

```
2021-05-28 22:58:37.789 BRTstaging_test_db_con Provided module can't be loaded.
2021-05-28 22:58:37.789 BRTstaging_test_db_con Is there a syntax error in your code?
2021-05-28 22:58:37.789 BRTstaging_test_db_con Detailed stack trace: Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
2021-05-28 22:58:37.789 BRTstaging_test_db_con In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
2021-05-28 22:58:37.789 BRTstaging_test_db_con at new PrismaClient (/workspace/node_modules/.prisma/client/index.js:3:11)
2021-05-28 22:58:37.789 BRTstaging_test_db_con at Object.<anonymous> (/workspace/lib/infrastructure/prisma.js:5:18)
2021-05-28 22:58:37.789 BRTstaging_test_db_con at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-05-28 22:58:37.789 BRTstaging_test_db_con at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-05-28 22:58:37.789 BRTstaging_test_db_con at Module.load (internal/modules/cjs/loader.js:863:32)
2021-05-28 22:58:37.789 BRTstaging_test_db_con at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-05-28 22:58:37.789 BRTstaging_test_db_con at Module.require (internal/modules/cjs/loader.js:887:19)
2021-05-28 22:58:37.789 BRTstaging_test_db_con at require (internal/modules/cjs/helpers.js:74:18)
2021-05-28 22:58:37.789 BRTstaging_test_db_con at Object.<anonymous> (/workspace/lib/infrastructure/my-sql-database.js:13:18)
2021-05-28 22:58:37.789 BRTstaging_test_db_con at Module._compile (internal/modules/cjs/loader.js:999:30)
```

package.json
```
{
  "name": "functions",
  "scripts": {
    "lint": "eslint \"src/**/*\"",
    "build": "tsc",
    "watch": "tsc --watch",
    "serve": "npm run build && firebase init emulators && firebase emulators:start",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy_test": "npm run env && firebase deploy --only functions:staging_test_db_con",
    "logs": "firebase functions:log",
    "set-env": "firebase functions:config:set env=\"$(cat env.json)\"",
    "unset-env": "firebase functions:config:unset env",
    "env": "npm run unset-env && npm run set-env"
  },
  "engines": {
    "node": "12"
  },
  "main": "lib/index.js",
  "dependencies": {
    "@google-cloud/storage": "^5.6.0",
    "@prisma/client": "^2.23.0",
    "@types/busboy": "^0.2.3",
    "@types/crypto-js": "^4.0.1",
    "@types/formidable": "^1.0.31",
    "@types/luxon": "^1.25.0",
    "@types/multiparty": "0.0.32",
    "@types/sharp": "^0.26.1",
    "async-redis": "^1.1.7",
    "axios": "^0.21.1",
    "body-parser": "^1.19.0",
    "busboy": "^0.3.1",
    "clevertap": "^1.1.1",
    "cors": "^2.8.5",
    "crypto-js": "^4.0.0",
    "express": "^4.17.1",
    "firebase-admin": "^9.9.0",
    "firebase-functions": "^3.14.1",
    "luxon": "^1.26.0",
    "mysql": "^2.18.1",
    "redis": "^3.1.2",
    "reflect-metadata": "^0.1.13",
    "rollbar": "^2.21.1",
    "sharp": "^0.26.3",
    "tsyringe": "^4.4.0",
    "uuidv4": "^6.2.5"
  },
  "devDependencies": {
    "@types/async-redis": "^1.1.1",
    "@types/express": "^4.17.9",
    "@types/node": "^14.14.7",
    "@types/redis": "^2.8.28",
    "@typescript-eslint/eslint-plugin": "^4.7.0",
    "@typescript-eslint/parser": "^4.7.0",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "^2.22.0",
    "firebase-functions-test": "^0.2.0",
    "prisma": "^2.23.0",
    "typescript": "^4.1.5"
  },
  "private": true
}

```

my prisma schema is in
```
/functions/prisma/schema.prisma
```

Localy everything works, but when I deploy it goes wrong.
Need some help if anyone could

**Comment by 26medias** [comment]
@xdougx you ever found a solution? I'm facing the same issue

**Comment by frapsMatheus** [comment]
I'm having the same issue? What did you do to fix it?

**Comment by xdougx** [comment]
No, I've never found a solution, I had to change to KnexJs instead of Prisma. Sorry guys
