### ISSUE TITLE
`db seed` returns a lot of unrelated information on broken seed script

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7405]
I was missing a dependency for my seed script, but got a lot more output:

```
gitpod /workspace/foo $ npx prisma db seed --preview-feature
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Running seed from "prisma/seed.js" ...
Result:
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /workspace/foo/prisma/seed.js
- /workspace/foo/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/workspace/foo/prisma/seed.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspace/foo/prisma/seed.js',
    '/workspace/foo/[eval]'
  ]
}
Error: Command failed with exit code 1: node -e "
console.info('Result:')

const __seed = require('./prisma/seed.js')
const __keys = Object.keys(__seed)

async function runSeed() {
  // Execute "seed" named export or default export
  if (__keys && __keys.length) {
    if (__keys.indexOf('seed') !== -1) {
      return __seed.seed()
    } else if (__keys.indexOf('default') !== -1) {
      return __seed.default()
    }
  }
}

runSeed()
  .then(function (result) {
    if (result) {
      console.log(result)
    }
  })
  .catch(function (e) {
    console.error('Error from seed:')
    throw e
  })
"
```

**Comment by gurleensethi** [comment]
Facing the same issue

```
Running seed from src/database/prisma/seed.ts ...
Result:
node:internal/modules/cjs/loader:930
  throw err;
  ^

Error: Cannot find module ...
Require stack:
... Stack Trace Here ...

Error: Command failed with exit code 1: ts-node --eval "
// @ts-ignore
declare const require: any


console.info('Result:')

const __seed = require('./src/database/prisma/seed.ts')
const __keys = Object.keys(__seed)

async function runSeed() {
  // Execute "seed" named export or default export
  if (__keys && __keys.length) {
    if (__keys.indexOf('seed') !== -1) {
      return __seed.seed()
    } else if (__keys.indexOf('default') !== -1) {
      return __seed.default()
    }
  }
}

runSeed()
  .then(function (result) {
    if (result) {
      console.log(result)
    }
  })
  .catch(function (e) {
    console.error('Error from seed:')
    throw e
  })


export {}
```

The stack trace has been hidden to due privacy reasons with `...`.

Comment used -> `npx prisma db seed --preview-feature`

**Comment by gurleensethi** [comment]
For me it was an issue with relative import.

I am imported a module like this:

```ts
import utils from "src/common/utils";
```

It got fixed when I used:

```ts
import utils from "../../utils";
```

**Comment by pantharshit00** [comment]
Seeding is getting a rework so this might get automatically addressed: https://github.com/prisma/prisma/pull/8146

**Comment by tomhoule** [comment]
Yep, can confirm this should be addressed by the new implementation. There is an integration release in the PR comments you can try, feedback is very much wanted.

**Comment by Jolg42** [comment]
🗒️ We heard the feedback and we are planning a redesign of `db seed` (currently planned to be released early September)

How it will work is that a `prisma.seed` property in the package.json of your project will be required if you want to use `prisma db seed`.

This property is where you will be able to put any command you want to execute your seed script.

More info/details & how to try it out now in:
https://github.com/prisma/prisma/issues/8732

**Comment by janpio** [comment]
The redesign of `db seed` was released with Prisma 3. Please try it, this problem should be gone.
