### ISSUE TITLE
Attempting to mock clocks causes prisma create to never return

### ISSUE THREAD

**Issue by goofiw** [prisma/prisma#7424]
### Bug description

Mocking timers with jest before running our seed function causes the a create function never to return.  Without a `$transaction` it seems to work fine

### How to reproduce

1.  Write a jest test
2. mock the time:
	  ```
	  jest.useFakeTimers('modern');
	  jest.setSystemTime(new Date(`2021-01-07T12:00:00.000Z`);
	  ```
3.  Call a prisma create:
	  ```
	  const sessions = await client.$transaction([
		    client.groupSession.create({
		      data: {
		        startTime: new Date('2021-01-01T11:00:00.000Z'),
		        timezoneName: 'America/Vancouver',
		      },
		    }),
		    client.groupSession.create({
		      data: {
		        startTime: new Date('2021-01-02T11:00:00.000Z'),
		        timezoneName: 'America/Vancouver',
		    
		      },
		    }),
	  ...
	  ```
4.  the await never returns

### Expected behavior

The await returns with sessions seeded.

### Prisma information

can add if needed

### Environment & setup

```
MacOS Big Sur (mac chips)
Postgresql (With timescaldb) - docker image: timescaledb:2.0.0-pg12
Node 16.2
```

### Prisma Version

```
"@prisma/client": "^2.22.1", (resolved to 2.22.1)
```

**Comment by pantharshit00** [comment]
Thanks for the report, I can reproduce this with `2.25`

Minimal reproduction:
```prisma
model User {
  id String @id @default(cuid())
  startTime DateTime
}
```

```ts
const { PrismaClient } = require("@prisma/client");

jest.useFakeTimers("modern");
jest.setSystemTime(new Date(`2021-01-07T12:00:00.000Z`));

const prisma = new PrismaClient();

afterAll(async () => {
  await prisma.$disconnect();
});

describe("sample suite", () => {
  it("should work", async () => {
    const sample = await prisma.user.create({
      data: {
        startTime: new Date("2021-01-01T11:00:00.000Z"),
      },
    });
    expect(sample).toBeDefined();
  });
});

```
 npx jest                                                                                                                         ─╯
 FAIL  ./prisma.test.js (5.698 s)
  sample suite
    ✕ should work (5002 ms)

  ● sample suite › should work

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       7 |
       8 | describe("sample suite", () => {
    >  9 |   it("should work", async () => {
         |   ^
      10 |     const sample = await prisma.user.create({
      11 |       data: {
      12 |         startTime: new Date("2021-01-01T11:00:00.000Z"),

      at prisma.test.js:9:3
      at Object.<anonymous> (prisma.test.js:8:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.795 s
Ran all test suites.

```

**Comment by pantharshit00** [comment]
This is still reproducible in the latest dev version: 
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/22195362/180267768-6abf11c5-dc2f-4223-abc3-a3feb1fcf399.png">

**Comment by njofce** [comment]
I am also experiencing the same issue with Prisma 4.4.0 and Jest 28.1.3, though it's a bit different situation:

1. Before any DB operations, the timers are mocked: `jest.useFakeTimers().setSystemTime(new Date(Date.parse('10 Sep 2021 22:00:00 GMT')));`
2. Different create operations work fine (without any transaction)
3. `findFirst`, `findMany` work fine
4. `findUnique` gets stuck

The workaround where the clock advances seem to solve the issue! However it feels like a bug where you can't fully control the time in the tests.

**Comment by bakoushin** [comment]
I was able to work around this issue using
```javascript
jest.useFakeTimers({ doNotFake: ['nextTick'] });
```

**Comment by cesarvspr** [comment]
Any work around for older jest versions?

**Comment by QuotableWater7** [comment]
> My personal recommendation would be to avoid jest entirely

... Prisma "solutions" never fail to amaze me.
