### ISSUE TITLE
db push --force-reset is not creating database if it doesn't exist

### ISSUE THREAD

**Issue by evoactivity** [prisma/prisma#7440]
### Bug description

running `npx prisma db push --force-reset` for a database that does not exist gives me an error instead of creating the database.

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "mydb-test", schema "public" at "localhost:5432"

Response: Database `mydb-test.public` does not exist on the database server at `localhost:5432`.
Error: UserFacingError
```

If I manually create the database using the same user then running `npx prisma db push --force-reset` my schema is correctly setup.

With debug output

```
DEBUG="*" npx prisma db push --force-reset                                                                                                         ─╯
  prisma:loadEnv project root found at {MY_PATH}/backend/package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from {MY_PATH}/backend/.env +0ms
Environment variables loaded from .env
  prisma:engines using NAPI: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +1ms
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig Using Query Engine Binary at: {MY_PATH}/backend/node_modules/@prisma/engines/query-engine-darwin +0ms
Datasource "db": PostgreSQL database "mydb-test", schema "public" at "localhost:5432"
  prisma:getConfig Using Query Engine Binary at: {MY_PATH}/backend/node_modules/@prisma/engines/query-engine-darwin +51ms

  prisma:migrateEngine:rpc starting migration engine with binary: {MY_PATH}/backend/node_modules/@prisma/engines/migration-engine-darwin +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"reset","params":{}} +18ms
  prisma:migrateEngine:stderr Jun 03 15:42:09.053  INFO migration_engine: Starting migration engine RPC server git_hash="f3e341280d96d0abc068f97e959ddf01f321a858" +0ms
Error: Error: UserFacingError
    at ChildProcess.<anonymous> ({MY_PATH}/backend/node_modules/prisma/build/index.js:57396:28)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

This was working fine until I tried to run my integration tests today.

I was on 2.23.0 when I first saw the error and then tried on 2.24.0 and saw the same issue.

### How to reproduce

run `npx prisma db push --force-reset`

### Expected behavior

A database is created if it does not already exist

### Prisma information

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

enum Role {
  USER
  INTERPRETER
  ADMIN
}

enum ReportTypes {
  FEEDBACK
  CONNECTED
  DISCONNECTED
}

model Token {
  id          String   @id @default(cuid())
  token       String   @unique
  description String?
  user        User?    @relation(fields: [userId], references: [id])
  userId      String?
  booking     Booking? @relation(fields: [bookingId], references: [id])
  bookingId   String?
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  revoked     Boolean  @default(false)
}

model User {
  id           String    @id @default(cuid())
  sharetribeId String?   @unique
  role         Role      @default(USER)
  name         String
  email        String    @unique
  avatar       String?
  tokens       Token[]
  bookings     Booking[]
  createdAt    DateTime  @default(now())
  updatedAt    DateTime  @updatedAt
  lastLogin    DateTime?
}

model Booking {
  id              String   @id @default(cuid())
  sharetribeId    String?  @unique
  startAt         DateTime
  remoteUser      Boolean  @default(false)
  reason          String?
  location        String?
  information     String?
  preferredGender String?
  users           User[]
  tokens          Token[]
  onDemand        Boolean  @default(false)
  createdAt       DateTime @default(now())
  updatedAt       DateTime @updatedAt
}

model Report {
  id                  String      @id @default(cuid())
  bookingSharetribeId String
  userSharetribeId    String
  type                ReportTypes
  score               Int?
  createdAt           DateTime    @default(now())
  updatedAt           DateTime    @updatedAt
}

```

### Environment & setup

- OS: MacOS BigSur 11.4
- Database: PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) 
- Node.js version: 14.16.1

PostgreSQL is running in a docker container with an exposed port of 5432
prisma is running on host os

### Prisma Version

```
prisma               : 2.24.0
@prisma/client       : 2.24.0
Current platform     : darwin
Query Engine         : query-engine f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt f3e341280d96d0abc068f97e959ddf01f321a858 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : f3e341280d96d0abc068f97e959ddf01f321a858
Studio               : 0.397.0
```

**Comment by ali-gen** [comment]
Yes

**Comment by pantharshit00** [comment]
I can reproduce this with `2.25`. Looks like only happening with `--force-reset`

**Comment by janpio** [comment]
I can also confirm this is happening:
```
+ npx prisma db push --force-reset --accept-data-loss
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "platforms-serverless_azure-functions-linux", schema "public" at "e2e-tests-postgres.cdoyhcosd7km.us-east-1.rds.amazonaws.com:5432"

Error: Error in migration engine: Starting migration engine RPC server
Database `platforms-serverless_azure-functions-linux.public` does not exist on the database server at `e2e-tests-postgres.cdoyhcosd7km.us-east-1.rds.amazonaws.com:5432`.
```

**Comment by tomhoule** [comment]
> Starting migration engine RPC server

This should not be showing up in the error, we need to look into that as well.

**Comment by Jolg42** [comment]
I can confirm it errors with

```
Prisma schema loaded from prisma/schema.prisma
Datasource "my_db": PostgreSQL database "reproforcereset", schema "public" at "localhost:5432"

Error: Error in migration engine: Database `reproforcereset.public` does not exist on the database server at `localhost:5432`.
```

It's not linked the the new error handling. It's because we implemented it that it only creates the db after. Moving the logic the create the db is it doesn't exit results in 
```
Prisma schema loaded from prisma/schema.prisma
Datasource "my_db": PostgreSQL database "reproforcereset", schema "public" at "localhost:5432"

PostgreSQL database reproforcereset created at localhost:5432


The PostgreSQL database "reproforcereset" from "localhost:5432" was successfully reset.

🚀  Your database is now in sync with your schema. Done in 39ms
```
