### ISSUE TITLE
npx prisma generate --watch Error: write EPIPE

### ISSUE THREAD

**Issue by huoxiangdong** [prisma/prisma#7452]
### Bug description

Running `npx prisma generate` watch mode will generate the following error

```
Generated Prisma Client (2.24.1) to ./node_modules/@prisma/cli
ent in 21.09s

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:769:11)
    at Socket._write (node:net:781:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at GeneratorProcess.sendMessage (/Users/farmer/Desktop/nine-link-ring/MagicCube-API/node_modules/prisma/build/index.js:27660:24)
    at /Users/farmer/Desktop/nine-link-ring/MagicCube-API/node_modules/prisma/build/index.js:27704:14
    at new Promise (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### How to reproduce

- schema

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["microsoftSqlServer"]
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}
```

 - run
 `npx prisma db pull`
 `npx prisma generate  --watch`

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["microsoftSqlServer"]
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

model ACCOUNT {
  ACCOUNT_ID       Int                @id @default(autoincrement())
  ACCOUNT_NAME     String             @db.NVarChar(10)
  CODE             String             @db.NVarChar(20)
  OPEN_TIME        DateTime           @db.Date
  ALL_PURPOSE_CARD ALL_PURPOSE_CARD[]
}
```

### Environment & setup

OS: Mac OS
Database: SqlServer
Node.js version: v16.3.0

### Prisma Version

```
prisma               : 2.24.0
@prisma/client       : 2.24.1
Current platform     : darwin
Query Engine         : query-engine f3e341280d96d0abc068f97e959ddf01f321a858 (at ../../../.tnvm/versions/node/v16.3.0/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli f3e341280d96d0abc068f97e959ddf01f321a858 (at ../../../.tnvm/versions/node/v16.3.0/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core f3e341280d96d0abc068f97e959ddf01f321a858 (at ../../../.tnvm/versions/node/v16.3.0/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt f3e341280d96d0abc068f97e959ddf01f321a858 (at ../../../.tnvm/versions/node/v16.3.0/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : f3e341280d96d0abc068f97e959ddf01f321a858
Studio               : 0.397.0
```

**Comment by pantharshit00** [comment]
Hello @huoxiangdong 

I wasn't able to reproduce this with `2.25.0`. Can you please try that again with that once?

If you can still reproduce this, can you list out the exact change you are making in order for this to trigger.

**Comment by saevarb** [comment]
I can consistently reproduce this bug:

1. Run `prisma generate --watch` in one place
2. Run `prisma format`

**Comment by pantharshit00** [comment]
Sorry for very late reply here, but @saevarb can you please try out with the latest version once?

**Comment by saevarb** [comment]
> Sorry for very late reply here, but @saevarb can you please try out with the latest version once?

I haven't run into this bug for months now, and it's definitely not showing on 3.14. 

I can see that I neglected to mention which version I was using previously, but from looking at the commit log it seems it may have been ~2.29. I'm not sure when it disappeared, but I haven't seen it for a good while, in any of the projects I use prisma in.

**Comment by janpio** [comment]
Perfect! Let's close this then and if anyone ever encounters this again, either comment here or open a new issue please.
