### ISSUE TITLE
the quickstart failed

### ISSUE THREAD

**Issue by yunfan** [prisma/prisma#7530]
### Bug description

i am a newbie here, so i followed the official quickstart here <https://www.prisma.io/docs/getting-started/quickstart>
when running `npm run dev` , it hasnt output the expected result, instead, it gave a error report like this

```
jyf@x1:~/hack/starter$ npm run dev

> dev
> ts-node ./script.ts


/home/jyf/hack/starter/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
script.ts:1:10 - error TS2305: Module '"@prisma/client"' has no exported member 'PrismaClient'.

1 import { PrismaClient } from '@prisma/client'
           ~~~~~~~~~~~~

    at createTSError (/home/jyf/hack/starter/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/home/jyf/hack/starter/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/home/jyf/hack/starter/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/home/jyf/hack/starter/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/home/jyf/hack/starter/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/home/jyf/hack/starter/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
npm ERR! code 1
npm ERR! path /home/jyf/hack/starter
npm ERR! command failed
npm ERR! command sh -c ts-node ./script.ts

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jyf/.npm/_logs/2021-06-08T15_31_06_703Z-debug.log
```

i think it must be the document out of date which caused the problem, please fix it as soon as possble

### How to reproduce

just follow the link <https://www.prisma.io/docs/getting-started/quickstart>

### Prisma information

no

### Environment & setup

- OS: ubuntu 21.04
- Database: SQLite
- Node.js version: v12.21.0

### Prisma Version

```
Environment variables loaded from prisma/.env
prisma               : 2.24.1
@prisma/client       : 2.24.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 18095475d5ee64536e2f93995e48ad800737a9e4 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 18095475d5ee64536e2f93995e48ad800737a9e4
Studio               : 0.397.0

```

**Comment by yunfan** [comment]
yes and sorry for that
