### ISSUE TITLE
Flaky `Engine is not yet connected.` CI test with Node-API

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#7569]
### Bug description

This test is flaky with Node-API

```
FAIL src/__tests__/integration/happy/disconnect-while-query/test.ts
  ✕ disconnect-while-query (770 ms)
  ● disconnect-while-query
    Invalid `prisma.user.findMany()` invocation in
    /home/runner/work/prisma/prisma/src/packages/client/src/__tests__/integration/happy/disconnect-while-query/test.ts:8:25
       5 const prisma = new PrismaClient()
       6 
       7 await prisma.user.findMany()
    →  8 const a = prisma.user.findMany(
      Engine is not yet connected.
       0: user_facing_errors::Error::new_non_panic_with_current_backtrace
       1: query_engine_napi::error::<impl core::convert::From<query_engine_napi::error::ApiError> for user_facing_errors::Error>::from
       2: query_engine_napi::error::<impl core::convert::From<query_engine_napi::error::ApiError> for napi::error::Error>::from
       3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
       4: tokio::runtime::task::core::CoreStage<T>::poll
       5: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
       6: tokio::runtime::task::harness::poll_future
       7: tokio::runtime::task::harness::Harness<T,S>::poll
       8: std::thread::local::LocalKey<T>::with
       9: tokio::runtime::thread_pool::worker::Context::run_task
      10: tokio::runtime::thread_pool::worker::Context::run
      11: tokio::macros::scoped_tls::ScopedKey<T>::set
      12: tokio::runtime::thread_pool::worker::run
      13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
      14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
      15: tokio::runtime::task::harness::Harness<T,S>::poll
      16: tokio::runtime::blocking::pool::Inner::run
      17: std::sys_common::backtrace::__rust_begin_short_backtrace
      18: core::ops::function::FnOnce::call_once{{vtable.shim}}
      19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
      at ../../../../../../../../rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
            <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
      at ../../../../../../../../rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
            std::sys::unix::thread::Thread::new::thread_start
      at ../../../../../../../../rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
        20: start_thread
        21: clone
      at cb (src/runtime/PrismaClientFetcher.ts:172:17)
```

In Github Actions:
https://github.com/prisma/prisma/pull/7566/checks?check_run_id=2783712904#step:8:1202

**Comment by janpio** [comment]
Internal Slack: https://prisma-company.slack.com/archives/C02232M9CP8/p1623346549042300

**Comment by janpio** [comment]
- Error message string from Rust: https://github.com/prisma/prisma-engines/blob/f461292a2242db52d9f4c87995f0237aacd300d2/query-engine/query-engine-napi/src/error.rs#L23
- The 3 uses of it in the codebase: https://github.com/prisma/prisma-engines/blob/d649ba712590fad2c3b015fc9f16643c0e86b063/query-engine/query-engine-napi/src/engine.rs#L235-L287
Which one of those is triggered in these tests?

**Comment by janpio** [comment]
Another example for this failure:

```
[2021-06-10T19:35:57Z]  FAIL  src/__tests__/integration/happy/blog/test.ts
[2021-06-10T19:35:57Z]   ● blog
[2021-06-10T19:35:57Z]
[2021-06-10T19:35:57Z]
[2021-06-10T19:35:57Z]     Invalid `db.user.findMany()` invocation in
[2021-06-10T19:35:57Z]     /app/src/packages/client/src/__tests__/integration/happy/blog/test.ts:46:17
[2021-06-10T19:35:57Z]
[2021-06-10T19:35:57Z]       43 db.$disconnect()
[2021-06-10T19:35:57Z]       44 expect(requests.length).toBe(2)
[2021-06-10T19:35:57Z]       45
[2021-06-10T19:35:57Z]     → 46 await db.user.findMany(
[2021-06-10T19:35:57Z]       Engine is not yet connected.
[2021-06-10T19:35:57Z]        0: user_facing_errors::Error::new_non_panic_with_current_backtrace
[2021-06-10T19:35:57Z]        1: query_engine_napi::error::<impl core::convert::From<query_engine_napi::error::ApiError> for user_facing_errors::Error>::from
[2021-06-10T19:35:57Z]        2: query_engine_napi::error::<impl core::convert::From<query_engine_napi::error::ApiError> for napi::error::Error>::from
[2021-06-10T19:35:57Z]        3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
[2021-06-10T19:35:57Z]        4: tokio::runtime::task::core::CoreStage<T>::poll
[2021-06-10T19:35:57Z]        5: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
[2021-06-10T19:35:57Z]        6: tokio::runtime::task::harness::poll_future
[2021-06-10T19:35:57Z]        7: tokio::runtime::task::harness::Harness<T,S>::poll
[2021-06-10T19:35:57Z]        8: std::thread::local::LocalKey<T>::with
[2021-06-10T19:35:57Z]        9: tokio::runtime::thread_pool::worker::Context::run_task
[2021-06-10T19:35:57Z]       10: tokio::runtime::thread_pool::worker::Context::run
[2021-06-10T19:35:57Z]       11: tokio::macros::scoped_tls::ScopedKey<T>::set
[2021-06-10T19:35:57Z]       12: tokio::runtime::thread_pool::worker::run
[2021-06-10T19:35:57Z]       13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
[2021-06-10T19:35:57Z]       14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
[2021-06-10T19:35:57Z]       15: tokio::runtime::task::harness::Harness<T,S>::poll
[2021-06-10T19:35:57Z]       16: tokio::runtime::blocking::pool::Inner::run
[2021-06-10T19:35:57Z]       17: std::sys_common::backtrace::__rust_begin_short_backtrace
[2021-06-10T19:35:57Z]       18: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-06-10T19:35:57Z]       19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-06-10T19:35:57Z]
[2021-06-10T19:35:57Z]       at ../../../../rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
[2021-06-10T19:35:57Z]             <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-06-10T19:35:57Z]       at ../../../../rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
[2021-06-10T19:35:57Z]             std::sys::unix::thread::Thread::new::thread_start
[2021-06-10T19:35:57Z]       at ../../../../rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
[2021-06-10T19:35:57Z]         20: start_thread
[2021-06-10T19:35:57Z]         21: clone
[2021-06-10T19:35:57Z]       at cb (src/__tests__/integration/happy/blog/node_modules/@prisma/client/runtime/index.js:33793:17)
[2021-06-10T19:35:57Z]       at Object.<anonymous> (src/__tests__/integration/happy/blog/test.ts:46:3)
```

via https://buildkite.com/prisma/prisma2-test/builds/7738#4a19c60f-b26c-4866-ba80-419a8419f483/181-677

Failing query there is https://github.com/prisma/prisma/blob/d1543af732818f1d8f864ec141d8ae66b987f1fb/src/packages/client/src/__tests__/integration/happy/blog/test.ts#L46
The `db.$disconnect()` that is run before that, is missing the `await` so might still be in progress when the actual `await db.user.findMany()` is executed. Probably things overlap different with Node-API Engine than they do with NodeEngine because of different performance characteristics (or implementation bugs in Node-API Engine).

**Comment by janpio** [comment]
Another example from: https://github.com/prisma/prisma/issues/7626

```
FAIL src/__tests__/integration/happy/disconnect-race/test.ts
  ✕ disconnect-race (1767 ms)

  ● disconnect-race


    Invalid `prisma.user.findMany()` invocation in
    /home/runner/work/prisma/prisma/src/packages/client/src/__tests__/integration/happy/disconnect-race/test.ts:9:31

       6 
       7 await prisma.user.findMany()
       8 prisma.$disconnect()
    →  9 const a = await prisma.user.findMany(
      Engine is not yet connected.
       0: user_facing_errors::Error::new_non_panic_with_current_backtrace
       1: query_engine_napi::error::<impl core::convert::From<query_engine_napi::error::ApiError> for user_facing_errors::Error>::from
       2: query_engine_napi::error::<impl core::convert::From<query_engine_napi::error::ApiError> for napi::error::Error>::from
       3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
       4: tokio::runtime::task::core::CoreStage<T>::poll
       5: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
       6: tokio::runtime::task::harness::poll_future
       7: tokio::runtime::task::harness::Harness<T,S>::poll
       8: std::thread::local::LocalKey<T>::with
       9: tokio::runtime::thread_pool::worker::Context::run_task
      10: tokio::runtime::thread_pool::worker::Context::run
      11: tokio::macros::scoped_tls::ScopedKey<T>::set
      12: tokio::runtime::thread_pool::worker::run
      13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
      14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
      15: tokio::runtime::task::harness::Harness<T,S>::poll
      16: tokio::runtime::blocking::pool::Inner::run
      17: std::sys_common::backtrace::__rust_begin_short_backtrace
      18: core::ops::function::FnOnce::call_once{{vtable.shim}}
      19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once

      at ../../../../../../../../rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
            <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
      at ../../../../../../../../rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
            std::sys::unix::thread::Thread::new::thread_start
      at ../../../../../../../../rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
        20: start_thread
        21: clone
      at cb (src/runtime/PrismaClientFetcher.ts:172:17)
```

Seems identical what is done in the `happy/blog/test.ts` in the previous message.

**Comment by janpio** [comment]
Here is another one: https://github.com/prisma/prisma/runs/4409393821?check_suite_focus=true#step:9:1167

**Comment by etc-tiago** [comment]
This error occurs most times when e2e test (frontend) stays longer than 5 minutes with frequent access to api with prism. The connection timeout and other timeouts are 8 hours and the problem is still happening.

My use case is for a site that has certain actions depending on the pages. The e2e test makes use of variations and sends requests depending on the action.

Any update on this problem or improvement of the message, possibility of reconnection by callback (.$on) or any other solution that is effective that solves it?

**Comment by janpio** [comment]
We have not heard of any cases outside our own test suite, so this obviously was lowest priority. Can you provide us some more information what exactly is happening for you with which queries and version and so on? We definitely need more information.

**Comment by etc-tiago** [comment]
I can't give you database details for intellectual property reasons but this is the Github ci log after 7 minutes of running.

```txt
2022-01-19T14:06:10.2179114Z 0|_dev     | PrismaClientUnknownRequestError: Engine is not yet connected.
2022-01-19T14:06:10.2179692Z 0|_dev     |    0: user_facing_errors::Error::new_non_panic_with_current_backtrace
2022-01-19T14:06:10.2180313Z 0|_dev     |    1: query_engine::error::<impl core::convert::From<query_engine::error::ApiError> for napi::error::Error>::from
2022-01-19T14:06:10.2180897Z 0|_dev     |    2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-01-19T14:06:10.2181393Z 0|_dev     |    3: tokio::runtime::task::core::CoreStage<T>::poll
2022-01-19T14:06:10.2181850Z 0|_dev     |    4: tokio::runtime::task::harness::Harness<T,S>::poll
2022-01-19T14:06:10.2182307Z 0|_dev     |    5: tokio::runtime::thread_pool::worker::Context::run_task
2022-01-19T14:06:10.2182733Z 0|_dev     |    6: tokio::runtime::thread_pool::worker::Context::run
2022-01-19T14:06:10.2183160Z 0|_dev     |    7: tokio::macros::scoped_tls::ScopedKey<T>::set
2022-01-19T14:06:10.2183581Z 0|_dev     |    8: tokio::runtime::thread_pool::worker::run
2022-01-19T14:06:10.2185867Z 0|_dev     |    9: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
2022-01-19T14:06:10.2186675Z 0|_dev     |   10: tokio::runtime::task::harness::Harness<T,S>::poll
2022-01-19T14:06:10.2188228Z 0|_dev     |   11: tokio::runtime::blocking::pool::Inner::run
2022-01-19T14:06:10.2188814Z 0|_dev     |   12: std::sys_common::backtrace::__rust_begin_short_backtrace
2022-01-19T14:06:10.2279093Z 0|_dev     |   13: core::ops::function::FnOnce::call_once{{vtable.shim}}
2022-01-19T14:06:10.2279787Z 0|_dev     |   14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2022-01-19T14:06:10.2280413Z 0|_dev     |              at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
2022-01-19T14:06:10.2280971Z 0|_dev     |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2022-01-19T14:06:10.2281582Z 0|_dev     |              at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
2022-01-19T14:06:10.2282115Z 0|_dev     |       std::sys::unix::thread::Thread::new::thread_start
2022-01-19T14:06:10.2282729Z 0|_dev     |              at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
2022-01-19T14:06:10.2283158Z 0|_dev     |   15: start_thread
2022-01-19T14:06:10.2283446Z 0|_dev     |   16: clone
2022-01-19T14:06:10.2283711Z 0|_dev     | 
2022-01-19T14:06:10.2284172Z 0|_dev     |     at cb (/home/runner/work/codebase/codebase/backend/server/dist/_dev.js:146444:27)
2022-01-19T14:06:10.2284843Z 0|_dev     |     at async withAutenticationMiddleware (/home/runner/work/codebase/codebase/backend/server/dist/_dev.js:1119:24) {
2022-01-19T14:06:10.2285548Z 0|_dev     |   clientVersion: '3.8.1'
2022-01-19T14:06:10.2285812Z 0|_dev     | }
2022-01-19T14:06:10.2286253Z 0|_dev     | PrismaClientUnknownRequestError: Engine is not yet connected.
2022-01-19T14:06:10.2286798Z 0|_dev     |    0: user_facing_errors::Error::new_non_panic_with_current_backtrace
2022-01-19T14:06:10.2287689Z 0|_dev     |    1: query_engine::error::<impl core::convert::From<query_engine::error::ApiError> for napi::error::Error>::from
2022-01-19T14:06:10.2288304Z 0|_dev     |    2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-01-19T14:06:10.2288804Z 0|_dev     |    3: tokio::runtime::task::core::CoreStage<T>::poll
2022-01-19T14:06:10.2289280Z 0|_dev     |    4: tokio::runtime::task::harness::Harness<T,S>::poll
2022-01-19T14:06:10.2289762Z 0|_dev     |    5: tokio::runtime::thread_pool::worker::Context::run_task
2022-01-19T14:06:10.2290248Z 0|_dev     |    6: tokio::runtime::thread_pool::worker::Context::run
2022-01-19T14:06:10.2290716Z 0|_dev     |    7: tokio::macros::scoped_tls::ScopedKey<T>::set
2022-01-19T14:06:10.2291294Z 0|_dev     |    8: tokio::runtime::thread_pool::worker::run
2022-01-19T14:06:10.2291736Z 0|_dev     |    9: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
2022-01-19T14:06:10.2292216Z 0|_dev     |   10: tokio::runtime::task::harness::Harness<T,S>::poll
2022-01-19T14:06:10.2292675Z 0|_dev     |   11: tokio::runtime::blocking::pool::Inner::run
2022-01-19T14:06:10.2293155Z 0|_dev     |   12: std::sys_common::backtrace::__rust_begin_short_backtrace
2022-01-19T14:06:10.2293646Z 0|_dev     |   13: core::ops::function::FnOnce::call_once{{vtable.shim}}
2022-01-19T14:06:10.2294182Z 0|_dev     |   14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2022-01-19T14:06:10.2294795Z 0|_dev     |              at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
2022-01-19T14:06:10.2295340Z 0|_dev     |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2022-01-19T14:06:10.2295924Z 0|_dev     |              at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1691:9
2022-01-19T14:06:10.2296436Z 0|_dev     |       std::sys::unix::thread::Thread::new::thread_start
2022-01-19T14:06:10.2297016Z 0|_dev     |              at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys/unix/thread.rs:106:17
2022-01-19T14:06:10.2297443Z 0|_dev     |   15: start_thread
2022-01-19T14:06:10.2297734Z 0|_dev     |   16: clone
2022-01-19T14:06:10.2297951Z 0|_dev     | 
2022-01-19T14:06:10.2298424Z 0|_dev     |     at cb (/home/runner/work/codebase/codebase/backend/server/dist/_dev.js:146444:27)
2022-01-19T14:06:10.2299256Z 0|_dev     |     at async withAutenticationMiddleware (/home/runner/work/codebase/codebase/backend/server/dist/_dev.js:1119:24) {
2022-01-19T14:06:10.2299843Z 0|_dev     |   clientVersion: '3.8.1'
2022-01-19T14:06:10.2300115Z 0|_dev     | }
```

- It is in a monorepo with yarn workspace and turborepo, with no-hist in all prisma packages and engines.
- The problem occurs since version 3.4, however the codebase has grown a lot in the last few weeks and the problem started to appear more.
- There are tests that pass without problems, and others that fail several times before passing (no changes, just running again), which may indicate failure/lack of memory.


Is there any way to debug the prisma, something that can bring more useful details?

**Comment by janpio** [comment]
With `DEBUG=*` you can enable a firehose of logs (more details see https://pris.ly/d/debugging).

**Comment by evencheng-rl** [comment]
Also run into this issue recently and it's been flakey. It can recover itself with a rerun. The scripts runs for ~9 seconds and it passes in other transactions. I see it breaks several time at findMany() but not 100% sure the correlation.

```
^
PrismaClientUnknownRequestError: 
Invalid `prisma.setAttribute.findMany()` invocation in
/home/runner/work/resilience-platform/resilience-platform/apps/example-gql-nest/prisma/seeder/practitioner/practitioners.seed.ts:10:47

   7   count: number,
   8   bookable = true,
   9 ): Promise<void> => {
→ 10   const languages = await prisma.setAttribute.findMany(
Engine is not yet connected.
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>

    at Pn.handleRequestError (/home/runner/work/resilience-platform/resilience-platform/node_modules/@prisma/example-gql-nest-client/runtime/library.js:171:7103)
    at Pn.handleAndLogRequestError (/home/runner/work/resilience-platform/resilience-platform/node_modules/@prisma/example-gql-nest-client/runtime/library.js:171:6358)
    at Pn.request (/home/runner/work/resilience-platform/resilience-platform/node_modules/@prisma/example-gql-nest-client/runtime/library.js:171:6237)
    at async seedPractitioners (/home/runner/work/resilience-platform/resilience-platform/apps/example-gql-nest/prisma/seeder/practitioner/practitioners.seed.ts:10:21) {
  clientVersion: '4.14.1'
}
Error: Process completed with exit code 1.
```

**Comment by Jolg42** [comment]
@etc-tiago @evencheng-rl this is unexpected to me 🤔 

Maybe try adding `await prisma.$connect()` right before and see if that changes anything. (calling `$connect()` explicitly is not required, but I'm curious to see if it changes something or not for you)

At the moment, we're missing a good reproduction to look at it in detail, if you have something you could share it would help.
Does it happen often? Or only "once in a while"?
Does this still happens with Prisma `4.15.0`? (latest version)

**Comment by millsp** [comment]
I found that new flaky tests have been detected around this
https://buildpulse.io/@prisma/prisma/tests/2892009034

**Comment by nettrino** [comment]
Also running into this issue in our codebase where a test might fail randomly with 
```
PrismaClientUnknownRequestError: 
Invalid `model.create()` invocation in
/home/runner/work/platform/platform/node_modules/factory-prisma/dist/index.js:33:55

  30 
  31 return {
  32     fields: fieldsFunc,
→ 33     instance: function (overrides) { return model.create(
Engine is not yet connected.
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>

    at si.handleRequestError (/home/runner/work/platform/platform/node_modules/@prisma/client/runtime/library.js:125:7007)
    at si.handleAndLogRequestError (/home/runner/work/platform/platform/node_modules/@prisma/client/runtime/library.js:125:6[151](https://github.com/crashappsec/platform/actions/runs/7291399550/job/19870231787#step:6:152))
    at si.request (/home/runner/work/platform/platform/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/home/runner/work/platform/platform/node_modules/@prisma/client/runtime/library.js:130:10025)
    at async Promise.all (index 49)```

**Comment by tastycrayon** [comment]
For my case the problem happened after I did 
```js
arr.forEach((e)=> {
    await prisma.recipe.create(e)
})
```
But got fixed after I did
```js
 for (let i = 0; i < arr.length; i++) {
        const e = arr[i];
        await prisma.recipe.create(e)
 }
 ```

**Comment by scientist1642** [comment]
Exactly the same thing happened to me, fixed after for loop. Thanks @tastycrayon

**Comment by togakangaroo** [comment]
I also just saw this happen within a docker container I'm building to run migrations. Changing the code to get rid of `forEach` made it work

**Comment by janpio** [comment]
Does the switch from `forEach` to a `for` loop make sense to anyone? Any way to explain what is going on here?

**Comment by togakangaroo** [comment]
Potentially some bit of metaprogramming. Maybe something looking upward the
call stack frames which finds the wrong thing at the wrong spot when you're
inside of a forEach. I've seen similar happen in other systems that got too
clever for their own good (some of these I wrote myself)

**Comment by Su386yt** [comment]
I tried switching the for each loops to no avail, however manually adding ``prisma.$connect()`` seemed to fix it

**Comment by bj-nostra** [comment]
> Does the switch from forEach to a for loop make sense to anyone? Any way to explain what is going on here?

Generally speaking, `forEach` does not support `async/await` functions.

**Comment by FezVrasta** [comment]
I'm experiencing this in production, not on a test suite. Could someone help me understand what it means? My database instance is healthy and the pod where Prisma is running looks healthy too.

**Comment by jkomyno** [comment]
Hi there,
As part of our effort to clean up our GitHub repo, we’re closing this issue to help focus on features and improvements that align with our focus areas and those of our community.

We point out two known workarounds:
- using an [explicit `await prisma.$connect()`](https://github.com/prisma/prisma/issues/7569#issuecomment-1779936856) before submitting your Prisma queries
- [don't accumulate `async` function calls in `async`-incompatible higher-order functions](https://github.com/prisma/prisma/issues/7569#issuecomment-1895435566), like `Array.prototype.forEach`.

We're working on something that will remove the root cause of this problem altogether, and that will be available to your sometimes in 2025.

---

This issue was originally created for internal tracking purposes, but if you feel this is important to you, feel free to reopen the issue and get like-minded users to upvote as we will prioritize fixing issues based on community interest.

For more insight into our priorities and how we’re thinking about the future of Prisma, please see our blog post: https://www.prisma.io/blog/prisma-orm-manifesto.

Thank you for your understanding and support!

**Comment by ngannt1710** [comment]
I tried add await prisma.$connect() and replace all forEach to for loop. But some time it still occurred this error. I have use Promisse.all and I don't know if it's because of it. Please give me some advice.

**Comment by CarlosBCIII** [comment]
I have all functions with await and im still with this error, but, only if im using others clouds like aws rds, render, etc... dont happen with db in prisma cloud.

**Comment by seb-mynotary** [comment]
> We're working on something that will remove the root cause of this problem altogether, and that will be available to your sometimes in 2025.

@jkomyno Thanks for your explanation, can we track the progress somewhere ?

**Comment by siwaneden** [comment]
I have the same error, can someone help me?


```text

Engine is not yet connected.
Backtrace []
    at l (.next/server/app/api/pedidos/pedidos/route.js:1:2448) {
  clientVersion: '6.11.1'
}
Erro ao buscar pedidos: Error [PrismaClientUnknownRequestError]: 
Invalid `prisma.pedidos.findMany()` invocation:


Engine is not yet connected.
Backtrace []
    at l (.next/server/app/api/pedidos/pedidos/route.js:1:2448) {
  clientVersion: '6.11.1'
}
Stack trace: PrismaClientUnknownRequestError: 
Invalid `prisma.pedidos.findMany()` invocation:


Engine is not yet connected.
Backtrace []
    at Xn.handleRequestError (/var/www/Pre-Roteiro/PreRoteiro/node_modules/@prisma/client/runtime/library.js:121:7649)
    at Xn.handleAndLogRequestError (/var/www/Pre-Roteiro/PreRoteiro/node_modules/@prisma/client/runtime/library.js:121:6784)
    at Xn.request (/var/www/Pre-Roteiro/PreRoteiro/node_modules/@prisma/client/runtime/library.js:121:6491)
    at l (/var/www/Pre-Roteiro/PreRoteiro/node_modules/@prisma/client/runtime/library.js:130:9812)
    at async Promise.all (index 0)
    at l (/var/www/Pre-Roteiro/PreRoteiro/.next/server/app/api/pedidos/pedidos/route.js:1:2448)
    at tf.do (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/dist/compiled/next-server/webpack:/next/dist/src/server/route-modules/app-route/module.ts:568:15)
    at tf.handle (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/dist/compiled/next-server/webpack:/next/dist/src/server/route-modules/app-route/module.ts:695:31)
    at doRender (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:2603:30)
    at NextNodeServer.renderToResponseWithComponentsImpl (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:3159:24)
    at NextNodeServer.renderPageComponent (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:3747:16)
    at NextNodeServer.renderToResponseImpl (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:3809:24)
    at NextNodeServer.pipeImpl (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:1784:21)
    at NextNodeServer.handleCatchallRenderRequest (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/next-server.ts:1093:7)
    at NextNodeServer.handleRequestImpl (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:1536:9)
    at invokeRender (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/lib/router-server.ts:295:11)
Erro ao associar pedidos: Error [PrismaClientUnknownRequestError]: 
Invalid `prisma.pedidos_perdidos.updateMany()` invocation:


Response from the Engine was empty
    at m (.next/server/app/api/pedidos/pedidos/route.js:1:7001) {
  clientVersion: '6.11.1'
}
Erro ao buscar estatísticas: Error [PrismaClientUnknownRequestError]: 
Invalid `prisma.pedidos.count()` invocation:


Response from the Engine was empty
    at l (.next/server/app/api/pedidos/pedidos/route.js:1:3337) {
  clientVersion: '6.11.1'
}
Erro ao buscar filtros contextuais: Error [PrismaClientUnknownRequestError]: 
Invalid `prisma.pedidos.findMany()` invocation:

**Comment by ikramhasib007** [comment]
> I have the same error, can someone help me?
> 
> ```
> 
> Engine is not yet connected.
> Backtrace []
>     at l (.next/server/app/api/pedidos/pedidos/route.js:1:2448) {
>   clientVersion: '6.11.1'
> }
> Erro ao buscar pedidos: Error [PrismaClientUnknownRequestError]: 
> Invalid `prisma.pedidos.findMany()` invocation:
> 
> 
> Engine is not yet connected.
> Backtrace []
>     at l (.next/server/app/api/pedidos/pedidos/route.js:1:2448) {
>   clientVersion: '6.11.1'
> }
> Stack trace: PrismaClientUnknownRequestError: 
> Invalid `prisma.pedidos.findMany()` invocation:
> 
> 
> Engine is not yet connected.
> Backtrace []
>     at Xn.handleRequestError (/var/www/Pre-Roteiro/PreRoteiro/node_modules/@prisma/client/runtime/library.js:121:7649)
>     at Xn.handleAndLogRequestError (/var/www/Pre-Roteiro/PreRoteiro/node_modules/@prisma/client/runtime/library.js:121:6784)
>     at Xn.request (/var/www/Pre-Roteiro/PreRoteiro/node_modules/@prisma/client/runtime/library.js:121:6491)
>     at l (/var/www/Pre-Roteiro/PreRoteiro/node_modules/@prisma/client/runtime/library.js:130:9812)
>     at async Promise.all (index 0)
>     at l (/var/www/Pre-Roteiro/PreRoteiro/.next/server/app/api/pedidos/pedidos/route.js:1:2448)
>     at tf.do (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/dist/compiled/next-server/webpack:/next/dist/src/server/route-modules/app-route/module.ts:568:15)
>     at tf.handle (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/dist/compiled/next-server/webpack:/next/dist/src/server/route-modules/app-route/module.ts:695:31)
>     at doRender (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:2603:30)
>     at NextNodeServer.renderToResponseWithComponentsImpl (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:3159:24)
>     at NextNodeServer.renderPageComponent (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:3747:16)
>     at NextNodeServer.renderToResponseImpl (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:3809:24)
>     at NextNodeServer.pipeImpl (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:1784:21)
>     at NextNodeServer.handleCatchallRenderRequest (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/next-server.ts:1093:7)
>     at NextNodeServer.handleRequestImpl (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/base-server.ts:1536:9)
>     at invokeRender (/var/www/Pre-Roteiro/PreRoteiro/node_modules/next/src/server/lib/router-server.ts:295:11)
> Erro ao associar pedidos: Error [PrismaClientUnknownRequestError]: 
> Invalid `prisma.pedidos_perdidos.updateMany()` invocation:
> 
> 
> Response from the Engine was empty
>     at m (.next/server/app/api/pedidos/pedidos/route.js:1:7001) {
>   clientVersion: '6.11.1'
> }
> Erro ao buscar estatísticas: Error [PrismaClientUnknownRequestError]: 
> Invalid `prisma.pedidos.count()` invocation:
> 
> 
> Response from the Engine was empty
>     at l (.next/server/app/api/pedidos/pedidos/route.js:1:3337) {
>   clientVersion: '6.11.1'
> }
> Erro ao buscar filtros contextuais: Error [PrismaClientUnknownRequestError]: 
> Invalid `prisma.pedidos.findMany()` invocation:
> ```

Same here: `"prisma": "^6.19.0"`

**Comment by glimmbo** [comment]
Encountered by having import statements that were not awaited, so one file of my seed was not finished before the next one errored (because the first one didn't finish). But the error was sometimes `Engine not yet connected` other `prisma` versions I tried was `Response from Engine was empty.` I adjusted the import order of seed scripts and awaited everything properly and no more errors.
