### ISSUE TITLE
Context propagation for query logging

### ISSUE THREAD

**Issue by tak1n** [prisma/prisma#7596]
## Problem

Currently query logs can not relate to requests or a parent context from which they were invoked from. This means solutions like https://github.com/iamolegga/nestjs-pino or as well datadog tracing https://github.com/DataDog/dd-trace-js/issues/1244 are not able to work properly.

## Suggested solution

Context propagation into query logging should work properly. Sadly I'm quite new to nodejs and therefore aren't able to further specify how this should happen. Also not sure if the architecture of prisma is a blocker here (separate query engine process, and whether this gets simpler once n-api is used)

## Alternatives

I've looked at https://github.com/Jeff-Lewis/cls-hooked (which nestjs-pino uses under the hood) so not a real alternative, but tried to understand whats happening here.

## Additional context

Slack convo: https://prisma.slack.com/archives/CA491RJH0/p1623345269439900

**Comment by Sytten** [comment]
Duplicate of https://github.com/prisma/prisma/issues/6882

**Comment by janpio** [comment]
If you ignore the middleware aspect of this that you assumed @Sytten, this is essentially about e.g. creating a query id (or request id) and logging that with each query, so any external tooling can pick those out of the logs and correlate Prisma Client query to logged SQL query.

**Comment by tak1n** [comment]
Possibly also duplicate of #6519 and #5956

Would assume it shouldn't really depend on which tracing solution is used, but the end result should be queries being traced which are as well correlated to the trigger on prisma client side (and furthermore the root of the prisma client call -> API Request, Background Job, etc).

**Comment by lake2** [comment]
same issue + 1 
any solution?

**Comment by moshcohen110** [comment]
Hi, having the same issue.
Is there any plan to create something like this?

**Comment by tak1n** [comment]
> Hi, having the same issue.
Is there any plan to create something like this?

Its already on the roadmap of prisma https://www.notion.so/Support-Tracing-in-Prisma-Client-c0afd7599022435da2b8fc05c30cd1c0

**Comment by joshribakoff-sm** [comment]
@tak1n this doesn't require tracing support in Prisma, per se. The issue is that since Prisma queries are sent to a rust engine, all of the context from the `dd-trace` library added with https://nodejs.org/api/async_hooks.html#async-hooks is lost in the `$on()` callback.

**Comment by joshribakoff-sm** [comment]
As I suspected, you can already trace today in Prisma:

```ts

prisma.$use(async (params, next) => {
  return await tracer.trace('prisma.query', async () => {
    // not logging params.args, which may contain personally identifying or confidential information
    logger.debug('Prisma query', {
      model: params.model,
      action: params.action,
      runInTransaction: params.runInTransaction,
    });
    const result = await next(params);
    return result;
  });
});
```

Tracing is entirely supported today, and the best way is w/ [Prisma middlware](https://www.prisma.io/docs/concepts/components/prisma-client/middleware), although you don't get raw SQL but that is tangential to tracing and a query can be replicated locally to debug the SQL if needed.

**Comment by joshribakoff-sm** [comment]
I tried this approach:


```ts
prisma.$use(async (params, next) => {
  return await tracer.trace('prisma.query', async (span) => {
    span?.setTag('model', params.model);
    span?.setTag('action', params.action);
    span?.setTag('runInTransaction', params.runInTransaction);
    logger.debug('Prisma query', {
      model: params.model,
      action: params.action,
      runInTransaction: params.runInTransaction,
    });
    const result = await next(params);
    return result;
  });
});

```

The spans are also taken out of context of the parent span from where I sent my Prisma query.

```ts
  try {
    throw new Error();
  } catch (e) {
    console.log(e);
  }
```

the above debug logging shows the stack trace lost the context that I called my prisma query from a particular GQL resolver / file:

```
Error: 
    at /Users/jribakoff/groundwater/dist/apps/api/webpack:/groundwater/apps/api/src/app/db.ts:16:11
    at consumer (/Users/jribakoff/groundwater/node_modules/@prisma/client/runtime/index.js:49914:20)
    at /Users/jribakoff/groundwater/node_modules/@prisma/client/runtime/index.js:49920:76
    at runInChildSpan (/Users/jribakoff/groundwater/node_modules/@prisma/client/runtime/index.js:49133:12)
    at /Users/jribakoff/groundwater/node_modules/@prisma/client/runtime/index.js:49920:20
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at PrismaClient._request (/Users/jribakoff/groundwater/node_modules/@prisma/client/runtime/index.js:49919:86)
    at /Users/jribakoff/groundwater/node_modules/@prisma/client/runtime/index.js:46474:25
    at _callback (/Users/jribakoff/groundwater/node_modules/@prisma/client/runtime/index.js:46233:52)
    at Proxy.then (/Users/jribakoff/groundwater/node_modules/@prisma/client/runtime/index.js:46240:14)
```

In my opinion the proposal from @matthewmueller  in https://github.com/prisma/prisma/issues/6882#issuecomment-1175427037 doesn't have anything to do with solving this issue. I do not want to manually get the parent span and pass it into every Prisma query. I just want the middleware to run from within the context where I called my Prisma query.

**Comment by janpio** [comment]
> or production ready (errors will never be surfaced or logged).

Can you please make sure an issue with more information for this exists? Thanks.

**Comment by mziwisky** [comment]
i've discovered that if you [use the binary query engine](https://www.prisma.io/docs/concepts/components/prisma-engines/query-engine#configuring-the-query-engine) instead of the default Node-API based one, then the async context is _not_ lost in the `client.$on('query', handler)` handler.  i don't know why this is, have been reading the [LibraryEngine](https://github.com/prisma/prisma/blob/main/packages/engine-core/src/library/LibraryEngine.ts) and [BinaryEngine](https://github.com/prisma/prisma/blob/main/packages/engine-core/src/binary/BinaryEngine.ts) code to try to find a difference that might matter, but so far haven't figured it out.

it would be nice if the docs would talk a little more about the differences between those engines.  the only thing it really says is "The Node-API library approach is recommended since it reduces the communication overhead between the Prisma Client and the query engine."  but that makes me wonder why the binary engine is even an option at this point?

**Comment by janpio** [comment]
> but that makes me wonder why the binary engine is even an option at this point?

Because sometimes the Node-API library gets something wrong, that works fine with the binary engine. Then it is a temporary workaround to use the binary engine. It is not recommended to use in other cases, and might be removed at any time.

**Comment by mziwisky** [comment]
@janpio would you consider this loss of async context an instance of the Node-API library getting something wrong?  if so, can it be fixed?  or is there some fundamental limitation with the Node-API approach that will never allow this to work?  i still don't really understand why the query event handler gets invoked in a different async context than that which initiated the prisma query (especially since it's only the case with the Node-API engine but _not_ with the binary engine)

**Comment by janpio** [comment]
Right now we do not give any expectation that the async context would be kept - it is not part of our documented API -, which is why this feature request exists and tracks this expectation (or other solutions to achieve the same outcome). So right now this seems to be undefined to me. If you really need it, you can use the binary to work around that - but be aware that you are off the really recommended path then and might have other negative (or positive) effects that are not documented.

**Comment by EladIsraeli** [comment]
> Right now we do not give any expectation that the async context would be kept - it is not part of our documented API -, which is why this feature request exists and tracks this expectation (or other solutions to achieve the same outcome). So right now this seems to be undefined to me. If you really need it, you can use the binary to work around that - but be aware that you are off the really recommended path then and might have other negative (or positive) effects that are not documented.


I tried to use the binary to work around that but it does not really work.
I use NestJS-CLS package, for saving information on the async context, but when I try to access it on query event.

```
    this.$on<any>('query', async (e) => {
      this.logger.debug({query: e.query, params: e.params});
      const info = this.clsService.get("info")
    });
```

The clsService return undefined.

My prisma engine was loaded with binary

✔ Generated Prisma Client (4.15.0 | binary) to ./node_modules/@prisma/client in 553ms

any idea?

**Comment by EladIsraeli** [comment]
Hi @janpio, I really want to contribute to that. I commented above and the solution you suggested has not worked, how can I contribute to the project, or have a solution for that

**Comment by EladIsraeli** [comment]
> @janpio would you consider this loss of async context an instance of the Node-API library getting something wrong? if so, can it be fixed? or is there some fundamental limitation with the Node-API approach that will never allow this to work? i still don't really understand why the query event handler gets invoked in a different async context than that which initiated the prisma query (especially since it's only the case with the Node-API engine but _not_ with the binary engine)

Have you managed to make it work?

**Comment by mziwisky** [comment]
> Have you managed to make it work?

@EladIsraeli sorry i missed your question until now.  i've been away from this problem for long enough now that i don't recall the details, but i recall a few things that might help you here if you're still stuck and still wanting to work around it with the binary engine.

i was using the `cls-hooked` library, and it includes [a `bindEmitter` function](https://www.npmjs.com/package/cls-hooked#namespacebindemitteremitter) that i know i experimented with, but don't recall whether it was necessary to make my workaround work.  but i believe that function exists because EventEmitter handlers don't get fired with the proper async context by default, so that function somehow propagates the context to them.  if NestJS-CLS has some similar kind of helper, you might need to apply it to your prisma client.

**Comment by exAspArk** [comment]
> The issue is that since Prisma queries are sent to a rust engine, all of the context ... added with https://nodejs.org/api/async_hooks.html#async-hooks is lost

This is a perfect summary by @joshribakoff-sm.

In short

* The Prisma engine written in Rust loses access to the Node.js context from which a query was triggered, so these Prisma features can't help solve this problem:
  * `$on()`
  * `$use()` middlewares
  *  `$extends()` extentensions
* As a result, a request-specific context can't be shared when a database query is being executed. It doesn't work with 
  * Native Node.js `AsyncLocalStorage`
  * `cls-hooked`
  * `continuation-local-storage`
  * and similar request-specific storage libraries that return `undefined`

One workaround I found is using the Prisma preview feature that allows the use of native Node.js database driver adapters to perform queries instead of the Prisma engine. Because these database adapters are executed in Node.js, `async_hooks` should just work fine.

You can find an example using https://github.com/brianc/node-postgres in [`@bemi-db/prisma`](https://github.com/BemiHQ/prisma) that allows tracking all database changes and stitching them with request-specific context (user ID, API endpoint, etc.)

**Comment by rpaterson** [comment]
A useful workaround that helped me was to log the Prisma operation instead of the SQL using "query $allOperations":

**Comment by deanbiltup** [comment]
thanks @wmadden ,   here is a possible solution based on my reading all the above info ^^^

others, I filed https://github.com/prisma/prisma/issues/25984 which I guess is a duplicate of this but contains some critically useful info. 

**The reason tracing info is hard to find is it is a bit of devops magic (java , scala too to be honest) but extremely useful.**

I assume **all tracing solutions in nodejs are using AsyncLocalStorage** which is that magic to avoid passing 2-15 paramaters in the request context around(read my ticket above for more detailed info).  Use of AsyncLocalStorage is generally found in those tracing libraries somewhere as they can't do this magic without it (AFAIK there is not another trick outside AsyncLocalStorage just like in scala, you need Local.scala).  This is how you set context that can be retrieved through a library.  If you support AsynLocalStorage, I would assume then that all the tracing solutions would work if tied into prisma correctly with minimal changes to prisma.   

thinking out loud for an idea here -> 
Let us give you the asyncLocalStorage instance to prisma and then use that instance to convert to map of <string, string> to pass to rust.  On the outside, when calling $on, perhaps resetup a new asyncLocalStorage().run() with a bunch of <string, string> re-setting up the original context such that the logger would have read all the same context info.

FYI, in old school java, the trick was ThreadLocal but in newer java versions, XCompletableFuture.java (from a special project) with Context.java is needed.   They missed passing this context in CompletableFuture (a very bad miss for devops requirements).

**Comment by dsldsl** [comment]
FYI to those following this thread, it was listed to the March/April/May roadmap targets 🚀

**Comment by deanbiltup** [comment]
It is june, any status?  any problem with using something like my proposed solution txfring context through rust?   (a simply map of string/string stuck back in asyncLocalStorage is all I need.  my logger reads it, my filters at the top set it up but rust wiped it so I cannot see which SQL queries go with which http requests since there is no traceId as it was lost across rust.
