### ISSUE TITLE
Error: [libs/sql-schema-describer/src/lib.rs:162:32] Column ID not found in Table DATABASECHANGELOGLOCK 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#7599]
Command: `prisma introspect`
Version: `2.23.0`
Binary Version: `adf5e8cba3daf12d456d911d72b6e9418681b28b`
Report: https://prisma-errors.netlify.app/report/13328 
OS: `x64 darwin 20.3.0`

JS Stacktrace:
```
Error: [libs/sql-schema-describer/src/lib.rs:162:32] Column ID not found in Table DATABASECHANGELOGLOCK
    at ChildProcess.<anonymous> (/<...>/node_modules/prisma/build/index.js:39885:28)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_handler::{{closure}}
   6: std::sys_common::backtrace::__rust_end_short_backtrace
   7: _rust_begin_unwind
   8: std::panicking::begin_panic_fmt
   9: sql_schema_describer::Table::column_bang::{{closure}}
  10: sql_schema_describer::Table::column_bang
  11: sql_introspection_connector::version_checker::VersionChecker::has_p1_compatible_primary_key_column
  12: sql_introspection_connector::introspection::introspect
  13: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  17: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  18: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  19: introspection_engine::main::{{closure}}
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: introspection_engine::main
  22: std::sys_common::backtrace::__rust_begin_short_backtrace
  23: std::rt::lang_start::{{closure}}
  24: std::rt::lang_start_internal
  25: std::rt::lang_start

```

**Comment by janpio** [comment]
Possible duplication: https://github.com/prisma/prisma/issues/9791

**Comment by tomhoule** [comment]
This code path is almost certainly gone by now. Let's close.
