### ISSUE TITLE
Error: [libs/datamodel/connectors/dml/src/model.rs:161:64] Could not find relation field Trade_OrderToTrade on model Order. 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#7600]
Command: `prisma introspect`
Version: `2.23.0`
Binary Version: `adf5e8cba3daf12d456d911d72b6e9418681b28b`
Report: https://prisma-errors.netlify.app/report/13330 
OS: `x64 darwin 20.4.0`

JS Stacktrace:
```
Error: [libs/datamodel/connectors/dml/src/model.rs:161:64] Could not find relation field Trade_OrderToTrade on model Order.
    at ChildProcess.<anonymous> (/<....>/core/node_modules/prisma/build/index.js:39885:28)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: user_facing_errors::Error::new_in_panic_hook
   3: user_facing_errors::panic_hook::set_panic_hook::{{closure}}
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_handler::{{closure}}
   6: std::sys_common::backtrace::__rust_end_short_backtrace
   7: _rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::option::expect_failed
  10: dml::model::Model::find_relation_field_mut
  11: sql_introspection_connector::re_introspection::enrich
  12: sql_introspection_connector::calculate_datamodel::calculate_datamodel
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  16: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  17: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
  18: introspection_engine::main::{{closure}}
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: introspection_engine::main
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal
  24: std::rt::lang_start

```

**Comment by tomhoule** [comment]
Probably the same: https://prisma-errors.netlify.app/report/13337

**Comment by tomhoule** [comment]
New example: https://prisma-errors.netlify.app/report/13520
