### ISSUE TITLE
Unexpected UnhandledPromiseRejectionWarning with Node-API library on Node 12.2.0 on Ubuntu

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7621]
Only present in 12.2.0 with Node-API library enabled (afaik, double check!)

```
$ ts-node ./script.ts
(node:1874) UnhandledPromiseRejectionWarning: Error: 
    at /home/runner/work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:22747:77
    at new Promise (<anonymous>)
    at NAPIEngine.start (/home/runner/work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:22744:31)
    at NAPIEngine.request (/home/runner/work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:22815:9)
    at cb (/home/runner/work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:33760:26)
(node:1874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1874) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

via https://github.com/prisma/e2e-tests/runs/2804081663?check_suite_focus=true

**Comment by janpio** [comment]
related: https://github.com/prisma/e2e-tests/issues/1750

**Comment by williamluke4** [comment]
I've just had a quick look at this. It seems that this is a node-api issue. Versions Nodejs v12.0.0 -> 12.5.0 will throw this error but it works from v12.6.0 onwards. Below is a small reproduction 
```js
const  fs = require("fs");
const QE = require("/home/will/Prisma/scratch-pad/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node");

const datamodel = fs.readFileSync("./prisma/schema.prisma", {
  encoding: "utf8",
});
const engine = new QE.QueryEngine(
  {
    datamodel: datamodel,
    env: process.env,
    logQueries: false,
    ignoreEnvVarErrors: false,
    datasourceOverrides: {},
    logLevel: "error",
    configDir: "/home/will/Prisma/scratch-pad/",
  },
  (e, log4) => {
    console.log(e, log4);
  }
);
async function main(){
  try {
    await engine.connect({ enableRawQueries: true })
  } catch (e) {
    console.error(e)
  }
  
}
main()
```

**Comment by pantharshit00** [comment]
I guess we can bump requirement to 12.6 when we release this to stable.

**Comment by janpio** [comment]
Will be avoided via https://github.com/prisma/prisma/issues/8839
