### ISSUE TITLE
Query engine binary for current platform "linux-musl" could not be found.

### ISSUE THREAD

**Issue by aixasz** [prisma/prisma#7631]
Hello Prisma team, 

I have an issue when run app on docker and got runtime error like this. 

My app env: typescript, nextjs. 

```
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: no next.config.js https://nextjs.org/docs/messages/webpack5
PrismaClientInitializationError2 [PrismaClientInitializationError]: Query engine binary for current platform "linux-musl" could not be found.
This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "/query-engine-linux-musl")

Searched Locations:

  /.prisma/client
  ..\src\generated\client
  /
  /
  /
  /tmp/prisma-engines
  /

You already added the platform "linux-musl" to the "generator" block
in the "schema.prisma" file as described in https://pris.ly/d/client-generator,
but something went wrong. That's suboptimal.

Please create an issue at https://github.com/prisma/prisma/issues/new
    at cb (/app/.next/server/pages/api/generate-code.js:892:539)
    at async Object.GetPlan (/app/.next/server/pages/api/generate-code.js:167:16)
    at async module.exports.YMAs.__webpack_exports__.default (/app/.next/server/pages/api/generate-code.js:464:20)
    at async apiResolver (/app/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async Server.handleApiRequest (/app/node_modules/next/dist/next-server/server/next-server.js:66:462)
    at async Object.fn (/app/node_modules/next/dist/next-server/server/next-server.js:58:580)
    at async Router.execute (/app/node_modules/next/dist/next-server/server/router.js:25:67)
    at async Server.run (/app/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async Server.handleRequest (/app/node_modules/next/dist/next-server/server/next-server.js:32:504) {
  clientVersion: '2.24.1',
  errorCode: undefined
}
```

**Comment by janpio** [comment]
Can you check the file system where the file called `query-engine-linux-musl` would be found?
What is your `prisma -v` output?

**Comment by mytharcher** [comment]
You may have a check of your `schema.prisma` file:

~~~
generator client {
    provider      = "prisma-client-js"
    binaryTargets = ["native", "linux-musl"]
}
~~~

And you could add the `"linux-musl"` to `binaryTargets` field. This step fixes my building for docker image.

**Comment by pantharshit00** [comment]
I am going to close this as its been 2 months now and there is no activity here. 

Please reply if you want us to take another look.

**Comment by malteneuss** [comment]
For those that encounter that "Query engine binary for current platform "linux-musl" could not be found." issue when packaging Prisma within Docker, i've added a solution workaround Gist here:
https://gist.github.com/malteneuss/a7fafae22ea81e778654f72c16fe58d3

**Comment by Casmei** [comment]
> You may have a check of your `schema.prisma` file:
> 
> ```
> generator client {
>     provider      = "prisma-client-js"
>     binaryTargets = ["native", "linux-musl"]
> }
> ```
> 
> And you could add the `"linux-musl"` to `binaryTargets` field. This step fixes my building for docker image.

Thanks, this way my code works again
