### ISSUE TITLE
Prisma cli failing quietly when starting studio under linux 

### ISSUE THREAD

**Issue by midgethoen** [prisma/prisma#7665]
### Bug description

Im using prisma as part of a blitz project. The project runs great under osx however on linx the prisma studio command fails quietly... I've tried troubleshooting using the DEBUG env variable but im not really sure anything usefull is in there an where I should go from here

### How to reproduce

```sh
$ DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test ./node_modules/.bin/prisma studio
Environment variables loaded from .env
Prisma schema loaded from db/schema.prisma
Starting Prisma Studio ...
Generating Prisma Client ... %   
$ echo $?
0    
```                

### Expected behavior

Either the studio should run or it should present an error

### Prisma information

debug info:

<details>
```sh
DEBUG=* DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test ./node_modules/.bin/prisma studio   
  prisma:loadEnv project root found at /home/midgethoen/projects/.../x-blitz/package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from /home/midgethoen/projects/.../x-blitz/.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # This env file should be checked into source control
[dotenv][DEBUG] did not match key and value when parsing line 2: # This is the place for default values that should be used in all environments
[dotenv][DEBUG] did not match key and value when parsing line 3: 
Environment variables loaded from .env
  prisma:engines using NAPI: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from db/schema.prisma
Starting Prisma Studio ...
Generating Prisma Client ...   prisma:loadEnv skipping package.json at /home/midgethoen/projects/.../x-blitz/db/package.json +0ms
  prisma:loadEnv project root found at /home/midgethoen/projects/.../x-blitz/package.json +1ms
  prisma:tryLoadEnv Environment variables loaded from /home/midgethoen/projects/.../x-blitz/.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # This env file should be checked into source control
[dotenv][DEBUG] did not match key and value when parsing line 2: # This is the place for default values that should be used in all environments
[dotenv][DEBUG] did not match key and value when parsing line 3: 
```
</details>

### Environment & setup

- OS: Ubuntu 20.04
- Database: postgresql
- Node.js version: 14.17.0

### Prisma Version

prisma version: 
```sh
$ ./node_modules/.bin/prisma -v
prisma               : 2.20.1
@prisma/client       : 2.20.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by pantharshit00** [comment]
Hello

Just to be sure can you please try this again with the latest version of Prisma which is `2.24.1` at the moment?

**Comment by midgethoen** [comment]
thnx for the response, @pantharshit00 

> Just to be sure can you please try this again with the latest version of Prisma which is `2.24.1` at the moment?

```sh
$ npm i prisma@latest
...
+ prisma@2.24.1
....

$ blitz prisma studio
Prisma schema loaded from db/schema.prisma
Prisma Studio is up on http://localhost:5556
Unable to get DMMF from Prisma Client:  Error: Schema parsing
error: Found argument '--enable-experimental' which wasn't expected, or isn't valid in this context
        Did you mean --enable-playground?

USAGE:
    query-engine-debian-openssl-1.1.x --enable-playground

For more information try --help
    at Object.getDMMF2 [as getDMMF] (/home/midgethoen/projects/capptions/capptions/x-blitz/node_modules/@prisma/client/generator-build/index.js:33169:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getDMMF (/home/midgethoen/projects/capptions/capptions/x-blitz/node_modules/@prisma/client/generator-build/index.js:77086:16)
    at async PCW.getDMMF (/home/midgethoen/projects/capptions/capptions/x-blitz/node_modules/prisma/build/index.js:110429:24)
    at async PrismaService.respond (/home/midgethoen/projects/capptions/capptions/x-blitz/node_modules/prisma/build/index.js:110692:50)
    at async /home/midgethoen/projects/capptions/capptions/x-blitz/node_modules/prisma/build/index.js:110867:35


```

I have an error now!

not really sure yet what is means but that's another story :)

thnx

**Comment by midgethoen** [comment]
for reference on the new bug: https://github.com/prisma/studio/issues/483

Ill close this since it is already fixed in the latest version
