### ISSUE TITLE
PANIC in query-engine/core/src/query_document/parser.rs:250:87called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by phatpham9** [prisma/prisma#7672]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.17.0           | 
| OS              | linux-musl         |
| Prisma Client   | 2.24.1             |
| Query Engine    | query-engine 18095475d5ee64536e2f93995e48ad800737a9e4|
| Database        | undefined|

## Query
```
mutation {
  createOneOrder(data: {
    total: 5e+23
    customer: "X"
    status: CREATED
    createdAt: "X"
  }) {
    id
    customer
    total
    status
    createdAt
    confirmedAt
    deliveredAt
    canceledAt
  }
}
```

## Logs
```
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:client clientVersion: 2.24.1
prisma:engine { cwd: '/app/node_modules/.prisma/client' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '44537' ] }
prisma:engine stdout  Starting a postgresql pool with 7 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:44537
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
prisma:engine Client Version: 2.24.1
prisma:engine Engine Version: query-engine 18095475d5ee64536e2f93995e48ad800737a9e4
prisma:engine Active provider: postgresql
prisma:engine stdout  PANIC in query-engine/core/src/query_document/parser.rs:250:87
called `Option::unwrap()` on a `None` value
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:26097:24)
      at Socket.emit (events.js:388:22)
      at endReadableNT (internal/streams/readable.js:1336:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:44537
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 44537
  }
}
prisma:engine { cwd: '/app/node_modules/.prisma/client' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '40619' ] }
prisma:engine stdout  Starting a postgresql pool with 7 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:40619
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
prisma:engine stdout  PANIC in query-engine/core/src/query_document/parser.rs:250:87
called `Option::unwrap()` on a `None` value
prisma:engine Client Version: 2.24.1
prisma:engine Engine Version: query-engine 18095475d5ee64536e2f93995e48ad800737a9e4
prisma:engine Active provider: postgresql
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:26097:24)
      at Socket.emit (events.js:388:22)
      at endReadableNT (internal/streams/readable.js:1336:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'UND_ERR_SOCKET'
  }
}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
