### ISSUE TITLE
The `ConnectorError` periodically appears (Postgres).

### ISSUE THREAD

**Issue by JackieJoo** [prisma/prisma#7678]
### Bug description

I've got several test suites for the graphql API (built with ApolloServer & Prisma).
The tests basically run some queries against the API endpoint with the apollo client. They are standalone (imitate user queries to the API). API uses a dev database (local Postgres docker container) and a locally running server.

An error occurs periodically, I can run 1 test file a few times and it passes, then this error occurs, after that again the tests pass.

```
console.error src/tests/utils/ErrorLog.ts:7
    Exception: {
      errors: [
        {
          message: '\n' +
            'Invalid `prisma.company.create()` invocation:\n' +
            '\n' +
            '\n' +
            '  Error occurred during query execution:\n' +
            'ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("0A000"), message: "cached plan must not change result type", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("plancache.c"), line: Some(722), routine: Some("RevalidateCachedQuery") }) }) })',
          locations: [],
          path: [Array]
        }
      ],
      stacktrace: [
        'Error: ',
        'Invalid `prisma.company.create()` invocation:',
        '',
        '',
        '  Error occurred during query execution:',
        'ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("0A000"), message: "cached plan must not change result type", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("plancache.c"), line: Some(722), routine: Some("RevalidateCachedQuery") }) }) })',
        '    at new CombinedError (/Users/jackiejo/main/smidyo/smidyo-monorepo/quoting-portal/api/node_modules/apollo-server/node_modules/graphql-tools/src/stitching/errors.ts:90:5)',
        '    at Object.checkResultAndHandleErrors (/Users/jackiejo/main/smidyo/smidyo-monorepo/quoting-portal/api/node_modules/apollo-server/node_modules/graphql-tools/src/stitching/errors.ts:111:11)',
        '    at CheckResultAndHandleErrors.transformResult (/Users/jackiejo/main/smidyo/smidyo-monorepo/quoting-portal/api/node_modules/apollo-server/node_modules/graphql-tools/src/transforms/CheckResultAndHandleErrors.ts:15:12)',
        '    at /Users/jackiejo/main/smidyo/smidyo-monorepo/quoting-portal/api/node_modules/apollo-server/node_modules/graphql-tools/src/transforms/transforms.ts:37:45',
        '    at Array.reduce (<anonymous>)',
        '    at applyResultTransforms (/Users/jackiejo/main/smidyo/smidyo-monorepo/quoting-portal/api/node_modules/apollo-server/node_modules/graphql-tools/src/transforms/transforms.ts:35:21)',
        '    at /Users/jackiejo/main/smidyo/smidyo-monorepo/quoting-portal/api/node_modules/apollo-server/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:104:12',
        '    at step (/Users/jackiejo/main/smidyo/smidyo-monorepo/quoting-portal/api/node_modules/apollo-server/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:32:23)',
        '    at Object.next (/Users/jackiejo/main/smidyo/smidyo-monorepo/quoting-portal/api/node_modules/apollo-server/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:13:53)',
        '    at fulfilled (/Users/jackiejo/main/smidyo/smidyo-monorepo/quoting-portal/api/node_modules/apollo-server/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:4:58)'
      ]
    }
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.15.1

### Prisma Version

```
2.24.1
```

**Comment by janpio** [comment]
Similar case reported in private Slack channel: https://prisma.slack.com/archives/GSH2PPNBF/p1623935918001400

**Comment by pantharshit00** [comment]
I can reproduce this after running the reproduction twice. It doesn't seem to happen if I add `&statment_cache_size=0` to the connection string so looks like a bug in the statement cache implementation. Add this to the connection string as a workaround for now. 

You need to enable mode using `DEBUG=*` to see these error logs. I am marking this as confirmed bug.

**Comment by janpio** [comment]
Is that first error message a follow up error to the query failing or how is this related?

**Comment by pantharshit00** [comment]
I fixed the order. First query fails with `cached plan must not change result type` which in turns fails another query because it received null instead of a valid id.

**Comment by Jackman3005** [comment]
@pantharshit00 OMG thank you for your comment about the `&statement_cache_size=0` workaround!

I've been futsin around with trying to get end-to-end tests working in GitHub Actions for two days and been stuck on this issue and this has solved it for me 🙏

We've also seen this error here and there when we have the API running and do a `yarn prisma migrate reset`. In our CI environment we were getting this error 100% of the time.  I'm not sure what Prisma can do to fix this at runtime, but would love to see it resolved for good!


In the off-chance I can help another poor wondering soul, here's a bit of information on my situation.


# Prisma Migration
We have a table called "FormPrototype" and it has a column that is an enum called "status". We have quite a few prisma generated migration files now and one of them has the following:

Note: this was generated when we removed a status from the enum

```sql
-- AlterEnum
BEGIN;
CREATE TYPE "FormPrototypeStatus_new" AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');
ALTER TABLE "FormPrototype" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "FormPrototype" ALTER COLUMN "status" TYPE "FormPrototypeStatus_new" USING ("status"::text::"FormPrototypeStatus_new");
ALTER TYPE "FormPrototypeStatus" RENAME TO "FormPrototypeStatus_old";
ALTER TYPE "FormPrototypeStatus_new" RENAME TO "FormPrototypeStatus";
DROP TYPE "FormPrototypeStatus_old";
ALTER TABLE "FormPrototype" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
COMMIT;
```

# Postgres Error
I believe that migration code in collaboration with how Postgres does caching is the cause for the following error that I was getting from the postgres container logs in my CI environment:

```text
2022-04-18 07:06:21.482 UTC [1] LOG:  database system is ready to accept connections
 2022-04-18 07:08:56.418 UTC [74] ERROR:  cache lookup failed for type 17062
 2022-04-18 07:08:56.418 UTC [74] STATEMENT:  SELECT "public"."FormPrototype"."id",
"public"."FormPrototype"."name"
FROM "public"."FormPrototype"
WHERE "public"."FormPrototype"."status" = $1
OFFSET $2
```

# Prisma Error
```text
/home/runner/work/our-repo/our-repo/api/node_modules/@prisma/client/runtime/index.js:38707
          throw new PrismaClientUnknownRequestError(message, this.prisma._clientVersion);
                ^
Error: 
Invalid `prisma.formPrototype.findMany()` invocation in
/home/runner/work/our-repo/our-repo/api/src/events/notifications.ts:15:45

  12 console.log("Sending notifications...");
  13 const currentDate = new Date();
  14 
→ 15 const quests = await prisma.formPrototype.findMany(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("XX000"), message: "cache lookup failed for type 17062", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("lsyscache.c"), line: Some(2851), routine: Some("getTypeBinaryInputInfo") }) }) })
    at cb (/home/runner/work/our-repo/our-repo/api/node_modules/@prisma/client/runtime/index.js:38707:17)
    at /home/runner/work/our-repo/our-repo/api/src/context.ts:40:18
    at /home/runner/work/our-repo/our-repo/api/src/context.ts:32:18
    at PrismaClient._request (/home/runner/work/our-repo/our-repo/api/node_modules/@prisma/client/runtime/index.js:40859:18)
    at Object.notificationEventHandler (/home/runner/work/our-repo/our-repo/api/src/events/notifications.ts:15:18)
error Command failed with exit code 1.
```

# End-to-end setup
We are using GitHub Actions and using the services feature specifying a Postgres container. Nothing too special here.

We have a `start` bash script that does the following to prepare and start our API:

```bash
export DATABASE_URL="postgresql://app_test:app_test@localhost:5432/app_test?schema=public"

yarn install --frozen-lockfile
yarn prisma migrate reset --force # no difference when using `migrate dev`
yarn start # ts-node --transpile-only src/index.ts
```

**Comment by Jolg42** [comment]
Can reproduce on the repo https://github.com/JackieJoo/prisma-error-sample with `2.25.0`
```
console.error src/tests/utils/ErrorLog.ts:5
    Exception: {
      clientVersion: '2.25.0',
      stacktrace: [
        'Error: ',
        'Invalid `prisma.user.create()` invocation:',
        '',
        '',
        '  Error occurred during query execution:',
        'ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("XX000"), message: "cache lookup failed for type 19972", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("lsyscache.c"), line: Some(2696), routine: Some("getTypeBinaryInputInfo") }) }) })',
        '    at cb (/Users/j42/Repros/prisma-error-sample/node_modules/@prisma/client/runtime/index.js:33820:17)',
        '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
      ]
    }
....
```

and on `4.3.1` as well
```
console.error src/tests/utils/ErrorLog.ts:5
    Exception: {
      clientVersion: '4.3.1',
      stacktrace: [
        'Error: ',
        'Invalid `ctx.prisma.user.create()` invocation in',
        '/Users/j42/Repros/prisma-error-sample/src/resolvers/user/mutations/index.ts:3:26',
        '',
        '  1 export function createUser (_, args, ctx) {',
        '  2   if(args.data.post)',
        '→ 3   return ctx.prisma.user.create(',
        'Error occurred during query execution:',
        'ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(EXX000), message: "cache lookup failed for type 20310", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("lsyscache.c"), line: Some(2696), routine: Some("getTypeBinaryInputInfo") }) }) })',
        '    at RequestHandler.handleRequestError (/Users/j42/Repros/prisma-error-sample/node_modules/@prisma/client/runtime/index.js:29913:13)',
        '    at RequestHandler.request (/Users/j42/Repros/prisma-error-sample/node_modules/@prisma/client/runtime/index.js:29892:12)',
        '    at PrismaClient._request (/Users/j42/Repros/prisma-error-sample/node_modules/@prisma/client/runtime/index.js:30864:16)'
      ]
    }
```

**Comment by MarcusHSmith** [comment]
Is there any news on this thread?

**Comment by macrozone** [comment]
this happens after reseting the database with `prisma migrate reset` and renders the app broken

**Comment by DimosthenisK** [comment]
What seemed to fix it for me was adding `prismaClient.$disconnect()` in the afterEach hook.

**Comment by tminard** [comment]
This is an issue for us as well. With long running connections it appears the prepared statement cache can be poisoned and/or the cache is not accounting for plan invalidation responses from postgres.

**Comment by janpio** [comment]
Internal occurrence of the error message: https://prisma-company.slack.com/archives/C04FDERNP32/p1683568637783869

**Comment by danil-iglu** [comment]
> What seemed to fix it for me was adding `prismaClient.$disconnect()` in the afterEach hook and reinstating the prismaClient in beforeEach.

@DimosthenisK could you please share the snippet?

**Comment by vladimiremi** [comment]
> Ocorrência interna da mensagem de erro: https://prisma-company.slack.com/archives/C04FDERNP32/p1683568637783869

@DimosthenisK  could you please share the snippet?

**Comment by lperrious** [comment]
Same problem with Prisma 5.0.0.

`statement_cache_size=0` is a workaround.

Already got prismaClient.$disconnect() in the afterEach hook but the problem appeared.

Btw for those asking :
`
beforeEach(() => {
    // Generate the Prisma schema in the DB
    execSync(`${prisma_binary} db push --skip-generate`, {
      env: {
        ...process.env,
        DATABASE_URL: generateDatabaseURL(schema_id),
      },
    });
  });

  afterEach(async () => {
    // Drop the Prisma schema in the DB
    await prisma.$executeRawUnsafe(
      `DROP SCHEMA IF EXISTS "${schema_id}" CASCADE;`,
    );
    await prisma.$disconnect();
  });
`

**Comment by janpio** [comment]
I can confirm this is still happening with the original reproduction with Prisma 5: https://github.com/JackieJoo/prisma-error-sample

(I just needed to use `npm install -force`, then `npm install prisma@latest @prisma/client@latest --force` and `npm install -g nodemon` - and then the documented individual steps. `npm run migrate` now also produces a small, additional migration - but that is not relevant either. Latest at third run of `npm run test` I got a failure.)

Does anyone have an actual theory what is happening here?
It's clear this is reproducible with the example, but _why_ is it happening?

(I'll try to simplify the reproduction to just use Prisma directly now, no Apollo server etc.)

**Comment by janpio** [comment]
My current understanding: 

Our PostgreSQL driver caches the type information about the enums when a connection is opened and put into the connection pool. This makes queries faster. Before and after the test run, @JackieJoo executes `npx prisma migrate reset --force` under the hood, which drops the database/schema and recreates it. As the Prisma Client runs in the GraphQL server application though, the connections stay open - including the previous types cache. The PostgreSQL driver then later references the cached data (`type 19972` etc) in a query - but the referenced was replaced (and just looks the same as before on a fundamental level). And💥 

This StackOverflow question is of a similar setup and problem: https://stackoverflow.com/questions/51086421/npgsql-postgresexception-0x80004005-xx000-cache-lookup-failed-for-type-20785

This also explains why `await prisma.$disconnect()` works - but only for the ones of you where the Prisma Client runs in the same instance as the tests, and not a long running server like in @JackieJoo's case. If you have a separate running app, you would need to `$disconnect()` in there, or restart the app.

I am not sure of what the best solution is in our case. 

The SO question above mentions a method `NpgsqlConnection.ReloadTypes()` in [Npgsql](https://www.npgsql.org/), that would also work for our case - but of course is not the most obvious. We should probably also catch the errors and link to documentation that explains what is going on.

Do you all actually _want_ to reset the database and re-migrate it or are you using it more as a way to ensure the database is empty? Then us offering a proper "truncate" method might actually be a workaround as well. With that the connection can keep using the old types cache.

**Comment by DimosthenisK** [comment]
> Do you all actually _want_ to reset the database and re-migrate it or are you using it more as a way to ensure the database is empty? Then us offering a proper "truncate" method might actually be a workaround as well. With that the connection can keep using the old types cache.

I personally need a complete remigration, as I add static data that wouldn't make sense to be added through seeding (entity permissions with entities that are added during the apps dev cycle)

**Comment by drewcorlin1** [comment]
I'm seeing this same error message when I
* Have an existing model with a `TEXT` column
* Have a node app that queries for that model on that column
  * Service is running, queries work as expected
* Run a migration (via `prisma migrate deploy`) that changes the data type of that column to `CITEXT`
* Queries now fail

**Comment by davidgustys** [comment]
up

**Comment by Alexandre-Pascal** [comment]
I encountered a similar issue when I modified the data type of my columns after creating a table. 
To resolve this problem, I simply cleared the cached plans in PostgreSQL by executing the `DEALLOCATE ALL` command. This action effectively removed all prepared queries from the cache, addressing the issue.

**Comment by voltidev** [comment]
In my case `DISCARD ALL` helped.

**Comment by ThomasBnf** [comment]
I added "&pgbouncer=true" to my DATABASE_URL and DIRECT_URL, then redeployed on Vercel, no more error. I redeployed again without it afterward, and it still worked.

**Comment by wwelder** [comment]
this is so annoying and makes migration a huge pain if you have a few services
