### ISSUE TITLE
`TypeError: mappings.map is not a function`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7743]
```
C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview>npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: 
TypeError: mappings.map is not a function
    at getMappings (C:\Users\Jan\Documents\throwaway\1363\node_modules\@prisma\client\generator-build\index.js:179983:21)
    at Object.externalToInternalDmmf (C:\Users\Jan\Documents\throwaway\1363\node_modules\@prisma\client\generator-build\index.js:179943:19)
    at Object.getPhotonDMMF (C:\Users\Jan\Documents\throwaway\1363\node_modules\@prisma\client\generator-build\index.js:181811:67)
    at buildClient (C:\Users\Jan\Documents\throwaway\1363\node_modules\@prisma\client\generator-build\index.js:172049:32)
    at Object.generateClient (C:\Users\Jan\Documents\throwaway\1363\node_modules\@prisma\client\generator-build\index.js:172129:43)
    at Object.onGenerate (C:\Users\Jan\Documents\throwaway\1363\node_modules\@prisma\client\generator-build\index.js:173638:33)
    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\1363\node_modules\@prisma\client\generator-build\index.js:157919:46)
    at Generator.next (<anonymous>)
    at C:\Users\Jan\Documents\throwaway\1363\node_modules\@prisma\client\generator-build\index.js:157906:71
    at new Promise (<anonymous>)
```

Schema:

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider          = "mysql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW")
}

generator client {
  provider = "prisma-client-js"
}

model foo {
  id  Int    @id
  bar String
}

// The following model is created manually so that the Prisma Migrations table is visible
model PrismaMigrations {
    id                  String    @id @db.VarChar(36)
    checksum            String    @db.VarChar(64)
    finished_at         DateTime?
    migration_name      String    @db.VarChar(255)
    logs                String?
    rolled_back_at      DateTime? 
    started_at          DateTime  @default(now())
    applied_steps_count Int       @default(0)

    @@map("_prisma_migrations")
}
```

`package.json` (as the client is not installed yet):
```
{
  "name": "planetscaleMigrationPreview",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "prisma": "^2.25.0"
  }
}

```

**Comment by janpio** [comment]
Does not happen after nuking `node_modules` and `npm install` 🤷

**Comment by pantharshit00** [comment]
I am also unable to reproduce this. Maybe you installed an older version of the client at first accidentally?

**Comment by janpio** [comment]
I would love to have a better reproduction, as this is one of those scary cases where everything just implodes. But as I do not, let's close this and see if someone pops up again via the error message.
