### ISSUE TITLE
"Value out of range for the type. The column `rolled_back_at` contained an invalid datetime value with either day or month set to zero." during `migrate dev`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7747]
I have a database with a table that contains a datetime field with a "datetime value with either day or month set to zero", `0000-00-00 00:00:00.000`, in the Migration table:

```
INSERT INTO `_prisma_migrations` (`id`, `checksum`, `finished_at`, `migration_name`, `logs`, `rolled_back_at`, `started_at`, `applied_steps_count`) VALUES
	('2bb8e0f9-a639-4dc3-90c5-864f26b93ac5', '9f2d7c8f4dad668fe86a7ac0861b523c438f1359dd3b50a098e8506269c5d482', '2021-06-18 10:18:32.343', '20210618101625_init', '', '0000-00-00 00:00:00.000', '2021-06-18 10:18:31.723', 1);
```

When trying to migrate that database, I get this error:

```
C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview>npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": MySQL database "migratetest" at "127.0.0.1:56875"

Error: P2020

Value out of range for the type. The column `rolled_back_at` contained an invalid datetime value with either day or month set to zero.
```

Or with DEBUG=*:

```
C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview>set DEBUG=*

C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview>npx prisma migrate dev
  prisma:loadEnv project root found at C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview\.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # Environment variables declared in this file are automatically made available to Prisma.
[dotenv][DEBUG] did not match key and value when parsing line 2: # See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables
[dotenv][DEBUG] did not match key and value when parsing line 3:
[dotenv][DEBUG] did not match key and value when parsing line 4: # Prisma supports the native connection string format for PostgreSQL, MySQL, SQL Server and SQLite.
[dotenv][DEBUG] did not match key and value when parsing line 5: # See the documentation for all the connection string options: https://pris.ly/d/connection-strings
[dotenv][DEBUG] did not match key and value when parsing line 6:
[dotenv][DEBUG] did not match key and value when parsing line 7: # main = 56093
[dotenv][DEBUG] did not match key and value when parsing line 8: # migrate = 56875
[dotenv][DEBUG] did not match key and value when parsing line 10:
Environment variables loaded from .env
  prisma:engines using NAPI: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +1ms
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview\node_modules\@prisma\engines\query-engine-windows.exe +0ms
Datasource "db": MySQL database "migratetest" at "127.0.0.1:56875"

  prisma:getDMMF Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview\node_modules\@prisma\engines\query-engine-windows.exe +0ms
  prisma:getConfig Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview\node_modules\@prisma\engines\query-engine-windows.exe +971ms
  prisma:getConfig Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview\node_modules\@prisma\engines\query-engine-windows.exe +463ms
  prisma:migrateEngine:rpc starting migration engine with binary: C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview\node_modules\@prisma\engines\migration-engine-windows.exe +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"devDiagnostic","params":{"migrationsDirectoryPath":"C:\\Users\\Jan\\Documents\\throwaway\\planetscaleMigrationPreview\\prisma\\migrations"}} +5ms
  prisma:migrateEngine:stderr Jun 18 13:44:32.813  INFO migration_engine: Starting migration engine RPC server git_hash="c838e79f39885bc8e1611849b1eb28b5bb5bc922" +0ms
  prisma:migrateEngine:stderr Jun 18 13:44:33.480  INFO quaint::single: Starting a mysql connection. +666ms
  prisma:migrateEngine:rpc {
  prisma:migrateEngine:rpc   jsonrpc: '2.0',
  prisma:migrateEngine:rpc   error: {
  prisma:migrateEngine:rpc     code: 4466,
  prisma:migrateEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:migrateEngine:rpc     data: {
  prisma:migrateEngine:rpc       is_panic: false,
  prisma:migrateEngine:rpc       message: 'Value out of range for the type. The column `rolled_back_at` contained an invalid datetime value with either day or month set to zero.',
  prisma:migrateEngine:rpc       meta: [Object],
  prisma:migrateEngine:rpc       error_code: 'P2020'
  prisma:migrateEngine:rpc     }
  prisma:migrateEngine:rpc   },
  prisma:migrateEngine:rpc   id: 1
  prisma:migrateEngine:rpc } +2s
Error: Error: P2020

Value out of range for the type. The column `rolled_back_at` contained an invalid datetime value with either day or month set to zero.

    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview\node_modules\prisma\build\index.js:56094:26)
    at MigrateEngine.handleResponse (C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview\node_modules\prisma\build\index.js:55969:38)
    at LineStream.<anonymous> (C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview\node_modules\prisma\build\index.js:56054:18)
    at LineStream.emit (events.js:315:20)
    at LineStream.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at LineStream.Readable.push (internal/streams/readable.js:223:10)
    at LineStream.Transform.push (internal/streams/transform.js:166:32)
    at LineStream._pushBuffer (C:\Users\Jan\Documents\throwaway\planetscaleMigrationPreview\node_modules\prisma\build\index.js:55844:19)
``` 

Is there a way around this? Is this only because the migration table contains an unexpected value?

**Comment by janpio** [comment]
Replacing the `0000-00-00 00:00:00.000` value with `NULL` made the problem go away.

**Comment by pantharshit00** [comment]
I wasn't able to reproduce this as I can't insert `0000-00-00 00:00:00.00` in the table. 

![image](https://user-images.githubusercontent.com/22195362/122688123-15c27880-d238-11eb-81bd-2712bb1385e4.png)


Is this problem specific to planetscale/vitess?

**Comment by janpio** [comment]
Indeed, it was Planetscale currently produces in their preview for a specific feature they are building with us. They somehow seem to reproduce this when copying data from one database to another.

In the end probably just a sepcific version of https://github.com/prisma/prisma/issues/5006 - that Prisma does not support zero dates.

**Comment by tomhoule** [comment]
Yep that's my understanding of the problem: zero dates are considered a legacy feature in the MySQL docs, and we error hard when we encounter them in quaint, so that applies to all the engines. We could conceivably handle this in the migration engine, but I think it's easier for PlanetScale to fix the code replacing NULLs with zero dates.

**Comment by tomhoule** [comment]
PlanetScale is working on this.

**Comment by janpio** [comment]
The problem is fixed on side of Planetscale.

When Prisma encounters the value, the error message is still the same though. Could we catch this and output something more helpful with a link to https://github.com/prisma/prisma/issues/5006 (probably via pris.ly) instead?

**Comment by janpio** [comment]
Created the issue: https://github.com/prisma/prisma/issues/8060

**Comment by tomhoule** [comment]
Note that the "value out of range" message is already something we are catching and giving a nicer error message for than what the database gives us, so it would be a matter of adjusting it.
