### ISSUE TITLE
PANIC in query-engine/core/src/query_graph_builder/read/utils.rs:52:85called `Result::unwrap()` on an `Err` value: FieldNotFound { name: "_count", model: "Issue" }

### ISSUE THREAD

**Issue by Argeento** [prisma/prisma#7750]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.24.1             |
| Query Engine    | query-engine 18095475d5ee64536e2f93995e48ad800737a9e4|
| Database        | undefined|

## Query
```
query {
  findFirstProject(where: {
    id: 5
  }) {
    id
    name
    description
    createdAt
    updatedAt
    users {
      id
      firstName
      lastName
    }
    issues {
      _count {
        comments
      }
    }
  }
}
```

## Logs
```
mprisma:engine stdout  Started http server on http://127.0.0.1:36089  
  prisma:engine Search for Query Engine in /home/adrian/work/sparing-support-api/node_modules/.prisma/client  
  prisma:engine { cwd: '/home/adrian/work/sparing-support-api/prisma' }  
  prisma:engine Search for Query Engine in /home/adrian/work/sparing-support-api/node_modules/.prisma/client  
  plusX Execution permissions of /home/adrian/work/sparing-support-api/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/adrian/work/sparing-support-api/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '34135' ] }  
  prisma:engine Client Version: 2.24.1  
  prisma:engine Engine Version: query-engine 18095475d5ee64536e2f93995e48ad800737a9e4  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:34135  
  prisma:engine Search for Query Engine in /home/adrian/work/sparing-support-api/node_modules/.prisma/client  
  plusX Execution permissions of /home/adrian/work/sparing-support-api/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine Client Version: 2.24.1  
  prisma:engine Engine Version: query-engine 18095475d5ee64536e2f93995e48ad800737a9e4  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in query-engine/core/src/query_graph_builder/read/utils.rs:52:85
called `Result::unwrap()` on an `Err` value: FieldNotFound { name: "_count", model: "Issue" }  +3s
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/home/adrian/work/sparing-support-api/node_modules/@prisma/client/runtime/index.js:26097:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:45511
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -111,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 45511
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/home/adrian/work/sparing-support-api/prisma' }  
  prisma:engine Search for Query Engine in /home/adrian/work/sparing-support-api/node_modules/.prisma/client  
  plusX Execution permissions of /home/adrian/work/sparing-support-api/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +3s
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '45139' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:45139  
  prisma:engine Search for Query Engine in /home/adrian/work/sparing-support-api/node_modules/.prisma/client  
  plusX Execution permissions of /home/adrian/work/sparing-support-api/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine stdout  PANIC in query-engine/core/src/query_graph_builder/read/utils.rs:52:85
called `Result::unwrap()` on an `Err` value: FieldNotFound { name: "_count", model: "Issue" }  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/home/adrian/work/sparing-support-api/node_modules/@prisma/client/runtime/index.js:26097:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
const project = await this.prisma.project.findFirst({
  where: {
    id: projectId
  },
  include: {
    users: {
      select: userDtoSelect
    },
    issues: {
      select: {
        _count: {
          select: {
            comments: true,
          },
        },
      },
    },
  },
});
```

## Schema
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["selectRelationCount"]
}

model User {
  id        Int     @id @default(autoincrement())
  jiraId    String? @unique
  email     String  @unique
  hash      String
  firstName String
  lastName  String

  roles    Role[]
  projects Project[]
  comments Comment[]
  issues   Issue[]
}

model Session {
  id     Int    @id @default(autoincrement())
  token  String @unique
  userId Int
}

model Role {
  id     Int    @id @default(autoincrement())
  userId Int
  name   String

  user User @relation(fields: [userId], references: [id])

  @@unique([name, userId])
}

model Project {
  id          Int      @id @default(autoincrement())
  name        String
  description String?
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  issues Issue[]
  users  User[]
}

model Issue {
  id          Int      @id @default(autoincrement())
  jiraKey     String   @unique
  jiraId      Int      @unique
  projectId   Int?
  authorId    Int?
  summary     String
  description String?
  status      String
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt

  project  Project?  @relation(fields: [projectId], references: [id])
  author   User?     @relation(fields: [authorId], references: [id])
  comments Comment[]
}

model Comment {
  id        Int      @id @default(autoincrement())
  jiraId    Int      @unique
  authorId  Int?
  issueId   Int
  content   String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  author User? @relation(fields: [authorId], references: [id])
  issue  Issue @relation(fields: [issueId], references: [id])
}
```

**Comment by pantharshit00** [comment]
This was fixed in 2.25 https://github.com/prisma/prisma-engines/pull/1980
