### ISSUE TITLE
prisma/prisma-client 2.20 and up does not build correctly on vercel

### ISSUE THREAD

**Issue by PookMook** [prisma/prisma#7776]
### Bug description

I created this repo yesterday: https://github.com/PookMook/starting-blocks (you can check the commits the see the history)
initially using latest prisma/prisma-client (2.25 at the time of writing) and noticed an error on the function call logs, ended up going in for a little bit of exploration and pulled another project using 2.18 that was working fine. For sanity checking I downgraded and everything seemed fine.

So I went into a bit of incremental downgrades and it seems anything from 2.20 and up isn't working at all with an error that looks like this one :

```
[GET] /api/graphql
11:34:12:12
Status:-1
Duration:795.34 ms
Init Duration: N/A
Memory Used:48 MB
ID:nqpxx-1624203252117-d3029b70b5d9
User Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
s/@prisma/client'\n" +    'Require stack:\n' +    '- /var/task/node_modules/nexus-prisma/dist/helpers/prisma.js\n' +    '- /var/task/node_modules/nexus-prisma/dist/runtime/index.js\n' +    '- /var/task/node_modules/nexus-prisma/dist/index.js\n' +    '- /var/task/.next/server/pages/api/graphql.js\n' +    '- /var/task/node_modules/next/dist/next-server/server/next-server.js\n' +    '- /var/task/___next_launcher.js\n' +    '- /var/runtime/UserFunction.js\n' +    '- /var/runtime/index.js\n' +    '    at getPrismaClientDmmf (/var/task/node_modules/nexus-prisma/dist/helpers/prisma.js:21:28)\n' +    '    at Object.<anonymous> (/var/task/node_modules/nexus-prisma/dist/runtime/index.js:14:14)\n' +    '    at Module._compile (internal/modules/cjs/loader.js:1068:30)\n' +    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n' +    '    at Module.load (internal/modules/cjs/loader.js:933:32)\n' +    '    at Function.Module._load (internal/modules/cjs/loader.js:774:14)\n' +    '    at Module.require (internal/modules/cjs/loader.js:957:19)\n' +    '    at require (internal/modules/cjs/helpers.js:88:18)\n' +    '\n' +    "Error: Cannot find module '/vercel/path0/node_modules/@prisma/client'\n" +    'Require stack:\n' +    '- /var/task/node_modules/nexus-prisma/dist/helpers/prisma.js\n' +    '- /var/task/node_modules/nexus-prisma/dist/runtime/index.js\n' +    '- /var/task/node_modules/nexus-prisma/dist/index.js\n' +    '- /var/task/.next/server/pages/api/graphql.js\n' +    '- /var/task/node_modules/next/dist/next-server/server/next-server.js\n' +    '- /var/task/___next_launcher.js\n' +    '- /var/runtime/UserFunction.js\n' +    '- /var/runtime/index.js\n' +    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)\n' +    '    at Function.Module._load (internal/modules/cjs/loader.js:730:27)\n' +    '    at Module.require (internal/modules/cjs/loader.js:957:19)\n' +    '    at require (internal/modules/cjs/helpers.js:88:18)\n' +    '    at getPrismaClientDmmf (/var/task/node_modules/nexus-prisma/dist/helpers/prisma.js:17:21)\n' +    '    at Object.<anonymous> (/var/task/node_modules/nexus-prisma/dist/runtime/index.js:14:14)\n' +    '    at Module._compile (internal/modules/cjs/loader.js:1068:30)\n' +    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)\n' +    '    at Module.load (internal/modules/cjs/loader.js:933:32)\n' +    '    at Function.Module._load (internal/modules/cjs/loader.js:774:14)',  message: 'Failed to get Prisma Client DMMF. An error occured while trying to import it from /vercel/path0/node_modules/@prisma/client. \n' +    "Cannot find module '/vercel/path0/node_modules/@prisma/client'\n" +    'Require stack:\n' +    '- /var/task/node_modules/nexus-prisma/dist/helpers/prisma.js\n' +    '- /var/task/node_modules/nexus-prisma/dist/runtime/index.js\n' +    '- /var/task/node_modules/nexus-prisma/dist/index.js\n' +    '- /var/task/.next/server/pages/api/graphql.js\n' +    '- /var/task/node_modules/next/dist/next-server/server/next-server.js\n' +    '- /var/task/___next_launcher.js\n' +    '- /var/runtime/UserFunction.js\n' +    '- /var/runtime/index.js',  code: 'MODULE_NOT_FOUND',  requireStack: [    '/var/task/node_modules/nexus-prisma/dist/helpers/prisma.js',    '/var/task/node_modules/nexus-prisma/dist/runtime/index.js',    '/var/task/node_modules/nexus-prisma/dist/index.js',    '/var/task/.next/server/pages/api/graphql.js',    '/var/task/node_modules/next/dist/next-server/server/next-server.js',    '/var/task/___next_launcher.js',    '/var/runtime/UserFunction.js',    '/var/runtime/index.js'  ],  toJSON: [Function: toJSON],  name: 'Error',  toString: [Function: toString]}RequestId: 8dfe433e-3d3a-4d4e-b586-3e9c83dacb67 Error: Runtime exited with error: exit status 1Runtime.ExitError
```

### How to reproduce

https://github.com/PookMook/starting-blocks and change prisma version to anything from 2.20 and up

2.25 https://starting-blocks-jzelac27k-arthurj.vercel.app/
2.24 also fails, didn't have same test : https://starting-blocks-mwfkjg9mo-arthurj.vercel.app/api/graphql
2.23: https://starting-blocks-1td4ebw0w-arthurj.vercel.app
2.22: https://starting-blocks-jt2i75v11-arthurj.vercel.app
2.21: https://starting-blocks-ppwua9ler-arthurj.vercel.app
2.20: https://starting-blocks-r0ip4x5tk-arthurj.vercel.app
2.19 (and working): https://starting-blocks-41h50hqdw-arthurj.vercel.app/ 
2.18 (and working): https://starting-blocks-dyb8qx07q-arthurj.vercel.app/

### Expected behavior

might be vercel's fault, but I expect the function to work just like it does in 2.19

### Prisma information

minimal schema just to get everything going

```
datasource db {
    provider = "postgresql"
    url = env("DATABASE_URL")
}

generator client {
    provider = "prisma-client-js"
}

generator nexusPrisma {
    provider = "nexus-prisma"
}

model User {
    /// Encoded ID exposed to the public.
    id String@default(cuid()) @id
    /// Name of the User
    name String
}
```

### Environment & setup

- OS:  vercel's lambda
- Database: PostgreSQL
- Node.js version: 14

### Prisma Version

Works fine locally, don't know how to get this on vercel's log

```
prisma               : 2.20.0
@prisma/client       : 2.20.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by janpio** [comment]
We have tests with that combination, Vercel and Prisma via Nexus, so this is something specific about this project. We will of course try to help you figure out what is going on here.

Your project's `package.json` is quite elaborate, what would be the relevant part for us to get to a minimal reprodution? (Same about the code obviously) Can you maybe try to create a minimal reproduction as well? That would help us _a lot_.

**Comment by PookMook** [comment]
Thanks for the response, it looks like you are indeed right. The problem seems to be coming from prisma-nexus, i'll have to dig a little bit deeper on this one and raise an issue on that repo once I have more information.

I removed pretty much all the tooling to make sure there's no interference, still got the same error.
Then I just created a prisma only route and this one is working just fine. My next step is going to remove the nexus-prisma part and query prisma manually in my nexus declaration to 100% isolate the problem.
You can see the code here (https://github.com/PookMook/starting-blocks/tree/prisma-isolation) and in action here https://starting-blocks-qnd1fsmfu-arthurj.vercel.app/

The route with pure prisma querying works just fine, while the one with nexus-prisma and nexus does throw the same error!
