### ISSUE TITLE
Using `PRISMA_FORCE_NAPI` only for Prisma Client (and not CLI) does not work

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7783]
If you create a normal project (with the binary), generate a Client, but then set `PRISMA_FORCE_NAPI=true` before/when using that Client, the Client will not find any engine file and crash:

```
(node:19296) UnhandledPromiseRejectionWarning: Error: Query engine library for current platform "windows" could not be found.
You incorrectly pinned it to windows

This probably happens, because you built Prisma Client on a different platform.
(Prisma Client looked in "C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\node_modules\@prisma\client\runtime\query_engine_napi-windows.dll.node")

Searched Locations:

  C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\node_modules\.prisma\client
  C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\node_modules\@prisma\client
  C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\node_modules\@prisma\client
  C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\node_modules\.prisma\client
  C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\prisma
  /tmp/prisma-engines
  C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\node_modules\.prisma\client


To solve this problem, add the platform "windows" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

Then run "prisma generate" for your changes to take effect.
Read more about deploying Prisma Client: https://pris.ly/d/client-generator
    at NAPIEngine.getLibQueryEnginePath (C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\node_modules\@prisma\client\runtime\index.js:22982:15) 
    at async NAPIEngine.loadEngine (C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\node_modules\@prisma\client\runtime\index.js:22646:35)      
    at async NAPIEngine.instantiateLibrary (C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\node_modules\@prisma\client\runtime\index.js:22612:7)
    at async NAPIEngine.start (C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\node_modules\@prisma\client\runtime\index.js:22762:7)
    at async main (C:\Users\Jan\Documents\throwaway\e2e-tests\engines\napi-preview-feature\test-generated-client.js:7:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

Adding the binaryTarget of course would not help here at all. The problem is that the library is indeed not downloaded at all, so can not be found anywhere. (The binary is present in the Client and multiple other locations)

(You can "work around" this by downloading the engine library manually and pointing to it with `PRISMA_QUERY_ENGINE_LIBRARY`)

**Comment by janpio** [comment]
Relevance: We need to figure out how this should work for the escape hatch for the "Enabling Node-API" implementation.

**Comment by pantharshit00** [comment]
I can reproduce but don't know specifics of the flag. My guess would be that we still check for binary existence even though Node API is forced.

**Comment by janpio** [comment]
Oh yeah, should have marked this as confirmed myself already - we clearly know what is going on here and it is kinda expected - we will probably ship the escape hatch like this as well. Just something for the tracking board so we are aware and can possibly add a nice error message.

**Comment by janpio** [comment]
Not a problem in context of https://github.com/prisma/prisma/issues/8731 any more.
