### ISSUE TITLE
Cant order by int in findMany

### ISSUE THREAD

**Issue by Floffah** [prisma/prisma#7806]
### Bug description

A bug which occurs when using the client programmatically and in the studio. 
Here is an example of what i am doing:

```ts
           const tenth = await this.bot.db.wordUse.findMany({
                orderBy: {
                    count: "desc",
                },
                where: {
                    userId: m.author.id,
                },
            });
```

Doing it without the where or without filters on the studio also gives me the error.

The error is:
```
PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]:
Invalid `prisma.wordUse.findMany()` invocation:


  Failed to validate the query: `Assertion error: Attempted conversion of non-map ParsedInputValue (Single(String("desc"))) into map failed..` at ``
    at cb (E:\projects\bot\crossant\node_modules\@prisma\client\runtime\index.js:33816:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Stats.trackWords (E:\projects\bot\crossant\src\modules\Stats.ts:66:27)
    at Bot.<anonymous> (E:\projects\bot\crossant\src\modules\Stats.ts:15:45) {
  code: 'P2009',
  clientVersion: '2.25.0',
  meta: {
    query_validation_error: 'Assertion error: Attempted conversion of non-map ParsedInputValue (Single(String("desc"))) into map failed..',
    query_position: ''
  }
}
```

### How to reproduce

Use the schema listed below, connect it to a postgres database, run the query I pasted above.

### Expected behavior

Returns all of the records ordered by count descending.

### Prisma information

Pasted the whole thing just in case i missed something crucial

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["selectRelationCount"]
}

// content delivery

model Image {
  id       Int     @id @default(autoincrement())
  content  String
  original String?
  Drink    Drink?  @relation(fields: [drinkId], references: [id])
  drinkId  Int?
}

// order

model Drink {
  id     Int     @id @default(autoincrement())
  name   String
  images Image[]
}

// users

model User {
  id String @id

  // opted in to
  optWordCount Boolean @default(false)

  // stats
  words WordUse[]
}

model WordUse {
  word    String
  userId  String
  user    User    @relation(fields: [userId], references: [id])
  isCurse Boolean @default(false)

  count Int

  @@id([word, userId])
}

// guilds
model Guild {
  id String @id

  // -- SETTINGS --
  // channel list
  channelListMode ListMode
  channelList     String[]
  // guild board
  boards          GuildBoard[]
}

model GuildBoard {
  id      Int    @id @default(autoincrement())
  guild   Guild  @relation(fields: [guildId], references: [id])
  guildId String

  channelId String
  emoji     String

  messages GuildBoardMessage[]
}

model GuildBoardMessage {
  reactedMessageId String
  messageId        String
  reactedChannelId String
  channelId        String

  board   GuildBoard @relation(fields: [boardId], references: [id])
  boardId Int

  @@id([reactedMessageId, reactedChannelId])
}

// common
enum ListMode {
  Blacklist
  Whitelist
}
```

### Environment & setup

- OS: Windows 10 Pro
- Database: PostgreSQL
- Node.js version: 16.3.0
(This error also occurs as far back as node 12, i tested it against 12, 14, 15, and 16)

### Prisma Version

```
Environment variables loaded from .env
prisma               : 2.25.0
@prisma/client       : 2.25.0
Current platform     : windows
Query Engine         : query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules\@prisma\engines\query-engine-windows.exe)
Migration Engine     : migration-engine-cli c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine : introspection-core c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary        : prisma-fmt c838e79f39885bc8e1611849b1eb28b5bb5bc922 (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash : c838e79f39885bc8e1611849b1eb28b5bb5bc922
Studio               : 0.402.0
Preview Features     : selectRelationCount
```

**Comment by Floffah** [comment]
turns out its just because i called the field count, prisma didnt warn me about that and just broke instead

**Comment by janpio** [comment]
That is the definition of a bug that should be fixed.

**Comment by MartinPavlik** [comment]
Hi, is there any workaround for this (how to order by the field `count`) or not? It would be nice to put this at least to the docs :smile:
