### ISSUE TITLE
Errors are different for Node-API library and normal binary

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7811]
Test indicate:
https://github.com/prisma/prisma/blob/5636b78e9f25f12a0738029e323a69715ddbee1b/src/packages/client/src/__tests__/integration/errors/invalid-input/test.ts#L19-L66

**Comment by janpio** [comment]
I can confirm this in manual reproduction:

```

C:\Users\Jan\Documents\throwaway\errorRepro  (errorRepro@1.0.0)
λ node script.js


node-api error message:
 PrismaClientValidationError:
Invalid `prisma.user.create()` invocation:

{
  data: {
    email: 'a@a.de',
    posts: {
    ~~~~~
      connect: {
        id: []
      }
    }
  }
}

Unknown arg `posts` in data.posts for type UserCreateInput. Did you mean `email`? Available args:
type UserCreateInput {
  email: String
  name?: String | Null
}


    at Document.validate (C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:32626:19)
    at NewPrismaClient._executeRequest (C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:34732:17)
    at consumer (C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:34677:23)
    at C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:34679:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:34679:25)
    at Object.then (C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:34787:39) {
  clientVersion: '2.26.0-dev.38'
}


binary error message:
 PrismaClientValidationError:
Invalid `prismaBinary.user.create()` invocation in
C:\Users\Jan\Documents\throwaway\errorRepro\script.js:22:29

  19 }
  20
  21 try {
→ 22   await prismaBinary.user.create({
         data: {
           email: 'a@a.de',
           posts: {
           ~~~~~
             connect: {
               id: []
             }
           }
         }
       })

Unknown arg `posts` in data.posts for type UserCreateInput. Did you mean `email`? Available args:
type UserCreateInput {
  email: String
  name?: String | Null
}


    at Document.validate (C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:32626:19)
    at NewPrismaClient._executeRequest (C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:34732:17)
    at consumer (C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:34677:23)
    at C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:34679:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:34679:25)
    at Object.then (C:\Users\Jan\Documents\throwaway\errorRepro\prisma\node-api\runtime\index.js:34787:39) {
  clientVersion: '2.26.0-dev.38'
}

```

```patch
2,3c2,14
< Invalid `prismaBinary.user.create()` invocation in
< C:\Users\Jan\Documents\throwaway\errorRepro\script.js:22:29
---
> Invalid `prisma.user.create()` invocation:
> 
> {
>   data: {
>     email: 'a@a.de',
>     posts: {
>     ~~~~~
>       connect: {
>         id: []
>       }
>     }
>   }
> }
5,18d15
<   19 }
<   20
<   21 try {
< ? 22   await prismaBinary.user.create({
<          data: {
<            email: 'a@a.de',
<            posts: {
<            ~~~~~
<              connect: {
<                id: []
<              }
<            }
<          }
<        })

```

The Node-API version is missing the filename with line numbers, and the line numbers in the code snippet.

**Comment by janpio** [comment]
But this also raises the question why these tests here are not failing because of snapshot differences as well:

- https://github.com/prisma/prisma/blob/master/src/packages/client/src/__tests__/integration/errors/client-version-error/test.ts
- https://github.com/prisma/prisma/blob/master/src/packages/client/src/__tests__/integration/errors/incorrect-column-type/test.ts
- ...

(Confirmed locally that with a Node-API enabled Client the error message is different, also missing the line numbers and filename. Also confirmed that the tests pass locally.)

**Comment by janpio** [comment]
Turns out this is a more general problem in Prisma, not specific to Node-API: https://github.com/prisma/prisma/issues/7874
