### ISSUE TITLE
PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18expected array type

### ISSUE THREAD

**Issue by romanalmashi** [prisma/prisma#7830]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.20.1           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.23.0             |
| Query Engine    | query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b|
| Database        | undefined|

## Query
```
query {
  findManyOffer(
    where: {
      OR: [
        {
          brand: "X"
        }
      ]
    }
    orderBy: []
    take: 5
    skip: 5
  ) {
    id
    inStock
    vatDeductible
    originalPrice
    countryCode
    priceCZ
    priceDE
    priceSE
    pricePL
    registeredAt
    createdAt
    updatedAt
    deletedAt
    deleted
    originalImages
    images
    imagesProcessed
    generation
    engineName
    carName
    vin
    registrationNumber
    colourCode
    energyLabel
    dealerName
    dealerAddress
    site
    url
    originalOfferId
    brand
    model
    type
    chassis
    colourExterior
    colour
    upholstery
    fuel
    gearboxType
    driveAxle
    condition
    consumption
    acceleration
    numberOfGears
    numberOfDoors
    numberOfSeats
    enginePower
    torque
    displacement
    cylinders
    numberOfElectricalEngines
    powerOfFrontEngine
    powerOfRearEngine
    topSpeed
    numberOfOwners
    mileage
    emissionCO2
    euroStandard
    modelYear
    manufactureYear
    manufactureMonth
    airbagCount
    weight
    height
    width
    length
    metallic
    lightAlloyWheels
    alloyWheels15
    alloyWheels16
    alloyWheels17
    alloyWheels18
    alloyWheels19
    alloyWheels20
    alloyWheels21
    alloyWheels22
    alloyWheels23
    steelWheels
    winterTyres
    summerTires
    yearRoundTires
    setOfWinterBikes
    setOfWinterLightAlloyWheels
    elControlledExteriorMirrors
    elFoldingExteriorMirrors
    heatedExteriorMirrors
    ledDaytimeRunningLights
    daytimeRunningLights
    lightSensor
    ledHeadlights
    halogenHeadlights
    xenonHeadlights
    biXenonHeadlights
    laserHeadlights
    adaptiveHeadlights
    fogLights
    rearLedHeadlights
    tirePressureCheck
    airSuspension
    sportsSuspension
    adaptiveSuspension
    chassisStiffnessRegulation
    slidingDoors
    electricTrunkControl
    powerWindows
    sunroof
    electricallyOperatedSunroof
    panoramicRoof
    elControlledPanoramicRoof
    tintedGlass
    roofRails
    selfLockingDifferential
    electronicDifferentialLock
    travelSpareWheel
    fullFledgedSpareWheel
    winch
    removableTowingDevice
    towingEquipment
    airConditioning
    automaticAirConditioning
    manualAirConditioning
    dualZoneAirConditioning
    threeZoneAirConditioning
    fourZoneAirConditioning
    independentHeating
    driverSAirbag
    passengerAirbag
    sideAirbags
    headAirbags
    kneeAirbags
    deactivatingTheFrontPassengerAirbag
    alarm
    immobilizer
    centralLocking
    remoteCentralLocking
    keylessAccess
    keylessStart
    childSafetyLock
    heatedWindshield
    blindSpotMonitoring
    abs
    esp
    tractionControlAsr
    collisionWarningSystem
    laneKeepingAssistant
    hillStartAssist
    hillStartAssistDac
    nightVisionAssistant
    selfDimmingRearViewMirror
    rainSensor
    startStopSystem
    acousticParkingAssistant
    parkingAssistant
    parkingCamera
    parkingSensors
    frontParkingSensors
    rearParkingSensors
    automaticEmergencyCall
    emergencyBrakeAssistant
    activeHood
    brandRecognitionSystem
    pedestrianAndCyclistRecognitionSystem
    obstacleRecognitionSystem
    behindTheVehicleWarningSystem
    fatigueRecognitionSystem
    powerSteering
    electricParkingBrake
    automaticHighBeams
    isofix
    isofixOnTheFrontPassengerSeat
    cruiseControl
    adaptiveCruiseControl
    cruiseControlInStopGoFunction
    speedmeter
    camera360
    controlSelectedCarFunctionsWithGestures
    voiceControl
    handsfree
    navigation
    acousticWindshield
    onboardComputer
    touchDisplay
    colorDisplay
    clearHeadUpDisplayHud
    display6
    display7
    display8
    display9
    display10
    display11
    display12
    display15
    display20
    gearIndicator
    radio
    tv
    cd
    cdChanger
    dvd
    soundSystem
    appleCarPlay
    androidAuto
    integratedMusicStreaming
    inductiveChargingForSmartphones
    dabDigitalRadio
    mp3
    usb
    thermometer
    aux
    bluetooth
    subwoofer
    armrest
    rearSeatArmrest
    airConditionedPassengerCompartment
    socketAtTheFront12V
    socketAtTheBack12V
    socketInTheCase12V
    socket230V
    smokingPackage
    drinkHolderInFront
    drinkHolderAtTheBack
    metalPedals
    ambientLighting
    makeupMirror
    electricSunVisor
    mechanicalSunVisor
    rearWindowBlinds
    clock
    multifunctionSteeringWheel
    sportsSteeringWheel
    shiftPaddlesUnderTheSteeringWheel
    leatherSteeringWheel
    adjustableSteeringWheel
    heatedSteeringWheel
    adjustableSeats
    electricallyAdjustableSeats
    electricallyAdjustableRearSeats
    electricallyAdjustableSeatsWithMemory
    heightAdjustableDriverSSeat
    foldingPassengerSeat
    heatedDriverSSeat
    heatedFrontSeats
    heatedRearSeats
    heatedSeats
    seatVentilation
    removableRearSeats
    massageSeats
    lumbarSupport
    sportsSeats
    electricallyAdjustableLumbarSupport
    skiBox
    railSystemInTheLuggageCompartment
    backlitBoardingRails
    emergencyStopSystem
    gestureControl
    remoteVehicleManagementViaAMobileApplication
    wiFiHotspot
  }
}
```

## Logs
```
s
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/home/roman/TDC/core/backend/node_modules/@prisma/client/runtime/index.js:25530:24)
  prisma:engine       at Socket.emit (events.js:326:22)
  prisma:engine       at Socket.EventEmitter.emit (domain.js:483:12)
  prisma:engine       at endReadableNT (_stream_readable.js:1241:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by pantharshit00** [comment]
Hello! Sorry for late reply here.  Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
