### ISSUE TITLE
PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by linxiaowu66** [prisma/prisma#7851]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v15.5.1            | 
| OS              | darwin             |
| Prisma Client   | 2.25.0             |
| Query Engine    | query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922|
| Database        | undefined|

## Query
```
mutation {
  queryRaw(
    query: "X"
    parameters: "X"
  )
}
```

## Logs
```
7Z prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:tryLoadEnv Environment variables not found at null
prisma:tryLoadEnv Environment variables not found at undefined
prisma:tryLoadEnv No Environment variables loaded
prisma:client clientVersion: 2.25.0
prisma:engine Search for Query Engine in /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/_@prisma_client@2.25.0@@prisma/.prisma/client
prisma:engine Search for Query Engine in /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/@prisma/client/nextdy
prisma:client prisma.queryRaw(show tables, [])
prisma:client Prisma Client call:
prisma:engine { cwd: '/Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/prisma' }
prisma:engine Search for Query Engine in /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/_@prisma_client@2.25.0@@prisma/.prisma/client
prisma:engine Search for Query Engine in /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/@prisma/client/nextdy
plusX Execution permissions of /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/@prisma/client/nextdy/query-engine-darwin are fine
plusX Execution permissions of /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/@prisma/client/nextdy/query-engine-darwin are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '62460' ] }
prisma:engine stdout  Starting a mysql pool with 9 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:62460
prisma:engine Search for Query Engine in /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/_@prisma_client@2.25.0@@prisma/.prisma/client
prisma:engine Search for Query Engine in /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/@prisma/client/nextdy
plusX Execution permissions of /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/@prisma/client/nextdy/query-engine-darwin are fine
prisma:engine Client Version: 2.25.0
prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922
prisma:engine Active provider: mysql
prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43
index out of bounds: the len is 0 but the index is 0
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/_@prisma_client@2.25.0@@prisma/client/nextdy/runtime/index.js:25736:24)
      at Socket.emit (node:events:388:22)
      at Socket.EventEmitter.emit (node:domain:470:12)
      at endReadableNT (node:internal/streams/readable:1305:12)
      at processTicksAndRejections (node:internal/process/task_queues:80:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:62460
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1138:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 62460
  }
}
prisma:engine { cwd: '/Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/prisma' }
prisma:engine Search for Query Engine in /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/_@prisma_client@2.25.0@@prisma/.prisma/client
prisma:engine Search for Query Engine in /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/@prisma/client/nextdy
plusX Execution permissions of /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/@prisma/client/nextdy/query-engine-darwin are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '62473' ] }
prisma:engine stdout  Starting a mysql pool with 9 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:62473
prisma:engine Search for Query Engine in /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/_@prisma_client@2.25.0@@prisma/.prisma/client
prisma:engine Search for Query Engine in /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/@prisma/client/nextdy
plusX Execution permissions of /Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/@prisma/client/nextdy/query-engine-darwin are fine
prisma:engine Client Version: 2.25.0
prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922
prisma:engine Active provider: mysql
prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43
index out of bounds: the len is 0 but the index is 0
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/Users/linxiaowu/Alibaba/chaoshi-fass/puma-node/node_modules/_@prisma_client@2.25.0@@prisma/client/nextdy/runtime/index.js:25736:24)
      at Socket.emit (node:events:388:22)
      at Socket.EventEmitter.emit (node:domain:470:12)
      at endReadableNT (node:internal/streams/readable:1305:12)
      at processTicksAndRejections (node:internal/process/task_queues:80:21) {
    code: 'UND_ERR_SOCKET'
  }
}
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?
