### ISSUE TITLE
PANIC in query-engine\connectors\mongodb-query-connector\src\root_queries\read.rs:101:74called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by naveenrobo** [prisma/prisma#7861]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | windows            |
| Prisma Client   | 2.25.0             |
| Query Engine    | query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922|
| Database        | undefined|

## Query
```
query {
  findFirstDeviceDetail(where: {
    AND: [
      {
        device_id: "X"
      }
    ]
  }) {
    id
    db_user_id
    kms_user_id
    rf_id
    rf_id_pin
    device_id
    device_role
    face_id
    face_id_path
    is_active
    active_from
    expiry
    slots {
      id
      slot
      name
      description
      status
      rf_id
      device_id
      last_used_user_id
    }
  }
}
```

## Logs
```
5;167;1mprisma:client clientVersion: 2.25.0  
  prisma:engine Search for Query Engine in D:\Projects\Key Management System\kms-backend-v2\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\Key Management System\kms-backend-v2\node_modules\.prisma\client  
  prisma:engine Search for Query Engine in D:\Projects\Key Management System\kms-backend-v2\node_modules\.prisma\client  
  prisma:engine { cwd: 'D:\\Projects\\Key Management System\\kms-backend-v2\\prisma' }  +24s
  prisma:engine Search for Query Engine in D:\Projects\Key Management System\kms-backend-v2\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '61023' ] }  
  prisma:engine stdout  Started http server on http://127.0.0.1:61023  
  prisma:engine Search for Query Engine in D:\Projects\Key Management System\kms-backend-v2\node_modules\.prisma\client  
  prisma:engine Client Version: 2.25.0  
  prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922  
  prisma:engine Active provider: mongodb  
  prisma:engine { cwd: 'D:\\Projects\\Key Management System\\kms-backend-v2\\prisma' }  
  prisma:engine Search for Query Engine in D:\Projects\Key Management System\kms-backend-v2\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '61029' ] }  
  prisma:engine stdout  Started http server on http://127.0.0.1:61029  
  prisma:engine Search for Query Engine in D:\Projects\Key Management System\kms-backend-v2\node_modules\.prisma\client  
  prisma:engine Client Version: 2.25.0  
  prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922  
  prisma:engine Active provider: mongodb  
  prisma:engine stdout  PANIC in query-engine\connectors\mongodb-query-connector\src\root_queries\read.rs:101:74
called `Option::unwrap()` on a `None` value  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:61029
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 61029
  prisma:engine   }
  prisma:engine }  
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd: 'D:\\Projects\\Key Management System\\kms-backend-v2\\prisma' }  
  prisma:engine Search for Query Engine in D:\Projects\Key Management System\kms-backend-v2\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '61036' ] }  
  prisma:engine stdout  Started http server on http://127.0.0.1:61036  
  prisma:engine Search for Query Engine in D:\Projects\Key Management System\kms-backend-v2\node_modules\.prisma\client  
  prisma:engine Client Version: 2.25.0  
  prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922  
  prisma:engine Active provider: mongodb  
  prisma:engine stdout  PANIC in query-engine\connectors\mongodb-query-connector\src\root_queries\read.rs:101:74
called `Option::unwrap()` on a `None` value  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
 let deviceDetail = await this.prisma.deviceDetail.findFirst({
      where: {
        AND: [
          {
            device_id: device_id,
          },
        ],
      },
      include: {
        slots: true,
      },
    });

```

## Schema
```prisma
model DeviceDetail {
    id           String     @id @default(uuid()) @map("_id")
    user         User       @relation(fields: [db_user_id], references: [id])
    db_user_id   String
    kms_user_id  String     @unique
    rf_id        String?
    rf_id_pin    Int?
    device       Device     @relation(fields: [device_id], references: [id])
    device_id    String
    device_role  DeviceRole @default(USER)
    face_id      String
    face_id_path String?
    is_active    Boolean    @default(true)
    active_from  DateTime   @default(now())
    expiry       DateTime?
    slots        Slot[]

    @@unique([kms_user_id, device_id])
}

model Slot {
    id                String         @id @default(uuid()) @map("_id")
    slot              Int
    name              String
    description       String?
    status            SlotStatus
    rf_id             String
    device            Device         @relation(fields: [device_id], references: [id])
    device_id         String
    last_used_user_id String?
    schedules         Schedule[]
    device_details    DeviceDetail[]
}
```

**Comment by matthewmueller** [comment]
I _think_ this is the same as https://github.com/prisma/prisma/issues/7057

**Comment by dpetrick** [comment]
Please follow the same modeling advise from this ticket and try again: https://github.com/prisma/prisma/issues/6877#issuecomment-881367613

**Comment by naveenrobo** [comment]
okay. let me try.

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
