### ISSUE TITLE
When a script throws multiple errors, the first one does not output a file path and line numbers

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7874]
When running the same query, that throws an error, multiple times in the same script, the first error message does not include a file path and the line numbers:

```

C:\Users\Jan\Documents\throwaway\errorRepro2 (main -> origin) (errorRepro2@1.0.0)
λ node script.js


1:
 PrismaClientValidationError:
Invalid `prisma.user.findMany()` invocation:

{
  invalidArg: true
  ~~~~~~~~~~
}

Unknown arg `invalidArg` in invalidArg for type User. Did you mean `where`? Available args:
type findManyUser {
  where?: UserWhereInput
  orderBy?: List<UserOrderByInput> | UserOrderByInput
  cursor?: UserWhereUniqueInput
  take?: Int
  skip?: Int
  distinct?: List<UserScalarFieldEnum>
}


    at Document.validate (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:32546:19)
    at NewPrismaClient._executeRequest (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34652:17)
    at consumer (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34597:23)
    at C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34599:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34599:25)
    at Object.then (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34707:39) {
  clientVersion: '2.25.0'
}


2:
 PrismaClientValidationError:
Invalid `prisma.user.findMany()` invocation in
C:\Users\Jan\Documents\throwaway\errorRepro2\script.js:13:23

  10 }
  11
  12 try {
→ 13   await prisma.user.findMany({
         invalidArg: true
         ~~~~~~~~~~
       })

Unknown arg `invalidArg` in invalidArg for type User. Did you mean `where`? Available args:
type findManyUser {
  where?: UserWhereInput
  orderBy?: List<UserOrderByInput> | UserOrderByInput
  cursor?: UserWhereUniqueInput
  take?: Int
  skip?: Int
  distinct?: List<UserScalarFieldEnum>
}


    at Document.validate (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:32546:19)
    at NewPrismaClient._executeRequest (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34652:17)
    at consumer (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34597:23)
    at C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34599:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34599:25)
    at Object.then (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34707:39) {
  clientVersion: '2.25.0'
}


3:
 PrismaClientValidationError:
Invalid `prisma.user.findMany()` invocation in
C:\Users\Jan\Documents\throwaway\errorRepro2\script.js:19:23

  16 }
  17
  18 try {
→ 19   await prisma.user.findMany({
         invalidArg: true
         ~~~~~~~~~~
       })

Unknown arg `invalidArg` in invalidArg for type User. Did you mean `where`? Available args:
type findManyUser {
  where?: UserWhereInput
  orderBy?: List<UserOrderByInput> | UserOrderByInput
  cursor?: UserWhereUniqueInput
  take?: Int
  skip?: Int
  distinct?: List<UserScalarFieldEnum>
}


    at Document.validate (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:32546:19)
    at NewPrismaClient._executeRequest (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34652:17)
    at consumer (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34597:23)
    at C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34599:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34599:25)
    at Object.then (C:\Users\Jan\Documents\throwaway\errorRepro2\node_modules\@prisma\client\runtime\index.js:34707:39) {
  clientVersion: '2.25.0'
}
```

Reproduction lives here: https://github.com/janpio/prisma-error-error-repro

Gist of it:
```
async function main() {
  try {
    await prisma.user.findMany({ invalidArg: true })
  } catch (e) {
    console.log('\n\n1:\n', e)
  }

  try {
    await prisma.user.findMany({ invalidArg: true })
  } catch (e) {
    console.log('\n\n2:\n', e)
  }

  try {
    await prisma.user.findMany({ invalidArg: true })
  } catch (e) {
    console.log('\n\n3:\n', e)
  }
}
```

Tested with 2.25.0 and current dev on Windows.

**Comment by janpio** [comment]
This also popped up in Node-API related tests: https://github.com/prisma/prisma/issues/7811 It is not fully clear why some of the tests require differentiation between Node-API and binary - It would kinda mean that the Node-API tests threw _another_ error before somehow that did have this bug, or the bug is not consistent in all cases (although it was in my testing).

**Comment by janpio** [comment]
@Jolg42 pointed to the code that might be responsible here:
https://github.com/prisma/prisma/blob/master/src/packages/client/src/runtime/utils/printStack.ts#L75-L86
you end up there via
https://github.com/prisma/prisma/blob/f19b157918da51dd24eb9559a2698e4d4f52406f/src/packages/client/src/runtime/query.ts#L59

**Comment by janpio** [comment]
Tried to create a quick test as reproduction, but for some reason there the first error also has the file path and line numbers: https://github.com/prisma/prisma/pull/7876 Does not make sense to me.

**Comment by janpio** [comment]
https://github.com/prisma/prisma/pull/7902 has been merged, so this might already be fixed. Needs to be confirmed.

**Comment by janpio** [comment]
This is unfortunately not fixed yet - the first stacktrace is still missing the line numbers in `2.27.0-dev.25`.
