### ISSUE TITLE
PANIC in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_common-0.26.0/src/constants.rs:498:18Unknown column type 14

### ISSUE THREAD

**Issue by kman1sh** [prisma/prisma#7895]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
I m hitting a raw query. When tested locally  everything works fine. However when deployed on aws I m getting below error with two of graphql queries.  I m very new to graphql and Prisma world. Please guide me on how to fix this.

## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.17.0           | 
| OS              | rhel-openssl-1.0.x |
| Prisma Client   | 2.22.1             |
| Query Engine    | query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c|
| Database        | MariaDB Server|

## Query
```
mutation {
  queryRaw(
    query: "X"
    parameters: "X"
  )
}
```

## Logs
```
  CASE 
          WHEN ExDate IS NULL THEN IFNULL(reinvestmentDate, payableDate) ELSE exDate END as 'ExDate',
        payableDate as 'PayDate', amount as 'DividendAmount', 
        titleCode as 'DividendType', title as 'EventDescription', 
        PayTypeList, FootnoteList, footnoteLiterals as 'FootnoteDescription', SplitLiteral, SplitType, IssueType, Literals,
        printLiterals as 'LiteralDescription', 
        actionRevisionList as 'RevisionCodeAll', 
        actionRevisionLiterals as 'RevisionCodeAllDescription', 
        currencyCode as 'Currency', ParValue, ParCurrency, dividendAmount as 'DPFCRate'
          from vms.MERGENT_CorporateActions 
          where eventGroupType = 'dividendsEvent'
          AND ISIN IN ('US53656F6566') AND (eventAddDate <= '2021-06-24' AND eventAddDate >= '2021-05-06') 
          order by ISIN DESC, paymentKey desc;, [])
prisma:client Prisma Client call:
prisma:engine { cwd: '/var/task/node_modules/.prisma/client' }
prisma:engine Search for Query Engine in /var/task/node_modules/.prisma/client
plusX Execution permissions of /var/task/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '35733' ] }
prisma:engine stdout  Starting a mysql pool with 5 connections.
prisma:engine stdout  Fetched a connection from the pool
prisma:engine stdout  Started http server on http://127.0.0.1:35733
prisma:engine Search for Query Engine in /var/task/node_modules/.prisma/client
plusX Execution permissions of /var/task/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine Client Version: 2.22.1
prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c
prisma:engine Active provider: mysql
prisma:engine stdout  Fetched a connection from the pool
prisma:engine stdout  PANIC in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_common-0.26.0/src/constants.rs:498:18
Unknown column type 14
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/var/task/node_modules/@prisma/client/runtime/index.js:25530:24)
      at Socket.emit (events.js:388:22)
      at endReadableNT (internal/streams/readable.js:1336:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:35733
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 35733
  }
}
prisma:engine { cwd: '/var/task/node_modules/.prisma/client' }
prisma:engine Search for Query Engine in /var/task/node_modules/.prisma/client
plusX Execution permissions of /var/task/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '40745' ] }
prisma:engine stdout  Starting a mysql pool with 5 connections.
prisma:engine stdout  Fetched a connection from the pool
prisma:engine stdout  Started http server on http://127.0.0.1:40745
prisma:engine Search for Query Engine in /var/task/node_modules/.prisma/client
plusX Execution permissions of /var/task/node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x are fine
prisma:engine stdout  Fetched a connection from the pool
prisma:engine Client Version: 2.22.1
prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c
prisma:engine Active provider: mysql
prisma:engine stdout  PANIC in /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_common-0.26.0/src/constants.rs:498:18
Unknown column type 14
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/var/task/node_modules/@prisma/client/runtime/index.js:25530:24)
      at Socket.emit (events.js:388:22)
      at endReadableNT (internal/streams/readable.js:1336:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'UND_ERR_SOCKET'
  }
}
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE:
not using schema as it is a raw query.
```

**Comment by pantharshit00** [comment]
Can you please share the whole raw query which you trying to run so that we can reproduce this? 

Also, if you can, share the part of the database schema as well which is required for that query to execute.

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
