### ISSUE TITLE
MongoDB: `Command failed (OperationNotSupportedInTransaction): Cannot run command against the 'admin' database in a transaction.`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7967]
The default Mongo connection string you get from DigitalOcean's hosted MongoDB offering looks like this: `mongodb+srv://doadmin:30x8...GR2@db-mongodb-nyc3-a1...21.mongo.ondigitalocean.com/admin?authSource=admin&replicaSet=db-mongodb-nyc3&tls=true&tlsCAFile=../ca-certificate.crt`. 

When you try to run a query on that, you get an error message like this:

```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: 
Invalid `prisma.user.deleteMany()` invocation:
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawError { code: "unknown", message: "Command failed (OperationNotSupportedInTransaction): Cannot run command against the 'admin' database in a transaction.)" } })
    at cb (/home/runner/work/e2e-tests/e2e-tests/databases/mongodb-digitalocean/node_modules/@***/client/runtime/index.js:33904:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.27.0-dev.6'
}
```

Turns out there is a limitation around default databases like `admin` for using transactions. We should handle that somehow.

**Comment by matthewmueller** [comment]
- New mongodb:
  - Can't run transactions on the system collections

- Workaround:
  - MongoDB creates databases on the fly (change to admin1)

- Possible improvement
  - Better error
  - Add Document

**Comment by janpio** [comment]
Suggestion: Better error that knows about the system databases and helps you to understand the failure and offers a solution: Change the database name to something that is not a system database and can use transactions.

**Comment by pinchez254** [comment]
creating a separate db with a different name worked for me. Avoid using primary `DBs` with reserved names such as `admin` or `root`
