### ISSUE TITLE
PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18expected array type

### ISSUE THREAD

**Issue by tafelito** [prisma/prisma#7977]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.17.0           | 
| OS              | darwin             |
| Prisma Client   | 2.26.0             |
| Query Engine    | query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d|
| Database        | undefined|

## Query
```
mutation {
  createOneUser(data: {
    email: "X"
    name: "X"
    hashedPassword: "X"
    roles: [ADMIN]
  }) {
    id
    name
    email
    roles
  }
}
```

## Logs
```
9m }  
  prisma:engine Search for Query Engine in /Users/.../node_modules/.prisma/client  
  plusX Execution permissions of /Users/.../node_modules/.prisma/client/query-engine-darwin are fine  
  plusX Execution permissions of /Users/.../node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '62907' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:62907  
  prisma:engine Search for Query Engine in /Users/.../node_modules/.prisma/client  
  plusX Execution permissions of /Users/.../node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.26.0  
  prisma:engine Engine Version: query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18
expected array type  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/.../node_modules/@prisma/client/runtime/index.js:25782:24)
  prisma:engine       at Socket.emit (events.js:388:22)
  prisma:engine       at Socket.emit (domain.js:470:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1336:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:62907
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -61,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 62907
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/Users/.../db' }  
  prisma:engine Search for Query Engine in /Users/.../node_modules/.prisma/client  
  plusX Execution permissions of /Users/.../node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '62915' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:62915  
  prisma:engine Search for Query Engine in /Users/.../node_modules/.prisma/client  
  plusX Execution permissions of /Users/.../node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.26.0  
  prisma:engine Engine Version: query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18
expected array type  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/.../node_modules/@prisma/client/runtime/index.js:25782:24)
  prisma:engine       at Socket.emit (events.js:388:22)
  prisma:engine       at Socket.emit (domain.js:470:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1336:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
await db.user.create({
      data: { email: ADMIN_EMAIL, name: "Admin", hashedPassword, roles: ["ADMIN"] },
      select: { id: true, name: true, email: true, roles: true },
    })
```

## Schema
```prisma
model User {
  id             Int       @id @default(autoincrement())
  createdAt      DateTime  @default(now())
  updatedAt      DateTime  @updatedAt
  deleted        Boolean   @default(false)
  name           String?
  email          String    @unique
  hashedPassword String?

  roles         UserRole[]
}

enum UserRole {
  USER
  ADMIN
}
```

**Comment by tafelito** [comment]
This issue happened when migrating an enum, for some reason when updated the enum values, it did not update the roles column to the proper type or something like that. I had to rename roles to roles2 and back to be able to get it fixed
