### ISSUE TITLE
SQLite: Constraint Violation is not a known error

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#7979]
When you try to delete an entry that is part of a relation, that is protected via `ON DELETE RESTRICT` (the default on required relations), the error in SQLite is not a known error:

```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: 
Invalid `prisma.buyerGroup.delete()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: ConstraintViolation, extended_code: 1811 }, Some("FOREIGN KEY constraint failed"))) })
    at cb (C:\Users\Jan\Documents\throwaway\refActionsError\node_modules\@prisma\client\runtime\index.js:33900:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  clientVersion: '2.26.0'
}
```

Schema:
```
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialActions"]
}

model Buyer {
  id           String        @id
  buyerGroupId String
  buyerGroup   BuyerGroup @relation(fields: [buyerGroupId], references: [id])
}

model BuyerGroup {
  id     String     @id
  buyers Buyer[]
}
```

Script:
```
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient({
  log: ['query', 'info', `warn`, `error`],
})

async function main() {
  console.log('deleted buyers:', await prisma.buyer.deleteMany())
  console.log('deleted buyerGroups:', await prisma.buyerGroup.deleteMany())

  await prisma.buyer.create({
    data: {
      id: 'Buyer A',
      buyerGroup: {
        create: { id: 'Group A' },
      },
    },
  })

  try {
    await prisma.buyerGroup.delete({
      where: {
        id: 'Group A'
      }
    })
  } catch(e) {
    console.log(e)
  }
}

main()
  .catch(e => {
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

```

**Comment by janpio** [comment]
This is relevant in context of referential actions, as it is now more probable that you see this error message: https://github.com/prisma/prisma/issues/8054
