### ISSUE TITLE
Relation (1-m) between two foreign keys in a table

### ISSUE THREAD

**Issue by masihjahangiri** [prisma/prisma#8035]
### Bug description

I don't know why I get this error when I try to make the relation between two foreign keys in a table!
I get this error:
```
Invalid `prisma.translation.create()` invocation:


  Foreign key constraint failed on the field: `translation_key_fkey1 (index)` +18689ms
Error:
Invalid `prisma.translation.create()` invocation:


  Foreign key constraint failed on the field: `translation_key_fkey1 (index)`
    at cb (C:\Users\masih\Desktop\Projects\thinkeo_back_gql\node_modules\@prisma\client\runtime\index.js:34862:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AttributesResolver.createAttribute (C:\Users\masih\Desktop\Projects\thinkeo_back_gql\dist\resolvers\attributes\attributes.resolver.js:65:9)
    at async target (C:\Users\masih\Desktop\Projects\thinkeo_back_gql\node_modules\@nestjs\core\helpers\external-context-creator.js:76:28)
    at async C:\Users\masih\Desktop\Projects\thinkeo_back_gql\node_modules\@nestjs\core\helpers\external-proxy.js:9:24
```
And database logs:
```
postgres_1  | 2021-07-03 04:10:00.404 UTC [837] ERROR:  insert or update on table "translation" violates foreign key constraint "translation_key_fkey1"
postgres_1  | 2021-07-03 04:10:00.404 UTC [837] DETAIL:  Key (key)=(WwuQQb6ZdT29mkb3yo55b) is not present in table "attribute".
postgres_1  | 2021-07-03 04:10:00.404 UTC [837] STATEMENT:  INSERT INTO "public"."translation" ("key","value","language_key","creation","last_upd") VALUES ($1,$2,$3,$4,$5) RETURNING "public"."translation"."id"
```

### How to reproduce

I want to  create an attribute with an array of traslation:
```ts
const name_key = nanoid();

await this.prisma.attribute.create({
  data: {
    name_key,
  },
});

await this.prisma.translation.create({
  data: {
    attribute_name: {
      connect: {
        name_key,
      },
    },
  },
});
```

### Prisma information

Schema:
```prisma
model attribute {
  id                       String        @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  name_key                 String?       @unique @db.VarChar(255)
  description_key          String?       @unique @db.VarChar(255)
  names_translation        translation[] @relation("attribute_name_to_traslation")
  descriptions_translation translation[] @relation("attribute_description_to_traslation")
}

model translation {
  id                    String     @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  key                   String?    @db.VarChar(255)
  attribute_name        attribute? @relation("attribute_name_to_traslation", fields: [key], references: [name_key])
  attribute_description attribute? @relation("attribute_description_to_traslation", fields: [key], references: [description_key])

  @@index([key], name: "translation_key_index")
}
```

### Environment & setup

- Docker image: postgres:13.3-alpine

### Prisma Version

```
"@prisma/client": "2.20.1",
"prisma-dbml-generator": "0.5.0",
```

**Comment by pantharshit00** [comment]
This is expected, you are using `key` as foreign keys for two relations so key should match foregin key constraint on both while you are inserting the id for only of the fields on the other side. 

Either add another field for separating the relations or insert the id for both of the fields.
