### ISSUE TITLE
`npx prisma migrate reset`: Must use import to load ES Module

### ISSUE THREAD

**Issue by benjaminviaud** [prisma/prisma#8044]
### Bug description

Hello,

Today I updated prisma and @prisma/client packages in my project from 2.22.1 to 2.26.0
But now i meet an error when i run ```npx prisma migrate reset```
Before it works like a charm but now it throw an error
```
migrations/
  └─ 20210602124413_create_user_role_company_tables/
    └─ migration.sql
  └─ 20210607142538_create_bakery_table/
    └─ migration.sql
  └─ 20210608120436_create_pharmacy_table/
    └─ migration.sql
  └─ 20210609122937_create_campaign_table/
    └─ migration.sql
  └─ 20210630124758_create_search_delivery_tables/
    └─ migration.sql

✔ Generated Prisma Client (2.26.0) to ./node_modules/@prisma/client in 298ms
Running seed from "prisma/seed.js" ...
Result:
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Sites/api/prisma/seed.js
require() of ES modules is not supported.
require() of /Sites/api/prisma/seed.js from /Sites/api/[eval] is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename seed.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Sites/api/package.json.

Error: Command failed with exit code 1: node -e "
console.info('Result:')

const __seed = require('./prisma/seed.js')
const __keys = Object.keys(__seed)

async function runSeed() {
  // Execute "seed" named export or default export
  if (__keys && __keys.length) {
    if (__keys.indexOf('seed') !== -1) {
      return __seed.seed()
    } else if (__keys.indexOf('default') !== -1) {
      return __seed.default()
    }
  }
}

runSeed()
  .then(function (result) {
    if (result) {
      console.log(result)
    }
  })
  .catch(function (e) {
    console.error('Error from seed:')
    throw e
  })

```

Thanks for your reply

### Environment & setup

- OS: Mac OS
- Database: MySQL
- Node.js version: v14.16.1

### Prisma Version

```
2.26.0
```

**Comment by tomhoule** [comment]
Hi @benjaminviaud , thanks for reporting the problem. We are seeing problems with seed scripts because of different module systems and import setups with node, and I think it's going to be hard to fix. One thing that I always come back to would be a `prisma:seed` script in your package.json that migrate would just start as a separate process. Do you think that would work for your use case?

**Comment by benjaminviaud** [comment]
Hello @tomhoule,

Thanks for your reply.
Your solution throw the same error.
If I compare two build scripts 

2.22.1
```.js
....
if (detected.js) {
    console.info(`Running ${chalk_12.default.bold(`node "${detected.js}"`)} ...`);
    return await execa_12.default("node", [`"${detected.js}"`], {
      shell: true,
      stdio: "inherit"
    });
  }

....
```
2.26.0
```.js
....
 if (detected.js) {
    console.info(`Running seed from ${chalk_12.default.bold(`"${detected.js}"`)} ...`);
    return await execa_12.default("node", [`-e "${getSeedScript("JS", detected.js)}"`], {
      shell: true,
      stdio: "inherit"
    });
  }
...
```
getSeedScript function (2.26.0)
```.js
function getSeedScript(type, seedFilepath) {
    let script = `
console.info('Result:')

const __seed = require('./${seedFilepath}')
const __keys = Object.keys(__seed)

async function runSeed() {
  // Execute "seed" named export or default export
  if (__keys && __keys.length) {
    if (__keys.indexOf('seed') !== -1) {
      return __seed.seed()
    } else if (__keys.indexOf('default') !== -1) {
      return __seed.default()
    }
  }
}

runSeed()
  .then(function (result) {
    if (result) {
      console.log(result)
    }
  })
  .catch(function (e) {
    console.error('Error from seed:')
    throw e
  })
`;
    if (type === "TS") {
      script = `
// @ts-ignore
declare const require: any

${script}

export {}
`;
    }
    return script;
  }
```

I understand why you use getSeedScript for  ["An export named seed"](https://www.prisma.io/docs/guides/database/seed-database#requirements-for-seeding-with-typescript-or-javascript)
but why for ["Seeding your database with Javascript"](https://www.prisma.io/docs/guides/database/seed-database#seeding-your-database-with-javascript)
When I try to remove the getSeedScript function call in 2.26.0 it works fine.
The getSeedScript function call is not useful in case we use ["Seeding your database with Javascript"](https://www.prisma.io/docs/guides/database/seed-database#seeding-your-database-with-javascript)

Thanks for your reply

**Comment by pantharshit00** [comment]
Seeding is getting reworked so this might be already fixed: #8146

**Comment by cehenriques** [comment]
I'm also having issues running the Seed script directly:

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Running seed from prisma/seed.ts ...
/Users/chenriques/Documents/proj/[eval].ts:66
export {};
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (node:vm:100:7)
    at exec (/Users/chenriques/Documents/proj/node_modules/ts-node/src/repl.ts:251:18)
    at /Users/chenriques/Documents/proj/node_modules/ts-node/src/repl.ts:243:27
    at Array.reduce (<anonymous>)
    at _eval (/Users/chenriques/Documents/proj/node_modules/ts-node/src/repl.ts:242:18)
    at Object.evalCode (/Users/chenriques/Documents/proj/node_modules/ts-node/src/repl.ts:109:12)
    at evalAndExitOnTsError (/Users/chenriques/Documents/proj/node_modules/ts-node/src/bin.ts:457:26)
    at main (/Users/chenriques/Documents/proj/node_modules/ts-node/src/bin.ts:334:7)
    at Object.<anonymous> (/Users/chenriques/Documents/proj/node_modules/ts-node/src/bin.ts:477:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
Error: Command failed with exit code 1: ts-node --eval "
// @ts-ignore
declare const require: any


console.info('Result:')

const __seed = require('./prisma/seed.ts')
const __keys = Object.keys(__seed)

async function runSeed() {
  // Execute "seed" named export or default export
  if (__keys && __keys.length) {
    if (__keys.indexOf('seed') !== -1) {
      return __seed.seed()
    } else if (__keys.indexOf('default') !== -1) {
      return __seed.default()
    }
  }
}

runSeed()
  .then(function (result) {
    if (result) {
      console.log(result)
    }
  })
  .catch(function (e) {
    console.error('Error from seed:')
    throw e
  })


export {}
```

This was working before (not sure what was the last working version), and now it breaks running `db seed`.

**Comment by Jolg42** [comment]
🗒️ We heard the feedback and we are planning a redesign of `db seed` (currently planned to be released early September)

How it will work is that a `prisma.seed` property in the package.json of your project will be required if you want to use `prisma db seed`.

This property is where you will be able to put any command you want to execute your seed script.

More info/details & how to try it out now in:
https://github.com/prisma/prisma/issues/8732

**Comment by janpio** [comment]
The redesign of `db seed` was released with Prisma 3. Please try it, this problem should be gone.
