### ISSUE TITLE
Invalid `.env` file leads to confusing error message

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8051]
This was my `env` file because of bad copy/paste:
```
DATABASE_URL="postgresql://s...ane:zou...5@pg-db-provision.cm0mkpwj8arx.eu-central-1.rds.amazonaws.com:5432/emerald_jellyfish
"
```

Instead of an error telling me about this, I got:
```
C:\Users\Jan\Documents\throwaway\refActionsError>npx prisma db push
  prisma:loadEnv project root found at C:\Users\Jan\Documents\throwaway\refActionsError\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\refActionsError\.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 2: "
[dotenv][DEBUG] did not match key and value when parsing line 3:
Environment variables loaded from .env
  prisma:engines using NAPI: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +2ms
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\refActionsError\node_modules\@prisma\engines\query-engine-windows.exe +0ms
Error: Error: Get config: Schema Parsing P1012

error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
  -->  schema.prisma:3
   | 
 2 |   provider = "postgres"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1

    at getConfigBinary (C:\Users\Jan\Documents\throwaway\refActionsError\node_modules\prisma\build\index.js:27046:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.getConfig5 (C:\Users\Jan\Documents\throwaway\refActionsError\node_modules\prisma\build\index.js:26950:14)
    at async Object.getDbInfo (C:\Users\Jan\Documents\throwaway\refActionsError\node_modules\prisma\build\index.js:61419:20)
    at async Object.printDatasource (C:\Users\Jan\Documents\throwaway\refActionsError\node_modules\prisma\build\index.js:62849:20)
    at async DbPush2.parse (C:\Users\Jan\Documents\throwaway\refActionsError\node_modules\prisma\build\index.js:64378:7)
    at async main (C:\Users\Jan\Documents\throwaway\refActionsError\node_modules\prisma\build\index.js:110797:18)
```

**Comment by thebiglabasky** [comment]
That's a dotenv-related thing and it would be difficult to tell apart actual errors from warnings that are fine.
Dropping.

**Comment by thebiglabasky** [comment]
Potential improvement: make the dotenv parsing output more visible and better so people can spot that when debugging

**Comment by janpio** [comment]
By default there should be no warnings or errors from `dotenv`, unfortunately they are only surfacing this via `debug` level logging so it will be hard to react or even capture that I guess.
