### ISSUE TITLE
SQL Server: `migrate dev` (and `db push`) does not create a database

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8058]
This is the error message when you try to migrate a database that does not exist on SQL Server:

```
C:\Users\Jan\Documents\throwaway\sqlServerCycles>npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db" - SQL Server

Error: Migration engine error:
Performing a TLS handshake
Trusting the server certificate without validation.
TLS handshake successful
Turning TLS off after a login. All traffic from here on is not encrypted.
Cannot open database "mydb" requested by the login. The login failed.
Database error
Database does not exist: mydb
```

(We should probably have tests for all databases that ensure this works)

**Comment by tomhoule** [comment]
@Jolg42 I think the new error logging code has a problem, this is not the expected error message. I'll try to look into this today.

**Comment by tomhoule** [comment]
(looking into it currently)

**Comment by Jolg42** [comment]
Todo reconfirm if fixed after it gets to dev in ~20 minutes.

**Comment by janpio** [comment]
No change for `2.27.0-dev.34`:

```
...

+ prisma@2.27.0-dev.34
added 2 packages from 1 contributor and audited 4 packages in 6.057s
found 0 vulnerabilities


C:\Users\Jan\Documents\throwaway\sqlServerCycles>npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db" - SQL Server
Error: Migration engine error:
Performing a TLS handshake
Trusting the server certificate without validation.
TLS handshake successful
Turning TLS off after a login. All traffic from here on is not encrypted.
Cannot open database "repro_cycles2" requested by the login. The login failed.
Database error
Database does not exist: repro_cycles2
```

**Comment by Jolg42** [comment]
Sorry I think I posted to the wrong issue I wanted to post to `https://github.com/prisma/prisma/issues/8058`

**Comment by tomhoule** [comment]
So I wasn't planning to look into the SQL server part of this, only the error message handling. And that is done, so the WIP with me assigned is a bit misleading. I'll still take a look tomorrow and see where the problem comes from.

**Comment by tomhoule** [comment]
I did some testing in the context of https://github.com/prisma/prisma-engines/pull/2089 and the ME does try to create a database on `create-database` and returns a proper error when that happens. Maybe there is something in the CLI preventing that code from running?

**Comment by Jolg42** [comment]
Error with `DEBUG="*"`
```
Error: Error: Migration engine error:
Performing a TLS handshake
Trusting the server certificate without validation.
TLS handshake successful
Turning TLS off after a login. All traffic from here on is not encrypted.
Cannot open database "hellomssql" requested by the login. The login failed.
Database error
Database does not exist: hellomssql

    at Object.canConnectToDatabase (/Users/j42/Dev/prisma-esbuild/packages/sdk/dist/migrateEngineCommands.js:94:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.ensureDatabaseExists (/Users/j42/Dev/prisma-esbuild/packages/migrate/src/utils/ensureDatabaseExists.ts:118:22)
    at DbPush.parse (/Users/j42/Dev/prisma-esbuild/packages/migrate/src/commands/DbPush.ts:116:26)
    at main (/Users/j42/Dev/prisma-esbuild/packages/migrate/src/bin.ts:80:18)
```

**Comment by Jolg42** [comment]
Should be fixed when https://github.com/prisma/prisma-engines/pull/2133 drops

**Comment by Jolg42** [comment]
Status: Will be worked on next release, WIP PR https://github.com/prisma/prisma-engines/pull/2133

**Comment by Jolg42** [comment]
Just played with the CLI, needed to fix some logic but now I get this

In `2.29.0-dev.40` (and soon in 2.29)

First push
```
Prisma schema loaded from prisma/schema.prisma
Datasource "my_db" - SQL Server
Error: Migration engine error:
Performing a TLS handshake
Trusting the server certificate without validation.
TLS handshake successful
Turning TLS off after a login. All traffic from here on is not encrypted.
Database change from 'master' to 'master'
Changed database context to 'master'.
SQL collation change from None to windows-1252/windows-1252
Microsoft SQL Server version 4077846543
Packet size change from '4096' to '4096'
Starting a mssql connection.
Performing a TLS handshake
Trusting the server certificate without validation.
TLS handshake successful
Turning TLS off after a login. All traffic from here on is not encrypted.
Database change from 'sdfsd1' to 'master'
Changed database context to 'sdfsd1'.
SQL collation change from None to windows-1252/windows-1252
Microsoft SQL Server version 4077846543
Packet size change from '4096' to '4096'
Starting a mssql connection.
The specified schema name "dbo" either does not exist or you do not have permission to use it.
Database error
Error querying the database: 'The specified schema name "dbo" either does not exist or you do not have permission to use it.' on server 5af6d931d9fb executing  on line 1 (code: 2760, state: 1, class: 16)
```

Second push
```
Prisma schema loaded from prisma/schema.prisma
Datasource "my_db" - SQL Server

🚀  Your database is now in sync with your schema. Done in 411ms
```

So something is created but we cannot use it right away somehow?

**Comment by Jolg42** [comment]
Note: the error on first "push" comes from calling `create-database` command on the engine.

https://github.com/prisma/prisma/blob/fe3d63cc11678d756732ad14887eea62b2590c36/packages/sdk/src/migrateEngineCommands.ts#L249-L259
