### ISSUE TITLE
Error: readStream must be readable

### ISSUE THREAD

**Issue by emmarvpol** [prisma/prisma#8118]
### Bug description

Im reciving the following error when Im trying to do a simple query (prisma.user.findMany())

``` 
Error: readStream must be readable
    at createLineStream (/home/***/Documents/NextJs/***/node_modules/@prisma/client/runtime/index.js:3778:13)
    at Object.module2.exports.createStream (/home/***/Documents/NextJs/***/node_modules/@prisma/client/runtime/index.js:3768:14)
    at Object.byline [as default] (/home/***/Documents/NextJs/***/node_modules/@prisma/client/runtime/index.js:3763:28)
    at /home/***/Documents/NextJs/***/node_modules/@prisma/client/runtime/index.js:27657:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  clientVersion: '2.25.0'
}
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/***/Documents/NextJs/***/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x EAGAIN
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -11,
  code: 'EAGAIN',
  syscall: 'spawn /home/***/Documents/NextJs/***/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x',
  path: '/home/***/Documents/NextJs/***/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x',
  spawnargs: [ '--enable-raw-queries', '--port', '41969' ]`
```
### How to reproduce

npm run dev

### Prisma information
```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator client {
  provider = "prisma-client-js"
}

model Page {
  id      Int    @id @default(autoincrement())
  title   String
  slug    String
  content String
}

model User {
  id            Int       @id @default(autoincrement())
  name          String?
  email         String?   @unique
  password      String?
  emailVerified DateTime? @map(name: "email_verified")
  image         String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")
  updatedAt     DateTime  @default(now()) @map(name: "updated_at")
}

model Article {
  id          Int        @id @default(autoincrement())
  title       String
  slug        String     @unique
  body        String?
  description String?
  views       Int        @default(0)
  tags        String?
  createdAt   DateTime   @default(now()) @map(name: "created_at")
  updatedAt   DateTime   @default(now()) @map(name: "updated_at")
  category    Category[]
  categoryId  Int?
}

model Category {
  id       Int       @id @default(autoincrement())
  title    String
  articles Article[]
}
```
### Environment & setup

- OS: Manjaro
- Database: SQLite
- Node.js version: v16.3.0

### Prisma Version

```
prisma               : 2.26.0
@prisma/client       : 2.25.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 9b816b3aa13cc270074f172f30d6eda8a8ce867d (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 9b816b3aa13cc270074f172f30d6eda8a8ce867d
Studio               : 0.408.0

```

**Comment by pantharshit00** [comment]
I wasn't able to reproduce this. Can you please try purging your `node_modules` and installing it again?

Also, looks like your cli and client version is out of sync, please match those.

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
