### ISSUE TITLE
$queryRaw fails when passing bigint as parameter

### ISSUE THREAD

**Issue by meeq** [prisma/prisma#8121]
### Bug description

My Postgres database uses BigInt for identifiers, but `$queryRaw` fails loudly when I try to pass a `bigint` as a parameter:

```
Raw query failed. Code: `08P01`. Message: `db error: ERROR: insufficient data left in message`
```

### How to reproduce

From the Node REPL:

```js
await prisma.$queryRaw`SELECT ${1n}::bigint;`
```
```
Uncaught PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.queryRaw()` invocation:


  Raw query failed. Code: `08P01`. Message: `db error: ERROR: insufficient data left in message`
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at cb (/app/prisma-client/runtime/index.js:33896:17) {
  code: 'P2010',
  clientVersion: '2.26.0',
  meta: {
    code: '08P01',
    message: 'db error: ERROR: insufficient data left in message'
  }
}
```

Passing in a number does not fail, but reproduces https://github.com/prisma/prisma/issues/7395 (the value is not a `bigint`):
```js
await prisma.$queryRaw`SELECT ${1}::bigint;`
```
```
[ { int8: 1 } ]
```

### Expected behavior

Expected `1n` to be serialized as a Postgres `bigint`; expected query not to fail.

### Prisma information

This is reproducible without a schema

### Environment & setup

- OS: Alpine Linux 3.13
- Database: Postgres 13.3
- Node.js version: 14.17.1
- Prisma version: 2.26.0

### Prisma Version

```
npm exec prisma -v
6.14.11
```

**Comment by pantharshit00** [comment]
This is reproducible, we need to fix bigints in raw queries in general.

**Comment by nicholaschiang** [comment]
This is currently blocking for my [`tweetscape`](https://github.com/rooteco/tweetscape) project that [uses a lot of complex raw queries](https://github.com/rooteco/tweetscape/blob/develop/app/query.server.ts) that have `bigint` parameters. Are there any suggested workarounds to accurately query a `bigint` field while #12367 is still in development?

**Comment by rstrand** [comment]
> This is currently blocking for my [`tweetscape`](https://github.com/rooteco/tweetscape) project that [uses a lot of complex raw queries](https://github.com/rooteco/tweetscape/blob/develop/app/query.server.ts) that have `bigint` parameters. Are there any suggested workarounds to accurately query a `bigint` field while #12367 is still in development?

This is ugly but it works:
```js
await prisma.$queryRaw`SELECT ${1n.toString()}::text::bigint;`
```

**Comment by chrisvariety** [comment]
Confirmed this works in 3.14.0. You don't need to specify `::bigint`, just `WHERE id=${bigIntHere}` works as-is 🎉
