### ISSUE TITLE
PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by manhninh** [prisma/prisma#8182]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | darwin             |
| Prisma Client   | 2.26.0             |
| Query Engine    | query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d|
| Database        | undefined|

## Query
```
mutation {
  queryRaw(
    query: "X"
    parameters: "X"
  )
}
```

## Logs
```
client/query-engine-darwin are fine  +25s
  prisma:tryLoadEnv Environment variables loaded from /Users/manhninh91/Freelancer/masvigac/.env  
  prisma:client clientVersion: 2.26.0  
  prisma:client prisma.queryRaw(CALL vigac.sp_functions_duties_selectall(?, ?);, ["","0"])  
  prisma:client Prisma Client call:  
  prisma:engine Search for Query Engine in /Users/manhninh91/Freelancer/masvigac/node_modules/.prisma/client  
  prisma:engine { cwd: '/Users/manhninh91/Freelancer/masvigac/prisma' }  
  prisma:engine Search for Query Engine in /Users/manhninh91/Freelancer/masvigac/node_modules/.prisma/client  
  plusX Execution permissions of /Users/manhninh91/Freelancer/masvigac/node_modules/.prisma/client/query-engine-darwin are fine  
  plusX Execution permissions of /Users/manhninh91/Freelancer/masvigac/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '49787' ] }  
  prisma:engine stdout  Starting a mysql pool with 5 connections.  
  prisma:engine stdout  Fetched a connection from the pool  
  prisma:engine stdout  Started http server on http://127.0.0.1:49787  
  prisma:engine Search for Query Engine in /Users/manhninh91/Freelancer/masvigac/node_modules/.prisma/client  
  plusX Execution permissions of /Users/manhninh91/Freelancer/masvigac/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.26.0  
  prisma:engine Engine Version: query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  Fetched a connection from the pool  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43
index out of bounds: the len is 0 but the index is 0  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/manhninh91/Freelancer/masvigac/node_modules/@prisma/client/runtime/index.js:25782:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/Users/manhninh91/Freelancer/masvigac/prisma' }  
  prisma:engine Search for Query Engine in /Users/manhninh91/Freelancer/masvigac/node_modules/.prisma/client  
  plusX Execution permissions of /Users/manhninh91/Freelancer/masvigac/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '49791' ] }  
  prisma:engine stdout  Starting a mysql pool with 5 connections.  
  prisma:engine stdout  Fetched a connection from the pool  
  prisma:engine stdout  Started http server on http://127.0.0.1:49791  
  prisma:engine Search for Query Engine in /Users/manhninh91/Freelancer/masvigac/node_modules/.prisma/client  
  plusX Execution permissions of /Users/manhninh91/Freelancer/masvigac/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine stdout  Fetched a connection from the pool  
  prisma:engine Client Version: 2.26.0  
  prisma:engine Engine Version: query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43
index out of bounds: the len is 0 but the index is 0  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/manhninh91/Freelancer/masvigac/node_modules/@prisma/client/runtime/index.js:25782:24)
  prisma:engine       at Socket.emit (events.js:327:22)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1327:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
