### ISSUE TITLE
Error: Error in migration engine. Reason: [migration-engine/connectors/sql-migration-connector/src/sql_renderer/mssql_renderer.rs:394:9] not yet implemented: DROP TYPE [dbo].[syspolicy_target_filters_type] 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#8185]
Command: `prisma migrate reset --preview-feature`
Version: `2.22.1`
Binary Version: `60cc71d884972ab4e897f0277c4b84383dddaf6c`
Report: https://prisma-errors.netlify.app/report/13406 
OS: `x64 darwin 19.6.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_renderer/mssql_renderer.rs:394:9] not yet implemented: DROP TYPE [dbo].[syspolicy_target_filters_type]

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

    at ChildProcess.<anonymous> (/Users/<censored>/index.js:56818:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

Rust Stacktrace:
```
[migration-engine/connectors/sql-migration-connector/src/sql_renderer/mssql_renderer.rs:394:9] not yet implemented: DROP TYPE [dbo].[syspolicy_target_filters_type]
```

**Comment by tomhoule** [comment]
It's from 2.22. For now just check if the `todo!()` that triggered the panic is still there. Probably not, then we can close this issue.

**Comment by tomhoule** [comment]
https://prisma-errors.netlify.app/report/13409
