### ISSUE TITLE
Error: Error in migration engine. Reason: [migration-engine/connectors/sql-migration-connector/src/sql_schema_calculator/sql_schema_calculator_flavour.rs:34:9] internal error: entered unreachable code: unreachable enum_column_type 

### ISSUE THREAD

**Issue by tomhoule** [prisma/prisma#8188]
Command: `prisma migrate dev --name unique`
Version: `2.26.0`
Binary Version: `9b816b3aa13cc270074f172f30d6eda8a8ce867d`
Report: https://prisma-errors.netlify.app/report/13408 
OS: `x64 darwin 20.3.0`

JS Stacktrace:
```
Error: Error in migration engine.
Reason: [migration-engine/connectors/sql-migration-connector/src/sql_schema_calculator/sql_schema_calculator_flavour.rs:34:9] internal error: entered unreachable code: unreachable enum_column_type

Please create an issue with your `schema.prisma` at 
https://github.com/prisma/prisma/issues/new

    at ChildProcess.<anonymous> (node_modules/prisma/build/index.js:55980:23)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
```

Rust Stacktrace:
```
[migration-engine/connectors/sql-migration-connector/src/sql_schema_calculator/sql_schema_calculator_flavour.rs:34:9] internal error: entered unreachable code: unreachable enum_column_type
```

**Comment by tomhoule** [comment]
Can't reproduce, I suspect something fishy with connection strings.

**Comment by pantharshit00** [comment]
We should wait for a report here from a user. We can't get a connection string from error reporting.

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this solved.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
