### ISSUE TITLE
Node-API: Flaky `disconnect-race` test

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8196]
https://buildkite.com/prisma/prisma2-test/builds/8376#ff74c1dc-1b3b-497a-996a-b6af0f95e147/178-1004

```
[2021-07-09T12:28:08Z] Summary of all failing tests
[2021-07-09T12:28:08Z]  FAIL  src/__tests__/integration/happy/disconnect-race/test.ts
[2021-07-09T12:28:08Z]   ● disconnect-race
[2021-07-09T12:28:08Z]
[2021-07-09T12:28:08Z]
[2021-07-09T12:28:08Z]     Invalid `prisma.user.findMany()` invocation in
[2021-07-09T12:28:08Z]     /app/src/packages/client/src/__tests__/integration/happy/disconnect-race/test.ts:9:31
[2021-07-09T12:28:08Z]
[2021-07-09T12:28:08Z]        6
[2021-07-09T12:28:08Z]        7 await prisma.user.findMany()
[2021-07-09T12:28:08Z]        8 prisma.$disconnect()
[2021-07-09T12:28:08Z]     →  9 const a = await prisma.user.findMany(
[2021-07-09T12:28:08Z]       Engine is not yet connected.
[2021-07-09T12:28:08Z]        0: user_facing_errors::Error::new_non_panic_with_current_backtrace
[2021-07-09T12:28:08Z]        1: query_engine::error::<impl core::convert::From<query_engine::error::ApiError> for user_facing_errors::Error>::from
[2021-07-09T12:28:08Z]        2: query_engine::error::<impl core::convert::From<query_engine::error::ApiError> for napi::error::Error>::from
[2021-07-09T12:28:08Z]        3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
[2021-07-09T12:28:08Z]        4: tokio::runtime::task::core::CoreStage<T>::poll
[2021-07-09T12:28:08Z]        5: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
[2021-07-09T12:28:08Z]        6: tokio::runtime::task::harness::poll_future
[2021-07-09T12:28:08Z]        7: tokio::runtime::task::harness::Harness<T,S>::poll
[2021-07-09T12:28:08Z]        8: std::thread::local::LocalKey<T>::with
[2021-07-09T12:28:08Z]        9: tokio::runtime::thread_pool::worker::Context::run_task
[2021-07-09T12:28:08Z]       10: tokio::runtime::thread_pool::worker::Context::run
[2021-07-09T12:28:08Z]       11: tokio::macros::scoped_tls::ScopedKey<T>::set
[2021-07-09T12:28:08Z]       12: tokio::runtime::thread_pool::worker::run
[2021-07-09T12:28:08Z]       13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
[2021-07-09T12:28:08Z]       14: std::panicking::try
[2021-07-09T12:28:08Z]       15: tokio::runtime::task::harness::Harness<T,S>::poll
[2021-07-09T12:28:08Z]       16: std::sys_common::backtrace::__rust_begin_short_backtrace
[2021-07-09T12:28:08Z]       17: core::ops::function::FnOnce::call_once{{vtable.shim}}
[2021-07-09T12:28:08Z]       18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-07-09T12:28:08Z]
[2021-07-09T12:28:08Z]       at ../../../../rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
[2021-07-09T12:28:08Z]             <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
[2021-07-09T12:28:08Z]       at ../../../../rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1546:9
[2021-07-09T12:28:08Z]             std::sys::unix::thread::Thread::new::thread_start
[2021-07-09T12:28:08Z]       at ../../../../rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys/unix/thread.rs:71:17
[2021-07-09T12:28:08Z]         19: start_thread
[2021-07-09T12:28:08Z]         20: clone
[2021-07-09T12:28:08Z]       at cb (src/runtime/PrismaClientFetcher.ts:172:17)
[2021-07-09T12:28:08Z]       at Object.<anonymous> (src/__tests__/integration/happy/disconnect-race/test.ts:9:13)
```

Happened once at least, let's observe if it happens more often.

**Comment by janpio** [comment]
Not observed since then any more.
