### ISSUE TITLE
PANIC in query-engine\connectors\sql-query-connector\src\query_ext.rs:58:43index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by beegeeta** [prisma/prisma#8206]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.17.1           | 
| OS              | windows            |
| Prisma Client   | 2.22.1             |
| Query Engine    | query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c|
| Database        | undefined|

## Query
```
mutation {
  queryRaw(
    query: "X"
    parameters: "X"
  )
}
```

## Logs
```
  prisma:tryLoadEnv Environment variables loaded from C:\Users\arm81\WebstormProjects\anasis-ayutthaya\.env  
  prisma:tryLoadEnv Environment variables loaded from C:\Users\arm81\WebstormProjects\anasis-ayutthaya\.env  
  prisma:client clientVersion: 2.22.1  
  prisma:engine Search for Query Engine in C:\Users\arm81\WebstormProjects\anasis-ayutthaya\node_modules\.prisma\client  
  prisma:engine { cwd: 'C:\\Users\\arm81\\WebstormProjects\\anasis-ayutthaya\\prisma' }  +6s
  prisma:engine Search for Query Engine in C:\Users\arm81\WebstormProjects\anasis-ayutthaya\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '58456' ] }  
  prisma:engine stdout  Starting a mysql pool with 13 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:58456  
  prisma:engine Search for Query Engine in C:\Users\arm81\WebstormProjects\anasis-ayutthaya\node_modules\.prisma\client  
  prisma:engine Client Version: 2.22.1  
  prisma:engine Engine Version: query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c  
  prisma:engine Active provider: mysql  
  prisma:client prisma.queryRaw(call usp_Staff_Validate('10012', 'arm813@hotmail.com'), [])  +21s
  prisma:client Prisma Client call:  
  prisma:engine stdout  PANIC in query-engine\connectors\sql-query-connector\src\query_ext.rs:58:43
index out of bounds: the len is 0 but the index is 0  +15s
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:58456
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 58456
  prisma:engine   }
  prisma:engine }  
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd: 'C:\\Users\\arm81\\WebstormProjects\\anasis-ayutthaya\\prisma' }  
  prisma:engine Search for Query Engine in C:\Users\arm81\WebstormProjects\anasis-ayutthaya\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '51650' ] }  
  prisma:engine stdout  Starting a mysql pool with 13 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:51650  
  prisma:engine Search for Query Engine in C:\Users\arm81\WebstormProjects\anasis-ayutthaya\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\connectors\sql-query-connector\src\query_ext.rs:58:43
index out of bounds: the len is 0 but the index is 0  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by beegeeta** [comment]
This is the response from call store procedure in mysql 
call usp_Staff_Validate('xxx', 'xxx')

**Comment by pantharshit00** [comment]
Can you share the database schema and the contents of the stored procedure so that we can try to reproduce this?

**Comment by janpio** [comment]
Ping @beegeeta

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
