### ISSUE TITLE
Possible interaction between referential actions and raw queries?

### ISSUE THREAD

**Issue by Sytten** [prisma/prisma#8232]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.17.1           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.26.0             |
| Query Engine    | query-engine 9b816b3aa13cc270074f172f30d6eda8a8ce867d|
| Database        | undefined|

## Description
It seems there might be an unexpected interaction between FK violation and raw queries?
It's the `Error in PostgreSQL connection: Error { kind: Closed, cause: None }` again which I didn't see for a while since I use a retry middleware.

## Logs
```
0T08:21:09.726Z prisma:client Prisma Client call:
prisma:client prisma.queryRaw(
    SELECT
      start_ts AS timestamp,
      COUNT(ticket.id) AS value
    FROM
      generate_series($1::TIMESTAMP, $2::TIMESTAMP, $3::TEXT::INTERVAL) AS start_ts
      ... --Private part
    GROUP by start_ts
    ORDER BY start_ts
  , [{"prisma__type":"date","prisma__value":"2021-03-01T06:00:00.000Z"},{"prisma__type":"date","prisma__value":"2021-07-11T05:00:00.000Z"},"1 day",29,"1 day"])
prisma:client Prisma Client call:
prisma:client prisma.queryRaw(
    SELECT
      start_ts AS timestamp,
      COUNT(ticket.id) AS value
    FROM
      generate_series($1::TIMESTAMP, $2::TIMESTAMP, $3::TEXT::INTERVAL) AS start_ts
       ... --Private part
    GROUP by start_ts
    ORDER BY start_ts
  , [{"prisma__type":"date","prisma__value":"2021-03-01T06:00:00.000Z"},{"prisma__type":"date","prisma__value":"2021-07-11T05:00:00.000Z"},"1 day",2266,29,"1 day"])
prisma:client Prisma Client call:
prisma:client prisma.queryRaw(
    SELECT
      start_ts AS timestamp,
      COUNT(ticket.id) AS value
    FROM
      generate_series($1::TIMESTAMP, $2::TIMESTAMP, $3::TEXT::INTERVAL) AS start_ts
       ... --Private part
    GROUP by start_ts
    ORDER BY start_ts
  , [{"prisma__type":"date","prisma__value":"2021-03-01T05:00:00.000Z"},{"prisma__type":"date","prisma__value":"2021-07-11T04:00:00.000Z"},"1 day",359,"1 day"])
prisma:client Prisma Client call:
prisma:client prisma.queryRaw(
    SELECT
      start_ts AS timestamp,
      COUNT(ticket.id) AS value
    FROM
      generate_series($1::TIMESTAMP, $2::TIMESTAMP, $3::TEXT::INTERVAL) AS start_ts
       ... --Private part
    GROUP by start_ts
    ORDER BY start_ts
  , [{"prisma__type":"date","prisma__value":"2021-03-01T05:00:00.000Z"},{"prisma__type":"date","prisma__value":"2021-07-11T04:00:00.000Z"},"1 day",382,"1 day"])
prisma:client Prisma Client call:
prisma:engine {
  error: Error: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: Some(KnownError { message: "Foreign key constraint failed on the field: `ticket_refund_refund_id_fkey (index)`", meta: Object({"field_name": String("ticket_refund_refund_id_fkey (index)")}), error_code: "P2003" }), kind: ForeignKeyConstraintViolation { constraint: Index("ticket_refund_refund_id_fkey") } })
      at /app/node_modules/.prisma/client/runtime/index.js:28009:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
}
prisma:engine {
  error: Error: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: Some(KnownError { message: "Foreign key constraint failed on the field: `ticket_refund_refund_id_fkey (index)`", meta: Object({"field_name": String("ticket_refund_refund_id_fkey (index)")}), error_code: "P2003" }), kind: ForeignKeyConstraintViolation { constraint: Index("ticket_refund_refund_id_fkey") } })
      at /app/node_modules/.prisma/client/runtime/index.js:28009:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
}
prisma:engine {
  error: Error: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: Some(KnownError { message: "Foreign key constraint failed on the field: `ticket_refund_refund_id_fkey (index)`", meta: Object({"field_name": String("ticket_refund_refund_id_fkey (index)")}), error_code: "P2003" }), kind: ForeignKeyConstraintViolation { constraint: Index("ticket_refund_refund_id_fkey") } })
      at /app/node_modules/.prisma/client/runtime/index.js:28009:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
}
```

**Comment by pantharshit00** [comment]
Hmm, let me know if you saw this again after this. The information provided and the log trace aren't enough to narrow this down.

**Comment by Sytten** [comment]
Yeah I need to try to create a repro, its on my todo for this week. Thanks for the reminder!

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this solved.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
