### ISSUE TITLE
MongoDB "Cannot create namespace"

### ISSUE THREAD

**Issue by asmuxlow** [prisma/prisma#8305]
### Bug description

Since I could not get the Prisma MongoDB tutorial working with the DB provided, I used an existing Atlas instance which has Replica Sets configured. I even created a collection in case Prisma was unable to create a collection (blog). However, on first run through of index.ts on the "create post" instance, Prisma failed with the following error:

```
PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: 
Invalid `prisma.post.create()` invocation in
/Users/ali/Documents/Work/ViaVid/Prisma/blog/index.ts:9:21

   6 await prisma.$connect()
   7 
   8 // Create the first post
→  9 await prisma.post.create(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawError { code: "263", message: "Cannot create namespace dev101.Post in multi-document transaction." } })
    at cb (/Users/ali/Documents/Work/ViaVid/Prisma/blog/node_modules/@prisma/client/runtime/index.js:34804:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  clientVersion: '2.27.0'
}

```

### How to reproduce

1. Change MongoDB to using a DB with a replica set
2. Run everything as per the example
3. npx ts-node index.ts

### Expected behavior

Expected posts to write to DB and to have them listed.

### Prisma information

```
// We want to connect to the MongoDB datasource
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

// We want to generate a typescript client
// Since mongodb is a preview feature, we'll enable that.
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongodb"]
}

// Create our post schema. All posts have a title, slug and body.
// The id attributes tell Prisma it's a primary key and to generate 
// object ids by default when we insert posts.
model Post {
  id    String @id @default(dbgenerated()) @map("_id") @db.ObjectId
  slug  String @unique
  title String
  body  String
}

```
### Environment & setup

- OS: MacOSX 11.4
- Database: MongoDB 4.2.15, DB dev101 collection (pre-created manually) blog
- Node.js version: 14.17.3

### Prisma Version

```
2.27.0
```

**Comment by pantharshit00** [comment]
Hmm, I am unable to reproduce this. Can you please provide your code in a git repo so that we can make sure we are trying to reproduce this correctly?

**Comment by patwritescode** [comment]
@pantharshit00 Just ran into this myself. Pretty sure it's because `create` in Prisma uses multi document transaction and 4.2 and below cannot create collections in 4.2 or below. This is allowed in 4.4 and above, though.

https://docs.mongodb.com/manual/reference/limits/#mongodb-limit-Multi-document-Transactions

**Comment by pantharshit00** [comment]
Yeah, we use transactions everywhere in the connector. I guess we can close this as Mongo 4.4+ is required for use with Prisma.

**Comment by janpio** [comment]
We should have a better errror message when using MondoDB 4.2 then?

**Comment by patwritescode** [comment]
@janpio I just opened a PR to update the supported db tables. https://github.com/prisma/docs/pull/2311

**Comment by matthewmueller** [comment]
Re-opening since 4.2 is a version we'd like to support.

**Comment by janpio** [comment]
From the description and the date above, I think it was https://www.notion.so/prismaio/Getting-Started-with-MongoDB-and-Prisma-58b41c67eb554787944c600d2239801f @matthewmueller

**Comment by patwritescode** [comment]
I don’t have the exact query on hand anymore but it was pretty much what @janpio linked.

**Comment by chrisschaub** [comment]
Why keep this open for an old version 4.2 of Mongodb? Most shops have moved to 4.4 or 5, and the upgrade from 4.2 to 4 4 is pretty painless which resolves this issue.

**Comment by janpio** [comment]
Because not _everyone_ has moved on (quite a few are actually on 4.0 or even earlier), and in theory it should not be a problem to support MongoDB 4.2 with the functionality we require. It's one of those things people usually like Prisma for, so we'll see if we can make it happen. (Usually Prisma MongoDB works perfectly fine with 4.2. by the way, this is a very specific case and we have no reproduction - so might not even be real any more.)

**Comment by patwritescode** [comment]
the 4.2 or lower issue really should only happen when you start with a new database w/o the collections created. Prisma tries to create the collections but can't because 4.2 and lower don't support creating collections in a transaction and it seems most or all of prismas calls are in a transaction scope. if you create your collections w/ migrate beforehand this doesnt seem to be an issue.

**Comment by janpio** [comment]
Thanks @patwritescode, that should be enough information then for us to reproduce the error reliably.

**Comment by patwritescode** [comment]
Yes. That situation should reproduce the issue.

**Comment by janpio** [comment]
I can confirm this bug:

```
PS C:\Users\Jan\Documents\throwaway\8305> npx ts-node index.ts
PrismaClientUnknownRequestError: 
Invalid `prisma.post.create()` invocation in
C:\Users\Jan\Documents\throwaway\8305\index.ts:9:21

   6 await prisma.$connect()
   7
   8 // Create the first post
→  9 await prisma.post.create(
  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: RawDatabaseError { code: "263", message: "Cannot create namespace test.Post in multi-document transaction." } })
    at Object.request (C:\Users\Jan\Documents\throwaway\8305\node_modules\@prisma\client\runtime\index.js:39822:15)
    at async PrismaClient._request (C:\Users\Jan\Documents\throwaway\8305\node_modules\@prisma\client\runtime\index.js:40646:18)
    at async main (C:\Users\Jan\Documents\throwaway\8305\index.ts:9:3) {
  clientVersion: '3.11.0'
}
```

I create a dedicated MongoDB 4.2 cluster on MongoDB Atlas, then followed the steps in https://www.notion.so/prismaio/Getting-Started-with-MongoDB-and-Prisma-58b41c67eb554787944c600d2239801f

**Comment by janpio** [comment]
Seems this is generally worked around by a) writing the data outside of a transaction or b) creating the collection explicitly outside the transaction: https://jira.mongodb.org/browse/GODRIVER-1649?focusedCommentId=3210346&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3210346

**Comment by janpio** [comment]
@matthewmueller reminded me that we actually have the perfect workaround for this `db push`:

```
PS C:\Users\Jan\Documents\throwaway\8305> npx prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db"
Applying the following changes:

[+] Collection `Post`
[+] Unique index `Post_slug_key` on ({"slug":1})


Your database is now in sync with your schema. Done in 490ms

✔ Generated Prisma Client (3.11.0 | library) to .\node_modules\@prisma\client in 138ms

PS C:\Users\Jan\Documents\throwaway\8305> npx ts-node .\index.ts 
[
  {
    id: '623271d6b4bc854088be387b',
    slug: 'prisma-loves-mongodb',
    title: 'Prisma <3 MongoDB',
    body: "This is my first post. Isn't MongoDB + Prisma awesome?!"
  },
  {
    id: '623271d6b4bc854088be387c',
    slug: 'prisma-is-type-safe-mongodb-client',
    title: 'Prisma is a type-safe MongoDB client',
    body: 'This is my second post.'
  }
]
```

So running `prisma db push` creates the collection (and the index) so that when you run the script, the collection exists and data can be inserted.

**Comment by Jolg42** [comment]
Can reproduce in our internal dev version `4.4.0-dev.27` using docker image for MongoDB 4.2

**Comment by domharrington** [comment]
I fixed this in our CI environment by using mongodb v4.4. It works fine locally with 4.2 though, I'm guessing because the collections are already in place when I'm doing anything that will require them.
