### ISSUE TITLE
`Error: P1012 Introspection failed as your current Prisma schema file is invalid` when space is added after `{`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8320]
This schema works:

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialActions"]
}

datasource db {
  provider = "sqlite"
  url = "foo"
}
```

And this schema fails:

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialActions"]
}

datasource db { 
  provider = "sqlite"
  url = "foo"
}
```

with this command and error message:

```
$ npx prisma introspect --url "postgresql://prisma:fCaD...s42L@introsp...rivate.clfeqqifnebj.eu-west-1.rds.amazonaws.com:5432/aut...ed?schema=public" --print
Prisma schema loaded from schema.prisma
Datasource "db"

Error: P1012 Introspection failed as your current Prisma schema file is invalid

Please fix your current schema manually, use prisma validate to confirm it is valid and then run this command again.
Or run this command with the --force flag to ignore your current schema and overwrite it. All local modifications will be lost.
```

This is the path between the two:

```patch
6c6
< datasource db {
---
> datasource db { 
```

So it seems adding an empty space after the `{` of the `datasource` makes `prisma introspect --url --print` fail.

**Comment by janpio** [comment]
The same is true for adding a space in front of `datasource` in the schema above:

```
generator client {
  provider = "prisma-client-js"
  previewFeatures = ["referentialActions"]
}

 datasource db {
  provider = "sqlite"
  url = "foo"
}
```

**Comment by tomhoule** [comment]
I can't reproduce this in datamodel tests. Will try again end-to-end with the CLI.

**Comment by pantharshit00** [comment]
I also wasn't able to reproduce.

**Comment by janpio** [comment]
This is reproducible for me on Windows with Prisma 2.27.0. Here is the output with `DEBUG=*`:

```
C:\Users\Jan\Documents\throwaway\repro8320  (repro8320@1.0.0)
λ npx prisma introspect --url "postgresql://prisma:fCaD...s42L@introsp...rivate.clfeqqifnebj.eu-west-1.rds.amazonaws.com:5432/aut...ed?schema=public" --print
  prisma:loadEnv project root found at C:\Users\Jan\Documents\throwaway\repro8320\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\repro8320\.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # Environment variables declared in this file are automatically made available to Prisma.
[dotenv][DEBUG] did not match key and value when parsing line 2: # See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables
[dotenv][DEBUG] did not match key and value when parsing line 3:
[dotenv][DEBUG] did not match key and value when parsing line 4: # Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server (Preview) and MongoDB (Preview).
[dotenv][DEBUG] did not match key and value when parsing line 5: # See the documentation for all the connection string options: https://pris.ly/d/connection-strings
[dotenv][DEBUG] did not match key and value when parsing line 6:
Environment variables loaded from .env
  prisma:engines using Node API: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +2ms
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig Using Query Engine Binary at: C:\Users\Jan\Documents\throwaway\repro8320\node_modules\@prisma\engines\query-engine-windows.exe +0ms
Datasource "db"
  prisma:introspectionEngine:rpc starting introspection engine with binary: C:\Users\Jan\Documents\throwaway\repro8320\node_modules\@prisma\engines\introspection-engine-windows.exe +0ms
  prisma:introspectionEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"introspect","params":[{"schema":"datasource db {\n  provider = \"postgresql\"\n  url      = \"postgresql://prisma:fCaD...s42L@introsp...rivate.clfeqqifnebj.eu-west-1.rds.amazonaws.com:5432/aut...ed?schema=public\"\n}generator client {\n  provider = \"prisma-client-js\"\n  previewFeatures = [\"referentialActions\"]\n}\n\ndatasource db { \n  provider = \"sqlite\"\n  url = \"foo\"\n}\n\nmodel User {\n  id    Int     @id @default(autoincrement())\n  email String  @unique\n  name  String?\n}"}]} +6ms
  prisma:introspectionEngine:rpc {
  prisma:introspectionEngine:rpc   jsonrpc: '2.0',
  prisma:introspectionEngine:rpc   error: {
  prisma:introspectionEngine:rpc     code: 4466,
  prisma:introspectionEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:introspectionEngine:rpc     data: {
  prisma:introspectionEngine:rpc       is_panic: false,
  prisma:introspectionEngine:rpc       message: 'error: Error validating datasource `db`: You defined more than one datasource. This is not allowed yet because support for multiple databases has not been implemented yet.\n' +
  prisma:introspectionEngine:rpc         '  -->  schema.prisma:1\n' +
  prisma:introspectionEngine:rpc         '   | \n' +
  prisma:introspectionEngine:rpc         '   | \n' +
  prisma:introspectionEngine:rpc         ' 1 | datasource db {\n' +
  prisma:introspectionEngine:rpc         ' 2 |   provider = "postgresql"\n' +
  prisma:introspectionEngine:rpc         ' 3 |   url      = "postgresql://prisma:fCaD...s42L@introsp...rivate.clfeqqifnebj.eu-west-1.rds.amazonaws.com:5432/aut...ed?schema=public"\n' +
  prisma:introspectionEngine:rpc         ' 4 | }generator client {\n' +
  prisma:introspectionEngine:rpc         '   | \n' +
  prisma:introspectionEngine:rpc         'error: Error validating datasource `db`: You defined more than one datasource. This is not allowed yet because support for multiple databases has not been implemented yet.\n' +
  prisma:introspectionEngine:rpc         '  -->  schema.prisma:9\n' +
  prisma:introspectionEngine:rpc         '   | \n' +
  prisma:introspectionEngine:rpc         ' 8 | \n' +
  prisma:introspectionEngine:rpc         ' 9 | datasource db { \n' +
  prisma:introspectionEngine:rpc         '10 |   provider = "sqlite"\n' +
  prisma:introspectionEngine:rpc         '11 |   url = "foo"\n' +
  prisma:introspectionEngine:rpc         '12 | }\n' +
  prisma:introspectionEngine:rpc         '   | \n',
  prisma:introspectionEngine:rpc       meta: [Object],
  prisma:introspectionEngine:rpc       error_code: 'P1012'
  prisma:introspectionEngine:rpc     }
  prisma:introspectionEngine:rpc   },
  prisma:introspectionEngine:rpc   id: 1
  prisma:introspectionEngine:rpc } +17ms

Error: Error: P1012 Introspection failed as your current Prisma schema file is invalid

Please fix your current schema manually, use prisma validate to confirm it is valid and then run this command again.
Or run this command with the --force flag to ignore your current schema and overwrite it. All local modifications will be lost.

    at DbPull2.parse (C:\Users\Jan\Documents\throwaway\repro8320\node_modules\prisma\build\index.js:64697:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (C:\Users\Jan\Documents\throwaway\repro8320\node_modules\prisma\build\index.js:110386:18)
```

Reproduction repository: https://github.com/janpio/repro8320

(This works with the exact same command with the invalid data source URL I posted above, so you can really check out the repo, run `npm install` and then execute `npx prisma introspect --url "postgresql://prisma:fCaD...s42L@introsp...rivate.clfeqqifnebj.eu-west-1.rds.amazonaws.com:5432/aut...ed?schema=public" --print`)

**Comment by thebiglabasky** [comment]
We'll pick this back up as soon as the team has capacity

**Comment by tomhoule** [comment]
Just saw @janpio 's comment, and it makes me think it could have something to do with windows line endings (`\r\n`).

**Comment by tomhoule** [comment]
It could also be a pest bug that has been reported/fixed, we should investigate.

**Comment by pantharshit00** [comment]
Reproducible on windows with the repository.
