### ISSUE TITLE
PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22Could not figure out an ID in create

### ISSUE THREAD

**Issue by Sotatek-ManhLuong** [prisma/prisma#8345]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.17.2           | 
| OS              | debian-openssl-1.1.x|
| Prisma Client   | 2.27.0             |
| Query Engine    | query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb|
| Database        | undefined|

## Query
```
mutation {
  upsertOnetd_union_user_bouncemail(
    create: {
      email: "X"
    }
    where: {
      email: "X"
    }
    update: {
      count: {
        increment: 5
      }
    }
  ) {
    id
    email
    count
    createMs
    updateMs
    deleteMs
  }
}
```

## Logs
```
e in /home/manhluong/sotatek/sendy-portal-batch-bouncemail/node_modules/.prisma/client  
  plusX Execution permissions of /home/manhluong/sotatek/sendy-portal-batch-bouncemail/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /home/manhluong/sotatek/sendy-portal-batch-bouncemail/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '33937' ] }  
  prisma:engine stdout  Starting a mysql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:33937  
  prisma:engine Search for Query Engine in /home/manhluong/sotatek/sendy-portal-batch-bouncemail/node_modules/.prisma/client  
  plusX Execution permissions of /home/manhluong/sotatek/sendy-portal-batch-bouncemail/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine Client Version: 2.27.0  
  prisma:engine Engine Version: query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22
Could not figure out an ID in create  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/home/manhluong/sotatek/sendy-portal-batch-bouncemail/node_modules/@prisma/client/runtime/index.js:26686:24)
  prisma:engine       at Socket.emit (events.js:387:35)
  prisma:engine       at Socket.emit (domain.js:470:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1317:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:33937
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  prisma:engine     errno: -111,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 33937
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   cwd: '/home/manhluong/sotatek/sendy-portal-batch-bouncemail/src/prisma'
  prisma:engine }  
  prisma:engine Search for Query Engine in /home/manhluong/sotatek/sendy-portal-batch-bouncemail/node_modules/.prisma/client  
  plusX Execution permissions of /home/manhluong/sotatek/sendy-portal-batch-bouncemail/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '38979' ] }  
  prisma:engine stdout  Starting a mysql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:38979  
  prisma:engine Search for Query Engine in /home/manhluong/sotatek/sendy-portal-batch-bouncemail/node_modules/.prisma/client  
  plusX Execution permissions of /home/manhluong/sotatek/sendy-portal-batch-bouncemail/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine Client Version: 2.27.0  
  prisma:engine Engine Version: query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22
Could not figure out an ID in create  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/home/manhluong/sotatek/sendy-portal-batch-bouncemail/node_modules/@prisma/client/runtime/index.js:26686:24)
  prisma:engine       at Socket.emit (events.js:387:35)
  prisma:engine       at Socket.emit (domain.js:470:12)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1317:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by pantharshit00** [comment]
Hello! Can you please provide a minimal reproduction for the above crash? Unfortunately the automatically collected information in the issue does not give us much to go with here - we will need a bit more information. What were you doing? Can you share the code and schema that was active?

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this closed.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
