### ISSUE TITLE
Got a misleading error while trying to update a many-to-many relation

### ISSUE THREAD

**Issue by faisalsayed10** [prisma/prisma#8390]
### Bug description

I was working with many-to-many relations and I got this error 

```
PrismaClientValidationError:
Invalid `prisma.list.update()` invocation:

{
  where: {
    id: 'd43fbfa6-2516-444c-ade6-1be2a43921d9'
  },
  data: {
    books: {
    ~~~~~
      connectOrCreate: {
        where: {
          gbookId: 'this is google books id'
        },
        create: {
          gbookId: 'this is google books id',
          title: 'this is a book title',
          authors: [
            'book.authors',
            'second author'
          ],
          publishedDate: 'book.publishedDate 1998',
          previewLink: 'https://book.previewLink',
          imageLinks: [
            '1234',
            44
          ]
        }
      }
    }
  },
  include: {
    books: true
  }
}

Unknown arg `books` in data.books for type ListUncheckedUpdateInput. Did you mean `id`? Available args:
type ListUncheckedUpdateInput {
  id?: String | StringFieldUpdateOperationsInput
  createdAt?: DateTime | DateTimeFieldUpdateOperationsInput
  updatedAt?: DateTime | DateTimeFieldUpdateOperationsInput
  title?: String | StringFieldUpdateOperationsInput
  type?: ListType | EnumListTypeFieldUpdateOperationsInput
  description?: String | StringFieldUpdateOperationsInput
  authorId?: Int | IntFieldUpdateOperationsInput
}


    at Document.validate (/Users/fayd/Projects/libook/node_modules/@prisma/client/runtime/index.js:32626:19)
    at NewPrismaClient._executeRequest (/Users/fayd/Projects/libook/node_modules/@prisma/client/runtime/index.js:34733:17)
    at consumer (/Users/fayd/Projects/libook/node_modules/@prisma/client/runtime/index.js:34678:23)
    at /Users/fayd/Projects/libook/node_modules/@prisma/client/runtime/index.js:34680:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (/Users/fayd/Projects/libook/node_modules/@prisma/client/runtime/index.js:34680:25)
    at Object.then (/Users/fayd/Projects/libook/node_modules/@prisma/client/runtime/index.js:34788:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  clientVersion: '2.26.0'
}
```
and it said that the argument `books` is unknown even though it was clearly defined in `schema.prisma`. later, after investigating further in the issue, I found out that it was due to accidentally passing an `int` in a `string[]` inside the `book` object. Though the error did not emphasize on this mistake but instead threw a misleading error that `books` is not an argument.

### How to reproduce

You can see the full details in this [discussion here](https://github.com/prisma/prisma/discussions/8377)

### Expected behavior

I was expecting a better error message which actually pointed me that a wrong data type was passed.

### Prisma information

```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model List {
  id          String   @id @default(uuid())
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  title       String
  type        ListType @default(normal)
  description String   @default("")
  books       Book[]

  @@map("lists")
}

model Book {
  id                  String   @id @default(uuid())
  gbookId             String   @unique @map(name: "gbook_id")
  title               String
  authors             String[]
  publishedDate       String   @map(name: "published_date")
  previewLink         String   @map(name: "preview_link")
  imageLinks          String[] @map(name: "image_links")
  lists               List[]

  @@map("books")
}

enum ListType {
  normal
  wantToRead
  currentlyReading
  alreadyRead
}
```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: 14.17.1

### Prisma Version

```
2.26.0
```

**Comment by OmanCoding** [comment]
I have the same problem with .create() and connect.
Using Mysql.
