### ISSUE TITLE
Query engine binary could not be found after 2.24 - Prisma / Serverless / Next.js

### ISSUE THREAD

**Issue by bozanbozkurt** [prisma/prisma#8393]
### Bug description

Updating prisma and @prisma/client dependencies from 2.23 to 2.24 causes query engine binary could not be found error on Prisma - Serverless - Next.js deployment.

'Query engine binary could not be found' issue for serverless was previously addressed on [5392](https://github.com/prisma/prisma/issues/5392). 
@millsp already had a [solution](https://github.com/prisma/prisma/issues/5392#issuecomment-837299286) that worked with prisma 2.22.0.

### How to reproduce

1. Use [prisma-serverless-nextjs](https://github.com/millsp/prisma-serverless-nextjs) example by @millsp.
2. Run `npm install` 
3. Run `npm deploy`
4. See Query engine binary could not be found error on the users page.
5. Remove ^ from prisma and @prisma/client dependencies. 
6. Run `npm install` 
7. Run `npm deploy`
8. See users page no longer Query engine binary could not be found error. 

### Expected behavior

Expected prisma to find query-engine-rhel-openssl-1.0.x under node_modules/.prisma/client on lambda edge.

### Prisma information

Schema from @millsp [example]( https://github.com/millsp/prisma-serverless-nextjs). 
```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id                        Int                   @id @default(autoincrement())
  name                      String
  email                     String                @unique
  emailVerified             DateTime?             @map(name: "email_verified")
  image                     String?
  createdAt                 DateTime              @default(now()) @map(name: "created_at")
  updatedAt                 DateTime              @default(now()) @map(name: "updated_at")

  @@map(name: "users")
}
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14

### Prisma Version

```
2.24.0
```

**Comment by millsp** [comment]
Hey bozanbozkurt is this limited to `2.24.0` or have you seen this on `2.27.0` as well?

**Comment by bozanbozkurt** [comment]
> Hey bozanbozkurt is this limited to `2.24.0` or have you seen this on `2.27.0` as well?

The problem is happening on 2.27.0 too. I tested it with the following versions.
2.22.0 -> Works
2.23.0 -> Works
2.24.0 -> Engine binary error.
2.25.0 -> Engine binary error.
2.26.0 -> Engine binary error.
2.27.0 -> Engine binary error.

**Comment by janpio** [comment]
Can you maybe share a deployment where we can observe this?
What is the error message you are getting?

**Comment by MGough** [comment]
Hi @janpio 👋🏻 ,

I've followed the steps (1-4) outlined by @bozanbozkurt above for this deployment. 

**Warning** This page may hang/crash/freeze your browser, it seems to keep trying to perform a network request. I've included the page contents in the code block below:
https://d2uqgknqu387ok .cloudfront.net/users

```json
{
   "message":"Query engine binary for current platform \"rhel-openssl-1.0.x\" could not be found.\nThis probably happens, because you built Prisma Client on a different platform.\n(Prisma Client looked in \"/query-engine-rhel-openssl-1.0.x\")\n\nSearched Locations:\n\n /.prisma/client\n /Users/merlin/not-bitfount/prisma-serverless-nextjs/node_modules/@prisma/client\n /\n /\n /\n /tmp/prisma-engines\n /\n\nYou already added the platforms \"darwin\", \"rhel-openssl-1.0.x\" to the \"generator\" block\nin the \"schema.prisma\" file as described in https://pris.ly/d/client-generator,\nbut something went wrong. That's suboptimal.\n\nPlease create an issue at https://github.com/prisma/prisma/issues/new",
   "stack":"Error: Query engine binary for current platform \"rhel-openssl-1.0.x\" could not be found.\nThis probably happens, because you built Prisma Client on a different platform.\n(Prisma Client looked in \"/query-engine-rhel-openssl-1.0.x\")\n\nSearched Locations:\n\n /.prisma/client\n /Users/merlin/not-bitfount/prisma-serverless-nextjs/node_modules/@prisma/client\n /\n /\n /\n /tmp/prisma-engines\n /\n\nYou already added the platforms \"darwin\", \"rhel-openssl-1.0.x\" to the \"generator\" block\nin the \"schema.prisma\" file as described in https://pris.ly/d/client-generator,\nbut something went wrong. That's suboptimal.\n\nPlease create an issue at https://github.com/prisma/prisma/issues/new\n at PrismaClientFetcher.<anonymous> (/var/task/pages/users.js:412:456)\n at Generator.throw (<anonymous>)\n at r (/var/task/pages/users.js:1:721)"
}
```

Where `/Users/merlin/not-bitfount/prisma-serverless-nextjs/` is the working directory the project was deployed from. The behaviour is the same on Github actions except that path is of course different.

As for logs in cloudwatch from the lambda, they appear to be all normal. No error messages or stack traces, just the usual `START` and `END` logs:
```


START RequestId: 3adc172c-0053-459e-96bd-03b1ec7a74c3 Version: 1
--
END RequestId: 3adc172c-0053-459e-96bd-03b1ec7a74c3
REPORT RequestId: 3adc172c-0053-459e-96bd-03b1ec7a74c3	Duration: 3.87 ms	Billed Duration: 4 ms	Memory Size: 512 MB	Max Memory Used: 66 MB	Init Duration: 160.98 ms
START RequestId: 1be98217-939d-4cf2-80d1-d0e8f785d99a Version: 1
END RequestId: 1be98217-939d-4cf2-80d1-d0e8f785d99a
REPORT RequestId: 1be98217-939d-4cf2-80d1-d0e8f785d99a	Duration: 1.79 ms	Billed Duration: 2 ms	Memory Size: 512 MB	Max Memory Used: 66 MB
START RequestId: eef1d30e-7d8d-4971-97a4-b8ee035ea31e Version: 1
END RequestId: eef1d30e-7d8d-4971-97a4-b8ee035ea31e
REPORT RequestId: eef1d30e-7d8d-4971-97a4-b8ee035ea31e	Duration: 1.31 ms	Billed Duration: 2 ms	Memory Size: 512 MB	Max Memory Used: 66 MB
START RequestId: 24caefe5-231a-4f7f-910e-8134b4d00938 Version: 1
END RequestId: 24caefe5-231a-4f7f-910e-8134b4d00938
REPORT RequestId: 24caefe5-231a-4f7f-910e-8134b4d00938	Duration: 2.19 ms	Billed Duration: 3 ms	Memory Size: 512 MB	Max Memory Used: 67 MB
START RequestId: a56af1a7-535d-4c34-a865-2432cf44bb75 Version: 1
END RequestId: a56af1a7-535d-4c34-a865-2432cf44bb75
REPORT RequestId: a56af1a7-535d-4c34-a865-2432cf44bb75	Duration: 867.03 ms	Billed Duration: 868 ms	Memory Size: 512 MB	Max Memory Used: 84 MB
START RequestId: 65f2822e-9f35-4158-bc0f-ef4cff717865 Version: 1
END RequestId: 65f2822e-9f35-4158-bc0f-ef4cff717865
REPORT RequestId: 65f2822e-9f35-4158-bc0f-ef4cff717865	Duration: 79.67 ms	Billed Duration: 80 ms	Memory Size: 512 MB	Max Memory Used: 84 MB
```

Downloading the lambda it looks like this:
![Screenshot 2021-07-30 at 15 01 51](https://user-images.githubusercontent.com/6558104/127664453-b2b640c4-f016-462a-b2a4-fcea9c9cb719.png)

The client appears to be included within `node_modules/.prisma/client`:
![Screenshot 2021-07-30 at 15 03 10](https://user-images.githubusercontent.com/6558104/127664605-f6fefb34-cf86-490f-906b-a4d5b2fbc657.png)

Which is the same location as deployments that are using Prisma `2.22.0`, so it appears that the file is in the right location, but in newer versions it cannot be found.

I'll leave my deployment online for now, please let me know if it's no longer of any use to you. Happy to try to answer any other questions you have about this deployment.

**Comment by bozanbozkurt** [comment]
We managed to update prisma to 3.2.0 on our builds. 
The query engine binary name and its directory have since changed. Located prisma query engine binary using this [comment](https://github.com/prisma/prisma/issues/5392#issuecomment-846841969).
