### ISSUE TITLE
Fail to create a new record

### ISSUE THREAD

**Issue by lkedmi** [prisma/prisma#8416]
### Bug description

Running the described seed file, I'm getting the following error:
```
Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.upsertOneForm.create.FormCreateInput.companyId`: Field does not exist on enclosing type., Query parsing/validation error at `Mutation.upsertOneForm.create.FormUncheckedCreateInput.template`: A value is required but not set.]` at `Mutation.upsertOneForm.create`
    at cb (/Users/lkedmi/LeasePilot/leasepilot-app/node_modules/@prisma/client/runtime/index.js:34800:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/Users/lkedmi/LeasePilot/leasepilot-app/prisma/seed.js:34:16) {
  code: 'P2009',
  clientVersion: '2.27.0',
  meta: {
    query_validation_error: 'Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.upsertOneForm.create.FormCreateInput.companyId`: Field does not exist on enclosing type., Query parsing/validation error at `Mutation.upsertOneForm.create.FormUncheckedCreateInput.template`: A value is required but not set.]',
    query_position: 'Mutation.upsertOneForm.create'
  }
}
```

Unless I'm totally missing something, it's odd because the previous command which creates a new `building` has the exact same relation to `company` and it executes consistently without failing.

Would appreciate any help 😄 

### How to reproduce

1. Create a new database
2. Push the schema to the database by running the command `npx prisma db push`
2. Seed the database by running the command `npx prisma db seed --preview-feature`

### Expected behavior

Be able to create a new `form` record.

### Prisma information

schema.prisma
```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["planetScaleMode"]
}

datasource db {
  provider          = "mysql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
  planetScaleMode   = true
}

model Company {
  id        Int        @id @default(autoincrement())
  createdAt DateTime   @db.DateTime(0)
  updatedAt DateTime   @db.DateTime(0)
  name      String?    @unique @db.VarChar(255)
  Lease     Lease[]
  Form      Form[]
  Building  Building[]
}

model Lease {
  id         Int      @id @default(autoincrement())
  createdAt  DateTime @db.DateTime(0)
  updatedAt  DateTime @db.DateTime(0)
  companyId  Int?
  formId     Int
  buildingId Int
  document   Json     @db.Json
  terms      Json     @db.Json
  Company    Company? @relation(fields: [companyId], references: [id])
  Building   Building @relation(fields: [buildingId], references: [id])
  Form       Form     @relation(fields: [formId], references: [id])
}

model Building {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @db.DateTime(0)
  updatedAt DateTime @db.DateTime(0)
  companyId Int?
  name      String?  @unique @db.VarChar(255)
  Lease     Lease[]
  Company   Company? @relation(fields: [companyId], references: [id])
}

model Form {
  id           Int          @id @default(autoincrement())
  createdAt    DateTime     @db.DateTime(0)
  updatedAt    DateTime     @db.DateTime(0)
  companyId    Int?
  documentType DocumentType @default(LEASE)
  dealType     DealType
  name         String       @unique @db.VarChar(255)
  template     Json         @db.Json
  editor       Json         @db.Json
  Lease        Lease[]
  Company      Company?     @relation(fields: [companyId], references: [id])
}

enum DocumentType {
  LEASE
  AMENDMENT
  LOI
}

enum DealType {
  OFFICE
  RETAIL
  INDUSTRIAL
}
```

prisma/seed.js
```
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  const company = await prisma.company.upsert({
    where: { 
      name: "test" 
    },
    update: {},
    create: {
      createdAt: new Date(),
      updatedAt: new Date(),
      name: "test",
    },
  });

  console.log("company", company);

  const building = await prisma.building.upsert({
    where: { 
      name: "100 Broadway" 
    },
    update: {},
    create: {
      createdAt: new Date(),
      updatedAt: new Date(),
      companyId: company.id,
      name: "100 Broadway",
    },
  });

  console.log("building", building);

  const form = await prisma.form.upsert({
    where: {
      id: 1,
    },
    update: {},
    create: {
      createdAt: new Date(),
      updatedAt: new Date(),
      companyId: company.id,
      documentType: "LEASE",
      dealType: "RETAIL",
      name: "RETAIL_LEASE",
      template: null,
      editor: [],
    },
  });

  console.log("form", form);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
```

### Environment & setup

- OS: MacOS
- Database: MySQL
- Node.js version: 14.15.0

### Prisma Version

```
prisma               : 2.27.0
@prisma/client       : 2.27.0
Current platform     : darwin
Query Engine         : query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.nvm/versions/node/v14.15.0/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.nvm/versions/node/v14.15.0/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.nvm/versions/node/v14.15.0/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt cdba6ec525e0213cce26f8e4bb23cf556d1479bb (at ../../.nvm/versions/node/v14.15.0/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : cdba6ec525e0213cce26f8e4bb23cf556d1479bb
Studio               : 0.410.0
Preview Features     : planetScaleMode
```

**Comment by pantharshit00** [comment]
Hey @lkedmi 

Can you please try this once without planetScaleMode? It is experimental right now.

**Comment by lkedmi** [comment]
Hey @pantharshit00,

I tried that by mimicking the scenario on my local machine - I created two databases (main database and shadow database), removed all planetScale related configuration from the schema file and ran the seed.
Unfortunately, I'm still getting the same issue.

Can you please try to reproduce the issue on your end?

Thanks!

**Comment by janpio** [comment]
Can you try again with just 1 local database, and no explicit shadow database? (The credentials you are using will have to be able to create a shadow database ad hoc and do that in the background) Would be interesting if this influences things at all.

**Comment by lkedmi** [comment]
@janpio sure, I tried it just now, still getting the same issue 😢

**Comment by dpetrick** [comment]
You're missing `template` in the create.

**Comment by lkedmi** [comment]
@dpetrick Not sure what's that and I wasn't able to find anything in the docs, can you please point me in the right direction? Thanks 🙏

**Comment by dpetrick** [comment]
I assume you're using JS, because TS would not even compile.

The short version: `template` is are required field, which means it's not nullable. `null` is therefore not a valid input for template, resulting in a runtime error.

The long version:

```prisma
model Building {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @db.DateTime(0)
  updatedAt DateTime @db.DateTime(0)
  companyId Int?
  name      String?  @unique @db.VarChar(255)
  Lease     Lease[]
  Company   Company? @relation(fields: [companyId], references: [id])
}
```

The above model create is covered by this input:
```
create: {
      createdAt: new Date(),
      updatedAt: new Date(),
      companyId: company.id,
      name: "100 Broadway",
    },
```

Why? Because everything you didn't provide is either a many relation (`Lease)` or an optional relation (`Company`, which is nullable) so you don't need it in the create input, or is a scalar field that doesn't have to be included because it is annotated in a way that the db or a default handles it (`id`).


In contrast, `Form` has different fields:
```prisma
model Form {
  id           Int          @id @default(autoincrement())
  createdAt    DateTime     @db.DateTime(0)
  updatedAt    DateTime     @db.DateTime(0)
  companyId    Int?
  documentType DocumentType @default(LEASE)
  dealType     DealType
  name         String       @unique @db.VarChar(255)
  template     Json         @db.Json
  editor       Json         @db.Json
  Lease        Lease[]
  Company      Company?     @relation(fields: [companyId], references: [id])
}
```

All fields that are _not optional_ and are _not covered by defaults_ (`name`, `template`, `editor`, `dealType`) must be provided when creating records for `Form`. `null` is not a valid input for required fields, only for optional fields.

**Comment by lkedmi** [comment]
Uh, I totally missed that and I totally misread the error, I'm sorry for the goose chase 😢 
Thank you so much for your help!
