### ISSUE TITLE
PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by 12emir** [prisma/prisma#8434]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.1.0            | 
| OS              | darwin             |
| Prisma Client   | 2.27.0             |
| Query Engine    | query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb|
| Database        | undefined|

## Query
```
mutation {
  queryRaw(
    query: "X"
    parameters: "X"
  )
}
```

## Logs
```
ery Engine in /Users/kozakiewicz/Desktop/scraper/node_modules/.prisma/client  
  plusX Execution permissions of /Users/kozakiewicz/Desktop/scraper/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.27.0  
  prisma:engine Engine Version: query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb  
  prisma:engine Active provider: mysql  
  prisma:client prisma.queryRaw(REPAIR TABLE Cryptoposts QUICK;, [])  +7s
  prisma:client Prisma Client call:  
  prisma:engine { cwd: '/Users/kozakiewicz/Desktop/scraper/prisma' }  
  prisma:engine Search for Query Engine in /Users/kozakiewicz/Desktop/scraper/node_modules/.prisma/client  
  plusX Execution permissions of /Users/kozakiewicz/Desktop/scraper/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '53552' ] }  
  prisma:engine stdout  Starting a mysql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:53552  
  prisma:engine Search for Query Engine in /Users/kozakiewicz/Desktop/scraper/node_modules/.prisma/client  
  plusX Execution permissions of /Users/kozakiewicz/Desktop/scraper/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.27.0  
  prisma:engine Engine Version: query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43
index out of bounds: the len is 0 but the index is 0  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/kozakiewicz/Desktop/scraper/node_modules/@prisma/client/runtime/index.js:26686:24)
  prisma:engine       at Socket.emit (node:events:377:35)
  prisma:engine       at endReadableNT (node:internal/streams/readable:1312:12)
  prisma:engine       at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:53552
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1133:16) {
  prisma:engine     errno: -61,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 53552
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/Users/kozakiewicz/Desktop/scraper/prisma' }  
  prisma:engine Search for Query Engine in /Users/kozakiewicz/Desktop/scraper/node_modules/.prisma/client  
  plusX Execution permissions of /Users/kozakiewicz/Desktop/scraper/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '53558' ] }  
  prisma:engine stdout  Starting a mysql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:53558  
  prisma:engine Search for Query Engine in /Users/kozakiewicz/Desktop/scraper/node_modules/.prisma/client  
  plusX Execution permissions of /Users/kozakiewicz/Desktop/scraper/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.27.0  
  prisma:engine Engine Version: query-engine cdba6ec525e0213cce26f8e4bb23cf556d1479bb  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in query-engine/connectors/sql-query-connector/src/query_ext.rs:58:43
index out of bounds: the len is 0 but the index is 0  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/kozakiewicz/Desktop/scraper/node_modules/@prisma/client/runtime/index.js:26686:24)
  prisma:engine       at Socket.emit (node:events:377:35)
  prisma:engine       at endReadableNT (node:internal/streams/readable:1312:12)
  prisma:engine       at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
await prisma.mydb
        .upsert({
          where: {
            unique: post.id,
          },
          update: {
          },
          create: {
            unique: post.id,
   ...
          },
        })
        .catch((e, item) => {
          console.log(e, item)
        })```

## Schema
```prisma


datasource db {
  provider = "mysql"

}


generator client {
  provider = "prisma-client-js"
}

model Post {
  id        Int     @default(autoincrement()) @id
  title     String @db.VarChar(255) 
  content   String? @db.LongText	
  published Boolean @default(false)
  author    User?   @relation(fields: [authorId], references: [id])
  authorId  Int?
}

model User {
  id            Int       @default(autoincrement()) @id
  name          String?
  email         String?   @unique
  createdAt     DateTime  @default(now()) @map(name: "created_at")
  updatedAt     DateTime  @updatedAt @map(name: "updated_at")
  posts         Post[]
  @@map(name: "users")
}

model Bushcraftposts {
    id  Int       @default(autoincrement()) @id
  title  String?    @db.VarChar(255) 
  unique   String?  @db.VarChar(255) @unique
  content    String?   @db.LongText()
  baseUrl String? @db.VarChar(255) 
  fullUrl String? @db.VarChar(255) 
  postUrl String? @db.VarChar(255) 
  categories String? @db.VarChar(255) 
  tags String?   @db.LongText()
images String? @db.LongText()
dbCollection String?  @db.VarChar(255) 
excerpt         String?   @db.LongText()

contentHtml           String?   @db.LongText()
date String?
newDate DateTime?
slug String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")

}


model Lgbtposts {
 id  Int       @default(autoincrement()) @id
  title  String?    @db.VarChar(255) 
  unique   String?  @db.VarChar(255) @unique
  content    String?   @db.LongText()
  baseUrl String? @db.VarChar(255) 
  fullUrl String? @db.VarChar(255) 
  postUrl String? @db.VarChar(255) 
  categories String? @db.VarChar(255) 
  tags String?   @db.LongText()
images String? @db.LongText()
dbCollection String?  @db.VarChar(255) 
excerpt         String?   @db.LongText()

contentHtml           String?   @db.LongText()
date String?
newDate DateTime?
slug String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")
}


model Konopnagalaktykaposts {
  id  Int       @default(autoincrement()) @id
  title  String?    @db.VarChar(255) 
  unique   String?  @db.VarChar(255) @unique
  content    String?   @db.LongText()
  baseUrl String? @db.VarChar(255) 
  fullUrl String? @db.VarChar(255) 
  postUrl String? @db.VarChar(255) 
  categories String? @db.VarChar(255) 
  tags String?   @db.LongText()
images String? @db.LongText()
dbCollection String?  @db.VarChar(255) 
excerpt         String?   @db.LongText()

contentHtml           String?   @db.LongText()
date String?
newDate DateTime?
slug String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")
}


model Devposts {
 id  Int       @default(autoincrement()) @id
  title  String?    @db.VarChar(255) 
  unique   String?  @db.VarChar(255) @unique
  content    String?   @db.LongText()
  baseUrl String? @db.VarChar(255) 
  fullUrl String? @db.VarChar(255) 
  postUrl String? @db.VarChar(255) 
  categories String? @db.VarChar(255) 
  tags String?   @db.LongText()
images String? @db.LongText()
dbCollection String?  @db.VarChar(255) 
excerpt         String?   @db.LongText()

contentHtml           String?   @db.LongText()
date String?
newDate DateTime?
slug String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")
}


model Cryptoposts {
 id  Int       @default(autoincrement()) @id
  title  String?    @db.VarChar(255) 
  unique   String?  @db.VarChar(255) @unique
  content    String?   @db.LongText()
  baseUrl String? @db.VarChar(255) 
  fullUrl String? @db.VarChar(255) 
  postUrl String? @db.VarChar(255) 
  categories String? @db.VarChar(255) 
  tags String?   @db.LongText()
images String? @db.LongText()
dbCollection String?  @db.VarChar(255) 
excerpt         String?   @db.LongText()

contentHtml           String?   @db.LongText()
date String?
newDate DateTime?
slug String?
  createdAt     DateTime  @default(now()) @map(name: "created_at")
}



```

**Comment by pantharshit00** [comment]
Hey @kozakiewicz1221 


The logs you shared show that the panic is triggered via a raw query while you shared upsert query. Are you sure that it is the query which triggered the panic? Is there any raw query in the code path which is triggering this panic? If so, please share that with us.

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this solved.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
