### ISSUE TITLE
Netlify / NextJS | Module not found: Error: Can't resolve '_http_common' in '/opt/build/repo/node_modules/@prisma/client/runtime

### ISSUE THREAD

**Issue by StartMeUp** [prisma/prisma#8503]
### Bug description

I can't deploy nextJs + prisma on Netlify. It works fine on my local PC (wsl2, node 14.17.0)

The report says:

```
12:02:37 PM: ModuleNotFoundError: Module not found: Error: Can't resolve '_http_common' in '/opt/build/repo/node_modules/@prisma/client/runtime'
12:02:37 PM: > Build error occurred
12:02:37 PM: Error: > Build failed because of webpack errors
12:02:37 PM:     at /opt/build/repo/node_modules/next/dist/build/index.js:15:924
12:02:37 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:6:584)
12:02:37 PM: ​
12:02:37 PM: ────────────────────────────────────────────────────────────────
12:02:37 PM:   "build.command" failed                                        
12:02:37 PM: ────────────────────────────────────────────────────────────────
12:02:37 PM: ​
12:02:37 PM:   Error message
12:02:37 PM:   Command failed with exit code 1: next build
12:02:37 PM: ​
12:02:37 PM:   Error location
12:02:37 PM:   In Build command from Netlify app:
12:02:37 PM:   next build
```

### How to reproduce

Try to deploy on netlify. Force NODE_VERSION 14.17.0  in environment variables
Prisma imported in the nextJs api, not directly in the pages

### Prisma information

"prisma": "^2.28.0",
"@prisma/client": "^2.28.0",

### Environment & setup

Netlify
NODE_VERSION 14.17.0

### Prisma Version

```
prisma               : 2.28.0
@prisma/client       : 2.28.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 89facabd0366f63911d089156a7a70125bfbcd27 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 89facabd0366f63911d089156a7a70125bfbcd27
Studio               : 0.417.0
```

**Comment by StartMeUp** [comment]
Update.
I don't get the error with Vercel

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma/issues/7539 which will remove dependency on `_http_common`.
