### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not an object | After doing HTTP request

### ISSUE THREAD

**Issue by KingfishX23** [prisma/prisma#8640]
### Bug description

I want to initialize prisma connection before starting the server
```
import { connectPrisma } from './prisma'; // Global prisma object

// Run the server
async function start() {
	await connectPrisma(); // Basically await prisma.$connect()
	httpServer.listen({ port: config.port }, async () => {
		console.log(READY_MESSAGE);

		someCronJob();
	});
}
start();
```

but when i do any prisma commands later, it always return this error

UPDATE!!
I found that this only happened after i called an http request command, i.e:
```
await axios({ method: 'get', url: URL });
```

the error are returned

TypeError: Right-hand side of 'instanceof' is not an object
    at parseURL (E:\SoftwareProjects\Copytrade\copytrade-server\node_modules\@prisma\client\runtime\index.js:25844:15)
    at Object.parseOrigin (E:\SoftwareProjects\Copytrade\copytrade-server\node_modules\@prisma\client\runtime\index.js:25856:11)
    at new Client (E:\SoftwareProjects\Copytrade\copytrade-server\node_modules\@prisma\client\runtime\index.js:26228:25)
    at Pool.dispatch (E:\SoftwareProjects\Copytrade\copytrade-server\node_modules\@prisma\client\runtime\index.js:27953:22)
    at Pool.request (E:\SoftwareProjects\Copytrade\copytrade-server\node_modules\@prisma\client\runtime\index.js:27310:12)
    at E:\SoftwareProjects\Copytrade\copytrade-server\node_modules\@prisma\client\runtime\index.js:28160:19
    at new Promise (<anonymous>)
    at Undici.request (E:\SoftwareProjects\Copytrade\copytrade-server\node_modules\@prisma\client\runtime\index.js:28159:14)
    at BinaryEngine.request (E:\SoftwareProjects\Copytrade\copytrade-server\node_modules\@prisma\client\runtime\index.js:28856:48)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  clientVersion: '2.28.0'
}

### Expected behavior

should be able to use command as usual

### Prisma information

I use this command
await prisma.$connect();

I want to run this command later on
let data = {...}

await prisma.myfxbookStats.upsert({
    where: { id: Number(account.id) },
    create: data,
    update: data,
    });

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```
2.28.0
```

**Comment by KingfishX23** [comment]
I solved the bug. its on my part. i forgot to declare "URL" variable in my code, which may affect prisma a variable also called URL in prisma code, hence the Right hand error.

for other people. do not use manipulate the global URL variable.
