### ISSUE TITLE
Disconnecting entity with composite id fails due to null constraint validation error

### ISSUE THREAD

**Issue by tlindener** [prisma/prisma#8650]
### Bug description

Within a multi tenant application where "tenantId" is a property shared across all entities the use of "disconnect" on a relation causes a null constraint validation error. Because prisma wants to setNull on both the entity Id as well as the shared tenantId.

### How to reproduce

1. Use provided schema
2. Run index.ts via ts-node
3. See error

### Expected behavior

Prisma should not set null a field which is required within its own entity.

### Prisma information

prisma.schema
```prisma
generator client {
    provider        = "prisma-client-js"
    previewFeatures = ["referentialActions"]
}

datasource db {
    provider = "postgresql"
    url      = "postgresql://admin:admin@localhost:5432/bug?schema=public"
}

model Token {
    tenantId String    @db.VarChar
    id       String    @db.VarChar
    location Location?
    tenant   Tenant    @relation(fields: [tenantId], references: [id])

    @@id([tenantId, id])
}

model Location {
    tenantId String  @db.VarChar
    id       String  @db.VarChar
    tokenId  String? @db.VarChar
    token    Token?  @relation(fields: [tenantId, tokenId], references: [tenantId, id])
    tenant   Tenant  @relation(fields: [tenantId], references: [id])

    @@id([tenantId, id])
}

model Tenant {
    id        String     @id @db.VarChar
    locations Location[]
    Token     Token[]
}

```

index.ts
```typescript
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
async function main() {
    const tenant = await prisma.tenant.create({
        data: {
            id: "myId"
        }
    })

    await prisma.location.create({
        data: {
            id: "locationId",
            tenant: {
                connect: {
                    id: tenant.id
                }
            },
            token: {
                create: {
                    id: "dataId",
                    tenant: {
                        connect: {
                            id: tenant.id
                        }
                    }
                }
            }
        },

    })
    await prisma.location.update({
        where: {
            tenantId_id: {
                tenantId: tenant.id,
                id: "locationId"
            },

        }, data: {
            token: {
                disconnect: true
            }
        }
    })

}
main()
    .catch(e => {
        throw e
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v16.4.0

### Prisma Version

```
2.27.0/2.28.0
```

**Comment by tlindener** [comment]
This issue is also related to #8649 because within my larger codebase this issue exists for other fields as well: E.g. the tokenId field mentioned in this issue which blocks me from simply setting tokenId to null.

**Comment by felixmokross** [comment]
I'm facing this issue as well. I also want to use composite keys on my entities, with the tenantId being part of the primary key, so that an entity cannot be maliciously re-assigned to a different tenant (given knowledge of the rest of the key). However, due to this issue, I can't disconnect any relations in this data model.

Would be great to have a solution for this (maybe allow to configure which keys get cleared on the disconnect or on the relation?).

Does somebody know a workaround for this? Or other approaches for multi-tenancy with prisma?

**Comment by felixmokross** [comment]
At least for simple cases (single entity relations), a workaround that works is to use the foreign key column instead of the relation. So instead of this:
```
prisma.account.update({
  where: ...
  data: {
    ...,
    group: groupId
       ? { connect: { id_tenantId: { id: groupId, tenantId } } }
       : { disconnect: true },
  }
});
```

I now just do this:
```
prisma.account.update({
  where: ...
  data: {
    ...,
    groupId: groupId || null
  }
});
```

However, I think this will not work if you have other fields in the same update where you really want to use nested writes (i.e., creating/updating/deleting related records, not just connecting/disconnecting). Because the types only allow either use of foreign keys or the entity relation fields. I think it would also break down if you have an array field to which you want to connect multiple related entities.

**Comment by Jolg42** [comment]
Reproducible with our internal dev version `4.4.0-dev.30`
```
ts-node main.ts                                 
thread 'tokio-runtime-worker' panicked at 'not yet implemented: not yet implemented for Udt', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tiberius-0.9.3/src/tds/codec/type_info.rs:206:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PrismaClientKnownRequestError: 
Invalid `prisma.$queryRaw()` invocation:


Raw query failed. Code: `N/A`. Message: `not yet implemented: not yet implemented for Udt`
    at RequestHandler.handleRequestError (/Users/j42/Repros/9933/node_modules/@prisma/client/runtime/index.js:30850:13)
    at RequestHandler.request (/Users/j42/Repros/9933/node_modules/@prisma/client/runtime/index.js:30833:12)
    at async Proxy._request (/Users/j42/Repros/9933/node_modules/@prisma/client/runtime/index.js:31805:16)
    at async main (/Users/j42/Repros/9933/main.ts:7:5) {
  code: 'P2010',
  clientVersion: '4.4.0-dev.30',
  meta: {
    code: 'N/A',
    message: 'not yet implemented: not yet implemented for Udt'
  }
}
```

**Comment by pimeys** [comment]
I reproduced this with the 2.28.0 and 4.3.1. The reproduction is made with 4.3.1:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Location {
  tenantId String  @db.VarChar
  id       String  @db.VarChar
  tokenId  String? @db.VarChar
  Tenant   Tenant  @relation(fields: [tenantId], references: [id], onDelete: Cascade)
  Token    Token?  @relation(fields: [tenantId, tokenId], references: [tenantId, id], onDelete: Cascade)

  @@id([tenantId, id])
  @@unique([tenantId, tokenId], map: "Location_tenantId_tokenId_unique")
}

model Tenant {
  id       String     @id @db.VarChar
  Location Location[]
  Token    Token[]
}

model Token {
  tenantId String    @db.VarChar
  id       String    @db.VarChar
  Tenant   Tenant    @relation(fields: [tenantId], references: [id], onDelete: Cascade)
  Location Location?

  @@id([tenantId, id])
}
```

```typescript
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient({
  log: ['query', 'info', 'warn', 'error'],
})

async function main() {
  await prisma.tenant.deleteMany()
  await prisma.location.deleteMany()

  const tenant = await prisma.tenant.create({
    data: {
      id: "myId"
    }
  })

  await prisma.location.create({
    data: {
      id: "locationId",
      Tenant: {
        connect: {
          id: tenant.id
        }
      },
      Token: {
        create: {
          id: "dataId",
          Tenant: {
            connect: {
              id: tenant.id
            }
          }
        }
      }
    },
  })

  await prisma.location.update({
    where: {
      tenantId_id: {
        tenantId: tenant.id,
        id: "locationId"
      },

    }, data: {
      Token: {
        disconnect: true
      }
    }
  })
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```

Debug log:

```
  prisma:tryLoadEnv  Environment variables loaded from /prisma-8650/.env +0ms
  prisma:tryLoadEnv  Environment variables loaded from /prisma-8650/.env +2ms
  prisma:client  dirname /prisma-8650/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../../prisma +0ms
  prisma:client  cwd /prisma-8650/prisma +0ms
  prisma:client  clientVersion 4.3.1 +0ms
  prisma:client  clientEngineType library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /prisma-8650/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /prisma-8650/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node +0ms
  prisma:client  Prisma Client call: +45ms
  prisma:client  prisma.tenant.deleteMany(undefined) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  deleteManyTenant {
    count
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +45ms
  prisma:client:libraryEngine  library starting +0ms
prisma:info Starting a postgresql pool with 33 connections.
  prisma:client:libraryEngine  library started +17ms
prisma:query BEGIN
prisma:query SELECT "public"."Tenant"."id" FROM "public"."Tenant" WHERE 1=1 OFFSET $1 /* traceparent=00-00-00-00 */
prisma:query SELECT "public"."Tenant"."id" FROM "public"."Tenant" WHERE 1=1 /* traceparent=00-00-00-00 */
prisma:query DELETE FROM "public"."Tenant" WHERE "public"."Tenant"."id" IN ($1) /* traceparent=00-00-00-00 */
prisma:query COMMIT
  prisma:client  Prisma Client call: +30ms
  prisma:client  prisma.location.deleteMany(undefined) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  deleteManyLocation {
    count
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +13ms
prisma:query BEGIN
prisma:query SELECT "public"."Location"."tenantId", "public"."Location"."id" FROM "public"."Location" WHERE 1=1 OFFSET $1 /* traceparent=00-00-00-00 */
prisma:query SELECT "public"."Location"."tenantId", "public"."Location"."id" FROM "public"."Location" WHERE 1=1 /* traceparent=00-00-00-00 */
prisma:query COMMIT
  prisma:client  Prisma Client call: +2ms
  prisma:client  prisma.tenant.create({
  data: {
    id: 'myId'
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  createOneTenant(data: {
    id: "myId"
  }) {
    id
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +2ms
prisma:query BEGIN
prisma:query INSERT INTO "public"."Tenant" ("id") VALUES ($1) RETURNING "public"."Tenant"."id" /* traceparent=00-00-00-00 */
prisma:query SELECT "public"."Tenant"."id" FROM "public"."Tenant" WHERE "public"."Tenant"."id" = $1 LIMIT $2 OFFSET $3 /* traceparent=00-00-00-00 */
prisma:query COMMIT
  prisma:client  Prisma Client call: +4ms
  prisma:client  prisma.location.create({
  data: {
    id: 'locationId',
    Tenant: {
      connect: {
        id: 'myId'
      }
    },
    Token: {
      create: {
        id: 'dataId',
        Tenant: {
          connect: {
            id: 'myId'
          }
        }
      }
    }
  }
}) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  createOneLocation(data: {
    id: "locationId"
    Tenant: {
      connect: {
        id: "myId"
      }
    }
    Token: {
      create: {
        id: "dataId"
        Tenant: {
          connect: {
            id: "myId"
          }
        }
      }
    }
  }) {
    tenantId
    id
    tokenId
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +5ms
prisma:query BEGIN
prisma:query SELECT "public"."Tenant"."id" FROM "public"."Tenant" WHERE "public"."Tenant"."id" = $1 OFFSET $2 /* traceparent=00-00-00-00 */
prisma:query INSERT INTO "public"."Token" ("tenantId","id") VALUES ($1,$2) RETURNING "public"."Token"."tenantId", "public"."Token"."id" /* traceparent=00-00-00-00 */
prisma:query SELECT "public"."Tenant"."id" FROM "public"."Tenant" WHERE "public"."Tenant"."id" = $1 OFFSET $2 /* traceparent=00-00-00-00 */
prisma:query INSERT INTO "public"."Location" ("tenantId","id","tokenId") VALUES ($1,$2,$3) RETURNING "public"."Location"."tenantId", "public"."Location"."id" /* traceparent=00-00-00-00 */
prisma:query SELECT "public"."Location"."tenantId", "public"."Location"."id", "public"."Location"."tokenId" FROM "public"."Location" WHERE ("public"."Location"."tenantId" = $1 AND "public"."Location"."id" = $2) LIMIT $3 OFFSET $4 /* traceparent=00-00-00-00 */
prisma:query COMMIT
  prisma:client  Prisma Client call: +5ms
  prisma:client  prisma.location.update({
  where: {
    tenantId_id: {
      tenantId: 'myId',
      id: 'locationId'
    }
  },
  data: {
    Token: {
      disconnect: true
    }
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  updateOneLocation(
    where: {
      tenantId_id: {
        tenantId: "myId"
        id: "locationId"
      }
    }
    data: {
      Token: {
        disconnect: true
      }
    }
  ) {
    tenantId
    id
    tokenId
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +5ms
prisma:query BEGIN
prisma:query SELECT "public"."Location"."tenantId", "public"."Location"."id" FROM "public"."Location" WHERE ("public"."Location"."tenantId" = $1 AND "public"."Location"."id" = $2) /* traceparent=00-00-00-00 */
prisma:query SELECT "public"."Location"."tenantId", "public"."Location"."id", "public"."Location"."tokenId" FROM "public"."Location" WHERE ("public"."Location"."tenantId" = $1 AND "public"."Location"."id" = $2) OFFSET $3 /* traceparent=00-00-00-00 */
prisma:query SELECT "public"."Token"."tenantId", "public"."Token"."id" FROM "public"."Token" WHERE (1=1 AND ("public"."Token"."tenantId","public"."Token"."id") IN (($1,$2))) OFFSET $3 /* traceparent=00-00-00-00 */
prisma:query SELECT "public"."Location"."tenantId", "public"."Location"."id" FROM "public"."Location" WHERE ("public"."Location"."tenantId" = $1 AND "public"."Location"."id" = $2) /* traceparent=00-00-00-00 */
prisma:query UPDATE "public"."Location" SET "tenantId" = $1, "tokenId" = $2 WHERE ("public"."Location"."tenantId","public"."Location"."id") IN (($3,$4)) /* traceparent=00-00-00-00 */
prisma:query ROLLBACK
  prisma:client:request_handler  PrismaClientKnownRequestError: Null constraint violation on the fields: (`tenantId`)
    at prismaGraphQLToJSError (/prisma-8650/node_modules/@prisma/client/runtime/index.js:20426:12)
    at LibraryEngine.buildQueryError (/prisma-8650/node_modules/@prisma/client/runtime/index.js:26363:12)
    at LibraryEngine.request (/prisma-8650/node_modules/@prisma/client/runtime/index.js:26297:22)
    at async RequestHandler.request (/prisma-8650/node_modules/@prisma/client/runtime/index.js:29873:24)
    at async PrismaClient._request (/prisma-8650/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async main (/prisma-8650/script.ts:38:3) {
  code: 'P2011',
  clientVersion: '4.3.1',
  meta: { constraint: [ 'tenantId' ] }
} +0ms
PrismaClientKnownRequestError: 
Invalid `prisma.location.update()` invocation in
/prisma-8650/script.ts:38:25

  35   },
  36 })
  37 
→ 38 await prisma.location.update(
Null constraint violation on the fields: (`tenantId`)
    at RequestHandler.handleRequestError (/prisma-8650/node_modules/@prisma/client/runtime/index.js:29909:13)
    at RequestHandler.request (/prisma-8650/node_modules/@prisma/client/runtime/index.js:29892:12)
    at async PrismaClient._request (/prisma-8650/node_modules/@prisma/client/runtime/index.js:30864:16)
    at async main (/prisma-8650/script.ts:38:3) {
  code: 'P2011',
  clientVersion: '4.3.1',
  meta: { constraint: [ 'tenantId' ] }
}
  prisma:client:libraryEngine  library stopping +19ms
  prisma:client:libraryEngine  library stopped +1ms
  prisma:client:libraryEngine:exitHooks  exit event received: exit +0ms
```

**Comment by ShoppasGit** [comment]
Any update on this? I am having the same issue. It is trying to null my tenantId since its in the composite relationship on a disconnect.

**Comment by ludralph** [comment]
Closing this in favour of [8403](https://github.com/prisma/prisma/issues/8403)
