### ISSUE TITLE
PANIC in C:\Users\runneradmin\.cargo\git\checkouts\cuid-rust-05420f73eb18afd9\4ffb2e4\src\lib.rs:29:65called `Result::unwrap()` on an `Err` value: FingerprintError("Could not retrieve hostname")

### ISSUE THREAD

**Issue by silvarafaelduarte** [prisma/prisma#8716]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.1           | 
| OS              | windows            |
| Prisma Client   | 2.19.0             |
| Query Engine    | query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d|
| Database        | undefined|

## Query
```
mutation {
  upsertOneUser(
    where: {
      username: "X"
    }
    update: {

    }
    create: {
      username: "X"
      password: "X"
      roles: ["X"]
    }
  ) {
    createdAt
    firstName
    id
    lastName
    password
    roles
    updatedAt
    username
  }
}
```

## Logs
```
  prisma:engine     at addChunk (internal/streams/readable.js:309:12)
  prisma:engine     at readableAddChunk (internal/streams/readable.js:284:9)
  prisma:engine     at LineStream.Readable.push (internal/streams/readable.js:223:10)
  prisma:engine     at LineStream.Transform.push (internal/streams/transform.js:166:32)
  prisma:engine     at LineStream._pushBuffer (D:\CursoAngular\Logg\server\node_modules\@prisma\client\runtime\index.js:26388:19)  {"timestamp":"Aug 12 10:29:08.625","level":"ERROR","fields":{"message":"PANIC","reason":"called `Result::unwrap()` on an `Err` value: FingerprintError(\"Could not retrieve hostname\")","file":"C:\\Users\\runneradmin\\.cargo\\git\\checkouts\\cuid-rust-05420f73eb18afd9\\4ffb2e4\\src\\lib.rs","line":29,"column":65},"target":"query_engine","span":{"name":"execute_single_operation"},"spans":[{"name":"execute_single_operation"}]}  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:58489
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 58489
  prisma:engine   }
  prisma:engine }  
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd: 'D:\\CursoAngular\\Logg\\server\\prisma' }  
  prisma:engine Search for Query Engine in D:\CursoAngular\Logg\server\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '58493' ] }  
  prisma:engine Client Version: 2.19.0  
  prisma:engine Engine Version: query-engine c1455d0b443d66b0d9db9bcb1bb9ee0d5bbc511d  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:58493  
  prisma:engine Search for Query Engine in D:\CursoAngular\Logg\server\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in C:\Users\runneradmin\.cargo\git\checkouts\cuid-rust-05420f73eb18afd9\4ffb2e4\src\lib.rs:29:65
called `Result::unwrap()` on an `Err` value: FingerprintError("Could not retrieve hostname")  
  prisma:engine TypeError: this.currentRequestPromise.cancel is not a function
  prisma:engine     at NodeEngine.handlePanic (D:\CursoAngular\Logg\server\node_modules\@prisma\client\runtime\index.js:29249:36)
  prisma:engine     at NodeEngine.setError (D:\CursoAngular\Logg\server\node_modules\@prisma\client\runtime\index.js:29195:16)
  prisma:engine     at LineStream.<anonymous> (D:\CursoAngular\Logg\server\node_modules\@prisma\client\runtime\index.js:29480:24)
  prisma:engine     at LineStream.emit (events.js:315:20)
  prisma:engine     at LineStream.EventEmitter.emit (domain.js:467:12)
  prisma:engine     at addChunk (internal/streams/readable.js:309:12)
  prisma:engine     at readableAddChunk (internal/streams/readable.js:284:9)
  prisma:engine     at LineStream.Readable.push (internal/streams/readable.js:223:10)
  prisma:engine     at LineStream.Transform.push (internal/streams/transform.js:166:32)
  prisma:engine     at LineStream._pushBuffer (D:\CursoAngular\Logg\server\node_modules\@prisma\client\runtime\index.js:26388:19)  {"timestamp":"Aug 12 10:29:09.427","level":"ERROR","fields":{"message":"PANIC","reason":"called `Result::unwrap()` on an `Err` value: FingerprintError(\"Could not retrieve hostname\")","file":"C:\\Users\\runneradmin\\.cargo\\git\\checkouts\\cuid-rust-05420f73eb18afd9\\4ffb2e4\\src\\lib.rs","line":29,"column":65},"target":"query_engine","span":{"name":"execute_single_operation"},"spans":[{"name":"execute_single_operation"}]}  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by janpio** [comment]
6 months later no further information, so I think we can consider this solved.

If this ever happens again, please comment here or even better - create a new issue. Thanks.
