### ISSUE TITLE
Prisma Client/Query Engine is giving me this error "Cannot create property 'clientVersion' on boolean 'true'"

### ISSUE THREAD

**Issue by provHarshaKommanaboyina** [prisma/prisma#8747]
### Bug description

Hello. The prisma client/query engine is giving the following error. If anyone has encountered this issue before then please help me out. Thanks in advance.

```
{
  "level": 50,
  "time": 1628981144709,
  "pid": 6,
  "stack": "TypeError: Cannot create property 'clientVersion' on boolean 'true'\n    at cb (/app/node_modules/@prisma/client/runtime/index.js:35953:25)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
  "type": "Error",
  "msg": "Cannot create property 'clientVersion' on boolean 'true'",
  "correlationId": "e676c591-889c-41b4-a1db-5b3d8b32d139"
}
```

### How to reproduce

1. My application is an express.js application. One of the endpoints has the following code block.
```
    const count = await prisma.content.count({
      where: {
          tags: {
            hasSome: ['Women],
          },
        publishedAt: { gt: "2021-04-12T00:00:00-0400", lt: "2021-08-13T03:16:05-04:00" },
      },
    });
 ```
 2. When I hit the above endpoint, I'm getting an error with the following logs.
 
 ```
2021-08-14T22: 45: 44.703Z prisma:client Prisma Client call: 2021-08-14T22: 45: 44.705Z prisma:client prisma.content.aggregate({
  where: {
    tags: {
      hasSome: [
        'Women'
      ]
    },
    publishedAt: {
      gt: '2021-04-12T00: 00: 00-0400',
      lt: '2021-08-13T03: 16: 05-04: 00'
    }
  },
  select: {
    _count: {
      select: {
        _all: true
      }
    }
  }
})
2021-08-14T22: 45: 44.705Z prisma:client Generated request: 2021-08-14T22: 45: 44.705Z prisma:client query {
  aggregateContent(where: {
    tags: {
      hasSome: [
        "Women"
      ]
    }
    publishedAt: {
      gt: "2021-04-12T00:00:00-0400"
      lt: "2021-08-13T03:16:05-04:00"
    }
  }) {
    _count {
      _all
    }
  }
}

2021-08-14T22: 45: 44.708Z prisma:engine { cwd: '/app/node_modules/.prisma/client'}
2021-08-14T22: 45: 44.709Z prisma:client:fetcher true
{
  "level": 50,
  "time": 1628981144709,
  "pid": 6,
  "errorMessage": "Cannot create property 'clientVersion' on boolean 'true'",
  "correlationId": "e676c591-889c-41b4-a1db-5b3d8b32d139"
}
{
  "level": 50,
  "time": 1628981144709,
  "pid": 6,
  "stack": "TypeError: Cannot create property 'clientVersion' on boolean 'true'\n    at cb (/app/node_modules/@prisma/client/runtime/index.js:35953:25)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
  "type": "Error",
  "msg": "Cannot create property 'clientVersion' on boolean 'true'",
  "correlationId": "e676c591-889c-41b4-a1db-5b3d8b32d139"
} 
 ```    

### Expected behavior

The Prisma client/query engine should work without any issues.

### Prisma information

```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Content {
  id           Int          @id
  title        String
  url          String
  thumbnailUrl String?      @map("thumbnail_url")
  publishedAt  String       @map("published_at") @db.VarChar(36)
  type         ContentType?
  tags         String[]

  @@map("content")
}

enum ContentType {
  blogs     @map("BLOGS")
  videos    @map("VIDEOS")
  docs      @map("DOCS")
  social    @map("SOCIAL")
  custom    @map("CUSTOM")
  targeted  @map("TARGETED")

  @@map("content_type")
}
```

### Environment & setup

- OS: Debian
- Database: PostgreSQL
- Node.js version: v14.16.0

### Prisma Version

```
prisma               : 2.29.0
@prisma/client       : 2.29.0
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
```

**Comment by janpio** [comment]
`clientVersion` should only be read or filled when you actually have an error, so this might be an error while creating an error message - something will try to reproduce with the code you provided.

**Comment by provHarshaKommanaboyina** [comment]
Thanks for the reply @janpio. Now I'm facing a different issue after I started using napi preview feature in prisma.schema file.

```
2021-08-15T20:19:38.960Z prisma:client:libraryEngine sending request, this.libraryStarted: false
2021-08-15T20:19:38.962Z prisma:client:fetcher TypeError: Cannot read property 'message' of undefined
    at LibraryEngine.request (/app/node_modules/@prisma/client/runtime/index.js:24476:101)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async cb (/app/node_modules/@prisma/client/runtime/index.js:35913:26)
```

**Comment by provHarshaKommanaboyina** [comment]
@pantharshit00 Did you get a chance to look into this issue? I'm kind of blocked with this issue. It would really be helpful for me if you can look into this issue.

**Comment by janpio** [comment]
Is this still reproducible in a recent version of Prisma @provHarshaKommanaboyina?

**Comment by garrensmith** [comment]
@provHarshaKommanaboyina this error should be resolved with our later versions of Prisma client. I'm going to close it but please open again if you are still getting the error.
