### ISSUE TITLE
Prisma giving error when trying to create multiple relations inside `connectOrCreate`

### ISSUE THREAD

**Issue by james0248** [prisma/prisma#8750]
### Bug description

```
/path-to-project/node_modules/@prisma/client/runtime/index.js:34800
          throw new import_engine_core.PrismaClientKnownRequestError(message, e.code, this.prisma._clientVersion, e.meta);
                ^

PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.post.create()` invocation:


  Query interpretation error. Error for binding '3': Error occurred during query execution:
InterpretationError("Unable to convert result into a set of projections", None)
    at cb (/path-to-project/node_modules/@prisma/client/runtime/index.js:34800:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'P2016',
  clientVersion: '2.28.0',
  meta: {
    details: "Error for binding '3': Error occurred during query execution:\n" +
      'InterpretationError("Unable to convert result into a set of projections", None)'
  }
}
```

### How to reproduce

Send a request to the `addPost` API

### Expected behavior

Prisma successfully creates a new Post, Track, Artist, Album.

## addPost.js
```js
const newPost = await context.prisma.post.create({
    data: {
        author: { connect: { id: userID } },
        text: text,
        track: {
            connectOrCreate: {
                where: {
                    spotifyID: trackSpotifyID,
                },
                create: {
                    spotifyID: trackSpotifyID,
                    name,
                    artists: {
                        create: artists.map(({ spotifyID, name }) => {
                            return {
                                artist: {
                                    connectOrCreate: {
                                        where: {
                                            spotifyID: spotifyID,
                                        },
                                        create: {
                                            spotifyID,
                                            name,
                                        },
                                    },
                                },
                            }
                        }),
                    },
                },
            },
        },
    },
})
```
I'm trying to create a new `Post` with information about a `Track` and the `Track` has 1 or more `Artist`s. The `artists` variable is an array containing data of the artists that made the track. If a `Post` with a new `Track`is being made, I need to create a new `Track` data in the database and also new `Artist`s. However, when there is a single artist, it works fine, but when there are more than 2 in the array, it gives an error.
## schema.prisma
```prisma
model tracksOnArtists {
  track    Track  @relation(fields: [trackID], references: [id])
  trackID  String
  artist   Artist @relation(fields: [artistID], references: [id])
  artistID String

  @@id([trackID, artistID])
}

model Post {
  id        String   @id @default(cuid())
  author    User     @relation(fields: [authorID], references: [id])
  authorID  String
  createdAt DateTime @default(now())
  text      String
  track     Track    @relation(fields: [trackID], references: [id])
  trackID   String
}

model Track {
  id         String            @id @default(cuid())
  spotifyID  String            @unique
  name       String
  post       Post[]
  artists    tracksOnArtists[]
}

model Artist {
  id        String            @id @default(cuid())
  spotifyID String            @unique
  name      String
  tracks    tracksOnArtists[]
}
```

### Environment & setup

- OS: macOS 11.4 20F71 arm64
- Database: SQLite
- Node.js version: v16.5.0

### Prisma Version

```
prisma               : 2.29.1
@prisma/client       : 2.28.0
```

**Comment by janpio** [comment]
Before we look into this, please update your `prisma` and `@prisma/client` to the same versions to make sure this mismatch is not causing this problem. Thanks.

**Comment by james0248** [comment]
> Before we look into this, please update your `prisma` and `@prisma/client` to the same versions to make sure this mismatch is not causing this problem. Thanks.

Thank you for the reply. I have updated `prisma` and `@prisma/client` both to `2.29.1`.
After that, I deleted the `prisma` directory and did a fresh re-install of all the `node_modules` just in case anything is wrong with the packages. And re-generated the prisma client, but it seems like no luck 😢 Below is the error after the re-install

```
/path-to-project/node_modules/@prisma/client/runtime/index.js:36374
          throw new import_engine_core3.PrismaClientKnownRequestError(message, e.code, this.prisma._clientVersion, e.meta);
                ^

PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]: 
Invalid `prisma.post.create()` invocation:


  Query interpretation error. Error for binding '3': Error occurred during query execution:
InterpretationError("Unable to convert result into a set of projections", None)
    at cb (/path-to-project/node_modules/@prisma/client/runtime/index.js:36374:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'P2016',
  clientVersion: '2.29.1',
  meta: {
    details: "Error for binding '3': Error occurred during query execution:\n" +
      'InterpretationError("Unable to convert result into a set of projections", None)'
  }
}
```

**Comment by askluke** [comment]
Also had this error with client version 3.6.0, so still an issue.
