### ISSUE TITLE
Prisma can't reach any external database.

### ISSUE THREAD

**Issue by snxk** [prisma/prisma#8795]
### Bug description

I am getting P1001 Error every time I try to access an external database. This only happens when accessing an external database hosting on Heroku/Supabase/Azure (tested with these), while testing with a local database running on podman prisma worked perfectly.

### How to reproduce

All commands that interact with the database like ```prisma migrate``` and ```prisma db pull``` give P1001 Error.

### Expected behavior

Prisma CLI executes the given commands without any error

### Prisma information

The Schema File
```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id   Int     @id @default(autoincrement())
  name String?
}

```

The env file
```
// .env
DATABASE_URL="postgresql://XXXX:XXXX@XXX-eu-west-1.compute.amazonaws.com:5432/XXX"
```

Debug log when running a ```prisma migrate dev```
```
 DEBUG="*" prisma migrate dev --name init
  prisma:loadEnv skipping package.json at /home/snxk/Projects/learn-prisma/package.json +0ms
  prisma:loadEnv skipping package.json at /home/snxk/Projects/package.json +2ms
  prisma:loadEnv skipping package.json at /home/snxk/package.json +0ms
  prisma:loadEnv skipping package.json at /home/package.json +0ms
  prisma:loadEnv skipping package.json at /package.json +0ms
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables loaded from ./.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: // .env
Environment variables loaded from .env
  prisma:engines using Node API: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig Using Query Engine Binary at: /home/snxk/.npm-global/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +0ms
Datasource "db": PostgreSQL database "XXXX", schema "public" at "XXX.eu-west-1.compute.amazonaws.com:5432"

  prisma:getDMMF Using Query Engine Binary at: /home/snxk/.npm-global/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +0ms
  prisma:getConfig Using Query Engine Binary at: /home/snxk/.npm-global/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +78ms
  prisma:getConfig Using Query Engine Binary at: /home/snxk/.npm-global/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +25ms
Error: Error: P1001: Can't reach database server at `XXX.eu-west-1.compute.amazonaws.com`:`5432`

Please make sure your database server is running at `XXX.eu-west-1.compute.amazonaws.com`:`5432`.
    at ensureDatabaseExists (/home/snxk/.npm-global/lib/node_modules/prisma/build/index.js:63712:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _MigrateDev.parse (/home/snxk/.npm-global/lib/node_modules/prisma/build/index.js:65680:28)
    at async main (/home/snxk/.npm-global/lib/node_modules/prisma/build/index.js:105366:18)
```

### Environment & setup

- OS: Arch Linux
- Database: PostgreSQL
- Node.js version: v16.5.0

### Prisma Version

```
Environment variables loaded from .env
prisma               : 2.29.1
@prisma/client       : 2.29.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at ../../.npm-global/lib/node_modules/prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at ../../.npm-global/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at ../../.npm-global/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at ../../.npm-global/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
```

**Comment by snxk** [comment]
It's the same for MySQL. Debug log of  `DEBUG="*" npx prisma migrate dev --name init`

```
  prisma:loadEnv project root found at /home/snxk/Projects/hello-prisma/package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from /home/snxk/Projects/hello-prisma/.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # Environment variables declared in this file are automatically made available to Prisma.
[dotenv][DEBUG] did not match key and value when parsing line 2: # See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables
[dotenv][DEBUG] did not match key and value when parsing line 3:
[dotenv][DEBUG] did not match key and value when parsing line 4: # Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server (Preview) and MongoDB (Preview).
[dotenv][DEBUG] did not match key and value when parsing line 5: # See the documentation for all the connection string options: https://pris.ly/d/connection-strings
[dotenv][DEBUG] did not match key and value when parsing line 6:
Environment variables loaded from .env
  prisma:engines using Node API: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +1ms
Prisma schema loaded from prisma/schema.prisma
  prisma:getConfig Using Query Engine Binary at: /home/snxk/Projects/hello-prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +0ms
Datasource "db": MySQL database "XXXXX" at "XXXXX-mysql.services.clever-cloud.com:3306"

  prisma:getDMMF Using Query Engine Binary at: /home/snxk/Projects/hello-prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +0ms
  prisma:getConfig Using Query Engine Binary at: /home/snxk/Projects/hello-prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +79ms
  prisma:getConfig Using Query Engine Binary at: /home/snxk/Projects/hello-prisma/node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x +30ms
Error: Error: P1001: Can't reach database server at `XXXXX-mysql.services.clever-cloud.com`:`3306`

Please make sure your database server is running at `XXXXX-mysql.services.clever-cloud.com`:`3306`.
    at ensureDatabaseExists (/home/snxk/Projects/hello-prisma/node_modules/prisma/build/index.js:63712:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _MigrateDev.parse (/home/snxk/Projects/hello-prisma/node_modules/prisma/build/index.js:65680:28)
    at async main (/home/snxk/Projects/hello-prisma/node_modules/prisma/build/index.js:105366:18)
```

**Comment by psiservices-ketan-javia** [comment]
I am also having the same issue connecting from Github Actions Workflow to an external MariaDB hosted on a shared VPS. Locally, I can connect to the same DB and issue Prisma commands, no issue.

**Comment by miguelff** [comment]
Hey @kjavia, I am able to connect to any external database without problems, are you able to use the database client `psql` or `mysql` to connect so such databases?

**Comment by psiservices-ketan-javia** [comment]
> Hey @kjavia, I am able to connect to any external database without problems, are you able to use the database client `psql` or `mysql` to connect so such databases?

Looks like firewall issue on the db server. I cannot connect from my local either.

**Comment by miguelff** [comment]
> Looks like firewall issue on the db server. I cannot connect from my local either.

Given this is the more likely cause for the problem @kjavia is experiencing, I will close this for the moment. Please comment below in case you could actually connect with a client and not prisma, and you unsuccessfully tried increasing the `connect_timeout` value.
