### ISSUE TITLE
PANIC in query-engine/core/src/response_ir/internal.rs:334:86called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by dannysofftie** [prisma/prisma#8810]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.17.5           | 
| OS              | Ubuntu 20.04 - debian-openssl-1.1.x|
| Prisma Client   | 2.29.1             |
| Query Engine    | query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a|
| Database        | MongoDB v4.4.8 Enterprise (MongoDB Atlas) |

## Query
```
query {
  findManyOrganisation {
    id
    name
    address
    employees
    contacts
    userId
    userUpdatedId
    createdAt
    updatedAt
    _count {
      admins
      borrowers
    }
  }
}
```

## Logs
```
  prisma:client clientVersion: 2.29.1  
  prisma:engine { cwd: '/mnt/Projects/work/app-api/prisma' }  
  prisma:engine Search for Query Engine in /mnt/Projects/work/app-api/node_modules/.prisma/client  
  prisma:engine Search for Query Engine in /mnt/Projects/work/app-api/node_modules/.prisma/client  
  plusX Execution permissions of /mnt/Projects/work/app-api/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  plusX Execution permissions of /mnt/Projects/work/app-api/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '37745' ] }  
  prisma:engine stdout  Started http server on http://127.0.0.1:37745  +2s
  prisma:engine Search for Query Engine in /mnt/Projects/work/app-api/node_modules/.prisma/client  
  plusX Execution permissions of /mnt/Projects/work/app-api/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +2s
  prisma:engine Client Version: 2.29.1  
  prisma:engine Engine Version: query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a  
  prisma:engine Active provider: mongodb  
  prisma:engine stdout  PANIC in query-engine/core/src/response_ir/internal.rs:334:86
called `Option::unwrap()` on a `None` value  +5s
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/mnt/Projects/work/app-api/node_modules/@prisma/client/runtime/index.js:27609:24)
  prisma:engine       at Socket.emit (events.js:412:35)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1317:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:37745
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  prisma:engine     errno: -111,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 37745
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/mnt/Projects/work/app-api/prisma' }  
  prisma:engine Search for Query Engine in /mnt/Projects/work/app-api/node_modules/.prisma/client  
  plusX Execution permissions of /mnt/Projects/work/app-api/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  +5s
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '35981' ] }  
  prisma:engine stdout  Started http server on http://127.0.0.1:35981  
  prisma:engine Search for Query Engine in /mnt/Projects/work/app-api/node_modules/.prisma/client  
  plusX Execution permissions of /mnt/Projects/work/app-api/node_modules/.prisma/client/query-engine-debian-openssl-1.1.x are fine  
  prisma:engine Client Version: 2.29.1  
  prisma:engine Engine Version: query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a  
  prisma:engine Active provider: mongodb  
  prisma:engine stdout  PANIC in query-engine/core/src/response_ir/internal.rs:334:86
called `Option::unwrap()` on a `None` value  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/mnt/Projects/work/app-api/node_modules/@prisma/client/runtime/index.js:27609:24)
  prisma:engine       at Socket.emit (events.js:412:35)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1317:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// in a resolver
 const organisations = await ctx.app.libs.prisma.organisation
      .findMany({
        include: {
          _count: {
            select: { admins: true, borrowers: true },
          },
        },
      })
```

## Schema
```prisma
datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["mongoDb", "referentialActions", "selectRelationCount"]
}

model User {
  id                   String            @id @default(dbgenerated()) @map("_id") @db.ObjectId
  name                 String?
  email                String?           @unique
  phone                String?           @unique
  idNumber             String?
  code                 String?
  password             String
  employeeNumber       String?
  address              String?
  role                 Role              @default(BORROWER)
  status               UserAccountStatus @default(ENABLED)
  avatar               Attachment?
  adminsOrganisation   Organisation?     @relation("OrganisationAdmins", fields: [adminsOrganisationId], references: [id])
  adminsOrganisationId String?           @db.ObjectId
  inOrganisation       Organisation?     @relation("OrganisationBorrowers", fields: [inOrganisationId], references: [id])
  inOrganisationId     String?           @db.ObjectId
  createdAt            DateTime          @default(now())
  updatedAt            DateTime          @updatedAt

  // map to table users
  @@map("users")
}

model Organisation {
  id            String      @id @default(dbgenerated()) @map("_id") @db.ObjectId
  name          String
  address       String?
  employees     Int?
  contacts      String?
  logo          Attachment?
  admins        User[]      @relation("OrganisationAdmins")
  borrowers     User[]      @relation("OrganisationBorrowers")
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt

  @@map("organisations")
}

enum Role {
  SUPER_ADMIN
  LENDER_ADMIN
  BORROWER
}

enum UserAccountStatus {
  ENABLED
  DISABLED
  UNVERIFIED
}
```
Prisma crushes with `_count`, an `include` like below works perfectly fine.
```ts
 const organisations = await ctx.app.libs.prisma.organisation.findMany({
    include: {
      //   _count: {
      //     select: { admins: true, borrowers: true },
      //   },
      admins: true,
      borrowers: true,
    },
  });
```

**Comment by janpio** [comment]
The related issues seems to be fixed in current `dev` versions of Prisma: https://github.com/prisma/prisma/issues/9651#issuecomment-1039396782 Can you also take another look @dannysofftie? `npm install prisma@dev @prisma/client@dev` should install those versions.
