### ISSUE TITLE
PANIC in query-engine\connectors\sql-query-connector\src\database\operations\write.rs:95:60called `Result::unwrap()` on an `Err` value: ScalarFieldNotFound { name: "device_id", model: "ValueMetrics" }

### ISSUE THREAD

**Issue by Swymby** [prisma/prisma#8813]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | windows            |
| Prisma Client   | 2.29.1             |
| Query Engine    | query-engine f3e341280d96d0abc068f97e959ddf01f321a858|
| Database        | undefined|

## Query
```
mutation {
  createManyValueMetrics(data: [
    {
      dataIdentityId: "X"
      deviceId: "X"
      workspaceId: "X"
      tenantId: "X"
      measurements: "X"
      time: "X"
    }
  ]) {
    count
  }
}
```

## Logs
```
  prisma:client clientVersion: 2.29.1  
  prisma:engine Search for Query Engine in C:\Users\jan.svimbersky\source\repos\zat.simonet.nx\node_modules\.prisma\client  
  prisma:engine {
  prisma:engine   cwd: 'C:\\Users\\jan.svimbersky\\source\\repos\\zat.simonet.nx\\prisma'
  prisma:engine }  
  prisma:engine Search for Query Engine in C:\Users\jan.svimbersky\source\repos\zat.simonet.nx\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '53973' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Fetched a connection from the pool  
  prisma:engine stdout  Started http server on http://127.0.0.1:53973  
  prisma:engine Search for Query Engine in C:\Users\jan.svimbersky\source\repos\zat.simonet.nx\node_modules\.prisma\client  
  prisma:engine Client Version: 2.29.1  
  prisma:engine Engine Version: query-engine f3e341280d96d0abc068f97e959ddf01f321a858  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  Fetched a connection from the pool  +9s
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  PANIC in query-engine\connectors\sql-query-connector\src\database\operations\write.rs:95:60
called `Result::unwrap()` on an `Err` value: ScalarFieldNotFound { name: "data_identity_id", model: "ValueMetrics" }  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:53973
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 53973
  prisma:engine   }
  prisma:engine }  
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine {
  prisma:engine   cwd: 'C:\\Users\\jan.svimbersky\\source\\repos\\zat.simonet.nx\\prisma'
  prisma:engine }  
  prisma:engine Search for Query Engine in C:\Users\jan.svimbersky\source\repos\zat.simonet.nx\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '53982' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Fetched a connection from the pool  
  prisma:engine stdout  Started http server on http://127.0.0.1:53982  
  prisma:engine Search for Query Engine in C:\Users\jan.svimbersky\source\repos\zat.simonet.nx\node_modules\.prisma\client  
  prisma:engine stdout  Fetched a connection from the pool  
  prisma:engine stdout  Unknown error  
  prisma:engine stdout  PANIC in query-engine\connectors\sql-query-connector\src\database\operations\write.rs:95:60
called `Result::unwrap()` on an `Err` value: ScalarFieldNotFound { name: "device_id", model: "ValueMetrics" }  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
await this.dataConnect.valueMetrics.createMany({
    data: [
        {
            dataIdentityId: 'h8mu1sPPC9',
            deviceId: '92h33aff-5',
            workspaceId: 'zHpBRyU1e_',
            tenantId: 'tSGIf3j_VL',
            measurements: { temp: 37.5, humidity: 90, alarm: 1 },
            time: '2021-08-18T14:01:30.296Z'
          },
          {
            dataIdentityId: 'gUaAoGtTs6',
            deviceId: '92h33aff-5',
            workspaceId: 'kh0x_EyrJM',
            tenantId: 'A6tJK8fTQQ',
            measurements: { temp: 37.5, humidity: 90, alarm: 1 },
            time: '2021-08-18T14:01:30.296Z'
          }
     ]
})
```

## Schema
```prisma
model ValueMetrics {
    id Int @default(autoincrement())

    dataIdentityId String @map("data_identity_id")
    deviceId String @map("device_id")
    tenantId String @map("tenant_id")
    workspaceId String @map("workspace_id")

    time DateTime
    measurements Json

    @@map("value_metrics")
    @@id([id, time])

    @@index(fields: [time], name: "value_metrics_time_idx")
}

```

Hello, when I try to use createMany, the prisma client panics. Using just create works OK. There are no foreign keys or references or anything, but I am using timescaleDB and ValueMetrics is a hypertable. Though as I said, create works fine.

**Comment by janpio** [comment]
Can you maybe check if this also fails when using plain PostgreSQL? That would help us narrow this down a lot already.

**Comment by Swymby** [comment]
Alright, it's working now. 
I tried it with postgres 12 and 13, then returned to timescale and everything is working fine now. I guess my prisma client wasn't generated properly after I had updated from 2.24.0 to 2.29.1 (ofc I ran prisma generate command).

Anyway all is fine on my end, thanks for your help.
