### ISSUE TITLE
PANIC in query-engine\core\src\response_ir\internal.rs:334:86called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by dariusj18** [prisma/prisma#8861]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | windows            |
| Prisma Client   | 2.29.1             |
| Query Engine    | query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a|
| Database        | Postgres (see schema below) |

## Query
```
query {
  findManyPosts(
    skip: 5
    take: 5
    orderBy: [
      {
        id: asc
      }
    ]
  ) {
    id
    createdAt
    updatedAt
    is_deleted
    title
    user {
      id
      createdAt
      updatedAt
      is_deleted
      username
      _count {
        posts
      }
    }
  }
}
```

## Logs
```
  prisma:client clientVersion: 2.29.1  
  prisma:engine Search for Query Engine in C:\PROJECT_FOLDER\node_modules\.prisma\client  
  prisma:engine {
  prisma:engine   cwd: 'C:\\PROJECT_FOLDER\\prisma'
  prisma:engine }  
  prisma:engine Search for Query Engine in C:\PROJECT_FOLDER\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '65337' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:65337  
  prisma:engine Search for Query Engine in C:\PROJECT_FOLDER\node_modules\.prisma\client  
  prisma:engine Client Version: 2.29.1  
  prisma:engine Engine Version: query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in query-engine\core\src\response_ir\internal.rs:334:86
called `Option::unwrap()` on a `None` value  +2s
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:65337
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  prisma:engine     errno: -4078,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 65337
  prisma:engine   }
  prisma:engine }  
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine {
  prisma:engine   cwd: 'C:\\PROJECT_FOLDER\\prisma'
  prisma:engine }  
  prisma:engine Search for Query Engine in C:\PROJECT_FOLDER\node_modules\.prisma\client  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '58392' ] }  
  prisma:engine stdout  Starting a postgresql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:58392  
  prisma:engine Search for Query Engine in C:\PROJECT_FOLDER\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\core\src\response_ir\internal.rs:334:86
called `Option::unwrap()` on a `None` value  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  prisma:engine     errno: -4077,
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
this.prisma.post.findMany({
  skip: offset,
  take: limit,
  orderBy,
  include: {
    user: {
      include: {
        _count: {
          select: {
            posts: true,
          }
        }
      }
    }
  }
});
```

## Schema
```prisma
datasource db {
  url      = env("POSTGRES_URL")
  provider = "postgres"
}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["interactiveTransactions", "selectRelationCount"]
}

model User {
  id         String   @id @default(uuid()) @db.Uuid
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
  is_deleted Boolean  @default(false)
  username   String

  posts Post[]
}

model Post {
  id         String   @id @default(uuid()) @db.Uuid
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
  is_deleted Boolean  @default(false)
  title      String

  user   User @relation(fields: [userId], references: [id])
  userId String   @db.Uuid
}
```

**Comment by dariusj18** [comment]
Just tested and it still occurs with Prisma 2.30.0

**Comment by dariusj18** [comment]
Here's a demo with the error

https://github.com/dariusj18/prisma_8861

**Comment by hayes** [comment]
I just ran into the same issue using sqlite, so doesn't seem db specific.

**Comment by janpio** [comment]
I can confirm this with your reproduction, when I create some simple data first:

```ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient({
  log: [
    { emit: 'stdout', level: 'query' },
    { emit: 'stdout', level: 'info' },
    { emit: 'stdout', level: 'warn' },
    { emit: 'stdout', level: 'error' },
  ],
})

async function main() {
  const user = await prisma.user.create({ data: {
     username: "foo",
     posts: {
        create: [
          { title: 'How to make an omelette' },
          { title: 'How to eat an omelette' },
        ],
      }, 
  }})

  console.log(user);
  
}

main()
  .catch((e) => {
    throw e
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

```
