### ISSUE TITLE
Error: P1001: Can't reach database server when including large table

### ISSUE THREAD

**Issue by nwidynski** [prisma/prisma#8878]
### Bug description

I am trying to query a table with around 10,000 rows and join a table with ~100,000 rows on it. Im expecting this query to run successfully or timeout at least, but it will not even show up in the query log as it will hit the error right after the graphql prisma:client request is printed out. I have tried increasing the timeout or check if something is going wrong at the database level, but the raw query runs fine, when ran manually. The error looks like the following:

```
{
    "errorMessage": "\nInvalid `prisma.item.findMany()` invocation:\n\n\n  Can't reach database server at `localhost`:`5432`\n\nPlease make sure your database server is running at `localhost`:`5432`.",
    "errorType": "PrismaClientKnownRequestError3",
    "stackTrace": [
        "Error: ",
        "Invalid `prisma.item.findMany()` invocation:",
        "",
        "",
        "  Can't reach database server at `localhost`:`5432`",
        "",
        "Please make sure your database server is running at `localhost`:`5432`.",
        "    at cb (/Users/nschroeter/Documents/workspace/RamboTrades/hercules-serverless/node_modules/@prisma/client/runtime/index.js:36374:17)",
        "    at processTicksAndRejections (node:internal/process/task_queues:94:5)",
        "    at async /Users/nschroeter/Documents/workspace/RamboTrades/hercules-serverless/dist/apps/updatePrices/main.js:219:27",
        "    at async AppService.run (/Users/nschroeter/Documents/workspace/RamboTrades/hercules-serverless/dist/apps/updatePrices/main.js:1482:23)",
        "    at async handler (/Users/nschroeter/Documents/workspace/RamboTrades/hercules-serverless/dist/apps/updatePrices/main.js:1910:5)"
    ]
}
```

### How to reproduce

1. Create a PostgreSQL 12 database with the default image via docker-compose
2. Create 2 tables, each with around 20 columns
3. Link them with a one-to-many relationship
4. Insert a couple (>100k) rows in both tables
5. Run a findMany query on the first table and include the second

### Expected behavior

Im expecting the query to either resolve or timeout.

### Prisma information

```
  prisma:client:fetcher Error: Can't reach database server at `localhost`:`5432`
  prisma:client:fetcher 
  prisma:client:fetcher Please make sure your database server is running at `localhost`:`5432`.
  prisma:client:fetcher     at BinaryEngine.graphQLToJSError (/Users/nschroeter/Documents/workspace/RamboTrades/hercules-serverless/node_modules/@prisma/client/runtime/index.js:29972:16)
  prisma:client:fetcher     at BinaryEngine.request (/Users/nschroeter/Documents/workspace/RamboTrades/hercules-serverless/node_modules/@prisma/client/runtime/index.js:29857:24)
  prisma:client:fetcher     at processTicksAndRejections (node:internal/process/task_queues:94:5)
  prisma:client:fetcher     at async cb (/Users/nschroeter/Documents/workspace/RamboTrades/hercules-serverless/node_modules/@prisma/client/runtime/index.js:36344:26)
  prisma:client:fetcher     at async /Users/nschroeter/Documents/workspace/RamboTrades/hercules-serverless/dist/apps/updatePrices/main.js:219:27
  prisma:client:fetcher     at async AppService.run (/Users/nschroeter/Documents/workspace/RamboTrades/hercules-serverless/dist/apps/updatePrices/main.js:1482:23)
  prisma:client:fetcher     at async handler (/Users/nschroeter/Documents/workspace/RamboTrades/hercules-serverless/dist/apps/updatePrices/main.js:1910:5)
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: 14
- Other: NestJS v8

### Prisma Version

```
prisma               : 2.29.1
@prisma/client       : 2.29.1
Current platform     : darwin
Query Engine         : query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 1be4cd60b89afa04b192acb1ef47758a39810f3a (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 1be4cd60b89afa04b192acb1ef47758a39810f3a
Studio               : 0.419.0
Preview Features     : filterJson, referentialActions
```

**Comment by janpio** [comment]
Do you run that query right after you added all this data or are these two separate scripts?
Can you provide a repository with the scripts and data you are testing this with?

**Comment by nwidynski** [comment]
> Do you run that query right after you added all this data or are these two separate scripts?
> Can you provide a repository with the scripts and data you are testing this with?

This happens at any point when querying the data. Ive done some digging and it seems related to prisma translating the include statement into 2 seperate SQL statements. The second one being a WHERE IN with a huge amount of data from the first query. Ive setup a minimum reproduction repo here: https://github.com/nwidynski/reproduction-prisma-8878

**Comment by janpio** [comment]
Thanks so much, that will help us a lot. The error message is probably that misleading as the database connection "dies" for some reason. We will definitely look into that with your reproduction. Thanks!

**Comment by nwidynski** [comment]
@janpio any progress on this? It kinda renders prisma unusable for us.

**Comment by pantharshit00** [comment]
Hey @nwidynski 

Sorry for the delay here. I actually forgot to post my findings here. I wasn't able to reproduce this when I attempted this locally. I tried multiple time but it didn't crash for me. 


What I will suggest here would be to upgrade to v3 which has some performance improvement and set the `QUERY_BATCH_SIZE` environment variable to `QUERY_BATCH_SIZE=5000` (or depending upon your postgres installation) to limit the number of items in `IN` clause. Using JOINs for many such queries a performance optimization that we will tackle later on. 


If you are still hitting this even after the above, please do let me know.

**Comment by hnrw** [comment]
> > I think, this is related/identical to #8832 and #9275. A reproduction repo exists in #8832.
> 
> Have you tried the fixes mentioned above? I haven't got around to implementing those. It could be related to the database running inside docker, since im also doing that? Also good to know that upgrading to v3 won't fix the issue.

Not the person you replied to, but I don't think docker is the issue. I had the error on a local db and a heroku managed db. #9275

**Comment by janpio** [comment]
As posted before, closely related to https://github.com/prisma/prisma/issues/9275 but I will keep this one open as some additional information is available here.

**Comment by cyrus-za** [comment]
I just ran into this and setting `QUERY_BATCH_SIZE=5000` fixes it for me. Thanks for saving me a lot of time @janpio and @pantharshit00

**Comment by janpio** [comment]
Do you have a reproduction by chance @cyrus-za? That would still be super helpful here.

**Comment by some-user123** [comment]
Have you seen the two reproduction repo already posted more then six months ago? https://github.com/prisma/prisma/issues/8832#issuecomment-903251153
https://github.com/prisma/prisma/issues/8878#issuecomment-905291403

What is missing to reproduce?

**Comment by janpio** [comment]
The one in this thread was tried by @pantharshit00 above and could not be reproduce, hence this issue is back to status `bug/0-unknown`. Even if the other one in #8832 would be reproducible, situations are often slighty different so when someone pops into a thread saying "I have the same problem and could work around it", asking for their reproduction it still helpful.

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.

**Comment by jkomyno** [comment]
If you stumble upon this issue, please see [this comment](https://github.com/prisma/prisma/issues/8832#issuecomment-1237850099).

**Comment by jkomyno** [comment]
We have closed the original issue in `prisma@4.4.0`, please see [this comment](https://github.com/prisma/prisma/issues/8832#issuecomment-1260533913).
