### ISSUE TITLE
Prisma crash in 2.29.1 `PANIC in query-engine/core/src/response_ir/internal.rs:334:86 called Option::unwrap() on a None value`

### ISSUE THREAD

**Issue by coffeemug** [prisma/prisma#8915]
Github told me the URL was too long, so pasting here manually. I'm on 2.29.1.

```
ERRORING: Error:
Invalid `prisma.timeline.findUnique()` invocation:


  PANIC in query-engine/core/src/response_ir/internal.rs:334:86
called `Option::unwrap()` on a `None` value

This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v16.4.0++++++++++++%7C+%0A%7C+OS++++++++++++++%7C+darwin+++++++++++++%7C%0A%7C+Prisma+Client+++%7C+2.29.1+++++++++++++%7C%0A%7C+Query+Engine++++%7C+query-engine+1be4cd60b89afa04b192acb1ef47758a39810f3a%7C%0A%7C+Database++++++++%7C+undefined%7C%0A%0A%0A%0A%23%23+Query%0A%60%60%60%0A%7B%22X%22%3Afalse%7D%0A%60%60%60%0A%0A%23%23+Logs%0A%60%60%60%0Arisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+SocketError%3A+other+side+closed%0A++prisma%3Aengine+++++++at+Socket.onSocketEnd+%28%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A27609%3A24%29%0A++prisma%3Aengine+++++++at+Socket.emit+%28node%3Aevents%3A406%3A35%29%0A++prisma%3Aengine+++++++at+endReadableNT+%28node%3Ainternal%2Fstreams%2Freadable%3A1329%3A12%29%0A++prisma%3Aengine+++++++at+processTicksAndRejections+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A83%3A21%29+%7B%0A++prisma%3Aengine+++++code%3A+%27UND_ERR_SOCKET%27%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A++prisma%3Aengine+%7B+cwd%3A+%27%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fprisma%27+%7D++%0A++prisma%3Aengine+Search+for+Query+Engine+in+%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F.prisma%2Fclient++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+Error%3A+connect+ECONNREFUSED+127.0.0.1%3A58924%0A++prisma%3Aengine+++++++at+TCPConnectWrap.afterConnect+%5Bas+oncomplete%5D+%28node%3Anet%3A1132%3A16%29+%7B%0A++prisma%3Aengine+++++errno%3A+-61%2C%0A++prisma%3Aengine+++++code%3A+%27ECONNREFUSED%27%2C%0A++prisma%3Aengine+++++syscall%3A+%27connect%27%2C%0A++prisma%3Aengine+++++address%3A+%27127.0.0.1%27%2C%0A++prisma%3Aengine+++++port%3A+58924%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A++plusX+Execution+permissions+of+%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine++%2B21s%0A++prisma%3Aengine+%7B+flags%3A+%5B+%27--enable-raw-queries%27%2C+%27--port%27%2C+%2759021%27+%5D+%7D++%0A++prisma%3Aengine+stdout++Starting+a+postgresql+pool+with+5+connections.++%0A++prisma%3Aengine+stdout++Started+http+server+on+http%3A%2F%2F127.0.0.1%3A59021++%0A++prisma%3Aengine+Search+for+Query+Engine+in+%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F.prisma%2Fclient++%0A++plusX+Execution+permissions+of+%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine++%0A++prisma%3Aengine+Client+Version%3A+2.29.1++%0A++prisma%3Aengine+Engine+Version%3A+query-engine+1be4cd60b89afa04b192acb1ef47758a39810f3a++%0A++prisma%3Aengine+Active+provider%3A+postgresql++%0A++prisma%3Aengine+stdout++PANIC+in+query-engine%2Fcore%2Fsrc%2Fresponse_ir%2Finternal.rs%3A334%3A86%0Acalled+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+SocketError%3A+other+side+closed%0A++prisma%3Aengine+++++++at+Socket.onSocketEnd+%28%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A27609%3A24%29%0A++prisma%3Aengine+++++++at+Socket.emit+%28node%3Aevents%3A406%3A35%29%0A++prisma%3Aengine+++++++at+endReadableNT+%28node%3Ainternal%2Fstreams%2Freadable%3A1329%3A12%29%0A++prisma%3Aengine+++++++at+processTicksAndRejections+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A83%3A21%29+%7B%0A++prisma%3Aengine+++++code%3A+%27UND_ERR_SOCKET%27%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+Error%3A+connect+ECONNREFUSED+127.0.0.1%3A59021%0A++prisma%3Aengine+++++++at+TCPConnectWrap.afterConnect+%5Bas+oncomplete%5D+%28node%3Anet%3A1132%3A16%29+%7B%0A++prisma%3Aengine+++++errno%3A+-61%2C%0A++prisma%3Aengine+++++code%3A+%27ECONNREFUSED%27%2C%0A++prisma%3Aengine+++++syscall%3A+%27connect%27%2C%0A++prisma%3Aengine+++++address%3A+%27127.0.0.1%27%2C%0A++prisma%3Aengine+++++port%3A+59021%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A&title=PANIC+in+query-engine%2Fcore%2Fsrc%2Fresponse_ir%2Finternal.rs%3A334%3A86%0Acalled+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value&template=bug_report.mdhttps://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v16.4.0++++++++++++%7C+%0A%7C+OS++++++++++++++%7C+darwin+++++++++++++%7C%0A%7C+Prisma+Client+++%7C+2.29.1+++++++++++++%7C%0A%7C+Query+Engine++++%7C+query-engine+1be4cd60b89afa04b192acb1ef47758a39810f3a%7C%0A%7C+Database++++++++%7C+undefined%7C%0A%0A%0A%0A%23%23+Query%0A%60%60%60%0A%7B%22X%22%3Afalse%7D%0A%60%60%60%0A%0A%23%23+Logs%0A%60%60%60%0Arisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+SocketError%3A+other+side+closed%0A++prisma%3Aengine+++++++at+Socket.onSocketEnd+%28%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A27609%3A24%29%0A++prisma%3Aengine+++++++at+Socket.emit+%28node%3Aevents%3A406%3A35%29%0A++prisma%3Aengine+++++++at+endReadableNT+%28node%3Ainternal%2Fstreams%2Freadable%3A1329%3A12%29%0A++prisma%3Aengine+++++++at+processTicksAndRejections+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A83%3A21%29+%7B%0A++prisma%3Aengine+++++code%3A+%27UND_ERR_SOCKET%27%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A++prisma%3Aengine+%7B+cwd%3A+%27%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fprisma%27+%7D++%0A++prisma%3Aengine+Search+for+Query+Engine+in+%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F.prisma%2Fclient++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+Error%3A+connect+ECONNREFUSED+127.0.0.1%3A58924%0A++prisma%3Aengine+++++++at+TCPConnectWrap.afterConnect+%5Bas+oncomplete%5D+%28node%3Anet%3A1132%3A16%29+%7B%0A++prisma%3Aengine+++++errno%3A+-61%2C%0A++prisma%3Aengine+++++code%3A+%27ECONNREFUSED%27%2C%0A++prisma%3Aengine+++++syscall%3A+%27connect%27%2C%0A++prisma%3Aengine+++++address%3A+%27127.0.0.1%27%2C%0A++prisma%3Aengine+++++port%3A+58924%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A++plusX+Execution+permissions+of+%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine++%2B21s%0A++prisma%3Aengine+%7B+flags%3A+%5B+%27--enable-raw-queries%27%2C+%27--port%27%2C+%2759021%27+%5D+%7D++%0A++prisma%3Aengine+stdout++Starting+a+postgresql+pool+with+5+connections.++%0A++prisma%3Aengine+stdout++Started+http+server+on+http%3A%2F%2F127.0.0.1%3A59021++%0A++prisma%3Aengine+Search+for+Query+Engine+in+%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F.prisma%2Fclient++%0A++plusX+Execution+permissions+of+%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F.prisma%2Fclient%2Fquery-engine-darwin+are+fine++%0A++prisma%3Aengine+Client+Version%3A+2.29.1++%0A++prisma%3Aengine+Engine+Version%3A+query-engine+1be4cd60b89afa04b192acb1ef47758a39810f3a++%0A++prisma%3Aengine+Active+provider%3A+postgresql++%0A++prisma%3Aengine+stdout++PANIC+in+query-engine%2Fcore%2Fsrc%2Fresponse_ir%2Finternal.rs%3A334%3A86%0Acalled+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+SocketError%3A+other+side+closed%0A++prisma%3Aengine+++++++at+Socket.onSocketEnd+%28%2FUsers%2Fcoffeemug%2Fprojects%2Falias-mono%2Fnode_modules%2F%40prisma%2Fclient%2Fruntime%2Findex.js%3A27609%3A24%29%0A++prisma%3Aengine+++++++at+Socket.emit+%28node%3Aevents%3A406%3A35%29%0A++prisma%3Aengine+++++++at+endReadableNT+%28node%3Ainternal%2Fstreams%2Freadable%3A1329%3A12%29%0A++prisma%3Aengine+++++++at+processTicksAndRejections+%28node%3Ainternal%2Fprocess%2Ftask_queues%3A83%3A21%29+%7B%0A++prisma%3Aengine+++++code%3A+%27UND_ERR_SOCKET%27%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A++prisma%3Aengine+%7B%0A++prisma%3Aengine+++error%3A+Error%3A+connect+ECONNREFUSED+127.0.0.1%3A59021%0A++prisma%3Aengine+++++++at+TCPConnectWrap.afterConnect+%5Bas+oncomplete%5D+%28node%3Anet%3A1132%3A16%29+%7B%0A++prisma%3Aengine+++++errno%3A+-61%2C%0A++prisma%3Aengine+++++code%3A+%27ECONNREFUSED%27%2C%0A++prisma%3Aengine+++++syscall%3A+%27connect%27%2C%0A++prisma%3Aengine+++++address%3A+%27127.0.0.1%27%2C%0A++prisma%3Aengine+++++port%3A+59021%0A++prisma%3Aengine+++%7D%0A++prisma%3Aengine+%7D++%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A&title=PANIC+in+query-engine%2Fcore%2Fsrc%2Fresponse_ir%2Finternal.rs%3A334%3A86%0Acalled+%60Option%3A%3Aunwrap%28%29%60+on+a+%60None%60+value&template=bug_report.md

If you want the Prisma team to look into it, please open the link above 🙏
To increase the chance of success, please post your schema and a snippet of
how you used Prisma Client in the issue.
```

**Comment by Jolg42** [comment]
Recovered from URL by manual parsing

Hi Prisma Team! My Prisma Client just crashed. 

## Versions
| Name | Version | 
|-----------------|--------------------| 
| Node | v16.4.0 |
| OS | darwin | 
| Prisma Client | 2.29.1 | 
| Query Engine | query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a|
| Database | undefined|

## Query 
``` {"X":false} ```

## Logs 
``` prisma:engine { prisma:engine error: SocketError: other side closed prisma:engine at Socket.onSocketEnd (/Users/coffeemug/projects/alias-mono/node_modules/@prisma/client/runtime/index.js:27609:24) prisma:engine at Socket.emit (node:events:406:35) prisma:engine at endReadableNT (node:internal/streams/readable:1329:12) prisma:engine at processTicksAndRejections (node:internal/process/task_queues:83:21) { prisma:engine code: 'UND_ERR_SOCKET' prisma:engine } prisma:engine } prisma:engine { cwd: '/Users/coffeemug/projects/alias-mono/prisma' } prisma:engine Search for Query Engine in /Users/coffeemug/projects/alias-mono/node_modules/.prisma/client prisma:engine { prisma:engine error: Error: connect ECONNREFUSED 127.0.0.1:58924 prisma:engine at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1132:16) { prisma:engine errno: -61, prisma:engine code: 'ECONNREFUSED', prisma:engine syscall: 'connect', prisma:engine address: '127.0.0.1', prisma:engine port: 58924 prisma:engine } prisma:engine } plusX Execution permissions of /Users/coffeemug/projects/alias-mono/node_modules/.prisma/client/query-engine-darwin are fine +21s prisma:engine { flags: [ '--enable-raw-queries', '--port', '59021' ] } prisma:engine stdout Starting a postgresql pool with 5 connections. prisma:engine stdout Started http server on http://127.0.0.1:59021 prisma:engine Search for Query Engine in /Users/coffeemug/projects/alias-mono/node_modules/.prisma/client plusX Execution permissions of /Users/coffeemug/projects/alias-mono/node_modules/.prisma/client/query-engine-darwin are fine prisma:engine Client Version: 2.29.1 prisma:engine Engine Version: query-engine 1be4cd60b89afa04b192acb1ef47758a39810f3a prisma:engine Active provider: postgresql prisma:engine stdout PANIC in query-engine/core/src/response_ir/internal.rs:334:86 called `Option::unwrap()` on a `None` value prisma:engine { prisma:engine error: SocketError: other side closed prisma:engine at Socket.onSocketEnd (/Users/coffeemug/projects/alias-mono/node_modules/@prisma/client/runtime/index.js:27609:24) prisma:engine at Socket.emit (node:events:406:35) prisma:engine at endReadableNT (node:internal/streams/readable:1329:12) prisma:engine at processTicksAndRejections (node:internal/process/task_queues:83:21) { prisma:engine code: 'UND_ERR_SOCKET' prisma:engine } prisma:engine } prisma:engine { prisma:engine error: Error: connect ECONNREFUSED 127.0.0.1:59021 prisma:engine at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1132:16) { prisma:engine errno: -61, prisma:engine code: 'ECONNREFUSED', prisma:engine syscall: 'connect', prisma:engine address: '127.0.0.1', prisma:engine port: 59021 prisma:engine } prisma:engine } ```

**Comment by pantharshit00** [comment]
@coffeemug Hmm, the information that automatic reporting collected is not sufficient for us to work on this. 

Can you please provide more details if possible like the query that you were running and the schema which you were using?

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
