### ISSUE TITLE
Invalid `.env` file leads to `Error: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#8919]
```
DATABASE_URL_WITHOUT_SCHEMA="postgresql://johndoe:randompassword@localhost:5432/mydb"
DATABASE_URL="${DATABASE_URL}?schema=public"
```

(Note how `DATABASE_URL` refers to itself, isntead of `DATABASE_URL_WITHOUT_SCHEMA` accidentally)

leads to

```
C:\Users\Jan\Documents\throwaway\docs1667>npx prisma -v
Error: Maximum call stack size exceeded
```

or with `DEBUG=*`:

```
C:\Users\Jan\Documents\throwaway\docs1667>npx prisma -v
  prisma:loadEnv project root found at C:\Users\Jan\Documents\throwaway\docs1667\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\docs1667\.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # Environment variables declared in this file are automatically made available to Prisma.
[dotenv][DEBUG] did not match key and value when parsing line 2: # See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables
[dotenv][DEBUG] did not match key and value when parsing line 3:
[dotenv][DEBUG] did not match key and value when parsing line 4: # Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server (Preview) and MongoDB (Preview).
[dotenv][DEBUG] did not match key and value when parsing line 5: # See the documentation for all the connection string options: https://pris.ly/d/connection-strings
[dotenv][DEBUG] did not match key and value when parsing line 6: 
Error: RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at interpolate (C:\Users\Jan\Documents\throwaway\docs1667\node_modules\prisma\build\index.js:57376:32)
    at C:\Users\Jan\Documents\throwaway\docs1667\node_modules\prisma\build\index.js:57391:19
    at Array.reduce (<anonymous>)
    at interpolate (C:\Users\Jan\Documents\throwaway\docs1667\node_modules\prisma\build\index.js:57377:22)
    at C:\Users\Jan\Documents\throwaway\docs1667\node_modules\prisma\build\index.js:57391:19
    at Array.reduce (<anonymous>)
    at interpolate (C:\Users\Jan\Documents\throwaway\docs1667\node_modules\prisma\build\index.js:57377:22)
    at C:\Users\Jan\Documents\throwaway\docs1667\node_modules\prisma\build\index.js:57391:19
    at Array.reduce (<anonymous>)
```

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/131854921-c9f5e59d-11cc-44b6-941a-b9fff5e454a0.png)
Easily reproducible.

**Comment by jkomyno** [comment]
I confirm the bug is still present as of `prisma@4.3.0`.

**Comment by LuisAlejandro** [comment]
This bug is still happening in prisma 4.3.0 for me.

**Comment by janpio** [comment]
Technically this is not a bug by the way, just a suboptimal error message. When you are getting this, it should mean that you are trying to expand an env var into itself, which of course can not work. But if would be better if the tools we are using would call that out to instead of just imploding with `Maximum call stack size exceeded`.
