### ISSUE TITLE
PANIC in query-engine\core\src\response_ir\internal.rs:395:26Application logic invariant error: received null value for field order which may not be null

### ISSUE THREAD

**Issue by TienAnhVo** [prisma/prisma#8924]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v12.13.0           | 
| OS              | windows            |
| Prisma Client   | 2.21.0             |
| Query Engine    | query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d|
| Database        | undefined|

## Query
```
query {
  findManyOrderItem(where: {
    id: 5
    OR: [
      {
        active: true
      },
      {
        active: false
        order_item_status_id: {
          in: [5, 5]
        }
      }
    ]
  }) {
    id
    invoice_id
    order_id
    sku_id
    user_id
    customer_buyer_id
    order_item_status_id
    customer_seller_id
    amount_qty
    total_qty
    origin_unit_price
    sale_unit_price
    total_price
    tax
    catch_weight
    active
    sku {
      name
      image
      product {
        name
        tenant_id
        image
      }
      oom {
        name
      }
    }
    customer {
      name
      alias_name
      minimum_order
      hub
    }
    order {
      orderStatus {
        name
      }
    }
    invoice {
      delivery_address
    }
  }
}
```

## Logs
```
ll  
  prisma:tryLoadEnv Environment variables not found at undefined  
  prisma:tryLoadEnv No Environment variables loaded  
  prisma:tryLoadEnv Environment variables not found at null  
  prisma:tryLoadEnv Environment variables not found at undefined  
  prisma:tryLoadEnv No Environment variables loaded  
  prisma:client clientVersion: 2.21.0  
  prisma:engine Search for Query Engine in C:\treedots\common\temp\node_modules\.prisma\client  
  prisma:engine { cwd: 'C:\\treedots\\packages\\prisma' }  +6m
  prisma:engine Search for Query Engine in C:\treedots\common\temp\node_modules\.prisma\client  
  prisma:engine {
  prisma:engine   flags: [
  prisma:engine     '--enable-experimental=orderByAggregateGroup',
  prisma:engine     '--enable-raw-queries',
  prisma:engine     '--port',
  prisma:engine     '62364'
  prisma:engine   ]
  prisma:engine }  
  prisma:engine stdout  Starting a mysql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:62364  
  prisma:engine Search for Query Engine in C:\treedots\common\temp\node_modules\.prisma\client  
  prisma:engine Client Version: 2.21.0  
  prisma:engine Engine Version: query-engine e421996c87d5f3c8f7eeadd502d4ad402c89464d  
  prisma:engine Active provider: mysql  
  prisma:engine stdout  PANIC in query-engine\core\src\response_ir\internal.rs:395:26
Application logic invariant error: received null value for field order which may not be null  +2m
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:201:27) {
  prisma:engine     errno: 'ECONNRESET',
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:62364
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
  prisma:engine     errno: 'ECONNREFUSED',
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 62364
  prisma:engine   }
  prisma:engine }  +2s
  prisma:engine There is a child that still runs and we want to start again  
  prisma:engine { cwd: 'C:\\treedots\\packages\\prisma' }  
  prisma:engine Search for Query Engine in C:\treedots\common\temp\node_modules\.prisma\client  
  prisma:engine {
  prisma:engine   flags: [
  prisma:engine     '--enable-experimental=orderByAggregateGroup',
  prisma:engine     '--enable-raw-queries',
  prisma:engine     '--port',
  prisma:engine     '62395'
  prisma:engine   ]
  prisma:engine }  
  prisma:engine stdout  Starting a mysql pool with 9 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:62395  
  prisma:engine Search for Query Engine in C:\treedots\common\temp\node_modules\.prisma\client  
  prisma:engine stdout  PANIC in query-engine\core\src\response_ir\internal.rs:395:26
Application logic invariant error: received null value for field order which may not be null  
  prisma:engine {
  prisma:engine   error: Error: read ECONNRESET
  prisma:engine       at TCP.onStreamRead (internal/stream_base_commons.js:201:27) {
  prisma:engine     errno: 'ECONNRESET',
  prisma:engine     code: 'ECONNRESET',
  prisma:engine     syscall: 'read'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
