### ISSUE TITLE
Patch releases: Creation of tags on prisma-engines fails

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9013]
https://buildkite.com/prisma/prisma2-publish/builds/5283#f46424f5-70b9-4420-af19-c77b0c430d7a/236-3448

```
[2021-08-30T16:19:27Z] Going to tag the engines repo dryRun: false
[2021-08-30T16:19:27Z] ./.         git clone --depth=50 https://github.com/prisma/prisma-engines.git
[2021-08-30T16:19:27Z] Cloning into 'prisma-engines'...
[2021-08-30T16:19:28Z] remote: Enumerating objects: 3506, done.
remote: Counting objects: 100% (3506/3506), done.
remote: Compressing objects: 100% (2326/2326), done.
remote: Total 3506 (delta 1636), reused 2135 (delta 1065), pack-reused 0
Receiving objects: 100% (3506/3506), 1.80 MiB | 11.98 MiB/s, done.
Resolving deltas: 100% (1636/1636), done.  0% (0/1636)
[2021-08-30T16:19:29Z] Error: Error running git log 2.30.1..b8c35d44de987a9691890b3ddf3e2e7effb9bf20 --pretty=format:' * %h - %s - by %an' -- in prisma-engines:fatal: Invalid revision range 2.30.1..b8c35d44de987a9691890b3ddf3e2e7effb9bf20
[2021-08-30T16:19:29Z]     at runResult (/app/scripts/ci/publish.ts:116:11)
[2021-08-30T16:19:29Z]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-08-30T16:19:29Z] Lock removed after 191989ms
```

**Comment by dpetrick** [comment]
Note: Joel mentioned that he knows how to fix this.

**Comment by Jolg42** [comment]
In the error shown the tag `2.30.1` doesn't exist so this why it failed.

Though 2.30.1 shows as created here https://buildkite.com/prisma/release-prisma-typescript/builds/5282#3394f411-ab3a-4b51-960f-5f300bbf9640/237-3587

We might have deleted it manually since this run was a mistake, I'll say we close this issue and if it happens again I'm happy to look into it.

**Comment by janpio** [comment]
As far as I know this happens on all patch releases, as it is trying to create the tag on the main branch and not on the patch branch the release is happening from.

**Comment by Jolg42** [comment]
Had a look at 2.30.3 the error is different and should be what you are talking about

```
[2021-09-02T16:29:32Z] Error: Error running git log 2.31.0-dev.42..b8c35d44de987a9691890b3ddf3e2e7effb9bf20 --pretty=format:' * %h - %s - by %an' -- in prisma-engines:fatal: Invalid revision range 2.31.0-dev.42..b8c35d44de987a9691890b3ddf3e2e7effb9bf20
```
https://buildkite.com/prisma/release-prisma-typescript/builds/5323#ee79783f-62dd-49ee-928a-580e7f22a205/237-3396

From first look it could be that this doesn't do what it should do
https://github.com/prisma/prisma/blob/main/scripts/ci/publish.ts#L805-L809

**Comment by janpio** [comment]
I remember the "invalid revision range" was what we talked about and looked at before, and came to the conclusion it might be using the wrong branch.

Probably we need to look at all recent releases of patch versions to see if this is present in all of them.

**Comment by Jolg42** [comment]
Looks like it's only affecting patch releases when there is a patch branch like 2.30.x on engine side.

I'm thinking we could probably use this to get the previous tag
```
git tag --points-at sha
```

it returns a list like 
```
2.30.1-dev.1
2.30.2
2.31.0-dev.19
2.31.0-dev.20
2.31.0-dev.21
2.31.0-dev.22
2.31.0-dev.23
2.31.0-dev.24
2.31.0-integration-node-api-memleak-investigation.1
```

then we can extract `2.30.2` and use that. but I sense that we could have a few minors on the same commit in some cases so we would need to get the higher one.

**Comment by pantharshit00** [comment]
Would love to see this get fixed. Over at https://github.com/pantharshit00/prisma-rpi-builds, script fails sometime for patch releases as I can't checkout to that specific tag if tag doesn't exists.
