### ISSUE TITLE
Build error when deploying with AWS Amplify

### ISSUE THREAD

**Issue by erichen114** [prisma/prisma#9043]
### Bug description

Getting this error when trying to deploy with AWS Amplify. I have no errors when I try to deploy with Vercel. 

My only packages are NextJS, Prisma, and NextAuth. 
``` 
2021-08-30T21:43:19.225Z [ERROR]: Error: Command failed with exit code 1: node_modules/.bin/next build
                                  Failed to compile.
                                  ModuleNotFoundError: Module not found: Error: Can't resolve '_http_common' in '/codebuild/output/src843141263/src/postpanion2/node_modules/@prisma/client/runtime'
                                  > Build error occurred
                                  Error: > Build failed because of webpack errors
                                  at /codebuild/output/src843141263/src/postpanion2/node_modules/next/dist/build/index.js:390:19
                                  at async Span.traceAsyncFn (/codebuild/output/src843141263/src/postpanion2/node_modules/next/dist/telemetry/trace/trace.js:60:20)
                                  info  - Loaded env from /codebuild/output/src843141263/src/postpanion2/.env.local
                                  info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
                                  info  - Checking validity of types...
                                  ./pages/api/auth/[...nextauth].js
                                  32:1  Warning: Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export
                                  info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
                                  info  - Creating an optimized production build...
                                  at makeError (/root/.//node_modules/execa/lib/error.js:60:11)
                                  at handlePromise (/root/.//node_modules/execa/index.js:118:26)
                                  at processTicksAndRejections (internal/process/task_queues.js:97:5)
                                  at async Builder.build (/root/.//node_modules/@sls-next/lambda-at-edge/dist/build.js:348:13) {
                                  shortMessage: 'Command failed with exit code 1: node_modules/.bin/next build',
                                  command: 'node_modules/.bin/next build',
                                  escapedCommand: '"node_modules/.bin/next" build',
                                  exitCode: 1,
                                  signal: undefined,
                                  signalDescription: undefined,
                                  stdout: 'info  - Loaded env from /codebuild/output/src843141263/src/postpanion2/.env.local\n' +
                                  'info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5\n' +
                                  'info  - Checking validity of types...\n' +
                                  '\n' +
                                  './pages/api/auth/[...nextauth].js\n' +
                                  '32:1  Warning: Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export\n' +
                                  '\n' +
                                  'info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules\n' +
                                  'info  - Creating an optimized production build...',
                                  stderr: 'Failed to compile.\n' +
                                  '\n' +
                                  "ModuleNotFoundError: Module not found: Error: Can't resolve '_http_common' in '/codebuild/output/src843141263/src/postpanion2/node_modules/@prisma/client/runtime'\n" +
                                  '\n' +
                                  '\n' +
                                  '> Build error occurred\n' +
                                  'Error: > Build failed because of webpack errors\n' +
                                  '    at /codebuild/output/src843141263/src/postpanion2/node_modules/next/dist/build/index.js:390:19\n' +
                                  '    at async Span.traceAsyncFn (/codebuild/output/src843141263/src/postpanion2/node_modules/next/dist/telemetry/trace/trace.js:60:20)',
                                  failed: true,
                                  timedOut: false,
                                  isCanceled: false,
                                  killed: false
```

I re-deployed a new project with Prisma removed and it deployed fine. Not really sure what the fix is for here!

[log (1).txt](https://github.com/prisma/prisma/files/7086214/log.1.txt)

### Expected behavior

A clean deploy

### Prisma information

**Schema**

```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id            String    @id @default(cuid())
  name          String?
  image         String?
  email         String?   @unique
  emailVerified DateTime?
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  accounts      Account[]
  sessions      Session[]
}

model Account {
  id                 String    @id @default(cuid())
  userId             String
  providerType       String
  providerId         String
  providerAccountId  String
  refreshToken       String?
  accessToken        String?
  accessTokenExpires DateTime?
  createdAt          DateTime  @default(now())
  updatedAt          DateTime  @updatedAt
  user               User      @relation(fields: [userId], references: [id])

  @@unique([providerId, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  userId       String
  expires      DateTime
  sessionToken String   @unique
  accessToken  String   @unique
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
  user         User     @relation(fields: [userId], references: [id])
}

model VerificationRequest {
  id         String   @id @default(cuid())
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt

  @@unique([identifier, token])
}
```

**Schema is set up, but I do not have any code in my project that makes calls to my database**

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v14.17.0

### Prisma Version

```
prisma                : 2.30.2
@prisma/client        : 2.30.2
Current platform      : darwin
Query Engine (Binary) : query-engine b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine      : migration-engine-cli b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine  : introspection-core b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary         : prisma-fmt b8c35d44de987a9691890b3ddf3e2e7effb9bf20 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash  : b8c35d44de987a9691890b3ddf3e2e7effb9bf20
Studio                : 0.422.0
```

**Comment by pantharshit00** [comment]
Try explicitly marking `_http_common` as external which is built in node js module:

// next.config.js
```
module.exports = {
  webpack: (config, {isServer}) => {
    if (isServer) {
      // https://github.com/prisma/prisma/issues/6899
      config.externals.push('_http_common')
    }

    return config
  },
}
```

**Comment by erichen114** [comment]
> Try explicitly marking `_http_common` as external which is built in node js module:
> 
> // next.config.js
> 
> ```js
> module.exports = {
>   webpack: (config, {isServer}) => {
>     if (isServer) {
>       // https://github.com/prisma/prisma/issues/6899
>       config.externals.push('_http_common')
>     }
> 
>     return config
>   },
> }
> ```

**Comment by erichen114** [comment]
> > Try explicitly marking `_http_common` as external which is built in node js module:
> > // next.config.js
> > ```js
> > module.exports = {
> >   webpack: (config, {isServer}) => {
> >     if (isServer) {
> >       // https://github.com/prisma/prisma/issues/6899
> >       config.externals.push('_http_common')
> >     }
> > 
> >     return config
> >   },
> > }
> > ```

You are amazing, this did the trick! Thank you so much :D
