### ISSUE TITLE
Cannot upsert more than 2 records with connectOrCreate relations in an array of promises

### ISSUE THREAD

**Issue by dariusj18** [prisma/prisma#9050]
### Bug description

I get the error

```
PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: 
Invalid `prisma.property.upsert()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: ToSql(1), cause: Some(Error(Parser(InvalidLength { expected: Any([36, 32]), found: 0 }))) }) })
    at RequestHandler.request (C:\PROJECTFOLDER\node_modules\@prisma\client\runtime\index.js:36748:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0) {
  clientVersion: '2.29.1'
}
```

### How to reproduce

When I am trying to run multiple upserts (more than 2 and it dies with this error) Inside promises and waiting until all the promises resolve.

The error seems to indicate that it has to do with the UUIDs, but I can run the upserts one two of any of my records, however as soon as I add a third I get the error above.

### Expected behavior

Upserts run as normal

### Prisma information

Example that shows the error

https://github.com/dariusj18/prisma_playground/tree/9050

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: v14.16.0

### Prisma Version

```
2.29.1 - 2.30.2
```

**Comment by dariusj18** [comment]
This isn't the issue I thought it was.  It was because I **was** missing a Uuid
