### ISSUE TITLE
Argument `column` for `data.column` must not be null. Please use undefined instead.

### ISSUE THREAD

**Issue by meotimdihia** [prisma/prisma#9199]
### Bug description

I have got this error when upgraded to Prisma 3.0.2. 

Updating JSONB column with NULL value
```
[17:02:43] ERROR: Argument colored_genres for data.colored_genres must not be null. Please use undefined instead.
Argument recent_comics for data.recent_comics must not be null. Please use undefined instead.

    Error: Argument colored_genres for data.colored_genres must not be null. Please use undefined instead.
    Argument recent_comics for data.recent_comics must not be null. Please use undefined instead.

        at Document.validate (/node_modules/@prisma/client/runtime/index.js:35604:19)
        at PrismaClient._executeRequest (/node_modules/@prisma/client/runtime/index.js:37991:17)
        at next (/node_modules/@prisma/client/runtime/index.js:37936:23)
        at t.middleware (/.build/webpack:/prisma/prisma.ts:271:16)
        at next (/node_modules/@prisma/client/runtime/index.js:37930:20)
        at /.build/webpack:/prisma/prisma.ts:259:10
        at next (/node_modules/@prisma/client/runtime/index.js:37930:20)
        at /.build/webpack:/prisma/prisma.ts:205:24
        at next (/node_modules/@prisma/client/runtime/index.js:37930:20)
        at /.build/webpack:/prisma/prisma.ts:155:10
```

### How to reproduce

```
  colored_genres Json?
```

### Prisma information  

```
model user_info {
  colored_genres Json?
}
```

### Environment & setup

- OS: Ubuntu 12
- Database: PostgreSQL 13
- Node.js version: 14

### Prisma Version

```
3.0.2
```

**Comment by janpio** [comment]
What query are you executing to get this error message? Seems you just pasted the field definition in the "How to reproduce" block of the issue template.

**Comment by chemicalkosek** [comment]
I'm having the same thing after upgrading to Prisma 3.0.2.
I have also ran `prisma migrate` with no changes in order to cohere with Upgrade Path for referential actions.

datamodel in particualar:
```
model Room {
  id        String    @id @default(cuid()) @db.VarChar(30)
  name      String
  updatedAt DateTime  @updatedAt
  createdAt DateTime  @default(now())
  accountId String    @map("account") @db.VarChar(30)
  bgColor   Json?
  account   Account   @relation(fields: [accountId], references: [id])
  bookings  Booking[]

  @@index([accountId])
}
```
Mutation from Nexus:
```
    t.field('createRoom', {
      type: 'Room',
      args: {
        name: nonNull(stringArg()),
        accountId: nonNull(idArg()),
        bgColor: arg({type: "Json"}),
      },
      resolve: (_parent, args, ctx) => ctx.prisma.room.create({
        data: {
          ...args
        }
      })
    });
```

Error when bgColor is null (the same thing when creating or updating):
```
Invalid `prisma.room.create()` invocation: { data: { name: 'Test Room', accountId: 'ckm7v6zpi00130huil8hbwvlk', bgColor: null ~~~~ } } Argument bgColor for data.bgColor must not be null. Please use undefined instead.```

**Comment by janpio** [comment]
Thanks for the report. Can you isolate the Prisma Query that Nexus creates under the hood here @chemicalkosek? Logging and debugging might help: https://pris.ly/d/logging +  https://pris.ly/d/debugging

**Comment by chemicalkosek** [comment]
Do you mean this? Nothing else pops out with all logs enabled.

```
{"level":30,"time":1631647777486,"pid":1906567,"hostname":"maciek-G3-3779","reqId":"req-2","req":{"method":"POST","url":"/","hostname":"localhost:4444","remoteAddress":"127.0.0.1","remotePort":47308},"msg":"incoming request"}
prisma:info Starting a postgresql pool with 13 connections.
{"level":50,"time":1631647777583,"pid":1906567,"hostname":"maciek-G3-3779","reqId":"req-2","err":{"type":"GraphQLError","message":"\nInvalid `prisma.room.create()` invocation:\n\n{\n  data: {\n    name: 'Test Room',\n    accountId: 'ckm7v6zpi00130huil8hbwvlk',\n    bgColor: null\n             ~~~~\n  }\n}\n\nArgument bgColor for data.bgColor must not be null. Please use undefined instead.\n\n","stack":"Error: \nInvalid `prisma.room.create()` invocation:\n\n{\n  data: {\n    name: 'Test Room',\n    accountId: 'ckm7v6zpi00130huil8hbwvlk',\n    bgColor: null\n             ~~~~\n  }\n}\n\nArgument bgColor for data.bgColor must not be null. Please use undefined instead.\n\n\n    at Document.validate (/home/maciek/Dokumenty/websites/bookingapp/backend/node_modules/@prisma/client/runtime/index.js:35604:19)\n    at PrismaClient._executeRequest (/home/maciek/Dokumenty/websites/bookingapp/backend/node_modules/@prisma/client/runtime/index.js:37991:17)\n    at consumer (/home/maciek/Dokumenty/websites/bookingapp/backend/node_modules/@prisma/client/runtime/index.js:37936:23)\n    at /home/maciek/Dokumenty/websites/bookingapp/backend/node_modules/@prisma/client/runtime/index.js:37938:47\n    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)\n    at PrismaClient._request (/home/maciek/Dokumenty/websites/bookingapp/backend/node_modules/@prisma/client/runtime/index.js:37938:25)\n    at request (/home/maciek/Dokumenty/websites/bookingapp/backend/node_modules/@prisma/client/runtime/index.js:38041:77)\n    at _callback (/home/maciek/Dokumenty/websites/bookingapp/backend/node_modules/@prisma/client/runtime/index.js:38246:14)\n    at PrismaPromise.then (/home/maciek/Dokumenty/websites/bookingapp/backend/node_modules/@prisma/client/runtime/index.js:38253:23)","locations":[{"line":2,"column":3}],"path":["createRoom"]},"msg":"\nInvalid `prisma.room.create()` invocation:\n\n{\n  data: {\n    name: 'Test Room',\n    accountId: 'ckm7v6zpi00130huil8hbwvlk',\n    bgColor: null\n             ~~~~\n  }\n}\n\nArgument bgColor for data.bgColor must not be null. Please use undefined instead.\n\n"}
```

**Comment by janpio** [comment]
Yes, in the third line, this is hiding:


```
Invalid `prisma.room.create()` invocation:
{
  data: {
    name: 'Test Room',
    accountId: 'ckm7v6zpi00130huil8hbwvlk',
    bgColor: null
             ~~~~
  }
}

Argument bgColor for data.bgColor must not be null. Please use undefined instead
```

From your schema we know that `bgColor` is of type Json. That would match the headline `Changes to how you query Null values on JSON fields` from our recent release: https://github.com/prisma/prisma/releases/tag/3.0.1 Here is the documentation for that change: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-by-null-values

**Comment by chemicalkosek** [comment]
Hmm but I'm not doing any filtering by Json field. This is updating or creating.

**Comment by janpio** [comment]
That is a very good point. I will let someone else take over that hopefully knows more. (Sorry about the confusion)

**Comment by janpio** [comment]
Similar problem that was split into its own issue as it has all required information: https://github.com/prisma/prisma/issues/9264
