### ISSUE TITLE
PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18expected array type

### ISSUE THREAD

**Issue by avetavos** [prisma/prisma#9242]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.17.4           | 
| OS              | darwin             |
| Prisma Client   | 2.30.0             |
| Query Engine    | query-engine 60b19f4a1de4fe95741da371b4c44a92f4d1adcb|
| Database        | undefined|

## Logs
```
orthub-api/node_modules/.prisma/client  
  plusX Execution permissions of /Users/phongraphiruamtham/Documents/sporthub-api/node_modules/.prisma/client/query-engine-darwin are fine  
  plusX Execution permissions of /Users/phongraphiruamtham/Documents/sporthub-api/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '51682' ] }  
  prisma:engine stdout  Starting a postgresql pool with 17 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:51682  
  prisma:engine Search for Query Engine in /Users/phongraphiruamtham/Documents/sporthub-api/node_modules/.prisma/client  
  plusX Execution permissions of /Users/phongraphiruamtham/Documents/sporthub-api/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.30.0  
  prisma:engine Engine Version: query-engine 60b19f4a1de4fe95741da371b4c44a92f4d1adcb  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18
expected array type  +4s
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/phongraphiruamtham/Documents/sporthub-api/node_modules/@prisma/client/runtime/index.js:27696:24)
  prisma:engine       at Socket.emit (events.js:412:35)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1317:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
  prisma:engine {
  prisma:engine   error: Error: connect ECONNREFUSED 127.0.0.1:51682
  prisma:engine       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  prisma:engine     errno: -61,
  prisma:engine     code: 'ECONNREFUSED',
  prisma:engine     syscall: 'connect',
  prisma:engine     address: '127.0.0.1',
  prisma:engine     port: 51682
  prisma:engine   }
  prisma:engine }  
  prisma:engine { cwd: '/Users/phongraphiruamtham/Documents/sporthub-api/prisma' }  
  prisma:engine Search for Query Engine in /Users/phongraphiruamtham/Documents/sporthub-api/node_modules/.prisma/client  
  plusX Execution permissions of /Users/phongraphiruamtham/Documents/sporthub-api/node_modules/.prisma/client/query-engine-darwin are fine  +4s
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '51690' ] }  
  prisma:engine stdout  Starting a postgresql pool with 17 connections.  
  prisma:engine stdout  Started http server on http://127.0.0.1:51690  
  prisma:engine Search for Query Engine in /Users/phongraphiruamtham/Documents/sporthub-api/node_modules/.prisma/client  
  plusX Execution permissions of /Users/phongraphiruamtham/Documents/sporthub-api/node_modules/.prisma/client/query-engine-darwin are fine  
  prisma:engine Client Version: 2.30.0  
  prisma:engine Engine Version: query-engine 60b19f4a1de4fe95741da371b4c44a92f4d1adcb  
  prisma:engine Active provider: postgresql  
  prisma:engine stdout  PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18
expected array type  
  prisma:engine {
  prisma:engine   error: SocketError: other side closed
  prisma:engine       at Socket.onSocketEnd (/Users/phongraphiruamtham/Documents/sporthub-api/node_modules/@prisma/client/runtime/index.js:27696:24)
  prisma:engine       at Socket.emit (events.js:412:35)
  prisma:engine       at endReadableNT (internal/streams/readable.js:1317:12)
  prisma:engine       at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  prisma:engine     code: 'UND_ERR_SOCKET'
  prisma:engine   }
  prisma:engine }  
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
mutation {
  createOneActivity(data: {
    activityType: RUN
    period: 5
    timestamp: "X"
    distances: 5
    calories: 5
    steps: 5
    locations: ["X"]
    logs: ["X"]
    user: {
      connect: {
        id: "X"
      }
    }
  }) {
    id
    period
    timestamp
    distances
    calories
    steps
    activityType
    locations
    logs
    userId
    createdAt
    updatedAt
  }
}
```

**Comment by janpio** [comment]
Can you try upgrading to 3.x and see if the error persists? Thanks.
