### ISSUE TITLE
Validation error when inserting data of type `List<String | DateTime>` into field of type `List<String>`

### ISSUE THREAD

**Issue by zhyuhan** [prisma/prisma#9248]
### Bug description

I have a column of type `String[]`, and when I try to insert an array that contains a mix of regular strings and an ISO 8601 formatted datetime string, e.g. `["hello", "2021-09-14T00:00:00.000Z"]`, an error is thrown.

```
PS C:\Users\zhyuhan\Development\prisma-string-datetime> npx prisma db seed
Environment variables loaded from .env
Running seed command `ts-node prisma/seed.ts` ...
prisma:info Starting a postgresql pool with 13 connections.
prisma:query BEGIN
prisma:query SELECT "public"."Post"."id" FROM "public"."Post" WHERE "public"."Post"."id" = $1 OFFSET $2
prisma:query SELECT "public"."Post"."id" FROM "public"."Post" WHERE "public"."Post"."id" = $1
prisma:query SELECT "public"."Post"."id", "public"."Post"."words" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
prisma:query COMMIT
Successfully created post #1 with words hello
prisma:query BEGIN
prisma:query SELECT "public"."Post"."id" FROM "public"."Post" WHERE "public"."Post"."id" = $1 OFFSET $2
prisma:query SELECT "public"."Post"."id" FROM "public"."Post" WHERE "public"."Post"."id" = $1
prisma:query SELECT "public"."Post"."id", "public"."Post"."words" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
prisma:query COMMIT
Successfully created post #2 with words 2021-09-14T00:00:00.000Z
prisma:query BEGIN
prisma:query SELECT "public"."Post"."id" FROM "public"."Post" WHERE "public"."Post"."id" = $1 OFFSET $2
prisma:query SELECT "public"."Post"."id" FROM "public"."Post" WHERE "public"."Post"."id" = $1
prisma:query SELECT "public"."Post"."id", "public"."Post"."words" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
prisma:query COMMIT
Successfully created post #3 with words 2021-09-14T00:00:00.000Z,2021-09-20T12:00:00.000Z

An error occured while running the seed command:
PrismaClientValidationError: 
Invalid `prisma.post.upsert()` invocation:

{
  where: {
    id: 4
  },
  update: {},
  create: {
    id: 4,
    words: [
      'hello',
      '2021-09-14T00:00:00.000Z'
    ]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  }
}

Argument words: Got invalid value 
[
  'hello',
  '2021-09-14T00:00:00.000Z'
]
on prisma.upsertOnePost. Provided List<String | DateTime>, expected PostCreatewordsInput or String:
type PostCreatewordsInput {
  set: List<String>
}
type PostCreatewordsInput {
  set: List<String>
}


    at Document.validate (C:\Users\zhyuhan\Development\prisma-string-datetime\node_modules\@prisma\client\runtime\index.js:35604:19)
    at PrismaClient._executeRequest (C:\Users\zhyuhan\Development\prisma-string-datetime\node_modules\@prisma\client\runtime\index.js:37991:17)
    at consumer (C:\Users\zhyuhan\Development\prisma-string-datetime\node_modules\@prisma\client\runtime\index.js:37936:23)
    at C:\Users\zhyuhan\Development\prisma-string-datetime\node_modules\@prisma\client\runtime\index.js:37938:47
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at PrismaClient._request (C:\Users\zhyuhan\Development\prisma-string-datetime\node_modules\@prisma\client\runtime\index.js:37938:25)
    at request (C:\Users\zhyuhan\Development\prisma-string-datetime\node_modules\@prisma\client\runtime\index.js:38041:77)
    at _callback (C:\Users\zhyuhan\Development\prisma-string-datetime\node_modules\@prisma\client\runtime\index.js:38246:14)
    at PrismaPromise.then (C:\Users\zhyuhan\Development\prisma-string-datetime\node_modules\@prisma\client\runtime\index.js:38253:23) {
  clientVersion: '3.0.2'
}
```

It works fine if the array is purely regular strings like `["hello", "world"]`, or purely datetime strings like `["2021-09-14T00:00:00.000Z", "2021-09-20T12:00:00.000Z"]`.

I found the part of the source code where the typechecking is done

https://github.com/prisma/prisma/blob/13d92ca5f9f823deb392d8a8d4d7496df558513a/packages/client/src/runtime/query.ts#L1343-L1349

and it seems to lack the case for `expectedType === "List<String>" && (graphQLType === "List<String | DateTime>" || graphQLType === "List<DateTime| String>")`, which is present for `UUID` strings.

https://github.com/prisma/prisma/blob/13d92ca5f9f823deb392d8a8d4d7496df558513a/packages/client/src/runtime/query.ts#L1370-L1374

I am not sure if this is the intended behavior or if this is a bug.

### How to reproduce

Please see the [reproduction repository](https://github.com/zhyuhan/prisma-string-datetime).

### Expected behavior

The row should be created with no errors, since the datetime string is still a `String`.

### Prisma information

The schema:
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id    Int      @id
  words String[]
}
```

Query that caused the error:
```js
prisma.post.upsert({
  where: {
    id: 4,
  },
  update: {},
  create: {
    id: 4,
    words: ["hello", "2021-09-14T00:00:00.000Z"],
  },
});
```

### Environment & setup

- OS: Windows
- Database: PostgreSQL
- Node.js version: `v16.8.0`

### Prisma Version

```
prisma                  : 3.0.2
@prisma/client          : 3.0.2
Current platform        : windows
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\query_engine-windows.dll.node)
Migration Engine        : migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\migration-engine-windows.exe)
Introspection Engine    : introspection-core 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\introspection-engine-windows.exe)
Format Binary           : prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules\@prisma\engines\prisma-fmt-windows.exe)
Default Engines Hash    : 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio                  : 0.423.0
```

**Comment by pantharshit00** [comment]
Thanks for the very detailed explanation and reproduction. I can confirm this bug.
