### ISSUE TITLE
Relations count with `_count` and `groupBy()` doesnt work like intented

### ISSUE THREAD

**Issue by Melonendk** [prisma/prisma#9289]
## Using
- NODE: v14.17.5
- NPM: v7.19.1
- Database: PostgreSQL v13
- OS Dev: Windows 10 latest
- OS TestServer: 512 MB RAM | 1 vCPU  x  1 - digital Ocean
- Prisma:
```
prisma			: 3.0.2
@prisma/client		: 3.0.2
Current platform 	: debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/libquery_engine-debian-openss1-1.1.x.so.node)
Migration Engine 	: migration-engine-cli 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine 	: introspection-core 2452cC6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary		: prisma-fmt 2452cc6313d52b8b9a96999ac0e974d0aedf88db (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash 	: 2452cc6313d52b8b9a96999ac0e974d0aedf88db
Studio			: 0.423.0
```

## Schema
```prisma
model Order {
  id                    String      @id
  firstname             String
  lineItems             LineItem[]
  vendors               Vendor[]
  subTotal              Float
  total                 Float
  totalShipping         Float
  totalRefunded         Float
  totalRefundedShipping Float
  recievedAt            DateTime
}

model LineItem {
  id            String    @id
  order         Order     @relation(fields: [orderId], references: [id])
  orderId       String
  title         String
  variantTitle  String
  productId     String
  quantity      Int
  originalTotal Float
  discountTotal Float
  recievedAt    DateTime
  vendor        Vendor    @relation(fields: [vendorId], references: [id])
  vendorId      String
  productType   String
  refunded      Boolean   @default(false)
}

model Vendor {
  id              String    @id @default(cuid())
  name            String    @unique
  lineItems       LineItem[]
  orders          Order[]
}
```

## The Problem

So im trying to do couple of things but they relate to the same category as i have followed the information on the [docs here
](https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing) and it works like intented on my dev machine.
But as soon as i update upon rebuild my server and generate prisma etc, i get that its not possible even tho i just seen it possible with no error which weirds me out.

### Issue 1 - PrismaClientValidationError: Argument by: Provided value 
I think i know what it is but i dont understand why it doesnt take productType into the aggegation but it allows it on dev weird enugh
But my simple goal is to get a type list out like so.
[
```yaml
{
  [
    { productType: 'T-Shirt', _count: { productType: 56 } },
    { productType: 'Hoodie', _count: { productType: 33 } },
    { productType: 'Crewneck', _count: { productType: 18 } },
    etc....
  ]
}
```
But i end up with the error even tho my code is fine (check that longer down)

### Issue 2 PrismaClientValidationError:
Another issue is simply cant count a many relation even tho i can on my own machine.
I have also tried doing it with include instead of select which gave same problem
And the thing is it should simple return `{ _count: { orders: number } }` but it does give the error istead

### Issue 1
```cmd
PrismaClientValidationError: Argument by: Provided value 
[
  'productType'
]
of type List<String> on prisma.groupByLineItem is not a List<enumTypes>.
→ Possible values: LineItemScalarFieldEnum.id, LineItemScalarFieldEnum.orderId, LineItemScalarFieldEnum.title, LineItemScalarFieldEnum.variantTitle, LineItemScalarFieldEnum.productId, LineItemScalarFieldEnum.quantity, LineItemScalarFieldEnum.originalTotal, LineItemScalarFieldEnum.discountTotal, LineItemScalarFieldEnum.recievedAt, LineItemScalarFieldEnum.vendorId
Unknown arg `productType` in orderBy._count.productType for type LineItemCountOrderByAggregateInput. Did you mean `productId`?
Unknown field `productType` for select statement on model LineItemGroupByOutputType. Did you mean `productId`?
Unknown field `productType` for select statement on model LineItemCountAggregateOutputType. Did you mean `productId`?
    at Document.validate (/workspace/node_modules/@prisma/client/runtime/index.js:35604:19)
    at PrismaClient._executeRequest (/workspace/node_modules/@prisma/client/runtime/index.js:37991:17)
    at consumer (/workspace/node_modules/@prisma/client/runtime/index.js:37936:23)
    at /workspace/node_modules/@prisma/client/runtime/index.js:37938:47
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at PrismaClient._request (/workspace/node_modules/@prisma/client/runtime/index.js:37938:25)
    at request (/workspace/node_modules/@prisma/client/runtime/index.js:38041:77)
    at _callback (/workspace/node_modules/@prisma/client/runtime/index.js:38246:14)
    at PrismaPromise.catch (/workspace/node_modules/@prisma/client/runtime/index.js:38257:14)
    at DashboardApi (/workspace/.next/server/pages/api/app/dashboard.js:129:11) {
  clientVersion: '3.0.2'
}
```

### Issue 2
```cmd
PrismaClientValidationError: 
Unknown field `orders` for select statement on model VendorCountOutputType.
   at Document.validate (/workspace/node_modules/@prisma/client/runtime/index.js:35604:19)
   at PrismaClient._executeRequest (/workspace/node_modules/@prisma/client/runtime/index.js:37991:17)
   at consumer (/workspace/node_modules/@prisma/client/runtime/index.js:37936:23)
   at /workspace/node_modules/@prisma/client/runtime/index.js:37938:47
   at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
   at PrismaClient._request (/workspace/node_modules/@prisma/client/runtime/index.js:37938:25)
   at request (/workspace/node_modules/@prisma/client/runtime/index.js:38041:77)
   at _callback (/workspace/node_modules/@prisma/client/runtime/index.js:38246:14)
   at PrismaPromise.catch (/workspace/node_modules/@prisma/client/runtime/index.js:38257:14)
   at DashboardApi (/workspace/.next/server/pages/api/app/dashboard.js:146:11) { 
 clientVersion: '3.0.2'
}
```

### Issue 1 Code
```js
await prisma.lineItem.groupBy({
  by: ['productType'],
  _count: {
    productType: true,
  },
  where: {
    vendor: {
      name: {
        contains: 'uniquevendorname',
      },
    },
  },
  orderBy: {
    _count: {
      productType: 'desc',
    },
  },
})
```

### Issue 2 Code
```js
// Only need the count
await prisma.vendor.findUnique({
  where: {
    name: 'Jaxstyle',
  },
  select: {
    _count: {
      select: { orders: true },
    },
  },
})
```

**Comment by jkomyno** [comment]
I understand this is an old issue, but I wasn't able to reproduce it with neither `prisma@3.0.2` nor the most recent `prisma@5.10.2`. There is likely some missing information. Perhaps no `prisma generate` was run after modifying the original `schema.prisma`, resulting in the validation errors above?

**Comment by FGoessler** [comment]
Hi 👋 

We are closing this issue as we haven't received enough information to reproduce this issue. Should you be able to provide more information for this please feel free to reopen this issue or create a new one.
