### ISSUE TITLE
Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 107, kind: NotConnected, message: "Socket not connected" }) }

### ISSUE THREAD

**Issue by kanso-git** [prisma/prisma#9292]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.16.0           | 
| OS              | linux-musl         |
| Prisma Client   | 2.23.0             |
| Query Engine    | query-engine adf5e8cba3daf12d456d911d72b6e9418681b28b|
| Database        | undefined|

## Query
```
query {
  findUniquePost(where: {
    id: "X"
  }) {
    room {
      id
      name
      adminKey
      num
      isTemporary
      isNicknames
      isModerated
      isPollOnly
      reCaptchaToken
      isCommentsAllowed
      isAutomaticFlow
      userId
      createdAt
      updatedAt
    }
  }
}
```

## Logs
```
ge: "Socket not connected" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 107, kind: NotConnected, message: "Socket not connected" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 107, kind: NotConnected, message: "Socket not connected" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 107, kind: NotConnected, message: "Socket not connected" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 107, kind: NotConnected, message: "Socket not connected" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 107, kind: NotConnected, message: "Socket not connected" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 107, kind: NotConnected, message: "Socket not connected" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 107, kind: NotConnected, message: "Socket not connected" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 107, kind: NotConnected, message: "Socket not connected" }) }
prisma:engine stdout  Error in PostgreSQL connection: Error { kind: Io, cause: Some(Os { code: 107, kind: NotConnected, message: "Socket not connected" }) }
prisma:client Error: Unique constraint failed on the fields: (`userId`,`pollOptionId`)
    at NodeEngine.graphQLToJSError (/app/api/node_modules/@prisma/client/runtime/index.js:27808:16)
    at NodeEngine.request (/app/api/node_modules/@prisma/client/runtime/index.js:27706:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async cb (/app/api/node_modules/@prisma/client/runtime/index.js:35071:26)
prisma:client Error: Unique constraint failed on the fields: (`userId`,`pollOptionId`)
    at NodeEngine.graphQLToJSError (/app/api/node_modules/@prisma/client/runtime/index.js:27808:16)
    at NodeEngine.request (/app/api/node_modules/@prisma/client/runtime/index.js:27706:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async cb (/app/api/node_modules/@prisma/client/runtime/index.js:35071:26)
prisma:client Error: An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
    at NodeEngine.graphQLToJSError (/app/api/node_modules/@prisma/client/runtime/index.js:27808:16)
    at NodeEngine.request (/app/api/node_modules/@prisma/client/runtime/index.js:27706:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async cb (/app/api/node_modules/@prisma/client/runtime/index.js:35071:26)
prisma:engine {
  error: Error: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: Some(KnownError { message: "Foreign key constraint failed on the field: `PostReaction_postId_fkey (index)`", meta: Object({"field_name": String("PostReaction_postId_fkey (index)")}), error_code: "P2003" }), kind: ForeignKeyConstraintViolation { constraint: Index("PostReaction_postId_fkey") } })
      at /app/api/node_modules/@prisma/client/runtime/index.js:27757:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
prisma:engine {
  error: Error: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: Some(KnownError { message: "Foreign key constraint failed on the field: `PostReaction_postId_fkey (index)`", meta: Object({"field_name": String("PostReaction_postId_fkey (index)")}), error_code: "P2003" }), kind: ForeignKeyConstraintViolation { constraint: Index("PostReaction_postId_fkey") } })
      at /app/api/node_modules/@prisma/client/runtime/index.js:27757:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
prisma:engine {
  error: Error: Error occurred during query execution:
  ConnectorError(ConnectorError { user_facing_error: Some(KnownError { message: "Foreign key constraint failed on the field: `PostReaction_postId_fkey (index)`", meta: Object({"field_name": String("PostReaction_postId_fkey (index)")}), error_code: "P2003" }), kind: ForeignKeyConstraintViolation { constraint: Index("PostReaction_postId_fkey") } })
      at /app/api/node_modules/@prisma/client/runtime/index.js:27757:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
```

```

## Schema
```prisma
model Room {
  id       String  @id @default(uuid())
  name     String
  adminKey String? @unique
  num      String? @unique

  // readonly fields
  isTemporary    Boolean @default(true)
  isNicknames    Boolean @default(false)
  isModerated    Boolean @default(false)
  isPollOnly     Boolean @default(false)
  reCaptchaToken String?

  // editable fields
  isCommentsAllowed Boolean @default(false)
  isAutomaticFlow   Boolean @default(false)

  // relation fields
  users     RoomAttendee[]
  posts     Post[]
  polls     Poll[]
  userId    String
  createdBy User           @relation(fields: [userId], references: [id])

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
.
.
.
model Post {
  id          String  @id @default(uuid())
  content     String
  isPublished Boolean @default(true)

  isFavorite Boolean @default(false)
  roomId     String
  room       Room    @relation(fields: [roomId], references: [id])

  reactions PostReaction[]
  comments  Comment[]

  nickName String?
  userId    String
  createdBy User   @relation(fields: [userId], references: [id])

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

**Comment by janpio** [comment]
This is most probably solved in a newer version of Prisma, especially 3.x. Can you try upgrading and see if you still get the same error?

**Comment by janpio** [comment]
Ping @kanso-git
