### ISSUE TITLE
Allow to change engine directory

### ISSUE THREAD

**Issue by xnerhu** [prisma/prisma#9337]
## Problem

I'm trying to integrate prisma with Bazel, but the main problem is that prisma downloads engine to `/home/xnerhu/.cache/prisma/master/2452cc6313d52b8b9a96999ac0e974d0aedf88db/debian-openssl-1.1.x/libquery-engine` directory. Bazel is a sandboxed environment and it throws `Error: EROFS: read-only file system`, which is expected. 
## Suggested solution

I'm asking to add an option to `prisma generate` CLI and the others to change path to engine directory.

## Additional context

`prisma generate --schema ./schema --engine ./engine`

**Comment by janpio** [comment]
Hmm, the `.cache` directory is a temporary location the engines are downloaded to, then extracted to before they are moved to their intended location. This uses https://www.npmjs.com/package/find-cache-dir which unfortunately does not seem to be able to handle your environment. (https://github.com/prisma/engines-wrapper/blob/7195c6e751d3661cfc5df1e1126789b88c291494/packages/fetch-engine/src/util.ts#L12-L32)

Would your system be able to manually create `/tmp/prisma-download` and use it to store data?

If we decide to implement a workaround here, I think an environment variable might be the better tool here than a parameter on the CLI level.

Can you share the full error message you are getting btw? Might be helpful for us to put some special error handling in the correct place as well.

**Comment by xnerhu** [comment]
Bazel uses sandbox, so everything outside of it will throw exceptions. The only solution in this case is to download engine directly to the sandbox.

Environment variable would be great.

```bash
Starting local Bazel server and connecting to it...
INFO: Invocation ID: be38dd14-90b5-4d26-871f-f6aceaa3a8ef
INFO: Analyzed target //common/updates-prisma:updates-prisma (34 packages loaded, 308 targets configured).
INFO: Found 1 target...
ERROR: /mnt/c/Users/xnerhu/Projects/cloud/common/updates-prisma/BUILD.bazel:29:7: Action common/updates-prisma/gen/index.d.ts failed: (Exit 1): prisma.sh failed: error executing command 
  (cd /home/xnerhu/.cache/bazel/_bazel_xnerhu/f3ad32c88ec8e5f85e621758bdc96e97/sandbox/linux-sandbox/2/execroot/init && \
  exec env - \
    BAZEL_NODE_MODULES_ROOTS='' \
    COMPILATION_MODE=fastbuild \
  bazel-out/host/bin/external/npm/prisma/bin/prisma.sh --nobazel_patch_module_resolver generate --schema bazel-out/k8-fastbuild/bin/common/updates-prisma/schema.prisma '--bazel_node_modules_manifest=bazel-out/k8-fastbuild/bin/common/updates-prisma/_prisma_build.module_mappings.json')
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
Error: EROFS: read-only file system, utime '/home/xnerhu/.cache/prisma/master/2452cc6313d52b8b9a9699
9ac0e974d0aedf88db/debian-openssl-1.1.x/libquery-engine'
Environment variables loaded from bazel-out/k8-fastbuild/bin/common/updates-prisma/.env
Prisma schema loaded from bazel-out/k8-fastbuild/bin/common/updates-prisma/schema.prisma
Target //common/updates-prisma:updates-prisma failed to build
INFO: Elapsed time: 252.426s, Critical Path: 1.13s
INFO: 3 processes: 2 internal, 1 linux-sandbox.                                    
FAILED: Build did NOT complete successfully
```

**Comment by CooperBills** [comment]
I'm also running into this issue integrating this into our toolchain (Bazel as well). Prisma's premise of generating the client from the schema would work well in build workflows, however hermetic builds require not reaching into and modifying parts of the filesystem.

```
2022-03-24T05:37:02.005Z prisma:download file /private/var/tmp/_bazel_cbills/3124d31a76ee2b6c7f4305be5f363e2f/execroot/project_name/bazel-out/darwin_arm64-fastbuild/bin/external/npm/node_modules/prisma/libquery_engine-darwin-arm64.dylib.node does not exist and must be downloaded
Error: Error: Can't write to /private/var/tmp/_bazel_cbills/3124d31a76ee2b6c7f4305be5f363e2f/execroot/project_name/bazel-out/darwin_arm64-fastbuild/bin/external/npm/node_modules/prisma please make sure you install "prisma" with the right permissions.
    at downloadBinary (/private/var/tmp/_bazel_cbills/3124d31a76ee2b6c7f4305be5f363e2f/execroot/project_name/bazel-out/darwin_arm64-fastbuild/bin/external/npm/node_modules/prisma/build/index.js:30366:17)
    at /private/var/tmp/_bazel_cbills/3124d31a76ee2b6c7f4305be5f363e2f/execroot/project_name/bazel-out/darwin_arm64-fastbuild/bin/external/npm/node_modules/prisma/build/index.js:30180:59
    at Array.map (<anonymous>)
    at download (/private/var/tmp/_bazel_cbills/3124d31a76ee2b6c7f4305be5f363e2f/execroot/project_name/bazel-out/darwin_arm64-fastbuild/bin/external/npm/node_modules/prisma/build/index.js:30180:46)
    at async getGenerators (/private/var/tmp/_bazel_cbills/3124d31a76ee2b6c7f4305be5f363e2f/execroot/project_name/bazel-out/darwin_arm64-fastbuild/bin/external/npm/node_modules/prisma/build/index.js:39782:45)
    at async Object.parse (/private/var/tmp/_bazel_cbills/3124d31a76ee2b6c7f4305be5f363e2f/execroot/project_name/bazel-out/darwin_arm64-fastbuild/bin/external/npm/node_modules/prisma/build/index.js:107257:20)
    at async main (/private/var/tmp/_bazel_cbills/3124d31a76ee2b6c7f4305be5f363e2f/execroot/project_name/bazel-out/darwin_arm64-fastbuild/bin/external/npm/node_modules/prisma/build/index.js:108785:18)
```

I see three solutions to this problem:
1. Allow specifying the engine directory (via cli or env), so it can be pointed to a tmp dir (as suggested on this ticket).
2. Allow specifying the engine itself, so it's toolchain can be managed by the build system.
3. Install the engine as part of the install script, rather than downloading it on the fly at runtime - this way it'll already be there.

...Digging through the code it looks like `#2` already exists through env. Hmmm... Hold my 🍺  - I'm going to see if I can get my pirsma bazel rule working.

**Comment by CooperBills** [comment]
Done! I managed to get Prisma working with Bazel, and open sourced the rule here: https://github.com/CooperBills/rules_prisma - It's currently pretty limited (it's only a single `prisma_js_library` rule that generates the typescript/javascript client in a bazel-compatible way, but should work as a good starting point if more functionality is needed).

As for how it works, it turns out `#3` from my comment above is also already happening, but in the `@prisma/engines` package (perhaps the prisma cli should check in `@prisma/engines` before trying to pull from the internet?). So my bazel rule references the engines from `@prisma/engines` and points the cli to them via environment variables.

**Comment by janpio** [comment]
(The engine download logic is a bit of a mess - as you might have noticed - and we are working on cleaning that up. Hopefully afterwards this will make a lot more sense and then also be able to be controlled more directly and cleanly.) Thanks for posting the workaround!
