### ISSUE TITLE
Unable to get the total count of records using prisma.model.count()

### ISSUE THREAD

**Issue by ibadeeCodes** [prisma/prisma#9340]
### Bug description

Hi,
I just want to get the total number of posts in my post table.
I tried :
`prisma.post.count()`
But it says:
Invalid prisma.post.aggregate() invocation:\n\n\n  Failed to validate the query: Field does not exist on enclosing type. at `Query.aggregatepost.AggregatePost._count

Any solution for it?

### How to reproduce

1. I want to know the total number of records in my post table.
2. In my controller I wrote prisma.post.count() to get the total count of records.
3. Ran my controller
4. See error : 
        PrismaClientKnownRequestError3 [PrismaClientKnownRequestError]:
Invalid `prisma.post.aggregate()` invocation:
  Failed to validate the query: `Field does not exist on enclosing type.` at `Query.aggregatepost.AggregatePost._count`
    at cb (F:\All Works\backend\node_modules\@prisma\client\runtime\index.js:36494:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (file:///F:/All%20Work/backend/prisma/seed.js:21:3) {
  code: 'P2009',
  clientVersion: '2.30.3',
  meta: {
    query_validation_error: 'Field does not exist on enclosing type.',
    query_position: 'Query.aggregatepost.AggregatePost._count'
  }
}

### Expected behavior

`prisma.post.count()` should provide me the total number of posts in the post table.

### Prisma information

**Post Model :**

model post {
  id           Int            @id @default(autoincrement())
  caption      String?
  img_url      String?
  link         String?
  created_at   DateTime?      @default(now())
  is_active    Boolean?
  gender       String?
  clicks       Int?
  impressions  Int?
  category_id  Int?
  user_id      Int?
  age          String?
  country      String?
  is_featured  Boolean?
  modified_at  DateTime?
  expires_at   DateTime?
  is_expired   Boolean        @default(true)
  ratio        String?
  coins        Int?
  category     category?      @relation(fields: [category_id], references: [id])
  user         user?          @relation(fields: [user_id], references: [id])
  bot_comments bot_comments[]
  bot_ratings  bot_ratings[]
  comment      comment[]
  favorite     favorite[]
  notification notification[]
  rating       rating[]
  report       report[]
  advise       advise[]
  voucher      voucher?
  @@index([category_id], name: "IDX_5A8A6C8D12469DE2")
  @@index([user_id], name: "IDX_5A8A6C8DA76ED395")
}

**Query:**
prisma.post.count()

### Environment & setup

- OS: Windows
- Database: MySQL
- Node.js Version: v14.16.1

### Prisma Version

```
prisma : 3.0.2
@prisma/client : 2.30.3
Current platform : windows
```

**Comment by janpio** [comment]
That is great. Closing this issue then.
