### ISSUE TITLE
PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18expected array type

### ISSUE THREAD

**Issue by bamada** [prisma/prisma#9392]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v16.8.0            | 
| OS              | linux-musl         |
| Prisma Client   | 2.25.0             |
| Query Engine    | query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922|
| Database        | undefined|

## Query
```
mutation {
  queryRaw(
    query: "X"
    parameters: "X"
  )
}
```

## Logs
```
v Environment variables loaded from /app/.env
prisma:client clientVersion: 2.25.0
prisma:tryLoadEnv Environment variables loaded from /app/.env
prisma:client clientVersion: 2.25.0
prisma:engine { cwd: '/app/prisma' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '36395' ] }
prisma:engine stdout  Starting a postgresql pool with 9 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:36395
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
prisma:engine { cwd: '/app/prisma' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '39209' ] }
prisma:engine Client Version: 2.25.0
prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922
prisma:engine Active provider: postgresql
prisma:engine stdout  Starting a postgresql pool with 9 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:39209
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
prisma:engine Client Version: 2.25.0
prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922
prisma:engine Active provider: postgresql
prisma:client prisma.queryRaw(SELECT * FROM mercure_configs mc 
        WHERE employee_id IN ($1) AND DATE_PART('year', mc.start_date) = CAST ($2 AS INTEGER) 
        AND CAST ($3 AS INTEGER) >= DATE_PART('month', mc.start_date)
        AND CAST($3 AS INTEGER) <= DATE_PART('month', COALESCE(end_date,'2020-12-01')), [["10004433","10004430"],2021,5])
prisma:client Prisma Client call:
prisma:engine stdout  PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18
expected array type
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:25736:24)
      at Socket.emit (node:events:406:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    code: 'UND_ERR_SOCKET'
  }
}
prisma:engine {
  error: Error: connect ECONNREFUSED 127.0.0.1:36395
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 36395
  }
}
prisma:engine { cwd: '/app/prisma' }
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
prisma:engine { flags: [ '--enable-raw-queries', '--port', '33047' ] }
prisma:engine stdout  Starting a postgresql pool with 9 connections.
prisma:engine stdout  Started http server on http://127.0.0.1:33047
prisma:engine Search for Query Engine in /app/node_modules/.prisma/client
plusX Execution permissions of /app/node_modules/.prisma/client/query-engine-linux-musl are fine
prisma:engine Client Version: 2.25.0
prisma:engine Engine Version: query-engine c838e79f39885bc8e1611849b1eb28b5bb5bc922
prisma:engine Active provider: postgresql
prisma:engine stdout  PANIC in /root/.cargo/git/checkouts/rust-postgres-dc0fca9be721a90f/8a61d46/postgres-types/src/lib.rs:762:18
expected array type
prisma:engine {
  error: SocketError: other side closed
      at Socket.onSocketEnd (/app/node_modules/@prisma/client/runtime/index.js:25736:24)
      at Socket.emit (node:events:406:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    code: 'UND_ERR_SOCKET'
  }
}
```

## Client Snippet
```ts
  async fetchConfig(
    employeeId: string,
    year: number,
    month: number,
  ): Promise<Config[]> {
    const emp = ['10004433', '10004430'];
    const config = await this.prismaService
      .$queryRaw<Config[]>(
        `SELECT * FROM configs mc 
        WHERE employee_id IN ($1) AND DATE_PART('year', mc.start_date) = CAST ($2 AS INTEGER) 
        AND CAST ($3 AS INTEGER) >= DATE_PART('month', mc.start_date)
        AND CAST($3 AS INTEGER) <= DATE_PART('month', COALESCE(end_date,'2020-12-01'))`,
        emp,
        year,
        month,
      )
      .then((v) => v);
    return config;
  }
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

**Comment by bamada** [comment]
I find my mistake. I use  this `(${Prisma.join(
          employeeIds,
        )})` instead of the string tableau inside the raw query.
