### ISSUE TITLE
Constraint identifiers created by `prisma migrate dev` exceeding 63 characters causing errors due to truncating

### ISSUE THREAD

**Issue by henry-young** [prisma/prisma#9415]
### Bug description

Postgres automatically truncates index identifiers to 63 bytes (default). 
https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes

If you have multiple indexes in a model, and the table name is sufficiently long, the indexes themselves will be truncated and will throw a unique constraint error.

```
Migration name: 20210924003818_init

Database error code: 42P07

Database error:
ERROR: relation "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongB" already exists
```

### How to reproduce

1. Clone the starter project
2. Use the schema provided
3. Run 'prisma migrate dev'

### Expected behavior

I would expect the `prisma migrate dev` command to show a warning if a constraint names exceeds the max length.

### Prisma information

```
// schema.prisma
datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model Post {
  id        Int     @id @default(autoincrement())
  link LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER?
}

model User {
  id    Int     @id @default(autoincrement())
  link LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER?
}


model LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER {
  id Int     @id @default(autoincrement())

  post   Post @relation(fields: [postId], references: [id])
  postId Int          @map("post_id")

  user   User @relation(fields: [userId], references: [id])
  userId Int       @map("user_id")
}
```

### Environment & setup

- OS: Mac OS
- Database: PostgreSQL
- Node.js version: v14.17.3

### Prisma Version

```
3.1.1
```

**Comment by janpio** [comment]
I can confirm the problem, and for `db push` as well:

```
λ npx prisma db push
  prisma:loadEnv project root found at C:\Users\Jan\Documents\throwaway\9417\package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from C:\Users\Jan\Documents\throwaway\9417\.env +0ms
Environment variables loaded from .env
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\Documents\throwaway\9417\node_modules\@prisma\engines\query_engine-windows.dll.node +0ms
Datasource "db": PostgreSQL database "harlequin_sailfish", schema "public" at "pg-db-provision.cm0mkpwj8arx.eu-central-1.rds.amazonaws.com:5432"
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\Documents\throwaway\9417\node_modules\@prisma\engines\query_engine-windows.dll.node +9ms
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\Documents\throwaway\9417\node_modules\@prisma\engines\query_engine-windows.dll.node +5ms
  prisma:migrateEngine:rpc starting migration engine with binary: C:\Users\Jan\Documents\throwaway\9417\node_modules\@prisma\engines\migration-engine-windows.exe +0ms
  prisma:migrateEngine:rpc SENDING RPC CALL {"id":1,"jsonrpc":"2.0","method":"schemaPush","params":{"force":false,"schema":"generator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n\nmodel mytable {\n  field1 String @db.VarChar(36)\n  field2 String @db.VarChar(36)\n  field3 String @db.VarChar(36)\n\n  @@id([field1, field2, field3])\n}\n\nmodel Post {\n  id   Int
                                                                @id @default(autoincrement())\n  link LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER?\n}\n\nmodel User {\n  id   Int
                                              @id @default(autoincrement())\n  link LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER?\n}\n\nmodel LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER {\n  id Int @id @default(autoincrement())\n\n  post   Post @relation(fields: [postId], references: [id])\n  postId Int  @map(\"post_id\")\n\n  user   User @relation(fields: [userId], references: [id])\n  userId Int  @map(\"user_id\")\n}\n"}} +8ms
  prisma:migrateEngine:stderr {"timestamp":"2021-09-24T15:29:38.788081100+00:00","level":"INFO","fields":{"message":"Starting migration engine RPC server","git_hash":"c22652b7e418506fab23052d569b85d3aec4883f"},"target":"migration_engine"} +0ms
  prisma:migrateEngine:rpc {
  prisma:migrateEngine:rpc   jsonrpc: '2.0',
  prisma:migrateEngine:rpc   error: {
  prisma:migrateEngine:rpc     code: 4466,
  prisma:migrateEngine:rpc     message: 'An error happened. Check the data field for details.',
  prisma:migrateEngine:rpc     data: {
  prisma:migrateEngine:rpc       is_panic: false,
  prisma:migrateEngine:rpc       message: 'db error: ERROR: relation "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongB" already exists\n' +
  prisma:migrateEngine:rpc         '   0: sql_migration_connector::sql_database_step_applier::apply_migration\n' +
  prisma:migrateEngine:rpc         '             at migration-engine\\connectors\\sql-migration-connector\\src\\sql_database_step_applier.rs:11\n' +
  prisma:migrateEngine:rpc         '   1: migration_core::api::SchemaPush\n' +
  prisma:migrateEngine:rpc         '             at migration-engine\\core\\src\\api.rs:161',
  prisma:migrateEngine:rpc       backtrace: null
  prisma:migrateEngine:rpc     }
  prisma:migrateEngine:rpc   },
  prisma:migrateEngine:rpc   id: 1
  prisma:migrateEngine:rpc } +876ms
Error: Error: db error: ERROR: relation "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongB" already exists
   0: sql_migration_connector::sql_database_step_applier::apply_migration
             at migration-engine\connectors\sql-migration-connector\src\sql_database_step_applier.rs:11
   1: migration_core::api::SchemaPush
             at migration-engine\core\src\api.rs:161

    at Object.<anonymous> (C:\Users\Jan\Documents\throwaway\9417\node_modules\prisma\build\index.js:57469:26)
    at MigrateEngine2.handleResponse (C:\Users\Jan\Documents\throwaway\9417\node_modules\prisma\build\index.js:57336:38)
    at LineStream.<anonymous> (C:\Users\Jan\Documents\throwaway\9417\node_modules\prisma\build\index.js:57427:18)
    at LineStream.emit (events.js:400:28)
    at LineStream.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at LineStream.Readable.push (internal/streams/readable.js:204:10)
    at LineStream.Transform.push (internal/streams/transform.js:166:32)
    at LineStream._pushBuffer (C:\Users\Jan\Documents\throwaway\9417\node_modules\prisma\build\index.js:57185:19)
```

Generated SQL:

```
-- CreateTable
CREATE TABLE "Post" (
    "id" SERIAL NOT NULL,

    CONSTRAINT "Post_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER" (
    "id" SERIAL NOT NULL,
    "post_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,

    CONSTRAINT "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotToo_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER_post_id_unique" ON "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER"("post_id");

-- CreateIndex
CREATE UNIQUE INDEX "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER_user_id_unique" ON "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER"("user_id");

-- AddForeignKey
ALTER TABLE "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER" ADD CONSTRAINT "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotToo_fkey" FOREIGN KEY ("post_id") REFERENCES "Post"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotTooLongBUTLONGER" ADD CONSTRAINT "LinkingTableForUserAndPostWithObnoxiouslyLongNameButNotToo_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
```

**Comment by alexmensak** [comment]
We have the same problem. After upaditng to prisma version 3+ we are unable to run prisma migrate dev as it tries to rename all indexes fails on: 


Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 20210930142326_prisma_3

Database error code: 42P07

```
Database error:
ERROR: relation "_BlankArticleVariantToBlankArticleVariantAttributeValue_AB_uniq" already exists

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P07"), message: "relation \"_BlankArticleVariantToBlankArticleVariantAttributeValue_AB_uniq\" already exists", detail: None, hint: None, position: None, where_: None, s
chema: None, table: None, column: None, datatype: None, constraint: None, file: Some("tablecmds.c"), line: Some(3483), routine: Some("RenameRelationInternal") }
```

I see the migration file and this line is problem:
```

-- RenameIndex
ALTER INDEX "_BlankArticleVariantToBlankArticleVariantAttributeValue_AB_uniq" RENAME TO "_BlankArticleVariantToBlankArticleVariantAttributeValue_AB_unique";
```
