### ISSUE TITLE
DateTime doesn't support ISO string with offset

### ISSUE THREAD

**Issue by paulrostorp** [prisma/prisma#9516]
### Bug description

When passing ISO8601 strings with offset information, prisma throws an error.

### How to reproduce

With a Prisma schema:
```graphql
model Task {
  startDate: DateTime @db.Timestampz
}
```

A Zulu ISO8601 string works:
```js
prisma.task.create({
  data: {
    startDate: "2021-09-28T22:00Z"
  }
})
```

A ISO8601 string doesn't
```js
prisma.task.create({
  data: {
    startDate: "2021-09-29T00:00+02:00"
  }
})
```

with the error:
```
Error: Argument startDate: Got invalid value '2021-09-29T00:00+02:00' on prisma.createTask. Provided String, expected DateTime or Null.
```

### Prisma information

```graphql
model Task {
  startDate: DateTime @db.Timestampz
}
```

### Environment & setup

- OS: mac os , m1 chip
- Database: PostgreSQL v13
- Node.js version: node 16

### Prisma Version

v2.30.3

**Comment by aqrln** [comment]
The issue is still reproducible with the latest Prisma version.

Schema:

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "../node_modules/.prisma/client"
}

datasource db {
  provider = "postgresql"
  url      = env("TEST_POSTGRES_URI")
}

model Task {
  id        Int      @id @default(autoincrement())
  startDate DateTime @db.Timestamptz
}
```

Code:

```ts
import { PrismaClient } from '.prisma/client'

async function main() {
  const prisma = new PrismaClient()

  const result = await prisma.task.create({
    data: {
      startDate: '2021-09-29T00:00+02:00',
    },
  })

  console.log(result)
}

void main()
```

Result:

```
/Users/aqrln/prisma/prisma/reproductions/reproductions/gh-9516/node_modules/.prisma/client/runtime/index.js:28989
    const error2 = new PrismaClientValidationError(renderErrorStr(validationCallsite));
                   ^
PrismaClientValidationError: 
Invalid `prisma.task.create()` invocation in
/Users/aqrln/prisma/prisma/reproductions/reproductions/gh-9516/index.ts:6:36

  3 async function main() {
  4   const prisma = new PrismaClient()
  5 
→ 6   const result = await prisma.task.create({
        data: {
          startDate: '2021-09-29T00:00+02:00'
                     ~~~~~~~~~~~~~~~~~~~~~~~~
        }
      })

Argument startDate: Got invalid value '2021-09-29T00:00+02:00' on prisma.createOneTask. Provided String, expected DateTime.


    at Document.validate (/Users/aqrln/prisma/prisma/reproductions/reproductions/gh-9516/node_modules/.prisma/client/runtime/index.js:28989:20)
    at serializationFn (/Users/aqrln/prisma/prisma/reproductions/reproductions/gh-9516/node_modules/.prisma/client/runtime/index.js:31903:19)
    at runInChildSpan (/Users/aqrln/prisma/prisma/reproductions/reproductions/gh-9516/node_modules/.prisma/client/runtime/index.js:25102:12)
    at PrismaClient._executeRequest (/Users/aqrln/prisma/prisma/reproductions/reproductions/gh-9516/node_modules/.prisma/client/runtime/index.js:31910:31)
    at async PrismaClient._request (/Users/aqrln/prisma/prisma/reproductions/reproductions/gh-9516/node_modules/.prisma/client/runtime/index.js:31839:16)
    at async main (/Users/aqrln/prisma/prisma/reproductions/reproductions/gh-9516/index.ts:6:18) {
  clientVersion: '0.0.0'
}
```

The regular expression that decides if a string is a valid date somewhere in `query.ts` doesn't match an ISO string with offset, which needs to be fixed.

The workaround is to pass a Date instead of a string:

```diff
   const result = await prisma.task.create({
     data: {
-      startDate: '2021-09-29T00:00+02:00',
+      startDate: new Date('2021-09-29T00:00+02:00'),
     },
   })
```

**Comment by Sameerthe-Big-O** [comment]
As of 2024 this is still here I want to store the simple date and currently passing the Iso format based string
`
 DateFound    DateTime @db.Date
`
`
 DateFound    DateTime 
`
in the both cases when I pass the string  `1990-05-06`

I'd get the same error

**Comment by Gerotha** [comment]
> As of 2024 this issue is still here I want to store the simple date and currently passing the Iso format based string
> 
> `DateFound DateTime @db.Date` `DateFound DateTime ` in both cases when I pass the string `1990-05-06` which's the standard iso date format I still the same error
> 
> `nInvalid value for argument `DateFound`: premature end of input. Expected ISO-8601 DateTime.`

Any news?
I'm having the same issue 😞

**Comment by R1NEJ0** [comment]
Same issue here

**Comment by hidayatridwan** [comment]
Same issue here

**Comment by ElBonds** [comment]
I'm having the same issue as well.

**Comment by matheusvellone** [comment]
The typings also allows the `string` type. Any dev that relies on TS types (probably most of us) may be surprised by this bug.

Is this error from prisma itself? If so, is there anything blocking it from being fixed? (despite time maybe)

**Comment by cofidoc** [comment]
same error here  "2011-08-30" =>  premature end of input. Expected ISO-8601 DateTime."

**Comment by Vincz** [comment]
Same issue! Keep getting this error event if I convert the string to a javascript Date before inserting.

**Comment by seamuncle** [comment]
Someone with more time and gumption then I... this is probably the regex you want (assuming regex is still the desired way to do this, and not just applying a parser) ...
```regex
^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$
```
(courtesy  https://www.myintervals.com/blog/iso-8601-date-validation/ with excellent explanation )

Anyone wondering where to apply this regex... https://github.com/prisma/prisma/blob/f36e3064a3f64975e74c4680a62ad541699741ec/packages/adapter-d1/src/conversion.ts#L66 and have fun with your PR

**Comment by jamiter** [comment]
Something to consider:

The [new JS native Temporal object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal) has support for all these date types and would be a perfect fit.

It's getting closer and closer to actual release and I hope it will be considered as the future API for any Date related features.

**Comment by andrecasal** [comment]
Another upvote for considering incorporating the Temporal API objects into Prisma.

This would make date and time handling considerably simpler with Prisma.
