### ISSUE TITLE
`db push` with empty `schema.prisma`: `Error: TypeError: Cannot read properties of undefined (reading 'url')`

### ISSUE THREAD

**Issue by janpio** [prisma/prisma#9518]
Running `db push` with an empty schema file leads to this suboptimal error message:

```
λ npx prisma db push
Need to install the following packages:
  prisma
Ok to proceed? (y) y
  prisma:loadEnv skipping package.json at C:\Users\Jan\Documents\throwaway\9184repro\foo\package.json +0ms
  prisma:loadEnv project root found at C:\Users\Jan\Documents\throwaway\9184repro\package.json +4ms
  prisma:tryLoadEnv Environment variables not found at null +0ms
  prisma:tryLoadEnv Environment variables not found at undefined +3ms
  prisma:tryLoadEnv No Environment variables loaded +9ms
  prisma:engines binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from schema.prisma
  prisma:getConfig Using CLI Query Engine (Node-API Library) at: C:\Users\Jan\AppData\Local\npm-cache\_npx\2778af9cee32ff87\node_modules\@prisma\engines\query_engine-windows.dll.node +0ms
Error: TypeError: Cannot read properties of undefined (reading 'url')
    at getDbInfo (C:\Users\Jan\AppData\Local\npm-cache\_npx\2778af9cee32ff87\node_modules\prisma\build\index.js:62954:34)
    at async printDatasource (C:\Users\Jan\AppData\Local\npm-cache\_npx\2778af9cee32ff87\node_modules\prisma\build\index.js:64502:20)
    at async _DbPush.parse (C:\Users\Jan\AppData\Local\npm-cache\_npx\2778af9cee32ff87\node_modules\prisma\build\index.js:66357:7)
    at async main (C:\Users\Jan\AppData\Local\npm-cache\_npx\2778af9cee32ff87\node_modules\prisma\build\index.js:112748:18)
```

Found via https://github.com/prisma/prisma/issues/9517

**Comment by do4gr** [comment]
This won't be a problem once we switch more commands to the Json RPC API.
