### ISSUE TITLE
Missing schema.prisma in lambda layer

### ISSUE THREAD

**Issue by revmischa** [prisma/prisma#9520]
I'm using 3.1.1 with NPM v7 workspaces -
It’s not running properly in my lambda function/layer setup. I get the error `ENOENT: no such file or directory, open '/var/task/schema.prisma'`
Can I at least tell it what path my schema.prisma file is at somehow? I couldn’t find anything in the [docs](https://www.prisma.io/docs/reference/api-reference/environment-variables-reference#engine-environment-variables). I have the file in a lambda layer (/opt/nodejs/prisma)

<img width="349" alt="Screenshot 2021-09-29 at 18 53 50" src="https://user-images.githubusercontent.com/245131/135304752-f8bc1070-7a37-47c8-947f-2e2f27e34429.png">

Additionally, it seems like in Prisma 3 it now is trying to find the schema.prisma file when I import the file that constructs my prisma client (`new PrismaClient()`), whereas before it didn’t do that. This is a problem for me because some of my lambda functions are set up to use prisma (with secrets, layer, network access to the DB, etc) and some aren’t but still import files which import the prisma client. So now I can’t start the functions that don’t have anything to do with prisma because it explodes saying it can't find `schema.prisma` even though I have no intention of using it in that function.

```
    "stack": [
        "Error: ENOENT: no such file or directory, open '/var/task/schema.prisma'",
        "    at Object.openSync (fs.js:498:3)",
        "    at Object.readFileSync (fs.js:394:35)",
        "    at new LibraryEngine (/var/task/index.js:139195:46)",
        "    at PrismaClient.getEngine (/var/task/index.js:151600:20)",
        "    at new PrismaClient (/var/task/index.js:151569:33)",
        "    at packages/repo/build/client.js (/var/task/index.js:156432:18)",
        "    at __require (/var/task/index.js:38:45)",
        "    at packages/repo/build/index.js (/var/task/index.js:187999:20)",
        "    at __require (/var/task/index.js:38:45)",
        "    at packages/domain/build/auth/user/invite.js (/var/task/index.js:233728:27)"
    ]
```

Ideally the engine would lazily load the library engine when I actually need it and I could tell it where to find the schema prisma file. 

Even better would be if it searched up from the `node_modules` dir (which lives in the layer) until it found a `prisma` dir and then looked in there for the schema file.

_Originally posted by @revmischa in https://github.com/prisma/prisma/issues/9435#issuecomment-930308899_

**Comment by janpio** [comment]
> Additionally, it seems like in Prisma 3 it now is trying to ...

This makes it sound like you were using Prisma 2.x before - was the difference in behavior only towards that second part of your message or also about using npm workspaces in general? Which version did your setup still work, and where exactly did it break? Can you set up a minimal reproduction to help us understand what is going on and put it on GitHub?

**Comment by s97712** [comment]
Did you regenerate the client before testing?

**Comment by revmischa** [comment]
> > Additionally, it seems like in Prisma 3 it now is trying to ...
> 
> This makes it sound like you were using Prisma 2.x before - was the difference in behavior only towards that second part of your message or also about using npm workspaces in general? Which version did your setup still work, and where exactly did it break? Can you set up a minimal reproduction to help us understand what is going on and put it on GitHub?

Yes my setup was working with Prisma 2.x but not 3.x. I am generating a prisma lambda layer for all of my functions that includes the various @prisma/.prisma/prisma node_modules and my prisma directory containing my schema and prisma-appsync files. The source code of the layer is [here](https://github.com/jetbridge/jetkit-cdk/blob/master/src/cdk/lambda/prismaLayer.ts).

Upgrading to 3.x broke my functions that import my file that constructs the prisma client as [described in the docs.](https://www.prisma.io/docs/concepts/components/prisma-client#3-use-prisma-client-to-send-queries-to-your-database).

As far as I can see even my functions which don't need prisma are constructing a new `PrismaClient` instance simply by means of importing this file. In version 2.x this was okay because merely constructing the client didn't throw an error if it couldn't find the prisma schema file. That appears to have changed.



> Did you regenerate the client before testing?

I did; I have a `postinstall` hook to make sure it's up to date and the prisma layer does so as well [when packaging](https://github.com/jetbridge/jetkit-cdk/blob/master/src/cdk/lambda/prismaLayer.ts#L130).

**Comment by revmischa** [comment]
I'm working around this issue with:
```
 // FIXME: https://github.com/prisma/prisma/issues/9520
        commandHooks: {
          afterBundling: () => [],
          beforeInstall: () => [],
          beforeBundling: (inputDir: string, outputDir: string) => [
            `cp ${inputDir}/packages/repo/prisma/schema.prisma ${outputDir}`,
          ],
        },
```
And looking into lazily loading (maybe with dependency injection) my `PrismaClient` instance when it's actually needed.

I wonder if the documentation example of importing `client` into any package is not best practice since the mere act of importing that file containing it causes some work to happen. It means any lambda function that might possibly import that files needs the lambda schema, engine, and DATABASE_URL, even if that function never talks to the DB.

Maybe wrapping the client in a lazy getter of some sort would be better advice so as to not run into this situation.

**Comment by Jason-Abbott** [comment]
I am getting the same error auto-deploying to Vercel from an npm 7 workspace. Everything works fine locally. The install and generate steps work fine on Vercel. It's a successful deploy. This only happens when executing the Vercel function.

I don't want to step on @revmischa 's question if this isn't much related. I'll share more details if it's useful.
```
[GET] / 21:19:10:31 2021-10-01T03:19:11.064Z
Error: ENOENT: no such file or directory, open '/var/task/schema.prisma'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at new LibraryEngine (/var/task/index.js:35249:46)
    at PrismaClient.getEngine (/var/task/index.js:47687:20)
    at new PrismaClient (/var/task/index.js:47656:33) 
    at Object.<anonymous> (/var/task/index.js:50679:8)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10) 
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
 {  errno: -2,  syscall: 'open',  code: 'ENOENT',  path: '/var/task/schema.prisma',  clientVersion: '3.1.1'}
```

**Comment by revmischa** [comment]
This is what I'm doing right now for my app:

`packages/repo/src/client.ts`:
```ts
import path from "path"
import dotenv from "dotenv-flow"
import { LazyInstance } from "@selfage/lazy_instance"

// loads DATABASE_URL for local development
// this should be loaded automatically by prisma but may
// not be when running one-off scripts
dotenv.load(path.join(__dirname, "..", "prisma", ".env"), { silent: true })

import { PrismaClient } from "@prisma/client"
const prisma = new LazyInstance(() => new PrismaClient())

export { prisma, PrismaClient }
```

`packages/repo/src/repository/base.ts`:
```ts
import { PrismaClient, User } from ".prisma/client"
import { prisma } from "../client"
import { LazyInstance } from "@selfage/lazy_instance"

export type LazyPrismaInstance = LazyInstance<PrismaClient>

const isLazyPrismaClient = (prismaClient: LazyPrismaInstance | PrismaClient): prismaClient is LazyPrismaInstance =>
  prismaClient instanceof LazyInstance

/**
 * Base class for repositories.
 */
export class RepositoryBase {
  lazyPrisma: LazyPrismaInstance | PrismaClient

  constructor(prismaClient?: LazyPrismaInstance | PrismaClient) {
    this.lazyPrisma = prismaClient || prisma
  }

  get prisma(): PrismaClient {
    if (isLazyPrismaClient(this.lazyPrisma)) return this.lazyPrisma.get()
    else return this.lazyPrisma
  }
}
```

It seems to work well at preventing any top-level prisma client imports or Repository instantiations from loading the full `PrismaClient` until I actually need it. This works pretty well for AWS lambda in a larger project.

**Comment by revmischa** [comment]
Also I have to add this to my environment:
```ts
      PRISMA_QUERY_ENGINE_LIBRARY:
        "/opt/nodejs/node_modules/@prisma/engines/libquery_engine-rhel-openssl-1.0.x.so.node",
```
Would be cool if prisma could find it automatically when loading modules from a lambda layer (i.e. a node_modules dir outside the project root)

**Comment by Jason-Abbott** [comment]
@revmischa That was helpful for me too. Thanks. For the same effect I did
```js
import pkg, { PrismaClient } from '@prisma/client'

let c: PrismaClient | undefined

export const db = {
	// Client instantiation must be lazy to avoid Lambda error
	// https://github.com/prisma/prisma/issues/9520
	//
	// Reference must differ for production to handle ES module build
	// https://github.com/prisma/prisma/pull/4920#issuecomment-927334909
	get client(): PrismaClient {
		if (c === undefined) {
			if (process.env.NODE_ENV === 'production') {
				const { PrismaClient: PrismaClientProd } = pkg
				c = new PrismaClientProd()
			} else {
				c = new PrismaClient()
			}
		}
		return c
	}
}
```
which I use elsewhere as `db.client.<whatever>`.

I think the `PRISMA_QUERY_ENGINE_LIBRARY` setting could solve my `postinstall` requirement on Vercel but after a few tries, I couldn't divine the right path so for now will stick with the seemingly redundant `npm i -D prisma@3.1.1`.

**Comment by Jason-Abbott** [comment]
That did not work. ⬆️ It did allow the Vercel function to load without error (so the site can load) but as soon as `db.client` is referenced, it just throws the same
```json
{"errno":-2,"syscall":"open","code":"ENOENT","path":"/var/task/schema.prisma","clientVersion":"3.1.1"}
```

**Comment by natevaughan** [comment]
I'm running into this when using SvelteKit on Vercel and hitting a serverless function in SvelteKit's `api` directory:

```
Error: ENOENT: no such file or directory, open '/var/task/schema.prisma'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at new LibraryEngine (/var/task/index.js:48098:44)
    at PrismaClient.getEngine (/var/task/index.js:51308:20)
    at new PrismaClient (/var/task/index.js:51279:33)
    at Object.<anonymous> (/var/task/index.js:53931:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
 {  errno: -2,  syscall: 'open',  code: 'ENOENT',  path: '/var/task/schema.prisma',  clientVersion: '3.6.0'}
```

**Comment by field123** [comment]
Running into the same error as @natevaughan SvelteKit but on Netlify instead of Vercel.

**Comment by ptya** [comment]
@natevaughan @field123 I also was facing this issue and copying over the `postbuild` script from this example solved the issue for me: [https://github.com/mikenikles/sveltekit-prisma/blob/main/package.json](https://github.com/mikenikles/sveltekit-prisma/blob/main/package.json)

**Comment by olup** [comment]
Hi, I am trying to deploy a serverless monorepo with yarn 1.x and prisma as a lambda layer. Prisma is looking for my schema, and my schema is located in the layer, so in /opt/nodejs - and so I am getting exactly this error.

I don't think that it was answered : is there a way to specify  - with an environment variable for instance - to the engine where it should look for the schema file ? 

Thanks for your help

**Comment by kettanaito** [comment]
Experiencing the same issue with Turborepo + Remix + Prisma. 

Adding the `vercel-build` or `postbuild` scripts from [here](https://github.com/mikenikles/sveltekit-prisma/blob/b497fbcd6e912c20388a5a7ee3a67b186b9af8ae/package.json) does not help. I have the `clients` repo generating the Prisma client, but when it comes to building the frontend repo, the Prisma client is gone (cannot be required in the edge function).

**Comment by krystian50** [comment]
Try using in your `prisma.schema`:
```
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
  engineType    = "binary"
}
```

**Comment by isnothenrique** [comment]
Im having the same issue, anybody solved this?

**Comment by Markkos89** [comment]
Facing the same issue here. With a nx serverless monorepo with serverless framework typescript and serverless-esbuild.
I also have my files in a Layer wich I can't "call" (yet) from the lambda... 

Any help would be much appreciated!

**Comment by natevaughan** [comment]
Solution for me (SvelteKit on Vercel) was adding the following line to the `scripts` block of `package.json`:
```
"postbuild": "cp node_modules/@prisma/engines/*query* .vercel_build_output/functions/node/render/; cp prisma/schema.prisma .vercel_build_output/functions/node/render/; ls .vercel_build_output/functions/node/render/"
```

**Comment by revmischa** [comment]
Related: #14484

**Comment by js-sapphire** [comment]
Facing the same issue in a nodeJs lambda repository using architect. Can someone tell me why PrismaClient looks for schema.prisma when it is already generated. Why does it need to look into the file which was used to extend its interface? I haven't deployed my lambda yet. I am running a sandbox using [arc sandbox](https://arc.codes/docs/en/reference/cli/sandbox). My directory structure looks like
<img width="351" alt="image" src="https://user-images.githubusercontent.com/41758940/185562176-aa4128d4-2f3f-4a94-a9cf-43e255f2690e.png">
I have a postinstall script `prisma generate` and when I build them, I get an http folder with different lambda handlers in different folders. For example, if there are two apis read-posts and create-post, whenever I try to hit either of them, I get an error saying `no file or directory in .build/http/read-posts/schema.prisma` 
Does it mean every built lambda handler folder must house a schema.prisma too? 
But isn't prisma generate step a build-time step? Why is this happening runtime?

**Comment by janpio** [comment]
The types are generated, some other things are created on construction of PrismaClient and for that theschema file is currently read.

**Comment by janpio** [comment]
Hey everyone here. We are currently working through these errors and problems, and there is something we need to point out here before we dig in: 

Prisma Client _never_ tries to load your **original** `schema.prisma` file from where you generated the Client. That file is only relevant for CLI usage and when you run `prisma generate`. Later, the generated Client has a _copy_ of the schema file that it reads and hands over to the Query Engine so it knows about the models and their fields and types. The `ENOENT schema.prisma` error message is about the Client not finding that file at the expected location (mostly right next to itself) when it starts. 

(We could in theory [inline the schema file into our JS code](https://github.com/prisma/prisma/issues/13052) to avoid this error. Then the next line in our code that searches and loads the Query Engine would fail in exactly the same way. We need to fundamentally solve the underlying problem.)

---

That out of the way:

These problems are most probably caused by bundlers not copying the full generated Prisma Client to the new location and skipping the schema file, or rewriting/bundling/moving the code of Prisma Client in a way that the schema file copy is not in the expected location either.

Optimally each of you could provide a reproduction with a simplified version of your project, and post it into a new issue and then drop a link to that issue here. Currently, we already have a workaround for Monorepo + Next.js + Prisma that works. We are pretty confident we will also find one for others.

(I would be especially interesting in reproductions from @natevaughan @field123 @ptya @olup @kettanaito @Markkos89 @js-sapphire as those are combinations we are not aware of yet. The workaround mentioned in some of your answers should _not_ be necessary.)

**Comment by 6eyu** [comment]
```Error: ENOENT: no such file or directory, open '/var/task/schema.prisma'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at new LibraryEngine (/var/task/index.js:4891:37)
    at t.getEngine (/var/task/index.js:7386:20)
    at new PrismaClient (/var/task/index.js:7368:1069)
    at /var/task/index.js:7983:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Runtime.handler (/var/task/index.js:7999:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/task/schema.prisma',
  clientVersion: '4.10.1'
}```

I am trying to make a prisma lambda layer on AWS. It throw me this error when I try to get `new PrismaClient()`.  I check the layer zip folder that contains `node_moodules` with @prisma/client
