### ISSUE TITLE
interactiveTransactions rollback but don't error out if timeout is reached

### ISSUE THREAD

**Issue by awinograd** [prisma/prisma#9533]
### Bug description

When using interactive transactions, the transaction returns successfully even if the timeout was reached and internally the transaction was rolled back.

More context here https://github.com/prisma/prisma/issues/8664#issuecomment-930403241

### How to reproduce

1. Clone https://github.com/awinograd/prisma-include-clause-bug/tree/interactive-transaction-timeout (note it is a specific branch, not main branch)
2. run `yarn dev:database`
3. run `prisma migrate dev`
4. run `yarn dev`

### Expected behavior

Transaction that surpasses `timeout` should throw an error rather than returning the return value as if nothing has happened.

### Prisma information

all included in repro example above

### Environment & setup

- OS: MacOS
- Database: PostgresQL
- Node.js version: 16.9.1

### Prisma Version

```
prisma                  : 3.1.1
@prisma/client          : 3.1.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt c22652b7e418506fab23052d569b85d3aec4883f (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : c22652b7e418506fab23052d569b85d3aec4883f
Studio                  : 0.423.0
Preview Features        : interactiveTransactions
```

**Comment by pantharshit00** [comment]
I can reproduce this. Thanks for the detailed report.

**Comment by garrensmith** [comment]
From what I can see on this. The issue is here https://github.com/prisma/prisma/blob/ec0a0182bd81f82b70d1a12a48bd7a523300a5b9/packages/engine-core/src/library/LibraryEngine.ts#L120

The query-engine will never throw an actual error but will return an error object:
```json
{
  "is_panic":false,
  "message":"Transaction API error: Transaction already closed: Transaction is no longer valid. Last state: 'Expired'.",
   "meta":{
        "error":"Transaction already closed: Transaction is no longer valid. Last state: 'Expired'."
    },
 "error_code":"P2028"
}
```

We need to check the response and throw an error if we detect it. We need to do the same for rollback

**Comment by matthewmueller** [comment]
PR ready for review: https://github.com/prisma/prisma/pull/10797

**Comment by livthomas** [comment]
I think I've also run into this issue. When I turn on `interactiveTransactions` preview feature, a long-running transaction invoked the old way (`prisma.$transaction([...])`) suddenly starts failing with this error:
```
[0] prisma:info Starting a sqlite pool with 9 connections.
[0] PrismaClientKnownRequestError: 
[0] Invalid `prisma_1.prisma.contract.create()` invocation in
[0] /home/livthomas/Projects/livthomas/pawnshop-next/build/main/legacy/contract/importLegacyContractRecords.js:15:41
[0] 
[0]   12 const userPasswordsMap = await (0, createUserHashedPasswordsMap_1.createUserHashedPasswordsMap)(userNames);
[0]   13 const operations = results.map(result => {
[0]   14     const data = (0, convertLegacyRecordToContract_1.convertLegacyRecordToContract)(result, userPasswordsMap, archived);
[0] → 15     return prisma_1.prisma.contract.create(
[0]   Transaction API error: Transaction already closed: Transaction is no longer valid. Last state: 'Expired'.
[0]     at Object.request (/home/livthomas/Projects/livthomas/pawnshop-next/node_modules/@prisma/client/runtime/index.js:39054:15)
[0]     at async Promise.all (index 0)
[0]     at async PrismaClient._transactionWithCallback (/home/livthomas/Projects/livthomas/pawnshop-next/node_modules/@prisma/client/runtime/index.js:39655:18)
[0]     at async importLegacyContractRecords (/home/livthomas/Projects/livthomas/pawnshop-next/build/main/legacy/contract/importLegacyContractRecords.js:17:5)
[0]     at async reportLegacyTableImportStatus (/home/livthomas/Projects/livthomas/pawnshop-next/build/main/legacy/reportLegacyTableImportStatus.js:34:9)
[0]     at async importLegacyDatabase (/home/livthomas/Projects/livthomas/pawnshop-next/build/main/legacy/importLegacyDatabase.js:27:20)
[0]     at async electron/js2c/browser_init.js:197:563 {
[0]   code: 'P2028',
[0]   clientVersion: '3.8.0',
[0]   meta: {
[0]     error: "Transaction already closed: Transaction is no longer valid. Last state: 'Expired'."
[0]   }
[0] }

```

This transaction works without any problems when this preview feature is disabled and its execution usually takes around 30 seconds.

I'm using SQLite database.
