### ISSUE TITLE
PANIC: Could not figure out an ID in create in query-engine/connectors/sql-query-connector/src/database/operations/write.rs:73:22

### ISSUE THREAD

**Issue by hossamxp33** [prisma/prisma#9838]
Hi Prisma Team! My Prisma Client just crashed. This is the report:
## Versions

| Name            | Version            |
|-----------------|--------------------|
| Node            | v14.18.0           | 
| OS              | rhel-openssl-1.0.x |
| Prisma Client   | 3.2.1              |
| Query Engine    | 0.1.0              |
| Database        | mysql              |

## Logs
```
ync cb (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:38705:26)
    at async main (/home/codesroots/satafood.codesroots.com/Controllers/Cities.js:28:20)
prisma:client:libraryEngine library stopping
prisma:client:libraryEngine library stopped
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine graphQLToJSError
prisma:client:fetcher Error: Could not figure out an ID in create
    at LibraryEngine.prismaGraphQLToJSError (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:26923:14)
    at LibraryEngine.request (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:26938:24)
    at async cb (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:38705:26)
    at async main (/home/codesroots/satafood.codesroots.com/Controllers/Cities.js:28:20)
prisma:client:libraryEngine library stopping
prisma:client:libraryEngine library stopped
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine graphQLToJSError
prisma:client:fetcher Error: Could not figure out an ID in create
    at LibraryEngine.prismaGraphQLToJSError (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:26923:14)
    at LibraryEngine.request (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:26938:24)
    at async cb (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:38705:26)
    at async main (/home/codesroots/satafood.codesroots.com/Controllers/Cities.js:28:20)
prisma:client:libraryEngine library stopping
prisma:client:libraryEngine library stopped
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine graphQLToJSError
prisma:client:fetcher Error: Foreign key constraint failed on the field: `city_id`
    at LibraryEngine.prismaGraphQLToJSError (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:26921:16)
    at LibraryEngine.request (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:26938:24)
    at async cb (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:38705:26)
    at async main (/home/codesroots/satafood.codesroots.com/Controllers/Cities.js:28:20)
prisma:client:libraryEngine library stopping
prisma:client:libraryEngine library stopped
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine graphQLToJSError
prisma:client:fetcher Error: Foreign key constraint failed on the field: `city_id`
    at LibraryEngine.prismaGraphQLToJSError (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:26921:16)
    at LibraryEngine.request (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:26938:24)
    at async cb (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:38705:26)
    at async main (/home/codesroots/satafood.codesroots.com/Controllers/Cities.js:28:20)
prisma:client:libraryEngine library stopping
prisma:client:libraryEngine library stopped
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
prisma:client:libraryEngine graphQLToJSError
prisma:client:fetcher Error: Could not figure out an ID in create
    at LibraryEngine.prismaGraphQLToJSError (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:26923:14)
    at LibraryEngine.request (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:26938:24)
    at async cb (/home/codesroots/satafood.codesroots.com/node_modules/@prisma/client/runtime/index.js:38705:26)
    at async main (/home/codesroots/satafood.codesroots.com/Controllers/Cities.js:28:20)
prisma:client:libraryEngine library stopping
prisma:client:libraryEngine library stopped
prisma:client:libraryEngine sending request, this.libraryStarted: false
prisma:client:libraryEngine library starting
prisma:client:libraryEngine library started
```

## Client Snippet
```ts
// PLEASE FILL YOUR CODE SNIPPET HERE
```

## Schema
```prisma
// PLEASE ADD YOUR SCHEMA HERE IF POSSIBLE
```

## Prisma Engine Query
```
{"X":{}}
```

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
