### ISSUE TITLE
generate client code error 

### ISSUE THREAD

**Issue by 779102260** [prisma/prisma#9887]
### Bug description

`output` config generate code error

### How to reproduce

1. set `ouput`
```ts
generator client {
  provider = "prisma-client-js"
  output   = "./client"
}

datasource db {
  provider = "sqlite"
  url      = "file:./sqlite3.db"
}
```

2. generate client
```
cd src/prisma
npx prisma generate
```

3. run code

src/prisma/prisma.ts
```
import { PrismaClient } from './client'
export default new PrismaClient()
```
```
ts-node src/prisma/prisma.ts
```

4. get error
```
Error: ENOENT: no such file or directory, open '/Users/nowcoder/project/icon-manager/.git/schema.prisma'
    at Object.openSync (node:fs:505:3)
    at Object.readFileSync (node:fs:401:35)
    at new LibraryEngine (/Users/nowcoder/project/icon-manager/src/prisma/client/runtime/index.js:36078:40)
    at PrismaClient.getEngine (/Users/nowcoder/project/icon-manager/src/prisma/client/runtime/index.js:39108:16)
    at new PrismaClient (/Users/nowcoder/project/icon-manager/src/prisma/client/runtime/index.js:39079:29)
    at Object.<anonymous> (/Users/nowcoder/project/icon-manager/src/prisma/prisma.ts:3:16)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1313:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/nowcoder/project/icon-manager/.git/schema.prisma',
  clientVersion: '3.3.0'
}
```

5. generate client dir path error, here the code

src/prisma/client/index.js
```js
const dirname = findSync(process.cwd(), [
    "client",
    "", // <--- match every dir
], ['d'], ['d'], 1)[0] || __dirname
```

### Environment & setup

- OS: Mac OS
- Database: SQLite
- Node.js version: v15.13.0

### Prisma Version

"prisma": "^3.3.0",
 "@prisma/client": "^3.3.0",

**Comment by janpio** [comment]
What does your project setup look like?
Can you possibly create a minimal reproduction project that makes it easy for us to experience this error?

**Comment by qauff** [comment]
I'm having the same issue, using `ts-node` to run my `seed.ts` and in it I use the generated prisma client to access the DB.

```
import { PrismaClient } from './lib'
```

This is the error I get:

```
Running seed command `npx ts-node ./seed.ts` ...
Error: ENOENT: no such file or directory, open '{MY_WORKING_DIR}/.git/schema.prisma'
```

**Comment by pantharshit00** [comment]
I am going to close this as its been 3 months now and there is no activity here. 

Please reply if you want us to take another look.
