### ISSUE TITLE
Unique constraint failed with connectOrCreate

### ISSUE THREAD

**Issue by austincrim** [prisma/prisma#9891]
### Discussed in https://github.com/prisma/prisma/discussions/9871

<div type='discussions-op-text'>

<sup>Originally posted by **ptrkcsk** October 20, 2021</sup>
Can anyone help with this? I'm not sure if this is a bug or user error, so I'm posting it here first. My gut says it has something to do with floating point fun.

## Actual behavior

Creating an item with a nested `connectOrCreate` fails because Prisma's `SELECT` fails to return a record even though it exists

## Steps to reproduce

1. Clone this test case repo: https://github.com/ptrkcsk/prisma-decimal
1. Follow the instructions in the readme

## Expected behavior

Prisma will find the record and connect it instead of trying to create a duplicate record

### Schema

```prisma
model Item {
  id   Int    @id @default(autoincrement())
  name String

  location   Location? @relation(fields: [locationId], references: [id])
  locationId Int       @map("location_id")

  @@map("item")
}

model Location {
  id  Int     @id @default(autoincrement())
  lat Decimal @db.Decimal(11, 8)
  lon Decimal @db.Decimal(11, 8)

  @@unique([lat, lon])
  @@map("location")
  Item Item[]
}
```

### Client query

```ts
const lat = 41.658
const lon = -70.2981

await prisma.item.create({
  data: {
    name: 'Test 1',
    location: {
      connectOrCreate: {
        create: { lat, lon },
        where: { lat_lon: { lat, lon } }
      }
    }
  }
})

await prisma.item.create({
  data: {
    name: 'Test 2',
    location: {
      connectOrCreate: {
        create: { lat, lon },
        where: { lat_lon: { lat, lon } }
      }
    }
  }
})
```

### Logs

```
prisma:query: BEGIN
  params: []
prisma:query: SELECT "public"."location"."id" FROM "public"."location" WHERE ("public"."location"."lat" = $1 AND "public"."location"."lon" = $2) OFFSET $3
  params: [41.65800000000000,-70.29810000000001,0]
prisma:query: INSERT INTO "public"."location" ("lat","lon") VALUES ($1,$2) RETURNING "public"."location"."id"
  params: [41.65800000000000,-70.29810000000001]
prisma:query: INSERT INTO "public"."item" ("name","location_id") VALUES ($1,$2) RETURNING "public"."item"."id"
  params: ["Test 1",1]
prisma:query: SELECT "public"."item"."id", "public"."item"."name", "public"."item"."location_id" FROM "public"."item" WHERE "public"."item"."id" = $1 LIMIT $2 OFFSET $3
  params: [1,1,0]
prisma:query: COMMIT
  params: []
prisma:query: BEGIN
  params: []
prisma:query: SELECT "public"."location"."id" FROM "public"."location" WHERE ("public"."location"."lat" = $1 AND "public"."location"."lon" = $2) OFFSET $3
  params: [41.65800000000000,-70.29810000000001,0]
prisma:query: INSERT INTO "public"."location" ("lat","lon") VALUES ($1,$2) RETURNING "public"."location"."id"
  params: [41.65800000000000,-70.29810000000001]
prisma:query: ROLLBACK
  params: []
(node:13983) UnhandledPromiseRejectionWarning: Error: 
Invalid `prisma.item.create()` invocation in
/Users/patrikcsak/Dev/ptrkcsk/prisma-decimal/main.ts:30:21

  27   }
  28 })
  29 
→ 30 await prisma.item.create(
  Unique constraint failed on the fields: (`lat`,`lon`)
```

Notice that `-70.2981` becomes `-70.29810000000001` in Prisma's generated queries. It seems likely to me that this is the problem.

When I execute the queries manually, the `SELECT` fails to return a record:

```sql
SELECT location.id FROM location WHERE (lat = 41.65800000000000 AND lon = -70.29810000000001) OFFSET 0;
```

But the `INSERT` fails because the record already exists:

```sql
INSERT INTO location (lat,lon) VALUES (41.65800000000000,-70.29810000000001) RETURNING location.id;
```

```
[23505] ERROR: duplicate key value violates unique constraint "location_lat_lon_key" Detail: Key (lat, lon)=(41.65800000, -70.29810000) already exists.
```

The `SELECT` query works as expected if I shorten the values to 8 digits after the decimal point:

```sql
SELECT location.id FROM location WHERE (lat = 41.65800000 AND lon = -70.29810000) OFFSET 0;
```

## Environment & setup

- OS: macOS v11.6 (Big Sur)
- Database: PostgreSQL @ latest (v14.0 I think)
- Node.js: v14.18.1

## Prisma version

```
prisma                  : 3.3.0
@prisma/client          : 3.3.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 33838b0f78f1fe9052cf9a00e9761c9dc097a63c (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 33838b0f78f1fe9052cf9a00e9761c9dc097a63c
Studio                  : 0.437.0
```</div>

**Comment by janpio** [comment]
To recap: The expectation here is that the existing `location` is used in the second query instead of creating a new one (which fails of course). Cause seems to be a mismatch in the value used to `SELECT` vs. what was inserted before.

**Comment by ptrkcsk** [comment]
> Can you confirm this works @ptrkcsk?

Yes, I can confirm that using strings works

**Comment by AgusVelez5** [comment]
+1 Here, I have the same problem but instead a float unique value I have an int unique value
`levelNumber  Int       @unique`

**Comment by Jolg42** [comment]
Note: can reproduce in `3.3.0` and also with our internal dev version `4.4.0-dev.25`
```
> ts-node main

prisma:query: TRUNCATE TABLE item, location RESTART IDENTITY;
  params: []
prisma:query: BEGIN
  params: []
prisma:query: SELECT "public"."location"."id" FROM "public"."location" WHERE ("public"."location"."lat" = $1 AND "public"."location"."lon" = $2) OFFSET $3 /* traceparent=00-00-00-00 */
  params: [41.65800000000000,-70.29810000000001,0]
prisma:query: INSERT INTO "public"."location" ("lat","lon") VALUES ($1,$2) RETURNING "public"."location"."id" /* traceparent=00-00-00-00 */
  params: [41.65800000000000,-70.29810000000001]
prisma:query: INSERT INTO "public"."item" ("name","location_id") VALUES ($1,$2) RETURNING "public"."item"."id" /* traceparent=00-00-00-00 */
  params: ["Test 1",1]
prisma:query: SELECT "public"."item"."id", "public"."item"."name", "public"."item"."location_id" FROM "public"."item" WHERE "public"."item"."id" = $1 LIMIT $2 OFFSET $3 /* traceparent=00-00-00-00 */
  params: [1,1,0]
prisma:query: COMMIT
  params: []
prisma:query: BEGIN
  params: []
prisma:query: SELECT "public"."location"."id" FROM "public"."location" WHERE ("public"."location"."lat" = $1 AND "public"."location"."lon" = $2) OFFSET $3 /* traceparent=00-00-00-00 */
  params: [41.65800000000000,-70.29810000000001,0]
prisma:query: INSERT INTO "public"."location" ("lat","lon") VALUES ($1,$2) RETURNING "public"."location"."id" /* traceparent=00-00-00-00 */
  params: [41.65800000000000,-70.29810000000001]
prisma:query: ROLLBACK
  params: []
/Users/j42/Repros/prisma-decimal/node_modules/@prisma/client/runtime/index.js:30850
      throw new PrismaClientKnownRequestError(message, error2.code, this.client._clientVersion, error2.meta);
            ^
PrismaClientKnownRequestError: 
Invalid `prisma.item.create()` invocation in
/Users/j42/Repros/prisma-decimal/main.ts:30:21

  27   }
  28 })
  29 
→ 30 await prisma.item.create(
Unique constraint failed on the fields: (`lat`,`lon`)
    at RequestHandler.handleRequestError (/Users/j42/Repros/prisma-decimal/node_modules/@prisma/client/runtime/index.js:30850:13)
    at RequestHandler.request (/Users/j42/Repros/prisma-decimal/node_modules/@prisma/client/runtime/index.js:30833:12)
    at async PrismaClient._request (/Users/j42/Repros/prisma-decimal/node_modules/@prisma/client/runtime/index.js:31805:16) {
  code: 'P2002',
  clientVersion: '4.4.0-dev.25',
  meta: { target: [ 'lat', 'lon' ] }
}
```
